### ISSUE TITLE
Impossible d'effectuer une recherche visuelle 

### ISSUE THREAD

**Issue by moh-verratti** [Kodi-vStream/venom-xbmc-addons#1003]
Bonjour, 
Désolé pour la description mais je suis depuis mon téléphone
J'ai un problème avec la recherche visuelle depuis quelques temps et je n'arrive pas à le résoudre. 

Lorsque je passe par la recherche visuelle sur n'importe quelle catégorie j'ai une erreur "Erreur Vstream :consulter le journal pour plus d'informations" 

J'ai uploadé mes logs. Mais je ne sais pas comment cela fonctionne. 
Le code est s2Avse1hca
Quelqu'un pourrait m'aider s'il vous plaît ? 

Merci d'avance.

**Comment by johngf** [comment]
Va dans les parametres de vstream et desactive urlresolver si tu l'as activé et reteste

**Comment by moh-verratti** [comment]
Merci pour ta réponse 
Il était déjà désactivé. 

J'ai regardé au niveau de tous les réglages s'il y avait quelque chose qui clochait mais tout est par défaut

**Comment by moh-verratti** [comment]
Dernière mise à jour des sources ? 
Aujourd'hui

**Comment by johngf** [comment]
Ça n'a rien a voir je pense mais ton timeout dans advancedsettings est trop petit 10 c'est preferable de mettre entre 30 et 60

**Comment by TmpName** [comment]
Tu as quelle version de Vstream ?

**Comment by johngf** [comment]
Si il a mis a jour aujourd'hui il devrait avoir la v5 est le fichier defaut.py qui va avec non
Probleme de cache ?

**Comment by moh-verratti** [comment]
Bonsoir
Merci pour votre aide 
C'est bien le curlclienttimeout ? Je l'ai mis à 60 je vais tester 
Pour la version de Vstream, j'ai la 0.4.9

**Comment by johngf** [comment]
Il faut mettre a jour vstream vers la v5

**Comment by moh-verratti** [comment]
Bonjour 
Merci pour votre aide 
Tout fonctionne à nouveau.
