### ISSUE TITLE
Nouvelle catégorie Jeunesse | enfant

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1004]
Si vous avez des sources jeunesse je serais bien intéresse pour faire une nouvelle catégorie.

Note pas d'url complet pas de http:// Merci

**Comment by TmpName** [comment]
tv-streamng a gave de dessins animes.

**Comment by johngf** [comment]
je pense qu'il parle des zouzous pour les tout petit
la derniere fois je suis tombé sur un site avec que du disney il faut que je le retrouve

**Comment by LordVenom** [comment]
Oui je penser regarder dans nos sources :) mais je parle d'anime jeune genre bisounours, wini ect.. on vas pas les traumatiser avec des manga hard lol

**Comment by TmpName** [comment]
Ben justement, bisounours wini et ect sont dedans, les derniers que j'ai vu c'etait les scoubidou

**Comment by Arias800** [comment]
Bonjour je suis tombe sur ce site et je pense qu'il serai pas mal voila le lien : www.voirdessinanime.com/

**Comment by TmpName** [comment]
J'ai regarde le site vite fait, mais je pense que c'est exactement ce que cherche @LordVenom

**Comment by Arias800** [comment]
Bon apres il y a pas un choix de fous mais bon c'est un bon debut ^^

**Comment by johngf** [comment]
Disney hd tk liste

**Comment by LordVenom** [comment]
ww w.voirdessinanime.com non site trop fouillis et renvoie sur les replays officiel.

**Comment by Arias800** [comment]
ah mince bon bah j'aurai essayer ^^

**Comment by Arias800** [comment]
Autre site www.youtitou.com

**Comment by LordVenom** [comment]
Il vont ce faire virer de youtube eux lol

**Comment by Arias800** [comment]
Je pense pas parce que leurs chaîne a été valide donc youtube sait ce qu'il font ^^

**Comment by Arias800** [comment]
Il y a aussi le site tfo qui propose des dessin animé : tfo.org/fr/enfants

**Comment by johngf** [comment]
Le probleme c'est pas les sites c'est les gens pour les faires... donc si t'es motivé vas y

**Comment by Arias800** [comment]
Je essayer mais bon je promets rien x)

**Comment by johngf** [comment]
Tu as le temps j'ai fini you titou juste pour qu'il soit dans la prochaine version de vstream qui arrive

**Comment by Arias800** [comment]
D'accord ^^

**Comment by johngf** [comment]
Si quelqu'un peut mergé pour you titou

**Comment by LordVenom** [comment]
Quel merge ?
