### ISSUE TITLE
Apple TV4 ,aucuns liens

### ISSUE THREAD

**Issue by Tokyo99** [Kodi-vStream/venom-xbmc-addons#1006]
Apres avoir effectué une recherche visuelle Séries ou Films,le chargement ( 18 sources ) s'opère normalement , mais au moment ou le résultat de la recherche devrait afficher les liens ,rien,je reviens a la page précédente !
Apple TV4 sous Kodi 17 et la toute dernière version 0.5.0 
Voici mon Log s2QPfhEsW8
Merci aux développeurs

**Comment by johngf** [comment]
deja on dirait que tu as un probleme de droit sur ta machine en ecriture 
`14:49:16 T:6152728576   ERROR: SQL: [Textures13.db] Attempt to write a readonly database
                                            Query: INSERT INTO texture (id, url, cachedurl, imagehash, lasthashcheck) VALUES(NULL, 'special://home/addons/plugin.video.vstream/resources/art/mark_fanart.jpg', '6/6cee0c2c.jpg', 'd1489488686s132448', '2017-03-14 `

**Comment by LordVenom** [comment]
```
14:47:43 T:6156169216   ERROR: EXCEPTION: Unknown addon id 'plugin.video.alluc.api'.
14:47:43 T:6156169216   ERROR: EXCEPTION: Unknown addon id 'plugin.video.theroyalwe'.
14:47:43 T:6156169216   ERROR: EXCEPTION: Unknown addon id 'plugin.video.redbeard'.
```
Ton Installation est bien attaquer fait le menage n'utilise pas superrepo mais plutôt fusion-repo
vide le cache de Kodi réinstalle vStream.

**Comment by Tokyo99** [comment]
Un problème de droit !! Avec la pomme c'est souvent le cas !! Bon un grand nettoyage s'impose !! Merci je vous tiens au courant

**Comment by Tokyo99** [comment]
Bonsoir à tous 
Mon problème a été réglé en opérant un nettoyage par le vide ... suppression de  Kodi puis réinstallation de Kodi17 .Resultat Vstream est tout beau tout neuf . 
Merci à vous et encore bravo pour l'énorme boulot
