### ISSUE TITLE
plugin youtube

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#1007]
bonsoir un code commencé fonctionelle pour se passer du plugin youtube en dépendance
[ici](https://github.com/johngf/divers/blob/master/img/etc.py)

**Comment by LordVenom** [comment]
Je peux pas tester de suite mais c'est cool

**Comment by TmpName** [comment]
Oblige de passer par keepvid du coup ?

**Comment by johngf** [comment]
En faite il y a plusieur site du genres c'esr le plus rapide 
Et on recup les liens direct par qualité test sur documovies

**Comment by TmpName** [comment]
Tu as regarde comment faisait le pluggin par curiosite ? Je croyais que kodi ne gere pas le dash ?

**Comment by johngf** [comment]
J'ai regardé plein de code sur github la plupart utilise youtube dl
Sinon j'ai pas trouvé dans le plugin youtube comment il récup les veritables url playable sur youtube 
Ceux du site youtube ne servent a rien en l'etat 
Donc j'ai fait comme ça

**Comment by LordVenom** [comment]
Je lis rarement des video youtube uniquement les bandes annonce et je sais du tout comment elle fonctionne jamais regarder le code.

**Comment by johngf** [comment]
avec un code trouvé sur le net et adapté 
j'arrive recup les bonnes url qui nécessite signature=etc....
Par contre avec certains lien l'url est formaté differrement il n'y a pas signature mais s=etc... en dehors de l'url 
donc avec ceux la ça fonctionne pas pour l'instant meme en faisant l'url a la main il manque des trucs ou ..
Testé sur firefox

**Comment by johngf** [comment]
bon pour les urls differente la signature est codée Cipher doit etre décodé grace avec l'aide du 
htlm5...player.js qui change de tps en tps de youtube trouvé que du php ou des apis sur le net
ou usine a gaz [ici](https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube/helper/signature/cipher.py)
[info](http://stackoverflow.com/questions/21510857/best-approach-to-decode-youtube-cipher-signature-using-php-or-js)
donc c'est préférable de passé par le site qui fait le taff

**Comment by TmpName** [comment]
Lol, ok, bon ben j'ai pas perdu mon temps on n'allant pas voir ^^.
Je m'attendais pas a un truc si complexe.

**Comment by johngf** [comment]
quelqu'un sais comment on pourrait viré ou bloqué la popup de kodi echec de lecture 1 ou plusieur elements etc...
parceque quand on ouvre un dialog choix qualité sur les hosters si on clic sur annuler ça met erreur parceque le script continue 
j'arrive a l'empécher pour que le bouton annuler fonctionne comme il devrait et stop tout mais au bout de plusieurs videos j'ai la popup de kodi

**Comment by TmpName** [comment]
Pour le premier prb, c'est un peu mort, en fait les hoster retournent soit True,url si le fichier est lisible soit False,False si le fichier est mort, illisible ou si on presse sur annuller.

Pour le second prb, c'est le popup qui apparait par exemple en cas de timeout ? Il faudrait voir quelle partie de vstream charge cette url et mettre un try/except.

**Comment by johngf** [comment]
Pour le premier j'ai aussi modif le fichier play pour quil arrete c'est ok mais kodi croit que c'est une erreur

**Comment by TmpName** [comment]
C'est quoi la modif ?

**Comment by johngf** [comment]
pour la fonction annuler je pense que c'est mort vu que kodi l'interprète comme un échec d'ouverture du dossier ou fichier

**Comment by johngf** [comment]
nouvelle version qui passe par le site uniquement pour les videos sans signature
