### ISSUE TITLE
Besoin d'aide sur une nouvelle source

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1012]
Bonjour,

j'arrive bien jusqu'au lien "titre du film +openload"  mais j'ai un défaut fichier introuvable et j'ai ce défaut dans le log de kodi T:2224   ERROR: Playlist Player: skipping unplayable item: 0,

en plus il ne me sort que openload et pas les autres hébergeurs. seul openload apparait dans le code de la page, sur le site il faut sélectionner l'hébergeur que l'on veut (par défaut c'est openload). comment faire pour qu'il s'affiche tous et pour que ça marche. merci

le lien de mon fichier:
https://gist.github.com/razorex/bc4b19e9afc264ef4149f7408b06c04b#file-cinemavf_bz-py

**Comment by johngf** [comment]
Avant d'ouvrir une issue il faut verifier que tu as la derniere version du fichier 
Mis a jours de ce matin openload
 https://github.com/Kodi-vStream/venom-xbmc-addons/commits/Beta

**Comment by TmpName** [comment]
Openload est HS, et pour le moment je cherche une methode durable.

Sinon comme dit @johngf avec le regex que tu utilise, tu ne peux recuperer que celui qui s'affiche directement.
Pour avoir la liste complete le code se trouve ici

```
form action="" method="post">
                                            <a onclick="$(this).closest('form').submit()">
                                                flashx                                            </a>
                                            <input name="levideo" value="199459" type="hidden">
                                        </form>
                                    </li>
                                                                        <li>
                                        <form action="" method="post">
                                            <a onclick="$(this).closest('form').submit()">
                                                openload.co                                            </a>
                                            <input name="levideo" value="199460" type="hidden">
                                        </form>
                                    </li>
                                                                        <li class="selected">
                                        <form action="" method="post">
                                            <a onclick="$(this).closest('form').submit()">
                                                okru                                            </a>
                                            <input name="levideo" value="199464" type="hidden">
                                        </form>
                                    </li>
                                                                        <li>
                                        <form action="" method="post">
                                            <a onclick="$(this).closest('form').submit()">
                                                youwatch                                            </a>
                                            <input name="levideo" value="199463" type="hidden">
                                        </form>
                                    </li>
                                                                        <li>
                                        <form action="" method="post">
                                            <a onclick="$(this).closest('form').submit()">
                                                streamin                                            </a>
                                            <input name="levideo" value="199461" type="hidden">
```

Il y a un fichier site qui utilise le meme code, attends je cherche.

**Comment by TmpName** [comment]
Bon pas retrouve, mais sokrostream utilse la meme methode.
Tu fais une partie showhosterlink ou tu affiches tout les hosters recuperer sur le code du post precedent, tu recupere aussi la valeur de value="xxx"

Et dans ShowHosters, tu lances la requete avec le parametre levideo=xxxx pour avoir le lien qui correspond.

**Comment by razorex** [comment]
je vais donc jeter un sur sokostream merci

**Comment by TmpName** [comment]
Lol mince, autant pr moi, j'ai rate la correction d'opnload aussi, mais j'ai l'impression que le code chnage tout les jours ...

**Comment by johngf** [comment]
@razorex quand tu modifie un fichier site exemple les genres il faut faire attention 
-Des fois tous les genres disponible ne sont pas afficher en clair sur le site

-tu peux combiner grace a une astuce exemple sur filmvostfr 
Serie et anim ont les meme genres peuvent etre combiné en une seule fonction
