### ISSUE TITLE
Changer de couleur

### ISSUE THREAD

**Issue by arzaz** [Kodi-vStream/venom-xbmc-addons#1023]
Bonjour,

Depuis la dernière mise a jour, il est impossible de changer la couleur des catégories a savoir Films, Recherche, series etc....
Est-il possible de rajouter cette option lors de la prochaine mise a jour? Car avec uniquement une seule couleur "Blanche" c'est un peu moche.

Merci

**Comment by LordVenom** [comment]
Non fonction supprimer et enterrer dsl
