### ISSUE TITLE
Infos sur onglets Marque pages et Librairie

### ISSUE THREAD

**Issue by Seth0713** [Kodi-vStream/venom-xbmc-addons#1027]
Bonjour,

Pouvez-vous me dire s'il vous plait à quoi servent les menus Marques pages et Librairies dans le menu et comment les utiliser ?

Je ne trouve pas le fonctionnement. D'ailleurs je me disais qu'un onglet AIDE pour l'utilisation de certaines choses seraient peut être pas mal, (je vais surement me pencher là dessus ;) )

Merci à vous.
Seth0713

**Comment by TmpName** [comment]
Les menu marques pages sont tres utiles, je sais meme pas comment s'en passer. Quand tu lances une recherche sur une serie par exemples, tu va avoir des dizaines de resulats, une fois que tu as chosit le site (en fonctions de tes gouts) tu vas sur le lien qui englobe toute la saisons par exemple, tu met ce lien en favoris. Et la prochaine fois il te suffira d'aller dans le menu favoris pour retrouver toute la saisons sans avoir a refaire la recherche.

La librairie fait la meme chose mais rajoute les liens dans la librairie de kodi, la c'est plus complique, c'est kodi qui gere ca, il te faut rajouter le repertoire des librairies Vstream dans la configuration de kodi. Mais la apres c'est kodi qui gere et cela ne se passe pas pareil selon les themes et ta config de kodi (et surtout pas fiable, car les liens changent trop souvent pour etre mit en librairie)

**Comment by LordVenom** [comment]
Pour afficher une aide sur vStream il faudrait afficher une popup et tout enregistrer, soit online soit dans l'addon pas terrible par contre alimenter le Wiki https://github.com/Kodi-vStream/venom-xbmc-addons/wiki
pourrais servir à d'autre.Nous n'avons pas le recule nécessaire car quand ont la coder ça parais toujours logique.

**Comment by Seth0713** [comment]
Bonjour,
Merci pour l'info je vais tester ça sur le pc. Mais pour tout dire j'utilise Vstream sur mon Raspberry-Pi avec l'application Yatse sur mon téléphone. Le Raspberry étant connecté directement en HDMI sur la TV. Du coup à partir de la télécommande ou de Yatse, je ne vois pas trop comment mettre en Marque-Page.

Pouvez-vous m'éclairer la-dessus ?

Concernant le deuxième point, je suis d'accord avec toi LordVenom, le wiki est la meilleure solution, je pourrai faire un premier travail de relecture sur l'existant déjà (orthographe, etc.) et ensuite vous proposer une arborescence et des articles si vous le voulez.

Comment dois-je faire pour avoir accès en modification sur le Wiki ?

Merci à vous et bonne journée.
Seth

**Comment by johngf** [comment]
normalement tu as un bouton sur ta telecommande qui fonctionne comme le clic droit d'une souris
ça affiche une popup avec ajouter marque pages ou librairie

**Comment by Seth0713** [comment]
Merci pour l'info, je vais essayer ce soir, à priori c'est la touche "Show TV guide".

**Comment by LordVenom** [comment]
Je tes envoyer une invitation membre.

**Comment by Seth0713** [comment]
Merci, je regarde ça très vite.
Bonne fin de journée.

**Comment by Seth0713** [comment]
Ok, sur ma télécommande c'est le bouton option.
Bonne journée.
