### ISSUE TITLE
Musique sur vstream !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1028]
Ça serais bien d'écouter de la Musique sur vstream.
Voici des sites pour écouter de la Musique si-dessous :
https://www.hauteculture.com/
http://www.alcanpromo.com/
https://www.deezer.com/fr/
https://play.spotify.com/?utm_source=web-player&utm_campaign=bookmark

**Comment by LordVenom** [comment]
Menu Télévision / radio
