### ISSUE TITLE
Lien Vidlox 

### ISSUE THREAD

**Issue by johnboisvert** [Kodi-vStream/venom-xbmc-addons#1034]
Bonjour,
je recherche la série : Victor Lessard
je l'est facilement trouvé le problème c'est que c'est juste sur les liens Vidlox qui demande Kodi 17 et j'ai Kodi 16..
est-ce possible de by passed ca ? svp

sinon pouvez vous me dire ou telecharger le nouveau Kodi 17.1 je vais l'essayer mais je ne peut pas le télécharger via Play Store et je ne l'est pas trouvé ailleur pour Android jusqu'à maintenant

Merci gang lâcher pas :)

**Comment by johngf** [comment]
Non vidlox utilise le ssl et kodi 16 ne le gere pas 
tu es sur android ? Normalement il est dispo sur le store

**Comment by johnboisvert** [comment]
Oui Android mais sur une box je ne peut pas sur ma box me connecté a play store c'est pour ca que je dois télécharger kodi 17 via mon ordinateur je ne sais pas ou je ne l'est pas trouvé et avec une clef usb l'envoyer sur ma boite android

**Comment by johngf** [comment]
Teste le lien plus haut

**Comment by johnboisvert** [comment]
Tu est officiellement une machine merci mon gars
je cliquais sur GET IT Play Store lol et non en bas :D merci mec

**Comment by johnboisvert** [comment]
Non j'ai essayer de tous les telecharger via leur site rajouter sur ma usb card il ne les detect meme pas

**Comment by johngf** [comment]
Sur ta box tu as un navigateur internet ? Si oui clic sur get it on quand il demande avec quoi tu choisis navigateur

**Comment by TmpName** [comment]
C'est quoi le site qui ne propose que des liens vidlox ?

**Comment by johnboisvert** [comment]
johngf ok merci je vais regarder ce soir 
TmpName j'ai faite une recherche série une nouvelle au quebec ca s'appel Victor Lessard donc je clic sur cette série qui a l'image Victor Lessard S01 et il y a que les liens Vidlox ou si il y en a je gosse depuis hier rien fonctionne je la conseil en passant cette série si elle fini par marché :P

**Comment by Kodigoal** [comment]
Si c'est sur filmstreamvk ta série  , il affiche que les liens vidlox  car ca zappe les liens netu ,le regex showHostersSerie est pas bon , si les url ne débutent pas par http ca zappe et là manque de bol on tombe sur une exception pêtre , ca débute par '//hqq'.
Modifier le code c'est ok , mais ya surement mieux à faire:
http://pastebin.com/ep9x0N2p

**Comment by TmpName** [comment]
Connais pas du tout, mais si ca parle quebequois ca risque de me faire bizarre :).
Sinon y a des liens Youwatch et flashX sur seriestremng.watch pr cette serie.

**Comment by TmpName** [comment]
Ca prend un lien "alakon" en trop @Kodigoal mais c'est filtre par Vstream donc ca gene pas. Met ta modif directement en ligne.

**Comment by johnboisvert** [comment]
Je suis nul en code :) merci les amis j'essaye ca ce soir ! :D

**Comment by johngf** [comment]
@TmpName tu,as commencé pour opeload il'est encore hs

**Comment by Kodigoal** [comment]
@TmpName oui j'ai vu  ,mais je sais pas comment faire niveau regex pour lui dire de zapper si ya qu'un chiffre entre ' ' .

**Comment by TmpName** [comment]
@Kodigoal, laisse tomber, c'est pas genant.
@johngf, ben je suis un poil deborde cette semaine, mais je ne fait quasiment que ca. Et je teste plusieurs solutions

https://github.com/TmpName/Fichier_en_vrac/tree/master/OpenloadExtractor
ici a partir d'une page html ca donne le code javascript en clair, possiblitee de continuer ce fichier pour extraire l'algorythme mais il leur suffit de chager une virgule et c'est mort.

Sinon via le code JS obtenu, si on le passe sur jsnice.org, on obtiens un code tres facile a gerer, mais il me faudrait la meme chose en python. Sinon en le gardant brut il passe presque sur mon interpreteur
https://github.com/TmpName/EasyJSParser

Il bloquerait juste sur la syntaxe condition&&code qui est l'equivalent de condition { code }, mais ca devrait etre bon dans quelques jours.

**Comment by johngf** [comment]
tu as deja test les convertisseurs js > python qu'on trouve sur github ou ailleur pour le code

**Comment by TmpName** [comment]
Lol yep, je viens d'editer le code.
Certains marchent tres bien, mais si le dev de openload est joueur, il peut executer du code sur Vstream.

**Comment by TmpName** [comment]
Sinon a voir si il existe en dependance pr kodi ?
Car ca me fait chier quand meme de le mettre avec Vstream, vu la taille.
En fait quand j'ai commence ma lib c'etait justement pr avoir quelque chose de light, mais js2py est largement plus robuste.
Apres c'est sur qu'avec cette lb on est trnaquille un moment, pour moi les bidouilleur d'openload n'ont pas le niveau pour bloquer cette lib.

**Comment by johngf** [comment]
en faite je parlé de convertir un code js en python pour pouvoir l'utilisé dans vstream
pas d'installé js2py

**Comment by TmpName** [comment]
Ben js2py fait justement ca, tu lui donne le code JS et ca te fait un fichier python utilisable.

Sinon ca y est ma version light marche, elle execute carrement le code JS de openload pr avoir le lien, tu peux tester la version en ligne de ce soir, tu vas avoir un message d'erreur mais si tu remontes un peu le lien s'affiche.

Comme le code JS change tout les jours, il faut que Vstream soit capable de le convertir ou l'interpreter tout seul.

**Comment by johnboisvert** [comment]
Vous etes ca coche vous travaillez en continue c'est fou !!! je tripe ! :)

**Comment by Kodigoal** [comment]
@TmpName ok mais juste pour info si on fait comme ca? 
Soit débute par  http, soit par un / . Ca a l'air ok après test mais 
pêtre que ca fonctionne pas comme je le pense ..
`sPattern = 'onclick="lecteur_serie\([0-9]+,\'((http|\/)[^<>]+?)\'\);">' `

**Comment by TmpName** [comment]
J'ai pas compris ce que tu veux faire, ton regex de base
`sPattern = 'onclick="lecteur_serie\([0-9]+,\'([^<>]+?)\'\);">'`

Marche que le nom commence par http ou pas, non ?

**Comment by Kodigoal** [comment]
Oui mais ca  vire le hoster 'alaKon' ('5') , je pensais que ca pouvait le faire avec ce regex sur ce site.

**Comment by TmpName** [comment]
Ha oui exact dsl, j'avais decroche ^^.
Mais ca va capturer 2 regex (http|\/) et ((http|\/)[^<>]+?)\'\), il y a les parenthses non capturante (?:)
sPattern = 'onclick="lecteur_serie\([0-9]+,\'((?:http|\/)[^<>]+?)\'\);">'

**Comment by Kodigoal** [comment]
Ah oui  merci^^ pas penser pour la capture.
Avec (?:)  niquel, modif demain.

**Comment by johngf** [comment]
@johnboisvert ta serie je l'ai vue sur bcp de site ne te fie pas a la recherche

**Comment by johnboisvert** [comment]
Oui j'ai réussit a la trouver avec la recherche ont dirais qu'elle c'est rajouter sur d'autre site fonctionnel :) je vous remercie tous n'oubliez pas de l'écouter c'est une série style Décadence en quebecois lol

**Comment by johngf** [comment]
Sur linux kodi 16.1 ça fonctionne peut etre qu'ils ont enlevée le ssl a voir sur autre plateforme
