### ISSUE TITLE
Framapad

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1041]
Tout d'abord : un grand merci aux développeurs !

Au sujet de framapad :

Pourquoi ne pas utiliser le format m3u qui permet en plus d'afficher les logos des chaines et éventuellement les programmes TV.

#EXTM3U
#EXTINF:-1 tvg-name="13rue" tvg-logo="fr_13rue.png" tvg-shift="-5" group-title="France", 13eme Rue
http://XXX.ts

Pour les programmes TV : J'ai déjà installé et configuré Webgrab++ alors je peux vous donner un coup de main si vous avez un serveur pour héberger le script.

Encore un grand merci à tous !

**Comment by LordVenom** [comment]
Framapad c'est surtout des copie colle des utilisateurs ce n'est pas vraiment gérer par nous donc le code est gérer au strict minimum.

Dsl je sais pas ceux que c'est que webgrab. Nous n'avons pas de serveur Le seul lieux d’hébergement pour les fichier de vStream c'est Github.

**Comment by canopre** [comment]
Hello et merci pour ta réponse rapide.

Webgrab+ permet d'ajouter les programmes TV aux chaines afin de savoir ce qu'on regarde et les programmes à suivre : C'est très pratique.
Je peux si tu veux partager avec toi mon fichier de config afin que tu en profites également mais malheureusement je ne pense pas que mon serveur permette d'en faire profiter toute les communauté.

Par contre j'ai une petite question au sujet de Framapad.

Avez-vous trouvé une solution pour éviter les coupures : sous rpi2 : c'est récurent :c

Mais peut-être que le gentils contributeur qui partage tous ces liens à une offre vip à proposer ?

**Comment by LordVenom** [comment]
Merci c'est gentil mais je ne regarde pas la tv.commeje le disais framad c'est aléatoir j'ai vraiment aucune emprise dessus je ne sais pas quel lien sont dessus et qui poste dedans mais y a la section tv qui elle et gérer par nous avec les icons ect non ?

**Comment by canopre** [comment]
Hello
Merci de m'avoir rappelé cette fonction : la dernière fois que j'avais regardé (-2ans) il n'y avait pas grand chose : maintenant c'est beaucoup + complet.

Mais beaucoup de chaines ne démarrent pas :; je joins mes logs au cas où :)
http://pastebin.com/FKe3T1Ww

Et quand même ca serait sympa que la section TV de Vstream indique les programmes TV : je suis à votre dispo pour partager mon expérience avec Webgrab++

**Comment by TmpName** [comment]
Nope c'est normal :), En fait ces chaines sont des streams officiel, pris directement du site officiel.
Les autres sont officieux et jamais longtemps valides.
