### ISSUE TITLE
Vstream recherche impossible 

### ISSUE THREAD

**Issue by mako83** [Kodi-vStream/venom-xbmc-addons#1045]
Bonjour,

J'ai actuellement kodi 17.1 sur mon téléviseur Android phillips avec l'extension vstream 5.0 installé via le repo'

J'ai un problème avec vstream j'ai un code d'erreur avec vstream lorsque j'effectue une recherche le code d'erreur est celui ci:

Connections impossible (405)
Erreur vstream

Je ne comprend pas pourquoi j'ai ce problème et malgré la réinstallation de kodi et des add-ons.
Alors qu'autrefois je ne l'avait pas.

Merci d'avance pour votre aide :) et continuer comme ça !

PS: à pars ce soucis de recherche les film marche bien.

**Comment by johngf** [comment]
c'était du a un site c'est corrigé

**Comment by mako83** [comment]
Merci de la réponse très rapide.
Je vais tester ça 
Cela prendra effet a la prochaine maj ? Ou ça a déjà pris effet ?

**Comment by mako83** [comment]
Re bonjour désolé pour le double post mais je trouve pas la fonction éditer sur téléphone.

Alors la recherche ne fonctionne toujours pas 
Erreur cloudfare et connexion impossible

Merci d'avance à vous ;)

**Comment by TmpName** [comment]
Tu passes par quelle recherche stp ?

**Comment by mako83** [comment]
Recherche normal,
Je viens de restaurer ma TV et réinstaller Kodi et  mes add on ça refonctionne merci du suivie
