### ISSUE TITLE
Mise à jour de Vstream

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1052]
Je n'ai plus les mise à jour de vstream (sur mon pc) depuis qq temp. j'ai désinstaller et réinstaller et mes sources sont dépassés (pourquoi)????? ça viendrais de kodi ou Vstream???

**Comment by TmpName** [comment]
Quelle mise a jour ?
cf https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour

**Comment by razorex** [comment]
les mises à jour auto. j'ai nettoyé le cache de kodi et réinstallé toujours pareil.

**Comment by razorex** [comment]
le problème vient de Kodi. il m'affiche l’icône du site que j’essaie de développer alors qu'il n'est pas dans le dossier de Vstream.

**Comment by johngf** [comment]
Il faut evité de démarré kodi via un raccourcis favoris ou autres raccourcis ça peut causé des soucis de caches 
Donc kodi ->extension video >vstream

**Comment by TmpName** [comment]
Ha oui, c'etait mon gros prb aussi ^^, dans les parametres de vstream, outils, vider le cache de kodi.

**Comment by razorex** [comment]
@johngf dsl je parlais du cache kodi. Ok vais tester @TmpName

**Comment by johngf** [comment]
@razorex vstream utilise le cache de kodi

**Comment by razorex** [comment]
Pourtant @johngf il y a bien la fonction clean cache addon dans le menu configurer de Vstream. 
J'ai désinstaller Kodi, fais une réinstalle de Krypton (même pb voir pire j'ai carrément aucun addons qui s'installe) donc je suis revenu sur Jarvis. regardé la config de mon pare-feu (ras). Alors est-ce que quelqu'un aurais une idée. je sais que çà ne viens pas de Vstream  (PC sur windws 7)mais je suis quand même pas le seul à avoir des soucis. Ma TVbox et mon smartphone ne rencontre aucun souci......

**Comment by johngf** [comment]
Avec krypton tu as activé l'option installer addon depuis source inconnue dans les parametres de kodi
Tu utilise un repo pour installé genre superrepo (déconseillé) ?

**Comment by TmpName** [comment]
Si au bout de 3 jours tu n'as pas les maj auto, vide la cache de kodi, (pas de Vstream) ca va recharger la page home completement, et donc refaire une recherche de maj. J'avais le meme prb sur la V16.

**Comment by razorex** [comment]
@TmpName justement j'ai vérifier et j'avais plus rien. J'ai déjà tester le clean cache de Kodi mais je vais attendre et retenter je verrais bien.

**Comment by TmpName** [comment]
Normallement ya un endroit ou la date de la prochine MAJ est affiche, dans les options je crois.

**Comment by razorex** [comment]
J'ai déjà tenté avec le repo de vstream et rien. mais je retesterais. oui la date de de la "dernière" mise à jour apparait dans le menu outils/a propos de la config de vstream.

**Comment by Kodigoal** [comment]
Normalement la date affichée c'est la prochaine maj prévue , pas l'ancienne .. T'as l'heure/date à jour sur ton pc ?

**Comment by razorex** [comment]
oui l'option sources inconnu est activé. Ben j'ai 25/03????? @Kodigoal

**Comment by razorex** [comment]
et il est écrit dernière

**Comment by razorex** [comment]
mais il me semble avoir vu la derniere date de maj dans kodi.log une fois

**Comment by razorex** [comment]
oui date et heure pc à jour

**Comment by Kodigoal** [comment]
Et sur ton tel ou TVbox, ya affiché une date à venir ou passée dans Outils/a propos ?

**Comment by razorex** [comment]
Donc j'ai cette ligne dans le fichier log de kodi
20:48:14 T:6780  NOTICE: 	[PLUGIN] Vstream: Prochaine verification de MAJ le : 2017-03-29 20:48:14.005000

**Comment by razorex** [comment]
Non @Kodigoal c'est bien la date de la dernière MàJ qui apparait.

**Comment by Kodigoal** [comment]
Ah, je croyais la prochaine , ou ca a été enlevé pour soucis de cache kodi.
Normalement si tu fermes kodi, avance de 3 jours date pc , en relancant kodi -vstream , la maj doit être proposée si des fichiers sont à mettre à jour via la Master branche.

**Comment by razorex** [comment]
Vu que fais fais une réinstallation il devrait faire une maj. vais testez sur un autre pc je verrais bien
 La date de MàJ évolue à chaque lancement...
18:56:35 T:5688  NOTICE: 	[PLUGIN] Vstream: Prochaine verification de MAJ le : 2017-03-30 18:56:35.742000

**Comment by Kodigoal** [comment]
Bizarre ton soucis

**Comment by TmpName** [comment]
Va dans \Kodi\userdata\addon_data\plugin.video.vstream et vire le fichier settings.xml.
Mais il te faudra reconfigurer Vstream.

De reinstaller kodi ca sert a rien vu que ce repertoire n'est pas efface (enfin j'ai pas teste mais c'est logique)

**Comment by razorex** [comment]
A priori c'est windobe qui coince j'arrive même pas à installer Vstream depuis sont dépot sur un autre pc avec Windows 8... pff.
 @TmpName quand j'ai désinstaller kodi sont dossier avait disparu. vais tout de même essayer

**Comment by razorex** [comment]
non ces pas mieux avec ça j'ai même plus les menus films/series etc...

**Comment by LordVenom** [comment]
ça vas recharger t’inquiète.

**Comment by TmpName** [comment]
Quand tu installes kodi, 2 dossiers sont crees, 1 qui est l'endroit ou tu l'installes et un autre pour la configuration. Quand tu desinstalles seul le premier est supprime.

**Comment by razorex** [comment]
Supprimer le fichier setting.xml et rien.. @TmpName tu parle du dossier sous roaming, il est bien supprimé au moment de la désinstallation.

**Comment by LordVenom** [comment]
![capture d ecran de 2017-03-30 02-19-32](https://cloud.githubusercontent.com/assets/4380112/24482130/594ce212-14ef-11e7-9c51-14f92e41a3ce.png)

**Comment by razorex** [comment]
non @LordVenom ça fonctionne pas non plus...

**Comment by LordVenom** [comment]
Je sais pas alors, attend la maj officiel ce week end ça devrais résoudre le soucis sinon on en reparle.

**Comment by razorex** [comment]
Donc la monté de version en 0.51 c'est bien passé.

**Comment by LordVenom** [comment]
Hé les mise a jour sites et Hosts ça tourne ?

**Comment by razorex** [comment]
Pour l'instant je n'ai pas eu de demande de mise à jour "sites et hosts"

**Comment by razorex** [comment]
bon a priori les mise à jour sites et hosts ne fonctionne toujours pas et ceux malgré la monté de version qui c'est bien faite.

**Comment by LordVenom** [comment]
Dans ton log quel et la date de la prochaine mise a jour ?

**Comment by razorex** [comment]
Le 9

**Comment by LordVenom** [comment]
Avance la date de ton ordis au 10 et relance Kodi. Il ce passe quoi?

**Comment by razorex** [comment]
eh bien quand je relance vStream la date de la prochaine mise à jour évolue à date et heure d'ouverture +3jours
Ex: ouvert le 08/04/2017 à 13.00 prochaine màj 11/04/2017 à 13.00

**Comment by razorex** [comment]
je suis quand même pas le seul à qui ça arrive...............

**Comment by LordVenom** [comment]
Ben j'ai recus une mise a jour ce matin sans soucis donc tu refait la manip avec la date et tu choppe le log juste aprés.

**Comment by TmpName** [comment]
Si la date evolue c'est que la mise a jour se fait.
Le changement de date se fait apres le dl, donc si y avait un bug y a peu de chance que la date soit changée das ce cas.

**Comment by johngf** [comment]
voir issue config

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1011#issuecomment-293193566
