### ISSUE TITLE
Openl_ad

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#1062]
Bon alors pour ce qui n'ont pas suivis toute l'histoire, cet hebergeur a mit en place un systeme de generation aleatoire d'algorytme de codage, celui-ci change tout les jours ou presque.

Donc voici quelques solutions que j'ai commence a tester, a approfondir.

Faire installer js2py sur kodi, en dependance ?, possible ou pas ? J'ai deja vu un addon l'utilisant, ce code permet beacoup de chose et est tres performant.

Utiliser un interpreteur maison, j'en ai un sous la main, qui fonctionne malgre un gros hack, que je vais corriger ce We je pense
Fichier ici http://pastebin.com/QxjXk6M6
Mais meme si le code fait peur, c'est juste un truc code avec des bouts de ficelles, m'etonnerait qu'il dure 6 mois.
Par contre on peut utiliser la premiere partie de ce code pr modifier le code JS et le rendre plus facilement interpretable.

**Comment by johngf** [comment]
Js2py je ne pense pas que c'est possible a moin de l'integré direct ou de l'install soit meme
Sinon ton code fonctionne ?

**Comment by TmpName** [comment]
Yep, et je l'ai deja modifie 2/3 depuis cettte version
Derniere version ici https://github.com/TmpName/TinyJSParser

Il marche aussi pr aadecode et jpspacker.

Le seul prb c'est qu'il est bourre de hack, il y a plein de trucs que j'ai eu la flemme de faire (au debut c'etait sense etre un code light) et ou j'utilise des magouilles.
A la prochaine grosse modif de openload il va devoir etre remit a jour mais les pauvres modifs qu'ils ont fait ces dernieres semaines, ca passe sans soucis.

Tu peux le tester direct en remplacant le fichier d'origine, je l'ai pas encore mis sur le github, car j'attend de voir si ca tient, pr le moment RAS.

**Comment by Kodigoal** [comment]
Testé en copiant collant le pastebin ( 1er post)  > openload.py 
Mais fonctionne pas de mon côté... Ya d'autres fichiers à changer ?

**Comment by TmpName** [comment]
Ha merde, je l'oublis tout le temps ce bout de code.
La j'essaye de simplifier le code pour que d'autres puissent rajouter facilement des fonctions manquantes, mais elle y sera pr la prochaine MAJ

**Comment by johngf** [comment]
fonctionne pas chez moi meme en virant les 'fh=open et cie'

**Comment by TmpName** [comment]
Ne marche plus ^^.
En fait ils n'ont pas trop modifie le code JS, mais la facon de parsemer le code JS dans la page html.
Donc pr le moment c'est la premiere partie du code qui est a revoir.

**Comment by TmpName** [comment]
Bon j'ai mit une version fonctionnelle en place.
Ils chnagent le code regulierement pr bloquer ceux qui utilisent js2py, la par exemple ils regardent si le document contient un mot special, et comme ils refont le fichiers .....

La bonne nouvelle, c'est que c'est assez facile de bidouiller ces bloquages via la fonction CleanCode(), cette fonction sert a avoir un code JS potable, c'est assez facile a comprendre, ya deja 2 lignes qui servent.

Apres le code est passe a l'interpreter JS, et la meme moi je ne peux pas expliquer ce que j'ai fais.

Le code est a optimiser, ca prend facile 1 mn chez moi a calculer, trop long, mais ca tourne.

**Comment by johngf** [comment]
Ça finis pas en timeout ?

**Comment by johngf** [comment]
ça dépend de la puissance du pc sur un vieux intel 4 coeur quad6600 moins de 30sec sur un raspberry ou autres ça doit mettre une plombe

**Comment by Arias800** [comment]
Chez moi ça retourne des truc comme ça :Error creating demuxer si vous savez d'ou ça vient ^^

**Comment by johngf** [comment]
@Arias800 tu as testé la version sur la beta ?

**Comment by Arias800** [comment]
oui j'ai essayer sur la dernière version et sur la beta les 2 ne marche pas et affiche l'erreur il y a aussi un problème de son sur mega-stream

**Comment by johngf** [comment]
chez moi c'est ok

**Comment by Arias800** [comment]
ah bizarre :/

**Comment by Arias800** [comment]
J'ai tester en désinstallant et réinstallant vstream rien ne change :/

**Comment by TmpName** [comment]
Nope, pas de prb de timeout, car ce n'est pas une requete web, ca fait juste des calculs en local et sans possibilitees de le stoper, j'attend de voir combien de temps ils vont mettre pour le bloquer (pour savoir si ils nous surveillent aussi comme les autres) et je la je bosses sur l'optimisation.
Mon but est d'avoir une base plus comprehensible pour que d'autres puissent ameliorer l'interpreteur, enfin si ils changent pas de methode car ce n'est pas un robot qui change le code aleatoirement, y a vraiement un pauvre type paye a nous surveiller et chnager le code en fct.

**Comment by Arias800** [comment]
@TmpName c'est chaud de ce dire qu'un mec est paye pour vous surveiller o.O

**Comment by TmpName** [comment]
Pas nous ^^, sinon ca ne marcherait deja plus. Mais il y a d'autres addons plus important que nous, qui sortent une nouvelle parade tout les jours, bloque dans les 24h, puis rebelotte.

Apres flashX avait fait pareil, puis 1,2 mois apres ils ont lache l'affaire.

**Comment by Arias800** [comment]
ah ok j'avais pas compris ça x) . Je savait pour flashX

**Comment by johngf** [comment]
hs

**Comment by LordVenom** [comment]
C est bizard il ont jamais blocker urlresolver.ils nous en veulent ou quoi ont peux ce permettre de répondre peux être ?

**Comment by johngf** [comment]
bah ils perdent de l'argent sans les pubs

**Comment by LordVenom** [comment]
Je doute que le plus gros des utilisateurs vienne de chez nous.

**Comment by johngf** [comment]
la ils bloquent tous les addons ou essaient iptvplayer youtubedl ... ils changent leurs code tous les 2 3 jours

**Comment by TmpName** [comment]
UrlResolver ne marche que avec le systeme de "pairage", il faut se connecter sur un site web avant de lancer la video sur kodi.

Moi ca me permet de developper mon interpreteur, ca pourrait tjours servir un jours, mais il n'y a pas d'autre solution qu'attendre qu'ils en ai marre, un systeme de MAJ journaliere, ou un fichier distribue uniquement en circuit ferme.
