### ISSUE TITLE
ignoring action 107, because topmost modal dialog closing animation is running

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1066]
Bonjour,
J'ai commencer a creer un script pour youtitou.com mais cette erreur apparait et je n'arrive pas a la passer 
Merci de votre aide
Lien: http://pastebin.com/Qmh5afpy

**Comment by LordVenom** [comment]
Chez moi le aResult de showMovies et incorrecte. y a bien a resultat mais je doute que ce soit les bon juste l'url peux être.

``
13:27:28.594 T:139748354021120  NOTICE: 	[PLUGIN] Vstream: (True, [('>                                ', ' style="text-align: center;">', 'http://www.youtitou.com/videos/2-a-4-ans/dessin-animes-2-a-4-ans/pingu/"'), ('>                                ', ' style="text-align: center;">', 'http://www.youtitou.com/videos/2-a-4-ans/dessin-animes-2-a-4-ans/ariol/"'), ('>                                ', ' style="text-align: center;">', 'http://www.youtitou.com/videos/4-a-6-ans/dessin-animes-4-a-6-ans/titeuf//"')``

**Comment by Arias800** [comment]
Ah d'accord je vais tester de rectifier ça ^^

**Comment by LordVenom** [comment]
https://regex101.com/r/9iJhQ7/1

Bon les titre sont mal coder defoix plusieur <a href peux etre le prendre ailleur.

**Comment by Arias800** [comment]
D'accord merci pour l'aide ^^

**Comment by Arias800** [comment]
Autre question pourquoi la le regex marche https://regex101.com/r/DFxLut/2 mais pas sur kodi car ça me trouve rien

**Comment by johngf** [comment]
ton regex ne marchera pas t'est sur golang il faut mettre python

**Comment by Arias800** [comment]
ah mince x)

**Comment by johngf** [comment]
mais le site pythex.org est mieux pour ça souvent celui la deconne

**Comment by Arias800** [comment]
D'accord je vais essayer pythex.org

**Comment by Arias800** [comment]
sur pythex il me mets match 1: www.youtube.com/embed/DBY_ntuMmqg qui est le bon lien et pourtant sur kodi rien apparaît ^^

**Comment by johngf** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/sokrostream_biz.py#L424
Essaie d'ajouter ça pour voir en dessous de shmlcontent = etc.....

**Comment by Arias800** [comment]
Si ça peut aidé j'ai voila les log http://slexy.org/view/s2PUQhXjda

**Comment by johngf** [comment]
Deja ligne 278 279 de ton code aentry[1] n'existe pas

**Comment by Arias800** [comment]
le showEpisode n'est pas utilisé normalement ^^

**Comment by johngf** [comment]
Ta pas inversé l'url et thumbail smovietitle dans showmovies

**Comment by Arias800** [comment]
Ca s’améliore j'ai une erreur 404 x)

**Comment by Arias800** [comment]
C'est bizarre ça fait comme si youtube n’était pas compatible :/

**Comment by johngf** [comment]
Avant d'arriver au hoster fais deja showmovie correctement il y a de tous et nimporte quoi dans ton log
Du vide ou il devrait pas y en avoir  ,des titre en une lettre

**Comment by LordVenom** [comment]
@johngf  je me suis fait avoir avec le timeout aussi mais c'est réglable https://regex101.com/settings

**Comment by LordVenom** [comment]
ont en et ou ?

**Comment by johngf** [comment]
fini j'ai pas les trucs en anglais
