### ISSUE TITLE
website protect

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#1095]
salut à tous,

@tmp_name et @LordVenom vous connaissez "incapsula" comme protect ?
hard à décoder ou ... ?

merci de vos réponses

**Comment by LordVenom** [comment]
Salut, aucune idée de quoi tu parle.

**Comment by ttrd06** [comment]
salut, c'est une protection de sites web comme cloudflare (www.incapsula.com).
si on fait un request simple sur ce genre site, il n'affiche rien sauf le js de protection.
je me demandais donc si l'un d'entre vous avait déjà eu affaire à ça ?
merci

**Comment by TmpName** [comment]
Ben je m'y suis deja penche dessus, mais je sais plus pkoi et je n'ai fait aucun fichier pour passer cette protection. Donc soit le site a supprime cette protection, soit j'ai pas trouve.

Sinon cette protection est assez courante, comme cloudflare, et il y a plein de code en python pour le decoder, mais le code change souvent, et tu risques de galerer pr trouver un code a jour. Mais dans tout les cas c'est trouvable deja fait.

**Comment by ttrd06** [comment]
ok, merci les gars pour l'info
