### ISSUE TITLE
icone de site

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1102]
je voulais savoir comment il faut faire pour proposer des icônes de site à jour...

**Comment by LordVenom** [comment]
Pareil que quand tu fait un pull request non ? sinon poste les ici je les prendrais.

**Comment by razorex** [comment]
![streaming_series_org](https://cloud.githubusercontent.com/assets/26149640/24578678/7b3284de-16e5-11e7-9071-74ddbb7fe46e.png)
 nouvelle image pour "streaming_series_org"

**Comment by razorex** [comment]
@LordVenom tu n'a pas remplacer le bon.

**Comment by razorex** [comment]
J'en profite pour te donner le nouveau de streamzzz_com
![streamzzz_com](https://cloud.githubusercontent.com/assets/26149640/24631374/4a906ac6-18c0-11e7-9cd8-7b1fa86b5287.png)

**Comment by johngf** [comment]
par @razorex https://cloud.githubusercontent.com/assets/26149640/24779441/ce66b95a-1b30-11e7-9c08-04a0d6ce93a4.png
