### ISSUE TITLE
Tuto

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1108]
@TmpName tu a parlé il y a qq temp d'un tuto pour les regex. je veux pas te mettre la pression mais je serais bien content de l'avoir. Pourtant je pense avoir compris les grande lignes mais je n'arrive pas a les faire fonctionner correctement.

**Comment by Arias800** [comment]
Pour te simplifier la vie utilise un site comme pythex.org qui permet de tester ton regex c'est déjà plus simple

**Comment by TmpName** [comment]
En fait me suis arrete la https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source

Fait passer le bout de ocde a extraire et ton regex sur le git hub pour voir.

**Comment by razorex** [comment]
c'est bien comme dans ton exemple que je fais et que j'avais compris.

**Comment by TmpName** [comment]
Alors tu t'en ai sorti ?
