### ISSUE TITLE
Recherche Visuelle : Top Imdb

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1112]
Hello

Depuis déjà un petit moment la recherche visuelle de film dans la catégorie Top Imdb ne fonctionne plus.

J'espère que vous pourrez y remédier.

Merci d'avance et bon courage pour la nouvelle semaine.

**Comment by LordVenom** [comment]
Fait merci.

**Comment by canopre** [comment]
Super ! Merci !
