### ISSUE TITLE
Article divers

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1113]
Article très intéressant, bien sur cela ne concerne que les utilisateurs finaux, les sites qui héberge c'est fichiers sont eux bien illégal.

http://www.numerama.com/magazine/20040-la-legalite-du-streaming-pour-le-spectateur-confirmee-par-la-cjue.html

Kodi veut en finir avec le streaming
http://www.01net.com/actualites/kodi-veut-en-finir-avec-sa-sulfureuse-reputation-de-service-pirate-1139574.html

**Comment by LordVenom** [comment]
Ca me fait rire, à qui kodi vas vendre c'est offre legal au utilisateur débauché grace au addon de stream.

**Comment by johnboisvert** [comment]
Jespere que vous abandonnerai pas :D

**Comment by razorex** [comment]
leur site a été fermé il y a peu

**Comment by razorex** [comment]
bloqué par L'état américain page fbi et tout le reste

**Comment by johnboisvert** [comment]
quel site?

**Comment by razorex** [comment]
c'était le site de kodi mais ça n'a pas duré

**Comment by Kodigoal** [comment]
C'était pas un poisson d'avril ? lol
On va tous finir en zonzon ^^ preparez les tatouages pour s'évader  ..

**Comment by razorex** [comment]
ptdr ma fille était en panique............pas sa série préféré....................................
