### ISSUE TITLE
Impossible de lire un film depuis l'onglet recherche visuelle 

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1140]
Bonsoir, j'en avais déjà parlé j'ai toujours ce meme beug de mon côté, si j'ouvre vstream, que je rentre dans l'onglet recherche visuelle, que je tente de lancer un film, ou une série s'en suit une erreur. 

Si je rentre dans l'onglet film, que je choisis le meme film celui-ci ce lancera. 

Merci à vous pour votre réponse
Kodi 17.1 estuary 
Vstream a jour aujourd'hui

**Comment by LordVenom** [comment]
Quel Version de Vstream ? (clique droit sur l'icone de vStream/information en haut avec le titre tu as la version)

**Comment by kikikodi** [comment]
Bonsoir,
La version mis a jour aujourd'hui, la 0.4.9
J'espère avoir été clair, en gros si je veux visualiser les films ou séries
par  "recherche visuelle" ensuite par exemple "films populaires", j'arrive
donc devant les "jaquettes" si je clique sur n'importe quel films affiché
il y a une erreur en haut à droite "erreur Vstream"

Si par contre je fais une recherche depuis l'accueil de vstream, onglet
"recherche" "recherche film"de ce meme film (exemple dory), j'obtiens tous
les résultats avec les sites hébergeurs, je choisi celui qui me convient,
le film se lance sans encombre...

Ce problème est identique pour une serie Tv

En gros l'onglet recherche visuelle bloque dans son ensemble.

Merci de ta reponse

**Comment by kikikodi** [comment]
autre exemple, dans "recherche visuelle"
Si je choisis "films populaires"
En l'occurrence pour moi le premier qui sort est la "belle est la bête " si je clique sur "ok" l'erreur vstream apparaît, si je clique sur "option"( je suppose équivalant clic droit) je sélectionne "recherche similaire" la la liste des hebergeurs apparaît il ne me reste plus qu'à selectionner celui que je veux visionner. 
Je ne comprends pas d'où viens l'erreur. 

Je tourne avec une box Android 5.0 
Kodi 17.1 
La dernière version de vstream 0.4.9

**Comment by LordVenom** [comment]
J'ai bien compris, une grosse mise a jour ête faite sur themoviedb (recherche visuelle) a la version 5.0 qui rend incompatible les ancienne version dsl du dérangement.Mais il suffis de te mettre a jour.
2Solutions
- Installer notre repository pour avoir les mises a jour automatiquement
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository
- Installer manuelle la version 0.5.1
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/v0.5.1

**Comment by kikikodi** [comment]
Je pensais être a jour puisque lorsque je recherche mise a jour disponible
il n'y en a pas d'affichée.

Aussi pour ne pas perdre mes addons installés j'ai fais un backup avec
indigo en le stockant sur un DD externe, une fois kodi mis à jour, j'ai
donc restauré avec indigo tous mes addons dont vstream.
Est-ce que le fait que je n'ai pas ajouté la source ou le lien de
téléchargement directement de vstream est dommageable et puisse en etre la
cause ?

**Comment by kikikodi** [comment]
Je n'ai pas compris les liens dans ta reponse pour la mise a jour automatique, je fais quoi au juste ? 
Je vais dans réglage, "gestionnaire de fichiers" "ajouter une source" c'est ça ? 
et la je met quoi comme lien ?

**Comment by LordVenom** [comment]
Si tu n'installe pas le repository Kodi ne sais pas qu'il y a une mise a jour.

Le premier lien et pour le repository le 2eme pour l'addon en lui même, La comme tu n'est pas a jour installer les 2 pour forcer la mise a jour, la prochaine ce feras toute seul.

Voila comment moi je fait:
https://www.youtube.com/watch?v=1uS5gbd8jpE&t=2s

**Comment by kikikodi** [comment]
T'es une bombe ça marche nikel, effectivement j'avais installé d'origine vstream en téléchargeant la version en zip sur Atlasweb, pensant que celle-ci se mettrai a jojr automatiquement, puisque a chaque fois des mises à jours l'étaient peoposees en lançant kodi. 
Merci milles fois ! 
Vraiment bravo 
Au passage openload fonctionne parfaitement avec la mise a jojr que tu as fais, mais comme spécifié ttes long avant de lancer la vidéo, presque 2 minutes dans mon cas, deja pas mal ! 
Passes une bonne nuit et merci encore

**Comment by LordVenom** [comment]
Faut pas confondre les mises a jour y en a deux différente un peux de lecture si tu veut
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour

Pour OpenLoad faut remercier @TmpName c'est lui qui leur donne des cauchemar la nuit lol

**Comment by kikikodi** [comment]
Bravo tout Fonctionne à merveille ! 
C'était bien la MAJ qui posait Pb
