### ISSUE TITLE
Uptobox2.py

### ISSUE THREAD

**Issue by diouf76** [Kodi-vStream/venom-xbmc-addons#1141]
Bonjour,
J'utilise le .py uptobox de john depuis un moment et tout marchait nickel.
Mais maintenant j'ai un soucis je n arrive plus à rentrer dans le rep série ça charge et ça revient sur le choix film et série. Par contre pour les films pas de soucis.
Une idée?

**Comment by johngf** [comment]
apres avoir fait ce que tu essaie de faire vas dans les parametres de vstream clic sur upload log et donne le code ici

**Comment by diouf76** [comment]
Sûrement un truc à vider dans le cache alors. Par contre je suis sur une box Android . Comment je fais pour récupérer le log?

**Comment by johngf** [comment]
c'est ecrit au dessus clic sur upload log normalement upe popup s'affiche avec un code

**Comment by diouf76** [comment]
Je bigle.....

**Comment by Kodigoal** [comment]
Je m'inscrute lol , juste pour savoir si tu comptes @johngf mettre à dispo sur vstream   ta modif pour effacer  les fichiers directement via vstream sur uptobox ? car si maj , ca me vire modif fichier si je fais pas gaffe ^^  et ca servira à ceux qui l'utilisent aussi.

**Comment by diouf76** [comment]
Salut alors j ai fait plusieurs tests, et apparement c est depuis la dernière mise à jour que ca me bug le dossier serie. Je suis retourné dû coups à la 0.4.9

**Comment by Kodigoal** [comment]
Accent pêtre qui bloque dans les titres de série , faudrait le log.

**Comment by diouf76** [comment]
Il n y a pas d accent mais bon je suis retourné sur la 0.4.9 donc plus de soucis et donc log inutile. Après à savoir d ou vient le soucis....

**Comment by Kodigoal** [comment]
Yaura d'autres soucis en restant en 0.4.9.... 
Maj + log =  résolution du problème, aussi simple que ca.
Tant pis.

**Comment by diouf76** [comment]
J ai une autre box qui est en 0.5.1 je testerai dessus ce week-end sinon

**Comment by LordVenom** [comment]
Y a rien dans ton log qui pourrais te porter préjudice, ça vas juste peux être pouvoir nous aider a corriger le soucis repasser en 0.4.9 c'est pas une bonne idée voir https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1140.

**Comment by diouf76** [comment]
Je fais le log ce week end pas de soucis.

**Comment by LordVenom** [comment]
Tu serais tester ce fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/tmdb.py

a remplacer dans plugin.video.vstream/lib/

**Comment by diouf76** [comment]
Ok je teste ce soir

**Comment by diouf76** [comment]
alors j ai remplacé le fichier mais cette fois ci c est film et serie qui ne marchent plus.

**Comment by LordVenom** [comment]
Ha ben j'aurais tenté lol sans le log ont iras pas plus loin.

**Comment by diouf76** [comment]
Je m en occupe ce week end

**Comment by Kodigoal** [comment]
Pêtre au niveau du decodeTitle:( siteuptobox.py)
sDisplayTitle = cUtil().DecoTitle(sTitle)
en 0.4.9 , ya l'ex decodeTitle dans util.py
Depuis maj , c'est  passé en DecodeTitle2 dans util.py.
Le DecodeTitle renvoit juste le string.

**Comment by TmpName** [comment]
Exact, les nouveaux fichiers sites sont incompatible avec les vielles version de Vstream.

**Comment by diouf76** [comment]
salut, j ai voulu faire le log kodi upload et il me transmet un code, comment procéder?

**Comment by LordVenom** [comment]
`PLUGIN] Vstream: could not load site: siteuptobox2 error: UNIQUE constraint failed: season.imdb_id, season.tmdb_id, season.season`

J'ai résolut ce bug tu est sur d'avoir remplacer tmdb.py.

Vide le cache de vstream change le fichier ça devrais revenir en ordre.

**Comment by diouf76** [comment]
Quand j avais mis ton fichier plus rien ne marchait. Là j ai tout re installé et remis la 0.5.1 sans modif le fichier que tu m avais donné. Donc je le re install?

**Comment by LordVenom** [comment]
ben si ça bug toujours oui

**Comment by diouf76** [comment]
Donc sur les prochaines versions cela sera corrigés ?

**Comment by LordVenom** [comment]
Le changement de fichier corrige ton soucis ou pas ?

**Comment by diouf76** [comment]
Pas encore pu essayer là box est dans la chambre de mes filles

**Comment by diouf76** [comment]
J ai re essayé ca bug toujours et j ai vidé le cache de vstream et xbmc

**Comment by diouf76** [comment]
Le code du log : s203rxtSP4

**Comment by LordVenom** [comment]
Je sais pas je vais attendre l'avis de @johngf .

**Comment by johngf** [comment]
siteuptobox2 error: invalid syntax (tmdb.py, line 7)
@diouf76 tu as appuyé sur raw avant ?
sur cette page 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/tmdb.py
clic droit sur raw enregistrer sous vers >> plugin.video.vstream/resources/lib 
ça va remplacé le fichier et reteste

sinon tu ouvre le fichier tmdb avec un editeur tu efface tous et colle ça 
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/lib/tmdb.py

**Comment by diouf76** [comment]
Exact j ai pas pris le raw, je teste ce soir

**Comment by diouf76** [comment]
c'est bon j ai recup le raw et effectivement c’était bien ça le problème et depuis ça marche sous 0.5.1.
