### ISSUE TITLE
Toujours le même qui pose problème 

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1144]
J'ai un probleme avec openload qui me retourne "code js extrait" puis "erreur fichier introuvable" (avec le fichier de TmpName )
J'ai déjà essayer de reinstaller vstream et kodi rien ne corrige le problème merci d'avance

**Comment by TmpName** [comment]
Yep, ils ont fait une petite modif, mais je sais pas si c'est pour nous ou pas, c'est corrigeable cote python.
M'en occupe de suite.

**Comment by Arias800** [comment]
D'accord et encore bravo pour ce script de fou ;)

**Comment by TmpName** [comment]
Lol, bon ben ca va prendre un peu plus de temps, mais je confirme, on nous surveille, y a un pauvre type qui passe tout les jours pour lire notre code et coder une parade ^^.

**Comment by Arias800** [comment]
Donc j'avais raison hier ;)

**Comment by TmpName** [comment]
La j'ai fini l nouvelle version mais je vais la mettre tard en soiree ou demain matin pr tester si ils bossent aussi le WE.

**Comment by Arias800** [comment]
J’espère qu'il bosse pas le WE ça serai bien x)

**Comment by Arias800** [comment]
Bonjour,
Je n'arrive toujours pas a lire de vidéo malgré la nouvelle version du script

**Comment by TmpName** [comment]
Moi c'est encore bon, essayes sur un autre site. ou directement sur le net pr voir si le lien est bon.

**Comment by Arias800** [comment]
J ai tester le lien est bon sur internet mais dans les log ça dit ne pas pouvoir le lire:/

**Comment by TmpName** [comment]
Tu as quoi dans les log ? j'ai rajoute des message d'erreur.

**Comment by Arias800** [comment]
Il y a bien "op...ad(08/04)" qui s'affiche et voila les log : http://slexy.org/view/s201ZhR1EE

**Comment by johngf** [comment]
@Arias800 t'on soucis avec mega stream viens de skin helper service je ne sais pas a quoi sa sert 
Comme addons si tu l'utilise pas desinstalle le

**Comment by Arias800** [comment]
D'accord moi non plus je sais pas il sait installer tout seul x)

**Comment by johngf** [comment]
Pour open load fait plus de teste il y a qu'un test dans ton log sur openload 
Test sur otaku fr derniers ajouts les liens sont récents

**Comment by Arias800** [comment]
Sur otakufr c'est ok ça marche

**Comment by johngf** [comment]
Spli est dispo sur kepli z en lien google beaucoup mieux que openload

**Comment by Arias800** [comment]
Ah je savais pas que google est mieux qu'openload merci pour l'info
