### ISSUE TITLE
manque icones

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1146]
je viens de m’apercevoir que j'ai affecté un icône series_views à la catégorie "Séries (Les plus vues)". Est-ce que vous rajouter un icône ou est-ce qu'il faut corriger les fichiers??

**Comment by johngf** [comment]
quel site ?

**Comment by johngf** [comment]
remplacer par films_views.png c'est pareil

**Comment by razorex** [comment]
Streaming_series_org. Je posais aussi la question parce que les genres (films/series/animes) n'ont pas les mêmes icones à dispo donc peut etre incomplet pour certain ou trop poussé pour d'autres. oui c'est pareil me suis juste dis que c'était volontaire dans le cas ou le skin de vstream évoluait

**Comment by razorex** [comment]
parce que sinon il y a views tout simplement
