### ISSUE TITLE
Nouvelle vignette

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1149]
nouvelle icône pour "streaming_series_xyz"

![streaming_series_xyz](https://cloud.githubusercontent.com/assets/26149640/24792371/fae825b6-1b7d-11e7-85d0-7b41a78d8c1e.png)

**Comment by LordVenom** [comment]
Pas de fond transparent stp.

**Comment by johngf** [comment]
ça pose un probleme avec le theme les fonds transparent? 
les icones que j'ai ajouté pour certains site son transparente parce que je trouve ça fait moins mal au yeux qu'un blanc éclatant

**Comment by razorex** [comment]
Ok. Comme il y en a je trouvais ca pas mal en arrière plan les fonds vstream. Je corrigerai.

**Comment by johngf** [comment]
Wé je prefere aussi les icones transparentes plus agreable a l'oeil

**Comment by razorex** [comment]
En plus les icônes de genres eux sont transparent.

**Comment by razorex** [comment]
nouvelle icône pour "streaming_series_xyz"

![streamzzz_com](https://cloud.githubusercontent.com/assets/26149640/24817446/cfa43728-1bdc-11e7-872f-306ac300d332.png)

**Comment by razorex** [comment]
@LordVenom tu prend pas la nouvelle vignette??

**Comment by LordVenom** [comment]
sisi t’inquiète je ferme pas le post pour m'en souvenir :)
