### ISSUE TITLE
Captcha masqué par zone écriture du clavier

### ISSUE THREAD

**Issue by protozoeus** [Kodi-vStream/venom-xbmc-addons#1150]
Bonjour,

Depuis l'arrivé de KODI 17 et le skin par defaut estuary, La disposition de la barre d'écriture du clavier se superpose par dessus le captcha. Ce qui empêche de lire correctement le captcha.

Auparavant j'utilisais un Fork de KODI 16 avec le skin Estuary Jarvis et je n'avais pas ce soucis. Comment remédier au soucis ?

**Comment by johngf** [comment]
les captchas ne fonctionne pas sur estuary (ça vient de lui) peut etre un jour ils regleront le probleme pour le moment il faut utilisé confluence

**Comment by Arias800** [comment]
Sous kodi 17.1 pas de problème chez moi

**Comment by johngf** [comment]
Arias tu as quel theme, sur quel site tu as testé peut etre le soucis est resolu sur 17.1

**Comment by protozoeus** [comment]
J'ai oublié de préciser mais je suis bien sous la 17.1

**Comment by johngf** [comment]
Je ne sais pas jamais bidouillé de theme et perso je prefere confluence

**Comment by Arias800** [comment]
Personnellement avec le theme de base je n'est pas remarquer de problème de captcha

**Comment by protozoeus** [comment]
@Arias800 Test voir un film qualité HD sur DDL-Island avec hebergeur UpToBox. Tu verra ce que je veux dire.

**Comment by johngf** [comment]
Normalement ça devrait pas fonctionné le sujet a était discuté ici de nombreuse fois dans les issues closed 
Apres peut etre @Arias800 a une version plus recente que la tienne 
@Arias800 Theme de base estuary ? Ou confluence

**Comment by protozoeus** [comment]
@johngf J'ai mis KODI à jour (passage 17.0 vers 17.1) avant hier donc je ne pense pas.

**Comment by johngf** [comment]
Oui mais je dis ça parceque sur linux tu peux avoir des versions plus recente que windows android qui inclue des petites modif sur archlinux notament

**Comment by Arias800** [comment]
Apres peut être que moi le bug ne ma pas dérange ^^

**Comment by johngf** [comment]
tu répond jamais au question........

**Comment by Arias800** [comment]
j'utilise le thème "Estuary"  j'avais pas vu la question :c @johngf

**Comment by LordVenom** [comment]
Peux être utiliser un xbmcgui.ControlEdit avec l'image et c'est lui qui ouvrirais le clavier virtuel comme ça vous avez le temp de lire perso je change le clavier en numerique et j'arrive a lire lol

**Comment by protozoeus** [comment]
J'ai trouvé une solution : Installer le skin Estuary MOD et masquer le clavier pour lire le capta et ensuite ré-afficher le clavier.

**Comment by TmpName** [comment]
Perso, je change de theme direct.
Clavier trop gros, fonctions qui ne servent a rien, je vois pas une raison de garder ce theme. (wé je sais, je deviens lourd avec ma haine envers ce theme de m****)

**Comment by LordVenom** [comment]
Lol

**Comment by LordVenom** [comment]
![capture d ecran de 2017-04-12 13-39-04](https://cloud.githubusercontent.com/assets/4380112/24955860/766a2512-1f85-11e7-9194-266340b09eb5.png)

J'abuse ou pas ?

**Comment by TmpName** [comment]
Nope juste ce qu'il faut pr les malvoyant ^^.

**Comment by LordVenom** [comment]
Non pas trop long ça vas et sur la TV le zoom et bien agréable j ai pas fini mais ça devrais allais.

**Comment by LordVenom** [comment]
fonctionnel sur dll_island quand vous avais 2sec faite moi un retour.

**Comment by protozoeus** [comment]
Ok je vais faire un test des que possible.

**Comment by Kodigoal** [comment]
Pêtre sous krypton utile , mais là sous kodi 15-16  je preferais avant , le clavier couvre l'image et faut mémoriser le catpcha , si on veut le revoir , faut fermer clavier et le remettre , ca efface tout ...

**Comment by LordVenom** [comment]
Hum si tu fait OK au clavier ça efface pas il me semble

**Comment by Kodigoal** [comment]
Oui comme ca c'est ok   mais en validant ca me ferme Kodi à chaque fois.( pas d'erreur dans le log).
Mais avec télécommande box android , c'est chiant ^^
mettre 2-3 lettres , se déplacer sur ok   , relire ,  se déplacer pour réouvrir clavier , écrire ,  déplacer sur ok , déplacer sur valider   ...  ( là bug plantage)
Quand même plus simple avant , écrire +ok.

**Comment by TmpName** [comment]
Il y a moyen via python de savoir quel est le theme utilise ?

**Comment by LordVenom** [comment]
C est pas critiquer mais 6 lettre a retenir 2seconde lol

**Comment by Kodigoal** [comment]
Parfois pas sur que c'est la bonne lettre vu comment c'est ecrit .. tu relis 15x pour être sur lol 
Mais bon comme ca, ca serait pas mal : xD
http://img15.hostingpics.net/pics/170618pic.jpg
On affiche en zoom et petit au dessus comme avant.
Quand je clique sur le bouton valider ( même sans rien mettre) , ca ferme ou plante kodi d'un coup.

**Comment by LordVenom** [comment]
La fenêtre d'information context menu sur un film/information plante aussi ton Kodi ?

![capture d ecran de 2017-04-14 13-17-14](https://cloud.githubusercontent.com/assets/4380112/25041983/b52058a4-2114-11e7-8a6d-dad7a2340373.png)

**Comment by Kodigoal** [comment]
Non pas de soucis sur la fenêtre d'information.
C'est  le getControl(5000).getText()  suivi du self.close() qui crash Kodi. ( enfin sous android)
Vu des posts via google  sur des soucis getControl qui crash kodi.

**Comment by LordVenom** [comment]
Arf chapeau kodi !!! pas d'autre solution ?

**Comment by Kodigoal** [comment]
sans xml pêtre ou si on peut rajouter juste  un control edit dans la class sans passer par le xml , ou en appelant un script à part qui récupère l'input en cliquant sur le bouton valider ( dans l'xml) puis juste if controlID=20 self.close()
Je sais pas trop lol

**Comment by LordVenom** [comment]
Tu pense bien que j ai tester sans XML l input fait n'importe quoi.

**Comment by Kodigoal** [comment]
J'ai bidouillé un truc, pas parfait encore mais ca se rapproche du tien.
https://pastebin.com/69w1rXFn
Testé android kodi 15-16-17
Après faut le retravailler niveau anim et image focusTexture et cie , car la je suis perdu niveau bouton.

**Comment by LordVenom** [comment]
Non ça tourne bien, j'avais pas reussis a mettre l'edit correctement cool :+1:

**Comment by Kodigoal** [comment]
Oui,  pas réussi à contourner ce bug encore , j'essayerais par un script externe voir si ca passe.
On peut aussi tester si version android ( à voir sous linux si même bug) , si oui = ancien code captcha  ,si non = ton code.
Ca prend que quelques lignes l'ancien code.

**Comment by LordVenom** [comment]
Nickel j'ai renvoyer un version sans en attendant la mise a jour officiel avec le xml :)

**Comment by Kodigoal** [comment]
:) modif à venir: icone clavier qui clignote lentement et stoppe quand clavier ouvert  + fix si cancel clavier = petit captcha non visible.

**Comment by LordVenom** [comment]
Aprés voir si tu peux faire la même avec les infos un zoom sur les images d'acteur lol

**Comment by Kodigoal** [comment]
Là ca défile auto d'acteur en acteur.
Tu penses à quoi comme zoom ? 
Genre la photo de l'acteur ou ya le focus s'agrandit un peu en défilant auto ou juste quand on clique dessus ca zoom ( pas beaucoup de place) ? ou si focus sur un acteur , l'afficher au dessus en grand?

**Comment by LordVenom** [comment]
La photo apparais avec un zoom in, fade in par exemple a une place avec l’arriére plan pour pas masque le texte.C'est juste pour avoir une photo un peux plus grande voir avec le nom et le role la c'est tout petit pratique pour voir vite fait mais quand ont veut vraiment l'info c'est plus chiant aprés le défilement automatique utile ou pas ?

**Comment by Kodigoal** [comment]
Compliqué .. Mais réussi à afficher en plus grand avec anim (  fade/slide qui peut stopper , ca dépend des films mais pas génant) , et défilement auto ca le fait comme ca , on peut de toute facln revenir sur un acteur , même si le défilement reprend vite mais suffit pour avoir l'info.
Mieux faire ca va être compliqué avec le Listitem dans le type="list" là , passer par config.py je sais pas comment faire lol
A tester.
Perso j'aime bien ^^

**Comment by LordVenom** [comment]
Hum dans l'idée oui mais tu peux pousser la taille entre le bord de fond noir le haut.et la quand ça soom l'image disparais dans la list vaut mieux utiliser une image affiche au focus avec un anim fade in.

**Comment by TmpName** [comment]
XD, ca fait 2 jours que je lis ce topic, je comprend rien du tout, vous parlez de kodi ou de powerpoint ?

**Comment by LordVenom** [comment]
Tu devrais pas utiliser la list mais fixe l'iamge dans le coin gauche et un slide genre le windows open et utiliser $INFO[Container(50).ListItem.Icon] pour afficher l'image en focus.

**Comment by LordVenom** [comment]
Non tu as raison c'est plus beau dans le slide un peux plus gros alors juste et avoir toujour les images dans le slide la c'est bizard.

**Comment by Kodigoal** [comment]
@LordVenom Voila ce qui me manquait '$INFO[Container(50).ListItem.Icon]'  merci.
Ben avec ca ( + récup des 2  label idem), on peut mettre l'image coin gauche avec anim voir ce que ca donne.
Sinon là ,agrandir un peu , je sais pas si ca va pas bugger  quand ca arrive à la fin de la liste à droite quand ya encore d'autres images qui arrivent .. à voir.
On peut doubler et remettre une image+label en bas pour que ca reste pas vide.

**Comment by Kodigoal** [comment]
Bon agrandit les images+ label haut + image+label manquant en bas.
J'arrête les frais .. ca rend fou xD 
Ps: Pas moyen d'animer si je récupère juste les images à part..
Déjà là j'anime avec 2 conditions et ca fonctionne plus ou moins bien, sinon je sais pas comment faire sinon lol
Si ya un expert en skin qui passe par là pour faire mieux ca serait pas de refus ^^
#1199

**Comment by LordVenom** [comment]
Je peux animer mais au scroll uniquement impossible avec le scroll auto

**Comment by Kodigoal** [comment]
Ca le fait bien à gauche aussi l'image ! plus propre xD
