### ISSUE TITLE
Réécriture Streamzzz

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1154]
Je tente de réécrire le code de Streamzzz (celui proposé n'étant pas fonctionnel) mais la je voudrais votre avis sur la "fonctionnabilité" de mon code, sachant que je réussi à allé jusqu'au liens des hôtes et après plus rien (probablement le pattern de seriesHosters).  Merci de votre aide et de vos explications (le but étant que je comprenne la ou je me loupe) joint mon lien git.

https://gist.github.com/razorex/b5185c48691d2f19f2266da7ed976f9c

**Comment by TmpName** [comment]
Ben ca marche pas trop mal.
J'ai fait quelques modifs https://pastebin.com/ApTG7zwL

Moi j'inverserais les noms des fonctions showlinks et seriesHosters. J'ai modifie un truc pr avoir le bon episode qui s'affiche, y a du travail de reformatage, pr les titres, y a un peu n'importe quoi qui s'affiche. Mais ca tourne.

**Comment by johngf** [comment]
A verif sur l'ancien site qui est utilisé actuellement certaine serie passé par regarder film gratuit a la fin

**Comment by TmpName** [comment]
Ha ?
Ce serait un clone ?

**Comment by razorex** [comment]
Oui @TmpName j'avais vu qu'il faut que je retravaille les titres pas top quand je passe par les nouveautés. 
Clone???? quand je tape le lien je suis automatiquement rediriger..... et pour le nom c'est juste que ca me permet de tester en //

**Comment by johngf** [comment]
pas un clone mais meme proprio il sert a soulager l'autre

**Comment by razorex** [comment]
@TmpName je pensais que seriesHoster était la dernière étape avant la lecture de la série. Tu a testé mon fichier?

**Comment by TmpName** [comment]
Ben pour moi seriehosters affiche des serie et tout a la fin j'affiche les liens avec une fonction showlinks.
Mais c'est pero, personne ira voir ton code.

Pour tester je vais dans:
"serie dernier ajout" "APB S01E09 " "Se01E01" "...Youwatch"

**Comment by razorex** [comment]
@TmpName le problème c'est que ça me bug le passage par les saisons et les genres. Vais essayer de mettre ton code dans le showLinks pour voir ( ce message est surtout là pour ne pas clôturer l'issue).

**Comment by TmpName** [comment]
La j'ai un peu perdu le fil, repasses ta derniere version pr voir ou ca en est stp.

**Comment by TmpName** [comment]
@razorex tu pourrais nous repasser ton code stp ?

**Comment by razorex** [comment]
oui pas de souci je remet à jour celui sur git et je transmet. j'ai pas beaucoup avancé.

**Comment by razorex** [comment]
Mon lien
https://gist.github.com/razorex/b5185c48691d2f19f2266da7ed976f9c

**Comment by razorex** [comment]
ta modif au niveau showSeriesSaison
`def showSerieSaisons():
    oGui = cGui()

    oInputParameterHandler = cInputParameterHandler()
    sUrl = oInputParameterHandler.getValue('siteUrl')
    sThumb = oInputParameterHandler.getValue('sThumbnail')
    sMovieTitle = oInputParameterHandler.getValue('sMovieTitle')
   
    oRequestHandler = cRequestHandler(sUrl)
    sHtmlContent = oRequestHandler.request()
    
    sPattern = '<div class="imagen">.+?<img src="([^<]+)">.+?<div class="numerando">([0-9x]+)<\/div>.+?<a href="([^<]+)">(.+?)<\/a>'

    oParser = cParser()
    aResult = oParser.parse(sHtmlContent, sPattern)
    
    if (aResult[0] == True):
        total = len(aResult[1])

        dialog = cConfig().createDialog(SITE_NAME)
        
        for aEntry in aResult[1]:
            cConfig().updateDialog(dialog, total)
            
            sSXXEXX = str(aEntry[1]).split('x')
            sTitle = "saison " + sSXXEXX[0]  + 'episode' + sSXXEXX[1] + ' ' + str(aEntry[3])
            sUrl2 = str(aEntry[2])
            
            oOutputParameterHandler = cOutputParameterHandler()
            oOutputParameterHandler.addParameter('siteUrl', sUrl2)
            oOutputParameterHandler.addParameter('sMovieTitle',sTitle)
            oOutputParameterHandler.addParameter('sThumbnail',sThumb )

            oGui.addTV(SITE_IDENTIFIER, 'showLinks', sTitle,'', sThumb, '', oOutputParameterHandler)

        cConfig().finishDialog(dialog)

    oGui.setEndOfDirectory()
`

**Comment by razorex** [comment]
et maintenant stremzzz propose des films. c'est pas gagné... (pour moi)

**Comment by TmpName** [comment]
Le probleme c'est que sans ma modif, va dans "dernieres series" prend une serie au hazard et tu vas avoir le meme numero d'episode a chaque ligne.

Sinon je m'etais loupe sur un regex, sur mes test l'episode etait code "3x2", mais dans certains cas c'etait "3 x 2"
Re testes ce fichier, ca marche pour moi si je vais dans la partie genre (teste pr black sails)
https://pastebin.com/9DdERUmF

**Comment by TmpName** [comment]
Ha oui, vires les lignes 244/245/246 pr que que ca fonctionne, et j'ai encore chnage le nom du fichier (pour avoir le meme que l'ancien)

**Comment by razorex** [comment]
@TmpName je viens de testé et çà marche nickel. Donc si j'ai bien compris ce sont les espaces qui posait problème?

**Comment by razorex** [comment]
Ou a tu récupérer ce pattern??
`    sPattern = '<div class="boton reloading">`

**Comment by TmpName** [comment]
En fait quand tu es sur la page principale et que tu cliques sur un lien, ca ouvre une seconde page et c'est que je l'ai trouve (de memoire).
Me sert de l'addon httpfox pr firefox (@johngf t'en avais deja parle aussi) ca aide pas mal pr voir le cheminement du site.

**Comment by razorex** [comment]
Perso moi je trouve çà et pas de <div class="boton reloading">
`<tr id="tvyotCXk1287516">
<td><a class="link_a" href="http://streamzzz.online/links/tvyotcxk1287516/" target="_blank">Telecharger</a></td>
<td><img src="https://plus.google.com/_/favicon?domain=1fichier.com"> 1fichier.com</td>
<td>HDTV</td>
<td>VOSTFR</td>
<td>54 minutes </td>
</tr>
<tr id="tvyotCXk1287516">
<td><a class="link_a" href="http://streamzzz.online/links/tvyotcxk1287516-2/" target="_blank">Regarder</a></td>
<td><img src="https://plus.google.com/_/favicon?domain=openload.co"> openload.co</td>
<td>HDTV</td>
<td>VOSTFR</td>
<td>53 minutes </td>
</tr>
<tr id="tvyotCXk1287516">
<td><a class="link_a" href="http://streamzzz.online/links/tvyotcxk1287516-3/" target="_blank">Regarder</a></td>
<td><img src="https://plus.google.com/_/favicon?domain=youwatch.org"> youwatch.org</td>
<td>HDTV</td>
<td>VOSTFR</td>
<td>53 minutes </td>
</tr>
<tr id="tvyotCXk1287516">
<td><a class="link_a" href="http://streamzzz.online/links/tvyotcxk1287516-4/" target="_blank">Regarder</a></td>
<td><img src="https://plus.google.com/_/favicon?domain=streamin.to"> streamin.to</td>
<td>HDTV</td>
<td>VOSTFR</td>
<td>53 minutes </td>
</tr>
<tr id="tvyotCXk1287516">
<td><a class="link_a" href="http://streamzzz.online/links/tvyotcxk1287516-5/" target="_blank">Regarder</a></td>
<td><img src="https://plus.google.com/_/favicon?domain=allvid.ch"> allvid.ch</td>`

**Comment by TmpName** [comment]
Regarde la page "ttp://str eamzzz.online/links/tvyotcxk1287516-2/" justement.
Mais pas sur que tu puises la voir sans httpfox car elle redirige tres rapidement.

**Comment by razorex** [comment]
Ok j'ai vu avec httpfox.

**Comment by razorex** [comment]
Donc je reviens vers vous parce que j'ai plusieurs problèmes.
 Mon fichier: [ici](https://gist.github.com/razorex/b5185c48691d2f19f2266da7ed976f9c)

- J'ai rajouté un menu recherche par année (inspiré de streamay) sauf que ça me bug tout, plus rien ne marche, pb d'importation de ressources peut être (du genre : xbmcgui) et autres .

- La recherche aussi ne fonctionne pas pourtant il me semble que c'est la bonne Url (ex de recherche:ttp://streamzzz.online/?s=flash)

- Et j'ai voulu supprimer les host qui propose de télécharger en mettant ce pattern    `sPattern` = '<a class="link_a" `href="([^"]+)".+?>Regarder</a><img` src=".+?">(.+?)</td>' dans showLink sauf que j'ai bien ma liste d'host au complet met le premier est vide pas de liens

merci pour votre aide

**Comment by TmpName** [comment]
La recherche par anne ne fonctionne pas car tu vas sur la page site/release/ qui donne un 404.
Le lien doit etre par exemple site/release/2016.

Dans showmovie tu affiches une video sur 2. Utilise plutot le regex
`sPattern = '<div class="poster"><img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'`
Ca ta demarche est bonne, mais pas de bol c'est un des prb de Vstream ^^, il effectue un post traitement qui aide, mais dans ton cas, c'est plutot l'inverse.

Dans ton regex il y a 
`Regarder</a><img`
Alors que moi sur le code html j'ai
`Regarder</a></td><td><img`

Mais tu peux laisser les hotst de telechargement, ca sert a ceux qui on des premiums

**Comment by TmpName** [comment]
Pour la recherche essayes ca
```
    oGui = cGui()
    if sSearch:
        sUrl = sSearch
        sPattern = '<div class="result-item">.+?<img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'
    else:
        oInputParameterHandler = cInputParameterHandler()
        sUrl = oInputParameterHandler.getValue('siteUrl')
        sPattern = '<div class="poster"><img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'

    oRequestHandler = cRequestHandler(sUrl)
    sHtmlContent = oRequestHandler.request()
```

Sinon je viens de voir ton code pr les annees, j'avais pas vu tout le code. Mais la je sais pas trop ou tu pars. Te prends pas la tete et fais comme pr les genres, ya que 15 annes de film.

**Comment by razorex** [comment]
non @TmpName si tu modifie l'année dans l'url tu a des series qui s'affiche alors que sur la page d'acceuil pas de lien

**Comment by razorex** [comment]
merci pour la confirmation xbmcgui. j'ai testé mais pas suffisant.

**Comment by razorex** [comment]
l'avantage de la méthode utilisé dans "streamay" c'est que tu n'a pas une liste interminable comme dans une liste de genres. j'avais pensé tu clic sur le menu "années" sa t'ouvre le numboard tu tape "1985" et valider et la tu fais un truc du genre sUrl= url_main + 'release' + "valeur numboard" et un output sUrl. tous ça dans un "label"

**Comment by razorex** [comment]
et j'avais désactiver la fonction dans showmovies sinon plus rien ne fonctionnais

**Comment by razorex** [comment]
en clair la tu selectionne année tu va dans showmovie la si tu vois "release" dans l'url tu va dans selectAnn
elif 'release' in sUrl:
        sUrl = selectAnn() la tu ouvre le numboard tu tape l'année et retour de sUrl modifié dans showmovie

**Comment by razorex** [comment]
Merci pour ma recherche par année j'ai trouvé et en plus ça marche.

**Comment by razorex** [comment]
@TmpName donc j'ai intégrer tes regex comme çà parce que dans ta version j'avais juste le menu news qui fonctionnais (pas le même code source): mon nouveau fichier [ici](https://gist.github.com/razorex/b5185c48691d2f19f2266da7ed976f9c)

>     if sSearch:
        sUrl = sSearch
        sPattern = '<div class="result-item">.+?<img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'
    else:
        oInputParameterHandler = cInputParameterHandler()
        sUrl = oInputParameterHandler.getValue('siteUrl')
        if '/episodes/' in sUrl:
            sPattern = '<div class="poster"><img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'
        else:
            sPattern = '<div class="poster">.+?<img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'

Sauf que çà me bloque ma recherche par années (qui fonctionnais avant), je sais un menu serais facile à mettre en place mais pourquoi faire simple....

**Comment by razorex** [comment]
je pense que c'est la sortie de mon menu "selectAnn" qui pose probleme

**Comment by razorex** [comment]
Bon personne pour me faire une critique destructive.... pfff pas marrant.

**Comment by TmpName** [comment]
Essayes ca

```
def showMovies(sSearch = ''):
    oGui = cGui()
    oInputParameterHandler = cInputParameterHandler()
    
    if '/release/' in sSearch:
        sUrl = sSearch
        sPattern = '<div class="poster">.+?<img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'
    elif sSearch and not '/release/' in sSearch:
        sUrl = sSearch
        sPattern = '<div class="result-item">.+?<img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'
    else:
        sUrl = oInputParameterHandler.getValue('siteUrl')
        if '/episodes/' in sUrl:
            sPattern = '<div class="poster"><img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'
        else:
            sPattern = '<div class="poster">.+?<img src="([^"]+)" alt="(.+?)".+?<a href="([^"]+)">'
            
    oRequestHandler = cRequestHandler(sUrl)
    sHtmlContent = oRequestHandler.request()
```

Par contre dans seriesHosters retires "Regarder" car sinon les sources de 1fichier n'apparaissent pas, alors que gerees pas Vstream.

**Comment by razorex** [comment]
ok je vais tester. sans "Regarder" sa marche mieux.

**Comment by TmpName** [comment]
En fait dans le code sSearch correspond a ce que tu passes a la fonction showMovies(blablabla), ici sSearch = blablabla.
En general ca ne sert que pr la recherche oui, mais c'est toi qui a insiste pr faire comme ca.

**Comment by razorex** [comment]
ok merci. je pense que c'est parce que je sort "sUrl" et pas "siteUrl" vers showmovie. après j'ai fais une liste ça prend 40 lignes, peut être est ce mieux pour un utilisateur.

**Comment by TmpName** [comment]
Non, mais y a pas de soucis, tu peux continuer comme ca, c'est pas le seul site a faire ca, et il y a quasi aucune chnace que la recherche contienne un jours '/release/'.

```
 sUrl = URL_MAIN + 'release/' + newNum + '/'
showMovies(sUrl)
```

En faisant ca, par defaut le code crois que tu fait une recherche avec cette url, car par defaut showMovies(n'importe quelle url) ne sert que pr la recherche.

**Comment by razorex** [comment]
Si je sortais genre:
        oOutputParameterHandler = cOutputParameterHandler()
        oOutputParameterHandler.addParameter('siteUrl', sUrl)
        oGui.addDir(SITE_IDENTIFIER, 'showMovies', sTitle, 'genres.png', oOutputParameterHandler)
Le code pourrais être généraliser sauf qu'avec le code actu faut "magouiller"

**Comment by razorex** [comment]
3/4 lignes tu pousse quand même. j'ai vu des exemples (avec regex).

**Comment by razorex** [comment]
bon je crois que j'en ai terminé avec Streamzzz. C'est vrai @TmpName, après réflexion, la liste parait plus intéressante pour l'utilisateur. j'ai rajouté l'affichage de la qualité (utile ou pas ???) et de la langue (indispensable) dans le titre au moment de la sélection de l'hotes.

**Comment by TmpName** [comment]
En quelques lignes

```
def showAnnees():
    oGui = cGui()
	
    for i in xrange(1963, 2017):
        Year = str(i)
        oOutputParameterHandler = cOutputParameterHandler()
        oOutputParameterHandler.addParameter('siteUrl', URL_MAIN + 'release/' + Year+ '/')
        oGui.addDir(SITE_IDENTIFIER, 'showMovies', Year, 'genres.png', oOutputParameterHandler)
        
    oGui.setEndOfDirectory()
```

**Comment by razorex** [comment]
lol oui

**Comment by TmpName** [comment]
Ha ok, tu t 'es fait chier a tester tout les liens ^^ ?
Oui, mais si demain ils rajoutent une serie dans une année que tu n 'as pas mise, elle n'apparaitra pas .... (mec qui veut tjours avoir raisons)
Et tu peux inverser l'ordre.

**Comment by razorex** [comment]
Non je n'ai pas tous testez. j'ai regarder avec httpfox (je tente de retenir les leçons) les années présentes et j'ai tester quelques une absentes de la liste , directement sur le site,  et çà me renvoyai une erreur sur la page. pour prouver que je cherche un peu quand même:
`def showAnnees():
    oGui = cGui()
	
    for i in reversed (xrange(1963, 2017)):
        Year = str(i)
        oOutputParameterHandler = cOutputParameterHandler()
        oOutputParameterHandler.addParameter('siteUrl', URL_MAIN + 'release/' + Year + '/')
        oGui.addDir(SITE_IDENTIFIER, 'showMovies', Year, 'genres.png', oOutputParameterHandler)
        
    oGui.setEndOfDirectory()
`
