### ISSUE TITLE
Erreur sur Kodi depuis 1mois 

### ISSUE THREAD

**Issue by flodez33** [Kodi-vStream/venom-xbmc-addons#1156]
Bonsoir les gens, depuis un mois sur mon Kodi 16 j'ai l'application Vstream à jour mais quand je cherche un film ou série , tout est vierge dedans avec un ? Dans un rond symbole d'une bobine de film. 
Merci pour votre aide.
J'ai vidé le cache de l'application et réinstallé mais c'est pareil :(

**Comment by TmpName** [comment]
???
Alors la je vois pas du tout.
Tu es sur quel systeme ? quelle version de Vstream ? Date de la derniere MAJ ponctuelle (celle en passant par la page home de Vstream ).

**Comment by razorex** [comment]
peut être le même pb que moi. mise à jour des sites et hosts

**Comment by Arias800** [comment]
Peut être du a une version de Kofi trop vieille car moi j ai kodi 12 et vstream 0.5 ne passe pas bien je doit faire beaucoup de changement de fichier

**Comment by johngf** [comment]
il a kodi 16 c'est pas trop vieux

**Comment by LordVenom** [comment]
Max 7 jours sans réponse.

**Comment by flodez33** [comment]
Je suis désolé , c'est chez mes parents que le probleme a lieu et je sais pas quand j'y retourne. Je vais essayer de mettre à jour Kodi et reinstaller VSTREAM et si ça marche pas je ferais des captures et tout le reste. merci de vos réponses en tout cas.
