### ISSUE TITLE
enrichissement replay

### ISSUE THREAD

**Issue by bobynou** [Kodi-vStream/venom-xbmc-addons#1160]
Bonjour,

Voici un site pour enrichir la section replay
replaytvstreaming.com

Car pour info Ddlfrench, En quête de reportages, Tntv-rattrapage.overblog.com ne doivent plus être actif (plus de nouveauté) et replay-documentaire ne fonctionne plus.

Merci.

**Comment by johngf** [comment]
Replay documentaire fonctionne mais seulement avec kodi 17 a cause du ssl

**Comment by bobynou** [comment]
Merci johngf effectivement je suis encore sous kodi 16.

**Comment by johngf** [comment]
Moi aussi

**Comment by johngf** [comment]
Pour les autres oui ils,sont abandonné depuis lgts mais certains liens fonctionne 
J'avais deja proposé de les virés

**Comment by TmpName** [comment]
Moi ca me derange pas, au pire les virer le jours ou leur site change, pour ne pas avoir a le mettre a jour.
Il m'arrive encore de chercher de vielles emmissions.

**Comment by TmpName** [comment]
Je viens de voir  replay-documentaire fonctionne (efin leur site) et a des trucs a jours.

**Comment by Kodigoal** [comment]
Ca fait du contenu même si mette plus trop à jour ou plus du tout.

**Comment by johngf** [comment]
Enfin tnt rattrapage pollue quand on recherche une serie

**Comment by Kodigoal** [comment]
ddl-island ya emission tv mais faut passer par toutes le sources ( et minimum un compte gratuit uptobox lol)

**Comment by Kodigoal** [comment]
replaytvstreaming mis sur la Beta, a tester si bug.

**Comment by TmpName** [comment]
@johngf Ca c'est vrai, je vais au moins y mettre un filtre pr eviter ca.

**Comment by LordVenom** [comment]
Pas vue de bug
