### ISSUE TITLE
Comment ajouter le repo de vstream sur iPhone ?  

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1164]
Bonsoir, j'ai installe la dernière version de kodi sur mon iPhone et iPad, mais je ne trouve ps comme t ajouter le repo de vstream.
En effet La source est ajoutée, mais ensuite les dossier ou sélectionzer les zip sont vides ..
Y a t'il une manip spéciale
Merci

**Comment by kikikodi** [comment]
Bonsoir, j'ai installe la dernière version de kodi sur mon iPhone et iPad, mais je ne trouve ps comme t ajouter le repo de vstream.
En effet La source est ajoutée, mais ensuite les dossier ou sélectionzer les zip sont vides .. 
Y a t'il une manip spéciale 
Merci

**Comment by LordVenom** [comment]
Y a pas de source sur le repository de vStream

https://www.youtube.com/watch?v=1uS5gbd8jpE

**Comment by kikikodi** [comment]
Je sais comment le faire depuis un appareil Android, mais qu'elle est la
manip a suivre sur iPhone ?
Je n'arrive pas a trouver, j'ai bien installé kodi mais l'interface n'est
pas du tout identique, y compris pour les extensions...

**Comment by Kodigoal** [comment]
T'as ajouté quoi comme url pour la source du repo?

**Comment by LordVenom** [comment]
C'est ce que je dit y a pas d'url a mettre mais un zip a télécharger mettre une source c'est pour passer par super-repo et autre serveur non recommander.

**Comment by LordVenom** [comment]
Tu peux tester http://atlasweb.net/installer-addonsextensions-vstream-sur-kodi-sous-ios-iphone-ipad-et-apple-tv/ mais pareil je garantis pas l'url ça vient pas de chez nous.

**Comment by Kodigoal** [comment]
Oui je crois si pas iphone&ipad jailbreaké , tu peux pas installer le zip directement via Kodi.
Donc via le lien de LordVenom c'est ok , testé le zip vstream c'est le bon.

**Comment by LordVenom** [comment]
Faudras ce faire une source direct aussi je vais regarder pour faire un truc officiel mais gratos lol

**Comment by kikikodi** [comment]
Justement beaucoup de chose que je trouve pour kodi ou autre est sur ce
site atlasweb, mais il explique comment ajouter kodi sur l'iPhone(fait)
mais apres comment ajouter le zip ? J'ai bien comprit que l'installation de
l'extension vstream etait par zip mais comment le faire depuis l'iphone ?
Sinon a quoi sert d'avoir kodi si impossible d'y a ajouter quoi que se soit
?
Le lun. 10 avr. 2017 à 00:21, Lord Venom <notifications@github.com> a
écrit :

**Comment by LordVenom** [comment]
C'est résolut ?

**Comment by kikikodi** [comment]
Salut lord, non je ne suis pas parvenu à le faire pour être honnête je ne me suis ps encore penché à fond dessus. La version que j'ai installe ne ressemble pas du tout à celle dans la vidéo 
Je te tiendrai au jus 
A plus 

Le 11 avr. 2017 à 14:44, Lord Venom <notifications@github.com> a écrit :

C'est résolut ?

**Comment by Kodigoal** [comment]
Suffit d'Ajouter une source Fichier : 
Url = 'http ://bestkodi.ca/  + nom 'Bestkodi'.
Puis Menu Système/Extentions/Installer depuis un zip/
Choisir emplacement Bestkodi / puis répertoire depots-fr /
et yaura le zip Repository.Vstream-0.0.2.zip

**Comment by kikikodi** [comment]
J'ai bien vu la manip mais où aller dans l appli sur iPhone pour ajouter la
source ?
Je ne trouve pas comment faire

**Comment by LordVenom** [comment]
Paramettre / gestion des fichiers / ajouter une source 

Click sur <Aucun> pour afficher le clavier et saisir l'url 'http ://bestkodi.ca/' puis nom de la source bestkodi de la tu suit le tuto.

**Comment by Kodigoal** [comment]
Avec le theme confluence , c'est en dessous de systeme, ya ajouter une source.
Sinon faut nous mettre un screenshot de l'accueil de kodi voir quel theme tu as.

**Comment by kikikodi** [comment]
Je viens de capter c'était pas ci fluence qui était active comme apparence,
mais celui de base pour Iphone, il n'y a aucun para métrage possible sous
cette apparence.
Le jeu. 13 avr. 2017 à 00:11, Lord Venom <notifications@github.com> a
écrit :
