### ISSUE TITLE
marque-pages

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#1169]
bonjour, par moment (assez rare) quand j'ajoute un marque page le titre est vide 
mais ça m'est arrivé souvent depuis que j'utilise vstream (sur chaque version )
vu que j'utilise les marque-pages comme pense-bête

![screenshot000](https://cloud.githubusercontent.com/assets/21311232/24895452/c74da472-1e90-11e7-8c70-3d9f8a2bfc21.png)

et donc avec la modif récente si on le supprime les marque-pages sont intégralement effacés
a cause de else: dans db.py

sur la photo le titre est vide parfois il y a seulement l'hoster

**Comment by LordVenom** [comment]
A cause de la fonction titre et filename c'est un gros bordel de savoir sur quoi s'appuyer pour avoir le vrai du faux en cour mais résolution dans un bout de temps.

**Comment by johngf** [comment]
En faite j'ai pas precisé ça m'est arrivé sur plusieurs site different je pense je n'ai pas de site préferé
Souvent apres une recherche si je vois un film ou je me dis (a regarder un jours )je le mets en marque-pages

**Comment by LordVenom** [comment]
voir a quoi serv le else et le virer au pire je sais plus j'ai plus le code en tête.

```
        else:       
            sql_delete = "DELETE FROM favorite;"
```
