### ISSUE TITLE
Iptv framapad

### ISSUE THREAD

**Issue by lolema** [Kodi-vStream/venom-xbmc-addons#1172]
Arrivez vous à editer le framapad ? Je voulais ajouter des chaînes mais pas moyen d'ouvrir, 'an error occured'...

**Comment by Kodigoal** [comment]
Même erreur ..

**Comment by LordVenom** [comment]
Le site ne repond pas ont vas attendre de voir un peux.

**Comment by lolema** [comment]
C'est bon tout est revenu à la normale, j'ai ajouté des chaînes mais le changement ne doit pas se faire en instantané avec vstream car j'ai toujours "problème de lecture avec la playlist". J'ai remplacer les '.ts' en '.m3u8' c'est ce qu'il faut faire apparemment pour éviter que cela coupe au bout de 10secondes, en espérant pouvoir essayer cela au plus tôt.
