### ISSUE TITLE
netu

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#1174]
Bonjour à tous tous liens netu ne fonctionne pas notamment sur Disney hd êtes vous au courant du souci ? Merci d'avance

**Comment by TmpName** [comment]
J'ai le meme prb, ca trouve le lien, mouline pendant 1mn, puis erreur, pas sur que ce soit un prb de timeout.

**Comment by sebi0606** [comment]
Salut @TmpName  J'ai testé sur le site Disney hd les liens netu fonctionne si tu peux jeter un oeil merci d'avance

**Comment by TmpName** [comment]
Un probleme de format ?
Le fichier se telecharge sans probleme apparement.

**Comment by TmpName** [comment]
Tjours rien trouve de special, il marche sous firefox mais impossible sous vlc ou media player classic, (alors kodi ....)

**Comment by TmpName** [comment]
Bon j'ai des news, mais pas de bonne, en fait quand on change le header dans une url pr kodi on fait ww.site.com/fichier.m3u|header="nouveau header"

Probleme ca marche pour la partie avec Curl mais pas FFmpeg. Donc la merde doit venir de chez eux.

**Comment by TmpName** [comment]
Je clos cette issue, pour en ouvrir une autre, plus gros probleme que prevu
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1209
