### ISSUE TITLE
[Sources] Je propose 2 sources.

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#1183]
_Salut à tous, je viens proposer 2 nouvelles sources et savoir si cela fonctionnerait car il y a des sources HD et elles font partis des meilleurs sites de DL. Au début j'avais proposer 3 sources qui ont étaient ajouter par la suite.

## La première c'est **ext reme-dow n.in**
![504_media365-sport-news_057_51d_2a5ee83c845f6d421b38a49de8_nasser-al-khelaifi-voit-plus-grand-pour-le-psg_274466_psg_alkhelaifi_280415_ext](https://cloud.githubusercontent.com/assets/12912677/25069986/4e39d024-2291-11e7-9951-a0e587352913.jpg)

## La source contient des liens Premium, donc 1 seul fichier, normalement il suffit juste de cliquer sur 1 bouton (Mais sur Vstream...)

![504_media365-sport-news_057_51d_2a5ee83c845f6d421b38a49de8_nasser-al-khelaifi-voit-plus-grand-pour-le-psg_274466_psg_alkhelaifi_280415_ext](https://cloud.githubusercontent.com/assets/12912677/25069992/742ff628-2291-11e7-9005-2c5fa1539626.jpg)

## Et un système reCaptcha pour les liens comme sur **Dd_l-Isl and**

![6422406_iu6sm-505230-01-02_1000x625](https://cloud.githubusercontent.com/assets/12912677/25070000/9e1b6436-2291-11e7-817b-5b42c50122b4.jpg)

## Voilà pour la première source et la deuxième est **telechrgement.pla nete-series.info**

![504_media365-sport-news_057_51d_2a5ee83c845f6d421b38a49de8_nasser-al-khelaifi-voit-plus-grand-pour-le-psg_274466_psg_alkhelaifi_280415_ext](https://cloud.githubusercontent.com/assets/12912677/25070012/c94ab864-2291-11e7-873a-1eb6166f2948.jpg)

## Tout comme l'autre source il y a des liens premium de plusieurs sources 

![14996225__a1d906b5213c1d44d8ff54ac16ab9b09](https://cloud.githubusercontent.com/assets/12912677/25070016/edf9590e-2291-11e7-8ac7-f119d126ce85.jpg)

## Par contre ce système de sécurité à l'air plus simple mais inconnu

![14996225__a1d906b5213c1d44d8ff54ac16ab9b09](https://cloud.githubusercontent.com/assets/12912677/25070021/0fd449d0-2292-11e7-80fa-03af9d7aabd5.jpg)

_Voilà j'attends vos réponses et savoir si c'est possible ou pas, si quelqu'un a déjà essayer...._

**Comment by TmpName** [comment]
Premier, deja repondu ici
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/517

**Comment by lebigboss** [comment]
@TmpName Merci j'attends la réponse pour le 2eme alors loll
