### ISSUE TITLE
google drive

### ISSUE THREAD

**Issue by zombiB** [Kodi-vStream/venom-xbmc-addons#1186]
Salut à tous 
les liens google drive ne fonctionnent plus tel que sur otakufr est ce possible de vérifier ce bug svp 
merci d'avance

**Comment by Kodigoal** [comment]
Salut,
t'as une série-épisode ou ya des liens googledrive , j'en trouve pas lol

**Comment by zombiB** [comment]
Berserk par exemple c'est marqué youtube comme lien ;)

**Comment by Kodigoal** [comment]
Testé les liens saison 1-2 de berserk , fonctionne de mon côté.
Ya pêtre une limite de temps  de visionnage en place?
ip francaise?

**Comment by zombiB** [comment]
bien vu @Kodigoal  j'ai changé l'ip et ça refonctionne 
merci beaucoup
