### ISSUE TITLE
Aucun fichier trouvé 

### ISSUE THREAD

**Issue by Abeillefan** [Kodi-vStream/venom-xbmc-addons#1193]
Bonjour, je ne crois pas que mon problème soit seulement avec Vstream. Je vous promets par contre que j'ai passé des heures à lire sur  le net par des vidéos YouTube afin de solutionner mon problème. J'avais tenté de demander de l'aide sur le site de Kodi lui-même. Y paraîtrait que j'ai violé les règles, je serais illégale?!  Comment je suis sensée savoir ? Je n'y connais pas grand chose, et je ne parle pas très bien l'anglais. Je fais du mieux que je peux...

J'ai le 17.1 sur Windows et lorsque je fais des recherches sur Vstream ou autre aucun fichiers n'apparaît. Je vois pourtant pendant le chargement qu' y en a des fichiers... Mais à la fin... Rien. Ça fonctionnait très bien avant.. Je peux mettre un log ici? 

J'ai aussi essayé de désinstallé Kodi... Mais mes config restent enregistré alors je me retrouve avec le même problème.  J'ai tenté de chercher ce dossier qui renferme mes config, je croyais avoir tout supprimé et non , tout revient. Pouvez-vous m'aider.  Je suis un brin découragée...  J'utilisais Vstream régulièrement.  Merci

**Comment by Abeillefan** [comment]
12:10:51.626 T:840   ERROR: Window Translator: Can't find window infodialog
12:10:51.648 T:840 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
12:10:51.780 T:840  NOTICE: ActiveAE DSP - starting
12:10:51.862 T:840  NOTICE: initialize done
12:10:51.863 T:840  NOTICE: Running the application...
12:10:51.863 T:840  NOTICE: starting upnp client
12:10:51.880 T:6368  NOTICE: ES: Starting UDP Event server on port 9777
12:10:51.881 T:6368  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
12:10:57.589 T:9200  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting background proc (6.0.15)
12:10:57.654 T:9200  NOTICE: script.tv.show.next.aired: ### no prior data found
12:10:57.761 T:5784   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
12:10:57.761 T:5784   ERROR: CCurlFile::Open failed with code 0 for http://passion-xbmc.org/addons/addons.xml.md5
12:10:57.762 T:5784   ERROR: XFILE::CFileCache::Open - failed to open source <http://passion-xbmc.org/addons/addons.xml.md5>
12:10:57.762 T:5784   ERROR: CRepository: failed read 'http://passion-xbmc.org/addons/addons.xml.md5'
12:10:59.721 T:9200  NOTICE: script.tv.show.next.aired: ### starting data update
12:11:03.375 T:5704   ERROR: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/Seko34/XBMC-Development/master/addons.xml.md5
12:11:03.375 T:5704   ERROR: XFILE::CFileCache::Open - failed to open source <https://raw.githubusercontent.com/Seko34/XBMC-Development/master/addons.xml.md5>
12:11:03.375 T:5704   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/Seko34/XBMC-Development/master/addons.xml.md5'
12:11:03.771 T:5704   ERROR: CCurlFile::Open failed with code 404 for https://offshoregit.com/Addonmaster/exodusfr/addons.xml.md5
12:11:03.771 T:5704   ERROR: XFILE::CFileCache::Open - failed to open source <https://offshoregit.com/Addonmaster/exodusfr/addons.xml.md5>
12:11:03.771 T:5704   ERROR: CRepository: failed read 'https://offshoregit.com/Addonmaster/exodusfr/addons.xml.md5'
12:11:03.892 T:5784   ERROR: CAddonMgr: Failed to parse addons.xml.
12:11:05.899 T:8176  NOTICE: Skin Helper Backgrounds --> BackgroundsUpdater - started
12:11:09.930 T:3780  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.1), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
12:11:12.954 T:7612  NOTICE: Skin Helper Widgets --> Backgroundservice started
12:11:13.018 T:6640  NOTICE: Skin Helper Service --> WebService - start helper webservice on port 52307
12:11:13.019 T:8580  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.13 started
12:11:16.538 T:504  NOTICE: URLResolver: Initializing URLResolver version: 3.0.29
12:11:24.997 T:7672  NOTICE: INDIGO NOTICE: STARTING INDIGO SERVICE
12:11:25.001 T:504  NOTICE: Stream All The Sources: Service: Installed Version: 2.0.171
12:11:25.054 T:504  NOTICE: Stream All The Sources: Service: starting...
12:11:25.141 T:6656   ERROR: [16/Apr/2017:12:11:25] ENGINE Bus STARTING
12:11:25.142 T:6656   ERROR: CherryPy Checker:
                                            The Application mounted at '' has an empty config.
12:11:25.296 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:25.297 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:25.298 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:25.299 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:25.301 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(1/10)...Continuing Service...
12:11:25.801 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:25.802 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:25.804 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:25.805 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:25.806 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(2/10)...Continuing Service...
12:11:25.898 T:6656   ERROR: [16/Apr/2017:12:11:25] ENGINE Serving on http://127.0.0.1:54321
12:11:25.899 T:6656   ERROR: [16/Apr/2017:12:11:25] ENGINE Bus STARTED
12:11:26.306 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:26.308 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:26.310 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:26.311 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:26.313 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(3/10)...Continuing Service...
12:11:26.814 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:26.815 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:26.817 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:26.819 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:26.820 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(4/10)...Continuing Service...
12:11:27.321 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:27.322 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:27.324 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:27.325 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:27.327 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(5/10)...Continuing Service...
12:11:27.827 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:27.828 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:27.829 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:27.831 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:27.832 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(6/10)...Continuing Service...
12:11:28.333 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:28.334 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:28.336 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:28.338 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:28.340 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(7/10)...Continuing Service...
12:11:28.842 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:28.844 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:28.845 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:28.847 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:28.849 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(8/10)...Continuing Service...
12:11:29.349 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:29.351 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:29.352 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:29.354 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:29.356 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(9/10)...Continuing Service...
12:11:29.856 T:504 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:29.858 T:504 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:29.859 T:504 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:29.861 T:504 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT value FROM db_info WHERE setting=? Error: no such table: db_info
12:11:29.863 T:504   ERROR: Stream All The Sources: Service: Error (no such table: db_info) received..(10/10)...Ending Service...
12:11:29.863 T:504  NOTICE: Stream All The Sources: Service: shutting down...
12:11:34.969 T:6188   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Sly\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.genesis\TVShows\
12:15:03.899 T:7672  NOTICE: INDIGO NOTICE: Auto Main Turned off
12:15:03.900 T:7672  NOTICE: INDIGO NOTICE: SCRIPT BLOCKER ON
12:15:03.995 T:7672  NOTICE: INDIGO NOTICE: Checking for Malicious scripts
12:15:08.229 T:4816  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
12:15:08.315 T:4816  NOTICE: 	[PLUGIN] Vstream: call load methode
12:15:11.354 T:4816  NOTICE: 	[PLUGIN] Vstream: Table initialized
12:15:15.262 T:4464  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
12:15:15.310 T:4464  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showUpdate
12:15:28.163 T:4464  NOTICE: 	[PLUGIN] Vstream: Table initialized
12:15:28.455 T:3164  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
12:15:28.476 T:3164  NOTICE: 	[PLUGIN] Vstream: call load methode
12:15:28.488 T:3164  NOTICE: 	[PLUGIN] Vstream: Prochaine verification de MAJ le : 2017-04-19 12:15:28.488000
12:15:29.536 T:3164  NOTICE: 	[PLUGIN] Vstream: Table initialized
12:15:29.578 T:840   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showUpdate&sFav=showUpdate&site=cHome&siteUrl=http%3a%2f%2fvenom&title=%5bCOLOR%20green%5dMise%20a%20jour%20disponible%5b%2fCOLOR%5d
12:15:29.579 T:840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showUpdate&sFav=showUpdate&site=cHome&siteUrl=http%3a%2f%2fvenom&title=%5bCOLOR%20green%5dMise%20a%20jour%20disponible%5b%2fCOLOR%5d) failed
12:15:34.062 T:2808  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
12:15:34.080 T:2808  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showSearch

**Comment by razorex** [comment]
sauf érreur sa dis simplement que tes dépôts sont inaccéssible. Normale exodus.fr est mort et si je ne me trompe pas le liens pour le repo seko ne dois pas être le bon. donc oui rien a voir avec vStream (sauf que tu a une mise à jour en attente en echec)

**Comment by Kodigoal** [comment]
T'as la dernière version de vStream? version 0.5.1
Tu as installé le repo vStream officiel ( pour les maj auto de l'addon vStream zip)
-->repository.vstream-0.0.2.zip
 https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository
Sinon pour tester le zip vStream 0.5.1 directement:
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/download/v0.5.1/plugin.video.vstream-0.5.1.zip

**Comment by TmpName** [comment]
Et tu as SALT aussi qui deconne.
C'est quoi ca ?
` NOTICE: INDIGO NOTICE: SCRIPT BLOCKER ON`

Franchement je sais pas qui a installle ton systeme, mais tu peux tout virer et commencer sur du propre.

**Comment by razorex** [comment]
Indigo c'est la "nouvelle" appli de kodi pour ce configurer. surement un paramètre qui bloque les scripts. C'est configurable depuis indigo

**Comment by TmpName** [comment]
Ben si tu n'es pas un pro avec ce logiciel, le plus simple c'est de le virer aussi.

**Comment by LordVenom** [comment]
Tout les soft qui promette de l’illégal installer facilement, direct à la poubelle pas de superrepo pas d'indigo et autre forks les seul lien officiel tester par l'equipe de vStream sont ceux donner par @Kodigoal.

**Comment by TmpName** [comment]
Désole d'etre aussi agressif, mais on perd patience avec les gens qui installent un peu n'importe quoi ^^.

En resume, pour moi y a trop de boulot a reparer ton systeme, je desinstalle tout, supprime le dossier que je t'ai donne plus haut et reinstalles tout.

**Comment by Abeillefan** [comment]
Merci à tous... @TmpName, je te comprends de perdre patience et merci d'avoir pris du temps pour moi... Par contre, cette fois-ci j'ai compris et je prends des notes. ;) Alors je désinstalle et réinstalle... Merci pour le dossier à supprimer, ça devrait aller. :)

**Comment by Abeillefan** [comment]
Salut à vous tous... J'ai réussi à repartir à neuf, merci. J'ai ajouté Vstream avec les fichiers  zips là-haut... Toutefois, ça lague incroyablement... Merci pour votre aide... J'ai modifier l'option flux vidéo,  ça ne change rien...

**Comment by TmpName** [comment]
Ca laggue, tu veux dire que les videos saccadent ?
Essayes avec un navigateur sur la meme machine (si possible pr voir si c'est pareil, suffit de rechercher le meme site sur internet).
Essayes sur le site "VoirFlm" c'est celui qui a le plus d hebergeurs, pr en tester plusieurs.

Sinon c'est ou l'option "flux video" ?

**Comment by Abeillefan** [comment]
Salut , oui ça saccade...  Ça ne le faisait pas avant avec Jardis 16.0 et Windows 10.  

L'option flux vidéo c'est dans mes additiels,  Flux d'entrée du lecteur vidéo...

**Comment by TmpName** [comment]
2 tests a faire.
1 - essayer avec d'autre hebergeurs (en passant par "voirflm")
2 - essayer via un navigateur si present sur ta machine

Si ca saccade en 2 ca vient de la machine ou de ton debit
Si ca ne saccade pas en 2 mais dans tout les cas en 1, prb sur kodi.

**Comment by johngf** [comment]
regarde si tu n'as pas mis 0 cache dans advancedsettings.xml

edit hier open load fonctionné mais était surchargé impossible de play une video

**Comment by Abeillefan** [comment]
Bonjour à tous, @TmpName , test fait.  Ça ne saccade pas en 2. Alors c'est Kodi... 
@johngf  où c'est advanced settings? Je dois ajouter un add-on? 

Merci

**Comment by TmpName** [comment]
Non, arrette d'installer des addons, ton fameux addiciel, toi tu as juste clique sur un boutton "optimiser" tu ne sais absolument pas ce qu'il a fait sur ta config, ca marche mal et nous on doit deviner.
La modification de cnfiguration se fait a la main pas avec des addons.

http://kodi.wiki/view/Advancedsettings.xml

**Comment by Abeillefan** [comment]
Salut, j'ai tout reparti à neuf. Nouveau Kodi. ;) La seule chose que j'ai ajouté c'est Vstream... Ok je vais regarder ça,  merci 😀

**Comment by Abeillefan** [comment]
@TpmName et @johngf... J'ai jamais fait ça créer des fichiers XML ... J'ai lu l'intro , mais je t'avoue ne pas tout comprendre... Dans le dossier database , je fais comment pour mettre ces fichiers XML ? Et peux tu me donner un exemple avec 2.8.4. Cache... de comment devrait ressembler mon fichier ? C'est vraiment pas clair pour moi... Désolé :/ Merci

**Comment by TmpName** [comment]
Le blocnote, clic droit dans le dossier "nouveau document texte" et tu le renommes advancedsettings.xml (en affichant les extensions sinon tu vas te retrouver avec advancedsettings.xml.txt).
Ou tu lances notepad, "enregistrer sous" et met advancedsettings.xml

Et c'est pas dans le dossier database. tape "%APPDATA%\kodi\userdata" sans les guillement dans un explorateur de fichier.

Pr la manip de @johngf tu peux deja tester ca
```
<advancedsettings>
    <cache>
      <memorysize>52428800</memorysize>
      <buffermode>0</buffermode>
      <readfactor>10.0</readfactor>
    </cache>
</advancedsettings>
```

**Comment by Abeillefan** [comment]
Salut ça saccade toujours. Par contre, avant que la barre noire en bas avec play stop pause disparaisse, ça ne saccade pas. Lorsqu'elle descend ça saccade...

Fanny
De : notifications@github.com
Envoyé : 23 avril 2017 5:09 AM
À : venom-xbmc-addons@noreply.github.com
Répondre à : reply@reply.github.com
Cc : ff_fanny@hotmail.com; mention@noreply.github.com
Objet : Re: [Kodi-vStream/venom-xbmc-addons] Aucun fichier trouvé (#1193)



Le blocnote, clic droit dans le dossier "nouveau document texte" et tu le renommes advancedsettings.xml (en affichant les extensions sinon tu vas te retrouver avec advancedsettings.xml.txt).
Ou tu lances notepad, "enregistrer sous" et met advancedsettings.xml

Et c'est pas dans le dossier database. tape "%APPDATA%\kodi\userdata" sans les guillement dans un explorateur de fichier.

Pr la manip de @johngf<https://github.com/johngf> tu peux deja tester ca

<advancedsettings>
    <cache>
      <memorysize>52428800</memorysize>
      <buffermode>0</buffermode>
      <readfactor>10.0</readfactor>
    </cache>
</advancedsettings>

**Comment by Kodigoal** [comment]
Donc ca saccade au lancement de la vidéo?
Si tu fais pause , t'attend un peu et tu relances play ?

**Comment by johngf** [comment]
et surtout quel hebergeur tu teste ? Open load you watch etc... quel qualité
teste ton debit internet sur le site Speedof.me pour voir

**Comment by TmpName** [comment]
Elle a teste avec un navigateur, et ca passe sans prbs. Bizarre ce truc.
Et ca passe nickel au debut, puis ca saccade, moi ca me le faisait sur flash X et all vid, mais ca veanait de la connexion, (la leur pas la mienne)

Le coup de la pause de @Kodigoal ca marche ?

**Comment by Abeillefan** [comment]
Si je fais pause, la barre noire avec "pause stop play "réapparaît donc ça arrête de saccader. Dès que la barre est là, ça ne saccade plus, dès qu'elle disparaît ça saccade à nouveau ... :( Ça fait ça avec tout les hébergeurs.  Si j'écoute directement sur le net rien ne saccade...

**Comment by Abeillefan** [comment]
@TmpName : Quand tu dis : Mais c'est bizarre que tu ais des soucis sous windws, avec une install clean et parametres de base, ca doit passer tout seul.
Tu aurais pas une video sur ton disque dur, pour tester avec un fichier local ? pour voir si ca vient de la connection ou du reglage du lecteur.

Tu veux que je test une de mes vidéos perso par Kodi?  Que veux tu dire par tester avec un fichier local ( mes fichiers sur mon disque dur) ?

**Comment by LordVenom** [comment]
Oui disque dur c'est Local

**Comment by Abeillefan** [comment]
Test fait download : 17.91 mbps upload: 11.55 mbps

Pour la vidéo, Kodi ne semble pas voir mes fichiers vidéos par parcourir... Faut qu'ils soient en quels format?

**Comment by LordVenom** [comment]
cliquer sur la section Vidéos
- cliquer sur Fichiers, Ajouter des vidéos...
- cliquer sur Parcourir,

**Comment by Abeillefan** [comment]
@LordVenom , c'est ce que j'ai fait,,, et j'ai été dans mon dossier vidéos ...Rien n'apparaît.

Cartes graphiques : Mobile intel(R) 4 séries express chipset...

**Comment by johngf** [comment]
Tu as des videos dans le dossier videos au moins ?

**Comment by LordVenom** [comment]
Lollllllllllllll

**Comment by Abeillefan** [comment]
c'est presque insultant... Ben oui!

**Comment by johngf** [comment]
C'est pas le but mais des fois ici on n'en voie des belles

**Comment by Abeillefan** [comment]
![mes videos](https://cloud.githubusercontent.com/assets/27683824/25314184/fd49a62c-280c-11e7-91e7-8642ff592d8d.jpg)

**Comment by johngf** [comment]
Voila maintenant il faut que tu ajoute ce repertoire a kodi

**Comment by Abeillefan** [comment]
lol je le sais, mais ya rien quand je clique sur le dossier et j'ai testé de faire AJOUTER quand même et ça dit  AUCUN...

**Comment by Abeillefan** [comment]
Je peux te montrer la preuve aussi là ;)

**Comment by Abeillefan** [comment]
Donc vous n'avez aucune idée de mon problème... Pour l'instant? ...Ça ne le faisait pas avec Kodi Jardis... C'est seulement depuis que j'ai intallé celui-là... et par voir le nombre de vidéo youtube qui ont fait pour ce problème, je ne dois pas être la seule ....

**Comment by johngf** [comment]
Oui mais la ça viens pas de vstream mais de kodi si tu n'arrive pas a ajouté un repertoire video

**Comment by Abeillefan** [comment]
Ok, alors je demande à qui pour m'aider alors ?? :/ :/ :/

**Comment by johngf** [comment]
Le truc c'est que chez nous ça fonctionne 
Tu est admin sur ton pc ou invitée

**Comment by LordVenom** [comment]
Nous temps que l'on a pas de réponse a nos question on peux pas avancer et des tuto de configuration Kodi y en a plein sur youtube.

**Comment by Abeillefan** [comment]
Oui ,mais ils te font mettre un paquet d'addons pour parvenir à tes fins....

**Comment by LordVenom** [comment]
Paremettre / paramettre de media / videos ...

ajouter une source video / parcourir  (selectionne ton dossier normal si pas de video)

**Comment by johngf** [comment]
perso je pense que tu t'y prend mal pour ajouté le dossier apres je peux me trompé
Tu as essayé d'ajouté le dossier télechargement ?

**Comment by LordVenom** [comment]
ensuite choisis la catégorie du dossier
![capture d ecran de 2017-04-23 16-25-42](https://cloud.githubusercontent.com/assets/4380112/25314294/8dcebad2-2841-11e7-8c3c-03cd92b6df04.png)

**Comment by LordVenom** [comment]
Peux importe qu'il trouve ou pas ensuite tu vas dans Video/fichier/ le nom du dossier que tu as mis et tes video sont la

**Comment by Abeillefan** [comment]
Tu as raison , comme ça disait aucun, je ne faisais pas OK. tout est là... 
Bon étrangement lorsque c'est une vidéo .3GP ou .MOV ....Ca ne saccade pas avec ou sans la barre  « PLAY PAUSE STOP» 
MAIS ma vidéo .MP4 que j'avais trouvé sur le net , fait comme mon problème, ça saccade ne saccade pas et  lorsque la barre disparaît ça saccade...

**Comment by johngf** [comment]
verifie dans les parametre de kodi tu as un soucis avec ton pilote graphique ou voir si tu la installé le driver intel

**Comment by Abeillefan** [comment]
Si je clique sur le pilote Intel et que je fais mise à jour et que ça dit que Windows confirme que le pilote est bien mise à jour, c'est que c'est ok? 
 Où je vérifie dans mes paramètres Kodi?
Pourquoi ça ne le faisait pas avec Jardis?

**Comment by johngf** [comment]
test ça pour voir si il est activé dxva2 http://kodi.wiki/view/HOW-TO:Enable_Hardware_Accelerated_Decoding_via_DXVA2_in_XBMC_for_Windows

**Comment by Abeillefan** [comment]
Le problème est probablement là car ma carte Intel n'avait pas de mise a jour avec windows 10 sur leur site...  là il l'a sur un autre site, mais est-ce que je peux faire confiance?

https://www.techbrown.com/windows-10-mobile-intel-4-series-chipset-graphics-drivers.shtml

**Comment by Abeillefan** [comment]
Je ne comprends pas grand chose de leurs étapes  :S

**Comment by johngf** [comment]
Cherche le driver sur le site intel c'est plus'fiable

**Comment by Abeillefan** [comment]
Il ne l'a pas avec windows 10, c'est ce que je disais ;)

**Comment by johngf** [comment]
Dans ce cas test avec le site lurl vien de windows update donc c'est bon

**Comment by johngf** [comment]
https://downloadcenter.intel.com/product/81507/Graphics-Drivers-for-Mobile-Intel-4-Series-Express-Chipset-Family
Tu na pas bien cherché

**Comment by Abeillefan** [comment]
Tu vois le windows 10 toi???

**Comment by johngf** [comment]
Non je viens de le voir essaie le 1er site

**Comment by Abeillefan** [comment]
Lorsque je mets le lien qu'ils me donne dans la barre de recherche , ça me donne aucun dossier à extraire...
http://download.windowsupdate.com/msdownload/update/driver/drvs/2013/04/200000265_b70e6e89dc0f24433f6fcc6b33d5f160f30a33cd.cab

**Comment by Abeillefan** [comment]
En effet ça fonctionnait très bien avec le 16... et ce qui est pas habituel c'est que ça saccade seulement quand la barre noire descend et que ça devient plein écran...

**Comment by Abeillefan** [comment]
WinRAR: http://www.rarlab.com/download.htm Je peux faire confiance à ça? C'est sur youtube 👍 
https://www.youtube.com/watch?v=j5Bx8NJ_5iI&ab_channel=3xclu5ive

**Comment by johngf** [comment]
Winrar c'est payant trouve un autre logiciel 7zip etc... il y en a plein 
si t'est pas sur pour un logiciel tu tape sur google son nom + avis

**Comment by TmpName** [comment]
Windows ouvre pas les archive par defaut ? ou uniquement les zip ?
J'arrive juste, dsl de reposer la question ?
"MAIS ma vidéo .MP4 que j'avais trouvé sur le net , fait comme mon problème, ça ne saccade pas et lorsque la barre disparaît ça saccade"
Ca veut dire que tu as dl une video, et qu'elle deconne si tu essayes de la lire en local ?

Tu as essaye d'activer/desactiver l 'acceleration materielle ? (via le lien de @johngf )

**Comment by Abeillefan** [comment]
@TmpName , c'est peut-être pour ça qu'il n'y a rien à décompresser, mais je ne comprends pas plus comment l'utiliser... Je devrai retourner voir les instructions,,,

Pour la vidéo, si je la lis local, tout va bien... Lorsque je la lis par Kodi, ça fait la même chose que le reste.

**Comment by Abeillefan** [comment]
![screenshot000](https://cloud.githubusercontent.com/assets/27683824/25315767/add8566c-2828-11e7-918d-1856647f2c64.png)

**Comment by Abeillefan** [comment]
OHHHH YEAHHHHH!!! Je l'ai DISABLE!!! Ça fonctionne!!!! Merci Les boys!!! Vous venez de faire mon mois au complet!!! <3 MERCI! MERCI ! MERCI!

**Comment by TmpName** [comment]
Mais ca va marcher pr les petites videos, car c'est ton processeur qui fait les calculs du coup au lieu du hardware, il va vite s"essoufler. Moi je serais toi je continuerais a chercher pkoi il est pas a jour.

**Comment by Abeillefan** [comment]
Donc à comprendre ça : http://download.windowsupdate.com/msdownload/update/driver/drvs/2013/04/200000265_b70e6e89dc0f24433f6fcc6b33d5f160f30a33cd.cab

**Comment by Abeillefan** [comment]
C'est sur ce site : https://www.techbrown.com/windows-10-mobile-intel-4-series-chipset-graphics-drivers.shtml

**Comment by TmpName** [comment]
Et en passant pr windows update ?
Tu vas dans le gestionnaire de peripherique, la tu vas galerer un peu pr trouver le materiel, puis clic droit "mettre a jour le pilote", chez moi ca a jamais marche, mais pr des pilotes intel, on peut tjours tester.

et ca ?
https://downloadcenter.intel.com/product/81507/Graphics-Drivers-for-Mobile-Intel-4-Series-Express-Chipset-Family

**Comment by TmpName** [comment]
Intel a une appli en dernier recours, pour trouver automatiquement les pilotes http://www.intel.com/content/www/us/en/support/detect.html Mais j'y crois pas trop ^^.

Penses a le desinstaller apres.

**Comment by Kodigoal** [comment]
Comme dit plus haut, installe 7zip
http://www.7-zip.org/ 
Désarchive le .cab avec,
et suit les instructions du site techbrown.
Ps: moi j'ai le soucis de saccade juste au lancement  vidéo sur box android  , je dois faire pause/play lol j'avais pas ca sous kodi15.2. tablette pas ce soucis.
A voir si je trouve d'ou ca vient sinon retour 15.2 ou 16.

**Comment by johngf** [comment]
pour que l'acceleraton fonctionne correctement il faut le bon driver graphique après sur android ???
faudrait jeter un oeil sur google

**Comment by Abeillefan** [comment]
Les épisodes de ma série durent 1h50... Et seulement vers la fin ça s'est mis à saccader,  mais pas du tout de la même façon.  J'ai fait "Stop" et play et c'est revenu ok. Mais ça ça me le fait aussi parfois avec le 16... ;) Merci de m'aider les gars. Je l'apprécie.

**Comment by Abeillefan** [comment]
@TmpName , j'avais déjà fait les updates des mises à jour Windows des pilotes comme Intel. Mais dans dans l'explication du "RXVA" machin truc... Hihi , ils disent que c'est préférable d'aller chercher moi même le pilote sur le site d'Intel. Et comme de fait, il n'y a pas de pilote pour Intel Windows 10... ;) Je vais regarder ça plus tard et je vous redonne des nouvelles avec vos conseils. Merci encore.

**Comment by Kodigoal** [comment]
@johngf Non sur ma box là elle fonctionne l'accélération , ya 2  cases à cocher/décocher dans Kodi17  :accélération matérielle Mediacodec ( surface) et accélération matérielle Mediacodec.
Le MediaCodec(surface) est une amélioration du Médiacodec simple ( surtout pour le 4K et cie) a ce que j'ai compris.
Et sur ma box , ca améliore rien du tout lol , ca me saccadait vidéo au lancement..
Ca dépend du matos android , tablette pas de soucis avec les 2 activés.

**Comment by Abeillefan** [comment]
Salut est-ce possible de mettre le film v.f. "A street cat named Bob" svp?

**Comment by TmpName** [comment]
Pour le moment j'ai pas trouve de site le proposant en VF.
