### ISSUE TITLE
Bug ADKami

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1198]
la recherche AZ ne fonctionne pas (animés et séries), je pense même qu'elle n'est pas utile puisque nous avons déjà d'autres moyens d'accès. Je tente d'être plus précis. Quand je fais animés ou series j'ai tous Vf et vostfr et j'édite la liste de A à Z. Quand je fais animés ou séries vf j'ai les vf qui s'affichent en liste de A à Z (même les vostfr) et pareil pour les recherche par VOSTFR. Alors avant de supprimer quoi que ce soit est-ce que vous êtes d'accord avec moi?

**Comment by razorex** [comment]
Et quand je fais une recherche des genres par langues (tous) soit version 0 ne fonctionne pas. dés que je choisi vf (1) ou vostfr (2) çà marche..

**Comment by TmpName** [comment]
Deja je te rappelle que tout le monde ne passe pas par Animes/VF moi je passe tjours par "toute les sources".
Sinon tu as raisons, si l'user trouve pas a VF il passe en VOSTFR, ca diminue la liste qui est franchement enorme. Par contre suis pas sur que ce filtre soit 100% precis.

Par contre pr les genres, c'est filtrage par genre, pas besoin de filtrer la langue aussi.

**Comment by razorex** [comment]
Oui je sais que tous le monde ne passe pas par les mêmes chemins (et je aussi que bcp d'utilisateur ne passe pas par les sources) . je remonte un pb c'est tout. Et justement comme je l'ai dis le menu "Animés AZ" accessible depuis "toutes les sources" ne fonctionne pas!
Le filtrage par genres sans tenir compte de la langue (version 0) ne fonctionne pas justement. j'ai testé les genres en mettent directement l'url (tous type) dans le fichiers genre sa marchais, vStream m'affichais bien tout .  Pas besoin de filtrer par langues ok, celui qui a fais le fichier a jugé utile de le faire, mais oui sa simplifierais les choses.

**Comment by TmpName** [comment]
Normallement c'est bon, j'ai mis un nouveau fichier exactement comme tu viens de le decrire (uniquement Vf et VOSTFR et sans langues pr les genres) il y a 2h en meme temps que mon post mais je suis pas partis de la derniere version que tu avais mise, donc j'ai remodifie apres, mais j'ai du zapper des trucs, dsl.

**Comment by razorex** [comment]
ah oui expéditif la..
