### ISSUE TITLE
Possibilité d'ajout d'une section de recherche par année ? 

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1200]
Bonsoir,
Serait il possible d'ajouter une forme de recherche par année ? Cela serait sympa je trouve de manière a avoir la sélection annuelle? 
Merci à vous 
Mika

**Comment by razorex** [comment]
proposer par certains sites sokrostream par exemple (sera fonctionnel à la prochaine MàJ).

**Comment by kikikodi** [comment]
Donc en gros si le site ne le propose pas impossible pour kodi de le détecter ? 
Par exemple sur exodus la recherche annuelle y est et j'i l'impression qu'elle est générale

**Comment by razorex** [comment]
oui c'est bien çà. faut voir sur quel site il récupère ces liens.

**Comment by Kodigoal** [comment]
Tu peux passer par recherche visuelle/ top imdb , top Film 2016-2010.

**Comment by kikikodi** [comment]
C'est quoi exactement Imdb?

**Comment by kikikodi** [comment]
Ok j viens de voir c'est l'équivalant de allo ciné pour les notes
appréciations des films... C'est bien ca ?
Le mer. 19 avr. 2017 à 15:19, MICHAEL ben ghozi <ecorendezvous@gmail.com> a
écrit :

**Comment by kikikodi** [comment]
Je viens de tester sur kodi/ iPhone
Je bois bien imdb dans recherche visuelle, effectivement le best mondial,
les 250 premiers et apres la recherche par années, mais lorsque je
sélectionne une année ou les autres rien ne se passe , vous aussi ?

Le mer. 19 avr. 2017 à 15:21, MICHAEL ben ghozi <ecorendezvous@gmail.com> a
écrit :

**Comment by LordVenom** [comment]
Non mais sur un téléphone... serieux c'est pas fait pour.Pas vue de soucis moi.

**Comment by kikikodi** [comment]
En déplacement... Entre deux Rdv... Faut bien tuer le temps... Un ptit
épisode de Vkings  fait l'affaire ;-) enfin je testerai ce soir à la
maison.
Aussi j'en profite, vstream est 10 fois plus long sur ma box Android que
sur l'iPhone y a t'il une explication ?, cela vient il de ma box ou cela
est le cas sur tous les systems Android ?
Le mer. 19 avr. 2017 à 15:50, Lord Venom <notifications@github.com> a
écrit :

**Comment by Kodigoal** [comment]
Ce soucis a été corrigé , basculé en maj auto ya 13 jours (fichier topimdb.py ), t'as pêtre pas le dernier sur ton tel car ca liste bien les films ( même sur mon tel lol )

**Comment by LordVenom** [comment]
Box android à 2€ avec moin de memoire vive que ton tel a 600€ simple non :)

**Comment by razorex** [comment]
De plus en plus de sites proposes des recherches par années, beaucoup ne sont pas encore "déclaré" dans leurs plugins. Peut être que dans un avenir (plutôt proche) il y aura un menu général ce qui permettra de référencé les sources qui proposent de faire une recherche sur une année bien précise.

**Comment by kikikodi** [comment]
Ouai exact mais ma box a tt de meme 8go de mémoire vive
Donc je ne pensais pas que cela pouvait faire ramer autant.
En tout cas bon boulot comme d'hab et reponse toujours rapide, même si
questions un peut bêtes pour vous, pour moi

Le mer. 19 avr. 2017 à 16:38, Lord Venom <notifications@github.com> a
écrit :
