### ISSUE TITLE
problème installation sur raspberry pi 3

### ISSUE THREAD

**Issue by Arno13** [Kodi-vStream/venom-xbmc-addons#1207]
Bonjour,
J'ai recement fait l'acquisition d'un raspberry pi 3.
J'ai installé beeryboot pour abtenir un triple boot avec kali retropie et openelec (version 6.0.3).
Je rencontre un problème avec l'installation de vstream.
J'ai bien télécharger le depot vstream grâce à l'url de fusion.tvaddons toutefois quand je veux l'installer à partir d'un fichier zip, je trouve bien vstream ( version 0.0.2) mais le dossier est vide, aucune extension ne m'est proposée.
j'ai cherché partout sur le net. Et il me semblait avoir trouvé une solution en validant source inconnue dans les paramètres mais je ne peux cocher l'option car elle est absente (et j'ai bien cherché....)
je suis novice en la matière alors pardonnez moi si je n'utilise pas le vocabulaire approprié...j'espère que vous avez cerné mon problème et que vous pourrez me donner un coup de main.
merci par avance

**Comment by razorex** [comment]
après il te faut passer par "installer depuis un dépot" plus par "à partir d'un zip". et tu va te faire engueuler faut utiliser le dépot vStream télécharger ici

**Comment by Arno13** [comment]
J'ai téléchargé le depot sur ce site et installé celui que j'avais mais cela ne fonctionne toujours pas. les extensions n'apparaissent pas...

**Comment by Arno13** [comment]
je voulais dire désinstallé celui que j'avais

**Comment by Arno13** [comment]
j'ai installé celui trouvé à  cette adresse:
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository

**Comment by Kodigoal** [comment]
@Arno13 Tu as quelle version de Kodi ? 
Tu as fais comme a dit @razorex ?

**Comment by Arno13** [comment]
J'ai installé openelec via berryboot. C'est la version 6.0.3 de openelec.
Et j'ai bien fait comme me l'a conseillé razorex toutefois quand je vais dans le dépôt, il y a bien le dépôt vstream mais il n'y a aucune extension à installer...

**Comment by Kodigoal** [comment]
Installe le zip de l'addon vstream directement:
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/download/v0.5.1/plugin.video.vstream-0.5.1.zip

Sinon je vois pas trop le soucis avec le dépôt, si c'est le repo officiel , devrait yavoir le zip.

**Comment by TmpName** [comment]
Lol, @razorex arretes de nous faire passer pour des monstres.

**Comment by Arno13** [comment]
Quand j'essaie d'installer le zip de l'addon (installer depuis un fichier zip), cela l'indique que la dépendance n'est pas respectée!
Est ce que je me trompe sur l'endroit où je dois l'installer?

**Comment by Arno13** [comment]
Alors pour info, je suis allé vérifier dans mes reporitorie les extensions qui s'affichaient et j'ai pu l'apercevoir en allant dans l'onglet situé verticalement sur la gauche que je pouvais modifier certaines options. J'ai alors coché de faire apparaître les éléments incompatibles. C'est alors que l'extension  vstream est apparue ( version 0.5.1). Toutefois, elle est indiquée comme incompatible et je ne peux l'installer. Que puis je faire?

**Comment by Arno13** [comment]
C'est un kodi 15.2
Quelqu'un peut il m'aider?

**Comment by TmpName** [comment]
Et sur raspberry la V17 ne marche pas ?

**Comment by Kodigoal** [comment]
Déjà perso vu que la dernière version openelec est la 8.0.1( = avoir  kodi 17.1 ) , je mettrais à jour openelec....
Ensuite  faut faire comme t'as dit @TmpName pour trouver la dépendance qui pose problème lors de l'installation du zip vStream .
Après  tu peux essayer de rebooter sous openlec, réinstaller le zip vStream 5.0.1 , et récuperer le log Kodi a cet emplacement (/storage/.kodi/temp/kodi.log) et le copier-coller sur pastebin(.com) et nous donner le lien ici qu'on y voye plus clair.
Mais bon je m'embéterais pas à rester sous openelec 6.0.3 lol

**Comment by LordVenom** [comment]
Perso j ai pas trouver kodi 17 sur openelect je suis passer sous libreelect même système d installation mais plus de mise a jour.

**Comment by Kodigoal** [comment]
ben faut installer la 8.0.1 non ?
 http://openelec.tv/news/22-releases/185-stable-openelec-8-0-1-released
Avec son beeryboot par contre , ya des manips à faire pour mettre à jour manuellement openelec.

**Comment by Arno13** [comment]
Merci beaucoup, je vais suivre vos conseils et tenter d'installer la version 8.0.1 avec les indications du post en anglais. 
Je vous tiendrai au courant de mes avancées.

**Comment by LordVenom** [comment]
Je préfère https://libreelec.tv/downloads/ leur site et plus compréhensible et c'est le même système il suffis de mettre les fichiers de mise a jour dans storage/.update/ et op.

**Comment by Kodigoal** [comment]
Peut le mettre aussi en multiboot pour comparer xD
Par contre via beeryboot , le hic c'est que ca lance des images squashfs des Os ( pour ca que le site au dessus là s'amuse à convertir les différentes images des os en image squashfs et les mettre à dispo , au lieu de convertir soit même) et rien n'est jamais écrit dans cette image , tout est à part .. donc pour les maj ca se passe pas comme si t'avais juste openelec ou librelec installé normalement.
T'es obligé de faire des manips , à moins qu'ils ont changer le système depuis... Posts de 2015 qui explique le binz lol
https://github.com/maxnet/berryboot/issues/151

**Comment by mmtest1** [comment]
osmc tourne bien également sur rpi

**Comment by Kodigoal** [comment]
@Arno13 des News?

**Comment by Arno13** [comment]
Désolé de répondre un peu tard mais effectivement en installant la dernière version d'openelec via USB sur berryboot. Tout fonctionné impeccablement! Merci à tous de vos conseils avisés

**Comment by Kodigoal** [comment]
xD tant mieux. 
Même principe quand yaura nouvelle version dispo sur le site officiel openelec ,  si tu veux maj la dernière version ,  garder sous le coude le site qui met à dispo les images pour berryboot et procèder comme t'as fait là.
Et il propose aussi les  maj images retropie j'ai vu , kali pêtre aussi..
