### ISSUE TITLE
Hebergeur Net _U

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#1209]
Bon la y a un soucis, si quelqu'un vois une erreur ou a plus d'infos que moi je suis prenneur.
Alors depuis quelques jours cet hebergeur ne marche plus sur Vstream. Dans kodi pour passer une url avec un header on utilise la commande ww.site/fichier.m3u\User-agent=blablabla.

Probleme, l UA marche bien pr le premier fichier, mais celui ci contient des fragment de fichiers et a ce moment la Kodi n'utilise pas l'UA.
Pr moi le prb vient de chez eux, j'ai meme verifie le code source pr etre sur, mais pour le moment j'ai pas d'info, et vu qu'ils sont aussi reactif que des huitres, c'est pas gagne.

La attend d'avoir plus d'info, mais je cherche une alternative. Il y a quelques annees on pouvait refaire soi-même un fichier m3u en local en rajoutant l'UA dans les urls, c'est bon ca aussi ils ont supprime.

Pour le moment la seule solution que je vois (et que je n'ai pas encore testee) c'est de faire une playlist kodi avec les fragments, probleme le code de Vstream marche avec des urls, pas des playlists.

**Comment by TmpName** [comment]
Ok, bon apres quelques tests.
Je fabrique une playlist, je la lance, ok ca marche mais entre chaque morceaux, un freeze.

Pkoi quand c'est un fichier m3u ca enchaine direct ?

**Comment by johngf** [comment]
c'est pas une histoire de player qui stoppe et reprend

**Comment by TmpName** [comment]
Yep, je pense, j'utilise ca http://mirrors.xbmc.org/docs/python-docs/13.0-gotham/xbmc.html#PlayList
Mais je vois pas d'autre solution, car si je fais un fichier m3u je peux pas rajouter l'UA dedans.

**Comment by johngf** [comment]
Ça me fait pensé que certaine video sur now video utilise maintenant le dash video audio séparé il faut un autre addons pour les lire ? Fichier mdp comme une playlist avec 2 m4s dedans 1 audio 1 video

**Comment by TmpName** [comment]
Il y a 1 an, un autre hebergeur faisait pareil puis a laisse tomber. Mais je croyais que maintenant kodi gerait les dash ?
Le fichier mdp ne se lit pas ?

**Comment by johngf** [comment]
Non kodi ne le gere pas apparement j'ai cherché vite fait sur le net

**Comment by TmpName** [comment]
Moi j'ai trouve ca https://github.com/peak3d/inputstream.mpd
Sinon livestream (l'addon de shani) doit le faire, et je pense que tu l as deja sur kodi.

**Comment by TmpName** [comment]
Tu aurais un exemple sur now video que je teste ?

**Comment by johngf** [comment]
Sur voir film sundown je pense

**Comment by TmpName** [comment]
Sinon pr netu je viens d'essayer de creer en local un fichier m3u, pour mettre dedans le lien m3u de net _u pr qu'il ne detecte pas le format. Probleme on ne peut pas mettre d'user agent avec un fichier local, du coup impossible de passer L'UA.

Sinon je viens de trouver ca pr les dash http://forum.kodi.tv/showthread.php?tid=237356&page=4

**Comment by johngf** [comment]
Pour ne tu un fichier strm fonctionnerai pas ? Bien que je ne sais pas trop comment fonctionne ce type

**Comment by TmpName** [comment]
Si tu veux faire un fichier strm c'est pas dur ^^, tu vas sur le dernier lien et tu le rajoutes en librairie, la librairie ne fonctionne que avec des fichier strm.

Pour le moment je vois que 2 solutions, lecteur externe et version de fichier modifiee (et je cherche le fichier la). A ce sujet vlc non plus ne lit pas les mdp pr le dash.

**Comment by TmpName** [comment]
Bon j'ai trouve comment faire tourner net_u mais chez moi ^^.
J'ai directement edite le fichier avformat-57.dll avec un editeur exadecimal, difficile de mettre ca en oeuvre chez tout le monde ....

**Comment by johngf** [comment]
bon en faite inputstream et rtmp sont deja dans kodi 17 mais désactivé par défaut reste a trouvé comment le faire fonctionné
ht tps://www.tvaddons.ag/rtmp-streams-krypton/

**Comment by johngf** [comment]
bon j'ai réussi mais il faut que l'user active inputstream dans extensions ou le faire activé via vstream ?

**Comment by TmpName** [comment]
Oui tu peux lire un fichier local via Vstream, mais tu peux pas passer d'user-agent.

**Comment by johngf** [comment]
oui j'y arrive en local mais avec le meme fichier via vstream ça fonctionne pas

**Comment by TmpName** [comment]
Ha oui, je viens d'avoir le meme probleme pr la librairie.
Je vois 2 solutions.
- Rajouter une bidouille dans notre lecteur pr gerer les strm via l'extension.
- gerer le code de lecture dans le meme fichier (le fichier hoster si j'ai bien compris ? )

**Comment by johngf** [comment]
pour ne_tu tu as essayé setAudioStream() setVideoStream()
ht tps://codedocs.xyz/xbmc/xbmc/group__python___player.html

**Comment by TmpName** [comment]
C'est juste pr le cas ou plusieurs flux audio/video sont dispo.
Il y a juste 2 ligne a changer dans le code source en c++, mais je vais pas installer tout l'environnement pour le recompiler.
La j'ai ouvert un ticket, suffit qu'un mec motive passe par la, j'ai meme indique les modif a faire.

Mais c'est tellement des pipes que j'ai l'impression de pisser dans un violon. Jamais vu une communautee aussi morte (et pourtant j'en ai teste pas mal sous linux).
Si dans quelques jours, j'ai toujours pas de reponse je ferais carrement un pull request sur leur github, mais sans tester mes modifs.

**Comment by johngf** [comment]
pour les strm dash j'arrive a play en bidouillant mais j'ai toujour une erreur
ERROR: XFILE::CDirectory::GetDirectory - Error getting ...
ERROR: CGUIMediaWindow::GetDirectory...
vu que l'url est de ce type plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=etc..
alors que ça devrait etre le chemin ou est le fichier strm c:\etc...

on peut la changé sans raffraichir la fenetre ?

**Comment by TmpName** [comment]
Je ne sais pas comment tu procedes mais j'arrive a creer un fichier m3u et le passer via un fichier hoster (netu.py dans mes tests) a la place d'une url, et il se retrouve execute comme un lien normal.

Il n'y a pas moyen de faire ta "magie" dans le fichier nowvideo et repasser le lien du fichier local a la place de l'url ?

**Comment by johngf** [comment]
oui m3u ou autre c'est ok mais la avec c'est inpustream qui gere la connection au site, le keep alive ,header et le reste donc ça play mais kodi me met une erreur vu que que le repertoire n'est pas le bon

**Comment by TmpName** [comment]
Exact la methode avec self.play( sUrl, item ) ne marche plus.
Si on met un timer, ca marche le temps du timer, puis ca plante.

**Comment by TmpName** [comment]
J'en suis au meme point que toi, j'arrive ala faire fonctionner en mettant 
xbmcplugin.endOfDirectory(sPluginHandle, True, False, False)
a la fin de la lecture mais j'ai beau mettre des stop(), le player recommence a lire la video suivant de la playlist imaginaire et me donne le meme message d'erreur.

**Comment by TmpName** [comment]
Si je met a la fin de la fonction def run(self, oGuiElement, sTitle, sUrl):
ff(mm)
Pr provoquer une erreur
Le film tourne nickel puis message d'erreur comme quoi la lecture a rate mais il s'arrette cash

Et si je met 
            xbmcplugin.endOfDirectory(sPluginHandle, True, False, False)
            gg(mm)

Il re-essaye de lancer une seconde video imaginaire avant de planter, donc la commande xbmcplugin.endOfDirectory suffit a delcancher le prb.

**Comment by johngf** [comment]
J'ai essayé toute les methode pour play via xbmc possible et c'est pareil
C'est un probleme de fin de repertoire ou pas quand on clique vu que addhost lance un lien playable qu'on utilise pas pour utilisé xbmcplayer je pense enfin pas encore trouvé la soluce

**Comment by TmpName** [comment]
Ben la fonction xbmcplugin.endOfDirectory sert justement a ca. C'est pr ca que je pensais que c'etait la solution, mais c'est pire ....

**Comment by johngf** [comment]
Et si tu rajoute return pour arreter le script ça stop aussi le player et erreur comme meme

**Comment by johngf** [comment]
je pensé avoir trouvé le probleme mais la soluce proposé fonctionne pas
[ici](https://github.com/maxgalbu/xbmc.plugin.video.nba/blob/master/docs/bug_description.one_or_more_items_failed_to_play.md)

**Comment by TmpName** [comment]
Ben je sais pas, nous ca lance la video sans probleme, c'est quand on la ferme que ca deconne, regarde les logs quand les video tourne, tout est ok, puis quand tu la fermes, kodi essaye d'en relancer une ( j'ai essaye de faire un clear playlist mais je sais pas ce qu'il essaye de lancer).

Sinon on ne tourne que avec setResolvedUrl et on vire la partie avec play() ?

**Comment by johngf** [comment]
Bah le truc c'est que setresolveurl ne fonctionne pas avec les strm c'est ce qui m'embete trouvé comment play sans erreur
Apres les autres play ne servent pas pour les liens habituel dans vstream

**Comment by johngf** [comment]
Tu'as essayé avec ne_tu de faire un strm pour play ?

**Comment by TmpName** [comment]
Ha, j'avais pas vu ce prb.
Mais suis sur qu'il ya moyen de lire un strm via setresolveurl, je vais voir de ce cote.
Pr netu, ce que je veux c'est justement empecher L'UA auto, il me faut mettre exactement le meme du debut a la fin. Mais j'ai pas teste inputstream , j'attend que tu sortes ton code pr tester ^^.

Vais voir pr les strm via setresolveurl.

**Comment by johngf** [comment]
teste ce fichier via kodi en activant inputstream dans extensions https://github.com/johngf/divers/blob/master/kodi/dash.strm

ensuite test avec setresolveurl via vstream

**Comment by TmpName** [comment]
Bouh que ca me saoule en ce moment kodi.
Je testerais ton code demain, mais la effectivement ca passe pas.

Je te propose de modifier le lecteur pr qu'il regarde lextension du fichier et si c'est *.strm methode avec play (je sais comment la faire marcher, meme si il y a un mess d'erreur dans les log). Faut juste virer la ligne xbmcplugin.endOfDirectory(sPluginHandle, True, False, False) et la remettre en fin de fonction uniquement si on passe par la methode play.

Et avec xbmc.executebuiltin( "PlayMedia("+sUrl+")" )

**Comment by johngf** [comment]
j'y arrive avec l'erreur mais je cherché a la viré

**Comment by TmpName** [comment]
Ha !
J'ai peu etre une piste pr toi.
Le manager de dl de Vstream utilise play() et sans message d'erreur.
En fait il fabrique une playlist avec l'url au lieu de chercher a lire l'url, mais je me souviens plus comment ca fonctionne dans le player .....

**Comment by johngf** [comment]
Je sais pas parceque inpustream gere le truc est c'est deja du dl 
Il dl met en cache dans un dosier

Pour l'erreur que tu as donné elle est toujours la

**Comment by TmpName** [comment]
Bon alors chez moi meme avec play() le strm ne marche pas, oblige de passer par kodi directement, par contre j'ai un code qui ne provoque pas de messages d'erreur.

Mais il faut supprimer les lignes de codes qui servent a rien petit a petit, car j'ai fais a tatons
https://pastebin.com/CBev07cm

Et surtout ca bypasse le lecteur de Vstream, donc pas bon non plus.

**Comment by johngf** [comment]
Il y a une nouvelle methode que j'ai trouvé et vais testé demain avec setresolvurl on verra bien

**Comment by johngf** [comment]
bon c'est ok avec la modif que j'ai proposé

**Comment by TmpName** [comment]
Yep, j'ai vu le code, ca va vite etre indispensable a mon avis.
Cet apres midi je teste avec netu meme si j'y crois pas trop.

**Comment by johngf** [comment]
bon alors ok ru s'y est mis aussi mais seulement en bonus on as toujours les fichiers normal j'ai fait le code pour les fichiers normal mais pas verif pour les ancienne videos

**Comment by TmpName** [comment]
Je pense que tout se met a jours tout seul, par contre tu le vois ou le dash en bonus, j'ai teste 2/3 videos sans le voir.

**Comment by johngf** [comment]
dash hlsManifestUrl pas pris en compte

**Comment by TmpName** [comment]
Pas vu de soucis.

**Comment by johngf** [comment]
@TmpName  tu veux bien testé ça [ici](https://github.com/johngf/divers/blob/master/kodi/cloudy.py) pour clou dy j'ai mis des annotations en bas 
soucis avec les mp4 meme sur firefox seul les flv fonctionne 
comme j'ai une ip mobile on sait jamais

**Comment by TmpName** [comment]
Pr le moment je galere, le site clouyd est HS
`This video is being prepared! Please try again later!`

**Comment by johngf** [comment]
j'ai mis des annotation en bas voir films

**Comment by TmpName** [comment]
Sinon le lien que tu as mit en bas du code (et c'est le seul que j'ai trouve), marche dans les 2 cas chez moi  flv et mp4.
La j'attend quelques heures que ca revienne.

**Comment by johngf** [comment]
apparemment la plupart des mp4 ne fonctionne pas sur le net les flv par contre ok

**Comment by TmpName** [comment]
Mais tu l'as trouve ou ton exemple ?
Moi sur le net j'ai tout de HS "This video is being prepared! Please try again later!" pas moyen de trouver un lien valide pr tester.

**Comment by johngf** [comment]
je crois sur google en recherchant clou dy.ec dans videos

**Comment by TmpName** [comment]
Bon je lache l'affaire, pr moi c'est bon.
J'ai ete sur leur site, pris une video au hazard et ton code a fonctionne pr les flv et les mp4.

Sinon pr en revenir a l'issue, Netu remarche pr disney.
