### ISSUE TITLE
Téléchargement (Bêta)

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1215]
@LordVenom il est possible de télécharger une copie du git vStream en entier, peut tu faire en sorte que l'on puisse aussi ne télécharger que le dossier vStream (beta) car pour l'instant je n'ai toujours pas réussi à résoudre mes pb de mise à jour et pour travailler sur les derniers fichiers sa éviterais de récupérer+ de 200mo de fichiers

**Comment by LordVenom** [comment]
Hum tu vas te faire taper sur les doigts lol, Page d'accueil du git rubrique contribuer y a un lien pour télécharger la bêta.Mais vue que tu participe tu devrais installer un logiciel de git et cloner comme ça tu seras toujours a jour.

**Comment by TmpName** [comment]
Sinon moi je copie/colle les fichiers 1 par 1, ca va assez vite.
