### ISSUE TITLE
Recherche visuelle

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1217]
Je suis entrain de modifier la recherche visuelle (une histoire de dossier que je met en ordre) bref. Encore et toujours les series me gène "allez dans un épisode pour en faite rechercher la séries", ça me gonfle donc je propose purement et simplement de virer tous les sous menu showsaison et showepisode quelqu'un a un avis contre ?

**Comment by johngf** [comment]
Oui surtout qu'avec la modif du titre en SXXEXX sur la grande majorité des sites 
La recherche ne trouve rien 
Il vaut mieux recherche le titre de la serie tampis si il y a bcp de résultat au moins il devrait y avoir ce qu'on cherche
C'est pas le cas actuellement j'en avais deja parlé dans modif titre

**Comment by TmpName** [comment]
Moi je les laisserais, ca m'aide pr me retrouver, mais pr la recherche faut faire sans la saison et les episodes, les moteur de recherche ne le gerent pas tous.

Apres meme si je suis sur la saison 4 episode 8, et que ca m'affiche toute les saisons/episode suis assez grand pr selectionner la bonne apres.

**Comment by LordVenom** [comment]
Perso je l'utilise pas si je peux pas chercher une saison ou un épisode je trouve ça pas logique de les afficher oui c'est beau mais c'est tout lol et quand tu mais en marque pas avoir juste les S01 ça me défrise carrément.

**Comment by TmpName** [comment]
Ben quand je veux reprendre une saison que j'ai arrette apres plus d'un an. Je passe par la, y a le resume, les titres, ect ... Ca me permet de me retrouver.
Aores faire la recherche avec "Saison X" c'est pas mal peut etre mais ca va virer des bon resultats. vaut mieux tout afficher, avec la nouvelle coloration c'est vite fait de retrouver soi-meme son saison et son episode.

Apres pr le bug des marque page et la recherche visuelle, moi je propose simplement d'empecher de mettre en marque page la recherche visuelle. Ca sert a quoi, c'est juste une base d'infos, tu met en favoris le site web ou tu as ton fichier, faut pas confondre avec exodus.

**Comment by LordVenom** [comment]
A ben moi je met en marque page la saison ou je suis et op même si les lien expire je suis ou j'en suis lol, j'ai fait mais motif dossier j'ai garder les saisons et épisode mais ça me fend le coeur.

**Comment by TmpName** [comment]
Ben meme si les liens expirent les marques page restent, c'est juste que tu ne peux plus acceder aux liens.
Moi je marque uniquement les saisons d'un site ( mais bon garder 20 series en favoris, y a un moment ou un autre ou tu fais un nettoyage)
