### ISSUE TITLE
recherche visuelle serie

### ISSUE THREAD

**Issue by korail** [Kodi-vStream/venom-xbmc-addons#1218]
Bonjour ! Merci pour les efforts, mon probleme est le suivant demuis quelque temps je n'ai plus acces a la recherche visuelle au niveau des serie aucun message d'erreur just une page vide, j'ai aussi remarqué que les series meme en recherche standard ne fonctionnaient pas correctement aillant epuiser mes reserve je me tourne vers vous merci d'avance ! Je suis sous kodi 17.1 vstream 5.1 windows 10

**Comment by TmpName** [comment]
On est dessus ^^
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1217

**Comment by korail** [comment]
Mon probleme date de plusieurs semaines, cela pourais etre lié ?

**Comment by TmpName** [comment]
Ben depuis la derniere MAJ d'apres ce que j'ai compris (qui se fait en debut de mois)

**Comment by LordVenom** [comment]
Version de vStream ?

**Comment by korail** [comment]
0.5.1

**Comment by LordVenom** [comment]
Petite vidage de cache via l'onglet outil de vStream sinon log stp.

**Comment by korail** [comment]
Je ne suis pas sur de la procedure a suivre pour effectuer le vidage du cache, le log aussi non plus "honte a moi"

**Comment by TmpName** [comment]
Dans les parametres de Vstream, onglet "outils/ A propos"
Tu trouveras pr les logs et pr le cache
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by johngf** [comment]
attention pour le cache j'ai remarqué que pour que le dossier ou il y a les fichier .fi le cache donc se régénère
(pas au meme endroit que kodi16 ) il faut redémarrer kodi

**Comment by korail** [comment]
Apres vidage du cache le probleme persiste je suis un peux larguer la, j'ai aussi procedé a une reinstallation complete de vstream et de kodi plusieurs versions heelp

**Comment by Kodigoal** [comment]
Comme dit plus haut , il faut le log kodi...
lancer kodi , vstream , faire tes manips qui posent problème , et aller ensuite dans les paramêtres de vStream uploader le log et nous donner le chiffre affiché comme expliqué sur le lien donné au dessus.
Ca va être dur de trouver , le log peut aider.

**Comment by korail** [comment]
Alors voici le log si ma demarche est bonne je m'en remet a vous s2mlSzzAP8

**Comment by LordVenom** [comment]
Active le mode debug de kodi et recommence la ça me parle pas asser.

**Comment by TmpName** [comment]
Yep, j'ai le meme resultat chez moi sans bug. Faudrait plus d''infos de debug.
