### ISSUE TITLE
Problème Playlist Framapad (Stop les Emails à Framapad Merci)

### ISSUE THREAD

**Issue by Ekynoxx** [Kodi-vStream/venom-xbmc-addons#1219]
Bonjour,

Depuis 2-3 jours je n'arrive plus à accéder à Framapad à partir de Kodi sur Android. J'ai me message "problème de lecture avec la playlist".

Avez-vous le même problème ? Si non comment y remédier et si oui d'où cela vient t'il ?

Merci !

Note: Edit du post trop lourd.

**Comment by Kodigoal** [comment]
Si c'est comme d'habitude , ca va revenir.
Même soucis erreur..

**Comment by lolema** [comment]
Que pensez-vous de l'idée, si elle ne s'avère pas trop compliquée, de réaliser un second framapad pour les fois ou le premier ne répond plus, car cela arrive souvent tout de même. Je n'ai aucune idée de la difficulté de la tache, étant un simple utilisateur de l'application qui met souvent la playlist framapad à jour. 
Cordialement

**Comment by LordVenom** [comment]
Il ont des problème de serveur ça finiras pas ce stabiliser, utiliser un autre framapad revient au même puisque même serveur.

**Comment by Ekynoxx** [comment]
En tout cas merci de vos réponses, juste a être patient alors.

**Comment by lolema** [comment]
Pourtant d'autre framapad sont accessibles.. Ou bien il y a des solutions similaires comme titanpad ? Je propose des idées pour éviter que des posts apparaissent à chaque problème serveur.

**Comment by lolema** [comment]
Au passage, où est écris le lien framapad dans le code de l'extension, car j'ai beau cherché je ne trouve nul part où il est mentionné, j'aimerais vraiment comprendre comment tout cela fonctionne malgré mes faibles connaissances cela m’intéresse. Merci d'avance

**Comment by Kodigoal** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/TV-FramaPad

**Comment by lolema** [comment]
Je voulais dire dans le code python, j'ai envoyé un mail à framapad, voilà ce qu'ils m'ont répondu:

Bonjour,
Parfois les pads restent mémorisés comme gelés et en erreur par le serveur et ça se débloque tout seul après un redémarrage du logiciel. Nous n'avons pas trouvé la cause de ce bug.
Actuellement le blocage vient de là, mais auparavant il y a eu également d'autres problèmes sur l'intégration de ce pad avec Kodi qui nous ont été signalés.
Les développeurs de Kodi font un usage détourné de Framapad. Si la playlist que contient le pad est incorrecte ça ne peut pas fonctionner.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki

Cordialement,
JosephK

**Comment by johngf** [comment]
@lolema le probleme viens de chez eux
mais quel idée de signaler a framapad qu'on utilise leur service ils vont finir par lesupprimer il faudra pas venir ce plaindre après

**Comment by lolema** [comment]
Si tu crois qu'ils ne sont pas au courant des dérives qu'il peut y avoir avec leurs services...

**Comment by LordVenom** [comment]
Ben c'est ce qu'il dise que le bug vient de chez eux mais qu'il ont pas trouver, mais qu'avant ça vener de l'ingretion de la playlist dans vstream et il donne même le wiki pour le faire comprendre au utilisateur plutot cool.Solution je ferez un autre pour la prochaine mise a jour mensuelle.

**Comment by FramaJosephK** [comment]
> Il ont des problème de serveur ça finiras pas ce stabiliser, utiliser un autre framapad revient au même puisque même serveur.

Juste pour préciser, que non ça ne revient pas au même. Nous avons en réalité 4 machines virtuelles actuellement pour gérer les pads : 

- une pour les pads privés
- une pour les pads mensuels et semestriels
- une pour les pads annuels
- et une pour le reste

Plus une instance contient de pads plus elle rencontre des problèmes de stabilité. Même chose si le pad en question contient énormément de modifications.

Bref, tout ça pour dire que le choix de l’instance a son importance. On compte communiquer un peut plus là dessus sur la page d’accueil (y a déjà des thermomètres comme indicateurs) parce que Framapad continue de grossir et ça devient difficile de le maintenir dans de bonnes conditions (qui permettent de dire que le libre c’est pas de la merde en gros :) ).

**Comment by lolema** [comment]
Merci @FramaJosephK pour ces précisions, donc le choix de la durée du pad est un critère qu'il va falloir prendre en compte pour une meilleure stabilité de celui ci.
@LordVenom Merci Super boulot j'ai hâte que la mise à jour apparaisse alors. Par simple curiosité je pourrais savoir où se situe la partie du code qui gère le framapad pour comprendre un peu comment cela est fait ?

**Comment by Kodigoal** [comment]
@lolema ah ok  , le code c'est ici ( freebox.py): url du pad via fonction showWeb
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/freebox.py

**Comment by LordVenom** [comment]
Oui oui c'est très simple à modifier mais avec les événement récent d'autre chose sont a prendre en considération, j’avoue qu'utiliser les ressources d'un sites libre gratuit sans pub et qui répond cordialement à des utilisateurs qui détourne leur projet me pose quelque soucis d’éthique.

@FramaJosephK , Le projet vStream vous pose un soucis préférer vous que l'ont change d’hébergeur ?

**Comment by FramaJosephK** [comment]
Techniquement ce n'est pas vraiment gênant que vous utilisiez Framapad. C'est surtout de devoir répondre au support qui l'est. 
Est-ce que l'aspect collaboratif en temps réel est vraiment indispensable pour vous ?
Est-ce que ce ne serait pas plus simple d'utiliser les pages statiques de Github/Gitlab ou même tout simplement la vue "raw" sur le fichier de playlist ? C'est moins user friendly pour apporter des correctifs mais ça reste possible et ça évite que n'importe qui casse tout.

**Comment by Kodigoal** [comment]
La lecture occasionnelle du chat va me manquer xD des passages collectors ^^

**Comment by LordVenom** [comment]
Malheureusement oui c'etait le point de depard de l'idée propose a tous a chaqu'un de contribuer sans inscription et sans connaissance particulier nous avons un autre system de playlist intégrer directement a Github celui rencontre moin de succès puisque moins souvent a jour. Mais j'ai pris note et nous allons changer d’hébergeur merci pour votre patience.

**Comment by lolema** [comment]
Dommage, c'était vraiment un bon compromis pour les personnes comme moi qui ne connaissent pas le python (je compte m'y mettre mais pour l'instant pas trop de temps) pour pouvoir mettre à jour une playlist iptv en direct, et la faire partager; ceci étant c'est une décision respectable et louable de votre part. Pour ce qui est du futur de l'iptv sur vstream, je veux bien contribuer s'il le faut, je peux fournir des listes iptv stables, avant que le framapad ne soit plus accessible j'avais fourni un bon nombre de chaines (aux alentours de 600 dont des doublons mais sur serveurs différents) et toutes semblaient fonctionner parfaitement, en effet lorsque le lien iptv est précédé d'un appel a la fonction f4mtester "plugin://plugin.video.f4mTester/?url=" et comporte le suffixe "&amp;streamtype=TSDOWNLOADER" le soucis de coupure au bout de 10 secondes disparait. Je suis conscient qu'une liste iptv n'est rarement stable plus d'une semaine mais je suis assez actif pour pouvoir la mettre à jour fréquemment.

**Comment by Kodigoal** [comment]
Ah , te faudrait pêtre une liste perso à part alors dans vStream, vu comment les gens effacaient les liens , la motivation en prend un coup...

**Comment by johngf** [comment]
il y a surement des autres hébergeur de ce type

**Comment by lolema** [comment]
Oui c'est vrai que c'est frustrant que tout le monde touche un peu à tout pour pas grand chose et parfois pour faire pire... Mais bon c'est le principe de l'aspect communautaire, il a des défauts comme des qualités. En tout cas si je peux aider ce serais avec plaisir.

**Comment by ldidry** [comment]
Disclaimer : je suis aussi de Framasoft.

Vous pourriez, pour lire le pad même s'il est planté, utiliser l'adresse de l'export texte : https://annuel.framapad.org/p/vstream/export/txt (bon, actuellement, ça renvoie un fichier vide car quelqu'un a tout effacé (peut-être d'ailleurs ce qui a causé le plantage), mais la version 27726 contient des trucs : https://annuel.framapad.org/p/vstream/27726/export/txt).

**Comment by LordVenom** [comment]
@ldidry Merci pour l'info.

@lolema Si je te fait un fichier github tu arriverais a le maintenir a jour sans trop te prendre de temp ? y a que toi qui pourais le modifier au moin personne ne viendrais tout effacer.

**Comment by johngf** [comment]
Sinon pirate pad net
http://www.similarsitesearch.com/alternatives-to/titanpad.com

**Comment by lolema** [comment]
@LordVenom Oui je pourrais le mettre à jour fréquemment, 1 fois par semaine minimum. Par contre j'ai des listes IPTV avec énormément de chaines dont la plupart sont en double ou triple sur la liste (Low, SD, HD) donc cela fait en tout aux alentours de 600 chaines, je n'aurais certainement pas le temps de les catégoriser comme certains le font (Sport, divertissement...). Ensuite j'aimerais savoir s'il serait possible de mettre la liste en syntaxe XML plutôt que M3U, c'est sous cette forme que je télécharge mes listes, cela ne me dérange pas de les éditer en M3U mais disons que cela me ferais gagner du temps donc je me permet de le demander.

**Comment by LordVenom** [comment]
Ok edit ce fichier 

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/repo/resources/tv.xml

Je verais par la suite comment l'implanter dans vstream tu a un nom préférer pour ta liste ?

La manip est simple tu vas sur le lien ci dessus et tu clique sur le stylo (edit) tu copie colle ton xml et tu commit le changement il seras afficher dans les pull request en attente de validation ont le valid et op c'est dispo.

**Comment by lolema** [comment]
C'est bon j'ai envoyé la liste sur le lien, je n'ai pas de nom favoris pour la liste. Mais du coup comment ça va se passer pour mettre à jour la liste ?

**Comment by LordVenom** [comment]
Dsl je voie rien

**Comment by LordVenom** [comment]
Ok c'est fait pour le tris y a un tris ? tu les mets par date ou moi je doit les mètres par ordre alphabétique?

**Comment by Kodigoal** [comment]
plus de 1400 entrées en listant ....j'ai abandonné à 100 lol trop lourd non ?

**Comment by LordVenom** [comment]
ça vas vite chez moi mais oui si tu peux diminuer un peux les entrer :)

**Comment by lolema** [comment]
Oui c'est vrai que j'en ai mis un peu beaucoup, je diminuerais la prochaine fois mais je m'étais dit qu'avec la fonction recherche de Kodi cela aurait permis aux utilisateurs d'affiner en fonction du programme qu'il souhaite regarder. En ce qui concerne le tri, je t'ai mit la playlist tel que je l'ai eu, j'ai juste rajouter l'appel a f4mtester et le suffixe. Maintenant il faut savoir que je compte pas mettre à jour la playlist mais plutot la remplacer intégralement chaque semaine par une autre, cela me prendra certainement moins de temps. Une liste de combien de chaînes vous conviendrez pour la prochaine fois ? Je pense qu'au minimum 2 serveurs différents est nécessaire pour que l'utilisateur est au moins une solution de secours. Mais c'est franchement le minimum, c'est pour ça que j'avais fait une si grande liste, je ne comprend pas vraiment le désavantage d'avoir des listes conséquente (bon là j'avoue que c'était certainement excessif), si vous pouvez m'expliquer.

**Comment by Kodigoal** [comment]
Ben c'est comme quand tu listes un site ou ya des Films par exemple , je crois kepliz liste 59 films en nouveautés , je trouve ca déja long parfois ^^
Imagine là via ta liste , ta popup qui s'ouvre  et t'as le compteur qui doit arriver à 1400 avant que les liens s'affichent lol .. 
De mon côté via android , ca doit prendre 3-4 min facile sais pas trop , je stoppe à 100 lol  je mettrais le chrono ..
De plus parfois en listant les sources , je sais pas d'ou ca vient  mais ca recharge la page de temps à autre .. donc là j'imagine te taper 1400 au compteur , tester des liens et il te ressort la popup 1400 à lister .. T'abandonne.
ps: Après c'est pêtre juste lent sur mes kodi android lol

**Comment by razorex** [comment]
@ j'ouvre le fichier en mode édition et quand j'ai fais mes modifs je fais proposer les modifs et encore apres un pull request

**Comment by johngf** [comment]
Comment ça se passe si comme dans le xml l'url commence par plugin plugin f4m au lieu d'une url simple
2 player demarre ?

**Comment by LordVenom** [comment]
Ok je vais faire un truc alphabetique bien trouver @Kodigoal.

Chez moi Kodi 17 si j'ai pas l'addon : il me dit que j'ai pas et me demande de l'installer 
Si j'ai l'addon il lance l'addon avec l'url bref parfait.

**Comment by lolema** [comment]
Oui pas mal trouver pour le système de première lettre. Pour simplifier la tâche dans la prochaine liste je supprimerait les "FR:" present sur certains serveurs. Cela permettra d'avoir la première lettre de la chaine désirée.

**Comment by LordVenom** [comment]
Fait c'etait plus chiant que l'imaginer mais bon.

**Comment by LordVenom** [comment]
@lolema c'est bon pour toi ? ont roule comme ça ?

**Comment by Kodigoal** [comment]
Encore un petit sorted() aussi après le filter si  on passe par  0-9A-Z et le total basé sur len(string) au lieu du len(aResult) ?
https://pastebin.com/mTnq3iuT
Ca classe mieux et on a le vrai nombre de liens boite de dialogue.
q

**Comment by LordVenom** [comment]
Bien vue.

**Comment by lolema** [comment]
C'est tout bon pour moi, où puis-je éditer le fichier pour mettre à jour la liste ?

**Comment by LordVenom** [comment]
Fait comme dit par @razorex  tu edit le fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/repo/resources/tv.xml

**Comment by LordVenom** [comment]
Il faut editer le lien si dessous. et faire comme la dit @razorex  pour proposer un pull request.

**Comment by vic1997** [comment]
Salut, il y a bien une grande liste d'IPTV cependant il n'y en a vraiment aucune qui marche, c'est normale ?

**Comment by Arias800** [comment]
Toute les IPTV sont temporaire (sauf celle officiel) donc oui c'est normale il faut attendre que quelqu’un les change

**Comment by vic1997** [comment]
Nan mais y en a vraiment aucune, même ceux qui devrait marcher (genre ça trouve, puis starting local proxy et puis rien, alors que normalement quand ça écrit ça c'est que c'est bon). Après c'est bizzare qu'il y en a vraiment aucune.

**Comment by lolema** [comment]
Je viens d'envoyer de nouvelles chaînes, cette semaine j'ai pas eu trop le temps avec les exams mais je vais essayer d'être plus actif

**Comment by vic1997** [comment]
Ha ok merci ! C'était pas pour te presser, c'était juste pour savoir si c'était moi ou pas mais ne t'inquiète pas c'est pas grave si ça marche pas de suite. Je voulais également savoir si je pouvais en mettre de façon plus organisé (juste les chaines principales) car j'ai une liste un peu plus organisé que je pourrais mettre à jour tout les jours si il le faut. (à voir avec @LordVenom ) Car là, bien qu'on a beaucoup de chaine et que l'on a beaucoup le choix, il y en a vraiment trop ! Bref, merci d'avoir mis ça à jour !

**Comment by LordVenom** [comment]
@vic1997  tu veut un autre acces xml ? ça vas faire doublon la y a deja 2 xml de tv

**Comment by vic1997** [comment]
@LordVenom ça serait bien, mais oui justement le problème du doublon est là, c'est pour ça j'ai pensé à faire plusieurs "trie", genre une section avec toutes les chaines de A à Z (déjà mis en place), une avec Beta (je sais pas à quoi ça sert mais c'est déjà en place) et une avec les chaines principales (définir un nom) où il n'y aurait que les chaines principales (TNT, quelques CANAL+, OCS, et les chaines premium, donc environ 50 chaines). Je pourrais m'occuper de mettre à jour ces chaines.
