### ISSUE TITLE
probleme accés librairie avec la beta

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#1220]
quand on ajoute un lien a la librairie on n'y a pas accés par la suite ça crée un dossier(ça devrait pas je pense)
on doit cliqué ensuite faire retour arrière pour avoir le strm

edit: et les fichier strm ne fonctione pas avec certains hebergeur now video google video (surement d'autres)
ValueError: dictionary update sequence element #3 has length 3; 2 is required

**Comment by TmpName** [comment]
Houla, alors la gros dossier ^^.
Normallement ca cree un dossier uniquement pr les series.

Pour le reste je vais tester.

**Comment by TmpName** [comment]
Bon j'ai fais quelques modif, mais en fait on ne devrait pas acceder a la librairie via Vstream mais via kodi, et la ca marchait.
En fait la partie dans kodi etait juste pr la gestion, pas la lecture.

**Comment by johngf** [comment]
Comment tu y accede via kodi?

**Comment by johngf** [comment]
Je pense quand il y a un & dans l'url ça foire a cause de split dans inputparametrehandler

**Comment by TmpName** [comment]
C'est le principe, sans integration a kodi ca sert a rien, c'est le but de la librairie.
En fait dans les options Vstream ca te donne un repertoire, et c'est celui que tu rentres dans la config des librairie de kodi.
http://www.geekmag.fr/kodi-ajouter-une-source-video-source-tv-films/

Pr le bug de lecture y avait site qui n'avait pas de valeur:  b=8&site&a=1, mais normalement now ca doit marcher. Par contre j'en ai pas un qui marche par le lecteur de Vstream, je pensais que c'etait normal, y en a qui marchent ? Si y en a qui marchent c'est que c'est possible, mais pour moi c'etait normal.

**Comment by johngf** [comment]
Oui you watch fonctionne all vid aussi

**Comment by johngf** [comment]
Le soucis de librairie n'est pas sur kodi 16 avec la master bizarre

**Comment by TmpName** [comment]
ha mince, me faut refaire des test alors pr passer avec le lecteur, c'est mieux. Et oui je pense aussi que ca a cause de caracteres speciaux.

**Comment by TmpName** [comment]
Bon alors je sais pas comment tu fais, mais moi impossible de lire un strm via le player.
J'ai bidouille le fichier de la librairie, remplace false par true a la ligne 198 et ca passe par le lecteur.
Chez moi ca charge meme pas et ca affiche juste les ".." pr revenir en arriere.

**Comment by johngf** [comment]
pour moi c'est un probleme avec kodi17 seulement

**Comment by TmpName** [comment]
Ha ok, ca me rassure car je me souvenais pas que ca deconnait autant. Merci la V17.
Avec Container.Update ca fonctionnait comme un simple explorateur de fichier.

La je t'avous, suis deja en train de batailler pr le bug de net_u je vais pas chercher a savoir pkoi les strm ne fonctionent plus, ca marche sans passer par Vstream, je vais faire avec ca pr le moment.

Au pire fais pareil pr les dash video, sinon avec un try/except on peut afficher un popup demandant d'activer inputstream, plutot que de forcer l'activation dans vstream.

**Comment by johngf** [comment]
du coup il faudrait tout refaire avec des addDir et addHost pour que ça fonctionne via vstream
et l'option supprimé fonctionne

**Comment by johngf** [comment]
inputstream est intégré a kodi et n'ai utilisé que si besoin comparé a tous les addons et repo qu'install les users ça ne va pas faire de difference pis les popup perso ça me saoule un peux d'autant plus que faudra verifier a chaque video si il est actif ou pas et comment le savoir .... perso j'en sais rien

**Comment by TmpName** [comment]
Lol, le popup tu ne l'as qu'une fois (si tu actives l'extension), j'ai peur que si on force son activation, ca demande une dependance du coup (je sais pas du tout comment ca marche).
Pr verifier si il est actif ou pas, on le fait deja pr l extension extendedinfo.

Sinon moi j 'etais partis pr un truc plus simple.
Soit on met un code pr utiliser le player de base directement de le fichier hoster, vu que seul now video en a besoin pr le moment. (Le code que j'utilise pour les bande annonces n'utilise pas le lecteur de Vstream)
Soit bidouiller le lecteur de Vstream pour que si il recoit un fichier avec l extension "strm" il gere ca de facon differente.
La premiere etant mieux car on touche pas au coeur.

**Comment by johngf** [comment]
pour l'instant je ne suis plus sur now video je regle la librairie si je fait a ma facon le strm ne sert plus rien ça serait pareil avec un txt mais au moin ça passe plus par kodi 
apres je reprendrait now video

**Comment by TmpName** [comment]
Mais de base, le fichier tel qu'il est sur le github fonctionne  (en laissant false) ?
Moi j'ai teste directement dans kodi et via la partie librairie, et ca a marche (flash comme hebergeur).

**Comment by johngf** [comment]
oui mais en faite moi je fait un truc qui ne depend pas de kodi

**Comment by TmpName** [comment]
Ha ? moi c'est ok sur V17, me faut revoir pkoi.
Mais du coup tes fichiers strm ne marche plus avec les libs, du coup, y a plus l'integration dans les skins, ni la bibliothequer, ect ...

**Comment by johngf** [comment]
Integration elle est utile  ? Jamais vu de thumb ça récup que l'url et le hoster a moins qu'il faut activé les meta ? 
Et pour la fonction supprimer ?

**Comment by TmpName** [comment]
En fait c'est comme tes fichier locaux (ta mediatheque)
Ca va recuperer les infos/poster/Vrai titre (pas celui du fichier), ect ... meme si les metas sont desactivés, ce n'est pas Vstream qui gere ca, c'est kodi, et ca les rajoutes dans ta mediatheque, aux endroit que tu as configure.
Tout les reglages se font dans kodi, Vstream ne fait que generer des fichiers.

Je viens de tester V17 pr flashX et allvid, fct ok.

Suppression ok, mais faudrait virer le repertoire si plus d'episode dedans.

**Comment by johngf** [comment]
bon bein je lache l'affaire facon j'utilise pas la mediatheque ni les metas de vstream ou de kodi
Je me servirai de mon fichier a la place parceque avec les marque pages t'es pas a l'abri de tous supprimer a fause d'un bug de la db

**Comment by TmpName** [comment]
Lol, ou d'un clic au mauvais endroit ^^.

**Comment by johngf** [comment]
Apres sa sert de pense betes si le lien marche pas recherche similaire et c'est bon

**Comment by johngf** [comment]
bon j'ai test ta derniere modif le soucis je n'arrive pas a aller jusqu'au strm

**Comment by TmpName** [comment]
Suis dessus la , mais j'ai pas les memes prb que toi.
Il mnaque ou le / ?

**Comment by johngf** [comment]
Apres films sans / ou \ c'est pas consideré comme un dossier

**Comment by TmpName** [comment]
Put1 j'ai pas ce prb moi ! Ni celui avec showcontent !
Tu as quoi comme repertoire dans la config ? 
J'ai fait une modif, a cause des caracteres chelous dans les urls, mais ca marche sans prb pr les films.

Je dois pas avoir les memes fichiers que sur la beta (j'ai pas mal de code en plus partout pr trouver quelque chose pr netu) , me faut tout installer pr tester.

**Comment by johngf** [comment]
Films series dans films des strm si je clique ça fonctionne pas si je rajoute le \\ ça play mais dans le log
Je voie 2 showcontent 1 avant readfile un aprés et l'erreur directory normal addfolder c'est pareil que par framapad quand tu play il y a toujour l'erreur dans le log tu play un dossier non playable normalement

**Comment by TmpName** [comment]
Donne moi ta manip stp.
Sinon je viens de me souvenir, mais pr la bibliotheque y a une structure a respecter, y a un tuto sur le wiki de kodi , repertoire ou pas repertoire, sysntaxe pr les saisons et episode ect ...

**Comment by johngf** [comment]
ex d'url dans le log 
AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\Filmsau bout du tunnel.strm
alors que ça devrait etre
AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\Films> ici \\  <   au bout du tunnel.strm
sinon le chemin n'est pas trouvé

**Comment by johngf** [comment]
bon en faite c'etait tout bete manquait un /
xbmc.executebuiltin("Container.Update(" + sFolder + ")")
apres c'est ok
xbmc.executebuiltin("Container.Update(" + sFolder +'/'+ ")")

**Comment by TmpName** [comment]
Mais on passe pas par "xbmc.executebuiltin("Container.Update" dans la version en ligne ?

Sinon tu passes par Vstream (et son menu librairie) pr lancer la video ou par kodi (et sa bibliotheque) ?

**Comment by johngf** [comment]
par vstream j'ai reteste l'ancien showcontent ça a fonctionné 5 min

**Comment by LordVenom** [comment]
Je pense pas que vstream le liser avant c'etait juste une navigation non ?

**Comment by johngf** [comment]
apparement c'est un bug de krypton

**Comment by TmpName** [comment]
Franchement c'est juste mon avis, mais
- Personne de dispo pr se pencher a fond dessus.
- Pas envie de chercher pkoi ca marche chez X et pas Y
- Je vois pas a quoi ca peut servir

Il y a bien eu de la demande, mais suis pas sur que ca serve vraiment ? On fait un sondage ^^ ?

Sinon effectivement faire un dossier pr les films, c'est bien aussi https://wiki.mpdb.tv/go/Organisation_de_vos_fichiers

**Comment by LordVenom** [comment]
J'ai déjà plusieurs tentative de sondage si tu veut enlever personne n'est d'accord lollll

**Comment by johngf** [comment]
par contre supprimé ne fonctionne pas comme avant a moins d'activer l'option dans kodi
autoriser a renommer et supprimer des fichiers

**Comment by TmpName** [comment]
Y a pas une option en clic droit (menu contextuel) ?

**Comment by johngf** [comment]
oui si tu active l'option dans kodi

**Comment by TmpName** [comment]
Ha ok, tu as remit en utilisant xbmc.executebuiltin("Container.Update, du coup j'ai plus la meme version.

**Comment by johngf** [comment]
ça fonctionne sur 16 et 17 c'est le fait que vstream utilise addir pour films et series qui cause le bug sur krypton
