### ISSUE TITLE
logo mangacity

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1221]
Le nouveau logo de mangacity_org 2 versions transparent et avec fond.
![ianime](https://cloud.githubusercontent.com/assets/26149640/25304291/c4e901a4-2764-11e7-8524-4a591eb7d6e1.png)
![mangacity_org](https://cloud.githubusercontent.com/assets/26149640/25304292/d20bf38c-2764-11e7-9f5e-f3c66fbce58b.png)

Note : fait

**Comment by razorex** [comment]
????? @LordVenom tu ne veux pas du nouveau logo de I anime??? et s'il est possible de modifier le nom dans le fichier "interdit" setting (lol)

**Comment by LordVenom** [comment]
Je savais que tu serais impatient lol la modif ne prend effet que a la fin du mois les images sont la c'est pas perdu j'ai rien a modifier pour le moment je repond juste au message mais ça viendras et je prendrais l'image dans la fouler.

**Comment by razorex** [comment]
lol. bien vu.

**Comment by razorex** [comment]
le transparent rend mieux.... lol

**Comment by razorex** [comment]
D'autres logos pour "series_en_streaming_tv"
![series_en_streaming_tv](https://cloud.githubusercontent.com/assets/26149640/25489573/83781598-2b6a-11e7-9a47-0be2117f669e.png)
![series_en_streaming_tv](https://cloud.githubusercontent.com/assets/26149640/25489584/8b087848-2b6a-11e7-86fd-589d15b8ca4e.png)

**Comment by razorex** [comment]
Ceux de "serie_streaminghd"
![serie_streaminghd](https://cloud.githubusercontent.com/assets/26149640/25490382/f12e6cb6-2b6c-11e7-9022-66d32012b2db.png)
![serie_streaminghd](https://cloud.githubusercontent.com/assets/26149640/25490385/f8de1b82-2b6c-11e7-9b4b-cca48978d423.png)

**Comment by razorex** [comment]
Ceux de "tv_streaming_ch"
![tv_streaming_ch](https://cloud.githubusercontent.com/assets/26149640/25490914/a7150656-2b6e-11e7-9892-0a30f7b24ffb.png)
![tv-streaming-series xyz](https://cloud.githubusercontent.com/assets/26149640/25490931/b1ba05f2-2b6e-11e7-87a7-189d266ea436.png)
