### ISSUE TITLE
Soucis de MAJ 

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1239]
Salut 
J'ai un soucis, mon vstream a affiché une MAJ de disponnible, quand je clique dessus rien ne s'opère. Elle ne se lance pas. 
Bisare tout ça ...

**Comment by Kodigoal** [comment]
Salut, 
via ton kodi sur ton iphone?
Faudrait refaire la manip de cliquer dessus quand ca arrive  , et uploader le log Kodi  ensuite via les options dans vStream , onglet Outils et nous  donner le chiffre affiché sur la popup après l'upload du log.
T'as la dernière version de vStream?

**Comment by kikikodi** [comment]
Salut 
sur Android, dernière version installée la 0.5.1 
Jusque là pas de problème a la mise a jour en règle générale le téléchargement de lancent, mais là hier rien en cliquant sur mise à jour dans vstream
Je vais voir pour le code erreur et reviens vers vous

**Comment by kikikodi** [comment]
La je suis dessus je ne comprends pas comment reccuperer le log, je n'ai ps de popup qui s'ouvre, j'ai par contre vidé tous les caches, et aussi "clear thumbnails"(à quoi ça correspond?) rien y fait je suis bloqué.

**Comment by kikikodi** [comment]
Et dans option je vois bien mise a jour auto le 2017/04/25 09:21:50.036833
En dessous il y a upload kodi.log mais rien ne viens si je clique dessus.

**Comment by LordVenom** [comment]
Mais ont n'a pas deja parler de ça ? le soucis vient pas de vStream.

**Comment by kikikodi** [comment]
@lordvenom 
Non je ne crois pas en tout cas pas avec moi, je ne parle pas de la mise a jour de la version de vstream, mais celle qui se lance plusieurs fois dans le mois , qui necesite qu'on clique sur "mise a jour" suite a quoi une pop up s'ouvre et les 150 sources environs de chargent. Mais la j'ai bien mise a jour de dispo en bas à droite quand on ouvre vstream mais en cliquent dessus rien ne se passe . Pourquoi tu dis que cela ne vient pas de vstream ? Tu penses que ça viens d'où ? 
Merci

**Comment by LordVenom** [comment]
Ben vue que je vais les mises a jour aussi et que ça fonctionne chez moi, fait une mise a jour et donne ton log.

**Comment by razorex** [comment]
même souci chez moi mais sous windows (on n'en a déjà parlé).. donc pour les màj je récupère les fichiers sur le github.

**Comment by LordVenom** [comment]
Android et Windows même soucis y a que sous linux que ça fonctionne ? lol
donner nous des logs en activer le mode debug de kodi.

**Comment by TmpName** [comment]
Nope, window chez moi, et pas de soucis.

**Comment by johngf** [comment]
Deja dit mais comment accedez vous a vstream ? 
Via un raccourcis ou un favoris
Ou la methode normale démarrage kodi >extensions videos >vstream

**Comment by kikikodi** [comment]
Salut
Moi perso depuis extensions et extension video
Et ça m'a fait l'erreur évoquée Le ven. 28 avr. 2017 à 17:31, johngf <

**Comment by razorex** [comment]
moi extension  video et vStream @johngf. Trois pc y a un souci quand même apres ces surement du coté de windows pour moi. installation faite en mode admin. ma tvbox et mon smartphone non pas de souci. Après je pense que peu d'utilisateur remonte les problèmes qu'ils rencontre avec vStream.

**Comment by razorex** [comment]
Qu'elle version de windows @TmpName  moi c'est sous seven et 8

**Comment by TmpName** [comment]
Moi j'avais le prb sur les version < V17, il me fallait vider le cache de Kodi (via les optiosn de Vstream) pour avoir les MAJ

La je suis sur Win 7 Kodi V 17.

**Comment by razorex** [comment]
Justement sur windows impossible de faire un clean cache et clear. fi

**Comment by johngf** [comment]
Windows 8 ?

**Comment by razorex** [comment]
non 10 dsl. mais windws 8 et 8.1 existe ......

**Comment by johngf** [comment]
Tu as quoi comme msg dans le log rien ?

**Comment by razorex** [comment]
j'ai tenté plusieurs fois la réinstal mais tjrs le même souci

**Comment by johngf** [comment]
Tu install via le store ou l'exe de kodi

**Comment by razorex** [comment]
l'exe de kodi

**Comment by johngf** [comment]
ok je passe vu que t'es pas décidé a regarder ton log ....
au cas ou tu ne sais pas ou il est https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by LordVenom** [comment]
voir y a deux jour 

> Android et Windows même soucis y a que sous linux que ça fonctionne ? lol
> donner nous des logs en activer le mode debug de kodi.

**Comment by TmpName** [comment]
Pour le clear cache.
Fichier runscript.py
Rajoute la ligne 72

```
            if dialog.yesno('vStream', 'Êtes-vous sûr ?','','','Non', 'Oui'):
                cConfig().log(xbmc.translatePath('special://temp/'))
                self.ClearDir(xbmc.translatePath('special://temp/'),True)
xbmc.executebuiltin("XBMC.Notification(Clear XBMC Cache,Successful,5000,"")")
```

Et regarde si le chemin correspond a ton disque dur.

**Comment by razorex** [comment]
dsl j'ai fais un upload mais il va il me semble avoir lu qu'il allais sur un site et que je donnais le numero mais rien

**Comment by razorex** [comment]
j'ai bien activer le mode debugg sur kodi. dsl de prendre du temp pour répondre.

**Comment by LordVenom** [comment]
Hé ben vas le cherche toi même. et colle le sur https://pastebin.com/ puis partage l'url.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by razorex** [comment]
ici [https://pastebin.com/VDXL4smg](url)

**Comment by LordVenom** [comment]
Haaaaaaaaaaaaaaaaaaaaaaaa Users\Hervé\

**Comment by razorex** [comment]
retester le .fi. ............................. arg j'aurais du le virer  (cnil).........................

**Comment by razorex** [comment]
non repo vstream. Même si srp est présent c'est vrai.

**Comment by razorex** [comment]
fais @TmpName

**Comment by TmpName** [comment]
Je crois que c'est plus la peine @LordVenom a du trouver, jamais d'accent en informatique ^^ c'est pour ca que tu en as tant a corriger dans le code de Vstream, j'en mets jamais.

Mais y a plus que nous qui avont des prbs sur tes log
` IOError: (2, 'No such file or directory', 'C:\\Users\\Herv\xc3\xa9\\AppData\\Roaming\\Kodi\\addons\\repository.xunitytalk\\addon.xml')`

T'inquiete pas avec ta vie privée, on parlera pas des 86 films de cul qui apparaissent dans les logs et ton emploi du temps de la semaine derniere, d'aileurs j'ai pas compris ce que tu faisais mardi a 17h23 ?

**Comment by LordVenom** [comment]
lolllll de notre coter on peux pas corriger? pour les autres addon ben il te faudras changer de nom :)

**Comment by razorex** [comment]
mdr @TmpName

**Comment by razorex** [comment]
et pour mon anonymat 41 personnes on regarder mon log, vais avoir des soucis avec les autorités... oui beaucoup de bug sur d'autres appli c'est bien pour çà que j'ai toujours dis que c'étais pas vStream le pb.

**Comment by LordVenom** [comment]
Y a rien dans ton log qui peux servir contre toi le faite que tu t'appelle hervé n'est pas grave lol enchanter moi c'est Alain.

**Comment by razorex** [comment]
tkt je sais je blague comme vous je pense salut Alain.

**Comment by LordVenom** [comment]
Bref ok ont vas tester des truc prés 

config.py ligne 87 

```
            self.__oCache = xbmc.translatePath(self.__oSettings.getAddonInfo("profile").decode('utf-8'))
            print self.__oCache
```

Pous toujour en mode debug tu vas dans vstream et tu vas voir ton log et tu me colle l'adresse retourner par le print.

**Comment by razorex** [comment]
ok mis mis le print. mais dans le log je vois pas ou je trouve l'adresse

**Comment by LordVenom** [comment]
Ha oui compliquer ajouter un 

Print "laaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" au dessus comme ça c'est l'url juste en dessous lol

**Comment by LordVenom** [comment]
Hum j'ai doute quand meme plus simple pour toi de modifier le nom hervé par herve et ça debugueras tout les autre addon.

**Comment by razorex** [comment]
mon lien pastebin https://pastebin.com/qYbaH6hn

**Comment by razorex** [comment]
ok je virerais le "é" mais il y en a surement plein d'autres qui ont mis des accents dans leurs nom d'utilisateur. pas sur en plus que je ne doivent pas tous réinstaller pour modifier en "dur"

**Comment by LordVenom** [comment]
Non non le changement de nom d'utilisateur et asser simple dans mes souvenir et pas temp de gens que ça en mette c'est plutôt l'inverse.

**Comment by razorex** [comment]
oui celui affiché pas le nom du dossier users

**Comment by Kodigoal** [comment]
/kîkîkodî/ ? :-)

**Comment by LordVenom** [comment]
self.__oPath = self.__oSettings.getAddonInfo("path") mais celui la veut pas je regarde tranquillement plus tard.

**Comment by razorex** [comment]
????????

**Comment by LordVenom** [comment]
Ha merde je peux pas faire de test linux n'autorise pas les nom d'user avec accent

**Comment by razorex** [comment]
mdr. ok je réinstallerais un de mes pc avec un pseudo sans accent.

**Comment by Kodigoal** [comment]
Par contre pour kikikodi sous android , pêtre si multicompte User (un avec accent) et encore ...
Bref on attend le log debug.
Pas de soucis sur mes kodi android de mon côté.

**Comment by TmpName** [comment]
Haaaa, attendez, il vas pas etre le seul a avoir ce prb, c'est mieux qu'il le garde et qu'on corrige.

**Comment by TmpName** [comment]
Edit:
je viens de tetser @LordVenom a raison, pour que ca marche
```
        import os
        file = 'c://éé.txt'
        os.remove(file.decode("utf8"))
```

Essayes avec la nouvelle version de runscript.py

**Comment by razorex** [comment]
ok je vais tester.

**Comment by TmpName** [comment]
Bon alors y a de grosse modifs en route pr gerer les accents, le plus simple c'est d'installer carrement la beta chez toi.

**Comment by LordVenom** [comment]
@TmpName  je doit poster la modif de config ou tu regarde ?

**Comment by TmpName** [comment]
Ha je sais pas, j'ai fais aussi des modif (sur 3 fichiers de memoire) que j'ai mis en ligne pr que les gens puissent tester.
Chez moi ca tourne, mais pas sur d'avoir tout corige, compares les fichiers.

**Comment by LordVenom** [comment]
Ok c'est mis parfait dit voir le 

self.__oPath = self.__oSettings.getAddonInfo("path")

os.path.join(self.__oPath,'resources', 'art','icon.png')

Return un chemin correct?

**Comment by TmpName** [comment]
Oui et non.
Jette un eouil dan guielement.
`return os.path.join(unicode(self.__sRootArt, 'utf-8'), self.__sIcon)`

Si le lien est deja en unicode du coup ca plante.

Le code est pas homogene Parfois il y a la convertion d'origine, parfois non, j'ai prefere eviter les bugs, jouer la securite et corriger les manquants.

**Comment by TmpName** [comment]
En fait c'est meme plus logique, faudrait laisser tout les path en normal et convertir juste dans les os.path. ... ?

**Comment by TmpName** [comment]
C'est bon @razorex tu peux installer la beta complete, tu devrais voir pas mal de changement de ton cote, notament dans les outils present dans le dialogue de configuration.

**Comment by razorex** [comment]
ok @TmpName je vais tester.

**Comment by kikikodi** [comment]
Mrs je vois que sans le faire exprès j'ai lancé un gros débat 😉

**Comment by razorex** [comment]
comment il ce la joue @kikikodi ....lol merci de remonté les pb. bon tout les clean ont fonctionnés tester aussi l'envoi du log et sa a fonctionné (s2EQghwTmw).

**Comment by LordVenom** [comment]
@razorex  remonte nous ton log toujours debug activer pour voir ou ça merdouille encore.

**Comment by kikikodi** [comment]
Non je plaisante avec vous 😂
Perso incapable défaire ce que vous faites ! Bravo les gars !

**Comment by LordVenom** [comment]
@kikikodi tu as tester la version bêta pour voir si ça resoud ton soucis aussi ?

**Comment by kikikodi** [comment]
Dites moi rié a voir mais je viens de voir les deux nouveaux onglets bêta
pour la TV, ceux sont des sources iptv ? Aussi le problème est le
chargement ultra long cule nombre important. Je pense que vous allez y
remédier puisque en bêta , non?
Le lun. 1 mai 2017 à 00:41, MICHAEL ben ghozi <ecorendezvous@gmail.com> a
écrit :

**Comment by kikikodi** [comment]
Non pas testé encore, j'ai deux box, les deux sous les mêmes compte, une a
posé peobleme l'autre non...
J'ai pas essayé je vais remonter le fil de la discution, je vois que vous
n'avez pas chômé, j'ai recu des notifications en pagaille , sur la boite
mail lol
Le lun. 1 mai 2017 à 00:46, MICHAEL ben ghozi <ecorendezvous@gmail.com> a
écrit :

**Comment by kikikodi** [comment]
Merde pouvez vous enlever mon mail et mon nom des commentaire, j'ai repindu directement redouls mon adresse mail je ne pensais pas que ça allais divulguer les infos Persos merci

**Comment by LordVenom** [comment]
Fait, oui ont a fait un classement par lettre mais une foix la liste charger la recharge vas vite.

**Comment by kikikodi** [comment]
Merci LordVenom dn'être intervenu aussi rapidement , ç etait lutin génant 😉

**Comment by kikikodi** [comment]
"Plutôt "

**Comment by razorex** [comment]
le code pour mon log s21seRihx0 . Inclus (normalement) un bug pour la sélection des sources

**Comment by TmpName** [comment]
C'est bizarre ca a coupe la fin.
C'est pas le code qui met en ligne le log qui deconnerait ? Une histoire de taille ?

Sinon c'est ou la selection des sources, dans le menu de config ?

**Comment by razorex** [comment]
dans le menu recherche

**Comment by TmpName** [comment]
Rien a faire j'arrive pas a voir de code avec des possible prb d'unicode.
Tu pourrais pas chercher les 4/5 lignes dans ton log ou se trouve le bug, et les coller ici, stp ?

**Comment by razorex** [comment]
@TmpName 
12:44:06 T:6920  DEBUG: CPythonInvoker(4, special://home/addons/plugin.video.vstream/resources/lib/runscript.py): entering source directory C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib
12:44:06 T:6920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named resources.lib.handler.pluginHandler
                                            Traceback (most recent call last):
                                              File "C:\Users\Herv�\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\runscript.py", line 260, in <module>
                                                cClear()
                                              File "C:\Users\Herv�\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\runscript.py", line 21, in __init__
                                                self.main(sys.argv[1])
                                              File "C:\Users\Herv�\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\runscript.py", line 118, in main
                                                from resources.lib.handler.pluginHandler import cPluginHandler
                                            ImportError: No module named resources.lib.handler.pluginHandler
                                            -->End of Python script error report<--
12:44:06 T:6600   DEBUG: ------ Window Init (DialogKaiToast.xml) ------

**Comment by LordVenom** [comment]
@TmpName  pk tu as virer ?
self.__oCache = xbmc.translatePath(self.__oSettings.getAddonInfo("profile")).decode("utf-8")

**Comment by TmpName** [comment]
Pr plusieurs raisons
1 - la fonction 
def getSettingCache(self):
        return self.__oCache

doit retourner non unicode car par la suite dans le code on fait
watched_db = os.path.join(cConfig().getSettingCache(), "watched.db" ).decode("utf-8")

2 - ca sert a rien de la mettre en unicode car par la suite on y "rajoute des bouts"
self.__sFileFav = os.path.join(self.__oCache,'favourite.db')
et il faut reconvertir encore la nouvelle chaine, du coup ca sert plus a rien la premiere fois

En fait le truc c'est de tout gerer en utf-8 (vu que kodi ne gere que ca), et juste a la fin avant d'utiliser le fonction, convertir en unicode, jamais avant car si 2 convertion a la suite > bug.

**Comment by TmpName** [comment]
Lol, c'est justement le bug a @razorex , je viens de comprendre.

**Comment by LordVenom** [comment]
Le jeux de patience pfff

**Comment by LordVenom** [comment]
grep -nHIrF -- cConfig().getAddonPath() (dans le dossier : /home/lordvenom/.kodi/addons/plugin.video.vstream/)
./resources/sites/ddl_island_su.py:905:        #wd = XMLDialog('DialogCaptcha.xml', cConfig().getAddonPath(), 'default', '720p')
./resources/lib/runscript.py:12:sLibrary = xbmc.translatePath(cConfig().getAddonPath())
./resources/lib/runscript.py:204:            wd = XMLDialog('DialogSelect.xml', cConfig().getAddonPath(), "Default")
./resources/lib/handler/pluginHandler.py:51:        sRootFolder = cConfig().getAddonPath()
./resources/lib/handler/rechercheHandler.py:148:        sRootFolder = cConfig().getAddonPath()
./resources/lib/handler/siteHandler.py:52:        sRootFolder = cConfig().getAddonPath()
./resources/lib/about.py:10:sLibrary = xbmc.translatePath(cConfig().getAddonPath())
./resources/lib/about.py:84:        sMath = cConfig().getAddonPath().replace('plugin.video.vstream', '')
Search completed with 8 matches.

**Comment by TmpName** [comment]
Lol, attend je regarde j'en ai pas vu autant de mon cote.

**Comment by TmpName** [comment]
Ha oui il y a def getAddonPath(self): et getSettingCache(self):
Mais pr le second tu recupere la valeur dans sRootFolder et tu fais 
`sFolder = os.path.join(sFolder, 'resources/art/').decode("utf-8")`
 un peu plus tard, donc faut le laisser en utf-8


Pareil pour about.py
```
        sMath = cConfig().getAddonPath().replace('plugin.video.vstream', '') 
        sFolder = os.path.join(sMath, folder).decode("utf-8")
```

Donc pas de convertion.

J'y ai passe une heure a suivre toute les commandes hier, donc je pense pas etre trop mauvais, en passant le mieux c'est dutiliser les commande de @johngf (direct en utf-8) VStranslatePath()

**Comment by LordVenom** [comment]
dll_island c'est le code pour la nouvelle popup toujours pas activer et pour les info ça vas buguer ou pas ?

config.py 

        wd = XMLDialog('DialogInfo.xml', self.__oPath, 'default', '720p')
        wd.doModal()

**Comment by TmpName** [comment]
Ha yet, ici faut wd = XMLDialog('DialogInfo.xml', self.__oPath.decode("utf-8"), 'default', '720p')

**Comment by TmpName** [comment]
Et avec ces modifs ca dit quoi sur vos install ?

**Comment by razorex** [comment]
pour info chez moi le menu selectionner vos sources dans la recherche fonctionne (je viens de télécharger la bêta)

**Comment by LordVenom** [comment]
@razorex  loggggggggggggggggggggggg

**Comment by TmpName** [comment]
Ben ca a l'air bon non ?
Y a un soucis avec les logs, ca coupe son fichier avant la fin.

**Comment by razorex** [comment]
un log [ici](https://pastebin.com/amSeFwMF) et un autre s216AJV11e

**Comment by razorex** [comment]
mais encore [ici](https://pastebin.com/7gdMjY07)

**Comment by razorex** [comment]
donc j'ai désinstallé kodi 16.1 et installé la 17.1, quand j'installe vStream depuis son repo (vStream) j'ai un défaut "error to start common cache. check log" j'avais activé le debug de kodi avant. Mon log d'installation [ici](https://pastebin.com/xdXfD06g)

**Comment by LordVenom** [comment]
Je me suis reconvertis en moteur de recherche : https://www.youtube.com/watch?v=ff9wI0KkJs0

**Comment by razorex** [comment]
sorry je pensais que c'était une dépendances de vStream

**Comment by TmpName** [comment]
Y a vraiment un soucis avec les logs, rebelotte ca a coupe son log au caractere accentue. Pourtant a d'autre endroit il s'affiche sans prb.

**Comment by johngf** [comment]
@razorex comme tu avait le soucis de log j'ai fait une modif sur la beta quand tu as le temps reteste upload log

**Comment by TmpName** [comment]
Je sais pas non plus d'ou vient ce bug.
ll y a encore eu des logs coupe today, et pas d'accent dedans. Ca ressemble a une limite de taille.

**Comment by johngf** [comment]
oui la limite de taille c'est parce qu'il y a  timeout au bout d'un moment
sinon windows peut coupé le fichier [ici](http://stackoverflow.com/questions/9644110/difference-between-parsing-a-text-file-in-r-and-rb-mode)

**Comment by TmpName** [comment]
On en est ou ici ? On cloture ?

**Comment by razorex** [comment]
pour l'instant de mon côté tout à l'air ok. Donc je pense que oui.

**Comment by razorex** [comment]
je reviens encore....... toujours pas de mise à jour hebdomadaire (pas les maj mensuelle) depuis un pc...

**Comment by LordVenom** [comment]
Tu as toujours ton dossier d'utilisateur avec accent ?

**Comment by razorex** [comment]
J'ai enlevé l'accent mais faudrait que je le réinstalle si je veux le viré correctement.

**Comment by TmpName** [comment]
Je croyais que les accents refonctionnaient ?

**Comment by johngf** [comment]
en faitee avec windows si tu change le nom d'utilisateur l'ancien est toujour utilisé pour certain truc et tu ne peut pas le viré totalement 
@razorex test en créant un nouveau compte

**Comment by razorex** [comment]
oui @TmpName plus de pb avec les accents (a priori) je sais pas si sa a un rapport avec eux. Question est-ce que certains d'entre vous on vStream sous windows et avez vous les update régulière (les mensuelles ne pose pas de souci chez moi). Après je peux faire un test en créant un second compte oui.

**Comment by TmpName** [comment]
Yep, beaucoup mieux depuis la V17.
Tu as quoi comme date indiquée dans les option de Vstream ?
Rien dans les logs ?

**Comment by razorex** [comment]
dans le log: Vstream: Prochaine verification de MAJ le : 2017-05-27 19:09:37.631000
et dans les options il est dit derniere maj 22/05 à 16:03 mais je n'ai pas eu l'affichage mise à jour dispo

**Comment by TmpName** [comment]
Ha wé ca fait 5 jours, peut etre leur cache a la con, vide le cache de kodi (pas de vstream). 
Mais moi quand la page etait en cache le ligne "Vstream: Prochaine verification de MAJ le : 2017-05-27 19:09:37.631000" ne s'affichait meme pas dans les logs (vu que pas chargée).

Et si tu triches en avancant la date apres le 27 ?

**Comment by razorex** [comment]
j'ai vidé tous les caches plusieurs fois ces derniers tant (test). non pas tester le remplacement de la date. mais a chaque fois que je lance vStream la date de la prochaine maj évolue...... j'ai pris l'habitude de récup la beta mais ceux sur W....... doivent forcément avoir le pb, je parle de ceux qui utilise vStream sur leur pc

**Comment by johngf** [comment]
j'ai windows 7 et pas de soucis de maj

**Comment by TmpName** [comment]
@razorex touches a rien stp (je parles de tes accents), je vais voir si je peux te faire tester une nouvelle version du fichier.

**Comment by TmpName** [comment]
Bon je t'ai mis une nouvelle version du fichier about.py.
- la date de la prochaine MAJ est corrigée (elle affichait juste la date de today + 3 jours)
- Une ligne de + en log
- Si ca rate durant le telechargement les noms s'afficheront en rouge.
- Si ca rate durant la verification, ca ne memorise pas la date.

Au moins si ca deconne j'espere avoir plus d'infos, parce que je ne vois aucun prbs.

A modifier dans le fichier setting.xml
service_time = date de la derniere MAJ a modifier pr forcer la maj.
home_update = MAJ a faire ou pas.

**Comment by razorex** [comment]
j'ai donc créer un autre user sans accent et installé vStream. j'ai eu la mise à jour auto.

**Comment by TmpName** [comment]
Lol, trop tard, fallait un cobaye avec une install avec accent. Now c'est foutu, on pourra plus tester.
Pas grave si ca deconne encore, on va bien avoir quelqu'un qui aime les accents comme toi qui va repasser par ici.

**Comment by razorex** [comment]
mais si j'ai fais sur un autre pc

**Comment by TmpName** [comment]
Ha, ok alors replace le fichier about.py par le dernier en date (ou la beta complete) et dis moi si ca deconne encore stp (tu devrais avoir plus d'infos dans les logs ou meme un message d'erreur).

**Comment by razorex** [comment]
about c'est fais je regarde le log

**Comment by TmpName** [comment]
Bon ben c'est nickel ^^. On sait que le prb se trouve entre les lignes 131 et 136.
La je vais prendre l'apero donc je continuerais demain mais si tu veux tester rajoute des 
```
cConfig().log("test1")
cConfig().log("test2")
```

pour voir si tu peux avancer le smilblic

ou des

`cConfig().log(rootpath)`

**Comment by kikikodi** [comment]
Dites moi rien à voir , kodi me propose la 17.3 est elle stable àvec vstream ou pas ? Ou vaut mieux attendre ?

**Comment by TmpName** [comment]
Nope, pr moi tu peux l'installer, c'est pas une MAJ majeure.

**Comment by kikikodi** [comment]
Ah ok parceque j'ai balisé LOL , j'ai pris peur avant de l'installer, aussi est-ce que le fait de le mettre à jour me fait perdre mes réglages et extensions?

**Comment by razorex** [comment]
ok mais where c'est ligne?? molo sur la boutanche

**Comment by TmpName** [comment]
Jusqu'a present je n'ai jamais perdu reglages/extension a chaque MAJ de kodi.

Essayes ce fichier @razorex https://pastebin.com/cC2ULb4H

Tu vas avoir un gros message d'erreur si tout se passe bien (wé ca fait bizarre dit comme ca)

**Comment by razorex** [comment]
voilà
`[PLUGIN] Vstream: SQL ERROR EXECUTE`

**Comment by TmpName** [comment]
Heu ? Ca c'est pas normal. Tu aurais pas le log plus complet ?

**Comment by razorex** [comment]
le pastebin [ici](https://pastebin.com/McvTEW8v)
oui juste avant le message d'erreur

**Comment by TmpName** [comment]
Bon ben j'ai corrige quelques fichiers ou y avait encore des prb d'accents, j'espere que c'etait ca.
Par contre j'ai modifie puis revenu en arriere plusieurs fois donc je peux pas te dire quels fichiers sont modifies au final , tmbd.py guielement.py cconfig.py about.py de memoire.

**Comment by razorex** [comment]
DSL te faire tant de pb

**Comment by TmpName** [comment]
C'est mieux la ?

**Comment by razorex** [comment]
Non je viens d'installer la bêta et je reste toujours à la date du 20/05.
`13:59:03.255 T:3892  NOTICE: 	[PLUGIN] Vstream: Erreur durant verification MAJ
13:59:03.885 T:4076   DEBUG: Saving fileitems [plugin://plugin.video.vstream/]
13:59:03.886 T:4076   DEBUG:   -- items: 15, sort method: 0, ascending: false
13:59:03.890 T:3892  NOTICE: 	[PLUGIN] Vstream: Table initialized`

**Comment by TmpName** [comment]
C'est bon me suis fait une install a accent pr tester.
juste le fichier about a modifier.

**Comment by razorex** [comment]
je viens de mettre la bêta et ohhhh miracle mise à jour disponible... lol

**Comment by TmpName** [comment]
Enfin.
