### ISSUE TITLE
Menu string

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1240]
J'ai rajouté ce "texte" dans mes fichiers string (en & fr) et pourtant je n'ai que le commentaire en anglais qui s'affiche. Y a t'il une manip pour la prise en compte du francais?
Pour la version fr:                                          
msgctxt "#30106"                                         
msgid "By Years"                                           
msgstr "Par Années"    

Pour la version en:
msgctxt "#30106"
msgid "By Years"
msgstr ""

**Comment by Kodigoal** [comment]
ca doit s'afficher ou ? menu vStream ou tu bidouilles un site?

**Comment by razorex** [comment]
Dans le menu home j'ai rajouté une fonction "pour moi" MOVIE_ANNEES donc quand je vais dans le menu 'Films' j'ai bien le menu mais en anglais pourtant j'ai modifié les deux langues.

**Comment by Kodigoal** [comment]
Testé de mon côté , d'abord mis string anglais = ok , puis mis string fr , je reliste Films/ ca m'affiche bien 'Par année'.
Un soucis de cache pêtre ... si tu mets #30104 dans le fichier Home  à la place de 30104, ca t'affiche 'Les mieux notés' ou 'Top Rated' ? 
Sinon je sais pas trop ..

**Comment by razorex** [comment]
Je viens de faire ta manip m'affichais bien "Les mieux notés" donc je suis revenu en arrière et maintenant sa fonctionne "Par Année" affiché.Surement un pb de cache oui. Merci
