### ISSUE TITLE
Je n'arrive pas à trouvé comment on ajoute quelque chose à la library...

### ISSUE THREAD

**Issue by thib5** [Kodi-vStream/venom-xbmc-addons#1241]
Salut je vois qu'il y a des préférences pour ça dans Stream je voie aussi qu'il a une section Library mais je ne trouve pas comment ajouté des trucs à la library... rien dans le menu contextuel ...

**Comment by Kodigoal** [comment]
Petite explication du fonctionnement de la librairie:
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1027

**Comment by thib5** [comment]
Je n'ai pas trouvé l'information que je voulais ... c'est avec un click droit puis ajouté à la library ? je n'ai pas cette option :

[http://imgur.com/a/dT9tm](url)

**Comment by johngf** [comment]
c'est normal c'est uniquement sur le dernier lien celui avec l'hébergeur en bleu ciel

**Comment by thib5** [comment]
ah oui ... c'est pas super pratique ... est-ce que ça serai possible dans une future mise a jours de faire un ajout a la library d'une série complet de recherche visuel ( donc dans la library on retrouverais la série avec tout les épisode et lors ce qu'on clique sur un épisode la VStream part une recherche 

J'imagine que si je peut mettre un résultat de recherche visuel en marque page il pourrait aussi être possible de l'ajouté à la library ? 

à la limite ça n'est même pas obliger de ce mettre à jours ça peut juste être un liens vers Vstream

**Comment by johngf** [comment]
non la library c'est des liens de lecture pour le reste il y a les marque pages

**Comment by TmpName** [comment]
Petite question pr infos. Pkoi tu preferes la librairie aux marques pages ? (Qui elle permet justement de mettre toute une saison en favoris)

**Comment by thib5** [comment]
J'ai toujours préféré utiliser la library ... meilleur intégration à Kodi ... tu peut le mette facilement direct sur la page d'accueil mélanger 2-3 addon,  ainsi que des vrai video local... utiliser les playlist, TVtuner que j'adore ! Donc j'aurais vraiment aimer mettre un résulta de recherche dans la Library avec une simplement redirection vers la recherche vstream... la mon setup ses toute mes série anglais dans ma library et appart dans un sous menu un liens vers le marque page de vstream. Sa aurait été plus coool de tout avoir à la même place

**Comment by TmpName** [comment]
Ok.
Je te dis ca, car justement il y a a peine 2/3 jours on allait la supprimer car on ne voyait qui pouvait s'en servir ^^.

Sinon oui, c'est possible de remonter plus haut, et donc de prendre une saisons, mais le prb vient de l'integration apres.
Dans ta mediatheque tu as un formatage special. Cf https://wiki.mpdb.tv/go/Organisation_de_vos_fichiers
Donc normallement tu es sense avoir un fichier par video pour rester correct, et que kodi aille cherche les infos par episode.

**Comment by thib5** [comment]
En effet présentement je ne sais pas si ses vraiment pratique faut ajouter manuellement chaque épisode .... mais pour les films ses déjà un peut mieux ! Mais pour les série  je réécoute rarement 2 fois la même série. C'est donc beaucoup de trouble quand je pourrais juste cliquer dessus ! Sinon je ne suis pas programmeur mais je ne crois pas que sa doit être 100% biens intégrer pour que sa sois déjà plus pratique ... je sais pas si ses fesable de faire pointer une strm directement sur une série complète parce que même si dans la library je ne voie pas chaque épisode et que je doit cliquer sur un liens qui m'amène à la bonne place dans vstream  je m'en fous ses pour une minorité de série de toute façon mais d'avoir un liens vers ma série vstream dans ma library m'éviterait de devoir retourner au menu général puis dans mon racourcis vers les marque page et ensuite choisir parons mes marques page la série que je veut ...  quelque chose comme chaque série contient qu'un seul épisode qui s'appelle vstream  qui ne se met jamais à jours mais qui pointe vers un résulta de recherche ou quelque chose comme sa .... je sais pas je lance dès idée mais si c'est pas fesable ou trop difficile je comprend !

**Comment by LordVenom** [comment]
Dsl j'ai pas suivis mais pk ne pas demander avec une popup préremplie avec le nom de creer le dossier. comme pour téléchargement.

**Comment by TmpName** [comment]
Tu as pas regarde mon lien ^^.
Pour l'integration des series kodi va dans un des repertoires de ta mediatheque.
Ensuite, il cherche le sous repertoire des saisons, si il le trouve il prend tout les fichier qui sont dedans et cherche le numero d'episode, puis avec ses infos il a tout ce qu'il faut et commence le scraping.
Si il ne le trouve pas il cherche a deduire l'episode et la serie a partir du nom par rapport au SXXEXX du nom.
Si par exemple tu n'as pas d'episode 2, ca va t'afficher l'episode 1 puis le 3.

Sachant cela, comment tu vas organiser le fichier strm, et quel nom vas tu y donner ?

Le gros avantage des favoris c'est que justement c'est a part (enfin pr moi) tu trouves une serie, tu met la saison en favoris et tu l'efface 1 semaine apres quand tu as fini, car la garder plus longtemps ne sert a rien, les liens chnagent et deviennent vite invalides. La a chaque fois que je veux tester la librairie de Vstream, je galere a tout revirer apres pour retourner a mon install d'origine.

Apres pour les manip en plus cette fois je ferme ma gueule car je suis repasse sous confluence car justement le nouveau theme de merde me demande plus de manip pr arriver a mes series.

**Comment by TmpName** [comment]
Je ne pense pas, les liens ne sont pas assez stables dans le temps.
