### ISSUE TITLE
Votre avis sur parsetitle

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1246]
Voila comment ça fonctionne 

```
sPattern = '(?P<title>.+)\sSaison\s(?P<season>.+)'
ResultTitle = oParser.titleParse(sName, sPattern)
sResultTitle['qual'] = aEntry[3]
```

print sResultTitle

ça retourne un dict {title:montitre, season:02} ect.. que guielement sais traduire et colorer. Reste quelque reglage a faire mais pour le traitement c'est pas mal mais il faut que les sites soit un peux logique sur alluc même pas la peine.

**Comment by TmpName** [comment]
Mais c'est pour mettre ou ?
guielement sais deja traduire et colorer, tu veux encore refaire la fonction TraiteTitre() ?

**Comment by LordVenom** [comment]
Oui et non comme j'avais dit je cherche un autre system et je suis toujours pas satisfer du traite titre y a que toi qui comprend ceux qu'il fait lolll.Mais je fait des test en off je voulais juste ton avis sur le traitement si tu voie une limiter ou un logique qui m’échappe peux être.

**Comment by TmpName** [comment]
Ben je vois une limite ^^, la complexite du regex. Tu vas mettre quoi comme regex pour traiter ces 2 titres en meme temps ?
"blabla saison 1"
"saison 1 blabla"
Et c'est pas des cas complexes. Beacoup plus facile avec la methode en place.

**Comment by LordVenom** [comment]
Ha mais c'est destiner au site pas au coeur, le coeur lui coloriser et dispatche les saisons anné ect.. si il sont la.

**Comment by TmpName** [comment]
Ha ok, j'avais pas compris.
Alors j'ai peur pr la surcharge de calcul, un calcul de regex dans la partie site, puis encore dans le Gui (meme si du coup il sera plus leger).
Y a pas moyen de faire que avec la partie GUI, y aura jamais plus performant, tu en aurais besoin ailleurs et avant le traitement ?

**Comment by LordVenom** [comment]
Le plus rapide et aussi le plus simple en terme de dev futur ces que les sites gere les oGuiElement.setTitle()
oGuiElement.setSaison()
ext.. et arette les Output qui donne des urls de dingue.

Mais bon en compromis tu (oParser.title) le title et tu retourne le resultat dans addmovie puis guielement .format le titre et dispatche les saison episode année ect..

Dans le Gui y a pas de calcul juste un Format soit c'est du code mais question vitesse c'est respectable.

**Comment by TmpName** [comment]
Ha oui gros prb sur les urls.
Mais si le titre est brut, ca va juste donner "title=nom de la serie Saisons 4 epsiode 8" je trouve pas ca enorme comme code en plus, compare au boulot de recuperer ces infs sur cxhaque fichier sites de maniere independante.

Par contre je pense encore avoir vu des [color] passer dans des  cOutputParameterHandler.

**Comment by LordVenom** [comment]
MovieTitle et la a cause de l'abense de titre propre dans guielement si ont peux tirer un titre propre ben du titre c'est dejas ça de virer et moi il me pompe l'air ce movietitle je sais jamais ceux qui y a dedans.

**Comment by TmpName** [comment]
Pareil, et il y a souvent des bugs a cause de ca. Le code utilise un coup l'un, un coup l'autre.

La par contre moi je suis pour:
1 - Virer sMovieTitle.
2 - Forcer un titre clean dans sTitle, la j'entend titre complet avec saison episode, caracteres speciaux, mais PAS de couleurs.
3 - Couleur uniqument via oGui.addMovie mais jamais oOutputParameterHandler.addParameter.

Mais d'ailleurs il vient d'ou ce parametre ? Dans le code on utilise que sMovieTitle pkoi on voit sTitle en parametre dans les liens ? Prb dans guielement ?

**Comment by LordVenom** [comment]
sTitle et le titre afficher sMovietitle et le title qui seras utiliser dans la base de donnée, pour reutilisation par exemple.

**Comment by TmpName** [comment]
J'ai plus le code en memoire mais y a vraiment besoin du titre affiche ? On le passe a la fonction qui l'affiche et on l'oublis direct sans le repasser en url ?

**Comment by LordVenom** [comment]
La tu m'en demande trop avec tous les changements je me suis perdu et c'est vraiment pas le plus motivant comme taff donc tranquillement mais surement.

**Comment by LordVenom** [comment]
En gros quand ont passe une saison ou autre par guielement il faudrais utiliser xbmc.getInfoLabel('ListItem.season') pour récuperer l'info et pas un output mais la tous et mélanger certain arrive par guielement d'autre en out et sMovieTitre c'est juste le titre passer dans str_conv de config titre propre sans couleur sans saison puisque les saisons sont gerer dans guielement.

**Comment by LordVenom** [comment]
Le soucis c'est la nivagation meme avec xbmc.getInfoLabel si tu fait un Back il a oublier donc ont peux passer en url le dict {Season :03, title:montitre} pour pouvoir le reutilser ont peux pas faire autrement.Le soucis c'est le host qui ajouter le nom du host a titre et donc transforme le dict en str de la il le comprend plus.

**Comment by LordVenom** [comment]
1 - Virer sMovieTitle. / pas possible pour le back xbmc a tout oulier même le titre.
2 - Forcer un titre clean dans sTitle, la j'entend titre complet avec saison episode, caracteres speciaux, mais PAS de couleurs. D'ou l'idée d'un dict qui comtient toute les info séparer et seul l'affichage le colorise mais ça surement gener pour le context menu. a voir...

3 - Couleur uniqument via oGui.addMovie mais jamais oOutputParameterHandler.addParameter. c'est simple a faire mais pour le moment pas de dict ancien traitement et dans le futur pas de dict pas de traitement purement et simplement.

**Comment by LordVenom** [comment]
note trouver comment modifier Hoster setDisplayName sans modifier tout les hosts.

**Comment by TmpName** [comment]
Mais le dictionnaire tu voudrais le faire passer comment ? par oOutputParameterHandler.addParameter ou oGui.addMovie ?
Dans les 2 cas tu passes au meme endroit le titre complet qui va etre parse et qui pourait renvoyer tes infos au bon endroit, si j'ai bien compris.
Car en parametre Stitle="Season 03 montitre" ou un sDict = {Season :03, title:montitre} c'est pas plus court.

**Comment by TmpName** [comment]
Sinon autre soucis. Pour viewinfo on utilise 
sFileName = oInputParameterHandler.getValue('sFileName')

Pkoi ne pas utiliser sTitle = oInputParameterHandler.getValue('sTitle') qui est plus facilement nettoyable ?

def setFileName(self, sFileName):
        self.__sFileName = self.str_conv(sFileName)
Probleme la fonction str_conv qui a l'origine servait juste a formater les titres dans un format compatible avec la base de donnee, fait aussi un triatement via regex. Et elle est bugguee du coup  ca fait deconner viewinfo.

```
addMovieDB(ID,fonction,"titre a afficher",icone, ......)
        if oOutputParameterHandler.getValue('sMovieTitle'):
            sTitle = oOutputParameterHandler.getValue('sMovieTitle')
            oGuiElement.setFileName(sTitle)
```
Je commence a douter de l'utilite de sMovieTitle, depuis un moment il n'y a plus de sMovieTitle propre (avec juste un titre), on est oblige d'y passer par exemple la saison ou la langue, car a la page d'apres ce n'est pas memorise. D'ou le patch dans str_conv.

Par contre la fonction TraiteTitre, elle est capable de donner le titre propre, sans deco, sans la langue, et sans faire de calcul regex en plus, suffirait de mettre self.setFileName(sTitle) vers la ligne 304.

Probleme, dans de rares cas, on utilise la vielle methode, c'est a dire par exemple
sMovieTitle = Saison4 episode 8 nom de serie
sLabel (passe via addMovieDB) = Saison4 episode 8 nom de serie NOM_DE_HOSTER VF
Et la pas de bol, on se retrouve avec le cas inverse, et le code actuel marche mieux.

Je pense que ca rejoint ton idee pr le dictionnaire, mais comment le faire passer d'une page a l'autre ?

PS: je reprend mon soufle, suite dans 10mn)

**Comment by TmpName** [comment]
Methode 1 : tout passer par sLabel
On ne se sert plus de sMovieTitle, le titre est donne par TraiteTitre()
Avantage:
- pas de grosses modif du core
- un seul parametre a passer d'une page a l'autre > sMovieTitle par exemple
- un seul parametre qui contient nom, saison, langue pr le traitement > sLabel.
Inconvenient
Tout ce qui n'a rien a voir avec le titre DOIT etre entre tag pr etre vire par la fonction TraiteTitre(), "Nom de serie S4E7 youwacht " fera tout deconner.

Methode 2: le dictionnnaire
La par contre je te laisse continuer, car je ne vois pas du ou l'inserer ^^.

**Comment by TmpName** [comment]
Bon j'ai peu etre une idee, c'est la fonction traitetitre qui genererait ton dictionnaire et qui le rajouterait dans oOutputParameterHandler dans addFolder() juste avant le 
`sItemUrl = self.__createItemUrl(oGuiElement, oOutputParameterHandler)`

**Comment by LordVenom** [comment]
Mais les site ont besoin d'un movietitle pour le retour arriere.

**Comment by LordVenom** [comment]
Bon imagine la ont a            
 "siteUrl": oGuiElement.setSiteUrl,#indispensable
"sTmdbId": oGuiElement.setTmdbId,
 "sImbdId": oGuiElement.setImdbId,#inutile ?
"sYear": oGuiElement.setYear

defoix sSaison et sEpisode

url = siteUrl=url&title=montitre saison 1 episode 4&sTmdb=2155&episode=4&saison=1& ect..

url=siteUrl=url&title={title:montitre,saison:1,episode:4,tmdb:2155}

Pas de rapelle saison = et l'usage devrais être simplifier.

**Comment by LordVenom** [comment]
voila un param 

`{'function': 'showHosters', 'sMovieTitle': 'Ai%20Shoujo%20Pollyanna%20Monogatari%20Episode%20005%20%5bVF%5d', 'siteUrl': 'http%3a%2f%2fwww.adkami.com%2findex.php%3fpage%3dmanga%26id%3d1874%26episode%3d005%26version%3d1%26genre%3d1', 'site': 'adkami_com', 'title': '%5bCOLOR%20lightcoral%5dE005%5b%2fCOLOR%5d%20Ai%20Shoujo%20Pollyanna%20Monogatari%20%5bCOLOR%20lightcoral%5d%5bVF%5d%5b%2fCOLOR%5d'}`

title ne "peux pas être suprimer puisqu'il et directement donner dans le creation de l'element

`sItemUrl = '%s?site=%s&title=%s&%s' % (sPluginPath, oGuiElement.getSiteName(), urllib.quote_plus(oGuiElement.getTitle()), sParams)`

**Comment by LordVenom** [comment]
Solution modifier
       oListItem = xbmcgui.ListItem(oGuiElement.getTitle(), oGuiElement.getTitleSecond(), iconImage=oGuiElement.getIcon(), thumbnailImage=oGuiElement.getThumbnail())
        oListItem.setInfo(oGuiElement.getType(), oGuiElement.getItemValues())

c'est ce   oGuiElement.getTitle() qui doit avoir le format.

**Comment by LordVenom** [comment]
`{'function': 'showHosters', 'siteUrl': 'http%3a%2f%2fwww.adkami.com%2findex.php%3fpage%3dmanga%26id%3d1874%26episode%3d005%26version%3d1%26genre%3d1', 'site': 'adkami_com', 'title': '%7b%27lang%27%3a%20%27vf%27%2c%20%27episode%27%3a%20%27005%27%2c%20%27title%27%3a%20%27Ai%20Shoujo%20Pollyanna%20Monogatari%27%7d'}`

**Comment by LordVenom** [comment]
Bon j'avance mais ça bug arrive au hoster.

**Comment by LordVenom** [comment]
Bon je vais pas tarder a faire la mise a jour ont continue de regarder aprés comme ça ont a du temp pour les test.

**Comment by TmpName** [comment]
Y a un test a faire pr le retour arriere pour tester l'obligation de smovietitle ?
Car chez moi, il n'y a pas de chargement, rien qui bouge dans les logs, c'est juste un re-affichage de la page memorise. Enfin je dis ca sans avoir fait de test, mais je trouve ca bizarre.

Donc en resume qui vont passer en parametre (et pr moi ca suffit)
function': 'showHosters
siteUrl': 'vvv:/site/adresse/page'
site': 'site_com'
'title': Titre A AFFICHER
'data' (par exemple) : {title:montitre,saison:1,episode:4,tmdb:2155,'years':2015}

sMovieTitle ???

Maintenant ma question N°1, je suis dans le fichier site, j'ai extrait via regex la chaine de caractere "Nom de serie Saison 7 VF", j'en fais quoi ? sachant que je veux aussi afficher a la fin du titre "WEBRYP opnlad"
- Si je passe en title "Nom de serie Saison 7 VF WEBRYP opnlad" ca va me traiter la fin de ma chaine alors que y'en a pas besoin je veux juste l'afficher et pas la traiter
- Je fait le traitement moi meme dans le fichier site et je remplis moi meme data avec le bon titre, la bonne saison, et ect .... Du coup traiteTitre ne sert plus, enfin si mais elle sera light juste pr la coloration et mise en page.

Et la question N°2, comment garder la compatibilite entre les versions ?

**Comment by johngf** [comment]
Pour ta premiere phrase chez moi souvent le retour arriere rapelle la fonction precedente

**Comment by LordVenom** [comment]
Le cache a une limite d'utilisation il faut + de 25 entrer pour l'activer il me semble.

**Comment by LordVenom** [comment]
Je travail sur toute tes questions j'ai pas encore la réponse puisque je suis pas sure des retours code mais si j'arrive a passé un Dict peux importe que tu le face toi même ou via le parse le resultat et le même il suffis d'utiliser les bons mot clef voir guielement function traitetitle.Je travailler pour coloriser a la sortis et plus a l'entrer pour avoir un titre= propre dans l'url. maintenant c'est possible avant c'etait pas possible.

**Comment by LordVenom** [comment]
hum

function': 'showHosters
siteUrl': 'vvv:/site/adresse/page'
site': 'site_com'
'title': si dict affichage coule sinon juste title {title:montitre,saison:1,episode:4,tmdb:2155,'years':2015}

Non les besoin supplémentairement seront toujours en outputt puis output = sysarg

**Comment by LordVenom** [comment]
Pour exemple c'est propre non ? 7ms tranquille 

https://regex101.com/r/ei6lul/2

**Comment by TmpName** [comment]
Oui mais ca ne marche que si tout est dans le bon ordre.
"Saison 4 ma serie" marchera pas.
C'est impossible de prendre tout les cas possible avec un seul regex, (enfin si mais laisse tomber le monstre), il vaut mieux plusieurs regex et une boucle.

**Comment by LordVenom** [comment]
Oui oui mais peux importe la c'est le regex de parstitle mais tu peux faire en supr search ect.. temps que à la fin du retourne un Dict propre pas de soucis.

**Comment by LordVenom** [comment]
Bon ça tourne sans smovietitre mais le host n'affiche pas les couleurs et les saisons simple resond il y a une balise [color= dans le host ça vas être chiant.

**Comment by LordVenom** [comment]
`C'est impossible de prendre tout les cas possible avec un seul regex, (enfin si mais laisse tomber le monstre), il vaut mieux plusieurs regex et une boucle.`

un exemple ?

**Comment by TmpName** [comment]
Un exemple, mais non fonctionnel, c'est juste pr te montrer l'horreur que ca peut etre.
https://regex101.com/r/mD4vM8/3

**Comment by LordVenom** [comment]
Je parler d un exemple de la boucle.

**Comment by TmpName** [comment]
Ben la boucle y 'en a une dans TraiteTitre.

**Comment by LordVenom** [comment]
Alors la tu m'a perdu...

**Comment by LordVenom** [comment]
Sinon toujour dans le fichier site

```
              sPattern = 'Episode\s(?P<episode>.+)'
                sResultTitle = oParser.titleParse(aEntry[2], sPattern)
                sPattern = 'Saison\s(?P<season>.+)'
                sResultTitle.update(oParser.titleParse(sSaison, sPattern))
                ou sResultTitle['title'] = "mon titre
```

**Comment by TmpName** [comment]
En fait TraiteTitre est une boucle qui traite tout les regex un par un.

**Comment by LordVenom** [comment]
Pour finir:

pour recuperer un titre propre oInputParameterHandler.getValue('title') inutile d'envoyer en plus un movietitle 

stitle d'une fonction addmovie, adddir ect.. ce divise toute seul en 3 sTitle vas etre transformer pour couleur scleantitle seras renvoyer d'en l'url title="titre propre sans couleur" sfilename deriver de cleantitle transformer pour la creation de dossier ou BDD
