### ISSUE TITLE
Erreur common cache a l'instal de vStream sur pc

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1249]
comment faire pour installer une dépendances a part "script.common.plugin.cache"

**Comment by johngf** [comment]
Normalement elle s'installe en meme temps que vstream 
Sinon dans extension va dans le repo de kodi recherche tu tape le nom

**Comment by razorex** [comment]
j'ai essayer pas de script trouver

**Comment by Kodigoal** [comment]
http://mirrors.kodi.tv/addons/
choisir version kodi et tu le trouveras pour l'installer manuellement.
