### ISSUE TITLE
Marque-Page : Ajout de Source impossible

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1251]
Hello,

En utilisant le menu : "toutes les sources"
J'ai voulu ajouter un des sites aux marques pages.
Mais le bouton "Ajouter Marque-Page" n'est pas présent dans le menu.
Est-ce normal ?

Merci pour votre réponse et longue vie à vstream.

**Comment by johngf** [comment]
oui c'est normal mais tu peux l'ajouter au favoris de kodi la petite étoile en bas quand tu démarre kodi

**Comment by canopre** [comment]
Ok mais alors pourquoi trouve t'on un menu "Sources" dans les marques-pages si on ne peux pas y ajouter de sources ?
Mais j'ai peut-être mal compris un point du fonctionnement...

**Comment by johngf** [comment]
en faite normalement il devrait etre écrit sources vidéos parceque c'est pour les liens avec hébergeur en bleu ciel

**Comment by TmpName** [comment]
Ben c'est pas prevu car il te faut plus de manip pour faire.
"Marque page" / "sources" /"site"
que
"Toute les sources" / "site"

On a jamais prevu que quelqu'un essayerait ca.

**Comment by LordVenom** [comment]
Simple modifier du texte si j'y pense pour les marque page j'ai autre chose en tête mais @TmpName  vas raler lollll

**Comment by TmpName** [comment]
Vas y je commence a avoir peur ?

**Comment by LordVenom** [comment]
C'est pas pour tous de suite mais je vais tester un xml design a la info.Mais je laisserais le choix d'activer ou pas.

**Comment by TmpName** [comment]
Et pkoi je ralerais ^^.
Les marques pages c'est le truc dont je me sers le plus, et pr moi c'est plus utilies que la libairie ou les favoris.

**Comment by LordVenom** [comment]
Je pense pas mais pour le moment pas d’actualiter les tests que j'ai fait ne m'on pas convaincus je re-test quand je veut me changer les idées lol.
