### ISSUE TITLE
Plus d'accès aux marque-page

### ISSUE THREAD

**Issue by fredo04** [Kodi-vStream/venom-xbmc-addons#1262]
Bonjour à tous.
Je n'arrive plus à accéder aux marque page.
J'arrive jusqu'à la liste des catégories (films, séries, TV.....), Le nombres de films est bien noté en face et lorsque j'en ajoute le nombre augmente bien mais quand je choisis films ben rien ne se passe.
Help svp car les marques pages sont indispensables pour moi, trop utile..... comme vstream d'ailleurs.

**Comment by johngf** [comment]
#931 c'est deja arriver

**Comment by fredo04** [comment]
Qu'elle rapidité....
Je veux bien trouver le problème.
Ma config : boitier TV Android 6, spmc 16.

**Comment by fredo04** [comment]
Bon j'ai suive le solution trouvé ici #931 en installant sqlite manager et bingo après 4 marques page sur 13 supprimé ça remarche.

**Comment by TmpName** [comment]
Et tu n'aurais pas remarque un detail, quelque chose de different de l'un a l'autre pr expliquer ce bug ?

**Comment by LordVenom** [comment]
je parie pour un accent dans le titre ?

**Comment by fredo04** [comment]
Dsl j'étais tellement absorbé par la recherche du fautif que j'ai pas pris la​ peine de comparer avec les autres titre.
