### ISSUE TITLE
Comment retirer des favoris 

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1276]
Bonjour les gars, 
Comment peut on retirer des films ou series que j'ai placé dans l'onglet favoris de kodi. 
En gros Ya des films qui e me servent a rien, que je veux retirer mais pour ce faire il faudrait que je retrouve le lien final, c'est a dire aller dans vstream, recherche de film, retrouver le bon site, le bon lien, appuyer sur menu et retirer des favoris... Vous vous imaginer que si j'ai comme cela 15 films à dégager des favoris je vais y passer des jours et sa se trouve ne meme pas les retriuver. Y aurait il une manip plus rapide que vous connaissez ? 
Sous kodi 17.1 krypton
Merci

**Comment by razorex** [comment]
tu ouvre le menu favori et après clic long sur le lien que tu veux supprimer et la une liste de menu s'affiche et tu sélectionne "retirer" (sur kodi 16.1)

**Comment by kikikodi** [comment]
Idem sous kodi 17.1? Sous Android ? Vais tester pour voir la je ne suis pas devant 
Merci de l'info

**Comment by LordVenom** [comment]
google.com favoris kodi, non gerer par vstream

**Comment by kikikodi** [comment]
Lord je parle du fait que si tu est dans vstream er que tu clique sur menu, et ajouter aux favoris, le film ou la series en question est donc ajouté aux favoris, pour ma part ça fonctionne, te restes plus qu'à retourner dans l'onglet favoris et cliquer dessus pour accéder directement au dilm sans faire de recherche dans vstream, plutôt utile je trouve. Par contre impossibilité de supprimer le favoris une fois qu'il y est, ah moins de retriuver exactement le bon site, le bon résolver, et la menu retirer des favoris ... Tu me comprends ? Presque impossible ou d'une galere monstre

**Comment by LordVenom** [comment]
https://www.mykodibox.fr/pages/comment-ajouter-et-utiliser-des-favoris-dans-le-media-center-kodi

Dans Kodi17 il suffis de cliquer sur l'onglet Favoris de kodi pour ouvrir un popup et clique droit pour avoir supprimer.

**Comment by kikikodi** [comment]
Oui mais pour moi sous Android ce que j'appelle le bouton menu équivaut au clic droit je suppose et bien la il nn'y a rien

**Comment by razorex** [comment]
un appui long sur le favori

**Comment by kikikodi** [comment]
Salut razorex, bien j'ai beau appuyer longuement rien ne se passe... Sur Android box je le rappel, donc appuis long équivaut a rester avec le bouton "OK" appuyé sur le favoris pour ouvrir un me pop up je suppose proposant la suppression de celui ci mais moi je n'ai rien qui se passe, et la je suis arrivé a un stade ou c'est le bordel dans mes favoris il y en a des tonnes

**Comment by razorex** [comment]
si tu a bien sélectionner le favori que tu veux supprimer ça devrais marcher

**Comment by johngf** [comment]
quand tu clic sur favoris (avec l'etoile) pas un long clic juste un clic une popup doit s'ouvrir

**Comment by kikikodi** [comment]
Vais détester mais je pense bien avoir fait ce que vous dites, merci en tout cas

**Comment by kikikodi** [comment]
Puisque j'y suis du coup la meilleur solution pour garder en mémoire un film ou une série que l'on voit ce serai plutôt librairie ou marque page dans vstream ? Quel est la différence ?

**Comment by kikikodi** [comment]
Vais re-tester pas détester lol

**Comment by TmpName** [comment]
Marque-page sans hesitation. La librairie est pas au point. Les liens ne sont pas fixes et changent souvent, selon l'endroit ou tu memorises  les marques pages resteront valides plus longtemps.
Aux marques pages tu peux memoriser un lien qui va t amener sur les 10 saisons d'une series.
Les marques pages sont memorise dans la base de donnes de Vstream uniquement, les librairies rajoutent des fichiers, et la maintenance de la librairie est juste un enfer (le nettoyage prend plusieurs minutes chez moi).

**Comment by kikikodi** [comment]
@tmpname donc si je vomprend bien, le marque page il faut le faire apres recherche, quand tu arrives au niveau des résultats par exemple
 1film-ilimite 
-la serie(et c'est donc la qu'on fait le marque page ) 
C'est bien cela que tu me conseille ?

**Comment by TmpName** [comment]
Nope, les marques-pages c'est absolumenbt quand tu veux (contrairement a la librairie), enfin presque quelqu'un a signale un endroit ou ca ne marchait pas la semaine derniere.
Tu peux le mettres apres la recherche, au niveau de la saison que tu veux, de l'episode, et meme du hoster.

**Comment by johngf** [comment]
@kikikodi tu as réussi ?

**Comment by kikikodi** [comment]
Salut non je n'y suis pas parvenu...
J ai fait acquisition d'un clavier sans fil bluetooth qu'on trouve sur internet, il y a clic droit clic gauche et le clavier je vais tester avec ça ... Je pense que le clic long n'est pas comprit pas kodi avec la telecommande type téléviseur de base qui est fournie avec la box Android 
En tout cas merci de revenir vers moi 
A plus les gars 
Mika

**Comment by Kodigoal** [comment]
Si tu as le theme Estuary (?)
Fallait faire la manip de @johngf ...
Se mettre à gauche sur l'onglet  (*)Favori 
Cliquer  1 fois (sur ok) va ouvrir une nouvelle fenetre qui affiche aussi les favoris, et ici en faisant clic droit , on peut les enlever....

**Comment by kikikodi** [comment]
Salut, oui effectivement le problème veanit du fait que je cliquer pas sur l'onglet favoris, en gros si on se positionne sur favoris sans cliquer dessus et que la popup ne n'ouvre ps avec tous les favoris, toutes les manipulations et menu déroulant ou on trouve effectivement "retirer des favoris" n'y est pas peoposé! 
Merci à tous 
Pb résolu
