### ISSUE TITLE
ddl-island

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1277]
DDl-Island ne fonctionne pas sur mon pc (version béta) j'arrive jusqu'au hotes et après plus rien. j'ai tester sur ma box tv et normalement le clavier s'ouvre pour rentrer le captchca. je viens de voir qu'il y a eu modif sur le fichier captchca??

**Comment by LordVenom** [comment]
Pas activer le captcha comme dab le log.

**Comment by razorex** [comment]
Ok mais je peux pas de suite

**Comment by LordVenom** [comment]
Pareil je peux regarder la je tester ce soir

**Comment by TmpName** [comment]
Cette source ne marche pas avec un repertoire a accent ^^.
PathCache pr les cookies n'est pas en unicode faudrait utiliser la lib de cConfig

`from resources.lib.config import GestionCookie`

Sinon elle tourne chez moi, la je pars bouffer, je fais la modif dans la soiree, si personne est passe dessus.

**Comment by TmpName** [comment]
Retestes avec la version que j'ai mise a l'instant.
Je viens de voir que cloudflare aussi peut deconner, je corrigerais plus tard si ca marche chez toi.

**Comment by razorex** [comment]
ok. je viens de voir je teste et te tiens au jus.

**Comment by razorex** [comment]
toujours pas de captchca dsl mon log [ici](https://pastebin.com/amSeFwMF)

**Comment by TmpName** [comment]
ocal variable 'wdlg' referenced before assignment
Ca deconne dans la boucle try a partir de la ligne 885.
Probleme, je ne vois pas le probleme. Dsl de te faire faire le cobaye (a mon avis c'est la derniere fois que tu met des accent dans tes repertoire ^^)
Faudrait que tu supprimes les lignes 
885 try
899 finally
Et que tu recules de 4 caractere tout le bloc, ca devrait donner un truc comme ca
```
    #finnnnn
        
    img = xbmcgui.ControlImage(450, 0, 400, 130, filename)
    wdlg = xbmcgui.WindowDialog()
    wdlg.addControl(img)
    wdlg.show()
    #xbmc.sleep(3000)
    kb = xbmc.Keyboard('', 'Tapez les Lettres/chiffres de l\'image', False)
    kb.doModal()
    if (kb.isConfirmed()):
        solution = kb.getText()
        if solution == '':
            cConfig().showInfo("Erreur", 'Vous devez taper le captcha' , 4)
    else:
        cConfig().showInfo("Erreur", 'Vous devez taper le captcha' , 4)

    wdlg.removeControl(img)
    wdlg.close()
```

En fait ca va desactiver la boucle try, et du coup ca va afficher un nouveau message d'erreur, tu peux le chercher toit meme dans les logs, pas besoin de tout poster, il devrait etre bien visible.

**Comment by razorex** [comment]
lol c'est moi qui suis dsl de vous faire autant de souci.

**Comment by TmpName** [comment]
Alors ? Tu as pu faire la modif pr tester ?

**Comment by razorex** [comment]
non pas regarder dsl. je teste là et je vous tient au courant.

**Comment by razorex** [comment]
22:16:34.536 T:4980   `ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=Display_protected_link&sMovieTitle=%20%20Skins%20%20(SD)&sThumbnail=http%3a%2f%2fimg.emule-island.ru%2f61911_1494169739.jpg&site=ddl_island_su&siteUrl=http%3a%2f%2fprotect.ddl-island.su%2ftkyJkkr&title=Skins%20%5bCOLOR%20lightcoral%5d(SD)%5b%2fCOLOR%5d%20%5bCOLOR%20lightcoral%5d(HitFile)%5b%2fCOLOR%5d
22:16:34.538 T:4980   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=Display_protected_link&sMovieTitle=%20%20Skins%20%20(SD)&sThumbnail=http%3a%2f%2fimg.emule-island.ru%2f61911_1494169739.jpg&site=ddl_island_su&siteUrl=http%3a%2f%2fprotect.ddl-island.su%2ftkyJkkr&title=Skins%20%5bCOLOR%20lightcoral%5d(SD)%5b%2fCOLOR%5d%20%5bCOLOR%20lightcoral%5d(HitFile)%5b%2fCOLOR%5d) failed`

**Comment by TmpName** [comment]
Y a pas un truc qui commencerait par ca ?
could not load site: ddl_island_su error

**Comment by razorex** [comment]
non comme tu peux voir
`10:51:25.020 T:6512  NOTICE: 	[PLUGIN] Vstream: load site ddl_island_su and call function showHosters`

**Comment by TmpName** [comment]
Doit manquer un truc.
Ce message veut rien dire, il apparait 20 fois par jours
Avant tu avais
```
22:45:13 T:1252  NOTICE:    [PLUGIN] Vstream: load site ddl_island_su and call function Display_protected_link
22:45:13 T:6140   DEBUG: ------ Window Init (DialogBusy.xml) ------
22:45:13 T:1252  NOTICE:    [PLUGIN] Vstream: could not load site: ddl_island_su error: local variable 'wdlg' referenced before assignment
22:45:13 T:1252  NOTICE:    [PLUGIN] Vstream: Table initialized
```

L'erreur doit,y etre encore, vu qu'on rien supprime.

**Comment by razorex** [comment]
j'ai
`12:17:18.019 T:6168  NOTICE: 	[PLUGIN] Vstream: could not load site: ddl_island_su error: 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)`

**Comment by johngf** [comment]
les accents encore

**Comment by TmpName** [comment]
Manque le numero de ligne.

**Comment by TmpName** [comment]
C'est bon je pense avoir trouve, teste le fichier ddl_island recement mit en ligne.
Si ca marche, on va pouvoir remodifier tout les endroit du code ou il ya le meme probleme.
en fait kodi marche un coup en unicode, un coup en ascii, selon l alignement des planetes.

**Comment by razorex** [comment]
Tester le captchca est bien apparu et je l'ai rentré, mais dèrriere aucun liens sur mon pc ni sur ma box tv??????

**Comment by TmpName** [comment]
Essayes les uptobox, tout les hebergeurs de ce site ne sont pas supportes, et meme si le lien s'affiche il ya de forte chance pr qu'il soit mort.

**Comment by Kodigoal** [comment]
Juste un truc , pourquoi c'est pas activer le captcha via dialogCaptcha.xml ? ou c'est juste sur la beta qu'on la laissé désactivé ?

**Comment by TmpName** [comment]
Aucune idee c'est pas moi qui gere cette source.
Peut etre parce qu'il fallait attendre la MAJ complete pr l'activer, maintenant ca doit etre possible, perso moi sa m'arrangerait d'avoir une seule fonction pour tout les captcha de Vstream.

**Comment by razorex** [comment]
les autres me disent liens premium. précisions le même film sur le site fonctionne pas sur vStream

**Comment by Kodigoal** [comment]
@TmpName ok je l'active 
@razorex faut se créer un compte gratuit via site uptobox et entrer identifiant dans les paramétres de vStream.
Pour ddl-island ya que via uptobox que ca fonctionne ( après 1 fois le captcha passé , en lancant le lien , mieux vaut passer via uptostream,  en direct via uptobox si 720- son 5.1 ca va lag en compte gratuit , parfois non si pas heures de pointes).
Pour les autres liens , faut je crois activer urlresolver et avoir des comptes premium ou un  compte débrideur à configurer dans addon urlresolver...
Mais avec un compte gratuit uptobox , j'utilise à 90% ddl-island pour films/série via uptostream sans soucis.

**Comment by razorex** [comment]
@Kodigoal pour les liens premium (je savais) mais les autres ne redirige vers rien.... j'ai tester en // sur vStream et sur le site. le ssite j'avais accès et vStream rien même pas le liens pour l'hote....

**Comment by Kodigoal** [comment]
quel film quel hoster ?

**Comment by TmpName** [comment]
J'ai corrige les prb unicode, mais y a un nouveau probleme.
Je l'avais deja eu et je me souvient plus de la manip.
En fait le captcha part en cache, et c'est toujours le meme qui est affiche, meme si celui sur le disque dur change.

**Comment by Kodigoal** [comment]
J'ai remarqué pour le catpcha , mais si t'attend par exemple pour tester en ne mettant pas
 le bon captcha  que la notif ' erreur: Mauvais captcha '  parte avant de relancer le lien , yaura un nouveau captcha. 
Si on relance le lien cash , même captcha..
Enfin chez moi j'ai ce petit soucis lol

**Comment by TmpName** [comment]
Ben justement non, ca m'affiche mauvais captcha (normal vu que c'est le precedent) mais quand je ferme et relance, tjours le meme.

**Comment by johngf** [comment]
avant le code supprimer l'ancien captcha non ?

**Comment by TmpName** [comment]
Nope, et tu peux tester en mettant False a la ligne 827.
Je crois que c'etait une histoire d'ordre de commande, la ligne 896 devait etre en premier, si tu la mettait apres la creation du dialog, meme probleme. J'avais passe du temps dessus, mais me souvient pas de l'astuce.

**Comment by TmpName** [comment]
C'est bon ya une option

> setImage(...)
>     setImage(filename, useCache)--Changes the image.
>      
>     filename : string - image filename. useCache : [opt] bool - true/use cache, false/don't use cache
>      
>     example:
>         - self.image.setImage('special://home/scripts/test.png')

**Comment by TmpName** [comment]
C'est bon en ligne, mais ce serait bien d'avoir un seul fichier pr les captcha pour la prochaine MAJ totale, meme si il n'y que 2 sites en utilisant.
Ca permettrait d'avoir qu'un seul fichier a modifier pr tout les cpatcha.

Reste le bug de @razorex

**Comment by razorex** [comment]
Pour répondre à ta question @Kodigoal c'est pup star ; menu "films SD (derniers ajouts)" sur hitfile et rapigator. Uploaded premium (pas tester) et uptobox (ok)

**Comment by razorex** [comment]
Test d'envoi du log : s213x1t27B

**Comment by johngf** [comment]
Celui la est ok n'a pas était coupé runscript est a la fin

**Comment by TmpName** [comment]
> 19:18:12.231 T:7376  NOTICE:    [PLUGIN] Vstream: could not load site: ddl_island_su error: 'ascii' codec can't decode byte 0xe8 in position 20: ordinal not in range(128)

Et tjours pas le numero de ligne, ca me saoule, demain je corrige ca.

Tu as bien le dernier fichier du site @razorex ? Si oui demain je vais encore avoir du taff pr toi ^^.

Uptobox a marche quand meme ?

**Comment by razorex** [comment]
Pas sur je reteste. oui Uptobox marche.

**Comment by Kodigoal** [comment]
Mais hitfile et rapidGator ca fonctionne pas sans activer urlResolver + compte débrideur c'est normal ..enfin si je dis pas de bétise?
Uploaded aussi faut un compte premium non ?

**Comment by razorex** [comment]
normale que j'affiche pas au moins les liens?

**Comment by TmpName** [comment]
Bon ben c'est le principal, je crois que c'est le seul qui marche a 100%, mais j'aimerais bien savoir d'ou sort ton message d'erreur.

Rien d'urgent, mais ca peut te servir vu que tu testes tout, j'ai mis une nouvelle version de defaut.py qui va afficher toutes ces put1 d'infos pr le debug qui nous manquent a chaque fois.

**Comment by TmpName** [comment]
Uploaded doit marcher que si tu es enregsitre, a cause de la tempo de 30s pr les user lambda, apres gratuit ou pas, j'ai pas teste.
Oui razorex, ca affiche juste les liens geres par Vstream, donc rapidgator n'affichera rien.

**Comment by johngf** [comment]
Faut memorisé le captcha ? A cause de la modif pour estuary

**Comment by razorex** [comment]
suis sous confluence

**Comment by johngf** [comment]
Oui mais cette modif a était faite a cause de estuary donc

**Comment by Kodigoal** [comment]
Normalement ya l'image du petit captcha  qui apparait quand on ouvre clavier en haut si on perd la mémoire ^^

**Comment by TmpName** [comment]
Bon je viens de tester meme en gratuit y a la tempo de 30s, donc uploaded uniquement premium.
@Kodigoal a bidouille un nouveau dialog.
Si tout se passe bien tu as le captcha en fond d'ecran et un petit en haut (le meme)

**Comment by razorex** [comment]
!!!!!!! petit mdr tout l'écran

**Comment by TmpName** [comment]
Lol, wé c'est pr les malvoyants.

**Comment by Kodigoal** [comment]
non regarde au dessus du clavier à gauche ya un petit captcha

**Comment by johngf** [comment]
faut leur dire a dev d'estuary sur le github de kodi qu'ils font de la m.....

**Comment by TmpName** [comment]
Attend si ca marche chez @razorex ca doit marcher partout.

**Comment by johngf** [comment]
C'est la generation tuile et mobile

**Comment by Kodigoal** [comment]
C'était pêtre le dev d'estuary va savoir xD

**Comment by razorex** [comment]
la plus de captchca pour l'instant j'ai clean les caches mais rien

**Comment by TmpName** [comment]
Lol @Kodigoal ouais surement ca, ou quelqu'un de la famille.

**Comment by razorex** [comment]
plus de captchca mais je pense qu'il faut attendre pour devoir en rentrer un de nouveau...
