### ISSUE TITLE
Une idée : plugin plex vstream

### ISSUE THREAD

**Issue by poto25** [Kodi-vStream/venom-xbmc-addons#1279]
Bonjours tout d'abord merci pour le travail que vous faites vous êtes top, tout est dans le titre ma question c'est , est ce que vous êtes capable de créer un plugin vstream pour plex si c'est oui se serait magnifique. 

Merci à vous tous.

**Comment by LordVenom** [comment]
Aucune idée c'est un forks de Kodi mais jamais mis le nez dedans a mon avis trop de différence dans le code.

**Comment by Kodigoal** [comment]
https://github.com/croneter/PlexKodiConnect
Et ca , ca le fait pas ? 
Vu que l'addon officiel plex for kodi , faut payer ...
