### ISSUE TITLE
Quel est la meilleur solution stable chaines iptv kodi ou autre Android box

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1281]
Salut, pas de lien direct avec vstream, mais selon vous quelle est la meilleur solution pour visionner les chaines TV de la façon la plus stable et sans lag avec ou sane kodi. Gratuite ou payante .
Merci de vos retours 
Mika

**Comment by LordVenom** [comment]
vStream

**Comment by kikikodi** [comment]
Bien vu, mais télé du web peopose un conte u limite et les bêta ajoutés récemment, sont certes excrément étoffé en nombre mais pour s'y retrouver c'est le parcours du combattant , entre le chargement des milliers de chaînes et Troy er celles qui fonctionnent. Enfin c'est déjà énorme comme boulot, bravo à vous

**Comment by LordVenom** [comment]
Lol je voulais dire par la qu'ici c'est vStream. Tu n'a pas la derniere version maintenant y a un classement alphabetique pour la tv et la radio.

**Comment by TmpName** [comment]
Par IP ?
Car tu peux aussi installer un bete tuner TV sur ta machine.
Netflix ?
