### ISSUE TITLE
Problème source VotreCompteUptobox

### ISSUE THREAD

**Issue by Atomium25** [Kodi-vStream/venom-xbmc-addons#1286]
Depuis aujourd'hui, il m'est impossible de rentrer dans mon compte Uptobox depuis Vstream, il y'a la petite roue de chargement en bas à droite qui apparaît, mais je n'arrive pas au menu avec le choix Mes Dossier / Mes Fichiers ...
Je ne sais pas si je suis le seul touché par ce problème, en tout cas le fait d'avoir accès à notre compte Uptobox était vraiment très pratique, notamment pour les Premium, si vous pouviez jeter un petit coup d'oeil :)

Merci d'avance les mecs !

**Comment by johngf** [comment]
il y a eu une modif https://github.com/Kodi-vStream/venom-xbmc-addons/commit/56294ff0f6e930ad715ecf6ef99d85b0efaa2742 sans faire attention au conséquence donc du coup c'est hs

**Comment by Atomium25** [comment]
Tu veux dire par là que ce ne sera plus jamais disponible ?

**Comment by johngf** [comment]
Si quand ça sera corrigé

**Comment by Atomium25** [comment]
Ah d'accord, et bien merci beaucoup pour ces réponses, j'espère que cela pourra rapidement revenir à la normale alors ;)

**Comment by TmpName** [comment]
Merde c'est ma faute.
Je corrige de suite.

**Comment by Atomium25** [comment]
Fait moi signe dès que c'est fait alors, que je puisse forcer la MàJ des 3 jours et de nouveau avoir accès à mes 7To de séries stockées sur mon compte :-)

**Comment by TmpName** [comment]
C'est bon tu peux y aller.
Tu risques d'avoir un bug a ta premiere connexion (mais la, ma boulette va devoir attendre la prochaine grosse maj), mais au second essais tout va repartir.

**Comment by Atomium25** [comment]
C'est bon, apparemment ça refonctionne ! Je donnerai des nouvelles ici en cas de problème ..

En tout cas un grand merci ! ;-)
