### ISSUE TITLE
Petit bug source zone telechar _gment.ws

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#1292]
Bonjour à tous,

Je viens de remarqué un truc bizarre ou bug ( à vous de voir lol). Tout d'abord je sais pas si vous le savez mais pour faire une recherche global sur cette source il faut au moins 4 caractères pour faire une recherche sinon ça marche pas et pas faire de faute d'orthographe dans la recherche.

Autre chose et c'est là que c'est bizarre car ça marche sur le site c'est quand tu cliques sur la rubrique dessins-animes rien ne s'affiche mais par contre sur le site ça marche vous avez le même soucis que moi?

**Comment by Arias800** [comment]
Bonjour pour ce qui est de la recherche global le site lui-même est buggé au niveau de la recherche et impose les 4 caractères donc le probleme ne vient pas du script (sauf erreur de ma parts)

**Comment by TmpName** [comment]
Ca a du etre corrige, car ca tourne chez moi. Re-testes pr voir.

**Comment by Arias800** [comment]
Ne fonctionne pas cher moi

**Comment by TmpName** [comment]
"toute les sources"  "ZT.WS"  "Dessisn animes" et c'est vide chez toi ?
Tu as recement eu la maj auto ?

**Comment by Arias800** [comment]
Oui c'est vide et je vient de mettre a jour la source via le github toujours pareil ^^

**Comment by TmpName** [comment]
Ok, c'est bon je viens de voir, c'est aleatoire, parfois ca affiche une autre mise en page, mais alors pkoi ?

**Comment by TmpName** [comment]
Bon alors, si tu peux tester ligne 28 remplace http par https.
Ne me demande pas pkoi ca fait ca, mais la ca a l'air de marcher, par contre pas sur pour les villes version  de kodi.

**Comment by Arias800** [comment]
Ok ça remarche tu t'occupe de mettre a jour le fichier ?ou je le fait ?

**Comment by TmpName** [comment]
j'ai mit le fichier a jours, mais pas en MAJ auto, juste pr les DA ca attendre la prochaine.

**Comment by johngf** [comment]
@Arias800 si t'est motivé il y a i anime qui déconne niveau hoster

**Comment by Arias800** [comment]
@johngf ok je peux regarde mais je garanti rien ^^

**Comment by TmpName** [comment]
Je viens d'y jeter un eouil, y a du taff ^^, plus rien qui tourne.

**Comment by Arias800** [comment]
Oui je confirme c'est le bazar x)

**Comment by Arias800** [comment]
Mais comment c'est possible de décrypte les host ?

**Comment by TmpName** [comment]
J'y suis pas encore, la je repare les genres/vf/vostfr mais si tu page commence par javascript et qu'il n'y a que du code en %12%78 c'est le meme codage que moi.

**Comment by Arias800** [comment]
non il y a des truc comme ça ('est un exemple mais ça change presque a chaque caractère) %3c%69%66%72%61%6d

**Comment by TmpName** [comment]
J'ai mis ma modif en place, la je regarde les hosters.

**Comment by Arias800** [comment]
Parce que la ça dépasse mes maigre connaissance ^^

**Comment by TmpName** [comment]
C'est bien la meme methode, rien de mechant, mais me faut rajouter la nouvelle methode sans desativer l'ancienne.

**Comment by TmpName** [comment]
Nouvelle version en ligne a tester.
