### ISSUE TITLE
La mémoire vive ou Ram change elle la rapidité d'utilisation de vstream ou non?

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1300]
J'ai fais acquisition d'une box TV Android avec 1go de Ram, la meme existe avec 2go de ram 
Cela changera quelquechose ou non ? 
Ou achat inutile ? 
Merci à bous

**Comment by kikikodi** [comment]
Merci à vous plutôt 😉

**Comment by johngf** [comment]
honnêtement toutes ces box android c'est de la camelote 
- le plus important c'est la puissance du cpu
- pour la ram tout dépend du systeme installé mais c'est mieux 2 go

**Comment by kikikodi** [comment]
Salut 
Je vais ou pour voir cela ? 
De quoi tu parles quand tu dis combien de mémoire ça utilise ? 
Aussi la question qu je me posait était de savoir, qu'aujourdhui elle est en Android 5.1 que le la version 6 existe, y aura t il un moment où ma box en android 5.1 avec 1 go de ram sera en rad par exemple quand la version leia 18 de kodi sortira ? 
Bon après c'est sûre que ce n'est pas un matériel de fou, mais ça fait vraiment l'affaire pour lancer kodi ou application android sur TV.

**Comment by kikikodi** [comment]
Ouai merci à vous, mais a 2 h du matin j'étais à bout 😜

**Comment by LordVenom** [comment]
Les box android sont bien jolie mais pas mal de soucis pour lire des gros fichiers Stream et des codecs audio un peux bizarre.

Les raspberry pareil lire des gros fichier stream il ont du mal peux être pas le 3 pas eux de retour.

Aprés ça depend de ce que tu fait avec pour avoir netfix et quelque logiciel sympas c'est bien une box mais pour juste lancer XBMC bof bof perso j'ai choisis pour un vrais HTCP je peux y mettre un OS sans soucis mais je m'en sert pas donc j'ai mis openElect et ça lance juste Kodi.

**Comment by johngf** [comment]
le probleme aussi sur ce genre de matos c'est la bande passante est partagé entre internet, les ports usb, et la lecture écriture sur disque >> donc pour la performance faut oublié

**Comment by kikikodi** [comment]
Oui mais a part ouvrir kodi et une ou deux app de stream a la façon Netflix je ne ne sert pas à autre chose à part ça, et c'est d'ailleurs ce que je cherchais

**Comment by TmpName** [comment]
Pr la difference de prix prend la  2 G, mais sinon comme tu le dis en plus des prb de performance cite par @johngf tu aura vite des probleme de version de OS.
Ca bouge tres vite et ces systemes sont rarement a jour, si tu vois un user bloque sur kodi V16 tu peux etre sur a 100% qu'il est sur android.

**Comment by Kodigoal** [comment]
En même temps changer de box android tous les 2  ans au pire , ca coute 30-35e.
Acheter la rolls nVidia shield pour être tranquille 3-4 ans pêtre, voir plus  , pas le même prix mais niveau perfomance et maj nVidia suivie, c'est le top.
1go /2go ram pour matter du stream , ca ne changera rien.
2go pêtre interface kodi plus fluide , tout dépendra du proc dans la box aussi.
Plutôt miser sur une box avec suivie maj android ou communauté dev qui propose maj custom, mais comme dit avant vu le prix , c'est du jetable lol
Kodi leia = lollipop android 5 comme kodi17  ..
Le jour ou il faudra android6 mini , et que ta box fait plus l'affaire ,  direction la poubelle ou revente à 10e.

**Comment by kikikodi** [comment]
La box est deja sous Android 6, à ce sujet vous avez des infos concrète sur la date de sortie de kodi 18 leia, et les améliorations apportées ?

**Comment by kikikodi** [comment]
Et puis en même temps 30€ la box ça va pas chercher loin et remplie amplement le job

**Comment by Arias800** [comment]
pour les amélioration apporté l’équipe de kodi ont créer une vidéo spécial : https://www.youtube.com/watch?time_continue=130&v=SrL3EDY3Pyk

**Comment by johngf** [comment]
ils devraient en faire une sur les trucs qu'ils ont empiré par rapport aux anciennes versions

**Comment by TmpName** [comment]
XD.
C'est clair que plutot que de rajouter des fonctions qui vont jamais servir, (quelqu'un a utilise une des nouvelles fonctions de la V17 ? ) Feraient mieux de garder leur appli a jours tout simplement.

**Comment by Arias800** [comment]
Ah la v17 a des "ajout" a parts le thème dégueulasse 
x)

**Comment by kikikodi** [comment]
D'ailleurs quel est le thème que vous trouvez le plus sympa pour kodi ?

**Comment by Arias800** [comment]
le thème de kodi 16 (j'ai oublié son nom)

**Comment by kikikodi** [comment]
Confluence ?  
Je pense que c'est l'habitude ... Notre nous il est degueulasse celui la , moi j'aime plutôt bien estuary, apres il en existe des tas justement je voulais vos avis

**Comment by kikikodi** [comment]
"Entre nous"

**Comment by johngf** [comment]
+ 1 confluence moins buggé , meilleur affichage par défaut

**Comment by TmpName** [comment]
Confluence aussi.
Moins de bug
Plus d'infos utiles affiche a l'ecran d'acceuil.
Moins de manip a faire pr acceder a ce que je veux.
Meilleure occupation de l'ecran, plus de texte utile affiche.

**Comment by kikikodi** [comment]
Bon bein franchement la 2g change littéralement , kodi est plus fluide et répond plus vite donc la mémoire vive joue un sacrée rôle ...

**Comment by TmpName** [comment]
Moi a 2 grammes, y a tout qui va plus vite aussi, ou alors c'est peut etre moi qui tourne au ralenti.

**Comment by kikikodi** [comment]
LOL

**Comment by Kodigoal** [comment]
A 2 grammes, on recommande estuary sans hésiter xD

**Comment by TmpName** [comment]
Yep et avec Win 10 emule sous un systeme linux.
