### ISSUE TITLE
Je n'arrive pas à trouver de films avec Vstream et cela même après 45 mn de recherche

### ISSUE THREAD

**Issue by Narmo70** [Kodi-vStream/venom-xbmc-addons#1325]
Bonjour à tous,

Je ne sais pas trop si je suis au bon endroit pour poster et m'en excuse par avance!

Je suis un nouvel utilisateur de kodi que depuis environ 2 mois et aussi de Vstream mais j'ai un souci d'utilisation!
Je m'en sers avec une box android mais j'ai le même souci avec mon pc sous windows 10

Je n'arrive pas à trouver de sources viables et donc de films avec Vstream. Il m'a fallu encore hier plus de 45 minutes de recherche pour avoir un film avec une qualité d'image très basse.
En fait à chaque fois que je clique sur une source, j'ai un message qui me dit "résolve" et ensuite "que le fichier est introuvable" ou alors " échec de lecture d'un ou plusieurs fichiers".
Par contre à chaque fois que j'avais la source google vidéo, j'ai eu quasiment un film sans aucun souci.

Est ce que cela vient d'une mauvaise utilisation de Vstream, de ma connexion internet qui n'est pas énorme ( 4 Mb )mais je peux regarder la tv par internet ou en streaming avec Amazon Prime et Exodus?
Pour information, je n'ai aucun souci pour trouver et visionner un film et cela en quelques minutes, avec l'addon Exodus (pas le fr).

Kodi 17 est à jour en tout cas depuis le google play et Vstream est à jour aussi 0.5.2
J'ai bien mis à jour vstream depuis le menu déroulant en bas et mis aussi à jour la liste de liens à nettoyer dans télécharger.

Autre chose c'est que quand je cherche un film, et que j'ai ces messages d'erreures, si je reviens sur le même lien, vstream me propose de reprendre ma lecteur à un moment précis du film comme si j'avais commencé à le visionner alors que je n'ai vu aucune image!
Et à chaque recherche, j'ai la roue qui tourn après le resolve puis j'ai ensuite le symbole de lecture qui s'affiche en petit en haut à droite de l'écran avant que j'ai ces messages d'erreures.

J'ai aussi augmenté le timeout et le speedtime à environ 60 pour laisser le temps mais toujours rien.(seulement fait pour ma box et non pour mon pc!)

J'aurais bien voulu vous mettre un lien mon log d'erreur mais je n'ai pas réussi à retrouver le fichier sur ma box android!!
Par contre voici ce que cela donne depuis mon pc où j'ai le même souci de recerche:
http://www.cjoint.com/c/GEhp3fSU1qE

Pourriez vous m'aider ?
Un grand merci d'avance pour votre réponse et aide.

**Comment by TmpName** [comment]
Tes autres addons fonctionnent bien ?
Pr uptobx : les liens sont morts.
Pr allvid/Youwtc/exshar : Ca a bien marche mais c'est ton systeme qui bloque.
Tu as kodi qui cherche la video combien de temps avant de t 'afficher le message d'erreur ? (y a un machin qui tourne et tout est bloque pendant ce temps)

**Comment by TmpName** [comment]
Bon alors deja bravo pr le post, c'est la premiere fois que quelqu'un expose son probleme aussi clairement. Par contre j'attend l'avis des autres, moi j'ai rien vu de flagrant.
Par contre si tu pouvais avtiver les logs a fond, pour avoir plus de detail, car la je vois pas trop pkoi ca deconne chez toi, Systeme/journalisation/activer .... specifique composant (en prennant libccurl/ffmepg/video comme composants a afficher)

**Comment by Narmo70** [comment]
Merci pour ton aide et aussi pour ta remarque sur mon post!

Je suis tout bête car je n'arrive plus à retrouver comme j'avais trouvé les log sur mon pc qui tourne sous windows 10 et je ne trouve pas d'info pour le faire sur le net!

Par contre est ce que tu pourrais me dire comme le faire que ce soit sur pc et sur android car comme j'ai ce souci sur mes 2 appareils.
Mais que je souhaite faire ces tests sur mon android car c'est avec ça que je voudrais utiliser vstream?

Merci d'avance

**Comment by Kodigoal** [comment]
Pour localiser kodi.log selon l'os:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log
ou plus simplement via les paramétres dans vStream Onglet Outils  - upload log et donner ici l'id affiché en popup
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by Narmo70** [comment]
Encore merci pour ton aide!

Alors avoir le temps avant le message c'est environ 25 secondes!

alors pour le log, je n'y arrive pas, j'ai bien trouvé l chemin pour android mais je n'ai qu'un vieux log et je n'arrive pas à en créer un nouveau!!

**Comment by TmpName** [comment]
A chaque fermeture de kodi le log repart a zero, donc c'est frcement un neuf.

**Comment by Narmo70** [comment]
ah ok alors je fais cela de suite enfin j'espère!!!!

**Comment by Narmo70** [comment]
Je n'arrive pas à utiliser l'addon up loader pour envoyer le log !
Et je ne trouve as de tuto avec kodi 17.1!

**Comment by Kodigoal** [comment]
? dans les paramêtres de vStream , cliquez sur upload log , et si ok une popup s'affichera avec un id à nous donner ici:

![foto_no_exif 4](https://cloud.githubusercontent.com/assets/16567960/25784998/d2047616-3376-11e7-8a8d-d19cf90dd04b.jpg)

**Comment by Narmo70** [comment]
Je suis vraiment désolé mais j'ai bien trouvé dans vstream  le upload kodilog quand je clique dessus on me demande "êtes vous sûr?" je clique oui qui est à gauche mais après rien ne se passe!

**Comment by Narmo70** [comment]
J'ai enfin pu avoir ce log en passant pas mon nas!
J'ai eu du mal mais le souci est que maintenant le mise en page pour la lecture di log est complètement changée!
j'espère que cela ira quand même et si besoin je peux refaire mais je n'y arrive toujours pas avec upload de vstream!
et je n'ai pas trouvé d'autre moyen que de le mettre directement dans le post suivant!!!
Désolé

**Comment by Narmo70** [comment]
J'ai enfin pu avoir ce log en passant pas mon nas!
J'ai eu du mal mais le souci est que maintenant le mise en page pour la lecture di log est complètement changée!
j'espère que cela ira quand même et si besoin je peux refaire mais je n'y arrive toujours pas avec upload de vstream!
et je n'ai pas trouvé d'autre moyen que de le mettre directement dans le post suivant!!!
Désolé

**Comment by Narmo70** [comment]
J'ai enfin pu avoir ce log en passant pas mon nas!
J'ai eu du mal mais le souci est que maintenant le mise en page pour la lecture di log est complètement changée!
j'espère que cela ira quand même et si besoin je peux refaire mais je n'y arrive toujours pas avec upload de vstream!
et je n'ai pas trouvé d'autre moyen que de le mettre directement dans le post suivant!!!

**Comment by Narmo70** [comment]
Je suis vraiment désolé mais j'ai bien trouvé dans vstream le upload kodilog quand je clique dessus on me demande "êtes vous sûr?" je clique oui qui est à gauche mais après rien ne se passe!
Là je sèche complètement!!!

**Comment by Narmo70** [comment]
Bon avant le dodo, je reviens avec un autre essai que j'ai fait avec mon pc avec lequel j'ai les mêmes soucis!
J'ai fait les mêmes manipulations et recherches qu'avec ma box android et j'ai eu les mêmes résultats!

Par contre là j'ai bien eu un message qui m'a donné un code après avec demandé le log depuis vstream!
Le voici:
s206AWGEmC

En espérant que cela aide!

**Comment by Narmo70** [comment]
Autre chose je n'arrive pas depuis un navigateur et sur différents pc depuis chez moi accéder à allvid.ch et youwatch.org!
je suis chez free avec une freeebox revolution, peut être qu'elle est mal configurée?

**Comment by TmpName** [comment]
Tu pourrais pas faire passer le log via cjoint stp comme tu faisais au debut, la mise en ligne via les outils de vstream deconne completement, ca coupe avant la fin, en plus de parfois de pas envoyer le log du tout.

Sinon c'est bon y a plus d'info ffmeg et ccurl. Mais si tu ne peux pas via navigateur, je pense que tu as trouve le prb tout seul. Les videos peuvent mettre 1mn a se lancer, donc kodi lui stoppe tout, mais si sur navigateur ca ne marche pas non plus la c'est inquietant.

**Comment by johngf** [comment]
changer de dns peut etre >>> open dns

**Comment by TmpName** [comment]
Je savais que free avait tendance a brider mais carrement bloquer ?  y a personne d'autre sur free qui aurait ce probleme ?

**Comment by LordVenom** [comment]
Pas de soucis chez Free mais leur DNS pue du cul je suis sur open dns

**Comment by Narmo70** [comment]
OK, 
Je vais essayer de refaire un test avec un log car le dernier fait environ 50 mb et sur ci-joint on ne peut mettre que 15mb.

Autrement je peux faire un copier coller mais la mise en page est catastrophique, tout le texte est enchaîné ! 

Par contre pour l'histoire du dns je n'ai pas compris ! 
Est-ce que je peux modifier cela avec ma box révolutionnaire ?

**Comment by Arias800** [comment]
Bonjour Narmo70,
Opendns a l'air gratuit car c'est financer par la version payante (la version entreprise) même si je te demanderai d'attendre la confirmation des autre ^^(pour pas que je te dise une bêtise)

**Comment by johngf** [comment]
c'est gratuit open >> ouvert

**Comment by Arias800** [comment]
"ffmpeg[1E70]: [mov,mp4,m4a,3gp,3g2,mj2] error reading header" ça peut venir de cette erreur le problème non ? (premier log)

**Comment by Narmo70** [comment]
Merci pour vos réponses!
je viens de changer les 2 adresses ip dans free mais est ce qu'il faut un compte opendns pour que cela fonctionne?
Pour le test voici ce que cela donne:
Download 3.5 mpbs
upload 0.85 mpbs
et le ping 21ms

Ce n'est pas bien gros comme débit mais normalement dans les jours qui viennent je devrais passer d"une distance de 5 kms à 1640 mètres entre chez moi et le nra avec un affaiblissement de 20 db au lieu de 60 actuellement et donc potentiellement 16 mb de débit

**Comment by johngf** [comment]
pas besoin de compte maintenant va sur https://www.opendns.com/welcome/
si c'est bien configuré il doit etre ecrit 
Your Internet is safer, faster, and smarter
because you’re using OpenDNS.
Thank you!

**Comment by Narmo70** [comment]
oui j'ai bien ce message!
par contre j'ai toujours le même souci !
voici le log mais j'ai été obligé de le mettre directement dans le post suivant car avec ci-joint je ne peux pas mettre plus de 15 mo et le log fait 49 mo!

**Comment by johngf** [comment]
@TmpName j'ai aussi l'erreur 'DIALOG2' is used prior to global declaration
dans le log j'en avais parlé il y a longtemps

**Comment by Narmo70** [comment]
oui j'ai bien ce message!

par contre j'ai toujours le même souci !
j'essaye de mettre le log sur le forum mais il fait 50 mo et je n'arrive pas à le mettre avec ci-joint et même en coipé collé directement sur ce post

**Comment by johngf** [comment]
va sur pastebin.com

**Comment by Narmo70** [comment]
alors voici le log depuis Drive mais en format zip car j'ai vraiment du mal à le mettre sur le forum!
avec pastebin cela fait planter mon navigateur mozilla!
https://drive.google.com/file/d/0B-CdPGYleI_qUU1ZbmdCVkJXVTA/view?usp=sharing

je suis en train de faire aussiavec drive mais avec le log non compressé!

**Comment by TmpName** [comment]
@Arias800 c'est possible, vu que dans 1 cas sur 2 le message d'erreur est precede de l'erreur de lecteure des headers, mais pkoi il ne peut pas lire les headers ....
Vu que kodi est code a la truelle ca peut venir de la connexion, des codecs, de la temperature de la piece, et tu auras tjours le meme message. C'est pour ca que j'ai demande un log plus complet.

Sinon pr baisser la taille, ce que je fais, je lance Vstream, je repasse sur l acceuil, active les logs et reviens sur Vstream, ca limite les lignes de debug. Par ce que 50M j'ai jamais vu ca ^^, je sais meme pas si vais arriver a le lire.

**Comment by Narmo70** [comment]
je vais refaire un log avec tes conseils!

**Comment by Arias800** [comment]
En fait dans les log il y cette ligne "13:26:01.308 T:2752   DEBUG: ffmpeg[AC0]: [mov,mp4,m4a,3gp,3g2,mj2] sample_count=1, sample_duration=656" un nombre incalculable de fois

**Comment by TmpName** [comment]
Pas besoin @Narmo70 il est parfait ce lui la.

**Comment by Narmo70** [comment]
ok et est ce que cela peut aider à trouver ce qu'il ne va pas et pourquoi je n'ai quasiment pas de films?

**Comment by TmpName** [comment]
Alors la par contre j'ai pas de bne nouvelles, je ne vois aucun probleme dedans , pas de timeout non plus.
Tu pourrais tester avec une config de kodi vierge, pour voir si ca ne vient pas du systeme, mais dans tout les cas si ca ne marche pas sur navigateur, c'est mort pr kodi.
Quand tu dis que ca ne marche pas sur navigateur, il se passe quoi, ca tourne dans le vide ou message d'erreur ?

`J'ai aussi augmenté le timeout et le speedtime à environ 60` 
Tu as fait comment, je ne vois aucun fichier advancedSetting ? Tu as utilise un addon pr tes reglages ?

**Comment by TmpName** [comment]
@johngf 
global DIALOG2 ne devrait pas etre au debut (4 lignes plus haut) ?

**Comment by Narmo70** [comment]
ah!

alors pour le navigateur avec mozilla sur mon pc j'ai ce message:
La connexion a été réinitialisée

La connexion avec le serveur a été réinitialisée pendant le chargement de la page.

    Le site est peut-être temporairement indisponible ou surchargé. Réessayez plus tard ;
    Si vous n’arrivez à naviguer sur aucun site, vérifiez la connexion au réseau de votre ordinateur ;
    Si votre ordinateur ou votre réseau est protégé par un pare-feu ou un proxy, assurez-vous que Firefox est autorisé à accéder au Web.

Mais avec allvid.ch sur microsoft edge cela fonctionne!

Ensuite pour une nouvelle installation, cela que j'utilise pour le test est toute nouvelle d'hier sur mon pc donc je pense qu'elle est bonne!


Pour le réglage du timeout, j'ai utilisé un addon mais c'est vrai que c'était sur ma box android et non sur le pc!
Je vais faire le test sur pc avec cet addon!

**Comment by TmpName** [comment]
Exact, dsl, instal clean, pas vu d'addon en plus.
Message d'erreur sur cette page ? http://youwatch.org/

**Comment by johngf** [comment]
C'est pas une bonne idée d'utiliser un addon qui modifie ta config

**Comment by Narmo70** [comment]
C'est vrai que je n'ai pas été clair, c'est avec allvid.ch que j'ai le message d'erreur dans mozilla mais pas dans edge.
Par contre hier il me semble qu'avec youwatch.og j'avais aussi un message d'erreur mais aujourd'hui cela fonctionne!

Alors je viens de refaire le test avec cet addon!
Rien n'a changé et je suis entre 25 à 33 secondes de recherche avant le message!
voici quand même le log:
https://drive.google.com/file/d/0B-CdPGYleI_qaFJYX2JGd2JiLW8/view?usp=sharing


Ensuite pour la bonne idée d'utiliser un addon qui modifie la configuration j'avais ce souci avant de l'utiliser et à partir d'une installation de kodi neuve et je pense correcte!

**Comment by Narmo70** [comment]
Est ce que cela peut venir de ma box freebox revolution qui est mal configurée?
Car je ne vois pas pourquoi j'ai le même souci sur différents appareils?

**Comment by Arias800** [comment]
Question qui peux paraître bête tu est connaitre a internet en wifi ?

**Comment by Narmo70** [comment]
alors avec ma box je suis en ethernet mais avec mon pc je suis en wifi!

je vais refaire un essai en éthernet avec le pc!

**Comment by Arias800** [comment]
Parce que je me suis dit qu'il y avais peut être quelque chose qui faisait obstacle a la wifi mais si tu est en ethernet alors c'est autre chose :/

**Comment by Narmo70** [comment]
je aussi le même souci avec mon téléphone android!

Donc cela vient de ma connexion mais je ne sais pas pourquoi, si vous aviez une idée!!!

**Comment by Arias800** [comment]
éteint et rallume la peut être que ca peut aider

**Comment by johngf** [comment]
@TmpName pour l'erreur re installe la beta en remplaçant le dossier plugin video vstream par celui de la beta au premier démarrage tu l'auras dans le log

**Comment by Narmo70** [comment]
Je viens encore sans succès!
par contre ce que je ne comprends pas c'est qu'avec exodus je trouve sans aucun souci des films mais en version originale!!

**Comment by Arias800** [comment]
La je sais pas je tombe a cours d’idée :/

**Comment by Narmo70** [comment]
Je comprends!
Merci beaucoup en tout cas de ton aide en espérant que d'autres pourront m'aider!

**Comment by Arias800** [comment]
De rien et moi aussi j’espère que d'autre personne pourront résoudre le problème ^^

**Comment by Narmo70** [comment]
Si des fois le concepteur passait par là..............
Sait on jamais!?

**Comment by johngf** [comment]
exodus est addon anglais normal c'est de la vo
le soucis viens de chez toi pour vstream reste a le trouvé

**Comment by Narmo70** [comment]
Ce que je veux dire c'est que je trouve de suite un film avec exodus!
par exemple le film "split", pas de souci avec exodus, introuvable avec vstream.

**Comment by johngf** [comment]
il est partout le film tu ne sais pas cherché correctement ou ton install a un souci

**Comment by TmpName** [comment]
@johngf a tester, suis pas assez cale en python pr dire si cette modif va chnager quelque chose ou pas. Et la j'ai plus acces a la machine, donc te dirait demain pr clouyd.

@Narmo70 pas de soucis, ton install est clean (enfin de visu) . Pour exodus ca peux venir des hebergeurs etranger, si tu essayes une video sur youwatch ca ne devrait pas marcher non plus. Sachant que sur exodus, ca ne sert a rien de choisir l'hebergeur, en cas d'erreur (et tres rapidement) il en resteste un suivant, donc sans voir les logs c'est assez dur de savoir sur quel site tu regardes ta video. Pour info il y a une version de exodus en fr avec sources FR.Tu peux tester avec VoirFilm ("toute les sources"/"voirfilm"/"nouveautee"), c'est celui qui propose le plus d'hebergeurs (ne tu/clouyd en cours de reparation).

Par contre si meme la recherche deconne (pas de resultat de recherche pr split ??) esssayes de te connecter directement sur le site de Str ae ming via navigateur, pour voir si c'est pas bloque aussi chez toi.

**Comment by Kodigoal** [comment]
![foto_no_exif 7](https://cloud.githubusercontent.com/assets/16567960/25813993/08ede914-341c-11e7-8861-9a13084aa425.jpg)
![foto_no_exif 9](https://cloud.githubusercontent.com/assets/16567960/25814116/9002a43a-341c-11e7-9530-0d538bc3e205.jpg)

Kepliz valeur sur ! 
Planetstreaming 
perso j'utilise que ddl-island ( via uptostream ou direct uptobox) avec un compte uptobox gratuit ( à rentrer dans les paramètres de vStream.
720p son 5.1 via uptobox en compte gratuit , si pas heure de pointe ca passe si bon débit.
Sinon je passe plus  via uptostream 720p son normal.
split 30sec recherche  ... 
Je passe directement par mes 2-3 sites favoris pour voir les  nouveautés , la recherche me sert juste pour des anciennes séries/ films..
Et ton soucis vient pas de vStream , si t'arrive pas à aller sur allvid ou youwatch  sauf via edge ,  si t'as bien changer les dns ( à vérifier dans les config tcpip des pc /box si le dhcp de la box a bien aloué les dns openDns ) , à part un bloqueur pub / antivirus ou autre fonction coché dans la config freebox .. je vois pourquoi via Firefox t'arrive pas à aller sur allvid...

**Comment by Narmo70** [comment]
johngf:
cela peut être fort probable que je fasse une erreur de manipulation pour la recherche!

Par contre je ne comprends pas bien comment tu as fait!
Quand j'ouvre vstream, menu déroulant je prends toutes les sources mais après comment je dois faire pour avoir le même résultat que toi?

Merci pour ton aide!

Alors peut être que mes choix de sources dans vstream ne sont pas bons!
Est ce qu'il y a une aide pour cela?

**Comment by TmpName** [comment]
Effectivement je vois le reglage du timeout sur le nouveau log, ca ne fera rien buggue mais c'est plus valide ^^.
CF http://kodi.wiki/view/Advancedsettings.xml#network

> Note: In Kodi v17, the three buffer settings are removed from the <network> tag and now placed under the new <cache> tag. See #cache for full details.

Et l'addon les met encore en network.

**Comment by TmpName** [comment]
Quand tu ouvres Vstream, page d'acceuil, "rechercher" "film", par defaut.

**Comment by Narmo70** [comment]
Ok je viens de le faire ce qui me donne plein de possibilité mais quoi prendre ensuite, comment on fait un choix judicieux!!?

**Comment by johngf** [comment]
bah tu fait comme nous tu clic si le liens est hs tu retourne en arrière tu clic sur un autre

**Comment by Narmo70** [comment]
je ne sais pas, je ne suis peut être pas doué tout simplement!!!
Je me doute bien que je dois cliquer sur les liens et chercher jusqu'à trouver, mon souci était justement de trouver après avoir cliqué pendant longtemps!!!

**Comment by johngf** [comment]
sinon sur you tube il y a des exemple de fonctionnement

**Comment by Narmo70** [comment]
je vais regarder là aussi!

**Comment by Narmo70** [comment]
peut être qu'il faut aussi que j'utilise de bonnes sources

Donc j'ai tout enlevé et mis comme proposé plus haut 
kepliz
planetstreaming

si vous en avez d'autres?

**Comment by TmpName** [comment]
Ben moi perso, je m'inquieterais pr les autres, c'est pas normal que youwtch ou allvd ne marchent pas du tout meme sur navigateur. Planetstrm propose aussi ces 2 hebergeurs.

Tu as pas essaye de regarder la config de ta box ? Un antivirus qui t'aurait modifier le fichier host de windows ...? Des voisins qui seraient sous free et qui aurait les memes problemes ?

**Comment by johngf** [comment]
Fait ton propre choix explore les sites et les fonctions tu finiras par te familiarisé

**Comment by Arias800** [comment]
Les anti-virus ont pas les droit de modifier le fichier host il me semble ^^

**Comment by TmpName** [comment]
Je pense qu'ils bloquent eux meme l'accés au fichier par securite, mais j'ai deja eu des applis qui me l'ont modifie (et pas des virus ^^ au contraire). Mais si il passe par openDNS, ce fichier n'est plus utilise normalement.

**Comment by Kodigoal** [comment]
et en partage 4G wifi en  connectant box dessus ou pc  , ca fonctionne ?

**Comment by Narmo70** [comment]
Est ce que le fait que je ne puisse pas accéder à youwatch.org et allvid.ch avec firefox mais je le peux avec edge, peut créer des soucis à kodi ou vstream?

Kidogoal: je n'ai pas compris ta demande !?

**Comment by Kodigoal** [comment]
@Narmo70  pêtre pêtre pas mais c'est pas normal , ou ya une extention activée dans firefox qui bloque ses 2 sites.
Si t'as un télephone avec  un forfait data 3g/4g inclus , tu actives la 3g/4g , tu partages la connection ( en wifi) et tu connectes un pc dessus ( sur le wifi créé par partage 3g  du tel) et tu testes si ca fonctionne mieux.
Comme ca tu peux voir si ca vient de la freebox ou non ou ton firefox ou autre ..

**Comment by Narmo70** [comment]
Pour le blocage j'ai aussi essayé avec un autre pc de la maison mais avec opéra et cela bloque aussi!!!
J'avais des extentions mais je les ai désactivées!

Je n'ai pas de gros forfait data sur mon portable et chez moi, la data ne passe pas bien!
Je peux essayer demain ailleurs pour voir si cela vient de la box .

**Comment by Kodigoal** [comment]
Oui essaye de tester ailleurs mais avec par ex un pc portable ( si tu as ca en stock)  qui pose soucis via la freebox , pour être fixer si ca vient bien que de la freebox et éliminé des soucis de config sur box android/pc fixe ou portable.

**Comment by Narmo70** [comment]
Je vais prendre mon pc que j'utilise actuellement et je ferai le test!

PAr ce que là je ne vois pas pourquoi avec opéra et firefox je ne peux pas aller sur des sites alors que edge sans souci!

**Comment by Narmo70** [comment]
Autre précision qui peut peut-être aider, depuis chez moi en Wi-Fi sur ma box, je peux accéder aux 2 sites avec mon navigateur Firefox Android

**Comment by Arias800** [comment]
Sur l'ordinateur ou tu a firefox a tu windows ?Si oui est -il un 32 ou un 64 bit ? A tu bien la bonne version de firefox (32 ou 64)

**Comment by Narmo70** [comment]
Alors mon pc tourne en 64 et mozilla est en 32!
Cela peut venir de ça?
Car en installant firefox j'ai installé sans rien changer dans les paramètres d'installation!

**Comment by Arias800** [comment]
Peut être que ça peut en être la cause car edge est de base preinstaller donc déjà dans la bonne version
petit aide pour firefox 64 bit :https://support.mozilla.org/fr/kb/passer-de-firefox-pour-32-bits-a-64

**Comment by johngf** [comment]
Non tu t'egare la n'importe quel logiciel 32 bit peut tourné sur un systeme 64
Regarde du coté de ta box ou parfeu

**Comment by Arias800** [comment]
oui mais un logiciel 32 bit sur 64 bit est moins performant qu'un 64 sur 64 donc peut être que ^^

**Comment by johngf** [comment]
Non pas pour lire une video

**Comment by Arias800** [comment]
ok ^^ mais si c’était la box pourquoi ça fonctionnerai avec edge ? Ou avec firefox android ?

**Comment by johngf** [comment]
Apres ta tes gens qui ont des install completement pollué parce qu'ils installe n'importe quoi
Comme sur kodi avec super repo repo ceci cela des addons qui change la config au lieu de le faire a main

**Comment by Arias800** [comment]
Oui c'est vrai il y a ce cas aussi mais bon si c'est ça on peut rien y faire ^^

**Comment by johngf** [comment]
Apres windows 10 connait pas win7>linux>win10

**Comment by TmpName** [comment]
Lol, wé me souviens lors de mon dernier passage en enfer, satan tournait sous Win 10.

**Comment by TmpName** [comment]
Et il avait estuary sur son kodi.

**Comment by TmpName** [comment]
Sinon je me moque, mais suis degoute pr toi, autant sur linux ou android, je trouve ca normal, mais windows ....
J'espere vraiment que ca vient de ta box.

**Comment by Narmo70** [comment]
Bon alors, je crois que cela fonctionne!

J'ai complètement réinstallé ma box android en paramètrage d'usine, j'ai réinstallé kodi 17.1 avec vstream dernière version et la miracle, j'arrive à lire plein de sources même les allvid et youwatch!
Bien sûr il arrive que quelques fois j'ai encore le message qu'il manque des fichiers mais je peux trouver un film en quelques minutes au ieu de 45 mn et de plus la recherche après avoir cliqué sur film est beaucoup plus rapide!

Tout ce que j'espère c'est que j'ai fait mes tests ce midi et j'espère que ce soir cela fonctionnera aussi bien, je fais cette remarque par rapport au trafique sur les lignes adsl car elles sont sûrement plus sollicitées le soir que le midi (sauf erreur de ma part!).

En tout cas cela semble avoir réglé mon souci et repartant d'une installation d'usine car même en suppriment kodi avec cache t données cela n'avait rien changé!
J'ai du bidouiller quelque chose!!!!!!!!

Je vous tiens au courant après des essais de ce soir!

**Comment by Narmo70** [comment]
Pour ce qui est de l'accès depuis le navigateur j'ai aussi remis à zéro mon pc et rien n'a changé!
Là actuellement je suis sur un autre ligne adsl et j'ai le même souci sauf une fois j'ai pu avoir youwatch.org!

**Comment by TmpName** [comment]
Tu n'aurais pas choppe une salete ? spyware, adware ? Car avec kodi clean ca ne marche pas, mais si tu reinitialise le systeme ca repart ? Sans modif sur le reseau ....

**Comment by Narmo70** [comment]
je ne sais pas trop j'ai fait des analyses et rien de bien probant!

PAr contre ce qui m'intéresse surtout de pouvoir utitliser avec ma box android !

**Comment by Narmo70** [comment]
Alors après des tests que ce soit sur pc et box android tout semble correctement fonctionner!

J'ai du avoir des spyware ou autre, ou peut être une mauvaise manipulation à moment!
Je pense que mon souci sur la box (mauvaise manipulation ou installation) et sur le pc (virus et autre) n'était pas le même!

pour ce qui est du navigateur j'ai eu de l'aide du super site de zébulon et d'autres on le même souci que moi avec les sites et firefox suivant que l'on utilise l'ouverture des sites depuis la barre de navigation, écriture de l'adresse ou depuis la de de google!

En tout cas hier j'ai pu trouver pas mal de film en quelques minutes alors qu'il me fallait entre 30 à 45 mn et je n'ai plus de lague sauf sur une source!!!!

Je vous remercie tous de la rapidité à laquelle vous m'avez apporter de l'aide!

**Comment by TmpName** [comment]
Tant mieux pr toi, parce que la je declarais forfait pr moi.

**Comment by Narmo70** [comment]
Normal avec tout ce que tu as fait pour m'aider!
Fallait bien que tu sèches sur les idée!! ;-)
