### ISSUE TITLE
Pb sur hoster OK.RU

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#1333]
Bonjour @TmpName ,

Le hoster ok.ru ne fonctionne pas, il faut rajouter à la ligne 86 de ce hoster:

`sHtmlContent = cUtil().unescape(sHtmlContent)`

par

`sHtmlContent = cUtil().unescape(sHtmlContent.decode('utf-8'))`

Après ça marche :-),
Bonne journée

**Comment by TmpName** [comment]
Merci, je met en place de suite.
Par contre tu as le film/site ou ca a deconne ?

**Comment by johngf** [comment]
mais le probleme on va pas mettre des decode partout

**Comment by TmpName** [comment]
Lol, c'est clair que c'est la fete en ce moment, mais la c'est pas un probleme d'accent dans un repertoire, ca doit venir du code html, c'est pour ca que je demande la page pr tester.

**Comment by johngf** [comment]
apres le site ok deconne c'est peut a cause de ça

**Comment by TmpName** [comment]
Le replace c'est pas le top, trop de possiblitees, la chaine complete ferait plusieurs lignes. Et celui la ne marche que pr les valeurs chifrées, il gere pas le &quot;.
J'ai teste avec le decode(), ca tourne. J'attend sa reponse pr voir mais pour le moment rien n'est passe en MAJ auto, j'attend de voir si cloudy va repondre avant ce soir.
Netu remarche au fait, en fait kodi fait par rapport au nom du fichier, il est buggué sur le mimetype (comme pr le format gif des images). La je bataille avec leur support, un gag.

**Comment by johngf** [comment]
je viens de test avec replace c'est ok chez moi

**Comment by TmpName** [comment]
Ton replace gere tout ces cas http://www.freeformatter.com/html-entities.html ?

**Comment by johngf** [comment]
pas tout cela mais une bonne partie https://pastebin.com/raw/u8R85f0R

**Comment by johngf** [comment]
sinon le module htlmparser le fait aussi

**Comment by ttrd06** [comment]
salut à tous,
désolé pour la réponse, j'étais au taf à l'étranger donc pas le temps de vous répondre.
@TmpName : c'était pour tous les films en hoster ok.ru ...?
@johngf : le `#-- coding: utf-8 --` je connais et je l'avais déja mis pour voir si ça faisait qq chose.
en mettant le `sHtmlContent.decode('utf-8')` le problème était résolu.

A part ça, youwatch et allvid ne fonctionnent plus, il y a ce message d'erreur pour youwatch:

Can't connect to Mysql server. at Modules/DataBase.pm line 75.

For help, please send mail to this site's webmaster, giving this error message and the time and date of the error. 

et pour allvid un pb de dns (site down) ?

**Comment by TmpName** [comment]
Yep, pr allvid ca fait un petit moment, a surveiller.
Pr ok.ru, j'ai pas pu trouver ton cas, et comme tu repondais plus, c'est en attente pr le moment.
Youwatch par contre, ca ressemble pas  a une erreur vStream ca ... Mais chez moi j'ai pas pu lancer une video encore, probleme de connexion, mais sur firefox ca marche pas mieux, donc en attente aussi.

**Comment by Kodigoal** [comment]
exashare youwatch allvid:
Soucis avec les attaques qui se passent en ce moment sur la toile.

**Comment by TmpName** [comment]
Ha yep, exashare aussi, mais celui la, j'ai tjours eu des prbs avec.
