### ISSUE TITLE
ajout site

### ISSUE THREAD

**Issue by amidevous** [Kodi-vStream/venom-xbmc-addons#1334]
svp ajouter quedustreaming_com comme site merci

**Comment by Arias800** [comment]
C'est ici les proposition https://github.com/Kodi-vStream/venom-xbmc-addons/issues/517

**Comment by johngf** [comment]
@amidevous tu sais ajouté un site toi meme dans le dossier sites de vstream ?

**Comment by TmpName** [comment]
Pr les motive, ce site a deja ete fait il y a tres longtemps, quand il avait un autre nom.
Le fichier a mettre a jour https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/trash/cacastream_com.py

**Comment by johngf** [comment]
J'ai le code amélioré est fonctionelle mais il est pas fait pour etre une source global sur vstream le soir il galere a fond

**Comment by TmpName** [comment]
Moi j'ai pas ete fan non plus.
30 source opnld, 20 sources Ywtch, ect ..... Ca sert a quoi ? Quand Ywtch est HS les 20 liens sont HS en meme temps.
Mais belle collection, y a des trucs rares dessus.

**Comment by johngf** [comment]
Non les liens ne sont pas les memes

**Comment by TmpName** [comment]
Yep mais le soir a 21h quand il a du mal, c'est les 20 qui sont out. Il vaut mieux 10 hosts differents  que 20 liens sur le meme.

**Comment by johngf** [comment]
Enfin moi j'aime pas,attendre ni remplir de captcha etc... donc je m'en sert pour les trucs rares

**Comment by johngf** [comment]
Et  sinon @TmpName c'est possible un timer dynamique qui attend le temps qu'il faut?

**Comment by TmpName** [comment]
Sans chiffres ?
xbmc.sleep(X*1000) attend X secondes. En fait tu veux faire une requete et attendre la reponse ? En jouant avec le timeout ?

**Comment by johngf** [comment]
Oui sans chiffre vu que selon la charge du site c'est plus ou loin long donc risque de timeout si trop petit 
Et si trop grand c'est chiant

**Comment by TmpName** [comment]
Un timeout dynamique selon la charge du site ?
Le prb c'est que pr savoir la charge tu es oblige de faire une requete. Mais si tu met un timeout "moyen" si y a pas de charge c'est plus rapide, et sinon ca attendra le max que tu auras decide.
Non ?

**Comment by johngf** [comment]
Ce que je veux c'est comme ci c'est sans timer des que la reponse arrive on continue parceque,si'le timer est trop petit le script continue avant d'avoir  la reponse qu'il veut

**Comment by TmpName** [comment]
Tu tournes en multithreading ?

Moi pas de timer, un timeout et je bloque tout le temps de la requete, si pas de reponse, le script ne continu pas,
Et peut etre un try/except pr pouvoir continuer en cas de timeout.

**Comment by johngf** [comment]
Non pas de multi vais voir si keep alive fait l'affaire le site te fait attendre donc si t'attend pas le script suis son chemin

**Comment by TmpName** [comment]
Ha, c'est pas une request GET ? ou tu attend une page en retour.
Et comment le navigateur fait ?
Boucle while avec un nombre max de boucle.

**Comment by johngf** [comment]
il ne sera pas ajouter a vstream mais tu peux l'ajouter toi meme [ici](https://github.com/johngf/divers/blob/master/refonte/quedustream_com.py)
