### ISSUE TITLE
Problème mise à jour

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1365]
Salut 
J ai un problème mise à jour, en gros vstream est installe, le Repondre également, il est en 0.5.2 
Mais la maj des sources et host ne veut pas se lancer la derniere en date est celle du 03/05 
Quoi faire ? 
Meme quand je force l'update celle fin''est pas prise en compte du coup impossible de lancer un film puisque les liens sont mauvais ...

**Comment by razorex** [comment]
Fais un clean de tout les caches

**Comment by kikikodi** [comment]
Salut razorex, c'est deja fait mais ne fonctionne quand même pas

**Comment by Kodigoal** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1239
Pourquoi réouvrir une issue la dessus?
Faudrait pêtre commencer à faire ce qui t'as été demandé la bas....

**Comment by kikikodi** [comment]
Oui exact j'ai zappé d'écrire dans cet issue, mais j'ai réussi à la faire je clôture
