### ISSUE TITLE
Comment trouver source uptobox, 1fichier directement depuis vstream 

### ISSUE THREAD

**Issue by Narmo70** [Kodi-vStream/venom-xbmc-addons#1374]
Salut à tous, 
Excuser ma question si elle paraît bête mais je voulais savoir si il était possible de trouver directement ou facilement un film par le biais de vstream en utilisant nos compte premium comme uptobox, 1 fichier et le 3ème dont j'ai oublié le nom. 
Je me suis bien inscrit sur ces sites comme on me l'avait conseillé et quand je trouve une de ces sources cela se connecte bien avec mon compte mais je ne trouve que très rarement ces sources. 

Est-ce qu'il y aurait une astuce pour y arriver directement ? 

Merci d'avance pour votre aide. 
Narmo

**Comment by alfred5959** [comment]
Salut, suis pas un expert, mais je pense que cela dépend des sites. Sur ddl-island par exemple il ne propose pas de lien pour 1fichier ou assez anciens. Sur ZT, tu en auras plus. 
S'il y a une astuce je prends également! :-)

**Comment by Narmo70** [comment]
Merci de ton aide. 
Alors on ça attendre sagement ensemble. 
😉

**Comment by TmpName** [comment]
Tout depend de la qualite que tu cherches, mais pour uptobox, c'est pas trop dur, il est sur pas mal de sites, et les liens durent assez longtemps, comme sokrostrm

Edit: Autant pr moi,Voirflm/streamingK tourne uniquement avec 1 fichier, apparement c'est plutot lui l hebergeur dominant.

**Comment by Narmo70** [comment]
Merci de ton aide!

Est ce qu'il existe une liste que quelqu'un aurait faite et qui permet de retrouver tout cela?
Comme ces inscriptions de compte sont communes à tous les utilisateurs, cela pourrait être utile?
En tout cas pour moi!!!!!!
