### ISSUE TITLE
Nouvelle source

### ISSUE THREAD

**Issue by cehanne** [Kodi-vStream/venom-xbmc-addons#1375]
Salut les gars et d'abord un énorme bravo pour votre addon qui est LA référence KODI en streaming français. 
J'ai une petite proposition d'ajout de source en HD : ht tp://ww w.lozmaz.com
Très bon site , sans pub et en HD.
Je suis désolé j'ai vu qu'il y avait une procédure pour ajouter les sources soi même , mais j'avoue être un peu dépassé.....
Si vous jugez ce site utile à ajouter , n'hésitez pas !

et encore BRAVO pour le boulot !

Cédric

**Comment by Arias800** [comment]
Bonjour ce site est une copie de kepliz déjà dans vstream il me semble ^^

**Comment by TmpName** [comment]
Exactement, deja presente.
