### ISSUE TITLE
Ajouter source de vidéos vstream au menu d'accueil de kodi 17

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1376]
Bonsoir, 
Je viens de voir sur internet que l'on a la possibilité d'accéder directement depuis l'onglet films ou bien séries aux contenus en question sans avoir besoin de rentrer dans un addon https://m.youtube.com/watch?v=jT1F7FmwChc
Est il possible de faire la même chose avec les sources de vstream ou non ? 
Merci

**Comment by TmpName** [comment]
Oui ca s'appelle les librairies, mais pr le streaming c'est pas trop conseille car les liens changent vite.
Tu peux tester, "librairie" dans la page home de Vstream, mais il te faut configurer kodi avec les chemin des lib de Vstream.
Et je sais pas ou ca en est (niveau fonctionnement) , car beacoup de problemes avec, personne veut y passer du temps, car plus chiant a maintenir que utile.

**Comment by kikikodi** [comment]
Je ne sais pas d'ailleurs Zintu connais également les kodi custom ou justement tu as tous les films et séries de tous tes addons affichés et une fois un film choisi ca te redirige vers l'Addon d'où provient le film tu n'a plus qu'à le lancer, c'est franchement pas mal

**Comment by LordVenom** [comment]
Oui Oui c'est faisable mais pas a l'ordre du jour Kodi 17 a apporter pas mal de changement dans le coeur et ont vas d'abord faire un truc stable.(il ont désactiver pas mal de code de la version 12, 14 la compatibilité vas prendre une claque)
