### ISSUE TITLE
Problème chargement des sources à répétition

### ISSUE THREAD

**Issue by tug912** [Kodi-vStream/venom-xbmc-addons#1378]
Bonjour,
je ne sais pas si le soucis vient de Kodi ou de Vstream, mais lorsque je fais une recherche tout se passe bien. La liste des résultats s'affiche. Puis je lance un lien pour le tester tout fonctionne bien. 
Mais lorsque je fais retour arrière pour revenir aux résultats il lance à nouveau la recherche !

Quand on navigue en cherchant la meilleure source cela devient très vite un casse tété vu qu'il charge les résultats encore et encore à chaque retour arrière.

Je ne sais pas si c'est lié mais j'ai le même soucis avec un autre addon : iStream. Alors qu'Exodus ou d'autres fonctionnent parfaitement.

Merci par avance pour vos réponses.

**Comment by Arias800** [comment]
Bonjour quels est votre version de kodi ?

**Comment by tug912** [comment]
Alors j'utilise Kodi 17.1 (Krypton)

**Comment by TmpName** [comment]
Ce bug etait present sur la V17, normallement resolu a la V17.1, tu es sur de ta version, c'est pas une version RC1 ?

**Comment by tug912** [comment]
Oui c'est bien la version 17.1. 
Voici un extrait du log :

18:30:14.004 T:6952  NOTICE: 	[PLUGIN] Vstream: Closing player
18:30:14.053 T:5268  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
18:30:14.081 T:4732 WARNING: CPythonInvoker(49): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
18:30:14.089 T:6952  NOTICE: 	[PLUGIN] Vstream: Table initialized
18:30:14.141 T:5268  NOTICE: 	[PLUGIN] Vstream: load site film_illimit_fr and call function ShowSpecialHosters
18:30:14.323 T:4732  NOTICE: iSTREAM: -searchhistory- -Loading sqlite3 as DB engine version: 3.10.2
18:30:14.354 T:4732  NOTICE: iSTREAM: Search History Cleanup Service - Starting\Waking...
18:30:14.357 T:4732  NOTICE: iSTREAM: -searchhistory- -SELECT DISTINCT indexer_type FROM searchhistory
18:30:14.357 T:4732  NOTICE: iSTREAM: Search History Cleanup Service - Sleeping... Sleep for 300 mins
18:30:14.704 T:5268  NOTICE: 	[PLUGIN] Vstream: Table initialized
18:30:15.678 T:5624  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
18:30:15.686 T:5624  NOTICE: 	[PLUGIN] Vstream: load site film_illimit_fr and call function showHosters
18:30:16.329 T:5624  NOTICE: 	[PLUGIN] Vstream: Table initialized
18:30:17.615 T:1588  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
18:30:17.625 T:1588  NOTICE: 	[PLUGIN] Vstream: load site globalSearch and call function searchMovie
18:30:22.933 T:1588  NOTICE: 	[PLUGIN] Vstream: Table initialized
18:30:22.966 T:2212   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%201%3a%20Films&type=film
18:30:22.967 T:2212   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%201%3a%20Films&type=film) failed
18:30:23.056 T:5572  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
18:30:23.063 T:5572  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showSearch
18:30:23.687 T:5572  NOTICE: 	[PLUGIN] Vstream: Table initialized
18:30:26.365 T:6620   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/e/ebce3ded.jpg
18:30:28.192 T:2212  NOTICE: Storing total System Uptime
18:30:28.192 T:2212  NOTICE: Saving settings
18:30:28.197 T:2212  NOTICE: Saving skin settings
18:30:28.200 T:2212  NOTICE: stop all

**Comment by Arias800** [comment]
"18:30:14.081 T:4732 WARNING: CPythonInvoker(49): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version." ça vien peut être de la non ? @TmpName

**Comment by tug912** [comment]
Merci pour votre aide par avance !
 
Autre Log si ça peut aider : 
pour info j'ai désinstallé iStream au cas ou et réinstallé Vstream. Toujours même problème

16:46:35.122 T:6596  NOTICE: 	[PLUGIN] Vstream: player stoped
16:46:35.722 T:6596  NOTICE: 	[PLUGIN] Vstream: Closing player
16:46:35.722 T:3444  NOTICE: Stream All The Sources: Service: Playback Stopped
16:46:35.783 T:7148  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
16:46:35.790 T:7148  NOTICE: 	[PLUGIN] Vstream: load site film_illimit_fr and call function ShowSpecialHosters
16:46:35.796 T:6596  NOTICE: 	[PLUGIN] Vstream: Table initialized
16:46:37.032 T:5272  NOTICE: Previous line repeats 1 times.
16:46:37.032 T:5272  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
16:46:37.038 T:5272  NOTICE: 	[PLUGIN] Vstream: load site film_illimit_fr and call function showHosters
16:46:37.684 T:5272  NOTICE: 	[PLUGIN] Vstream: Table initialized
16:46:38.526 T:4688  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
16:46:38.532 T:4688  NOTICE: 	[PLUGIN] Vstream: load site globalSearch and call function searchMovie
16:46:43.113 T:4688  NOTICE: 	[PLUGIN] Vstream: Table initialized
16:46:43.128 T:6548   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%201%3a%20Films&type=Film
16:46:43.128 T:6548   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%201%3a%20Films&type=Film) failed
16:46:43.201 T:5624  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
16:46:43.206 T:5624  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showSearch
16:46:43.850 T:5624  NOTICE: 	[PLUGIN] Vstream: Table initialized

**Comment by TmpName** [comment]
Le message "Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version" n'est pas genant, il est juste provoque quand on utilise "runscript" sans utiliser addon id ou de parametres dans la commande. Si ca vient de Vstream on va vite s'en rendre compte car ca veut dire aussi que pour le moment c'est autorise, mais que ca va etre desactive dans une version future.
Ca peut provoquer des bugs, mais je pense pas que ce soit ca.

Sinon, plus besoin de log, c'est bien le bug de la V17. On peut voir que tu as lance un film sur film_illimit_fr et que a chaque fois que tu as fait un retour arriere tu as eu ShowSpecialHosters puis showHosters puis globalSearch et searchMovie. Chez nous les log sont vierge car kodi utilise la page memorisee, ca logue quand on accede a la page mais pas quand on revient en arriere.

Tu as bien installe la version prise sur le site officiel ? Chez nous ce bug s'est corrige seul avec la derniere version et je n'ai aucune idee de l'endroit ou peuvent se trouver les reglages concernant ce cache, et suis pas sur qu'ils existent, vu que tout le monde a du attendre la derniere version justement.

**Comment by tug912** [comment]
Merci pour ta réponse ça m'a orienté vers la solution !

Incroyable mais c'était tout bête, j'ai fini par réinstaller la version depuis SuperRepo.org et non le repo Vstream dispo ici et oh miracle plus de bug !
Naïvement je me suis dit que ce serait le plus récent ici mais il faut croire que non. Pourtant les deux repos affichent bien la version 0.5.2. ! 
A croire que ce ne sont pas vraiment les mêmes.

Désolé pour le dérangement et Merci à tous pour votre aide en tout cas !

**Comment by tug912** [comment]
En fait je viens de réessayer la manip sur mon PC cela ne marche plus ! 
Mais ça a marché sur le raspberry... je n'y comprend plus rien !

**Comment by Arias800** [comment]
Sur PC essaye de prendre la version en alpha peut être que ça peut corriger le bug ^^

**Comment by TmpName** [comment]
C'etait en prenant la derniere version de kodi que le defaut partait, pas celle de Vstream.
