### ISSUE TITLE
Vstream et sportsdevil problèmes 

### ISSUE THREAD

**Issue by hart07** [Kodi-vStream/venom-xbmc-addons#1379]
Bjr je suis sous kodi 17 via mon Android TV jusqu'à il y a 15 jours tout marchait plutôt bien
Sauf que les soucis de liens qui marche pas son arrivé avec sportsdevil 
Message d'erreur Web request failed 
Ensuite la plupart des chaînes tv sports idem je peux pas les avoir alors que tout était OK 

Et maintenant c'est vstream qui marche alors qu'avant tout marchait. 
Exemple je cherche la série Colombo je tombe sur une liste j'y vais ensuite clique sur un épisode youwatch qui marchait avant et là message d'erreur suivant un ou plusieurs objets sont introuvables voir log pour plus de détails ou alors en haut à droite une icône avec connection erreur 405.
Est il possible que mon fournisseur internet bloque mon ip ?
Ou est-ce un problème complètement différent ?
Merci de votre aide

**Comment by hart07** [comment]
Je suis sous kodi 17.1 krypton
J'ai installé vstream via le super repo 
Et sportsdevil avec fusion

**Comment by Kodigoal** [comment]
"Youw atch Exas hare et Allv id auraient perdu TOUTES leurs données après un piratage : 4000 TB"
Pour ses 3 hosters si ca fonctionne pas , c'est normal lol
Pour sport de vils ,si ca fonctionne pas , faut poster la bas ^^
voir lien officiel topic sur pastebin:
https://pastebin.com/iB1ViEyB

**Comment by hart07** [comment]
OK je comprends mieux 
Elles vont être récupérées les données ou c mort?
Pourquoi les liens sont encore visible alors ?
Je vais voir sur le lien que tu m'a donné pour spirtsdevil 
Merci encore des informations

**Comment by hart07** [comment]
Donc ce n'est pas un soucis de vpn qu'il faudrait pour les liens sur sportddevil par exemple, même si je suis pas dans le bon forum 
Merci

**Comment by Arias800** [comment]
@Kodigoal sérieux ? Source?

**Comment by Kodigoal** [comment]
@arias800 apparemment oui
@ Da mien_Ba ncal: #Youw atch #Exash are et #Allv id auraient perdu TOUTES leurs données après un piratage : 4000 TB ! @za taz #cybers écurité @ lea kid

**Comment by hart07** [comment]
OK merci 
Pour vstream apparemment ça marche tjrs pas 
Quand je vais dans recherche exemple columbo 
Il charge les sites et à un moment en haut à droite il y a marqué vstream connexion impossible erreur 405 puis ça continue et j'arrive sur une liste de dossier 
J'obtiens une liste je vais dans un dossier qui contient les épisodes je clique sur un épisode qui marchait avant et là j'obtiens le message suivant 
Échec de lecture d'un ou plusieurs fichiers consultez le journal pour plus d'informations sur le message

**Comment by hart07** [comment]
Les épisodes en flash x marchent mais pas youwatch ni exashare

**Comment by Kodigoal** [comment]
Surement un site inaccessible lors de la recherche ( erreur 405)
Sinon comme dit plus haut, pour les liens  you watch exa share all vid , ca ne fonctionne plus car ils se sont fait hacker et toutes leurs données ou presque ont été effacées (donc adios toutes les vidéos hébergées sur ses 3 sites) 
rien d'anormal donc les liens sont h.s

**Comment by TmpName** [comment]
Pr columbo, suis filmstrmvk, ils marchent sur le site mais pas dans Vstream (netu) a corriger.
Il y est sur kaydo, fct ok.
Sur serie-strm-watch fct avec flashX

**Comment by TmpName** [comment]
Netu repare.
Sinon j'ai plus l'error 405, mais c'est l'erreur correspond a "mauvaise methode" donc le prb a pu provenir de Vstream aussi.

**Comment by laquarico** [comment]
Bonsoir j utilise kodi 17.1 sur fire stick et vstream ne fonctionne pas ca a commence y a une semaine tout mes liens venant d ADKami ( tous les dragonball series) ont arrete de marcher et maintenant c est tout mes liens mis en favori peut importe le serveur plus rien ne marche....est ce qu il y a une nouvelle version de vstream? Je suis en version 0.5.0
Merci

**Comment by TmpName** [comment]
On en est a la V 0.5.2 ^^.
Mais beacoup d'hebergeur ont eu des soucis dernierement Ywatch allVD et je sais  plus lequel mais netu a fonctionne pr les Dragon ball quand j'ai teste.

**Comment by Arias800** [comment]
Exashare a des problème aussi il me semble ^^

**Comment by laquarico** [comment]
Merci bien et quel est le url pour le repo? Celuo que j ai ne me laisse pas
faire une update

**Comment by TmpName** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository

Je crois meme qu'il y a une video pour le mode d'emploi.

**Comment by laquarico** [comment]
Merci c est le repo que j ais

**Comment by TmpName** [comment]
Et quand tu vas dessus en te baladant dans "depots dextensions" tout a l'air bon ? pas desactive ou bloque par le systeme ?

**Comment by laquarico** [comment]
Non me l ai reinstalle heir et tout va bien maintenant me vais chercher les
streams pour mes dessin anime de mon enfance qui marchent

**Comment by TmpName** [comment]
Pour ca mon site prefere c'est tv_streaming_ch, une pepite ^^.
