### ISSUE TITLE
Ajout de source via la recherche visuelle

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1380]
Bonjour,

Quand je fais une recherche visuelle dans "Séries Populaires" et que j'ajoute des séries aux marques-pages :

Les séries sont ajoutés à l'onglet des marques pages : "Recherche visuelle"

Serait-il possible qu'ils soient ajoutés à l'onglet "Séries" ?

Merci d'avance pour votre réponse.

**Comment by TmpName** [comment]
Et ca marche sinon ?
Je croyais que les favoris deconnaient avec la recherche visuelle, car ca avait besoin de plus d'infos (comme saison, episode, ect ...) et que ce n'etait pas gere dans les favoris.

Je pensais meme que ca avait ete desactive pr ce type de recherche.

**Comment by canopre** [comment]
Oui ça fonctionne correctement.
