### ISSUE TITLE
Ajout site pour live tv

### ISSUE THREAD

**Issue by dias7** [Kodi-vStream/venom-xbmc-addons#1382]
Bonjour,  est-ce que c'est possible d'ajouter ce site, h ttps://w ww. firstonetv.eu/Live
 il offre plusieurs chaines .
Merci d'avance.

**Comment by vic1997** [comment]
Ca peut être pas mal si les liens de streaming ne bouge pas, ça permettrais de les récupérer et de pouvoir les utiliser sans avoir à les changer à chaque fois. @LordVenom doit voir ça.

**Comment by dias7** [comment]
Merci pour ta réponse,  c'est un site très intéressant où on trouve plusieurs chaînes françaises en directe et la qualité est pas mal aussi. Espérant qu'on peut l'ajouter. 
 merci pour le travail que vous faites.

**Comment by Arias800** [comment]
Le problème c est que si tout les utilisateur de vstream utilise ce site ça risque de surchargé les serveur par exemple il ont été down pendant la coupe du monde handball

**Comment by vic1997** [comment]
Ouais c'est sur, ce qu'il faudrait c'est un serveur qui capte le flux te qui le renvoi à tous ceux qui le veulent (ici du coup c'est nous, enfin client de vstream). Ça coute pas cher mais je pense pas que les créateurs voudraient payer, il faudrait récupérer des dons pour pouvoir acheter un serveur.

**Comment by dias7** [comment]
Ça c'est un problème du site et pas notre problème puisque il offre ce service. Pour moi I'essentiel c'est que les clients de vstream en profitent. En plus y a plusieurs liens qui ne marche pas dans la catégorie télévision. Et c'est normale . Si on veut un service optimale on devrait payer!!! C'est mon point de vu.

**Comment by TmpName** [comment]
Pareil, je me plaint jamais sur un truc gratis, par contre si je paye, y a interet a avoir du support derriere.
Non au pire je me tais, je pleure en silence (put1 encore une nouvelle version de kodi bourrée de bugs ....), et je viens raler ici le lendemain.

Apres les utilisateurs de Vstream sont discret, on va pas etre 15 a se connecter en meme temps.

**Comment by Arias800** [comment]
Après vous pouvez teste mais je prévenait juste ^^
