### ISSUE TITLE
Ajout d'une catégorie : Spectacles

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1383]
Bonjour à tous,

Serait-il possible de rajouter la catégorie "Spectacles" à la liste des genres de films ?

Merci d'avance et encore merci à tous pour ce super addon !

**Comment by TmpName** [comment]
C'est vrai que ca manque, mais je vois pas ou le rajouter.
Chez moi ca rentre pile sur 1 ecran avec 3 * 5 icones  l'ecran ^^. 

![son](https://cloud.githubusercontent.com/assets/8311559/26274327/d028e93c-3d47-11e7-8b23-4cf3f3af27e7.jpg)

**Comment by canopre** [comment]
Hello
Merci pour ta réponse,
Je pensais à un ajout à la liste des catégories quand on fait une recherche visuelle par genre.
Mais ce n'est peut-être pas si simple.
Bon we.
++

**Comment by TmpName** [comment]
Ha, pour la recherche visuelle c'est mort, de memoire sur le site tmdb il y a juste series et films (ou gros documentaire)
