### ISSUE TITLE
Liens Zone Telechargement.ws ne s'affichant plus

### ISSUE THREAD

**Issue by pierrinator** [Kodi-vStream/venom-xbmc-addons#1389]
Yo,

Les liens des hosters ne s'affichent plus chez moi... j'ai essayé de modifier un peu le .py de ZT.ws, j'ai l'impression que ça foire au niveau de dl-protecte... je suis le seul ?

Merci :)

**Comment by karim505** [comment]
Salut 

Oui j'ai aussi le même problème les liens ZT.WS ne s'affiche plus.
Je pense aussi que c'est au niveau de dl-protecte car on a les hébergeur pour le fichier et c'est juste après que sa foire ( le site n'est pas down pour autant)
Hey dit moi je viens juste à l'instant de m'inscrire je ne connais pas trop , est ce que tu connais un tuto ou un lien pour m'aider a configurer super bien kodi 17.1, ma config ( shield tv 2017 + tv lg 4k hdr)
Merci d'avance :)

**Comment by akatimke** [comment]
Même problème chez moi les lien ZT n'apparaît plus :(

**Comment by Arias800** [comment]
Ils vous suffit de mettre manuellement a jour le fichier :https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py ou d'attendre quelque jour pour la mise ajour automatique

**Comment by karim505** [comment]
Je fais comment pour mettre le fichier à jour manuellement svp ?
Je l'ai jamais fais

Le 21 mai 2017 16:54, "Arias800" <notifications@github.com> a écrit :

Ils vous suffit de mettre manuellement a jour le fichier :
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.
vstream/resources/sites/zone_telechargement_ws.py ou d'attendre quelque
jour pour la mise ajour automatique

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1389#issuecomment-302941675>,
or mute the thread

**Comment by Arias800** [comment]
Mise à jour Manuelle

Pour les impatients et les bidouilleurs vous pouvez télécharger les sites et host directement du github et les copier dans le dossier de vStream

Naviguer sur la beta pour choisir votre fichier, cliquer sur RAW puis enregistrer la page.

https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/plugin.video.vstream
Les dossiers de vStream sont des fichiers cachés.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-vStream
ATTENTION

Ne pas copier des fichiers du core de vStream (en fait les seuls intéressants pour vous sont dans le répertoire "sites" et "hosters".

La mise à jour auto et semi-auto modifiera ces fichiers.
Pour acceder au fichier de vstream il faut faire : Windows+r ensuite tu tape %appdata% et apres tu vas dans Kodi\addons\plugin.video.vstream\resources\sites et tu ouvre le fichier de zone téléchargement et tu y colle le nouveau

**Comment by karim505** [comment]
Merci beaucoup je teste sa

**Comment by pierrinator** [comment]
Merci, je viens de tester, mais malheureusement ça tue carrement l'affichage de la source dans Kodi..

**Comment by Arias800** [comment]
Ah bon ? il se passe quoi exactement ?

**Comment by pierrinator** [comment]
My bad, je suis un blaireau, j'm'etais mélangé les pinceaux dans Atome pour voir vos modifs et j'avais tout cassé... tout fonctionne, merci !

**Comment by Arias800** [comment]
Ah sur le coup j'ai eu peur car chez moi tout fonctionne ^^ et de rien mais il faut aussi remercie @Ryuk999 qui a fait la modife du script ^^

**Comment by noipo** [comment]
j'ai un probleme similaire, aucun lien uptobox ne joue chez moi... Je ne peut même as entrer le captcha.
Même chose sur ddl island

**Comment by karim505** [comment]
Exact dsl island ne fonctionne pas chez moi

**Comment by Arias800** [comment]
Ok je teste et je vous dit ^^

**Comment by Arias800** [comment]
Normalement le captcha apparaît en plein écran et il faut cliquer sur le clavier en bas a droite pour faire apparaître le clavier et taper sur valider Pour uptobox ça ne marche pas alors que uptostream oui mais ça dépends des site chez moi des fois (zone-telechargement ) par exemple c'est l'inverse ^^

**Comment by Kodigoal** [comment]
creer un compte gratuit sur le site uptobox et rentrer les identifiants dans les paramètres de vStream.

**Comment by akatimike** [comment]
Salut J'ai mi a jour le fichier python fournie ci dessus pour ZT mais je rencontre le mémé problème... aucun lien apparaît seulement ...

**Comment by reds07** [comment]
Salut,

Quelqu'un a une idée de quand est pour la mise à jour, je ne peux plus accéder à aucun liens sur zone téléchargement 😣😣😣

**Comment by TmpName** [comment]
Le fichier a ete mit a jour il y a 2 jours, donc normalement vu que la verification se fait tout les 3 jours, ca devrait plus tarder.

**Comment by karim505** [comment]
Quelqu'un la mis à jour à titre individuel ? Je deviens fou de pas avoir
accès à ZT.ws
C'est dans ce genre de cas qu'on se rend compte que les autres sources ne
lui arrive pas à la cheville
En tout cas si qqn peut me l'envoyer sa serait op
Merci

**Comment by TmpName** [comment]
Ben normallement depuis le temps la MAJ devrait t etre propose, sinon remplace l'ancien fichier par celui la.
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

Sinon pour ses chevilles, c'est quoi le plus que tu trouves a cette sources ? la qualitee des videos ?
