### ISSUE TITLE
Lien Kaydo.ws ne se lancent pas 

### ISSUE THREAD

**Issue by noipo** [Kodi-vStream/venom-xbmc-addons#1393]
les lien sur la source kaydo ne s'ouvrent pas, une solution ?

**Comment by TmpName** [comment]
Mit a jour a l'instant.

**Comment by patoche2025** [comment]
On doit avoir un login et un mot de passe pour accéder à kaydo.ws @TmpName @noipo car moi je vois rien à part ... ?

**Comment by johngf** [comment]
@Patoche2025 kaydo(hdstream) bloque certaine ip comme les ip via vpn ou 4g

**Comment by patoche2025** [comment]
C'est nul de faire ça! lol

**Comment by TmpName** [comment]
Suite ici
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1400
