### ISSUE TITLE
Problème installation KODI

### ISSUE THREAD

**Issue by alexgasio** [Kodi-vStream/venom-xbmc-addons#1398]
Bonjour à tous, 

Je viens de faire la dernière mise à jour Krypton, et lorsque j'essaye d'installer l'addon Vstream, rien ne se passe. 
Quelqu'un a déjà eu ce soucis ? 

Merci d'avance,

**Comment by alexgasio** [comment]
Après plusieurs essais j'ai finalement réussi ! 

Sujet à fermer!

**Comment by TmpName** [comment]
C'est bon, car tu as deja cloture l'issue ?

**Comment by alexgasio** [comment]
Oui oui merci :-) !
