### ISSUE TITLE
KAYDO

### ISSUE THREAD

**Issue by noipo** [Kodi-vStream/venom-xbmc-addons#1400]
Décidement la source kaydo.ws est vraiment versatile, autant hier tout fonctionnait très bien mais je viens de réessayer et plus rien ne fonctionne.
Peut-être faudrait-il indiquer dans py hd-stream.net plutot que kaydo.ws même si j'imagine que cela ne changerait pas grand chose

**Comment by TmpName** [comment]
C'est possible de basculer en auto sur l'autre, si le premier marche pas, c'est d'ailleurs ce qui se passe sur le navigateur, mais moi perso ca marche tjours, donc peut pas faire de tests.

**Comment by noipo** [comment]
Je viens de réssayer à l'instant et lorsque que je clique sur un film ça charge et rien ne se passe tandisque avant les films ne s'affichaient même pas, étrange...
Pourtant le site web est parfaitement fonctionnel

**Comment by noipo** [comment]
J''ai peur d'être répétitif mais kaydo ne marche toujours pas je viens encore de réssayer

**Comment by Kodigoal** [comment]
testé et tout se lance , lien direct ou via uptobox.
Nouveauté , lego batman et cie , 1er page tous les films ok.

**Comment by TmpName** [comment]
Nouvelle version encore.
