### ISSUE TITLE
TV

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1402]
@lolema  prévient nous quand tu met a jour ton xml que je puisse faire le pull request car j'ai pas de notif.

**Comment by vic1997** [comment]
@LordVenom Je pense que tu l'as vu, j'ai commit de nouveau lien pour la section "Tv du web", cependant j'ai testé et elle ne marchent pas sur Vstream, pourtant ça marche avec VLC et les liens direct, faut mettre à jour Kodi ou c'est du direct (il chope les liens direct sur github) ?
Sinon les liens sont en .ts, c'est peut-être ça ? #1399 

Parce que j'ai pleins de lien de tv que je pourrais mettre à jour souvent (les chaines de base en tout cas), mais les catégories "Télévision" sont déjà mis à jour par @lolema , j'aimerais juste une section où j'ai les droits et qu'il n'y a que les chaines de base (du genre Tv du web c'est bon pour moi) où je pourrais modifier souvent les liens.

**Comment by lolema** [comment]
mis à jour à l'instant

**Comment by LordVenom** [comment]
@lolema Mise ajour :)

@vic1997 Oui ta modification à était valider ça devrais fonctionner maintenant.

**Comment by vic1997** [comment]
@LordVenom Ok c'est bon j'ai vérifié ! Ça marche !
J'actualiserais donc "Tv du Web" le plus souvent possible, à toi d'accepter mes pull request !
Quand aux chaines avec regex, je les laisses car ils ont l'air d'être permanent et de ne jamais expirer, mais les autres je risque de supprimer de coller au fur et à mesure les chaines que je trouve !

**Comment by vic1997** [comment]
Les chaines TV de la catégorie "Tv du web" possédais des id, nom, groupe et logo, j'ai du par manque de temps ajouter toutes les nouvelles chaines sans ces attributs (il faut remplacer un par un à la main). D'ici 2-3 semaines je m'occuperais de créer un logiciel pour faire tout ça automatiquement, mais pour l'instant je n'ai pas le temps, ils sont donc pour l'instant sans ces attributs. @LordVenom

**Comment by vic1997** [comment]
@LordVenom Comment faire pour que mes pull request soit directement accepté et mise "en ligne" (sur master) ? Car là, le temps que les liens soient accepté, ils souvent déjà mort !

**Comment by TmpName** [comment]
Tu peux demander a etre inscrit au groupe mais si le lien ne tient pas plus de 24h, personne n'aura le temps d'en profiter.

**Comment by vic1997** [comment]
@TmpName c'est ce que je vais faire je pense, mais comment ?
Pour les liens ça varie, y en as qui dure des semaines et d'autres quelques heures voir jours, mais je suis la pour les changer à n'importe quel moment :)

**Comment by TmpName** [comment]
Je sais pas si tu peux te proposer ou si c'est a l'admin de t'envoyer la proposition.
C'est le chef qui gere ca ^^.

**Comment by LordVenom** [comment]
Tu as les pouvoir aussi lol mais bon je les fait :)

**Comment by vic1997** [comment]
@LordVenom @TmpName Haha oui c'est ce que je me disais qu'il avait les droits aussi. En tout cas merci ! Je mettrais à jour tout ça le plus souvent possible !

**Comment by vic1997** [comment]
@LordVenom Je ne sais pas comment faire pour envoyé seulement mon fichier sur la branche master (pour que les TV soit mis à jour dans l'application vu qu'ils ne le sont pas en restant dans Beta), saurais-tu comment faire ?

**Comment by LordVenom** [comment]
ça seras corriger a la maj pour le moment pas possible.

**Comment by TmpName** [comment]
Lol, savais pas
I've got the powerrrrrr !!!

Mais de toute facon je savais pas comment faire ^^.

**Comment by lolema** [comment]
la playlist a été mis à jour et cette fois j'ai enlever tout les préfixes avant les chaines pour que la première lettre soit réellement celle de la chaîne rechercher

**Comment by vic1997** [comment]
@LordVenom Ok, tu me diras quand c'est bon !

**Comment by vic1997** [comment]
@nathjo Salut, normalement je les mets à jour très souvent, le problème actuel c'est que je n'ai pas les droits pour les mettres sur le branche master (et c'est que sur la branche master que vStream lit ce fichier), du coup les chaines ne sont pas à jour comme elles devraient l'être !

Donc tu peux très bien en rajouter (même si celles qui sont sur beta marchent normalement toutes) mais tant que ça n'est pas déplacé sur master, elle ne serviront à rien.

@LordVenom doit d'ailleurs m'indiquer comment faire pour que ces chaines soit directement mis sur master.

Sinon tu peux modifier ce fichier directement dans beta avec le bouton "modifier" qui a une forme de crayon.

**Comment by nathjo** [comment]
C'est note, merci pour vos réponses :)

**Comment by LordVenom** [comment]
Voila quand la 0.5.3 sortira la tv du web ça mettra a jour en direct.

**Comment by vic1997** [comment]
@Lordvenom Super ! Merci !

**Comment by vic1997** [comment]
Je vais donc faire un "logiciel" de mise à jour automatique des chaines IPTV de la section TV du web, avec une mise en forme et les logos.
