### ISSUE TITLE
Possibilité de choisir par un onglet uniquement les films et séries hd

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1403]
Salut, 
Pensez vous qu'il est possible de créer une sous catégorie dans les recherche pour filtrer les films qui ne sont qu'en hd? 
Pour éviter de devoir aller jusqu'au résultat de la recherche et n'avoir que des cam. 
Ou sinon directement depuis mes réglages , cocher une option"ne montrer que les films/séries en HD) 
Je pense que ce serai pas mal pour les films encore en salle... ?

**Comment by johngf** [comment]
Pas possible des fois les sites marque hd alors que ça ne l'est pas ,des fois il n'est rien écris sur la qualité,
Faire le tri réel n'est pas possible à cause des sites
La recherche par vstream utilisé le nom du film ou serie 
si tu ajoute nom du film + hd il y a peu de chance de trouver de la HD vu que les sites référence seulement le nom du film

**Comment by TmpName** [comment]
Tout depend de l'appellation HD, pour certains sites 720p c'est de la HD.
Mais il y a une section HD qui donne de bon resultat, meme si c'est pas toujours de la HD, tu tombera pas sur des screener ou alors donnes le site, c'est qu'in n'est pas a sa place.

**Comment by kikikodi** [comment]
Oui quand je dis hd que ce soit du 720 ou du 1080 ou autre tant que la qualité d'image est identique peu importe. L'idée c'est de ne pas tomber sur du camscreen ou autre image déguelasse
A la limite quitte à se passer dès sites ne le mentionnant pas... 
franchement ce serait top 
Parceque de revenir tous les jours sur une jacquette faire la recherche et arriver que sur du cam c'est lassant ... non?

**Comment by johngf** [comment]
mais la hd c'est pas sur tous les sites et si tu cherche un film qui est sortis récemment au ciné en hd t'es sur de tombé sur un cam ou screener(bon sens)

**Comment by TmpName** [comment]
Jetes un oeuil dans films/films qualites HD. Je ne garantis pas que tout les sites soient a la bonne place, mais pour ceux dont je me souviens, tu aura dedans de la HD et meme de la vraie.

**Comment by kikikodi** [comment]
Tmpname mais ou choisir les sites HD dans la version actuelle de vstream? Dans les paramètres?

**Comment by razorex** [comment]
Tu a un menu films (qualité HD) en sous menu de "films"

**Comment by TmpName** [comment]
Tu peux aussi, dans les parametres, dans l'onglet recherche, definir toi meme la recherche "Film HD" et dedans ne selectionner QUE les sites ou tu es sur a 100% de trouver des resultats HD.

**Comment by kikikodi** [comment]
Oui j'ai vu pour le choix des films hd, mais cela nécessite de choisir site ensuite, donc ce n'est pas General, aussi impossible de choisir les hd par date de sortie, puisque l'onglet hd donne accès à tout les films...

**Comment by kikikodi** [comment]
Autre problème je viens de tester par exemple àvec la méthode en question àvec filmillimite qui propose des contenus presque tout le temps hd, et la j'en lance un il est bien en hd mais en vostfr, pas en VF

**Comment by razorex** [comment]
oui j'avais vu (lol) en projet du moins de mon côté.

**Comment by kikikodi** [comment]
Franchement je pense que le fait de pouvoir passer par la recherche visuelle de façon Classic et de pouvoir choisir en salle > puis hd serai top , non? Plutôt que d'aller dans films > films hd 
Parceque dans la
Seconde on est limite à choisir le site et apres y'a de tout des films récents et des plus vieux sans choix précis

**Comment by johngf** [comment]
oui mais film en salle t'aura j'amais de la hd

**Comment by kikikodi** [comment]
Si il est souvent possible d'en avoir en hd des films en salle, à la limite classer par année ou autre mais je pense sincèrement que ce serait vraiment top comme ajout à la prochaine mise à jour, vous en pensez quoi ?

**Comment by johngf** [comment]
c'est parque la liste est mal mis a jour ou mélangé avec sortie recente via recherche visuelle comment veux tu avoir un film en hd si il n'est pas sortie dans le commerce les pirate sont fort mais pas a ce point

**Comment by kikikodi** [comment]
Je ne vais pas te l'apprendre bien souvent les films sont soit piraté et meme encore encore en salle et en hd, j'ai meme teouve un film l'autre jour pas encore en salle uniquement prévu avec les affiches publicitaire l'annonçant pour dans dix jours en salle.. tout est possible. Apres il y a aussi les versions canadiennes 
Enfin vraiment tout est possible de nos jours 😜

**Comment by johngf** [comment]
les films que tu arrive a avoir en hd qui sont dans la rubrique en salle sorte en commerce directement (direct to video) et au ciné dans certains pays essaye de trouver le dernier alien en hd bon courage

**Comment by kikikodi** [comment]
Attention je ne t'ai pas dit tous les films mais certains, et justement d'où l'intérêt de pouvoir filtrer de façon à avoir uniquement les récent, les en salle ou autre uniquement t en hd depuis la recherche visuelle . 
Par ce qu'il n'y a pas plus rageant que de cliquer sur une jacquette , lancer la recherche sur les 28 sources et apres de tenter de trouver éperdument parmis les résultats le film en hd qui d'ailleurs peu ne pas exister au moment venu

**Comment by LordVenom** [comment]
Comme dit par @TmpName  tu peux te faire une recherche perso qui cherchera uniment sur les sites que tu trouve de qualiter (à toi de les sélectionner) ceux dans la catégorie HD par exemple, Aprés ne pas confondre HD et de qualiter certain film nom marquer HD sont trés propre.

**Comment by TmpName** [comment]
Sur "filmillimite" la langue n'etait pas indique dans le titre ?
Si non ca ca se corrige par contre.
Mais la recherche visuelle est un gadget, c'est ce qu'il y a de moins efficace pr trouver un film. Ca marche d'apres une base de donnee, pas de fichier present trouves sur le net.
Pour trouver de la HD faut partir dans l'autre sens, tu cherches de la HD et tu choisit ton film.
La recherche visuelle, cherche un film et tu te demerde pr trouver la HD.

**Comment by razorex** [comment]
@TmpName Non pas récupérable dans showmovie mais dans showhosters `<meta itemprop="genre" content="VOSTFR">.` c'est possible uniquement pour les films pas pour les séries la langue n'étant pas précisée.

**Comment by TmpName** [comment]
Mouais et en plus c'est tjours de la VF pr les films, a part pr les trucs recents. C'est possible mais ca va compliquer le code pr pas grand chose.

**Comment by razorex** [comment]
non de la vostfr aussi

**Comment by kikikodi** [comment]
Tmpname, tu ne trouves pas que cela serait mieux franchement ? 
Perso je teouve que ça change la vie ...

**Comment by TmpName** [comment]
Ben c'est a voir mais deja c'est pas indique pr les series, c'est rare (juste des trucs recent) et j'ai meme pas pu tester encore si c'etait vraiment de la VOSTFR car leur player est HS (du moins chez moi).
J'aimerais etre sur que ca va servir a quelque chose, en fait ca va se baser sur ce qui est indique sur l'onglet des players, et ca deconne chez moi.

**Comment by kikikodi** [comment]
Ah ok j'ai capté, du coup vous pouvez me dire qu'elle sont les sources qui ne sont généralement pas hd ou lni verse les sources sûres? J'ai remarqué par exemple que film-illimité a toujours de la hd , enfin du 1080

**Comment by TmpName** [comment]
Lol, HD si tu veux, 1080 par contre ..... :) , y a que google/uptobox (premium) par exemple qui le propose. 80% des fois ou tu vois ecrit 1080 c'est pas du 1080 au final, mais si tu vois pas la difference c'est pas genant.

**Comment by TmpName** [comment]
PS: issue a garder ouvert pls, pr memoire, j'attend qu'ils reparent le lecteur pr voir si modif.

**Comment by TmpName** [comment]
C'est bon, rajout de 'VOSTFR' mais les liens vostf ne marchent pas encore, donc pas de chance de se tromper.
