### ISSUE TITLE
[Information] Attention vulnérabilité kodi

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1404]
Des chercheur de check point on mit au point une attaque permettent de prendre le contrôle d'un ordinateur grâce au sou-titre des vidéo voyer par vous même : https://www.youtube.com/watch?v=vYT_EGty_6A&feature=youtu.be (kodi 1:00)

**Comment by johngf** [comment]
sur vstream la plupart sont intégré a la video donc pas de soucis

**Comment by Arias800** [comment]
Je préviens au cas ou car des vidéo sont upload sans sous titre justement ^^

**Comment by johngf** [comment]
sur kodi j'ai deux addons perso vstream youtube je me mefie des addons et repo exotiques

**Comment by Arias800** [comment]
Meme sur vstream il y a des video sans sous titre (elle reste environ 2 jour ) et qui te parle de repo et addon exotique dans la vidéo il montre exodus depuis quand c'est exotique ?

**Comment by johngf** [comment]
si tu telecharge pas les sous titres pas de soucis donc

**Comment by Arias800** [comment]
Apres on ne sait pas si les sous-titre déjà intégré ne comporte pas de risque ^^

**Comment by johngf** [comment]
oui mais une video n'est pas executé elle est seulement lue donc pas possible d'y integré un virus le le mec ajoute une sorte de script manuellement en sous titre mais la video est clean

**Comment by TmpName** [comment]
Kodi a deja corrige. 17.2
UptobX/Uptostrm va chercher des sous titres, mais sur son propre site, donc pas de soucis.
Sur exodus tu as les film en anglais (en general) donc tu forcement tu passe par la fonction integree a kodi pr chercher les sous titre > opensubtitle.

Perso ca m'est deja arrive d'avoir une video sans sous titre mais j'ai eu la flemme d'aller chercher les sous titres ^^, j'ai pris un autre hebergeur. (la flemme aurait sauve ma config :) )

**Comment by Arias800** [comment]
Oui mais je prend mon cas personnels ça m ait déjà arrive pour colony notamment de devoir ajouté les sous titre donc je prévenait ses personne mais c est bien si il ont déjà corriger la faille ^^

**Comment by Kodigoal** [comment]
lol bien trouvé cette faille ..
Au pire , on peut check le fichier sousTitre via uptobox/uptostream si ya pas du code malicieux dedans avec de l'afficher ^^

**Comment by Arias800** [comment]
de tout façon si c'est fixe je ferme ^^

**Comment by TmpName** [comment]
Mais j'aime bien ce genre de news, juste pr ma culture personnelle, les failles meme comblées, ca m'interesse.
