### ISSUE TITLE
Kepliz - Next

### ISSUE THREAD

**Issue by Atomium25** [Kodi-vStream/venom-xbmc-addons#1410]
Bonjour tout le monde, 

Depuis peu, l'option next lorsque nous sommes dans la catégorie Derniers Ajout de Kepliz a disparu ..
C'est dommage c'était vraiment très pratique pour visionner des choses sorties il y'a quelques semaines.
Pourriez vous jeter un oeil là-dessus ? :)

Merci d'avance, bon week-end ;)

**Comment by Arias800** [comment]
C'est normale car de base sur le site dans Derniers Ajouts le next n'est pas disponible par contre dans a l'affiche c'est disponible ^^

**Comment by Kodigoal** [comment]
Ya jamais eu de next pour dernier ajout sur Kepliz.
Suffit d'aller voir la version web et tu verras qu'il n'y ya pas plusieurs pages sur l'accueuil.
On peut pas l'inventer xD

**Comment by Atomium25** [comment]
Ah ben je pensais que de mémoire il y avait, j'ai du confondre avec Film Illimité ! :P
Excusez moi pour la gêne alors .. ;)
