### ISSUE TITLE
Sites dead

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1411]
enquete de reportages et Ddlfrench sont mort.

**Comment by LordVenom** [comment]
Mort ? les sites ou le code ?

**Comment by TmpName** [comment]
Le site je dirais, mais j'ai juste une page vide, ca se connecte.

**Comment by razorex** [comment]
les sites. page blanche oui pour Ddlfrench et une page qui dit que le nom de domaine est dispo pour l'autre.

**Comment by TmpName** [comment]
C'est cool on avait trop de source ^^. On va attendre un peu pr etre sur mais je trouve que YWTCH et ses copains mettent du temps a revenir ...

**Comment by razorex** [comment]
trop de sources............

**Comment by TmpName** [comment]
Lol, me dis pas que tu te sert des 40/50 ?

**Comment by razorex** [comment]
oupsssss non

**Comment by johngf** [comment]
you watch fonctionne avec les nouveaux lien'je pense les ancien sont perdus deffinitivement

**Comment by johngf** [comment]
mis dans trash
