### ISSUE TITLE
Marquer vue

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1414]
J'ai pas trouver la solution encore, j'ai corriger pour pas que ça bug mais le code ultime c'est que quand c'est addmovie ou addmisc ou addtv

```
        if cGui.CONTENT == "movies" or cGui.CONTENT == "tvshows":
            oListItem = self.createListItem(oGuiElement)
            isFolder = False
        else :
            oListItem = self.createFolderListItem(oGuiElement)
            isFolder = True
```
`
  xbmcplugin.addDirectoryItem(sPluginHandle, sItemUrl, oListItem, isFolder=isFolder)`

isfolder doit etre False pour que xbmc ne recharge pas toute la fonction mais le soucis c'est que l'on peux plus rien lancer derriere puisqu'il pante sur WARNING: Attempt to use invalid handle -1 certain addon y arrive mais j'ai pas trouver encore.

**Comment by TmpName** [comment]
Les warnings ne bloquent pas le code normalement ?

**Comment by LordVenom** [comment]
Ben si ça passe pas mais ça c'est un code en test pas celui envoyer pour résoudre le bug

**Comment by TmpName** [comment]
Heu, la je tape en touche, ^^, rien compris.

Le handle est sense etre int(sys.argv[1]) quand ca marche, avec un print int(sys.argv[1]) tu devrais voir la difference entre quand ca marche et quand ca marche pas, mais pr moi le prb ne vient pas de la.

**Comment by LordVenom** [comment]
Si c'est declarer en  isFolder = True ça fonctionne mais si c'est  isFolder = False ça me retourne -1

Hé ça serais pas mal de mettre les addmovie en False ça bug pas le W et ça reload pas la recherche a priorie il ont modifier un truc il aime pas trop qu'on mette des metas sur un folder True mais j'ai pas le choix pour le moment.

**Comment by LordVenom** [comment]
J'ai reussis a faire ceux que je voulais a tester, ont peux même penser a virer l'option marquer lu non lue de vstream celle de Kodi ne bug plus.

**Comment by TmpName** [comment]
Lol, jusqu'a la prochaine version ......
