### ISSUE TITLE
recherche visuelle

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#1416]
bonsoir je viens de remarquer que la recherche visuelle n'est plus en miniatures ? 
ça restera comme ça ou pas ?
perso je ne me sert pas de l'affichage vue personnalisée donc j'ai tout the moviedb en mode liste c'est embétant , j'ai pas envie de mettre les autres sites en mode miniatures

**Comment by LordVenom** [comment]
Change la vue Kodi vas s'en souvenir normalement.

**Comment by johngf** [comment]
oui mais je doit le faire manuellement pour chaque page c'est pour ça la question si ça reste comme ça je pourrais toujours ajouter le mode manuellement dans le script

**Comment by TmpName** [comment]
Exact ca deconne chez moi aussi.

**Comment by TmpName** [comment]
Bon impossible de voir ce qui a chnage depuis.
Donc j'ai mit une nouvelle fonction cachée qui sera en place a la prochaine MAJ
`oGui.setEndOfDirectory(500)`

**Comment by johngf** [comment]
bah en faite la ligne est commenté [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/themoviedb_org.py#L226)

**Comment by TmpName** [comment]
Oui mais ca fait un moment. Le prb ne vient plus de la. Depuis que l'user a la possibilites de choisir le mode de vu depuis les parametres de Vstream c'est gui.py ou guielement.py qui gere les vues.

Si tu decommentes, ca risque de ne pas marcher car juste apres la commande oGui.setEndOfDirectory() va te remettre la mauvaise vu. 

Mais je sais pas pkoi car marchait encore il ya quelques jours ...
Cette modif sur themoviedb remonte a plus d'un mois.

**Comment by johngf** [comment]
sur kodi 16.1 avec la master (via maj auto non bidouiller) j'ai décommenté la ligne ça fonctionne correctement
le soucis viens de kodi 17 ?

**Comment by TmpName** [comment]
@LordVenom est en train de reparer le truc avec les vus/non vus.

Sinon ma modif ne marchera que apres la MAJ mensuelle, suffira de rajouter entre parenthese 500 dans la fonction oGui.setEndOfDirectory() . Et elle marchera a chaque fois que tu feras cette modif, faudra modif dans showmovies, dans showtrucs dans showmachins du fichier themoviesdb.py.

**Comment by johngf** [comment]
ça fonctioné bien avant je suis pas sur que bcp de monde utilise vue personalisée

**Comment by TmpName** [comment]
Ben si mais pour d'autres sites (y en a qui aiment bien les grosses affiches alors que moi je prefere le mode liste). Et en option tu as juste films/serie/normal rien de special pr themoviesdb, donc ca ne peut pas marcher, c'est pour ca que j'ai rajoute cette option cachée (a ne pas utiliser pr les autres sites) juste pr le forcer pour le site themoviedb.

Par contre je sais pas pkoi ca marchait avant, apres le bug de @LordVenom  a demande pas mal de modifs.

**Comment by LordVenom** [comment]
Je comprend pas l'idée la..  

- Si l'option des vue n'est pas activer effectivement decommenter la ligne dans themoviedb résout le problème.

`if (cConfig().getSetting("active-view") == 'true'): `

Je pige pas vous aimer le mode liste mais pas pour themovie c'est pareil.. pas d'affichage hors standard c'est encore un coup a buguer tout ont n'a déjà tous virer une foix ont vas pas recommencer encore.

**Comment by johngf** [comment]
c'est exactement ça "mode liste" pour les autres sites et the moviedb "mode miniatures" (recherche visuelle)
ça permet de naviguer plus rapidement via next page en se fiant au image

**Comment by LordVenom** [comment]
ben la correction de @TmpName  fonctionne aussi.

**Comment by Arias800** [comment]
Peut être que la 17.3 fixe le problème car la 17.2 a été déployer dans l'urgence pour colmatée la faille des sous titre

**Comment by TmpName** [comment]
De decommenter la ligne ne marchera pas (enfin pas toujours), regardes le code de oGui.setEndOfDirectory().
Si tu decommentes, ca va changer le mode d'affichage mais selon les reglages de l'user Vstream va encore les rechanger juste apres.

Apres sa s'apelle recherche "visuelle", pour moi si on vire le cote poster ca sert plus a grand chose, je pense vraiment que 95% des users qui utilisent cette fonction veulent le cote flashy des fanart. Et dans la config on ne peut pas choisir, il n'y que film/serie/defaut.
J'ai laisse cette option discrete justement pour eviter que tout le monde fasse pareil dans les autres fichiers site pour eviter les bugs.

**Comment by johngf** [comment]
oui surement mais j'utilise pas les reglage perso donc chez moi c'est ok apres je pense comme toi sans les poster aucun interet

**Comment by LordVenom** [comment]
Encore un bug marque vue, mais c'est en cours pause pour aujuord'hui remplacement de tout les 

oOutputParameterHandler.addParameter('type', 'film')
oOutputParameterHandler.addParameter('disp', 'search_1')
oOutputParameterHandler.addParameter('searchtexte', 'stitle')

ect..

Par des variables xbmcgui.Window(10101).setProperty() ça resoud le probleme car les variables ne sont pas soumis au rechargement pour être enregistrer par Kodi.

**Comment by TmpName** [comment]
Nope, pas encore teste, j'attendais que tu ais fini ^^.

Par contre, ton dernier post me fait peur ? Tu as l'intention de faire ces remplacement dans tout les fichiers ?
oOutputParameterHandler.addParameter est quelque chose de sur, c'est comme ca que kodi passe des parametre depuis sa creation et ca ne va pas bouger. tandis que xbmcgui.Window(10101).setProperty() tu es pas a l'abris qu'il modifient ca a la prochaine version, c'est plus un hack qu'une fonction faite pour ca.

Faut vraiment trouver une solution globale. pas possible de desactiver le vu/non vu sur les pages a probleme ?

**Comment by LordVenom** [comment]
Juste ceux que j'ai mentionne, les paramètres oui mais il ne prenne pas en compte la popup. d'ou le rechargement a chaque foix il faudrais faire la popup sDisp avant de choisir le film pour virer l'erreur et ça vas clairement pas le faire, donc meilleur solution setProperty qui existe depuis un bout de temp et je pense pas qu'il le vireront un jours.

**Comment by johngf** [comment]
je suis sur la 17.3 confluence avec la beta je viens de faire une recherche je clic droit sur un dossier le menu est enorme 
vu quand mettant isfolder= false ça rajoute les entrées des fichier playable au menus

**Comment by LordVenom** [comment]
Oui mais non si y a des metas ont doit mettre False pour setinfo, ça fonctionner bien avant mais plus maintenant.

**Comment by johngf** [comment]
j'ai pas tous suivis mais c'était quoi le probleme avec les métas je viens de test en mettant isFolder=false 
ça a l'air ok
sachant que j'utilise pas les métas d'habitude

**Comment by LordVenom** [comment]
Le soucis du Realod vient d’ailleurs je vient de le corriger par contre la raccourcis W marquer lu de Kodi plante si y a pas addinfo et si le folder et pas false enfin d'apres ce que j'ai pus tester.

**Comment by johngf** [comment]
Mais avec la telecommande ou clic droit je l'ai jamais vu planté bizarre

**Comment by TmpName** [comment]
Moi ca faisait une boucle sans fin, mais j'ai pas teste la derniere version encore.
C'est fini la ? on peux tester ?

**Comment by johngf** [comment]
oui il ya juste le menu qui a des truc qui devrait pas y etre

**Comment by LordVenom** [comment]
Oui c'est fini pas encore full tester mais vite fait c'est bon lol

**Comment by TmpName** [comment]
Bon plus de bug si je presses W apres avoir fait une recherche, mais laisse tomber le bordel, juste pr afficher un petit "v" oblige de recharger la page, bvo la team kodi, pas moyen d'utiliser le cache en plus je pari vu que les infos ne sont plus les memes juste pr ce signe ?

Sinon wé je trouve comme @johngf que le menu est devenu monstrueux ...

Edit:
Nouveau bug ^^
Faire une recherche, prendre une serie, menu contextuel en prendre "lire a partir de cet episode" > boucle sans fin.

**Comment by TmpName** [comment]
Franchement ca devient le bordel.

Moi ce que j'aurais fait c'est que en cas de refresh provoque par "marque vu" >> page vide (ou erreur).

Plutot que de faire en sorte que ca marche, empecher de le faire.

**Comment by LordVenom** [comment]
même les recherche direct sur les soucrces reload ... il ont modifier leur cache c'est c..

**Comment by TmpName** [comment]
Lol, te prend pas la tete, si ca se trouve a la prochaine MAJ ils vont encore changer ca.
Moi je remettrais comme avant et je garderais le code que tu utilises pr les refresh, et je bloquerais tout si refresh en recherche.
Je ne vois aucune raison pr avoir un refresh lors d'une recherche, surtout que vu le temps de generation de la page, c'est mise en cache obligatoire donc pas de refresh.

Dit toi que moi j'ai fait pire, j'ai essaye d'avoir de l'aide via leur support, honnettement maintenant je trouve mon bureau de poste tres performant compare a eux.

**Comment by LordVenom** [comment]
Bon pour aujourd'hui stop.De voir la recherche des sources direct planter ça ma plomber serieux.

**Comment by TmpName** [comment]
Fais comme moi, prend un autre pseudo, c'est dingue comme il ont vite un stereotype en tete.

"Quelle heure est il ?"
"On te repond pas mechant pirate qui vole ceux qui travaille dur".

**Comment by johngf** [comment]
pour le bug  "Lire a partir de cet épisode" c'est normal en mettant isFolder=False kodi croit que les dossiers de la page (ainsi que les sous dossier) sont des épisode a la suite (fichier playable)
normalement isFolder doit etre True pour les dossiers et les options cité plus haut non présente dans le menu popup

**Comment by LordVenom** [comment]
En faite a chaque popup la page dans la mémoire de Kodi n'est pas la bonne puisqu'il n'y a pas searchtext
En gros la solution c'est de demander le texte via popup puis de recharger l'url en inserant searchtext dans l'url mais ça vas demander pas mal de modif.

**Comment by LordVenom** [comment]
Bon j’arrête la moi. Il faut un cerveau plus intelligent que moi je passe trop de temps dessus pour rien chaque modif fait buguer un autre truc.

**Comment by TmpName** [comment]
Ben moi j'ai meme pas essaye ^^.
Mais si je m'y colle ce que je ferais, je recupere une partie de ton code qui te permet de savoir si il ya un refresh ou pas.
Je remet tout comme avant et dans la page defaut.py (si c'est bien elle qui est appelle a chaque fois) un gros retturn pr avoir une page vide si le mec a provoque un refresh de kodi lors d'une recherche.
Tout fonctionnera comme avant et plus de boucle sans fin.

**Comment by TmpName** [comment]
Un autre prb, on est 3 a trouver que Vstream est ralenti avec ces modifs

**Comment by Kodigoal** [comment]
4 lol j'ai maj beta chez moi  , et depuis quand j'ai la popup qui liste les films sur une source par exemple , ca met 15ans a disparaitre la popup genre en fondu au ralenti ^^ 
Pas trop regarder les fichiers maj pour voir d'ou ca venait.

**Comment by johngf** [comment]
moi pareil sur mon nuc

**Comment by TmpName** [comment]
Vous reproduissez ce bug comment ?
Sinon @Kodigoal si tu as 5 mn essayes avec ces 2 fichiers stp https://github.com/TmpName/Fichier_en_vrac/tree/master/versiontest

**Comment by johngf** [comment]
bah tu la popup qui te dit le nombre elle reste plus lontemps qu'avant sur la master

**Comment by TmpName** [comment]
Arf, pas visible sur ma machine (windows, kodi V 13.1)

**Comment by johngf** [comment]
faut tout remettre comme avant a mon avis

**Comment by TmpName** [comment]
Ben teste les 2 precedents fichiers.
Compare les fichiers avec l'ancienne version master, normalement a part le blocage que j'ai rajoute, c'est tout comme avant enfin pr la gestion des pages, les modifs utilent je les ai laisse.

Mais j'ai pu virer 1 truc utile ou au contraire oublie de virer quelque chose.

**Comment by johngf** [comment]
je parle de toute les modifs recente is folder false alors que c'est des dossiers etc...

**Comment by TmpName** [comment]
Ca en fait partie. Ca j'ai remit comme avant, sauf sur la page des recherches ou justement je le force, tout le reste est comme avant.

**Comment by Kodigoal** [comment]
je test ca plus tard ^^

**Comment by Kodigoal** [comment]
Testé ok , plus de ralentissement popup ou retour en arrière listage showmovie showhoster xD
Ya autre chose à tester comme bug/ ralentissement ?

**Comment by TmpName** [comment]
Bon ok alors soit
- isfolder = false, et du coup les liens ne sont plus cliquable
- isfolder = true, et du coup ce con considere que c'est un repertoire donc charge tout les liens qui sont dedans puis tout les liens qui sont dans les precedents liens et ect ....

Et pas d'option pour bloquer ca. Put1 mais sont con ou quoi ?

**Comment by TmpName** [comment]
Si on clique sur le lien on lance une url
Si on appuis sur W ca lance exactement la meme url avec les memes parametres (meme si ca ne chnage pas l'affichage).
J'ai beau tester tout les parametre 1 par 1, que ce soit le clik normal ou la touche W, c'est la meme page actuellment a l'ecran, c'est la meme qu'on desire, c'est le meme nbre de page, ect ....

Je pense que c'est impossiblke tout simplement, le mec clique une fois sur W , redemarre son ordi et ne le refera plus.

Sujet clos.

**Comment by Kodigoal** [comment]
xD je comprend pas tout mais on fait quoi alors pour que tout refonctionne comme avant  ? pas de touche W via android

**Comment by LordVenom** [comment]
Ben la modif de @TmpName  c'est comme avant sauf le blocage du refresh mais pour la creation des dossier c'est pareil, c'est kodi qui a changer pas vStream.

**Comment by Kodigoal** [comment]
Oui mais cliquez sur les liens après une recherche ne fonctionne plus , avant que je maj beta tout était ok de ce côté là aussi... ou j'ai loupé un épisode ^^ pas trop suivi les modifs ses derniers temps ...

**Comment by TmpName** [comment]
Yep ca c'est ma faute @Kodigoal, la version en ligne est encore en test.
Je vais remettre en ligne sur le beta, la version complete normallement comme avant les modifs (et donc fonctionnelle)

Le bug sera toujours la, mais il reste une place dans la chambre ou @LordVenom et moi sommes soignes pr depression si tu veux tenter ta chnace ^^ ?

**Comment by TmpName** [comment]
En ligne, par contre je garantis rien, y a un put1 de mixage de versions .....

**Comment by Kodigoal** [comment]
xD Je suis pas loin de vous , étage en dessous ,  je crois que je suis dans une sorte de coma , mais je peux entendre le docteur Estuary qui explique à mes proches que mon cerveau a pas supporter la lecture de  l'issue:
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1427
Dès que je me réveille , rdv à la cafette ^^

ok merci vais tester.

**Comment by TmpName** [comment]
Haa !!!
C'etait ca les grognements qu'on entendait en bas.

Mefis toi du docteur.
