### ISSUE TITLE
Libertyland vide

### ISSUE THREAD

**Issue by spiralemystik** [Kodi-vStream/venom-xbmc-addons#1420]
Bonjour,

Un enorme merci pour tout le travail, vraiment un grand bravo.
Tout le contenu de Libertyland apparait vide depuis quelques semaines.
Pouvez-vous y jeter un oeil.

Merci d'avance

**Comment by johngf** [comment]
oui ils ont changé de fonctionnement

**Comment by johngf** [comment]
bon en verité le il faudrait entierement le refaire pour prendre en compte les liens avec hébergeur spécial mais bon ....
la j'ai commencé une modif reste les anims, l'affichage de la langue, optimisé un peu tous ça

**Comment by TmpName** [comment]
Lol, ha wé ils ont decide de remettre leur site a jours ?
Perso j'ai tjours eu des prbs avec eux.
