### ISSUE TITLE
Version 0.5.3

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1427]
Bug : Si vous recherchez plusieurs fois le même titre, vous avez plusieurs entrer dans l'historique.

Correction : Veuillez effacer le cache de l'addon

Pour cela voir Clear cache addon dans le Wiki https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by johngf** [comment]
bah c'est pas vraiment un bug et on peut supprimé les deux en n'en supprimant un

**Comment by TmpName** [comment]
Ce qu'il veut dire c'est qu'il a corrige le bug, mais pour que ca marche il faut supprimer l'ancienne table, la nouvelle gere le probleme.
Je viens de voir la modif.

**Comment by LordVenom** [comment]
Perso c'est un truc qui me gonfler mais j'ai jamais eu le temp lol

**Comment by TmpName** [comment]
A part que chez moi ca lance une boucle sans fin lors du refresh.

Je deconne bien sur ^^.

**Comment by LordVenom** [comment]
Même pas drôle :'( lol

**Comment by johngf** [comment]
pour certains hosters hs peut etre définitif pour exa share et all vid  pour you watch je suis tombé sur des videos qui fonctionne parfois
[ici](https://twitter.com/hashtag/exashare?lang=frl)

**Comment by TmpName** [comment]
C'est clair que pr l avenir de ces 3 hosters je trouve pas d'infos, je sais pas si ils vont mettre cle sous porte ou quoi.

**Comment by johngf** [comment]
j'ai mis exa et all vid en trash j'hésite pour you watch en trash je ne trouve plus aucune vidéos playable

**Comment by TmpName** [comment]
Pour youwatch leur site est encore en route, donc ils vont peut etre repartir, pour les autres ...

**Comment by johngf** [comment]
Non marche pas erreur dans le log pour ça mis dans trash

**Comment by johngf** [comment]
@TmpName  si tu peux teste l'affichage des genres toutes les sources strea miz co genres avec ces fichiers https://github.com/johngf/divers/tree/master/subopload
c'est un début du code (avec du code qui devra sans doute etre déplacé et optimisé) mais normalement tu va voir la différence de vitesse d'affichage
pour les dossiers static ça peut etre utile genre home sources etc...

**Comment by TmpName** [comment]
Bon alors alors deja, la difference de vitesse est incomprehensible, mais c'est vraiment notable.
J'en connais un qui va paniquer, mais ca vaudrait presque le coup de modifier le coeur de Vstream pr fonctionner avec cette nouvelle methode.
La transition va etre bordelique, mais franchement j'ai fait des tests avec juste des liste de liens en me disant que tu exageres, et non, c'est vraiment plus rapide dans tout les cas visible a l'oeuil nu.

Faut voir ce que @LordVenom en pense, mais si on integre ton code, prevoir qu'il remplace l'ancien.

Sinon pour ce qui est des genres, tu vas galerer sur certain sites pr generer l 'url a partir du genre.

**Comment by johngf** [comment]
Oui a adapté ou pas possible ou galere pour certains sites je verrai

**Comment by TmpName** [comment]
Sinon en facile, ya les recherche alphabetique aussi, au pire une modif pour 0-9 qui chnage sur certains sites mais apres c'est pareil.

En passant l'optimisation de ton code est impressionnate.

**Comment by razorex** [comment]
@johngf j'ai vu que tu liste les années a partir de 1926 dans "util" il y a des sites qui propose à partir de 1913.. et du coups mon affichage des "quantités" exit. et qu'entend tu part #utilse le nom pour l'url donc doit etre correct parce que certains sites ont des fautes d'ortographes dans leurs url ex: un site (de mémoire) écrit espionage et pas espionnage

**Comment by johngf** [comment]
@razorex oui j'ai vu on peut le changer pour les fautes ça peut etre corriger c'est un premier jet le code

**Comment by razorex** [comment]
donc si une fois unsite mais documentaire et un autre documentaires faudra rallonger ta liste dans util????

**Comment by johngf** [comment]
Ajouter un genres spécifique ou a voir autres methode donne moi le site si tu le connais

**Comment by TmpName** [comment]
Perso, je le sens moyen aussi, y a  plein de sites avec des variantes, streamingk
liste.append( ['Emissions TV',URL_MAIN + 'category/emissions-tv/'] )
liste.append( ['Comédie Dramatique',URL_MAIN + 'category/films/comedie-dramatique/'] )

La tu t 'embarques sur le meme bateau que @LordVenom et son refresh buggué ^^.

**Comment by razorex** [comment]
c'est qu'une hypothèse. si un site propose un genre drama mais faut que je trouve lequel..

**Comment by johngf** [comment]
J'y ai pensé justement tous a l'heure me suis dit ceux il vont etre chiant mais pas impossible le code va changer il est beta beta beta

**Comment by TmpName** [comment]
Par contre @LordVenom, si tu passes par la, regardes les fichiers a @johngf sur la fonction optimisée stp.

**Comment by laquarico** [comment]
Bonsoir j ai un problem avec vstream...aucun stream ne marche et je suis toujours sur la version 5.0.0 l addon ne se met a jour....quel est l url du repo svp si quelqu un pouvait m aider car je ne peux plus rien regarder...merci

**Comment by johngf** [comment]
C'est sur la page d'acceuil telechargez le repository [Ici](https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository)

**Comment by laquarico** [comment]
Merci et juste pour info la plupart des sources ne fonctionnent pas?
Exashare,vidup,youwatch et autre.... j arrive plus a avoir goldorak et
olive et tom entre autre....

**Comment by johngf** [comment]
regarde la #1433

**Comment by laquarico** [comment]
Je void merci

**Comment by TmpName** [comment]
Goldorak je viens de le tester sur kaydo.

**Comment by johngf** [comment]
Certain site le utilise le nom japonnais

**Comment by laquarico** [comment]
Merci c est la version francaise? Kaydo c est un server sur vstream? Je
vais voir ca ce soir

**Comment by TmpName** [comment]
C'est quoi le nom Japonis ? ^^

**Comment by laquarico** [comment]
Ufo robot grendizer j ai essaye la recherche dans kaydo mais sans succes

**Comment by TmpName** [comment]
Avec "goldorak" y a 3 saisons.

**Comment by laquarico** [comment]
Je pence que j ai trouve merci c est sur une nouvelle source que je n avais
pas avant

**Comment by johngf** [comment]
@TmpName quel est la différence entre appeler oGui = cGui() ou cGui() direct ??

**Comment by TmpName** [comment]
Dans le premier cas, tu ne cree qu'un seul objet, et c'est le meme que tu utilises tout le temps.
Si tu changes self.CONTENT, a un moment, il sera modifie pour tout les suivants.
L'initialisation ne se fait que lors de la creation de l'objet (if cConfig().isKrypton(): ne se fait que a ce moment).
A chaque appel a une classe (je sais plus laquelle), searchResults est modifie, y a un truc de rajoute.
Et je crois que c'est tout pour cGui(), c'est pas l'objet le plus utile de Vstream.

Si tu met cGui() a chaque fois, tout recommence a zero a chaque ligne, car un nouvel objet par ligne.

**Comment by johngf** [comment]
C'etait pour savoir si vaut mieux appeler direct une fonction avec () ou non pas neccesairement ogui
Et j'ai commencé un truc le menu home de vstream en light (static)  pour l'instant sans langage ni deco ni config 
et j'ai remarqué en bidouillant des config() partout des fois 2 fois sur la meme ligne addir juste pour le titre

**Comment by TmpName** [comment]
Pareil, et quand je pense juste a l'initialisation de l'objet, ca me fait peur niveau perf.

Pour le moment, meme si on a pas l'avis de @LordVenom, je pense que refaire le coeur c'est mort ^^. La, il doit encore faire des cauchemar avec le bug refresh, et il sait pas encore qu sa ralenti le fctment.

Par contre commencer a rajouter tes fonctions dans le coeur ca doit etre possible ? Car meme si utilise sur juste une dizaine de pages, ca vaut vraiement le coup.

**Comment by johngf** [comment]
Bah je suis repartis de zero pour pas m'embrouillé nouveau main home gui sitehandler pour l'instant c'est en cours...

**Comment by LordVenom** [comment]
Houla je sais pas à quoi repondre, clairement oui le bug refresh me gonfle, j'ai pas la tête a tous refaire ni l'envie clairement.J'attend de voir si l'un d'autre vous en regardant auras l’illumination qui ma manquer.

Pour le code de @johngf  c'est pas comparable pas de prise en compte des metas, des fanarts de dossiers des couleurs auto. c'est du texte brut donc oui plus rapide.

**Comment by TmpName** [comment]
Ben perso si je m'y penche, je repars comme c'etait avant (version officielle), et je bloque le refresh (page vierge), pas envie de passer 15jours a essayer de reparer leur bordel qui risque de chnager a la prochaine MAJ. Si tu es ok avec ca ? Mais du coup si je trouve quelque chose, tout ce que tu aura fais sera perdu (je comprend rien au code, je sais meme pas si je peux laisser ou pas)

Sinon, si le code de @johngf peut tout gerer, mais faut tout refaire, en fait le truc c'est que a l'origine on rajoute chaque ligne une par une, alors que lui les ajoute a une liste qui est rajoutée d'un coup. Je sais pas pkoi c'est plus rapide, c'est les memes manip, a mon avis c'est du a une mauvaise optimisation du code de kodi, mais le resultat est la. On commence a mettre des prototypes en place pour quelques pages et on avisera plus tard.

**Comment by johngf** [comment]
j'ai un question bete  dans les fichiers site >> site desc << est visible dans vstream ?? je trouve pas

**Comment by TmpName** [comment]
C'est pas le resume ? Ca apparait que sur certain site avec certains affichages.

**Comment by johngf** [comment]
j'ai essayé toute les vues + touche o i rien

**Comment by TmpName** [comment]
Site : Full strm
Vue : information du media

**Comment by johngf** [comment]
je l'ai pas avec la beta et kodi 17,3 vue  infomedia seulement sur les films pas de description du site

**Comment by TmpName** [comment]
J'ai aussi la beta ??
Ca apparait pour les films justement, c'est le resume du film. Meme si ca sert pas pour la page home ca servira pour autre chose, j'attend de voir ce que tu vas faire mais je pense qu'on va pouvoir utiliser les memes fonctions qu'actuellement

oGui.addTV > rajout dans la liste
oGui.setEndOfDirectory() > envois tute la liste d'un coup.

**Comment by johngf** [comment]
je fais le maximum pour la compatibilité mais avec vstream je confirme je ne l'ai pas
SITE_DESC = 'blabla' au début du fichier site

**Comment by TmpName** [comment]
Ha merde, le truc en debut de fichier ? C'est pour afficher une description dans certain dialog de config, eg choix des sources. rien a voir avec ce a quoi je pensais.

**Comment by johngf** [comment]
en regardant bien le code je vois des truc bizarre ex [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/default.py#L188) demande le text alors qu'il est tapé ligne 205

**Comment by TmpName** [comment]
Y a pas un rattage ?
Moi en ligne 205 j'ai
`sSearchText = oHandler.setText(sSearchText)`

Sinon via oInputParameterHandler.getValue c'est la vielle methode
et via xbmcgui.Window(10101).getProperty la nouvelle
Mais suis pas fan des dernieres modifs.

**Comment by johngf** [comment]
non c'est ça ohandler ouvre le dialog

**Comment by TmpName** [comment]
Ben c'est bon non  ? Il recupere la valeur passée en parametre ou via les propriete, et il s'en sert pr ouvrir le dialog avec cette valeur.

**Comment by johngf** [comment]
sinon je galere un peu pour le resultat final vstream est tellement configurable a souhait qu'il verifie xxx fois a chaque affichage 
-si ceci est activé ou non pour home 
- le language ,le titre
- verifie le nom du dossier au cas ou l'user a changé le noms du dossier Films en Filmblabla (utile ?)
- pareil pour les sites activé ou non ça plus vite de les affichées que de verifs 
  je veut bien qu'il ne soit pas pris en compte pour la recherche mais pour l'affichage

**Comment by TmpName** [comment]
Pour moi affichage de la page home en mode vignette. Apres tout par defaut je pense.

Le fan art de la page home est defini par vstream, non ?

> verifie le nom du dossier au cas ou l'user a changé le noms du dossier Films en Filmblabla (utile ?)

Tu parles de la librairie ?

> pareil pour les sites activé ou non ça plus vite de les affichées que de verifs
> je veut bien qu'il ne soit pas pris en compte pour la recherche mais pour l'affichage

La tu parle de la selection des sites dans le menu ou de "toute les sources" ?

Mais tu refait tout l'addon la ? ^^ je croyais que tu voulais juste accelerer l'affichage de la page home pour commencer.

**Comment by TmpName** [comment]
Pour ces verification sur la pahe home si tu veux acceler tu fait des le debut et une seule fois.
`oConfig = cConfig()`

Si apres dans les fonction tu fais oConfig.getlanguage() ca va aller beacoup plus vite.

**Comment by johngf** [comment]
pas l'addon entier mais ce qui est avant juste avant les sites page  default.py home.py et je ne compte pas appeler config j'ai ajouté la fonction getsetting et getlanguage dans util

**Comment by TmpName** [comment]
Tu te prend la tete pr rien, si tu as deja mis une fonction getsetting dans util sert toi en, c'est pas enorme en perte de perf et le seul moyen de faire mieux c'est de recup tout les infos de config en 1 fois, impossible avec kodi et un fichier xml.

**Comment by johngf** [comment]
ça tiendrait qu'a moi j'aurais enlevé cet fonctionnalité de personnalisé home

**Comment by TmpName** [comment]
Lol, a un moment @LordVenom voulait virer les couleurs, il a commence, mais il en a laisse.
Apres moi j'aime bien ca me permet d'avoir pile un affichage de 3 * 5 vignettes, en virant ce qui ne me sert pas (bon la y a pas besoin, mais ca me servira :) )

**Comment by johngf** [comment]
En tous cas ce que j'ai commencé c'est fast et ça m'embete de l'allourdir pour un truc pour sur peu utilisé
Je test integré la recherche mais ça m'embrouille un peu avec disp type et readdb qui par true de home pour etre mis false dans searchglobal

**Comment by TmpName** [comment]
Y a eu une modif, tu peux chosir le nom que tu veux "vieux film" "films" "mes films" mais tu n'as qu'un choix limite pour les types, dans le fichier site, type = "mes films" est impossible, ou alors y a un probleme.

Pr la recherche, laisse en attente, si @LordVenom valide le retour en arriere y a des trucs qui vont sauter.

**Comment by johngf** [comment]
oui je me suis trompé mais je pense qu'il faudrait figé les type non ? film c'est film pas docus

**Comment by LordVenom** [comment]
@TmpName n'attend pas sur moi, c'est toi le patron :) comme je l'ai dit considérer moi en vacance.

**Comment by johngf** [comment]
bon en faite je mis prenais mal pour getsetting j'utilisé xbmcaddon qui a aussi la fonction getsettings au lieu xbmcplugin (plus rapide) 
et pour la getlanguage ça va c'est imperceptible le fichier et loader par kodi au démarrage donc en memoire

**Comment by TmpName** [comment]
Bon ben vu que le boss est en vacances j'en profite, je vais tenter un rollback avec un patch de bourrin pr le refresh. 
J'ai une photo de la team de kodi avec des flechettes et un tube d'aspirine, je me lance.

**Comment by johngf** [comment]
vous en pensez quoi de mettre l'historique dans un dossier propre qu'il ne soit plus afficher quand on clique sur recherche mais en cliquant sur votre historique ?

**Comment by TmpName** [comment]
Moi suis pour.
Ca sert peu, en general, une fois la recherche faite, je met en favoris, tres rare que ca me serve de l'avoir affiche sur la meme page, par contre au bout de 20 recherches, je pete un cable et supprime tout car ca prend trop de place.

**Comment by johngf** [comment]
Bah pour film on peut mettre type serie docu  et inversement dans les parametre de vstream

**Comment by TmpName** [comment]
Bon apres plante kodi au moins 10 fois j'ai trouve une astuce
https://github.com/TmpName/Fichier_en_vrac/tree/master/versiontest

Normallement, il y a assez peu de modif, j'ai pas encore teste mais ca a la'ir de marcher, et avec l'ancienne methode.
Je rajoute un parametre dans tout les items qui apparaissent sur la premiere page de la recherche (vu que c'est la seule qui buggue). Et si on se retrouve avec un refresh, ca le lance 1 fois, le parametre disparait et du coup tout les refresh suivant sont bloque.

En fait ca bloque tout les chargement si
- on est sur la premiere page de recherche.
- pas de parametre special dans l'url.

**Comment by TmpName** [comment]
Edit: Bon en fait ca marche tant qu'on reste sur la page ^^

Si 10 mn apres on chnage la page, ben kodi reprend ces mise en "vu/non vu", c'est pas beau ca ?

**Comment by johngf** [comment]
De mon coté j'ai modif default il n'est plus comme il est la (presque) mais comme j'ai pas encore integré la recherche global que je pense mettre ailleur j'ai pas pu testé le bug refresh

**Comment by johngf** [comment]
@LordVenom  avais parlé d'un probleme de cache en faite sur kodi17.3 si tu lui dit pas de le mettre en cache il ne le fait pas (pas de fichiers .fi créé) donc cachetodisc=true

**Comment by TmpName** [comment]
Ca j'ai laisse, c'est dans le fichier gui, je suis pas reparti a zero, j'ai juste supprime quelques lignes.
Pour la recherche je lui ai pose la meme question , et je me souvient plus de son explication mais y avait une bne raison pr le mettre dans defaut.py plutot que la ou c'etait avant.

**Comment by johngf** [comment]
bah peu etre que c'esst parce que toute fonction passe par default en premier 
tu connais une alternative a oOutputParameterHandler.addParameter ?
comme je traite par liste ça fonctionne pas ou alors faudrait extraire les params pour les remettre dans
chaque objet de la liste ...

**Comment by LordVenom** [comment]
pour faire simple outpout c'est l'url de xbmcplugin.addDirectoryItem

l'input c'est  qui ce trouve dans sys.argv.

**Comment by johngf** [comment]
je connais pas  xbmcgui.Window(10101).getProperty je vais voir

**Comment by TmpName** [comment]
oOutputParameterHandler.addParameter on ne peut pas s'en passer, comme le dit @LordVenom c'est l'url qui est passe a chaque page, c'est fait pour.
Il y a des fonction pr convertir les liste en parametres, mais c'est pas normal que tu ais d'autres parametres a faire passer ? Les seuls truc a passer son le titre, l'url, la fonction et en bonus thumb ou 2 /3 truc exotique pr certains sites.

Sinon j'ai une version qui marche sans refresh 
https://github.com/TmpName/Fichier_en_vrac/tree/master/versiontest

Alors la j'ai desactive une partie mais qui est reactivable. Sans la partie ca recharge le page de recherche (et c'est long) mais plus de blocage, avec ca bloque tout.

**Comment by johngf** [comment]
bah pour la recherche ou l'historique vstream ajoute des truc genre [](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/home.py#L384)

**Comment by TmpName** [comment]
L'ordre n'a pas d'importance, et python a aussi une fonction pr virer les doublons d'un tableau.
Il y  aussi la fonction update() au lieu de append(), si ca existe c'est remplace sinon c'est rajoute, mais j'ai tendance a confondre liste dict et tuple.

**Comment by johngf** [comment]
bon j'ai trouvé une parade grace a getParameterAsUri 
donc j'envoie soit l'url format "siteUrl=blabla" soit le OutputParameterHandler transformé par getParameterAsUri est c'est ok

**Comment by laquarico** [comment]
Bonsoir je recois vos feed et je devine que vous etes codeur.. j ai une
question je suis en uk et je voudrai savour si il y avait une bonne addon
pour la tele francaise live....merci

**Comment by LordVenom** [comment]
@johngf  y a des function dans le gui afficher la bande annonce et les recherches similaire il me semble qui sont mal placer je sais mais bon...

@laquarico , je sais pas je n'utilise que vStream :)

**Comment by laquarico** [comment]
@lord venom j arrive pas a avoir la tele francaise sur vstream. J ai besoin
d un VPN?

**Comment by Kodigoal** [comment]
vpn ip francaise + molotov tv appli pc /ios / android

**Comment by laquarico** [comment]
Merci

**Comment by johngf** [comment]
les chaine sont hs les trois quart du temps sur vstream les liens ne dure pas
enfaite faudrait faire comme pour les fichiers sites récup les liens sur des sites internet via requete

**Comment by laquarico** [comment]
En fait faudrai une list m3u a changer tout les jours c est pas mal de
boulot surtout que je suis un novice et ne connais rien en codage j ai un
site pour les playlist m3u mais je sais pas quoi en faire apres mdr

**Comment by johngf** [comment]
@TmpName avec la beta d'aujourd'hui tu peux test [ici](http://www86.zippyshare.com/v/tK5SWAWB/file.html
) je n'ai pas intégré la recherche mais ça fonctionne si tu rajoute la fonction (searchglobal) dans default.py avec ces import
 - le dossier est a mettre dans resources et le defaut py dedans a la place de l'autre
 - pour about c'est juste une optimisation en test

**Comment by TmpName** [comment]
Je reconnais plus le code ^^.
Bon ca va me prendre du temps pr les tests, tu pourrais pas fusionner ta version avec l'officielle ? Ca va pas la ralentir, ca permettra d'aider pour la transistion, et surtout Vstream pourra continuer a fonctionner chez moi :) .

Alors mes premiers retours.
- heureusement que tu as mit une aide en com.
- beacoup moins redondanta
- Vaudrait mieux utiliser "misc" au lieu de menu. A moins qu'il y ait une difference de visuel, mais tv/movie/misc/next/text devrait suffir.
- Moi je preferais mettre la partie avec menu et submenu dans une classe a part, et dans un fichier commun, mais j'avous que vu le peu de code a mettre dedans, ca coute rien de faire comme tu as fais, ca vaudrait le coup si il y avait un remplissage auto, ou une gestion d'erreur, mais la ...
- oGui = cGui() a mettre dans la meme fonction que oGui.endOfDirectory() plutot que tout seul en haut, pas de difference niveau perf, mais plus clair et moins de prbs si on se retrouve a imbriquer les fonctions.

Moi ca me plait bien, le gros prb c'est que c'est dur a tester, faut vraiment faire en sorte qu'il y ait juste une ligne a toucher pr faire basculer les versions. On aura jamais fini pour la prochaine MAJ, et j'ai pas envis de refaire une beta beta sur un autre github.
Je vote pr mettre ta version desactivee mais complete dans le code actuel. 


Edit: 
et de faire
Fonction(("freebox", "load", VSlang(30115), "tv.png", "tv_fanart.jpg", "siteUrl=http://venom","XXX"))
avec xxx = tv/movie/misc/next/text
La du coup ca vaudrait le coup de faire une fonction pour eviter des repetition de code ?

**Comment by johngf** [comment]
pour l'instant je me suis juste concentré sur la page home ,les sous menu,toutes les sources,l'affichage de l'historique et des menus contextuels et que les fonctions au départ de home fonctionne ensuite ça bascule sur l'autre code

**Comment by TmpName** [comment]
T'inquiete pas pr quelques boucles, le python est assez optimise pour afficher un tableau (les API de kodi c'est autre chose).
Quand je bidouilllais l'interpreteur Javascript j'utilisait des fonctions qui mesures les perfs, nbre d'appel, temps en ms, ect ... C'est du natif python donc elle doivent etre avec Vstream. Mais c'est vraiement pr les fous.

**Comment by johngf** [comment]
niveau vitesse il y a une énorme différence tu ne vois presque plus en cours... sur kodi17,3 meme avec un historique de 80 recherche
sur kodi 16,1 je ne le vois plus du tout

**Comment by TmpName** [comment]
Yep mais niveau lisibilite c'est pas le top, et surtout on sait pas ce qui va se passer dans 6 mois, si on se retrouve a imbriquer les fonctions ca va deconner car se sera le meme oGui pr toute.
En le mettant dans chaque fonction ca rend le tout autonome, un gros copier/coller et tu deplaces tout.

**Comment by johngf** [comment]
pour la repet du folder je me suis rappelé pour quoi j'ai fait comme ça: 
le menu contextuel de l'historique de recherche est différent pour chaque entrée vu qu'on a besoin du titre pour savoir quoi effacé (qu'on récupère dans la boucle)

**Comment by TmpName** [comment]
Je vais tester sur un fichier site today pr tester les metas.

**Comment by TmpName** [comment]
Teste ca, juste le fichier gui.py a modifier.
Ca utilise ta methode mais avec tout le bouzins d'avant donc compatibilitee avec les fichier sites, metas, recherche, ect ....

**Comment by johngf** [comment]
Je peux pas testé la de suite mais " si une valeur est nulle provoque un crash "
Justement il ne doit pas avoir de valeur nulle d'ou le comment dans le fichier de la marche a suivre

**Comment by TmpName** [comment]
Nope, c'ette partie ne sert plus, tu peux la virer.
En fait avant si tu avais '' pour l'icone ou le fanart > plantage.
Mais a force de reduire, j'ai carrement integre ta methode dans addfolder, et du coup ca l'active pour addtv, addnext, adxx ,..

**Comment by LordVenom** [comment]
Ca résous le problème de refresh ?

**Comment by johngf** [comment]
non ce problème sera toujours la si on refresh la page vu que kodi ré-execute la fonction précédente
sur tous les refresh
le mieux c'est comme il y avait un moment le popup info comme quoi c'est marquer vu

sinon @TmpName je pige pas comment tu affiche le listing la fonction addSimpleFolder n'est pas appeller ?

**Comment by TmpName** [comment]
Tres simple pour assurer la compatibilitee avec les fichier sites.
1 - j'ai modifie la fonction addfolder (les fonctions que tu as dans addsimple folder sont dedans) du coup oGui.addTV rajoute dans la liste
2 - j'ai modifie oGui.setEndOfDirectory qui envois toute la liste a la fonction.
Peu de modifs et tout reste compatible.
Regarde ce comparatif https://www.diffchecker.com/WGltZUuh

Le prb de refresh est tjours la, et restera la, a mon avis c'est mort (j'ai explique pkoi je sais plus ou) . Le prb de refresh est bien celui de la touche W ou il est aussi ailleurs ?
Mais par contre en utilisant la methode de @johngf ca accelere l'affichage.

**Comment by TmpName** [comment]
En resume, tu peux remplacer le fichier gui.py par celui la.
Tout restera compatible et tu pourras utiliser la nouvelle methode sur toutes les pages de VStream (mais sans optimisation).
Je le teste depuis ce jours la sans bug encore.

**Comment by johngf** [comment]
j'ai compris mais quand je parlé des metas peut etre pas compatible avec cette methode plus haut j'avais en tete d'envoyer direct comme je fait la liste aEntry[1] d'un site pour voir si ça fonctionne méta activé

**Comment by LordVenom** [comment]
Ben vue que tu as reload le fichier default la recherche rebug.

**Comment by TmpName** [comment]
Tu peux pas envoyer direct une liste car il faut traiter au cas par cas, eg
1 er ligne du texte > pas de meta
2 - 10 lignes meta pour films
11  next page, avec un meta et menu special

Mais tu te prend la tete pr rien. Toi tu veux faire
1 - tout mettre en vrac dans une liste a partir d'un fichier site
2 - passer tout les items de la liste pr les traiter un par un et creer une deuxieme liste
3 - afficher la deuxieme liste

Fct actuel de Vstream
1 - Envoyer les element 1 par 1 du fichier site
2 - traiter les element en direct et les mettre dans la nouvelle liste
3 - afficher la deuxieme liste

Ca revient au meme.

Sinon c'est quoi le bug de la recherche deja ? Je viens de refaire un teste avec la recherche visuelle, pas vu de prbs.

**Comment by johngf** [comment]
c'est justement ce que je disais ça peut pas fonctionné enfin bref 
- pour le bug du refresh je pense qu'il faudrait diviser la recherche en 2 fonction
- la premiere qui cherche - la deuxieme qui affiche
 - le refresh ré-exécuterai seulement la fonction affichage

**Comment by TmpName** [comment]
Mais me souvient plus comment on provoque ce bug, c'etait pas en faisant back ?

**Comment by johngf** [comment]
Non c'est marquer vu ça recommence la recherche

**Comment by TmpName** [comment]
Et vous voulez faire quoi ?
1 - Empecher le refresh
Supprimer le xbmc.executebuiltin( 'Container.Refresh' )
> plus de refresh mais le signe "v" n'apparait pas
2 - Rafraichir la page, et la on peut eviter que ca redemande le titre mais dans tout les cas ca va repasser tout les sites 1 par 1 car on va pas memoriser tout une page de resultats.
3- laisser comme ca. Pour moi c'est completement idiot de marquer un titre de serie en vu. Il faudrait le marquer sur tout les sites et croiser les doigts pr rien ne chnage sur les urls. On rajoute un nouveau site et hop la serie apparait de nouveau en "non vu"

**Comment by johngf** [comment]
Oui le mieux c'est une popu info comme quoi c'est fait le v s'affichera plutard si tu repasse sur la page

**Comment by TmpName** [comment]
Moi je bloquerait l'utilisation, moins d'ennuis. et faisable avec 2/3 lignes.

**Comment by LordVenom** [comment]
Bon alors la !!!! Question test je suis refait, j'ai mis une version 16.1 de Kodi avec une version 0.3.0 de vStream hé ben j'ai la popup impossible mais vrai !!!

Bon ça deconne dans la recherche texte mais aussi dans la recherche visuelle.
La popup ne refresh pas le sys.argv et si je le force par un runplugin ça fait des truc bizarre.
un moyen de remplacer sys.argv[2] à la voler ? j'ai pas trouver.

1 : blocker les refresh
2: utiliser setProperty
3: supprimer les popups et remplacer par des menus 
Par exemple si je cherche avatar un dossier avatar çeras creer
Comme je clique sur un dossier avec un outpout searchtext:avatar par exemple le sys.argv searchtext=avatar seras présent donc pas de soucis pour le refresh (normalement)

**Comment by TmpName** [comment]
Mais calculez ce qu'il y a gagner et ce qu'il y a perdre.
Combien de personnes mettent des recherches en "marque vu", combien essayeront une seconde fois apres avoir du redemarrer kodi la premiere fois ....

Sinon il y a moyen de savoir quelle est la page actuellement affichée, si c'est la recherche globale ou la recherche visuelle, ok on lance la recherche, si c'est un resultat de recherche on bloque tout.

**Comment by LordVenom** [comment]
@TmpName  Oui ta modif et la plus simple et on voie deja la vitesse améliorer pourtant j'ai bien lus quelque par que 1 par 1 ou en liste était aussi rapide ils ont encore picoler chez Kodi lol

https://pastebin.com/ZcvZK3SY

Au plus simple pas tester partout.

**Comment by TmpName** [comment]
Et c'est juste avec la fonction decouverte pas @johngf, si tu rajoutes toutes ses optimisations (VSlang, ect ....) tu gagnes encore un peu.

**Comment by TmpName** [comment]
Et y a aussi le fichier defaut ici https://github.com/johngf/test/tree/master/default
Mais on peut pas le mettre tel quel, faut faire un mix des 2.

**Comment by TmpName** [comment]
Ha be non, y a plus.
Tu as vire les fichiers ?

**Comment by johngf** [comment]
Non ré organisé j'ai supprimer d'autre truc le dossier divers enfin je l'ai toujours sur mon pc

**Comment by TmpName** [comment]
Ben hier j'avais un peu de temps libre, je voulais commencer a refaire le fichier defaut.py et je trouvais plus le fichier.
En fait je voulais commencer a fusionner les 2 fichiers progressivement de maniere a garder tout fonctionnel et commencer l'optimisation.

**Comment by LordVenom** [comment]
Ont en est ou de toute c'est modif ?

**Comment by TmpName** [comment]
Ben y a plus ^^.
Et la je suis reparti sur un nouvel MMO, donc moins de temps libre.
Je pense qu'on peut cloturer cette issue, on recommencera pr la version suivante a la rentree.

Le bug est tjours la, mais pour moi c'est moins genant de laisser ce bug, que de tout compliquer pr le contourner (et non supprimer car impossible pr moi)

**Comment by LordVenom** [comment]
Ok, MMO ? Teso morrowind ?

**Comment by LordVenom** [comment]
- Correction bug refresh recherche global
- modification de la recherche sur tmdb
- modification du context (del voir marque-page-bande annonce)
- modification popup info bande annonce gerer par vstream.
