### ISSUE TITLE
Généralisation de recaptcha

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#1429]
salut
je n'ai plus eu trop de temps à consacrer pour contribuer ces derniers temps...
par contre, en jetant un coup d'oeil rapide je constate avec regret la généralisation progressive de recaptcha : ddl-island est mort car c'est intégré, libertyland est à moitié mort (car recaptcha est activé pour tous les liens de téléchargement, cad tous les liens de meilleur qualité)
si jamais ça continue ça va commencer à pas sentir bon :-(
je parle même pas du drame que ça va être si zt.ws l'active  

vous avez toujours pas vu de parade possible ?

**Comment by TmpName** [comment]
Pour ddl-island je viens de tester c'est encore possible sans recptcha.
Sinon lors de mes derniers tests j'etais tombe sur 
- duktape un exemple la https://github.com/kovidgoyal/dukpy IPTVplayer utilise cette methode
- PhantomJS mais qui necessite Selenium (donc assez lourd).
- La team kodi planche sur un navigateur (mais faut pas rever).

Apres Exodus Jdonwloader pyload le gererait mais j'ai jamais pu tester.

**Comment by Kodigoal** [comment]
ddl-island ok encore chez moi .

**Comment by chataigne73** [comment]
ddl-island est OK uniquement pour les liens de 'streaming' tels qu'ils les classent sur leur site. Tous les liens qu'ils appellent de 'telechargement' (uptibox 1fichier etc) sont ko, et ce sont justement ceux de la meilleure qualité (1080p, 720p DTS)

**Comment by Arias800** [comment]
@TpmName tu a parler de sennuim c est possible de l utilisé avec kodi ?

**Comment by TmpName** [comment]
Sisi je confirme ca marche encore, et pr les telechargment, il y a un petit lien avec "cliquez icic pour une autre methode et tu as le captcha normal, celui qui marche avec Vstream.

Yep ce serait possible mais jamais teste, ca marche avec ca https://github.com/andrewleech/script.module.webdriver

Sinon ya un mec qui a developpe un navigateur web pr kodi sans souris, a mon avis c'est plus interessant
http://forum.kodi.tv/showthread.php?tid=309391&highlight=selenium

**Comment by Arias800** [comment]
Parce que la je suis en train de faire un script qui automatique la création d un compte netflix via sélénium donc si je pouvais l ajouter sur vstream

**Comment by johngf** [comment]
Il y a un addon netfix  sur github pour kodi @Arias800

**Comment by Arias800** [comment]
Oui mais ilf aut déjà avoir un compte ^^
