### ISSUE TITLE
Problème (Mise à jour disponible en vert)

### ISSUE THREAD

**Issue by njnr34** [Kodi-vStream/venom-xbmc-addons#1431]
Bonjour,

J'ai un problème avec la mise a jour disponible en vert dans Vstream. J'ai installer Vstream mes je n'ai pas la notification mise a jour disponible en vert du coup je me retrouve avec les liens et hébergeur non mise a jour.

Un énorme merci pour tout le travail et merci d'avance.

**Comment by Arias800** [comment]
Normalement ils faut attendre 3 jour max pour la mise à jour des fichier (site et hoster)

**Comment by njnr34** [comment]
bonjour Arias800,

J'ai déjà attendu plus de 3 jours mes toujours rien, j'ai désinstaller réinstaller Kodi et Vstream mais rien n'y fait.

Merci quand même pour ta réponse.

**Comment by johngf** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-à-jour 
Sinon tu peux avancer la date de ta machine de 3 jours

 Note :you watch exa share all vid ça sert a rien de cliqué ils sont hs meme sur le net

**Comment by njnr34** [comment]
Je viens d’essayer cela ne marche pas. Je tien a préciser que je suis en version 17.3 sur Windows.

**Comment by Arias800** [comment]
Tu a essayer la version beta ?

**Comment by njnr34** [comment]
Non j'ai pas essayer, mais avant avec les anciennes versions de kodi ça fonctionner et sur mon ordinateur portable ça fonctionne mes pas sur mon fixe, je comprend plus rien.

**Comment by johngf** [comment]
Tu as installé comment vsteeam via le repository vstream ?

**Comment by njnr34** [comment]
Oui j'ai installé via le repository vstream

**Comment by johngf** [comment]
Apres ils ont pas mal bidouillé a cause de ça #1239

**Comment by Arias800** [comment]
Moi sur j ai 2 version une sur windows XP (kodi 12) et windows 10 (kodi 17.3) et pas de problème

**Comment by njnr34** [comment]
j'ai remarqué que pendant l'installation de vstream y'a un message d'erreur qui s'affiche pendant l'installation ça viens peut être de la le problème.

**Comment by johngf** [comment]
Non l'erreur n'est pas de vstream mais de common plugin cache  si je me souviens bien c'est pas grave

**Comment by njnr34** [comment]
vous pensez que cela viens de mon ordi fixe? parce-que sur mon ordi portable tout marche très bien

**Comment by Arias800** [comment]
Peut être après tu peux essayer un coup de adwcleaner par exemple essayer de désactiver le pare feux juste le temps de tester bref il y a plein de truc possible mais après tu peux allez sur des forum specialise ^^

**Comment by johngf** [comment]
Attend @TmpName il a suivis le soucis de maj il sera mieux t'aider

**Comment by njnr34** [comment]
j'ai installé vstream beta est ça a fonctionné bizarre.

**Comment by njnr34** [comment]
D'accord johngf je vais faire ça, merci beaucoup pour votre aide et vos réponses a toi et Arias800.

**Comment by Arias800** [comment]
De rien c est un plaisir d aidée ^^

**Comment by TmpName** [comment]
C'est bon avec la beta, donc bne nouvelle ...

Ou est la sortie ?

Sinon oui y a eu de grosses modifs, et la reinstallation ne sert a rien, les parametres sont memorisés ailleurs.
Par contre si ca redeconne me faut les logs.

**Comment by njnr34** [comment]
Oui avec la beta pas de soucis par contre la recherche virtuelle ne fonctionne pas.

Oui je me suis rendue compte ça sert a rien de faire la réinstallation par contre quand j'essaye d'installer avec le repo le problème persiste.

**Comment by TmpName** [comment]
Me faudrait plus d'infos ou mieux un log
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by njnr34** [comment]
Bonjour TmpName, je fait comment pour vous envoyez le log?

**Comment by Arias800** [comment]
Upload Kodi log : Upload automatiquement votre log sur Slexy vous pouvez par la suite simplement nous transmettre l'ID vous étant donner en popup. Votre log http://slexy.org/view/+ votre ID
C est dans les paramètre dans outil et upload log

**Comment by njnr34** [comment]
c'est bon j'ai trouver voici le log: https://slexy.org/view/s21ezwNFnx

**Comment by Arias800** [comment]
C est moi ou il y pas de trace de vstream ?

**Comment by johngf** [comment]
Oui les accent encore du prenom

**Comment by TmpName** [comment]
XD, wé encore un fan des accents.

Donc je confirme, si tu n'installes pas la beta c'est mort, ca fait 1 mois qu'on corrige pour que ca tourne avec des accent avec @razorex , et la derniere modif date d'une semaine max, donc si ta version a plus d'une semaine ca ne marchera pas.

**Comment by johngf** [comment]
Il a essayé avec la beta et c'est ok donc il faudra attendre le 5.3 de vstream bientot

**Comment by Arias800** [comment]
Il a dit qu'il installer la beta plus haut ^^

**Comment by TmpName** [comment]
Ben apparement meme avec la beta la recherche visuelle deconne.

**Comment by TmpName** [comment]
Et le log est coupe, c'est le meme prb qu'avais @razorex avant ses modifs.

**Comment by johngf** [comment]
Rien a voir mais i anime hs et streaming watch aussi

**Comment by Arias800** [comment]
Mais c est quoi le problème des accent pour le coup ca je n ai pas suivit ^^

**Comment by Arias800** [comment]
I ianime il a pas ete mit a jour ressamment ?

**Comment by TmpName** [comment]
Si mais ca deconne pr les nouveautes, je m'en occupe ce soir, ca doit pas etre mechant.

**Comment by Arias800** [comment]
OK ^^

**Comment by njnr34** [comment]
Mdr je peut savoir c'est quoi le rapport du nom avec accents ou sans accents le problème viens vraiment de la lol ?

Oui j'ai installé la beta et effectivement la recherche visuelle ne fonctionne pas quand tu clique dessus rien ne ce passe.

**Comment by TmpName** [comment]
Tres simple un chemin (sur internet ou ton ordi) est code en ascii (sur toute la planete de la meme maniere), et les accents ne sont pas dans ces tables. Donc en informatique la bonne habitude c'est jamais d'accent (et a l'ecrit je dirais pareil, mais ca c'est perso).

Donc pour permettre l'utilisation des accents (et pire, par exemple les kanji japonais) on utilise l'unicode, un caractere a ton ecran est en fait code par 2 caracteres.

Entre les deux il y a l'utf-8, kodi fonctionne par defaut en utf-8 (normal ca aussi c'est le standard), donc c'est aux createurs d'addons de faire attention a l'unicode, et comme c'est assez rare des personnes mettant des accents on a jamais fait attention. Donc les modifs sont encore fraiches.

Toi dans une url ou un chemin, tu vois juste www.siteavecdeséeà/blalbla, mais il y a plein de convertions qui se font en arriere plan (car pas gere a la base) , et crois moi c'est l'enfer a gerer quand tu as un site qui marche en iso, a convertir en utf-8 pr Vstream puis unicode pr une gestion complete.

**Comment by TmpName** [comment]
Tu pourrais pas essayer de nous faire passer un log d'une autre maniere stp ?
Ou sinon on attend le retour de @razorex, mais il y a peu etre eu une modif sur un fichier recemment.

**Comment by Arias800** [comment]
Ah OK je comprend mieux merci professeur

**Comment by TmpName** [comment]
En fait ce n'est pas ta faute, si windows le permet, c'est que tu peux. C'est a nous de nous adapter. Le soucis c'est que du coup ca fait plus de boulot pr nous, et comme on a pas d'accents on voit pas tjours le prb.

**Comment by njnr34** [comment]
Ah d'accord TmpName, oulala que ça a l'air bien compliqué tout ça lol.

C'est a dire d'une autre manière? et pour info j'ai fait le log pas avec la version beta mais avec la version avec repository.vstream.0.0.2, et si j'installe vstream sans le nom avec l'accent ça pourrais pas résoudre le problème? j'y connais vraiment rien.

**Comment by njnr34** [comment]
Ah d'accord je comprend mieux merci pour les explications lol.

**Comment by johngf** [comment]
Si mais normalement il faut un nouveau compte windows changer le nom ne l'enleve pas de certains dossier 
Test pour voir en virant l'accent

**Comment by TmpName** [comment]
Et si tu veux rigoler tape sous google "python UnicodeDecodeError", tu vas voir le nbre de personnes qui galerent avec ca et juste sous python.

Supprimer l'accent, va faire marcher Vstream, mais ca corrigera pas le probleme. Normallement la version beta doit marcher, ou alors @razorex va se faire engueler.
Pout voir ton probleme, il nous faut vraiment le log de la version beta qui plante. La version du repositary deconne, ca on a deja vu.

**Comment by njnr34** [comment]
La version beta marche ça me fait la mise a jour en vert mais mon véritable problème ne viens pas de la version beta mais juste de la version repo qui me fait pas la mis a jour en vert je pense qui faut que j'attende la version 5.3.

De mon coté la version beta fonctionne bien a pars la recherche visuelle qui fonctionne pas, mais si tu veut je peut te faire le log avec la version beta.

**Comment by TmpName** [comment]
Yep, stp, histoire de corriger le bug avant de sortir la 5.3.

**Comment by njnr34** [comment]
Le log de la beta TmpName : https://slexy.org/view/s2Yxqd2Ngx

**Comment by Arias800** [comment]
Voila le probleme @TpmName : 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)

**Comment by TmpName** [comment]
Heu me faudrait juste les 3 lignes qui manquent ^^ juste apres.
Le log est tronque, mais normallement avec la version de la beta tu devrais avoir le log complet.

Apparement l'erreur est bien ecrite dans le log, reprovoques le bug, et va voir directement dans le log, ca devrait etre dans les 10 dernieres lignes, celles qui commencent par 'error'

**Comment by razorex** [comment]
ça a fonctionné chez moi il y a qq jours..

**Comment by TmpName** [comment]
Ha ca redeconne depuis peu ?
Tu pourrais pas refaire un log stp ? Sur le sien l'erreur a l'air d'etre loguee mais comme toi avant, le log est tronque.

**Comment by johngf** [comment]
je trouve que vstream deviens lourd ou c'est kodi 17 parfois en cours.... reste une plombe simplemant en naviguant dans les répertoires (nouvelle install)

**Comment by TmpName** [comment]
Oui, meme constatation, les dernieres modif de @LordVenom ?
Meme parfois je fais retour arriere 4/5 fois et il se passe rien, et 5 ou meme 10s apres ca commence a reagir.
Kodi V 17.1

Y en a pas un qui pourrait faire passer un log avec une install avec accent, pas envis d'en refaire une juste pr tester ca ....

**Comment by razorex** [comment]
Je viens de faire la mise à jour à l'instant et tout a fonctionner

**Comment by TmpName** [comment]
@njnr34 tu peux retester si tu veux. Mais @razorex a le meme type d'install que toi donc ca devrait etre bon.

En passant merci pr le log @razorex, en esperant que c'est le dernier qu'on te demande ^^.

**Comment by razorex** [comment]
Pas de souci.

**Comment by razorex** [comment]
Par contre j'ai l'impression qu'il y a un pb de ralentissement entre la version0.52 et la bêta. ma TV box fonctionnait bien j'ai installé la bêta dessus et depuis elle rame?????

**Comment by razorex** [comment]
`21:23:41.717 T:6120   DEBUG: ------ Window Deinit (DialogAddonInfo.xml) ------
21:23:41.728 T:6120   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
21:23:42.609 T:7860   ERROR: Failed to rename file/directory \\?\C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream to \\?\C:\Users\Hervé\AppData\Roaming\Kodi\addons\temp\1b3c74f5-56d7-47fe-aa74-b83a791d9262, Error: (null)
21:23:42.609 T:7860   ERROR: XFILE::CFile::Rename - Error renaming file C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream
21:23:42.609 T:7860   ERROR: Failed to move old addon files from 'C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream' to 'C:\Users\Hervé\AppData\Roaming\Kodi\addons\temp\1b3c74f5-56d7-47fe-aa74-b83a791d9262', retrying in 500ms
21:23:43.112 T:7860   ERROR: Failed to rename file/directory \\?\C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream to \\?\C:\Users\Hervé\AppData\Roaming\Kodi\addons\temp\1b3c74f5-56d7-47fe-aa74-b83a791d9262, Error: (null)
21:23:43.112 T:7860   ERROR: XFILE::CFile::Rename - Error renaming file C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream
21:23:43.112 T:7860   ERROR: Failed to move old addon files from 'C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream' to 'C:\Users\Hervé\AppData\Roaming\Kodi\addons\temp\1b3c74f5-56d7-47fe-aa74-b83a791d9262', retrying in 500ms
21:23:43.615 T:7860   ERROR: Failed to rename file/directory \\?\C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream to \\?\C:\Users\Hervé\AppData\Roaming\Kodi\addons\temp\1b3c74f5-56d7-47fe-aa74-b83a791d9262, Error: (null)
21:23:43.615 T:7860   ERROR: XFILE::CFile::Rename - Error renaming file C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream
21:23:43.615 T:7860   ERROR: Failed to move old addon files from 'C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream' to 'C:\Users\Hervé\AppData\Roaming\Kodi\addons\temp\1b3c74f5-56d7-47fe-aa74-b83a791d9262', retrying in 500ms
21:23:44.118 T:7860   ERROR: Failed to rename file/directory \\?\C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream to \\?\C:\Users\Hervé\AppData\Roaming\Kodi\addons\temp\1b3c74f5-56d7-47fe-aa74-b83a791d9262, Error: (null)
21:23:44.118 T:7860   ERROR: XFILE::CFile::Rename - Error renaming file C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream
21:23:44.118 T:7860   ERROR: Failed to move old addon files from 'C:\Users\Hervé\AppData\Roaming\Kodi\addons\plugin.video.vstream' to 'C:\Users\Hervé\AppData\Roaming\Kodi\addons\temp\1b3c74f5-56d7-47fe-aa74-b83a791d9262', retrying in 500ms`

**Comment by TmpName** [comment]
Yep, @johngf  on a remarque les memes problemes de ralentissement, @LordVenom essaye de corriger un bug de refresh, mais honnetement je prefere avec le bug.

**Comment by LordVenom** [comment]
Perso je me demande si c'est pas la 17.3 sur le pc un peux de lenteur pas enorme mais bon, et sur le htpc reset total de la base de donner merci Kodi :)

**Comment by TmpName** [comment]
Suis encore sous kodi 17.1, et j'ai les memes ralentissement.
