### ISSUE TITLE
Ajouter une source quand on est pas root

### ISSUE THREAD

**Issue by jhdscript** [Kodi-vStream/venom-xbmc-addons#1432]
Bonjour j'ai codé ma propre source et je voudrai l'ajouter sur le kodi de ma bbox miami mais impossble d'uploader le fichier. Pourriez vous m'aider svp ? Cdt

**Comment by Arias800** [comment]
Déjà de quel source s'agit-t-il ?

**Comment by jhdscript** [comment]
une source privée juste pour moi et je souhaite juste l'ajouter dans le plugin mais impossible de trouver comment faire sur la bbox car elle n'est pas rooté

**Comment by Arias800** [comment]
En ce qui me concerne n utilisant pas ce type de système je ne peux pas t aidé (la seul solution a la quels j ai pensé c'était de faire un pull request mais si c est privé ça ne va pas fonctinner)

**Comment by jhdscript** [comment]
oui je prefererai ne pas diffuser la source pour le moment :(

**Comment by TmpName** [comment]
Encore plus original comme systeme ^^,
Peut etre sur un forum dedie a la BBox ?

**Comment by Arias800** [comment]
Alors attends un peu peut être que quelqu'un puisse t aider ^^

**Comment by jhdscript** [comment]
merci.

En fait quand j'ai lu le readme du plugin j'ai vu qu'il etait simple de developper le code pour ajouter une source mais je n'ai pas pensé qu'il serait impossible de l uploader :(

**Comment by razorex** [comment]
et pk tu root pas?????

**Comment by jhdscript** [comment]
parceque la bbox miami est pas rootable, enfin j ai pas trouvé comment faire.

Je clos le ticket car j'ai trouvé comment ajouter ma source en bidouillant :p
