### ISSUE TITLE
Fichiers introuvables 

### ISSUE THREAD

**Issue by Turk182es** [Kodi-vStream/venom-xbmc-addons#1433]
Salut,

Depuis quelques temps toutes les séries que je recherche ne marchent pas. Les lien sont vides ou fichier introuvables .
C'est chez moi ou c'est tout le monde pareil ? 
Exemple : Notre belle famille, silverspoon, manimal etc...

**Comment by razorex** [comment]
Beaucoup d'hotes sont hs en ce moment. Il faut patienter

**Comment by johngf** [comment]
Sur quel site ? Sinon you watch all vid exa share c'est mort les 2 dernier leurs site ne fonctionne meme plus il faut meme pas cliqué

**Comment by Turk182es** [comment]
Ah d'accord, donc c'est pas chez moi le problème, je suis rassuré :)

Super merci pour votre aide, vous pouvez fermer le ticket.

Cordialement
Stephane
