### ISSUE TITLE
Netu

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1434]
les liens Netu ne fonctionnent plus sur vStream, ok sur le site. testé sur Filmstreamvk

**Comment by johngf** [comment]
Tu a la derniere version de netu

**Comment by razorex** [comment]
Ok. Pas de pb. Des que je rentre

**Comment by johngf** [comment]
@razorex chez moi c'etait ok meme sans le nettoyage que j'ai fait hier testé sur le meme site
