### ISSUE TITLE
Derniere MAJ 

### ISSUE THREAD

**Issue by mako83** [Kodi-vStream/venom-xbmc-addons#1435]
Salut,

Quel est la derniere maj de Vstream en version officiel ?

La 0.5.2 ou 0.5.3 

si c'est la version 0.5.3 comment l'obtenir?

Merci d'avance

**Comment by johngf** [comment]
elle n'est pas sortie la 5.3 >> https://github.com/Kodi-vStream/venom-xbmc-addons/releases/
