### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1439]
streamiz_co :

![streamiz_co](https://cloud.githubusercontent.com/assets/26149640/26743509/7bbb74be-47e2-11e7-9fd7-a81dd7a5c76f.png)

**Comment by TmpName** [comment]
Sur fond blanc ca ressort pas terrible, bon moi m'en fou mon fond et noir, mais je sais pas comment vous faites dans ce cas ?

**Comment by razorex** [comment]
il apparait sur le fond vStream

**Comment by razorex** [comment]
J'en profite pour proposer les nouveau logo de megastream (transparent):

![megastream](https://cloud.githubusercontent.com/assets/26149640/26744440/354b4a82-47e6-11e7-8b46-1d236d35c0b1.png)

**Comment by johngf** [comment]
@razorex si tu peux faire sk stream co comme icone

**Comment by razorex** [comment]
le logo de 'filmstreamingv2'
![filmstreamingv2](https://user-images.githubusercontent.com/26149640/26887817-5e0ef240-4ba9-11e7-8d44-6b96aac138d7.png)

**Comment by razorex** [comment]
J'ai repris le logo de 'serie_streaminghd' pour réduire son poid 
![serie_streaminghd](https://user-images.githubusercontent.com/26149640/26888708-25048dea-4bac-11e7-935d-b564d4143cda.png)

**Comment by razorex** [comment]
Celui de 'skstream_co':

![skstream_co](https://user-images.githubusercontent.com/26149640/26890917-8684b8cc-4bb3-11e7-931b-a39f6ad093b9.png)

**Comment by razorex** [comment]
@LordVenom impossible d'upload les logos, pb d'accès si tu veux changer çà? j'ai ce défaut....
`Uploads are disabled. File uploads require push access to this repository.`

**Comment by TmpName** [comment]
Meme sur la beta ?

**Comment by razorex** [comment]
oui sur la bêta

**Comment by LordVenom** [comment]
Demande envoyer quand tu auras valider tu auras les permissions :)

**Comment by razorex** [comment]
??????? @LordVenom qu'elle demande parce que j'ai rien reçu.

**Comment by TmpName** [comment]
Tu le recois sur github de memoire, un truc a valider, par mail tu recois juste une info.

**Comment by LordVenom** [comment]
J'ai relancer l'invite toujours en attente.

**Comment by razorex** [comment]
Pas eu d'info par mail rien sur le github, j'ai retenté un upload mais pareil

**Comment by LordVenom** [comment]
Moi ça me dit :
> Vous avez invité razorex à vstream! Ils recevront rapidement un courriel. Ils peuvent également visiter https://github.com/Kodi-vStream pour accepter l'invitation.

**Comment by razorex** [comment]
Ok. ben pas eu l'invitation mais je viens de recevoir un mail qui me dis qu'elle a été annulée. je viens de validé la dernière d'il y a 20mn.
`Hi razorex,
Your invitation to the vstream organization on GitHub has been canceled. Links to the invitation in previous emails will no longer work.

Thanks,
The GitHub Team`

**Comment by LordVenom** [comment]
Oui j'ai cancel pour en faire une autre toujours en attente.
