### ISSUE TITLE
zt.ws uptostream fichier introuvable

### ISSUE THREAD

**Issue by nathjo** [Kodi-vStream/venom-xbmc-addons#1440]
Bonjour à tous,

Ceci est mon premier post et je tiens avant tout à vous remercier pour tout le travail effectué. C'est remarque ce qui est fait ici au quotidien..

Venons à mon petit soucis.
Possédant un compte premium uptobox, j'utilise essentiellement Kodi vstream avec la source ZT.WS et le lecteur uptostream. Ayant eu des problèmes d'accès à cette source via Kodi, j'ai suivi la resolution du post #1389 et j'ai pu y acceder ( Merci 👍 ). J'ai fait quelques test de lecture sur des films, séries et animes concluant. Cependant, j'ai rencontré des problèmes avec certains. Exemple pour certaines séries ou animes qui sont biens présent via uptostream via le site web, je n'ai pas accès sur l'application. Cela me met la suite de message d'erreur suivant "PREMIUM MODE"authentification réussie , "UPTOBOX" fichier introuvable. Je ne sais pas si ce problème avait déjà été traité auparavant... Avez-vous des informations dessus ?

Encore merci à vous

**Comment by TmpName** [comment]
up2stream ou up2box ?

**Comment by johngf** [comment]
oui mais les liens sont éphémere est-ce que le lien fonctionne sur ton navigateur internet ?

**Comment by nathjo** [comment]
Oui, cest la première chose que j'ai faite . Cela fonctionne bien sur le navigateur. 
Cela conserve peu de série donc ce n'est pas bien grave. Merci tout de même.

**Comment by TmpName** [comment]
Effectivement y a un soucis.

**Comment by TmpName** [comment]
Bon j'ai commence, toute la partie apres la ligne 563 est a desactiver.
Et au niveau des commandes posts, de la fonction DecryptDlProtecte c'est l hallu complete, je sais pas si c'est volontairement bugguée ou quoi, mais ca ressemble a rien. En tout cas c'est a refaire.

**Comment by TmpName** [comment]
Bon la je galere, j'en suis la https://pastebin.com/A3ARYvCK

Ma requette est presque comme celle de Firefox a part que ca ne marche pas, la seule difference reside dans le formatage de la partie multipart, mais je ne pense pas que ca chnage quelque chose.

Si quelqu'un a une idee ?

**Comment by johngf** [comment]
Le code multipart dans le code d'upto box ne fonctionne pas ?

**Comment by TmpName** [comment]
Sisi, il devrait fonctionner, il est meme inclus dans requestHandler.py mais comme httpfox deconne sur ce site (et je sais pas pkoi) ca affichait n'importe quoi et je pensais que c'etait different, suis tombe dessus par hazard, mais effectivement en passant par requestHandler au lieu de urllib le code serait plus leger.

**Comment by johngf** [comment]
ça mais deja arrivé que hhtp fox deconne dans ce cas j'utilse livethttpheaders

**Comment by johngf** [comment]
sinon @TmpName si tu peux test chez toi la fonction [cette ligne](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/util.py#L364)
le decode fait planté chez moi

**Comment by TmpName** [comment]
Ca marche en virant le .decode("utf-8")
Sinon des la ligne 41 avec "Télévision/Radio " > plantage.
