### ISSUE TITLE
zone_telechargement_ws / exclus (films populaires) ou films + plus

### ISSUE THREAD

**Issue by sribou** [Kodi-vStream/venom-xbmc-addons#1446]
Bonjour,

Dans zone_telechargement_ws.py, pouvez-vous rajouter la ligne 
MOVIE_VIEWS = (URL_MAIN + 'exclus/', 'showMovies') # films + plus
ou me dire comment gérer MOVIE_EXCLUS 
car je ne le vois pas dans le menu

Ou me dire comment exclure zone_telechargement_ws.py de la mise à jour automatique ?

Merci.

**Comment by TmpName** [comment]
Elle est a "Exclus (Films populaires)"

La mise a jour auto met tout a jour, il te suffit de ne pas la valider, et de mettre a jour uniquement les fichiers dont tu as besoin (mais c'est beacoup plus long)

**Comment by sribou** [comment]
Merci pour ce retour rapide mais je n'ai pas Exclus (Films populaires) dans le sous-menu Films

Merci.

**Comment by TmpName** [comment]
"Toutes les sources" "zt.ws" "exclus"

**Comment by sribou** [comment]
Merci, c'est exactement ce que je cherchais
