### ISSUE TITLE
Television Replay : addon à intégrer ?

### ISSUE THREAD

**Issue by sribou** [Kodi-vStream/venom-xbmc-addons#1447]
Bonjour,

Avez-vous jetez un oeil à cet addon 
https://github.com/spmjc/plugin.video.freplay
Perso, je l'utilise en plus de vstrem mais ce serait super de les fusionner ?

Merci.

**Comment by Arias800** [comment]
Personnellement je ne serai pas contre mais le problème viens du faite que l'addon n'est plus mit a jour :/

**Comment by sribou** [comment]
Pour info la dernière mise à jour date de la semaine dernière et tout ce que j'ai testé fonctionne a merveille

**Comment by Arias800** [comment]
ah ok parce que lorsque l'on vois que personne ne réponds pour les issue :/

**Comment by TmpName** [comment]
Non, non, il est actif ^^. Et je m'en sert aussi, tres bon addon, et qui pourrait etre officiel je pense.

Par contre non, j'aime vraiment cet addon et pas envie de marcher sur leur plate-bande, c'est ce qu'il y a  mieux question replay, Fusion pas possible (et pourquoi faire, chacun developpe son secteur de son cote), et pas envis non plus d'utiliser les memes sources que eux.

**Comment by sribou** [comment]
Ok. Je continue comme ça alors mais moins d'intérêt sur cette section dans vstream dans ce cas.

**Comment by TmpName** [comment]
Yep ^^.
Les replay de vstream sont comme pr les autres videos, des fichiers archivés sur des hebergeurs.
FReplay lui propose des replay a chaud propose par des distributeurs de programmes, c'est vraiment un plus.

**Comment by sribou** [comment]
Compris. Merci pour la clarification et pour le boulot.
