### ISSUE TITLE
Chaines TV !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1449]
Je viens de trouver un site pour regarder les Chaines TV qui s'appelle "ALL FR TV"
au ht tp://racacaxtv.ga/mega.php

**Comment by Arias800** [comment]
Racacax a ça propre version kodi ^^

**Comment by TmpName** [comment]
Yep, et on peut pas prendre ses liens, il les cherches/conçoit lui meme. Beacoup de taff, rien que pr les garder a jours ca doit etre l'enfer.

**Comment by Arias800** [comment]
Et en plus il est tout seul des qu'il y a un problème il le répares très rapidement donc ce ne serai pas morale de gâchez son travail

**Comment by luluvulcain** [comment]
Je suis pas la pour gâcher son Travail, juste pour le partage à la communauté de vstream.

**Comment by TmpName** [comment]
Pas de soucis, l'info vaut le coup, je n'y vais plus en ce moment (marre de la tv) mais ses liens sont tres fiables. A recommander aussi.

**Comment by Arias800** [comment]
D ailleurs pour allfrtv il vaut mieux utilise l application que le kodi ^^
