### ISSUE TITLE
Multiple termes

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1450]
il y a sSyn, sCom et sResume n'est il pas possible de faire un choix et de réduire à un terme??

**Comment by johngf** [comment]
Ce ne sont pas des fonctions juste des noms tu peux ecrire ce que tu veux meme n'importe quoi tant que ça affiche le synopsis

**Comment by razorex** [comment]
dsl j'étais pas sur du terme. mais peut etre que d'imposer un "terme" n'est pas une mauvaise chose. j'ai eu le pb quand fonction de l'affichage (fanart, info.....) le synopsis n'apparaissait.

**Comment by johngf** [comment]
Si elle ne s'affiche pas en fonction de l'affichage c'est peut etre un soucis avec le theme
