### ISSUE TITLE
Problème recherche (liste de résultats non mémorisée)

### ISSUE THREAD

**Issue by tug912** [Kodi-vStream/venom-xbmc-addons#1452]
Bonjour, j'ai un problème non résolu (malgré plusieurs tentatives précédentes).

Lorsque je fais une recherche tout fonctionne la liste des résultats s'affiche. Je Test le premier lien, mais lorsque que je veux revenir à la liste des résultats il m'affiche à nouveau la fenêtre de recherche. Je dois retaper le nom et attendre que la recherche recommence. Comme si Kodi ne sauvegardait pas la liste des résultats...
C'est vraiment bloquant pour utiliser l'addon. 
J'ai déjà tenté de désinstaller/réinstaller l'addon et j'ai mis la dernière version de kodi rien n'y fait.
Je pense que le problème vient plus de Kodi mais aucune idée d'où.

Je suis sur Kodi 17.3 et voici un extrait du Log  : 

20:13:31.621 T:3232  NOTICE: 	[PLUGIN] Vstream: Load Recherche: streamingk_com
20:13:32.515 T:3232  NOTICE: 	[PLUGIN] Vstream: Load Recherche: tv_streaming_ch
20:13:33.074 T:3232  NOTICE: 	[PLUGIN] Vstream: Load Recherche: vkstreamingfilm_biz
20:13:33.650 T:3232  NOTICE: 	[PLUGIN] Vstream: Load Recherche: voirfilms_org
20:13:34.623 T:3232  NOTICE: 	[PLUGIN] Vstream: Load Recherche: zone_telechargement_eu
20:13:35.406 T:3232  NOTICE: 	[PLUGIN] Vstream: Load Recherche: zone_telechargement_ws
20:13:36.831 T:3232  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:13:44.511 T:4876  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:13:44.517 T:4876  NOTICE: 	[PLUGIN] Vstream: load site film_illimit_fr and call function showHosters
20:13:45.193 T:4876  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:13:45.907 T:624  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:13:45.913 T:624  NOTICE: 	[PLUGIN] Vstream: load site globalSearch and call function searchMovie
20:13:48.504 T:624  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:13:48.536 T:4280   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%201%3a%20Films&type=Film
20:13:48.536 T:4280   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%201%3a%20Films&type=Film) failed
20:13:48.608 T:928  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:13:48.614 T:928  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showSearch
20:13:49.258 T:928  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:13:52.391 T:4280   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
20:13:52.472 T:3804  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:13:52.478 T:3804  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showSearch

Merci par avance

**Comment by Arias800** [comment]
Problème déjà connu sur kodi 17 qui aurai du être fix essayé d installer la beta

**Comment by tug912** [comment]
Bonjour et merci. malheureusement j'ai déjà essayé ça et ça ne solutionne pas mon problème.
Sur une installation "vierge" de kodi ou je mets juste Vstream pas de soucis. Sur mon build perso contenant pas mal d'addons, cela ne change rien.

Une autre piste ?

**Comment by Arias800** [comment]
@TpmName ça peur venir de la ?" Control 50 in window 10025 has been asked to focus, but it can't"

**Comment by TmpName** [comment]
Nope ce message est reccurent, pas tres grave.
Sinon pour ton probleme, ca vient des reglages de kodi, en fait quand la page est longue a charger (comme pr la recherche) kodi la met en cache. Chez toi pas de cache.

"Sur une installation "vierge" de kodi ou je mets juste Vstream pas de soucis. Sur mon build perso contenant pas mal d'addons, cela ne change rien."
Ca veut dire que sur un kodi vierge ca marche sans probleme, mais sur ton build .... ?

**Comment by Arias800** [comment]
Ca doit être a cause des addon si une vierge marche ce que tu peux essayer c est de réinstaller un par un les addon et tester entre chaque installation

**Comment by tug912** [comment]
Enfin trouvé la solution ! 
Merci à vous et surtout @TmpName qui m'a mis sur la bonne voie !

Il y avait donc bien un soucis de cache et j'ai fini par trouvé où ! Cela venait d'un addon que j'utilise pour faire des clear cache automatiques (TDB Wizard). Je l'avais réglé pr faire un clear cache à chaque démarrage. Cela fonctionnait bien sur kodi 16, mais à priori cela pose des problème sur kodi 17.

Bref en désactivant les clear cache automatiques plus de problème de recherche sur mes addons (notament vstream et istream).

Merci à vous pour votre aide.

PS : connaissez vous un autre addon que tdb qui me permettrait de faire des auto clean cache sur kodi 17 sans avoir de problème cette fois ?

**Comment by johngf** [comment]
vstream a ces fonctions clean cache dans les parametres

**Comment by TmpName** [comment]
Pkoi en auto ? Tu vois bien que ca apporte plus de prbs que d'avantages.

**Comment by tug912** [comment]
Bah en auto évite d'avoir à le faire et/ou d'y penser et évite ainsi que ca finisse par poser problème en plein film. 

Sur ma config précédente, à chaque démarrage kodi vidait le cache, comme ça aucun soucis et pas la peine d'y penser. 
Malheureusement cela semble effectivement poser pb sur kodi 17 et l'addon TDB n'a pas été mis à jour en intégrant ce problème.
Dans tous les cas j'ai trouvé dans ce même addon une fonction permettant de vider le cache automatiquement à partir d'un certain poids j'ai mis 100 Mo et cela fonctionne et ne pose plus de soucis dans vstream ni istream.

**Comment by TmpName** [comment]
Je ne sais pas de quel cache tu parles mais le cache video est a priviligier en memoire vive, le cache par addon est ridiculement petit (celui de Vstream meme pas 1 M chez moi), Les metas peuvent prendre de la place, mais si tu les supprimes a chaque fois, je pense que tu l'as desactives.

Si tu as 100 M de cache par semaines, je me demande ce que font tes addons.
