### ISSUE TITLE
De gros addons américains ont commencé à fermer suite à cela ...

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#1453]
https://www.tvaddons.ag/forums/underground-news/59849-dish-network-sues-zemtv-tv-addons-copyright-infringement.html#post420663

Phoenix (développé par Cosmix) ferme
Le développeur Echo Coder jette l'éponge, pareil pour Shani
et ce n'est peut être qu'un début

En gros, si Kodi est reconnu comme un outil "neutre" et légal, ce n'est pas le cas des addons d'après un récent jugement aux états unis

... à méditer...

**Comment by Arias800** [comment]
Apparemment ça ne concerne que les add-on qui retransmettent des chaine avec un copyright bien précis ^^

**Comment by chataigne73** [comment]
http://www.clubic.com/television-tv/actualite-831548-piratage-extensions-kodi-ferment.html

**Comment by Arias800** [comment]
Effectivement ça craint mais après il n'y a pas encore eu de cas en france ?

**Comment by chataigne73** [comment]
Non en effet, pas en France... Mais à mon avis ça viendra

**Comment by Arias800** [comment]
Normalement en France on risque rien car on héberge rien

**Comment by TmpName** [comment]
Vous en connaissez beacoup d'addon fr pour voir les chaines cablees/satelite ?
Moi j'en connais qu'un, est on est loin de leur performances

**Comment by johngf** [comment]
c'est pas grave on peut toujours s'en faire un perso si ça arrive

**Comment by chataigne73** [comment]
En tous cas je pense qu'il faudrait supprimer la partie tv de vstream pour être tranquille... Et en plus ya d'autres add-ons pour ça

**Comment by TmpName** [comment]
C'est pas des chaines du cable, c'est des chaines gratuites la plupart du temps, les autres ne marchent que 2/3 jours.

**Comment by chataigne73** [comment]
Ya c+, beIN, etc...

**Comment by johnboisvert** [comment]
Si vous faite un pv allez vous nous l'envoyer par courriel svp? :P

**Comment by TmpName** [comment]
Un pv ?

**Comment by johnboisvert** [comment]
addon privé désolé :)

**Comment by TmpName** [comment]
C'est clair que si Vstream disparait, beacoup vont continuer, moi suis obliger, j'ai plus de TV ^^.
Mais t'inquietes pas, c'est du code open source, ca disparait pas comme ca, regarde l'addon "popcorn".

**Comment by johnboisvert** [comment]
Fiou !! heureusement 💃
