### ISSUE TITLE
Petit problème avec la recherche visuelle

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1459]
Hello

Je vous signale un petit problème rencontré avec la recherche visuelle :

Donc : Quand je sélectionne :

Recherche Visuelle + Séries à la TV 

La liste s'arrête à la page 12 après "Ackley Bridge"

Je sais que 12 pages c'est déjà pas mal mais c'est sans doute un bug quand même.

Et encore merci à tous les contributeurs.

**Comment by Arias800** [comment]
La recherche visuel est base sur le site imbd il me semble donc si ça ce trouve il y a que 12 page sur le site ^^

**Comment by canopre** [comment]
C'est possible mais pour les autres requêtes : "séries mieux notées" et "Séries populaires" : il y a bien plus de pages.

**Comment by TmpName** [comment]
C'est bien ca, je viens de voir sur le site, 12 pages, c'est les series qui passent en ce moment a la TV, le nbre n'est pas illimite.

**Comment by canopre** [comment]
ok alors : merci pour ces précisions !
