### ISSUE TITLE
Multiupload

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#1464]
Juste une question est il possible d inclure les liens multiupload?
La source ht tp://ww w.film.telechargementz.tv a des liens ddl et stream 
Mais aussi multiupload qui donne d autre lien ddl et stream

Ya une chance de voir cette source et ses liens ddl/ stream/ multiupload 

Merci

**Comment by TmpName** [comment]
Vstream gere deja Jheberg et multiup, je peux m'occuper de celui la, mais je ne ferais pas le fichier site.
Pour le moment je chercherais plutot a faire du tri.
