### ISSUE TITLE
papystreaming non fonctionnel

### ISSUE THREAD

**Issue by noipo** [Kodi-vStream/venom-xbmc-addons#1465]
lors du choix d'une source rien ne se passe. Une solution ?

**Comment by TmpName** [comment]
Je suis dessus mais il n'y a que si tu passes par le "papyplayer" que ca deconne non ?

**Comment by 1shad** [comment]
Bravo pour le lien youtube.
J'ai pas encore tester, j'attends que ca me propose de mettre à jours.
Mais Je crois qu'ils ont le même type de lien sur skstream, au cas ou...
Merci

**Comment by TmpName** [comment]
Exact, c'est exactement le meme systeme, enfin y a des endroit ou c'est un lien vers ok.ru mais la plupart du temps c'est le meme truc.

**Comment by 1shad** [comment]
Je ne sais pas qui bosse dessus non plus :D,
Mais pour sktream c'est des liens dl-protect, donc il suffit de faire
un head avec le referrer de la page, et recup le header 'location' en retour.
Sauf pour le sktream player ou il faut recupérer le contenu et prendre le 'src' de l'iframe.

**Comment by TmpName** [comment]
C'est deja en place, mais ca doit deconner pr les lien youtube aussi

**Comment by 1shad** [comment]
Quoi qu'il en soit, ca fonctionne bien en modifiant à la main pour papystreaming.
( docid et lien drive google ).
Merci

**Comment by 1shad** [comment]
Salut
Il faudrait remplacer la regex : 
 - sPattern = 'docid=([a-zA-Z0-9]+)'
+ sPattern = 'docid=([\w-]+)'

( Il y a des liens avec ce type de docid: AA-BB-CCCCCCCC )

**Comment by TmpName** [comment]
He merde, je l'ai deja mit sur 2 fichiers cette modifs, je corrige de suite, merci.
