### ISSUE TITLE
Plus aucun lien ou presque ne fonctionne

### ISSUE THREAD

**Issue by Abeillefan** [Kodi-vStream/venom-xbmc-addons#1466]
Bonjour, j'ai Vstream sur kodi 17. J'écoutais la série Koh Lanta, comme il y a de vieilles saisons, je croyais que c'était la raison pour laquelle plusieurs liens n'étaient plus valides. 

Mais là je commence la saison 4 : Orange is the new black. Pratiquement aucun lien ne fonctionne et ceux qui fonctionnent , ça écrit pas d'appuie  pour VGA sur ma télévision...  Que ce passe til?

**Comment by Arias800** [comment]
Bonjour pouvez vous essayer la version beta de vstream peut être que ça peut régler le problème

**Comment by johngf** [comment]
les liens viennent des sites internet donc si ils sont hs on n'y peut rien sinon si tu clic sur des liens
( you watch exashare ou all vid)  #1433

**Comment by TmpName** [comment]
Sur le site filmstrmVK, tu n'as que 2 hebergeur pr la saison 4 mais les 2 fonctionnent.
Sur full-strm, plein de lien fonctionnel aussi.

**Comment by Abeillefan** [comment]
Merci à vous 3, je devrais essayer le Bêta?  

@TmpName , ça fonctionne en VGA ?? Sur ma TV ? Je vais vérifier.  

Merci

**Comment by TmpName** [comment]
Ca, ca depend de ta tv et ta machine, cote logiciel tout est possible avec les bons reglages.

**Comment by Arias800** [comment]
J ai moi ça fonctionne en VGA sous kodi 12 donc ça devrai marche avec kodi 17 :p

**Comment by Turk182es** [comment]
J'avais aussi soulevé ce problème il y a quelques semaine. Fan de série TV des années 80 il est maintenant impossible de retrouver des liens qui fonctionnent, on trouve bien les series mais après on a l'éternel "Fichier introuvable" sur pratiquement tous les liens (Exemple : Wonder Woman)

**Comment by Arias800** [comment]
Oui mais après le problème vient peut etre des site qui n'ont pas de liens donc nous on ne peux rien faire de ce côté là :/

**Comment by Abeillefan** [comment]
@Turk182es ... C'est frustrant d'en essayer 30 et qu'aucun fonctionnent. ;) Il arrive parfois aussi que ça ne fonctionne pas sur Kodi, je cherche sur le net et j'en trouve parfois par chance.  
Dommage que FlashX est... Soit down. Ils constituaient la majorité des liens qui fonctionnaient. 
@TmpName tu avais raison, filmstrmVK , j'ai un lien qui fonctionne en VGA , j'avais du sauter ce site. Merci

**Comment by johngf** [comment]
flash x n'est pas down mais parfois il met longtemps a repondre donc timeout
il crée  ou modif advancedsettings.xml et augmenté le timeout a 60

**Comment by Abeillefan** [comment]
Comment ? 🙈🙉🙊

**Comment by TmpName** [comment]
Yep meme prb pr moi, je regarde plutot des vieux trucs.
Youwtch me manque pas mal, mais c'etait flashX mon gros prb, et effectivement, il est en train de revenir, il etait encore en panne ce WE.

**Comment by Abeillefan** [comment]
Merci tout le monde, avances settings,  j'espère que c'est pas trop compliqué à créer lol :)

**Comment by johnboisvert** [comment]
Moi aussi 3/4 des liens ne fonctionne plus

**Comment by TmpName** [comment]
Donnes plus d'infos stp qu'on puisse tester.
Les liens Ywatch allvd et exashare sont out, et a mon avis ne reviendront pas.

**Comment by Abeillefan** [comment]
Orange is the new black saison 4. Les liens qui fonctionnaient sur filmstreamvk... n'y sont plus :(

**Comment by TmpName** [comment]
Fimstrmvk corrige, en MAJ ce soir.
