### ISSUE TITLE
free-telechargement

### ISSUE THREAD

**Issue by rod93** [Kodi-vStream/venom-xbmc-addons#1467]
bonjour
depuis quelques temps plus de liens free-telechargement.org
y compris avec la derniére version 0.52 merci

**Comment by TmpName** [comment]
Je vais la mettre en MAJ auto, ca va remarcher mais merci de me dire si la recherche visuelle marche encore apres la MAJ stp.

**Comment by rod93** [comment]
Ok je teste et te fais un retour merci

**Comment by rod93** [comment]
Salut la recherche visuelle fonctionne mais toujours aucun liens sur free-telechargement merci

**Comment by TmpName** [comment]
Exact.
Soit je suis tres mauvais pr taper le captcha, soit y a un prb.

**Comment by TmpName** [comment]
Ok, ca remarche chez moi juste en changeant l'url de depart *.co au lieu de *.com

**Comment by rod93** [comment]
Comment tu change l'URL merci

**Comment by TmpName** [comment]
Fichier "free_telechargement_org.py" ligne 24
