### ISSUE TITLE
Le jt des addon version tf1

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1471]
Le site TVAddon est down insit que ça page facebook quelque heure plus tard (source : 
ht tps://torrentfreak.com/kodi-turmoil-continues-as-tvaddons-mysteriously-disappears-170613/)

**Comment by TmpName** [comment]
Lol, ca fait meme pas 24h, attend d'avoir des infos, on est pas sur tf1 ici ^^.

**Comment by Arias800** [comment]
Le dev de Phoenix a annonce arrêter le développement de l add-on suite a la fermeture de tvaddon

**Comment by TmpName** [comment]
C'est pas suite a la "fermeture" de tvaddon, il l'a dit des le debut en meme temps que shani08.

**Comment by Arias800** [comment]
J ai fait exprès de me tromper ça ascentu le cote tf1 :3

**Comment by TmpName** [comment]
Lol, ok, dsl JPP j'ai pas vu le second degres.

**Comment by LordVenom** [comment]
Perso j'ai suivis un peux l'histoire et j'ai limiter la pub c'est tous ceux que je ferais pour le moment

Suppression de la page youtube
Suppression du compte twitter
Suppression du compte Google+

**Comment by TmpName** [comment]
D'apres des sources non confirmées il semblerait que au moins une personne de leur equipe serait a guantanamo. Tout de suite un reportage sur les vacances a cuba.

**Comment by Arias800** [comment]
Pour TV add-on et shani ça se complique actuellement il ont les flic(pu une autre société du type) au cul et tout est bon pour les trouve jusqu'à demande a PayPal des les livre ^^

**Comment by TmpName** [comment]
C'est des men in blacks ?

**Comment by Arias800** [comment]
Oui car shani serai un extra-terrestre qui peux se multiplié et qui a créer TV add-on .bref blague a part mais apparemment se serai les mec qui possède les qui a demandé a la cour des état unis de trouve les responsable et sa apparemment été acceptée ^^

**Comment by Arias800** [comment]
"A US court has just granted a subpoena to help identify a number of prolific add-on developers"

**Comment by TmpName** [comment]
Yep ca j'ai vu aussi, mais je trouve tjours curieux que presque 15 jrs apres on ait tjours pas d'infos officielles, on sait meme pas si tvaddon est definitivement ferme ou pas.

**Comment by Arias800** [comment]
Bah après ça se comprend que TV add-on ne donne pas de nouvelle pour le moment ^^
