### ISSUE TITLE
Petit problème avec les marques pages

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1472]
bonjour,

j'ai ajouté 25 séries en marques pages depuis le site "serie-en-streaming"

tout ce passais bien.

Mais ensuite j'ai ajouté une autre série depuis "librestream" et maintenant je ne peux plus accéder aux marques pages séries et c'est la deuxième fois que je fais la manip.

Dans mes logs j'ai cette erreur :

19:33:22 111.703606 T:1956426672   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=getFav&sCat=2&sFav=getFav&site=cFav&title=S%c3%a9ries%20%5bCOLOR%20lightcoral%5d(25)%5b%2fCOLOR%5d
19:33:22 111.705521 T:1956426672   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=getFav&sCat=2&sFav=getFav&site=cFav&title=S%c3%a9ries%20%5bCOLOR%20lightcoral%5d(25)%5b%2fCOLOR%5d) failed**

Merci d'avance pour votre aide.

**Comment by Arias800** [comment]
J'ai vais eu un bug du même style j ai neyouter le cache et ça a remarcher ^^

**Comment by TmpName** [comment]
Yep de remettre le cache de Vstream a zero corrige le probleme, mais tu perd tout.
Sinon il y a des outils pr editer la base sql.

Si tu choisis la remize a zero, attend un peu stp, je pense avoir trouve le prb, mais dans le cas contraire il me faudrait un fichier a toi.

**Comment by TmpName** [comment]
C'est bon, j'ai trouve, j'ai fait une modif dans favorite.py qui te permettra d'acceder a tes favoris sauf celui qui deconne (et tu ne pourras pas le supprimer encore).

Le prb vient de fichier site, non corrige encore. Si tu utilises un editeur sql tu verras le prb facilement y a du code html dans l'url.

**Comment by TmpName** [comment]
Site corrige aussi.

**Comment by canopre** [comment]
Bonjour,

Merci beaucoup !

J'ai remarqué le même problème avec libertyland et peut-être d'autres : Je vous les signalerais.

Mais encore un grand merci pour votre aide !

**Comment by TmpName** [comment]
Pr libertyland suis pas arriver a le faire deconner.
