### ISSUE TITLE
Navigation impossiblesur une source

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1473]
Bonjour,

Quand je vais sur "toutes les sources" + "LibreStream" +" Séries" : j'ai des erreurs 404 pour chaque liens de la pages "Séries"

par contre les liens "Séries VOSTFR" fonctionnent bien sur la même source.

Merci d'avance.

**Comment by TmpName** [comment]
Ca deconne aussi sur leur site, soit on vire la ligne, soit on attend que ca remarche.

**Comment by canopre** [comment]
Ah OK : Alors je comprends mieux : Merci pour ta réponse ultra rapide !
