### ISSUE TITLE
Bug favorite 

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1474]
Si je mets la series 13 reason why en favoris ça me le mets en temps que film est ce que c est liée au catégories du site ?

**Comment by TmpName** [comment]
Yep ca doit etre un bug du fichier site, c'est quel site ?

**Comment by Arias800** [comment]
Frère telchargement ou dll island

**Comment by TmpName** [comment]
C'est le second, corrige, merci pour l'info.

**Comment by Arias800** [comment]
Merci a tout pour ta rapidité surtout ^^
