### ISSUE TITLE
Ajout section 4K - ZT.ws

### ISSUE THREAD

**Issue by Atomium25** [Kodi-vStream/venom-xbmc-addons#1478]
Bonjour à tous,

J'ai remarqué depuis un certains temps qu'une nouvelle rubrique "4K" avait fait son apparition sur le site ZT.ws, serait-il possible de mettre à jour cette source sur Vstream en y ajoutant ladite rubrique ? 

Cela serait profitable à tous les utilisateurs recherchant du contenu 4K accessible facilement.

Merci d'avance,
Souhaitant une bonne semaine à tous les utilisateurs et développeurs,

**Comment by Arias800** [comment]
Oui c est possible après on ne sais pas combien de blu Ray 4k vont être disponible pour le moment il y "les stroumph 2" et "inferno" donc si la catégorie ne se rempli pas il y a un risque quelques-uns l enlève

**Comment by Atomium25** [comment]
D'accord, en revanche en ce qui me concerne quand je vais sur le site j'ai 31 référence dans la catégorie "4K", j'imagine que c'est suffisant pour reprendre la rubrique sur Vstream ?

**Comment by Arias800** [comment]
Oui mais je parlait dans le futur car les blu Ray 4k sont protégé par un DRM qui s appelle l'aacs 2 et il a longtemps été réputée un violabme sauf jusqu'au 14 mai ou des hacker russe dis l avoir cracker donc si les createur du DRM trouve la faille et la bloque alors finit les version crack pendant un moment

**Comment by TmpName** [comment]
Mais ils trouveront tjours la parade a plus ou moins long terme.
Apres de rajouter ca sur Vstream n'est pas trop dur, ca devrait passer en modifiant meme pas 5 lignes.

**Comment by Arias800** [comment]
Jusqu'à la la parade na jamus été trouve ^^

**Comment by LordVenom** [comment]
Stream du 4K vous avez de bonne connections vous loll

**Comment by TmpName** [comment]
On le fait ou pas ?
Car tu as deja mit l'issue en resolu ?

**Comment by LordVenom** [comment]
Pour 31 films ? non je voie pas l'utilité.

**Comment by Arias800** [comment]
En plus énormément de lien hs ^^
