### ISSUE TITLE
Ajout de lien streaming de catch

### ISSUE THREAD

**Issue by Mcm1k344** [Kodi-vStream/venom-xbmc-addons#1479]
Bonjour tout le monde,
d'abord bravo pour le travail qui est impeccable (j'ai pas eu beaucoup de problème avec mon kodi pour le moment).
Je souhaitais ajouté un site h ttp://ultimate-catch.eu/  mais je bug sur ça : 

 # ("  sPattern = 'class="movie movie-block">")

J'ai regarder sur la source de libre stream pour avoir un exemple je vois bien où le code source à été pris.
Mais pour mon lien je ne vois pas du tout.
Si quelqu'un peut m'aider, cela serait vraiment cool.
Merci

**Comment by TmpName** [comment]
Tu en est ou la ?
Recuperation des titres et images de la video ou carrement du fichier a streamer ?

**Comment by Mcm1k344** [comment]
Bah j'ai regarder le fichier ajoute de source.
J'ai donc regarder les description après le " # ", j'ai modifier les différentes rubriques pour obtenir un menu qui se tient à source.
J'ai mis les différents lien correspondants à mes rubriques, ainsi que le lien. Mon problème c'est dans le code de sPatern comme je l'ai mis ci-dessus. Pour libre stream, j'ai trouvé mais pour mon site j'ai pas trouvé.
Je me demandais si cela était normale, après je trouve que le code source de libre stream et écrit beaucoup plus proprement que celui que de mon site de catch ^^
Peut être que je m'y prends mal aussi, je fais ligne par ligne en suivant les indications, c'est peut être une erreur de ma part.

**Comment by TmpName** [comment]
Alors j'ai toujours pas compris si c'etait la premiere page ou la page de la video mais je ne trouves pas ton tag dans le code.
Moi j'aurais fais ca pr la premiere page
https://regex101.com/r/AX5VEn/1

**Comment by Mcm1k344** [comment]
Alors la je vois de quoi tu parles ^^
Donc si je comprends bien je dois aller récupérer chaque lien pour les intégré dans le fichier source.
Mais je voyais un truc plutôt automatique, dans le même genre que le fichier libre stream ( bah du moins ce que j'ai pu voir il y a peut un autre fichier code.
Je vais regarder cela sinon je comprends mieux le principe et pourquoi cela demande du temps.
Merci à toi.

**Comment by TmpName** [comment]
Le regex change pr tout les sites, et pour le meme site, il peut changer tout les mois. C'est le plus difficile a faire.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source

**Comment by Mcm1k344** [comment]
Oui, j'ai aperçu ce lien en fin d'aprem. Je vais mis attardé un peu plus tard du coup et je vous tiens au courant.
Merci de m'avoir donné un peu de ton temps.

_Sent from my WIKO FEVER using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
