### ISSUE TITLE
pas de metadonnées

### ISSUE THREAD

**Issue by FreeFighter77** [Kodi-vStream/venom-xbmc-addons#1480]
Bonjour, et tres beau boulot de toute la communauté. Je voulais juste vous signaler que les métadonnées ne fonctionne pas sur zone tele .ws . est ce normale ? n y a t il pas un moyen de remédier a cela ?

**Comment by TmpName** [comment]
Je viens de regarder la source, et apparement c'est normal de ne pas les avoir sur la premiere page, mais elle devraient apparaitre sur la seconde non ?

**Comment by FreeFighter77** [comment]
a oui bien vu,n'y a t'il pas moyen de les mettre en première page ? car j utilise des widget ...

**Comment by TmpName** [comment]
Si c'est possible, en fait suffit de regarder l'url et en fonction utiliser oGui.addMovie ou oGui.addTV au lieu de oGui.addMisc.

**Comment by TmpName** [comment]
Testes avec ce fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by FreeFighter77** [comment]
impeccable Tmp toujours au top comme d'habitude !!!!
Je reviens avec une dernière question (peut être compliqué a me faire comprendre) ... 
J utilise des widgets visuels pour faire apparaitre les pochettes, j ai les dessins anime serie films 3d qui se charge en arrière plan,sans aucune fenêtre (sur la page d accueil du skin) pour les films j utilise la source kepliz et elle m affiche une fenêtre 1/59 ... (avec métadonnées activer on est d accord). 
Question n'y a t il pas moyen de masquer cet fenêtre.

Je te remercie par avance de ta réponse bravo a toi et venom que je suis depuis le début, mais également a toute la communauté qui participe a la beta !!!!!!!! dommage plus bcp de tps a moi pour tenter de vous aider comme avant ...

**Comment by TmpName** [comment]
La je peux pas te dire, j'utilise pas les widgets.
Mais tu as le prb pr toute les sources ou que kepliz ?
