### ISSUE TITLE
Je suis encore en version 0.5.2 est-ce Normal ? 

### ISSUE THREAD

**Issue by kikikodi** [Kodi-vStream/venom-xbmc-addons#1481]
J'ai vu que la 0.5.3 est sorti Si je ne me trompe pas
Mon vstream est encore en 0.5.2 ou la télécharger pour le mettre à jour manuellement ?
Merci

**Comment by LordVenom** [comment]
Non elle et pas sortis on en parle juste.

**Comment by kikikodi** [comment]
Ah ok parceque j'ai un soucie, ma box est en 0.5.2 tout fonctionne tout est ok 
Mais j'ai une seconde box qui elle ne teouve plus aucun lien Dans vstream peut importe le site ou le titre en question il y a à chaque fois "..." comment ça se fait ?

**Comment by LordVenom** [comment]
Pas plus d'indication que ça marche pas ?

**Comment by kikikodi** [comment]
C'est à dire ? 
En gros je fais ma recherche ,  par le menu d'u. Titre, sur ma
Première box j'ai donc toute la liste des titres trouvé, ça marche nickel hormis quelques liens hs, comme d'habitude quoi .
Mais sur ma Seconde box android , kodi en 17.3 , vstream apparent à jour puisque 0.5.2  recherche du même titre, ça Check les 27 sources, et la liste est vide ... 
je peux aussi faire une recherche Dans toutes les sources, par exemple film illimité ou autre films hd, j'ai toutes les jaquettes, je clique sur l'une d'elle , et la ou je suis censé avoir les resolvers y'a rien juste "..."

**Comment by LordVenom** [comment]
Aucune idée un log peux être ?

**Comment by kikikodi** [comment]
Une question , quand est-ce qu'est la prochaine maj des sources et resolvers ? Je ne  parle pas de la mensuelle

**Comment by TmpName** [comment]
Je sais pas trop, la y a juste un fichier site de nouveau par rapport a la precedente (et qui va encore chnager bientot), donc personnellement j'attend qu'il y ait plus de fichiers a mettre a jours

**Comment by alfred5959** [comment]
Bonjour, j'ai le même problème que toi kikikodi sur ma box en V17, sur mon ordi en V16 ou mon appleTV en V14, je n'ai aucun problème. A mon avis, c'est lié à V17 mais je ne sais pas pourquoi cela fonctionnait auparavant.

**Comment by TmpName** [comment]
des logs ?

**Comment by bigjojo** [comment]
bonsoir, le probleme viens de la version 17.3, j'avais le meme probleme, je viens de remettre la 17.2 et vstream 0.5.2 et tous fonctionnes de nouveau.
désactivez la mise a jour auto sur les boxandroid et smartphone.
a+

**Comment by TmpName** [comment]
Et personne aurait un log avec le bug ?

**Comment by alfred5959** [comment]
Je veux bien, sans abuser... tu peux expliquer comment faire?

**Comment by TmpName** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils
Partie "log" c'est le plus facile mais c'est pas dit que ca marche.

**Comment by alfred5959** [comment]
Merci TmpName, je suis sur boitier xiaomi et je n'ai pas trouvé comment accéder au chemin spécifié dans la partie log. Je ne sais pas si c'est possible. Si quelqu'un sait, je suis preneur, le boitier est sous android 6.0

**Comment by TmpName** [comment]
Apres il y a pas mal de MAJ sur la future version, elle se fait attendre cette fois, mais elle risque de chnager pas mal de chose.

**Comment by alfred5959** [comment]
Pour ceux qui cherchent une solution, j 'ai installé SMPC est cela fonctionne impec. Bonne soirée

**Comment by kikikodi** [comment]
C'est quoi SMPC?

**Comment by kikikodi** [comment]
Ok je viens de trouver sur internet , mais quelle est la difference on dirait en tout point tkodi,
