### ISSUE TITLE
DDL FRENCH

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1487]
Le site "DDL French" sur Vstream marche plus car il a changer d'adresse. 
Maintenant son Nom est "DDL FR" au https ://  ddlfr .pw/

**Comment by razorex** [comment]
Non c'est pas le même site.

**Comment by luluvulcain** [comment]
Ok je croyais, desolé. Ce Site la est bien donc ca serais bien qui soit dans vstream.

**Comment by Kodigoal** [comment]
Si c'est le même site , les liens films  pointent sur ddlfrench org.
Ont rajoutés films et cie..
Par contre recaptcha à gogo sur les liens donc pas possible , à confirmer...

**Comment by TmpName** [comment]
J'ai teste pas de recaptch a pr les series.
