### ISSUE TITLE
1fichier premuim

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1488]
Y'a til un moyen d'injecter ça :" javascript: var domain = '1fichier.com';var cookies = new Array();cookies['SID'] = 'iZ70jGwo4TI48mVgYFcxBUhFJJUYKv2lgS7GWV67Vpk==MPixajU58zqYYoqEhrz';if (location.href.indexOf(domain)==-1) {var g = confirm('Welcome ' + domain + ' page. Copy again the script to address bar and run again this script . Continue?');if (g) {location.href = 'http://' + domain;}} else {alert("Enjoy, for more premium accounts visit h ttp://premiumaccounts.me/");for(var i in cookies){void(document.cookie = i+'='+cookies[i]+';domain=.'+domain+';path=/;');}location.href = 'http://'+domain;}" dans l'url directement depuis vstream ?

**Comment by TmpName** [comment]
Pas trop compris ce que tu veux faire ? Y a un bug ?
C'est du code javascript donc rien a voir avec une url, mais y a moyen de rajouter un cookie si c'est ca que tu cherche a faire ?

**Comment by Arias800** [comment]
En gros  e serai d exécuter ce code sur 1fichier pour avoir un accès premium sans`Compte^^

**Comment by TmpName** [comment]
Tu as le fonction GetHtmlwithcookies() dans premiumHandler.py, ca recupere une page html avec un cookie en parametre.
Le cookie est juste une chaine "SID=Yao29yrd=aPl7vlnd4XFGSSEfeY9ADDYZnz42cxjEQUxNqvz0ziIzBBOOp;"

**Comment by Arias800** [comment]
Mon cookies c'est ça "SID='iZ70jGwo4TI48mVgYFcxBUhFJJUYKv2lgS7GWV67Vpk==MPixajU58zqYYoqEhrz" donc je doit le mettre comme paramétré pour GetHtmlwithcookies() ?

**Comment by TmpName** [comment]
onefichier.py ligne 110
api_call = url + '|Cookie=SID=Yao29yvfdgfdggd'

Mais il faut que ca passe par le mode premiun donc fait toi un compte gratuit ca t'evitera d'avoir a modifier le code.
Vstream te veras enregistre donc passera par le mode premium, utilisera ton acces gratuit pr se connecter mais prendra ce cookie pour obtenir le fichier.

Maintenant pour info les cookies sont souvent associe a une ip ou un navigateur. Le fonctionnement de 1fichier depend de la configuration utilisateur associe a ce cookie.

**Comment by TmpName** [comment]
Testes deja le cookie via navigateur pr voir si ca vaut la peine de te fatiguer ^^.

**Comment by Arias800** [comment]
Il fonctionnait hier soir a voir si il marche toujours ^^
