### ISSUE TITLE
Problème avec plusieurs site

### ISSUE THREAD

**Issue by helpmoi** [Kodi-vStream/venom-xbmc-addons#1493]
Bonjour, je ne sais absolument pas ouvrir un seul film dans vstream. Avant tous fonctionnait correctement. Cela ne fonctionne ni sur ma tablette ni sur mon gsm et mon Androidbox. Par exemple les fill de streamay ne s'ouvre pas par contre les films s'ouvrent sans soucis sur leur site donc ça ne viens pas du site...

**Comment by razorex** [comment]
Slt. tu fais les mise à jour??

**Comment by helpmoi** [comment]
Bizarre pourtant je fais les mises a jours...

**Comment by TmpName** [comment]
Tout depend des MAJ https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour

**Comment by razorex** [comment]
Avec le repo? ou avec le fichier vStream?

**Comment by helpmoi** [comment]
Je le fais avec Vstream. Donc le message vert qui apparaît tous en bas...

**Comment by TmpName** [comment]
Tu as un accent dans tes noms de repertoire ?

**Comment by helpmoi** [comment]
Non je n'en avais pas. J'ai résolu mon problème en désinstallant vstream et en le réinstallant.
