### ISSUE TITLE
Evilox et recherche

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1498]
Hello

Si je rajoute Evilox à la liste des sites : Quand je lance une recherche de série : Il y a une erreur 404 et aucun (ou presque aucun) résultat.

Merci pour votre aide.

**Comment by Kodigoal** [comment]
En même temps evilox c'est juste un site  de vidéos droles ... pourquoi le rajouter à la liste des sites ?

**Comment by TmpName** [comment]
C'est un choix ^^.
Mais dans tout les cas la recherche est a faire, en fait elle n'a jamais ete sur le fichier.

**Comment by TmpName** [comment]
Testes avec ce fichier 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/evilox.py
