### ISSUE TITLE
décrypter (Pyobfuscate )

### ISSUE THREAD

**Issue by homayon50** [Kodi-vStream/venom-xbmc-addons#1499]
Bonjour , 
je travaille depuis quelque temps sur les addon Kodi, je suis embêter par un fichier et je n'arrive pas a comprendre avec quel méthode cryptologie a était crypter le ficher de cette addon .j'aimerais bien le décrypter mais je vois pas comment j'ai  un peu.. tout essayer

j'ai une version précédent de ce ficher qui n'est pas crypter je mets tout en pièce jointe ,si quelqu'un pourrais m'aider ce sera vraiment sympa .
je tiens a remercier la team vStream pour ce beau travail . 
[default.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1117334/default.zip)
Et voici le addon : 
[repository.persia-1.0.4.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1117342/repository.persia-1.0.4.zip)

**Comment by homayon50** [comment]
Et voici le addon : 
[repository.persia-1.0.4.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1117342/repository.persia-1.0.4.zip)

**Comment by TmpName** [comment]
Ce n'est pas  du cryptage mais de "l'obfuscation" (connais pas le mot en francais).
Et ca a l'air d'etre du fait maison, donc tu n'as pas le choix ^^, soit tu lis le code comme il est, soit tu passes plusieurs heures a le nettoyer.
Mais le code est lisible, il est juste ecrit de maniere a etre chiant a lire.

**Comment by homayon50** [comment]
Merci beaucoup pour votre réponse ,Franchement j'ai passer beaucoup de temps pour pouvoir nettoyer ce code mais le probleme c'est que j'arrive pas a tout déchiffre ..,et j'ai vu cette méthode utiliser dans plusieurs addon ,je me dis que il doit bien avoir quelque choses pour décoder tout ca ^^

**Comment by homayon50** [comment]
Je viens de voir que la méthode utiliser est Pyobfuscate  cependant je ne trouve rien pour retourner vers le code source de base !

**Comment by Kodigoal** [comment]
Tu ne peux pas ... 
Faut le faire manuellement en s'aidant des anciens .py non crypté pour avoir les bons noms des  class et cie , et encore t'auras pêtre pas tout.
Comment tu veux faire du reverse sur '  class I1IiI ' ?
Avec l'ancien .py on  vois le vrai nom de la class , mais sinon faut changer tous les 'I1IiI' avec un autre nom par exemple et basta.
C'est pour faire quoi la source décryptée ?
Et pourquoi il a  crypté d'ailleurs ? peur de quoi?

**Comment by homayon50** [comment]
c'est ce que je me disais aussi...
bon ce soir j'ai passer 5h à déchiffrer j'ai mal au yeux Lol... j'ai pas tout fini en faite je viens de comprendre que il a tout simplement embrouiller  le code et il a mis en place une système de login ,  .

Pour mieux vous aider a comprendre pour quoi ce addon a était crypter ,de base cette addon à était créé par un site Persan pour les persan qui sont en dehors de pays qui regrouper quelque site de film,serie,..sa rejoind l'idee de Vstream et il etait 100% gratuite , le site à était malheureusement dows du jour au lendemain et le projet à était abandonnée  , cependant  une personne a voler le projet et il rendu payant..

Mon but est de crée quelque chose de gratuit pour les gens et pour ma famille ,c'est vrai que je suis nul en programmation (python ),masi bon j'essaye de faire quelque chose pour faire plaisir au gens .

Si quelqu’un pourrais m'aider a ajouter cette partie  sur mon ficher default avec les classe concernée  ca serra vraiment sympa 
```
addDir ( 'Manoto DVR' , '' , 500 , artpath + 'manotodvr.png' , fanart , 'Manototv.com Aired videos (DVR) ...' , genre , date , credits , 'source' )
   addDir ( 'TV Channels DVR' , '' , 510 , artpath + 'tvchannelsdvr.png' , fanart , 'Watch TV Channels Aired videos (DVR) ...' , genre , date , credits , 'source' )
   addDir ( 'Film/Serial/Mostanad' , '' , 98 , artpath + 'new.png' , fanart , 'Movies , Series , Shows and Documentary archive ...' , genre , date , credits , 'source' )
   addDir ( 'Movies & Series' , '' , 600 , artpath + 'intfilmseries.png' , fanart , 'International Movies & Series Archive ...' , genre , date , credits , 'source' )
   addDir ( 'Sports' , '' , 90 , artpath + 'sports.png' , fanart , 'A list of sport channels' , genre , date , credits , 'source' )
```
Voici ce que j'ai décrypter pour l'instant :
[default en cours de cryptage .zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1118239/default.en.cours.de.cryptage.zip)

**Comment by TmpName** [comment]
Rajouter quoi ? le code est present dans ton fichier decrypte, non ?

**Comment by homayon50** [comment]
Merci Beaucoup j'ai réussi à le faire fonctionner et recouper ce que je voulait ,quelqu'un a des forum a me conseiller pour les développeur d'addon ou des chose comme sa ?

**Comment by TmpName** [comment]
Malheureusement non, si tu trouves ca m'interesse aussi. En general les forums sont plutot mort ou consacres a leurs propres addons.
Le forum officiel de kodi, si tu as besoin de rien, tu peux y aller.

**Comment by homayon50** [comment]
J'ai trouver ce forum si ca peux servir a d'autre personne : https://forum.mpdb.tv/

d’ailleurs j'ai un probleme avec la création de mon Repository  :
https://forum.mpdb.tv/index.php/topic,35500.html?PHPSESSID=b6deea8c39c0eaf41744455306b26cfb
