### ISSUE TITLE
Plus aucun lien ni Source

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#1500]
J ai installé  le repo de vstream de github et puis de là installé Vstream mais rien ne marche

Par recherche il ne cherche pas sur toute les sources, alors que sur certains c'est sur qu il y a la serie (tout est bien sélectionné dans parametre chez tout coché)

Si je vais dans chaque source pour recherche soit ça trouve pas soit lya aucun lien ou le lien hs

En gros c'est devenu très limité et buggué et je parle meme pas du temps  de chargement des sous menu de vstream

Donc ya t il une panne ou le vstream du repo est corrompu.

Pas de nouvel de 0.5.3?

**Comment by TmpName** [comment]
Alors, d'abord desole, je sais pas ce qui s'est passe, mais en general on recoit une notification en cas de nouvelles issues, et je n'ai recus aucune notification pour les 3 issues que tu as cree.

Tu n'aurais pas un caractere accentue dans ton repertoire ?
Le github contient la future version , tu peux l'installer sans probleme, mais il faut bloquer la mise a jour.
Apres il y a une seconde MAJ celle des fichier sites et hosts, (tout les 3 jours)
cf https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour
