### ISSUE TITLE
Sources 1fichier et Uptostream

### ISSUE THREAD

**Issue by sribou** [Kodi-vStream/venom-xbmc-addons#1501]
Bonjour,

J'ai un soucis avec les sources 1fichier en premium dont voici ma log : 

15:21:32.464 T:11120  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_ws and call function Display_protected_link
15:21:32.515 T:11120  NOTICE: 	[PLUGIN] Vstream: DecryptDlProtecte : htt ps://ww w.dl-protecte.com/123455601123455603123455610123455615123455617stdxaa4j0y
15:21:32.960 T:11120  NOTICE: 	[PLUGIN] Vstream: Table initialized
15:21:34.284 T:2788  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
15:21:34.299 T:2788  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
15:21:34.324 T:2788  NOTICE: 	[PLUGIN] Vstream: Hoster - play htt ps://1fich ier.com/?stdxaa4j0y
15:21:34.346 T:2788  NOTICE: 	[PLUGIN] Vstream: Utilise compte premium pour hoster onefichier
15:21:34.456 T:2788  NOTICE: 	[PLUGIN] Vstream: Auhentification reussie
15:21:34.457 T:2788  NOTICE: 	[PLUGIN] Vstream: h ttps://1fic hier.com/?stdxaa4j0y|Cookie=SID=q1fxo5TWT2eIJ1FyvJ6CUif6q3hRzrx=sa0Df4RBD4OXbfZzsVEfsoTwFPg7yf5I;
15:21:34.477 T:2788  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
15:21:34.478 T:2788  NOTICE: 	[PLUGIN] Vstream: player initialized
15:21:34.493 T:2788  NOTICE: 	[PLUGIN] Vstream: Player use setResolvedUrl() method
15:21:34.772 T:8120  NOTICE: VideoPlayer: Opening: http s://1fichi er.com/?stdxaa4j0y|Cookie=SID=q1fxo5TWT2eIJ1FyvJ6CUif6q3hRzrx=sa0Df4RBD4OXbfZzsVEfsoTwFPg7yf5I;
15:21:34.772 T:8120 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:21:34.962 T:9020  NOTICE: Creating InputStream
15:21:35.600 T:9020  NOTICE: Creating Demuxer
15:21:35.703 T:9020   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, htt ps://1fichi er.com/?stdxaa4j0y
15:21:35.703 T:9020   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
15:21:35.703 T:9020  NOTICE: CVideoPlayer::OnExit()
15:21:35.704 T:8120   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=Chez+Nous+%5BCOLOR+violet%5D1Fichier%5B%2FCOLOR%5D&sHosterIdentifier=onefichier&sTitle=Chez+Nous+%5BCOLOR+violet%5D1Fichier%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2F1fichier.com%2F%3Fstdxaa4j0y&sFav=play&sMediaUrl=https%3A%2F%2F1fichier.com%2F%3Fstdxaa4j0y&sCat=4&sId=cHosterGui&sFileName=Chez+Nous]
15:21:35.718 T:8120  NOTICE: CVideoPlayer::CloseFile()
15:21:35.718 T:8120  NOTICE: VideoPlayer: waiting for threads to exit
15:21:35.718 T:8120  NOTICE: VideoPlayer: finished waiting
15:21:35.718 T:8120  NOTICE: CVideoPlayer::CloseFile()
15:21:35.718 T:8120  NOTICE: VideoPlayer: waiting for threads to exit
15:21:35.718 T:8120  NOTICE: VideoPlayer: finished waiting
15:21:35.793 T:2788  NOTICE: 	[PLUGIN] Vstream: player stoped

Oui, en Web via mon navigateur, le fichier existe et fonctionne.

Avant cela fonctionnait mais depuis quelques temps, plus moyen d'utiliser la source 1fichier

Et quand j'essaie uptostream, au bout de 90/120 min, ça s’arrête. Donc je commence un film et pas moyen de le finir :'-( donc du coup je passe sur kepliz en google drive mais la qualité est souvent en dessous

Merci de votre aide

**Comment by TmpName** [comment]
Aucun prb de mon cote (avec un autre fichier). Telecharges le fichier et essaye de le lire avec kodi.
Essayes de voir le format du fichier si ca ne marche pas, c'est surement un format dash.

Uptostrm coupe tout au bout d'un moment en version gratuite.

**Comment by sribou** [comment]
Je viens de faire un test et KO sur Uptobox avec compte premium. Sans le premium tout est OK :
_17:46:44.146 T:13872  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
17:46:44.176 T:13872  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://uptobox.com/rpaqxse48y1u
17:46:45.937 T:13872  NOTICE: 	[PLUGIN] Vstream: Utilise compte gratuit pour hoster: uptobox
17:46:50.015 T:13872  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
17:46:50.015 T:13872  NOTICE: 	[PLUGIN] Vstream: player initialized
17:46:50.031 T:13872  NOTICE: 	[PLUGIN] Vstream: Player use setResolvedUrl() method
17:46:52.020 T:1700  NOTICE: VideoPlayer: Opening: http://www66.uptostream.com/3l335mb4ff6/360/0/video.mp4
17:46:52.020 T:1700 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:46:52.586 T:492  NOTICE: Creating InputStream
17:46:52.672 T:492  NOTICE: Creating Demuxer
17:46:55.615 T:492  NOTICE: Opening stream: 0 source: 256_

Mais ca coupe au bout d'un certain temps

Mais avec Premium :
_17:48:03.289 T:13076  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
17:48:03.297 T:13076  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
17:48:03.336 T:13076  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://uptobox.com/rpaqxse48y1u
17:48:04.947 T:13076  NOTICE: 	[PLUGIN] Vstream: Utilise compte premium pour hoster uptobox
17:48:05.166 T:13076  NOTICE: 	[PLUGIN] Vstream: Table initialized
17:48:05.197 T:1700   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=The+Wizard+Of+Lies+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sHosterIdentifier=uptobox&sTitle=The+Wizard+Of+Lies+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&siteUrl=http%3A%2F%2Fuptobox.com%2Frpaqxse48y1u&sFav=play&sMediaUrl=http%3A%2F%2Fuptobox.com%2Frpaqxse48y1u&sCat=4&sId=cHosterGui&sFileName=The+Wizard+Of+Lies]
17:48:13.389 T:12200  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
1_

C'est bizarre ou je fais quelquechose de mal ? Pour info, urlresolver N'est PAS actif

Et pour 1Fichier, j'ai 2 potes qui ont le même problème que moi (c'est d'ailluers pour ce que je me tourne vers le vous) : 
1. Lancement 1fichier
2. Premium reconnu
3. Rien et quelque soit le fichier/film/serie mais via le lien, par le navigateur ça fonctionne
Exemple : https://1fichier.com/?stdxaa4j0y

En parallèle, je télécharge le fichier et vous tient au courant.

Merci.

**Comment by TmpName** [comment]
Dans le compte uptostrm

A desactiver:
téléchargement direct et téléchargement ssl

**Comment by sribou** [comment]
Malheureusement, ca marche pas non plus :

_20:46:11.216 T:1316  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:46:11.324 T:1316  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_ws and call function Display_protected_link
20:46:11.443 T:1316  NOTICE: 	[PLUGIN] Vstream: DecryptDlProtecte : https://www.dl-protecte.com/123455600123455602123455610123455615morzvjxm1z4g
20:46:12.399 T:1316  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:46:14.257 T:5588  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:46:14.327 T:5588  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
20:46:14.411 T:5588  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://uptobox.com/3y7wc74z9zal
20:46:20.620 T:5588  NOTICE: 	[PLUGIN] Vstream: Utilise compte premium pour hoster uptobox
20:46:20.929 T:5588  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:46:20.957 T:5228   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=L.A.+Rush+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sHosterIdentifier=uptobox&sTitle=L.A.+Rush+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&siteUrl=http%3A%2F%2Fuptobox.com%2F3y7wc74z9zal&sFav=play&sMediaUrl=http%3A%2F%2Fuptobox.com%2F3y7wc74z9zal&sCat=4&sId=cHosterGui&sFileName=L.A.+Rush]
20:46:32.402 T:8548   ERROR: Unable to find plugin
20:46:32.402 T:5228   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
20:46:32.403 T:5228   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
20:46:46.113 T:5228   ERROR: Control 55 in window 10025 has been asked to focus, but it can't_

mais OK sans mon compte :

_20:47:13.472 T:6704  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:47:13.572 T:6704  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
20:47:13.651 T:6704  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://uptobox.com/3y7wc74z9zal
20:47:15.548 T:6704  NOTICE: 	[PLUGIN] Vstream: Utilise compte gratuit pour hoster: uptobox
20:47:18.802 T:6704  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
20:47:18.803 T:6704  NOTICE: 	[PLUGIN] Vstream: player initialized
20:47:18.824 T:6704  NOTICE: 	[PLUGIN] Vstream: Player use setResolvedUrl() method
20:47:22.638 T:5228  NOTICE: VideoPlayer: Opening: http://www18.uptostream.com/3l8y0pq0a90/1080/0/video.mp4_

**Comment by TmpName** [comment]
L'info devrait servir ^^ merci.
