### ISSUE TITLE
Recherche visuelle HS

### ISSUE THREAD

**Issue by Moyounnet37** [Kodi-vStream/venom-xbmc-addons#1502]
Bonjour, 

Depuis la dernière mise à jour (au minimum), lorsque je vais dans "Recherche Visuelle", j'ai un message "Erreur vStream. Consulter le journal pour plus d'information".

Voici le journal : 
[Kodi.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1122980/Kodi.txt)

Je vois bien qu'il y a quelques erreurs, mais je ne sais pas comment les résoudre. Le problème se pose sur la version Windows que j'ai installé, mais également sur la version "Google TV".

J'utilise Kodi 17.3.

Si quelqu'un a une idée, je suis preneur. 

Merci d'avance pour votre aide.

**Comment by Kodigoal** [comment]
Tu as le fichier tmdb.py présent dans
D:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\ ?
(pour windows)

**Comment by LordVenom** [comment]
Fait un Clear cache addon  : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

Puis reinstaller l'addon depuis le repository.

**Comment by Moyounnet37** [comment]
Merci LordVenom, l'idée était la bonne. 

En fait, VStream ne se mettait plus à jour. Ma version était bloquée en 0.4.5 et ne détectait plus les mises à jour. J'avais beau la réinstaller, ça ne fonctionnait pas, et pour cause, je ne repartais pas d'un repository mais d'un zip un peu plus vieux.
A croire qu'il y a eû un problème dans le chainage des mises à jours, et que les vieilles versions ne pouvait se mettre à jour que jusqu'à la 0.4.5.

Merci.

**Comment by LordVenom** [comment]
Change ta version du repository il te faut celle la 

https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository
