### ISSUE TITLE
Médiathèque  Service tv et film

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#1503]
Je me demandais si il est possible de mettre une serie tv (ou film) dans la médiathèque de kodi pour etre averti des mise a jour ?

**Comment by TmpName** [comment]
Nope.
On a commence un truc avec trakt, ca peut te donner les dates de sorties des series ou t'en proposer d'autres, mais ce sera toujours les sorties americaines. Impossible de savoir quand elle sera en place sur un site de strm FR.

Et aller verifier a chaque connexion si la page a changee sur un site ralentirait le fonctionnement, et ne serait pas fiable vu comme certains sites changent vite.
Difficile dans ce cas de faire mieux que l'intervention humaine.
