### ISSUE TITLE
Besoin d'aide pour libre-stream

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1504]
J'ai rajouté la langue pour les séries mais je voudrais ne pas l'afficher quand ont sélectionne les menus VF et Vostfr. ça fonctionne pour un type (en 2eme position) mais pas l'autre. j'ai fais plein d'essai mais pas moyen.

 le pastebin [ici](https://pastebin.com/R4nd9V6H)

**Comment by TmpName** [comment]
Et en remplacant le 'or' par un 'and' ?
`if not '/vostfr/' and not '/version-francaise/' in sUrl:`

**Comment by razorex** [comment]
testé j'affiche plus la langue.. c'est le premier not qui ne fonctionne pas.

**Comment by TmpName** [comment]
Ca marche chez moi, enfin ca supprime vf et vostfr si on choisit la langue, et si on prend "dernier ajout" ca l'affiche.
C'est pas ca que tu essayes de faire ?

**Comment by razorex** [comment]
ben si ça marche as chez moi!!!!!! truc de dingue...

**Comment by TmpName** [comment]
Oups ^^ loupage.

`if not '/vostfr/' in sUrl and not '/version-francaise/' in sUrl:`

**Comment by razorex** [comment]
ben même çà je pensais avoir essayer. la sa marche merci pour ton aide. j'ai du esayer avec le "in sUrl" et le "or" mais pas le "and".
