### ISSUE TITLE
cloudy.py

### ISSUE THREAD

**Issue by 1shad** [Kodi-vStream/venom-xbmc-addons#1509]
Bonjour,

Il faudrait modifier le hoster cloudy.py pour que ca fonctionne, surement après une maj.
Sinon les sources n'apparaissent plus dans le code de la page.

ligne 56: ( ajout en fin de ligne )
`self.__sUrl = 'https://www.cloudy.ec/embed.php?id=' + str(self.__sUrl) + '&playerPage=1'`

-edits-
Et s'assurer que l'url est bien nettoyée juste au dessus.
`import re`
`self.__sUrl = re.sub( r'&\w+=\d',  '', self.__sUrl )`

Dans le cas où l'url de base est comme ca par exemple:
`http://www.cloudy.ec/embed.php?id=123456abcdefg&playerPage=1&autoplay=1`

**Comment by TmpName** [comment]
Mit a jour, merci ^^.
