### ISSUE TITLE
Lien non fonctionnel

### ISSUE THREAD

**Issue by Alex2450** [Kodi-vStream/venom-xbmc-addons#1514]
Bonjour, depuis quelque semaine j'ai plusieurs lien qui ne fonctionne plus comme par exemple tout ce qui vient de youwatch ne fonctionne plus.
Est-ce que c'est juste moi ou c'est normal et est-ce que je peux faire quelque chose pour régler le problème.

Merci

**Comment by TmpName** [comment]
Youwatch est mort ainsi que allvid et exashare.
Streaminto est en train de mourrir aussi je pense (si c'est pas deja fait)

**Comment by Mcm1k344** [comment]
Moi perso il y a pas longtemps je dirais deux ou trois m. J'ai utilise un lien youwatch

**Comment by TmpName** [comment]
J'ai plus les dates en tetes, mais ca doit correspondre.
Leur site est encore la, mais plus aucune videos.

**Comment by laquarico** [comment]
Bonsoir est ce qu il y a un problem aussi avec akadmi? Y a plus aucune source!!! Toute mes series manga etait sur ce site

**Comment by TmpName** [comment]
Adkami a refait leur site, pas mal de modif a faire.

**Comment by laquarico** [comment]
Merci donc il faut juste parienter et les liens vont revenir ou comment je dois faire pour retrouver le nouveau site sur vstream

**Comment by TmpName** [comment]
Faut qu'on refasse le fichier site ^^. Y en a pr un moment.

**Comment by laquarico** [comment]
Oh wow en tout merci merci poir le travail que vous faites vous etes des
strars!!! Je suis sur que je vais trouver une alternative!!! Bonne chance

**Comment by TmpName** [comment]
Nouveau fichier adkami a tester https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/adkami_com.py

**Comment by laquarico** [comment]
Comment ca marche? Set ce c est directement sur vstream ou je Doris
telecharger ce lien sir mon stick?

**Comment by TmpName** [comment]
Faut rempplacer l'ancien fichier par le nouveau.
Mais laisse tomber, je le passe en MAJ auto, tu l'auras dans max 3 jours.

**Comment by laquarico** [comment]
Wow vraiment merci mais pas besoin de te donner tant de mal...vraiment le
suivi de ce site c est superbe!!! Moi qui suis completement inutile encore
merci poir tout le travail que vius faites les admin

**Comment by Alex2450** [comment]
Merci pour toute vos réponse
c'est beaucoup plus claire maintenant
Si les lien ce remettre a fonctionner j'appréciais que quelqu’un l'indique sur le fil de discutions.

Merci

**Comment by TmpName** [comment]
Ben normallement tout ceux qui marchent encore devraient fonctionner.
A part FlashX qui reste a verifier. Mais j'ai pas tout teste.
