### ISSUE TITLE
Television sur vstream

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1515]
Ça serait bien d'installer une source manuellement comme Livestreampro dans la Rubrique 
"Télévision/Radio" pour par exemple avoir AllFrTV sur Kodi comme RSIPTV la fait dans son extension.

**Comment by TmpName** [comment]
Ben justement, il y a un autre addon pr ca ^^.
Sinon de memoire ou je confond avec celle de racacax mais tu peux meme utliser l enregistreur iptv (ou un nom comme ca) et ca marche comme un tuner.

**Comment by Arias800** [comment]
Effectivement sur l'appli de racacax ont peux enregistrer mais comme je l'ai dit sur l'autre post il vaux mieux utiliser l'application de racacax que le kodi

**Comment by TmpName** [comment]
Nope, ce que je veux dire c'est qu'il genere une liste de lien directement lisibles dans kodi, sans utiliser d'addon. Donc on peut mettre son lien directement dans le "truc" de kodi qui apparait par defaut tout a gauche > "TV", et tu choisis la chaine comme sur une tv normale.

**Comment by Arias800** [comment]
ah oui IPTV Simple Client par exemple

**Comment by TmpName** [comment]
Yep c'est ca ^^.
