### ISSUE TITLE
Comment fait on pour changer flux audio

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#1516]
Bonjour à tous j’espère que vous allez tous bien?

Comme stipuler dans le titre voilà dimanche passé j'ai regardé la chute de la maison blanche et j'ai trouvé un lien en 1080P qui me proposer 3 flux audio le VFF+VFQ+ENG quand je lance le lien le film se lance mais en flux audio anglais comme j'ai un peut l'habitude avec Vstream je sais ou il faut changer pour le mettre en VFF sauf que là pas moyen de changer la langue est ce que quelqu'un aurait une solution merci.

Et autre question et ca c'est plus de la curiosité mais comment se passe l'avancement de la version 0.5.3?

Mille merci pour vos réponses

**Comment by TmpName** [comment]
Pour le 0.5.3, le boss est en vacances, donc pas de dates du tout.
Pr ton lien il te faudrait voir directement sur le site en question, les sous titres peuvent etre dans un fichier anexes mais la langue .... , a part les fichiers dash, je n'ai jamais vu ca.

L'option de kodi en bas a droite n'a pas marché si j'ai bien compris ?

**Comment by patoche2025** [comment]
Bonjour @TmpName 

Tout d'abord merci pour ta réponse à mes 2 questions.

Et sinon désolé d'avoir posé la question sur le flux audio car je viens de refaire le teste est j'arrive à changer la langue, je ferais le teste aussi sur ma box android.

Un tout grand merci à toi
