### ISSUE TITLE
VStream + SuperFavorites

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1517]
Bonjour à tous,

SuperFavorites est un addon très pratique et pas mal utilisé par la communauté Kodi.

Malheureusement quand j'active le context menu de superfavorites : il n'apparait pas et celui de Vstream n'est plus visible.

Y'a t'il une solution (un réglage) pour faire cohabiter ces 2 addons ou pourriez-vous svp prévoir de les rendre compatibles dans une future version ?

Pour les utilisateurs de SuperFavorites : Ce sera beaucoup plus simple et efficace que d'utiliser les marques pages.

Merci d'avance et encore merci à toute la communauté VStream !

**Comment by LordVenom** [comment]
Bonjour, Le temps de réfléchir à la question est non l'addon ne peux pas dépendre d'un addon que l'on ne gere pas, ont n'a déjà eu trop de soucis avec ce genre de chose.

**Comment by canopre** [comment]
Ok : je comprends : mais c'est dommage de "bloquer" SuperFavorite dans Vstream : En général il est disponible dans le menu contextuel de "tous" les addons.
D'ailleurs il n'est pas vraiment bloqué dans Vstream : On peut l'utiliser pour SuperFavoriter des sources mais pas des vidéos.
Dans tous les cas, comme je n'y comprends pas grand-chose en programmation : je vous fais confiance pour choisir la meilleure solution :)

**Comment by Arias800** [comment]
Perso j'utilisais super favoris et si je voulais accéder au menu de vstream j ouvrait deux fois le menu contextuel a la suite et il apparaissait
