### ISSUE TITLE
KODI freebox

### ISSUE THREAD

**Issue by harrynou123** [Kodi-vStream/venom-xbmc-addons#1518]
Salut la team vStream après plusieurs recherche je n'ai rien trouver .
Je souhaiterais rendre disponible l'application KODI sur la Freebox révolution (v6) depuis le FREESTORE.
Malheureusement pour moi je ne sais pas comment rendre compatible KODI sur la Freebox .
Je sais que mon post est mal placé mais je ne connais pas d'autre team francophone qui connaissent et savent programmer avec KODI.

MERCI de vos réponses.

**Comment by harrynou123** [comment]
S'il vous plait même si je sais que le but de cette team est de coder pour vStream ne me laissez pas tomber.

**Comment by LordVenom** [comment]
Aucune idée dsl

**Comment by luluvulcain** [comment]
Salut harrynou123, pour ton problème, tu as la Freebox Mini 4K. 
Informations à lire au http://www.universfreebox.com/article/30715/Freebox-Mini-4K-l-appli-a-tout-faire-Kodi

**Comment by harrynou123** [comment]
je sais bien que la freebox 4K serait une solution mais je ne peux pas changer de freebox

**Comment by harrynou123** [comment]
Je préférais rendre compatible l'application sur la freebox.
Vous ne connaissez pas un forum dédié au application freebox ?

**Comment by LordVenom** [comment]
dsl mais la ont vas pas pouvoir t'aider, aucun rapport avec vStream et aucune idée du fonctionnement de la freebox c'est pas du python lol.
