### ISSUE TITLE
Pas de liens fullstream 

### ISSUE THREAD

**Issue by pjil62** [Kodi-vStream/venom-xbmc-addons#1519]
Bonjour à vous 

Je sais pas si c'est ici qu'il faut poster

Voilà quand je vais dans catégorie  film selectione full stream aucun liens dans vostfr vo et vf
Dans les autres catégories de source pas de soucis. 

Le problème viens que de fullstream.

Pouvez m'aidez à résoudre ce problème

**Comment by Arias800** [comment]
Chez moi ça marche verifie que tu a la dernière version du fichier

**Comment by TmpName** [comment]
Moi j'ai pas compris pr ou tu passes ?
Si je passe par "film" je peux pas selectionner fullstream, et encore moins la langue.
D'ailleurs c'est bizarre mais dans "film" je pensais y trouver "vostfr" et "vf" et y a pas.

**Comment by Arias800** [comment]
Dans film (genre) il y a tout en bas de la liste la ligne "EN VOSTFR" et je pense que c'est la (même si le site redirige des résultat bidon)

**Comment by pjil62** [comment]
Oui dernière version 5.2

Install du repo 0.2 sur kodi krypton la même chose

Jai pas de lien dans full stream kodi

Sinon quelle version est la.dernière ?

**Comment by TmpName** [comment]
Toujours pas vu de problemes ?
Il ya une MAJ ponctuelle, mais normallement le fichier date de 3 mois, donc il devrait etre a jours.
Indiques nous par ou tu passes stp ?

**Comment by razorex** [comment]
la 0.52, oui les langues sont bien traités en "genres"

**Comment by TmpName** [comment]
C'est bon j'ai trouve.

**Comment by TmpName** [comment]
Nouvelle version https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/full_stream_org.py

Y a encore un probleme que je ne comprend pas, il affiche d'abord les films et apres les langues, alors qu'il les traitent dans l'ordre. Et j'ai pas teste pour un film ayant les 2 langues mais ca doit donner un truc chelou.

Y a pas quelqu'un  qui aurait programme un tri des resultats quelque part dans le core ?

**Comment by razorex** [comment]
?????? je viens de tester ton fichier et je comprend pas ton pb. moi sa m'affiche les langues(vostfr, vo, vf) et si dispo les liens sous la langue

**Comment by TmpName** [comment]
Nope, les series fonctionnent.
C'est les films qui ne marchent plus, qu'importe la langue, plus de lien a la fin.

**Comment by razorex** [comment]
Ben moi j'ai la deuxieme version
VOSTFR
lien1
lien2
etc..
VF
lien1
lien2
etc....

**Comment by TmpName** [comment]
Lol, bon ok ca doit venir de mes reglages alors ?
Mais du coup pas de bugs, ca marche (j'ai teste sur les derniers films) ?

**Comment by pjil62** [comment]
Résolu merci à vous tous.

**Comment by johngf** [comment]
@TmpName ce décalage est toujours présent sur plusieurs site je pense que c'est a cause de la modif de gui (mode par liste)

**Comment by TmpName** [comment]
Ha ?
C'etait quoi la modif si tu t'en souvient ?
Cette semaine je suis pas trop la, je prepare mes vacances, et dans une semaine je pars pour une autre semaine.

**Comment by johngf** [comment]
[la](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/gui.py#L50) et la [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/gui.py#L303) a voir si en utilisant l'ancienne méthode le problème est résolu ou pas (pas testé)
ou alors c'est le fait d'utiliser oGui.addText dans la meme boucle que oGui.addTv ou Movie qui bug avec le mode listing

**Comment by TmpName** [comment]
Bon c'est ca, tu as raison, j'ai trouve 2 trucs.
1 - possibilites de chnager le choix de classement addSortMethod(), mais dans ce cas, c'est pas ca le prb.
2 - mixage de methode.

Addtext utilise la nouvelle methode, la rapide mais pas cHosterGui().showHoster(), ce qui fait que Vstream affiche d'abors les hosters, et apres ceux qui est dans listing[].

Donc pour corriger ce bug, faut que les hosters utilisent aussi la nouvelle methode.
```
        #bug
        oGui.addHost(oGuiElement, oOutputParameterHandler)

        #oGui.addFolder(oGuiElement, oOutputParameterHandler)
```

C'etait quoi le bug ? Faudrait vraiement utiliser addFolder et non pas addHost

**Comment by johngf** [comment]
ce n'est pas que niveau hoster ça le fait aussi niveau serie >> saison 1 saison 2 exemple sur stre amay

**Comment by TmpName** [comment]
J'ai mis une nouvelle version en ligne, si tu peux la tester et faire un rollback si trop de problemes.
La suis un peu en speed, on part dans 2 jours pour 1 semaine.

**Comment by johngf** [comment]
chez moi ça a l'air ok teste sur 3 site

**Comment by pjil62** [comment]
Bonjour a tous, le problème viens de revenir après une maj dispo, j'ai pris le fichier full stream modifier il y a 4 jour en l incluant dans le zip du plugin vidéo. rien ne ceux passe.

peut être que je montre de manip ?

**Comment by TmpName** [comment]
La derniere modif est dans le coeur, donc pas possible de tester sans passer par la version beta.
