### ISSUE TITLE
Problème Kaydo

### ISSUE THREAD

**Issue by Mystikal57** [Kodi-vStream/venom-xbmc-addons#1521]
Bonjour,

Aucun lien ne se lance sur kaydo.
Voilà les logs lors de la tentative:
12:28:06.558 T:1123820464  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
12:28:06.593 T:1123820464  NOTICE: 	[PLUGIN] Vstream: load site kaydo_ws and call function seriesHosters
12:28:13.166 T:1123820464  NOTICE: 	[PLUGIN] Vstream: Table initialized
12:28:28.095 T:1123820464  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
12:28:28.125 T:1123820464  NOTICE: 	[PLUGIN] Vstream: load site kaydo_ws and call function showHosters
12:28:30.216 T:1123820464  NOTICE: 	[PLUGIN] Vstream: could not load site: kaydo_ws error: 'NoneType' object has no attribute 'group'
12:28:30.227 T:1123820464  NOTICE: 	[PLUGIN] Vstream: Table initialized
12:28:30.267 T:1946210976   ERROR: GetDirectory - Error getting plugin://plugin

Merci

**Comment by funilrys** [comment]
Same here impossible to read series ... @TmpName @mino60 @razorex

**Comment by Arias800** [comment]
J'ai essayer avec Game of Throne et ça fonctionne chez moi verfifier la version de votre fichier (I have try with Game of Throne and he work for me check if you have the lastest version of kaydo's file

**Comment by Mystikal57** [comment]
j'ai tenté de réinstaller l'addon mais sans effets depuis des jours/semaines.
Les liens se lancent très bien via un navigateur

**Comment by razorex** [comment]
il faut un accès maintenant pour Kaydo (HD-Stream)........

**Comment by Arias800** [comment]
Ah je savais pas ^^

**Comment by TmpName** [comment]
Tu as un exemple de lien avec acces ? Je viens de tester pas vu de probleme non plus.

**Comment by razorex** [comment]
quand je vais sur le site, depuis un navigateur, je suis redirigé sur HD-stream et il me demande un user.

**Comment by Arias800** [comment]
Moi je suis rediriger vers HD-stream mais tout fonctionne bien le problème doit venir d'ailleur

**Comment by razorex** [comment]
??????????? tu a acces au site @Arias800 ???? parce que pas moi..

**Comment by TmpName** [comment]
Ben j'ai teste ce matin aussi, aucun probleme non plus.

**Comment by Arias800** [comment]
Chez moi ça marche aussi

**Comment by razorex** [comment]
je dois avoir un pb parce sur mon pc, ma TV Box et mon smartphone je n'ai rien tout est vide!!!!!!!!

**Comment by Arias800** [comment]
Je sais pas

**Comment by Kodigoal** [comment]
Histoire d'ip , proxy , vpn , la redirection vers hd-stream et login.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/784
Mais le soucis de l'issue faut chercher ailleurs vu le log.
