### ISSUE TITLE
update vkstreamingfilm

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1522]
Comme plusieurs chose ne fonctionnais plus (les genres et la recherche) j'ai repris le code, j'en ai profité pour rajouter les synopsis. La recherche ne fonctionne toujours pas. Si qq veux y jeté un œil ou je la désactive tout simplement??
le code [ici](https://gist.github.com/razorex/779d3520ccf9eb8bf7203b7dfde58f78)

**Comment by Arias800** [comment]
L'url de recherche c'est ça : www.vkstreamingfilm.co/index.php?story="FILM RECHERCHER A METTRE LA" &do=search&subaction=search

**Comment by razorex** [comment]
sa donne çà????? mais sa fonctionne pas
`URL_SEARCH = (URL_MAIN + 'index.php?story=', 'showMovies')`
`sUrl = URL_SEARCH[0] + sSearchText + '&do=search&subaction=search'`

**Comment by Arias800** [comment]
Normalement ça devrai marcher  j'ai essayer sur le site et ça fonctionne donc je sais pas faut attendre @TpmName

**Comment by razorex** [comment]
Ok merci. A mon avis c'est plus compliqué qu'une simple url

**Comment by TmpName** [comment]
La methode GET marche mal, il faut passer avec la methode POST, cf l'ancienne source qui marche tres bien pour la recherche, je viens de la tester y a 2 mn.

**Comment by razorex** [comment]
j'ai testé avec l'ancien fichier et ça marche pas. teste une recherche exemple 'Amar' et qui ce trouve en page 2 tu a 0 résultat, il y a un résultat que si il ce trouve en page 1.

**Comment by TmpName** [comment]
Ha yep ^^ C'est parce que j'ai teste "alien" et justement il est present sur la premiere page.
Effectivement ca deconne.

Nope ca tourne en boucle a cause d'un regex trop large. Si c'etait un prb de lib y aurait un arret direct.

**Comment by razorex** [comment]
j'ai intégrer mon regex sans pb dans le fichier.
Question qu'est-ce qui est le mieux intégrer la récupération du syn au regex ou le mettre à part??

**Comment by TmpName** [comment]
C'est bon la recherche marche sur la ville source si on change URL_MAIN.

J'ai pas compris ta question ?

**Comment by TmpName** [comment]
Ha si j'ai compris ^^.

Testes les deux, tu verras si y'en a un qui ralenti plus le programme. Ca depend des regex, si tu peux tout prendre d'un coup c'est mieux car plus rapide, sauf que selon le regex ca le complique tellement que ca ralentit l'execution du prog.

**Comment by razorex** [comment]
La recherche marche sur la ville source???????????

**Comment by TmpName** [comment]
Yep, teste avec Amar, donne amar et tamarra.
https://pastebin.com/R3SbLQQZ

**Comment by razorex** [comment]
Test avec la momie tu aura 0 résultat sur vStream et 8 sur le site. J'ai remis la recherche comme avant mais sa m'a obligé à revenir en arrière sur les regex et supprimer la récupération du synopsis,, sa récupération bug la recherche  .

**Comment by TmpName** [comment]
Je viens de tester momie avec la source que je t'ai passe via pastebin, j'ai 5 resultats.
![tmp](https://user-images.githubusercontent.com/8311559/28579759-d59350f2-715d-11e7-895c-46f949f24a8b.png)

**Comment by razorex** [comment]
ok. je viens de retester avec "momie" et j'ai bien des résultats (pas avec "la momie").
donc tout est ok. merci @TmpName .

**Comment by TmpName** [comment]
Ben pour moi c'est bien un bug. J'avais pas pense a l'article. Pour que ca marche avec "la momie"
```

        #on redecode la recherche codé il y a meme pas une seconde par l'addon
        sSearch = urllib2.unquote(sSearch)

        sSearch = sSearch.replace(' ','%20')
       
        query_args = { 'do' : 'search' , 'subaction' : 'search' , 'story' : str(sSearch) , 'x' : '0', 'y' : '0'}
```

**Comment by razorex** [comment]
c'est çà ou tu t'en souvient plus @TmpName 
`sSearch = sSearch.replace(' ','%20')`

**Comment by TmpName** [comment]
Nope une fonction avec urllib, qui corrige toute la chaine pas juste les %20

**Comment by razorex** [comment]
ah ok. en tout cas rien que çà sa apporte un mieux, je l'ai tester

**Comment by TmpName** [comment]
C'est un truc du genre unquote(), je m'en sert souvent mais je les confond tjours.

**Comment by razorex** [comment]
Ok j'ai tout de même intégrer la ligne`sSearch = sSearch.replace(' ','%20')` en attendant que tu retrouve (ou moi si je tombe dessus par hasard). En attendant je laisse l'issue ouverte??????

**Comment by TmpName** [comment]
La source remarche a fond, non ? tu peux cloturer pr moi.

**Comment by razorex** [comment]
ok
