### ISSUE TITLE
Prblème de lecture des vidéo sur kodi

### ISSUE THREAD

**Issue by rbcraouf** [Kodi-vStream/venom-xbmc-addons#1523]
Bonjour, je n'arrive plus a regarder les vidéos sur vstream v0.5.2 à partir de kodi v17.3, 
La liste ne s'affiche pas pour film illimité et pour tous les autres sites aucunes vidéos ne peut être vues

**Comment by razorex** [comment]
film illimité çà viens de chez eux (inaccessible) les autres ?????? est tu à jour??????

**Comment by rbcraouf** [comment]
Oui je suis à jours,  les autres à part les bandes annonces sur youtube rien ne marche

**Comment by rbcraouf** [comment]
Bon tout est OK maintenant, c revenu tout seul
