### ISSUE TITLE
FANART sur topimdb

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#1524]
salut...
je vouler ajouter FANART sur la source topimdb mais son succès  j'ai ajouter un fichier nommer  imdb dans recouces/lib le meme que tmdb seulement j'ai chanjer l'adressse ou ce trouve les images ( imdb.com/title/%s /mediaviewer/%s  ).
comme par un exemple les sept samouraïs (1954)
il ya 36 images fanart jai utiliser le code de tmdb mais il ya des erreurs au niveau str dans showmovie je les ai enlevés je trouve une autre erreur n° 11004 
si quelqu'un peut m'aider je le serai reconnaissant .

**Comment by TmpName** [comment]
Tu veux que Vstream cherche les fan art tout seul avec son moteur (metahandler active) ou les scrapper toi meme sur le site ?

**Comment by mino60** [comment]
Je veux le deusiéme chois les fanart aficher comme sur la source tmdb son activer les metahandler .

**Comment by TmpName** [comment]
Pas possible, tmbd marche a partir d'une base de donnée complete, topimdb a partir d'un site scrappe.
Si pas present sur le site a la bonne page, pas possible
