### ISSUE TITLE
Version 0.5.3

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1526]
## Version bêta non officiel. (Pas de date de sortis pour le moment) ##

**Note : Ceci est un post pense-bête pour les programmeurs, ce sont uniquement les modifications récentes du cœur de vstream beaucoup d'autre ont déjà êtes faite par l'équipe.**

Correction bug sql historique
Correction bug refresh recherche global
modification de la recherche sur tmdb
modification du context (del voir marque-page-bande annonce)
modification popup info bande annonce gerer par vstream.
del tris de la recherche global
del posibiliter de masquer une catégorie
remplacement de cconfig() par oconfig
test de rapidité pas vue de grand changement entre cConfig() , oConfig, vLang
exécution page home environ 0.78
del Tv du web
ajout en dependance du repo de vstream pas de repo pas d'installe de vstream.
del info marque-page (vous avez x )

**Comment by laquarico** [comment]
Comment j update vstream 0.5.3? Je ne trouve pas l url pour le mettre sur mon fire stick j ai que le repo 5.2

**Comment by TmpName** [comment]
Lol, c'est normal, pas encore diffusé.

**Comment by laquarico** [comment]
Lol ok merci bien

**Comment by LordVenom** [comment]
c'est écrit en gros et en Gras sur le premier post "Version bêta non officiel" :1st_place_medal:

**Comment by Turk182es** [comment]
Salut,

Est ce que cette nouvelle version va réparer tout les serveur mort comme FlashX, Youwatch etc ?

**Comment by Arias800** [comment]
Tout ce qui est youwatch exashere stream,io et allvid ne sont pas prés de revenir et nous n’avons aucun contrôle dessus car ce ne sont pas nous qui geront les serveur

**Comment by TmpName** [comment]
FlashX fonctionne ?

**Comment by Turk182es** [comment]
Non, ok il ne  fonctionne pas.

Enviado desde mi iPhone

**Comment by TmpName** [comment]
Exact, j y jette un oeuil dessus ce WE.

**Comment by TmpName** [comment]
FlasX Remit a jour.

**Comment by Turk182es** [comment]
FlashX donne toujours "Fichier introuvable" chez moi :-/

**Comment by TmpName** [comment]
Teste sur Voirflm / nouveaute / incredible jessica james, fct ok pr moi.

**Comment by laquarico** [comment]
Aucun lien flashx marche pour les serie animes et films

**Comment by TmpName** [comment]
Reteste a l'instant sur sokrostrm , the most beautifull day, fct ok.
Merci de donner l'emplacement precis des liens ne fctnant pas.

**Comment by laquarico** [comment]
Section animes aucun lien flashX ne marche, tv show la meme (par exemple un
gars une fille)

**Comment by TmpName** [comment]
Tu as compte combien il y a de lien dans animes ?
TVshow pas trouve.
J'ai fais un test sur tv-strmg qui n'a pas marche, mais le lien est out sur le site aussi.

**Comment by Turk182es** [comment]
Il suffit de chercher n'importe quelle série un peu ancienne et de chercher les liens FlashX ... tous donneront Fichier introuvable.

**Comment by laquarico** [comment]
La meme pour les animes les man has des series 80 cherche lien FlashX et au
in ne marche fichiers introuvables

**Comment by TmpName** [comment]
Yep, mais dans ce cas faut aller voir sur le site en question si le prb ne vient pas de la.
C'est pour ca que je teste des trucs recent, j'ai plus de chance que le fichier soit encore la, si le lien est mort, on peut plus faire grand chose.

**Comment by laquarico** [comment]
Ok je vois donc je pense que c est sur le site...
