### ISSUE TITLE
Problème avec raspberry pi sous osmc et vstream

### ISSUE THREAD

**Issue by Aliasexterne** [Kodi-vStream/venom-xbmc-addons#1528]
Bonjour, 
Déjà merci beaucoup pour le super travail que vous faites ! J'utilise votre application depuis maintenant quelques mois avec plaisir. 
Je l'ai installée sur un raspberry pi 1 deuxième génération qui traînait chez moi sur lequel je fais tourner une distribution osmc. J'ai la version 0.5.2 de votre application et jusqu'à il y a 2 jours tout fonctionnait sans aucun soucis, mais là il se trouve qu'il y a des soucis au niveau de la recherche et de la lecture des fichiers. Quasiment plus aucun lecteur ne fonctionne, que ce soit youwatch, flashx, netu, etc.. Même uptobox que j'utilisais quasiment tous les jours pour lire de gros fichiers ne veut plus rien savoir. Uptostream ne lance plus les sources et lorsque je Je fais lire directement cela m'indique que le fichier est introuvable alors qu'en parallèle je le vois bien sur un ordi. J'ai réinstaller tout mon système ainsi que l'application mais le problème reste là. Si vous avez des solutions je suis preneur ! Merci

**Comment by Arias800** [comment]
Pourrais tu mettre les log ?

**Comment by Aliasexterne** [comment]
Est-ce qu'il s'agit du fichier que l'on peut voir dans l'onglet "outils/A propos"? Je n'arrive pas à l'extraire...

**Comment by Arias800** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils dans la catégories Upload Log

**Comment by mino60** [comment]
tu peux essayer de vider le cache vstream si non telecharge et installe la derniere version kodi 17.3  et metre la vertion beta vstream le lien ce trouve dans la premiere page github.

**Comment by Aliasexterne** [comment]
Avec un peu de retard : 
21:12:14.086 T:3026092032  NOTICE: special://profile/ is mapped to: special://masterprofile/
21:12:14.086 T:3026092032  NOTICE: -----------------------------------------------------------------------
21:12:14.086 T:3026092032  NOTICE: Starting Kodi (17.3). Platform: Linux ARM 32-bit
21:12:14.086 T:3026092032  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
21:12:14.087 T:3026092032  NOTICE: Kodi compiled Jun  7 2017 by GCC 4.9.2 for Linux ARM 32-bit version 3.16.7 (200711)
21:12:14.088 T:3026092032  NOTICE: Running on Open Source Media Center 2017.06-1, kernel: Linux ARM 32-bit version 4.9.29-10-osmc
21:12:14.098 T:3026092032  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
21:12:14.098 T:3026092032  NOTICE: Host CPU: ARMv6-compatible processor rev 7 (v6l), 1 core available
21:12:14.098 T:3026092032  NOTICE: ARM Features: Neon disabled
21:12:14.098 T:3026092032  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
21:12:14.098 T:3026092032  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
21:12:14.099 T:3026092032  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
21:12:14.099 T:3026092032  NOTICE: special://masterprofile/ is mapped to: /home/osmc/.kodi/userdata
21:12:14.099 T:3026092032  NOTICE: special://envhome/ is mapped to: /home/osmc
21:12:14.099 T:3026092032  NOTICE: special://home/ is mapped to: /home/osmc/.kodi
21:12:14.099 T:3026092032  NOTICE: special://temp/ is mapped to: /home/osmc/.kodi/temp
21:12:14.099 T:3026092032  NOTICE: special://logpath/ is mapped to: /home/osmc/.kodi/temp
21:12:14.100 T:3026092032  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
21:12:14.100 T:3026092032  NOTICE: Local hostname: osmc
21:12:14.100 T:3026092032  NOTICE: Log File is located: /home/osmc/.kodi/temp//kodi.log
21:12:14.101 T:3026092032  NOTICE: -----------------------------------------------------------------------
21:12:14.224 T:3026092032   ERROR: DBus: Error org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
21:12:14.307 T:3026092032  NOTICE: load settings...
21:12:14.892 T:3026092032  NOTICE: Found 2 Lists of Devices
21:12:14.892 T:3026092032  NOTICE: Enumerated PI devices:
21:12:14.892 T:3026092032  NOTICE:     Device 1
21:12:14.893 T:3026092032  NOTICE:         m_deviceName      : HDMI
21:12:14.893 T:3026092032  NOTICE:         m_displayName     : HDMI
21:12:14.894 T:3026092032  NOTICE:         m_displayNameExtra:
21:12:14.894 T:3026092032  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
21:12:14.894 T:3026092032  NOTICE:         m_channels        : FL,FR
21:12:14.894 T:3026092032  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
21:12:14.895 T:3026092032  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_RAW
21:12:14.895 T:3026092032  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_EAC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512
21:12:14.895 T:3026092032  NOTICE:     Device 2
21:12:14.895 T:3026092032  NOTICE:         m_deviceName      : Analogue
21:12:14.896 T:3026092032  NOTICE:         m_displayName     : Analogue
21:12:14.896 T:3026092032  NOTICE:         m_displayNameExtra:
21:12:14.896 T:3026092032  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
21:12:14.896 T:3026092032  NOTICE:         m_channels        : FL,FR
21:12:14.896 T:3026092032  NOTICE:         m_sampleRates     : 48000
21:12:14.896 T:3026092032  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
21:12:14.896 T:3026092032  NOTICE:         m_streamTypes     : No passthrough capabilities
21:12:14.897 T:3026092032  NOTICE:     Device 3
21:12:14.897 T:3026092032  NOTICE:         m_deviceName      : Both
21:12:14.897 T:3026092032  NOTICE:         m_displayName     : HDMI and Analogue
21:12:14.897 T:3026092032  NOTICE:         m_displayNameExtra:
21:12:14.897 T:3026092032  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
21:12:14.898 T:3026092032  NOTICE:         m_channels        : FL,FR
21:12:14.898 T:3026092032  NOTICE:         m_sampleRates     : 48000
21:12:14.898 T:3026092032  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
21:12:14.898 T:3026092032  NOTICE:         m_streamTypes     : No passthrough capabilities
21:12:14.898 T:3026092032  NOTICE: Enumerated ALSA devices:
21:12:14.898 T:3026092032  NOTICE:     Device 1
21:12:14.899 T:3026092032  NOTICE:         m_deviceName      : @
21:12:14.899 T:3026092032  NOTICE:         m_displayName     : Default (bcm2835 ALSA bcm2835 ALSA)
21:12:14.899 T:3026092032  NOTICE:         m_displayNameExtra:
21:12:14.899 T:3026092032  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
21:12:14.899 T:3026092032  NOTICE:         m_channels        : FL,FR
21:12:14.900 T:3026092032  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,32000,44100,48000
21:12:14.900 T:3026092032  NOTICE:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_U8
21:12:14.900 T:3026092032  NOTICE:         m_streamTypes     : No passthrough capabilities
21:12:14.987 T:3026092032  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
21:12:14.988 T:3026092032  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            
                                            
                                            
                                            <advancedsettings>
                                              <imageres>540</imageres>
                                              <fanartres>720</fanartres>
                                              <splash>false</splash>
                                              <handlemounting>0</handlemounting>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                            </advancedsettings>
21:12:14.995 T:3026092032  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
21:12:14.995 T:3026092032  NOTICE: Default Video Player: VideoPlayer
21:12:14.995 T:3026092032  NOTICE: Default Audio Player: paplayer
21:12:14.996 T:3026092032  NOTICE: Disabled debug logging due to GUI setting. Level 0.
21:12:14.996 T:3026092032  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
21:12:14.997 T:3026092032  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
21:12:15.002 T:3026092032  NOTICE: Loaded playercorefactory configuration
21:12:15.003 T:3026092032  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
21:12:15.004 T:3026092032  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
21:12:16.479 T:3026092032  NOTICE: Running database version Addons27
21:12:19.101 T:3026092032  NOTICE: ADDONS: Using repository repository.xbmc.org
21:12:19.101 T:3026092032  NOTICE: ADDONS: Using repository repository.vstream
21:12:28.740 T:3026092032  NOTICE: Raspberry PI firmware version: May 30 2017 15:27:20 
                                            Copyright (c) 2012 Broadcom
                                            version b8cdd5ae76f39d9f353dfa8fb48bf7e33b74903c (clean) (release)
21:12:28.740 T:3026092032  NOTICE: ARM mem: 368MB GPU mem: 144MB MPG2:0 WVC1:0
21:12:28.741 T:3026092032  NOTICE: cache.memorysize: 20MB libass.cache: 0MB
21:12:28.741 T:3026092032  NOTICE: Config:
                                            arm_freq=850
                                            audio_pwm_mode=1
                                            config_hdmi_boost=2
                                            core_freq=375
                                            disable_auto_turbo=1
                                            disable_commandline_tags=2
                                            disable_splash=1
                                            enable_uart=1
                                            force_pwm_open=1
                                            framebuffer_ignore_alpha=1
                                            framebuffer_swap=1
                                            hdmi_channel_map=8
                                            hdmi_force_cec_address=65535
                                            hdmi_ignore_cec_init=1
                                            ignore_lcd=1
                                            init_uart_baud=19200
                                            init_uart_clock=0x2dc6c00
                                            pause_burst_frames=1
                                            program_serial_random=1
                                            temp_limit=85
21:12:28.742 T:3026092032  NOTICE: Config:
                                            device_tree=-
21:12:28.777 T:3026092032  NOTICE: InitWindowSystem: Using EGL Implementation: raspberrypi
21:12:28.785 T:3026092032  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 60.000000 Hz
21:12:28.786 T:3026092032  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 59.940063 Hz
21:12:28.786 T:3026092032  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 72.000000 Hz
21:12:28.786 T:3026092032  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 71.928070 Hz
21:12:28.786 T:3026092032  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 75.000000 Hz
21:12:28.786 T:3026092032  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 60.000000 Hz
21:12:28.786 T:3026092032  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 59.940063 Hz
21:12:28.787 T:3026092032  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 72.000000 Hz
21:12:28.787 T:3026092032  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 71.928070 Hz
21:12:28.787 T:3026092032  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 75.000000 Hz
21:12:28.787 T:3026092032  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 60.000000 Hz
21:12:28.787 T:3026092032  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 59.940063 Hz
21:12:28.788 T:3026092032  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 70.000000 Hz
21:12:28.788 T:3026092032  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 75.000000 Hz
21:12:28.788 T:3026092032  NOTICE: Found resolution 1152 x 864 for display 0 with 1152 x 864 @ 75.000000 Hz
21:12:28.788 T:3026092032  NOTICE: Found resolution 1280 x 800 for display 0 with 1280 x 800 @ 60.000000 Hz
21:12:28.788 T:3026092032  NOTICE: Found resolution 1280 x 800 for display 0 with 1280 x 800 @ 59.940063 Hz
21:12:28.788 T:3026092032  NOTICE: Found resolution 1280 x 1024 for display 0 with 1280 x 1024 @ 60.000000 Hz
21:12:28.789 T:3026092032  NOTICE: Found resolution 1280 x 1024 for display 0 with 1280 x 1024 @ 59.940063 Hz
21:12:28.789 T:3026092032  NOTICE: Found resolution 1280 x 1024 for display 0 with 1280 x 1024 @ 75.000000 Hz
21:12:28.789 T:3026092032  NOTICE: Found resolution 1440 x 900 for display 0 with 1440 x 900 @ 60.000000 Hz
21:12:28.789 T:3026092032  NOTICE: Found resolution 1440 x 900 for display 0 with 1440 x 900 @ 59.940063 Hz
21:12:28.789 T:3026092032  NOTICE: Found resolution 1680 x 1050 for display 0 with 1680 x 1050 @ 60.000000 Hz
21:12:28.790 T:3026092032  NOTICE: Found resolution 1680 x 1050 for display 0 with 1680 x 1050 @ 59.940063 Hz
21:12:28.790 T:3026092032  NOTICE: Found resolution 1366 x 768 for display 0 with 1366 x 768 @ 60.000000 Hz
21:12:28.790 T:3026092032  NOTICE: Found resolution 1366 x 768 for display 0 with 1366 x 768 @ 59.940063 Hz
21:12:28.790 T:3026092032  NOTICE: Found resolution 1600 x 900 for display 0 with 1600 x 900 @ 60.000000 Hz
21:12:28.790 T:3026092032  NOTICE: Found resolution 1600 x 900 for display 0 with 1600 x 900 @ 59.940063 Hz
21:12:28.790 T:3026092032  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
21:12:28.791 T:3026092032  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 59.940063 Hz
21:12:28.791 T:3026092032  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 60.000000 Hz
21:12:28.791 T:3026092032  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 59.940063 Hz
21:12:28.791 T:3026092032  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
21:12:28.791 T:3026092032  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.940063 Hz
21:12:28.791 T:3026092032  NOTICE: Found resolution 720 x 576 for display 0 with 720 x 576 @ 50.000000 Hz
21:12:28.792 T:3026092032  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 50.000000 Hz
21:12:28.792 T:3026092032  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
21:12:28.792 T:3026092032  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
21:12:28.793 T:3026092032  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 23.976025 Hz
21:12:28.793 T:3026092032  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 25.000000 Hz
21:12:28.793 T:3026092032  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 30.000000 Hz
21:12:28.793 T:3026092032  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 29.970032 Hz
21:12:28.793 T:3026092032  NOTICE: Found (1920x1080@60.000000) at 48, setting to RES_DESKTOP at 16
21:12:28.794 T:3026092032  NOTICE: Checking resolution 16
21:12:29.118 T:3026092032  NOTICE: GL_VENDOR = Broadcom
21:12:29.118 T:3026092032  NOTICE: GL_RENDERER = VideoCore IV HW
21:12:29.122 T:3026092032  NOTICE: GL_VERSION = OpenGL ES 2.0
21:12:29.122 T:3026092032  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
21:12:29.122 T:3026092032  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker
21:12:33.969 T:3005215728  NOTICE: Running database version Addons27
21:12:34.002 T:3005215728  NOTICE: Running database version ViewModes6
21:12:34.019 T:3005215728  NOTICE: Running database version Textures13
21:12:34.023 T:2904007664  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
21:12:34.061 T:3005215728  NOTICE: Running database version MyMusic60
21:12:34.115 T:3005215728  NOTICE: Running database version MyVideos107
21:12:34.132 T:3005215728  NOTICE: Running database version TV29
21:12:34.148 T:3005215728  NOTICE: Running database version Epg11
21:12:34.156 T:3026092032  NOTICE: start dvd mediatype detection
21:12:37.082 T:3026092032 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
21:12:41.044 T:3026092032  NOTICE: initialize done
21:12:41.045 T:3026092032  NOTICE: Running the application...
21:12:42.843 T:3026092032  NOTICE: starting zeroconf publishing
21:12:42.857 T:3026092032  NOTICE: CWebServer[8080]: Started
21:12:42.868 T:3026092032  NOTICE: starting upnp client
21:12:43.002 T:2709517296  NOTICE: ES: Starting UDP Event server on port 9777
21:12:43.014 T:2709517296  NOTICE: UDP: Listening on port 9777 (ipv6 : true)
21:13:28.859 T:2788742128  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.3), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
21:13:36.512 T:2814956528 WARNING: CSkinInfo: failed to load skin settings
21:23:05.976 T:2788742128   ERROR: GetDirectory - Error getting
21:23:45.726 T:2625631216   ERROR: Previous line repeats 2 times.
21:23:45.733 T:2625631216 WARNING: CPythonInvoker(4): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.

**Comment by TmpName** [comment]
Tu as fait bugguer Vstream avant de faire le log ? CAr je ne vois rien sur Vstream.
Essayes plutot de faire passer les logs via Pastebin ou l'outil integre a vstream, pour alleger l'issue stp.

**Comment by Aliasexterne** [comment]
Bonjour, 
après quelques jours d'absence et appliqué la nouvelle mise à jour je n'ai plus rencontré le problème depuis 2 jours. Mystère mystère... En tout cas merci beaucoup pour votre réactivité!!

**Comment by Aliasexterne** [comment]
Bonsoir, 
Le soucis a refait surface ! Voici le log https://pastebin.com/qmTZWazA
Merci !

**Comment by TmpName** [comment]
Pour ce que j'en vois ce ne sont pas des erreurs de Vstream mais des erreur de connexion venant de ton systeme.
Apres pour configurer un systeme Unix ...
