### ISSUE TITLE
Aide pour cinemaVF

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1532]
Besoin d'aide pour terminer ce plugin en "levideo" le fichier [ici](https://gist.github.com/razorex/bc4b19e9afc264ef4149f7408b06c04b). j'affiche bien les titres les thumbs je coince au links des hotes. Merci d'avance. pour la partie showLinks je me suis inspiré de sokrostream.

**Comment by TmpName** [comment]
if '/serie' in sUrl or '/mangas' in sUrl:

**Comment by TmpName** [comment]
https://pastebin.com/L5LzQ06b

Certaines sources ne marchent pas a cause du dernier regex.

**Comment by razorex** [comment]
Cette écriture fonctionne pourtant `if '/serie' or '/mangas' in sUrl:`
pour le regex ce n'étais qu'une ébauche puisque je n'arrivais pas à afficher les liens.

**Comment by TmpName** [comment]
Teste dans"film" "dernier ajout" tu te retrouve avec showsaisons() (alors que c'est un film)

**Comment by razorex** [comment]
oui je viens de voir dans le log de kodi. Quand tu met c'est code ou "atterisse" c'est info?
`    cConfig().log(str(sUrl))`
    `cConfig().log(str(aResult))`

**Comment by razorex** [comment]
Comment puis jumeler c'est 2 pattern en un :
`sPattern = '<iframe.+?src="(.+?)"'`
`sPattern = '<iframe.+?src='(.+?)''`

**Comment by TmpName** [comment]
Nope, pas de vshare, je vais essayer dans la semaine si je trouve du temps.
Sinon pr le regex, ca ca suffit
`sPattern = '<iframe.+?src=["\']([^"\']+)["\']'`

Tu peux meme supprimer le dernier groupe entre crochet.

**Comment by TmpName** [comment]
Nope, te prend pas la tete a changer le regex, les deux marche c'est juste que le tien prend en compte le caractere | , mais ca change rien car il n ' y en a pas dans l'url.
Pour les hosters, je nai pas trop de temps en ce moment, mais je vais voir ca dans la semaine.

**Comment by TmpName** [comment]
Vitdo.me j'ai pu le refaire fonctionner en rajoutant dans le code de ton fichier
```

            if not 'http' in sHosterUrl:
                sHosterUrl = 'http:' + sHosterUrl
```

**Comment by razorex** [comment]
j'avais bien vu que le lien ne commencais pas par 'http' mais pas pensé à le rajouter.
