### ISSUE TITLE
Hosters (pense bête)

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1536]
Manque vshare.eu et cloudvid.co si qq ce sent pour les faires.

**Comment by LordVenom** [comment]
vshare fait

**Comment by razorex** [comment]
French-stream. la source sur vStream est hs de mon côté je viens de réparer la partie film et les séries (jusqu'au hosters) il n'y a plus que cloudvid.co qui fonctionne les autres hosters sont vides. soit je met maintenant ma correction ou j’attends que tu fasse le hoster et je terminerais la correction....

**Comment by TmpName** [comment]
Normalement l'un n'influe pas sur l'autre.
Corrige le fichier site que ce soit plus facile pour tester. Il vaut mieux que tout soit en place pour la MAJ, quitte a faire les dernieres modis en MAJ auto.

**Comment by LordVenom** [comment]
French-stream réparer cloudvid fait mais ne fonctionne pas même sur navigateur donc après l'avoir fait je l'ai désactiver dans hoster.py.

**Comment by razorex** [comment]
j'ai vu que j'avais oublié de remettre le bon site_identifier dans french-stream.  il y a d'autres sites qui utilise cloudvid mais aucun ne me revient en tête

**Comment by razorex** [comment]
Deux nouveaux Hosters, Streamax et Vidmoly. sur film illimité le film Taking Earth.

**Comment by TmpName** [comment]
Lol, mwé je ne les trouve nulle part ailleurs, ya beacoup de film dessus, car si c'est pour que le site ferme dans 1 mois ...

**Comment by razorex** [comment]
streamax oui parce que les sources fonctionnent Vidmoly moins. j'ai vu que film illimité réduisait la "voilure" série HS. après je laisse décider la team.

**Comment by TmpName** [comment]
C'est pas l'inverse ?
J'ai voulu m y coller et je ne trouve que vidmoly en hoster ?

**Comment by TmpName** [comment]
@razorex tu as un nom de film stp ?

**Comment by razorex** [comment]
@TmpName j'avais Taking earth sur la page d'accueil mais plus de source streamax fonctionnelle.

**Comment by TmpName** [comment]
clickopen.win ?? Lol, ca ca sent le hoster qui va durer longtemps ^^

**Comment by razorex** [comment]
lol... on laisse en standby alors

**Comment by Arias800** [comment]
clickopen est deja mort je croit x) sur film illimite the defenders video introuvable alors que ca vient d'etre ajoute ^^
