### ISSUE TITLE
Utile ou pas

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1538]
cet élément dans addMovies, addTV et addMisc. c'est dans la plupart des cas vides ou alors on utilise cette 'function' pour affiché le fanart et on ne conserve que addMovies, j’espère être clair.
`oGuiElement.setIcon(sIcon)`

**Comment by LordVenom** [comment]
Un mélange de version rend incompatible le faite de supprimer le code et les images passe par icon ou thumb suivant les versions de Kodi.

**Comment by razorex** [comment]
ok merci
