### ISSUE TITLE
TvAddon de retour ?!

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1540]
Voilà plus d un mois que tvaddon a fermer mais il n a pas fallut longtemps a tvaddon pour revivre meme si la justice na pas décidé de les laisse continuer bon aller voilà le lien (a utiliser avec prudence car il n y a pas de preuve que c'est effectivement le vraie)tvaddons,co bref affaire a suivre

**Comment by TmpName** [comment]
"Revivre", il a juste re ouvert, par contre c'est du foutage de gueule, avec le pognon que brasse le site, il demande une participation aux frais de 25k Dollar. Et le mec apparait en photo sur son bateau.

**Comment by Arias800** [comment]
Oui c'est vraie que c'est un peut bizarre ce paradoxe mais bon si il le fait c'est qu'il est sur que des pigeon payeront x)

**Comment by LordVenom** [comment]
Ha mais bien sure c'est ça que j'aurais du faire une grosse banderole rouge vif "DONATE"

heu rassurer moi c'est 25 dollard pas 25.000 en 6 jours quand même.

**Comment by TmpName** [comment]
Si si, ^^
Et le montant par defaut est de 50 dollars.

Te faut fermer le github pendant 15 avant de mettre la banderole @LordVenom et apres c'est bon a toi le Yatch sur la mer bleu.

**Comment by Arias800** [comment]
Attend le mec demande 250,000 $ au totale x)
