### ISSUE TITLE
Tv

### ISSUE THREAD

**Issue by helpmoi** [Kodi-vStream/venom-xbmc-addons#1541]
Bonsoir, 
Est-ce que la télévision marche chez vous ? Car chez moi ça ne marche pas.

**Comment by LordVenom** [comment]
La version 0.5.3 règle le soucis plus de tv dans vstream.

**Comment by helpmoi** [comment]
Ah d'accord. Par contre serai possible d'ajouter le bouton bande annonce sur les films car on dois tous le temps aller dans information... (pour la version 0.5.3)

**Comment by LordVenom** [comment]
Non pas possible.

**Comment by mmtest1** [comment]
bonjour,
@LordVenom, comme vous l'avez indiqué la fonction tv a été supprimée, certainement pour des raisons de droits de diffusion mais serait-il possible de retablir une partie ?
Je n'ai pas d'accès à la tv à la maison, je tourne avec un rpi b+ osmc et évidemment vstream mais j'avais pris l'habitude d'utiliser la fonction tv de vstream avec les liens france0,2,3,4,5 en regex de tmpname et comme la diffusion des chaines du groupe francetv sont en libre diffusion sur le net serait-il possible de les réintégrer à l'extension ?
Avant la dernière maj je les avais ajouté en marque page et ils sont restés fonctionnels mais ils seront inaccessibles sur de prochaines installations. J'ai également essayé de les faire fonctionner dans une playlist sous livestreampro mais impossible d'ouvrir les liens.
Dans tous les cas je vous remercie ainsi que le reste de la team pour votre excellent travail et votre suivi constant de l'extension qui nous permettent à nous simple utilisateur de ne plus subir la tv et de reprendre un peu de contole  sur le contenu et de s'affranchir de la pub, merci

**Comment by LordVenom** [comment]
Bonjour, 

Merci pour votre message de soutient. Pour votre demande: 

- Si la question est: Je peux remettre la tv, la réponse est oui le code source existe toujours suffis de chercher.

- Si la question est: Si moi je peux le faire, la réponse et non je n'utilise pas cette fonction et de mes souvenirs aucun codeur de vStream non plus.

**Comment by mmtest1** [comment]
merci pour votre reponse et je comprend parfaitement les motivations, je ne connais rien à python mais je n'ai cas m'y plonger...... et prendre le temps de comprendre afin de ne plus être un simple utilisateur.
une dernière question : serait-il possible d'être aiguillé pour rendre les liens francetv en regex compatible avec livestreampro car le fichier .m3u créé contenant les liens n'est pas lu par l'extension certainement un problème de synthaxe, en attendant d'appréhender le python.
merci pour votre temps

**Comment by TmpName** [comment]
Ce n'est pas un probleme de syntaxe, c'est jute que le codage utilise par Vstream lui est propre et ne marchera que sur lui.
Et leur codage n'est pas du python non plus.
Le plus simple est d'utiliser une autre methode pr la TV, cherche sur google racacax par exemple.

**Comment by mmtest1** [comment]
Bonjour,
@TmpName, merci pour ces precisions cela explique pourquoi les liens ne sont pas lus non plus par vlc sur le pc,
j'ai deja regarder un peu sur google : racacax, kodi livetv et autres et je n'ai pas vraiment été convaincu par la stabilité, je ne cherche pas à avoir c+ et autres mais seulement les france tv (principalement pour les informations et france 5) de manière stable, je vais me tourner vers le replay (fReplay et catchuptv & more) en attendant de percer les mystères du codage, et pour l'instant ils sont toujours opérationnels dans les marques-pages
merci

**Comment by TmpName** [comment]
Yep, mais c'est bizarre car racacax utilise les memes methode que nous pour avoir les chaine de france TV, il n'ya pas de raisons pour que les siennes soient moins table que les notres.
Apres il propose plusieurs lien par chaine, et uniquement l'un d'entre eux est le meme que nous.

**Comment by mmtest1** [comment]
merci, je retesterai à l'occasion allfrtv malgré l'inscription et les restrictions (on est pas encore au niveau de l'ancien téléFR)
merci pour les conseils
