### ISSUE TITLE
Raccourci recherche

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1542]
Alors voila je me suis mit en quête de trouve un moyen pour afficher les film sur l’écran d’accueil de kodi et de pourvoir les utilise avec vstream et c'est cette solution que je fait vous présente(ne marche potentiellement pas sur kodi 17 et +).
Tout d’abord il vous faut vstream et un addon nommé MetalliQ (https://howtomediacenter.com/en/metalliq-kodi-addon-library-integration/ regarde uniquement comme l'installer) une fois ces addon installer il faut aller dans le fichier player :

Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data\plugin.video.metalliq\players

iOS | /private/var/mobile/Library/Preferences/Kodi/userdata/addon_data\plugin.video.metalliq\players

Linux | ~/.kodi/userdata/addon_data\plugin.video.metalliq\players

Mac | /Users/<your_user_name>/Library/Application/Support/Kodi/userdata/addon_data\plugin.video.metalliq\players

LibreELEC/OpenELEC | /storage/.kodi/userdata/addon_data/plugin.video.metalliq\players

Windows | Start - type %APPDATA%\kodi\userdata\addon_data\plugin.video.metalliq\players - press <Enter>

Une fois cela fait vous devez créer le fichier "zonal.vstream.o.metalliq.json" (https://github.com/Arias800/zonal.vstream.o.metalliq.json/blob/master/zonal.vstream.o.metalliq.json)
Optionel : Ensuite vous n'avez plus qu'a suivre le reste du tutoriel (https://howtomediacenter.com/en/metalliq-kodi-addon-library-integration/ )et normalement dans la liste des addon de streaming vstream apparaît ^^

**Comment by LordVenom** [comment]
Plus simple utilise Eminence 2.0 sous Kodi 17

![screenshot000](https://user-images.githubusercontent.com/4380112/28993085-73be483e-79ad-11e7-852f-aab73fbe1328.png)

Les posters retourne sur la recherche du films y a plus cas :)

**Comment by Arias800** [comment]
Eminence 2.0 fonctionne aussi pour les séries ?

**Comment by fennec213** [comment]
Bonjour LordVenom,

Pourrais-je te demander quelques minutes pour m'expliquer la marche à suivre pour bien configurer Eminence 2.0 et obtenir du même coup ce que tu as pris comme screen ? En effet moi j'ai bien le même affichage mais pas de V stream directement qui s'affiche. 

Merci d'avance ;)

**Comment by LordVenom** [comment]
Paramètre -  Interface
- Configurer l'habillage

Accueil - Custom home menu

Sélectionne Film ou autre et click sur le + pour crée un nouveau menu

![image](https://user-images.githubusercontent.com/4380112/31388813-86cea620-adcf-11e7-8038-a17d4c5ae9b2.png)

Dans le nouveau menu 
- Action = Extention -> Extention video -> vStream -> Créer l'élément de menu ICI.
- Label = vStream
Widget = Extention -> Extention video -> vStream -> Recherche Visuelle -> Films Populaire -> Utiliser comme Widget.

**Comment by ryan1308** [comment]
Merci l'ami

**Comment by canopre** [comment]
Hello

Moi je faisais la même chose avec Aeon Nox Silvo mais depuis Vstream 5.5 ça ne fonctionne plus avec ce message d'erreur quand je sélectionne un film 

19:25:07.586 T:1958645760   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?site=globalSearch&function=showSearch&title=Deadpool&sMovieTitle=Deadpool&siteUrl=http%3A%2F%2Fvenom&sTmdbId=293660&searchtext=deadpool&type=film&sThumbnail=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Fw396%2FnsHOWVQcinAWRtGeIbfZJCTDoNX.jpg) failed

Une idée du problème que je rencontre ?

Merci d'avance.

**Comment by LordVenom** [comment]
@Arias800 Tu peux faire un tuto au propre dans le wiki que je puisse clore cette conversation ?

**Comment by Arias800** [comment]
Oui je m'en occupe quand internet sera de retour

**Comment by LordVenom** [comment]
Trop tard xD

**Comment by Arias800** [comment]
Ah zut x)
