### ISSUE TITLE
Recherche visuelle ko

### ISSUE THREAD

**Issue by Allonsbon2004** [Kodi-vStream/venom-xbmc-addons#1543]
Salut, 
Visiblement la recherche visuelle ne fonctionne plus

**Comment by Allonsbon2004** [comment]
Recherche par genre non plus

**Comment by TmpName** [comment]
Pas vu de prbs, quelqu'un peut confirmer ?

**Comment by Allonsbon2004** [comment]
Une fois que je selectionne le film via les images  je reviens sur l écran de recherche standard

**Comment by Arias800** [comment]
Pareil chez moi quand je clique sur un site ça ramène sur le menu de recherche ^^

**Comment by TmpName** [comment]
Vous avez essayez avec la version beta ou officielle ?

**Comment by LordVenom** [comment]
La mise a jour 0.5.3 corrige le bug ?

**Comment by Arias800** [comment]
La recherche visuel renvoie bien le nom du film mais la recherche ne se lance pas toute seul normal ?

**Comment by TmpName** [comment]
Moi ca marche mais le mode d'affichage par defaut n'est plus les vignettes.

**Comment by LordVenom** [comment]
Y a une étapes en plus  il faut maintenant valider le nom.
J'ai rien changer dans l'affichage ok ça passeras en maj auto.

**Comment by Allonsbon2004** [comment]
Le pb c est la recherche visuelle dans catégories film populaire par exemple 

Le 5 août 2017 13:15:49 GMT+02:00, Lord Venom <notifications@github.com> a écrit :
>Y a une étapes en plus  il faut maintenant valider le nom.
>J'ai rien changer dans l'affichage ok ça passeras en maj auto.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1543#issuecomment-320438010

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by LordVenom** [comment]
Je comprend pas tu tombe la dessus normalement ?

![screenshot001](https://user-images.githubusercontent.com/4380112/28995373-ef34c51c-79e7-11e7-8df7-b3fc0026fbe1.png)

**Comment by Arias800** [comment]
C'est tout bon pour moi ça fonctionne ^^

**Comment by TmpName** [comment]
Ca remarche apres une petite MAJ des fichiers sites non ?

**Comment by Arias800** [comment]
Perso j'ai pris la version beta qui a regler le probleme

**Comment by Allonsbon2004** [comment]
Effectivement il faut reselectionner film et cela fonctionne. La procédure est un peu différente d avant. 

Le 6 août 2017 13:56:39 GMT+02:00, Arias800 <notifications@github.com> a écrit :
>Perso j'ai pris la version beta qui a regler le probleme
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1543#issuecomment-320502367

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.
