### ISSUE TITLE
Quelques sites ne fonctionnent plus

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#1544]
salut @TmpName ,

Pour streamay, le new pattern de liste de films:
`sPattern = '\"id\":.+?,\"title\":\"([^\"]+)\".+?\"qualite\":\"([^\"]+)\",\"img\":\"([^\"]+)\",.+?\"url\":\"([^\"]+)\"'`

Pour planet-streaming:
l'url de recherche est: `'http://www.2017.planet-streaming.com/'`

Voilà si ça peut te faire gagner du temps !
Bonne continuation à l'équipe

**Comment by TmpName** [comment]
Merci.
Pr PS je le met en place de suite, pour Strmway, il y  a d'autres problemes donc j'ai pas encore tout fini.

**Comment by TmpName** [comment]
C'est bon, en place, merci ^^.

**Comment by soichirou** [comment]
Le site http://www.Ianime.tv ne fonctionne pas non plus. Voici l'erreur que je reçois dans mon log:

`04:41:04 T:21780   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=ShowAlpha2&sFav=ShowAlpha2&site=mangacity_org&siteUrl=http%3a%2f%2fwww.ianime.tv%2flisting_vf.php&title=I%20anime
04:41:04 T:21780   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=ShowAlpha2&sFav=ShowAlpha2&site=mangacity_org&siteUrl=http%3a%2f%2fwww.ianime.tv%2flisting_vf.php&title=I%20anime) failed`

**Comment by Arias800** [comment]
Le probleme vient de la fonction ShowAlpha2 avec en plus un probleme au niveau du changement de page et des hoster

**Comment by TmpName** [comment]
Nouvelle version a tester
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/mangacity_org.py

**Comment by Arias800** [comment]
La nouvelle version fonctionne chez moi ^^

**Comment by soichirou** [comment]
Pareil, merci beaucoup pour le hotfix.
