### ISSUE TITLE
Soucis derniere MAJ.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#1550]
Alors la je ne comprend rien, je me retrouve avec de vieux fichiers, c'est le deuxieme qui ne correspond pas avec les fichiers du github.

**Comment by LordVenom** [comment]
Quoi ! le deuxième ?

**Comment by Konradedz** [comment]
Bonsoir,
depuis hier, vstream ne marche plus sur ma android box, alors que ca fonctionne toujours sur la tablette et le PC. c'est quoi le probleme ?
Merci.

**Comment by LordVenom** [comment]
Bonsoir, je te retourne la question c'est quoi le problème.

**Comment by LordVenom** [comment]
@TmpName  , je pense que tu travail sur un Forks en oubliant de merge c'est pour ça que tu n'a pas les même fichier. exemple 

https://github.com/Kodi-vStream/venom-xbmc-addons/compare/Beta...TmpName:patch-1

**Comment by Konradedz** [comment]
Bonsoir,
sur l'android box tous marchais bien sous 0,5,2, mais depuis hier tout est vide. alors que sur le PC et la tablette ca marche encore. est ce que ca a un lien avec les version 17 de kodi ?
Merci.

**Comment by TmpName** [comment]
Nope ca deconne depuis que j'ai fais la MAJ Complete. Je pensais avoir les dernieres versions du coup, mais c'est loind 'etre le cas.

**Comment by laquarico** [comment]
Bonsoir est ce que la mise a jour de vstream ce fait automatiquement ou je dois retelecharger le fichier zip?

**Comment by TmpName** [comment]
Si tu as installe le repo, la MAJ de Vstream est automatique, et la verification des fichiers sites/hosts se fait tout les 3 jours. Tu as une option qui va apparaitre, pas besoin de retelecharger quoique ce soit.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour

**Comment by laquarico** [comment]
Ok merci je vais voir ca une fois de retour

**Comment by razorex** [comment]
@TmpName j'ai moi aussi vu qu'il y avait des fichiers qui sont revenu avec des versions antérieur avec le passage à la version 0.53............. je pensais être le seul.

**Comment by razorex** [comment]
Je pensais être le seul à avoir cette sensation.

**Comment by LordVenom** [comment]
Alors je sais pas quoi dire, j'ai fait la même manip que d'habitude et je fait ça a des heures creuses pour toujours avoir les derniers fichiers sur le bêta.

**Comment by TmpName** [comment]
Mais c'est bizarre, ca peut venir du github.
Parfois je met a jour un fichier sur le site, je lance la MAJ ponctuelle chez moi, et je me retrouve avec une vielle version, je relance la MAJ en bidouillant la date, et ca remarche.

**Comment by LordVenom** [comment]
Je pense à un temps de chargement entre le pull request et l'api attendre entre les Pulls peux être.

**Comment by razorex** [comment]
j'ai aussi des pb d'affichage sur certaines sources au niveau des hosters la ligne addText pour affiché en générale les langues n'est plus affichées au bonnes endroit ex: films stream v2 / full-stream. il n'y avait pas de soucis sur la0.52

**Comment by TmpName** [comment]
Ha !!!
Ca me rassure ^^, moi j'avais dans le desordre et sur github la personne disait que c'etait bon.
Y a tout les film et apres les titre en rouge, et j'arrive pas a comprendre pkoi, surtout que ca le fait pas sur tout les sites.

**Comment by razorex** [comment]
ben faut que je refasse un test mais si tu fait une modif sans rapport après sa refonctionne correctement......................................... bizarre. j'en profite pour dire que sur cinemavf les jaquettes ne fonctionnent plus et je seche.

**Comment by TmpName** [comment]
Pr cinemaVF, ca vient de la protection Cloudflare.
En general cette protection est temporaire, suffit d'attendre, si elle reste 24/24, il faudra passer le code avec la protection cloudflare et il y a une fonction dans la lib pr rajouter le cookie au image ( sThumb = sThumb + GetHeadercookie() ) , une dizaine de ligne a modifier max.

**Comment by Arias800** [comment]
Problème avec uptostream a chaque maj je doit recopier coller manuellement le code sinon ça ne marche pas

**Comment by TmpName** [comment]
Ha ?
Pourtant je ne vois pas de difference entre celui en beta et celui en master ?
C'est celui de la beta que tu copie ?

**Comment by Arias800** [comment]
Oui après c'est peut être une coïncidence mais bon je teste un lien il marche je copie et colle et il marche ^^

**Comment by TmpName** [comment]
J'ai deja eu ce probleme, c'est pour ca que j'ai cree cette issue justement, c'est passe avec le temps.
Si ca passe pas, copies les 2 version du fichier ici pour les comparer https://www.diffchecker.com/
