### ISSUE TITLE
lien Uptobox 

### ISSUE THREAD

**Issue by itchy13** [Kodi-vStream/venom-xbmc-addons#1554]
bonsoir, depuis avant hier soir je nest plus aucun lien uptobox qui fonctionne sur vstream  jai essayé avec un autre  compte premium mais sa fais la meme chose (erreur fichier introuvable) sauf que quand je me rends sur le site en question les lien son bien fonctionnel  :/

**Comment by TmpName** [comment]
Pas de soucis chez moi, il y a un probleme sur les MAJ, si tu as fais une MAJ complete de la version il te faut attendre quelques jours et refaire la MAJ propose sur la page d'acceuil de Vstream.

**Comment by Arias800** [comment]
Pas de problème n'ont plus chez moi

**Comment by itchy13** [comment]
jai etais jeté un coup d'oeil sur mon  compte upto et j'ai décoché les 2 case téléchargement direct et sa fonctionne maintenant 👍

**Comment by stefane31** [comment]
Bonjour à tous,
J'ai le même cas que Itchy13,en utilisant les liens utptobox en passant par Vstream,ça m'indique 'Fichier introuvable' .
J'ai vérifié et les liens sont bien ok.
Qui peut m'aider...Help!!!!

**Comment by Arias800** [comment]
Essayer cette version du fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/uptobox.py

**Comment by TmpName** [comment]
Il y a 3 options dans ta configuration uptobox qui doivent etre d'un certaine maniere.

**Comment by TmpName** [comment]
Verifie que sur ton compte uptobox (sur navigateur) tu n'ais pas coche "téléchargement direct" et "telechargement SSL".
Et le troisieme option me souviens plus laquelle c'est.
