### ISSUE TITLE
Source Uptobox

### ISSUE THREAD

**Issue by alex83100** [Kodi-vStream/venom-xbmc-addons#1555]
Bonjour, j'ai un problème avec la source uptobox (compte premium). 

Je ne vois pas les fichiers à partir de deux niveaux de dossiers (dossier vide), par contre cela fonctionne très bien à la racine et dans le premier niveau de répertoire. 

A titre d'information j'utilise à défaut un autre plugin qui n'a pas ce problème : Cloudstream pour parcourir mes fichiers uptobox. 

Il est également dommage de ne pas pouvoir ajouter à la bibliothèque  les fichiers de son compte uptobox (création de STRM), j'utilise la aussi un autre plugin Osmosis mais il n'est pas capable de générer des strm dans des sous répertoire. En espérant cette fonctionnalité dans une évolution futur de votre plugin ... En tout cas bravo pour votre travail. 

Alexandre

**Comment by TmpName** [comment]
Alors la, je n'ai jamais touche a ce site, je preferais attendre que l'auteur repasse par la, pour corriger.
Donc pour le moment perso, je laisse en attente de mon cote.

**Comment by sebi0606** [comment]
Next page n'apparaît plus aussi maintenant 
Si tu peux jeter un coup d'oeil merci d'avance
