### ISSUE TITLE
Amélioration vStream - sources HD

### ISSUE THREAD

**Issue by FEARZYAH** [Kodi-vStream/venom-xbmc-addons#1556]
Bonjour,

Utilisant vStream depuis un bon moment chez moi et rien que pour ça je félicite toute votre équipe pour le travail fourni c'est top 👍 

Ma demande est celle-ci : 

Serait-ce possible techniquement parlant de créer un bouton dans le menu principal qui aurait pour but de activer/désactiver les sources SD ? 

Typiquement on peut chercher des films en HD dans les menus mais l'idée serait de juste cacher les sources non-hd lors de l'utilisation de la recherche visuelle? Plutôt qu'avoir une liste de 30 sources en avoir disons 5-6 (les chiffres sont des exmples).

Comme ça on a le choix d'activer ou non les sources SD, et ça faciliterait vraiment lors des recherches de films de taper uniquement sur certaines sources ou non. Si je vois que mon film est disant récent et qu'il n'existe pas en HD et que je désire absolument le voir, j'ai la possibilité par un simple bouton de réactiver toutes mes sources et pouvoir le voir en qualité moyenne.

Est-ce que techniquement ça serait réalisable? :)

Merci d'avance pour votre réponse et de votre avis sur ce post, ça m'intéresse de savoir si je suis le seul dans ce cas.

**Comment by TmpName** [comment]
On ne peut pas savoir si une source est HD ou pas.
Certains sites donnent les deux, d'autres mettent "HD" sur la "SD" d'autres ne donnent aucunes infos, ...
Tu peux par contre te faire une selection de sites proposant generallement du HD, et n'utiliser que cette selection.

**Comment by FEARZYAH** [comment]
Merci pour ta réponse.

Effectivement c'est vrai que c'est difficile à filtrer le tout... Quand tu parles de me faire une selection, c'est passer dans les paramètres de l'extension et décocher les non-HD ?

**Comment by TmpName** [comment]
Recherche
Recherche personalisee 4 (c'est les documentaires, celle qui doit servir le moins)
Tu met le nom " Source HD"
Tu selectionnes les sites que tu juges d assez bne qualitée.

Lors de ta prochaine recherche tu auras "Sources HD" comme choix.

**Comment by FEARZYAH** [comment]
Effectivement j'utilise pas du tout les documentaires. Bonne idée je vais faire ça, merci beaucoup. À lock
