### ISSUE TITLE
Plus de bande annonce

### ISSUE THREAD

**Issue by fredo04** [Kodi-vStream/venom-xbmc-addons#1557]
Bonjours tout le monde.
Depuis la dernière mise à jour le lien pour les bandes annonces du menu contextuel à disparu, c'est dommage car bien pratique. On peut toujours y aller en passant par informations.
http://hpics.li/d851151

**Comment by Arias800** [comment]
Il me semble (a confirme) mais c'est volontaire de la part de LordVenom

**Comment by fredo04** [comment]
Ha mince.
Ho grand lordvenom pourrais tu remettre les bandes annonces stp, car c'était fort pratique.
( Ça fait pas trop fayot ? )

**Comment by TmpName** [comment]
Ha bon ?
Moi aussi ca me servait souvent. Me fous des infos mais la bande annonce c'etait rapide.
Y a une raison pour cette modif ?

**Comment by Arias800** [comment]
Je sais pas du tout peut etre pour regrouper tout ce qui a un rapport avec les information ensemble

**Comment by LordVenom** [comment]
Est notre grand vainqueur et @Arias800  :)

**Comment by fredo04** [comment]
Allé steuplait lordvenom remets comme avant.
C'était bien comme c'était.

**Comment by Arias800** [comment]
Par contre je sais pas pourquoi donc si tu peux expliquer ce serai bien ^^

**Comment by FEARZYAH** [comment]
Quelle est l'utilité d'avoir enlever les BA? Même si parfois elles étaient en anglais, c'est quand même utile :)

**Comment by Arias800** [comment]
Il ne l'a pas enlever elle sont dispo avec les autre information sur le film il me semble ^^ donc il la juste deplace ^^

**Comment by Arias800** [comment]
Voila le fichier gui.py avec la ba active dans le context menu https://github.com/Arias800/Restaure_ba/blob/master/gui.py

**Comment by fredo04** [comment]
Merci arias800.
Je viens de remplacer le gui.py par celui que tu donne et vstream ne veux pas s'ouvrir, erreur.

**Comment by Arias800** [comment]
ah attends je regarde ca

**Comment by fredo04** [comment]
Pas mieux.

**Comment by Arias800** [comment]
C'est bizarre chez moi ça marche passe les log pour voir

**Comment by fredo04** [comment]
Je suis sur Android si ça peut expliquer.
Les log ok......on fait comment déjà ?

**Comment by Arias800** [comment]
Ah peut être que ça peut expliquer le bug ^^ c'est dans les parametre de vstream et dans outil
Pour les log : Upload Kodi log : Upload automatiquement votre log sur Slexy vous pouvez par la suite simplement nous transmettre l'ID vous étant donner en popup. Votre log http://slexy.org/view/+ votre ID

**Comment by fredo04** [comment]
Alors quand je clic sur upload kodi log une fenêtre s'ouvre en me demandant si je suis sur, je clic oui......et après plus rien.

**Comment by Arias800** [comment]
Mets ce gui.py (https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/gui.py) et normalement ca doit remarche

**Comment by fredo04** [comment]
Je fonctionne sous spmc et non kodi. Spmc ( son créateur faisait partie de l'équipe kodi) et une version de kodi spécialement développée pour Android. D'aspect c'est identique c'est juste optimisé pour les processeurs et l'architecture Android.

**Comment by fredo04** [comment]
Pour le dernier gui.py ça marche mais toujours pas de bandes annonces dans le menu contextuel.

**Comment by Arias800** [comment]
Oui c'est normale c'est celui de base de vstream (la version actuelle )

**Comment by fredo04** [comment]
Ok.

**Comment by fredo04** [comment]
Merci de ton aide.

**Comment by fredo04** [comment]
ça marche.  je faisais toute mes manipulations ( copier le gui.py et recoller) depuis la box android et a chaque fois erreur. Pour etre certain que le nouveau gui.py fonctionne j'ai refais la manip mais depuis l'ordi avec la box android branchée dessus ( comme perriferique de stockage) et la tadaaaaa ça marche avec le premier gui.py fourni. donc merci beaucoup

**Comment by Arias800** [comment]
Ok bon bah temps mit mais normalement avec les ba active tu na pas plus le panel "information"

**Comment by fredo04** [comment]
Pas trop important, j'y allais jamais.

**Comment by Arias800** [comment]
Oui mais bon je préfère prévenir ^^

**Comment by Arias800** [comment]
Ça interresse quelqu’un une version avec uniquement les ba en français ?

**Comment by TmpName** [comment]
Ca si tu y arrives ca m'interesse, sur youtube le resultat est plutot aleatoire pr la recherche FR.

**Comment by Arias800** [comment]
Faut que je teste sur vstream mais normalement ca devrait pas etre mal ^^

**Comment by Arias800** [comment]
voila la version par contre impossible de filtre les version vostfr youtube ne supporte pas ça sur certain film https://github.com/Arias800/Restaure_ba/blob/master/ba_vf_edition

**Comment by TmpName** [comment]
Ce servait a quoi deja le "&sp=EgIYAQ%253D%253D" dans la version originale ?
Par contre ta methode fait avec le titre, et les bandes annonces n'ont souvent nu l'un nu l'autre dans le titre, c'est mieux d'utiliser "gl=FR" dans l'url ?

**Comment by Arias800** [comment]
le "&sp=EgIYAQ%253D%253D" c’était peut être ce qui définit les vidéo courte perso je l'ai enlever parce que ça produisait des résultat trop aléatoire avec les filtre "+vf -vo".
gl=FR revoit des ba en anglais alors qu'avec ma solution YouTube fait un trie même au niveau de la description de la vidéo

**Comment by Arias800** [comment]
J'ai mit dans le fichier un autre url en commenté qui est a testé (il comporte le filtre de video court)

**Comment by TmpName** [comment]
Je viens de tester, pr une serie un animes, ca marche bien.

**Comment by Arias800** [comment]
Ok perso j'ai fait des test et a chaque fois je suis tombe juste et en francais ^^

**Comment by fredo04** [comment]
ça m'interessee mais ou se trouve le fichier ?
je l'ai trouvais dans addons/plugin.video.vstream/resources/lib  c'est bien lui ?

**Comment by Arias800** [comment]
Oui c'est le ba.py ^^

**Comment by fredo04** [comment]
Ok merci. Je viens de faire un essai et j'ai des ba en anglais qui sortent.

**Comment by Arias800** [comment]
ah sur quoi ?

**Comment by fredo04** [comment]
Film/derniers ajouts/cinemay/Big Twitter grave

**Comment by fredo04** [comment]
Film/derniers ajouts/cinemay/Big Two grave

**Comment by Arias800** [comment]
Effectivement je regarde ca ^^

**Comment by Arias800** [comment]
Il n'existe pas de ba en francais sur Youtube

**Comment by fredo04** [comment]
À OK. Ben du coup c'est comme avant alors car si dispo en francais ça sortait en Francais et si pas dispo en francais ça sortait en anglais.
J'ai pas compris ta modif alors.

**Comment by Arias800** [comment]
J'ai renforcer les chance de tombe sur des ba en français car j'ai exclus les ba contenant le mots clé vo ^^

**Comment by fredo04** [comment]
Ok

**Comment by LordVenom** [comment]
Retour des bandes annonces dans le menu contexte a la prochaine mise à jour mensuel.

**Comment by bitschies** [comment]
Bonjour, je me permet d'intervenir sur ce post, j'utilise vstream via spmc sur la miami box. Et outre la disparition du menu bande annonce, il n'y a plus non plus l'option recherche similaire et voir marque page.
C'était pourtant pratique surtout sur la miami où la navigation est pas tjs hyper simple...
Est ce que c'est un bug chez moi?
En tout cas merci pour le job, vous m'avez déjà sauvé bon nombres de soirées.

**Comment by TmpName** [comment]
Recherche similaire, ca fait un moment que c'est plus la, et pour "voir les marque page" c'est pas plus logique de l'avoir a la racine ?

**Comment by bitschies** [comment]
Recherche similaire je l'avais encore le mois dernier, d'ailleurs ça ne faisait pas longtemps que je l'avais. Et j'aimais bien. Genre quand tu regardes une série depuis tes marques pages et que l'épisode suivant fonctionne pas (frustration 😭), une p'tite recherche similaire et hop c'est reparti.
Pour le voir marque page, on l'avais dans le menu de depart (ce que tu appel racine je pense) et dans les raccourcis. Ca me servait quand je faisais des recherches de série, vu que je sais jamais a quelle saison j'en suis j'aillais jeter un oeil dans les marques pages voir la dernière saison vue et un petit retour pour revenir a la recherche.
C'était pratique. 
Après je te l'accorde je suis peut être pas douée à la base, mais du coup ces petits trucs en plus m'aidaient bien. 😊 Ça m'évitait de revenir au menu principal à chaque fois, par ce que sur ma miami, un simple retour ça peut être long parfois...

**Comment by TmpName** [comment]
Moi je vois pas de prbs, faut negocier avec le boss ^^. la il est pas mal occupe avec des restructurations de menu dans tout les sens.

**Comment by LordVenom** [comment]
Heu.. il est en vacances lolllllllll

**Comment by TmpName** [comment]
Ben tiens, pkoi tu crois que je me fais petit et que je te renvois tout le monde ^^.

**Comment by bitschies** [comment]
On est des sales gosses, c'est comme ça. 😊

Non mais en vrai jai cru que c'était un bug, ou qqch que je devais reactiver... je pensais pas que vous l'aviez supprimer.

Mais, quand même, je persiste, c'est dommage. 

C'etait mieux avant 😏

Bref à vous de voir.

Bonnes vacances ou bonne rentrée, je sais pas où vous en êtes.
