### ISSUE TITLE
Recherche Visuelle > Séries > Genres

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1558]
Bonjour,

Je ne sais pas chez vous mais pour ma part quand je fais : 
Recherche Visuelle > Séries > Genres

J'ai bien la liste des épisodes de chaque série mais quand je clique sur un épisode : Il ne se passe rien.

Sinon la nouvelle version semble beaucoup plus rapide pour les recherche. (Je suis sur RPI2)

Merci d'avance pour votre aide.

Florent

**Comment by FEARZYAH** [comment]
Hello,

J'ai le même cas que toi, je me sens moins seul... Quand je clique que ça soit épisode, saison entière, série complète il ne se passe rien.

En espérant que qqun de l'équipe vas nous éclairer sur le sujet :)

**Comment by Arias800** [comment]
C'est toute la categories serie sur la recherche visuel qui ne fonctionne plus

**Comment by TmpName** [comment]
Yep, ca y est ca deconne aussi chez moi, je vois enfin le bug ^^.

**Comment by Arias800** [comment]
Ça redirige pas vers la rechercher globale alors que dans les log ça appels bien "GlobalSearch" ca c'est bizarre

**Comment by layounih** [comment]
J'ai le même bug. Kodi 17.3 sur Android 6. Dernière version de vstream

**Comment by LordVenom** [comment]
Merci pour le retour, Correction à la prochaine mise à jour auto.

**Comment by Arias800** [comment]
Ok merci @LordVenom

**Comment by funilrys** [comment]
@LordVenom New update came today and still not fixed ... --"

**Comment by LordVenom** [comment]
Un Retour ? le bug est résolut ?

**Comment by Arias800** [comment]
Résolut chez moi ^^

**Comment by canopre** [comment]
c'est bon chez moi zossi ! Merci beaucoup !

**Comment by layounih** [comment]
Je viens de mettre à jour mais le pb est encore prèsent.
J'ai vider les caches, ça n'a rien changé. Je procède à une réinstallation ?

**Comment by LordVenom** [comment]
Seul la mise ajour automatique peux avoir le bon fichier elle n'est pas dans le zip de la version.

Modifie le fichier a la main serais le plus rapide.

https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/themoviedb_org.py

**Comment by johnboisvert** [comment]
Même problème pour moi aussi et chez mes 2 frères je vais patienter a la prochaine mise a jour 
savez vous quand? :)

**Comment by Arias800** [comment]
Dans maxi 3 jour normalement la maj des fichier site ^^
