### ISSUE TITLE
Problème spécifique à Adkami

### ISSUE THREAD

**Issue by Nux007** [Kodi-vStream/venom-xbmc-addons#1559]
Bonjour l'équipe, tout d'abord, je tiens à vous féliciter pour votre boulot, on ne le dit jamais assez, sans doute que pour comprendre le temps passé pour un projet il faut être programmeur soi même ;-).

Bon, j'en reviens à mes moutons. J'ai découvert kodi il y a 3 - 4 semaines, et votre addon dans la foulée... Ne faisant plus de python depuis 10 ans, je post donc cette issue sans avoir regardé plus loin dans le code.

**Definition:** Source adkami en paradoxe sur la liste des saisons pour chaque anmié.
**Location:**  Addons > vStream > Animes >  Sources > Adkami
Step 1: Attendre le chargement.
Step 2: Sélection d'un animé ( ils semblent tous buggés )
Step 3: Select season
Bug: vStream fait un loop sur la sélection de la saison, peu importe l'animé choisi.

Testé sur vstream : **V.0.5.3** et sur le **trunk**.
OS: Ubuntu **17.04**
Kodi **17.03**
Relatded log file: [https://pastebin.com/7n3TUCk8](https://pastebin.com/7n3TUCk8)

**Comment by Arias800** [comment]
Problème au niveau de la récupération des hoster ou des épisode je connais pas trop le code d'adkanim mais le bug de rechargement c'est normale quand on clique sur saison car c'est juste pour séparer les différente saison ^^

**Comment by Nux007** [comment]
En fait, le réel soucis est le paradoxe sur la séletion d'une saison. Je m'explique, à cheque fois que je clique sur une saison, peu importe l'anime, je suis redirigé vers une autre page contenant aussi la meme liste de saisons, si je clique à nouveau, rebelote, de nouveau la liste des saisons. Pour revenir en arrière, je dois cliquer sur "..." autant de fois que j'ai cliqué sur la saison.

**Comment by Nux007** [comment]
Bhen en fait, je viens de remarquer que j'ai ca avec pas mal de sources... hmmmmm

**Comment by Nux007** [comment]
hmmm, j'ai même ca avec la plupart des sources, aucun lien de streaming, j'investigue toujours.

**Comment by Arias800** [comment]
Oui c'est normale ca me le fait aussi je pense que dans les menu de kodi ont ne peux pas afficher de texte non cliquable donc vstream "refresh" le menu a chaque fois que tu clique sur saison xx ^^

**Comment by Nux007** [comment]
Ok, donc le soucis est qu'il n'y a aucun lien référencé, c'est donc un problème relatif à mon installation ... Ca avance :-) J'ai supprimé les temporaires, logs, etc ... je vais voir mes logs. 
Ce qui est bizarre c'est que ca ne le fait pas avec toutes les sources...

**Comment by Arias800** [comment]
Pour adkami c'est un normale le site est down sur vstream mais pour les autre c'est bizarre

**Comment by Nux007** [comment]
Je ne savais pas qu'il était down, j'y regarderai, ce sera l'occasion idéale de me remettre à python. Par contre, je cherche toujours car ce n'est pas normal d'avoir autant de liens manquant avec autant de sources.

**Comment by Arias800** [comment]
Passe les log ca peux aider pour adkami j'ai fait réapparaître les épisode maintenent je m'occupe des hsoter

**Comment by Nux007** [comment]
Ok, je repasse en 0.5.3, j'étais en trunk ( master ) les soucis sont identiques.

Logs frais: [https://pastebin.com/nzeH8Kzu](https://pastebin.com/nzeH8Kzu)

**Comment by Arias800** [comment]
Adkami nouvelle version termine j'attend la verification ^^

**Comment by Nux007** [comment]
Quelle rapidité :-)

**Comment by Arias800** [comment]
Ah tu fait buggé vstream avant de passer les log ?

**Comment by Nux007** [comment]
Non, pas encore, c'est pour ca que j'ai indiqué "logs frais" :-)

**Comment by Arias800** [comment]
ah ok ^^

**Comment by Nux007** [comment]
Voilà m'sieur :-)

[https://pastebin.com/8SRJkEgp](https://pastebin.com/8SRJkEgp)

**Comment by Nux007** [comment]
Je confirme que ca n'affecte pas toutes les sourses.

**Comment by Nux007** [comment]
Pendant que tu check, je vais tester ta regex adkami :-)

**Comment by Arias800** [comment]
Je pense que le probleme vient de APEP Common Routines mais le probleme c'est que je ne sais pas ce que c'est :/

**Comment by Arias800** [comment]
Regarde si tu l'interface web activer pour cela il faut aller dans Settings → Services → Control → Allow remote control via HTTP et verifie que c'est decoche

**Comment by Nux007** [comment]
J'ai désactivé APEP , je regarde ce que ca donne. le controle http est en effet activé, je l'utilise pour divers tests php :-) ca m'ennuierais de le désactiver mais bon, s'il n'y a pas d'autres solutions...

**Comment by Arias800** [comment]
Apres je suis pas sur que ce soit ca mais bon ca vaut le coup d'essayer ^^

**Comment by Nux007** [comment]
hmmm, c'est vraiment bizarre ... Regarde :
Les sites se chargent, a part des liens morts sur certaines sources, je n'ai pas encore regardé adkami.
[https://pastebin.com/pTADq7n1](https://pastebin.com/pTADq7n1)

**Comment by Arias800** [comment]
La derniere video (celle sur raptu ) tu a pu l'ouvrir (pour le film a bras ouvert) ?

**Comment by Arias800** [comment]
Désactive Skin Helper Service ca fera un probleme en moins

**Comment by Nux007** [comment]
Ouep, j'ai pu l'ouvrir sans soucis
Pour Skin Helper, je viens de le faire :-)
Je fais un tour, mais ca me semble résolu, sauf pour adkami, je n'ai pas encore fait le pyo, il faut que je me refamiliarise avec tout ca :-)

**Comment by Arias800** [comment]
Uptostream peux ne pas fonctionner car chez moi aussi il ne s'ouvre pas

**Comment by Nux007** [comment]
J'ai quand meme pas mal de liens morts, mais bon, ce n'est pas en rapport avec l'addon il faut faire avec lol.

**Comment by Arias800** [comment]
Apres youwatch exashere et allvid sont mort définitivement uptostream a des probleme chez moi apres les autre c'est moins normale (ou pas normale si tout s'ouvre via le navigateur)

**Comment by Nux007** [comment]
Je vais tester tout ca, tu utilises la version du trunk ?

**Comment by Arias800** [comment]
C'est quoi "trunk" ?

**Comment by Nux007** [comment]
Donnes moi une source sur laquelle tu as ces liens stp, ce sera plus rapide que de chercher dans tout ce qu'il y a :-)

**Comment by Nux007** [comment]
l'équivalent du "master" mais avec subversion ( != git )

**Comment by Arias800** [comment]
ah ok ^^

**Comment by Nux007** [comment]
je suis de la vieille école lol

**Comment by Arias800** [comment]
Sur voirfilm tu plein de choix au niveau des hoster (pour le film dunkerque normalement il doivent tous fonctionne (sauf peut etre 1fichier et uptobox)

**Comment by Nux007** [comment]
Gangsterdam     ->  uptostream -> fichier introuvable
The black Room ->  uptostream -> fichier introuvable
Les Schtroumpfs -> uptostream -> fichier introuvable
Power ranger 2017 -> uptostream -> fichier introuvable
Gardiens galaxie -> uptostream -> introuvable

**Comment by Arias800** [comment]
uptostream est mort chez moi aussi ^^ faut tester openload flashx netu éventuellement ok,ru

**Comment by Nux007** [comment]
flashx ok à hauteur de 80% des flux

**Comment by Nux007** [comment]
je teste actuellement le flashx de powerrangers sur Tv-Streaming , les vieux animes style picsou ok aussi avec flashx

**Comment by Nux007** [comment]
* Et ca fonctionne

**Comment by Arias800** [comment]
Bah ca a l'air ok ^^

**Comment by Nux007** [comment]
Ce pourrait être chouette 'identifier les liens morts pour pouvoir les suppriler de la base au lancement de vstream.

**Comment by Arias800** [comment]
Oui ca pourrait etre pas mal mais est ce que ca vaut le coup

**Comment by Nux007** [comment]
ca dépends ou tu te place, coté développeur ou coté utilisateur :-)

**Comment by Nux007** [comment]
ca fait partie de l'ergonomie générale

**Comment by Arias800** [comment]
Oui c'est pas faut ^^

**Comment by Nux007** [comment]
Je le ferai peut être si je me décide à reprendre python lol
Openload ok de mon coté

**Comment by Arias800** [comment]
Ah ^^

**Comment by Nux007** [comment]
Netu ok aussi

**Comment by Nux007** [comment]
Jusqu'a ce que kodi se fasse killer par une video netu lool

**Comment by Arias800** [comment]
Ah bah ca arrive moi ca me le fait si je recharge 2 fois la meme video x)

**Comment by Nux007** [comment]
Ho purée, ca recommence :
[https://pastebin.com/WCnY7nWk](https://pastebin.com/WCnY7nWk)

**Comment by Arias800** [comment]
La je sais pas :/ faudrait attendre @TmpName @LordVenom

**Comment by Nux007** [comment]
J'ai supprimé un module qui ne fonctionnait pas, il y a du mieux mais toujours certains sites qui ne chargent pas

**Comment by Arias800** [comment]
Apres tu peux essayer si tu a d'autre addon de faire une backup du fichier addon et de les réinstaller un par un au moins on pourra isoler les addon qui pose probleme

**Comment by Nux007** [comment]
En tout cas ce qui est certain c'est que c'est lié à mon installation et non pas au plugin...

**Comment by Arias800** [comment]
Aurait tu un caractere special dans le nom de l'ordi ? (un accent ou ce style de chose)

**Comment by Arias800** [comment]
ou dans ton nom de repetoire

**Comment by Nux007** [comment]
Non, rien de tout ca, en plus j'utilise le ppa officiel en stable. Je vais déjà faire un nettoyage complet de kodi car je m'apperçois qu'il y a pas mal de dossiers modules non supprimés ou encore référencés dans les logs alors qu'ils ont été supprimé DANS KODI.

**Comment by Arias800** [comment]
Tu a installer vstream via le repository ?

**Comment by Nux007** [comment]
ouep, repository vstream 0.0.2

**Comment by Arias800** [comment]
Bon bah la je sais vraiment pas x)

**Comment by Nux007** [comment]
Pas grave, c'est déjà bien sympa d'aider ;-) je vais déjà faire un gros nettoyage de kodi, mais dans l'immédiat je vais faire une petite pause mdrrr

**Comment by Nux007** [comment]
Je vais complètement réinstaller kodi avec uniquement vstream pour voir car j'ai toujours des sources qui ne peuvent pas être chargées, j'ai ré ouvrirai le ticket si ca ne résoud pas le soucis...

**Comment by TmpName** [comment]
Nouvelle version de up2strm (pas encore en MAJ)
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1563
