### ISSUE TITLE
Upto_tream

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1563]
Retourne fichier introuvable chez moi . D'autre dans ce cas ?

**Comment by Nux007** [comment]
Pareil chez moi

**Comment by TmpName** [comment]
Nouvelle version a tester
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/uptostream.py

**Comment by Arias800** [comment]
Pas resolu chez moi pour blacklist lien non hs http://uptostream.com/jcxql38gl3sk

**Comment by TmpName** [comment]
Ben chez moi ca m'a presente les 3 formats et ca a marche.
Tu es sur que ca vient pas du fichier site ?

**Comment by Arias800** [comment]
je sais pas ^^

**Comment by TmpName** [comment]
Tu es passe par quel site ?

**Comment by Arias800** [comment]
Zone telechargement,ws et j'ai aussi fait des teste sur kaydo

**Comment by TmpName** [comment]
J'ai teste sur kaydo, pas de lien uptostrm mais des liens uptobox que j'ai fait convertir et le film a demarre.
Tu es sur de ne pas avoir depasse le quota ?

**Comment by Arias800** [comment]
Ça fait plusieurs jours que je ne peux plus utilise upto donc bon l'attente est longue x)

**Comment by TmpName** [comment]
il y a des lignes de code pr le debug dans le fichier python (mise en commentaires), ca enregistre la page html dans c: (ca depend du niveau de protection de ton ordi), regarde le code pour voir.

**Comment by Arias800** [comment]
J'ai rien dans le fichier

**Comment by Arias800** [comment]
Apres c'est peut etre en lien avec ce bug https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1555

**Comment by TmpName** [comment]
C'est bizarre , peut etre un truc avec le https http ?
Et si actives le debug de kodi ?

**Comment by Arias800** [comment]
Problème règle j'ai juste mit ajour le fichier
