### ISSUE TITLE
Nombre de page

### ISSUE THREAD

**Issue by alex83100** [Kodi-vStream/venom-xbmc-addons#1564]
Bonjour,

Sur la source zone de telechargment.ws  quelque soit  le choix à parcourir je n'ai que 3 à 4 pages alors que sur le site j'en ai beaucoup plus. Quelqu'un a-il le même problème que moi ?

Alexandre

**Comment by Arias800** [comment]
Dans films(dernier ajouts) tu dois en avoir beaucoup plus normalement peux tu me donner un exemple de categories ou tu a peux de page ?

**Comment by TmpName** [comment]
Confluence
