### ISSUE TITLE
playlist mémoirisé

### ISSUE THREAD

**Issue by jpforever** [Kodi-vStream/venom-xbmc-addons#1568]
je pensé a une option qui pourrait être utile dans le plugin, pouvoir mémorisé des playlist. je pense que ça serait un bon plus pour le plugin si c'est possible

**Comment by TmpName** [comment]
Comme les favoris ?

**Comment by jpforever** [comment]
@TmpName un peut le même style que les favoris mais avec les playlist, pour ne pas avoir à la refaire a chaque fois, par exemple une série on pourrai crée une playlist et la sauvegarder, comme ça il enchaine les épisodes sans que l'on ai besoin de refaire la playlist a chaque fois.
je sait pas si j'ai bien explique lol

**Comment by Arias800** [comment]
Oui en gros une liste qui permet de lire des episode tout seul automatiquement ^^

**Comment by jpforever** [comment]
@Arias800 oui en gros c'est ça ;), mais ça pourrais fonctionner aussi avec des films par exemple

**Comment by Arias800** [comment]
Oui mais c’était un exemple ^^

**Comment by jpforever** [comment]
@Arias800 je sait mais j'en ai ajouter un autre ;)

**Comment by TmpName** [comment]
Pas possible, pour faire une playlist faudrait faire avec le dernier lien, celui de la video. et c'est le moins stable, opelaod marche tres bien cette semaine mais laguait a fond la semaine derniere passe 22h.
Si tu supprimes l'intervention humaine, tu vas augmenter les liens morts.

**Comment by LordVenom** [comment]
Bonjour, Pour faire une playlist deux solution, 
Pour cela toujours partir du Host, le dernier lien en bleu ex: avatar(openload)

- Ajouter à la playlist faite ça pour tous vos lien et enregistrer la.
- Ajouter au marque page puis dans les marques-pages section source click droit et lire a partir...

**Comment by jpforever** [comment]
@LordVenom merci pour ces infos, seulement sur la première solution comment je fait pour enregistré ma playlist après avoir ajouté tous mes liens? 
La deuxième solution est pas mal aussi, mais si ont pouvez créer nos propres dossiers dans les marques page je pense que sa serait parfait pour cette solution

**Comment by LordVenom** [comment]
C'est compréhensible ça ou pas ?

![image](https://user-images.githubusercontent.com/4380112/29245635-b0cfd39e-7fe0-11e7-9321-6fa86a274a55.png)

**Comment by jpforever** [comment]
@LordVenom bizard j'ai pas cette onglet dans les paramètres du plugin

**Comment by LordVenom** [comment]
Non c'est normal.

**Comment by jpforever** [comment]
@LordVenom pourquoi ça n'iras pas pour le moment?

**Comment by LordVenom** [comment]
Pas de changement dans les marques pages trop de taff et ça tourne bien comme ça.

**Comment by VinhLg** [comment]
Bonjour,

Il n'y a pas eu de réponse à la question « comment enregistrer la playlist après avoir ajouté les liens ? ».

Pour ceux qui cherche encore la réponse, la voici : il suffit d'aller dans le volet de gauche, tout en bas il y a la playlist actuelle, entrez, ensuite déployez à nouveau le volet sur la gauche et enregistrer là. Vous la trouverez dans la rubrique vidéo sous le nom que vous lui avez attribué.

Bonne après-midi ;)
