### ISSUE TITLE
StreamComplet

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1569]
chez moi ce site est mort. pas d'accès depuis un navigateur.

Edit: sauf depuis TOR

**Comment by Arias800** [comment]
Sûrement un blocage DNS ^^

**Comment by TmpName** [comment]
Suffit de passer par l'adresse IP directement, sans taper l'url, mais je ne l'ai pas encore trouve, (le whois me donne l'ip de cloudfalre)

**Comment by LordVenom** [comment]
Bizarre pas chez moi opérateur free

**Comment by Arias800** [comment]
Chez moi c'est bloquer (orange)

**Comment by LordVenom** [comment]
Et si tu change tes dns ça passe ? ou c'est pas aussi simple ?

**Comment by Arias800** [comment]
Ca marche avec openDns donc ca doit etre un bloquage avec le dns d'orange ^^

**Comment by TmpName** [comment]
Et si tu peux te connecter dessus, tu pourrais pas nous passer l'ip ?
On a eu un autre site qui avait le meme prb, et on avait code un bypass dns dans le code python.

**Comment by Arias800** [comment]
J'ai trouve cette adresse mais je sais pas si c'est la bonne ^^ 46.246.69.68

**Comment by TmpName** [comment]
Nope ^^. Pour savoir si c'est la bonne suffit de la taper dans la barre d'adresse.
Si tu tu peux t y connecter c'est pas dur, il te suffi d'utiliser un url resolver en ligne. Sinon dans les logs du parefeu.

Ca c'est pas trop dur a trouver, mais je retrouve pas le vieux code, et j'ai pas trop le temps de le refaire.

**Comment by TmpName** [comment]
Pour les bidouilleurs.
https://pastebin.com/WV8dM9xg

Ce code permet de bypasser le bloquage dns, en fait ca code notre propre dns resolver, ca marche pour la premiere page, pas pr les images, pas teste les hosters (vu que j'ai pas acces au site non plus).

Pour les images, je vois pas comment faire vu que c'est kodi qui gere le truc, en y passant l'url decodée et un "host" en parametre peut etre, mais je sais pas si il gere ca (normallement oui car j'ai deja pu y faire passer des cookies en url)

**Comment by Arias800** [comment]
Tu as essayer openDns : 208.67.222.222 · 208.67.220.220 pour acceder au site perso a fonctionner ^^

**Comment by TmpName** [comment]
Yep, mais on peut pas demander a tout les users de passer sur opendns.

**Comment by Arias800** [comment]
On peux pas force kodi a utilise un dns precis ?

**Comment by TmpName** [comment]
Pareil, tu demanderais a tout les suer de configurer kodi d'une certaine maniere ? La plupart ne savent meme pas ou se trouve la configuration.

**Comment by Arias800** [comment]
Chez moi tout fonctionne (hoster image recherche)

**Comment by razorex** [comment]
Ah bon et tu a fait qqchose ^pour que sa passe @Arias800 ??

**Comment by Arias800** [comment]
J ai mit le fichier de TmpName ^^

**Comment by TmpName** [comment]
Mais j'ai pas fini de tout corriger sur le fichier, j'ai juste fait showmovie de memoire.
