### ISSUE TITLE
Ajout film à la librairie

### ISSUE THREAD

**Issue by alex83100** [Kodi-vStream/venom-xbmc-addons#1570]
Bonjour, il y a-il une raison pour supprimer l'année du film lors de l'ajout d'un film à la librairie ? le problème, c'est que sans l'année le scrapper ne reconnait pas forcement le bon film lorsqu'on scan le répertoire contenant les STRM.

**Comment by TmpName** [comment]
Nope, pas de raisons, m'en occupe ce WE.

**Comment by TmpName** [comment]
Heu tu as un exemple ou l'année est supprimée ?
Je viens de faire un test c'est le titre affiché qui est utilise.

**Comment by alex83100** [comment]
Bonjour, oui ci joint le fichier généré, à partir d'une source de zone de téléchargement avec un lien uptobox https://www.amazon.com/clouddrive/share/vyeJ1VsICBLsolvUXXZbaO02gG0zTdlu3s9SPsNDIKh .En l'occurence ici Brimstone multi 1080p sous zone de telechargement .Le scrapper se débrouille très bien avec un nom complet, il suffit je crois d'enlever au moins le nom du site et le nom de la source.

**Comment by TmpName** [comment]
En fait tout se joue sur le titre, ma question concernait le site. Quand je teste il n'y a pas la date dans le titre, donc pas possible de la rajouter sur le nom du fichier.

**Comment by alex83100** [comment]
Je comprend que le titre affiché ne comprend que le nom du film, néanmoins le context menu uptobox (ajout à mon compte uptobox) que l'on peut lancer à partir de la même page et sur le même lien génère le fichier suivant Brimstone.2016.MULTI.1080p.WEB.H264-PHI.WwW.Zone-Telechargement.Ws.mkv je suis persuadé que le scrapper arrive à trouver le bon film à partir de Brimstone.2016.MULTI.1080p.WEB.H264. Il y a t-il un moyen de généré ce nom long à la place du nom court ? où au moins donner la possibilité de choisir lors de la création du strm. Vous devez avoir le même problème pour la recherche de bande annonce si vous n'avez pas la date du film à partir du titre court.

**Comment by Arias800** [comment]
Oui c'est vrai que si les  film ont le même noms ça pause problème au niveau des bande annonce ^^

**Comment by TmpName** [comment]
Ca c'est le nom du fichier, donc ca peut etre video.mkv ou meme dfd8787dfdf4545.mkv pas utilisable, ca marche pour ce site mais pas pour les autres.

Pour les bande annonces suis meme pas sur que la date soit sur toute les videos, c'est juste des recherches youtube.

**Comment by Arias800** [comment]
Pas sur toute mais sur certains elle sont dispo dans le titre

**Comment by alex83100** [comment]
Bonjour, oui je n'avais pas pensé que le nom du fichier pouvais ne pas contenir la date du film sur certain site ... mais est_il possible techniquement avant d'écrire le fichier strm d'ouvrir une fenêtre de dialogue pour permettre à l'utilisateur de changer le titre (pour y rajouter l'année par exemple). Ou mieux encore, avant d'ecrire le fichier strm, de lancer une recherche sur le titre du film (comme on peut le faire dans kodi sur un film non reconnu dans le bibliothèque) pour écrire ensuite le nom du fichier avec la date ?

**Comment by TmpName** [comment]
Kodi peut te le demander aussi, quand il scrappe les infos (du fichier strm), il peux te proposer plusieurs choix quand il en trouve plus, mais je me souvient plus comment j'avais fais. Peut etre quand je le faisait 1 par 1.

**Comment by alex83100** [comment]
oui c'est ce que je fais, après en avoir enregistré un dans la librairie, je vais sous kodi dans Videos / File / le répertoire de vstream ou se trouve les films puis je choisis le film que je viens d'ajouter à la library et je fais (si il n'est pas reconnu) "scan to library" à partir du menu contextuel, il m'ouvre alors une fenêtre et je peux choisir le film. Par exemple, pour le film "chez nous", j'ai 4 choix un en 2017, 2013, 2012 et 1978. Si je choisis celui de 2017 ma bibliothèque est à jour avec la bonne jaquette. Si il est reconnu mai avec une mauvaise jaquette, je vais dans information, refresh information et là aussi je peux choisir le bon film). Mais cela ne renomme pas le fichier, ce qui veut dire que si je partage mon répertoire contenant les fichier strm avec un autre poste la manip est à refaire. L'idéal est donc renomer correctement le fichier lors de la création du strm ce qui permet au scrapper de ne pas se tromper de film.

**Comment by TmpName** [comment]
Mais le probleme c'est que ca augmente le nombres de manip, tu imagines pr une serie ? Le temps de rentrer tout les episodes le premier lien est deja mort ...

Bon je deconne ^^, je peux te rajouter une fenetre pr confirmer le titre avant la creation, mais tu l'auras pour tout les fichiers, et je ne vois pas comment tu vas deviner les dates des films que tu enregistres ?

**Comment by alex83100** [comment]
Merci, à toi. Pour l'instant j'utilise le context menu addlib que tu peux trouver sur github avec Taifxx/xxtrep. il s’intègre assez bien à Vstream mais, cela fait un moment qu'il n'y a pas eu d'évolution du code. Pour ce qui est de deviner l'année, elle figure très souvent dans les résultat de la recherche.

**Comment by TmpName** [comment]
Essayes avec ce fichier
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/library.py

**Comment by alex83100** [comment]
Bonjour la creation du fichier se fait correctement mais lorsque je veux le lire cela m'indique fichier introuvable. La lecture du fichier strm fonctionne pour toi ?

**Comment by TmpName** [comment]
Mince, je corrige ca dans l'apres midi.

**Comment by alex83100** [comment]
Si cela peut t'aider :

Le lien générer par l'addon addtolib qui fonctionne

nom du fichier chez.nous.strm

plugin://context.addtolib//?#strmtype=#10002&#strmfile=#chez.nous.strm&#strmurl=#plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=Chez+Nous+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sHosterIdentifier=uptobox&sTitle=Chez+Nous+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&siteUrl=http%3A%2F%2Fuptobox.com%2Frqe90g82g5dr&sFav=play&sMediaUrl=http%3A%2F%2Fuptobox.com%2Frqe90g82g5dr&sCat=4&sId=cHosterGui&sFileName=Chez+Nous

et le tiens (même sans rajouter la date) il ne fonctionne pas

nom du fichier chez nous.strm

plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=Chez Nous&sMediaUrl=http%3A//uptobox.com/rqe90g82g5dr&sHosterIdentifier=uptobox

**Comment by TmpName** [comment]
Remet a jours le meme fichier que precedement.
Et celui la
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/hoster.py

Mais je vois que quelqu'un a desactive la mise a jours auto des fichier que tu rajoutes en librairie, du coup tu as oblige de faire scanner le repertoire par kodi.

**Comment by alex83100** [comment]
je viens de faire un test, si ton strm contient : plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=Chez Nous&sHosterIdentifier=uptobox&sTitle=Chez Nous&siteUrl=http://uptobox.com/rqe90g82g5dr&sFav=play&sMediaUrl=http://uptobox.com/rqe90g82g5dr&sCat=4&sId=cHosterGui&sFileName=Chez Nous  cela fonctionne.

Je vais essayer maintenant de remettre l'ancien hoster.py

**Comment by alex83100** [comment]
en mettant le fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/hoster.py

J'ai un message d'erreur dont voici le log kodi.

   Error Contents: No module named hoster
                                            Traceback (most recent call last):
                                              File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 6, in <module>
                                                from resources.lib.gui.hoster import cHosterGui
                                            ImportError: No module named hoster
                                            -->End of Python script error report<--
14:03:38.109 T:3204   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/
14:03:38.109 T:3204   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/) failed

**Comment by alex83100** [comment]
j'avais une sauvegarde de mes fichiers, je n'ai donc plus de problème à présent pour lancer Vstream.

**Comment by TmpName** [comment]
Sinon utilises un editeur de fichier. Y a juste 2 lignes a rajouer
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/3c15996015ef0d609cc1a9dfa908ea084fe1ccbb

**Comment by alex83100** [comment]
je t'assure si je rajoute ces deux lignes je ne peux pas ouvrir vstream, il faut aussi remettre l'ancien library.py ?

**Comment by TmpName** [comment]
Nope le nouveau https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/library.py
Mais lui ne change pas grand chose.

Mais le message d'erreur est bizarre, ca ne dit pas qu'il ne peut pas le charger mais qu'il ne le trouve pas ....

**Comment by alex83100** [comment]
Je viens de modifier ton fichier library.py que tu m'avais envoyé avec la ligne ci dessous et le lien fonctionne de mon cotés.

sLink = 'plugin://plugin.video.vstream/?site=cHosterGui&function=+play&title='+ sFileName + '&sHosterIdentifier=' + sHosterIdentifier +'&sTitle=' + sFileName + '&siteUrl=' + sMediaUrl + '&sFav=play&sMediaUrl=' + sMediaUrl + '&sCat=4&sId=cHosterGui&sFileName=' + sFileName

à la place de 

sLink = 'plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=' + sFileName + '&sMediaUrl=' + sMediaUrl + '&sHosterIdentifier=' + sHosterIdentifier

Cela fonctionne, je peux donc à présent ajouter l'année manuellement sur le nom des fichiers strm.

Je vais faire d'autres tests.
