### ISSUE TITLE
Voir le rating du film sans appuyer sur la touche information

### ISSUE THREAD

**Issue by mifrey00** [Kodi-vStream/venom-xbmc-addons#1571]
Bonjour,

J'ai essaye toutes les vues (List, Poster, Shift, etc.) mais aucune ne permet de voir le rating du film.  Il faut pour chaque film appuyer sur la touche information pour voir le rating.  La vue Shift montre directement pas mal d'infos comme le genre, le producteur, la date de diffusion mais pas le rating.  Y a-t-il un moyen de voir le rating directement ?

Merci

**Comment by fredo04** [comment]
Bonjour. J'utilise le skin aeon nox qui fais apparetre les notes/résumé/acteur/année/genre sur la même page. Il faut choisir la vue "vitrine" directement.

**Comment by fredo04** [comment]
Une photo de mon skin.
URL=https://www.hostingpics.net/viewer.php?id=

**Comment by fredo04** [comment]
Le premier lien ne fonctionne pas.
http://hpics.li/8e38bfd

**Comment by mifrey00** [comment]
Merci ca marche en effet avec d'autres skins.

**Comment by fredo04** [comment]
De rien.
