### ISSUE TITLE
Site de Stream et Television !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1576]
Je viens de trouver un Site de Streaming du Nom de "Que du Stream" au quedustreaming.com/
J'ai vu que le Rubrique "Television" à disparue sur vstream et ça sera pas mal de la ré-avoir. Si c'est possible, je suggères le Site "ARTV" au artv.watch/countries/france/ (Lien des Chaines)

**Comment by razorex** [comment]
ARTV à une application

**Comment by LordVenom** [comment]
Pas stable leur system faire payer un abonnement pour ça ? bizarre.

**Comment by luluvulcain** [comment]
Oui ARTV est disponible sur Internet et Android. Y'as un abonnement oui mais c'est fait pour entretenir les Serveurs.
