### ISSUE TITLE
Problèmes vstream raspberry pi

### ISSUE THREAD

**Issue by cozaq** [Kodi-vStream/venom-xbmc-addons#1577]
Bonjour,

Je suis sous raspberry PI 2.

J'ai installé OSMC, puis Vstream (via superrepo).

Tout fonctionne bien pendant quelques heures, puis, lorsque je veux lire un film, soit vstream me dit "fichier introuvable", soit il me dit qu'il y a une erreur dans ma librairie.

J'ai essayé de désinstaller vstream, puis OSMC, et tout réinstaller plusieurs fois, mais rien à faire.

Quelqu'un aurait il une idée ? Je découvre le système donc je galère un peu.

Merci !

**Comment by Arias800** [comment]
Utilise tu  youwatch allvid exashere ? Car ils sont HS ça pourrait en partit expliquer la notification fichier introuvable.

**Comment by cozaq** [comment]
Non justement je privilégie les liens uptobox

**Comment by Arias800** [comment]
Avec uptostream ?

**Comment by cozaq** [comment]
Quand je choisis mon films j'ai le choix entre "streaming avec uptostream" et "direct avec uptobox". En général je choisis en direct mais les deux ne fonctionnent pas

**Comment by Arias800** [comment]
Ah bizarre qu'uptobox ne fonctionne pas :/

**Comment by Arias800** [comment]
Tu peux passer les log ?

**Comment by cozaq** [comment]
Comment je peu les avoir ?

**Comment by Arias800** [comment]
Dans les parametre de vstream ensuite outils , Upload Kodi log : Upload automatiquement votre log sur Slexy vous pouvez par la suite simplement nous transmettre l'ID vous étant donner en popup. Votre log http://slexy.org/view/+ votre ID

**Comment by cozaq** [comment]
HTTPS://slexy.org/view/s21MMGRt4h

**Comment by Arias800** [comment]
faut faire un log apres que le bug soit apparut parce que la il est vide ^^

**Comment by cozaq** [comment]
Voilà le log juste après avoir eu le défaut "consultez votre journal"

HTTPS://slexy.org/view/s207k6NCrg

**Comment by Arias800** [comment]
@TmpName doit ca peut venir ca ? COMXImageFile::GetCodingType progressive images not supported by decoder

**Comment by Arias800** [comment]
Sinon a part ca rien de bizarre dans les log :/

**Comment by cozaq** [comment]
Parfois ça marche, parfois non, alors que chez un pote qui a la même config il a pas de soucis.
Peut être la box ?

**Comment by Arias800** [comment]
Les meme films exactement ?

**Comment by Arias800** [comment]
Le dernier liens est non fonctionelle sur le site donc pas fonctionelle chez nous ^^

**Comment by cozaq** [comment]
Oui sur les memes films.

**Comment by Arias800** [comment]
Apres je sais qu'uptobox a une limite mais je sais pas la quel ^^

**Comment by cozaq** [comment]
J'ai un compte là bas qui permet d'avoir accès en illimité aux films. Je peu l'associer avec kodi ?

**Comment by Arias800** [comment]
Oui ^^dans les parametre il y a un endroit pour les compte ^^

**Comment by cozaq** [comment]
Ah c'est peut être ça

**Comment by cozaq** [comment]
Je viens d'essayer avec le film doctor strange. J'ai rentré mon id uptobox, pas de soucis la dessus.
Le film s'est lancé, puis il s'est arreté. J'ai essayé de le relancer, puis il m'a signalé le même pb qu'avant. Je l'ai fait avec mon tel, sur de la 4G donc ma box n'est pas en cause

**Comment by alex83100** [comment]
bonjour votre carte SD sur votre raspberry PI n'est pas pleine ?

**Comment by cozaq** [comment]
non elle est vide. mais j'ai le même soucis sur mon tel...

**Comment by cozaq** [comment]
Je viens d'essayer avec un autre pc, chez qulqu'un d'autre. Toujours le même problème.Petite question, est ce que cela peut venir a la base du fichier zip repository, ou cela ne change rien ? Si oui est ce que vous conaissez un site ou je pourrais le telecharger ou alors la source à rentrer ?

**Comment by Arias800** [comment]
Voila ou telecharger le repo https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository

**Comment by TmpName** [comment]
"skipping unplayable item"
Ca ca le fait quand le compte uptobox est mal regle (sur leur site), il ya 3 options qui DOIVENT etre coche ou decoche.

Verifie que sur ton compte uptobox (sur navigateur) tu n'ais pas coche "téléchargement direct" et "telechargement SSL".
Et le troisieme option me souviens plus laquelle c'est.

**Comment by cozaq** [comment]
Merci pour la réponse.
Le problème c'est que d'habitude je n'utilise pas mon compte uptobox et j'ai le même soucis. Et je viens daller sur mon compte uptobox, mais je n'ai pas accès aux paramètres que tu m'as cité plus haut. Soit je ne les voit pas soit je me débrouille comme une bille

**Comment by TmpName** [comment]
La je peux pas te dire non plus ^^, je crois que c'est que pr les premium, moi j'ai un compte gratuit.

**Comment by cozaq** [comment]
Je viens de refaire des tests. Beaucoup de films sont introuvables via uptobox mais dispo via uptostream. Ya une limitation sur uptostream ?

**Comment by Arias800** [comment]
C est pas plutôt l inverse trouvable sur uptobox et pas sur uptostream ? Car chez moi c est comme ça en tout cas ^^

**Comment by cozaq** [comment]
Nan lol justement c'est l'inverse chez moi mdr

**Comment by Arias800** [comment]
Ah d accore x)

**Comment by TmpName** [comment]
Oui y a une limite 1h30 en free, 3h en enregistre, illimite pr premium (de memoire)
