### ISSUE TITLE
Affichage source Uptobox

### ISSUE THREAD

**Issue by alex83100** [Kodi-vStream/venom-xbmc-addons#1578]
Bonjour, est-il possible d'augmenter le nombre de fichiers vu dans la source Uptobox ? Actuellement uniquement 25 lignes sont affichées, et pas de possibilité de faire next page. Je viens de vérifier, il suffit de mettre http://uptobox.com/?op=my_files&per_page=1000 à la place de http://uptobox.com/?op=my_files pour afficher par exemple 1000 lignes.

**Comment by TmpName** [comment]
Source HS pr le moment
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1555
