### ISSUE TITLE
Feature Request - Afficher les liens des comptes premium uniquement

### ISSUE THREAD

**Issue by celogeek** [Kodi-vStream/venom-xbmc-addons#1579]
Hello,

C'est une requête d'ajout pour une option.

J'ai activé mon compte premium uptobox, et j'aimerais n'afficher en résultat des ShowHosters, ShowSerieHosters que les liens de ce compte là (j'ai regardé le code, mais le parsing est vraiment très orienté pour tout prendre).

Ca serait bien d'avoir une option dans les paramètres pour ne garder que les liens uptobox dans le résultat des recherches. Genre "Afficher uniquement les liens des comptes premium activés"

Est ce possible ?

Merci

**Comment by Arias800** [comment]
Afficher que les liens premuim ? et si il n'y en a pas ça retourne riens ?

**Comment by LordVenom** [comment]
Vstream n'a pas de system pour activer ou pas une source.

Ne regarde pas le parsing des sites mais plutôt hoster.py qui cherche si le host existe ou pas alors il ne serais pas difficile je pense de regarder si elle et activer ou pas mais ça reste à coder.

**Comment by celogeek** [comment]
En fait c'est plus simple que ça.

Ca serait pas mal de pouvoir choisir les hosters qu'on souhaite afficher.

Par exemple je ne veux que uptobox, alors cela n'affiche que celui la dans les liens trouvés. que ça soit des liens premium ou pas.

Comme ca si on a un compte premium et qu'on souhaite favoriser celui ci, alors on peut.

**Comment by Arias800** [comment]
Donc si uptobox est down tu n'a plus rien tres utile  ^^

**Comment by TmpName** [comment]
Exactement, perso j'ai pas envis d'avoir tout les jours, "ca marche pas y a plus de liens".
Pareil une option qui est sur exodus et qui ne sera pas sur Vstream, c'est quand une source est HS l'addon passse a la suivante, resultat, tu choisis opnlad pour avoir de la HD et tu te retrouvais sur Youwatch avec un truc bien baveux.

Et meme si ca n'affichait que les liens uptobox, ca te fais gagner du temps ou ? Y aura le meme nombres de pages affichees, a part que sur une il n'y aura qu'un lien ou rien du tout ?

**Comment by Arias800** [comment]
On peux appeler ça un cache misère quoi x)
