### ISSUE TITLE
Zone Telechargement - Dédupliquer

### ISSUE THREAD

**Issue by celogeek** [Kodi-vStream/venom-xbmc-addons#1580]
L'affichage des series et des films sur ce site génère des doublons

On voit plusieurs fois le même film ou la même saison d'une série apparaître.

Ensuite pour les séries il redemande la qualité requise (même écran quelque soit le choix effectué)

Pour les films c'est la même chose, on choisi la qualité

Si 4 versions existes, on a 4 fois le film, puis les 4 qualités à choisir.

Pourriez vous fixer ce problème ?

**Comment by Arias800** [comment]
Effectivement c'est un peux bizarre ^^

**Comment by TmpName** [comment]
Ca vient du site, fait une recherche sur leur site, tu vas avoir des doublons aussi.

**Comment by celogeek** [comment]
Du coup vu le fonctionnement du plugin, on pourrait pas dédoublonner à la volé ?

Si on voit plusieurs fois le meme titre, on prend le premier (celui ci affiche la saison la plus avancée sur zone-telechargement)

**Comment by TmpName** [comment]
Lol, decidement, 3 eme issues ou je te vois et pr les memes raisons ^^.
Oui c'est possible mais si tu regarde bien sur leur site, pour le meme titre, tu n'as pas forcement la meme chose, (qualitee differente, langues, ....) et tu ne peux le savoir que en cliquant dessus (meme si en regardant l'url ca se devine)

**Comment by Arias800** [comment]
de toute façon zt ws est une contrefaçon du vrai pas étonnant qu'il soit bugge ^^

**Comment by alex83100** [comment]
Bonjour, je profite de ce poste pour demander pourquoi il n'est pas possible de voir game of thrones à partir de zone de téléchargement depuis Vstream et uniquement GOT.

**Comment by Arias800** [comment]
C'est possible avec un navigateur normal ?

**Comment by alex83100** [comment]
oui, en passant directement par le site aucun problème

**Comment by Arias800** [comment]
Je vient d'essayer j'ai pu lancer un episode de la saison 7 sans probleme ^^

**Comment by alex83100** [comment]
ci joint mes copies d'écran https://www.amazon.com/clouddrive/share/cKlBehoufB7bRiu7zR598UkM1kzGxMXpQRamglO11v3

**Comment by alex83100** [comment]
étrange uniquement en passant par Series VF derniers ajouts en faisant une recherche ok

**Comment by Arias800** [comment]
Oui parce que ce lien la est bugge et c'est le dernier ^^

**Comment by alex83100** [comment]
Ok merci
