### ISSUE TITLE
Lien hoster (ex uptobox) - réduire les étapes finales

### ISSUE THREAD

**Issue by celogeek** [Kodi-vStream/venom-xbmc-addons#1581]
Lorsqu'on choisi un film ou une série on a le lien uptobox par exemple qui est disponible.

Une fois ce lien choisi il remet le meme lien mais cette fois tout seul.

Une fois choisi on a enfin le choix entre stream ou direct (pour uptobox).

Est ce qu'on pourrait pas supprimer l'étape en trop qui est de rafficher le lien tout seul et directement passer à la lecture ou le choix du format ?

Si c'est possible de mettre une option pour ce choix du genre: 
  * choisir le format
  * direct
  * stream (360, 480, ... 1080, meilleur qualité disponible)

Merci

**Comment by Arias800** [comment]
Alors de mon point de vue de débutant non vu que l'on suit les étape du site pour raccourcir il faut que les site raccourcisse déjà de leurs cote hors nous on a aucun contrôle la dessus

**Comment by LordVenom** [comment]
Faut ce plonger dans le code, c'est pas si simple ça nous permet des fois d'allais chercher une info sur une api, de contourner un javascript,, de supprimer des pubs, pour vous ceux qui et un lien chiant est la plupart du temps des heures de travail pour contourner des systems à la C..

**Comment by TmpName** [comment]
En general non, comme l'ont dit les autres, il y a une raison, en general c'est que l'url est code, donc elle se decode au second clic, si on veut supprimer cette etape faudrait decoder tout les liens et les afficher deja decode.
Meme avec la fibre, avec le temps de reponse des serveurs, ou les temporisation force des decodeur, tu iras plus vite en passant par 3 etapes qui kodi en une seule.

**Comment by celogeek** [comment]
On pourrait afficher le lien crypté, puis lorsqu'on le choisir on le décrypte et le lance dans la foulé.

Cela evite l'étape d'afficher le lien décrypté puis de lancer le lien. On peut décrypté et lancer dans la meme foulée.

**Comment by Arias800** [comment]
Comme TmpName a dit c'est beaucoup plus long ^^

**Comment by TmpName** [comment]
C'est ce qui est fait.
1 er page >> La liste des liens en vracs, non decode (Vstream ne sais meme pas a quel site correspondent les utl)
2 eme page >> Vstream decode le lien, mais ne peut pas encore le lancer car ce n'est pas le meme type de page, en fait la derniere page, celle avec les liens qui se lancent, n'est pas du meme type que la precedente. Donc il affiche le meme hoster mais cette fois avec la bne url.

La page 1 est comme un repertoire.
La page 2 comme un executable.

Si tu fais un clic droit (ou contextuel) tu n'auras pas les memes options.

Je reconnais que sur certains sites il y a moyen de reduire, mais c'est tres rare, il y en a qui ne supportaient pas ca, et qui sont deja passe par la.
