### ISSUE TITLE
TMDB Lists

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1583]
Le soucis de la recherche visuelle c'est quelle et limiter face à toute les sources dispo sur vstream.
soucis régler avec vos Lists :  

Creer un compte https://www.themoviedb.org/
Creer une list public et proposer la nous.

Point négatif c'est pas par ce que votre film ce trouve dans la liste que vStream vas forcement le trouver ça lanceras uniquement une recherche global avec le titre.

Point positif pas mal pour avoir des idées et enfin des lists anime, manga dans la recherche visuelle.

![image](https://user-images.githubusercontent.com/4380112/29387848-5038a560-82e2-11e7-89c0-1ed4c927b33e.png)

![image](https://user-images.githubusercontent.com/4380112/29387865-6be7636e-82e2-11e7-8544-445072b17297.png)

**Comment by Arias800** [comment]
Pas mal comme idée ^^
