### ISSUE TITLE
Kaydo

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1584]
Plus possible d’accéder au choix des episode pour les serie erreur : timeout: timed out

**Comment by TmpName** [comment]
Essayes en remplacant par
URL_MAIN = 'http://www.hd-stream.net/'

et faut virer tout les 
    # modif url par Gregwar  
    #if '?' in sUrl:
    #    sUrl += '&r=n'
    #else:
    #    sUrl += '?r=n'

car ca ne marche que pr kaydo (et pas hd-strm)

**Comment by Arias800** [comment]
A savoir que ca ne le fait pas tout le temps peut etre que les serveur etait surcharger a ce moment la je garde l'issue ouvert a cas ou ca recommence

**Comment by TmpName** [comment]
Yep, j'ai pense pareil, on peut adapter le code pr etre compatible avec les 2 urls, style
```
if hdstrm' in URL_MAIN:
# modif url par Gregwar
if '?' in sUrl:
 sUrl += '&r=n'
else:
 sUrl += '?r=n'
```

Mais comme dans tout les cas on est oblige de changer URL_MAIN et que il n'y a aucune garantie que le reste fonctionne sans modif ....

**Comment by Arias800** [comment]
Non mais je pense que c'etait passager je ferme et je reouvre si ca recommence^^
