### ISSUE TITLE
1fichier.com

### ISSUE THREAD

**Issue by bellad17** [Kodi-vStream/venom-xbmc-addons#1585]
Bonjour et merci pour le travail
j'essais d'avoir mes fichiers de 1fichier , mais rien n'apparait
j'ai cocher et mis mes indentifiants à la case 1fichier
ensuite où je dois voir mes fichiers ?
dans autre sources je n'ai rien ( à part l'inscription à uptobox
ai je pas tout fait comme il faut ?
merci

**Comment by TmpName** [comment]
Quand une source te propose des fichier sur 1fichier, tu as un message d'erreur ?

**Comment by bellad17** [comment]
dans ' autre sources' ou ailleurs , je n'ai pas de dossier "1fichier"

**Comment by Arias800** [comment]
Normale c'est juste un hoster on n'a pas de fichier site pour 1fichier

**Comment by bellad17** [comment]
désolé mais je ne comprends pas !!
 , j'ai des fichiers chez "1fichier" 
 à quoi sert la coche "1fichier" avec log et pass dans vstream ?
merci

**Comment by Arias800** [comment]
Il me semble que vstream utilise 1fichier comme lecteur de video pas comme site de stokage donc il me semble que ce n'est pas possible de lire vos propre fichier en passant par 1fichier

**Comment by LordVenom** [comment]
L'identifiant et utile uniquement pour autoriser la lecture des liens proposer en mode premium il n'y pas de navigateur de vos propre fichier. Cette fonction est uniquement disponible pour Uptobox il me semble.

**Comment by bellad17** [comment]
ah ok , je comprends mieux , 
comment ou où met on les liens , je pense du style " https://1fichier.com/?yyn49plxxxx" dans vstream ?

**Comment by LordVenom** [comment]
Tu peux pas, seul les liens proposer en Host sont décoder par vStream.

**Comment by bellad17** [comment]
tu peux me donner un exemple
merci

**Comment by LordVenom** [comment]
Heu.. non j'ai jamais regarder le code voir plugin.video.vstream/sites/siteuptobox.py

**Comment by bellad17** [comment]
ok, je vais faire autrement , je crée une playlist mu3 et indique sur 1fichier que tous les fichiers que je veux visionner sous kodi soit en 'hotlink' , j'ai droits , en premium , à 100g/mois
merci quand meme
