### ISSUE TITLE
Plantage de Kodi dans Vstream

### ISSUE THREAD

**Issue by Lemania** [Kodi-vStream/venom-xbmc-addons#1586]
Bonjour,

J'ai une installation fraiche de Mint 18.2, un kodi 17.3 et un Vstream 0.5.3 installé via le zip du repo.

Je ne peux rien faire du tout, des que j'accede à la liste de film ou de serie, kodi se coupe.

Avez vous une version de Kodi à recommander ? 

Avez vous une distribution linux (+version) à recommander ?

Merci

**Comment by LordVenom** [comment]
Bonjour, Il dit quoi le log de Kodi ?
