### ISSUE TITLE
Problème sous-titre

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1587]
Bonjour,
Je ne sais pas si vous avez le même problème que moi et je ne suis même pas sûr que le pb vienne de Vstream mais je n'arrive plus à trouver de sous-titre avec Open Subititles.

**Comment by LordVenom** [comment]
Pas de soucis chez moi.
![image](https://user-images.githubusercontent.com/4380112/29565552-b43524ea-8746-11e7-8673-974c36f62d99.png)

Note : Promis j' arrête de faire des Screenshots tout le temp :+1:

**Comment by Arias800** [comment]
Chez moi non plus pas de problème ^^
Note : Je ne savais que tu est screenshotophile x)

**Comment by canopre** [comment]
Je reviens vers vous car ça fait maintenant des mois que j'ai pas pus télécharger un sous-titre avec Vstream. (sous-titre introuvable).

Et je viens de refaire un test avec un film US et l'addon covenant : les sous-titres sont disponibles presque immédiatement.

Y'a peut-être bien un petit bug là ?

**Comment by Arias800** [comment]
Va sur un lien ou tu a les sous titre et regarde dans les option des sous titre pour voir si il se terminent par .vtt

**Comment by canopre** [comment]
Désolé mais VStream ne trouve AUCUN sous-titre alors je peux pas "aller sur un lien"...

**Comment by TmpName** [comment]
Ca doit dependre des sources, Open Subititles fait par rapport au titre du film, si il y a des mots "parasites" ca peut faire deconner la recherche.
Mais normalement Vstream prend les sous titres integres a la page html (via uptostrm), donc il n'y a pas a passer par Open Subititles, ou alors c'est que cela deconne encore.
