### ISSUE TITLE
Recherche à choix multiple

### ISSUE THREAD

**Issue by mmtest1** [Kodi-vStream/venom-xbmc-addons#1594]
bonjour,
depuis la dernière mise à jour de Vstream la recherche à choix multiple a disparu, est-ce que la disparition de cette fonction est volontaire ? J'ai nettoyé le cache de kodi et fais un refresh du skin mais toujours non disponible. Dans mon historique de recherche lorsque je relance une titre de recherche précèdement selectionné en recherche à choix multiple un popup me propose de choisir les sites. Est-il possible de retrouver cette fonction ? je trouve que la recherche à choix multiple est plus souple à utiliser que choisir les sites de recherche en fonction de la categorie (ce que j'ai dejà fait d'ailleurs).
merci

**Comment by LordVenom** [comment]
Oui c'est volontaire pas asser utiliser.

**Comment by mmtest1** [comment]
Merci pour la réponse, la fonction était utile pour chercher en fonction des heures sur les différentes sources notamment sur un rpi b+ qui manque de ram sans avoir à consulter l'ensemble des sources de la catégorie, je vais peaufiner le choix des sources en fonction des catégories
Merci et bonne soirée
