### ISSUE TITLE
Sokrostream

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1595]
J'ai un beug bizarre avec sokrostream. Sur mon smartphones et sur ma boxtv le site ne fonctionne pas et sur mon pc tout est ok... pourtant j'ai vérifié j'ai bien la dernière version du fichier installé sur mon pc et sur ma boxtv... suis je le seul???

**Comment by TmpName** [comment]
Aucun prb sur PC de mon cote aussi.

**Comment by razorex** [comment]
Et sur un autre système??

**Comment by razorex** [comment]
bon je viens de faire une nouvelle mise à jour et ces revenus, je précise que ce n'est pas la première.
