### ISSUE TITLE
Cacher les fenetres de progression de recherche

### ISSUE THREAD

**Issue by fredsundy** [Kodi-vStream/venom-xbmc-addons#1596]
Bonjour, j'ai customisé un skin (Titan) afin d'avoir une interface un peu du type Netflix mais sur la base de différentes sources de stream. Mon problème est que régulièrement les recherches sont relancées et j'ai un gros bandeau m'empêchant de naviguer le temps que les 10 sources soient rechargées... Bref long t rebutant..., Afin d'éviter ce désagrément il faudrait pouvoir cacher la boîte de dialogue. Est possible d'avoir les informations dans le header'comme pour la mise à jour des bibliothèques plutôt qu'une boîte de dialogue ? Ou alors est il possible de les désactivées ? Merci d'avance. L'autre moyen serait d'éviter que le script se relance mais je n'ai pas trouvé le trigger car la mise à jour est plutôt aléatoire.

**Comment by TmpName** [comment]
Ben elles ont une utilitéé (bon ok ca marche rarement car kodi freeze, mais ca c'est pas notre faute), c'est de pouvoir tout stoper si c'est trop long en appuyant sur le boutton cancel.

**Comment by fredsundy** [comment]
Je suis bien bien d'accord surla fonction et le besoin pour la grande majorité des utilisatuers. Y'aurait il une possible de les cacher par la modification d'un xml ou autre petite modif a apporter localement ?
Ca doit etre possible ? car par example un add on comme genesis se met a jour sans afficher les recherches.
Merci d'avance

**Comment by LordVenom** [comment]
Si tu parle d'une recherche global la popup et générer dans default.py

`dialog = cConfig().createDialog("vStream")`

`cConfig().updateDialogSearch(dialog, total, text)`

`cConfig().finishDialog(dialog)`

Si c'est la recherche d'un site c'est directement dans le code du sites.

**Comment by fredsundy** [comment]
Merci ! je vais tester ca
