### ISSUE TITLE
Flashx erreurs / introuvable

### ISSUE THREAD

**Issue by Nux007** [Kodi-vStream/venom-xbmc-addons#1599]
J'ai systématiquement des vidéos illisibles en passant par flashx
exemple sur Documentaires -> tv - streaming -> ...
Presque tous les fichiers ne se lancent pas.

**Comment by TmpName** [comment]
Regardes sur un navigateur si le lien n'est pas mort. Je viens de tester un truc au pif chez moi, c'est passe.
