### ISSUE TITLE
affichage uptobox2 (Bientot del)

### ISSUE THREAD

**Issue by diouf76** [Kodi-vStream/venom-xbmc-addons#1602]
bonjour,

J'ai remarqué que depuis la version 0.52 voir 0.51 ainsi que la dernière 0.53 que l affichage fanart des séries ne correspondait pas toujours a l intitulé.

J'ai pu tester avec une version 0.49 et là aucun soucis.

Je précise que c'est avec uptobox2.py ( john).

Merci par avance de votre aide.

**Comment by sebi0606** [comment]
Et toujours pas de next page dans votre compte uptobox

**Comment by LordVenom** [comment]
Heu j’hésite entre regarder et virer la fonction.

**Comment by diouf76** [comment]
Trop long à régler ? Ou suite au commentaire précédent ?

**Comment by LordVenom** [comment]
Pff faut que je face un compte que je créer les liens que je teste. Ca vas me prendre une plombe pour un truc que j'utilise pas j'ai la flême.

**Comment by diouf76** [comment]
Oui je comprends, sinon tu veux que je te donne mes accès pour tester ?

**Comment by LordVenom** [comment]
Non c'est personnel ce genre de chose.

**Comment by diouf76** [comment]
Ou est ce possible de modifier le fanart en y mettant une image en local ?
