### ISSUE TITLE
Zone telechargement ws aucun lien fonctionne 

### ISSUE THREAD

**Issue by akatimike** [Kodi-vStream/venom-xbmc-addons#1603]
Salut! Suis je le seule qui a le problème avec zone telechargement.. aucun lien ne fonctionne toujours des .. (deux petit point)

**Comment by Arias800** [comment]
Chez moi ca fontionne ^^

**Comment by sebi0606** [comment]
Chez moi pas quand je fais une recherche on arrive à la deuxième étape uptobox et quand on clique plus rien

**Comment by Arias800** [comment]
Effectivement je regarde ca ^^

**Comment by itchy13** [comment]
Idem j'ai le même souci que l'auteur aucun lien ne fonctionne. aussi bien sur mon android box que sur mon raspberry 3

**Comment by Arias800** [comment]
Oui ca vient de dll protect il ont du faire une modif :/

**Comment by TmpName** [comment]
Vous l'avez ou le message d'erreur, moi c'est juste que je n'ai pas le lien.
J'ai commence la https://pastebin.com/Ngz7CkAw
Mais ca marche tjours pas.

**Comment by TmpName** [comment]
Ok c'est au niveau des hhtp / https
Ce code a fonctionne https://pastebin.com/ik756vze

Mais faut garder que ce qui est utile ^^, y a plein de debug dedans.

**Comment by luluvulcain** [comment]
Oui les Liens sur Zone Telechargement ne fonctionne plus et pour régler le soucis, il suffit de chercher ce que vous voulez regarder sur les autres sources en attendant que le problème soit régler.

**Comment by chataigne73** [comment]
correction effectuée à partir des modifs de TmpName

**Comment by raza974** [comment]
Bonjour,
Je confirme que j'ai le même problème aussi bien en utilisant Vstrem/Kodi sur ma box Android TV que sur mon téléphone , plus aucun lien en passant par Z.T, seulement trois points de suspension. C'est dommage car je trouve qu'il y a vraiment du choix avec cette Source sur Vstream.
En espérant qu'une solution soit vite trouvée 😁

**Comment by LordVenom** [comment]
Hum... voir le post de @TmpName et @chataigne73

**Comment by raza974** [comment]
Je suis vraiment novice dans l'utilisation de Kodi ainsi que dans celle de Vstream, pourriez vous m'expliquer svp comment faire pour utiliser le code posté ci dessus par @TmpName .
Merci d'avance pour votre aide😀

**Comment by Alaliam** [comment]
Bonjour, je me suis inscrit récemment suite au soucis relaté ci-dessus...je pense qu'il n'y a pas que Zone télé .ws qui soit concerné, on dirait que le problème est avec tout ce qui concerne "1 fichier", "uptobox", "uploaded"...

**Comment by Arias800** [comment]
Ah bon ? Je regarde ça ^^

**Comment by akatimike** [comment]
Un gros merci à vous tous pour le support c'est apercier :)

**Comment by luluvulcain** [comment]
Il est marquer que le Problème est Résolu mais chez moi ça ne marche pas. J'ai aucun lien en passant par Zone Telechargement, seulement deux points de suspension.

**Comment by Arias800** [comment]
Tu as bien mit le nouveau fichier ? https://github.com/Kodi-vStream/venom-xbmc-addons/blob/7d11d96d49c42c0f2d936c248f52ca44284df98f/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by luluvulcain** [comment]
Merci Arias800, je viens de mettre le nouveau fichier et ca marche. Merci Beaucoup pour le Support et l'Aide.

**Comment by Arias800** [comment]
De rien vu que j'ai peux de connaissance en programmation j'aide comme je le peux ^^

**Comment by raza974** [comment]
Pouvez-vous m'indiquer comment faire pour mettre le nouveau fichier svp car je suis novice 😁
Merci

**Comment by Arias800** [comment]
Sur quel plateforme ou quels os ?

**Comment by raza974** [comment]
J'ai Kodi/vstream installé sur une box Android TV ainsi que sur mon téléphone qui est aussi sous Android

**Comment by Arias800** [comment]
Je t'ai repondu juste au dessus ^^

**Comment by raza974** [comment]
Merci beaucoup c'est très gentil 😁

**Comment by Arias800** [comment]
De rien ^^

**Comment by bidous13** [comment]
ça fonctionne à merveille merci

**Comment by raza974** [comment]
J'ai installé le nouveau fichier cité précédemment mais maintenant lorsque que j'essaye de charger un lien des différents hoster, cela charge mais plus rien ne s'affiche, même plus la page où précédemment il y avait les trois petits points de suspension.
Quelqu'un aurait il une idée ?
Vraiment désolé pour le dérangement 😀😶

**Comment by Alaliam** [comment]
Même avec le wiki, pas évident surtout quand on n'a pas l'habitude...est-ce que tout rentrera dans l'ordre lors d'une prochaine mise à jour?...car dans ce cas, je préfère attendre...merci

**Comment by raza974** [comment]
Y-aurait-il une âme charitable svp afin de pouvoir m'aider 😁 car je pense que j'ai dû faire une mauvaise manipulation au moment de l'installation du nouveau fichier.

**Comment by akatimike** [comment]
Je vais faire là modif et poster le fichier zip tantôt :)

**Comment by akatimike** [comment]
http://www28.zippyshare.com/v/erQEKI6n/file.html
Voila tu n'a qu'à faire la mise à jour manuellement -> addon -> addon browser -> installer from zip file -> et tu choisi le fichier que tu a telecharger ( http://www28.zippyshare.com/v/erQEKI6n/file.html
)

**Comment by raza974** [comment]
Merci beaucoup pour le coup de main c'est très gentil 😁

**Comment by akatimike** [comment]
Fait plaisir :)

**Comment by Alaliam** [comment]
Impec pour moi aussi finalement...un grand merci pour la méthode et je rejoins le commentaire de Raza ci dessus ;)

**Comment by reds07** [comment]
Bonjour à tous,

Je n'avais également plus aucun liens sur Zone téléchargement et d'autres, j'ai donc appliquer le Zip de akatimike, et depuis a chaque fois que j'essaye de lancer un liens j'ai l'annonce ,"Erreur Site Dl Protect HS".

Quelqu'un pour m'aider.

**Comment by Arias800** [comment]
Normalement quand ce messaga apparait c'est que vstream ne peux pas ce connecter a dl protect
Essaye de lancer le film "quiz show" depuis la categories film (dernier ajout)

**Comment by K3R0ZEN** [comment]
Idem que mon ami du dessus.  J'ai le droit a "site DL protect HS" sur n'importe quel films

**Comment by Arias800** [comment]
Essaye de lancer le film "quiz show" depuis la categories film (dernier ajout) et dit moi si ca marche

**Comment by K3R0ZEN** [comment]
Non je viens d'essayer et cela ne fonctionne pas Arias.

**Comment by Arias800** [comment]
Donc le zip a un problème donc remets le zip officiel https://github.com/Kodi-vStream/venom-xbmc-addons/releases/

**Comment by K3R0ZEN** [comment]
Et maintenant avec le zip d'origine je n'ai plus aucun lien proposer, retour au souci initial donc ...

**Comment by Arias800** [comment]
Bizzarre bon je vais jette un oeil a dl protect ^^

**Comment by Arias800** [comment]
Pendans ce temps remets la version modifier reteste et passe les log ^^

**Comment by K3R0ZEN** [comment]
Je sais pas comment t'envoyer les log parce que je ne sais même pas ou aller les chercher mon ami :s

**Comment by Arias800** [comment]
Upload Kodi log : Upload automatiquement votre log sur Slexy vous pouvez par la suite simplement nous transmettre l'ID vous étant donner en popup. Votre log http://slexy.org/view/+ votre ID ca se trouve dans les parametre de vstream dans l'onglet outils

**Comment by K3R0ZEN** [comment]
Quand je valide , upload kodi.log j'ai aucun popup qui s'affiche ...

**Comment by Arias800** [comment]
ah bizzarre la malheureusement je peux pas t'aider car ca touche au coeur de vstream et je connais peux le fonctionnement faut attendre @LordVenom ou @TmpName

**Comment by K3R0ZEN** [comment]
Pas grave, merci pour ton aide Arias ;)

**Comment by TmpName** [comment]
Desinstaller Vstream, et reinstaller via le repo.

Je rappelle que lorsque vous installez une nouvelle version (sauf si elle date de 2 jours bien sur), il peut falloir jusqu'a 3 jours pour avoir les bons fichiers, car les fichier du zip ne sont jamais les derniers.

Infos pr trouver le fichier log http://kodi.wiki/view/Log_file/Advanced#Log_files
Ne pas copier le log sur le github, mais passer par un site d'hebergement de texte comme pastebin ou slexy.

**Comment by akatimike** [comment]
Tester maintenant et tout fonctionne chez moi

**Comment by LordVenom** [comment]
Merci @akatimike pour le don , ça fait toujours plaisir  :+1:

**Comment by akatimike** [comment]
De rien 😀😀😆

**Comment by reds07** [comment]
Bon bah je suis perdu, j'ai désinstaller vstream, réinstaller depuis le repo, mais toujours cette erreur site de protect hs.je ne sais plus rien voir.

**Comment by TmpName** [comment]
Si dans 3 jours tu n'as pas la MAJ propose, il nous faudra le log.

**Comment by karim505** [comment]
Bonjour à tous,
J'ai eu une mise a jour disponible hier je l'ai effectué mais depuis maintenant 5 jours zone telechargement ne marche plus 
J'ai lu plus haut qu'il y avait un fichier zip modifié , je peux l'installer ?
Cela me met depuis la mise a jour " erreur sit protect hs "
Merci d'avance

**Comment by doubidave** [comment]
Je ne sais pas si cela peut aider, mais j ai remarqué que selon la version de Kodi, les liens zone telechargement apparaissent ou non. Par exemple, j ai 2 raspberry différent: un sous kodi 16 et l autre 17. Eh bien les liens apparaissent sur le 17 mais pas sur le 16. La j ai les 2 petits points. 
J ai testé avec la saison 4 de Halt and catch fire. Si ca peut en aider certains...

**Comment by Arias800** [comment]
Ça vient peut être du ssl (je sais pas si c'est ca le nom) c'est quelque chose qui peux être sur le site et qui est supporté uniquement par kodi 17 ca explique pourquoi vstream ne peux pas ce connecté car chez moi (kodi 17) pas de probleme

**Comment by doubidave** [comment]
Ou alors la maj s est faite sur un et pas sur l autre. C est une possibilité dans mon cas.

**Comment by karim505** [comment]
Je vais essayer kodi 17 en rentrant 
Mais sinon je peux mettre le fichier partage sur une autre discussion ou c'est le même que la mise à jour de hier ?
ZT qui ne fonctionne pas et je me sens tout nu Mdr
En tout cas addons magnifique je passe mes soirées dessus et je l'ai installé chez tous mes amis et famille
Merci pour tout

**Comment by reds07** [comment]
Si Avec Kodi 17 Sa passe, pourrait tu nous en tenir informer... est ce difficile de passer sur kodi 17 ?

**Comment by reds07** [comment]
et surtout est ce mieux que Kodi 16

**Comment by Arias800** [comment]
Difficile de passe a kodi 17 oui et non car dans la base ce ne change pas radicalement c'est le thème de base qui est un bazarde sans non

**Comment by Alaliam** [comment]
Pour migrer sur Kodi 17: aller sur le play store, chercher Kodi17.3, installer...Sans désinstaller l'ancienne version
Par contre, il est possible que cela ne fonctionne pas car sur certaines tv box, le kodi préinstallé n'est pas reconnu dans le play store...dans ce cas, désinstaller le "Kodi" d'origine et réinstaller le nouveau proposé dans le play store

**Comment by psykotropz** [comment]
Pour ceux qui comme moi galèrent avec la mise à jour, pensez à faire un nettoyage des fichiers!

Source : https://www.seeyar.fr/plugin-kodi-vstream-mettre-a-jour-liens-streaming/

**Comment by LordVenom** [comment]
Hum 2/Mise à jour des liens morts aucun rapport avec les mises a jour.
