### ISSUE TITLE
Site (pense bete)

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1604]
libertyland_tv : Beaucoup de modif suite au changement d’équipe
streamay : modification de la fonction de recherche (ne marche pas pour les serie)
kaydo : pas tres stable actuellement

**Comment by TmpName** [comment]
Pr strmwy, c'est deja corrigé ? Chez moi pas vu de prbs ?

**Comment by chataigne73** [comment]
Salut.
Streamase est down depuis un moment et ne reviendra pas --> à supprimer

**Comment by TmpName** [comment]
Ha wé, mince, il etait pas mal ce site.
