### ISSUE TITLE
Solutions aux Problemes Techniques !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1608]
Vu le Problème de "Zone telechargement ws aucun lien fonctionne", je propose d'inclure le nouveau fichier directement dans le fichier zip du plugin en l'intitulant "plugin.video.vstream-0.5.3.modified" et le mettre en téléchargement sur le site en créant une nouvelle Rubrique intitulé "Versions Modifiées". Ça serais pas mal le temps que la mise à jour public automatique soit faite.

**Comment by Arias800** [comment]
La mise a jour va arriver dans maxi 3 jour pour les site et puis il existe d'autre site de ce type donc a mon avis ca va etre non ^^

**Comment by luluvulcain** [comment]
Peut être oui Arias800 mais je le propose quand mème car ça peut être bien pour dépanner et pour les gens qui n'y connais pas en programmation et informatique.

**Comment by Arias800** [comment]
Oui et a aucun moment je dit que c'est une mauvaise idée c'est juste que l’utilité est relative ^^

**Comment by LordVenom** [comment]
Non faire le zip, rapatrier les modifs vérifier le setting ça prend 1 jour a lui tous seul et c'est chiant 1 fois par mois grand max.

**Comment by akatimike** [comment]
http://www28.zippyshare.com/v/erQEKI6n/file.html

**Comment by LordVenom** [comment]
Non mais y a une mise a jour automatique tous les 3 jours, un peux de patience juste.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour

**Comment by johnboisvert** [comment]
Lordvenom ca fais 8 jour je n'est pas eu de mise a jour et l'option mise a jour en vers n'est pas la  jai encore le probleme des série télé quand ont clique ca fais rien

**Comment by TmpName** [comment]
8 jours c'est pas normal, faudrait un log.

**Comment by michellemikor84** [comment]
Bonjour à tous et toutes,
Je suis nouvelle sur le site et je vous dis un grand merci.
Il n'y a qu'ici que j'ai trouvé la solution pour mon problème sur Zone téléchargement.
J'ai fait la mise à jour et tout fonctionne, génial.
Un tout grand merci.
A bientôt.

**Comment by michellemikor84** [comment]
Bonjour,
Je voudrais signaler une anomalie sur zone-téléchargement.
Quand on sélectionne une série saison 5, on arrive sur la saison 5 et on nous donne les autres saisons disponibles. Mais quand on sélectionne une autre saison disponible ex : saison 3 et bien il ne se passe rien chez moi.
Pourriez-vous me dire si cela est normal ?
D'avance un tout grand merci.

**Comment by TmpName** [comment]
Y a effectivement un prb dessus.
Chez moi, il ya de nouveaux liens qui apparaissent, les bons, mais ca ne chnage pas le numero de la saison.
En fait ca affiche toute les saisons avec le premier numero de saisons affiche. Ca utilise le nom contenu dans la variable.
