### ISSUE TITLE
Lenteur affichage sections

### ISSUE THREAD

**Issue by zoidav67** [Kodi-vStream/venom-xbmc-addons#1610]
Bonjour à tous.
Cela fait un bout de temps depuis la 5.3que j'ai des lenteurs phénoménales à la navigation dans les menus de Vstream.
P.e : Si je veux afficher les derniers films, je clique et la liste mets une plombe à s'afficher puis si je sélectionne un film c'est sa liste de liens qui mets encore une fois un éternité (plus d'une min) à s'afficher.
Par contre le film lui une fois lancé tourne nickel.
Auriez vous des réponses une piste ?

**Comment by Arias800** [comment]
Il me semble que la 5.3 a (avais)des problème de lenteur mais je sais pas si ça a été régler par @LordVenom

**Comment by TmpName** [comment]
Regarde si sur navigateur le meme site, le meme film, au meme moment, tu as les memes problemes.
Ca peut venir du regex trop lourd pr ta machine (mais ca ne le ferait qu'a certains sites)

**Comment by LordVenom** [comment]
- Désactiver certain site voir si ça change quelque chose

- Retourne sur le theme de base.

- Désactiver la recuperation des metas.

**Comment by zoidav67** [comment]
Faut il être bête c'est un problème réseau de chez moi. J'ai deux box free branchées au même réseau et la box Android TV devait jongler entre les deux réseaux d'où la lenteur voir l'échec ....depuis réseau est bien séparé et ras merci qd même à tous. Merci de clore le sujet 😀
