### ISSUE TITLE
Type de vue non personnalisable

### ISSUE THREAD

**Issue by nabsboss** [Kodi-vStream/venom-xbmc-addons#1612]
Bonjour et merci bcp pour cet add-on ;)

Depuis 2 mises à jours, la vue par défaut est "Mur".  Quand je change sur " Liste", ça ne le fait que sur la page courante car quand je clique sur la page suivante, ça revient sur "Mur".
Quand je relance vstream, tout redevient sur " Mur".
J'ai essayé "activer vue personnalisée" dans les options mais celà n'a aucun effet :(
Comment personnaliser la vue dans ce cas, merci !

**Comment by Arias800** [comment]
Il me semble (a confirmé) que dans certaine partit de vstream le type de vue est forcé

**Comment by TmpName** [comment]
A quel endroit ? la recherche visuelle est forcee, le reste n'a pas chnage normallement.

**Comment by nabsboss** [comment]
Oui dans recherche visuelle. Je me sers de la vue Liste car on a le titre la jaquette, le synopsys et surtout la date complète de la sortie. Pourquoi avoir forcé la vue dans ce menu ?

**Comment by TmpName** [comment]
Ben parce que le but de cette section, c'est le cote visuel, et quoi de plus visuel que les affiches ?
C'est un mode d'affichage qui est proscris des autres methodes, alors que beacoup de devs ont voulus utliser ce mode pour leur source. C'est le seul endroit de Vstream ou ce mode est utilise.

**Comment by nabsboss** [comment]
Peut-être mais ce ne serait pas mieux de laisser le choix aux utilisateurs. Pour moi, le meilleur visuelle est "liste" contrairement à mur ! Quand j'utilise la recherche visuelle pour les séries, c'est imbuvable avec les jackettes. Serait-il possible de nous redonner cette liberté ?

**Comment by nabsboss** [comment]
Si vous ne souhaitez pas faire la modification, pouvez-vous me dire où se trouve l'info dans le code que je le fasse moi même ?

**Comment by nabsboss** [comment]
C'est bon j'ai trouvé ! Merci encore pour tout le taf mais franchement ce n'est pas cool d'imposer de force une vue. Dommage pour ceux qui ne savent pas modifier un code !!

**Comment by TmpName** [comment]
C'est pas le mode de vue qu'on impose, c'est la fonction.
Recherche visuelle > Impact visuel
Si tu preferes le mode liste, tu peux activer les metas datas et passer par n'importe quelle lautre fonction, tu auras le resultat que tu preferes (enfin en theorie, me sert pas des metadata donc pas teste)

**Comment by mifrey00** [comment]
J'avais le meme probleme pour toutes les listes de films.  J'ai le skin Aeon Nox et je voulais que la vue par defaut soit VideoLowList.

J'ai resolu le probleme en editant le fichier /home/osmc/.kodi/addons/skin.aeon.nox.5/1080i/MyVideoNav.xml en mettant l'ID de la vue (501) en  premiere position <views>501,50,51,52,53,55,56,57,58,59,500,502,503,510</views>.

Je ne sais pas si marche pour la recherche visuelle mais ca marche pour le reste.

**Comment by LordVenom** [comment]
La vue peux être force pour les catégorie films, série, sauf pour la recherche visuelle.

@nabsboss : 50/50 Avec ou sans ont n'a des retours donc malheureusement ceux qui savent ce servir d'un paramétrage "option activer les vues perso" paye pour ceux qui ne savent pas.

**Comment by LordVenom** [comment]
Résolut toujours forcer mais modifiable dans les options , Disponible dans la prochaine mise à jour mensuel.

**Comment by nabsboss** [comment]
Cool merci beaucoup ;) Encore bravo pour tout le taf que vous faites, ça mérite bien une petite donation que je ne manquerai pas de faire le mois prochain ;)
