### ISSUE TITLE
Coco_stream

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1613]
Dans coco_stream (dossier site en cours) on ne récupère qu'un seul Host les openload et pas les Netu. QQ à une solution. est-ce du au liens "ttps://goo.gl/bCykDi" pour Netu.

@Arias800 j'ai épuré ton fichier. Une fois que l'on aura corriger ce dernier pb. tu pourra le proposer (on le renommera en coco_stream avant). A l'avenir si tu peux ouvrir une issue quand tu propose un site ce sera plus facile pour t'expliquer les différents pb et place ton fichier sur ton Git.

**Comment by Arias800** [comment]
D accord je m occupe de netu des que je rentre

**Comment by razorex** [comment]
Je pense que c'est du côté hoster

**Comment by TmpName** [comment]
Pour les liens goo.gl, si pas deja fait

```
            if 'http://goo.gl' in sHosterUrl:
                try:
                    headers = {'User-Agent' : 'Mozilla 5.10','Host' : 'goo.gl', 'Connection' : 'keep-alive'}
                    request = urllib2.Request(sHosterUrl,None,headers)
                    reponse = urllib2.urlopen(request)
                    sHosterUrl = reponse.geturl()
                except:
                    pass
```

**Comment by Arias800** [comment]
Dans le code en lui même je fait retirer le HTTPS

**Comment by razorex** [comment]
@TmpName je l'ai écris comme çà [url](https://pastebin.com/vDCXPS6J) mais pas de fonctionnement. et pour le https on fait un replace????????

**Comment by TmpName** [comment]
Tu aurais pas plutot le dernier code complet stp ?
Sinon moi je laisserais tel quel, si c'est https, je laisserais https.

**Comment by razorex** [comment]
le dernier code c'est celui qui est dans le dossier site "en cours". Sans ta correction.

**Comment by TmpName** [comment]
Essayes avec ca
https://pastebin.com/RvUPdZF5

**Comment by Arias800** [comment]
J'ai teste alors ça trouve un lien qui retourne 404  si on attends alors que le lien n'ai pas mort donc je pense qu'il doit y avoir une protection du cote de netu

**Comment by TmpName** [comment]
Ca doit etre un prb de lien car sur un autre site les liens fonctionnent.

**Comment by Arias800** [comment]
Ok ca fontionne chez moi il reste quelque modif a faire et apres je fait le pull request

**Comment by razorex** [comment]
????? @Arias800 çà fonctionne chez toiles liens Netu??? j'ai mis le dernier hoster de netu et moi je n'ai rien...

**Comment by Arias800** [comment]
Moi ça fonctionne faut que je fasse des modifier dans le dernier code et je le publie

**Comment by razorex** [comment]
@Arias800 tu est sur que tu a pas un bug encore dans le titre affiché. moi j'ai du refaire une correction parce que j'ai 2 fois la langue qui s'affichent.

**Comment by razorex** [comment]
coco_stream ajouté aux sites.
