### ISSUE TITLE
hoster speedvid

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#1614]
Salut @TmpName ,

Je me suis aperçu que le hoster speedvid ne fonctionne plus. Apparemment cela vient de la librairie cpacker de Dean Edward's.
Par contre en mettant le code de la fonction p,a,c,k,e,d du hoster directement dans le décodeur en ligne de Dean ça décode parfaitement et on obtient le lien.
T’aurais pas une maj de cette librairie sus le coude ?

Bon courage à toute l'équipe !

**Comment by TmpName** [comment]
J'ai commence, j'en suis la https://pastebin.com/7Zc6PctW

Mais le prb ne vient pas de la librairie, les liens sont recuperes mais je pense qu'il y a une partie du code qui remodifi le lien.

**Comment by TmpName** [comment]
Bon c'est bon j'ai trouve, mais vais pas avoir le temps ce soir.
Alors sur la premiere page il y a des liens, et un code louche. Les liens sont faux, le code contient un autre code a unpacker, celui ci renvois sur la vraie page, et c'est sur celle la qu'il faut chercher les liens.

**Comment by TmpName** [comment]
Nouvelle version en test
https://pastebin.com/4zGhnCp6

**Comment by TmpName** [comment]
Bon ben on va dire que c'est bon ^^. Le site dont je me servait est HS, donc peux plus tester.
Mit en place.
