### ISSUE TITLE
TV du Web a disparu?

### ISSUE THREAD

**Issue by ColinWillies** [Kodi-vStream/venom-xbmc-addons#1615]
Bonjour à tous,

Je ne sais pas depuis quand car j'ai pris l'habitude de passer par mes favoris qui fonctionnent toujours. J'ai du faire une réinstalle sur un appareil qui a crashé complètement (tout perdu y compris mes backups sur la carte SD). Je ne retrouve plus les chaines nationales (avant sous TV du Web). Quelqu'un pourrait m'aider a comprendre / corriger SVP?...

**Comment by Arias800** [comment]
TV du web a disparut mais il me semble que ça devrait revenir après si tu ne peux pas attendre je te conseil allfrtv qui est très pratique pour regarde la tv

**Comment by LordVenom** [comment]
Bonjour, à moins qu'un membre de la team le veuille, pour moi la tv c'est fini.

**Comment by ColinWillies** [comment]
Merci - je regarde encore certaines choses à la télé (télématin est mon "péché mignon" :-)

**Comment by TmpName** [comment]
C'etait quoi le soucis ? Les chaines nationale etaient stables ?

**Comment by ColinWillies** [comment]
Celles que j'ai encore en favoris fonctionnent encore en effet. Le souci est que suite à un rebuild d'un device sans backup je ne trouve pas de moyen de retrouver les chaines sous vstream.

**Comment by ColinWillies** [comment]
allfrtv est moins bien que ce que nous avions avant sous vstream - max 40 changements de chaine en 24H et compte suspendu... Ce serai vraiment bien si ces chaines pourraient être remise dans vstream...

**Comment by LordVenom** [comment]
Rien de spécial trop de demande et je l'utilise pas donc c'est passer à la trappe, je pensais que tu l'utiliser pas non plus. Ont fait un retour mais uniquement les chaines stable ?

**Comment by ColinWillies** [comment]
Tout ce qui peut être fait sera apprécié :-)

**Comment by TmpName** [comment]
Les chaines stables venaient de sources officielles, donc pas trop mechant et y en avait 5/6 max je crois donc c'est pas non plus la mort a gerer.

**Comment by LordVenom** [comment]
Fait

**Comment by mmtest1** [comment]
@LordVenom 
bonjour, 
à mon avis la liste de livetv  ajoutée ne correspond pas aux quelques liens fonctionnels mentionnés,
il s'agit plutôt, à mon avis de la rubrique tv du web avec les liens officiels en regex de francetv et autres

#EXTINF:-1 tvg-id="FRA1.kazer.org" tvg-name="France 1" tvg-logo="tf1.png" group-title="Group 1",TF1
[REGEX]"(http[^"]+)"[POSTFORM]udid=B85E0FCB-A255-48BD-9A71-3C1AB782A7BB&mediaId=L_TF1&appName=sdk%2FIphone%2F1.0&authKey=d7a5407b73696fc9b1e983c7be9009db%2F1409816606000&method=getLiveUrl[URL]http://api.wat.tv/services/Delivery

#EXTINF:-1 tvg-id="FRA2.kazer.org" tvg-name="France 2" tvg-logo="france2.png" group-title="Group 2",France 2
[REGEX]{"url": "([^"]+)"}[URL]http://hdfauthftv-a.akamaihd.net/esi/TA?format=json&url=http%3A%2F%2Flive.francetv.fr%2Fsimulcast%2FFrance_2%2Fhls_v1%2Findex.m3u8&callback=_jsonp_loader_callback_request_2

#EXTINF:-1 tvg-id="FRA3.kazer.org" tvg-name="France 3" tvg-logo="france3.png" group-title="Group 3",France 3
[REGEX]{"url": "([^"]+)"}[URL]http://hdfauthftv-a.akamaihd.net/esi/TA?format=json&url=http%3A%2F%2Flive.francetv.fr%2Fsimulcast%2FFrance_3%2Fhls_v1%2Findex.m3u8&callback=_jsonp_loader_callback_request_2

#EXTINF:-1 tvg-id="FRA4.kazer.org" tvg-name="France 4" tvg-logo="france4.png" group-title="Group 4",France 4
[REGEX]{"url": "([^"]+)"}[URL]http://hdfauthftv-a.akamaihd.net/esi/TA?format=json&url=http%3A%2F%2Flive.francetv.fr%2Fsimulcast%2FFrance_4%2Fhls_v1%2Findex.m3u8&callback=_jsonp_loader_callback_request_2

#EXTINF:-1 tvg-id="FRA5.kazer.org" tvg-name="France 5" tvg-logo="france5.png" group-title="Group 5",France 5
[REGEX]{"url": "([^"]+)"}[URL]http://hdfauthftv-a.akamaihd.net/esi/TA?format=json&url=http%3A%2F%2Flive.francetv.fr%2Fsimulcast%2FFrance_5%2Fhls_v1%2Findex.m3u8&callback=_jsonp_loader_callback_request_2

#EXTINF:-1 tvg-id="FRA1.kazer.org" tvg-name="France O" tvg-logo="franceo.png" group-title="Group 65",France O
[REGEX]{"url": "([^"]+)"}[URL]http://hdfauthftv-a.akamaihd.net/esi/TA?format=json&url=http%3A%2F%2Flive.francetv.fr%2Fsimulcast%2FFrance_O%2Fhls_v1%2Findex.m3u8&callback=_jsonp_loader_callback_request_2

#EXTINF:-1 tvg-id="ART1.kazer.org" tvg-name="Arte" tvg-logo="arte.png" group-title="Group 14",Arte
http://artelive-lh.akamaihd.net/i/artelive_fr@344805/master.m3u8

#EXTINF:-1 tvg-id="GUL1.kazer.org" tvg-name="Gulli" tvg-logo="gulli.png" group-title="Group 165",Gulli
[REGEX]file: '([^']+master.m3u8)'[URL]http://replay.gulli.fr/jwplayer/embedstreamtv

**Comment by LordVenom** [comment]
Oui

**Comment by ColinWillies** [comment]
Est ce que le changement est fait? Si oui comment accéder ces chaines à nouveau? Sinon je vous laisse travailler tranquillement - merci encore :-)

**Comment by ColinWillies** [comment]
Je vois que la solution est en place et fontanelle - merci beaucoup! :-)
