### ISSUE TITLE
Source Anglaise 

### ISSUE THREAD

**Issue by CharlyNetSky** [Kodi-vStream/venom-xbmc-addons#1616]
Salut tout le monde, 
Petite question certain d'entre vous ont des sites de streaming de film et série en VO sans les sous titre ? 
J'ai regardé un peu dans vstream mais j'avoue que j'ai pas tout regardé... 
Merci ☺️

**Comment by LordVenom** [comment]
Bonjour, Non pas de VO c'est un addon pour les francophones y a d'autre d'addon pour les anglais.

**Comment by CharlyNetSky** [comment]
Merci pour ta réponse ☺️ 
Tu aurais le nom d'un addon en particulier ? Car ceux que j'ai pu trouver ne marche pas ou plus 🙁 
C'est principalement pour bosser mon anglais lol

**Comment by razorex** [comment]
Bonjour, tu a exodus

**Comment by TmpName** [comment]
Lol, j'aurais repondu pareil.

**Comment by CharlyNetSky** [comment]
Merci j'avais trouvé çà aussi mais pas moyen de trouver un repo qui fonctionne j'en ai trouvé un autre c'est covenant 

T'inquiète LordVenom ton addon est bien meilleur et a chaque fois que je l'utilise (tout les jours) je me dit que c'est magique ! :D

**Comment by LordVenom** [comment]
C'est pas le soucis de savoir quel est le meilleur c'est juste de pas leur faire de la pub gratos surtout qu'il sont moin bon xD

Note : Notre addons j'y tient beaucoup à ça.
