### ISSUE TITLE
PlayerDebug (Plugin Keymap modifié inside)

### ISSUE THREAD

**Issue by Vidalcris** [Kodi-vStream/venom-xbmc-addons#1617]
Salut !
Desolé ce sujet ne touche pas directement Vstream mais je voulais demander comment vous faites pour avoir l'ancien CodecInfo dans Kodi17.
Le raccourcis de base c'est Ctrl+Shift+o .. mais je voit pas comment le faire sur ma box tv ^^
J'ai modifié le fichier keymap directement et maintenant CodecInfo et PlayerDebug affichent la meme chose contrairement à mon PC ou avec la meme modification cela fonctionne :-/

-----------------
Probleme resolu avec cette version modifié de Keymap editor : http://wikisend.com/download/367056/xbmc-keymap-editor-patch-Crisssss.zip

**Comment by chataigne73** [comment]
As tu essayé l addon keymap editor puis dans sa rubrique fullscreen vidéo tu mappes une touche de ta télécommande

**Comment by Vidalcris** [comment]
Yep c'etait la bonne piste merci ;)
Par contre j'ai du modifier un des fichiers du plugin pour pouvoir associer une touche à "PlayerDebug".
Si ca interesse qqun il suffit de remplacer ce fichier : http://wikisend.com/download/509532/actions.py

J'ai juste ajouté la deuxieme ligne : 
"codecinfo"         , "Show codec info",
"PlayerDebug"       , "Show Player Debug",

**Comment by Vidalcris** [comment]
Juste si qqun a besoin je laisse ouvert, je vous laisse gerer ca ;)

**Comment by Arias800** [comment]
@LordVenom va peut etre mettre le lable "Information"

**Comment by LordVenom** [comment]
L'ancien CodecInfo ? pourquoi, c'est quoi, un screen peux être.

**Comment by Vidalcris** [comment]
Yep, alors l'ancien j'ai pas de screen mais y'avait toutes les info sur un seul ecran.
Les nouveaux les voila : 
Quand on presse "o" : https://ibb.co/b2sZ1k
Et quand on presse "ctrl+maj+o" : https://ibb.co/dCHdSQ

**Comment by LordVenom** [comment]
Ok mais l'addon n'est pas utilise tu peux créer le fichier avec un simple editeur texte style block-note.

http://kodi.wiki/view/Keymap

**Comment by Vidalcris** [comment]
Bah disons que sur une box TV sans clavier c'est pas facile ;)
Et puis pour trouver la correspondance avec la telecommande sans l'application ca va etre la merde..

**Comment by tchirou** [comment]
Hello Vidalcris
Ton zip n’est plus accessible, pourrais-tu le remettre en ligne stp ?
Merci beaucoup pour le taf

**Comment by Vidalcris** [comment]
Salut @tchirou ;)
Celui ci devrais ne jamais se perimer : http://uptobox.com/j2aoheblofll

**Comment by tchirou** [comment]
Au top merci beaucoup
J'avais modifié le gen.xml à la main mais ça sera pratique pour le futur.
Il s'installe en + du keymap officiel ?
Merci beaucoup

**Comment by Vidalcris** [comment]
De rien ;)
Il ecrase l'original.
