### ISSUE TITLE
Possible de faire une recherche avec extended info mod

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#1618]
Voilà extended info mod et un addon qui permet de faire une recherche via the movie database
Et je voulais savoir si on peut faire une recherche vstream avec extended info mod sur kodi 17 

Merci

**Comment by LordVenom** [comment]
Bonjour, Je comprend pas la question. Si extended est installé tu peux voir les informations d'un film avec est c'est tout.

**Comment by Ovni-crea** [comment]
Bonjour,je parlais de la version modder de extended info mod sur q s repository pas la version original ,la version modder avec metalliq Désolé si j ai mal expliqué

**Comment by Arias800** [comment]
Alors faire une recherche avec MetalliQ c'est possible https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1542 mais avec je n'ai pas encore trouve de solution ^^
