### ISSUE TITLE
ZT ne fonctionne plus ? 

### ISSUE THREAD

**Issue by Vidalcris** [Kodi-vStream/venom-xbmc-addons#1619]
J'ai un ecran gris quand je clic sur un lien uptobox.
Juste avant d'arriver sur le lien du fichier.
C'est pareil chez vous ?

**Comment by Arias800** [comment]
Chez moi  ça me mets que DL protect est hs encore une fois

**Comment by Vidalcris** [comment]
Ok merci faut que je m'habitue a Kodi17 et le skin Eminence 2.0..

**Comment by Vidalcris** [comment]
J'aimerai bien comprendre comment on procede pour creer ajouter ou deja modifier un site.
Ca à l'air plutot compliqué ^^
Est ce que ce probleme de DL protect peut etre resolu ou il faut juste attendre ?
Je viens de verifier sur mon pc ca fonctionne en passant par l'url2 qui est dans le fichier zt...ws.py

**Comment by Arias800** [comment]
Voila pour les base de la creation d'un site pour vstream https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-créer-sa-propre-source ensuite pour dl protect ça doit surement être possible de le réparer car @chataigne73 la fix il y a pas longtemps

**Comment by chataigne73** [comment]
Pour moi ça marche très bien donc je ne comprends pas le problème

**Comment by Arias800** [comment]
Ca remarche en copier collant la dernier version peut etre un bug de mise a jour ^^

**Comment by Vidalcris** [comment]
Comment en copiant collant ? je viens d'essayer de desinstaller completement Vstream et apres reinstallation c'est toujours pareil. Ca me met juste aucun lien.
voila ce que j'ai : 
13:14:10.725 T:18446744071780206848  NOTICE:    [PLUGIN] Vstream: SQLITE 3 as DB engine
13:14:10.754 T:18446744071780206848  NOTICE:    [PLUGIN] Vstream: load site zone_telechargement_ws and call function showMoviesLinks
13:14:11.352 T:18446744071780206848  NOTICE:    [PLUGIN] Vstream: Table initialized
13:14:13.169 T:18446744071779225216  NOTICE:    [PLUGIN] Vstream: SQLITE 3 as DB engine
13:14:13.197 T:18446744071779225216  NOTICE:    [PLUGIN] Vstream: load site zone_telechargement_ws and call function showHosters
13:14:15.480 T:18446744071779225216  NOTICE:    [PLUGIN] Vstream: Table initialized
13:14:17.518 T:18446744071795412864  NOTICE:    [PLUGIN] Vstream: SQLITE 3 as DB engine
13:14:17.631 T:18446744071795412864  NOTICE:    [PLUGIN] Vstream: load site zone_telechargement_ws and call function Display_protected_link
13:14:17.759 T:18446744071795412864  NOTICE:    [PLUGIN] Vstream: DecryptDlProtecte : https://www.dl-protecte.org/1234556001234556021234556101234556152pj3ce3jvanv
13:14:18.201 T:18446744071795412864  NOTICE:    [PLUGIN] Vstream: Table initialized
13:14:31.842 T:18446744071768462592 WARNING: Attempt to use invalid handle -1
13:14:31.843 T:18446744071768462592 WARNING: Previous line repeats 2 times.

**Comment by Arias800** [comment]
J'ai copier le contenu de ce fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py dans le fichier zone_telechargement_ws.py

**Comment by Vidalcris** [comment]
Ah ok, encore un truc que je peut pas faire avec ma Freebox mini 4k ;)
Je vais me faire un zip avec les derniers fichiers et l'installer .. ca devrais faire pareil ^^

**Comment by Arias800** [comment]
Normalement oui ^^

**Comment by Vidalcris** [comment]
Ok ca fonctionne !

**Comment by TmpName** [comment]
Dsl, y avais un gros retard sur les MAJ auto, normallement dans max 3 jours ce sera bon pr tout le monde.

**Comment by Vidalcris** [comment]
Ne le soit pas, c'est juste que ca tombais en meme temps que mon passage à Kodi17 du coup j'avais peur que ca vienne de moi ;)
Merci pour ton super boulot au contraire !

**Comment by Arias800** [comment]
Les retard ca arrive regarde la SNCF :p

**Comment by rod93** [comment]
bonjour jai essaye de copier le contenu mais pareil cela mindique site dl protect hs

**Comment by valkerball** [comment]
J'ai le même problème "dl protect hs" via n'importe quels liens zone téléchargement via la version 0.5.4 de vstream ou versions ultérieures.
J'ai également fait un essai en modifiant le fichier zone_telechargement_ws.py --> Même erreur "dl protect hs"
(J'utilise url resolver via vstream) cela est il lié ?

**Comment by rod93** [comment]
Non pas lié même problème avec abonnement 1fichier

Le 3 sept. 2017 18:48, "valkerball" <notifications@github.com> a écrit :

J'ai le même problème "dl protect hs" via n'importe quels liens zone
téléchargement via la version 0.5.4 de vstream ou versions ultérieures.
J'ai également fait un essai en modifiant le fichier
zone_telechargement_ws.py --> Même erreur "dl protect hs"
(J'utilise url resolver via vstream) cela est il lié ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1619#issuecomment-326816365>,
or mute the thread

**Comment by valkerball** [comment]
Je viens de faire un test via l'installation complète de kodi v17 --> les liens zone téléchargement fonctionnent
Avec une réinstallation complète de SPMC -->  les liens zone téléchargement  indiquent "dl protect hs"
J'utilise principalement SPMC car mieux adapté à la Nvidia Shield

**Comment by valkerball** [comment]
J'ai trouvé d'ou vien le problème la version de SPMC en 16.6.x ne fonctionne pas avec les lien de zone téléchargement. 
J'ai utilisé la version 16.7.1 depuis le site de SPMC : https://github.com/koying/SPMC/releases/download/16.7.1-spmc/SPMC-16.7.1-spmc-4baafdf-armeabi-v7a.apk
Et ça fonctionne !! :)

**Comment by Arias800** [comment]
Ah bizarre ça ^^

**Comment by reds2206** [comment]
Toujours le meme souci d'erreur SiTE DL PROTECT HS, je ne peux plus rien regarder sur Zone telechargement depuis 2 semaine et la mise a jour 5.4 n'a rien changer :(:(:( , ya vraiment personne qui peux nous aider....

**Comment by Arias800** [comment]
bah chez moi ça fonctionne le code en lui-même a l'air ok donc faut trouver le point commun entre les personne qui ont le bug et voir si ça ne vient pas du site en lui-même

**Comment by reds2206** [comment]
Salut quelle version de Kodi a tu:

Pour ma part je tourne sur la version 16.1 jarvis, j'ai essayer d'essayer d'installer la version 17.4 sur pc pour voir si sa reglait le souci mais encore pire, des que je clique sur un liens Zone telechargement, j'ai droit a un beau message ' Erreur Vstream consultez le journal pour plus d'info '

**Comment by Arias800** [comment]
J'ai kodi 17.3 sur mon pc j'essaye avec kodi 17.4 ^^

**Comment by Arias800** [comment]
Peut tu me donner un exemple qui ne marche pas chez toi ?

**Comment by reds07** [comment]
N'importe lesquelles des liens sur zone téléchargement me met l'erreur sur kodi 17.4, je choisi une section et dès que je veux pour afficher le liens de l'hébergeur sa me donne le message d'erreur.

**Comment by Arias800** [comment]
Bon alors chez moi ça marche pas d'erreur

**Comment by Vidalcris** [comment]
Je suis passé a Kodi 18 il y'a quelques heures et ca fonctionne aussi.
Juste pour info ;)

**Comment by Arias800** [comment]
@reds07 essaye kodi 18 voir si ça regle le probleme

**Comment by Vidalcris** [comment]
@reds07 si tu va sur ZT avec ton navigateur sur ton pc est ce que ca fonctionne ?
Dans ce cas ce serait pas la peine de chercher plus du coté de Vstream ;)

**Comment by reds07** [comment]
Je peux sans problème aller sur zone téléchargement via mon navigateur sur pc, ces vraiment sur Android box depuis 2 bonne semaine que je ne sais plus y aller comme pas mal de monde et j'ai voulu tester sur pc avec l'application kodi 17.4 et ces pire.

**Comment by Vidalcris** [comment]
et tu a reinstallé la 0.5.4 directement avec le zip ?
Tu a bien la derniere version du repo aussi ? C'est la 0.2 il me semble ...
Je te demande des details parce que chez moi ca fonctionne depuis la derniere mise à jour de ZT.
Avant cette mise a jour j'avais le meme soucis que toi..

**Comment by Xiaomisenz1** [comment]
Pareil pour moi, sur box Android et kodi v16.1 les liens ne fonctionnent plus

**Comment by reds07** [comment]
Oui j'ai carrément supprimer vstream effacer les caches et perdu mes favoris, comment bien nettoyé le cache, car malgré sa il a garder mes comptes premium, pourrait tu stp me donner directement les liens des zip à télécharger et à installer pour être sûr que je ne me soit pas tromper lors de la réinstallation. Je les installerait directement depuis l'usb.

**Comment by rod93** [comment]
OK super cela fonctionne avec la dernière version de smpc

**Comment by reds07** [comment]
https://ares-project.uk/logupload/log.php?id=2440223

Au cas ou

**Comment by TmpName** [comment]
Y a de gros soucis de version python.
Je sais pas qui tient le systeme a jours, mais il  a du taff.

**Comment by Xiaomisenz1** [comment]
Ca y est c'est bon pour moi, j'ai installe la dernière version de kodi sur mon pi3 car ma box Android a une version d'android trop ancienne pour pouvoir mettre la dernière version de kodi. Plus de soucis sur mon raspberry ça fonctionne nickel

**Comment by Pack33** [comment]
La seule solution que j'ai trouvé a été de passer sur Kodi 17.
CONSEIL : Pour tous ceux qui comme moi avaient beaucoup de mal avec l'interface Kodi 17, il suffit de choisir l'habillage CONFLUENCE. Et hop... je retrouve l'interface Jarvis sur le Krypton. :)
