### ISSUE TITLE
bande annonce

### ISSUE THREAD

**Issue by yas06** [Kodi-vStream/venom-xbmc-addons#1620]
Bonjour les bandes annonce ne fonctionne pas chez avez vous le même soucis ?

**Comment by LordVenom** [comment]
Bonjour, cette conversation répond a ta question?

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1557

**Comment by Vidalcris** [comment]
Bande annonce, recherche similaire, et info... :-/
Mais si j'ai bien compris ca va revenir ;)

**Comment by Arias800** [comment]
Pour les bande annonce je le redit voila la version du gui.py qui permets de les remettre dans les context menu https://github.com/Arias800/Restaure_ba/blob/master/gui.py

**Comment by khalilounet** [comment]
J'ai bien Bande Annonce dans le menu contextuel mais quand je clique rien ne se passe. 
Faut-il activer quelque chose de particulier ?

**Comment by TmpName** [comment]
J'ai eu le meme prb sur kepliz un dimanche, mais la je viens de re-essayer ca passe sans probleme.
En fait pour les video youtube on depend d'un autre site, celui ci a du declarer forfait a un moment, mais la pas vu de problemes.
