### ISSUE TITLE
free telechargement

### ISSUE THREAD

**Issue by rod93** [Kodi-vStream/venom-xbmc-addons#1625]
bonjour 
plus de liens sur free telechargement

**Comment by Arias800** [comment]
Alors pas sur tous mais sur certain oui je regarde ça de plus près (les lien bugge sont identifiable car il ont un "-" devant de nom

**Comment by Arias800** [comment]
Chez copier coller manuellement le fichier a regler le probleme https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/free_telechargement_org.py

**Comment by rod93** [comment]
Merci mais je n'arrive pas à le copier sur une box Android non rooter

**Comment by rod93** [comment]
bonjour jai copier le contenu dans le fichier mais meme probleme cela ne souvre pas merci

**Comment by Arias800** [comment]
Un exemple qui ne marche pas stp ?

**Comment by rod93** [comment]
alien

**Comment by rod93** [comment]
1080p

**Comment by Arias800** [comment]
Normale il n'y a qu'un lien premuim et des lien interchangeable qui n'apparaisse pas car ce n'est pas compatible ^^

**Comment by Arias800** [comment]
De memoire les lien premuim ne sont pas utilisable il me semble sauf qu'il y a que ca ^^

**Comment by rod93** [comment]
poutant avant je nutilise que les liens premium avec abo 1fichier

**Comment by Arias800** [comment]
Ok bon bah je regarde ^^

**Comment by TmpName** [comment]
Le probleme vient du "if total == 1" ligne 566, mais je vois pas a quoi ca sert.
Il faudrait refaire toute cette partie, elle fonctionne avec 2 regex, un qui prend une valeur, et un qui en prend plusieurs.

```
if len(aEntry) > 1:
     partie regex 1
else:
     partie regex 2
```

**Comment by Arias800** [comment]
A la ligne 566 j'ai ca personnelement : cConfig().finishDialog(dialog)

**Comment by TmpName** [comment]
Ha ^^, j'ai du bidouiller le code, mais dans le coin tu dois avoir "if total == 1"

**Comment by Arias800** [comment]
Yep moi j'ai ca ` if total == 1:
                sTitle = '[COLOR skyblue]' + 'Liens Premium' + '[/COLOR]'
                oOutputParameterHandler.addParameter('siteUrl', aEntry)
            else:
                sTitle = '[COLOR skyblue]' + sHostName + '[/COLOR]'
                oOutputParameterHandler.addParameter('siteUrl', aEntry[1])`

**Comment by TmpName** [comment]
C'est ca, en fait tu as une seule ligne (1 seul lien premium, 1fichier je crois), donc total = 1 et donc tu affiches juste "Lien premium" sans rien d'autre.
J'ai pas compris le but du smilblik.

**Comment by TmpName** [comment]
Le bug n'a pas encore ete corrige.

**Comment by LordVenom** [comment]
ok dsl
