### ISSUE TITLE
Kepliz HS

### ISSUE THREAD

**Issue by Benaland** [Kodi-vStream/venom-xbmc-addons#1626]
Salut la team, je n'arrive plus à ouvrir Kepliz. Je voulais testé le site avant de poster ici mais ils changent souvent de noms ... Du coup je me suis permis de le signaler ici

Et merci pour tout !

**Comment by Arias800** [comment]
Le site a encore change de nom mozdad_com et il ont encore foutu un beau bordel dans le code ^^

**Comment by geekeeg** [comment]
Bonjour,
Je confirme, page plage pour kepliz, pas de création de liste de films....
Ça serais cool de corriger ce hic !
D'avance merci.
Bizarre car le site est toujours dispo sous le nom de fetayo.com.....

**Comment by Arias800** [comment]
C es normal ils ont un nombre un calculable de clone ^^

**Comment by TmpName** [comment]
Bon ben pour le moment j'ai meme pas pu acceder au site une seule fois, (mozdad), ca boucle meme avec les antipub a off.

**Comment by Arias800** [comment]
Essaye avec l'url du site : ht_p://mozdad_com/sqcdsf54c8f7sq87q/

**Comment by TmpName** [comment]
Marche pas ^^, du coup j'ai corrige avec fetayo qui marche encore.

**Comment by TmpName** [comment]
Si quelqu'un veut s'en occuper, il ya un gros prb dans le code dans showHostersLink2().
Quelqu'un a voulu supprimer une etape et c'est pas fiable.
Le regex extrait plusieurs liens et plusieur qualitée, sauf qu'il essais de resoudre tout les liens, et il n'y en a qu'un qui marche a chaque fois (c'est pour ca qu'il n'y a qu'une seule qualite affichée).
Il faudrait rajouter une etape, avec toute les qualitée, et ne resoudre le lien qu'a l'etape d'apres.

**Comment by razorex** [comment]
@TmpName sur Wonder woman je n'ai jamais le même résultat des fois les 2 qualités l'autre fois une 720 ou 360, après l'autre et une autre 0 résultat. donc PB de regex

**Comment by TmpName** [comment]
Nope, c'est parceque Vstream essaye de decoder les 2 urls, et le site ne le fait pas, il faut afficher les 2 liens non decode, et uniquement apres le clic, decoder le lien et uniquement un.

**Comment by razorex** [comment]
vStream me dis bien que j'ai deux liens. Alors pk j'ai jamais le même résultat?

**Comment by TmpName** [comment]
En fait faut rajouter une etape, le lien php qui decode le lien ne doit etre fait qu'une seule fois.

**Comment by TmpName** [comment]
C'est bon ?
Sinon je m'y colle ?

**Comment by razorex** [comment]
Sit u veux regarder la suite reste à retravailler showHostersLink2 [ici](https://pastebin.com/UEVfrHhZ) le lien pastebin.

**Comment by TmpName** [comment]
Bon j'ai refait une version en virant tout ce qui sert a rien mais tjours le meme prb
https://pastebin.com/NCD4fRiq

Je suis reparti de la version originale car je mettais trop de temps a comparer les 2 fichiers. Tu peux bidouiller celui la si tu veux.

Cette fois, je ne fait qu'une requete a la fois pr decoder le lien, mais j'ai le meme resultat, quand on essaye d'afficher la resolution manquante ca marche 1 fois sur 7/8. Mais la ca viens de leur serveur, je peux pas faire mieux.

Du coup suis pas sur que ce soit utile, si le mec a du bol, il a deux liens, sinon il n'en a qu'un mais fonctionnel, plutot que de galeer a faire des va et viens pr afficher le lien.

Edit:
En fait suis meme sur que ca sert a rien ^^.

**Comment by TmpName** [comment]
Tu as de meilleur resultats que moi ? ou on cloture l'issue en laissant comme ca ?

**Comment by LordVenom** [comment]
Ont n'a un soucis avec google drive ?

Si je force toujours le vrais url ligne 372 de Kepliz

```
            try:
                response = urllib2.urlopen(req)
#code ajouter
                sLink2 = response.geturl()
                #data = response.read()
                response.close()
            except urllib2.URLError, e:
                sLink2 = e.geturl()
```

J'ai bien toujours les urls de googledrive mais impossible a lire

**Comment by LordVenom** [comment]
Ha ok si je transforma en 

```
            try:
                response = urllib2.urlopen(req)
                sLink2 = response.geturl()
                response.close()

                oHoster = cHosterGui().getHoster('lien_direct')
                oHoster.setDisplayName(sTitle)
                oHoster.setFileName(sTitle)
                cHosterGui().showHoster(oGui, oHoster, sLink2, '')
                #data = response.read()
```

J'ai bien des liens hoster lien direct qui tourne je continue les tests + tard.

**Comment by TmpName** [comment]
En fait on etait dessus avec @razorex, il y a un bug aleatoire qui fait que parfois le decodage deconne.
Tu fais une requete sur une page php du site lui meme avec try/except.
Si tu as une erreur, c'est que c'est bon, tu recupere l url de redirection avec "sLink2 = e.geturl()"
Si ca marche, je sais pas ce que c'est, mais ca charge pendant 10 plombes (voire meme bloque kodi), et tu te retrouves avec la meme url, c'est pour ca que je faisais sLink2 = '' car le lien n'avait pas pu etre decode.

La dans ton code normalement la ligne 376 ne sert a rien car elle sert qu'en cas de redirection.

**Comment by LordVenom** [comment]
J'ai modifier le fichier sur bêta j'ai fait quelque test pas de soucis, il me met soit lien direct ou google drive.

**Comment by TmpName** [comment]
Yep, j'ai vu, c'etait pour prevenir, pour les futures modifications, le pourquoi de ce code.

**Comment by razorex** [comment]
OK, merci pour l'info @TmpName.
