### ISSUE TITLE
libertyland , kaydo HS??

### ISSUE THREAD

**Issue by fminou** [Kodi-vStream/venom-xbmc-addons#1627]
Bonjour à tous,
je demande de l'aide parce que chez moi je n'arrive plus à avoir de lien vidéo sur ces serveurs en recherchant sur vstream que chez un pote des liens s'affiche pour le même film rechercher!

pouvez vous m'orienter 

merci

**Comment by TmpName** [comment]
Pas les memes reglages ?
Fichiers de version differentes ?

**Comment by fminou** [comment]
Tous les deux on a les mêmes boîtier beelink sous kodi 17.3 vstream 0.5.3 mis à jour du repo de vstream... Les réglages sont identiques c moi qui ait installés les deux boîtiers!! Sa me rend dingue cette histoire j'y comprend rien

**Comment by TmpName** [comment]
Si tu es sur des reglages, c'est surement les fchiers qui ne sont pas les memes, il y a une maj tout les 3 jours.

**Comment by fminou** [comment]
Ok je vais attendre la mise à jour voir si sa corrige mon souci.... mais j'ai hâte qu'il refonctionne ces 2 la !!!
Merci
