### ISSUE TITLE
Supprimer les popups Vstream ?

### ISSUE THREAD

**Issue by Vidalcris** [Kodi-vStream/venom-xbmc-addons#1628]
Alors voila j'ai un probleme que je n'arrive pas à resoudre ...
Lorsque j'ai fait ma nouvelle installation avec Kodi 17.4 au debut je n'avais pas de popup qui s'affiche pour dire que Vstream est en train de charger une liste.. Et la d'un coup ca revient je sait pas pourquoi je sait pas comment :-/
En fait j'utilise le skin Eminence 2.0 avec deux listes (films et series de ZT) sur mon ecran principal kodi.
Et donc quand je lance kodi au debut ca me bloque pendant le chargement de ces deux listes.

Je sait pas ce que j'ai fait, j'ai cherché de partout et je n'arrive pas a enlever ces popups ..
Au pire est ce que je pourrais modifier qqch dans  mes fichiers de config Vstream pour que ca n'apparaisse jamais ? (Une option dans le settings du plugin serait cool si c'est le cas ;) )

**Comment by Vidalcris** [comment]
J'ai trouvé que ca en cherchant ..
if (aResult[0] == True):
        total = len(aResult[1])
        dialog = cConfig().createDialog(SITE_NAME)
        for aEntry in aResult[1]:
            cConfig().updateDialog(dialog, total)
            sTitle = str(aEntry[2])
            sUrl2 = aEntry[0]

C'est bien ca qui genere le popup pendant le chargement d'une liste ?

Si c'est le cas je comprend pas pourquoi au debut j'avais pas le popup et maintenant je l'ai :-/

**Comment by Vidalcris** [comment]
Si je remplace : 
oDialog = xbmcgui.DialogProgress()
par
oDialog = xbmcgui.DialogProgressBG()

Ce serait trop simple .. j'imagine que la definition des deux fonctions est differentes :p

**Comment by TmpName** [comment]
Je vois pas pkoi ca bloque ?
Sinon ces fenetres sont utiles, le probleme c'est quand elle ne s'affichent pas.

**Comment by Vidalcris** [comment]
Tu utilise le meme skin non ? c'est suite a un de tes posts que j'ai mis ca en place. (je veut dire la liste film et series de ZT en page d'acceuil).
Donc au debut ca chargais en fond de tache et ca se marquai juste sur la ligne d'info.
Je pouvais me deplacer et faire tout ce que je voulais ca genais pas.
Mais maintenant j'ai le message de chargement de la liste qui s'affiche en plein milieu de l'ecran et ca m'empeche de naviguer ..

**Comment by Vidalcris** [comment]
Y'a pas moyen que globalement tous les messages de vstream s'affichent sur la ligne d'info et pas en dialog box ou popup .. ? :)

**Comment by Vidalcris** [comment]
Bien j'ai reussi a supprimer la fenetre en modifiant directement le fichier ZT.py
if (aResult[0] == True):
        total = len(aResult[1])
        #dialog = cConfig().createDialog(SITE_NAME)
        for aEntry in aResult[1]:
        #    cConfig().updateDialog(dialog, total)
            sTitle = str(aEntry[2])
            sUrl2 = aEntry[0]

Je me sent un peut seul alors qu'on aurai pu me confirmer que c'etait bien la ...
Bref c'est pas top ma modif car a chaque mise a jour du fichier faudra que je le refasse .. mais bon au moins c'est propre quand je demarre mon kodi ;)
