### ISSUE TITLE
Problème liens uptostream

### ISSUE THREAD

**Issue by alex83100** [Kodi-vStream/venom-xbmc-addons#1632]
Bonjour j'ai un problème avec les liens uptostream. Les films se lancent bien par contre impossible de les lancer à partir de la bibliothèque, ni de les rajouter au compte uptobox (indique fichier introuvable). 

J'ai regarder le lien générer par exemple plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=Wonder Woman&sMediaUrl=https%3A//uptostream.com/iframe/yaxqtwochetr&sHosterIdentifier=uptostream

Il contient /iframe/ ce qui semble poser problème, si on l’enlève je n'ai plus le problème.  Est il possible de modifier le code pour corriger ce problème ?

Alexandre

**Comment by Arias800** [comment]
Je regarde ca meme si moi j'ai plus la possibilite de choisir la qualite ^^

**Comment by alex83100** [comment]
Si cela peut t'aider j'ai fait mes tests sur VOIRFILM, moi non plus il ne me demande pas la qualité, mais ce n'est pas trop grave.

**Comment by Arias800** [comment]
Effectivement ca aide ^^

**Comment by Arias800** [comment]
Je vient de copier coller le fichier d'uptostream et personellement ce me redemande les qualité teste voir si ca ne regle pas ton probleme https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/uptostream.py

**Comment by alex83100** [comment]
Bonjour, non j'ai toujours le même problème : impossible de faire à partir du menu contextuel "ajout à mon compte uptobox" message d'erreur fichier introuvable et l'ajout à la bibliothèque vstream fonctionne mais le fichier STRM généré est illisible, certainement à cause de iframe contenu dans le lien. A quoi sert le fichier up2stream.py ?

**Comment by Arias800** [comment]
j'en ai aucune idée ^^ après le problème doit venir de "mon compte uptobox" et la par contre je connais pas le code ^^Avec quoi tu creer le fichier STRM ?

**Comment by alex83100** [comment]
je viens de faire d'autres tests certains STRM arrivent à se lancer à partir de la bibliothèques.

**Comment by alex83100** [comment]
oui, tu as raison le problème ne se pose que sur "ajout à mon compte uptobox", le test du fichier à partir de la bibliothèque qui ne fonctionnait pas était un fichier réellement introuvable. Sais tu qui connais le code de la source uptobox ?

**Comment by Arias800** [comment]
@LordVenom peut etre @TmpName ^^

**Comment by TmpName** [comment]
C'etait @johngf, mais la pr le moment c'est a l'abandon, car personne n'a de compte premium pr tester.

**Comment by alex83100** [comment]
Bonjour, je ne sais pas programmer en pyton, mais j'ai regarder le code de siteuptobox.py. 
J'ai fais la modification suivante à la ligne 147 qui fonctionne pour moi

    if 'https://uptostream.com/iframe/' in sMediaUrl : sId = sMediaUrl.replace('https://uptostream.com/iframe/','') 
    else : sId = sMediaUrl.replace('http://uptobox.com/','') 

à la place de 

sId = sMediaUrl.replace('http://uptobox.com/','')

Comment faire pour faire la modification sur le site pour que quelqu'un d'autre test ?

**Comment by alex83100** [comment]
Bonjour, je viens de faire une proposition de modification de code sur le site.
