### ISSUE TITLE
Bandes annonces hs

### ISSUE THREAD

**Issue by fredo04** [Kodi-vStream/venom-xbmc-addons#1633]
Comme promis par lordvenom les bandes annonces sont revenues dans le menue contextuel, sauf que.......ben rien ne se passe aussi bien par le menue contextuel que par information, les ba ne se lancent pas. Je suis sous box Android. J'ai fais une nouvelle installation sur tablette pour voir si ça venait de la box et bien non ça merde aussi sur une nouvelle installation sur tablette.

**Comment by LordVenom** [comment]
Ils ont changés leur site. Je passe par leur api maintenant mais c'est limité, à voir si ont explose le cota ou pas ont verra !. Encore un peux de patiente je fait encore quelques tests.

**Comment by TmpName** [comment]
Ha c'est plus la recherche via youtube ?
Pour onfo les BA passe par les TMDB sont tres souvent foireuses.

**Comment by LordVenom** [comment]
j'ai pris l'api de youtube :)

**Comment by TmpName** [comment]
Youtube propose une API ? Je croyais qu'ils etaient contre le partage de leur video ? C'est meme a cause de ca que l'addon youtube est refuse par la communaute officielle.

**Comment by LordVenom** [comment]
Ben c'est en ligne et fonctionnel a voir si ont dépassent le cota gratuit.
