### ISSUE TITLE
Stream pour la music

### ISSUE THREAD

**Issue by JaqenGOT** [Kodi-vStream/venom-xbmc-addons#1634]
Bonsoir,
Est-il possible de  créer des scripts pour des sites de music comme streamalbums.com ou hotnewhiphop.com, sachant que ces sites propose de lire les titres en streaming comme n'importe quel autre site de films et séries en streaming. 
De même avoir une section music dans vstream serait top.
Merci

**Comment by LordVenom** [comment]
C'est du python tout est possible xD.

**Comment by JaqenGOT** [comment]
Ok, merci mais n'y connaissant rien, y aurait-il une personne volontaire pour le faire ou bien me donner la démarche a suivre?

**Comment by LordVenom** [comment]
C'est pas dans le projet de vStream de faire dans la music.

**Comment by TmpName** [comment]
La, niveau volontaire, on est plutot a la ramasse pour maintenir les sources existantes, donc peu de chance de trouver quelqu'un.
Apres si tu veux te lancer il y a un fichier squelette https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source

**Comment by JaqenGOT** [comment]
OK, je vais tenter de le faire et si j'y arrive pourra t'il faire partie de vstream car LordVenom m'indique que ça fait pas parti du projet?

**Comment by LordVenom** [comment]
Je voulais dire ceux qu'a dit @TmpName  mais en moin bien tourner xD. Si c'est coder, utile et maintenus, pas de soucis.

**Comment by JaqenGOT** [comment]
Ok, je vais essayer mais je garantie rien. J'aurais sûrement besoin de vôtre aide à un moment où un autre.

**Comment by JaqenGOT** [comment]
bonjour, j'ai commencé le fichier et je voulais savoir si je pouvais supprimer les lignes 29 à 66 qui concernent les films, series, docs, etc? ou si il faut que je remplace "films" par  "music"? ou si il faut que j'ajoute les Genres ( pop, hip hop, electro,...) à la place?
Merci de votre aide.

**Comment by LordVenom** [comment]
C'est mieux dans créer des nouvelles genre MUSIC_NEWS , MUSIC_GENRES pour faire les choses bien, pas utile pour le moment mais par la suite peux être.

**Comment by TmpName** [comment]
Ha oui j'avais pas pense au cote integration.
Ta source marchera en allant dans "toutes les sources" mais pour le moment y a rien de prevu pour l'integrer, pas de moteur de recherche, pas de sections, ect ...

**Comment by JaqenGOT** [comment]
Un peu trop complexe pour moi j'avoue...

**Comment by TmpName** [comment]
Lol, oui en general, ca demarre tres vite, puis quand la personne arrive au regex, ca ralenti d'un coup ^^.
Apres ca depend de la motivation, mais ca prend du temps.
