### ISSUE TITLE
Idée pour la partie recherche

### ISSUE THREAD

**Issue by Aliasexterne** [Kodi-vStream/venom-xbmc-addons#1637]
Bonjour, 
voici une idée, je n'ai pas retrouvé dans les archives quelque chose de similaire mais je peux me tromper et si ça se trouve vous y avez déjà pensés. 

Mes dernières années de codage (html/css/java) remontent à loin maintenant, mais pour la section de recherche est-ce qu'il serait envisageable d'avoir une fonction de type
 _"if result='null' then "source"=HIDDEN"_. 
En gros, la fonction serait si le site ne retourne pas de réponse correspondante à la requête alors il n'apparait pas dans la liste finale. J'ai regardé le code du fichier rechercheHandler.py  pour voir comment sont compilés les résultats, mais je n'y ai pas compris grand chose. En théorie, d'après mes souvenirs si les résultats étaient compilés dans un tableau, il serait alors possible de masquer les champs vides. Cela pourrait alléger la page des résultats quand seulement un ou deux sites proposent des réponses. 

C'est une idée flou mais si jamais... 
En tout cas encore merci pour le taff énorme que vous faites!

**Comment by LordVenom** [comment]
La recherche global ce fait dans default.py fonction searchGlobal()

**Comment by TmpName** [comment]
Ha oui, pas betes, et c'est facile a faire.
Moi ca me gene pas, car j'aime bien voir les sites utilises, meme si il n'y a pas de resultats, mais ca peut etre utiles.

On lance un vote ?

**Comment by Arias800** [comment]
Je trouve ça que c est un bonne idée mais si un site ne fonctionne plus il ne s affichera plus et on s'en rendrai peut être pas compte . Donc je reste neutre

**Comment by LordVenom** [comment]
J'avais regarder pour moi pas possible a faire.

**Comment by Aliasexterne** [comment]
par rapport aux sites qui n'afficheraient plus de réponse du fait de leur inactivité je ne vois pas de mon côté où serait le problème si leur activité est surveillée par un autre biais. Cette idée m'est venue après avoir cherché le film _vipère au poing_ et j'ai eu une longue liste de site sans réponse , du coup cela aurait permis d’alléger visuellement les réponses. Mais je n'ai plus de notions en programmation hormis une idée du schémas de fonctionnement, c'est pourquoi je soumet juste l'idée, mais c'est vrai que ça peut vite être "usine à gaz".

**Comment by TmpName** [comment]
Avant c'etait pas possible, mais depuis ta derniere bidouille ou tu fais 2 passes pour l'affichage, c'est tjours pas jouable ?
Si result['guiElement'] ou result['params'] == Null on saute les lignes 226 a 232, y a pas moyen de jouer avec ca ?

D'ailleurs je comprend tjours pas comme ca fonctionne, la ligne 214 n'affiche rien ?

**Comment by LordVenom** [comment]
Le problème c'est pas les résultat mais le nom du site qui est indépendant de l'import et impossible de savoir si un import donne un resultat positif ou pas ou j'ai pas trouver tout simplement.

**Comment by TmpName** [comment]
Mais comment fonctionne la fonction ?
Il y a deux passes. Tu recuperes bien le nom du site et les resultats. Apres il y a une seconde progress bar, donc je pense que c'est a ce moment que tu ecris dans la "fenetre" ?

**Comment by LordVenom** [comment]
1 boucle - sur les plugin dispo pour la recherche a l'aide de disp et voir si activer ou pas
- nom du site
- import du site et creation des guielements du site

2 bouble des elements - tous les guielement sont bouclé pour creer les menus

**Comment by TmpName** [comment]
Me faudra faire des tests, mais si _pluginSearch() retournait true ou false, ca aiderait pas ?

**Comment by LordVenom** [comment]
Ben le resultat et le même à moins de changer l'affichage et mettre le nom du site aprés le resultat.

- result 1
- result 2
-- nom du site
-result 1
- result 2
-- nom du site

**Comment by FEARZYAH** [comment]
Hello,

Je suis clairement pour, si c'est réalisable. Ou sinon pourquoi pas avoir un moyen d'activer/désactiver la fonction dans les options du plugin?

**Comment by TmpName** [comment]
Ben j'ai pas encore regarde ^^ (je fous pas grand chose en ce moment ) mais je voyais un truc comme ca

if _pluginSearch(plugin, sSearchText):
      oGui.addText(plugin['identifier'], '%s. [COLOR olive]%s[/COLOR]' % ((count+1), plugin['name']), 'sites/%s.png' % (plugin['identifier']))


Comme ca si pas de retour, on affiche pas le nom du site, mais faut que la fonction _pluginSearch retourne true ou flase.

**Comment by LordVenom** [comment]
J'ai modifier tous les sites pour qu'il retourne "pas de reponse" pas trop dur de re-modifier pour qu'il return False.
