### ISSUE TITLE
Merci

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1638]
Je sais pas trop quoi faire avec les donateurs,  je créer un post ici, je poste les prénoms sur l'accueil du github,  sur l'addon ? c'est important de vous remercier mais je suis pas trop à l'aise avec ça, pour le moment vous êtes tous dans le readme, je trouve ça léger comme remerciement mais en même temps ont et pas sur du stream twitch xD donc des idées des envies dite moi tout.

Note: Vos nom de famille, email ou autre données sont toujours confidentiel. je poste uniquement Prénom première lettre du nom exemple. - Alain B.

**Comment by LordVenom** [comment]
Je sais pas si ça vous intéresse mais les dons n'ont jamais été touchés, il sont sur mon paypal, c'est compliquer c'est un addon open source mais c'est mon paypal donc si j'y touche c'est pour améliorer l'addon ou si ont me coupe le chauffage :) La somme total sans être ridicule ne permet pas d'être investie dans une structure qui pourrais servir à l'addon. 

Voila pour les grandes lignes merci a vous tous qui donner votre temps ou votre argent.

**Comment by TmpName** [comment]
Un post ici, pas tres utile, personne le verra, sur la page d'acceuil du github pour moi est une bne place.

Apres je trouve normal que les dons servent a quelques chose pour toi, acheter un yatch, une nouvelle villa, ect ..., si un jour y a besoin d'argent, tu auras tjours la possibilitéee de reinjecter l'argent.

Serieusement, on a rien a voir avec des projets qui brassent des milliers d'euros, les dons, c'est juste un remerciement pas un payment, il n'y a rien de financier la dedans vu les montants. Te prend pas la tete, c'est comme si pote te payait une biere, tu vas pas le noter pour la lui rembourser un jours.
Ne consideres pas ca comme de l'argent, ou alors je t'embauche pour ce "salaire".

**Comment by LordVenom** [comment]
heu.. l'esclavage c'est fini xD

**Comment by johnboisvert** [comment]
C'est ou qu'ont fais des dons?

**Comment by TmpName** [comment]
Page d'acceuil du github de Vstream, tout en bas.
