### ISSUE TITLE
hoster jwpcdn ?

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#1646]
salut
je tombe de plus en plus sur des stream comme ceci : 
(après une redirection belike)  [belik e.pw/play/wp-emb ed.p hp?url=dXBTS0tLbEVzTC9TNXdnd202SnpnK0Z5UWE4RG8zQVB5VWFuT3JRV0NHNWxXU2xUZTQ4VGVxSGthZnVaS2dXMHlMNjMzODZQNXdCVkI5RkFqbkdSUS9sOWxIWktpWGRXdCtnMFJUekJTUHZUWHpBdHlUMFhoTmE3S1o0K1JaSkw=]

une idée pour supporter ça dans vstream ?

**Comment by johngf** [comment]
déja resolve le meme genre sur [https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/papystreaming_org.py#L448](url)

**Comment by chataigne73** [comment]
@johngf    oui j'avais vu pour la redirection belike
le problème est après : mon lien belike conduit à une video hébergée chez jwpcdn.com, hoster non supporté par vstream

**Comment by johngf** [comment]
ce n'est pas un hoster mais surement un lien redirigé au final vers un hoster ou un lien codé
