### ISSUE TITLE
ZT toujours HS ( linux )

### ISSUE THREAD

**Issue by cnene7878** [Kodi-vStream/venom-xbmc-addons#1647]
Bonjour à tous, 
ZT ne fonctionne plus depuis 15 jours chez moi, sur un serveur NAS QNAP. ( base linux )
j'ai un message d'erreur "site DL protecte HS"
J'ai essayé avec Kodi 16 et Kodi 17 idem.
Par contre depuis mon téléphone Android tout fonctionne.
J'ai tout essayé rien n'y fait...
Si vous avez des idées ?!

**Comment by K3R0ZEN** [comment]
Désolé pas d'idée pour toi. Toutefois il semble que ZT soit HS depuis 20 minute environ. Impossible de valider quand je vais sur un lien ;)

**Comment by Arias800** [comment]
Apres le problème de DL protect si c est le même que avant ne provient pas de vstream essayé de passer a kodi 18

**Comment by Pack33** [comment]
J'ai eu le même problème et j'ai trouvé la solution. Le problème venait de l'addon url resolver.
Pour corriger, installe le fichier script.module.urlresolver-3.0.25.zip. Tu vas facilement le trouver soit sur un repository soit sur gogole en faisant une petite recherche. ;)

**Comment by cnene7878** [comment]
Merci pour l'info! je vais tester ça ce soir ;)

**Comment by cnene7878** [comment]
Toujours le même probleme malgré le changement de version d'Url résolver... 
Peut être lié à l'OS Linux. 
Toujours le message " erreur dl protecte HS".
Sur Windows et Android ça marche... J'ai beau désinstaller tout sur Linux pour le réinstaller mais toujours pareil. 
Je désespère !

**Comment by cnene7878** [comment]
Voici le log avec les erreurs
[kodi.log.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1309192/kodi.log.txt)
