### ISSUE TITLE
Problème Recherche vStream

### ISSUE THREAD

**Issue by ReikoIX** [Kodi-vStream/venom-xbmc-addons#1648]
Bonjour à tous,
Je ne sais si c'est le lieu ou l'endroit mais je rencontre un problème depuis quelques temps.
Il me semble que depuis la version 17.4 de Kodi, la fonction recherche dans vStream ne fonctionne plus.
Je l'utilise sous une box Android et sous un pc.
Je n'ai touché à aucun paramètre car avec le peu de connaissances que j'ai, j'ai peur de faire une connerie.

Donc, quand je recherche un film, ça mouline et ne m'affiche aucun résultat.
Par contre, si je me balade dans les sous menus (films, séries, etc...), je peux accéder aux liens des sources sans problèmes.

Y a t il un paramètre à modifier !? Un pbm avec Kodi !?

Amenez du feu à ma lanterne s'il vous plaît, elle s'est éteinte :-(

Merci d'avance,

Julien

**Comment by LordVenom** [comment]
Bonsoir, Quelle recherche ? un log peux être ?, pas de soucis chez moi avec Kodi 17.4
