### ISSUE TITLE
Vstream HS ?

### ISSUE THREAD

**Issue by K3R0ZEN** [Kodi-vStream/venom-xbmc-addons#1649]
Bonsoir les z'amis,

Chez vous aussi aucun lien ne s'ouvre ? Sur ZT aucun pour moi et sur Kepliz j'en ai tester une dizaine et quenini.

**Comment by LordVenom** [comment]
Kepliz pas de soucis, Zones-telechargement.ws HS chez moi aussi.

**Comment by chataigne73** [comment]
ZT a changé son domaine de site dlprotect ; je viens de mettre un correctif à jour dans la beta

**Comment by K3R0ZEN** [comment]
Merci chataigne, Malgré la modif réaliser manuellement ZT est devenu complètement inaccessible chez moi. Je m'y suis peut être mal pris ..

**Comment by michellemikor84** [comment]
Bonjour à tous,
J'ai le même problème impossible de lire sur Zt.
Dois-je attendre la mise à jour ?
J'aimerais aussi savoir comment faire pour voir si j'ai la beta ?
Merci bcp

**Comment by Pack33** [comment]
En attendant la prochaine mise à jour, vous pouvez aller sur ddl-island ou films streaming V2 avec les liens uptobox en attendant c'est nikel ;) Merci encore à la team pour son boulot ^^

**Comment by frankmandude** [comment]
Zones-telechargement.ws  fonctionne avec nouveau beta merci chataigne73

**Comment by LordVenom** [comment]
Oui c'est résolut.

**Comment by psykotropz** [comment]
Hello

On peut récupérer la beta via le repo?

**Comment by K3R0ZEN** [comment]
Merci pour la réactivité les mecs. Tout fonctionne. Bonne soirée

**Comment by Pack33** [comment]
Impeccable, mise à jour effectuée, tout fonctionne notamment ZT 😁👍

**Comment by psykotropz** [comment]
J'ai fait une mise a jour de Vstream et réinstallé depuis le repo, mais je n’arrive toujours pas à accéder aux liens sur ZT.
Je suis sur OSMC

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour

**Comment by michellemikor84** [comment]
Bon et bien j'attendrai la mise à jour demain.
Par contre petite question je suis sur 1fichier premium et mon abonnement va bientôt se terminer que me conseillez-vous ? Rester chez 1fichier ou uptobox ?
Merci pour vos réponses

**Comment by K3R0ZEN** [comment]
Salut, je te conseille vivement de prendre un abonnement sur Alldebrid, pour 8,99€ tu as 90 jours. Alldebrid te débride tout les liens , uptobox , 1fichier , openload et j'en passe, c'est en faite un débrideure universel.

Il te suffit juste de rentrer tes identifiants dans l'URLresolver de kodi que Vstream prend parfaitement en charge, c'est comme si tu avait pris un abonnement chez chaque hébergeur pour 20 fois moins chère. 2 ans que j'utilise se systéme en j'en suis ravie. 

@+

**Comment by michellemikor84** [comment]
Merci beaucoup pour le renseignement et contente de voir que je ne suis pas la seule fille ici.
A bientôt.

**Comment by LordVenom** [comment]
Aucun, avec un peux de temps pour bien te faire une idée des sites et des hosts, tu trouveras quasiment toujours ton bonheur sans utiliser de lien uptobox, debrid ou autre.

**Comment by K3R0ZEN** [comment]
En faite je ne suis qu'un homme qui a fait une merveilleuse faute d'orthographe "lol" 

Mais derien

**Comment by Pack33** [comment]
Il y a souvent des offres promos (exemple je suis uptobox premium pour 10€ par an). La qualité est toujours au RDV et les serveurs sont top ! Je lis les fichiers en direct en 1080p plutôt que de passer par l'uptostream, c'est plus rapide et de meilleure qualité ;)

**Comment by michellemikor84** [comment]
merci pour toutes vos réponses, je vais étudier la chose.

**Comment by michellemikor84** [comment]
Merci, merci beaucoup j'ai fait la mise à jour hier soir et super ZT refonctionne.
