### ISSUE TITLE
vstream recherche bloque sur french stream

### ISSUE THREAD

**Issue by svan1812** [Kodi-vStream/venom-xbmc-addons#1650]
Bj
J'utilise kodi 16.1 --> marche nickel
Mais deux jours, lorsque j'effectue une recherche sur vstream le moteur de recherche se bloque sur sur le serveur french-stream 
Que faire car meme kodi se bloque
Merci d'avance
Stéphane

**Comment by frankmandude** [comment]
moi aussi avec 17.4

**Comment by svan1812** [comment]
Il n'est pas possible de retirer cette source de la recherche ?
C'est surement la recherche d'infos sur le site qui bloque éphane
St

**Comment by frankmandude** [comment]
oui ca marcher merci svan1812

**Comment by svan1812** [comment]
Tu veux dire que vstream ne bloque plus ?

**Comment by TmpName** [comment]
Oui dans les parametres, tu peux desactiver cette source, sans problemes.

**Comment by frankmandude** [comment]
cool merci j'ai retire la source et ca fonctionne

**Comment by svan1812** [comment]
Dans les parametres  de vstream ? Comment je peux les atteindre ?

**Comment by svan1812** [comment]
ok cela fonctionne j'ai trouve le paramètre merci

**Comment by johnboisvert** [comment]
Mr LordVenom lors de la prochaine mise à jour aller vous suprimer ce lien qui fais geler a 25% lors des recherche svp ? :)

**Comment by LordVenom** [comment]
Oui chef

**Comment by razorex** [comment]
je viens de corriger le pattern de showMovies dans French-stream peut être est-ce du a ça le plantage de la recherche. French-stream tournait en boucle quand on entrait dans un menu film.
