### ISSUE TITLE
Echec de Lecture + 95% des liens non fonctionnels

### ISSUE THREAD

**Issue by Protyx** [Kodi-vStream/venom-xbmc-addons#1654]
Bonsoir à tous,

**Concerne FILMS & SERIES TV **

Est-il normal qu'il y aie que les lien Netu qui se lancent ? ( au détriment de gros problèmes de Buffering)

Pour toutes les autres sources, le cercle de charge apparaît  et après quelques instants le communiqué " Erreur de Lecture - Veuillez vérifier votre journal de logs pour plus d'informations apparaît ' Pour toutes les sources et tout les hébergeurs mis à part l'hébergeur "Netu" mais comme dit plus haut il à de gros problèmes de Buffering ...

Merci de régler se problème contraignant pour une si belle extension et la seul avec encore des Mises à jours régulières 

Screen(s)

![image](https://user-images.githubusercontent.com/31970463/30453196-59d171e8-9998-11e7-8503-73050f8178c6.png)
![image](https://user-images.githubusercontent.com/31970463/30453223-6e1bad8a-9998-11e7-9fc2-1973e148b1ac.png)
![image](https://user-images.githubusercontent.com/31970463/30453269-9d29c332-9998-11e7-984d-b52b0af54e42.png)

**Comment by LordVenom** [comment]
Bonjour, sur quel site ? 

pour avoir un vrais log : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by Protyx** [comment]
Rien ne marche à part Netu  sur tout les sites l'entierté des hébergeurs ne fonctionne plus sauf Netu

**Comment by LordVenom** [comment]
Désinstalle et réinstalle.

**Comment by Protyx** [comment]
Désinstaller - réinstaller déja fait, Cela ne change rien  je vais vous donner un log dans 2sec ;)

**Comment by Protyx** [comment]
Voilà https://slexy.org/view/S2U4Oi14Ve

Et ça fait ça partout sur 3 appareil différents, la version de Kodi et de l'extension est la même sur les 3 appareils

**Comment by LordVenom** [comment]
Je voie rien tu tester des liens HS donc forcement.

**Comment by Protyx** [comment]
Non car ça fait ça avec tout les liens ... ou dans la prochaine Maj faire un système qui n'affiche que les liens valides et non morts 
 Car teste de ton coté tu verra que il y a que le host Netu qui fonctionne ..
A moins que tu ailles une solution, je t'en serais gré que tu me la partage ^^

**Comment by Arias800** [comment]
Tu teste des lien youwatch et TOUT les liens youwatch sont mort ^^

**Comment by Protyx** [comment]
Tout est mort et c'est dommage car je regarde mes séries depuis 3 ans via Kodi et VStream et je n'ai pas envie de devoir retourné à la méthode de M.toutlemonde

**Comment by Arias800** [comment]
Apres il y a pleins d'autre hoster (openload , netu vidlox uptobox ... ) y a juste youwatch qui est mort

**Comment by Protyx** [comment]
Remonte les commentaire a mon premier commentaire & tu comprendra mon problème :)

**Comment by Arias800** [comment]
Essaye uptobox sur dll island et dit moi si ca marche car si ca marche pas le probleme vient de chez toi

**Comment by LordVenom** [comment]
Ce que je dit c'est qu'il me faut un log avec un test de lien valide, la pas de chance tu a tester des liens HS.

**Comment by Protyx** [comment]
Je te met ça ce soir ;-)

**Comment by Protyx** [comment]
Mort de Kodi de toute façon dommage, je clos ce sujet de discussion qui ne mènera à rien car le streaming est en train de mourrir malheureusement... :( Toujours le même problème, malgré les logs et les fouilles incessantes. Incapacité de lire un fichier Openload alors que l'on obtient la boîte de dialogue "Openload ok " dans le plugin Vstream ( voir screens)

**Comment by Protyx** [comment]
Atlasweb.net ne met  même plus ses liens pour dl les repo c'est bien la peine de ce casser le cul .. Les sites de streaming eux même ont pleins de liens mort.. Faites vos tests vous même montrer moi VOUS que ça fonctionne ! Ras le bol . A Bon entendeur !

**Comment by Protyx** [comment]
J'espère que vous me comprendrez . Marre de devoir chercher 3h après une source ou un host qui daignent bien aller... :)

**Comment by Protyx** [comment]
Tjs plein de liens qui ne fonctionne pas sur pleins de host sur divers sites ...

J'attend la MaJ mensuelle ...

Conseille : - Quand on recherche quelques chose , faite que cela s'affiche 1x par titre avec directement tout les liens disponible menant au média concerné et que cela soi que des fichier valides ainsi enlever les liens inutiles/ résiduel  offrant ainsi une recherche plus aisée

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/vStream-FAQ

**Comment by Protyx** [comment]
Toujours est-il que rien ne fonctionne chez moi sur PC avec Kodi 17.4 Raspberry Pi 3 Modele B et Portable avec Kodi 17.4 ...

**Comment by Protyx** [comment]
Et je suis certains d'être à jour car je l'ai installé depuis le Repository vstream 0.0.2
Et j'ai bien la version 0.5.4 de l'extension VStream 
De plus je viens d'effectuer la MaJ des liens qui s'effectue tout les 3 jours

**Comment by Protyx** [comment]
et toujours le même problème . 

Cela ne viens pas de ma connexion ou configuration Kodi car d'autres extensions sont bel et bien fonctionnelles à 100% et ne posent aucuns soucis (Buffering ou autre)...

**Comment by LordVenom** [comment]
Il nous faut le site et les liens que tu test afin de pouvoir recrée le bug chez nous pour pouvoir le réparer,

1 - Vérifier que le lien que tu teste fonctionne sur le site internet.
2 - Nous fournir un log du test et les informations du site et film tester

**Comment by mmtest1** [comment]
Bonjour,j'avais le même soucis c est derniers jours, presque tous les liens hs sauf sur Kaydo lien direct avec un problème de buffering important, coupure toutes les 30',je viens de resoudre le problème en mettant à jour urlresolver en version 4.... ainsi que f4mProxy (mais je pense pas que se soit lié au dernier), le depot de Eldorado's et Shani's étant HS  j'ai fait la mise à jour sur depot de Smash mais si quelqu'un a mieux je suis preneur.....
voilà......si ça peut aider ou être une piste

**Comment by Protyx** [comment]
mmtest1 

Peux-tu me mettre les repo's que tu as utilisé pour mettre à jour URLResolver vers la version 4 ainsi que F4MProxy s'il te plait bien? 

Toutes 2 sont-elles dispo sur Smash Repo ? :) 

En te remerciant ;)

**Comment by Protyx** [comment]
TROUVER - Problème résolu ! Merci à tous - Communauté au top 👍 👍 👍  - Merci à LordVenom pour cette superbe extension et ses collaborateurs !

**Comment by LordVenom** [comment]
Tu l'a résolu en mettant à jour URLResolver?, mais vous avez activer l'option "utiliser urlresolver" dans les options de vStream ? sinon je voie pas le rapport faut je regarde ça.

**Comment by Protyx** [comment]
J'ai installer F4MTester  et Maj URLResolver vers la version 4 ^^

**Comment by stevebou** [comment]
Bonjour, j'ai le même problème. Les seuls liens accessibles sont ceux de netu. URLResolver est mis à jour vers la version 4.
Avez-vous une autre piste pour résoudre le problème ?
Merci d'avance

**Comment by mmtest1** [comment]
@LordVenom je n utilise pas urlresolver dans les paramètre de l appli, je n ai de debrideurs mais la mise à jour de urlresolver et f4mproxy a resolu mon problème sans trop savoir pourquoi

**Comment by ttoto69** [comment]
Bonsoir
Je suis exactement dans le même cas pratiquement aucun lien ne fonctionne et voici un exemple d'erreur : 
` ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=Les+As+de+la+Jungle++%5BCOLOR+skyblue%5DOpenload+%2814%2F04%29%5B%2FCOLOR%5D&sHosterIdentifier=openload&sTitle=Les+As+de+la+Jungle++%5BCOLOR+skyblue%5DOpenload+%2814%2F04%29%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2Fopenload.co%2Fembed%2FTZ5A8xoEFmk%2F%22%2C%22%2F%2Fmystream.la%2Fexternal%2FEJNE6Y7G6K3E&sFav=play&sMediaUrl=https%3A%2F%2Fopenload.co%2Fembed%2FTZ5A8xoEFmk%2F%22%2C%22%2F%2Fmystream.la%2Fexternal%2FEJNE6Y7G6K3E&sCat=4&sId=cHosterGui&sFileName=Les+As+de+la+Jungle+]
`

J'ai réinstallé l'addons sans succes, j'ai mis à jour UrlResolver, mais rien non plus, par contre je n'ai pas installer F4Proxy je ne sais pas où le trouver ...

Merci d'avance, et good job pour cet addons

**Comment by ttoto69** [comment]
Suite à mon précédent commentaire j'ai également supprimer d'autres addons pensant qu'ils pouvaient interférer mais pas mieux.
Un truc bizarre c'est que avant avec Openload il y avait un message du genre "décodage en cours...ceci peut durer plusieurs minutes .." mais plus maintenant ...
En tout cas je confirme seuls Netu et les liens directs fonctionnent mais le reste est down

**Comment by Arias800** [comment]
Openl_ad.py vient d être mise a jour donc essaye de le mettre a jour manuellement ou attends quelque jour pour voir si ça ne règle pas le problème d openlo_d

**Comment by ttoto69** [comment]
@Arias800 je viens de test Openl_ad.py est ça semble ok, du coup j'ai testé également Str_amango et idem ça semble fonctionné pour le reste c'est down

**Comment by Arias800** [comment]
Et les reste c est quel hoster ?

**Comment by ttoto69** [comment]
Je viens de refaire une passe sur différents sites et voici les hosters down :
Fl_shX
Youw_tch
Vodl_cker
Spe_dvid
Upstr_am
Ok._u
W_tchers
The_ideo
Nowv_deo
Zstr_am

Sinon les sites pour lequels il y a un pb
Kaydo
Fil_ illi_ite
str_amase
stre_may

je n'ai pas tout testé

**Comment by LordVenom** [comment]
Je vais regarder mais tu as tester avec la bêta ? ou au moins la dernières mise a jour ?

**Comment by johngf** [comment]
-ok ru = fonctionne
-flash_x = réparé mais chez certaines personnes ou en fonction des heures nécessite de modifier le timeout
du advanced setting.xml de kodi a 60 secondes (voir sur google comment créer l' advanced settings.xml pour ceux qui ne savent pas)

**Comment by ttoto69** [comment]
@LordVenom Non je n'ai pas testé la bêta par contre comme mentionné j'ai updaté Openl_ad et Stre_mango
@johngf je vais tester en modifiant le setting et vous ferais un retour, pour ce qui est de ok_ru sur plusieurs site pour moi c'est down, mais je vais continuer à tester

**Comment by TmpName** [comment]
Uptostrm ok chez moi
Wtcher ok chez moi.
the vdo ok chez moi
Nowvdo ok chez moi.

**Comment by Arias800** [comment]
Uptostrm ok chez moi aussi ^^

**Comment by johngf** [comment]
spedd vid soucis packer j'ai mis une maj temporaire pour contourner

**Comment by TmpName** [comment]
Yep, je viens de la voir, dsl de tout te pourrir, j'etais sur la mienne en meme temps, et y a 2/3 details qui font que je prefere la mienne, apres le rollback est facile en cas de prb.

**Comment by johngf** [comment]
J'ai fait ça parceque unpack ne fonctionné pas avec les liens que j'ai testé 
Count et symtab de la librairie packer n'était pas = apparemment

**Comment by TmpName** [comment]
Yep, ils ont mit en place un truc a la con, il rajoutent '|mp4' a la fin de la chaine, du coup pour que ca fonctionne faut le retirer (sinon la chaine faisait un element de trop).

Dailymotion HS aussi, visible sur gumgum.

**Comment by johngf** [comment]
Chez moi daylimotion fonctionne

**Comment by ttoto69** [comment]
J'ai eu une maj aujourd'hui et il semble que beaucoup de sources soient de nouveaux actives
FilmIllimte ok
Openlo_d ok
RapidV_deo ok
Ok_ru ok
Fl_shx ok
... je n'ai pas tout testé mais ça semble ok pour moi

Par contre j'ai remarqué une anomalie sur Cinem_aVF : quelque soit l'élement qu'on clique dans a liste le Hoster sera le 1er de la liste : 
exemple si j'ai une liste avec le 1er item : Hoster = A, si je clique que le 5eme item le Hoster dans la page suivante ne sera pas E mais A.
Je ne sais pas si c'est bien clair :p

Merci pour votre job :) hyper efficace

**Comment by johngf** [comment]
now_video quelque chose d'oublier à l'intérieur du fichier causé l'erreur > fixé

**Comment by TmpName** [comment]
Exact, le source Cinema_vf a un prb, il y a toujours le meme lien en hoster.

**Comment by TmpName** [comment]
Cinema_vf ok, mais pas de MAJ avant la nouvelle version.

**Comment by ttoto69** [comment]
Bonsoir, Pour ma part pas de nouveau problème notable
Good Job :) à l'équipe
merci

**Comment by johngf** [comment]
Flash x c'est repartis avec la video des bulles.

**Comment by TmpName** [comment]
Lol, ha oui, mais c'est pas dur ca vient de la partie de code UnlockUrl()
M'en occupe dans la semaine si pas deja fait.
