### ISSUE TITLE
gum gum streamming

### ISSUE THREAD

**Issue by diouf76** [Kodi-vStream/venom-xbmc-addons#1659]
Le .py du site ne marche plus?

Est ce du au cloud protection?

Merci de vos réponses.

**Comment by LordVenom** [comment]
Oui mort pour le moment, mais la vas falloir de la patience, perso c'est hors de mes compétences.

**Comment by diouf76** [comment]
Ok au moins c'est clair.

**Comment by TmpName** [comment]
Remarche a ce jours.

**Comment by diouf76** [comment]
Ok je teste

**Comment by johngf** [comment]
il y a un problème avec la lib cloudflare top replay hs a l'instant

**Comment by diouf76** [comment]
Ok,  par contre John uptobox2. py  ne marche plus sur vstream, peux tu m'aider ?

**Comment by TmpName** [comment]
TopReply ok, c'etait l'adresse du serveur qui avait changé, donc il renvoyait un message de redirection non gere par le code de clouflar.

**Comment by johngf** [comment]
sur gum gum la dernière fois c'était cloudflare a chaque clique ou presque du coup page vide

**Comment by TmpName** [comment]
Mais la plus moyen de tester. Et cette protection est rarement activee longtemps, faut vraiement arriver au bon moment.
Si je le teste sur TopRply (ou la protection est encore activée) ca passe.
