### ISSUE TITLE
Problème mise à jour Vstream

### ISSUE THREAD

**Issue by reds07** [Kodi-vStream/venom-xbmc-addons#1660]
Salut à tous,

J'ai 2 box et un pc, quand jallume la première box j'obtiens directement la mise à jour ( celle qui règle les souci avec Zone téléchargement), j'allume ensuite mon pc, idem directe la mise à jour est demandé, mais quand j'allume la 3 ieme box ( la plus importante et la plus utilisée) il ne se passe rien.

J'ai beau effacer le cache, réinstaller l'application depuis le dépository, avancé la date, il ne me propose rien depuis 2 jours, et ces comme sa à chaque mise à jour. Pourtant les box son identique.

Quelqu'un a une idée pour m'éclairer.

**Comment by alex83100** [comment]
Bonjour, je profite de ce post sur les mises à jours. 
Pour ma part elles se passent correctement, je voulais juste savoir si il était possible de les lancer sans la validation de l'utilisateur et en arrière plan et sans validation à la fin.

Je m'explique : je vais toujours sur les mêmes liens de Vstream, directement la plupart du temps pour regarder par exemple les films récents d'un site. 

La plupart des skins proposent de pouvoir accéder à des favoris, j'ai donc rajouter sur ma page principale de kodi le lien qui m’intéresse et il m'arrive souvent de ne pas faire attention au mises à jour.  

Il y a -il donc pas la possibilité en ajoutant un paramètre dans la configuration de VSTREAM de forcer les mises à jour si l'option est coché, ou de laisser comme actuellement le choix de les lancer.

Par avance merci

**Comment by TmpName** [comment]
Nope ^^, ca aussi c'est fait expres.
On est heberge par github qui propose tout ses services, gratos et sans pubs, donc on veut eviter que trop de personnes se connectent pour faire de simple MAJ en meme temps (beaucoup de traffic pas forcement utile).
En fait les MAJ des fichiers ne sont pas toujours utiles, si tout fonctionne chez toi tu n'en a pas besoin, quand ca deconne jete un oeuil pour voir si il y a une MAJ proposée.
