### ISSUE TITLE
Problème générale 

### ISSUE THREAD

**Issue by xtreamer31** [Kodi-vStream/venom-xbmc-addons#1661]
Bonjour,

Films streaming v2 ne fonctionne plus j'ai essayer sur plusieurs support  ( os android tv , smartphone et box android ) tous mis à jour.
Sur films illimités, on plus accès aux pages suivantes comme auparavant, une seul page de films est disponible.
Concernant la liste des sites pour les films HD, il me semble que la liste a diminuer, il y a une dizaine de sites disponible. 
Le plus gros manque c'est films illimités et films streaming v2 ..

Merci .

**Comment by LordVenom** [comment]
Houla Merci, ont regarde ça.

**Comment by xtreamer31** [comment]
Merci à vous et bon couŕage

**Comment by Arias800** [comment]
Kaydo a eu pas mal de problème notamment avec des crash ou ce genre de chose donc le problème ne vient  pas de nous
French-stream bug connu en cours de resolution

**Comment by xtreamer31** [comment]
Tout à fait j'ai utilisé kaydo hier soir et au trois quarts du film, celui-ci a craché depuis ke serveur lien direct , il a fallu relancer le film et avancer le curseur, sinon la qualité est au rendez-vous

**Comment by chataigne73** [comment]
j'ai corrigé le problème du nextpage sur film-illimit

concernant filmstreamingv2, en effet le site est down donc on ne peut rien faire
concernant plus de streaming en HD je vais prochainement ajouter 2 autres sites

sinon c'est vrai qu'on aurait besoin de faire un grand ménage dans les sites : il y en a trop et souvent de médiocre qualité
il faudrait aussi qu'on réfléchisse à un moyen de checker les liens mort

**Comment by Arias800** [comment]
Pour checker les lien mort pourquoi faire une regex qui verfirai si il y'a un message comme "file notre found" ou "404"

**Comment by LordVenom** [comment]
Voir https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/vStream-FAQ

**Comment by razorex** [comment]
French-stream j'ai fais une correction du regex récemment.

**Comment by xtreamer31** [comment]
La tv replay ( buzmonclick ) plus de liens serveurs dans les dossiers sur télé-réalité par exemple ..

**Comment by razorex** [comment]
Pour Kepliz c'est normal que tu ai que 51 liens c'est la page d’accueil pas de nextpage. j'ai tout de même fais une correction j'ai supprimer le menu view et rajouter le menu MOVIE_MOVIE dans "load".
