### ISSUE TITLE
Ianime vide

### ISSUE THREAD

**Issue by Fullpom** [Kodi-vStream/venom-xbmc-addons#1662]
Il ne ressort plus aucune source sur Ianime, pourtant il y a bien l'arborescence et le site est accessible via un navigateur mais rien ou plutôt "..."
Ps: J'ai testé sur plusieurs appareils depuis plusieurs endroits

**Comment by johngf** [comment]
ok a testé

**Comment by Fullpom** [comment]
Pour l'instant je ne vois pas d'évolution mais il faut sûrement que je patiente surtout que j'utilise kodi sur Android/AndroidTv.

**Comment by Fullpom** [comment]
Bonjour, pb toujours présent...😔

**Comment by TmpName** [comment]
Y a une nouvelle version sortie hier qui doit corriger, enfn chez moi c'est reparti.

**Comment by Fullpom** [comment]
Chez moi aussi. Merci à tous, Vstream est génial 😉
