### ISSUE TITLE
Openload problem

### ISSUE THREAD

**Issue by NizarAloui** [Kodi-vStream/venom-xbmc-addons#1663]
Openload hoster is no longer working, there is a problem fetching final video link.

**Comment by johngf** [comment]
Fixed.

**Comment by xtreamer31** [comment]
+1 no work for all link  

In french: les liens serveurs openloads ne se lance plus dans mon utilisation HD c'est films illimité qui est gêne le plus 

Merci

**Comment by LordVenom** [comment]
Voir :  https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour

Patience xD
