### ISSUE TITLE
À propos des bandes annonces

### ISSUE THREAD

**Issue by fredo04** [Kodi-vStream/venom-xbmc-addons#1664]
Slt tout le monde.
J'ai vu que maintenant les bandes annonces passent par l'API de youtube et que la modification a était mise en ligne.
Je la prend ou la modification ?
J'ai un peut fouiner sur le site et j'ai pris le gui.py ici---->https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/gui.py

J'ai bon ?
Si oui y a un souci car les bandes annonces se lancent toujours pas.

**Comment by Arias800** [comment]
C est le fichier bâ.py

**Comment by fredo04** [comment]
Nickel ça marche, merci.
Toujours un bonheur la réactivité de la communauté vstream, ne changez rien.
