### ISSUE TITLE
problème ZT et kodi 16.1 

### ISSUE THREAD

**Issue by baillou861** [Kodi-vStream/venom-xbmc-addons#1666]
bonjour 
de puis quelque semaine je n arrive plus a utilisé ZT car ca me notifi toujours que dl protec est HS je suis sur la derniere version de vstream et est meme fait une mise a jour manuel du fichier site de ZT .
Merci de votre aides.

**Comment by Arias800** [comment]
Problème rependu regarde dans les issue closes voir si il y a rien qui peut t aider

**Comment by damev** [comment]
Résolu en passant à kodi 17.1. Tout simplement.
