### ISSUE TITLE
Streamango

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1667]
Quelqu'un peut corriger le host moi je vois pas que faire avec çà
 le link c'est un truc du genre 
hosterurl + `'c+DNOJ3bJaLfMqjRcqzRMeDKc6wRMp3QNaHPJ6vTMqDMJqvcM5IPed=KdN=Kdt0KQt3fdN8GJ64PdNYGQrXsFq32DsLZc90KfQAA'`
`{type:"video/mp4",src:d('c+DNOJ3bJaLfMqjRcqzRMeDKc6wRMp3QNaHPJ6vTMqDMJqvcM5IPed=KdN=Kdt0KQt3fdN8GJ64PdNYGQrXsFq32DsLZc90KfQAA',191)`

**Comment by LordVenom** [comment]
Il utilise une grosse librairie Js pour coder ça, Urlresolver 4.0.05 peux le résoudre pas vStream.

https://github.com/jsergio123/script.module.urlresolver

**Comment by johngf** [comment]
ok pour le moment mais je pense il vont faire comme opl puis se lasser

**Comment by razorex** [comment]
euh non c'est dans le hoster de streamango
il fut prendre sHosterUrl et y rajouter ce qu'il y a entre les `'` `'`
donc si je suis assez clair 
sHosterUrl + `'c+DNOJ3bJaLfMqjRcqzRMeDKc6wRMp3QNaHPJ6vTMqDMJqvcM5IPed=KdN=Kdt0KQt3fdN8GJ64PdNYGQrXsFq32DsLZc90KfQAA'`

**Comment by johngf** [comment]
ça fonctionne avec le fichier modif hier sur la beta

**Comment by razorex** [comment]
oui c'est bon çà fonctionne.
