### ISSUE TITLE
Problème Vstream liens ?

### ISSUE THREAD

**Issue by ryan1308** [Kodi-vStream/venom-xbmc-addons#1668]
Bonsoir à tous, 

Je tenais dans un premier temps à remercier les artisans de cette extension qui nous a changé la vie, il faut le dire. Et malheureusement il est de coutume que les gens viennent se plaindre de tel ou tel bug en oubliant que derrière ce genre de projets il y a des gens investis. Merci à vous. 

Cela étant dit, est-il normal que plus aucun lien ne fonctionne sur Vstream ?

Merci d'avance pour votre réponse.

**Comment by LordVenom** [comment]
Bonsoir, Voir https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1654
