### ISSUE TITLE
FILM ILLIMITÉ  ( HD)

### ISSUE THREAD

**Issue by xtreamer31** [Kodi-vStream/venom-xbmc-addons#1669]
Bonsoir, tout dabord merci à toute la team Vstream. 

Me concernant beaucoup de liens ne fonctionne plus sur beaucoup de site, le pire de tout  se sont les links serveurs openloads qui sont carrément hors service et sur films illimités nous avons toujours accès à une seul page, impossible de faire suivant comme auparavant et ceux malgré la mise à jour de ce soir.
Seul les serveurs Netu fonctionne dans film illimité et en plus il crash en plein films exactement comme kaydo mais en pire, car impossible à relancer par la suite .. ou bien en insistant le film lag en continu, obligé de faire une recherche manuel afin de trouver le film ailleurs pour continuer le film. 

La solution d'un debrideur universel communautaire ne serait-il pas la solution, au lieu de payer 8€ par personnes pour 3 mois sur alldebride, on pourrait voir pour une solution globale vstream a moindre coût, je suis prêt à participer de quelques euros. Beaucoup de torrent fonctionne avec les dons pour payer les serveurs. Je connais pas le nombres d'utilisateurs mais cela pourrait être la solution, car beaucoup sont néophyte et je vois mal ces personnes prendre un debrideur et paramétrer kodi .. A moins qu'il n'y ai pas besoin de debrideur et que les problème viennent de autre chose  ( référencement ?).
Mon utilisation est assez récente sur le streaming,  je sais que tot ou tard il faudra s'équiper de vpn, cela pas forcément pour masquer son ip mais plutôt pour passer au travers du bridage de débit  du streaming ou bien encore cela servira certainement à débloquer le blacklistage des liens de streaming en passant par un serveur vpn â l'étranger. . Ou encore comme pour les torrents, masquer son ip avec cryptage de donnée. .
Mais on est pas encore là dieu merci. 
Merci pour temps

**Comment by LordVenom** [comment]
Bonsoir, Le monde du libre est cruel pour les programmeurs si plus rien ne fonctionne tous le monde ce tourneras vers d'autre solution et voila. 

Pour ceux qui est des protections, ça vas ça vient comme les serveurs de stream. J'ai aussi remarquer des périodes ou les serveurs font le ménages et réajuste leurs sécurités mais dans l'ensemble vue le nombre de source et d'hébergeur que supporte vStream y a pas de soucis a ce faire sur une pénurie de films, séries xD. Pour les hosts vous pouvez activer URLResolver pour tester.

**Comment by xtreamer31** [comment]
Merci de ton retour Venom 😊

**Comment by johngf** [comment]
des fichiers ont été mis a jour chez moi c'est ok avec la beta sur 4 hébergeur vu 4 ok il faut attendre la prochaine maj ou bidouillé les fichiers soit même >> copier coller
