### ISSUE TITLE
pb MAJ vers 0.5.4 sur tél android

### ISSUE THREAD

**Issue by jackouille2** [Kodi-vStream/venom-xbmc-addons#1670]
bonjour,
j'ai Kodi 17 installé sur un tél Samsung J3 android avec le plugin Vstream 0.4.3
bien sur il voit une MAJ vers la 0.5.4 mais celle-ci ne se fait pas en auto, même si je la lance en manuel
cela vient de la MAJ qui n'est pas compatible avec mon tél ou autre chose ?

**Comment by LordVenom** [comment]
Installer directement le zip

**Comment by jackouille2** [comment]
merci j'ai réussi en installant d'abord le repositery puis l'extension vstream à partir du repositery
