### ISSUE TITLE
Vstream et les bandes annonces

### ISSUE THREAD

**Issue by lilou2** [Kodi-vStream/venom-xbmc-addons#1673]
Bonjour 
je possede une box beelink gt1 ultimate avec kodi 17.4  vstream 0.54 et les bandes annonces ne s ouvre plus et la recherche similaire n y est plus .

Est il possible de les reactivés ?

Merci par avance

**Comment by LordVenom** [comment]
C'est fait mais dispo à la prochaine mise a jour, fin de semaine prochaine si tous vas bien. Par contre la recherche similaire pour le moment est désactivé.

**Comment by lilou2** [comment]
Super!!!!!
Merci pour ta reponse 
Plus qu a attendre .
