### ISSUE TITLE
Adresse de la source actuelle pour installer vStream

### ISSUE THREAD

**Issue by Groddur** [Kodi-vStream/venom-xbmc-addons#1674]
Bonjour,

Voilà des heures que je tente en vain d'installer la dernière version de vStream sur Kodi qui est sur la Recalbox de mon Raspberry.
En suivant des tuto vidéo, je suis passé par le mirror superrepo, mais dans vStream Repository la partition Extensions Vidéo (qui devrait contenir vStream) est vide.
Auriez-vous svp une adresse viable (à taper dans Système - Fichier - Ajouter une Source) qui me permette d'installer vStream ?
Je suis perdu ! Merci de votre aide.

**Comment by Arias800** [comment]
Voila le repo officiel https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository

**Comment by LordVenom** [comment]
Ca fonctionne pas par url, mais par le téléchargement du zip je regarde si je peux faire un truc Officiel mais c'est pas gagné vu que j'utilise github.

**Comment by Groddur** [comment]
Merci de vos réponses. 
Dans le lien que vous m'indiquez il y a ça :
repository.vstream-0.0.2.zip 
Source code (zip) 
Source code (tar.gz) 
Que dois-je faire avec ça ? Je dois les "installer depuis un fichier zip" ?
Désolé je suis un parfait noob

**Comment by LordVenom** [comment]
Alors Vite fait pas forcement bien fait lol

https://kodi-vstream.000webhostapp.com/repo/

**Comment by Groddur** [comment]
J'ai suivi le tuto avec ton url. Mais ça ne marche pas :
Quand je suis dans Extensions-Installer depuis le dépôt-vStream Repository, dans Extensions Vidéo il n'y a pas de fichier vStream

**Comment by LordVenom** [comment]
Tu as bien activer les sources inconnue j'ai tester ça fonctionne chez moi.

![image](https://user-images.githubusercontent.com/4380112/30773312-b98420a4-a06e-11e7-9fc0-c8812b4e6dc7.png)

**Comment by Groddur** [comment]
Je n'ai pas ce curseur (j'ai Kodi 15.2)
Dans les paramètres avancés j'ai 
Sortie vidéo
Sortie audio
Périphériques
Accès Internet
Gestion de l'Energie
Débogage
Verrouillage administrateur / Verrouillage administrateur

**Comment by LordVenom** [comment]
Houla version 15.2 officiellement plus supporter.

Teste avec le zip direct mais c'est pas dit que ça fonctionne.

Installer depuis un fichier zip et 

https://github.com/Kodi-vStream/venom-xbmc-addons/releases/download/v0.5.4/plugin.video.vstream-0.5.4.zip

**Comment by Groddur** [comment]
Le journal des modifications m'indique : "le dépôt indique que cette extension est incompatible ou inutilisable"...
Bon je crois que c'est foutu.
Aurais-tu une version antérieure qui fonctionne sur mon Kodi stp ?

**Comment by Arias800** [comment]
Voila la liste des version https://github.com/Kodi-vStream/venom-xbmc-addons/releases/ essaye celle avant la 5.0

**Comment by Groddur** [comment]
Merci à vous, finalement j'ai réinstallé la version ancienne.
