### ISSUE TITLE
Nouveau Site pour vStream !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1679]
Bonjour,
En cherchant sur internet pour avoir des Films, je suis tomber sur le Site "Zone Mania". 
J'ai tester ce site et il est bien. Est possible de l'avoir dans vStream pour avoir de nouveaux films à regarder s'il vous plait ? Adresse du site : zo ne-mania.co m

Cordialement,
Luluvulcain

**Comment by liberodark** [comment]
Oui j'avoue mais aussi on pourrait ajouter : https://www.extreme-down.one
Qui est aussi un gros site comme zone téléchargement.

Cordialement

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/517
