### ISSUE TITLE
Échec installation

### ISSUE THREAD

**Issue by Hardrocktom** [Kodi-vStream/venom-xbmc-addons#1680]
Bonjour j'ai dl le dernier zip et j'ai un échec lors de l'installation. (Kodi 17.4 et sources inconnues autorisées). Merci d'avance.

**Comment by JeromeDesseaux** [comment]
+1. Même problème chez moi. Kodi 17.4 sur Raspberry pi 3 et LibreElec.

**Comment by TmpName** [comment]
C'est bien le zip du repositary que vous essayez ?
Il y a marque quoi dans le message d'erreur ?

**Comment by JeromeDesseaux** [comment]
Le zip du repo s'installe bien (du moins chez moi). C'est lorsque j'essaie d'installer vstream depuis le dépôt que ça ne fonctionne pas. J'ai une erreur de dépendance impossible à installer ou à trouver (je ne suis pas chez moi, je ne peux pas être plus précis). 

Visiblement, c'est un problème assez récurrent que j'ai déjà croisé sur Google au fil de quelques recherches. 

Par contre, pas de solutions concrète :/

**Comment by TmpName** [comment]
La liste des dependances est ici https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Liste-des-d%C3%A9pendances

C'est laquelle qu'il manque ? A mon avis UrlResolver vu qu'il n'est plus officiel depuis pas mal de version.

**Comment by JeromeDesseaux** [comment]
Du coup, sans même passer par chez moi : c'est quoi la solution? Si cette dépendance n'est plus officielle, il faudrait la rajouter au dépôt. Sinon vstream va devenir obsolète et personne ne pourra l'installer sur les supports à venir. 

Une manip ?

**Comment by JeromeDesseaux** [comment]
J'ai eu ma réponse en regardant ce midi les détails du  pourquoi ça ne s'installe pas. Peut-être que ça servira à d'autres :
- C'était le package "Common cache plugin" qui n'arrivait pas à s'installer. Alors j'ai cherché pourquoi et j'ai vu que c'était un package de base de Kodi. J'ai essayé de l'installer mais en fait, j'avais deux versions dans deux dépôts différents : Kodi et un autre dépôt d'une extension Kodi.
- Le problème était donc un souci d'incohérence entre les paquets
- J'ai installé manuellement le package depuis le dépôt officiel Kodi et l'installation a fonctionné sans problème par la suite. 

Très bonne extension par ailleurs! Je ne connaissais pas avant hier mais c'est vraiment prometteur. Un système permettant de vérifier les liens morts automatiquement serait vraiment un plus. Mais on s'en sort en essayant plusieurs liens de plusieurs plateformes :) 

Bon courage pour le développement et la suite :) en espérant que cette remarque puisse servir à d'autres

**Comment by TmpName** [comment]
On va essayer de s'en souvenir cette fois,^^, mais la plupart tournent sous windows donc pas eu ce probleme.
Pour la detection de lien mort, c'est possible, mais avec l'habitude l'humain est plus rapide que la machine.

**Comment by Hardrocktom** [comment]
Bonjour,

Pour ma part, la réinstallation du package Common cache plugin n'a pas résolu le problème d'installation de vstream. Est-ce autre chose ?

Merci d'avance.

**Comment by LordVenom** [comment]
A tu vérifier la liste des dépendances ? quel message d'erreur ?

**Comment by Hardrocktom** [comment]
Pour être franc je ne maîtrise pas encore bien Kodi ^^"... J'ai ajouter Log Viewer pour avoir l'erreur lors de l'installation et je n'ai qu'une ligne : "ERROR: GetDirectory - Error getting zip://%2fmedia%...repository.vstream-0.0.2.zip/

Sinon je n'arrive pas à voir le problème car le popup d'erreur disparait avant la fin du message.

**Comment by LordVenom** [comment]
Hum.. ça m'aide pas.Tu est sure de ta manip et du dossier du zip ?

**Comment by Hardrocktom** [comment]
Oui j'ai dl le zip "repository.vstream-0.0.2.zip" et je l'exécute classiquement, comme d'autres dépôts que j'ai déjà installés précédemment qui ont fonctionné. Comment puis-je voir cette liste de dépendance ?

**Comment by Hardrocktom** [comment]
Merci. Ou puis-je trouver xbmc python ? Toutes les dépendances viennent d'être installées sinon.

**Comment by LordVenom** [comment]
C'est inclus à Kodi ça.

**Comment by Hardrocktom** [comment]
Du coup j'ai toujours l'erreur d'installation.

**Comment by Hardrocktom** [comment]
Je peux le voir comment ce log ?

**Comment by LordVenom** [comment]
Avec un éditeur de text. Bloc note ou autre.

**Comment by Hardrocktom** [comment]
Oui mais depuis Kodi est-ce possible ?

**Comment by LordVenom** [comment]
Pas que je sache.

**Comment by Hardrocktom** [comment]
Du coup j'ai pas ces infos :/

**Comment by LordVenom** [comment]
Ha mince tu est sur quel machine ? tu as tester de re-télécharger le zip ?

https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository

**Comment by Hardrocktom** [comment]
Je suis sur RPI3. Mais cest bon :) je viens de dl à nouveau le zip et l'installation s'est correctement effectuée. Je navigue dessus pour voir si tout passe bien.

**Comment by LordVenom** [comment]
Ha tu avais pris le zip ailleur que chez nous ?

**Comment by Hardrocktom** [comment]
Bon... C'est plutôt particulier comme fonctionnement. Par exemple j'ai fais un test en cherchant un épisode des Simpsons ^^. Je vais sur recherche visuelle > genre > animation > Les Simpsons > (exemple) saison 3 > épisode 5... Et là il me sort pleins de sites et d'autres catégories de Simpsons etc (où la plupart ne fonctionnent pas) est-ce un problème de paramétrage ?

**Comment by Hardrocktom** [comment]
Et non non je l'avais pris ici pourtant oO

**Comment by LordVenom** [comment]
Prend le temps de le prendre en main avant de poser des questions multiple stp Pour nous retourner un site HS fait un nouveaux Post merci.

Note je fait le nettoyage du post.
