### ISSUE TITLE
zt + 1fichier

### ISSUE THREAD

**Issue by thorsten68** [Kodi-vStream/venom-xbmc-addons#1681]
Bonjour. Je suis nouveau ici, je n'arrive pas a utiliser les liens 1 fichier dans vstream sur box Android. J'ai pourtant un premium, ça affiche authentification réussi, début telech, arrêt telech.
J'ai testé un autre lien uptobox (épisode de série) ça fonctionnait. Y'a t il des paramétrages a faire sur son compte 1fichier ?
Merci d'avance

**Comment by thorsten68** [comment]
P.s : j'ai la dernière version de kodi et de vstream et j'ai essayé avec et sans SSL dans les paramètres 1fichier

**Comment by thorsten68** [comment]
Idem en lecture streaming , ça affiche résolve, authentification réussi puis plus rien

**Comment by TmpName** [comment]
Pas de prb de mon cote, mais j'ai un compte gratuit.
Quelqu'un d'autre a teste ?

**Comment by thorsten68** [comment]
Sans aucun réglage particulier ? Le change le type de lecteur dans les options kodi ou tu laisses celui par défaut ?

**Comment by thorsten68** [comment]
De toute façon mon problème doit venir d'1fichier vu qu'avec uptobox ça fonctionne (y compris en téléchargement). L'authentification passe aussi, du coup je sais plus ou chercher

**Comment by TmpName** [comment]
Tu as quoi comme infos dans les logs ?

**Comment by thorsten68** [comment]
Je te met ça dans l'après-midi

**Comment by thorsten68** [comment]
Rien d'affiché  dans le journal d'événements :-(

**Comment by yas06** [comment]
salut j utilise aussi 1fichier effectivement ce week ca bloquer mais g un compte gratuit g réinitialiser mon compte  et ca refonctionne pour moi

**Comment by thorsten68** [comment]
Cad réinitialiser ton compte ?

**Comment by yas06** [comment]
ben en faite comme c un compte gratuit j en ai refait un de compte  j avais plus de credit cdn

**Comment by thorsten68** [comment]
Faut utiliser son compte cdn pour faire ça même en premium ? C'était décoché chez moi. J'ai coché (j'ai du crédit a gogo) et réessayé sans succès :-(

**Comment by thorsten68** [comment]
A nouveau essayé sur uptobo x avec un fichier de 1,4go sans soucis. Alors qu'impossible  avec 1 fichier

**Comment by TmpName** [comment]
Et sa marche si tu passes par un navigateur web ?
Et il nous faut vraiment le log, il y a moyen d'augmenter les infos ecrites dedans, mais deja la base ca aiderait.

**Comment by thorsten68** [comment]
Sur le PC ça marche. Sur le navigateur de la box j'ai jamais essayé. Le log je le trouve ou ? Dans le journal de kodi ou dans les paramètres de vstream ?
Dans le journal de kodi y'a rien malgré des modifs du niveau d'ecriture.

**Comment by TmpName** [comment]
Dossier log https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log
Parfois ca ca marche https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

Tu peux envoyer le log tel quel, et si vraiment on y voit rien, dans les option de kodi tu peux activer le mode debug, et la ca va remplir le log mais pas sur que ce soit utile.

**Comment by thorsten68** [comment]
OK merci, je vais utiliser upload kodi log. Je mettrais ça demain. Merci pour votre patience... On va y arriver...

**Comment by thorsten68** [comment]
17:45:46.894 T:18446744071924012416  NOTICE:    [PLUGIN] Vstream: Table initialized
17:45:51.770 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: SQLITE 3 as DB engine
17:45:51.794 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: load site cDownload and call function AddtoDownloadList
17:45:51.982 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: Telechargement https://1fichier.com/?ed8doxh3dq
17:45:57.672 T:18446744072444038656 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://FREEBOX/Toshiba%201To/film%20HD/1
17:45:57.997 T:18446744071864357888 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://FREEBOX/Toshiba%201To/film%20HD/spiderman%20homecoming.flv
17:45:58.004 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: Rajout en liste de telechargement https://1fichier.com/?ed8doxh3dq
17:45:58.026 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: SQL INSERT download Successfully
17:45:58.215 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: Utilise compte premium pour hoster onefichier
17:45:58.432 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: Auhentification reussie
17:45:58.433 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: https://1fichier.com/?ed8doxh3dq|Cookie=SID=hvakqUp8gafTsl=S6DlsoEdwFAjpvK3w4=6Nb3Opp=hgHmAi5QTQBVhAAZIDHteW;
17:45:58.434 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: Telechargement https://1fichier.com/?ed8doxh3dq|Cookie=SID=hvakqUp8gafTsl=S6DlsoEdwFAjpvK3w4=6Nb3Opp=hgHmAi5QTQBVhAAZIDHteW;
17:45:58.441 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: Telechargement ok
17:45:58.476 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: smb://FREEBOX/Toshiba 1To/film HD/spiderman homecoming.flv
17:45:58.487 T:18446744071864357888  NOTICE:    [PLUGIN] Vstream: Table initialized
17:45:58.779 T:18446744071867820288 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://FREEBOX/Toshiba%201To/film%20HD/spiderman%20homecoming.flv
17:46:16.515 T:18446744071864359168 WARNING: CPythonInvoker(14): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
17:47:33.144 T:18446744072444038656  NOTICE: Samba is idle. Closing the remaining connections
17:48:30.269 T:18446744072444040576  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
17:48:30.272 T:18446744072444040576  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 28224 m_frames: 1764 m_frameSize: 8 channels: 2
17:48:33.251 T:18446744071864353408 WARNING: CPythonInvoker(15): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
17:49:46.745 T:18446744072444040576  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
17:49:46.749 T:18446744072444040576  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 28224 m_frames: 1764 m_frameSize: 8 channels: 2
17:49:49.429 T:18446744071864353408 WARNING: CPythonInvoker(16): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.

**Comment by TmpName** [comment]
J'ai du editer le post car il y avait trop de liens illegaux.
As tu essaye de lire le stream, pas de le telecharger ?

**Comment by thorsten68** [comment]
Pour ce log c'était une tentative de téléchargement. J'ai déjà essayé le stream ça marche pas non plus. Je peux te poster le log d'une tentative de stream si tu veux.

**Comment by TmpName** [comment]
je veux bien mais alors en activant le mode debogage dans kodi, car franchement je ne vois aucun probleme, ca se connecte au bon fichier, et sa coupe de suite, comme si le prb venait plutot de la machine.

**Comment by thorsten68** [comment]
Ouai mais pourquoi ça fonctionne bien en téléchargement avec uptobox, en streaming aussi avec upload

**Comment by TmpName** [comment]
C'est pas moi qui ait configure ta machine ^^, sous linux tout est possible, un reglage qui bloquerait un protocole par exemple. Il y a des dizaines de facons pour comminuquer avec un serveur.
