### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1682]
@TmpName  , ne fait pas de mise a jour auto cette semaine, mise a jour mensuel a la fin de la semaine (normalement) avec suppression du system de source pour la recherche.

En gros dans les sites tu auras 3 choix 

URL_SEARCH_MOVIES

URL_SEARCH_SERIES

URL_SEARCH_OTHER

Séries et anim fusionner

documentaire et video web dans OTHER

Les +
- ça permet d'avoir différente recherche pour un même fichier.
- La vérification de l'exitence ou non simplifier.
- Juste a tester si URL_SEARCH existe et si il est activer dans les prefs.
- Ont vire doucement sDips et stype.

Les -
- Je sais pas ou mettre alluc (pour le moment HS).
- Compatibilité avec les marques pages.

Je pense me servir de gui.CONTENT pour voir si c'est movie, tv , ou autre.
ou xbmc.getInfoLabel('Container.Content') mais pour le moment il retourne pas la même chose c'est bizarre bref.

J'ai pas encore commencer à coder donc si vous avez des idées ou autres je vous écoutes.

**Comment by Arias800** [comment]
Y a des gens qui  ce serve d 'alluc car sinpersonne sans sert ça peut degage

**Comment by johngf** [comment]
comme d'habitude ce n'est pas parce que vous ne l'utilisez pas que c'est une généralité

**Comment by Arias800** [comment]
Juste je demande si il y en a qui l utilise

**Comment by TmpName** [comment]
Ben a une epoque, y avait un lien "autre recherche" ou un truc comme ca qui passait par alluc, et oui y en a qui ont demande pkoi le lien avait saute, donc ca doit servir.

Moi ce qui me fait peur, c'est que si ont touche aux fichiers sites, sans assurer la retocompatibilite, ca va foutre du bordel.
Et il y a aussi des sites qui ont un moteur de recherche pour les serie et un autre pour les animes (mais la suis pas sur que ce soit encore le cas ..)

**Comment by johngf** [comment]
pour alluc ils ont changé le cryptage du lien

**Comment by LordVenom** [comment]
Ben le faite de modifier ça permet de mettre autant de recherche qu'on veut en faite puisque ça ne passe plus par un sdip.

Plus de setting à rallonge masquer, ça ce base vraiment sur la présence ou non de la variable URL_SEARCH et sur plugin on/off

**Comment by yas06** [comment]
salut je pense qu il y avait plus de gens qui ce servait de recherche similaire que de alluc qui a une fonction recherche dans ca source peut être tu l enlevé de la recherche ca peut ne pas gener ?

**Comment by TmpName** [comment]
Ha oui c'etait ca le nom ^^.
Mais de toute facon alluc est HS apparement pour le moment.

**Comment by LordVenom** [comment]
Bon je suis partis pour utiliser sCat mais sans l'envoyer dans oOutput.
