### ISSUE TITLE
Essaie Source

### ISSUE THREAD

**Issue by liberodark** [Kodi-vStream/venom-xbmc-addons#1683]
Bonjour, 

Je me tente à ajouter une source pourriez vous jeter un coup d’œil quand vous avez le temps ?

Cordialement

https://github.com/liberodark/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/extreme_down_one.py

**Comment by TmpName** [comment]
Alors je t'arrette de suite ^^.
Je n'ai pas regarde ta source, mais le site que tu as choisis utilise la protection recaptcha qui n'est pas encore geréé par Vstream, donc je sais pas ce que tu as prevu mais tu as pas choisit le plus facile.

Cf https://github.com/Kodi-vStream/venom-xbmc-addons/issues/517

**Comment by liberodark** [comment]
Après c'est seulement un test.
Je suis encore à essayer de comprendre le tout.
Python j'en est pas fait depuis ma 5ème donc c'est vraiment loin.

Cordialement

**Comment by TmpName** [comment]
Y a pas de soucis, et tu arrives presque au plus dur, les regex ^^.
Le prb c'est que tu n'as pas choisit le bon site pr commencer.

**Comment by liberodark** [comment]
je vais essayer une autre source que vous avez pas ! 
Merci du conseil
