### ISSUE TITLE
Discord / Youtube

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1684]
Bonjour, J'ai ouvert un Salon discord et une chaine youtube:

 [![images](https://img.shields.io/badge/Chaine-Discord-blue.svg?style=for-the-badge)](https://discord.gg/rZa9fcH)

 [![images](https://img.shields.io/badge/Chaine-Youtube-red.svg?style=for-the-badge)](https://www.youtube.com/channel/UCdyY1QEC8dJSU6-6GPKPrnA)

Note : Pas de Salon Vocal, Robot Github dispo (message automatique à chaque changement sur le Github).

**Comment by Arias800** [comment]
Yes j arrive en fin de semaine ^^

**Comment by diouf76** [comment]
Il n'y a pas grand monde

**Comment by LordVenom** [comment]
Tu vas rire mais je penser qu'il y aurais moins de personnes encore xD, c'est en test si vraiment ça bouge pas je le ferme y a pas mort d'homme.
Perso j'utilise Discord pour autre chose aussi donc...

**Comment by diouf76** [comment]
Oui mais l'idée est bonne en espérant que cela va faire venir du monde pour échanger
