### ISSUE TITLE
Kaydo.ws

### ISSUE THREAD

**Issue by KujoWolfgang** [Kodi-vStream/venom-xbmc-addons#1685]
Bonjour, Vous êtes peut-être déjà au courant. Depuis le début de la semaine, Kaydo.ws redirige maintenant sur http://www.hds.to

Suite a ce changement, les films sur Kaydo, fonctionne toujours, mais les séries ne fonctionne plus dans Vstream. Lorsqu'on fait une recherche sur une séries dans Kaydo, on obtient le resultat de recherche, et on nous présente chaque saison de la séries, mais quand on ouvre une saison, il ni a aucune épisode.

Je vous remercie a l'avance, pour votre excellent travail, Vstream ses le meilleurs addons de kodi :)

**Comment by LordVenom** [comment]
Merci du retour, correction a la prochaine mise a jour.
