### ISSUE TITLE
Serveur Rabbit

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#1687]
Bon soir...
J'ai trouvais sur le net  un super  site qui vous permets de telecharger ou de regarder des vidéos à une  vitesse jusqu'à  990 M/s  et même mètre des vidéo on ligne comme YouTube
le serveur ai héberge aux usa 
ma question et ce est que on peux cree une source de ce site pour le streaming 4k UHD?

rabbit.it

rabbittvgo.com

**Comment by TmpName** [comment]
Si le site est 100% FR, pkoi pas.
