### ISSUE TITLE
Filmvostfr

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1688]
le premier lien (hoster) ne fonctionne pas, celui de filmvostfr. Je ne vois pas le fichier hoster pour filmvostfr??

**Comment by johngf** [comment]
C'est normal il n'y en a pas le lien n'est pas résolu et vu le nombre de lien par film ... a voir

**Comment by razorex** [comment]
Ok je me disais bien que c’était çà. donc oui à voir sachant que les liens sont fonctionnels.

**Comment by TmpName** [comment]
J'ai commence a mettre une correction, ca marche mais je n'ai teste que pour un film (lien google)

**Comment by johngf** [comment]
Tu appelle cpacker sans l'importé ?

**Comment by TmpName** [comment]
J'avais pas copier le code complet, vu que j'avais pas la derniere version.

Le regex est a modifier pour la compatibilite avec uptbox, mais pas trouve de lien pr tester.

**Comment by johngf** [comment]
Version 5 de vstream avec la modif seul le lien filmvostfr fonctionne plus les autres
