### ISSUE TITLE
Lenteur du programme 

### ISSUE THREAD

**Issue by miekperez** [Kodi-vStream/venom-xbmc-addons#1691]
Bonjour, voilà deux jours que le programme est super lent est ce normal?même après la mise à jour d aujourd'hui. Y a t il qqch a faire de spéciale?
Merci 
@Lord Venom je n arrive plus à te joindre sur twitter es tu parti ?

**Comment by lord** [comment]
Désolé, vous avez peut-être voulu envoyer un message à @LordVenom?

**Comment by miekperez** [comment]
Non pas spécialement. C est lui qui m avait aidé il y a 2mois d ici avec vstream. 
Avez vous une idée de pourquoi est ce si lent depuis deux jours ?
J utilise kodi dernier version sur 3 appareils différents (win 10,mac os,Android) et je le problème à chaque fois. Il faut plus d'une minute pour faire une recherche de série dans mon cas. 
Une piste?
Merci

**Comment by Arias800** [comment]
Quand tu dit recherche de série tu parle de la recherche globale ? Si oui c à peut venir de la connections internet

**Comment by miekperez** [comment]
Salut merci. Je veux dire lorsque je lance vstream. Je clique sur série et la déjà il y a un temps anormal. Après si je recherche , il me faut 10 minutes pour que la recherche soit faite dans tout les sources. 
Cela fonctionne correctement chez vous?
Merci

**Comment by miekperez** [comment]
Ah oui je suis à 75 mbps. Je viens de faire le test

**Comment by Arias800** [comment]
Alors  personnelles je n ai pas remarquer de lenteur particulière c est quel version de vstream que tu utilise ?

**Comment by miekperez** [comment]
La dernier mise à jour à été faite. J ai un peu explorer ta piste et j ai trouvé ce qui n allait pas. Malgré un débit de 75mbps, je n arrivais pas à faire des recherche. J avais  bien internet sur le PC. J ai redémarrer mon modem et tout et rentré dans s l ordre. Merci de ton aide. Je cherchais trop long :-(

**Comment by Arias800** [comment]
De rien content que tu est trouver ^^
