### ISSUE TITLE
Bug cinemaycom

### ISSUE THREAD

**Issue by NizarAloui** [Kodi-vStream/venom-xbmc-addons#1692]
Cannot fetch any movies or any movies link for cinemay website.

**Comment by johngf** [comment]
Le site est désactiver mais peut etre ré-activé le site est de nouveaux mis a jour et plusieurs hoster disponible

**Comment by NizarAloui** [comment]
Oui c'est pour cela, il est mis a jours et super bien indexé, ya t'il moyen de le reactiver ?

**Comment by TmpName** [comment]
Je viens de le tester, la reactivation ne suffit pas, tout les regex doivent etre refait.

**Comment by johngf** [comment]
Bloqué au dernier lien avant hoster ....

**Comment by NizarAloui** [comment]
J'ai deja fait les modif en local, il faudra utiliser un executeur JS (java script) pour avoir les liens du hoster, ou reimplementer la fonction js en python ce que j'ai fait aussi, je pense que c'est mieux de faire ainsi que de rajouter un analyseur javascript.

**Comment by johngf** [comment]
le probleme déjà c'est pour avoir le code JS de l'avant derniers liens pas moyen nous dirige vers une page blanche (surement un problème de cookie ou cloudflare)

**Comment by TmpName** [comment]
Yep, je viens de tester en coup de vent.
La premiere page cree un cookie, qui est systematiquement repasse a chaque clic sur un lecteur.
Mais il faut aussi une activation, doit y avoir un lien qui active le cookie car si j'active l'antipub, les cookies sont passé mais le site ne marche pas.
J'ai pas pu trouver quel cookies etaient indispensable en les retirant un par un a cause du cache, faut que je trouve comment le desactiver.

**Comment by NizarAloui** [comment]
Les 3 cookies indispensables sont ces trois la :

> __cfduid=xxxxxxxxx; ; PHPSESSID=xxxxxxxxx; starstruck_xxxxxxx=xxxxxxxxxxxx

**Comment by TmpName** [comment]
Ha ? c'est tout ?
J'ai du louper un truc de mon cote alors, car meme avec les cookies, ca ne passe pas a chaque fois, peut etre que c'est de "vieux cookies".

**Comment by johngf** [comment]
pareil meme avec les cookies

**Comment by johngf** [comment]
Quelqu'un a avancé ? J'ai test de nombreux trucs pas moyen

**Comment by TmpName** [comment]
Nope, vu que @NizarAloui avait trouve, je laisse la main, la je suis sur AAdecode et flash X

**Comment by NizarAloui** [comment]
Ha,
 j'ai juste vu que les 3 cookies mentionnés dans mon derniers poste , en les copiant d'un browser style chrome dans le code sources ca a marché, mais en fetchant tous les url et settant les memes cookies, ca marchait pas !

**Comment by TmpName** [comment]
Ha ok, du coup tu n'as pas teste avec un code python ?
Parce que du coup, moi j'ai plus le mien (j'ai refais une mise a jour depuis)

**Comment by NizarAloui** [comment]
Si c'est avec un code python que j'ai testé.

**Comment by TmpName** [comment]
Et on pourrait pas avoir le debut de code, meme non fonctionnel, stp ? Ca eviterait de repartir a zero.

**Comment by NizarAloui** [comment]
J'ai rajouter une version draft de cinemay sur mon fork de la repo:
[(https://github.com/NizarAloui/venom-xbmc-addons/commit/33cd90578d8abfa024ca66ebfd1e4e0c2c8d3717)]

Vous pouvez voir les cookies setter en dure, il faudra trouver le moyen de les avoir dynamiquement, sinon tous les patterns sont testé.
Le code en lui même n'est pas du tout tester , je l'ai importé de mon script local vers celui de la repo venom.
Faite moi un signe si vous voulez un autre renseignement par rapport a ça.

**Comment by johngf** [comment]
j'ai fait un test avec nouveau cookie et quelque modif c'est ok

**Comment by TmpName** [comment]
Il y a des fonctions pour gerer les cookies dans RequestHandler, je pourrais avoir le dernier code pr jeter un oeuil ?

**Comment by TmpName** [comment]
Bon j'ai une nouvelle version, faites gaffe les liens sont en dur.
Ca gere les cookies, ca ne marche pas et pour moi c'est normal, il me manque le cookie _ga, et quand on regarde la date des cookies, c'est le seul qui est renouvele au moment de l'affichage de la page.

https://pastebin.com/tqyHKfKK

**Comment by NizarAloui** [comment]
Quand on efface les cookies du navigateur , et essayer d'accéder au liens hoster, ça ne marche pas dés le premier coup, il faudra que les cookies:
__cfduid=xxxxxxxxx; ; starstruck_xxxxxxx=xxxxxxxxxxxx
soit générer. Le cookie 'PHPSESSID=xxxxxxxxx; ' est lui généré dés le début.
lors du deuxieme accés on arrive a avoir les deux cookies manquants et la ça marche bien et on arrive a avoir le code JS. 
Bien sure c'est une analyse faite sur le browser (chrome ou firefox).
Si on implémente le même scénario dans le script ça ne marche pas, il doit y avoir encore un autre truc qui nous échappe. 
ça me rappelle le système de signature des cookies faite avec les amazon webservice.
A suivre ...

**Comment by johngf** [comment]
meme constat sur le navigateur au premier test rien pas de code.js on doit actualisé la page pour que ça fonctionne et nous donne le code.

PS:@NizarAloui tu as l'air de connaitre le javascript tu saurais convertir cette [fonction](https://pastebin.com/Prw51DvZ) en python avec des annotations pour qu'on puisse apprendre

**Comment by NizarAloui** [comment]
Voici la conversion en python, après j'ai pas testé la fonction, il me faudra des données correct comme entré pour que je valide la fonction.
ce que la fonction fait c'est que du math , des opérations de math pour générer un code.
Voici le lien: https://pastebin.com/Hqhs1Drt

**Comment by TmpName** [comment]
Bon j'ai continue mes tests, toujours pas trouve comment rendre valide le cookie.
C'est pas google analyse ni recaptcha, j'ai teste en mettant bloquant ces sites.
La j'ai une version qui liste tout les liens et essaye de s'y connecter mais ca marche tjours pas.
https://pastebin.com/T5gjE0c4

**Comment by johngf** [comment]
Ce serait pas le clic to play ? J'ai deja testé mais on sait jamais
@NizarAloui non c'est pour un hébergeur upvid co

**Comment by NizarAloui** [comment]
La seul hypothèse c'est que il y a un script JS qui signe ces cookies ou qui génère un id=xxx trust, car on a déja analysé tous les échanges avec le serveur. Je vais essayer de regarder tous les script JS utilisé sur ce site qui interviennent au moment de la génération des liens.

**Comment by TmpName** [comment]
Ben y a du script ajax, mais meme lui doit apparaitre dans les echanges, et depuis la derniere version de firefox j'ai plein d'extention qui ne marchent plus, donc je galere un poil.

**Comment by TmpName** [comment]
Bon ben c'est pas le "clic to play".
Je prend des cookies non fonctionnel, je met les memes dans kodi et firefox.
Il me suffit d'actualiser le page, sans cliquer nulle part pour le valider pour qu'il fonctionne sous kodi.

**Comment by TmpName** [comment]
Bon j'ai peu etre une piste, il y a un fichier javascript detectmobile, le code n'est pas celui d'origine (trouvable sur le net) et si je bloque ce fichier dans adblock le cookie ne se valide plus en actualisant juste la page pour kodi, par contre via firefox ca ne gene pas du tout.

**Comment by johngf** [comment]
Faudrait verifier avec l'addon iptv player for e2 qui a cinemay dedans voir si il fonctionne

**Comment by TmpName** [comment]
Et il marche encore cet addon ?

**Comment by johngf** [comment]
Il est tres souvent mis a jour sur git lab il doit fonctionner

**Comment by TmpName** [comment]
Je vais pas tout installer pour tester, mais un truc marrant c'est qu'il charge "/image/logo.png", a mon avis c'est pas pour rien. Ma faudra tester plus tard.

**Comment by johngf** [comment]
Ba oui c'est pour ça je parlais du clic to play  j'ai pas réussi

**Comment by johngf** [comment]
bon c'est ok ça fonctionne

**Comment by TmpName** [comment]
Lol, c'etait ca alors ?
Le code est completment fini ?

**Comment by johngf** [comment]
je suis dessus c'est ok

**Comment by TmpName** [comment]
Bon ben nickel, je retourne me coucher alors ^^. Par contre c'est dommage que tu n'utilises pas la lib de Vstream maintenant qu'elle a quelques outils pour gerer les cookies.

**Comment by johngf** [comment]
je corrigerai plus tard quand je regarderai comment ça fonctionne dans la lib

**Comment by johngf** [comment]
j'ai jeté un oeil( testé la lib) et il y a un souci quand le cookie ne termine pas par ; il n'est pas pris en compte

**Comment by TmpName** [comment]
Ha ?
Merci je jette un oeuil de suite. C'est quand je recupere les cookies du site, quand je parse la chaine pour les extraires un par un que ca deconne ?

**Comment by TmpName** [comment]
Bon je vois pas ou il peut manquer un ;
Un exemple de chaine recuperée

`__cfduid=d6dcb8e84bb2088085b6999543e5eb8171509798909; expires=Sun, 04-Nov-18 12:35:09 GMT; path=/; domain=.cinemay.com; HttpOnly, PHPSESSID=s0hbg4p5g71vfldpp3bg0uo8d3; path=/, starstruck_78c00ef9b545ea40b94ca34d6718f713=4062eebed65af9ad533af1ccfe7fc46b; expires=Sun, 04-Nov-2018 12:35:09 GMT; Max-Age=31536000; path=/`

C'est la ou le ; manquerait ?

**Comment by johngf** [comment]
non pas sur cine may

**Comment by johngf** [comment]
@NizarAloui  le fichier a été mis a jour sur le github

**Comment by NizarAloui** [comment]
Oui merci, j'ai suivi les echanges c'est bien une belle astuce venu de cinemay :)

**Comment by TmpName** [comment]
Je peux mettre la lib de vstram a jour, mais je vois pas ou est le prb ? tu aurais pas la requete foireuse ?

**Comment by johngf** [comment]
Bah finalement pas besoin du cookie donc c'est bon

**Comment by johngf** [comment]
@TmpName ton code sait executé du code js

**Comment by TmpName** [comment]
Yep, c'est le but du smilblick.

**Comment by johngf** [comment]
J'ai testé mais ça fonctionne pas le code que j'ai test est composé de 5 fonction séparé et dans une fonction ça plante a cause de reverse()  ex: r.split("").reverse().join etc...
Pour utilisé ton code j'ai pris exemple sur le code dans speed vid

**Comment by TmpName** [comment]
Il manquait la fonction reverse(), je viens de la rajouter https://github.com/TmpName/TinyJSParser/blob/master/tinyjsparser.py

Now ce code fonctionne
```
JScode ="""
a = "abcd";
a = a.split("c").reverse().join('+');

debug();

"""
```

**Comment by johngf** [comment]
reverse ok par contre ça plante avec une fonction base64 a l'intérieur du code
code https://pastebin.com/Z571UAtp

**Comment by TmpName** [comment]
C'est bon, j'ai mit a jour le fichier, j'ai juste deux probleme, un caractere qui deconne en plein millieu du lien, et un probleme au niveau de la gestion des variables, normalement ca marchera dans la semaine, mais ca vient d'ou ce code ?

**Comment by johngf** [comment]
de alluc ee

**Comment by TmpName** [comment]
Ha tiens ils l'ont change, c'est vraiment un code simple, qu'ils ont volontairement complique. Enfin bon moi ca m'arrange ca me permet d'optimiser mon interpreteur.

**Comment by johngf** [comment]
de mon coté j'apprends a convertir le js en python j'ai deja fait 3 fonction

**Comment by johngf** [comment]
je crois que j'ai finis le code

**Comment by TmpName** [comment]
C'est bon j'ai mis a jour https://github.com/TmpName/TinyJSParser
Now compatible avec les exentricitees de ton code.
