### ISSUE TITLE
Ajout dans Marques Pages !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1693]
Je trouve que dans la Rubrique "Marque-page" de l’Extension", il manque une Rubrique du nom de "Coffrets Vidéos" ou on ajouterait une série de Films en la nommant car ça serait pas mal. Est-que ça serais possible de l'avoir dans l’Extension s'il vous plait ?

Cordialement,
Luluvulcain

**Comment by LordVenom** [comment]
Pour faire tes propres liste et organiser au mieux tes films streamer regarde du coter de Trakt.
