### ISSUE TITLE
Extended info script

### ISSUE THREAD

**Issue by arzaz** [Kodi-vStream/venom-xbmc-addons#1695]
Erreur Extended info script
Merci de verifier le problème.

**Comment by LordVenom** [comment]
Un peux plus d’explication ou quand comment ?
Un petit Bonjour aussi.

**Comment by arzaz** [comment]
Bonjour LordVenom,
A chaque fois que je veux avoir l'information sur un film je reçois le message Erreur Extended info script, puis il plante sur Mise en cache et Veuillez patientez?
Je dois a chaque fois redémarré ma box android

**Comment by LordVenom** [comment]
Sur quel Source, et quel Film j'ai pas de soucis moi.

**Comment by TmpName** [comment]
Essaye cette extension sur un autre addon pour voir.

**Comment by arzaz** [comment]
D'après des forum extendedinfo ne fonctionne pas sur la dernière version kodi 17.4

**Comment by LordVenom** [comment]
Je suis en 17.4 perso

**Comment by nabsboss** [comment]
Salut ! Ça me le fait aussi depuis 1 mois ! Ce bug est apparue quand j'ai vidé TS les caches et réinstallé vstream il me semble. Extend info marche sans problème en dehors de vstream. J'ai une box Android, un peu galère pour envoyer des logs avec une télécommande :)

**Comment by LordVenom** [comment]
Pour les logs rien de compliquer voir 

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by nabsboss** [comment]
Voilà ;) https://slexy.org/view/s2k3JWiBP7

**Comment by Arias800** [comment]
Alors Extend info script généré bien une erreur faut voir si quelqu'un la déjà rencontré

**Comment by LordVenom** [comment]
C'est moi ou y a aucune erreur vStream ? fait la mise a jour de Extend.

**Comment by LordVenom** [comment]
https://media.discordapp.net/attachments/362558547088900097/366350630043779082/unknown.png?width=1202&height=677

**Comment by LordVenom** [comment]
Des nouvelles ?
