### ISSUE TITLE
Recherche film en UHD 4K

### ISSUE THREAD

**Issue by nabsboss** [Kodi-vStream/venom-xbmc-addons#1696]
Salut !

Je galère pour trouver des films en 4K sur Vstream. Je ne peux le voir que quand je recherche un film en particulier seulement.
J'ai essayé depuis les sources mais sur zones téléchargement par exemple, y'a une section [x264 et x265] du coup la plupart sont en x264 et non x265.
Existe t-il un moyen de faire une recherche visuelle sur des contenues 4k ultra HD ?

Merci de votre aide

**Comment by TmpName** [comment]
Ben justement le x264 est mieux supporte par les plateformes non ?
Sinon, non, le meilleur moyen est de passer directement par un site qui propose du 4k, mais surtout d'y croire tres fort.

**Comment by nabsboss** [comment]
Sinon sur zone téléchargement y'a un tag qualités [ULTRA HD] sur Fury par exemple. Est-il possible d'avoir une recherche sur ce type dans toutes les sources -> zone téléchargement -> films ultra Hd (x265) au lieu de Films (x265 & x264)  ?

**Comment by TmpName** [comment]
Rajouté, pas encore dans les mise a jours
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py
