### ISSUE TITLE
Kepliz HS

### ISSUE THREAD

**Issue by Benaland** [Kodi-vStream/venom-xbmc-addons#1697]
Salut la Team, aucun lien ne s'affiche sur Kepliz. J'ai été sur le site Mozdad_com et tout à l'air fonctionnel pourtant...

**Comment by TmpName** [comment]
La version en ligne autre un autre site, qui a les videos HS.
En attente de voir si le site va etre corrige ou abandonne.

**Comment by luluvulcain** [comment]
Oui Benland, tout marche bien sur Mozdad.com (ancienement OZPORO.COM) mais comme dis TmpName, vaut voir si il va être corrigé ou abandonner et aussi être mis a jour dans vStream.

**Comment by Arias800** [comment]
Parce que au pire si le site n'est pas corrige il faut trouve un autre clone de kepliz ce qui est long d'etre difficile

**Comment by khalilounet** [comment]
J'utilisai aussi OZPORO avant mais on m'avait averti que OZPORO était qu'un clone. Depuis Mozdad le site était truffé de pub alors qu'un autre clone n'avait pas mis en place cette procédure de pub.
Le voici : 
http://topulor.com/m5o4h8g73n1bv2b1vc5g4f6lop8d5qs4q874ds5sd48/index.php

**Comment by TmpName** [comment]
Bon, toujours pas fonctionnel, je change le site.
