### ISSUE TITLE
Probleme : site dlprotecte hs

### ISSUE THREAD

**Issue by draculahub** [Kodi-vStream/venom-xbmc-addons#1698]
Bonjour à tous.
Quand j'utilse vstream impossible de streamer depuis zone -techargement car je reçois le message d'erreur SITE DL-PROTECTE HS sous android.
Avec vstream mais sous linux ça fonctionne bien.
Quelqu'un d'autre a-t-il le même problème sous android ?
Merci.

**Comment by Arias800** [comment]
Quel version de kodi a tu ?

**Comment by draculahub** [comment]
Bonsoir arias800
bonne remarque , ca fait tellement longtemps que je n'ai pas eu de problèmes que j'utilise de vieilles versions de kodi : kodi 16.1 sous linux et kodi 14.1 sous android.
Je vais changer ma version android et passer à la 16.1.

**Comment by reds07** [comment]
Bonjour, j'avais la version 16.1 et même souci de liens protect HS, il faut passer à kodi 17.4 et c'est réglé.

**Comment by jcoooo** [comment]
Zone-telechargement n'utilise plus dl-protect mais protect-zt.com pour ses liens. depuis quelques heures.

**Comment by Arias800** [comment]
J'envoie un pull request pour fix ca ^^

**Comment by jcoooo** [comment]
je confirme retour des liens .... merci pour l'efficacité

**Comment by jcoooo** [comment]
Ne marche plus

**Comment by Arias800** [comment]
Ah il on se encore du faire une modife mais je peux pas en occupé

**Comment by jcoooo** [comment]
Ce n'est pas la mort s'il faut un jour ou deux pour corriger.  
Ce qui est bizarre c'est que certains liens fonctionnent alors que d'autres pas.

**Comment by Arias800** [comment]
Perso je pourrait regarde en fin de semaine (jeudi voir vendredi)

**Comment by jcoooo** [comment]
pas la peine seul quelques liens de dimanche soir ne fonctionnent pas depuis tous les nouveaux sont ok.

**Comment by Arias800** [comment]
OK ^^

**Comment by firimar6** [comment]
Coucou (j'en profite pour vous féliciter et vous remercier pour Vstream !!)

Par contre, j'ai toujours l'erreur moi... Sous Win 10, Kodi 16.1 et la dernière version Vstream.

**Comment by Arias800** [comment]
Pour la recherche il ont du faire un midif faut sue je regarde c asinon pour DL protect a tu mit a jour le fichier ?

**Comment by firimar6** [comment]
Euh c'est à dire ? J'ai mis à jour vStream en 0.5.5.

**Comment by Arias800** [comment]
Verifie si dans le dossier site tu a bien cette version de zone téléchargement
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by Arias800** [comment]
Bon pour la recherche je comprends pas trop comment fonctionne le fichier donc je vais laisse quelqu'un qui le connais s'en occupé ^^

**Comment by firimar6** [comment]
Si la manip consiste bien à remplacer le contenu du "bloc note" par ce dernier, ouais c'est fait. Mais toujours les mêmes problèmes. :(

**Comment by Arias800** [comment]
Sur quoi tu a l'erreur ?

**Comment by johngf** [comment]
Tu as cliqué sur raw avant'de copié le contenu ?

**Comment by firimar6** [comment]
Je l'avais pas fais non, la je l'ai fais dans le doute mais ça ne change rien. :(

Sous Win 10, Kodi 16.1,la dernière version vStream et le fichier d'Arias800 copié,  j'ai toujours "erreur SITE DL-PROTECTE HS" quand je veux lancer un film de la source zone telechargement.

Le reste marche niquel, mais c'est vraiment cette source qui m'intéressait... je vais pleurer un coup je crois. ^^

**Comment by Arias800** [comment]
Essai de passer a kodi 17 voir si ça ne règle pas me problème. Pour ma recherche oui elle est HS et personnellement je n arrive pas a trouvée une solution ^^

**Comment by firimar6** [comment]
Erf dommage, pas très pratique sans la fonction recherche. J'espère que quelqu'un pourra en trouver une. :)

Pour Kodi 17 on verra du coup, va falloir que je m'organise avec mes autres applications qui ne sont pas encore compatibles pour certaines d'entre elles. :(

**Comment by Arias800** [comment]
Recherche fix grace a @TmpName

**Comment by luluvulcain** [comment]
Pour remédier au Problème de Zone telechargement et autres, il suffit de telecharger ma version modifié de l’extension en fichier zip au https://github.com/luluvulcain/vStream-Kodi
Ensuite de désinstaller vstream et d'installer ma version comme ça l’extension sera a jour et tout remarchera.

**Comment by akatimike** [comment]
Marche pas encore suis je le seul

**Comment by firimar6** [comment]
Sous Kodi 16.1 pas moyen de le faire marcher. :(

Sous Kodi 17.4 en installant le lien de luluvulcain ça fonctionne. Par contre ne pas mettre vStream à jour (il me le propose dans Kodi) sinon ça ne marche plus.

**Comment by jcoooo** [comment]
zt a encore changé l'adresse de son obfuscateur.
protect-zt.com est devenu protecte-link.com

**Comment by Fabiodirt** [comment]
Bonjour à vous,

Je suis un gros newbie de chez newbie ! ^^
J'ai installé la version modifiée mais j'ai toujours les 3 "petits points" quand je rentre dans la fiche d'un film via ZT.
J'ai mis la page en favoris, en espérant suivre l'évolution de tout ça ! 
Encore bravo à vous pour le taf que vous accomplissez !

**Comment by jcoooo** [comment]
il va falloir que tu attendes que quelqu'un fasse la nouvelle modif ...

**Comment by TmpName** [comment]
Franchement, faudrait recuperer l'url du site directement sur le code html, pour la prochaine fois qu'il vont le rechanger.

**Comment by toadnam** [comment]
Salut tout le monde, merci beaucoup pour le travail que vous faites! Je préfère vstream à exodus et de loin! Par contre , j'ai installé la version modifiée de luluvulcain mais j'ai toujours les ... sur Zt.
vous avez le meme probleme que moi? Vous utilisez quel site en général pour les films en bonne qualité? Pour ma part ca depend, films illimité ou filmstreamvk (mais netu est saturé le soir...)

**Comment by Arias800** [comment]
Relie les dernier poste avant d envoyé un message (zone telecharhement est pour le moment HS ) et en se qui concerne les source de films en bonne qualité et bah je regarde peut de film mais j utilisé kep_liz ou kay_o

**Comment by luluvulcain** [comment]
Moi aussi j'ai le meme probleme

**Comment by TmpName** [comment]
Nouvelle version https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by jcoooo** [comment]
Merci je testerais ça demain

**Comment by jcoooo** [comment]
zt a encore changé l'adresse de son obsfucateur
www.liens-telechargement.com

**Comment by Arias800** [comment]
La version beta du fichier zt est normalement immunisé contre les banale changement de nom de l'obsfucateur https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py
