### ISSUE TITLE
Re Rabbi.it

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#1699]
Rabbit site qui vous permets de telecharger ou de regarder des vidéos à une vitesse jusqu'à 990 M/s et même mètre des vidéo on ligne comme YouTube
le serveur ai héberge aux usa
ma question et est ce que on peut créer une source de ce site pour le streaming 4k UHD?
J'ai  posté ce sujet mais malheureusement il a était fermée le site effectivement qu'il est en anglais....ce que je veux c'est l'utiliser pour avoir une connexion internet haut débit pour ce qu'il en un probleme de réseaux

ht tps://youtu.be/Q5zgjgC8ywg

utiliser ra bb.it comme un débrideur ou en doit mettre just le lien de la video, pour  regarder les vidéo 4kUHD comme par exemple.

**Comment by johngf** [comment]
pour regarder des vidéos UHD tu doit avoir le débit internet nécessaire a ton domicile (fibre optique) aucun débrideur ne te donnera un plus gros débit que ta ligne internet est capable de gérer.

pour ce qui est de l'uhd sur le net c'est souvent encodé a des débit inférieur comme pour le 1080p donc >> en vérité non full UHD ou non HD 

edit: la plupart des hosters ont déjà du mal en 1080p et bug souvent

**Comment by Arias800** [comment]
Le seul lecteur qui a du vraie 4kUHD en contenu c'est uptobox (et uptostream) de mémoire
