### ISSUE TITLE
Ka_do.ws

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1704]
Alors voila j'ai un petit probleme avec ka_do lorsque je me vais sur hds ca m'affiche members only avec des champs pour me connecte.
Quelqu'un aurai une solution pour passer ca ?

**Comment by johngf** [comment]
déjà dans les issues >> kaydo détecte les ip mobile(4g) proxy ou autres pays ... et donc les bloques
le pourquoi ????
moi aussi bloqué ip 4g
rien a faire a part réactivé son clone qui est dans trash et qui fonctionne avec ces ip's la

**Comment by Arias800** [comment]
Mais je suis pas sur mobile , je n'ai pas de proxy , je suis en France (c'est peut etre ca le probleme ) sinon je vois pas x)

**Comment by johngf** [comment]
enfin il bloque certaines ip je ne sais pas pourquoi ipv6 peut etre pour ton cas

**Comment by Arias800** [comment]
nop je suis en ipv4 bref ce site est bizarre x)

**Comment by johngf** [comment]
t'est chez free ?

**Comment by Arias800** [comment]
non orange

**Comment by johngf** [comment]
bizarre moi ça fonctionné avant avec orange et niveau dns tu utilise opendns ?

**Comment by Arias800** [comment]
non j'ai le dns en mode automatique sur windows mais ca bloque depuis le changement de nom ^^

**Comment by Arias800** [comment]
Meme probleme sur mon ordi portable bref le mystère reste entier

**Comment by yas06** [comment]
Salut j ai le même problème quand j ai pris la fibre orange g tester avec fibre pas accès, avec la Freebox adsl pas de soucis g tester avec des  vpn des  proxi j ai pas trouvé le bloquage

**Comment by Arias800** [comment]
J ai ma petite idée , peut être que il bloque les personne qui ont des box avec IP dynamique

**Comment by Arias800** [comment]
C'est bon j'ai acces au site ^^

**Comment by yas06** [comment]
Salut Arias peut on avoir la solution Merci d avance

**Comment by Arias800** [comment]
Je n ai absolument rien fait ça c est débloquer tout seul

**Comment by Arias800** [comment]
Bon je ré ouvre cette issue temporairement car j'ai résolut le problème de connexion avec orange (livebox play) en mettant a jour ma box internet
