### ISSUE TITLE
Changement de Rubrique dans le Menu de vStream

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1705]
Bonjour,
J'ai remarquer que dans le Rubrique "Télévision / Radio", les chaines TV ne marche pas tout le temps. Ça serais bien de les enlever et de les remplacer par les Radios en renommant la Rubrique 'Radio" et aussi de renommer la Rubrique ""Télévision replay" avec le Nom "Replay". Est ce qu'est possible de le faire lors de la prochaine mise à jour s'il vous plait ?

**Comment by TmpName** [comment]
Quelle chaine de Tv ne marche pas ?
Sinon on vient juste de les remettre justement car les gens les voulaient a nouveau ^^.

**Comment by LordVenom** [comment]
Ha ça ma jamais choquer le terme télévision Replay mais l'idée est bonne ce sont bien des émissions de télé en replay alors TV Replay si tu préfère xD

**Comment by luluvulcain** [comment]
Changer le Nom de la Rubrique "Télévision replay" en TV Replay me va oui LordVenom. Je Valide et si c'est possible de le faire ça serais bien.
