### ISSUE TITLE
Mise au Vote

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1709]
![image](https://user-images.githubusercontent.com/4380112/31497253-d3748680-af5e-11e7-9f20-9cd0f672e208.png)

**Comment by TmpName** [comment]
C'est la version pour le reveillon ?

Ok , me sauve.

**Comment by LordVenom** [comment]
La version des 3ans faut changer la sérieux !!! xD.

**Comment by diouf76** [comment]
Comme je t'ai dit garder la base du logo et rajouter de la profondeur ou effet 3d

**Comment by LordVenom** [comment]
J'ai pas oublie je regarde :)

**Comment by LordVenom** [comment]
![image](https://user-images.githubusercontent.com/4380112/31515549-d28119d2-af95-11e7-9707-20781366281b.png)

**Comment by LordVenom** [comment]
![image](https://user-images.githubusercontent.com/4380112/31520183-528db3ce-afa5-11e7-84c1-d24a23e92d8d.png)

**Comment by TmpName** [comment]
Je prefere les suivants, ca change moins, mais pour quelqu'un qui n'aime pas le flashy la toute premiere version fait mal aux yeux.

**Comment by razorex** [comment]
le fond du premier avec le logo du 2eme

**Comment by LordVenom** [comment]
![image](https://user-images.githubusercontent.com/4380112/31574898-1942f77e-b0da-11e7-9a44-f2af27258f00.png)

**Comment by LordVenom** [comment]
Les bandes noir sur les cotes n'existe pas c'est juste l'aspect ratio de mon FullScreen.

**Comment by LordVenom** [comment]
![image](https://user-images.githubusercontent.com/4380112/31575128-d8176720-b0df-11e7-868c-ac1a8d47bf81.png)

**Comment by luluvulcain** [comment]
Moi je Vote oui

**Comment by LordVenom** [comment]
Il faut mettre vaut réaction sur votre choix (et pas sur les commentaires "farfelue" des gens xD)

**Comment by LordVenom** [comment]
Y a des moments ou tu vois que tu est en surchauffe... 
1h passé à me dire c'est bizarre ce logo fait flou 50000 modification plus tard, je me suis rendu compte qu'il sont en 512px et moi en 256px ...Pfff

Note: faut modifier toute les icônes..

**Comment by LordVenom** [comment]
![image](https://user-images.githubusercontent.com/4380112/31589391-f773fada-b200-11e7-8a32-bfadf7df3e75.png)

**Comment by LordVenom** [comment]
![image](https://user-images.githubusercontent.com/4380112/31589899-01c3bacc-b209-11e7-9c4b-42813e56303b.png)

**Comment by TmpName** [comment]
Moi j'aime bien, mais c'est sous confluence ton screen ?

**Comment by LordVenom** [comment]
Non , Le Theme de base sous kodi 17
