### ISSUE TITLE
Possible de réinstaller la recherche similaire?

### ISSUE THREAD

**Issue by Christian26800** [Kodi-vStream/venom-xbmc-addons#1710]
Possible de remettre " recherche similaire " très utile pour faire des recherches rapidement

**Comment by Arias800** [comment]
La recherche visuels a ete désactivé par @LordVenom pour le moment mais si elle peut être réactive elle le sera

**Comment by LordVenom** [comment]
Puisque 80% des gens passe par la recherche visuelle un simple Back et plus simple que de relancer une recherche.

**Comment by TmpName** [comment]
La recherche similaire, c'etait pas la recherche via alluc ?

**Comment by Christian26800** [comment]
Non je trouvais ça très pratique et  un vrai gain de temps pour les recherches  "recherche similaire " et je ne parle pas des recherche alluc.

**Comment by Christian26800** [comment]
Et merci de votre rapidité à répondre .

**Comment by spcxsat** [comment]
bonjour,

moi aussi j'aimais bien recherche similaire, a vrais dire j'utilise pour dire jamais la recherche visuelle

**Comment by TmpName** [comment]
80% passent par la recherche visuelle ? Serieux, je suis le seul a trouver la methode classique 10 fois plus rapide ?

**Comment by LordVenom** [comment]
1. | /cHosterGui | 55 825 936 (18,79 %) (resolver url)
 2. | /cHome | 39 514 809(13,30 %)  (page d'accueil)
 3. | /filmstreamvk_com | 16 457 164(5,54 %)
 4. | /film_illimit_fr | 15 997 493(5,39 %)
 5. | /themoviedb_org | 14 352 669(4,83 %) (recherche visuelle) 
 6. | /full_stream_org | 13 075 789(4,40 %)
 7. | /globalSearch | 8 654 072(2,91 %) (recherche global)
 8. | /libertyland_tv | 7 009 150(2,36 %)

**Comment by razorex** [comment]
Moi non plus j'utilise pas la recherche visuelle, j'utilise la recherche classique. Qu'entend tu dire dans ta note @LordVenom ??

**Comment by luluvulcain** [comment]
Moi j'utilise les deux recherches.

**Comment by LordVenom** [comment]
@razorex  Un?Quoi? sur ?

**Comment by johngf** [comment]
Perso j'ai désactivé les statistics ça ralentis souvent les menus je trouve

**Comment by razorex** [comment]
@LordVenom :
Note : est c'est la que je vois pas mal de source créer mais jamais partager, je pense même y mettre un terme.Hum enfin non mais c'est chiant quoi xD

**Comment by LordVenom** [comment]
@razorex : Simple l'addon me donne les stats par sites, donc si tu crée un site "monsite.py"  y une stats monsite.py.

Donc je disais juste que beaucoup de site sont crée mais pas partagés, ceux qui n'est pas interdit ou quoi que ce soit, mais bon l'idée de partage est un peux bléser.

**Comment by razorex** [comment]
Ahhhh tu nous surveille lolllllllllllll

**Comment by LordVenom** [comment]
Oui je voie tout, je sais tout, Hahahahah :)

**Comment by TmpName** [comment]
N'oubliez pas de cacher votre webcam quand vous vous servez de Vstream.

**Comment by razorex** [comment]
Oui ben après ma collection privé......................

**Comment by LordVenom** [comment]
Vous allez loin la xD

**Comment by Arias800** [comment]
Enfaite LordCenop fait partit de la NSA :p

**Comment by Arias800** [comment]
Enfaite LordVenom fait partit de la NSA :p

**Comment by LordVenom** [comment]
Oui @LordVenom agent infiltrer à votre écoute xD

**Comment by LordVenom** [comment]
ca vous vas si je met la recherche similaire dans la page d'information ?

**Comment by Christian26800** [comment]
Moi du moment qu' on peut y accéder rapidement ça me convient . Merci pour tout votre travail

**Comment by LordVenom** [comment]
Elle est de retour dans le menu contexte comme avant.

**Comment by Christian26800** [comment]
C est bizarre je l ai sur aucun de mes appareils.

**Comment by Christian26800** [comment]
Par contre option bande annonce alors qu' n y étais plus.

**Comment by Christian26800** [comment]
Par contre option bande annonce alors qu' n y étais plus.

**Comment by Arias800** [comment]
@Christian26800 remplace le contenu de gui.py par celui la https://github.com/Arias800/Restaure_ba/blob/master/gui.py

**Comment by LordVenom** [comment]
Non Non faut faire les mises à jour juste remplacer .gui risque de planter l'install

Pour la recherche Similaire dans la prochaine version. Dans quelques semaines.
