### ISSUE TITLE
Sokrostream les réponses n apparaisse pas .

### ISSUE THREAD

**Issue by Christian26800** [Kodi-vStream/venom-xbmc-addons#1711]
Je fais la recherche "saving hope" et les résultats n apparaisse pas .  Alors qu ils fonctionnent lorsqu on va directement aux source

**Comment by LordVenom** [comment]
Bonjour, Quoi ?

![image](https://user-images.githubusercontent.com/4380112/31504729-6e565e30-af73-11e7-9b85-4ccfb47e958e.png)

**Comment by Christian26800** [comment]
![screenshot_2017-10-12-18-00-26-812](https://user-images.githubusercontent.com/32741836/31506362-7df73112-af77-11e7-9d28-567c1d2fad36.jpeg)

**Comment by Christian26800** [comment]
J ai pas du tout les même résultats

**Comment by Christian26800** [comment]
C est ok j ai tout réinstaller et cela fonctionne merci ...😀
