### ISSUE TITLE
zone telech + 1fichier

### ISSUE THREAD

**Issue by thorsten68** [Kodi-vStream/venom-xbmc-addons#1712]
je reviens vers vous pour essayer de trouver une solution a mon soucis
dans vstream pour les liens de zone telechargement, tout fonctionne pour les liens uptobox en streaming (via uptostream),même en 1080p.
par contre j'ai des coupures le soir. j'imagine que la priorité est donné a ceux ayant un premium.

d’où mon souhait de passer par les liens 1fichier vu que j'ai un premium chez eux
mais la rien ne se passe, j'ai une notification qui m'indique 'authentification réussi' puis plus rien.
streaming impossible et telechargement impossible

**Comment by thorsten68** [comment]
NOTICE: Creating Demuxer
10:22:06.607 T:18446744071916448384    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
10:22:06.675 T:18446744071916447104   ERROR: Open - error probing input format, https://1fichier.com/?lypfgtrvib
10:22:06.675 T:18446744071916447104   ERROR: OpenDemuxStream - Error creating demuxer
10:22:06.675 T:18446744071916447104  NOTICE: CVideoPlayer::OnExit()
10:22:06.676 T:18446744071916448384   DEBUG: Thread FileCache 18446744071916448384 terminating
10:22:06.676 T:18446744071916447104   DEBUG: OnPlayBackStopped: play state was 1, starting 1
10:22:06.677 T:18446744071916447104   DEBUG: Thread VideoPlayer 18446744071916447104 terminating
10:22:06.693 T:18446744072444038016   DEBUG: OnPlayBackStopped: play state was 3, starting 0
10:22:06.695 T:18446744072444038016   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=La+Plan%C3%A8te+des+Singes+-+Supr%C3%A9matie+%5BCOLOR+violet%5D1Fichier%5B%2FCOLOR%5D&sHosterIdentifier=onefichier&sTitle=La+Plan%C3%A8te+des+Singes+-+Supr%C3%A9matie+%5BCOLOR+violet%5D1Fichier%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2F1fichier.com%2F%3Flypfgtrvib&sFav=play&sMediaUrl=https%3A%2F%2F1fichier.com%2F%3Flypfgtrvib&sCat=4&sId=cHosterGui&sFileName=La+Plan%C3%A8te+des+Singes+-+Supr%C3%A9matie]

**Comment by thorsten68** [comment]
j'ai déjà bidouillé dans les options de mon compte 1fichier
j'ai essayé de changer de lecteur par defaut (test avec Xbmcplayer) sans succes

**Comment by thorsten68** [comment]
NOTICE: VideoPlayer: Opening:
10:39:36.274 T:18446744072444037376 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:39:36.276 T:18446744071864329088  NOTICE: Creating InputStream
10:39:36.276 T:18446744071864329088   ERROR: CVideoPlayer::OpenInputStream - error opening []
10:39:36.277 T:18446744071864329088  NOTICE: CVideoPlayer::OnExit()
10:39:36.282 T:18446744072444037376   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=Annabelle+2+%3A+la+Cr%C3%A9ation+du+Mal+%5BCOLOR+violet%5D1Fichier%5B%2FCOLOR%5D&sHosterIdentifier=onefichier&sTitle=Annabelle+2+%3A+la+Cr%C3%A9ation+du+Mal+%5BCOLOR+violet%5D1Fichier%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2F1fichier.com%2F%3Fu2s9qwggek&sFav=play&sMediaUrl=https%3A%2F%2F1fichier.com%2F%3Fu2s9qwggek&sCat=4&sId=cHosterGui&sFileName=Annabelle+2+%3A+la+Cr%C3%A9ation+du+Mal]
10:39:36.306 T:18446744072444037376  NOTICE: CVideoPlayer::CloseFile()
10:39:36.306 T:18446744072444037376  NOTICE: VideoPlayer: waiting for threads to exit
10:39:36.306 T:18446744072444037376  NOTICE: VideoPlayer: finished waiting
10:39:36.306 T:18446744072444037376  NOTICE: CVideoPlayer::CloseFile()
10:39:36.306 T:18446744072444037376  NOTICE: VideoPlayer: waiting for threads to exit
10:39:36.307 T:18446744072444037376  NOTICE: VideoPlayer: finished waiting
10:39:36.321 T:18446744071864325888  NOTICE:    [PLUGIN] Vstream: player stoped
10:39:36.598 T:18446744072444037376  NOTICE: VideoPlayer: Opening: https://1fichier.com/?u2s9qwggek|Cookie=SID=uuMDUO5E2dkNjHc2Tk6JBHdHnOAnQKdZIrpx3WKFFpXtksKPFq1clhNjT1MuSI33;
10:39:36.598 T:18446744072444037376 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:39:36.766 T:18446744071864327168  NOTICE: Creating InputStream
10:39:37.252 T:18446744071864327168  NOTICE: Creating Demuxer
10:39:37.342 T:18446744071864327168   ERROR: Open - error probing input format, https://_1fichier.com/?u2s9qwggek
10:39:37.343 T:18446744071864327168   ERROR: OpenDemuxStream - Error creating demuxer
10:39:37.343 T:18446744071864327168  NOTICE: CVideoPlayer::OnExit()
10:39:37.402 T:18446744072444037376  NOTICE: CVideoPlayer::CloseFile()
10:39:37.402 T:18446744072444037376  NOTICE: VideoPlayer: waiting for threads to exit
10:39:37.403 T:18446744072444037376  NOTICE: VideoPlayer: finished waiting
10:39:37.403 T:18446744072444037376  NOTICE: CVideoPlayer::CloseFile()
10:39:37.403 T:18446744072444037376  NOTICE: VideoPlayer: waiting for threads to exit
10:39:37.403 T:18446744072444037376  NOTICE: VideoPlayer: finished waiting
10:39:37.421 T:18446744071864325888  NOTICE:    [PLUGIN] Vstream: player stoped
10:39:56.223 T:18446744071864325888  NOTICE:    [PLUGIN] Vstream: Closing player
10:39:56.233 T:18446744071864325888  NOTICE:    [PLUGIN] Vstream: Table initialized
10:40:04.841 T:18446744071864312448 WARNING: CPythonInvoker(9): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.

**Comment by TmpName** [comment]
error probing input format
Ca a l'air d'etre un prb de codec. Essayes plutot de telecharger le fichier et de voir si il passe sous kodi.

**Comment by thorsten68** [comment]
Ça me fait ça pour tous les fichiers, mkv ou bdrip d'1fichier. Alors que le même s'ouvrira sur uptobox.
Je regarde tout a l'heure pour le paramétrage d'1fichier

**Comment by Arias800** [comment]
Je suis le seul a trouve le _ entre  https:// et  1fichier.com/?u2s9qwggek bizarre ?

**Comment by thorsten68** [comment]
C'est moi qui l'ai rajouté pour pas avoir de lien illégal

**Comment by thorsten68** [comment]
C'est moi qui l'ai rajouté pour pas avoir de lien illégal

**Comment by Arias800** [comment]
Ah ok bonne initiative ^^

**Comment by TmpName** [comment]
Et si tu essayes de telecharger le fichier au lieu de le streamer (en menu contextuel), pas besoin de dl la totalitee pr tester.

**Comment by thorsten68** [comment]
Ça plante aussi, 'début téléchargement' puis 'téléchargement arrêté' dans la foulée.
Sur tous types de fichiers (1fichiers)

**Comment by thorsten68** [comment]
C'est moi qui l'ai rajouté pour pas avoir de lien illégal

**Comment by thorsten68** [comment]
Eureka !!!!!! Merci tmpname !!!
Tu avais raison ! Il suffisait de décocher 'afficher un menu de téléchargement' dans les paramètres d'1fichier !!!
Je me prosterne !!

**Comment by thorsten68** [comment]
Eureka !!!!!! Merci tmpname !!!
Tu avais raison ! Il suffisait de décocher 'afficher un menu de téléchargement' dans les paramètres d'1fichier !!!
Je me prosterne !!

**Comment by thorsten68** [comment]
Je vous kiff merci !!
