### ISSUE TITLE
Recherche zone_telechargemnt.ws hs?

### ISSUE THREAD

**Issue by Gregwar** [Kodi-vStream/venom-xbmc-addons#1715]
La recherche sur zone telechargement semble HS pour moi, vous confirmez?

**Comment by Arias800** [comment]
Oui elle est HS pour le moment

**Comment by TmpName** [comment]
Marche tres bien chez moj, suffir de mettre a jours l'url https://ww1.
Apres je sais pas si elle chnage toute seule ou si elle est fixe.

**Comment by Arias800** [comment]
Ok j'avais essayer hier et ca n'avais pas marche x) Merci du coup de main

**Comment by svader13** [comment]
Salut 

Je n'ai pas compris ta manip pour refaire fonctionner zone téléchargement sur vtream

**Comment by luluvulcain** [comment]
Pour remédier au Problème de Zone telechargement et autres, il suffit de telecharger ma version modifié de l’extension en fichier zip au https://github.com/luluvulcain/vStream-Kodi
Ensuite de désinstaller vstream et d'installer ma version comme ça l’extension sera a jour et tout remarchera.

**Comment by svader13** [comment]
Merci pour ta réponse  je vais essayer

**Comment by svader13** [comment]
Impeccable ça  marche nickel même  pour les animes qui n'avait jamais marchés  auparavant avant

**Comment by svader13** [comment]
Bonjour

C'est normal que cela ne refonctionne plus zone telechargement

**Comment by TmpName** [comment]
Yep https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1698#issuecomment-337191410

**Comment by luluvulcain** [comment]
Chez moi aussi, zone telechargment ne marche plus

**Comment by svader13** [comment]
😭😭😭😭



Envoyé depuis mon Téléphone Mi
Le luluvulcain <notifications@github.com>, 17 oct. 2017 8:30 PM a écrit :

Chez moi aussi, zone telechargment ne marche plus

**Comment by frankmandude** [comment]
moi aussi

**Comment by LordVenom** [comment]
Voir le post de @TmpName Merci
