### ISSUE TITLE
Manque dossier SÉRIES en Vstream

### ISSUE THREAD

**Issue by mlh77** [Kodi-vStream/venom-xbmc-addons#1716]
Je trouve plus le dossier Séries , j'ai desinstaller et  réinstaller de nouveau toujours le même problème. 
Pouvez vous m'aider s'il vous plaît. 
Merci

**Comment by mlh77** [comment]
Je trouve plus le dossier Séries , j'ai desinstaller et  réinstaller de nouveau toujours le même problème. 
Pouvez vous m'aider s'il vous plaît. 
Merci

**Comment by TmpName** [comment]
C'est quoi le dossier serie ?

**Comment by mlh77** [comment]
La page d'accueil ou on trouve les films les derniers ajouts et les séries

**Comment by LordVenom** [comment]
Fait un screen pars ce que la c'est bizarre

**Comment by TmpName** [comment]
Lol, je dois pas avoir la meme version non plus ^^

**Comment by mlh77** [comment]
Je l'ai supprimé et j'ai telecharger du nouveau
