### ISSUE TITLE
filtre de recherche

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#1717]
bonjour, j'ai une question le filtre de recherche (que je n'utilisais pas) a été intégré sans possibilités de le désactiver 
ou il a été supprimé ? 
je tiens au résultat de recherche hs pour découvrir des films ou autres inconnu
si il est intégré ou est t'il que je l'enlève chez moi

**Comment by LordVenom** [comment]
Supprimer dans la 5.5.
