### ISSUE TITLE
Reparation de l'Extension !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1719]
Bonjour, j'ai trouver une solution pour remédier ou bug ou autre sur vStream. Je m'explique : 
- J'ai changer manuellement et informatiquement les fichiers corrompus de vStream depuis le site, 
je les ai mis dans l’extension, ensuite ré-compresser l’extension en zip en renommant le nom et ensuite désinstaller l'addon et installer ma version en laissant le repo installer et comme çà l'extension est à jour sans attendre la mise à jour automatique.

Est-ce que je peux mettre en ligne en issue sur le Site le lien du fichier de l’extension que j'ai modifié pour les gens presser qui veulent pas attendre la mise a jour automatique ?

Cordialement,
Luluvulcain

**Comment by Arias800** [comment]
Tu la ré-compresser quand parce que la en pull request j'ai mis lu fix pour zone-téléchargement donc a moins que tu l'ai pris en compte çà fait un problème non réparer avec ta solution

**Comment by luluvulcain** [comment]
Oui Arias800, j'ai tenu compte du fix pour zone telechargement car j'ai pris les codes du fichier (https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py) donc pas de probleme.

**Comment by Arias800** [comment]
Non y a pas le dernier pull request car le dans URL_MAIN il n'y a pas le 1 c'est celui la le dernier pull request mais il n'a pas été accepter https://github.com/Kodi-vStream/venom-xbmc-addons/pull/1718

**Comment by luluvulcain** [comment]
Ok merci Arias800, je vais le modifié mais est-ce que ma solution peux être validé ou pas ?

**Comment by Arias800** [comment]
Le probleme c'est qu'il faut refaire une fichier zip a chaque modif mais bon perso je suis pas contre que passe le lien sur l'issue en rapport avec dl protect (avec ma toute dernière modif) pour ceux qui veulent un retour rapide de zt

**Comment by luluvulcain** [comment]
Ok Arias800, je fais ca car j'aime cette extension et j'aimerais aider a son bon fonctionnement. Comment deviens ton Contributeur (Contributor) ?

**Comment by LordVenom** [comment]
Bonjour, 

Pour avoir une version Beta 2 solution
- Utiliser un grabeur Github  https://desktop.github.com/
- Voir sur la page Home / Contribuer / Télécharger la Bêta. (ça fait un zip de la beta directement)

Note : Les Pulls Request non validés ne sont pas dispo dans la bêta.

**Comment by luluvulcain** [comment]
Ok merci du renseignement LordVenom. Si je peux aider au bon fonctionnement de vStream, ça sera avec plaisir

**Comment by LordVenom** [comment]
Pas de soucis Prend un siège, installe toi bien et go :)
