### ISSUE TITLE
chargement des catégories mais rien ne se passe...

### ISSUE THREAD

**Issue by plasmotek** [Kodi-vStream/venom-xbmc-addons#1721]
Bonjour, je suis bloqué sur le menu principal de v-stream. 
Lorsque je rentre dans une catégorie (film par exemple) la fenêtre de dialogue s'ouvre, le chargement démarre puis s'arrête et plus rien.
Dans les paramètres de Vstream lorsque j'efface les caches ou autres une erreur extension apparait.
j'ai bien sur désinstaller puis réinstaller Vstream mais rien à faire...
Kodi 17.4 - android tv 6.0.1

merci pour votre super boulot avec V-stream !!

**Comment by TmpName** [comment]
Il nous faudrait le log stp.

**Comment by plasmotek** [comment]
désolé j'ai du mal à l'extraire de la box. xiaomi mi box . je ne peux pas écrire sur un disc externe depuis la box. je vais voir pour l'upload sur un cloud

**Comment by LordVenom** [comment]
VStream inclus un system simple d'upload pour le log.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by plasmotek** [comment]
oui ce que j'ai vu, mais j'ai une erreur quand je tente d'upload

**Comment by TmpName** [comment]
Un caractere accentue dans ton chemin d'accee ?

**Comment by plasmotek** [comment]
non du tout, chemin classique android

**Comment by plasmotek** [comment]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1403074/kodi.log)

**Comment by LordVenom** [comment]
Ca te le fait sur tout les sites ou juste sur film_illimit?

note : tu as bien pourris ton installation avec Indigo et Ares Wizard vire tous ça.

**Comment by plasmotek** [comment]
non ça le fait sur tous les sites
Ares c'est naze ?

**Comment by plasmotek** [comment]
je pense que je vais faire une fresh install. je me servais d'Ares pour les backup et un coup de clean de temps en temps... une meilleur alternative ?

**Comment by LordVenom** [comment]
Déja une installe propre de vstream, vider les caches voir vStream ./paramètre / outils.
Puis désinstaller vStream et le réinstaller depuis notre repos.

**Comment by plasmotek** [comment]
aucune action depuis outils ne marche

**Comment by plasmotek** [comment]
a oui depuis le dossier, pardon

**Comment by TmpName** [comment]
Deja une installation propre de kodi sans passer par ARES.

**Comment by plasmotek** [comment]
j'ai jamé installé Kodi en passant par ares... je me sert d'ares pour la maintenance ou pour restore des backup

**Comment by LordVenom** [comment]
Pourquoi avoir un advancedsettings tu as des bug de lecture ?
Pourquoi script.tv.show.next.aired ce lance toute les 10s ?
Pourquoi Indigo ce lance au démarage ?
Pourquoi plugin.video.bob.unleashed lance un service qui plante ?
Pourquoi Ares Wizard ce lance au démarage?

Bref tu a compris l'idée. c'est la merde xD
Si tu veut faire un backup utilise l'addon de base de Kodi dans leur repository 
http://kodi.wiki/view/Add-on:Backup

Le faite d'installer un addon dans un autre repo que l'officiel ne veut pas dire que tu as le même fichier des transformation peuvent être faite.

**Comment by TmpName** [comment]
C'est ce que j'allais dire mais j'etais pressé, regarde le log, pour une appli qui ne sert que pour la maintenance, elle apparait bien placee dans les logs. Le prb de ce genre de truc, c'est que meme toi qui l'utilise tu ne peut pas savoir ce qui a ete modifie sur ta version de kodi, alors nous .....

**Comment by plasmotek** [comment]
ok, advanced settings, je ne sais pas ce que c'est
- script.tv.show non plus
- indigo est installé automatiquement avec exodus, je ne l'utilise pas mais apparement je dois le garder ?
- bob unleashed, aucune idée non plus, je vais le désintaller
- Ares au démarrage, je ne savais pas non plus. je vais le désintaller aussi du coup. 

vous utilisez quoi pour la maintenance ?

**Comment by LordVenom** [comment]
Aucune maintenance sur mon ordi de salon le seul truc qu'il fait sais ce mettre à jour xD

J'ai renommer correctement mes films et series pour le scan de la base de donnée, comme ça quand ça merde ça met 1h grand max a être réinstaller.

**Comment by plasmotek** [comment]
tu n'effaces pas les thumbnails et autres merdes qui squattent le disc ?

**Comment by LordVenom** [comment]
Non c'est que des images et des base de donnée ça permet de rendre Kodi plus réactif.

**Comment by plasmotek** [comment]
ok je comprends, mon Kodi est installé sur une xiaomi mi box, pas beaucoup d'espace dessus, j'essaye de ne pas trop laisser Kodi s'étaler.

merci beaucoup pour les conseils !!
dernière petite question :D, métalliq et v-stream sur Kodi 17 ??

**Comment by LordVenom** [comment]
métalliq c'est l'addon qui permet de chercher sur tout les autres addon via une recherche TMDB. Pfff
La recherche Visuelle de vStream c'est TMDB.

**Comment by TmpName** [comment]
Ok, pour infos les addons qui servent a "virer les merdes" ne servent a rien si tu n'utilises pas les fanarts. Tu n'auras pas de probleme de place.
Vas voir toi meme la place que ca prend sur le disque dur, et compare avec ton espace total.

**Comment by nabsboss** [comment]
Bonjour,

J'ai exactement le même problème et c'est une installé propre sans ares ou autre.
Pour info, j'ai commencé à avoir ce problème en vidant tous les caches, en désinstallant puis réinstallant vstream. Je ne sais pas si ça à un lien mais voilà comment tout à commencé pour moi.
Peut-être que c'est dû à une mise à jour et qu'en vidant les caches,etc.. cela met en avant un bug qui ne pouvait être visible.
Voici les logs: 
https://slexy.org/view/s21PufYyKQ

Upload des logs n'a pas fonctionné également pour moi.

Merci pour votre aide !!

**Comment by nabsboss** [comment]
I confirme that there is a bug on themoviedb_org.py
I replace it with an old version and it worked like a charme !

**Comment by TmpName** [comment]
Ha ?
Par contre je ne comprend pas ton message d'erreur.
'''Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/runscript.py", line 13, in <module>
                                                from resources.lib.util import VStranslatePath
                                            ImportError: No module named util'''

Tu n'as pas de fichier util dans le repertoire resources/lib ?

**Comment by nabsboss** [comment]
Si, j'ai bien un fichier util.py

**Comment by LordVenom** [comment]
Oui themoviedb_org est HS mise à jour ce week end.

**Comment by nabsboss** [comment]
OK merci ;)

**Comment by nabsboss** [comment]
Désolé mais après la maj ça ne marche toujours pas :(
https://slexy.org/view/s2NNMvP9rI

**Comment by nabsboss** [comment]
Bonjour,

Pourquoi le ticket à été fermé ?

**Comment by TmpName** [comment]
Car la suite se trouve sur un autre post.
