### ISSUE TITLE
recherche sur streaming hds.to ?

### ISSUE THREAD

**Issue by flogith** [Kodi-vStream/venom-xbmc-addons#1725]
Bonjour,
tout d'abord, bravo et merci pour votre plugin!
j'ai découvert récemment le site de streaming hds.to, qui est anciennement hd-stream je crois.
J'aimerais savoir si vstream liste le contenu provenant de ce site?
les sources ont l'air vraiment stable, d’où ma demande.
merci d'avance pour votre réponse!

**Comment by LordVenom** [comment]
Oui c'est kaydo
