### ISSUE TITLE
Probleme Zone Telechargement !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1726]
J'ai installer ma version modifiée et après j'ai fait la mis a jour automatique et depuis les liens de zone telechargement sont ilisible ? Pourriez vous m'aider s'il vous plait ?

Cordialement,
Luluvulcain

**Comment by billouetaudrey** [comment]
Bonjour, une petite recherche rapide 👍 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1715

**Comment by luluvulcain** [comment]
Merci mais zone telechargement ne marche vraiment plus chez moi, il se lance plus

**Comment by Arias800** [comment]
Sûrement parce que il ont fait une autre modif vu que actuellement il aime foutre le bordel

**Comment by frankmandude** [comment]
ca fonctionne chez moi

**Comment by Arias800** [comment]
@luluvulcain quel version de kodi ?

**Comment by dream77270** [comment]
bonjour, est-ce que quelqu'un sait quand il y auras une nouvelle mise a jour pour regler le probleme de zt.
merci a tout ceux qui participent à l'amélioration de cette extension.

**Comment by TmpName** [comment]
Suite la bas.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1698#issuecomment-337646613
