### ISSUE TITLE
Problème Trakt.tv

### ISSUE THREAD

**Issue by Allinou** [Kodi-vStream/venom-xbmc-addons#1727]
Bonjour,
D'abord merci pour vStream.
J'ai un problème depuis plusieurs mois avec Trakt TV
J'ai une erreur lorsque je choisi le menu Trakt (Beta) dans VStream
Voici le log: https://slexy.org/view/s2HBXtc90W
Pouvez-vous m'aider ?
Merci
Alain

**Comment by LordVenom** [comment]
Deco toi de Trakt et reco

**Comment by Allinou** [comment]
J'ai essayer plusieurs fois de deconnecter et reconnecter avec le code "ACTIVATE"
Info supplémentaire: Je vois 2 erreurs dans le log https://slexy.org/view/s2HBXtc90W à la ligne 627:
-------------------------
12:13:39.366 T:18446744073505610032   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=getLoad&sFav=getLoad&site=cTrakt&siteUrl=http%3a%2f%2fvenom&title=Trakt%20(b%c3%aata)
12:13:39.371 T:18446744073505610032   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=getLoad&sFav=getLoad&site=cTrakt&siteUrl=http%3a%2f%2fvenom&title=Trakt%20(b%c3%aata)) failed

**Comment by LordVenom** [comment]
Tu est a jour ? version 0.5.5 les reste de l'addon fonctionne?

**Comment by Allinou** [comment]
Oui 0.5.5 tout fonctionne nickel par le repo
J'ai essayé d'effacer le cache par le menu "a propos" d'installer/reinstaller Vstream et Trakt sans succès

**Comment by LordVenom** [comment]
Vas sur https://trakt.tv/ - Settings - Connected App

Ya vStream ?

**Comment by Allinou** [comment]
non il y a 'trakt for kodi' mais pas 'vstream'.
Il etait présent alors que j'avais déjà ce probleme. Pour tenter de résoudre j'ai effacé les connected app : 'trakt for kodi' et 'vstream'
Après réinstallation et connection, seul 'trakt for kodi' est présent

**Comment by LordVenom** [comment]
Je pense que j'ai reussis a reproduire le bug.

Modifie le fichier 
Télécharge : https://github.com/Kodi-vStream/venom-xbmc-addons/raw/Beta/plugin.video.vstream/resources/lib/trakt.py

Et remplace le fichier du dossier plugin.video.vstream\resources\lib
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-vStream

**Comment by LordVenom** [comment]
https://cdn.discordapp.com/attachments/362558547088900097/370537192646377472/Sans-titre-2.jpg

**Comment by Allinou** [comment]
Alors là, bravo... quelle efficacité ! 
Ca fonctionne !
VStream est au top avec mise a jour régulière. Super !
J'apprécie le petit plus la connexion avec Trakt.
Merci

**Comment by LordVenom** [comment]
Merci pour le retour et le rapport supers propre :)
