### ISSUE TITLE
Free-Telechargement + Zone Telechargement HS 

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#1728]
Salut à tous
Je suis en version 0.5.5 et quand je clique sur un lien ZT rien ne s'affiche, y'a plus les liens url
Et sur FT c'est pareil.

Quelqu'un a une solution ? Merci

**Comment by luluvulcain** [comment]
Salut lebigboss, pour régler le problème de zone telechargement, 
telecharges ma version modifiée au https://github.com/luluvulcain/vStream-Kodi,
et ensuite installe la sans désinstaller vstream.

Cordialement,
Luluvulcain

**Comment by toadnam** [comment]
Salut luluvulcain, apparrement le code a du etre modifié, les liens sont à nouveau vide... :-(

**Comment by Arias800** [comment]
Si le code a été modifié a ma prochaine modif normalement ça va être rétabli et on devrai plus entre embêté par le changement de nom

**Comment by chataigne73** [comment]
vous faites unpeu de zèle en terme de modifs les gars : la version commitée hier par Tmpname fonctionne encore très bien, rien n'a changé depuis ... suffisait donc pour ceux qui ne l'ont pas déjà fait d'aller chercher le fichier sur la beta

et tes nouvelles modifications Arias800 ne marcheront plus si le site de cryptage change encore de nom (c'est ta ligne 595 qui n'est pas bonne ; il faut récuperer URL_DECRYPT de manière dynamique)

**Comment by toadnam** [comment]
En tout cas, je tiens à préciser que vous êtes au top les gars !
Je viens d'installer la version modifiée de luluvulcain et ça tourne au top sur zt. 
Bonne soirée à tous .
Et encore merci

**Comment by Arias800** [comment]
Oui je m'occupe de récupérer URL_DECRYPT de manière dynamique demain

**Comment by luluvulcain** [comment]
Merci toadnam. Si je peux aider, je le fais. Pour infos, ma version modifiée marche car je l'ai tester chez moi et pour zone telechargment, j'ai pris le fichier de Tmpname.

**Comment by toadnam** [comment]
Oui je confirme elle marche du feu de Dieu . Je suis entrain de look une série grâce à ça... Merci à vous , parce que je trouve que uptobox pour lire c'est le plus stable , comparé à netu ou autre...

**Comment by cnene7878** [comment]
Bonjour LordVenom,

J'ai deja mis sur mon serveur QNAP la version modifiée de luluvulcain, mais aucun resultat, toujours le message "erreur site dl-protecte HS" , alors qu'effectivement ça remarche sur mon tel Android et sur mon ipad. 
J'ai essayé toute les mises à jour sur mon QNAP mais rien y fait, depuis juillet aout ça n'a jamais refonctionné malgré de nombreux essais ( desinstallation de kodi , installation kodi 16 kodi 18 mais toujours exactement le meme message! ). La source Zone-telechargement a toujours très bien marché depuis 2 ans mais depuis cet été ça n'a jamais remarché malgré toute vos mise a jour sur mon serveur. 

Mon log avec l'erreur est dispo sur Issue #1734

**Comment by LordVenom** [comment]
Pas de soucis avec la dernière version : 

![image](https://user-images.githubusercontent.com/4380112/31790628-641dded6-b516-11e7-96a1-ce7aaca602c2.png)

**Comment by cnene7878** [comment]
Jusqu'a cet écran ça marche aussi pour moi mais il ne me donne jamais le dernier lien, j'ai le message erreur dl-protecte HS. 

Je me repete mais en faisant exactement les meme manip sur la tablette ou android ça fonctionne. 

Je suis habitué des manipulations informatique mais pas en programmation !

**Comment by cnene7878** [comment]
Avez vous regarder mon log ? Le log de l'erreur est avec la meme version VSTREAM et modif que la version de VSTREAM sur mon tel ANDROID et IPAD qui fonctionne.

**Comment by LordVenom** [comment]
Non mais ça tourne la lecture pour moi. ton fichier ne doit pas être a jour.

Prend ce fichier : https://github.com/Kodi-vStream/venom-xbmc-addons/raw/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

Et remplace celui de plugin.video.vstream\resources\sites

Info dossier vStream : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-vStream

**Comment by LordVenom** [comment]
Sinon patience 3jours, @TmpName  à lancer une mise a jour aujourd'hui.

**Comment by cnene7878** [comment]
Tu fais tourner sur quel environnement ? 
Je vais essayer ta manip mais vu tout ce que j'ai deja fait depuis juillet , je pense que mon environnement QNAP est le problème, c'est pour ça que j'ai publié mon log.
je le fais fonctionné avec toute vos modif sur les autres environnement !

**Comment by cnene7878** [comment]
En fait j'ai deja fait ta manip de remplacer le site par la version beta, mais pas plus de resultat

**Comment by cnene7878** [comment]
Manip refaite au cas ou... toujours HS, désespérant :( 
Depuis juillet je me contente de me servir de la source zone-telechargement avec mon telephone Android pour streamer via localcast vers mon serveur. 
Si jamais une solution est trouvée ce serait super !

**Comment by LordVenom** [comment]
Je comprend pas trop ton system mais une recherche avec QNAP et URLError ne donne rien ?

**Comment by cnene7878** [comment]
non je n'ai rien trouvé, le QNAP est une base linux

**Comment by LordVenom** [comment]
Le problème avec les versions linux c'est quel ont leur propre version de python, le system windows et android c'est inclus dans Kodi. Donc si tu as un soucis avec ta version de python c'est la mort.Mais bon si l'addon fonctionne partout sauf sur cette source...

**Comment by LordVenom** [comment]
Ce que tu peux faire c'est vider tous les caches voir Parametre de l'addon / outil puis tester la bêta.

https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by cnene7878** [comment]
Bon toujours la meme ! 
Oui en general les autres sources fonctionnent, mais depuis juillet zone-telechargement veut plus rien savoir ! grrr

**Comment by LordVenom** [comment]
Ben je sèche peux être que d'autre auront une idée.

**Comment by cnene7878** [comment]
J'avoue le serveur c'est un peu particuliers, heuresement que j'ai mon tel et l'ipad !! :)
Sans VSTREAM ma vie s'arrete !! mdr

**Comment by cnene7878** [comment]
merci en tt cas ;)

**Comment by chataigne73** [comment]
FT corrigé normalement

**Comment by TmpName** [comment]
Ca pourrait etre un prb SSL.
Le plus simple c'est d'interroger directement la page web avec les outils sur ton NAS, et de voir si la connexion se fait.
Tu peux aussi activer le mode deboguage de kodi avant le bug pour avoir plus d'info sur le log (plus d'infos ccurl ou urllib par exemple)

**Comment by Arias800** [comment]
Maintenent il pourront changer leurs nom pour le site de cryptage normalement ca devrai plus posé probleme

**Comment by billouetaudrey** [comment]
ZT OK mais les liens apparaissent vides lorsque je clique sur l'hébergeur souhaité, pas vous ?

**Comment by Arias800** [comment]
Essaye avec celle la https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by billouetaudrey** [comment]
Ça Marche ! Je pensais que celle push aujourd serait fonctionnel :)
Merci beaucoup :)

**Comment by mino60** [comment]
@cnene7878 je croix que le problème c'est le fichier seting.xml  voici un vieux fichier de 2014 compatible avec le système Linux si ça peux t'aider !!?..

https://www.mediafire.com/file/ktk70ft6m9jrvby/dossier_sans_titre.zip
https://mon-partage.fr/f/vBzGu8l0/

**Comment by cnene7878** [comment]
Merci mino60, je vais faire un test, je vous ferai un retour ça peut servir à d'autre !

**Comment by cnene7878** [comment]
Bon j'ai essayé, ça ne fonctionne toujours pas, toujours le même message " erreur DL-PROTECTE HS " ...

**Comment by mino60** [comment]
Est ce que tu a fait une mise à jour du système Linux et Kodi ???
essaye d'activer URL resolver dans les paramètres de vstream si non mettre à jour python 2.7.8

**Comment by TmpName** [comment]
Dans les logs, tu as plus d'infos, sauf si c'est un probleme de connexion, cas du timeout.

**Comment by cnene7878** [comment]
Kodi est en 17.4 mais j'ai testé également en version 16 et 18. 
Mettre à jour Linux sur le QNAP impossible. URL resolver je l'utilise deja avec un abonnement real-debrid.
J'ai mis Python à jour en 2.7.14.
Mon log est en PJ...
[log.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1411871/log.txt)

**Comment by madmocas** [comment]
cnene7878
je pense que c est la version de kodi tu est dans le même cas que moi c est mykody17 de fathermade

**Comment by cnene7878** [comment]
Madmocas, j'avais déjà essayé kodi 18 sans résultat, mais sur la piste que tu m'as donné et avec un peu d'acharnement, sur le site forum.qnap.com, il distribue une version 17.4.2 avec un mise a jour specifique de Python ! (THIS version is the same as 17.4 + a specific updated Python engine for some add-ons that don't works with QNAP delivery) 
Et miracle ça remarche  ! 
Donc c’était bien un problème lié à la version de python...  

Merci à yous pour votre aide ! et merci a tout ceux qui travaillent sur l'addons !

**Comment by madmocas** [comment]
tu peux me dire le lien car j ai le même problème

**Comment by cnene7878** [comment]
Yes !
https://www.father-mande.ovh/Q/F/mykodi17_17.4.2.zip

**Comment by madmocas** [comment]
merci

**Comment by LordVenom** [comment]
C'est Résolut ?

**Comment by cnene7878** [comment]
Pour c'est résolu !

**Comment by madmocas** [comment]
Pour moi aussi résolu
