### ISSUE TITLE
Zone telechargement HS depuis plusieurs mois ( NAS QNAP )

### ISSUE THREAD

**Issue by cnene7878** [Kodi-vStream/venom-xbmc-addons#1734]
Bonjour, 

Depuis le mois d'aout ou meme juillet, zone téléchargement ne marche plus du tout sur kodi 17.4 installé sur un serveur QNAP. 

J'ai systématiquement le message " erreur site DL protecte HS" malgré les mises a jour de Vstream.

J'ai essayé plusieurs versions de KODI idem... 

J'ai ouvert le log et découvert cette erreur : 'URLError' object has no attribute 'read' ( en PJ le log )

Je pense qu'il y a des gens qualifiés ici pour peut être trouver le problème !

J'ai kodi installé également sur un Ipad et Un telephone Android et ça fonctionne. 

Sur mon QNAP ça a longtemps marché, jusqu'a ce mois d'aout ou juillet en gros et depuis plus rien, toujours ce satané message " erreur site DL protecte HS"

J'éspère que vous trouverez un moyen de résoudre ce beug :)

Merci 

Log : https://pastebin.com/rVFGaJKC

**Comment by LordVenom** [comment]
Voir https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1728
