### ISSUE TITLE
Mettre en marque page.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#1736]
Bon alors la comprend pas, ce soir j'ai voulu mettre en lien en marque page, et je ne retrouve plus le raccourcis dans le menu (apres avoir fait une recherche).
De memoire y avait pas "Mettre en marque page" en couleur quelque part ?
Il y a bien une option "marque page" mais elle ouvrait la page des marques pages.
La MAJ date de 19 jours, et je ne m'en rend compte que ce soir, quelqu'un peut me rassurer ?

**Comment by LordVenom** [comment]
Houla Tu a pris la dolorean de retour vers le futur xD

Le lien ce nomme Marque-page, il n'existe plus de raccourcis pour aller au marque page dans le menu context.La couleur à aussi était supprimer.

**Comment by TmpName** [comment]
Put1 mais depuis quand ?
Je veux bien que j'ai de gros prb de cache, mais m'en suis apercu que hier !
Je retrouvais plus le menu.

**Comment by Arias800** [comment]
Ca fait effectivement un petit moment qu'il n'y a plus le menu ^^ de tete je dirai presque 1 mois

**Comment by LordVenom** [comment]
Plus que ça ça date du 24 juillet 

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/46cb430b8a3d028dbadd4dcae0ade24497581eef#diff-0a24ba342b7241ee44ff6f007e005d4b

Sacré cache que tu as la xD

**Comment by TmpName** [comment]
XD.
Le pire c'est que je suis serieux, j'ai mis en marque page 2 series la semaine derniere sans probleme, et la j'ai modifie le fichier langue, mais apres 1 redemarrage total, j'ai toujours pas la modif active.

**Comment by LordVenom** [comment]
Tu as deja tester ça ? http://kodi.wiki/view/HOW-TO:Modify_the_cache

**Comment by TmpName** [comment]
J'ai trouve la technique depuis, il me faut passer par le menu parametre de Vstream et utiliser clear cache addon.
Mais c'est pas le truc auquel tu penses quand ca t'arrives d'un coup, ma premiere reaction a été "put1 mais y a eu une MAJ sauvage ?" ou "Suis bourre au point de ne plus trouver le menu ?"
