### ISSUE TITLE
Depannage Rapide de vStream !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1741]
Si vous voulez corriger les Bugs et autres de vStream, il vous suffit de telecharger mon Patch que je mets régulièrement à Jour sans désinstaller l’extension au https://github.com/luluvulcain/vStream-Kodi

**Comment by LordVenom** [comment]
Propose ta modif en Pull ça c'est valider ça passeras dans la mise a jour auto :)

**Comment by luluvulcain** [comment]
Oui mais moi je fais la modif manuellement en reprenant les modif des codes deja fait pour les utilisateurs de vStream, LordVenom.

**Comment by TmpName** [comment]
Et on fait pas ca avec la beta ^^ ?
Car du coup legalement, on ne peut meme pas copier directement ton code pour le mettre en officiel car tu es "propretaire" du code de ton github.

**Comment by LordVenom** [comment]
J'ai pas compris en faite, les modifs faite dans la bêta tu les reprends pour en faire un zip.

- Pas besoin de réécrire un code si il et sur le github tu as un boutton RAW qui te permet de chopper le code brut ou même d'enregistrer la page et donc d'avoir le fichier direct.
- En accueil sur notre github y a un lien pour télécharger la bêta.

Aprés quelqu'un qui n'a pas les bases pour copier un fichier et le remplacer n'a pas besoin de la bêta, pour ma part seul ceux qui font des retours devrais utiliser la bêta.

**Comment by billouetaudrey** [comment]
Bonjour,

Je n'y connais rien en Github etc... mais pourquoi ne pas donner la possibilité de télécharger directement les beta a l'aide de kodi ( en cochant par ex " Beta " dans les paramètre de Vstream ) ?

**Comment by luluvulcain** [comment]
Vous avez pas compris. Je m'explique : 
Pour faire bref, je mets a disposition manuellement les modification de l'addon faite sur la Beta pour les utilisateurs pressés et inexpérimentés de vStream pour qu'il puissent régler les problèmes liés à l’extension. 
Car faut savoir, quand téléchargent le fichier zip de la Beta, ca marche pas (j'ai essayé). Je fais ca car je me suis retrouver dans cette situation et j'ai trouver cette astuce en la testant. Si vous voulez LordVenom et TmpName, je peux faire ça sur la Beta mais vu que c'est les mêmes codes, j'en vois pas l’intérêt. Après, si ça vous gêne que je fasse ça, dites-le moi et j’arrêterais sans problèmes (Je penses juste à faire partager mon astuce aux gens, voila tout). Quand pensez-vous ? L'idée de billouetaudrey est pas mal.

**Comment by toadnam** [comment]
Pour ma part , je remercie toute  l'équipe et luluvulcain pour ses patchs car je m'en sers pour mettre à jour zt. 
Je trouve que c'est pratique. Je m'explique , je vais sur vstream, je lance ma recherche si je vois que zt ne fonctionne pas , je vais sur le lien de luluvulcain, je regarde s'il y a une mise à jour ,en général oui car il est réactif, je la telecharge, je l installe et je relance vstream et zt me donne des résultats. 
Pour moi vous êtes tous au top !

**Comment by johngf** [comment]
@luluvulcain avec la beta ça fonctionne mais faut pas cliqué sur mise a jour sinon ça te ré installe la master.

**Comment by LordVenom** [comment]
La version de @luluvulcain c'est la version en cours avec les sites et hots de la beta.

**Comment by TmpName** [comment]
Ben ce qui me gene c'est le concept de beta.
Tu dis mettre a "disposition manuellement les modification de l'addon faite sur la Beta pour les utilisateurs pressés et inexpérimentés de vStream pour qu'il puissent régler les problèmes liés à l’extension" et c'est ca le probleme.
Le support ne se fait que sur la version officielle, pas la beta, il y a des moment ou la beta est HS car on teste de nouveaux fichiers. La beta est la pour les personnes experimentées justement, pas pour resoudre les bugs.
La personne qui veut installer la version beta devrait le faire pour aider au developpement, pas avoir en avance une version qui a de forte chance d'etre bugguee.

**Comment by luluvulcain** [comment]
Oui TmpName, je mets à disposition manuellement les modification de l'addon faite sur la Beta pour les utilisateurs pressés et inexpérimentés de vStream pour qu'il puissent régler les problèmes liés à l’extension. Après je te confirme que ça marche car j'ai tester avant de la partager. Ensuite, il faut que je teste mon Patch pour voir après avoir installer la mise à jour auto si ça bug. Je peux comprends ta réaction mais moi je parle pour les Utilisateurs. J'ai parler avec LordVenom de ça.
