### ISSUE TITLE
Tvrex+Navixpsort

### ISSUE THREAD

**Issue by JaqenGOT** [Kodi-vStream/venom-xbmc-addons#1743]
Bonsoir,
Je voulais savoir si c'était possible de mettre à jour ces 2 sites pour les matchs de NBA en priorité vu que la saison vient de reprendre. Pour tvrex le replay fonctionne mais le live n'a jamais fonctionné depuis que le site est sur vstream. Pour Navixsport le live fonctionnait pour la saison dernière mais depuis la reprise de la saison aucun lien de disponible.
Merci

**Comment by JaqenGOT** [comment]
Bonjour, aucune réponse de la team ou de personne qui pourrait corriger le problème?
Merci d'avance

**Comment by razorex** [comment]
Salut je vient de faire Navixsport tu pourra tester lors des prochains live stp

**Comment by JaqenGOT** [comment]
Bonsoir @razorex, encore merci pour ton aide je manquerais pas de faire un retour dès que possible.

**Comment by JaqenGOT** [comment]
Bonjour,
Alors hier soir j'ai fait un test pour un match en live mais ça n'a rien donné. Toujours aucun lien de disponible.

**Comment by razorex** [comment]
@JaqenGOT tu avait fait la mise a jour de navixsport

**Comment by JaqenGOT** [comment]
Oui même en ayant fait la mise à jour. J'ai fait le test hier soir, la liste des matchs apparait mais toujours aucun lien pour le visionner. De plus le replay des match sur TVrex ne fonctionne plus.

**Comment by JaqenGOT** [comment]
Bonjour, @razorex alors hier soir j'ai pu regarder le match Cavs-Pacers sur Navixsport, mais concernant les autres matchs de la soirée aucun lien de disponible.

**Comment by JaqenGOT** [comment]
Bonsoir,
Alors hier soir beaucoup plus de lien de dispo sur les matchs. Mais le replay de TVrex ne fonctionne toujours pas.

**Comment by razorex** [comment]
Bonjour @JaqenGOT,
-Pour Navixsport je viens encore de regarder on récupère bien les liens dispo sur le site donc si les liens fonctionnent aux moment du direct pour moi c'est donc bon. et pour infi le site ne propose plus de direct pour la NHL.
-Pour Tvrex je n'ai pas encore vraiment regarder

**Comment by JaqenGOT** [comment]
Bonjour @razorex,
Je te remercie pour ton aide. En effet Navixsport a l'air de bien fonctionner. Pour TVrex ça serait bien qu'il fonctionne aussi au cas ou, on l'utiliserait en alternative.

**Comment by JaqenGOT** [comment]
Bonjour @razorex, en tout cas merci pour ton aide. Je me rappel qu'à l'époque ou j'a proposé TVrex c'est si je me rappel bien @kodigoal qui s'en ai occupé. Pourquoi pas lui demander de l'aide.

**Comment by faribole** [comment]
Bonjour
Le site tvrex a changé de seveur et de nom depuis quelques jours, voilà pourquoi cela ne fonctionne plus dans vstream.
Le nouveau site se trouve ici : http://nbareplaytv.com/tvrex-nba-replay-watch-nba-replays/
Comment peut-on demander une mise à jour ou faire la modif soi-même ?

**Comment by razorex** [comment]
Bonjour, je viens de regarder et Tvrex n'a pas changer d'url!!!!!!!!!!!!!!!
@Kodigoal si tu peut jeter un oeil dessus

**Comment by faribole** [comment]
je viens de ressayer et je crois que mon antivirus bloque tvrex à cause d'un trojan

**Comment by faribole** [comment]
Il s'agit de  JS:Miner-C trojan

**Comment by Arias800** [comment]
C'est pas un trojan c'est un miner de crypto money

**Comment by razorex** [comment]
Petit message pour dire que je suis tjrs sur Tvrex j'ai avancé mais je n'ai pas encore terminé.

**Comment by JaqenGOT** [comment]
Bonjour,
Sur la dernière mise à jour vstream j'ai vu le fichier TVrex, j'ai testé hier soir pour voir si ça fonctionner mais toujours aucun lien de disponible. @razorex as-tu avancé sur le fichier? Est ce le tien qui figure sur la dernière mise à jour?

**Comment by razorex** [comment]
@JaqenGOT j'ai repris les replay et normalement çà fonctionnait.

**Comment by JaqenGOT** [comment]
Bonsoir @razorex alors pour TVREX LES replays fonctionnent bien mais pour le live toujours aucun lien de dispo. Aussi depuis la dernière mise à jour vstream, navixsport ne fonctionne plus (erreur: connexion impossible(404)).
Et enfin je viens de trouver un autre site qui diffuse la NBA en streaming, c'est nbastream.net. serait-il possible de créer le fichier pour qu'il soit que vstream?

**Comment by JaqenGOT** [comment]
Bonjour,
Toujours le même problème que cité précédemment, concernant les live pour TVrex et l'erreur de connexion sur Navixsport malgré la mise à jour latéral que j'ai faite hier (30/12/2017). Pourtant les fichiers tvrex et navixsport étant bien présents dans la liste de mise à jour. 
Merci @Razorex, je crois bien que tu es le seul a t'en occupé.
Bonne  saint sylvestre et à l'année prochaine.

**Comment by Arias800** [comment]
Pour l'erreur de connexion sur Navixsport pour le moment impossible a corrigé car le site est down/en maintenance donc normal

**Comment by JaqenGOT** [comment]
merci pour l'info @Arias800.
