### ISSUE TITLE
Message "aucune information"

### ISSUE THREAD

**Issue by sebserra06** [Kodi-vStream/venom-xbmc-addons#1747]
Bonjour à tous,

D'abord merci pour le travail effectué sur cette extension c'est vraiment génial.

Je rencontre un problème qui est certainement de mon fait mais je ne trouve pas ce qui cloche.

J'ai fait l'installation de vstream sur mon pc et tout fonctionne à merveille (c'est pour ça que je la trouve géniale :) ).

Je tente l’installation sur le pc d'un ami en lui vantant ces grâces et là c'est le drame lorsque je vais dans film > qualité HD > planête serie (par exemple) j'ai un message rouge "aucune information". parfois, j'obtiens la liste des films mais sans source et en faisant "précédent"  le même message apparaît.

voici le log : s2csS48toe

Une petite lumière ?

Merci encore

**Comment by mino60** [comment]
Essaye de changer la langue englaise par française dans paramètres Kodi.

**Comment by sebserra06** [comment]
Bonjour,

Merci pour ta réponse, j'ai essayé dans les deux langues et même tabac...
Par ailleurs j'ai également refais une installation sur un autre pc avec un autre fournisseur d'accès (orange pour ne pas le citer) et tout pareil.

**Comment by Arias800** [comment]
Pourquoi a tu fermer l'issue tu a trouve la solution ?

**Comment by sebserra06** [comment]
non pas du tout :)
je sais pas comment j'ai fais ça

**Comment by Arias800** [comment]
Donc quel version de kodi utilise tu ? Sur quel os ?

**Comment by sebserra06** [comment]
Je suis Kodi 17.4 depuis ce matin avec Windows 10

**Comment by Arias800** [comment]
Avant tu avais une ancienne version de kodi 17 ou une version encore plus ancienne (16 ,15 ...) ?

**Comment by Arias800** [comment]
Tu a installer vstream via le repo ?

**Comment by sebserra06** [comment]
j'ai fais plusieurs tests en fait avant j'étais sur une version 16 puis je suis passé en 17 en pensant que ça venait de là et du coup j'ai fait 17.3, 17.4 et sur un autre pc 17.5 qui date de ce matin.

oui j'ai installé via le repo, bien qu'il me proposait aussi l'update à partir de "super repo"

**Comment by Arias800** [comment]
A tu déjà désinstaller et réinstaller vstream ?

**Comment by sebserra06** [comment]
oui plein de fois, j'aime même tout désinstallé et recommencé... mais je peux le refaire si besoin, je suis habitué maintenant :)

**Comment by Arias800** [comment]
Si tu la deja fait ca ne sert a rien

**Comment by Arias800** [comment]
Dans les info de l'addon il met bien que c'est la version 5.5 ?

**Comment by sebserra06** [comment]
oui c'est une version 0.5.5

**Comment by Arias800** [comment]
Essaye dans les option de vstream de desactive la source "french stream" car perso cette source faisait un bug presque similaire au tien chez moi

**Comment by mino60** [comment]
Par foix la réinitialisation porte ses fruits
désinstaller Kodi + vstream complètement 
supprimer Apt DATA Kodi et vstream
installer repovstream + la version bêta.

**Comment by sebserra06** [comment]
@Arias800 j'ai décoché toutes les sources et j'ai seulement laissé planet-streaming (par exemple) mais le problème reste entier.

@mino60 j'ai déjà tout refait à neuf et le résultat est le même. Exception faite sur la version béta, je sais pas où la trouver d'ailleurs

**Comment by Arias800** [comment]
La beta c'est par ici : https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by sebserra06** [comment]
Ok, je désinstalle vstream ou c'est en complément ?

**Comment by Arias800** [comment]
Desinstalle c'est plus sur

**Comment by mino60** [comment]
Sommere : Apropo
![screenshot_20171024-144614](https://user-images.githubusercontent.com/11494048/31946979-31791db6-b8cb-11e7-8ff0-9ee9e92f70d5.png)

**Comment by sebserra06** [comment]
alors, ça a marché, j'ai pu lancé le premier film de planet-streaming, puis quand j'ai stoppé pour revenir au menu j'ai eu de nouveau "aucune information".
Par contre rien ne me dis que je suis en version beta dans les informations, et après désinstallation et installation de la version béta il avait garder en mémoire l'opération précédente (c'est à dire que seul la source planet-streaming était coché dans les sources).

**Comment by Arias800** [comment]
Que ca te dise pas que tu est en beta c'est normal ^^

**Comment by sebserra06** [comment]
ok ^^

**Comment by mino60** [comment]
Paramétre outille vider le cache XBMC et vstream.

**Comment by sebserra06** [comment]
Toujours le même message frustrant.

**Comment by mino60** [comment]
Attend le retour de tmpName si il ne trouve pas une solution a ton probleme alors perssonne ne poura t'aider.

**Comment by TmpName** [comment]
Rien vu de special, peut etre l'espace dans le nom du repertoire, mais depuis la correction unicode ca devrait passer.
Faudrait activer le mode debug de kodi et refaire un test, mais n'en fait pas trop car avec le mode debug active le fichier va etre beacoup plus gros.

**Comment by sebserra06** [comment]
Bonjour @TmpName,
alors j'ai tout refait à neuf, maintenant je suis : 
- Kodi version 17.5
- Vstream 0.5.5
et j'ai toujours même problème.
voici le nouveau fichier log : s20hDJjHa6
je vais activer le mode debug...

**Comment by sebserra06** [comment]
et le log en mode debug : s21EszFTQ9

**Comment by TmpName** [comment]
Ben le truc c'est que dans tes 2 derniers logs il n'y a plus de messages d'erreurs, la franchement si ca ne marche pas, c'est que le site ne te repond pas.
Si l'install est sur PC tu peux te connecter aux site WEB en question sans problemes via navigateur ?

**Comment by sebserra06** [comment]
oui je pense que c'est celui là : http://www.2017.planet-streaming.com/regarder-film/
je vais en essayer un autre j'ai pas forcement de préférence

**Comment by sebserra06** [comment]
bon ça le fait sur toutes les sources

**Comment by sebserra06** [comment]
misère.... je crois que j'ai trouvé.
il s'agissait de l'antivirus.

**Comment by sebserra06** [comment]
je vais faire quelque test mais il semblerait que ça fonctionne....
merci encore à tous pour votre aide

**Comment by Arias800** [comment]
Tu a quel antivirus ? ça pourrait aider d autre personne dans le futur

**Comment by sebserra06** [comment]
Eset Nod 32 version 10, que j'ai désinstallé et réinstallé dans la même version. je pense qu'il avais un souci et c'est Windows Defender qui a pris le dessus et qui bloqué l'accès à certain site.
