### ISSUE TITLE
site uptobox

### ISSUE THREAD

**Issue by madmocas** [Kodi-vStream/venom-xbmc-addons#1749]
Bonjour merci pour votre super addon 
Pour le affichage de Next page sur mon compteuptobox editer le site uptobox a la place de 1000 mettez 25 attention ill a deux endroits à changer
URL_UPTOBOX_SEARCH = (URL_MAIN + '?op=my_files&per_page=25&fld_id=0&key=', 'showMovies')
if 'uptobox.com' in sUrl:
        sHtmlContent = oPremiumHandler.GetHtml(sUrl+'&per_page=25')

**Comment by johngf** [comment]
c'était comme ça avant mais une personne la changer pour avoir qu'une page je ne sais plus pourquoi voir dans les issues fermé

**Comment by madmocas** [comment]
oui mas dans la page avec 1000 avait que 25 fichiers et next page était vide comme ça next page apparait avec le contenu

**Comment by alex83100** [comment]
Bonjour, c'est moi qui avait mis 1000. Si on laisse 25 et je vient de re-tester, je n'ai que 2 pages de 25 puis plus rien. Pourtant j'ai 67 lignes dans mon compte uptobox.

**Comment by madmocas** [comment]
Bonsoir moi avec 1000 j ai que une page de 25 quelqu'un peut me aider

**Comment by madmocas** [comment]
Je suis sur Android et linux

**Comment by madmocas** [comment]
Alex83100  tu est sur Windows ?

**Comment by alex83100** [comment]
oui, mais je peux faire le test sous Android si nécessaire, et dans ton navigateur internet en mettant ?uptob ox .co m/?op=my_files&per_page=1000 cela donne quoi ?

**Comment by madmocas** [comment]
Alex83100 en mettant &per_page=1000 j ai bien mes 2 pages sur le navigateur mais pas sur kodi

**Comment by johngf** [comment]
bon alors je viens de testé sans mettre '&per_page=etc..' avec 53 fichier donc 3 pages!!
et j'ai bien 3 pages

**Comment by madmocas** [comment]
Je vais tester je te dirais quoi

**Comment by madmocas** [comment]
Merci tout est ok en enlevant les 1000

**Comment by johngf** [comment]
@alex83100 tu as testé les nextpage avec l'ancienne methode chez moi et @madmocas ça fonctionne
Les fichiers qui ne s'afficher pas chez toi était peut etre des dossiers ou autres fichiers

Je precise sur mon compte il n'y a pas de dossier seulement les films direct

**Comment by madmocas** [comment]
Moi aussi je ai que des liens direct en enlevant les 1000 tout se affiche

**Comment by sebi0606** [comment]
Bonjour je suis novice pourriez vous enlever les 1000 dans la prochaine mise à jour car moi je ne vois qu'une page merci d'avance

**Comment by johngf** [comment]
ok

**Comment by sebi0606** [comment]
Merci @johngf
