### ISSUE TITLE
TVIP

### ISSUE THREAD

**Issue by johnboisvert** [Kodi-vStream/venom-xbmc-addons#1750]
Suggestion pouvez vous rajouter ces chaine la en tvip sur un projet futur vstream svp ?
beaucoup de chaine quebecoise ca serais génial que ca soit  dans vstream :) 

Merci. 

htt ps://racacaxtv.ga/index.php?category=VG91dGVz&pls=RnJhbmNvcGhvbmVz

**Comment by Arias800** [comment]
Perso je suis contre car racacax a deja une version kodi (bridé) et ce serai imorale de lui voler son travail

**Comment by johnboisvert** [comment]
ouais ta raison jai pas trouver la version kodi :(

**Comment by luluvulcain** [comment]
Salut johnboisvert, pour avoir Racacax TV sur Kodi, tu la sous le nom d'AllfrTV au http://allfrtv.ga/kodi.php

**Comment by johnboisvert** [comment]
hey merci beaucoup c'est gentil :)

**Comment by johnboisvert** [comment]
luluvulcain sais tu ou je peut avoir LiveStreamsPro ? ca prend ca pour kodi et malheureusement via les repos qu'ils donne les installation ne fonctionne pas lol donc rien fonctionne

**Comment by luluvulcain** [comment]
Oui johnboisvert, tu peux telecharger LiveStreamPro au https://androidaba.com/addons/plugin.video.live.streamspro.zip

**Comment by johnboisvert** [comment]
Ohh yeah super si y fonctionne merci beaucoup je test ce soir :)

**Comment by TmpName** [comment]
Tout a ete dit.
Non, on ne rajoutera pas de section iptv, on vient justement de la supprimer, car trop complique a gerer.
Non, on n'utilisera pas celle d'une autre personne qui fait du gros boulot justement pour ca.
Et effectivement Racacax TV est deja dispo sur kodi.
