### ISSUE TITLE
Zone-telechargement 4K

### ISSUE THREAD

**Issue by nabsboss** [Kodi-vStream/venom-xbmc-addons#1751]
Bonjour,

Y'a 2 semaine quand j'allais dans tout les sources -> zones téléchargement.ws -> films 4K  les films en ultra HD présentait un seul lien. Maintenant il y a plusieurs fichiers du type partie 1, partie 2, partie 3,.... qui sont impossibles à lire :(

Une solution ?

Merci !

**Comment by Dinan2000** [comment]
Je pense que ça doit être des fichiers RAR

**Comment by Arias800** [comment]
Yep c est els fichier rar qui en sont pas lisible il ont du faire une modif ou il y a un but dans le code . A tu la dernière version du fichier de zt ?

**Comment by Dinan2000** [comment]
Je ne sais pas si j'ai la dernière version mais j'utilise kodi AVEC vstream 5.5 plus le patch 0.6
Pour moi Kodi est installé sur la Nvidia Shield 2015 
Et justement après l'installation du patch j'ai un problème avec les films quand je clique dessus il me met juste un fichier intitulé premium mais aucune possibilité d'accéder au film et toujours également le problème pour lire mes vidéos avec direct UPTOBOX

**Comment by nabsboss** [comment]
Oui j'ai la dernière version de ZT et j'ai même essayé avec la beta. Effectivement ce sont des rar mais ce qui est bizarre, c'est qu'il y a 2 semaines j'avais un lien et non pas des parties sur la jolie Scarlett johanson par exemple ;)

**Comment by Arias800** [comment]
Effectivement il y a un petit bug je regarde ca ^^

**Comment by Arias800** [comment]
Fix avec cette modif https://github.com/Kodi-vStream/venom-xbmc-addons/pull/1753

**Comment by luluvulcain** [comment]
Arias800 à fait la modif et j'ai actualiser mon Patch que vous pouvez telecharger pour corriger le Bug de Zone Telechargement au https://github.com/luluvulcain/vStream-Kodi

**Comment by nabsboss** [comment]
Je viens de tester et j'ai une erreur "erreur décryptage du lien" avec un popup xbmc qui disparait avec écrit "Site Dl-Protecte HS"
https://slexy.org/view/s20WxCa6hl

**Comment by Arias800** [comment]
Effectivement y a un bug sur certain 4K

**Comment by Dinan2000** [comment]
Bonjour à tous
Merci pour votre réactivité à traiter les problèmes mais je me permets de reparler de mon problème 
Ayant un compte premium Uptobox je suis toujours dans l'impossibilité de lire les films en direct sur UPTOBOX 
Merci d'avance

**Comment by Arias800** [comment]
Si c'est un film 4k c'est normale le code n'est pas finit si c'est un film 1080p c'est deja plus bizarre

**Comment by Dinan2000** [comment]
re-bonjour
Je précise que mon problème avec UPTOBOX concerne tous les formats vidéo et cela depuis 2 mois à peu près 
J'utilise Kodi 17. 5 j'ai essayé avec SPMC même problème 
Et je précise que j'utilise une Nvidia shield de 2015 
Voilà les précisions que je voulais apporter 
Merci d'avance pour vos réponses

**Comment by TmpName** [comment]
Dc strange est aussi reserve aux premium, il faut afficher le lien dans les log et voir si le lien fonctionne dans un navigateur, c'est soit le serveur qui met trop de temps a repondre, soit le lien est foireux donc le serveur ne te repond pas du tout.

@Dinan2000 , il nous faudrait un log.

**Comment by Dinan2000** [comment]
Ok d'accord alors
Qu'entends-tu par log je dois t'avouer que je ne suis pas un professionnel 
Par contre est-ce possible de le voir via la Nvidia Shield si oui comment et je me ferai un plaisir de vous transmettre

**Comment by TmpName** [comment]
Il y a un outil pour les logs dans Vstream https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by Dinan2000** [comment]
Https,://slexy.org/view/s2hlj8waqj
Voilà ce que j'ai pu trouver 
Merci d'avance

**Comment by TmpName** [comment]
Est tu premium ?
Essayes de telecharger le fichier, ou un bout, et de lire sur ton systeme pour voir si il possede les bon codecs.

**Comment by Dinan2000** [comment]
Je possède un NAS 
Quand je télécharge le fichier directement sur le site via le PC et que je le mets sur le NAS aucun problème pour le lire avec Kodi je pense que le problème viens spécifiquement de vstream 
 bonne soirée

**Comment by Dinan2000** [comment]
Désolé j'allais oublier oui je suis premium

**Comment by TmpName** [comment]
Si tu passes par navigateur, tu as le fichier direct, ou une page WEB avec un lien a cliquer ?
Si tu as les bon reglages de ton compte uptobox tu es dans le second cas.

**Comment by Dinan2000** [comment]
re-bonjour
Je viens de refaire le test sur la gâchette via Firefox les liens uptobox fonctionne et je les ouvre avec Kodi tout fonctionne donc le problème vient bien de vstream

**Comment by TmpName** [comment]
Mais quand tu passes par le navigateur, tu as une page web avec un lien a cliquer ou directement le fichier a DL.
Tu peux aussi activer urlresolver (et le regler) et regardr si ca marche dans ce cas la.
