### ISSUE TITLE
Télécharger les gros fichier 

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#1752]
Bonjour....
Télécharger les gros fichier avec le serveur rabb.it
est ce que c'est possible ???... 
je m'explique une fois inscrire sur le site je peux mettre dans un cadre n'inporte lien comme Google uptobox ext... mais avec une vitesse de connexion 1 Go/s si que veux dire télécharger une vidéo de 700 Mo [...] en moins d'une seconde 
avec dropbox est ce que c'est possible avec vstream??.

**Comment by TmpName** [comment]
Ben je pense pas, vu que aucun site ne s'en sert comme hebergeur, et que tres peu de user s'en servent, je ne vois pas qui serait assez motive pour maintenir le fichier python pour cet hebergeur.

Et pour info ca m'etonnerait que tu ais 1 Go/s ^^. En france pas encore vu cette offre pour un particulier.

**Comment by LordVenom** [comment]
Tient pour les téléchargement justement @TmpName  tu seras faire sans les lignes 

try:
    import StorageServer
    Memorise = StorageServer.StorageServer("VstreamDownloader")
except:
    print 'Le download ne marchera pas correctement'

Bref voir un autre system de memorise ça perpétrer de virer plug.cache des extentions obligatoire.

**Comment by mino60** [comment]
Non j'ai une connexion 4 M  mais avec le serveur rabbit.it j'ai télécharger par exemple wifislax 
1.2 Go en 2 seconde et en final je trouve le fichier sur Dropbox j'ai même télécharger un video 4k de 15 Go 
à une minute pres le serveur c'est comme vous avez un autre système virtuelle sur votre PC ce que je veux 
c'est d'ajouter une option pour téléchargement avec rabbit pour plus d'info voilà une vidéo tutorial
https://youtu.be/Q5zgjgC8ywg

**Comment by TmpName** [comment]
Ben StorageServer fait pas partie des plugin installe a la base ?
Le truc c'est qu'il n'y a rien de plus fiable,  xbmcgui.Window(10101).setProperty est un nid a bug, il ya aussi la creation d'un fichier "bidon" a un endroit et verifier son existence, mais le truc de ce pluggin c'est qu'il est resident en memoire, donc pas d'accés disque quand on s'en sert.

**Comment by LordVenom** [comment]
Non Storage server et une fonction de plug.cache utiliser uniquement dans download y a aucune autre importation de cette fonction. Oui windows c'est compliquer si tu quitte la page c'est mort mais tu peux faire un truc avec cConfig().setSetting peux être.

**Comment by TmpName** [comment]
Non mais ce que je veux dire c'est que ca ne fait pas partie des dependances a installer, c'est d'office dans kodi, non ? C'est comme quand tu importes xbmc, c'est une lib proposée dans le "package".

**Comment by LordVenom** [comment]
Je pense pas non, puisqu'il est installer avec vStream sur une nouvelle installation.

**Comment by TmpName** [comment]
Ha ? merde. Ca c'etait pas prevu.
http://kodi.wiki/view/Add-on:Common_plugin_cache

Je vais voir, si je trouve une nouvelle fonction, mais a l'epoque, j'avais presque tout teste.

**Comment by vic1997** [comment]
Je pense qu'il confond Gb (Gigabit) et Go (Gigaoctet), j'ai une connexion 1Gb personnellement, mais Go c'est impossible pour l'instant.

**Comment by johngf** [comment]
c'est un transfert sur dropbox et non un téléchargement

**Comment by mino60** [comment]
Il n'y à pas de différence entre GO et GB, l'un veut dire Giga Octet (en français) et l'autre Giga Byte (en anglais) 
c'est bien un téléchargement le fichier non visible son Dropbox mediafire ou Mga..ext.

**Comment by vic1997** [comment]
@Mino60 tu te trompes toi aussi, j'ai parlé de Gb et non pas de GB, ce qui n'est pas la même chose.
Gb = bit
GB = bute

8 bit = 1 byte = 1 octet

**Comment by mino60** [comment]
@vic1997  j'ai une connexion 1Gb personnellement???
merci pour l'info mais ce que je sache 1Gb disponible on japan

**Comment by vic1997** [comment]
@mino60 Oui au Japon 2Gb/s. En France il y a déjà la fibre et je l'ai, avec 1Gb/s pour l'instant. Pour l'Algérie je n'en sais rien.

**Comment by TmpName** [comment]
@LordVenom, j'ai vu que Covenant tournait juste avec "xbmcgui.Window(10000).setProperty" mais je n'ai pas teste leur module de telechargement.
Cette dependance est vraiment problematique ? Car elle est est vraiment puissante, avec pas mal d'option, pas de ralentissement systeme et surtout pour moi infaillible.
