### ISSUE TITLE
Rubrique "Aide" dans vStream.

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1755]
Je propose une idée à avoir dans vStream.
Est-ce que vous penser que ça serais bien d'avoir une Rubrique "Aide" dans vStream pour savoir comment marche l'addon, réparer sois même l'addon et aussi avoir des infos sur la qualité des fichiers vidéos.
Quand pensez-vous ?

**Comment by Arias800** [comment]
Pour la qualité des video kodi s'en charge plus ou moins après je suis pas contre . A noter qu'il y a aussi le Wiki sur le github qui peux aider dans certain cas

**Comment by luluvulcain** [comment]
Oui Arias800, ben ca serais bien d’intégrer le Wiki dans la Rubrique avec la Liste des différents formats de fichiers vidéos.

**Comment by Arias800** [comment]
Oui pourquoi pas a voir ce que les autre en pense ^^

**Comment by LordVenom** [comment]
Y a pas d'api pour le wiki.
