### ISSUE TITLE
zone de téléchargement 

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#1756]
Bonjour depuis les dernières modifs par rapport à dlprotect des liens se mettent en erreur alors que sur le site ils sont fonctionnels exemple la grande muraille en bluray 1080 sur films populaires merci d'avance

**Comment by Arias800** [comment]
Oui je bosse dessus la le site par totalement en co*****. Je demande d'afficher les film ca me les compte comme des series x)

**Comment by Arias800** [comment]
Test cette version : https://pastebin.com/EjsM4e6h

**Comment by nabsboss** [comment]
Vu que c'est le même problème que mon post avec et 4k, je me permet de répondre ici :)
C'est beaucoup mieux, y'a plus le message et les vidéos se lance par contre sur certains il reste un problème, ex:
En 4k, sur celle du chasseur, uptobox propose la qualité du stream puis j'ai fichier introuvable.
Chez scarlette, uptobox, propose stream ou download puis quand je clic sur stream, j'ai directement fichier introuvable sans proposer la qualité.

**Comment by Arias800** [comment]
Depuis j'ai fait des modif https://pastebin.com/8Vjzwq60 mais j'ai toujours fichier introuvable moi aussi et je sais pas pourquoi (vu que c'est le bon lien qui est trouvé ) ^^

**Comment by TmpName** [comment]
Pour le chasseur le fichier est en Rar (et fractionne) , donc non lisible.

**Comment by Arias800** [comment]
Pour inferno par exemple le lien est bon mais ca me retourne "Failed: HTTP returned error 403" parce que je suis pas premuim peut etre ?

**Comment by TmpName** [comment]
Yep , testes en direct htt p://uptobox.com/r2ipgdm3dby8

**Comment by nabsboss** [comment]
Le download se passe bien depuis un navigateur en premium.
Ah non pitié je me suis équipé en full 4k :( Je sais que ce n'est le lieu mais si ça déconne avec zt, y aurait moyen d'avoir un site alternatif comme extreme-download qui propose plus de fichier 4K pour remplacer ZT ?

**Comment by nabsboss** [comment]
Il semblerait que le lien n'est pas récupérer correctement contrairement à d'autres qui fonctionne:
https://slexy.org/view/s2162YDTfD

**Comment by Arias800** [comment]
Malheureusement j ai plus internet donc je peux pas m en occupe pour le moment

**Comment by nabsboss** [comment]
OK pas de problème Arias800, merci en tous cas de ton aide ;)

**Comment by Allonsbon2004** [comment]
Hello,
La section 3d de zt pose également problème sur le dl protect.

**Comment by Arias800** [comment]
Essaye le film la momie en 3d chez moi ca marche

**Comment by TmpName** [comment]
@nabsboss , exact ton lien est encore un fichier rar, donc pas lisible sur kodi.
Il y a des fonctions CutNonPremiumlinks() et CutPremiumlinks() qui servent a virer les liens rar, c'est elles qui doivent deconner.

**Comment by Allonsbon2004** [comment]
Test de la momie 3d via uptobox. Ne se lance pas chez moi.
Spider Man, transformer, planète des singes. Erreur dl protect.
Vstream 5.6.

**Comment by Allonsbon2004** [comment]
Test de la momie 3d via uptobox. Ne se lance pas chez moi.
Spider Man, transformer, planète des singes. Erreur dl protect.
Vstream 5.6.

**Comment by Allonsbon2004** [comment]
Et sinon y a un quota en temps ou en data sur uptobox. J ai eu plusieurs blocage sur des films qui durent plus de 2h. La coupure arrive au bout des 2h image figée.

**Comment by TmpName** [comment]
Retestes avec la derniere version en ligne stp, spiderman ok chez moi.
Et yep, y a un quota, 2 h sans inscription, 3 enregistre en gratuit (de memoire)

**Comment by luluvulcain** [comment]
Bonjour Allonsbon2004, essaye ce que ta dit TmpName ou sinon télécharges mon Patch au https://github.com/luluvulcain/vStream-Kodi

**Comment by nabsboss** [comment]
@TmpName aahh OK ! Merci pour l'info ;)

**Comment by Allonsbon2004** [comment]
Effectivement, c'est Ok avec le dernier fichier ZT. Merci beaucoup pour votre engagement et votre de taf

**Comment by Arias800** [comment]
Normalement plus de fichier rar sur les film 4K avec cette version https://pastebin.com/8Vjzwq60
Quelqu'un peu confirmé ?

**Comment by sebi0606** [comment]
Oui c'est bon nickel pour moi merci beaucoup

**Comment by Akekekiukou** [comment]
Les séries ne marchent plus. Aucun lien visible

**Comment by Arias800** [comment]
D acc je m occupe de zt en fin de semaine

**Comment by Arias800** [comment]
@Akekekiukou un exemple parce que chez moi j'en ai essayer et elle fonctionne

**Comment by Akekekiukou** [comment]
@Arias800 les films marchent mais pas les séries. J'ai essayé de très nombreuses séries et les liens n'apparaissent pas contrairement aux films

**Comment by Arias800** [comment]
Justement j'ai teste plusieurs séries et chacune  marche

**Comment by Akekekiukou** [comment]
@Arias800 bizarre. J'utilise kodi sur mi box tv. Le problème vient peut être de la box😞

**Comment by Arias800** [comment]
Essaye rivertale la saison 2 en vostfr le 1er episode voir si il marche

**Comment by Akekekiukou** [comment]
@arias800

Ca ne marche pas chez moi

**Comment by Arias800** [comment]
Donc le probleme vient de chez toi il faudrai les log ^^

**Comment by Akekekiukou** [comment]
Y a personne d'autre qui a une mi box TV 4k pour vérifier ?

**Comment by Akekekiukou** [comment]
Ça recommence et je ne comprends pas où est le problème.
Ça passe très bien pour les films mais aucun lien pour les series

Quelqu'un a le même problême ?

**Comment by Arias800** [comment]
Je peux pas tester avant la fin de la semaine donc je peux pas te dire
