### ISSUE TITLE
Suggestion : cacher hébergeur non utiliser 

### ISSUE THREAD

**Issue by billouetaudrey** [Kodi-vStream/venom-xbmc-addons#1757]
Bonjour,

Est il possible d'ajouter la possibilité de cacher les héberger / cloud non utilisé ? 

Ça pourrait éviter de chercher après un épisode dans une saison de 24 épisodes... Ça peut vite aller à +100 liens...

Merci :)

**Comment by TmpName** [comment]
Ben ca demanderait de cocher tout les hebergeurs non utlisés dans un menu de config. Et ca risque de provoquer des pages vierges si justement le seul lien dispo est dans les hebergeurs bloqués.

**Comment by nabsboss** [comment]
Oui mais avant on pouvait sélectionner des hébergeur pour les films et d'autres pour les séries. Maintenant je scanne tous les hébergeurs alors qu'il n'y a que 4 qui m'intéresse pour les films et pour les séries je prends tous  mais comme je fais pas de distinctions je dois laisser tous activé. Pourquoi vous avez enlevé cette fonctionnalité de favoris du coup ?

**Comment by johngf** [comment]
Vous mélangez hébergeur de fichier et site internet ou vstream cherche du contenu pour nous hébergeur c'est le lien final en bleu ciel >> hébergeur de la video

**Comment by LordVenom** [comment]
> Pourquoi vous avez enlevé cette fonctionnalité de favoris du coup ?

Quoi ?

**Comment by TmpName** [comment]
Heu ^^, bon c'est pas la premiere fois que je rate un truc, mais j'ai jamais vu cette fonctionnalitée avant.

**Comment by nabsboss** [comment]
OK je me suis mal exprimé et du coup je suis hors sujet par rapport à celui du topic je pense. Je voulais seulement dire qu'auparavant dans les paramètres, on pouvait sélectionner les sites pour la recherche de films et de même pour les séries et cette fonctionnalité a disparue.

**Comment by billouetaudrey** [comment]
Et on peut pas ajouter un petit

If résulter nulle, alors afficher tous les hébergeur ? 

Par hébergeur, j'entends 1fichier uptobox etc...

**Comment by TmpName** [comment]
Ha bon ?
L'option est plus la ?
@LordVenom, ca marche plus ?

**Comment by LordVenom** [comment]
Non ça existe plus. Trop incompris comme fonctionnaliter.

Mais j'ai poster un message avant de toucher, pâs eu de retour.

**Comment by billouetaudrey** [comment]
Suffirait juste de recocher d'autres hébergeur non ?
Car il me semble, que beaucoup d'hébergeur sont payant non ? (dont uplea, uploaded etc...) donc si le lien est mort sur 1fichier premium ou uptobox, quel intérêt d'avoir les autres ?

**Comment by LordVenom** [comment]
@billouetaudrey Ont parle pas de la même chose. 
Le system de Hosts (youwatch upto ect..) est bloquer en code aucune sélection n'est possible. Pour avoir un system de choix (activer ou pas) il faudrait tout recoder.

**Comment by billouetaudrey** [comment]
En effet alors, je parlais d'hébergeur du fichiers et non du lien :)

**Comment by LordVenom** [comment]
Les sites proposant des hébergeur type download ou payant sont de couleur violet normalement.

**Comment by billouetaudrey** [comment]
C'est justement les sites que j'utilise, c'est pas grave hein, c'était juste une proposition qui me paraissait évidente à mettre en place :)
