### ISSUE TITLE
problème recherche

### ISSUE THREAD

**Issue by mmtest1** [Kodi-vStream/venom-xbmc-addons#1758]
Bonjour, 
je rencontre un soucis avec l'extension : lorsque j'effectue une recherche de série tout fonctionne, mais lorsque je lance une recherche de film le scanne des sites fonctionne mais lors de l importation des résultats kodi crash puis reboot
j'utilise vstream 0.5.5 + kodi 17.4 + osmc + confluence sur raspberry b+
De plus la recherche visuelle est chez moi hs (les deux problèmes sont-ils liés ?)
Le problème peut-il venir d'un site hs dans la catégorie film non présent dans la recherche série ?
Ça fonctionne chez vous ?
J'ai réinstallé l'extension et osmc sans amélioration, le crash se reproduit
Je vous remercie pour votre soutien

**Comment by luluvulcain** [comment]
Bonjour mmtest1,
Pour régler ton soucis, installe la mise a jour de Kodi en 17.5 et ré-installe vStream depuis son repo ou aussi installe mon patch au https://github.com/luluvulcain/vStream-Kodi

**Comment by mmtest1** [comment]
merci pour la réponse, je vais attendre la mise a jour d'osmc certainement avec kodi 17.5 et debian 9 en début de mois prochain mais ce que je ne comprends pas c'est que cela fonctionné sans soucis avec kodi 17.4 et vstream 0.5.5 et que cela fonctionne pour les séries mais crash maintenant pour les films, ce qui m'interroge sur les causes du crash

**Comment by Arias800** [comment]
Peut tu passer les log ?

**Comment by mmtest1** [comment]
Je viens de retester la recherche de film : 
- une recherche avec capitaine fantastic fonctionne parfaitement avec un nombre de résultat limité
- une recherche avec le monde de narnia crash à l'importation des résultats, le nombre de résultats étant superieurs (130)
Les logs présentent un grand nombre d'erreurs en rapport avec SQL
[kodi.old.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1424091/kodi.old.log)
Merci pour votre patiente

**Comment by Arias800** [comment]
@TmpName je pense que c'est lié a ca "The database disk image is malformed" une idée ?

**Comment by TmpName** [comment]
Pas bete, essayes de supprimer les databases, elle seront recréés.
Tu peux faire ca a partir des parametres de Vstream.

**Comment by mmtest1** [comment]
Bonjour,
J'ai déjà essayer de supprimer le cache de vstream et Kodi sans succès, par contre la suppression des thumbnails renvoie une erreur d'extension

**Comment by mmtest1** [comment]
Y a t il un moyen de supprimer manuellement les bases de données corrompues ?

**Comment by LordVenom** [comment]
C:\Users\"NOM"\AppData\Roaming\Kodi\userdata\Database

**Comment by mmtest1** [comment]
J'ai supprimé le dossier /home/osmc/.Kodi/userdata/Database et je me retrouve avec un système creux plus rien ne fonctionne, la coquille est la mais plus extension utilisable, je vais réinstaller les dépôts et les extensions, je vous tiens au courant de la suite

**Comment by mmtest1** [comment]
Les dépôts ont disparut et toutes les extensions sont désactivées, j’essaie de les réactiver manuellement mais j'ai peur que certains services ne soit pas activés et que le système soit instable

**Comment by mmtest1** [comment]
après avoir réactivé les extensions une à une ainsi que les services disponibles la recherche de film fonctionne à nouveau et le nettoyage des thumbnails fonctionne également, le problème venait bien d'une corruption de la base de donnée,
je vous remercie, problème resolu

**Comment by mmtest1** [comment]
Juste un petit bémol la recherche visuelle est hs si vous aviez une idée des erreurs du log ?
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/1424295/kodi.log)
