### ISSUE TITLE
Recherche visuelle et vue par défaut

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1759]
Hello,

Depuis la version 5.4 ou 5.5 : la vue par défaut ne fonctionne plus pour la recherche visuelle.

Pas de problème avec les autres recherches mais avec la recherche visuelle c'est la vue  par icones qui est sélectionnée par défaut et c'est pas très pratique.

Dans les logs je trouve cette erreur qui a certainement un rapport avec mon soucis : 
ERROR: Control 53 in window 10025 has been asked to focus, but it can't

Merci d'avance pour votre aide et bon we.

**Comment by Arias800** [comment]
C est normale dans ma recherche visuels PN force la vue avec les icône

**Comment by TmpName** [comment]
C'est ca, la recherche visuelle est une recherche par affiche, donc avec affichage par icones.

**Comment by LordVenom** [comment]
Deja débattu de ce sujet la majorité à parlé le mode forcer icone resteras.

**Comment by canopre** [comment]
Ben c'était mieux avant...
Et je vois pas l'intéret de pouvoir régler la vue dans la config et que finalement ce réglage n'est plus pris en compte...

**Comment by LordVenom** [comment]
Effectivement y a un réglage dans les paramètres je penserais le virer xD

**Comment by canopre** [comment]
Ca serait beaucoup mieux qu'il soit actif...
Tu avais ajouté ce réglage suite à une de mes demandes et je ne comprends pas pourquoi tu veux le supprimer.
Que ça soit "icones" par défaut : Pas de problème.
Et si on préfère une autre configuration : On utilise ce réglage.
Pour info : En vue "53" : Je peux afficher les métadonnées en même temps que l'affiche.
En vue "Icones" : Les métas ne sont plus visibles.

**Comment by TmpName** [comment]
Le reglage des vues concerne l'affichage classique de Vstream, pas la recherche VISUELLE qui est un outil a part.
C'est comme un reglage de la couleur dans des sections de films ayant une categorie couleur et une autre en noir et blanc.
Pour ceux qui ne veulent pas les poster > recherche classique.

**Comment by LordVenom** [comment]
Ben en faite ça fonctionne. mais les vues ne sont pas le même depuis estuary ou d'autre skin a toi de savoir quelle vue ce trouve a quel ID.

Estuary fichier MyVideoNav.xml : 

```
			<include>View_50_List</include>
			<include>View_51_Poster</include>
			<include>View_52_IconWall</include>
			<include>View_53_Shift</include>
			<include>View_54_InfoWall</include>
			<include>View_55_WideList</include>
			<include>View_500_Wall</include>
			<include>View_501_Banner</include>
			<include>View_502_FanArt</include>
			<include>View_50_List</include>
			<include>View_51_Poster</include>
			<include>View_52_IconWall</include>
			<include>View_53_Shift</include>
			<include>View_54_InfoWall</include>
			<include>View_55_WideList</include>
			<include>View_500_Wall</include>
			<include>View_501_Banner</include>
			<include>View_502_FanArt</include>
```
