### ISSUE TITLE
Désactiver les fanart dans la configuration

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1760]
Hello

Pour les utilisateurs de Raspberry, ca serait bien pratique de pouvoir désactiver les fanarts.

Ils ralentissent le bouzin et n'apportent pas grand chose.

Merci d'avance.

**Comment by TmpName** [comment]
L'option est deja presente "Recherche les metas données".

**Comment by canopre** [comment]
Oui mais c'est bien les métadonnées ! C'est juste les fanarts qui ne sont pas forcéments utiles.

**Comment by LordVenom** [comment]
Les passer en w300 ça aide pas ta machine un peux ?

**Comment by canopre** [comment]
Si si bien sûr mais avec la vue "53" : Les métadonnées sont affichées et on ne voit presque plus le fanart en arrière plan... alors autant ne pas les charger pour rien.
