### ISSUE TITLE
Chargement des catégories mais rien ne se passe...

### ISSUE THREAD

**Issue by nabsboss** [Kodi-vStream/venom-xbmc-addons#1763]
Bonjour LordVenom,

Pourquoi tu as clôturé le #1721 si ça ne marche toujours pas !?

**Comment by LordVenom** [comment]
Mais encore... , J'ai fermer le post car le dernier soucis themoviedb et résolut.

**Comment by mmtest1** [comment]
Bonsoir
J'espère  ne pas polluer la discussion mais j'avais un problème de database sql corrompue  et le problème est réglé mais j'ai un second soucis sur la recherche visuelle qui est hs, le log de kodi concerne des erreurs themoviedb
Voir le dernier log contenu dans le dernier post #1758 (désolé pas trouvais comment reouvrir l issue)
La mise à jour de themoviedb qui resout le probleme est déjà effective?

**Comment by nabsboss** [comment]
Oui et de mon côté c'est pas résolu non plus mais LordVenom dis que si malgré les logs du coup je ne sais pas quoi si ce n'est qu'on est 2 maintenant :( Pour info LordVenom, mon log étais aprés la maj qui étais censé corriger themoviedb et j'ai encore des erreurs dessus.

**Comment by mmtest1** [comment]
Bonjour,
Problème résolu de mon côté, la mise a jour de themoviedb n'avait pas suffit à régler mon problème de recherche visuelle hs mais ce matin mise à jour de tvdb qui résout le problème 
Merci a toute l'équipe et bon dimanche

**Comment by TmpName** [comment]
Tmdb est justement la recherche visuelle ^^.

**Comment by LordVenom** [comment]
Vous avez vue je prédit l'avenir !

**Comment by TmpName** [comment]
Et sinon, niveau sante, amour, travail, tu annonces qui ?

**Comment by nabsboss** [comment]
Cool merci LordVenom ;)
