### ISSUE TITLE
Probleme Zone Telechargement 

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1764]
Bonjour, les liens des séries VF en mode recherches ne marche pas sur zone telechargement.
Pourriez vous corrigez ce problème s'il vous plait ?

Cordialement,
Luluvulcain

**Comment by Arias800** [comment]
Essaye cette version du fichier https://pastebin.com/8Vjzwq60

**Comment by luluvulcain** [comment]
Merci Arias800, cette version du Fichier marche.

**Comment by psykotropz** [comment]
hello
Est ce que la maj corrige ce probleme? je n'ai toujours pas compris comment faire les modifs manuellement sur un Raspberry

**Comment by Arias800** [comment]
J ai pas encore m'y la modifi car je voulait finir la section 4k mais après peut que @luluvulcain la mit dans son patch
