### ISSUE TITLE
Problème lenteur VStream sur RPI depuis la mise à jour

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#1766]
Hello
Depuis la dernière mise à jour : je trouve Vstream beaucoup + lent sur mon RPI3 : ca mets une plombe à afficher les affiches et les fanarts.

Suis-je le seul à avoir remarqué le problème ?

Je joins mes logs à toute fin utile.
https://pastebin.com/Hu6nmTuN

**Comment by TmpName** [comment]
Pour en revenir a ta precedente issue, si tu as des problemes de ralentissement, desactive les metas, il n'y a pas que les fanart qui ralentissent.

> 22:32:39 12213.249023 T:1464226800  NOTICE: Metadata and Artwork module --> Rate limiter active for omdbapi.com - delaying request with 2 seconds - Configure a personal API key in the settings to get rid of this message and the delay.

Tu peux accelerer en utilisant ta propore cle API.

Mais tu as aussi de gros problemes pour acceder aux images.

> 21:17:02 7676.408203 T:1650979824  NOTICE: LoadJpeg: unable to load https://image.tmdb.org/t/p/w396/7GDj0mi7vtRfYXJkGJzQV7MOrin.jpg
> 21:17:03 7677.002930 T:1455838192 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder

**Comment by LordVenom** [comment]
Je suis dubitatif...

w = witdh = largeur de l'image.

Le fanart son en w780 le mini c'est w300 et @TmpName  soulève un truc marrant  NOTICE: Metadata and Artwork module --> Rate limiter active for omdbapi.com (omdbapi) ? what the fuck ? tu aurais pas un addon qui chope les extra fanart, icone et autre joyeuseté inutile.

Je suppose que c'est script.module.metadatautils mais pourquoi il cherche c'est une autre question.

**Comment by LordVenom** [comment]
Si moi j'active les metadatas et que je lance les films populaire de la recherche visuelle voici mon bout de log 

https://pastebin.com/x0RZQ49x

**Comment by LordVenom** [comment]
La recherche visuelle n'etait pas impacter par le cache, ça seras réparer dans la prochaine mise a jour auto.

**Comment by canopre** [comment]
Hello.
J'ai pas tout compris :) mais j'espère t'avoir aidé un peu quand même...
Merci d'avance pour la prochaine mise à jour.

**Comment by LordVenom** [comment]
Le soucis que j'ai relever ne vas améliorer que la recherche visuelle.

**Comment by canopre** [comment]
Hello
Petit problème : la recherche visuelle est encore plus lente car elle affiche maintenant  la barre de progression.
Alors quand on utilise la recherche visuelle pour faire des menus et des widgets : tout est bloqué pendant le chargement.
Désolé mais c'était beaucoup mieux avant...

**Comment by canopre** [comment]
Salut.
De mon côté c'est beaucoup mieux maintenant et il n'y a plus les lenteurs pour afficher les affiches.
Merci à vous.

**Comment by LordVenom** [comment]
C'est un des soucis du nouveau Kodi est de son nouveau système de cache, j'ai cette gène aussi mais j'ai pas de solution dsl.

**Comment by canopre** [comment]
Salut et merci pour ta réponse.
Quand tu dis "nouveau Kodi" : C'est à partir de quelle version ?
Car j'utilise toujours une "vieille" 16.1 et je rencontre pourtant le problème.

**Comment by LordVenom** [comment]
Ha... même réponse, pas de solution.
