### ISSUE TITLE
vStream en source ?

### ISSUE THREAD

**Issue by vic1997** [Kodi-vStream/venom-xbmc-addons#1767]
Bonjour tout le monde !

Je viens vous poser une petite question, j'ai un problème mais qui n'est pas directement lié à vStream, je viens ici parce qu'on a pas une grosse communauté et ça fait 3 jours que je cherche et j'ai RIEN trouvé sur internet, je commence à désespérer. Donc je vous explique : 

J'ai pris un abonnement premium à UpToBox, mon idée était d'héberger mes films chez eux et de lire tous mes films avec kodi à distance pour économiser de la place sur mes disques dur. Le problème c'est que UpToBox n'a aucun moyen permettant d'accéder à ses propre fichier (FTP et tout ça), le seul moyen est de passer par l'interface web mais kodi ne propose pas ça.
J'ai donc ensuite vu que vStream proposait de se connecter à son compte UpToBox pour voir ses fichiers ! Yes !! (punaise il fait vraiment tout cet addon :D ) Donc tout marche j'ai réussi ! Le truc, c'est que je suis obligé d'aller dans vStream ==> Toutes les sources ==> Compte UpToBox pour y accéder, alors ça ne serait pas le problème si c'était juste le fait de devoir faire ça mais en plus de ça, ces films là, ne peuvent être scanné pour être ajouté à la médiathèque (en passant par l'onglet film), je n'ai donc aucune infos sur ces films, ni image et autres. J'aimerais donc savoir comment rajouté ces films en tant que source sur kodi pour que je puisse les avoir dans l'onglet Films et que le scrapper puisse télécharger les infos sur ces films.

J'ai vu que cette question avait déjà été posé, mais sans réponse : [https://github.com/Kodi-vStream/venom-xbmc-addons/issues/777#issuecomment-270359579](https://github.com/Kodi-vStream/venom-xbmc-addons/issues/777#issuecomment-270359579)

Merci à vous d'avoir pris le temps de lire (et désolé, ça n'a pas trop de lien avec vStream mais vous êtes ma dernière chance), j'attends vos réponses ! :D

**Comment by Arias800** [comment]
Il y a l add-on AddToLib qui permet d ajouter un lien d un film ou série dans la médiathèque de kodi

**Comment by vic1997** [comment]
@Arias800 Ho punaise oui c'est ça !!! Super !! D'ailleurs j'ai en même temps trouvé qu'on pouvait ajouté à la librarie de vStream (j'vais jamais compris à quoi ça servait). Tout marche impeccable !
J'ai juste encore une question, que ça soit avec AddToLib ou directement avec vStream, comment on fait pour ajouter un dossier complet de film ? Au lieu d'ajouter un par un (sachant que si j'en ai des centaines ça risque de prendre du temps :D )

Merci d'avance et merci beaucoup @Arias800 , tu me sors d'une sacré me*de !

**Comment by Arias800** [comment]
Je sais pas du tout pour le coup x)

**Comment by vic1997** [comment]
@LordVenom Je sais pas si tu as lu toutes mes explications, mais j'ai précisé à la fin que j'ai trouvé ça. Cependant avec UpToBox en passant par "Votre compte Uptobox" ça ne marche pas, essaie tu verras.
**J'ai fais une vidéo pour vous montrer le problème** : [https://youtu.be/N1I3z9Wg640](https://youtu.be/N1I3z9Wg640)

Et sinon, ça serait bien d'ajouté la possibilité d'ajouter un dossier complet (remplit de film), pour éviter de les ajoutés un à un, avec mise à jour du dossier ça serait le top.

@LordVenom Je t'ai dis ça pour UpToBox car j'ai regardé beaucoup d'issues d'ici où tu répondais à des problèmes similaire avec uptobox, tu as dis que tu avais un compte premium, je pensais que tu pourrais m'aider.

**Comment by LordVenom** [comment]
Pour avoir les infos, Il ne faut pas oublier d'ajouter le dossiers films / séries en contenue de la librairie.

![image](https://user-images.githubusercontent.com/4380112/32255328-5863af5e-bea7-11e7-8cab-115b06f9d2c4.png)

Pour ton bug de lecture oui c'est un bug.
Par contre je n'est pas de compte premium upto ou autre.

**Comment by alex83100** [comment]
Bonjour, il existe un addon : OSMOSIS qui permet de générer les strm d'un dossier complet d'uptobox et en utilisant comme interface Vstream. Par contre test avec les premières version de l'addon, les dernières versions ne fonctionnent pas correctement pour cet utilisation.

**Comment by vic1997** [comment]
@LordVenom Merci de ton aide, j'ai essayé ce que tu as dit, mais je n'ai pas plus de résultat.
@alex83100 Merci à toi !!! Cet addon est exactement ce qu'il me fallait ! Je ne l'avais absolument pas trouvé en cherchant sur internet, merci !!

Je clos le problème alors ! La solution est donc d'utiliser l'addon OSMOSIS (met les films dans la mediatheque) avec l'addon CloudStream (récupère les films d'UpToBox), je n'ai pas utilisé vStream finalement vu que pour l'instant le système avec le compte uptobox est bugué.

Encore merci tout le monde !
