### ISSUE TITLE
Problème uptostream

### ISSUE THREAD

**Issue by alex83100** [Kodi-vStream/venom-xbmc-addons#1770]
Bonjour,

J'ai un problème avec uptostream, alors que pour le même film les liens uptobox fonctionnent . Je précise que le problème se pose aussi sur des liens que j'avais dans ma bibliothèque et qui fonctionnaient avant la dernière mise à jour.  **Vstream ne me demande plus la qualité 320p, 720p** lorsque je choisis uptostream comme il le faisait avant et kodi me retourne un message d'erreur.

Un exemple de série que j'avais dans ma bibliothèque Vstream et qui fonctionnait 
 
Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=Grey's Anatomy - Saison 2 Episode 1&sMediaUrl=http%3A//uptobox.com/dmt5gzy8qjph&sHosterIdentifier=uptobox]

http://uptostream.com/dmt5gzy8qjph me donne bien un lien valide sous IE

**Comment by vic1997** [comment]
@alex83100 Salut, si je ne dis pas de connerie c'est le bug que j'ai eu (je n'avais jamais essayé avant donc je ne savais pas que ça buguait que depuis peu). J'en ai parlé dans mon issues : [https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1767#issuecomment-341092453](https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1767#issuecomment-341092453)

**Comment by dali004** [comment]
@alex83100 exactement le même problème chez moi ! :(

**Comment by Arias800** [comment]
Moi aussi sur les source normal je crois qu'il ont fait une modif hier

**Comment by TmpName** [comment]
Yep, y a une modif sur le site, faut juste modifier le regex.
Une version qui marche https://pastebin.com/ruPE0Zzk

Mais pas teste sur des films proposant plusieurs qualitées, donc a finir.

**Comment by Arias800** [comment]
J'ai une version que je vient de testé et qui fonctionne faut juste que je fix uptobox

**Comment by Arias800** [comment]
Bon bah je trouve pas le probleme d'uptobox ^^

**Comment by alex83100** [comment]
Bonjour, merci je viens de tester les "pull requests" cela fonctionne pour moi.

**Comment by Arias800** [comment]
Oui c'est vrai j'ai pas precisé mais normalement j'ai fix ca
