### ISSUE TITLE
serie sur zt

### ISSUE THREAD

**Issue by yas06** [Kodi-vStream/venom-xbmc-addons#1772]
bonjour a tous je n ai plus de lien dans la section série sur zone téléchargement
alors que c est ok dans la section film
merci d avance de vos reponse

**Comment by KiliK150** [comment]
Oui ça fait un petit moment qu'il y a ce problème. Les liens s'affichent qu'en passant par le marque page ( il faut encore que la série soit dedans 😄😅 )

**Comment by Arias800** [comment]
Cette version fonctionne normalement https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by yas06** [comment]
Slt kilik le souci c que j ai effacer le cache xbmc et la plus de marque pages😱
Merci ariase je vais tester ça jte remercie 👍👍👍

**Comment by yas06** [comment]
Merci j ai mis la version bêta ça marche 😸😸😸👍👍
