### ISSUE TITLE
erreur 404

### ISSUE THREAD

**Issue by michellemikor84** [Kodi-vStream/venom-xbmc-addons#1778]
Bonjour à tous et à toutes,
Depuis deux jours j'ai l'erreur 404 et plus aucun accès à quoi que ce soit.
Apparemment personne d'autre ne s'en est plaint ?
Je reste donc en attente d'une mise à jour.
Encore un grand merci à toute l'équipe qui nous fait ce merveilleux programme.

**Comment by hourra** [comment]
Je confirme , même problème.
Fichier introuvable pour presque tous les sites. Cependant qques films sont accessibles selon l'adresse du lien (très très peu). Méme Kepliz ne donne rien, il y a un problème avec le "RESOLVE" google video.

**Comment by toadnam** [comment]
Idem pour moi , malgré le dernier patch de vulcain, fichier introuvable pendant la lecture d'un épisode d'une serie ! Ça s'est coupé, j'ai voulu relancer et fichier introuvable...sur zt 
 kaydo c'est la même...
Que ce soit sur pc ou sur Android tv c'est pareil...
Ça ne marche pas non plus. Bizarre bizarre.
Merci quand même pour le taf de toute lequipe

**Comment by TmpName** [comment]
Effectivement probleme pr les liens google.

**Comment by TmpName** [comment]
Bon J'ai corrige Kepliz et le hoster googlevideo, mais j'ai teste juste sur un film.

**Comment by hourra** [comment]
Merci TmpName. j'ai téléchargé la béta et kepliz fonctionne.
Ainsi que zone télechargement .
