### ISSUE TITLE
Ajouter site streaming sur covenant

### ISSUE THREAD

**Issue by bubuleur** [Kodi-vStream/venom-xbmc-addons#1779]
Bonjour,
Déjà merci beaucoup pour cette extension, vraiment c'est du super boulot que vous faite merci encore
Juste une petite question voila j'ai remarqué qui il y a très peux d'extension comme vstream pour kodi 
à par covenant j'ai aider à traduit cette extension en français mais malheureusement c'est très pauvre en films français je sais que je suis pas au bonne endroit pour ça mais serait-il possible d'ajouter des sites de streaming français sur covenant je ne sais pas faire 
Je dis ça parce que si un jour vstream vient a disparaitre il y aura une alternative 
Enfin je ne souhaite pas que vstream s'arrête un jour
En vous remerciant
Covenant trouvable ici: https ://github.com/Colossal1

**Comment by Arias800** [comment]
Vstream ne disparaitra pas car c'est de l'open source donc le code tout le monde y a acces ^^

**Comment by TmpName** [comment]
XD, ben franchement Vstream est beacoup plus vieux que covenant, il etait la meme avant exodus, donc perso je te propose plutot d'ajouter les site de convenant sur Vstream pour la prochaine fois ou l'addon va disparaitre ^^.

**Comment by bubuleur** [comment]
j'aurai essayer comme meme
