### ISSUE TITLE
Libretv

### ISSUE THREAD

**Issue by Ricky834** [Kodi-vStream/venom-xbmc-addons#178]
Merci pour votre développement, ca fonctionne bien et ca va probablement apporter de nouveau contributeur.

Partager et géré vos listes facilement via pastbin 
http://libretv.me/chaine/

Groupe
http://bit.ly/LiBrE-Tv

**Comment by TmpName** [comment]
Ben j'espere bien, le concept de libreTV est sympa.

Pour le moment on bosse encore sur l'integration car via m3u c'est moins ergonomique que de passer par l'ipTV "simple client", mais dans tout les cas vous avez un superbe projet.

Mon seul regret c'est que le coté "communautaire" n'apparait pas trop pour l'user lambda qui regarde juste les chaines sans voir la difference avec les listes standards.

**Comment by Ricky834** [comment]
Tu aimerais un genre de tag (COM) pour les liste qui sont gérer par la communauté et non des liste ajouter sur pastbin ?

**Comment by TmpName** [comment]
Nope ^^. Rien a voir avec la gestion, je suppose que vous avez assez de retour pour gerer ca.

C'est juste que le concept de liste communautaire ou n'importe qui peut participer en quelques clics ne frappe pas au regard de la personne qui se sert de la liste. En fait une personne qui n'a jamais fait un tour sur votre site ne sais meme pas ce qu'elle a entre les mains.

**Comment by Ricky834** [comment]
Ok je comprend ton point de vue , manque un peut d'information sur le système de communauté a l’intérieur même de la source , Qui partage cette liste , qui est le dernier utilisateur a avoir contrôler cette liste , ce genre de chose ?

**Comment by TmpName** [comment]
Pour info ils viennent de mettre en place une option pour pouvoir rajouter 1 lien unique.
J'ai pas encore pu tester mais en 4 clics vous pouvez rajouter vos liens, surement dans une liste speciale.

**Comment by andykimpe** [comment]
et bien par exemple

Sakura, chasseuse de cartes vf (seulement en vostfr sous vstream)

http://www.planet-series.tv/sakura-chasseuse-de-cartes/

le tour du monde en 80 jours (il y a bien des version différente mais pas la même)

http://www.planet-series.tv/le-tour-du-monde-en-80-jours/

ont peut trouver des épisode de série comme plus belle la vie, ou encore Joséphine ange gardien, etc qui n'ont pas encore étais diffuser en France

les épisode sont enregistrer sur les belge (rtbf) ou suise (rts)

qui sont en avance sur la diffusion par rapport a la France

autre avantage les upload sont ouvert a tous et chaque utilisateur est informer lorsque un lien est mort ce qui permet de réup
