### ISSUE TITLE
Pairing -> No daily changes

### ISSUE THREAD

**Issue by flashxtv** [Kodi-vStream/venom-xbmc-addons#1780]
Hey,

if you want you could implement our new pairing method, like jsergio123:
https://github.com/jsergio123/script.module.urlresolver/blob/master/lib/urlresolver/plugins/flashx.py

This will save you a lot of work and time.
If you have any questions write to flashx@protonmail.com or info@flashx.tv or with UNSEEN.is: "flashx".

Regards

flashX

**Comment by TmpName** [comment]
Need to check how the pairing work, but If I need to go on a website everyday to active it, it s totaly useless, I remember you, kodi haven't a WEB scrapper.
