### ISSUE TITLE
ajout 1fichier

### ISSUE THREAD

**Issue by madmocas** [Kodi-vStream/venom-xbmc-addons#1781]
Bonjour merci encore pour votre travaille j aimerai savoir si quelqu'un peux ajouter 1fichier site pour voir nos fichiers comme sur uptobox merci

**Comment by hourra** [comment]
Sur zone telechargement il y a toujours un lien 1fichier.

**Comment by madmocas** [comment]
Non je voulais voir mes fichiers sur mon compte 1fichier je parlerai de l ajouter comme moncompteuptobox

**Comment by hourra** [comment]
Tu vas dans les options premium login de vstream et tu entres ton pseudo et mot de passe de ton compte 1 fichier . Déroule le menu option c'est en dernier.

**Comment by madmocas** [comment]
Non je voulais le ajouter au sites pour voir mes fichiers

**Comment by LordVenom** [comment]
déjà demander jamais réaliser si vous le voulez faudras le faire :)
