### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1782]
Hé oui vStream fait tous xD, bref jamais conquit par les video de présentation de vStream je me suis mis au taff.  

1- Donner vos idée ce qui mérite une présentation.
2- L'idée final une rubrique dans vStream d'aide, de présentation en video.

Note:  Je suis pas monteur et mon pc n'a pas de carte video dédier alors on vas rester soft.

https://www.youtube.com/channel/UCdyY1QEC8dJSU6-6GPKPrnA

**Comment by TmpName** [comment]
Lol, ben heureusement que c'est pas moi qui ait fait la video, j'ai vraiment un systeme plus light, j'ai pas la moitie de ta presentation.

**Comment by LordVenom** [comment]
xD 30mn de traitement pour 5min d'HD c'est bon je veut pas pire.

**Comment by karim71** [comment]
Super présentation 
Abonné aujourd’hui 
Très bon taff
