### ISSUE TITLE
Vstream crach sur SPMC

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#1783]
Salut à tous
Avant, il y a quelques temps je regarder vstream sur SPMC et maintenant à chaque fois que je lance une vidéo ça crach

Vous avez des infos ? Ça le fait chez vous aussi ?

http://paste.semperpax.com/poojljrf7

**Comment by TmpName** [comment]
Salut, il nous faudrait un log.

**Comment by lebigboss** [comment]
Ok, on les trouvent ou les log ? 
Désolé pour la question

**Comment by lebigboss** [comment]
http://paste.semperpax.com/poojljrf7

c'est bon j'ai trouvé et désolé pour la question

**Comment by TmpName** [comment]
Il faudrait plutot un log juste apres le bug ^^, pour pouvoir voir les messages d'erreur enregistres.

**Comment by lebigboss** [comment]
http://paste.semperpax.com/p4o08nad4
Voilà ;)

**Comment by LordVenom** [comment]
> ERROR: Unable to load /system/lib/libamplayer.so, reason: dlopen failed: library "/system/lib/libamplayer.so" needed or dlopened by "/data/app/com.semperpax.spmc16-1/lib/arm/libspmc.so" is not accessible for the namespace "classloader-namespace"

En regardant sur google je trouve l'erreur : 
Amcodec n'est pas disponible sur votre appareil. Il suffit de désactiver le codec.

**Comment by lebigboss** [comment]
Merci beaucoup mon pote, t'es un chef
Franchement tu me sauve

Kodi est bridé en 1080p sur Android box et je vais enfin pouvoir profité de la 4K
