### ISSUE TITLE
Sports not updating

### ISSUE THREAD

**Issue by laquarico** [Kodi-vStream/venom-xbmc-addons#1787]
Bonsoir premierement je voulais vous remercier developper poir le superbe travail que vous faites!!!
J ai juste une question edt ce que Robin des droits a disparu? La tedif des matchs de football n a pas ete updater depuis vendredi...

**Comment by lebigboss** [comment]
Va sur leur site, dans la section dernière upload ça date du 03/11

**Comment by laquarico** [comment]
Ba oui normalement ca prend just une journee mais la il y a aucune upload
du week end donc je me demandais si le site etait toujours vivant ou bien
ils avait arrete

**Comment by LordVenom** [comment]
Je vois aucune erreur perso

**Comment by laquarico** [comment]
Merci je vais verifier ce soir

**Comment by lebigboss** [comment]
Il y a un tchat sur le site et le mec avait dit qu'il avait tout enregistré mais que ça allé lui prendre du temps

**Comment by laquarico** [comment]
Merci pour ca.
