### ISSUE TITLE
Sous titre et lecteur uptobox

### ISSUE THREAD

**Issue by Aliasexterne** [Kodi-vStream/venom-xbmc-addons#1789]
Bonjour, 

depuis la dernière MaJ il m'est impossible d'afficher les sous titres d'une vidéo uptobox, peut importe la provenance. Est-ce que je suis le seul dans ce cas? J'ai essayé sur 2 supports différents et même soucis.
Si le problème est déjà connu, merci de ne pas tenir compte de ce post.

Bonne journée

**Comment by Arias800** [comment]
Oui je l ai remarqué hier malheureusement je peux pas m'en occupé pour le moments

**Comment by Aliasexterne** [comment]
Ok, pas de problème, je remontais juste le problème au cas où! 
Ce n'est pas bien gênant, d'autres sites proposent les vidéos avec sous titres incrustés direct dans la vidéo en attendant

**Comment by Aliasexterne** [comment]
Avec du retard... Seulement avec uptostrm.

**Comment by TmpName** [comment]
Donc me faudrait un lien qui ne marche pas pour tester, j'ai teste 2 films, a chaque fois les st etaient incrustes.
Sinon la langue n'apparait pas dans la liste generée, mais ca c'est facile a corriger, le regex est recupere mais pas affiche.

**Comment by Arias800** [comment]
Modf pour la langue effectué ^^ parcontre le regex pour les sous titre est bon

**Comment by Arias800** [comment]
J'ai trouve pour les sous titre je poste les nouvelle version

**Comment by TmpName** [comment]
Nickel, car la moi j'ai meme pas encore trouve le bug.

**Comment by Arias800** [comment]
Tu a pas vu le bug sur uptostr_am ou dans le script ?

**Comment by TmpName** [comment]
En live, pas vu de film avec sous titre separes.

**Comment by Aliasexterne** [comment]
Avec du retard, voici un log https://pastebin.com/embed_js/A9tjsm0k 
j'ai fait un test avec l'épisode 1 de la saison 4 de Peaky Blinders 
Impossible de charger les sous titre via uptostream alors qu'en lecture direct pas de problème. 
De mon côté et vu mon installation il est plus simple de lire via uptostm que de lire en direct. 
Le lien du fichier est là : https://ww1.zone-telechargement.ws/31057-peaky-blinders-saison-4-vostfr-hd720p.html ou http://uptobox.com/65lchumhgqfq 
Thks

**Comment by TmpName** [comment]
@Aliasexterne, il n'y a aucun probleme dans tes logs, ca trouve le fchier, extrait les bonnes infos, commence la lecture et ferme tout.
Essayes de telecharger le fichier et de le lire dans kodi.

**Comment by Aliasexterne** [comment]
J'ai fait la manip après avoir dl le fichier, je n'ai pas le problème. Cela vient seulement de la lecture via uptostream, mystère mystère. Pourtant il me détecte bien un soustitre quand je vais dans les paramètres de lecture, mais ensuite plus rien.

**Comment by TmpName** [comment]
Il y a une option speciale, me souvient plus du nom exact "DL+visu" en clic droit, ca va te telecharger le fichier, attendre quelques seconde et demarrer la lecture, si ca ca marche le prb viendra de ta connexion.

**Comment by TmpName** [comment]
Il y a une option speciale, me souvient plus du nom exact "DL+visu" en clic droit, ca va te telecharger le fichier, attendre quelques seconde et demarrer la lecture, si ca ca marche le prb viendra de ta connexion.

**Comment by TmpName** [comment]
La je peux pas te dire, c'est un mkv, les sous titres sont integres dedans, nous on passe juste le lien a kodi, apres c'est lui qui gere.
Je viens de voir qu'il y a une option pr activer/desactiver les soustitres trouve par Vstream dans les parametres, essayes de jouer avec ca.

**Comment by Arias800** [comment]
Perso j ai pas encore trouve de vidéo comportent un problème car chez moi les sous titre marche
