### ISSUE TITLE
Uptostream

### ISSUE THREAD

**Issue by toadnam** [Kodi-vStream/venom-xbmc-addons#1790]
Bonjour,
voilà je possède un compte debrid-link  depuis peu.
Je souhaiterai savoir s'il est possible de lire un fichier via uptostream (passer en streaming) et non uptobox (rester en direct) sur ZT?
je m'explique : 
J'ai une connexion qui est de 6-7 mega environ...
Et si je lance un épisode d'une série sur ZT sur uptobox, je choisis toujours uptostream sinon mon fichier lag à mort...!
Sauf que je suis limité aux 150mn par jour...
C'est pour cela que j'ai opté pour un compte debrid-link, qui me permet de ne plus avoir cette limite et d'autres avantages...
Sauf que je suis confronté à un problème que je ne savais pas, c'est que je ne peux choisir de lire via uptostream ni de choisir la qualité...
Helpppp! plizzzz

Bonne journée à tous
Hormis cela vous êtes au top!

**Comment by Arias800** [comment]
Déjà ton debrideur supporte t il uptostr_am ?

**Comment by toadnam** [comment]
oui il est compatible, j'utilise debrid-link.

**Comment by TmpName** [comment]
En passant Vstream ne gere pas debrid-link. En passant par urlresolver ca y est surement mais la c'est plus nous qui geront.

**Comment by toadnam** [comment]
oui c'est ce que je me suis dit, après avoir parlé avec venom hier... donc je dois voir avec urlresolver tu penses?

**Comment by TmpName** [comment]
Yep, quand tu passes par eux, Vstream ne gere rien du tout, on donne le lien web au pluggin et on lance le lien qu'il nous redonne, pas de parametres, pas d'options, rien de plus.

**Comment by toadnam** [comment]
tu sais si je peux rentrer en contact avec eux? et s'ils sont aussi sympa que vous? ;-)

**Comment by TmpName** [comment]
Lol, j'ai pas teste, je ne connais pas la version officielle, mais ils ont un github aussi.

**Comment by toadnam** [comment]
je regarderai alors , merci je vous tiendrai au jus !! ^^
