### ISSUE TITLE
Erreur connexion impossible 500

### ISSUE THREAD

**Issue by Akekekiukou** [Kodi-vStream/venom-xbmc-addons#1791]
Bonjour,
Une erreur depuis la dernière version 
Erreur: connexion impossible (500)

Merci d'avance

**Comment by TmpName** [comment]
Salut.
Ou ? comment ? log ?

**Comment by Akekekiukou** [comment]
Log:  view/s20auD6z6H

**Comment by LordVenom** [comment]
Hum faite l'erreur puis le log, la y a rien.

**Comment by Akekekiukou** [comment]
Voir pièce jointe
http://hpics.li/2847f53

Cette erreur apparaît de que je clique sur une rubrique sous vstream tel q film série documentaires etc... 

J'ai reproduit l'erreur à plusieurs reprise et le log est : view/s20FNSCMyt

Merci

**Comment by LordVenom** [comment]
Je voie rien activer le mode debug.

**Comment by TmpName** [comment]
il n'y aucun "plugin" qui se charge
`Vstream: cant import plugin: `

Qu'il y en ai qui rate c'est fait expes, mais tous ?
Y a pas quelqu'un qui a deja eu exactement le meme probleme ? Meme log ?

**Comment by TmpName** [comment]
Essayes en vidant le cache (dans les parametres de Vstream)

**Comment by LordVenom** [comment]
c'est quel version ?

> 18:45:00.285 T:18446744073047374128  NOTICE: URLResolver: Initializing URLResolver version: 4.0.09
> 18:45:00.528 T:18446744073047374128  NOTICE: metahandler: Initializing MetaHandlers version: 3.0.2

ça c'est pas "normal"

**Comment by Akekekiukou** [comment]
Kodi 17.5

**Comment by Akekekiukou** [comment]
J'ai activé debug mais maintenant il n'y a aucun lien pour le log. Qqn peut m'expliquer ?

**Comment by LordVenom** [comment]
Ha non ça devrais fonctionne pareil. au pire si tu est sur pc vas chercher le log toi même.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by Akekekiukou** [comment]
J suis sur mi box TV 4k

**Comment by LordVenom** [comment]
Ben alors la.. test ce que ta dit @TmpName sinon re-install vStream.

**Comment by Akekekiukou** [comment]
J'ai vide le cache et aussi fait une re-install mais toujours le même problème.
Je n'avais pas ce souci avant la dernière version

**Comment by LordVenom** [comment]
Hum c'est bizarre que tu puisse pas faire de log une foix le mode debug activer.

1) installer l'addon Log Viewer for Kodi : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

2) Nous transmette le log une foix l'erreur afficher.

**Comment by Akekekiukou** [comment]
s2Mh21yLpb

**Comment by LordVenom** [comment]
L'addon fonctionne quand même ?

Tu plante sur un code qui n'a jamais changer.
Alors je peux mettre une condition a ce bout de code mais si tu plante la dessus ça vas déconner ailleurs.

**Comment by Akekekiukou** [comment]
On peut essayer avec ta modification. Merci

**Comment by LordVenom** [comment]
Pas ce soir demain.

**Comment by LordVenom** [comment]
Tu n'a pas répondu a ma question l'addon fonctionne quand même d'autre addon fonctionne.J'ai regarder je peux pas outre-passer cette erreur qui est un erreur global (implanter dans le system) a voir ceux quand pense les autres perso j'ai rien vue de notre coter.

**Comment by Akekekiukou** [comment]
Oui laddon fonctionne mais avec des bugs.
Je vais essayer de Désinstaller kodi et faire une installation propre. 
Merci pour l'aide

**Comment by Akekekiukou** [comment]
J'ai tout r installé et ça fonctionne à nouveau. Plus d'erreur.😀
Par contre j'ai toujours le même problême avec zone téléchargement. La section série ne marche pas alors que j'ai aucun problème avec la section film

**Comment by Arias800** [comment]
Chez moi pas de probleme pour le series essaye de mettre a jour le fichier manuellement https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by Arias800** [comment]
Au pire utilise le patch de @luluvulcain https://github.com/luluvulcain/vStream-Kodi/issues

**Comment by Akekekiukou** [comment]
OK c'est bon. Merci
😊

**Comment by Arias800** [comment]
Si tout remarche je t'invite a fermer l'issue ^^
