### ISSUE TITLE
Probleme avec Kepliz !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1793]
Bonjour,
Quand je fais une recherche sur Kepliz et que je clique sur le lien pour regarder la vidéo, ça marche pas.
Pourriez-vous régler ce problème s'il vous plait ?
Cordialement,
Luluvulcain

**Comment by LordVenom** [comment]
Voila ça devrais allais.

**Comment by luluvulcain** [comment]
Merci LordVenom. Bon Travail.

**Comment by cnene7878** [comment]
Bonjour, 
Kepliz ne marche pas des qu’url resolver est activé. 
J’utilise realdebrid et ça ne marche pas non plus, et en désactivant le resolver ça refonctionne.
Peut être une modification à faire sur kepliz...

**Comment by LordVenom** [comment]
Quand j'ai tester ont pouvais pas faire de recherche la maintenant ça fonctionne.

Pour l'erreur fichier introuvable quel lien ? fonctionne t'il sur leur site ?

**Comment by luluvulcain** [comment]
@LordVenom : l'erreur fichier introuvable sur les liens que j'ai eu marche sur le site. Donc je penses que ça dois venir de chez eux.

**Comment by LordVenom** [comment]
il marche pas sur le site, tu voulais dire non ?

**Comment by TmpName** [comment]
Si ca marche en desactivant l'urlresolver, c'est que le resolver de vstream fonctionne mais pas le leur. Et la on n'y peut rien.
