### ISSUE TITLE
Chaines YouTube sur vStream !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#1796]
Bonjour,
Je penses que ça serais pas mal d’avoir certaines Chaines YouTube de Films ou autres à intégrer dans vStream ? Quand pensez-vous ?
Cordialement,
Luluvulcain

**Comment by Arias800** [comment]
Moi je suis pas contre mais le probleme c'est le robot de youtube qui dega en grande majorité des cas les video en bonne qualité :/

**Comment by LordVenom** [comment]
Y a un addon youtube qui fonctionne trés bien sur Kodi.
