### ISSUE TITLE
Besoin d'aide

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1797]
Bonsoir, besoin d'aide pour terminer ce fichier
[streaming_films_hd](https://gist.github.com/razorex/cbca5afb43b35cee1ce2242d8a06e61d)

je n'affiche pas le hoster (showHosters)

Merci

**Comment by Arias800** [comment]
J'ai ma petite idée mais je suis pas sur je doit effectué un ou deux teste je te tien au jus

**Comment by Arias800** [comment]
Non pour le moment je n ai pas encore retoucher au code

**Comment by TmpName** [comment]
Bon j'ai continue https://pastebin.com/3iUHwRJs
Alors, la par contre j'ai besoin de tests. Ce code ne marche qu'une fois, mais c'est pareil sur navigateur. Une fois que j'obtiens un lien, j'ai systematiquement le message d'erreur "Link expired..." pour les suivants, il me faut chnager de film pour que cela remarche.
Du coups, les cookies ne sont pas forcement necessaire, ni la tempo de 5 s. Mais comme je ne peux faire qu'un test a chaque fois, ca me prend des plombes.

Mais meme sur navigateur, si quelqu'un sait comment re avoir un lien (cliquer sur "click to refresh the player" ne marche pas). Antipub desactive, cookie active, ca bloque tjours au second coup.

**Comment by Arias800** [comment]
Il me semble que c est pas possible de réutiliser le lien déjà charger alors pourquoi ne pas stocker dans une variable le lien du hsoter et le réouvrir via urllib peut ce qui va recharge la variable k pour en avoir un valide

**Comment by johngf** [comment]
chez moi c'est ok https://pastebin.com/e0BFbtZR

**Comment by TmpName** [comment]
Je sais pas trop, il me faudra faire d'autres tests, je sais pas si ca marche via le cookie ou via l'ip, mais le fonctionnement est bizarre.

**Comment by razorex** [comment]
Plus personne pour me porter assistance....lol

**Comment by TmpName** [comment]
Ben le code propose par @johngf ne marche pas chez toi ?
Apres ca deconne aussi via navigateur, la on y peut pas grand chose.

**Comment by razorex** [comment]
Salut. Non il ne fonctionne pas chez moi.

**Comment by johngf** [comment]
augment le sleep
