### ISSUE TITLE
Plugins qui ne fonctionnent plus

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1799]
Bonjour,

filmvostfr et filmzenstream ne fonctionne plus au niveau de hosters.

**Comment by Arias800** [comment]
filmzenstream presque finit

**Comment by Arias800** [comment]
J'ai un probleme avec film zenstream car ca me mets cette erreur ' raise URLError('no host given')' voila le script https://pastebin.com/QBY2yUHm

**Comment by TmpName** [comment]
J'ai teste sur le premier film, pas vu de prb, tu testes avec lequel ?

**Comment by Arias800** [comment]
Oui je l'ai pas précisé mais c'est sur un film plus bas dans la liste (comme ryde , moi moche et mechant 3 par exemple)

**Comment by razorex** [comment]
le pb viens du faite que une fois l'url dans showHosters commence par http et d'autres non

**Comment by razorex** [comment]
Question bBelike ne devrait pas être dans les hosters???

**Comment by Arias800** [comment]
Belike sert juste pour "cacher" un hoster il me semble donc c est pas un hoster a proprement parlé

**Comment by razorex** [comment]
Filmvostfr à été corrigé par @johngf

**Comment by TmpName** [comment]
Je viens de tester pour filmzen, c'est pas juste parce que le le lien est tout simplement hs sur leur site ?

**Comment by razorex** [comment]
@TmpName c'est possible. seul ce film retourne une erreur 404, alors on peut ajouter un modif pour ne pas affiché le défaut, je l'ai faite sur mon fichier mais pas sur celui de la bêta. Perso pour un film pas forcément utile.

**Comment by TmpName** [comment]
Nope, je pense aussi.
