### ISSUE TITLE
URL resolver

### ISSUE THREAD

**Issue by bruinster** [Kodi-vStream/venom-xbmc-addons#1800]
Depuis se matin, sur PC egalement sur boite android, je ne peut configurer URL resolver a partir de Vstream, sa me donne erreur d'extention,  le probleme vient de Vstream puisque je peut configurer avec d'autre extention ?

**Comment by luluvulcain** [comment]
Faut que tu mettes à Jour URL Resolver en le téléchargent au https://androidaba.com/addons/script.module.urlresolver-4.0.01.zip

**Comment by bruinster** [comment]
C,est deja fait, mais toujour erreur d'extention sur mes 2 appareil et PC ?

**Comment by TmpName** [comment]
Il doit y avoir plusieurs version d'url resolver, moi je connais celui la https://github.com/jsergio123/script.module.urlresolver

**Comment by johngf** [comment]
Pour info url resolver pour la deuxieme fois n'est plus maintenu jsergio123 a supprimer le code sur github

**Comment by chataigne73** [comment]
Honnêtement ça sent mauvais. Les autorités ne s'attaquent plus seulement aux add-ons de diffusion de chaines payantes, mais aussi maintenant aux films. Disney, Netflix etc sont derrière l'action contre jsergio.

Je pense malheureusement qu'il faut penser à faire la même chose pour vstream.
Votre avis ?

**Comment by chataigne73** [comment]
C'est également fini pour covenant

**Comment by LordVenom** [comment]
Ben si il m’envoie des mails en anglais il sont pas prés de recevoir une réponse ^^

**Comment by luluvulcain** [comment]
Moi j'ai pas de Soucis avec URL Resolver

**Comment by luluvulcain** [comment]
Pour avoir URL Resolver, tu peux l'avoir au https://github.com/kodil/kodil/tree/master/repo/script.module.urlresolver

**Comment by Arias800** [comment]
Normalement on est protéger par la moi française car on herberge rien . Hadopie a même dit que vu que l add-on ne sert pas a passer les mesure de sécurité des ayant droit on n est pas considéré comme illégal

**Comment by TmpName** [comment]
TV-addon a dit continuer le suivi de l'urlresolver mais pour le moment faut attendre.

@LordVenom, t'inquietes pas meme en anglais, c'est compehensible ^^, j'ai deja du fermer un de mes github, tu recois un mail avec ecrit "DMCA" et "24h to solve the problem", apres sur le coup tu cherches pas a traduire les petites lignes, tu fermes tout tres vite.

**Comment by LordVenom** [comment]
Pour moi c'est du spam direct poubelle je regarde même pas le contenue.

24h to solve the problem ça me fait penser au mail d'arnaque pour paypal xD

**Comment by luluvulcain** [comment]
Pour mettre à Jour URL Resolver, il suffit télécharger la Dernière Version au au https://github.com/kodil/kodil/tree/master/repo/script.module.urlresolver
