### ISSUE TITLE
Developpeur

### ISSUE THREAD

**Issue by johneven** [Kodi-vStream/venom-xbmc-addons#1804]
Salut a tous,Je suis a la recherche d'un développeur pour me créer un addon kodi de ma bibliothèque films etc...Le taff sera rémunéré :-)

dsl de poster ca ici mais c'etais le seul endroit que j'ai trouver pour poser ma question.

bonne soiree

**Comment by vic1997** [comment]
Dit plutôt ce que tu veux faire

**Comment by johneven** [comment]
Ben comme je tai dis un addon kodi pour ma bibliothèque de films etc...

**Comment by vic1997** [comment]
@johneven ça sert à rien ce que tu viens de dire, tu l'avais déjà dis dans le premier post. Je te demande des détails, à quoi il sert l'addon que tu veux faire ?

**Comment by johneven** [comment]
@vic1997 c'est pour des clients a qui je veux partager ma bibliothèque de films et séries.
c'est possible que je t'explique plus en details et privee sur skype ou icq?

**Comment by vic1997** [comment]
@johneven Non je n'utilise plus skype et icq. Dis plutôt ici ce que tu veux et je te dirais quoi faire.

**Comment by johneven** [comment]
dsl impossible comme ca. sinon jabber?

**Comment by vic1997** [comment]
Non je n'ai pas non plus et de toute façon je ne viendrai pas si tu as une question tu la poses ici sinon tu peux supprimer le sujet s'il n'a rien à voir avec vstream. C'est possible que ça soit simple et que j'ai la réponse mais vu que tu ne veux pas poser ta question tant pis...
