### ISSUE TITLE
IMDB Note 

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#1806]
Salut à tous. 
Croyez vous qu'il soit possible d'avoir les notes d'imdb sur les liens Vstream. Comme Moviedb ?

**Comment by vic1997** [comment]
@lebigboss Salut, non, mais tu peux ajouter les films que tu veux à la librairie, ce qui te permettra d'avoir les infos que tu souhaites ensuite (note, nom, description...) grâce au scrapper.

**Comment by LordVenom** [comment]
https://youtu.be/-_-5-9fbcNg

**Comment by lebigboss** [comment]
Merci les mecs
