### ISSUE TITLE
Comment ouvrir une video src

### ISSUE THREAD

**Issue by helpmoi** [Kodi-vStream/venom-xbmc-addons#1808]
Bonsoir, 
Est-il possible d'ouvrir de jouer/lire une vidéo src sur ce lien par exemple htt p://www.trt.net.tr/anasayfa/canli.aspx?y=tv&k=trt1
Donc je vois comment récupérer le lien "src" qui diffuse la vidéo mais je ne vois pas comment le lire. Et je n'ai vu quasi aucun forum qui mentionne comment y arrivé. J'essaye de faire un petit addon qui permettrait de récupérer et diffuser la tv streamer sur le web.
Merci.

**Comment by TmpName** [comment]
Je dirais que oui, c'est comme un fichier m3u, apres faut voir au niveau des drms, teste avec vlc (plus facile a gerer que cette usine de xbmc) , si ca passe, ca passera sous kodi.

**Comment by helpmoi** [comment]
Ok, merci. Je vais regardé cela.
