### ISSUE TITLE
pb de mise a jour

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1809]
Bonjour

j'ai fais des modifications il y a plus de 10 jours sur certains fichiers (ex: cinemavf) et malgré les "updates" régulière elles ne sont tjrs pas intégrer dans vstream. je parle de mes box pas de la bêta.

**Comment by LordVenom** [comment]
Pourtant elle sont passer en mise a jour y a  6 Jours.Tu as verifier la date de mise a jour dans les parametres.

**Comment by razorex** [comment]
j'ai fais une maj hier et elle était incomplète, juste qq fichiers.

**Comment by LordVenom** [comment]
J'ai refait une mise a jour max 3jours xD

**Comment by razorex** [comment]
??????? donc tu dis que si je ne met qu'une partie des fichiers à jours le pb vient de mon côté????

**Comment by LordVenom** [comment]
Regarde le Merge de la mise à jour est tu verras les sites et hots qui sont dans cette mise a jour.

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/d1e0177f1a33d9b9572c988ca560fe5aff7ff110

**Comment by TmpName** [comment]
Tu connais la manip pour "forcer" la mise a jour chez toi ?

**Comment by razorex** [comment]
Une modif dans le fichier Home??????

**Comment by TmpName** [comment]
Nope, si tu ne l'as jamais fait (car ca va tout decaler) tu avances la date de ton systeme de 3 jours avant de lancer Vstream.
