### ISSUE TITLE
officiel film illimité 

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#1812]
Bonsoir à tous serait t'il possible d'ajouter la section 4k de film illimité ? 
merci d'avance

**Comment by LordVenom** [comment]
Oui tu peux le faire.

**Comment by sebi0606** [comment]
Ce dépasse malheureusement mes compétences ^^

**Comment by TmpName** [comment]
Il n'y a rien de complique, regarde juste les lignes 24 et 47/48/49.

**Comment by sebi0606** [comment]
Alors juste en regardant je me suis aperçu que la catégorie ultra hd était dans catégorie de film illimité seulement les liens ne marchent pas par le biais de vstream mais fonctionne sur le site peux tu regarder ? Merci

**Comment by TmpName** [comment]
Je viens de tester la categorie "HD", pas vu de problemes ?

**Comment by sebi0606** [comment]
La catégorie hd marche très bien c'est dans la catégorie ultra hd

**Comment by razorex** [comment]
Pareil pour la Ultra-HD

**Comment by KiliK150** [comment]
Par contre aucun lien n'est disponible dans la catégorie séries

**Comment by sebi0606** [comment]
@razorex nope je persiste et je signe quand tu es dans film illimité genre ultra hd quand tu lance uptostream tu as un message d'erreur alors que sur le site les liens fonctionnent merci

**Comment by Arias800** [comment]
Si tu n est pas premium ça peut posé problème et ne pas lance le lien regarde si il y a un time out dans les log

**Comment by yas06** [comment]
Salut moi je suis premium j ai testé film illimité genre ultra hd j ai testé le film  ça fonctionne en 4k

**Comment by Arias800** [comment]
Pour les série c'est "normale" car le hoster utilisé n'ai pas supporté car on voulait voir si il durai dans le temps

**Comment by TmpName** [comment]
Mais moi j'ai pas de section "Ultra HD" ?

**Comment by Arias800** [comment]
Tu doit avoir un bug de cache car moi je l'ai

**Comment by helpmoi** [comment]
Salut,
J'ai également la catégorie Ultra Hd

**Comment by TmpName** [comment]
Ben meme dans le fichier source , elle n'y est pas https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/film_illimit_fr.py
il y a juste "film HD"

**Comment by Arias800** [comment]
liste.append( ['Ultra-HD',URL_MAIN + 'ultra-hd/'] )

**Comment by yas06** [comment]
Salut si regarde ligne 79

**Comment by razorex** [comment]
La catégorie Ultra-HD existe dans les genres. je suis allé voir sur le site et les liens qui ne fonctionnent pas sur vStream ne fonctionnent pas sur le site ex: x-men ne fonctionne pas, the revenant fonctionne (des 2 côtés).

**Comment by sebi0606** [comment]
Salut @razorex je te confirme pour moi the revenant ne fonctionne pas sur vstream et je suis aussi Premium uptobox J'ai essayé sur kodi et spmc même souci :(

**Comment by razorex** [comment]
@sebi0606 je vient de refaire un essai chez moi çà fonctionne donc ce n'est pas vStream ou le fichier de film illimité...... ça vient de chez toi.

**Comment by KiliK150** [comment]
Salut, je viens aussi de tester the revenant en ultra : 
- sur Vstream le lien ne marche pas ( erreur : fichier introuvable ) 
- directement sur le site , le film démarre sans problème ( il faut juste désactivé l'adblock )

**Comment by Arias800** [comment]
y'a un petit soucis effectivement

**Comment by TmpName** [comment]
Testez avec ce fichier pour voir
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/uptostream.py

**Comment by Arias800** [comment]
Problème réglé chez moi
