### ISSUE TITLE
Hoster upvid sur cinemay

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1813]
Salut,
j'ai bien le hoster upvid dans le dossier hoster mais ça ne fonctionne pas. pas de lien, pas de création du fichier "compiled python file"

**Comment by johngf** [comment]
Tu a télecharger la beta entiere  ou seulement le fichier ?
Nouveau hoster ===> mise a jour de https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/hoster.py qui affiche les liens

**Comment by razorex** [comment]
Seulement le fichier.... dsl j'ai oublié ce fichier merci @johngf
