### ISSUE TITLE
voirfilms

### ISSUE THREAD

**Issue by korail** [Kodi-vStream/venom-xbmc-addons#1814]
Les liens voirfilms ne fonctionne plus depuis quelque jours chez moi quelqu'un sais quelque chose ? Merci !!!

**Comment by Arias800** [comment]
Le site a été mis a jour par @johngf

**Comment by korail** [comment]
je n'ai pas encore recu de Màj de mon coté

**Comment by Arias800** [comment]
normalement ca ne devrai pas tarde peut etre demain
