### ISSUE TITLE
French-stream

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1817]
Salut.
quelqu'un peut regarder french-stream plus aucun liens ne sont dispo sur vStream (films et séries).

Merci

**Comment by Arias800** [comment]
Il ont fait pas mal de modif il y notamment les lien cloudvid qui son caché

**Comment by TmpName** [comment]
J'ai commence https://pastebin.com/miiKY9P9
En fait  je pense qu'il me faudrait modifier la lib de Vstream RequestHandler, car elle ne gere pas toute les redirections.

J'ai commence a la modifier mais les url de redirection contiennent des caracteres bizarres, donc pas encore au point.

Sinon refaire le code avec urllib2.

**Comment by TmpName** [comment]
OK, c'est bon j'ai trouve pkoi.
Il y a un code JS dans la page qui change les url a la volee, donc celle affchee ne sont pas les memes que celles du code html.

J'ai mit en ligne une nouvelle version qui tourne, mais elle est a finir, y a plein de code a virer qui ne sert plus, et comme d'hab j'ai pas eu le temps de tout tester.

Reste a voir si le code JS sera fixe ou tournant.

**Comment by razorex** [comment]
ok je regarderais ce qui peut etre enlevé

**Comment by TmpName** [comment]
Apres j'ai pas eu le temps de tester, mais au vu de mes resultats, l'appel a l'url de decodage peut etre evitee (et du coup on peut decoder les url a la page precedente au lieu d'afficher lecteur 1 , lecteur 2)
L'id correspond a un hoster soit le debut de l'url et le second parametre et juste code base64, donc suffit de le decoder et de le rajouter au debut d'url.

**Comment by TmpName** [comment]
Bon j'ai continue , et effectivement on peut faire le decodage de notre cote.
J'ai commence les series, mais il faut refaire comme pour les film pour le decodage.

Fichier en ligne sur beta.

**Comment by razorex** [comment]
@TmpName  ton fichier n'est pas terminé c'est bien çà??

**Comment by TmpName** [comment]
Nope, mais je met a jours au fur et a mesure pour eviter q'un autre perde son temps a faire pareil.
La je recupere un pave de code avec les lien, a decoder 2 fois.
Et pour sId, je sais pas encore si ca sert ^^, je le prend au cas ou, quitte a le virer si inutile.

**Comment by TmpName** [comment]
Bon je pense avoir presque fini, me manque plus que les tests.
Par contre pour les liens iframse.secure, il faut la derniere version avec les modif de @LordVenom.

**Comment by razorex** [comment]
J'ai refait qq modif aujourd'hui les url ont changé.
