### ISSUE TITLE
Site en rose...

### ISSUE THREAD

**Issue by lorenzolamas** [Kodi-vStream/venom-xbmc-addons#1820]
Hello, 
Ca signifie quoi quand un site de streaming est écrit en rose ?

comme ça:
https://image.prntscr.com/image/TnxXs1oNS0GVzNcBsrmuIg.png

![image](https://user-images.githubusercontent.com/9819802/33489309-d31095ea-d6b3-11e7-8101-dcb84a9262e6.png)

**Comment by Arias800** [comment]
C'est des site de telechargement ^^
