### ISSUE TITLE
Séries Kaydo

### ISSUE THREAD

**Issue by KujoWolfgang** [Kodi-vStream/venom-xbmc-addons#1821]
Bonjour, merci pour votre super addons. VStream ses le best :)

J'aimerais apporté a votre attention que les séries ont cesser de fonctionner sur Kaydo.

Merci a l'avance

**Comment by TmpName** [comment]
A se sujet, je suis l  le seul a avoir des prbs avec cloudflare ? Notamment pour ce site ?

**Comment by Arias800** [comment]
je peux pas t'aider car le site me bloque l'acces

**Comment by LordVenom** [comment]
J'etait entrain de le faire quand je suis tombé sur une page membres only.

**Comment by Arias800** [comment]
Ah toi aussi il ton bloquer x)

**Comment by LordVenom** [comment]
Je pense pas ça ne passe pas non plus avec un VPN

**Comment by Arias800** [comment]
je sais pas chez moi ca me fait la meme chose ^^

**Comment by LordVenom** [comment]
Ben le site et HS ou en maintenant ou devenue priver.

**Comment by Arias800** [comment]
non a un moment j'ai pu acceder au site par hasard et il est toujours maintenu

**Comment by LordVenom** [comment]
Pour le moment site HS et désactiver sur vStream

**Comment by KujoWolfgang** [comment]
Bonjour, je suis désolé de vous déranger a nouveau.

Les séries sur Kaydo etait a nouveau fonctionnel, mais ce matin il on cessé de fonctionner.

J'ai vérifier les log de kodi:

14:19:29.141 T:10104  NOTICE: 	[PLUGIN] Vstream: could not load site: kaydo_ws error: Incorrect padding
14:19:29.141 T:10104   ERROR: Traceback (most recent call last):
14:19:29.141 T:10104   ERROR:   File "\Kodi\portable_data\addons\plugin.video.vstream\default.py", line 123, in parseUrl
14:19:29.142 T:10104   ERROR:     function()
14:19:29.142 T:10104   ERROR:   File "\Kodi\portable_data\addons\plugin.video.vstream\resources\sites\kaydo_ws.py", line 418, in showHosters
14:19:29.142 T:10104   ERROR:     url = Decode(str(aEntry))
14:19:29.142 T:10104   ERROR:   File "\Kodi\portable_data\addons\plugin.video.vstream\resources\sites\kaydo_ws.py", line 47, in Decode
14:19:29.142 T:10104   ERROR:     return base64.b64decode(chain)
14:19:29.142 T:10104   ERROR:   File "\Kodi\system\python\Lib\base64.py", line 77, in b64decode
14:19:29.143 T:10104   ERROR:     raise TypeError(msg)
14:19:29.143 T:10104   ERROR: TypeError: Incorrect padding
14:19:29.145 T:10104  NOTICE: 	[PLUGIN] Vstream: Table initialized

Merci a l'avance, Vstream ses le best :)

**Comment by TmpName** [comment]
Kaydo est en attente, le site bouge trop en ce moment.

**Comment by KujoWolfgang** [comment]
Merci d'avoir vérifier 👍

**Comment by luluvulcain** [comment]
Salut TmpName, j'ai ré-encoder le fichier Kaydo que LordVenom a mis dans vstream mais on as pas accés a la source car y'a pas le logo. Est-ce qu'il aurais possibilité de ré-activer la source de kaydo s'il vous plait ?

**Comment by TmpName** [comment]
Le logo n'est pas indispensable, il manquera, mais la source marchera.
Normalement si tu telecharges la beta, il va etre re-active car j'ai mit ton code a la place.

cf https://github.com/Kodi-vStream/venom-xbmc-addons/pull/1839

**Comment by KujoWolfgang** [comment]
Bonjour, J'ai copié le nouveau fichier (beta) et remplacer l'ancien. La source Kaydo n'apparait pas, est ce qu'il y a autre chose a faire.

Merci

**Comment by TmpName** [comment]
Nope, je viens de retester, ca marche.

**Comment by KujoWolfgang** [comment]
Ok, j'ai essayé en téléchargeant le fichier et le déposé dans le repertoir site. J'ai aussi essayé avec un edit du fichier d'origine et j'ai remplacer le contenue avec le contenue du nouveau fichier. Je ne vois pas la source kaydo dans Vstream

**Comment by luluvulcain** [comment]
Oui KujiWolfgang, chez moi ca fait pareil, la source Kaydo ne se vois pas. C'est moi qui est ré-encoder cette source et y'a un soucis avec le site appartement.

**Comment by KujoWolfgang** [comment]
Salut luluvulcain J'ai réussi a importer dans site, et ça apparait maintenant dans source, quand j'ouvre Kaydo, je vois le menu racine, ses à dire film, séries, etc, mais ça arrête la.

Merci du suivi.

**Comment by Momo5001** [comment]
Bonsoir à tous, tout d'abord un grand merci au staff, je ne sais pas comment contacter les admins pour leurs donner l'info mais kaydo (qui est quand même en contenu et qualité vidéo un pillier de vstream) a un site annexe www.hds.to ça lui arrive de changer de nom anciennement nommé filmstreaming.club mais le squelette ne bouge pratiquement pas. Si vous descendez en bas de la page vous verrez une image avec plusieurs écran et dans leur coin supérieur gauche inscrit kaydo.ws, j'espère que l'information serra utile et transmisse en haut de l'échelle eet surtout que nous reverrons bientôt kaydo ou pourquoi pas hds.to

**Comment by Arias800** [comment]
Quand on parle de Kaydo c est de hds. to donc on parle ont a juste pas changer le nom dans vstream pour simplifié

**Comment by johngf** [comment]
n'oubliez pas que 
- vpn >> bloqué
- proxy >> bloqué
- ip mobile(telephone ,routeur) >> 4G bloqué
- ip étrangère >> bloqué
- certaines ip française >> bloqué
- etc......
- fonctionné avant avec orange adsl 

pilier de vstream faut pas abuser non plus kep-liz je veux bien mais la c'est un site banal

**Comment by KujoWolfgang** [comment]
Bonjour,  j'aimerais bien vous aider, mais je sais pas jusqu'ou mon aide pourrais vous être utile.

en consultant le fichier kaydo.py j'ai remarqué deux chose.

Quand on ouvre la source Kaydo, on arrive pas a entré dans les dossier ex: films

J'ai regarder les log, et lorsque je clique sur le dossier films... Vstream tente de resssoudre le url: http://www.hds.totop-films.php, mais devrais ressoudre http://www.hds.to/top-films.php.

dans le fichier kaydo.py
j'ai donc remplacé URL_MAIN = 'https://www.hds.to' par URL_MAIN = 'https://www.hds.to/'

maintenant j'arrive a ouvrir le dossier films, séries etc... mais j'ai pas le bonbon a la fin. lorsque je veux ouvrir un films ou une saison, la plupart du temps je reçois un message ''no information'' mais j'arrive a faire décoller certain films.

Lorque j'ai le message ''no information'' je trouve ce qui suis dans les log de kodi.

File "C:\Users\JDM\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 123, in parseUrl
08:37:02 T:18308   ERROR:     function()
08:37:02 T:18308   ERROR:   File "C:\Users\JDM\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\kaydo_ws.py", line 409, in showHosters
08:37:02 T:18308   ERROR:     sHtmlContent = aResult.group(1).replace('return de("$")','') #serie
08:37:02 T:18308   ERROR: AttributeError: 'NoneType' object has no attribute 'group'

Merci a tout ceux qui travail a résoudre ce problème.

**Comment by LordVenom** [comment]
Je peux toujours pas test , ça vas finir désactiver de nouveaux.

**Comment by TmpName** [comment]
Lol, j'ai commence mais pas pu finir
https://pastebin.com/LUjDw4zj

J'obtiens plusieurs liens mais il y en a surement de faux, et je suis meme pas sur d'avoir le bon car il ya une partie que je ne traite pas encore.
A tester avec series, film pas encore au point

**Comment by LordVenom** [comment]
```
    oRequestHandler = cRequestHandler(sUrl)
    sHtmlContent = oRequestHandler.request()
```

me retourne : https://pastebin.com/E68AYfLv

Donc impossible de voir quoi que ce soit.

**Comment by TmpName** [comment]
Ca c'est a cause de la partie
```
    # modif url par Gregwar
    if '?' in sUrl:
        sUrl += '&r=n'
    else:
        sUrl += '?r=n'
```

Parfois ca marche, d'autre fois ca bloque, donc comme moi j'en ai pas besoin je l'ai supprime a pas mal d'endroits, ca doit etre necessaire a des endroits mais comme moi je ne suis pas bloque, je ne peux pas savoir ou c'est indispensable.

**Comment by TmpName** [comment]
J'ai mis a jour la version beta, les films et serie sont ok chez moi, mais bloque chez certaines IPs.

**Comment by LordVenom** [comment]
Nop je suis bloquer sur toute les urls :'(

**Comment by Arias800** [comment]
Pareil pour moi même avec un vpn

**Comment by TmpName** [comment]
Meme en rajoutant le "&r=n" ? et via navigateur ca tourne chez vous ?

**Comment by LordVenom** [comment]
Rien a faire &r=n , Vpn , reset cookie ect..

**Comment by TmpName** [comment]
La par contre je peux rien faire, si ca marche pas sur navigateur avec vos IP, c'est foutu.

**Comment by KujoWolfgang** [comment]
Merci TmpName. j'ai vérifié quelque séries que j'écoute, et ça fonctionne bien, la seul chose que j'ai remarqué, ses qu'il manque le 1er épisode de chaque séries/saison.

**Comment by TmpName** [comment]
Lol, ca me rassure de ne pas etre le seul chez qui ca marche ^^.

**Comment by KujoWolfgang** [comment]
TmpName, je confirme qu'ici ca fonctionne a merveille sans VPN. 

Pour ce qui est de la mise à jours que je voulais proposé dans la section beta. Ca fonctionne pour moi, mais j'ai pas réussi soumettre la petite modif dans le fichier beta.

Si tu peux SVP tester et valider

Merci pour tout

**Comment by TmpName** [comment]
J'ai deja validé.
