### ISSUE TITLE
Ajouter dossier dans librairie Vstream

### ISSUE THREAD

**Issue by chicungunya** [Kodi-vStream/venom-xbmc-addons#1822]
Bonjour,

Je pense que la question a déjà été posée mais je n'ai pas vu de réponse claire.
Je souhaite pouvoir ajouter un dossier à la librairie vstream.

Exemple : 

Je veux ajouter toute la saison 2 d'une série hébergée sur zone telechargement. 

Impossible je peux uniquement ajouter les liens finaux.

Sur Covenant ou Spekto j'ai vu que c'était possible mais il n'y a aucune série en FR.

Merci à tous et merci encore pour cet add on exceptionnel !

**Comment by TmpName** [comment]
Ca ne marche que pour les liens finaux, par contre tu peux mettre la saison complete en marque page.
