### ISSUE TITLE
Film illimit .py

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1824]
Les films en bonne qualiter et les series ne fonctionne plus nouvelle hébergeur.

Proteger par : juicycodes.js

https://clickopen.win/x/embed/Da928zI5lm346DC/

**Comment by Arias800** [comment]
Ca fait un moment qu'il existe pour les série il me semblé

**Comment by TmpName** [comment]
Ok, alors je viens de perdre 2 heures a comprendre leur code pour rien.
Alors c'est tout con, il faut recuperer la chaine 
`JuicyCodes.Run("XXXXXXX"+"YYYYY"+"ZZZZZ");`

Et virer les "+", ca va donner

"XXXXXXXYYYYYZZZZZZ"

Apres il suffit de le decoder en base64, ca va donner un code code avec Cpacker, et apres le decodage un code html avec le lien dedans.

**Comment by LordVenom** [comment]
Putain cette logique quoi ! j'ai vue un code de variable juicy je me suis dit que c'etait une clef pour décoder bizarre.Tu as lancer le codage ? sinon je regarde.

**Comment by TmpName** [comment]
Nope, en fait j'ai passe 2 heures a decrypter leur bordel et j'ai finallement reconnu un codage base64 fait a la main, mais j'avais plus trop la motivation de continuer apres ca ^^.
