### ISSUE TITLE
archos et vstream ?

### ISSUE THREAD

**Issue by thorsten68** [Kodi-vStream/venom-xbmc-addons#1826]
Bonjour a tous.
Pour pouvoir avoir un son 5.1 dans vstream j'ai tenter d'installer un lecteur auxiliaire archos qui lui le permet (je suis sur freebox mini 4k).
En effet si j'ouvre un film de mon DD avec archos j'ai bien du 5.1 que je n'arrive pas a avoir avec kodi.
J'ai donc suivit des tuto et installé kodiwrapper et copié le fichier playercorefactory au bon endroit.
Du coup je peux choisir dans vstream avec quel lecteur je veux ouvrir mon film.
Sauf que.... Quand je choisis archos le film ne démarre pas alors qu'avec videoplayer ça marche (mais avec un son 2.0)
Quelqu'un a une idée ?
Merci d'avance

**Comment by thorsten68** [comment]
J'ajoute que l'appli archos fonctionne bien, c'est que en essayant de l'utiliser dans vstream que ça ne marche pas (lien 1fichier)

**Comment by Arias800** [comment]
Dans les options de vstream tu peux choisir le lecteur par defaut il me semble

**Comment by thorsten68** [comment]
Oui mais archos n'apparaît pas dans la liste.
Ça aurait été simple sinon... :-(

**Comment by Arias800** [comment]
Ah bah la je sais pas du coup ^^

**Comment by LordVenom** [comment]
vStream n'est pas en cause mais le lecteur de Kodi et tes réglages une recherche sur internet t’apporteras plus de réponse que nous.

**Comment by thorsten68** [comment]
OK merci !

**Comment by thorsten68** [comment]
bon après une nouvelle bidouille, archos fonctionne avec kodi.
il est mon lecteur par défaut dans kodi et réussit donc a lire mes films (du DD) avec un son 5.1 dans kodi.
par contre en lançant un film dans vstream ca plante (lien premium 1fichier)
je vous joint le log, je suis sur que je suis près du but mais çà sera pas sans vous

10:09:14.756 T:18446744071809747712 WARNING: CPythonInvoker(15): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
10:09:30.150 T:18446744071809748352 WARNING: CPythonInvoker(16): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
10:09:45.638 T:18446744072444038656   ERROR: Control 500 in window 10025 has been asked to focus, but it can't
10:09:46.201 T:18446744071833598336  NOTICE:    [PLUGIN] Vstream: SQLITE 3 as DB engine
10:09:46.246 T:18446744071833598336  NOTICE:    [PLUGIN] Vstream: load site zone_telechargement_ws and call function Display_protected_link
10:09:46.385 T:18446744071833598336  NOTICE:    [PLUGIN] Vstream: DecryptDlProtecte : https://www.liens-telechargement.com/123455601123455603123455610123455615123455617tapmlrcu83
10:09:47.318 T:18446744071833598336  NOTICE:    [PLUGIN] Vstream: Table initialized
10:09:55.886 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: SQLITE 3 as DB engine
10:09:55.920 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: load site cHosterGui and call function play
10:09:55.970 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: Hoster - play https://1fichier.com/?tapmlrcu83
10:09:56.003 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: Utilise compte premium pour hoster onefichier
10:09:56.157 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: Auhentification reussie
10:09:56.159 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: https://1fichier.com/?tapmlrcu83|Cookie=SID=JaCCRufvtqXZ0UZZdmUmCLFNPPaxz7ZqVzwSGJT5gjeYMBwU6sHW0r1Te=4GDjMB;
10:09:56.187 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: playertype from config: auto
10:09:56.189 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: player initialized
10:09:56.243 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: Player use setResolvedUrl() method
10:09:56.612 T:18446744072444038656  NOTICE: ExternalPlayer Filename: org.videolan.vlc
10:09:56.612 T:18446744072444038656  NOTICE: ExternalPlayer Tweaks: hideconsole (false), hidexbmc (true), islauncher (false), warpcursor ()
10:09:56.612 T:18446744072444038656  NOTICE: OpenFile: https://1_fichier.com/?tapmlrcu83|Cookie=SID=JaCCRufvtqXZ0UZZdmUmCLFNPPaxz7ZqVzwSGJT5gjeYMBwU6sHW0r1Te=4GDjMB;
10:09:56.612 T:18446744071663917312  NOTICE: Process: Player : org.videolan.vlc
10:09:56.613 T:18446744071663917312  NOTICE: Process: File   : https://1_fichier.com/?tapmlrcu83|Cookie=SID=JaCCRufvtqXZ0UZZdmUmCLFNPPaxz7ZqVzwSGJT5gjeYMBwU6sHW0r1Te=4GDjMB;
10:09:56.613 T:18446744071663917312  NOTICE: Process: Content:
10:09:56.613 T:18446744071663917312  NOTICE: Process: Args   :
10:09:56.613 T:18446744071663917312  NOTICE: Process: Start
10:09:56.613 T:18446744071663917312  NOTICE: Process: Hiding Kodi window
10:09:56.707 T:18446744071663917312  NOTICE: ExecuteAppAndroid: org.videolan.vlc
10:09:56.756 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: player started
10:09:56.928 T:18446744071663917312   ERROR: CXBMCApp::StartActivity - ExceptionOccurred launching org.videolan.vlc
10:09:56.928 T:18446744071663917312  NOTICE: ExecuteAppAndroid: Failure
10:09:56.928 T:18446744071663917312  NOTICE: Process: Stop
10:09:56.928 T:18446744071663917312  NOTICE: Process: Showing Kodi window
10:09:56.935 T:18446744072348918784  NOTICE: Float is supported
10:09:56.985 T:18446744072348918784  NOTICE: Found 1 Lists of Devices
10:09:56.985 T:18446744072348918784  NOTICE: Enumerated AUDIOTRACK devices:
10:09:56.986 T:18446744072348918784  NOTICE:     Device 1
10:09:56.986 T:18446744072348918784  NOTICE:         m_deviceName      : AudioTrack
10:09:56.986 T:18446744072348918784  NOTICE:         m_displayName     : android
10:09:56.986 T:18446744072348918784  NOTICE:         m_displayNameExtra: audiotrack
10:09:56.986 T:18446744072348918784  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
10:09:56.986 T:18446744072348918784  NOTICE:         m_channels        : FL,FR,FC,LFE,SL,SR,BL,BR,BC,BLOC,BROC
10:09:56.986 T:18446744072348918784  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000
10:09:56.986 T:18446744072348918784  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_FLOAT,AE_FMT_RAW
10:09:56.986 T:18446744072348918784  NOTICE:         m_streamTypes     : No passthrough capabilities
10:09:56.987 T:18446744072444040576  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
10:09:56.990 T:18446744072444040576  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 28224 m_frames: 1764 m_frameSize: 8 channels: 2
10:09:57.359 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: player stoped
10:09:57.361 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: Closing player
10:09:57.376 T:18446744071809718272  NOTICE:    [PLUGIN] Vstream: Table initialized
10:10:17.580 T:18446744071663917312 WARNING: CPythonInvoker(19): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.

**Comment by thorsten68** [comment]
je precise que vlc n'est pas installé

**Comment by thorsten68** [comment]
voila le fichier playercorefactory utilisé
<playercorefactory>
        <players>
                <player name="ArchosVideo" type="ExternalPlayer" audio="false" video="true">
                        <filename>com.archos.mediacenter.videofree</filename>
                        <hidexbmc>true</hidexbmc>
                        <playcountminimumtime>120</playcountminimumtime>
                </player>

<player name="VLC" type="ExternalPlayer" audio="false" video="true">
<filename>org.videolan.vlc</filename>
<hidexbmc>true</hidexbmc>
<playcountminimumtime>120</playcountminimumtime>
</player>
        </players>
        <rules action="prepend">
                <rule protocols="smb" player="ArchosVideo" />
                <rule dvdimage="true" player="ArchosVideo"/>
                <rule protocols="rtmp" player="ArchosVideo"/>
                <rule protocols="rtsp" player="ArchosVideo" />
                <rule protocols="sop" player="ArchosVideo" />
                <rule internetstream="true" player="VLC" />
                <rule video="true" player="ArchosVideo"/>
        </rules>
</playercorefactory>

**Comment by thorsten68** [comment]
bon, ayant compris que le playercore factory voulait lancer vlc pour la lecture de streaming, j'ai installé vlc
celui ci ne permet pas d'avoir du 5.1 et ne demarre pas a partir de vstream
j'ai aussi essayé de modifier le playercorefactory pour qu'il lance archosvideo pour internetstream
sans succès

**Comment by thorsten68** [comment]
voila le log 

11:13:40.439 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: SQLITE 3 as DB engine
11:13:40.489 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: load site cHosterGui and call function play
11:13:40.554 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: Hoster - play https://_1fichier.com/?tapmlrcu83
11:13:40.592 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: Utilise compte premium pour hoster onefichier
11:13:40.760 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: Auhentification reussie
11:13:40.763 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: https_://1fichier.com/?tapmlrcu83|Cookie=SID=ww4LJsIPh0hWd7Eg67FYKgH0H3FA0gfH5lF3l7bVZWQheVvupOCihou=E4P4pp9s;
11:13:40.794 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: playertype from config: auto
11:13:40.797 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: player initialized
11:13:40.892 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: Player use setResolvedUrl() method
11:13:41.264 T:18446744072444039296  NOTICE: ExternalPlayer Filename: com.archos.mediacenter.video
11:13:41.264 T:18446744072444039296  NOTICE: ExternalPlayer Tweaks: hideconsole (false), hidexbmc (true), islauncher (false), warpcursor ()
11:13:41.265 T:18446744072444039296  NOTICE: OpenFile: https_://1fichier.com/?tapmlrcu83|Cookie=SID=ww4LJsIPh0hWd7Eg67FYKgH0H3FA0gfH5lF3l7bVZWQheVvupOCihou=E4P4pp9s;
11:13:41.265 T:18446744071919535232  NOTICE: Process: Player : com.archos.mediacenter.video
11:13:41.265 T:18446744071919535232  NOTICE: Process: File   : https:_//1fichier.com/?tapmlrcu83|Cookie=SID=ww4LJsIPh0hWd7Eg67FYKgH0H3FA0gfH5lF3l7bVZWQheVvupOCihou=E4P4pp9s;
11:13:41.265 T:18446744071919535232  NOTICE: Process: Content:
11:13:41.265 T:18446744071919535232  NOTICE: Process: Args   :
11:13:41.266 T:18446744071919535232  NOTICE: Process: Start
11:13:41.266 T:18446744071919535232  NOTICE: Process: Hiding Kodi window
11:13:41.325 T:18446744071919535232  NOTICE: ExecuteAppAndroid: com.archos.mediacenter.video
11:13:41.331 T:18446744071919535232   ERROR: CXBMCApp::StartActivity - ExceptionOccurred launching com.archos.mediacenter.video
11:13:41.333 T:18446744071919535232  NOTICE: ExecuteAppAndroid: Failure
11:13:41.333 T:18446744071919535232  NOTICE: Process: Stop
11:13:41.334 T:18446744071919535232  NOTICE: Process: Showing Kodi window
11:13:41.340 T:18446744072348921344  NOTICE: Float is supported
11:13:41.370 T:18446744072348921344  NOTICE: Found 1 Lists of Devices
11:13:41.370 T:18446744072348921344  NOTICE: Enumerated AUDIOTRACK devices:
11:13:41.370 T:18446744072348921344  NOTICE:     Device 1
11:13:41.371 T:18446744072348921344  NOTICE:         m_deviceName      : AudioTrack
11:13:41.371 T:18446744072348921344  NOTICE:         m_displayName     : android
11:13:41.371 T:18446744072348921344  NOTICE:         m_displayNameExtra: audiotrack
11:13:41.371 T:18446744072348921344  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
11:13:41.371 T:18446744072348921344  NOTICE:         m_channels        : FL,FR,FC,LFE,SL,SR,BL,BR,BC,BLOC,BROC
11:13:41.371 T:18446744072348921344  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000
11:13:41.372 T:18446744072348921344  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_FLOAT,AE_FMT_RAW
11:13:41.372 T:18446744072348921344  NOTICE:         m_streamTypes     : No passthrough capabilities
11:13:41.372 T:18446744072444041216  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
11:13:41.376 T:18446744072444041216  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 28224 m_frames: 1764 m_frameSize: 8 channels: 2
11:13:41.393 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: player started
11:13:41.394 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: player stoped
11:13:41.893 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: Closing player
11:13:41.899 T:18446744071919539072  NOTICE:    [PLUGIN] Vstream: Table initialized
11:14:01.415 T:18446744071919535872 WARNING: CPythonInvoker(9): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.

**Comment by TmpName** [comment]
C'est toi qui edite la ligne
`NOTICE: OpenFile: https_://1fichier.com/?`

Si non, il y a un soucis je pense, car ce n'est pas un lien video valide, (mais comme apres il essaye de lancer la video, je pense que ca du a une edition ?)

**Comment by LordVenom** [comment]
oui de moi :)

**Comment by thorsten68** [comment]
Oui c'est moi. C'est pas un soucis de lien, il fonctionne avec videoplayer.
Peut-être qu'archos n'est pas capable d'ouvrir les liens stream ?

**Comment by thorsten68** [comment]
Personne ?
