### ISSUE TITLE
goo.gl

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1827]
En corrigeant Gum gum streaming j'ai vue des liens goo.gl j'ai cherche si un code avais déja etait fait pour les liens racourcis j'ai trouver ça :          

```
   if 'http://goo.gl' in sHosterUrl:
                try:
                    headers = {'User-Agent' : 'Mozilla 5.10','Host' : 'goo.gl', 'Connection' : 'keep-alive'}
                    request = urllib2.Request(sHosterUrl,None,headers)
                    reponse = urllib2.urlopen(request)
                    sHosterUrl = reponse.geturl()
                except:
                    pass
```

Aprés plusieurs test cela ne fonctionne pas, plus.

Pour note et correction d'autre site plus tard. ce code fonctionne : 

```
            if 'goo.gl' in sHosterUrl:
                try:
                    import requests
                    url = sHosterUrl
                    session = requests.Session()  # so connections are recycled
                    resp = session.head(url, allow_redirects=True)
                    sHosterUrl = resp.url
                except:
                    pass
```

**Comment by Arias800** [comment]
Le premier code fonctionne sur coco stream il mes semble

**Comment by TmpName** [comment]
Il y a plein de code redondant, il y a aussi celui de tinyurl, je pense que ce serait utile de les mettre dans le fichier util.py et de creer une fonction GetGoo_gl(url), de cette maniere un seul fichier a modifier pour tout les endroits ou ce code est utilise.

**Comment by LordVenom** [comment]
@Arias800  tu est sur qu'il fonctionne ?

**Comment by Arias800** [comment]
La dernière fois que j ai utiliser coco stream il marchais après peut être que depuis il marche plus

**Comment by LordVenom** [comment]
J'ai fait plus simple j'ai creer un host de redirection :

- les +
Rien a faire au niveaux des sites hosts ça vas trouver que c'est une redirect et au click faire le taff tous seul

- Les -
Le Host affiche allow_redirect impossible de savoir quel est le vrais host avant d'avoir click (j'avais penser a une popup d'info mais bon ça fait un click en plus est ont vas me le reprochez xD).

**Comment by karim71** [comment]
@LordVenom
1 J’ai regardé voir films pour tester il propose tout les liens et qd tu y vas aucune information log ne signal rien
2 sur free telch les requetes sur les premières pages de chaque onglet aboutissent qd tu vas sur la 2 eme et 3 eme page la les liens tu y accede mais le ou le film démarre pas tu as une lecture sans image
Exemple 2 eme page spectacle mariage pour tous ou le mur
3 french dll pour moi il fonctionne pas 
Je t’enverrais mes logs demain
Bonne soirée

**Comment by LordVenom** [comment]
1 . Pas de soucis chez moi

2. Je teste même pas impossible de lire.  uptobox 1h entre chaque test les autres c'est premium.

3. Pareil premium uniquement je peux pas tester.

**Comment by karim71** [comment]
Ok je suis premium et cela marche pas
Pour le premier il doit y avoir un truc mais comme il y a pas d’erreur signalé jepeux pas te montrer le log

**Comment by Arias800** [comment]
1.Effectivement il y a un probleme au niveau des hoster (@LordVenom essaye le film "I wish" avec open_oad)

**Comment by LordVenom** [comment]
Ont n'est sortis du sujet ou ont parle encore de goo.gl ?

Quel site @Arias800 ?
