### ISSUE TITLE
openload

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1829]
Fonctionne toujours avec les url type openload mais pas avec les url type ht tp://oload.stream/

**Comment by TmpName** [comment]
Deja modifie il y a quelques jours sur la beta
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/edb75c6c91c6483d2caf3c3cb6ce64314a179c67#diff-40879c91530b4a2d3f1c95d70766a86b

**Comment by LordVenom** [comment]
Non non ça envoie bien sur le hoster mais ça n'aboutis pas je suis a jour sur le github.

**Comment by TmpName** [comment]
Ha ?
Tu testes sur quel site ?

**Comment by LordVenom** [comment]
Sur gum gum mais j'ai pas envoyer la version je suis dessus encore je tente de decripter iframe-secure.

Donc l'url c'est : 

https://openload.co/embed/Iw6M7LlLm9k/Angel_Beats!_01_-_Le_d%C3%A9part.mkv.mp4

ça retourne sur navigateur : 

https://oload.stream/embed/Iw6M7LlLm9k/Angel_Beats!_01_-_Le_d%C3%A9part.mkv.mp4

Mais ça a pas l'air de le gérer même si j'envoie direct l'url oload.

**Comment by TmpName** [comment]
Je viens de tester sur le site, ca deconne aussi.

**Comment by LordVenom** [comment]
Ben non.

![image](https://user-images.githubusercontent.com/4380112/33619055-79a0ea30-d9e4-11e7-90f7-766a40926220.png)

**Comment by TmpName** [comment]
Ok, ils ont mit en place un nouveau truc, faut desactiver antipub pour que ca fonctionne.

**Comment by TmpName** [comment]
Bon c'est tout con ^^, suffit de virer toute la fin de l'url, m'en occupe de suite.

**Comment by LordVenom** [comment]
Ho le iframe secure c'est rigolo ça decode un packer puis trouve le bon host puis lance le decode host puis lis le film. J'ai casi fini ça tourne faudras quand même plus de test mais pas aujourd'hui xD.

**Comment by LordVenom** [comment]
Tester ça fonctionne.

**Comment by TmpName** [comment]
J'espere que le mec qui conçu le cPacker touche des royalties, car on ne voit que ca.
