### ISSUE TITLE
Télécharger, DL et visualiser

### ISSUE THREAD

**Issue by hafuz** [Kodi-vStream/venom-xbmc-addons#1830]
Bonjour et merci pour votre addon....
J'essaie en vain de telecharger depuis vstream, est-ce en cours de mis au point ou est-ce un bug ?
Merci

**Comment by lorenzolamas** [comment]
tu as un débrideur?

**Comment by hafuz** [comment]
Oui, Alldebrid

**Comment by TmpName** [comment]
Un log ?

**Comment by hafuz** [comment]
Non, je n'ai pas de log (uniquement le log general)... J'utilise principalement Zone-Téléchargement avec *URLresolver (alldebrid dans mon cas). Quang je lance un "DL et Visualisaser" (ou un téléchargement seul) , il crée un fichier "nom.flv" vide, et ne lance pas la visualisation.
Pouvez vous me dire comment faire un log de l'opération ? Merci

**Comment by hafuz** [comment]
J'ai trouvé comment visualiser les logs... Voici une capture....
![capture du 2017-12-09 09-51-56](https://user-images.githubusercontent.com/7572478/33794210-c35fc7dc-dcc7-11e7-9593-ec15b42874f4.png)

**Comment by TmpName** [comment]
Et le stream ne marche pas ?

**Comment by hafuz** [comment]
Si, le stream fonctionne sans problème, juste le téléchargement ne fonctionne pas !!!

**Comment by hafuz** [comment]
@TmpName , je ne suis pas expert en python, mais penses-tu qu'il pourait y avoir un probleme avec l'adresse obtenue par URLResolver (version utilisée 4.0.15 avec compte alldebrid) lors d'une demande de telechargement, le streaming fonctionnant parfaitement ?
Merci

**Comment by TmpName** [comment]
Ben pour moi si le streaming fonctionne, il n'ya pas de prbs, le telechargement est pour les petites connexions, Vstream n'est pas une applis de dl.
UrlResolver change tout les 2 jours en ce moment, donc j'attend que ca se stabilise, mais dans tout les cas je n'ai pas de compte alldebrid pr tester.

**Comment by TmpName** [comment]
Je pense tout simplement que UrlResolver n'est pas compatible avec le systeme de telechargement.

**Comment by hafuz** [comment]
Je ne comprends pas pourquoi, omment fonctionne urlresolver? Y as tu il un appel direct à urlresolver ou vstrzam  débride  t il les liens en passant par Kodi ?

**Comment by hafuz** [comment]
> Ben pour moi si le streaming fonctionne, il n'ya pas de prbs, le telechargement est pour les petites connexions, Vstream n'est pas une applis de dl.

J'ai besoin de DL un fichier de temps à autre, donc cette fonctionnalité est pratique pour ma connexion en effet

> UrlResolver change tout les 2 jours en ce moment, donc j'attend que ca se stabilise, mais dans tout les cas je n'ai pas de compte alldebrid pr tester.

Si c'est UrlResolver qui deconne, peut-etre y a-t-il le meme probleme avec tout les debrideurs....

**Comment by luluvulcain** [comment]
Salut hafuz,
Pour régler ton problème, mis à jour URL Resolver à télécharger au https://github.com/tvaddonsco/tva-resolvers-repo/tree/master/zips/script.module.urlresolver

**Comment by hafuz** [comment]
Merci @luluvulcain, mais le telechargement ne fonctionne pas....
Le telechargement n'utilise pas  urlresolver, je pense, alors que les logs d'une lecture montrent clairement de "debridage" du lien.
 Ce qui n'est pas le cas lors du telechargement:
![capture du 2017-12-11 09-34-55](https://user-images.githubusercontent.com/7572478/33822255-333dc9f6-de57-11e7-9370-606e57733c94.png)

**Comment by luluvulcain** [comment]
Ca dois venir de ton Kodi. Efface les Données de Kodi, désinstaller-le, et ensuite installe la Mise à Jour de Kodi. Ensuite, installe le Repo de vStream et ré-installe vStream depuis son Repo.

**Comment by hafuz** [comment]
Après avoir suprimer toutes les entrées dans la liste de téléchargement et avoir installé vstream 0.5.7 et [urlresolver 4.0.15]( https://github.com/tvaddonsco/tva-resolvers-repo/tree/master/zips/script.module.urlresolver), tout est rentré dans l'ordre, merci.

@TmpName , @luluvulcain 
Serait-il possible d'ajouter mkv à la liste des extensions dans **download.py**
```
#recherche d'une extension
        sUrl = sUrl.lower()
        m = re.search('(flv|avi|mp4|mpg|mpeg|mkv)', sUrl)
        if m:
            sTitle = sTitle + '.' + m.group(0)
        else:
            sTitle = sTitle + '.flv' #Si quedale on en prend une au pif
```

et une supression totale des entrées dans la liste de téléchargement, pas seulement les fichiers terminés.

Les deux choses seraient utiles....

Merci à vous...

Hafuz

**Comment by TmpName** [comment]
Pour les mkv, c'est fait.
Par contre pour la suppression des fichiers incomplets, il te faut passer par le menu contextuel. Il n'y a pas de fonction pour supprimer tout les incomplets d'un coup, tout simplement car trop brutal. Si l'user rajoute des film a DL c'est pas pout tout vider le lendemain, au pire si il change d'avis sur un film je peux comprendre, mais sur une liste complete, la je vois pas.

**Comment by hafuz** [comment]
... lors d'un bug par exemple, après moulte essais, la liste se remplit vite... 
Merci pour les livres...
