### ISSUE TITLE
Kepliz - Lien Aucune Information

### ISSUE THREAD

**Issue by Atomium25** [Kodi-vStream/venom-xbmc-addons#1833]
Bonjour à tous,

Je me permets de vous exposer mon problème ici, puisque je n'ai pas vu de réponse dans le dernier post traitant de cette source.

Depuis un moment maintenant, lorsque que je vais sur les liens de cette source, je tombe sur "Aucune Information" alors qu'auparavant j'avais toujours les 2 liens : 720p 360p.

Tout fonctionne sur leur site et URL Resolver n'est pas activé dans les paramètres de Vstream.

Je ne sais pas si le problème est isolé à mon seul cas, ou si je suis passé à côté de quelque chose qui le solutionnerait ?

Merci d'avance,
Bon week-end à tous les utilisateurs et l'équipe de développement,

**Comment by toadnam** [comment]
Bonjour , 
Je viens de faire le test et c'est pareil chez moi. J'ai aucune information dans les résultats de ce site Kepliz.
Il doit surement avoir une mise à jour qui doit être dans les tuyaux bientôt...
Wait and see

**Comment by Arias800** [comment]
Ils ont du faire une modif sur leur site a mon avis il doit y avoir un systeme de cookie et les liens bloque des fois

**Comment by LordVenom** [comment]
Voila si quelqu'un veut test le nouveau et me dire chez moi c'est ok.

**Comment by toadnam** [comment]
Ça fonctionne ! Merci la team !

**Comment by FreeFighter77** [comment]
moi perso ca ne marche pas du tout.

**Comment by LordVenom** [comment]
Tu as bien tester la version bêta ?

**Comment by Atomium25** [comment]
Merci Lord, il fait donc forcer la mise à jour avec l'astuce des 3 jours pour voir le résultat ?

**Comment by TmpName** [comment]
Nope faut installer le fichier a la main soi-meme encore.

**Comment by Atomium25** [comment]
OK merci, je vais attendre la prochaine MàJ mensuel alors parce que depuis la box Android voilà voilà quoi :)

**Comment by mino60** [comment]
NB: la modification de TmpName marche pour l'instant elle ce trouve dans la version vstream-0.5.6
