### ISSUE TITLE
Source Extreme down 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#1834]
bonjour

J ai commencer à codé la source "extreme down" https://pastebin.com/yW6RgW0j
mais le problème c'est que je suis bloqué à la partie regex et aussi pour le captcha "https://ed-protect.org"
voilà je suis débutant sur python et j'ai du mal à comprendre le regex

Merci

**Comment by Arias800** [comment]
Le probleme c'est que ed-protect est proteger par recaptcha et je sais pas si il y a un moyens de le passé donc tant que personne a trouve une solution a ce probleme ca ne sert a rien de faire ce site

**Comment by Ovni-crea** [comment]
ok merci je savais pas

**Comment by Arias800** [comment]
apres si tu veux continué le site et t'entrainer tu peux^^. Donc pour faire simple le regex c'est ce que veut recupéré par exemple si il y a `<a href "https://www.unsite.pom"` le regex serai le suivant `<a href="(.+?)"` pour tester un regex tu peux allez sur pythex.org

**Comment by Ovni-crea** [comment]
J'ai trouvé ce tuto https://stackoverflow.com/questions/1440239/how-to-use-python-plugin-recaptcha-client-for-validation apparament c'est le client de validation de recaptcha 
je vais m'entrainer pour le regex

**Comment by Arias800** [comment]
Et surtout ne te decourage pas car au debut ca va etre dur ^^

**Comment by Ovni-crea** [comment]
oui je sais le début est simple c'est aprés que sa devient plus compliqué mais j'abandonne pas

**Comment by Arias800** [comment]
Si tu a la moindre question n’hésite pas ^^

**Comment by Ovni-crea** [comment]
ok merci bonne soirée

**Comment by johngf** [comment]
alors pour la 100eme fois c'est pas possible je l'avais deja fait ce site mais le problème c'est qu'il y a plusieur captcha différent et surtout recaptcha donc ne vous fatiguez pas.

[issue](https://github.com/Kodi-vStream/venom-xbmc-addons/issues?utf8=%E2%9C%93&q=extreme)
