### ISSUE TITLE
Sokrostream

### ISSUE THREAD

**Issue by 1shad** [Kodi-vStream/venom-xbmc-addons#1841]
Salut,

Pour ce site lorsque je fais une recherche j'ai un lien "security badge" qui apparait.
J'imagine que c'est mieux de le virer.

Alors  il y 'a surement mieux à faire mais je vous propose de remplacer cette ligne:   
[ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/7f2a34a70130886796c06cdb6811fd31e294fcc4/plugin.video.vstream/resources/sites/sokrostream_biz.py#L356)
Par:   
```
    for aEntry in aResult[1]:    
        if '/series/' not in aEntry[0] and '/films/' not in aEntry[0]:
           continue
```

bye

**Comment by johngf** [comment]
Ton fichier n'est pas à jour voila pourquoi

**Comment by 1shad** [comment]
Ben c'est que j'ai télécharger celui que tu as modifier aujourd'hui :)
( Les liens pour les pages suivantes fonctionnent )

**Comment by 1shad** [comment]
J'ai modifié la regex si tu veux, comme ça, le lien n'apparait plus:
[à remplacer](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/7f2a34a70130886796c06cdb6811fd31e294fcc4/plugin.video.vstream/resources/sites/sokrostream_biz.py#L346)   
par:
```
sPattern = 'data-v-.+?<a href="([^"]+)".+?<img src="(.+?)" alt="(.+?)".+?class="language'
```

**Comment by johngf** [comment]
corrigé mais j'ai pas mis language car ça peut changé et chez moi au premier essai ça a fait planté kodi

**Comment by 1shad** [comment]
Ca fonctionne, merci

**Comment by johngf** [comment]
@1shad la mise a jour que tu as fait c'était quoi le soucis ?

**Comment by 1shad** [comment]
@johngf La recherche n'affichait pas les series. Sur le site il faut cliquer sur le bouton 'series' pour avoir les resultats et le dom est modifier via javascript. ( pas d'ajax ), Alors j'ai rajouter les series aux résultats.   
J'ai aussi fait une modif sur le lien générer pour la recherche. Car avec des espaces dans le texte de recherche, ca ne fonctionnait pas.   
Voila globalement pour les  modifs

**Comment by johngf** [comment]
ok pour les espaces je pense que vstream les emplace par des + ou %20 si je me souviens bien

**Comment by 1shad** [comment]
Surement mais dans ce cas la non.      
Les url etait etait du type: http://.../search/the big bang   
par exemple, sans + ni %20. ( Pour la recherche globale ou normale )

**Comment by TmpName** [comment]
Vstream faisait des re-encodage lors des recherches globales ou visuelles, mais la plus maintenant (ou j'ai pas retrouve le reformatage) mais dans tout les cas jamais en direct.

**Comment by johngf** [comment]
il y a un soucis avec les accents qu'il n'y a pas sur d'autre site exemple : filmzen stream 
le titre avec accent s'affiche avec showmovies de la il est envoyé a showhoster en output
et la si on clic ça ne fonctionne plus 
'UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)'
le seul moyen que j'ai trouvé c'est de supprimer les accents avec unicodedata
mais pourquoi ça fonctionne dans showmovies  et sur un autre site et pas dans showhoster ???

**Comment by LordVenom** [comment]
C'est pas le MovieTitle qui déconne mais le aEntry["language"] il suffis de le code en str

    #sDisplayTitle = cUtil().DecoTitle(sMovieTitle + ' (' + aEntry["language"] + ')' )
par
      sDisplayTitle = "%s (%s)" % (sMovieTitle, str(aEntry["language"]))

DecoTitle n'est plus utile.

**Comment by johngf** [comment]
quand j'ai test ça avait l'air d'etre la combinaison des deux
