### ISSUE TITLE
DDL Island Séries OUT ?

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#1843]
Salut à tous,
Suis-je le seul à ne pas avoir accès aux séries de DDL ?

**Comment by lebigboss** [comment]
Non tu peux le fermer.  En faite j'ai mis une mauvaise API et ça me bloqué l'accès à DDL

**Comment by Arias800** [comment]
D'acc mais avant de fermer precise comment tu a résolu le problème ca peut toujours servir
