### ISSUE TITLE
Mega-Stream

### ISSUE THREAD

**Issue by pc1984** [Kodi-vStream/venom-xbmc-addons#1844]
Bonjour, 
Les liens Mega-Stream ne fonctionnent plus. Il semble que leur site web ne fonctionne plus aussi... Est-ce que vous avez des informations à ce sujet?

Excellente extension en passant! Je prévois vous faire un don pour Noël! 🥇 :)

Merci!

**Comment by pc1984** [comment]
En passant, les recherches visuelles ne semblent plus fonctionner non plus... :(

**Comment by lebigboss** [comment]
oui ça fait 2 jours que je l'ai désactivé des sources, ça me faisait crashé mes recherches

**Comment by LordVenom** [comment]
La bonne solution, désactiver les sources qui bloque, faire un rapport de bug xD

**Comment by johngf** [comment]
full stre am était HS aussi j'ai commencé https://pastebin.com/mW8HUNU1 en cours... 
reste soucis nextpage besoin d'une requete post
recherche.
niveau hoster unescape qui ne fonctionne pas avec les liens ne tu

**Comment by TmpName** [comment]
J'ai continue pour le coup du post https://pastebin.com/Y2cWN3d8
Par contre pas encore trouve pour le unescape, ca deconne pour les valeurs chiffrée.

Autre soucis, plus de recherche si pas enregistre.

**Comment by johngf** [comment]
j'essaie de convertir la function unescape sur leur site de js en python

**Comment by TmpName** [comment]
Je pense que c'est possible en modifiant la notre, elle marche avec les code hexadecimal, pkoi elle marcherait pas avec les code decimal.

**Comment by TmpName** [comment]
Lol, je viens de comprendre ce que tu disais ^^.
En fait il refont leur propre fonction unescape, une fausse.
Tu en es ou de la convertion en python ? Si tu as pas commence je m'y colle.

**Comment by johngf** [comment]
elle est faite ça fonctionne en local mais pas en parsant le code par regex 
boqué pour l'instant avec des listes

**Comment by johngf** [comment]
nouvelle version en test sur la beta
-pour la recherche ça changera peut etre par la suite c'est un nouveau site
-manga enlevé (il y en a que 6)
-ancienne catégorie suprrimer

**Comment by TmpName** [comment]
Yep, pour la recherche je pense pareil, et si vraiment y a de la demande on mettra un systeme d'authentification.

**Comment by pc1984** [comment]
Bonjour,
Si je comprends bien, il n'est pas encore prévu de remettre en marche la recherche visuelle?
Merci!

**Comment by TmpName** [comment]
Sisi, apres je sais pas ou ca en est, mais chez elle fonctionne.
C'est la recherche (normale et visuelle) via fullstream qui est en attente.

**Comment by pc1984** [comment]
La recherche visuelle ne fonctionne pas chez moi... :( J'ai Kodi 17.6 sur windows d'installé.

Aussi, il y a un site avec beaucoup de films et séries en HD. Peut-être que vous pourriez vous en servir comme une nouvelle source ? https://www.hds.to/

**Comment by Arias800** [comment]
hds c'est kaydo on a juste pas changé le nom

**Comment by pc1984** [comment]
Je ne vois pas Kaydo dans les sources de films... il y a Kepliz par contre?

**Comment by Arias800** [comment]
Normalement Kaydo devrait apparaitre essaye de copier collez ca : https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/kaydo_ws.py dans le fichier kaydo_ws

**Comment by pc1984** [comment]
Je le copie à quelle ligne?

**Comment by Arias800** [comment]
Tu copie la totalité du contenu de la page que je t'ai mit plus haut dans kaydo_ws

**Comment by pc1984** [comment]
Pardonnez mon ignorance! Je me suis aperçu que mon Vstream n'a pas fait la dernière mise a jour du repo 0.3 et de l'addiciel 0.5.8. J'ai installé le nouveau vstream sur un kodi vierge. Les recherches fonctionnent et le Kaydo apparait. :)
Toutefois, dès que je parcours les sources de Kaydo, la 2e page marque toujours erreur 301. Et ce sur n'importe quelle page de films ou séries (les plus vues, etc .).

**Comment by Arias800** [comment]
Tu peux accéder aux site via un navigateur classique ?

**Comment by pc1984** [comment]
Oui, je peux accéder au site hds.to. Dans Vstream, si je vais par exemple dans Movies/Genre/Kaydo/Action ... il n'apparait aucune source... et il y a erreur 301 encore.... :(

Suis-je le seul à avoir cette erreur?

**Comment by Arias800** [comment]
Je peux pas t'aider j'ai pas accès au site

**Comment by TmpName** [comment]
Passes par "sources". Le reste je jette un oeuil apres.

**Comment by TmpName** [comment]
Nouvelle version sur beta.
