### ISSUE TITLE
info concernant re-captcha 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#1854]
bonjour,bonsoir 

J'ai vue un topic concernant un gars qui essaye d'implenter un module de recaptcha sur python 
https://stackoverflow.com/questions/1440239/how-to-use-python-plugin-recaptcha-client-for-validation
et j ai trouver beaucoup de source de documentation concernant re captcha
https://developers.google.com/recaptcha/docs/display
https://code.google.com/archive/p/recaptcha/
et voici un lien de extreme down au moment du captcha
ht tps://ed-protect.org/KfHZif
ainsi que le code source de la page
https://pastebin.com/N9uU9uFG
et le code source du cadre
https://pastebin.com/FUd2PHEM

voila tout les infos concernant re captcha sur python je pense que c est totalement possible de 
l'implanter sur vstream 
Ps:Excuser moi pour les fautes d'orthographe

**Comment by TmpName** [comment]
Ce sont des modules pour s'en servir, pas pour valider un captcha.
Pour le faire tourner tourner sous Vstream je ne vois que 2 solution, passer par un service de "resolvation" de captcha, ou implementer un moteur Javascript.
C'est pas impossible, juste trop lourd pour ce qu'il y a gagner.

**Comment by Ovni-crea** [comment]
Apparament j ai trouver peut etre quelque chose 
https://github.com/eastee/rebreakcaptcha
tu me dit ce que t'en pense

**Comment by Arias800** [comment]
Sauf si je me trompe rebreakcaptcha est un faille corriger par Google il y a longtemps

**Comment by johngf** [comment]
ou https://github.com/ecthros/uncaptcha

**Comment by TmpName** [comment]
Les deux utilise un "navigateur" ca passe par selenium.
Le seul que j'ai trouve 100% autonome est celui la https://github.com/toogle/InsideReCaptcha
J'ai commence a bosser dessus, j'ai un code fonctionnel (celui du github ne marche que sur linux) mais le boulot est enorme, donc j'ai laisse tombe.

**Comment by Ovni-crea** [comment]
et celui la https://github.com/mardix/flask-recaptcha
je pense qu'il y a moins de truc a faire

**Comment by TmpName** [comment]
Tu as pas compris.Il y a 2 personnes:
1 - celui qui protege sa page avec recaptcha.
2 - celui qui veux acceder a la page.

Mon code marche pour le 2, le tiens pour le 1.

**Comment by TmpName** [comment]
Desole de faire le fossoyeur, mais je viens de tomber sur ca.
Apparement ca marcherait sans proxy.

https://2captcha.com/newapi-recaptcha-en

Faut resoudre pas mal de captcha sur leur site pour crediter un compte, mais apres c'est gratuit et ca marcherait pour recpatcha.

**Comment by Arias800** [comment]
C'est payant c'est 1000 pour 3 euro il me semble

**Comment by TmpName** [comment]
Sur 9kw tu as un tableur de combien coute/rapporte un captcha mais ils appellent ca "interactive captcha" je sais pas si ca parle de recaptcha.

Pour 2captcha je cherche si ca marche sans argent, c'est a dire comme 9kw, tu resous des captcha> tu gagne des points > tu les depense en faisant resoudre les tiens.

**Comment by TmpName** [comment]
Bon je laisse tomber, mais apparement on a 
1 - le service qui gere recaptcha mais qui ne marche que avec de la tune
2 - le service qui marche avec des points mais qui gere mal recpatcha (on recupere des images a cliquer)
