### ISSUE TITLE
bug concernant le repo vstream ?

### ISSUE THREAD

**Issue by mmtest1** [Kodi-vStream/venom-xbmc-addons#1855]
Bonjour,
j'utilise regulièrement vstream (encore un grand merci pour votre excellent boulot) sous raspberry et osmc, et depuis une semaine ou deux j'ai une mise à jour qui refuse de s'installer (OSMC Skin 17.0.3) sans rapport apparent avec Vstream à priori. Pourtant en recherchant le depot de mise à jour je decouvre avec grand étonnement qu'il y a une nouvelle rubrique disponible dans le depot de Vstream : habillage et qu'il contient la fameuse mise à jour. Dans un premier temps je pense que c'est un bug mais la rubrique habillage et également disponible sous kodi android contenant également osmc skin.
Avez-vous fait une correction mineure sur le skin afin de corriger un problème d'integration ? S'agit-il d'un bug ? ou d'une erreur ?
Je ne vois pas de difference puisque j'utilise confluence mais la situation me parait bizarre
Suis-je le seul à avoir la rubrique habillage avec osmc skin sur le depot de Vstream ?
Merci

**Comment by mmtest1** [comment]
Edit : depot vstream officiel téléchargé sur le github, kodi et osmc dernière version stable, vstream à jour

**Comment by LordVenom** [comment]
Ha je vais déplacer ça ce sont des fichiers sauvegarde pour moi.

**Comment by mmtest1** [comment]
je viens de relancer une recherche de mise a jour pour rafraichir les depots et la section habillage est toujours visible avec la mise a jour de osmc skin (avec echec de l'installation)

**Comment by LordVenom** [comment]
Voila ça devrais aller xD

**Comment by mmtest1** [comment]
toujours dispo chez moi, peut-etre une histoire de cache, je verrais au prochain demarrage, une verification des mise a jour renvoie toujours une erreur d'installation, ou peut-etre faut-il attendre que le serveur se synchronise....
merci

**Comment by mmtest1** [comment]
Je viens de vider le cache de Kodi et les autres clear à partir des outils de vstream et j ai toujours accès à la rubrique apparence sous le dépôt et erreur d installation de mise à jour osmc

**Comment by LordVenom** [comment]
@mmtest1  : Je clos l'issue mais si a la prochaine mise a jour mensuel ça deconne toujours revient me prevenir.
