### ISSUE TITLE
Changer la vue par défaut du mur

### ISSUE THREAD

**Issue by cormaltes** [Kodi-vStream/venom-xbmc-addons#1857]
Est-il possible de changer la vue par défaut du mur des films et séries que ce soit appliqué partout ?

Car à chaque fois que je change de pages ça repasse à la vue par défaut.

Merci

**Comment by TmpName** [comment]
Tu es dans la recherche visuelle ou le mode classique ?

**Comment by cormaltes** [comment]
Dans la recherche visuelle

**Comment by Arias800** [comment]
C est normale la vue est "bloqué" car si on remet la vue normal on pers le cote visuel

**Comment by johngf** [comment]
pour la recherche visuelle normalement on peut le changer dans les paramètres 
Vue : recherche visuelle recommandé 500 tu clic et change le numéro 500
en 50 ,51 ,500 ,508, 501 et il y a surement d'autres type de vue
