### ISSUE TITLE
Ajouter un lien dans vstream 

### ISSUE THREAD

**Issue by donsai007** [Kodi-vStream/venom-xbmc-addons#1858]
Bonjour je voudrais savoir si cest possible d’ajouter un lien dans vstream car jai vu un lien ou tous les film disney sont dispo en francais et pour les petits sa seras que du bonheur 

Je cite le lien ici 

Je suis noob au developpement 
Si je peux faire une donation au service je ferais avec plaisir 

Voici le lien 

disneyhd.tk

**Comment by bernzJ** [comment]
Regarde [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/sites.json), control + F et entre le nom du site: **disneyhd**.

**Comment by Arias800** [comment]
Deja dispo dans toute les source

**Comment by johngf** [comment]
il est déja dans vstream 
sur la page d'accueil de vstream clic sur sources ensuite disney hd
