### ISSUE TITLE
Vstream et compatibilité 

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#1860]
Bonjour 

Vu son succès est il possible de voir ce plugin compatible d'autre logiciel comme Movian (pour PS3) ou Perfect Player (Pour android et PC?

Merci

**Comment by AizenKnower** [comment]
Pas de réponse ?

**Comment by Arias800** [comment]
Kodi est dispo sur android pc et apparemment ps3 donc la réponse est non

**Comment by johngf** [comment]
vstream a besoin de kodi donc pas de kodi pas de vstream
