### ISSUE TITLE
Sous dossiers VotreCompteUpToBox ne sont pas pris en compte

### ISSUE THREAD

**Issue by vic1997** [Kodi-vStream/venom-xbmc-addons#1862]
Salut,
J'ai remarqué qu'en utilisant mon compte premium UpToBox, en passant par "Toutes les sources" puis "Votre compte UpToBox" on avait bien accès aux dossiers à la racine ainsi qu'aux fichiers qui y sont mais on n'a pas accès aux sous-dossiers, ça serait bien de pouvoir avoir accès aux sous-dossiers.
Par exemple, j'ai moi même un dossier film et un dossier séries.
Le dossier film contient directement les films, donc ici aucun problème tout s'affiche.
Le dossier séries contient lui d'autres dossier qui correspondent chacun à une série, cependant je ne peux pas y accéder car ces sous dossiers ne s'affichent pas.

Voici un screenshot de ce qui se passe quand on va dans le dossier ayant normalement des sous-dossiers : https://i.imgur.com/biNUf2P.png

**Comment by johngf** [comment]
je l'ai deja fait ce truc faut que je retrouve le fichier mais je pense qu'il y avait un soucis
apres faut une limite a tout
alors un dossier (nom de serie) des sous-dossier (saison) ça s'arretera la en ce qui me concerne
je jeterai un oeil demain

**Comment by Atomium25** [comment]
Je me rappelle avoir déjà soulevé le problème il y a un certain temps déjà et effectivement il y avait un petit problème je crois ..
En ce qui me concerne le plus logique serait 3 niveaux de dossiers ( Un pour organiser le type de fichier Film / Série, un autre pour les titres des séries et un dernier pour la saison) pas besoin de plus je pense.

Merci d'avance en tout cas parce que cela pourrait vraiment être pratique 👍

**Comment by vic1997** [comment]
Oui je pense la même chose que @Atomium25 , 3 niveaux serait juste bien. Et là il n'y en a qu'un seul ! (donc pas du tout de système de sous-dossier), ça serait cool et utile de pouvoir en avoir plusieurs. Je suis obligé d'utiliser un autre addon juste à cause de ça.

En tout cas merci d'avance !!!!

**Comment by Darkfuzz42** [comment]
Bonjour, effectivement ça serait cool de pouvoir rajouter des sous dossier pour cette source. J'avais aussi une question pour savoir si c'était possible de rajouter des metadata aux films et séries dans cette source ?

**Comment by vic1997** [comment]
@Darkfuzz42 Salut, j'ai réfléchie et chercher longtemps comment faire, après plusieurs jours de recherche j'ai conclue que le meilleur était le duo OSMOSIS/Vstream (Je suis obligé d'utilisé CloudStream encore pour les séries vu que Vstream ne gère pas les sous-dossiers). Osmosis permet d'obtenir les metadatas sur les films directement obtenue en streaming via Vstream.

**Comment by Darkfuzz42** [comment]
@vic1997 merci pour ta réponse je vais essayer cet addon

**Comment by johngf** [comment]
bon alors tester ça [ici](https://raw.githubusercontent.com/johngf/ab/master/siteuptobox.py)

par contre l'upload a partir des liens 1 fichier ne fonctionne plus pour l'instant pas encore trouvé pourquoi

**Comment by vic1997** [comment]
@johngf Ca marche niquel !!! Super !!! Avec un nombre illimité de sous dossier (j'ai testé jusqu'à 6) et ça fonctionne impec' ! Merci beaucoup johngf !! Manque plus qu'à l'ajouté à la version officiel de vstream. Pour ma part je valide, tout marche et c'est ce qu'il manquait.

**Comment by Darkfuzz42** [comment]
Marche très bien sur Android merci beaucoup

**Comment by vic1997** [comment]
@johngf Est ce que ça a été ajouté pour la prochaine mise à jour ? Pour ma part je n'ai plus les droits donc je peux pas l'accepter, après je peux faire le commit si il faut, comme tu veux.

**Comment by vic1997** [comment]
J'ai pris l'initiative de faire le pull request.

**Comment by Arias800** [comment]
Normalement c'est bon si je me suis pas foiré x) (c'est la 1er fois que je fait ça)

**Comment by vic1997** [comment]
@Arias800 Oui normalement c'est bon. Je sais pas pourquoi j'ai plus les droits pour le merge moi même, pas grave, merci ! 👍

**Comment by Arias800** [comment]
Peut être que tu a été inactif pendant un moment faut voir avec @LordVenom

**Comment by vic1997** [comment]
@Arias800 Oui, je viens de retrouver les messages, effectivement je lui avais dit qu'il pouvait me retirer du groupe, j'avais oublié.

**Comment by johngf** [comment]
je ne l'ai pas mis sur la beta parceque je testé l'upload de fichier rapi gator et turbo bit sur le compte

**Comment by vic1997** [comment]
@johngf Ha ok, je savais pas que tu faisais encore ça. Je ne comprends pas, à quoi sert l'upload de fichier de ces hébergeurs par rapport à uptobox ?

**Comment by johngf** [comment]
a envoyer les fichiers sur ton compte up tobox sans avoir besoin d'un compte chez les autres hébergeur

**Comment by vic1997** [comment]
@johngf Ha ok j'ai compris, ça sert à ajouter un film trouvé sur vStream directement sur son compte UpToBox. Ok ! Je n'utilise pas cette fonction c'est pour ça que j'ai pas compris. (je passe directement par les sites de téléchargement et j'ajoute les films à mon compte)

**Comment by johngf** [comment]
tu n'as pas compris c'est justement des hébergeurs que tu trouve sur les sites de telechargements comme zt etc...

**Comment by vic1997** [comment]
@johngf Oui c'est ça que j'avais compris

**Comment by madmocas** [comment]
salut quelqu’un peut me expliquer comment mettre les fichiers dans un dossier uptobox 
j aimerai avoir 3 a 4 dossiers avec films séries animations 
merci

**Comment by vic1997** [comment]
Regarde ce screen que j'ai fais de mon compte.
https://i.imgur.com/eY78DD3.png
Le 1 permet de créer un dossier.
Le 2 permet de sélectionner les films.
Le 3 permet copier ou déplacer les fichiers dans un dossier, la destination est choisit avec le 4.

Mais ça n'a rien avoir avec Vstream.

**Comment by madmocas** [comment]
Merci Vic 1997

**Comment by madmocas** [comment]
Et pour déplacer un dossier dans un dossier commun est possible

**Comment by vic1997** [comment]
@madmocas J'avais demandé à UpToBox directement, ce n'est pas possible, on ne peux pas déplacer un dossier. Il faut réfléchir avant de le créer, car on ne peut plus le déplacer une fois fais.

**Comment by madmocas** [comment]
OK comme ça je le sais merci

**Comment by Kastoner63** [comment]
Bonjour j'ai un problème je ne peut pas ajouter mes séries et ses sous-dossier présent sur mon compte uptobox premium.

J'utilise le duo vstream et osmosis mais j'ai eu erreur quand je fait un clique droit puis create strms
Version vstream 0.7.4  osmosis 1.0.7

**Comment by Kastoner63** [comment]
> Tu auras pas au moins le message d'erreur venant des logs stp ?

Je l'ai ajouter sur mon propre post https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2635
