### ISSUE TITLE
film illimité 

### ISSUE THREAD

**Issue by moimeme45** [Kodi-vStream/venom-xbmc-addons#1864]
Salut a tous
Je n'ai plus rien sur film illimité 😯
C'est dommage car beaucoup de films en 1080p
Merci de jeter un oeil si vous pouviez ☺
Merci d'avance

**Comment by Arias800** [comment]
Deja fait par @LordVenom plus qu'a attendre la maj (dans max 3 jour)

**Comment by moimeme45** [comment]
Je ne savais pas
J'attend la MAJ encore merci a toute l'equipe
Bye
