### ISSUE TITLE
EXTREME DOWNLOAD

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#1865]
https://www.extreme-down.pro/home.html

Bonjour , extreme download est un des site que je me sert , avec un compte premiun uptobox , equivalent a zone téléchargement , par contre faut il du streaming ?

**Comment by Arias800** [comment]
Impossible et les proposition c'est ici ; https://github.com/Kodi-vStream/venom-xbmc-addons/issues/517

**Comment by ktm520** [comment]
Dommage que se soit impossible de mettre extreme download , désolé , je ne savait pas qu'il avait un sujet ouvert , pour les propositions de sources  .
