### ISSUE TITLE
Bye bye Gotham, Helix et Isengard

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1868]
Pour la version 0.5.8 

Mise a jour de xbmc.python qui tourner encore sous la version 2.14.0  (Gotham 13.x)
Nous sommes passer en 2.24.0 (Jarvis 16.x, Krypton 17.x, Leia 18.x)

Pour ceux que ça intéresse : http://kodi.wiki/view/Addon.xml#Dependency_versions

**Comment by Arias800** [comment]
La plus vieille becanne que j'ai tourne sous kodi 12 avec la version 0.5.7 (modifié) donc si la personne bidouille un peux elle peux faire marche la 0.5.8 non ?

**Comment by LordVenom** [comment]
Oui et non pour python il suffis de changer la version de xbmc.python dans addon.xml pour le reste a voir les erreurs que ça retourne.

**Comment by Arias800** [comment]
Ok ^^

**Comment by freddykrueger59** [comment]
Bonsoir
Quelle version je peux utiliser avec Kodi 15.2 ?
J'aimerais rester sous 15.2 car j'ai des  soucis avec les nouveaux décodeurs mediacodec surface
Merci
