### ISSUE TITLE
Repository Version 0.0.3.

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#1870]
Bonjour , j'ai vu qu'il existe un nouveau Repository Version 0.0.3. , faut il obligatoirement l'installer en remplacement de la Version 0.0.2.  ?

**Comment by Arias800** [comment]
Il est possible qu'elle sois nécessaire a partir de la 0.5.8 car @LordVenom est passé sous une nouvelle version de xbmc.python (une dépendance)

**Comment by ktm520** [comment]
On peut installer la nouvelle version du Repository a la place de l'ancienne , sans réinstaller le plugin   ?

**Comment by Arias800** [comment]
Normalement oui mais attends @LordVenom pour voir si c'est nécessaire que tu l'installe

**Comment by ktm520** [comment]
Merci pour la réponse  ,  je vais attendre la confirmation .

**Comment by ktm520** [comment]
![joyeuses-fetes-2016](https://user-images.githubusercontent.com/34879102/34452324-29543e26-ed3d-11e7-8049-fa0eab17e691.jpg)

**Comment by LordVenom** [comment]
Merci joyeuses fêtes a tous aussi.

Oui le repo 0.0.3 est une dépendance de vStream 0.5.8.

Si tu as le repo 0.0.2 la version 0.0.3 vas s'installer automatiquement ainsi que vStream 0.5.8

Tu peux remplacer manuellement le repo 0.0.2 sans soucis pour vStream.

**Comment by ktm520** [comment]
Merci pour la réponse , la mise a jour vStream 0.5.8 c'est fait automatiquement , donc le repo doit être la version 0.0.3. , je peux vérifier dans kodi ?
Super travail continuez .

**Comment by Arias800** [comment]
Oui tu va dans installer un add-on via repository et te positionne sur vstream repository

**Comment by ktm520** [comment]
La version du repo est bien passée en 0.0.3. , avec la mise a jour 0.5.8
