### ISSUE TITLE
Pas de lien sur zone telechargement

### ISSUE THREAD

**Issue by nabsboss** [Kodi-vStream/venom-xbmc-addons#1871]
Salut,

J'attendais une mise à jour mais apperement il n'y a plus de lien ! J'utilise la dernière version 0.5.8, suis je le seule dans ce cas ?

Chez des amis, ils ont le même problème mais je ne vois pas d'où ça peut venir :(

Merci pour vôtre aide !

**Comment by Arias800** [comment]
J'ai corrigé ca par contre la mise a jour ne s'est pas fait

**Comment by nabsboss** [comment]
J'avais déjà remplacé hier le fichier zone_téléchargement_ws.py de la version beta qui a été modifié, je l'ai mis à son enplacement mais ça n'a rien changé. J'ai loupé une manip genre un autre fichier à remplacer ?

Merci

**Comment by Arias800** [comment]
Moi aussi ça me l'a réinitialisé aujourd'hui car il y a eu une maj réessaye car chez moi ça marche

**Comment by nabsboss** [comment]
Ça marche toujours pas. J'ai retélécharger le fichier, vides les caches/bdd redémarrer etc...mais rien n'y fait :( Je vais essayer le patch pour voir, dommage qu'il n'y ait pas de repository pour ça d'ailleurs !

**Comment by Arias800** [comment]
Bizarre chez moi ca marche quel version de kodi ?
Pour le patch il faut voir avec la luluvulcain c'est lui qui s'en occupe

**Comment by nabsboss** [comment]
Kodi 17.6 sur NVIDIA shield

**Comment by nabsboss** [comment]
J'oubliai vstream 0.5.8 et toi ?

**Comment by Arias800** [comment]
vstream 0.5.8 aussi . Essaye serie vostfr => BlackMirror S04 et dit moi si ça marche (n’importe quel qualité)

**Comment by nabsboss** [comment]
Intéressant ! On ne fait pas la même chose :) oui comme ça, ça marche ! Mon problème c'est quand on passe par la recherche visuelle qui donne aucun lien pour ZT !

**Comment by Arias800** [comment]
Donc ça doit être la recherche visuelle qui a un problème car zt fonctionne

**Comment by nabsboss** [comment]
Je me doutais que c'etais la 5.0.8 mais j'en étais pas sûre mais là c'est une confirmation :) En plus, la fenêtre de résultat bug souvent, elle ne s'ouvre pas ou s'ouvre plus tard et relance la recherche !!?? Un truc de ouf !
Ça te le fais aussi en recherche visuelle sur un movie pour ZT ?

**Comment by Arias800** [comment]
Je n'utilise jamais la recherche visuel ^^

**Comment by nabsboss** [comment]
Lol !! Tu peux tester ? Je me sentirai moins seul ;)

**Comment by Arias800** [comment]
Je fait un essaie ^^

**Comment by nabsboss** [comment]
Merci ;)

**Comment by Arias800** [comment]
Apres si c'est le site en lui-meme qui renvoit rien malheureusement on peux rien y faire parce que la recherche normale marche

**Comment by nabsboss** [comment]
Recherche non visuel ? Je me demandais si c'était pas le nombre de sites qui fait que ça déconne, j'essaierai en désactivant quelques sites pour voir.

**Comment by Arias800** [comment]
oui la recherche non visuel . Je vais testé quelque chose je te tien aux courant

**Comment by nabsboss** [comment]
OK merci :)

**Comment by Arias800** [comment]
Je sais pas :/ faut attendre voir si quelque sait

**Comment by nabsboss** [comment]
Patience alors :) Merci beaucoup en tous cas ;)

**Comment by nabsboss** [comment]
Je confirme, j'ai tout désinstallé et mis la 0.5.2. La recherche visuelle fonctionne parfaitement et tout liens ZT sont présent. Aprés mise à jour en 0.5.8 + last ZT py, la recherche visuelle donne aucun résultat pour ZT.
Le problème vient bien de la mise à jour 0.5.8 !

**Comment by LordVenom** [comment]
Non le site à un soucis c'est résolut et en plus j'ai ajouté les qualités.

Pas encore en mise a jour. si quelqu'un test merci du retour :)

**Comment by Arias800** [comment]
Je confirme ca marche du coup j'ai compris mon erreur ^^

**Comment by nabsboss** [comment]
Impeccable, ça remarche avec la cerise sur le gateau :) Merci les pros ;)
