### ISSUE TITLE
Openload hoster is down.

### ISSUE THREAD

**Issue by NizarAloui** [Kodi-vStream/venom-xbmc-addons#1872]
I could not resolve any link from openload. I think the hoster is down.

Edit: do you speak French ? xD (pas d'anglais Merci)

**Comment by KujoWolfgang** [comment]
J'ai vérifié certain site web avec mon browser et openload semble en panne partout...

**Comment by johngf** [comment]
non il fonctionne sur le net mais ne fonctionnait plus sur vstream ton browser doit bloqué javascript

mise a jour sur la beta

**Comment by NizarAloui** [comment]
Merci ça refonctionne avec le dernier commit :)

**Comment by vic1997** [comment]
@NizarAloui Et pour information on parle principalement français ici 😄 , c'est un addon français

**Comment by Arias800** [comment]
@NizarAloui il le sait puisqu'il est déjà venu ^^

**Comment by NizarAloui** [comment]
@vic1997: oui tu as raison, a chaque fois j'oublie cette partie.
