### ISSUE TITLE
Vstream erreur kodi 18 Xbox one

### ISSUE THREAD

**Issue by jjey59** [Kodi-vStream/venom-xbmc-addons#1876]
Bonjour je rencontre un problème en essayant de lancé vstream dans kodi 18 alpha sur Xbox one .
Message : vstream error consulté le journal
La version de vstream installé est la 0.5.8
Error: xfile::cdirectory::getdirectory - error getting plugin://plugin.video.vstream/
Error: cguimediawindow::getdirectory(plugin://plugin.video.vstream/) failed

Je vois également juste au dessus de ces lignes des erreur python script.

Doit on attendre une mise à jour 
Ou auriez vous une manipulation pour installer correctement vstream sur la Xbox one. 

Merci

**Comment by Arias800** [comment]
L'appli kodi est en cours de développement sur xbox one  et il est précisé que certains module python et d'autre fonctionnalité (comme lecture de video depuis un périphérique externe) ne marcherons pas .

**Comment by LordVenom** [comment]
Ca m’étonnerais que ça fonctionne un jour, c'est très fermer comme system, deja qu'avec android c'est la merde alors la... bon j'ai vue arriver Kodi sur one je ferais quelque test l'année prochaine xD

**Comment by jjey59** [comment]
Merci à vous pour vos réponse j'espère que ce sera possible un jour ;)

**Comment by lebigboss** [comment]
On peut installer et lancer Exodus https://www.youtube.com/watch?v=OMVbZxxtcak

**Comment by Arias800** [comment]
Apparemment il faut un vpn et les film pour la majorité ne se lance donc pas stable @LordVenom a ton avis l'option upload log fonctionne sur xbox ?

**Comment by LordVenom** [comment]
J'ai toujours pas fait de test , je n'en sais rien du tout pour le moment.

**Comment by Arias800** [comment]
Essayé avec ce lien pour le repo :http://vstream.ga/repo/

**Comment by moha0075465** [comment]
merci j'ai essaye maintenant
mes même problème
​

2018-01-04 20:12 GMT+01:00 Arias800 <notifications@github.com>:

**Comment by Arias800** [comment]
Bon je pensait bien que ce ne fonctionnerai pas mais bon faillait testé ^^

**Comment by LordVenom** [comment]
https://paste.ubuntu.com/26325284/

Voila un log si quelqu'un a une idée.

**Comment by Arias800** [comment]
Regarde de 470 a 480 ça plante lors de `from ctypes import *` dans statistic.py donc essaye en faisant juste un `import ctypes`

**Comment by LordVenom** [comment]
je suis même pas sur que cette import soit utile.

**Comment by Arias800** [comment]
Teste sans pour voir car il y a que ça dans les log ^^

**Comment by LordVenom** [comment]
non y a plugin cache aussi a voir avec @TmpName  faut vraiment le virer il et utile que dans le téléchargement.

**Comment by Arias800** [comment]
Oui j'ai edite poste de toute a l'heure c'est pour ca que je disait qu'il y avais que ca comme erreur

**Comment by LordVenom** [comment]
bon comment mettre les changements sur la one je suppose que l'usb ne fonctionne pas. a j'ai une idée un zip via le site.

**Comment by LordVenom** [comment]
Ok ça tourne. 

Donc pour les xboxone
- Installer le repo via http://vstream.ga/repo/
- Installer l'addon via le zip plugin.video.vstream-0.5.8_just_xbox

si vous avez dejas installer vstream via le repo pas de soucis écraser simplement l'addon.

 "installer via un zip" source http://vsteam.ga/repo/ choisisser plugin.video.vstream-0.5.8_just_xbox.

**Comment by Arias800** [comment]
Donc c'était ctypes ou autre chose ?

**Comment by LordVenom** [comment]
juste ctypes est je sais pas a quoi c'est utilise, les stats on l'air de tourner encore donc...

**Comment by Arias800** [comment]
Bon bah ecoute tant mieux on attends d'autre retour avant de mettre en résolut ?

**Comment by LordVenom** [comment]
Ben j'ai gens qui l'install oui je vais pas faire beaucoup de test 2 vStream dans mon salon ça fait beaucoup et mon ordi de salon et mieux que la one xD

**Comment by Arias800** [comment]
Petit joueur j'ai 2 vstream donc un sous frodo avec la dessus 0.5.7 :p

**Comment by LordVenom** [comment]
Mais heu... j'ai un vStream sur l'ordi du bureau aussi que j'utilise pour le code uniquement. ça fait 3 j'ai gagnerrrrrrrrrr :) ha c'est ça les grosse stats xd

**Comment by Arias800** [comment]
j'en ai un sur mon téléphone aussi ça fait 3 après si tu veux je peux l'installez sur tout les ordi et téléphone de chez moi et on arrive a une dizaine de vstream minimum :p

**Comment by LordVenom** [comment]
Ok note a moi même faire un system pour autoriser 1 seul vstream par personne :)

**Comment by Arias800** [comment]
Ah mince alors ^^

**Comment by moha0075465** [comment]
j'ai Installer l'addon via le zip plugin.video.vstream-0.5.8_just_xbox
il marche très bien

**Comment by simolee19** [comment]
Salut l' Addon vstream plugin.video.vstream-0.5.8_just_xbox.marche nickel sur Xbox une s merci LordVenom et adryanlist peut le faire tourner sur v18 moi il marche très bien sûr mon portable en 17.4 y du sport à gaver

**Comment by lebigboss** [comment]
Merci les gars. Ça fonctionne nickel chez moi. A part ZT ou les liens ne s'ouvrent pas.
Mais c'est déjà pas mal.

**Comment by jjey59** [comment]
Merci c'est parfait tout est fonctionnel ;)
Par contre faut il retirer le repo vstream pour éviter une futur mise à jour ?
Et du coup est ce que les petites mise à jour disponible fonctionnent elles encore ?
En tout cas ce qui était loin d'être prévu au début de mon poste à été super rapide !!!
Merci à tous pour cet excellent travail

**Comment by Arias800** [comment]
non ne retire pas le repo car ça permets de mettre a jour vstream. Pour les mise a jour on ne peux pas savoir temps que personne n'en a effectué une

**Comment by jjey59** [comment]
Aucun problème je le laisse alors ;)
Merci encore pour votre travail

**Comment by Bouddha13** [comment]
Bonjour

Je viens de tester l instalation depuis le zip / vstream /plugin.video.vstream-0.5.8_just_xbox.zip

Une fois validé message d erreur :la dépendance de repository vstream 0.0.3 n a pu être satisfaite. 

J ai raté un truc ?

**Comment by LordVenom** [comment]
Bonjour, tu as louper une étape oui : https://vstream.ga/tutorial-installation/

**Comment by Bouddha13** [comment]
Résolu désolé

**Comment by stivxgamer** [comment]
Bonjour, question bête vous installez comment ces extensions ? 
vous mettez le zip sur clé usb et vous importez dans Kodi ? Exfat fat32 ?
merci

**Comment by daddysisi** [comment]
slt tout le monde apres avoir suivi l instalation pour xbox vstream aalais sans aucun souci il y a deux jour mais aujourd hui je lance vstream et boum error ...
je suis donc aller voir et il y a eu une mise a jour de 0.5.8 ces passer a 0.5.9
le souci ces que j ai desinstaler et voulu retelecharger via http://vstream.ge/repo
comme la premiere fois mais la le plug in just xbox a disparu 
plus moyen de le faire aller 
quelqun aurait il une idee ?
merci les gars

**Comment by sebdivx** [comment]
Bonsoir tout le monde même problème depuis la mise à jour en 0.5.9 et la 0.5.8 juste xbox n'est plus disponible.

**Comment by moha0075465** [comment]
meme probleme

2018-01-26 23:41 GMT+01:00 sebdivx <notifications@github.com>:

**Comment by cybertalis** [comment]
Idem pour moi . Il n y a plus le plugin juste Xbox et ça ne marche plus, depuis la mise à jour 0.5.9 alors que je l utilisé couramment depuis 20 jours...

**Comment by LordVenom** [comment]
Suject Fermer voir https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1921
