### ISSUE TITLE
version 0.5.8 erreur menu principal

### ISSUE THREAD

**Issue by manur20** [Kodi-vStream/venom-xbmc-addons#1877]
Bonne année à tous et Merci pour votre travail sur cet addon qui est vraiment top !!!
J'utilise Kodi 16.1 sur une RecalBox et vStream ne fonctionne plus sur mon raspberry avec la version 0.5.8.
Le requisotory est bien passé en version 0.0.3

Lorsque je lance vStream, je me retrouve sur un menu de lignes vide à la place du menu Recherche / Recherche visuelle / ... Les lignes du menu semblent présentes mais sans les libellés.
Lorsque je clique sur une ligne, j'ai l'erreur : "erreur vStream consulter le journal..."
En regardant dans les logs, il est indiqué des erreurs ligne 8 sur defaut.py et ligne 27 home.py

Merci d'avance de votre aide...

**Comment by LordVenom** [comment]
Bonne année a toi aussi.

La ligne 08 et 27 corresponde au class donc ça m'aide pas il faut le log complet.
Est tu en langue française sur ton Kodi ?

**Comment by Arias800** [comment]
Deja bonne année a vous 
Juste une question par rapport au menu principal c'est normale que "mise a jour disponible" soit en haut du menu et pas en bas comme d'habitude ?

**Comment by manur20** [comment]
Merci pour ta réponse.

J'ai bien Kodi en Français. J'utilise l'addon "Log Viewer for Kodi" pour visualiser les logs mais je n'ai pas accès au fichier texte pour copier-coller.
Je t'envoie des photos de l'écran pour que tu constates le texte complet de l'erreur.

![img_20180101_170714](https://user-images.githubusercontent.com/35001986/34469084-57d465b0-ef17-11e7-9139-37443e67f257.jpg)
![img_20180101_171227](https://user-images.githubusercontent.com/35001986/34469085-58154c92-ef17-11e7-9841-94f2f78fac8e.jpg)

**Comment by LordVenom** [comment]
Réinstaller au pire. Avec log viewer tu as une option upload log.

@Arias800 , Oui j'ai déplacer le menu trop de retour sur des gens qui ne font pas la mise a jour.

**Comment by TmpName** [comment]
J'ai pas encore installe la derniere version, donc j'ai rien teste encore, mais j'en profite juste pour vous souhaiter aussi une bonne année, avec le reste et toussa et toussa.

**Comment by johngf** [comment]
une bonne année a tous aussi .
pour le probléme de @manur20 tu as un argument de vide quelque part je pencherai une erreur de chemin
mais on voit pas grand chose sur ton log

**Comment by Arias800** [comment]
D'accord @LordVenom  c'est juste que la 1er fois ça fait bizarre

**Comment by manur20** [comment]
J'ai réinstallé vStream (desinstaller / installer) mais le problème perdure.
Je n'ai pas la possibilité de saisir un texte de recherche, l'erreur survient directement.
J'essaye dès que possible de vous communiquer le log complet...
