### ISSUE TITLE
Problème avec Kodi et vstream

### ISSUE THREAD

**Issue by driteur** [Kodi-vStream/venom-xbmc-addons#1880]
Bonsoir à tous,

Depuis quelques jours je rencontre le même problème avec Kodi 17.3 et vstream 0.5.8, à savoir que je configure Kodi en français, j'installe l'extension vstream, j'arrive à l'utiliser toute une soirée et le lendemain je retrouve un Kodi sans aucune extension et de nouveau en anglais exactement comme ci il  avait été réinitialisé ... 
Quelqu'un a une idée du problème et surtout de comment le résoudre ??

Je suis sous Windows 10 Fall Creators Update et je ne rencontre pas de problème avec les autres programmes.

**Comment by Arias800** [comment]
Essaye kodi 17.6 c'est (d’après la team de kodi) la dernière version 17.x avant kodi 18 et chez moi ça marche bien

**Comment by driteur** [comment]
Merci pour ta réponse, mais c’est bien la version 17.6 de kodi que j’utilisais et non la 17.3.

**Comment by Arias800** [comment]
Tu a un accents quelque part dans le chemins d’accès ?

**Comment by driteur** [comment]
Non il n'y a pas d'accents dans le chemin d'accès. 
le voici :   

C:\Program Files (x86)\Kodi\kodi.exe

**Comment by TmpName** [comment]
Regarde dans "\userdata\profiles" c'est la que sont les fichiers de config de kodi.
Regarde avant de lancer kodi, pendant le lancement de kodi et apres la fermeture de kodi pour reperer si les fichiers sont supprimes a un moment.

**Comment by driteur** [comment]
Effectivement le problème venait de l’antirirus Avira qui supprimait un fichier de configuration  à l’utilisation de l’extension sportdevil

**Comment by driteur** [comment]
Merci pour vos réponses
