### ISSUE TITLE
Sous Titres films et séries

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#1882]
Bonjour a tous , tous mes meilleurs vœux pour l'année 2018 .
Quel est le meilleur plugin pour les sous titres , des films et séries ?

**Comment by LordVenom** [comment]
opensubtitles.org mais inscription obligatoire.

**Comment by Arias800** [comment]
Apparement il y a un addon pour utilisé addic7ed mais je n'ai l'ai pas testé https://github.com/Amelandbor/service.subtitles.addic7ed

**Comment by ktm520** [comment]
Bonjour , merci  pour vos réponses , perso j'ai opté pour opensubtitles.org , vous pouvez clore le sujet .

**Comment by Arias800** [comment]
Tu sais que tu peux toi aussi clore le sujet car tu en ai le créateur ^^

**Comment by ktm520** [comment]
Désolé , je ne sais pas comment faire , donné moi la manip a faire .

**Comment by Arias800** [comment]
A coté de comment tu a reopen and comment vu que je l'ai déjà fermé mais sinon tu a close and comment ^^
