### ISSUE TITLE
Uptobox vs Uptostream

### ISSUE THREAD

**Issue by fredkerm** [Kodi-vStream/venom-xbmc-addons#1884]
Bonjour,

Tout d'abord merci pour le super boulot.
J'ai remarqué que sur un lien Uptobox si l'on choisit téléchargement direct ou streaming, l'authentification premium se fait correctement. Mais s'il s'agit d'un lien Uptostream j'ai l'impression que l'authentification ne se fait pas. D'autres personnes ont constaté la même chose ?

J'en profite pour poser une autre question, il me semble que l'option SSL n'est pas gérée par Vstream. C'est une évolution prévue ou pas du tout ?

Merci

**Comment by Arias800** [comment]
De mémoire l'authentification est fait sur le fichier d'uptobox et c'est après avoir récupéré le liens pour uptostream que l'on lance uptostream donc si l'authentification marche sur uptobox elle devrait marche sur uptostream. En ce qui concerne le SSL je crois que c'est kodi qui le gère depuis la version 17

**Comment by TmpName** [comment]
Yep, exactement SSL depuis V17.
Et non l'authentification n'est pas geree sur uptstream. En fait a l'origine il n'y avait pas d'authentification pour les hebergeur, on y a ete force pr uptobx mais jamais mit en place pr uptostrm.

Je pense qu'on peut le mettre en place. C'est les meme identifiant pour les deux ? Ca donne uptostrm en illlimite ?

**Comment by fredkerm** [comment]
Merci pour vos réponses rapides !
Oui il s'agit du même compte, je pense qu'il n'y a que le nom de domaine qui change.
Pour le SSL je vais essayer ça :)

**Comment by TmpName** [comment]
Heu sinon j'ai un petirt probleme, j'ai voulu retester uptostrm sur navigateur et
1 - Ca m'a demande un captcha pour m'authentifier.
2 - Ca affiche un petit lecteur vide et la video ne marche pas.

**Comment by fredkerm** [comment]
Je viens de tester je n'ai pas eu de demande de captcha

Par exemple : https://uptostream.com/x7ivdxstgd4r

**Comment by Arias800** [comment]
Mais c'est recaptcha :c si il y a un captcha regarde en bas a droite de la page de connection il y a le logo

**Comment by TmpName** [comment]
Yep, et en plus ca deconne si on a un anti pub.
J'espere qu'il me l'a propose car je me sert jamais de mon compte, car sinon c'est une belle source d 'emmerdes.
Et ca marche sinon chez vous up2strm ?

**Comment by Arias800** [comment]
oui ca marche chez malgré mon débit internet x)
