### ISSUE TITLE
Son sur androidbox tronsmart

### ISSUE THREAD

**Issue by tronsmartbox** [Kodi-vStream/venom-xbmc-addons#1887]
Bonjour,
Je sort le son des films en passthrough (HDMI) sur ampli 5.1
Tout fonctionnait bien même KODI+Plex AddOn ou KODI direct
Mais je n'ai aucun son avec VStream AddOn ...
J'ai essayé plusieurs films sans succès.
Dans les options, je n'ai pas le choix dans la sortie audio : android audiotrack
Ou est ce que ça coince ?
Merci.

**Comment by vic1997** [comment]
Sur des films qui ne sont pas sur vStream ça marche ? Sans rien toucher au paramètres ?

**Comment by Arias800** [comment]
Dans le option de son quand un film est lancé tu a bien mit HDMI comme sortit son ?

**Comment by tronsmartbox** [comment]
sur des films qui ne sont pas sur vStream ça fonctionne très bien.

Je n'ai pas le choix dans les option du son dans un film ... android audiotrack
Et c'est d'ailleurs le point sur lequel je bloque
Je vais essayer de trouver cette sortie et s'il y a du son je saurais d'ou ça vient
Mais comment forcer la sortie son en passthrough HDMI ?

**Comment by tronsmartbox** [comment]
autre info, j'ai essayé les mêmes films et la même configs (kodi+vstream) sur windows et ça fonctionne
parce qu'effectivement je peux choisir dans les options la sortie audio
sur androidbox pas moyen

**Comment by Arias800** [comment]
Je sais pas je peux pas t'aidé je sais pas comment marche une box android :/

**Comment by vic1997** [comment]
@tronsmartbox Est ce que sur le PC tu es à la même version de Kodi que sur l'android box ?
