### ISSUE TITLE
Bug marquer comme vu/non vu avec trakt.tv

### ISSUE THREAD

**Issue by dbuteau** [Kodi-vStream/venom-xbmc-addons#1888]
J'ai remarqué un bug avec l'addon trakt.tv(je ne sais pas si ca se reproduit avec des vus autres que trakt.tv).
Quand on est sur la page présentant la liste des films (ou les séries) provenant de trak.tv, ca peut être la watchlist, les recommandés,les populaires etc...

Si on ouvre le menu contextuel sur une des occurrences (par ex le film deadpool) et que l'on sélectionne "marquer comme vu/non vu" ca marque comme vu tous les films (ou séries) de la page

Et si on clic sur l’occurrence pour entrer dans la vue des stream disponibles parmi les sources, et que là on sélectionne une des occurrences pour marquer comme vu, là ça ne marque comme vu que et uniquement le stream sélectionné

Cela devrait être dans le sens contraire, marquer tous les streams comme vu (quelque soit le site source), pour marquer le film (niveau hiérarchique supérieur) comme vu. Ou bien sur la page de listing des films/séries pouvoir marquer uniquement l’occurrence sélectionné comme vu, pas toutes les occurrences...

**Comment by LordVenom** [comment]
Merci je vais regarder ça.

**Comment by LordVenom** [comment]
C'est résolut pour trakt bien que marquer vue c'est pas la même chose que noter comme regarder dans la menu trakt. L'un est visuel l'autre ajoute comme regardé dans trakt. 
J'utilise pas asser trakt pour l’implanter dans le core de vStream.
Pour la recherche "c'est normal" pour le moment je l'aisse comme ça.

**Comment by dbuteau** [comment]
Pardon @LordVenom en lisant ta réponse je me rend compte que je me suis mal exprimé.

En fait quand j'ouvrais le menu contextuel, j'avais 2 occurrences qui apparaissaient;
- "marquer comme vu/non vu"
- "marquer comme vu/non vu dans trakt"

Je parlais de la première occurrence qui était "vu" au sens xbmc/kodi (que j'ai put rattraper en vidant la BDD kodi),  la seconde je ne l'ai même pas testé parce que je crois que de souvenir l'option était grisé (désolé si je me trompe je dis cela de souvenir)
Mais si tu as réussi a réunir les 2 options en une seule c'est cool 😄 

**Concernant les différences de notions entre regardé et vu** 
**TL;DR**
je peux t'expliquer l'utilisant intensément et ayant un peu étudié l'api de trakt.tv
En fait [dans l'API](https://trakt.docs.apiary.io/#) ce qu'ils appellent: 
- Watching: c'est relié aux "checkin" manuel ou au "scrobble" automatique, qui permet de signaler qu'on est là maintenant tout de suite en train de le regarder, et qu'on a pas fini de le regarder. Si on commence de regarder une vidéo et qu'on interrompt la lecture pour faire autre chose, la vidéo reste marqué en "watching".
- Watched: là c'est le bon terme pour dire que l'épisode a été réellement vu jusqu'au bout (ou plutôt à plus de ~80%), quand ce status est appliqué il remplace le status "Watching" automatiquement

**En Details**
Donc théoriquement, dans l'idéal en fait:
- quand je lance la vidéo une requete scrobble/start devrait être envoyé avec un progress=0%, ca passe la vidéo en "watching"
- si je met en pause une requete scrobble/pause avec le % de progress est envoyé trakt laisse la vidéo en "watching" et conserve l'endroit ou il en était
- je relance la vidéo c'est une requete scrobble/start à nouveau
- je stop la vidéo requete scrobble/stop avec le pourcentage de progression, si le %<80% alors ca reste en watching, si le % de progression est >80% alors ca passe la vidéo en watched

Bon là c'est pour de la gestion automatique, et je sais pas si c'est possible de récupérer la progression des streaming, donc pour marquer comme vu une vidéo manuellement dans traktv, je pense que logiquement tu envoie une requete scrobble/stop avec un progress a 100% et trakt s'occupe de gérer le reste 😄 

Je pense que les requetes API de type:
- users/id/watched/type (watched): ne sert qu'a lister les vidéos marqués comme déjà vu et a le synchroniser dans la bdd kodi pour flager le film ou l'épisode avec une icône vu
- users/id/watching (watching): ne sert qu'a lister les vidéos en cours de visionnage et qui n'ont pas été vue en entier (et donc afficher l'icone a moitié remplie)

Voilà désolé pour ce commentaire très long, mais j'espère que cela t'aidera a mieux comprendre la logique de trakt.tv et pourra peut être t'éviter de perdre de longues heures, j'ai étudié la doc de l'api pensant te filer un coup de main pour améliorer le plugin, mais là je bosse sur un autre plugins déjà (de gestion automatisé des m3u et epg via l'api freeboxtv pour les PVR) 😄 
Mais si tu as des questions n'hésite pas ;)

**Comment by LordVenom** [comment]
Le core de vStream la lecture, le marquer lus n'est pas associer a Track 
Tout est possible mais il faut le coder et c'est pas fait.

Donc la si tu lis un film que tu veut que track le sache il faudras allais dans le menu track et le marquer lu 
Le menu track réunis c'est option :

https://api.trakt.tv/sync/collection
https://api.trakt.tv/sync/collection/remove
https://api.trakt.tv/sync/watchlist
 https://api.trakt.tv/sync/watchlist/remove
 https://api.trakt.tv/sync/history
https://api.trakt.tv/sync/history/remove

Ceux qu'il faut comprendre qui et le plus dire a gère avec vStream et pas avec les autres addon c'est que l'on peux utiliser vStream sans métadonner et sans métadonner pas d'id pour marquer lus/ect.. dans trakt. A chaque lecture/reprise il faudrait le chercher et tous ça pour ne même pas afficher les infos juste pour relancer une requête a trakt et le marquer lus (ceux qui est fait pour ajouter à la collection ect.. mais ont le fait qu'a la demande.

Dans le menu Home/Track nous sommes obliger de forcer les metas justement a cause de ce soucis.
donc de la je suppose qu'il seras possible d'afficher l'icone marque lus au lieu d'un menu regarde.

Note : C'est bizarre de faire 2 requette json 1 pour la collection l'autre pour voir ceux qui et lus !!! merci la bande passante. il suffisait de mettre un champ vue dans leur api j'ose même pas regarder quand je voie ceux qu'il ont fait avec leur navigation j'ai peur.
Ben si c'est ça une boucle pour la collection et une  requete a chaque boucle pour voir si y a un nombre de lecture pas top autant un menu regarder c'est Kif Kif.

**Comment by dbuteau** [comment]
> Note : C'est bizarre de faire 2 requette json 1 pour la collection l'autre pour voir ceux qui et lus !!! merci la bande passante. il suffisait de mettre un champ vue dans leur api.

C'est exactement la réflexion que je m'étais fait à la lecture de cette API X-D
