### ISSUE TITLE
Changement de nom du film

### ISSUE THREAD

**Issue by vic1997** [Kodi-vStream/venom-xbmc-addons#1892]
Bonjour,
Je suis toujours actuellement en train de travailler sur mon système de streaming via le compte UpToBox, et j'aurais quelques petites questions aux développeurs vu que j'ai quelques problèmes.

Je parle donc essentiellement de la source VotreCompteUptobox.

Premièrement, j'aimerais savoir pourquoi les noms des films se termine par un "Uptobox" d'une couleur rose et dans quel partie du code c'est insérer (je ne l'ai pas trouvé dans le fichier siteuptobox.py).

Deuxièmement, j'aimerais savoir pourquoi les noms des films sont changé, avez vous créé un système qui le fait tout seul ? Avec un autre plugin les noms des fichiers restent les mêmes que sur le site uptobox, mais là vstream les change, pourquoi ?

Voici un screen, le dossier de gauche est l'autre plugin, le dossier de droite c'est le dossier de vstream : https://i.imgur.com/pq5pYk6.png

Et là le dossier vstream comparé au dossier directement sur uptobox : https://i.imgur.com/brC57Qv.png

On voit bien que vStream change le nom du film.
Pouvez vous m'expliquer ? Et me renseigné sur le fichier qui fait ça ? Merci

Je cherche cela car ça rend les noms des films invalide pour le scraper, du coup, ça ne marche pas avec vStream ! Si on pourrait régler ça je pense que j'en aurais finis. 

Merci pour vos futur réponses !

**Comment by TmpName** [comment]
Je ne me suis jamais servi de ce fichier site donc je peux me tromper mais : 
1 - Pour ce que je vois le site VotreCompteUptobox ne créé pas de fichier sur le disque dur.
2- Les noms affiches n'ont rien a voir avec le nom reel du film, kodi a une variable pour le nom du film et une autre pour le titre a afficher, up2bx par exemple n'est jamais dans les titres.

**Comment by vic1997** [comment]
@TmpName Oui oui, c'est un nom qui est récupéré, il n'y a aucun fichier (quand on clique dessus ça ouvre le film en streaming).
Et justement c'est ça le problème, que sur vStream, le nom du film (ou titre comme vous voulez) n'est pas le même que sur UpToBox, ce qui fait que le scraper ne comprend pas. C'est pas possible d'enlever cette partie du code qui modifie le nom ?

Parce qu'avec un autre addon qui lui ne modifie pas les noms, tout marche, mais ça serait bien que vStream y arrive.

**Comment by TmpName** [comment]
Fichier guiElement.py, il repere les date entre caracteres speciaux et dans ton cas c'est le "." qui pose probleme, suffit de remplacer tout les . par des espaces avant l'affichage dans le fichier site pour eviter ca (traitemant par la fonction TraiteTitre())

**Comment by vic1997** [comment]
@TmpName Super merci pour l'aide ! (je cherche depuis ce matin)
Je vais essayer et je te dis si j'y arrive.
Sinon tu penses qu'un système qui le désactive pour la source VotreCompteUptobox c'est possible ?
Soit un truc à cocher dans les paramètres soit définitivement.

Sinon j'ai encore une question, le Uptobox en rose à la fin je crois pas qu'il est rajouté avec guiElement, est-ce que tu saurais où ?

**Comment by LordVenom** [comment]
Perso je voie que des addDir ça cherchera pas les metas.

**Comment by vic1997** [comment]
@LordVenom Désolé mais je n'ai pas compris ton message, peux tu être plus clair s'il te plait ? Je te remercie d'avance.

**Comment by TmpName** [comment]
Te pre-occupe pas de la partie en rose, je te repete que Vstream fonctionne avec un titre de film et un titre affiché, la partie en rose est ignorée.
Sinon oui le plus simple pour toi et de modifier le fichier site en remplacant les point par des espaces, du coup le titre sera toujours modifie mais au lieu d'avoir "DarkwebTRUFRENC" tu auras "Darkweb TRUEFRNCH" et ca ne genera plus le scraper.

**Comment by vic1997** [comment]
@TmpName Justement, chez moi si, j'utilise OSMOSIS et lui capte le Uptobox en rose, ce qui fait que dans le titre du film il y a "[COLOR rose] titre [/COLOR]" et ça empêche le scraper de fonctionner !! C'est justement l'inverse de ce que tu dis, chez moi ça marche si je désactive le changement de nom. Le scraper comprends Darkweb.MULTI mais pas DarkwebMULTI (ce que donne vStream). Après désactivation de la modification du titre et de la date ça marche !
Le scraper fonctionne.
Le uptobox rose gêne quand même dans le titre mais le scraper arrive quand même à trouver le film (donc c'est pas trop gênant une fois le film analysé et dans la médiathèque).

Par contre ça va être chiant, à chaque mise à jour il va falloir re-modifier ce fichier.

**Sinon, la fonctionnalité ultime que vous pourriez faire (si vous avez envie, en tout cas ça serait pour moi la meilleure des choses), c'est de pouvoir ajouter un dossier entier à la librairie (j'ajoute mon dossier film de UpToBox), tous mes films sont donc ajouté en .strm + ajouter une fonctionnalité de mise à jour automatique (au lancement, toutes les X heures ou manuellement) de ce dossier dans la librairie (au cas où j'ajoute un film sur uptobox).**

Voilà ce que j'en pense, en tout cas merci pour l'aide !

**Comment by LordVenom** [comment]
On parle bien de la rubrique moncompte upto sur vStream avec le scraper auto de vStream "activer les metadonner" dans les préférence de vStream ? donc ça ne cherche pas difficile de dire çi le titre l'empeche de trouver puisque pas de recherche c'est pas coder pour.

**Comment by LordVenom** [comment]
J'ai pas lus ça dans ton messages et tu sais ceux que je vais dire sur OSMOSIS (connais pas, j'installerais pas pour tester) xD et pour la médiathèque je sais pas faudrait tester, je vais regarde un truc bouge po.

**Comment by vic1997** [comment]
@LordVenom oui j'ai oublié de préciser le nom de l'affrontement.
En gros je me sers de vStream pour accéder à uptobox.
Et je me sers de osmosis pour qu'il crée des liens de streaming vers les films de mon compte, dans la médiathèque.

Si vstream tout seul pourrait faire ça ça serait énorme.

**Comment by LordVenom** [comment]
Ok c'est bien ceux que je pensé quand tu ajoute à la librairie il te demande le nom donc rien ne l’empêche de trouver le bon film, bon la j'ai tester upto depuis la librairie ont peux pas le lire ça fonctionne avec les autres host ça doit être un bug mineur a voir. Mais l'ajout a la librairie pas de soucis c'est pas automatique et je trouve ça moins pratique que les metas direct mais bon.

**Comment by LordVenom** [comment]
Et je me sers de osmosis pour qu'il crée des liens de streaming vers les films de mon compte, dans la médiathèque. Hum... Comme dirais jack Sparrow (ceux que tu dis n'a aucun sens) xD

**Comment by vic1997** [comment]
En gros faudrait pouvoir ajouter un dossier à la librairie, car là on peut juste ajouter des fichiers un par un.

**Comment by LordVenom** [comment]
Hum un code quoi scan tous ton dossier pour créer ensuite des .stmr si pas irréalisable mais c'est pas pour une utilisation global. Moi je retient que les metas marche pas sur moncompteupto pour le reste je pose mon Veto.

Fait tes propres .stmr ça seras peux etre plus simple. Ensuite le scraper suivant les titres feras le job.

Exemple:
AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\Films Si tu met un stmr nommer avatar.stmr que tu vas dans vStream/librairie que tu fait la mise a jour op avatar dans ta librairie.
Pour les bon lien ect je te l'aisse ouvrir un .stmr y a pas beaucoup d'info dedans.

**Comment by vic1997** [comment]
@LordVenom Justement, l'addon OSMOSIS permet de créer des fichier .stmr en utilisant la section VotreCompteUptobox de vStream. (Osmosis peut parcourir les autres addons !)

Ce qui fait que je peux avoir des fichier .strm et donc les avoir dans ma médiathèque facilement avec des mises à jour automatique.

vStream permet aussi de le faire mais il faut tout faire à la main, film par film (fichier par fichier) et moi j'ai + de 200 films donc ça serait long.

**Comment by TmpName** [comment]
Non regardes mieux les exemple que je te donne, Il y a un espace.
Ce n'est pas Darkweb.MULTI qui va donner DarkwebMULTI
Mais Darkweb.MULTI qui devient  Darkweb MULTI.
Si le scrapper gere le 1080p TRUEFR www zone et ect ... c'est pas "uptobx" qui va le gener. Le plus important c'est l espace.

**Comment by vic1997** [comment]
@TmpName Oui, c'est ce que j'ai compris. Mais non chez moi ça donne bien DarkwebMULTI, as-tu vérifié ? C'est peut-être une erreur ?

**Comment by johngf** [comment]
J'ai le code pour renommer ou supprimer un fichier ou dossier  sur son compte depuis vstream
Mais jamais mis en place.
Pour les métas le soucis c'est l'impossibilité de savoir si film ou série 
sur les autres sites le tri est fait avant par le site donc abandonner

**Comment by TmpName** [comment]
Non je te donne la solution, c'est a toi de mettre cette ligne dans le fichier site.
Si tu remplace les "." par des espaces avant la convertion tu n'auras pas ce probleme. Apres ca ne derange que si on utilise Osmosis donc je vais pas le mettre en systematique dans le code.

**Comment by vic1997** [comment]
@TmpName Bref, c'est résolu (y a juste le [COLOR]Uptobox.... ) à la fin mais ça gêne pas le scraper). Mais j'utilise Osmosis parce que vStream ne permet pas de faire ça, sinon j'utiliserais seulement vStream.
