### ISSUE TITLE
Proposition de 2 sites (sources) de streaming

### ISSUE THREAD

**Issue by Massancha** [Kodi-vStream/venom-xbmc-addons#1893]
Bonjour a vous,

Merci pour cette super application! Ca marche du tonnerre ! Pour un petit peu contribuer (je ne sais pas si ça peut vous aider mais j'ai vu des sites de streaming en source) j'ai 2 sites a vous proposer hds.to/ et dpstream.net (est-il down ?) encore merci a vous pour ce super add-on

**Comment by vic1997** [comment]
Salut, il y a un sujet pour ça ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/517

Mais merci quand même.

**Comment by Massancha** [comment]
Désolé merci d'en avoir tenu compte. Hds est très complet avec bcp de film en hd. Par hasard, vous connaissez pas une communauté française sur Kodi? Je voudrais me renseigner pour l iptv, il y a une chaîne que je n'arrive pas à trouver ^^

**Comment by vic1997** [comment]
@Massancha J'ai jamais trouvé de vrai forum pour la communauté française, c'est pour ça que je me débrouille tout seul voir exceptionnellement je viens parfois demander ici, même si c'est pas l'idéal vu que ça ne les concerne pas.

**Comment by Massancha** [comment]
C'est vraiment dommage de ne pas avoir de communauté.. Ça aiderais vachement bien !! merci d'avoir pris du temps pour me répondre, bonne soirée

**Comment by Arias800** [comment]
Hds n'est pas privé il bloque juste des IP de manière aléatoire et il est déjà dans vstream c est Kaydo

**Comment by vic1997** [comment]
@Arias800 perso je tombe sur une page de connexion sans possibilité d'inscription.

Sinon oui je pense qu'il faudrait faire un site et un forum pour vStream et la communauté française de Kodi.
J'ai vu que @LordVenom a déjà fait un site il y a peu de temps.
Je me propose pour faire un site propre et un forum si vous voulez.

**Comment by LordVenom** [comment]
Effectivement y a un site et un forum en création mais j'ai pas fait de projet pour ce projet. xD

**Comment by Arias800** [comment]
@vic1997 C est justement ce qui ce passe si tu est bloqué

**Comment by vic1997** [comment]
@LordVenom Haha, ok, n'hésite pas à me demander si tu as besoin d'aide (je travail là dedans) et pareil si tu veux faire un repo.

@Arias800 Ok, bizarre, pourtant je suis jamais allé sur leur site, leur système est très bizarre 😄

**Comment by vic1997** [comment]
@Massancha @LordVenom Re, bah du coup j'ai fais un forum, c'est pas spécialement pour vStream, c'est pour toute la communauté française de Kodi, on peut parler des problèmes, des addons et de toutes les autres choses qui concernent Kodi ! Ça permettra de réunir la communauté française vu que personne ne l'a fais pour l'instant.
Je vous invite donc à vous y inscrire !

**Comment by Massancha** [comment]
Magnifique ! Je viens de m'inscrire. A plus sur le forum Et bonne journée ☺

**Comment by TmpName** [comment]
Pour info si Vstream est toujours la apres tant de temps, c'est pour plusieurs raisons, et l'une d'entre elle c'est sa discretion, donc un forum sur Vstream ...
Sinon en commanute Fr je connais
h ttp://www.dzsat.org/forum/
htt ps://forum.mpdb.tv/index.php#c5
htt ps://plus.google.com/communities/109513844750693990070

**Comment by Massancha** [comment]
@TmpName c'est pas sur Vstream c'est pour la communauté française de kodi, référencer les addons en fr, sous titres fr entre autres..

**Comment by vic1997** [comment]
@TmpName Oui, le forum que j'ai créé est sur la communauté FR pas spécialement sur Kodi, même si j'ai fais un sous-forum pour lui. De plus je trouve que justement, se cacher comme ça ne sert à rien, ça montre justement qu'ils ont raison (l'état et hadopi) alors qu'en réalité vStream n'a rien d'illégal. Et un forum serait tellement utile parce que niveau organisation... C'est pas du tout le top avec les issues sur github.

Après LordVenom veut faire un forum spécialement sur vStream, il a mon encouragement en tout cas.

**Comment by Arias800** [comment]
Hadopi ne coïncidèrent pas vstream comme illégal car on récupère juste des info sur des site (faut que je retrouve l article ou j ai vu ça mais je suis sur a 100% qu'il l'on dit ) ^^

**Comment by vic1997** [comment]
@Arias800 Bah oui, vStream récupère que les liens des hébergeurs, celui qui est en tord est l'hébergeur. Et EN PLUS hadopi ne surveille que le réseau torrent, donc les téléchargements direct y a pas de soucis !!! 😄

**Comment by Arias800** [comment]
Le seul problème c est les ayant droit qui du peuvent faire pressions ^^

**Comment by LordVenom** [comment]
J'ai pas d'idée encore pour le site mais les issues de github même si des fois limiter sont plaisante à utiliser.
La il me fallais juste un Repo aprés j'aimais pas le vide alors j'ai remplis pour l'instant ça reste comme ça jusqu’à l'illumination xD.

Note : je vais devoir supprimer le hors sujet j'aime pas trop voir ça ici.
