### ISSUE TITLE
Hoster et site 

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#1896]
Hello @TmpName ,

juste pour te prévenir que openl... ne fonctionne plus et streamingk.com non plus.
j'ai vérifié en béta si c'était corrigé en attendant la maj mais non.

Bonne année à tous !

**Comment by TmpName** [comment]
Test de openlad avec cette version https://github.com/Kodi-vStream/venom-xbmc-addons/edit/Beta/plugin.video.vstream/resources/hosters/openload.py ok chez moi.

**Comment by ttrd06** [comment]
testé aussi et ok pour moi. Et pour le site streamingk tu es dessus? 
merci

**Comment by TmpName** [comment]
Reteste la version beta modifie hier, ca a marche pr moi.

**Comment by ttrd06** [comment]
ok c'est tout bon merci !

**Comment by Tedok** [comment]
Bonjour, 
Chez moi aussi tout est revenu à la normale sur les liens openload Avec la dernière version bêta.
