### ISSUE TITLE
Nouvelle rubrique dans marques pages

### ISSUE THREAD

**Issue by fredo04** [Kodi-vStream/venom-xbmc-addons#1899]
Bonjour et encore merci pour votre super boulot.
Je me sers beaucoup du marque page.
Est il possible lorsque on met un film en marque page de créer et choisir sa rubrique.
Par exemple si c'est un film pour moi ou pour ma femme ou pour les enfants de créer et choisir ces rubriques au moment de mettre en marque page.

**Comment by LordVenom** [comment]
J'avais tenter un truc du genre mais ça m'avais gonfler, je l'aisse l'idée en attente mais a mon avis c'est pas pour tout de suite.

**Comment by fredo04** [comment]
slt lordvenom.
a dommage, toute la famille se sert de ton addon (boitier android) et du coup je me retrouve avec une vingtaine de films tout mélangés dans le marque page. ça aurait permis de faire du rangement.
Si tu as une solution équivalente je suis preneur.

**Comment by Arias800** [comment]
@LordVenom au pire tu peux faire en sorte de faire apparaître une boite de dialogue demandant si il veut changer le nom lors de l'ajout ou une option pour changé de nom unnmatque page existant. C'est peut être plus simple non?

**Comment by LordVenom** [comment]
Ben non puisqu'il demande des rubrique la meilleur solution c'est de faire une BDD et un nouveaux champ dans celle des marques page pour associer le tout, puis faire un system de gestion pour changer les noms est les catégories oui sans catégorie pas de meta.

**Comment by vic1997** [comment]
Sinon il peut créer des profils sur kodi je crois, un pour les enfants, l'autre pour lui...

**Comment by fredo04** [comment]
Des profils ça serait pas mal et surtout dans mes cordes.

**Comment by vic1997** [comment]
@fredo04 C'est déjà disponible de base sur Kodi ! C'est comme des comptes Windows/Linux/Netflix... chacun a ses propres vidéos, films, photos, musique... Donc tu pourrais en faire un pour toi, un pour ta femme, un pour tes enfants (voir un faire un pour chaque enfant s'ils ne regardent pas la même chose) ! C'est super efficace, par contre je ne sais pas si tu dois réinstaller les addons pour chaque profil étant donné que je n'ai jamais testé.
Pour l'interface de kodi 16.1 c'est ici : [https://i.imgur.com/dHMJ5fA.jpg](https://i.imgur.com/dHMJ5fA.jpg)
Pour la dernière version ça doit également être dans les options.
