### ISSUE TITLE
Vos installation

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#190]
Bonjour, juste pour savoir sur quoi vous faite tourner vStream.
- PC acer win7 - kodi 14.2
- Xtreamer ultra : http://www.xtreamer.net/ultra/  - Openelec - http://openelec.tv/

**Comment by TmpName** [comment]
Une Gigabyte Brix GB-BXBT-2807 avec Win7 kodi 14.2

**Comment by mino60** [comment]
Moi PC DELL 3010 core i3 Win7 kodi 14.2 Helix.

**Comment by arzaz** [comment]
Prismcube ruby: http://www.prismcube.com/

**Comment by poto25** [comment]
Freebox mini 4k kodi 14.2

**Comment by venon45** [comment]
Bonjour je suis sur raspberry 2 et Lodi 14.2 ca fonctionne très bien..
Bonne journée

**Comment by richarback** [comment]
Désoler du retard
androidtv.4.2 et je veux mettre sur windows 10

**Comment by SuN969** [comment]
Raspberry 2
Openelec 5.0.8

Stable jusqu'à chaque mise à jour! 😁

**Comment by X-ardion** [comment]
Installé sur android Box 4.4.2.
Raspberry 1 B
Raspberry 1 B+
Raspberry 2 B (OpenElec 6.03)
Raspberry 3 B
Tout fonctionne correctement.

**Comment by lilou34** [comment]
Bonjour à tous moi je suis sur un mxq et c'est top. Merci lordvenom pour ton boulot

**Comment by johngf** [comment]
intel nuc DN2820FYKH
archlinux
xbmc standalone

**Comment by darky78** [comment]
BBox Miami pour moi (Bouygues), ça marche nickel!

**Comment by yamoky** [comment]
Mon pc gaming pour le moment 
Carte mère: asus maximus héros 7 (ROG)
Processeur: i7 (je ne sais plus les numéros lol) 
Carte graphique: asus strix 980 4go 
Ram: 16 go 
Ssd 500go plus 3 tera 
Windows 10 

Je passe par de la fibre optique pour le son 

Mais ça c'est pour le moment. 
Je pense me faire un serveur de fichier Red 
Avec 10 disque dur de 3 To (c'est pas pour de suite lol) 

Je ne sais pas encore quoi prendre pour juste utiliser kodi sur ma télévision car il faut que je puisse passé en fibre optique sans que ça me coûte un bras 🙋

**Comment by gralex68** [comment]
Hello,
TX8 Android 6 (kodi 17 beta)
Lifetab Android 4.4 sous kodi 5.2 et embc
Pc
@+
