### ISSUE TITLE
Kaydo: Séries E01 VF manquante et affichage du titre d'un épisode.

### ISSUE THREAD

**Issue by KujoWolfgang** [Kodi-vStream/venom-xbmc-addons#1902]
Bonjour,  Un gros merci pour Vstream. j'utilise beaucoup la source Kaydo pour les séries VF. 

J'aimerais apporté a votre attention deux petits problème

Problème 1:
Présentement chaque saison , peut importe la séries il manque l'épisode 1 VF.
J'ai apporté la modification suivante a la ligne 331 de mon fichier kaydo.py

oRequestHandler = cRequestHandler(sUrl + '?ep=0')

Suite a cette modification j’obtiens l'épisode 1 VF de chaque séries / saisons

Problème 2:
Il y a un petit bug d'affichage du titre de l'épisode.

le titre devrais ressembler à quelque chose du genre:
E01 : Sur le ring 

présentement on obtient le titre suivant.
E01 : Sur le ring <script>if (lastep == '1') .....etc (la string est longue.)

une modification de la ligne 341 regle le problème d'affichage du titre
sPattern = '<div class="truncate.+?</i>(.+?)<script>(.+?)</li>'

Merci

KujoWolfgang

**Comment by KujoWolfgang** [comment]
Bonjour. J'aimerais valider si ses ok de participer et aider a la résolution de problème, J'ai appliqué deux petit fix sur le fichier kaydo.py dans la section beta (ligne 331 & 341)

Est-ce que j'utilise la bonne méthode? Est-ce que les modification proposé cause un souci ailleurs dans Kaydo. Cette issue a été fermé sans commentaire de votre part.

En ce qui me concern présentement j'ai manuellement modifié mon kaydo.py et tout fonctionne bien pour moi.  Prévoyez vous déployer cette solution dans la prochaines mise a jours de Kaydo

merci de votre attention et un gros merci pour Vstream

KujoWolfgang

**Comment by LordVenom** [comment]
Bonjour, Je voie qu'une modif mais oui elle à était valider : 
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/5b35baf8af46ce18924422150659fc6a83e33747

Je ne peux pas tester Kaydo mais j'image que tu as tester avant d'envoyer, je n'est pas vue de code pouvant ne pas fonctionne donc j'ai valider pour la bêta.
