### ISSUE TITLE
Question programmation Hoster

### ISSUE THREAD

**Issue by jhdscript** [Kodi-vStream/venom-xbmc-addons#1903]
Bonjour je suis en train de coder un hoster pour vstream et j'ai un souci. Les films téléchargés sont encodés en AES-128. Il faudrait donc que je decode le stream recu avant qu'il soit lu par le player.

J'i beau cherché, je n'arrive pas a trouver de fonctions dans Kodi pour modifier le flux avant l'entrée dans le player. Auriez vous deja fait ce genre d'operations ?

**Comment by johngf** [comment]
Il y a des modules pour python pour décoder le aes 
google >> décode aes python

Quel est le nom du hoster? J'ai jamais vu ça

**Comment by jhdscript** [comment]
oui le souci c'est pas le decodage mais comment passer un stream decodé au player.
DOWNLOAD -> DECODE -> PLAYER

**Comment by TmpName** [comment]
Tu es sur de ton coup ?
Ca voudrait dire qu'il te faut un lecteur special pour lire le flux ?
Ou sinon un "codec" special pour lire le flux.

**Comment by jhdscript** [comment]
Oui j en suis certain car c est un dev un peu particulier. Avant j etais full nodejs mais je souhaite fzire un portage sous kodi

**Comment by TmpName** [comment]
Du coup illisible avec un lecteur tel que vlc ou mediaplayer ?

**Comment by jhdscript** [comment]
En utilisant le lien direct impossible en effet mais avec un simple decryptage aes ca marche du feu de dieu :)

**Comment by jhdscript** [comment]
Seul souci je ne sais pas comment faire pour decrypter avant d'envoyer au player de Kodi. Je ne trouve pas l equivalent des pipes nodejs sous Kodi

**Comment by johngf** [comment]
tu as essayé d'utilisé l'addon inputstream adaptive qui intégrée a kodi
crée un fichier DASH (.mpd) AES 128 supporté apparemment [ici](https://github.com/peak3d/inputstream.adaptive/wiki)

**Comment by jhdscript** [comment]
A tout hasard on pourrait pipe les flux dans Kodi ou c'est carrement impossible ?
