### ISSUE TITLE
Api permettant d'effectuer des actions via http ? 

### ISSUE THREAD

**Issue by abdel-m** [Kodi-vStream/venom-xbmc-addons#1904]
Bonjour, 
existe-t-il une api permettant d'effectuer des actions dans vstream via des requêtes http ? Cela permettrait entre autre une interaction avec Google assistant par exemple. 
Si cela n'existe pas, est-ce prévu ?

**Comment by LordVenom** [comment]
Bonjour, 

Ben.. en activer le serveur web de Kodi et en utilisant l'interface web.

**Comment by abdel-m** [comment]
Pour être plus précis, j'ai découvert le projet github.com/omertu/googlehomekodi cet après midi. Il utilise les webservice de kodi mais ceux-ci ne permettent que les actions de base comme naviguer dans l'interface, play, pause etc. Je n'ai pas réussi à trouver une solution pour effectuer une recherche directement dans vstream et jouer le "premier lien fonctionnel"? Je ne sais pas si c'est compréhensible ce que je dis haha

**Comment by LordVenom** [comment]
Faire une recherche pk pas il faudrait récupérer le lien générer par le webservice. Lancer un lien fonctionnel impossible la recherche n'est pas stocker par Kodi ni par vStream ce sont des menu dynamique.

**Comment by abdel-m** [comment]
Oui, j'ai vu qu'il y avait un lien permettant de faire une recherche de série, de film etc mais à partir de la bibliothèque kodi, donc si on arrive à catcher l'event, je pense que ça peut être faisable

Mais la recherche tu dois quand même la stocker en mémoire pour pouvoir l'afficher non ? Donc il "suffirait" de tester les liens un par un en mettant en premier les liens susceptible de fonctionner directement ? Je n'ai jamais programmer sur kodi donc je ne fais que balancer des idées, dis moi ce que tu en penses
