### ISSUE TITLE
Meilleure gestion d'exécution des vidéos

### ISSUE THREAD

**Issue by abdel-m** [Kodi-vStream/venom-xbmc-addons#1905]
Bonjour,
Je trouve le concepte de vStream excellent, je l'utilise depuis maintenant 2 ans, tout est parfait a l'exception d'un truc, la navigation pour trouver la vidéo qu'on cherche est assez fastidieuse... Dites moi ce que vous en pensez ? Mon idée serait simplement de ne plus séparer le résultat entre les différentes sources et de jumeler (cacher ?) les résultats identiques. Exemple : on fait une recherche sur "iron man" dans les films, le résultat nous montrerait "Iron man 1, iron man 2, etc" et lorsque l'on clique sur un choix, on retrouve la liste de toutes les sources venant de tous les sites. Cela nous évite d'avoir un résultat un peu brouillon avec plusieurs "iron man 1". Qu'en pensez-vous ?

**Comment by LordVenom** [comment]
J'ai rien compris xD

Tu veut virer le nom des sites de la recherche ? dans ce cas deja discuter c'est non.
Tu veut afficher directement les Hosts sur une recherche visuelle Active et utilise alluc

**Comment by abdel-m** [comment]
Désolé, c'est dur à expliquer mdr

En gros, je ne veux pas virer le nom des sites mais juste les déplacer. Le résultat ne serait plus grouper par site mais par film(ou série). Un peu comme une requête Sql :p
Du coup, quand on choisi un film, on a la liste de toutes les sources relative à ce film et qui seraient ventilé par site, ce serait plus ergonomique non ?

**Comment by LordVenom** [comment]
Ok lister les sites puis au click les recherches mouai faut limiter c'est source ça évite la liste de 50km.

**Comment by abdel-m** [comment]
J'ai pas compris ton message ?

En fait, je viens de regarder un peu le fonctionnement des autres add-on comme exodus par exemple, ça fait un peu ce que j'ai décrit plus haut, ça affiche les films (sans doublon) et quand on clique sur un film, on a toutes les sources qui apparaissent. Je ne sais pas si c'est faisable dans le cas de vStream ?

**Comment by LordVenom** [comment]
Pas possible.

**Comment by TmpName** [comment]
Nope pas possible, car le meilleur outil de recherche c'est toi.
Plus l'addon te simplifie le boulot, plus les recherches ne seront pas fiables.
