### ISSUE TITLE
Retrouver la liste des films et series Netflix

### ISSUE THREAD

**Issue by fawado** [Kodi-vStream/venom-xbmc-addons#1908]
Salut tous (et encore merci pour tout çà)
Question qui me vient, dans le meme genre que la recherche visuelle qui va chercher sur un site les infos des derniers films & co, serait-il possible d'avoir un dossier ou on retrouve les films, series,.. Netflix ? Je sais pas si un site existe et si ca serait possible de l'intégrer au sein de vstream... 

Voila si ca interesse, moi ca m'intéresserait, donc une idée comme une autre.

Thks a tous

**Comment by LordVenom** [comment]
La seul option que je voie c'est de faire une liste TMDB / recherche visuelle / liste ce sont des liste créer par la communauter TMDB et vStream fait ensuite une recherche sur les titres. Il suffis donc de créer la liste et de la partager.
