### ISSUE TITLE
les recherches des sources recommence 

### ISSUE THREAD

**Issue by lefou66** [Kodi-vStream/venom-xbmc-addons#1909]
Bonjour, tout d’abord merci bien pour vstream ont utilise pratiquement que ca pour nos films et séries. Jai 2 boites android chez moi avec kodi 17.6 a jour...les 2 ont la dernière version de vstream mais une fonctionne différament. Lorsque je lance une recherche par ex. pour un film...il cherche parmi les sources..jen essaie une..elle marche pas donc je fais back mais au lieu de retourner directement aux résultat de recherches des sources il recommance encore la recherche donc c'est très long ....quelqu’un a une solution ce serait très apprécier merci.

**Comment by Arias800** [comment]
A tu un addon qui sert a nettoyer le cache de kodi ?

**Comment by TmpName** [comment]
C'est ce que j'allais demander ^^.
Ou tout autre addon servant a configurer (optimiser XD)  kodi a ta place.

**Comment by lefou66** [comment]
j'ai ares wizard la dernière version mais quand j'ai remarqué ce problème la boîte était neuve

**Comment by lefou66** [comment]
bonjour,toujours pas de solution à mon petit problème? Peut etre le skin...la boite qui marche bien utilise aeon nox silvo et lautre aeon nox

**Comment by ktm520** [comment]
Bonjour a tous , intéressant , quel addon faut il pour nettoyer le cache de kodi , je suis novice avec kodi .

**Comment by Arias800** [comment]
Il fait utilise l'outil fournit avec stream il se trouvr dans les paramètre

**Comment by Arias800** [comment]
Il faut utilisé l'outil fournit avec vstream il se trouve dans les paramètre

**Comment by ktm520** [comment]
Merci , je vais regarder .

**Comment by LordVenom** [comment]
Bonjour,

Aucun addon pour nettoyer le cache. Juste quand tu as des soucis avec Kodi.
Comme pour ton navigateur tu ne nettoie pas le cache a chaque démarrage de ton navigateur.

**Comment by lefou66** [comment]
est ce que je peux mettre un lien pour une vidéo..pour vous montrer mon problème?

**Comment by LordVenom** [comment]
Oui même des images. Mais ont n'a compris le soucis tu as un problème de cache mais je sais pas s'ou ça peux venir.

**Comment by lefou66** [comment]
https://youtu.be/xYmsEZwXaCQ
ok je comprends..mais je me demande pourquoi ça le fait pas sur mon autre boîte Android...merci de m'aider

**Comment by LordVenom** [comment]
- remet le skin par default
- verifier que tu as la dernier version 0.5.8

**Comment by lefou66** [comment]
aucun changement...une time kb2 pro

**Comment by lefou66** [comment]
yoka kb2 pro

**Comment by LordVenom** [comment]
Je ne sais pas t'aider dsl. Je laisse ouvert le post, un jour quand j'aurais du temps je regarderais pour forcer le cache de cette page mais je sais pas quand et je sais pas comment vue que je ne peux pas reproduire le bug.

**Comment by Arias800** [comment]
Par hasard aurai tu le plugin colossus d'activer car moi j'avais eu un problème du même style qui a disparut lorsque je l'ai désactive

**Comment by TmpName** [comment]
Copie l'integralite de la box qui marche sur celle qui ne marche pas en ecrasant le contenu.

**Comment by lefou66** [comment]
je le trouve ou colossus,dans programmes addons?

**Comment by Arias800** [comment]
Dans extensions video
