### ISSUE TITLE
Proposition (indécente?)

### ISSUE THREAD

**Issue by RasPsykk** [Kodi-vStream/venom-xbmc-addons#1911]
Bonjour,

je ne sais pas s'il existe un forum ou autre mais j'ai vu que le salon Discord est fermé et que Twitter aussi il me semble, donc je me permets de poster ici, si cela ne convient pas merci de me le signaler.

Bien entendu je tenais à vous féliciter pour votre addon qui me permet d'occuper toutes mes soirées et ce depuis un moment maintenant (pas un jour ne passe sans Vstream) et la seule chose qui me manquerait c'est pouvoir utiliser mon abonnement canal sur Kodi (comme ça je ne lâche plus mon raspberry). Alors je ne sais pas trop quoi proposer, certains seraient-ils prets à m'aider pour réaliser cela, j'ai un peu d'expérience dans les addons mais vraiment les bases.

Le gros souci d'un tel addon est les DRM, j'ai pas mal parcouru de forums et j'ai vu que Kodi 18 apportait du nouveau. En effet, certains ont développé un addon pour NetFlix grâce à ces nouveaux scripts :

https://github.com/peak3d/inputstream.adaptive
https://github.com/emilsvennesson/script.module.inputstreamhelper
https://github.com/rolapp/plugin.video.zattooHiQ

Pensez-vous que quelque chose soit faisable de votre coté?
Alors si certains veulent se lancer dans ce projet, ou juste me filer un coup de main.

Merci encore pour tout ce que vous faites.

Amicalement

**Comment by LordVenom** [comment]
Bonjour, 

Non effectivement plus de discord, pas de forum, mais pour discuter avec l'equipe de vStream tu est au bon endroit xD.

Pour ma part je te remercie pour les encouragement mais je n'est pas le temps de me mettre sur un autre gros projet et j'ai même pas idée si c'est codable ou pas.

**Comment by RasPsykk** [comment]
Re,

pas de souci, je vous y rejoins, plus on est de fous, plus on avance loin !

Amicalement
