### ISSUE TITLE
VSTREAM Echec de lecture d'un ou plusieurs fichiers. 

### ISSUE THREAD

**Issue by moha0075465** [Kodi-vStream/venom-xbmc-addons#1912]
Vstream 
Kodi 16

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/11

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/vStream-FAQ

**Comment by Christian26800** [comment]
Moi j ai 80% des lien qui fonctionnent plus depuis 3 semaine . Je trouve ça bizarre . Quelques fichier netu et easyvid fonctionne .

**Comment by TmpName** [comment]
Il nous faut le log pr savoir d'ou ca vient.
