### ISSUE TITLE
Dolby 5.1 sur Uptobox ? 

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#1914]
Salut a tous.
Je n'arrive pas à avoir du 5.1 avec les liens Uptobox. Je suis sur alldebrid donc jai du 5.1 sur les liens 1fichier, rapidgator, uploaded, etc.

Dites moi si c'est possible d'avoir du 5.1 sur uptobox et comment ? Merci

**Comment by TmpName** [comment]
Si la source est en 5.1, tu l'auras.

**Comment by mino60** [comment]
sur zone telechargement.ws par exemple le film 
Open Water: 3 Cage Dive le son c'est bien du Dolby digital AC3 5.1sur la piste audio french et DTS 5.1

**Comment by vic1997** [comment]
Oui, j'ai tous mes films sur UpToBox et ils sont bien en 5.1 (après faut activé le laissé passé, le multi-canaux...)

**Comment by thorsten68** [comment]
Moi j'ai déjà beaucoup cherché a avoir du 5.1 j'ai suis jamais arrivé. J'utilise les liens 1fichiers (premium) avec kodi et vstream sur une mini 4k.
La seule fois ou j'ai réussit c'était en lisant mes films avec archos.
J'ai essayé en changeant le lecteur par défaut je suis arrivé a rien. 
Si quelqu'un a une idée, parce que c'est tout se qui manque pour avoir un système parfait.
Bravo déjà pour le taf accompli !

**Comment by Arias800** [comment]
Tu a active les laissé passé , le multi canaux dans Kodi ?

**Comment by thorsten68** [comment]
Oui j'ai déjà tout essayé, et activé le laissé passez dans les paramètres de la box.
Rien a faire

**Comment by thorsten68** [comment]
Pour moi le problème venait de kodi, même en lisant un mkv de mon disque dur ça marche pas en 5.1, alors qu'avec le lecteur archos j'y arrive.
Par contre si y'en a qui arrivent a avoir du 5.1 avec kodi je suis preneur...
