### ISSUE TITLE
Problème opnlod

### ISSUE THREAD

**Issue by Benian86** [Kodi-vStream/venom-xbmc-addons#1915]
Bonjour, depuis plus de deux semaines, il m'est impossible d'accéder aux flux opnload. (Et je ne suis apparemment pas le seul). Auriez vous une solution à ce sujet ou cela sera il réglé avec la prochaine mise à jour ?
Le boulot sur cette extension est tellement bon qu'il devient dur de s'en passer (car openlad représente une grande partie de la bibliothèque vstream) 
Merci d'avance

**Comment by TmpName** [comment]
Je m'en suis servi hier sans probleme.
Tu as d'abord une fenetre qui affiche que le temps peut etre de plus d'une minute, puis ca affiche "ok", si tu as ca et que apres ca tourne dans le vide pendant 30s, le prb vient d'opnlod, serveur surcharges.

Et sur certains sites tu pas de 6/7 hosters, donc non opnlad n'est pas indispensable.

**Comment by johngf** [comment]
a mon avis tu n'as pas la dernière version du fichier il faut attendre la prochaine mise a jour

**Comment by Benian86** [comment]
C'est bien ce que je pensais. J'espère que ça réglera ce problème. 
Merci pour vos avis

**Comment by TmpName** [comment]
Si ca affiche "ok", c'est que le lien a bien ete decode, c'est donc le serveur qui deconne, j'ai eu le prb aussi ces derniers jours.

**Comment by johngf** [comment]
la derniere modif n'est pas sur la master donc ça fonctionne pas

**Comment by 1shad** [comment]
Salut!
@TmpName , j'ai remarqué que la branche master a 31 commits  de retard.
Et il se trouve que ça correspond au commit de opld.   
Comme il y a une review demandé, sur [#1894](https://github.com/Kodi-vStream/venom-xbmc-addons/pull/1894), je crois qu'il faut l'acccepter(ou la refuser), car j'ai peur que cà bloque de pouvoir poussé sur master.

Alors je me trompe peut-être évidement...
En tout cas bon WE

**Comment by TmpName** [comment]
Mit a jour, dsl, avais pas vu.

**Comment by Benian86** [comment]
Merci.
S'agit il d'une mise à jour de source ou d'une mise à jour de l'extension ?

**Comment by Arias800** [comment]
mise a jour de source

**Comment by Benian86** [comment]
Ok j'attendrai que la mise à jour soit disponible. Merci à tous

**Comment by Benian86** [comment]
Tout est ok à présent. Merci à vous
