### ISSUE TITLE
question changement d'ip

### ISSUE THREAD

**Issue by ouaisouais** [Kodi-vStream/venom-xbmc-addons#1916]
bonjour,
mon ip change assez fréquemment dès que j'ai atteint 2giga de données
est-il possible de trouver une solution pour que le stream reprenne automatiquement après le changement d'ip?
ou suis-je condamné a regardé des fichier de moins de 2giga?
toute aide est la bienvenue merci

**Comment by johngf** [comment]
il nous faut plus de détails ...
si tu parle d' upto box il y a une limite si compte gratuit

**Comment by ouaisouais** [comment]
non je n'ai pas de problème de limite sur uptobox...
je m'explique, car c'est peut-être hors sujet...
mon mobile est mon routeur jusque la pas de souci. 
Quand j'utilise 2giga de données je n'ai plus d'internet, pas grave un script me reconnecte  la 4g automatiquement  et je peux a nouveaux utiliser 2giga de données (et ainsi de suite autant de fois que j'en ai besoin (c'est illimité)
le problème c'est que mon ip public change en même temps
vstream n'aime pas trop ça pendant la reconnexion il se fige (vstream ou kodi) pendant 1a2min avant que je puisse relancer le film la ou il en étais
j'aurai voulu savoir si on pouvais gérer une reconnexion auto avec vstream quand le stream est perdu (je pense aussi qu’un proxy ou vpn pourrai faire l'affaire mais la 1er solution serai top

**Comment by johngf** [comment]
j'utilise un routeur 4g (illimitée) et je n'ai jamais eu ce soucis tu est chez qui ?
dans les paramètres de ton smartphone  il n'y a pas une option qui coupe internet tous les 2 giga ?

**Comment by ouaisouais** [comment]
j'utilise une mobicarte avec une options internet max mon routeur c'est mon portable et je suis chez orange (ne pas rire a 9euro par mois qui date de l'iphone4 j'ai la 4G en illimité mais bon...) peut etre que une limitation par défaut sur  android mais je pense que c'est orange qui bloque tous les 2giga (mais si je me reconnecte c'est reparti) en soit vstream marche au top

**Comment by vic1997** [comment]
@ouaisouais J'ai orange avec un abonnement et ça bloque pas au bout de 2Go. Ca doit être ton forfait qui fait ça (trop vieux) ou ton téléphone.

**Comment by LordVenom** [comment]
Bonjour, dsl @ouaisouais  c'est pas vStream qui et en cause.
