### ISSUE TITLE
hds.to

### ISSUE THREAD

**Issue by noipo** [Kodi-vStream/venom-xbmc-addons#1917]
Bonsoir,
J'ai deux problèmes/reccomandations à faire sur cette sources.

- Depuis un moment, hds propose également des flux en VOSTFR pour la plupart de ses films et series mais on ne peut y accéder à travers vstream.

- Quand une series compte plusieurs saison, il est impossible de selectionner ( je pèse et il ne se passe rien ). Pourriez-vous régler ce problème ? 

Merci

**Comment by noipo** [comment]
@LordVenom

**Comment by LordVenom** [comment]
Bonjour, non pas moi j'ai pas accès dsl.

**Comment by Arias800** [comment]
@LordVenom tu est chez orange ?

**Comment by TmpName** [comment]
Lol, moi je peux, mais ca risque de prendre du temps, c'est ma semaine de reprise et j'ai plus trop de temps libre la.

**Comment by noipo** [comment]
Ok pas de problème, tiens moi au courant de l'avancement :)

**Comment by LordVenom** [comment]
@Arias800 : Non un petit fournisseur de Fibre.

**Comment by TmpName** [comment]
J'ai teste sur breaking bad, aucun prbs, j'ai pu avoir toute les saisons.
Et pour les episodes, j'ai VF et VOSTFR qui s'affiche.

**Comment by akatimike** [comment]
Kaydo (hds.to) moi jai toujour aucun information...

**Comment by Arias800** [comment]
Essayer de mettre a jour votre bix internet ou routeur pour ceux qui n'arrive pas ace connecté au site

**Comment by Arias800** [comment]
Box

**Comment by akatimike** [comment]
Jai acces sur pc directement...weird....

**Comment by mass2110** [comment]
Pareil pour moi, aucune information, impossible de démarrer le film avec Kaydo

**Comment by TmpName** [comment]
Bon me faudrait un exemple qui deconne, je viens de tester avec thor, aucun probleme, je suis tombe sur un lien uptobx et le film a demarre.

**Comment by noipo** [comment]
Black mirror la série :) @TmpName

**Comment by TmpName** [comment]
Pas pu tester, le site est en protection cloudflare, et le code actuel deconne. Donc je corrige d'abord cloudflare.

**Comment by TmpName** [comment]
Bon j'ai fais quelques modifs pour que la recherche marche mais je suis pas sur que ce soit ca ton probleme.
Enfin bon, en passant par la recherche, j'arrive a avoir les 4 saisons, j'ai lance l'episode 1 de la saison 2, pas vu de prbs.
