### ISSUE TITLE
Xbox One X

### ISSUE THREAD

**Issue by mediax24** [Kodi-vStream/venom-xbmc-addons#1921]
Bonjour à tous 
je n'arrive pas à faire fonctionner Vstream sur ma xbox one sous Kodi 18 (64bit)

Je sais que c'est tout nouveau (et un véritable retour au source, car j'ai commencé xbmc sous xbox première génération) mais je suppose que vous êtes déjà sur le pied de guerre concernant le retour de kodi sur xbox.

Y-a-t-il une astuce en particulier à faire pour le faire fonctionner?   

C'est vrai que pour le moment il n'y a pas grand chose qui fonctionne parfaitement sur xbox à part
SportDevil et Youtube  qui sont les seuls actuellement à fonctionner sans problèmes parmi mes applications habituelles

Cordialement

**Comment by Arias800** [comment]
Il faut utiliser ce lien: http://vstream.ga/repo/ et choisir la version  "just-xbox"

**Comment by mediax24** [comment]
Merci
L'installation cette fois ne fonctionne pas avec le plugin special xbox
Pas grave j'attendrai quelques temps

**Comment by luluvulcain** [comment]
Bonjour mediax24, j'ai pas la Xbox One mais pour avoir vStream sur Kodi PC & Android, il faut installer le Repo et ensuite l’extension. Il faut faire pareil sur la Xbox One au http://vstream.ga/repo/

**Comment by mediax24** [comment]
Oui j'utilise déjà vstream sur ma box android depuis quelques temps et je n'ai aucun soucis pour l'installation et l'utilisation de vstream. Seulement sur xbox one x l'installation se passe bien mais l'application se crash au démarrage. Ce n'est pas bien grave je continuerais d'utiliser ma box android. 

Cordialement 

Envoyé de mon iPhone

**Comment by LordVenom** [comment]
Bonjour,

Pas de rapport de bug ? aucune piste ? Personne ne peux résoudre la problème de cette façon.

**Comment by LordVenom** [comment]
Nouvelle version dispo sur http://vstream.ga/repo/ 

plugin.video.vstream-0.5.9-justXbox.zip.

**Comment by cybertalis** [comment]
Merci super ça remarche...

**Comment by lebigboss** [comment]
Vous arrivez a accéder aux fichiers de ZT.ws vous ?

**Comment by StarLord87** [comment]
Oui bein j’ai beau avoir fait tout ce qu’il faut 30 fois de suite... il n’y a tjrs rien qui marche sur Xbox !!

**Comment by Arias800** [comment]
Il y a deux possibilité :
-1 Il ont fait une modif qui ferait buggé l’installation 
-2 Il y a encore une modif a faire
En tout cas si personne d'autre ne teste je peux pas t'aider

**Comment by StarLord87** [comment]
Oui, je découvre kodi donc pas évident pour moi. Mais j’ai bien autorisé les sources inconnues

**Comment by LordVenom** [comment]
Bonjour, juste au dessus vous avez un message clair que vous n'avez pas du lire.


`Pas de rapport de bug ? aucune piste ? Personne ne peux résoudre le problème de cette façon.`


Perso j'ai tester vStream sur xBox one fonctionne chez moi.

**Comment by StarLord87** [comment]
Bonjour et merci d’essayer de m’aider... je découvre kodi et ces fonctions donc je ne sais ce qu’est un rapport de bug ou autre.... quel renseignement vous faudrait il.... en fait mon problème est apres l’installe dans je souhaite télécharger une liste (film populaire par exemple..) ça commence à répertorier les sites de films et d’un coup le message «  vstream connection impossible 405 » s’affiche ! Puis finalement quand j’arrive au film,  après « résolve «  ça m’affiche «  lecture impossible un ou plusieurs fichier manquant » ! Je reste à votre disposition au qu’à au vous pourriez m’éclairer. Merci encore ____________________De : "Lord Venom" Date : 5 févr. 2018 à 11:59:05À : Kodi-vStream/venom-xbmc-addonsCc : thomas.stephane@cegetel.net, comment@noreply.github.comSujet : Re: [Kodi-vStream/venom-xbmc-addons] Xbox One X (#1921)Bonjour, juste au dessus vous avez un message clair que vous n'avez pas du lire.
Pas de rapport de bug ? aucune piste ? Personne ne peux résoudre le problème de cette façon.
Perso j'ai tester vStream sur xBox one fonctionne chez moi.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Kodi-vStream/venom-xbmc-addons","title":"Kodi-vStream/venom-xbmc-addons","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Kodi-vStream/venom-xbmc-addons"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LordVenom in #1921: Bonjour, juste au dessus vous avez un message clair que vous n'avez pas du lire.\r\n\r\n\r\n`Pas de rapport de bug ? aucune piste ? Personne ne peux r&#233;soudre le probl&#232;me de cette fa&#231;on.`\r\n\r\n\r\nPerso j'ai tester vStream sur xBox one fonctionne chez moi."}],"action":{"name":"View Issue","url":"https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1921#issuecomment-363051133"}}}

**Comment by Arias800** [comment]
Sur quel hoster (open load , uptobo x...)?

**Comment by StarLord87** [comment]
Tous en fait.

**Comment by gepzep** [comment]
Salut je ne trouve pas de lien pour xbox le site est apparemment down pourriez vous m'envoyer un lien svp.

**Comment by cybertalis** [comment]
Bonjour lordVenom il y a eu une mise à jour de Kodi leia alpha 2 sur Xbox One depuis Vstream ne fonctionne plus . Es tu au courant ?

**Comment by mediax24** [comment]
Je confirme cela ne fonctionne plus

**Comment by Arias800** [comment]
Un peux plus de détaille quoi qui ne fonctionne pas ?

**Comment by mediax24** [comment]
Je ne sais en dire plus pour le moment. Mais ce soir j’essayerais à nouveau.

**Comment by cybertalis** [comment]
Alors en faite lorsque l on fait une recherche et que l on clique sur une source au lieu de trouver les différents fichiers cela créer une nouvelle arborescence avec les résultats en dessous ... Et au final quand le fichier apparaît il marque quand on clique dessus qu il est introuvable...En espérant avoir était clair ( j ai un doute ) 😁...

**Comment by Arias800** [comment]
L'affichage bugger c'est un bug de kodi 18 donc on attends la beta pour voir si c'est corriger par contre chez moi les liens marche normalement

**Comment by cybertalis** [comment]
Arias800 tu es passé sur l alpha2 ?

**Comment by Arias800** [comment]
Oui sur windows mais je suis retour sur l'alpha 1 beaucoup moins bugger ^^

**Comment by cybertalis** [comment]
Oui mais là on parle de xboxone et malheureusement une fois la mise à jour faite on peut pas revenir en arrière ...

**Comment by Arias800** [comment]
Faut voir avec @LordVenom si il essaye de corriger ça avant la beta puisque qu’apparemment il doit y avoir beaucoup de modif a faire dans vstream

**Comment by LordVenom** [comment]
heu non c'est @TmpName  je pense.Mais en ce moment y a rien de prévus pour XboxOne.

**Comment by cybertalis** [comment]
Bien eux ils ont prévue de faire une mise à jour 🤔🤔😒😒😟😟

**Comment by LordVenom** [comment]
C'est qui eux ?

**Comment by cybertalis** [comment]
Bien eux ils ont prévue de faire une mise à jour 🤔🤔😒😒😟😟

**Comment by cybertalis** [comment]
Les gens de chez Microsoft on passé la version de kodi  leia alpha à leia alpha 2 et depuis je n arrive plus à faire fonctionner Vstream

**Comment by LordVenom** [comment]
Une version alpha c'est une version développer c'est comme télécharger la bêta de vstream et dire que ça fonctionne pas. ça n'aide personne, faite vos retour de bug a Kodi ça aideras les développers.

**Comment by Arias800** [comment]
Faut juste pas préciser que tu parle de vstream sinon il vont te faire dégager x)

**Comment by cybertalis** [comment]
Ok je vais éviter de les énerver et attendre une nouvelle mise à jour...

**Comment by Arias800** [comment]
Après tu peux les prévenir mais ne pas siter le nom de l'addon (quand je dit dégager c'est un peux violant comme terme mais il vont te dire "addon illégal on aime pas ça " et fermer l'issue comme des sauvage x)

**Comment by Poucinet929** [comment]
Pareil de mon côté (xbox one) , tout fonctionné très bien et d'un coup que je clique sur n'importe quelle demande (film ou série) ça me renvoi direct sur la première page où j'étais déjà

**Comment by Arias800** [comment]
Ça s'affiche à la suite du menu précèdent

**Comment by Poucinet929** [comment]
Le menu principal se répète encore et toujours peu importe ma demande

**Comment by lebigboss** [comment]
Moi aussi bug d'affichage sur les menus
Par contre j'ai testé un addons vidéo anglais et les menus s'affiche normalement, pourtant c'est même pas une version faites pour Xbox.

Par contre ils ont mit Kodi 18 pour nous faire chier

**Comment by Arias800** [comment]
Non c'est parce que vous avez pas de kodi inférieur donc pas de stable mais patientez je crois avoir résolu le problème j'attends juste un retour et je le mets dans la bêta donc vous aurez la correction dans la maj mensuel si tout ce passe bien ^^

**Comment by Arias800** [comment]
Normalement c'est corriger faut attendre la maj mensuel ^^ https://github.com/Kodi-vStream/venom-xbmc-addons/commit/b9ce7bca6c71b059c3862fc6c10a97bdc4b55484

**Comment by lebigboss** [comment]
J'ai tester avec la bêta 0.6.3 et le menu fonctionne très bien. Tout s'affiche dans l'ordre sauf quand on consulte un site ça bloque avant la fin du chargement de la page 
Exemple dans
Film
Film (Qualité HD)
DDL-Island 
Le chargement ce fait 10/10 mais Kodi reste figé et obligé de le relancé.
Alors que Vstream-Recherche fonctionne bien et même les liens DDL-Island

**Comment by Arias800** [comment]
Je crois savoir d'où ca viens j'ai essayer de corrige ce bug sur le plus de site possible mais j'ai du en oublier ^^

**Comment by cybertalis** [comment]
Merci Arias depuis la 0.6.3 sur Xbox ça remarche.

**Comment by Poucinet929** [comment]
Les deux mises à jours viennent de se faire de mon côté aucun changement, j'y comprends rien ^^
Help ?

**Comment by Arias800** [comment]
Si tu parle de la mise à jour en vert c'est normal puisqu'il y a 2 type de mise à jour celle en verte donc celle des site et hoster et celle qui se fait de manière mensuelle (la versions 0.63 qui est en phase de bêta actuellement ) qui correspond à la mise a jour du cœur de vstream et c'est cette mise à jour qu'il faut ^^

**Comment by Poucinet929** [comment]
Merci de ta réponse 
Et du coup cette mise à jour la n'existe pas encore ?
Désolée je suis absolument nul en tout ça, j'avais eu du mal à me le télécharger la première fois

**Comment by Arias800** [comment]
Elle existe mais réserver au développeur ou au personne connaissant un minimum tout ce qui est rapport de bug mais elle devrait pas tarder à sortir à mon avis (après si ça ce trouve je me trompe mais bon x))

**Comment by Poucinet929** [comment]
T'as pas trop l'air du genre à te tromper ^^
Je vais patienter alors, en espérant que ça fonctionne à nouveau. 
Merci de ta réponse, et autre question sur xbox quelqu'un peut prendre la main comme sur un pc ?

**Comment by Arias800** [comment]
J'en n'ai aucun idée je n'ai pas d'xbox chez moi ^^

**Comment by Poucinet929** [comment]
Bon je vais attendre alors ☺️

**Comment by cybertalis** [comment]
Sur Xbox tu vas dans ton Kodi sur installer une extension depuis un fichier ZIP si tu as installer Vstream depuis la source http://vstream.ga/repo/ tu vas trouver un plugin se finissant par 0.63 tu le selectionne   tu appuis sur la touche A de ta manette . Tu attends un petit 1\4 d heur qui s installe et quand tu vas retourner sur Vstream tu sera en version 0.63 qui corrige les beugs.

**Comment by Poucinet929** [comment]
Ça a l'air de fonctionner, merci à tous !!

**Comment by Poucinet929** [comment]
Bon les menus sont revenus correctement mais maintenant tous les liens sont en introuvables
