### ISSUE TITLE
Ajouter une catégorie (DRAMA ) dans une source déjà présente 

### ISSUE THREAD

**Issue by Saab51** [Kodi-vStream/venom-xbmc-addons#1922]
J'aimerais savoir si c'etait possible d'ajouter la catégorie Drama presente dans la source ianime (mangacity) déjà présente dans vstream , parce que les source de drama sont vraiment rare !

J'ai vu que l'url etait "(URL_MAIN + 'drama.php?liste=' + RandomKey, 'ShowAlpha')" comme celui des animes et séries mais les épisodes ne s'affiche pas !

Merci d'avance .

Modif:
j''ai parvenue en changeant "SERIE_SERIES = (URL_MAIN + 'series.php?liste=' + RandomKey , 'ShowAlpha')" 
et 
 "elif '?drama=' in aEntry[2]:
                oGui.addTV(SITE_IDENTIFIER, 'showEpisode', sDisplayTitle, sPicture, sPicture, 'series.png', oOutputParameterHandler)

par

SERIE_SERIES = (URL_MAIN + 'drama.php?liste=' + RandomKey , 'ShowAlpha')"
 et
 "elif '?drama=' in aEntry[2]:
                oGui.addTV(SITE_IDENTIFIER, 'showEpisode', sDisplayTitle, sPicture, sPicture, 'series.png', oOutputParameterHandler)"

mais ca remplace la categorie serie !

**Comment by LordVenom** [comment]
Tu ne peux pas utiliser SERIE_SERIES si tu ajouter une catégorie a la source il faut creer ta propre variable SERIE_DRAMA ou même pas besoin juste creer une nouvelle entrer dans le menu la fonction **load**()

Tu verras ton menu que en navigant dans la source vStream/toutes les sources/nom de ta source.

```
    oOutputParameterHandler = cOutputParameterHandler()
    oOutputParameterHandler.addParameter('siteUrl', 'URL_MAIN + 'drama.php?liste=' + RandomKey ')
    oGui.addDir(SITE_IDENTIFIER, 'ShowAlpha', 'Drama', 'animes.png', oOutputParameterHandler)
```

Pour le **elif '?drama=' in aEntry[2]:** oui tu peux faire ça ou
`if 'series' in aEntry[2] or '?drama in aEntry[2]`

**Comment by Saab51** [comment]
Ah oui c'est bon ca marche merci, je croyais qu'il fallait créer la categorie en haut en variable et pas qu'avec la fonctionne  **load()**
