### ISSUE TITLE
VSTREAM Sources vide

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#1923]
Bonsoir , je n'ai plus de films sur les sources normal ou pas ?
Y a t'il une mise a jour a venir ?

**Comment by LordVenom** [comment]
Bonjour,

Dsl, mais il faut de temps en temps le rappeler.

Ta question et mal poser, ce Github n'est pas un service d'assistance mais un "forum" de rapport de bug.
Je t'invite a lire ce message pour plus d'information
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/11

**Comment by ktm520** [comment]
Bonjour , merci pour la réponse , existe t'il un forum dédié a vstream ?
Problème résolu , j'ai débranché la tvbox , puis la mise a jour c'est faite .
