### ISSUE TITLE
Communauté Kodi Fr

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#1924]
La communauté francophone du media center Kodi. 

http://kodi-fr.rf.gd/index.php

**Comment by hotlittlewhitedog** [comment]
Passez svp en HTTPS

**Comment by TmpName** [comment]
^^.
C'est juste un forum, pas un site de transaction en bourse, si l'hebergeur le propose pas, pas franchement vital.
