### ISSUE TITLE
Possibilité d'avoir Soundcloud

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#1928]
Depuis un moment l'addon Soundcloud ne fonctionne plus à cause du changement api
mais le problème c'est que le développeur n'est plus actif et il y a aucun autre addon Soundcloud.
Donc,je voulais savoir si c'est possible de l'ajouter dans Vstream(avoir une section musique)

**Comment by TmpName** [comment]
Pour moi non. Reprendre un projet existant demande quelques procedures, on est pas des voleurs non plus.
Et chacun son domaine, c'est pas pour rien qu'on a laisse tomber la Tv par  IP.
