### ISSUE TITLE
Plus rien ne fonctionne

### ISSUE THREAD

**Issue by rafik775** [Kodi-vStream/venom-xbmc-addons#1929]
Bonjour à tous et merci d´avance, depuis la mise à jour 0.5.9 (environ 3 semaine) plus rien ne fonctionne et aucun lien ne s’affiche lorsque je clique sur un site (ex: je clique sur Films>Films(qualité HD)>French-stream) et bien sa m’en met en chargement x/18 et une fois qu’il est finit rien ne s’affiche, alors que avant tout marchais à pars certains liens, j’ai essayé de le desinstaller/réinstaller mais rien ne change avez vous des idées s’il vous plait ??

**Comment by LordVenom** [comment]
Bonjour, Une erreur dans le log ?

**Comment by rafik775** [comment]
Bonjour j’ai été dans Android>data>org.xmbc.kodi>files et après dans le dossier files et bien il n’y a absolument rien

**Comment by LordVenom** [comment]
Utilise l'outil de vStream pour uploder le log (Apres avoir activer les logs dans le system de Kodi et d'avoir reproduit ton bug).

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by rafik775** [comment]
Tenez le lien : https://slexy.org/view/s2uzRAgx0R

**Comment by LordVenom** [comment]
Aucune erreur dans le log.

**Comment by rafik775** [comment]
Ta aucune idée ducoup ???

**Comment by TmpName** [comment]
Moi je trouves que
1 - il y a beacoup de "cant import plugin", trop pour des fillms
2- ligne 95

Mais je ne vois rien de bizarre non plus.

**Comment by rafik775** [comment]
Je voit deux ERROR ligne 95-96 sa a aucune incidences ??

**Comment by LordVenom** [comment]
Le mode debug de Kodi est activé ?

Vide le cache et réinstall. (voir les outils de vStream).
