### ISSUE TITLE
Pas de streaming sans premium

### ISSUE THREAD

**Issue by bgiraut** [Kodi-vStream/venom-xbmc-addons#1930]
Bonsoir à tous,

Depuis deux semaines j'ai pas mal de soucis avec les liens 'zone-telechargement'
Sur les hébergeurs uploaded et 1fichiers, j'ai systématiquement le message 'Pas de streaming sans premium' alors que je dispose d'un abo 'real-debrid' configuré dans le plugin UrlResolver. 
De plus les liens sur Rapidgator,Nitroflare et Turbobit sont toujours vides. Rencontrez vous les mêmes soucis de votre coté. 

Merci

**Comment by LordVenom** [comment]
Bonjour, 

Il y a une issues sur Urlresolver : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1819
peux être trouveras tu la solution la bas.

Pour les autres hosts je vérifierai dans la semaine merci.

**Comment by LordVenom** [comment]
Rapidgator,Nitroflare et Turbobit ne sont pas supporter. Logiquement on peux tester avant d'afficher mais comme leur url sont coder pour le coup ont peux pas.

**Comment by bgiraut** [comment]
Salut LordVenom,

Que veux tu dire par "Rapidgator,Nitroflare et Turbobit ne sont pas supporter" ???
J'ai tjs streamé les films depuis 'Rapidgator' sur vStream et ca à tjs marché. 

Le message  'Pas de streaming sans premium'  est bien remonté par le plugin Vstream non ?

**Comment by TmpName** [comment]
Oui justement, c'est remonte par vstream mais pas par urlresolver, verifie qu'il soit bien active dans la config de Vstream.
Si les liens s'affiche avec un nom de hoster en rose > url desactive.
Si les lien s'affiche avec un code de juste 3 lettres (UPT par exemple) > urlresolver ok.

**Comment by bgiraut** [comment]
Je te confirme, seul uptobox semble passer par le debrideur et a le nom court sur 3 lettres. Les autres sont tout rose et affiche le message 'Pas de streaming...' ou sont vides.

**Comment by TmpName** [comment]
Non c'est possible.
En fait Vstream cherche le le lien de la video, si tu as le debrideur active, il envoit le lien au debrideur.
A partir de la c'est plus Vstream qui gere, le debrideur regarde si il peut s'en occuper ou pas (donc a ce moment Rapidgator peut fonctionner)
Si il peut, il affiche le code de 3 lettres, et le gere
Si il ne peut pas, il repasse le lien a Vstream, et la c'est le resolver de Vstream qui s'en occupe (donc rapidgator ne marchera plus)

Donc ca vaudrait dire que UrlResolver galere avec le lien, donc deux possibilitées.
1- UrlResolver deconne ou est mal configure
2- Le lien passé par Vstream a urlresolver est foireux, mais la c'est bizarre car dans ce cas Vstream ne devrait pas pouvoir le gerer non plus.

**Comment by bgiraut** [comment]
Le fait que Vstream ne propose pas de fichier pour Rapidgator (tout rose ou sur 3 lettres) semble confirmer que le lien passé par Vstream à UrlResolver est foireux non ? sinon il proposerait à minima un lien tout rose non ?

**Comment by TmpName** [comment]
non, car vstream ne le gerant pas, il n'affiche plus rien.

**Comment by TmpName** [comment]
Bon je viens de tester, et je confirme, c'est ton urlresolver qui deconner.
J'ai teste sur le premier film de la liste (me souvient plus du nom) avec urlresolver active, et j'ai eu tout les liens avec le codage AZERTY-ABC, nitroflare, uptbx, rapigtr, ect ...

**Comment by bgiraut** [comment]
Merci pour le test TmpName. Ca me rassure j'ai sûr d'avoir déjà regarder des videos via les liens rapigt et nitroflare. 
Néanmoins, je viens de refaire un test et seul uptobox est bien proposé en premium via Urlresolver.

**Comment by bgiraut** [comment]
Je vous remercie, j'ai trouvé la solution. J'ai réactivé mon 'device' sur Realdebrid via le plugin UrlResolver et maintenant tous les liens me sont bien proposés. Bizarre bizarre. 
Encore merci pour votre aide et pour votre super travail.
