### ISSUE TITLE
Trakt : Marquer comme regardé 

### ISSUE THREAD

**Issue by Moyounnet37** [Kodi-vStream/venom-xbmc-addons#1931]
Bonjour,

Je viens de jeter un œil à la dernière mise à jour. Je fais un peu suite au bogue #1888. 

Lorsque dans le menu trakt, on se place sur un épisode d'une série de notre collection, et qu'on le marque comme 'regardé dans trakt', ce sont tous les épisodes de la saison (peut être même de toutes les saisons) qui sont marqués comme regardé. 

Autre point plus personnel, j'ai du mal à voir jusqu'où vous souhaitez intégrer trakt. De mon point de vu, il est dommage que lorsque l'on veuille marquer un épisode comme vu, il faille le faire pour vstream et pour trakt. J'ai un peu l'impression que cela fait doublon, mais c'est un autre débat :)

**Comment by TmpName** [comment]
Yep, pour le moment ca marche juste avec les titres, donc toutes les saisons doivent se cocher aussi, en fait cette fonctionnalitee a ete debute il y a plusieurs mois mais jamais ameliorée (car peu utilisée encore)
Par contre je vois pas pkoi il faut le faire pour trakt + Vstream ?

**Comment by Moyounnet37** [comment]
> Par contre je vois pas pkoi il faut le faire pour trakt + Vstream ?
De  mon point de vu, lorsque je marque une série comme vu dans vstream, c'est pour me souvenir que j'ai vu l'épisode. Même intérêt lorsque je marque l'épisode comme vu dans trakt. Ce qui fait que je marque systématiquement un épisode comme vu dans vstream et dans trakt. La principale différence entre les deux, et c'est peut être sur ce point  que j'utilise mal vstream, c'est que dans vstream, on ne marque pas un épisode comme vu, mais simplement un 'lien'. Et pour deux liens différents, l'un peut être vu, et l'autre non vu.
Ceci dit, pour lancer la patate chaude au voisin,  je dirais que c'est au plugin officiel de trakt, que revient la responsabilité de marquer comme regardé les sources visionnés puisque ces options permettent de surveiller les extensions et les liens HTTP (je crois).
Question bonus : les vidéos sont visualisées via un lien HTTP ?

**Comment by TmpName** [comment]
Si tu marques un lien lu dans un des deux, ca devrait marcher pour l'autre vu que c'est le meme compte trakt ?
Trakt propose la surveillance des sources, il y a une autre issue la dessus, et c'est a Vstream de faire des modifs.

Kodi gere plus que les lien http, et sur d'autres ports que le 80.

**Comment by Moyounnet37** [comment]
Je ne sais pas si on se comprend bien :)
Si je marque un lien comme regardé depuis vstream, via le plugin trakt, le site trakt est mis à jour et tous les logiciels qui utilisent trakt voient bien que le film a été vu. Je pense que c'est à cela que vous faites référence. 

Si je marque un lien comme vu/non vu, celui-ci n'est pas automatiquement marqué comme 'regardé' dans vstream. Voilà ce que je voulais exprimer. C'est dommage, mais je me doute que techniquement, cela ne doit pas être évidant à gérer. D'autant que par la suite, on peut s'attendre à ce qu'un lien marqué comme Trakt sur leur site, apparaisse comme 'vu' dans vstream. Et vous n'avez pas fini de faire des développements.

**Comment by LordVenom** [comment]
Bonjour,

Je savais même pas que l'addon track pouvais marque lus sur tous les addons mais sur vStream il ne pourras pas comme vous l'avez remarqué ce sont des liens qui sont marquer lus et pas une série ou un film puisque l'addon peux être utilisé sans META, peux être activer les metas réglerai le soucis ?

Mais bon nous sommes partis du principe que comme nous sommes persona non grata dans le monde de Kodi il vaut mieux éviter d'inclure ou de dépendre d'un addon tiers.

**Comment by TmpName** [comment]
Ha ok, pareil ^^, j'avais pas compris que le plugins trakt se rajoutait sur Vstream.
Comme le dit @LordVenom le plugin a besoin des metas et qu'on utilise celle dont il a besoin, c'est a tester mais je ne suis pas sur que Vstream remplisse les bon metas.
Ce n'est pas prevu d'etre gere pour le moment car ca augmente les traitements et surtout impossible de le faire fiable a 100%, a partir d'un titre on ne peut pas etre sur a 100% de recuperer le bon titre ou le bon episode.
