### ISSUE TITLE
DocuStream does not work using "Genres"

### ISSUE THREAD

**Issue by Nux007** [Kodi-vStream/venom-xbmc-addons#1938]
Le plugin fonctionne parfaitement sauf lorsqu'on entre dans le menu "Genre" des documentaires. Ce n'est pas critique mais je reporte quand même le bug ;-)

NOTICE: 	[PLUGIN] Vstream: could not load site: documentaires_streaming_com error: 'module' object has no attribute 'showGenres'
ERROR: Traceback (most recent call last):
ERROR:   File "/home/nux007/.kodi/addons/plugin.video.vstream/default.py", line 127, in parseUrl
ERROR:     function = getattr(plugins, sFunction)
ERROR: AttributeError: 'module' object has no attribute 'showGenres'
[PLUGIN] Vstream: Table initialized
ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=showGenres&sFav=showGenres&site=documentaires_streaming_com&siteUrl=True&title=Documentaires%20Streaming
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showGenres&sFav=showGenres&site=documentaires_streaming_com&siteUrl=True&title=Documentaires%20Streaming) failed

**Comment by TmpName** [comment]
Vu, merci, la prochaine version devrait corriger ce prb.

**Comment by Nux007** [comment]
Fix testé et confirmé , merci ;)
