### ISSUE TITLE
MaReplay TV => Categories

### ISSUE THREAD

**Issue by Nux007** [Kodi-vStream/venom-xbmc-addons#1939]
Le plugin fonctionne bien, néanmoins, un petit bug non critique a été trouvé 

Aller à
`vStream -> TV Replay -> TV Replay (Genres ) -> Ma Replay TV -> Categories`
Montre un dossier vide, hors, coté site web, il existe bien des catégores ( htt  ps ://www.mareplaytv.com/categorie/ )
Le bug n'est vraiment pas critique, mais comme d'hab, je reporte l'issue.

NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
NOTICE: 	[PLUGIN] Vstream: load site mareplaytv and call function showMovies
NOTICE: 	[PLUGIN] Vstream: Table initialized

( Seules infos dispos dans le log )

**Comment by TmpName** [comment]
Ok, la j'ai laisse tomber, il y a vraiment beacoup trop de modif a faire pr metre le code a jour.

**Comment by Nux007** [comment]
Ok, je vais essayer de trouver un peu de temps pour plonger dans le code alors

**Comment by Nux007** [comment]
Fix mergé par LordVenom
