### ISSUE TITLE
Papystreaming

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1940]
Papystreaming ne fonctionne plus. J'ai une nouvelle url ttps://papystreaming.pw/. Ma question est est ce une copie ou le nouveau site?

**Comment by TmpName** [comment]
Nouveau site je dirais, et j y trouve rien de special, moi je desativerais le site.

**Comment by razorex** [comment]
Qu'entend tu part tu n'y trouve rien de spécial?

**Comment by TmpName** [comment]
Yep, petit catalogue, peu de hosters.

**Comment by johngf** [comment]
le site que tu propose ne ressemble pas a l'ancien les plus proche sont papystreaming .fr ou  .video
