### ISSUE TITLE
re: changement d'ip public

### ISSUE THREAD

**Issue by ouaisouais** [Kodi-vStream/venom-xbmc-addons#1942]
ancien message closed https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1916
je reviens vers vous car j'ai pris un compte uptobox suite a la réponse me
parlant de problème du au compte gratuit.
donc je suis avec un compte premium sur uptobox bien configuré dans Vstream (pas par urlresolver
je comprends pas pourquoi je ne peux pas changer d'ip sans coupure de mon film
le cache du film devrait reprendre en premium non?(sur le navigateur web ca le fait en transparence la reprise du cache j'ai tester avant)
sinon une astuce pour gérer ce changement d'ip
je ne dis pas que vstream bug, mais il doit bien avoir un moyen de gérer ça ?

**Comment by TmpName** [comment]
Ce n'est pas Vstream qui gere ca mais kodi lui meme, et pour moi c'est normal.
Tu telephones a quelqu'un, a un moment tu changes de telephone, tu trouves pas normal que la communication soit coupee ?

**Comment by ouaisouais** [comment]
Heu je vois pas le pourquoi tu me parles de téléphoner....(changement d'ip ne veux pas dire téléphoner et le tel sert juste a ca) donc Réponse Hors Sujet
moi j’essaie juste de faire en sorte que ca marche (je pense pas que c'est ici que je vais trouver une solution) j'irai voir les anglais beaucoup plus ouvert que vous et surtout plus compréhensif
vu les réponse débile que je reçois je vais pas aller loin
 
heureusement que j'ai pas demandé comment on fait pour regardé direct 1080p sur uptobox 10807sans passer par uptostream et eviter la gui et lancer la video un peu comme resolver.... on m'aurait dit pas possible. :D
T’inquiètes pas , comme un grand j'ai modifier le fichier hoster de uptobox.....(d'ailleurs si besoin pour la communauté 1 je le laisserai
mais ici vous êtes supérieur au gens qui pose des question....
 belle mentalité arrête Vstream te prends pas la tete fait le que pr toi c'est mieux
un vulgaire scrapping web et ça ce prends pour un dieux du codage 📦 
des scripts c pas compliqué a adapter surtout quand tu connais le language je récupérè tous mes stream sur les site en .strm grâce a un script et je me la pète pas pour autant.
(j'aurai préférer une réponse plus constructive genre c pas vstream qui gere mais vstream envoi le lien a lui qui gere et voir si yavais moyen de faire Quelquechose
en 2018 on gere tjrs pas une reco automatique??

super prouesse...j'irai demandé de l'aide ailleur.

tu peux te faire plaisir et close le sujet  tu pourras jouer au grand manitou encore une fois ;)

**Comment by ouaisouais** [comment]
https://www.petit-fichier.fr/2018/02/08/uptobox/uptobox.rar
a mettre dans  \kodi\addons\plugin.video.vstream\resources\hosters
c'est le  fichier uptobox hoster modifier sans la Gui qui sert a choisir uptobox ou uptostream
lance directement la video en qualité maximum avec uptobox
3lignes de changer....toi tu m'aurais dit quoi vu la qualité de ton dialogue
les 3 lignes c moi qui les a modifier en 2minute juste en analysant ton script sans meme connaitre ce language.

**Comment by Arias800** [comment]
Je répond au cas ou tu te serai calmé ... pour rajoute une options de ce style (je parle de la reco automatique )il faut avoir le temps voir si c'est gerable avec tout les hoster bref ça ne se fait pas comme ça . Ensuite TmpName ne ta pas manquer de respect alors pourquoi toi tu le fait ? Et non les anglais ne sont pas forcément plus ouvert vu la mentalité des dev de la team de kodi

**Comment by ouaisouais** [comment]
Je suis tout a fait d'accord il  ne m'a pas manquer de respect vulgairement, mais bon la il ma envoyé boulet comme un boulet! (ça c'est pas bien) 
après il m'aurait fait une réponse constructive comme tu viens de le faire j'aurai vraiment apprécie
d'ailleurs je t'en remercie je comprends mieux 👍 
au moins je sais le pourquoi du comment pas de fausse réponse genre quand tu téléphone ça te déco (parce que rien a voir c'est une rotation de proxy) ou te faut un premium (d'ailleurs en premium ça change rien "urlresolver" gère les liens premium du peux que je l'ai utiliser j'ai pas vu trop de différence pas vu la limite de temps juste au lancement quand il trouve pas le fichier changement d'ip et c'est repartit ) (bon premium c'est bien aussi je suis pas 30 balles près et plus d'erreur de lancement)
une dernière question si c'est trop compliqué a gérer par vstream  (ou et trop lourd je comprends bien que python et kodi on des limites  )

Une fois le liens envoyer c'est bien kodi qui gère le buffer ou Vstream?

(vu que ce dernier ce rappel l'endroit ou il c'est coupé et peux reprendre ce que kodi ne sais pas faire avec .strm ou plutôt que par playlist)

merci pour ta réponse 
et dsl pour TmpName (je peux comprendre qu'il doit en avoir marre de gérer des message ou tous le monde ce pleins et réclame  sans même chercher comme si tout étais dut...mais faut pas mettre les gens dans le même panier)
je peux me mettre a ça place mais lui a ma place il aurai fait quoi? (on va dire 50 Tmpname  50 moi )

**Comment by Arias800** [comment]
Content que tu le prenne comme ça ^^ 
Il me semble que c'est vstream qui gère le buffer mais comme tu la dit il y'a des limite en particulier avec kodi après urlresolver comme dit dans l'addon ce n'est pas nous qui le geront c'est juste un supplément que je utilise pas pour ma part mais qu'il n'y est pas de limite a urlresolver c 'est normale car c'est un resolver utilisant des debrideur après je ne dit pas que ce ne sera pas faisable mais par exemple quelqu'un qui utilise uptobox comme moi en version gratuite si il arrive a la limite pas que la reco automatique boucle l'envoi dans une espèce de boucle infini ^^

**Comment by ouaisouais** [comment]
ok je vois mieux
et c'est aussi vstream qui crée la playlist avec le  temps déjà lu quand le fichier plante ?(ce qui permet la reprise)
je pense que oui 
Maintenant a voir si c'est facile d'ajouté une fonction automatique au moment de la creation  de la playlist pour la relancé automatiquement 
sinon tu me parle de la boucle infini en gratuit mais en premium la reprise de fichier devrait ce faire si on la redemande au bon moment?
qu'en penses-tu

**Comment by ouaisouais** [comment]
avec urlresolver je me doutais bien qu'il passait par des débrideurs et que du coup pas moyen de changer d'ip vu que le débrideur en général débride des liens pour une ip pendant un temps dédié.

**Comment by Arias800** [comment]
Oui en théorie apres la pratique ça peu changer

**Comment by LordVenom** [comment]
Non il ta pas envoyer boulet, mais moi je le fait, content pas content je m'en fous.

**Comment by TmpName** [comment]
Lol, bon j'ai rate des trucs, mais pour rappel Vstream ne gere rien du tout.
Vstream recupere une url, la passe au player de kodi et attend que le player lui repasse la main, entre les deux, il ne voit rien du tout.
C'est le player de kodi qui gere les marche avant, les stops, les formats video et le reste.

**Comment by LordVenom** [comment]
Non mais il est BAN y a des jours comme ça faut pas déconné.
