### ISSUE TITLE
Recherche visuelle par genres

### ISSUE THREAD

**Issue by Nux007** [Kodi-vStream/venom-xbmc-addons#1945]
Bug recherche par genres, 
Un clic sur la page suivante, rend inactif le genre sélectionné, par exemple 

`Recherche visuelle ->  Séries (genres ) ->  Kids`
La page 1 donne bien des animés pour les enfants, mais la page deux et les autres donnent une liste de séries pour ados / adultes

J'ai aussi testé avec 'Séries (genres) -> News'  et même constat.
Désolé, j'apporte pas toujours de bonnes nouvelles lol.

**Comment by LordVenom** [comment]
Dans la recherche visuelle? à oui ça c'est pas normal je regarderais ça merci.

**Comment by Nux007** [comment]
Ouep, dans la recherche visuelle, je vais essayer d'avoir plus d'infos.

**Comment by Nux007** [comment]
Voilà un log avec tes messages debug activés juste avant le point d'entrée 

h ttps://pastebin.com/ptFySH6d

**Comment by Nux007** [comment]
C'est bon, j'ai trouvé, je corrige et je fais un pull request
