### ISSUE TITLE
Section recherche Zone-Telechargement.ws ne marche pas

### ISSUE THREAD

**Issue by DoMiiiSSS** [Kodi-vStream/venom-xbmc-addons#1948]
Bonjour,
J'ai pour habitude d'utiliser Zone-Telechargement.ws  sur Kodi, mais malheureusement la section recherche ne marche pas sur cette source.
Avez-vous des infos pour mon problème ?
Par avance merci

**Comment by Arias800** [comment]
Fix par mes soins il y a quelque jour https://github.com/Kodi-vStream/venom-xbmc-addons/commit/f70b80e3b500b2d6ba4c4c6a5cb58428770768a5

**Comment by DoMiiiSSS** [comment]
Merci pour ta réponse rapide Arias800.
En espérant que la prochaine mise à jour prenne en compte ta modif

**Comment by TmpName** [comment]
Ma faute, je lance la MAJ dans  10mn.

**Comment by FloRidaBzH** [comment]
Bonjour à tous ! Pour ma part le problème est toujours existant sur les différents supports que j'utilise. Au cas où si le problème était censé être résolu... Merci pour votre taf en tout cas !

**Comment by Arias800** [comment]
Dans la prochaine maj car j ai la modif mais elle est pas passe dans cette maj si tu veux changer le fichier manuellement il suffit de remplacer www. par ww1. dans URL_MAIN

**Comment by FloRidaBzH** [comment]
Alors étonnement, sur mon ipad, il m'a proposé une mise à jour tardive sur les coups de 22h30. Cela a l'air d'avoir eu un effet positif car j'ai à nouveau la fonction rechercher opérationnelle. Je précise que j'avais procéder à un nettoyage complet en passant par les outils de vstream. D'ailleurs c'est après cela qu'il m'a proposé une MAJ. Si j'ai le temps, je vais tenté la même chose sur les autres appareils.

**Comment by TmpName** [comment]
La MAJ est proposee aleatoirement tout les 3 jours, donc c'est normal que tu ne l'ai pas forcement le jour meme.

**Comment by FloRidaBzH** [comment]
Petit retour et je confirme suite à la MAJ que vous avez fait remonté pour ma part cela fonctionne à nouveau. Merci aussi car avec discussion j'ai 0u découvrir la partie outil de vstream. J'avais un soucis avec url resolver qui a été grâce à ça.

**Comment by DoMiiiSSS** [comment]
Merci pour la MAJ, Ça remarche impeccable sous Android.
