### ISSUE TITLE
Aide pour terminer cineiz

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#1954]
J'ai (presque) terminer cineiz. Je n'affiche pas les hosters. c'est du levideo.
Mon fichier [ici](https://gist.github.com/razorex/6f001048a94af156cdf136b2aebe2a51).

merci pour votre aide

**Comment by TmpName** [comment]
Heu ...
J'ai voulu tester sur le site "trauma" et j'ai un ecran noir a chaque fois, impossible de lancer une video.

**Comment by TmpName** [comment]
Ton code marche tres bien.
Fallait juste decoder le lien une fois de plus 
https://pastebin.com/DH0ZZESD

**Comment by razorex** [comment]
merci @TmpName. Encore un souci le premier lien est "en clair" sur la page.

**Comment by TmpName** [comment]
Heu la j'ai pas compris ?
Le premier lien de la liste ?

**Comment by Arias800** [comment]
le 1er lien n'a pas besoin de requete post

**Comment by razorex** [comment]
Exact @Arias800

**Comment by TmpName** [comment]
Lol, ben wé mais je vais pas faire une procedure differente juste pr 1 lien. C'est pas plus simple comme ca ?

**Comment by razorex** [comment]
je n'ai rien contre. faut juste que je tente de corriger en prenant a partir du lien 2 (hosters, link).
