### ISSUE TITLE
Est ce que c'est possible

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#1955]
Bonjour à tous,

Je me permets de vous poser une question car j'ai pas trouvé la réponse sur google ou alors j'ai mal chercher, bref. 

Je vous pose donc la question est ce que c'est possible de dire vstream de lancer le film, la série ou le documentaire quand la barre de lecteur soit grise qui pour moi doit être la mise en tampon du moins je crois (voir l'image ci dessous).

![capture vstream](https://user-images.githubusercontent.com/16462265/36340503-9e729d5c-13de-11e8-970c-8776d35f325c.JPG)

Juste pour info voici sur quoi tourne vstream : EMISH X810 Andoird TV Box, Game Player, 4 K * 2 K Rockchip 3368 64bit Octa noyau DDRIII 2 GB, eMMC Flash 16 Go, DirectX Support Reproduction 9,3 vidéo pour la moisissure multiple, argent et sur un pasberry PI 3B.

D'avance je vous remercie.
Bien à vous
Patrice

**Comment by Arias800** [comment]
Vstream sert juste a donné le fichier qui doit être lu par Kodi et c'est Kodi qui s'occupe du reste et oui la partit grise c'est la mise en tampon (mémoire ; buffering comme tu veux )^^

**Comment by gituserfr** [comment]
ca ce fait du advancedsettings.xml.

**Comment by patoche2025** [comment]
Merci pour vos réponse @Arias800 et @gituserfr  advancedsettings.xml c'est un addon ou un fichier à créer et ajouter dans le kodi?

**Comment by TmpName** [comment]
https://kodi.wiki/view/Advancedsettings.xml

**Comment by patoche2025** [comment]
Un tout grand merci @TmpName je vais aller voir ça!

**Comment by johngf** [comment]
normalement la lecture démarre automatiquement des que le tampon est a 100% et pas avant

**Comment by patoche2025** [comment]
Bonjour @johngf moi j'ai pas ça et comme tu peux le voir sur l'image le tampon ce fait pas à 100% la lecture se met en route quasi tout de suite. 

Est ce que c'est une option à cocher ou c'est grâce avec advancedsettings.xml

**Comment by johngf** [comment]
quand je dis 100% c'est a dire 100% de la taille tu tampon 
de base sur kodi ça dépend de la résolution de la video il me semble de 7,50 mo a 15mo
si ça ne démarre pas automatiquement c'est que le tampon n'est pas pleins (débit internet insuffisant ou débit du serveur d'ou proviens la vidéo insuffisant)
essaie d'augmenter la taille du tampon dans un advancedsettings.xml ou de choisir le même film avec une résolution inférieur
souvent les hébergeurs ont du mal en 720 ou 1080p
