### ISSUE TITLE
DDL Island et Zone Tele.ws 

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#1956]
Salut à tous
Je sais pas si j'ai manqué quelque chose mais chez moi les liens de DDL ne s'affichent pas 
et c'est impossible d'effectuer une recherche sur ZT 
Je suis en version 0.5.9

**Comment by Arias800** [comment]
Pour zt c'est corrigé sur dans la beta il faut que la maj passe

**Comment by lebigboss** [comment]
@Arias800 Cool, déjà une bonne nouvelle.
Je vais tester la bêta

**Comment by lebigboss** [comment]
Je viens de tester la bêta qui est toujours en 0.5.9 et les recherches sur ZT fonctionnent, 
Mais sur DDL ça n'affiche toujours pas les captchas . Vous avez le même problème ?

**Comment by Arias800** [comment]
je regarde la ^^

**Comment by Arias800** [comment]
Nouvelle version sur la beta ^^

**Comment by lebigboss** [comment]
@Arias800  J'ai DL la nouvelle beta et ça fait les 2 mêmes problèmes
plus de recherche ZT et impossible d'ouvrir un lien DDL

**Comment by Arias800** [comment]
Pourtant les fichier sont les bon sur le github :/ Au pire faut attendre la prochain maj qui passe tout le 3 jour il faut juste que @TmpName pense a prendre mes modif cette fois :p

**Comment by sam5558** [comment]
Salut tout le monde, je suis nouveau.
J'ai aussi le pb avec ZT en 0.5.9 - Je sais que je vais passer pour un con mais comment on passe en BETA ? Merci

**Comment by Arias800** [comment]
Et tu coup ca refonctionne ?

**Comment by sam5558** [comment]
@Arias800 en fait, avant de passer à la version Beta je pouvais même pas accéder au contenu de ZT, avec la Bêta je peux accéder à la 1ère page du contenu. Le problème maintenant c'est que le contenu est là mais quand je sélectionne un film/animé ca me donne rien! (retour à la case départ quoi héhé)
Et pour le bouton next (pour afficher les autres pages) il ne fonctionne pas lui aussi. 

Faudra donc attendre la 0.6 . Quelqu'un a une idée de la date de sortie de la prochaine MAJ du plugin?

**Comment by Arias800** [comment]
Il ont du faire une modif je te tiens au courant

**Comment by Arias800** [comment]
Bon bah tout la partie dl protect a refaire ...
