### ISSUE TITLE
Probleme avec les docu

### ISSUE THREAD

**Issue by leductdh** [Kodi-vStream/venom-xbmc-addons#1960]
Salut Razorex Kodigoal Chataigne et Arias
Il semble avoir un trouble avec documentary.

documentary-Documentary (genre) - Les docus (peu importe le choix)
Plusieurs liens nouveaux non fonctionnel. temps d'attente long ou je sait pas mais
si on revient en arriere dans kodi parceque on en a marre d'attendre...Ca crash kod

Resultat le meme sur trois installation de kodi. 2 androide et un windows.

Pourtant ça marchais bien il y a quelques jours,

J'adore votre addon... Vous avec les meilleurs Docu.

Merci les gars

Rémi Dallaire

Quebec Canada

**Comment by Arias800** [comment]
Nouvelle version sur la beta https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/les_docus.py

**Comment by leductdh** [comment]
J'update vstream 5.9 . meme resultat. Desolé je sais pas . 
J'essaie les docu n'importe quel. le (working( roule et roule sans arret. si J'arrete et revient en arriere
Kodi crash  ou mieux il blocke he je suis obloger de redemarrer Kodi.

**Comment by Arias800** [comment]
Il faut passer par la https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream ou installez le fichier manuellement car on refait pas une version de vstream a chaque modif (une nouvelle version apparait tout le mois )

**Comment by domocan-koala** [comment]
Merci Arias800, ton dernier lien m'a débloqué.  @+

**Comment by LordVenom** [comment]
Hors sujet : @domocan-koala  j'adore ton avatar XD
