### ISSUE TITLE
Probleme Bande Annonce 

### ISSUE THREAD

**Issue by fanfanderson** [Kodi-vStream/venom-xbmc-addons#1961]
Bonjour a toute la communauté Vstream,
Les bandes annonce ne fonctionnant plus(version stable) j'ai réussi hier a en lancé une, en allant dans information j'ai cliqué sur "Casting" et ensuite j'ai réussi a lancer la bande annonce, impossible de le refaire depuis. 
Y'a t'il une vrai solution?
Merci
PS: Super taf Venom, un grand merci.

**Comment by Arias800** [comment]
Je vient de teste et ca marche chez moi essayer par la 
![kodi](https://user-images.githubusercontent.com/24809312/36534806-e5f82b32-17c7-11e8-8a29-6e73ddd10fa1.PNG)

**Comment by fanfanderson** [comment]
c'est avec cette méthode que j'essaye mais en vain, avant j'avais directement bande annonce dans ce menu maintenant il faut faire information puis bande annonce mais ça me relance sur le mur des films.

**Comment by fanfanderson** [comment]
Petite précision je suis sur Kodi sous Windows

**Comment by Arias800** [comment]
moi aussi je suis sous windows un exemple de quelque chose qui ne marche pas ? (nom + site ou le trouve)

**Comment by fanfanderson** [comment]
j'utilise essentiellement Z-T comme sources et aucunes bandes annonce ne se lancent, hier soir j'ai fait une manip et j'ai réussi une fois(Full metal alchimist) mais j'ai jamais réussi depuis.

**Comment by Arias800** [comment]
Dans zt va dans films (dernier ajout) mets le curseur sur nos année folles ouvre le menu menu et fait bande annonce normalement ca doit marché

**Comment by fanfanderson** [comment]
j'essayerai ce soir je suis au boulot je vais tester tout ça merci pour ton aide et je te donnerai le résultat ici ;)

**Comment by Arias800** [comment]
D'acc

**Comment by fanfanderson** [comment]
re , je viens de tester en réinstallant Kodi sur un autre pc tout fonctionne , et surtout j'ai directement "bande annonce" , plus besoin d'aller dans information.
Certainement un problème dans un fichier conf je vais regarder tout ca.
Merci en tout les cas.

**Comment by Arias800** [comment]
D'acc
