### ISSUE TITLE
aucun resultat de recherche sous voirfilms

### ISSUE THREAD

**Issue by nickspaow** [Kodi-vStream/venom-xbmc-addons#1967]
coucou quand je fais des recherche dans longlet visual search je ne trouve aucun lien sous la source voirfilms ( celle que je prefere) alors que je survole la source et trouve la fameuse serie ou film que je cherche mais cest plus long car je doit cherche manuelement.

jai fais un test jai ete sous search jai ecrit '' Daredevil'' jai eu un resultat dans voirfilms jai fais le mm test avec visual search encor ecrit dans recherche un serie '' Daredevil'' et sa me dit ya aucun resultatdans voirfilms je vais voir dans la source directement et je trouve manuellment ''Daredevil''

donc voila je veut savoir pk en recherche normal je trouve un resultat mes en visual search je ne trouve rien sous cette source jai fais plusieur test avec differante serie et film et c la mm chosse chaque fois

**Comment by TmpName** [comment]
Je me souvient avoir le probleme, mais la je viens de tester pour la meme recherche "daredevil" et j'ai eu 2 resultats a chaque fois pour ce site.
