### ISSUE TITLE
UptoBox (Zonetelechargement) HS

### ISSUE THREAD

**Issue by camelone** [Kodi-vStream/venom-xbmc-addons#1969]
Bonjour l'équipe!

Depuis la mise à jour d'aujourd'hui, la recherche sur zt fonctionne à nouveau. Merci pour votre taf! C'est ensuite que rien ne va plus.. peu importe le film choisi, lorsque l'on choisi la source Uptobox, au lieu de proposer de regarder en direct ou en streaming, il affiche le nom du film suivi de Facebook (???) et impossible de lancer le film. Pouvez-vous tester? Un grand merci pour votre travail... Sans vous, qu'est ce qu'on s'ennuyerait!!

**Comment by Arias800** [comment]
Oui zt ne marche pas car il ont change la manière de fonctionnement de DL protect et du coup nous on doit refaire cette partie et pour le moment moi je n'ai pas trouvé comme faire donc j'espère quelqu'un d'autre poura jeté un œil

**Comment by camelone** [comment]
Mais on pouvait qd même regarder en streaming et ça marchait... par contre pas en direct. Les deux méthodes utilisent le dl protect?

**Comment by camelone** [comment]
Ça marchait juste avant la mise à jour.. je vais voir si j'ai un backup...

**Comment by TmpName** [comment]
La nouvelle methode est pas plus simple ?
Elle a l'air de fonctionner sans cookies ?
Juste avec la valeur "continuer" en format POST multipart ?

**Comment by TmpName** [comment]
Essaye ce code

https://pastebin.com/6Ka1ZjSf

Sur Navigateur Boundary est du type "-----------------------------16151341432470"
et celui du code "--MrN39GIPbdCUxay355TbP6FNeONqdH"
Mais je ne pense pas que cela pose probleme.

Tu peux comparer sur Firebug les requetes sont exactement pareil (a part que sur Vstream ca s'affiche dans les log au lieu de lancer la requete)

Apres je pense qu'il y a une astuce, ce serait trop facile sinon, ca marche avec les cookies desactive, il faut peut etre charger les 2 pages avec un timer, ou il y a un lien a la con qui bloque tout si pas charge.

**Comment by Arias800** [comment]
Au passage il y'a un code JS de recaptcha qui est apparut dans le code mais a mon avis il est pas encore actif donc a surveiller

**Comment by Ovni-crea** [comment]
je viens de faire la dernière mise a jour de vstream et j'ai constaté aucun bug entre zone telechargement et les liens uptobox

**Comment by KiliK150** [comment]
Pareil que @Ovni-crea . 
J'avais ce bug début de la semaine dernière mais depuis la maj de samedi , je n'ai plus aucun problème de ce genre .  Tout les liens sur ZT fonctionnent parfaitement à part la recherche.

**Comment by Arias800** [comment]
Ça devait être un teste pour une futur version wait and see Par contre la recherche je m'en occupe vendredi après-midi ^^

**Comment by dbast57** [comment]
Bonjour à toute l'équipe,
Je suis utilisateur de vstream avec  une box android tv nvdia
L'incident #1953 n'est pas résolu dans mon cas,
J'ai un compte uptobox prémium, et depuis ZT le message est toujours "fichier introuvable"
Vous donnez des astuces dans l'incident #1953, mais je n'y comprend pas grand chose (je suis plutôt novice)
Pourriez vous m'expliquer pas à pas ce qu'il faut faire pour résoudre ce problème
Merci beaucoup

**Comment by Arias800** [comment]
Attend la mise a jour auto

**Comment by dbast57** [comment]
Merci de ta réponse, mais vous parlez de version beta ? puis je l'installer sur ma box ?

**Comment by Arias800** [comment]
Oui bien sur ça s'installe comme n'importe qu'elle version

**Comment by dbast57** [comment]
merci Puis je avoir le lien de téléchargement

**Comment by Vidalcris** [comment]
Pas de problèmes chez moi, à part la recherche qui ne fonctionne pas.

**Comment by Arias800** [comment]
je te passe ça dbast57 mais avant je m'occupe de zt ^^

**Comment by akatimike** [comment]
Bizarre.... la plupart me donne no information et uptobox me donne ça...
https://ibb.co/fxZksn
Ça c'est avec celui que arias800

**Comment by camelone** [comment]
Exactement pareil que akatimike.. Malgré la mise à jour reçue hier.. J'ai essayé une dizaine de films et à chaque fois ce lien suivi de "Facebook".

**Comment by Arias800** [comment]
Oui parce qu'il font des modif pour une nouvelle version de dl protect pour le moment elle apparait de manière aléatoire je cherche

**Comment by camelone** [comment]
courage à toi Arias800 et encore merci pour votre dévouement à tous!

**Comment by Arias800** [comment]
il se peux que ce soit de ma faute en partit >.< quelqu’un cette version https://pastebin.com/raw/j1wskL5Y ?

**Comment by camelone** [comment]
Impossible là tout de suite mais je veux bien tester tout à l'heure..

**Comment by Arias800** [comment]
D'acc j'attends ton retour 👍

**Comment by camelone** [comment]
Avec plaisir.. Si je peux apporter ma toute petite collaboration (n'ayant aucune notion de programmation), je n'hésite pas!

**Comment by akatimike** [comment]
J'ai compiler avec la source que tu a donner arias800 et toujours le même probleme.. :(

**Comment by akatimike** [comment]
Btw voici le lien avec la source que tu nous a partager : https://drive.google.com/file/d/1TGe4gS9RMS0VfNwBfAWBN0k9uT-g35H_/view?usp=drivesdk

**Comment by Arias800** [comment]
Tu n'a pas prit le fichier du dessus ^^ je te prépare une version toute faite ^^

**Comment by Arias800** [comment]
Normalement cette fois c'est le bon x) https://drive.google.com/file/d/1mNsALBhFjseXAOQx8AQLdcCsgbJOMhjz/view?usp=sharing

**Comment by akatimike** [comment]
Pourtant j'ai vraiment utiliser de .py que tu avait fournie j'ai compiler entre 2 job avec mon cell par exemple pt fait une erreur bref ça fonctionne bien! J'ai quelque lien encore aucune information prob lien mort a voir plus tard merci ! :)

**Comment by Arias800** [comment]
C'est normal vu que c'est moi qui a merdé ^^

**Comment by dbast57** [comment]
Je vous remercie beaucoup pour votre travail !!

Ça refonctionne à merveille !!

:)))))))

**Comment by Vidalcris** [comment]
J'ai du mal à suivre desolé .. c'est la recherche qui fonctionne c'est ça ?
Est ce que je devrais aussi faire la maj ? :)

**Comment by dbast57** [comment]
Mon message de félicitation concerne :+1: 

"Bonjour à toute l'équipe,
Je suis utilisateur de vstream avec une box android tv nvdia
L'incident #1953 n'est pas résolu dans mon cas,
J'ai un compte uptobox prémium, et depuis ZT le message est toujours "fichier introuvable"
Vous donnez des astuces dans l'incident #1953, mais je n'y comprend pas grand chose (je suis plutôt novice)
Pourriez vous m'expliquer pas à pas ce qu'il faut faire pour résoudre ce problème
Merci beaucoup"

**Comment by Arias800** [comment]
Normalement ca fixe la recherche et ma connerie ^^

**Comment by Vidalcris** [comment]
Ok je vais l'installer alors, Merci ;)

**Comment by camelone** [comment]
Est ce que ça fixe aussi le fait de pouvoir regarder en direct et non en streaming?

**Comment by Arias800** [comment]
Ca depends si c'est sur la version streaming de zt oui si c'est uptobox non ^^

**Comment by camelone** [comment]
Arias800, il n'y a que ceux qui ne font rien qui ne font pas de conneries 😉 Dans ton cas, tu es tout pardonné car niveau réactivité t'es au top, VOUS êtes au top!

**Comment by Vidalcris** [comment]
Je viens de l'installer et tout fonctionne, Direct et recherche.

**Comment by camelone** [comment]
Et c'est un problème chez uptobox ou chez ZT?

**Comment by camelone** [comment]
Ah super Vidalcris, je vais alors tester ça..

**Comment by Arias800** [comment]
j'ai juste modifié zt car (pour ceux que ca intéresse de savoir ou était ma connerie) le script redirigeait tout le temps vers streaming n'ont pas vers le direct comme d'habitude ^^

**Comment by camelone** [comment]
Je viens seulement d'avoir le temps de tester... Super! TOUT refonctionne. La recherche, le streaming ET le direct.. Bon travail Arias800. Et vive VSTREAM!
