### ISSUE TITLE
VStream Dossier vide avec "...."

### ISSUE THREAD

**Issue by aldoranx** [Kodi-vStream/venom-xbmc-addons#1970]
Hello,

Depuis des que je recherche un film ou une série sur VStream la série apparaît bien mais une fois que je clique afin de pouvoir lancer l'épisode le dossier est vide avec "..." uniquement.

J ai aussi un message d'erreur "Erreur Connexion Failed (405)

Mon repo est à jour 0.0.3
Add-on 0.5.9

Merci de vos retour

Aldo

**Comment by razorex** [comment]
Quel site??????

**Comment by aldoranx** [comment]
Quand je choisis une série n'importe laquelle j ai la fenêtre 

VStream
Chargement 1/28 qui apparaît à cette étape j ai un premier message d erreur qui apparaît l'erreur connection failed 405

Ensuite une fois arrivé à 28/28 la je n'ai plus rien dossier vide avec ... de suspension donc je pense que cela est pour tous les sites.

Hier j'ai desinstaller et réinstallé VStream sans succès

**Comment by aldoranx** [comment]
Ps

Le message connexion failed error 405 apparaît à 2/28 "StreamingK"

**Comment by LordVenom** [comment]
Click sur recherche serie complete, vStream à du mal avec les saisons.
