### ISSUE TITLE
Click Open

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1977]
Il ont effectué une modif a l’intérieur du JuicyCode en rendent le regex qui le parse non fonctionnel et en ajoutent des | a l’intérieur . Et je bloque au niveau des | car je ne sais pas ou les remplacé ^^

**Comment by TmpName** [comment]
C'est quel site qui utilise ca deja ?

**Comment by Arias800** [comment]
Film illimite

**Comment by TmpName** [comment]
Tu aurais un exemple ?
Je viens de tester pr le premier film "call me by your name" et le fichier hoster hoster tourne bien, pas vu de caracteres a la con dedans.

A part la ligne media = aResult[1][0].replace('+', '') qui ne vire pas les ".

**Comment by TmpName** [comment]
Tu aurais un exemple ?
Pas vu de caracteres a la con, cf https://pastebin.com/TmX2APQu
J'ai teste avec le premier film de la liste.

A part peut etre un bug a la ligne media = aResult[1][0].replace('+', '') qui ne vire pas les ".

**Comment by Arias800** [comment]
Ok ça remarche bizarre
