### ISSUE TITLE
Liens uptobox- ddl-island / ZT

### ISSUE THREAD

**Issue by Kiribou** [Kodi-vStream/venom-xbmc-addons#1978]
Bonjour,
Dans un premier temps je voulais vous remercier pour votre travail :). 

Depuis les dernières maj, je n'arrive pas à charger les liens uptobox (abo premium) 
Il se charge 2 sec puis affiche : aucune information
Je suis sur un raspberry pi. 
J'ai essayé plusieurs versions dont la 0.5.9 et la 0.6.0.
Auriez vous une solution ? 

J'ai testé la solution du ticket 1969 sans succès. 

Merci de votre aide

**Comment by Arias800** [comment]
La le problème doit venir d’ailleurs tu a quel version de kodi ?

**Comment by Kiribou** [comment]
Version 17.3 de kodi

**Comment by Arias800** [comment]
Peut tu passez les log via upload log qui se trouve dans outils dans les parametre de vstream

**Comment by Kiribou** [comment]
https://slexy.org/view/s2ZXTQMqnd

**Comment by Arias800** [comment]
Il faut effectué le bug pour que je vois quelque chose dans les log la j'ai que le démarrage de vstream et de kodi ^^

**Comment by Arias800** [comment]
Sur dll-island tu a le captcha qui apparait ?

**Comment by Kiribou** [comment]
Pas du tout, je n'ai plus de captcha.
Je valide le lien uptobox et le message aucune information s'affiche.

**Comment by Arias800** [comment]
Donc tu n'a pas la toute dernier version de dl island j'ai fait la modif il y a environ 7 heure donc installe la beta et dit moi si ca change quelque chose https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by Kiribou** [comment]
Super ça fonctionne. 
Te un chef, merci beaucoup ;)

**Comment by Arias800** [comment]
Tant mieux 👍

**Comment by Kiribou** [comment]
Depuis la dernière maj le problème est revenu. J'ai remis la version que tu m'as filé (la version bêta) et ça fonctionne

**Comment by LordVenom** [comment]
Pourtant la mise a jour a était envoyer y a 7jours par @TmpName c'est le bon fichier sur beta ?

**Comment by Arias800** [comment]
Moi aussi j'ai eu ce bug juste après la maj maintenant c'est bon car vstream changeait le fichier même si il était bon

**Comment by Kiribou** [comment]
J'ai tjrs le bug alors que j'ai fais la maj, pas de captcha

Merci de votre aide

**Comment by akhas113** [comment]
Bonjour,
J'ai un compte uptobox premium et lorsque je suis sur vstream et que je clique sur zone téléchargement et met un film il y'a écrit authentification raté et je ne peu pas voir mon film.
Avez vous une solution s'il vous plait ?

Merci de votre aide
