### ISSUE TITLE
DDL Island sur version 0.06

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#1979]
Salut à vous
Déjà merci pour votre job, à chaque mise à jour je suis en kiff
Je veux juste signalé que DDL Island ne fonctionne pas chez moi, j'ai peut être raté quelque chose ?
C'est mon site préférer pour les séries car c'est le seul à proposer mes séries en 1080p

Je viens prendre des nouvelles

**Comment by Arias800** [comment]
La toute deniere version n'est pas dispo dans la 0.6.0 voila le lien ci tu veux faire la modif manuellement https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/ddl_island_su.py

**Comment by lebigboss** [comment]
@Arias800  Mais DDL a modifié le Captcha ?

**Comment by Arias800** [comment]
il avais fait une modif au niveau des cookies donc oui ça bloque au niveau du captcha si on n'a pas la dernière version

**Comment by lebigboss** [comment]
C'est bon ça fonctionne.  Merci 🖒🖒

**Comment by Arias800** [comment]
Nickel donc je ferme l'issue
