### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Abeillefan** [Kodi-vStream/venom-xbmc-addons#1980]
Hi, Vstream is working now ? All sources doesn't work for me. 
Thank you 😊

**Comment by Abeillefan** [comment]
Someone ????

**Comment by LordVenom** [comment]
French please

**Comment by Abeillefan** [comment]
Oups. En plus je parle français. Presque tout est en anglais, c'est un réflexe. Désolé

**Comment by TmpName** [comment]
Oui, oui il fonctionne.
