### ISSUE TITLE
Lien filmsvostfr

### ISSUE THREAD

**Issue by lecorniste** [Kodi-vStream/venom-xbmc-addons#1981]
Bonjour.
Merci pour le travail incroyable qui est proposé.

j'écris pour un petit problème. La source filmsvostfr propose toujours ses liens mais aucun ne marche sur Kodi. Pourtant sur le site sur navigateur, les streams marchent parfaitement...

Je pense que j'ai fais toutes les MAJ pourtant. 

Merci d'avance.

**Comment by TmpName** [comment]
Je viens de tester "disaster artist", openload ok, stremango ok. mystream ok, thevideo marche pas, mais sur navigateur non plus chez moi.

Flashx a du changer, uptostrm non dispo sur le site non plus.
