### ISSUE TITLE
Alluc c'est finit

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#1982]
Le site alluc a finalement fermée ses porte après 13 ans . L'API restera fonctionnel jusqu'à la fin du mois .

**Comment by ebs111** [comment]
hi,
you can use the "http://pron.tv/" it still have all of alluc database and porn

**Comment by lebigboss** [comment]
Nooooooooonnnnn !!!!!! 
C'est sur ? Parce qu'on a toujours accès au site

**Comment by Arias800** [comment]
Voila le message sur leur site "The all_c search engine has been discontinued.
After 13 years of alluc, we decided to take a break and focus on other projects.
Over this last decade alluc served more than one billion unique users in total and we would like to thank all of you for your support over the years." . Après pour pron je sais pas faut voir avec @LordVenom ^^

**Comment by lebigboss** [comment]
Dégoûté

**Comment by LordVenom** [comment]
Supprimer de vStream
