### ISSUE TITLE
Real Debrid URL Resolver

### ISSUE THREAD

**Issue by Nostalgeeek** [Kodi-vStream/venom-xbmc-addons#1988]
Bonjour,

Je n'arrive pas à faire fonctionner mon débrideur (real debrid) sur vstream! J'ai essayer sur une version fraiche et quand je veux aller sur configurer url resolver j'obtiens une erreur.

J'ai ensuite installer la dernière version d'url resolver sur tvaddons et j'arrive à rentré dedans et à le configurer mais quand je vais dans vstream et que je lance un film ou autres celui ci ne se lance pas et j'ai le message pas de prémium etc... Alors que j'ai bien ré-autorisé mon compte! Je sèche si vous avez une solution!

Merci

**Comment by yas06** [comment]
Salut j ai le même problème j'ai real debrid  aussi depuis la dernière mise à jour 
Je sais pas où ça coince je cherche j ai fais comme toi tout reconfigurer mais pareil

**Comment by FloRidaBzH** [comment]
Bonjour ! Si ça peut rassurer je suis dans le même cas. Cela a commencé des dimanche soir le problème. Je n ai accès qu'aux liens Uploaded. Les autres comme 1fichier sont en violet mais dans la valise urlrslv devant... j'ai trouvé une maj pour url mais ça ne change rien.

**Comment by Arias800** [comment]
Sûrement un problème du cote de real-debri

**Comment by FloRidaBzH** [comment]
Oui probable mais en général quand il y a une coupure de ce côté je vais sur le site de realdebrid et il y a une mention de perturbation réseau avec tel ou tel service. Hors il n'y avait rien...

**Comment by yas06** [comment]
Salut retour du bug ça fonctionne plus

**Comment by lebigboss** [comment]
Moi je suis chez Alldebrid et juste pour dire qu'il y avait le même problème l'année passée et ça venait du faite que Alldebrid avait changer l'API de leur site donc ça ne fonctionner plus, il fallait attendre une maj de urlresolver mais après plusieurs messages reçus,  Alldebrid à remit l'ancienne API.
Voilà si ça peut faire avancer le chmilblick

**Comment by Arias800** [comment]
C'est possible il faudra leur envoyé un mail ^^

**Comment by LordVenom** [comment]
@lebigboss, Oui histoire qui a fait couler beaucoup d'encre voir https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1819

Aprés çi vous avez pas trop de suivis de notre pars voir https://github.com/Kodi-vStream/venom-xbmc-addons et lire **A Savoir!**

> vStream n'est pas affilié avec KODI, URL-Resoler, ou autres services payants,
