### ISSUE TITLE
Webcam streams for Kodi (snow and skying availabilities,...)

### ISSUE THREAD

**Issue by spartrekus** [Kodi-vStream/venom-xbmc-addons#1989]
Hello,

You like skying or maybe watching webcams before travelling somewhere. 
Lift for skying for instance, might be interesting to check first on the webcam.

What about a database of cool areas, upgraded/updated by users directly. 

Would you mind, if you want, if you'd like,... to add on a webcam possibility, simply over CSV database (simple for everyone):

Join us at : https://github.com/spartrekus/webcam-stream-database 
or here !

The plugins might have cool webcam as well. 

We may join developments for amazing Kodi/Venom/.... pluings !

**Comment by TmpName** [comment]
Nice project but Vstream doesn't work on same domain.
I haven't statistic but I think 98% of research on this plugin are french films/series. There is some other sources, but not sure they are often used.
