### ISSUE TITLE
Aide source

### ISSUE THREAD

**Issue by rayan310** [Kodi-vStream/venom-xbmc-addons#1991]
Bonjour à tous, je souhaiterais de l'aide pour la source fullstreaming.pw merci à vous :)
https://pastebin.com/0CBf5nq2

**Comment by Arias800** [comment]
Pour les aide lier au source c'est par ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1971

**Comment by LordVenom** [comment]
MOVIE_HD = (URL_MAIN + '**url**', 'showMovies') #films HD

- ou est declarer url ?
exemple pour l'url http://fullstreaming.pw/films/films-hd/
MOVIE_HD = (URL_MAIN + 'films/films-hd/', 'showMovies') #films HD

oOutputParameterHandler = cOutputParameterHandler()
oOutputParameterHandler.addParameter('siteUrl', MOVIE_VF[0])
 oGui.addDir(SITE_IDENTIFIER, MOVIE_HD[1], 'Films (HD)', 'films_hd.png', oOutputParameterHandler)

Plutot

oOutputParameterHandler = cOutputParameterHandler()
oOutputParameterHandler.addParameter('siteUrl', **MOVIE_HD**[0])
 oGui.addDir(SITE_IDENTIFIER, MOVIE_HD[1], 'Films (HD)', 'films_hd.png', oOutputParameterHandler)
