### ISSUE TITLE
Problème UpToBox

### ISSUE THREAD

**Issue by vic1997** [Kodi-vStream/venom-xbmc-addons#1994]
Les liens "direct" d'uptobox ne fonctionnent plus. On dirait que ça redirige vers Uptostream.
On avait déjà régler ce soucis il y a pas longtemps mais ça a l'air d'être revenu.

**Comment by johngf** [comment]
si tu n'a pas de compte premium c'est redirigé vers upto stream automatiquement a cause du timer de 30 seconde mis en place sur upto box

**Comment by vic1997** [comment]
@johngf J'ai un compte premium c'est ça le problème :/
En plus ça marchait hier soir, j'ai regardé un épisode et quand j'ai voulais passer au prochain ça marchait plus. Ils ont du modifié un truc sur uptobox.

**Comment by johngf** [comment]
si tu n'a la popup du choix entre les deux c'est un probleme d'authentication 
sur le site internet d'upto box quand tu te connecte ça fonctionne

**Comment by Seb1971** [comment]
Bonsoir, je confirme bien qu'il y a un souci avec Uptobox, depuis ce matin impossible de lire quoi que ce sois.  Cela bloque au niveau de l’authentification et pourtant je suis en premium,d'ailleurs même  souci avec 1fichier mais là l’authentification réussi mes la vidéo n'arrive jamais !

**Comment by vic1997** [comment]
@johngf il y a bien la popup du choix, ça bloque l'authentification premium je pense, comme l'a dit @Seb1971 . Voilà une vidéo (vu que c'est plus rapide que d'expliquer) [https://youtu.be/b1EDgJldQQM](https://youtu.be/b1EDgJldQQM)

**Comment by Seb1971** [comment]
@johngf  Mais comment résoudre ce problème d'authentification ?

**Comment by Arias800** [comment]
Normal que tu puisse par lire de vidéo car la connections a ton compte échoue ça soit être un problème au niveaux de la requête post

**Comment by vic1997** [comment]
@Arias800 Ouais mais c'est apparu sans rien avoir touché et pareil pour les autres utilisateurs de vStream.
Ca vient donc de UpToBox le changement, peut-être une nouvelle sécurité ? Parce qu'avec les mêmes identifiants j'arrive bien à m'identifier sur Uptobox et à regarder les films.

**Comment by Arias800** [comment]
Oui le changement vient de chez eux ça c'est quasi ment sur et si tu arrive a te connecté sur leur site ça doit être une modif soit au niveaux des requête (je crois pas que l'on ce sert des cookies) ou alors une toute nouvelle sécurité quelconque

**Comment by vic1997** [comment]
@Arias800 Mince... Bah je suis pas assez compétent pour régler le problème, faut attendre que quelqu'un veuille bien le faire.

**Comment by Vidalcris** [comment]
J'ai vraiment l'impression qu'ils veulent pas qu'on renouvelle nos abo chez uptobox ... En tous cas pour ma part ca risque plus d'arriver ^^

**Comment by Arias800** [comment]
Non il veulent bloquer vstream car on ne leur rapport pas d'argent (n'y via les pub,ni via le minage )

**Comment by vic1997** [comment]
Oui, ils arrivent pas à comprendre que les premium ont déjà payé, justement pour ne pas avoir de pub... Je les comprends pas, j'ai déjà discuté avec eux et ils pensent qu'on les voles en utilisant Kodi alors qu'on a déjà payé le premium...

Personne n'a une idée de où ça coince ?

**Comment by Vidalcris** [comment]
Que dire ... il y'a énormément de gens qui pensent que les regles du moment qu'elles sont établis deviennent juste evidente et indiscutables... En toute logique il y'a aussi des entreprise qui pensent la meme chose et c'est meme largement plus répandu j'imagine.
C'est le cas d'uptobox qui sont donc à mon sens des cons.

**Comment by Arias800** [comment]
C'est juste que les mec pensent qu'a l'argent et sans foute si vous payer ou pas pour eux vous êtes des vache a lait quoi .Mais bon si un jour le cœur leur en dit pourquoi pas trouvé un arrangements ^^

**Comment by vic1997** [comment]
@Vidalcris Je pense pareil que toi. Encore, qu'il aurait bloqué aux personnes ayant un compte gratuit ou sans compte j'aurais rien dis, c'est normal. Mais là bloqué les accès aux premium, faut vraiment être con.

@Arias800 Oui c'est ça, ils pensent qu'à l'argent, mais derrière ils offre aucun service, aucun addon kodi ou application qui permet de voir leur film autre part que sur uptostream...

**Comment by johngf** [comment]
il faut au minimum le contenu htlm de la page de dl sur upto box connecté en premium.
le mieux serai d'avoir un compte pour testé personne a un compte en fin de vie a prêté pour les tests.

**Comment by vic1997** [comment]
@johngf Désolé le mien est tout neuf, et oui ça serait bien un compte d'un mois ou un compte en fin de vie.

**Comment by Arias800** [comment]
Il ont changé la manière de ce connecté maintenant il y a une variable referer qui est dans l'url et en post_data

**Comment by Arias800** [comment]
Quelqu'un peux teste ce fichier ? https://pastebin.com/24tCQAtr

**Comment by vic1997** [comment]
@Arias800 Je test et je te dis ça

**Comment by vic1997** [comment]
@Arias800 Ça ne me dit plus mauvais identifiant, mais ça me dit quand même Fichier introuvable (et même pour les fichiers uptostream maintenant)

**Comment by Arias800** [comment]
Dans un premier temps je voulait savoir si ca te mettait une erreur au niveau de la connection ^^

**Comment by vic1997** [comment]
@Arias800 Ok ^^, bah tu as ma réponse, donc la connexion a l'air de fonctionner, mais les streams ne marchent plus.
GG en tout cas.

**Comment by Arias800** [comment]
Mais enfaite le fichier il est pas bon j'ai fait une faute de frappe dans le fichier qui fait que ca ne marche pas donc retour au point de departs ^^

**Comment by Arias800** [comment]
Bon je sais pas y'a du recaptcha sur uptostream (en version invisble il m'est apparut d'un coup) pour uptobox je sais pas :/

**Comment by vic1997** [comment]
@Arias800 mince, du coup c'est la merde... :(

**Comment by Arias800** [comment]
Bah je suis entrain de réfléchir a un moyen de passer les recaptcha avec l'addon chrome launcher mais ça va prendre un moment et faut chrome quoi :/

**Comment by vic1997** [comment]
@Arias800 Ouais.... C'est la merde, comme j'ai dis xD

**Comment by Arias800** [comment]
Après peut etre qu'il y a quelque chose que j'ai pas vu mais si j'ai tout vu oui x)

**Comment by vic1997** [comment]
@Arias800 J'espère que t'as mal vu alors :D

**Comment by ddav33** [comment]
J'ai le même problèmes, mais hier soir ça a marché un moment le temps de voir une série puis 1h dun film puis ça a coupé de nouveau, voilà un petit retour de bug ci ça peu aidé ! 😕

**Comment by madmocas** [comment]
Moi si le problème est pas résolu je renouvelle pas uptobox je garde juste 1 fichier si on fait tous le même eux vont finir par céder

**Comment by vic1997** [comment]
@madmocas T'inquiètes pas qu'ils vont rien capter.... Faut régler le soucis ici. C'est le seul moyen.

**Comment by Cikai91** [comment]
Bonjour, j’ai remarqué aussi ce problème depuis quelque jours ... c’était tellement pratique.

**Comment by TmpName** [comment]
Le prb c'est que les seul qui cherchent sur le fichier n'ont pas de compte premium.
Il faudrait que quelqu'un ayant des bases en python (et un compte premium)  decommente les lignes 135 a 137 du fichier de @Arias800 et nous fasse passer le resultat (sur windows, car sur les autres systemes il risque d'y avoir des prbs de droit pour le chemin d'acces)

**Comment by Cikai91** [comment]
Arias800 s’il est partant je veux bien lui prêter mon compte pour ses tests.

**Comment by vic1997** [comment]
@TmpName J'ai des bases en python. J'ai décommenté les lignes que tu m'as dis. Et j'ai vérifié dans le fichier (que j'ai créer vu qu'il se créait pas tout seul) mais il n'y a rien après plusieurs tentatives ! (j'ai rallumé en admin, changé de disque dur)

**Comment by Arias800** [comment]
Malheureusement ça risque d'en compliquer pour moi ce week-end donc je pourrai peut être pas bosser dessus :/

**Comment by TmpName** [comment]
Ok, alors pas de bol ^^, si le fichier ne se crée pas mais que le message "Authentification rate" apparait c'est que le script s'arrette a la ligne 127.
Il faudrait donc rajouter plein de ligne de debug dans la partie entre 112 et 127, et enregistrer e.read() de la meme maniere pour avoir le code.

Edit:
En fait ca deconne aussi en compte gratuit, donc je vais pouvoir tester demain si j'ai du temps.

**Comment by vic1997** [comment]
@TmpName Ok super, par contre ça met "Fichier Introuvable" et non pas "Authentification raté"

**Comment by TmpName** [comment]
Ok, autant pour moi, je viens de relire le post, j'avais pas  vu que le dernier fichier fichier de @Arias800 corrigeait le prb, mais chez moi ca charge une page de non authentifié, meme en gratuit, donc je vais peut etre pouvoir tester demain.

**Comment by Cikai91** [comment]
Super TmpName ! On compte sur toi 😂
Ils sont vraiment con chez uptobox ... ça pourrait les aider à vendre leur premium ...

**Comment by Arias800** [comment]
Mon fichier contient une faute de frappe (psot_data au lieux de post_data) qui a l'air de passer si on passe par un hoster mais pas sur mon compte uptobox

**Comment by johngf** [comment]
upto stream fonctionne tres bien meme sans compte pas de captcha

**Comment by Cikai91** [comment]
Oui, sans compte premium ça passe mais on est limité... avec le compte premium message «  authentification raté » et on bascule sur le sans’ premium donc à nouveau limité

**Comment by ddav33** [comment]
On est limité a combien?, j'ai regardés 2x40 mn d une série et plus 30 d
une autre ça donne 110 mn

**Comment by Cikai91** [comment]
Il me semble 120 min

**Comment by TmpName** [comment]
Pas besoin de premium, tu peux faire un compte gratuit, l authentification va rater aussi.
Bon j'ai pas pu finir j 'en suis la https://pastebin.com/uCrrHhUS

En fait le post part sur une page en erreur 302, un cookie est creé a ce moment puis la page est redirigee.
Actuellement sans bloquer la redirection impossible de recuperer le cookie.
La je bute sur le formatage de la requete post.

Si la requete est en get > code 200 page ok
Si la requete en post > code 302 avec cookie+ redirection > code 200

Et la bonne nouvelle, recaptcha ne sert a rien, meme en bloquant les deux site je peux m'authentifier sur navigateur.

**Comment by Cikai91** [comment]
Bon bah c’est une bonne concernant le reCaptcha.

**Comment by vic1997** [comment]
@TmpName Comme je l'ai dis, suite à la résolution des erreurs dans le code, ça m'affiche bien authentification raté.

**Comment by vstreamkodi** [comment]
@johngf Comtpe premium envoyé dans ton gmail machintruc en espérant que tu puisses résoudre le problème.

**Comment by dialka07** [comment]
Comme vous authentification raté depuis quelques jours...en esperant que ce problème se règle rapidement

**Comment by TmpName** [comment]
Nouvelle version https://pastebin.com/wJCP0egw
Elle bloque la redirection (et je sais pas pkoi ca marche maintenant) et affiche le cookie en log.

**Comment by Cikai91** [comment]
Hum ... c’est une bonne nouvelle ? Je m’y connais pas =\

**Comment by dialka07** [comment]
Merci mais ou faut t'il placer le fichier texte ?

**Comment by vic1997** [comment]
@TmpName Ça ne fonctionne pas chez moi. Ça me dit fichier introuvable.

**Comment by johngf** [comment]
de mon coté le soucis et du au 2eme cookie qui est donné au momentde la redirection >>xfss
en cours

**Comment by TmpName** [comment]
lol @vic1997 c'est normal, le code est pas fini, c'est pour le prochain qui va continuer, pour eviter de chercher en double.
Xfss c'est justement le cookie qui s'affiche dans les log avec mon code.

**Comment by vic1997** [comment]
@TmpName Ha ok lol, j'ai cru que t'avais finis :D

**Comment by johngf** [comment]
version qui fonctionne pour ce soir [la](C:\Users\john-Q6600\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\premiumHandler.py) clic droit sur raw enregistrer sous plugin.video.vstream\resources\lib\handler\premiumHandler.py ça le remplacera ou clic sur raw et faite un copier coller

le fichier c'est premiumHander.py

**Comment by vic1997** [comment]
@johngf Yes ça marche niquel !! Pourquoi juste pour ce soir ?

**Comment by johngf** [comment]
parceque le fichier est a optimisé il gere aussi 1 fichier etc.. j'ai pas tous testé plus le temps

**Comment by vstreamkodi** [comment]
C cool mais 1fichier premium ne marche plus avec ce fichier en l'état.

**Comment by Cikai91** [comment]
Merci à l’equipe !! Vous avez assuré ! @johngf et @TmpName

**Comment by JimmyLaurent** [comment]
J'ai codé en parallèle un autre fix, je vous le joins pour les intéressés. Pas sur qu'il fonctionne mieux avec 1fichier mais ça se tente. => [Gist](https://gist.github.com/JimmyLaurent/b28bcca9d419eff474c239e97c0d4c55)

**Comment by vic1997** [comment]
Super, merci à tout le monde @TmpName @johngf @JimmyLaurent

**Comment by vstreamkodi** [comment]
Ok merci à la team vStream et @JimmyLaurent pour leur réactivité. Le dernier fichier @JimmyLaurent fonctionne avec uptobox et 1fichier

**Comment by vstreamkodi** [comment]
Finalement, mon problème n'est pas résolu. Avec mon IP fixe (RED THD), j'ai toujours   authentification raté avec sur liens uptobox (basculement en uptostream 120min) mais quand je connecte le même équipement sur une connexion en 4G par exemple ça fonctionne. Il doit y avoir encore des cookies qui me bloque sur ma ligne fixe (avec ou sans VPN). Pourtant je n'ai pas de problème pour me connecté sur uptobox.com avec un navigateur web.

**Comment by Torped00** [comment]
Bonsoir,

Je me suis inscris sur GitHub uniquement pour vous remercier pour le taf que vous avez fait sur ce sujet meme si la solution trouvé n'est pas perene elle servira. GG les gars et merci :)

**Comment by vstreamkodi** [comment]
Ça fonctionne de nouveau. Pour info, si on rate qq fois son mot de passe sur uptobox.com alors un recaptcha bloque l'authentification sur vStream pendant une certaine durée sur l'adresse IP en question. Si on rate qq fois son mot de passe sur 1fichier.com alors ce compte est bloqué pendant 1 heure.

**Comment by Cikai91** [comment]
Salut est-ce que tu as un compte premium ou pas

**Comment by vstreamkodi** [comment]
Compte premium obligatoire pour profiter pleinement de vStream.

**Comment by Cikai91** [comment]
Ok, j’ai testé hier soir 2 séries c’est passé nickel, après j’ai essayé de voir si l’authentification était réussi, et il y a pas eu de soucis. 
Je testerai ce soir sur des vidéos plus longues

**Comment by johngf** [comment]
quelqu'un d'autre confirme pour 1 fichier normalement il devrait fonctionné avec la modif que j'ai faite hier

**Comment by vstreamkodi** [comment]
Ce dernière mise à jour ne fonctionne pas avec 1fichier -> erreur fichier introuvable

**Comment by Vidalcris** [comment]
Bizzare chez moi ca charge sans jamais lancer le film avec uptobox.. Et ca ne fonctionne plus  du tout sur 1fichier.

**Comment by KiliK150** [comment]
c'est pareil que @Vidalcris , aucun des 2 ne fonctionne... Après ce problème vient peut-être de chez moi,  vue que même uploaded ne marche plus depuis 2-3 jours.

**Comment by Popoffake** [comment]
Bonjour à tous,
je tiens déjà à vous remercier pour tout le travail accompli jusqu'ici.
Quelqu'un pourrait-il me dire quand cette modification sera implantée dans la mise à jour de vstream, parce que je ne sais pas du tout comment le faire manuellement (j'utilise une box androïd) ?

**Comment by Arias800** [comment]
C'est tout les 3 jour les maj des herbergeur et des site (sauf quand @TpmName oublie des fichier :p)

**Comment by Popoffake** [comment]
Arf. Le week-end va être long.^^
J'ai eu une mise à jour hier soir, et mon premium uptobox n'est toujours pas reconnu par vstream... (j'ai découvert le problème quand mon film s'est arrêté au bout de deux heures. A dix minutes de la fin. Vous n'imaginez pas ma souffrance.^^)

Merci d'avoir répondu aussi rapidement.

**Comment by Arias800** [comment]
Ou alors tu peux utilisé ce patch : https://github.com/luluvulcain/vStream-Kodi/releases/tag/Patch

**Comment by johngf** [comment]
si ça fonctionne pas je pense que c'est du a un ancien cookie 
dans ce cas il faut le supprimer ex sur windows AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream le fichier cookie.etc...
@vstreamkodi test 1 fichier avec celui la [ici](https://github.com/johngf/test/blob/master/premiumHandler.py)

**Comment by Vidalcris** [comment]
J'ai supprimé le cookie des que j'ai vu que ca fonctionnais pas hier soir mais ca n'a rien changé :-/

**Comment by johngf** [comment]
la chez moi upto box fonctionne

**Comment by Vidalcris** [comment]
C'est la version que tu a partagé juste au dessus que j'utilise au cas ou : https://github.com/johngf/test/blob/master/premiumHandler.py

**Comment by Popoffake** [comment]
@Arias800 Merci beaucoup, je teste le patch dès ce soir.

**Comment by vstreamkodi** [comment]
@johngf Ce fichier fonctionne avec uptobox et pas avec 1fichier. Celui @JimmyLaurent fonctionne pour les 2.

**Comment by Vidalcris** [comment]
Bon pour ma part c'etait de ma faute ;) Un parametre de uptobox que j'avais changé...

**Comment by Jojo31780** [comment]
Bonsoir. Je suis novice sur Kodi et vstream. Depuis ce matin j ai le message authentification rate lors du demarrage de films sur uptobox. J ai kodi sur un firestick amazon. Je ne sais pas du tout faire la manipulation dont vous parlez plus haut avec premium handler? Pouvez vous m aider? Je vous remercie par avance.

**Comment by Jojo31780** [comment]
J ai un compte premium uptobox. Et jusqu a présent c etait juste parfait cette extension kodi merci !!! Je suis triste ce soir lol...

**Comment by Popoffake** [comment]
Le patch n'a pas fonctionné... 
pire, je n'ai même plus accès à uptostream, maintenant. Quand je clique sur les liens uptobox, plus rien ne se passe.

**Comment by vic1997** [comment]
@Jojo31780 Si tu es sur Windows, tu vas dans C:\Users\UTILISATEUR\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler

Une fois là tu modifies le fichier, tu supprimes tout ce qu'il y a dedans et tu colles ce qu'il y a là : [https://gist.githubusercontent.com/JimmyLaurent/b28bcca9d419eff474c239e97c0d4c55/raw/127da3b5dfa5d7cb7a3361e3fefb902e3af43231/premiumHandler.py](https://gist.githubusercontent.com/JimmyLaurent/b28bcca9d419eff474c239e97c0d4c55/raw/127da3b5dfa5d7cb7a3361e3fefb902e3af43231/premiumHandler.py)

**Comment by benking110181** [comment]
slt c'est ce que j'ai fait mais une fois allez jusqua le choix entre mes fichier et mes dossier si j'en choisi un il m'affiche ensuite aucune information en rouge

**Comment by johngf** [comment]
pour upto box c'est ok , pour 1 fichier je n'y ai pas touché le problème doit être ailleurs.

**Comment by lofrez** [comment]
Bonjour la communauté.

Est ce qu'une âme charitable peut m'expliquer comment faire si je suis sous rasp ?
Depuis mon explorateur Windows, je tape l'adresse de mon IP fixe "Libreelec", j'arrive dans tout les dossiers et sous dossiers de ce dernier, j'y retrouve quelque dossier "Vstream", mais je ne trouve ni le dossier "lib/handler" ni le fichier "premiumhandler.py"

Quelqu'un peut m'aider ?

Merci d'avance

**Comment by Jojo31780** [comment]
@vic1997. Merci pour ton aide. En fait j ai Kodi sur un boîtier du style android tv qui est le firestick d amazon.. Alors a part faire les mises à jours via un fichier Zip et un repository je ne sais pas quoi faire! Un patch peut etre? Merci encore.

**Comment by JimmyLaurent** [comment]
Et pourquoi pas installer via le fichier zip original dans lequel tu aurais remplacé le fichier incriminé ("resources/lib/handler/premiumHandler.py") ?

**Comment by lofrez** [comment]
Bonjour,
Je viens de suivre ta méthode @JimmyLaurent sur mon rasp pi ...
La mise a jour de vstream a bien été effectuée, mais l'eternel problème de "connexion ratée" est toujours présent ...

Une idée pour pouvoir modifier ce premiumHandler.py sous rasp ?

Merci

**Comment by Cikai91** [comment]
Bonjour j’ai procédé de la même manière j’ai modifié le fichier .zip et le problème est résolu chez moi depuis que la solution avait été donné. 
Tu te connectes sur uptobox.com ?

**Comment by madmocas** [comment]
Emplacement sur Linux share/CACHEDEV1_DATA/.qpkg/mykodi17/homes/newkodi17/.kodi/addons/plugin.video.vstream/resources/sites/

**Comment by madmocas** [comment]
Merci Jimmylaurent

**Comment by Jojo31780** [comment]
Salut a tous.
J ai réalisé la manipulation avec le fichier Zip (en remplaçant le premium handler.py par celui donné plus haut). J ai installé la mise à jour et j ai authentification réussie sur Kodi! Merci @Jimmylaurent!
Merci@vic1997.

**Comment by lofrez** [comment]
Alors, moi aussi je viens de faire la même manip en remplacent le premiumhandler.py dans l'archive, un petit redemarrage est cela fonctionne à nouveau !!!

Super, mille merci  @JimmyLaurent! & @vic1997

**Comment by fanfanderson** [comment]
Bonjour a tous, pour les utilisateur Mi box y'a une solution ? 
Si on télécharge le dépôt vstream le problème a été réglé directement ?
Thx

**Comment by Arias800** [comment]
Essayé avec ça http://uptobox.com/2embm2oac2bk

**Comment by ddav33** [comment]
J'ai essayé les deux solution plus haut en modifiant le ZIP sur Android avec es explorer et cela ne fonctionne toujours pas pour moi 😕

**Comment by Nassi123** [comment]
Moi aussi j'ai essayé de remplacer le fichier dans zip, mais j'ai toujours message erreur de connexion sur Android :(

**Comment by vic1997** [comment]
Je viens de recevoir une mi box, j'installe Kodi et tout ce qui faut dans les prochains jours. Je vous indiquerais ce qu'il faut faire alors.

**Comment by fanfanderson** [comment]
Merci @vic1997  t'assures, déjà que je te sollicite sur discord ;)

**Comment by Nassi123** [comment]
Pourquoi ça ne marche pas pour moi, ni sur Android tv ni sur Android téléphone, j'ai toujours le fameux msg :connexion impossible " j'ai un compte premium activé. 
Est-ce que quelqu'un a une idée pour ce problème Svp??

**Comment by Cikai91** [comment]
Bonjour, j'ai une box Android Tv, j'ai fais manuellement la modification du fichier qui a été fourni ici. Et depuis ça fonctionne. J'ai pas voulu mettre à jour via vstream depuis.

Pour ceux à qui cela ne fonctionne pas, vous avez un message " authentification raté " ?  Ou autre chose ?

**Comment by ddav33** [comment]
Oui j'ai authentifications raté et après ça ouvre sur uptostream limité a
2h par jours

**Comment by Nassi123** [comment]
Oui authentification raté moi aussi

**Comment by Cikai91** [comment]
C'est que le fichier n'a pas été modifié...
Le lien à été posté j'ai peu plus. 
Il faut mettre à jour le fichier mettre sur clé usb ensuite brancher sur la box.
Allez dans kodi système addon puis installer via fichier. .zip et vous sélectionnez le fichier sur votre clé usb

**Comment by Cikai91** [comment]
http://uptobox.com/op452zbyhsrz. 

Je vous remet mon lien j'ai utilisé ce fichier et chez moi ça marche sans problème.

**Comment by Nassi123** [comment]
@ddav33 comment t'as fait exactement pour modifier sur Android tv, t'as modifié sur le fichier original et après tu l'as installé après avoir desinstallé l'ancienne ?

**Comment by Nassi123** [comment]
Mais le problème est que même si l'authentification est réussi, ça affiche toujours fichier introuvable grrr

**Comment by Cikai91** [comment]
Tu utilises quelle sources sur kodi ? Moi je suis sur Zone téléchargement   et ça marche.

**Comment by Cikai91** [comment]
Dans kodi > vstream > tout en bas tu as sources > zone téléchargement...  J'ai mis en favoris cette sources

**Comment by Nassi123** [comment]
J'essaie de lire la série 4 de "SUITS" sur DDL-ISLAND ça me met fichier introuvable sur uptobox et uptostream

**Comment by Cikai91** [comment]
@Nassi123 et sur Zone T ?

**Comment by ddav33** [comment]
Cikay esque le lien que tu as mis le fichier et déjà modifié ?

**Comment by ddav33** [comment]
Oui avec es explorer

**Comment by Cikai91** [comment]
Oui ddav33 c'est le fichier dont je me sers

**Comment by Nassi123** [comment]
La série laquelle je cherche à regarder n'existe que dans DDL-ISLAND en version True HD.
Lorsque je vais à Zone-telechargement pour regarder n'importe quel film  : le lien uptostream ça marche, par contre quand je clique sur uptobox : ça me met un bout de temps à chercher et puis fichier introuvable.
Je crois qu'il y a un problème de streaming sur uptobox premium

**Comment by ddav33** [comment]
C'est bon cela a fonctionné merci bien cikai

**Comment by akhas113** [comment]
Bonjour,
Je suis sur boitier android et je n'arrive pas à accédé à premium handler.
Un micro tuto s'il vous plait sur la façon de modifier le fichier zip.

Merci beaucoup du travail que vous fournissez.

**Comment by akhas113** [comment]
Merci beaucoup ddav33 et cikai91 sa marche

**Comment by akhas113** [comment]
Re bonjour

Désolé sa a marché mais maintenant sa ne fonctionne pas.
Je n'y comprend plus rien.

Merci de votre aide et désolé encore.

**Comment by akhas113** [comment]
c'est bizarre j'ai redémarré ce matin et comme par hasard uptobox fonctionne très bien merci infiniment les gars!

**Comment by Cikai91** [comment]
Bonsoir, la dernière mise à jour dispo sous vstream, y a le correctif uptobox et recherche ZT ? Svp
