### ISSUE TITLE
Qu'elle version pour Kodi 15.2

### ISSUE THREAD

**Issue by freddykrueger59** [Kodi-vStream/venom-xbmc-addons#1995]
Bonjour 
J'aimerais trouver comment faire fonctionner vstream avec Kodi 15.2 
En effet je reste sur cette version de Kodi car c'est la dernière qui n'utilise pas mediacodec qui fonctionne mal chez moi 
Merci d'avance

**Comment by Arias800** [comment]
Prends la version 0.5.7 ^^

**Comment by LordVenom** [comment]
Il suffis de désactiver l’accélération matériel pour résoudre ton soucis non ?

**Comment by freddykrueger59** [comment]
Je vais essayer la 0.5.7 car si je désactive l'accélération matérielle ça saccade a fond

**Comment by freddykrueger59** [comment]
Je n'avais aucun soucis avec l'ancienne accélération matérielle libstagefright

**Comment by freddykrueger59** [comment]
je viens d'essayer la 0.5.7 , l'addon s'installe mais ne lance aucune video lorsque je selectionne

**Comment by freddykrueger59** [comment]
Pourtant il me fait bien une mise à jour des sites .py 
Mais quand je sélectionne un lien .rien ne se passe sur zone téléchargement

**Comment by Arias800** [comment]
Si tu ne peux pas lire de lien uptobox c'est normal

**Comment by freddykrueger59** [comment]
J'ai tout essayé est pas moyen de faire fonctionner vstream correctement avec Kodi 15.2 
Là je sèche

**Comment by LordVenom** [comment]
La, ça vas être compliquer de t'aider avec tous les changements c'est possible que les sites est besoin de code implantés dans les versions récente.

Regarde ton log voir si c'est grave mais la compatibilité Kodi 15 ont vas pas pouvoir y faire grand chose il faut travailler sur la version 18.
