### ISSUE TITLE
Source film/series et maj auto

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#1996]
Bonjour 

Je me demandais si on pouvais avoir les maj des séries ou des sources au démarrage de kodi.
En demarrant kodi il y a l'onglet Films et Series TV et TV et Extensions etc...

Mais j'aimerais mettre mes seriestv de vstream dans Series TV et films dans Films pour que que au demarrage cela me previent des maj de mes series et de la source de films

Comment avoir les maj auto des series film a partir des sources de vstream svp 

Merci

**Comment by TmpName** [comment]
Il n'y a pas de MAJ des serie/films, juste une mise a jours de fichier, la difference est generallement invisible pour toi.

**Comment by LordVenom** [comment]
J'ai rien compris XD

**Comment by AizenKnower** [comment]
Donc si on veut savoir si une source a maj une serie. Ya pas moyen de le savoir a part cliquer sur Vstream/sources/site/serie ?

Je me suis dis en mettant la serie sur librairie ou marque-pages puis sur "ajouter source" dans l'onglet SERIE TV de kodi (page d'accueil) ou directement le source internet (genre Planet-streaming) ; on aura une maj des series.

De plus je sais que vstream a "librairie/serie" et "librairie/film" jai cru que c'était dans ce but d avoir justement l'affichage des maj des series sauvegardées dans librairie et en être averti.

Si c'est pas possible est ce que ce serait compliqué de le mettre en Request?

**Comment by TmpName** [comment]
Et non c'est pas possible, comment tu fais en general pour savoir si un site de strming a mit une serie a jours ? Tu t y connectes et regardes, pas vu de sites proposant des flux RSS pour ca.

**Comment by AizenKnower** [comment]
@lordvenom

Je cherche just a ajouter une source vidéo a kodi pour afficher les nouveaux film et episode de serie dans le menu de démarrage au niveau de l'onglet Film et de celui de Serie.

Quand on clique sur serie il demande de cliquer sur fichier et ajouter source et je veux ajouter un site de streaming pour voir les maj.

Vu que vstream affiche les nouveautés pour chaque site je me demander si on pouvais afficher le site dans le menu de démarrage.

Car je regarde uniquement les series de series-streaminghd et film de Planet-streaming (au pire ZT streaming )

Lol je viens de comprendre que je cherche un lien de raccourci qui dès le demarrage affiche le contenu d'un site de streaming en page d'accueil 

Peut etre déplacer ce sujet en Pull Request si c'est pas possible ?

**Comment by AizenKnower** [comment]
@tmpName

Je parle pas de flux rss. Mais je pense que c'est possible en mettant le site de streaming en raccourci sur la page d accueil de Kodi (possible que cela depend des devs de Kodi et pas de Vous meme)

Merci quand meme.

**Comment by LordVenom** [comment]
Tu peux ajouter le dossier au marque-page c'est le plus rapide.

**Comment by Arias800** [comment]
Il y'a aussi des add-on qui permet d'ajouter des liens de streaming dans la page d'accueil  (comme add to lib en autre)

**Comment by AizenKnower** [comment]
Je ne pense pas que c'est ce que je cherche car ce n'est pas les liens de streamings mais la source qui les hebergent que be souhaite être averti des maj

Merci @Arias800 et @ lordvenom , 

Tu peut me dire quelque skin?

**Comment by LordVenom** [comment]
Etre avertis ça non. mais visualement tu verras la différence si il ajoute un épisode.
Le skin Eminence par exemple te permet d'avoir un visuelle sur la page d'accueil.

Aprés pour être avertis par email par exemple tu peux t’inscrire sur https://trakt.tv/ puis combiner ton compte avec vStream il te permettras de faire la recherche suivant les Series Films que tu auras dans Trakt.

**Comment by AizenKnower** [comment]
Merci je vais voir pour Eminence

Mals je pe se que j'ai trouvé ce que je cherche

https://youtu.be/NkMYsltqsF8

C'est le skin xConfluence ; sur la vidéo ça semble que je recherche
Donc apparemment le nouveau de Kodi 18 n'a plus ces possibilité 

Merci pour cette idée de skin

**Comment by LordVenom** [comment]
Je te conseil hé c'est pas pour me faire de la pub XD

https://www.youtube.com/channel/UCdyY1QEC8dJSU6-6GPKPrnA

Une video sur les marques pages et  un autre sur la librairie.

**Comment by AizenKnower** [comment]
C'est quoi la source pour éminence ?
J'ai trouvé eminence 2.5 mod mais souci de xmbc.gui qui n'est pas satisfait

**Comment by AizenKnower** [comment]
Finalement Eminence est pas compatible Kodi 18 et Confluence n'est pas compatible avec vstream

La video youtube montre l addon Specto qui est l'équivalent de Vstream mais quand on arrive a la serie tv qu'on veut sélectionner pour mettre dans la librairie comme avec Specto; malheureusement Vstream n'offre pas cette possibilité 

Donc est il possible d'avoir cette possibilité ? On le voit a partir de la 4e minute sur la video https://youtu.be/NkMYsltqsF8

**Comment by Arias800** [comment]
![capture](https://user-images.githubusercontent.com/24809312/37876763-b559644e-3051-11e8-994d-973a74731c82.PNG)
Comme ça ? Si oui tu peux le faire avec add-to-lib ou si tu fait comme @LordVenom fait dans la video sa devrait marché (des fois ca ne s'actualise pas donc il faut allez dans la categorie de ton choix et faire actualisé la mediatheque)

**Comment by Abeillefan** [comment]
@LordVenom , est-ce possible de mettre la série Departures svp ? Il y en a une, mais ce n'est pas la bonne... Moi c'est celle-ci : https://www.netflix.com/ca-fr/title/80027841 

Merci 😊

**Comment by Arias800** [comment]
C'est pas nous qui geront le contenue nous on l'affiche juste ^^

**Comment by Abeillefan** [comment]
Je ne suis pas sure de comprendre ? Vous ne pouvez pas ajouter une série  dans Vstream ?

**Comment by Arias800** [comment]
non c'est les site qui ajoute ce qui veulent et nous on récupéré juste les info sur les site et on les affiche (ce qui nous permets de resté dans la l’égalité de la lois française qui ne sanctionne que les hébergeur en autre)  ^^ donc a moins de trouve un site qui dispose de cette séries on n'a pas la possibilité de la proposé ^^

**Comment by Abeillefan** [comment]
Oh je vois. Merci 😊

**Comment by AizenKnower** [comment]
@

oui jai essayer avec des skins mais ca marche pas.
Tu peut faire si tu a le temps un tuto pour avoir la meme chose
Je suis surtout sur streaminghd et Planet-streaming 
Donc jaimerais comme ca voir les maj de ces 2 là pour serie et film
Comment as tu pu obtenir cette page stp
Avec add to lib?
Merci

**Comment by Arias800** [comment]
Faut que je vois pour faire un turo le week-end prochain parce que c'est long x)

**Comment by AizenKnower** [comment]
Jai testé add to lib 
Jai choisi un dossier d une source genre film ajout recent de planet streaming
Jai mis add to lib et forced add etc..... mais  rien ne s affiche

**Comment by AizenKnower** [comment]
@Ariase800 

Dit je me demandais si tu a pu faire un tuto

**Comment by Arias800** [comment]
Je vais m'en occupé ^^

**Comment by Arias800** [comment]
@AizenKnower fait ça ma pris une bonne heure cette histoire x) http://kodi-fr.rf.gd/showthread.php?tid=30

**Comment by AizenKnower** [comment]
Merci désolé si ça ta pris bcp de ton temps
J'ai cherché partout un tuto mais sans succès 
Merci encore et bon weekend prolongé

**Comment by Arias800** [comment]
C'est pas grave le principe c'est que ca peut aidé et je comprends car moi meme j'ai eu du mal a l'utilisez au debut
Bon week-end a toi aussi
