### ISSUE TITLE
Ajout de chaîne tv

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#1997]
Je me demander pourquoi ya plus de chaines tv sur vstream 
Est ce que c'est un souci technique ou juste une absence de playlist fiable?
Car des playlist yen a plein sur des sites de iptv ce serait bien d avoir aussi la tv sur vstream comme avant 

Merci

**Comment by AizenKnower** [comment]
Ou permettre dans les reglages l ajout de playlist iptv (qu'il soit interne ou online)

**Comment by TmpName** [comment]
Il ya quelques chaines, les seules stables.
Et non, il n'y a pas de sites iptv stables, on a deja teste.

**Comment by AizenKnower** [comment]
Je peut en fournir une qui est stable et met a jour regulierement si çà interesse mais c'est une longue liste (3700 en gros)

Si ajout de fonction ajout de playlist iptv est pas possible je peut vous passer une belle playlist 

Car livestreampro deconne souvent et iptv simple stop la chaîne au bout de 

donc possible que avec vous yaura pase ce probleme.
Je regarde tf1 et le buffer semble largement assez et et niveau qualité image est niquel meme en chaîne SD alors que iptv client et livestreampro c'est pas top

Qu en pensez vous?

**Comment by Arias800** [comment]
Plus de chaine payante pour des raison legale

**Comment by AizenKnower** [comment]
Ok mais il suffit juste de filtrer les chaines payante et garder que ceux gratuit non?
Je suis pas devs mais si vous arrivez a filtrer les chaines payantes et garder que la TNT ça peut se faire

Bref c'est juste pour ajouter quelque chaines même si c'est de la tnt c'est mieux que rien

Si jamais ça intéresse faite signe de toute facon c'est pas ma playlist il est stocké sur goo.gl.

**Comment by AizenKnower** [comment]
Pour le côté légal ; il me semble  que si le serveur est a l'étranger partager les liens n'a rien d illégal en tout cas pas plus que partager les liens des sites de streaming car ce que je propose c'est just inclure un lien internet sur vstream tout comme on le fait avec livestreampro ou pvr simple client..

Est ce que au moins il est possible d'avoir une option dans les réglages pour selectionner la playlist m3u que l'on souhaite stocké dans un autre addon ? comme ça on mettra notre propre playlist

**Comment by Arias800** [comment]
Après oui les chaine TNT ça ne pose pas de problème mais le truc c'est que les chaine comme a traquer les add-on de partage d'iptv alors que pour le streaming d'après la hadopi nous ne somme pas dans l'illégalité ^^

**Comment by AizenKnower** [comment]
Ben ce que je propose c'est la meme chose que le streaming car c'est juste un seul lien qui affiche la playlist donc comme le streaming de serie ou de film qui affiche la playlist des episodes lol

Après je comprend les craintes mais vu que c'est du streaming du net que ce soit film serie musique chainetv soit cest legal soit non

Et d apres ce que jai compris c'est ceux qui heberge les film les serie video les chaine qui sont dans l inégalité mais pas ce quu recense les liens meme si hadopi ferme ces site de streaming qui heberge aucune oeuvre

En tout pas de souci mais j'espère qu'on aura cette possibilité  d ajouter le dossier contenant la playlist m3u dans les reglages pour y mettre notre propre playlist car celui de vstream y a que arte france tv et tf1

**Comment by ddav33** [comment]
Y'a un addon, jai pas le nom en tête ,pour lire ces propre liste iptv , si t'a une liste stable je demande qu'à voir car impossible d en trouver sur Google et toujours incomplète suivant les chaînes qu'on veut ! 😕

**Comment by freddykrueger59** [comment]
Je suis intéressé par ta liste aizenknower
Pourrais tu me l'envoyer stp ?

**Comment by benking110181** [comment]
moi aussi ! Je suis intéressé par ta liste aizenknower

**Comment by kabcasa** [comment]
Je suis aussi intéressé par ta liste aizenknower .
Pourrais tu me l'envoyer stp ? merci

**Comment by AizenKnower** [comment]
Désolé retard lol (boulot oblige)

Je veux bien le mettre ici si çà cause pas de problème aux proprietaires de ce github.

Donc je vais attendre leur permission et si pas de problème je le partage.

La liste est très longue et regulierement mis a jour pour. Donc si les proprio ne voient d'inconvénients je met le lien (c'estun raccourci goo.gl que l'ont peut mettre sur livestreampro ou iptv simple client mais sur les chaines Ful HD ya des soucis de buffering mais pas avec les chaines HD et encore mois sd.

Je pense que vstream gere mieux les chaines full hd que les 2 addons cités donc j'espère une possibilité de personaliser le dossier tv contenant m3u pour y mettre notre playlist.

Donc puis je partager ce lien goo.gl contenant la playlist ?

**Comment by Arias800** [comment]
Je propose de le posté ici : http://kodi-fr.rf.gd/?i=1 étant donnée que c'est un forum ce sera plus simple de retrouve le liens pour les futur intéressé

**Comment by AizenKnower** [comment]
Ok merci

**Comment by AizenKnower** [comment]
Je vais voir si ce forum accepte car je pense pas. Les admins travaillent sur un iptv participatif donc forcement payant donc une liste gratuit risque  de pas être le bienvenue.

Est ce que il sera possible de mettre un lien d iptv sur les reglage de vstream pour que la rubrique TV affiche notre playlist personel? Si c'est pas possible je comprendrait

(Pour les intéressés pour la liste iptv pas de souci je vais vois quel forum accepte que je partage)

**Comment by Arias800** [comment]
Je fait partit du staff (je suis moderateur) donc t’inquiète pas :p Et le systeme d'iptv n'est pas payant passe sur notre discord si tu veux en savoir plus ^^

**Comment by AizenKnower** [comment]
Ok je vais dans ce cas m inscrire et y partager ce lien car je sais la galere que c'est de trouver une playlist convenable (je le mettrait dans le forum rubrique lien iptv là où vous parler de faire une iptv participatif)
J'espérais que vous le mettiez sur vstream en remplacement du webtv.m3u pour  vous remercier de votre travail sur vstream car c'est le seul addon sur mon kodi et il est excellent et suffisant.

(Par contre si tu peut me dirr comment mettre mon url dans settings.xml pour remplacer celui par defaut webtv2.m3u je l'ai remplacé mais il y a toujous les chaines webtv.m3u a la place de mon playlist.m3u)
