### ISSUE TITLE
Filtrer les hosters pour playlist

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#1998]
Désolé déranger à nouveau mais comme on dit jamais 2 sans 3 :)  et en esperant avoir compris le terme hoster ;)

J'ai suivi un post sur ce github pour lire une playlist en suivant. Il faut juste cliquer "lire a partir de cette episode"
Le hic c'est que l'épisode qui suit c'est le meme épisode mais d'un hoster different.

Quand y en a plusieurs on zappe beaucoup pour lire le 2e episode en esperant que c'est pas Netu ou openload qui mette plus longtemps a "resolve" le lien.

Donc y a t il moyen de lire l episode suivant sans qu il lance le meme episode d'un autre hoster

Sinon dite moi comment vous faite pour lire une playlist d une serie qui a plusieur hoster pour un episode

Merci

**Comment by TmpName** [comment]
Y a une fonction playlist sur Vstream ?

**Comment by AizenKnower** [comment]
Ben oui. 
Quand on clique sur un episode il demande si on veut l ajouter a la playlist (cliquer en maintenant le bouton  et c'est le premier  er ca sauvegarde dans une playlist

Pour avoir acces a la playlist cest en accedant au menu a gauche  (cliquer gauche) puis cliquer sur aller a la liste  de lecture 

Puis tu enregistre ta playlist 

Le hic c'est que la playliste n'a pas son racourci dans vstream faut cliquer gauche pour y aller je crois

**Comment by LordVenom** [comment]
Il me semble que tu peux ajouter que le lien final (lien bleu) à la playlist donc aucun soucis.

Perso je met le dossier contenant la série dans les marque page voir plusieurs au cas ou. ca me prend 10-15min pour trouver les bon lien ect... aprés y a plus cas regarder :)

**Comment by AizenKnower** [comment]
@lordvenom

Justement j'espérais qu'on pouvait ajouter la catégorie gene Serie TV puis faire un raccourci pour l afficher au demarrage juste en dessous de favori ou en widget. 

Je vais essayer de voir si des skin ou addon mettent le contenu en page d'accueil. 

Merci quand meme

**Comment by LordVenom** [comment]
Tu peux parfaitement faire un menu "vStream" sur l'accueil avec en sous menu tes marque page film ou série ça demande un peux de réglage et il faut pas utiliser le skin officiel.

**Comment by AizenKnower** [comment]
Finalement ça  rejoint mon autre poste sur les maj de serietv et film. Donc les 2 questions que je me pose se resoid juste en changeant de skin

Merci encore donc les 2 sujets peuvent etre clos je pense
