### ISSUE TITLE
Vstream l'addon qui monte

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#200]
Malheureusement je sais plus quand a été crée vStream normalement aout 2014 en tous cas ce sont la mes premier stats avec 4 993 sessions (une session correspond a une visite sur la page home de l'addon) 
Bref comme le mois d'aout n'est pas fini je vous donne celle de juillet 2015 c'est un record avec 4 659 165 sessions. Dans l'année c'est plutôt fixe a 2 500 000. Voila je voulais juste partager cette réussite avec tous ceux de prés comme de Loing qui participe avec moi a vStream.

(Pour les personnes qui comme moi n'aime pas avoir des stats sans le savoir, je precise aucune ip n'est enregistrer)

**Comment by hicham31300** [comment]
Tout simplement BRAVO. Continuez comme ça.

**Comment by LordVenom** [comment]
Voila les stats pour aout :+1: 

Donc pour rappelle y a 1 ans 4 993 session et cette année 4 633 362.

**Comment by zombiB** [comment]
Bravo à tous.

**Comment by LordVenom** [comment]
Année 2016:

01/16 : 10 639 716
02/16 : 11 089 487
03/16 : 13 277 788
04/16 : ,12 419 081
05/16 : 13 845 161
06/16 : 13 995 453
07/16 : 15 607 431
08/16 : 15 900 369
09/16 : 14 689 052
10/16 :  19 341 056
11/16 : 19 890 491
12/16 : 25 718 074

Total : 186 413 159

**Comment by LordVenom** [comment]
Année 2017:
1. 33291067
2. 32461682
3. 33519664
4. 31427134
5. 32619420
6. 28214653
7. 31431769
8. 31146077
9. 30248390

**Comment by AizenKnower** [comment]
Bonjour 

Vu son succès est il possible de voir ce plugin compatible d'autre logiciel comme Movian (pour PS3) ou Perfect Player (Pour android et PC?

Merci

**Comment by Arias800** [comment]
Kodi est apparemment dispo sur ps3 mais aussi dispo sur android et pc donc pourquoi compliqué les chose en le créent sur d'autre plateforme
