### ISSUE TITLE
problème librairie série de vstream

### ISSUE THREAD

**Issue by ddav33** [Kodi-vStream/venom-xbmc-addons#2002]
Bonjour voilà je vient vous faire par dun problèmes, quand j ajoute une série dans la librairie vstream le clavier de modifications du nom de la source pour être reconnu par les méta donné serie, qui apparaît bien au moment de l ajout dans celui de film n'apparaît pas dans celui de  série, donc il faut le faire manuellement dans série de la librairie mais la il y a un bug la série s'ajoute bien mais le fannar ne s'affiche pas dans mon skin serie comme pour les films qui lui marche tres bien ,alors que cela marché avant pour les série, merci de votre aide si vous voyez ce que je veux dire 😉

**Comment by TmpName** [comment]
J'ai commence a te modifier le fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/library.py

Mais le prb des series, c'est que si tu supprimes les infos sur la saison ou l'episode, tout risque de deconner.

Si ca marchait avant et plus maintenant, je pense que le prb vient de l'ortographe car la derniere modif date de janvier.
