### ISSUE TITLE
Site de streaming gratuit et legal

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2003]
Il existe des services gratuit notamment pour les anime permettant d'en regarde gratuitement :
Crunchyroll : Un des plus connus qui permets de visionner des anime gratuitement en 480p maximum avec des publicité
Wakanim : Permets de regarde des anime en 480p avec des publicité mais necessite un compte et il n'est pas possible de voir certaine série .
Je mettrai cette liste a jour car cela permettra d'encourager de plus gros site (amazon prime vidéo ,netlfix) a créer des version gratuite de leurs services

**Comment by TmpName** [comment]
Elles se presentent comment les pubs ?

**Comment by Arias800** [comment]
Ça dépend sur wakanim c'est une au début , une autre au milieu et j'en a la fin (il me semble) et sur Crunchyroll ça varie selon la série et le supports dans tout les cas c'est regardable

**Comment by Kiribou** [comment]
Sur wakanim tu ne peux pas regarder autant d'épisodes que tu souhaites.(à moins d'avoir un abonnement premium..) 
Les pubs ne sont pas dérangeante cela dit

**Comment by Arias800** [comment]
Ah je ne savais pas il me smebalit qu'il avait enlever cette restrictions
