### ISSUE TITLE
Premium mode Authentification ratée

### ISSUE THREAD

**Issue by GVinceG** [Kodi-vStream/venom-xbmc-addons#2006]
Bonjour à tous,

J'utilise Kodi sous libreelec avec l'addon Vstream dont j'ai fait la derniere mise à jour dans le courant de la semaine. 
J'ai un abonnement premium Uptobox. Depuis quelques temps j'ai le message suivant : "Premium Mode Authentification ratée". Il me propose de passer par uptostream plutôt qu'en direct download et au delà de 2h de visionnage (de films de vacances de ma tante Irma) je suis "bloqué" pour 24h. 
Mon compte Upto fonctionne parfaitement sur PC, Tablette, téléphone...

**Comment by Arias800** [comment]
Il y a deja un sujet qui parle de ca : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1994 merci d'eviter les doublons
