### ISSUE TITLE
Cineiz

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2010]
Ne fonctionne pas.

1- dans showLinks il faut lui envoyer un faut post id
oRequestHandler.addParameters('levideo', '12345')
Pour avoir les bons code (sinon c'est décaler et aucun host n'est a la bonne place).

2- La requette du hosts 
http://vimple.org/video.php?p.....
Re-tourne toujours une mauvaise adresse pourtant sur le site ça fonctionne j'ai pas trouver le pk du comment.

Note fichier mis OFF pour le moment (return False en debut de site)

**Comment by TmpName** [comment]
J'ai corrigé pour la fausse url mais j'ai pas vu de decalage chez moi ?

**Comment by LordVenom** [comment]
Sisi j'ai réparer juste derrière ta correction.c'etait le referer le soucis ben j'ai pas trouver merci.
