### ISSUE TITLE
Openload

### ISSUE THREAD

**Issue by ebs111** [Kodi-vStream/venom-xbmc-addons#2011]
hi,
there is a problem with openload,
it stoped working.
thanks.
(the best addon by the way 👍

**Comment by TmpName** [comment]
J'ai commence, ca marche mais le code n'est pas fini, il y a une partie du code en dur, donc ca ne va pas durer mais je n'arrive pas a trouver comment la page html recupere la variable du code JS.

>>url = JP.GetVar( Liste_var , '_0x1bf6e5' )

**Comment by TmpName** [comment]
Ha mince, j'avais pas vu, c'etait ce qui me manquait ^^.
Ma modif fonctionne mais n'est pas stable, si ils changent le nom de la variable c'est mort, avec ta modif par contre c'est plus stable.
Je fusionne les deux codes, et met tout ca en MAJ.

**Comment by 1shad** [comment]
impeccable

**Comment by ebs111** [comment]
Merci ça marche !!! Vous êtes un champion incroyable
