### ISSUE TITLE
Série saisons 

### ISSUE THREAD

**Issue by AngelineL** [Kodi-vStream/venom-xbmc-addons#2012]
Bonjour à tous . Déjà merci beaucoup pour votre taf. 
Un soucis que j'ai  ( sur tous les supports j'ai testé ) : j'entre dans la catégorie derniers ajouts series  sur zt par ex  je clique sur autres saisons disponibles cela me ramène pas sur la dite saison mais sur la même qu'avant.

**Comment by Arias800** [comment]
Oui ce bug date d'il y'a un petit moment mais ai pas encore trouvé de solution :/

**Comment by Arias800** [comment]
Oui c'est juste un bug d'affichage mais je ai toujours pas trouvé d'où ça vient peut être du site ^^

**Comment by AngelineL** [comment]
Oui effectivement c'est la bonne saison qui est lancée :)
