### ISSUE TITLE
Zone-Telechargement.ws mode recherche HS 

### ISSUE THREAD

**Issue by chaiba2006** [Kodi-vStream/venom-xbmc-addons#2013]
Bjr merci bcp pr le travail colossal que vous faite .
Je tient à vous rapporter mon problem c que le mode rechercher ne marche plus depuis 3 jour sur zone telechargement sûrement suit au changment de leur adresse de ww1.zone-telechargement1.com
A ww2.zone-telechargement1.com 

Si quelqu'un pouvait me montrer comment faire merci

**Comment by Arias800** [comment]
Déjà fix dans la beta ^^

**Comment by chaiba2006** [comment]
Merci Arias800 pr votre réponse . J'ai changer l'extension en .py  est j l'ai copier à ds le fichier site j'ai écraser l'ancien fichier . Mais maintnn l'ensemble des raccourcis zonetelechargement ne marche . Est ce que jai fait une erreue quelque part . 
Merci encore

**Comment by LordVenom** [comment]
Bonsoir, Cliquez sur le bouton RAW pour n'avoir que le code.

**Comment by chaiba2006** [comment]
Merci bcp ça marche . Le mode recherche marche à merveille

**Comment by AngelineL** [comment]
Merci

**Comment by toterra** [comment]
Bonjour je suis nouveau je vien dacheter ma tele et jai decouvert cette aplication qui est fabuleuse mais j'aimerai egalment pouvoir resoudre se probleme mais je ni connait pas grand chose pour se qui de ajouter un fichier .py je ne sais meme pas comment acceder au dossier depuis la tele si vous pouvez me detailler se serait super

**Comment by TmpName** [comment]
Il te suffit d'attendre. La MAJ est proposee tout les 3 jours. Donc si tu l'as rate, elle te sera proposée dans max 3 jours, sans avoir a toucher aux fichiers toi meme.

Sauf evidement si c'est un nouveau probleme, qui n'a pas encore ete corrige.

**Comment by Arias800** [comment]
Je vient d’aller sur le site et il n'a pas changer donc normalement le fichier sur le bêta est bon

**Comment by toterra** [comment]
Jai reussi a mettre le fichier jai relancer kodi la source marche mais longlet recherche ne donne toujours rien

**Comment by Arias800** [comment]
oui c'est parce qu'a chaque modif de l'url tout marche hormis la recherche donc faut attendre 3 jour pour avoir la maj
