### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2017]
Pour info, la protection cloudflare a chnagée, je suis dessus, fichier sur beta, mais ca ne marche pas encore donc faites gaffe avec.

**Comment by TmpName** [comment]
C'est bon fini. Normallement elle devrait plus bloquer.

**Comment by johngf** [comment]
du coup on peut ré activer gum gum et serie en stream.

**Comment by TmpName** [comment]
Ha ?
Je savais pas que gumgum etait a l'arret. En fait c'est gace a lui que j'ai vu que cloudflare etait HS.

**Comment by johngf** [comment]
il y a un soucis avec la lib sur le site ad kami ça passe pas ligne 286
ERROR: HTTPError: HTTP Error 503: Service Temporarily Unavailable
comme ci la requete était bloqué j'ai essayé de bidouillé mais j'ai toujours droit au 503

**Comment by TmpName** [comment]
J'avais deja eu ce prb, donc j'ai deja le code pr le 503, mais j'ai un prb s de cookie manquant (c'est pour ca que je l'avais abondonne a l'epoque
https://pastebin.com/3tCSmqjv

Le je suis dessus, pourvu que ca reste bloque assez longtemps.

**Comment by johngf** [comment]
oui le premier cookie est manquant mais meme en le donnant dans mes test ça fonctionné pas

**Comment by TmpName** [comment]
Peut etre ici, tu as plein de lien dans le code. 
en fait je crois que quand tu as ca dans les headers c'est pas bon.

`Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"`

**Comment by TmpName** [comment]
Bon pas trouve, peut etre un prb SSL, mais c'est trop tard le site refonctionne.

**Comment by TmpName** [comment]
Ha yep bien vu, pas le meme code d'erreur, je regardes vu que le site est de nouveau sous protection.

**Comment by TmpName** [comment]
Bon alors j'ai remarque que sur navigateur, ca avait l'air de faire 2 fois la requete sur la premiere page donc j'ai refait le code
https://pastebin.com/jd38cnBx

Now c'est une boucle, donc il peut refaire 2/3 fois la requete, mais rien a faire meme resultat, meme code d'erreur.
Le je vois pas pkoi ca deconne, je partirais sur un truc ssl.

**Comment by johngf** [comment]
bah oui c'est bizarre il doit y avoir un truc

**Comment by TmpName** [comment]
C'est bon je pense avoir trouver.
Regardes le code de la page html, protection recaptcha. C'est lui qui provoque la page 403.

**Comment by TmpName** [comment]
Nouvelle version plus en date https://pastebin.com/5n2WzYWe
Mais je galere, j'ai tout mes addon de firefox qui bugguent, meme httprequester, il me trouve une page web meme sans cookies, juste avec une url.

**Comment by TmpName** [comment]
Bon ca me gave, j'essaye de comparer avec la lib python qui fait la meme chose, mais ils ont utilise des fonctions de heuts niveaux a tel point que tu n'as aucune idee de ce qui se passe derriere.
La j'ai desactive tout les cookies et ca marche encore, doit y avoir une lib encore dessous.

https://pastebin.com/UsiX6hsA

Faudrait un code fonctionnel avec des fonctions de bas niveau.

**Comment by johngf** [comment]
moi aussi ça ma soulé la premiere fois j'ai meme ouvert la lib urllib2 pour voir

**Comment by TmpName** [comment]
Ca y est, derniere version et fonctionnelle celle la

https://pastebin.com/FjdCR1BX

Par contre pas sur quelle va marcher sur tout les sites, les redirections ne sont pas geréés pareil.

**Comment by TmpName** [comment]
C'est le site (ou le code ddu site)  qui deconne, non ?
Dans le code html de la derniere page c'est bien le contenu du site adkami.

**Comment by TmpName** [comment]
Nouvelle version https://pastebin.com/DRa9DiVD
Et cette fois le site se charge sans prb, j'ai laisse la tempo a 6s, mais ca doit passer a 5.

**Comment by johngf** [comment]
pareil fonctionne pas 503 ou connexion impossible

**Comment by TmpName** [comment]
Put1, moi aussi, je compend pas ca marchait hier ...

**Comment by TmpName** [comment]
Bon ben faut rajouter
url = url.replace('https','http')

ligne 230, pas trouve pkoi ca deconne, et comme y a que wireshark qui marche chez moi pour debogger, avec le ssl, c'est la misere.

**Comment by TmpName** [comment]
Ca y est g trouvé, encore une nouvelle version ^^.
https://pastebin.com/13x9zmkf

Ca que je'ai pas encore testé, si une url de redirection ne commence pas pat http, et si la page obtenue contient aussi une redirection, mais bon c'est vraiment des cas rares.

**Comment by TmpName** [comment]
Cette fois ca a la'ir bon ?
Je le passe sur la beta ?

**Comment by TmpName** [comment]
Ok , j'envois alors.

**Comment by johngf** [comment]
mais ça fonctionne pas sur voirfilms ws

**Comment by TmpName** [comment]
Je viens de tester, y avait bien encore la protection, mais c'est passé.
Tu as quoi comme bug ?

**Comment by johngf** [comment]
503

**Comment by TmpName** [comment]
La je vois pas, moi j'ai eu une fois l'erreur 503, puis au second chargement c'etait bon.
J'ai modifier le code pour repartir a zero quand les cookies memorisee ne sont pas bon, dis moi si c'est mieux, mais la je ne comprend pas (le debug est reactive dans le code)

https://pastebin.com/zPxbG3Yx

**Comment by TmpName** [comment]
Tjours 503 ?

**Comment by johngf** [comment]
ils ont enlevé la protect mais demain je vais test sur t farjo aujourd'hui je suis loin du pc

**Comment by johngf** [comment]
bon ça fonctionne mais au niveau hoster c'est hs requete post cookie manquant

**Comment by TmpName** [comment]
Alors j'ai pas eu ton prb, y a plus la protection, mais j'ai un bug chelou, ca marche sur certaines series et pas d'autres a cause de la redicrection 302, il y a des cas ou ca gere la redirection et d'autre ou ca donne carrement un message d'erreur.

Je corrige ca, sinon y a pas de "post" dans voirfilm ?

**Comment by johngf** [comment]
non sur t farjo

**Comment by BENJI97200** [comment]
Bjr....pour le site zone de telechargement c pareil , probleme protection cloudfare sur samsung s8 alors que sur nvidia shield TV, zt ne se lance pas....une solution svp

**Comment by TmpName** [comment]
A mince je pensais que ct un film tfarjo, je viens de comprendre et ca buggue effectivement chez moi aussi, je regardes.

**Comment by TmpName** [comment]
C'est bon nouvelle version a tester, en fait le prb venait du fait qu'il y a 2 moyen de passer les cookies, soit en parametres, soit en headers.
