### ISSUE TITLE
Dossiers Librairie

### ISSUE THREAD

**Issue by vic1997** [Kodi-vStream/venom-xbmc-addons#2019]
Salut tout le monde.
J'ai depuis longtemps et je l'avais déjà dit ici, l'idée de pouvoir ajouter un ou plusieurs dossier à la liste de la librairie. Pour que quand on démarre Kodi, Vstream vérifie s'il y a des nouveaux films ou épisodes.
Pour l'instant la librairie ne permet que d'ajouter film par film.

**Comment by johngf** [comment]
le truc avec la librairie c'est que une fois que tu ouvre le dossier films ou série tu n'est plus dans vstream mais dans kodi donc je pense que c'est pas possible.
après j'ai pas cherché plus loin.

**Comment by TmpName** [comment]
Et dans tout les cas pas possible de "verifier si il y a de nouveaux film".

**Comment by Saab51** [comment]
Moi perso j'utilise une autre extension qui s'appelle "add to lib" qui ajouter n'importe quel lien a kodi dans un dossier et qui peut verifier aussi de temps en temps si y'a un ajout de video et les rajoute tout seule a kodi !
Apres ca marche que si tout les lien des film sont sur la meme page et on qu'un hebergeurs !

**Comment by vic1997** [comment]
@johngf Non ce que j'ai dis est bien une fonctionnalité qui serait sur vStream.
@TmpName Si, à l'allumage de kodi (de vStream également donc) on vérifie l'emplacement des dossiers enregistrés et on ajoutes les nouveaux films.

@Saab51 Oui je sais, j'utilise aussi, mais j'aimerais que cette fonctionnalité soit directement dans vStream, ça serait l'idéale.
Et oui je l'utilise que pour "Mon compte Uptobox'

**Comment by TmpName** [comment]
Ben a l'origine la librairie c'est tu trouve un lien Web vers un film tu le met en librairie, et tu le retrouves dans kodi comme un fichier sur ton disque dur.
Aucune verification de modification. Meme pour un fichier sur le DDR, si je le modifis il me faut relancer un scan pour que ce soit prit en charge ou alors la librairie c'est pas la meme chose chez moi.

**Comment by vic1997** [comment]
@TmpName Oui, mais ça serait bien qu'on puisse sélectionner un dossier et que tous les films à l'intérieur soient ajouté à la librairie.

**Comment by TmpName** [comment]
"un fichier librairie" c'est un fichier *.strm a l'interieur il y a le lien "web", pas possible de mettre plusieurs fichier dedans.
Et pas possible de les generer a la volee car a chaque fois il faut le lien "web" c'est a dire le tout dernier, apres la selection du hoster et a ce moment il n'y a qu'un seul lien affiches.

**Comment by vic1997** [comment]
@TmpName Oui, chaque fichier = un film, mais on peut vérifier si le film est déjà dans la librairie (si le fichier existe déjà).
Ce que j'explique est faisable, car j'utilise un autre addon qui permet de le faire, vu que vStream ne le permet pas.

On choisit un chemin (dossier) qui à chaque lancement est chargé et vérifié.

**Comment by vic1997** [comment]
@TmpName Non je parle pas de changer la librairie, je parle d'ajouter une fonctionnalité à vStream, permettant de charger des dossiers distants et d'obtenir les liens en fichier .strm et de les stocker dans le dossier vStream par exemple, et ceci à chaque démarrage.

**Comment by TmpName** [comment]
Je repete une derniere fois.
Un fichier strm contient obligatoirement 1 et 1 seul lien web qui donne obligatoirement sur une video directement. On peut y mettre un popup pour choisir un hebergeur, faire du traitement mais au final ca doit doit donner une URL lisible directement par un lecteur.
Donc c'est apres le captcha, apres la selection hoster de Vstream, apres l'authentification, apres le decodage des liens, ect ...
Impossible a fabriquer juste avec une liste de film sur un site web.

Je vois ce que tu veux faire, mais ce n'a rien avoir avec la librairie, ni les fichier strm non plus. L'addon de @Saab51 ne convient pas non plus ? "add to lib"

**Comment by vic1997** [comment]
@TmpName Bah si il convient, mais pourquoi ces addons permettent de la faire et pas vStream ?
Je sais très bien que un fichier = un film, sauf qu'il suffit d'avoir plusieurs fichiers pour avoir plusieurs films...

**Comment by TmpName** [comment]
Tout simplement car ce n'est pas la meme chose.
Ok alors un par film, mais tu veux un fichier par hebergeur ? un par resolution (car certains hebergeur proposent 2 resolutions) ? Ca va en faire des fichier strm juste pr 10 films. Sur un site a captcha, pas de soucis pour taper les 10 captchas pour avoir les 10 derniers film ?

**Comment by LordVenom** [comment]
@vic1997  Dsl mais dans le code de la librairie ont iras pas plus loin que ça je pense.Si tu veut implanter un nouveaux system il vas falloir le proposer :smile:

**Comment by vic1997** [comment]
@LordVenom Ok, c'est dommage, car là, pour le coup elle sert quasiment à rien.
Je suis obligé de passer par un autre addon pour faire ce que je veux, alors qu'on pourrait simplement le faire avec vStream. Dommage.
