### ISSUE TITLE
Besoin d'aide pour terminer une source

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2024]
Bonjour,
J'ai besoin d'aide pour affiché le numéro d'épisode dans showSeries.
je vois bien qu'il faut récuperer la valeur dans "Div id" pour la suite du regex mais comment le transmettre??? j'ai tester plusieurs chose sans succès.
Le fichier [ici](https://pastebin.com/bYmh9UzM)
merci de votre aide

**Comment by razorex** [comment]
ce ne serais pas mieux de prendre la valeur juste avant le lien vidéo et de faire dans ce genre
`    sPattern = '<div id="(.+?)">.+?<iframe.+?src="(.+?)"'`
`    sPattern = sPattern + '|href="#' + sData + '">(épisode.+?)<\/a>'`
sData serais la valeur div id..

**Comment by razorex** [comment]
@TmpName peut être à cause de l'écriture du premier lien
`<a href="#div2" class="selected">Épisodes 1</a>`
`<a href="#div3"> Épisodes 2</a></li>`

**Comment by TmpName** [comment]
Franchement c'est comme tu preferes, moi je prefere faire 2 grosses recherches regex que mettre un regex dans une boucle pour les performances, mais suis pas sur que la difference se sente.

Apres il ya meme des chances pour que div1 = epsiode 1 div2 = episode 2, et ect..., faudrait voir avec une serie incomplete si ca marche aussi.

**Comment by razorex** [comment]
Il n'y a pas de div1 ça commence à toujours par div2.

**Comment by razorex** [comment]
Plus personne pour m'aider??

**Comment by Arias800** [comment]
Je verrai si j'ai le temps ce weekend

**Comment by razorex** [comment]
Ok je te remercie

**Comment by razorex** [comment]
J'ai utilisé ta modif. je l'ai un peu réécris. J'ai remplacer "Error" par "Episodes 1" comme çà j'ai ma liste. [Mon fichier](https://pastebin.com/K19sbhhc). 
Par le regex çà dois etre possible mais je n'y arrive pas pourtant j'ai même fais çà `sHtmlContent = sHtmlContent.replace(' class="selected"', '')`

**Comment by Arias800** [comment]
Chez moi tout fonctionne je vois pas ou est le problème :/

**Comment by TmpName** [comment]
`<a href="#(div[0-9])+.+?"*>(.+?)<\/a>`
Pour le premier

**Comment by TmpName** [comment]
Fait passer le dernier code stp, pour que je teste.

**Comment by razorex** [comment]
En fait je viens de me rendre compte que ton second regex était différent du mien moi j'avais çà
`<div id="([^"]+)">.+?<iframe.+?src="(.+?)"`.
Pour le premier j'ai mis 
`<a href="#(div.+?)">(.+?)<\/a>`  (plus de 9 épisodes pour certaines séries).
Tout fonctionne correctement. Merci de ton aide.
Edit : Je l'ai mis en Beta.

**Comment by Smanar** [comment]
Merde me suis loupe c'etait #(div[0-9]+) et pas #(div[0-9])+.

**Comment by TmpName** [comment]
Merde me suis loupe c'etait #(div[0-9]+) et pas #(div[0-9])+.

**Comment by rayan310** [comment]
Très beau travail sa marche niquel de mon coté vous gérer les gars chapeau :)

**Comment by razorex** [comment]
Pas grave @TmpName. Laquelle des deux façons d'écrire ce regex est le mieux, la tienne ou la mienne?

**Comment by TmpName** [comment]
Ben perso je prefere le mien, le regex .+? est a eviter au maximum, pour 2 raisons.
Il peut commencer a la deuxieme ligne du fichier et finir a la derniere. En fait c'etait justement le probleme du precedent regex quand il affichait "custom-search", si tu regardes dans regex101, la partie recuperee faisait au moins 20 lignes. Ce regex est trop "laxiste".
Il demande plus d'iterations, donc plus long.

Essaye ces 2 regex
```
<a href="#(div[0-9]+)">
<a href="#(div.+?)">
```

Pour la phrase
`<a href="#div5" style="abc">`

Le premier ne marche pas, mais le second oui, le soucis du regex .+? c'est qu'il marchera toujours meme si il commence a la premiere ligne pour finir a la derniere.

Pour la meme raison il vaut mieux id="([^"]+)" que id="(.+?)"

**Comment by TmpName** [comment]
Le + veut dire "1 (au minimum) ou plus"
Le * veut dire "0 ou plus".
[XXX] veut dire 1 (et un seul) caractere du groupe entre crochet
0-9 veut dire un chiffre de 0 a 9 ( peut etre remplace par \d , mais ne marche pas pour tout les interpreteur regex).
[^XXX] veut dire 1 caractere sauf un du groupe entre crochet.

Donc [0-9]+ veut dire au moins un chiffre, mais autant qu'il peut y en avoir.
et [^"]+ tout les caracteres possibles (et au moins un) sauf "

**Comment by LordVenom** [comment]
Pareil j'ai commencer python avec vStream hé j'ai déjas changer 5 fois de clavier XD.

Une autre chose a savoir sur https://regex101.com/ en haut a droite il y a le nombre de Match et le temps d'exécution ont peux jouer avec les regex pour trouver le bon compromis temps/résultat ça optimise l'affichage dans vstream.

Tu peux aussi Click sur **Save regex** pour avoir une url à nous proposer.

**Comment by TmpName** [comment]
Ha ? ca j'avais pas vu, qu'on pouvait regler le temps maximum. Si on pouvait aussi le regler dans vstream ...

**Comment by razorex** [comment]
Faut que je l'utilise plus souvent ce site, çà m'aidera à comprendre.Enfin j’espère. En gmis il faut au moins 15s pour ne pas être en timeout.

**Comment by TmpName** [comment]
Mets plutot (.+?) au lieu de (.*?) mais sinon je vois pas pkoi Vstream supprimerait les "=", en general le traitement se fait sur les caracteres vides. Y aurait pas un replace qui trainerait quelque part ?
Ou tu ferais pas un truc du genre var[1] au lieu de var (vu que ca n'afficherait que le deuxieme caractere)

**Comment by razorex** [comment]
@TmpName j'avais déjà testé c'est pareil.

**Comment by TmpName** [comment]
Fais passer le code pr voir ?

**Comment by razorex** [comment]
Merci [ici](https://pastebin.com/HAFg5PVp)

**Comment by TmpName** [comment]
J'ai fais mes tests dans showSeriesAz() et c'est bien ca.
Remplaces aEntry[0] par aEntry ligne 121 et 122.

**Comment by razorex** [comment]
Merci pour l'aide. j'avais pas compris le var[1] et var dsl. 
Par contre je comprend pas ce que tu veux dire par la suite.

**Comment by TmpName** [comment]
Regarde dans le site series_en_streaming_tv, fonction AlphaSearch(), pas de regex. Elle y est aussi dans voirfilm.

**Comment by razorex** [comment]
exact tu écris une liste.

**Comment by johngf** [comment]
@razorex [tu as lu en bas](https://github.com/Kodi-vStream/venom-xbmc-addons/commit/ccedcf37d8dbaa2248b2ac3fe0c4d0881549c528) ne met pas la fonction dialog pour 1 ou quelque hosters
c'est inutile

**Comment by razorex** [comment]
Dsl je viens de voir..
et la fonction `cUtil().DecoTitle` utile ou pas??? avant que je fasse une connerie.

**Comment by Arias800** [comment]
Si ça marche sans pas besoin je crois

**Comment by razorex** [comment]
oui normalement c'est vStream qui ce charge de le faire dans son "coeur" comme pour les séries.

**Comment by johngf** [comment]
cUtil().DecoTitle tu peut l'enlever elle a été remplacée par la fonction traitement du text global

**Comment by razorex** [comment]
Je profite de ce post pour pose rune question. J'ai remarqué qu'en désactivant le 
`#sThumb = oInputParameterHandler.getValue('sThumb')` l'affiche s'affiche (lol). est ce que l'on ne peut pas supprimer cette instruction et gagner en traitement et modifier exemple  :
`cHosterGui().showHoster(oGui, oHoster, sHosterUrl)` en supprimant la dernière instruction.
ou alors est elle présente pour des questions de compatibilité????
Pareil pour les synopsis, ont les affichent alors qu'il n'y a pas `oInput`
Merci

**Comment by johngf** [comment]
Pour httpfox desinstalle firefox 56 et installe le 54 on le trouve sur le net en exe
Seul solution
Et quand il te propose une maj tu refuse

**Comment by LordVenom** [comment]
Non ont peux pas c'est utile ou cas ou ça reload, fin de lecture par exemple et surtout pour l'ajout au marque page.

**Comment by razorex** [comment]
Pas d'alternative à httpfox???  je t'avais adresser un autre message @LordVenom à ce propos. merci.

**Comment by TmpName** [comment]
Pareil, j'ai aussi une vielle version de firefox, trop de trucs qui ne marche pas sur la nouvelle.
