### ISSUE TITLE
vStream 1fichier

### ISSUE THREAD

**Issue by vstreamkodi** [Kodi-vStream/venom-xbmc-addons#2025]
Les liens 1fichier.com ne fonctionnent plus depuis la mise à jour. Affichage 1fichier resolve / fichier introuvable. L' authentification du compte premium ne semble pas se faire (pas de message réussi ou raté). La modification du fichier premiumhandler.py du post #1994 résoud le problème.

**Comment by TmpName** [comment]
Alors je pense que la modif pr 1fichier a du etre zappee lors des differentes versions.
Je vais essayer de refusionner le code actuel avec le code @JimmyLaurent

**Comment by vstreamkodi** [comment]
Oui, ça fonctionne avec ce fichier.

**Comment by TmpName** [comment]
Bon ben , dsl, y a eu un rattage, now zetes bon pr attendre la prochaine version ou bidouiller les fichiers.

**Comment by LordVenom** [comment]
Logiquement j'ai modifier le zip si tu réinstall la version 0.6.1 ça devrais rouler.
