### ISSUE TITLE
ianime cloudflare erreur connection

### ISSUE THREAD

**Issue by tekenai** [Kodi-vStream/venom-xbmc-addons#2026]
Bonjour,
Depuis quelques temps ianime ne fonctionne plus.
j'avais une erreur cloudflare ensuite c'est devenue une erreur connection failed (503).
Est-ce qu'il y a moyen de rectifier ça par une mise à jour? ou c'est d'une autre ordre.

Merci pour votre travail. 

Bonne journée

**Comment by LordVenom** [comment]
Pas vue de soucis moi dsl

**Comment by TmpName** [comment]
Cloudflare a ete mit a jour avec la version de VSstream qui date de 3/4 jours.
Je viens de tester avec gumgum qui est encore sous protection cloudflare, pas vu de prbs.

**Comment by tekenai** [comment]
Merci bcp

**Comment by tekenai** [comment]
Désoler mon erreur. je croyais m'en tirer avec des clear et des update dans la config. :)
donc c'est repartis pour désinstallation et réinstallation. 4 androids (kodi, ftmc et spmc) et 3 ordi avec kodi.
pour l'instant ftmc ferme lorsque la video s’apprête a ouvrir.  ça doit être du côté de ftmc qui est kodi 16.1 custom
kodi 17 avec vstream 6.0.1 ianime fonctionne :) mais gumgum a disparu :) drôle de coïncidence.
Merci vous êtes rapide sur le clavier. 
Bonne fin de journée ou bonne soirée ou ....   :)
