### ISSUE TITLE
Problème TVRex

### ISSUE THREAD

**Issue by Waaaario** [Kodi-vStream/venom-xbmc-addons#2031]
Bonjour,

La source TVrex.net (matchs NBA) ne fonctionne plus correctement :
- La liste Replay NBA games ne se met pas correctement à jour (beaucoup de matchs présents sur le site ne sont pas visible dans vstream);
- Quand on clique sur un match, cela renvoie vers un autre match (URL erronée);
- Vstream indique parfois "Live/replay non disponible" alors qu'il est visible sur le site.

J'ai regardé le .py mais mes faibles connaissances ne m'ont pas permis de détecter d'où vient le soucis.

Merci de votre aide.

**Comment by razorex** [comment]
J'avais commencer à reprendre ce site, il faut que je m'y remette.

**Comment by Waaaario** [comment]
Merci beaucoup. S'il y a besoin de testeur, je suis partant.

**Comment by johngf** [comment]
@Waaaario je l'ai mis a jour du moins commencé par contre pas de live dispo pour le moment.
pour que le live fonctionne il faudrait testé pendant la diffusion d'un match en direct pour pouvoir le faire fonctionné

**Comment by razorex** [comment]
Pour les fans de sport j'ai réaliser beaucoup de modif sur Robin des droits. Allez y jeter un oeil. Par contre que du replay.

**Comment by KiliK150** [comment]
@razorex un grand merci pour ton gros boulot sur Robin des droits ( un de mes site préféré sur Vstream) , l'interface est beaucoup plus clair , plus simple ... Au top !
