### ISSUE TITLE
Téléchargement multiples

### ISSUE THREAD

**Issue by mightyjay999** [Kodi-vStream/venom-xbmc-addons#2032]
Est il possible de télécharger plusieurs films en même temps  pour visionner en mode hors ligne car vstream telecharge un seul fichier et crée des fichiers vide pour tout les autres

**Comment by Arias800** [comment]
Il me semble que le téléchargement est gérée par un add-on qui ne nous appartient pas donc à mon avis on ne peux rien . Attend la confirmation au ça où

**Comment by LordVenom** [comment]
Ha oui c'est pas normal, logiquement vstream gere une liste et fait le téléchargement 1 par 1 à la suite.
J'ai surement casser un truc quand j'ai modifier je regarderais Merci.

**Comment by TmpName** [comment]
La fonction "telecharger + visualiser" ne marche que pour 1 film.
Le telechargement comme le dit @LordVenom fonctionne par liste, et on ne peut en telecharger qu'un par un. Il y a un gestionnaire de telechargement pour pourvoir relancer le DL ou changer de fichier.

**Comment by mightyjay999** [comment]
@TmpName Je telecharge et Visionne autre chose et cela ne fonctionne pas des fichier sont crée et le téléchargement des films suivant ne démarre pas après que le premier aie terminé mais je n’aie pas tenté de charger plusieurs films sans visionner quoi que ce soit par contre

**Comment by mightyjay999** [comment]
Il faudra que je farfouille ce soir car j’en suis à mes débuts sur la plateforme Kodi je n’aie  pas vus qu’il y  avais un gestionnaire de téléchargement

**Comment by TmpName** [comment]
Pas dans kodi, dans Vstream, car c'est de ces telechargements que je parle.
Quand tu es sur unlien hebergeur final, clic droit > telecharger.

**Comment by mightyjay999** [comment]
J’essaie présentement mais les téléchargement sont tellement lent je ne saurais que lorsque c’est terminé

**Comment by mightyjay999** [comment]
Et oui le téléchargement résume si je le fait à la main

**Comment by LordVenom** [comment]
Note : kodi nous donne la possibilité de choisir le dossier mes avec les permissions linux impossible de changer le dossier sans une erreur de perm. Dossier autoriser a ecrire (.kodi/userdata/addon_data/plugin.video.vstream)
