### ISSUE TITLE
Plus de bandes annonces ?

### ISSUE THREAD

**Issue by romasterr** [Kodi-vStream/venom-xbmc-addons#2033]
Bonjour tout le monde, depuis la dernière mise à jour, je n'ai plus accès aux bandes annonces, quand je clique dessus, ça me dit "Erreur Vstream, consulter le journal..." 

Quelqu'un aurait une idée ?

Merci

**Comment by johngf** [comment]
c'est surement parce qu'il y a pas de bande annonce pour le film 
je viens de testé ça fonctionne

**Comment by romasterr** [comment]
Et non, ça me le fait pour tous les films, j'en ai essayé une vingtaine, et toujours pareil, avant la MAJ, c'était nickel :/

**Comment by johngf** [comment]
sur quel site ?

**Comment by romasterr** [comment]
Comment ça ? Je lance Kodi, Vstream, recherche de film en visuel, puis en fonction du film je mets la BA

**Comment by johngf** [comment]
bah chez moi ça fonctionne regarde dans le fichier kodi.log si tu y a accés 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by romasterr** [comment]
Je viens d'essayer, je n'y ai pas accès

**Comment by romasterr** [comment]
C'est bon, j'ai installé l'extension, je peux enfin voir le log :)

**Comment by romasterr** [comment]
![f183e743-32ae-4667-af36-66dae4bdc45e](https://user-images.githubusercontent.com/38556523/39048941-97197e30-449f-11e8-878b-0ccc48158f6a.jpeg)
![5efe1dc1-6282-4ccd-a938-51dd9cd6c224](https://user-images.githubusercontent.com/38556523/39048942-973a0448-449f-11e8-9114-76b5aa2cf4db.jpeg)

**Comment by Arias800** [comment]
Tu a une version ultérieure à kodi 17

**Comment by johngf** [comment]
ah ok tu a kodi16 ? le ssl n'est pas pris en charge.

**Comment by romasterr** [comment]
Pas de soucis, surtout que c’est seulement depuis la mise à jour d’ici y a quelques jours, merci à vous tous :)

**Comment by romasterr** [comment]
Et pour la précision, j'utilise Kodi 16.0 Jarvis, car mon appareil ne me permet pas d'aller au delà, il est en 4.4.2

**Comment by romasterr** [comment]
Du coup je modifie quoi et comment ? ^^

**Comment by TmpName** [comment]
Ici tu as les modifs qui posent problemes https://github.com/Kodi-vStream/venom-xbmc-addons/commit/e9d587b9209dbadf81881bb350d95f676f0c37c7

Mais je sais pas trop quoi faire, car la derniere version marche chez plus de monde, sauf si vielle version de kodi, enfin je ne pense pas etre le seul avec ce prb.

**Comment by romasterr** [comment]
Que je comprenne bien, tu as le meme’ soucis que moi c’est ça ?

Parce que je trouve ça génial les bandes annonces :/

Si non, y a t’il une astuce pour passé à kodi 17 sur mon vieux mxq ?

**Comment by TmpName** [comment]
Non moi c'est l'inverse, c'est sans la modif que ca ne marche plus.
J'ai fais comme le dit @johngf la nouvelle version devrait marcher pour nous deux.

**Comment by romasterr** [comment]
Ah ok d'accord ! 

La nouvelle version de Vstream ? Car juste au cas où, j'ai installé Kodi 16.1, c'est KO. Avec Mygica c'est nickel, mais que c'est mou -____-

Donc si au cas où avec le prochain Vstream ça passe pas, je vais flasher le firmware de mon S805 pour y mettre Android 5.1.1 et passer sur Kodi 17 !

**Comment by TmpName** [comment]
Nope, tu peux juste changer le fichier.

**Comment by romasterr** [comment]
Quel fichier ? Et comment ? J’avoue ne pas comprendre

**Comment by romasterr** [comment]
Excusez les gars, j'ai vu le fichier, mais je veux dire qu'on le remplace comment ??

**Comment by romasterr** [comment]
Je ré édit encore une fois, je trouve pas le chemin sur Android pour le modifier :/

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-vStream

**Comment by romasterr** [comment]
Merci, mais ça ne fonctionne toujours pas pour moi :/

J'ai téléchargé le fichier, l'ai renommé en ba.py, l'ai remplacé à la place de l'autre, j'ai redémarre la box android, et toujours le soucis :(

**Comment by LordVenom** [comment]
Renommer le fichier en ba.py ? il ce nomme comme ça quand tu le prend.

https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/lib/ba.py

Enregistrer la page sous.

**Comment by romasterr** [comment]
C'est exactement ce que j'avais fait, sauf que moi il n'était pas déjà renommé, je viens de réessayer, et c'est ok, j'avais du faire une erreur.

En tout cas merci à tous pour votre aide, c'est vraiment top, à bientôt les passionnés !
