### ISSUE TITLE
Sources uptobox

### ISSUE THREAD

**Issue by Kiribou** [Kodi-vStream/venom-xbmc-addons#2034]
Salut à tous,
Depuis quelques temps, je trouve de moins en moins de contenu uptobox voir rien du tout. 
Sur ddl-island par exemple et même tous les autres sites. 
Vous avez également le souci ? 
Merci de vos retours

**Comment by Kiribou** [comment]
Ps : kodi sur raspberry pi

**Comment by Arias800** [comment]
Tu à la version 0.6.1 de vstream ?

**Comment by Kiribou** [comment]
Non la 0.6.0 (dernière maj dl il y a 2 jours je crois)

**Comment by Arias800** [comment]
Et bah la 0.6.1 règle le problème normalement https://github.com/Kodi-vStream/venom-xbmc-addons/releases/

**Comment by Kiribou** [comment]
Ok super, la maj ne m'étais pas proposer en auto.
Je clôture 
Merci
