### ISSUE TITLE
Mise à jour de Vstream

### ISSUE THREAD

**Issue by pplanteg** [Kodi-vStream/venom-xbmc-addons#2035]
Bonjour, j'ai le repo qui est configuré dans mon raspberry, je vois qu'il y a une mise à jour de l'addon Vstream vers 6.1  mais je la mise a jour ne s'effectue pas a partir du repo.

Je suis donc obligé de telecharger le .zip pour faire l'installation.

est-ce normal ?

merci de vos reponses

bonne soirée

**Comment by LordVenom** [comment]
Kodi vérifies les mises a jour sur les repo tous les X temps donc oui tu peux avoir une mise a jour sans que Kodi ne la lance.

Tu peux forcer l'installation directement depuis Kodi.

vStream repository / extention video / vstream / (menu contextuel) / information / mettre à jour.
