### ISSUE TITLE
Probleme parametres.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2036]
+ Parametres Vstream
+ Sources
+ Activer/desactiver sources

>>File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\runscript.py", line 161, in main
from resources.lib.handler.pluginHandler import cPluginHandler
ImportError: No module named handler.pluginHandler

**Comment by LordVenom** [comment]
Resolut logiquement.

**Comment by TmpName** [comment]
Pas sur, j'ai deja fait ca, y a un second prb qui arrive du coup.

**Comment by LordVenom** [comment]
Les deux tourne chez moi Xd 
Soit il faut remonter le fichier, soit il faut trouver un moyen de suppirmer le sys path kodi/addons/plugin.video.vstream/resources/lib 
puisque nous on lui donne 
kodi/addons/plugin.video.vstream

**Comment by LordVenom** [comment]
Test avec sys.path.remove(sys.path[0]) et ensuite tous les import en normal 

from resources.lib.util import VStranslatePath
from resources.lib.config import cConfig

ect..

**Comment by TmpName** [comment]
Tjours pas 
>17:13:41.398 T:1712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named util
                                            Traceback (most recent call last):
                                              File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\runscript.py", line 14, in <module>
                                                from resources.lib.util import VStranslatePath
                                            ImportError: No module named util
                                            -->End of Python script error report<--

J'ai essaye plusieurs variante, ca marche pas mieux.

**Comment by TmpName** [comment]
Bon je laisse tomber, ca et les unicode .....
Mais y a que chez moi que ca deconne ?

Rien que ca je comprend pas pkoi ca marche pas
>sLibrary = xbmc.translatePath(vstream.getAddonInfo("path")).decode("utf-8")
sys.path.append (sLibrary)
from resources.lib.util import VStranslatePath

**Comment by LordVenom** [comment]
verifie ton sys path si tu as d'autre vstream genre vstream/lib ect.. ça foux la merde.

**Comment by TmpName** [comment]
Meme pas
>17:39:08.946 T:2116  NOTICE: 	[PLUGIN] Vstream: ['C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.pyamf\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.dialogaddonscan\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.beautifulsoup4\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.httplib2\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.myconnpy\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.beautifulsoup\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.common.plugin.cache\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.pytz\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.video.F4mProxy\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.actionhandler\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.exodus.artwork\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.exodus.metadata\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.buggalo\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.t9.search\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.xbmcswift2\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.addon.signals\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.t0mm0.common\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.autocompletion\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.simplejson\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.youtube.dl\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.addon.common\\lib', 'C:\\Applications\\Kodi\\addons\\script.module.pil\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.unidecode\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.simple.downloader\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\plugin.video.youtube\\resources\\lib\\', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.requests\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.urlresolver\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.parsedom\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.elementtree\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.metahandler\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.routing\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.kodi65\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.exodus\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.certifi\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.chardet\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.idna\\lib', 'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\script.module.urllib3\\lib', 'C:\\Applications\\Kodi\\system\\python\\DLLs', 'C:\\Applications\\Kodi\\system\\python\\Lib', 'C:\\Applications\\Kodi\\python27.zip', 'C:\\Applications\\Kodi\\system\\python\\lib\\plat-win', 'C:\\Applications\\Kodi\\system\\python\\lib\\lib-tk', 'C:\\Applications\\Kodi', 'C:\\Applications\\Kodi\\system\\python', 'C:\\Applications\\Kodi\\system\\python\\lib\\site-packages', u'C:\\Users\\BRIX\\AppData\\Roaming\\Kodi\\addons\\plugin.video.vstream']

**Comment by LordVenom** [comment]
VStranslatePath et utiliser que dans ce fichier les autre son apeller util.VSlang
from resources.lib import util

ça devrais fonctionner cette modif tu as tester ?

**Comment by TmpName** [comment]
Mais tu as raisons, j'ai fais un 
sys.path = [sLibrary]
Et ca a marche, bon ca a redeconne plus loin, mais l'import a marche. pkoi j'ai autant de merde dans Sys.path. ?

**Comment by LordVenom** [comment]
En print sur runscript voici le mien

 ['/usr/share/kodi/addons/script.module.pil/lib', '/home/lordvenom/.kodi/addons/script.module.certifi/lib', '/home/lordvenom/.kodi/addons/script.module.chardet/lib', '/home/lordvenom/.kodi/addons/script.module.idna/lib', '/home/lordvenom/.kodi/addons/script.module.urllib3/lib', '/home/lordvenom/.kodi/addons/script.module.requests/lib', '/home/lordvenom/.kodi/addons/plugin.video.youtube/resources/lib/', '/home/lordvenom/.kodi/addons/script.common.plugin.cache/lib', '/home/lordvenom/.kodi/addons/script.module.simplejson/lib', '/home/lordvenom/.kodi/addons/script.module.beautifulsoup/lib', '/home/lordvenom/.kodi/addons/script.module.six/lib', '/home/lordvenom/.kodi/addons/script.module.unidecode/lib', '/home/lordvenom/.kodi/addons/script.module.dateutil/lib', '/home/lordvenom/.kodi/addons/script.module.arrow/lib', '/home/lordvenom/.kodi/addons/script.module.musicbrainz/lib', '/home/lordvenom/.kodi/addons/script.module.simplecache/lib', '/home/lordvenom/.kodi/addons/script.module.thetvdb/lib', '/home/lordvenom/.kodi/addons/script.module.metadatautils/lib', '/home/lordvenom/.kodi/addons/script.module.autocompletion/lib', '/home/lordvenom/.kodi/addons/script.module.addon.signals/lib', '/home/lordvenom/.kodi/addons/script.module.youtube.dl/lib', '/home/lordvenom/.kodi/addons/script.module.kodi65/lib', '/home/lordvenom/.kodi/addons/script.module.routing/lib', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/lordvenom/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', u'/home/lordvenom/.kodi/addons/plugin.video.vstream']

Y a aussi beaucoup de merde.

**Comment by LordVenom** [comment]
C'est pour virer le  plugin.video.vstream/resources/lib que j'ai ajouter sys.path.remove(sys.path[0]) mais oui il et pas forcement a la premiere placer.Si je vire ce resources/lib j'ai plus de soucis d'imports.

**Comment by TmpName** [comment]
Lol, je viens de voir ta derniere modif, joli, bon ca marche pas, mais j'ai hallucine en voyant jusqu'ou ca peut aller cette histoire.

Sinon j'ai une autre piste qui marche chez moi, je te laisse tester chez toi ^^. En fait python lit les chemin dans sys.path dans l'ordre, des qu'il en trouve un qui correspond, il teste. Donc 2 solutions: 

1- faire un chemin d'acces qui ne corresponde a aucun autre, pas trouve comment vu qu'on demarre a "ressources", pas trouve comment le faire chercher dans "plugin.video.vstream"
2- solution mettre le chemin de vstream en debut de liste, et ca a l'air de tourner chez moi.

>vstream = xbmcaddon.Addon('plugin.video.vstream')
sLibrary = xbmc.translatePath(vstream.getAddonInfo("path")).decode("utf-8")
sys.path.insert (0,sLibrary)

En fait append le rajoute mais obligatoirement en fin de liste.

Mais la je comprend pas pkoi on doit aller aussi loin pr faire tourner le code ....

**Comment by LordVenom** [comment]
Ca fonctionne chez moi. mais tu n'a pas de probleme de mise a jour comme about.py utilise le même style d'import ?

- Tu ne peux pas spécifier si une source et pour les séries ou les films 
il suffi de lire la desciption du site pour voir ceux quelle fait et si tu la désactive elle et désactiver pour tous.

**Comment by TmpName** [comment]
Nope, ou alors j'ai pas encore eu de probleme, et c'est arrive d'un coup (bon ok je vais pas souvent voir les parametres).
Je cherchais a modifier ca, car par exemple ca cherche les series dans kepliz, alors qu'il n y en a pas.

**Comment by TmpName** [comment]
Kepliz pas kaydo, pas de series sur le site.
Sinon yep avec la derniere modif ca tourne.

**Comment by LordVenom** [comment]
lol ben même reponse pourquoi y a ça

`URL_SEARCH_SERIES = ('', 'showMovies')`

Je le vire de suite.

**Comment by TmpName** [comment]
lol.
Tu te rend compte que cette simple ligne me pourris la vie depuis 3 jours, sans elle j'aurais rien vu du tout.
