### ISSUE TITLE
1 fichier ne fonctionne plus

### ISSUE THREAD

**Issue by rod93** [Kodi-vStream/venom-xbmc-addons#2037]
Bonjour les’liens 1 fichier ne fonctionnent plus «  fichier introuvable « 
Merci

**Comment by reds07** [comment]
Bonjour, même chose pour moi depuis plusieurs jours, malgré la mise à jour de ce matin. Quelqu'un pour nous aider. Merci d'avance

**Comment by vstreamkodi** [comment]
Les liens 1fichier fonctionnent en faisant l'installation depuis un zip dans kodi -> voir issue #2025. 
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/download/v0.6.1/plugin.video.vstream-0.6.1.zip

**Comment by TmpName** [comment]
C'est ce que j'allais demander, y a pas deja une MAJ qui corrige ca ?

**Comment by rod93** [comment]
merci tout fonctionnement avec le zip

**Comment by thorsten68** [comment]
Ça a marché aussi pour moi, merci beaucoup !!

**Comment by thorsten68** [comment]
Pour l'instant les mises a jour ne corrigent pas le problème, j'avais le plugin vidéo 0.6.1 a jour mais il faut télécharger celui du lien ci dessus et miracle tout rentre dans l'ordre....
Merci pour le taf

**Comment by thorsten68** [comment]
T'as téléchargé le ZIP ci dessus ?

**Comment by perive** [comment]
J'ai récupéré tous les fichiers du zip ci-dessus mais ça résout pas le problème de 1fichier !
