### ISSUE TITLE
Aide pour une fonction annexe !

### ISSUE THREAD

**Issue by Saab51** [Kodi-vStream/venom-xbmc-addons#2044]
On va me dire que Vstream n'es pas fait pour ca mais j'essaye quand meme !
J'ai crée une source pour voir des photo avec vstream tout marche a peu pres ,les différents répertoires s'affichent avec les differents lien en dessous les miniatures et titres etc mais quand je veut afficher une page ,bah "aucune information" les regex et tout ca sont bon mais je suppose que vstream cherche un lien hebergeur !

> def showHosters(): #recherche et affiche les hotes
>     oGui = cGui() #ouvre l'affichage
>     oInputParameterHandler = cInputParameterHandler() #apelle l'entree de parametre
>     sUrl = oInputParameterHandler.getValue('siteUrl') #apelle siteUrl
>     sMovieTitle = oInputParameterHandler.getValue('sMovieTitle') #appelle le titre
>     sThumb = oInputParameterHandler.getValue('sThumb') #appelle le poster
> 
>     oRequestHandler = cRequestHandler(sUrl) #requete sur l'url
>     sHtmlContent = oRequestHandler.request(); #requete sur l'url
> 
>     oParser = cParser()
>     sPattern = '<img id="img" src="([^"]+)" style="'
>     #ici nous cherchons toute les sources iframe
> 
>     aResult = oParser.parse(sHtmlContent, sPattern)
>     #pensez a faire un xbmc.log(str(aResult)) pour verifier
> 
>     #si un lien ne s'affiche pas peux etre que l'hote n'est pas supporte par l'addon
>     if (aResult[0] == True):
>         for aEntry in aResult[1]:
>             sUrl2 = str(aEntry[0])
>             sHosterUrl = str(aEntry)
>             oHoster = cHosterGui().checkHoster(sHosterUrl) #recherche l'hote dans l'addon
>             if (oHoster != False):
>                 oHoster.setDisplayName(sMovieTitle) #nom affiche
>                 oHoster.setFileName(sMovieTitle) #idem
>                 cHosterGui().showHoster(oGui, oHoster, sHosterUrl, sThumb)
>                 #affiche le lien (oGui, oHoster, url du lien, poster)
> 
>     oGui.setEndOfDirectory() #fin

**Comment by LordVenom** [comment]
Oui tu as compris 
`cHosterGui().checkHoster(sHosterUrl)`

Recherche dans le lien web le bon hébergeur.
Si tu veut réafficher une photo utilise addDir.

```
oOutputParameterHandler = cOutputParameterHandler() oOutputParameterHandler.addParameter('siteUrl', 'http://')
oGui.addDir(SITE_IDENTIFIER, 'function', 'titre', 'image.png', oOutputParameterHandler)
```

Ou si tu veut une photo avec lien non clickable

`oGui.addText('function', 'titre', 'image.png')`

**Comment by Saab51** [comment]
Hum Oo
 oGui = cGui()
    oInputParameterHandler = cInputParameterHandler()
    sUrl = oInputParameterHandler.getValue('siteUrl')
    sMovieTitle = oInputParameterHandler.getValue('sMovieTitle')
    sThumb = oInputParameterHandler.getValue('sThumb')

    oRequestHandler = cRequestHandler(sUrl)
    sHtmlContent = oRequestHandler.request()

    sPattern = '<img id="img" src="([^"]+)" style="'
    oParser = cParser()
    aResult = oParser.parse(sHtmlContent, sPattern)
    if (aResult[0] == True):
        for aEntry in aResult[1]:
            
            sUrl = str(aEntry[0])
            
            oOutputParameterHandler = cOutputParameterHandler() 
            oOutputParameterHandler.addParameter('siteUrl', 'http://')
            oGui.addText('function', 'titre', 'image.png')
            

    oGui.setEndOfDirectory()
