### ISSUE TITLE
VStream uptobox

### ISSUE THREAD

**Issue by vstreamkodi** [Kodi-vStream/venom-xbmc-addons#2045]
Les liens uptobox ne fonctionne plus. La team uptobox a encore modifié quelque chose. Ça fait la 3ème fois qu'il bloque la lecture de leur fichier par vStream en moins de 2 mois. L'authentification premium est bien réussi mais le fichier est introuvable. Dans VotreCompteUptobox sous vStream, mes fichiers sont présents mais impossible de les telecharger (fichier introuvable). Ce qui semble changer via un navigateur web, c'est 48 pop-up qui apparaissent lors de la tentative de lecture d'un fichier uptostream sans avoir authentifié le compte. L'accès au fichier reste disponible uniquement via un navigateur web avec compte authentifié.

**Comment by isandard** [comment]
J'avais le problème hier soir sur mon pc, je viens de tester sur ma mini 4k et ça fonctionne.
En regardant la différence entre les deux versions, je me suis rendu compte que le pc etait toujours en 0.59.

J'ai forcé la mise à jour en 0.61 et hop ça marche, donc je te conseillerais de regarder ta version de vstream au cas où

**Comment by vic1997** [comment]
Chez moi ça marche niquel. Sur mon compte UpToBox avec la dernière version de vStream.

**Comment by vstreamkodi** [comment]
J'ai réinstallé la release du 0.6.1 et ça fonctionne. Je comprends pas pourquoi le zip 0.6.1 du début modifié avec le fichier de jimmylaurent a cessé fonctionné. Bref mea culpa.
