### ISSUE TITLE
Papystreaming de retour

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2046]
Papystreaming est de retour ttp://papystreaming.com/fr/.

j'ai commencer à le reprendre avec le fichier d'origine mais je ne suis pas sur qu'il soit possible d'afficher les liens de l’hôte. Quelqu'un peut regarder et me dire s'il est utile d'aller plus loin??? 

Merci

**Comment by johngf** [comment]
C'est pas papy stream ,c'est une copie inutile qui existait déjà quand j'ai fait le code pour le site

**Comment by razorex** [comment]
Celui que j'ai mis en lien c'est bien du cacaoweb. J'ai pu accéder au stream sans payé.

**Comment by TmpName** [comment]
Yep, mais va voir sur leur forum.
C'est pas indique a la base, il ne faut surtout pas installer leur appli. Tu peux acceder au liens avec magouille mais si tu regarde les plaintes sur leur forum, c'est la que j'avias vu a l'epoque la description des "quotas".
En gratuit tu es bride.

**Comment by razorex** [comment]
Ok je laisse tomber alors. Je l'ai mise sur le GIT.
