### ISSUE TITLE
Erreur Pochettes Métadonnés TMDB 

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2047]
Salut à tous,
Je voudrais savoir si c'est possible d'activer la recherche de Métadonné TMDB sur Vstream mais en laissant les pochettes d'origine du site visité.
Je sais pas si je suis clair, mais quand on va sur certains sites, parfois il n'y a pas de pochettes présentés ou alors la métadonné ce trompe en mettant la pochette d'un film avec le même titre.
Exemple : 
![screenshot_10](https://user-images.githubusercontent.com/12912677/39392342-3aa84f9e-4ab4-11e8-8d42-3df455fa6649.jpg)
Donc je voudrais juste savoir si c'est possible de seulement recherché le Fanart ?

**Comment by LordVenom** [comment]
Hé oui personne n'est parfait même vStream ce trompe parfois XD. Non ont peux rien n'y faire dsl.

**Comment by lebigboss** [comment]
@LordVenom  Loll non ce n'est pas Vstream qui ce trompe c'est TMDB
Mais je pensais qu'il y avait quand même un moyen de supprimé une ligne du script pour faire que des recherches de Fanart
Dommage alors
