### ISSUE TITLE
addLink

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2048]
Ajout d'un menu rapide addLink pour les fonctions showLinks:

Pour le moment les fonctions showLinks sont code avec addMovie mais sont utilise pour des films des series ect et donc retourne la mauvaise catégorie à showhoster.

addLink 
- Vus Liste pas de modification possible
- Pas de context (on peux plus les marquer vus ni les enregistrer en marque page)
- Utilise le fanart du dossier précédent.
- Utilise le sCat du dossier précédent.
- Pas de Méta possible.

**Comment by johngf** [comment]
Perso je préfère quand on a la possibilité de mettre en marque page, ou favoris de kodi 
J'y met tous et n'importe quoi c'est juste un pense bete

**Comment by LordVenom** [comment]
Oui pareil mais la ce sont que des liens alors autant revenir avant pour avoir toute la liste ou aprés pour avoir le lien final.

**Comment by AizenKnower** [comment]
Ce serait bien aussi de trier par nom (excluant la saison qui début souvent le nom de la serie)
Car quand on découvre des series on les met en marque page et quand nombreux c'est fastidieux de chercher les saisons d une serie pour les regarder en playlist

De meme que trier les videos par site hebergement comme ça  on peut les lire a partir d un episode au suivant sans que l episode se repete avec le 2e site hebergement si vous voyez ce que je ve dire

**Comment by LordVenom** [comment]
Ben y a que 2 solution. soit juste la modif addlink soit ont vire pour charger tous les liens direct ?

**Comment by AizenKnower** [comment]
Justement je parle aussi de cette page là 
Quand on fait lire a partir de cette episode il lit le lien suivant or c'est  le meme episode mais sur un hebergeur different 

Et trier par hébergeur on peut pas? Un peu comme ddl-island qui eux separe les episodes par hébergeur 

Merci

**Comment by TmpName** [comment]
Suffit de mettre en marque page le nom de la serie, pas le hoster final, moi dans mes favoris, y a juste "serie1" "serie2" "serie3", me faut cliquer dessus pour avoir les saisons et episodes.

Et pour moi, non pas possible, car je suis peut etre un mutant mais quand je veux voir une serie, je choisis dans l'ordre
Titre > saisons > episode > hoster et pas Hoster > episode.

**Comment by LordVenom** [comment]
Bon j'ai fait un test dite moi si l'idée et bonne ou pas j'ai passer addlink avec un threads.

Voir fichier cineiz fonction showLinks et showHosters2.

**Comment by TmpName** [comment]
Ben je sais pas ce que ca va donner selon les connections mais chez moi c'est plus long avec les threads (pour une page en moins).
Mais ce qui me fait peur c'est que j'ai eu un freeze aussi, c'est le genre de bug aleatoire que j'ai aussi avec les donwloads.

Par contre c'est con mais c'est vraiement bien fait comme code. Du coup on a un tuto sur les thread ^^.

**Comment by LordVenom** [comment]
Ok on oublie chez moi c'est rapide mais pas dans le bon ordre.

**Comment by TmpName** [comment]
L'ordre a une importance ?

**Comment by LordVenom** [comment]
Oui sur certain site c'est organiser

- title (vf) (host)
et d'autre
- VF
-- title (host)
