### ISSUE TITLE
Aucun lien fonctionne sur kepliz

### ISSUE THREAD

**Issue by boulbix** [Kodi-vStream/venom-xbmc-addons#2049]
Bonjour au niveau des liens kepliz aucun lien dispo ne fonctionne avez vous une idée ?

**Comment by 1shad** [comment]
Salut !    
Est-ce que tu as fais la dernière mise à jours ?

**Comment by boulbix** [comment]
Oui j’ai une mise à jour hier je viens de réessayé c’est idem

**Comment by boulbix** [comment]
Films hd / kepliz j’ai testé sur tablette même problème

**Comment by 1shad** [comment]
Quand tu choisis une vidéo, est-ce que tu vois les deux liens (360p et 720p) ou non ?  

Si tu ne les vois pas, remplace le fichier "kepliz_com.py" sur ton disque par celui de la béta.  
Dispo ici: [kepliz_com.py](https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/kepliz_com.py)

**Comment by boulbix** [comment]
Non je ne vois pas 360p et 720p comment je procède ou est situé ce fichier ?

**Comment by TmpName** [comment]
Mise a jour de Vstream ou mise a jour dans Vstream ?

**Comment by 1shad** [comment]
Ah oui, Je n'avais pas précisé. C'était la mise à jours dans Vstream.  
Mais peut-être qu'il faudrait mettre à jours Vstream pour que cela fonctionne automatiquement. Et que tu n'ai pas à toucher toi même aux fichiers.

(Je n'ai pas de windows sous la main donc je ne peux pas te donner le répertoire qui va bien.)

**Comment by boulbix** [comment]
J’ai remplacé le fichier je vois les dossiers 360 et 720 mais rien j’en vais attendre la prochaine mise à jour
