### ISSUE TITLE
encodage caractères accentués : synopsis film

### ISSUE THREAD

**Issue by nekcorp** [Kodi-vStream/venom-xbmc-addons#2050]
Bonjour,

Merci pour votre travail, c'est super génial ce que vous faites. Pouvez vous me dire comment vous faites pour que sous Kody les caractères accentués, apostrophes etc .... soient écrit correctement, comment encodez vous où décodez vous le texte ? Je vous demande ça car je suis entrain d'essayer d'apporter ma pierre à l'édifice. J'arrive à récupérer les titres, genre, images liens des films d'un site web, sous Kodi tout fonctionne sauf la retranscription des caractères accentués. J'ai une variable _description_ qui reprend la synopsis du film et qui est du type : **<type 'unicode'>**, mais en faisant un description.decode("utf-8") j'ai toujours pas les caractères correctement accentués sous Kodi. Je bloque dessus depuis hier. Merci pour votre aide.

**Comment by Arias800** [comment]
Tu peux faire un replace par exemple pour la variable string tu faire string.replace('é',',e') ce qui aura pour effet de remplacer le é par e  , il me semble que c'est comme ça en gros la manière donc fonctionne vstream mais je suis pas sur à 100% ^^

**Comment by nekcorp** [comment]
@Arias800, s'ils font comme ça c'est pas très propre, j'attend un retour de leur part car il ne me reste pas grand chose pour proposer quelque chose de propre et fonctionnel.

**Comment by johngf** [comment]
poste un exemple de ce que tu veut convertir sur pastebin et donne l'adresse ici ça sera plus simple
il y a des encodages différent : latin iso utf8 ...

**Comment by Arias800** [comment]
Après ça peut être utiliser temporairement le temps de trouver quelque chose de mieux au pire des cas ^^

**Comment by TmpName** [comment]
Perso, ca fait 10 ans que je n'utilise plus d'accents. Ca sert obsolument a rien, ca exite la fana de la langue francaise, mais le texte sans accent se lit tres bien.

**Comment by nekcorp** [comment]
Voilà un exemple de texte qui se trouvent sur le site où je récupère le résumé du film: [https://pastebin.com/wQeDvGZt]

> Perso, ca fait 10 ans que je n'utilise plus d'accents.

Quand j'écris un code où que j'affiche des infos sur l'écran j'utilise l'anglais également, mais là pour le coup je récupère du texte en français, du coup pas trop le choix. 

Le fait de faire des replace ne m'enchante pas vraiment, il y a forcément un moyen d'encode ou décoder ça proprement.

Actuellement voilà comment je fait :
`    li.setInfo('video', {'title': stream['name'], 
    'genre': stream['genre'], 
    'mediatype': "video", 
    'plot' : stream['description'].encode('utf-8')})`

**Comment by TmpName** [comment]
Nope, pas besoin de replace, la commande que je te donne fait tout d'un coup
`label = unicodedata.normalize('NFKD', label).encode('ASCII', 'ignore')`
C'est une commande joker
Sinon comme infos ca va pas suffir ^^, la page pastebin par exmple est en htf-8
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
Donc pour avoir le code en unicode propre
html2_unicode= html.decode('utf-8') devrait marcher

Mais normalement l'encodage en utf-8 est justement le standard, tu devrais pas avoir de probleme avec ce type de page, verifi en quoi "fonctionne" le reste de ton code.
Tu n'as pas oublie le 
`#-*- coding: utf-8 -*-`
En debut de fichier ?

Ou alors c'est completement a la fin, ou l'affichage doit etre en utf8 et non pas unicode ?

Il faudrait le message d'erreur, ou l'affichage que tu voudrais et celui que tu as a la place.

**Comment by nekcorp** [comment]
@TmpName Merci pour ta réponse, voilà ce que j'ai lorsque je ne met aucun encodage :
`li.setInfo('video', {'title': stream['name'], 'genre': stream['genre'], 'mediatype': "video", 'plot' : stream['description']})`

https://ibb.co/mvecB7

Lorsque je met decode('utf-8') j'ai le même résultat : 

`li.setInfo('video', {'title': stream['name'], 'genre': stream['genre'], 'mediatype': "video", 'plot' : stream['description'].decode('utf-8'})`

J'ai ce message d'erreur : 

> 13:21:30.594 T:3088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 46-50: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.test_video\addon.py", line 202, in <module>
                                                show_streams(TAG)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.test_video\addon.py", line 45, in show_streams
                                                'plot' : stream['description'].decode('utf-8')})
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeEncodeError: 'ascii' codec can't encode 

Le caractère en question c'est le premier apostrophe présent dans le texte : https://pastebin.com/wQeDvGZt

**Comment by nekcorp** [comment]
@TmpName Merci pour tes réponses, mais ça ne fonctionne toujours pas.
avec unicode(stream['description'], 'utf-8') j'ai ce message d'erreur : 

> 01:04:06.601 T:3092   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: decoding Unicode is not supported
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.test\addon.py", line 214, in <module>
                                                show_streams(TAG)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.test\addon.py", line 43, in show_streams
                                                'plot' : unicode(stream['description'],'utf-8')})
                                            TypeError: decoding Unicode is not supported
                                            -->End of Python script error report<--

u.encode('utf-8') me donne le même résultat que la capture précédente que j'ai mise : https://ibb.co/mvecB7

Du coup je sèche :-(

**Comment by nekcorp** [comment]
Je met ma solution car j'ai enfin trouvé :-)

Alors le problème venait du mon xml, celui dans lequel j'ai les infos sur mes vidéos. L'encodage était en cp1252 et je l'ai changé en utf-8.

Dans mon addon je n'ai absolument rien fait j'ai laissé tout par défaut sans spécifier aucun encodage ou décodage.
`li.setInfo('video', {'title': stream['name'], 'genre': stream['genre'], 'mediatype': "video", 'plot' : stream['description']})`

et voilà le résultat : [https://ibb.co/n1rwR7](url)

Voilà si à l'avenir certains en trouvent l'utilité au moins tout est tracé ;-)

Merci à vous tous et bonne continuation dans vos projets ;-)

**Comment by TmpName** [comment]
Pour moi c'est bien encode('utf-8') qu'il te faut appeller avant de l'afficher (pour avoir une chaine un utf-8) si ca deconne c'est quand tu l'as converti en unicode. Une page web recupereree ne peut pas etre en unicode (les entree/sortie ne sont jamais unicode).
La variable description est en unicode mais le texte ne peut pas l'etre, donc a mon avis c'est a cet endroit que ca deconne, un mauvais choix d'encodage pour passer la chaine en unicode.

**Comment by LordVenom** [comment]
Par défaut dans python 2.7 (celui utilser pour Kodi 17) l'encoding est ASCII, il est donc nécessaire d'indiquer l'encodage UTF8 à chaque fois.
#-*- coding: utf-8 -*-
