### ISSUE TITLE
Problème affichage

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#2051]
Bonjour j'ai juste un petit souci d affichage des films.
D'habitude j'affiche les vidéos en LISTE pour une vue simple
Mais depuis la version 0.6.1 je crois c'est bloqué en affichage MUR
Comment débloqué cette affichage MUR car quand je choisi LISTE ça ne reste pas et revient en mode MUR

Merci

**Comment by Arias800** [comment]
Tout le temps ou juste pour la recherche visuel ?

**Comment by AizenKnower** [comment]
Tout le temps sur chaque rubrique 
Si ya une solution ça  m'aiderai car je veux pas supprimer et reinstaller
Pourtant je fais les mises a jour mais ça reste bloqué qur affichage en MUR
Dommage qu'il y a pas de fonction sauvegarde/restauration

**Comment by Arias800** [comment]
Dans les paramètres de l'addon il y a un rubrique vue personnalisé peut être que ça vient de la mais il faut voir avec quelqu'un qui connais mieux cette option que moi @LordVenom

**Comment by AizenKnower** [comment]
C'est bon tu a resolu mon problème car effectivement il a été activé et en l'inactivant tout est revenu a la normal en affichage liste 

Alors merci beaucoup pour ton aide

Bon weekend
