### ISSUE TITLE
Chaine tv

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#2052]
Bonjour je ne sais pas où le mettrr alors je crée un nouveau sujet 
Vstream met des sites de streaming de film serie reportage etc...
Mais qu'en est il des chaines tv en streaming ? Car il y a 3 sources intéressantes surtout le 

http_://www.firstonetv.net/Live/France
http_//www.regarddirect.fr
http_//racacaxtv.ga/light.php

Est il possible de les ajouter ?

**Comment by Arias800** [comment]
Les chaine tv on a arrêter car trop dangereux (a la limite les chaine de la tnt oui) ensuite je suis totalement contre le faite d'utiliser ce que fait racacax car il faut un très bon taf tout comme first _ne tv

**Comment by AizenKnower** [comment]
Ok merci mais je pensais plus au site firstone tv
Et je vois pas en quoi c'est plus dangereux que le streaming de série ou film
Au pire site internet fermera comme zonetelechargement sinon juste filtrer les chaînes TNT et exclure les autres

Pour racacax beaucoup de chaines ont disparu c'est devenu inutile
Quant a respecter leur travail je trouce ça désolé de le dire mais un peu hypocrite car respectes tu le travails des dizaines de sites internet qui streament films series spectacle documentaires mangas etc...?

Tout ces sites sont illegales mais tu prend quand meme le risque de toutes les réunir en un seul addon donc je pense pas que un site se plus changera le risque

Le pire vous demandez d autre proposition de site de streaming qui sont aux yeux de l'état ILLÉGALE

Désolé mais le risque et le non respect est deja la base de votre travail car sans cela vstream aura jamais vu le jour sans les sites de streaming illegales et le travail de ceux qui ont fait ces sites

**Comment by Arias800** [comment]
Alors les site de streaming sont illégal mais nous non 

L'IPTV étant un domaine récent les fermeture sont beaucoup plus fréquentes car les états tente de tuer le "bébé dans l'œuf" 

Ensuite racacax pour avoir pu lui parler c'est quelqu'un qui a tout mon respect car il fait ça comme une simple passion en plus de ces cours donc il faut pas le comparés aux site de streaming qui eux pense qu'à l'argent (il suffit de voir le nombre de clone des site qui ferme s'en est limite ridicule) et racacax à décider de réduire le nombre de chaîne car il a compris que c'était trop dangereux pour lui

En ce qui me concerne je me bats pour le streaming légale j'ai même ouvert une issue la dessus dans ce github 

Voilà j'espère avoir été assez claire dans mes propos en espérant que tu comprenne mieux mon point de vue

**Comment by AizenKnower** [comment]
Je dis pas que vous etes dans l'illégalité mais je comprend pas pourquoi vous dite que streamer des chaines tv c'est plus risqué que streamer des series et film

En plus dans les 2 cas c'est pas vous qui streamer vous ne faite que heberger le  site qui lui meme heberge le lien de stockage vers une video

C'est pareil pour les sites de streaming de film serie musique etc
Mais la cela ne doit pas etre un souci car dans tout les cas vous ne faite que heberger un site qui lui heberge de l iptv çà na pas plus de risque que ces dizaines de sites que vous heberger pour streamer film serie etc...

Je critique pas c'est juste faut etre sois 100pr 100 legal soit 100pr illegale. 
Pour moi dire que stream la tv c'est plus illegale ou plus risqué que stream des films serie etc.. c'est complètement illogique 

Mais je répète cela ne doit pas vous inquiétez le risque car ce n'est pas vstream qui heberge le film la serie la musique la chaine tv. 

Vstream n'est qu'un annuaire qui recense les sites internet qui eux meme recensent des liens de stockage donc déjà les États ont du mal a fermé ces sites qui n heberge rien; ils vont pas perdre le temps avec un addon qui recense les sites dans une sorte d annuaire

Vous etes juste un google spécialisé dans les sites de streaming et ça na rien d illegal ni de risqué 

Je pense qu'on a pas ma meme vision des choses mais comme tu dis l'état cherche pas a couper le bébé dans l'oeuf mais il veut tuer la poule ou la steriliser lol pour eviter des bb.
Donc pour l'état illégalité c'est de mettre au monde des poussins sans leur accord du coup il cherche a les faire avorter

Vstream est a des annees lumières de ce risque car il ne renferme aucune oeuvre et meme pas le contenu d un site de stockage ni meme le contenu d un site de streaming soit disant illegale car si je comprend bien c'est just un script qui importe la liste des videos

Bref désolé pour ce long msg et pour mol point de vue sur la question qui  est different du votre mais je vois pas le risque pour vstream sinon google aussi aurai du souci a se faire et tout autre moteurs de recherche car vstream est juste un moteurde recherche

**Comment by AizenKnower** [comment]
Je pense pas que shani et phoenix ont fermé a cause de l iptv car y a des sites bien plus evident compatible toute plateforme qui stream la tv et ils sont ouvert depuis longtemps.

Je parle des sites qui sont comme zone de téléchargement et qui recense plein de liste iptv par pays donc si vraiment c'est  l iptv la cause des fermetures ils auraient été ferme mais c'est pas le cas

Si tu lis les causes de fermeture de ces nombreux repository c'est parce quils ont des contenus sous copyright et non pas a cause de l iptv en gros c'est une sorte d Hadopi international non officiel qui leur a fait peur).

Bref je persiste en disant que ce n'est pas l iptv le souci (qui soit dis en passant y a des abonnement iptv qui ne sont pas pout autant fermé ) mais l hebergement de contenus sous copyright et jusqu'à present vstream n heberge pas de contenus mais c'est  just un moteur de recherche donc y a rien d illegale a recherche un site de streaming de film serie ou meme de chaine tv

Bref chacun sa vision des choses mais pour moi y a aucun risque si parmi les sources y a des sources de streaming de chaines tv ( je parle de source pas de fichier iptv ou m3u stocké quelque part dans vstream ou dans le repo de vstream (je crois que là oui c'est pas légal et a causé ma fermeture d"addon)

**Comment by TmpName** [comment]
On a deja mit des chaines de TV sur Vstream. Le boulot est enorme pour maintenir ca en place,
donc oui, pour l'avoir fait, je respecte plus le boulot de racacax que celui de mecs qui se font de la tune en plombant de pub des sites hebergeant des liens qui sont eux meme souvent reprit sur d'autres sites.
Je ne sais pas ce que propose actuellement racacax mais a l'epoque c'etait un fichier m3u a mettre direct dans kodi, sans aucunes pubs. Rien a voir avec firstonetv.net, eux par contre ca me derange pas de pourrir leur site.

Et non, ce n'est illegal, la preuve ils essayent de faire fermer captvtv depuis une eternite et ils sont encore la.

Les addons americain se sont fait fermer car ils faisaient plus que mettre des liens a dispo, il les creaient.
Et surtout, il y avait de l'argent dans l'histoire. L'histoire brassait pas mal d'argent
htt ps://torrentfreak.com/images/0b176c04-5f41-4375-9d73-ffdaf1a1af8a.pdf

France 2 est sur Vstream car "legal" et serveur officiel stable, mais n'espere pas y voir canal. Le boulot est enorme pour juste 4/5 chaines de plus sachant que les autres ne marcheront que 1 jours sur 2 pendant 1 semaine max. Moi perso meme si j'aime les defis, je n'ai pas assez de temps pour m'y consacrer, je prefere encore trouver la parade pour Recpatcha.

Sinon pour le cote legal @Arias800 je me tate pour netflix, le jours ou le streaming devient verbalisable en france je pense que je vais sauter le pas.

**Comment by Arias800** [comment]
En ce qui concerne les addon américain je n’était pas au courant du coup merci @TmpName 
En ce qui concerne racacax il a arrêter les playlist kodi il y a sont site ou son application pour regarder les chaine qu'il propose
Le problème de netflix c'est que je n'ai pas encore de source de revenu donc compliquer de prendre un abonnement ^^

**Comment by TmpName** [comment]
C'est le prix d'une place de cine, et meme moins 8 euros le mois. Compare aux autres offres c'est vraiement interessant.

**Comment by Arias800** [comment]
Je n'ai pas dit le contraire ^^

**Comment by AizenKnower** [comment]
J'ai liké +1 pour vous dire que je suis ok avec vous et justement c'est ce que je disais les addon US heberger des fichiers sous copyright et les créer et comme tu dis ça brasse de l'argent mais si il n'y a pas de fichier m3u ni de liens de stockage y a rien  d'illégal comme dit TmpName car si c'est pas fermé c'est qu'ils n'arrivent pas a montrer l'illégalité de streamer la tv

Maintenant il est evident que cela demande du travail  mais j'en conclu que c'est paq illégal et faisable mais cela demande du travail et je comprend qu'il y a des priorités et une vie à côté.

En tout cas j'espère qu'un jour y aura un de ces sites de streaming tv ce qui rendra Vstream vraiment complet.

Merci

**Comment by vic1997** [comment]
@TmpName Le streaming ne deviendra jamais verbalisable. Ils sanctionnent juste le P2P car c'est simple d'obtenir l'adresse IP. Là c'est impossible à moins de ne pas respecter la loi, ils ne peuvent donc pas le faire (vu que c'est un peut leur but de faire respecter la loi).
Quant à Netflix, ce n'est absolument pas complet.

**Comment by Arias800** [comment]
Le problème de netflix c'est qu'il ont du mal a compléter les séries qui ne leurs appartienne pas par exemple pour gotham il ont que 2 saison sur 4 c'est pas de leur faute c'est sur mais bon ça c'est pas top :/

**Comment by TmpName** [comment]
Yep ^^. Va falloir trouver autre chose pr finir les series.
Histoire de sous, mais rapport prix/contenu je trouve vraiment ca honnette.

**Comment by Arias800** [comment]
Oui mais c’était une exemple parmi tant d'autre :p c'est le même problème qu'il y a chez les anime en autre 
Mais oui netflix niveau rapport qualité/prix est vraiment honnête ^^

**Comment by vic1997** [comment]
@TmpName Je regarde pas trop les séries, donc peut-être au niveau des séries c'est complet, mais au niveau des films absolument pas.

Sinon, non ce n'est pas faisable matériellement. Tout simplement parce qu'ils n'ont pas les moyens pour se mettre entre le client et le serveur. Ce n'est pas faisable et pleins de protocoles permettent justement de se protéger (https notamment).

**Comment by Arias800** [comment]
Ils ont déjà réfléchit a intercepter les données qui transite directement chez les FAI mais il sont bloquer par les lois pour le moments ^^

**Comment by vic1997** [comment]
@Arias800 Oui, c'est illégal, en plus les FAI ne les autoriseraient pas, et même, on peut facilement crypté les données par plusieurs moyen avant de passer par les FAI.
Sans parler des internet alternatif ne se basant pas sur le model OSI TCP/IP.

**Comment by TmpName** [comment]
Bien sur que si que c'est possible, meme de contourner un vpn, ou passer outre le reseau TOR, pour info, la securite absolue n'existe pas, c'est juste une question de rentabilite. Si tu etait le plus gros terroriste de la panete, tu pourrais utiliser tout les moyens techniques possibles, tu serais retrouve sans problemes. Mais bon pour chopper quelqu'un qui telecharge le dernier Marvel, ca va etre dur de justifier les autorisations ^^.

https://fr.wikipedia.org/wiki/Deep_packet_inspection
Ca a justement ete demande et refuse (pour le moment). Il essayent aussi de faire mettre telechargement avec pedophilie et terrorisme.

Techniquement il n'y a aucun probleme, c'est juste les lois sur la liberte qui frennent, mais qui se reduisent tout les jours.
