### ISSUE TITLE
sokro

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#2053]
hi ! sokro stream est hs j'ai commencé la modif mais reste un soucis aléatoire niveau hoster parfois on a le lien final parfois non (perso je pense au cookie..) et pour les series un lien php (a voir) le fichier est la [ici](https://github.com/johngf/ab/blob/master/sokrostream_biz.py) si personne y jette un oeuil je le finirai plus le temps aujourd'hui.

edit: ça a l'air d'etre pareil sur le site donc on va attendre c'est surement un bug

**Comment by LordVenom** [comment]
J'allais le dire ça bug chez eux aussi. XD

**Comment by TmpName** [comment]
J'ai fait quelques modifs
https://pastebin.com/vVGsmhBN

Les series deconnaient si on passait par le genre, et y avait pas les dernieres series.

La recherche est a refaire, le lien a change, mais je peut pas tester encore, site HS.

**Comment by razorex** [comment]
Salut j'ai regardé un peu ton fichier et je me suis permis qq modif parce que l'affichage des films ne fonctionnait pas mon fichier [ici](https://pastebin.com/WdHV13sF).

**Comment by johngf** [comment]
avec la version que j'ai mis plus haut les films s'affiche mais le problème est ailleurs niveau hoster. 
mais le site n'a plus l'air d'etre mis a jour je le désactive pour l'instant

**Comment by razorex** [comment]
Ok. j'avais intégré tes modifs au miennes le fichier [ici](https://pastebin.com/CMbxvKdb).
la recherche ne fonctionnait pas. Si jamais tu veux le mettre avant de le désactiver..

**Comment by johngf** [comment]
@TmpName la plupart des hoster avait de faux lien avec video_code dedans

**Comment by TmpName** [comment]
Ben c'est (etait ?) un gros site, assez bizarre qu'il ferme comme ca, j'attend un peu pour voir.

**Comment by johngf** [comment]
il est revenu a changé de nom. certain truc sont vide des series mais c'est le début je pense je l'ai mis a jours

**Comment by TmpName** [comment]
Ca fait plaisir ^^, c'est (etait) un de mes 2 sites preferes
