### ISSUE TITLE
Dialoginfo

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2054]
![image](https://user-images.githubusercontent.com/4380112/39660932-953a16fa-5049-11e8-847f-0616e3c897de.png)

![image](https://user-images.githubusercontent.com/4380112/39660935-a8f10e56-5049-11e8-8a2c-558b30e5064b.png)

![image](https://user-images.githubusercontent.com/4380112/39660940-bae45f3c-5049-11e8-9cce-da3be8ad4090.png)

**Comment by TmpName** [comment]
C'est ou ca ?

**Comment by Arias800** [comment]
C'est le menu pour avoir plus d'info sur ce que l'on veut regarder (Information dans le menu contextuel)
