### ISSUE TITLE
La fonction Recherche de Zonetéléchargement KO

### ISSUE THREAD

**Issue by willaax** [Kodi-vStream/venom-xbmc-addons#2058]
Bonjour, j'ai fais la mise à jour hier depuis le repo vstream 0.6.1 sans problème, j'ai tenté une recherche dans la source Zonetelechargement mais elle échoue, peut-être un changement sur leur site

Est-ce que ça fonctionne chez vous?

Je suis sur une box android (Krypton)

Zonetéléchargement est l'une de meilleure sources surtout lorsque l'on possède un compte premium uptobox comme beaucoup d'entres nous. 

Ce serait bien de rajouter aussi extreme-down.im (Extreme-Download V3.5) - Ils ont pleins de liens uptobox

**Comment by willaax** [comment]
Ok super !
merci pour ta réponse Arias
Merci encore pour tout le boulot sur vstream

**Comment by kipopo** [comment]
Juste pour info,

Lorsque vous faites une recherche de série, avez-vous toujours un résultat avec ZT ?

Car parfois je ne trouve pas le titre mais je retrouve dans les derniers ajouts ... ( et pourtant écrit de la même manière)

Merci :-)

**Comment by willaax** [comment]
Oui je constate le même problème, lorsque je test la recherche je cherche
une série ou un film. En général je tape un film simple comme Dumbo par
exemple, normalement sur zonetel il y a 3 résultats. Si ça me met
indisponible c'est que la recherche est plantée (modification du site
zonetel par exemple ici c'est encore le cas).
Essaie avec un film, si les recherches de films sont ko, les séries aussi

**Comment by Arias800** [comment]
Le fichier a été mis a jour sur la beta donc normalement tout refonctionne

**Comment by willaax** [comment]
![image](https://user-images.githubusercontent.com/39027819/39749432-ee8a5b28-52b2-11e8-8313-713db4fea99d.png)

Bonjour, je viens de fair ela mise à jour depuis le repo sur ma android tv box, la fontion recherche ne fonctionne pas.

@Arias800 quand tu parles de maj effectuée sur la beta, comment proceder sur une box android tv ? moi par défaut il me propose de faire la maj depuis le repo 0.6.1

**Comment by Arias800** [comment]
Soit tu attends 2-3 jour que la maj des site apparaisse (la méthode la plus simple et la plus sur) ou alors tu installe la beta https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream (mais il y a des risque de bug car c'est la version beta donc potentiellement pas stable)

**Comment by willaax** [comment]
OK dans ce cas, je préfère attendre la maj des sites (moins complexe pour
moi sur ma tv) merci Arias🙏

**Comment by Popoffake** [comment]
Bonjour,
malgré la mise à jour, la recherche ne fonctionne toujours pas sur ZT.
Elle fonctionne vraiment sur la bêta ?

**Comment by Arias800** [comment]
Ils ont encore changer l'url j'ai fait la modif faut attendre la mise a jour des 3 jour ....

**Comment by Popoffake** [comment]
Arf. S'ils changent tous les deux jours, on est pas sorti d'affaire.^^

**Comment by Arias800** [comment]
Il vont se calmer au bout d'un moment t'inquiète pas pour ça ^^

**Comment by TmpName** [comment]
Est que tu as fait une re-instal (Vstream etait deja installe) si oui c'est normal, tu as tout perdu, il te faut now attendre 3 jours pour avoir ta version a jours.

**Comment by lebigboss** [comment]
Apparemment c'est le site entier qui vient de changer.
On a plus accès à rien. Même les marques page ZT ne fonctionnent pas.

Et je sais pas si ça vous fait ça à vous aussi mais en allant sur le site tout fonctionne, sauf quand je me connecte à un compte que je viens de créer il n'y a plus aucun lien.

**Comment by isandard** [comment]
En fait le site a bougé sur : ww3.zone-telechargement1.com

Mais ce qui est moins rigolo c'est que l'ancien nom de domaine redirige sur tirexo, donc les catégories ne fonctionnent plus aussi.

**Comment by Arias800** [comment]
La modification à ete faite sur la bêta

**Comment by vstreamkodi** [comment]
Pour ceux qu'ils ne peuvent pas attendre la mise à jour tous les 3 jours alors il suffit de modifier la ligne URL_MAIN= "ww2.zone-telechargement1.com" par URL_MAIN= "ww3.zone-telechargement1.com" (nouvelle adresse URL de zone-telechargement1) dans le fichier du zip "plugin.video.vstream-0.6.1.zip/plugin.video.vstream/resources/sites/zone_telechargement_ws.py" et de faire l'installation depuis un zip.

**Comment by lebigboss** [comment]
Il y'a seulement la section Série VF qui ne fonctionne pas sur la bêta

**Comment by KiliK150** [comment]
Depuis ce changement d'adresse là , le bug d'affichage #2012 n'est plus présent 👍🏻✌🏻️

**Comment by AngelineL** [comment]
Bonjour suis-je la seule à avoir fichier introuvable via uptobox? ( un peu hors sujet désolée )

**Comment by Wolsey20** [comment]
Bonjour, tu n'es pas le seul ,Uptobox HS que ce soit sur zone téléchargement ou ddl island (Lien introuvable).

**Comment by vstreamkodi** [comment]
@KiliK150 moi j'ai toujours le bug de l'affichage de la saison depuis la version 0.6.0 il me semble. @AngelineL et @Wolsey20 les liens uptobox fonctionnent. Vous pouvez essayer d'installer ce zip https://uptobox.com/tg6dhofc2slj

**Comment by AngelineL** [comment]
J'ai installé le zip. Toujours le même soucis.

**Comment by vstreamkodi** [comment]
Il faut bien vérifier que tes options de configuration dans ton comtpe uptobox.com sont bien désactiver.

**Comment by KiliK150** [comment]
Chez moi le problème d'uptobox HS venait des identifiants qui ont disparu dans les paramètres Vstream

**Comment by KiliK150** [comment]
@vstreamkodi oui ce bug d'affichage est toujours présent sur les anciens marque-pages. Mais sur les nouveaux ( depuis hier pour ma part ) , l'affichage fonctionne très bien.

**Comment by Wolsey20** [comment]
Toujours le même bug avec uptobox après avoir installer le fichier zip https://uptobox.com/tg6dhofc2slj 
que ce soit en version premium ou free

**Comment by AngelineL** [comment]
Oui tout est bien désactivé dans configuration sur mon compte uptobox.

**Comment by Lolobeboy** [comment]
slt, est-ce que chez vous zone-telechargement fonctionne ? J'ai déjà changé le main URL et j'ai même installé la version bêta mais rien n'y fait .

**Comment by Wolsey20** [comment]
J'ai trouvé, il faut modifier le fichier uptobox.py et uptostream.py  il faut rajouter le S a HTTP
(https://uptobox.com) ligne 48 (https://uptostream.com) ligne 78 avec notepad++

**Comment by AngelineL** [comment]
Merci @wolsey20 . Ça marche en rajoutant le s

**Comment by TmpName** [comment]
Merci pour l'info ^^.
Y en a qui risquent d'avoir des prbs, mais je met ta modif sur la beta, on a bien voir ce que ca donne.

**Comment by willaax** [comment]
Je viens de tester de nouveau la fonction recherche est toujours KO pour ZoneTel. 

Je précise je viens de faire la maj de l'extention et la maj des sites à l'instant sur ma box android 

ça marche pour vous?

**Comment by Arias800** [comment]
Pas de problème chez moi ^^

**Comment by vstreamkodi** [comment]
Ils ont encore bougé l url sur 1ww.zone-telechargement1.com

**Comment by TmpName** [comment]
Ok, bon ben faut faire comme pr kepliz, on va pas chnager l url tout les 4 jours.

**Comment by Fraisdos** [comment]
Mettre l'url dans une variable sous option ?

**Comment by TmpName** [comment]
A terminer
https://pastebin.com/Tp3dRuh3

Ca marche pour les recherches uniquement.
Chnagez URL_MAIN par une vielle url, ca marchera quand meme.

Ne pas tenir compte de la premiere fonction, j'avais prevu un truc pour tout le code mais j'ai compris apres que ca deconnais que pour les recherche et le lien final, donc pas besoin d'artillerie lourde.

**Comment by Arias800** [comment]
De tout façon si dans URL_MAIN tu mets http://zon_-telechargement1.com/ normalement ça marche pour un moment car c'est la première modification qu'il sont fait après l'url en .ws

**Comment by TmpName** [comment]
Yep, mais c'etait juste pour tester, faire avec la bne url, et avec une mauvaise pour voir si le code pouvait s'adapter.
Avec ce systeme pas besoin de changer URL_MAIN tout les 4 jours.
