### ISSUE TITLE
zone téléchargement  a changé sont site en tirexo.com

### ISSUE THREAD

**Issue by ddav33** [Kodi-vStream/venom-xbmc-addons#2064]
Les sources ne fonctionne plus sur vstream avec la sources zone téléchargement.ws depuis sont changement en tirexo.com qui semble avoir pris la place de zt avec une nouvelle interface car depuis un navigateur on tombe sur ce site avec l'adresse de zt ?!

**Comment by johngf** [comment]
non il n'ont pas changé

**Comment by ddav33** [comment]
OK mais sur vstream la source marche plus ils ont changé en
https://ww3.zone-telechargement1.com/ faudrait la modifié dans vstream si
c'est la bonne car moi je sais pas faire ni si c'est la bonne adresse car
je sais pas non plus qui copie qui sur internet , mon skyn fonctionne
qu'avec vtream et et d'où mon desaroua 😟👉📺😊

**Comment by johngf** [comment]
si tu aurais lu l'issue juste en dessous au lieu d'en ouvrir une nouvelle tu te serait rendu compte que ça a déjà été fait sur la beta [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2058)

**Comment by ddav33** [comment]
Pardon autant pour moi j'avais lu mais jusqu'au bout vue que ça parler du mode recherche au début de cet issue 👌👀✔
