### ISSUE TITLE
streamango.com

### ISSUE THREAD

**Issue by ebs111** [Kodi-vStream/venom-xbmc-addons#2068]
salut,
il y a un problème avec streamango.com, ils ont changé quelque chose.
Est-ce que tu peux le réparer s'il te plaît?
Merci.
excellent addon en passant.

**Comment by johngf** [comment]
je viens de testé il fonctionne. sur quel site tu as vu le soucis

**Comment by ebs111** [comment]
désolé j'ai eu tort j'ai vérifié à nouveau et son fonctionnement,
Merci pour tout.
