### ISSUE TITLE
Problème fonction de recherche général 

### ISSUE THREAD

**Issue by blvssou** [Kodi-vStream/venom-xbmc-addons#2074]
Bonjour j'ai un petit problème depuis hier avec la fonction de recherche général de l'extension, en effet lorsque quand je lance une recherche l'extension scan bien tout les sites mais ne me sort aucun résultat mais bizarrement d’habitude quand une recherche ne donne rien dans les résultat j'ai quand même l'index des sites scanné mais sans résultat hors là je n'ai même pas cet index.
D'où ma question de savoir si j'étais le seul dans ce cas.

**Comment by johngf** [comment]
le problème a été corrigé en attendant désactive >>cineiz depuis les parametres de vstream
sources>activer/désactiver sources> cineiz puis ok

**Comment by blvssou** [comment]
Je viens du coup d'essayer néanmoins quand je clique sur "activer/désactiver les sources" il m'affiche "Erreur d'extension consulter le journal pour plus d'information" 
Petite info complémentaire si ça aide je suis sur une Xiaomi box tv

**Comment by johngf** [comment]
faudra attendre la mise a jour dans ce cas il a toujours des problèmes avec ce genre de "box" android 
comparé a windows ou linux .

**Comment by blvssou** [comment]
j'ai la dernière version de kodi la v17.6

**Comment by blacksnacke** [comment]
Bjr,
Je ne pense pas que le Probleme soit lié a Android. J ai aussi une Box android, mais aussi j utilise Kodi sur le PC. Le Probleme apparait sur les deux platte forme. Dans les Option (Choissir Sources) aucune source ne s affichent, donc il y a pas moyen d'activer ou de desactiver une source.
J ai fait l actualisation manuel ce matin, et depuis lors le Probleme arrive.
Veuillez nous aider svp.

**Comment by johngf** [comment]
Alors j'ai testé sur pc Windows et linux ça fonctionne avec kodi17.1 et kodi 16.1
Ça viens peut être de kodi 17.6 je testerai après

**Comment by johngf** [comment]
testé avec kodi 17.6 ça fonctionne

**Comment by LordVenom** [comment]
Pour "activer/désactiver" les sources le bug est résolut depuis 23jours CF (https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2036)  mais ne seras dispo qu'a la prochaine mise a jour mensuel pour ceux qui ont le bug merci de tester le fichier et de nous faire vos retours.

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/runscript.py

**Comment by johngf** [comment]
Je ne sais plus quel était le soucis mais si c'est syspath 
J'ai remarqué  il y a lgt que le décode utf8 ne fonctionne pas si il y a un - dans le chemin.

**Comment by blvssou** [comment]
Je viens de tester sur ma xiaomi box tv et la recherche général est de retour à la normal, j'avoue que le couplage Vstream + ZT + un débrideur c'est juste le top. 
Merci du taff.

**Comment by blacksnacke** [comment]
le Probleme persiste chez moi. Lorsque j effectue une recherche, le Resultat est completement vide, malgres que pendant la recherche le checking des sources defilent.
Dans la Configurration, dans le registre Source, Aucune source n est afficeher.
Je suis sous Android et Windows10 avec la version 17.6

**Comment by blacksnacke** [comment]
![image](https://user-images.githubusercontent.com/28162815/40197628-54cb75ee-5a14-11e8-9624-757fceda531b.png)

**Comment by blacksnacke** [comment]
Exemple de recherche
![image](https://user-images.githubusercontent.com/28162815/40197703-817878b2-5a14-11e8-835d-c8fbc65bb25d.png)

Resultat de Recherche (rien n affiche)
![image](https://user-images.githubusercontent.com/28162815/40197754-a69b8648-5a14-11e8-9670-b2214b86b251.png)

**Comment by blvssou** [comment]
Si jamais ça peut aider perso le problème à été résolu sur ma box android quand dans kodi j'ai été dans: extension > Vstream (rester cliqué dessus) > informations > Mettre à jour > cliquer sur la Version 0.6.1 (perso qui était déjà celle installer enfin bref). Perso après cette manip tout est revenu à la normal.
Petite info complémentaire je viens de tester sur mon smartphone android et effectivement j'ai fait la maj (en verte) dans Vstream et cela à fait planter les résultats de recherche puis en faisant la démarche que je vous est cité ci-dessus tout est revenu nickel.

**Comment by Tokyo99** [comment]
Si vous voulez règler votre problème de sources apparu après la derniere mise a jour , faites comme #blvssou l’explique 👍
Merci

**Comment by blacksnacke** [comment]
Bjr,

Merci a "blvssou". Ta Methode fonctionne. J ai tester sur Windows 10 et Android Box aussi. Kodi 17.6
J espere qu elle sera durable.
A+

**Comment by LordVenom** [comment]
Fausses bonne idée puisque vous remettais tous vos fichier sites/hots dans leur version d'origine.

Si la recherche plante c'est qu'un site plante il suffis de trouver le coupable et de le désactiver dans les préférence si "activer/désactiver" les sources ne fonctionne pas chez vous voir mon message si dessus.

Si ma méthode au dessus ne fonctionne pas merci de nous fournir un log qu'on puisse avancés.

**Comment by TmpName** [comment]
Ben si ya pas de retours, c'est que y a pas de bugs ^^.

**Comment by Turk182es** [comment]
Moi en desactivant Cineiz ça passe nickel

**Comment by LordVenom** [comment]
Y en a pas chez moi donc pas de soucis. XD

**Comment by LordVenom** [comment]
N'oublier pas que quand vous aurais la mise a jour site/host avec cineiz dedans, vous pourrez le réactiver sans soucis "normalement".

**Comment by Arias800** [comment]
j'ai tester avec la toute dernière version j'avais le même problème @LordVenom

**Comment by LordVenom** [comment]
Un message d'erreur ?

**Comment by Arias800** [comment]
Que ça qui sort de l'ordinaire 19:28:10.656 T:7012 WARNING: `Attempt to use invalid handle 15
19:28:10.673 T:7012 WARNING: Previous line repeats 4 times.`

**Comment by Arias800** [comment]
C'est bon je croit avoir trouver

**Comment by Arias800** [comment]
C'est bon trouver je mets a jour

**Comment by Arias800** [comment]
Enfaite c'est la modif de @johngf qui fait planter la recherche

**Comment by Arias800** [comment]
En faite j'avais pas la bonne version merci Kodi x)

**Comment by blacksnacke** [comment]
Salut,

mais cmt activer/desactiver les Source si rien n y apparait. Voila cmt ca se presente chez moi. Je ne peux donc pas choisir une source.
Version 0.61 sur Window et sur Android TV box. 
Avez vous la meme image chez vous? Qui pourra m aider
![image](https://user-images.githubusercontent.com/28162815/40464685-e654579e-5f1c-11e8-9291-2e8987b1ae77.png)

**Comment by Arias800** [comment]
Normalement quand tu appuye sur activer/désactiver les source tu à un menu qui apparaît où tu choisi quel source tu supprimes

**Comment by blacksnacke** [comment]
Merci Arias,
Mais moi je recois tjr un message d erreur sur windows et sur android. Bizarre

Log.file
07:13:28.836 T:14164 WARNING: CPythonInvoker(43): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
07:13:30.008 T:14164  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
07:13:30.059 T:14164   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named handler.pluginHandler
                                            Traceback (most recent call last):
                                              File "C:\Users\Name.....\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\runscript.py", line 305, in <module>
                                                cClear()
                                              File "C:\Users\Name....\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\runscript.py", line 30, in __init__
                                                self.main(sys.argv[1])
                                              File "C:\Users\Name....\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\runscript.py", line 161, in main
                                                from resources.lib.handler.pluginHandler import cPluginHandler
                                            ImportError: No module named handler.pluginHandler
                                            -->End of Python script error report<--

**Comment by Arias800** [comment]
Faut attendre @LordVenom pour ça

**Comment by LordVenom** [comment]
un copier coller d'un message juste au dessus :

> 
> Pour "activer/désactiver" les sources le bug est résolut depuis 23jours CF (#2036) mais ne seras dispo qu'a la prochaine mise a jour mensuel pour ceux qui ont le bug merci de tester le fichier et de nous faire vos retours.
> 
> https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/runscript.py

**Comment by blacksnacke** [comment]
Merci Lordvenom, mais je ne comprend tjr pas ce qu il reste a faire pour resoudre ce BUG des source. J ai lu completement le #2036 Mais c etait un dialogue entre 2 personne qui s y connaissent profondement, moi j ai pas saisi la solution. 
Que dois faire pour mon PC ou ma box pour pouvoir activer ou desactiver mes sources.
Merci de ton aide

**Comment by TmpName** [comment]
Essayes en remplacant ton fichier runscript par celui que te passe @LordVenom.
Editeur de texte puis copier/coller.

**Comment by dark3hack** [comment]
j'ai exactement le même soucis depuis quelque jour sur ma box xiaomi plus aucun film apparaît je comprend pas jai toucher à rien
