### ISSUE TITLE
uptobox ne fonctionne quand direct 

### ISSUE THREAD

**Issue by ddav33** [Kodi-vStream/venom-xbmc-addons#2075]
Bonjour chez moi utopbox ne fonctionne qu en direct ,sur uptostream cela marque fichier introuvable sur tout les liens !

**Comment by johngf** [comment]
Ti as la dernière version  du fichier  ? Il a été mis à jour hier

**Comment by ddav33** [comment]
J'ai eu une mise a jour y a deux jours je crois

**Comment by Cikai91** [comment]
Bonjour 
Je confirme uptostream ne fonctionne plus. Message fichier introuvable. 
Idem avec la dernière mise à jour

**Comment by johngf** [comment]
chez moi ça fonctionne par uptostream

**Comment by Cikai91** [comment]
Je suis en premium moi par contre.
En direct pas de soucis. Mais uptostream...  Toujours fichier introuvable. 
Je vais essayer de revenir à la version précédente de vstream

**Comment by ddav33** [comment]
J'ai reçu une mise a jour hier soir et ça refonctionne merci beaucoup👌😊

**Comment by Cikai91** [comment]
Super ! Merci l'équipe ça refonctionne

**Comment by rinty35** [comment]
Bonjour tout le monde. Moi j'ai toujours le probleme avec Uptobox. Je passe le captcha et au moment d'ouvrir la source j'ai le message "Fichier introuvable". J'ai fait le test avec plusieurs recherches et toujours le même symptôme. J'ai essayé en me créant un compte (non premium), dans ce cas pas de captcha mais le même résultat en uptostream. Une idée ?

**Comment by johngf** [comment]
tu n'est pas a jour il faut attendre la maj ecrit en vert

**Comment by rinty35** [comment]
Comment faire pour forcer la MAJ ? Il ne me la propose pas ? Au besoin je peux éventuellement aller corriger le fichier concerné à la main.

**Comment by Arias800** [comment]
Voilà la modif à effectuer si tu veux la faire à la main https://github.com/Kodi-vStream/venom-xbmc-addons/commit/1b04b57beb3a892753ce5eb3f28c1766b1ece83e pour uptostream c'est la même chose mais dans le fichier uptostream

**Comment by rinty35** [comment]
Bonjour.
Merci beaucoup, je n'ai pas eu besoin de le faire j'ai récupéré la mise à jour hier après avoir posté mon message. C'est OK maintenant

**Comment by ddav33** [comment]
Bonjour je revient vers vous pour vous notifié que l'option d'ajout au compte uptobox ne fonctionne plus ..

**Comment by johngf** [comment]
Forcément ce n'est pas le même fichier donc il y a pas eu de modif faudra le mettre à jour

**Comment by johngf** [comment]
je suis dessus @ddav33

**Comment by johngf** [comment]
bon avec la prochaine version vous pourrez mettre sur votre compte les liens
1 fichier ,up loaded, up tobox ,up tostream, up lea (d'autre sont possible turbo bit etc.. mais ne sont pas pour l'instant pris en charge par vstream)
et vous pouvez faire autre chose pendant l'upload une popup s'affichera en haut si le transfert démarre sinon c'est que le liens est hs ou ...
