### ISSUE TITLE
Plus aucun film hd ?

### ISSUE THREAD

**Issue by romasterr** [Kodi-vStream/venom-xbmc-addons#2076]
Bonjour tout le monde !

Depuis quelques jours je n’ai plus aucun film HD, avant lorsque je recherchais un film, j’avais toujours un petit logo HD en vert, et la plus rien. 

J’ai fait le test avec 3 films, le hobbit, Thor et 50 nuances de grey. 

Je n’ai que de la qualité SD alors qu’avant je les avais bien en HD. 

Quelqu’un aurait une idée ? Car j’en viens à préférer le vieux téléchargement et balancer sur une clé usb...

Merci !

**Comment by romasterr** [comment]
Je viens à l’instant de faire un test avec le film Logan, c’est pareil, j’ai simplement deux films en HD, sur cinémegatoil, et quand je clique dessus, c’est marqué « aucune information »

C’est vraiment chiant :/

**Comment by Arias800** [comment]
Tu est en quel version de Kodi ? Si tu parle des petit logo HD c'est Kodi qui les ajoute et il me semble que c'est très aléatoire au niveau du fonctionnement après il se peux que les liens soit mort sur le site donc là c'est pas de notre faute ^^

**Comment by LordVenom** [comment]
C'est que tu texte le logo tu peux trouver de l'HD sans le logo, enfaîte si dans le titre y a 1080 ou HD ou 720 ça met le logo rien a voir avec la vrais qualiter de sortie.

**Comment by romasterr** [comment]
J'arrive à avoir le Hobbit en HD dessus, et encore, en 720p, mais c'est tout, j'ai aucun autre film en HD.

**Comment by romasterr** [comment]
Je viens à l'instant de faire le test avec ton film, je n'ai qu'une source pour ce film qui est "planet streaming", et un seul 720p de fonctionnel sur les 4

**Comment by TmpName** [comment]
Ben tu as pas de bol.
Moi j'en ai teste 4 (sauf netu) et ils ont tous fonctionne.
J'ai refait un test et j'ai trouve les tuches (c'etait pr tester, je vais pas rgarder ca) en 1920*800 sur film illimite.

**Comment by LordVenom** [comment]
C'est pas un bug c'est du Streaming pour du pur HD 25Go le film tourne toi vers le téléchargement.

**Comment by romasterr** [comment]
Forcément je ne demande du pur HD, mais je trouve ça pénible d'avoir à chercher pendant 15 minutes, et au final regarder du SD, alors qu ça allait nickel :/
