### ISSUE TITLE
ZT mauvaise redirection en sélectionnant une autre saison

### ISSUE THREAD

**Issue by Fraisdos** [Kodi-vStream/venom-xbmc-addons#2077]
Bonjour,

Voici les étapes qui amènent au bug:
1) Selection d'une saison (par exemple S2 west world).
2) lorsque la liste obtenue propose différentes saisons, choix d'une autre (par exemple S1)
3) la liste obtenue reste sur la saison 2.

Des idées pour corriger ce problème ?

**Comment by Arias800** [comment]
Normalement c'est juste un bug d'affichage les épisode sont les bon

**Comment by lebigboss** [comment]
Oui c'est comme ça depuis toujours je crois. Quand tu clic sur une saison dans ZT ça t'affiche pas le bon chiffre de la saison mais en faite ça fonctionne.
Je fait pareil sur Bojack Horseman en allant sur saison 4 je clic sur saison 1 HD 720 et ça affiche saison 4 HD 720 mais c'est la saison 1 HD 720

**Comment by Arias800** [comment]
C'est en cours de reparation ^^
