### ISSUE TITLE
Echec de lecture d'un ou plusieurs fichiers.......fichier introuvable.

### ISSUE THREAD

**Issue by Stam06** [Kodi-vStream/venom-xbmc-addons#2078]
Bonjour,
Depuis quelques jours, impossible de lire ^presque quoi que ce soit. Soit c'est le message d'erreur "échec de lecture d'un ou plusieurs fichiers........" ou encore "erreur fichier introuvable".
On m'a proposé une mise à jour, chose que j'ai faîte. Mais, toujours rien. J'ai pu lire tout à l'heure un fichier sd sur Netu, mais en HD rien ne fonctionne (du moins, ce qui m'intéresse).
Merci de m'aider, svp, à régler ce problème. Je suis un novice, je ne m'y connais pas. J'utilise Kodi sur pc.
Merci de votre compréhension.

**Comment by Arias800** [comment]
Tu peux me donnez un exemple de quelque chose qui ne marche pas

**Comment by razorex** [comment]
Bonjour, quel site déjà???? donne un max de précision, du genre site / films ou série?? est tu aller sur le site d'origine pour voir si les liens était valide

**Comment by Stam06** [comment]
Westworld saison 2 épisode 4 à partir de la source zonetéléchargement.

**Comment by LordVenom** [comment]
Recherche global "westworld" - filmstreamvk  - saison 02 - episode 04 - Netu

**Comment by AizenKnower** [comment]
Si ça existe avec pas mal de source comme  series stream hd oi kaydo ou seriestreaming.cx la quantité est souvent hd ou fhd

Et je confirme les problemes de lien qui marche plus tout

Jai meme essayer une mise a jour manuel par github et la c'est pire ca fait planter kodi des quon lance un lien

**Comment by lebigboss** [comment]
ça vient du site, tous les liens sont dead
donc vérifiez les sites avant de posté
Sinon va sur DDL , la saison 2 y est en HD

**Comment by KiliK150** [comment]
Pour info aucuns liens de westworld n'est mort sur ZT. J'ai déjà testé hier en 1080 ou 720 VOSTFR , tout marche à la perfection .

**Comment by Stam06** [comment]
ça remarche les amis! Merci à vous tous!
Bon Dimanche!
