### ISSUE TITLE
Kaydo bug streaming

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#2081]
Bonjour 

Ces derniers temps kaydo hds.to fonctionne bien mais a chaque serie streamé des parties de videos disparait comme des sauts d'image 

Est ce que quelqu'un a ce meme souci car dure de visionner une serie quand des minutes sont zappé

**Comment by AizenKnower** [comment]
Aucune idée j'ai pas accès au site aujourd'hui.
Il faut se connecter mais je suis pas inscrit
Et y a pas d endroit où s enregistrer 
Mais la derniere fois que j'ai voulu çà demander de s abonner 
Donc je me suis pas inscrit du coup je sais pas si c'est pareil

**Comment by Arias800** [comment]
Il ne faut pas s’inscrire car il te demande d'appeler un numéro surtaxer pour l'inscription mais normalement ce n'est pas vstream qui en est la cause ^^

**Comment by AizenKnower** [comment]
Jusqu'ici je peut lire toute les vidéos sans bug meme en FullHD avec mon débit mais ya ke ce kaydo qui fait sauts de scène car je constate que des coupures de scene ou de conversation 

Je veux m'assurer que c'est bien les liens direct de kaydo qui cause le probleme et pas vstream ni kodi

**Comment by Arias800** [comment]
Oui mais ça doit être une problème temporaire chez eux donc faut attendre . Je sais pas chez moi il apparait pas souvent le pop-up d'inscription

**Comment by Arias800** [comment]
Va sur hds.to si tu tombe sur une page members only c'est cuit on peux rien faire

**Comment by AizenKnower** [comment]
Ok donc ca me rassure que ce n'est pas que chez 
je vais retester avec la maj Vstream d aujourd'hui avec update de Razorex dya quelque minute
Jusque là la source kaydo me trouve des series et les catégories sont bien rempli 
Reste a voir si y a des coupures de streaming ou si c'est réglé aujourd'hui

**Comment by razorex** [comment]
Ben c'est tout a fait ca @Arias800

**Comment by Arias800** [comment]
Bon bah c'est cuit pour toi le site te bloque @razorex

**Comment by AizenKnower** [comment]
@Arias800, je ne pense pas qu'il le bloque car moi aussi je tombe sur la page members et pourtant je n ai jamais utiliser leur site version web ni visionner leur streaming en ligne

On tombe sur la page members en 4G mais pas en wifi donc je pense pas que c'est un souci de blocage car j'ai activé mon wifi et la j'ai accès a hds.to

**Comment by LordVenom** [comment]
Un bloquage ip ou pays ou operateur un truc du genre donc avec 2 connection différente tu as une change, perso sous Free bloquer avec la fibre bloquer aussi.
