### ISSUE TITLE
Problème de recherche... Rien ne s'affiche 

### ISSUE THREAD

**Issue by Tracknard** [Kodi-vStream/venom-xbmc-addons#2082]
Bonjour,

Je dispose d'une boxe android. Sur celle-ci, j'ai installer la dernière version de kody ainsi que vstream qui est bien à jour. 
Je précise qu'il y à deux jours encore, tout fonctionnait parfaitement. 
Donc voici mon problème. Je vais dans Recherche, je tappe le nom du film et ne selectionne la recherrche "film".
On vois bien la barre de recherche travailler et trouver des films pendant son scan. Mais lorsque le scan est terminé.. Rien ne s'affiche. 
Je suis complètement perdu, avez vous une idée du problème ?

Merci d'avance, 

Cordialement, 

Tra k

**Comment by razorex** [comment]
Bonjour,
regarde les autres issues. C'est traité et résolu il te faut juste de la patience.

**Comment by Tracknard** [comment]
Super merci.
Désolé pour le dérangement, sujet clos. Ça fonctionne à nouveau en désactivé cineiz 😀
