### ISSUE TITLE
Liste iptv

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2083]
Les chaine payante sont de retour maintenant vstream scrape un site qui distribue des liste d'iptv a retrouver dans television/radio -> Liste site Iptv(Beta - Nécessite F4mTester)->Choisissez un site

**Comment by AizenKnower** [comment]
Ya un truc a régler car ça fait planter kodi 
Est ce que ces iptv s ouvre avec le player de kodi ou faut installer un lecteur ?
Je parle de lecteur car en choisi vlc comme lecteur pour vstream ca plante kodi donc jai remis xbmcplayer plugin
Mais les iptv ne souvre pas et plante kodi de la meme facon

**Comment by Arias800** [comment]
Ça s'ouvre avec le player par défaut de kodi vu que je me suis baser sur le code de base du fichier freebox

**Comment by AizenKnower** [comment]
Ca fait planter kodi
19mai ne souvre pas
18 et 17 et 16 s'ouvre  je choisi la chaine et kodi plante

**Comment by Arias800** [comment]
Alors le 19 s'ouvre pas je cherche pourquoi par contre chez moi le 18 marche essaye en supprimant la ligne 523 https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/freebox.py

**Comment by Arias800** [comment]
Voila une version qui normalement corrige le bug du 19 car elle propose les lien de secours par contre j'ai ajouter le support de f4mTester donc cette addon est nécessaire pour lancer les lien https://pastebin.com/hwWwgLbz

**Comment by Arias800** [comment]
D'ailleurs @AizenKnower si tu est d'accord je peux peut être ajouter ta liste de chaine

**Comment by AizenKnower** [comment]
@Arias800 oui bien sur s'il fonctionne toujours 
Sinon as tu resolu le probleme de plantage car moi ça plante
J'ai pas pu retirer la ligne 553

**Comment by Arias800** [comment]
Il te faut l'addon f4mTester sans c'est normal que ça ne marche pas tu peux le trouver la https://github.com/kodil/kodil/tree/master/repo/plugin.video.f4mTester sinon je sais pas d’où ça peut venir il me faudra les log ^^

**Comment by AizenKnower** [comment]
J'ai installé f4mtester mais çà plante kodi donc si tu veux les log dis moi comment faire

**Comment by Arias800** [comment]
Dans les option de vstream dans outil tu a Upload Kodi log voila ce qu'il faut faire : Upload automatiquement votre log sur Slexy vous pouvez par la suite simplement nous transmettre l'ID vous étant donner en popup. Votre log http://slexy.org/view/+ votre ID

**Comment by AizenKnower** [comment]
https://slexy.org/view/s2U4Gyvjwk voila

**Comment by Arias800** [comment]
Tu a reproduit le bug avant de passez les log car la j'ai rien dedans

**Comment by Arias800** [comment]
A tu les même paramètre la 
![capture](https://user-images.githubusercontent.com/24809312/40277534-ac577066-5c20-11e8-80a8-7eafa7c81222.PNG)

**Comment by AizenKnower** [comment]
Je pense pas vu que ca a voir avec kodi ou les plugin car j'ai jamais eu de plantage de kodi surtout avec les iptv vu que j'ai la tv avec le pvr client simple et livestreampro et meme les addon qui fournissent des LISTE iptv comme teamtuga ou loganaddon ou stallion ou rstiptv ou amerikana etc... meme kodilive fonctionne mais meme quand y a un bug ca fait pas planter kodi.

Ben tanpis merci quand-même

**Comment by Arias800** [comment]
Je suis entrain de me demander si c'est pas pvr simple client par tout hasard qui ferai tout planter

**Comment by Arias800** [comment]
Tu a kodi 18 repasse sous kodi 17 car kodi 18 est en alpha et d’après le team de kodi il est loin d’être stable ça peut venir de la

**Comment by AizenKnower** [comment]
C'est ce que je me suis dis aussi donc tu a lequel exactement si tu pouvez me dire quelle version avec la date precisement comme ca je suis sûr que çà marchera puisque le tien marche

Merci

**Comment by Arias800** [comment]
J'ai la toute dernière version de kodi 17 en stable sur une box android et ça marche après je ne peux pas être sur a 100% que ça marche mais normalement ça devrait

**Comment by AizenKnower** [comment]
Ok Jvais tester çà en espérant que ca marche merci

**Comment by Arias800** [comment]
J’installe kodi 18 et je te tiens au courant ^^

**Comment by Arias800** [comment]
Le crash est liée a kodi 18 je cherche pourquoi donc si tu veux profiter de cette option de vstream retour a kodi 17 obligatoire ^^

**Comment by AizenKnower** [comment]
Cher Arias800 ne le prend pas mal mais jusqu'ici tous fonctionnent sur kodi 18 et si on veut profiter de cette option je comprends qu'il faut kodi 17.

Mais n'est ce pas plus simple que de rendre cette option compatible kodi 18? Faut pas mieux resoudre ce bug plutôt que de demander  a de downgrader kodi et tous ce qui implique sauvegarde restauration avec probablement des incompatibilité d addons ou autre problème ?

Je vais du coup zapper cette option car faut resoudre les bugs plutot que régresser les applications a des verstions anterieur et risquer de tout chambouler.

Merci  quand meme

**Comment by Arias800** [comment]
Je me suis mal exprimé pendant que je cherche une solution il faut passez par kodi 17 mais uniquement le temps que je cerne le problème bien-sur qu'il faudra que ça marche sur kodi 18 a l'avenir ^^

**Comment by Arias800** [comment]
@AizenKnower je crois avoir trouvez je te tiens au courant

**Comment by AizenKnower** [comment]
Bon courage je reste en kodi 18 comme ça je testerais tes corrections sur cette option. Merci

**Comment by AizenKnower** [comment]
J'ai copié coller et c'est bon çà plante plus mais M3U playlist ne s'ouvre pas 
Mais les backup s'ouvre mais par contre ma liste semble reduite dans celui du 20 mai par rapport au 19mai mais je suppose que c'est normal si ca provient de 2 sources différentes ?

**Comment by Arias800** [comment]
C'est tout sur le même site mais les chaine dispo change car la liste change tout simplement . Bon les 1er ne s'ouvre pas souvent je ne sais pas pourquoi mais le principal c'est que ça tourne du coup je mets sur la beta (avant je vérifie si ça tourne sur kodi 17)

**Comment by AizenKnower** [comment]
Ya un souci de buffering qui saccade la lecture en fonction de la résolution. Plus cest hd et plus la lecture est pas fluide

**Comment by Arias800** [comment]
je verrai ce que je peux faire plus tard parce que la je me suis trop pris la tête dessus x)

**Comment by AizenKnower** [comment]
Je comprend t'inquiète pas merci pour cette option ca rend vstream incontournable et complet. J'espère que vstream durera très longtemps

**Comment by Arias800** [comment]
D’ailleurs Vstream a un système d'epg dans le menu contextuel (je ne sais pas si il est a jour mais il existe) ^^

**Comment by AizenKnower** [comment]
Je pense que ma playlist peut etre retirer car selon l addon xtream-codes iptv la playlist expire le 17 mai donc je pense pas qu'il refonctionnera sauf si l abonnement est renouvelée (j'essaierai de trouver une autre mais j'utilise les site 
Iptvsource 
Iptvgratuit
Iptv4sat 
Café-tv
Wiki iptv
C'est l'aiguille dans une botte de foin lol de trouver quel playlist est stable

**Comment by Arias800** [comment]
Je la retirerai la en suis entrain de tester une autre méthode pour avoir des liste
Mais oui c'est pénible pour trouver de un site proposant du contenu fonctionnel

**Comment by johngf** [comment]
"Ya un souci de buffering qui saccade la lecture en fonction de la résolution" @AizenKnower 
ça a toujours était le cas les liens sont souvent des playlist (.m3u8 , .ts) donc >>> pas de cache dans kodi
il faut que le serveur envoie a débit élevé et constant et c'est jamais le cas donc au finale c'est inutile de  l'integré a vstream t'auras une chaine qui va fonctionné une fois tous les 10 du mois

**Comment by AizenKnower** [comment]
La playlist que j'avais fourni est down car expirée ya 1 semaines
Cest grâce a l addon ULTIMATE IPTV que je trouve un iptv correct.
J'entends par correcte qu'il dure des mois et quand arrive a expiration je le remplace par une autre

Du coup la ya 2 playliste une qui devrai durer jusque novembre 2018 :
http://linux-app.tv:8080/get.php?type=m3u&username=Reda&password=Reda 

Celle ci dessous malheureusement ne dure que jusqu'àu 6juin mais les chaînes sont plus intéressante car ya les chaînes tv canadien français très rare a trouver

J'essayerai de trouver un autre qui dure aussi 6 mois comme lien de secours et qui contiendrait des chaînes francophones canadienne
http://p4.giffy.be:8080/get.php?username=thalia&password=thalia&type=m3u

**Comment by Arias800** [comment]
Ok je les ajouterai jeudi ou vendredi merci d'ailleurs j'ai ajouter 2 autre site de liste iptv

**Comment by Arias800** [comment]
Nouvelle version avec l'ajout de tes deux liste + plusieurs modification https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/freebox.py

**Comment by AizenKnower** [comment]
Je teste tes fichiers mais pour

Iptvsource , il y a les playlists par date et dans chacune des dates ya 3 possibilités donc 2 backups

Malheureusement  ne s'ouvre pas et pour les backups je me demande si il manque pas des chaines genre page 2 etc...
Pareil pour daily iptv la liste est courte

Pour iptv gratuit le temps de charge de la playlist est longue mais bien que la liste tres complete beaucoup ne marche pas.

Peut on inclure un lecteur externe a vstream pour la lecture ? Jaimerais que ça ouvre avec Perfect Player qui gere bien iptv

**Comment by Arias800** [comment]
La lecture externe je pense pas que ce soit possible . Pour iptv source c'est normal qu'il n'y est pas de page suivante j'ai tout simplement parce eux le temps de regarder. Pour les temps de chargement long je suis au courant j'ai d'ailleurs bien rétréci la fonction qui parse le m3u . Je pense inclure le site utiliser par ultimate iptv pour rajouter plus de contenu
En tout cas merci du retour ^^

**Comment by AizenKnower** [comment]
Si tu rajoute ultimate iptv tu pourras supprimer mes playlists car elles viennent de ce addon pour evitez les doublons.merci

**Comment by Arias800** [comment]
Nouvelle version ou je réduit les temps de chargement de beaucoup x) et corrige le bug de certaine playlist d'iptvsource qui ne s'ouvrait pas ^^

**Comment by AizenKnower** [comment]
J'ai testé la nouvelle version mais la playlist iptv source  "M3U Playlist" ne souvre toujours pas mais les backup list 1 et 2 oui)

Iptv gratuit est celui qui marche le mieux car les playlist de la veille fonctionne encore et maj rapidement.

La liste d'Aizenknower ne s'ouvre pas chez moi (p4 giffy) et l autre les chaine ne se lance pas.
Peut tu me dire si chez toi ça marche car normalement c'est valable jusque 6juin et novembre 

Sans vouloir t embeter avec ça tu en est où pour inclure ultimate iptv?
Merci

**Comment by Arias800** [comment]
Pour la liste d'Aizenknower les liens sont down même via navigateur . Ensuite pour le site d'ultimate iptv ce sera dans la prochaine maj comme le next page pour iptv source ^^ Pour les "M3U Playlist" je sais pas pourquoi ça ne veut pas il doit y avoir un truc que kodi aime pas mais j'ai pas encore trouvez quoi ^^

**Comment by AizenKnower** [comment]
Sauf que mes playlists fonctionne sur une application apk lecteur m3u comme perfect player mais pas sur vstream. 
Je viens de tester les et la chaine demarre d ailleur bien.

Mais bon si tu met ultimate iptv pas sur que resoudre ce problème soit utile car elles sont dans ultimate iptv.

Moi je cherche plutot des playlist stable pour perfect player car kodi lis mal les iptv (lecteur  qui bug)

**Comment by Arias800** [comment]
Voila nouvelle version avec le next page pour iptvsource et l'ajout du site utiliser par ultimate iptv ^^

**Comment by Arias800** [comment]
Si tu veux @AizenKnower je peux mettre la possibilité de générer un fichier m3u automatiquement via kodi que tu peux lire avec perfect player

**Comment by AizenKnower** [comment]
Ce serait sympa car ca éviterai de taper les liens dans les reglages de perfect player 
Est ce que ce sera pour chaque sources?

**Comment by Arias800** [comment]
Oui car ca se position en meme temps que l'affichage des lien sur kodi par contre il faudra mettre toi meme le chemin ou tu veut créer le m3u et effacer a chaque fois le contenu du fichier avant d'en régénérer un car sinon ca mets tout a la suite

**Comment by AizenKnower** [comment]
Par decomment tu veux dire Je supprime les ligne 504 a 507 
Si je veux enregistrer dans le dossier "download" qui est dans "mes fichiers" (la où y a les dossiers : android , document, video, music, backup...etc..) :
J ecris juste open('file/download, 'r+b) as f: ? 
Corrige moi stp si je me trompe

**Comment by Arias800** [comment]
Par decommenter je parle d'enlever le # devant les ligne car si il sont la kodi ne les lit pas
Tu est sur quel os ?

**Comment by Fabiodirt** [comment]
Bonjour à vous,
Je viens de découvrir cette fonction iptv hier et je viens ici vous dire un grand merci pour le taf abattu ! 
Je vais suivre de près ce que vous faites.
Certaines chaines ramaient un peu hier ou se figeaient...Mais ça a été un test rapide... :)
Je vais suivre ce post de près.
Encore merci à vous !

**Comment by Arias800** [comment]
Si les chaîne rame je n'y peut rien c'est pour ça que j'ajoute plusieurs site comme ça il y a plus de choix

**Comment by Fabiodirt** [comment]
Yes je sais que tu n'y peux rien.
Encore merci
