### ISSUE TITLE
SSL error.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2084]
Bon les bande annonces deconnent, c'est normal
"SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)"

Il faudrait faire comme dans le fichier BA.py pour que ca marche.

Je ne voit aucun moyen pour savoir si on doit ou pas utiliser le ssl, mais du coup pour eviter les problemes il faudrait le faire a toutes les urls (ou du moins celle qui commence par https), y a peu de modifs a faire dans le fichier requesthandler mais gros chnagement dans le traitement de vstream (et gros prb pour ceux qui sont sur de vielles versions)

Quelqu'un a une autre idee ?

Ou alors si on a cette erreur refaire la requete ? ca va ralentir mais pour le moment y a que uptobox et youtube qui font chier avec ca.

**Comment by johngf** [comment]
elle deconne ou ? avec kodi 16 ?

**Comment by Arias800** [comment]
Si il y a le ssl c'est normale que ça marche avec Kodi 17 puisque c'est la première versions supporter le ssl

**Comment by LordVenom** [comment]
> Bon les bande annonces deconnent, c'est normal
> "SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)"
> 
> Il faudrait faire comme dans le fichier BA.py pour que ca marche.

1 quoi le fichier BA c'est les bandes annonce.

**Comment by TmpName** [comment]
Ben j'ai kodi 17, et chez moi ca marche pas ? Prb de config chez moi, ou ca deconne aussi chez vous ?
Le coup du https ne suffit pas, il ya plein de site en https qui ne posent pas de problemes, ca va peut etre chnager avec le temps mais pour le moment je trouve ca agressif.

Le fichier BA.py fonctionne, mais pour voir le lien il passe par le fichier hoster de youtube qui lui n'est pas equipe pour le ssl (il passe par requesthandler).

En fait ma question, est "est que ca vaut le coup de le faire pour TOUTE les urls en https dans le fichier requesthandler ?
Ou est ce que c'est moi qui suis mal configure ?

**Comment by johngf** [comment]
J'ai jamais eu d'erreur ssl avec kodi17 sur Windows et kodi16 sur linux

**Comment by TmpName** [comment]
Tu as essaye de visualiser une bande annonce via menu contextuel/ bande annonce ?
Ici j'ai aussi kodi 17 win 7.

**Comment by johngf** [comment]
Bah oui je le fait souvent  et la j'ai test plusieurs n'a et aucun soucis

**Comment by TmpName** [comment]
Ben ca me le fait depuis quelques jours, ca marchait au moins la semane derniere.
La je viens d'installer kodi 17.6, meme probleme, ca parle d'une histoire de version de python ou de certificat dans les variables d'environnement, mais je vois pas pkoi ca marcherait chez toi et pas chez moi. On a la meme version de kodi sur le meme OS, et j'ai rien de plus sur cette machine, ca ne me sert que pour la TV.

Sinon tu as 
sHtmlContent = oRequestHandler.request() pour recuperer le code html mais aussi
oRequestHandler.getRealUrl() pour l'url de redirection
oRequestHandler.GetHeaders() pour les cookies (je viens de voir un bug, on melange GetHeaders() et getResponseHeader().

Normalement si tu passes par requesthandler tout est recupere si tu utilise la lib en direct il te faut faire comme dans la lib
```
CF = cloudflare.CloudflareBypass()
sContent = CF.GetHtml(self.__sUrl,e.read(),cookies,sParameters,oRequest.headers)
self.__sRealUrl,self.__HeaderReturn = CF.GetReponseInfo()
```

**Comment by johngf** [comment]
Ok sinon ba oui mais ça fonctionne pas 503 redirection j'avait deja test patraque la lib cloudflare retourne une page vide moi je veut l'url et geturl retourne la précédente url

**Comment by TmpName** [comment]
J'avais deja eu le prb, attend je recherche si je retrouve le code.

**Comment by TmpName** [comment]
Bon j'ai trouve comment faire, en fait tu trouve la redirection dans les headers.
Pas dans geturl vu que la redirection est bloquée.

La je me tate si il faudrait pas desactiver le "non direction" pour ce cas precis ?

Quand tu n'as pas les cookies, il faut bloquer la redirection pour ne pas aller sur la page 503, mais tu as les cookies, pas sur qu'il y en ai besoin ...

**Comment by TmpName** [comment]
Bon j'ai mit une nouvelle version de cloudflare.
Elle a l'air de tourner, mais elle risque de foutre le bordel sur certaine source existante.
En fait il faut bloquer la redirection sur l'erreur 403 de cloudflare mais quand les cookies sont generee, si redirection il y a c'est celle du site, donc a suivre.

**Comment by johngf** [comment]
il y a un bug maintenant l'acces au site protéger par cloudflare ne fonctionne plus voir films stream zz

**Comment by LordVenom** [comment]
C'est quoi le nom du .py je trouve pas de films stream zz

**Comment by johngf** [comment]
Il n'y a pas de films c'est que des séries mais c'est un soucis avec la lib cloudflare

**Comment by TmpName** [comment]
Essayes avec la derniere versions, elle marche mais il faut 2 / 3 essais, et je sais pas pkoi.
Une fois j'avais vu une protection antibot, declenchee je sais pas comment (y avait un captcha), faudrait enregistrer toutes les pages et les regarder, mais c'est tellement aleatoire ...

**Comment by johngf** [comment]
ça fonctionne mais les 2 3 essais était deja la avant je crois a cause des 5 secondes peut etre pas assez pour le site il rame un peu c'est temps ci
de mon coté je cherchai a faire une fonction comme getrealurl mais le code dans request handler et cloudflare et fait a la base pour retourner le contenu d'une page
tant que ça fonctionne comme ça c'est bon
