### ISSUE TITLE
Mise à jour 0.61 Recherche affiche aucun résultat

### ISSUE THREAD

**Issue by UNILIEN** [Kodi-vStream/venom-xbmc-addons#2085]
Bonjour,

j'ai fait la mise a jour de vStream à 0.6.1 et la recherche semble fonctionner normalement, je vois défiler les résultats mais au moment d'afficher, le résultat est systématiquement vide

J'ai enlevé la version 0.6.2 et remis la version 0.60 et cela fonctionne

Quelqu'un peut m'aider ?

**Comment by vincgag** [comment]
J’ai le même problème. Merci d’avoir ouvert.

**Comment by johngf** [comment]
#2074 pas utile d'en ouvrir une autre.

**Comment by blacksnacke** [comment]
Salut,
mais cmt activer/desactiver les Source si rien n y apparait. Voila cmt ca se presente chez moi. Je ne peux donc pas choisir une source. L'option des Plugins a disparu dans cette version.
Version 0.61 sur Window et sur Android TV box.
Avez vous la meme image chez vous? Qui pourra m aider

![image](https://user-images.githubusercontent.com/28162815/40464807-b27b799c-5f1d-11e8-8fb8-b78a7dfc0887.png)

**Comment by Arias800** [comment]
Merci de ne pas poster plusieurs fois le même message sur 2 issue différentes ^^
