### ISSUE TITLE
Zt Down

### ISSUE THREAD

**Issue by camelone** [Kodi-vStream/venom-xbmc-addons#2089]
Juste pour info, ZT down.. bug ou fermeture? Croisons les doigts...

**Comment by Arias800** [comment]
Même àvec cette version ça ne marche pas https://pastebin.com/Tp3dRuh3?

**Comment by lebigboss** [comment]
@Arias800 
Avec ton lien ça fonctionne merci

**Comment by camelone** [comment]
Hier, ils ont probablement eu un probleme avec leur site.. beaucoup d'erreurs sql.. aujourd'hui ça marche mais j'ai l'impression de retrouver dans les nouveautés les films des mois précédents...

**Comment by ddav33** [comment]
Je confirme y a un bug , plus moyen d'avoir ces anciens marque page et beaucoup de sériés ne sont plus complète ainsi que certains films

**Comment by johngf** [comment]
c'est normal quand tu mets en marque pages c'est avec une certaine url du site mais comme il n'arrete pas de changer du coup mauvaise url  >>>> ça fonctionne plus

**Comment by perive** [comment]
L'url où les séries sont complètes est https://zone-telechargement.pw mais en mettant à jour le fichier, ça ne marche pas contrairement avec les modifications d'url précédentes.

**Comment by Arias800** [comment]
Le lien "officiel" c'est celui là https://1ww.zone-telecha_gement1.com

**Comment by perive** [comment]
Peut-être mais avec ce lien, les séries sont très incomplètes.

**Comment by Arias800** [comment]
au pire je propose qu'on attends de voir si il corrige ça et si il ne le font pas je changerai de liens ^^

**Comment by TmpName** [comment]
Ils ont plusieurs url qui fonctionnent mais pas les meme pages ?

Sinon on peut reutiliser la methode du fichier pastebin pour toute les fonctions, ca va resoudre le problemes quand on met en marque page, mais si il y a plusieurs urls qui fonctionnent la c'est plus complique.

**Comment by Arias800** [comment]
Soit il on plusieurs site qui servent de backup soit c'est un clone

**Comment by perive** [comment]
ça expliquerait pourquoi cette url ne fonctionne pas dans zone_telechargement_ws.py ?

**Comment by Arias800** [comment]
oui il y a peut être des modif à faire dans le code ^^

**Comment by TmpName** [comment]
En fait le prb du code de pastebin, c'est que ca part d'une bonne adresse, regarde si le site fait une redirection ou pas, et chnage en fonction l'url.
Donc dans tout les cas il faut au moins une bne url a la base, si on prend les urls des sites incomplets c'est mort.

Mais moi ce qui me choque, c'est que les gens vont sur son site, mettent le site en favoris, quand zt chnage d'url c'est normal que la premiere url envoit sur la nouvelle, si elle renvoyait sur une url d'archive le mec verrait un site incomplet et n'y reviendrait plus, pas du tout perein comme methode ....

Pour moi le mec a une collection d'url de sites complets qui se renvoit rgulierement sur les autres, et une autres de clones ou backup a ne jamais aller qui ne renvoit pas sur les premieres.

**Comment by camelone** [comment]
Au fait d'après les commentaires sur leur site, ils se sont fait hackés et sont repartis sur un backup d'avril.. ils travaillent à réalimenter les sources...

**Comment by camelone** [comment]
Chez moi tout fonctionne mais on voit que les toutes dernières nouveautés ont disparu...

**Comment by TmpName** [comment]
Ok ^^, ca explique pas mal de trucs.

**Comment by Arias800** [comment]
ça paraît plus probable du coup on attends qu'il reajoute du contenue où on mets l'autre site en attendant ?

**Comment by camelone** [comment]
C'est beaucoup de boulot de mettre les 2? Et de les nommer différemment?

**Comment by camelone** [comment]
Sincèrement je serais bon en prog je proposerais volontiers de le faire.. mais je suis une clinche!

**Comment by Arias800** [comment]
Tout dépends si il y a des modif je jette un œil de demain ^^

**Comment by perive** [comment]
Y'en aura. Les chemins sont pas les mêmes...

**Comment by Arias800** [comment]
Je me suis posée la même question x)

**Comment by Arias800** [comment]
En faite je suis pas sur que ça vaut le coup d'ajouter ce clone car le site de base ce reremplie vachement vite ^^

**Comment by Arias800** [comment]
Quelqu'un peut faire les modif a ma place car chez moi le site faire crasher kodi tout le temps (j'ai modifier les regex mais je n'en ai pas trouvez un qui fonctionne bien)

**Comment by TmpName** [comment]
Donc au final vous voulez faire quoi ?
Attendre que ca se stabilise ?
Partir sur quelle url ?
Prise en charge de la redirection ?

**Comment by Arias800** [comment]
Moi je suis d'avis d'attendre qu'il reremplisse le site car ça va relativement vite et le clone est pas terrible (tres lent et fait crasher kodi chez moi)

**Comment by perive** [comment]
Il se passe de drôles de truc avec ZT. Le site se restaure mais beaucoup de vidéos réapparues sont introuvables via Vstream alors qu'on y accède sur le site direct. Les vidéos qui n'avaient pas disparu fonctionnent toujours sur Vstream.

**Comment by perive** [comment]
Help !

**Comment by Arias800** [comment]
Si personne ne répond c'est que personne n'a eux le temps de regarder en ce qui me concerne j'entre dans ma période d'examens donc tu peux comprendre que j'ai d'autre préoccupations ^^

**Comment by perive** [comment]
Of course ! 
Je ne savais pas si mon message était valide d'où ma petite piqûre de rappel...
Merdum pour tes exams ;)

**Comment by perive** [comment]
Les nouveaux liens de fichiers sont en https et les liens des fichiers non disparus sont restés en http.

**Comment by Arias800** [comment]
J'ai rien vu de suspects chez moi vérifie que tu a bien la dernière version du fichier

**Comment by perive** [comment]
Avec la version 0.6.2, ils doivent être tous à jour, non ?
J'ai remarqué avec ZT que les liens en https que l'on voit dans la page dl-protect envoient sur des pages (uptobox par exemple) où n'apparait pas le streaming alors que les liens en http montre ensuite la page avec la fenêtre de streaming.

**Comment by Arias800** [comment]
Ça dépends quand la mise a jour en vert apparait . Chez moi pas de différence entre le http et le https

**Comment by perive** [comment]
Je mets à jour à chaque fois. Le problème est apparu depuis le crash de ZT. Je vais remettre zone_telechargement_ws.py pour voir...

**Comment by perive** [comment]
C'est pareil. Je me demande comment Vstream peut choper des streamings quand on ne peut pas sur le site direct.

**Comment by Arias800** [comment]
J'en est aucune idée mais de toute façon ce site a toujours eu des réaction bizarre x)

**Comment by perive** [comment]
Et en plus on est pas tous égaux vis-à-vis de ce site ! Est-ce que par exemple The Americans vostfr s06e03 fonctionne chez toi ?

**Comment by perive** [comment]
Oui, ben, sur le site direct, il est dispo.

**Comment by Arias800** [comment]
Non même sur le site d'uptost_eam il est pas dispo (j'ai essayer en 720p alors peut être qu'il est dispo en hdtv je sais pas)

**Comment by perive** [comment]
C'est donc pour ça que la fenêtre de streaming n'apparait pas sur le site direct ? Mais alors, en DDL, ça devrait le prendre puisque ça marche sur le site.

**Comment by Arias800** [comment]
Ça dépends tu est premuim ou pas ? Dans tout les cas zt n'est pas la source du problème ^^

**Comment by perive** [comment]
D'accord, mais sur uptobox, le téléchargement est possible pour les non premium...

**Comment by Arias800** [comment]
Oui mais si tu est en gratuit tu est obliger de passez par uptostr_am pour voir un fichier sur uptobox

**Comment by perive** [comment]
C'est bizarre parce que le lien de téléchargement pointe sur uptobox et pas sur uptostream...

**Comment by Arias800** [comment]
Après je peux pas t'en dire plus car je ne sais pas comment marche la fonction de téléchargement

**Comment by perive** [comment]
ok, merci

**Comment by camelone** [comment]
Depuis ce matin ZT est HS. Plus aucun lien dispo et recherches vides... Quelqu'un peut tester?

**Comment by camelone** [comment]
Aie.. Erreur 502 sur leur site.. Ont-ils encore changé de nom de domaine?

**Comment by camelone** [comment]
Je viens de tester https://www.zone-telechargement1.pw. Est-ce le bon ou un clône?

**Comment by Arias800** [comment]
Non le site est down pour le moment

**Comment by camelone** [comment]
Les liens ont l'air corrects. Ca passe par https://www.dl-protect.top et les liens sont bons, j'ai testé...

**Comment by Arias800** [comment]
Le clone aussi est down x)
