### ISSUE TITLE
Question stupide

### ISSUE THREAD

**Issue by johnboisvert** [Kodi-vStream/venom-xbmc-addons#2090]
Bonjour,
petite question surment stupide mais qui me dérange un peu :) 
j'aimerais savoir quand ont va dans visual search je vais dans film populaire,
lorsque les films apparaissent, ont les voit en liste .. VUE : LISTE et je change toujours en VUE: MUR 
mais lorsque je change de page , ca revien toujours à VUE: LISTE 
est-ce qu'il y a moyen de faire VUE: MUR PERMANANT ? 
désolé pour ma question newbie j'ai regarder dans la config jai rien trouvé :(
Merci a vous c'est magique !!

**Comment by LordVenom** [comment]
![image](https://user-images.githubusercontent.com/4380112/40467618-e7a04faa-5f2a-11e8-93ee-238d0c52ea4b.png)

**Comment by johnboisvert** [comment]
Les settings etais deja comme ca 
merci de vos explications c'est assez clair :)

**Comment by LordVenom** [comment]
@KiliK150  Mince elle est pas claire cette fonction ?

Vue recherche visuelle : (modifie la vue de la recherche visuelle)
Activer vue personnalisée (pour les autre menu)
Vue default (dossier, lien, source)
Vue accueil (lol vue de l'accueil)
Vue films (non serieux ?)
vue Series (bon ben la...)

Je plaisante bien sur, mais si tu as une autre façon d'expliquer ça. Dit moi ça peux m'aider, vue que je suis dans le code pour moi c'est logique mais pas forcement.

**Comment by AizenKnower** [comment]
J'ai eu le même souci qui a été résolu en désactivant "vue personnalisé"

**Comment by KiliK150** [comment]
@LordVenom , oui c'est dommage que l'ID change d'un skin à l'autre. Mais bon après c'est vrai que c'est plutôt simple lorsque tu sais que tel chiffre correspond à telle vue.

**Comment by thorsten68** [comment]
Elle est pas stupide ta question, je me suis aussi déjà demander si on peut pas bloquer la vue mur. Merci !

**Comment by Arias800** [comment]
Aucune question est stupide et de toute façon on est la pour y répondre ^^
