### ISSUE TITLE
Problème 1fichier

### ISSUE THREAD

**Issue by perive** [Kodi-vStream/venom-xbmc-addons#2091]
Bonjour,
Les fonctions "Télécharger" ou "DL et Lire" sur 1fichier ne fonctionnent pas.
Elles renvoient "Fichier introuvable" ou "Lien non résolvable" ou "Téléchargement impossible"...
Rien n'explique le problème dans la log.
Tous mes fichiers Vstream sont pourtant à jour.
Merci pour votre aide.

**Comment by LordVenom** [comment]
Bonjour, quel site ? quel lien ?

**Comment by perive** [comment]
Tout site proposant cette source pour tout lien.

**Comment by johngf** [comment]
tu as un compte premium ?

**Comment by johngf** [comment]
ok je viens de voir pourquoi il ont ajouté un truc a posté avant d'avoir le lien final

**Comment by perive** [comment]
ça correspond à la page supplémentaire sur le site ?

**Comment by johngf** [comment]
non c'est pour savoir si tu sais modifier le fichier toi meme

**Comment by perive** [comment]
oui, dis-moi la modif à faire

**Comment by perive** [comment]
android tv

**Comment by perive** [comment]
android

**Comment by johngf** [comment]
le fichier est la [ici](https://github.com/johngf/test/blob/master/onefichier.py) 
clique sur bouton raw copier coller tu remplace le contenu de onfichier.py vstream /resources /hoster/ 

ou clique droit sur bouton raw enregistrer sous chemin >> vstream /resources /hoster/ 
il doit remplacer l'autre .

**Comment by perive** [comment]
Super, ça marche. Bravo johngf et merci.

**Comment by johngf** [comment]
si une personne en premium passe par la vous avez le meme problème ?

**Comment by vstreamkodi** [comment]
Ça fonctionne avec mon compte premium. La fonction 'Telecharger' est très lente avec moins de 0,1 MB/sec. La fonction 'DL et Lire' telecharge quasi au debit max. Le fichier télécharger se renomme systématiquement en .flv qui est agaçant. Serait-il possible de corriger le problème du débit ralentit en mode 'Telecharger', garder l'extension du fichier d'origine et enfin avoir l'accès la fonction VotreCompteOnefichier dans les sources (comme pour Uptobox)? La fct Telechager pour les liens uptobox est aussi brider à - de 0.1MB/sec.

**Comment by johngf** [comment]
La fonction télécharger à été modifier il me semble il y a un moment déjà par
@TmpName ou @lordvenom

**Comment by TmpName** [comment]
L'extension flv se met quand il n'y a pas d'extension. Les liens sont du type "...ier.com/?j93h5oeff9", comment tu veux deviner l'extension ? Elle apparait dans le header "Content-Disposition" en reponse a la requete, et rien ne le gere encore car ca ne sert a rien pour etre "streame".

La fonction telecharger est bridee (ce n'est pas un bug), normal Vstream n'est pas une application de telechargement. Elle sert a visionner des streaming. Donc si le telechargement se faisait a fond, les user n'auraient plus assez de bande passante (et de ressources, Kodi est tres lourd) pour pouvoir se servir du reste. L'utilite du truc est de mettre les fichier recalcitrants en DL quand le stream ne marche pas, tout en puissant continuer a regarder autre chose.
Ceci dit 0.1 MB/s ca fait peu, meme avec la pire des connections tu devrais avoir plus. il faudrait 2h pour un fichier de 700 M. Mais ca depend de la taille des paquets que propose le serveur.

**Comment by vstreamkodi** [comment]
Ok, merci pour l'info. La fonction 'DL et lire' devra donc être bridée. Le débit de la fct 'Telechager' est bien inférieur à 0,1 Mo/sec car je met qq 
min pour télécharger un zip de 10Mo via VotreCompteUptobox. La fct 'Telechager' reste 
intéressante pour les fichiers strm (ex:plugin://plugin.video.vstream/?function=play&site=cHosterGui&...) et pour éviter de prendre une clé USB. Serait-il possible de développer la même source que VotreCompteUptobox pour 1fichier.com afin de récupérer les fichiers perso?

**Comment by perive** [comment]
Pourquoi brider la fonction "DL et lire" ? C'est une fonction de streaming aussi !

**Comment by vstreamkodi** [comment]
En passant par 'DL et lire' sur un fichier de 300 Mo ça me telecharge le fichier en 5 secondes dans mon répertoire download. Hors c'est pas fait pour ça si j'ai bien compris. En plus ça prend de la mémoire pour rien qd c'est un gros fichier. Par contre qd on a pas de débit c'est vrai que ça peut être utile.

**Comment by perive** [comment]
Cette fonction me sert quand je ne peux pas visualiser directement. Je supprime le fichier téléchargé ensuite. L'avantage d'un débit correct pour cette fonction est la mise en buffer rapide qui permet de commencer la visualisation assez rapidement sans attendre trop longtemps.

**Comment by vstreamkodi** [comment]
Ok pour moi ça fonctionne avec ou sans la modif du fichier.
