### ISSUE TITLE
Acces à la recherche

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2095]
Quelqu’un pourrait m'expliquer comment avoir accès aux informations de la recherche sur des sites comme Streamay ou Streamiz

merci

**Comment by Arias800** [comment]
Pour Streamiz il fallait juste trouvez quel lien était utilisez pour la recherche et ensuite trouvez le regex  pour parser le json

**Comment by razorex** [comment]
justement moi j'ai une fenêtre qui s'ouvre mais je ne trouve pas l'url... j'ai désactivé la recherche des séries sur streamay, car pas de résultat sur les séries et j'aimerais la remettre.

**Comment by LordVenom** [comment]
J'aurais pas fait comme ça un  json.loads(sHtmlContent) ne resoult pas le soucis ?

**Comment by LordVenom** [comment]
Note pour répondre a ta question : 

On fait pas tous pareil, moi j'utilise Chrome et son outil de développement. et donc je vais faire une recherche sur le site avec mon outil de developement ouvert et je fait une recherche bidon genre "avatar".

![image](https://user-images.githubusercontent.com/4380112/40605265-14feb8e4-6262-11e8-8632-046d981bebc3.png)

Donc je sais que l'url c'est /search que le header demande le referer et que c'est en post et l'id de la recherche c'est "K".

**Comment by johngf** [comment]
Json le soucis C'est que si il manque une } ça fonctionne plus
le code doit être correctement fermé c'est pour ça que je ne j'avait pas utilisé pour streamay après avoir remarqué des soucis .
