### ISSUE TITLE
Regex qui prend un caractere a la fois

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2096]
J'ai de plus en plus de problème avec les regex (surtout sur les site d'iptv) ou je ne sais pas pourquoi mon regex prends un caractère a la fois voila le regex
![capture](https://user-images.githubusercontent.com/24809312/40576051-677c84d4-60f0-11e8-9c05-23b3aa264019.PNG)
et voila ce que je veux récupéré `<br />
http://lista.digita_group.me/get.php?username=dud&amp;password=dud&amp;type=m3u<br />` Si quelqu'un a une idée je suis preneur ^^

**Comment by johngf** [comment]
'([^<]+)' test ça

**Comment by Arias800** [comment]
Voila la page html https://pastebin.com/Cxtn6idw

**Comment by Arias800** [comment]
C'est bon j'ai trouvez en découpent le regex en 2 `'<br />http([^<]+)/(.+?)<br />'` et en le reconstituant après ça marche x)

**Comment by johngf** [comment]
bah '<br />([^<]+)<br />' celui la fonctionne mais en oublie 2 vu que la page est pas uniforme manque 2 br

**Comment by Arias800** [comment]
D'accord ^^

**Comment by johngf** [comment]
[exemple dans ce site](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/streamfilmzzz.py)

**Comment by TmpName** [comment]
Sinon
`>\s*(http[^<]+)<br \/>`
