### ISSUE TITLE
problème compte premium uptobox

### ISSUE THREAD

**Issue by tiger92150** [Kodi-vStream/venom-xbmc-addons#2097]
bonsoir,
j'ai un compte uptobox premium.
je n'ai plus la popup du choix entre les deux modes habituels : le streaming et le lien direct.
Ce qui laisse envisager un nouveau problème d'authentication.
je n'ai pas non plus la confirmation habituelle "authentification réussie".
sachant que sur le site internet d'uptobox quand je me connecte ça fonctionne normalement.
est ce qu'il y'a quelqu'un parmis vous qui rencontre le même problème.
Merci d'avance.

edit : après visonnage d'une série, j'ai eu la confirmation qu'il y'a un problème d'authentification en compte premium.

**Comment by johngf** [comment]
#2075 tu n'est pas a jour a mon avis

**Comment by tiger92150** [comment]
merci pour ta réponse johngf.
non je suis à jour.
j'avais le même problème mentionné dans l'issue #2075, utopbox ne fonctionnait qu en direct seulement.
mais j'arrivais à me connecter en mode premium tout de même.
là il y'a un problème d'authentification en compte premium, je n'ai plus la popup du choix entre les deux modes habituels : le streaming et le lien direct, et la lecture se coupe après un certain temps comme dans les comptes non premium.

**Comment by tiger92150** [comment]
merci pour ta réponse johngf.
finalement c'était un problème tout bête, apparement lors de la mise à jour, le compte premium a été désactivé dans les paramètres de configuration de vstream.
il a suffit de le renseigner à nouveau mour que tout rentre dans l'ordre.
