### ISSUE TITLE
Impossible de réinstaller Vstream sur appletv2 hélix 14.2?!

### ISSUE THREAD

**Issue by milkmann14** [Kodi-vStream/venom-xbmc-addons#2098]
Bonjour,

j’ai desinstaller suite à un problème d’icones. 
Je n’arrive plus à l’installer bien que le repository soit toujours présent. 
La notification : incompatible s’affiche. 
J’essaie d’installer des sources comme bestaddons.ca mais après validation, kodi affiche que le chemin n’exister pas. 
Je désespère de devoir vivre sans Vstream!!
Merci pour vos conseils éclairés

**Comment by KiliK150** [comment]
Regarde ceci 👉🏻 #1868

**Comment by milkmann14** [comment]
Merci KiliK150,

mais je ne suis pas certain de comprendre !
Ma version fonctionnait bien jusqu’à ce que je la desinstalle. 
Y a t il quelque part un tuto pour réinstaller cette ancienne version ou est ce que je dois comprendre que ce n’est plus possible de la réinstaller ? 
Ou faut il passer en 15.2 sur une apple TV2 ?

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/tree/master/repo/plugin.video.vstream

**Comment by milkmann14** [comment]
Je dis merci déjà à LordVenom car j’entrevois un espoir de recouvrer Vstream. 

Par contre je ne sais pas comment télécharger le bon fichier sur l’appleTv! 

Existe il une source fiable qui permette de le télécharger via kodi?

après je le jure j’économise et j’achète une box androïd!

**Comment by LordVenom** [comment]
une clef USB ? sinon tu peux entrer une URL de Depot ?

**Comment by LordVenom** [comment]
Alors ta version c'est la 0.5.7 "normalement".

Si tu peux ajouter une url de dépôt je l'ai mise dans le Dépôt Officiel.

Tuto pour le dépot : https://vstream.ga/tutorial-installation/

Note (ne pas oublie de désactiver la mise a jour).

Mes extentions/Depots d'exention/vStream repository - context menu Information - mettre a jour automatiquement.

**Comment by milkmann14** [comment]
J’ai bien suivi le tuto ( mais je suis en apparence Confluence).
Je parviens à télécharger  
le repo vstream 0.0.3 mais lorsque je vais dans extension en face de Vstream j’ai la notification « incompatible » !
J’ai essayé de desinstaller totalement le repo et laddon Vstream pour refaire l’installation avec cette nouvelle url mais idem? 
La mise à jour sur le signet latéral est bien à automatique. 

Là je me demande si j’ai pas complètement déréglé la machine !!

**Comment by milkmann14** [comment]
Est ce que je dois télécharger le pluggin 0.5.7? 

J’ai tout recommencé et maintenant j’ai un téléchargement de l’addon Vstream mais il reste à 0%!

**Comment by milkmann14** [comment]
Merci LordVenom!!! Ça a marché ! 
Vstream is back ! J’ai envie de dire Youhouuu!!
