### ISSUE TITLE
Problème connexion erno 7 vstream 

### ISSUE THREAD

**Issue by El-dede** [Kodi-vStream/venom-xbmc-addons#2102]
Vstream fonctionnait à peu près bien jusqu'à aujourd'hui, impossible de charger un film. L erreur erno 7, problème de connexion apparaît à chaque fois.
J utilise kodi sous Android sur ma box tv.

Quelqu'un a t il une idée de ce qu il ce passe ?

Merci Beaucoup de prendre le temps de me répondre.

**Comment by LordVenom** [comment]
Bonjour, Version de vStream ? un log ?

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by El-dede** [comment]
Version 0.6.2 de vstream, j essai de vous envoyer un log ce soir

**Comment by jesusisback66** [comment]
pareil pour moi mais avec l'erreur errno 111 qui s'affiche mais j'arrive encore a lire les serie en stream

**Comment by Antho59380** [comment]
Bonjour.
J'utilise kodi et Vstream depuis pas mal de temps. 
Je suis sous kodi krypton 17.6 Vstream 0.6.2 sur mi box et depuis hier j'avais un message erreur connexion impossible SSL CERTIFICATE..... ainsi que erreur ernno 7.
J'ai désinstallé kodi et je suis reparti à neuf.
J'ai toujours cette erreur ernno 7 mais ça ne gêne en rien l'utilisation de Vstream. J'accède au contenu que je recherche aisément.
Cependant j'ai un ami chez qui l'erreur ernno 7 l'empêche d'accéder aux contenus. La recherche se lance et arrivé aux résultats impossible de lancer quoi que ce soit.
J'espère avoir été clair. 
Vous faites du super boulot.

**Comment by johngf** [comment]
au risque de se répéter ou avez-vous cette erreur >>> des details ...

**Comment by Antho59380** [comment]
Alors pour ma part c'est à la fin de la recherche.
Pour l'erreur SSL CERTIFICATE c'était au cours de la recherche puis au lancement de divers liens

**Comment by El-dede** [comment]
Cette erreur apparaît juste avant le chargement de la vidéo. J'ai cette erreur sur mes deux box kodi. Sur ma mi box sur Android tv cela empêche de charger les vidéos, sur la box Bouygues également Android tv, les vidéos se charge normalement.

J essai de fournir le log des que je peux. 

Merci beaucoup pour votre travail.

**Comment by johngf** [comment]
sur upto box ou 1 fichier ?

**Comment by Antho59380** [comment]
Quasiment tous les hébergeurs.
Pour le log je n'ai jamais fait t'aurai un lien qui explique comment faire ?

**Comment by LordVenom** [comment]
Dans les outils de vStream : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by johngf** [comment]
vous avez url resolver activé ou pas ? dans les parametres de vstream (déconseillé)

**Comment by Antho59380** [comment]
@LordVenom merci je vais essayer de vous envoyer le log ce soir

@jhongf je n'ai pas l'url resolver activé.

**Comment by johngf** [comment]
j'ai eu une fois une erreur de ce type avec zt a cause de  dl protect mais ça n'empeche pas d'avoir le liens donc ...

**Comment by Antho59380** [comment]
Oui pour l'erreur ernno 7 c'est uniquement que je lance une recherche mais les liens s'affichent et fonctionnent. Par contre pour erreur connexion SSL CERTIFICATE plus rien ne fonctionnait donc j'ai desinstallé kodi et ré installait et ça s'est mis à refonctionner.

**Comment by mnett0** [comment]
errno 111 lorsque adAway est activé

**Comment by jesusisback66** [comment]
Non si tu est sur Android et que tu est rooté il y a une application qui
s'appelle Adaway il faut juste la désactiver et perso cela m'a fait
disparaître l'erreur eerno 111

**Comment by Antho59380** [comment]
Ah non je ne suis pas rooté et je n'ai pas adway

**Comment by Antho59380** [comment]
Alors pour l'erreur SSL il semblerait que ce soit dû à la ram.
Je m'explique. Sur kodi j'ai vu que la température ne s'affichait pas et que donc la box était un peu en difficulté. 
Je suis allé sur la seule appli qui tournait en arrière plan à savoir ATLAS PRO j'ai forcé l'arrêt et retour sur Vstream qui ne m'affichait plus l'erreur SSL CERTIFICATE. 
J'ai toujours l'erreur ernno 7 mais ça ne gêne pas l'utilisation de Vstream. 
J'essaierai quand même de mettre le log que vous voyez s'il y a quelque chose d'anormal.

**Comment by perive** [comment]
Chez moi, lors de la recherche, l'erreur errno7 se produit à cause de Tv-streaming.

**Comment by johngf** [comment]
si vous avez l'erreur SSL CERTIFICATE
c'est que la version python fournis avec android ne gere pas le vrai ssl
donc mise a jour kodi et android en espérant que la bonne version de python y soit inclu (voir le changelog d'android)

**Comment by razorex** [comment]
Chez moi aussi çà arrive après une longue veille. Je reboot ma box et c'est reparti. çà dois venir d'android pas de vStream.
