### ISSUE TITLE
Impossible d'installer la version 0.6.2

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#2105]
Bonjour 

Je n'arrive pas à mettre à jour Vstream avec l'erreur suivante :
ERROR: CAddonInstallJob[plugin.video.vstream]: La dépendance de script.module.python.requests version 2.16.0 n'a pas pu être satisfaite.

J'ai bien lu https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1868
Mais comme je suis sous Kodi 17.6 : Il ne devrait pas y avoir de problème.
J'utilise un RPI3 sous OSMC.

Merci d'avance pour votre aide.

**Comment by johngf** [comment]
le plus simple install l'application youtube et ça fonctionnera

**Comment by canopre** [comment]
merci beaucoup pour ton aide rapide.

J'ai bien Youtube installé.
J'ai installé le script request fournis.
Et pourtant j'ai toujours la même erreur quand j'essaie de mettre à jour Vstream.

Je n'ose pas désinstaller la version actuelle qui fonctionne pour faire une nouvelle installation qui risque de ne pas marcher non plus :(

**Comment by LordVenom** [comment]
Bonjour,

Tu aurais pas une installation bien pourris avec superrepo et plein d'addon installer ?

**Comment by canopre** [comment]
Hello
Ben je sais pas à partir de combien d'addons on a une installation "bien pourrie" mais j'ai 6 addons vidéos installés.

**Comment by LordVenom** [comment]
Ha j'ai rien dit alors.Mais comme la dit @johngf  cette dépendance ne vient pas de vStream.

**Comment by canopre** [comment]
Si je suis le seul à signaler le pb c'est de toute manière que ça vient de chez moi.
J'ai fait une installe un peu brutale de Vstream : copie de la version 6.2 dans le dossier addons de kodi et tout est rentré dans l'ordre...pour l'instant.
En espérant que j'ai pas le même problème tous les mois :)
En vous remerciant encore une fois pour votre aide rapide.

**Comment by LordVenom** [comment]
Pour moi script.module.requests passe de la v2.12.4 à la v2.18.4 donc ta version n'existe pas.

Je vais quand même mettre requests dans les import de vstream mais bon puisqu'on import youtube qui import request c'est un peux le serpent qui se mord la queue.

**Comment by LordVenom** [comment]
Tu peux chercher dans tes .py quel et l'addon qui a cette ligne

<import addon="script.module.requests" version="2.16.0"/>

Au moins tu seras qui bug.

**Comment by canopre** [comment]
Je voulais parler de la 6.2 de vstream : c'est vstream que je n'arrive pas à mettre à jour (à cause de requests)

**Comment by johngf** [comment]
en faite @canopre vstream installe youtube meme si il n'en a plus besoin et youtube installe requests 
donc je me demande comment tu as fait pour installer youtube sans request ça doit etre une dependance optionelle ou une autre version de request qui bug

**Comment by LordVenom** [comment]
J'ai compris mais y a pas d'import de request dans vstream.Il est pas dans les addons nécessaire a l'instalation. y a youtube, le repo vstream, simplejson c'est tout bon plus maintenant j'ai ajouter requests ou cas ou.

**Comment by johngf** [comment]
[essaie celle ci bonne version](https://mirrors.kodi.tv/addons/gotham/script.module.requests/script.module.requests-2.12.4.zip)

**Comment by LordVenom** [comment]
Normalement c'est le même mais Gotham c'est kodi 13. mieux prendre dans Jarvis 16.0 ou Krypton 17

https://mirrors.kodi.tv/addons/ puis tu choisis ta version /
