### ISSUE TITLE
Errno 111

### ISSUE THREAD

**Issue by mnett0** [Kodi-vStream/venom-xbmc-addons#2109]
Bonjour, 
Une erreur 111 apparait sur l'add-on lorsque AdAway est activé, une fois désactivé plus de soucis. ça rend vStream inutilisable enfin on ne peut pas lire les vidéos mais sinon on peut toujours naviguer. 

Voici mon log : 
https://slexy.org/view/s20yEAhm8U

**Comment by johngf** [comment]
bah alors le soucis ne viens pas de vstream mais de adaway 
d'ailleurs comment un antipub arrive a bloqué kodi ?

**Comment by mnett0** [comment]
AdAway bloque une longue liste d'hostnames mais le truc c'est de savoir quel sont les hostnames bloqués, qui empêchent le bon fonctionnement de vStream, je vais essayer avec un autre add-ons

**Comment by mnett0** [comment]
Même soucis avec un add-ons de streaming mais pas d'erreur 111, il me reste plus qu' a savoir quels sont les hostnames a mettre en liste blanche

**Comment by LordVenom** [comment]
Disponible dans vStream : 

Sites : https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/plugin.video.vstream/resources/sites

Host : https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/plugin.video.vstream/resources/hosters

**Comment by johngf** [comment]
le plus simple créer un raccourci bureau avec comme fonction de désactivé ou activé adaway (c'est possible sur android)
avant d'ouvrir kodi tu désactive et quittant kodi tu le ré-active
