### ISSUE TITLE
Planet streaming et serie streaming HS

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#2110]
En mettant a jour vstream a partirde github donc derniere mise a jour, ces 2 sites ne s'ouvre pas au niveau des sous catégories ou des series

**Comment by johngf** [comment]
comment tu as fait la mise a jour  "a partir de github"? parce que les deux site fonctionne.

**Comment by AizenKnower** [comment]
J'ai  pour habitude de télécharger le github en entier et dezipper le dossier plugin vstream et copier coller dans le dossier addon de kodi 

Jusque la ça marche impeccable pour avoir les derniers mise a jour de vstream notamment les fixes de iptv mais la les 2 sites ne marche pas

Mais jai re copier coller l ancien dossier de vstream telecharger et çà marche (il date de dimanche) mais celui d aujourdui non.

J'ai toujours la version 0.6.2 mais avec les mises ajour quotidienne du site donc hier la maj marche mais pas celui d'aujourd'hui

**Comment by LordVenom** [comment]
Bonjour, @AizenKnower 

Merci pour le retour, mais la version bêta et faite pour les bidouilleurs, programmeurs qui fond des retours de log ou mieux encore les modifications eux même. en plus je suis entrain de faire des modifs au coeur et comme dab ça plante tous le reste XD. Tous ça pour dire qu'il faut éviter la bêta si tu ne compte pas mettre les mains dans le camboui.

**Comment by AizenKnower** [comment]
Disons que jusque là y a pas eu de souci et je suis intéressé par la fonction iptv donc j'ai du petit a jour en beta

Le probleme je crois que cest les liens Netu ca dit "introuvable"

**Comment by johngf** [comment]
ne tu viens d'etre mis a jours.

**Comment by AizenKnower** [comment]
J'ai pas compris ton message mais bon les liens netu ne fonctionne pas peu importe les versions ou les appareils que j'ai  (smartphone  box tv ou tablet)
Donc ya un bug sur vstream car les liens netu marche sur leur site
