### ISSUE TITLE
M$ le Mal ?

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2111]
Comme je vient de le découvrir Github vas être racheter par M$. Alors a voir si le git sera déplacer ou pas ou et comment pour le moment j'ai pas trop de réponse un espace gratuit avec autant de liberter ça cours pas le net XD.

https://www.lemonde.fr/pixels/article/2018/06/04/le-rachat-de-github-par-microsoft-suscite-des-inquietudes-chez-les-developpeurs_5309561_4408996.html

**Comment by Arias800** [comment]
Faut voir ce qu'il vont faire d'ailleurs github appartenait déjà à un boîte privée de mémoire ^^

**Comment by lebigboss** [comment]
Ouai, faut déjà ce préparer à être ailleurs, parce qu'avec des boîtes comme Microsoft qui veulent faire du profit, on sait pas trop si ils vont pas essayer de rendre tout ça payant.

**Comment by TmpName** [comment]
Moi je pense pas, sinon il va y avoir une migration massive, suffira de suivre le mouvement.

**Comment by Nux007** [comment]
Perso, je pense bien que je vais aller voir du coté de GitLab ...

**Comment by vic1997** [comment]
Ca va rien changer du tout. Et pour info Gitlab est sur les serveurs d'Amazon, donc c'est la même chose !

**Comment by TmpName** [comment]
Faut pas trop diaboliser la bete, microsoft est moins esprit open source que les autres, mais niveau developpement il est largement au dessus des autres. Que ce soit au niveau des outils qu'il propose (gratuitement), de sa communaute (il y a plus de github de microsoft que de google lui meme), de leur services (code une appli c++ en directX, puis en SDL, ..., et pleure).

C'est pas apple, si il peut monayer quelque chose il ne va pas s'en priver, mais je ne le vois pas aller contre l'esprit de developement, au contraire il va avoir la un moyen se booster.

**Comment by LordVenom** [comment]
Je sais pas, j'avoue je suis amoureux de leur visual studio code et de leur boite email mais c'est tout il ont quand même beaucoup merder, zune, nokia, bing, ect.. (sérieux qui met des images du jour dans un moteur de recherche XD)

Mais bon, temps que rien ne change sur Github peux n’importe qui le possède quand a Gitlab (Beurk) .
