### ISSUE TITLE
Proposition d'une potentiel solution a recaptcha

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2112]
Alors voila ça fait un petit moment que je réfléchit a comment faire pour laisser l'utilisateur résoudre le recaptcha et repasser la main a vstream une fois celui-ci résolu et j'ai enfin trouvez bref voila un demo : https://youtu.be/9FdvTXVGI7I (ne fonctionne que pour uptobox pour le moment)

**Comment by johngf** [comment]
c'est bien pour ceux qui ont un navigateur sur leur machine et qui sont motivé perso j'aurai la flemme je fait tout a la télécommande.
edit : si jamais ça ne fonctionne pas avec android ou 1 fichier les utilisateurs vont ouvrir bcp d'issue le pourquoi du comment etc...

**Comment by Arias800** [comment]
Yep c'est un addon chrome que j'ai modifier pour le play with kodi c'est pour ca que pour le moment ca ne marche qu'avec uptobox ^^

**Comment by lebigboss** [comment]
Bravo pour le taff
ça peut intéressé des gens, moi j'utilise une box android :(

**Comment by Arias800** [comment]
Après si j'arrive à le mettre sur Android pourquoi mais pour le moment ce n'est pas possible ^^

**Comment by Arias800** [comment]
Alors Chrome launcher a été améliorer et apparament il est compatiblele Android faut juste que je trouve comment ajouter l'addon à Chrome et que je finit les modif et ça pourrai peut être le faire ^^

**Comment by Arias800** [comment]
Pour ceux qui veulent essayer voila les fichier nécessaire https://github.com/Arias800/Vstream-extreme-down
