### ISSUE TITLE
Question: comment jouer m3u8 sur Kodi

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2116]
Bonjour,

J'ai besoin d'aide sur m3u8 (IPTV) et je ne sais pas ou je dois poster.
Toutes mes excuses si j'ai poste dans le mauvais endroit.

J'essaye d'apprendre a coder en utilisant le site racacaxtv.ga et en regardant l'expertise du code de VStream, je pense que vous pouvez m'aider.

J'utilise Kodi xbmcPlugin pour jouer le lien m3u8:
xbmcplugin.setResolvedUrl(handle=self.plugin, succeeded=True, listitem=item)

Pour la chaine "France 2", je peux trouver quelque m3u8 liens:

"https://opus_cf/allfrtvstrm/tkn/francetv2017/ZGHlBQD3AQVmZP0kAGV4AGR3ZQZjYJL0ZQx4AmuxLwyuZQR0LwqwZwH3MQHjZwt1LmRjZGOwYGquZQL4AzD1Z2EyZJL4LGL5Z2HkZJLlMTIvZJAxMGEy/France_2/France_2-audio_20000=65600-video=1404000.m3u8" 

marche tres bien mais celui-ci ne marche pas:

"https://opus_cf/allfrtvstrm/tkn/wil/ZGHlBQD3AQVmZP0kAGV4AGR3ZQZjYJL0ZQx4AmuxLwyuZQR0LwqwZwH3MQHjZwt1LmRjZGOwYGquZQL4AzD1Z2EyZJL4LGL5Z2HkZJLlMTIvZJAxMGEy/france_2_hd/32.m3u8" 

J'ai continue avec ce lien et j'ai un autre m3u8 qui ne marche pas:

"https://opus_cf/allfrtvstrm/tkn/wil/ZGHlBQD3AGRlAl0kAGV4AGR3BGV3YGD2ZwIyMwRmA2SuZQR1AzMzBJAyZJIvMGtmMGIuBQRlYGquZQL4AzD1Z2EyZJL4LGL5Z2HkZJLlMTIvZJAxMGEy/62.65.140.229:80/session/3552750c-fba4-11e6-9eab-005056bc1a52/nvnv5a/2/2028/3305000/index.m3u8"

Est ce quelqu'un qui a un peu de temps pout m'aider a trouver une solution ?

Merci en avance de votre aide

**Comment by Arias800** [comment]
C'est bizarre les fichier sont vide et j'ai commencer a jeter un œil a ce site pour le mettre dans vstream mais je suis tomber sur une playlist dans un format que je connais pas ^^

**Comment by sviet2k** [comment]
Pour avoir le content, il faut que le header du Request a 'Referer' = 'https;//racacaxtv.ga'

C'est quoi le playlist? :)

**Comment by Arias800** [comment]
C'est les liens utiliser par racacax donc je n'y touche pas car il fait du super taf . Ensuite je parle de playlist car dans les fichier m3u8 il y a plusieurs chose a lire donc c'est une playlist ^^

**Comment by Arias800** [comment]
Ensuite voila le fichier qui s'occupe de la partit itpv de vstream donc tu peux y jeter un oeil et me demander si il y a des chose que tu comprends pas https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/freebox.py

**Comment by sviet2k** [comment]
Merci @Arias800  pour l'info.
J'ai regarde le code et malheureusement je n'ai pas trouve la solution. 
Dans le code, on utilise xbmc.player ou f4mtester pour jouer le URL. 
Je fais la meme chose mais ca ne marche pas :(

Encore merci pour ton aide @Arias800

**Comment by KiliK150** [comment]
Je vois que ça parle de racacax et iptv par ici ^^ ,
 et justement le forum-racacax , l'utilisateur z3r0z0n3 a créé au mois de mars un  topic
[https://forum-racacax.ga/viewtopic.php?f=55&t=2623&sid=08ef005b627ca0c9ea375ef819e1b7f9](url) où il propose une liste IPTV FR qui fonctionne avec livestreampro. Les liens sont plutôt lent au chargement mais fonctionnent bien au final . 

Quelqu'un pourrait le contacter pour voir s'il serait d'accord pour intégré son projet à celui de l'IPTV Vsteam ? non ?

Et encore merci pour tout ce boulot

**Comment by Arias800** [comment]
Je m'en occupe ^^

**Comment by Arias800** [comment]
Pour utiliser ce site il faut passer par livestreampro car trop complexe a ajouter a vstream (il faut décoder un url avec des module supplémentaire)
