### ISSUE TITLE
Mise a jour

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2118]
@TmpName  ne fait pas de mise a jour auto stp trop de modif dans le code.

**Comment by Arias800** [comment]
Tu a peur d'avoir tout casser ? :p

**Comment by LordVenom** [comment]
Ben non ça tourne chez moi XD, 

J'ai crée des nouvelles function logiquement c'est que le coeur qui les utilise mais comme ont a deja eux des bug a cause de ça mieux vaut prévoir.

Note: je pense bloquer les mise a jour host & site à la dernière version officiel en cour.

**Comment by TmpName** [comment]
ok c'est note, mais tu touches pas aux fichiers sites et hosts ca devrait passer ?

**Comment by razorex** [comment]
Je voulais proposer un site avec kvid en hoster, je peux le mettre?????? remettre aussi kvid dans les hosterr??

**Comment by johngf** [comment]
@razorex oui c'est la maj auto des 3 jours qui est repoussé

**Comment by johngf** [comment]
d'ailleur kvid je l'avait mis dans trash parce qu'il n'était que sur mega stream 
c'est peut etre les anciens proprio de mega qui ont crée le site

**Comment by LordVenom** [comment]
util.VSlog passe de xbmc.LOGNOTICE à xbmc.LOGDEBUG

LOGNOTICE inscript dans le log même quand le mode debug n'est pas activer.

**Comment by johngf** [comment]
ça veut dire qu'on est obligé d'utiliser le mode debug >> que je n'utilise jamais
pour écrire dans le log?

**Comment by TmpName** [comment]
Yep, pareil pour moi, j'active jamais le mode debug, mais je me sert de de Vslog pour le debug ...

**Comment by TmpName** [comment]
Yep, parfait ^^.
Dsl de faire le boulet, mais franchement le mode debug de kodi est trop lourd pour moi.

**Comment by LordVenom** [comment]
Si j'en parle c'est bien pour avoir les retours, pas de soucis 4 ligne de code XD

**Comment by LordVenom** [comment]
Je me demande c'est pas mieux si on hérite les class xbmcaddon.addon plutot que de les rapelles a chaque foix ? exemple 

from resources.lib.common import addon

addons = addon()

print addons.lang(30305)

print addons.lang(30305)

print addons.lang(30305)

J'ai tester l'init et bien passe 1 seul foix contre a chaque foix avec xbmcaddon.Addon('plugin.video.vstream').getLocalizedString(lang)

**Comment by TmpName** [comment]
Ha yep, suis pour, mais pour rappel on a deja eu la meme discution pour la fonction cConfig(), qui est (etait) tres lourde a chaque appel.
Y a des fonctions python qui mesure le "temps d'execution", pour savoir si c'est utile, mais pour moi soit c'est benef, soit y a rien a perdre.

**Comment by LordVenom** [comment]
Le soucis de cConfig c'est que je le rappelle à chaque alors qu'il y a pas besoin.En plus il utilise des function xbmc.gui, xbmc plus xbmc.addon bref un bordel j'aimerais ranger un peux éviter de multiplier les imports.

le plus de l'héritage normalement ont peux utiliser les fonctions de xmbc.addon et celle de (common.addon) avec les même appelle j'ai pas encore tous tester mais ça semple fonctionner.

**Comment by LordVenom** [comment]
Correction pour pouvoir appeler les fonctions avec un autre addon opensetting par exemple.

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/comaddon.py

J'ai découvert un nouveau jouer la XD, dsl ça vas bousculer les chaumières.

**Comment by LordVenom** [comment]
Bon j'ai rassemble xbmcaddon, xbmcgui, xbmc de toute facon c'est rare qu'on apelle l'un sans les autres

Ont peux donc hériter xbmcaddon toutes class
xbmcgui juste dialog pour le moment.c'est des class séparer.
xbmc ben c'est pas des class.

tout et écrit dans le fichier.

**Comment by TmpName** [comment]
J'ai pas encore teste, mais en tout cas c'est propre.

**Comment by LordVenom** [comment]
Je fait les gros fichier et si tout ce passe bien la mise a jour mensuel seras dans les temps, le faite de rendre compatible cConfig() c'etait vraiment chiant  mais y a plus de 256 apelles alors j'ai la flemme XD.

**Comment by LordVenom** [comment]
Autre nouveauter sur le Github. merci @Arias800  une mini popup permet d'afficher les info pour contribuer et dans la fouler j'ai modifier les templates des issues, si vous avez des idées de catégorie à jouter ou des corrections a faire, faite les ou dites moi.

**Comment by LordVenom** [comment]
Alors je cherche à modifier le chemin des fichiers pour integrer le system de chemin special:// de Kodi 
les plus :
normalement (difficile de trouver une doc qui parle des accents)
le system fonction sans translate path sans decode si ont utile xbmcvfs
Je vire les appelles a xbmc.addon pour avoir le path c'est ecrit en DUR c'est donc supert leger.

Les moins
xbmcvfs et limiter, il faut refaire pas mal de code.

**Comment by TmpName** [comment]
La je commence a flipper, tu vas pas toucher au systeme unicode des chemins de fichiers ?

**Comment by LordVenom** [comment]
Hé tu as raison mais ça vas bien ce passer au pire j'ai commenter tous les anciennes direction.

**Comment by LordVenom** [comment]
Quelqu'un c'est ceux veut dire ça :

`WARNING: CPythonInvoker(34, /home/lordvenom/.kodi/addons/plugin.video.vstream/default.py): the python script "/home/lordvenom/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE`

Il est gentil Kodi mais nettoyer des class ça me parle pas.

Note: c'est pas la traduction Française que je demande XD

**Comment by LordVenom** [comment]
Ok j'ai trouver c'est un soucis de Kodi problème de comptage des sous-class pff normal quoi.

**Comment by LordVenom** [comment]
On peux virer le fond qui change selon le menu ? sur mon theme on voie pas la différence et les icons ou le texte ça suffis non ?

**Comment by LordVenom** [comment]
Bon ça commance a prendre forme la, vous avez vue une différence de rapiditer ou c'est juste moi ?

**Comment by LordVenom** [comment]
non elle ne l'ai pas, l'activation des metas diminue toujours beaucoup le temps de charge et l’anulation via la popup progress c'est toujours utile.

**Comment by LordVenom** [comment]
hep hâte de tester sur mon HTCP

**Comment by Arias800** [comment]
Après c'est vraie que j'avais pas les metadonnes activer mais bon la différence ce ressent je trouve ^^

**Comment by LordVenom** [comment]
Pour les metas le temp qu'il mette en cache puis ça devient quand même asser rapide.

**Comment by LordVenom** [comment]
@TmpName tu as les permissions pour creer une release ?

**Comment by TmpName** [comment]
Je pense que oui, le boutton "draft release" fonctionne.

**Comment by LordVenom** [comment]
Ok gros changement en perceptive (oui encore un) , toujours en cours de test si ça fonctionne ça vas nous simplifier la vie (enfin les manip sur github juste XD).

**Comment by TmpName** [comment]
Ha c'est bien ca, c'est ou ?

**Comment by LordVenom** [comment]
Oui je me suis dit que c'etait bien aussi d'avoir une meilleur vue sur notre travail. Quand tu fait une mise a jour tu as c'est info avant de pouvoir finir la dite mise à jour.
