### ISSUE TITLE
Changement kodi ou vstream

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#2119]
Je fait part d'un possible changement sur kodi qui rend l affichage de vstream incorrect 
C'est sur les derniers version beta de kodi depuis le 12 juin (j'ai cru a un bug de kodi mais mes apk du 12 13 14 juin donne le meme souci donc possible que cela soit problématique pour vstream quand Kodi 18 sortira de sa phase beta) 

Le souci est que lorsqu'on atteint la liste des sources pour y cliquer,  le contenu de la source est affiche a la suite des sources et non plus seul 
Ex si je clique sur series-streamingHD son contenu s'affiche en dessous de zone-streaming

Je sais bien que c'est pas un bug de vstream mais juste pour prevenir que kodi aussi change leur facon de faire qui risque de poser problème pour vstream a l avenir.
Donc c'est juste une info et donc la derniere beta qui posse pas de probleme est celle du 11juin (je met souvent a jour pour voir si des améliorations au niveau iptv car la lecture ne reste pas permantent chez moi que ce soit addon intégré ou livestreampro, la lecture arrive vite au boutet s arrete)

**Comment by LordVenom** [comment]
Une astuce pour la lecture tv c'est de mettre la chaine en playlist et de mettre la playlist sur répéter quand la chaine coupe elle reprend direct. c'est ceux que fait VLC mais c'est invisible car le lecteur de VLC et un peux mieux coder XD.

Pour Kodi 18 j'ai envie de dire Pffffff. Si l'erreur vient de ce que je pense ça vas faire mal.

**Comment by Arias800** [comment]
Après vstream répète aussi tout seul le flux mais c'est pas compatible avec f4mTester donc je sais pas trop quoi choisir x)

**Comment by Arias800** [comment]
Je viens de voir passer un pull request sur le github de kodi qui corrige le problème il me semble ^^

**Comment by AizenKnower** [comment]
@lordvenom si je comprend bien je met la liste de chaine en playlist et je repete la playlist ou juste la chaine? Comment repeter la chaine ou la playlist c'est par une fonction de kodi (quel addon) ou par une fonction vstream (fonction tv/radio)

Pour vlc aussi faut cliquer sur LOOP pour qu'il repete la chaine. J'ai essayé de mettre vlc en tant aue lecture externe pour kodi mais il n'est pas dans la liste il propose que mxplayer et je sais pas c'est lequel car playstore en a plein avec ce nom.


@ariase800 la version beta d'origine présente le meme probleme donc le pull request n a pas été pris en compte donc non corrigé.

Avec l iptv d Ariase800 (la source tv dailyiptv liste du 15juin) et le kodi18 beta du 11juin ya pas de coupure de lecture (chaine game one) sur une tablette tf300t 7.1.2 depuis presque 1heure minute (esperons que cela dure et que sur ma box tv cela soit aussi sans coupure mais c'est bien partie pour l'instant.

Esperons que ce problème s'affichage des sources soit résolu dans un un prochain maj de kodi. C'était juste pour signaler  le problème persiste depuis 3jours donc esperons que c'est pas définitif car je sais pas si pour vstream c'est un souci ou un début de souci plus gros a l'avenir si kodi change

**Comment by LordVenom** [comment]
Autant pour moi , les chaines tv ne vont pas en playlist le film et serie oui (je sais même pas comment) a voir si c'est possible pour la tv aucune idée.

**Comment by johngf** [comment]
@AizenKnower quand on veut un systeme stable on installe pas de béta quelque soit le programme ou os
parce que la tu signale des bugs qui ça tombe ne seront plus dans kodi 18 version finale

**Comment by Arias800** [comment]
Normalement f4mTester permets d'utiliser le cache de kodi donc arriver a la fin si le liens ferme pas l’addon mets en cache

**Comment by AizenKnower** [comment]
@ jonhgf ta contribution est pas productif et surtout fausse car ce problème  d'iptv n est pas un probleme de beta mais de kodi.
Ce problème de lecture est connu depuis belle lurette bien avant kodi 18 ou les beta.
Tu pense pas que si le problème etait resolu par une version stable non beta j'aurai deja trouvé ou pensé ? C'est meme la 1er chose que j'ai faite en installant differente version stable depuis kosi 15 16 et 17 et ca n'as jamais resolu le problème 

D'ailleurs kodi le precise dans l addon iptv que ce cette addon est experiemental donc quelque soit la version l addon iptv ne fonctionne pas correctement 

Voila donc essaie de trouver une solution plutot que de mettre en cause l origine du problème sans connaitre son origine mdr.

@lordvenom je pense que le souci est peut etre l absence de "repeter la playlist ou chaine comme  vlc" car beaucoup de site offrant des playlists d iptv conseil de "looper" la lecture pour qu'elle stream en continue or sur kodi on ne peut pas looper

Je sais que tout ca est possible avec easy advanced settings mais il est plus compatible depuis kodi 18. Il permet de justement faire des reglages pour les iptv pvr et le playback et meme changer le lecteur externe (je cherche un tuto pour le paramétrer car ca demande des "value" et pas le nom ou chemin de l addon/application externe)

(Nb: apparemment mon essai de tout  a l heure a montrer qur cela depend des chaine et que ca bloque quand c des chaine hd bref le meme souci)

@Ariase800 est ce que une fenetre s'ouvre avec f4mtester avant le stream de la chaine? Comment etes sur qu'il se lance car moi c'est 

Er est ce que f4mproxy est la meme chose?

**Comment by Arias800** [comment]
F4mProxy ce n'est pas la même chose que f4mTester . Les liens qui sont en ts coupe et c'est normal du coup je les convertit automatiquement en liens f4mTester ^^ . Pour savoir si les liens utilise f4mTester c'est facile si il y a une fenêtre "Loading proxy" qui apparait au lancement des liens c'est que c'est un liens f4mTester

**Comment by AizenKnower** [comment]
Ok merci Arias800 je confirme que f4mtester est bien installé et loading proxy qui apparait. As tu parametrer ce f4mtester au niveau bitrate.

Enfin bref oublions  ce sujet de stream iptv je pense que le souci pourrai venir des liens iptv car ce matin gameone a durer 1hr sans coupure donc peut etre je devrais m abonner a un iptv pour voir si la coupure est pas du au serveur surchargée comme la spécifié lordvenom y a quelque semaine. 

Merci quand meme de votre aide

**Comment by johngf** [comment]
@AizenKnower ma contribution se base sur la première partie de ton message a savoir ''Le souci est que lorsqu'on atteint la liste des sources pour y cliquer, le contenu de la source est affiche a la suite des sources et non plus seul'' qui n'a rien a voir avec l'iptv qui d'après vos messages ne fonctionnera jamais correctement au final.
sinon vu que vlc sait "looper" tu en as parlé aussi pourquoi pas je n'en sais rien surement possible [ici](https://betanews.com/2017/06/16/how-to-play-kodi-streams-in-vlc-media-player/)

**Comment by AizenKnower** [comment]
@arias800 autant pour moi  pour le souci d affichage désolé 
Et pour vlc je vois que les grand esprits se rencontre car je viens juste de lire ceci https://kodi.wiki/view/External_players qui parle justement de ce fichier xml donc je vais tenter cette solution

Merci

**Comment by Arias800** [comment]
Je reouvre l'issue car l'alpha 2 de kodi 18 est sortie hier et il reste encore le bug d'affichage donc a mon avis il ne sont pas près de le corriger ..
![capture](https://user-images.githubusercontent.com/24809312/41807297-5de678a6-76cd-11e8-8d50-59e541a6afeb.PNG)

**Comment by LordVenom** [comment]
Je m’inquiéterais pas avant la Bêta.

**Comment by TmpName** [comment]
Moi je suis encore sous confluence, donc je vois meme pas ce que c'est ^^.

**Comment by Arias800** [comment]
En faite toute les menu s'ouvre les un à la suite des autre ^^

**Comment by TmpName** [comment]
Et c'est ou que tu utilises du code exotiques ? Apres comme dit @LordVenom avant la 2/3eme RC, pas la peine de tester leur version, non pas que la suivante sera mieux, mais elle aura encore plus de bug.

**Comment by Arias800** [comment]
Tu n'a pas si tor que ça mais c'est parce qu'il font beaucoup de modif lié à L'IPTV que j'essaie leur version de test ^^

**Comment by TmpName** [comment]
Tu as dit utliser des fonctions d'affichage de kodi car celle de vstream etaient trop lente.

**Comment by Arias800** [comment]
Ah oui pour afficher les chaines des playlist 
![capture](https://user-images.githubusercontent.com/24809312/41817439-7f2740f8-779b-11e8-95fe-279b6c566840.PNG)

**Comment by LordVenom** [comment]
XD je suis pas tomber dessus encore mais non.

**Comment by LordVenom** [comment]
1 truc tes gentils toi XD

**Comment by TmpName** [comment]
Lol, non suis conciliant. Bon ok, le code commence a etre crade mais que @Arias800 ait trouve une methode d'affichage plus rapide, ca peut valoir le coup, surtout que la derniere en date a bien ete testee et je suis sur de son optimisation.
A voir si il suffit de desactiver une partie du code existant (quitte a rajouter une option) car ok le code de Vstream est plus lourd que des fonctions de base, ou tout refaire.

**Comment by Arias800** [comment]
Le bug d'affichage est corriger chez moi avec ça : https://pastebin.com/VwxEy1Nz

**Comment by Arias800** [comment]
Correction pour le bug d'affichage de kodi 18 : https://pastebin.com/VwxEy1Nz

**Comment by LordVenom** [comment]
Filtre les resultats.

**Comment by TmpName** [comment]
Desactiver, pas virer, ca sert tjours.
Sinon pr comparer 2 fichiers j utilise ht tps://ww w.diffchecker.com/

**Comment by Arias800** [comment]
Bon bah tant pis au moins ceux qui veulent savent que ça marche en temps que solution de secours en attendant une meilleur solution si le problème perdure dans une version plus stable

**Comment by TmpName** [comment]
Je retrouve plus l'issue, mais y a vraiment eu du monde dessus.
Avant xbmcplugin.addDirectoryItem etait apellé a chaque liens et maintenant tout est mit dans une liste, et la fonction n'est appelle plus qu'une fois, les differences de temps d'affichage sont visibles a l'oeuil nu.
Y a peut etre une correction a faire mais pas de retour arrierre.

**Comment by Arias800** [comment]
Je comprends et pas la peine de préciser pourquoi si tu est contre c'est  qu'il y a une  raison je cherchait juste à faire disparaître le bug vu que j'utilise Kodi 18 pour voir les modif qu'il font pour L'IPTV ^^

**Comment by LordVenom** [comment]
Reste que tu doit filtrer tes iptv 3000 entrer c'est impossible a gerer pour les petites machine regarde du cote de lamba pour filtrer doit y a avoir des exemples dans le code de vStream.

**Comment by LordVenom** [comment]
y a des gens qui ont vstream qui vont regarder autre chose que les chaines FR ? moi les anglais tu sais... lol

**Comment by Arias800** [comment]
Bah c'est possible apres bon au moins ça laisse le choix quoi x)

**Comment by Arias800** [comment]
Bon je propose autre chose pour corriger le bug d'affichage c'est l'ajout de self.listing = [] a la ligne 576 ^^

**Comment by Arias800** [comment]
Pour corriger le bug d'affichage je propose l'ajout de del self.listing [:] a la ligne 575 de gui.py ^^

**Comment by TmpName** [comment]
Ben la je vois ce que ca peut chnager, apres la ligne 557, cette liste ne sert plus, et peut etre remise a zero juste apres.

**Comment by Arias800** [comment]
Kodi est bizarre donc bon , apres la question c'est est-ce que je peux mettre cette modif dans la bêta (après avoir fait plus de teste) ?

**Comment by LordVenom** [comment]
Si tu est sur de toi tu as juste a commenter vite fait et oui tu peux soumettre.

exemple : 

```
#bug affichage Kodi 18
mon code
```

**Comment by Arias800** [comment]
Avant je ferai des test bien sûr ^^

**Comment by Arias800** [comment]
J'ai pas vu de problème donc je l'ai soumis

**Comment by TmpName** [comment]
Moi je vois pas ce que ca pourrait faire comme prb, je ne comprend meme pas a quoi ca sert ^^, c'est magique.

**Comment by Arias800** [comment]
En gros la liste utiliser pour l'affichage ne se vidait pas donc je la vide ^^

**Comment by TmpName** [comment]
Dans ce cas c'est plutot del var au lieu de del var[:] mais j'arrive pas a comprendre pkoi ca gene kodi, a cause des 3000 entrees peut etre, mais franchement j'ai ai deja fais pire.

**Comment by Arias800** [comment]
parce qu'il on fait de modif bizarre par exemple y a une autre modif qui a été faite de leur coter qui fait que si tu ne mets pas cConfig().finishDialog(dialog) tu est bon a fermer et reouvrir Kodi car impossible de fermer la boite de dialogue ^^

**Comment by TmpName** [comment]
Ha yep je viens de comprendre, la commande del n'efface que les index designes et en mettant juste ':' ca efface du premier au dernier.
