### ISSUE TITLE
UPTOBOX Compte premium

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#2120]
Bonjour a tous , j'ai un compte premium chez UPTOBOX depuis 2 ans  , après parametrage de mon compte UPTOBOX dans VSTREAM  ,  quand je choisi un film l'hautentification réussie , mais le film ne se charge pas , j'ai la fleche qui tourne , avec le message : en cours , que faire ?

**Comment by LordVenom** [comment]
Bonjour, 
Je fini par te répondre par politesse car malheureusement je ne peux peux rien pour ce bug DSL.

**Comment by ktm520** [comment]
Bonjour , merci pour la réponse .

Tant pis pour moi .
