### ISSUE TITLE
Tv Replay

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#2121]
Bonjour a tous , existe il une extension pour voir la TV en replay sur VSTREAM ?

**Comment by ktm520** [comment]
J'ai confondu avec Kodi , dans le temps j'utilisait TVPLUZZ sur ma TV SAMSUNG , freplay doit etre l'équivalent , je vais tester .

**Comment by ktm520** [comment]
J'ai confondu avec Kodi , dans le temps j'utilisait TVPLUZZ sur ma TV SAMSUNG , freplay doit etre l'équivalent , je vais tester .
MERCI pour la réponse .

**Comment by LordVenom** [comment]
Y a un menu TV replay dans vStream avec 6 source dispo.

**Comment by ktm520** [comment]
Merci .
