### ISSUE TITLE
up2strm reagit bizarrement chez moi

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2122]
Bon alors c'est peut etre que chez moi , mais voila, en gratuit sans authentification, quand je lance une video avec le hoster up2strm
1- kodi freeze (pendant au moins 40s, mais ca c'est un reglage)
2- dans les logs (2fois) >ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https:...
3- puis la video demarre normallement

```
17:13:09.000 T:152  NOTICE: 	[PLUGIN] Vstream: Player use setResolvedUrl() method
17:13:29.000 T:152  NOTICE: 	[PLUGIN] Vstream: player stoped
17:13:29.023 T:152  NOTICE: 	[PLUGIN] Vstream: Closing player
17:13:29.028 T:152  NOTICE: 	[PLUGIN] Vstream: Table initialized
17:14:09.030 T:2312   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https
17:14:09.070 T:2312  NOTICE: VideoPlayer: Opening: https
17:14:09.070 T:2312 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:15:05.295 T:2312   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https
```

Autre truc bizarre > player stopped, closing player, et ca bugge avant meme NOTICE: VideoPlayer: Opening

**Comment by TmpName** [comment]
Bon pour la seconde remarque j'ai trouve pkoi.
Vstream attend pendant 20s que le lecteur demarre, si pas de demarrage il referme le lecteur.

**Comment by Arias800** [comment]
Le freeze j'ai la même chose donc c'est quoi comme réglage ?

**Comment by LordVenom** [comment]
un petit xbmc.sleep entre la réponse et le lecteur ça n'aiderais pas ?

**Comment by TmpName** [comment]
Tu peux regler le timeout via le fichier advancedsettings.xml.
Mais je comprend pas ce qui se passe, c'est comme si Vstream essayait de le lire avec son lecteur, qui ne marche pas (timeout) puis kodi essaye de le lire avec le sien , et la ca marche.
Si c'est ca ca veut dire qu'on a un probleme dans le code du lecteur de Vstream.

**Comment by Arias800** [comment]
Mais le lecteur sur le site bug chez moi ça fait plus ou moins la même chose

**Comment by TmpName** [comment]
Ok bon ben la j'ai fait 2 tests, et le serveur est mort ^^.
Donc alors quand on essaye avec le lecteur de Vstream, c'est un player qui essaye d'ouvrir le lien avec une requete HEAD, quand c'est kodi c'est directement Curl avec une requete GET (avec Range=bytes=0-), et y a de grosses difference dans la partie SSL mais la j'y comprend rien.

**Comment by LordVenom** [comment]
Je comprend pas le lecteur de vStream ? le seul truc que vstream fait en plus c'est de mettre le lien en playlist aprés c'est le lecteur de Kodi xbmc.player.

**Comment by TmpName** [comment]
Ben je croyais, mais active le mode debug, et tu verras que ce n'est pas gere pareil. apres je ne sais pas d'ou ca vient, il ya 3 methode que Vstream peut utiliser, je vais tester ca, mais comme je suis en gratuit, apres quelques tests je defonce mes quotas sur le site.

**Comment by Arias800** [comment]
Chez moi uptostream remarche normalement ca devait etre passager ^^
