### ISSUE TITLE
Kaydo hds.to

### ISSUE THREAD

**Issue by Lola33** [Kodi-vStream/venom-xbmc-addons#2123]
Vstream,  la source kaydo hds.to ne fonctionne plus, le lien est vide, est-ce que c'est la même chose pour tous. merci de m'aider.
Lola33

**Comment by Lola33** [comment]
Je vois connexion.., courriel et mot de passe

**Comment by Arias800** [comment]
Le site te bloque on peux rien n'y faire desoler ...

**Comment by Lola33** [comment]
Kodi log indique kaydo_ws et non kaydo hds.to, Kodi est installer sur mon televiseur Android, sur mon PC je peux ouvrir la page de hds.to
Lola33

**Comment by LordVenom** [comment]
Oui j'ai vue ton message sur Kodi Québec (biz à eux), c'est pas aussi simple ont n'est plusieurs à avoir regarder personne n'a jamais trouver le pk du comment, perso même avec un VPN (une nouvelle IP) je ne peux pas y accéder.

**Comment by Lola33** [comment]
Un gros merci..., vStream est tellement extraordinaire meme sans Kaydo
bonne soiree
Lola33

**Comment by Lola33** [comment]
Un gros merci..., vStream est tellement extraordinaire meme sans Kaydo
bonne soiree
Lola33

**Comment by adulescente** [comment]
J'ai le même souci... Hds, j'y accède sans problème via tous mes appareils sauf kodi. Et peu importe ou je suis. Donc mon adresse IP n'est pas en cause. Est-ce que ça fonctionne pour vous ??!

Ceci dit, tout comme Lola plus haut je vous dit merci et même si HDS ne fonctionne plus, vStream est tout à fait extraordinaire. Grand merci de nous donner l'opportunité d'en bénéficier
Jue

**Comment by TmpName** [comment]
Tu utilises quelle url pour hds ?

**Comment by TmpName** [comment]
Pour ceux que sa bloque essayez "ht tps://www .hds.to/search.php?q=test"

Par contre now que c'est debloque, impossible de le refaire bloquer, donc ca pas demain qu'on va trouver le prb.

**Comment by Lola33** [comment]
Le site twitter
https://twitter.com/hds_to?lang=fr

**Comment by LordVenom** [comment]
Nop l'url n'a rien donner toujours bloquer.

**Comment by tuxdata** [comment]
https://www.hds.to/home.php fonctionne avec vpn sur france; mais c'est la page de login

**Comment by Arias800** [comment]
Justement si tu tombe sur la page login c'est que ça ne marche car ça te bloque
