### ISSUE TITLE
Filmzenstream

### ISSUE THREAD

**Issue by AngelineL** [Kodi-vStream/venom-xbmc-addons#2124]
Bonjour.  Filmzenstream ne fonctionne plus chez moi .

**Comment by TmpName** [comment]
Un exemple qui ne marche pas, et qui marche sur le site ?

**Comment by AngelineL** [comment]
Au temps pour moi j'avais pensé à verifier le site avant mais je l'avais fait sur ma 4g sur mon tel . J'ai changé mes dns , c'est bon .
