### ISSUE TITLE
sous-titres

### ISSUE THREAD

**Issue by perive** [Kodi-vStream/venom-xbmc-addons#2125]
Bonjour,
Les sous-titres de Upto_ox n'apparaissent plus sous Vstream depuis 2 jours.
Sur le site, les sous-titres sont off par défaut et il faut les activer dans les options du lecteur du navigateur, mais, dans Vstream, impossible...

**Comment by Arias800** [comment]
Corriger il faut mettre a jour uptob_x.py et uptoste_m.py si tu veux tester avant la maj des 3 jours

**Comment by perive** [comment]
C'est bon, ça marche. Merci Arias800.

**Comment by Arias800** [comment]
Ah oui c'est vraie j’avais oublier qu'il n'y aurai pas de maj x)

**Comment by perive** [comment]
La MAJ des 3 jours a remis les fichiers uptobox.py et uptostream.py sans la correction des sous-titres.
J'ai dû remettre manuellement les bons fichiers corrigés par Arias800.

**Comment by Arias800** [comment]
Oui ça arrive quand tu corrige les fichier manuellement mais de toute façon il n'y a pas de maj des 3 jours donc si le bouton mettre a jour apparait fait la pas

**Comment by perive** [comment]
Ok, merci.

**Comment by TmpName** [comment]
Yep, surtout ne faites  la MAJ, sinon vous allez avoir un retour en arriere.
