### ISSUE TITLE
Mise à jour du 18.06.18

### ISSUE THREAD

**Issue by jay-jay69** [Kodi-vStream/venom-xbmc-addons#2126]
Bonjour,
Suite à la mise à jour du 18.06 à 16:37, il y a plusieurs sources qui n'ont plus aucuns films. Par exemple:
Cela fait presque 2 mois que je regarde des films en utilisant la source film illimité sans aucun soucis. Mais depuis la mise à jour, film illimité reste vide. Plus aucun films.

Cela m'embête beaucoup car sur film illimité, il y a megadrive qui est plus rapide et connaît moins de soucis qu'openload pour la lecture de films.

Je ne sais pas à quoi cela tient, mais s'il existe une solution, merci de la communiquer/appliquer au plus vite.

 Merci encore pour le développement de cet indispensable addon.
Salutations

**Comment by LordVenom** [comment]
Merci pour le rapport de bug, par contre la correction c'est pas pour tous de suite XD.

**Comment by TmpName** [comment]
Il te suffit de chnager lurl a la ligne 20 par la derniere en date et ca va remarcher.

**Comment by jo9724** [comment]
Bonjour,

J'ai le même problème que Jay-jay69 concernant l'absence totale de films pour certaines sources dont film illimité et Kaydo. Il y a bien la solution donnée par TmpName, mais je suis un novice.
De quelle manière peut-on changer l'url à la ligne 20 par la dernière url en date. J'ai cherché dans la configuration de Vscream, mais je n'ai rien trouvé pour faire cette manip.

Quelques explications plus détaillées me seraient d'un grand secours

Merci et bravo pour ce merveilleux addon

Salutations

**Comment by Arias800** [comment]
Tout dépend de ton os (Android , Windows...)

**Comment by jo9724** [comment]
Kodi est installé sur une Shield Android TV

**Comment by Arias800** [comment]
Il faut que tu va dans le dossier de vstream https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-vStream et que tu modifie la ligne 20 du fichier film_illimite.py

**Comment by jo9724** [comment]
Ok mais il m’est impossible de modifier le fichier car l’application « ES Editeur de texte » ne me permet pas de sélectionner  l’icône « modifier » avec le petit crayon…

La ligne 20 contient :   URL_MAIN =  ‘ https://official-film-illimite.co '

Si je trouve le moyen de modifier cette ligne, par quoi dois-je la remplacer ?

**Comment by jo9724** [comment]
Ok encore merci, mais je ne trouve pas comment modifier ce fichier avec la NVIDI SHIELD

**Comment by LordVenom** [comment]
Bonjour, Cherche dans une autre source.

**Comment by Arias800** [comment]
J'utilise xplorer sur ma Shield une fois le fichier sélectionner je clique sur texte et après le petit crayon

**Comment by jo9724** [comment]
Ça y est j’ai réussi à modifier la ligne en remplaçant co par ws mais cela n’a rien changé.
Au contraire, avant s’affichait « aucune information », maintenant film illimite ne s’ouvre même plus.

**Comment by TmpName** [comment]
Tu as du faire une faute de frappe, python est tres sensible, un espace un guillemet en trop et ca marche plus.
