### ISSUE TITLE
Opnload HS? 

### ISSUE THREAD

**Issue by Antho59380** [Kodi-vStream/venom-xbmc-addons#2127]
Bonjour.
Utilisateur de kodi 17.6 il me semble la dernière version stable sur Android TV. 
Plus aucun lien openload ne fonctionnent. 
Quand j'appuie dessus le cercle tourne il est écrit décodage peut prendre plus d'une minute. Ensuite une fenêtre avec écrit "OK"
Jusque là tout fonctionne mais au moment où le film devrait se lancer il m'écrit à chaque fois "échec de lecture d'un ou plusieurs fichiers". 
Avant la mise à jour ça fonctionnait normalement, mon timeout est à 60s comme vous le préconisez. 
Merci pour vos réponses.
Log s2Gq8BsCF2

**Comment by LordVenom** [comment]
Bonjour,

désoler openload fonctionne tu doit tenter de lire des liens morts.

Merci pour le log c'est rare mais comme tu peux le lire dans le post ce dessous en ligne 2 avec le sites et le nom c'est plus rapide pour tester.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/11

**Comment by Antho59380** [comment]
Merci pour la réponse.
Je te donnerai le nom directement.

**Comment by TmpName** [comment]
Il y a effectivement un prb sur tes logs, le decodage s'est mal fait.
Apres j'ai pas acces a ma machine donc je peux pas dire si ca vient de leur code ou de ta machine, j y jette un oeuil ce soir.

**Comment by Antho59380** [comment]
TmpName merci pour ton aide

**Comment by TmpName** [comment]
Bon ben dsl, je viens de retester avec le meme lien, pas de prbs.
En fait le code d opnload est dynamique donc il a pu chnager depuis, a part te dire de re-essayer je vois pas trop.
Verifi si ta version de python de python est a jour, c'est un truc recurrent sur les machines exotiques (eg les problemes SSL), mais la je peux pas t aider, j'ai vu passer la manip plusieurs fois en issue, mais je connais pas du tout android.

**Comment by Antho59380** [comment]
Merci pour ton aide.
C'est une Xiaomi mi box 3 sous Android 7.
Je ne connais pas python ou est ce que ça se trouve ?

**Comment by Antho59380** [comment]
Alors j'ai regarder dans mon navigateur. Voir films/ready player one/openload et la vidéo à mis au moins 5 minutes à charger.
Du coup mon problème vient de Vstream/kodi ou ma mi box ?
Si quelqu'un a une solution. 
Merci

**Comment by Arias800** [comment]
Après il se peux que ce soit openload ^^

**Comment by Antho59380** [comment]
Oui possible mais avec Vstream il me met échec de lecture tout le temps eu importe le moment ou le film alors qu'avant je n'ai jamais eu de problème je regardais quasiment que ces liens là.

**Comment by TmpName** [comment]
Dans tes logs le decodage du lien s'est mal fait, donc soit le code du parser est tombe sur un os (mais j'ai pas pu reproduire), sois il y a un hic au niveau de ton executeur python, y a de gros calculs pendant au moins 1 minutes.

Dans ton cas ca a affiche 'ok' mais le lien etait rate, donc ca n'aurait jamais marche.
5 mn a charger c'est bizarre, tu aurais eu un timeout. Ca met 1/2 mn a calculer puis ca affiche 'ok', a partir de la, tu as le timeout qui se met en place 30s par defaut je crois.

**Comment by Antho59380** [comment]
OK je vois. Mais qu'est ce que je dois faire avec python ? Ma mi box est à jour je ne peux pas faire de mise à jour Android.
Les liens speed video fonctionnent et upto stream aussi mais ça m'embete parce que openload c'était vraiment bien

**Comment by Arias800** [comment]
Il me semble que pour Android c'est kodi qui gèrent python donc peut être qu'en réinstallant Kodi ça remarchera ?

**Comment by Antho59380** [comment]
Je vais essayer ce soir à ce moment là mais je l'ai réinstallé il y a pas longtemps suite à l'erreur SSL CERTIFICATE

**Comment by Antho59380** [comment]
Bon ben j'ai desinstallé kodi et Vstream et tout réinstallé mais ça ne fonctionne toujours pas.
Je désespère.

**Comment by helpmoi** [comment]
Il y a certains lien openload qui ne s'ouvrent pas. Je dirai le problème vient du site (lien) et non de kodi et encore moins de vstream. J'ai le soucis avec les liens netu. Je n'utilisait pour regarder des séries. Maintenant il ne marche plus. Der plus en plus de liens ne marchent plus malheureusement. Par exemple, il m'est impossible de regarder la série Suits. Plusieurs sites proposent des liens morts ou d'autre propose des liens qui fonctionnent mais qui bug au bout de 5 min...

**Comment by Antho59380** [comment]
Non mais la c'est des liens qui ont été testés par d'autres personnes et par moi même sur mon portable donc ce n'est pas un problème de lien mort

**Comment by helpmoi** [comment]
Et si tu testes SPMC c'est une apps qui ressemble à kodi. Il se trouve sur le Playstore si tu utilises android.

**Comment by Antho59380** [comment]
Je préfère rester sur kodi. Ça doit faire 4 ans que je l'utilise.

**Comment by Arias800** [comment]
Je viens de comprendre que j'ai le même bug chez moi (kodi 17.6 nvidia shield android 7.0)

**Comment by Antho59380** [comment]
Tu as trouvé une solution Arias 800?

**Comment by Arias800** [comment]
Non pas encore

**Comment by Arias800** [comment]
@TmpName le ?mime=true après le liens openload il est obligatoire ?

**Comment by Arias800** [comment]
J'ai trouver l'origine du bug enfaite vstream décode le liens donc pour colony s3episode 8 sur serie-streaming hd c'est ça : https://oqbkia_oloadcdn.net/dl/l/gXTJr288CDSI-jE9/AWZ898H7Wns/Colony.S03E08-planet-streaming.com.m4v.mp4?mime=true 
Mais il ouvre celui la https://openload.co/embed/AWZ898H7Wns qui est le liens de base non décoder par contre pourquoi je sais pas 
![capture](https://user-images.githubusercontent.com/24809312/41817241-37d8bf28-7797-11e8-90b3-a02d3779d962.PNG)

**Comment by Antho59380** [comment]
Ah d'accord je vois. Moi je suis pas développeur alors je ne pourrai pas aider.
Mais si tu trouves une solution je suis preneur.

**Comment by Arias800** [comment]
J'attends TmpName car le code d'openload est juste trop complexe pour moi x)

**Comment by Antho59380** [comment]
Et encore plus pour moi lol.
En tout cas merci d'avoir identifié le problème

**Comment by Arias800** [comment]
Après je suppose que c'est mais si ça se trouve je me trompe mais y a pas d'erreur ou de chose bizarre hormis ca donc bon ^^

**Comment by TmpName** [comment]
Bon le log est plus dispo, mais ca c'est normal, en fait il faut regarder le lien decode, il y a une partie avec des chiffres du style 111.222.333 et lui avait 112::445z, un truc totallement impossible a ouvrir.

C'est le parser JS qui deconne, mais impossible de reproduire le bug chez moi.

**Comment by Arias800** [comment]
Voila mon log @TmpName https://slexy.org/view/s2kayauZ2A

**Comment by TmpName** [comment]
Vstream: h ttps://open load.co/stream/AWZ898H7Wns~1529913086~2a01:cb15::~XOgaQQDg?mime=true
La partie "~2a01:cb15::~" n'est pas bonne, du coup vais restester chez moi.

**Comment by Arias800** [comment]
C'est bizarre sur navigateur le liens marche pourtant ^^

**Comment by TmpName** [comment]
C'est normal, c'est le parser de Vstream qui decode mal le lien.
Mais la je vient de retester j'ai obtenu le lien

> Decoded url : AWZ898H7Wns~1529916800~176.128.0.0~CetWloB_

Et qui du coup marche tres bien. Compare les 2 urls, tu vas vite voir le prb.
Par contre pour pouvoir tester, il ma faudrait le code html de la page brute qui deconne, car celle que j'ai moi marche sans prbs.
Ou mieux, tu as 3 lignes a re-activer pour sauver le code JS extrait dans un fichier (l167 a 169).
Si tu peux me passer le code JS + la ligne dans les logs avec le code, je me retrouverais exactement avec les memes bases que toi.

**Comment by TmpName** [comment]
Alors c'est que c'est peut etre normal, et la redirection se fait vers quelle url ?
Peut etre que c'est a faire systematiquement sur des url avec ":"

**Comment by Arias800** [comment]
La redirection mene ici : https://o_bkia.oloadcdn.net/dl/l/GHkRp7q-5TIwIiUD/AWZ898H7Wns/Colony.S03E08-planet-streaming.com.m4v.mp4?mime=true

**Comment by Arias800** [comment]
Le liens décoder sur mon pc c'est ça : https://ope_load.co/stream/AWZ898H7Wns~1529926211~90.112.0.0~w0Ky4X5H?mime=true

**Comment by TmpName** [comment]
Pour le coup, je pense que tu as raisons, c'est pas le code du parser qui deconne, mais une redirection a la con pour les machines android.

**Comment by Arias800** [comment]
Donc si je mets un UA android dans le code d'open load sur mon pc de windows alors ça devrait bugger

**Comment by Arias800** [comment]
J'ai mis ca comme UA Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1 mais ca n'est pas passer ..

**Comment by Arias800** [comment]
Je tente un replace pour forcer la recuperation des truc erroner pour voir si ca vient de la

**Comment by Arias800** [comment]
Sur le site d'openload ca parle d'androd         `if(!!window.chrome && !!window.chrome.webstore && navigator.vendor == "Google Inc." && !/ios/i.test(navigator.userAgent) && !/android/i.test(navigator.userAgent) && parseInt(getChromeVersion().split(".")[0]) >= 65){
            noPopunder = false;
        }
            }catch(e){}` 
mais je sais pas ce que ca veux dire x)

**Comment by Arias800** [comment]
Si je me connecte via navigateur (donc sur mon android tv ) au liens qu'utilise vstream ça ne marche plus ça me mets 403 wrong ip

**Comment by Arias800** [comment]
En passant par le navigateur de ma box android j'ai wrong ip  code erreur 403 donc je comprends plus x)

**Comment by Arias800** [comment]
@TmpName Avec un UA vide ça passe pas alors que ça marche sur mon pc donc c'est pas un probleme de user agent ....

**Comment by TmpName** [comment]
En fait si tu laisses l'UA vide, ca va mettre un UA android. Et j'ai peur que le lien "louche" soit reserve aux machines android, vu que moi je ne l'ai jamais, et toi non plus sur ton pc.

**Comment by Arias800** [comment]
En restant le lien à la con sur un navigateur internet de ma box Android

**Comment by Antho59380** [comment]
Je ne comprends rien à ce que vous dites mais je suis la conversation lol

**Comment by TmpName** [comment]
Lol.
Sinon du coup ca me conforte dans l'histoire de l'user-agent, "wrong ip" c'est un message courant quand ce n'est pas le meme lors de la requete pour obtenir l url, et lors de celle pour l'url en question.

**Comment by Arias800** [comment]
Après j'ai essayer avec un UA de pc tournant sous windows avec Mozilla et rien n'a faire ce n'est pas passer sur la box android .Et inversement avec une UA android sur mon pc sous windows il récupère le bon liens...

**Comment by TmpName** [comment]
XD, alors la c'est magique ^^.
Y aurait un bug dans le traitement du code sur android ?
Tu pourrais me faire passer fichier js.txt + les 3 ligne de logs produite avec le meme fichier stp (les codes + l url decode par la machine android)

**Comment by Arias800** [comment]
Je fait ça demain là je peux pas mais oui 'c'est tres bizarre comme truc la x)

**Comment by TmpName** [comment]
Apres si les urls "foireuse" marche apres la redirection, suffit de les detecter (si il y a ":" en fin d'url) et de traiter la redirection. Mais c'est vraiment bizarre car la fin de l'url est bonne, au vu de l'algorytme si il y a un seul decalage, toute la fin de l'url devrait deconner, pas juste la parti avec des chiffres.

**Comment by Arias800** [comment]
Bah j'ai mon pc avec python installer dessus

**Comment by Arias800** [comment]
Les log avec les code et l'url decoder : https://pastebin.com/d6Lvf1Pg
Le fichier js.txt : https://pastebin.com/FAhNWDjU

**Comment by TmpName** [comment]
Bon la je comprend pas, j'ai meme teste le code sur navigateur,j 'obtiens la meme url decodee avec des ":".
Donc le prb ne vient definitivement pas du parser
Le code JS etant extrait de la page html, on doit avoir le prb des l'obtention de la page html. Mais si c'est pas l'user-agent, qu est qui peut faire que le serveur reconnaisse une machine android et envoit un code batard ?

**Comment by Arias800** [comment]
Je sais pas pourtant j'ai essayé dans les deux sens (faire croire que mon Android TV est un windows et inversement ) et rien à changer je testerai demain après-midi au cas où mais bon j'y crois moyen ^^

**Comment by TmpName** [comment]
Je viens de tester avec un UA android, la page etait bonne.
Faut faire des tests avec navigateur+httpfox , sur android, sur pc et comparer les liens obtenus (si il y a des ":") et du coup les requetes.

**Comment by Arias800** [comment]
On peux pas il me semble utiliser httpfox sur Android TV donc là pour moi ça va être compliqué x)

**Comment by Arias800** [comment]
Essaye avec un UA pour Android TV peut être que le site différencie Android et Android TV ça expliquerait pourquoi ça passe avec une UA Android et pas avec ma Shield

**Comment by TmpName** [comment]
Wé j'imagine, sinon faut passer par kodi en mode debug, ca va afficher tout les en tetes.

Resume pour ceux qui veulent faire avancer le smilblick.
- Sur machine normale, quand on lance une video openload (sur navigateur), le lien final est du genre
`Decoded url : AWZ898H7Wns~1529916800~176.128.0.0~CetWloB_`
- sur machine android, le lien est du genre
`stream/AWZ898H7Wns~1529913086~2a01:cb15::~XOgaQQDg?mime=true`

La question est : pourquoi ?
Ca ne semble pas venir de l'user-agent.

**Comment by TmpName** [comment]
Now que je regarde, ca ressemble a une adresse ip V6 incomplete. Mais je vois pas comment passer de l'une a l'autre.

**Comment by Arias800** [comment]
Je viens d'essayer sur Android 8.0 même problème

**Comment by TmpName** [comment]
Je pense qu'il y a moyen de gruger.
En fait il s'agit des 2 premiers nombre de ton adresse ip, code en ipv6 pour android, et ca doit bien etre genere tout seul lors de la premiere requete par le serveur openload lui meme.

Une fois que tu as le lien decode, remplace
`~XXXX:XXXX::~`
par 
XXX.XXX..0.0

avec xxx.xxx qui sont les deux pemier chiffre de ton ip en ipv4.

**Comment by Arias800** [comment]
Si je désactive l'ipv 6 de ma Shield et /ou  de ma box internet il ne peux pas l'obtenir donc logiquement ça devrait passer je testerai ça demain

**Comment by Arias800** [comment]
Tu à raison c'est ça ^^

**Comment by TmpName** [comment]
Lol, c'etait que ca  ? Et y a donc des sites peu compatible avec les ip v6 encore.
On met un message d'erreur dans Vstream pour prevenir l user ?

**Comment by Arias800** [comment]
Ah mon avis c'est un bug lié à l'exécution de python chez Android puisque via mon téléphone la vidéo ce lance sur le site ^^

**Comment by TmpName** [comment]
Bon, j'avoue moi android, je cherche plus trop a comprendre, mais on peut tjours afficher un message si il y a des ":" dans l'url pour prevenir que l'user que ca va merder, ou alors avec ton telephone c'est aussi une ip v6 mais qui fonctionne ?

**Comment by Antho59380** [comment]
Vous êtes au top les mecs !!! Donc il faut enlever ip v6 de la box ? Ça ne va pas poser de problèmes pour d'autres périphériques sur le réseau ?

**Comment by Arias800** [comment]
Via mon navigateur Android et l'ipv6 activer sur la box ça passe mais avec Kodi ca ne passe pas et ça expliquerait pourquoi on arrive pas à reproduire le bug via un UA puisque le problème ne viens pas de la ^^

**Comment by Arias800** [comment]
Problème regler sur Android TV aussi

**Comment by Antho59380** [comment]
On peut désactiver ipv6 dans kodi ou il faut le faire seulement depuis la box opérateur ?

**Comment by Arias800** [comment]
Tu peux depuis ta box Android ,la box de ton opérateur et après pour Kodi je sais pas

**Comment by Arias800** [comment]
Peut importe il fait juste pas que le serveur récupère l'adresse IPv6

**Comment by Antho59380** [comment]
Il faut que la box Android soit rooté. Je vais le faire depuis ma box
opérateur.
En tout cas super boulot.
Merci.

**Comment by TmpName** [comment]
Mais le prb reste la.
Le prb vient de kodi, de vstream, de opeload ?
Si l'adresse comprend 2 ":" a la suite, ca plante systematiquement ? Dans ce cas on fout une fentre pr prevenir.

**Comment by Arias800** [comment]
Je sais pas je comprends pas trop faut voir si on peux pas forcer l'ipv4 quand on se connecte au serveur d'openload

**Comment by TmpName** [comment]
Surtout que un de ces jours faudra tous passer en ipv6.
Pour le moment je ne peux pas faire de tests, mais il semblerait que le serveur reconnaisse le type d'ip a utiliser en fonction du "host" que le client retournerait lors de la requete.
En resume faudrait un navigateur compatible ipv4 et ipv6 et regarder la requete.
Y aurait aussi un truc avec python et socket.AF_INET6

Enfin bon, vu le peu de personne qui se plaigne, vais juste mettre un popup.
