### ISSUE TITLE
Opnload

### ISSUE THREAD

**Issue by ebs111** [Kodi-vStream/venom-xbmc-addons#2129]
J'ai une suggestion à propos de OPNLOAD
Peut-être utilisez le site 9xbuddy, il génère un lien très rapide et un autre serveur privé qui est vraiment rapide, voici un exemple:
ht tps://9xbuddy.com/process?url=https%3A%2F%2Foload.download%2Ff%2FGATXBC0jc8I
J'ai vérifié le lien qu'ils créent dans Cody et il a volé.
Juste ne pas juste comprendre comment ils font le lien direct là-bas, bien sûr, il sera vraiment facile pour vous.
Merci beaucoup

**Comment by TmpName** [comment]
A garder sous le coude, l'inconvenient c'est que les sites changent souvent, le code mit en place actuellement est plutot stable, tres peu de modifs depuis un an. Mais faut que je regarde plus en detail, ca peut servir.

**Comment by ebs111** [comment]
Vous avez raison, bon code, un petit inconvénient lent.Vous pouvez ajouter une option dans les paramètres, et ce site est assez stable et assez unique, ce qui résout OPENLOAD assez rapidement.
Merci quand même

**Comment by TmpName** [comment]
Yep, j'ai teste, il marche tres bien, mais si ils changent leur code regulierement, on va devoir faire pareil, la on a trouve une parade fiable pour opnload, donc pr le moment c'est pas une priorite pr moi, mais ce site est tres bien, je connaissais pas.

**Comment by ebs111** [comment]
Je connais Python et je suis allé écrire à Cody, je serais heureux de vous aider si vous pouviez me guider un peu

**Comment by ebs111** [comment]
J'ai été en mesure de prendre et d'organiser tout le code pertinent du site 9xbuddy pour Python et d'implémenter les codes, je serai heureux de partager le problème est seulement que le lien ne laisse pas passer dans le film que vous connaissez peut-être un moyen de l'arranger? Merci

**Comment by TmpName** [comment]
La par contre si tu veux de l'aide, faudra faire passer ton code (via pastebin par exemple) qu'on puisse tester.

**Comment by ebs111** [comment]
[9x.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/2160772/9x.zip)

J'ai joint le fichier, voyez si vous pouvez aider. Merci

**Comment by TmpName** [comment]
Je viens de tester, tout marche.
Ton lien marche sans probleme dans VLC par exemple.
Par contre je ne suis pas sur que l'hebergeur propose le streaming, tu peux lire le fichier depuis le debut, mais si tu fais marche avant ca bloque.
J'ai essaye avec media player classic, meme bloquage.

**Comment by ebs111** [comment]
Oui je sais une honte ...
Je pensais que vous pourriez penser à une façon que je ne pensais pas, merci quand même

**Comment by ebs111** [comment]
Que diriez-vous de télécharger le code sur HEROKU par exemple? Et puis la solution sera beaucoup plus rapide?

**Comment by TmpName** [comment]
C'est a dire ?

**Comment by Arias800** [comment]
Heroku c'est un hébergeur cloud mais je sais  pas de quel code il parle ^^

**Comment by ebs111** [comment]
Swap to Hebrew
Je vais vous expliquer à propos de herooku Vous pouvez mettre du code en Python en cours d'exécution Envoyez-lui le code HTML et votre code va résoudre et retourner la réponse.
Swap to Hebrew
Voici un exemple qui résout le problème herooku qu'il résout l'openload sur le serveur de l'herooku et donc la réponse n'est pas bonne car c'est ip.

https://github.com/Rudloff/alltube

**Comment by ebs111** [comment]
https://phantomjscloud.com/?gclid=CjwKCAjw4PHZBRA-EiwAAas4ZsuM8TQX81MBj09rnwWROz9EOQrcItV8SW9rR-T_4lBN9DRmDUOgBRoCIBgQAvD_BwE
Another idea :-)

**Comment by ebs111** [comment]
https://elements.heroku.com/buttons/rudloff/alltube


Cliquez simplement sur
déployer à herooku puis enregistrer où vous choisissez un nom, puis déployer l'application attendez qu'il se termine et cliquez sur la vue à la fin et voir quelle beauté

**Comment by ebs111** [comment]
Eh bien, j'ai trouvé une façon beaucoup plus rapide de résoudre avec OPENLOAD :-), avec l'aide de js2py si vous voulez faire apparaître le code

**Comment by TmpName** [comment]
Si tu convertis le code JS vers du code python, ca ne marchera pas car le code change tout le temps.
Si tu utilises leur interpreteur, je suis pas sur qu'il soit plus rapide que le notre.

**Comment by ebs111** [comment]
Swap to Hebrew
Je ne convertis pas le code en python car je sais qu'il change, j'utilise js2py, ajoute juste sa bibliothèque extensible, ce qui est beaucoup plus rapide que quelque chose comme 3 secondes, pour le navigateur sans tête, ils sont juste pour l'ordinateur et ne donnent pas de solution Android

**Comment by TmpName** [comment]
C'est imposible, js2py ne gere pas la fonction "With", donc impossible d'arriver a executer le code JS avec cette lib
```

  File "G:\Python\js2py\js2py\translators\translating_nodes.py", line 504, in WithStatement
    raise NotImplementedError('With statement not implemented!') NotImplementedError: With statement not implemented!
```

Apres je suis pas un pro, mais pour avoir vu les deux code, ca m'etonnerait que le leur puisse etre plus rapide.

**Comment by ebs111** [comment]
Oui, j'ai aussi eu ce problème et je l'ai résolu, regardez et voyez si c'est plus rapide ou pas ... Il y a beaucoup de code qui est mort là parce que je n'ai pas encore nettoyé

**Comment by ebs111** [comment]
Oui j'ai eu ce problème résolu, et il est nettement plus rapide, ici vous allez vérifier ...
[smalled_opf2.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/2182027/smalled_opf2.zip)

**Comment by TmpName** [comment]
Tu as vu le nbre de modif faites sur le code JS ?
Si demain ils changent juste "_0x531f91' par "_0x531f92' (et c'est ce qu'ils fnt toute les semaines)  c'est mort ton code ne marchera plus.
Le but est justement d'avoir un code qui tournera meme si ils modifient le leur.

**Comment by ebs111** [comment]
Vous avez raison de petits changements au code nécessaire, bien que je suis sûr que vous serez en mesure de rendre le code plus général Total 3 paramètres manquants pris à partir de la source de la page.
De toute façon tu as vu la vitesse mais?

**Comment by TmpName** [comment]
yep plus rapide.

**Comment by ebs111** [comment]
Peut-être que vous pouvez perfectionner ce code?

**Comment by TmpName** [comment]
Ben moi c'est pas prevu, si ca t interesse, tu peux le bidouiller, tu as une version plus a jours ici, mais encore plus lente.
https://github.com/TmpName/TinyJSParser

**Comment by ebs111** [comment]
Je ne vous comprends pas, peut-être en anglais?

**Comment by TmpName** [comment]
I don't have planified to improve the code, I just correct bugs.
On the previous link you have an updated version, more in date but slower than the version you have tried ^^.
This code is free to use/modify or whatever you want to do with it.

**Comment by ebs111** [comment]
Ok, alors qui est le grand expert ici? Toujours à la recherche de quelqu'un à apprendre et à améliorer

**Comment by ebs111** [comment]
Avez-vous un groupe à TELEGRAM peut-être?

**Comment by ebs111** [comment]
maybe you can modify my code?

**Comment by TmpName** [comment]
Nope, we can't use js2py because :
- Hard to include this libs in a kodi addon as dependency.
- The lib is too heavy

**Comment by ebs111** [comment]
Its not hard you just add the folder, like in the example i send, lots of addon (plcenta, exudus ext.) use it you need it for cloudflare,and  its only 3Mb in size

**Comment by TmpName** [comment]
3 MB and our lib less than 100kb.

**Comment by ebs111** [comment]
How do solve and enter cloudflare sites?

**Comment by TmpName** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/cloudflare.py
