### ISSUE TITLE
pour la source free-téléchargement il y a le captcha , mais le clavier virtuel embarque par dessus , comment résoudre ce probleme , merci 

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2130]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by LordVenom** [comment]
Note: sujet clos ne respecte pas le standard de rapport.

**Comment by Arias800** [comment]
@KodiTopQuebec  C'est a toi de compléter les différente infos il ne faut pas juste ouvrir l'issue comme ça ^^
