### ISSUE TITLE
free téléchargement , captcha

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2131]
**Décrivez le bug**
Le captcha est cacher par le clavier virtuel

**Votre system**
 - OS: Android ou pc même problème
-  Appareil [nvidia shield, Ultra]
 - Version Kodi .17
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Free-telechargement
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Je n'ai aucun souci sur dll-island le captcha apparaît de manière lisible

**Comment by KodiTopQuebec** [comment]
j ai aucun problème avec dll ou zone téléchargement , mais avec free-téléchargement il nous demande un captcha , lorsque l on clique sur par exemple multi pour un lien le clavier virtuel est par dessus le captcha donc impossible de le voir , airiez-vous une solution ?

**Comment by Arias800** [comment]
J'ai modifier le premier post merci de compléter les différentes informations manquantes versions de Kodi sur quoi ton l'utilise versions de vstream ...

**Comment by KodiTopQuebec** [comment]
C est sur toute version soit sur pc ou Android , oui j ai la dernière version de kodi et de vstream , je gère un groupe de 1648 personnes sur Facebook ( kodi top Québec ) je suis une référence pour ce beau monde , je me pose juste la question pourquoi c est comme ça et je suis certain que toi aussi tu as ce même problème

Envoyé de mon iPhone

Le 24 juin 2018 à 14:43, Arias800 <notifications@github.com<mailto:notifications@github.com>> a écrit :


J'ai modifier le premier post merci de compléter les différentes informations manquantes versions de Kodi sur quoi ton l'utilise versions de vstream ...

**Comment by LordVenom** [comment]
Et le  Captcha de DL-island Fonctionne bien sous Android ? en faite ont n'a fait des tests pour voir les retours mais personne ont c'est dit que ça allais bien. Donc y a deux version de  Captcha.

**Comment by Arias800** [comment]
Le captcha de dl-island fonctionne chez moi mais celui de free-telechargement ce mets en plein milieu de l’écran (étant donnez que moi c'est sur une télévision c'est lisible) mais sur android normal il doit pas l'etre

**Comment by Arias800** [comment]
Je vient d'y corriger chez moi https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/free_telechargement_org.py

**Comment by lebigboss** [comment]
Moi ça fonctionne bien sur Android et sur PC, mais ça dépend surtout du skin que vous utilisez aussi
Il y a des skins avec le clavier qui prend tout l'écran alors que mon skin le clavier ne prend que la moitié 

![screenshot_20](https://user-images.githubusercontent.com/12912677/41844593-eb8c7e18-7870-11e8-847b-308b7892abc7.png)

![screenshot_21](https://user-images.githubusercontent.com/12912677/41844601-f4cf3060-7870-11e8-8e13-6043b54da609.png)

Donc si vous y arrivez pas, vaut mieux changer de skin

**Comment by Arias800** [comment]
Problème régler maintenant il prends tout l’écran comme pour dll-island ^^

**Comment by KodiTopQuebec** [comment]
il est certain que je ne changerais pas mon skin , mon build est monté sous xonfluence que selon moi est un des top skin a avoir pour tout les réglages qui peut offrir , sous DDL-island il est écrit en haut pour le captcha et free-téléchargement il est écrit milieu de la page , donc est il possible dans les lignes de programmations de faire apparaitre le captcha en haut tout comme DDL-Island ?

**Comment by Arias800** [comment]
Normalement maintenant il apparaît de la même manière car j'ai copier coller le code (en le rendant compatible bien sûr)

**Comment by KodiTopQuebec** [comment]
merci tout fonctionne comme sur DDl-Island , si jamais vous décider de mettre cette correction a votre prochaine mise a jour , juste changer un petite erreur code sur le titre Free-Tlchargement pour Free-Telecharchement, merci de m avoir aider sur mon bug

**Comment by KodiTopQuebec** [comment]
![sans titre](https://user-images.githubusercontent.com/40530593/41869381-5e2f9f40-78a8-11e8-88d1-1058b7d235cb.png)

**Comment by Arias800** [comment]
De toute façon la prochaine mise à jour ça va être une mensuel donc ça va mettre à jour la totalité de vstream

**Comment by KodiTopQuebec** [comment]
un petit bug est apparu , d après moi au cause du nom sur ma photo précédente (Free-Tlchargement ) au lieu de Free-Telecharchement , maintenant lors d une recherche dans vstream a la fin ca dit erreur check the log , pour enlever ce problème lors de la recherche j ai été dans les réglages de vstream pour enlever la source free-telechargement et maintenant la recherche fonctionne , si vous avez une correction sur cela merci de l inscrire ici

**Comment by Arias800** [comment]
C'est bizarre dans le fichier le nom est écrit correctement tu es peut être pas à jour

**Comment by KodiTopQuebec** [comment]
oui bien certain que je suis a jours , c est juste depuis que l on a modifié ce dossier , moi aussi j ai été voir dans ce dossiers et le nom est bon , j  y comprend rien pourquoi le nom ne sort pas correctement

**Comment by Arias800** [comment]
Peut être que c'est à cause de l'accent dans le nom du site

**Comment by KodiTopQuebec** [comment]
tu as tout a fait raison , j ai trouvé la ligne a faire la correction, maintenant le nom affiche correctement et la recherche fonctionne  
![free](https://user-images.githubusercontent.com/40530593/41927571-1f2ce090-7962-11e8-8e4b-7f1b3195277e.png)

**Comment by KodiTopQuebec** [comment]
![sans titre](https://user-images.githubusercontent.com/40530593/41927844-e0fb6778-7962-11e8-8274-8bdc64d48a94.png)

**Comment by LordVenom** [comment]
Heu WordPad je doute qu'il encode en UTF-8 lui c'est pas un bonne idée des modif sous python avec ça.

Voir : Notepad++, Atom, visual studio code. du plus simple au plus complet.

**Comment by LordVenom** [comment]
![image](https://user-images.githubusercontent.com/4380112/41928667-3624306e-7976-11e8-9a1b-663ed60b9b74.png)
