### ISSUE TITLE
Lien NETU

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#2132]
Salut

J'ai un souci avec les liens Netu ils sont tous HS quelque soit la video ou la source : fichiers introuvables.

Quelquun d autre a ce souci?

**Comment by Arias800** [comment]
Corrige par @TmpName hier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/netu.py

**Comment by AizenKnower** [comment]
Désolé mais non ca ne marche toujours pas avec votre mise a jour netu.py

Est ce que on doit le rajouter nous même ou ca se fait automatiquement  cette correction ?

**Comment by TmpName** [comment]
A faire soit meme, les mise a jour sont bloquées pour plusieurs jours encore.

**Comment by AizenKnower** [comment]
Ok c bon jai remplacé le fichier netu.py ca remarche dsl du derangement donc oui résolument résolu

**Comment by ktm520** [comment]
Bonjour a tous .

Systeme utilisé  Android
Derniere version de Kodi utilisé (17.6)
Version Vstream 0.6.2

Etant débutant avec Vstream , j'aimerais savoir quelle est la manip a faire pour mettre a jour  ou remplacer la fichier netu.py , qui je pense doit etre a l'origine des films qui ne se lance pas sur ZT , qui restent en rouge .
J'ai bien cherché sur le net , mais je ne trouve pas la manip .

**Comment by TmpName** [comment]
Tu as netu d'affiche comme hoster sur ZT ?
C'est juste un fichier texte a remplacer, il se trouve dans le dossier "hosters".
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/netu.py

**Comment by Arias800** [comment]
Ça doit être son fichier ZT car j'avais fait une correction pour ça  : https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py dans le dossier site
