### ISSUE TITLE
Problème avec Kaydo et I Anime

### ISSUE THREAD

**Issue by tuego72** [Kodi-vStream/venom-xbmc-addons#2133]
Kaydo et I anime ne fonctionne pas. Kaydo affiche seulement 3 points... et I anime ne réagi pas du tout  J'ai réussi à régler film illimité en changeant l'URL mais pas eux.

**Votre system**
 - OS: Linux, Android
-  Appareil m9+ et pc
 - Version Kodi  17.6
- Version Vstream 0.6.2

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
kaydo
I anime

**Comment by Arias800** [comment]
Kaydo je ne peux pas te dire je n'est pas acces au site et Ianime a ete corriger hier il faut attendra la mise a jour mensuel (car il n'y a plus de maj de 3 jour pour le moment ) ou modifier le fichier manuellement https://github.com/Kodi-vStream/venom-xbmc-addons/blob/d9c4d13181a2b721ed2b1b917c131ff0c0d028aa/plugin.video.vstream/resources/sites/mangacity_org.py

**Comment by TmpName** [comment]
Pour kaydo, regardes si tu peux avoir les films en passant par navigateur.

**Comment by tuego72** [comment]
I anime: j'ai copier-coller le fichier au complet de ton lien(Arias800) et il ne marche pas plus, il n'ouvre même pas.
Kaydo (hds.to) : oui je viens d'essayer et avec chrome ça fonctionne.

**Comment by tuego72** [comment]
pour I anime pour être plus précis si je passe par source dès le début, le menu avec recherche, films, séries, etc... apparait mais si je clique sur un de ces choix, il indique working... et après reste sur ce menu

**Comment by TmpName** [comment]
La je sais plus quoi te dire, je peux pas trop aider, pas vu de prbs de mon cote.

**Comment by tuego72** [comment]
TmpName pour toi I anime et Kaydo fonctionne ?

**Comment by TmpName** [comment]
Yep, a part "genre" sur ianime. Et j'ai que des liens upto sur kaydo mais ca c'est peut etre normal.

**Comment by tuego72** [comment]
ok sur ma boite I anime fonctionne je vais refaire mon build et reessayer plus tard sur mon linux. Par contre j'ai encore que 3 points sur kaydo

**Comment by tuego72** [comment]
finalement sur la boite je vois les choix de films/series dans I Anime mais aucun lien...bizarre

**Comment by tuego72** [comment]
j'ai finalement fais un copier/coler de votre dossier de vstream dans Linux. Les menu de I anime sont revenu mais y a toujours aucuns liens de disponible pour les différents animes

**Comment by Arias800** [comment]
Un exemple d'anime qui ne marche pas car chez moi ça fonctionne

**Comment by tuego72** [comment]
anime--anime(vf)--I anime--A--Albator 78--S01E001 Albator 78, là j'ai aucun résultat

**Comment by Arias800** [comment]
Chez moi ça marche donc soit tu a un bug que nous on a pas soit quand tu a copier collez il y  a eu un problème a tu cliquer sur mise a jour entre temps ?

**Comment by tuego72** [comment]
oui

**Comment by Arias800** [comment]
Voila pourquoi car quand tu modifie un fichier manuellement et clique sur la mise a jour le fichier retourne a l’état précédent donc avant la modif
Donc pour mettre a jour manuellement il faut que tu copier et colle la totaliter de cette page : https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/mangacity_org.py

**Comment by tuego72** [comment]
ok moi j'avais pris celui-ci
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/mangacity_org.py

**Comment by tuego72** [comment]
j'avais même pris le dossier au complet en copier coller

**Comment by tuego72** [comment]
mais là ça fonctionne merci
