### ISSUE TITLE
Crash kodi apres maj vstream

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#2134]
Jaimerais savoir si certains qui utilise kodi 18 a pas dernièrement des crashs de kodi apres les maj de vstream?
Depuis 2jours en mettant a jour par github kodi crashes des que son demarrage et je dois le relancer pour kil fonctionne 

Sujet un cas isolé lol?

**Comment by TmpName** [comment]
Kodi 18 pas encore sortis, donc meme pas teste encore.

**Comment by Arias800** [comment]
Le problème de crash avec vstream vient de chez toi car moi ça fonctionne

**Comment by Arias800** [comment]
Je crois que j'ai corriger le bug du crash : https://pastebin.com/0BxTGTcW

**Comment by LordVenom** [comment]
re - un numero de ligne, une info ou je cherche dans les fichiers pendant 3/4 d'heure ?

**Comment by Arias800** [comment]
Mais c'est pour que @AizenKnower teste parce que j'ai eu le bug de crash qu'une fois ^^
Dans gui.py j'ai décommander la ligne 335 et 378 et j'ai commenter la 336 et 379
Dans default.py j'ai décommander la ligne 134 et 135

**Comment by LordVenom** [comment]
Ok dans gui tu est repasse en mode 1 par 1

Dans gui tu aurais du commenter les lignes 136-138 la pour moi y a deux import en même temps

```
exec "from resources.sites import " + sSiteName + " as plugin"
                exec "plugin."+ sFunction +"()"
                plugins = __import__('resources.sites.%s' % sSiteName, fromlist=[sSiteName])
                function = getattr(plugins, sFunction)
                function()
```

**Comment by Arias800** [comment]
J'essaye et je te dit ^^

**Comment by Arias800** [comment]
Je peux pas te dire j'arrive pas a reproduire le bug ..

**Comment by Arias800** [comment]
Oui mais je voulait dire que je n'ai aucune idée de quel ligne corrige le problème x)

**Comment by Arias800** [comment]
Le bug d'affichage est corriger ici : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/b9ce7bca6c71b059c3862fc6c10a97bdc4b55484 @AizenKnower

**Comment by AizenKnower** [comment]
Merci @Arias800
J'ai juste un souci avec les maj de vstream ces dernières jours car sans vouloir critiquer elles apportent plus de bugs que correction
Il y a ce probleme d affichage et le crash kodi (meme si le redémarrage fonctionne jusko prochain maj) et la dernièrement( je crois hier ) la maj apporte un bug sur tout les liens devenu non fonctionnelle

J'ai remettre le dernier backup de vstream fonctionnelle et je reste a cette version tout comme je suis rester a kodi 18 version du 11juin.

Je vais tester les modif d aujourdui  pour voir si les liens sont fonctionnelles et si le probleme d affichage est résolu

Merci

**Comment by LordVenom** [comment]
Ont t'a dit que la bêta était instable que ce soit Kodi ou vStream. Si tu veut aider fait des rapport de bug discute avec nous mais les commentaires genre la bêta plante sérieux ça vas finir par plus passer du tout.

**Comment by Arias800** [comment]
Après au pire tu peux chercher qu'elle modif fait dans la bêta génère le bug et directement commenter en dessous des pull request fait par @LordVenom  comme j'ai fait ici : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/8e69aad3b97950a68a454db7ffd605d60829f606

**Comment by TmpName** [comment]
Et ne surtout pas valider les mise a jours, car automatiquement tu vas te retrouver avec des fichiers plus vieux.

**Comment by arzaz** [comment]
Bonjour,

Depuis quelques je trouve beaucoup de difficultés avec vStream, la mise a jour bug en attente de "mise en cache", tout s'affiche sur une page au lieu de passer vers une autre page je m'explique quand je lance par exemple Film, le résultat ne s'affiche pas sur une autre page mais  je dois dérouler tout a fait en bas pour trouver la suite et ainsi de suite….
Voir le log ci-dessous:

https://slexy.org/view/s2nf68QHFK

Système utilisé: Android Oreo
Appareil: nvidia shield tv 2017
Kodi: Leia 18 Alpha 2

De l'aide svp

**Comment by Arias800** [comment]
Le bug est corriger ici : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/b9ce7bca6c71b059c3862fc6c10a97bdc4b55484 soit tu mets la correction manuellement soit tu attends la mise a jour mensuel

**Comment by arzaz** [comment]
J'ai bien corrigé manuellement le fichier gui.py mais malheureusement au lancement de vStream j'ai l'erreur "Erreur vStream"
Ci-dessous le lien du log:

https://slexy.org/view/s2Oo0xXIf3

**Comment by LordVenom** [comment]
Tu as copier juste le fichier gui ? ça vas pas nous aidez y a eu tellement de modif.

Soit tu reste sur la version 0.6.2, soit tu teste la beta mais faut prendre tout le dossier sinon ça vas planter a coup sur.

**Comment by arzaz** [comment]
J'ai installé la beta et tout est en ordre maintenant.

Merci LordVenom
