### ISSUE TITLE
Pas de streaming sans premium

### ISSUE THREAD

**Issue by Yhan06** [Kodi-vStream/venom-xbmc-addons#2135]
Bonjour je suis novice sur Kodi et Vstream. Au bout d'un certain temps j'ai un message "Pas de streming sans premium sur énormément de vidéo.
Pouvez vous m'expliquer au bout de combien de temps et les solutions à cela??
J'ai également des soucis sous OpenLoad avec des fichiers introuvables?
Merci d'avance de votre aide

**Comment by Arias800** [comment]
Merci de remplir le formulaire pour les rapport de bug car la c'est comme chercher une aiguille dans une botte de foin :

**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
@Yhan06 si tu clic sur un lien >> 1 fichier <<< il faut un compte premium d'ou les msg pas de streaming sans premium

**Comment by TmpName** [comment]
Openload est corige, mais les MAJ sont bloques pour le moment, donc pas trop de choix, soit attendre, soit mettre toit meme les fichier a jours.
