### ISSUE TITLE
Avant de faire un rapport de bug

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2136]
Afin de faciliter notre travail merci d’organiser votre demande...

1 - Merci de créer un nouveau message (new issue) pour chaque nouvelle question.

2 - Si c'est une erreur de script indiquer les lignes d'erreur de votre log (voir wiki pour l'emplacement).

3 - vStream vérifie tous les 3 jours les mises à jour automatiquement.

4 - Une mise à jour du cœur de vStream ce fait 1 fois par mois. Installer le Repository de vStream pour que cela soit automatique.

5 - Nous avons mis en place un formulaire que vous devez remplir pour faire des rapports de bug:

![capture](https://user-images.githubusercontent.com/24809312/42077655-d8b34478-7b79-11e8-8283-c62cfd0f5d19.PNG)
Car cela nous simplifie le travaille et nous permets de corriger les problèmes plus rapidement.
Ensuite quand vous ouvrez un issue il y a un document avec des règles à lire. Si vous ne l'avez pas déjà fait il donne quelques informations pouvant vous être utile. Il ce trouve ici : 

![capture](https://user-images.githubusercontent.com/24809312/42077769-39c1d36a-7b7a-11e8-9900-cc5672c16445.PNG)

Tout les sujets qui ne respectent pas les règles seront Fermer vous voila prévenu.

Repository vStream:
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.0.3

Documentations vStream:
https://kodi-vstream.github.io/

Url d'installation du plugins :
https://github.com/Kodi-vStream/venom-xbmc-addons/tree/0.0.3/repo/plugin.video.vstream

**Comment by Arias800** [comment]
Nouveau petit message pour préciser que le mode debug de kodi est une purge donc je vous demanderai de l'activer que si demander et vstream a maintenant un petit mode debug qui peux être activer ^^
![capture](https://user-images.githubusercontent.com/24809312/42625700-b25e903a-85c8-11e8-9691-fd3f0599a11a.PNG)

**Comment by TmpName** [comment]
Y a moyen de mettre ce screenshoot dans le formulaire ? ou plutot dans le wiki avec un lien qui pointe dessus dans le formulaire, parce que je suis entierement d'accord avec toi, maintenant qu'il n'y a plus de log vstream, si on active les logs via kodi c'est l'enfer.

**Comment by Arias800** [comment]
J'ai fait comme ça c'est bon ? https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils/_compare/a6105378b6b7568e3d5ff1f7aab6876aae4c7265

**Comment by TmpName** [comment]
Yep, on verra si on se retrouve avec des log de 5 M ^^.

**Comment by TmpName** [comment]
Alors la, felicitation ^^.
Tu as resussi a faire un rapport de bug, au meme endroit ou se trouvait le mode d'emploi pour en faire un , sans faire rien du tout comme indique au mem endroit.
Sinon

1 - ZT mis a jour y a meme pas 24 h
2 - Voir film reactive y a moins de 2 jours
3 - C'est pas nous qui gerons UrlResolver, on l'utilise juste.

**Comment by LordVenom** [comment]
Vous avez pas le droit de supprimer normalement c'est bon pour ça aussi ça devient une usine à paramètre Github et traduisez votre site non de non.

**Comment by jmenand** [comment]
Bonjour, j'utilise vstream (bravo au passage😉) depuis la version 17 de Kodi.
N'étant pas un utilisateur averti, je le permet de poster mon problème ici.
Depuis la version 18 de Kodi, j'ai un soucis.
Par exemple si je fais une recherche sur vstream, les serveurs ont l'air de charger mais ma page de résultats est tout le temps blanche. Et ça pour toute tentative de recherche. L'indicateur me montre le chargement (de 1/20 en alliant jusqu'à 20, exemple) et la page suivante est vide.
J'ai un vpn géré par vpn manager qui démarre en boot. Mais j'avais le soucis avant de l'installer. 
Voici le lien vers mon kodilog. Vous pourrez peut-être déjà comprendre ce qui se passe 😊 merci beaucoup par avance.
https://drive.google.com/file/d/1mR0_GkADOeFanTObtoUI-Dlj9xLB3mVC/view?usp=drivesdk

**Comment by TmpName** [comment]
Bon effectivement y a du boulot, j'arrive plus a trouver la page qui explique tout mais :
1 - Est que cella fonctionne sans le vpn ?
2 - Faudrait que tu actives les log de vstream,  c'est dans les parametres de Vstream, car la il n'y en a aucun.
3 - Essayes plutot de creer ta propree issue plutot que de continuer a la suite de celle la.

**Comment by sizanic** [comment]
@chataigne73 
Arrete d'unpinned les issues, ça le fait pour tout le monde.
