### ISSUE TITLE
Pas de liens pour les films zone telechargement

### ISSUE THREAD

**Issue by vstreamkodi** [Kodi-vStream/venom-xbmc-addons#2137]
Les liens des films zone telechargement ne s'affichent pas alors que les séries et animes fonctionnent.

**Comment by ethanael83** [comment]
Pareil, il n'y a plus les liens quand on sélectionne un film
Il y a une mise à jour à effectuer ?

**Comment by ethanael83** [comment]
Merci pour votre aide

**Comment by Nostalgeeek** [comment]
Bonsoir ou Bonjour,

J'ai également le meme soucis avec ZT alors qu'avec DDL-ISLAND ca fonctionne niquel. 

Merci d'avance les gars pour le travail que vous faites!

**Comment by LordVenom** [comment]
Merci de lire https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2136

Sujet Verrouiller.

**Comment by Arias800** [comment]
Corriger ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2139 car @edenweb1 a correctement remplis le formulaire de rapport de bug ^^
