### ISSUE TITLE
Plus de liens affichés sur la source Zone-Telechargement

### ISSUE THREAD

**Issue by edenweb1** [Kodi-vStream/venom-xbmc-addons#2139]
Bonjour j'ai essayé de faire au mieux afin de respecter le nouveau formulaire de bug. J’espère que cela conviendra a l'équipe.

Bug constaté:
Au moment de choisir le Host, Les liens ne s'affichent plus pour tout la plupart du contenu Film sur la source Zone-Téléchargement . Ce qui rend impossible le lancement de la lecture vidéo.

Systeme utilisé : Android

Derniere version de Kodi utilisé (17.6)
Version Vstream 0.6.2

Merci pour votre boulot les gars, tellement pratique ce Vstream !

**Comment by Arias800** [comment]
Merci d'avoir respecter cette nouvelle règle tu a bien remplis le formulaire ^^ 
Je confirme il y a un correction a faire je m'en occupe ^^

**Comment by Arias800** [comment]
Corriger ^^

**Comment by LordVenom** [comment]
Bonjour,

@Arias800 a corriger sur la bêta, mais malheureusement il n'y auras pas de mise a jour avant la sortie de la 0.6.3.Donc soit tu fait un copie colle du fichier soit tu devras patienter.

Si tu est motivé pour la premier option pense a lire le https://github.com/Kodi-vStream/venom-xbmc-addons/wiki qui devrais te donner quel indication précieuse.

**Comment by camelone** [comment]
Il s'agit juste du ficher zone_telechargement_ws.py?

**Comment by camelone** [comment]
Parce que chez moi ça ne fonctionne pas. Je ne vois même plus zone_telechargement dans les sources. J'ai remarqué aussi hier, qu'ils ont changé l'adresse du site dl-protect... https://www.dl-protect1.com

**Comment by Arias800** [comment]
Alors si le fichier a disparu c'est que tu a eu un problème lors de la copie ressaye en le copiant de la  https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/ddf9602cb056936421b886d32967f87db50bbf18/plugin.video.vstream/resources/sites/zone_telechargement_ws.py
Pour le changement de nom de dl-protect ça ne pose pas de problème car vstream le récupère de manière dynamique ^^

**Comment by R4g3-79** [comment]
Merci résolu pour moi grace au dernier message d' Arias800 :)

Systeme utilisé : Android
Derniere version de Kodi utilisé (17.6)
Version Vstream 0.6.2

Continuez comme ça, vous faites un super taf !!!!

**Comment by KiliK150** [comment]
Fichier ZIP : 
 []https://uptobox.com/umz0cluiu2ev(url)
