### ISSUE TITLE
Problème de lenteur démarrage vidéo

### ISSUE THREAD

**Issue by nore77** [Kodi-vStream/venom-xbmc-addons#2140]
Salut à tous,

-Bug constaté:
Lancement des vidéos Vstream de plus en plus long Vstream Uptobox/uptostream.
Reset, désinstaller réinstaller tout essayé
Les vidéos se lancent toutes au bout de 2/3 min environ alors qu'avant c'était casi instantanée...
Test identique à une autre adresse fibre et résultats identiques.

Aucun problème sur une autre box très peu utilisée avec les mêmes config sur le même réseau

+Compte Uptobox premium utilisé
+Sources utilisés ddl Island et Zone T
-Os: Androïd 7 (box) et 8 ( Smartphone)
-Appareil : box beelink gt1 ultimate / Huawei mate 9
-Kodi: 17.6
-Vstream : 0.6.2

J'espère avoir bien complété le formulaire cette fois ci...

Merci et bonne soirée

**Comment by LordVenom** [comment]
Bonjour, quand je lis ça : 

`Aucun problème sur une autre box très peu utilisée avec les mêmes config sur le même réseau`

Je me doute que ça vient de ta box et pas de vStream ou y a un truc que j'ai pas compris.

**Comment by TmpName** [comment]
Essaye avec un navigateur integre a la box sans passer par vstream.

**Comment by lebigboss** [comment]
J'ai une GT1 ultimate et j'ai exactement le même problème

**Comment by lebigboss** [comment]
Ha bah je crois que....
Je viens d'installé la bêta et ça va vachement plus vite

**Comment by nore77** [comment]
Bizarre... Bon je vais essayer avec la bêta pour voir et vous dis si ça fonctionne!!!

**Comment by LordVenom** [comment]
Tu nous dit ? ou c'est un secret XD

**Comment by nore77** [comment]
Sorry, je suis en vacances et j'ai pas tjs accès à la fibre pour tester...
Pareil pour la bêta !! C'est tjrs aussi long juste à charger en uptostream 😐😐😐
J'ai tt formaté et le problème persiste 😶😶😶

**Comment by nore77** [comment]
Problème réglé ! J'ai démarré en recovery et ai fait un wipe de tout... Après réinstallations tout fonctionne nickel comme avant...
