### ISSUE TITLE
Pas de iframe dans le code source

### ISSUE THREAD

**Issue by valas69** [Kodi-vStream/venom-xbmc-addons#2141]
Bonjour,
Je bloque actuellement sur un truc, il n'y pas de lien de video dans le code source du site:
http://www.mondedescartoons.fr/atvo-s7-e03/
Pourtant, y'a une bien une vidéo (netu).
Si vous pouviez m'aider ce serait formidable ^^
Et merci pour votre gros taff 🥇 :D

**Comment by Arias800** [comment]
Il faut que tu récupère ce liens https://h_q_tv/player/hash.php?hash=222229232246222229245213222244264244194271217271255 car ensuite les script de netu s’occupe de tout le reste d’après ce que j'ai compris ^^

**Comment by valas69** [comment]
Merci de ta réponse, effectivement c'est bien ça mais sauf que le fichier est introuvable..
Du coup, j'ai un peu chercher dans le code source et je trouve ça:

> %3c%73%63%72%69%70%74%3e%0a%76%61%72%20%6f%75%74%65%72%57%69%64%74%68%20%3d%20%77%69%6e%64%6f%77%2e%6f%75%74%65%72%57%69%64%74%68%7c%7c%77%69%6e%64%6f%77%2e%69%6e%6e%65%72%57%69%64%74%68%3b%0a%69%66%28%6f%75%74%65%72%57%69%64%74%68%20%3e%20%31%29%7b%0a%20%20%20%20%76%61%72%20%6e%65%74%75%5f%70%6c%61%79%65%72%5f%64%61%74%61%73%20%3d%20%7b%27%76%69%64%27%3a%27%32%36%31%32%32%31%32%32%37%32%34%30%32%34%31%32%34%35%32%31%33%32%37%33%32%34%33%32%35%36%32%36%37%32%36%30%31%39%34%32%37%31%32%31%37%32%37%31%32%35%35%27%2c%27%68%61%73%68%5f%66%72%6f%6d%27%3a%27%38%65%62%63%61%30%34%65%32%33%66%39%65%35%61%62%30%36%34%37%64%64%33%30%39%39%62%33%32%65%33%35%27%20%20%7d%3b%0a%7d%0a%3c%2f%73%63%72%69%70%74%3e

Je le décode puis je trouve du code:
`<script>
var outerWidth = window.outerWidth||window.innerWidth;
if(outerWidth > 1){
    var netu_player_datas = {'vid':'261221227240241245213273243256267260194271217271255','hash_from':'8ebca04e23f9e5ab0647dd3099b32e35'  };
}
</script>`
Si j'entre les ref dans "http://hqq.tv/watch_video.php?v=" j'obtiens un bouton watch video qui mène à rien...
Que faire ?

**Comment by Arias800** [comment]
Après je sais pas car je connais pas bien le code de netu mais si je me fit au code normalement http://h_q.tv/player/hash.php?hash= est remplacer par http://h_q.tv/player/embed_player.php?vid= ensuite on récupère le truc coder a la fin de la page on le décode ... Donc a mon avis si tu donne juste ce liens a vstream ça devrais marcher : https://h_q_tv/player/hash.php?hash=222229232246222229245213222244264244194271217271255 ^^

**Comment by valas69** [comment]
Ok ça marche, j'ai aussi oublier de preciser qu'avec un autre site où y'a netu ca marche

**Comment by TmpName** [comment]
Yep @Arias800 a raison, te prend pas la tete, je viens de verifier, si ton lien commence par
`h ttp://h qq.tv/player/hash.php?hash=`
C'est deja gere nativement par vstream, donc tu peut passer ce lien a la fonction hoster.

**Comment by Arias800** [comment]
C'est bizarre le replace ne se fait pas il reste  le /player/hash.php?hash= qui normalement devrait être remplacer par ça /player/embed_player.php?vid=  donc à mon avis ça vient de la ...

**Comment by valas69** [comment]
C'est résolu... 
Y'avait une personne qui avait fait un rapport, je pensais que la mise à jour serait faite au bout d'une semaine mais visiblement non...
Du coup j'ai fais la maj manuellement.
Je commençais à devenir fou avec ce netu.. xd
Merci les gars :D

**Comment by Arias800** [comment]
Oui parce que la prochaine mise à jour est actuellement en phase de test donc il y a plus de mise à jour des site et hoster pour le moment
