### ISSUE TITLE
IPTV ne fonctionne plus depuis quelques jours.

### ISSUE THREAD

**Issue by mike855** [Kodi-vStream/venom-xbmc-addons#2142]
Hello. 

Depuis quelque jour aucune chaîne IPTV ne fonctionne sur aucun de mes appareils.
Kodi 16 sur raspberry et Kodi 17 sur Android
Que ce soit depuis chez moi en fibre ou en 4G n'importe où.
Le chargement de fait mais il ne se passe rien.
Voici ce que je vois dans le log: 
ERROR: AttributeError: 'NoneType' object has no attribute 'recv'

**Comment by Arias800** [comment]
Depuis quelques catégorie TV du web ou liste site iptv ?

**Comment by mike855** [comment]
Depuis les listes iptv

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., juil. 2, 2018 à 17:47, Arias800<notifications@github.com> a écrit :   
Depuis quelques catégorie TV du web ou liste site iptv ?

**Comment by mike855** [comment]
Voici le log complet de Kodi 17 sur Android

https://www.dropbox.com/s/o3c4ulbqids350r/kodi.log?dl=0

**Comment by mike855** [comment]
Je suis chez orange, je les soupçonnés de faire du bridage pendant la coupe du monde

**Comment by Arias800** [comment]
Je suis chez orange aussi et j'ai pas vu trop de problème le truc c'est que c'est très compliqué de rendre stable ce genre de liste essaye avec la versions 0.63 de vstream pour voir https://github.com/Kodi-vStream/venom-xbmc-addons/releases/ .A tu f4mTester d'installer car après j'ai une petite idée doit ça peut venir

**Comment by valas69** [comment]
Voici les logs (La ligne 227 montre bien le lien): https://pastebin.com/L3zYWu76
Par contre c'est un gros bordel...
https://hqq.tv/player/hash.php?hash=261221227240241245213273243256267260194271217271255

**Comment by mike855** [comment]
Je vais tester la bêta. Ça marchait très bien et ça s'est arrêté du jour au lendemain, j'ai testé énormément de lien et aucun de marchent

**Comment by mike855** [comment]
Même problème avec la 0.6.3
J'ai bien f4mtester en 2.7.2.
La WebTV fonctionne
C'est vraiment d'un coup que ça arrêté de fonctionner. J'ai testé vite fait avec un vpn gratuit sur Android et c'est pareil

**Comment by Arias800** [comment]
Essaye avec cette version https://pastebin.com/raw/faHUgsG5 c'est le fichier freebox.py qu'il faut modifier ^^

**Comment by AizenKnower** [comment]
Moi jai pas de vpn
Jai kodi 18 du 2 juillet
Je peut dire que ca marche plutot bien

Je crois que le probleme c liste elle disparaîssent a une vitesse folle
Mais jai aussi remarquer une chose c les chaînes française car hier jai regarde unz chaine etranger et il y a pas eu de problemze
Ca a diffuser pendant 3heurs non stop et en FHD je crois que cetait bein sport

La je regarde unz chaine turc  TRT 4K ca freeze un peu mais c normal c du 

donc je me demande si pour une raison ou une autre les chains française sont bloqué ou bridé ? Je suis chez sfr Numericable 

Apres le temps que je passe a comprendre d ou viens le probleme je realise que c que les chaînes française qui deconne 

C juste une impression ou vous avez une playlist qui se lis sans souci si oui lequel svp

**Comment by mike855** [comment]
Il va falloir que je test avec le PC. Avec Android quand je copie le nouveau fichier que tu m'a envoyé il garde pas les sauts de lignes du coup ça marche pas lol

**Comment by Arias800** [comment]
Petit précision pour savoir si le liens et morts si dans les log il y a ERROR: AttributeError: 'NoneType' object has no attribute 'recv' ça veut dire que le liens est mort ^^
Personnellement j'utilise les liste World d'iptv Gratuit et ça passe plutôt bien après je fournit juste les liens et je fait mon maximum pour les rendre stable malheureusement je ne suis pas magicien donc au bout d'un moment j'arrive a la limite de ce que je peux faire c'est pour ça que je chercher des liste stable et surtout des liens qui change pour pas avoir 15 fois les même liens ^^

**Comment by mike855** [comment]
C'est bon ça marche avec le nouveau freebox.py. C'était quoi le problème?

**Comment by mike855** [comment]
Et merci au faite!

**Comment by Arias800** [comment]
C’était lier a la manière donc je lançais F4mTester (je le lançais pas comme un addon mais comme un liens normal) qui pour une raison inconnu ne marche pas chez toi ^^

**Comment by Arias800** [comment]
J'avais déjà essayer mais je n'étais toas arrivé car trop complexe à mettre en œuvre

**Comment by AizenKnower** [comment]
J'ai ecrit au gars et il s agit d'une écriture en regex (jy connait rien ) mais merci avoir essayé.
