### ISSUE TITLE
vstream version beta 0.6.3

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2143]
**Décrivez le bug**
mise a jour version beta

**Votre system**
 - OS: [Windows, Android] les deux 
-  Appareil pc ou boite android 
 - Version Kodi 17.6
- Version Vstream 0.6.3

le problème est la mise a jour en haut( en vert) ne se fait pas le plugin , je sais c est une version beta , juste au cas avant de sortir la version final . donc pour cela j ai effacé l ancien vstream au complet , ensuite fermer kodi , j ai été dans userdata/addon data/ effacer le plugin vstream , ensuite ouverture de kodi , installation de la version beta et en haut impossible de faire la mise a jour , pour le reste zone téléchargement parfait , free téléchargement parfait  ( merci pour avoir mis le captcha en gros) , film illimité super et meme plus beau qu avant , je m explique : j ai un compte premium donc je dois activer dans les réglages de vstream de passer par urlresolver , donc mes liens sur film illimité étaient juste en mauve , mais la j ai les deux sans avoir a désactiver mon url , photo en commentaire 
![vstream mise a jour](https://user-images.githubusercontent.com/40530593/42182638-70428ec8-7e2e-11e8-94bf-448645634c8b.png)

**Comment by KodiTopQuebec** [comment]
![film illimite](https://user-images.githubusercontent.com/40530593/42182686-9bc0f576-7e2e-11e8-8746-189d86e791b8.png)

**Comment by LordVenom** [comment]
Bonjour, Alors mauvaise idée de faire les mise a jour mais autant pour moi je l'est pas préciser.

Aprés y a un message d'erreur dans le log, je regarderai le code au cas ou un truc me saute au yeux.

**Comment by KodiTopQuebec** [comment]
Moi je suis très satisfait car vstream fonctionne mieux

Envoyé de mon iPhone

Le 2 juill. 2018 à 19:18, Lord Venom <notifications@github.com<mailto:notifications@github.com>> a écrit :


Bonjour, Alors mauvaise idée de faire les mise a jour mais autant pour moi je l'est pas préciser.

Aprés y a un message d'erreur dans le log, je regarderai le code au cas ou un truc me saute au yeux.

**Comment by AizenKnower** [comment]
Pour infos moi ce maj en vert me cause des soucis depuis bien avant ce 0.6.3 il faisait planter kodi et ou freeze et la il ne fonctionne plus.
D ailleur yavai un nouvel icone pour vstream et il es redevenu sur ancien icone
Moi je reinstall vstream de github si je vois cette maj vert et szs bugs

**Comment by LordVenom** [comment]
C'est pourtant écrit noir sur blanc.

```
Ne pas installer cette version développer si vous ne faite pas de rapport de bug bien remplis avec votre log.

Note : Ne faite pas la mise a jour auto (le menu en vert dans vStream)
```

Sans déconner dernier avertissement encore un (sa marche pas @AizenKnower  et je te BAN)

**Comment by AizenKnower** [comment]
@lordvenom

Faut pas le prendre mal je suis pas sur github 24hr sur 24
Je suis là pour aider et je precise les bugs que je signal ne sont pas la pour etre résolu mais pour rassurer la personne qu'elle est pas seule
Moi quand ca bug je reviens a la version qui marche et puis c'est tout
La mise a jour en vert je la fait plus du tout mais vu qu'une personne la faite je l'ai fait pour voir si je peut aider vu ma config
Pas la peine de s emballer car je jai aucun souci avec vstream ou kodi puisque je n utilise que 2 sources de streaming qui marche sans problème 

Bref jaidais juste cette personne a comprendre que le probleme nest pas la version 0.6.3 ni kodi 17 car ce souci existe avec 0.6.2 et kodi 18 

Voila donc désolé je nai nulle besoin de faire un rappory de bug car jai aucun bug et vu que la personne avant moi parle de ce bug ce serait plutôt  a lui de faire ce rapport

Donc c pas très objectif ni fairplay de demander a ce qui veule aider les autres dans leur bug a faire des rapports de bug a leur place tu ne crois pas?

**Comment by Arias800** [comment]
@LordVenom effectivement la il ne faisait pas un rapport il confirmais juste que lui aussi a ce bug par contre @AizenKnower si tu installe cette version il est demander de faire un rapport de bug et/ou avec les log ce qui pourrai aider pour corriger le bug de mise a jour ^^

**Comment by mike855** [comment]
Tiens c'est bizarre je croyais que c'était fini les maj. Ca fait plusieurs semaines que je ne les ais plus sur 3 appareils différents les mises à jours en vert

**Comment by Arias800** [comment]
Oui il n'y a plus de maj jusqu'a la sortie de la 0.63 mais le bouton apparait des fois (sur ma shield par exemple)

**Comment by LordVenom** [comment]
Dsl mais la :

`Pour infos moi ce maj en vert me cause des soucis depuis bien avant ce 0.6.3 il faisait planter kodi et ou freeze et la il ne fonctionne plus.`

Pour moi il fallait un rapport ou cherche soit même pour aider a avancer enfoncer une porte ouvert c'est pas très constructif.

Bref y a pas mort d'homme. Les mises a jour sur la 0.6.3 bêta sont inutile car ce sont tous les derniers fichiers.

Et qu'ont ce le dise je vais devenir chiant avec les rapports de bug et les messages hors sujet.La ça vire au forum et c'est chiant a gérer.

**Comment by Arias800** [comment]
Oui mais la il a importer une info intéressent car il a préciser que ça lui est arriver avec la version 0.6.2 et kodi 18 donc ce n'est pas totalement lier a la version 0.6.3 après si tu trouve ça pas intéressent comme information pourquoi pas mais il n'a pas totalement enfoncer une porte ouverte ^^

**Comment by AizenKnower** [comment]
Oui Arias800 pour le rapport de bug je suis ok mais jusqu a present jai pas de bug car tout fonctionne sinon on pire je remet la version  d avant.
Moi les seules bug c est si les lien Netu marche plus mais je repete je reinstalle la version derniere que jai en backup
Sinon ya les souci iptv mais ca na rien avoir avec vstream

Du coups je comprend pas trop la reaction de Lordvenom surtout que le bug est deja signalé donc c'est celui qui publie en premier le bug qui doit faire le rapport

Bref je manquerais pas de faire un rapport si vraiment je suis dans l impasse mais pour instant je ne suis que ton travail sur m iptv qui est excellent 

Moi aussi il apparait cet maj vert meme sur 0.6.3 mais je la fait pas.

**Comment by LordVenom** [comment]
@mike855 : oui y a plus de mise a jour, nous travaillons un peux sur le coeur de vStream donc patience.

**Comment by Arias800** [comment]
@AizenKnower en faite il a cru que tu répétait juste qu'il y avais un bug de mise a jour d’où le terme enfoncer une porte ouverte
Mais après je suis totalement d'accord avec les rapport de bug et j'ai même préciser dans ce poste https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2136 que tout les issue non conforme seront lock ^^

**Comment by AizenKnower** [comment]
Lordvenom justement si je fait pas de rapport c parsque c pas un bug chez moi
Je passe par télécharger le plugin sur github et je l install sur kodi et hop la maj vert disparait
Jai toujours proceder ainsi et c pourquoi quand ca bug je reinstall le zip que jai ddl
Tu conseille d eviter les maj vert mais c ske je faisait bien avant et comme dit Arias800 jenfonce pas une porte jen ferme une car c pas lier a 0.6.3 ni a kodi 
C juste un souci sur les dernier version beta de 0.6.2 et je suis pas la pour en faire un forum juste que si une personne a un souci je partage mon experience pour affiner la recherche de solution

**Comment by AizenKnower** [comment]
@Arias800 ok du coup maintenant je me demande si c pas mieux que je me tais et je laisse les autres galéré tout seul car si mes msg derangent je préfère éviter. 

Si ca peut contenter Lordvenom.

**Comment by LordVenom** [comment]
Ok ok j'ai compris ton point de vue, voici le mien dans c'est 15 commentaire y a un qu'un qui me dit qu'il y a un bug. Donc je vais regarder ne pas fermer le sujet pour me souvenir de ça et cherche dans les 15 message un truc qui m'avance mais y a pas.
