### ISSUE TITLE
Zone-Telechargement liens films en rouge

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#2146]
Bonjour a tous , voici ma config :

Systeme utilisé  Android  7.1 , sur box Alfawise H96 Pro+
Derniere version de Kodi utilisé (17.6)
Version Vstream 0.6.2

Depuis quelque temps  sur Zone-Telechargement , je ne peux plus lancer le streaming des films , ceux ci sont écrit en rouge  , que faire ?
Pourtant j'ai éffectué la dernière mise a jour du 06/07/2018 .

**Comment by Arias800** [comment]
Un exemple car chez moi ca marche ?

**Comment by Cikai91** [comment]
Bonjour, pareil, au lieu d’avoir les liens uptobox 1fichier premium ... il y a juste un lien en rouge.

**Comment by AizenKnower** [comment]
En rouge si je dis pas de bêtise c'est le nom du fichier meme si y a un icone de dossier a gauche si tu cliques tu auras rien.
Les liens pour regarder c'est juste en dessous du nom en rouge genre uptobox uploaded turbobit etc..
Puis un 2e fichier avec un nom diffèrent en rouge qui je repete de sert a rien de cliquer dessus mais en dessous tu a les liens uptobox uploaded turbobit etc a cliquer pout visionner

Donc si en dessous du nom en rouge ya pas de liens d hebergement alors c'est qu il y a pas de fichier hébergé et donc pas de visionnage possible

Comme le film the archer ou the last dragonslayer ya pas dd fichiers  mais war zone ou action ou vérité oui tu peux visionner en cliquant sur le site d hebergement 

J'espère que c'est bien ca ton souci car je pense que ce qui est en rouge ne sont pas cliquer mais uniquement les liens d hebergement uptobox  uploaded  turbobit  etc...car si ya pas ces liens alors pas de film et donc pas possible de visionner

**Comment by Cikai91** [comment]
Le problème c’est qu’il y a uniquement le lien en rouge et pas les autres

**Comment by Arias800** [comment]
Bizarre chez moi ça fonctionne ça doit être un truc bizarre de kodi 18

**Comment by Cikai91** [comment]
Moi je suis encore sous Kodi 17

**Comment by Arias800** [comment]
Je confirme sous Kodi 17 aucun problème chez moi vous devez avoir un fichier qui n'est pas à jour ^^

**Comment by FloRidaBzH** [comment]
Je confirme chez moi même problème et uniquement dans la partie films de ZT

**Comment by AizenKnower** [comment]
Arias800 et autres 

L'initiateur de ce sujet est aussi en kodi 17. 6 et 0.6.2 donc 2 version stable donc
Et moi en kodi 18 et jai testé 0.6.2 puis maj vert puis 0.6.3.1 puis et toujours aucune apparition des liens sur certains films comme last dragonslayer ou the archer mais qui sont bien sur la version web

**Comment by Arias800** [comment]
Ah oui il doit y avoir un autre disposition du site je regarde écarter demain

**Comment by ktm520** [comment]
Merci a tous pour vos réponses , avant les films se lançaient , peut etre un probleme de mise a jour ?

**Comment by LordVenom** [comment]
Chez moi pas de soucis !!! Comment ça. Ça n aide personne de dire ça !!!

**Comment by lebigboss** [comment]
Regarde ton URLRESOLVER
Si tu utilise un compte Premium essaye de te re-identifier

**Comment by Arias800** [comment]
D'après ce que j'ai vu les film où il n'y pas de qualité à coter du nom ne marche pas parcontre le autre marche normalement @ktm520

**Comment by ktm520** [comment]
Effectivement j'ai un compte premium , je vais voir cela , je vous tiens informé .

**Comment by tiger92150** [comment]
Bonjour, 
Avant la dernière mise à jour j'avais le même problème que toi et ça a été résolu en changeant manuellement le fichier "zone_telechargement_ws.py".
après la mise à jour, le même problème a réapparu exactement comme tu le décris .
donc j'ai rechangé le fichier "zone_telechargement_ws.py" une nouvelle fois parcelui que j'avais téléchargé auparavant et ça a résolu le problème de nouveau.
donc l'originedu problème c'est la dernière mise à jour.
jette un coup d'oeil sur cette issue pourn savoir plus :
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2139

**Comment by Arias800** [comment]
Nouvelle version de zt qui corrige la récupération des qualité et différente saison des séries ainsi que les site qui ne marchais pas comme the archer https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by ktm520** [comment]
Bonjour , comment injecton le fichier .py , désolé je commençe sur vstream .
Voici ma config : 
Systeme utilisé Android 7.1 , sur box Alfawise H96 Pro+
Derniere version de Kodi utilisé (17.6)
Version Vstream 0.6.2

**Comment by Arias800** [comment]
C'est expliquer dans le wiki https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Test-d-un-fichier-Beta

**Comment by ktm520** [comment]
Merci pour le retour , j'ai fait un modeste don par paypal hier , sans passé par mon compte GITHUB , et , je ne regrette pas , vous êtes au TOP .

**Comment by AizenKnower** [comment]
Merci pour la correction c'est revenu a la normal en verifiant les 2 examples archer et lastdragonslayer.

**Comment by AngelineL** [comment]
En copiant celui mis plus haut zone téléchargement disparaît chez moi.
Du coup j'ai testé la solution donnée par @Arias800  ici #2139 et les liens apparaissent de nouveau.

**Comment by ktm520** [comment]
Je suis vraiement une quiche , j'ai reussi a copier le fichier .py sur la clé usb , mais après je ne sais pas comment le remplacer ?
Faut il passer par KODI ?

**Comment by Arias800** [comment]
Non tu passe après un explorateur de fichiers es explorer, xplorer ...

**Comment by ktm520** [comment]
OK faut mette l'appli es explorer, xplorer ou autre , je pouvais chercher longtemps .
Je me pose la question , peux t'on mettre la plugin de la version beta ?

**Comment by Arias800** [comment]
Faut demander à @LordVenom pour savoir si ça en gêne pas par rapport au modif qu'il effectue

**Comment by ktm520** [comment]
MERCI a tous pour vos messages d'entraide , je vous tiens informé si problème .
Sinon j'avais trouvé cela :  

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/879

**Comment by LordVenom** [comment]
1 quoi me gêne ? XD

**Comment by Arias800** [comment]
Je reformule la questions : est ce que installer la bêta peut poser un problème par rapport au modification que tu a effectué depuis la dernière version de la 0.63 ? C'est pas compliquer comme question x)

**Comment by Cikai91** [comment]
Moi j’ai installé la bêta, chez moi ça fonctionne à nouveau.

**Comment by LordVenom** [comment]
J'ai fait un zip pour que les gens test mais et je dit bien MAIS c'est une bêta pour faire des tests et des rapports de bug.

**Comment by AngelineL** [comment]
Oui ça fonctionne plus. Ça refonctionne de nouveau avec l'ancien zone_telechargement_ws.pyo

**Comment by dbast57** [comment]
Bonjour,
Tout d’abord un grand merci à toute l'équipe pour votre fantastique travail
Je suis assez novice, j'utilise vstream 6.2 avec kodi 17.6 avec une shield tv
Ou dois je copier le code ?
Y a t il un fichier zip ?
Merci beaucoup pour votre aide
David

**Comment by LordVenom** [comment]
Bonjour,

Si tu est novice évite d'installer bêta, patience la version final arrive.

**Comment by dbast57** [comment]
Bonjour,

Merci à tous, je patiente

Bon courage

**Comment by LordVenom** [comment]
La version 0.6.4 est sortie Hier.
