### ISSUE TITLE
Sources Serie-streamingHD

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#2147]
edit par Venom: non pas d'insulte merci

**Comment by Arias800** [comment]
Chez moi ils sont tous down donc c'est normal ^^

**Comment by AizenKnower** [comment]
Je suis pas sur que mon bug est me meme que celui de #2148 vu que tu dis dans ton commentaire que son bug ne concerne que ddl island et ZT

**Comment by johngf** [comment]
Perso j'attend que @LordVenom ai finis ces modifs vu que pour l'instant il y a plus de maj
Et oui plusieurs site déconne.

**Comment by LordVenom** [comment]
Tu peux modif y a pas de soucis je tient à jour mon Git local.Les mises à jour sont relancer mais sur la beta uniquement. Encore quelque test et je pourrais sortir une version final.

**Comment by AizenKnower** [comment]
Jai mis a jour vstream avec les derniers modif mais en plus des sources cités yen a un autre qui est a un souci cinemaVf et voirfilms a disparu de la liste.
Je n'ai pas testé toutes les sources (uniquement ceux pour films et serie et animé ) donc a vérifier pour les autres. 

Pensez vous que c'est un souci des sites internets ou vstream peut régler le souci ? 

Merci e

**Comment by LordVenom** [comment]
C'est l'été beaucoup de site font le ménage, lien mort ou changement de style, ça n'a pas forcement a voir avec les changements dans le coeur. 

- Vous pouvez vérifier par vous même si le site fonctionne et nous le reporter.
- Vous pouvez vérifier sur les projets si ont l'a pas déjà signaler.
https://github.com/Kodi-vStream/venom-xbmc-addons/projects

**Comment by Arias800** [comment]
CinemaVf corriger https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/cinemavf.py

**Comment by LordVenom** [comment]
Sérieux tu voie le site Filmvostf online toi ? chez moi c'est off. Pour les autres j'ai perdu le fil. Donc patience verifier de temps en temps sur les projet voir les mises a jour. Note c'est pas parce-que c'est réparer qu'il y a une mise a jour dispo.

**Comment by johngf** [comment]
k streaming a été mis en trash par @razorex alors qu'il fonctionne

**Comment by LordVenom** [comment]
Surement HS quand il a tester. remet le au pire.

**Comment by AizenKnower** [comment]
@Lordvenom
Ya t il un souci avev moi car je trouve que tu es un peu agressif avec mes messages

Alors oui je vois filmvostf online avec le dernier film Titanium publié en 2014 donc a moins que c'est un autre site de meme nom oui il est en ligne  filmvostf.com

Si tu regards bien mon rapport de bug il est fait correctement non? Avec plus d infos sur les commits, vérification online et sur les projets donc oui je vérifie deja tous ca pour le rapport de bug 

On es pas la pour rapporter les bug en vue d'une correction ? Donc je rapporte qu il y a des bug sur la derniere maj ve qui veut pas dire que jattend une correction a chaque mise a jour

Filmzenstreaming.me fonctionne chez moi.

Bref vu que tu semble m avoir sur ton collimateur pour critiquer mes comms alors que j ai fait le rapport comme tu le souhaitais.

Je pense que c'est bon. Je ne ferai plus de rapport plus de messages. Tu ne verras plus de message de ma part puisque je pense que ma présence de dérange.

Je vous souhaites bonne vacance et je vous remercie quand même pour votre travail.

**Comment by razorex** [comment]
A bon dsl chez moi k-streaming fonctionne plus depuis plusieurs jours et même encore maintenant.
Papstream à une autre url mais plus que des films.

**Comment by AizenKnower** [comment]
@Lordvenom 

Jai dis je repondrais plus mais ton souci c'est ta façon de répondre qui est irrespectueux et agressive donc si ta un truc dit le mais poliment et avec respect car je vois aucune questions mais plutot des critique ou reproche donc oui ca me fait chier de repondre a ce genre de réponse sans respect de ta part

Donc oui j'arrête de poster car je veux bien etre gentil et rapport les bug mais pas pour quon me parle comme un chien 
Possible que tu te sent supérieur ou autoritaire car c est ton site ou ton addon

Mais je te conseil de répondre correctement si tu veux quon  t aide pour les bugs car je te signal que juska present personne ne ta rapporter tous ces bugs des sources si ce nest pas moi 

Chacun y va de son pti egoisme a signaler que la source quio utilise et jaurai pu faire pareil avec la seul source que j'utilise mais voila jai voulu rendre service en vérifiant chaque source pour vous faciliter la tâche  avec de precisions mais tu na aucun respect pour l'aide qu'on  t apporte

Donc je dirait plutot et jai l'impression que c est plutôt no rapport de bug qui te font chier et dans ce cas tu devrais clore ma section Issue ou eviter de repondre au message car tu fais pas avancer vstream

Deja que a chaque mise a jour ya de plus en plus de bug on respect votre travail et on  prend le temps de vous aider et tu viens nous manquer de respect pour une broutille sans nom.

Bref sois tu me répond correctement soit tu m.ignore mais je quitte ce site par parce que tu le demande ou me menace de bannir lol mais parce que ya plus de respect pour ceux qui vienne en aide

Deja la fois dernière tu ma critiquer a tord ta supprimer les messages je paris tu fera de meme ici sur ce abstiens toi de me repondre ou banni moi si tu veux mais c est mon choix de plus poster ici ny apporter mon aide

Sur ce ciao et evite de cracher ton venim sur ce qui prend du temps pour t aider .bye

**Comment by LordVenom** [comment]
Ok vas pour l’épanchement alors ! (pff ça me fatigue)

> Sérieux tu voie le site Filmvostf online toi ? chez moi c'est off. Pour les autres j'ai perdu le fil. Donc patience verifier de temps en temps sur les projet voir les mises a jour. Note c'est pas parce-que c'est réparer qu'il y a une mise a jour dispo.
> 
> Edit: j'ai verifier filmsenstreaming fonctionne chez moi ? plus d'info ?

Perso je voie 2 questions tu sais les ? (ok y a un ? en trop XD)

- Je te le re-dit puisque tu veut pas le croire quand tu fait des post qui m'agace je te le dit et je les supprimes.
- Les suppressions c'est juste du hors sujet ou inutile genre épanchement sur mon caractère.
- Les issues ont à fait les règles pas pour faire chier mais pour nous faciliter la vie.
- lol "tu te sens superieur" c'est vStream c'est pas une navette spatial et vue mon niveaux de français je serais bien con de me sentir supérieur à qui que ce soit.
- vStream c'est mon passe temps rien de plus qu'ont soit 2 ou 10 je continue moi.
- (Bon la je passe en mode j'abuse) : Si par contre tu est insatisfait de vStream (addon de merde qui bug tout le temps) je t'invite à le désinstaller et créer toi même ton addon sur ton temps libre je viendrais avec plaisir te faire un rapport de bug qui diras "ça ne marche pas".

Bon sur ce c'est messages m'ennuis et comme je t'avais prévenue tu seras BAN et c'est messages supprimer. Je te laisse le temps de lire ce beaux discourt qui ne mène a rien ne sert a rien mais bon tu avais envie de discuter...

Cordialement.

**Comment by AizenKnower** [comment]
Lordvenom 
Tu es pathétique tous ce que tu dis est pure orgueil de ta part mauvaise foi
Tu peut ban si tu veux jen ai rien a foutre mdr ta cru que je vais mourir pour commenter ici?

Les  posts qui t agace cest d rapport de bug ducon alors commence pas a critiquer ce que ta chialer l autre jour a avoir ok

Ban supprime je men fout mais ta un putain de probleme d orgueil ou de complexe car oui je dirais vstream merde un peu bcp et c ski te fait chier quon rapporte des bugs

Mais tu te defoule sur moi et si c un passe temps alors prend du recul et respect les personnes qui t aident

Deja la semaine dernière on ta dit ke a eu tord de m agresser et tu recommence

Mdr tu menace de ban et tu ose dire que c pas de la supériorité ? Fallais parler correctement et yaurai pas tout ces msg a la con mais je vais pas me taire devant un pti merdeux qui se sent pousser des couilles derriere son pc car il est dépassé par les bugs

Va trouver une autre personne a te defouler car jen ai rien a foutre de vstream puisque le.site que j'utilise est dispo en ligne et pas avec ton vstream

Jai juste voulu aider mais alors garde ton vstream et t ptite couille et ban mais je repete c moi qui m en vait car t trop con pour comprendre que ta merdais en parlant mal 

Ciao

**Comment by AizenKnower** [comment]
Jouer au billes ce qui reflete bien ta mentalité de gamin puérile pour pas reconnaître ton tord et tes menaces de ban.
Tu t es défoulé sur la mauvaise personne car vstream est inutile pour moi car je visionne le seul site de streaming en version web depuis quelque jour jai juste voulu apporter mon aide alors que ca ne me rapporte rien mais continue a traiter les gens commes ça tu verras plus personne t aidera.

Evite de répondre et ban car c'est le seul truc qui te redonnera un semblant de victoire sur une personne si ya que ca pour te sentir avoir raison

**Comment by LordVenom** [comment]
Bon je ferme ce post c'est partis n'importe comment et ont est pas plus avancer.
