### ISSUE TITLE
Recherche ZT out + DDL out  0.6.3+0.6.31

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2148]
**Décrivez le bug**
Impossible d'effectuer une recherche dans la source ZT (J'ai tapé "Trust" et "Atlanta" rien n'est afficher.)
Dans le menu DDL Island aucun lien ne s'affiche (ex: en cliquant dans Films SD ou Films HD aucun lien ne s'affiche) Mais le site est fonctionnel dans une page de recherche

**Votre system**
 - OS: Xbox One + Android Box  + Windows 10
-  Appareil (GT1 Ultimate)
 - Version Kodi  17.6 + 18.0 Alpha2 + 3
- Version Vstream Beta 0.6.3 + 0.6.31

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : Zone Téléchargement + DDL island
- Le titre du fim/serie  : Atlanta, Trust
- Le nom du host : Hors sujet

**Plus**
J'espère avoir tout fait dans les règles, si j'ai mal fait un truc dite le moi.
Et il y a aussi d'autres sites qui ont ce genre de problème mais j'ai préférer pas en demander trop.
Merci à vous

**Comment by Arias800** [comment]
Vérifie si les site que tu n'a pas mentionner n'apparaisse pas la https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2147 sinon dit et je regarde ^^

**Comment by lebigboss** [comment]
@Arias800 Oui pour les autres sites Down c'est bien ça, exactement celà
Donc là ça ne concerne que ZT et DDL

**Comment by Arias800** [comment]
Je m'occupe de Zt et de DDL ^^

**Comment by Arias800** [comment]
DDL corriger sur le github

**Comment by AizenKnower** [comment]
J'ai pas mis ddl island car la catégorie s'ouvre mais aucun fichier pour la version 0.6.3.2

**Comment by Arias800** [comment]
Oui mais du coup je viens de corriger ça ^^

**Comment by AizenKnower** [comment]
Ddl et zt corrigé ? Il faut voir si ce problème de recherche n'est pas egalement dans les autres sources

**Comment by Arias800** [comment]
DDL de corriger et zt j'ai corriger le regex qui récupère les info de la page de recherche mais il y a une modif a faire pour le next page mais je sais pas comment faire du coup j'ai besoin d'un peux d'aide ^^

**Comment by lebigboss** [comment]
Maintenant il y'a un autre problème sur ZT. Dans la catégorie Films HD ça n'affiche aucun lien.
Exemple dans les derniers films HD genre Sans Un Bruit 1080p tu clique sur n'importe quel version et il y'a aucun lien

**Comment by arzaz** [comment]
Je confirme aucun lien ne s'affiche.

**Comment by AizenKnower** [comment]
Pareil pour cinemaVF
Et voirfilms a disparu de la liste des sources

**Comment by vstreamkodi** [comment]
A tester https://uptobox.com/r1xwdzlnc3fq

**Comment by Arias800** [comment]
Ils ont un code qui change la ça devrais être bon : https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by lebigboss** [comment]
la mise à jour viens de sortir merci.
Zt fonctionne normalement  et DDL maintenant affiche les liens mais pas les fichiers.
