### ISSUE TITLE
Mise à jour impossible

### ISSUE THREAD

**Issue by Benian86** [Kodi-vStream/venom-xbmc-addons#2151]
Bonjour, est ce normal qu'avec le repository 0.0.3, je n'arrive pas à obtenir les mises à jour supérieur à la 0.6.2?

J'ai dut aller chercher moi même la 0.6.4 pour régler mes bugs.

**Comment by LordVenom** [comment]
Depuis le repos la mise à jour automatique devrais ce faire. Je vais vérifier merci

**Comment by LordVenom** [comment]
Bonsoir,

Sur mon ordi la mise a jour c'est faite tard ce soir 21h/22h, Kodi ne vérifier pas les mise a jour régulièrement.

**Comment by Benian86** [comment]
Ok. Je surveillerait pour la suite
