### ISSUE TITLE
Proposition de sites pour ajouter sources

### ISSUE THREAD

**Issue by adsav1** [Kodi-vStream/venom-xbmc-addons#2152]
Bonsoir
Je vous propose diférents sites pour ajouter les sources dans VStream. 
J'ai essayé moi même de les ajouter en modifiant le fichier Python, mais je n'ai que le nom du site dans les sources de VStream et quand je clique dessus je n'ai aucun contenu.

htt p://ww w.french-stream.co
htt p://filmcomplet.la/films-en-streaming.html
h ttp://streamelite.net/
h ttp://film2018.cinemay.com/films/

**Comment by LordVenom** [comment]
Bonsoir,

Mauvaise rubrique j'ai copier ton post ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1971
