### ISSUE TITLE
Zone Telechargement ne se lance pas

### ISSUE THREAD

**Issue by adsav1** [Kodi-vStream/venom-xbmc-addons#2153]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.
J'ai bien accès à la source Zone Téléchargement  sur Vstream mais quand je clique pour explorer 1 catégorie il ne se passe rien
**Votre system**
 - OS: [Windows, Android] Android
-  Appareil [nvidia shield, Ultra] Mbox TSX10008
 - Version Kodi  [16.17.18]
- Version Vstream 0.64

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site Zone Tel
- Le titre du fim/serie Tous
- Le nom du host (openload/vidzi) Tous

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by lebigboss** [comment]
Essaye un nettoyage du cache

**Comment by adsav1** [comment]
Apparement ils viennent encore de changer l'adresse du site : 
https://zone-telechargement1.ws/

**Comment by lebigboss** [comment]
Ça fonctionne sur vstream
Ça doit juste être une redirection d'un nom de domaine

**Comment by Arias800** [comment]
De tout façon les changement d'url ne dérange plus vstream pour zt ^^

**Comment by adsav1** [comment]
Bonne nouvelle :)

**Comment by adsav1** [comment]
Vu que le nettoyage du cache à rien changé voici mon fichier log de Kodi
https://transfernow.net/617xh4a20wc5

**Comment by Arias800** [comment]
Il y a une erreur ssl `URLError: <urlopen error [Errno 1] _ssl.c:480: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>` tu a une version  de kodi inférieur a kodi 17 ?

**Comment by Arias800** [comment]
Dans le fichier de zone-telechargement à la ligne URL_MAIN remplace https par http pour voir

**Comment by adsav1** [comment]
Je veux bien essayer mais vraiment pas sûr que ça va changer quelque chose.

**Comment by Arias800** [comment]
Une fois il y avais eu un bug ssl justement lier a zt et c’était la solution après est ce que ça va marcher cette fois je sais pas ^^

**Comment by adsav1** [comment]
Bon on y ai presque cette fois ci je vois bien tout le répertoire du site ZT  dans l'interface de Vstream mais quand je lance un flux j'ai un message d'erreur  
Voilà le nouveau log
http://www.sendbox.fr/8b2dbb472d131103/1531347302665_kodi.log

**Comment by Arias800** [comment]
Toujours des erreur de ssl faut que je remplace tout les https par des http et apres ca devrait etre bon ^^

**Comment by Arias800** [comment]
Essaye cette version du fichier https://pastebin.com/raw/Knnndf8e (tu a juste a copier collez) normalement ça devrait être mieux par contre désactive le debug de Kodi parce que c'est juste illisible x)

**Comment by adsav1** [comment]
Encore merci pour ton aide précieuse et tes réponses rapides

**Comment by adsav1** [comment]
Bon je viens d'essayer la dernière version du fichier python on y ai pas encore ^^ 

Dernier fichier log :
http://www.sendbox.fr/e3f7bc0e1ae6ff5e/1531424884838_kodi.log

Décidément ce site nous donne du fil à retordre

**Comment by adsav1** [comment]
Ah, c'est sûrement parceque le site est instable en ce moment.
On verra bien quand tout redeviendra à la normale.

**Comment by Arias800** [comment]
Il a jamais été vraiment stable mais bon x)

**Comment by Arias800** [comment]
Ressaye avec celui-la normalement ça devrait être bon : https://pastebin.com/Knnndf8e

**Comment by adsav1** [comment]
Encore merci m'sieur

**Comment by Arias800** [comment]
Tu me remerciera quand ça fonctionnera :p

**Comment by BENJI97200** [comment]
Tjrs pas de solution pour Zt svp?

**Comment by adsav1** [comment]
Bon je viens d'essayer le dernier fichier mais c'est encore pire je vois même plus la source Zone_téléchargement  dans Vstream

**Comment by johngf** [comment]
@adsav1 #2164

**Comment by rod93** [comment]
pareil zt ne se lance plus

**Comment by BENJI97200** [comment]
Pour moi aussi

**Comment by rod93** [comment]
Hourra ça remarche tout seul

**Comment by rod93** [comment]
Salut plus rien ne s’affiche dans zt suite mise à jour en 065

**Comment by BENJI97200** [comment]
@rod93 ....il faut changer l adresse Ds zt....https://ww2.zone-telechargement1.ws 
Avec cette adresse fonctionne pour moi

**Comment by rod93** [comment]
super merci ca fonctionne

**Comment by johngf** [comment]
meme site suite #2192
