### ISSUE TITLE
Dépendances non satisfaites 

### ISSUE THREAD

**Issue by thorgal-06** [Kodi-vStream/venom-xbmc-addons#2155]
**Décrivez le bug**
Lors de la mise a jour vers la version 0.6.4 de Vstream message d'Erreur : dépendances non satisfaites
donc mise a jour impossible même par fichier zip
**Votre system**
 - OS: [Windows 7]
-  
 - Version Kodi  Gotham
- Version Vstream 0.6.2

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Arias800** [comment]
Il nous faut les log pour savoir d'où vient le problème

**Comment by TmpName** [comment]
Regarde dans tes logs si tu voit pas quelle dependance est manquante, je crois que ca s'affiche.

**Comment by thorgal-06** [comment]
[xbmc.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/2180945/xbmc.log)

Voila pour les log 

Cordialement

**Comment by TmpName** [comment]
Alors deja, je te proposerait de tout desisntaller/supprimer les fichier a la main et re installer proprement. Pourquoi ? Ben par exemple "Universal - An Addons Toolkit for XBMC" qui est typiquement le genre d'addon an e pas mettre et qui n'est plus mit  a jour depuis plusieurs années (si quelqu'un a vu une version plus recente ?, mais deja XMBC ne s'apelle plus comme ca depuis longtemps).

>> [PLUGIN] Vstream: SQL ERROR INSERT
Supprime les databases, il ya une option dans vstream.

Tu regardes regulierement des series americaines en VO ? > script.tv.show.next.aired

Kodi 13 n'est plus trop supporte (on est quand meme a la V17) , ici tu as la liste des dependance, avoir celle que tu as ou pas.
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Liste-des-d%C3%A9pendances

```
                                              File "H:\Programmes\Gotham\XBMC\portable_data\addons\script.common.plugin.cache/lib\StorageServer.py", line 263, in run
                                                if self.xbmcvfs.exists(self.socket):
                                            TypeError: argument "path" for method "XBMCAddon::xbmcvfs::exists" must be unicode or str
                                            -->End of Python script error report<--

Et c'est justement une des dependances.
```

**Comment by thorgal-06** [comment]
Bonjour ,
je viens d'installer une version plus récente de Kodi "jarvis"
et donc j'ai pu mettre à jour Vstream
Merci de votre soutien
