### ISSUE TITLE
Pb de lecture vidéo sur ZT

### ISSUE THREAD

**Issue by R4g3-79** [Kodi-vStream/venom-xbmc-addons#2156]
Décrivez le bug
Depuis aujourd'hui quand on lance un film via uptobox, le mode premium 'authentification réussi" n'envoie plus la video en direct mais renvoie la fenêtre 'Select Quality' du mode Uptostream.  Puis la vidéo ne se lance pas.

Votre system

    OS: [Android]
    Appareil Nvidia shield
    Version Kodi [17.6]
    Version Vstream [0.6.4]

Nous devons le reproduire
Pour cela il nous faut:

    Le nom du site : [zone telechargement]
    Le titre du fim/serie : tous les films 720p,1080p et 4K
    Le nom du host : [uptobox]

Log

Image

Plus

**Comment by LordVenom** [comment]
Bonjour,

Je vais regarder, mais je ne pourrais pas reproduire le bug puisque je n'est pas de premium.
