### ISSUE TITLE
Pas de captcha DDL Island

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2157]
Décrivez le bug
Dans la section Films HD de DDL ou dans Series HD  quand on clique on clic sur une jaquette ça ouvre le lien mais quand on choisi le film ou l'épisode ça n'affiche aucun lien et aucun Captcha

Votre system

OS: Xbox One + Android Box + Windows 10
Appareil (GT1 Ultimate)
Version Kodi 17.6 + 18.0 Alpha2 + 3
Version Vstream 0.6.4

Le nom du site :  DDL Island
Plus

J'espère avoir était clair. 
J'ai essayé en allant directement dans l'URL d'un fichier pour ouvrir avec le captcha mais 
Le site utilise une serrure a coulisse et qui est toujours présente

**Comment by LordVenom** [comment]
Le sélecteur bug chez eux pour le moment pas de solution.

**Comment by adsav1** [comment]
LordVenom au lieu de clore mon topic sur ZT dites moi comment uploader mon fichier log de Kodi sur le bon site et ré ouvrez le svp sinon je vais devoir refaire un topic pour ZT
