### ISSUE TITLE
base64 entre les fonctions

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#2159]
Donc au cas ou @LordVenom ou @TmpName saurait pourquoi le fait de passer une url avec du code base64 entre showlinks(addlink) et showhoster enleve le signe + et rend le decodage hs 
exemple: 
de showlinks addlinks: `AmcWeXsbOzpeaW1+IAoG00oUFmcCHBRganB7O0VifjZ4wQ4+dBsocdNqNTZgaw==` 
vers showhoster : `AmcWeXsbOzpeaW1 IAoG00oUFmcCHBRganB7O0VifjZ4wQ4 dBsocdNqNTZgaw==` 
les 2 + sont effacés
j'ai d'abord cru que c'était VSlog mais en faite non pareil avec addTV

**Comment by TmpName** [comment]
Ben c'est au niveau du passage de parametre, mais en fait pour une url ca change rien
```

 VSlog(sUrl)   
oRequestHandler = cRequestHandler(sUrl)
```
donne en log
```
18:27:22.377 T:1660  NOTICE: 	[PLUGIN] Vstream: AmcWeXsbOzpeaW1 IAoG00oUFmcCHBRganB7O0VifjZ4wQ4 dBsocdNqNTZgaw==
18:27:22.378 T:1660  NOTICE: 	[PLUGIN] Vstream: could not load site: cinemavf error: unknown url type: AmcWeXsbOzpeaW1+IAoG00oUFmcCHBRganB7O0VifjZ4wQ4+dBsocdNqNTZgaw==
```

En debug, y a des espaces, mais en url teste les + sont de retour.

Je pense que le plus simple c'est d'utiliser replace juste avnt le decage base64.

Et il y a un urllib.unquote_plus(sParamValue) dans la fonction cInputParameterHandler.getValue() qui remplace les espaces par des +. Present aussi dans cOutputParameterHandler.

**Comment by johngf** [comment]
mais le truc c'est que je dois décodé l'url base64 dans sHowhoster avec un décode (code Js en python) et qu'il me faut les + donc a part replace ou décodé en base64 dans showlink je vais test

**Comment by Arias800** [comment]
Si tu veux utiliser replace sur un truc coder en base64 c'est pas une bonne idée car ça peut poser problème pendant le décodage

**Comment by johngf** [comment]
ça fonctionne mais je me demande si urllib unquote enlève seulement les + ou autres choses

**Comment by TmpName** [comment]
Du coup tu as fait comment ?
Moi j'aurais juste fait un replace juste avant le decodage, vu que je ne pense qu'il y a d'autre espace dans l'url a part la partie en base64 ?

**Comment by johngf** [comment]
j'ai replace + par plus et ensuite l'inverse dans showhoster
