### ISSUE TITLE
Fonction de recherche Zone-Telechargement ne marche pas

### ISSUE THREAD

**Issue by mannou78** [Kodi-vStream/venom-xbmc-addons#2160]
Bonjour,

Lorsque j<essaie de recherche un film ou une serie dans zone-telechargement aucun resultat n<est retourne. Il semble que la fonction de recherche ne marche plus 

Encore merci pour le super boulot

 - OS:Librelec
-  Appareil India
 - Version Kodi  17
- Version Vstream: 0.6.4

**Comment by doberberto** [comment]
Hey !! Même problème mais je ne comprend pas comment résoudre le problème.... Je suis sur Xbox one ! Bises et merci pour tout !

**Comment by mannou78** [comment]
Navre, je viens de re-tester et le probleme n'est pas encore resolu.

La recherche affiche encore le message en rouge Aucune Information

Encore Merci

**Comment by BENJI97200** [comment]
Bjr et vous arrivez a avoir les liens sur zt...moi non ca m affiche aucune information.....

**Comment by BENJI97200** [comment]
Une solution svp?merci

**Comment by BENJI97200** [comment]
Fonctionne de temps en temps....et apres plus rien

**Comment by ktm520** [comment]
J'ai l'impression que c'est lié a l'activité du site , actuellement accès impossible , donc aucun lien n'apparait ,  comme hier il y avait un message , comme quoi ZT avait été piraté https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2164 , je pense que cela a une concéquence sur les liens .

**Comment by ktm520** [comment]
J'y comprends plus rien le site est de nouveau accessible .

**Comment by Arias800** [comment]
Comme jai dit dans un autre piste il teste une nouvelle protection ce qui Fiat que le site fait n'importe quoi donc je ne peux rien n'y fait il faut patienter
