### ISSUE TITLE
apple tv 4k 11.0 vstream zone de telechargement video 4k problem

### ISSUE THREAD

**Issue by surfrdm** [Kodi-vStream/venom-xbmc-addons#2162]
**Décrivez le bug**
after the nitotv  jailbreak of apple tv 4k 11.0 i installed kodi 17.6-5, the problem is  with the video 4k in vstream addon: white and black video and video  playback hangs or bug;
on the other hand on pc there is no problem, internet 100 Mb
thank you

**Votre system**
 - OS:11.0
-  Appareil apple tv 4k
 - Version Kodi  17.6-5
- Version Vstream dernière mise a jour

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site zone de telechargement
- Le titre du fim/serie  Tomb Raider
- Le nom du host 1fichier

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by lebigboss** [comment]
Not a problem of Vstream but of kodi settings

**Comment by LordVenom** [comment]
Alors perso si je post sur un forum anglais je parle anglais mais ici c'est français donc un effort ou un traducteur merci.

**Comment by surfrdm** [comment]
ok merci 
bien noté

**Comment by TmpName** [comment]
Tu as essaye de lire une video sur un disque local avec kodi ? en 4 k si possible.

**Comment by BENJI97200** [comment]
Bjr , mm avec la fibre 100 Mbps, film 4k sur Zt saccade enormement(compte uptobox) ....une solution SVP???

**Comment by LordVenom** [comment]
Tu peux avoir le débit que tu veut le serveur derrière ne suis pas peux être en mode payant et encore j'ai un doute.

**Comment by LordVenom** [comment]
D'aprés une petite recherche google : 

Le Full-HD à 28 Mbit/s en 50p  (format courant aujourd'hui) c'est autour de  12 Go pour une heure
Le 4k(UHD) à 100 Mbit/s en 25p c'est autour de 42 Go pour une heure

**Comment by BENJI97200** [comment]
LordVenom ....merci pour ta reponse

**Comment by BENJI97200** [comment]
Vraiment merci ....
