### ISSUE TITLE
Problème avec Kaydo 

### ISSUE THREAD

**Issue by helpmoi** [Kodi-vStream/venom-xbmc-addons#2163]
Bonsoir,
Est-ce que le mise à jour avait pour but de régler les soucis avec les sites ? 
Grâce à la mise à jour j'arrive à accéder aux films du site Kaydo. Mais lorsque je sélectionne la qualité du film (sd ou hd). Il ne se passe strictement rien. J'ai essayé d'ouvrir les films via leurs site, ça marche...

Appareil : android box.
Version Vstream: la dernière 
Version kodi: la dernière

**Comment by LordVenom** [comment]
Bonsoir, post mal remplie. sujet fermer.

**Comment by TmpName** [comment]
Lol.
Sinonn je viens de tester, pas vu de prbs de mon cote encore.
