### ISSUE TITLE
Zone téléchargement piraté

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#2164]
Bonjour a tous , en me rendant sur le site Zone téléchargement , il y a le message suivant : 

Désolé, une erreur s'est produite.

Nous sommes piratés , par des Hacker !

Fait attention n'entre pas au site Zone(S)-Telechargement1.com

ce lui le Hacker , Zone(s) a la fin "S" n'entre pas ce dangereux !!!

Nous Travaillons pour résoudre la problème .

**Comment by ktm520** [comment]
Tout a l'air d'etre revenu a la normal .

**Comment by BENJI97200** [comment]
Bjr , site Zt : aucune information

**Comment by BENJI97200** [comment]
J ai trouvé, il y avait 2 zt ds le fichier site....

**Comment by BENJI97200** [comment]
Ca fonctionné 1mn et maintenant aucune information

**Comment by Arias800** [comment]
Oui mais il y a un truc bizarre qui rends le site instable donc je peux rien faire pour le moment

**Comment by ktm520** [comment]
Je me demande si les problèmes rencontrés sur Zone téléchargement , seraient lié au piratage du site ??

**Comment by Arias800** [comment]
Je sais pas c'est une protection quelconque mais quoi je suis pas ^^

**Comment by ktm520** [comment]
Bonjour , voici ce que j'ai trouvé 

![zt](https://user-images.githubusercontent.com/34879102/42721258-10a7119c-8738-11e8-8d0c-dcf54ea4a723.jpg)

**Comment by Arias800** [comment]
De tout façon le "vraie" zt enfin celui qui est apparut le plus vite après la fermeture du précédent est entrain de mourir totalement x)

**Comment by AzeRim** [comment]
Avez-vous une solution pour ZT avec vStream (on a aucune information concernant les vidéos)? Est-ce que le problème provient d'une ressource ou du fichier zone_telechargement_ws.py à modifier? On arrive pourtant sans problème à obtenir les liens avec un navigateur web sur http://zone-telechargement1.ws

**Comment by lebigboss** [comment]
Pourtant je suis sur le site là et il est ultra réactif 
c'est le zt qui fini par 1.ws

**Comment by Arias800** [comment]
Bon bah il est revenu entre temps ^^

**Comment by BENJI97200** [comment]
Bjr a tous ...le site Zt fonctionne sur Kodi???

**Comment by Arias800** [comment]
Ça fonctionne pour les série par contre pour les film ça merde un peu je cherche pourquoi

**Comment by BENJI97200** [comment]
@Arias800 ....pour moi le site ne se lance pas....une solution STP?   (Shield TV, kodi 17.6, vstream 0.6.4)

**Comment by Arias800** [comment]
Tu copie et colle ça dans le fichier de zone-telechargement https://pastebin.com/raw/Knnndf8e

**Comment by BENJI97200** [comment]
@Arias800 ..Il se trouve ou le fichier zt? Tu peux m indiquer le chemin a suivre STP, desolé je debute....

**Comment by Arias800** [comment]
Android/data/org.xbmc.kodi/files/.kodi/addon/plugin.video.vstream/ressources/site/zone_telechargement

**Comment by BENJI97200** [comment]
Quand j arrive ds site ...il y a 2 fichiers zt (py et pyo) et tous les autres sites , dc j ai collé le fichier text dedans , j ai testé et tjrs impossible d ouvrir zt sur kodi.......

**Comment by BENJI97200** [comment]
@Arias800...Quand j arrive ds site ...il y a 2 fichiers zt (py et pyo) et tous les autres sites , dc j ai collé le fichier text dedans , j ai testé et tjrs impossible d ouvrir zt sur kodi.......

**Comment by yas06** [comment]
Salut c le fichier py que tu doit modifier

**Comment by yas06** [comment]
Salut Arias g tester les série ça passe je vois les lien mais les film non, je vois pas ou ça bloque dans la récup des liens je vais essayer quand même merci de votre énorme boulot les gars

**Comment by Arias800** [comment]
Oui je suis au courant du bug des film je regarderai demain

**Comment by BENJI97200** [comment]
@yas06 ....je dois le modifier c est dire??? Merci de ton aide

**Comment by ethanael83** [comment]
Merci Arias et toute l'équipe pour votre travail et votre réactivité !

**Comment by mannou78** [comment]
Merci Aria et toute l'équipe !

**Comment by johngf** [comment]
testé avec ce fichier pour avoir accès aux liens [ici](https://github.com/johngf/test/blob/master/zone_telechargement_ws.py)
clic droit sur raw enregistrer sous vers \plugin.video.vstream\resources\sites\
ou clic sur raw et copier coller le contenu
le bug était a la ligne 485.

**Comment by AzeRim** [comment]
Merci à votre équipe. ça refonctionne avec cette modif.

**Comment by ethanael83** [comment]
Ça fonctionne merci, mais les liens uptobox ne s'affichent plus correctement. Plus précisément, il propose le choix de la résolution comme uptostream, le problème est que la qualité n'est pas du tout la même.
Je ne sais plus quelle est la modif à faire dans le fichier py pour cela

**Comment by johngf** [comment]
Ça n'a rien à voir avec zt lire issue #2154

**Comment by hylliotv** [comment]
fonctionelle 👍 🥇  merci

**Comment by hylliotv** [comment]
Par contre je vous ens tout juste de remarquer que la next page embarque pas suis je le seul ? 
La première page est nickel avec la ligne 485 modif mais série et movie accès à seulement la
Première page 🤔

**Comment by AzeRim** [comment]
J'ai le même problème. On a accès  qu'à la première page. La page NEXT ne fonctionne pas. Y a encore un autre bug sur le fichier.

**Comment by AzeRim** [comment]
Url encore modifié
https://pastebin.com/raw/DUWDMVHa

**Comment by BENJI97200** [comment]
Bjr...zt ne fonctionne plus ...qqu un a ce probleme?

**Comment by BENJI97200** [comment]
@AzeRim ....comment je fais pour changer l URL ds vstream STP ???

**Comment by AzeRim** [comment]
Tu modifies la ligne URL_MAIN du fichier \plugin.video.vstream\resources\sites\zone_telechargement_ws.py

**Comment by BENJI97200** [comment]
@AzeRim....merci

**Comment by BENJI97200** [comment]
@AzeRim....desolé mais je debute,  tu le modifies avec un logiciel ou...?

**Comment by BENJI97200** [comment]
C bon merci j ai reussi

**Comment by lebigboss** [comment]
Apparemment ça refonctionne même dans maj
Sauf les movies

**Comment by TmpName** [comment]
Trop de posts ouvert en ce moment pour ce site.
