### ISSUE TITLE
Connexion impossible (errno -2)

### ISSUE THREAD

**Issue by bast69** [Kodi-vStream/venom-xbmc-addons#2165]
**Décrivez le bug**
Dès que je souhaite accéder à n'importe quelles sections, j'obtiens le message d'erreur "connexion impossible (errno -2) name or service not

**Votre system**
 - OS: Libreelec
-  Appareil Raspberry pi 3
 - Version Kodi  [17.6]
- Version Vstream 0.6.4

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
Sous libreelec, je n'ai pas la même arborescence que dans linux, je ne trouve pas le fichier de log. Si quelqu'un a une idée.
Quand je clique sur upload log, j'ai le message d'erreur et rien ne se passe, du coup je n'ai pas les informations.

**Image**
si besoin je peux faire la capture d'écran du message d'erreur

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Arias800** [comment]
Les log tu peux allez les chercher manuellement et nous les mettre sur un site comme pastebin voila les différent chemin ou tu pourra les trouver : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log après oui la capture d’écran de l’écran peux être utile

**Comment by bast69** [comment]
Je n'ai pas ce répertoire, j'ai tout fait...

**Comment by johngf** [comment]
J'ai remarqué  que cette erreur arrive quand  tu n'es pas connecté à Internet
Ou une requête est bloqué ou ne fonctionne pas sur ta machine??? google analylic pour les statistiques ???

**Comment by johngf** [comment]
bah pour les stats de frequentation des sites perso je le désactive ouvre le fichier default.py de vstream et met un '#' devant les ligne 5 et 72
et re-test

**Comment by bast69** [comment]
@johngf tu utilises quoi ? sur le raspberry pi 3 ça fonctionne bien et niveau rapidité c'est fluide. Je me suis connecter en ssh sur ma machine j'ai modifié le fichier, le problème n'est plus présent.

**Comment by johngf** [comment]
j'avais test le raspberry 2 avec des distribs basé sur kodi xbian, raspbmc etc... et je trouvé ça trop lent 
du coup j'ai acheté un nuc intel avec archlinux de base qui démarre direct sur kodi

**Comment by bast69** [comment]
@johngf ahok, c'est pas le même tarif non plus :)
