### ISSUE TITLE
Problème avec Kaydo ! (Version 2)

### ISSUE THREAD

**Issue by helpmoi** [Kodi-vStream/venom-xbmc-addons#2167]
Décrivez le bug :
Impossible d'ouvrir les films de Kaydo.

Votre system

OS: Android (android box et Samsung galaxy s8+)
Version Kodi 17.6
Version Vstream 0.6.4

Nous devons le reproduire
Pour cela il nous faut:

Le nom du site :Kaydo
Le titre du fim/serie : Peut importe le film
Le nom du host (openload/vidzi): Lien rapide

Log:
Voici le lien du log: 

https://drive.google.com/file/d/18CQb_ONzMCH59qb49TqmBS-OwoBPVGgE/view?usp=drivesdk

Image
/

**Comment by johngf** [comment]
déjà /plugin.video.vstream/resources/lib/runscript.py", line 166, in main
 request = urllib2.Request(cUrl,urllib.urlencode(post_data),headers)
 NameError: global name 'urllib' is not defined

**Comment by johngf** [comment]
j'ai mis a jour runscript.py pour que upload log fonctionne mais pour kay do je peux rien faire pas accès au site

**Comment by helpmoi** [comment]
Ok merci pour la mise à jour. Je vais attendre TmpName ou LordVenom pour Kaydo...

**Comment by helpmoi** [comment]
Comment mon système pourrait ne pas le lire ? Je viens de l'essayer également sur mon pc sans résultat...

**Comment by LordVenom** [comment]
Bon j'ai acces en ce moment , je regarde demain a priori les regex ont changer.

**Comment by TmpName** [comment]
Non plus, tjours pas d'acces.

**Comment by helpmoi** [comment]
Mince c'était un des meilleur site proposant du hd avec un lien qui s'ouvre direct :(
