### ISSUE TITLE
Impossible de faire la mise a jour 0.6.4 sur xbox

### ISSUE THREAD

**Issue by doberberto** [Kodi-vStream/venom-xbmc-addons#2168]
Décrivez le bug
Quand je veux mettre a jour en 0.6.4 (la première ligne avant la fonction recherche) j'ai une erreur de retournée. (Erreur connection impossible erreur 404... Et je vois pas la suite. 

Votre Log:
`10:17:08.139 T:547470472256  NOTICE: 	[PLUGIN] Vstream: Erreur: Connexion Impossible (404),https://api.github.com/repos/Kodi-vStream/venom-xbmc-addons/compare/0.6.4...`

https://1fichier.com/?18ld1t0m6dt5y6x17ctv

OS: windows ui
Appareil Xbox one Fat
Version Kodi [18 alpha3]
Version Vstream [0.6.4]

Merci encore pour votre travail fantastique continuez comme ca !!! Bises

**Comment by AzeRim** [comment]
J'ai le même problème pour la mise à jour des sites. Je suis sur android samsung s7 kodi 17.6 vstream 0.6.4.

**Comment by doberberto** [comment]
D'accord. J'attends votre retour alors !! :)

**Comment by LordVenom** [comment]
Non mais toi c'est pas le même soucis  que @AzeRim Erreur connection impossible erreur 404. c'est une erreur de connection mais comme tu n'a pas fournis ton log je sais pas de ou.

**Comment by doberberto** [comment]
Oui mais je peux récupérer le log sur Xbox one???

**Comment by LordVenom** [comment]
Je croie que le system de log et buguer installe un addon en plus genre Log Viewer.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils 

Mais ton message n'est pas clair tu ne peux pas passer de la version Bêta 0.6.3 a la version 0.6.4 final par les mise a jour automatique tu doit prendre le zip ou l'installer depuis le repository.

**Comment by doberberto** [comment]
Ca ne fonctionne pas quand je fais upload Kofi.log. j'ai bien active les notices de log, mais ca veut pas upload le log...

**Comment by LordVenom** [comment]
D'ou l'installation de Log Viewer.

**Comment by doberberto** [comment]
Je n'arrive pas a upload le log... :pensive: :cry:

**Comment by AzeRim** [comment]
J'ai bien le message Erreur connection impossible erreur 404 quand je tente la mise à jour sites avec la version 0.6.4. Quand je remet la version 0.6.2, il n'y a pas de problème de mise à jour sites. Je pensais que le bug est lié à la version 0.6.4. Je ne sais faire de mode debug mais je peux te fournir mes fichiers home.pyo et about.pyo si ça t'intéresse.

**Comment by doberberto** [comment]
Et danson log j'ai la même erreur que toi azerim

**Comment by LordVenom** [comment]
@AzeRim si tu voie erreur 404 dans le log il devrais avoir une ligne avec l'url qui ne passe pas,

- Active les notice de log (paramètre de vStream/Outil) 
- Lance la mise a jour, ensuite regarde le log et transmet nous la ligne en question.

**Comment by LordVenom** [comment]
Ok je vous est fait un zip dans le repo de vstream.ga installer plugin.video.vstream-0.6.4-update-test et dite moi.

**Comment by doberberto** [comment]
Je ne le trouve pas dans le repo le fichier ZIP. Il faut un temps peut être?

**Comment by doberberto** [comment]
Bon, j'ai toujours la ligne de mise a jour disponible qui apparait au dessus de la fonction recherche, mais sans le numéro de maj entre parenthèse. J'essaie de faire la maj des liens, mais cette fois pas de message d'erreur, mais pas non plus de mise a jour des liens... Étrange...

**Comment by LordVenom** [comment]
Bon je vient de me motiver a faire un test sur ma xBox et la mise a jour fonctionne même sans le patch. 

- Désinstalle reinstall
- Sinon log car la je ne peux pas reproduire le bug.

**Comment by doberberto** [comment]
Desinstalle et réinstallé, pleins de messages d'erreur de partout, mise a jour passe toujours pas, mais je peux quand meme utiliser laddon. On va attendre la prochaine maj, tkt... Merci quand même d'avoir pris le temps. Je n'arrive pas a upload le log sur Xbox...

**Comment by LordVenom** [comment]
DSL mais les mises à jour ne changeront rien. J'ai pas de piste pour une modif donc ça vas rester comme ça.

**Comment by AzeRim** [comment]
Après installation du zip update-test, la mise à jour () n'a pas fonctionnée. Après suppression du cache, des données et désinstallation puis installation de kodi, repo 0.0.3 et zip update-test alors la mise à  jour (0.6.41) a fonctionnée.

**Comment by LordVenom** [comment]
Donc j'avais la bonne erreur, le paramètre qui sert a la mise a jour n'est pas initialiser, la mise a jour mensuelle corrigeras le bug. Pour les autres faite comme @AzeRim .

**Comment by doberberto** [comment]
Pour ma part, j'ai quitter et relancer Kodi, et tout est rentré dans l'ordre (après avoir désinstaller et réinstaller vstream). Merci encore ! Bon match cet après-midi !!!!!!
