### ISSUE TITLE
Télécharger

### ISSUE THREAD

**Issue by adsav1** [Kodi-vStream/venom-xbmc-addons#2169]
Décrivez le bug
Une description claire et concise de ce qu'est le bug.
J'aimerai savoir : comment télécharger une série en passant par Vstream? En effet,  cette fonction me serait utile assez régulièrement pour suivre la suite de certains épisodes quand je suis pas chez moi (quand je suis dans les transports pour aller au boulot par exemple)
Votre system

OS: [Windows, Android] Android
Appareil [nvidia shield, Ultra] Mbox TSX10008
Version Kodi [16.17.18]
Version Vstream 0.64
Nous devons le reproduire
Pour cela il nous faut:

Le nom du site Tous
Le titre du fim/serie Tous
Le nom du host (openload/vidzi) Tous
Log
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

Image
Si votre soucis est visuel faite une capture d’écran.

Plus
Ajoutez plus d'information sur le problème ici.

**Comment by Arias800** [comment]
Tu choisit quel l'hoster que tu veux et tu va dans le menu contextuel et tu a l'option télécharger

**Comment by adsav1** [comment]
Quand je choisis une série à partir de l'hoster je n'ai que les options suivantes :+1: 
Playlist
Marque-pages
Librairie
Marquer comme vu
Lire à partir de cet épisode
Ajouter aux favoris

**Comment by adsav1** [comment]
C'est quoi ce format de fichier? . flv?

**Comment by Arias800** [comment]
C'est quand vstream ne détecte pas le type de fichier que ça met en flv après je sais pas

**Comment by adsav1** [comment]
Chouètte, je viens de test, apparement ça marche aussi en changeant l'extension en .AVI: :)

**Comment by johngf** [comment]
@adsav1 .flv est un conteneur qui passe bien dans kodi. 
parfois tu auras l'option télécharger mais ça fonctionnera pas sur certain liens.
