### ISSUE TITLE
Ajout source Extreme Download

### ISSUE THREAD

**Issue by theminibergy** [Kodi-vStream/venom-xbmc-addons#2170]
salut, j'aimerais savoir s'il est possible d'ajouter la source https://www.extreme-d0wn.com/home.html dans les sources de vStream. C'est un peu comme ZT , mais fonctionnel.

Merci

**Comment by Arias800** [comment]
Lis le 2ème poste et la prochaine fois cherche dans les issue ouverte : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1971

**Comment by theminibergy** [comment]
ok désolé je vais le fermer alors
