### ISSUE TITLE
mise a jour 0.6.41 n'a pas fonctionné

### ISSUE THREAD

**Issue by ddav33** [Kodi-vStream/venom-xbmc-addons#2171]
Bonjour, j'attendais avec impatience cette mise a jour pour corriger zt et uptobox premium mais elle n'a pas fonctionné et ma notifié de zéro mise a jour après avoir clicqué dessus, que faire! 
Android 6
Kodi 17.6
Boitier tx7

**Comment by Arias800** [comment]
Essaye de faire la même chose que la : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2168

**Comment by AzeRim** [comment]
L'issue 2168 ne corrige pas ZT et uptobox premium mais corrige uniquement la mise à jour des sites.
L'issue 2164 corrige ZT (il faut attendre qu'il soit prise en comtpe).
L'issue 2154 corrige uptobox premium (il faut attendre la version 0.6.5). 
Il faut tous faire manuellement ou installe ce zip en attendant toutes les modif officielles https://1fichier.com/?39sclon6niu2bz4zu81x
Attention si tu fais la mise à jour site après installation de mon zip alors ZT ne fonctionnera plus.

**Comment by ddav33** [comment]
Oui bien sur et mon skin et dédié a zt lol !!

**Comment by Arias800** [comment]
Donc oui faut attendre la prochaine version ou installez le zip au dessus ^^

**Comment by ddav33** [comment]
OK j'essaie le ZIP alors sans mise a jour pour le moment !

**Comment by ddav33** [comment]
Le ZIP apporte pas grand chose sans uptobox effectivement on a accès a zt ou on peu voir les liens .. Merci quand même , je vais utilisé mon navigateur en attendant vous pouvez marqué résolu pour la mise a jour dans tout les cas 😉😴✔

**Comment by AzeRim** [comment]
C'est bizarre car mon zip corrige zt et uptobox premium

**Comment by ddav33** [comment]
Oui azerim uptobox fonctionne en direct je viens de m'en apercevoir après ton commentaire y a que sur uptostream que j'ai fichiers introuvables , c'est pas encore l'idéal pour ma connection en 720p mais ça dépanne ,merci bien l'ami😉

**Comment by Arias800** [comment]
Je viens de corriger uptostream il y a 2 heure https://github.com/Kodi-vStream/venom-xbmc-addons/commit/aa900c586254662e120d0a19c70fc5f8dcce415a :p

**Comment by ddav33** [comment]
Je sais pas si ça serai trop demander de l'avoir dans le ZIP , je sais pas ou peu pas modifié mon vstream sur androïde déjà tenté sans succès 😰😗😭😊

**Comment by Arias800** [comment]
Il y a un bouton pour télécharger la beta https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by Arias800** [comment]
ddl island toute la partie Dl protect j'ai finit mais faut juste séparer les hoster https://pastebin.com/tT8eK4RH ^^

**Comment by ddav33** [comment]
Merci arias tout refoncionne avec la bêta ✌☝😊

**Comment by AzeRim** [comment]
@Arias800 la page next de ZT ne fonctionne pas avec la beta. La modification de la ligne 254 oOutputParameterHandler.addParameter('siteUrl', sNextPage) par oOutputParameterHandler.addParameter('siteUrl', sNextPage.replace('https','http')) du zone_telechargement_ws.py semble résoudre ce bug.

**Comment by Arias800** [comment]
Oui c'est un probleme de ssl le truc c'est que le https va au bout d'un moment devenir obligatoire donc faut trouver autre chose ^^

**Comment by LordVenom** [comment]
La sélection ac3 / 720 et inutile puisque non fonctionnel.

**Comment by Arias800** [comment]
J'arrive pas a faire mieux si quelque peu jeter un oeil pour voir si il y a des amélioration a faire ^^ https://pastebin.com/tT8eK4RH

**Comment by TmpName** [comment]
Y a quoi qui marche pas ?

**Comment by Arias800** [comment]
Si tu parle de Dll island il y a une étape (celle avant les hoster qu'on doit pouvoir passez ) mais je n'y arrive pas

**Comment by LordVenom** [comment]
Ca et y a pas les liens de stream mais juste les uptos/filetruc/ect... c'est dommage.

**Comment by Arias800** [comment]
Oui mais de mémoire il n'y a jamais eu les liens de stream si ?

**Comment by TmpName** [comment]
Nope, je crois pas, y en a mais ca renvoit sur un autre site, c'est exactement les memes urls mais un hebergeur different.

A mon avis on doit pouvoir garger les regex, je teste pour voir.

Sinon, pour moi ca vaut pas le coup de te prendre la tete pr supprimer une etape, j'ai deja explique mes raisons pour ca.

**Comment by TmpName** [comment]
Bon j'ai commence a faire en sorte que ca gere Strm+DL, par contre il reste a convertir le code de decoadage JS en python.
J'ai deja extrais le code il est a la fin du fichier, par contre quand j'ai vu la longueur, j'ai eu un coup de barre.

https://pastebin.com/31eY1sMY

**Comment by LordVenom** [comment]
Ben c'est ça oui y a deux choix soit prendre les streams sur DLL soit sur la redirection au plus court c'est pareil de toute façons.

**Comment by TmpName** [comment]
En fait je fait une modification d'url juste avant la fonction showhoster, j'ai teste vite fait mais ca a l'air bon.
Reste a convertir les fonctions, mais la ce soir j'ai plus le temps, apres j'ai jamais teste le site de streaming, je sais meme pas si il vaut le coup ?

**Comment by TmpName** [comment]
Bon en fait je viens de tester le site de streaming.
A part quelques lien openload, soit ca marche pas, soit le lien est mort, je pense pas que ca vaille la peine de se pencher dessus ?

**Comment by Arias800** [comment]
Personnellement je pense pas après faudra voir plus tard si par hasard c'est plus intéressent ^^

**Comment by TmpName** [comment]
Ben vu l'age du site, j y crois plus trop ^^

**Comment by Arias800** [comment]
On sais jamais x)

**Comment by LordVenom** [comment]
Ok toi qui voie.

**Comment by TmpName** [comment]
moi je ferais un rollback, en virant mes modifs, pas besoin d'un site bancale en plus, y en a deja assez a gerer.
