### ISSUE TITLE
Trakt et librarie

### ISSUE THREAD

**Issue by adulescente** [Kodi-vStream/venom-xbmc-addons#2172]
Bonjour!
Vous devez sûrement le savoir mais je suis curieuse de connaître ce qui arrive avec TRAKT a l'intérieur de vstream depuis quelques jours.... Aussi, le pourquoi nous ne pouvons plus ajouter d'élément a notre librairie kodi.

Merci beaucoup!
Je sais que vous travaillez très fort sur vStream. Et c'et grandement apprécié

Julie L
(La fatigante sur le groupe google+ Kodi québec)

**Comment by LordVenom** [comment]
Bonsoir, Effectivement on travail fort puisque tous le coeur de l'addon à etait modifier (même si personne n'a vue la différence :'( et plusieurs Sites/Hosts sont tomber mort en même temps. Bref dans tout ça j'avais pas connaissance d'un soucis avec Trakt et la librairie.

Note : Oui je voie qui sais, mais j'aurais pas dit fatigante mais pétillante :)

**Comment by adulescente** [comment]
Merciiiii :)))

Je pétille la.

**Comment by adulescente** [comment]
Et....
On se rends bien compte que vous travaillez beaucoup sur vStream dernièrement... Et puis, j'ai remarqué que votre logo était plus actuel, si ça peut consoler un peu.... Je ne suis pas allé fouillé dans les abysses de votre code mais bon.... Je sens bien qu'il y a du changement et vous deviez aussi bien sentir que vous êtes apprécié :))

**Comment by LordVenom** [comment]
Encore Merci. C'est Résolut pour trakt. fonctionnel à la prochaine mise a jour.

**Comment by vstreamman** [comment]
Pourquoi on met la source filmvf.org dans les source de vstream

**Comment by TmpName** [comment]
Je le vois pas ce site ?

**Comment by miniskull14** [comment]
bonjour, je voudrais vous signaler qu'on ne peut pas se connecter a Trakt après une fresh Install.
Je suis sur Raspberry Pie 3B+ avec OMSC et la dernière update de Vstream.

Y'a t'il une solution pour sauvegarder nos marques pages au cas ou on devrait réinstaller vstream, a part trakt?

(message plus personnelle , Un grand merci a vous pour ce boulot monumentale, je vous suit depuis le début

**Comment by LordVenom** [comment]
Bonjour,

- Librairie réparer.
- @vstreamman  je voie pas le rapport la hors sujet.
- @miniskull14 c'est le bug retourner. déjà réparer.
- Oui tu peux sauver les marques page. Vas voir cette vidéo ça seras plus simple.
https://www.youtube.com/watch?v=OGFwrqieXu8

**Comment by miniskull14** [comment]
Exactement ce que je cherchais, merci Ô Seigneur LordVenom.

Je n’utilise pas trackt (je suis plus TVShow Time mais n’intègre pas trakt) mais j’ai voulu essayer d’où la remontée d’info.
