### ISSUE TITLE
zone-telechargement1.com  changement d'adresse 

### ISSUE THREAD

**Issue by chaiba2006** [Kodi-vStream/venom-xbmc-addons#2174]
Bjr le site  Zone telechargement à arrêter de travailler encore une foi . Svp comment peut on changer l'adresse . J'ai remarquer que la nouvelle adresse c'est #https://zobi.zone-telechargement1.com#
J'ai
 kodi 17.6 
Android oreo 
Xiaomi mi3

**Comment by Arias800** [comment]
Ça ne pose pas de problème puisque vstream gèrent la redirection pour zt ^^

**Comment by chaiba2006** [comment]
Merci #Arias800 pr ta réponse rapide . Mais je sait pas j'arrive pas à accéder à Zone-telechargement sur kodi   . Je vais vérifier encore une foi merci bcp

**Comment by Arias800** [comment]
Apres c'est peut etre parce que tu a un fichier qui n'est pas a jour ^^

**Comment by chaiba2006** [comment]
Merci bcp Arias800 le problem c'est régler tu seul . C le site qui était out à midi.  Maintenant tt ds l'ordre merci bcp
