### ISSUE TITLE
Bonne nouvelle 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2175]
Extrême download on enlevé leurs captcha 

h ttp://ed-protect.org/gNKO voici un exemple maintenant on doit juste cliquer sur afficher les liens

**Comment by Arias800** [comment]
Et non ça ma tout l'air d’être la version invisible de recaptcha onSubmitCallbackInvisibleCaptcha je regarde plus en détaille au cas ou ^^

**Comment by Ovni-crea** [comment]
OK d'ailleurs j'ai mis à jour ton fichier avec chrome launcher pour extrême download  sur les fonction car certaines fonction de fonctionnait pas vue que vous avez modifié vstream

**Comment by Arias800** [comment]
Yep je viens de voir ca si tu la corriger c'est possible que tu me le passe ? (ca sera plus rapide ) ^^

**Comment by Ovni-crea** [comment]
OK je vérifie et je le termine si il reste des trucs

**Comment by Arias800** [comment]
Non mais au pire laisse je m'en occupe c'est pas grave ^^

**Comment by Ovni-crea** [comment]
Voilà https://pastebin.com/30U5gtM7

**Comment by Arias800** [comment]
Merci ^^

**Comment by Ovni-crea** [comment]
De rien

**Comment by Arias800** [comment]
Bon bah pour moi il y a recaptcha attends de voir si quelqu'un dit le contraire au cas ou ^^
Par contre tu te sert du truc un peux bizarre que j'ai fait avec chrome launcher ?

**Comment by TmpName** [comment]
Je viens de tester le premier lien, et j'ai eu le captcha

**Comment by Ovni-crea** [comment]
Oui je teste avec chrome launcher mais sur Android sa ouvre chrome mais voilà il faudrait qu'il a un système sur Android c'est dès que tu copie un lien http(s) kodi le détecte et ouvre le lien pour le lire

**Comment by johngf** [comment]
donc en faite c'est mort...
@Ovni-crea tu avait surement le cookie d'un captcha déja résolu dans ton navigateur quand tu as test et du coup ça fonctionné pour d'autre liens.

**Comment by Arias800** [comment]
Je regardait justement si il y avais pas moyens de faire ca pour le moment je n'ai pas trouver ^^ @Ovni-crea

**Comment by KaKi87** [comment]
Bonjour, je ne travaille pas sur votre projet, mais j'ai testé l'injection de cookie sur ED Protect, sans succès, probablement parce-que c'est Google qui gère les sessions, et non le site ED Protect lui-même.
Mis à part en passant par des plateformes payantes comme 2Captcha ou Death By Captcha qui emploient des gens juste pour résoudre des captchas (eh oui !), alors je ne vois aucune autre solution que d'adapter le logiciel client pour afficher le captcha et faire faire un clic authentique par l'utilisateur.

**Comment by TmpName** [comment]
Y a une histoire d'ip aussi, si le cookie a ete genere sur un autre ordi, ca ne marchera pas.
Pour les site comme 2captcha, ca ne marche que si tu fournis un proxy, vu que l'ip qui provoque la generation du cookie doit etre la meme que celle qui accede a la page.

**Comment by KaKi87** [comment]
En fait, j'ai testé sur le même poste, mais avec une session normale et une session privée.

**Comment by TmpName** [comment]
Mais c'est trop l'enfer leur captcha, ca devient de pire en pire, y a des fois ou il te faut attendre que les images changent pour recliquer, ca met 10 plombes.

Le cote image a cliquer c'est rien, on avait deja integre ca a vstream au debut, mais c'est le token genere en javascript qui devient hallucinant. Ca devient plus complique pour les humains, que les bots qui eux scriptent des automatismes sur navigateur.

Mais si tu cherches a eviter la navigateur, bonne chance ...

**Comment by KaKi87** [comment]
A priori, impossible. Y a même pas d'API Google pour ça. En revanche, il parait qu'ED Protect a une API...

**Comment by KaKi87** [comment]
Je vois que le logiciel JDownloader fait comme je disais : il affiche le captcha dans une page web

![2018-08-19 16_11_01-new captcha](https://user-images.githubusercontent.com/21284089/44309673-81ba6d80-a3ca-11e8-8f05-0ea3f87a0d77.png)

A priori, il suffit de copier le code `g-recaptcha` et l'URL de l'iframe contenant le captcha

![2018-08-19 16_12_02-devtools - ed-protect org_malu](https://user-images.githubusercontent.com/21284089/44309709-f55c7a80-a3ca-11e8-9328-d68668970891.png)

**Comment by TmpName** [comment]
Yep, mais le but c'est se passer justement de la page web.
@Arias800 a fait un code recement pour ce site en utlisant un navigateur https://github.com/Arias800/Vstream-extreme-down

Si tu veux voir comment est calcule le token de recaptcha https://github.com/toogle/InsideReCaptcha

**Comment by KaKi87** [comment]
Y aurait-il moyen d'avoir une description ou un schéma algorithmique du code d'Arias800 sur la partie qui concerne reCaptcha ? Merci !

**Comment by TmpName** [comment]
Aucun algoritme, pour le moment ca lance juste le captcha sur un navigateur, et c'est a toi de rettaper le lien sur vstream.
Mais si tu es motive, tu dois pouvoir "facillement" l'ameliorer, il suffirait de recuperer le cookie du navigateur dans Vstream, et dans ce cas la, ca "simplifi" la requete.
C'est la methode utilise par JDownloader.

Mais perso, moi j'ai pas le courage de me lancer la dedans, je prefere bannir les sites a recaptcha.

**Comment by KaKi87** [comment]
En fait, dans mon cas je ne peux rien bannir du tout ^^
Car mon projet est d'automatiser tout le processus :
1. Recherche
2. Sélection qualité
3. Sélection hébergeur
4. Débridage
5. Téléchargement
Le tout en n'utilisant que des services gratuits et redondants pour que ça soit accessible et viable :D
Et dans ce processus, les captchas, URL encodées et redirections, c'est pas ce qui manque 😂

**Comment by TmpName** [comment]
Ben le plus facile c'est les navigateurs automatises. Un vieux truc totallement depasse depuis mais qui t'inspirera peut etre http://scraping.pro/recaptcha-solve-selenium-python/.

En fait tu peut "programmer" ton navigateur, pour ouvrir la page, lancer le captcha, cliquer sur les case et obtenir le lien, ca c'est pas le pire, mais pour qu'il reconnaisse tout seul les bonnes vignettes, sans passer par un truc payant, la je vois pas ...

Le plus simple, change de site, ou de source pour tes liens, prend un truc sans captcha. Apres je crois que quand tu fais un captcha, tu es tranquille pour 2h (enfin ca depend des sites)

**Comment by KaKi87** [comment]
En fait je préfère un backend à base de requêtes. J'avais déjà tenté le coup de l'iframe une fois, mais c'est très chiant. A cette époque j'avais essayé ZT, mais la structure HTML de leurs pages est trop imprévisible, et y a des erreurs partout. ZT et ED sont les plus grands sites de DDL francophones, alors mon choix c'est automatiquement porté sur ED, qui est plus simple.

**Comment by TmpName** [comment]
Serieusement je suis en train de reflechir, mais y a pas de tempo sur leur site.
A ta place je ferais un bot pour recuperer tout leurs liens, et je me servirait de cette liste, plutot que de leur site.
Le premier lancement se ferait a la main avec captcha, les suivants avec cookie.

**Comment by KaKi87** [comment]
La récupération des liens se fait sur la base d'une recherche.
Mais alors quel est ce cookie ?

**Comment by TmpName** [comment]
cookie sur google pas le site en question, mais je peux pas te dire lequel, ca fait longtemps que j'ai laisse tomber recaptcha.

**Comment by Arias800** [comment]
Je crois que c'est sur un url de ce style le cookie : https://www._oogle.com/recaptcha/api2/userverify?k=6LeH9lwUAAAAAGgg9ZVf7yOm0zb0LlcSai8t8-2o

**Comment by KaKi87** [comment]
Ca c'est un paramètre de requête

**Comment by Arias800** [comment]
Oui je me suis tromper de liens sur celui la il y a un cookie : http_://www.go_gle.com/recaptcha/api2/reload?k=6LdyC2cUAAAAACGuDKpXeDorzUDWXmdqeg-xy696
Et le cookie ressemble a ça d’après ce site la : htt_s://recaptcha-demo.appspot.com/ : 
```
1P_JAR | 2018-08-21-15
-- | --
APISID | Sf0Ohl-u2lokJoWh/AMnpjjVCOIKm6B3re
CONSENT | YES+FR.fr+20161218-19-0
HSID | ACIb4J1euedIJfcbx
NID | 137=o6NNOleC9JFyp2-15rvXX_hnDTqKlH2WoXhlmmg8F71KLpBdJIl6v8FFGe8q6Px6pTdUf2SG8JfVPBxpQfF_KgYXRTHsWQD-fmcjhAsrmE0OJoAyPWuQmZKt-LgmFAwmy_Iu8Wis3dRJbtO_oP4RSGrRxmSmUPj6aW-18ufJxsmebaT_V84AEOVevZrf_qvreOoIyZGTIpv_qRHRsGDjkxLpLIa_w1zXZPlr8Q
OGP | -5061451:
SAPISID | Ol27tEETAMCzYeCq/AwBw_AXMK-1zYb_-H
SID | XwY609icpAAx_uREqD81GycvBPJXhCtj9NeMVznOrfYMFDdvWLsNhtvhjhPIxbn-rONt4g.
SIDCC | AGIhQKQuHjlgb9durTHYydaEU2_y6rra-ZWAF3Cd0HfVyuS_LA8SF-mwetA8F-5i2r_TQpyylA
SSID | AcyAPEw2NkenhmmBr

```

**Comment by KaKi87** [comment]
Je n'arrive pas à trouver ça

**Comment by TmpName** [comment]
Je sais pas quel navigateur tu utilises, mais testes avec firefox et la console reseau (outils/developpement web/reseaux)
Quand tu passes sur les liens google, tu vas avoir les cookies correspondant envoyes et recus.
