### ISSUE TITLE
Streamer directement un lien uptobox via uptostream ?! Possible ?

### ISSUE THREAD

**Issue by lofrez** [Kodi-vStream/venom-xbmc-addons#2176]
Salut à tous,

Je me pose une question depuis plusieurs jours, j'ai fais plusieurs tests... non concluants bien-sur :( c'est pourquoi je pose la question directement aux experts que vous êtes ;)

Imaginons qu'on me passe, ou que je trouve sur un site non référence dans Vstream, un lien uptobox (donc  par exemple au format : https://uptobox.com/blabla0123bla)

Est ce qu'il existe une possibilité de renseigner, ou de mettre cette URL Uptobox directement dans Vstream, qui me proposerait alors, en cliquant dessuis de lire la vidéo, de la même manière qu'il le propose lorsqu'on clique sur un lien dispo sur la source zone-telechargement par exemple.

Qu'en pensez vous ?

Merci pour votre aide

Kris

NB : mon système tourne sur Raspberry 3, libreelec + Vstrem

**Comment by Arias800** [comment]
Teste ça : https://pastebin.com/raw/jVTu7ThE enregistre (le nom doit être : hoster_direct.py ) ensuite mets le dans les site le nom c'est Hoster Direct et tu a juste a mettre le liens que tu recherche ^^

**Comment by lofrez** [comment]
Merci Arias800 pour tes réponses rapide, et ton petit fichier fait maison !
J'apprécie ton coup de main, et te rermercie pour le temps passé !

Je test ça demain sans faute, et reviendrais vers toi pour te tenir informé !

Encore merci

**Comment by lofrez** [comment]
Arias800, j'ai effectué un test ce matin (j'en ai profité pour me rajouter le fichier extrem-down.py ;)
Mais après redémarrage, la source "Hoster Direct" n’apparaît pas dans la liste (le site extrem-down par contre oui)
Ai-je mal fait quelque chose ?

Au besoin, je peux faire des essais plus poussé ce soir.

**Comment by Arias800** [comment]
Tiens je te passe le fichier : https://drive.google.com/open?id=1rGX__4KMi4Qect-D_uRW7qnr6nvk9tIY tu a juste a le mettre dans le dossier site ^^

**Comment by Pitipito** [comment]
@Arias800 En ce qui me concerne, cela fonctionne très bien, un grand merci.

**Comment by lofrez** [comment]
@Arias800 , je viens de coller ton fichier si gentiellement donné ;) et ça semble fonctionner.
Je le trouve bien dans mes "sources", mais actuellement, à l'heure ou je t'écris, les liens uptobox ne semblent pas passer ... mais cela n'a apparement rien à voir avec ton travail :)

Tu valides le lien, tu peux le sélectionner, tu peux valider que tu veux passer par uptostream, tu peux valider la qualité voulue, mais ensuite ça marque une erreur "le fichier n'a pas été trouvé".
J'ai fais des essais directement en sélectionnant une vidéo sur la source zone-telechargement, et c'est surement un problème qui concerne directement uptobox.com même :(

Quoi qu'il en soit, encore merci pour ton fichier.

J'ai juste une question un peu HS, ...

La source que tu m'avais donné à la base (https://pastebin.com/raw/jVTu7ThE) j'aurais dû la copier dans quoi ? 
Je te demande ça, parce que j'ai surement fait la bêtise de le copier dans le bloc note de Windows  ...
Et comme il me semble que le bloc note de Windows ne correspond pas au standard Linux, j'imagine que ça viens de là...

Merci

**Comment by Arias800** [comment]
Sublime Text , notepad ++ en autre ^^

**Comment by FredFrancisIT** [comment]
Hello !! Arias800 tu évoque un plugin qui permet d'envoyer les lien uptobox dans kodi ?? ca m'intéresse beaucoup, est-il partageable ? 
Merci pour tt ton taff en tout cas :-)

**Comment by FredFrancisIT** [comment]
Génial ca marche nickel .... sauf les liens uptobox, que se soit de manière classique ou avec ce plug j'ai des "fichiers introuvables" sur toutes tentatives. Je demandais le plugin justement pour voir si ca allait mieux marche.

**Comment by adsav1** [comment]
Idem

**Comment by Arias800** [comment]
Il me fraudai les log ^^

**Comment by lofrez** [comment]
@Arias800 mon problème décrit hier soir venait donc de là .... ce n'était pas un problème chez uptobox ....

J'ai suivi tes recommandations, à savoir : installer la dernière version de Vstream + réinstallé zone-telechargement.py & Hoster_direct.py... et ça fonctionne au poil !!! 😋 

Je ferai plus de test ce soir, mais il semble que les liens uptobox refonctionnent comme avant 💃

**Comment by adsav1** [comment]
Le fichier Hoster_direct.py se trouve ou SVP?

**Comment by Arias800** [comment]
Ici : https://drive.google.com/open?id=1rGX__4KMi4Qect-D_uRW7qnr6nvk9tIY

**Comment by adsav1** [comment]
Merci

**Comment by kenshiro000** [comment]
@kilik150 tu n'as pas besoin de modifier le fichier , hoster direct lit déjà ce type de fichier ( je pense qu'il lit tous types disponible dans le dossier "hoster").

@Arias800 serait-il possible de l'intégrer de définitivement à Vstream ? Parce que c'est vrai que c'est plutôt pratique ✌🏻️👍🏻
