### ISSUE TITLE
Erreur 404 

### ISSUE THREAD

**Issue by Funeoz** [Kodi-vStream/venom-xbmc-addons#2178]
Impossible de télécharger le zip pour le repository 0.0.3. Pourriez vous le remettre?

**Comment by Funeoz** [comment]
C'est bizarre. Depuis la partie repository avec les updates, j'appuyais sur le fichier ZIP et ça m'emmenait vers une erreur 404.

**Comment by Funeoz** [comment]
D'ailleurs, cette erreur 404 existe toujours:
https://imgur.com/a/wZtL9MW

**Comment by LordVenom** [comment]
Une indispo pendant quelque temps peux être je sais pas.
