### ISSUE TITLE
Sources «premium» via débrideur

### ISSUE THREAD

**Issue by Ambremont** [Kodi-vStream/venom-xbmc-addons#2179]
Je ne sais pas si je suis à la bonne place.
Ai activé URLResolver ds vStream et paramétré et autorisé mon débrideur ds URLResolver. Je ne vois pas les liens premiums dans vStream: quid?

**Comment by LordVenom** [comment]
Merci de lire https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2136

Sujet Fermer
