### ISSUE TITLE
Voir les sources

### ISSUE THREAD

**Issue by karim7878** [Kodi-vStream/venom-xbmc-addons#2181]
Bonjour,

Question sur une fonction que je ne trouve pas lors du'une recherche.
Est il possible de voir la liste des film (ex derniers ajouts HD) avec tout les sources incluses sans avoir a consulter source par source?
En gros je souhaites voir la liste des derniers ajouts de film sans avoir à parcourir chaque source.
Merci à vous. 

OS:Android
Appareil Xiaomi box
Version Kodi 17
Version Vstream: 0.6.4

**Comment by LordVenom** [comment]
Bonjour, Non c'est impossible.

**Comment by karim7878** [comment]
Ok merci.ce n’est pas une fonction primordiale qui est demandé je pourrais voir dans le code si cela est simple ou bien il y a déjà des difficultés?

**Comment by TmpName** [comment]
Le code est dispo, public et "free to use", pas de soucis de ce cote.
Mais par contre oui, ca va etre coton surtout sans modifier le mode de fonctionnement actuel, regardes comment fonctionne la recherche, c'est un peu ce que tu veux faire.
