### ISSUE TITLE
Nouvelle installation : Erreurs AttributeError

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#2182]
Bonjour,

Je viens d'installer OSMC 17.6 sur un RPI2.

Mais la nouvelle installation de VStream ne veux pas fonctionner et m'envoie plein de messages d'erreurs.

J'ai regardé les logs mais je n'y comprends rien: https://pastebin.com/xgLTqF0D

Toute aide serait la bienvenue.

Remerciements anticipés.

**Comment by Arias800** [comment]
En faite il y a qu'une seul erreur qui vient en boucle faut voir avec @LordVenom ou @TmpName

**Comment by johngf** [comment]
Problème  de base de donnée ou chemin vers la base de donnée 
Par contre tu parle de nouvelle installe mais tu as d'autre erreur qui provienne d'autre addon....

**Comment by TmpName** [comment]
Supprimes tes bases de données (de Vstream).
Il y en a une de corrompu, et elle ne sont regenrees que si elle n'existent pas deja. Il y a un outil pour ca dans la config de vstream.

**Comment by canopre** [comment]
Bonjour,

Merci pour votre réponse rapide.

J'ai utilisé l'outils Vstream pour supprimer les BD mais j'ai un message d'erreur à chaque tentative.

Et toujours la même erreur vstream;

https://pastebin.com/1zDQr378

Je comprends pas comment la BD peut-être corrompu après une installe tout neuve?

J'avais déjà le problème sur une "ancienne" installation alors j'ai tout recommencé mais sur du neuf : je comprends pas :(

**Comment by canopre** [comment]
Je viens de faire un nouvel essai sur une autre install et j'ai le même problème...
C'est de plus en plus compliqué d'installer Vstream.
Comme disait ma grand-mère : C'était mieux avant :)

**Comment by LordVenom** [comment]
Bonsoir, trouve .kodi/userdata/addon_data/plugin.video.vstream/vstream.db et supprime le regarde si il ce régénère bien.

Voir https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-vStream pour plus d'info sur l'emplacement dossier.

**Comment by canopre** [comment]
Comme indiqué + haut : c'est bien ce que j'ai fais...

Mais après le redémarrage : Vstream n'a pas re-créé ce fichier.

**Comment by LordVenom** [comment]
Hum.. tu peux teste db.py modifie la ligne 37

`if not xbmcvfs.exists(self.DB):`

par 

`if not xbmcvfs.exists(REALDB):`

**Comment by canopre** [comment]
Hello
Encore merci pour votre aide.
J'ai bien fait : sudo apt-get install sqlite3
Mais c'est toujours pareil.

https://pastebin.com/m3JJjRiA

**Comment by LordVenom** [comment]
Tu as modifier celon mon post que j'ai effacer puisque c'est pas la que ce creer le fichier mais bien via sqlite.

`Error Contents: ('expected an indented block', ('/home/osmc/.kodi/addons/plugin.video.vstream/resources/lib/db.py', 38, 0, 'if not xbmcvfs.exists(REALDB):\n'))`

remet 

`if not xbmcvfs.exists(self.DB)`

De plus je sais pas ce que tu utilise comme éditeur mais c'est pas bon indented block c'est une erreur d'espacement utilise un vrais editeur sublimetext, notepad++, visual studio code.

**Comment by canopre** [comment]
Merci pour ton aide.
Je comprends pas tout, j'essaye de suivre mais j'ai toujours la même erreur 
https://pastebin.com/zMiJXDyC

**Comment by LordVenom** [comment]
- Fait un print sqlite au dessous de l'init dans db.py

```
def __init__(self):

        print 'reponse sqlite %s' % sqlite

        try:
            #if not os.path.exists(self.cache):
            if not xbmcvfs.exists(self.DB):
```

Tu devrais avoir un object dans le log 

`reponse sqlite <module 'sqlite3.dbapi2' from '/usr/lib/python2.7/sqlite3/dbapi2.py'>`

**Comment by canopre** [comment]
Je suis pas sur d'avoir bien fait : 
https://pastebin.com/cK0AW1BG

Et voici une nouvelle fois mes logs :)
https://pastebin.com/rB6TRJYN

Et encore merci.

**Comment by LordVenom** [comment]
t' a pas le mode debug activer ?

**Comment by canopre** [comment]
sorry : je m'en occupe de suite

**Comment by LordVenom** [comment]
Le soucis c'est que c'est pas une install neuve ont voie bien 

```
repository repository.xbmc.org
repository repository.vstream
repository repository.xvbmc
repository repository.popcornmix
repository.aeon.nox.silvo
```

De plus c'est OMSC et j'arrive pas a savoir ce qu'il y a dedans c'est un forks de Kodi?, kodi avec un theme? aucune idée. Vire tous et test libreelec 10min l'installation je pense que tu est plus a ça prés.

**Comment by canopre** [comment]
pas de soucis chef ! Désolé et merci pour ton temps !

**Comment by LordVenom** [comment]
Non mais pas de souci, mais la ont nage dans le potage et j'ai pas moyen de tester et te dire a chaque etapes comment faire pour tester ça vas pas le faire. DSL et bon courage.

**Comment by canopre** [comment]
En attendant je suis retourné en 0.6.1 et tout est rentré dans l'ordre.
Je vais tenter un 0.6.2 qui marchait encore bien.
J'espère que je rate pas de super fonction mais avec les suivantes ça marche po chez moi :(

**Comment by LordVenom** [comment]
Ben voila ton dernier log te dit l'erreur

```
12:40:23.762 T:1378611968  NOTICE:  [PLUGIN] Vstream: SQLITE 3 as DB engine
12:40:23.814 T:1378611968  NOTICE:  [PLUGIN] Vstream: erreur: Impossible d ecrire sur /home/osmc/.kodi/userdata/addon_data/plugin.video.vstream/vstream.db
12:40:23.823 T:1378611968  NOTICE:  [PLUGIN] Vstream: erreur: Impossible de ce connecter sur /home/osmc/.kodi/userdata/addon_data/plugin.video.vstream/vstream.db
```

Test ce code a coller ligne 32  en dessous de dialog() et au dessus de _init_

```
    ####### news code testtt
    from sqlite3 import Error
    TEST = xbmc.translatePath("special://userdata/addon_data/plugin.video.vstream/vstream2.db").decode("utf-8")
    try:
        conn = sqlite.connect(TEST)
        print(sqlite.version)
    except Error as e:
        print(e)
    finally:
        conn.close()
    #######
```

Aprés soit tu as un fichier vstream2.db soit tu devrais avoir l'erreur dans le log pk le fichier ne ce créer pas. (mode debug activer)

**Comment by TmpName** [comment]
Impossible d'ecrire ? C'est pas encore un prb de droits ?

**Comment by LordVenom** [comment]
Ben c'est bizarre un problème de droit dans userdata normalement il a tous les privilèges.

**Comment by johngf** [comment]
si tu as un terminal vu que c'est basé sur linux  et si tu as un pseudo utilisateur je sais pas comment fonctionne osmc
tape sudo chown -R tonpseudo /home/osmc/
