### ISSUE TITLE
Streamer Vstream smarttv 

### ISSUE THREAD

**Issue by adsav1** [Kodi-vStream/venom-xbmc-addons#2183]
OS:Android
Appareil Galaxy S6
Version Kodi 17
Version Vstream: 0.6.5
Bonjour
J'ai une question sur Vstream.
Est il possible de streamer vers une Smarttv Samsung?

**Comment by LordVenom** [comment]
Bonjour,

vStream n'est pas Kodi, je ne sais pas ceux que ton installation peux gérer ou pas. Demande plutôt a Google.

**Comment by adsav1** [comment]
Déjà faiss , c'est pour ça que je demande ici

**Comment by adsav1** [comment]
Arias800? Help please?

**Comment by Arias800** [comment]
Une petite recherche sur internet m'informe que smart tv = tizen os et que c'est impossible d'utiliser kodi sur tizen ^^

**Comment by adsav1** [comment]
Et en utilisant un Addon sur Kodi pour relier les deux?

**Comment by Arias800** [comment]
bah euh pour diffuser kodi sur un autre support ça passe par une chromecast ou ce genre de chose je pense ^^

**Comment by adsav1** [comment]
Je cherche un plugin qui pourrait faire ce genre de chose comme on voit dans la vidéo 
https://www.youtube.com/watch?v=mQT1EIMBulQ

**Comment by Arias800** [comment]
Après si tu doit pouvoir en activant la fonction Web interface de kodi https://kodi.wiki/view/Web_interface et en te connectant via le navigateur de ta tele ^^

**Comment by johngf** [comment]
si je comprend bien de ton telephone tu veut envoyer la video sur ta télé ?
mais il y a une application genre remote desktop (bureau a distance) qui peut affiché le bureau de ton telephone ou tablette sur pc 
c'est peut etre possible avec ta TV je sais pas .
du coup tu lancerai la lecture sur ton tel et tu verra la video sur ta tv
jamais testé ce truc faut voir ... question avec l'économiseur d'écran est-ce que la TV devient noir aussi enfin...

**Comment by LordVenom** [comment]
tu lance le film puis pause et tu tape Y si t'a tv fait dlna/upnp normalement Kodi la voie.

**Comment by adsav1** [comment]
?

**Comment by LordVenom** [comment]
Donne l'info complète pour les autres merci

**Comment by adsav1** [comment]
Utiliser ce fichier : 
https://transfernow.net/89df17n1y9hd

**Comment by johngf** [comment]
@adsav1 le lien a expiré tu peux le re posté qu'on le garde au cas ou qqun en a besoin

**Comment by Starceleste02** [comment]
Bonjour
J ai kodi 17.6 et impossible d installer du dépôt vstream 0.6.5
Message erreur la dépendance de plugin vidéo YouTube 5.5 etc
Est ce que quelqu un aurait une solution à me propose
Sur tvbox mxg pro 4k
Merci beaucoup

**Comment by LordVenom** [comment]
Bonjour, 

La dernières version 0.6.6 n'a plus youtube comme dépendance ça devrais résoudre le soucis.

https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.6.6
