### ISSUE TITLE
disney hd

### ISSUE THREAD

**Issue by rod93** [Kodi-vStream/venom-xbmc-addons#2184]
bonjour plus de liens dans disney hd avez vous une solution merci

**Comment by LordVenom** [comment]
Bonjour, j'ai fait un test vite fait, fonctionne pour moi de plus Merci de lire : 

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2136

Sujet Fermé.

**Comment by johngf** [comment]
mis a jours les serie n'afficher rien
