### ISSUE TITLE
Gum gum streaming passe au legal

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2187]
Petit message pour prévenir que a partir de maintenant gum gum streaming utilise des lecteur légal (wakanim , crunchyroll quand ils ont la possibilité) de ce fait ces lecteur ne sont pas disponible sur vstream pour plus d'information je vous renvois sur le site ou tout est expliquer ht tps://gum-gum-streaming.com/pourquoi/

**Comment by TmpName** [comment]
Par contre c'est pas encore une majoritee, si ?
J'ai fais 2 tests et suis tombe sur rutube et opnload.

**Comment by Arias800** [comment]
C'est pour les anime licencier chez crunchyroll et wakanim au pif l'attaque des titans et black clover
