### ISSUE TITLE
Youtube erreur 403

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2191]
**Décrivez le bug**
Quand je veut lire une vidéo YouTube sa affiche erreur 403

**Votre system**
 - OS: [Android TV 8.0]
-  Appareil [Xiaomi Mi Box 3 international]
- Version de Kodi [17.6]
- Version de Vstream [0.6.51]

**Comment by Arias800** [comment]
Pour l'exemple sur liveset database -> genres musicaux -> acid ->Icey @Acid Test

**Comment by johngf** [comment]
si tu teste a partir de ton site musical assure toi déjà d'avoir finis ton code 
(c'est pas le cas de ce que j'ai pu voir ) et d'avoir un liens valide avant de posté une issue

**Comment by Ovni-crea** [comment]
Je viens de teste youtitou pour YouTube et sa vient de mon site les vidéos YouTube démarre sur youtitou et le lien que je viens de test était valide sur mon site donc sa doit venir de mon code

**Comment by Ovni-crea** [comment]
Par contre j ai tester soundcloud sur mon site et sa démarre bizarre

**Comment by Ovni-crea** [comment]
Bon dans le log c est marqué unsupported protocole

**Comment by TmpName** [comment]
Si tu lit les logs, tu as le lien que essaye de resoudre le resolver. Testes celui la.

**Comment by Ovni-crea** [comment]
https://pastebin.com/m6BjTL3f regarde j ai pris le lien de la vidéo dans le navigateur sa met erreur 403

**Comment by Ovni-crea** [comment]
J ai tester avec urlresolver sa marche donc c est bien youtube.py le problèmes

**Comment by johngf** [comment]
il faut savoir que certain lien youtube sont codé cipher
donne le liens de ta video

**Comment by Ovni-crea** [comment]
https://www.youtube.com/watch?v=IbtTbMfFm4A

**Comment by Ovni-crea** [comment]
OK tien je te donne le hoster de urlresolver pour YouTube on ne sait jamais :)
https://pastebin.com/HBBaS0Eg

**Comment by johngf** [comment]
non pas besoin c'est le site qui ne fait plus le taff il faut changer de site

**Comment by Ovni-crea** [comment]
A ok du coup mon site lui est nickel

**Comment by johngf** [comment]
je viens de le mettre a jour test le
