### ISSUE TITLE
Fonction de recherche zone téléchargement

### ISSUE THREAD

**Issue by Lolobeboy** [Kodi-vStream/venom-xbmc-addons#2192]
Bonjour la fonction de recherche de zone Téléchargement ne fonctionne plus pourtant hier soir, elle fonctionnait très bien. Merci
Votre system

    OS: android 5.1.1
    Appareil: Box android
    Version Kodi 17.6
    Version Vstream 0.6.5 -> 0.651

Nous devons le reproduire
Pour cela il nous faut:

    Le nom du site zone téléchargement
    Le titre du fim/serie dans l onglet ( the middle)
    Le nom du host (openload/vidzi) probleme est avant de choisir le serveur

Log
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://slexy.org/raw/s20c6ba8Q3?token=7cff21a09d4ef6d98e65d57d867c2266dff504719b17f0eb53e17c031538d100&ts=1532441990

(l'erreur se trouve à 16:15:57.117 T:24632)

Image
en commentaire

Plus
ouvir zone-téléchargement , allez à recherche et notez le titre du film et ensuite aucune recherche n'est effectué, il est juste affiché "no information" en rouge.

**Comment by Arias800** [comment]
Chez moi ça marche tu doit avoir le fichier zone téléchargement pas a jour : https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by TmpName** [comment]
@Arias800 est deja sur le coup, la derniere version fct.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2177#issuecomment-407115193

**Comment by Lolobeboy** [comment]
ok super, je vais testé ça de suite. merci

**Comment by BENJI97200** [comment]
Bjr ....Zt ne fonctionne plus....liens marqués en rouge...une solution svp?

**Comment by johngf** [comment]
@Arias800 test [ça](https://github.com/johngf/test/blob/master/zone_telechargement_ws.py)
une modif pour toujour avoir la bonne url main comme je n'utilise pas ce site j'ai pas tous testé

**Comment by Arias800** [comment]
Ca fonctionne je mets dans la beta

**Comment by Arias800** [comment]
Enfaite il y a le next page de la recherche qui ne fonctionne pas donc j’hésite a tout simplement enlever le next page pour la recherche car pas extrêmement utile et c'est le bazar a géré

**Comment by johngf** [comment]
Chez moi il fontionne

**Comment by Arias800** [comment]
Moi non ca me mets cette erreur :
`13:11:23.856 T:13540   ERROR:     raise ValueError, "unknown url type: %s" % self.__original
13:11:23.856 T:13540   ERROR: ValueError: unknown url type: index.php?`

**Comment by johngf** [comment]
reprend le et test je l'ai mis a jour

**Comment by BENJI97200** [comment]
Bsr,  quand je telecharge le fichier , il est en html....je le met ds site ,et la recherche ne fonctionne tjrs pas....une solution svp ???merci

**Comment by johngf** [comment]
@BENJI97200 
clic droit sur raw enregistrer sous vers >>/plugin.video.vstream/resources/sites
il va remplacer l'ancien.
ou un clic sur raw et copier le contenu et le coller dans le fichier >>
/plugin.video.vstream/resources/sites/zonetel......py

**Comment by BENJI97200** [comment]
@johngf .....merci

**Comment by BENJI97200** [comment]
@johngf....j ai reussi a remplacer le lien....la recherche fonctionne , mais end cliquant sur le titre rien ne se passe(nvidia shield).....

**Comment by Arias800** [comment]
Des fois il faut 2 clique pour ouvrir les liens

**Comment by johngf** [comment]
Le site déconne.. des fois on a droit au timeout

**Comment by BENJI97200** [comment]
@johngf ...sur tous les films

**Comment by johngf** [comment]
Donne nous le log de kodi j'ai posté un liens au dessus vers le wiki qui explique comment faire

**Comment by BENJI97200** [comment]
@johngf ....un peu compliqué pour moi....j essaye j essaye....

**Comment by johngf** [comment]
Y'a rien de compliquer tu va dans les parametres de vstream tu active notice de log
Ensuite tu va sur zt tu test de clic sur un resultat de recherche
Ensuite tu retourne dans les parametres de vstream et clic sur upload log et donne nous le liens affficher

**Comment by BENJI97200** [comment]
@johngf ....ok

**Comment by BENJI97200** [comment]
@johngf ....https://slexy.org/view/s27ROwQYhF

**Comment by Arias800** [comment]
Essaye avec cette version : https://pastebin.com/raw/bSBJjUzp

**Comment by johngf** [comment]
effectivement il y a un soucis sur certain flms

**Comment by BENJI97200** [comment]
@Arias800 ....je met le fichier out? Ds site?

**Comment by BENJI97200** [comment]
Le non du fichier telechargé:bSBJjUzp

**Comment by Arias800** [comment]
Le nom tu doit mettre zone_telechargement_ws.py et tu le mets a la place du fichier existant dans site ^^

**Comment by johngf** [comment]
tu as changer quoi @Arias800

**Comment by BENJI97200** [comment]
@Arias800 ....en mettant le fichier zt n apparait plus

**Comment by Arias800** [comment]
J'ai mis ça : oOutputParameterHandler.addParameter('MAIN', URL_MAIN) a la fin dans showmovielinks comme j'ai pas vu de bug de mon coter j'ai tenter ^^

**Comment by johngf** [comment]
en faite partout ou il y a url_main dans une fonction il faut le rajouter

**Comment by Arias800** [comment]
Normalement @BENJI97200 la c'est bon tu a juste a faire comme @johngf ta dit de faire tout a l'heure https://raw.githubusercontent.com/Arias800/Vstream-extreme-down/master/zone-telechargement_ws.py

**Comment by johngf** [comment]
je l'ai mis a jour [la](https://github.com/johngf/test/blob/master/zone_telechargement_ws.py) normalement c'est bon

**Comment by BENJI97200** [comment]
Passe pas pour moi.....merci a vous deux mais je laisse tomber la recherche sur Zt( les films passe c deja ca)....Mon cerveau chauffe trop....merci

**Comment by johngf** [comment]
ça fonctionne re-teste  @BENJI97200  et @Arias800 pas partout mais global n'ap pas l'air de servir a quelque chose donc

**Comment by BENJI97200** [comment]
Wouahhh....vraiment vous etes  trop fort.....ca passe nickel , merci a vous deux....(grace a vous je suis presqu un Expert )...encore merci

**Comment by BENJI97200** [comment]
@johngf ....la recherche fonctionne , quand on clique sur le titre, le film demarre sans probleme....par contre si je fais films/derniers ajouts/Zt....la rien ne se passe

**Comment by johngf** [comment]
reprend le fichier je l'ai modif c'est du bricolage mais bon ça fonctionne 
le mieux serait d'enregistrer l'url dans settings et de la récup a chaque fois a voir si possible..
penible ce site.

**Comment by BENJI97200** [comment]
@johngf ....Je reprend le fichier?

**Comment by johngf** [comment]
Oui

**Comment by BENJI97200** [comment]
@johngf.....merci , c bon ca fonctionne.....bon boulot ...encore merci

**Comment by johngf** [comment]
@Arias800 [test celui la](https://github.com/johngf/test/blob/master/zone_telechargement_ws.py)
il enregistre l'url dans settingsdans le pire des cas quand tu entre dans le site il recup l'url

**Comment by Arias800** [comment]
J'ai corriger les genres tout marche sauf le next page de la recherche : https://pastebin.com/bSBJjUzp

**Comment by johngf** [comment]
oui j'ai oublié d'enlever un truc

**Comment by Arias800** [comment]
C'est bon ca marche je mets en beta ^^

**Comment by doberberto** [comment]
Je n'est pas les liens de zone téléchargement dispo.... Je suis sous Xbox one.... Quelle manip a effectuer svp 😭😭 désolé d'être un gros naze... 😞😞

**Comment by johngf** [comment]
@doberberto met a jour vstream et c'est bon
