### ISSUE TITLE
Tout les fichiers vidéo sont vide ?

### ISSUE THREAD

**Issue by jujubeelink** [Kodi-vStream/venom-xbmc-addons#2193]
Bonjour, je suis novice, utilisateur de vstream depuis 2 semaines, sur box Android TV, tout fonctionnait à merveille jusqu'à ce que je touche des paramètres pour vider le cache et depuis les onglets pour les films et séries sont présents mais arrivé au film tous est vide, aucun fichier n'est visible, j'espère que vous comprenez mon explication. J'ai essayé de vérifier tout les réglages, réinstaller mais rien n'a faire. Merci par avance pour votre aide.

**Comment by johngf** [comment]
vu que tu est novice commence déjà #2136

**Comment by jujubeelink** [comment]
Bug: les chemins des films et séries sont existant mais les liens finale ont disparus.

-Os: Android
-appareil : box beelink gt1
-kodi V17.6 kripton
-vstream V0.6.5

Log: https://slexy.org/view/s2mFYP7KyV

J'espère avoir fait comme il faut, merci pour vos services.

**Comment by johngf** [comment]
ça aide pas ton log ne contient pas d'info
sur quel site ? tu les trouves ou tes onglet film et serie?

**Comment by jujubeelink** [comment]
Tous ceux de vstream et je viens de voir que c'est le même problème avec flixnet, peux être un bug de Kodi.

**Comment by johngf** [comment]
Ça répond pas à ma question .....
Tu na plus de liens finale sur un site, dans la librairie,dans les favoris .....

**Comment by jujubeelink** [comment]
Dans tous les chemins, tous les sites, favoris...

**Comment by jujubeelink** [comment]
Je constate que les liens finaux des vidéos de tout les Addons de Kodi ont disparus, les liens TV et youtubes fonctionnent .

**Comment by johngf** [comment]
Essaie de désinstallé et réinstaller vstream dans un premier temps.

**Comment by jujubeelink** [comment]
C'est la première chose que j'ai essayé mais sans effet puis j'ai installé flixnet pour voir si lui fonctionnait et le problème est identique donc peut être un soucis de Kodi, je pense essayé un Addon pour reseter Kodi.

**Comment by Arias800** [comment]
Quitte a reset kodi désinstalle le complétement en suppriment le dossier .kodi ça fait l’équivalent de ce genre  d'addon en plus propre ^^

**Comment by ethanael83** [comment]
Bonjour, souci un peu similaire :

Bug: j'utilise adlib sur vstream pour créer ma bibliothèque de films, depuis plusieurs jours quand je veux voir un film avec comme lien uptobox via ZT, cela affiche "! Aucune information" en rouge. Comme si il ne trouvait plus les liens.
J'ai ajouté Tomb Raider dans ma bibliothèque hier via adlib, toujours un lien uptobox via ZT et j'ai le lien quand j'ouvre le film.
Cela est arrivé dernièrement avec les bugs sur ZT et les changements de fichier .py réguliers.
Est-ce que je dois remettre les liens de tous les films de ma bibliothèque un à un ou y a t-il une modif à faire dans le fichier .py ?
Car il y a beaucoup de films enregistrés....

Merci pour toute votre aide et votre réactivité

-Os: Android
-appareil : mi box
-kodi V17.6 kripton
-vstream V0.6.5 (la dernière maj)

**Comment by Arias800** [comment]
Le probleme c'est que Zt a effectuer beaucoup de changement d'url ça peut venir de la ^^

**Comment by johngf** [comment]
c'est normal je pense quand tu as mis les liens dans ta bibliothèque 
ils sont avec une certaine url et avec zt l'url change souvent et du coup tes liens sont plus valide
tu peux pas mettre le liens ex: upto box directement ?

**Comment by ethanael83** [comment]
Ok merci je vais mettre le lien direct de l'hébergeur
Merci pour votre aide ! Au top comme toujours !
