### ISSUE TITLE
Emplacement de la librairie

### ISSUE THREAD

**Issue by adulescente** [Kodi-vStream/venom-xbmc-addons#2195]
Bonjour,
Tel que discuté dans la communauté google+, voici le problème rencontré lors d'ajouts de nouvel élément a la librairie:
https://drive.google.com/file/d/1Rfvla2xfQdHnqmlTi3pJLHOOczEdibYh/view?usp=sharing

sur mon impression d'écran, j'ai ajouté un élément et dans ''Films'' et dans ''Série''.. comme vous voyez,ils ne se placent pas a l'intérieur du répertoire ''FILMS'' et ''Séries'' de vstream... et chaque fois que j'ajoute un élément, il se cré un nouveau dossier encore a l'extérieur.

J'ai essayé sous windows 10, leia et krypton (2 portables différents) et c'est le même résultat.

Ceci a commencé a se produire après la mise a jour qui devait rétablir TRAKT et la librairie...

Voici maintenant mon dossier cible dans mon gestionnaire de fichiers:

https://drive.google.com/file/d/1HCE6czW00EYK53jbxX6g8PwVED0LC4Kt/view?usp=sharing

Biensur, j'ai essayé de supprimer mes fichiers .db mais sans succès.  
J'ai ait des fresh install sous mes 2 versions (leia et krypton) en prenant soins de faire le ménage dans mon regidit...

Voici mon fichier de settings:

Edit: password inside

Puis, enfin, mon dernier log ou on voit les ''no matching in local db''

https://drive.google.com/file/d/14xVb9VNAF9cnQHvCHGebGwEbCPF9_VmO/view?usp=sharing

Espérant avoir donné assez de détails pour que vous puissiez me donner assistance dans la résolution de mon ennui  ;)

Grand Merci!
Jue

**Comment by johngf** [comment]
et il vaut mieux rester sur krypton pour le moment

**Comment by TmpName** [comment]
J'ai retire ton fichier setting, on y voyait certains mots de passe dedans, j'espere que c'etait des comptes gratuit ?

Et comme dit @LordVenom, Vstream est presque totallement francise, donc si tu vois un message en anglais, il y a 90/100 de chance que cele vienne d'un autre addon, comme metahandler par exemple.

**Comment by adulescente** [comment]
TmpName:

oui ouffffff, et merci !!!°°°je suis pas très vigilente....

**Comment by adulescente** [comment]
merci pour le suivi LordVenom!

Tu sais, j'adore vstream.... Mais je n'irais pas jusqu'à faire un fresh install et nettoyer mes clés à l'aise du regedit juste pour cet addon hihi.... je venais de terminer des build, alors je devais le faire. :)))

Merci pour tout!
À plus
Jue

**Comment by adulescente** [comment]
johngf:

je n'ai noté aucune instabilité sous leia jusqu'à présent, ... c'est un super additiel...

Je l'utilise sur les 2 versions

A+ !
Jur

**Comment by johngf** [comment]
j'ai teste leia 18.2 15 min ça ma suffit 
 -lors des retours en arrière parfois le clavier s'ouvre tous seul
 -il mais les fichiers sites et host en cache du coup pour une modif manuelle faut redémarrer kodi (ou d'apres @Arias800 retourner sur page d'accueil de kodi)
 -une modif a déjà été faite par @Arias800 pour eviter l'affichage de base de leia ,
   qui affiche la page courante avec la page précédente en gros

**Comment by LordVenom** [comment]
Des nouvelles avec la version 0.6.52 ?

**Comment by LordVenom** [comment]
Oui c'est chiant mais c'est pour pouvoir avec les mêmes saison dans les mêmes dossier le grabeur de Kodi t'en remerciras XD

**Comment by LordVenom** [comment]
Pareil pour nous tous je pense le code de vStream nous à interloquer voire énerve et ont c'est lancer.

J'ai pas de connaissance particulière en tous cas moins que les autres contributeur mais je suis un éternel insatisfait en plus d'être têtu XD.

Note : Les marques-pages je suis sure qu'on peux faire mieux ^^

**Comment by adulescente** [comment]
Ha!
Je me reconnais dans ta mentalité hihi!!

:)))

**Comment by LordVenom** [comment]
Vient du cote Obscure de la force ^^

**Comment by adulescente** [comment]
Ouiiiii!!!

Çadonne beaucoup de nuit blanches hein!

**Comment by LordVenom** [comment]
La preuve vStream ce fait vieux ont vas battre le record du monde de maintient d'un addon.

**Comment by adulescente** [comment]
Vous en êtes à combien, dis?

**Comment by LordVenom** [comment]
Dans ma tête ? beaucoup, non c'est libre tu peux voir les contributeurs ici 
https://github.com/Kodi-vStream/venom-xbmc-addons/graphs/contributors
