### ISSUE TITLE
Connexion compte premium 1 fichier.

### ISSUE THREAD

**Issue by reds07** [Kodi-vStream/venom-xbmc-addons#2198]
Bonjour à tous,

Depuis quelques jours, j'ai des soucis de connexion lors ce que je veux me connecter avec mon compte premium, je reçoit un message style, connections premium refusé. Mon compte est bien entendu toujours valide jusqu'à fin octobre.

Quelqu'un a une idée ?

**Comment by johngf** [comment]
tu t'y connecte comment en lançant une video ? depuis un site zt ou autres ?

**Comment by reds07** [comment]
Je fait comme d'habitude, je lance mon liens via ZT,  sa fonctionnait très bien jusqu'à ya quelques jours,  via PC avec un gestionnaire de téléchargement aucun souci, la s via vstream, arrivé au liens j'ai un message " authentification raté " au moment de lancer le lien.

**Comment by johngf** [comment]
perso j'arrive a m'authentifier tu peut essayer et nous donner le log de kodi ? [upload log](https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils)

**Comment by johngf** [comment]
ça fonctionne maintenant ou pas ?

**Comment by reds07** [comment]
Voilà, j'ai été sur le site de 1fichier même, et au moment de le logger on m'a demandé de choisir un nouveau mot de passe je ne sais pour qu'elle raison, j'ai remis le même, et depuis je peux me reloguer en premium sur vstream, merci pour ton aide johngf.

**Comment by johngf** [comment]
il m'est arrivé la meme chose ,je m'étais trompé d'une lettre dans mon adresse mail et après plusieurs tentative de connexion j'ai du changer de pass
