### ISSUE TITLE
Import/Export Marque page

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2199]
J'en avais marre de perdre mes favoris a chaque installation.

![image](https://user-images.githubusercontent.com/4380112/43516459-f182ea32-9585-11e8-8eda-b0a6b4b997a5.png)

![image](https://user-images.githubusercontent.com/4380112/43516305-7c929f9c-9585-11e8-9956-05a2019bd41c.png)

**Comment by lebigboss** [comment]
Bien jouer mdrrr
