### ISSUE TITLE
Retour ancienne version après mise a jour automatique 

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#2200]
Bonjour , voici ma config actuelle  : 

Systeme utilisé Android 7.1 , sur box Alfawise H96 Pro+
Derniere version de Kodi utilisé (17.6)
Version Vstream 0.6.5

Après avoir effectué la mise a jour 0.6.52 , qui m'était proposé , je n'avais plus accès aux films sur ZT , j'ai donc reinstaller la version zip 0.6.5 , et , j'ai de nouveau accès aux films sur ZT .
Pouvez me dire pourquoi ?
Je n'ose plus faire les mises a jour auto , qui me sont proposé .
Je tiens a vous remercier , pour le super boulot que vous effectué .

**Comment by johngf** [comment]
non la 0.6.53 fonctionne je viens de  test

**Comment by ktm520** [comment]
J'avais le problème uniquement sur ZT , 
Le faite d'etre revenu a la version 0.6.5 , le problème a disparu .

**Comment by LordVenom** [comment]
Ici ont cherche des solutions pour tous le monde (l'open source) 
Le retour en arrière n'est pas une solution viable sur le long terme et ton message n'aide personne.
