### ISSUE TITLE
Streaming ou direct plus disponible sur Uptobox

### ISSUE THREAD

**Issue by camelone** [Kodi-vStream/venom-xbmc-addons#2202]
Bonjour, je suis de retour de vacances. Donc, aujourd'hui j'ai fait la mise à jour VStream. Depuis, je n'ai plus le choix du direct ou du streaming depuis Uptobox. 

Votre system

OS: Openelec v7.0.1
Appareil: Raspberry pi2
Version Kodi 16.1
Version Vstream 0.6.5
Nous devons le reproduire
Pour cela il nous faut:

Le nom du site zone téléchargement ou ddl Island
Le titre du fim/serie dans l onglet: tous. Ex: pierre lapin.
Le nom du host (uptobox)
Log
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://slexy.org/raw/s20c6ba8Q3?token=7cff21a09d4ef6d98e65d57d867c2266dff504719b17f0eb53e17c031538d100&ts=1532441990

Plus

Plus possible de regarder en direct, donc plus de bande son Dolby, dts ou autre. J'ai un compte premium.

**Comment by johngf** [comment]
chez moi j'ai la popup après c'est un comptre gratuit
@camelone sur le site internet ton compte est valide ?
dans les settings de vstream efface ton pass et mail et renseigne les de nouveau et re-test

ton fichier log ne fonctionne pas invalid id ou expired c'est bizarre normalement il est gardé 3j peut etre une erreur d'une lettre

**Comment by kenshiro000** [comment]
Vérifie dans les réglages de ton compte uptobox, que " téléchargement direct " soit bien désactivé.

**Comment by camelone** [comment]
Ok. J'ai trouvé.. mon compte uptobox était désactivé dans vstream et plus de login et mot de passe.. suite à une mise à jour.. merci pour vos conseils! Vous pouvez closer...
