### ISSUE TITLE
Problème de redirection du site ZT

### ISSUE THREAD

**Issue by AzeRim** [Kodi-vStream/venom-xbmc-addons#2205]
Décrivez le bug
Suite à  des problèmes de connexion et de redirection de ZT, la soulution de l'issue #2192 ne semble plus fonctionner. La modification de la ligne URL_HOST en 'https://zone-telechargement1.org/' semble fonctionner pour l'instant. Y a-t-il une autre solution plus viable?

Votre system

OS: [Android]
Appareil [smartphone galaxy S7]
Version Kodi [17.6]
Version Vstream [0.6.5]
Nous devons le reproduire
Pour cela il nous faut:

Le nom du site [zone telechargement]
Le titre du fim/serie 
Le nom du host 
Log

Image

Plus

**Comment by Arias800** [comment]
Corriger par @johngf sur la beta : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by AzeRim** [comment]
OK merci @Arias800. Desolé, issue ouvert par erreur car j'aurais dû vérifié avant dans la beta que fichier était déjà modifié depuis 14h.

**Comment by BENJI97200** [comment]
Bjr sur nvidia shield TV , ne fonctionne plus

**Comment by ludopotte** [comment]
Hello BENJI97200, si tu veux que la Source "Zone Telechargement" marche, il te suffit de télécharger mon Patch au https://github.com/ludopotte/vStream en suivant la Notice d'installation dans la rubrique "Issues".

**Comment by BENJI97200** [comment]
Merci....mais je ne trouve pas la notice d installation....

**Comment by BENJI97200** [comment]
@ludopotte....c bon j ai reussi....mais en voulant lancer le lien erreur protection cloudflare

**Comment by BENJI97200** [comment]
J ai erreur connexion impossible 503 et apres erreur protection cloudflare

**Comment by ludopotte** [comment]
Ben alors BENJI97200, tu ré-installe mon Patch sans désinstaller vStream et normalement ça devrais marchais correctement. Si ça fonctionne pas, tu as un soucis avec l'extension ou Kodi chez toi.

**Comment by BENJI97200** [comment]
OK j essaye...et je te tiens au courant....merci

**Comment by BENJI97200** [comment]
J ai desinstaller vstream , ne fonctionne tjrs pas ....je desinstalle kodi pour voir

**Comment by BENJI97200** [comment]
Desinstaller Kofi et ne passe tjrs pas

**Comment by ludopotte** [comment]
Ben desolé BENJI97200, je peux rien de plus pour toi. Ré-installe vstream depuis son depot au https://vstream.ga/repo/, ré-installe l'extension et ensuite installe mon Patch.

**Comment by AzeRim** [comment]
Merci @TmpName pour la modif 
h ttps://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/cloudflare.py
Mais comme dit au dessus les messages d'erreur apparaissent très souvent🤔

**Comment by TmpName** [comment]
Lol, a mince j'avais pas vu que ca bugguait ici aussi pr la meme raison, en fait GT sur un autre site ^^.
Mais j y rejette un oeuil, apparement ca buggue aussi encore sur l'autre.

**Comment by K3R0ZEN** [comment]
Salut, problème sur ZT avec Cloudflare ici aussi.

**Comment by BENJI97200** [comment]
Slt... La solution de Ludopotte fonctionne aujourd hui alors qu hier non.....merci

**Comment by ludopotte** [comment]
Pour régler le Problème de Zone Telechargement (ZT), il suffit de télécharger mon Patch en Version 1.80

**Comment by TmpName** [comment]
Y a une nouvelle version de cloudflare mais je sais pas si ca corrige votre prb.

**Comment by ludopotte** [comment]
La Nouvelle Version de Cloudflare corrige le Problème car j'ai tester.
