### ISSUE TITLE
que des problèmes apres mise à jour 

### ISSUE THREAD

**Issue by meufeu** [Kodi-vStream/venom-xbmc-addons#2208]
**Décrivez le bug**
Bonjour,
j'ai installé il y a plusieurs semaines mon Kodi avec vstream mais je n'ai l'écran que depuis avant hier.
avant hier donc j'ai apprécié pouvoir regarder un film et plusieurs dessins animés disney HD .. le top
vstream m'a proposé une mise à jour et depuis .. plus rien ne marche .. quand je fais "liste des films" dans disney HD il n'y a plus rien
j'ai activé les logs 
il y a d'abord ce warning .. je ne sais pas si c'st grave

```
21:33:29.173 T:2545410816 WARNING: CPythonInvoker(7, /home/osmc/.kodi/addons/plugin.video.vstream/default.py): the p
ython script "/home/osmc/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we co
uldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
```

et puis ... le drame ... voici un exemple mais je n'ai pas pu regarder un film et ca fait une heure que j'essaie ...
qu'est ce que je fais mal ?

```
21:35:21.168 T:2526802688  NOTICE:      [PLUGIN] Vstream: load site cHosterGui and call function play
21:35:21.502 T:2526802688  NOTICE:      [PLUGIN] Vstream: Hoster - play https://openload.co/embed/M3UtlU1Cr3U/La_Lége
nde_de_Despereaux
21:35:23.075 T:2526802688  NOTICE:      [PLUGIN] Vstream: Erreur: Connection Failed (400),https://openload.co/embed/
M3UtlU1Cr3U/La_Légende_de_Despereaux
21:35:23.122 T:2526802688  NOTICE:      [PLUGIN] Vstream: OPL er 1
21:35:23.181 T:2526802688  NOTICE:      [PLUGIN] Vstream: Erreur: Fichier introuvable
21:35:23.262 T:2526802688  NOTICE:      [PLUGIN] Vstream: Table initialized
21:35:24.000 T:2526802688 WARNING: CPythonInvoker(10, /home/osmc/.kodi/addons/plugin.video.vstream/default.py): the
python script "/home/osmc/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we c
ouldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
21:35:24.190 T:2991862352   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream
/?site=cHosterGui&function=play&title=La+L%C3%A9gende+de+Despereaux+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&sHoste
rIdentifier=openload&sTitle=La+L%C3%A9gende+de+Despereaux+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&siteUrl=https%3A
%2F%2Fopenload.co%2Fembed%2FM3UtlU1Cr3U%2FLa_L%C3%A9gende_de_Despereaux&sFav=play&sMediaUrl=https%3A%2F%2Fopenload.c
o%2Fembed%2FM3UtlU1Cr3U%2FLa_L%C3%A9gende_de_Despereaux&sCat=4&sId=cHosterGui&sFileName=La+L%C3%A9gende+de+Despereau
x]
```

**Votre system**
 - OS: LINUX OSMC
-  Appareil raspberry PI 1
 - Version Kodi  17.6
- Version Vstream 0.6.53

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site disneyhd
- Le titre du fim/serie .. n'importe lequel, il n'y en a plus aucnu
- Le nom du host disneyvk

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
alors j'ai eu le même soucis pour moi c'est le site les docus
- j'ai remarqué que certains fichier mise a jour ici ne sont pas inclus dans la maj ou ne sont pas mis a jours chez nous
- concernant le lien dans ton log c'est normal il ne devrait pas y avoir d'accent dans une url 
   je vais corriger le fichier d'open load pour qu'il puisse le lire

**Comment by LordVenom** [comment]
@johngf, DSl j'arrive pas a reproduire ce bug chez moi les fichiers sont mise à jour correctement.

**Comment by johngf** [comment]
avec la 06.53 ça a l'air d'etre  ok 
@meufeu tu as quel version de vstream ?

**Comment by meufeu** [comment]
bonjour,
j'ai bien la 06.53 ... mais j'ai trouvé et je suis honteux
je ne l'explique pas mais j'ai fait un arret électrique de la box ..
pourtant je surfais, téléchargeait et tout mais tous les liens de streaming
étaient HS ..
maintenant tout remarche
merci de votre travail et désolé ..

2018-08-11 10:53 GMT+02:00 johngf <notifications@github.com>:

**Comment by meufeu** [comment]
bonjour,

Il semble que le redémarrage aie eu un effet mais il n'a été que temporaire
..
exemple gaston lagaffe sur streamango comme sur openload


13:42:55.143 T:2535670528 WARNING: CPythonInvoker(46,
/home/osmc/.kodi/addons/plugin.video.vstream/default.py): the
python script "/home/osmc/.kodi/addons/plugin.video.vstream/default.py" has
left several classes in memory that we c
ouldn't clean up. The classes include:
N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
13:42:55.155 T:2991735376   ERROR: Playlist Player: skipping unplayable
item: 0, path [plugin://plugin.video.vstream
/?site=cHosterGui&function=play&title=Gaston+Lagaffe+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&sHosterIdentifier=ope
nload&sTitle=Gaston+Lagaffe+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2Fopenload.co%2Fembed%2Fdw
DSVHbh5qc&sFav=play&sMediaUrl=https%3A%2F%2Fopenload.co%2Fembed%2FdwDSVHbh5qc&sCat=4&sId=cHosterGui&sFileName=Gaston
+Lagaffe]
13:43:07.747 T:2569188096  NOTICE:      [PLUGIN] Vstream: SQLITE 3 as DB
engine
13:43:08.495 T:2569188096  NOTICE:      [PLUGIN] Vstream: load site
cHosterGui and call function play
13:43:08.751 T:2569188096  NOTICE:      [PLUGIN] Vstream: Hoster - play
https://openload.co/embed/dwDSVHbh5qc
13:43:09.569 T:2569188096  NOTICE:      [PLUGIN] Vstream: OPL er 1
13:43:09.645 T:2569188096  NOTICE:      [PLUGIN] Vstream: Erreur: Fichier
introuvable
13:43:09.745 T:2569188096  NOTICE:      [PLUGIN] Vstream: Table initialized
13:43:10.603 T:2569188096 WARNING: CPythonInvoker(47,
/home/osmc/.kodi/addons/plugin.video.vstream/default.py): the
python script "/home/osmc/.kodi/addons/plugin.video.vstream/default.py" has
left several classes in memory that we c
ouldn't clean up. The classes include:
N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
13:43:10.713 T:2991735376   ERROR: Playlist Player: skipping unplayable
item: 0, path [plugin://plugin.video.vstream
/?site=cHosterGui&function=play&title=Gaston+Lagaffe+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&sHosterIdentifier=ope
nload&sTitle=Gaston+Lagaffe+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2Fopenload.co%2Fembed%2Fdw
DSVHbh5qc&sFav=play&sMediaUrl=https%3A%2F%2Fopenload.co%2Fembed%2FdwDSVHbh5qc&sCat=4&sId=cHosterGui&sFileName=Gaston
+Lagaffe]


j'ai beaucoup de mal à voir une video .. en fait il n'y a guere que disney
hd qui fonctionne ..
Je me permet en passant de suggérer une modification ergonomique : a
l'heure actuelle pour regarder un film il faut faire énormément de clic
dans kodi
video > extension > vstream > films > derniers ajouts par exemple >
streamsite > openload / streamango
donc pour voir 1 film .. il faut au moins 7 clics !!

ne pourrait on pas avoir en page d'accueil directement une page indiquant
(un peu comme ce qu'il y a sur tous les sites de streaming) montrant les,
je ne sais pas, 5 derniers films, 5 plus vus, idems pour les series etc ...
?


2018-08-11 10:07 GMT+02:00 Lord Venom <notifications@github.com>:

**Comment by meufeu** [comment]
pour info, je suis développeur donc si je peux vous aider a améliorer je
suis disponible

une idée serait de tester le lien avant de l'afficher ... ca serait un peu
plus long mais les liens seraient automatiquement validés

2018-08-11 10:07 GMT+02:00 Lord Venom <notifications@github.com>:

**Comment by LordVenom** [comment]
La fonctionn recherche visuelle fait ça elle affiche les films populaire, plus vue ect.. puis fait une recherche sur quasi tous l'addon pour trouver une correspondance aprés à l'utilisateur de trouver le bon lien y a le choix.

**Comment by meufeu** [comment]
C est donc anti ergonomique .. C est dommage il y a beaucoup de gens qui
abandonnent kodi car on leur propose des liens daubes .. je pense que si
des liens validés etaiengt proposés il y aurait plus c utilisateur au
contraire .. suffit de prendre parmi les plus vus et de pouvoir spécifier
des criteres

**Comment by meufeu** [comment]
C est pas clair ce que fait la recherche visuelle .. il faudrait alors la
même chose mais sans avoir a taper qq chose

Le mar. 14 août 2018 5:46 PM, Lord Venom <notifications@github.com> a
écrit :

**Comment by TmpName** [comment]
Lol, on fait pas dans l'ergonomie mais l'efficacite.
L'outil le plus efficace c'est l humain, on va pas pondre on algorythme pour proposer la source qui a le plus de chance de fonctionner, car trop de variable a prendre en compte alors qu'un humain avec l experience ira plus vite.

> suffit de prendre parmi les plus vus

Arretez de faire les nombrilistes, meme si on mettait les 20 videos les plus vues, y a pas 20% des users qui voudront voir celles la.

Et y a trop de criteres, exemple la video qui marche a 12h ne marchera pas a 21h sur certains hebergeurs.

La recherche visuelle sans avoir a taper quelques chose ? Tu veut qu'on affiche 3000 vignettes comme ca l'user a juste a cliquer ? Peut etre que toi, tu ne regardes que les 3 derniers films sortis aux USA, mais la quantite de donnée est enorme pour "les autres".
