### ISSUE TITLE
Impossible d'installer vstream sur Windows 10

### ISSUE THREAD

**Issue by liberodark** [Kodi-vStream/venom-xbmc-addons#2209]
**Décrivez le bug**
Windows 10 x64 avec kodi que je viens d'installer mais vstream ne s'installe pas.

**Votre system**
 - OS: [Windows10]
-  Appareil [PC]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Windows 10 + Kodi 17.6 téléchargé sur le site officiel
PS  ou télécharger le repo je suis allé sur deux site je ne sais pas si cela vient de là.

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
dans les paramètres de kodi tu as activer installation depuis sources inconnues ?
sinon faut le log pour voir ce qui fonctionne pas chez toi c'est pas compliqué a trouver kodi.log https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Comment by liberodark** [comment]
Kodi installé depuis le site officiel impossible de trouver le repo sur votre github pourquoi ?
Donc je les pris sur : https://kodi-addons.club/addon/repository.vstream/0.0.3
Installé sur kodi puis ensuite lancement de l'installation de vstream une fois installé impossible de le lancer un erreur est présente mais je ne sais pas quoi.

Cordialement

**Comment by Arias800** [comment]
Il y a le repo officiel ici : http://vstream.ga/repo/
