### ISSUE TITLE
streaming_series_xyz

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2213]
**Décrivez le bug**
Plus de lien finaux sur la source streaming_series_xyz

**Nous devons le reproduire**
site : streaming_series_xyz
Doit deconner sur tout les liens finaux

**Plus**
Probleme non trouve dans la fonction ProtectstreamBypass()

**Comment by johngf** [comment]
alors j'ai test plein de truc et pas vraiment de résultat de rare cas ou le lien s'affiche ...

**Comment by johngf** [comment]
j'ai remarqué que meme si le timer a 5 seconde sur le net c'est toujours 5 et quelques..
j'ai test cookie, 2eme cookie ,referer, user-agent  content encoding br ,requete sur le js avant,requete sur les icones ou le font qui est toujours 404 
rarement le liens s'affiche je pense que c'est un soucis de timer mais pas trouvé la soluce pour l'instant

**Comment by TmpName** [comment]
Ben si toi le lien s'affiche de temps en temps, je vais voir pr le coup du timer, car j'ai tut teste sauf le timer, et ca a pas marche une seule fois, et ca marche cookies desactives sur navigateur, donc je pense qu'on peut sauter cette piste.

**Comment by TmpName** [comment]
Bon c'est pas le timer, j'ai bloque la requette avec tamperdata pendant 10s, mais quand j'ai laisse passer, pas eu de soucis ...

**Comment by TmpName** [comment]
Y a un autre site qui utilise la meme protection "Serie-Streaming-Watch" mais j'ai transpose le code, meme probleme.
C'est du https donc ca va etre la galere avec wireshark, vais tester avec httrequester.

**Comment by johngf** [comment]
meme chose que l'autre sauf que le timer est a 4 j'ai un lien qui s'est affichier une fois en mettant timer 4000

**Comment by johngf** [comment]
bon j'ai trouvé

**Comment by TmpName** [comment]
serie_streaming_watch marche sans prb chez moi. M'en suis meme servis ce matin. Mais en copiant le code de watch dans celui qui deconne ca ne marche pas chez moi.
J'ai la longeur de data qui chnage.

J'ai meme essaye la fonction "refaire la requette" dans firefox avec une nouvelle valeur de k affiche sur une page avec JS desactive >> meme prb

J'ai essaye en bloquant toute les images et pub >> ca marche encore.

**Comment by TmpName** [comment]
Bon j'ai refait quelques tests en bloquant des headers
1 - referer sert a rien
2 - cookie sert a rien
3 - Accept encoding sert a rien
4- accept sert a rien
5 - accept encoding sert a rien

En fait le seul moyen que j'ai trouve pour reproduire le bug c'est en utilisant Tamperdata et essayant de modifier la requete "secur2.js", mais pas trouve pkoi.

**Comment by 1shad** [comment]
Salut,
Les requètes sur secur2.js, et secur2.php passent via HTTP/2.0, peut-être pour ça que ca ne fonctionne pas.

**Comment by TmpName** [comment]
Mais c'est pas bete, je crois vraiment que c'est une histoire de reseau.
Le prb c'est que c'est en SSL, donc pour pouvoir comparer dans wireshark, faut recuperer des fichiers a ajouter, que via kodi c'est l'enfer , faudrait passer en python direct, autrement dit, ca va prendre 10 plombes.
Mais via firefox, rien vu de special.

**Comment by 1shad** [comment]
En fait non c'est pas ça. Avec Firefox, dans about:config, on peut forcer l'utilisation de HTTP/1.1, en mettant sur False la variable: network.http.spdy.enabled.http2

Et ça fonctionne quand même...

**Comment by 1shad** [comment]
C'est frustrant, je n'arrive pas à trouver pourquoi ca ne marche pas. Comme Johngf, j'ai le lien qui s'affiche aléatoirement, mais je trouve pas de solution pour que ça marche à chaque fois.

J'ai écris ce script à l'arrache et ca marche à chaque coup, seulement dans vstream niet.
[http://ix.io/1lVX](http://ix.io/1lVX)

**Comment by TmpName** [comment]
Attend en python ca marche sans prb ? Mais pas sous kodi ?

**Comment by 1shad** [comment]
C'est ça, après j'utilise requests et je ne sais pas si je peux l'import dans une source de vstream.

**Comment by TmpName** [comment]
Sisis, ca marche, request aussi dans lib python de kodi . Mais du coup je reprend espoir ^^.

**Comment by Arias800** [comment]
Et faudra tester mais request gèrent mieux le ssl qu'urllib d’après internet donc peut être que ca va limiter les erreur liée au ssl ^^

**Comment by 1shad** [comment]
Génial, ben je vais essayer

**Comment by 1shad** [comment]
Bon alors ca marche. J'ai les liens à chaque fois. Seulement j'ai une nouvelle erreur,
due à l'utf-8. Vous êtes peut-être déjà tomber dessus donc ma demande pour aller un peu plus vite.

Un problème avec les characteres style '\xe9', c'est le 'é' dans le mot télécharger qui apparait dans le résultat. Et du coup il fait planter ça:
 aResult = oParser.parse(data, sPattern)

Vous savez comment les gérer, ou les enlever, ou c'est quoi qu'il faut faire  ?

**Comment by TmpName** [comment]
Alors sans voir le code c'est pas sur mais essaye

            sTitle = sTitle.decode("utf-8", 'ignore')
            sTitle = sTitle.encode("utf-8", 'ignore')

La premierer ligne encore ton texte en unicode, en prennant l'hypothese que ta page est en utf-8.
La seconde repasse en format utilisable par python/kodi

**Comment by 1shad** [comment]
Merçi, ca marche avec le encode.
Je refais quelques tests je met au propre le fichier.

**Comment by 1shad** [comment]
Si vous voulez essayer: [http://ix.io/1lWp](http://ix.io/1lWp)

Si ç'est bon pour vous, dites le moi et je ferais une PR. Sinon, ben comme vous voulez...

**Comment by TmpName** [comment]
Franchement je te fais confiance, la j'ai pas acces a la tv pr tester, mais vas y te genes pas pour le pull.
On saura jamais ce qui manquait, mais le principal c'est que quelqu'un ait trouve.
Gz en passant :).

**Comment by johngf** [comment]
est-ce request est obligatoire ? ça fonctionne pas avec urllib2 ?

**Comment by 1shad** [comment]
Je dirais que non, ce n'est pas du tout obligatoire. Et que je n'ai pas réussi avec urllib2,
en prenant en exemple ce qui il y avait au départ. ( Ni avec cRequestHandler  comme dans watch)

**Comment by TmpName** [comment]
Pareil, j'ai pas trouve pkoi ca deconne avec urllib. Ca doit marcher, c'est oblige, mais pas envie de repasser 2h a chercher pr rien, la le code marche, c'est parfait.
J'aimerais bien savoir par curiosite, mais j'ai vraiment pas le temps en ce moment.
