### ISSUE TITLE
UPTOBOX

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#2214]
Les Liens Uptobox ne marche plus car sur vStream ça marque : lien introuvable.
Est-ce qu'il aurait un moyen de repérer ça s'il vous plait ?

**Comment by AzeRim** [comment]
VotreCompteUptobox et les liens uptobox fonctionnent chez moi. Pas problème.

**Comment by ludopotte** [comment]
C'est Bon johngf, mon problème à était régler avec la modification de Cloudflare fait par TmpName

**Comment by TmpName** [comment]
Wé dsl, j'ai voulu faire un gros changement sur cloudflare et ca a foutu pas mal de bordel.

**Comment by BENJI97200** [comment]
Bjr sur kodi avec compte uptobox les films bug, alors qu avec le navigateur de la box aucun bug....une solution SVP?

**Comment by johngf** [comment]
de quel bug tu parle @BENJI97200 ?

**Comment by BENJI97200** [comment]
@johngf ...en voulant lire un film sur kodi (site zt)...le film saccade ou se fige et me marque memoire tampon ou vitesse trop lente(j ai un compte uptobox)....alors qu avec Mon navigateur le film passe sans probleme....

**Comment by BENJI97200** [comment]
OK merci ...je vais tester advanced....(j ai 100 mega SFR)

**Comment by johngf** [comment]
en gros c'est kodi le probleme premiere chose a faire c'est de mettre sur pause 10 sec pour voir
la barre de cache doit augmenter si ça augment pas c'est ton debit ou celui d'upto box qui est en cause

**Comment by BENJI97200** [comment]
Si ca passe sur le navigateur de la box cela veut dire que le debit est bon???

**Comment by BENJI97200** [comment]
En mettant sur pause sur kodi la barre n avance pas....sur le navigateur elle avance tres vite

**Comment by johngf** [comment]
oui certines video dans kodi ont 7,50 mo de cache d'autre 15mo ça dépend essaie de créer le fichier tu le met dans userdata et test dans le log de kodi il doit etre chargé au démarrage

**Comment by TmpName** [comment]
Essayes avec un navigateur sur ta machine ou se trouve Vstream pour tester.

**Comment by BENJI97200** [comment]
Kodi est sur nvidia shield TV et google chrome de la shield et en filaire....

**Comment by BENJI97200** [comment]
Je dois le metre ou? Le fichier XML cree?

**Comment by johngf** [comment]
t'est sur windows ? 7 ou 10
ou autres

**Comment by BENJI97200** [comment]
Sur android...nvidia shield TV

**Comment by BENJI97200** [comment]
Sur chrome de la nvidia ....quand je met pause sur un film (compte uptobox )la barre avance rapidement alors que sur kodi en mettant pause la barre n avance pas mm en laissant 5mn......

**Comment by johngf** [comment]
sur android >> Android/data/org.xbmc.kodi/files/.kodi/userdata/

**Comment by BENJI97200** [comment]
Merci mais ct deja ds ce dossier....ca passe mieux....pas de buffering pour le moment, LA pause 10s ne fait pas avancer la barre (reste figee)....Merci beaucoup tant que ca passe ca me va.....MERCI

**Comment by johngf** [comment]
tout dépend a combien de mo tu mets le cache de base il est a 20 mo max

**Comment by BENJI97200** [comment]
Encore une question....desolé johngf ....tu regles le cache ou?

**Comment by BENJI97200** [comment]
@johngf .....merci

**Comment by AzeRim** [comment]
Je confirme qu'en 4G la video s'arrête. Pas encore tester chez moi en débranchant le cable ethernet. Pour info, avec ce fichier Avenger en ultra ZT via uptobox fonctionne bcp mieux (shield avec red 100M)

**Comment by johngf** [comment]
@AzeRim ça fait 20 mo ~278921216
@BENJI97200 c'est surement a cause d'upto box lui meme qui bride involontairement le débit en fonction du nombre de connexions

@AzeRim la 4g c'est pas stable ça coupe sans arret a moin d'etre proche de la borne c'est pour ça que les maj sur les smartphones ce font en wifi

**Comment by BENJI97200** [comment]
@johngf ...mais pour moi pause ne sert a rien....dc je me contente du 720 p....
@AzeRim....tu arrives a lire des ultra HD?(deja essayé rien a faire)

**Comment by johngf** [comment]
@BENJI97200 tu dit que tu as une connexion 100 mega mais combien réél test ici http://openspeedtest.com/

**Comment by AzeRim** [comment]
Sur ma ligne fixe, la video ne s'arrête pas (avengers 1080p lecture 1 min puis débranchement du cable ethernet jusqu'à 1min30s).
Sur ht tps://translate.googleusercontent.com/translate_c?depth=1&hl=fr&nv=1&prev=search&rurl=translate.google.com&sl=en&sp=nmt4&u=https://kodi.wiki/view/HOW-TO%253AModify_the_video_cache&xid=17259,15700022,15700122,15700124,15700149,15700186,15700190,15700201&usg=ALkJrhhjTgUBRC5fyP7ZV7irBBd26GHX7A , l'exemple 4 indique 133Mo donc je l'ai doublé et je n'ai pas mis de readfactor.
Avengers en 4K fonctionne bien. Je n'ai plus de saccadement intempestif avec ce fichier.

**Comment by AzeRim** [comment]
En 4G, il ya sûrement un problème d'IP qui change

**Comment by BENJI97200** [comment]
C pour ca que quand je met un film sur le navigateur de ma box (avec uptobox,  site Zt), un bluray 1080p le film est a moitié et la barre d avancement est deja fini dc aucun soucis , je peux avancer ou reculer le film comme je veux, mais le soucis c qu il ne passe pas en dolby, dts.....c pour cela que j utilise Kodi (qui decode bien sur)

**Comment by AzeRim** [comment]
Avec le navigateur, tu lis avec uptostream (la qualité vidéo et audio sont diminués). Attention avec kodi via uptobox le son n'est pas décodé en dolby en sortie de la box, il faut activer dans kodi/système/audio/activer le mode laisser-passer sinon pas dolby.

**Comment by BENJI97200** [comment]
@AzeRim ....oui je sais ....merci....mais pour les 1080p (sniffff)....impossible (saccade) et j ai mm pri un vpn en pensant que....c pire...

**Comment by AzeRim** [comment]
@BENJI97200, c'est bizarre car j'ai aussi la nividia shield Tv en filaire et tous passent sans problème.

**Comment by BENJI97200** [comment]
@AzeRim ....ah ouiii...bizarre.....

**Comment by AzeRim** [comment]
@BENJI97200 ton test de débit est bien réalisée avec la shield via chrome?

**Comment by BENJI97200** [comment]
@AzeRim .....oui

**Comment by schroef** [comment]
who introduced UpToBox to kodi. Dang what a pain the A.... Never works, keeps showing login/register screen. ALways shows with othre links.  But that is KODI issue in general. WHy does it loop over streams again when you pick one? Makes abosulty no sense at all!
