### ISSUE TITLE
Voir films down ? 

### ISSUE THREAD

**Issue by RogerWilco08** [Kodi-vStream/venom-xbmc-addons#2215]
Bonjour

Je suis vstream depuis un petit moment mais comme les URL des sites changent souvent y a t'il un moyen simple de les updater sans attendre une mise à jour.
Dans la dernière mise à jour, hier ou avant hier le fichier était vide.
Ou sont stocké les flag lu/pas lu car lors de l'avant dernière mise à jour tt avait disparu.
Qu'elle sont les fichiers impactés par la mise à jour et sa db. 

Pour ma par il est exclu de desinstaller et réinstaller Kodi 18 qui marche bien. 

Voilà sûrement plein de question redondante mais la principale est que lorsque une mise à jour foire comment la refaire sans tt péter l'existant. 

Merci de vos réponses. 

Roger

**Comment by johngf** [comment]
comme kodi 18 est une version alpha  aucune modif dans vstream ne sera faite pour l'instant on attend la version final ou non alpha (j'ai remarqué quelque soucis)
sinon voirfilms avec un (s) le vrai les autres étant des copies fonctionne l'autre sans (s) est fermé et voirstream qui a l'icone de voirfilms pareil

**Comment by RogerWilco08** [comment]
En gros plus rien ne marches voir film avec ou sans s et dans votre version. Lol

Alors qu'avant ça marchait et leur site Web est fonctionnel. 

Et le script lui est fonctionnel aussi donc y a un pti truc chez vous. 

Mais pas grave je suis ds linfo et autre et si on fait bien son truc on empêche les personnes d'installer un script ds une version boiteuse.... C'est plus cool..

**Comment by johngf** [comment]
[voir film]('http://www.voirfilm.bz/)
[voir films](http://www.voirfilms.ws/) fonctionne
[voir stream](http://www.voirstream.ws/)
avant c'etait avant aujourd'hui >> vas verifier sur les sites

**Comment by RogerWilco08** [comment]
Ma question est super simple, dingue. Ma maj a foiré sûrement kodi 18, comment la refaire sans tt péter..

C'est claire comme requête non ?

**Comment by johngf** [comment]
tu as essayer > sur l'ecran d'accueil des applications  tu clic droit (clic prolongé sur android) sur vstream clic sur info puis mettre a jour

**Comment by RogerWilco08** [comment]
Je vais tester merci, mais la db ou y a "les vue et non vue" c'est qu'elle fichier ?

**Comment by johngf** [comment]
sur windows 7 AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream
sinon avec le [wiki](https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-vStream) tu devrais trouvé vstream.db

mais comment la maj a planté une idée ? coupure de connection autres ..

**Comment by RogerWilco08** [comment]
Gg les gars, l'underground de bas niveau, nous qu'en on piratais les clefs de canal plus on a abandonné quant les clef changeaient tt les 10 min. Trop de taff pour rien. Vous un changement URL et hop vous savez plus ou aller.

J'ai des dé et ré installé vstream,  j'ai eu droit à une mise à jour qui m'a péter tt mes favoris, top, plus une autre mise à jour qui marche pas et tout ça pour rien lol bravo continuez comme ça.

Heureusement que c'est gratuit. 

Bonne continuation si on peut dire.

**Comment by johngf** [comment]
encore un qui se prend pour ce qu'il n'est pas remets en question tes compétences avant de critiquer

**Comment by LordVenom** [comment]
Allais encore un banni , profiter ça n'a pas d'importance sur l'utilisation de l'addon pour l'instant.

**Comment by adulescente** [comment]
Whatttt???
D'accord..  Je suis tout à fait consciente que ce thread ne me regarde en rien... Que voulez-vous, je suis curieuse lorsque je suis à la pêche aux infos... 

Mais J'ai eu comme un besoin pressant de lancer une fléchette empoisonnée à ce Roger machin-truc qui crois que son ca ca ne pu pas...

C'est vraiment d'un pathétisme à dénoncer... 

 Comme l'a déjà dit Einstein: "Deux choses sont infinies : l'Univers et la bêtise humaine. Mais en ce qui concerne l'Univers, je n'en ai pas encore acquis la certitude absolue."

Fallait que ça sorte...
Et ce que j'en pense est bien pire dans ma tête...

A+
Jue
