### ISSUE TITLE
JWplayer

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2219]
JWplayer est un hoster dispo sur zonestreaming et streamingk. Si quelqu'un à un peu de temps à perdre pour m'expliquer comment faire le fichier. Je vois bien qu'on termine par des liens googledrive.
[le fichier](https://pastebin.com/h0kC1M0E)

**Comment by TmpName** [comment]
Je viens de tester sur streamingk, un lien JWplayer est en fait un truc de ce genre chez moi

h ttps://li nkrag.com/st?api=5821799852a075f4ad9432eefa73332cf053130f&url=http://filmhdstream.net/player/embed.php?f=JCrtLCbsN7OiLhPR4FZzDROzDKeGwROTNan1uRPiuYQjXQPonfrEbeSolcHFbREG4RTA4Yw9b14vliP4DQMagM==

Donc si on prend 
http://filmhdstream.net/player/embed.php?f=JCrtLCbsN7OiLhPR4FZzDROzDKeGwROTNan1uRPiuYQjXQPonfrEbeSolcHFbREG4RTA4Yw9b14vliP4DQMagM==
Tu vas trouver dans la page
"ht tps://drive.google.com/file/d/1_tYpUdi1J05rR3jngkPe6326q6IYlX7z/preview"
Qui lui est gere nativement par Vstream, ou en tout cas le devrait.

JWplayer n'est pas un hoster mais un player, moi je decoderais le lien dans le fichier site, pour mettre en hoster directement le fichier google (moins de taff pr toi)
Surtout que je crois que ce truc est deja utilise sur certains sites.

**Comment by razorex** [comment]
oui c'est ça. donc du coup tu me conseille de renvoyer les liens en "filmstream" dans un showHoster.?
façon:
`                if '//goo.gl' in sHosterUrl:
                    import urllib2
                    try:

                        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0'}
                        request = urllib2.Request(sHosterUrl, None, headers)
                        reponse = urllib2.urlopen(request)
                        sHosterUrl = reponse.geturl()
                    except:
                        pass
`

**Comment by TmpName** [comment]
Heu j'ai pas compris ce que tu veux dire, mais a la facon de film_illimit_fr.
sur ce site  (du moins a l'origine) tu avais
1 - des hoster classique
2- des hoster redirige par goog.gl
3 - un player maison.

Pour le cas 3, y avait plus de clic a faire pour arriver sur le lien final, mais en hosters tu passais le dernier lein, celui de google.
En fait tout le boulot se fait dans le fichier site, pas dans un fichier hoster.

**Comment by razorex** [comment]
Désolé de n'avoir pas été assez clair. Par contre j'ai intégrer la récupération des liens jheberg et pour certain film çà beug, pour "Luna" par exemple, j'ai vu que pour robin des droits ont fait un url decode est ce que çà pourrait venir de là. j'ai ce défaut dans le log de kodi 
`line 382, in showHosters`
`for aEntry in aResult:`
`TypeError: 'bool' object is not iterable`

**Comment by TmpName** [comment]
???
La j'ai tjours pas compris ce que tu veux dire ^^, au pire fait tourner ton code, on y jettera un oeuil.

Moi je faisais ton code, tout serais dans le fichier site. apres y a pas de soucis on est pas a un hoster pres, mais ca va compliquer le truc car ca va etre un hoster qui va renvoyer sur un autre hoster.

**Comment by razorex** [comment]
Encore dsl j'ai mélangé les sujets. J'ai compris ce que tu veux dire, une redirection vers un showHoster qui "décryptera" l'url des liens filmhdstream.
Mon autre pb qui concerne zone streaming mais pas les liens jwplayer, suite à la récupération des liens jheberg il y a certains films (ex: Luna) qui n'affiche plus de liens. Et le log de kodi me met:
`ERROR:   File "C:\Users\****\****\sites\zonestreaming.py", line 379, in showHosters`
`ERROR:     for aEntry in aResult:`
`ERROR: TypeError: 'bool' object is not iterable`
pourtant pour la plupart des films ca fonctionne.
Par la même occasion si je fais un vslog je trouve ou le log???

**Comment by TmpName** [comment]
Bien vu, effectivement ca bloque tout les hosts, meme les valide, je corrige de suite.
Vslog ecrit la ligne dans le fichier log que tu es en train de lire.
Sino pour les logs j'utilise 2 methodes
1 - Y a une appli qui permet de lire les log de Vstream en direct, tres lourd, et qui bloque frequement chez moi, du coup je m'en sert plus
2 - faire un raccourcis sur le bureau du fichier "C:\Users\BRIX\AppData\Roaming\Kodi\kodi.log" pour moi. Du coup il me suffit de cliquer a la demande sur ce raccourcis pour avoir les logs

**Comment by razorex** [comment]
J'ai terminé le fichier et je l'ai mis dans la bêta. Merci encore de ton aide. J'ai un peu galéré avec le split je ne récupérais qu'une partie de l'url.
