### ISSUE TITLE
Probleme sur Lien Uptobox ZT

### ISSUE THREAD

**Issue by LeBarbu31** [Kodi-vStream/venom-xbmc-addons#2223]
Bonjour,

Tout d’abord merci pour cette addon fabuleux, et beau travail de l’équipe.

Mais voila, depuis quelque jours, je rencontre pas mal de problèmes concernant les liens Uptobox sur ZT et autre sites.
Pour faire simple, rien ne se lance tout simplement comme si le passage dl_protect ne se faisait pas.
Je précise bien avoir un compte premium fonctionnel.
Que le site ZT n’était pas en maintenance l'or de mes test.

Ceci est présent depuis la dernière MAJ.

Merci de me faire un retour si cela est général, 
Et si ce n'est pas la cas de m'orienter vers une piste à la résolution de ce problème.

**Comment by johngf** [comment]
essaie pass id #2214
