### ISSUE TITLE
Téléchargement très lent. 

### ISSUE THREAD

**Issue by Lesproges** [Kodi-vStream/venom-xbmc-addons#2225]
Bj
Je ne comprends pas pourquoi lorsque je souhaite télécharger un film sur zt avec abonnement premium real debrid je clique droit sur le fichier puis je choisi download, ensuite je choisi mon dd externe. Le téléchargement démarre mais avec une vitesse de pas plus de 500ko/s. Alors que le streaming marche super bien. Est-ce normal ?
Merci.

**Comment by TmpName** [comment]
Yep, Vstream n'est pas un logiciel de telechargement, cette fonction est pour les petites connexions, le telechargement est bride de maniere a ne pas prendre de bande passante du tout pour en laisser au maximum a kodi.

**Comment by Lesproges** [comment]
Ok je comprends très bien. Merci pour l'info !
