### ISSUE TITLE
1fichier premium renvoit sur un fichier introuvable

### ISSUE THREAD

**Issue by widze** [Kodi-vStream/venom-xbmc-addons#2228]
**Décrivez le bug**
Bonjour,

J'ai un compte premium 1fichier et j'ai configuré mon compte dans les paramètres vtream.
Cela fait pas mal de temps qu'aucun lien 1fichier ne marche (en utilisant comme source zone-telechargement) et que l'erreur fichier introuvable apparait.
Comme aucun lien ne marchait, j'ai comparé avec la version web sur mon PC et la je me suis aperçu en réalité que les liens fonctionnaient...
Y-t-il un bug ou le problème arrive seulement chez moi ?
Merci pour votre aide.

**Votre system**
 - OS: Android
-  Appareil Mibox
 - Version Kodi  17.6
- Version Vstream 0.6.5

**Comment by AzeRim** [comment]
Je viens de tester Stéphanie et Wolverine en 1080p avec mon compte 1fichier acces et ça fonctionnent plutôt bien. Je confirme quand même que la plupart des liens 1fichier meurent plus souvent et plus rapidement que ceux sur uptobox.

**Comment by AzeRim** [comment]
Pour info, 1fichier.com a imposé la réinitialisation du mdp fin juillet à ces membres sous peine de ne plus pouvoir utiliser leur compte. Tu peux réinitialiser avec le même mot de passe.

**Comment by widze** [comment]
Merci pour ton retour j'ai réinitialisé mon mdp, tout est rentré dans l'ordre :)
Ce qui est dommage c'est que vtream n'indique pas l'échec d'authentification mais seulement que le fichier est introuvable...

**Comment by TmpName** [comment]
Ha ?
Normallement c'est le cas, mais il se peut qu'il y ait un deuxieme message d'erreur qui passe de suite sur le premier, le rendant illisible.

**Comment by widze** [comment]
Oui ça doit être le cas, si vous voulez tester, mettez un mot de passe invalide et essayer de visionner un truc.
