### ISSUE TITLE
Open source le bon comportement

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2229]
J'ai lus cet article et ça me penser à certain utilisateurs qui sont passer ici.

https://framablog.org/2018/08/29/les-logiciels-libres-meurent-lentement-sans-contributions/

**Comment by LordVenom** [comment]
Clairement sans encouragement et sans personne pour suivre le code le mec fait ceux qu'il a besoin est stop.
Les 3/4 du code de vstream sont des demandes utilisateurs que perso j'utilise jamais.
Quand l'aventure à débuté ont ma fait de la pub, des encouragements et de l'aide c'est vrais que question communauter y a pas a ce plaindre est c'est pour ça que ça dure depuis 5ans. 
Mais dernièrement ont n'a sévis ont a bannis car le comportement des gens sans gène c'est pas tolérable.

Tous ça pour dire que quand vous aimer un projet dite le, quand vous pouvez aidez faite le et quand ça bug prener votre mal en patience si vous coder pas faite un rapport de bug et stop inutile de pete un cable ça vas juste nous énerver.

**Comment by TmpName** [comment]
Lol, ha merde, bon apres tout, derniere maj il y a 11 mois, pr un addon de stream c'est bizarre a la vitesse ou bougent les sites. Par contre en comparant les codes, on voit que les projets ont pas mal evolue depuis leur base commune.
