### ISSUE TITLE
help for webtv

### ISSUE THREAD

**Issue by jodathewise1969** [Kodi-vStream/venom-xbmc-addons#2230]
thank's for your great work. i'm an italian fan of frecnh tv so i'd like to view TF1 (for example) without geo restriction.
I can't see that from webTV with vstream in kodi 17.6. why it is impossible? can you help me?
thanks in advance

**Comment by LordVenom** [comment]
French please.

**Comment by Arias800** [comment]
You can use "Liste site Iptv" but it's unofficial link and you need F4mTester

**Comment by jodathewise1969** [comment]
merci pour les réponses.
pourquoi je ne peux pas utiliser le webtv?

**Comment by Ovni-crea** [comment]
Il faut que tu as f4mtester

**Comment by AzeRim** [comment]
Tv du web fonctionne pour moi sans f4Tester.
Je n'arrive pas a installé plugin.video.f4mTester-2.7.2.zip sur mon galaxy s7. J'ai ça 
ERROR: CAddonInstallJob[plugin.video.f4mTester]: The dependency on script.video.F4mProxy version 2.7.1 could not be satisfied.
Est-ce que je suis le seul?

**Comment by LordVenom** [comment]
Installe F4mProxy avant alors.

https://vstream.ga/repo/

**Comment by Arias800** [comment]
Alors pour F4mTester il faut F4mProxy (qui est lui aussi utiliser) . F4mTester n'est pas utiliser pour webtv car c'est des liens m3u8 donc pas utile. Et TF1 empeche la connection si la personne n'habite pas en France c'est pour ça que webtv ne marche pas pour toi @jodathewise1969

**Comment by AzeRim** [comment]
Merci la team. TF1 fonctionne bien sur vStream Televsion_music/Liste site iptv/Iptv Gratuit/France IPTV Links.

**Comment by Arias800** [comment]
Peut tu nous donner le contenu des log de Kodi après avoir reproduit l'erreur ?

**Comment by jodathewise1969** [comment]
![log error](https://user-images.githubusercontent.com/42840845/44915796-3a21d300-ad34-11e8-9c34-39e45be56495.png)

**Comment by jodathewise1969** [comment]
merci

**Comment by Arias800** [comment]
Je viens de vérifier et cette erreur apparait quand TF1 empêche la connexion si la personne habite en dehors de ces ville FR|GP|GF|RE|MQ|YT|NC|TF|WF|PM|BL|MF|PF|MC|AD donc on ne peux rien n'y faire

**Comment by TmpName** [comment]
Essayes sur le site web de tf1, si ca marche pas, ca ne marchera pas sur Vstream, c'est le lien officiel  qu'on utilise.

**Comment by TmpName** [comment]
Nope, c'est techniquement faisable, mais personne ne va le faire car le streaming demande trop de bande passante.
Et c'est bizarre que ca fonctionne car le point de sortie est aleatoire, donc tu as autant de chance de te retrouver en france comme au japon (meme si apparement ca reste en europe)

**Comment by johngf** [comment]
@jodathewise1969 tu peutx utiliser un vpn
