### ISSUE TITLE
Question : Est-il possible de synchroniser la base vstream entre plusieurs périphériques ?

### ISSUE THREAD

**Issue by widze** [Kodi-vStream/venom-xbmc-addons#2233]
Bonjour,

Est-il possible de synchroniser la base vstream entre plusieurs périphériques pour partager les bookmarks, avancement de lecture des différents médias ?
J'ai cherché mais pas trouvé....
Merci

**Comment by TmpName** [comment]
Tu es pas le premier a poser la question, et non je vois pas comment, les fichiers sont dans le dossier "userdata" propre a chaque ordinateur, et j'ai pas vu d'option dans Vstream pour changer ce repertoire (et le mettre sur un disque partage).
Au pire un script qui copierais les fichiers d'une machine a une autre, mais de faire ca, tu risques d'avoir d'autre prbs, corruption de database (jamais de copie quand l'appli tourne) ou d'ecraser des databases que au final tu voulais garder.

**Comment by LordVenom** [comment]
Y a un menu importer /exporter dans les paramètre de vStream, donc tu peux balader tes préfs mais les synchroniser ça je sais pas.

**Comment by widze** [comment]
Merci pour vos réponses. Donc ça confirme que ça n'existe pas.
L'idée serait par exemple de commencer un film sur une boxtv pour le continuer sur un portable. Y a que moi que ca intéresse comme fonctionnalité ?

**Comment by TmpName** [comment]
Ca par contre c'est faisable, kodi a une fonction de serveur media, pour diffuser un media sur tout les peripherique connecte sur le reseau.

**Comment by matojoli** [comment]
Bonjour, je me permets de mettre un lien qui pourrait aider je pense. C'est dans le wiki de Kodi, j'ai déjà fait la manœuvre pour les collection de média avec MySQL et ça marchait, je pense qu'une fois que c'est fait ça doit aussi fonctionner avec les Addons, mais à vérifier en pratique. https://kodi.wiki/view/MySQL/Sync_other_parts_of_Kodi
