### ISSUE TITLE
Erreur python dans les logs qui se répète en boucle

### ISSUE THREAD

**Issue by ttoto69** [Kodi-vStream/venom-xbmc-addons#2235]
**Décrivez le bug**
WARNING: CPythonInvoker(27, /home/osmc/.kodi/addons/plugin.video.vstream/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE

**Votre system**
 - OS: [OSMC]
-  Appareil [raspberrypi]
 - Version Kodi  [17]
- Version Vstream 0.6.5

**Nous devons le reproduire**
Pour cela il nous faut:
regarder les logs

**Plus**
Le message s'affiche en boucle

**Comment by LordVenom** [comment]
Bonjour, nous sommes au courant mais ça n'a pas incidence sur l'utilisation de l'addon.

**Comment by TmpName** [comment]
Yep, pas d'incidences "visibles", d'ailleurs si y en a qui ont des infos la dessus, je suis prenneur.

**Comment by 9962500116** [comment]
E-Wallet:110000801268326,swetyyujg@gmail.com
