### ISSUE TITLE
Bug d'affichage du numéro de saison sur série ou animé

### ISSUE THREAD

**Issue by AzeRim** [Kodi-vStream/venom-xbmc-addons#2237]
Décrivez le bug
L'affichage du numéro de la saison ne change pas quand on sélectionne une 'autres saisons disponibles pour cette série'. Ce bug avait déjà été résolu sur une version antérieure de vStream mais il est de nouveau présent. Sur le site de ZT, il ne semble pas y avoir de problème. Ce bug est déstabilisant car on visionne bien la saison souhaité mais avec une désignation différentes. 

Votre system

OS: [Android]
Appareil [smartphone galaxy S7]
Version Kodi [17.6]
Version Vstream [0.6.5]
Nous devons le reproduire
Pour cela il nous faut:

Le nom du site [zone telechargement]
Le titre du fim/serie [Ballers ou tokyo ghoul]
Le nom du host
Log

Image

Plus

**Comment by Arias800** [comment]
Fix normalement c'est bon j'ai pris en compte tout les pattern https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by AzeRim** [comment]
Merci @Arias800 , ça fonctionne bien avec ta modif.
