### ISSUE TITLE
fonction dl an play pour certains m3u8

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#2240]
bonjour, donc pour éviter les coupures avec les m3u8 qui me les brises :) genre ne_tu a certaines heures.
j'ai commencé ce code [la](https://github.com/johngf/m3) . (en test)
A la base j'étais partis sur du dl pure ensuite j'ai changer de directions plusieurs fois pour finalement trouver la meilleur solutions pour moi crée un fichier m3u8 avec des fichiers locaux (kodi le permet) Dl et play en meme temps avec threading et urllib3 qui normalement est installé par request vu qu'il l'utilise.
pour l'instant ne_tu tu_ne il y en aura d'autre que je n'ai pas encore testé

edit: la classe est annoté , peu de modifs dans les autres fichiers.
prise en charge dans default,menu context, petite modif host

**Comment by LordVenom** [comment]
Je suis pas sur mais pour moi urllib3 c'est une lib à importer 
https://kodi.wiki/view/Add-on:Urllib3

Importer par request qui lui et importer par vstream mais pas dans les imports obligatoire et pas sur que ce soit compatible Kodi 16.

**Comment by johngf** [comment]
alors le code fonctionne sur kodi 16.1 mais l'import d'urllib3 j'ai pas testé

**Comment by LordVenom** [comment]
J'ai peur que si ont force request l'installation de vstream soit refuser à kodi 16.

**Comment by johngf** [comment]
la je teste une modif  sur kodi 16.1 en important urllib3 depuis le module request ça tourne correctement

**Comment by TmpName** [comment]
Donc ton code permet du coup de dl des fichiers fragmentes pour une playlist m3u ?

**Comment by johngf** [comment]
oui il dl les fichiers a l'intérieur des m3u8

**Comment by TmpName** [comment]
C'est bon ca, je sais pas pour l'integration dans Vstream, mais tres beau projet, moi aussi j'ai des prb avec netu et meme pas myen de faire de la mise en cache.

**Comment by johngf** [comment]
pour le moment ça fonctionne j'ai test sur kodi 16.1 17.1 17.6

**Comment by TmpName** [comment]
On fait quoi pour l'integration dans Vstream ?

**Comment by johngf** [comment]
Aucune dépendance supplémentaires n'est nécessaire 
Vstream utilisé deja request donc dans dans tous les cas urllib3 est inclu 
Request en a besoin 
Donc fonctionne reste à intégrer details mineur une popup info en cas de fichier introuvable.

**Comment by TmpName** [comment]
Et tu vas l'integrer comment ?
Activer "DL+visualiser" pour netu ?

**Comment by johngf** [comment]
Via le fichier hoster une entrée menu clic droit

**Comment by johngf** [comment]
J'y est pensé au début et après avoir regardé le code j'ai décidé de faire un truc à part plus simple
- le but n'est pas de dl mais ne plus avoir de coupure dès qu'il y a de la musique ou de l'action dans le film .
- certains hoster ont mp4 ou m3u8 / ou mp4 et m3u8 ou m3u8 à l'intérieur d'un m3u8 donc je fais le tris dans le fichier host
- je veux pas attendre pour play donc pas de dialog explorer ou progression du dl ou pause quelconque, tu clic dès que les 5 premiers fichiers sont dl le player démarre.
- il ne sera pas compatible avec l'iptv ou d'autres livetv  (Pas testé) vu les fichiers m3u8 bizarre ou il manque des bout ex tf1 4 ligne donc à mon avis nécessite une nouvelle requête à la fin du premier m3u8. 
- je teste l'hoster avant de l'activer compatible ou pas et modif si nécessaire. 
-
