### ISSUE TITLE
N_tu

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2241]
Les liens n_tu ne s'ouvre pas et je sais pas si c'est un bug du code de n_tu ou du fichier site

-OS: [Windows]
-Version Kodi  [18 beta 1]
-Vstream 0.6.55

-Le site : Monde des Cartoon ( https://pastebin.com/VVkK565M )
-Le dessin animé : Adventure Time s09 episode 07
-L'host : N_tu

**Comment by johngf** [comment]
les liens ne tu fonctionne post le lien pour voir a quoi il ressemble

**Comment by Arias800** [comment]
Le liens récupéré sur le site c'est ça : `https://hq_.tv/player/script.php?3` et ensuite il y a ce liens dans les log `https://h_q.tv/sec/player/embed_player.php?iss=MTkyLjE2OC4yMTkuMjAy&vid=RXBqdWVKRitoNHZGZ3lvWFV5U3VqUT09&at=712c14705b8de31c7c444c245a7ed8c6&autoplayed=yes&referer=on&http_referer=aHR0cDovL2ZyZW5jaC1zdHJlYW0udHYvMTM3OTctdm9pci1tYXRyaXgtc3RyZWFtLWNvbXBsZXQtdmYuaHRtbA==&pass=&embed_from=&need_captcha=0`

**Comment by johngf** [comment]
le liens est sans doute mal récup il doit ressembler a ça ht tps://hq q.tv/player/embed_player.php?vid=kanVc4tZh3vz&autoplay=none

**Comment by Arias800** [comment]
Oui mais les liens google drive c'est des pack de saison c'est pour ca qu'il est pas utiliser ^^

**Comment by TmpName** [comment]
Apparement il faut utiliser l'id et le lien est code par un code lui meme code avec WISE.

**Comment by TmpName** [comment]
Je pense avoir trouver la page.
```
function makeid(t) {
  var text = "";
  var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  for (var i = 0; i < t; i++) text += possible.charAt(Math.floor(Math.random() * possible.length));
  return text;
}
if (typeof netu_player_datas !== 'undefined') {
  if (typeof netu_player_datas.height === 'undefined') {
    netu_player_datas.height = '100%';
  }
} else {
  netu_player_datas = {
    'height': '100%'
  };
}
if (typeof netu_player_datas !== 'undefined') {
  if (typeof netu_player_datas.width === 'undefined') {
    netu_player_datas.width = '100%';
  }
} else {
  netu_player_datas = {
    'width': '100%'
  };
}

function ch_video_sup() {
  var video = document.createElement("video");
  var mediasupport = {
    video: (video.play) ? true : false
  };
  return mediasupport.video;
}
var _0xf70b = ["\x2E", "\x69\x6E\x64\x65\x78\x4F\x66", "\x73\x75\x62\x73\x74\x72", "", "\x6C\x65\x6E\x67\x74\x68", "\x25\x75\x30", "\x73\x6C\x69\x63\x65"];

function un(_0xf43cx2) {
  if (_0xf43cx2[_0xf70b[1]](_0xf70b[0]) == -1) {
    _0xf43cx2 = _0xf43cx2[_0xf70b[2]](1);
    s2 = _0xf70b[3];
    for (i = 0; i < _0xf43cx2[_0xf70b[4]]; i += 3) {
      s2 += _0xf70b[5] + _0xf43cx2[_0xf70b[6]](i, i + 3)
    };
    _0xf43cx2 = unescape(s2)
  };
  return _0xf43cx2
};
var isPhantom = !!window.callPhantom;
if (!isPhantom) {
  var isPhantom = !!window._phantom;
}
if ((!isPhantom) && (ch_video_sup())) {
  document.oncontextmenu = function() {
    return false;
  };
  document.onselectstart = function() {
    return false;
  };
  document.onkeydown = function(e) {
    e = e || window.event;
    if (e.ctrlKey) {
      if ((e.keyCode == '85') || (e.keyCode == '67') || (e.keyCode == '65') || (e.keyCode == '45')) return false;
    }
  };
  document.onkeypress = function(e) {
    e = e || window.event;
    if (e.ctrlKey) {
      if ((e.keyCode == '85') || (e.keyCode == '67') || (e.keyCode == '65') || (e.keyCode == '45')) return false;
    }
  };
  var domain_for_pl = 'hqq.tv';

  function create_netu_player(vid_f, hash_from_f, type, id_netu_player_f, height_f, width_f) {
    if (hash_from_f) var VJDIKS = '<scr' + 'ipt>self.location="https://' + domain_for_pl + '/player/embed_player.php?vid=' + vid_f + '&autoplay=none&hash_from=' + hash_from_f + '"</scr' + 'ipt>';
    else var VJDIKS = '<scr' + 'ipt>self.location="https://' + domain_for_pl + '/player/embed_player.php?vid=' + vid_f + '&autoplay=none"</scr' + 'ipt>';
    var timer = setInterval(function() {
      var RFGZM = document.getElementById(id_netu_player_f);
      if (RFGZM) {
        var doc = RFGZM.contentDocument;
        if (doc) {
          var OIFXFL = RFGZM.contentWindow.document;
          OIFXFL.open();
          OIFXFL.write(VJDIKS);
          OIFXFL.close();
        }
      }
    }, 500);
  }

  function create_player_old() {
    var id = makeid(5);
    if (typeof netu_player_datas.vid !== 'undefined' && typeof netu_player_datas.hash_from !== 'undefined') {
      document.write('<iframe webkitAllowFullScreen mozallowfullscreen allowfullscreen scrolling="no" frameborder="0" height="' + netu_player_datas.height + '" width="' + netu_player_datas.width + '" id="' + id + '"></iframe>');
      create_netu_player(netu_player_datas.vid, netu_player_datas.hash_from, true, id, netu_player_datas.height, netu_player_datas.width);
      netu_player_datas = undefined;
    }
  }
  create_player_old();

  function create_player() {
    var list = document.getElementsByTagName("div");
    for (l = 0; l < list.length; l++) {
      if (typeof list[l].id !== 'undefined' && list[l].id !== '' && typeof list[l].children[0] === 'undefined') {
        try {
          var o = JSON.parse(un('#' + list[l].id));
          if (typeof o.v !== 'undefined') {
            var id = makeid(12);
            var ifr = document.createElement("iframe");
            ifr.id = id;
            ifr.style.width = "100%";
            ifr.style.height = "100%";
            ifr.setAttribute('webkitAllowFullScreen', '');
            ifr.setAttribute('mozAllowFullScreen', '');
            ifr.setAttribute('allowFullScreen', '');
            ifr.setAttribute('frameBorder', '0');
            var name = list[l].getAttribute("name");
            if (name) {
              ifr.setAttribute('name', name);
            }
            list[l].appendChild(ifr);
            create_netu_player(o.v, false, false, id, netu_player_datas.height, netu_player_datas.width);
          }
        } catch (e) {}
      }
    }
  }
  create_player();
}
```

En utilisant l'id du code html sur la meme ligne id="07b02207602203a02206b06106e05606303407405a06803307607a02207d"

Mais j'ai pas encore teste

**Comment by johngf** [comment]
ba oui c'est le code js dont je parlais plus haut

**Comment by TmpName** [comment]
Code simplifie

<script>

id = '07b02207602203a02206b06106e05606303407405a06803307607a02207d'

var _0xf70b = ["\x2E", "\x69\x6E\x64\x65\x78\x4F\x66", "\x73\x75\x62\x73\x74\x72", "", "\x6C\x65\x6E\x67\x74\x68", "\x25\x75\x30", "\x73\x6C\x69\x63\x65"];

function un(_0xf43cx2) {
  if (_0xf43cx2[_0xf70b[1]](_0xf70b[0]) == -1) {
    _0xf43cx2 = _0xf43cx2[_0xf70b[2]](1);
    s2 = _0xf70b[3];
    for (i = 0; i < _0xf43cx2[_0xf70b[4]]; i += 3) {
      s2 += _0xf70b[5] + _0xf43cx2[_0xf70b[6]](i, i + 3)
    };
    _0xf43cx2 = unescape(s2)
  };
  return _0xf43cx2
};

var o = JSON.parse(un('#' + id));
window.alert( 'https://hqq.tv/player/embed_player.php?vid=' + o.v + '&autoplay=none');

</script>

Juste a le convertir en python

**Comment by johngf** [comment]
la lib que tu a fait ne peut pas l'exec

**Comment by TmpName** [comment]
Si, mais le code doit etre fixe, et il fait 10 lignes, pas trop dur a convertir.

**Comment by johngf** [comment]
deja var _0xf70b = [".", "indexOf", "substr", "", "length", "%u0", "slice"];

**Comment by johngf** [comment]
si tu l'execute en js ça donne du charabia `ްȠݠȠΠȠڰؐ۠ՠذ̀݀֠ڀ̰ݠޠȠ%u07d`

**Comment by johngf** [comment]
en faite je me disais bien que ce code me disait quelque chose je l'ai déja fait en python dans le hoster ne_tu

**Comment by johngf** [comment]
`def decodeUN(a):
    import json
    s2 = ""
    i = 0
    while i < len(a):
      s2 += ('\u0' + a[i:i+3])
      i = i + 3
      
    #pas trouvé autre méthode qui fonctionne  
    s3 = json.loads(s2.decode('unicode-escape'))
    
    s4 = "ht_tps://hqq.tv/player/embed_player.php?vid=" + s3["v"] + "&autoplay=none"

    return s4`

@Arias800 decodeUN(id)

**Comment by Arias800** [comment]
Bon bah pour le moment le site est down mais j'ai pas encore réussit a récupéré le code WISE

**Comment by johngf** [comment]
le site est hs la mais plus besoin du code wise tu récup l'id ex: '61464646546168' au dessus de script.php3
puis decodeUN(id)

**Comment by TmpName** [comment]
Lol, j'avais pas vu que el code etait deja dans le fichier host ^^
