### ISSUE TITLE
filmcomplet

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2242]
J'ai mis à jour les regex de filmcomplet mais les hosters sont passé en POST. est-ce que qqun peut m'aider et m'expliquer. Les données à récuperer sont elles là?? et comment les mettre en ordre. J'ai commencé à intégrer un showLink le [pastebin](https://gist.github.com/razorex/a48b4507799407d28e32de479f13eadf).
`<li id="player-option-1" class="dooplay_player_option " data-post="5698" data-nume="1">`
`<i class="icon-play3"></i>`
`<span class="title">TS</span>`
`<span class="server">openload.co</span>`
`<span class='flag'><img src='****/vf.png'></span> <span class="loader"></span>`

**Comment by Arias800** [comment]
Bon j'ai avancer mais j'ai erreur 400 donc il doit manquer un truc dans le headers https://pastebin.com/mXEFVBjU

**Comment by johngf** [comment]
test en ajoutant le referer >> sUrl (du film) si ça fonctionne toujours pas ajoute le cookie ou les cookies

**Comment by Arias800** [comment]
C'est bon ça fonctionne en utilisant urllib2 directement  https://pastebin.com/mXEFVBjU

**Comment by johngf** [comment]
bah si ça fonctionne avec urllib2 ça fonctionnera avec requestHandler de vstream ^^
faut bien faire la requete c'est tout

**Comment by Arias800** [comment]
Pourtant j'ai mis exactement la même chose mais avec requestHandler ça voulais pas bon bah je vais réessayer ^^

**Comment by Arias800** [comment]
Enfaite c'est bon j'ai mis a jour le pastebin je sais pas pourquoi hier ça voulais pas x)
