### ISSUE TITLE
ExtremeDown Page Next

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2243]
Salut et bravo pour cette source. Ça fait plaisir.
J'ai juste remarquer le problème sur le faite que ce soit impossible d'aller aux pages suivantes d'une catégorie. 
Ex: Dans Série >> Série VF >> Next = Chargement puis ça reste sur la même page 

ÉDIT: Juste pour dire que ça fonctionne quand on fait des recherches

**Comment by Arias800** [comment]
Corriger https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/extreme_down.py (ça fonctionne pour la recherche car que les deux fonction différemment ) ^^

**Comment by lebigboss** [comment]
Merci gg

**Comment by AzeRim** [comment]
J'ai pas bien compris. Comment on fait pour avoir le lien quand le clavier apparaît pour le recaptcha?

**Comment by Ovni-crea** [comment]
@AzeRim regarde dans le wiki il y a l'explication

**Comment by Arias800** [comment]
@Ovni-crea tu peux tester cette version sur android pour voir (même si ça m'étonnerait ) si ça copie automatiquement le liens dans le presse papier https://raw.githubusercontent.com/Arias800/Vstream-extreme-down/master/extreme_down.py

**Comment by Arias800** [comment]
C'est la seul solution que l'on a trouver pour ne pas être obliger de passer par une lib comme selenuim qui sont très lourde mais ce genre de script est amener a évoluer au fur et a mesure donc peut être qu'un jour ce ne sera plus nécessaire d'utiliser un navigateur ^^

**Comment by Ovni-crea** [comment]
@Arias800 j'ai tester sur Android sa copie pas automatiquement

**Comment by Arias800** [comment]
Ça m'étonne pas faut que j'essaie d'utiliser adb avec le module os de python peut être que ça peut passer  🤔

**Comment by Ovni-crea** [comment]
@Arias800 t'es sûr que ça va être possible parce que sur Android c'est impossible de copié collé

**Comment by Arias800** [comment]
Sur que ça va marcher non mais je peut toujours essayer ^^

**Comment by LordVenom** [comment]
J avais tester en activant l accès Web de kodi la conversation doit traîner quelque par.
