### ISSUE TITLE
recherche fonctionne plus ( 0.6.56)

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2246]
![correction film illimite](https://user-images.githubusercontent.com/40530593/45276417-a8436400-b4b1-11e8-8b15-c9f0469234c2.png)
**Décrivez le bug**
1:suite a la mise a jour 0.6.56 , la recherche ne fonctionne plus , en version 0.6.55 film illimité indiquait aucune information , la en version 0.6.56 film illimité est revenu mais la fonction recherche ne fonctionne plus a cause de film illimité , lorsque l'on supprime la source film illimité la recherche re fonctionne. 
j ai modifié la ligne 16 et 17 et tout fonctionne pour la recherche (voir photo)

2:autre point , lors de la recherche peut importe le titre du film , il y a plusieurs sources qui ne fonctionnent pas , au bas on voit plusieurs erreurs vstream , 
 
**Votre system**
 - OS: [Windows, Android] les deux peux importe
-  Appareil pc et boite android 
 - Version Kodi  17.6
- Version Vstream 0.6.5

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site vstream
- Le titre du fim/serie sur la recherche , pour tester j ai pris TAG (film)
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by KodiTopQuebec** [comment]
en photo plus haut j ai surligné les deux lignes en problème , la tout est revenu pour la recherche

**Comment by LordVenom** [comment]
Wé ça fait un bout de temps que j'ai pas fait une version officiel pour mettre a jour tous ça, mais c'est pas pour tous de suite encore trop de M... en ce moment.

**Comment by KodiTopQuebec** [comment]
+TmpName , oui film illimité fonctionne , c'est peut-être plus le ( é) a changer , mais j ai fait les deux et tout est fonctionnel , selon moi et plusieurs cette mise a jour est de loin la pire pour causer des problèmes , avant il n y avait pas de temps de recherche aussi long ( a cause des nouvelle source ajouter peut être) , d'habitude lorsqu' il y a une mise a jour c est pour régler des problèmes ou ajout de source , mais la oufff ce n'est pas le cas , si un admin regarde ceci ,j'aimerais être tester pour vous avant de publier une mise a jour .

**Comment by LordVenom** [comment]
Tu peux clone le github et faire des remonter sans soucis

http://vstream.ga/docs/clone/

**Comment by TmpName** [comment]
J'ai fait une modif hier, normallement ca corigeait le bug.
Apres tu peux desactiver toi meme les sources qui bloque (dans les parametres), mais par contre elles risquent de te manquer a un autre moment.
Perso je me sert jamais de la recherche, je vais dans mon site prefere, et j'utilise la recherche de celui ci.

**Comment by johngf** [comment]
non le temps de recherche dépend du temps de réponse des sites @KodiTopQuebec 
donc si le temps de réponse du site est long la recherche sera longue et pareil si il y a un site qui bug vstream attend 30 seconde avant le timeout si le site ne répond pas ou est trop long

**Comment by johngf** [comment]
par contre chez soucis avec le plugin youtube sans l'utiliser il interfère avec vstream comme ci il est toujours actif 
`17:35:11.469 T:1344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any media file
                                            Traceback (most recent call last):
                                              File "C:\Users\john-Q6600\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\player.py", line 74, in onPlayBackStarted
                                                self.current_video_total_time = self.getTotalTime()
                                            RuntimeError: XBMC is not playing any media file
                                            -->End of Python script error report<--`

[img](https://s22.postimg.cc/ue6mf8ok1/screenshot000.png)

**Comment by johngf** [comment]
je n'utilise pas youtube je suis dans vstream l'installe date de 2 jours j'ai essayé de de le mettre a jour mais il est a la bonne version du coup je l'ai deactivé

**Comment by razorex** [comment]
@TmpName pour skstream chez moi çà fonctionne.

**Comment by LordVenom** [comment]
quelqu'un peux confirmer qu'il n'est plus utiliser non plus dans les hosters ?

**Comment by TmpName** [comment]
Sisi, il est utilise en hosters, c'est rare, mais il sert pour des trucs 100% legaux comme les mangas non licencies ou de vielles series.

**Comment by LordVenom** [comment]
Alors je pige pas perso comme reference à plugin.video.youtube j'ai plus que meta['trailer'] chose qu'on peux virer puisque plus utiliser.

**Comment by KodiTopQuebec** [comment]
autre petite chose pour cette mise a jour 0.6.56 , maintenant kaydo(hds.to) n est plus la , pour voir aller a film/film (qualité hd) , kaydo n'y est pas , pour le faire revenir mais cela enlève la mise a jour 0.6.56 si l'on fait une mise a jour de vstream a partir du repo ,kaydo est revenu mais film illimité ne fonctionne plus , Pourquoi kaydo n'y est plus ?

**Comment by johngf** [comment]
@TmpName le plugin youtube lui meme n'est plus utilisé a la place il y a un fichier hoster que j'ai fait il y a lgts pour le remplacer

**Comment by KodiTopQuebec** [comment]
vu que ma mise a jour de vstream est so so , j ai fait un test , j ai tout effacé vstream ( et même dans add-on data le plugin) , j ai réinstallé et été changer l'url dans resource/site/film illimit_py , comme la photo et tout est parfait , la seul chose a ne pas faire est la foutu mise a jour en vert en haut ....kaydo et film illimité , la recherche tout est parfait 
![film](https://user-images.githubusercontent.com/40530593/45434322-ae963380-b69d-11e8-8e7c-6fe0381c0ecc.png)

**Comment by LordVenom** [comment]
Ok plugin.video.youtube virer des addons obligatoire a la prochaine maj XD

**Comment by AzeRim** [comment]
La page vstream.ga/repo affiche:
The page you are looking for cannot be found.404
Pouvez-vous voir pourquoi?

**Comment by LordVenom** [comment]
Ça n existe plus c est normal plus d hébergeur

**Comment by AzeRim** [comment]
Du coup, on fait comment pour avoir les fichiers officiels?

**Comment by TmpName** [comment]
Respositary officiel ici https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.0.3
Le lien est sur la premiere page.

**Comment by johngf** [comment]
j'ai update voir films il reste un soucis de nextpage la 2eme page bug donc tourne en rond 
plus le temps aujourd'hui

**Comment by TmpName** [comment]
Ben le premier lien est justement le lien du repositary, pour l'installer et mettre a jour via kodi

**Comment by Niconimes** [comment]
Bonjour, tout d'abord merci pour le taff que vous faites, Vstream a (presque) changé ma vie, c'est un addon vraiment remarquable.
Je tiens à remercier aussi KodiTopQuebec pour la solution à ce problème de Recherche impossible que je n'arrivais pas à résoudre.
Merci à tous et longue vie à ce super Addon 👍

**Comment by LordVenom** [comment]
@AzeRim  Sans passer par un navigateur faut trouver un repo qui possede vStream ont ne gère plus cette fonction. Pour nous c'est le zip sur le github c'est tout.

**Comment by TmpName** [comment]
Ha ?
Ca marche plus d'installer le repo officiel du site ?

**Comment by TmpName** [comment]
Et en passant par le zip du repositary du github ?
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/download/0.0.3/repository.vstream-0.0.3.zip
