### ISSUE TITLE
Légal ?

### ISSUE THREAD

**Issue by Winxglo** [Kodi-vStream/venom-xbmc-addons#2247]
Salut,

Je m'explique concernant le titre : j'ai déjà reçu une lettre de la part d'hadopi concernant des téléchargements de films en torrents. Je sais que normalement, hadopi ne fait rien sur le ddl (comme zone telechargement par exemple) et sur le streaming (il me semble). Et donc je voulais savoir si kodi utilise le réseau p2p (ou vstream l'utilise t'il ?) ou si ce n'est pas cela, je peux le faire en toute tranquilité sans avoir peur d'avoir des policiers au dos de ma porte pour me dire "non non non". Et j'adorerais avoir des explications sur kodi aussi

Merci bien

**Comment by TmpName** [comment]
Nope, absolument tout passe par http, comme si tu regardais le film via navigateur. Pour les hebergeurs speciaux c'est pareil, protocole http.

Kodi est juste un lecteur, c'est l'addon qui lui donne un flux a lire, et l'addon peut le prendre via le protocole http comme vstream ou p2p comme pop corn.

**Comment by Winxglo** [comment]
Ah ok donc en théorie, je n'aurais aucuns problèmes avec hadopi ? Merci beaucoup :)

**Comment by LordVenom** [comment]
Tu n’héberge pas de fichier avec le Streaming à part ton fournisseur d’accès personne ne sais ceux que tu regarde et les fournisseurs ne fournisse pas les info aussi facilement.
