### ISSUE TITLE
La recherche recommence lorsque l ont sort des liens 

### ISSUE THREAD

**Issue by Christian26800** [Kodi-vStream/venom-xbmc-addons#2248]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Christian26800** [comment]
Enfaite quand je fais une recherche je vais sur le premier lien par exemple et que le lien ne fonctionne pas alors la recherche se lance à nouveau au lieu de tomber sur les résultats des autres sites .

**Comment by johngf** [comment]
pas très précis ... (recherche a partir d'un site, recherche de base, recherche visuelle ???)
sur quel lien ça plante ?
tu as kodi 18 ?

**Comment by LordVenom** [comment]
@Christian26800  Sinon tu peux remplir le post correctement ?

**Comment by Christian26800** [comment]
J ai kodi 17.4 et pour vstream 0.6.56  et C est pour toute les recherches  .  Quand je suis sur un lien netu par exemple et que le lien ne fonctionne je reviens un cran en arrière et là la recherche recommence.

**Comment by LordVenom** [comment]
- Utilise les outils pour vider tes caches.
- Désinstalle et réinstalle.

**Comment by Christian26800** [comment]
Ok cela a fonctionné. Merci pour votre aide .
