### ISSUE TITLE
Couleur sous titres

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#2249]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Une description claire et concise de ce qu'est le problème. Ex. Je suis toujours frustré quand [...]

**Décrivez la solution que vous souhaitez**
Une description claire et concise de ce à quoi vous voulez arriver.

Bonjour , question bête , peut on changer la couleur des soustitres incrustés , dans les séries ,  par exemple :

Jack Ryan - Saison 1 [COMPLETE] 
Qualité Webrip | FRENCH sur ZT 

Systeme utilisé Android
Derniere version de Kodi utilisé (17.6)
Version Vstream 0.6.5.6

**Comment by LordVenom** [comment]
Alors la pas que je sache non.

**Comment by Arias800** [comment]
Si c'est le sous titre que Kodi lis de mémoire dans Paramètres -> lecteur -> langages (avec les paramètres en expert )  il y a le choix pour changer les couleurs

**Comment by TmpName** [comment]
Par contre dans le second cas, c'est incruste a la video, donc c'est mort.

**Comment by johngf** [comment]
une petite recherche sur google et t'aurais eu la réponse .
tu peux le faire manuellement si c'est un mkv  > demux > recupr fichier srt ou ass >edit notepad ou autre editeur
