### ISSUE TITLE
Recherche reste vide 

### ISSUE THREAD

**Issue by sparkyx** [Kodi-vStream/venom-xbmc-addons#2250]
Quand on fait une recherche , quelque soit le mot clef, le résultat est toujours une liste vide, comme si rien n'avait été trouvé. Hier , avec le mot "Alien" j'avais un résultat , aujourd'hui après la mise à jour vers la version 0.6.5  , la reste vide

**Votre system**
 - OS: OSMC ( Linux sur arm)
-  Appareil Raspberry
 - Version Kodi  17.6
- Version Vstream 0.6.5

**Nous devons le reproduire**
Prenez "Recherche" => un mot simple (anna , alien, terreur , espion,...) , quand la recherche se termine , aucune liste ne s'affiche

[kodi.log.gz](https://github.com/Kodi-vStream/venom-xbmc-addons/files/2379090/kodi.log.gz)

**Comment by LordVenom** [comment]
Voir https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2246

**Comment by sparkyx** [comment]
merci , mais quel est la solution simple ? Effacer , réinstaller ? Corriger le fichier "film_illimit_fr.py" ??? Remettre la version précédente , la version d'il y a 4 jours ?

D'avance merci :-)

**Comment by LordVenom** [comment]
Simple : désactiver film illimité et penser à le réactiver la prochaine mise à jour.

**Comment by sparkyx** [comment]
j'ai supprimé les 2 fichiers film_illimit_fr.py et film_illimit_fr.pyoc + changez dans setting.xml.

**Comment by TmpName** [comment]
Lol, ca marche aussi mais c'est plus brutal.
Tu peux juste le desactiver dans les options.
