### ISSUE TITLE
IPTV

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2251]
Bonjour à tous,

Tout d'abord merci pour tout le travail effectué, c'est top.

J'ai une question, j'ai bien f4mTester, les chaines tv marchaientt relativement bien mais depuis hier plus rien. Je lance une chaîne et cela se referme aussitôt.

C'est un problème globale ou juste moi?

Si vous avez besoin d'info ou fichiers log dites moi juste lequel je dois vous envoyer.

merci à tous 

Bonne soirée

**Comment by yvandicara** [comment]
Merci pour ta réponse. Je vais faire les logs cette apres midi. D'autre pas j'ai remarqué que le fichier de liste tv date du 12 septembre comme si elle ne se mettait pas à jour.

**Comment by Arias800** [comment]
Après les liste sont récupérer sur des site internet donc si eu ne les mettent pas a jour je ne peut rien y faire ^^

**Comment by adsav1** [comment]
J'ai le même cas

**Comment by Arias800** [comment]
Des nouvelles ?

**Comment by yvandicara** [comment]
Bonjour,

Bon c'est revenu. Ce qui serait intéressant c'est d'avoir un message d'erreur quand les chaines ne sont pas disponibles. Du genre lien non accessible. Merci à tous en tt cas.

**Comment by yvandicara** [comment]
Voila mon dernier log au cas ou. J'ai quand mm certaines chaines qui ne marchent pas 

https://slexy.org/view/s2KTFmo3KG

**Comment by Arias800** [comment]
Pour savoir si le lien est mort il faut voir si il y a cette ligne dans les log  `AttributeError: 'NoneType' object has no attribute 'recv'` si elle apparaît alors le liens est mort

**Comment by adsav1** [comment]
On dirait que F4mtester ne fonctionne plus, quand je lance n'importe quelle chaine cela s'ouvre et se ferme direct, obligé d'installer l'addon à la main en passant par le ZIP et impossible de le mettre à jour (il dit échec)?

**Comment by TmpName** [comment]
Des logs ?

**Comment by adsav1** [comment]
https://transfernow.net/022gaex0c1ie

**Comment by TmpName** [comment]
Ben y a des trucs chelou dans ton log Hiding/Showing window ou Process: Failed to restart AudioEngine after return from external player. Mais sinon toi ca a marche, tu n'as pas les memes prbs que @yvandicara.

Par contre la, faudrait presque voir sur le forum de f4mtesteur, c'est une usine leur appli.

Ca ca a pas l'air normal non plus

> 22:07:07.205 T:542373328112   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=play2__&sCat=6&sFav=play2__&sId=freebox&sMovieTitle=FR%3a%20Action%20HD&sThumbnail=tv.png&site=freebox&siteUrl=plugin%3a%2f%2fplugin.video.f4mTester%2f%3furl%3dhttp%3a%2f%2fxbox.ztv4you.com%3a25461%2flive%2fPD8fkEdbZ5%2fiz55nL9LQn%2f5236.ts%26amp%3bstreamtype%3dTSDOWNLOADER%26name%3dFR%3a%20Action%20HD&title=FR%3a%20Action%20HD

Et je ne trouve meme pas l'url du stream de depart pour tester.
Rajoutez VSLog(sUrl) a la ligne 552 ca va vous afficher l'url et testez la dans VLC.

**Comment by adsav1** [comment]
J'ai pas compris c'est ou le fichier VSlog?

**Comment by TmpName** [comment]
Bon j'ai trouve l'url encode dans ton log
 http://xbox.ztv4you.com:25461/live/PD8fkEdbZ5/iz55nL9LQn/5236.ts

Mais pas arrive a la lire.

**Comment by adsav1** [comment]
Comment faire pour décider si je lance une chaîne avec le player par défaut (tel) ou Locacast pour l'afficher sur ma TV?

**Comment by yvandicara** [comment]
Bonjour voici mon test de ce matin,

Television ==> IPTV GRATUIT ==> France IPTV LINKS

1/ FR:CANAL_HD ==> PAS DE PROBLEME
2/ FRANCE 2 HD (FR) ==> PROBLEME

Voila une video youtube du test https://www.youtube.com/watch?v=mS8vRLor1GE&feature=youtu.be

Voila les logs
https://slexy.org/raw/s20ETCkt3p?token=da8d63664ec18031cb997944ef5c414db8f999d242df8abbecb6d0db12948a0b&ts=1537433099


En faites j'ai l'impression que quand il y a des ( ) ou des | dans le nom de la chaîne cela ne marche pas..

Si vous pouvez faire le mm test exactement et me dire si cela est ok chez vous ou pas, cela me permettra de me rediriger vers un problème de parefeu. 

Merci

**Comment by Arias800** [comment]
Normalement lors de tout les test que j'ai fait quand il y a `NoneType' object has no attribute 'recv'`
