### ISSUE TITLE
Impossible d'effectuer de nouvelle recherche

### ISSUE THREAD

**Issue by Elarmix** [Kodi-vStream/venom-xbmc-addons#2252]
Bonjour ! Depuis aujourd'hui (je n'ai pas d'heure spécifique), il m'est impossible de faire de nouvelles recherches avec vStream. En utilisant l'historique, je peux acceder a ce qu'il avait charger, mais une nouvelle recherche n'affiche rien, si ce n'est les deux points pour retourner au menu

Tester avec un raspberry pi 3 et Windows 10 64-bits LTSC + kodi 17

**Comment by Ovni-crea** [comment]
@Elarmix installe la beta ça va te fixer le bug :+1:

**Comment by johngf** [comment]
@Ovni-crea ce n'est pas la solution miracle a tout ...
le mieux est de trouvé ce qui cause le bug chez @Elarmix 
sinon si vous voulez qu'on vous aide ,aidez nous aussi on arrete pas de le répéter 
 - **activer le mode debug dans les parametres de vstream** [outils](http://vstream.ga/docs/outils/) [fichier log de kodi](http://vstream.ga/docs/folder/)

**Comment by LordVenom** [comment]
voir https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2246

**Comment by Ovni-crea** [comment]
@johngf je sais mais j'ai dit de faire ça j'avais le même bug que lui sa venait de l'API tmdb

**Comment by Elarmix** [comment]
Merci pour vos réponses  ! Et désolé pour le peu d'infos que je vous ai donné hier, je devais faire vite. J'essaie de suite vos réponses et j'editerai le message avec ce qui a fonctionné ou non + les logs
