### ISSUE TITLE
Robin des droits

### ISSUE THREAD

**Issue by AzeRim** [Kodi-vStream/venom-xbmc-addons#2253]
Décrivez le bug
Les liens pour la Formule 1 ne s'affichent pas. Il y a indiqué 'aucune information'. Sur chrome, il y a la page ht tp://brightvar.bid/ qui apparaît avant la page ht tp://www.mylink.zone/ . Les liens Moto GP s'affichent. Sur chrome, il y a la page ht tp://www.mylink.zone/ qui apparait sur le lien.

Votre system

OS: [Android]
Appareil [smartphone galaxy S7]
Version Kodi [17.6]
Version Vstream [0.6.56]
Nous devons le reproduire
Pour cela il nous faut:

Le nom du site [Robin des Droits]
Le titre du fim/serie [Formule 1: Singapour-le Grand Prix du 16/09/18 (dans Sports Automobiles)]
Le nom du host
Log

Image

Plus

**Comment by TmpName** [comment]
Nouvelle version en place, a tester.

**Comment by AzeRim** [comment]
Merci @TmpName pour cette mise jour. Je vais pouvoir enfin regarder la vidéos de F1 en 1080p en stream.

**Comment by TmpName** [comment]
Nouvelle version en ligne.

**Comment by AzeRim** [comment]
Merci @TmpName pour cette modif. Ça marche nickel.
