### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2256]
j'avais dans l'idée de virer les icônes de site certaine sont moche et visuellement les icônes de toute les couleur ça m’énerve lol

J'avais pensé remplacer ça par des Identicons ça ce ferais automatiquement plus de dossier /art pour l'addon 

![screenshot000](https://user-images.githubusercontent.com/4380112/45739808-14ca0b80-bbf4-11e8-8cb9-1c1ee389c070.png)

**Comment by TmpName** [comment]
Ben moi j'aimais bien, c'etait plus facile pour reperer les sites (J utilise l'affichage par icone)
Apres en faire de moins flashy pkoi pas, ou de moins bne qualitee ?

**Comment by LordVenom** [comment]
Ok je laisse comme ça, pourris mon thème ? celui de base avec Kodi c'est a eux qu'il faut le dire XD.

**Comment by johngf** [comment]
sinon des icones similaires écrit en blanc sur fond transparent comme les icones de bases

**Comment by LordVenom** [comment]
![screenshot001](https://user-images.githubusercontent.com/4380112/45826616-1b8c7780-bcf5-11e8-992d-c89a0555d861.png)

![screenshot002](https://user-images.githubusercontent.com/4380112/45826632-21825880-bcf5-11e8-95a1-debe4c320f71.png)

Bon ok en vue icone le all blanc ça pique un peux lol aprés pourquoi écrire le nom il et dejas la

**Comment by LordVenom** [comment]
![screenshot003](https://user-images.githubusercontent.com/4380112/45827584-06184d00-bcf7-11e8-950c-acd55c87ea38.png)

**Comment by LordVenom** [comment]
![screenshot004](https://user-images.githubusercontent.com/4380112/45827694-4972bb80-bcf7-11e8-88fe-b394ce826303.png)

**Comment by johngf** [comment]
j'avais en tête des icones avec le titre qui utilise la police du fanart

**Comment by LordVenom** [comment]
Je me doute mais elle et pas dispo sur aucun api, perso c'etait plus pour virer le dossier art et ne plus s'en oqp puisque automatique.

**Comment by LordVenom** [comment]
![screenshot005](https://user-images.githubusercontent.com/4380112/45831423-9e1a3480-bcff-11e8-8abf-cc7cd8b63624.png)

**Comment by LordVenom** [comment]
Quoi je m'amuse tous seul XD bon ont vas laisser comme c’était avant d'accord lol

**Comment by TmpName** [comment]
XD.
Nan mais c'est pas con comme idee, faut juste trouver le compromis
Ton premier test, fait trop penser a github ^^, les memes icones que les avatars. Sinon essayes la proposition de @johngf .
En fait (dsl pour ta phobie des arc en ciel ^^) mais des icones randoms avec de la couleurs me suffirait pour reconnaitre les sites, avec le temps tu te souviens que le rouge c'est tel site et ect ....

Mais serieusement sans couleur j'ai du mal, j'ai un theme normal moi, homologue par des professionnels de l'optique et de l'esthetisme pas le vomi appelle "estuary".

**Comment by LordVenom** [comment]
Ben je trouve ça moche moi plein de couleur pixeliser c'est une des raisons pour laquelle je met ça toujours en liste le nom me suffis.

**Comment by TmpName** [comment]
C'est quoi le probleme avec la couleur ?
La suis habille avec un pantalon jaune, un sweet vert a rayure rose et des chausettes bleu, et ca va tres bien ensemble, regardes comment sont habille les super-heros ^^.

Avant qu'on me prenne pour un dingue, je precise que je deconne ofc.

**Comment by higuelzim** [comment]
Bonjour,

Je me permets de rebondir sur ce sujet mais avant tout je tiens a vous féliciter pour cet Addon absolument genial !!!!!!

Voila, il se trouve que depuis un petit moment, FILM ILLIMITE ne propose plus de vue en icône comme pour les autres serveur. Le choix est restreint a une vue en liste et ce n'est pas ergonomique visuellement parlant.

Pouvez vous y jeter un coup d'oeil pour le remettre la vue en plusieurs format comme précédemment 

Par avance merci et encore BRAVO pour tous les efforts fournis.

**Comment by TmpName** [comment]
Tu as essaye de regarder si ca ne venait pas de tes reglages ?
Tu vas sur la page sui deconne, "option de vue", "miniature" si c'est ca le mode icone ?

**Comment by johngf** [comment]
@higuelzim a raison il y a toujours le mode miniatures mais elle sont petite peut etre a cause de addlink au lieu de addmovie

**Comment by higuelzim** [comment]
Non plus de mode option de vue seulement sur FILM ILLIMITÉ, en revanche sur les autres pas de pb il y est!!!

**Comment by TmpName** [comment]
Ha yep, y a pas les memes mode de vue avec addlink et addmovie.
@razorex a corrige ca y a un jour.
