### ISSUE TITLE
Marquer comme lu

### ISSUE THREAD

**Issue by Topheur** [Kodi-vStream/venom-xbmc-addons#2257]
Bonjour à tous ;)

J'aimerais savoir si y'a moyen de marquer un épisode comme lu et si oui comment voir ce qu'on a déjà vu.. par exemple je recherche une série, je clique sur une saison et là j'ai une liste énorme de liens pour chaque épisode / chaque lecteur et j'arrive pas à savoir ce que j'ai déjà lu ou non.

Merci !

**Comment by johngf** [comment]
marquer comme vu clic droit ( sur android long clic ) sur le film ou l'episode un menu s'ouvre et marquer comme vue , pour le reste non pas possible a mettre en place mais tu peux utiliser les marque pages,
tu mets la saison en marque pages comme ça tu sais ou tu t'es arreté.

**Comment by Topheur** [comment]
Comment on fais ça ? Moi j'ai mis en Favoris c'est pas la même chose ? Je vois pas trop là où je me suis arrêté...

**Comment by johngf** [comment]
non pas pareil les favoris sont géré par kodi les marques pages par vstream mais ça fonctionne aussi
sur télécommande la touche menu (apres ça dépend des télécommandes des fois il faut l'attribuer manuellement en modifiant un fichier de kodi ou lirc c'est plus compliqué) 
a la souris message précédent

**Comment by TmpName** [comment]
Ou la touche W, commande de kodi.
