### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2258]
Faire le changelog me gonfle ça me prend 1h de temps pour pas grand chose donc stop.

- Le changelog et disponible toujours depuis l'addon - /parametre/apropos/changelog
- Le changelog et automatique et plus visuel maintnenant
- La modification visuel seras apporter au mise a jour semi-auto aussi enfin selon le rendu y a plus d'info a traiter.

![image](https://user-images.githubusercontent.com/4380112/45927284-52e76800-bf31-11e8-9050-e6679bbadfd4.png)

**Comment by TmpName** [comment]
Ca te demande pas plus de taff qu'un simple fichier texte ?

**Comment by LordVenom** [comment]
Ben si mais j’espère moin souvent XD puis c'est plus style quand même. Pour la mise mise a jour semi auto j'ai pas regarder encode ce code et tellement chiant a tester mais je vais le faire.

**Comment by LordVenom** [comment]
![screenshot007](https://user-images.githubusercontent.com/4380112/45954325-04a79700-c00d-11e8-950c-85e75ce5bd7f.png)

**Comment by TmpName** [comment]
Clair que par contre cote "Style", c'est mieux foutu que beacoup de fenetres de kodi.
