### ISSUE TITLE
ZT dans la bibliotheque

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2259]
Bonsoir à tous,

Savez vous si il existe un moyens d'ajouter en source bibliothèque les derniers ajout du site zone téléchargement ? 

Merci à tous

**Comment by TmpName** [comment]
Pas a la base, c'est des liens finaux vers fichier qui se mettent en favoris.
Apres via addons tierce ....

**Comment by yvandicara** [comment]
@TmpName merci pour votre réponse. Addons tierces ? ça m'intéresse :)

**Comment by TmpName** [comment]
Mais la je peux pas t'aider ^^.
Y en avait qui arrivaient a mettre sur la page d'acceuil de kodi ou en favoris (c'est pas la bibliotheque par contre mais si ca t'interesse ...) des pages de video tiree d'un hebergeur,  en bidouilllant je ne sais plus quoi, plutot un addon qu'un theme de memoire.
En faisant une recherche dans les issues tu as peut etre une chnace de trouver.

**Comment by Arias800** [comment]
Alors pour ajouter des source dans la bibliothèque de Kodi il y a l'addon add to lib et osmosis mais le problème c'est que de mémoire ce n'est pas possible d'ajouter la catégorie dernier ajout directement ^^

**Comment by LordVenom** [comment]
Bonjour, le plus simple pour suivre une source c'est de changer de skin par exemple pour avoir les nouvelle de ZT en page d'accueil on peux avoir un truc du genre.

![screenshot022](https://user-images.githubusercontent.com/4380112/46255700-8cbfed80-c4a0-11e8-9302-bc424643ffe0.png)

Faut que je pense a refaire un tuto je sais plus ou il est l'autre XD

**Comment by yvandicara** [comment]
@LordVenom ok je vois le truc, estuary mod de guilloz et création de raccourci. Ca m'a l'air pas mal. 
![20180930_211111](https://user-images.githubusercontent.com/10349444/46262103-008fe380-c4fd-11e8-9da0-194e85ebda29.jpg)

J'ai encore une question :) quand je lis un film sur un kodi et que je l arrête au milieu, si je lis le mm film sur un autre kodi, je peux reprendre au mm endroit ? Genre en récupérant la base de donnée vstream ? Yen a une en local ?
