### ISSUE TITLE
hi, Openload issue

### ISSUE THREAD

**Issue by ebs111** [Kodi-vStream/venom-xbmc-addons#2261]
lately alot of openload links wont work i mean it resolves the link just fine but wont play, but still the original links play just fine.
can you please take alook, thanks.
i have added an example link.
"ht tps://openload.co/embed/423zBYCDuyg"

**Comment by johngf** [comment]
no issue , the links work's the problem is only for you

**Comment by LordVenom** [comment]
French please close issues.
