### ISSUE TITLE
Le vrai site Zone-Telechargement

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#2264]
Bonjour

Le vrai site Zone-Telechargement dispo à cette adresse (attention aux fakes)

**Edit by Venom pas d'url**

**Comment by Arias800** [comment]
Alors le seul vrai zone téléchargement pour rappel a été fermer fin 2016 suite a l'arrestation des administrateurs du site qui dorme actuellement en prison donc non ton lien c'est aussi un clone ^^

**Comment by Vidalcris** [comment]
Et puis ce n'est plus ww3 mais ww4 ;)

**Comment by Arias800** [comment]
Yep il change constamment c'est pour ça que  vstream fait la redirection ^^
