### ISSUE TITLE
1fichier problème

### ISSUE THREAD

**Issue by Winxglo** [Kodi-vStream/venom-xbmc-addons#2266]
Salut,

Je souhaite savoir, j'ai regardé un film l'autre jour (taxi driver) et le film s'est arrêté juste avant la fin. J'avais pris Zone Telechargement et uptobox. Je souhaite donc savoir si il est normal que cela le fasse puisque cela passe par le stream d'uptobox donc limitation de temps (si c'est ça au final sert pas à grand chose l'extension je pense) ou si c'est un autre problème.

Merci beaucoup pour votre aide et si vous avez un bon site de streaming avec de la bonne qualité sur vstream, je suis preneur.

**Comment by johngf** [comment]
Ceux qui on un compte Premium n'ont pas de limitation de temps sinon c'est 2h il me semble

**Comment by Winxglo** [comment]
> 
> 
> Ceux qui on un compte Premium n'ont pas de limitation de temps sinon c'est 2h il me semble donc c'est utile pour quand on est Premium ou que le film dure moin de 2h

Et du coup tu connais un site de streaming dispo sur vstream en bonne qualité ? Car du bdrip pour les gros films j'aime pas trop :/

**Comment by johngf** [comment]
Il y pas ce que tu cherche ailleur je pense le 1080 ou supérieur est rare en stream ou ça bug à cause des hébergeur qui rame 
Tu veux quoi comme qualité ? Full bluray ? C'est mort il y a que sur zt que tu peux trouver ça et encore.

**Comment by Winxglo** [comment]
Je veux pas du full bluray, juste du hd minimum 720p quoi parceque bdrip ect aie :/ Sinon je vais devoir prendre un compte uptobox et je t'avoues que ca fait assez cher :/

**Comment by johngf** [comment]
Ah regarde kepliz / film illimité pour les film après ça reste rare sur les autres site 
Souvent c'est hdrip ou hdrip webrip
Par contre le 720p on en trouve souvent

**Comment by Winxglo** [comment]
Oue je vient de regarde c'est vraiment de la bonne qualité merci :)

**Comment by Winxglo** [comment]
Excuse moi, j'ai mit un compte 1fichier premium, mais je peux pas voir les films rien ne s'affiche comment ça se fait ? Le compte marche j'ai testé

**Comment by LordVenom** [comment]
Merci de lire : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2136

**Comment by Winxglo** [comment]
Très bien je vais rouvrir une issue pour indiquer comme précisé dans le formulaire le bug. Merci beaucoup et désolé :x
