### ISSUE TITLE
Une question pour ajouter une source #1

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2267]
La 1ere méthode testé mais le problème c'est les matchs qui affiche l'URL donc j'ai préfère d'utiliser cette méthode qui paraît le mieux mais la le fichiers n'est plus détecté est mon logiciel ne  détecte pas d'erreur de synthax donc je sais pas ou je me suis planté j'ai rechercher sur Google mais rien si quelqu'un peut me corriger je lui dit merci ^^

_Originally posted by @Ovni-crea in https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2212#issuecomment-424045802_

Quote @TmpName 

> ligne 1057, prb d'indent.

**Comment by Ovni-crea** [comment]
Bon maintenant je pense qu'il est fini https://pastebin.com/nsN49bf5
Il y a certains hosters que j'ai pas ajouté généralement on les vois rarement 
J'ai mis des commentaires sur chaque hosters ou je marque "terminé" qui veut dire fini
Si c'est marqué autre chose c'est a terminer plus tard
il y a thesport4u.net qui n'est pas terminer car en ce moment il y a pas de lien sur cette hébergeur en ce moment
PS: j'ai retiré les classement de ligues car j'ai prévu de le mettre dans un autre fichiers site sinon ça serait le 
Bordel dans le code ^^

**Comment by TmpName** [comment]
Proposes le deja sur le github, moi je serais toi je chnagerais le nom en SITE_NAME = 'Livetv.sx (Beta)' pour calmer les raleurs.
Comme ca ca sera plus facile pour trouver des testeurs que si il est sur un pastebin.

**Comment by Ovni-crea** [comment]
@TmpName d'accord je vais le faire

**Comment by TmpName** [comment]
Il est en place, a la prochaine MAJ les gens pourront la tester.

**Comment by Ovni-crea** [comment]
@TmpName d'accord pas de problèmes
