### ISSUE TITLE
Problème d'ouverture de plusieurs site.

### ISSUE THREAD

**Issue by helpmoi** [Kodi-vStream/venom-xbmc-addons#2268]
Bonjour/Bonsoir,

Décrivez le bug
Filmillimite ne s'ouvre pas ou lorsqu'il s'ouvre parfois il n'y a pas de film. 
Film complet ne s'ouvre également pas.
CineMegaToil ne trouve aucun film
FilmStreamVk tourne en rond, chargement infini (lorsqu'on clique sur le site)
Full streaming: Erreur certificat
LibertyLand: ne s'ouvre pas du tout. Il n'y a même pas de chargement. Pareil pour VoirFilms.
Skstream: erreur 404
VoirStream: ne charge aucun film

Votre system

OS: [Android]
Appareil [smartphone galaxy S8+ ou androidbox]
Version Kodi [17.6]
Version Vstream [0.6.6]

Nous devons le reproduire:
Voici mon log:
https://slexy.org/view/s21iwC6pZK

**Comment by LordVenom** [comment]
Bonjour, merci ont vas regarder ça.

- [ ] Filmillimite
- [ ] Film complet
- [ ] CineMegaToil
- [ ] FilmStreamVk
- [ ] Full streaming
- [ ] LibertyLand:
- [ ] VoirFilms
- [ ] Skstream
- [ ] VoirStream

**Comment by LordVenom** [comment]
Ok tous les sites joue au ww1 ww2 ww3 nouvelle mode ?  c'est quoi l'utilité ? , si c'est éviter les grabeurs vous allez souffrir encore plus de requête sur vos serveurs, alors Heureux !

**Comment by johngf** [comment]
le probleme @LordVenom  avec cette fonction [la](https://github.com/Kodi-vStream/venom-xbmc-addons/commit/197f2d2208b9266069a0722e54cdb754a0edc247#diff-8f7aadb0ac486707b3541ca0409e7805R20) c'est que a chaque fois que vstream load les sites  ou le site ça envoi une requete si on fait ça sur tous les sites qui change leur url la navigation va etre ralentis ou va planter si un site répond pas

**Comment by LordVenom** [comment]
Perso pour le moment je voie que cette solution aprés je trouve ça bizarre qu'on puisse pas faire de requête sur https://monsite.com/ obliger d'avoir le ww c'est pas logique puisque le site, le dns fait la redirection.

Sur filmcomplet si ont fait la quette sur http:// ça fonctionne jusqu'au Host qui ajoute un lien et la ça vas plus.

sUrl2 = URL_MAIN + 'wp-admin/ext...'

**Comment by TmpName** [comment]
@johngf a raison, c'est bien pour depanner mais sur le long terme, c'est a optimiser.

Il y a une autre methode, il suffit de ne pas utiliser URL_MAIN, mais de recuperer le debut de l'url, j'utilise ca pour la derniere partie de voirfilm (pour les hosters).

showmovies() : URL_MAIN = ww1.blabla
puis l'url deviens apres redirection
showsaisons() : www2.blabla/film1/hd
et a partir de la, a la place d'utiliser URL_MAIN on prend le debut de l'url > www2.blabla

2 problemes:
1 - ne marche pas systematiquement avec les favoris, surtout si c'est la page hoster qui est memorisee
2 - la page DOIT rediriger toute seule, si on tape www1.blabla sur firefox ca doit charger www2.blabla

Possibilite de mixer les 2:
Par exemple si oInputParameterHandler.getValue('siteUrl') est present utiliser cette valeur (en prenant l'hebergeur seul) sinon utiliser la fonction getRealUrl()

**Comment by johngf** [comment]
la fonction dans zt que j'ai fait fonctionne pour zt mais on va pas mettre dans settings toutes les url de site ?
faudrait la meme fonction modif en global

**Comment by TmpName** [comment]
Nope 100% d'accord avec toi. Faut trouver un truc plus leger.
Le prb c'est que je vois pas comment l'integrer dans le core de Vstream, et je veux vraiment pas faire d'usine a gaz. Dans request handler, ca charge une url et point, au pire ca donne la vraie url a reutiliser par la suite.
Apres pour l'avoir teste pour les derniers lien sur voirfilm, de prendre juste le debut de l'url a la place de URL_main, ca marche pas mal.

D'ailleurs j'ai pas de prb sur VoirFilm moi ??

Le je suis en train de tester filmillimte, c'est la fonction SucurieBypass qui fout la merde
Si je remplace par 
    oRequestHandler = cRequestHandler(sUrl)
    sHtmlContent = oRequestHandler.request()

Ca passe sans probleme par exemple, et du coup on a la bonne url pr le reste. Suffit de prendre le debut de l'url qui se trouve dans oInputParameterHandler.getValue('siteUrl')

**Comment by TmpName** [comment]
J'ai corrige Sucuri pour suivre les redirections si pas de protection.
Donc le site remarche sans prb avec la redirection, sans s'en occuper, justement car on ne se sert pas de URL_MAIN a pars dans la premiere fonction.

**Comment by helpmoi** [comment]
C'est peut-être parce que je suis de Belgique que voirFilm ne marche pas. Faudrait j'essaye sur mon pc si ça marche...

**Comment by LordVenom** [comment]
Chez moi VoirFilm tourne mais y a aucun lien fonctionnant sur le site aprés 30min à cherche un truc qui fonctionne sur leur site j'ai virer la source de vStream.

Pour les autres source tous a était passer au crible.

**Comment by johngf** [comment]
ça bug aussi sur le site lui meme voir films

**Comment by TmpName** [comment]
Attend on parle du meme voirfilm ?

**Comment by johngf** [comment]
bah oui

**Comment by TmpName** [comment]
Mais moi il marche ??? Je me sert de ce site un jour sur deux (c'est un de mes prefere) . Vous etes sur d'utiliser la bonne version ?
La je viens de retester, dernier ajout / gemini / aucun problemes.

**Comment by LordVenom** [comment]
Ben déFalse le alors XD

**Comment by TmpName** [comment]
Lol, pas de soucis, je le ferais dans quelques jours, mais je trouve ca bizarre d'etre le seul sans problemes, encore un truc a la Kaydo ?
Je m'en sert vriament tout le temps, catalogue fournis et tjours 2/3 hosters minimum fonctionnel sur les vielles series.

**Comment by helpmoi** [comment]
Bonsoir,
J'ai effectué la mise à jour 6.6.1.
La plupart des sites refonctionnent (gg :) ).
J'ai juste remarqué 3 soucis:
- french-stream : Erreur 404
- skstream : il a toujours le même soucis c'est à dire qu'une fois qu'on ouvre le lien il ne se passe rien du tout même pas de chargement...
- 3eme problème : Une fois qu'on clique sur "Film" puis "Film (derniers ajouts)" le temps de chargement de la liste des films à augmenter c'est passer de +- 5 sec à +- 25 sec. (Tester sur 3 machines différentes)

**Comment by Ovni-crea** [comment]
@helpmoi j'ai fait un pull request pour french stream c'est leur domaine qui avait changé ^^
Par contre désolé mais skstream fonctionne chez moi des que j'ouvre un lien il démarre normalement donc sa doit venir de chez toi (ou pas)
Par contre le 3eme problème je sais pas c'est le code de vstream je préfère pas y toucher tu vois ça avec les autres administrateurs car moi  je suis pas administrateur et je connais pas trop le code de vstream en lui même

**Comment by LordVenom** [comment]
Oups pour le temps de chargement c'est moi dsl. Alors attention pour les autres site en ww1 ww2

Mettre autre chose que du texte dans URL_MAIN fous la merde, la ça a ralentis tous l'addon. Pour ZT il et plus visible dans les addons à désactiver.

**Comment by helpmoi** [comment]
Non, je ne confonds pas. Le site est vraiment hs chez moi.

**Comment by Ovni-crea** [comment]
@helpmoi ta essayer d'aller sur le site sur un navigateur

**Comment by johngf** [comment]
@TmpName c'est juste qu'ils l'ont réparé entre temps voir films mais ça change rien faut trouver une solution globale pour les ww2 ww4 etc.

**Comment by TmpName** [comment]
Non, mais justement ce que j'essaye de dire, c'est que depuis la derniere version on se fou du chnagement d'url
La version actuelle c'est www2, sur navigateur www4 et tout marche, je viens de tester, le chnagement d'url n'est pas un probleme.
Si quand vous tapes la vielle url sur navigateur ca renvoit sur la bonne, vstream le fait aussi.

**Comment by helpmoi** [comment]
@Ovni-crea je viens d'essayer ça marche sur le navigateur mais pas sur vstream. C'est assez bizarre...

**Comment by TmpName** [comment]
Skstream ne marche pas chez pas, ni sur  navigateur ni vstream automatiquement.

**Comment by 1shad** [comment]
Certains sites sont bloqués au niveau des dns par les FAI, comme Sktr... par exemple.
Il suffit d'utiliser les dns de google ou autre chose que ceux de son FAI pour pouvoir
acceder de nouveau à ces sites.

**Comment by TmpName** [comment]
Ha wi, ca me reviens, frenchstrm avait ca aussi, et dedans y avait un code pour bypasser le service DNS.

**Comment by helpmoi** [comment]
Lorsque j'essaye de faire une recherche d'un film ou d'une serie le chargement ne se termine pas. En effet, j'ai une boucle infini. Est-ce que vous avez aussi ce problème ?

**Comment by TmpName** [comment]
Yep, ca arrive souvent, faut trier les sources.

**Comment by helpmoi** [comment]
J'ai ce soucis sur 1 ou 2 sites. Des liens ne s'ouvrent pas sur vstream mais s'ouvrent sur les sites en question. Par exemple, la série "Bull" saison 2 épisode 14-16 vf ne s'ouvrent pas dans filmstreamvf. J'ai ce problème avec d'autre séries et sites...
@TmpName

**Comment by LordVenom** [comment]
> Yep, ca arrive souvent, faut trier les sources.

Faudrait trouver un truc pour que les gens y pense je regarderais dans la semaine.

**Comment by higuelzim** [comment]
Bonjour, je viens juste preciser que le site FRENCH STREAM fonctionne mais par contre a l'ouverture d'un film, ce dernier ne propose qu'un seul lien "netu" qui ne fonctionne pas sur tous les films.

Encore merci pour cet EXCELLENT ADDON !!!!!!!!

**Comment by Arias800** [comment]
Netu a été corriger hier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/netu.py

**Comment by higuelzim** [comment]
Super merci Arias800 mais pourquoi le site ne propose plus tous les liens comme pour FILM ILLIMITE (rapide video, open load, etc...)?

**Comment by TmpName** [comment]
@helpmoi , les liens sur le site filmstrmvk sont out, serie dispo en vf sur Ianime par exemple

**Comment by helpmoi** [comment]
Les liens de libre-streaming aussi sont out... Je vais y jeter un oeil.
