### ISSUE TITLE
Question autour des différents lecteurs de stream

### ISSUE THREAD

**Issue by Aliasexterne** [Kodi-vStream/venom-xbmc-addons#2269]
Bonjour à tous ! 

Voilà depuis quelques jours une petite question me trotte par la tête: est-ce que quelqu'un connait et saurait où trouver des sources en 4K autre que via un lecteur uptostream? J'ai commencé à faire le tour ses sources et des lecteurs mais pour le moment j'ai du mal a trouver un lecteur qui le gère. D'où ma question aux utilisateurs pour savoir si pour le moment vous n'avez croisé sur votre route du stream que ce lecteur qui gère ( + ou - moins bien on ne va pas se le cacher) le format "4k". 

Merci d'avoir pris le temps de lire ma question et belle journée/nuit ou autre!

**Comment by Arias800** [comment]
Déjà que les vrai 1080p c'est presque que sur uptostream donc le 4k c'est uptostream seulement .

**Comment by Ovni-crea** [comment]
@Aliasexterne généralement pour voir un film en 4k il te faut un compte premium sur un hébergeur 
Je sais que uptostream le fait mais sinon passe par un debrideur c'est ce que je fais pour voir un film en 1080 ou 4k pour que ça soit fluide

**Comment by TmpName** [comment]
Pour moi ils ont tout dit.
C'est n'est pas un lecteur mais un hebergeur, a moins que tu regardes les videos sur navigateur, on n'utilise pas les lecteurs embarques mais le lecteur de kodi.
Donc en premium il y a beacoup de site comme uptobox ou 1fichier qui doivent avoir assez de debit.

Mais pour rappel, le stream 4k developpe en france c'est pas avant 3/4 ans, trop elitiste pour le moment, ne t'attend pas a des miracles pour pas cher.

**Comment by Arias800** [comment]
Et surtout le drm qui est utiliser sur les Blu Ray 4k a pour longtemps été inviolable chose qui n'est plus le cas depuis fin 2017 environ donc de toute façon ça prendra des années pour que les site de streaming si mettent ^^

**Comment by Ovni-crea** [comment]
@Arias800 ta raison surtout qu'un film en 4k prend énormément de place dans un disque dur

**Comment by Aliasexterne** [comment]
> C'est n'est pas un lecteur mais un hebergeur, a moins que tu regardes les videos sur navigateur, on n'utilise pas les lecteurs embarques mais le lecteur de kodi.

J'utilise bien le lecteur de Kodi, je me suis un peu embrouillé les pinceaux! 

> on surtout qu'un film en 4k prend énormément de place dans un disque dur
 Effectivement, d'où l’intérêt de les héberger ailleurs pour les streamer !

En tout cas merci beaucoup pour vos retours!
