### ISSUE TITLE
Streams NFL

### ISSUE THREAD

**Issue by Celtiore** [Kodi-vStream/venom-xbmc-addons#2274]
Bonjour,
super boulot pour votre addon, je viens de trouver ce site pour des streams NFL, si ca interesse quelqu'un...

Je suis intéressés par la fonction de l'addon pour les streams live reddit NBA, j'ai vu que c'etait en cours, si je peux aider pour des tests ou logs, ce sera avec plaisir,

merci à vous

**Comment by TmpName** [comment]
Alors d'abord je precise, je ne comprend rien au sport.
Ensuite quelqu'un est sur cette source https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/livetv.py
Il y a des chance que ton site fasse doublon, je pense ?
