### ISSUE TITLE
Mise à jour intempestives des widgets

### ISSUE THREAD

**Issue by king76** [Kodi-vStream/venom-xbmc-addons#2275]
Salut

Tout d'abord merci pour le travail sur cette extension, c'est ma meilleur ! Je l'utilise tous les jours.

Sauf que j'ai plusieurs widgets pour afficher les derniers films ou documentaires sur ma page d'accueil de Kodi via le thème Estuary MOD V2. À chaque fois, il y a une boîte qui s'ouvre pour exécuter une mise à jour. 
Y'a t'il moyen de modifier du code quelque part pour que cela ne se fasse qu'une fois par jour ?

Merci

**Comment by TmpName** [comment]
ha ?
Alors la ca m'interesse, tu aurais pas un screen ?
Car la seule MAJ de Vstream est justement concue pour se mettre en marche le plus rarement possible, pour ne pas defoncer le serveur.

**Comment by king76** [comment]
Hello,

Je ne parle pas de la mise à jour de Vstream mais des widgets ;-)

Merci

**Comment by king76** [comment]
Hello,

En effet j'avais vu une ancienne discussion a ce sujet, je voulais vérifier ou ça en était maintenant.

Je ne te connais pas LordVenom, mais j'ai cru comprendre que tu es l'auteur et le développeur de l'addon.
Quand tu dis qu'il n'y a pas de solution, c'est à cause d'une limitation de Kodi ? Si c'est le cas, on ne pourrait pas faire une demande aux développeurs pour offrir une option qui cacherai cette fenêtre pour la mettre dans les notifications ? Ou ajouter une option pour configurer la fréquence de mise à jour ? 

Je dis ça parce qu'en théorie y'a rien qui ne peut se faire en développement ;-)

Merci

**Comment by LordVenom** [comment]
lol oui pas de solution connue, j'ai pas fait asser de test pour savoir si ça vient de l'addon ou de kodi.

**Comment by king76** [comment]
Ok donc c'est pas toi qui a développer l'addon.
Sais tu dans quelle partie du code on pourrait regarder ça ?

Merci

**Comment by LordVenom** [comment]
Qu'est ce que tu met en widget ? TMDB ou des sites Directement.

Pour TMDB c'est sites/themoviedb_org
Pour les sites c'est sites/nomdufichier

**Comment by king76** [comment]
C'est des sites, exemple les derniers films de PapStream.

Merci je vais regarder ca

**Comment by LordVenom** [comment]
Ok donc c'est la popup de chargement le soucis tous les addons reload dans les widgets sauf qu'on et les seul a avoir une fenêtre de load et il serais une mauvaise idée de la virer mais faut voir si on peux lui indiquer de pas fonctionner si appeler en dehors de l'addon.

**Comment by LordVenom** [comment]
Si tu est connaisseur voici la popup criminel a ne pas supprimer mais a contourner.

```
progress_ = progress().VScreate(SITE_NAME)
            progress_.VSupdate(progress_, total)
            if progress_.iscanceled():
                break
progress_.VSclose(progress_)
```

**Comment by LordVenom** [comment]
@TmpName  tu avais pas fait un code pour voir si l’appelle était interne ou externe a vStream ?

**Comment by king76** [comment]
Merci LordVenom, c'est intéressant.

Je ne sais pas en quoi c'est programmé, mais je peux toujours chercher pour ajouter une condition à l’exécution de ce code et ne l’exécuter qu'une seule fois par jour et au moins une fois au démarrage de l'application. Pour ça il faudrait avoir une variable qui dit depuis combien de temps, Kodi est executé.

**Comment by TmpName** [comment]
Ben ca ma rappelle quelque chose, mais si on l'a vire, ca doit pas etre pour rien. Mais j'arrive pas non plus a trouver l'issue de l'epoque.

` sys.argv[0]`

Devrait afficher un truc different non ?

Apres le popup sert surtout si les metas sont activees, pour la page showmovie qui est assez rapide a voir pr le desactiver si pas de metas.

Mais vous mettez en widget sites/themoviedb_org, sys.argv[0] ne devrait pas afficher defaut.py, y a peut etre moyen de jouer avec ca.

**Comment by king76** [comment]
Heu c'est un peu du chinois lol

sys.argv[0] ça affiche quoi ? 

Les métas activées ? KESAKO ??

Si tu veux que je teste de quoi, fait le moi savoir, je peux ajouter un ligne ou un paramètre quelque part ;)

Merci

**Comment by TmpName** [comment]
Essayes ca

```
    import sys
    from resources.lib.comaddon import VSlog
    VSlog('******' + str(sys.argv))
```

Si j'ai bien compris le widget lance la fonction showmovie ? si c'est ca rajoute ces lignes en debut de fonction et ragrde les logs
1- en passant par vstream
2- en passant par les widgets

Tu vas voir dans les logs une ligne qui commence par '*******'*

Sinon je confirme, faut pas la supprimer cette fenetre, sur adkami par exemple, le site essaye d'afficher 3000 liens, sans possibilite d'annuler c'est la mort ....

**Comment by LordVenom** [comment]
Alors voici les investigation Sherlock :) (Je suis pas du tout entrain de regarder cette série)

1- Dans sys.argv[2] le widget ajoute une variable &reload=
2- Si ont demande l'id de la fenêtre xbmcgui.getCurrentWindowId() l'id home == 10000 sinon 10025

Alors c'est quoi le mieux je dirais currentID ça évite d'importer sys. mais la ou je bloque je regarderais demain c'est comment passé la fonction progress.

J'ai tester pass , return , return False mais il aime pas XD.

**Comment by LordVenom** [comment]
Pense bête pour pas sauvegarder la modif

```
    import sys
    print sys.argv
    print sys.argv[2]

    current_window = xbmcgui.getCurrentWindowId()
    print current_window
    if current_window == 10000:
        print "passeee"
    else :
        print "pooooooooooooooo"
```

**Comment by TmpName** [comment]
Je penserais comme vous watson, et je sais pas quelle de serie exactement on parle ^^, y en a tellement sur ce duo. Mais la variable, pas sur qu'un jour on ait pas la meme (&reload c'est plutot banal), et L'id home ca parait pas mal, impossible que dans vstream on soit sur la page home de kodi (ou de vstream ?), donc c'est forcement un widget

**Comment by LordVenom** [comment]
Oui c'est bon pour le début mais des test que j'ai fait cette aprem c'est pas concluant empêche de créer un objet ou le détruire passer la class ext.. bref c'est pas pour tout de suite XD dommage [sherlock](https://www.themoviedb.org/tv/19885-sherlock?language=fr-FR)

**Comment by LordVenom** [comment]
J'ai réussis houhou

Il fallais lui renvoyer une class j'ai donc crée une class vide et recréer les VSupdate et VSclose mais vide.

Correction disponible à la prochaine mise à jour.

**Comment by king76** [comment]
Salut les gars,

J'ai suivi ça de loin, pas eu le temps de faire des tests cette semaine, mais en même temps j'avais du mal à savoir de quoi vous parliez lol.

Qu'avez-vous réussi à faire finalement que l'on pourrait trouver dans la prochaine mise à jour ?

Parce que hier je regardais une série sur vstream et j'ai eu deux fois la fenêtre de mise à jour, grrr

Merci

**Comment by LordVenom** [comment]
Tu n'aurais plus la popup de chargement sur tes widgets, après il ce charge toujours la c'est pas nous qui gérons ça. Et oui pour voir la modif il faudra attendre la mise a jour automatique (pas de date précise).

**Comment by king76** [comment]
Désolé de réouvrir le post, mais j'ai appliqué deux mises à jour et je n'ai rien vu qui aurait changé, il y a toujours une demande de mise à jour, dès que je lance un film ou quand je me promène dans la liste de mes films. Peut être pas sur la page d'accueil, mais ailleurs oui.

Et vous ?

Merci
