### ISSUE TITLE
Site Streamonsport

### ISSUE THREAD

**Issue by Ludo57rule** [Kodi-vStream/venom-xbmc-addons#2280]
Bonjour, j’utilise tout les jours Vstream, c’est ouf comme extension, je vous en remercie

Je me posais une petite question, serait il possible d’intégrer le site Strea_monsport pour tout ce qui est des matchs et sport en tout genres

Sur la page d’acceuil du site il y’a les matchs a venir avec les liens

Il y’a un aussi un onglet chaînes H24, en gros c’est des liens de diffusion en live de différentes chaînes, du genre RMC Sport, Bein Sports, Canal +, Canal + Sport etc....

Serait-il possible d’intégrer cela ?

Merci beaucoup

**Comment by TmpName** [comment]
Alors je crois qu'il y a deja un truc du genre en beta https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/livetv.py

**Comment by Ludo57rule** [comment]
Alors oui je l’ai dans la dernière version, mais c’est pas les chaînes en direct.

C’est déjà très bien, mais je n’ai pas pu tester pour les matchs des championnats européens ou ligue des Champions, cause de trêve internationale.

Hâte de tester ça d’ici 1 semaine et demi

**Comment by informagenie** [comment]
A t-il déjà été intégré sur Vstream ? Puisque [Streamonsports ](https://site-de-streaming.com/streamonsports/)a pas mal de fois changé d'URL.

**Comment by TmpName** [comment]
Alors ce site en particulier je pense pas qu'il y soit. Apres j'ai pas regardé si ce n'etait pas les memes videos.
Pour moi un match de foot france/espagne et de rugby autriche/pologne, a moins de 50cm je vois pas la difference.
