### ISSUE TITLE
Problème de recherche

### ISSUE THREAD

**Issue by Benian86** [Kodi-vStream/venom-xbmc-addons#2281]
Bonjour. 

Depuis aujourd'hui, mon Vstream n'effectue plus de recherches a partir des sources.
Tout le reste fonctionne, on peut atteindre les vidéos via les sources direct, marque pages, films séries etc... Mais une recherche simple ou visuelle est impossible. La recherche ne se lance pas.
Que faire?

Merci

PS: j'ai désinstallé, réinstallé vstream. Nettoyé la cache, fait la dernière mise à jour, empêché la dernière mise à jour... Sans succès

**Comment by BENJI97200** [comment]
Bjr , pour moi aussi la recherche ne fonctionne pas et la navigation dans vstream est tres lente

**Comment by LordVenom** [comment]
Bonjour, 

Ca nous aide pas merci de remplir le rapport de bug.

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2136

**Comment by Benian86** [comment]
mon Vstream n'effectue plus de recherches a partir des sources.
Tout le reste fonctionne, on peut atteindre les vidéos via les sources direct, marque pages, films séries etc... Mais une recherche simple ou visuelle est impossible. La recherche ne se lance pas.

Système 1 :

*Android
*Box TV Android 8
*Kodi 18 beta 3
*VStream 0.6.62

Système 2 :

*Android
*Box TV Android 6
*Kodi 17.6
*VStream 0.6.62

Plus :

j'ai désinstallé, réinstallé vstream. Nettoyé la cache, fait la dernière mise à jour, empêché la dernière mise à jour... Sans succès

**Comment by Benian86** [comment]
Après quelques test, la recherche se déclenche après 2-5 minutes ( chrono ) et information supplémentaire, "zone-telechargements" prend quand même 3-4 minutes avant de passer a l'étape suivante.

**Comment by Benian86** [comment]
Problème réglé de mon côté.

Après réinitialisation complète de mon modem (Proximus)

Merci de votre suivi et longue vie à VStream
