### ISSUE TITLE
Erreur ssl zone telechargement

### ISSUE THREAD

**Issue by jeyjey43** [Kodi-vStream/venom-xbmc-addons#2284]
Lorsque je sélectionne la source ZT, j'ai systématiquement un message d'erreur "erreur : connexion impossible SSL..."

Voici l'URL du log :
https://slexy.org/views/s2000337DD

Merci pour votre aide

**Comment by gianniloup** [comment]
j’ai le même bug c’est énervant car je regarde presque tout mes animes/films sur zone téléchargement pour le HD 100% du coup la j’ai un peu le seum ..

**Comment by ludopotte** [comment]
Moi aussi quand je je sélectionne la source ZT, j'ai systématiquement un message d'erreur "erreur : connexion impossible SSL...". La Nouvelle Adresse est https://ww5.zone-telechargement1.org/ ou https://ww5.zone-telechargement1.org/index.php

**Comment by kenshiro000** [comment]
Perso je cherche directement mes liens sur le ZT2 .lol et je les colle dans la source extreme-download où il demande "Mettre ici le liens du hoster apres avoir passer les Recaptcha manuellement". C'est bien-sûr plus chiant mais au moins je suis sûr que le site et les liens fonctionnent bien.

**Comment by Arias800** [comment]
L'erreur ssl venait de la variable BUG_SSL qui ne fonctionne plus mais en parallèle zt a changer la manière donc marche dl protect donc ça va prendre plus de temps pour corriger ca ^^

**Comment by Arias800** [comment]
Bon j’arrête pour aujourd'hui alors pour le bug ssl voila ce que j'ai changer : https://github.com/Arias800/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/handler/requestHandler.py et le fichier de zt qui est en cours (pour le moment ça bloque avec une erreur 400) ici si jamais quelqu'un veux continuer  : https://github.com/Arias800/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by jay-jay69** [comment]
Soir,
Même problème pour film_illimité et Disney HD.
Reboot -> nouvelle mise à jour disponible -> film_illimité: vide, Disney HD: erreur ssl.

La mise à jour sur la version 0.6.62 à corriger l'erreur ssl sur film_illimité mais pas sur Disney HD. De plus, film_illimité affiche: aucune information, comme après chaque mise à jour... ou presque.

Je me propose comme beta testeur des mise à jour avant déploiement si cela peut servir.

Bonne nuit.

**Comment by tuego72** [comment]
jay-jay69 film illimité fonctionne très bien chez moi

**Comment by TmpName** [comment]
Alors je sais pas si ca a marche mais je t'ai propose une modif pr requesthandler sur ton github.
La je regarde pr le fichier site.

**Comment by ludopotte** [comment]
Hello TmpName, pourrais-tu m'envoyer ta modif pour requesthandler sur mon github car moi j'ai trouver le nouvel url de ZT s'il te plait ?

**Comment by TmpName** [comment]
Ce sont les liens de @Arias800 donnes plus haut, il a fait des erreurs impardonable lors de ses precedentes reincarnations et du coup sur celle ci, il s'occupe de ZT comme penitence.

**Comment by Arias800** [comment]
C'est bon zt fix : https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2288 :p

**Comment by ludopotte** [comment]
Merci Arias800 pour ton super Boulot. Tu es un Top !

**Comment by lebigboss** [comment]
@Arias800 J'étais connecter sur un vpn Belge et ça fonctionnait mais depuis que je me suis déconnecter ça fonctionne plus
Tu confirme que ça fonctionne en France ?

**Comment by Jojo31780** [comment]
Bonsoir. Ce pb SSl bloque beaucoup de sources. 
Merci pour votre aide.

**Comment by ludopotte** [comment]
Je confirme que ca fonctionne en France lebigboss

**Comment by jeyjey43** [comment]
Merci beaucoup pour le correctif. Tout est rentré dans l'ordre.

**Comment by TmpName** [comment]
Yep, la modif est officielle, donc suffit d'attendre, elle va venir toute seule.
Merci @Arias800, je crois que le jours ou cette source a ete rajoute dans Vstream, ca a change ta maniere de gerer ton temps libre ^^.

**Comment by Jojo31780** [comment]
Bonsoir.
Toujours les mêmes soucis SSL. Impossible de faire des recherches.
Merci.
