### ISSUE TITLE
Soucis caractère %20 transformé en  '+' dans les requêtes URL du plugin

### ISSUE THREAD

**Issue by jon-padawan** [Kodi-vStream/venom-xbmc-addons#2285]
Bonjour,

Je bosse sur une nouvelle source et j'ai rencontré un soucis lié au format des URL du site
J'ai pas mal de caractères spéciaux dans les URL et ils semblent modifié avant d'être envoyé par le plugin

OS: Windows
Kodi: 17
Vstream: 0.6.62

fichier de base utilisé
ajouter_une_source.py

Le site burningwhee1s chez blogspot

dans mes traces wireshark, je constate que les URL envoyé par le plugin sont "modifié" par rapport à ce que j'ai en entré
Que faudrait il modifier pour que le plugin envoie des requêtes HTTP sans modifier les caractères spéciaux du type %20 et %2B en '+'?
ou est-ce un soucis du site qui ne respect pas les normes d'encodage et comment pourrais-je contourner ca?

Il semble que ce soit uniquement le '+' qui soit problématique sur le site
Que se soit le %20 de l'espace transformé en + ou le %2B transformé en +
Et %20 c'est utilisé pour toutes les catégories et %2B pour toutes les "pages suivantes" donc je suis bloqué sur la page d'accueil et ses 7 derniers contenus... lol

[Lien Pastbin](https://pastebin.com/bKDqspu6)

Help

PS1: le code est encore embryonnaire, beaucoup de chose doivent encore être amélioré
PS2: le template est super efficace! merci (j'avais jamais fait de python et j'arrive à voir des vidéos!!!)

**Comment by TmpName** [comment]
Alors le soucis c'est que ton environnement est la pour t'assister, quand tu demandes d'afficher l'url, ca peut t'afficher un "+" , mais apres la lib convertie elle meme l'url sans te le dire (d'ou la difference que tu peux voir avec wireshark)
Par experience quand tu fais un VSlog(url), c'est exactement la meme url (celle qui s'affichera en log) sans aucunes modifications que tu dois rentrer dans le navigateur, si celle si marche, elle marchera en python, pas de modification a y faire.
Je n'ai pas eu le temps de tester ton code, mais si les liens sont directement prit sur la page et non "calcules" (par exemple par du javascript) il sont a prendre tel que, donc aucunes modifs non plus.

J'ai regarde sur le site, je n'ai vu que des "%20" dans les urls.

Si tu as un prb d'url, il s'affiche egalement en log. Et ca va t'afficher l'url ou a essaye de se connecter python, avec l'enbcodage qu'il a utilise.

Apres si vraiement ca pose probleme, il ya des fonction d'encodage quote_plus(), urllib.urlencode(), ect ...

**Comment by TmpName** [comment]
Ok, j'ai vu le prb donnes moi quelques mn.

**Comment by jon-padawan** [comment]
Re, ca me donne un contournement partiel, merci TmpName!

j'ai modifié la ligne 163
            oOutputParameterHandler.addParameter('siteUrl',  sNextPage.replace('%2B','-'))
J'ai remarqué que si j'altère l'URL "page suivante" en remplaçant le %2B par '-' au lieu de '+' le site réagit plutôt bien et je peux naviguer de page en page (ca me duplique le premier et dernier contenu des pages, mais c'est un énorme progrès)

Pour l'autre proposition => en fait le %20 n'est utilisé que dans les URL des categories, pas pour les postes ou on trouve les video, donc j'ai pas d'enjeux de modifier la requête de showMovies pour remplacer d'éventuels %20, il y en a jamais

Par contre je bute sur les categories...
comment ouvrir la page search/label/WRC%202018
SPORT_WRC = (URL_MAIN + 'search/label/WRC%202018/', 'showMovies') #WRC 2018

Je prends vos bonnes idées

En parallèle je vais bosser le script

Comme chaque poste correspond à une épreuve de course, elle comprends plusieurs sous video pour un même événement (practice, race 1, race 2...) je vais m'inspiré de ce qui est fait pour les séries

**Comment by jon-padawan** [comment]
Bon, c'est encore un gros chantier, mais ca ira pour aujourd'hui

Donc a date on peut naviguer dans les derniers ajouts de burningwee1s (passer de page en page)
On peut ouvrir un lien (une épreuve)
Lister toutes les videos disponible pour l'épreuve sur tous les hoster (mais seul MailRu semble fonctionner)
Avoir le nom de l'épreuve dans 80% des cas (race 1, fp1, etc... mais comme le gars normalise pas sa fonca de nommer les épreuves j'ai pas trouvé de filtre magique pour 100% des cas)
Et regarder la video si elle est hosté sur MailRu

Reste à faire
_comprendre pourquoi les hoster VK et Netu marche par
_Trouver un contournement pour créer des catégories à cause de ce satané soucis de %20 transformé en '+' (car toutes les catégory sont au format d'URL XXXXXXX%202018)

Le nouveau code sur [PastBin](https://pastebin.com/jEzSeF9Y)

**Comment by TmpName** [comment]
@jon-padawan  tu fais fausse route, le prb c'est pas le %20 le probleme mais le %2B, l'espace et le %20 ne sont pas genant, essayes sous navigateur, ca passe sans prb.
Et le %20 ne peut pas etre converti en '+' sans actions de ta part

@johngf a repare netu ya 1 jours ou 2

**Comment by jon-padawan** [comment]
@TmpName Pas sur de comprendre ou tu veux en venir, si c'est une remarque d'ordre général ou spécifique à ce site. 
Ce que je comprends c'est que ce site n'aime pas qu'on change les %20 et les %2B et typiquement ce site n'aime pas du tout les '+' ( je n'en ai trouvé aucun nativement sur ce site). Donc je ne met pas de '+' dans mon code python et dans les URL qui sont récupérées par le code il n'y a jamais de '+' pourtant dans mes trace wireshark je retrouve des '+' à la place des espaces, des %20 et des %2B ce qui fait que le site plante.... arghh
Je suis sur que c'est pas wireshark qui décode mal les requêtes, car les requêtes qui viennent du browser et que je fais à la main, les %20 et %2B et espace ne sont pas modifié par wireshark en '+' c'est donc bien le combo vstream/kodi qui réencode les url... du coup je peux faire ce que je veux sur mon scripte c'est ailleurs que c'est modifié pour moi
Tu peux vérifié mon code, si tu trouve ou j'ai mis une commande qui transforme les %20 et %2B en '+' je suis preneur :) (sachant que maintenant j'ai un contournement partiel pour nextpage qui est de transformer le %2B en '-' ca a des effets de bord, mais c'est mieux que rien)
J'ai repris le template et j'ai fait des modif à la marge (notamment les spattern) et je suis un noob en python, donc comme ca je trouve pas...

Je suis du coup toujours à la recheche d'une solution pour que les %20 et %2B ne soit pas changé en '+' par vstream/kodi :'(

[lien pastbin](https://pastebin.com/jEzSeF9Y)

**Comment by Arias800** [comment]
Solution de bourrin mais ça marche sauf pour FORMUL@ il y a des caractère que python aime pas je chercher encore pourquoi https://github.com/Arias800/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/burningwhee1s_beta.py

**Comment by TmpName** [comment]
Essayes avec ca https://pastebin.com/yJ9YMC1L
Par contre tu es bon pour installer la beta de Vstream j'ai modifie au moins 3/4 fichiers du coeur de vstream pour gerer les '+', a mon avis y a pas mal de sources qui vont tirer la gueule, j'ai fais quelques tests ca a l'air de passer.

Now plus de probleme avec les '+' par contre pour le reste y a pas le choix, je t'ai mit une fonction qui re encode les urls
sUrl = QuoteSafe(sUrl)

**Comment by jon-padawan** [comment]
Super, j'ai essayé les 2 et ils marchent pour toutes les categories que j'ai essayé, pas eu besoin d'installer la beta?!
Reste dans les 2 cas la section Formul@ 1 qui ne marche pas, trop de caractères spéciaux :/

Super, merci!

J'ai du coup amélioré un peu le plugin et ajouté des catégories, maintenant que ca marche :+1: 

Mais j'ai vu un truc bizarre en bidouillant: le coupable?
23:40:01.355 T:17228   ERROR:   File "C:\Users\j_elb\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\requestHandler.py", line 93, in request
23:40:01.355 T:17228   ERROR:     **self.__sUrl = self.__sUrl.replace(' ', '+')**

**Comment by jon-padawan** [comment]
Re

Grosse refonte du plugin sur la partie présentation

Formula 1 résolu (en partant d'un autre lien qui passe bien ou alors une ancienne coquille)
Ajouté: toutes les catégories dispo sur le site (avec une nouvelle fonction pour parser toutes les categories)
Avec une préselection de mes préférés

Je l'ai passé plutot en mode (alpha) car il est jeune encore 

Merci @TmpName et @Arias800 

[pastbin](https://pastebin.com/DL0YYc5W)

**Comment by LordVenom** [comment]
@TmpName  tu as tester la recherche global

Y a un truc de casé la https://pastebin.com/5xwHyEfi

**Comment by TmpName** [comment]
@LordVenom c'est bon le prb cause par ma modif sont plus la, par contre gave d'erreur ssl encore ....

**Comment by LordVenom** [comment]
J'ai vue que certain addon importer urllib3 ont aurais pas moins de soucis avec lui ?

**Comment by Arias800** [comment]
Peut être parce qu'il y a une section spécial ssl et il a l'air de mieux gérer ça https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl et en plus en bonus ce sera moins pénible le passage a kodi 19 (puisque les addon devront être compatible python 3 sinon il seront désactiver) car urllib 2 c'est le bazar avec python 3 puisque le module est couper en 3 ^^

**Comment by LordVenom** [comment]
C'est un peux le bordel comment l'addon peux etre en xbmc.python 2.0.1 (Kodi 12) et avoir un import urllib3 mais sans la lib python.

https://github.com/elgatito/script.elementum.burst/tree/master/resources/site-packages/urllib3

Je regardé comme ça mais c'est la merde.

**Comment by Arias800** [comment]
Ah bon bah on va rester sur urllib 2 alors x)

**Comment by TmpName** [comment]
Ils en sont a la beta 3 ? Y en a pour combien de temps encore ? beta 4 beta 5 RC1 RC2 RC3 RC4 ?

**Comment by TmpName** [comment]
Ben la, a part uptobx, y a tout qui tourne, j'ai mit un patch tout crade dans un fichier le temps de trouver pkoi ca ne marche pas comme ca devrait, mais la tout devrait rouler.
C'est quoi la convertion qui deconne sous uptobx ?
