### ISSUE TITLE
NETU HS

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#2286]
@TmpName salut, netu est hs.
voila c'était juste pour informer.
@ +

**Comment by TmpName** [comment]
Lol, ben merci ^^.

**Comment by johngf** [comment]
ils ont changé encore ça passe par une requete a recaptcha j'ai pas encore trouvé le truv pour avoir le contenu a posté >> postdata

**Comment by TmpName** [comment]
J'ai regarde et c'est mal barre
1 > si tu bloque google.com > freeze
2 > gtoken est un token fabrique par google

**Comment by johngf** [comment]
oui mais il y a pas de recaptcha jai test de lancé l'url ht tps://www.google.com/recaptcha/api2/anchor?ar=1&k= vite fait pas eu le tps

**Comment by Arias800** [comment]
Oui mais c'est Recaptcha invisible que Extreme download ^^

**Comment by TmpName** [comment]
co de memoire c'est l'adresse du site en base64, mais je pense qu'on va attendre que sa rebouge de leur cote.

**Comment by Arias800** [comment]
Comment il faut faire pour appeler ce script https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/recaptcha.py car j'aimerai y jeter un œil ^^

**Comment by TmpName** [comment]
C'etait avec la fonction performCaptcha(), mais tu peux oublier, c'etait a l'epoque ou il y avait une faille, actuellement c'est exactement le meme prb que netu il te manque un token qui s'obtient avec "anchor?ar=1&k=" et sans machine javascript pas possible, apres tu peux envoyer le code a un navigateur pr executer le code (comme recaptcha)

**Comment by Arias800** [comment]
Enfaite co c'est le nom de domaine du site par exemple https://www.google.com avec un nombre derrière en base64

**Comment by TmpName** [comment]
Yep, un port
co = base64.b64encode('https://www.google.com:443')

**Comment by pascalmazda** [comment]
Les liens netu sur Kodi fonction plus avais vous une solution pour arrangé le problème ???

**Comment by Arias800** [comment]
Non car netu utilise recaptcha ^^
