### ISSUE TITLE
Message pour Kodi-FR

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2287]
@vic1997 Je me balader (en chantant lalalala) sur le web et je me suis aperçue qu'il manquer des balises sur http://kodi-fr.rf.gd 

Voir :
http://www.infowebmaster.fr/outils/analyse-balises-meta.php?url=http%3A%2F%2Fkodi-fr.rf.gd%2F&choix=balises_principales

Autre chose tu peux ajouter  f4mTester et F4mProxy  dans ton repo ?

**Comment by vic1997** [comment]
@LordVenom Je vais faire ça pour les balises, merci de l'avoir signalé.
Pour f4mTester et F4mProxy je peux le faire, sauf que je n'ai toujours pas réglé le problème qui est que kodi n'arrive pas à accéder au repo.
Je t'avoue que j'ai un peu laissé de côté ce site web qui n'est plus très actif et c'est dommage (il n'y a pas eu énormément de monde non plus).
Donc si votre équipe voudrait reprendre le site web ce serait avec plaisir, je resterais pour vous aider un peu, à mettre en place le repo pour qu'il soit fonctionnel et d'autres trucs du genre.
Comme vous voulez !

**Comment by LordVenom** [comment]
Le soucis c'est qu'il est pas référencé à cause je suppose des balises puisqu'il est noter ici il devrais avoir un page rank asser élever.Perso j'arrive toujours pas à me loguer avec Github et pour le repo il te manque un .htaccess avec l'option 
> Options +Indexes.

**Comment by vic1997** [comment]
@LordVenom Chez moi il est bien référencé : https://i.imgur.com/2CB5Ehm.png
Je vais quand même voir pour régler ça et pour le login Github j'avais cherché mais le bug ne venait pas de moi, je ne me rappel plus pourquoi mais je n'arrivais pas à le régler.

Sinon fais moi un retour sur la proposition.

**Comment by LordVenom** [comment]
Google c'est spécial puisqu'il t'affiche les sites que tu a visiter en premier vérifie sur www.qwant.com plutôt.

Ben pas de soucis je peux t'aider pour les autres membres je sais pas.

**Comment by LordVenom** [comment]
Ben ça dépend des conditions. Si c'est faire un peux de code et le maintenir a flot ça ce discute si c'est prendre en charge l’hébergeur et le nom de domaine c'est mort.

**Comment by vic1997** [comment]
@LordVenom Uniquement le maintenir à jour (un peu de code, rendre la communauté active...). Je resterais dans le projet mais vraiment pour être là en cas de besoin.
L'hébergement et le nom de domaine je m'en occupe.
