### ISSUE TITLE
Lien Direct ?

### ISSUE THREAD

**Issue by isandard** [Kodi-vStream/venom-xbmc-addons#2290]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Une description claire et concise de ce qu'est le problème. Ex. Je suis toujours frustré quand [...]

Bonjour,

En fait quand uptobox ne marche pas en mode fichier comme c'est le cas actuellement où même un autre hébergeur.

**Décrivez la solution que vous souhaitez**
Une description claire et concise de ce à quoi vous voulez arriver.

En fait un systeme simple à implémenter ( je pense car je ne code pas en python ) serait de pouvoir passer un lien direct ( un peu comme ce qui existe pour extreme down ) et laisser le systeme decoder le lien / lancer la lecture.

on pourrait imaginer dans le menu "lecture lien direct" et passer l'adresse du lien, il y aurait une detection de l'hebergeur et lancement du decode ==> lecture.

**Comment by Arias800** [comment]
J'avais fait une source comme ça nommé Hoster Direct ou il suffit de coller le lien et ça permets de le lancer mais je ne l'ai jamais  ajouter a vstream https://pastebin.com/raw/jVTu7ThE

**Comment by AzeRim** [comment]
@Arias800 ,  Je n'arrive pas à faire fonctionner ton fichier site Hoster Direct.py sur windows 8.1 ou 10 familial avec Kodi 17.6 vStream 0.6.62. Pourtant il fonctionne très bien sur Android et Android TV.  As-tu une idée du bug? Quand je sélectionne Recherche lien, le clavier ne s'affiche pas alors que Extreme -Download affiche bien le clavier.

**Comment by isandard** [comment]
E

> En fait tu cherches a donner un lien a kodi qui le lirait directement ?
> Lien final (en *.avi par exemple) ou d'hebergeurs ([www.opnload/fichier/75d5f5d14](http://www.opnload/fichier/75d5f5d14) ) ?

En version hoster directement, comme pour extreme-down.

**Comment by Arias800** [comment]
@AzeRim ça fonctionne chez moi il a du y avoir un probleme quand tu as copier coller le fichier
@isandard Donc c'est bien ce que fait le fichier du dessus
Du coup ça vaut le coup de l'ajouter ?

**Comment by TmpName** [comment]
J'avais une extension kodi (qui ne marche plus atm je pense, urltester ou un truc comme ca)
Tu y donnais une url, tu choisissais avec ou sans urlresolver et ca lancait la video.

Mais perso quand je voulais streamer un lien du navigateur vers ma TV, je decodais le lien avec le navigateur et je lancais une lecture du lien decode avec kodi ou n'importe quel autre lecteur.

Le code de @Arias800 est tres utile, mais je vois pas trop ou le mettre dans l'addon, Vstream est plus un moteur de recherche qu'un lecteur.

**Comment by TmpName** [comment]
Ou l'inverse, vu qu'il n y a pas de recherche, l'empecher d'apparaitre dans les moteurs de Vstream et le laisser dans toutes les sources.

**Comment by isandard** [comment]
ou alors carrément dans le menu principal puisqu'il ne s'agit pas vraiment d'une source

**Comment by BENJI97200** [comment]
@Arias800....bjr , comment fais tu pour lire les fichiers d extreme download (nvidia shield TV)....car je n ai tjrs pas compri....merci de ton aide

**Comment by BENJI97200** [comment]
@Arias800 ....merci bcp

**Comment by BENJI97200** [comment]
@Arias800.....c bon j ai reussi merci
