### ISSUE TITLE
Probleme NETU depuis mise a jour

### ISSUE THREAD

**Issue by Predat0r64** [Kodi-vStream/venom-xbmc-addons#2294]
**Décrivez le bug**
Alors depuis la mise a jour tous les liens NETU ne fonctionnent plus
J'ai même pris le fichier hoster NETU.py mais rien y fait

**Votre system**
 - OS: Windows 10
 - Version Kodi 17
- Version 0.6.63

**Nous devons le reproduire**
Pour cela il nous faut:
- series streamind hd
- fear walking dead saison 2 fr (mais tous les autres aussi ne fonctionne plus)
- NETU

**Comment by johngf** [comment]
ça passe par une requete a recaptcha j'ai pas encore trouvé le truv pour avoir le contenu a posté >> postdata
