### ISSUE TITLE
ZONE TELECHARGEMENT BUG SSL IS BACK

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2295]
Salut à tous,
![kodi](https://user-images.githubusercontent.com/10349444/47158998-25ea6300-d2ed-11e8-9f2f-c59f78a6f8e0.jpg)

Le problème de SSL est revenu pour ZT :(

Merci Beaucoup

**Comment by Arias800** [comment]
Chez moi j'ai pas d'erreur tu a peut être pas les fichier a jour faut que tu verifie

**Comment by Cikai91** [comment]
Bonsoir
Chez moi aussi j’ai le même soucis ssl pourtant j’ai mis à jour le fichier

**Comment by grego057** [comment]
Bonsoir,
Novice, pouvez vous me dire quel fichier mettre  à jours? Et comment?
Merci d'avance.

**Comment by Cikai91** [comment]
Bonsoir, 

Pour forcer la mise à jour, avancez la date système de votre appareil, box androïd ou pc ou autres. Puis relancer Kodi , vstream il devrait vous proposez une mise à jour

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2136

**Comment by BENJI97200** [comment]
Bjr et merci ça foncionne, mais le probleme c qu apres mise a jour kodi ne reconnais plus la manette de la shield TV...une solution svp?

**Comment by laquarico** [comment]
Bonsoir quand je lance l addon vstream il me met un message connection failed SSL certificate...je viens de lire de faire une mise a jour mais mon addon ne me propose pas de mise a jour je suis en version 0. 6.6.
Que dois je faire? Merci d avance

**Comment by yvandicara** [comment]
@laquarico Salut, Moi j'ai fait ce que @Cikai91 a dit. J'ai fermé kodi, changé la date de mon système à la date de demain et relancer kodi et la vstream m'a proposé la mise à jour.

**Comment by johngf** [comment]
oui il y a un soucis ssl
