### ISSUE TITLE
yggtorrent.site

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2296]
Bonjour,

Je me demandais si cela serait faisable pour vous t'intégrer en source un site torrent comme ht tps://yggtorrent.site/ et de pouvoir lire en streaming un fichier torrent.

Je sais que d'autre extensions le font pour d'autres site de torrent, mais dans Vstream cela serait top

Merci à tous et encore une fois super boulot. Vous assurez

**Comment by Arias800** [comment]
Pas de site en torrent sur Vstream car de 1 ce n'est pas du streaming , ensuite il y aurai normalement de modif a faire hors des extension spécialiser doivent très bien faire les boulot et de 3 c'est le meilleur moyens de ce faire choper par Hadopi ^^

**Comment by yvandicara** [comment]
Okay ;) Merci
