### ISSUE TITLE
Meilleures sources

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2297]
Bonjour,

J'aimerais faire appel à la communauté VSTREAMER.

Quelle est pour vous LA meilleure sources films et séries ?

Quand je dis meilleure, plusieurs critères sont à prendre en compte tels que 

La disponibilité de la source,
Des liens fonctionnelles
Qualité vidéo : HD ou pas

Pour moi c'est Zone téléchargement mais trop souvent HS

Merci à tous

**Comment by TmpName** [comment]
VoirFilm, tres rare de tout avoir HS

**Comment by chataigne73** [comment]
Tu n'as pas précisé un critère important : la qualité (HD ou non)
- si pas besoin de HD ou full HD, je suis d'accord avec TmpName: voirfilms
- si tu veux de la HD: ddlfr, cinemegatoil ou filmillimite

**Comment by kenshiro000** [comment]
En plus de ce qui a déjà été mentionné , j'aime bien Kepliz pour les films en 720 et série-streamingHD pour les séries ( les dernières séries sont en 720 et les plus anciennes en 480 mais la qualité d'image est très correct

**Comment by LordVenom** [comment]
Perso je fait une recherche sur un film ou une série puis je regarde les résultats, je met ça en marque-page puis je tris, je vérifie la qualiter et la disponibilité des liens et je suis tranquille pour la semaine.

**Comment by gwendallebourvellec** [comment]
Solarmovie.cab mais que en anglais mais il y a les sous-titres :)
