### ISSUE TITLE
aucun resultat trouver

### ISSUE THREAD

**Issue by nickspaow** [Kodi-vStream/venom-xbmc-addons#2300]
**Décrivez le bug**
quand je clic sur cherche film par typer un barre de progression apparait mais rester bloque a 2/20 et disparait

**Votre system**
 - OS: Windows 10
-  Appareil pc portable
 - Version Kodi  v17.16
- Version Vstream 0.6.63

**Nous devons le reproduire**
Pour cela il nous faut:
- plusieu source ( a la recherche pas type horreure)
- me fais en cherchant sur TMDB zone streaming, cinemay et plusieur autre

**Log**
**Edit : suppression du log vous utilisez votre nom comme compte donc on le voie.**

L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by LordVenom** [comment]
Bonjour, 

il doit y a voir un bug avec un site désactiver le dans les préférence de l'addon votre log ne contient pas d'erreur il vous faut d'avoir faire buguer vStream puis envoyer le log.

Note : N'envoyer pas votre log si vous utiliser votre nom réel comme nom de compte.
