### ISSUE TITLE
probleme netu

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#2301]
bonjour à tous,

@tmpname, c'est le même pb que le weekend dernier: tous les liens netu ne fonctionnent plus.
j'ai été absent pendant longtemps (job etranger) et je me suis remis sur ce fabuleux addon.
donc je post si il y a des pb.
par exemple dans films/derniers ajouts il y a cineiz, filmvfgratuit, filmcomplet, filmsvostfr etc.. qui fonctionne pas.
ya personne qui fait remonter l'infos ? ou si les liens sont dead pourquoi pas les virer de la liste ?

bonne continuation à l'équipe

**Comment by johngf** [comment]
c'est si difficile que ça regarder les issues sur la page d'accueil ?

**Comment by Arias800** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2298

**Comment by TmpName** [comment]
Par contre sa proposition est pas con, on desactive netu, ou on attend encore un peu pour voir si ca rebouge ?
