### ISSUE TITLE
Probleme de plus dans le nom

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2302]
**Décrivez le bug**
Lors de la mise en favoris, les espace sont remplaces par des plus

**Plus d'infos **
Bon c'est ma faute, c'est depuis mes dernieres modifs, mais je trouve pas comment corriger proprement. Il suffirait de faire un replace() et c'est regle mais j'arrive pas a comprendre d'ou vient le probleme.

Lorsqu'on est sur le site, aucun probleme, les titres sont bons.

Si dans le fonction createContexMenuFav() je met un 
`VSlog('********3 ' + str(oOutputParameterHandler.getValue('sMovieTitle')))`
Le nom est bon aussi.

Mais si je met dans la fonction setFavorite() un
VSlog('********8 ' + str(oInputParameterHandler.getValue('sMovieTitle')))
Le nom deconne, espace remplace par '+'

D'ou vient la magie ? Ce n'est pas les fonctions cInputParameterHandler et cOutputParameterHandler sinon ca deconnerait aussi lors de la navigation sur le site.

**Comment by LordVenom** [comment]
hum dans la fonction createContexMenuFav le movietitre n'est pas pris

```
 oOutputParameterHandler.addParameter('sId', oGuiElement.getSiteName())
oOutputParameterHandler.addParameter('sFav', oGuiElement.getFunction())
oOutputParameterHandler.addParameter('sCat', oGuiElement.getCat())
```

Faudrais tester dans la fonction setFavorite si il prend

xbmc.getInfoLabel('ListItem.title')
ou 
oInputParameterHandler.getValue('sMovieTitle')

**Comment by LordVenom** [comment]
La recherche similaire et morte aussi pour "controle parentale 2018 j"ai "controleparentale+2018"

**Comment by TmpName** [comment]
J'ai vu ca, mais ca peut pas marcher, imagine une url avec a la fois des + et des espaces.
Je vais mettre un patch en place pt tester.
