### ISSUE TITLE
Uptobox direct menu uptostream?

### ISSUE THREAD

**Issue by Oeil2L** [Kodi-vStream/venom-xbmc-addons#2304]
Bien le bonjour,

je suis inscrit mais pas premium sur uptobox, l'authentification se passe bien dans Vstream mais lorsque je lance une source en mode direct j'obtiens le même menu de choix de résolution (voir de langue si fichier multi), résultat le fichier est lu uniquement en stéréo au lieu de profiter de l'AC3 du fichier source.

Est-ce que quelqu’un pourrait confirmer le problème?

**Comment by LordVenom** [comment]
Bien le bonjour,

j'ai envie de dire heu... pour qu'on puisse tester il nous faut des exemples quel film? quel source?
Apres quand tu lance le film appuis sur la touche O pour avoir les infos du flux retourné.

**Comment by johngf** [comment]
il ya un souci avec l'auth premiuim

**Comment by AzeRim** [comment]
fichier premium handler mise à jour mais sur Indian Horse de ZT en hdlight 720p , on a toujours le menu uptostream avec compte inscrit sans premium même après le temps d'attente. Il n'y a pas mieux qu'un compte premium car sinon il y a trop de restriction (temps d'attente, débit limité, durée de visionnage limité sur uptostream...).

**Comment by johngf** [comment]
la maj de premium handler était juste pour evité au premium de s'authentifier a chaque clic @AzeRim 
pour l'instant je suis sur le site upto box pas le resolver

**Comment by Oeil2L** [comment]
merci pour les retours ma question était plutôt d'ordre général qu'un lien ou un site source en particulier.

A l'époque de ZT 1er du nom et de l'arrivée du HDLight, il était possible de voir depuis Uptobox en mode direct les fichiers inférieurs à 2Go, bien sur si le DL s'interrompait (par manque de cache) fallait patienter 1 heure mais cela permettait de visionner comme en streaming les fichiers en AC3, alors que Uptostream n'offre que du 2.0.

Je m'y suis remis que récemment, j'ai donc créé un compte sur uptobox, mais je n'ai pas vu de changement notable dans les règles uptobox mais comme la lecture direct affiche le même menu que lorsque l'on passe par uptostream, soit c'est une nouvelle limite de uptobox ou un bug de Vstream.

Cette possibilité de lecture direct n'est-elle plus possible?

**Comment by TmpName** [comment]
Ha oui, c'etait l'option "DL+Visualiser" ?

**Comment by johngf** [comment]
non maintenant pour les non premium ça passe par upto stream meme quand on clique sur direct

**Comment by Oeil2L** [comment]
merci pour le retour johngf.

ya plus qu'à fermer, désolé pour le dérangement.
