### ISSUE TITLE
Problème série streaming hd

### ISSUE THREAD

**Issue by lefou66** [Kodi-vStream/venom-xbmc-addons#2305]
Bonjour, fichier introuvable sur série streaminghd, netu et openload.
os:Android 
tx95
kodi 17.6
vstream à jour
sinon quelle source vous prenez pour les séries en hd?

**Comment by sviet2k** [comment]
C'est tres etrange. Openload ne marche pas sur streaminghd mais fonctionne bien sur skstream.???

**Comment by Che-debarras** [comment]
Il y a dpstreaming je crois la source c'est seriestreaming.cx.se termine par .CX

Il y a beaucoup de lien mais le lien VIDOZA à une excellente haute définition 

J'utilisais beaucoup serie-streaminghd mais vu les souci de Netu Jai du chercher une autre source et pour l l'instant ya la source qui fini en .cx

C'est une source moins rapide qie serie-streaminghd pour publier les series mais la qualité y est
Par contre seul un seul lien vidoza fonctionne et pas les autres a toi de trouver lequel lol

Possible que tu as du HD avec les autres lien.

**Comment by LordVenom** [comment]
C'est réparer pour openload mais netu je pense que c'est mort pour le moment.

**Comment by lefou66** [comment]
merci bien!

**Comment by lefou66** [comment]
ça fonctionne toujours pas ...

**Comment by lefou66** [comment]
comment est ce que ça peut marcher chez quelqu'un d'autre mais pas chez moi??

**Comment by lefou66** [comment]
ont dirait bien que film illimité est hs aussi😭

**Comment by LordVenom** [comment]
Pas disponible en mise a jour auto pour le moment voila tout.

**Comment by lefou66** [comment]
ok désolé j'suis un peu noob la dessus...j'vais ou pour le mettre à jour?

**Comment by LordVenom** [comment]
Tu doit juste t’équiper de patience a la prochaine mise ajour ça seras corriger fin du mois normalement.

**Comment by freemanB9** [comment]
Depuis plus de 2 semaines sur série stream HD . Je vois bien les liens mise a jour mais impossible de visionner . Erreur fichier introuvable.
J ai bien fait toute les mise a jours j ai mm réinstaller Kodi de zéro mais toujours le mm problème.

**Comment by lefou66** [comment]
je prends le plug in ici sur la page principale ?

**Comment by lefou66** [comment]
Beaucoup de bug chez nous je comprends pas ....film illimité aussi marche pas

**Comment by TmpName** [comment]
Il y a une mise a jour auto proposee tout les 3 jours, suffit d'attendre.

**Comment by freemanB9** [comment]
Version bêta des plugins.

https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by freemanB9** [comment]
Il y a mieux que film illimité.
DDL.ISLAND.SU
Avec un compte uptobox va mal nickel et en HD
Après ta série.streamingHD mais il y a que le lien openload qui fonctionne.

**Comment by lefou66** [comment]
ces t pour ça que j'aime la source série streaminghd...dans vstream sous l'onglet tvshow/news/ série streaminghd...les nouvelles épisodes sont la et arrivé plus vite que les autres

**Comment by freemanB9** [comment]
Ba chez moi tout fonctionne correctement sauf le lien Netu.
Même sur film illimité sa fonctionne je viens de tester.
