### ISSUE TITLE
VSLog ou xbmc.log fait planter la compilation d'un site.py

### ISSUE THREAD

**Issue by chaudCacaco** [Kodi-vStream/venom-xbmc-addons#2308]
Bonjour,

**Décrivez le bug**
Ma fille est fan de pokemon et je peine à trouver un site sur lequel elle puisse regarder tous les épisodes. J'ai trouvé un site pas trop mal pour lequel je voulais créer un site.py comme dans l'exemple https://github.com/Kodi-vStream/venom-xbmc-addons/blob/master/ajouter_une_source.py mais je reste bloquer lors de la reherche des videos et les pattern.
Pour aller plus loin dans l'analyse j'ai donc voulu mettre quelques logs mais le fichier python ne compile pas dès lors que j'ajoute un VSLog('...') ou un xbmc.log('...')

Le bout de code (non fini) : [pikachu.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/2521927/pikachu.txt).

Merci par avance pour votre aide

**Votre system**
- OS: Windows 7
-  Appareil : PC
- Version Kodi : 17.6
- Version Vstream : 0.6.63

**Comment by chaudCacaco** [comment]
Merci @Arias800 pour ton retour très rapide :)

>Alors pour afficher les information d'un VSlog dans les log il y a une option a activer dans les paramètre de Vstream nommer "Activer les notices de log"

C'est bien fait et justement je ne comprend pas pourquoi dans un site.py déjà existant il m'est impossible d'ajoute un VSlog. Le fichier ne s'importe pas correctement
`[PLUGIN] Vstream: Cant import plugin otakufr_com`

>Ensuite le fichier que tu nous donne est en .txt alors que normalement il devrai être en .py

- J'avais bien un .py mais pour l'upload sur github le .py ne convenait pas donc j'ai changé en .txt

>  Je te conseil de pas afficher directement les saison mais de d'abords laisser le choix entre le contenu a voir (un film , un téléfilm , un spin off ...) car pokemon mine de rien c'est avant tout un large choix et pas que les épisode et ce serai (de mon points de vue ) dommage de ce contenter des épisode uniquement
- C'est exactement ce que je souhaitais faire mais comme je ne connaissais pas le fonctionnement et le langage python j'ai juste voulu faire un truc simple en choisissant une saison

Encore merci je vais regarder tout ça cette nuit ou demain

**Comment by chaudCacaco** [comment]
Je développe en Java. La syntaxe est assez similaire mais le coup de la tabulation VS les espaces je n'y avais pas pensé une seconde.
J'ai rapidement vérifié sur un bout de code que j'avais mis de côté et qui ne marchait pas et en remplaçant les tabulations par des espaces ça compile :)

Merci pour votre aide. Je vous posterais le résultat dès que ce sera terminé

**Comment by chaudCacaco** [comment]
Bonjour à tous,

Voilà le résultat (en renommant en .py bien sûr) : [pikachu_streaming.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/2525678/pikachu_streaming.txt)

J'avoue que je n'ai pas forcément pris le meilleur site car l'organisation est mal faite. Je me suis donc arrêté aux Films et Saisons.

Avant de clôturer l'issue, j'aurais deux questions 

1. Comment faite vous pour gérer les saut de lignes (\r\n) et tabulations (\t) correctement en regexp ? La seule solution que j'ai trouvé c'est de faire une suppression de tous les saut de ligne et tabulation dans ma variable de sortie `sHtmlContent`
```
sHtmlContent = oRequestHandler.request().replace('\n', ' ').replace('\r', '').replace('\n\r', '').replace('\t', '')`
```

2. Lorsqu’un `hoster` a été vu entièrement ou partiellement on le voit dans kodi grâce à une icone. Par contre lorsqu'on remonte d'un niveau dans l'arborescence ce n'est pas le cas et on doit le faire manuellement. Ne serait t-il pas possible de remonter l'information au parent afin d'afficher que l'épisode a déjà été vu sur un hoster?

**Comment by TmpName** [comment]
1 - Alors ta solution degeulasse est ce qui se fait par defaut ^^, quand tu utilises la lib de vstream tout ces caracteres sont vires (pour simplifier le boulot), si tu passe par les commandes regex brutes, tu utilises les regex \s

2- Nope pas possible, la structure des dossiers est speciale quand c'est du stream, tu peux le faire en forcant l'affichage de l'icone quand tu es sur le parent (marquer vu) mais je te le deconseille pour preserver tes bases de données, surtout que ce ne sera pas fiable (lien web dynamique, pas constant).

Sinon pour virer les caracteres bizarre, aucas ou tu les ai aussi sur ta version (apres avoir importe la lib)
```
            sFilmTitle = sFilmTitle.encode('utf-8')
            sFilmTitle = cUtil().unescape(sFilmTitle)
            sFilmTitle = sFilmTitle.encode('utf-8')
```

Apres perso les pokemons, j'ai arrette apres les 150 premiers ^^, mais si tu veux rajouter ton site officiellement sur Vstream rajoute ton pseudo est fais un PR.

**Comment by chaudCacaco** [comment]
OK merci. Je ferais une contribution sur un site mieux que celui là car là ça craint :)

Je clos le ticket.

**Comment by TmpName** [comment]
Lol, quoi y a des gens qui aiment pas les pokemons ?
