### ISSUE TITLE
UnicodeEncodeError dans mes fichiers uptobox

### ISSUE THREAD

**Issue by moviefangithub** [Kodi-vStream/venom-xbmc-addons#2309]
**Décrivez le bug**
la liste des fichiers uptobox commence à se charger puis l'écrant de chargement disparait et retourne a l'état d'avant, ou c'est marqué mes fichiers

**Votre system**
 - OS: osmc
-  Appareil box tv
 - Version Kodi  la dernière
- Version Vstream 0.6.6 je crois et mis à jour aujourd'hui avec le lien vert

**Nous devons le reproduire**
en ayant un compte uptobox, aller dans sources, compte uptobox, mes fichiers
ca marque authentification réussie ca commence a charger et ca bug

**Log**
```
ERROR: Traceback (most recent call last):
ERROR:   File "/home/osmc/.kodi/addons/plugin.video.vstream/default.py", line 139, in parseUrl
ERROR:     function()
ERROR:   File "/home/osmc/.kodi/addons/plugin.video.vstream/resources/sites/siteuptobox.py", line 146, in showFile
ERROR:     cHosterGui().showHoster(oGui, oHoster, sHosterUrl, '')
ERROR:   File "/home/osmc/.kodi/addons/plugin.video.vstream/resources/lib/gui/hoster.py", line 54, in showHoster
ERROR:     oOutputParameterHandler.addParameter('sFileName', oHoster.getFileName())
ERROR:   File "/home/osmc/.kodi/addons/plugin.video.vstream/resources/lib/handler/outputParameterHandler.py", line 11, in addParameter
ERROR:     self.__aParams[sParameterName] = urllib.unquote_plus(str(mParameterValue))
ERROR: UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 14: ordinal not in range(128)
```
merci!

**Comment by johngf** [comment]
tu n'est pas a jour il faut attendre la Version 0.6.64 ou remplacer les fichiers soit meme 
[celui la](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/siteuptobox.py)
et [celui la](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/handler/premiumHandler.py)

**Comment by moviefangithub** [comment]
ça marche merci!!!!!
