### ISSUE TITLE
Suivre ces series

### ISSUE THREAD

**Issue by freemanB9** [Kodi-vStream/venom-xbmc-addons#2310]
J aurai une question sur les addons je regarde beaucoup de série mais je ces jamais quand c mis a jours .
Il y aurai pas un Addon qui me préviens dès la sortie d'un nouvel épisode.
Merci

**Comment by freemanB9** [comment]
Ba déjà si sa existe après en français sinon en anglais c pas trop grave tant que sa fonctionne.

**Comment by TmpName** [comment]
Francais y a pas ^^.

Alors d'integre a Vstream tu as track, mais ca fait un moment que j'ai pas teste, a l'epoque ca te proposait des series en fonction de tes gouts, et te prevenait des sorties.

En addon Next Aired
