### ISSUE TITLE
Nouvelle sources a ajouter

### ISSUE THREAD

**Issue by chamkill** [Kodi-vStream/venom-xbmc-addons#2311]
Salut je viens de tomber sur ce site ! Excellent, sans pub, fonctionnel et avec un lecteur nickel ;)
Ajout possible dans les sources ?
ht p://ibogiv.com/sq45hgj4mlu4i1v54bfd5487sd

**Comment by TmpName** [comment]
Quel film vous trouvez sur votre site et pas sur Vstream, dans la meme qualitee ?


Pr info, site deja sur Vstream depuis plus d'un an.
