### ISSUE TITLE
Téléchargement Fichier UPTOBOX

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2312]
Bonjour,

Possédant un compte premium uptobox, j'aimerai pouvoir télécharger via vstream, mais quand je lance un téléchargement il me prend à chaque fois un fichier flv. 

Pourquoi ce n'est pas le fichier d'origine?

Merci beaucoup

**Comment by BENJI97200** [comment]
@yvandicara....bjr le telechargement via vstream prend trop de temps malgré le compte uptobox, mieux vaut telecharger avec son navigateur

**Comment by TmpName** [comment]
Exact ^^. Je pense meme plus a cette reponse.

**Comment by karim7878** [comment]
Bonjour,
Question je vois souvent des sujets concernant les compte premium etc..
Pour ma part je n'ai jamais eu de compte premium sur n'importe quelle hébergeur uptobox ou autres et j'ai toujours réussi à regarder ce que je voulais.
Pouvez vous me dire en quoi cela est utile svp?

**Comment by BENJI97200** [comment]
@karim7878 ....avant sans compte premium je galerais pour trouver un lien de bonne qualité et qui ne soit pas mort, avec le compte uptobox j ai la qualité( son dts etc....)et la garantie que les liens ne soit pas HS, surtout il existe de bon site ayant des liens uptobox(zt, ddl, free telechargement)

**Comment by yvandicara** [comment]
@BENJI97200 tu n'as jamais de lag sur des 1080 avec uptobox? Moi des fois je comprends pas j'en ai par moment.
Pourtant j'ai une connexion fibre

**Comment by BENJI97200** [comment]
@yvandicara ...seulement sur les 4 k .....en 1080 p ça passe tres bien apres avoir installé l extension TT buffer fix...

**Comment by yvandicara** [comment]
@BENJI97200 Super astuce merci. Derniere question, vous savez si un compte uptobox premium peut se partager ?

**Comment by Arias800** [comment]
Je viens de regarder et l'extension TT buffer fix sert juste a créer un fichier Advancedsettings.xml je pense que c'est mieux de le faire soi même plutôt que via une extension : https://kodi.wiki/view/Advancedsettings.xml

**Comment by BENJI97200** [comment]
@yvandicara ....oui tu peux le partager...jusqu a combien je ne sais pas, mais actuellement ns sommes 4 sur le mm compte et aucun soucis.
@Arias800 ....j ai essayé de creer advanced setting xml, mais ça ne fonctionnait pas , vraiment pas le mm resultat...

**Comment by yvandicara** [comment]
@Arias800 oui j'ai vu ça quand j'ai fais la config. En tt cas ca marche vachement mieux. Pourrais t on envisager d'ajouter la possibilité de modifier les paramètres de l'advanced setting directement dans les paramètres vstream?

**Comment by Arias800** [comment]
Pourquoi pas a voir ^^

**Comment by Cathy131313** [comment]
Bonjour et merci pour ce forum.

J'ai installé Kodi sur ma mi box 3. J'ai pris un compte premium uptobox car j'habite à la campagne et ma connexion Internet est pourri. Donc le but est de télécharger avant le visionnage en streaming, sinon le film s'arrête plusieurs fois en cours de lecture.

Question 1 : est ce que je peux directement faire ma recherche de film à télécharger sur la mi box 3. Avec Kodi ou bien sur un autre site ?

Question 2 : Comment faire pour télécharger le film sur mon disque dur. Remarque j'ai suivi un tuto et Kodi reconnait mon disque dur et les films qu'il y a dedant.

Merci beaucoup pour vos réponses. Ou peut-être dois je faire un autre post ?

**Comment by sizanic** [comment]
Bonjour @Cathy131313 

Tu dois en effet créer un autre post.

**Comment by Cathy131313** [comment]
D'accord, je fais le faire.
Merci pour la réponse.
