### ISSUE TITLE
Grand ménage

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2313]
J'ai tester un peux les sites résultat 15 désactiver voir le lien pour la liste.

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/af79c045100aa639566f9ccd8873d3d6e5d94483

J'ai pas pris le temps de voir si il sont corrigeable je veut envoyer la mise à jour mensuel avant.

**Comment by TmpName** [comment]
Lol, put1, y en avait autant.

**Comment by helpmoi** [comment]
Bonsoir,
Êtes vous actuellement sur une maj pour régler les liens comme netu, openload, ... ? Car plusieurs lien ne fonctionne plus. Depuis 2 semaines, il m'est impossible de regarder une série tranquille à cause d'énormément de lien qui ne s'ouvre pas. Merci.

**Comment by TmpName** [comment]
Openload pas de soucis, regarde sur navigateur si le prb ne vient  pas du site.
Netu on oublit pour quelques mois.

**Comment by Arias800** [comment]
Mieux fait comme si netu ne reviendra pas comme ça pas de déçu si la situation ne change pas ^^

**Comment by helpmoi** [comment]
Normalement j'ai pas de soucis sur mon navigateur. Je ferai un post avec mon log... Dommage Netu était pratique.
