### ISSUE TITLE
IMDB regex pattern est incorrect.

### ISSUE THREAD

**Issue by bernzJ** [Kodi-vStream/venom-xbmc-addons#2314]
**Décrivez le bug**

Le regex pour get next page semble ne plus etre fonctionel.

old pattern: `<a\shref="([^"]+?)"class="lister-page-next`
new pattern: `<a[^>]*href="([^"]+?)"[^>]*class="lister-page-next`

Raison: semble que la page returne parfois un charactere de plus entre le `a` tag et le href.
Regex101: [https://regex101.com/r/FPlU3i/1](https://regex101.com/r/FPlU3i/1)

**Votre system**
- potato

**Le reproduire**
Suivez ici le replt.it: [https://repl.it/repls/DeafeningAthleticParameters](https://repl.it/repls/DeafeningAthleticParameters)

lien vers le site et le pattern: [https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/topimdb.py#L200](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/topimdb.py#L200)

Ou tenter de loader une page sur recherche visuel (IMDB).

**Comment by LordVenom** [comment]
Bonjour, réparer à la prochaine mise a jour merci.
