### ISSUE TITLE
Filtrage par qualité et hébergeur

### ISSUE THREAD

**Issue by ludonice54** [Kodi-vStream/venom-xbmc-addons#2317]
Bonjour , 

Petite idée qui pourrait permettre d'améliorer encore un peu l'interface . Un filtrage par qualité et par hébergeur .

Exemple : Je choisis de ne faire apparaître que les HDRIP et uniquement en Uptobox, dans ce cas si je me rend dans ma sources (ZT par exemple) je ne verrai que les films correspondants à ces critères .

Cela permettrai de rendre fonctionnel le plugin OSMOSIS et du coup l'ajout d'une source complète dans sa librairie perso .

**Comment by Arias800** [comment]
@vic1997 a fait une tutoriel pour faire fonctionner OSMOSIS avec Vstream http://kodi-fr.rf.gd/showthread.php?tid=27
Après pour le filtre pour la qualité ça ne sert pas a grand chose puisque beaucoup de site affiche pas la qualité ou alors mentent sur la qualité réel (c'est le cas pour beaucoup de film 4k par exemple)
Après un filtre pour hébergeur pourquoi pas mais bon je trouve pas ça hyper utile car si un lien est mort faut modifier les paramètre pour essayer sur d'autre hébergeur donc pas très pratique ^^

**Comment by ludonice54** [comment]
Oui j'étais déjà tombé sur le tutoriel de @vic1997 mais son but était de streamer via Vstream les films stockés sur son compte Uptobox perso et de les intégrer à sa bibliothèque en utilisant OSMOSIS.

Ici l'idée serait d'intégrer les films d'une source comme ZT a sa bibliothèque et OSMOSIS n'aime pas trop les sous répertoires (qualité/hébergeurs) .
