### ISSUE TITLE
Informations Film Zone téléchargement

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2318]
Bonjour,

C'est encore moi :). Désolé de vous déranger encore une fois.

Pourrais t on, pour la sources Zone téléchargement, rajouter les infos du films : synopsis, acteur etc?

Merci

**Comment by TmpName** [comment]
Salut, essayes le menu contextuel > "information"

**Comment by yvandicara** [comment]
@TmpName Exacte ca marche mais bon je vais être relou :) ca serait cool que ca s'affiche directement. sur la gauche sur la photo ci-jointe
![kodi_2](https://user-images.githubusercontent.com/10349444/47804685-b5543500-dd35-11e8-988c-e073f389c879.jpg)

**Comment by LordVenom** [comment]
Bonjour, Active les métadonnées dans les paramètre de vStream.

**Comment by BENJI97200** [comment]
@LordVenom ....bjr, est ce possible d avoir les informations (jaquette.....) des films dans compte uptobox sur vstream?

**Comment by LordVenom** [comment]
Non c'est pas possible.

**Comment by BENJI97200** [comment]
Merci
