### ISSUE TITLE
Lien zone téléchargement hs

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2319]
Bonsoir,

Ya plus aucun lien qui se lance sur zt. 

Ca vient de vstream ou zt ? 

Vous savez ce qu'il se passe ? 

Merci beaucoup :)

**Comment by yvandicara** [comment]
Je suis pas sur mais est ce que le lien aurait changé ? Ça m'a l'air d'être un nouveau lien https://www.zone-telechargement.lol

**Comment by zakaria220** [comment]
Selon les logs c'est un problème cloudflare

	23:06:44.715 T:3888  NOTICE: ******  Decodage *****
	23:06:44.725 T:3888   ERROR: Traceback (most recent call last):
	23:06:44.725 T:3888   ERROR:   File "C:\Users\master\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 139, in parseUrl
	23:06:44.727 T:3888   ERROR:     function()
	23:06:44.727 T:3888   ERROR:   File "C:\Users\master\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\zone_telechargement_ws.py", line 695, in Display_protected_link
	23:06:44.729 T:3888   ERROR:     sHtmlContent = DecryptDlProtecte(sUrl)
	23:06:44.729 T:3888   ERROR:   File "C:\Users\master\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\zone_telechargement_ws.py", line 860, in DecryptDlProtecte
	23:06:44.730 T:3888   ERROR:     reponse = oRequestHandler.request()
	23:06:44.730 T:3888   ERROR:   File "C:\Users\master\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\requestHandler.py", line 95, in request
	23:06:44.735 T:3888   ERROR:     return self.__callRequest()
	23:06:44.735 T:3888   ERROR:   File "C:\Users\master\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\requestHandler.py", line 166, in __callRequest
	23:06:44.737 T:3888   ERROR:     sContent = CF.GetHtml(self.__sUrl,e.read(),cookies,sParameters,oRequest.headers)
	23:06:44.737 T:3888   ERROR:   File "C:\Users\master\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\cloudflare.py", line 279, in GetHtml
	23:06:44.741 T:3888   ERROR:     hash = re.findall('<input type="hidden" name="jschl_vc" value="(.+?)"\/>',htmlcontent)[0]
	23:06:44.741 T:3888   ERROR: IndexError: list index out of range

**Comment by TmpName** [comment]
Le site en *.lol n'est pas le meme.
Moi je n'ai deja plus d'erreur cloudflare, mais des prbs de regex, donc pas sur que je sois sur le bon site.

**Comment by AzeRim** [comment]
J'ai l'impression que dl-protect à ajouter une protection cloudflare qui fait bugger l'affichage du lien.
12:16:45.476 T:54712588   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=Display_protected_link&sCat=1&sMovieTitle=%20Skyscraper&sThumb=https%3a%2f%2fwww.zone-image.com%2fuploads%2fkv3Jb.jpg&site=zone_telechargement_ws&siteUrl=http%3a%2f%2fwww.dl-protect1.com%2f4355555154062067067565155503750590633850480676052464343590k4953505850 &title=%20Skyscraper%20%5bCOLOR%20coral%5dUptobox%5b%2fCOLOR%5d%20

**Comment by Arias800** [comment]
@TmpName comment il faut faire pour passer en paramètre le résultat de l'encode multipart avec oRequestHandler ?

**Comment by rod93** [comment]
Bonjour pareil plus aucun liens zt ne fonctionnent

**Comment by ludopotte** [comment]
Le Site ZT ne marche plus ca marque "Connexion Impossible" et les Liens ZT ne fonctionnent toujours pas.
Âpres le site marche sur Internet au https://ww9.zone-telechargement1.org/ et aussi le DL-Protect marche mal au https://www.dl-protect1.com

**Comment by Arias800** [comment]
Je trouve pas pourquoi çà merde du coter de cloudflare donc si quelqu'un a une idée : https://github.com/Arias800/Fichier-divers/blob/master/zone-telechargement_ws.py

**Comment by Kiri85** [comment]
Effectivement pour ma part les liens Uptobox ne se lance plus à partir de ZT.

**Comment by yvandicara** [comment]
J'aimerais bien vs aider mais jsuis nul en dev :) mais j'ai confiance en vous

**Comment by yvandicara** [comment]
@Arias800 Euh ca remarche chez moi.... Test sur derniers ajout indestructible 2 uptobox avec compte premium

**Comment by zakaria220** [comment]
Ça remarche chez moi aussi, depuis 3h..

**Comment by ludopotte** [comment]
Pour que ZT remarche, il suffit de télécharger la Beta de vStream au https://github.com/Kodi-vStream/venom-xbmc-addons/archive/Beta.zip et de remplacer le fichier "zone-telechargement_ws.py" par le mien au https://github.com/ludopotte/vStream/blob/master/zone-telechargement_ws.py

**Comment by zakaria220** [comment]
Le problème ne vient pas du lien zt. 
Et le fait de remplacer www par ww10 va rapidement cassé le site car Zt change de lien régulièrement, passant de ww1 à ww10 en quelques mois. En plus, la fonction GetURL_MAIN récupère le lien du site à jour (ici ww10)

**Comment by Arias800** [comment]
Bon bah bonne nouvelle alors  ^^

**Comment by AzeRim** [comment]
La protection cloudfare n'est plus présente sur le site dl-protect pour le moment. On risque encore de revoir le problème prochainement.

**Comment by Arias800** [comment]
Non mais je pense qu'il l'avais mal implémenter car le site était instable donc ca doit etre pour ca qu'il l'ont retirer ^^

**Comment by yvandicara** [comment]
et c'est RE down :(

**Comment by ludopotte** [comment]
Je viens de voir que ZT à était retirer de la Liste des Sources dans vStream car c'est vrai que le site est instable.

**Comment by yvandicara** [comment]
@ludopotte pas accessible parce que le. Site https://ww9.zone-telechargement1.org est down. Ils doivent encore changer de serveur

**Comment by ludopotte** [comment]
@yvandicara Le Site à changer d'adresse : https://ww10.zone-telechargement1.org/ et il marche de temps en temps

**Comment by yvandicara** [comment]
@ludopotte ah ! au temps pour moi.

**Comment by AzeRim** [comment]
ZT sur ww10 a ré-implémenté la protection au niveau du dl-protect -> plus de lien :(

**Comment by ludopotte** [comment]
Oui @AzeRim tout a fait, c'est un problème de codage du Fichier Zone-Telechargment dans vStream

**Comment by Arias800** [comment]
De toute façon je bloque toujours au même endroit ^^

**Comment by TmpName** [comment]
Y a une adresse stable (et officielle) qui fonctionne et avec cloudflare active ?

**Comment by yvandicara** [comment]
Et quelle est le problème d'ajouter en source les zt non officiel ?

**Comment by TmpName** [comment]
Ben que c'est pas le meme site, donc faut refaire un nouveau fichier, et a mon avis @Arias800 a deja assez de boulot avec l'officiel.

**Comment by yvandicara** [comment]
@TmpName t'assure. Merci beaucoup pour votre travail. :)

**Comment by TmpName** [comment]
Ben dsl, mais pr le moment pas trouve.
@Arias800 > https://pastebin.com/PtScfTPY

Il y a de temps en temps un bug sur cloudflare, mais c'est pas ca le prb.

Pour tester, quand tu as reussi a avoir les liens affiches sur navigateur, ca reste en place pendant un bon moment, donc tu peux copier/coller les cookies du navigateur vers Vstream ( faire gaffe a l'UA). Histoire d'essayer d'avoir les memes requetes.

Avec le dernier code, pour moi les requetes sont absolument identique, soit y a un truc que j'ai pas vu, soit c'est le meme prb qu'avec le site ou on a du utiliser la lib request car impossible avec urllib (si c'est ca on est mal barre)

**Comment by Arias800** [comment]
Pour les cookie Cloudflare il me semble que ca bloque car il faut inverser l'ordre des cookie pour que __cfduid soit en 1er et cf_clearance soit en deuxieme mais je trouve pas comment faire ^^^

**Comment by TmpName** [comment]
Y a un ordre aux cookies ?
Ca je peux te faire un code pr ca, mais pour avoir teste sur navigateur, suis pas sur que ca change quelque chose.
Mais cloudflare fonctionne sans probleme, tu recuperes la page, mais il te faut "represser le boutton" pour redemander le lien, que tu n'as jamais.
Je peux te passer mes logs mais j'ai vraiment plus de prb avec CF, et j'ai modifie les cookies au moins 3/4 fois.

**Comment by Arias800** [comment]
Peut être qu'il y a un ordre pour les cookie oui parce qu'à un moment je n'arrivais pas arrivait pas a avoir le liens donc j'ai changer l'ordre et c'est passer après c'est peut être qu'une simple coïncidence ^^

**Comment by ludopotte** [comment]
Salut @TmpName et @Arias800, ZT se lance plus vite mais les liens ne marche toujours pas. Comment on peux faire pour réparer ?

**Comment by TmpName** [comment]
Ben si c'est passe en chnageant l'ordre des cookies, je vais retester, car moi, ca a pas marche une seule fois ?
Tu parles de cloudflare qui est passe ou tu as eu les liens ?

Pas teste encore la modif de @zakaria220, je fais ca dans la soiree.

**Comment by Arias800** [comment]
J'ai obtenu le lien final en changeant l'ordre des cookies mais après peux être que c'était un coup de chance

**Comment by ludopotte** [comment]
Comment fais-tu @Arias800 pour changer l'ordre des cookies dans le code de ZT s'il te plait ?

**Comment by TmpName** [comment]
@Arias800 Essayes cette fonction pr tes cookies, faut juste y passer la liste que tu passe en headers d'habitude

```
def CookieOrder(c):
    c2 = re.findall(' *([^;,]+?)=([^;,\/]+?)(?:;|$)',c)
    order = [2,1,0]
    cookies = ''
    for i in order:
        cookies = cookies + c2[i][0] + '=' + c2[i][1]+ ';'
    cookies = cookies[:-1]
    return cookies
```

Mais perso, j'ai pas vu de chnagements.

**Comment by Arias800** [comment]
J'essayerai vendredi

**Comment by lebigboss** [comment]
Ils ont mis un nouveau protecteur de lien, vous croyez que ce genre de captcha fonctionne sur kodi ?

**Comment by lebigboss** [comment]
Dsl j'ai rien dit je me suis trompé de site, la copie est trop ressemblante
C'est bien Dl-protect

**Comment by benoitdupart** [comment]
Bonjour, quelqu'un a trouvé une solution pour les liens ZT ?

**Comment by yvandicara** [comment]
@benoitdupart Apparemment @Arias800  va se remettre dessus vendredi

**Comment by yvandicara** [comment]
Nouvelle info : ce lien redirige htt ps://ww10.zone-telechargement1.org vers htt ps://1ww.zone-telechargement1.org/

Autre chose: je sais que j'ai déjà demandé mais est ce que c'est vraiment complique de rajouter une source vers htt ps://1ww.zone-telechargement1.org/ et peut etre qu'il aura pas le mm probleme de cloudfare.

Merci

**Comment by ludopotte** [comment]
Oui @yvandicara l'Adresse ZT est maintenant https://1ww.zone-telechargement1.org/

Âpres, je suis d'accord avec toi, ca serais bien d'avoir 2 sources ZT dans vStream.

**Comment by Arias800** [comment]
Toujours la même réponse c'est un manque de temps donc si vous voulez vous lancer allez si mais moi je peut pas on a pas encore inventer le clonage \o/
Et les bug de ce weekend ne venais pas de nous mais c'était de l'heure coter ^^

**Comment by TmpName** [comment]
Chez vous, vous avez 2 ordinateurs ? un qui vous sert 360 jours par an, et un qui prend la poussiere qui sert 5 jours par an quand le premier deconne ?
Non, perso je trouve inutile d'avoir 2 sites avec la meme chose, au pire si vous preferez l'autre, on change.
Y a peut etre 20/30 sources sur Vstream, perso sans ZT pendant 1 semaine, ca va pas tuer du monde.

**Comment by ludopotte** [comment]
Oui @TmpName c'est sur de pas avoir ZT pendant une Semaine ca va pas tuer le Monde mais ce Site a de la Qualité. Personnellement, moi je trouve pas mal d'avoir le plus de Source possible.

**Comment by Arias800** [comment]
Oui mais avoir des source mais personne pour les maintenrir ça ne sert a rien

**Comment by TmpName** [comment]
Ce site a de la qualite mais l'avoir en double ne sert a rien, tu n'as pas plus de sources, tu as les meme en doubles, nuance, et pour reprendre mon exemple precedent, meme si ton ordi ne sert que 5 jours par ans, tu doit t'en occuper autant que celui qui tourne 360 jours, donc 2 fois plus de boulot.

**Comment by yvandicara** [comment]
@TmpName @Arias800 je comprends pas de problème. Il n'a que vs deux qui maintenez vstream ?

**Comment by Arias800** [comment]
C'est bon corriger j'allais dans la bonne direction mais l'erreur venais de leurs site et pas du code de vstream https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by yvandicara** [comment]
@Arias800  champioooon!! Merci. Peut être une question bête mais pour mettre à jour le requesthandler on fait comment ?

**Comment by Arias800** [comment]
Normalement il est passez dans la derniere mise a jour mais il au cas ou il suffit de mettre a jour ce fichier (https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/handler/requestHandler.py) qui se trouve dans /resources/lib/handler/

**Comment by yvandicara** [comment]
@Arias800 ok. Merci à tous pour votre super boutot :)

**Comment by ludopotte** [comment]
@Arias800 Merci pour ton super Boulot.

**Comment by AngelineL** [comment]
Ça marche merci .

**Comment by TmpName** [comment]
Non, il n'y a pas que nous deux ^^, mais pour la source ZT, il n'y a presque que @Arias800, et a chaque fois que je me connecte je vois "probleme sur ZT" , donc laissez le respirer de temps en temps au lieu de lui demander de faire une autre source qui serait la copie de la premiere.

**Comment by rod93** [comment]
bonjour
lorsque je met les deux fichiers vtream me met une erreur

**Comment by TmpName** [comment]
Attend la MAJ auto.

**Comment by stanler2659** [comment]
@Arias800 comment on fait pour installer la beta avec le lien que vous donnez ? Je dois avoir un ordi si sa se fait direct dans Kodi section vstream ou ?? J’utilise Nvidia Shield merci sinon je vais attendre la maj automatique d’ici là fds ...

**Comment by Arias800** [comment]
Le plus simple c'est de passer par la https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream il suffit d'attendre et le site te donne un fichier ZIP a installer comme un Addon classique
