### ISSUE TITLE
PROTECTION CLOUDFLARE

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#2322]
Bonjour, quand on cliques sur Les Liens provenant de ZT, ca marque "Problème Protection Cloudflare". J'ai essayer de réparer mais sans succès. Comment faut-t'il faire pour réparer le code de Cloudflare ?

**Comment by yvandicara** [comment]
Sujet déjà ouvert ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2319
