### ISSUE TITLE
Question consernant regex

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#2323]
Bonsoir

Je mecsuse pour poster ce problème sur le github consernant le regex
 car c'est pas le bonne onderoi pour ce jor de question et j'ai pas ù la chance d'avoir une réponse et tout ceux que je l'ai est poser cette question mon répondu négatif  , je voulais savoir si c'est possible de faire un code pour activer
cette page : fcccam.com/free.php
J'ai pu avoir le user et mot de pass le host et  le port sur la page code source mais il me faut active la cline
avec le bouton on clic (activer 5 day) on vert.
Je sait que ce n'est pas le bonne onderoi pour cette question 
Mais  je veux de l'aide du poin de vue que ça concerne la programmation , c'est comme le decrypt protect .
vous me diriez d'activer la cline sur le site tout simplement mait mon but c'est de faire  un script auto update marche aux demarage et avec cron job chaque 5 jours, ou même avec kodi vstream!!!...

**Comment by TmpName** [comment]
Hu, moi j'ai pas trouve le "5days" au mini j'ai "1mois".
Le lien que tu donnes fonctionne pour la france ?

**Comment by mino60** [comment]
Non je suis actuellement en algerie 1mois !!!? Je suis étonné d'apprendre cette nouvelle pour 1Moi en une seul fois c'est beaucoup trop...

cccampk.fr
cccampk.fr/free-test-cline/
même avec VPN  adresse ip française j'ai toujour 5day
https://i.imgur.com/rZb6pgX.png

**Comment by TmpName** [comment]
Ben moi j'ai un boutton bleu a la place pour partager sur facebook.
Sinon sur la premier pahe le boutton vert est juste une requete get vers share.php, c'est de celui que tu parles ? car ya aucun parametre chez moi, ni port, ni mot de passe., faut s'enregistrer d'abord ?

**Comment by mino60** [comment]
A  bon !!! ils on changé  le code du site hier la page directe devient comme ça ;
htt p://www.fcccam.com/freecline.php#_=_
les clines son generer selon adresse ip , j'ai utilisé vpn pour avoir une autre cline si non il faut passer par premiume
https://pastebin.com/AvHqA7Fv


h ttps://i.imgur.com/xP9Ht0W.png

https://i.imgur.com/PFUJuxP.png

remarque le host et le port il est connue toujour fixer

**Comment by TmpName** [comment]
Bon la ca marche mais je vois pas ou est le probleme.
Sur la premiere page tu as deja toutes les infos, mais ca doit juste etre non valide.
Une requete post (index.php) avec 2 parametres user et pass qui doit valider le truc.
Y a meme pas de javascript, c'est quoi le soucis ?

**Comment by mino60** [comment]
Je veux faire un code pour valider le serveur son passé vert le navigateur
et l'ajouter comme une source sur vstream si non je faire un script Shell sous linux
qui marche avec le cron le but de renouveler la cline j'utilise vusolo4k
C'est comme tu a un abonnement annuel just avec la cline test sur tout ce site
h ttps://hiberlo.com/home/get-cccam-trial/cccam-test-line/

**Comment by TmpName** [comment]
Choisit un site, car la j'ai 50 url et je ne vois pas laquelle tu veux.
Si c'est fcccam.com/freecline.php je ne vois pas ou est le probleme.

**Comment by mino60** [comment]
Pour celui la ;
h ttps://hiberlo.com/home/get-cccam-trial/cccam-test-line/
Le premier tu a une seul cline paŕ ip adresse je croix que c'est 
fini pour lui mon problème comme je l'ai dit avant , j'ai pu avoire
Le host,port,user name et le passwoard mait avec ce site
pour tester  :  h ttps://testious.com 
la cline ne fonctionne pas il me faut le regex pour activer le bouton sumbit ou add
Je croix que le hiberlo.com c'est encore mieux ,il fonctionne avec adresse mail bidon et non par ip adresse

**Comment by TmpName** [comment]
Pas pu tester, j'ai utilise une adresse email jetable que j'avais sous la main, il me l'a pas prise.
Mais tu as quoi dans le mail ?

**Comment by mino60** [comment]
Moi j'ai tester une centaine de fois avec une adresse mail qui n'existe même pas et ç a marche
comme par exemple :
aminovitch908776544@yahoo.fr
pour avoir une autre
aminovitch908776545@yahoo.fr

**Comment by TmpName** [comment]
Mais d'apres ce qu'ils disent tu recoit des infos par mail.
Sinon pas vu de prb non plus, les cookies ne servent a rien, juste une requete POST avec 2 parametres.

**Comment by mino60** [comment]
Ça fait plus d'un an que j'utilise cette méthode et je l'essentiel que l'adresse mail soit juste même si elle n'existe pas réellement leur but de vérifier que vous n'êtes pas une machine
comme ce site similaire:
h ttps://cccampass.com/tests/takeatest/
qui utilise le recaptcha

**Comment by mino60** [comment]
J'ai trouver ça  sur le net
https://unix.stackexchange.com/questions/88825/press-a-html-button-via-sh

**Comment by TmpName** [comment]
C'est ce que je t'ai dit juste avant
`Sinon pas vu de prb non plus, les cookies ne servent a rien, juste une requete POST avec 2 parametres.`

**Comment by kenshiro000** [comment]
Question toute bête concernant les CCcam : qu’est-ce que ce type de lien peut être utilisé sur l’app « iptv smarters « ou les utiliser dans un lien m3u du genre « http //free ccam com:25000/get.php?username=XXXXXX&password=XXXXXX&type=m3u «  ?

**Comment by mino60** [comment]
Le cccam c'est pour Card sharing (DVB et DVB-S2) 
Il existe des générateur free iptv quand peut utiliser sur vstream peut-être a l'avenir 
comme vavoo pro la clé ce trouve dans le vavoo.log et faire une liste iptv avec cette clé 
 tu a même cannal sat cannal + sur l'écran 

http://www.vjackson.info/live/index  

/user/App Datta/Roaming/vavoo.log/

https://ia601509.us.archive.org/5/items/dreamosat/vavooLive.txt

**Comment by kenshiro000** [comment]
Ok merci pour toutes ces infos ! 👍🏻

**Comment by mino60** [comment]
> Bon la ca marche mais je vois pas ou est le probleme.
> Sur la premiere page tu as deja toutes les infos, mais ca doit juste etre non valide.
> Une requete post (index.php) avec 2 parametres user et pass qui doit valider le truc.
> Y a meme pas de javascript, c'est quoi le soucis ?

les gens ne voit pas les choses si facile comme tu la vois toi
Il ya qui ne connaît même pas ce que veut dire "if"  "else"...
moi ce que je veux c'est de traduire ce que tu dit on langage python
 avec les deux parametre post spécifier Http Request.

**Comment by TmpName** [comment]
La recherche de ZT utilise aussi une requete post.
https://developer.mozilla.org/fr/docs/Web/HTTP/M%C3%A9thode/POST

**Comment by Arias800** [comment]
Tout dépend générer les playlist d'après ce que j'ai vu de la conversation oui après pour les lire c'est déjà plus compliqué puisqu'il faut adapter le code pour parser la playlist

**Comment by mino60** [comment]
Je commence à comprendre un peut 
# Python + request + beautiful soup
Posté par j_m le 25/11/18 à 08:14. Évalué à 3 (+1/-0). Dernière modification le 25/11/18 à 08:14.


Le shell et les regex, ce ne sont pas les bon outils pour automatiser le scraping web et l'envoi d'une requête post.

Je te conseille python. La librairie request pour envoyer et récupérer les contenus html:
http://docs.python-requests.org/en/master/
et beautiful soup pour parser le contenu et ne récupérer que ce dont tu as besoin:
https://www.crummy.com/software/BeautifulSoup/bs4/doc

**Comment by mino60** [comment]
tenter d'interpreter le javascript simuler un clic 

Peut-être avec un navigateur sans tête? https://fr.wikipedia.org/wiki/Navigateur_sans_t%C3%AAte
C'est pour exécuter une page comme dans un vrai navigateur, mais en ligne de commande.

Répondre

**Comment by TmpName** [comment]
Si tu parles toujours de la meme page, je t'ai deja dis qu'il n y a pas de javascript, inspire toi du code de ZT.
