### ISSUE TITLE
skstream.info est de retour

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2324]
Bonjour,

Le site sktream est de retour. Si possible, veuillez re-active le site.

Merci

**Comment by LordVenom** [comment]
plus d'info ici https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2330

**Comment by informagenie** [comment]
J'aime bien [skstream.info](https://site-de-streaming.com/skstream-info/) ! Il est parmi mon préféré...

Merci !

**Comment by TmpName** [comment]
Ben si tu peux tester (et finir si besoin) la version du post de @LordVenom .
La derniere version, doit marcher si le FAI bloque l'ip sans image, et a 100% pour les autres.

Apres je suis d'accord, tres bon site, c'est pour ca que me suis prit la tete, mais si elle se fait bloquer sur les FAI, son audience va baisser.

Au pire je vais la desactiver pour la recherche globale, pour eviter de foutre le bordel dans Vstream si ma bidouille est trop lourde, seul les "connaisseurs" s'en serviront.
