### ISSUE TITLE
Voirfilm

### ISSUE THREAD

**Issue by kenshiro000** [Kodi-vStream/venom-xbmc-addons#2325]
Bonjour, serait-il possible d'enlever le return false de voirfilm ? Je viens de tester  quelques épisodes de séries pris au hasard beaucoup de liens fonctionnent très bien (Streamango, Upvid, vidoza, vidtodo, mystream, rapidvideo ). Merci ✌🏻

**Comment by TmpName** [comment]
Ha merde, me disait aussi, il marchait plus depuis la maj, alors que je suis tjurs dessus ^^.
Dsl, il a du partir en sucette a un moment, je le remet de suite.

**Comment by kenshiro000** [comment]
Ok nickel merci 👍🏻
