### ISSUE TITLE
Sous catégories marques pages

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2333]
Bonsoir à tous,

Avec des amis on se partage notre vstream.db afin que l'on puisse s'ajouter des marques pages mutuellement. Cela fonctionne bien mais je voulais savoir si il était possible de rajouter des sous catégories dans les marques pages ? 

Comme ca je pourrais avoir des marques page de Pierre, Paul ou Jacques :)

Merci

**Comment by TmpName** [comment]
Nope, dsl, je t'avoue que j'avais meme pas pense a cette utilisation.
