### ISSUE TITLE
Ajout recherche

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2335]
Vraiment trop de soucis avec les urls des recherches depuis la modif des input output j'ai donc rajouter un urllib.quote_plus au searchtext pour avoir un retour du style " master+of+none" plutot que des espaces pour les sites ne supportant pas le + mais préfèrent le %20 faut ajouter manuellement un replace dans la fonction showmovie.

**Comment by TmpName** [comment]
J'ai oubli des sites ?
Normallement y en avait juste 4 / 5 et oui justement j'avais modifie le code dans showmovie

**Comment by LordVenom** [comment]
Oui mais la je suis tomber sur une erreur qui ma fait perdre la tête. 

qu'ont soit en direct  showMovies(sUrl) la y a des espaces je dirais normal puisque aucun traitement

mais dans showmovie avec un input espace aussi normalement y a un traitement d'url 

dans le lot y a une logique qui me perturbe mais soit ça merde que sur la recherche j'ai donc retoucher la recherche. XD

**Comment by TmpName** [comment]
Ben y a un truc chelou dans kodi, j'ai pas trouve non plus 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2302

Mais comment on peut reproduire ton bug ?

**Comment by LordVenom** [comment]
tu vas dans cinemaVF tu fait un recherche normal dans la source ça plante y a des espaces en recherchant master of none y a pas de resutat mais y a une erreurs http plutot qu'un "pas de resultat"
puis une recherche global même erreur.

et tu vire la modif que j'ai faite dans gui.showKeyBoard 

return urllib.quote_plus(sSearchText)

return sSearchText

**Comment by LordVenom** [comment]
Aprés avec tout le code ça devais arriver y a eu télément de modif et clairement ça manque de commentaire pour la partis coeur de vstream ont c'est plus ceux qu'on envoie et ce qu'on reçoit.

**Comment by LordVenom** [comment]
En faite la ou le texte devrais être encoder c'est dans request c'est pas logique de foutre un quote sur du texte l'ors du request c'est lui qui devrais encoder avant d'envoyer la demande.

**Comment by TmpName** [comment]
Yep mais jamais quote_plus, sinon c'est mort vu qu'il y a modification irreversible. Il est impossibe de savoir si un + est un vrai + ou un espace.

Essayes avec ligne 216 du fichier site
```
    if sSearch:
        sUrl = sSearch.replace(' ','+')
```

Ca depend aussi si le site fait une requet en GET ou en POST, mais moi je me prend pas la tete, j'ai deja fait cette modifs aux 4/5 sites qui deconnaient. Je remplace juste les espaces par des +, uniquement aux sites qui le demandent, et uniquement au moment ou ca coince, sinon fonctionnement normal, pour moi c'est plus propre possible.

**Comment by LordVenom** [comment]
hé je vais le faire cinemaVf merde aussi en recherche visuelle forcement ta modif résoudra le soucis mais je trouve pas ça plus propre.

**Comment by LordVenom** [comment]
ben oui j'ai reflechis aussi logiquement oui c'est + mais y a des sites en %20 donc nous il faudrais qu'ont est le chois une option du request comme pour POST ou GET qu'on puisse lui dire + ou %20 par default + mais si on veut %20

**Comment by TmpName** [comment]
Hu, ben si tu es motive ^^. Ca doit pouvoir aussi se faire automatiquement, mais ca me rappelle le bordel qu'on a eu pour les espaces dans les chemins.

En fait la methode en place n'est pas la meilleure ok, mais elle permet de revenir en arriere, comme avec un bete replace('x','y'). Donc pour moi c'est celle qui ne nous bloquera pas, apres chaque site encode comme il veut, donc pour moi le plus logique est de coller le "patch" dans le fichier site en fonction des besoins.

Si tu veux rigoler encore un autre cas, google utilise # et %20 > url#blable%20bla=blabla

**Comment by LordVenom** [comment]
je regarde la je comprend pas comment les sites fonctionne sans le replace '', + en faite.

**Comment by TmpName** [comment]
En fait c'est le formulaire qui met un '+' automatiquement, mais sinon y'en aurait jamais.
Donc je peux dire une connerie mais si tu as l'url ww.sit/page a la con ca va devenir ww.site/page%20a%20la%20con. Et si tu as un formulaire sur cette page ca va devenir ww.site/page%20a%20la%20con?parametre1=aaaa+bbb+ccc

**Comment by TmpName** [comment]
Et si tu as un '+' dans les parametres
ww.site/page%20a%20la%20con?parametre1=aaaa+bbb+ccc%2Bccc

Moi apres reflection, j'aime bien faire au cas par cas ^^.

**Comment by LordVenom** [comment]
ça rend foux il envoie http://buzzmonclick.com/?s=touche pas a mon

dans request j'aimerais bien avoir la vrais url faut que je trouve comment mettons c'est un %20 pk voir film ça fonctionne pas puisque j'ai teste + ou %20 même résultat de recherche.

**Comment by TmpName** [comment]
Voir film fait un POST, le parametre ne passe par en url.

**Comment by LordVenom** [comment]
cinemaVf pardons

**Comment by LordVenom** [comment]
fonction a l'arache quesque tu pense de 

    def request(self, replace="+"):
        #Supprimee car deconne si url contient ' ' et '+' en meme temps
        self.__sUrl = self.__sUrl.replace(' ', replace)
        return self.__callRequest()

**Comment by TmpName** [comment]
Le prb c'est que comme tu le disait avant, l'url qu'on passe a la fonction est sensee etre deja encodee.
Si quelqu'un fait 

```
oRequestHandler = cRequestHandler(url)
sHtmlContent = oRequestHandler.request()
```

C'est a lui de verifier que url est bien encodee, normallement tu ne devrais jamais avoir d'espaces. C'est a lui de regarder comment fonctionne le site, et d'encoder correctement l'url pour la passer a la fonction. La si je passe rien en parametre, ca va me coller des '+' partout

**Comment by LordVenom** [comment]
Ben y a 2 option la tu passe soit une recherche et la c'est pas coder puisque c'est du texte taper faut refaire les sites pour encoder ça ou input qui devrais être coder mais qui l'es plus.

donc la pour le moment au moin les request sont coder et tu peux choisir de coder en + en %20 ou en espace.

Pourquoi ça te mettrais des plus partout avec le replace si y a pas d'espace y a pas de traitement. j'avoue le urllib.quote c'est plus chiant il encode tous ce qui traîne.

**Comment by LordVenom** [comment]
Le soucis c'est la recherche global vue que c'est elle qui fait l'url de recherche et quel peux pas savoir si tu veut un + ou un %

**Comment by laquarico** [comment]
Bonsoir desole de pirater un comment mais j ai un problem...mon kodi a completement disparu..je l ai reinstale sur ma xbox mais je n ais pas es file explorer pour partager le repo....quelle adresse doi je taper pour recupere le repo via zip file svp merci d avance

**Comment by LordVenom** [comment]
Alors l'erreur et la sUrl = URL_SEARCH[0] + sSearchText ont ne creer pas d'url avec des espaces MyBad

Mais pour modifier ça c'est la merde, sur le site c'est simple, mais pour la recherche global carrément moins la seul solution c'est de rajouter un argument à URL_SEARCH_MOVIE pour savoir si le site veut un codage + ou %20.

**Comment by TmpName** [comment]
URL_SEARCH[0] ne contiendra jamais d'espace car elle viens du fichier site et est normallement bien encodée, sauf si le mec qui a fait le fichier site s'est loupe.
Donc tu peux laisser des espaces dans sSearchText, le fichier site corrigera l'url en fonction de ses propres besoins juste avant de faire la requete
1 - espace vers %20
2 - espace vers '+'
3 - espace intacts, je crois qu'il ya des sites ou URL_SEARCH[0] = '' et ou il y a un traitement special.

Et si vraiment, ca deconne quelque part dans le plugin, tu met soit des '+' soit des '%20', mais faudra repasser tout les fichiers sites pour refaire les convertions pour ceux qui vont deconner.
Moi je me prendrais pas la tete avec une methode globale.

**Comment by johngf** [comment]
a la base une modif pour un site qu'on ne verra jamais qui nécessite de modif d'autre sites...

**Comment by TmpName** [comment]
Ben c'est plutot que la methode de base n'est pas fiable, je prefere avoir une base sure a 100%, meme si aujourdhui y en a qu'un, pourra y en avoir d'autres.
Et la modif va prendre 10 mn pr l'ensemble des sites, d'autant plus que si le site VEUT des '+' autant etre sur que l'url passe a ete corrige, en mettant un replace (' ','+') 
Apres si tu veux faire un truc universel, tu regarde l'url, si elle contient un ? , remplacer tout les espaces qui suivent pas des '+'

**Comment by LordVenom** [comment]
Hum sSearchText le l'aisser tel quel oui mais pas si il est utiliser dans une url 
sUrl = URL_SEARCH[0] + urllib.quote_plus(sSearchText)

C'est le plus propre mais pas le plus simple perso je pense que je vais mettre des + partout pour la logique c'est au site avec des %20 de faire exception pas l'inverser.

**Comment by TmpName** [comment]
Mais le prb c'est que le '+' est autorise dans les urls, si tu remplace par des plus, il n'y a plus moyen de faire marche arriere
ww.site/page+a+la+con/lien?data=titre film
>ww.site/page+a+la+con/lien?data=titre+film
>ww.site/page a la con/lien?data=titre film > BUG si j'essaye de remplacer + par espace. Le replacement par des + est irreversible.

**Comment by LordVenom** [comment]
J'avais compris c'est uniquement l'url qui doit être coder. Mais la pas de moyen simple vas faloir refaire toute les recherches.
