### ISSUE TITLE
Question .strm

### ISSUE THREAD

**Issue by ludonice54** [Kodi-vStream/venom-xbmc-addons#2336]
Bonjour,

Est ce qu'il serait possible de me fournir un exemple de fichier .strm utilisant la fonction Display_protected_link ? 

Je cherche a creer des fichiers .strm à partir de lien dl-protect que je récupère de ZT mais je galère à mettre en forme tout ca 

J'ai bien les paramètres sThumbs , siteurl et smovietitle mais impossible de creer un .strm fonctionnel .

**Comment by johngf** [comment]
normal c'est pas possible le strm n'accepte que des liens videos

**Comment by ludonice54** [comment]
Pourtant il y'a une semaine ce type de .strm fonctionnait en appelant la fonction Display_protected_link
plugin://plugin.video.vstream/?function=Display_protected_link&sCat=1&sMovieTitle=%202036%20origine%20&sThumb=https%3a%2F%2Fwww.zone-image.com%2Fuploads%2Flk6Bj.jpg&site=zone_telechargement_ws&siteUrl=http%3a%2F%2Fwww.dl-protect1.com%2F4355555154062067067565155503750590633850480670h49490k3756530x0f600k0m&title=%202036%20
