### ISSUE TITLE
Lien 9Docu HS

### ISSUE THREAD

**Issue by mannou78** [Kodi-vStream/venom-xbmc-addons#2337]
Bonjour,

9Docu semble HS avec une error 503 Connection Failed

Merci

**Comment by TmpName** [comment]
Yep, essayes sur navigateur, pareil, site HS, a surveiller.

**Comment by Nux007** [comment]
Infos pour le site 9Docus, à voir ici : https  ://twitter.com/9docu_com?lang=fr

**Comment by Nux007** [comment]
9Docus en ligne et fonctionnel sur VS
