### ISSUE TITLE
Problème avec plusieurs lien

### ISSUE THREAD

**Issue by helpmoi** [Kodi-vStream/venom-xbmc-addons#2338]
Décrivez le bug :
Impossible d'ouvrir un film depuis film illimite

Votre system

OS: Android (android box et Samsung galaxy s8+)
Version Kodi 17.6
Version Vstream la dernière 

Nous devons le reproduire
Pour cela il nous faut:

Le nom du site :Kaydo
Le titre du fim/serie : Peut importe le film
Le nom du host : quasi tous les lien (upvid, openload, etc)

Log:
Voici le lien du log:

https://slexy.org/view/s2G9joPNCw

**Comment by johngf** [comment]
je viens de testé equalizer 2 avec (click open) ça fonctionne chez moi 
pour open load tu as un timeout normal le 1080p c'est lourd pour cet hébergeur surtout le soir

**Comment by TmpName** [comment]
Apres tu n'as pas la totalite des log mais pour ton dernier essais pour celui sur vcstream, le lien a ete decode, Kodi a essaye de le lire, et soit c'est toi qui l'a interrompu, soit ton systeme n'a pas pu le lire, car de suite apres 
`23:12:36.679 T:500597941488   ERROR: CDVDMediaCodecInfo::ReleaseOutputBuffer ExceptionCheck index(5), render(1)`
Et il a tout stope.

**Comment by helpmoi** [comment]
@johngf En effet, click open s'ouvre. Merci.

@TmpName Je n'ai rien stoppé. Donc le système a dû arrêter de lire le lien... Pourquoi et comment empêcher cela ?

**Comment by TmpName** [comment]
C'etait l hebergeur vidcloud et le lien marche tres bien tel quel.
Regler ton systeme, pilotes, ...,  mais la je fais pas android.
