### ISSUE TITLE
Zone téléchargement hs ? 

### ISSUE THREAD

**Issue by thorsten68** [Kodi-vStream/venom-xbmc-addons#2339]
Tous les liens zt sont hs depuis plusieurs jours chez moi. Je suis le seul ??
Merci pour votre taf !

**Comment by AzeRim** [comment]
Déjà résolu sur #2319 . Il faut remplacer les 2 fichiers ou attendre la MAJ 0.6.72

**Comment by thorsten68** [comment]
Ok merci

**Comment by lapin47** [comment]
Zone téléchargement  ses fini
Ses (https://annuaire-telechargement.com)
