### ISSUE TITLE
Chaine Tv

### ISSUE THREAD

**Issue by gmrnico** [Kodi-vStream/venom-xbmc-addons#2340]
Bonjour je cree ce petit post car y a encore 5 6 jours y avait pas mal de chaine Tv qui marcher seasons chasse peche le sport etcccc et la plus rien penser v ous que cela va revenir a la normal ? vous y bossez dessus ? au passage suerbe addon .... Thanksssssssssss

**Comment by LordVenom** [comment]
Bonjour, sans plus d'info et un effort sur la présentation de ton posts personne ne pourras répondre dsl pour l'attente.

**Comment by Arias800** [comment]
Si c’était iptv gratuit la source qui marchait pas c'est corriger ^^
