### ISSUE TITLE
film 3d

### ISSUE THREAD

**Issue by rod93** [Kodi-vStream/venom-xbmc-addons#2344]
bonjour,
est il possible d'avoir une nouvelle catégorie 3d hd merci 
ps: je ne trouve aucun film en 3d 

Cordialement

**Comment by kenshiro000** [comment]
Tu peux trouver des films 3D sur extreme down et ZT.

**Comment by BENJI97200** [comment]
@ rod93 ...la première page de vstream/sources/zt  ou extrem down/films 3d.....

**Comment by Arias800** [comment]
Si la recherche n'affiche pas de film 3D c'est que le site n'en affiche pas non plus et là on ne peux rien y faire  ^^
