### ISSUE TITLE
LiveTv.sx

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2345]
Bonjour,

Merci beaucoup d'avoir ajoute la section Sport avec cette livetv.sx. J'espere que vous allez completer le developement :)

Je ne suis pas sur mais cette logique suivante (dans la source) ne va pas marcher pour youtube and laola. Pouvez-vous reviser le code SVP? 
    if not 'aliez' in sUrl4:
        sPattern = '<td bgcolor=".+?" *align="center".+?\s*<iframe.+?src="([^"]+)".+?</iframe>'
    elif 'youtube' or 'aliez' or 'laola1tv' in sUrl4:
        sPattern = '</script>\s*<iframe.+?src="([^"]+)".+?</iframe>\s*</td>'
    else:
        sPattern = '<td bgcolor=".+?" *align="center".+?\s*<iframe.+?src="([^"]+)".+?</iframe>'

Et je complete le code pour thesports4u mais je ne sais pas comment rouler votre addon sur Eclipse donc je ne peux pas modifier/tester la modification. Veuilez-vous ajouter cette modification ?

sPattern2 = '<script>fid="(.+?)"'
fid = self.get_link(url, sPattern2)
if fid:
    url2 = 'http://wlive.tv/embed.php?player=desktop&live='+fid+'&vw=700&vh=440'
    h = {'User-Agent':utils.USER_AGENT, 'Referer':'http://thesports4u.net/','Host':'www.wlive.tv'}
    sHtmlContent3 = utils.http_req(url2,customHeader=h,saveCookie=True)
    
    m = re.search('return.*?\[(.*?)\].*?\+\s+(.*)\.join.*document.*?"(.*?)"', sHtmlContent3)
    if m:
      timeVar = m.group(2)
      hashVar = m.group(3)
    
      #http://tv.wlive.tv/tv/lu2mIWw6KZ20180321/playlist.m3u8?hlsendtime=1542297480&hlsstarttime=0&hlshash=jhTrgemr-kGm9E01YIVfqkZ9VPobibqbDRiov2psf_A=
      url3 = ''.join(m.group(1).split(','))     
      url3 = 'http:' + url3.replace('"','').replace('\/','/')
      
      m = re.search(timeVar + '.*?\[(.*?)\]', sHtmlContent3)
      if m:
        timeStr = ''.join(m.group(1).split(',')).replace('"','')
        url3 = url3 + timeStr

      m = re.search(hashVar + '>(.*?)<', sHtmlContent3)
      if m:
        hashStr = ''.join(m.group(1).split(',')).replace('"','')
        url3 = url3 + hashStr

Et derniere chose: Le site 'emb.aliez.me' a change du nom: 'emb.aplayer1'.

Encore merci pour votre travail

**Comment by LordVenom** [comment]
Bonjour, pour faire tourner le code il faut le faire à l'ancienne j'ai jamais tester mais je pense pas qu'un interpréteur puisse fonctionner avec les imports xbmc, xbmcgui ect..

A l'ancienne c'est a dire qu'il faut lancer Kodi pour voir les changements grâce au mode debug de Kodi et des prints ou des VSlog()

j’explique comment j'utile un dossier lien dans Kodi pour pouvoir travailler direct sur la version github
[ICI](http://vstream.ga/docs/clone/)

**Comment by TmpName** [comment]
Pour proposer tes modis, le plus simple sans outils, a la dure, c'est de passer par github directement.
Tu affiches le fichier, editer, tu fais tes modifs et tu valides, ca va te dire que tu n'as pas acces, et automatiquement creer un fork sur ton compte github, apres suffit de cliquer sur tout les bouttons vert, pour envoyer le pull request.

**Comment by sviet2k** [comment]
@Arias800  viens de le faire. :)
Merci beaucoup tout le monde de m'avoir aide.

**Comment by Arias800** [comment]
Tout corriger plus que autre modification https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2346
Par contre laola n'a jamais ete ajouter car j'ai jamais réussit et Youtube marche de manière aléatoire a cause de Kodi ^^

**Comment by Ovni-crea** [comment]
@Arias800 si ça peut aidé pour thesports4u 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2212#issuecomment-423837842

**Comment by Ovni-crea** [comment]
@Arias800 je croyais que t'avais pas terminé c'est pour ça c'est pas grave sinon
