### ISSUE TITLE
vstream.ga/repo/

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2354]
Bonjour,

Oui l'adresse http://vstream.ga/repo/ est enfin fonctionnelle.

Elle a même retrouver son [Tutorial](http://vstream.ga/docs/installation2/)

**Comment by ragora13** [comment]
Bonjour
l'adresse est-elle toujours fonctionnelle, car elle ne fonctionne pas et votre site non plus
merci

**Comment by LordVenom** [comment]
nouvelle adresse le nom de domaine n'est plus a nous

https://kodi-vstream.github.io/venom-xbmc-doc/

https://kodi-vstream.github.io/venom-xbmc-doc/repo/

Note suivant votre navigateur le cache peux toujours vous afficher la redirection.

**Comment by Loloxbzh** [comment]
Bonsoir,

Est-ce normal que plus aucune série ne soient visible ? les films pas de problème mais les séries tout est vide...

Ça marchait très bien la semaine dernière.

Merci d'avance.

**Comment by TmpName** [comment]
Heu, quel site ?

**Comment by Loloxbzh** [comment]
tout les sites...

**Comment by TmpName** [comment]
Moi j'en ai essaye un pas vu de problemes.
Un exemple ?

**Comment by TmpName** [comment]
"Home" "serie" "dernieres serie" Et la c'est vide ? Un log ?

**Comment by Loloxbzh** [comment]
C'est complétement vide oui, dans tout les répertoires série...

**Comment by Loloxbzh** [comment]
c'est bon y avait un filtre a modifier dans les recherches :) ca remarche !
MERCI

**Comment by Arias800** [comment]
@LordVenom le site "vstream.ml/repo/" est down c'est possible de le remettre fonctionnel ou pas ?
