### ISSUE TITLE
Streamio

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2355]
Vraiment sympas bon c'est écris en nodejs ont peux pas être parfait XD.

https://www.youtube.com/watch?time_continue=64&v=Pax3scyv2MQ

**Comment by TmpName** [comment]
D'ailleurs en hors sujet, y en a qui ont teste le plugin netflix pour kodi ?
Car justement ca a l'air vachement mieux integre sur ton appli, meme si justement c'est un addon fait par la communaute (non officiel).
On va peut etre avoir un concurrent a kodi ^^.

**Comment by LordVenom** [comment]
J'ai fait un peux le tour des applis mais appart offrir des addons en .json .js y a rien d'interessant en python code source ouvert, la dessus Kodi et vraiment au sommet. Si j'avais asser de connaissance je mettrais au pyobject vstream à lui seul mangerais toute la concurrence Française sérieux.

**Comment by TmpName** [comment]
C'est clair, c'est pour ca que meme en nodejs ca peut facilement etre plus leger.
Mais je me vois pas reconvertir Vstream en JS, par contre pour le coup, moins de probleme avec les code en JS comme recpatcha.
Mais ce projet ne tourne que avec nodeJS ? Ca prend aussi le python ?

**Comment by LordVenom** [comment]
https://github.com/Stremio/stremio-addon-sdk

Que du node il me semble et il faut forcement passer par un serveur pour retourner des json si j'ai bien compris, c'est con comme idée j'ai pas ête plus loin dans les infos.

**Comment by TmpName** [comment]
Ha yep, exact faut heberger un truc.
