### ISSUE TITLE
Problème source depuis maj 0.6.73

### ISSUE THREAD

**Issue by Kiri85** [Kodi-vStream/venom-xbmc-addons#2356]
Bonsoir,

Depuis la dernière maj, à savoir la 0.6.73, j'ai le message systématique : aucune information lorsque je clique sur un lien. 

Ma machine : kodi sur raspberry pi / raspbian
Version kodi : 17.3
Log kodi : https://slexy.org/view/s20dZvFoI9

J'ai un compte Premium Uptobox et je prends principalement sur ddl island et ZT, mais les autres liens ne passent pas non plus.

J'ai testé également extrem download mais je ne comprend pas comment ça fonctionne sur vstream. 

J'ai fais une recherche avec "Bates Motel".

Merci de votre boulot ;)

**Comment by lefou66** [comment]
même chose chez nous...les sources DDL,full stream et Zt ne fonctionne plus .
Kodi 17.6
vstream à jour
tx95

**Comment by Arias800** [comment]
Zt est down leur nouvelle adresse est morte pour les autre je regarde

**Comment by lelensois** [comment]
Bonjour Zt est mort.
La nouvelle adresse est : https://www.annuaire-telechargement.com/
Esperons que LordVenom met a jour les sources de vstream bientot

**Comment by lelensois** [comment]
@Arias800 non chez moi ca foctionne y a eu des problemes ce matin mais ca été resolu

**Comment by Arias800** [comment]
Chez moi c'est toujours pas revenu donc il doivent pas encore avoir tout regler ^^

**Comment by lelensois** [comment]
Ok désolé moi sous firefox win 7 ca fonctionne

**Comment by lelensois** [comment]
@Arias800 C'est difficile de changer une url dans vstream ou de creer une souce nous meme ?
Je sais que LordVenom va mettre a jour mais il doit avoir un travail et une vie privée et j aimerai bien participer... 
Merci de ta reponse

**Comment by Arias800** [comment]
Y'a déjà un pull request de près pour changer l'url host mais j'attends de voir si d'autre personne on accès au site car si ca ce trouve il change encore l'url ^^

**Comment by Ovni-crea** [comment]
Ça commence fort ils font déjà des fakes ^^ htt ps://www.annuaire-telechargement.cc faites attention

**Comment by BENJI97200** [comment]
Bjr,sur mon téléphone Zt passe sans problème, alors que sur shield tv non,pourtant mm mise à jour sur les 2....une solution svp?

**Comment by lelensois** [comment]
@Arias800 As tu reussi a te connecter sur AT vu que maintenant c est son nouveau nom ?

**Comment by Arias800** [comment]
Le site est toujours down chez moi

**Comment by lelensois** [comment]
![image](https://user-images.githubusercontent.com/22278158/48971667-1a413900-f01d-11e8-9834-a60185ca1581.png)
Ca fonctionne chez moi et c est pas un clone bizarre

**Comment by Arias800** [comment]
Bon bah du coup j'ai merge le pull request on verra bien ^^

**Comment by lelensois** [comment]
Et ca veut dire quoi j ai merge le pull request ?

**Comment by Arias800** [comment]
Ça veut dire que j'ai intégrer la modif de @Ovni-crea dans le code de Vstream ce qui fait qu'il va etre pris en compte a la prochaine maj ^^

**Comment by lelensois** [comment]
Ah ok nickel on a plus qu a attendre le feu vert de LordVenom

**Comment by LordVenom** [comment]
Faut pousser la team à faire des mises a jour il ont les permissions XD

**Comment by lelensois** [comment]
Mon dieu le grand LordVenom me parle.... j en reste sans voix....
Juste un copier coller ca ira ?

**Comment by Arias800** [comment]
Si tu copie et colle correctement le contenu de ce lien normalement ça devrais marcher https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py

**Comment by LordVenom** [comment]
Vieux surement, grand bof bof... XD

**Comment by lelensois** [comment]
@Arias800 merci je vais tenter ca ce soir.... ce sera ma mission vu que ce soir la tv est a Mme pour danse avec les stars mdr

**Comment by lelensois** [comment]
@LordVenom on est toujours jeune dans sa tete c est le corps qui ne suit plus..... pour ma part j ai 44 ans et je le ressents qd je fais la fete le delai de recuperation est bien plus grand qu a 20 ans mdr

**Comment by LordVenom** [comment]
> Votre mission, si toutefois vous l'acceptez.

A tient il pas trop mal le nouveau Mission impossible juste Tom Cruise si tu fait des films d'action arrête de manger.

**Comment by BENJI97200** [comment]
@Arias800...mm en remplaçant le fichier tjrs aucune information sur shield tv pour Zt

**Comment by lebigboss** [comment]
@BENJI97200  Moi ça fait fonctionne sur shield tv ZT avec la beta du site et sur Linux aussi
Par contre si tu parle de t'es raccourcis ZT c'est normal, met à jour tes raccourcis
![screenshot_20181124-232412](https://user-images.githubusercontent.com/12912677/48973549-f47a5b00-f041-11e8-9d2e-fae366e183c4.png)
![screenshot_20181124-232455](https://user-images.githubusercontent.com/12912677/48973553-fc39ff80-f041-11e8-9b40-b37b28a28cc4.png)

![capture du 2018-11-24 23-35-58](https://user-images.githubusercontent.com/12912677/48973560-0f4ccf80-f042-11e8-90a4-2d82f8aa30ed.png)

**Comment by BENJI97200** [comment]
@ lebigboss ....merci ca fonctionne en allant ds source /Zt ,mais comment mettre à jour les raccourcis ? Stp

**Comment by BENJI97200** [comment]
@ lebigboss....en faisant cette manipulation, c bon ca me l a mis à jour merci bcp....

**Comment by lelensois** [comment]
@BENJI97200 ET @lebigboss pourriez vous me donner la beta de votre vstream svp ?
J ai voulu remplacer les liens dans mon vstream mais suis une m.... je n y arrive pas.

**Comment by Arias800** [comment]
La bêta est téléchargeable ici : https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream
Le probleme de copier coller c'est que le moindre espace peut tout faire planter ^^

**Comment by lelensois** [comment]
OK merci @Arias800 par contre le fichier fait 152 Mo c est normal ?

**Comment by Arias800** [comment]
Je sais pas de toute façon le site télécharge les fichier du github donc si il fait 152 mo c'est que c'est le cas ^^

**Comment by Kiri85** [comment]
Pas mieux,il me sort des fichiers introuvables sur la plupart des sources + aucune information sur ddl island et je suis sur qu'il y a la série dessus.
Dites moi si vous voulez les logs

Merci ;)

**Comment by Arias800** [comment]
Oui pour le coup je veux bien les log (je vais au passage reregarder celui qui est plus haut ) ^^

**Comment by Kiri85** [comment]
Https://slexy.org/view/s2ItnvRMFU

**Comment by Arias800** [comment]
J'ai mis une version corriger de dll island sur le github essayer d'installer la beta car c'est impossible que tu est cette erreur avec la nouvelle version  : 
```
22:52:13.469 T:1475343280   ERROR: Traceback (most recent call last):
22:52:13.469 T:1475343280   ERROR:   File "/home/pi/.kodi/addons/plugin.video.vstream/default.py", line 139, in parseUrl
22:52:13.471 T:1475343280   ERROR:     function()
22:52:13.471 T:1475343280   ERROR:   File "/home/pi/.kodi/addons/plugin.video.vstream/resources/sites/ddl_island_su.py", line 717, in Display_protected_link
22:52:13.477 T:1475343280   ERROR:     sHtmlContent = DecryptDlProtecte(sUrl)
22:52:13.478 T:1475343280   ERROR:   File "/home/pi/.kodi/addons/plugin.video.vstream/resources/sites/ddl_island_su.py", line 821, in DecryptDlProtecte
22:52:13.478 T:1475343280   ERROR:     except timeout:
22:52:13.478 T:1475343280   ERROR: NameError: global name 'timeout' is not defined
```

**Comment by lebigboss** [comment]
Par contre, dans la recherche global ça n'affiche pas les liens de la source ZT. C'est normal ?

**Comment by Arias800** [comment]
Ça par contre je peux pas rien n'y faire car j'ai plus accès a zt ^^

**Comment by lebigboss** [comment]
@Arias800  Dommage mais c'est pas trop grave, mercii

**Comment by Kiri85** [comment]
@Arias800 : je prends le lien de la beta que tu as mis au dessus ? 

Merci

**Comment by Arias800** [comment]
Oui ou alors tu peux attendre que quelqu'un lance la mise a jour auto ^^

**Comment by Kiri85** [comment]
Comment je peux voir que la beta est bien appliquée ? 
Je pense que je l'ai bien installée mais le souci reste le même 

Merci

**Comment by Fabiodirt** [comment]
@Arias800 , si quelqu'un lance la mise à jour auto, tout rentrera dans l'ordre, ou il faut attendre la mise à jour de venom ?
Je suis newbie, désolé si ma question semble "con".
Nonne journée à tous

**Comment by Arias800** [comment]
Redonne le log  @Kiri85 stp pour voir si il y a toujours l'erreur de dll island
@Fabiodirt Il faut attendre la mise a jour auto après il n'y a pas que LordVenom qui peut les lancer c'est juste que c'est souvent lui qui s'en occupe . Ensuite tout ce qui est corriger ici va être corriger chez vous vu que ça va mettre a jours les fichier ^^

**Comment by Fabiodirt** [comment]
Merci pour l'info @Arias800 :)

**Comment by Kiri85** [comment]
@Arias800 je pense que la beta est passée car j'ai la source ddlfr, à moins que ce soit dans la 0.6.73.
Voici les logs : https://slexy.org/view/s20IY837gf

Merci

**Comment by Arias800** [comment]
C'est avant la source ddlfr parcontre le liens slexy ne marche pas ^^

**Comment by Kiri85** [comment]
Je  t'ai remis un autre lien

**Comment by lelensois** [comment]
La bêta fonctionne j'ai accès à ZT... en attendant la maj de LordVenom le 30 je m'en contenterai merci @Arias800 et @LordVenom de m'avoir répondu et aidé

**Comment by Kiri85** [comment]
Ce ne fonctionne pas non plus.
J'ai refais la config donc kodi est à jour en 17.6.
J'ai testé avec la dernière maj et les titres s'affichaient mais idem : aucune information.
Je viens de tester à l'instant avec la beta et la comme au début, aucune information juste après la source.

Voici les logs : https://slexy.org/view/s2SUHAgwMZ

Merci

**Comment by Arias800** [comment]
Là je vois pas @TmpName @LordVenom une idée ?

**Comment by Kiri85** [comment]
Je viens de tester avec le mot "indestructibles" et ça passe bien sûr ddl island par contre j'ai testé avec "Harry potter", idem aucune information
J'ai d'ailleurs pareil sur la source ADKami,free-telechargement ,libertyland, ZT..

**Comment by TmpName** [comment]
Ben comme @Arias800 je comprend rien a tes logs.
Tu passes par ou pour acceder par exemple a LDD-Island ?
Dans les logs tu devrais avoir affiche par exemple
`[PLUGIN] Vstream: load site ddl_island_su and call function showSearchMovies`

Ou alors 

`[PLUGIN] Vstream: load site ddl_island_su and call function showMenuFilms`

Juste avant la recherche. Tout ce qu'on voit c'est que ta machine a beaucoup de mal juste pour lire une image, mais aucune ligne au sujet de Vstream ....

**Comment by Kiri85** [comment]
DDL-island tu veux dire.
Je fais une recherche et ensuite je scroll en bas pour avoir des island.
Bien sûr qu'elle est co à internet en filaire.
Je te postes les logs dans 2min

**Comment by Arias800** [comment]
C'est bizarre que ça genere une erreur ça
 ```
20:14:50.366 T:1911382016   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=showSearchText&sFav=showSearchText&site=cHome&siteUrl=http%3a%2f%2fvenom&title=Recherche
20:14:50.369 T:1911382016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showSearchText&sFav=showSearchText&site=cHome&siteUrl=http%3a%2f%2fvenom&title=Recherche) failed
```

**Comment by TmpName** [comment]
Ben je vois pas ce qui est en plus dans la derniere version et qui peut provoquer ca.
On pourrait activer plus de log via kodi, mais ce que je te propose, c'est de faire une copie complete des repertoires kodi (ou du moins les bases de donnes, plus facile sur linux), de refaire une install, et de tout reactiver un par un. Je vois moins d'addon dans ce log que le premier, je sais pas si tu as deja essaye ca ?

Mais la franchement je tape en touche. J'ai vu un peu de tout pour ce message d'erreur, y en a meme un qui l'a corrige en modifiant les reglages de sa carte graphique ... Donc bon, je pense que ca ira plus vite en repartant de zero.

Par contre sur rapsberry, j'espere que la procedure de desinstal fonctionne, car tu as des fichiers de partout.

**Comment by Kiri85** [comment]
Mon raspberry est vierge, j'ai réinstallé l'os Raspbian complet et j'ai 2 addons sur kodi.(dont vstream)
La base de données est donc vide mis à part login/pw Uptobox.
J'avais déjà eu le cas et une maj avait résolu mais c'était ya un moment.

**Comment by TmpName** [comment]
Et en installant la precedente version de Vstream mais le fichier LDD island actuel ?

**Comment by Kiri85** [comment]
A la limite je peux remettre celle d'avant pour tester mais fichier trop lourd à priori :
This file is too big to show. Sorry!

**Comment by stanler2659** [comment]
ohhh que je suis content d’avoir trouver ce site !! J’avais vstream sur mon laptop et j’utilisais ZT pour écouté film en HD et j’ai acheté ma Nvidia Shield hier pour installer vstream ! Quand j’ai vu que LLD , ZT et la plupart des site ne fonctionnais pas j’étais déçu :( mais de voir que le tout risque de rentrer dans l’ordre d’ici la fin de semaine je suis vraiment content j’espère que ce sera le cas ! 

Merci à l’équipe de garder vstream à jour et fonctionnel ! 
J’attend de vos nouvelle ici si jamais ya eu du changement !

**Comment by TmpName** [comment]
Le message d'erreur est normal, faut cliquer sur le boutton "download" apres, fichier environ 6Mega, tu peux meme choisir la version a installer.
Apres par contre tu risque d'avoir a remplacer le fichier DLL Siland a la main.

**Comment by stanler2659** [comment]
Je vais attendre la mise à jour sa va être moins compliqué comme ça :)

**Comment by Arias800** [comment]
@Kiri85 peut tu nous redonner des log avec le mode debug de Kodi activer ?

**Comment by Kiri85** [comment]
Https://slexy.org/view/s21VKL5nLa

**Comment by Arias800** [comment]
@TmpName ca pourrait être encore un problème lier a cette modif (https://github.com/Kodi-vStream/venom-xbmc-addons/commit/817236a2ad18710d85258e80ec2def23b02574c5) car j'ai l'impression qu'à chaque appel de la recherche il y a une erreur invalid handler

**Comment by Ovni-crea** [comment]
Bonsoir vous tous mais j'ai un problème il y a que moi qui fonctionne pas la recherche sur zt

PS:j'ai mis à jour le fichier de zt

**Comment by stanler2659** [comment]
@ovni-crew you have to wait til the next update this weekend !

**Comment by TmpName** [comment]
@Arias800 cette commande ne fait que reformatter du texte, et elle marche sans prb chez nous, je veux bien que android fonctionne bizarrement mais la sous UNIX c'est quand meme pas une commande extra ordinaire.
Et la recherche fonctionne, tu vois quelle passe plusieurs sites a la suite l'un de l'autre, c'est vraiment au moment d'afficher la page que ca part en sucette.
Et apparement ca deconne aussi, hors recherche.
Pour moi ca vient du systeme, vu la galere qu'il a pour charger de simples images. Apres c'est facile a tester, si une vielle version donne le meme message d'erreur ca vient pas de Vstream.

**Comment by Kiri85** [comment]
Je peux tester sans souci, avez vous un lien d'une plus vieille version ?

Merci

**Comment by TmpName** [comment]
Nope, une vielle version de Vstream, le lien que j'ai donne un peu plus tot (celui qui donne qui donne sur un message d'erreur et ou il faut DL le fichier)

**Comment by lelensois** [comment]
Ah voilà nous y sommes le week-end du 30 la maj va sortir

**Comment by stanler2659** [comment]
Yeahhh j’ai hâte de voir ça et que le tout fonctionne :) 

Juste comme ça je me demandais est ce qu’il existe une section 4K pour les film sur vstream ? Car sur free téléchargement leur site ya les film 4K aussi !!

**Comment by Arias800** [comment]
@Kiri85 j’utilise une ancienne version donc je vais te la passer ^^

**Comment by Arias800** [comment]
@Kiri85 essaye avec cette version (c'est ma version test donc les fichier dll island et zt sont mis a jour) https://drive.google.com/file/d/1jDl8-MRlnvy267llhrzMYImlBSGFKNN2/view?usp=sharing

**Comment by dark3hack** [comment]
Bonjour a tous, je comprend pas depuis quelque jour et malgré les mise à jour sur ma box xiaomi tv, plus aucun lien ne s'affiche sur toute les sources disponible aucun film aucun lien etc dernier ajout dernier ajout hd etc pourtant jai strictement rien toucher aurriez vous une idée ? merci

**Comment by stanler2659** [comment]
Est ce que la mise à jour automatique est prête ?

**Comment by TmpName** [comment]
Pareil je viens de tester beacoup mieux pour LDD island

**Comment by stanler2659** [comment]
Je vois la mise à jour 0.6.8 je l’ai fait et dans movie qualité HD je vois encore zone téléchargement au lieu de annuaire ... c’est tu normal ?

**Comment by Arias800** [comment]
Oui j'ai pas changer le nom du site c'est plus simple pour tout le monde ^^

**Comment by stanler2659** [comment]
@Arias800 bien si je click sur zone de téléchargement dans movie qualité HD il a rien ... sa m’écrit no information en rouge ...

**Comment by Arias800** [comment]
Je viens de rajouter les film 4k donc il ne sont pas passez a la maj ...
Zone telechargement fonctionne chez moi donc envoie les log ....

**Comment by stanler2659** [comment]
@Arias800 après un reboot de kodi ZT fonctionne bien mais free téléchargement fonctionne aussi mais je sais pas si c’est normal mais je dois cliquer plusieurs fois dessus pour qui fonctionne !! Une fois rendu dedans si tu veux aller à la prochaine page de film le next ... bien sa fonctionne pas sa marque working mais sa me change pas de page !! Peux tu vérifier svp et comme tu as dit la section 4K on ne l’a vois pas !!!

**Comment by Arias800** [comment]
Pour envoyer les log c'est dans les paramètre de Vstream dans Outil https://vstream.ga/docs/outils/

**Comment by stanler2659** [comment]
@arias800 d’accord mais bon sa fonctionne mais avec plusieurs tentative de click !! La seule chose qui me mmanque c’est la section 4K que j’aurais bien aimé avoir vu ma télé 4K de 75 pouce hehe est ce qu’il aurait possibilité qu’on puisse l’avoir ?

**Comment by Arias800** [comment]
Faut mettre a jour le fichier manuellement ou installer la beta mais zt en propose déjà . Par contre je viens de tomber sur un bug sur zt au niveau de la recherche . Par contre le bug du next c'est pas normal car je l'ai pas modifier

**Comment by stanler2659** [comment]
@Arias800 est ce que tu peux m’expliquer comment l’installer manuellement svp ? Si c’est pas trop compliquer merci ! Tu regardera si tu as le bug du next aussi !

**Comment by Arias800** [comment]
Il faut allez dans les dossier de Kodi (https://vstream.ga/docs/folder/) ensuite dans les fichier de vstream addons\plugin.video.vstream\resources\sites\ et remplacer free_telechargement_org.py par celui la
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/free_telechargement_org.py
Et non le bug du next je n'ai l'ai pas

**Comment by stanler2659** [comment]
@Arias800 Ohh sa semble compliqué sa se fait pas direct dans kodi sur la tv je dois plugger ma shield dans mon Mac ou ??

**Comment by Arias800** [comment]
Non ça ce fait pas via Kodi puisque dans manuellement il y a manuel donc a la main apres tu peux telecharger la beta via ce site https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream et l'installez comme un addon classique mais c'est les seul solution ^^

**Comment by stanler2659** [comment]
@Arias800 D’accord merci je n’ai jamais jouer avec ça manuellement ... je vais peut être regarder sur YouTube mais bon pk pas refaire la mise à jour automatique pour que se soit simple ?

**Comment by stanler2659** [comment]
Ok je vais regarder sur YouTube probablement merci à moins que quelqu’un peux me montrer une vidéo tuto qui me montre comment faire le tout !

**Comment by stanler2659** [comment]
Erreur connection failed 404 dans movie news zt si tu essaye un film sa marque erreur et rien n’affiche aucun lien !

**Comment by AngelineL** [comment]
Bonjour  . Même  chose  depuis  hier sur ddl fr "aucune information  " quand on clique .

**Comment by Arias800** [comment]
Je vais jeter un oeil a ddl fr . Pour installez la beta via le liens il suffit de ce connecter au liens via un navigateur internet et ensuite installez le beta via Kodi comme un addon classique

**Comment by TmpName** [comment]
Sinon, vous profitez des autres sources en attendant que les corrections arrivent en MAJ auto dans quelques jours, sans rien avoir a toucher.

**Comment by TmpName** [comment]
Pr LDD island, c'est normal, j'ai finalement trouve un lien qui deconne, evidement moi j'allais que dans les sections qui fonctionne, sHost = 'Revivelink' donc comme le test fait 
```
            oHoster = cHosterGui().checkHoster(sHost.lower())
            if (oHoster != False):
```
Ca bloque.
Si tu l'as pas deja fait essayes juste ca comme patch
```
if  sHost == 'Revivelink':
     oHoster = True
```

Sinon pour info, suffit d'aller voir dans les autres sections, les liens fonctionent.

**Comment by Fabiodirt** [comment]
Salut les gars ! 
C'est moi le newbie avec mes questions.
Malgré la mise à jour, je n'ai aucun films dans ZT. Comme cité plus haut j'ai "aucune information" écrit en rouge.
Faut-il que je vous envoie mes logs ou il me suffit d'attendre une prochaine mise à jour ?

Merci à vous et merci pour votre patience me concernant :)

**Comment by Arias800** [comment]
Je viens de corriger zt : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/e8e75c75b3675d00ac84ca4f6c4ffc46d602ee48

**Comment by Arias800** [comment]
@AngelineL dll fr proteger par recaptcha donc pas possible a corriger

**Comment by AngelineL** [comment]
D'accord merci a toi d'avoir regardé

**Comment by Kiri85** [comment]
Utilisation de la version test de Arias800.
Ok pour utilisation de ZT / ddl island.

**Comment by Fabiodirt** [comment]
Et encore un gros merci arias pour tes explications et ta patience !
Merci. On patiente

**Comment by Arias800** [comment]
Est ce que @Kiri85 tu a essayer d'installer la version 0.6.8 de Vstream ?

**Comment by TmpName** [comment]
Mon commentaire sur LDD island etait pour @Arias800 ^^.

**Comment by Arias800** [comment]
Tu a un exemple qui bug parce que moi je n'en trouve pas @TmpName ?

**Comment by stanler2659** [comment]
Je sais pas pour vous mais j’ai erreur 404 pour zt version 0.6.8

**Comment by stanler2659** [comment]
J’ai télécharger un browser pufin et quand j’ai télécharger la bêta je sais même pas où elle est rendu ....

**Comment by stanler2659** [comment]
@Arias800 jai finalement réussi à trouver comment installer les version bêta avec Google chrome browser :) est ce que la dernière version bêta c’est toujours le même lien de téléchargement que tu m’avais donné ? Ou sa change car si sa change j’aimerais savoir l’emplacement exacte pour toujours avoir la dernière version svp merci :)

**Comment by Kiri85** [comment]
Ça éviterait que les gens pourrissent mon post lol
Un tchat c'est l'idéal.

**Comment by Arias800** [comment]
Il y avais un Discord puis il a fermer et Discord pour le rapport de bug c'est encore pire que github x).
Bizarre pourtant j'ai bien lancer la modif il y a peut être un délai mais la je sais pas pourquoi tu vois la catégorie 4K

**Comment by stanler2659** [comment]
@Arias800 comme je t’avais demander est ce que toute les modifications que tu fais vont dans le même lien de téléchargement que tu ma donner ou le lien deviens différent ? 

Puis comme kiri dit un system de chat serait vraiment apprécié :) 

Quand je click sur free téléchargement je vois que les titre de film et non section 4K ...

**Comment by stanler2659** [comment]
@Arias800 j’ai créer un discord parfait pour nous tous ! Viens me rejoindre je te donnerai accès admin et tu pourras arranger le tout comme tu veux ! Il est super tout le monde est inviter :) 

https://discord.gg/S65HBXm

**Comment by TmpName** [comment]
@Arias800  Essayes avec le moit "grenouille" princesse et la grenouille.
