### ISSUE TITLE
Kodi 18

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2357]
Bonjour,

Kodi 18 est sortie en RC1 y a pas mal de changement dans les class xbmc.. (non il ont pas résolut leur soucis de surcharge de class XD), Quelques modifications dans le setting aussi mais rien qui plante l'addon ils ont était cool tous est rétroactif. même pas en plantage python 3 d’ailleurs j'ai pas compris sur certain de mes code python je suis obliger de bidouiller les imports pour que ça tourne et la non soit il l'on fait en amont soit c'est toujours du python 2.7 à voir.

Le soucis c'est de savoir si les modifs pour Kodi 18 vont faire planter sur Kodi 17 à les joie d'avoir une nouvelle version qui apporte rien mais qui change tout. Bref quand la team seras motiver je regarderais pour le moment mon libreELEC et toujours en Kodi 17.

**Comment by Arias800** [comment]
Pour le moment c'est python 2 qui prime sur python 3 donc pas de changement pour le moment sur Vstream j'attends les 1ere build Kodi 19 (donc en full python 3 ) pour m'en occuper  . Ensuite j'utilise Kodi 18 et pour le moment aucun probleme sur Windows ça tourne même mieux avec la version 64 bit (et le bug des liste a l'air d’être corriger donc le fix pourra peut être être virer si besoin ) ^^

**Comment by LordVenom** [comment]
Il ont foutue les 2 versions dans Kodi ? faut que je me renseigne c'est bizard ça, bon vStream en python 3 c'est pas si buguer j'ai fait des test en python 3 et PyQt5 a pars la partie request qui vas faire chauffer la tête le reste c'est easy.

**Comment by Arias800** [comment]
Oui voila deux extrait trouver sur les info officiel pour cette "RC1"

> Currently, Kodi includes the Python 2.7 interpreter to run add-ons written in Python programming language.

Et un peux plus loin : 

> Kodi 19 (M*) will be released with Python 3 interpreter for running Python-based add-ons.

Après la partie requête le truc pénible c'est urllib qui est séparer en 3 partie mais ca devrait allez vite vu que j'ai deja utiliser urllib 2 avec python 3 ^^

**Comment by LordVenom** [comment]
Perso je supprime les appelles a urllib.quote_plus par exemple pour juste quote_plus et en import

```
try:
    from urllib import quote_plus
except ImportError:
    from urllib.parse import quote_plus
```

**Comment by Arias800** [comment]
C'est pas mieux de faire quelque chose comme ca : 
```
if sys.version_info >= (3, 0):
   from urllib.parse import quote_plus
else:
    from urllib import quote_plus
```

**Comment by LordVenom** [comment]
Surement mais la tu importe aussi sys et j'ai une psychose avec les import depuis l'histoire de comaddon.py de vstream.

**Comment by Arias800** [comment]
Oui c'est sur que sans import il n'y a pas 36 solution ^^

**Comment by lebigboss** [comment]
Python 2 & 3 compatibility will be enforced

Currently, Kodi includes the Python 2.7 interpreter to run add-ons written in Python programming language. However, Python 3 was released almost 10 years ago and the matter of implementing the Python 3 interpreter in Kodi has been brought up on the Kodi forum several times. Now, thanks to a successful GSOC 2017 project, we have a working Python 3.6 interpreter for Kodi, and on the latest DevCon 2017 in Prague Team Kodi decided that it’s time to move on and migrate Python add-on subsystem to Python 3. <--break->There are several reasons for that:

    Python 2 End of Life is planned for 2020.

    Python 3 is mature enough and more and more Python libraries either convert their codebase to Python 3-compatible or drop Python 2 support completely (Django is the most notable example).

    Most current Python books, tutorials and courses are focused on Python 3.

    Python 2 is not actively developed. It receives only security patches while Python 3 gets all the cool new features with every minor version.

However, Python 3 is not backward-compatible with the 2nd version so some transition process is required. Currently the plan is the following:

    Kodi 19 (M*) will be released with Python 3 interpreter for running Python-based add-ons.

    After the release of Kodi 18 (Leia) only add-ons that are compatible with both Python 2 and 3 will be accepted to the official add-on repository. Also, Python 3-only add-ons will be accepted to the repositories for Kodi 19 (M*) and above.

    Add-on developers are highly encouraged to convert their add-ons to Python 2/3-compatible so that after the release of Kodi 19 (M*) we will have enough add-ons that work with the new version.

    Test builds based on Kodi 18 with the Python 3 interpreter will be provided continuously so add-on developers can test their add-ons for compatibility with Python 3. Test builds for Windows are already available for downloading from here and test builds for Ubuntu can be obtained from this PPA.

    One the v18 version has been branched off for final release the nightlies will become Python 3 only while the release builds will still be Python 2.

Writing Python code that is compatible with both 2 and 3 versions is totally possible and the “big” Python world has been doing it for years since the release of Python 3.0. There are a number of tools and best practices developed to simplify this process. Please read this Kodi Wiki article for more information and technical details about the migration process. Also a special Wiki section has been created that will be updated with new information. You can post questions about converting your add-on code to Python 3-compatible or share your experience in “Python 3 migration” subforum on the official Kodi forum.

https://kodi.tv/article/kodi-v18-leia-rc1-new-hope

**Comment by TmpName** [comment]
Lol, merci ^^

**Comment by Arias800** [comment]
Alors j'ai l'impression que kodi 18 gèrent nativement  les redirections car extrême download sans changer l'URL fonctionne chez moi et j'ai vu un pull request qui correspondrai a ça ^^

**Comment by johngf** [comment]
rien a voir mais certains commit parfois passe au travers de la maj comme pour moi strea may qui na pas été mis a jours
c'est pas la premiere fois que ça arrive sur deux pc different

**Comment by LordVenom** [comment]
Faudrais trouver le pourquoi du comment le github lui envoyer la liste des fichiers présent dans le commit
 si je regarde la dernier version envoyer que je la compare a la beta y a plus rien normal.
https://github.com/Kodi-vStream/venom-xbmc-addons/compare/0.6.83...Beta

si je la compare a la version 0.6.82
https://github.com/Kodi-vStream/venom-xbmc-addons/compare/0.6.82...0.6.83

y a  bien mais 18 commit.

**Comment by TmpName** [comment]
Pareil deja eu le soucis, mais c'est pas mechant donc j'ai pas reflechit, peu etre le temps que tout les serveurs github se sychronise ?

**Comment by victore447** [comment]
Bonjour,la librairie ne s'ouvre pas  avec kodi 18.1leia quand on clique dessus après avoir ajouté des films,series.Par contre  fonctionne avec les anciennes version de kodi.
Quelqu'un à trouvé une solution?

**Comment by TmpName** [comment]
Nope, dsl, le prb a deja été signalé, mais on a pas encore trop bouge de notre cote.
Perso moi j'ai meme pas pu installer kodi 18 encore (crash), je me dis qu'il vont corriger leur bouzins avant de savoir si ca va etre a nous de refaire le code ou pas. Pour moi c'est encore une Beta.

**Comment by Arias800** [comment]
J'ai jeter un oeil avec la 18.1 ça na toujours pas été corriger alors que c'est clairement un probleme de leurs fonction donc a mon avis cette partit est a refaire ^^

**Comment by Arias800** [comment]
Bon j'ai commencer a réécrire la partie qui ne marche pas de la librairie : https://pastebin.com/raw/tw18JbFf
Pour le moment le nom des fichiers sert de titre et les liens pour une raison inconnu ne s'ouvre pas  ^^

**Comment by TmpName** [comment]
Ha oui, ils ont sortis la 18.1, demain je re-essaye de l'installer.

**Comment by TmpName** [comment]
Bon alors j'ai finallement pu passer a kodi 18, et me faire chier pour recuperer ma TV vu que l'addon iptv simple avait disparu.

Donc j'ai pu tester ton code, le prb ne vient pas du fichier strm, car j'ai pu le lancer dans kodi sans probleme. Donc si kodi peut le lancer nativement, j'ai voulu utiliser le lecteur de vstream pour lire le fichier comme un fichier normal (j'ai recup le code qui lit les Bande annonce)

CRASH

Serieux c'est un gag cette version, j'en suis au 3 eme crash la, je jette l'eponge.

Premier concurrent a kodi, je le prend direct.

**Comment by victore447** [comment]
Bonjour Aris800,
Si vous faite actuellement la partie écrite qui ne marche pas dans la librairie de vstream ( https://pastebin.com/raw/tw18JbFf );Exodus est bien fait sur ce point pour l'intégration de la bibliothèque dans le menu d'accueil de n'importe quel skin..Voir exemple sur ce lien https://koditips.com/covenant-library-kodi-setup-integration/ 

Victor.e447

**Comment by Arias800** [comment]
Alors j'ai jeter un œil au code de cette addon mais j'ai rien vu d'intéressement mais je garde ça de coter au cas où merci .
Ensuite j'ai avancer sur mon code malgré que je n'ai pas mis a jour le code du coter de github puisque maintenant j'arrive à lire les strm ^^

**Comment by Gziin** [comment]
Bonjour,
Je viens l'extension Vstream sur Kodi 18.1 mais elle n'apparaît pas dans mes extensions.
Quelqu'un sait d'où ça peut venir ?
Je suis bien passé par le repository.
Merci beaucoup d'avance.

**Comment by TmpName** [comment]
Hello, le repository apparait dans kodi ?
