### ISSUE TITLE
api uptobox

### ISSUE THREAD

**Issue by moviefangithub** [Kodi-vStream/venom-xbmc-addons#2358]
à ce que je vois pour uptobox vous utilisez pas l'api https://docs.uptobox.com/, il y a une raison particulière?
merci!

**Comment by johngf** [comment]
et tu vois ça ou ? on utilise l'url de l'api pour le fichier site [ligne 20](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/siteuptobox.py#L20)
