### ISSUE TITLE
My free tivi identification 

### ISSUE THREAD

**Issue by piro8413** [Kodi-vStream/venom-xbmc-addons#2360]
Salut à tous, merci pour le boulot que vous faites sur vstream.
Sur my free tivi, est-ce possible de s’identifier ? 
Merci d’avance pour votre réponse.

**Comment by Arias800** [comment]
C'est pas encore possible mais c'est prévu je pense ajouter cette possibilités en même temps que la mise a jour pour ça https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2303

**Comment by piro8413** [comment]
Super cool, encore merci pour ce que vous faites 🙏🏼 Vous êtes au top 👌🏼

**Comment by Arias800** [comment]
Bon j'ai une mauvaise nouvelle la connexion au compte pour my free tivi ne va pas être possible a ajouter a cause de Recaptcha ^^

**Comment by piro8413** [comment]
A dommage c’est comme ça 🤙🏼
