### ISSUE TITLE
Aucun film sur toute les source. 

### ISSUE THREAD

**Issue by dark3hack** [Kodi-vStream/venom-xbmc-addons#2364]
Bonjour à tous, depuis quelques jours malgré les mises à jour effectuer et aucune modification de ma part, j'ai plus aucun film qui s'affiche lors du scan d'une source que ce soit en recherche manuelle ou dernière ajout ou ajout hd, cependant cela fonctionne avec les séries.
Auriez-vous une idée ? 
je suis sous xiaomi box TV, dernière version de Kodi et stream.
Merci pour votre aide. 

https://slexy.org/view/s2H9fiU7dz

**Comment by TmpName** [comment]
Tu as fais les tests sur une seule source, c'est la seule qui deconne ?
LDD island en cours de reparation.

**Comment by dark3hack** [comment]
Merci pour ton aide, une erreur de ma part toute bête panneau de gauche, films vue etc
