### ISSUE TITLE
REPLAY TV OUT

### ISSUE THREAD

**Issue by higuelzim** [Kodi-vStream/venom-xbmc-addons#2365]
Bonsoir,

Cela fait un bon moment que le replay tv n'est plus opérationnel sur Vstream (aucune information lors de l'accès), je pensais que cela serait réparer avec les moultes mises à jour qui se sont suivies (BRAVO encore pour le travail des développeur) mais non visiblement.

Pouvez vous y jeter un coup d'oeil? et le remettre en marche car très pratique en cas de rediffusion.

Par avance merci et bon courage pour la suite !!!!

**Comment by TmpName** [comment]
Alors je suis allé dans TV replay / dernier ajout / buzzmonclk / 1er lien , fct ok
Plus d'infos ?
