### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2367]
Pour ceux qui sont intéresser @stanler2659 a ouverts un Discord pour Vstream . Message original (j'ai juste couper les info inutile pour cette issue :

>  J’ai créer un discord parfait pour nous tous ! Il est super tout le monde est inviter le lien d’invitation n’expire pas ! :)
> 
> https://discord.gg/S65HBXm

**Comment by stanler2659** [comment]
Merci @Arias800 je t’attend pour te donner les droit d’admin ! Pour rajouter ce qui manque et faire un intro rajouter les lien utiles etc !

**Comment by Arias800** [comment]
Je suis déjà la ^^

**Comment by Arias800** [comment]
@LordVenom peut tu ajouter cette URL dans les réglage du github 
pour ajouter le webhooks sur le serveur discord ? https://discordapp.com/api/webhooks/519567714487107595/zNcNRnzyy-AaVdJhUBdGVV8AGA_EpKb9rvlXh2TlPKNXr3vRQXlN901XRiQ9ONGQ22gH

**Comment by LordVenom** [comment]
Fait

**Comment by Arias800** [comment]
Merci

**Comment by stanler2659** [comment]
@ludopotte merci :)

**Comment by ludopotte** [comment]
Mon Patch vStream est maintenant disponible sur le Discord Officiel de vStream au https://discord.gg/S65HBXm ou au https://discordapp.com/channels/519198717463625764/699136870709461003

**Comment by LordVenom** [comment]
C'est toujours bon et y a du monde mais pour info c'est qui l'admin de ce discord ? si les admins du github non aucune droit sur le discord ça dégage direct.

**Comment by sizanic** [comment]
Le lien du Discord est maintenant en page d'acceuil du github.
