### ISSUE TITLE
Dialog info

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2368]
![image](https://user-images.githubusercontent.com/4380112/49459501-795a3700-f7ef-11e8-93d5-92a173762a1d.png)

**Comment by TmpName** [comment]
Par contre c'est propre a Vstream ou theme dependant ?

**Comment by LordVenom** [comment]
Comme dab propre a vstream faut surement fixe les polices juste peux être jamais fait gaffe.

**Comment by TmpName** [comment]
Moi j'aime bien, peut etre agrandir la fentre avec les infos, elle ne fait que 25% de l'image.

**Comment by LordVenom** [comment]
Par la suite tu pourras agrandir le synopsys pour le lire entièrement et bien XD

**Comment by johngf** [comment]
sur kodi 16.1 ont ne voit rien a cause du fanart il n'y a pas en bas une bordure noire et le dialog ne s'ouvre pas sur le synopsis qui est a droite tout petit

**Comment by johngf** [comment]
comment faire pour afficher le résumé directement sans cliqué comme avant ? les autres infos ne m'intéresse pas vraiment
![screenshot001](https://user-images.githubusercontent.com/21311232/51487450-9e0c6d00-1da3-11e9-9c8c-e93a83e9d09f.png)

**Comment by TmpName** [comment]
J'ai pas trouve non plus, et comme j'avais pas envie de me prendre la tete j'ai juste remis

`wd = XMLDialog('DialogInfo.xml', path , 'default', '720p')`

C'est une vielle version mais y a le resume sur 20% de l'ecran au moins.

**Comment by TmpName** [comment]
Moi pareil, rajoutes self.setFocusId(36) dans la partie init, ca va afficher le resume direct, et tant que tu touches pas a la telecommande ca restera.

Si ca te va comme bidouille, on peut la passer en off, sauf si quelqu'un prefere les infos.

**Comment by johngf** [comment]
ça fonctionne je vais mettre une option dans settings pour afficher le synopsis par défaut

**Comment by johngf** [comment]
je l'ai modif maintenant il affiche direct le synopsis

**Comment by johngf** [comment]
rien a voir mais tu as deja eu affaire avec un token type bearer jwt >json token
dans le header j'ai besoin de 
authorization Bearer GvXtznl/cBypzEEJl57O2nV6r8/BYN9WLoZF2vmkekEZLSV+21mSS4RX7n+jKrWJyH0eWqzxpF8H/7sRO23CY42qBhSvQwVNSrkwR0MhrQl6JLNP4M3wt872saytC05lEZ0Ew+Ew7lss0qQ3csbq8NqNnveSRx8Hu0HeLb/WFjw=' 
mais je le trouve pas sur le site ni dans les js ,code html ou header et si il est encodé ce que je pense pas trouvé le code pour le décodé

**Comment by TmpName** [comment]
C'est quoi le site pour tester ? C'est vraiment indispensable ?
En fait le token a renvoyer est normalement transmit en clair, dans un simple JSON.
Y a pas un lien ou tu t'authentifi ? en POST ? et c'est lui qui te renverrait le token.

Rien a voir avec ce que je connais, mais comme tu parlais de JWT > https://jwt.io/introduction/

**Comment by johngf** [comment]
je connais le site je suis arrivé la j'ai testé mais le token n'est pas commun du coup je cherche

**Comment by TmpName** [comment]
Et c'est quoi le site ou tu cherches le token ?

**Comment by johngf** [comment]
va sur adkami fairy tail 291 c'est sur  la redirection adn 
j'arrive a play la video mais il faut le token pour avoir les liens finaux

**Comment by Arias800** [comment]
Adn est un hébergeur légal donc c'est pas une bonne idée d'essayer de l'ajouter a Vstream ^^

**Comment by johngf** [comment]
pourquoi you tube est legal et on play sur vstream je vois pas le soucis on play que les video gratuite

**Comment by Arias800** [comment]
ADN ne propose que certaine vidéo gratuite tout les reste du catalogue est payant . C'est comme si tu ajoute Netflix a Vstream . up tobox 1 fichier ne sont absolument pas légal puisque pour qu'un service comme ça soit légal il doit avoir les droits du contenu qu'il propose chose qui n'est pas le cas pour up tobox 1 fichier . Mais adn eux contactent les ayant droits japonais et négocier la diffusion en achetant les droit ^^

**Comment by johngf** [comment]
bah il y a deja un plugin net flix perso je play que que les video free (voir pour ceux qui ont un compte on verra posiible de s'auth) sur vstream au lieu d'aller sur le site

**Comment by Arias800** [comment]
Mais l'addon Netflix a eu des probleme car Netflix n'a pas approuver la création de l'addon donc c'est pas un bonne exemple de prendre exemple sur lui (tout comme l'addon de Crunchyroll d'ailleurs). Ensuite les vidéo qui sont gratuite affiche des publicité pendants la lecture puisque cette argent sert a au site (acquisition de nouvelle licence , hébergement) et au ayant droits japonais. Ensuite Vstream ne sert a pas a détourner les protection mise en œuvre par les ayants droits (c'est d’ailleurs pour ça qu'aux yeux de la Hadopi nous somme dans la légalité)

**Comment by johngf** [comment]
les utilisateurs de vstream sont (légal) uniquement parce que tu stream les vidéos tous ceux qui vont sur ZT et qui dl sur upto box ou 1 fichier non hein ^^

**Comment by Arias800** [comment]
Du point de vue de la Hadopi l'addon est dans les légalité car "Ces extensions ne sont donc pas destinées à contourner directement des mesures techniques de protection afin d’accéder illégalement à des plateformes de vidéo à la demande licites ou à des flux télévisés originaux " . Et la différence entre les site comme adn et tout le reste des hébergeur disponible sur Vstream c'est que l'on passe nous même les protection mise en place par les ayants-droits.

**Comment by johngf** [comment]
pour firefox j'ai gardé les deux version 54 en install et 64 en version portable

**Comment by johngf** [comment]
@TmpName ça fonctionne avec le plugin pour kodi youtube dl [ici](https://github.com/ruuk/script.module.youtube.dl)

**Comment by TmpName** [comment]
Ya le code ici github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/adn.py

**Comment by johngf** [comment]
le code ne fonctionne plus pour l'instant tu as la video mais pas les sous titres j'ai regardé le code js mais je trouve pas le pourquoi du comment :)

avec une bidouille 'recup le bearer de firefox' j'arrive a avoir les sous titres mais que pour le 360p pas le 480p
pourtant les deux urls sont données en meme temps

**Comment by TmpName** [comment]
J'ai vu un truc sur le forum, en fait il faut decoder les sous titres, et le code est un code JS dynamique (comme celui de openload), mais apparement c'est plus galere que ca en l'air.

Par contre j'ai pas compris, toi tu arrives a avoir les sous titres sous kodi avec le beaver de firefox ?
Donc ce serait leur beaver le prb ?

**Comment by johngf** [comment]
non les sub sont automatiquement dispo sur la qualité "mobile" c'est pour ça 
la le soucis c'est la clef a changé je pense [ligne](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/adn.py#L59) du coup le décodage plante (ils sont au courant mais personne ce bouge) et je la trouve pas

**Comment by TmpName** [comment]
Bon j'ai commence mais y a du taff.
Le code a l'air de changer souvent, donc faut vraiment le reperer efficacement, leur regex ne marche deja plus.
Pour le reperer efficacement je pense qu'on a pas le choix, faut nettoyer.
Du coup j'ai commence avec ca
https://pastebin.com/pY2V5cMr
En python3

Par contre, mon  sHtmlContent.decode('unicode_escape') est un peu trop bourrin, ca me provoque des bugs a niveaux des " et ', et du coup j'ai des erreurs de syntaxe quand je repasse le code a JSnice.

**Comment by TmpName** [comment]
Une version qui fonctionne > https://pastebin.com/DqWY1GjV
Ca nettoye le code qui passe ensuite dans jsnice.

Par contre
1 - je suspecte un decallage dans le tableau, ce qui fait que mes remplacement ne sont pas bon
2 - J'ai pas trouve la partie gerant les sous titre encore .

**Comment by johngf** [comment]
j'en suis au meme point que toi sauf que le fichier sub est encodé on le récup via une url et on doit le décodé avec la clef fichier hoster [ici](https://github.com/johngf/test/blob/master/adn.py)

**Comment by TmpName** [comment]
Avec mon code j'arrive a la cle : 094831fababd5e58

```
    var _0xc819f2;
    var self = [_0xc819f2 = 22940, _0xc819f2 = _0xc819f2 + 55390, _0xc819f2 = _0xc819f2 + 48153, _0xc819f2 = _0xc819f2 + -25131];
    self[2] = self[3] ^ self[1];
    self[3] = self[0] * self[1];
    var content = 1;
    for (; content < 19; content++) {
      self[2] += content;
    }
    self[0] = 101709 * self[0] % (2 << 16);
    self[0] = 121942 * self[0] % (2 << 16);
        window.alert(self.map(function(_0xc819f2) {
            return ("0000" + _0xc819f2.toString(16)).substr(-4)
        }).join(""))
```

Si ca change a chaque video, faut qu'on se mette d'accord pour chercher sur la meme.

Pour lol4 tu le recuperes via navigateur, ou tu as deja un code python ?

**Comment by johngf** [comment]
oui bonne url les sub sont dans le sHmlcontent4 sur le fichier hoster

**Comment by johngf** [comment]
ah non je me suis gouré de code j'ai ça en faite return ("5820" + intval["toString"](16))[_0x5b81("0xff")](-4);

**Comment by TmpName** [comment]
Bon j'ai du mieux, j'arrive a extraire le code, et le rendre compatible
https://pastebin.com/VM5vTShY

Par contre jsparser ne gere pas la commande "map", donc soit faut adapter soit ameliorer la lib.

**Comment by johngf** [comment]
c'est du python 3 ? chr() arg not in range(256)

**Comment by TmpName** [comment]
Oui j'ai misere avec les version de python ca marche pas du tout pareil.
Du coup j'ai refait le code pour python2 et ca fonctionne, ca donne le code (j'ai mit a jour le parser sur mon github)
https://pastebin.com/qZ6UEyaT

**Comment by johngf** [comment]
la c'est ok sur kodi reste a test le decode des sub

**Comment by TmpName** [comment]
https://pastebin.com/96i5PQRG
Fichier hosters, bon y a pas de message d'erreur, mais ca marche pas.

Et y a encore un soucis avec le JSparser il rajoute un "L" a certain moment dans les variables, du coup dans certains cas le code n'est plus bon, suis desssus la, ce sera vite corrige.

**Comment by johngf** [comment]
fonctionne pas chez moi pour l'instant par contre il faut laisser la premiere requete indispensable il faut l'url avec le titre complet sinon rien ne fonctionne
sur ad kami les url sont des embeded >> redirection

**Comment by TmpName** [comment]
Et si je dis pas de connerie, on peut se servir du fichier GKDecrypter.py pour ne pas avoir a refaire le code de decryptage aes.

**Comment by johngf** [comment]
la je test enregistrer les sub au format srt

**Comment by TmpName** [comment]
Non, je pense pas, j'ai reverifié mais j'ai vu que 2 modes, fichier local et fichier distant.

**Comment by johngf** [comment]
la je suis au moment de donner le path du fichier sub

**Comment by johngf** [comment]
https://pastebin.com/raw/4wpgQWuv

**Comment by TmpName** [comment]
Lol, y a du lourd, ..., pour un hebergeur qui ne va pas souvent etre solicité ^^.
Par contre, tu as teste a utiliser le code de GKDecrypter.py ? c'est exactement le meme code, c'est un decodeur AES RSA, ca ferait un code plus leger.

**Comment by johngf** [comment]
je m'y prend peut etre mal mais pourquoi le [param 3](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/GKDecrypter.py#L30) n'est pas utilisé ?

**Comment by TmpName** [comment]
Ha tiens j'avais jamais fait gaffe, effectivement ca sert a rien.
Faut dire que ce code la a ete genere a partir du code flash, y aussi une lib python qui fait ca, mais elle doit faire plus d'un seul fichier, c'est pour ca que celle la est bien.

Pour le prb du code , suis dessus la.

**Comment by johngf** [comment]
un coup de regex et cest bon

**Comment by TmpName** [comment]
Du coup c'est bon ? Tu as deja trouvé ?
Car moi j'ai un autre bug

Traceback (most recent call last):
  File "G:\Python\adndecode\adndecode.py", line 106, in <module>
    print ("\ncode : " + JScode + '\n')
  File "F:\Application\Python2\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0435' in position
 432: character maps to <undefined>

**Comment by johngf** [comment]
moi le code date de ce matin pas eu ce soucis je testerai apres midi

**Comment by TmpName** [comment]
Moi j'ai corrige avec juste

```
end = r.end()
start = end
while sHtmlContent[start:start + 7] != 'for(var':
    start -=1
JScode = sHtmlContent[start + 0:end - 1]
```

Le regex fonctionne pour localiser le code, mais c'est quand je remontre pour trouver le debut du code ou ca deconne.
Mais ca risque de prendre du temps pour trouver LA methode qui marchera dans tout les coups.

**Comment by johngf** [comment]
ah moi j'ai enlever ça [ici](https://pastebin.com/admWSFEa) je testerai demain si le code change encore

**Comment by johngf** [comment]
ça plante au 1 processing tu peux expliquer ce que tu cherche au premier et au deuxieme processing

**Comment by TmpName** [comment]
Alors :
- 1 er processing : Recuperer le nom de la variable et le tableau (son contenu) tout en haut de la page.
- Fabriquation du tableau avec les valeurs decodées.
- Recuperation de la valeur du decalage du tableau, et decalage du tableau
- 2 eme processing : 
On remplace les variables, par leur valeur relle venant du tableau.

La moi je viens de tester, pas vu de soucis, le code JS est bien extrait. Mais pas assez haut, il me manque une partie du code.

```
var _0x592340 = 0;
for (; _0x592340 < 13; _0x592340++) {
  _0x5aeb84[2] += _0x592340;
}
_0x5aeb84[2] = _0x5aeb84[2] ^ _0x5aeb84[3], _0x5aeb84[1] = _0x5aeb84[3] ^ _0x5aeb84[0], _0x5aeb84[3] = _0x5aeb84[1] ^ _0x5aeb84[2], code = _0x5aeb84["map"](function(intval) {
  return ("9765" + intval["toString"](16))["substr"](-4);
})["join"]("");
```

Il me manque le contenu de la variable  _0x5aeb84[2], ca doit etre les lignes precedente, vu que now je coupe plus bas avec 'for(var'
Faut repartir avec le precedent code.

**Comment by TmpName** [comment]
Bon ben 3 jours apres, le code fonctionne encore.
Il font une rotation de 24h et je tombe tjours sur le meme (vu que je teste tjours a la meme heure) ?

**Comment by johngf** [comment]
oui une journée ça n'a plus fonctionné mais depuis c'est ok
