### ISSUE TITLE
Problème de recherche

### ISSUE THREAD

**Issue by lefou66** [Kodi-vStream/venom-xbmc-addons#2369]
Bonjour, les recherches ne trouve pas grand chose...par exemple, j'ai lancé une recherche pour la série the haunting of hill house mais seulement 2 sources avec des résultats donc je suis allé parcourir une source par moi même (série streaminghd ) pour la trouver.Bug?
boite android  Tx 95
kodi 17.6
vstream à jour

**Comment by Arias800** [comment]
Il faudrait les log (dans les parametre de Vstream -> Outil -> Upload log )et pense a reproduire le bug avant de nous envoyer les log

**Comment by johngf** [comment]
quand tu recherche n'ecrit pas le nom entier si il est trop grand je l'ai vue cette série sur plusieurs site tape juste >> haunting

**Comment by lefou66** [comment]
ok je regarderai pour les log...et je sais pour la recherche....je les trouvé mais seulement 2-3 sources qui me le sort...et il est est dispo dans plusieurs

**Comment by TmpName** [comment]
Un exemple de site qui ne donne rien en recherche et ou la serie est presente ?

**Comment by lefou66** [comment]
voici les log...j'ai reproduit la recherche de haunting hill house..disponible dans la source série streaminghd  mais pas en recherche...https://sexy.org/view/s24VGvfnMe

**Comment by TmpName** [comment]
Par contre desactiver les log par defaut, suis pas sur que ce soit une bne idee.
Dsl pour le log, mais pas de chance, ils sont desactives sur ta machine, mais c'est pas grave, je viens de tester sur le meme site, et ta serie y est, uniquement des liens OPNLAD mais fonctionnels.

**Comment by lefou66** [comment]
Bizarre..je les actives comment ?

**Comment by johngf** [comment]
@lefou66 ta serie est sur streamzz 
donc menu principal en bas sources ensuite stream zzz >>>recherche>>> haunting et hop vendu!

**Comment by lefou66** [comment]
Ok...je voulais juste savoir pourquoi elle ne sortait pas en recherche...mais seulement en recherche manuel

**Comment by TmpName** [comment]
Je viens de faire une recherche globale.
Elle sort sur Serie-Streaming-hd, en fait je la vois en tout sur 8/9 sources, en retirant les site de dl. Utilises juste un mot pour la recherche
