### ISSUE TITLE
ZT2.org ce revendique comme Officiel 

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2371]
Apparemment le site ZT est de retour, c'est ce que dit le site comment ça marche

Sur comment ça marche ils disent que c'est l'équipe officiel du site qui revient après 2 ans d'absence

**Comment by Arias800** [comment]
Alors avant d'avoir 50 poste différent oui l'équipe original serai de retour a ce liens la : ht tps://www.zonetelechargement.site/homep.html
Mais aucun preuve concret pour prouver l'identité des personnes derrière ce site donc prudence ^^

**Comment by lebigboss** [comment]
@Arias800  Okk c'est cool, ça reste à voir
Mais j'ai vue qu'il y avait un compte a rebour sur les liens avec DL-Protect, ça fonctionnerai sur vstream ?

Je vais surveiller ce site de prêt

**Comment by Arias800** [comment]
A voir comment ça fonctionne mais logiquement oui

**Comment by lebigboss** [comment]
@Arias800 Okk mais c'est quand même bizarre que ce site là à plus l'air d'être une copie de annuaire telechargement plutôt que du ZT original.
Par exemple la série "Escape at Dannemora" est pas dispo dessus en HD et il y a pas de section 4k.
Mais bon c'est peut être le début

**Comment by Vidalcris** [comment]
Si ca fait une source de plus pour uptob*x et 1f*chier c'est plutot cool :)
Et puis sans mot de passe surtout XD
Apres je suis assez d'accord ... ils sont en retards par rapport a Annuaire-T.. donc ca ressemble plus à un clone qu'a un original..

**Comment by isandard** [comment]
d'un autre coté, ils ont une "historique" superieure et le skin ressemble bien plus au zt avant sa fermeture avec les articles sur 30 jours, les notions de saisons en cours et ainsi de suite.....
