### ISSUE TITLE
Live tv

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2374]
Bonsoir 
J'ai aperçu sur l'addon sportdevil, le site firs_on_tv avec les chaines tv incluses classées par pays (page de démarrage du site avec tous les drapeaux des pays)
Je n'arrive pas à avoir cette liste sur vstream jtombe directe sur les listes de chaines francaises, comment faire pour avoir les autres directement
![screenshot_20181208-161547_kodi](https://user-images.githubusercontent.com/44464129/49687615-d0208300-fb05-11e8-88bc-c262ccbddaba.jpg)
![screenshot_20181208-161529_kodi](https://user-images.githubusercontent.com/44464129/49687619-dd3d7200-fb05-11e8-9fd2-cdb39660cc40.jpg)

 sur Vstream?
Bien sur en espérant que cela soit possible

Merci

**Comment by Arias800** [comment]
Alors je n'ai juste pas mis la liste des chaine des autre pays pour plusieurs raison : 
-La 1ere tous simplement un manque de place car pour le moment tout ce qui concerne l'iptv est stocker dans un seul et même fichier 
-Ensuite pour tout simplement éviter le plus possible d’être repérer par l'administrateur du site 
Donc pour le moment je n'ai pas prévu de mettre les autre pays mais ca ne va jamais arriver ^^

**Comment by kenshiro000** [comment]
Addon videodevil ?!?! Il y a de l’iptv là déçu ? 👫👭😅
C’est pas plutôt de l’addon sportdevil que tu veux parler 😁.

**Comment by Che-debarras** [comment]
@Arias800

Ok je comprend bien, en plus ça explique certaine chose puisque c'est vrai que sur sportdevil  les chaines ne marchent pas donc sans doute du a cette surveillance que tu parles. Donc effectivement faut mieux pas.  Merci pour ta reponse

**Comment by Arias800** [comment]
J'ai surtout l'impression que SportDevil est abandonner ^^

**Comment by Ovni-crea** [comment]
@Arias800 il faut faire attention avec sportdevil il y a tellement de version avec des développeur différents que tu sais même plus l'officielle

**Comment by Che-debarras** [comment]
C'est lequel l'officiel ?

**Comment by Ovni-crea** [comment]
@Che-debarras bah honnêtement je sais pas

**Comment by LordVenom** [comment]
Pour rebondir sur ce que demande @Che-debarras  perso vStream c'est toujours limiter au source francophone le reste bof bof.

**Comment by Nux007** [comment]
@TmpName je suis Breton, donc tout va bien ^^

**Comment by TmpName** [comment]
Put1 j 'aurais voulu le faire expres, j y serais pas arrive, je voulais dire les corses bien sur ....

**Comment by Nux007** [comment]
@TmpName t'inquiète, je le vis bien , enfin je crois, et puis je n'y vis plus depuis un bon moment ^^

**Comment by LordVenom** [comment]
ben... oui marre de la pluie XD

**Comment by Nux007** [comment]
mdrrrrr

**Comment by Arias800** [comment]
C'est le lecteur multimédia qui s'occupe de ça tous seul ^^

**Comment by Nux007** [comment]
C'est ce que je pensais, mais kodi n'a pas l'air de trop aimer ca ... ( entre parenthèses, unfucker m'a bien fait rigoler :p )

**Comment by Arias800** [comment]
Ah ah c'est pas de ma faute c'est le nom du code base ^^
Pour Kodi c'est inputstream.adaptive qui gèrent ^^
