### ISSUE TITLE
Débrideur Tout-Debrid ?

### ISSUE THREAD

**Issue by anys357** [Kodi-vStream/venom-xbmc-addons#2375]
Bonjour à toutes l'équipe de vStream, merci pour votre addons qui est génial.
Serait il possible d'ajouter le débrideur tout-debrid.ch ? 
Il est l'une des meilleur solution pour télécharger des fichier avec un rapport qualité/prix imbattable (j'ai eu mon compte pour 10€ à vie)

**Comment by TmpName** [comment]
Ben jusqu'a present on ne fait pas les debrideurs.

**Comment by lebigboss** [comment]
C'est Urlresolver qui gère ça, regarde plutôt sur l'addon

**Comment by Ovni-crea** [comment]
@lebigboss urlresolver ne le fait pas enfin je crois
