### ISSUE TITLE
Zone-Telechargement ne Fonctionne plus !

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#2377]
La Source "Zone-Telechargement" avec le Site Annuaire Telechargement ne fonctionne plus. Ça marque "Aucune Information" et pourtant le Site fonctionne sur Internet. Comment résoudre ce problème ?

**Comment by stanler2659** [comment]
@Arias800 vas regarder ca demain :)

**Comment by AngelineL** [comment]
Ça refonctionne actuellement non?

**Comment by stanler2659** [comment]
Version bêta fonctionne plus mais la version officiel fonctionne apparement

**Comment by AngelineL** [comment]
Ok car chez moi ça  fonctionnait plus de la journée ( erreur en rouge ) mais là ça remarche

**Comment by stanler2659** [comment]
Est ce que tu as la version bêta ou officiel ?

**Comment by AngelineL** [comment]
Officiel là

**Comment by stanler2659** [comment]
Voila la officiel fonctionne comme je disais plus haut mais la bêta fonctionne plus ...

**Comment by Arias800** [comment]
Site instable pour changer : http://www.fredzone.org/annuaire-telechargement-ex-zone-telechargement-enchaine-les-pannes-887/amp

**Comment by stanler2659** [comment]
le site fonctionne bien pour ma part ... et dans vstream aussi tout est correct maintenant !

**Comment by Arias800** [comment]
Enfaite avant la beta je forcais le HTTP (donc pas de ssl) hors dans l'article c'est écrit que le site a des erreurs ssl voilà pourquoi ça marchais sur la version avant et pas sur la beta  ^^

**Comment by ludopotte** [comment]
Ok Arias800 mais maintenant Zone-Telechargement marche ou pas dans vStream ?

**Comment by Arias800** [comment]
Si mon raisonnement est bon et que c'est un problème liée au site je peux pas savoir vus que j'ai pas accès à mon pc ce soir
