### ISSUE TITLE
KEPLIZ OUT

### ISSUE THREAD

**Issue by higuelzim** [Kodi-vStream/venom-xbmc-addons#2378]
Bonjour, le site KEPLIZ a changé d’adresse ? Le lien sur Vstream ne renvoi vers aucun site!!!

Par avance merci

**Comment by TmpName** [comment]
Il y a eu une modif il y a 4 jours avec une bne url.

**Comment by LordVenom** [comment]
l'url et la bonne mais les liens finaux ne fonctionne toujours pas dans la dernière version.

**Comment by TmpName** [comment]
Ha yep, je jette un oeuil.

**Comment by LordVenom** [comment]
Oui ça fonctionne.
