### ISSUE TITLE
Iptv ne fonctionne pas avec Vstream 

### ISSUE THREAD

**Issue by adsav1** [Kodi-vStream/venom-xbmc-addons#2385]
Bonjour
J'ai remarqué que les sites IP TV ne saffichengmnt plus sur mon Vstream dans Kodi le message suivant s'affiche à la place : connexion impossible.
Je suis sur box Android MBOX 6.0.1
Pourtant sur mon smartphone tout fonctionne correctement.
Pensez vous que c'est un problème de connexion ou de soft?
Merci

**Comment by adsav1** [comment]
Personne?

**Comment by adsav1** [comment]
Version de Kodi 16.1
Version de Vstream 0.68
Sites qui ne fonctionnent pas : CinemaVF
Cinemay 
DDLFR
Filmstreamvk
Fullstream
SerieSTreamWAtch
SerieStreamHD
Seriestream.cx
Streamingdivx
StreamingK
Streamzzz
Tfarjo 
Tv_seriestreaming 

Autant dire pas grand chose ne marche ^^

**Comment by johngf** [comment]
@adsav1 je pense un probleme de connexion  mais remet a zero ton install sans tous les addons & repos (poubelle) qu'il y a d'installer et reteste une installe propre kodi & vstream

**Comment by Arias800** [comment]
La peux déjà dire que DDLFR c'est normal qu'il ne marche pas car ils ont activer recaptcha

**Comment by johngf** [comment]
cineme gatoil recaptcha aussi nouveau liens

**Comment by adsav1** [comment]
Et pour la selection IPTV c'est pareil il n'arrive pas à afficher la liste des chaines du pays France

**Comment by LordVenom** [comment]
J'ai éditer ton post avec la liste des sites qui ne fonctionne pas sur tous les test j'en ai trouvé 2 seulement que j'avais désactiver ce matin lors du ménage. Pour moi un site fonctionne si la navigation fonctionne jusqu'au lien finaux, 
Si le décodage du lien ne fonctionne pas soit le lien et mort et ont peux rien faire soit c'est un soucis dans les hosters la c'est intéressant de nous retourner qui quoi comment.

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/6da4a3a21324a8777145bb7f915166fdb2d831c5

**Comment by adsav1** [comment]
C'est bon j'ai réinstallé Kodi tour refonctionne je pense que c'était un problème de corruption avec l'ancienne version de Kodi qui était toujours installé dans la box
