### ISSUE TITLE
Aide sur les .strm

### ISSUE THREAD

**Issue by ludonice54** [Kodi-vStream/venom-xbmc-addons#2388]
Bonjour , 

Je travail sur un petit script permettant de lister tous les film d'un site pour générer des .strm qui seront ensuite ajouter a Kodi .

Voici le format de mes .strm 
plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=Batman+v+Superman++-+L%e2%80%99Aube+de+la+Justice&sMediaUrl=https%3a%2f%2fuptobox.com%2fhn9uc5kp3ulp%3faff_id%3d597033&sHosterIdentifier=uptobox

Tout cela fonctionne sans problème , le film apparaît bien dans ma médiathèque et à la lecture c'est Vstream qui fait le reste .

Seul petit bémol vu que je ne passe pas par Vstream directement si j'arrête le film , le "timecode" auquel j'ai stoppé n'est pas stocké dans la db et je ne peux donc pas reprendre la lecture au même endroit .

Des idées pour corriger ça ? 

Merci d'avance

**Comment by TmpName** [comment]
Tiens c'est bizarre de memoire ca fait un bail que c'est gere par kodi et plus Vstream, tu parles bien du petit popup qui demande si on veut tout revoir depuis le debut, ou continuer la ou on s' est arrette ?

**Comment by Arias800** [comment]
Tu utilise quel version de Kodi ?

**Comment by ludonice54** [comment]
Krypton . Je pensais aussi que Kodi gérerai ce popup mais vu que le film se lance avec Vstream et que si je stop puis relance j'ai pas de popup j'ai un doute du coup .

**Comment by ludonice54** [comment]
Du coup j'ai lancé un film depuis Vstream où le resume fonctionne et j'ai regardé dans la table bookmark de la base vidéo de Kodi ce que ça donne . L'Id me renvoi vers la table files qui contient ceci .

"plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=+Spider-Man+%3A+New+Generation&sHosterIdentifier=uptobox&sTitle=+Spider-Man+%3A+New+Generation+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2Fuptobox.com%2Fob5d79ayj2jm&sFav=play&sMediaUrl=https%3A%2F%2Fuptobox.com%2Fob5d79ayj2jm&sCat=1&sId=cHosterGui&sFileName=+Spider-Man+%3A+New+Generation"

J'ai ensuite exporté depuis Vstream le même film en .strm (qui ne se relance pas) et fait le même test j'ai ceci .

"plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=+Spider-Man+%3A+New+Generation&sMediaUrl=https%3A%2F%2Fuptobox.com%2Fob5d79ayj2jm"

Pour finir j'ai modifié le .strm en faisant un copier coller du lien resumable . Résultat , toujours pas resumable ... 

Je n'arrive pas à comprendre a quel niveau Kodi voit une différence .

**Comment by TmpName** [comment]
La logique voudrait que kodi fasse avec le chemin exact du media.
Tu met un fichier video a 2 endroit sur ton DDR, tu en demarre un, tu l'arrette puis demarre le second, ca repart a zero, meme si c'est le meme.
Dans la mesure ou un fichier video sur Vstream et un fichier strm ne sont pas organise pareil, moi ca me choque pas.

**Comment by ludonice54** [comment]
De ce que j'ai vu sur le net depuis je suis d'accord avec toi . Mais du coup comment ça se passe avec Vstream pour que Kodi soit capable de sauvegarder le temps de lecture ?

**Comment by ludonice54** [comment]
J'ai enfin compris ce qui pose problème .
Lors de la synchro de ma source contenant mes fihiers .strm Kodi associe le film trouvé sur IMDB au .strm sauf qu'au moment de la lecture Kodi récréer une ligne dans files avec le contenu du .strm et c'est cette valeur qu'il utilisera par la suite pour lancer le film.
Donc au final le film scrappé n'est pas associé au contenu du .strm utilisé pour la lecture et c'est pour cela qu'il ne fait pas la liaison avec la table bookmark . Bref un update dans movie vers le contenue du .strm et non son nom corrige le problème .

**Comment by Mtruco** [comment]
Bonsoir,
Je reprends ce post car j’ai le même problème mais je ne comprends pas la solution proposée, si quelqu’un pourrait m’expliquer ce serait sympa.
Merci

**Comment by sizanic** [comment]
Bonsoir, 

Je ne peux pas t'expliquer la solution.

Mais je voudrais m'assurer que tu as bien le même problème.
Car si ton problème est différent, j'aurai peut-être une solution.

Tu as des fichiers .strm qui redirige vers vStream ?

**Comment by Mtruco** [comment]
Bonsoir,
D’abord merci pour ta réponse.
En fait c’est pas avec vstream mais c’est le même principe.
j’ai des strm sur réseau smb que je scraper avec kodi dans ma bibliothèque mariadb et j’ai le même soucis pour la reprise de lecture. J’ai bien compris que le lien du strm a pas le même nom que le nom du film scraper en cours de lecture.

**Comment by sizanic** [comment]
En effet, le même probleme.

Désolé, je ne peux t'aider.

**Comment by Mtruco** [comment]
Bonjour, personne peut m'aider 😢,
Je suis toujours à la recherche d’une solution.

**Comment by sizanic** [comment]
ça sort un peu de notre périmètre, on n'a jamais eu besoin de faire ça.
On ne travaille pas avec des strm.

Concernant un question purement sur KODI, tu auras plus de chances d'avoir de l'aide ici : 
https://forum.kodi.tv/
