### ISSUE TITLE
Nettoyage iptv

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2391]
Je voudrai savoir si quelqu'un a une idée de comment je pourrais faire le même système que pour récupéré les fichier site mais avec l'iptv car tout dans un seul fichier c'est plus viable ^^

**Comment by LordVenom** [comment]
J'ai dejas nettoyer un peux j'ai virer la music de la. voir radio.py tu peux faire plusieurs fichier avec des imports si besoin pour tes fonctions et appelle la fonction load de chaque site pour les menus.

**Comment by Arias800** [comment]
C'est surtout pour maintenir a jour que ça deviens une purge parce qu'une modif peut faire planter tout les sites ^^

**Comment by LordVenom** [comment]
Si je dit pas de connerie et j'ai faim donc c'est possible.

```
    oOutputParameterHandler = cOutputParameterHandler()
    oOutputParameterHandler.addParameter('siteUrl', MOVIE_NEWS[0])
    oGui.addDir(SITE_IDENTIFIER, 'load', 'Films', 'news.png', oOutputParameterHandler)
```

N'importe quel identifier fonctionne donc si tu apelle un fichier site genre mytv2 avec une fonction load il iras l'ouvrir sans soucis.

Donc tu peux faire autant de niveaux que tu veut y a pas de soucis.

**Comment by Arias800** [comment]
D'accord je regarderai merci ^^

**Comment by adsav1** [comment]
Concernant le nettoyage de la liste des chaines IPTV, n'y a t(il pas un moyen simple de retrouver directement les chaines les plus fiables? Surtout quand elles sont nombreuses comme dans la catégorie IpTV(Sites) - IpTv Gratuit - France ?

**Comment by Arias800** [comment]
Non c'est impossible c'est a la personne de faire le tri ^^
