### ISSUE TITLE
Ajouter une radio dans Vstream

### ISSUE THREAD

**Issue by adsav1** [Kodi-vStream/venom-xbmc-addons#2396]
Bonsoir
Je voulais savoir si c'est possible et si oui, et comment faire, pour ajouter une webradio sur l'annuaire de Vstream?

Merci

**Comment by LordVenom** [comment]
Bonjour, joyeux fêtes.
Ill te suffis de proposer ta modification pour ce fichier.

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/extra/radio.xspf

**Comment by adsav1** [comment]
![topelement](https://user-images.githubusercontent.com/40966317/50419391-e54d1f80-0830-11e9-9d78-917193ea4427.jpg)

**Comment by adsav1** [comment]
Et voila ;
https://ufile.io/enojr

**Comment by LordVenom** [comment]
Ok c'est fait par contre fait gaffe ton éditeur n'est pas utf-8 en gros évite notepad XD

**Comment by adsav1** [comment]
Je viens de faire la mise à jour là radio n'apparaît pas dans la liste.

**Comment by LordVenom** [comment]
lol Je voulais dire la prochaine mise à jour aprés la 0.6.83
