### ISSUE TITLE
Contenu disparu suite à réinstallation

### ISSUE THREAD

**Issue by sandoche** [Kodi-vStream/venom-xbmc-addons#2401]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: Android TV
-  Appareil Freebox 4K

**Nous devons le reproduire**
1. J'ai désinstallé VStream (par erreur)
2. J'ai réinstallé VStream
3. Je vais dans Movies et je lance une source
4. Je vois "..." quelque soit la source

**Log**
https://slexy.org/view/s20BJFi0fa

**Plus**
Mon problème est similaire à celui là: https://github.com/Kodi-vStream/venom-xbmc-addons/issues/772
Mais la réinstallation ne le résout pas.

**Comment by LordVenom** [comment]
Un petit test svp allais dans les paramètres de vStream dans l'onglet à **propos/sources** et cliquez sur le boutton d'**origine**. faite ok puis sortez de vStream et revenais l'addon devrais vous demedez de faire la mise à jour. Cela résout le problème ?

**Comment by sandoche** [comment]
J'ai essayé (séparemment)
- de faire le "default" dans les paramètres puis mettre à jour
- de supprimer settings.xml 
- de supprimer le dossier complet (où se trouve settings.xml) et de réinstaller l'app
Rien de tout ça n'a marché.

J'ai donc fini par désinstaller Kodi et réinstaller mes addons (heureusement j'en ai pas beaucoup) et ça a fini par marcher!
