### ISSUE TITLE
Google analytics erreur

### ISSUE THREAD

**Issue by Lola33** [Kodi-vStream/venom-xbmc-addons#2402]
Quand je cherche une tv séries ou que j'utilise vStream..., j'ai toujours ce message

erreur connection failed (404) http//: www.google-analyt......., 
Et le message flash très vite...,  à chaque recherche 
Comment j'peux faire pour arrêter ce message vraiment agaçant.,

Je suis sur un Téléviseur Android version 7. Kodi Krypton 17.6

Merci à l'avance,

Lola

**Comment by johngf** [comment]
ce soucis est déjà arrivé et arrive souvent perso je le désactive mais faut avoir accès au fichier defaut.py ( sur une télé je sais passi on peut) 
le mieux serait une fonction dans settings pour ne pas participer au statistique. voir avec @LordVenom

**Comment by Lola33** [comment]
Merci beaucoup @johngf, je regarde ca, si je peux modifier le default.py, sinon je vais attendre si LordVenom a une autre solution pour moi. 😁
Lola33

**Comment by Lola33** [comment]
Bon..., avec mon éditeur de fichier, j'ai réussi à modifier le default.py
ta solution bin.., super 😁 je n'ai plus ce message et tout fonctionne numéro un
Un gros Merci à toi @johngf

**Comment by Lola33** [comment]
Bonjour, wooow.. minute là 
Qu'est-ce que tu entends par prochain patron? je suis en état de choque là 😭😭😭, sans toi bin, c'sera pas pareil..., je suis inquiète là..., tu vas faire quoi?
J'ai pas de firewall sur mon téléviseur mais un VPN WindScribe que je soupçonne être le coupable car il y a beaucoup de setup pour bloquer les malwares, popups etc, à la prochaine mise à jour, je vais changer les. paramètres et voir si mon VPN est le coupable
Merci pour ton excellent travail
Je suis toujours étonner de voir la très grande efficacité de vStream
Vous êtes les seuls à me donner des résultats pour des series tv en langue française que je ne trouve nulle part ailleurs 
Bonne année à toi et à une équipe vraiment exceptionnelle
Lola33

**Comment by LordVenom** [comment]
Lol c'est gentil mais ça fait plusieurs mois que je fait que de minime modification. Ceux que je vais faire c'est finir la correction d'un bug sortir la version 0.6.9 et donner le repo à @TmpName.

**Comment by TmpName** [comment]
Hein ?
C'est un gag ? Tu laisses tomber le projet ?

**Comment by LordVenom** [comment]
Ben il faut au moins ça pour que je me lance sur d'autre projet 4 ans sur vStream, j'ai bien envie de faire un truc sous Stremio dans le futur il permette au dev de mettre un peux de pub et faire une appli pour smartphone j'ai toujours pas tester bref changer XD.

- Je pourrais faire comme maintenant et me limiter au mise a jour mensuel et quelque bug mais l'envie s’étiole de jour en jour et j'ai pas envie de me transformer en sav sur github.
- Je vais te donner le github mais github ne permet pas de transférer une organisation il faut penser que je vais finir par la supprimer.
- Aprés j'ai toujours internet et mon compte Github XD

**Comment by TmpName** [comment]
Ben, ca me fait plaisir que tu penses a moi mais 
- c'est que moi aussi suis sur pas mal de projet ATM, c'est d'ailleurs pour ca que je passe plus rarement.
- surtout, je me vois pas faire ton boulot de porte drapeau pour Vstream.

Apres je te comprend sans probleme.

**Comment by LordVenom** [comment]
Tu ne veut pas le Github ?

**Comment by Nux007** [comment]
Je veux bien donner un coup de main de manière ponctuelle ;-)

**Comment by TmpName** [comment]
Ben pareil ^^.
Attend c'est pas rien, c'est pas comme si tu pretais les cle de ton appart pour un WE. Deja attend toi a pas mal de reactions suite a cette declaration, et non franchement, dsl, mais c'est un trop gros morceau pour moi.

**Comment by TmpName** [comment]
Houla ^^. Ta maison vient de passer sous un tunnel ? y a des prbs sur la ligne.

**Comment by Lola33** [comment]
Bon..., si je comprends bien parce que vous m'avez perdu là avec vos détails techno...,  🤣🤣🤣 mais bon...,  @LordVenom tu quitte tranquillement pour finalement disparaître completement et @TmpName tu vas prendre la relève mais pas pour tout..., 
SVP dites moi est-ce que nous devrions nous inquiéter pour l'avenir de vStream
Je suis vraiment triste parce qu'il y aura jamais une équipe aussi extraordinaire que vous autres.., 

@LordVenom je te souhaite bonne chance dans tes nouveaux projets.., 
entouka u vas sérieusement nous manquer 
Bon au moins dit moi cé qui le nouveau patron et est-il aussi superfantasmagorique 😁
Lola (je verse une larme ou deux) 😭😭

**Comment by LordVenom** [comment]
Mais non y auras pas de réaction c'est juste pour vous faciliter la vie moi je peux l'aisser tourner le github il me suffis de changer de compte mais c'est dommage de bosser sur un github non gérer administrativement je veut dire.

Personne ne veut de mon cadeau :'( . Venez Venez

`Ils flottent, Georgie… Ils flottent, et si tu viens avec moi… Tu flotteras aussi`

**Comment by Nux007** [comment]
@LordVenom Tu trouves ton compte avec Stremio ? Perso, je le trouve plat et pas très mature ... Je pense aussi la même chose d'Emby mais c'est un autre débat ^^

**Comment by LordVenom** [comment]
Ben coder un truc ça ma pris 5h voila voila quoi.

**Comment by LordVenom** [comment]
Comment ça allais plus loin la tu clicke sur play et tu regarde ton film, aprés tu vas a la douche puis au lit. XD

**Comment by Nux007** [comment]
Mdrrr, ca manque un peu de tv ^^

**Comment by LordVenom** [comment]
Ha j'ai pas regarder je voulais juste faire un test je penser même pas le faire tourner aussi vite.

**Comment by Nux007** [comment]
Y a moyen de faire pas mal de petites choses quand même avec ce machin la ^^

**Comment by adulescente** [comment]
Tut tut tut @ LordVenom

On est le 1er janvier, pas ke 1er avril alors les blagues comme ça, tu peux pas en faire 😜

Je ne veux pas bon! Il est hors de question que tu partes ok??

(Maintenant tu es supposer prendre l'air piteux d'un enfant de 2 ans qui promet qui ne fera plus ça)

Hihi!!

Allez.. 
Fait comme dans le film (Venom). Il part pas au final!

Jue

**Comment by TmpName** [comment]
Enfin bon si tu comptes le temps qu'il a passe sur Vstream, tu peux comprendre qu'il veuille se lancer sur un nouveau projet, et c'est tres dur de se consacrer a fond sur 2 gros projets.

L'avantage de Vstream, c'est que la machine est bien lancée et que donc elle demande moins de boulot (a pars @Arias800 qui est enferme a la cave et qui bosse comme un fou). Donc vous faites pas de soucis, meme sans personne, l'addon peut survivre plusieurs mois, a part que ca va raler a fond comme quoi la source X ou Y est out (D'ailleurs ca fait longtemps que personne ne s'est plaint pour ZT, le site est fermé ?)
Apres vouloir reprendre le projet est une grosse responsabilitée, et c'est pas sur que les candidats "capables" se bousculent. Mais perso si @LordVenom decide de prendre des "vacances" pendant 1 an, ce n'est vraiment pas un probleme, meme si a mon avis vous n'aurez pas de refonte graphique par exemple ^^, mais tenir le code a jour, c'est faisable, surtout si vous voulez vous lancer dans le python c'est le moment ou jamais de filer la main.

En resumé, c'est tres bien pour lui, ca montre que vous aimez sa creation, que l'on est pas dans ce cas la https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2229
Et c'est vraiment encouragant, un grand merci, mais plutot que de vouloir lui mettre la pression, proposez plutot de vous occuper de la maison en son absence.

Et je rappelle, qu'il n'a encore prit aucune decision officielle, mais je peux comprendre qu'il se pose des questions.

**Comment by Arias800** [comment]
C'est les vacance donc la je suis disponible par contre avec la reprise des cours ça être autre chose \o/
Ensuite non zt n'a pas fermer il est toujours la mais il est stable pour le moment .
Et ensuite peux importe le choix de LordVenom il faut le respecter puisque sans lui Vstream n'existerai surement pas donc je pense que le meilleur moyens de le remercier est de respecter ça décision quel quel sois ^^

**Comment by LordVenom** [comment]
google analistycs supprimer de vstream.

**Comment by Lola33** [comment]
This is just to much..., your are so fantastic 
thanks again to make a difference
Lola
