### ISSUE TITLE
suppression tvrex.net

### ISSUE THREAD

**Issue by faribole** [Kodi-vStream/venom-xbmc-addons#2408]
Bonjour et tous mes voeux pour l'équipe vstream qui fait un bon et gros boulot.
Depuis quelques semaines, l'accès à tvrex.net dans la section sport a disparu.
Est-ce temporaire ou définitif.
Le site lui fonctionne toujours mais l'avoir dans vstream est bien pratique pour les replay.

Merci à vous

**Comment by TmpName** [comment]
Il avait ete signale HS au 30/10.
Pour le reactiver met un # au debut de la ligne 6
`#return False`

La je suis pas devant la tv pour tester, mais si ca fonctionne dis le moi stp, je le reactive dans la foulee.

**Comment by Arias800** [comment]
Y'a pas mal de modif a faire c'est pour ça qu'il a été désactiver je suis entrain d'y jeter un œil la  ^^

**Comment by Arias800** [comment]
Normalement c'est bon j'ai corriger le site sauf les live vu qu'il n'y en a pas actuellement ^^

**Comment by TmpName** [comment]
Promis c'est pas ma faute.
Ca fait plus de 2 mois que j'ai touche au moteur de recherche ^^

**Comment by faribole** [comment]
Je viens de vérifier, sans faire de changement dans le fichier tvrex_net.py, la situation reste identique. Pas de lien vers tvrex.
Je décommenterai, ce soir, la ligne que TmpName a indiqué et je vous dirai ce que j'obtiens.
Merci à vous

**Comment by Arias800** [comment]
Oui enfin quand je dit que c'est corriger faut attendre la prochaine maj ou installer la beta ^^

**Comment by faribole** [comment]
hello. J'ai commenter la ligne 6 du fichier. tvrex apparait bien maintenant dans les choix de la section sport mais ensuite aucun affichage des liens. Je suppose que ça fait partie de la prochaine mise à jour.
Je vais patienter
