### ISSUE TITLE
unable to display download list 

### ISSUE THREAD

**Issue by awhabe** [Kodi-vStream/venom-xbmc-addons#2409]
Hi, i can't display or edit download list.

I'd like to contrib but i'm a newbie on python code.
Thx in advance

Env:

Win10 up to date

log error:

{code}
21:32:39.882 T:15160   DEBUG: CPythonInvoker(49, C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): start processing
21:32:39.952 T:15160   DEBUG: -->Python Interpreter Initialized<--
21:32:39.952 T:15160   DEBUG: CPythonInvoker(49, C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): the source file to load is "C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py"
21:32:39.952 T:15160   DEBUG: CPythonInvoker(49, C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): setting the Python path to C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream;C:\Users\alexis\AppData\Roaming\Kodi\addons\script.module.certifi\lib;C:\Users\alexis\AppData\Roaming\Kodi\addons\script.module.chardet\lib;C:\Users\alexis\AppData\Roaming\Kodi\addons\script.module.idna\lib;C:\Users\alexis\AppData\Roaming\Kodi\addons\script.module.requests\lib;C:\Users\alexis\AppData\Roaming\Kodi\addons\script.module.simplejson\lib;C:\Users\alexis\AppData\Roaming\Kodi\addons\script.module.urllib3\lib;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\DLLs;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\Lib;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\python27.zip;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\lib\plat-win;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\lib\lib-tk;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\lib\site-packages
21:32:39.952 T:15160   DEBUG: CPythonInvoker(49, C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): entering source directory C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream
21:32:39.952 T:15160   DEBUG: CPythonInvoker(49, C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): instantiating addon using automatically obtained id of "plugin.video.vstream" dependent on version 2.24.0 of the xbmc.python api
21:32:40.069 T:15160   DEBUG: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:32:40.081 T:15160   DEBUG: 	[PLUGIN] Vstream: load site cDownload and call function getDownloadList
21:32:40.188 T:15160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 65-66: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 288, in <module>
                                                main()
                                              File "C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 24, in __init__
                                                self.parseUrl()
                                              File "C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 86, in parseUrl
                                                if (isDl(sSiteName, sFunction) == True):
                                              File "C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 180, in isDl
                                                exec "oDownload."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\download.py", line 583, in getDownloadList
                                                oOutputParameterHandler.addParameter('sUrl', url)
                                              File "C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\outputParameterHandler.py", line 13, in addParameter
                                                self.__aParams[sParameterName] = urllib.unquote(str(mParameterValue))
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 65-66: ordinal not in range(128)
                                            -->End of Python script error report<--
21:32:40.194 T:15160 WARNING: CPythonInvoker(49, C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): the python script "C:\Users\alexis\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::Dialog,class XBMCAddon::xbmcgui::Dialog,class XBMCAddon::xbmcaddon::Addon
21:32:40.194 T:15160    INFO: Python script stopped
{code}

**Comment by TmpName** [comment]
There is 2 solutions.
1 - Edit the database C:\Users\BRIX\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\vstream.db for PC
2 - patch the code, but I have a problem, you have an error on an url not in the title, so without the url, I can't make a tested patch
But you can try that

```
            try:
                url = str(url)
            except:
                url = str(url.encode('utf-8'))
```

Just after the line 575

**Comment by awhabe** [comment]
Thx a lot TmpName, i have clear all download fioelds on vstream.db and it works fine.

Happy new years :).
