### ISSUE TITLE
Question sur la dernière maj

### ISSUE THREAD

**Issue by ludonice54** [Kodi-vStream/venom-xbmc-addons#2410]
Salut à tous et bonne année ! :) 

Suite à la dernière maj y'aurai t'il eu des modifs sur la résolution des noms de liens ? 

J'utilise Vstream pour lancer des .strm dans ma bibliothèque Kodi .
Pour disposer de l'option "reprendre" sur mes films je remplaçais dans la table files le chemin du strm par son contenu
 (ex : plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=.... etc ) et le path était l'id du plugin Vstream , ça marchait nikel .

Depuis la maj , Kodi lance les films en les nommant dans la table files "video.mp4" et le path est le lien uptobox . 

Si il y'a eu des mofis la dessus est ce qu'il serait possible de m'indiquer les fichiers modifiés ? J'ai regardé les dernières modif sur git mais je suis peut être passé a coté .

**Comment by TmpName** [comment]
Nope, rien de special depuis 2 mois. La je vois pas.

**Comment by ludonice54** [comment]
Ok merci , je vais repartir de 0 j'ai du loupé un truc .
