### ISSUE TITLE
Lag avec lecteur 4k

### ISSUE THREAD

**Issue by GintokiXSakata** [Kodi-vStream/venom-xbmc-addons#2411]
Bonjour / Bonsoir à tous,

Voilà j'ai pris un abonnement Uptobox pour enfin pouvoir voir tout c'que j'veux en illimité (et en bonne qualité) et justement, j'ai un p'tit soucis assez irritant en ce qui concerne la lecture de tout fichiers 4k avec vstream.

En effet, quand je lance par exemple un film en 4K, tout va bien pendant environ 5 min et à partir de là, je rencontre énormément de lag et aussi de freeze avec le p'tit chargement (qui d'ailleurs reste pour la plupart du temps figé à 0 lol). Du coup, je voudrais savoir si quelqu'un a déjà rencontré ce problème ou peut même m'aider, ce serait hyper sympa.

Merci d'avance !

**Comment by johngf** [comment]
quel est ton débit internet ??
pour le 720p 1080p ou la 4k il faut que le serveur t'envoie un débit énorme la plupart des hébergeur n'en sont pas capable ou up tobox c'est limite  >1 fichier est plus performant
