### ISSUE TITLE
LordVenom is False

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2412]
J'en ai déjà parler mais je voulais faire un sujet propre pour vous dire que je cédais ma place, 

Ca fait maintenant plus de 4 ans que vStream existe et il faut que je change un peux de code. J'ai vraiment plus rien à lui apporter, faire les mises à jour et la chasse au bug ça a rien de sympas. Quand au correction plus ça vas moins je les comprend.

Je suis resté uniquement pour l’équipe de fous malade que vous êtes, on à rit on à pleurés, mais il est temps de passer à autre chose.

Donc comme je le disais il faut un nouveau gérant pour le Github. Si personne ne ce dévoue ça resteras comme ça je compte pas supprimer le travail de temps d'année de plus qui n'est pas que le mien.

**Comment by Ovni-crea** [comment]
@LordVenom et on fait quoi du coup si il y a personne le projet sera abandonné ? 
PS:c'est le seule add-on kodi en fr pour les films et séries

**Comment by Mokoman30** [comment]
On a besoin que vStream reste à jour et en vie sinon c est trop embêtant

**Comment by Arias800** [comment]
Supprime de toute façon on peux pas donner le projets au 1er venu trop risquer ^^

**Comment by Ovni-crea** [comment]
@Arias800 ta raison sur ça je le supprime surtout que vstream reste quand même illégale

**Comment by Arias800** [comment]
Non on est pas dans l'illégaliter puisque l'on héberge rien et on ne cherche pas a passer les mesure de securite mis en place par les ayants droit d’après la Hadopi ^^

**Comment by Ovni-crea** [comment]
@Arias800 Ah ouais c'est vrai j'avais oublier que dès qu'on héberge aucun fichiers on reste dans légaliter

**Comment by mino60** [comment]
Pourquoi abandonner définitivement un travail titan, tu pourra passer de temps en temps pour pour le soutient...

**Comment by Ovni-crea** [comment]
@mino60 LordVenom veut développé vstream sur streamio je crois qui serait quand même pas mal non plus mais c'est vrai que c'est vraiment dommage qu'il abandonne le projet surtout quand ta une communauté qui augmente https://github.com/Kodi-vStream/venom-xbmc-addons/issues/200

**Comment by Mokoman30** [comment]
Mais c nul si vstream s arrête comment on va faire pour regarder c était le seul
Addon

**Comment by Nux007** [comment]
Il suffit juste d'arrêter de se plaindre et simplement se retrousser les manches .... comme une vrai communauté ...

**Comment by TmpName** [comment]
De toute facon c'est nul Streamio, dans 15 jours il revient :)
Non, serieusement j'ai quand meme quelques questions pour toi.
1 - Tu vas te refaire une identité, histoire d'avoir la paix ou tu vas garder celle de @LordVenom, pour les deux projets ? Car franchement ca va etre dur de trouver un reprenneur, et je vois mal disparaitre @LordVenom.
2 - Avant de partir, si tu pouvais mettre a jour la procedure pour les MAJ mensuelle (verier la partie obsolette, ...) car je l'ai jamais fais depuis cette methode la.
3 - On peut chnager le copyright de Vstream pour etre sur que personne va nous piquer le code pour un autre plugin sur un autre systeme ^^ ?

Sinon on devrait pouvoir faire le garde meubles sans problemes, pas sur pour ta villa sur la cote par contre, et @johngf a deja pose une option sur tes porches. Mais a part ca, te fais pas de soucis on garde ta place au chaud.

Apres pour ceux qui s'inquietent, je vous rappelle que Vstream tourne grace a vous aussi, donc ca va vous faire du boulot en plus aussi. Mais pas de soucis Vstream restera la.

**Comment by Ovni-crea** [comment]
@TmpName OK merci ça me rassure

**Comment by LordVenom** [comment]
Non je garde mon pseudo il et trop vieux pour le changer. 

Changer le copyright oui vous pouvez, après difficile de reprendre le code pour autre chose que Kodi le mec vas ce retaper toute les fonctions.

Autre info ont a perdu vstream.ga j'ai encore oublier le renouvellement les boites qui font du trading de nom de domaine ont pas attendu dommage.

Je posterais un truc dans le wiki pour la mise à jour mensuel bientôt.

**Comment by LordVenom** [comment]
Ca reste du grab j'aime bien le system mais il génère un json complet avec info et url final ceux qui change c'est la rapidité pour l'user et la non gratuite.

**Comment by zicmama** [comment]
Plutot que de quitter la gratuité, on pourrait associer la Monnaie Libre?
Ca peut se faire en utilisant duniterpy https://git.duniter.org/clients/python/duniterpy pour profiter d'une blockchain monétaire, libre, égale et fraternelle
https://duniter.org

**Comment by shmoxy** [comment]
Francophonie is False.
Dommage (rien de personnel), je n'utilise quasiment plus le français sur le net tellement les ressources francophones sont quasi nulle par rapport à l'anglais. J'aurais bien aimé contribué si je pouvais développer en python mais c'est pas le cas.
En tout cas bravo @LordVenom et tout les dévs et autres... pour tout le travail, j'ai pas bien saisie mais si ça veut dire la fin de vstream, c'est alors la fin du streaming fr sur kodi car je ne connais pas autre chose à la place personnellement

**Comment by TmpName** [comment]
Nope ^^, pas encore.
Et si ca se trouve, dans un an tu auras un nouveau vsteam sur streamio, mais c'est pas franchement la meme politique.
Et je le repette souvent, pas beoin d'etre un kador en python pour filer la main. Tres souvent c'est juste une url a changer, ou 2/3 caracteres a modifier dans un regex.

**Comment by shmoxy** [comment]
> Nope ^^, pas encore.
> Et si ca se trouve, dans un an tu auras un nouveau vsteam sur streamio, mais c'est pas franchement la meme politique.
> Et je le repette souvent, pas beoin d'etre un kador en python pour filer la main. Tres souvent c'est juste une url a changer, ou 2/3 caracteres a modifier dans un regex.

En attendant les updates seront toujours actualisées sur kodi ? EN plus sur stremio si c'est payant vaut pas la peine pour moi je n'ai même pas de carte bancaire alors. Bien que je comprenne tout à fait la nécessite de gagner de l'argent, seulement ça laissera un paquet de personnes à la touche car peuvent pas payer.
Sans faire le statisticien, si je me rappelle bien le premier continent francophone de nos jour (ou dans quelque temps) c'est l'Afrique et franchement, le pouvoir d'achat en Afrique n'est pas très haut.
Donc pour ça que j'ai dit francophonie = false

**Comment by TmpName** [comment]
Le github ne bouge pas. Donc pas de modif de ce cote, a part peut etre quelques plantage le jour de la MAJ ^^.

**Comment by Nux007** [comment]
@TmpName ca va aller :-) 
@LordVenom tu as créé un repo ou je pourrais tester ce que tu as deja fait pour stremio ?

**Comment by LordVenom** [comment]
C'est deja en ligne c'est dans leur repo dans les add communautaire c'est estream.

**Comment by Nux007** [comment]
Ha bon ? ca pourrait m'intéresser, je vais voir de mon coté ce qu'il est possible de développer avec stremio .... je trouve au final que c'est un bon complément à kodi ... C'est quoi ton deuxieme projet ?

**Comment by LordVenom** [comment]
Pas un projet une envie j'ai envie de développer une applis. Je suis partis sur du Js avec electron je penser partir d'une application existante pour apprendre mais je trouve rien qui m’intéresse donc je suis toujours dans les recherches.

**Comment by Nux007** [comment]
Plus pour desktop ou mobile ?

**Comment by LordVenom** [comment]
Electron fait les deux mais pour pc pour le moment

**Comment by Nux007** [comment]
regardes ca:https :// kivy .org

**Comment by LordVenom** [comment]
C'est pas forcement mon niveau Kivy 4 jours pour faire ça

![image](https://user-images.githubusercontent.com/4380112/51346873-f7705580-1a9e-11e9-8c7b-70f1922efa11.png)

**Comment by Nux007** [comment]
Bhen ça va... tout s apprends.. le seul truc de mauvais que je vois dans ce que tu montres , c est l OS mdrr . Tu as un repo git ?

**Comment by LordVenom** [comment]
Nop pas de repo y a rien qui fonctionne sauf l'affichage mais en json pour le moment si tu peux aider je peux faire ça sinon plus tard quand ça "fonctionneras".

**Comment by Nux007** [comment]
Oui, je peux éventuellement aider , mais pas avant milieu de semaine
prochaine, je termine un gros projet PHP 😊 ça m intéresse de savoir jusque
ou tu veux aller avec ton projet, ou les grandes lignes de ce que tu veux
faire quoi... une app Android type vstream serait pas mal...

Le jeu. 17 janv. 2019 à 21:43, Lord Venom <notifications@github.com> a
écrit :

**Comment by LordVenom** [comment]
Les grandes ligne  hum ceux que j'ai en tête pour le moment

- Une application exécutable android & Pc.
- Des poster tirer de themovie database  avec des categories populaire, ect..
- Au click les infos avec un button chercher.
- Recherche via des class dans les sources qui doivent retourner un titre, une url.
Affichage de tous les lien trouver.

Ok ben je ferais un github plus tard ont et pas à la minute XD.

**Comment by Nux007** [comment]
En gros, prendre les points forts de stremio et les points forts de vstream.... Et ça, j achète ^^

**Comment by LordVenom** [comment]
Carrément XD

**Comment by Nux007** [comment]
S il n y a qu' une url de retour et un titre, il y a même peut être moyen d étendre le système de sources a d autres langages, mais je ferai un test avant de dire une bêtise
...

**Comment by LordVenom** [comment]
C'est le but pouvoir recevoir n'import quoi pourvue qu'il passe dans un object mais ça c'est la theorie.

**Comment by Nux007** [comment]
J ai pas mal d idées qui me vient du coups... mais faut pas se tromper sur l architecture histoire de ne pas brider involontairement... on y est pas encore.... on pourrait l appeller vStreamio mdrrr

**Comment by LordVenom** [comment]
Lol me lance pas la dedans faut que je face ma fenêtre d'info la après ont verras XD.

**Comment by Nux007** [comment]
C etait pour deconner hein 😉

**Comment by Nux007** [comment]
@LordVenom tu as une messagerie instantannée ou on pourrait discuter de ce projet ?

**Comment by LordVenom** [comment]
Hum un discord qui traîne par la je pense.

**Comment by Nux007** [comment]
@LordVenom hé merde, l'invitation a expiré lol ^^

**Comment by LordVenom** [comment]
https://discord.gg/rzzKfk

**Comment by Daltons09** [comment]
Salut premièrement félicitations pour votre travail depuis toutes ces années. Mais finalement depuis quelques mois du départ de LordVenom. Que devient vStream ? ça appartient à qui maintenant, la même équipe ? Es-ce que quelqu'un travaille toujours sur vStream ?

**Comment by TmpName** [comment]
Lol, ben pas de changement, ou pas plus que la normalle.
Y a bien un nouveaux qui a eu plus de droits car il changeait souvent les codes, mais sinon depuis le premier janvier il y a 7 personnes qui ont proposes des modifs sur le code dont 5 tres actives, donc pas trop de changement par rapport a avant.
C'est assez peu, car on est pas a l'abri d'un "coup de barre" et ca se ressent de suite, mais pour le moment ca va.
Le projet t'appartient aussi, rien t'empeche de modifier le code, repondre aux issues. En fait tant qu'il y aura des personnes pour s'impliquer un peu plus dans le projet, ca survivra. Dans le cas contraire c'est mort. A chaque mois de l'année y a eu un motivé pour la maintenance, pas possible pour une seule personne de s'occuper du projet.

**Comment by Daltons09** [comment]
@TmpName J'aimerais bien ça vous aidez,  je suis capable de me débrouiller dans les codes mais je ne suis pas un expert. j'aimerais vous proposer des nouveaux sites pour faire du changement. Mais dans ajouter une source.py  je suis perdu à la ligne 246 sPattern = Pour les gens qui aimerait apprendre comment faire pour mieux vous aidez, vous n'avez pas des tutoriaux ? un groupe pour ça ?

**Comment by TmpName** [comment]
Ha les regex ^^, c'est normal, tout le monde se prend ce mur, il y a quelques indices ici https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source
