### ISSUE TITLE
Zt hs? 

### ISSUE THREAD

**Issue by Vidalcris** [Kodi-vStream/venom-xbmc-addons#2413]
ZT ne fonctionne plus chez moi.
"aucune information" de partout.

**Comment by Arias800** [comment]
Oui ils ont changer l'affichage du site donc en cours de correction

**Comment by Vidalcris** [comment]
Ok merci 😉

**Comment by Arias800** [comment]
Corriger dans la beta ^^

**Comment by Vidalcris** [comment]
Super, je vais essayer😉
Merci !

**Comment by Arias800** [comment]
Je pense que tu n'a pas la toute dernière version du fichier ou alors le site a eux un coup de moins bien ^^

**Comment by Vidalcris** [comment]
En effet... Désolé je sait pas pourquoi j'avais pas la dernière version 😅
Merci pour ta réponse, le problème est réglé après installation de la dernière beta.

**Comment by lefou66** [comment]
Bonjour moi aussi j'ai des problèmes avec zt depuis aujourd'hui...certains liens ne marche plus et les recherches non plus et ça fonctionnais bien hier...
Je peux attendre pour la mise à jour mais j'aimerais savoir comment faire pour installer la bêta.. merci.
2 boîtes
Nvidia
Kodi 17.6
Yoka pro 
Kofi 17.6

**Comment by TmpName** [comment]
Si c'est juste pour un fichier, un copier coller du contenu de l'un dans l'autre, dans le bon format est le plus simple.
