### ISSUE TITLE
Fi_s_O_e_v Hs 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#2414]
Salut tout le monde j ai un soucis je regarder la tv j ai changer de chaîne et la Erreur connection failed 403 je comprend pas pourquoi

**Comment by Arias800** [comment]
Corriger dans la beta

**Comment by Mokoman30** [comment]
Merci vivement

**Comment by TmpName** [comment]
J'aurais jamais devine le nom du site avec ce titre.
C'est pour faire un pendu ?

**Comment by Arias800** [comment]
Oui x)
Non enfaite c'est surtout pour être sur qu'il modifie pas le cryptage car sinon ça va être pénible x)

**Comment by Arias800** [comment]
Il faut cliquer une fois sur une chaine cacher pour que enclencher la connexion (j'ai fait ça pour ne pas spammer leur serveur) ^^

**Comment by AzeRim** [comment]
Merci

**Comment by Mokoman30** [comment]
Moi j ai erreur 403 faut j attend la Maj ? J ai pas la bêta
