### ISSUE TITLE
aidez mois pour faire un code

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#2415]
Je veux avoir les lignes C sur un plugin enigma2 linux System 
  est ce que le code est juste car je n'arrive pas à les afficher
url_ main = testious.com

> 
    def load_iptv(self, data, main_url):
        url1 = re.findall('<a href="(.*?)">Free CCcam servers</a></li>', data)
        URL = url1[0]
        self.list_cccam(URL)

>

**Comment by TmpName** [comment]
Pour moi, cette partie est bonne.

**Comment by mino60** [comment]
>  <p class="message"><h2>
  Please enter your Email to get test for free, please note that you'll receive test in your inbox	     </h2></p><br/>
		  <form class="sub-form" method="post" action="#">
		     <input type="hidden" name="idreferrer" value='0'/>
		    <input type="text" name="email" placeholder="Email" required/>
		    <button>Give me test now</button>
		    <p class="message">we offer instant free test for 24H now !</p>
		  </form>
		</div>           
           <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

> 
pour methode post est e que le code et juste..
url_ main = http://cccamlive.com/tests/takeatest/

>     def load_iptv(self, data, main_url):
        url1 = re.findall('<input type="text" name="email" placeholder="amino[0-9]@yahoo.fr" required/><button>Give me test now</button>', data)
        URL = url1[0]
        

> self.list_cccam(URL)

**Comment by TmpName** [comment]
Alors je sais pas ce que tu veux recuperer avec le regex, mais comme je ne vois pas de parentheses, a mon avis tu vas pas recuperer grand chose.

**Comment by mino60** [comment]
je veux recuperer cette page avec un email bidon
[https://i.imgur.com/tp3EZys.png?1](url)
