### ISSUE TITLE
9Docu Off-Line

### ISSUE THREAD

**Issue by mannou78** [Kodi-vStream/venom-xbmc-addons#2418]
Bonjour,

9Docu ne semble plus marcher. Quand on selectionne la source aucun lien n est dispo

Merci pour votre aide

**Comment by Nux007** [comment]
Confirmé, j'y regarde ...

**Comment by Nux007** [comment]
Fixé, la modif sera disponible une fois mergé ...

**Comment by mannou78** [comment]
> Fixé, la modif sera disponible une fois mergé ...

Super merci beaucoup pour le fix!
