### ISSUE TITLE
Idée connection avec betaserie ou trakt

### ISSUE THREAD

**Issue by topio** [Kodi-vStream/venom-xbmc-addons#242]
Bonjour, est ce qu'il est possible de lier dans le futur les episode vus avec vstream a un compte betaserie ou trakt.tv ?

**Comment by LordVenom** [comment]
Bonjour, 

J'avais regarder trakt.tv mais leur api et pas terrible il faut jumeller leur api avec celui de tmdb.
Pour betaserie c'est leur doc incomplète qui me gène ont connais l'api mais pas son résultat faux que je teste a l'occasion.

**Comment by topio** [comment]
Super merci, je me servais bcp de betaserie pour les films et séries en
local et c'est plutôt stylé, ils t'envoie un mail une fois par semaine pour
donner la date des prochains épisodes des séries que tu suis

**Comment by domtom25** [comment]
salut

je voulais simplement remercier pour le travail que vous effectue on vous le dit jamais assez
merci pour la mise a jour des liens vstream v6

**Comment by domtom25** [comment]
vstream version 0 3.6   MERCI longue vie a vous

**Comment by LordVenom** [comment]
Bon aprés 1ans d'attente je commence le code uniquement BetaSerie n'hesitez pas à me dire si vous avez une option que vous désirer je connais encore mal les fonctions du site.

**Comment by TmpName** [comment]
Ha ca fait deja un an ?
Sinon j'ai commence a l'installer, faut que ma copine s'ouvre un compte dessus, mais j'aurais une question:
Tu avais commence a faire un fichier site pour cela, puis tu l'as supprime pour faire carrement une section speciale, avec sa propre classe, une raison ?

**Comment by LordVenom** [comment]
Oui pour pouvoir ajouter un context j avance vite mais il sont limiter en fonction j aurais voulus un truc qui propose des idées peux être trakt mais leur système de login c est de la merde.

**Comment by LordVenom** [comment]
Bon je repart sur track j'ai reussis a m'identifier merci json.dumps.

**Comment by TmpName** [comment]
Heu, bon a part quelques erreurs
>AttributeError: cBseries instance has no attribute 'load' 
[PLUGIN] Vstream Erreur: Connection Impossible,https://api.betaseries.com/timeline/member 

J'ai pas compris pkoi les gens se servent de ca ?
En fait tu vas sur le site de BS, tu coches les films/series que tu as vu (et au bout de 5/6 tu laisses tomber), et ca apparait dans Vstream ?
Et le site est incomprehensible, tu affiches une pages, tu attend 30s, tu actualises et y a des trucs en plus ou en moins, impossible de comprendre comment marche les plannings, c'est tjours vide.
A part passer 8 h a configurer ton profil juste pour afficher Truc a vu machin sur facebook, ca sert a quoi ?

**Comment by LordVenom** [comment]
C'est pourquoi je fait trakt plutot y a plus d'option pour le moment je met le plus évident ont verras par la suite les demandes ou pas.

**Comment by TmpName** [comment]
Bon moi j'y connais rien a leur site, je galere dessus et franchement j'ai pas le temps de m'y pencher, faudrait quelqu'un qui le gere pour dire quelles options lui servirait ou pas.

Du coup j'ai regarde leur API, et y a des trucs a tester, comme la recherche d'info sur un film a partir d'un nom de fichier, ou le calendrier des 8 derniers jours et les 8 suivant.

J'ai un addon (americain) qui scan le dossier de kodi pour voir les series presentes et afficher les sorties future, et la presentation est pas mal script.tv.show.next.aired.

Mais pour l'integrer a Vstream, vaudrait mieux un truc en menu contextuel style "A surveiller avec BetaSerie"

**Comment by LordVenom** [comment]
J'ai commencer trakt beaucoup plus d'option qui lui vas faire des propositions personnaliser et plein d'autre option plus compliquer aussi et comme tu dit faudrais un utilisateur avance de trakt pour les tests. Je tente de voir ceux qui moi me servirais mais je suis pas trop suivis de series ou films perso le marque page me suffis mais en apprenant a bien l'utiliser ça pourrais être pas mal.

**Comment by TmpName** [comment]
Mais les infos de trakt seront pour les americains ?
BetaSerie ne donne pas des infos sur des traductions, ou des diffusions FR ?

**Comment by TmpName** [comment]
Ok, on vient de me repondre, BetaSerie fonctionne avec les sorties americaines uniquement, donc aucun interet face a Trakt.

**Comment by LordVenom** [comment]
Bon on peux envoyer de modif a trakt sans Imdb donc soit pour l'utiliser il faudra activer metahandler soit je fait une fonction pour trouver l'id a la voler. par exemple j'aime asser ce site les infos de base en rapide
http://www.omdbapi.com/?t=%s&y=%s

t= titre
y = année

**Comment by TmpName** [comment]
Trakt a une api qui permet d'avoir l'ID a partir du titre
http://docs.trakt.apiary.io/reference/search

> Search all text fields that a media object contains (i.e. title, overview, etc). Results are ordered by the most relevant score. Specify the type of results by sending a single value or a comma delimited string for multiple types.

**Comment by TmpName** [comment]
Suite la bas
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/676
