### ISSUE TITLE
Qualité sur Uptobox

### ISSUE THREAD

**Issue by FireFirstAce** [Kodi-vStream/venom-xbmc-addons#2420]
Bonjour à tous,

Avant de commencer un énorme merci à tous les contributeurs de cette formidable application qu'est Vstream ! 

Je l'utilise sur une Android TV 4K HDR et étant assez pointilleux sur la qualité j'aimerais pouvoir en profiter au maximum 🤓

Je cherche des contenus avec la meilleure qualité possible (que ce soit image ou son) donc du full 4K etc. et je stream le tout via Uptobox la plupart du temps sur lequel j'ai simplement un compte enregistré non premium pour le moment. 

Du coup j'aurais plusieurs questions :
 
La lecture via Vstream est faite à partir du fichier source Uptobox (donc sans perte de qualité) ou bien à partir du fichier uptostream ? Ce dernier doit être compressé j'imagine et donc moins bon non ? 

D'après ce que j'ai compris en non premium au moment du choix entre direct et stream cela n'a pas d'importance mais je voulais savoir si en prenant un compte premium j'aurais accès justement à ce fichier entier sans perte de qualité ( Blu Ray Full 4K qui font souvent 60Go et +) tout en gardant la facilité de passer par le streaming ? 

En résumé, quelle est la meilleure méthode pour avoir accès aux fichiers complets sans compression ? Est ce possible en gardant une méthode via streaming ? 

J'espère avoir été clair dans ma requête 😅

Par avance merci beaucoup !

**Comment by Nux007** [comment]
Qu'on m'arrete si je me trompe, mais ca va être chaud d'avoir du 4K via Uptobox ...

**Comment by Aliasexterne** [comment]
Avec Uptostream c'est possible.. MAIS, parce qu'il y a un mais, il faut savoir que ce lecteur ne gère pas l'HDR ( HDR10 ou Dolby vision peu importe), ce qui fait que la lecture peut se faire, mais le fichier ne contient pas les données de colorimétrie et l'image se retrouve avec un étalonnage "fade". C'est donc dommage d'avoir accès à la résolution mais de ne pas profiter du contenu dans son intégralité.

**Comment by nicolobi** [comment]
Et donc, quel lecteur est le plus performant ???

**Comment by Arias800** [comment]
En compte non premium il est obligatoire de passer sous Upsostream et j'imagine que via uptostream le flux est compresser . Donc la seul méthode pour avoir de la 4K c'est de payer un hébergeur (1fichier , uptobox) ou un debrideur  . Après faut prendre en compte que la 4K en streaming est très difficile d’accès car il faut avoir une bonne fibre et en plus il faut que les serveur de l'hebergeur envoie assez de débit ce qui est compliquer et rare . Ensuite il faut avoir une television 4K car sans c'est inutile et il faut aussi prendre en compte que la 4K en streaming est TRÈS récent dont forcement peut développer en streaming ^^

**Comment by johngf** [comment]
https://www.lesnumeriques.com/photo/la-vision-humaine-pu121883.html

**Comment by TmpName** [comment]
Lol, ca c'est parce que tu n'est pas "pointilleux sur la qualité" "pour en profiter au maximum". Attend moi j'arrive meme a savoir si une image est en 100hz ou 200hz, et de dos.

**Comment by Aliasexterne** [comment]
Il y a des propositions, reste que bien souvent les fichiers sont découpés en multiples parties au sein des hébergeurs ce qui complexifie le stream. De plus le catalogue UltraHD en général ne fait que commencer. 
Un dernier point concernant la 4k et le streaming. Si la fibre permet d'approcher une qualité correcte voir sensiblement proche des débit que l'on trouve sur du Blu-ray, les débit d'un Blu-ray ultraHD (qui peuvent parfois atteindre les 90/100mb/s) sont encore loin d'être la norme dans le streaming. 
Concernant les différences de fichiers et de lecture, je pense qu'il faut vérifier les encodages. Est-ce du x264, du x265 et quelles sont les métadonnées choisies. Tout en sachant que ce n'est pas Vstream qui gère le HDR, mais le matériel sur lequel le soft tourne ;-)

Autre point important, niveau HDR, il ne faut pas simplement prendre en compte les plages dynamiques mais également l'interprétation des fichiers d’étalonnage par le matériel. Il faut penser la chaîne dans son ensemble et pas simplement en éléments distincts. 
Quoi qu'il en soit à l'heure actuelle, aucun rip ne peut rivaliser avec le support physique pour une question de débit.

**Comment by TmpName** [comment]
XD, moi je viens de me refaire l'integrale de mission impossible (la vielle, pas celle "20ans apres"), son et resolution d'origine, tu crois que ca va passer sur ton matos ?

**Comment by AzeRim** [comment]
Il faut savoir que l’œil humain ne perçoit plus de différence dans la finesse des détails à 240 dpi sur une page A4 imprimée tenue à 30/40 cm. Or nous regardons nos écrans au moins au double soit environ 70 cm. Un écran à 120 ppp donnerait donc l'impression d'être parfaitement lisse avec des pixels invisibles dans ces conditions.

**Comment by TmpName** [comment]
Moi je m'en fou, avec mes yeux, je regarde canal+ sans decodeur. Suffit de regarder 1 pixel sur 2 et de les decaler a chaque affichage (ou alors tu secoue une passoire devant)

**Comment by lebigboss** [comment]
Moi je regarde mes contenus 4k sans problème avec Uptobox et Kodi avec VLC . Des fichiers de 40 ou 50go sur une NVIDIA Shield TV et en stream, j'ai seulement 100mega et aucun lag.
Il y a 4 sites sur vstream qui propose de la 4k

**Comment by AzeRim** [comment]
@lebigboss test ce lien everest 57 Go
 ht tps://upt_b_x.com/surckm0e7bb6
Moi ça lag sur vStream alors que je suis a 95 Mbps en down. Je suis au quasi taquet si je dl en direct.

**Comment by FireFirstAce** [comment]
Merci de votre intérêt (et/ou moqueries 😂) mais du coup ça répond pas à ma question de base : en prenant un abo uptobox Premium j'aurais le choix de faire du direct via Vstream (au moment du choix entre streaming uptostream et rester en direct uptobox) et ça me donnera accès au fichier complet et non celui encodé sur uptostream on est d'accord ? 
Par exemple le film everest de 57go doit sûrement en faire qu'une dizaine en compressé sur uptostream. Y a-t-il donc possibilité d'avoir accès au fichier complet (son 5.1 Dolby/DTS et image sans compression par exemple) en passant par Vstream/Uptobox Premium sans le télécharger en amont ?

**Comment by FireFirstAce** [comment]
Justement si je teste avec Everest, le film se lance sans soucis mais je vois dans les infos : son 2.0 AAC en x264 (certes résolution 4K)  donc pas mal de pertes par rapport au potentiel du RIP d'origine ! Dommage de pas pouvoir profiter du matos a fond quoi...

**Comment by AzeRim** [comment]
Upt_sream est un réencodage du fichier upt_box avec qualité réduite de la vidéo et du son. Je n'utilise jamais uptostream mais uniquement upt_box sur vStream pour lire le fichier en direct sans perte de qualité audio et video (dolby, dts...). La lecture avec l'option rester en direct upt_b_x est l'equivalent de la lecture d'un fichier sans perte déjà dl sur ton dd. 
Généralement, 12 Mbps (1,5Mops) en down suffit pour lire un flux bluray 1080p sans saccade (le webrip 1080p est une qualité réduite). Pour la 4k, c'est aléatoire. Si tu ne veux pas de pb en 4k alors il fo dl sur ton dd (la galère). L'avantage de vStream, c'est de pouvoir visionner direct du bluray 1080p (qualité vidéo/son  du fichier original) qd t premium sans avoir a dl le fichier.

**Comment by BENJI97200** [comment]
@lebigboss ...bjr ,sans configurer advanced setting?

**Comment by lebigboss** [comment]
@AzeRim oui ton lien fonctionne parfaitement, merci j'étais passé a côté de ce film, et c'est en Dolby Digital, comme il y a 3 sources Vff, j'ai aucun ralentissement
Évite de lire sur Kodi, il est trop lourd, utilise un lecteur externe
@BENJI97200 Si j'ai créer un advancesetting, c'est impossible sans

**Comment by AzeRim** [comment]
@lebigboss j'ai pas compris. 
Comment tu fais pour passer par un lecteur externe puis identifier ton compte premium et sans avoir à dl le fichier?
Je ne connais que vStream pour lire un gros fichier uploadé sur un serveur sans avoir a dl sur le dd .
J'ai pas encore tester xbmc avec vStream. Est-ce que c'est bien le lecteur dont tu parle?
C'est quoi t paramètres advancessetting?
Moi j'ai mis ça
<advancedsettings>
<network>
<autodetectpingtime>50</autodetectpingtime>
<buffermode>3</buffermode>
<memorysize>536521386</memorysize>
<curllowspeedtime>30</curllowspeedtime>
<curlclienttimeout>40</curlclienttimeout>
<readfactor>4</readfactor>
</network>
<cache>
<buffermode>2</buffermode>
<memorysize>536521386</memorysize>
<readfactor>5</readfactor>
</cache>
</advancedsettings>

**Comment by BENJI97200** [comment]
@AzeRim ...slt,moi j ai touché 3 réglages : buffer mode(1)/memorysize(375134679)/readfactor(4.0)....et les 1080 p saccadent .Comment savoir quoi mettre ds les autres réglages?

**Comment by AzeRim** [comment]
@BENJI97200 Pas de besoin de fichier advancedsetting pour le 1080p. Tu dois avoir un pb chez toi avec ta connexion. Essayes plutôt sur ton phone android en 4G, il n'y a rien a configurer à part ton compte premium sur vStream.
Pour les paramètres advancedsetting, j'ai pas trouver la solution. J'espère que @lebigboss nous partagera les paramètres qu'il lui permet de lire de la 4k a tt les coup sans lag. 
En attendant tu peux consulter [ça](https://kodi.wiki/view/Advancedsettings.xml)

**Comment by BENJI97200** [comment]
@AzeRim ...merci mais je me perd ds ca désolé....pourtant J ai 100Mbps chez SFR....en 1080 p j ai bcp de freeze (fige sur mise en memoire)/720p aucun soucis...
@lebigboss,tu peux nous donner ta configuration stp? Merci

**Comment by Arias800** [comment]
100mbps c'est le maximum de ton abonnement pas la connexion réel pour savoir ta connexion réel il faut faire un speed test ^^

**Comment by lebigboss** [comment]
@AzeRim @BENJI97200 @FireFirstAce 
Je vais vous répondre, la je fais un truc 
Wizard c'est nul, il y a plus simple. 
Je fini mon truc

**Comment by lebigboss** [comment]
@AzeRim @BENJI97200 @FireFirstAce 
Bon, comme je suis crevée je vais expliquer tout le reste demain ou peut être faire une vidéo sur Youtube.
Déjà pour commencer vous avez seulement besoin de 7 ligne dans votre advancesetting.
memorysize52428800
 buffermode1
readfactor10

Voilà, faut juste ajouter les balises et mettre les balises cache avant et après ce script.
Dites moi ce que vous en pensez.
Normalement vous pouvez même lire les 4k

**Comment by BENJI97200** [comment]
@lebigboss ....Ton memorysize c au hasard on tu as calculé (...÷3*1024*1024)C est quoi les balises?? J attend ton explication demain, merci

**Comment by BENJI97200** [comment]
@lebigboss...et si je met la mm configuration que toi ça passera ?

**Comment by AzeRim** [comment]
Merci @lebigboss ça fonctionne beaucoup mieux avec ta conf.

**Comment by BENJI97200** [comment]
@AzeRim ....tu as mis les mm chiffres et ca passe(4k)?

**Comment by BENJI97200** [comment]
@AzeRim ....pour le memorysize: 52428800....il y a 8 chiffres, ce n est pas 9 qu il faut avoir?

**Comment by lebigboss** [comment]
@BENJI97200  dsl j'étais KO, j'ai oublié qu'on pouvait mettre des images 
![img_20190112_040936](https://user-images.githubusercontent.com/12912677/51068576-2f4f4700-1620-11e9-89d6-6e3d366d5d5a.jpg)

@AzeRim  OK, je te conseil de l'optique si tu peu pour le son, après faut voir les réglages de Kodi
Bon moi je lis les gros fichier et les fichiers de qualités directement avec VLC.

**Comment by AzeRim** [comment]
Merci @lebigboss je comprend mieux de quoi tu parler par lecteur externe avec les images.
J'ai pas la même fenêtre ça va de playlist jusqu'à marquer comme vu ensuite y a juste ajouter aux favoris.
@Arias800 c'est quel fichier STP qu'il faut que je modifie pour avoir l'option lire avec en plus. Je suis sur kodi 17.6 vStream 0.6.9?

**Comment by Arias800** [comment]
Normalement c'est avec le fichier playerfactory.xml https://kodi.wiki/view/External_players

**Comment by BENJI97200** [comment]
@lebigboss.......Ça passe Nickel ,merci....pour fois je lis du 4k....vraiment top .....merci

**Comment by BENJI97200** [comment]
Encore une question ....quelle est la différence entre le lecteur d origine et VLC? C mieux d utiliser VLC?.....Merci à tous

**Comment by TmpName** [comment]
Suis pas sur qu'il y ait de grosses differences de performance (vu qui'ils utilisent les memes libs), par contre pour l'integration evidement celui d'origine a plus d'options possibles.

**Comment by BENJI97200** [comment]
@TmpName ....merci ,tout passait bien j ai pu regarder tout le film first man en 4k.... et mnt des saccades mais je pense que cela vient de uptobox

**Comment by lebigboss** [comment]
@BENJI97200  je vais faire une petite vidéo vite fait Youtube pour expliquer comment paramétrer Kodi pour Uptobox et VLC, etc...
Je sais pas si on peut posté ici des vidéos YouTube, mais ça servira pour plus de monde

**Comment by Arias800** [comment]
Poster une vidéo n'est pas interdit tant quel n'est pas hors sujet ^^

**Comment by BENJI97200** [comment]
@lebigboss....merci bcp

**Comment by BENJI97200** [comment]
@lebigboss....Bjr, j ai un doute quand mm ,car j ai 2 compte premium(uptobox et 1fichier) et sur le film equalizer 2(4k) que ce soit sur uptobox ou 1fichier le film bug au même endroit quand le train entre ds le tunnel,Dc.....????

**Comment by BENJI97200** [comment]
@lebigboss...Merci je teste et je te tiens au courant ......voila le lien :http://uptobox.com/fwu6gef70ruo

**Comment by BENJI97200** [comment]
@lebigboss.....dc ds vstream tu n utilises pas premiun/login ...tu passes directement par urlresolver pour configurer uptobox?

**Comment by lebigboss** [comment]
@BENJI97200  J'utilise un debrideur
Essaie en activant UrlResolver sur Vstream
Désolé j'ai zappé que certains n'utilise pas URLresolver et il y a une option sur Vstream pour Uptobox
"Toujours me demander"

**Comment by lebigboss** [comment]
@BENJI97200 
J'ai testé ton lien Equalizer 2 et sa fonctionne parfaitement.
Avec les réglages sur la vidéo ça devrait fonctionner aussi

**Comment by BENJI97200** [comment]
@lebigboss.....tu utilises quel urlresolver et quel décideur stp? Car en activant le débrider de vstream le film ne démarre pas

**Comment by lebigboss** [comment]
@BENJI97200 
Le 5.0.30 et Alldebrid

**Comment by BENJI97200** [comment]
@lebigboss....ok merci je teste et je te tiens au courant

**Comment by lebigboss** [comment]
@BENJI97200  envoi un screen

**Comment by AzeRim** [comment]
Le lecteur externe ne fonctionne pas avec les liens 1f_chier
![image](https://user-images.githubusercontent.com/41041702/51090232-09898580-1779-11e9-9002-15c2ed5c61fa.png)
En plus, qd tu ferme vlc, ça relance la video sur kodi.

**Comment by BENJI97200** [comment]
@lebigboss....merci J ai réussi ca passe très bien ...vraiment top(j ai gardé le urlresolver de vstream et c nickel)....***2 questions..... vlc ne decode que du dolby digital ? Car sur first man le son n est pas decodé(vu que ce n est pas du dolby) ***...Comment faire pour mettre le lecteur VLC par défaut sur Vstream....Merci pour tout

**Comment by johngf** [comment]
url resolver ne fait pas partie de vstream c'est un addon a part pour ceux qui ont des débrideur
si tu as un compte up tobox ou un fichier il ne sert a rien @BENJI97200

**Comment by lebigboss** [comment]
@BENJI97200 Si, chez moi le Dts fonctionne avec VLC, pas le Dolby Atmos j'ai pas l'équipement pour.
Met ton téléviseur en bistream
Il faut modifier le script pour avoir VLC par défaut (ce que je déconseille, mais bon) 
Modifie ces lignes et remplace Videoplayer par VLCPlayer
![img_20190114_103806](https://user-images.githubusercontent.com/12912677/51105247-ca931880-17e8-11e9-8a84-58949892dbb4.jpg)
@AzeRim Chez moi 1fichier et autres fonctionnent sur VLC.
Par contre tu utilise sur Windows ? Parce que mon script est pour Android normalement
Quand je testerai sur Windows je pourrai t'aider 

@BENJI97200 Si tu as fait exactement comme sur mon tuto vidéo tu devrais avoir du Dolby.
Regarde dans tes réglages son de ta télé
![img_20190114_104445](https://user-images.githubusercontent.com/12912677/51105782-3f1a8700-17ea-11e9-870a-8123ce2dcd4b.jpg)
Ou de ta box. Moi c'est une Shield tv
![img_20190114_105005](https://user-images.githubusercontent.com/12912677/51105799-4fcafd00-17ea-11e9-9411-03b3b928f5b6.jpg)
Mettre soit en automatique ou toujours

**Comment by AzeRim** [comment]
@lebigboss ça marche pas non plus pour moi sur android pour les liens 1 fichier. 
C'est quoi t'as procédure avec urlresolver et debrideur. T'as pas de comtpe premium si j'ai bien compris et tu arrives à tous lire en direct avec ta méthode?

**Comment by BENJI97200** [comment]
@johngf ....Bjr, le problème c qu avec uptobox et 1fichier en premium ,je n arrive pas à lire de 4k et en 1080P les films saccadent....alors qu avec la procédure  de "@lebigboss" j ai aucun soucis pour lire du 4k et 1080P....Et je suis passé par vstream pour régler urlresolver......

**Comment by BENJI97200** [comment]
@AzeRim ....Quand je lance un fichier sur kodi le film ne démarre pas.....Je vais sur l application VLC et ca demarre...

**Comment by BENJI97200** [comment]
@lebigboss....j ai aussi une shield tv ....tous les films passe avec Du dts ,du dolby......sauf les films 4k ,ou ca me donne du pcm...Et j ai exactement suivi ton tuto...Mais ce n est pas grave le plus important pour moi ct les bugs,merci Bcp

**Comment by johngf** [comment]
@BENJI97200 url resolver récupère le meme liens que vstream et ne play pas la video c'est vstream qui démarre le player en envoie l'url au player de kodi.
j'ai pas tous suivi la procédure mais la partie url resolver sur vstream c'est pour débrider un liens via un débrideur non gérer par vstream ex >> all debrid 
comme dit plus haut si tu as un compte premium c'est pas utile
a moins que limite de vitesse de dl de vstream est active sur ça je sais pas voir si @TmpName en sais plus

**Comment by BENJI97200** [comment]
@johngf ....merci pour tes réponses....Je suis sur shield tv...et je t assure que j ai déjà tout essayé concernant advancedsetrings.xml....uptobox ou 1fichier en premium....pour le streaming j ai bcp d arrets sur les films (Je ne dirais pas tout le temps mais" souvent")...Je cherchais une bonne configuration sur kodi pour le streaming et avec celle de "le bigboss" pour le moment ça fonctionne nickel(@lebigboss....pour le son c réglé merci)....j ai suivi bcp de tutos pour configurer advancedsetrings.xml,uptobox,1fichier,rien à faire tjrs des saccades(j ai mm enlevé le décodage audio).....Connexion Sfr 100mbps,avec test :95 mbps/5mbps.....

**Comment by lebigboss** [comment]
@AzeRim J'ai un debrideur, Alldebrid
Ça fonctionne avec rapidgator, 1fichier, uploaded, uptobox, etc. Sauf Nitrofare et d'autres. 
Normalement si tu a pris les fichiers sur mon tuto vidéo ça devrait aussi fonctionné pour toi. Après je passe par URLresolver donc si le problème vient de Vstream j'y peu rien. 
Sinon sur Vstream il faut quand même cocher les cases comme ceci 
![img_20190114_170857](https://user-images.githubusercontent.com/12912677/51124653-1cef2c00-181f-11e9-8b9a-9b6a3a7237ee.jpg)
@BENJI97200 De rien mec, au plaisir
Pour le son Dolby en 4k, est-ce que tu as bien ton téléviseur et VLC en bistream ?
On a les mêmes configuration, je suis à 100mb chez sfr, une Nvidia Shield tv. 
Mais j'ai une sortie optique qui est branché de ma télé à mon home cinéma.

**Comment by lebigboss** [comment]
@BENJI97200 et quand tu lis un Blu-ray 4k surtout les remux, dans la source audio ne choisi pas le Dolby Atmos ça sera du pcm

**Comment by AzeRim** [comment]
Ok c bon j'ai créé un compte sur alldebrid. Il offre 7 jours premium gratuit. J'ai pu faire fonctionner urlresolver via vstream avec la version 5.0.20. En faite on se retrouve plus vraiment avec des liens up tobox ou 1 fichier mais des liens RSLVR-UP ou RSLVR-1FI.
Du coup on a plus accès à mon fichier up tobox ou 1fichier. Peut-être plus de debit avec leur serveur.

**Comment by BENJI97200** [comment]
@ AzeRim ...et mm sans VLC, les films 4k passent très bien...le débit est plus important que uptobox ou 1fichier....

**Comment by AzeRim** [comment]
Perso ça fonctionne mieux pour moi sur kodi. Je trouve VLC plus lent et ça saccade. Je préfère rester sur kodi. C'est vrai que alldebrid est plus avantageux car on a accès à plein d'autres lien sur d'autre serveur du coup moins chargé.

**Comment by BENJI97200** [comment]
@ C vrai que ca passe mieux sur kodi....surtout que le débit de alldebrid est plus rapide ...(contrairement à 1fichier et uptobox)

**Comment by lebigboss** [comment]
Moi je vois clairement une meilleure qualité d'image sur VLC, surtout pour les Blu-ray 4k.
Par exemple su le Blu-ray de Everest en 4k bah je vois grave une différence 
Avec vlc
![img_20190114_215819](https://user-images.githubusercontent.com/12912677/51140986-38baf800-1848-11e9-89ca-66fb55bba0c0.jpg)
Avec Kodi
![img_20190114_220035](https://user-images.githubusercontent.com/12912677/51141002-453f5080-1848-11e9-9dc4-960ef138919a.jpg)

Je sais pas si c'est le cas chez vous, mais ça dépend de votre tv, votre branchement etc... 
Et chez moi VLC est plus fluide, même si Kodi l'est mais on sent qu'il a besoin de beaucoup de ram pour fonctionner. 
Après c'est que mon avis

**Comment by AzeRim** [comment]
Pas mal faudra que je fasse l'essai aussi avec ma shield qu'en j'aurais le temps.

**Comment by BENJI97200** [comment]
@lebigboss ....quelques fois quand je veux lire un film avec VLC, ça me dit emplacement annuaire téléchargement......ne peut être lu...?

**Comment by BENJI97200** [comment]
![15475099798925488091092197494570](https://user-images.githubusercontent.com/41129179/51148892-3ea7dd80-1836-11e9-94ec-0d85c010e4cb.jpg)

**Comment by AzeRim** [comment]
Mode hdr activé sur la tv
![vlc](/storage/emulated/0/Download/20190115_000600.png)

![kodi](/storage/emulated/0/Download/20190115_000739.png)

**Comment by AzeRim** [comment]
Résultat avec ma Shield TV avec mode hdr activé sur la TV

![image](https://user-images.githubusercontent.com/41041702/51159932-d1269c00-188b-11e9-90b4-fc4bbe8c44a5.png)
![image](https://user-images.githubusercontent.com/41041702/51159942-e3a0d580-188b-11e9-8985-2df9c7ed38f0.png)

**Comment by Aliasexterne** [comment]
Hé bien je vois que le sujet a évolué, mais cela reste passionnant de voir comment optimiser le tout. 
De mon côté j'ai juste une petite question, comment faites vous pour avoir "lire avec" dans le menu contextuel? je n'ai pas cela dans mes versions ( Kodi sur windows 10 et kodi sur android tv)

**Comment by AzeRim** [comment]
Pour avoir l'option lire avec tu peux telecharger le zip dans la video youtube de @lebigboss (c le fichier playercorefactory.xml).
Oui a priori vlc lance la video en 1080p malgré une source 4k. A voir si c'est paramétrable via vlc ou playercorefactory

**Comment by lebigboss** [comment]
@BENJI97200 Normalement sur la Shield quand tu lance une vidéo sur VLC des fois ça lance pas directement, il faut double cliquer sur le bouton home et aller sur VLC.

@AzeRim Je vois que tu as la même qualitée. Kodi ne prend pas en charge la hdr normalement, à mon avis ça doit dépendre du branchement.
Moi j'ai un câble hdmi 18gbps qui gère le hdr 60hz. J'ai activer le UHD Color de Samsung. 
Je suis donc en 10bits sur Shield en yuv 2020, ma télé fait 10 bits. 
Si je t'explique tout ça c'est que peu importe si tu lance la vidéo sur kodi ou sur VLC si ta config est faite pour ne pas avoir une autre qualité bah ce sera le même résultat.

Moi par exemple j'utilise par le hdr, à part sur Netflix ou Amazon prime qui sont intégré à la tv,
mais si je met le hdr et quelques réglages j'ai pratiquement le même résultats que toi
**Kodi avec hdr à droite et sans à gauche** 
![img_20190115_114627](https://user-images.githubusercontent.com/12912677/51175681-48bfef80-18bb-11e9-8930-3ad061179e69.jpg)
Mais avec des réglages et VLC on voit bien ala différence entre ton média et le mien
_À gauche le mien avec VLC et le tien à droite avec Kodi_
![img_20190115_113930](https://user-images.githubusercontent.com/12912677/51175740-6c833580-18bb-11e9-964c-77e43b9ddc9d.jpg)
C'est juste une photo et normalement on peut pas juger de la qualité d'un 4k sur une photo, mais on voit bien les différences de couleurs, le rouge est plus vif d'un côté que de l'autre alors que le HDR devrait être au dessus.
On voit que le sac est jaune fluo et pas seulement jaune, etc et je suis sur qu'il doit y avoir une différence avec les visages. 
VLC prend en compte le YUV parfaitement puisque j'ai déjà essayé en ayant DL un Blu-ray 4k de 50go et je l'ai mis sur un hdd 3.0 pour le lire directement sur ma TV. 
Et le résultat est le même que quand je lis le lien directement avec VLC en passant par Kodi, en stream. 

Par contre c'est pas normal que tu es du 1080p sur VLC. Ta du te trompé quelque part

**Comment by BENJI97200** [comment]
@Merci bcp....

**Comment by AzeRim** [comment]
Spec de ma tv www.displayspecifications.com/fr/model/02f2431
 Tu dois avoir une touche info sur ta tv pour les détails sur ton flux.
Vlc sur android est peut-être bridé à 1080p car la photo a été prise à partir de vlc via vStream avec kodi 17.6
J'essayerai de mettre des photos avec le mode normal ou sport plus tard.

**Comment by johngf** [comment]
"À gauche le mien avec VLC et le tien à droite avec Kodi"
quand tu affiche le bandeau en bas kodi assombri l'image c'est normal @lebigboss

**Comment by AzeRim** [comment]
Photos avec TV en mode HDR désactivé et affichage image Dynamique avec flux up tobox (l'hebergeur n'est pas stable dc la vidéo saccade par moment) 

**SHIELD TV Branchement direct à la TV**
KODI
![image](https://user-images.githubusercontent.com/41041702/51197667-7aa07880-18f2-11e9-87f5-5a332dfabfdb.png)
![image](https://user-images.githubusercontent.com/41041702/51198673-3bbff200-18f5-11e9-9335-e78c35ec556b.png)
VLC
![image](https://user-images.githubusercontent.com/41041702/51197847-e551b400-18f2-11e9-97ec-3177d7262ef2.png)
![image](https://user-images.githubusercontent.com/41041702/51197986-4da09580-18f3-11e9-9563-68d90aa8b155.png)

**SHIELD TV Branchement direct à un ampli qui ne prend pas en charge le HDR**
KODI
![image](https://user-images.githubusercontent.com/41041702/51198773-7a55ac80-18f5-11e9-9ead-0d30422390b4.png)
![image](https://user-images.githubusercontent.com/41041702/51198391-6b222f00-18f4-11e9-868e-8506d8a019ec.png)
VLC le son est en retard d'environ 1s et léger saut d'image tte les 3s environ
![image](https://user-images.githubusercontent.com/41041702/51198838-a5400080-18f5-11e9-9419-98c3eb1688b6.png)
![image](https://user-images.githubusercontent.com/41041702/51198485-a91f5300-18f4-11e9-9de6-885d451769ae.png)

Le flux avec 1 fichier était plus stable que up tobox la dernière fois sur une autre vidéo.
Le premium gratuit de 7 jours sur allde brid est limité à 25Go car gratuit donc j'ai pas trop insisté dessus.

**Comment by lebigboss** [comment]
@AzeRim ok et tu vois une différence de qualité ?

**Comment by AzeRim** [comment]
C'est pareil au niveau de l'image mais vlc semble plus performant pour le décodage audio au détriment de la vidéo. Par rapport à mon matos, tant que c'est du dolby digital ou du dts tout court c nickel mais dès que c'est au dessus (digital+ truehd...) ça commence a bug sur le son et l'image. Obligé de désactiver le décodage audio.
Perso je préfère kodi par rapport à mon equipement actuel.

**Comment by AzeRim** [comment]
@BENJI97200  t'es branché direct à un ampli qui decode le format audio en auto ou direct à la Tv où faut choisir en manuel le format audio
![image](https://i.ibb.co/6gwJYMZ/20190116-063550.jpg)

**Comment by lebigboss** [comment]
Bizarre, bon pas grave, du moment que ça fonctionne. Ça doit dépendre du Matos des gens

**Comment by BENJI97200** [comment]
@AzeRim ....Bjr,oui en direct sur ampli Yamaha  Rxa 3070(En hdmi).....

**Comment by AzeRim** [comment]
Ok, il va falloir que j économise pour prendre un autre ampli plus performant pour décoder tous les formats audio et avec prise en charge du hdr afin de profiter pleinement du lecteur externe vlc.

**Comment by tigait62** [comment]
bonjour, j'ai suivi un peu le tuto et ce post malgre avoir telecharger le fichier zip pour avoir l'option "lire avec" je n'arrive pas a installer le fichier zip dans kodi cela me marque echec d'installation du fichier zip
