### ISSUE TITLE
Programme vavoo 

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#2421]
J'ai essayé vstream sur le programme vavoo je croi qu il est plus rapide que kodi facile a utiliser idéal pour les téléchargement et les info
pour le build vous devez mettre comme adresse: vavoo.to
tout les chaines française sont disponible dans vavoo live

h ttps://www.vavoo.tv/software

**Comment by LordVenom** [comment]
99,99 € pourquoi? un linux avec une application base sur Kodi ça fait cher quand même. pour l'applis oui c'est pas mal trés rapide mais pour vstream ça change pas grand chose pourquoi  les requetes plus y a de requetes moin ça vas vite CQFD.

**Comment by Che-debarras** [comment]
Je viens de tester cette appli Vavoo mais y a un point négatif c'est que ya pas "bundles" français sans parler de la non gratuité 

Le seul truc bien dans vavoo c'est l integration de F_rstO_ne.tv dans l onglet TV avec toutes les chaines de tous les pays comme sur le site ey ca fonctionne sans lag

Peut etre qu il es possible d integrer de la meme facon cette source
