### ISSUE TITLE
Series manquantes sur seriestreamingHD

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2422]
Bonjour, 
J'ai lu les dernières posts et il semblerait que c'est la fin de vstream ce qui explique que ya presque plus de bugs rapportés donc je sais pas si celui sera corrigé mais qui tente rien n as rien.

Sur sériestreaminghd ya une serie "COUNTERPART" qui ne montre aucune episodes que ce soit saison 1 ou 2 et tous ce qu'on lit c'est "LANGUE VF" et "LANGUE VOSTFR" en rouge.

J'ai vérifié sur le site internet de la source et il y a bien les episodes 5 au total mais elle ne s'affiche pas sur vstream.

Merci et dommage pour l arrêt de vstream, ya eu la fermeture de   allfrtv pour kodi et voila vstream qui ferme donc oui les addons kodi fr finissent pas quitter ce monde  prématurément 

NB: peut etre voir les devs de Allfrtv sil peuvent reprendre ou ceux de Catchup tv & more je pense qu'ils sont digne de confiance (c juste une idée dsl si hors sujet)

**Comment by Arias800** [comment]
Non Vstream n'est pas mort ^^
En ce qui concerne cette série elle est uniquement disponible sur netu qui a ete desactiver sur Vstream a cause de Recaptcha donc ce n'est pas un bug ^^

**Comment by Che-debarras** [comment]
@Arias800. Autant pour moi c'est vrai que voir les liens netu non fonctionnelle ça agace un peu donc désactiver c'est une bonne chose.

Juste par curiosité et désolé si çà été expliqué mais si tu peux me rappeler le problème avec Netu sur vstream. Merci

**Comment by Arias800** [comment]
Le probleme c'est que pour accéder au liens de la vidéo il faut passer par Recaptcha qui un système de protection anti bot de Google . Or il n'existe actuellement aucun moyens de passer cette protection via Kodi et donc l'utilisation d'un navigateur est obligatoire donc pour le moment ont la désactiver ^^

**Comment by TmpName** [comment]
1 remarque, j'ai eu le meme soucis pour une serie a moi https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2220
Et justement elle est presente sur ce site. Du coup je repose ma question, est ce que vous pensez que ce site vaut le coup ? Au pire on en supprime une pour garder le quota.

2eme remarque, j'ai adore cette serie aussi.

**Comment by Arias800** [comment]
Personnellement je trouve toujours ce que je cherche donc je m'en fiche un peux ^^

**Comment by Che-debarras** [comment]
Pour moi cette sourcr est excellent pour sa qualité et rapidité donc la garder serait bien. L autre source identique est streamingserie.cx de bonne qualité et complet jy retrouve cette series , le seul souci c'est pas rapidement a jour par rapport a seriestreaminghd

**Comment by TmpName** [comment]
Ben moi j'ai toujours un train de retard donc c'est pas la rapidite qui m'interesse, mais j'aime bien trouver de vielles series qui ont plus de 5 ans. L'epoque de Youwatch me manque, c'etait pourri, ca ramait un max mais y avait vraiment de tout ... meme si c'etait pas du 4k.

Bon du coup je touche rien, a prochain qui galere pour trouver un titre.

**Comment by Che-debarras** [comment]
C'est vrai que le retard n'est pas genant vu que ya d autre serie et film. 

Jen profite pour demander si la source Mamzouka est sur vstream ( sous un autre nom)

**Comment by TmpName** [comment]
Nope, je pense pas.
