### ISSUE TITLE
MAJ 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#2424]
Salut tout le monde c’est pour quand la mis à jour car j ai un iptv qui est en erreur 403 merci

**Comment by TmpName** [comment]
Ben, la derniere remonte a 15jours, donc encore 15jrs.
Mais suis pas sur que ton prb soit resolu. C'est quel lien ?

**Comment by johngf** [comment]
on peut faire des version intermediaire
si je comprend bien il faut faire un pull merge la beta sur la master ( un doute >> ensuite merge la master sur la beta) et faire la release et c'est bon ?

**Comment by TmpName** [comment]
Ben je crois qu'il ya que 2 etapes, @LordVenom a mit a jour le wiki.
Je tente, si je me rate, me cherchez pas, suis a tombouctou.

**Comment by TmpName** [comment]
Alors je peux pas te dire quand elle va arriver chez toi (meme moi je l'ai pas), mais je confirme @Arias800 l'a deja corrigée, elle fonctionne en ce moment (si je copie le fichier).

**Comment by Mokoman30** [comment]
J ai eu une Maj l iptv à marcher et au bout de quelque jour cette fois l iptv charge ,cette fois sans erreur charge indéfiniment je comprend pas

**Comment by Mokoman30** [comment]
après la maj il y a un petit moment tout va bien tout remarche jusqu au weekend ou l iptv en question charge sans s arrêter quand je veux cliquer sur une chaîne pourtant je rentre sans problème dans l iptv juste quand je clique sur une chaîne sa charge sans s arrêter j ai essayer sur 2 de mes tv même résultat sa dois pas venir de chez moi le soucis

**Comment by Arias800** [comment]
C'est bon nouvelle version en ligne normalement elle corriger le probleme ^^

**Comment by Mokoman30** [comment]
Super bon ba j attend qu on me propose la MAJ je te tiens au courant

**Comment by Mokoman30** [comment]
C est pour quand la Maj pas mal de lien mort niveau série 
Zone téléchargement marche pas
Iptv f..st o.e Tv marche pas 
Vivement une Maj vite

**Comment by TmpName** [comment]
Faudrait faire un calendrier, car moi je suis plus du tout la, me souviens meme pas de mon annif, donc les MAJ partielles ...
On prendrait
- tout les 15js > maj partielle
- tout les 45 jours > maj totalle 

Non ?

**Comment by johngf** [comment]
je te laisse la maj mensuelle :-)

**Comment by TmpName** [comment]
Ben y a pas de soucis, alors je pars de la derniere en date et je compte 45 jours ?

**Comment by johngf** [comment]
ok

**Comment by TmpName** [comment]
Bon ben dernier maj 30 decembre, lol, donc m'en occupe cette semaine, on a deja depasse les 45jours.
Par contre je viens de lire le mode d'emploi, va falloir faire ca a tete reposée ...

**Comment by johngf** [comment]
quelqu'un avait trouvé une fois mais je m'en souviens plus voir dans les issues apres dans repo il y a tous les anciens vstream donc... faudrait peut etre allégé le répertoire

**Comment by TmpName** [comment]
Lol, la je vais pas oser y toucher pour le moment.
J'espere que la prochaine fois je vais pas etre oblige de tout re DL, car franchement c'est abuse la taille de l'archive.

Bon alle ce soir, je tente la grosse MAJ.
