### ISSUE TITLE
changement correctif a insérer dans vstream

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2428]
1:depuis 2 mises a jours dernière  il y a Kaydo(hds.to) qui est revenu dans la liste de source , pourriez-vous l'enlever vu qu'il n est plus fonctionnel , ( photo en commentaire)

 2: a la source Wawacity il n'y a pas d'image pour identifier la source , faite juste ajouter dans le dossier :
kodi/addons/plugin.video.vstream/ressource/art/sites
j'ai mis juste une image et la source l'indique, je vais vous donnez l'image a ajouter

merci de faire la modifications pour la prochaine MAJ

**Comment by KodiTopQuebec** [comment]
![sans titre](https://user-images.githubusercontent.com/40530593/51356003-f0d5e400-1a86-11e9-9b73-3658929a05a9.png)

**Comment by KodiTopQuebec** [comment]
![kaydo](https://user-images.githubusercontent.com/40530593/51356011-faf7e280-1a86-11e9-833a-4f7622939556.png)

**Comment by KodiTopQuebec** [comment]
![wawacity](https://user-images.githubusercontent.com/40530593/51356018-021ef080-1a87-11e9-977b-13d31d0eb99c.png)

**Comment by tuego72** [comment]
Salut
    ZT ne fonctionne plus depuis votre mise à jour et fonctionnait très bien avant...

**Comment by TmpName** [comment]
Kaydo deconne, mais il marche chez moi (enfin le site). Faudra y jetter un oeuil.
Pour wawa city, je m'en occupe de suite, merci ^^.

**Comment by johngf** [comment]
c'est pour ça je j'avais pas posté la modif de hds  a mon avis il faut refaire le m3u8 avant de le play

**Comment by Arias800** [comment]
Faut le désactiver kaydo je vais changer de site car celui utiliser ne vaut plus le coup ^^

**Comment by TmpName** [comment]
Ha ce point ?
C'est quoi le prb ? (j'ai pas pu m'y connecter ce matin , bloque par un captcha en boucle) Fichiers pas a jours, plus de news ? liens mort ou juste site casse couille ?

**Comment by Arias800** [comment]
A la base je l'avais ajouter car il proposait du 1080p et car hd ss n'avais pas de serie mais maintenant ce n'est plus le cas donc je vais basculer sur hd ss ^^
