### ISSUE TITLE
Erreur URL resolver alldebrid

### ISSUE THREAD

**Issue by filetransfert** [Kodi-vStream/venom-xbmc-addons#2430]
salut j'ai activer alldedbrid sur vstream.

mais tous les lien affiches fichier introuvable.

la version de mon urlresolver est de 5.0.30.

quelqu'un peut m'aider

**Comment by BENJI97200** [comment]
Bjr ,tu as un compte alldebrid?

**Comment by Arias800** [comment]
De toute façon url resolver est indépendant de Vstream donc si c'est un bug d'url resolver nous on ne peux rien y faire ^^

**Comment by johngf** [comment]
"Exemple, lien uptobox fonctionne sans problème via un site Z, mais pas de probleme sur site Y toujours en uptobox" ça veut dire que tous va bien ?

**Comment by johngf** [comment]
si c'est un site #2220 autres page principal 
pour urlresolver c'est pas vstream qui resolve l'url

**Comment by BENJI97200** [comment]
@Lioon2 ....ds les paramètres de urlresolver..fait reset my autorisation et( Re)Authorize my Account ,et ca devrait marcher car j ai eu le mm soucis

**Comment by Lioon2** [comment]
Deja essayé sans succès, même après avoir complètement reinstaller kodi+extensions. J'ai même lu sur le net qu'il était bon de desactiver use function cache qui pouvait poser problème. Sans succès :)

**Comment by Ovni-crea** [comment]
@Lioon2 au pire pourquoi tu le signale pas au développeur de urlresolver

**Comment by Lioon2** [comment]
officiellement il n'est plus supporté si?

**Comment by Ovni-crea** [comment]
Bah si normalement il est toujours supporter la dernière mise a jour date il y a 1 mois
