### ISSUE TITLE
Extreme d0wn ne fonctionne plus 

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2433]
**Décrivez le bug**
Extreme d0wn ne fonctionne plus 

**Plus**
Salut, ça fait quelques jours que ED ne fonctionne plus, merci pour la MAJ.

**Comment by Ovni-crea** [comment]
@lebigboss c'est bon j'ai fait un pull request pour extreme download

**Comment by lebigboss** [comment]
@Ovni-crea ça fonctionne merci

**Comment by Ovni-crea** [comment]
@lebigboss De rien
