### ISSUE TITLE
Erreur Vstream sur une nouvelle install

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#2434]
Hello
Je viens d'installer Vstream sur une nouveau OSMC 17.6 sur RPI3.
Malheureusement il y a une erreur à chaque démarrage de Vstream.
Tout marche bien d'habitude.
Je joins mes logs en espérant que vous pourrez m'aider.
Remerciements `anticipés.`

https://pastebin.com/Xmh5VvTJ

**Comment by TmpName** [comment]
Tu as quelle version de Vstream ?

**Comment by canopre** [comment]
0.6.9

**Comment by TmpName** [comment]
C'est bzarre quand meme, tu connais un peu le python, j'aurais des modifs de fichier a te faire faire ?

default.py ligne 25
Remplacer
cDb()._create_tables()
par
tmp = cDb()
tmp._create_tables()

Car j'arrive pas a comprendre pourquoi la fonction _create_tables() ne marche pas si l'initialisation se fait correctement.

Ni pourquoi sur une install neuve, tu passes par tmdb des le debut ...

**Comment by canopre** [comment]
Hello
J'ai activé les logs de vstream et redémarré :
Voici les nouveaux logs :
https://pastebin.com/Dvq82e8z

Je vais maintenant faire la modification suggérée.

**Comment by canopre** [comment]
Et maintenant les logs avec la modification :
https://pastebin.com/2KTfPm2v

Pour info : Après la modification : Je n'ai plus dutout accès au menu de Vstream ; Avant j'avais une erreur et pas de film mais tout de même accès à l'addon.

**Comment by TmpName** [comment]
'unexpected indent' ^^
C'est pour ca que je demandais si tu connaissais le python, en fait en python 3 espaces ou un tab c'est pas pareil, les 2 lignes doivent etre exactement au meme niveau, et si avant c'etait des espaces, remettres des espaces, ou des tabulations , mais pas les deux.

**Comment by canopre** [comment]
Oups...Désolé.
J'ai vérifié les droits mais ça ne fonctionne tjrs pas.
J'ai toujours cette erreur :
11:03:06.857 T:1622143744  NOTICE: 	[PLUGIN] Vstream: erreur: Impossible d ecrire sur /home/osmc/.kodi/userdata/addon_data/plugin.video.vstream/vstream.db

C'est bizarre...

**Comment by canopre** [comment]
J'ai installé Osmc via PinnLite : Ca doit venir de là.
