### ISSUE TITLE
Gros bug avec l'arrivé de kodi 18 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2436]
**Décrivez le bug**
Impossible de rentrer dans la section librairie

**Votre system**
 - OS: Android TV 8.0
-  Appareil xiaomi mi box 
 - kodi 18 (la version release)
- la dernière version de vstream.

**Plus**
Je peux toujours ajouter un film dans la librairie

**Comment by TmpName** [comment]
Je peux pas te dire, j'ai voulu l'installer, crash.
Ni la version 64 ni la version normale ne veut s 'installer.

**Comment by Arias800** [comment]
Correction ça fait deux ans qu'il teste Kodi 18. :p
C'est lors que Kodi appel la fonction pour ouvrir les dossier que ça merde et forcement pas de message d'erreur x)

**Comment by Arias800** [comment]
Bah elle est exécuté mais c'est comme si elle ne fait pas effets

**Comment by Ovni-crea** [comment]
@TmpName j'ai fait pareil que toi j'ai rétrogradé ma version je suis revenu à la v17 sinon dans le log il y avait rien donc j'ai pas besoin de vous le donné

**Comment by BENJI97200** [comment]
@TmpName...slt comment fais tu pour rétrograder la version en 17.6 sur android stp?

**Comment by TmpName** [comment]
Je suis pas sur android.
Mais sur PC il suffit de reinstaller le version que tu veux sur la precedente, sans desinstaller la precedente, c'est crade, mais propose par leur team.

**Comment by tuego72** [comment]
le problème semble être sur kodi 18 avec windows car moi avec linux tout fonctionne bien sauf pour superfavourites mais ça ça doit être parce qu'il n'est pas à jour pour kodi18

**Comment by BENJI97200** [comment]
Bjr...le menu de vstream est très lent(kodi 18 lea)....une solution svp?

**Comment by TmpName** [comment]
Ne se servir que du s9 ?

**Comment by Arias800** [comment]
Le problème doit venir de chez toi car chez moi aucun problème avec la Shield c'est même bien plus rapide ^^

**Comment by BENJI97200** [comment]
@Arias800 ....merci et tu penses que ça vient du réseau Internet?

**Comment by Arias800** [comment]
Je sais pas après c'est peut être ton installation Kodi qui merde

**Comment by BENJI97200** [comment]
@Arias800 ...j ai tout réinstallé

**Comment by BENJI97200** [comment]
Et pourtant pareil...snifff

**Comment by TmpName** [comment]
C'est quoi que tu appelles "le menu", le menu hors ligne ou le menu qui apparit sur les sites, ou il y a des recherches ?

**Comment by BENJI97200** [comment]
Bjr...Non, juste le menu des sites ...merci ce n est pas grave

**Comment by TmpName** [comment]
Tu as les metadatas activées ?

**Comment by BENJI97200** [comment]
@TmpName ....Oui ct activées....merci bcp ca passe très bien mnt...merci

**Comment by BENJI97200** [comment]
@@TmpName...au fait c le site zt qui rame ...tous les autres sont bons

**Comment by TmpName** [comment]
Alors c'est normal ^^.
Le site a encore des soucis, deja c'est bien qu'il marche chez toi, chez certains c'un bloquage cloudflare.
