### ISSUE TITLE
Modifier la métadonnée proposée

### ISSUE THREAD

**Issue by B4rtux** [Kodi-vStream/venom-xbmc-addons#2437]
Bonjour ! Merci énormement pour cette fabuleuse extension, petite question? Serait-il possible d'avoir la possibilité de changer de métadonnée comme le propose les addon avec un répertoire de film. Par exemple, quand un FanArt est celui d'un autre film du même nom ? SVP ça me sauverait la vie !

**Comment by TmpName** [comment]
Non pas trop possible, la recherche se fait d'apres le titre, donc c'est pas tres precis selon les sites, et si ca demandait une validation a chaque fois, tu deviendrais rapidement dingue quand tu fais defiler les films.
Quand c'est pour du fixe comme un repertoire de film ok, mais du contenu en ligne c'est pas trop realisable.

**Comment by B4rtux** [comment]
Oh c'est vraiment dommage car j'avais trouvé une petite astuce sympathique justement, j'ai sauvegardé tous les films disney de la source Disney.tk, je les ai mis en marque pages, et je voulais les scaper en mode dossier de sources vidéos (avec super favourite) mais je n'y parviens pas :( c'est dommage parce que la , le répertoire était fixe ! Surtout qu'il n'y a que les liens directs ! Merci quand même :(

**Comment by B4rtux** [comment]
On peut modifier la db ??

**Comment by B4rtux** [comment]
Ca ne me dérangerait pas de modifier, sur les 93 Films, y en a une dizaine avec une mauvaise affiche etc...

**Comment by TmpName** [comment]
Deja, tu risques de perdre ton temps car ce sont des urls, qui, meme si elle n'ont pas bougées depuis 5 ans, peuvent bouger demain. Et les favoris de Vstream sont dynamiques, pas fixes, un changement d'url, du nom du site, et tout devient invalide
Ensuite oui tu peux editer toi meme les databases, avec un editeur SQL (kodi eteint par contre, jamais en utilisation), mais c'est la solution de la derniere chance.
Pour scraper des sources avec le scraper de kodi, il te faut creer des fichiers STRM, possible en passant par la librairie, mais parait que c'est en panne avec la derniere version de kodi.

**Comment by Ovni-crea** [comment]
@TmpName  les fichiers STRM fonctionne sur la nouvelle version  c'est juste la section librairie qui est inaccessible depuis le menu principal de Vstream

**Comment by TmpName** [comment]
Ben je trouve ca plutot handicapant quand meme pour quelqu'un qui veuille utiliser cette fonction.
