### ISSUE TITLE
Vstream erreur de lecture

### ISSUE THREAD

**Issue by aya927** [Kodi-vStream/venom-xbmc-addons#2439]
Message d'erreur au lancement des vidéos Vstream

OS android - appareil : plusieurs modèles de box impactés - même symptôme ( mxq pro, X96 )

 - Version Kodi  17.6
- Version Vstream ( 0.6.9 )

Bonjour à tous, j'ai parcouru plusieurs topics mais n'ai pas trouvé de réponse, je m'excuse donc pas avance si jamais je suis en doublon.

Voici mon problème, j'ai déployer chez moi et chez quelques proches des boitiers android ( deux modeles : X96 - MXQ ), apres quelques temps d'utilisation de KODI/Vstream, les box sont une a une assujettis au même problème : lors du lancement d'une video/pendant la lecture, l'appli freeze ( ou pas ) et affiche " Erreur de Lecture - Veuillez vérifier votre journal de logs pour plus d'informations apparaît"

Par la suite impossible de relancer une video, peu importe la source.
Elles **semblent** toutes impactées, mais pour info j'utilise majoritairement uptobox avec un compte premium

Relance de l'appli, de la box, clean cash : idem
Suppression Vstream, KODI+ réinstallation : idem

Après plusieurs jours, certaines se sont remises à fonctionner correctement sans action supplémentaire
de ma part, et le problème est réapparu.

N'y connaissant pas grand chose, j'ai quand même jeter un œil aux logs et ce message d'erreur apparait lors de ma tentative de visionnage : 

08:10:09.478 T:18446744072583903520 WARNING: CPythonInvoker(34, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
08:10:12.168 T:18446744073123924256 WARNING: RunScript called for a non-script addon 'plugin.video.vstream'. This behaviour is deprecated.

Merci d'avance pour votre aide/retour d'experience !

Bonne journée

**Comment by TmpName** [comment]
Pas de chances, ces erreurs sont normales ^^.
Tu peux augmenter les logs dans les parametres de Vstream, mais en general les "WARNING3 ne sont pas vitaux. Il faudrait vraiment un log plus complet, ou un message d'erreur.

Par contre si tu passes tjours par uptobox jamais uptostream ?

**Comment by aya927** [comment]
Merci du retou ! au temps pour moi je voulais dire "uptostream" exclusivement.

Si c'est normal je ferme le sujet, je ferai un retour si je trouve quelque chose la dessus. ;)

**Comment by TmpName** [comment]
Alors oui c'est normal, il ya une slimitation de duree sur uptostream sans login.
Si tu depasses , ca coute, meme durant la video.
De memoire c'est 2h en gratuit, par contre si tu as un compte premium, il n'est pas uilisé (mais je sais plus pourquoi, parcequ'il est plus facile de passer par utptobox je pense, mais pas dispo sur tout les sites.)

**Comment by johngf** [comment]
si il est utilisé si tu veux simplement en mode gratuit ou erreur de login ça bascule auto sur upto stream meme si tu clic sur up tobox
