### ISSUE TITLE
Uptobox premium

### ISSUE THREAD

**Issue by Jojo31780** [Kodi-vStream/venom-xbmc-addons#2442]
Pb d authentification uptobox premium.

Tout les liens uptobox testés.

Systeme: fire stick tv Amazon
Kodi 17
Version vstream 0.6.92

Il m indique authentification ratée quelquesoit le lien uptobox tester.
Même pb uptobox/uptostream.

Merci pour votre aide.

**Comment by Jojo31780** [comment]
Erreur de ma part le site UPTOBOX est en maintenance.

**Comment by TmpName** [comment]
Vu le peu de reaction, je pense que tu es un cas isolé. Tu es sur d'avoir rentre les identifiant/mot de passe au bon endroit ? Tu passes pas par urlresolver ?

**Comment by johngf** [comment]
moi hier ça fonctionné pas en gratuit sur uptostream

**Comment by Jojo31780** [comment]
C etait une maintenance du site uptostream. Tout est ou. Merci
