### ISSUE TITLE
bug vstream sport spmc

### ISSUE THREAD

**Issue by jorandall62** [Kodi-vStream/venom-xbmc-addons#2443]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

bonjour,j'ai un souci avec vstream dans la catégorie SPORT.
lorsque je veux regarder un match en replay grace a " ROBIN DES BOIS "les liens ne fonctionnent pas  Sad
je m'explique (enfin j'essaie  Wink) à noter que j'ai installé KOdi sur mon pc et sur un boitier la par contre les liens de sports fonctionnent donc mon problème vient du fait que i'ai un vidéo projecteur ou  je ne n'ai pas pu mettre KODI mais le SPMC .
il y a quelque temps tout allais bien que ce soit sur pc , boitier ou video projecteur mais la dans le projecteur les liens  de sports dans vstream_robin des bois-- ne fonctionnent plus ! 
concernant les films tout est ok .
pouvez vous m'expliquer et surtout m'aider ?en espérant avoir était clair  Wink
merci d'avance

**Comment by TmpName** [comment]
Un exemple complet qui ne marche pas ?
Moi je viens de tester un truc en foot, et c'est parti sans prb.

**Comment by jorandall62** [comment]
Bonjour oui ça fonctionne sur mon pc avec kodi mais ça ne fonctionne plus avec mon vidéo-projecteur avec SPMC.
Lorque je fais  vstream-sport-robin des bois -ligue1-Dijon om-
J'ai une fenêtre qui s'ouvre en disant "erreur:connections failed. .

**Comment by TmpName** [comment]
Mais le prb c'est que si ca fonctionne sur PC, c'est que c'est pas un bug de Vstream.
Et comme SPMC est a l'abandon depuis 1 an, ca va etre dur de trouver de l'aide.
Un probleme de codec ? Telecharge une video qui deconne sur le pc et essayes de la lire sous SPMC.

**Comment by jorandall62** [comment]
Ah M...e !!! Je ne savais pas. 
Comment trouver une vidéo qui déconne ? Lol

**Comment by TmpName** [comment]
Ben une video qui marche sur l'un et pas sur l'autre, si tu as tes 2 machines avec les dernieres mise a jours, ca doit marcher pareil (apres c'est assez dur d'etre sur d'avoir les dernieres versions, ca n'apparait meme plus dans les logs)
