### ISSUE TITLE
Liste vide près chargement des serveurs

### ISSUE THREAD

**Issue by jmenand** [Kodi-vStream/venom-xbmc-addons#2446]
Bonjour, j'utilise vstream (bravo au passage😉) depuis la version 17 de Kodi.
N'étant pas un utilisateur averti, je le permet de poster mon problème ici.
Depuis la version 18 de Kodi, j'ai un soucis.
Par exemple si je fais une recherche sur vstream, les serveurs ont l'air de charger mais ma page de résultats est tout le temps blanche. Et ça pour toute tentative de recherche. L'indicateur me montre le chargement (de 1/20 en alliant jusqu'à 20, exemple) et la page suivante est vide.
J'ai un vpn géré par vpn manager qui démarre en boot. Mais j'avais le soucis avant de l'installer.
Voici le lien vers mon LOG vstream.
Je l'ai uploadé après tentatives avec et sans vpn
 Vous pourrez peut-être déjà comprendre ce qui se passe 😊 merci beaucoup par avance.
HTT PS://slexy.org/view/s2vFsBGGA

**Comment by TmpName** [comment]
Rebonjour ^^, par contre le lien marche deja plus , ca fait rapide quand meme pour qu'il soit supprime.
Ca deconne aussi sans vpn alors ?

**Comment by jmenand** [comment]
Bonjour, oui ça déconne sans. D'ailleurs c'est pour ça que j'en ai remis un
pensant que c'était parce qu'il n'y en avait pas que ça déconnait.
Sous 17 ça marchait très bien avec un vpn.
Désolé pour le lien vers le log, je ne sais pas pourquoi ça n'a pas pris.
Ou puis-je trouver le log vstream?merci

**Comment by TmpName** [comment]
Lod kodi     Windows Desktop: %APPDATA%\Kodi\kodi.log 
    Windows Store: %LOCALAPPDATA%\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\kodi.log
    Linux: $HOME/.kodi/kodi.log
    mac OS: /Users/<user_name>/Library/Application Support/Kodi/kodi.log
    Android: <data | sdcard | storage>/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
    iOS: /private/var/mobile/Library/Preferences/Kodi/kodi.log
    OpenELEC: /storage/.kodi/kodi.log
    OSMC: /home/osmc/.kodi/temp/kodi.log
    XBian: /home/xbian/.kodi/temp/kodi.log

Donc en resume ca marche avec la V17 et pas la V18 ?
Bon ben deja moi suis pas encore a la V 18^^.

**Comment by jmenand** [comment]
https://slexy.org/view/s2vFsBGGA

**Comment by jmenand** [comment]
https://pastebin.com/1GnFVK5K

**Comment by TmpName** [comment]
Alors pour le moment dsl mais.
1 - C'est quoi cette instal ? Tu es sur que tout ce que tu as installé est utile et encore compatible avec la V18 ?
2 - Pas vu une seule erreur au sujet de Vstream dans les logs
3- Gros soucis au niveau des meta data.

Moi ce que je te conseillerais, c'est de tout desinstaller, et repartir sur un truc propre. Il ya des dizaines de messages d'erreurs dans tout les sens, et aucun sur Vstream.

**Comment by jmenand** [comment]
Pour les metadata, je l'ai fait deux ou trois fois.
Sinon oui, j'avoue c'est le gros bazar.
Ne m'y connais pas trop encore, j'ai bêtement essayé d'installer des repos qui pourraient "éventuellement" m'aider à corriger certaines choses dans cette usine à gaz qu'est Kodi sans trop savoir tout ce que je fesais.
Indigo me propose un reset ou un Renuvenate. Pensez-vous que ça suffit où il faut que je me tape tout le truc avec noob. Je suis sous raspberry pi 3.
Merci.

**Comment by TmpName** [comment]
Ne jamais installer indigo, ou autre truc du meme genre qui sont sensé parametrer a ta place.
C'est ton appli, c'est toi qui la regle, et tu es le seul qui peux savoir ce qui a été modifié ou pas, quand tu sais pas, tu touches pas.
Moi je repartirais a zero, vu les degats. Ou meme mieux, si tu n'en a pas besoin, rester en V17.

Sinon j'ai commence a faire quelques recherches, tu es pas le seul a avoir ce type de probleme, ce serait des problemes de compatibilitée entre addons et leia, par contre je peux pas dire si le probleme vient de Vstream ou de la partie meta-data.

Si quelqu'un sous V18, pourrait me dire si il a les memes problemes ?

**Comment by jmenand** [comment]
Merci pour ces avis éclairés qui l'aident à avancer.😊
Je vais les prendre en compte.
J'avoue (c'est un peu HS désolé) que j'ai un du mal à m'en sortir avec tout ça...
J'étais très bien en V17 jusqu'à ce que je veuille installer Amazon Prime vidéo pour bénéficier sur la télé de mon compte prime. Pour ça il fallait passer en V18. 
Amazon Prime fonctionne très bien. Mais du coup je perd vstream. Je ne parle pas non plus du fait d'avoir du changer de provider vpn car l'ancien n'assurai plus la V18. Je suis revenu vers vous car vstream est le seul Addon que j'utilise, du fait de sa stabilité (avant que ça déconne😉).
On lis de tout comme conseils pour une bonne installation de Kodi sous raspberry et on se perds vite dans les avis de chacun. Bon, c'est aussi comme ça qu'on apprend...

**Comment by TmpName** [comment]
Attend un peu d'avoir d'autre reaction au sujet de la V18, mais de mon cote, pas pu l'installer non plus. Donc j'attend qu'il corrige leur truc.
Apres, je dirais que le probleme vient de Vstream (vu que petit a petit on a vire les addons externe), mais je trouve bizarre que tu sois le seul avec ce probleme.
Moi j'attendrais un troisieme avis.

Sinon pour une instal propre moi je testerais
```
sudo apt-get update
sudo apt-get install kodi
```

et pour desinstaller
`sudo apt-get autoremove kodi`

Mais je sais pas si ca va marcher pour les fichier utilisateurs

**Comment by jmenand** [comment]
En fait j'ai deux SD avec Kodi.

Une avec librelec : c'est sur celle-ci que je reporte mon soucis vstream
avec le Kodi log ci-dessus.
Kodi est en V18
Mon vpn fonctionne
Amazon Prime fonctionne

Une sur OSMC (install clean sans addons pourris) que je viens de ré essayer.
Et sur celle-ci vstream fonctionne (là sans vpn)! Càd que j'ai accès aux
listes de films. Par contre je ne me sens pas a l'aise pour lancer un film
sans vpn ...
Kodi est en 17.6
Le vpn me coupe ma connexion internet donc je l'ai viré
Je n'ai pas encore essayé Amazon Prime mais étant en Kodi 17....

Donc j'attends les autres avis en attendant.

Je rappel mon soucis vstream concerne une installation Kodi 18 sur Librelec.

**Comment by TmpName** [comment]
Et si tu passe en V18 sur la version propre (OSMC) ca marche ?

**Comment by tuego72** [comment]
pas besoin de vpn pour du streaming...

**Comment by jmenand** [comment]
OSMC ne propose pas encore de version stable Kodi 18 mais ça ne devrait pas
tarder.
J'ai fait un sudo apt-get dist-upgrade et rien de nouveau pour le moment.

Pourquoi peut-on se passer d'un vpn avec vstream ?
Je demande parceque ça serai là seule raison pour moi d'en avoir un...
Je n'utilise pas d'autres addons.

**Comment by TmpName** [comment]
Pas encore de loi pour ca, flou juridique.
C'est pas autorise, mais pas interdit.
En resume, c'est pas bien, faut pas faire, mais aucune amende/proces pour lire du streaming.
Tant que tu ne fais que voir une video, pas de telechargement, aucun probleme.
