### ISSUE TITLE
French stream pb sur vignette

### ISSUE THREAD

**Issue by higuelzim** [Kodi-vStream/venom-xbmc-addons#2450]
Bonjour à tous et à toutes, prière de noter que les vignettes sur French stream présentent un petit bug de flou, je pense juste que la résolution n’est pas adaptée
Par avance merci pour tous vos efforts 🙏🙏🙏

**Comment by TmpName** [comment]
Pas encore pu tester, site HS au 20/02

**Comment by TmpName** [comment]
Je viens de voir que @Arias800 a fait une grosse mise a jour dessus.
C'etait plus le meme site je pense, vu le nbres de modif, mais de mon cote plus de prbs.

**Comment by Arias800** [comment]
C'est pas moi qui a fait les modif c'est @razorex ^^

**Comment by razorex** [comment]
Oui j'ai refais french-stream . @higuelzim tu n'a surement pas la dernière version. En plus la résolution de la thumb dépend du site et quand il est possible de prendre mieux je fais comme pour dadyflix, hébergement sur tmdb des thumbs par exemple.

**Comment by TmpName** [comment]
Ha merde, lol, dsl, la force de l'habitude.
