### ISSUE TITLE
Télévision/Musique

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2451]
**Décrivez le bug**
les listes sont mis a jour mais vide a l'intérieur

**Votre system**
 - OS: [Windows, Android], les deux
-  Appareil [nvidia shield, Ultra] , android box et pc
 - Version Kodi  [16.17.18] (18.1)
- Version Vstream 0.7.0

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
voici comment voir ce petit problème : allez a l onglet Télévision/Musique,IPTV(Sites),IptvSource, ici peut importe l'ouverture d'une liste elle est vide(aucune information)  et pourtant se met a jour les listes , pourquoi ? , merci

**Comment by TmpName** [comment]
Je viens de tester. Protection cloudflare sur les liens, et pas de bol le code actuel est simplifié (on est jamais tombe sur cloudflare ici)

Now ca marche, mais la variable inf contient une chaine de caracteres au lieu d'un fichier, du coup la fonction
`for line in inf:`
prend la chaine lettre par lettre au lieu de ligne par ligne.

**Comment by KodiTopQuebec** [comment]
effectivement c'est revenu , merci

**Comment by TmpName** [comment]
Comment ca c'est revenu ??
J'ai pas fini ^^. on doit pas faire les tests au meme endroit.

**Comment by KodiTopQuebec** [comment]
avant lorsque je regardais dans les listes ca disait aucune information , et la j 'ai les listes de postes exemple backup liste 1 , backup liste 2 . j'ai pas regardé par contre aujourd hui

**Comment by TmpName** [comment]
Yep, mais ca deconne apres en fait.
La j'ai voulu retester, et ca passe plus par les memes fonctions, donc pas pu finir de reparer la fonction showeb().
Et la il me manquerait une etape, je passe de showDailyList a showAllPlaylist , mais le prb c'est que dans cette fonction je cherche avec les regex des infos qui serait une page apres.

**Comment by TmpName** [comment]
Bon je viens de tester, avec la version en ligne a ce moment, ca marche, (on passe de nouveau par showeb() )
