### ISSUE TITLE
qualité 1080p sur youtube

### ISSUE THREAD

**Issue by zombiB** [Kodi-vStream/venom-xbmc-addons#2452]
Bonjour à tous , 

Serait-il possible d'ajouter la qualité 1080 p et plus sur le hoster  youtube ?

cdt

**Comment by TmpName** [comment]
Je dis peut etre une connerie, mais on passe par un site externe keepvid, et je viens de tester leur site, pas pu avoir plus de 720p.
Donc soit je m'y prend comme un manche, soit faut passer par le plugin youtube.

**Comment by zombiB** [comment]
en suivant le lien `URL_MAIN = 'https://keepvid.app/videos?url='` j'arrive sur ce site `https://piratebay.help/videos?url=tg52up16eq0` dans la source on trouve la qualité 1080 
(td>High1080</td><td><i class="glyphicon glyphicon-ok)


est ce qu'on peut l'ajouter a vstream ?

**Comment by johngf** [comment]
de base vstream récup les liens disponible donc jusqu'a 720p 
>> pour les vidéos codé cipher genre vévo etc... il utilise un site keep_vid
>> le 1080p n'est jamais disponible directement video et audio séparé meme avec keep_vid 
donc possible oui >> l'addon youtube 
sur vstream une galère ajouté et adapté les libs pour le décodage etc.. ça vaut pas le coup

**Comment by TmpName** [comment]
Ha yep, si tu essayes de lire le lien recupere dans le code pour la qualite 1080, il n'y a pas de son.
