### ISSUE TITLE
Help sur les liens ed-protect

### ISSUE THREAD

**Issue by doberberto** [Kodi-vStream/venom-xbmc-addons#2453]
Salut les amis ! Je suis bloqué sur les liens (je ne sais plus quel site) protégés par ed-protect. Comment faire pour accéder au lien?... Ça ouvre une fenêtre dans laquelle on me demande de rentrer une adresse après avoir passer manuellement le capcha.... Merci d'avance !!! Bonne soirée.

**Comment by TmpName** [comment]
Alors je crois que c'est le mode d'emploi
http://www.vstream.ml/docs/recaptcha/

**Comment by Arias800** [comment]
Oui c'est ça le "mode d'emploi" même si ce n'en est pas réellement un puisque ç'est surtout un exemple de fonctionnement ^^

**Comment by doberberto** [comment]
Marche pas... En même temps ce sont des liens uptobox en 9 parties. Peut être pour ça..... Dommage

**Comment by TmpName** [comment]
Ha oui, si c'est en plusieurs partie, c'est des fichiers zip, pas video.

**Comment by FireFirstAce** [comment]
D'ailleurs petite question en rapport : est il possible de lire des fichiers rar ou zip ? Ils sont souvent compressés les fichiers sur AT maintenant...

**Comment by TmpName** [comment]
Non, pas  en streaming en tout cas.

**Comment by Arias800** [comment]
Ça dépend si ce sont des partit ou des fichiers rar complet ^^

**Comment by FireFirstAce** [comment]
Les fichiers complets justement. Les parties je me doute bien que c'est pas possible ^^
C'est pour ça que souvent ça marque fichier introuvable alors ? C'est que c'est pas lisible directement. Merci bien !

**Comment by Arias800** [comment]
Pour les fichier complet si c'est possible car python peux extraire le contenu d'une archive j'utilise déjà ça pour l'iptv ^^

**Comment by TmpName** [comment]
Yep, mais tu doit telecharger l'archive et l'extraire, c'est plus du streaming.

**Comment by Arias800** [comment]
Euh non de mémoire tu peux tout faire depuis la mémoire comme dans freebox.py ou alors si ça mets quelques chose sur l'ordinateur je n'ai pas trouver où x)

**Comment by TmpName** [comment]
Autant pour moi, tu m'a mit le doute.
Pour moi c'etait pas possible car les applications de base, ne peuvent pas t'ouvrir le fichier zip si il n'est pas entier.
Apparement ca a l'air de marcher, mais dans ce cas, pourquoi ce n'est pas fait d'office ? Peu de lecteur le supporterait ? Il suffirait de mettre application/zip, pour que firefox puisse lire le fichier sans probleme via http.

**Comment by johngf** [comment]
kodi c'est lire les archives normalement
