### ISSUE TITLE
Problèmes Replay sur Replay Tv et Top Replay.

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#2459]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Papounet58** [comment]
La plupart des replay ne fonctionnent plus.
Aucun liens dispo.
Je suis sur Kodi 18.1 sur box android.
Merci à vous.

**Comment by johngf** [comment]
top replay fonctionne et replay tv streaming déconne aussi sur le site lui meme quand tu clic sur lecteur

**Comment by Papounet58** [comment]
Oui

**Comment by Papounet58** [comment]
Depuis la mise à jour 0.71 le problème semble résolu en partie.
Merci à vous

**Comment by Papounet58** [comment]
Après analyse sur le site 
Replaytvstreaming.com,
je me suis rendu compte que certains liens Openload 
correspondent à des liens gérés par DRM
Etant en Belgique ce types de liens ne fonctionnent pas.

Bonne journée

**Comment by johngf** [comment]
non c'est parceque open load est hs

**Comment by Papounet58** [comment]
Hier certains liens fonctionnaient.
J'avais de plus testé sur le site à partir de mon PC.
Merci à vous
