### ISSUE TITLE
Bug suggestions de recherche

### ISSUE THREAD

**Issue by Brewyard** [Kodi-vStream/venom-xbmc-addons#2462]
Kodi crash quand je sélectionne une suggestion de recherche.

Android 
Mi box 3
Kodi 18
Vstream 0.7.0

**Comment by TmpName** [comment]
C'est ou la "suggestion de recherche" ?

**Comment by Brewyard** [comment]
Sur le menu de départ de Vstream,
Quand on sélectionne Recherche,
Là quand je tape le nom d'un truc il y a des suggestions qui apparaissent au dessus du clavier et quand j'en selectionne une ça plante et ça ferme Kodi

**Comment by TmpName** [comment]
???
Moi j'ai pas ca, et j'ai mis kodi 18 ce WE, tu aurais un screen ?

**Comment by johngf** [comment]
c'est un clavier android pas celui de kodi

**Comment by Brewyard** [comment]
D'accord alors désolé du dérangement, merci

**Comment by lebigboss** [comment]
J'ai le même problème sur PC avec Kodi 18.

**Comment by TmpName** [comment]
Tu aurais un screnn STP, car j'ai jamais vu cette option sur PC ? Du coup pour reproduire  ....

**Comment by lebigboss** [comment]
@TmpName C'est en bas, ça évite de taper tout en entier, mais je sais pas si ça vient pas de kodi
![screenshot_9](https://user-images.githubusercontent.com/12912677/54005245-07302000-4159-11e9-86c0-6ce52c1d50bb.png)
![screenshot_10](https://user-images.githubusercontent.com/12912677/54005252-0c8d6a80-4159-11e9-98ac-319666f0ced6.png)

**Comment by TmpName** [comment]
Alors la ....
Franchement ca pourrait etre le plugin, j'arrive a planter kodi avec 4/5 lignes de python. Mais moi j'ai pas ca du tout, c'est peut etre mit en place avec le theme, tu n'as pas un autre addon avec le clavier pr tester ?

**Comment by Arias800** [comment]
Problème deja rapporter au développeur de l'addon : https://github.com/phil65/plugin.program.autocompletion/issues/12

**Comment by lebigboss** [comment]
Ok donc ça vient bien de kodi
