### ISSUE TITLE
Problème de mise a jour avec FTMC

### ISSUE THREAD

**Issue by fiahaze5000** [Kodi-vStream/venom-xbmc-addons#2463]
Bonjour, utilisateur d'une box Android h96 pro + sous Android 7.1.2 avec une custom rom de Freaktab.com 

Je vous explique le problème, sous Android et avec cpu arm il y a des problème de codec par exemple avec vstream openload a des freeze d'image ça dépend des plateformes vidéo avec Kodi officiel alors freaktab (superceleron) a créér FTMC qui résout tout les problème codec et vidéo sous Android malheureusement il y a un seul et unique problème les mises a jours mettent parfois 5-6 jours pour apparaître dans le menu principal de vstream, je dispose aussi de Kodi 18 et je les reçoit instantanément j'ai essayé avec SPMC et je les reçoit instantanément aussi. J'ai essayé de télécharger 0.7.1 et l'installer manuellement mais sans résultat. 

Pouvez-vous m'aider ? Avez vous une solution ?  Je pense a un conflit de dépendance déjà présent sur FTMC mais je ne peux pas déactiver les dépendances système déjà implanté dans FTMC

**Comment by TmpName** [comment]
Les mises a jours peuvent mettre jusqu'a 3 jours pour apparaitre, meme si elle apparaissent directement sur une autre machine.

**Comment by fiahaze5000** [comment]
merci pour votre réponse extrêmement rapide. 

1 seul machine mais avec 3 versions de kodi ( Kodi 18.1 , FTMC et spmc ) mise a jours instantané sur Kodi 18 et spmc et rien avec FTMC. Je viens de réinstaller FTMC et vstream entièrement pour avoir la mise a jour 0.7.1 mais à la prochaine update rebelote, vraiment aucun moyen d'installer manuellement les mises a jour ? 

Pouvez vous aussi m'expliquer comment enregistrer sur firstone ? Comment écrire la date exemple 18:23 7-03-19 ? Ou 18:23-7/03/19 ? Que mettre dans ffmpg2 mais aussi comment créer le dossier ou se placeront les enregistrements ? J'ai lu un article sur le sujet mais il est plutôt ancien. Si vous pouviez m'aider a faire fonctionner les enregistrements ce serrait vraiment parfait !

Un grand merci pour votre travail vstream est vraiment une tuerie !!! 4 ans d'utilisation je ne saurais plus vivre sans c'est Noël tout les jours grâce a vous !

**Comment by johngf** [comment]
pour ton soucis de mise a jours des que tu réinstalle vstream ou clic sur mise a jour dans le menu (parametre ou info)  settings plus ça décalle la prochaine maj
n'y touche plus et attend la prochaine si rien probleme de cache

**Comment by fiahaze5000** [comment]
Merci pour ta réponse ! J'attend toujours de voir la mise a jour dans le menu d'accueil de vstream je ne passe jamais par le menu information et même si j'y vais pas de mise a jour. J'ai ce problème uniquement avec FTMC c'est embêtant mais malheureusement c'est la seul version dérivée de Kodi qui fonctionne parfaitement sur les box Android avec cpu arm. J'ai le choix ou la vidéo plante sur certaines plateforme vidéo mais les mises a jour arrivent directement avec Kodi ou j' ai aucun problème de vidéo mais je reçois pas rapidement les mise a jour qui réparent les bug avec FTMC et sur mon pc c'est parfait avec Kodi mais malheureusement je sais pas l'utiliser dans mon salon. J'aimerais résoudre ce problème et rendre parfait le fonctionnement sur FTMC. Ajouter un possibilité de mettre a jour manuellement me conviendrait très bien. Merci d'avance.

**Comment by TmpName** [comment]
Je viens de me souvenir, dans les options "A propos / sources", tu as la date de la derniere MAJ, avec la version pour comparer, si la difference est inferieure a 3 jours, c'est normal.

**Comment by fiahaze5000** [comment]
J'ai regardé tantôt avant de tout réinstaller il m'indiquait 0.7.0 alors que sur Kodi j'étais déjà en 0.7.1 je ferai attention la prochaine fois et j'attendrai 3 jours mais j'ai déjà du attendre 5-6 jours. Je me serre de Kodi uniquement pour voir si une mise a jour est disponible le problème ne peut pas venir du fait que j'ai Kodi + FTMC sur le même appareil ? Comme je viens de faire une installation propre j'espère que cela résoudra peut-être le problème ça fait pas loin d'un an que je met a jour sans réinstaller heureusement j'ai fait un backup et importer pour retrouver mon historique et marque page. 

Pour l'enregistrement je dois aller poser les questions sur la bonne discussion ou c'est simplement plus possible ?

**Comment by TmpName** [comment]
Apres comme dit @johngf y a parfois des soucis de cache, Vstream se souvient de la page et ne la met pas a jours, jamais compris pkoi, ni comment.
Et non je pense pas, en fait on compare juste 2 dates et en fonction on affiche ou pas l'icone, a chaque affichage de la page "home"

Pour l'enregistrement, je m'en suis jamais servi, je crois que c'est @Arias800 qui maitrise le truc,

**Comment by fiahaze5000** [comment]
Je suis actuellement dans informations sur l'extension / configurer / enregistrement 
J'ai activé l'enregistrement mais où trouver le ffmpeg et je sais pas trop comment écrire le chemin sur Android j'aimerais le placer dans le stockage externe (les dossiers accessible sans Root même si j'ai aussi accès a la racine la box est rooté) ou on trouve le dossier download sur Android ou sur une carte sd. 
J'ai aussi besoin de savoir comment écrire le chemin pour le chemin enregistrement. Sur Windows je suppose que ça ressemblait à c:/user/document/enregistrement par exemple mais sur Android aucune idée peut-être mnt/sdcard/enregistrement.

**Comment by fiahaze5000** [comment]
Pour les mises a jours j'ai vidé le cache de FTMC dans paramètre / application / FTMC avant de réinstaller et aussi dans informations sur l'application / configurer / outils mais ça n'a absolument rien changer la mise a jour ne m'était quand-même pas proposer. 
 
Pour les enregistrements j'espère avoir un éclaircissement de arias800 Utile et très très intéressant pour ma part.

**Comment by Arias800** [comment]
Alors bon c'est vrai que j'ai pas encore fait de guide détailler car c'est une option qui n'est pas encore finit  car je ne l'ai pas tester sur d'autre plateforme que sur mon pc sous Windows. Alors voila quelque information : 
- Pour ffmpeg il y a un projet sous Android qui existe mais comme dit précédemment je ne l'ai pas tester donc je ne peux pas dire si il fonctionne correctement ou pas : [ffmpeg](https://github.com/tanersener/mobile-ffmpeg)
- Ensuite pour le chemin ça a l'air de bien être celui la `/mnt/sdcard/enregistrement `
- Pour écrire le chemin je n'ai pas trouver d'autre solution que de l'essayer l'utilisateur le rentrer a la main (je sais c'est pénible mais j'ai pas trouver autre chose pour le moment) ^^

**Comment by fiahaze5000** [comment]
> Alors bon c'est vrai que j'ai pas encore fait de guide détailler car c'est une option qui n'est pas encore finit car je ne l'ai pas tester sur d'autre plateforme que sur mon pc sous Windows. Alors voila quelque information :
> 
> * Pour ffmpeg il y a un projet sous Android qui existe mais comme dit précédemment je ne l'ai pas tester donc je ne peux pas dire si il fonctionne correctement ou pas : [ffmpeg](https://github.com/tanersener/mobile-ffmpeg)
> * Ensuite pour le chemin ça a l'air de bien être celui la `/mnt/sdcard/enregistrement `
> * Pour écrire le chemin je n'ai pas trouver d'autre solution que de l'essayer l'utilisateur le rentrer a la main (je sais c'est pénible mais j'ai pas trouver autre chose pour le moment) ^^

Un grand merci pour ta réponse rapide arias ! Tu peux aussi me passer le ffmpeg pour Windows stp si il est différent ? Je vais essayer aussi sur mon pc. 

J'ai aussi besoin de connaître le format date et heure comment l'écrire exemple 17:54 08/03/2019 c'est correct ? 

Donc je place le ffmpeg dans un dossier et j'inscris les chemins dans paramètre pareil pour le chemin où se placeront les enregistrements ? 

Un grand merci Arias800 tu gères ! Vous êtes vraiment des gars super je suis vraiment agréablement surpris sur d'autres forum on n'a même pas de réponse.

**Comment by Arias800** [comment]
Pour Windows ffmpeg c'est ici : https://ffmpeg.zeranoe.com/builds/
Pour le format normalement c'est tout indiquer au dessus du clavier donc normalement tu devrai avoir les info en temps voulu mais au cas ou voila les format : 
- Pour l'heure du début : `Date-Heure-Minute`
- Pour l'heure de fin : ` Heure-Minute`

Ensuite voila il te suffit de mettre les chemins et normalement tout devrai fonctionner correctement
Après pour les réponse je fait du mieux que je peux vu que je suis en période d'examens  ^^

**Comment by fiahaze5000** [comment]
> Pour Windows ffmpeg c'est ici : https://ffmpeg.zeranoe.com/builds/
> Pour le format normalement c'est tout indiquer au dessus du clavier donc normalement tu devrai avoir les info en temps voulu mais au cas ou voila les format :
> 
> * Pour l'heure du début : `Date-Heure-Minute`
> * Pour l'heure de fin : ` Heure-Minute`
> 
> Ensuite voila il te suffit de mettre les chemins et normalement tout devrai fonctionner correctement
> Après pour les réponse je fait du mieux que je peux vu que je suis en période d'examens ^^

Donc 08/03/19-18:13 pour le début et 18:25 pour la fin si j'ai bien compris ? Correcte ?

Je vais chipoter un peu et essayer ça ce soir je donnerai un feedback. 

Raison de plus de te remercier je te souhaite bonne merde pour tes examens !

**Comment by Arias800** [comment]
Pour ton exemple ça donne : 08-18-13 car Jour-Heure-Minute (j'ai mis Date alors que j'aurai du mettre jours ) et pour la fin c'est 18-25 c'est important de mettre le "-" entre les nombre . Le chemin tu doit le mettre dans les paramètre et après c'est Vstream qui gèrent tout ^^

**Comment by fiahaze5000** [comment]
> Pour ton exemple ça donne : 08-18-13 car Jour-Heure-Minute (j'ai mis Date alors que j'aurai du mettre jours ) et pour la fin c'est 18-25 c'est important de mettre le "-" entre les nombre . Le chemin tu doit le mettre dans les paramètre et après c'est Vstream qui gèrent tout ^^

Ok c'est bien clair je te transmets rapidement un feedback encore un grand merci !

**Comment by fiahaze5000** [comment]
@Arias800 pour que l'enregistrement fonctionne il faut démarrer la chaîne ou pas besoin ? 

Pour le titre il faut écrire de cette manière game-of-thrones ? 

Je viens de faire mon premier essai mais pas d'enregistrement dans le dossier enregistrement.

**Comment by fiahaze5000** [comment]
@Arias800 voilà je viens de faire 3 essais sur Android le dossier enregistrement est présent dans librairie j'ai tout fait comme tu me l'a conseillé j'ai reçu un message me demandant de redémarrer Kodi après avoir programmé l'heurebde début et fin mais rien dans le dossier enregistrement je vais essayer sur Windows.

**Comment by Arias800** [comment]
Pas besoin de démarrer la chaine pour que cela fonctionne.
Pour le titre il n'y a pas de format particulier il ne faut pas par-contre mettre de caractere spéciaux car sinon  ça risque de poser probleme pendant la création du fichier vidéo donc pour ton exemple mettre  `game of thrones` suffit .Car il y a un format obligatoire pour l'heure car il me permets de calculer la durer de l'enregistrement ^^

**Comment by OroJJ** [comment]
Bonjour, je viens vers vous suite à un problème après la MàJ vstream 0.7.1. (désolé si je suis pas au bon endroit mais mon problème ressemble à celui au dessus).
Je détiens deux raspberry pi3 sous kodi17.
Voilà depuis la MàJ automatique d'hier 0.7.1 aucun lien ne fonctionne.
J'ai vider tous les caches comme dis plus haut, toujours rien, je l'ai désinstallé et réinstaller avec le repository 0.3, aucun succès non plus.
Par contre quand je vais sur information de vstream il y a bien marqué 0.7.0 dans version mais quand je suis sur configurer=> A propos/Sources il me dis version 0.7.1 dérniere MàJ le 08/03/19 vers 13h.
J'ai mis le patch de ludupotte 2.84 en ésperant une amelioration et toujours rien.
Du coup j'ai pas fais la MàJ sur mon autre rasp pi3 qui a bien la version 0.7.0 et qui fonctionne très bien.
Merci d'avance pour votre aide

**Comment by TmpName** [comment]
Y aurait moyen d'avoir un log ?

**Comment by fiahaze5000** [comment]
> Pas besoin de démarrer la chaine pour que cela fonctionne.
> Pour le titre il n'y a pas de format particulier il ne faut pas par-contre mettre de caractere spéciaux car sinon ça risque de poser probleme pendant la création du fichier vidéo donc pour ton exemple mettre `game of thrones` suffit .Car il y a un format obligatoire pour l'heure car il me permets de calculer la durer de l'enregistrement ^^

D'accord merci je vais refaire des essais aujourd'hui, je demandais pour le titre parceque avec les boîtier IPTV mag il faut laisser la chaîne tourner et le titre s'inscrit avec des - entre chaque mots. 

Pour le ffmpeg il faut le décompresser ou pas ? Peut être mettre le dossier racine contenu a l'intérieur du .zip dans le dossier créér ffmpeg j'ai essayé avec le ffmpeg compressé et décompressé mais décompresser j'ai un sous dossier avant d'accéder à la racine. 
 Je me demande si l'erreur vient pas des chemins j ai remarqué du buffering anormal a l'heure des programmations ce qui me fait penser a un travail en cours mais pas d'enregistrement physique après l'heure d'enregistrement dépassée. Je vais essayer aujourd'hui sur Windows également. encore merci pour ton aide.

**Comment by OroJJ** [comment]
Voila pour une partie du log, désolé impossible de récupérer le fichier en lui même, j'ai fais comme j'ai pu ^^ En espérant que ça puisse vous aider.
![20190309_150925](https://user-images.githubusercontent.com/48377295/54072652-30969c00-427e-11e9-97ae-8e0d90a86e6a.jpg)

**Comment by TmpName** [comment]
C'est pas Vstream qui deconne chez toi mais urlresolver.

**Comment by OroJJ** [comment]
ah je viens de trouver pour le log complet 
https://slexy.org/view/s2uZa0ioLC

**Comment by OroJJ** [comment]
ah mince pourtant tout fonctionnait parfaitement avant la MàJ

**Comment by OroJJ** [comment]
c'est bon j'ai trouvé grâce à toi, tu avais bien raison, j'ai mis à jour mon URL Resolver et tout refonctionne à nouveau, merci beaucoup pour ta rapidité de réponse, vous êtes au top, encore merci.

**Comment by fiahaze5000** [comment]
@Arias800  voilà le message que je reçois quand l'enregistrement démarre

**Comment by fiahaze5000** [comment]
@Arias800  j'ai essayé sur Windows j'ai placé le ffmpeg 64bit dans documents et aussi le dossier enregistrement  les chemins sont bons dans paramètre vstream quand le l'enregistrement démarre je reçois un message de Windows comment voulez vous ouvrir le fichier .py j ai essayé avec le ffmpeg en .Zip ou décompresser pareil ça n'enregistre pas et message du .py
Dans ton premier tuto il faut remplacer des XML c'est toujours d'actualité ? J'ai pas suivi les étapes de ton premier tuto il fallait ?

**Comment by Arias800** [comment]
Ton 1er essayer est le bon mais il faut essayer d'installer python 2 car je pensais que c’était l’interpréteur de Kodi qui lisais le .py mais visiblement non : https://www.python.org/downloads/release/python-2716/
Il n'y a rien a remplacer du tout c'est tout automatique tu a juste a régler les paramètre , programmer l'enregistrement et redémarrer la suite ce fait tout seul ^^
