### ISSUE TITLE
Bug FreeTelechargement et FullStream

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2464]
Salut

Sur Fullstream les liens ne s'affichent pas (La version avec le menu Netiflix)
![screenshot_13](https://user-images.githubusercontent.com/12912677/54007373-afe27d80-4161-11e9-9703-970b698f3d01.png)
![screenshot_11](https://user-images.githubusercontent.com/12912677/54007391-b7a22200-4161-11e9-9cce-03c2ec589172.png)

Sur Freetelechargement il n'y a que les 2 liens encadrés qui fonctionnent dans le menu FILMS
![screenshot_12](https://user-images.githubusercontent.com/12912677/54007435-00f27180-4162-11e9-886e-0d96314f51a5.png)

**Comment by TmpName** [comment]
1 er bug corrige, juste un prb d'url.

**Comment by lebigboss** [comment]
@TmpName Non, il fonctionne
Par contre ce qui est bizarre c'est que les raccourcis sur le script fonctionnent sur le site mais pas sur kodi.
ça charge bien la page mais ça reste sur le menu FILMS 
![Screenshot_16](https://user-images.githubusercontent.com/12912677/54058606-a5be8e80-41f6-11e9-89e8-ed1522f487bd.png)

**Comment by TmpName** [comment]
Tu as teste avec le fichier que j'ai corrigé hier ?
Sinon chez moi le site fonctionne, mais affiche n'importe quoi.

**Comment by lebigboss** [comment]
@TmpName Je viens de testé ton fichier et ça fonctionne merci, même les catégories Manga et autres
