### ISSUE TITLE
Coupler assistant Google Android TV avec la recherche vstream + idée hybridation vavoo vstream

### ISSUE THREAD

**Issue by fiahaze5000** [Kodi-vStream/venom-xbmc-addons#2466]
Salut a vous les As, depuis que j'ai apprit a la sortie de Kodi 18 qu'il était possible de coupler l'assistant Google en recherche de film sur Google play et Kodi pour pour avoir cette proposition dans Google assistant il faut avoir le film physiquement sur Kodi sinon le film est uniquement proposer sur Google play pensé vous qu'il serait possible de coupler Google assistant avec la recherche vstream ? Ce serrait vraiment pas mal du tout ! 

Une autre idée me trotte dans la tête connaissez vous vavoo ? Ils ont prit le squelette de Kodi et ils ont créé quelque chose de vraiment pas mal a leurs sauce malheureusement en allemand mais pensez vous qu il serrait possible de reprendre leurs squelette et la remplacer par vstream ? Ce serrait pas mal non plus même si ça me convient déjà très bien actuellement simple idée que je partage.

**Comment by lebigboss** [comment]
Sur kodi la recherche vocale fonctionne avec vstream, j'ai tester avec une Nvidia Shield et quand on lance une recherche sur Vstream au lieu de tapé un titre on reste appuyer sur le bouton OK de la télécommande et ça active la recherche vocale. Donc, tu dis avec la voix genre "Games Of Thrones" et ça écrit automatiquement sur la recherche.
Je sais pas si c'est de ça que tu parle

**Comment by fiahaze5000** [comment]
> Sur kodi la recherche vocale fonctionne avec vstream, j'ai tester avec une Nvidia Shield et quand on lance une recherche sur Vstream au lieu de tapé un titre on reste appuyer sur le bouton OK de la télécommande et ça active la recherche vocale. Donc, tu dis avec la voix genre "Games Of Thrones" et ça écrit automatiquement sur la recherche.
> Je sais pas si c'est de ça que tu parle

Non ce n'est pas  ça mais tu m'apprend quelque chose malheureusement moi c'est une box chinoise et pas la Shield ce dont je parle la recherche ce fait sur le menu principal Home d'Android TV avant meme d'ouvrir kodi voilà une vidéo qui montre le couplage Android TV Kodi depuis Leia. 

https://youtu.be/4U_Xmsn_avg

**Comment by lebigboss** [comment]
@fiahaze5000 Ok, mais bon c'est une recherche qui se fait sur une médiathèque déjà présente, je vois pas comment ça pourrait être intégrer à Vstream
ça coûte rien de demander

**Comment by fiahaze5000** [comment]
> @fiahaze5000 Ok, mais bon c'est une recherche qui se fait sur une médiathèque déjà présente, je vois pas comment ça pourrait être intégrer à Vstream
> ça coûte rien de demander

Oui c'est ce que j'explique au début du post mais je le suis mal expliqué, c'est pour ça que je demande si éventuellement ce serrait possible de coupler Google assistant et la recherche vstream ce serrait franchement pas mal !

**Comment by Arias800** [comment]
A mon avis c'est pas faisable car ça a l'air d’être intégrer a Kodi directement donc impossible a modifier via des script python ^^

**Comment by TmpName** [comment]
Je pense aussi, a moins que la dev kodi propose des apis pour ca, pas possible.

Sinon je vient de regarder vavoo, et je ne peux que les encourager, meme si je ne le testerais pas car aussi lourd que kodi (> 50 Mega) et apparement encore moins stable, mais dans le futur je dis pas.

**Comment by lebigboss** [comment]
Si c'était an anglais ça serai bon mais là, de l'allemand.
A part les insultes je connais rien d'autre

**Comment by fiahaze5000** [comment]
> Si c'était an anglais ça serai bon mais là, de l'allemand.
> A part les insultes je connais rien d'autre

L'anglais est aussi disponible j'ai réussi a installer le language en français aussi mais malheureusement rien en français sauf un serveur TV

**Comment by fiahaze5000** [comment]
Ça coûtait rien de proposer les idées je vous remercie d'avoir jeté un coup d'œil et d'avoir répondu !
