### ISSUE TITLE
ExtremeDown aucun lien catégorie (Séries,Manga)

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2467]
Salut, en faite ça concerne le py de @Arias800 , pour passer le recaptcha de extremedown.
Dans la catégorie film ça fonctionne, on voit bien les liens une fois qu'on clique sur le film mais pour les séries ça n'affiche rien
C'est à partir de ce menu que ensuite ça n'affiche rien
![Screenshot_17](https://user-images.githubusercontent.com/12912677/54077403-f77b1d80-42b7-11e9-876f-469fa8328d13.png) 

Par contre j'ai pas trouver aussi, ou je pouvais ajouté mon token alldebrid dans le script, j'ai bien mis le fichier settings.xml mais ou mettre le token ? Merci

**Comment by Arias800** [comment]
Voila la liste des corrections : 
- Correction de la recherche
- Ajouts d'une option pour automatiquement recuperer le token AllDebrid
- Correction bug d'affichage pour les serie

Voila le fichier : https://github.com/Arias800/Fichier-divers/blob/master/extreme_down.py

**Comment by lebigboss** [comment]
@Arias800  Fonctionne super bien et l'affichage des liens est meilleur
Merci

**Comment by Arias800** [comment]
Bon du coup je profite de ce poste pour dire que j'ai pull la nouvelle version d'extreme download dans la beta de Vstream ^^
