### ISSUE TITLE
Problème gêneral vstream sur les lien 

### ISSUE THREAD

**Issue by huitcentsix** [Kodi-vStream/venom-xbmc-addons#2468]
Salut à tous, voilà, j'ai un soucis depuis la version 0.7 et 0.7.1 :

Vstream fonctionne correctement à première vu dans son ensemble, rien à dire sur ça.
Voici un exemple lambda de mon probleme:

Je vais dans vstream/sources/ZT (peu importe le répertoire disons films derniers ajout) /je sélectionne n'importe quel film/ça charge comme d'hab/les liens des différents hebergeurs s'affichent et quand je clique sur, exemple, le lien uptobox/qualité du lien (hdrip, webdl, HD light etc) rien ne se produit. 

Ça charge 2sec (la roue bleu) et ca reste sur le même affichage. Ça ne va pas plus loin, aucun message, aucune fenêtre, aucun chargement après le premier qui est très bref. Je reste sur la page du lien et voilà. 

Et ça, ça le fait sur tous les sites, peu importe les sources... Ca ne me l'avait encore jamais fait et ça fait 2 semaines voir plus que ça dur. (j'attendais la mise à jour 7.1 mais c'est toujours pareil) 

Je suis sur 
 - OS: libreElec 8.2.5
-  Appareil : raspberry pi3
 - Version Kodi : 17.6 (13/04/18)
- Version Vstream : 0.7.1 

Voila merci d'avance, je ne sais pas si j'ai bien éclairci mon problème ! Et je précise que je suis novice et n'y connais rien en programmation / log etc

**Comment by lebigboss** [comment]
Ça vient peut être de ton debrideur. Regarde tes réglages

**Comment by huitcentsix** [comment]
Merci d'avoir répondu.
Pour ce qui est du débrideur je passe par resolver avec real debrid. Il est config comme d'hab et je refresh (ré autorise) l'acompte souvent...

Il faut peut être faire une mise à jour ? J'en avait fait une manuel y'a un mois il me semble

**Comment by lebigboss** [comment]
J'ai justement un problème avec urlresolver aujourd'hui, là version 5.0.30.
Peut être un problème d'API, je verrai ça plus tard

**Comment by TmpName** [comment]
Regarde juste tes logs, avec un simple editeur de texte, et regardes le message d'erreur. Ja pense que @lebigboss a raison, quelqu'un a eu le meme probleme ya quelques jours.

Android
Remarque: Le premier dossier peut être différent sur différents périphériques:

Windows
%APPDATA%\Kodi\kodi.log
MacOS
/Users/ /Library/Logs/kodi.log
IOS / ATV2
/private/var/mobile/Library/Preferences/kodi.log
Linux
$HOME/.kodi/temp/kodi.log

**Comment by lebigboss** [comment]
Moi ça refonctionne, dans le doute j'ai DL la Dernière version de urlresolver sur le repo fusion, ça ne propose pas la maj il faut le faire manuellement, je suis passé du 5.0.30 au 5.0.32, je les deux fonctionne pour l'instant.
Moi je suis chez Alldebrid

**Comment by huitcentsix** [comment]
Merci à vous 2 !
Je vais regarder ça dès que j'ai un peu de temps et je vous tiens au courant histoire d'être sûr que ça vient de là.

**Comment by huitcentsix** [comment]
Yep! 
Bon c'était bien un problème d'URLresolver. Ca ne marche plus avec la dernière version du repo supremacy 2.6 
Du coup j'ai test avec le repo fusion 5.0.32 et c'est nickel :) (je ne l'avais pas) 
Merci lebigboss

**Comment by FireFirstAce** [comment]
Bonjour
Je me permets de rebondir sur ce sujet avec un problème similaire. 
Depuis pas mal de temps sur beaucoup de liens surtout uptobox j'ai des soucis et je n'arrive pas à lire le fichier alors que ce dernier est valide (testé sur navigateur) 

Par exemple ce lien pour un épisode de walking dead https://uptobox.com/y2kiqxk7qbp8
Lorsque je le lance via uptostream, je choisis la qualité du stream et derrière rien ne se passe, pas de message d'erreur juste un message comme quoi les sous titres sont correctement chargés.
Ce n'est pas un soucis de temps de lecture en non premium dépassé puisque je réussis à lancer d'autres liens.... 

Une idée ? Kodi 18 et Vstream à jour bien entendu 😉

Merci par avance

**Comment by TmpName** [comment]
Tu pourrais nous faire parvenir les logs stp ?
Et si tu en prend un sans sous titres, ca fonctionne ? (vu que tu as pu lancer d'autres liens).
En fait ca passe quand c'est up2strm en direct, et ca deconne pour les lines up2box convertis en up2strm ?

**Comment by FireFirstAce** [comment]
J'ai essayé de refaire le bug depuis le kodi installé sur mon téléphone (je suis pas chez moi)
Voici mon lien vers le log normalement : https://slexy.org/view/s21e9uMbIp

C'est hyper aléatoire comme problème ça dépend vraiment des liens j'ai pas encore su dire à quel moment ça me le faisait je vais creuser ça si le log suffit pas. 
C'est vraiment juste le lancement de la vidéo qui se fait pas. 
Et j'ai pas urlresolver. J'ai juste un compte premium 1fichier et je suis enregistré sur uptobox (donc 2h30 de visionnage par jour)

**Comment by TmpName** [comment]
Il me faudra tester le meme fichier de mon cote, mais ca a l'air d'etre un prb de timeout.

**Comment by Gayed92** [comment]
Bonjour j'ai la fibre depuis 15 jours et j'étais content j'attends depuis 10 ans mais galère sur vstream c'est lent à charger et les source zt ouvre bien la page des de séries mais si je clique dessus ça essai et ça indique erreur j'ai essayé sur d'autres pareil ! J'utilise vpn unlimited depuis 6 mois jamais eu de problème en adsl sauf quand et était out ! Avez vous ce problèmes ? J'ai essayé sans vpn mais la j'arrive pas a du tout à ouvrir zt ! J'ai testé plusieurs serveur vpn différents pays idem ! J'ai jamais utilisé Url resolver car pas nécessaire sur zt et 1fichier ou je suis abonné ! Merci

**Comment by Gayed92** [comment]
Merci pour l'info !

**Comment by TmpName** [comment]
Salut, tu as testé le site via navigateur ?

**Comment by Gayed92** [comment]
Bonjour non j'ai pas de pc je regarde sur la clé Amazon fire 4K mais je pense que ça doit fonctionner le site zt fonctionne

**Comment by Gayed92** [comment]
Bon je viens de testé depuis mon téléphone j'arrive à télécharger sur zt et 1 fichiers
