### ISSUE TITLE
Google Home et marque pages

### ISSUE THREAD

**Issue by B4rtux** [Kodi-vStream/venom-xbmc-addons#2469]
Bonjour, voilà j'ai acquis une Google Home Mini, et une Alexa, et je souhaite utiliser Google Home pour contrôler mon Kodi, ce que j'arrive à faire aisément pour le moment, mais j'aimerais pousser le vice, car dans VSTREAM, j'ai ajouté dans mon marque pages, pleins de Disney HD, et j'aimerais, via Google Home, lancer un film présent dans mes marques pages et non faire une recherche à travers le plugin pour trouver des liens. J'ai vu qu'il y avait eu un topic pour faire une recherche vocale dans vstream, mais pour trouver un film déjà présent dans les marques pages non.

Aidez moi s'il vous plaiiiiiit

Cordialement :)

**Comment by TmpName** [comment]
Meme reponse que dans l'autre issue.
C'est pas Vstream qui gere ca, et pas d' API propose pour.
A voir si kodi propose de faire des raccourcis claviers, via la commande vocale par exemple.

**Comment by Arias800** [comment]
Pour Google home I'm y a déjà eu une discussion par rapport a ça et il me semble qu'il vais réussit https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1966

**Comment by reecord** [comment]
Salut ! 
Un merci à tous pour avoir fait remonter ce post ! 
La solution donnée par @thib5 (ainsi que par tous les autres membres du post #1966 ) sur le post cité par @Arias800, m'a permis de l'intégrer avec mon google Home via IFTTT ! 
Le top !

**Comment by B4rtux** [comment]
Oui mais le soucis c'est que je ne parviens pas à accéder à un endroit en particulier

**Comment by thib5** [comment]
Moi je l’utilise pour lancer une recherche j’imagine qu’on peut le modifier. Je ne me souviens plus dutout de mon code faudrait que je regarde.... Aussi je me souviens que je passait la commande via IFTTT puis un script sur mon serveur de domotique pour ne pas pas ouvrir kodi directement sur le web

**Comment by B4rtux** [comment]
Parce que ca pourrait être vachement interessant plutôt que de chercher dans la bibliothèque personnelle
