### ISSUE TITLE
Series streaming watch hs

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2471]
Bonsoir 
Suite a une modif de vstream aujourdui le site serie streaming watch ne fonctionne plus :contenu vide

Pour reproduire le bug c'est de chercher la serie Shadowhunters et la le contenu ne montre aucun lien
Sur un smartphone les fichiers du github du 13 mars me permet de voir les liens mais sur une box la maj manuel avec les fichiers du 14mars aucun lien 

Merci

**Comment by razorex** [comment]
Reglé par @johngf .

**Comment by Che-debarras** [comment]
Merci mais la correction ne semble pas etre mise sur le github je me trompe? Car le probleme est tjrs la. Merci

**Comment by johngf** [comment]
si mais quand tu fait un copier coller faut cliquer sur le bouton raw
si du dl le fichier (firefox) clic droit sur raw enregister sous normalement il doit remplacer l'ancien

**Comment by Che-debarras** [comment]
Je sais comment mettre a jour manuellement
Tu dis avoir réglé le bug mais le fichier n a pas été modifié 
J'ai quand meme télécharger et copier coller mais le bug toujours là 
Jai remis les fichiers du 13 mars car ceux du 14 et 15 mars me donne le bug
Peut etre puis je prendre que le fichier. Py de la source et je fais copier coller ? Si oui c'est dans quel dossier de vstream?

Merci

**Comment by Che-debarras** [comment]
Merci j'ai mis a jour manuellement avec les fichiers d'aujourd'hui  et j'ai copier-colleé le fichier .py du 13 mars et ça remarche.

Du coup c'est pas plus simple de remplacer ce fichier de la source sur github pour que tout le monde en profite ?

Ce fichier serie.streaming.watch.py du 14 mars aujourdui ne fonctionne pas du.

Merci encore pour ton aide
