### ISSUE TITLE
Streaming.serie.cx

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2473]
Un bug avec cette source affiche erreur 404
On a accès a la liste des series et les episodes mais pas de lien 
Jai vérifié sur le site dpstreaming.to (il a changé de nom apparemment.

Pour reproduire le bug prendre nimporte quel serie de streaming.series.cx et il y aura aucun lié pour les episodes mais sont bien presente sur le site

**Comment by Arias800** [comment]
Corriger ici : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/streaming_series_xyz.py

**Comment by Che-debarras** [comment]
Merci effectivement c'est résolu
