### ISSUE TITLE
Lien openload hs

### ISSUE THREAD

**Issue by mickve** [Kodi-vStream/venom-xbmc-addons#2474]
Bonsoir ! Plus aucun lien openload ne fonctionne (vstream erreur : fichier introuvable)depuis aujourd’hui tester sur plusieurs site (serie streaming hd , planet streaming ,etc...

Merci

OS: Android 6.0,8.1 et IOS
Appareil : t95z plus,t95q box Android,iphone 6s
Kodi:18 et 17.6
Vstream:0.7

**Comment by TmpName** [comment]
Je suis dessus, va falloir modifier un fichier du coeur de Vstream je pense, le decodeur JS.

**Comment by TmpName** [comment]
Si quelqu'un veut continuer, j'ai mis le code du parser a jour > https://github.com/TmpName/TinyJSParser/blob/master/tinyjsparser.py
Ca fonctionne en virant toute la partie de detection de selenium/phantom ou en mettant un return false juste avant le try {

```
if(!_0x45ae41[_0x5949('8')](_0x5949('9'),document)||!(!(function(){
return false;
try{
if('_phantom'in window|
```

**Comment by magicseb** [comment]
https://github.com/TmpName/TinyJSParser/commit/4c5f6a7487b8f59be9405f79513cbfc47f693de1

C'est ce commit appliqué à jsparser.py qui semble régler le problème.

**Comment by TmpName** [comment]
Bon j'ai fini par gerer moi meme le block try/catch via le JS parser.
Pour tester mettre a jour le fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/jsparser.py
Par contre pour le coup, j'ai l'impression que le temps de decodage a vraiment augmenté cette fois.

**Comment by Arias800** [comment]
Je confirme ça a bien augmenter ca va piquer pour les petit appareil  :/

**Comment by Derka31** [comment]
bonsoir comment mettre à jour je suis un novice

**Comment by johngf** [comment]
pas vraiment vu d'augmentation de temps de décodage mais le soir open_load rame sur du 720 ou 1080 c'est peut etre a cause de ça

**Comment by TmpName** [comment]
Ben en fait, ca a saute 3/4 versions d'un coup au moins, je pourrais faire une version speciale utilisant la vielle lib plus rapide avec les 2/3 modifs de la nouvelle, mais je sais pas si ca vaut le coup.

Comme dit @johngf , parfois c'est la lecture qui rame, parfois c'est meme pour acceder au fichier, donc y a peu de cas ou on aura la video en 2s.
Apres perso, attendre 1 mn ca me derange pas si je suis sur d'avoir la video, les pages du pubs sur les chaines TV sont largement pires.
A un moment ou l'autre la vielle version ne marchera plus.

@Derka31 pour faire la mise a jour, pas le choix, tu ouvres le fichier de ton disque dur avec un editeur de texte et tu copie/colle celui du site. Tu auras moins de probleme qu'en essayant de copier le fichier.

Va falloir une MAJ complete, pour changer le fichier, la derniere date de 29 jours, mais il vient juste d'en avoir une, ca fait con de la faire de suite.

**Comment by Derka31** [comment]
Merci je vais essayer, j'ai installé kodi sur une box tv Android.

**Comment by johngf** [comment]
bas besoin de version complete @TmpName les versions intermédiaire modifie tous fichiers donc la version 0.7.10 est ok

**Comment by mickve** [comment]
Ça refonctionne avec la mise à jour 0.7.10
👍openload fonctionnel !je vais pouvoir regarder mes séries ! Vous êtes trop fort! Merci
