### ISSUE TITLE
Update 0.7.10 et librairie

### ISSUE THREAD

**Issue by bast69** [Kodi-vStream/venom-xbmc-addons#2477]
**Décrivez le bug**
Vstream ne se met pas à jour en version 0.7.10, j'ai lancé la vérification de mise à jour mais il ne voit pas la dernière.

Dans les paramètres de l'application, dans la section Librairie, je ne peux pas modifier les emplacements de films et série tv, cela est grisé.

**Votre system**
 - OS: Libreelec
-  Appareil Raspberry pi 3 b
- Version Kodi  18
- Version Vstream 0.7.0

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
ça ne fonctionne pas comme ça on peut par forcer la maj il faut attendre 3j depuis la derniere

**Comment by bast69** [comment]
j'ai bien la mise à jour en vert comme tu le précises en revanche quand je la lance, à la fin j'ai bien le résumé des modifications mais une fois que je clique sur "OK" pour valider rien ne se passe. Avant l'addon était "rechargé" je pense, là ce n'est pas le cas et la mise à jour en vert reste visible.

**Comment by johngf** [comment]
oui kodi 18 ne recharge pas il faut fermé le dialog

**Comment by bast69** [comment]
j'ai essayé de supprimer l'addon et le repo et de tout réinstaller, sans succès. Sur le repo, il ne voit que la version 0.7.0 je ne sais pas si cela peut venir de là.

**Comment by TmpName** [comment]
C'est normal, c'est la derniere "grosse version", la 0.7.10 est une MAJ ponctuelle, elle n'apparait QUE dans vstream, et comme tu as tout reinstallé, tu repars a zero.
