### ISSUE TITLE
Ianime ne marche plus. 

### ISSUE THREAD

**Issue by Gizey** [Kodi-vStream/venom-xbmc-addons#2478]
Bonjour, 
J ai un problème avec la source Ianime qui ne marche plus depuis quelques jours. 
Connection imossible erreur 403. 

 system
 - OS: Android
-  Appareil : huawei p20 pro
 - Version Kodi : 18.1

**Comment by TmpName** [comment]
Ca a l'air d'etre a cause de cloudflare, le code a chnage y a un truc en plus.
Sinon y a des correction a faire sur le site aussi, les urls ont chnagées.

**Comment by Arias800** [comment]
C'est mort ils ont intégrer recaptcha dans Cloudflare x)

**Comment by TmpName** [comment]
Non ?
Je viens de tester et c'est passé, pas vu de recpatcha, ca marche pas avec la modif que je viens de faire ?

**Comment by Arias800** [comment]
Chez moi il apparait ca : 
![Screenshot_2019-03-22 Attention Required Cloudflare](https://user-images.githubusercontent.com/24809312/54842921-7ec28b00-4cd3-11e9-99c2-fe147431a270.png)

**Comment by TmpName** [comment]
Ha ??
Pas moi et pourtant je viens de defoncer le site en faisant des requetes en boucle.
Ca vient de cloudflare peut etre ? tu es sur vpn ?

**Comment by Arias800** [comment]
Non ceci dit je vient de jeter un œil ça n'a pas l'air très complexe a passer ^^

**Comment by TmpName** [comment]
Nope, j'ai deja fais la modif, mais c'est meme trop simple, a mon avis c'est un truc qui va chnager regulierement

**Comment by Arias800** [comment]
Oui je parle de la protection de recaptcha si tu veux y jeter un œil j'ai mis les code source ici : https://github.com/Arias800/Fichier-divers/tree/master/cfrecaptcha .
En gros dans le code html de cloudflare il y a l'iframe de recaptcha et dans l'iframe de recaptcha il y a : 
- Les paramètre nécessaire
- L'image qui vont être afficher
- Et le theme

Et ensuite pour valider il faut mettre les case sélectionner en paramètre (donc de 0 a 9) ainsi que les autre paramètre requis et on récupère le token necessaire ^^

**Comment by TmpName** [comment]
Par contre dans le code j'ai vu que cloudlfare supporte "Privacy Pass", apparement y a des plugins qui utilisent ca, ca peut etre interessant de se documenter la dessus, apparemen ca marcherait comme un "credit de pass" ou tu n'aurais plus a saisir de captcha.

**Comment by TmpName** [comment]
Encore en panne a cause de la protection CF, en cours.
