### ISSUE TITLE
Récupérer toutes les saisons des anciennes séries sur ZT

### ISSUE THREAD

**Issue by wazzou8333** [Kodi-vStream/venom-xbmc-addons#2479]
Bonjour,
Est-ce qu'il serait possible de pouvoir récupérer toutes les saisons pour les vieilles séries sur ZT
Actuellement, le plugin récupère uniquement les liens de la saison 1 d'une série, ces liens étant renseignés en bas de la page
Les autres saisons sont renseignes dans d'autres encadré, tout en haut de la page  (voir capture ci dessous)
Ces encadrés pointent vers d'autres URL
Y a t*il moyen d'intégrer ces autres URL et leurs liens dans le plugin?
Merci d'avance
Cordialement

![2019-03-23_020514](https://user-images.githubusercontent.com/48846401/54859669-75a3df00-4d10-11e9-8ddb-aff318ed1dcc.png)

**Comment by razorex** [comment]
Bonjour, merci pour le retour d'info.
j'ai modifié le regex çà fonctionne de nouveau.
