### ISSUE TITLE
Installer Vstream sur box androïd Kodi Leia 18

### ISSUE THREAD

**Issue by milkmann14** [Kodi-vStream/venom-xbmc-addons#2480]
Bonjour,

comment installer Vstream directement sur ma box androïd. Aucune adresse trouvé sur le forum permet la création d’une nouvelle source et impossible d’installer une version de superrepo leia. 
Par avance merci de vos lumières !

**Comment by KodiTopQuebec** [comment]
L'adresse a entrer dans gestion de fichier est :http://www.vstream.ml/repo/

**Comment by milkmann14** [comment]
Merci
