### ISSUE TITLE
Cloudflare modification

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2481]
Alors voila j'utilise le code de Cloudflare pour un code personnel pour télécharger des scans et sur Japscan et ils y a depuis quelque jours une nouvelle version de cloudflare qui est apparu et il est fort probable quel apparaisse bientôt sur d'autre site. Voila l'erreur générer 
```
  File "<string>", line 1
    str(+str(+str(str(1+1+1+1+1+1+1+1+1+0)+str(+0)+str(1+1+1+1)+str(1+1+1+1+1+1)+str(1+1)+str(1+1+1+1+1+1+1+1)+str(1+1+1+1+1+1+1+1)+str(1+1+1+1+1+1+1+1+1)+str(1+1+1+1+1)))+str(functionstr(p){return evalstr(str(true+"")[0]+"."+str(0["fill"]+"")[3]+str(+str(101))["to"+String["name"]]str(21)[1]+str(false+"")[1]+str(true+"")[1]+Functionstr("return escape")str()str(str("")["italics"]str())[2]+str(true+0["fill"])[10]+str(undefined+"")[2]+str(true+"")[3]+str(+0+Array)[10]+str(true+"")[0]+"str("+p+")")}str(+str(str(1+1+1+1+1+1+1+0)))))
                                                                                                                                                                                              ^
SyntaxError: invalid syntax
```
Elle est declencher par `dd = eval(droite)` pendant `calcul = eval( format(calcul,'.17g') + str(aEntry[0]) + format(parseInt(aEntry[1]),'.17g'))`. J'ai poser le code de la page cloudflare ici : https://github.com/Arias800/Fichier-divers/blob/master/newCF.html

**Comment by TmpName** [comment]
La y a un soucis, y a plein de commande JS dans le code.
Donc soit c'est fixe et on passe par un code python qui extrait juste les chaine de caracteres, soit ca bouge et faut passer par l'interpreteur JS

Mais ya plein de nouvelle commande, y compris un passage en base64.

En fait le code est pas dur, un fois simplifié y a juste 2 /3 commandes je dirais a vu d'oeuil, mais si ca bouge tout les jours ca va pas etre possible.

**Comment by Arias800** [comment]
Je sais pas j'ai vu qu'ici il sont deja dessus et que ça a l'air de bien avancer mais il passe par js2py https://github.com/Anorov/cloudflare-scrape/issues/215 ^^

**Comment by TmpName** [comment]
Je viens de lire, en fait ca plante si les parametres ne sont pas passé dans le bon ordre aussi, ca c'est vicelard.

Je ne pense pas avoir besoin de js2py, mais par contre leur code me semble leger

`js = js.replace('function(p){return eval((true+"")[0]+"."+([]["fill"]+"")[3]+(+(101))[`

Je sais pas combien de temps ca va rester fixe ca ?

**Comment by Krylanc3lo** [comment]
j'utilise ce code depuis un moment et c'est assez stable. c'est surtout le coup des parametres a mettre dans l'ordre qui est galere. 
J'essaie d'implementer  le OrderedDictionary et ensuite on pourra peut-etre adapter sans js2py

**Comment by Arias800** [comment]
Ca depends si c'est pour japscan oui il y a un code qui traine sur internet il faut juste faire deux 3 modif dessus ^^

**Comment by Krylanc3lo** [comment]
Oui c'est pour JS, ca marche pour la  plupart des scans mais pas sur tous. 
Merci je vais chercher alors!

**Comment by TmpName** [comment]
Ben le truc c'est que leur derniere modif ne date que de quelques jours, donc je sais pas ce que ca va donner sur le long terme.
En fait mon probleme est de savoir ce que je laisse en JS et ce que je converti en python.

**Comment by Arias800** [comment]
Depuis qu'ils ont mis cette version il ne l'ont pas modifier mais ça fait une petite semaine donc ca n'indique rien :/

**Comment by Krylanc3lo** [comment]
Merci beaucoup @Arias800, je regarde tout de suite :)

**Comment by Arias800** [comment]
Si tu a des question créer une issue la : https://github.com/Arias800/Fichier-divers/issues comme ça on pollue pas cette issue avec du hors sujet ^^

**Comment by TmpName** [comment]
Alors je viens de faire un mix de notre code, du leur et de fonction prise dans le parser JS et j'arrive a ca https://pastebin.com/b7ciDLUN

Par contre faudrait remettre ce code dans le fichhier cloudflare et trouver un site pour tester.

**Comment by Arias800** [comment]
Je viens d'essayer pour que ca fonctionne il faut que je mettent a jour manuellement les cookie sinon il y a le cookie __cfduid qui apparait deux fois et du coup il manque le cf_clearance

**Comment by Krylanc3lo** [comment]
ah nice. tu l'updates avec quelle valeurs?

**Comment by Arias800** [comment]
Avec celle recuperer via le navigateur internet ^^

**Comment by TmpName** [comment]
Le code actuel permet d'avoir deux fois le meme cookie ?

**Comment by Arias800** [comment]
Non il y a deux cookie différent pour __cfduid l'un apres l'autre mais aucun pour cf_clearance ^^

**Comment by Arias800** [comment]
Tiens voila le code cloudflare que j'utilise pour voir si tu trouve d'ou viens le probleme (je l'ai mis sous python 3) https://github.com/Arias800/Fichier-divers/blob/master/cf.py

**Comment by TmpName** [comment]
Ben deja me suis loupe dans mon code pour decoder ^^.
La je repare un code qui traine sur internet jsunfuck.py pour l'integrer a notre code, si ca marche pas j'integre notre parserJS.

**Comment by Arias800** [comment]
Je sais pas si c'est celui la mais il y a deja un jsunfuck.py dans Vstream que j'avais mis pour FirstOneTv ^^ https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/jsunfuck.py

**Comment by TmpName** [comment]
C'est presque de celui que je suis parti, mais il ne marche pas, je suis sur la fin la.

**Comment by Arias800** [comment]
D'accord c’était pour savoir vu que j’hésitais a le dégager vu que FirstOneTv a fermer ^^

**Comment by TmpName** [comment]
Alors nouvelle version https://pastebin.com/s07UsjDz
Fonctionne avec le nouveau jsfuck.

Le decodage est bon, enfin la valeur renvoyée est bonne, mais ca marche pas ^^.

Par contre pas vu le probleme de cookie ?

**Comment by Arias800** [comment]
C'est bizarre sur japscan ca ne veux pas recuperer les cookie et donc ça ne veux pas rediriger vers la page que je demande si tu veux essayer pour voir si ca vient de chez moi voila un liens qui ne marche pas : https://www.japscan.to/manga/jackals/

**Comment by TmpName** [comment]
Non , mais le code que j'ai mis en ligne de marche pas non plus ^^.
J'ai le premier cookie, le decodage est bon, mais au lieu d'avoir la page qui donne le bon cookie (le deuxieme cf_clearance), je reboucle.
Y a un probleme sur la requete, c'est pour ca qu'on a pas le bon cookie

La j'ai supprime le header 'Content-Type' mais ca marche tjours pas, j'ai du rater un truc.

**Comment by ebs111222** [comment]
i solved it finaly i will share what i did gladly since your code help me so much

**Comment by ebs111222** [comment]
found a better one here:

https://github.com/Anorov/cloudflare-scrape/issues/218

**Comment by TmpName** [comment]
C'est bon ca remarche, probleme d'encodage.
Nouveau fichier > https://pastebin.com/7RUhGSwk

Reste a la convertir en python2 pour kodi, et faire un peu de nettoyage.

**Comment by ebs111222** [comment]
[new_cf.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/3035205/new_cf.zip)
here is a working code.

**Comment by TmpName** [comment]
@ebs111222 but your version can't work on the new CF version with in code
`]+!![]+!![]));YixtMfi.bV-=function(p){var p = eval(eval(atob("ZG9jdW1l")+(undefined+"")[1]+(true+"")[0]+(+(+!+[]+[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+[!+[]+!+[]]+[+[]])+[])[+!+[]]+(false+[0]+String)[20]+(true+"")[3]+(true+"")[0]+"Element"+(+[]+Boolean)[10]+(NaN+[Infinity])[10]+"Id("+(+(20))["to"+String["name"]](21)+")."+atob("aW5uZXJIVE1M"))); return +(p)}();YixtMfi.bV*=+((!+[]+!![]+!![]+!!"`

your fonction parseJSString is not strong enought.

And after reflexion, my version works with the new one, but does't work any more with the old one, and CF still use the old one ...

**Comment by TmpName** [comment]
```
            if '+ t.length).toFixed' in self.html:
                answer += len(self.domain) # Only old variantes add the domain length.	
```

Was exactly, that we miss for old version compatibility ^^, realy good code.

**Comment by ebs111222** [comment]
@TmpName 
i think that the safe side is reading the correct one.
its in the code here:
js_data["wait"]
any way any improvement you can make will be welcome.

**Comment by Arias800** [comment]
I have make some change : 
- I have switch between python 3 to python 2 and i use all library of Vstream
- I have add the compatibily with the old Cloudflare protection

https://github.com/Arias800/Fichier-divers/blob/master/cf.py

**Comment by Arias800** [comment]
Cloudflare change again today

**Comment by ebs111222** [comment]
As i understood it was changed again any way here is a working solution
https://gist.github.com/doko-desuka/58d9212461f62583f8df9bc6387fade2

**Comment by TmpName** [comment]
ok, so on my side I will wait for some days to see if cloudflare want to make a dynamic code.
And if yes, i will update the JSparser for it, I don't want to make a new code every 2 days.

**Comment by ebs111222** [comment]
@TmpName
Accualy the repair was made not because cf changed there code as i understood it the was aproblem with the old code but i didnt checked exactly what

**Comment by ebs111222** [comment]
You know i never understood why isnt there some sort of an API where you send him the address and get the resolved html...

**Comment by TmpName** [comment]
Lol, yeah will be usefull :)
But you need tons of proxy to change the server IP, because you will be banned so fast. Too much people will need it.

**Comment by TmpName** [comment]
Bon j'ai refais le code.
Le decodage est bon, le lien est bon , mais ca marche pas, et j'arrive pas a voir ce qui deconne dans les headers.
https://pastebin.com/Y0PUJmtX

**Comment by Arias800** [comment]
C'est quand même bizarre ce probleme de headers peut être est ce urllib qui merde car tout les autres code utilise request ?

**Comment by ebs111222** [comment]
@TmpName
Why? Tmdb does it quite well...

**Comment by TmpName** [comment]
Ben je voulais compararer les deux solutions, et la leur ne marche plus non plus
```
# coding=utf-8
import cf
import cfscrape

UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'


headers = {}
headers['User-Agent'] = UA
headers['Accept'] = 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
headers['Accept-Language'] = 'en-US,en;q=0.5'
headers['Cache-Control'] = 'no-cache'
headers['Pragma'] = 'no-cache'
headers['DNT'] = '1'

if (False):

    CF = cf.CloudflareBypass()
    sContent = CF.GetHtml("https://www.japscan.to/" ,"","","",headers)
    
else:
    s = cfscrape.CloudflareScraper()
    s.headers.update(headers)
    r = s.get('https://www.japscan.to/')
    sContent = r

print (r)
```
```

G:\Python\Cloudflare2>python G:\Python\Cloudflare2\comparatif.py
<Response [403]>
```

**Comment by Arias800** [comment]
Ah moi j'utilise celle la et elle fonctionne très bien https://github.com/Arias800/CloudflareScraper/blob/master/CloudflareScraper/__init__.py 
Pour la requete je l'effectue comme ça : 
```
scraper = CloudflareScraper.create_scraper()
file = scraper.get("https://www.japscan.to/").content
```

**Comment by TmpName** [comment]
Ben celui la marche "mieux" mais j'ai la protection captcha a la place ^^.

**Comment by Arias800** [comment]
Ah bizarre d'habitude c'est moi qui est la protection captcha x)

**Comment by Arias800** [comment]
@TmpName c'est corriger https://github.com/Arias800/CloudflareScraper/blob/master/CloudflareScraper/__init__.py c’était un bug que j'avais pas vu passer dans le pull request x)

**Comment by TmpName** [comment]
Ben en fait j'ai encore un truc bizarre
Si je fais cloudflare_kwargs = deepcopy(original_kwargs) > captcha
Si je fais cloudflare_kwargs = original_kwargs.copy( ) > ca marche
mais si je fais print (str( cloudflare_kwargs )) j'ai la meme chose, c'est le type qui va pas ?

**Comment by Arias800** [comment]
C'est vrai que j'ai pas vérifier car a la base c'est baser sur un code qui utilise ce principe et c'est vrai qu'entre temps j'ai juste dégager deepcopy car ça faisait une dépendance en plus et qui plus est pas utile mais j'ai pas penser a faire totalement sans cette ligne et effectivement ca marche sans x)

**Comment by TmpName** [comment]
Bon ca me gave, derniere version > https://pastebin.com/BhBD5hrz

Tout a l'identique et ca passe pas.
Et je vais pas foutre en place le https dans webshark, donc si quelqu'un  a un site en http avec cette protection sinon, moi je change de lib.

**Comment by TmpName** [comment]
Bon j'ai voulu garder notre code et faire avec request > meme probleme.
Mais au moins ca va etre plus facile pour comparer.
Si tu as 5mn pr avoir ton avis https://pastebin.com/YNDAhSZx

A part le systeme de sessions je vois pas ce qui manque

**Comment by Arias800** [comment]
Je viens d'essayer et chez moi ca me revoie tout le temps sur la page de le protection donc il y a un probleme pendant le decryptage des valeurs je pense ^^

**Comment by TmpName** [comment]
Nope, j'ai meme utilisé le site http://httpbin.org/headers pour comparer, les requetes
Tout est identique.
Derniere version ici
https://pastebin.com/pzRyDyhm

Elle donne exactement le meme resultat que le code prit sur ton github.

La ca commence a me saouler

**Comment by TmpName** [comment]
J'utilise ca pr tester

```
# coding=utf-8
import cf
import cfscrape


UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'
url = 'https://www.japscan.to/'
#url = 'http://httpbin.org/headers'

#https://stackoverflow.com/questions/5725430/http-test-server-accepting-get-post-requests

#'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0'
#'Accept-Encoding': 'gzip, deflate'
#'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
#'Connection': 'keep-alive'
#'Accept-Language': 'en-US,en;q=0.5'
#'Cache-Control': 'no-cache'
#'Pragma': 'no-cache'
#'DNT': '1'


headers = {}
headers['User-Agent'] = UA
headers['Accept'] = 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
#headers['Accept-Language'] = 'en-US,en;q=0.5'
#headers['Cache-Control'] = 'no-cache'
#headers['Pragma'] = 'no-cache'
#headers['DNT'] = '1'

if (True):

    CF = cf.CloudflareBypass()
    sContent = CF.GetHtml(url ,"","","",headers)
    try:
        sContent = sContent.decode("utf-8")
    except:
        pass
    
else:
    s = cfscrape.CloudflareScraper()
    s.headers.update(headers)
    r = s.get(url)
    sContent = r.text

fh = open('result.html', "w")
fh.write(sContent )
fh.close()
```

**Comment by TmpName** [comment]
Tu peux activer le debug de request

```
import logging
# These two lines enable debugging at httplib level (requests->urllib3->http.client)
# You will see the REQUEST, including HEADERS and DATA, and RESPONSE with HEADERS but without DATA.
# The only thing missing will be the response.body which is not logged.
try:
    import http.client as http_client
except ImportError:
    # Python 2
    import httplib as http_client
http_client.HTTPConnection.debuglevel = 1

# You must initialize logging, otherwise you'll not see debug output.
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True
```

Met ca en debut de fichier et tu auras le detail (desactive les autres debugs par contre), j'arrive pas a voir le prb.

**Comment by Arias800** [comment]
Bon bah j'arrive pas a trouver d’où vient le probleme c'est vraiment bizarre

**Comment by TmpName** [comment]
Grave, et tu as pas idée a quel point ca m'enerve.
Kodi gere request ?
Car la faut trouver un truc, cette solution CF commence a arriver de partout.

**Comment by Arias800** [comment]
Oui Kodi le gèrent vu qu'on l'utilise sur un site qui ne marchait pas avec urllib . Mais le pire c'est que le code qui est sur mon github marche alors que l'header est exactement le même peut être que c'est le système de session qui change quelque chose et encore je suis même pas sûr

**Comment by TmpName** [comment]
Ben la je teste avec request et avec sessiosn dans les deux cas, et y a que le code original qui marche.
Mais la ca me saoule, je ne vois pas pkoi ca marche pas.
Donc soit on capitule, et on refait une lib cloudflare a partir de leur code.
Soit on s'acharne sur ce code, mais la j'arrive pas a comprendre.

Perso je prefererais la solution deux, ne serait ce que pour dormir trnaquille, mais parti comme c'est parti la moitie des sources seront HS dans 1 semaine.

**Comment by Arias800** [comment]
Je ne comprends pas plus que toi pour le coup j'ai essayer de prendre le code dans tout les sens rien n'a marcher :/

**Comment by TmpName** [comment]
Ce soir je prendrais le probleme a l'envers.
Je pars du code qui marche et je reviens vers le notre. Je commence a virer la sessiosn , et ect ...

**Comment by Arias800** [comment]
Bonne idée ^^

**Comment by TmpName** [comment]
Bon c'est quoi deja pour ne pas avoir le cpatcha ?
connexion:  close
accept : blabla
ET ?

**Comment by Arias800** [comment]
Bah le probleme c'est qu'il sont l'air d'avoir changer les règle dans la journée des fois il faut forcer le http pour ne pas l'avoir ^^

**Comment by TmpName** [comment]
Ben je l'ai pas sur navigateur, doit bien y avoir un moyen de le sauter ?

**Comment by Arias800** [comment]
Justement je cherche depuis le début d’après-midi et le seul truc concluent forcer le http ^^

**Comment by TmpName** [comment]
CT la langue qui me manquait, ca remarche, je continu.

**Comment by TmpName** [comment]
Bon ca me saoule, je vais pas y passer mon WE, je laisse le code tel quel.

**Comment by TmpName** [comment]
J'ai mis une version sur la beta, c'est crade a n'en plus pouvoir, mais ca tourne.

Le temps de faire du nettoyage, ca devrait passer.

**Comment by TmpName** [comment]
Bon pr gumgum ca marche sur windows mais pas sur kodi.

**Comment by TmpName** [comment]
Bon ca redeconne, meme la version du github > captcha

**Comment by ebs111222** [comment]
hi,
i have noticed that if you change the https to http it solves all the capcha problems.

**Comment by TmpName** [comment]
Harrrrrrr, it s a certificate check ?
The problem, there is some site that don't work in http, but it s a good thing to check, thx.

**Comment by TmpName** [comment]
Tu as pas de soucis de ton cote @Arias800 ?

**Comment by Arias800** [comment]
Normalement j'ai déjà corriger le problème du HTTPS sur le script cloudflare qui est sur mon repo en ajoutant une boucle pour voir si le captcha disparaît sans le HTTPS ^^

**Comment by TmpName** [comment]
Mais pour les sites ne fonctionnant que en https ?
Si tu lances le site en http, ca te redirige direct vers le https.
Ca marche sur navigateur, pkoi ca marcherait pas en python ?

**Comment by Arias800** [comment]
J'en ai aucun idée xD

**Comment by TmpName** [comment]
Bon effectivement ca aide, mais nouveau probleme pourquoi
Request.text() me retourne une page encodée (BR encoding), je pensais que cette fonction faisait le decodage automatique ?
