### ISSUE TITLE
Kepliz , 

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2482]
kepliz lorsque l'on veut regarder un film on se rend jusqu' a la fin et ca dit aucune information 

**Votre system**
 - OS: [Windows, Android] les deux
-  Appareil [nvidia shield, Ultra]pc et android
 - Version Kodi  [16.17.18] 18.1
- Version Vstream 0.7.10

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by KodiTopQuebec** [comment]
![1](https://user-images.githubusercontent.com/40530593/55267831-39660680-525b-11e9-9d9b-ab2ba540b399.png)
![2](https://user-images.githubusercontent.com/40530593/55267832-3bc86080-525b-11e9-8be9-8ef2099d954a.png)
![3](https://user-images.githubusercontent.com/40530593/55267833-3e2aba80-525b-11e9-941c-15b7f02a4e6a.png)
![4](https://user-images.githubusercontent.com/40530593/55267836-4256d800-525b-11e9-90ef-9ce24baf2b8a.png)

**Comment by TmpName** [comment]
Nouvelle version sur beta a tester

**Comment by KodiTopQuebec** [comment]
j'ai essayé la béta et meme chose , ne fonctionne pas , merci d'avoir essayé de trouver une solution

**Comment by TmpName** [comment]
Je viens de retester, le meme film, pas vu de prbs.

**Comment by Benaland** [comment]
HS de mon coté aussi

**Comment by TmpName** [comment]
Refaites un test a un autre moment de la journée, la je viens de retester avec le dernier film en date, c'est passé direct.

**Comment by KodiTopQuebec** [comment]
oui effectivement il fonctionne la

**Comment by TmpName** [comment]
Moi c'est le dimanche soir, impossible de me connecter dessus depuis au moins 1 mois. Le serveur doit etre vite surchargé en ce moment.
