### ISSUE TITLE
F-OneTv est fini :(

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2483]
Y-a-t'il un autre site pour le remplacer?

Merci

**Comment by TmpName** [comment]
C'etait l'iptv ca ?

**Comment by Arias800** [comment]
Non il y avais my free tivi qui aurai pu sauf qu'ils ont mis recaptcha de partout sur leurs site donc c'est mort ^^

**Comment by sviet2k** [comment]
Quelle tristesse.
Les canaux de sport (Bein, RMC ...) vont me manquer.

**Comment by faribole** [comment]
Live TV dans la rubrique Sport remplace avantageusement F-oneTV. Il est même plus performant que directement sur le site internet

**Comment by Arias800** [comment]
Pour ceux que ça intéresse dans quelque jours ils vont annoncer pourquoi leur site a fermer :` In the next days we'll inform you why the service was closed and what FirstOne TV will offer in the future.` ^^
