### ISSUE TITLE
Opnload hs

### ISSUE THREAD

**Issue by mickve** [Kodi-vStream/venom-xbmc-addons#2484]
Bonsoir opnload  hs sur plusieurs site

**Votre system**
 - OS:iOS Android
-  Appareil iPhone 6s t95q 
 - Version Kodi  17.6,18
- Version 7

**Nous devons le reproduire**
Pour cela il nous faut:
- serie streaming hd,planet streaming
- Le titre du film: tous les films ou série
- Le nom du host opnload

**Comment by TmpName** [comment]
Je viens de retester, pas vu de probleme, tu as peut etre pas encore la derniere correction https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2474

**Comment by mickve** [comment]
Effectivement après désinstallation et réinstallation ça refonctionne! Merci
