### ISSUE TITLE
9Docu HS

### ISSUE THREAD

**Issue by mannou78** [Kodi-vStream/venom-xbmc-addons#2485]
La source 9Docu semble Hors Service en cliquant dessus on obtient le message no informations

 - Version Kodi  [16.17.18] 18
- Version Vstream 0.71
- Android

Encore merci pour le super boulot !

**Comment by TmpName** [comment]
Modif en cours, mais j'arrive pas au video sur le site non plus.

**Comment by Arias800** [comment]
Le site remarche et ca remarche sur Vstream aussi du coup ^^

**Comment by TmpName** [comment]
Coup de bol ils ont pas modifé la suite alors.
