### ISSUE TITLE
Impossible de lire les films via UpToBox/UptToStream

### ISSUE THREAD

**Issue by MarvinGdt** [Kodi-vStream/venom-xbmc-addons#2486]
Bonjour, 
J'utilise vStream depuis tout récemment et aujourd'hui, je remarque avoir un petit soucis (j'ai peut-être mon idée). J'essaie de lire des films via UpToStream (que je préfère utiliser quand il s'agit de HD, FHD ou 4k UHD), cela charge, demande ma qualité mais une fois chargé, le film ne se lance pas. Cela me laisse sur Kodi et en vain. Est-ce que j'aurais dépassé mais 120 minutes de film/jour gratuit offert par l'hébergeur ou juste un bug? 
Merci!! 

Système : 
 - OS: [Windows, Android]
-  Appareil [Android TV, portable Android, PC sous Windows 10]
 - Version Kodi  [18.1]
- Version Vstream 0.7.1

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : UpToBox
- Le titre du film : Spider-Man New Generation, Les Crimes de Grindelwald
- Le nom du host : UpToBox

Voici mes logs si jamais le soucis peut venir de moi si jamais : 

https://slexy.org/view/s20ieaVo22

**Comment by TmpName** [comment]
Un cas deja en cours avec le meme probleme https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2468#issuecomment-478281915

Mais de mon cote, je ne vais jamais sur ces sites, et quand j'y vais je doit avoir 6 lien pour un film qui m'amene sur 10 liens qui m'amene sur 5 liens donc, evidement moi quand j'essaye ca marche. Donc il me faudrait la manip EXACTE que vous faites pour tester.

Sinon cette fois pour chnager c'est erreur 403.

**Comment by FireFirstAce** [comment]
Super je suis pas le seul ça me rassure un peu lol. 
Je répondrais sur ce thread désormais du coup. 
J'essaierai dans les jours à suivre de reproduire le problème et surtout de vous l'envoyer précisément. 
En tout cas si c'est juste un problème de timeout (ce qui me paraît bizarre puisque j'en étais à même pas 1h30 de visionnage et que surtout j'arrivais à lancer d'autres fichiers) y a-t-il un moyen de savoir qu'on a dépassé la limite ? Message d'erreur ou quoi.

En passant j'ai vu que via extreme down je n'ai plus besoin de résoudre le captcha ed protect via le kodi vstream installé sur le mon téléphone alors que sur ma TV android si... Mêmes versions installées... Une idée du pourquoi du comment ?
Merci  d'avance encore vous êtes des tueurs 😍

**Comment by TmpName** [comment]
Nope le timeout, c'etait pour la seconde personne, rien a voir avec un depassement, c'est juste le serveur qui ne repond pas assez vite.
Et non, rien vu qui donne une info en cas de depassement de limite, sinon suffit de regarder une video sur navigateur.
Je pense vraiment que c'est un format qui doit pas passer, style les video avec sous titre a part, mais lequel ....

**Comment by FireFirstAce** [comment]
Voilà le problème vient de recommencer alors que j'ai pas du tout utiliser uptobox aujourd'hui...

Voici le log : https://slexy.org/view/s2yjjppr4j

**Comment by TmpName** [comment]
403, accee interdit.
Tu es sur que ca marche si tu passes par le meme lien sur navigateur, avec la meme IP ?
C'est pas normal que ca marche a un moment, puis plus a un autre, tu es sur de ne pas avoir depasse le quota ou active une protection par captcha ?

**Comment by FireFirstAce** [comment]
Bon ba j'ai fait une reinstall complète de Kodi et Vstream je verrais bien si ça me le refait... Avec le recul ça avait l'air d'être un problème de timeout mais je comprends pas trop pourquoi sachant que j'avais pas dépassé le temps... Après j'ai une installation bizarre (box 4g pour internet kodi sur la TV et sur mon tel) donc des fois uptobox suit pas tout niveau adresse ip compte enregistré etc.)
Merci pour les réponses en tout cas

**Comment by Gayed92** [comment]
Bonjour moi j'essaie sur uptobox et 1 fichiers je suis abonné mais quand je clique ça met du temps et indique ensuite erreur je sais plus quoi d'autre c'est en anglais
