### ISSUE TITLE
On vire ou pas ?

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2487]
> 2019-03-31 16:28:12.776 T:2408   ERROR: NEWADDON Unknown Video Info Key "backdrop_url"
> 2019-03-31 16:28:12.776 T:2408   ERROR: NEWADDON Unknown Video Info Key "cover_url"
> 2019-03-31 16:28:12.776 T:2408   ERROR: NEWADDON Unknown Video Info Key "imdb_id"
> 2019-03-31 16:28:12.776 T:2408   ERROR: NEWADDON Unknown Video Info Key "label"

On vire ou pas, je ne pense pas que ca serve aileurs ? Surtout si ils ont decide que ca ne servira plus.
Ca commence a charger mes logs.

**Comment by Arias800** [comment]
Je sais même pas a quoi ça servais x)

**Comment by TmpName** [comment]
C'est des metas que l'on rajoute nous meme.
Apres ca peut servir a d'autres adddons, mais on peut aussi s'en servir pour faire passer des parametres, je pense a "imdb_id" qui ma l'air plus pour les devs que pour un artwork.
C'est encore un cadeau de kodi 18, au pire je peux essayer de les virer chez moi pour tester, mais je ne vais pas pouvoir tester tout les themes (suis encore sous confluence) ni tout les trucs de decos diverses (c'est tout sobre chez moi, je suis d'un ennuis ....)

**Comment by TmpName** [comment]
Bon ben, on en a besoin donc ca restera la.
Si quelqu'un a une liste des info key utilisables, moi j'en ai trouve, et elle suffisent pas.

Le plugin a besoin de ses infos.
