### ISSUE TITLE
Question methode post

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#2489]

**Comment by mino60** [comment]
@tmpName
je n'arrive pas a extraire la cline cccam sachon que le username et une variable
ou est le problème dans le code si vous vous pouvez a resoudre ce problème..

https://pastebin.com/DTdjkT6s

**Comment by TmpName** [comment]
Donnes nous plutot la ligne tirée du code html pour tester le regex

**Comment by mino60** [comment]
voila la ligne 7 je eu la cline : C: pakface.info 16000 dreammpr cs
le paramètre "dream" et une variable 
pour tester il te faux utiliser vpn
telnet:
python pakface.py


https://pastebin.com/H4j3YU8j

**Comment by TmpName** [comment]
Alors j'ai pas compris, mais dans ton code html j'ai trouve ni "Free Test Cline" ni "dreammpr" ?

**Comment by mino60** [comment]
tu ouvre la page html : http://pakface.info/freetest/
avant de cliquer sur le bouton generate cline dans la page source e trouve le username qui ai une variable
(dreammpr) lorsque que vous actualiser la page il change par exemple (dream0ph) 

un exemple pour tester qui fonctionne
site cccamlive.com

https://pastebin.com/nFrRjtqG

https://i.postimg.cc/SsWC0ZhT/screenshot-927.png
