### ISSUE TITLE
probleme iptv vstream

### ISSUE THREAD

**Issue by kevinc1979** [Kodi-vStream/venom-xbmc-addons#2490]
Bonjour

je vous contacte car quand je veut regarder les chaines gratuite via iptv site plus rien ne s'affiche seul aucune info
j'ai tout désinstaller et réinstaller je suis en version 0.7.10 et toujours pareil

pouvez vous m'aider

par avance merci

**Comment by kevinc1979** [comment]
> Une description claire et concise de ce qu'est le bug.

Bonjour

je vous contacte car quand je veut regarder les chaines gratuite via iptv site plus rien ne s'affiche seul aucune info
j'ai tout désinstaller et réinstaller je suis en version 0.7.10 et toujours pareil

pouvez vous m'aider 

par avance merci

**Comment by Arias800** [comment]
Corriger dans la beta ^^

**Comment by kevinc1979** [comment]
ou peut on trouve la beta ??

**Comment by TmpName** [comment]
Laisse moi quelques h pour me remettre dans le bain, je vais essayer de remettre en ligne une nouvelle version complete (la derniere date de 2 mois), qui arrivera via kodi naturellement.
