### ISSUE TITLE
Openlad HS (après patch)

### ISSUE THREAD

**Issue by plugngeek** [Kodi-vStream/venom-xbmc-addons#2491]
**Décrivez le bug**
Depuis quelques heures, les liens opnload ne fonctionnent plus (j'ai la 0.7.1 qui avait déjà un patch à cause d'un problème similaire il y a quelques jours. Ça refonctionnait sans problème )

**Votre system**
 - OS: [Android]
-  Appareil [nvidia shield]
 - Version Kodi  [18.1]
- Version Vstream 0.7.1

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : peu importe 
- Le titre du fim/serie : peu importe
- Le nom du host opnload

**Plus**
Le problème a débuté il y quelques heures.

**Comment by TmpName** [comment]
Mit a jours sur beta.
