### ISSUE TITLE
Dl protect

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2492]
Impossible d'obtenir le liens sur dl protect ils ont encore changer leurs protection donc je pense basculer sur la même méthode que pour extreme download car zt commence vraiment a me souler ?

**Comment by Ovni-crea** [comment]
@Arias800  bah personnellement je pense que c'est la meilleure solution pour réglé ça et en plus ça chargera plus rapidement

**Comment by lebigboss** [comment]
ZT fonctionne ? Parce que moi ça fait 2 jours que j'ai pas accès.
Sinon, il y a moyen de passé par là méthode alldebrid pour ceux que sa concerne ?

**Comment by BENJI97200** [comment]
@lebigboss....Slt ,comment faire?

**Comment by Ovni-crea** [comment]
bonjour/bonsoir 
j'ai 2 version à vous proposer 
la 1ère c'est pour les utilisateur de real-debrid https://github.com/Ovni-crea/Source-vstream/blob/master/zone_telechargement_ws.py
normalement vous avez associer real debrid avec urlresolver donc j'ai fait en sorte que urlresolver debrid les liens dl-protect et puisse le debrider tranquillement (non il faut pas telecharger une version custom de url resolver pas besoin)

**Comment by Ovni-crea** [comment]
@Arias800 excuse moi mais ça serait possible que tu arrives à fusionner les 2 méthodes dans un seul fichier et qu'on puisse sélectionner la methode qu'on veut utiliser 
(pour extreme download pareil mais avec comme choix la méthode normal donc avec le clavier et la 2ème avec alldébrid parce que c'est incompatible avec real debrid et les liens rapidgator uploaded et nitroflare ne sont pas débrider par alldébrid ça serait super bien 👍 je te remercie

**Comment by BENJI97200** [comment]
@Ovni-crea ....tu peux m expliquer comment faire pour la 2e méthode(j ai remplacé le fichier zt.py par celui que tu as mis et rien  ne passe),,car pour extrême download je n ai rien fait de particulier et pourtant ça passe nickel

**Comment by Ovni-crea** [comment]
@BENJI97200 normalement ça fonctionne après ça dépend à partir de ou ça ne fonctionne pas parce que c'est que dl protect pas annuaire telechargement en lui meme

**Comment by BENJI97200** [comment]
@Ovni-crea....je clique sur zt rien ne se passe ,impossible d avoir les liens....j utiliserais extrême download merci

**Comment by Ovni-crea** [comment]
@BENJI97200 ok ça marche

**Comment by yas06** [comment]
salut merci beaucoup Ovni-crea j ai real-debrid j ai mis le fichier zt.py ca marche nikel juste pours savoir si ta fais le même pour extreme down ?

**Comment by Arias800** [comment]
@Ovni-crea tu n'a pas bien compris comment fonctionne la méthode All Debrid . Car All Debrid sert juste a passer  le protecteur d'URL rien de plus . Donc dans tout les cas une fois le liens obtenu il est renvoyer a Vstream qui le prends en charge comme un liens normal donc c'est inutile de faire une version pour real debrid. En plus la méthode All debrid fonctionne pour tout le monde même les non abonné ^^

**Comment by Ovni-crea** [comment]
@Arias800 le problème avec alldebrid c'est qui ne débride pas les captchas avec rapidgator , nitroflare, et uploaded comme hébergeur ça marque aucune information parce que alldebrid ne supporte pas c'est hébergeur par rapport à Real-Debrid qui eux débride tout les liens Dl-protect avec rapidgator , nitroflare, et uploaded

**Comment by Ovni-crea** [comment]
@yas06 non Real-Debrid ne supporte pas les liens ed-protect :( du coup on doit quand même resté avec la méthode alldebrid sans les liens Rapidgator, nitroflare, et Uploaded malheureusement

**Comment by Arias800** [comment]
@Ovni-crea mais c'est pas liée a l'utilisation d'alldebrid puisqu'il sert juste a passer le raccourssisseur d'URL ensuite le liens de l'hoster est traitée par Vstream comme un liens basic donc si jamais tu utilise Real debrid il serai lu par Real debrid ^^

**Comment by Ovni-crea** [comment]
@Arias800 si si c'est bien lié à l'utilisation d'alldebrid d'ailleurs c'est pour ça que j'ai fait un fichier spécialement conçu pour real debrid si tu veux pour preuve je te donne les logs pour te montré la preuve ^^

**Comment by Ovni-crea** [comment]
@Arias800 
voila l'exemple avec alldebrid
`11:34:49.793 T:1868  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
11:34:49.817 T:1868  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_ws and call function Display_protected_link
11:34:49.848 T:1868  NOTICE: 	[PLUGIN] Vstream: ZT pas besoin d'url
11:34:49.853 T:1868  NOTICE: 	[PLUGIN] Vstream: https://api.alldebrid.com/link/redirector?agent=service&version=1.0-bc7e1b20c2&token=783fbed50d05600c6d739bc4db3e18a21vlvo&link=https://www.dl-protect1.com/4355555106206706749445553504147365340063385048067574440580670m003600380r00370r004100370m0l00410l0m0n0x06700554340005906600414447405400540f0l00400f0l0660051444750550048005600470055440l0f0m0f510058004000370660039004700430r0h0z06600420047360039005000540660061504940066005540474038433653424048404955063005854063484657
11:34:50.071 T:1868  NOTICE: 	[PLUGIN] Vstream: (False, [])
11:34:50.246 T:1868  NOTICE: 	[PLUGIN] Vstream: Table initialized
11:34:50.257 T:1868 WARNING: CPythonInvoker(12, C:\Users\quent\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): the python script "C:\Users\quent\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcgui::Dialog`

**Comment by Ovni-crea** [comment]
@Arias800 là c'est le meme exemple mais avec la méthode real-debrid 
`11:38:55.974 T:960  NOTICE: 	[PLUGIN] Vstream: Hoster - play https://www.dl-protect1.com/4355555106206706749445553504147365340063385048067574440580670m003600380r00370r004100370m0l00410l0m0n0x06700554340005906600414447405400540f0l00400f0l0660051444750550048005600470055440l0f0m0f510058004000370660039004700430r0h0z06600420047360039005000540660061504940066005540474038433653424048404955063005854063484657
11:38:56.084 T:960  NOTICE: URLResolver: Initializing URLResolver version: 5.0.32
11:38:57.640 T:960  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
11:38:57.642 T:960  NOTICE: 	[PLUGIN] Vstream: player initialized
11:38:57.656 T:960  NOTICE: 	[PLUGIN] Vstream: Player use setResolvedUrl() method
11:38:57.960 T:6280  NOTICE: VideoPlayer: Opening: https://34.rdeb.io/d/XXXXX`

**Comment by FireFirstAce** [comment]
Merci à vous les gars pour votre implication c'est vraiment super ce que vous faites.
Du coup avec la nouvelle méthode l'astuce où on pouvait coller n'importe quel lien via kore au moment du captcha sur extrême down (pour lancer n'importe quel fichier pas dispo via recherche vstream) ne fonctionne plus... Un moyen de retrouver un truc similaire ?
Je sais pas si j'ai été clair 😅

**Comment by FireFirstAce** [comment]
Autre petite question au passage :
En utilisant un débrideur (j'ai pris l'essai de 7j sur alldebrid hier) est il possible d'avoir les fichiers complets non compressés (pas de réencodage uptostream avec son aac 2.0 mais bien 5.1 Dolby ou dts par exemple)
Ou pour ça il faut vraiment l'hébergeur premium ?
J'ai déjà 1fichier premium mais comme ZT bug souvent et qu'il y a plus de liens sur extreme down je me tâte à prendre soit à o alldebrid soit uptobox.
Merci encore pour vos éclaircissements 🙏🙏🙏

**Comment by Ovni-crea** [comment]
@FireFirstAce  perso je c'est pas pour alldebrid je l'utilise pas (j'utilise real-debrid moi ) mais par contre tient enregistre le fichier en .py et tu le met sur le dossier de vstream
https://pastebin.com/raw/jVTu7ThE

**Comment by AzeRim** [comment]
Zt fonctionne pour moi avec la dernière  maj du cloudfare.py . C vrai que ca bug un peu avec  zt mais ça semble à cause du cloudfare donc sûrement à optimiser. Pas eu de pb de dl-protect.

**Comment by Arias800** [comment]
Bon bah dl protect remarche tous seul de toute façon x)

**Comment by FireFirstAce** [comment]
J'ai essayé de mettre le fichier que tu m'as donné @Ovni-crea mais je trouve pas comment ça fonctionne après...
J'ai copié le texte dans un fichier d'éditeur de texte que j'ai renommé en .py et je l'ai mis dans le fichier plugin.video.Vstream. J'ai essayé dans la racine et dans le dossier  ressources/sites mais je vois pas comment faire après...

Merci !
