### ISSUE TITLE
Plus aucun lien ne fonctionne ;(

### ISSUE THREAD

**Issue by kdurand44** [Kodi-vStream/venom-xbmc-addons#2493]
Bonjour,

Depuis hier, je ne parviens plus à lancer quoique ce soit sur Vstream. Les recherches se lancent bien, j’ai les résultats mais je n’arrive pas à lire les vidéos.
Je suis sur Kodi 17.6 sur RECALBOX.
Pour info, j’ai changé ma box hier pour une Box 4g. Est ce qu’il y a un lien ? Merci de votre aide ;)

**Comment by whynotnow2** [comment]
J'ai le même problème uniquement sur ZT depuis plusieurs jours. Une idée ?

**Comment by kdurand44** [comment]
ZT ?
Pour ma part aucun openload, streamango ne fonctionnent... juste de très très rares Upvid et autres ;(
Est ce que cela peut venir de mon routeur 4g ? Ou est ce que cela vient juste des liens qui sont morts ? niveau messages d’erreurs j’ai un peu de tout (fichier introuvable, errno 2, errno 5, erreur 404)

**Comment by kdurand44** [comment]
Par ailleurs je suis sous Vstream 0.7.0. On ne me propose par la MAJ 0.7.10

**Comment by whynotnow2** [comment]
Moi aussi 0.7.0. Aucune mise à jour dispo

**Comment by lebigboss** [comment]
Bizarrement, les liens fonctionnent pas parfois sauf quand je lance avec VLC. Donc c'est peut être un problème de décodage

**Comment by kdurand44** [comment]
Dans mon cas, comment faire pour savoir d’où viens mon problème ? La mise à jour 0.7.10 resoudrait mon souci ? Je suis sur Kodi sur raspberry...

**Comment by whynotnow2** [comment]
Est ce que qqn peut me donner le lien pour la bêta zone_telechargement_ws.py ?

Merci

**Comment by TmpName** [comment]
Zt en cours de modification.
Openload aussi.
La MAJ 0.7.10 n'est pas une MAJ complete, elle n'apparait pas.

**Comment by kdurand44** [comment]
Je passe depuis hier par un routeur 4g pour me connecter... ça peut venir de ça ?

**Comment by TmpName** [comment]
Fais nous passer un log pour regarder, la on peut pas deviner.
Regharde sur un navigateur sur le meme site, si le lein fonctionne.
Opnload vient d'etre repare
.

**Comment by kdurand44** [comment]
Il y en a tellement qui ne fonctionnent pas que ça devient bizarre...
Et comme par hasard ça coïncide avec mon changement de box pour un routeur 4G (adsl pourri chez moi)

**Comment by kdurand44** [comment]
https://slexy.org/bien/s2myUGdX5J

**Comment by kdurand44** [comment]
Non ce log la

**Comment by kdurand44** [comment]
https://slexy.org/view/s2myUGdX5J

**Comment by kdurand44** [comment]
Une idée de ce qui cloche ?

**Comment by kdurand44** [comment]
Je suis donc sur un routeur 4G avec IP Statique. Le problème peut il venir de l'IP ? J'ai déjà désactivé le parfait et désactivé ipv6 comme vu sur d'autres topics. Je désespère et suis bien deçu de ne plus pouvoir utiliser Vstream (pour laquelle vous avez fait un super boulot !), que j'utilisais quotidiennement ;(

**Comment by Arias800** [comment]
Tu a essayer pour voir si ça marche via ton navigateur internet ?

**Comment by kdurand44** [comment]
Ah non je vais essayer ;)
Sinon vous voyez quelque chose d’anormal sur mon log ?
A quoi corresponde les errno 5 ou 404 ?

**Comment by Arias800** [comment]
L'erreur erno5 et 404 ce ressemble assez puisque qu'au final le résultat est le même car il n'arrive pas a ce connecter au site car il ne le trouve pas ^^

**Comment by kdurand44** [comment]
Donc d’après toi ça viendrait plus des sites que de ma connexion ?

**Comment by kdurand44** [comment]
Sur mon log tu vois quelque chose ? Pour moi c’est du chinois 😂

**Comment by Arias800** [comment]
A mon avis c'est entre ta connexion et le site en question peux être un problème de dns ?

**Comment by kdurand44** [comment]
DNS ? ça se complique pour moi... ahah
Et comment régler ça du coup ?

**Comment by Arias800** [comment]
Je viens de voir que recalbox n'utilise pas de dns donc c'est pas ça . Essaye de redémarrer ta box 4g pour voir ^^

**Comment by kdurand44** [comment]
déjà fait plusieurs fois ;(

**Comment by kdurand44** [comment]
Recalbox n'en utilise pas mais peut être Vstream et Kodi que j'utilise via la Recalbox non ?

**Comment by kdurand44** [comment]
Car c’est sur Vstream que je ne peux accéder à (quasiment) rien...

**Comment by kdurand44** [comment]
Petite précision, quand je redémarre mon routeur 4G j’arrive à lancer certains liens... et plus du tout par la suite...

**Comment by Arias800** [comment]
C'est quand même bizarre cette histoire . Pour le coup j'ai pas trop d'idée sur le pourquoi du comment ^^

**Comment by kdurand44** [comment]
J’ai refait un test avec ma Freebox (mon abonnement n’est pas encore résilié, et pareil) je pense donc que c’est interne à Vstream dans mon cas. (Kodi 17.6 sur Recalbox sur Raspberry). Peut être les liens sont ils morts ?! Arrivez vous à voir thé Handmaid’s tale (en faisant recherche puis série) et si oui avec quelles sources ?

**Comment by TmpName** [comment]
Essayes avec le site "Voirflm" car la plupart de tes liens etaient mort aussi.
Et pour les lien opnload tu avais la vielle version
20:01:53.459 T:1720706016  NOTICE: 	[PLUGIN] Vstream: Hoster - play ht tps://openload.co/embed/xxxxx
20:01:54.124 T:1720706016  NOTICE: 	[PLUGIN] Vstream: OPL er 1
20:01:54.130 T:1720706016  NOTICE: 	[PLUGIN] Vstream: Erreur: Fichier introuvable

Je crois que dans tout tes logs, j'en ai trouve un seul de fonctionnel.

**Comment by kdurand44** [comment]
Rassurant, ça ne viendrait donc pas de ma connexion ?

**Comment by TmpName** [comment]
Ben je sais pas, c'est quand meme hallucinant d'avoir aussi peu de chance que toi.
Testes avec le site que je t'ai donné juste avant, et les fichiers a jours (Opnload a été corrigé il y a peu de temps donc evites le)

**Comment by kdurand44** [comment]
Ok je vais tester ! Pour les liens openload, la mise à jour se fera automatiquement ? 
Pour ce qui est des sources, quelles sont celles qui marche le mieux ?

**Comment by kdurand44** [comment]
Je procède toujours de la même manière, j’ouvre Vstream et je fais recherche (film ou série) avec peu de chance donc pour the handmaid’s tale... incapable de trouver un lien qui marche ;(

**Comment by kdurand44** [comment]
Et dernière question ;) comment faire en sorte que les sites ou liens Vstream soient à jour ?

**Comment by TmpName** [comment]
handmaid’s tale on vient de la finir, on est passé par "voirflm" justement, lien fctel sur opnload et up2strm.
Les MAJ se font toute seule, si tu ne resinstalles rien.

**Comment by kdurand44** [comment]
Je vais regarder ça, je ne suis pas chez moi ce week-end. Je vais donc tester sur voirfilm. Qu’entends-tu par lien fctel sur openload ?

**Comment by kdurand44** [comment]
Et si tu restes dans recherche série the handmaid’s tale les autres liens ne marchent pas pour toi non plus ? Autrement dit, mes problèmes viennent plus des liens que de ma connexion donc ?

**Comment by TmpName** [comment]
Ben dans tes logs, tres peu on marché, mais tu t es acharné sur une version d'openload non fonctionnelle donc ca aide pas.

**Comment by kdurand44** [comment]
Ok, et est que je peux avoir une erreur errno3 ou errno 5 ou errno 403 si le lien est mort ? Car ça m’affiche ça souvent... désolé pour toutes ces questions mais je cherche à en savoir plus car je n’avais pas de souci il y a quelques jours...

**Comment by TmpName** [comment]
Ha, ca c'est plus rare, en general en cas de lien mort c'est juste un petit message "lien introuvable"

**Comment by kdurand44** [comment]
Et donc ça correspondrait à quoi ces erreurs ?

**Comment by kdurand44** [comment]
Que dois modifier pour ne plus avoir ces codes erreur ?

**Comment by TmpName** [comment]
Ben prend moi un lien qui te donne cette erreur. 
Testes le dans un navigateur.
Mais ca peut venir du site tout simplement.

**Comment by kdurand44** [comment]
Mais du coup (vu que vous avez tous plus d’expérience que moi) qu’est ce qui pourrait faire que la connexion fasse bugger Vstream ?

**Comment by zicmama** [comment]
Ce serait une bonne idée de trouver un moyen de retirer les liens morts que chacun découvre pour le compte de tous...
Genre inscrire les références dans un répertoire IPFS que tous les Vstream Pin et se partagent. Ou je sais pas, mieux peut-être?

NB: Pour ceux dont les DNS déconnent... Utiliser ceux de opennic.org

**Comment by kdurand44** [comment]
Est ce que justement mon problème d’errno 3, errno 5, errno 403 etc pourrait venir d’un souci de DNS à changer ?

**Comment by TmpName** [comment]
@zicmama , pas trop possible, tu imagines la taille de la base de donnée ? Sachant que selon l heure certains liens ne sont pas valides, mais valides a d'autres moment, pareil quand le probleme vient de Vstream comme un hoster HS, tout les liens qui vont etre ouvert vont se retrouver tagger "mort" alors qu'ils sont valides.

**Comment by kdurand44** [comment]
Je viens donc de tester des liens qui ne fonctionne pas sur Vstream directement sur mon navigateur et ça fonctionne... qu’est ce qui cloche sur Vstream pour moi du coup ?

**Comment by kdurand44** [comment]
Et où trouver la source voirfilm svp ?

**Comment by kdurand44** [comment]
Alors, petite MAJ dans mon problème. J’ai fait la mise à jour 7.0.2. J’ai enfin réussi à lire l’épisode que je voulais voir. Par contre le lien qui a fonctionné n’a pas marché tout de suite. Il m’a d’abord mis « impossible de lire le ou les fichiers »... puis une 2e fois rien... j’ai insisté et il a fini par le lancer... incompréhensible ! Vous avez une explication ? Comment faire pour ne plus avoir ce souci ?

**Comment by kdurand44** [comment]
J’ai peut être un élément de réponse en parcourant le forum. Ma connexion n’étant pas stable du tout... il faut peut être que je joue sur le délai d’attente pour charger la vidéo non ? Par contre dans quoi je peux gérer ça ?

**Comment by kdurand44** [comment]
J’ai vu aussi que le lecteur intégré à Kodi pouvait contourner ce problème, c’est vrai ?

**Comment by kdurand44** [comment]
Je re précise que je n’ai pas de souci sur un navigateur... en attendant un peu... (chose que je ne peux pas faire avec Vstream)

**Comment by kdurand44** [comment]
Quelqu’un pour m’aider svp ? 🙏

**Comment by TmpName** [comment]
La source "voirflm" etait bloque depuis 15jrs, je viens de voir, tu peux la reactiver en faisant cette modif https://github.com/Kodi-vStream/venom-xbmc-addons/commit/52a2dd3afd3c9230ccf2d3f248ca0733370c4131

Tu peux augmenter le timeout oui, en editant le fichier advancedsettings.xml
De mon cote par exemple j'ai
```
      <network>
         <curlclienttimeout>60</curlclienttimeout>
         <curllowspeedtime>60</curllowspeedtime>
         <!--<curlretries>2</curlretries>-->
         <disableipv6>true</disableipv6>
      </network>
```

Vstream utilise le lecteur integré  de kodi

**Comment by kdurand44** [comment]
Et comment faire la modif pour voir film ? ;) stp

**Comment by kdurand44** [comment]
Je ne sais pas où trouver le fichier advanced settings ? ;(
Ni la modif pour voirfilm..

**Comment by TmpName** [comment]
https://kodi.wiki/view/Advancedsettings.xml

**Comment by kdurand44** [comment]
Désolé mais je suis sur RECALBOX comment faire ?

**Comment by magicseb** [comment]
faut aller dans \\RECALBOX\share\system\.kodi\userdata

Pensez à afficher les fichiers cachés dans WINDOWS.

**Comment by kdurand44** [comment]
Merci c’est réglé !! Et comment faire la modif pour voirfilm ?

**Comment by magicseb** [comment]
tu vas là : \\RECALBOX\share\system\.kodi\addons\plugin.video.vstream\resources\sites
 et tu modifies voirfilms_org.py avec notepad++ ou autre editeur de texte

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/52a2dd3afd3c9230ccf2d3f248ca0733370c4131

la modif est la.from resources.lib.comaddon import progress#,VSlog
