### ISSUE TITLE
Problème installation 

### ISSUE THREAD

**Issue by stobleux** [Kodi-vStream/venom-xbmc-addons#2494]
Hello

J ai installé kodi sur ma tv Android jusque là pas de soucis, mais le problème viens lorsque j installe V stream... Il m indiqué que l appli est installée mais elle n apparaît pas

D ou peut bien venir le problème ? J ai déjà desinstallé réinstallé mais rien n y change. 

J ai aussi testé l install via divers repo et avec l officiel 

 - OS: Android
-  Appareil tv philips
 - Version Kodi  18
- Version Vstream 0.0.3

**Comment by Gziin** [comment]
J'ai exactement le même problème sur NVIDIA Shield

**Comment by FireFirstAce** [comment]
Tu n'as pas tout simplement installé le repo de vstream mais pas encore l'application ?
1.Installer depuis un fichier zip => installe le repo vstream puis f4m tester et f4m proxy ensuite
2. Installer depuis un depo => la tu installe l'addon vstream depuis le repo vstream

**Comment by stobleux** [comment]
J ai tout installé mais les fm4 testeurs après v stream. Je vais tt retirer et le faire dans l ordre que tu dis pour voir

**Comment by Arias800** [comment]
F4mtester et f4mproxy ne sont pas obligatoires  dont si ils ne sont pas utilisés ça ne vaut pas le coup de les installer ^^

**Comment by stobleux** [comment]
D où peut bien venir le problème alors... V stream pas compatible sur les TV Android ??? J ai une box sur une autre TV et la pas probleme

**Comment by Gziin** [comment]
Non c'est pas un problème d'Android TV sur une télé. Car j'ai le même souci que toi sur ma box NVIDIA Shield alors que ça fonctionne sur ma Mi Box...

**Comment by FireFirstAce** [comment]
Ça vient pas d' Android TV j'ai moi même installé mon Kodi Vstream sur ma télé Philips 😉
Reessaye de tout de s'installer et réinstaller je vois pas ce que ça peut être...

**Comment by stobleux** [comment]
Argh même en desinstallant et en réinstallant tjrs le même problème dans installer depuis un dépôt vstream repository est la et quand je rentre dedans il me met qu il est installé... Mais il est invisible je pige pas

**Comment by stobleux** [comment]
Il m installe aussi URL resolver, request tommo common et d autres script

**Comment by Gziin** [comment]
Exactement la même chose pour moi

**Comment by Gziin** [comment]
J'ai même essayé de réinitialiser ma NVIDIA Shield et Kodi

**Comment by FireFirstAce** [comment]
Lorsque vous allez dans mes extensions vous avez bien vstream dans la liste où pas ? Il doit y avoir vstream repository ET vstream

**Comment by Arias800** [comment]
Par hasard dans la liste des extensions Vstream ne serai pas désactive de base par Kodi ?

**Comment by TmpName** [comment]
Un fichier pour ma collection de log ?

**Comment by Gziin** [comment]
FireFirstAce : Lorsque que je vais dans mes extensions il n'y a pas Vstream dans la liste.

Arias : Comment savoir s'il est désactivé de base par Kodi ?


TmpName : Et voilà le fichier : https://drive.google.com/file/d/1oXestiEiN1tmiVG9m35sgwyrjOBZ4Kdh/view?usp=drivesdk

**Comment by TmpName** [comment]
Ben d'apres le log, aucune info sur un quelquonce blocage par contre tu n'as installe aucun plugin encore.
Le repositary est bien la en effet par contre.

Il est physiquement present sur le disque dur ? Si oui a quel endroit ?
