### ISSUE TITLE
Lancer un téléchargement ?

### ISSUE THREAD

**Issue by Mike4ftv** [Kodi-vStream/venom-xbmc-addons#2495]
Bonjour,

J'arrive bien a lire en live une video mais je ne connais pas la manip pour la télécharger sur mon bureau ...
Quelque un pourrait il m'aider ?
merci

**Comment by TmpName** [comment]
Quand tu es sur le dernier lien, clic contectuel, "telecharger".
Mais ce n'est pas fait pour telecharger les fichiers, c'est pour les petites connexions, tu vas vite comprendre pourquoi.
Vstream n'est pas fait pour les DL.
