### ISSUE TITLE
problème site zone téléchargement.

### ISSUE THREAD

**Issue by tiger92150** [Kodi-vStream/venom-xbmc-addons#2496]
Bonjour,
j'ai un problème sur le site zone téléchargement.
quand je vais sur source et je clique dessus rien ne se passe, le menu ne s'affiche même pas.
avant ça fonctionnait sans problème, jusqu'à il y'a quelques jours.
sachant que je n'utilise aucun débrideur j'ai seulement un compte uptobox premium.

Merci d'avance pour votre aide.

**My system**
 - OS: [Android]
-  Appareil [android box tv , version 7.1.1]
 - Version Kodi  [18]
- Version Vstream [0.7.10]

**Comment by willaax** [comment]
Bonjour, 
je confirme j'ai le même problème depuis mardi ou mercredi dernier avec Zone Telechargement (annuaire-telechargement)

**Comment by Pxwel** [comment]
Bonjour,

Même soucis, apparemment il est en cours d'être réglé.
J'ai installé la version beta en attendant et ça fonctionne sinon : [https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream](url)

**Comment by tiger92150** [comment]
Bonjour Pxwel,

J'ai téléchargé la version béta comme tu me l'as suggéré, et ça marche.
Merci beaucoup pour ton aide.
