### ISSUE TITLE
IPTV en partie KO

### ISSUE THREAD

**Issue by denseye73** [Kodi-vStream/venom-xbmc-addons#2499]
Bonjour.
Une partie de la partie IPTV/sites ne fonctionne pas.
Daily IPTV fonctionne, mais IPTV source et IPTV gratuit sont KO.

**Comment by kevinc1979** [comment]
idem pour moi

**Comment by milkmann14** [comment]
Pareil! IpTV gratuit HS!

**Comment by Arias800** [comment]
Corriger ensuite ce n'est pas utile de mettre différent message juste pour dire que vous ete impacter car si vous n'avez pas de réponse c'est qu'on est occuper a autre chose donc faut prendre son mal en patience ^^
