### ISSUE TITLE
ZT innacessible depuis derniére MAJ Bêta

### ISSUE THREAD

**Issue by wazzou8333** [Kodi-vStream/venom-xbmc-addons#2500]
Hello,
Pour vous signaler que depuis la deniére MAJ cloudflare, ZT est inaccessible, il est impossible de renter dans la section.
Le petit pop-up indique "En Cours", avec le cercle qui tourne 2/3 secondes et puis plus rien.
En revenant sur la version du repo, ZT est de nouveau accessible.

Testé sur 2 appareils différents, l'issue est reproduite sur mes appareils :

Nvidia shield/AndroidTV8/Kodi 18.1 /Vstream Bêta 0.7.2
PC/Win10 /Kodi 18.1/Vstream Bêta 0.7.2

Merci.
Cordialement.

**Comment by AzeRim** [comment]
Idem pour moi avec la dernière mise à jour de @razorex sur le fichier cloudfare.py.
Faut remettre le fichier avant MAJ pour que ça refonctionne.
Dl-protect sur extrême down (MAJ du token alldebri) ne fonctionne plus pour moi non plus. Avez-vous le même souci ou c est que pour moi?

**Comment by TmpName** [comment]
Je pense avoir corrige le prb de clodflare, mais comme il n'ya plus la protection sur le site de ZT, pas pu tester.

**Comment by TmpName** [comment]
Je pense avoir corrige le prb de clodflare, mais comme il n'ya plus la protection sur le site de ZT, pas pu tester.

**Comment by TmpName** [comment]
Je pense avoir corrige le prb de clodflare, mais comme il n'ya plus la protection sur le site de ZT, pas pu tester.

**Comment by wazzou8333** [comment]
Merci , c'est l’accès est OK à nouveau
