### ISSUE TITLE
Changer Fanart VSTREAM

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2501]
Bonjour,

Afin de tirer la meilleure expérience de Vstream sur kodi, j'ai essayé plusieurs skins, j'ai activé la recherche des métadata et j'affiche les fanart.

Seulement, il arrive que les infos ne soit pas trouvés et c'est alors le fanart VSTREAM par défaut qui s'affiche.

Avez-vous prévu un fanart un peu plus "Média" ?

Un peu comme celui d'Exodus :
http://redeneobux.com/wp-content/uploads/2016/02/2-2.jpg
ou
https://mykodiaddons.com/wp-content/uploads/2017/12/Top-Kodi-addons-Exodus-Covenant-.jpg

A moins qu'il existe la possibilité de le désactiver pour ne rien mettre, mais je n'ai pas trouvé.

Merci pour votre réponse.

**Comment by TmpName** [comment]
Alors la, moi perso je ne suis pas graphiste du tout ^^.
Mais sinon je l'aime bien, l'actuel, c'est sobre.

**Comment by sizanic** [comment]
Oui l'actuel est sobre, si on parle bien du texte VSTREAM écrit en gros.
Mais vu qu'il est à moitié masqué par la jaquette ou la description de la vidéo, une image plus neutre serait d'un meilleur effet.
Peut-être que la communauté pourrait en proposer un (évitant d'utiliser une image libre).

![Fan Art VSTREAM](https://user-images.githubusercontent.com/47307622/55991711-2b78a280-5cab-11e9-8e6a-340451fe7fec.png)

**Comment by sizanic** [comment]
Voici un exemple avec Exodus
![Fan Art EXODUS](https://user-images.githubusercontent.com/47307622/55992032-e2751e00-5cab-11e9-93c8-9c02d4c27aea.png)

**Comment by lebigboss** [comment]
![Screenshot_20190412-001253](https://user-images.githubusercontent.com/12912677/55996585-1c4c2180-5cb8-11e9-8a64-9bb7c55a809e.png)
Perso j'ai changé de Fanart. J'aime pas trop avoir de couleur en fond

**Comment by TmpName** [comment]
Apres moi ca me derange pas, si tu trouves un truc sobre qui fasse pas 10M en taille.
Je vais voir si le code affiche ca quand il n'affiche rien, ou si c'est un affichage par defaut, mais la ca sera pas pour de suite, pour le moment la priorite c'est CF.

**Comment by sizanic** [comment]
ok
si ça affiche le fond d'écran par défaut de mon skin, ce serait bien.

Sinon voici quelques propositions (+ url d'origine) :

![fanart-35](https://user-images.githubusercontent.com/47307622/56516666-58df0f00-653b-11e9-98d4-e41e5a3aa9cf.jpg)

http://phimtvfree.com/zip/.kodi/addons/plugin.video.specto/fanart.jpg

![qQsare9](https://user-images.githubusercontent.com/47307622/56516706-7f9d4580-653b-11e9-9e51-d8e3d7489ed1.jpg)
https://www.sporcle.com/games/stevenmiller61/minimalist-movie-poster-art-depictions-iii

![movies_digital_art_collage_movie_posters_fan_art_1920x1080](https://user-images.githubusercontent.com/47307622/56516733-92177f00-653b-11e9-9aab-7efccfa78a67.jpg)

**Comment by sizanic** [comment]
> Je vais voir si le code affiche ca quand il n'affiche rien, ou si c'est un affichage par defaut, ...

Pour afficher l'image par défaut, cela fonctionne presque bien.
J'ai remarqué en effet que lorsque le résumé est trouvé mais pas l'image, c'est bien celle par défaut (du skin) qui est utilisée.

On retrouve ce fonctionnement pour ces liens :
ZT - Autres - Spectacles - plamashow / Gustin / Dieudonné

Dans cette liste de spectacles, on a donc une alternance de bons fanart, d'image du skin et du logo VSTREAM.

**Comment by TmpName** [comment]
C'est quoi que tu appelles afficher une image par defaut ?
Dans le code par defaut c'est l'image plugin.video.vstream/fanart.jpg
Elle peut etre ecrase par meta['backdrop_url'] qui lui doit venir du gestionaire de meta.
Mais je vois pas ce que peut etre ton 3 eme cas ?

**Comment by sizanic** [comment]
Dans les paramètres de plusieurs skin, on peut définir un arrière-plan personnalisé,
comme ici avec le skin Estouchy :

J'ai choisi un pot de popcorn : 

![popcorn-bkg](https://user-images.githubusercontent.com/47307622/56617806-0f68ef80-6621-11e9-8c69-0210abdbb58b.jpg)


Ou avec le skin Xperience1080 : 

![Xperience1080](https://user-images.githubusercontent.com/47307622/56618395-c6199f80-6622-11e9-8f94-719e8d1bf2cb.jpg)


On aura alors 3 résultats : 
- Avec Fanart : 

![bkg-Gerrra](https://user-images.githubusercontent.com/47307622/56618285-6c18da00-6622-11e9-8cff-562fdf98efe7.jpg)

- Avec résumé mais background personnalisé : 

![bkg-palmashow](https://user-images.githubusercontent.com/47307622/56618332-9074b680-6622-11e9-90d7-56de0408df30.jpg)


- Sans résumé, avec fan art de l'extension : 
![bkg-catch](https://user-images.githubusercontent.com/47307622/56618412-d2056180-6622-11e9-8248-31bd9cc8a6b5.png)


* Le résultat sous Xperience 1080 : 

- Avec FanArt, il est affiché sur le coté ET derrière : 

![WWE](https://user-images.githubusercontent.com/47307622/56618648-8b643700-6623-11e9-8d2d-b3e66df72e55.jpg)


- sans fanart, le comportement est différent, rien d'affiché à coté mais le personnalisé est affiché derrière : 

![Palma](https://user-images.githubusercontent.com/47307622/56618443-f19c8a00-6622-11e9-89bd-92e5e3f7c151.jpg)

- le cas Extension : 

![Madani](https://user-images.githubusercontent.com/47307622/56618752-c9f9f180-6623-11e9-8907-729985d08bff.jpg)

**Comment by sizanic** [comment]
> Dans le code par defaut c'est l'image plugin.video.vstream/fanart.jpg
> Elle peut etre ecrase par meta['backdrop_url'] qui lui doit venir du gestionaire de meta.

Je veux bien m'y pencher si on me guide un peu.
Ce code est dans quel fichier ?

**Comment by TmpName** [comment]
Donc en fait c'est le skin qui se permet de chnager des trucs ?
Ben va falloir le skipper alors, car selon les skins ca risque de ne pas reagir pareil.

Sinon tout se passe dans plugin.video.vstream/resources/lib/gui/guiElement.py
Ligne 50 , tu as la valeur par defaut qui se met en place.
La fonction qui cherche les meta getMetadonne() declenchée ligne 596, en fonction des meta actives ou pas.

Ca doit se passer ligne 535, mais je n'ai aucune idée de a quel moment le skin se permet d'injecter son image.

Le fichier tmdb.py sert a telecharger les metas, mais a aucun moment il devrait entrer en compte, soit il donne une image de fond, soit il en donne pas, c'est tout.

Apres il y a aussi la possibilitée de choisir une image dans les option  de Vstream, ca c'est cool au moins on met pas un image en plus dans l'archive.

**Comment by sizanic** [comment]
Merci pour les sources, je vais jeter un œil.

La solution que tu proposes est bien également (voire mieux), elle permet une personnalisation même pour les skins qui ne la gèrent pas.

Dis nous si tu penses l'implémenter.

**Comment by TmpName** [comment]
Ben moi non ^^, je pensais que tu allais le faire :).
Mais pareil je pourrais t'expliquer si tu choisis ca, ca prend juste une ligne de plus dans un autre fichier.

**Comment by sizanic** [comment]
Dans le doute, j'ai tenté :)

Du coup, je veux bien le nom de l'autre fichier pendant que t'es dedans, même si je sais pas encore quelle implémentation je vais suivre.

**Comment by TmpName** [comment]
C'est settings.xml, tu peux t'inspirer de la partie ou tu peux choisir un dossier pour le telechargement.

**Comment by sizanic** [comment]
Et voilà, j'ai implémenté la première solution : 
https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2515#

Seulement en mode Métadonnées : 
Si pas de fanart trouvé pour un média, ne pas en afficher : pas même celui par défaut de l'addon, laisser le skin afficher son background (qui peut être redéfini).

**Comment by TmpName** [comment]
Ha wé, ca a ce moment que je realise que le code original etait plutot crade.
Donc l'image de fond est gerée par le skin pluto que Vstream, aucun impact sur les autres users, parfait.
On va voir a l'usage mais pour mmoi ca va passer, meme si je me disais ca aussi pour le marquage vu/pas vu qui fout le bordel en ce moment.
