### ISSUE TITLE
Bugs des sources 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2502]
**Décrivez le bug** 
Depuis le dernier commit #5ebbd41, 

aucun lien host à visionner :
-kstreming 
-stremingK RÉSOLU 
-Papstrem
-Stremiz (liens manquants comparé au website , meme bug que stremcomplet?!)
-Stremzzz (error timeout)

Categorie qui s'ouvre pas:
-Filmstremvk
-kaydo (dossier des titres pour avoir accès au lien host)
-Stremcomplet : maj manquant et seul l'host ok.ru s'affiche 
Surement un site clone car le site Strem-complet.WS est maj et bcp plus de lien
Donc possible de remplacer le site par celui avec un "-" et .ws?

**Votre system**
OS: [Android 6.0.1]
Appareil [KingBox TV K3]
Version Kodi 19
Version Vstream : 0.7.21 (dernière commit #5ebbd41 ) 

**Nous devons le reproduire**
Pour cela il nous faut:
ouvrir la source cité ci-dessus et atteindre le lien host de visionnage

**Comment by TmpName** [comment]
ZT, surement corrigé, ct un prb sur clodflare.

**Comment by whynotnow2** [comment]
Plus aucun lien depuis quelques heures sur ZT 😢

**Comment by TmpName** [comment]
Surement CF.

**Comment by lebigboss** [comment]
Pareil pour extreme down. C'est la panique

**Comment by Arias800** [comment]
Euh non extrême download c'est juste que la technique d'alldebrid ne passe plus et qu'il mon bannis \o/

**Comment by TmpName** [comment]
Lol, serieux un ban  ?

**Comment by Arias800** [comment]
Oui bannis x)
Bah je sais pas il foute un token en clair dans la page et après c'est de ma faute si je l'utilise mdr
Mais bon pour contourner suffit de ce faire une compte gratuit et ca passe x)

**Comment by TmpName** [comment]
Bon Ianime c'est bon
GumGum, je me remet dessus, ca redeconne ..... une variante CF.

**Comment by Che-debarras** [comment]
Désolé mais non, Ianimé n'est pas résolu même bug et pour tfarjo pareil le bug toujours présent.

Seul streaming est resolu

**Comment by AzeRim** [comment]
@Arias800 
On fait comment pour Extreme down avec un compte gratuit?
J'ai modifier les lignes 264 et 265 avec mon username et mon mdp
![image](https://user-images.githubusercontent.com/41041702/56084066-e9c43500-5e2d-11e9-93f3-cd9d6d82d4aa.png)
J'ai aussi modifier la ligne 616 avec mon token récupéré via  https://api.alldebrid.com/user/login?agent=mySoft&username=USERNAME&password=PASSWORD
![image](https://user-images.githubusercontent.com/41041702/56084085-22fca500-5e2e-11e9-9eee-35b8e675b85b.png)
çà ne marche toujours pas pour moi.

**Comment by Arias800** [comment]
Tu n'a rien a modifier tu mets le fichier qui est dans la beta ensuite tu va dans extreme download -> tu clique sur le text en rouge et tu suis les instruction ^^

**Comment by Arias800** [comment]
Wawacity c'est mort il s'utilise recaptcha ^^

**Comment by TmpName** [comment]
Un truc qui aurait utile dans kodi 18, c'est le support du JS, au lieu de l'integration des emulateurs par exemple (y a 100 fois mieux en front end pour emulateur que kodi)

**Comment by Arias800** [comment]
Oui et les seuls code existant son souvent des truc ce basant sur des service de reconnaissance vocal donc compliquer a intégrés :/

**Comment by TmpName** [comment]
Y a aussi via les site ou tu payes pr resoudre des cpatcha.
Mais la c'est le captcha invisible, c'est plus facile, il faut juste un vrai navigateur pour avoir un vrai accés, mais c'est la misere a integrer.

GumGum ok, correction de la lib CF. Par contre elle gere pas encore le POST, me souvient plus quelle source en avait besoin, c'etait pas ZT ?

**Comment by Arias800** [comment]
Oui zt demande une requête post . Oui c'est sur que pour integrer ca c'est penible ^^

**Comment by TmpName** [comment]
Petite correction pour ZoneStreaming, plus de sources dispo, mais encore l'erreur 404, ca veut juste dire que les liens ne sont plus dispo (et non affichés du coup)

**Comment by Che-debarras** [comment]
#TmpName
Désolé mais Ianime ne fonctionne toujours pas avec le fichier du dernier commit.
Peut-être peut tu partager le fichier host.py car les derniers en date ne règles pas le problème.
A chaque mise à jour je vérifie les sources qui bug et celui n'ouvre pas ses catégorie

**Comment by Arias800** [comment]
Che-debarras essaye via navigateur si ca ce trouve le site bloque sur le captcha comme chez moi et si c'est le cas il n'y a pas de solution ^^

**Comment by Che-debarras** [comment]
@Arias800

Non chez moi j'ai accès au site Ianime ya pas de blocage Cloudfare.

**Comment by TmpName** [comment]
En fait ca doit dependre des sources, j'en ai trouve une qui deconne sur les dernieres sortis, je met ca en ligne dans 10mn.

**Comment by Arias800** [comment]
@Che-debarras ah bah ça va tu a delà chance chez moi le site est totalement bloquer x)

**Comment by TmpName** [comment]
Moi, aujourdhui je doit avoir au moins 1 site sur 10 minimum avec leur protection, zont craqué leur slips.

**Comment by Che-debarras** [comment]
@Arias800 du coups c'est où le souci car chaque correction faite sur le github corrige pratiquement tout sauf celui de Ianime  alors que chez TmpName dis que ça fonctionne

**Comment by Arias800** [comment]
Enfaite le probleme c'est que pour une raison inconnu la protection cloudflare c'est mis a pété un câble et je commence a douter sur le faite que ce soit volontaire ^^

**Comment by TmpName** [comment]
@Che-debarras, je viens de faire une modif y a 5mn, ianime + CF + host, ca devrait passer la

**Comment by Che-debarras** [comment]
@TmpName je teste ça de suite

**Comment by TmpName** [comment]
Pr dadyflix faut juste refaire tout les regex, trop de temps de calcul, si quelqu'un veut s y pencher...

**Comment by Che-debarras** [comment]
Non pour Ianime peu importe la catégorie film serie animé aucun ne s'ouvre

**Comment by TmpName** [comment]
Essayes de supprimer le cookie (C:\Users\BRIX\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\ sur win7, il doit s'appeller "cookie_www_ianimes_co.txt" )
Tu as rien de special dans les logs ?

**Comment by Che-debarras** [comment]
TmpName

Je suis sur box tv kingbox K3  
Et non je pense pas avoir un truc spécial dans les logs
Par contre juste une question est ce normal que le site s'appelle Ianime mais que le fichier site.py c'est mangacity? 
Pour infos ça fait longtemps j'ai pas utilisé cette source donc je ne sais pas depuis combien de temps j'ai ce bug

**Comment by TmpName** [comment]
Yep, c'est Vstream lui meme qui le fabrique, rien avoir avec les caches, ni les fichier temporaire de ton systeme.
Sinon, si y a un truc special ^^, toi de ton cote c'est la protection cf qui bloque a cause d'un captcha.
Mais pourquoi toi tu l'as et pas nous, avec les memes fichiers ....

Yep mangacity etait son premier nom, ca pour cela que le fichier porte tjours ce nom.

Y a que 2 choses que tu as et que nous on a pas, ton IP et un reliquat de cookie.
Vu que ca marche sur gumgum, je pense pas que ce soit le code.

Fais une recherche sur ton disque dur pour un fichier avec ce nom "cookie_www_ianimes_co.txt". Aucune idee de la ou ca part sur android.

**Comment by Che-debarras** [comment]
Ce reliquat n'est pas celui de ianime car j'ai vérifié je n'ai aucun fichier cookie avec ce nom, donc peut tu me dire sur mon log qu'elle est le nom de ce reliquat ?

J'ai carrément supprimé tous les cookies de userdata de ma box tv et toujours rien.
Je pense pas que ce soit de mon coté le souci vu que ça semble marché via navigateur et je ne fais que copier coller vos fichiers github pour une majorité manuel.

Tanpis je vais pas m'éterniser dessus. Merci quand même.

**Comment by TmpName** [comment]
Tu as obligatoirement ce cookie, tu en as un pour chaque fichier protege par cloudflare.
C'est du made in maison, il ne va pas dans des repertoire pour cookies.
Regardes du cote de /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.vstream/

**Comment by Che-debarras** [comment]
Les seuls cookies que j'ai :
gumgumstreaming_com.txt
Wawacity.txt
Dlprotect_com.txt
Www.annuaire-téléchargement_com.txt
WwwV.Annuaire-téléchargement_com.txt

Si il doit y avoir faute cookies alors c'est que vstream ne les créent pas pour une raison ou une autre

**Comment by TmpName** [comment]
Non, mais tu dois avoir raison, pour le coup je comprend pas pkoi ca marcherais sur certains sites et pas d'autres.

A la ligne 44 du fichier cloudflare, il y a 
`Mode_Debug = False`
Si tu met True a la place, ca va rajouter quelques lignes dans tes logs.
Sinon tu passes par ou pour aller sur Ianime ?

**Comment by TmpName** [comment]
StreamingK  repare
Sokrostream  site de fake ? Pas de liens fonctionnels sur le site non plus quand ca deconne sur Vstream.

**Comment by Che-debarras** [comment]
Sokostream sur le site via navigateur il y a recaptcha si je me fie a l url du fichier.py car il ya un autre site sokostream mais c'est pas le même.

Quel fichier Cloudfare (je peut le trouver où ?

**Comment by FireFirstAce** [comment]
Je n'arrive plus à faire de recherche sur extreme down... En version 0.7.2. 
D'autres sont concernés ? Je sais que c'est la galère en ce moment entre les captcha cloudflare et autres bon courage aux développeurs 😅😅😅

**Comment by TmpName** [comment]
Cloudflare https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/cloudflare.py
J'ai bien Mode_Debug = False a la ligne 44.

Tu parles bien du Fullstream sans tiret ? Chez moi il passe, un titre qui passe pas ?

**Comment by TmpName** [comment]
streamingdivx refonctionne, c'etait juste un changement d'url.

**Comment by Che-debarras** [comment]
Je rajoute cloudfare et teste fullstre sans tirer oui et streamdivx jte tiens au courant

**Comment by Arias800** [comment]
@FireFirstAce la recherche d'extreme download marche sur la version en beta ^^

**Comment by lebigboss** [comment]
En tout cas moi pour l'instant j'ai plus d'erreur CF depuis que j'ai ajouté leurs DNS, les chargements sur ZT sont aussi plus rapide. Sur version officiel 0.7.2

Par contre il y a moyen de passé le captcha de Wawa avec la méthode alldebrid ??

**Comment by Arias800** [comment]
Impossible car le service d'alldebrid ne prends pas ce site en compte pour le moment ^^

**Comment by Arias800** [comment]
Dadyflix corriger : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/dadyflix.py

**Comment by FireFirstAce** [comment]
Super merci @Arias800

**Comment by lebigboss** [comment]
@Arias800 Merci

Je voulais savoir aussi, quelqu'un a essayer de mettre planet series world dans les sources ?

**Comment by Che-debarras** [comment]
Comme d'habitude je met les bugs résolu et effectivement dadyflix résolu
Parmi les bugs y a un pti truc étrange c'est que da s le bug de kaydo, le dernière film ajouté, le numero 1 du top films, le numéro 1 du top vue films, le 1e film de chaque genre (film) et enfin le dernier série ajouté  : ils ont tous l'affiche d'Aquaman qui est le top film vue

C'est un pti souci qui accompagne l absence de lien host

**Comment by Arias800** [comment]
Il ne me semble pas que quelqu'un a deja essayer de mettre planet series world.
Pour Kaydo donc hdss je ne peux pas accéder au site car je suis bloquer a cause du captcha de cloudflare ^^

**Comment by TmpName** [comment]
Moi suis pas fan de planet series world, par exemple, y a meme pas la serie breaking bad qui est quand meme une reference.

**Comment by lebigboss** [comment]
@TmpName j'avoue que là, si t'aime pas Breaking Bad alors tu mérite pas qu'on t'aime

**Comment by Che-debarras** [comment]
Moi breaking bad je les regardes sur dptreaming.cx il y a pas mal de lien de visionnage en excellente qualité. 
C'est l'un des rares à avoir d'anciennes serie en HD
Pour moi c'est la meilleur source pour les séries HD.
(Avant c'était seriestreaminghd mais sans netu ça l'est moi)

**Comment by TmpName** [comment]
lol, nope j'adore (je suis dessus en plus en ce moment) mais justement elle n'est pas sur le site planet series world, ca donne un exemple de leur bibliotheque.

**Comment by lebigboss** [comment]
@TmpName  Jte comprends. Je viens de la finir ce mois ci. C'était la 3eme fois que je la regarder.
Ils ont refait le site donc il y a plus les truc anciens mais y a du neuf genre GOT en  HD

**Comment by TmpName** [comment]
Ben le neuf, il est partout, suffit d'allumer la TV, ca ou le style de site ne proposant que les derniers box office americain, peu d'interet pr moi.

**Comment by Che-debarras** [comment]
Possible d'inclure planete serie world et l autre site de zonetelechargement cités dans dans l'autre discussion ?
NB: une grande partie des sources est résolue

**Comment by TmpName** [comment]
Ianime j'ai ton bug aussi, du coup, vais pourvoir essayer de corriger.

**Comment by Che-debarras** [comment]
Le but de ianime et streamzz je pense ils sont identique et la derniere modif permet d'ouvrir les categories mais le contenu est vide avec erreur 503 
Ya a nouveau le bug chez tvstreaming avec le derniere changement fait (cloudfare)

**Comment by TmpName** [comment]
Il a pas changé, c'est juste une amelioration, j'ai pas trouve le probleme, comme toi le probleme de captcha.

**Comment by TmpName** [comment]
Bon nouvelle version de cloudflare, mais j'ai plus le cpatcha, donc pas pu tester de mon cote.

**Comment by Che-debarras** [comment]
J'ai vérifié les sources qui bug avec le dernière commit #34e5838 Ianime et voirstream et GumGumstream refonctionne mais pas les autres

**Comment by TmpName** [comment]
Y en a 2/3 de memoire ou c'est le site qui est mort, donc a part les desactiver, on pourra pas faire grand chose.

**Comment by Arias800** [comment]
Kaydo corriger sauf le bug d'aquaman j'arrive pas a savoir pourquoi Kodi ce comporte comme ça pour le coup xD

**Comment by Che-debarras** [comment]
Arias800
Oui kaydo corrigé mais du coups les sources corrigées de la fois derniere reviennent
Voir la maj de la liste 3 sources qui n'ouvrent plus leur catégorie et gumgumstream a nouveau sans lien host et voirfilms a disparu

Pour 1 source retrouvé on en perd 5 lol ya des incompatibilités de corrections c'est ça ?

**Comment by Arias800** [comment]
Voirfilms a ete desactiver car il est plus maintenu . Pour Gum gum streaming tu a un exemple ?

**Comment by Che-debarras** [comment]
Ok pour voirfilms sinon je vais revérifier gumgumstream et les autres
Comme exemple c juste essayer d ouvrir une catégorie animé recent mais dis moi si ça marche avec le dernier maj de ton côté

**Comment by Arias800** [comment]
Chez moi gumgumstream pour les animes non licencier par contre pour ceux licencier non voir cette issue pour plus d'info : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2187

**Comment by Che-debarras** [comment]
J'ai vérifié pour voirfilms est-ce c'est pas un souci de changement d d'adresse ? Car c'est voirfilms.Link et non plus .MX

Finalement il fonctionne gumgumstream maintenant

**Comment by TmpName** [comment]
Quand j'edites les noms de sites avec des fautes, c'est fait expres ^^.
C'est histoire d'eviter de se retrouver en top de page des recherche warez de google, ce topic ressemble a un annuaire de telechargement.

**Comment by Che-debarras** [comment]
Ok autant pour moi pour les fautes j'éviterai de les corriger dsl., je ferais de même pour pas que tu a réédité toi toi-même 
Je ferais un autre poste lors du prochain maj ou correction de bug avec plein de faute d'aurtaugraf 😉

**Comment by TmpName** [comment]
TVstrm desactive pr le moment, protection captcha invisible

**Comment by TmpName** [comment]
Bon nouvellle version de cloudflare, normallement plus de captcha, ca va ameliorer certains sites comme ianime.
Si vous le pouvez, vous pouvez aller mettre une etoile sur le github du mec a qui j'ai tout pique, franchement sa derniere decouverte est vraiment de haut niveau https://github.com/VeNoMouS/cloudscraper

**Comment by Arias800** [comment]
Ah oui le mec il est pas la pour rigoler xD

**Comment by TmpName** [comment]
Put1, j'avais devine que c'etait a cause du ssl, mais apres pour moi le cypher, c'est une planete de star trek, et mettre ca en place en plus dans un code python pour une machine qui n'a pas les fichiers a jours moi j'etais parti pour mettre a jour la version openssl de kodi, j'etais en plein reve la.

**Comment by Arias800** [comment]
Il a re modifier son code en quelque chose de plus simple ^^ : https://github.com/VeNoMouS/cloudscraper/commit/7d3731c6bd8669363fc4865eb0e4a0c5d2425902#diff-3e32adf734f250c9b724258793bea4cd

**Comment by TmpName** [comment]
Ha wé, de suite, ca a l'air plus simple ^^.
Nan, franchement bon boulot.

**Comment by johngf** [comment]
voir films est revenu apparemment

**Comment by TmpName** [comment]
Je cloture celui la, quelqu'un a refait le meme topic
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2534
