### ISSUE TITLE
Marquage Vu/Non Vu

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2504]
**Décrivez le bug**
Absence du symbole "vu"

**Votre system**
Win 7
Kodi 18
Confluence en theme

Juste une question ca deconne chez vous aussi ou pas ?
Le marquage se fait, mais si je quitte la page et reviens, il n'y ait plus visuellement, mais il est encore la pour le systeme.

**Comment by Che-debarras** [comment]
Oui mais depuis longtemps je veux dire cela fait longtemps que je me fie au symbole
Quand j'ai vu l'épisode je la relance en avançant un peu et je quitte du coup le symbole vu à moitié lui il est toujours là 
Et pour les films je les mets en favoris et une fois vu je les supprime
Mais le symbole vu des fois il reste des fois il disparait

**Comment by johngf** [comment]
c'est peut etre du au fait que kodi 18 n'actualise pas le refresh ne fonctionne pas

**Comment by TmpName** [comment]
J'en sais rien mais moi ca me gene, quand je regarde une serie, pour me souvenir ou je me suis arrete la veille, c'est indispensable.
Mais quand je quitte la page et revient, il y a forcement un refresh ?
Ou alors faut forcer un truc ? Ca doit bien etre possible car ca marche sur des fichier locaux. Mais pour le peu que j'ai lu, c'est un des nouveau BUG de la V18.

https://forum.kodi.tv/showthread.php?tid=340216

Franchement je suis a 10 bug faciles qui me pourrissent la vie et 0 ameliorations visibles, serieux vivement qu'ils aient des concurrents serieux.

**Comment by Che-debarras** [comment]
Ya kodi 19 qui est sortie peut-être ça été corrigé ce refresh (version alpha)

**Comment by TmpName** [comment]
Mais vu le bordel que c'est la V18 stable et officielle, je te cache pas que j'ai un peu peur avec la V19 en pur beta.

**Comment by Arias800** [comment]
Kodi 19 ça sert a rien de l'installer car il taffe sur l’implémentation total de python 3 et ils vont bloquer tout les addon non compatible donc il y a du taffe x)

**Comment by Che-debarras** [comment]
Et du coup que va devenir vstream? Il va rester sur kodi18?

**Comment by Arias800** [comment]
Bah faudra tout convertir en python 3 xD

**Comment by lebigboss** [comment]
Faite comme moi, utilisez Trakt Tv, vous mettez l'épisode ou le film que vous avez vu et utilisez des addons genre Mettaliq ou Mx-WinG
![Screenshot_20190418-172638](https://user-images.githubusercontent.com/12912677/56372602-98d28900-61ff-11e9-80e6-6b6356c564c1.png)
![Screenshot_20190418-172720](https://user-images.githubusercontent.com/12912677/56372617-9d973d00-61ff-11e9-89e7-cbad6232f2a2.png)

Et j'utlise Moviebase sur mon tel, ça s'actualise automatiquement.
Après j'utilise aussi TvTime, mais pour d'autres raisons

**Comment by TmpName** [comment]
Je viens de retester, et @Che-debarras a raison, en fait ca marche, sauf pour les liens finaux, le prb se situe peut etre cote Vstream dans les hosts.

**Comment by Che-debarras** [comment]
@TmpName ,Pas cool lol le manque de confiance 😥 😉

**Comment by TmpName** [comment]
Lol, c'est pas que je ne te faisais pas confiance, mais comme je ne marque jamais les dossier, pour moi ca buguait tout le temps, et comme ce matin je l'ai vu fonctionner sur un autre addon, j'ai refais des tests.

**Comment by razorex** [comment]
Salut @TmpName depuis ta dernière modif de guiElement la petite coche n'apparait plus lorsque l'on fait un marquer vu. Sur kodi 17.3, 17.6, et 18.2
li549`        # Disabled, use the kodi feature `
li550`        #self.__aItemValues['Playcount'] = self.getWatched() `

**Comment by TmpName** [comment]
Ha merde, ca doit venir des meta, moi je fais sans, donc c'est kodi qui le gere.
Essayes en virant la ligne 
`del meta['playcount']`
Je pense que du coup c'est la partie qui gere les metas qui doit le memoriser.

**Comment by johngf** [comment]
kodi 16.1 mes anciens marquage ont disparu :)

**Comment by TmpName** [comment]
La V 16, c'est normal, ca commence a dater ^^.
On peut reactiver le bout de code pour les vielles versions (en faisant un test), mais c'est pour la V18 que ca m'inquiete.

**Comment by johngf** [comment]
pas besoin de réactiver je me souviens de ce que j'ai vu ou pas
mais l'air de rien la 16.1 était la version de kodi la moins buggé

**Comment by TmpName** [comment]
C'est clair, moi de mon cote ma copine me demande "elle apporte quoi la nouvelle version a part des bugs ?", pas trouve quoi y repondre.
Apres comme tu veux,, ca coute rien a reactiver, avec un test qui compare les versions.

**Comment by razorex** [comment]
Non dsl çà ne marche pas.

**Comment by razorex** [comment]
Ben moi je trouvais sa utile au moins pour suivre ou j'en étais d'une série.

**Comment by TmpName** [comment]
Bon j'ai compris, vais reactiver ces meta de *****, pour tester de mon cote.

**Comment by razorex** [comment]
Quand je réactive cette ligne oui çà ` #self.__aItemValues['Playcount'] = self.getWatched()` fonctionne.

**Comment by TmpName** [comment]
Nan, mais moi j'ai le petit "v" meme sans la ligne. Tu fais ca sur un site particulier ?

**Comment by razorex** [comment]
non tous les sites. le petit v n'apparait.

**Comment by TmpName** [comment]
Yep, je lance la video, ou je la marque en vu le V apparait, je quitte la page, reviens et il est encore la.

**Comment by razorex** [comment]
pas au niveau hoster au niveau showmovies.

**Comment by TmpName** [comment]
Ha ok, en fait ca marche pas comme ca, pour qu'un dossier soit marque vu, il faut que tout les fichiers contenus dedans le soient aussi.
C'est pour ca que ca ne marche pas avec la fonction de base de kodi.

Vais voir si je peux le reactiver uniquement via le menu pour ton cas.
Tu auras la modif en fin de soirée je pense.

**Comment by razorex** [comment]
Ben en faite je m'en sers surtout pour suivre les épisodes des séries que j'ai en marque pages. Je dois pas être le seul à faire çà. Et oui avant quand je marquais un dossier en vu les fichiers à l'intérieur l'était aussi.

**Comment by razorex** [comment]
Ben en faite je m'en sers surtout pour suivre les épisodes des séries que j'ai en marque pages. Je dois pas être le seul à faire çà. Et oui avant quand je marquais un dossier en vu les fichiers à l'intérieur l'était aussi.

**Comment by razorex** [comment]
je vais encore faire le chieur. maintenant on fait 2 fois le rafraichissement à chaque fois que l'on fais marqué vu.

**Comment by TmpName** [comment]
La je peux pas tester, mais ca devrait marcher, je desactive le rafraichissement car de passer par la commande kodi, ca doit le faire automatiquement.

**Comment by razorex** [comment]
Dsl je viens de regarder c'est Lordvenom.
