### ISSUE TITLE
Wawacity toujours opérationnel ?

### ISSUE THREAD

**Issue by f3n3k** [Kodi-vStream/venom-xbmc-addons#2505]
Bonsoir,

Petite question avant de lancer un rapport de bug, mais chez vous Wawacity fonctionne sur vstream  ?
Car moi plus rien depuis quelques temps, cela ne va pas plus loin que la demande du code captcha.

Cordialement

**Comment by Arias800** [comment]
Non ca ils ont mis recaptcha du coup la source a été désactiver ^^

**Comment by f3n3k** [comment]
hooo oki,je close alors, merki pour la réponse. ;)
