### ISSUE TITLE
MAJ 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#2507]
Les gars il est de retour Fi...on...tv mais il manque les chaînes importante :/ 

Et c est pour quand la Maj svp car ianime me manque et nous faut d new link  

Merci l équipe

**Comment by TmpName** [comment]
Je viens de lancer une MAJ ponctuelle, elle devrait arriver d'ici 3 jours max.

**Comment by Mokoman30** [comment]
j ai reçu la MAJ 7.20 a l instant  mais toujours rien pour Ianime et F..o.tv pas de nouveauté a première vue je pense que c est pas celle la la Maj Ponctuelle (TmpName)

**Comment by Arias800** [comment]
Firstonetv est mort oui le site est actif mais il se contente de revoyer sur les sites officiels des chaine ...

**Comment by Mokoman30** [comment]
Ah d accord Merci et sinon cette Mini Maj 7.20 c est pas la Maj ponctuelle sa j imagine ? Car ianime marche pas :/ vivement la grosse Maj 0 7.3

**Comment by TmpName** [comment]
En fait Ianime marchait chez moi, mais je viens d'avoir le meme bug qu'un autre user.
Du coup je vais pouvoir corriger le truc, par contre cette maj aura rate pour ce site.
