### ISSUE TITLE
Coller n'importe quel lien dans vstream

### ISSUE THREAD

**Issue by FireFirstAce** [Kodi-vStream/venom-xbmc-addons#2510]
Bonjour à tous,

Désolé d'ouvrir un sujet pour ça mais j'avais posé la question ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2492#issuecomment-482965056 mais pas eu de réponse puisque le sujet a été fermé car résolu.

Existe-t-il une nouvelle technique pour coller n'importe quel lien (uptobox 1fichier etc.) trouvé sur le net et l'ouvrir via vstream lorsque ce fichier est pas dispo via les sites enregistrés ou que le site bug ? 

Avant j'utilisais l'astuce où on pouvait coller n'importe quel lien via kore au moment du captcha pour ed protect sur extreme down (pour lancer n'importe quel fichier pas dispo via recherche vstream) via un raccourci mais grâce aux dernières avancées en matières de recaptcha ça marche plus...

@Ovni-crea avait commencé à me donner une solution (voir le sujet précédent) mais j'arrive pas à l'exécuter... 

Peut être pourrait on l'inclure de base dans une prochaine mise à jour ? (si vous voyez de quoi je parle bien sur 😅) 

Merci encore à vous 🙏🙏🙏

**Comment by AzeRim** [comment]
Hoster direct #2290 mais à rajouter manuellement au zip pour faciliter l instal sur tous t équipement.

**Comment by FireFirstAce** [comment]
Super merci, j'ai réussi à mettre le fichier correctement ( pour ceux que ca intéresse et qui galèrent comme moi ^^ il faut coller le texte de cette adresse : https://pastebin.com/raw/jVTu7ThE dans un éditeur de texte au format .py et mettre le fichier dans le dossier source de l'addon vstream)

Cependant j'ai toujours un problème : j'ai bien la source "hoster direct" qui apparait dans la liste des sources de Vstream mais en l'ouvrant j'ai juste "recherche lien" et lorsque je l'ouvre rien ne se passe (juste la roue de chargement bleue qui apparait 1 demi seconde) impossible de coller un lien...
Une idée de l'origine du problème ? Serait-ce lié à un problème de compatibilité maintenant qu'il y a la méthode alldebrid pour résoudre les captcha ed protect directement ?

**Comment by FireFirstAce** [comment]
mon log si jamais ça aide : https://slexy.org/view/s21UL3A6eo

j'ai un compte alldebrid avec urlresolver activé aussi.

**Comment by TmpName** [comment]
2019-04-27 16:15:18.899 T:11130   ERROR: ImportError: No module named hoster_direct
2019-04-27 16:15:18.898 T:11130  NOTICE: 	[PLUGIN] Vstream: could not load site: hoster_direct error: No module named hoster_direct

Doit manquer un fichier.

**Comment by AzeRim** [comment]
@FireFirstAce j'avais le même pb en passant par un éditeur de texte. J'ai résolu mon pb en cliquant droit sur le lien pastebin pour telecharger le lien puis le renommer en Hoster_direct.py

**Comment by FireFirstAce** [comment]
Merci @AzeRim ! Ça marche parfaitement ! Il faut bien respecter le nom du fichier en effet. Sujet résolu merci beaucoup à tous les contributeurs de Vstream !

**Comment by Che-debarras** [comment]
Possible de l'ajouter nativement dans vstream?

**Comment by TmpName** [comment]
A voir avec @Arias800, vu que c'est son code, moi je vois pas en quoi ca generait.

**Comment by Arias800** [comment]
En faite je l'ai jamais ajouter car je n'ai jamais trouver ou l’intègres pour faire quelque chose de propre ^^

**Comment by Che-debarras** [comment]
Ok merci car cet host direct acec la la telecomande Kore pour copier coller le lien c'est parfait

**Comment by Arias800** [comment]
Bon alors pour l’intégrer  je propose ça avec comme nom Recherche Hoster ^^ :
![Capture](https://user-images.githubusercontent.com/24809312/58378725-f8f3e200-7f98-11e9-9fcb-207253c6fb38.PNG)

**Comment by Che-debarras** [comment]
Je ne vois pas recherche hoster sur vstream dans ma version

**Comment by Arias800** [comment]
Oui parce que je propose juste la manière de l’intégrer  j'ai pas encore modifier les fichier ^^

**Comment by TmpName** [comment]
Heu non, moi suis pas fan sur la page home. C'est pas un truc qui va servir a tout le monde, et j'ai deja trop d'icones sur cette page. Le laisser dans "toutes les sources" c'etait pas mal.

En fait c'est pas une recherche, c'est un lancement direct de lien.

Ou sinon faire une rubrique "outils", et y mettre dedans les telechargement + librairie + lancement de lien direct ?

**Comment by Arias800** [comment]
Bonne idée de mettre une rubrique outils . Donc au pire pour le moment je le mets parmi les source ?

**Comment by TmpName** [comment]
Donnes moi une heure, je fais une rubrique outil. Tu le mettras dedans. Sinon oui qu'il apparaisse dans les sources moi je trouve ca normal.

**Comment by Arias800** [comment]
Prends ton temps t’inquiète pas depuis le temps que ça traine il y a le temps xD
Bah après moi je cherchais a faire un truc ranger ^^

**Comment by TmpName** [comment]
Lol, ben en fait ca m'a prit 5mn, c'etait pas dur.
Et moi ca m'arrange, comme ca j'ai pile 15 icones, 3 rangées de 5 sur un seul ecran.

**Comment by Arias800** [comment]
Bon bah voila ajouter au pire on modifiera si besoin ^^
