### ISSUE TITLE
Supprimer les metadonnées de LiveTV

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2511]
Bonjour,

J'utilise la recherche des métadonnées pour avoir les pochettes et le résumé des films.

Par contre, pour la source LiveTV, dédié aux sports, la recherche des métadonnées retourne malheureusement aussi des résultats.

Ce qui donne une pochette et un résumé forcement faux :

![Football](https://user-images.githubusercontent.com/47307622/56517934-719cf400-653e-11e9-8937-289ef7fe5a09.png)

=> Comme il s'agit ici de catégories, est-il possible de désactiver la recherche et de mettre en place une icone unique ?

Par exemple, voici ce qui est en place pour les catégories de la source Robin des Droits : 
![Replay](https://user-images.githubusercontent.com/47307622/56517744-00f5d780-653e-11e9-99ca-897dee755f66.png)

**Comment by TmpName** [comment]
C'est tres simple.
Dans le code tu as des oGui.addMovie ou les fanart sont appliqués il te suffit de les remplacer par des oGui.addDir qui eux n'en ont pas, tu as aussi une petite correction de parametre a faire, pas le meme nombre sur les 2 fonctions.
Mais en comparant les 2 codes tu vas vite voir la difference.

**Comment by sizanic** [comment]
Merci @TmpName ,

c'est d'autant mieux comme ça que maintenant le chargement de la liste des 500 matchs de la catégorie foot se charge presque instantanément !
(près de 20 sec. avant)


J'ai créé cette PR, en espérant qu'elle soit prise en compte : 
https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2514

Merci.

**Comment by TmpName** [comment]
Nickel, tout est parfait, j'ai valide de suite.

**Comment by sizanic** [comment]
Merci.

Bien que ce soit pas si parfait, car pour le troisième niveau ( celui du
flux), l'icône est un peu coupé.

Ça ce voit un peu.

J'ai pas trouvé pourquoi.

**Comment by TmpName** [comment]
Ha ?
Moi j'ai pas de problemes, le skin peut etre ? Suis encore sous confluence.
