### ISSUE TITLE
Disney hd erreur 404

### ISSUE THREAD

**Issue by turlututu76** [Kodi-vStream/venom-xbmc-addons#2512]
Bonjour et merci à tous les contributeurs :)

Le lien Disney hd dans la catégorie Films/Films (qualitė hd) me donne depuis très longtemps une erreur 404 (lien introuvable).

Si vous pouviez régler ce petit problème,  ce serait super !

**Comment by Che-debarras** [comment]
Fait une mise à jour manuel avec les fichiers du github
La version 7.20 est une version moins avancée que celui du github
Je viens de vérifier et ça fonctionne  avec les dernières maj

**Comment by turlututu76** [comment]
J'ai jamais fait de maj manuelle, quels fichiers faut-il remplacer ?

J'ai accès à Disney hd seulement en passant par "Sources" sur le menu principal.
Ps : je suis bien en version 7.20

**Comment by johngf** [comment]
c'est normal le liens n'existe pas et l'acces a ce site ce fait par anime enfants

**Comment by turlututu76** [comment]
Il se fait par film hd aussi, enfin le lien est présent en tout cas.
