### ISSUE TITLE
mise a jour 07.20

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2513]
**Décrivez le bug**
il y a des sources qui ne sont plus la 

**Votre system**
 - OS: [Windows, Android] pc et boite
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]18.1
- Version Vstream 0.7.20

**Plus**
ou sont passé free téléchargement et wawacity ? sur la nouvelle mise a jour

**Comment by KodiTopQuebec** [comment]
![free](https://user-images.githubusercontent.com/40530593/56530031-bd8c7080-651f-11e9-9561-be822d494fbb.png)

**Comment by KodiTopQuebec** [comment]
![wawacity](https://user-images.githubusercontent.com/40530593/56530044-c3825180-651f-11e9-8154-aeb8e20ab9bc.png)

**Comment by turlututu76** [comment]
Je les ai toujours moi sur la 7.20

**Comment by BENJI97200** [comment]
@turlututu76 ....slt moi non plus je n ai plus wawacity et free téléchargement....

**Comment by KodiTopQuebec** [comment]
@turlututu76 , es tu certain que tu es en 0.7.20 , cette mise a jour est sortie aujourd hui le 22 avril ?

**Comment by lebigboss** [comment]
Oui y a plus

**Comment by BENJI97200** [comment]
@lebigboss....ok ,pas de wawacity ,pas de free téléchargement, et ddl ne passe pas erreu" erno7"....une solution stp?

**Comment by wazzou8333** [comment]
Pour wawacity, c'est marqué que c'est désactivé à cause du recapcha:
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/238faeab4441a04b92fe55c56389107ce0c2ab48

**Comment by turlututu76** [comment]
C'est bizarre sur ma tablette Android les sites ont effectivement disparus,  mais sur le coreelec de ma box android ils y sont toujours (je suis bien en 0.7.20)

**Comment by TmpName** [comment]
La V0.7.2 est la derniere version complete.
Si vous l'avez depuis plus de 3 jours une MAJ ponctuellle vous sera proposé la V 0.7.20, qui n'apparait pas sur kodi.
V0.X.X sont les version completes qui apparaissent sur kodi, les V0.X.XY sont les version internes au plugins, si voius desinstallez/reinstallez vous les perdez.

**Comment by KodiTopQuebec** [comment]
@TmpName , toi tu n as aucune idée pourquoi suite a cette mise a jour free téléchargement n est plus disponible dans les sources ?

**Comment by wazzou8333** [comment]
Pour ma part, je viens de refaire la MAJ depuis le repo, et retour de wawacity et free-telechargement...
J'ai rien compris à l'histoire lol

**Comment by KodiTopQuebec** [comment]
@wazzou8333 , pour la tu es en version 0.7.2 et non en 0.7.2.0 , va voir dans les réglages de kodi sous l onglet a propos tu verras ta version officiel

**Comment by wazzou8333** [comment]
@KodiTopQuebec , oui c'est bien ça , je suis en 0.7.2
Pourtant hier, j'avais la même chose (mise à jour depuis le repo), et je n'avais pourtant les 2 sources citées précédemment

**Comment by KodiTopQuebec** [comment]
@wazzou8333 , tu as tout a fait raison , de cette façon sont revenu et lorsque l on va voir dans les réglages de vstream a l onglet a propos il est bien en 0.7.2.0

**Comment by KodiTopQuebec** [comment]
![vstream](https://user-images.githubusercontent.com/40530593/56598209-16144a00-65c2-11e9-804d-67ac9efd23af.png)

**Comment by wazzou8333** [comment]
@KodiTopQuebec 
oui, tu as raison , j'avais pas regardé au même endroit que toi, dans les préférences du plugin je suis comme toi en v 0.7.20, mais si je vais sur information du plugin j'ai une v 0.7.2

**Comment by BENJI97200** [comment]
@wazzou8333....slt comment as tu fais pour refaire la mise a jour depuis le repo stp?

**Comment by BENJI97200** [comment]
@wazzou8333...j ai trouvé...merci

**Comment by TmpName** [comment]
Wawa n'est plus dispo, si vous l'avez, c'est que vous etes sur une vielle version, suffit d'attendre, a chaque reinstal vous repartez a zero.

**Comment by mannou78** [comment]
ZT ne marche plus depuis cette mise a jour. Suis je le seul a avoir ce probleme.

Merci pour le super travail toute l euiqpe!

**Comment by KodiTopQuebec** [comment]
personne a trouvé pourquoi free téléchargement n est plus affiché dans source ? si je vais voir dans kodi/addons/plugin.video.vstream/ressource/sites  il est la , cela est depuis la dernière mise a jour de vstream

**Comment by TmpName** [comment]
Je viens de le remettre en place, normallement.

**Comment by KodiTopQuebec** [comment]
j'ai désinstallé vstream , remis vstream , fait la mise a jour 0.7.21 et free-téléchargement n est toujours pas dans la liste dans source , j'ai été voir dans ajout de source et il n est pas la non plus , j y comprend plus rien alors

**Comment by TmpName** [comment]
Ben j'ai fais la MAJ hier, et elle aparait dans la liste chez moi, mais pour info la MAJ du site a ete faite apres la MAJ 0.7.21, donc elle est peut etre pas prise en compte, essayes en remplacant juste le fichier.

**Comment by KodiTopQuebec** [comment]
c est exactement ce que j'avais fait , merci du retour ,
