### ISSUE TITLE
Ajouter stream complet comme source 

### ISSUE THREAD

**Issue by jbunny20** [Kodi-vStream/venom-xbmc-addons#2519]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Une description claire et concise de ce qu'est le problème. Ex. Je suis toujours frustré quand [...]

**Décrivez la solution que vous souhaitez**
Une description claire et concise de ce à quoi vous voulez arriver.

**Comment by jbunny20** [comment]
Ajouter stream complet comme source sa serais bien !

**Comment by johngf** [comment]
il été désactivé , je l'ai mis a jour et ré-activé mais il faut le remettre dans settings il me semble ? @TmpName

**Comment by jbunny20** [comment]
Parfait je regarde sa merci beaucoup

**Comment by johngf** [comment]
le fichier est la [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/streamcomplet.py)

**Comment by TmpName** [comment]
Ben le remettre dans setting ne sert qu'a une chose, pouvoir le desactiver ^^.
Il apparait partout ailleur sans probleme, et si il n'est pas du tout present dans la config, il apparait aussi dans la recherche.
Je refais une verif au moment de la grosse MAJ, normallement si il est encore present, il sera remit. Mais dans tout les cas si tu le re-activse ca suffit pour qu'il re apparaisse.

**Comment by KodiTopQuebec** [comment]
je l ai activé, par contre les films ne décolent pas , donc au final a quoi sert de le réactiver

**Comment by johngf** [comment]
il fonctionne apres c'est sur il y a surement des liens hs comme tous les sites

**Comment by razorex** [comment]
@TmpName avait basculé ce site en trash parce que les liens sont de très mauvaise qualité. Je parle qualité d'images bien sur.

**Comment by TmpName** [comment]
Ha bon ?
Pourtant la qualitée video, c'est pas mon critere premier. En general c'est plutot quand le site est mort.

**Comment by razorex** [comment]
Dsl c'est lordvenom.
