### ISSUE TITLE
Accelerer les recherches

### ISSUE THREAD

**Issue by cedricam** [Kodi-vStream/venom-xbmc-addons#2520]
Le temps des recherches est long car il est sequentiel.Cela rends dependant chaque source l 'une de l'autre.
Il serait judicieux de lancer  les recherches avec un parallelisme configurable. Cela rendrait la recherche plus efficace et si un site ne reponds pas, cela permets d'avoir les reponses des autres sites plus rapidement...
en gros des thread Avec une gestion de queue et pool.
https://medium.com/@shashwat_ds/a-tiny-multi-threaded-job-queue-in-30-lines-of-python-a344c3f3f7f0

**Comment by TmpName** [comment]
Alors, oui tu as raison, surtout que ce n'est pas des consommation de processur mais de connexion internet, mais moi perso je m'y pencherais pas car.
- Ca demande de mettre en place un systeme multithread, avec tout le boulot de controle que ca demande, juste pour gagner quelques mn sur une recherche que l'on ne fait pas toute les 5mn quand meme, pour moi c'est chasser le moustique au lance-flamme.
- Kodi est une bouse, instable. Pas du tout adapté pour ce fonctionnement, j'ai code le telechargement sur ce fct, je connais des dizaines de bugs possibles, et j'imagine le nombre de personne qui ont du redemarrer kodi car il n'arrivaient pas a fermer le telechargment de Vstrm.

Par contre, pour l'ameliorer, y a plus simple, mettre en place un timeout, si pas de reponse du site au bout de 2s, on saute au suivant. De mon cote 2/3 sites a eux seul mettent plus de temps que tout les autres.
