### ISSUE TITLE
Personnalisation/Customisation de l'interface

### ISSUE THREAD

**Issue by thib5** [Kodi-vStream/venom-xbmc-addons#2521]
Bonjour, J'ai réaliser récemment que j'utilise très souvent les même 2-3 source.... je me disait ( je sais c'est long et dur a implémenter ) qu'il pourrait avoir un réglage dans Stream pour mettre une source par défaut. 

Donc lors ce que l'on navigue ou qu'on lance des recherche ça serait beaucoup plus rapide et si il ne trouve pas ce qu'on veut il y aurait un option pour relancer la recherche mais avec un source spécifique ou toute les source

**Comment by TmpName** [comment]
Hello, 
sinon c'est que je fais (ou plutot faisais, ma source viens de fermer :( ), je vais dans toutes les sources, et je prend toujours la meme. Et quand elle ne trouve pas, je passe par la recherche globale.

**Comment by sizanic** [comment]
Il suffit de mettre dans les favoris :
- sa source préféré pour les films
- sa source préféré pour les séries
- l'accès à la recherche global
- l'accès aux marque-pages
- ...

exemple : 
![Favoris](https://user-images.githubusercontent.com/47307622/57182207-d3dde900-6e9c-11e9-8193-630dcfe865ae.jpg)

**Comment by TmpName** [comment]
Ha, j'avais pas vu cette fonction, y a moyen d'avoir des favoris par extension naturellement sur kodi?
C'est ou ca sur confluence ?

**Comment by sizanic** [comment]
Comme pour tout ajout dans les favoris, par le menu contextuel ;

![Ajout Favoris](https://user-images.githubusercontent.com/47307622/57199822-0f071780-6f84-11e9-8323-ed1f2a332929.jpg)

Avec cette utilisation des favoris, il ne faut pas polluer cet écran avec des films mis en favoris.
Pour les films et séries, utiliser les marques-pages (d'où le raccourci vers les marques pages).

**Comment by sizanic** [comment]
Mais pour personnaliser son écran, il y a mieux que confluence, comme par exemple Xperience1080.

On peut ajouter une tuile qui pointe sur un raccourci :

![Ajout Tuile](https://user-images.githubusercontent.com/47307622/57199994-17605200-6f86-11e9-81fa-2b6bd23bf219.jpg)

**Comment by sizanic** [comment]
Certains Skin vont plus loin, comme par exemple Aeon, qui permet une personnalisation tellement poussée qu'il est possible d'écrire sa propre url :

![raccourci perso](https://user-images.githubusercontent.com/47307622/57200190-e9304180-6f88-11e9-920e-9583bbe53dc8.jpg)

C'est ce genre de raccourci que j'utilise pour lancer les mises à jour Vstream : RunAddon(plugin.video.vstream,site=cHome&function=showUpdate)

**Comment by sizanic** [comment]
Mais je suis maintenant bloqué pour certaines personnalisations de VStream.

Je voudrais pouvoir, sans repasser par les paramètres : 
- activer/désactiver une source
- activer/désactiver les métadonnées
- etc.

Pour cela, je propose cette modification : 
https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2526

A discuter ...

**Comment by TmpName** [comment]
Put1 4 ans apres, je viens de decouvrir une fonctionnalitée utile sur kodi, merci.

**Comment by sizanic** [comment]
Tu veux voir une belle ligne de commande.
Alors accroche-toi : 

Si je veux enchaîner plusieurs actions, la seule façon que j'ai trouvé, c'est d'utiliser 
"dialogyesno"
dans le plugin
"script.skin.helper.service" (qui contient plein de fonctions utiles)

Utilisation (attention, pas d'accent dans les textes) :

`RunScript(script.skin.helper.service, action=dialogyesno, header=Mon titre, 
message=Enchainer des action ?, yesaction= actionYes1| actionYes2, noaction=actionNo1| actionNo2`

Ce qui donne pour plusieurs setting Vstream (merci pour le merge en passant) : 

```
RunScript(script.skin.helper.service,action=dialogyesno,header=Parametres,
message=Mettre à jour les parametres ?, yesaction= 
RunAddon(plugin.video.vstream,function=setSetting&id=meta-view&value=true)|
RunAddon(plugin.video.vstream,function=setSetting&id=plugin_kepliz_com&value=true)|
Notification("Parametres","Mise a jour des parametres OK")
```
(j'ai ajouté à la fin une notification systeme)

Mais cela ne fonctionne pas, à cause d'un souci de multithreading (que tu a soulevé ailleurs).
Les deux appels sont appelés en même temps et le premier appel voit ces parametres écrasés par le deuxième appel. Il n'y a que le deuxième setting qui est mis à jour.

Alors la solution est de diffuser les appels dans des timers (Alarmclock) : 


```
RunScript(script.skin.helper.service,action=dialogyesno,header=Parametres,
message=Mettre à jour les parametres ?, yesaction=
AlarmClock(setting1,RunAddon(plugin.video.vstream,function=setSetting&id=meta-view&value=true),00:01,silent)|
AlarmClock(setting2,RunAddon(plugin.video.vstream,function=setSetting&id=plugin_kepliz_com&value=true),00:03,silent)|
AlarmClock(goBack,Action(Back),00:05,silent)|
AlarmClock(Notif,Notification("Parametres","Mise a jour des parametres OK"),00:06,silent))
```

(je lance tous ça depuis la page Home, alors j'ai ajouté une action(Back) sinon je me retrouve dans la liste des extensions)

Liste des fonctions KODI :  https://kodi.wiki/view/List_of_built-in_functions


Je te laisse t'extasier devant tout ça ;)

**Comment by TmpName** [comment]
Pour quelqu'un qui aime la customisation, c'est vraiment impressionant.
Ca me deprime encore plus de voir les "a coté" de kodi, et ce que fait leur team de dev, je pense que c'est la plus mauvaise team de dev que je connaisse, ignare, agressif, hautain, completement a coté de la plaque, tu supprimes tout les petis plugins, ca devient juste un VLC avec un frontend mais 5 fois plus lourd.
J'ai edité le titre pour pouvoir retrouver ton issue plus facilement dans le futur.

**Comment by sizanic** [comment]
Perso, je n'ai pas encore eu affaire à cette équipe.
De ce que je vois de KODI, c'est à travers le Skin que j'utilise et VStream. Et je suis satisfait.
(Mais vu mes exigences, cela pourrait arriver)

La team VStream, vous êtes super cool et accessible.
Et j'ai eu de bons rapports également avec l'équipe qui développe un skin que j'ai utilisé, et dans lequel ils ont implémenté une évolution que j'avais demandé.

Pour le titre de cette issue, je suis d'accord avec ta modif, même si ce n'est pas moi qui l'avait créé :-)
Et je ne peux donc la clôturer ;-)
