### ISSUE TITLE
Dpstreming.cx

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2522]
**Décrivez le bug**
Je ne met pas cette source dans la liste avec les autres car le bug est differentsnn, les liens host s'affichent mais aussi disparaissent..J'ai eu ce souci avec NCIS los angeles 
Apres un nettoyage des caches (Vstream et Kodi) les liens host reviennent mais pas tous
J'ai quitté le dossier NCIS Los Angeles et y revenir sur le meme episode et là le lien host à de nouveau disparu

**Votre system**
 - OS: [Android]
-  Appareil [kingbox k3]
 - Version Kodi  [18]
- Version Vstream

**Nous devons le reproduire**
Essayer de visionner une serie (NCIS L.A)  et si pas de lien host nettoyage des caches qui pourraient refaire revenir le lien host dans certains dossiers host 
Et dans quitter le dossier host dont le lien est réapparu pour y revenir et le voir disparu
Voir les 2 photos sur le comment qui suit

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Che-debarras** [comment]
[
![20190503_215354](https://user-images.githubusercontent.com/44464129/57162318-257b6a80-6dee-11e9-9edf-daa647756b80.jpg)
![20190503_214810](https://user-images.githubusercontent.com/44464129/57162369-53f94580-6dee-11e9-8084-28e026051a22.jpg)


](url)

**Comment by Che-debarras** [comment]
Je pense que le problème est résolu car le liens s'affichent sauf pour le host Flix555

**Comment by razorex** [comment]
Il y a peu de lien valide sur ce site.
j'ai trouvé un lien valide mais pas stable [ici](https://dpstreaming.to/serie-shadowhunters-saison-3-streaming/2/#myPlayer) si çà peut aidé.
![Capture](https://user-images.githubusercontent.com/26149640/57435640-2b35dd80-723e-11e9-8de2-9bd79c58952c.JPG)

**Comment by Che-debarras** [comment]
@razorex
Ce serait bizarre qu'il ajoute des liens hosts vides
Personnellement j'utilise très souvent ce site et les liens ont toujours été valide
Apres netu, Vidoza est le meilleur mais ces derniers temps les liens disparaissent.
Je parle pas de valide car liens morts je parle de liens qui disparaissent
Je peux faire une video pour montrer le bug mais je sais pas si je peut joindre la video en pièce jointe
Le site que tu donne est le meme, c'est les même liens car c'est un site clone je pense

**Comment by TmpName** [comment]
Alors de mon cote
j'ai teste le site ht tps://d pstreaming.pro.
Meme serie, meme saison, episode 1, et j'ai le meme resultat que sur le site. C'est a dire 50 liens, pas pu en lancer un seul, et gavé de pub.

**Comment by Makoto83** [comment]
En même temps quand on voit le site faut pas se demander pourquoi ça marche pas, c'est des sites de merde qui se gave de fric sur des gens qui cherche a cliquer pour faire marché leurs sois-disant liens :D

**Comment by TmpName** [comment]
Yep, c'est dommage, car leur bibliotheque etait geniale, ya des trucs qui ne sont que chez eux. Mais la pour le coup j'arrive plus a lancer un seul truc.

**Comment by razorex** [comment]
De toute façon le pb vient pas de vStream mais du site.

**Comment by johngf** [comment]
il y a bug parfois avec l 'anti bot pour les liens aussi mais cette semaine chez moi j'ai pu regardé une serie sans soucis

**Comment by TmpName** [comment]
Je sais pas, mais meme avec navigateur anti-pub desactivé, je tombe que sur des liens absents, et ca me demande de rafraichir la page, je sais que l'anti-bot est tatillons mais la ...

**Comment by Che-debarras** [comment]
Comme johnf
La semaine derniere pas de soucis et cette semaine ça a l'air d'aller.
Esperont que ça dure
