### ISSUE TITLE
Sources et reseau

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2523]
Je me permet de poser une question, quelqu'un pourrait m'expliquer pourquoi une source vstream fonctionne en wifi mais pas en 4G ex LibertyLand 

Par contre c'est l'inverse pour Kstreming il marche en 4g mais pas en wifi

Merci

**Comment by TmpName** [comment]
DNS je dirais, ou site bloquant simplement les clients mobiles.

**Comment by Che-debarras** [comment]
Une solution pour ces 2 soucis?
Quelqu'un d'autre a ce soucis (reseau free et wifi Numericable)

**Comment by TmpName** [comment]
Eviter la 4G pour autre chose qu'un smartphone ?
Reconfigurer les DNS avec des adresse ne venant pas des FAI ?

**Comment by Che-debarras** [comment]
Pour kstreming quelle dns je pourrais utiliser sans que ça touche les autres sources merci

**Comment by TmpName** [comment]
Essaye avec le dns de google, je crois qu'il y en a plein qui l'utilise celui la.
Moi j'ai celui de base de mon FAI et effectivement le site est bloque avec les dns par defaut.

**Comment by Che-debarras** [comment]
Merci je vais tester.

**Comment by Che-debarras** [comment]
Résolu en changeant dns 
Topic a fermer merci
