### ISSUE TITLE
Source Iptv

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2524]
Serait il possible d'ajouter cette source IPTV
ht tps://extinf.tk (iptv passion)
Je crois que c'est l'ancien ultimate iptv il ya de bonne chaines tv en tres bonne qualité 

Merci

**Comment by Arias800** [comment]
Ajouter dans la beta : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/freebox.py ^^
