### ISSUE TITLE
uptobox enlevé une etape inutile Mes Fichiers et Dossiers

### ISSUE THREAD

**Issue by moviefangithub** [Kodi-vStream/venom-xbmc-addons#2525]
Bjr
merci pour votre travaile!
quand on a un compte uptobox et quon veut lire les fichiers sauveragder dans le compte
il faut aller dans Mes comptes dans Uptobox et après dans Mes Fichiers et Dossiers, on pourait pas aller dirrectement dans Mes Fichiers et Dossiers, ça ferai une étape de moin à faire à chaque foi
merci!

**Comment by TmpName** [comment]
Franchement, je m'en suis jamais servi, mais il y a plein de tests qui se font sur la page que tu trouves inutile, verification de la presence d'un compte, connexion au compte si present, message d'erreur, ce n'est pas juste un menu, c'est plus une initialisation pour le fichier site.

**Comment by isandard** [comment]
par contre je me permet juste une autre remarque, est ce qu'il est possible de faire un tri en utilisant kodi ?

Car que je fasse un tri croissant ou décroissant, ca change rien.

**Comment by johngf** [comment]
c'est pas inutile a la basse c'est pour eviter d'avoir 100 ou plus sur une page 
pour ranger les serie etc...
pour ceux qui garde bcp de films series

**Comment by isandard** [comment]
En fait la le tri c'est que je fais des dossiers avec les liens que j'ai rajouté a mon compte mais des fois je le fais pas dans l'ordre et quand je veux mettre "lire à partir de ce fichier" je me retrouve a lire le 1 puis le 3 puis le 5.
Je sais absolument pas comment arranger ça meme sur l'interface uptobox qui, entre nous est bien pourrie en termes de fonctions.

**Comment by johngf** [comment]
ça c'est une option de kodi pas de vstream je sais pas comment ça fonctionne et si on peut mettre dans l'ordre

**Comment by isandard** [comment]
dans le menu à gauche où on a aussi l'affichage de la playlist ou le type d'affichage ( liste miniatures .........)

**Comment by johngf** [comment]
ba oui mais je ne l'ai pas moi peut etre il faut plusieurs liens

**Comment by johngf** [comment]
j'ai lire a partir de cette épisode >> je vais voir le fichier du menu

**Comment by isandard** [comment]
meme pas je viens te tester avec un lien unique
![image](https://user-images.githubusercontent.com/38729278/57537672-13964c00-7347-11e9-96f4-223ab6f47cae.png)

**Comment by johngf** [comment]
perso meme sur d'autre lien qu' upto je n'ai pas "lire à partir de ce fichier"

**Comment by isandard** [comment]
ah oups j'etais encore sur mon truc de tri, non c est dans le contextuel et je me suis planté dans le nom c est lire à partir de cet episode :
![image](https://user-images.githubusercontent.com/38729278/57538668-34f83780-7349-11e9-8eec-f724ab335cf6.png)
et au passage j'ai trouvé pour filtrer directement en fait dans le fichier siteuptobox.py il suffit de changer l'api_url : 
API_URL = 'https://uptobox.com/api/user/files?token=none&orderBy=file_created&dir=desc&offset=0&limit=100&path='

par : 

API_URL = 'https://uptobox.com/api/user/files?token=none&orderBy=file_name&dir=asc&offset=0&limit=100&path='

j'ai également changé le sens du coup car autant par date d'ajout c'etait bien de mettre les derniers en haut, autant par non c'est plus facile en alphabetique.

Apres est ce que c'est mieux je sais pas trop, pour moi ca depend des utilisations, par contre je connais pas du tout le python donc je ne saurais pas faire une option.

**Comment by isandard** [comment]
bon j'ai trouvé une modif qui me plait bien car sur la racine ( vu que c'est un peu le bronx ) je pense que c'est mieux sur la date d'ajout.
Mais dans les repertoires ( pour les series par exemple), je pense que par nom c'est mieux pour faire des playlists faciles :

j'ai rajouté : 
API_URL_F = 'https://uptobox.com/api/user/files?token=none&orderBy=file_name&dir=asc&offset=0&limit=100&path='

et à la ligne 138 dans

>

                for z in content[x]:
                    sTitle = z["name"].encode('utf-8')
                    sFoldername = z["fld_name"].encode('utf-8')
                    
                    sUrl = API_URL.replace('none',sToken)

j'ai changé par 

> 

                for z in content[x]:
                    sTitle = z["name"].encode('utf-8')
                    sFoldername = z["fld_name"].encode('utf-8')
                   
                    sUrl = API_URL_F.replace('none',sToken)

Par contre je suis pas sûr de la propreté et de l'optimisation ( je suis même sur que c'est nul mais ça marche )

**Comment by johngf** [comment]
ne met pas les liens en clair je regarderai demain pour moi il y a juste asc au lieu de desc

**Comment by isandard** [comment]
oui désolé un copier coller de code un peu rapide.
