### ISSUE TITLE
Replaytvstreaming

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#2527]
les replay sur Replaytvstreaming ne fonctionnent pas.
Que ce soit sur openload ou gounlimited je reçois le message " aucune information "
Pour info je suis situé en Belgique.
Merci à vous;

**Comment by TmpName** [comment]
Merci pour l'info, mit a jours sur beta a l'instant.

**Comment by Papounet58** [comment]
Super.
Bonne journée
