### ISSUE TITLE
Netu

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2528]
Bonjour,

netu est toujours inaccessible??

**Comment by Arias800** [comment]
Oui j'ai regarder il y a quelque semaine en arrière et il y avais toujours recaptcha d'activer ^^

**Comment by razorex** [comment]
Oui j'avais bien vu donc.
`<script src="https://www.google.com/recaptcha/api.js?render=6Ldf5F0UAAAAALErn6bLEcv7JldhivPzb93Oy5t9"></script>`
Merci

**Comment by TmpName** [comment]
Moi ca me manque aussi ^^.
Apres y en a bien un qui va craquer et sortir une lib pour ca, mais perso moi j'ai pas le temps pour ca, et a mettre en place sur kodi et toutes les machines possibles ca va etre la mort.
