### ISSUE TITLE
Problème avec plusieurs sources

### ISSUE THREAD

**Issue by abaylina** [Kodi-vStream/venom-xbmc-addons#2534]
**Décrivez le bug**
Je voie les liens mais rien ne ce lance ou pas vide. 
Sur hdss. Streming DivX. Straming k. 

**Votre system**
 - OS: [Android]
-  Appareil [note 10 et mxqpro]
 - Version Kodi  [18]
- Version Vstream 7.21 la dernière quoi

**Nous devons le reproduire**
Pour cela il nous faut:
- hdss. Stramingdivx
- games of Thones saison 8 
- Le nom du host (tous)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
On dirait que les sources bloque l'accès ou lien mort ?

**Comment by TmpName** [comment]
hdss HS, prb de mix clouflare+captcha
Streaming DivX Sur le sites, les liens sont morts aussi, Mystream fonctionne, je repare vidtodo.
Streaming k, 1 seul lien dispo, qui fonctionne, mais il n'y a que les epidodes pairs, pas normal.

**Comment by abaylina** [comment]
Génial 🤩 vstream le top du top .

**Comment by Che-debarras** [comment]
Depuis le dernier commit #df0e16e0,

aucun dossier/lien host à visionner pour
-kstreming
-Papstrem
-Stremzzz (error timeout)
-Stremingdix RÉSOLU 
-StremingK RÉSOLU

-Stremiz (liens manquants comparé au website , meme bug que stremcomplet?!)

Categorie qui s'ouvre pas:
-Filmstremvk
-Kaïdo
-Stremcomplet : maj manquant et seul l'host ok.ru s'affiche
Surement un site clone car le site Strem-complet.WS est maj et bcp plus de lien
Donc est-il possible de remplacer le site par celui avec un "-" et .ws?

**Comment by TmpName** [comment]
Sur Stremcomplet , y a plusieurs hosts ?

**Comment by Che-debarras** [comment]
Oui il y a plusieur host sur streamcomplet j'ai vérifié les sites car yen a  3 dont 2 sûrement des clones avec ce bug de host mais celui avec - et. Ws je pense que c'est l'original car il es mise a jour avec plusieur host

**Comment by TmpName** [comment]
Alors tu aurais un exemple de film avec plusieurs host ?
Je viens de retester et je n'ai qu'un seul host a chaque fois.

**Comment by Che-debarras** [comment]
Batman vs TMNT
![Screenshot_20190516-182050_Samsung Internet](https://user-images.githubusercontent.com/44464129/57870490-7be1a380-7807-11e9-92cf-19dd224adc73.jpg)


C'est stream-complet.me

**Comment by TmpName** [comment]
Ben moi je parle de celui de vstream, si tu chnages juste l'url ca ne marche plus, ce n'est pas les memes sites, les modifications sont minimes, mais ca ne marchera pas juste en changeant l'url.

**Comment by Che-debarras** [comment]
Ok si vous pouviez remplacer et faisant ces changement minime cela rendrait cette source plus intéressante car il y a bcp de sources qui semble ne plus se mettre a jour au niveau film

**Comment by Arias800** [comment]
kstreming corriger, pour Stremiz  ca va être plus long vu qu'il faut faire tout les hoster ^^

**Comment by Che-debarras** [comment]
Kstreming n'est pas résolu, il y a toujours aucun lien

**Comment by Mokoman30** [comment]
Salut tout le monde et Ianime sera corriger quand svp car il e en erreur :/ j en ai besoin

**Comment by TmpName** [comment]
Bon pour ianime, je bloque encore sur cloudflare, le code marche sur win 7, mais par sur kodi
J'ai mit a jour le fichier de la beta
J'utilise ce fichier pour le rendre compatible hors kodi https://pastebin.com/bUPFzKJA suffit de faire (  from config import GestionCookie, xbmc )

Mais j'arrive pas a voir ce qui chnage d'un systeme a l'autre. surtout que a marchait il ya 15 jrs.

**Comment by Che-debarras** [comment]
Depuis le dernier commit

aucun dossier/lien host à visionner pour
-iAnime RÉSOLU 
-kstreming
-kaydos
-Stremzzz (error timeout)

Stremcomplet : maj manquant et seul l'host ok.ru s'affiche
Surement un site clone car le site Strem-complet.me est maj et bcp plus de lien
Donc est-il possible de remplacer le site par celui avec un "-" et .ws?
-Stremiz (liens manquants comparé au website , meme bug que stremcomplet?!)

Categorie qui s'ouvre pas:
-Filmstremvk
-Sokostream

Merci

**Comment by Arias800** [comment]
- Sokostream le site lui-même est down
- Filmstremvk fonctionne chez moi (donne moi un exemple pour voir)
- kstreming fonctionne chez moi avec ma dernière modif donc si tu a un exemple je suis preneur
- Kaydo corriger https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/kaydo_ws.py
- Streamzzz ça vient du site 
- Stream complet passage au .me car plus de choix de hoster (manque un hoster a faire ): https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/streamcomplet.py
- Stremiz la raison n'a pas changer il car c'est tout des nouveau hoster

**Comment by Che-debarras** [comment]
Filmstremvk : je peut pas donner d'exemple car justement les categories ne s'ouvrent pas que ce soit film series ou animé, impossible d'y acceder

kstreming : meme problème que filmstremk sauf que tout les categories sont accessible mais vide


Streamzzz ça vient du site

Stream complet passage au .me : ya une erreur sur les liens host :upvid est toujours vide et streamango affiche un lien verystrem au lieu de stremango ex film Booksmart, ou the perfection 

Stremiz la raison n'a pas changer : j'ai pas saisi

**Comment by Arias800** [comment]
Filmstremvk et kstreming j'ai tester ceux sur la bêta et il fonctionne correctement chez moi donc je peux pas reproduire le bug
Stream complet : c'est sur le site ou il se sont tromper et qu'ils ont mis streamango a la place de verystream donc je n'y peux pas grand chose. Pour upvid c'est juste que ce ne sont pas des liens upvid mais jetload , un hébergeur qui été pas encore pris en charge par Vstream je viens de corriger ça
Stremiz : Je viens de le mettre a jour dans la bêta : https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/streamiz_co.py

**Comment by Che-debarras** [comment]
Ok merci c'est quoi ton appareil ? Version android ?
Moi je suis en android 6 sur kingbox k3 et c'est 2 sources filmstreamvk et kstreaming bug.

**Comment by Arias800** [comment]
Tout mes teste ce font sur Windows . Mais le probleme viens de la ` ERROR: CertificateError: hostname 'www.filmstr_amvf.com' doesn't match either of ...` et j’hésite entre deux chose soit c'est ton installe de Vstream qui pose probleme car tu a beaucoup d'addon et il ce peux que ça pose probleme ou alors c'est un probleme de liée a ton fournisseur internet.

**Comment by Che-debarras** [comment]
Je me suis connecté cette fois en partage réseau avec mon abonnement 4G et effectivement les 2 sources filmstreamvk et kstreaming fonctionne.
Comment permet au fournisseur d'internet d accepter ces 2 sources?

**Comment by Arias800** [comment]
Je sais pas trop peut être changer de dns ?

**Comment by Che-debarras** [comment]
Tu pourrais me dire comment faire ça stp merci

**Comment by Arias800** [comment]
Il y a 2 possibilité : sois la box Android propose une option pour configurer ca connexion internet sois dans le panneau de configuration de la box internet il y a une option pour changer de dns

**Comment by Che-debarras** [comment]
Effectivement changer dns resout le problème du moins sur smartphone car sur ma box tv je n'arrive pas a le changer (mais c'est ma box qui a un souci car après avoir changer dns la box le bug n'est pas résolu.

Donc je dirait que hormis sokostream et stremzzz dont le probleme vient de leur site, il y a aucun problème de bug pour les sources films series et animés.

Je tiens a vous remercier pour ces résolutions et votre aide.

J'aimerais savoir si on peut ajouter la source host direct dans la beta svp ce serait parfait

**Comment by Arias800** [comment]
Netu est désactiver et a mon avis il ne reviendra jamais.
Pour host direct on en parle ici comme ca c'est plus simple a suivre https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2510

**Comment by Che-debarras** [comment]
J'ai résolu le pb des 2 sources grace au dns mais ZT ne fonctionne pas avec changement de dns ou pas , j'ai bien acces au site grace au navigateur en Wifi ou en 4G mais pas avec vstream que ce soit en 4G ou wifi impossible d'ouvrir les categories
