### ISSUE TITLE
Juste pr info, vielle versions

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2535]
Juste pour info, je pense a supprimer les vielles versions de Vstream qui sont sur le github.
Pas sur quelles servent un jour, une seule fois j'ai du aller faire des recherches dedans, mais par contre pour ceux qui telechargent tout a chaque fois ca fait une archive enorme.

**Comment by Che-debarras** [comment]
Exactement c'est un lourd fichier zip et sur mon android tv ça met du temps car vstream ne semble pas se mettre a jour automatiquement ou alors avec une version anterieur.
La j'ai fait une maj automatique et ça me met une version avec des bug et wawacity present et c'est pourtant la version 0.7.21.

Comment mettre a jour avec les dernieres correction beta? Si possible automatiquement svp

**Comment by TmpName** [comment]
Ben tout est automatique, suffit d'attendre.

**Comment by Che-debarras** [comment]
Juste une question:les maj manuelle via l'onglet de kodi ne met pas a jour vstream avec la version beta? Mais avec la version Master de vstream?
Car quand je fait maj il remet une ancienne version où y a encore wawacity dans la liste des sources

**Comment by TmpName** [comment]
C'est normal. Il ne faut rien toucher et laisser faire, toute intervention provoque un retour arriere.
