### ISSUE TITLE
Uptostream limité 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2536]
Il y a de plus en plus de film qui durent plus de 2h sur ZT.
Est ce qu'il y a une façon de outrepasser cette limite de 2hr sur vstream ?
Si possible une solution gratuit 
J'ai voulu essayer l'addon dathovpn mais le site pour s'enregistrer a ete fermé 
Existe il un addon qui fait vpn?

**Comment by FireFirstAce** [comment]
Rien qu'en ayant un compte enregistré gratuit tu as 2h30 au lieu de 2h. Sinon hormis abo premium ou débrideur (qui revient vraiment pas cher à l'année franchement) pas sur que tu trouves un truc fiable au long terme...

**Comment by Che-debarras** [comment]
2h30? C'est mieux.
Quel est le meilleur débrideur ?

Merci

**Comment by tuego72** [comment]
real-debrid va bien

**Comment by FireFirstAce** [comment]
Je me sers de alldebrid moi. 

Les 2 sont très bien intégrés à Vstream grâce à Urlresolver.

D'ailleurs j'ai un ptit soucis : 

Comment forcer la lecture d'un fichier via uptobox et non uptostream ? Parfois ça lit l'un parfois l'autre... Gênant pour les fichiers avec sous titres incrustés ou les puristes niveau son/image (genre moi ou appelez ça casse bonbon 😂)

AVEC URLResolver et alldebrid activés et configurés. J'ai essayé en décochant "pick automatically best quality" dans les paramètres urlresolver mais c'est pas mieux (hormis me proposer la qualité voulue lorsque c'est uptostream qui est lancé)
Merci !
