### ISSUE TITLE
problème avec zone telechargement et urllib

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2537]
**Décrivez le bug**
Impossible d'accéder à la source du fichiers 

**Votre system**
 - OS: [Windows, Android]
-  Appareil [PC, Xiaomi mi box ]
 - Version Kodi  [17.18]
- Version Vstream la dernière version

**Comment by AzeRim** [comment]
En remettant cette version https://github.com/Kodi-vStream/venom-xbmc-addons/blob/1b75c434357559b4cff3de1ae575685a6efee157/plugin.video.vstream/resources/lib/cloudflare.py on a de nouveau accès au lien. Déjà 11 mise à jour de ce fichier depuis le 22 mars.

**Comment by lefou66** [comment]
Même problème chez nous aussi mais sur une boîte Android sur deux.Jme demande si la version de Kodi est la cause...marche avec Kodi 18.1 mais pas avec Kodi 18.2. 
Aussi DDL fonctionne pas depuis un bout...des update sur celui là?

**Comment by Lioon2** [comment]
Merci azerim, ça refonctionne !

**Comment by Lioon2** [comment]
update : ça ne fonctionne plus avec la dernière maj de cloudflare.py, remettre la version d'AzeRim permet de corriger le tir

**Comment by TmpName** [comment]
Encore une nouvelle version de cloudflre, corrigé pour mangacty, mais qui devrait marcher aussi aussi pour ici.

**Comment by Ovni-crea** [comment]
merci c'est réglé

**Comment by Lioon2** [comment]
à nouveau en panne

**Comment by Arias800** [comment]
J'ai fait un test en passant par requests pour voir si ca tiens mieux ^^
