### ISSUE TITLE
G_unlimited bug

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2538]
**Décrivez le bug**
Les liens Gounlimited ne se lance pas

**Votre system**
 - OS: [Android]
-  Appareil [kingbox k3]
- Version Vstream 0.7.21

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site :............series-streaminghd
- Le titre du fim/serie......hawai 5.0
- Le nom du host.............gounlimited

**Comment by johngf** [comment]
pas de bug ... juste un petit hébergeur donc la hd c'est limite et quand il y a trop de monde dessus (en fonction des heures) fonctionne pas >>> timeout

**Comment by Che-debarras** [comment]
Effectivement je viens de relancer l'épisode et ça refonctionne. Merci pour l'info
