### ISSUE TITLE
Categorie de source

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2540]
Je me demandais si dans les categories de vstream notamment dans films on pouvait avoir la categorie film 4k qui répertorie les sources qui contienne les films serie etc en 4k.

Je sais qu'il y a Zt et wawacity mais je pense que des sources 4k serait le bienvenue. C'est juste une idée .

**Comment by TmpName** [comment]
Trop peu de sources, le 4k en streaming n'existe pas, reservé a une elite.

**Comment by Che-debarras** [comment]
Ok merci.
