### ISSUE TITLE
Iptv bug

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2544]
**Décrivez le bug**
Iptv EXTINF n'affiche aucun lien m3u
Pareil pour Iptvgratuit la chaîne tv sélectionnée s'ouvre comme un dossier au contenu vide

Nb: est il possible d'ajouter iptv4sat.com svp

Merci

**Votre system**
 - OS: [android]
-  Appareil [k3 et s8+]
 - Version Kodi  [18 &.19]
- Version Vstream 0.7.2.1 6a9f3ae9

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site IPTV Site puis Extinf 
-

**Comment by Arias800** [comment]
Corriger : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/freebox.py
Rajouter iptv4sat n'est pas utile puisque qu'iptv gratuit utilise les liens d'iptv4sat ^^

**Comment by Che-debarras** [comment]
Je suis pas sur qu'il utilie les même liens et je vois certaines playlistes qui ne sont pas sur iptvgratuit.
Et dailyiptv aussi a des playlists en commun.
Je me suis dis vu les soucis de iptvgratuit une autre source serait utile.
Sinon merci

**Comment by Arias800** [comment]
Ah bon bah je ferais la bascule ^^
Pour afficher en catégorie le probleme c'est que toi est dans un seul fichier car je ne me suis pas encore lancer dans la séparation en différente partit donc pour le moment c'est non mais quand tout sera séparer pourquoi pas ^^

**Comment by Arias800** [comment]
@Che-debarras voila j'ai séparer tout les sites d'iptv et du coup j'ai ajouter le reste des catégorie , j'ai aussi remplacer iptv gratuit par iptv4sat ^^

**Comment by Che-debarras** [comment]
Alors je sais pas quoi dire c'est magnifique clean et on s'y retrouve facilement.
Un grand merci pour ce travail qui a du prendre bcp de temps.

**Comment by Arias800** [comment]
J'avais surtout peur de casser des chose en déplacent tout mais finalement ca va je m'en suis pas trop mal sortit xD

**Comment by Che-debarras** [comment]
Juste un pti souci avec extinf.
La categorie par pays n affiche pas les pays commençant par A 

Et aussi aucun des chaines ne se lance quelque soit les sources iptv

**Comment by Arias800** [comment]
J'ai corriger le bug des A par contre chez moi les chaines ce lance quand elle marche , Tu a f4mTester et f4mProxy d'installer car sans les chaine ne se lance pas ? ^^

**Comment by Che-debarras** [comment]
Tinkiete pas je regarde souvent les chaines je crois que le souci  est que il y a 2 fois extinf.py l'un nommé extinf et un autre iptv.py sur la liste des sources et c'est celui nommé extinf qui a le bug des chaines "A"
 
Dans televison direct/stream c'est toujours affiché extinf et non iptv (iptv passion)

**Comment by Arias800** [comment]
Les deux fichier c'est parce que @razorex a changer le nom de extinf en iptv donc celui utilser c'est iptv et n'ont pas extinf . Et le nom je ne l'ai pas changer pour pas gêner les personne qui potentiellement utilise cette source ^^

**Comment by razorex** [comment]
Salut. dsl d'avoir renommé ton fichier. Tu peu aussi le renommer iptv dans le fichier freebox, c'est l'url extinf et elle évoluera peut etre. et au moins ce serais plus clair. le site s'appelle IPTV..

**Comment by Arias800** [comment]
OK bon bah je changerai ca quand je metterai a jour freebox ^^
