### ISSUE TITLE
12 sites de streaming fermés

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2545]
Je met cette info pour ceux qui ne sont pas au courant et qui se demanderai pourquoi le site fonctionne pas.
J'ai pas la liste complète et apparemment les sites sont encore en hébergement.
Parmi les sites fermés il y a series-en-streaming.tv, seriefr.eu, seriefr.xyz, full-stream.ws et dpstream.co.

**Comment by TmpName** [comment]
Ha oui je viens de tomber dessus, apprement c'etait le meme mec qui gerait tout ces sites.

**Comment by lebigboss** [comment]
@TmpName  J'avais pas vue ça. J'ai vue des infos comme quoi le mec faisait un petit business
, La police lui a saisi 8 bitcoins, en faite il faisait miné les visiteurs du site sans qui le sache.

**Comment by TmpName** [comment]
Bon ben je sais pour les 12 sites, mais y en a plein qui ont un bloquage dns, donc mon chouchou voirfilm.
