### ISSUE TITLE
TV du Web (iptv officiel)

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2546]
Depuis quelque semaine je me suis mis ajouter au fur et a mesure de nouvelle chaine en utilisant les liens officiels mis a disposition par les chaines donc je pense que faire une issue pour regroupe chaque ajout et permettre au gens de demander des chaines peut être une bonne idée. Attention quand je parle de

>  liens officiels mis a disposition par les chaines 

je parle de liens officiel gratuit.
```
Liste des chaines deja disponible : 
  - Arte
  - BFM Buisness
  - BFM TV
  - C8
  - Canal + (uniquement pendant les période la chaine est en clair)
  - CNEWS
  - CStar
  - France 2
  - France 3 
  - France 4
  - France 5 
  - FranceInfo
  - France O
  - Gong
  - Gong Max
  - Gulli
  - L'equipe 21
  - LCI
  - LCP 100
  - LCP assemblée national
  - Nrj 12
  - Rmc Decouverte
  - Rmc Story
  - TF1
  - TF1 Series et Films
  - TFX
  - TMC
  - Virgin radio tv

Liste des chaines qui vont être ajouter  :
  - Cherie25
```

**Comment by TmpName** [comment]
Ya un lien officiel pour tf1 ?

**Comment by Arias800** [comment]
Oui pour l’obtenir c'est ici : https://delivery.tf1.fr/mytf1-wrd/L_TF1?format=hls

**Comment by TmpName** [comment]
Tiens c'est marrant, moi a l'epoque c'etait les seuls que je trouvais pas en legal, vu que pas dispo sur leur site officiel.

**Comment by Arias800** [comment]
Visiblement ils ont trouver un intérêts de le faire et tant mieux ^^

**Comment by Che-debarras** [comment]
Sauf qu aucune chaine ne se lance. Pourquoi?

**Comment by Arias800** [comment]
Effectivement j'ai casser un truc involontairement je corrige ça xD

**Comment by Arias800** [comment]
Corriger : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/freebox.py

**Comment by Arias800** [comment]
J'ai ajouter Virgin Radio Tv et TMC a la liste des chaines ^^
