### ISSUE TITLE
Nouvelles sources Asiatique?!

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2547]
Je vois qu'il manque cruellement des sources de series asiatiques alors je me demandais si ces sources peuvent etre ajoutés:..
Viki.com
otakuji.com
anime-saijou.com
dramapassion.com
dramacoreen.co
dramasvostfr.com 
dramavostfr.net
myasietv.net

Je sais que c'est un peu beaucoup mais ça apportera un petit plus d'avoir des sources spécialisées autre que mangas vostfr

**Comment by lebigboss** [comment]
Je suis fan du cinéma coréen en plus.
Merci pour la liste je vais les visités

**Comment by Che-debarras** [comment]
Il y a l application viki rakuten qui contient pas mal de serie asiatique vostf malheureusement il nont pas de site web pour l'inclure sur vstream

**Comment by Makoto83** [comment]
J'ai créé la source Otaku-attitude il y a pas mal de Dramas allez voir 😁

**Comment by johngf** [comment]
pourquoi vous n'essayez pas de créé des sources vous-mêmes ?  il n'y a rien de compliqué faut juste s'y mettre.
- https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_un_hebergeur.py
- http://www.vstream.ml/docs/add/
- apres vous pouvez demander de l'aide ici après recherche minimum sur google, stackoverflow etc... pour python

**Comment by TmpName** [comment]
Merci @Makoto83, je l'avais pas vu car encore en beta, mais pareil on aime bien les dramas pr changer.

Apres pour reprendre ce que dis @johngf, personnellement je ne rajoute jamais de nouvelle sources (sauf si j'en ai besoin moi meme, mais la derniere doit avir plus d'un an), y a assez de boulot a maintenir celle deja en place.
Il n'y rien de magique, ca va piquer un peu quand vous allez decouvrir les regex, au pire avant de perdre votre temps vous pouvez demander si c'est bien realisable, si trop grosse protection sur le site par exemple.

**Comment by Arias800** [comment]
Et après vous pouvez aussi me mp sur Discord si vous voulez de l'aide  .Après moi je rajoute des sources mais c'est sois parce qu'elle propose des choses qui sont disponible en petite quantité sois ce sont des sources qui ont leurs propre lecteur pour moins être dépendants d'op_nload et compagnie en cas de panne ^^

**Comment by Makoto83** [comment]
Je préfère quand même les sites qui font leur propre streaming j'ai d'autre source que j'ai personnellement comme Ottaku-attitude du genre , Anime-ultime ou sky-anime que j'ai pu finir avec l'aide @Arias800 merci à toi au passage ;)

**Comment by Makoto83** [comment]
Je partage la source que je viens de finir [Otakuji.com](https://pastebin.com/cUrfiNzL) par contre il y a énormément de liens qui ne fonctionne pas sur leurs site ^__^

**Comment by TmpName** [comment]
Tu veux le garder en privé celui la ? ou tu veux aussi le rajouter aux sites de Vstream ?

**Comment by Makoto83** [comment]
Comme vous voulez mais vu le peux de liens qui fonctionne je sais pas a vous de voir 😁

**Comment by Che-debarras** [comment]
Moi je suis pour le rajouter 😉

**Comment by AzeRim** [comment]
@Makoto83 Pourrais-tu partager ton fichier sky-anime? Merci

**Comment by Makoto83** [comment]
Pas de soucis ;) ils sont fonctionnel mais pas optimiser ;) du coup je partage aussi anime ultime
[Sky-Animes.com](https://pastebin.com/H76XZ5Le)
[Anime-Ultime.net](https://pastebin.com/YFANy9pD)

**Comment by Che-debarras** [comment]
@makoto83
J'ai ajouté tes 2 sources animé mais il apparaisse pas sur la liste de sources

**Comment by Makoto83** [comment]
@Che-debarras hm bizarre pourtant j'ai bien les fichiers dans sources :x
tu les a biens copier dans plugin.video.vstream/resources/sites ?

**Comment by Che-debarras** [comment]
Oui dans le bon dossier
Est tu sur du nom? Car dans les fichiers .py le seul symbol qui est dans les noms sont "_" et pas de "-"?

**Comment by Makoto83** [comment]
Alors effectivement si tu as marquer comme j'ai écrit ici ça ne fonctionnera pas désolé c'est marquer dans les fichiers 
SITE_IDENTIFIER = 'skyanimes'
SITE_IDENTIFIER = 'animeultime'

donc skyanimes.py et animeultime.py

**Comment by Che-debarras** [comment]
Lu Corrigé Testé et Vérifié : fonctionne. Merci

**Comment by Makoto83** [comment]
De rien @Che-debarras amuse toi bine surtout que se sont des liens directs ;) donc du streaming pur :D

**Comment by TmpName** [comment]
@Che-debarras il y a une option justement par activer/desactiver les sources dont tu ne te sert pas.
Elles n'aparaitront que dans "toutes les sources".
Apres non, ce n'est pas specialement au createur de la source de reparer, quand c'est une source speciale comme l'iptv (petite dedicace au masoshiste qui a voulu remettre ca en place), je veux bien, mais les autres sont standards, tout le monde peut y jeter un oeuil, surtout quand c'est juste un chagement d'url.
Apres moi je comprend que certains veuillent garder leur source en privé, et j'ai jamais refusé une source, meme incomplete ou bugguée, suffit juste de pas l'activer, si tu la veux pas.
Si elle est sur le github, elle restera viable plus longtemps (plus fiable que pastebin) et surtout elle aura des testeurs.

**Comment by Arias800** [comment]
Ceci dit l'iptv maintenant que j'ai séparer tout les site ça devient des site classique faut juste pas toucher au fichier freebox qui centralise tout xD

**Comment by AzeRim** [comment]
@Makoto83 Merci mais pour anime-ultime ça bloque sur le menu recherche/animes/dramas/tokusatsu

**Comment by Makoto83** [comment]
@AzeRim  Comprend pas ?

**Comment by AzeRim** [comment]
@Makoto83 en faite ça fonctionne Je l'aV renommé ultimeanime au lieu de animeultime
Merci. C koi ton mp en cas de soucis?

**Comment by Makoto83** [comment]
Je suis sur discord sous le pseudo Zeigadis ^___^

**Comment by AzeRim** [comment]
ok merci

**Comment by Che-debarras** [comment]
@tmpName justement c'est ton ps qui est pertinent quand je desactive ça ne fonctionne pas toujours quand je fait les petit maj.

NB: donc pour les sources que j'ai cité dans mpn 1er poste il suffit que je prend nimporte quel source.py et je remplace Url?

**Comment by johngf** [comment]
non @Che-debarras il faut récupérer la page html grâce a l'url ensuite grâce au regex récupérer les la partie que tu veux.
ça a l'air compliqué au début mais en faite pas du tout 
- la je souhaite récupérer la valeur de srv  >> https://regex101.com/r/2xgO2f/1
