### ISSUE TITLE
Zone Telechargement 

### ISSUE THREAD

**Issue by Karnia** [Kodi-vStream/venom-xbmc-addons#2552]
**Décrivez le bug**
Impossible d'accéder à la source Zone Telechargement
Lorsque je clic dessus il ne se passe rien

**Votre system**
 - OS: Android
-  Appareil Mi Box
 - Version Kodi  dernière version
- Version Vstream  dernière version

**Plus**
Dans le fichier zone_telechargement_ws.py
Ligne 69, si on remplace la ligne par 
`URL_MAIN = 'https://wwvvv.annuaire-telechargement.com/'`
Cela fonctionne plus ou moins, le site réponds mais la recherche semble ne pas fonctionner correctement

Sinon, quelqu'un aurait développé un connecteur qui tape sur ZT.lol ?

**Comment by Arias800** [comment]
Le probleme c'est que ZT lol faut refaire la totaliter du fichier et un zt c'est deja assez dur a maintenir . J'ai d'ailleurs fait une modification pour le probleme de l'url hier et pour le moment ca a l'air de tenir

**Comment by Karnia** [comment]
Pour récupérer la modification que tu as fait hier comment je fais ?

Et pour ZT.lol j'imagine bien ^^, on a pas des experts volontaire pour ca ?
Je pense en être capable mais je la que cruellement de temps.. 
Si j'avais un début de script fonctionnel je pourrais le compléter au fur et à mesure

**Comment by Arias800** [comment]
Ca sert a rien que tu assez la modif d'hier car elle ne marche pas .
Ensuite le probleme de zt lol c'est que personne ne se lance a le faire car rajouter un clone ne sert pas a grand chose en plus qu'on a deja assez de travail avec les sites deja ajouter  ^^

**Comment by Arias800** [comment]
Bon j'ai essayer de corriger pour mettre a jour le fichier il faut prendre ce fichier : https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py et le mettre a la place du fichier zone_telechargement_ws qui se trouve dans le dossier site de vstream

**Comment by Karnia** [comment]
Merci pour le fichier
Je viens de tester et en effet j'arrive à parcourir la source ZT désormais 
Par contre la recherche ne fonctionne pas :(...
J'essaye par exemple avec "Manifest" et je ne trouve pas la série en ligne resultat :/...
Une idée pour résoudre ce problème ?

**Comment by Arias800** [comment]
La recherche c'est le bazar et c'est une horreur vraiment meme sur le site elle ne marche pas correctement donc j'essayerai demain mais je garantie rien xD

**Comment by Karnia** [comment]
Oui en effet ^^ mais si à minima ça peut donner les même résultats c'est pas mal :)

Le site zt.lol est quand même beaucoup mieux foutue ^^
Faut que je trouve un homme courageux pour l'implémenter :p...

Le dim. 9 juin 2019 à 21:20, Arias800 <notifications@github.com<mailto:notifications@github.com>> a écrit :

La recherche c'est le bazar et c'est une horreur vraiment meme sur le site elle ne marche pas correctement donc j'essayerai demain mais je garantie rien xD

**Comment by Arias800** [comment]
Je viens de vérifier la recherche sur le site ne retourne pas Manifest mais juste du catch et Vstream l'affiche donc je pense que tu parle pas du bon site (annuaire-telechargement com)

**Comment by Arias800** [comment]
@TmpName j'essaie de remettre l'ancienne recherche de zt mais le contenu de la page est compresser et je n'arrive pas a la décompresser : https://github.com/Arias800/Fichier-divers/blob/master/zone_telechargement_ws.py

**Comment by TmpName** [comment]
Moi, j'ai cloudflare qui se met en route, ya un prb avec ce site en post.

**Comment by Arias800** [comment]
Hum bon faudra que je face d'autre test hors Kodi alors ^^

**Comment by TmpName** [comment]
Attend je re-essaye, c'est une protection cloudflare, mais la meme, juste une en fonction des headers.

**Comment by TmpName** [comment]
Mais c'est pas du POST chez moi, mais du GET ? Jai pas la bonne url ?  je suis sur le .fr ?

**Comment by Arias800** [comment]
Normalement c'est celle donner par la redirection a partir d'ici : zone-telechargement.ws . Mais c'est pour la vieille recherche car la nouvelle ne marche pas correctement de leurs coter ^^

**Comment by TmpName** [comment]
Ha ok, ben la vielle marche pas de mon coté, j'ai ca comme erreur "<p>This website is using a security service to protect itself from online attacks.</p>" erreur 403

Si je desactive le post ca remarche, mais sans les resultats bien sur.

C'est quoi le prb avec la nouvelle version ?

**Comment by Arias800** [comment]
Ah bon bah je pense que ca va rester comme ca xD
En faite la nouvelle version n'est pas trop fonctionnel car elle renvoie des resultat approximatif et en bonus a chaque changement de page ca renvoie la meme liste de film et de serie mais avec un elements en plus a chaque fois (donc ca donne par exemple plus de 98 pages des fois ) xD

**Comment by TmpName** [comment]
Pour les resultat approximatif, y a une fonction de filtrage sur certaines sources, apres pour leur bug par contre ...

**Comment by Makoto83** [comment]
Salut apparemment l’adresse a changé !!! maintenant c'est https://www.annuaire-telechargement.cc/

**Comment by Arias800** [comment]
C'est bien la deuxième adresse la bonne et elle marche chez moi ^^

**Comment by Makoto83** [comment]
Mince Chez moi sa marche pas la deuxième adresse

**Comment by Arias800** [comment]
Peut être qu'il y a trop de monde connecter dessus ^^

**Comment by Makoto83** [comment]
Non ça me dit carrément :
Ce site est inaccessible Impossible de trouver l'adresse IP du serveur de ww.annuaire-telechargement.com.
Essayez d'exécuter les diagnostics réseau de Windows.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Arias800** [comment]
Ah bizarre faut voir si il remarche pendant la soirée

**Comment by Makoto83** [comment]
Ouais je vais essayé de changer mon ip pour voir si ça passe ou pas :x

**Comment by hylliotv** [comment]
Moi aucun bug et c’est toujours lui je me sert j’ai pas plus que la dernière update dans vstream aucun bêta et numéros 1 ici j’écoute des série

**Comment by Makoto83** [comment]
moi sur vstream ou n'importe quel navigateur a la maison même en 4G j'ai aucune connexion :x

**Comment by Makoto83** [comment]
Bon je viens de passé par un VPN je crois que c'est Bouygues Telecom qui bloque !!!

**Comment by Arias800** [comment]
C'est possible effectivement ^^

**Comment by Makoto83** [comment]
Ouais je viens de changer les DNS de Bouygues Telecom par ceux de FDN pour le moment ça marche ;)

**Comment by jesusisback66** [comment]
je confirme Bboxfibre c'est bouyg qui bloque je suis passé par un autre dns ZT marche

**Comment by sizanic** [comment]
Juste pour vous annoncer que j'ai commencé un fichier ZT.lol et que j'avance bien.
Donc pour info, pour pas qu'on soit plusieurs dessus en même temps.
Une première livraison dans la semaine.

**Comment by Karnia** [comment]
@sizanic ah super! merci!
On avait rapidement commencé avec @Makoto83 , je devais continuer mais j'ai beaucoup de mal à trouver du temps malheureusement...
Merci à toi en tout cas si tu prends le temps de le faire :)
Hâte d'avoir ça ;)

**Comment by jesusisback66** [comment]
Je me demande a quoi cela va servir ? Car au final il suffit de changer de
DNS

**Comment by jesusisback66** [comment]
Même avec les DNS de FDN cela ne fonctionne plu ainsi que la Source streaming HD

**Comment by Arias800** [comment]
Zone telechargement corriger a c'etait a cause de Cloudflare par contre Source streaming HD est down ^^

**Comment by jesusisback66** [comment]
@Aria800 pour ZT il faut attendre la maj de vstream ? Ou c'est bon la ?

**Comment by Arias800** [comment]
Il faut attendre la mise a jour a moins que Cloudflare ne se debloque tout seul mais je pense pas ^^

**Comment by jesusisback66** [comment]
@Arias800 je viens de test c'est revenu ZT est de nouveau opérationnel donc cloudflare c'est débloquer

**Comment by Arias800** [comment]
D'accord ^^

**Comment by ethanael83** [comment]
Bonjour est ce que ZT marche de nouveau chez vous?
Le site hs et sur vstream je peux voir les liens mais ils ne s'ouvrent pas.

**Comment by Che-debarras** [comment]
@ethanael83
Essaye en changeant le DNS ça résout les problèmes car les sites de streaming font l'objet de contrôle par hadopi pour les interdire et en ce moment les FAI les bloque .
J'utilise une appli "DNS changer" et j'ai accès a ces sites qui sont vides

**Comment by sizanic** [comment]
Et voilà.
J'ai une première version du fichier ZT.lol à proposer.

Par contre je pense que l'URL va changer, comme elle l'a déjà fait précédemment.
Mais que le vrai site derrière c'est 'tirexo'.

Alors je ne veux pas appeler cette source "ZoneTelechargement_lol" (pour bien la séparer de la vrai également) mais "tirexo".

ça vous va ?

**Comment by Makoto83** [comment]
Fais donc 😁 @sizanic

**Comment by sizanic** [comment]
La pull Request est dispo 
https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2568
