### ISSUE TITLE
Fichier setting

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2554]
Pb avec le fichier setting situé sous kodi\userdata\addons_data\plugins.video.vstream.

Dans ce fichier qui ce met à jour avec la mise à jour hebdo il reste encore des traces de sources supprimer depuis qq temps. et tout les clean n'y change rien. A contrario les ajouts apparaissent correctement. N'est pas du au fait que le fichier site.json ne soit pas maintenu a jour???
pareil pour le fichier hoster.json

**Comment by TmpName** [comment]
Les deux derniers fichiers ne servent plus, pour le fichhier setting, il faut le mettre a jours a la main a chaque MAJ, je le met a jour bientot, le temps que @Arias800 mette en place sa derniere trouvaille et qu'il y ait quelques tests.
Tu peux le modifier si tu veux, mais dans tout les cas, je referais un checkup au moment de la MAJ.

**Comment by razorex** [comment]
Ce n'est pas ce fichier setting regarde l'adresse..

**Comment by TmpName** [comment]
Ha oui, lol, désolé, le mien doit avoir 4/5 ans, j'aurais cru qu'il y avait tant de bordel dedans. C'est les reglages de Vstream, memorisé sur kodi.
Mais la dommage, d'apres leur doc http://mirrors.kodi.tv/docs/python-docs/13.0-gotham/xbmcaddon.html tu peux rajouter des setting, les modifier, mais pas les supprimer.
Normallement, si tu supprimes toi meme le fichier, tu perd tout tes reglages, mais le fichier est refait a neuf.

**Comment by razorex** [comment]
C'est ce que j'ai fais. oui on refait m^me la mise à jour mensuelle.
