### ISSUE TITLE
Acces compte  uptobox prenium par vstream avec vpn non francais bloqué

### ISSUE THREAD

**Issue by 31rems31** [Kodi-vStream/venom-xbmc-addons#2555]
Problème d'accès au compte uptobox prenium par vstream derrière un serveur vpn non Français 

Saut à tous,
Je viens de remarquer que si je positionne mon VPN (expressvpn) hors de la France, l'authentification de mon compte prenium uptobox m'est refusé.

Boitier android H96 PRO+
OS android 7.1.2
version kodi 17.6 Krypton
version vstream 0.7.22

Dès que je remets une connexion à un serveur Fr, l'authentification de mon compte prenium uptobox par vstream est de nouveau acceptée.

Est-ce normal ?

Merci de vos retours.

**Comment by TmpName** [comment]
La je peux pas te dire, tu as essayé sur un navigateur ?

**Comment by 31rems31** [comment]
Salut,
Exact ! 👍 en fait il faut faire une connexion sur le compte prenium direct sur le site avec la nouvelle @ip. Ca envoie automatiquement un mail de demande de validation de cette adresse et ça débloque la connexion avec vstream !
Merci de votre aide 👍
