### ISSUE TITLE
Reprise automatiquw

### ISSUE THREAD

**Issue by Jocean69** [Kodi-vStream/venom-xbmc-addons#2556]
Bonjour,
Depuis +/- 2 mois, sur vStream, quand j'arrive a la fin d'un film ou d'un feuilleton, au lieu de s’arrêter, ça reprend le film au début, Je n'ai rien fait de spécial, ça c'est mis a faire ça du jour au lendemain, une idée pour remédier au problème?
Merci pour vos réponses

**Comment by lebigboss** [comment]
Ça n'a rien a voir avec Vstream.
En faite quand tu lis une vidéo, pendant que la vidéo tourne, tu reviens au menu d'avant.
Liste de lecture
![IMG_20190614_070052](https://user-images.githubusercontent.com/12912677/59484557-904ea580-8e72-11e9-932b-df7967d5864f.jpg)
Et ensuite tu cherche "Répéter" et tu met non
![IMG_20190614_070105](https://user-images.githubusercontent.com/12912677/59484584-a9575680-8e72-11e9-9d77-95e738b26b69.jpg)

**Comment by Jocean69** [comment]
AAAAAAAAAAAAh, merci Bigboss! C'était bien ça! Et ça devenait très pénible a la longue...
Merci a toi!
