### ISSUE TITLE
surce

### ISSUE THREAD

**Issue by yokoya06150** [Kodi-vStream/venom-xbmc-addons#2559]
comment ajoute des surce

**Comment by razorex** [comment]
En modifiant ce [fichier ](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_une_source.py)avec ta source. dispo depuis l’accueil du git vstream.

**Comment by yokoya06150** [comment]
pas compris

**Comment by TmpName** [comment]
Lol.
Regardes le fichier qu'il a linké, en fait c'est a toi de faire la source, donc faut apprendre las bases du python, et pas paniquer en arrivant au regex.

Et non, on se fout pas de toi, ca a l'air infaisable, mais plein y arrivent.

On rajoute rarement des sites nous memes, car il y a deja beacoup de boulot a tenir en place les existantes, par contre on peut aider.

**Comment by TmpName** [comment]
C'est je l'ai retrouvée https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source
