### ISSUE TITLE
N_tu bug

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2560]
**Décrivez le bug*
Le captcha marche bien mals la lecture bug, il y a des sauts d'images qui nous fait  manquer quelque seconde d'image.

Est ce normal?
D'autres à ce souci?

**Votre system**
 - OS: [Android 6.0]
-  Appareil [K3 kingbox]
 - Version Kodi  [19]
- Version Vstream 0.7.3

**Nous devons le reproduire**
Pour cela il nous faut:
- streaminghd
- murders ou tout autre series avec netu
- Le nom du host (N_tu)

**Comment by lebigboss** [comment]
Rien a voir mais tes vraiment sur Android 6.0 et ta vraiment Kodi 19 ?

**Comment by Che-debarras** [comment]
Oui je suis bien sur android 6.0 et kodi 19 pourquoi ?
Tous fonctionne très bien

**Comment by Arias800** [comment]
Je pense pas que ce soit un bug de Vstream car normalement Vstream récupère juste le liens et l'envoie a Kodi après c'est lui qui s'occupe du reste donc logiquement c'est pas liée a Vstream (après je n'ai jamais eu ce bug car je n'utilise pas beaucoup N_tu )
En ce qui concerne Kodi 19 au bout d'un moment tu va te retrouver bloquer puisqu'il finiront par désactiver python 2 et a partir de ce moment la Vstream ne marchera plus tant que la conversion ne sois pas finit ^^

**Comment by Che-debarras** [comment]
Merci Arias800
Pas de souci pour kodi je sais a quoi m'attendre mais je crois qu'il  y a 2 versions de kodi 19 donc un je pense a python 2 désactivé nom de code Leia parmi les nighy mais celui que j'utilise c'est la maj de la version Master.
Donc tot ou tard les addons  devront se mettre a python 2 si c'est pas  le cas de vstream je rétrograderait kodi qui fonctionne.

J'utilise plus N_tu depuis son desactivation mais si tu regarde un épisode tu vera que apres quelques minute il y a un saut de  quelques seconde avec du vert sur l'image.

Avant sa désactivation il y avait pas ce problème et j'utilisais constamment N_tu.
Donc si quelqu'un peut me dire s'il a ce problème et a quoi c'est du svp

**Comment by johngf** [comment]
c'est parceque c'est du m3u8 donc pas de cache

**Comment by Che-debarras** [comment]
Ok effectivement c'est souvent du hd ou fhd mais il me semble que kodi met en cache lui non?
Les iptv aussi sont souvent en m3u8 ou m3u et kodi les met en cache pourquoi pas avec N_tu?
J'utilise les hosts de dpstrem.cx qui n'ont pas ce souci de bug mais n_tu semble avoir de meilleur qualité.
Merci pour l'explication même si ya pas de correction posssible

**Comment by johngf** [comment]
kodi ne met pas en cache le m3u8 jamais .
pour iptv c'est grace a un autre addon f4m que ça plante pas

**Comment by Che-debarras** [comment]
Jetais persuadé qu'il mettait en cache, Merci bcp pour ce code que tu testeras
Ce code marchera pour tout? Même iptv?
F4m c'est pas tres stable non plus ça s'arrête souvent apres une certaine durée  plus ou moins longue
C'est la raison pour laquelle je met a jour avec les derniers version de kodi 19 car iptv addon de kodi est mise a jour en version 4.0.2 donc ya un peu d amélioration mais toujours pas stable

Bon courage
