### ISSUE TITLE
LiveTV 

### ISSUE THREAD

**Issue by faribole** [Kodi-vStream/venom-xbmc-addons#2561]
Je viens de mettre à jour la dernière version de vstream sur mon téléviseur et je constate que LiveTV a été supprimé de la section sport. Dommage car cela fonctionnait plutot bien étant donné que la plupart des liens iptv sont hs.
Est-ce une suppression temporaire ? Allez-vous remettre en place LiveTV ?
Merci

**Comment by Arias800** [comment]
C'est surement une erreur de manipulation je vais le corriger pendant ce temps elle est toujours accessible dans le menu source ^^

**Comment by marcoLPT** [comment]
je vais arrêter de chercher alors :-D

**Comment by Arias800** [comment]
Corriger dans la prochaine maj c’était bien une erreur de ma part désoler ^^
