### ISSUE TITLE
LibertyVF

### ISSUE THREAD

**Issue by Jur4ssic** [Kodi-vStream/venom-xbmc-addons#2562]
il serais pas mal de pouvoir ajouter ce site il en aiderais pas mal a trouver leu bonheur

h ttp://li bertyvf.co/

**Comment by Arias800** [comment]
Il y a la vrai version disponible sur Vstream sous le nom Libertyland car le liens que tu a donner est un clone ^^

**Comment by Jur4ssic** [comment]
ah oui d'accord car moi je le trouve vraiment très complet ce "clone" comparer au vrai, mais merci quand même d'avoir répondu et maintenant je sais pourquoi il n'a pas été rajouter

**Comment by Che-debarras** [comment]
@Jur4ssic
Je te rejoins sur ce coup car il est vrai que des fois les clones sont plus complet et plus de liens.
Mais il y le fameux host direct qui comble le souci donc je pense le mieux est d'ajouter des sources différentes pour diversifier comme des sources de drama ou film asiatique ou version Vavoo de vstream pour ce qui comme moi utilise que vstream (ce serait peut etre une idée quand python sera désactivé)

Vstream est très complet déjà les sources asiatique serait la cerise sur le gâteau mais vu la période faut plutôt se contenter de ce qu'il y a car je suppose certains développeurs sont en examens ou merite aussi des vacances.

Souhaitons plutôt du repos a ces personnes qui vont vivre Vstream depuis si longtemps.

**Comment by Jur4ssic** [comment]
Je ne sais pas du tous a quoi sert le menu Host et ni comment il marche si je devais l'utiliser je doute bien qui sert à quelque chose mais étant nouveau sont utilité est assez flou pour moi

Oui c'est vrai que Vstream et pas mal complet j'aime beaucoup pouvoir l'avoir ou juste naviguer dedans voir ce qu'il a

Il ont fais un très beau travail j'espère qu'il restera très longtemps en vie

**Comment by razorex** [comment]
Pour info l'adresse du plugin récemment mis à jour
.ttps://www.libertyvf.cz/
