### ISSUE TITLE
Robin des droits fonctionne plus

### ISSUE THREAD

**Issue by ddav33** [Kodi-vStream/venom-xbmc-addons#2563]
Bonjour c'est pour vous signaler que la source Robin des droits fonctionne plus quand on arrive sur la fenêtres supposé du replay on a no found comme message, sur navigateur Firefox le site on y a accès avec un capcha anti robots avec image a trouvé, voilà merci pour votre super add-ons

**Comment by Arias800** [comment]
Dans l'immédiate site n'est plus utilisable sur Vstream pour le moment mais je peux pas faire de test plus pousser vu que la dernière mise a jour Windows a mis mon pc ko du coup il faut que je change d'os donc le temps que je setup tout je peux pas faire de teste ^^

**Comment by TmpName** [comment]
Tu aurais un exemple, stp ?
Je viens de tester, j'ai que des liens sans le lien de strm (que du DL) ou alors un lien en gounlimited qui ne marche plus.

**Comment by Arias800** [comment]
Par exemple le liens gounlimited qui est la  : http://robind_sdroits.me/cfc-du-17-06-2019/

**Comment by TmpName** [comment]
Ha oui, des liens clicksfly, par contre a quoi on reconnais si ca peut marcher avec ton code ou pas ?

**Comment by Arias800** [comment]
Le seul moyens de savoir c'est de voir si il retourne le parametre c et si il y a un liens pour les image , pour le moment j'ai pas réussit a faire marcher avec clicksfly mais leurs implémentation de recaptcha est bizarre xD

**Comment by TmpName** [comment]
J'ai voulu retester a ce jours, pas pu naviguer sur le site, tres tres lent.

**Comment by johngf** [comment]
il fonctionne la

**Comment by TmpName** [comment]
je commence des modifs dessus, on avait pas un resolveur clictune ?

**Comment by Arias800** [comment]
Clictune c'est dans le code mais ou je sais pas . Par contre j'ai trouver une parade pour clicksfly ^^

**Comment by TmpName** [comment]
Lol, ben justement, j'etais sur d'avoir vu un truc, mais je le vois pas non plus ^^.
Demain je met en ligne ma version, en sautant clicsfly, mais je suis en train de me demander si ce n'est pas les memes codes, avec juste le nom du host qui change.

**Comment by Arias800** [comment]
Normalement c'est bon j'ai corriger le site . Si il y en a un qui ne marche pas merci de dire le nom pour que ce soit simple a trouver ^^

**Comment by TmpName** [comment]
Merde, je viens de mettre mon code en ligne.

**Comment by Arias800** [comment]
Ta fait quinze alors que moi ça marchait avec une seul sois j'ai de la change sois ton fichier etait pas a jour xD

**Comment by TmpName** [comment]
Nope , y avait besoin que de ta modif.
Mais le code est plus clair, now on voit ou se trouve la partie clictune par exemple.

**Comment by TmpName** [comment]
Et j'ai aussi desactivée la partie avec adfly car j'ai pas pu la tester et

`if 'AdF' in sHtmlContent:`

Je trouve ca trop leger, y a des chance d'avoir ca dans un code html.

**Comment by Arias800** [comment]
Bah écoute depuis qu'il y a eu cette modif ca marche relativement bien donc visiblement c'etait assez stable ^^

**Comment by TmpName** [comment]
Tu parles de adfly ?

**Comment by Arias800** [comment]
Oui depuis cette modif il n'y a pas eu a changer la méthode de détection donc c'est que ca devais bien fonctionner ^^

**Comment by TmpName** [comment]
Bon je remet, mais perso j'ai fais quelques tests rapides, pas vu de liens adf.

**Comment by Arias800** [comment]
Oui parce qu'il change souvent de site pour gérer leurs liens. Pour le moment ils ont remplacer adfly par  clicksfly ^^
