### ISSUE TITLE
Problème de compatibilité entre kodi 16.1 et VSTREAM

### ISSUE THREAD

**Issue by Bretuu** [Kodi-vStream/venom-xbmc-addons#2564]
**Décrivez le bug**
Les recherches des séries, films et documentaires (sur KODI 16.1) ne fonctionnent plus comme sur mon PC (tournant avec la dernière version de KODI)

**Votre system**
 - OS: [Android 4.3]
-  Appareil [sony xperia]
 - Version Kodi  [16.1]
- Version Vstream [7.3]

**Nous devons le reproduire**
Peut importe quelle est la recherche, quel est l'hébergeur et quel est le site, lors de la recherche, rien n'est trouvé. Multiples tests effectués (réseaux, fichiers corrompus, cache, partition etc ... nettoyés) réinstallation de kodi & de vstream mais rien de concluant.

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Contre-tests effectués sur un PC tournant sous windows et un raspberry pi avec la dernière version de KODI (Tests OK)

**Comment by TmpName** [comment]
La il faudrait les logs.

**Comment by Bretuu** [comment]
D'accord, avez-vous besoin des logs de mon pc (qui fonctionne) en plus de ceux du téléphone pour pouvoir comparer les deux ?
Je vous envoie ça ce soir.

**Comment by TmpName** [comment]
Nope, un seul suffit, ceux du pc sont plus facile a gerer, et perso suis pas fan des configs exotiques.
