### ISSUE TITLE
Bud seriestremhd, 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2565]
**Décrivez le bug**
Cest plus une infos qu un bug:

Depuis 2 ou 3 jours la source seriestreminghd tarde a s'ouvrir voir pas du tout et quand ça ouvre il y a pas l'affiche des séries.
Je sais que c'est pas un bug de vstream car le site web agit pareil sur reseau cellulaire ou fillaire : tard aussi et plus aucun affiche.

Je crains une fermeture mais j'espère que ce n'est qu'une maintenance, donc si quelqu'un en sais plus car cest de loin la meilleur source 

Merci 

**Votre system**
 - OS: [Android 6.0]
-  Appareil [k3 kingbox]
 - Version Kodi  [18 , 19]
- Version Vstream 0.7.3

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site seriestreminghd
- Le titre du fim/serie tous
- Le nom du host (peu importe)

**Comment by Arias800** [comment]
C'est un problème de Cloudflare corriger ici : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/cloudflare.py

**Comment by Che-debarras** [comment]
Merci testé mais aucun changement , il s'ouvre mais plus long que d'habitude et toujours aucune affiche des series (film pour son autre site de film)
J'ai pourtant effacé le cache vstream le cache kodi et meme clear thumbnails et refresh skin
De meme pour son site de film planetstreming.

**Comment by Arias800** [comment]
La je vois pas d'ou ca peut venir a mon avis c'est a cause du faite que les images sois derrière cloudflare qui fait que Kodi bloque . C'est logique puisque  seriestremhd utiliser les image de planetstreming ^^

**Comment by TmpName** [comment]
Chez moi ca deconne aussi sur navigateur, pas d'images.

**Comment by Che-debarras** [comment]
La source ne fonctionne plus sur  stream erreur 503

**Comment by Arias800** [comment]
C'est normal le site est down pour le moment ^^

**Comment by Che-debarras** [comment]
Le site n'est pas down mais on a toujours pas les affiches maj.
