### ISSUE TITLE
Iptv Simple Client

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2566]
J'ai trouver pour les personne intéresser comment envoyer un playlist trouver sur Vstream vers Iptv Simple Client . Ce n'est pas encore finit mais pour le moment c'est fonctionnel :
- Mettre a jour le fichier freebox de Vstream : https://github.com/Arias800/Fichier-divers/blob/master/freebox.py
- Allez dans Television/Musique et cliquer sur "Paramétrer Iptv Simple Client pour Vstream" (etape qui doit etre fait une seul fois il n'est pas utile de le faire plusieurs fois)
- A partir de maintenant toute les playlist qui vont etre visiter sur Vstream vont s'enregistrer localement (fichier qui va a chaque ouverture de playlist ce vide) et vont automatiquement etre lu par iptv simple client

Infos complémentaire :

- La 1er fois il faut allez dans les parametre d'iptv simple client et de les valider pour que les modification importer par Vstream fonctionne
- Pour que la nouvelle playlist sois ouverte par Iptv Simple Client il faut redémarrer Kodi

**Comment by Che-debarras** [comment]
Excellent 
Juste une question si tu a testé est ce que iptv simple client lit une chaine sans se stopper ?
C'est le gros souci des playlists quand je lance une chaine la lecture s'arrête au bout de quelque minute
(Possiblement di a la qualité HD des chaines qui plante la lecture)

Qu en dis tu?

**Comment by TmpName** [comment]
Quand je testais, c'etait un probleme de debit, je pouvais ameliorer ca en mettant plus de donnée en tampon, mais c'etait toujours le meme probleme. Tu peux afficher ca avec un raccourcis clavier (Touche O ou shift O de memoire), quand ca arrive a zero, ca deco ^^.
Tres peu de liens sont fiables.

**Comment by Arias800** [comment]
De toute facon il n'y a pas de magie si les liens ne sont pas stable ca marchera pas bien ^^

**Comment by Che-debarras** [comment]
Cette fonction a été retirée? Car avec la mise a jour manuelle on n'a plus accès au paramete iptv dans télévision/musique

**Comment by Arias800** [comment]
Elle n'a pas ete retirer puisque je ne l'ai jamais ajouter officiel pour la simple et bonne raison que je n'ai pas encore fait beaucoup de test ^^
