### ISSUE TITLE
Zone Téléchargement Out ?

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2567]
**Décrivez le bug**
Plus rien ne fonctionne sur ZT, est-ce que c'est normal ?
Merci

**Comment by sizanic** [comment]
Salut 
Tout est expliqué ici :
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2552

Merci de supprimer ce thread.

**Comment by ludopotte** [comment]
Pour résoudre le Problème de ZT sur Android, il faut changer le DNS car ça résout les problèmes des sites de Streaming qui font l'objet de contrôle par Hadopi en utilisant l'Application "DNS Changer" disponible au 
https://play.google.com/store/apps/details?id=com.burakgon.dnschanger&hl=fr

**Comment by ktm520** [comment]
Bonjour ,a tous , ZT a changer d'adresse ,
Voici la cause  , voir le lien : 
https://www.zone-telechargement.ec/?p=actu1

**Comment by TmpName** [comment]
Ils ont pas deja fait la meme info, mot pour mot ?

**Comment by lebigboss** [comment]
@TmpName  c'est pas le même site, c'est encore une copie d'une copie d'une copie.

**Comment by ktm520** [comment]
Quelle est la vrai adresse de ZT ?

**Comment by lebigboss** [comment]
@ktm520 C'est tous des copies

**Comment by Lioon2** [comment]
Pour moi le vrai c'est celui ci: d'ailleurs il a recupéré son domaine original https://www.zone-telechargement.net

**Comment by lebigboss** [comment]
Il y a plus de vrai depuis très longtemps et c'est pas parce qu'un site écrit officiel et attention aux arnaqueurs qu'il est le vrai

**Comment by sizanic** [comment]
Oui, il n'y a plus de vrai.
Certains clones ont dépassés l'original et sont devenus des références a part entière.

**Comment by lebigboss** [comment]
Ouai, dans vstream c'est annuaire téléchargement

**Comment by Makoto83** [comment]
Non ça marche faut que tu fasse la mise à jours du fichier directement.
=> [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_ws.py) et tu le remplace dans ton dossier => /plugin.video.vstream/resources/sites/

**Comment by Makoto83** [comment]
@BENJI97200 pas de quoi ;)

**Comment by Makoto83** [comment]
@BENJI97200 il suffit d'allez [ici](https://github.com/Kodi-vStream/venom-xbmc-addons) et de cliquer sur Branch et de choisi beta
![image2](https://i.imgur.com/7tQ00tr.png)
Et après tu navigues dans les dossier ;)

**Comment by Makoto83** [comment]
@BENJI97200 il y aussi un [Discord](https://discordapp.com/invite/S65HBXm) si tu as d'autre question ^^

**Comment by Makoto83** [comment]
@BENJI97200 Je n'utilise pas ce site Zt me suffit amplement ;) donc j'ai jamais tester si cela fonctionne.
