### ISSUE TITLE
Ocine

### ISSUE THREAD

**Issue by f3n3k** [Kodi-vStream/venom-xbmc-addons#2569]
Bonjour,

est il possible d'ajouter la source htt p://ww w.ocine.tv/ ?

Je trouve ce site de streaming, pratique, du HD, et leur façon de mettre les fichiers en streaming sur plusieurs serveur est pas mal pensé, hélas impossible à utiliser sur une android TV car pas de navigateur compatible sur Miibox, donc ca serait un plus de l'avoir sur Vstream.

Merci et cordialement

**Comment by Arias800** [comment]
J'avais commencer le fichier justement ^^

**Comment by Che-debarras** [comment]
Possible de mettre leur site manga avec? Jetanime.

**Comment by f3n3k** [comment]
haaa fantastique, je vous remercie Arias pour cette bonne nouvelle, peut on avoir une date approximative  pour la mise à jour et l'ajout de ce site ? Merci encore pour votre travail !

**Comment by Arias800** [comment]
Alors non je préfère ne pas de donner de date même approximative . Par contre tutoie moi s'il te plait parce que j'aime pas qu'on me vouvoie xD
Pour Jetanime oui pourquoi pas mais c'est pas dans mes priorités pour le moment ^^
