### ISSUE TITLE
Kodi alternative

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2572]
Bon je sais que c'est pas la premiere fois que ce genre de topic apparait, mais j'en peux vraiment plus de kodi. Alors j'ai commencé a regarder autour.
- stremio : apparement c'est mort, c'est un systeme client/serveur, rien en local.
- plex (serveur/client)/MediaPortal : pas vu de systeme d'extension pouvant reproduire Vstream.

Pour le moment j'ai rien trouvé de motivant, si quelqu'un a deja vu un plugin ressemblant a vstream sur l'une de ces applis ca m'interesse.

Trouve quelques exemples pour plex htt ps://www.imaginetricks.com/plex-plugins-channels/ mais vu que ca fonctionne en client/serveur je sais pas ce que ca donne.

**Comment by johngf** [comment]
bah il y a rien d'autre en free c'est quoi le soucis avec kodi ?

**Comment by TmpName** [comment]
Ben en fait je viens de voir que PLEX utilise des plugins en python, et la version gratuite a l'air suffisante, je vais tester ca ce soir.
Le soucis de kodi, c'est que c'est gavé de bugs depuis la derniere version, et qu'ils s en foutent completement.

Regardes sur les 3 dernieres année l'evolution de kodi, j'ai rien d'utile en plus (a part des mise a jour de composant mais ca ne vient pas de eux), les memes bugs que au depart (des freezes, des crashs) et a chaque versions des bugs en plus et jamais rien d'utile.

**Comment by Che-debarras** [comment]
Il y a MrMC alternative de kodi qui a fusionné avec SPMC, le dev de spmx a joint cette equipe de MrMC mais le seul souci c'est qui accepte pas de plugin ou addon enfin c'est le développeur qui décide et pour l'instant il y a que le plugin PLeX
D'après ce que j'ai lu et si jai compris l'anglais ce addon plex utilise le player de MrMC et non en serveur (mais a vérifier)

Peut etre en discutant avec les développeurs ils peuvent accepter l'ajout de vstream si cela résout tes soucis

**Comment by TmpName** [comment]
Mais c'est que sur android ca ?

Donc j'ai teste plex, plugin facile a faire et en python, ca marche bien, mais tres lourd aussi, et ils se foutent des retours de la communautée (comme kodi) et ils sont meme supprimé le support des plugins, donc a mon avis ca va partir dans un autre style, l'iptv payante d'apres ce que je vois.

Mediaportal, tres bien, mais pour faire un plugin, ...

**Comment by Che-debarras** [comment]
Oui apparemment c'est que sur android. Apple tv, iOS et amazon store mais ils font un sondage pour le porter ailleurs ( https://mrmc.tv/forum/viewtopic.php?f=5&t=350 ) et d'après ce que j'ai lu les devs de cette appli pensent la meme chose que toi sur kodi et c'est la raison pour laquelle ils ont créé MrMC.

Mais bon il n'ont pas l'air de vouloir travailler sur une version pc.

Sinon il y a le player Perfect Player (android et pc) qui accepte des plugins ou Movian (android,Linux, rasperry,macos,google chrome, ps3, : il y a des plugins https://movian.tv/plugins/movian donc certains viennent de kodi) .)

**Comment by Arias800** [comment]
Au pire tu peux faire ton propre fork de Kodi 17 ou 18 si tu cherches a partir sur un truc bugger xD

**Comment by Che-debarras** [comment]
Pourquoi pas un bundle pour vavoo? Les vavoo sont des fork de kodi

**Comment by TmpName** [comment]
@Arias800 , si je te dis que ca me motive pas trop, tu comprend pourquoi ? ^^

Perfect Player ce serait que pour l'iptv
Les plugin sont pour une autre appli mais qui ne tourne pas sous windows.

Par contre vavoo, ca a l'air pas mal, je teste ca ce soir. Mais si le fork est trop proche, je vais avoir les memes merdes ^^.

**Comment by Arias800** [comment]
Je comprends totalement xD

**Comment by TmpName** [comment]
Bon ben en fait vavoo c'est kodi.
J'ai juste survolé, mais il y a rien de different, au pire j'installe une vielle version de kodi et c'est bon.

Suis degouté, comment ca se fait qu'ils n'aient aucun concurrent ...

**Comment by Arias800** [comment]
Bon bah vu que @LordVenom viens de mettre en public le github j'en parle ici donc LordVenom et moi-même on commencer à bosser sur un logiciel baser sur Kivy et sur python 3 donc @TmpName si tu veux venir aider tu est le bienvenue \o/ (je précise pour les non développeurs essayer le logiciel n'est pas utile car pour le moment il ne sert pas a grand chose étant donner qu'il reste beaucoup de travail et qu'il ne verra peut être même pas le jour au final ) https://github.com/LordVenom/exode

**Comment by TmpName** [comment]
Bande de petit cachotier, je viens voir ce que c'est, je connais pas du tout.

**Comment by noway80** [comment]
Bonjour
J ai develloppe media player sous android tv et un syno
J utilise mxplayer ou archos pour lire les videos , utilisez vous le player kivy sous android avec des liens http ?

**Comment by TmpName** [comment]
Alors oui, ils utilisent kivy, mais lordvenom se tate pour une autre lib, car niveau performance le lecteur de kivy c'est juste une horreur.
