### ISSUE TITLE
Plusieurs source hs

### ISSUE THREAD

**Issue by fredo04** [Kodi-vStream/venom-xbmc-addons#2573]
**Décrivez le bug**
Depuis quelques semaines lorsque je fais film/dernier ajout j'ai pas mal de site hs.
Cinemay - erno 7
Dadyfix - fichier introuvable
Exyreme-download - fichier introuvable
Filmstreamvk - erno 7
K-streaming - erno 7
Kaydo - fichier introuvable
Streamindivx- erno 7
Streamiz - erno7
De plus lors de recherche j'obtiens bien des resultas mais souvent quand je lance le film -erreur fichier introuvable.
**Votre system**
 - OS:  Android 9 (honor 8x) + box android 7
-  Appareil : honor 8x + box android
 - Version Kodi : 18 (honor 8x), spmc 16 box
- Version Vstream : la derniere

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
https://slexy.org/view/s2z4O6MNVZ

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Che-debarras** [comment]
Il faut changer le DNS et t'aura accès à ces sites sauf a ceux la: #2570
 Sinon met ajour manuellement avec le dernier version de github

**Comment by fredo04** [comment]
Je viens de changer le dns par celui de cloudflare, ça marche nickel merci pour la solution.
Par contre j'ai jamais mis a jours manuellement, comment on fait ?

**Comment by Che-debarras** [comment]
Pas de souci si tu n'as pas mis a jour manuellement mais avec la mise a jour manuelle tu devrais avoir besoin du changement de DNS pour très peu de site.
Sur mon poste #2570 il y a 3 ou 4 site qui bug dû a des modif du site web
Juste faut patienter qu un dev ai le temps de corriger (dadyflix, voirfilm et streamdivx)
Mais vu le nombre de site tu trouveras ton  bonheur dans d'autres sources

**Comment by fredo04** [comment]
Comment fait on la mise a jour manuelle stp ?

**Comment by Che-debarras** [comment]
Quand tu est sur le github de vstream , en bas il est écrit télécharger Beta et tu clique et il télécharge directement.
Et ensuite tu ouvre le ficher avec winrar et tu fais copier coller du dossier plugin.video.vstream vers le dossier addon de kodi (android/data/org.xbmx.kodi/files/.kodi/addons)

La dernier mise a jour a résolu le problème de dadyflix.

**Comment by fredo04** [comment]
Super merci ça va bien m'aider car chez moi les mises à jour n'apparaissent que tous les deux ou trois mois

**Comment by TmpName** [comment]
Je cloture cette issue, suite la bas : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2570
