### ISSUE TITLE
Impossible d'installer F4Mtester

### ISSUE THREAD

**Issue by Turk182es** [Kodi-vStream/venom-xbmc-addons#2579]
Salut,

Je viens de réinstaller Vstream mais impossible de trouver un repository valable pour installer F4Mtester afin de voir la TV française.
Avez-vous un Repository valable ?

**Comment by Arias800** [comment]
Trouvable ici : http://www.vstream.ml/repo/

**Comment by Turk182es** [comment]
Super merci ce soir je teste !
