### ISSUE TITLE
Zt lol

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#2584]
Salut à tous
oourriez vous rajouter sur zt lol les films classés par année comme sur le site
Merci d'avance

**Comment by TmpName** [comment]
Hello,
La ,c'est pas tres dur, tu as regardé le fichier pour voir comment c'etait foutu ?

**Comment by sebi0606** [comment]
Malheureusement je suis une bille en python :(
Si a l'occase quelqu'un de sympa se sent de le faire
Merci d'avance

**Comment by BENJI97200** [comment]
Bjr ,ce site ne fonctionne pas pour moi:erreur 403....pour vous ca fonctionne? Si oui une solution svp ? Merci

**Comment by sizanic** [comment]
@BENJI97200 
Pas d'erreur sur ce site pour moi.
Sur Vstream, c'est Tirexo. Pas d'erreur non plus.

**Comment by BENJI97200** [comment]
@sizanic...merci mais pour moi erreur

**Comment by BENJI97200** [comment]
@sizanic...aucune information...

**Comment by sizanic** [comment]
@sebi0606 
Voici le développement pour les films classés par années : https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2590

Si tout se passe bien, tu le retrouvera bientôt dans Vstream.

**Comment by sebi0606** [comment]
Top merci a toi @sizanic :)

**Comment by sizanic** [comment]
@BENJI97200 
Je viens de tester ce chemin : 
- Tirexo
- Films
- Films populaires
- antman et la guepe
- ultra-hdlight 265
- uptobox
- sélection de la qualité
-> lecture du film 👍 

Deuxieme test avec 
- MI fallout
- hdlight 1080

=> OK

Par contre il est vrai qu'il m'arrive d'avoir "aucune information".
Dans ce cas, je reviens en arriere une fois et je revalide le lien.
La deuxième fois ça passe.

**Comment by BENJI97200** [comment]
@sizanic...en suivant ton chemin ,tjrs aucune information ,mm en revenant en arrière plusieurs fois

**Comment by BENJI97200** [comment]
@sizanic....j ai erreur 403...https://ww.22 zone-telechargement....

**Comment by BENJI97200** [comment]
@sizanic...wawacity fonctionne pour toi?

**Comment by johngf** [comment]
je valide #2590mais il est possible faire beaucoup plus courts et simples regarde dans les autres sites qui affichent les années @sizanic

**Comment by TmpName** [comment]
@BENJI97200 essayes sur un navigateur web, pour voir si c'est pas une histoire d'ip.

**Comment by BENJI97200** [comment]
@TmpName....ça passe sur le navigateur Google mais pas sur Kodi...merci quand mm,j ai tout essayé, mm désinstallé kodi ,rien a faire

**Comment by BENJI97200** [comment]
@TmpName...sur le site en passant par Google je clique sur uptobox , et la page est bloquée sur :vérification de votre navigateur avant d accéder à dl-protect1.co.

**Comment by TmpName** [comment]
Ha la protection cloudflare ?

**Comment by BENJI97200** [comment]
@TmpName....1 solution stp?

**Comment by TmpName** [comment]
Ben j'ai re-regarde le code, normallement la protection cloudfalre est gerée, il faudrait que tu actives les logs de Vstream (pas ceux de kodi) et que tu fasses passer un log.

**Comment by BENJI97200** [comment]
@TmpName....hummm ,comment fait on cela ?

**Comment by BENJI97200** [comment]
@TmpName....https://sexy.org/view/s20svTkK3a

**Comment by jesusisback66** [comment]
dites c'est moi ou zt et encore HS ?

**Comment by johngf** [comment]
@BENJI97200 il faut activer les notices de log dans les paramètres de vstream , testé le site ou le bug se trouve et ensuite cliquer sur upload

**Comment by BENJI97200** [comment]
@johngf....J ai desinstalle kodi et reinstalle avant d upload la notice,dis moi si c est mieux....https://slexy.org/view/s2uzpad26n       merci

**Comment by johngf** [comment]
en faite pour zt.lol tu as un 403 c'est normal ils ont changé d'url encore ht_tps://wwv et non plus
ht_tps://ww22.

**Comment by BENJI97200** [comment]
@ johngf ...merci dc il faut que je change l url manuellement ?

**Comment by TmpName** [comment]
Lol, mais c'est quoi cette install ? Tu te sert vraiment de tout ces repositary ? ^^
Sinon pas de changement, mais hier je regardais l'autre ZT, mais le code est semblable.

Apres tu peux changer l'url a la main, mais chez moi meme la mauvaise fonctionne, et sans verification de navigateur.

Mais normalement la page gere cloudflare, tu as quoi comme page de protection sur navigateur, un message au centre, et ca apparait 5s apres ?

**Comment by BENJI97200** [comment]
J ai tout reinstallé...Et ca ne passe tjrs pas(sniffff)....https://slexy.org/view/s2yzl44leh      j ai mm perdu extreme down............

**Comment by BENJI97200** [comment]
Car impossible de réinstaller chrome launcher

**Comment by BENJI97200** [comment]
@TmpName ...@johngf....tout remis à neuf ,tirs pas zt lol, j ai réussi a installer game launcher et kore pour extreme download,mais le soucis ce qu en cliquant sur le lien du film ,ça me redirige vers la page web d extrem down...je copie le lien que je met ds kore et quand je retourne sur extrem down ....j ai le message aucune information...Alors qu avant je regardais des films sur extrem down ...sans passer par kore (ça me proposait le lien uptobox et c tout)

**Comment by BENJI97200** [comment]
Bjr....pas de solution ?

**Comment by TmpName** [comment]
Ben les seules infos qu'il ya dans les logs c'est

> 2019-08-01 13:19:30.221 T:8408  NOTICE: 	[PLUGIN] Vstream: load site tirexo and call function showMovies
> 2019-08-01 13:19:30.524 T:8408  NOTICE: 	[PLUGIN] Vstream: Connexion Impossible (403),htt....one-telechargement.lol/exclus/

Alors que le lien fonctionne, dans la mesure ou ca marche chez les autres et pas chez toi, je pense que ca doit venir de ta machine, tu es sur que ca fonctionne si tu vas sur la meme page et un navigateur web et la meme machine ?
On peut essayer de rajouter des headers en aveugle, mais vu que ca deconne que chez toi ....

**Comment by BENJI97200** [comment]
@TmpName....ça fonctionne sur le navigateur de la mm machine (nvidia shield tv)....mais pas sur vstream. Je n ai plus aucun site proposant uptobox ,avant j avais extreme download qui fonctionnait mais plus mnt,Zone téléchargement c mort ,wawacity c mort ainsi que free téléchargement...Sniffff

**Comment by Cikai91** [comment]
Bonjour, pareil chez moi. 
Plus aucun lien sur ZT juste les liens en rouge. 

J'ai installé différentes version 17.6 , 18,  19beta idem 

Je pensais à problème de DNS, j'utilise les DNS de Google.

**Comment by sebi0606** [comment]
Les gars ça fonctionne parfaitement bien chez moi regardais effectivement du côté de vos dns

**Comment by BENJI97200** [comment]
On fait comment pour vérifier les dns? Car aucun sites cités plus haut ne fonctionnent....

**Comment by sebi0606** [comment]
@benji97200 A tout hasard tu es chez free?

**Comment by BENJI97200** [comment]
@sebi0606....chez Sfr

**Comment by BENJI97200** [comment]
@sebi0606....j ai désinstallé kodi au moins une dizaine de fois....j ai la fibre 100mega ...et j ai mm essayé en 4g ...rien a faire.....je prend le lien sur mon portable et je l envoie sur mon compte uptobox...c ma seule alternative pour l instant

**Comment by sebi0606** [comment]
Tu as un VPN ?

**Comment by Cikai91** [comment]
J'ai testé avec un vpn idem 
J'ai changé les dns idem 

Je sèche la ... 
j'ai installé kodi sur mon phone et tester idem .. 
 :/

**Comment by BENJI97200** [comment]
Oui j ai un vpn...et pareil rien ne passe

**Comment by sebi0606** [comment]
@benji97200 @cikai91 il ne vous reste plus que Netflix les gars désolé attendais peut être une prochaine mise à jour

**Comment by BENJI97200** [comment]
Tirexo passe avec purevpn....mais pas zone téléchargement, ni extreme download....merci en tout cas pour cas

**Comment by sebi0606** [comment]
C'est bien un souci de dns les VPN change les dns

**Comment by BENJI97200** [comment]
@sebi0606....comment faire stp?...merci

**Comment by sebi0606** [comment]
Prend un abo chez nordvpn il Marche très bien

**Comment by BENJI97200** [comment]
@j ai purevpn...mais réduit considérablement la bande passante

**Comment by sebi0606** [comment]
@benji97200 nordvpn très très bien et pas cher en ce moment

**Comment by BENJI97200** [comment]
@sebi0606....merci bcp

**Comment by TmpName** [comment]
Pour changer les dns, il ya un lien sur la page d'accueil.

**Comment by BENJI97200** [comment]
@TmpName...bjr,quelle page d acceuil?

**Comment by jesusisback66** [comment]
Tu es sur box android ou pc ? Sur pc c’est dans les paramètres de ta carte
réseau clic droit option ipv4 et tu rentre les paramètres de dns , si tu ne
trouve pas sur Windows tu a un logiciel qui s’ap dns changer

Sur android tu va pareil sur tes paramètres réseaux et paramètres ip tu
choisis statique,tu rentre la passerelle qui correspond à l ip de ton
interface d’admi Box ,longueur préfixe réseau tu laisse 24,et après tu
rentre le dns1 de open dns ,puis le second et tu valide

**Comment by BENJI97200** [comment]
@jesusisback66....merci mais comment puis je savoir les chiffres à rentrer ds dns 1 ou 2?

**Comment by sebi0606** [comment]
https://www.justgeek.fr/liste-des-serveurs-dns-les-plus-rapides-et-securises-44705/
Tu devrais trouver ton bonheur

**Comment by BENJI97200** [comment]
@sebi0606.....sur android en mettant le dns cloudflare,plus de connexion...merci bcp ,j abandonne

**Comment by sebi0606** [comment]
Essaie tout simplement ceux de Google

**Comment by BENJI97200** [comment]
@sebi0606...avec ceux de Google tjrs aucune information, j utiliserai purevpn mm si ça ralentit énormément....merci pour tout tes conseils

**Comment by sebi0606** [comment]
@benji97200 de rien vraiment j'aurais préféré que tu trouves une solution pour ton problème 
À tout hasard tu as pas de par feu activé sur ta box ou ton routeur ?

**Comment by BENJI97200** [comment]
@sebi0606....non pas de par feu activé...

**Comment by BENJI97200** [comment]
@sebi0606....et mm sur mon tel en 4g pareil aucune information ....avec purevpn ca fonctionne mais ralenti la bande passante

**Comment by sebi0606** [comment]
4g sfr aussi?

**Comment by BENJI97200** [comment]
Oui aussi

**Comment by sebi0606** [comment]
Je me souviens a une époque Netflix ne Marcher plus avec sfr ils avaient changer leur dns ton souci vient réellement des dns avec de la patience essaie ceux que tu as sur la liste du site que je t'ai passé tu vas en trouver un de bon

**Comment by BENJI97200** [comment]
@sebi0606...merci je testerais et je te tiens au courant....encore merci

**Comment by sebi0606** [comment]
You're welcome :)

**Comment by BENJI97200** [comment]
@sebi0606...merci

**Comment by Cikai91** [comment]
Bonsoir Benji97200, 

Il y a une solution qui a été posté .. 

Test ce bêta :  https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

Et dis-moi si ça marche chez moi, chez moi c'est ok !

**Comment by BENJI97200** [comment]
@Cikai91....zone téléchargement passe mnt très bien....mais zt lol (tirexo) ...aucune information....merci j ai au moins z téléchargement...

**Comment by Cikai91** [comment]
C'est grace au fichier ?

**Comment by BENJI97200** [comment]
@Cikai91....oui oui car avant z de téléchargement ne passait pas

**Comment by BENJI97200** [comment]
Tirexo passe chez toi? Sans vpn?

**Comment by Cikai91** [comment]
Non lien vide mais j'utilise surtout ZT

**Comment by BENJI97200** [comment]
@Cikai91....quand purevpn est activé ,je vois tous les liens uptobox que ce soit z téléchargement ou tirexo,mais ça tourne en boucle et ne démarre pas le film...dc j ai désactivé pour profiter pleinement de z de téléchargement qui passe très bien...encore merci

**Comment by BENJI97200** [comment]
@Cikai91....encore une question....chez toi wawacity et extreme download fonctionnent ???

**Comment by Cikai91** [comment]
J'ai pas essayé je teste tout à l'heure et je te dis ça

**Comment by sebi0606** [comment]
Bonsoir à tous 
Zt lol changement d'adresse ne marche plus
Merci d'avance
