### ISSUE TITLE
Source ZT errno 111

### ISSUE THREAD

**Issue by Cikai91** [Kodi-vStream/venom-xbmc-addons#2585]
**Décrivez le bug**
Errno 111 sur la source ZT depuis ce matin

**Votre system**
 - OS: [ Android]
-  Appareil [box android ]
 - Version Kodi  [17]
- Freebox mini 4K

**Comment by sebi0606** [comment]
Salut
Marche parfaitement chez bien 
Sur Nvidia shield kodi 18 et fire stick tv kodi 18

**Comment by Cikai91** [comment]
Ce matin j’ai changé d’opérateur de orange chez Free. 
Il y a peut être un adblock ou firewall

**Comment by sebi0606** [comment]
Change tes dns free bloque certain site et moi effectivement je suis chez orange

**Comment by Cikai91** [comment]
Je vais tester ça, on est bien d’accord que les dns je les change sur ma box’ android ?

**Comment by sebi0606** [comment]
Il faut que tu utilises un VPN sur ta box ou que tu changes les dns sur la console de gestion de ta freebox

**Comment by Cikai91** [comment]
Ok ça marche avec un vpn 
Je vais essayer de régler sur là box le dns

**Comment by Cikai91** [comment]
Super merci Sebi j’ai réglé le DNS et ça fonctionne.

**Comment by sebi0606** [comment]
Avec plaisir :)
