### ISSUE TITLE
Kepliz bug

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2586]
**Décrivez le bug**
Impossible d'ouvrir le dossier d'un film pour atteindre le fichier hoster

**Votre system**
 - OS: [,Android 6 et 8]
-  Appareil [kingbox k3, Android TV]
 - Version Kodi  [18, 19]
- Version Vstream : 0.7.3.2

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
testé le 27/07 aucun bug

**Comment by TmpName** [comment]
Ce site est instable, en general suffit d'attendre 24h.
