### ISSUE TITLE
9Docus- Source ne se rafraichit plus

### ISSUE THREAD

**Issue by mannou78** [Kodi-vStream/venom-xbmc-addons#2591]
Bonjour,

Depuis plus de 3 semaines 9Docus ne semble plus se rafraichir avec du nouveau contenu.

Tout le contenu est plus a jour depuis 3 semaines ou un peu plus.

Merci

**Comment by johngf** [comment]
oui sur le site internet [ici](https://9docu.net/) c'est pareil soit en vacance soit abandonné
