### ISSUE TITLE
Replay TV Streaming Off-Line

### ISSUE THREAD

**Issue by mannou78** [Kodi-vStream/venom-xbmc-addons#2592]
Bonjour,

La source Replay TV Streaming semble ne plus fonctionner.

La liste des emissions s affichent mais quand on clique dessus rien ne se passe. Donc on peut uniquement voir le nom de l emission mais pas de stream dispo

A+

**Comment by johngf** [comment]
fonctionne le 29/07 
edit : quand il y a un soucis, il faut vérifier si sur le site internet c'est pareil.
