### ISSUE TITLE
Bugs sources (maj)

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2593]
**Décrivez le bug**

Flmilmt fixed

strmz : fixed

Frtlchgmnt: fixed

Dossier Onlystream et flix555 ont aucun lien

**Votre system**
 - OS: [Android 6 et 8]
-  Appareil [kingbox tv et s8+]
 - Version Kodi  [18 et 19]
- Version Vstream 0.7.33 ccadcf30

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site cité ci-dessus 
- Le titre du fim/serie cité ci-dessus 
- Le nom du host cité ci-dessus

**Comment by johngf** [comment]
tu teste avec la beta ? ou non

**Comment by Che-debarras** [comment]
Oui je teste toujours avec la beta maj et avec ou sans dns
Pourquoi être agressif? "m'en fout"...
Je clos cete issue puisqu'elle dérange.

Bonne journée

**Comment by johngf** [comment]
ce n'est pas de l'agressivité juste les sites de téléchargement je ne m'en n'occupe pas.

**Comment by Arias800** [comment]
Frtlchgmnt corriger : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/30a5b45ccf24b36318885e5d2ce0f5f9131315b6

**Comment by johngf** [comment]
strmz > fix

**Comment by KodiTopQuebec** [comment]
et pour film illimité , pourriez-vous regarder pourquoi il indique aucune information a dernier ajout , par contre si l'on va a par année /2019 la liste est la  et fonctionnelle , merci

**Comment by whynotnow2** [comment]
Y a également un probleme avec ZT. Plus aucun lien visible . Merci

**Comment by KodiTopQuebec** [comment]
@whynotnow2 , le problème est réglé , mais la version béta et tout va revenir ou tu devras attendre a la prochaine mise a jour de vstream

**Comment by whynotnow2** [comment]
@KodiTopQuebec ou est ce que je peux trouver la bêta svp ?
Merci

**Comment by razorex** [comment]
@johngf  flix555 j'ai vu ce hoster sur zonestreaming ainsi que streamty.

**Comment by jesusisback66** [comment]
c'est vrais zt " acces au menu de recherche " mais dossier vide " testé avec open dns et sans , puis vpn mais rien y fais , streaming hd la casi totalité des liesn sont " dead ou innaccessible " zt " lol " completement disparu , 70% des source sont HS

**Comment by TmpName** [comment]
@KodiTopQuebec , je viens de tester voirfilm, pas vu de prbs a "dernier ajouts"

ZT lol et mort ? ca c'est cool, y a justement des prb avec ^^, ca va faire du taff en moins.

Demain je regarde pour  flix555

**Comment by KodiTopQuebec** [comment]
@TmpName j'ai écrit sur film illimité et non voir film , le problème est toujours la

**Comment by KodiTopQuebec** [comment]
@jesusisback66 , met la version beta et ZT va fonctionner de nouveau comme j'ai écrit plus haut

**Comment by KodiTopQuebec** [comment]
@jesusisback66 je viens de tester ZT lol(tirexo), et mes fils démarrent ici tous

**Comment by jesusisback66** [comment]
> 
> 
> @jesusisback66 je viens de tester ZT lol(tirexo), et mes fils démarrent ici tous

et je la trouve ou la beta car j'ai toujour etais en stable ?

**Comment by jesusisback66** [comment]
> 
> 
> @jesusisback66 , met la version beta et ZT va fonctionner de nouveau comme j'ai écrit plus haut

**Comment by jesusisback66** [comment]
@KodiTopQuebec et je le trouve ou le zip beta ? car j'ai toujour etais en stable

**Comment by KodiTopQuebec** [comment]
@jesusisback66 , clique en haut sur code ici même sur cette page , ensuite descend plus bas tu verras télécharger la beta , fait le , ton fichier sera dans tes téléchargements , par la suite ouvre kodi et va a install from zip file et va chercher ton.zip vstream qui est dans tes téléchargement , voila tu verras vstream mis a jour

**Comment by TmpName** [comment]
Mince, dsl
@KodiTopQuebec , je viens de faire une modif, ca devrait aller.

**Comment by jesusisback66** [comment]
@KodiTopQuebec  un grand merci sa fonctionne !

**Comment by KodiTopQuebec** [comment]
@TmpName merci beaucoup mon film illimité fonctionne de nouveau ,tu es un champion

**Comment by stef2d** [comment]
Bonjour savais pourquoi livetv bêta événement en live et robin des droits rediff fonctionne plus ? cdlt

**Comment by razorex** [comment]
@stef2d  robindesdroits vient d’être mis à jour soit tu installe la bêta soit tu prend patience et tu attend la prochaine mise à jour.

**Comment by stef2d** [comment]
razorex Ok j ai installer la bêta ça fonctionne merci pour le boulot

**Comment by TmpName** [comment]
Donc si j'ai bien suivi reste plus que le hoster "Onlystream ", pour ceux qui l'ont testé, il vaut le coup, c'est pas un hoster jamais utilsé qui risqque de disparaitre dans 15 jours ?

**Comment by johngf** [comment]
only stream vu sur i anime

**Comment by lefou66** [comment]
Salut tout le monde, j'aimerais savoir si c'est moi ou non...tirexo marche plus..sur ZT il y a plusieurs films qui ne fonctionne plus...exemple: les Schtroumpfs 2 ..aucun lien ne fonctionne le 4 k aussi
Nvidia shield
Kodi 18.2

**Comment by TmpName** [comment]
Ca vient de la protection cloudflare qui doit etre mal mise en place, essayes le meme lien 2 fois de suite et ca va marcher, la premiere fois Vstream recupere le cookie, la deuxieme fois il l'utilise. Testé sur les Schtroumpfs 2.

**Comment by TmpName** [comment]
Nouvelle version > https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2601
