### ISSUE TITLE
Zt lol hs 

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#2595]
Salut à tous zt lol hs changement d'adresse
Merci d'avance

**Comment by isandard** [comment]
Si je me rappelle bien y avait un système à l'époque de zone-telechargement ( qui est devenu annuaire qui est redevenu zone ........ on va plus chercher à force :) ) qui permettait que tout marche même sans changer l'adresse du site.
Si on pouvait l'implémenter dans le tirexo ça serait super car il est en passe de changer 3 fois par jour et on va jamais suivre la cadence.

**Comment by spcxsat** [comment]
J’ai essayé de faire une modification en changent url qui fonctionne sur mon navigateur 
https://www.zone-telechargement.vip/
Mais ça fonctionne pas avec vstream, je comprend pas....

**Comment by johngf** [comment]
ils ont du changé autres choses que l'url

**Comment by sizanic** [comment]
corrigé

**Comment by sebi0606** [comment]
Merci @sizanic

**Comment by whynotnow2** [comment]
Y aurait pas un problème avec ZT.? Lorsque je click sur un lien premium ça marche pas.

**Comment by ethanael83** [comment]
Oui le problème c'est zt-protect et plus dl-protect du coup plus de liens

**Comment by Arias800** [comment]
Deja corriger dans la beta depuis 2 jours ^^

**Comment by ethanael83** [comment]
Super! Merci
