### ISSUE TITLE
Live TV liens absent, liste incomplete

### ISSUE THREAD

**Issue by faribole** [Kodi-vStream/venom-xbmc-addons#2599]
**Décrivez le bug**
Sur un poste en Windows 7 avec kodi 18, vstream 0.7.3 j'accède au match Marseille - Reims depuis LiveTV mais sur les 29 propositions de liens aucun ne s'affiche.

Sur un poste en Windows 10 avec Kodi 17.6, vstream 0.7.3 je ne vois pas le match Marseille Reims dans la liste de Live TV

**Comment by TmpName** [comment]
Le match de pétanque ?

Bon je deconne, mais c'est l'enfer ce site, j'ai fais une petite modif, mais si on ne va pas sur le meme match a la meme minute, on trouvera jamais les memes liens, la j'en ai meme trouvé ou c'est des liens twitter ou il faut se rendre pour avoir les vrais liens ...
