### ISSUE TITLE
film illimité (netu)

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2606]
**Décrivez le bug**
sur film illimité il n y a presque plus rien qui fonctionne , pourriez-vous regarder netu pourquoi maintenant il est HS , et si l on va directement sur le site j ai vu comme lien de streaming 2 nouveaux Streamax ,vembed , peut être que vous seriez en mesure d ajouter ces liens , merci de votre soutien précieux

**Votre system**
 - OS: [Windows, Android] les deux
-  Appareil [nvidia shield, Ultra] sur tout les types d appareils
 - Version Kodi  [16.17.18]18.4
- Version Vstream la beta du 7 sept 

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
clic open mis a jour
netu je pense c'est mort recaptcha v2
strea_max compliqué mais faisable va faloir dl fichier par fichier

**Comment by TmpName** [comment]
Pour netu, j'avais pas vu, le code de @Arias800 ne marche plus ?
Sinon j'ai reagrdé aussi pour strea_max, c'est vraiment le bodel, d'apres ce que j'ai compris ils ont une requete speciale de leur coté, qui donne sur un fichier texte hebergé par google, et cette requete ne donne qu'une partie du fichier.

Autrement dit suffit que google s'en apercoive et supprime un seul des fichiers et c'est mort, et a mon avis ils vont vite se faire reperer. Pas sur que ca vaille le coup de se pencher dessus ?

**Comment by johngf** [comment]
j'ai cherché pour voir si on avait une url avec tous les liens mais non
 - sinon 4 ou 5 qualité dispo
 - il faut fabriquer une liste avec les urls , dl le contenu de chaque url  >> une autre url
 - faire une autre liste avec les urls  et dl chaque fichier et faire un m3u8 local pour play

**Comment by johngf** [comment]
finalement j'ai trouvé l'astuce

**Comment by TmpName** [comment]
Lol, joli, ca a l'air beacoup plus facile en voyant ton code ^^

**Comment by DaX59** [comment]
J'ai toujours le problème avec Netu. ll y a quelques semaines, ça me demandait un captcha avec des photos à valider mais maintenant, ça me dit lien mort. Ca vient du plugin ou bien des DNS ?

**Comment by TmpName** [comment]
J'ai pas eu l'occasion de retester, mais il me semble qu'ils ont rechange leur code, plus compatible avec l'astuce de @Arias800

**Comment by johngf** [comment]
oui ne tu c'est mort pour le moment
