### ISSUE TITLE
extreme_down

### ISSUE THREAD

**Issue by vstreamkodi** [Kodi-vStream/venom-xbmc-addons#2607]
Décrivez le bug
Impossible d'accéder aux sous-catégories une fois dans la catégorie Films, Séries, Animés ou Autres. Cela fonctionne sur PC avec Kodi 17.6 mais pas sur mes smartphones. Elles fonctionnent bien sur Kodi 18.3 sous android. La recherche sur ce site ne fonctionne pas quelque soit la version. Je voudrai repasser en 17.6 sur la Shield et la mi box car Kodi Leia bug bcp trop souvent, plantage...

Votre system
OS: [Android 6.1.0 et 7.0.0]
Appareil [S7, P9 lite] 
Version Kodi [17.6]
Version Vstream 0.7.4
Nous devons le reproduire
Pour cela il nous faut:

Le nom du site Extreme-Download (beta)

**Comment by fredterros** [comment]
Remplacez https://www.extreme-d0wn.net par https://www.extreme-d0wn.xyz dans la source, ;)

**Comment by razorex** [comment]
la source à été modifié.

**Comment by vstreamkodi** [comment]
Petite correction copie/coller pour la fonction recherche
https://pastebin.com/fVmKV2JG
