### ISSUE TITLE
Problème IPTV4SAT

### ISSUE THREAD

**Issue by fredterros** [Kodi-vStream/venom-xbmc-addons#2608]
**Décrivez le bug**
J'ai remarqué que dans tv/direct le site iptv4sat ne marchais plus, voici une correction qui marche pour moi, éspérant pouvoir aider ;)

PS: c'est la première fois que je poste sur git hub

cela concerne le fichier iptv_four_sat.py dans ressources/sites
la source corigée ci-dessous:   
https://pastebin.com/gnQ1kGcC

**Votre system**
 - OS: [Windows, Android]
-  Appareil [MxQ 4K, N10, Toshiba]
 - Version Kodi  [18.3]
- Version Vstream 0.7.4

**Comment by KodiTopQuebec** [comment]
merci beaucoup ca fonctionne maintenant

**Comment by TmpName** [comment]
Merci, j'ai mis ta modif sur la beta.

**Comment by fredterros** [comment]
Merci, petite question, comment fait on lorsque l'on veut créer une source et qu'un lien doit être cliqué pour pouvoir avoir le hoster?

PS: je débute en phyton, y a t'il une doc pour les fonctions addmovie addtext...etc ?

**Comment by TmpName** [comment]
Nope, pas de doc, en general les noms de fonctions sont assez explicites.
Tu cherches quoi comme lien ?

addmovie  > pour les films (Media)
addTV >  pour les series (Media)
addMisc > quand tu es pas sur (Media)
addDir > Lien neutre cliquable (Pas de media)
addLink > Lien neutre cliquable (Media)
addText > lien neutre non cliquable (pas de media)

**Comment by fredterros** [comment]
Voilà ma source, ;)

https://pastebin.com/g7tHcF8B

**Comment by TmpName** [comment]
Ha mince, c'etait kepliz ^^, je suis tombé sur l'autre post en premier.
Désolé pour le temps que tu y auras passé, dis toi que tu n'es pas le premier, ni le dernier a faire la meme source, au moins now, tu comprends le systeme du fichier site :)

**Comment by fredterros** [comment]
https://pastebin.com/XhaV4Saz
