### ISSUE TITLE
Besoin d'aide pour resoudre: harleyquinnwidget

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2609]
Bonjour,

Dans le sport liveTv, Il y a des liens suivantes que j'ai essaye de resoudre mais sans succes:
h ttp://live.harleyquinnwidget.live/freelivematch/7272152568433830.html

J'arrive a trouver le lien:
h ttp://185.39.11.106:8081/mamy.php?ch=zhengzhou2&width=640&height=360

Mais a partir de la, je ne sais pas comment pour trouver le lien final:
h ttp://185.39.11.106:8081/live/zhengzhou2.m3u8?e=1568241954&st=bguQbzntT9K-vsdmCW2_bg

Merci en avance de votre aide
sviet

**Comment by TmpName** [comment]
Alors la je suis désolé, mais je peux pas t'aider.
Tes liens ne sont plus valides, et quand je re-essaye sur le site, j'ai un autre type de lien.
Mais ton lien a l'air d'etre un lien final, j'a trouvé le meme dans un fichier de liens IPTV.

**Comment by sviet2k** [comment]
Merci de m'avoir repondu tres rapide.

Voici un nouveu lien si ca te tente. :)
h ttp://live.harleyquinnwidget.live/freelivematch/7259651634376640.html

Le final lien a trouver: h ttp://185.39.11.106:8081/live/vesplsh99.m3u8?e=1568252135&st=gcIrjTvgsFFvn3zwwfXISg mais je ne suis pas capable. :9

**Comment by TmpName** [comment]
De rien, franchement je crois que c'est la bonne solution, ce genre de site bouge beacoup, a maintenir a jour c'est enormement de boulot, alors si en plus faut passer des heures a faire un code qui risque de plus etre utilisé dans 15 jours ...

**Comment by sizanic** [comment]
Traité ici : 

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/7b81a5aeba66fba38ed18b448f3f09b9fb80fa81/plugin.video.vstream/resources/sites/livetv.py#L809

@sviet2k , toujours motivé pour nous aider ?
Fais-toi connaitre ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2727
