### ISSUE TITLE
Ajout d'une source html

### ISSUE THREAD

**Issue by yvandicara** [Kodi-vStream/venom-xbmc-addons#2612]
Bonsoir à tous,

J'ai un serveur perso avec un dossier film accessible via une adresse http.
Si j'ajoute cette source dans kodi il n'y pas de problème.

j'aimerai passer par vStream en utilisant votre fichier ajouter_une_source.py

J'ai mis mon lien http dans URL_MAIN =
dans les logs Kodi [PLUGIN] Vstream: could not load site: monsite: No module named monsite

Avez-vous un tuto détaillé pour l'ajout de source simple http?
Si j'ajoute cette source comment vStream gère les différentes catégories?
Comment Vstream va trouver les artwork?

Brefs quels sont tous les prérequis pour pourvoir ajouter une simple source http de fichier?

Merci beaucoup pour votre aide.

**Comment by johngf** [comment]
[dans le fichier](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_une_source.py) il y a des annotations qui explique
 -SITE_IDENTIFIER = 'nom de ton fichier .py' #identifant (nom de votre fichier) remplacez les espaces et les . par _ AUCUN CARACTERE SPECIAL
 - SITE_NAME = 'nom de ton fichier' #nom que xbmc affiche
 - SITE_DESC = 'pas vraiment utile' #description courte de votre source
 -URL_MAIN = 'http://le_site.org/' #url de votre source`

http://www.vstream.ml/docs/add/
