### ISSUE TITLE
Problème de lien en wifi

### ISSUE THREAD

**Issue by Gizey** [Kodi-vStream/venom-xbmc-addons#2613]
Bonjour, 
Pour commencer je tiens à remercier toute l équipe pour ce Plug-in fabuleux. 
Mon problème est que certains liens ne marchent pas quand je suis sur ma connexion WiFi (Bouygues) alors qu ils fonctionnent très bien quand je repasse en 4G (Orange). Je prend l exemple de la source "Ianime" qui est vide en WiFi et marche très bien en 4g.

**Mon system**
 - OS: Android
-  Appareil: Huawei p20 pro
 - Version Kodi 18.4
- Version Vstream 0.7.4

**Comment by Gizey** [comment]
J ai oublié de préciser que Kodi m affiche une erreur, notamment sur la source "planet streaming".
Quand je suis en WiFi il m affiche "Erreur: Connexion Impossible ([Errno 7])"
Alors qu en 4G aucun problème.

**Comment by zicmama** [comment]
Contrôle des DNS
Utiliser ceux de https://www.opennic.org/

**Comment by Gizey** [comment]
C est à dire désolé mais je ne comprend pas trop @zicmama

**Comment by zicmama** [comment]
Lorsque tu te connecte à un site web, il faut au préalable transformer
son nom en adresse IP.
C'est le rôle du DNS, une IP que donne ton fournisseur d'accès
(resolv.conf) avec ta propre adresse IP (DHCP).

Certains opérateurs "bloquent" des noms sur leurs DNS. Ca semble être le
cas chez Bouygues...

**Comment by TmpName** [comment]
Tu as un lien en page d'accueil qui explique comment changer les DNS.

**Comment by johngf** [comment]
c'est possible d'utiliser un dns prècis avec urllib2 ? depuis vstream ? pour le mettre par défaut.

**Comment by TmpName** [comment]
Ben en python surement, y avait des sites ou je bypassais directement le dns, en decodant moi meme l'IP, mais vu que celle ci bougeait, ca deconnait parfois et surtout impossible de faire un code marchant sur tout les systemes possibles.

Il y a aussi dnspython, mais comme precedement tu ne changes pas le serveur DNS, tu le remplaces, donc c'est pas anodin comme bidouille. Compare a un reglage dans les options de la machine je trouve ca vraiment plus sujet a problemes.

**Comment by johngf** [comment]
j'avais dans l'idée d'utiliser opendns pour les requetes

**Comment by TmpName** [comment]
Ben ca voudrait dire utiliser un semblant de mon code, mais au lieu d'utiliser les ip predecodée, passer par opendns pour avoir l'adresse.
Donc on se retrouverait avec la meme usine, je pense encore qu'un petit tuto sur l'utilisation de opendns sur l'OS est plus simple.
