### ISSUE TITLE
Nouvelle source non détectée

### ISSUE THREAD

**Issue by Brewyard** [Kodi-vStream/venom-xbmc-addons#2614]
Bonjour, alors je vous explique, je suis parti du fichier ajouter une source.py et j'ai -pour le moment- juste modifié les variables qui contiennent l'url, etc.
Lorsque je rajoute le fichier .py dans resources/sites et que je lance vstream et fais une recherche j'ai pas ma nouvelle source, j'ai regardé dans le menu Activer/desactiver sources mais je ne la vois pas, est-ce que j'oublie quelque chose ? Dans les log de kodi je vois rien à propos de ma nouvelle source non plus.
Kodi tourne sur ma MI BOX 3.
Merci d'avance

**Comment by johngf** [comment]
la recherche ne peut pas fonctionner si le fichier n'est meme pas commencé par contre ton fichier doit apparaitre en cliquant sur sources il doit etre dans la liste

**Comment by Brewyard** [comment]
J'ai laissé tout le code du ajouter_une_source.py , j'ai simplement renommé le fichier et changé le nom des variables comme dans le tuto et l'issue #2612, mais je comprends pas que le fichier soit pas au moins détecté dans les sources

**Comment by johngf** [comment]
le fichier doit avoir le meme nom que site identifier exemple:
 - SITE_IDENTIFIER = 'ddlfr'
 - ton fichier doit se nommer ddlfr.py

**Comment by Brewyard** [comment]
ça y est, en fait j'avais nommé mon fichier avec des traits d'unions et apparemment ça passe pas

**Comment by johngf** [comment]
verifie que la source n'est pas deja dans vstream
