### ISSUE TITLE
Live TV: N'affiche pas les matchs en direct

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2615]
**Décrivez le bug**
Dans les categories (ex: football), Live TV n' affiche pas les matchs en direct, affiche seulement les matchs de demain ou dans les heures qui suivent i.e. aucun lien n'est valide.

**Votre system**
- OS: Android
- Appareil: Android Box
- Kodi 18.4
- Vstream 0,7,4

Merci de votre aide

**Comment by sizanic** [comment]
Salut @sviet2k ,
c'est corrigé dans la Beta, récupères-la ou attends la prochaine mise à jour officielle.

**Comment by sviet2k** [comment]
Merci beaucoup pour le fix. 👍
