### ISSUE TITLE
TheMovieDB - Listes personnalisées

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2617]
Bonjour,

La source TheMovieDB propose des listes toutes faites.
Il s'agit de listes pré-enregistrées au nom de VStream sur le site TMDb.

J'ai remarqué que la liste ['Top Manga', '31665'] ne propose plus qu'un seul film.
Et la liste ['Top Manga 2', '31695']  est vide.

Je ne vais donc pas me permettre de les supprimer de la source car c'est quelqu'un de votre équipe qui les gère.

=> Comment sont maintenues ces listes ?
=> Peut-on se permettre d'ajouter/enlever des éléments ?

Pour proposer de nouvelles listes, le sujet avait été ouvert ici :
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1583

Mais comment maintenir une liste existante comme pour Manga.
(peut-on retrouver l'auteur de la liste originale ?)

**Comment by TmpName** [comment]
Moi j'ai 27 films dans une et 65 dans l'autre.
Donc tu as pu y acceder depuis ? Moi j'ai essayé les mots de passes classiques de @LordVenom et ca ne marche pas, ca doit donc etre son ancien compte privé.

Sinon oui c'est possible de retrouver l'auteur, mais si c'est son compte privé, il va pas choisir de le rendre public ^^. Mais c'est vrai que du coup, pas moyen de continuer ou modifier une liste existante.

Apres c'est pas mal de boulot, a maintenir, tu as deja l'air de pas mal faire bouger le code, tu veux vraiment te lancer la dedans ?

**Comment by LordVenom** [comment]
@TmpName  tu tente de pirater mon compte ? Xd tu as tester 123456 .

Tu ne peux pas modifier la liste mais tu peux en créer une nouvelle sur TMDB et la rendre public ensuite la mettre dans le code suffis d'avoir son ID je sais plus trop ou c'est mais c'est simple.

**Comment by sizanic** [comment]
Oui, j'ai vu que c'est simple d'ajouter une liste publique.

Ma question concerne les listes existantes.
Quelqu'un les a ajoutées, je demande juste avant de supprimer les listes qui ne sont plus maintenues (exemple supplémentaire, la liste des TOP séries).

Pour la création de nouvelles listes, je voudrais relancer un nouveau sujet.
Pour que tout le monde propose des listes.

Donc, puis-je supprimer de la source :
- manga ?
- manga 2 ?
- séries ?

(ou comptez-vous les réalimenter ?)

**Comment by LordVenom** [comment]
Tu peux modifier sans soucis, ce sont des listes public trouver sur tmdb ou mes listes perso mais je ne les touches plus depuis un bout de temps.

**Comment by TmpName** [comment]
lol @LordVenom, ouais bien sur, a chaque fois que tu ouvrais un compte sur un site sous le nom de Vstream, y avait des codes bateau pour que tout le monde s'y connecte, donc j'ai tenté.

**Comment by LordVenom** [comment]
Oui mais non ça gère aussi l'api TMDB et y a des infos perso dedans tient j'y est jeter un œil vite fait y a des stats de l'api pour votre plaisir voici les requêtes.

2 Dernières semaines : 2,976,624 de sessions.

4 Dernières semaines : 6,197,562 de sessions.
