### ISSUE TITLE
Tirexo saison x

### ISSUE THREAD

**Issue by AngelineL** [Kodi-vStream/venom-xbmc-addons#2618]
**Décrivez le bug**
Bonjour. 
Sur tirexo quand on fait la recherche d'une série ou quand on clique sur une série les saisons affichées sont toujours les mêmes ( ex: saison 4 Chesapeake shores...mais c'est comme ça pour toutes). Du coup c'est vraiment galère à trouver la bonne quand y'a beaucoup de saisons 
**Votre system**
 - OS: Android TV 
-  Appareil : mi box /shield
 - Version Kodi  18
- Version Vstream : 0.7.41

**Nous devons le reproduire**
Pour cela il nous faut:
- tirexo ( zone telehargement lol) 
- frères Scott Chesapeake shores... Mais c'est pour toutes il me semble

**Comment by sizanic** [comment]
Bonjour @AngelineL 

En effet.
Je vois le problème, je m'en occupe ...

**Comment by sizanic** [comment]
C'est corrigé.

![image](https://user-images.githubusercontent.com/47307622/65621560-4a9e8e80-dfc4-11e9-91ed-015dd85055bd.png)

Avec affichage de la langue en bonus.

Plus qu'a attendre la diffusion de la mise à jour...

**Comment by AngelineL** [comment]
Je viens d'essayer, c'est bon maintenant ça affiche les bonnes saisons. Merci beaucoup.
