### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by johnboisvert** [Kodi-vStream/venom-xbmc-addons#2619]
Tous d'abort merci ! 
Un gros MERCI!!! 
a tous l'equipes!! Ont ne vous remercies pas assez.. grâce  à vous moi, ma fille, mon gars, ma copine, mes freres etc.. ont ne s'ennuie plus grâce a vous et votre travail! 
Jai déjà faite des dons et je vien d'en refaire un de 50.00$ et continuez votre bon travail ce nest pas le dernier! 

Jaimerais rajouter aussi merci que ca soit gratuit a tous! Cest pas tous le monde qui ont l'argent pour un film au club video ou etc.. vous etes génial ! 

Merci merci merci!!!

**Comment by TmpName** [comment]
Alors d'abord merci a toi, ca fait plaisir a lire.

Par contre, désolé de jeter un pavé dans la marre, mais du coup moi de mon coté je ne gere plus du tout les dons, le compte est celui de Vstream, mais je ne sais pas qui est dessus, je ne sais meme pas si @LordVenom est encore dessus.

Du coup je ne sais pas si il faut laisser le lien ou pas ?

**Comment by johnboisvert** [comment]
Fais plaisir c'est mérité et merdeee :P je vais cancel au cas et si vous en avez un nouveau je referai

**Comment by TmpName** [comment]
Lol, t'en fais pas, quelqu'un va en profiter de toute facon.
C'est juste que je ne sais pas qui, ni si ce lien est toujours utile avec la team actuelle, par exemple avant, @LordVenom citait les donateurs a chaque MAJ, la vu qu'il n'est plus la ...

**Comment by LordVenom** [comment]
Ha oui c'est toujours mon compte paypal perso, remboursement effectuer. quelqu'un s'y colle pour enlever le lien svp :)

**Comment by johnboisvert** [comment]
Ahh merci 
je ne savais plus si c'étais encore actif etc...
publiez le quand vous aurez un système de don pour vous tous 
je vais refaire !! :)

**Comment by TmpName** [comment]
Ben la, y a plus vraiment de "boss" pour gerer ca ^^. En fait personne a voulu prendre la responsabilité de prendre en charge le projet, du coup on passe tous a temps perdu sans reel engagement.

Mais t'en fait pas, juste de voir quelques reactions sur le github fait plaisir :)

**Comment by johnboisvert** [comment]
Beaucoup ne connaisse pas ce github pour vous remercier ! :)

**Comment by lebigboss** [comment]
Alors, c'est où pour faire des donations ?

**Comment by TmpName** [comment]
lol, mais vous allez pas vous battre pour ca non plus.
Pour le moment y a plus, pour les remerciements vous reste plus qu'a filer la main sur les issues ^^.

**Comment by johngf** [comment]
je prend que des billets de 200 mdr

**Comment by TmpName** [comment]
Ouais les lingots, c'est trop lourd.
