### ISSUE TITLE
kepliz

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2624]
dans vstream a la source kepliz il y a lorsque que l'on veut voir un film deux choix de qualités , présentement ça dit 360p et 720p , pourriez-vous changer cela dans le code pour les vrais qualités qui sont 720p et 1080p
![Sans titre](https://user-images.githubusercontent.com/40530593/65934326-da887200-e3e2-11e9-98f1-ceec84205642.png)
![Sans titre2](https://user-images.githubusercontent.com/40530593/65934329-dceacc00-e3e2-11e9-9e36-94c88676350a.png)

 ,

**Comment by johngf** [comment]
ce n'est vstream qui affiche les mauvaise qualité ,c'est ce qui est dans le code source après avec goo_gle video souvent il y a plusieurs choix

**Comment by KodiTopQuebec** [comment]
ok merci je croyais que le 360 et 720 écrit en orange venaient du code , merci
