### ISSUE TITLE
Uptobox en direct

### ISSUE THREAD

**Issue by CharlyNetSky** [Kodi-vStream/venom-xbmc-addons#2630]
Bonsoir tout le monde,

Depuis maintenant quelques temps je n'ai plus accès au "rester en direct" sur les liens uptobox malgré mon compte premium. Cependant j'ai bien accès aux données via uptostream. J'ai regardé si quelqu'un avait déjà eu ce problème mais je n'ai rien trouvé.

Voici le lien du log : https://slexy.org/raw/s20M071uNo

Merci à vous !

**Comment by johngf** [comment]
test en renottant identifiant et mot de passe c'est déjà arrivé a une personne a ma connaissance.

**Comment by kenshiro000** [comment]
Regarde si tu as bien "les téléchargements directs" de désactivé dans les options de ton compte.

**Comment by CharlyNetSky** [comment]
Génial ça refonctionne ! Merci à vous !
