### ISSUE TITLE
Fichier mp4 source DISNEY HD

### ISSUE THREAD

**Issue by peto51** [Kodi-vStream/venom-xbmc-addons#2631]
Bonjour a tous, je voudrais rapporter un bug sur la source Disney HD

Tous les fichiers ne sont pas lisible sur la source Disney HD, a priori ce ne sont que les fichiers au format mp4 (le film cendrillon fonctionne mais pas cendrillon 2 : il m'affiche "aucune information") super référence vous allez me dire :)

OS: OSMC
Appareil Raspberry Py 3
Version Kodi 18.3
Version Vstream 0.7.42

j'ai essayé d'analyser le fichier .py de disney hd mais je ne suis pas assez calé pour ça.
par avance merci, je ne pense pas être le seul dans ce cas là.

**Comment by johngf** [comment]
oui il y a 2 bug mauvais film + trouve pas le lien je m'en occupe

**Comment by peto51** [comment]
Ok je testerai demain avec tes mis à jour, en tout cas merci de ta réponse rapide.

**Comment by peto51** [comment]
je viens de tester et ça marche nikel, merci johngf
