### ISSUE TITLE
Bug Strmng-Series.cx

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2632]
**Décrivez le bug**
Aucun lien host dans les dossiers hosts de chaque films  series etc
NB: y a aussi iptv dont aucun lien ne marche ou vide et certaines playlist iptv s'ouvre comme un dossier avec le contenu vide
**Votre system**
 - OS: [Windows, Android]
-  Appareil [vorke z6, S8+]
 - Version Kodi  [18 , 19]
- Version Vstream 0.7.42

**Nous devons le reproduire**
Pour cela il nous faut:
- Strmng-Series.cx/ dpstrmng.to
- tout les fim/serie 
- tous les host

**Comment by johngf** [comment]
mis a jour d74ba39
