### ISSUE TITLE
Tous sur Tirexo

### ISSUE THREAD

**Issue by isandard** [Kodi-vStream/venom-xbmc-addons#2633]
Bonjour serait il possible de rajouter les tous pour les films / series / animés car le menu tous correspond au dernier ajout et c'est bien pratique de se passer de certains filtres .
Films tous :  ./films-gratuit/
Series tous : ./telecharger-series/
Animes tous : ./animes/

**Comment by TmpName** [comment]
Quelque chose comme ca ? https://github.com/Kodi-vStream/venom-xbmc-addons/commit/9fb54edb68d1c0fd600744cea7ca4e2758976618#diff-81630a44ab993887374263566538b0b3

**Comment by isandard** [comment]
Exactement un truc comme ça, merci beaucoup TmpName :)
