### ISSUE TITLE
Tirexo message aucune information

### ISSUE THREAD

**Issue by isandard** [Kodi-vStream/venom-xbmc-addons#2634]
Bonjour,
Sur le site tirexo, peut importe que j'aille dans films ou autre il n'arrive pas a afficher la liste et affiche à la place : Aucune information.
J'ai tenté de changer l'adresse c'est pareil.
Mibox 3 android 8.0 Kodi 18.4
Voici l'adresse d'un log : https://slexy.org/view/s2NegOFFNA

**Comment by BENJI97200** [comment]
@isandard....slt pour moi aussi c pareil sur nvidia shield tv ,kodi 18.4

**Comment by lebigboss** [comment]
Pareil

**Comment by johngf** [comment]
testé rapidement acb0a63

**Comment by BENJI97200** [comment]
@johngf...merci bcp ca fonctionne

**Comment by isandard** [comment]
Effectivement merci beaucoup.

**Comment by kintoral** [comment]
Bonjour , Vous avez fait comment en faite pour réglé le problème j’ai pas trop compris ?. Merci

**Comment by BENJI97200** [comment]
@kintoral....slt ,télécharge le fichier de johngf....et copie le ds la Racine de kodi...
