### ISSUE TITLE
Sous dossier uptobox

### ISSUE THREAD

**Issue by Kastoner63** [Kodi-vStream/venom-xbmc-addons#2635]
Bonjour j'ai un problème je ne peut pas ajouter mes séries et ses sous-dossier présent sur mon compte uptobox premium.

J'utilise le duo vstream et osmosis mais j'ai une erreur quand je fait un clique droit puis create strms

 - OS: Windows10
-  Appareil PC
 - Version Kodi  18.4
- Version Vstream 0.7.4
- Version osmosis 1.0.7

**Comment by johngf** [comment]
[link](https://kodi.wiki/view/Internet_video_and_audio_streams) 
 - en gros c'est pas possible seul des liens playable (mp3,mp4 etc...) peuvent etre mis dans un strm pas les dossiers

**Comment by Kastoner63** [comment]
Sur ce post https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1862 vic1997 y avait réussi

**Comment by Kastoner63** [comment]
voici le lien de mon log https://slexy.org/view/S2ITV3J2XJ

**Comment by johngf** [comment]
tu as accès au sous dossier sur up tobox ( je viens de testé) 
 - mais un fichier strm est un raccourcis donc a mon avis ce n'est pas comme ça qu'il fait vaut mieux lui posé la question sur http://kodi-fr.rf.gd/?i=1
 - dans ton log l'erreur viens de osmosis

**Comment by Kastoner63** [comment]
Je lui est justement poser la question sur son forum. Merci en tous cas
