### ISSUE TITLE
nouveau dl protect ?

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2636]
Bonjour,
avez-vous déjà traité ce protecteur de lien ?
protect-
stream
.com

C'est celui utilisé par exemple sur ce site (clone de ZT, je sais) :
zone-
telechargement-
1.org

**Comment by TmpName** [comment]
Je pense pas, mais j'ai regardé vite fait, rien vu de mechant, ca a marché sans cookies, sans javascript.
J'ai juste vu une requete POST a faire avec 1 parametres de 10 km, ce parametre est visible dans la page precedente.

**Comment by TmpName** [comment]
Autant pour moi, il a l'air d'etre dans 'zone_telechargement_ws'

**Comment by Arias800** [comment]
Je confirme c'est bien un système qui est ou a été utilisé par zone_telechargement_ws ^^

**Comment by sizanic** [comment]
J'avais essayé de faire le POST avec les paramètres, et j'étais bien parti de la source ZT_WS.
Mais je n'y étais pas arrivé, c'est pour cela que je pose la question.

Merci pour vos réponses, cela me confirme que je suis sur la bonne piste, je vais persister.

**Comment by sizanic** [comment]
Impec'

Ca fonctionne mnt.

Je me suis relu et finalement je n'étais pas partie de ZT_WS, mais d'un autre code pour Display_protected_link.
Il me manquait des bouts de formatage pour mes paramètres, tel que urllib.quote_plus et urllib.urlencode.

Merci encore.

**Comment by TmpName** [comment]
Mais tu te fais un site perso ou tu veux rajouter un ZT dans vstream ?

**Comment by sizanic** [comment]
Je travaille en effet sur un clone de ZT.
Mais pas pour l'intégrer forcement tout de suite dans VStream.

C'est plus un exercice de style.

C'est un site sous WordPress, et plutot que de décortiquer avec des regex les pages HTML (qui bougent tout le temps), j'attaque le site par les WebService.

REST API : 
https://developer.wordpress.org/rest-api/reference/tags/

Exemple : 
https://zone-telechargement-1.org/wp-json/wp/v2/tags/

**Comment by TmpName** [comment]
Ha oui , bien vu et c'est surement plus stable que leur code html.
