### ISSUE TITLE
#2632Bug Strmng-Series.cx

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2641]
**Décrivez le bug**
Aucun lien host verystream ne se lance quelque ce soit la video, échec de lecture.
(Possiblement sur d'autres sites)

**Votre system**
 - OS: [Android]
-  Appareil [Z6 et wk3]
 - Version Kodi  [19 et 18]
- Version Vstream 0.7.43

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site dpstrm.cx
- Le titre du fim/serie  TOUTES
- Le nom du host (verystream)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
je viens de testé vite fait les griffin saison 18 episode 3 le premier lien very str_eam et il fonctionne
peut etre les liens sont hs sur quelle série tu as testé parceque toutes ... 
log

**Comment by Che-debarras** [comment]
GOTHAM ou FOR THE PEOPLE SAUF que quand un lien est HS on a une notification avec croix rouge en haut a droite
La c'est une impossibilité de lecture et jai essayé different lien host et cela met echec
Plus tard dans la journée c'est redevenu normal donc peut etre que le site effectue des changements.

On va dire c'est résolu mais ca arrive souvent sur ce site donc des fois impossible de lire des videos (ce n'est pas que verystre qui est affecté il y a aussi vidoza ou clipwatching sur cette source)

Il y a pas ce souci avec les autres sources ayant les memes host

**Comment by johngf** [comment]
ah ça c'est le systeme de protection du site qui bug parfois je l'ai déjà remarqué
et pour very stream parfois on a un timeout host surchargé

**Comment by starfoulay** [comment]
Salut je remarque la même chose sur tous les liens gounlimited et vidoza sur n'importe quel source host. J'ai checké un des site directement (streaming-series. Cx) effectivement les lecteurs du site ne fonctionnent pas mais si on clique sur le lien direct de la vidéo ça fonctionne. Des idées ?

**Comment by TmpName** [comment]
Ben je viens de tester, meme site siren S2E1, hoster gun, la video est partie de suite.
Tu aurais un exemple qui ne marche pas ?

**Comment by starfoulay** [comment]
Essaye par exemple south Park ou hannibal  n'importe quel épisode sur le même site

**Comment by starfoulay** [comment]
Je viens de tester aussi siren S2E1 résultat du gounlimited :  aucune information (écrit en rouge)

**Comment by starfoulay** [comment]
Log : https://slexy.org/view/s2NagPCeek

**Comment by TmpName** [comment]
Tu as oublié d'activer les logs dans les options de vstream (pas besoin de ceux de kodi) ^^.

**Comment by starfoulay** [comment]
Les notices de log vstream étaient activé dans option/outil. Et en dessous il me propose uniquement upload kodi.log et ensuite il m'a donné l'URL que j'ai envoyé

**Comment by starfoulay** [comment]
Je recommence https://slexy.org/view/s203SJejIb

**Comment by TmpName** [comment]
Ha wi mince, suis con, ca sert a rien, vu que tu n'as pas d'erreur, c'est juste que dans ton cas Vstream ne voit rien.

Mais la je vois pas, je viens de re-essayer hannibal saison 1 episode 1, j'ai eu le lien.

**Comment by starfoulay** [comment]
Ça voudrai dire que je suis le seul à qui il y a un problème ?

**Comment by starfoulay** [comment]
Ce qui est étrange c'est que il y a quelques jours tout fonctionnait les liens étaient tous valide

**Comment by starfoulay** [comment]
J'ai essayé avec plusieurs série du même site "streaming-series.cx" aucun lien ne fonctionne il y a toujours écrit aucune information en rouge

**Comment by johngf** [comment]
je l'ai mis a jour il a 14 jours test avec ce fichier [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/d74ba39f44616fd0042f5e1b694ff997b55a1ac7/plugin.video.vstream/resources/sites/streaming_series_xyz.py)

**Comment by starfoulay** [comment]
Je dois faire quelque chose avec ce fichier ? Dsl mais j'y connais vraiment rien

**Comment by TmpName** [comment]
@johngf viens de lancer une MAJ dns max 3 jours tu l'auras chez toi.

**Comment by starfoulay** [comment]
Super merci !!!

**Comment by starfoulay** [comment]
Bon bah je viens de faire la maj les liens streaming-series.cx ne fonctionnent toujours pas chez moi. Tant pis merci quand même de m'avoir accordé du temps

**Comment by johngf** [comment]
il faudrait activer les notices log dans les parametres de vstream et partager ton log de kodi pour voir ce qui cloche

**Comment by starfoulay** [comment]
https://slexy.org/view/s2UZ1guk7i 
Je viens de remarquer que presque rien ne fonctionne maintenant ça ne concerne pas que streaming-series.cx

**Comment by lebigboss** [comment]
streaming-series.cx fonctionne bien.
Je suis en 0.7.45 RAS

**Comment by starfoulay** [comment]
Bah je suis maudit alors

**Comment by lebigboss** [comment]
@starfoulay  essaie de redémarrer ton routeur

**Comment by Arias800** [comment]
Tout les liens que tu a ouvert sont mort ou alors qui ont fermer (voir cette issue https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2654)

**Comment by starfoulay** [comment]
OK je vois mais je comprends pas pourquoi streaming-series.cx fonctionne chez-vous et pas chez moi et quand je dis ça c'est aucune série qui fonctionne. Toujours écrit aucune information en rouge pour tout les liens

**Comment by starfoulay** [comment]
Je viens de tester plusieurs série de streaming-series.cx voici le log et c'est pas une histoire de lien mort c'est plutôt que mon vstream ne voit pas les liens
https://slexy.org/view/s21BOECdg1

**Comment by Arias800** [comment]
Le problème il viens de la :
`17:41:45.651 T:1666159584   DEBUG: erreur Invalid URL '/embed.lnk?video=djQEgWMxootglo2FdqMk0kGBCBSQk3GrkngigWGpAkcROaDrkngclkS6CWDnCkLPoj0aXODhdHOQE3GadnJ1bz==': No schema supplied. Perhaps you meant http:///embed.lnk?video=djQEgWMxootglo2FdqMk0kGBCBSQk3GrkngigWGpAkcROaDrkngclkS6CWDnCkLPoj0aXODhdHOQE3GadnJ1bz==?`
C'est bizarre car normal le code détecte si le liens commence par `/` et si c'est le cas il ajoute le domaine donc la je vois pas pourquoi ca ne veut pas marcher chez toi :/

**Comment by johngf** [comment]
@starfoulay est-ce que tu sais modifier des fichiers toi meme ?

**Comment by starfoulay** [comment]
Dsl mais ce genre de chose c'est du chinois pour moi c'est très handicapant d'ailleurs

**Comment by johngf** [comment]
telecharger un fichier et le copier dans le repertoire sites de vstream non plus ?

**Comment by starfoulay** [comment]
Ça Je pense pouvoir le faire

**Comment by johngf** [comment]
clic droit sur raw et enregister sous ou telecharger https://github.com/johngf/test/blob/master/streaming_series_xyz.py

**Comment by starfoulay** [comment]
Halleluja !!!!! Ça fonctionne merci mille fois !!!!!!!

**Comment by starfoulay** [comment]
Salut je viens de faire la nouvelle MAJ et gros problème plus rien ne fonctionne sur aucun site que ça soit film ou série. Est ce possible de retrouver la version précédente afin d'en rester là ?

**Comment by starfoulay** [comment]
Salut je reviens vers vous car j'ai remarqué le même problème sur d'autres sites (comme serie_streaming_watch et libre_streaming) et je voulais savoir si c'était possible de faire la même manip ou un truc du genre comme pour streaming-series.cx
Voici le log 
Https://slexy.org/view/s20GW5lg0n

**Comment by johngf** [comment]
serie str watch [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/6aea808a9fba5ecfd8551f2e13edddc2353060b0/plugin.video.vstream/resources/sites/serie_streaming_watch.py)

**Comment by starfoulay** [comment]
Top merci pour votre travail !!! j'aimerai bien savoir qu'est ce qu'il faut modifier a chaque fois pour que je puisse le faire tout seul les prochaines fois parce qu'il est vrai que j'ai pas forcement essayé toutes les source site et il est possible que le même soucis se passe ailleurs. En tout cas merci encore j'adore votre plugin j'espère qu'il vivra longtemps .

**Comment by johngf** [comment]
il y a rien de compliqué il faut regardé le code source de la page ou les urls la j'ai changé ça : 1eceef9
j'utilise [firefox 52 legacy](https://portableapps.com/apps/internet/firefox-portable-legacy-52) et [httpfox ](https://legacycollector.org/firefox-addons/6647/index.html)un ancien module de firefox qui n'a pas d'equivalent en webextension (norme d'aujourd'hui)

note : httpfox fonctionne sur waterfox et palemoon (normalement)

**Comment by TmpName** [comment]
C'est clair, meme les outils de debogguage integré a firefox me servent moins que httpfox/firebug.
De visu on a l'impression que c'est la meme chose mais a l'usage y a moins de probleme avec httpfox, deja il n'est jamais bloqué par des scripts JS.
