### ISSUE TITLE
Recherche globale HS dans certains cas, pour certains sites.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2643]
La recherche propre au site fonctionne, mais pas lors d'une recherche globale.
Les sites concernés sont ceux sous protection cloudflare.

Voir par ici > https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2601#event-2732075900

Le probleme viens du code cloudflare, le meme code est executé a chaque fois, mais il marche en recherche site, et abouti sur une erreur 403 en passant par la recherche globale.

Pas d'idée de mon coté .....

**Comment by johngf** [comment]
est-ce que c'est pas une histoire de cookie il faut peut etre changé de cookie pour chaque site

**Comment by TmpName** [comment]
J'ai essayé aussi, avec vieux cookie generé par une recherche sur le site, apres avoir effacé les cookies.
Et chaque site a son propre cookie basé sur le nom du site.

Nan franchement la je seche, faudrait comparer les requetes avec un truc comme wireshark pour voir ou se trouve cette diffrence, mais comme c'est en https now ....

J'ai meme essayé de coller des tempo aleatoires.

**Comment by johngf** [comment]
faudrait faire un test avec urllib3

**Comment by TmpName** [comment]
Ben la partie cloudflare utilise Request.
Urllib3, j y ai pas pensé, mais ce qui me saoule, c'est que c'est les memes requetes avec les memes fonctions, a croire que kodi fout un reglage en plus quand on fait une recherche globale.

Ce WE j'ai un peu de temps, je vais activer le debug python de kodi pour voir si je vois un truc.

**Comment by TmpName** [comment]
Page qui rate

```
[PLUGIN] Vstream: Page protegee par cloudflare
[PLUGIN] Vstream: Headers present {'Accept-charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7', 'Accept-language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3', 'User-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'}
[PLUGIN] Vstream: url ht_tps://ww_w.zone-telechargement.net/
[PLUGIN] Vstream: cookies passés__cfduid=d34c8c2e8e5fbba3fc0e6420c6c4d721572106876
[PLUGIN] Vstream: post data :
[PLUGIN] Vstream: Pas de cookies present sur disque
[PLUGIN] Vstream: Headers send : OrderedDict([('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), ('Accept-Language', 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3'), ('Accept-Encoding', 'gzip, deflate'), ('Connection', 'close'), ('Upgrade-Insecure-Requests', '1')])
[PLUGIN] Vstream: Cookies send : {'__cfduid': 'd34c8c2e8e5fbba3fc0e6420c6c4d721572106876'}
[PLUGIN] Vstream: url : ht_tps://w_ww.zone-telechargement.net/
[PLUGIN] Vstream: data send :
[PLUGIN] Vstream: param send : {}
[PLUGIN] Vstream: cookie recu {}
[PLUGIN] Vstream: 403 Forbidden
```

Page qui marche

```
[PLUGIN] Vstream: Page protegee par cloudflare
[PLUGIN] Vstream: Headers present {'Accept-charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7', 'Accept-language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3', 'User-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'}
[PLUGIN] Vstream: url h_ttps://ww_w.zone-telechargement.net/
[PLUGIN] Vstream: cookies passés__cfduid=d81bbf54aedfeb1ad449f67cecf1a5215210028
[PLUGIN] Vstream: post data :
[PLUGIN] Vstream: Pas de cookies present sur disque
[PLUGIN] Vstream: Headers send : OrderedDict([('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), ('Accept-Language', 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3'), ('Accept-Encoding', 'gzip, deflate'), ('Connection', 'close'), ('Upgrade-Insecure-Requests', '1')])
[PLUGIN] Vstream: Cookies send : {'__cfduid': 'd81bbf54aedfeb1ad449f67cecf1a5215210028'}
[PLUGIN] Vstream: url : ht_tps://ww_w.zone-telechargement.net/
[PLUGIN] Vstream: data send :
[PLUGIN] Vstream: param send : {}
[PLUGIN] Vstream: cookie recu {}
[PLUGIN] Vstream: Page still protected
[PLUGIN] Trying decoding, pass 1
```

Qui voit une difference ?

**Comment by TmpName** [comment]
Ok donc bonne nouvelle je pense avoir trouvé le probleme, mais pas corrigé encore
Dans recherchehandlers si on met
aFileNames = self.__getFileNamesFromFolder(sFolder) > bug
aFileNames = ['zone_telechargement_ws'] > ok

En fait il doit y avoir un fichier site avec un import special (comme ssl ou socket) qui fait tout planter.

Par contre j'ai plu le temps de trouver lequel.

Il faut passer tout les fichiers sites, ou alors a tatons avec les options de Vstream, desactiver la moitié des sites, refaire une recherche, si ca marche c'est un de ceux desactives, et ect ....

**Comment by sizanic** [comment]
Tu peux pas mettre un point d'arret là où ça bug,
et regarder dans la stacktrace le site appelant ?

Je peux essayer de regarder.
Mais tu veux dire quoi par 'bug' ? comment ce bug se présente ?

**Comment by johngf** [comment]
adkmi import httplib
free tele CloudflareBypass
you_tube.py utilise ssl sans l'importé (mis en false)

**Comment by johngf** [comment]
ex down 403
zt 503
planet str 503

**Comment by johngf** [comment]
en désactivant adkam la RG fonctionne sur planet str

**Comment by TmpName** [comment]
Ben en fait ya plusieurs moyen,
1 - sans toucher au code
Mettre ZT en liste de site autorisé + 4 sites en plus et lancer une recherche globale
Si ca marche on en rajoute 4, si ca rate le prb vient de l'un des 4
2 - En touchnant au code editer la liste de site au niveau de aFileNames =

Le bug est simple, ZT bloque sur une erreur 403 ou (503), sinon ca affiche des resultats pour lui
Et non il n'y a pas de bug pour tracer, en fait la fonction importe tout les fichiers, ca ne provoque pas de bug, sauf que un des fichiers doit avoir un import non compatible avec la lib cloudflare. Donc pas defaut lors de la mavaise manip, mais ca provoque un bug plus tard.
Enfin c'est une theorie, mais je vois que ca pour le moment.

**Comment by johngf** [comment]
pour moi c'est adkami le premier soucis

**Comment by TmpName** [comment]
Lol, et c'etait le premier.
Moi je confirme aussi, si je le desactive, les autres sites remarchent.

**Comment by johngf** [comment]
en plus je pense que httplib ne sert a rien

**Comment by TmpName** [comment]
Ben ca forcait urllib/request/socket ect .... (soit toute les lib) a passer en http 1.0. Et evidement cloudflare pas compatible avec ca.

Si le site remarche sans, fait virer juste les 3 lignes.

**Comment by DaX59** [comment]
Je pense qu'on peut passer en "résolu".
Pour ma part, les seuls erreurs que j'ai encore sont celles des sites tf*rjo (qui passe via 4G), filmstr**mvf et k-str**ming (à tester en changeant les DNS car passe pas en 4G)
