### ISSUE TITLE
Avenir de vstream et kodi

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2644]
J'écris ce post pour avoir votre avis sur l'avenir de vstream avec les futures versions de kodi 

Il se trouve que je met souvent a jour kodi version 19 et depuis l'apk rend incompatible Vstream(et d'autres addons)

La version nightly du 11.10.19 est le dernier avec vstream compatible mais depuis les versions du 12.10 jusqu'à ce jour Vstream n'est plus compatible.

Pensez vous que vstream va rester bloqué sur Kodi 18 ou des modications sont prévues ?

**Comment by TmpName** [comment]
On est obligé de suivre, on arrette pas le progres, obligé de s'adapter aux futures version meme si plus lentes, moins d'options et plus de bugs.
Par contre on attend toujours les officielles.

**Comment by Arias800** [comment]
Hum j'ai l'impression que c'est le début du passage en python 3 car visiblement tout les imports sont a refaire xD

**Comment by Arias800** [comment]
Bon bah je confirme ils ont bien rendu python 3 obligatoire. Bref il faut quasiment tout modifier chaque fichier a la main xD

**Comment by TmpName** [comment]
Sympa, du coup les fichiers sites seront incompatible d'une version a l'autre ? ou ca concerne que le coeur de Vstream ? Parce la synthaxe des imports est la meme entre  pyton2 et 3.

**Comment by Arias800** [comment]
J'ai commencer a faire les modif. Le plus gros des modif c'est au niveau du cœur mais il y a un taff important a faire. Par contre pour assurer la rétrocompatibilité je pense ajouter un paramètre dans setting qui va être automatiquement régler a chaque démarrage en ce basant sur un cas précis. Car sinon si on doit tout faire a coup de try et except ça va rendre le code illisible xD

**Comment by johngf** [comment]
je pense qu'il faut faire une version pour chaque en fonction du kodi

**Comment by Arias800** [comment]
Déjà j'ai centraliser tout les appel a urllib (quote, quote_plus...) directement dans le fichier utils.py comme ça il n'y qu'une seul fonction a changer. J'ai aussi remplacer tout les requêtes urllib par la fonction de requête de Vstream. Et pour finir tout les "print" on été remplacer par VSlog.

Oui c'est vrai que ça peux être la solution.

**Comment by Arias800** [comment]
Il n'y a qu'un seul site qui n'a pas besoin de modif. Ca va etre tellement long xD

**Comment by johngf** [comment]
j'ai pas pu testé la derniere nigthlies fonctionne pas avec windows 7 il manque des dll api ils font chier kodi

**Comment by Arias800** [comment]
Tu manque rien de toute facon en l'etat la build de marche pas correctement car la mise en cache est totalement inexistante xD

**Comment by johngf** [comment]
et dire que j'utilise principalement kodi 16,1 sur linux qui fonctionne trés bien ...

**Comment by TmpName** [comment]
@johngf tu m'etonnes, a chaque MAJ de nouvelle emmerdes, la j'ai l'IPTV en rade depuis kodi 18, tout le monde se plaint sur leur forum, mais ca les excite pas.

Par contre tu as quoi a modifier sur les fichiers sites ? Moi je partirais pour rendre les fichiers sites compatibles au maximum avec les diffrentes versions.

**Comment by johngf** [comment]
sinon il ya comme meme un soucis avec les meta 
2019-10-27 17:20:06.954 T:4012   ERROR: NEWADDON Unknown Video Info Key "backdrop_url"
2019-10-27 17:20:06.954 T:4012   ERROR: NEWADDON Unknown Video Info Key "cover_url"
2019-10-27 17:20:06.954 T:4012   ERROR: NEWADDON Unknown Video Info Key "imdb_id"
2019-10-27 17:20:06.971 T:4012   ERROR: NEWADDON Unknown Video Info Key "backdrop_url"
2019-10-27 17:20:06.971 T:4012   ERROR: NEWADDON Unknown Video Info Key "cover_url"
2019-10-27 17:20:06.971 T:4012   ERROR: NEWADDON Unknown Video Info Key "imdb_id"
2019-10-27 17:20:06.988 T:4012   ERROR: NEWADDON Unknown Video Info Key "backdrop_url"
2019-10-27 17:20:06.988 T:4012   ERROR: NEWADDON Unknown Video Info Key "cover_url"
2019-10-27 17:20:06.988 T:4012   ERROR: NEWADDON Unknown Video Info Key "imdb_id"
 et niveau hoster pas de fanart et quand on ne les utilise pas on a des erreur comme meme a cause de 
oGuiElement.getInfoLabel()

**Comment by johngf** [comment]
oui les fichier site seront simple a modifier mais le coeur...

**Comment by TmpName** [comment]
Yep ca c'est aussi depuis la MAJ de kodi 18.
Je vais te rechercher le lien, mais en fait pour pouvoir utiliser certains addons, les devs ont rajouté des champs meta, qui ne sont pas reconnu comme officiel par kodi.

**Comment by Arias800** [comment]
@TmpName C'est ce que je tente de faire. Pour les fichier site c'est tout simplement remplacer les fonction urllib par des fonction gérer par Vstream. Ce qui pose problème par contre c'est les accent car il ne sont pas du tout gérer de la même manière :/

**Comment by johngf** [comment]
on ne peut pas les cacher ces erreur avec genre raise NotImplementedError()

**Comment by TmpName** [comment]
Je sais pas, je crois qu'elle sont dans le core de Vstream, perso j'en ai supprimé 1 ou 2 qui ne servaient plus, mais les autres j'ai pas pu.

**Comment by sizanic** [comment]
> sinon il y a comme meme un soucis avec les meta
> 2019-10-27 17:20:06.954 T:4012 ERROR: NEWADDON Unknown Video Info Key "backdrop_url"
> 2019-10-27 17:20:06.954 T:4012 ERROR: NEWADDON Unknown Video Info Key "cover_url"
> ...
> et niveau hoster pas de fanart et quand on ne les utilise pas on a des erreur comme meme a cause de
> oGuiElement.getInfoLabel() dans hoster py

Je suis en train de travailler sur une refonte des meta, je regarde ça en même temps ...

**Comment by Arias800** [comment]
Tiens le système pour activer ou désactiver les sources est totalement hs en python 3. J’espère que c'est un bug du coter de Kodi xD

**Comment by Arias800** [comment]
Le gros problème pour le moment de l'alpha c'est le fait que le retour en arrière ne marche pas correctement :/

**Comment by TmpName** [comment]
@Arias800 C'est pas fait expres ?

**Comment by Arias800** [comment]
Non je pense pas car lors du retour en arrière l'affichage ne s'actualise pas jusqu’à ce que je sort de l'addon. Par contre je viens de tester avec l'addon de Youtube et ça fonctionne donc le problème doit venir de Vstream :/

**Comment by Arias800** [comment]
J'ai trouver d’où ça venais c'est le `cacheToDisc` de `xbmcplugin.endOfDirectory` qui ne marche pas sous Kodi 19

**Comment by TmpName** [comment]
XD, ils avaient fait pareil pour le V17, on en a parlé il y a quelques semaines ici.

**Comment by Arias800** [comment]
Jje vais mettre ça sur le fait que j'était fatiguer xD
Bon sinon mine de rien Kodi 19 a l'air de vachement bien tourner et j'ai bien avancer sur la compatibilité en python 3 ^^

**Comment by Arias800** [comment]
Bon je teste une dernière fois avec Kodi 18 et si ça fonctionne je fait le pull request pour ajouter le compatibilité avec python 3 en esperant avoir limite les problème xD

**Comment by Arias800** [comment]
Finalement non je ne vais pas pull car j'ai beaucoup de hoster a corriger xD

**Comment by johngf** [comment]
pour moi c'est beaucoup trop tôt, la beta n'est meme pas encore sortie.
poste tes fichiers sur ton github qu'on y jette un oeil

**Comment by johngf** [comment]
je vais pouvoir testé normalement, j'ai enfin installé win 10  ça a de la gueule 
![Capture2](https://user-images.githubusercontent.com/21311232/68069230-c2976b80-fd5d-11e9-903b-2ee19f40ecf1.PNG)

**Comment by Arias800** [comment]
Je vais mettre mes débuts de modif sur mon fork comme ca tu n'aurai pas a recommencer depuis le début ^^

**Comment by Arias800** [comment]
Voila j'ai tout mis dans le fork : https://github.com/Arias800/venom-xbmc-addons
Tout ne fonctionne peut etre pas mais ou mieux Vstream s'ouvre et est utilisable xD

**Comment by johngf** [comment]
j'ai juste jeter un oeuil a 2 3 fichier mais pour moi il est temps de passer a urllib3 compatible avec les 2 version

**Comment by papapat** [comment]
Dommage que la recherche de liens ne soit pas plus simple et rapide car il faut 20 minutes pour trouver un bon lien

**Comment by TmpName** [comment]
Certains sites sont vraiment lent (surtout quand ils sont avec CF activé), tu peux les desactiver dans les options.
Pour le reste, pas le choix on affiche tout ce que Vstream peut trouver, meme les liens morts.

Mais de mon coté je me sert jamais de la recherche globale, j'ai 2/3 sites que j'utilise dans 95% des cas et je passe directement par eux.
