### ISSUE TITLE
pb vstream et jdownloader

### ISSUE THREAD

**Issue by c0py34** [Kodi-vStream/venom-xbmc-addons#2645]
bonjour la communaute

je ne m'y connais pas en language python, je voudrais savoir comment faire pour pouvoir ajouter au menu contextuel de 'vstream' (kodi leia), une option pour coller l'url du fichier distant, donc d'un site de streaming, dans le presse papier afin que jdownloader qui surveille ce meme presse papier puisse recuperer' le lien du film en streaming' que je souhaiterais' eventuellement' telecharger ?

je m'y connais un peu en vb et c, mais je ne m'y retrouve peu en python;;;
si qq'un a une idée...

cordialement.
Alex

**Comment by TmpName** [comment]
Alors du coup je pense qu'il te faut les lien finaux ?
Tu trouveras ca dans le fichier hoster.py
Apres pour le fonction du presse papier, a part installer une lib du type pyperclip, je sais pas du tout si kodi en implemente une.

**Comment by c0py34** [comment]
merci bcp de ta reponse, j'ai trouver pour recuperer la variable du nom de fichier. saurais tu comment on declare cette lib si elle est supportee et ou la declarer, au debut du fichier hosteer.py ?

**Comment by TmpName** [comment]
Si tu veux pas te prendre la tete, telecharge la et installe la dans kodi (j'ai pas la procedure par contre, mais tu l as ici https://github.com/moedje/kodi-repo-gaymods/tree/master/script.module.pyperclip), car si tu las met dans Vstream c'est plus facile, mais a chaque MAJ tu risques de la perdre.
