### ISSUE TITLE
Planet Stream Hs Vstream KODI

### ISSUE THREAD

**Issue by OULALA75** [Kodi-vStream/venom-xbmc-addons#2646]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Salut les gas avez vous des souci pour Plante stream? quand je le lance il tourne après il se quitte tous seul pour les autres sources pas de souci j'ai bien mis la mise à jour de Vstream
Xiaomi BOX S Android 8.0

**Comment by johngf** [comment]
#2640
