### ISSUE TITLE
double appel

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#2647]
en voulant afficher le synopsis niveau hoster j'ai remarqué un truc dans le fichier gui un peu partout
`if oOutputParameterHandler.getValue('sMovieTitle'):`
`sTitle = oOutputParameterHandler.getValue('sMovieTitle')`
` oGuiElement.setFileName(sTitle)`
devrait etre:
`if oOutputParameterHandler.exist('sMovieTitle'):`
`sTitle = oOutputParameterHandler.getValue('sMovieTitle')`
` oGuiElement.setFileName(sTitle)`

ça doit etre la meme chose avec intputParameterHandler

et aussi je pense a remplacer bGetRedirectUrl [dans hoster.py](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/hoster.py#L23) qui ne sert a rien par sDescription pour afficher le synopsis niveau hoster certain site ne le donne qu'a la fin

**Comment by TmpName** [comment]
Yep, assez peu de chance de trouver une url dans un titre ^^

Quand a bredirecturl > # step 1 - bGetRedirectUrl in ein extra optionsObject verpacken

A mon avis, c'est tres vieux aussi ^^. Par contre c'est rare d'avoir le resume sur le lien final, on ne l'a pas toujours sur la liste de film, mais toujours une fois le film selectionné ?

**Comment by johngf** [comment]
c'est pas que pour le titre on appelle 2 fois getValue() une fois a la place de exist et une fois pour l'importé

pour le synopsis ça mais souvent arriver de l'avoir a la fin sur les sites mais on pouvait pas l'afficher donc.
