### ISSUE TITLE
kepliz  working v0.7.45 , Filmzenstream bug

### ISSUE THREAD

**Issue by yayo1702** [Kodi-vStream/venom-xbmc-addons#2651]
la source kepliz sur vstream v07.43 et v07.44 ne s'ouvre pas 

**Votre system**
 - OS: [Windows10, Android pie]

**Comment by yayo1702** [comment]
bonsoir, j'ai vidé le cache de kodi, le problème persiste, merci pour ce que vous faites pour nous

**Comment by sizanic** [comment]
Lorsque je teste, c'est en pas à pas.
Je vérifie toujours que je passe dans chaque nouvelle ligne que j'ajoute (donc pas d'effet de cache)
J'ai bien testé.
Je vais regarder pourquoi ça passe plus ...

**Comment by sizanic** [comment]
Pour le cache, je comprends ce que tu suggères.
Je me connecte une première fois au site lors d'un premier test, puis j'y reste connecté (donc sans passer par la page de garde) lors d'un deuxième test.
A voir...

**Comment by TmpName** [comment]
Honnettement j'ai pas vu pkoi ton code marchait pas, y a une subtilité qui m'echappe.

Ceci dit, je vois pas l'utilité de chercher l'url de base dans la fonction load(), elle ne sert pas dans cette fonction et il y a beaucoup de cas, ou on demarre direct par showmovies(), qui est aussi la suite apres load().
Les seuls cas ou elle fait vraiment gagner du temps c'est quand l'user va dans le menu "films" puis "documentaire" puis "animé", franchement je pense que ce cas est rare et lui fait que 2 rechargement en plus.

PS:
Par contre je commence a m y faire a ton systeme de "marquer vu" par titre  (j'ai un petit freeze en plus, mais je pense pas que ca vienne de ca) et franchement ca me sert.

**Comment by sizanic** [comment]
Après plusieurs tests, je l'ai finalement mis dans load car cette fonction n'est appelée qu'une seule fois et dès le début, et c'est ce que je recherchais. Même si on s'en sert pas là, c'est un peu comme une fonction "init" où on initialise les variables globales pour plus tard.

Et le cas le plus fréquent pour passer plusieurs fois dans showMovies c'est par :
Genre -> Suivant -> Suivant -> etc.
Et comme je trouve rien qui me plait, je change de genre et je recommence : ) 

Par contre je ne pense pas qu'on puisse arriver dans showMovies directement sans passer par load. Sinon oui, cela pose problème.
=> Est-ce possible ?

Sinon, je viens de faire un test rapide et je n'ai pas le problème sur mon Kodi.
Je vérifierai demain que je suis bien à jour sur tous les fichiers de v0.7.44.
C'est quoi exactement le symptome ?
Y'a pas une trace dans le log ?

Si je trouve ce qui bloque, j’espère pouvoir reproposer mes modifs de cette source (le revert dès que ça coince c'est un peu brutal :( 

PS:
Merci pour ton retour le "marquer vu", j'espérais provoquer ce genre de réaction :)

**Comment by yayo1702** [comment]
bonjour, merci bcp pour le taf kepliz marche a nouveau v0.7.45

**Comment by BENJI97200** [comment]
Bjr ,pour moi ne fonctionne pas ,une solution svp

**Comment by johngf** [comment]
@BENJI97200 il faut attendre la maj v0.7.45 ou telecharger ou copier coller le fichier
[ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/79a5aade8618c6816f1230ff908da16d78555202/plugin.video.vstream/resources/sites/kepliz_com.py)

**Comment by BENJI97200** [comment]
@johngf.....merci mais ne fonctionne tjrs pas ,ouvre les liens mais ne lit pas ....

**Comment by johngf** [comment]
c'est un probleme qui vient de chez toi alors @BENJI97200  je viens de testé a l'instant et c'est ok.
 - je me rapelle que tu avait une install avec plein d'erreur du aux addons et repos que tu avait installé  
regarde dans le log de kodi

**Comment by TmpName** [comment]
>Par contre je ne pense pas qu'on puisse arriver dans showMovies directement sans passer par load. Sinon oui, cela pose problème.
=> Est-ce possible ?

Ben si, justement ^^.
Via la recherche globale
Via les menu de bases > page "home" / film / derniers ajout, tu arrives direct a la page sans passer par le menu load.
Pour avoir vu les reactions sur le github, tres peu passent par "toute les sources" et ne connaissent meme pas cette sources (et la propose 2 fois par mois mini)

**Comment by BENJI97200** [comment]
@johngf ....j avais déjà désinstallé et réinstallé une version propre ....j ai réinstallé le fichier et ca passe mnt ...merci pour tout

**Comment by yayo1702** [comment]
je viens pour signaler un autre bug sur la source Filmzenstream, la source s'ouvre juste pour les genre sdes films ensuite aucune information, mais si on recherche un film dans l'option recherche de Vstream, la recherche s'effectue sur Filmzenstream sans problème.

**Comment by TmpName** [comment]
Modif en ligne, mais j'ai pas testé pour tout les liens, apres la correction est facile.

**Comment by sizanic** [comment]
OK, je m'y suis remis.
j'ai trouvé mon problème sur Kepliz.

Il ne vient pas de l'URLMain que je ne calcule qu'une seule fois.
Car même lorsqu'on arrive directement dans showMovies sans passer par load, je reforcais le recalcul de toute facon : 
```
    if not sMainUrl:
        sMainUrl = sLinkdyn()
```

Le problème vient d'ici, je ne fournis plus d'url dans le premier parametre (car sera calculé plus tard) : 
`MOVIE_NEWS = ('', 'showMovies')`

=> dans ce cas, on arrive dans showMovies sans le parametre sUrl.
Cela pose problème.

OK pour remettre comme avant.

Je cloture ce sujet.

@yayo1702  si tu as toujours un problème Filmzenstream, il faut recréer un sujet dédié.
on essaye de garder un problème par sujet de discussion, il ne suffit pas de changer le titre ;-)
