### ISSUE TITLE
Liste des hebergeurs fermé

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2654]
L'ACE a commencer a passer a l'action en fermant pas mal d'hébergeur. Donc inutile de nous avertir que les hébergeur suivant ne fonctionne plus :
   - Openload
   - Streamango
   - Streamcherry 
   - Verystream
   - RapidVideo

Source : 
https://torrentfreak.com/openload-and-others-taken-down-by-anti-piracy-alliance-ace-191031/
https://torrentfreak.com/rapidvideo-shuts-down-following-legal-pressure-from-warner-bros-and-netflix-191021/

**Comment by TmpName** [comment]
Harrrr, la ca va faire mal ....

**Comment by Arias800** [comment]
Et c'est que le début tu verra quand ce sera Uptobox ou 1fichier qui ferme xD

**Comment by lebigboss** [comment]
Oui mais là ça concerne uniquement le streaming. Peut être ils vont devoir arrêter uptostream. C'est pas des bonnes nouvelles.
J'aimais bien openload et streamango

**Comment by Arias800** [comment]
C'est surtout que les streaming touche beaucoup plus de personne. C'est pour ca que si jamais il réussissent a faire fermer un site comme Uptobox cela va en faire paniquer pour beaucoup car Uptobox n'est pas senser être touchable grâce a leurs localisation . Déjà que c'est déjà suffisant pour faire peur a certain (vu que verystream est down depuis hier).
Par contre a mon avis le prochain qu'ils vont tenter d'atteindre c'est gounlimited.

**Comment by lebigboss** [comment]
C'est vrai, d'ailleurs gounlimited ne fonctionne pas sur vstream ?
Mais toute façon on sait tous comment ça marche, ils ont fermé rapidshare et megaupload et derrière il y a eux 15 hébergeur qui ont ouvert pour récupérer les clients

**Comment by Arias800** [comment]
Gounlimited marche sur Vstream.
Après l'ACE existe depuis un moment sans pour autant qu'ils ferme quoique ce sois. Hors la ça fait quand même 5 hébergeur en a peut prés une semaine et a mon avis c'est pas les derniers. Car je pense que la c'est Disney qui a pris les choses en mains pour préparer l'arriver de Disney + ^^

**Comment by lebigboss** [comment]
Oui ça fait peur. 
En parlant de Disney+ j'ai vue leurs programmes et ça a l'air tellement nul que pour eux le streaming ça ne les touches pas normalement. D'ailleurs la j'étais en train de regarder le pilote d'une série Apple et c'est digne d'un film, alors avec tous les abonnements qui se prépare je pense que ça risque surtout de faire augmenter le piratage.

**Comment by Arias800** [comment]
C'est le problème des abonnements car en plus de couter chère il faut que ce soit rentabiliser. Par exemple je regarde peu de série et de film donc je ne prendrai pas d'abonnement Netflix car je ne pourrai jamais le rentabiliser xD

**Comment by lebigboss** [comment]
Fait comme moi. Demande un code a un ami, c'est plus rentable 😊😊

**Comment by Arias800** [comment]
Faudrait t-il avoir un ami qui dispose d'un abonnement Netflix ce qui n'est pas mon cas xD

**Comment by zicmama** [comment]
Les portes du cyberespace se ferment !! Sa privatisation est bientôt terminée...
Je propose d'organiser la retraite de ce web2.0... Motivé par la marchandisation effrénée de toute valeur imposé à tous par l'usage de la "monnaie dette"!!!

En déployant vstream dans un essaim [IPFS](https://ipfs.io ) associé à des portefeuilles de [monnaie libre](https://monnaie-libre.fr/). On pourrait bâtir un Mediacenter [mode Web3.0 sympa](https://www.copylaradio.com/blog/blog-1/post/jukebox-interplanetaire-9) ;)

Pour y parvenir, il faudrait que je puisse configurer vstream pour qu'il lance **"Lire et DL"** par défaut dans un répertoire fixé.
Là, je m'occupe de transférer, identifier, asocier à un wallet le fichier dans IPFS... Et fournir une table indexée par "Nom du Film - Qualité" (ou mieux)...

On transforme ces "hébergeurs qui ferment" en essaim de stockage Libre.
https://www.youtube.com/watch?v=SjoYIz_3JLI

**Comment by DaX59** [comment]
Salut,
si on a la liste des serveurs down, on peut pas les masquer sur les différents sites dans les résultats ?

**Comment by TmpName** [comment]
Non, mais on pourra les virer oui, dans le futur, pour le moment moi j'attend.
Faut dire que c'est tres recent, faut voir comment ca va evoluer.
- les sites peuvent les virer eux meme.
- les hebergeurs peuvent re-ouvrir
- les hebergeurs peuvent juste changer de nom.

**Comment by TmpName** [comment]
Bon ben, 20 jours apres, pas de news.
Je pense qu'on va les virer du coup.

**Comment by eco-plus** [comment]
@TmpName ou @Arias800 [mystr fix](https://gist.github.com/eco-plus/2def06ff358a15591db517a25abbfc34)

**Comment by TmpName** [comment]
@eco-plus joli modif, merci, je viens de l'envoyer.

**Comment by eco-plus** [comment]
host strea mz il faut ajouter `+'&Referer=' + self.__sUrl '` a apicall

**Comment by TmpName** [comment]
J'ai pas la machine pr tester, je fais la modif en aveugle.

Par contre tu es sur quel site pour avoir autant de source HS, moi je suis sur voirfilm mais quand je verifis, les lien sont morts (en put1 y en a a la toque)

**Comment by eco-plus** [comment]
sur otakufr .
@TmpName ou @Arias800 [ne tu fix](https://gist.github.com/eco-plus/d6249e152d6f32d41af99878404ba5d0)

ne tu, h qq, wa aw a réactiver.

**Comment by TmpName** [comment]
Netu remarche ?

**Comment by eco-plus** [comment]
test sur film stream vk j'ai mis une annotations en haut

**Comment by TmpName** [comment]
Yeahhh, rien que pour ca, ca vaut le coup de faire une maj.
Par contre pour le coup j'ai l'impression que c'est trop tard pour eux, ils sont de moins en moins utilisé sur les autres sites.

**Comment by eco-plus** [comment]
il faut remettre a jour my str ils sont passé au m3u8 [here](https://gist.github.com/eco-plus/2def06ff358a15591db517a25abbfc34)

**Comment by TmpName** [comment]
Mit en place et je refais un MAJ de suite.

**Comment by eco-plus** [comment]
[ne tu](https://gist.github.com/eco-plus/d6249e152d6f32d41af99878404ba5d0)
