### ISSUE TITLE
Problème Top Replay

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#2655]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Papounet58** [comment]
La plupart des liens sur Top Replay renvoient sur " aucunes informations "
Dernière mise à jour effectuée et cache vidé.
Utilise Kodi 18.4

**Comment by johngf** [comment]
quand c'est le cas c'est parce que les liens sont des (netu,hqq) protégé par recaptcha
pour pouvoir les play dans kodi il faudrait un solver de captcha payant.
donc c'est hs

**Comment by Papounet58** [comment]
Merci

Bon week-end
