### ISSUE TITLE
could not find suitable input format when download video on vstream

### ISSUE THREAD

**Issue by Trinamic2130** [Kodi-vStream/venom-xbmc-addons#2656]
Hello, I would like to download a stream video but when I click on download I choose the location for the downloading video and click on ok a popup appear "Format Not Supported". The video if a .flv file, I read the kodi log and found this:
ERROR : could not find suitable input format x-directory/normal
I know this not "a bug" but I would like to know if there is a workaround solution, Thank for your help

Bonjour, j'aimerais télécharger une vidéo qui n'est pas hébergée chez un site web du style openload (rip) mais en "lien direct". Quand je clique sur Download une pop-up apparaît "Format non supporté", la vidéo est un fichier .flv. J'aimerais donc savoir si il existe une solution de contournement, (je me demande si il ne serait pas possible de récuperer l'url de la video vu que c'est un lien direct et la télécharger depuis un navigateur, mais je ne sais pas comment). Merci d'avance pour votre aide

Je précise tout de même que votre addons reste génial :)

**Comment by TmpName** [comment]
Alors la franchement actives les logs, et tu devrais avoir plus d'infos.
1 - L'url du fichier
2 - Pourquoi ce message, car il n'apparait que si le fichier ne commence pas par http ou fini par m3u8

**Comment by johngf** [comment]
a mon avis c'est des lien premium
 - certain sont mis lien direct parce qu'ils finnisent par mp4 ex: nitro flare etc..

**Comment by Trinamic2130** [comment]
Bonjours, merci pour votre aide, j'ai essayé d'activer les log et je n'ai pas trouver l'url mais juste ça:
ERROR : could not find suitable input format x-directory/normal
Je précise que j'arrive sans problème a dl un .mp4 ou .avi, je suis actuellement avec windows 10 et sans - dans le nom d'utilisateur, j'ai aussi essayé sur une android tv mais sans succès.
Si ce sont des liens preniums il n'y a aucun moyen de les récupérer ?
Merci encore

**Comment by Trinamic2130** [comment]
Ah si j'ai trouvé le lien, le soucis étant que je ne peux visualiser les logs que depuis Kodi, donc je ne l'ai pas en entier... J'ai cherché dans AppData\Roaming\ le dossier Kodi n'existe pas alors que kodi me dit qu'il si trouve...

**Comment by Trinamic2130** [comment]
Après quelque recherche, j'ai trouver le dossier Kodi qui n'était pas a sa place et j'ai donc pu récupérer le lien: https://slave4.hdsto.me/hls/ecaefa0775d296b2570e3be3d6ffb5ad/ecaefa0775d296b2570e3be3d6ffb5ad.playlist.m3u8
Il termine par m3u8 ce qui justifie ce message si j'ai bien compris ?

**Comment by Trinamic2130** [comment]
Voici les logs ou j'ai trouver le lien:
DEBUG: 	[PLUGIN] Vstream: Rajout en liste de telechargement https://slave4.hdsto.me/hls/ecaefa0775d296b2570e3be3d6ffb5ad/ecaefa0775d296b2570e3be3d6ffb5ad.playlist.m3u8
DEBUG: CAddonSettings[plugin.video.vstream]: loading setting definitions
DEBUG: CAddonSettings[plugin.video.vstream]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[plugin.video.vstream]: loading setting values
DEBUG: CSettingsManager: requested setting (home_update) was not found.
DEBUG: CAddonSettings[plugin.video.vstream]: failed to find definition for setting home_update. Creating a setting on-the-fly...
DEBUG: CSettingsManager: requested setting (hoster_firstonetv_password) was not found.
DEBUG: CAddonSettings[plugin.video.vstream]: failed to find definition for setting hoster_firstonetv_password. Creating a setting on-the-fly...
DEBUG: CSettingsManager: requested setting (hoster_firstonetv_premium) was not found.
DEBUG: CAddonSettings[plugin.video.vstream]: failed to find definition for setting hoster_firstonetv_premium. Creating a setting on-the-fly...
DEBUG: CSettingsManager: requested setting (hoster_firstonetv_username) was not found.
DEBUG: CAddonSettings[plugin.video.vstream]: failed to find definition for setting hoster_firstonetv_username. Creating a setting on-the-fly...
DEBUG: CSettingsManager: requested setting (plugin_cineiz) was not found.
DEBUG: CAddonSettings[plugin.video.vstream]: failed to find definition for setting plugin_cineiz. Creating a setting on-the-fly...
DEBUG: CSettingsManager: requested setting (plugin_cinemavf) was not found.
DEBUG: CAddonSettings[plugin.video.vstream]: failed to find definition for setting plugin_cinemavf. Creating a setting on-the-fly...
DEBUG: CSettingsManager: requested setting (plugin_ddl_island_su) was not found.

**Comment by johngf** [comment]
ligne 3 on ne peut pas télécharger un m3u8 c'est comme un fichier text , pas une video

**Comment by Trinamic2130** [comment]
Ok... Merci de votre aide en tout cas
