### ISSUE TITLE
Fichiers UpToBox

### ISSUE THREAD

**Issue by speedjeje** [Kodi-vStream/venom-xbmc-addons#2660]
Bonjour,
Utilisateur de vStream, je cherche à supprimer les fichiers de mon compte UpToBox directement depuis l'interface.
Est-ce possible ?
Quelle est la procédure ?
Merci
Speedjéjé

PS: un grand merci pour tout le boulot fourni qui nous ravi tous les jours

**Comment by johngf** [comment]
avant (il y a longtemps) oui j'avais fait le code maintenant il faut que je regarde a l'occaz

**Comment by speedjeje** [comment]
Un petit up ... :+1:

**Comment by isandard** [comment]
au passage j'avais proposé une modif pour les repertoires.
En effet j'ai classé sur mon compte uptobox les fichiers dans des repertoires ( pour les series notamment ) et le but etait de pouvoir faire clic droit et "lire à partir de cet épisode".
mais pour ça il faut que le repertoire soit affiché par nom et non par date d'ajout.

Le soucis c'est que je ne m'y connais pas assez en github donc du coup je propose ici ma version modifiée.
A la racine, on laisse par date d'ajout car souvent cette zone est pour les fichiers non classés, mais par contre dès qu'on est dans un répertoire elle classe différemment .

Je l'ai compressé en zip pour qu'elle soit prise par github, si quelqu'un pouvait le mettre sur la prochaine mise à jour si il le souhaite :)
[siteuptobox.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4246428/siteuptobox.zip)
