### ISSUE TITLE
Plus rien ne fonctionne

### ISSUE THREAD

**Issue by michellemikor84** [Kodi-vStream/venom-xbmc-addons#2661]
Tout d'abord un tout grand merci pour votre travail !!!
Cette nuit je regardais une série et tout s'est coupé et depuis plus rien.
Pourriez-vous me dire si c'est général ou si c'est juste chez moi.

**Comment by johngf** [comment]
bah si ça fonctionne sur quel site tu as eu le soucis ?

**Comment by michellemikor84** [comment]
zone téléchargement mais j'ai beau essayer d'autres sites cela ne fonctionne pas je crois que je vais réinstaller kodi.
Pour l'instant j'ai la dernière version de kodi, j'espère que ce n'est pas elle qui cause des problèmes.
Bon au boulot, je commence cela de suite et je donne des news.

**Comment by michellemikor84** [comment]
J'ai réinstaller vstream et tout fonctionne.
Super merci bien
