### ISSUE TITLE
Extreme down et AllDebrid

### ISSUE THREAD

**Issue by Wolsey20** [Kodi-vStream/venom-xbmc-addons#2662]
Bonjour,

Connexion impossible de alldebrid sur extreme down soit avec mes identifiants ou le token.
A chaque fois vstream me dit token ajouter, mais rien ne se passe et je ne suis pas identifier j'ai essayer sur Windows et Android avec la version actuelle ou beta de vstrream toujours la même chose. (kodi 18.4).

**Comment by lebigboss** [comment]
Chez moi ça fonctionne sur ma Shield

**Comment by Wolsey20** [comment]
Sur ma Shield ça marcher aussi, mais j'ai fait une réinitialisation d'usine et depuis impossible de se connecter

**Comment by lebigboss** [comment]
Comment ça une réinitialisation d'usine ?
Tu utilise urlresolver ?
Est-ce que tu as bien configuré ton vstream pour les comptes premium ?

**Comment by Wolsey20** [comment]
oui  j'ai fais une réinitialisation d'usine de la Shield donc j'ai du réinstaller vstream et mes autre applications
oui j'utilise URL revolver tout et bien configurer et marche très bien, les liens son débrider
ils y a qu'avec extreme down que sa bug
![Capture 2](https://user-images.githubusercontent.com/39297004/68530574-b5542100-0309-11ea-83ba-594cffc82664.PNG)
![Capture](https://user-images.githubusercontent.com/39297004/68530575-b5542100-0309-11ea-9500-c248d4ded4c4.PNG)

**Comment by lebigboss** [comment]
Pour l'instant a mon avis re essaie, tu as peut être mal tapé ton mot de passe

**Comment by BENJI97200** [comment]
@lebigboss...bjr tu peux m aider a configurer extrem down ....car avant ca fonctionnait super bien mais depuis que j ai desinstalle et réinstallé...ça ne passe plus ....une aide stp?

**Comment by lebigboss** [comment]
Il faut déjà récupérer son token alldebrid, il est directement sur le site dans mon compte
"Synology / App token :"
et l'insérer dans le fichier Extreme Down

**Comment by BENJI97200** [comment]
@lebigboss ...sur le site alldebrid?....je ne trouve pas ...

**Comment by BENJI97200** [comment]
@lebigboss....c bon j ai trouvé le token....et je le copie ou? Ds Extrem down.py?

**Comment by lebigboss** [comment]
@BENJI97200  Désolé en faite je connais plus trop la méthode précise, ça fait plusieurs mois que je ne l'ai pas fait.
Je fais toujours des backup de kodi et ensuite je restaure les backups.

Demande a un autre ou alors je vais essayer de voir comment on fait sur mon ordinateur

**Comment by BENJI97200** [comment]
Ok merci

**Comment by BENJI97200** [comment]
Car je ne sais vraiment pas où copier le token...merci pour ton aide

**Comment by Wolsey20** [comment]
Dans vstream tu vas sur sources puis choisis extreme down clique sur le message en rouge et rentre le token tu auras un message token ajouter.
Après pour mon cas ça ne marche toujours pas peut être alldebrid a changer quelque chose sur l'identification ( sur urlresolver sa marche pas code pin https://alldebrid.fr/pin/ )

**Comment by BENJI97200** [comment]
@Wolsey20..... bjr....pour moi aussi ne fonctionne pas

**Comment by lebigboss** [comment]
Désolé les gars je vous est complètement zappé.
En faite il faut utiliser un autre DNS pour accéder aux liens. Mais il y a des adresses DNS qui ne fonctionne pas, parce exemple sur DNS Changer il y a des adresses qui sont bloqués par le site.

**Comment by BENJI97200** [comment]
@lebigboss ...slt ne fonctionne tjrs pas mm en changeant le dns....j ai tjrs : mettre ici le lien du hoster après avoir...............manuellement

**Comment by lebigboss** [comment]
@BENJI97200  essaie en désactivant les urlresolver et resolveurl

**Comment by BENJI97200** [comment]
@lebigboss ....rien a faire tjrs mettre ici le lien du hoster........

**Comment by Wolsey20** [comment]
La même chose, ça ne marche pas, toujours le problème d' identification  j'ai rentrai manuellement le token dans le fichier de extreme down, je n'ai plus le message en rouge qui demande de s'identifier, mais après quand je clique sur un lien j'ai plus rien, j'ai le message aucune information (fais sur plusieurs lien).
![Capture kodi](https://user-images.githubusercontent.com/39297004/68804313-bff01c80-0661-11ea-98de-a7917263ce9c.png)

**Comment by BENJI97200** [comment]
@Wolsey20 ....slt le token tu l as mis ou ds extrem down py (a quelle ligne)....stp?

**Comment by Wolsey20** [comment]
Slt, Lignes 81 et 620

**Comment by BENJI97200** [comment]
Snifff,ne passe tjrs pas

**Comment by BENJI97200** [comment]
@Wolsey20 ....quand je met le token ....extrem down n apparait plus ...tu peux me faire une capture d ecran du token inséré ds extrem down py Stp?Merci

**Comment by Wolsey20** [comment]
Il faut mettre le token entre les 2 guillemets 
![vstream](https://user-images.githubusercontent.com/39297004/68853319-fcf7f580-06d9-11ea-8845-b1a48868bec8.png)
![vstream 2](https://user-images.githubusercontent.com/39297004/68853321-fff2e600-06d9-11ea-845c-2f6a85a8fc53.png)

**Comment by BENJI97200** [comment]
@Wolsey20 ....j ai fais comme tu as dis ....la mnt extrem down ne s ouvre plus ...merci pour tout mais j abandonne ....merci

**Comment by lelooser** [comment]
Désinstaller/réinstaller Kodi
Télécharger [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/archive/0.7.21.zip)
Extraire le dossier venom-xbmc-addons-0.7.21.zip\venom-xbmc-addons-0.7.21\repo\repository.vstream\repository.vstream-0.0.3.zip et venom-xbmc-addons-0.7.21.zip\venom-xbmc-addons-0.7.21\plugin.video.vstream à rezipper
Installer les 2 zip dans kodi
Fermer kodi
Copier son token sur ht tps://alldebrid.fr/account/
Coller son token à la ligne setting id="token_alldebrid" value="xxxxxxxxxx" dans le fichier \\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\settings.xml 
Les liens extrem down sont de nouveau accessible
Faire la mise à jour vers 0.7.46
Pour que la recherche sur extrem down fonctionne remplacer le fichier .py [ici](https://pastebin.com/raw/fVmKV2JG)
Désolais, je suis pas développeur pour modifier directement le fichier pour que tout refontionne directement.

**Comment by BENJI97200** [comment]
@lelooser ....slt ,je n arrive pas a modifier le fichier xml....car je n ai pas compri (l histoire de dézipper),tu peux m expliquer stp ,merci

**Comment by BENJI97200** [comment]
@lelooser ....j ai réussi a modifier le fichier ,je n ai plus l ecriture rouge des utilisateurs alldebrid.....,mais ne passe tjrs pas....j ai tjrs le hoster manuellement.......

**Comment by lelooser** [comment]
Installe une release antérieur à la 0.7.41 il me semble et désactive la maj auto.
supprime le fichier settings
lance et ferme kodi
Modifie le fichier settings avec ton token

**Comment by BENJI97200** [comment]
@lelooser ... merci mais trop compliqué pour moi....j abandonne merci en tout cas ....merci de ton aide
