### ISSUE TITLE
Même problème ERREUR 503 Planet streaming

### ISSUE THREAD

**Issue by Nicoco17** [Kodi-vStream/venom-xbmc-addons#2663]
Bonjour
J'ai le même problème d'errreur 503 avec le site planet streaming.
Je suis sur KODI 18.4 avec Vstream  0.7.46
Merci pour votre aide car c'est le meilleur site proposé à mon sens et je ne n'ai plus accès.

**Comment by TmpName** [comment]
Ce site est bloque sur mon FAI aussi, il te faut changer les serveur DNS, tu as un lien pour t'expliquer ca sur la page d'acceuil du github.

**Comment by dlaweb** [comment]
Voici un tuto pour changer le dns d'un raspberry pi :
https://pimylifeup.com/raspberry-pi-dns-settings/

**Comment by Nicoco17** [comment]
Bonjour
J'ai installé Kodi sur mon PC et cela fonctionne.
J'a suivi le tuto pour changer le fichier resolv.conf, mais a redémarrage du raspberry, c'est toujours la même valeur qui est inscrite soit nameserver 192.168.1.1
Pour éviter que le système ne réécrive j'ai fait un chattr +i /etc/resolv.conf mais j'ai le essage suivant
chattr: Operation not supported while reading flags on /etc/resolv.conf

**Comment by Nicoco17** [comment]
avez vous des propositions?
Merci

**Comment by dlaweb** [comment]
essaye de mettre ça :  nohook resolv.conf
dans ton fichier : /etc/dhcpcd.conf

**Comment by Nicoco17** [comment]
Bonjour
je n'a pas de fichier /etc/dhcpcd.conf

**Comment by dlaweb** [comment]
Même /etc/dhcp/dhcpd.conf ?

**Comment by Nicoco17** [comment]
Non pas de dhcpd
