### ISSUE TITLE
Wawacity  et DDL Island ?

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2667]
Salut à vous, je voulais savoir si Wawacity co et DDL Island co avaient complétement disparu de vos projets ?
Ils font partis de mes sites préférer personnellement

**Comment by TmpName** [comment]
Alors pr le second, ca a ete mit en pause a cause du recaptcha.
Et wawacity pareil, donc pas de retours prevus.

**Comment by lebigboss** [comment]
@TmpName  Ok dommage merci en tout cas
