### ISSUE TITLE
Hosts qui  bug

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2668]
**Décrivez le bug**
L hébergeur clipwatching ne fonctionne pas depuis quelque jour et je n'ai rien vu qu'il soit dans le viseur pour etre supprimé puisque régulièrement il y a de nouveaux film et serie ajouter sur les différentes source.
Donc je pense un bug de vstream qui ne lis plus ce fichier host
 
De même pour openload.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [Windows 10 et Vorke Z6]
 - Version Kodi  [17 & 18]
- Version Vstream 0.7.46

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site dpstrm.cx
- Le titre du fim/serie toute
- Le nom du host (openload/vidzi) clipwatching et openload

**Comment by johngf** [comment]
6aea808
open_load a fermé normalement #2654

**Comment by Che-debarras** [comment]
Merci c'est résolu
