### ISSUE TITLE
Jetload

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#2670]
Le hoster Jetload sur les dernières nouveautés de Planet Streaming ne fonctionne pas

Box Android
Kodi 18.4

Merci à vous

**Comment by johngf** [comment]
mis a jour ddabca23a8e03e41a81d69fb031ae7bd64ce6ddd

**Comment by Papounet58** [comment]
Quelle rapidité.

Merci à vous.

Bon WE

**Comment by adsav1** [comment]
Bonjour
Je viens de faire une MAJ et chez moi aussi, les séries ne se lancent pas depuis cet hébergeur.
Que faire?

**Comment by Papounet58** [comment]
J'ai installé la version Béta de Vstream et cela fonctionne.
Sinon vous pouvez attendre la nouvelle mise à jour qui ne saurait tarder.
Bien à vous

**Comment by Che-debarras** [comment]
Cela depend des fichiers et faut des fois patienter.
Moi aussi les series recentes bug mais pas les anciens
Donc je pense pas que c un bug de vstream

**Comment by adsav1** [comment]
Pouvez vous poster ici lorsqu'une prochaine MAJ fera fonctionner les nouveaux hébergeurs?

**Comment by TmpName** [comment]
La prochaine MAJ sera un maj complete du plugin donc elle va se faire par kodi sans que tu ne touches rien.
Tu devrais l'avoir dans les jours a venir.

**Comment by christophe006** [comment]
Bonjour,
J'ai bien eu une MaJ aujoudhui en 0.75 mais depuis plus rien ne fonctionne. 
Sur streaming HD je n'arrive pas a voir les liens. Ils n'apparaissent pas apres la mise en cache.
Je n'arrive plus a me connecter sur ZT.

**Comment by Makoto83** [comment]
Tu as quoi comme erreur ? 
Car moi depuis j'ai Erreur décryptage du lien.

**Comment by christophe006** [comment]
Aucune erreur visible. 
Juste si je selectionne une saison d'une serie rien ne se passe.
Je vois bien le message mise en cache et, habituellement j'atteri sur une page avec le lien du fichier uptoox par ex. La, l'ecran reste sur la meme fenetre.

**Comment by Makoto83** [comment]
Ah on a pas le même problème :(
Moi tout marche sur mon PC normal mais le petit pc de salon même après réinstallation tout propre ça ne marche pas :(

**Comment by johngf** [comment]
déja je vous conseille de changer vos dns il y a un lien en page d'accueil en bas

**Comment by christophe006** [comment]
J'utilise un VPN et en changeant le dns j'ai toujours "fichier non trouve" sur les liens Netu et jetload (quelquesoit le lien)

**Comment by johngf** [comment]
netu c'est normal pour jet load la 0.7.5 règle le soucis

**Comment by christophe006** [comment]
Toujours fichier introuvable sur jetload en testant plusieurs liens recents :(

**Comment by johngf** [comment]
sur quel site quel liens ?

**Comment by christophe006** [comment]
Par ex un episode de la serie "The mandalorian" ou "See" sur jetload retourne systematiquement "fichier introuvable". 
Comment je peux connaitre le lien de l'episode pour verifier sur le site?

**Comment by johngf** [comment]
je viens de testé ça fonctionne see  sur streaming hd donc... 
va sur le site internet et regarde si tu arrive a lire l'épisode

**Comment by christophe006** [comment]
Je ne connais pas l'adresse exacte du site streaming hd (celle que j'ai rentree, streaming-hd.fr ne semble pas bonne car je ne trouve pas la serie see).
Je suis alle dans les logs et j'ai essaye de rentrer direct l'adresse du fichier du lien  jetload mais j'obtiens l'erreur  "cannot read property 'encoding status' of null"

**Comment by TmpName** [comment]
Tu as cette erreur dans un navigateur ?

**Comment by christophe006** [comment]
Oui tout a fait. Sous le navigateur de la box android.

**Comment by johngf** [comment]
c'est le mystere des box androis il y a toujour un truc qu'il font pas comme les autres

**Comment by christophe006** [comment]
Hourraaaaaa apres mise a jour ce matin ca fonctionne...
