### ISSUE TITLE
Résultats différents sur 2 VStream à jour

### ISSUE THREAD

**Issue by Benian86** [Kodi-vStream/venom-xbmc-addons#2672]
**Décrivez le bug**
Lors d'une recherche d'une série sur mon smartphone et ma box TV, j'obtiens des résultats différents sur Vstream (Moins de résultats ou liens morts sur ma box alors que ces liens fonctionnent sur smartphone et que les deux modules sont à jour)

**Votre system**
Système n°1
 - OS : android
-  Appareil : One Plus
 - Version Kodi  : 18
- Version Vstream : 0.7.4 a jour

Système n°2
- OS : Android TV
- Appareil : NVIDIA SHIELD
- Version Kofi : 18
- version Vstream : 0.7.4 a jour

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : fullstream (exemple A), streaming-series (exemple B)
- Le titre du fim/serie : The mandalorian
- Le nom du host : 
    * A : pas de résultat sur le box mais uptostrem et vidoza présents sur smartphone
    * B : gounlimited fonctionnel sur smartphone et aucun lecteur sur box

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
![Screenshot_20191116-154506](https://user-images.githubusercontent.com/35571271/68994930-9238ec80-0888-11ea-9985-a597dfc51a76.jpg)
![IMG_20191116_154436](https://user-images.githubusercontent.com/35571271/68994931-9238ec80-0888-11ea-8773-fc18db21f835.jpg)
![Screenshot_20191116-154414](https://user-images.githubusercontent.com/35571271/68994932-9238ec80-0888-11ea-95a0-103badb67270.jpg)
![IMG_20191116_154547](https://user-images.githubusercontent.com/35571271/68994933-92d18300-0888-11ea-97c7-9ab1485c8049.jpg)

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Benian86** [comment]
Après vérification de ma par la version box est en 0.7.42 et le smartphone en 0.7.46. je n'ai pas de mise a jour proposée. Comment puis-je forcer la mise a jour ?

**Comment by Che-debarras** [comment]
En téléchargeant la beta directement sur le github de vstream tout en bas de la page

**Comment by Benian86** [comment]
Merci, je n'ai pas réussi a installer la bêta mais en desinstallant et réinstallant Vstream, il m'a proposé la mise a jour et a réglé le problème. Merci du support.
