### ISSUE TITLE
Openmeta player

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2673]
Bonjour et merci d’assurer l’entretien de cet additiel indispensable aux francophones utilisant Kodi!

Je me demandais s’il était possible d’intégrer vStream comme « player » avec l’additiel Openmeta?

J’ai essayé de faire fonctionner l’ancien  fichier .json auparavant développé pour metalliq, mais il ne fonctionne pas bien.... 

(Je fais référence au fichier  proposé par @Arias800 présenté sur cette page:  http://www.vstream.ml/docs/metalliq/  )

Bien que ce dernier soit reconnu comme player, la fonction de recherche avec openmeta recommence en boucle au lieu de présenter les résultats de recherche.

Merci à l’avance de votre aide!

**Comment by alKODIque** [comment]
Re-bonjour!
Personne ne peut me venir en aide sur ce sujet?

Merci!

**Comment by TmpName** [comment]
Ben, dsl mais de mon coté je ne vois meme pas de quoi tu parles ^^, c'est pas du tout un truc que je suis.

**Comment by melmel0101** [comment]
bonjour, 
j'ai le meme probleme.

**Comment by alKODIque** [comment]
Bonjour!
Effectivement, j’en suis arrivé à la même conclusion que toi... Un bug d’openmeta puisqu’avec l’additiel Meta original (Meta4kodi) vStream fonctionne très bien (côté films seulement.. car meta ne gère plus les séries)

Dommage que  les devs de openmeta ne semblent pas vouloir s’attarder à ce bug.

**Comment by melmel0101** [comment]
re, alors moi j'ai modifié le fichier: play_base.py (dans addons\plugin.video.openmeta\resources\lib)
j'ai modifier : 
def on_play_video(players, params, trakt_ids=None):
	assert players
	action_cancel()
	selection = get_video_link(players, params)
	if not selection:
		return
	link = selection['path']
    if link.startswith('videodb://'):
        return xbmc.executebuiltin('ActivateWindow(10025,"%s")' % link)
    elif link.endswith('.strm'):
        return action_playmedia(link)
    else:
        if trakt_ids:
            plugin.setProperty('script.trakt.ids', json.dumps(trakt_ids))
        return link
    return None
par: 
def on_play_video(players, params, trakt_ids=None):
	assert players
	action_cancel()
	selection = get_video_link(players, params)
	if not selection:
		return
	link = selection['path']
	if link.startswith('videodb://'):
		return xbmc.executebuiltin('ActivateWindow(10025,"%s")' % link)
	elif link.endswith('.strm'):
		return action_playmedia(link)
	else:
		if trakt_ids:
			plugin.setProperty('script.trakt.ids', json.dumps(trakt_ids))
		**### return xbmc.executebuiltin('ActivateWindow(10025,"%s")' % link)**
	return None

je pense que sa modifie pleins de truc (je ne sais pas bien lesquels) mais vstream fonctionne.

**Comment by alKODIque** [comment]
C’est génial!! 
J’ai fait la modification et magiiiiiiie!
Qu’une simple petite ligne a ajouter... 
Grand merci à toi!

Maintenant faut vite sauvegarder une copie pour ne pas perdre lors de la prochaine MAJ

MERCI MERCI MERCI

**Comment by alKODIque** [comment]
@melmel0101 

De mon côté, suite à la dernière mise à jour de l’addiciel « themoviedb helper » developpé par @jurialmunky, j’ai fait un player pour pour vStream. Si ça t’intéresse, il te faudra insérer mon fichier sous:

userdata/addon_data/plugin.video.themoviedb.helper/players/

Voici donc mon fichier (il faut le nommer « vStream.json » avant de l’enregistrer dans le dosdier « players » que tu devra créer à l’endroit que j’ai inscrit plus haut:

{ "name" : "vStream", "plugin" : "plugin.video.vstream", "search_movie" : "plugin://plugin.video.vstream/?function=showSearch&sCat=1&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(Films)&action=activate&searchtext={title}/", "search_episode" : "plugin://plugin.video.vstream/?function=showSearch&sCat=2&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(S%c3%a9ries%2fAnim%c3%a9s)&action=activate&searchtext={showname}/" }

Pour plus d’informations sur l’addon « themoviedb helper », voir:


https://github.com/jurialmunkey/plugin.video.themoviedb.helper
