### ISSUE TITLE
VFSPlayer bug

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2674]
**Décrivez le bug**
Sur une source flmstub je voit vfsplayer mais quand j'ouvre le dossier host je ne voit aucun lien host.
Est ce un nouveau host non pris en charge ou désactivé ?
Merci

**Votre system**
 - OS: [Windows, Android]
-  Appareil [Pc et Vorke z6]
 - Version Kodi  [18 et 19]
- Version Vstream 0.7.46

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site flmstub
- Le titre du fim/serie elementary
- Le nom du host (VFSPlayer)

**Comment by TmpName** [comment]
Je dirais non pris en charge, ou alors c'est un player fictif, mais je suis pas arrivé a tomber dessus pr tester.

**Comment by Che-debarras** [comment]
Ok sinon même question pour onlystream qui ne fonctionne pas sur la serie elementary de la source Ianime

**Comment by TmpName** [comment]
Onlystrm > https://github.com/Kodi-vStream/venom-xbmc-addons/commit/4da29412dbee74df50734280f248b8d948aeee97#diff-6994203b203d641e1927aec64c07f08f

Tu aurais un ex pour ls VSF player ?

**Comment by Che-debarras** [comment]
C'est-à-dire un exemple? 
Sur le site web il s'appelle ça  VFSVIP j'ai lancé la belle et le clochard et ça marche sur leur site mais sur la source de vstream non

**Comment by TmpName** [comment]
Pas trouvé, flmstub, recherche , "belle", et j'ai 2 films a la con.

**Comment by johngf** [comment]
c'est sur full Stream 2 et il n'est pas pris en charge encore

**Comment by Che-debarras** [comment]
Ok dsl pour l'erreur de souce. Donc il suffit juste d'attendre la correction. 
Merci

**Comment by TmpName** [comment]
@johngf exact, j'ai juste changé le nom et ca a marche direct.
