### ISSUE TITLE
wiflix.net?

### ISSUE THREAD

**Issue by flowtime** [Kodi-vStream/venom-xbmc-addons#2680]
Salut la team,
pensez-vous pouvoir ajouter wiflix sur vstream?
Je trouve le contenu clair, et pas mal de truefrench indiqué comme tel.
Je me retrouve souvent avec des version quebec et j'attends toujours la sortie truefrench (histoire de gout).
Bon ce n'est pas la seule raison, je trouve le contenu du site à jour et bien fourni avec des services stream assez rapides.

**Comment by johngf** [comment]
commencer 9cd458f2a484a2ad0b40da1347d9e0e0fe5875d2
nouveau host dipo sur ce site aussi dont un que je n'ai pas réussi a play avec kodi

**Comment by flowtime** [comment]
J'ai tenté de créer une source hier pour reprendre un peu la programmation, pas encore réussi :)
Tu dis qu'elle existe déjà si j'ai bien compris?

**Comment by johngf** [comment]
non je viens de de le commencer
