### ISSUE TITLE
plus de NBA sur robin des droits 

### ISSUE THREAD

**Issue by kauderni35** [Kodi-vStream/venom-xbmc-addons#2681]
Salut

super site , bien géré...mais plus de nba depuis un bout de temps !!!
Un soucis ?

sebastien

**Comment by johngf** [comment]
genre sport us nba > mis a jours

**Comment by kauderni35** [comment]
j'ai pas compris ??? je dois faire quelque chose avec ton lien ???

désolé !

sebastien

**Comment by TmpName** [comment]
Ca veut juste dire que c'est corrigé.
Tu l'auras a la prochaine MAJ.
