### ISSUE TITLE
kaydo(hdss.to)

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2682]
**Décrivez le bug**
lorsque l'on veut partir un lien de cette source cela fait planter kodi , a partir du site directement il est possible de faire fonctionner les films , mais a partir de vstream cela est mort et même si j essaye les 2 liens directs proposés , merci 

 - OS: [Windows, Android]windows, android, androidtv  etc
-  Appareil [nvidia shield, Ultra] tout les types de boitier 
 - Version Kodi  [16.17.18]18.5
- Version Vstream 17.5 (et même la bêta du 2 dec installé)

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by TmpName** [comment]
Pas pu m'y connecter, captcha en place.

**Comment by KodiTopQuebec** [comment]
a partir du site directement si l on prend le 2 em serveur qui est Playme
Français - HD le film démarre

**Comment by johngf** [comment]
il y a un soucis meme quand on récup le bon fichier m3u8

**Comment by TmpName** [comment]
Par contre faudra que quelqu'un m'explique comment fonctionne le captcha sur son site ? C'est fonction de l'alignement des planetes ou de son horoscope ?

**Comment by Arka06** [comment]
Est ce que quelqu'un a des nouvelles de ce bug qui est toujours persistant ?

**Comment by ddav33** [comment]
J'ai le même problème, avant la mise à jours vstream j'avais deux liens qui fessait sauter kodi maintenant un lien mais toujours qui fait sortir de kodi
Android 6 kodi 18.5 vstream toutes versions bêta et mises à jours

**Comment by TmpName** [comment]
Ben moi je peux pas m'y connecter, donc si on pouvait au moins avoir un log pr jeter un oeil ?

**Comment by johngf** [comment]
quelque chose a encore changé je pense a kodi 18 qui a du mal avec les ( m3u8 ssl/hls ) ou un cookie  parce que fichier goog user content a l'interieur du m3u8.

**Comment by rvitch** [comment]
si je peux essayer de faire avancer un peu, le site semble avoir migré sur https://hdss.co

**Comment by johngf** [comment]
non il a 2 ou plusieurs adresse comme bcp de site

**Comment by johngf** [comment]
sinon certain film fonctionne d'autre non parce que kodi ne peut pas les lire .
- ils mettent des extension ( .png, .jpg, .txt ) qui ne sont pas des format vidéo dans les fichier m3u8 au lieu de ( .ts .mp4 etc...)
donc kodi ne sait pas le lire et bug
