### ISSUE TITLE
themoviedb helper vs Extended info script

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2683]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Une description claire et concise de ce qu'est le problème. Ex. Je suis toujours frustré quand [...]

**Décrivez la solution que vous souhaitez**
Une description claire et concise de ce à quoi vous voulez arriver.

Bonjour,

Petite suggestion bien que vous sachiez beaucoup mieux que moi si ceci est faisable... Présentement, dans la page de configuration de vStream, nous avons la possibilité de demander d’ouvrir Extended info Script pour se procurer l’information des films et Séries.  Puisque le script n’est plus mis à jour ni entretenu, serait-il possible de remplacer par l’additiel « themoviedb helper » ? Il est un peu le remplaçant de Extended info et en plus d’être disponible dans le repo officiel de kodi, nous avons la possibilité de créer un dossier « players » dans le script et d’y insérer un fichier json de vStream (j’ai créer un fichier et testé, ça fonctionne vraiment bien)

Merci beaucoup et bonne journée!

**Comment by alKODIque** [comment]
Info sur Themoviedb helper:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper

Mon fichier « player » de vStream:


{ "name" : "vStream", "plugin" : "plugin.video.vstream", "search_movie" : "plugin://plugin.video.vstream/?function=showSearch&sCat=1&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(Films)&action=activate&searchtext={title}/", "search_episode" : "plugin://plugin.video.vstream/?function=showSearch&sCat=2&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(S%c3%a9ries%2fAnim%c3%a9s)&action=activate&searchtext={showname}/" }

**Comment by Djej30** [comment]
> Info sur Themoviedb helper:
> https://github.com/jurialmunkey/plugin.video.themoviedb.helper
> 
> Mon fichier « player » de vStream:
> 
> { "name" : "vStream", "plugin" : "plugin.video.vstream", "search_movie" : "plugin://plugin.video.vstream/?function=showSearch&sCat=1&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(Films)&action=activate&searchtext={title}/", "search_episode" : "plugin://plugin.video.vstream/?function=showSearch&sCat=2&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(S%c3%a9ries%2fAnim%c3%a9s)&action=activate&searchtext={showname}/" }

Bonjour @alKODIque 
Comment faite vous pour rajouter le player vstream dans tmdb helper?
J'ai créer un fichier json en copiant  votre commande, j'ai mis le fichier dans le fichier player de tdmb helper, mais quand je clique sur play sur une vignette d'un film un message d'erreur apparait.
PS: Je suis nul en programmation

**Comment by karimgharbi5** [comment]
il faut 

> > Info sur Themoviedb helper:
> > https://github.com/jurialmunkey/plugin.video.themoviedb.helper
> > Mon fichier « player » de vStream:
> > { "name" : "vStream", "plugin" : "plugin.video.vstream", "search_movie" : "plugin://plugin.video.vstream/?function=showSearch&sCat=1&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(Films)&action=activate&searchtext={title}/", "search_episode" : "plugin://plugin.video.vstream/?function=showSearch&sCat=2&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(S%c3%a9ries%2fAnim%c3%a9s)&action=activate&searchtext={showname}/" }
> 
> Bonjour @alKODIque
> Comment faite vous pour rajouter le player vstream dans tmdb helper?
> J'ai créer un fichier json en copiant votre commande, j'ai mis le fichier dans le fichier player de tdmb helper, mais quand je clique sur play sur une vignette d'un film un message d'erreur apparait.
> PS: Je suis nul en programmation

il faut enlever les / après {showname} et {title} et mettre des espaces comme ça 
![vs](https://user-images.githubusercontent.com/85798622/121781295-566d2280-cba4-11eb-9d69-5e83d80d841b.PNG)
