### ISSUE TITLE
Vstream Errno 111

### ISSUE THREAD

**Issue by DEGARDO986** [Kodi-vStream/venom-xbmc-addons#2684]
Bonjour,
Lorsque je suis sur Vstream et que je fais une recherche de film, j'ai une erreur Errno 111 et aucun liens fonctionnent.
Avant ça fonctionnait.
J'ai une freebox.
J'ai réinitialisé ma box android (toujours pareil).
Merci pour votre retour.

**Comment by TmpName** [comment]
Tu as un autre plugin utilisant internet et qui fonctionne dessus ?
Vas voir dans "sources" si en prenant les fichiers sites directement ca marche mieux.
Sinon il faudrait un log.

**Comment by DEGARDO986** [comment]
Bonjour TmpName,

Qu'appelles-tu log ?

**Comment by TmpName** [comment]
http://www.vstream.ml/docs/outils/

**Comment by DEGARDO986** [comment]
Bonjour,
J'ai activé le mode debug dans Kodi.
Le fichier de debug ne s'enregistre pas pour pouvoir le poster.

**Comment by DEGARDO986** [comment]
Au fait, j'ai oublié de préciser.
J'ai une box android Z69 plus
Kodi V18.5 Leia
Vstream 0.7.5

**Comment by DaX59** [comment]
Hello,
@TmpName , j'en ai parlé sur l'autre issue et je n'ai pas vu que le topic remontait le problème réel.
Les erreurs me font un peu pensé aux problèmes d'il y a un mois environ : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2643
Dans le log, voilà ce que j'ai de bizarre : 
En début de recherche, il va tout de suite sur extreme-d--w mais il recherche sur w**v**w (pourquoi un v ...) 

> 2019-12-19 00:17:17.666 T:27123  NOTICE: 	[PLUGIN] Vstream: url : https://wvw.extreme-d-w-.xyz/home.html
2019-12-19 00:17:17.687 T:27123  NOTICE: 	[PLUGIN] Vstream: Method : POST
2019-12-19 00:17:17.707 T:27123  NOTICE: 	[PLUGIN] Vstream: param send :

> 
Ensuite j'ai les sites suivants qui sont en erreur 111 : 
**Pour les films :**
filmstr-a-vf
k-str-am-ng
fr.planet-stre-m-ng.net
stre-m-z.org
zone-t-l-charg-ment.net

**Pour les séries :** 
Les mêmes qu'au dessus +
dadyfl-x.ws

**Comment by TmpName** [comment]
@DaX59 Essayes de te connecter sur les sites avec un navigateur et la meme machine.
chez moi ca a marché au moins sur 2 de ces sites, surement un bloquage DNS.

**Comment by DaX59** [comment]
@TmpName , en effet, rien ne fonctionne alors qu'il y a 3 semaines c'était good.
On dirait que Free a bloqué les sites en question.
par contre, c'est normal que pour extreme d*wn ça soit wvw ?
Merci pour l'info en tout cas.

**Comment by TmpName** [comment]
La je sais pas, tu peux mettre ce que tu veux en adresse. Je ne vois pas ca codé en dur dans le fichier site, donc je pense que le code a reelement trouvé cette url sur leur site.
