### ISSUE TITLE
Vstream sur Fire Stick TV amazon

### ISSUE THREAD

**Issue by moz-kito** [Kodi-vStream/venom-xbmc-addons#2685]
**Décrivez le bug**
bonjour,
j'ai beau chercher un peu partout, je n'ai pas trouver de solution à mon problème sur la toile.
vous êtes donc mon dernier recours. 
j'ai installé kodi+Vstream sur mon Fire Stick TV amazon.
Jusqu'il y a quelques semaines, tout se passait bien, mais voilà un moment que Vstream ne trouve plus aucun film. tous les dossiers sont vides, il n'y a plus de lien.
j'ai donc desinstallé Vstream et réinstallé d'après ce site 👍 ht tps://hitechland.fr/installation-de-vstream-sur-kodi/
mais ça n'a rien changé. :(
je n'y connais pas grand chose. Donc si vous pouvez m'aiguiller, ça serait cool. Merci.

**Votre system**
 - OS: - Android
-  Appareil : Amazon Fire TV
 - Version Kodi  18.0
- Version Vstream : 0.7.5

**Comment by johngf** [comment]
- activer le mode debug de Vstream dans les parametres  de vstream
  - faire quelque test sur un site
  - puis le fichier log bien lire http://www.vstream.ml/docs/outils/

**Comment by ludopotte** [comment]
Bonjour moz-kito, 
Pour résoudre le Problème de Site qui ne marche pas sur vStream sur Android, Android TV et Fire Stick TV,, il faut changer le DNS car ça résout les problèmes des sites de Streaming qui font l'objet de contrôle par Hadopi en utilisant l'Application "DNS Changer" disponible sur le Play Store pour Android et Android TV au https://play.google.com/store/apps/details?id=com.burakgon.dnschanger&hl=fr et disponible sur Aptoide pour Fire Stick TV au https://dns-changer.fr.aptoide.com/

**Comment by TmpName** [comment]
Deja desinstaller/reinstaller ne sert a rien, pire vous perdez des mise a jour.
Le site ou vous avez lu le mode d'emploi pr l'installation est bidon. Il y a une adresse officielle pour le repo, qui se trouve tout simplement sur ce github.

**Comment by moz-kito** [comment]
> * activer le mode debug de Vstream dans les parametres  de vstream
> * faire quelque test sur un site
> * puis le fichier log bien lire http://www.vstream.ml/docs/outils/

d'abord, merci à tous les 3 de prendre du temps pour me répondre.

bon, vous allez dire que je suis une quiche, mais je ne trouve pas ou activer le mode debug dans les paramètres de Vstream (je suis bien allé dans les paramètres Vstream et non ceux de Kodi)

j'ai quand même un fichier log ici : https://slexy.org/view/s2Zkjqi1hr
mais je ne sais pas s'il va vous être utile, vu que je n'ai pas activer le debug avant.

**Comment by johngf** [comment]
22:04:48.888 T:22492  NOTICE: 	[PLUGIN] Vstream: SQL ERROR EXECUTE a voir

**Comment by moz-kito** [comment]
> Le site ou vous avez lu le mode d'emploi pr l'installation est bidon. Il y a une adresse officielle pour le repo, qui se trouve tout simplement sur ce github.

ok, du coup, est-ce qu'il vaut mieux que je désinstalle/réinstalle depuis cette adresse ?

**Comment by johngf** [comment]
test ça oui

**Comment by moz-kito** [comment]
j'ai réinstallé depuis ce lien http://www.vstream.ml/repo/ mais c'est pareil. tous les dossiers sont vides. je vois bien des jaquette de film, mais c'est tout.

je vais essayer DNS changer.

**Comment by TmpName** [comment]
Gros soucis sur les bases de donnée. En plus du bug de @johngf tu as aussi des
>22:04:56.805 T:22516  NOTICE: 	[PLUGIN] Vstream: erreur: Impossible d ecrire sur /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.vstream/vstream.db
22:04:56.827 T:22516  NOTICE: 	[PLUGIN] Vstream: erreur: Impossible de ce connecter sur /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.vstream/vstream.db

Essayes de vider les cache de Vstream.
Plugin preference / outils , tout les caches en premier et BDD ensuite.

**Comment by moz-kito** [comment]
j'ai vidé les caches et les BDD, mais ce n'est pas mieux.
Quand je fais une recherche, j'ai bien les dossiers avec les jaquettes, mais ils sont toujours vides. :(

**Comment by TmpName** [comment]
Toujours les problemes en rapport avec les base de données ?

**Comment by moz-kito** [comment]
> Toujours les problemes en rapport avec les base de données ?

je ne saurais pas dire, j'y connais rien et je n'ai pas de messages d'erreur à l'écran, si ce n'est des fois "erreur connexion impossible ([Errno7)

**Comment by TmpName** [comment]
Tu as tjours les memes message d'erreurs que precedement dans tes logs ?
Tu as essayé un site au hasard pris dans "source" ?

**Comment by moz-kito** [comment]
je sais pas, c'est du chinois pour moi !

voici le log : https://slexy.org/view/s2AOFMhs3m

sinon, oui, j'ai essayé pleinde site au hasard dans source... ils sont tous vide.  :(

**Comment by johngf** [comment]
on dirait une erreur comme quand kodi n'est pas connecté a internet

**Comment by moz-kito** [comment]
je peux utiliser son lien pour installer une app sur mon Fire TV ? 

je ne sais pas comment on fait ça, je vais regarder.

**Comment by TmpName** [comment]
Ben ben deja y a plus les erreurs de BDD.
Par contre c'est quoi qui est vide ? uniquement les liens finaux (car la sur ianime tu es au moins arrivé jusque la) ?
N'utilises pas la recherche globale pour les logs, mais chosis une source (dans "sources") qui deconne chez toi, et tu as oublié d'activer les logs de vstream.

**Comment by moz-kito** [comment]
> Par contre c'est quoi qui est vide ? uniquement les liens finaux (car la sur ianime tu es au moins arrivé jusque la) ?

oui, je vois bien les dossiers des sources et des films/séries, mais il n'y a pas les liens vers les video et j'ai souvent cette erreur : "erreur connexion impossible ([Errno7)"

> N'utilises pas la recherche globale pour les logs, mais chosis une source (dans "sources") qui deconne chez toi, et tu as oublié d'activer les logs de vstream.

Ah bon, pourtant "activer les notices de log dans vstream/paramètres/outils est bien activé.

**Comment by johngf** [comment]
pour moi comme dit plus c'est probème de connexion internet avec kodi ou dns comme dit plus haut

**Comment by TmpName** [comment]
@johngf le probleme c'est que moi dans ces logs, je ne le vois pas lancer une seule video.
Dans ianime il arrive sur la page avec les liens, mais rien apres, meme pas de message d'erreur.

**Comment by moz-kito** [comment]
bon, impossible d'installer DNS Changer (j'arrive à lancer Aptoide, mais je ne peux pas cliquer sur le bouton Installation (il n'est pas accessible avec l'interface Fire TV) !

J'ai vu cette appli par contre 👍  Unblockr DNS https://www.amazon.fr/dp/B0817S25L5/ref=pe_386181_48772441_TE_M1DP 

est-ce que ça peut faire l'affaire ?

**Comment by TmpName** [comment]
Et a la main sans appli ? un truc comme ca https://www.pcastuces.com/pratique/astuces/4885.htm

**Comment by moz-kito** [comment]
je ne peux pas modifier le réseau. Je n'ai aucune options si ce n'est le vérifier ou le supprimer.

**Comment by jesusisback66** [comment]
@moz-kito  pour changer le dns sur fire stick il faut allé dans les parametre wifi  ensuite tu oublie tout tes wifi  au préalable tu attribue une ip fixe a ton fire stick via le dhcp de ta box , puis tu selectionne le SSID sur lequel tu veux te co ensuite tu renseignez le mot de passe et tu ne valide pas , tu vera la case " avancé " ce degrisé tu clique dessu et dans cette section tu peut changer les DNS directement sur la fire stick  ;)
