### ISSUE TITLE
Jetload bug

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2686]
**Décrivez le bug**
Les fichiers host Jetload ne fonctionne plus

**Votre system**
 - OS: [Windows, Android]
-  Appareil [S8+ , Z6+]
 - Version Kodi  [18 et 19]
- Version Vstream 0.7.46

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site strmserieshd
- Le titre du fim/serie carnival row
- Le nom du host (Jetload)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
a3ea7c35728e87b78d382738652fe41b3bb420c1
