### ISSUE TITLE
Wiflix

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#2687]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android] Android
-  Appareil [nvidia shield, Ultra] Box Beelink
 - Version Kodi  [16.17.18] 18.5
- Version Vstream  Vstream Beta

Wiflix n'apparait plus dans la liste des hosters dispo.
Il est apparu une seule fois il y a 3 jours.

Bien à vous

Bon week-end

**Comment by johngf** [comment]
wiflix n'est pas un hoster mais un site si tu utilise la béta normalement tu l'as regarde dans sources en bas

**Comment by Papounet58** [comment]
Merci

**Comment by Papounet58** [comment]
Dans la béta j'ai beau parcourir l'ensemble des sources, Wiflix n'y figure plus.

**Comment by johngf** [comment]
bah c'est que tu n'a plus la béta si tu fait une maj la béta disparait normalement il faut la ré installer

**Comment by Papounet58** [comment]
Doit-on lorsque l'on utilise la béta désactiver les mises à jour automatiques ?

**Comment by TmpName** [comment]
Bonne question, je ne pense pas si on a installé la BETA apres la maj. Car sinon on pourrait pas modifier les fichiers.

**Comment by Papounet58** [comment]
Merci
