### ISSUE TITLE
Kaydo

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2688]
Bonjour!

Lorsque je navigue par genre, dans Kaydo, il y a certaines sections qui ne comportent aucun lien. Par exemple, sous « Horreur » la section est vide... Par contre, sur le site, la section se présente plutôt sous le nom « Horror » et non « Horreur »... Est-ce que c’est possible que ça en soit la cause?

**Comment by KodiTopQuebec** [comment]
va voir directement sur le site internet pour voir si ça fonctionne

**Comment by alKODIque** [comment]
Oui comme je l’ai dit dans mon message, c’est exactement ce que j’ai fait

**Comment by TmpName** [comment]
Il faut comparer les liens et corriger.
Pour info celui pr les film d'horreur est hdss.to/horeur/ :) je sais pas si les fautes sont volontaires
Alors que nous le lien qu'on utilise est https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/kaydo_ws.py#L148

**Comment by alKODIque** [comment]
Haaa d’accord ...
je comprends mieux comment le code de vStream fonctionne pour aller chercher l’information des sites maintenant 

Merci de ta réponse @TmpName  :))

**Comment by alKODIque** [comment]
J’ai apporter des changements au fichier que tu as mentionné et voilà! J’obtiens maintenant des résultats

**Comment by TmpName** [comment]
Y a eu un petit loupage sur ta modif ^^. Tu fais 43 modifs au lieu d'une.

**Comment by alKODIque** [comment]
Ayayaye...
Je sais pas ce qui s’est passé c’est étrange...
J’ai dû louper quelque chose
