### ISSUE TITLE
Catégorie Collection

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2690]
Bonjour!

Bien que le sujet de l’heure soit à trouver une solution pour corriger les problèmes de liens dans vStream, j’aimerais avoir de l’aide pour être capable d’afficher la catégorie ‘collections’ que l’on retrouve maintenant sur le site ZT lol...

Jusqu’ici, j’ai été capable de faire afficher la section dans vStream mais aucun contenu ne s’affiche... voici le fichier site où j’ai ajouté les lignes... Y-a-t’il quelqu’un qui peut me dire où j’ai merdé et comment je peux corriger?
 Voir ligne 28 et lignes 114 à 116)

Grand merci à l,avance, je sais que vous devez être fort occupé 

https://pastebin.com/5ffrWtPY

**Comment by johngf** [comment]
d'abord un peu de lecture http://www.vstream.ml/docs/add/

**Comment by alKODIque** [comment]
Merci..
Je relis et j’essaierai encore...
Essaie-erreur = meilleure moyen d’apprentissage hihi :))

**Comment by johngf** [comment]
exemple https://regex101.com/r/1xWmj6/1

**Comment by johngf** [comment]
ça a l'air compliqué au début mais en faite une fois que ta pigé comment ça fonctionne c'est un jeux d'enfants

**Comment by alKODIque** [comment]
Haa merci beaucoup pour le lien et l’exemple, j’apprécie vraiment :))

Je m’y mets dès demain! (2h du matin ici au Canada ) 
Merci encore!!
