### ISSUE TITLE
Bug de recherche

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#2691]
Bonjour a tous
J ai un petit souci avec la recherche de vstream, (kodi 18.5 et même les anciennes versions)
Lorsque je lance une recherche, les résultats s affichent bien , je clique sur l un des résultats obtenus il s affiche bien aussi, mais lorsque je reviens en arrière vers la page de résultats, vstream relance la recherche de nouveau et c'est très énervant car ça prend du temps !!!!
J ai effacé le cache de kodi, mais ça n a rien résolu. 

Qq1 d autre a eu ce problème.?
Merci de votre aide

**Comment by TmpName** [comment]
Bon impossible de retrouver l'issue.
La seulle que j'ai retrouve c'est https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2248

Regardes dans tes logs si tu vois pas un probleme de permissions.

**Comment by johngf** [comment]
il faut pas vidé tout le temps le cache et quand on le fait depuis kodi 17xx il faut rédemarrer kodi

**Comment by falciatrice10** [comment]
Bonjour
J ai essayé de désinstaller vstream , sans résultat.
Pour le cache, j utilise un addon et je ke fais aussi via le menu informations de l appli.
Sinon, ou je peux trouver le fichier log ?

Merci

**Comment by TmpName** [comment]
Pour les logs https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outils
Sinon, ca te fait ca sur d'autres addons ou pas ? (meme si le chargement est plus rapide, normallement il ne devrait pas y en avoir quand tu fais retour arriere)

**Comment by lefou66** [comment]
jai déja eu ce problème mais la seule solution que javais trouvé et de tout désinstaller kodi et meme je crois que javais réinitialisé ma boite android

**Comment by DaX59** [comment]
Salut, 
On dirait que c'est l'erreur de recherche que j'avais remonté y'a un moment qui revient. 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2643
À l'époque ça impactait que les sites protégés par Cloudflare et on dirait que c'est toujours le cas.

**Comment by TmpName** [comment]
Nope c'est pas un probleme de recherche, c'est juste que ca relance la recherche au lieu d'utiliser la page deja chargée qui devrait normalement etre en cache.

**Comment by Leefax** [comment]
Hello à tous,

Même problème depuis l'avant dernière maj. Je vais tester supprimant des sources.
Cache vidé régulièrement  à défaut de faire un wipe global.
La maj 0.7.5 n'a pas réglé le problème.

Bonne soirée.

**Comment by johngf** [comment]
normalement c'est ça je l'ai remis commen avant 63517237e87d6f471b8f16d55c160c7db5aea2bd

**Comment by Leefax** [comment]
Bonne nouvelle merci.
Dispo dans la prochaine MAJ (?) car je ne peux pas faire la modif manuellement - Box non rootée.

**Comment by TmpName** [comment]
Le soucis c'est que la MAJ date juste de 2 jours.
Y a vraiment pas moyen d'editer un fichier avec un editeur de texte ?

**Comment by Leefax** [comment]
Non, sinon je l'aurai fait sans hésiter. J'ai essayé mais sans éditeur de texte compatible Android TV.
J'ai essayé 45 min là, j'ai dû réinstaller vstream qui ne voulait plus se lancer.
Tant pis ,merci pour vos efforts.

**Comment by Leefax** [comment]
Bonjour à tous,
Je viens d'appliquer le correctif et le problème persiste :/  Downgrade en 0.7.4 pareil.
Du coup je n'utilise plus cet excellent addon.
J'aimerai savoir une chose : on est seulement une poignée à avoir ce problème ou ça touche tout le monde ?
Simplement pour savoir si j'attends une solution ou je fais un factory reset en dernier recours car ça ne m'arrange absolument pas.

Grand merci.

**Comment by TmpName** [comment]
Ben attend d'avoir plus de retour, mais en general ce bug ne vient pas du code de Vstream, mais de la config de la machine, et donc c'est assez rare.

**Comment by motokoghost** [comment]
Bonjour ! Alors je viens de faire une fresh install de mon raspberry pi 3 avec la distrib Librelec et même bug de recherche. J'avoue que c'est galère...

**Comment by Leefax** [comment]
Hello,
Merci pour ton retour, je me sens moins seul :)
J'ai écouté @TmpName et j’ai bien fait apparemment !
Affaire à suivre donc .

**Comment by TmpName** [comment]
@Leefax tu es aussi sous librelec ?

Vous n'avez pas installé de plugin "d'amelioration de kodi" du style indigo ?

**Comment by Leefax** [comment]
Ma config : Mibox 3 / Android 8.0 / Kodi 18.5
PLug in : Merlin wizard et TTbuffer Fix : pas de souci jusqu'à maintenant, le dernier est désactivé

**Comment by Leefax** [comment]
Hello à tous,

Un bon format data des familles avec une resinstall propre : problème réglé !
Par contre, au vue de ce que j'ai vu sur la toile et le souci de @motokoghost , je suis resté sur Leia 18.0.
Tout est rentré dans l'ordre et ça fait plaisir ;) J'ai juste perdu le SMB, me souviens plus de la manip que j'avais faite sur Kodi.

**Comment by TmpName** [comment]
Super Mario Bros ?

**Comment by Leefax** [comment]
Voilà c'est ça ^^
Il m'a fait la maj tout seul en 18.5 mais tout est ok ( ouf ) et le SMB aussi.
Au top.
