### ISSUE TITLE
Code Erreur 503 erreur décryptage du lien

### ISSUE THREAD

**Issue by Mobius69** [Kodi-vStream/venom-xbmc-addons#2695]
Bonjour, 
Suite à la mise à  jour 0.7.51 j'étais ravi de pouvoir revoir mes films et séries sur zone telechargement( sur kodi18.5 sur android tv vstream), mais voilà depuis hier après-midi à mon grand désarroi l'erreur de décryptage du lien (503) refait surface. Suis-je le seul dans ce cas? D'où pourrait provenir le problème? 
Par avance un grand merci aux réponses qui pourront être apportées.

**Comment by johngf** [comment]
issue déjà ouverte #2694

**Comment by Mobius69** [comment]
Celle ouverte est une erreur 513 moi c'est une 503. A code erreur différent j'ai préféré ouvrir un nouveau sujet

**Comment by johngf** [comment]
c'est la meme cause, meme si pas le meme code

**Comment by TmpName** [comment]
Le bug 503 serait pas celui la ? Bug reservé a android.

**Comment by Mobius69** [comment]
Ok John 👍
TmpName mon problème n'est pas lié au DNS, je l'avais déjà changé.
J'espère une prochaine mise à jour qui mettra terme à ce problème.
En tout cas merci d'avoir pris le temps de me répondre messieurs 🤙🤙🤙

**Comment by TmpName** [comment]
@Mobius69 le bug de mon precedent post ne concerne pas les dns mais cloudflare+android.

**Comment by Mobius69** [comment]
Au temps pour moi!

**Comment by Mobius69** [comment]
Mais la mise à four 0.7.51 avait semblé fixer le problème, malheureusement c'était temporaire.

**Comment by Mobius69** [comment]
En tout cas je tenais à vous remercier pour la qualité de l'extension vous faites un boulot extraordinaire

**Comment by TmpName** [comment]
Non Bug toujours present. Il disparait car cloudflare n'est pas activé tout le temps, mais aucune correction encore.

**Comment by johngf** [comment]
j'ai un doute avec ça from urllib.parse import urlparse

**Comment by TmpName** [comment]
Le truc c'est qu'il n y a jamais d'erreur python dans les logs. C'est le serveur qui bloque avec erreur 403.
Et je reste persuadé que ca concerne le SSL.

**Comment by Mobius69** [comment]
Pour palier au problème en attendant je vais sur zt avec mon téléphone ou mon ordi, une fois passé le cloufare et zt protection je recopie le lien, je vais sur tools, hoster direct et j'y écris le lien et ça fonctionne.
