### ISSUE TITLE
Vstream ZT

### ISSUE THREAD

**Issue by adsav1** [Kodi-vStream/venom-xbmc-addons#2696]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: , Android
 - Version Kodi  18
- Version Vstream

**Nous devons le reproduire**
- Le nom du site : ZT
- Le titre du fim/serie : tous
- Le nom du host : jetload

Tous les fichiers présents avec cet hebergeur retourne une erreur Fichier introuvable.

**Comment by TmpName** [comment]
Y a des liens jetload sur ZT ?

**Comment by adsav1** [comment]
Pas sur ZT mais avec l'hebergeur Gounlimited 
Je me suis trompé

**Comment by johngf** [comment]
@adsav1 il faut mettre du votre aussi, vérifie sur le site ou les sites dans le cas présent avant de venir ouvrir une issue.
- tu aurais vu que l'hébergeur jet load est hs et son site internet aussi a l'heure ou j'écris.

**Comment by lebigboss** [comment]
J'ai jamais vue de liens jetload sur ZT, j'utilise cette source tous les jours

**Comment by adsav1** [comment]
La source ZT ne fonctionne plus sur Vstream

**Comment by TmpName** [comment]
C'est pas l'adresse du fake ca ?

**Comment by adsav1** [comment]
sinon ya aussi https://www1.zone-telechargements.net/

**Comment by Makoto83** [comment]
La source n'est pas morte https://www.zone-telechargement.net/ marche très bien !!!!

**Comment by yas06** [comment]
> 
> 
> La source n'est pas morte https://www.zone-telechargement.net/ marche très bien !!!!

salut le lien que tu donnes ne fonctionne pas voila les 2 adresse du vrai zt
https://ww8.annuaire-telechargement.cc/
https://www1.zone-telechargements.net/
est ce n’est pas la source qui est hs mais le décryptage du lien des host vu qu on arrive jusqua la page ou tu vois les host mais pas les liens (upt-nitro-1fi-rapidg)

**Comment by Makoto83** [comment]
Merci @yas06 je ne dit pas que ça marche sur vstream mais que la vrai source 
n'est pas morte et soit dit en passant le seul et unique ZT c'est celui que j'ai donnée plus haut !

**Comment by Arias800** [comment]
Normalement j'ai corriger dl protect donc zt devrai remarcher ^^

**Comment by yas06** [comment]
salut  Makoto83 merci a toi.
Arias800 merci beaucoup j ai tester ta maj je te confirme ça marche impec
merci a vous est passer de bonne fête les amis

**Comment by lebigboss** [comment]
Il faut que tu m'apprennes comment tu @Arias800 , tu va me dire que un magicien révèle jamais ses secrets, mais merci

**Comment by adsav1** [comment]
Arias800 ne fonctionne toujours pas chez moi

**Comment by Arias800** [comment]
Hum bizarre ca fonctionne chez moi. Tu peut me donner un exemple qui ne fonctionne pas chez toi ?

**Comment by adsav1** [comment]
Toute la source ZT ne fonctionne pas ainsi que les fichiers hébergés chez jetload

**Comment by Arias800** [comment]
Ah oui mais tu est sur Android donc c'est l'erreur 503 mais je peut rien n'y faire pour ca xD

**Comment by jesusisback66** [comment]
@Arias800 chez moi kodi 17.6 sheild zt j'ai tout les liens mais ils ne se lance pas

**Comment by TmpName** [comment]
Donnes un log.

**Comment by jesusisback66** [comment]
@TmpName  log ici : https://slexy.org/view/s21Vn5ncmM

**Comment by Stam06** [comment]
Bonjour les amis,
J'ai le même problème signalé plus haut. J'utilise kodi 18.5, sur la mi box. Comment vous fournier le fichier log svp? Désolé, mais je ne suis pas du tout connaisseur. Ça serait bien que vous me l'expliquiez une fois pour toutes et la prochaine fois, le fichier dira mieux les choses. 
En plus de l'erreur mentionnée, il y a d'autres aussi. Exemple, dès que je lance kodi, j'ai un message qui me dit «erreur de communication à distance» (impossible d'afficher). 
Lorsque je fais une recherche, plusieurs erreurs apparaissent. Exemple d'erreur numéro 7.
Zone téléchargement ne s'ouvre même pas et j'ai un message «erreur 7». Rien n'apparaît à l'intérieur.
Merci de votre aide, merci pour le travail que vous faîtes. Bonnes fêtes de fin d'année.

**Comment by TmpName** [comment]
@jesusisback66 
>16:50:58.417 T:180674258160   ERROR: UnboundLocalError: local variable 'token' referenced before assignment

Tu as un probleme avec le regex de la ligne 870, je regarde si je peux faire quelque chose.

@Stam06 ZT ne marche plus sur android.

**Comment by TmpName** [comment]
Bon correction faite pour ZT, mais ne marchera pas sur android a cause de CF.
Et deconne a cause de CF sur les autres machines aussi pour le moment, le cookie ne marche pas, obligé d'en refaire un a chaque fois.

**Comment by ludopotte** [comment]
Je confirme que ZT et Tirezo ne fonctionne pas sous Android et PC, donc moi j'ai supprimé les Fichiers de ses 2 Sources dans mon Patch vStream. En attendant la résolution du problème, il y a d'autres sources qui marchent.

**Comment by Stam06** [comment]
Tirexo aussi est dead! ça ne marche pas; rien d'affiché.
Chez moi, peu de chose marche, en ce moment. C'est quoi CF, svp? Vous pensez que ça sera réglé pour ZT et  Tirexo, sur Android ou bien c'est mort?

**Comment by jesusisback66** [comment]
@TmpName  voici un log tout frais avec ta correction : https://slexy.org/view/s20s01oika
