### ISSUE TITLE
Bug hos mixdrop /jetload

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2697]
**Décrivez le bug**
2 hosts ne fonctionnent pas: l'un ne lance pas la vidéo (jetload pour la source Seriestrmnghd )et l'autre il y a que le dossier host mais pas le lien host (mixdrop pour ma source dpstrm.cx)

**Votre system**
 - OS: [Android 8]
-  Appareil [vorkez6]
 - Version Kodi  [18]
- Version Vstream (0.7.51)

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by johngf** [comment]
#2696

**Comment by Arias800** [comment]
Jetload utilise recaptcha donc le seul moyens de l'utiliser avec Vstream c'est d'autoriser l'appareil via jlpair.net .

**Comment by johngf** [comment]
@Arias800 tu as regardé ça [ici](https://github.com/nickolas360/librecaptcha/tree/master/librecaptcha)
apparemment il y aurait moyen de le modif pour kodi remplacer le gui par un dialog ou récup le token

**Comment by Arias800** [comment]
J'arrive même pas exécuter le code vu qu'il utilise des lib qui sont tres peut maintenu a jour xD

**Comment by johngf** [comment]
j'y arrive mais il y a un bug

**Comment by johngf** [comment]
bon j'arrive a le lancé jai le captcha mais ça fonctionne pas encore

**Comment by johngf** [comment]
bon ça fonctionne ^^

**Comment by TmpName** [comment]
C'est quoi ca ?
Comment ca affiche des images ?
J'arrive pas a trouver le moteur JS, slimit serait juste une lib qui compacterait le code.

**Comment by johngf** [comment]
c'est pour recaptcha

**Comment by Arias800** [comment]
Je comprends pas pourquoi ca ne marche pas chez moi mais tant mieux si ca  fonctionne xD

**Comment by johngf** [comment]
nan mais j'ai galérer a le faire fonctioner

**Comment by TmpName** [comment]
Ben les images c'est pas dur a afficher dans kodi, mais j'arrive pas a trouver le moteur JS.
En tout cas ca a vraiment l'air d'etre une tuerie ce truc.

**Comment by johngf** [comment]
c'est comme jsnice c'est pour raccourcir le code

**Comment by TmpName** [comment]
Ben j'ai l'impression que c'est cette lib qui "fait la magie". Ca raccourcis le code mais ca compile aussi
Regardes le fichier extract_strings.py.
Par contre c'est une grosse lib, et on va devoir la rajouter dans Vstream pour s'en servir ou en dependance ca pourrait marcher ?

**Comment by johngf** [comment]
je pense qu'on peut la réduire grandement il y a bcp de truc qui serviront pas sur kodi mais reste déjà a l'adapté

**Comment by TmpName** [comment]
Je parlais pas de la lib recaptcha, mais de slimit, c'est elle qui me fait peur, suis quasiment sur que c'est elle la lib la plus importante.

**Comment by johngf** [comment]
bah non je l'utilise pas la et ça fonctionne

**Comment by TmpName** [comment]
Ha bon ?
lol, bon c'est une tres bonne nouvelle alors ^^, je vois pas e qui pourrait bloquer pour l'integration kodi.

Mais je vois pas comment ca peut marcher sans. Tu pourrais mettre ton code sur ton github ?

**Comment by johngf** [comment]
bah slimit reduit le js  mais j'ai pas fait grand chose pour le moment j'ai désactive une partie c'est tout et au niveau de add_strings je l'ai remplacer list(javascript)

**Comment by Arias800** [comment]
Bon j'ai enfin réussit a faire marcher cette lib par contre j'ai jamais reussit a valider aucun des tokens générer par la lib xD

**Comment by johngf** [comment]
façon il y a plein de truc a faire le dilog de la lib re captcha qu'on a ne fonctionne pas avec python 3
tu clique mais ok et cancel nefonctionne pas et sans doute d'autre chose ya un taff énorme

**Comment by johngf** [comment]
bon en faite maintenant il faut action.getId()

**Comment by johngf** [comment]
@Arias800 tu sais comment faire avec xbmcguiwindoxdialog pour chargé une autre image a la place de la premiere ?
il doit avoir un soucis de cache il reload la meme alors que l'image a changé

**Comment by Arias800** [comment]
Je sais pas du tout, peut être que cette réponse peut t'aider :

> You need to run a secondary thread from which you can update your Controls with new data.  (source : https://forum.kodi.tv/showthread.php?tid=322357)

**Comment by johngf** [comment]
bah comment ça fonctionné avant ? il me semble que si le capatcha été refusé t'en avait un autre non

**Comment by Arias800** [comment]
Je faisait qu'avec un seul captcha et de toute manière le code n'a pas fonctionner longtemps donc je n'ai jamais pris le temps pour améliorer le système xD

**Comment by johngf** [comment]
ah en test offline avec 2 image differente a cause de do modal mon avis l'image change que si tu clic sur ok pour l'instant

**Comment by johngf** [comment]
sinon ça avance bien bientot il y aura un code a test

**Comment by Che-debarras** [comment]
Bonsoir  juste pour signaler que mixdrop et jetload ne fonctionne plus depuis la maj dernier.

Merci

**Comment by TmpName** [comment]
Pour jetload, c'est mort pour le moment > recaptcha, pour nmixdrop j'ai pas trouvé d'exemple, tu en aurais un ?

**Comment by johngf** [comment]
jet load normalement c'est possible mais il faut modif le code et ce pairer au site pour 3h sur jlpair.net

**Comment by TmpName** [comment]
Ha yep je viens de tester.

**Comment by johngf** [comment]
@Che-debarras mix drop , jet load mis a jour pas vu re captcha sur mix 
 - pour utiliser jet tu dois te pairer au site [ici](https://jlpair.net/) tous les 3h

**Comment by TmpName** [comment]
Ha, pas de captcha ?
J'etais bourré ou ca change selon l'alignement des planetes ?

Sinon ca m'interesse votre code recaptcha, y a une version qu'on peut tester ? Mettez ca sur un de vos github, a mon avis ca va faire un carton vu la mode actuelle.

**Comment by johngf** [comment]
j'ai presque fini une version test ( bcp de taff ) par contre c'est python 3 obligatoire
j'ai déja galérer pour le reverse engineering et je pige pas tout encore mais je sais que certaine fonction ne fonctionne pas en python 2 faudrait refaire plein de truc

**Comment by TmpName** [comment]
Du coup c'est pas integrable dans le kodi actuel ? ou alors faut convertir les fonctions ?

**Comment by johngf** [comment]
j'étais sur autre chose  mais version python 3 ok  en plugin je posterai après quelque nouveau test je vais voir pour python 2
