### ISSUE TITLE
plus de Liens sur ZT et Tirexo

### ISSUE THREAD

**Issue by dbast57** [Kodi-vStream/venom-xbmc-addons#2698]
Bonjour, plus de liens sur ZT et Tirexo

**Votre system :**

OS: Android 9.0 et Windows
Appareil : nvdia shield et pc
Kodi (17.6). 
Version Vstream 0.7.5

**Nous devons le reproduire**

Impossible de lancer un lien sur ZT et aucun lien de disponible sur ZT

**Comment by TmpName** [comment]
Salut,
Cf https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2679#issuecomment-568881946
