### ISSUE TITLE
Vstream intégré à un autre addon

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2699]
Quelqu'un avait remarqué que vStream avait été "intégré" à un autre addon?????

**Comment by johngf** [comment]
lequel ?

**Comment by razorex** [comment]
loganaddon

**Comment by TmpName** [comment]
Tant que ca reste "Vstream" ...
J'arrive pas a comprendre les gens qui pour installer une appli vont sur telecharger.com au lieu du site officiel de l'application ....
