### ISSUE TITLE
Mise à jour bêta 

### ISSUE THREAD

**Issue by rod93** [Kodi-vStream/venom-xbmc-addons#2700]
Bonjour est il possible d’avoir en option les mises à jour en bêta directement depuis le addon Android merci

**Comment by Che-debarras** [comment]
Je comptais aussi le demander car ça évite de télécharger manuellement et aussi ca évite les mise a jour de la version master qui rétrograde la version bêta 

L'addon catchTV à  2 repos une beta et une master donc si yavais 2 repos vstream une pour beta et une pour master ce serait cool

**Comment by sizanic** [comment]
J'ai essayé en utilisant GitBrowser, mais ça ne le permet pas, il ne propose que des ZIP.
(installation de GitBrowser : https://www.tvaddons.co/git-browser/ )

![image](https://user-images.githubusercontent.com/47307622/71564473-2362cc00-2aa1-11ea-892d-3ea40b0fab4d.png)

(On notera que d'anciennes versions sont disponibles sur d'autre REPO)

=> Mais il existe peut-être un moyen rapide de générer ce ZIP de la BETA et de la mettre sur GITHUB.

**Comment by TmpName** [comment]
Ben le truc c'est que la version beta, et la pour tests. Ce n'est pas une version pour avoir les derniers fichiers en date.
Imagines notre reaction quand on essaye de reparer le code d'une source, qu'on est 3 / 4 a modifier le code a tout de role, et que a chaque modification tu vois comme issue "j'ai telecharger la beta, mit le dernier code et ca marche pas".
Normallement tant qu'il n'est pas en MAJ, il n'est pas sensé fonctionner.

**Comment by sizanic** [comment]
On comprend très bien qu'une Beta n'est pas stable, et c'est bien dans l'idée d'aider les développements qu'on veut pouvoir l'installer facilement (mais pas trop facilement pour pas faciliter l'accès à ceux qui comprennent pas ce qu'est une beta).

**Comment by johngf** [comment]
moi je vois surtout des gens qui veulent la béta pour avoir les mise a jours tout de suite quand z_t est hs  ou ex_d sans ce faire chier, mais personne ne participe vraiment a pars nous dire ça fonctionne pas ...
vu que beaucoup ne savent même pas comment on remplace un fichier sur android, ou faire un copier coller, ou trouvé le fichier log de kodi.
- bonne année

**Comment by lebigboss** [comment]
La ta pas tort. Si les gens sont pas capable d'aller sur le github pour récupérer une bêta alors pour parler des problèmes.
Non moi j'aimerais plus voir un forum pour pouvoir discuter plus simplement de problème.
Heureusement qu'il y a discord, dommage il y a pas d'onglet bêta.

**Comment by TmpName** [comment]
Désolé pour le hors sujet, je profite de l'issue ^^.

Meilleurs voeux tout le monde .

Sinon pour rajouter une couche au post de @johngf, la beta etant la pour le dev, vu que cela necessite quand meme quelques bases, la personne s'en servant devrait etre capable de l'installer toute seule. Normallement on ne devrait meme pas expliquer comment l'installer, ce n'est pas destiné a l'utilisateur standard.

**Comment by ludopotte** [comment]
Voici 3 Méthodes pour installer vStream et son Patch si-dessous :
Méthode 1 : Installez l'Extension au https://github.com/ludopotte/vStream  
ou directement depuis Kodi avec Github Browser au https://www.youtube.com/watch?v=qJvm4DHmJmo
et ensuite allez dans "Search by GitHub Username" et tapez "ludopotte".
Méthode 2 : Installez le Fichier Zip de mon Patch sans désinstaller vStream 
au https://github.com/ludopotte/vStream/releases/
Méthode 4 : Téléchargez la Version Beta au https://github.com/Kodi-vStream/venom-xbmc-addons 
en cliquant sur le Bouton "Clone or download" et appuyez sur le Bouton "Download Zip".
Ensuite ouvrez le fichier et compressez le Dossier "plugin.video.vstream" avec Winzip 
et renommez le en "patch.vstream". Apres installez ce Fichier manuellement sur Kodi 
à l'aide d'une clé USB, d'une Carte SD ou d'une Carte Micro SD.

**Comment by sizanic** [comment]
Est-ce qu'il s'agit de la branche BETA, ou d'un ZIP du dernier patch de la branche MASTER ?

**Comment by ludopotte** [comment]
Il s'agit du fichier de la Branche BETA. Le Patch vStream est fait par moi qui est extrait de la Beta que je mets en fichier Zip.

**Comment by sizanic** [comment]
super, et la méthode GIT Browser est celle que j'expliquais, mais il ne me manquait que le ZIP de la beta.
=> C'est ce que tu mets à disposition !

Et tu as l'air de bien mettre à jour tes ZIP pour chaque version BETA de Vstream.
Dommage que tu ne suives pas les mêmes numéros de version.

Ici, rien ne nous indique qu'il s'agit de la 0.7.52 :

![image](https://user-images.githubusercontent.com/47307622/71644401-078d3f00-2cc8-11ea-91f0-8ab4ad34d620.png)

Par contre, je rejoins en partie l'avis des autres développeurs, tu facilites peut-être trop l'accès à la BETA, on va se retrouver avec trop de faux Beta-testeur :))

Je ne sais pas si on doit vraiment te remercier pour ce travail.   :D  :D

**Comment by ludopotte** [comment]
Mon Patch s'installe par dessus la Version 0.7.52. Je mets souvent à jour mon Patch et maintenant le nom a changer en patch.vstream-0.7.52.1

**Comment by rod93** [comment]
Salut merci beaucoup pour ton patch (même si je n’ai pas réussi à l’installer)
En fait cela est utile sur les Box qui ne sont pas rootee car on n’a pas accès au fichier root afin de modifier les fichiers

**Comment by sizanic** [comment]
Pas besoin d'être rooté, il faut juste faire apparaître les fichiers cachés.
L'application X-plore est bien pour ça.
