### ISSUE TITLE
Taille police

### ISSUE THREAD

**Issue by fredo04** [Kodi-vStream/venom-xbmc-addons#2703]
Bonjour a tous.
Contant que le boulot de lordvenom soit repris car vstream est limite indispensable pour moi .
Je suis sous box Android avec spmc et skin aeon nox, est il possible d'augmenter la taille de la police des résumés ?

**Comment by johngf** [comment]
de quel résumé tu parle 
 - ceux avec les métas activé ? > dans ce cas oui mais pas facilement
 - ou les autres sans les métas. > dans ce cas c'est la police du skin qu'il faut augmenté dans les paramètres de kodi.

**Comment by fredo04** [comment]
Ceux avec les métas activées.
J'active toujours les métas comme ça j'ai plus d'info et les fanar.

**Comment by johngf** [comment]
donc en faite il faut que la valeur que tu vas utilisé soit dispo dans le font.xml de ton theme.
on peut pas mettre n'importe quoi.
 - donc example sur windows avec confluence AppData\Roaming\Kodi\addons\skin.confluence\720p font.xml dedans tu as plein de taille dispo	comme:
`<name>font24_title</name>` # >>>>>>>> on a besoin de ça font24_title
 `<filename>Roboto-Bold.ttf</filename>`
`<size>24</size>`
`<name>font10_title</name>`
`<filename>Roboto-Bold.ttf</filename>`
`<size>12</size>`

 - ensuite dans le dossier AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\skins\default\720p fichier  >> **DialogInfo2.xml**
  ligne 237 tu change font12_title par la taille que tu as récup au dessus

**Comment by fredo04** [comment]
Je viens de faire un essai et rien n'a changé avec le skin aeon nox silvio

**Comment by fredo04** [comment]
Je viens de faire un essai avec le skin aeon nox silvio et rien n'a changé
![Screenshot_20200101_131054_org xbmc kodi](https://user-images.githubusercontent.com/11046698/71641259-08f34300-2c99-11ea-8ddf-788905945b48.jpg)

**Comment by johngf** [comment]
autant pour moi je me suis gouré je pensais que tu parlé du dialog info sur clique droit

**Comment by johngf** [comment]
bah on peut pas ça depend du skin il faut modifier le skin

**Comment by johngf** [comment]
si ça peut aider sur confluence le fichier ce nomme ViewsVideoLibrary.xml pour changer ce dialog

**Comment by fredo04** [comment]
Ok merci je regarde ça

**Comment by lelooser** [comment]
Vous faite comment pour activer les informations (méta).
J'ai rien avec ZT -> non disponible
![Screenshot_2020-01-02-11-00-05-866_org xbmc kodi](https://user-images.githubusercontent.com/57831629/71661759-88434e00-2d4f-11ea-9ead-3852baa8e336.jpg)
J'ai essayé de créer un compte tmbd dans Mes Comptes mais Ça ne fonctionne pas.
Je suis obligé de cliquer droit puis faire informations. c'est plus long.

**Comment by johngf** [comment]
@lelooser dans les parametres de vstream activé les métas ou pas

**Comment by lelooser** [comment]
merci @johngf  ça fonctionne nickel.
zt refonctionne depuis ce weekend dernier sur Android

**Comment by fredo04** [comment]
Bon j'ai fait des essais avec confluence pour voir ce que ça donné et rien ne change. Idem avec le skin aeon nox silvio

**Comment by johngf** [comment]
t'as du de trompé quelque part soit le nom du font ou tu as pas redémarrer kodi ou autre
si j'ai réussi tu dois y arriver normalement

**Comment by johngf** [comment]
tu as réussi ?

**Comment by fredo04** [comment]
Je m'y suis pas remi, pas mal occupé ces derniers jours.
Je vais essayer de voir ce weekend.
