### ISSUE TITLE
Pré-Intégrer Vstream dans kodi

### ISSUE THREAD

**Issue by shmox75** [Kodi-vStream/venom-xbmc-addons#2704]
Bonjour à tous, je ne sais pas si c'est toléré mais j'ai essayé d'intégrer vstream dans l'apk kodi en utilisant apktool. J'ai donc copié le contenu de .kodi de ma box android avec le user data ettout et j'ai recompilé l'apk kodi, le plugin se trouve bien dans kodi mais il n'y a pas de sources (sites) il me propose d'abord de faire la mise à jour et une fois faite ça marche normalement.  Si quelqu'un peut m'aider ça serait bien car je veux avoir vstream préinstallé dans kodi pour donner à mon frère qui ne sait pas trop comment installer les plugins kodi, comme ça ça serait plus facile d'installer l'apk kodi avec vstream fonctionnel :)

**Comment by TmpName** [comment]
J'ai aucune idée du fonctionnement d'android, mais les fichiers sites sont dans le plugin, donc je vois pas comment tu pourrais avoir le plugin fonctionnel mais sans aucun sites ...

**Comment by shmox75** [comment]
> J'ai aucune idée du fonctionnement d'android, mais les fichiers sites sont dans le plugin, donc je vois pas comment tu pourrais avoir le plugin fonctionnel mais sans aucun sites ...

Par fonctionnel je veux dire que il est préinstallé mais les sources ne sont pas là qu'après mise à jour proposé par vstream et celà même si j'ai mis les sources disponnibles dans le plugin.

Sinon oui il n'est pas fonctionnel avant la mise à jour. Il ne manque que les sources par exemple quand je cliques sur dernier ajout etc c'est vide bien que je l'ai ai mis dans l'apk kodi  :(
