### ISSUE TITLE
Prise en charge ResolveURL

### ISSUE THREAD

**Issue by mike855** [Kodi-vStream/venom-xbmc-addons#2705]
Hello!

Vstream supporte URLResolver, ce qui est super pour les gens qui ont un débrideur.
Par contre, il ne supporte pas ResolveURL, qui est sa suite. URLResolver n'est plus mis à jour depuis un moment.

Vous pensez que l'intégration est possible? Son code est vraiment quasi le même, c'est juste un fork

**Comment by johngf** [comment]
[il y a 4 jours](https://github.com/tvaddonsco/script.module.urlresolver)
