### ISSUE TITLE
Changement de box android 

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#2706]
Salut à tous,

Je vais commencer par féliciter toute votre équipe pour le boulot génial que vous faites, sans vous ma box n'aurait jamais été aussi intéressante.
Je viens vers vous car justement je vais recevoir ma nouvelle box d'ici ce week-end et en ce moment ma version de Kodi/Vstream marche du feu de dieu ce qui m'amène à la question suivante: Il y a t'il un moyen de copier l'intégralité de ma config Kodi/Vstream pour la recoller à l'identique sur mon nouveau joujou ?
Actuellement je suis sur une box android MXQ Pro 1Go et Android 7.1 et je passe sur une X96MAX 4Go et Android 9.0.

Merci d'avance pour vos réponses.

**Comment by TmpName** [comment]
Honnetement je dirais oui, mais deja que c'est compliqué de trouver tout les fichiers sur windows, j'imagine meme pas sur android, surtout que si ca se trouve les repertoires chnagent de la version 7.1 a 9.0

Sinon il y a une extension officielle de backup, qui te prermet de faire ca, franchement si tu n'es pas habitué a android c'est la solution que je te conseille.
