### ISSUE TITLE
Bug Mxdrop & jetload

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2709]
**Décrivez le bug**
2 hosts ne fonctionnent pas: l'un ne lance pas la vidéo (jetload pour la source Seriestrmnghd )et l'autre il y a que le dossier host mais pas le lien host (mixdrop pour ma source dpstrm.cx)

dont la vérification sur le website confirme bien un lien fonctionnel pour le visionnage sur ces 2 hosts et les 2 sources mais pas avec vstream

**Votre system**
 - OS: [Android 9 et Windows10]
-  Appareil [S8 plus, PC ]
 - Version Kodi  [18 ET 19]
- Version Vstream 0.7.53

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site Srstrmhd et dpstrm
- Le titre du fim/serie Chicago Med et young sheldon
- Le nom du host (openload/vidzi) jetload et mxdrop

**Comment by johngf** [comment]
mix drop ok "ton site" evil saison 1 episode 10
 jet load serie stream hd superstore saison 5 episode 5 ok

renseingne toi sur google pour advanced setting xml de kodi pour regler le timeout  de ta machine a plus de 60 seconde mini c'est peut etre ça

**Comment by Che-debarras** [comment]
Ok j'ai aucun configurateur mais je vais me renseigner sur ce advancedsetting.xml
Cette solution c'est pour jet seulement ou aussi mxdrop?

Merci

**Comment by johngf** [comment]
bah mix drop fonctionne c'est juste que parfois il y a pas de lien derrière après le décodage sur dpcx
ou peut etre l'url est differente

**Comment by TmpName** [comment]
Young sheldon ^^
Je suis dessus aussi, moi je passe par voirflm.

**Comment by Che-debarras** [comment]
> bah mix drop fonctionne c'est juste que parfois il y a pas de lien derrière après le décodage sur dpcx
> ou peut etre l'url est differente

Sauf que sur le site il y a bien la video qui démarre si on clique sur lecture.

Les 2 sources que je cite pour jetload et mxdrop c'est parcr que les épisodes sont de bonne qualité video et son très réactif pour afficher les nouveaux episodes.

Donc j'espère qu'une solution arrivera. Merci de votre aide

**Comment by johngf** [comment]
je viens de test young sheldon s03 1 8 11 au hasard ça fonctionne sur dpcx tes sur d'etre a jours ?

**Comment by Che-debarras** [comment]
J'ai maj avec les modifs de la beta d'aujourd'hui et retenter et même si je sais pas si ce sont ces modifications qui ont réglé le souci. Mxdrop semble afficher un lien et il se lance.

Pour jetload il faut coupler son ip avec le site jlpair ce que j'ai fait et ça marche mais l'inconvénient c'est que ca dure que 3h ce couplage.

Donc ensuite on doit recommencer a pairer l ip? Toutes les 3h?

**Comment by johngf** [comment]
oui a cause du captcha

**Comment by Che-debarras** [comment]
Quelqu'un d'autre a pas accès a jlpair.net?

**Comment by TmpName** [comment]
Fct ok a ce moment pour moi.

**Comment by Che-debarras** [comment]
Oui le site refonctionne , sûrement un bug de leur part.
