### ISSUE TITLE
Ajouter un nouveau source HD

### ISSUE THREAD

**Issue by zouhair2015** [Kodi-vStream/venom-xbmc-addons#2710]
Bonjour,
J'ai beaucoup utilisé cette application et je l'ai partagée avec mes amis, j'ai remarqué que ht tps://streamcomplet.vip c'est un meilleur site pour Stream, pouvez-vous l'ajouter s'il vous plaît.

**Comment by johngf** [comment]
il est deja dans vstream

**Comment by zouhair2015** [comment]
merci
