### ISSUE TITLE
Fire Stick Amazon 4K et Iptv (sites) 

### ISSUE THREAD

**Issue by Padistan** [Kodi-vStream/venom-xbmc-addons#2712]
Bonjour,

Mon bug :

Aucune chaine IPTV (sites) ne s'ouvre lorsque je tente de les regarder.
J'ai bien tout le déroulement pour y avoir accès jusqu'à la liste des chaines téléchargées mais au moment du click de lancement, je vois juste quelques secondes le symbole de lecture qui apparait sur kodi, pour se fermer rapidement ensuite.

A noter que sur mon pc, je n'ai aucun problème de lecture en testant les mêmes iptv.
C'est probablement une histoire de compatibilité entre la firestick 4k et kodi/vstream.
Les iptv (officiel) marchent bien.

J'ai testé nombre de modifications (changement de lecteur, accélération matériel, vidage de nombreux caches, réinstallation etc etc) mais rien n'y fait.

OS : Androïd
Appareil : Amazon Fire Stick TV 4K
Version Kodi : 18.5
Version Vstream : La dernière (0.7.5.3)

Pour le reproduire :
- Avoir une firestick 4k je suppose (le pc marchant parfaitement bien).
- Allez sur Vstream jusqu'aux listes Iptv (sites), en ouvrir une quelconque encore valide puis lancer une chaine.

Log :
https://slexy.org/view/s2IPa2GXAV
(Voir fin du log avec quelques essais différents qui buggent. SD/HD/FHD même combat)

Un exemple du bug :

> 2020-01-13 15:49:49.599 T:9427 WARNING: CPythonInvoker(12, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
> 2020-01-13 15:49:49.604 T:9426   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=play__&sCat=6&sFav=play__&sId=freebox&sMovieTitle=%7cFR%7c%206TER%20(SD)&sThumbnail=special%3a%2f%2fhome%2faddons%2fplugin.video.vstream%2fresources%2fart%2ftv%2ftv.png&site=freebox&siteUrl=http%3a%2f%2fiptvpro.premium-tv.media%3a8789%2flive%2ffrancesdclark%2fMJ5jwjknJA%2f39446.m3u8&title=%7cFR%7c%206TER%20(SD)
> 2020-01-13 15:49:49.621 T:9180   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=play__&sCat=6&sFav=play__&sId=freebox&sMovieTitle=%7cFR%7c%206TER%20(SD)&sThumbnail=special%3a%2f%2fhome%2faddons%2fplugin.video.vstream%2fresources%2fart%2ftv%2ftv.png&site=freebox&siteUrl=http%3a%2f%2fiptvpro.premium-tv.media%3a8789%2flive%2ffrancesdclark%2fMJ5jwjknJA%2f39446.m3u8&title=%7cFR%7c%206TER%20(SD)) failed
> 2020-01-13 15:49:56.966 T:9430  NOTICE: Creating Demuxer
> 2020-01-13 15:50:04.321 T:9430   ERROR: OpenDemuxStream - Error creating demuxer
> 2020-01-13 15:50:04.322 T:9430  NOTICE: CVideoPlayer::OnExit()

A part ca, félicitations pour le meilleur addon kodi francais ! :)

**Comment by TmpName** [comment]
Tu as essayé avec l'autre lecteur ?
>2020-01-13 15:50:15.334 T:9500  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer

**Comment by Padistan** [comment]
J'ai essayé avec mplayer et dvdplayer.
Par miracle, j'ai quelques Très rare fois une chaine qui se lance (à l'instant animaux fhd sur iptv4 , liste "1")  alors que j'étais sur mplayer mais si tôt que je réessaye ca ne marche plus ! Que ce soit sur la même chaine ou une autre.
Je ne sais pas si c'est le lecteur qui augmente de 1% la chance que ca passe ou si c'est totalement aléatoire.

**Comment by TmpName** [comment]
Parce que a pas mal de moment tu as eu les fichier m3u8, mais la video n'a pas marché.
Ca peut etre aussi la machine qui ne supporte pas ce type de flux, c'est que de l'android.
