### ISSUE TITLE
Ajouter des options pour les videos hosters

### ISSUE THREAD

**Issue by shmox75** [Kodi-vStream/venom-xbmc-addons#2715]
Bonjour à tous ça serait bien d'ajouter des options pour les videos hosters comme par exemple: 
Cocher / décocher hosters avec captcha ou des hosters qui posent problème pour la lécture.

Comme ça si on choisis que les host qui n'ont pas de captcha on auras que des liens de ces dernier.

Enfin je ne sais si j'ai bien élaboré mon idée ?

**Comment by TmpName** [comment]
Sisi c'est clair ^^.
Le probleme c'est le filtrage, si la personne met trop de filtre, elle peut arriver sur une page avec aucun liens disponibles, c'est deja la cas pour certain sites ayant peu de sources (netu HS, beaucoup d herbergeur fermé, ect ...) et impossible de savoir si le site est mort, ou si c'est un probleme de filtrage.

Actuellement sur la plupart des sites, tu as une liste de hosters, ceux qui marchent et ceux qui ne marchent pas, c'est rapide pour toi de choisir.

Et moi par exemple je n'utilise pas les memes hosters selon l'heure de la journée (ou du resultat precedent)

**Comment by shmox75** [comment]
> Actuellement sur la plupart des sites, tu as une liste de hosters, ceux qui marchent et ceux qui ne marchent pas, c'est rapide pour toi de choisir.

Désolé je ne savait pas, J'ai pas compris je clique ou pour avoir la liste des hosters ? Merci

**Comment by TmpName** [comment]
Heu tu me met un doute, tu parles pour un site en particulier ?
Normallement sur la page ou tu lances le film (ou juste la page precedente), tu as plusieurs liens avec le nom du host a chaque fois, non ?

**Comment by shmox75** [comment]
> Heu tu me met un doute, tu parles pour un site en particulier ?
> Normallement sur la page ou tu lances le film (ou juste la page precedente), tu as plusieurs liens avec le nom du host a chaque fois, non ?

Sincèrement je suis confus je ne sais pas si je dois ouvrir une autre topic car mon expérience avec vstream s'est vraiment dégradé, pleins de sites ne marches pas ou retournes des liens morts d'autres sites plante carrément mon android.
Maintenant pour voir un film qui me plait et trouver un bon lien, je passe 30 min à chercher pour trouver un site qui me renvois un lien qui marche :(

PS: js suis sous android 7.1.2 avec une box pas cher mais qui fait l'affaire et ma version kodi est 18.5

Je ne sais pas si je dois revenir à une version 17 de kodi ?

**Comment by Arias800** [comment]
Reviens a Kodi 17.6 car on a beaucoup de problème avec Kodi 18 donc certain qui sont incorrigible de notre coter :/

**Comment by TmpName** [comment]
Pour les liens morts, la on y peux pas grand chose, mais si tu as des sites morts, balances les noms stp.

**Comment by shmox75** [comment]
> Reviens a Kodi 17.6 car on a beaucoup de problème avec Kodi 18 dont certain qui sont incorrigible de notre coter :/

Ah ok je ne savais pas je vais donc revenir à Kodi 17.6. Merci beaucoup.
PS: quel genre de problèmes cause Kodi 18.5 ?

**Comment by shmox75** [comment]
> Pour les liens morts, la on y peux pas grand chose, mais si tu as des sites morts, balances les noms stp.

Ok, je vais d'abord revenir à Kodi 17.6 pour voir si ça remarche, comme ça je ne donnerais pas de fausses erreurs car apparemment  Kodi 18.5 fait des misères :/

**Comment by calvin4242** [comment]
Bonjour à tous! 
Avant je tenais à remercier toute l'équipe pour tout ce que vous faites, et même si j'en profite celà ne m'enpeche pas d'aller au cinéma bien sur... 
Donc pour en revenir au ce pourquoi je suis là c'est que je suis dans le même cas de figure que **shmox75**, cad que mon experience vstream s'est considerablement dégradée. Je fais tourner kodi Leia sur micro pc odroid c2 depuis des années. C'est depuis la fin 2019 que les premiers soucis commencent. Effectivement j'avais realisé la MAJ vers kodi leia aout-sept 2019. Je n'ai pas reellement trouvé de sources qui parlent de ce probleme sur les forums. Neanmoins j'ai l'impression et pas que - que les hebergeurs soit ferment les uns apres les autres soit suppriment les fichiers de leurs serveurs. Peut on affirmer qu'à l'heure actuelle en france on assiste à une "chasse aux sorcieres" sur le marché des box tv ? 

Techniquement ce que je vois c'est que malgré après avoir activé toutes les sources j'ai surtout plein de resultats sur des sources premium (ex: Cinemay) auxquelles je n'ai pas acces sauf certaines quelquefois (captcha, etc) , et pour le reste tres peu de resultats de recherche comparé à "avant": soit un manque de resultats, soit lors de la consultation des liens des sources la plupart du temps ils sont tous morts alors qu'ils apparaissent. Je ne sais pas si je me fais bien comprendre.

On dirait qu'il y a un net manque d'abondement niveau films en effet les recherches par exemple par genre ne varient quasiment pas d'une semain sur l'autre. De plus certains serveurs me font presque planter le pc tellement ca mouline dans le vide (vidoza, flashx,..).  Ah oui j'allais oublier en resultat de recherche je tombe toujours en plus avec une même liste de films+series qui n'ont absolument rien à voir avec ma recherche. 
 
Derniere chose, d'apres ce que je lis plus haut, vstream ne s'entendrait pas au mieux avec kodi 18.5 (qui est sorti il y bientot 1 an public) mais avec la 17,6 ? Es ce un manque de temps et de moyens? Quelqu'un de FIABLE pourrait il l'affirmer ?
Es ce que qqun pourrait m'expliquer ce qui se passe? Merci

**Comment by Arias800** [comment]
Alors pour faire la réponse la plus complète possible je vais séparer ma réponse en plusieurs points :
- Le cas de Kodi :
    L'arrivé de Kodi 18 a provoquer beaucoup de problème avec Vstream, le plus récent est celui avec Cloudflare qui rendait difficile l’accès a pas mal de site. @TmpName a récemment trouver un moyens de débloquer la situation, donc de ce coter là les choses devrai s'améliorer. Mais on est pas a l'abri  de subir a nouveau des bugs gênants de la part de Kodi.

- La fermeture des sites et hébergeurs :
    Depuis toujours les sites et hébergeurs ferme et réouvre, mais récemment il y a des hébergeurs majeur qui ont été fermer (voir cette issue : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2654). Sans compter le problème technique de Gounlimited qui les ont obliger a tout réuploader leurs contenus.

-Manque de temps :
    Vstream ne nous coutes rien hormis du temps, et c'est ce qui nous manque le plus car ont a moins en moins de temps mais d'un autre coter Vstream nous en demande de plus en plus. Donc forcement la situation est compliquer.

En tout cas j’espère que j'ai pu expliquer simplement et de manière complète la situation actuel ^^

**Comment by sizanic** [comment]
C'est vrai que la fin 2019 et janvier ont été difficile. Mais le plus dur est derrière nous.

Techniquement, une grosse passe de corrections a été apportée en janvier et maintenant le déblocage Clouflare. Et aussi les recherches qui retournent plus de résultats. (et pour les sites qui retournent les résultats faux, c'est repéré et la correction va arriver)

Pour le manque de temps, c'est en effet en comptant sur les développeurs historiques qui ne peuvent pas tout prendre en charge.
Pour combler cela, on va augmenter le nombre de développeurs par des actions déjà en cours.

@calvin4242 si tu utilises un odroid C2, c'est que tu as sans doute un niveau technique qui te permettrais de nous donner un coup de main ?
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2727


@shmox75 on ne perd pas de vue ta remarque sur les hosters. Un premier travail en cours va être d'épurer les hosters obsolètes : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2654

**Comment by calvin4242** [comment]
niveau technique oui et non ; je touche a linux, reseaux, serveur php mais car ca n'a pas grand chose a voir avec du dev/debugging la je suis une quiche. Hier soir pour voir j'ai installé eclipse/Pydev c'est plutot la misere a mettre en place d'ailleurs je suis bloqué alors j'immagine meme pas apres...

**Comment by sizanic** [comment]
Si t'es toujours bloqué sur la mise en place d'eclipse, n'hésite pas à en parler sur le sujet : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2739

Ce qu'il manque sur le tuto, c'est qu'il faut afficher les fichiers caché sous windows.
