### ISSUE TITLE
erreur 503 décryptage lien z t et tix 

### ISSUE THREAD

**Issue by drec78711** [Kodi-vStream/venom-xbmc-addons#2717]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.
salut toujour le meme probleme sur vstream on peut plus lancer les liens de zt et tix erreur de decrytage merci de m'aider

**Comment by TmpName** [comment]
Ben je crois que c'est toujours au meme point, pas vu de news
Plus de ZT sur android.

**Comment by Arias800** [comment]
Je viens de tester avec ma toute dernière version, sous Android TV , avec Kodi 18.5 et zt fonctionne correctement. Donc le problème doit venir de ton coter, il me faudrait des logs pour voir d’où ça pourrai venir.

**Comment by sizanic** [comment]
C'est quel version d'Android ?
J'ai déjà relevé qu'il y avait moins de problème sous Android TV 9.

**Comment by Arias800** [comment]
C'est possible, mais logiquement il utilise Android 9 vu que toutes les shield sont mises a jour ^^.

**Comment by TmpName** [comment]
Ha c"etait android le prb ?
Je croyais que ca venait d'une version de lib pourrave cote kodi ?

**Comment by drec78711** [comment]
kodi leia toujour le meme probleme avec vstream  meme avec mise a jour ces 2 source beug et je suis pas le seul rien avoir avec android ou quoi
    Le vendredi 31 janvier 2020 à 18:28:22 UTC+1, TmpName <notifications@github.com> a écrit :  
 
 
Ha c"etait android le prb ?
Je croyais que ca venait d'une version de lib pourrave cote kodi ?

**Comment by Arias800** [comment]
@TmpName En réalité le problème devais venir d'OpenSsl  ^^

**Comment by sizanic** [comment]
@drec78711  
"rien à voir avec Android", comment peux-tu etre si formel ?

J'ai plusieurs versions d'Android pour faire des tests et le fonctionnement est différent !
Et tu ne nous donnes pas ta version. Ou quoi.

De plus, tu n'utilise pas la version de ZT en cours de DEV, la derniere mise à jour par Arias800.
Et pour lui ça fonctionne bien.

@Arias800 , C'est bien sous Android TV 9 que tu ne constates plus de probleme avec ZT ?

**Comment by Arias800** [comment]
Oui après je pense que zt (et tous ses clones ) ont des problème au niveau de leurs implémentation de CF donc c'est difficile de prouver qu'Android 9 limite le problème ou non ^^

**Comment by drec78711** [comment]
salut as tu une solution  concernant pour moi c'est le boitier android de bouygues
    Le vendredi 31 janvier 2020 à 19:27:29 UTC+1, Arias800 <notifications@github.com> a écrit :  
 
 
@TmpName En réalité le problème devais venir d'OpenSsl ^^

**Comment by TmpName** [comment]
Yep openssl, mais de quel coté ? La lib deconne coté android ou coté kodi, c'est auquel des deux de mettre a jour ?

**Comment by isandard** [comment]
j'ai 2 mibox ( une 3 et une S ) avec 2 kodi 17.6 et le même vstream ( beta installée en zip )
OS : différents Android 8 et 9
sur les 2 ZT fonctionne en décryptage de lien
sur les 2 hier tout fonctionnait même en Tirexo


sur les 2 depuis hier soir changement d'host de tirexo, je n'ai même plus le parsing du site ( je pense qu'ils ont changé un petit peu le site et vstream n'extrait plus les données )

Voila un retour d'expérience qui pourrait dire que ce n'est pas Android le soucis.

**Comment by sizanic** [comment]
Il n'y a pas de soucis avec Android si tu utilises Kodi 17.6. Personne n'a de problème avec cette version.
Le débat ici est de faire fonctionner Kodi 18.5.

j'ai 2 mibox ( une 3 et une S ) avec 2 kodi 18.5 et le même vstream.
OS : différents Android 8 et 9

Et je n'arrive pas à lancer de films sur Android 8.0 depuis ZT. J'y arrive en V9.
Nous avons besoin de retours d'expériences pour cette même configuration afin d'identifier une incompatibilité entre Kodi 18.5 et Android 8.

**Comment by isandard** [comment]
je vais tester ce week end sur mon 9 pour voir ZT car tirexo est ko pour le moment

**Comment by TmpName** [comment]
Suite ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2694
