### ISSUE TITLE
bug avec l'apostrophe et autres

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#2718]
correction à voir sur vstream.
En effet, sur ZT la recherche (pour exemple)  du film  « mourir d’aimer » n'aboutie pas
En revanche,  si on retire l’apostrophe à « mourir d aimer »  on trouves enfin  les 2 films
Cette anomalie est très gênante avec les recherches et surtout en vocales…

Enfin, toujours sur ZT, la recherche du film  pour exemple "Titanic" avec ou sans majuscule ne trouve pas le film de 1998 alors qu'il existe bien sur le site (il y a d'autres films qui souffrent de cette même anomalie)

Par ailleurs, à l'ouverture de vstream sur la source ZT le premier clic sur un  lien uptobox a pour résultat un lien inexistant.  il faut revenir en revenir à la position précédente puis cliquer une seconde fois pour voir apparaître le lien uptobox

**Comment by sizanic** [comment]
Bonjour @kris06 ,

problème réglé à l'instant pour les recherches.

Par contre "mourir d'aimer" sur le site ZT ne retourne qu'un seul résultat et ce n'est pas ce film.
Avec la correction, le résultat est le même.

Pour ton problème uptobox, je te conseille de le décrire dans un autre sujet.
Il n'est pas conseillé de traiter de plusieurs sujets en même temps (il n'apparait pas dans le titre, et comme la recherche est maintenant réparée, ce sujet va être cloturé et cet autre sujet va être perdu).

**Comment by kris06** [comment]
En effet mais le problème semble venir de VStream puisqu'à la recherche de
mourir d'aimer  avec apostrophe VStream ne trouve rien  
mourir d aimer  sans apostrophe VStream trouve les 2 films

https://www.zone-telechargement2.vip/films-gratuit/519024-mourir-d-aimer-TVrip-French.html
https://www.zone-telechargement2.vip/films-gratuit/501725-mourir-d-aimer-DVDRIP-French.html

Pour Titanic (de 1998) ça reste un mystère…
Titanic n'apparait pas alors qu’il existe bien sur le site de ZT 
https://www.zone-telechargement2.vip/films-gratuit/5192-titanic-HDLight%201080p-MULTI.html




----- Mail original -----
De: "sizanic" <notifications@github.com>
À: "Kodi-vStream/venom-xbmc-addons" <venom-xbmc-addons@noreply.github.com>
Cc: "kris06" <christian.gross@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Dimanche 2 Février 2020 23:38:34
Objet: Re: [Kodi-vStream/venom-xbmc-addons] bug avec l'apostrophe et autres (#2718)



Bonjour @kris06 , 

problème réglé à l'instant pour les recherches. 

Par contre "mourir d'aimer" sur le site ZT ne retourne qu'un seul résultat et ce n'est pas ce film. 
Avec la correction, le résultat est le même. 

Pour ton problème uptobox, je te conseille de le décrire dans un autre sujet. 
Il n'est pas conseillé de traiter de plusieurs sujets en même temps (il n'apparait pas dans le titre, et comme la recherche est maintenant réparée, ce sujet va être cloturé et cet autre sujet va être perdu).

**Comment by sizanic** [comment]
Tu n'es pas du tout sur le bon site.
Tes exemples sont ceux d'un clone de ZT.
Vstream n'utilise pas ce site.
Normal que les résultats soient différents. :)

**Comment by TmpName** [comment]
De mon coté quand je fais une recherche, je retire moi meme les apostrophes, quand tu fais un recherche vocale, il n'y a pas moyen de dire "mourir aimer" ?

**Comment by sizanic** [comment]
J'ai modifié ZT pour qu'il prenne en charge l'apostrophe.
Plus de problème ici.
Je vais voir pour l'appliquer également à tous les sites.

**Comment by sizanic** [comment]
C'est corrigé de manière globale avec une gestion généralisée des caractères spéciaux.
C'est vérifié sur l'ensemble des sites.

Quelques sites ont été modifiés en complément : 
FilmZenStream, FreeTelechargement, MesFilms, VoirFilms, ZoneTelechargement
