### ISSUE TITLE
anime otakufr

### ISSUE THREAD

**Issue by amahmou** [Kodi-vStream/venom-xbmc-addons#2719]
**Décrivez le bug**
la source otakufr n est plus opérationnalle depuis l activation du DDOS protection de cloudflare sur leur site.

**Votre system**
 - OS:  Android 
-  Appareil [MIBOX]
 - Version Kodi  [18]
- Version Vstream ( LAST VERSION )

**Comment by TmpName** [comment]
Arf.
Alors la désolé, mais faut esperer que cela ne dure pas. Toujours le meme probleme sur android et la lib SSL.

**Comment by Arias800** [comment]
Corriger dans la beta avec les modif de CF
