### ISSUE TITLE
Tirexo et ZT ne fonctionnent plus sur KODI 18

### ISSUE THREAD

**Issue by Rikikisifreddo** [Kodi-vStream/venom-xbmc-addons#2720]
Bonjour, 
Je suis sur fire stick, kodi 17.6 et vstream à jour, compte real debrid. Depuis quelques semaines, zt et planet streaming ne fonctionnaient plus, ok. Depuis peu, tirexo ne fonctionne plus non plus. Avec zt c'est connexion impossible, mais sir tirexo ça connecte, mais "aucune information" sur les liens... Je comprends rien à ces trucs...

**Comment by Arias800** [comment]
Bon il y a l'air d'y avoir eu, en plus du changement d'url, un changement au niveau de Cloudflare. Et j'arrive pas a trouver d’où ça vient.

**Comment by isandard** [comment]
c'est pas le pattern qui a changé ? Je suis pas assez connaisseur pour voir les differences

**Comment by Arias800** [comment]
Non ca a l'air d’être autre chose, mais j'ai pas les connaissance nécessaire pour corriger ca xD

**Comment by Rikikisifreddo** [comment]
Re. Alors, pour info, sur ma fire stick ni tirexo ni zt ne fonctionnent, mais sur ma tcl android, zt fonctionne...les 2 sont en 17.6 avec vstream à jour...

**Comment by TmpName** [comment]
@Arias800 je viens de tester le decodage cf ne marche plus les valeurs jschl_answer ne sont plus bonnes.

Je suis dessus, mais je comprend meme pas comment ca marchait avant.

**Comment by TmpName** [comment]
Bon j'ai une nouvelle version de cloudflare https://github.com/TmpName/Fichier_en_vrac/blob/master/cloudflare.py

Que j'ai faite pr rien au final, je pense aavoir trouve un probleme, voila les valeurs quand j'utilise un navigateur.

>>>  1.1671421305497567
>>>  1.2796602520448697
>>>  1.4480905255480827
>>>  3.0946331472547692
>>>  1.9453516122029721
>>>  3.2339127609001777
>>>  1.9968743344979922
>>>  12.653731644852062
>>>  9.667245404856168
>>>  8.123223869903471
>>>  6.442867483921326
>>>  30.630916953307572
>>>  26.170910250504182
>>>  23.750520226407495
>>>  25.230162347847408
>>>  21.116922273610662
>>>  19.574512372039
>>>  22.14422568480853
Final 31.4778477046

Et maintenant celle avec kodi

2020-02-15 17:10:08.853 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  1.16714213055
2020-02-15 17:10:08.936 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  1.27966025204
2020-02-15 17:10:09.038 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  1.44809052554
2020-02-15 17:10:09.131 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  3.09463314725
2020-02-15 17:10:09.237 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  1.9453516122
2020-02-15 17:10:09.322 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  3.2339127609
2020-02-15 17:10:09.426 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  1.9968743345
2020-02-15 17:10:09.520 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  12.6537316449
2020-02-15 17:10:09.657 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  9.66724540489
2020-02-15 17:10:09.763 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  8.12322386994
2020-02-15 17:10:09.872 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  6.44286748396
2020-02-15 17:10:09.967 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  30.6309169535
2020-02-15 17:10:10.079 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  26.1709102506
2020-02-15 17:10:10.179 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  23.7505202265
2020-02-15 17:10:10.274 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  25.230162348
2020-02-15 17:10:10.404 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  21.1169222737
2020-02-15 17:10:10.478 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  19.5745123722
2020-02-15 17:10:10.568 T:860  NOTICE: 	[PLUGIN] Vstream: >>>  22.1442256849

Final  31.4778477048

Ca se joue pas a grand chose mais au final, la valeur passée en post n'est pas exactement la meme a cause des problemes d'arrondis.
Faudrait voir a refaire des tests en augmentant le nombre de chiffre que kodi traite apres la virgule.

**Comment by TmpName** [comment]
Bon derniere version pour moi https://github.com/TmpName/Fichier_en_vrac/blob/master/cloudflare.py

Bloquage 403.

Donc j'en ai eu marre, j'ai decidé d'utiliser la lib de venom intacte, comme ca, moins de boulot pour nous.
Probleme encore erreur 403 avec kodi (bloquage captcha)

**Comment by Arias800** [comment]
C'est ça qui est ouf parce que même avec la lib de venom ça ne marche pas et pourtant je l'ai retourner dans tout les sens pour trouver une solution, mais rien n'a marcher xD

**Comment by TmpName** [comment]
Ha ok, ca me rassure, ca vient pas de moi.
Donc le probleme qu'avaient les gens avec android, on l'a aussi avec windows ?

Sinon il y a un probleme sous kodi avec les arrondis, faut utiliser Decimal() et pas float()

**Comment by Arias800** [comment]
Je sais pas, j'arrive vraiment pas a comprendre d’où peut venir le problème xD

**Comment by TmpName** [comment]
Je viens de trouver un addon kodi qui l'utilise
`https://github.com/greko17/addon/tree/master/lib/cloudscraper`

A tester si ca fonctionne (vieux de 9 mois)

**Comment by lebigboss** [comment]
Salut les gars je sais pas de quoi vous parlez j'ai pas suivi le file mais chez moi Tirexo et ZT fonctionne parfaitement sur NVIDIA Shield

**Comment by isandard** [comment]
je comprends pas non plus, rien fait, et ce matin suite au commentaire de @lebigboss, je teste et ça fonctionne ausi.

**Comment by TmpName** [comment]
Le soucis, c'est que si ca remarche, c'est pas notre faute ^^.

**Comment by sizanic** [comment]
@TmpName 

> Bon derniere version pour moi https://github.com/TmpName/Fichier_en_vrac/blob/master/cloudflare.py

Je te confirme que cette version est meilleure.

J'étais bloquée depuis deux jours sur les recherches FullStream par un probleme de décodage CF.
Avec ta version, réponse directe !

**Comment by TmpName** [comment]
Ha ?
Ben pkoi elle marche pas chez moi ?
La j'allais installer le plugin que j'ai donné plus haut, pour voir si ca marche, si c'est la cas, on ne sera plus jamais emmerdé avec ca, on prendra la lib officielle de venom.

**Comment by christophe006** [comment]
La derniere mise a jour a pete ZT sur SPMC (base de kodi 17 il me semble) alors que ca marchait parfaitement. 
Est ce qu'il est possible de telecharger la version precedente quelquepart et de la reinstaller?

**Comment by TmpName** [comment]
Oui https://github.com/Kodi-vStream/venom-xbmc-addons/releases

Mais ca devrait pas changer grand chose.

**Comment by TmpName** [comment]
@Arias800 ca marche ^^.
Je suis arrivé a ouvrir une page protegé avec leur code.
Second essais dans la soirée avec la lib dans Vstream.

**Comment by Arias800** [comment]
😮

**Comment by TmpName** [comment]
Bon, pas pu finir, mais c'est bon.
J'ai mit l'appel aux fonctions de venom au millieu de notre fichier CF, du coup pas de modif a faire de notre coté.
Et sa marche :), fini les emmerdes avec CF

En fait dans son code il a un gros fichier de 2M avec tout les UA et les "valeurs SSL", je pense que c'est ca l'astuce, du coup ca risque meme de marcher sur android.

Me reste juste a gerer ses cookies avec notre code.

Et suffira de mettre a jour sa lib a chaque modif de CF.

Bon si ca marche, faudra tous aller sur son github :)

**Comment by Arias800** [comment]
Après faut aussi penser a enregistré dans les fichiers textes l'UA utiliser pour générer le cookie.
Mais sinon c'est tellement bien d'être enfin débarrasser de CF xD

**Comment by TmpName** [comment]
@Arias800 je viens de mettre la nouvelle version de CF.

Ca marche si je prend une url au hasard, mais rien a faire ca veut pas pour tirexo (recaptcha).
Reste a attendre que ca revienne sur ZT pour tester.

**Comment by Arias800** [comment]
Pour Tirexo le seul moyens de passer c'est de remplacer le https par http. Donc il y a encore un soucis de ssl.

**Comment by TmpName** [comment]
Put1 la je vois pas.
J'ai meme essayé le lien pur en desactivant tout et ne gardant que l'url.

**Comment by TmpName** [comment]
Alors vous allez etre mort de rire.
Je suis arrivé a faire marcher tirexo, je sais pas si le code actuel fonctionne, une fois les cookies generes, ca marche a tout les coups.

Le probleme était
> Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider

En fait cloudflare nous detecte comme bot et nous bloque avec un captcha.

J'ai essayé tout les navigateur possible, pas un a voulu marcher, puis j'ai testé ca.
> s = cloudscraper.create_scraper(browser={'custom': 'ScraperBot/1.0'})

Je me suis fais passer pour un bot, et bien c'est bon c'est passé.

**Comment by Arias800** [comment]
Je sais pas si je doit rire ou pleurer en voyant ça xDD
Au pire on passe uniquement avec `s = cloudscraper.create_scraper(browser={'custom': 'ScraperBot/1.0'})` vu que ça a l'air de marcher pour tout les sites ^^

**Comment by TmpName** [comment]
Ben je sais pas, je trouve ca tellement enorme que je prefere pas prendre le risque.

Tu as testé sur android ?

**Comment by Arias800** [comment]
Non mais apparemment ça fonctionne : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2740

**Comment by TmpName** [comment]
Alleluia

**Comment by christophe006** [comment]
Est ce qu'il est prevu une maj auto pour fixer le soucis de ZT avec la 0.7.6?

**Comment by TmpName** [comment]
Ha oui bonne question, merde c'est vrai que ca meriterais la maj auto, mais je viens juste de la faire ....

Et vu qu'il va y avoir de nouveau repertoire, je sais meme pas si ca marcher en MAJ ponctuelle.
Je pense qu'on va tester la ponctuelle.

**Comment by christophe006** [comment]
Merci pour la confirmation @TmpName  . Je ne vois pas encore la Maj donc j'imagine que ca va arriver les prochains jours.
En tout cas merci pour le boulot.

**Comment by sizanic** [comment]
Une màj auto 0.7.7 a été publiée. Elle corrige les problèmes ZT.

**Comment by BENJI97200** [comment]
@sizanic ...Salut ne fonctionne plus nvidia shield tv.....Une solution stp???? merci

**Comment by sizanic** [comment]
Salut @BENJI97200 
Vois s'il n'y a pas déjà un sujet ouvert sur ce problème.
Ou ouvres-en un nouveau en donnant plus de détail.

Ce sujet est fermé.
Un nouveau sujet sera visible par tout le monde et quelqu'un aura peut-être une réponse.

Perso j'ai pas de nvidia.
