### ISSUE TITLE
Bug sur les sources

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2722]
**Décrivez le bug**
NB: je supprime au fur et a mesure les bugs corrigés pour ne laisser que les bugs à corriger.
DERNIER COMMIT EN DATE INSTALLÉ EST CELUI DE TmpName 9d7bf96b

En cherchant la saison 6 de Vikings j'ai rencontré les problèmes ci-dessous:

- **tvseriestreaming** : aucun lien host dans les dossiers des épisodes 
- **Adkami** : pas de lien host POUR LES SERIE (difficile à scraper)
- **Tirexo** : erreur de decryptage de lien 
- **Dpstreaming.cx** et **Series-Streaminghd** et **Planet streaming** et **I.anime** : lien host prostream et gounlimited ne fonctionne pas

**Votre system**
 - OS: [Windows, Android]
-  Appareil [PC, Z6+]
 - Version Kodi  [17 et 18]
- Version Vstream 0.7.5.3

**Comment by Arias800** [comment]
Streamiz , Skstream, Dadyflix on fermer
Streamingdivx  corriger dans la beta

**Comment by Che-debarras** [comment]
Ok peut-être un nettoyage des sources et host fermé ou mort

**Comment by Arias800** [comment]
Oui je le ferai après avoir corriger celle qui sont corrigible ^^

**Comment by Che-debarras** [comment]
Merci beaucoup pour ton aide si tu peux corriger ceux la en 1er:
Dpstreaming.cx 
Seriestreaming 
Planet streaming 
Kaydo 
Tirexo 
filmillimité

**Comment by Arias800** [comment]
Pour Tirexo regarde cette issue :  https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2720

**Comment by sizanic** [comment]
Il faut ajouter dans la liste "Corrigé dans la béta" : 
ZUSTREAM

@Arias800 t'as commité avant moi :)
J'avais aussi une autre modif pour le trie des résultats, que j'ai ajouté.

Les films ne se lançaient pas tous, en y regardant de plus près, le problème venait du hoster "upstream".
J'ai corrigé également le hoster.

**Comment by sizanic** [comment]
Pour Filmstub, je n'ai pas les pubs.
J'ai même réussi à lancer un film : 
- Beaux-parents -> Upvid

**Comment by Arias800** [comment]
Corriger :
- Mixdrop

**Comment by Che-debarras** [comment]
Pour adkami c'était ma première impression que c'est aleatoire donc je m'attendais à ce que ce soit difficile à scraper.

Mixdrop marche, merci
Ok pour zustream et puis les 3 aurees hosts qui marche suffit
Ok pour filmillimité je fais rectifier mon issue

**Comment by Arias800** [comment]
Bon je m’arrête la pour aujourd'hui, je pense que c'est déjà pas mal xD
Voila les dernière modif que j'ai fait :
Corriger :
- Kaydo
- Streamelite
- Streamcomplet

Incorrigible: 
- HLSplay => Recaptcha

**Comment by sizanic** [comment]
Merci pour ce boost de corrections.
Peux-tu éditer ton premier message pour suivre ce qui fonctionne.
Je vais regarder pour en traiter aussi.

Ce serait bien de proposer une MAJ 0.7.54 pour toutes ces corrections.
(Ou une maj majeure 0.8 ?)

Qui s'en occupe généralement ?

**Comment by Arias800** [comment]
Pas besoin d'éditer mon message, il suffit de regarder mon dernier message et le 1er message de Che-debarras (vu qu'il a éditer son poste au fur et mesure) et comme ça tu peut voir ce que j'ai corriger et ce qu'il reste a corriger.
Normalement les maj c'est TmpName et johngf qui s'en occupe mais visiblement johngf a supprimer son compte Github.

**Comment by yodidon** [comment]
Pour info j’avais proposé des modifications sur k-streaming je regarde ce que je peux faire de mon côté

**Comment by TmpName** [comment]
Streamz, plus de video de lapin.

**Comment by sizanic** [comment]
Oui, il a quitté le projet sans explication.
Ces derniers commits, il y a deux jours, ont consisté à supprimer son nom dans le projet !
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/8abcc1f96a56af5228fbbfb2fbfca0e0e99b2ad6


Pour les maj majeurs, tu restes donc le seul.
**Cela est-il sain ?**
(que tu sois seul, pas que ce soit toi :-) )
Il faudrait toujours qu'il y est au moins deux personnes capable de le faire.

Pour les maj mineurs, je vois que la dernière date du 10/01.
C'est automatique et mensuel ?
La prochaine sera le 10/02 ?

ça a beaucoup bougé depuis un mois, ça ferait du bien une petite maj.

**Comment by TmpName** [comment]
Ben j'ai pas compris ce qu'il lui a prit, il suffisait de ne plus se connecter.

Effectivement ca fait un bail pour les majeures. Je vais en refaire une ce WE au plus tard.
Non c'est pas automatique du tout, et c'est assez chiant a faire ^^ cf https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour-(admin)

Et non c'est pas sain du tout, mais je pense que tout le monde peut les faire, c'etait juste un arrangement entre nous deux :)

Par contre la, j'ai les boules, c'est le deuxieme pilier qui quitte le projet et toujours pas de pilote pour diriger. Je pense que je vais mettre une annonce dans la prochaine maj comme quoi on recrute ^^.
Je crois qu'il y a un petit popup avec des infos, faut que je retrouve quand ca s'active.

**Comment by TmpName** [comment]
@Che-debarras il est jour ton post ? C'est pas possible que @Arias800 est deja tout reparé ?

**Comment by Arias800** [comment]
J'en est corriger un paquet donc je ne saurai pas te dire si j'ai tout corriger ou pas xD

**Comment by yodidon** [comment]
Si je peux aider à mon niveau pas de problème 

Envoyé de mon iPhone

**Comment by Che-debarras** [comment]
> @Che-debarras il est jour ton post ? C'est pas possible que @Arias800 ait deja tout reparé ?

Si il est a jour avec le dernier commit de sizanic
Oui Arias a corrigé pratiquement tout et ceux qui reste est négligeable a part tirexo mais le reste c'est des problèmes interne des sites internets.

Donc je remercie grandement Arias pour ses corrections et sa réactivité.

**Comment by sizanic** [comment]
Et perso j'ai également traité un grand nombre de sources LiveTV.
Ce qui permet l'accès au sport en direct pour pratiquement tous les flux proposés.

**Comment by TmpName** [comment]
Si vous voulez retarder la MAJ prevenez moi ici, je pense la faire ce WE.

**Comment by Che-debarras** [comment]
La maj de tvstreaming donne des dossiers d'épisodes vide sans aucun lien host quelque soit l'host  upvid embed www jetload vidoza

**Comment by TmpName** [comment]
Ha mer2, j'ai pas été aussi loin.
Et la c'est trop tard ca vient de partir.

**Comment by Che-debarras** [comment]
Ok c'est juste pour le signaler pour eviter que d'autres fassent la demande ( je met a jour mon post pour eviter les doublons)
Merci pour cette maj.

**Comment by sizanic** [comment]
De toute façon on pourra jamais etre à jour avec toutes les sources qui fonctionnent en même temps.
Je suis par exemple en train de travailler sur FullStream.

Il fallait sortir cette MAJ de toute façon.
Merci de l'avoir fait.

@Che-debarras  je propose de cloturer cette issue et d'en créer une nouvelle pour suivre les sources OK/NOK, afin de suivre le contenu de la prochaine mise à jour.

**Comment by Che-debarras** [comment]
J'y est pensé à clore et créer une nouvelle pour que ce sois visible pour tous.
Donc je vais le clore et recréer un autre post
