### ISSUE TITLE
Bouton retour au menu précédent

### ISSUE THREAD

**Issue by cedricam** [Kodi-vStream/venom-xbmc-addons#2723]
Il serait bien d'avoir un bouton retour pour remonter directement au menu précédent et non pas simplement à la page précédente. 
Ex:
Si on est a la 5e page dune recherche sur un moteur, il faut remonter toutes les pages alors que le but est de revenir à la liste des moteurs.

**Comment by sizanic** [comment]
Salut.
Je comprends l'idée, mais on ne veux pas tous revenir au même endroit.
Perso, j'utilise des raccourcis depuis les favoris de KODI.
J'aimerai revenir ici, dans les favoris de KODI (donc je ressors de VStream).


J'ai regardé ce qu'on peut faire, il faut choisir l'action parmi cette liste : 
https://kodi.wiki/view/Action_IDs

On associe l'action choisie avec une touche grâce à cette méthode : 
https://kodi.wiki/view/Keymap

Voici un exemple (qui me correspond et que je vais garder du coup).
J'associe le "retour au menu principal" avec un "appuie long" sur la touche "Backspace" (ce qui est compatible avec ma télécommande de ma box android).
Dans un fichier que je nomme "keymaps.xml" et que je dépose dans le dossier userdata.
Sous Windows, c'est ici : 
C:\Users\MyName\AppData\Roaming\Kodi\userdata\keymaps\keymaps.xml

Contenu du fichier : 

<keymap>
  <global>
    <keyboard>
	  <backspace mod="longpress">PreviousMenu</backspace>
    </keyboard>
  </global>
</keymap>

**Comment by TmpName** [comment]
Ha wi pas bete.
Mais il y a un soucis, quand tu fais "precedent" ca recupere la precedente page du cache, sans la recharger. Tandis que si tu veux revenir directement a la page des recherches, ca va recharger la page (et put1 que c'est long pour celle la)
