### ISSUE TITLE
KODI 19 MATRIX

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2725]
Bonjour!

Y a-t’il des gens qui ont essayé vStream avec la version 19 de kodi?
Est-ce fonctionnel?

**Comment by Che-debarras** [comment]
Oui moi mais il faut utiliser la  version du 11.10.2019 car toutes les versions depuis rendent Vstream incompatible à cause d'une dependance python.

**Comment by Arias800** [comment]
Ça ne sera pas fonctionnel avant un moment car ça demande de faire pas mal de modification (surtout pour faire fonctionner python 2 et python 3 en même temps) ^^

**Comment by Che-debarras** [comment]
Pourquoi python 2 et 3 en même temps? Vu que kodi fonctionne avec python 3.

**Comment by Arias800** [comment]
Kodi 19 fonctionne avec Python 3 mais Kodi 18 et inférieur fonctionneront toujours sous Python 2. Donc on ne peut pas limiter Vstream a Python 3 ^^

**Comment by Che-debarras** [comment]
C'est ce que je pensais mais si une 2eme version vstream avec les dernieres maj de kodi voit le jour cela motivera certain a mettre a jour leur kodi.

Je ne sais pas les intentions des devs de vstream donc est ce que cela veut dire que vstream sera utilisable qu'avec kodi 18?  Je pense que nombreux sont les utilisateurs de vstream qui veulent mettrea jour leur kodi pour d'autres addons egalement

**Comment by Arias800** [comment]
Non Vstream sera utilisable sur n'importe quel version de Kodi (dans la mesure du possible bien sur) donc ajouter la compatibilité a python 3 ne supprimera pas la version python 2 vu qu'il suffit de vérifier quel version de Kodi est actuellement utiliser pour en déduire les différente fonction a utiliser. En sois rien ne changera pour les utilisateurs de Kodi 18 ou inférieure. ^^

**Comment by alKODIque** [comment]
> Ça ne sera pas fonctionnel avant un moment car ça demande de faire pas mal de modification (surtout pour faire fonctionner python 2 et python 3 en même temps) ^^

Ouff,,
J’en doute aucunement. Vous êtes vraiment très courageux et probablement tout autant passionnés pour vous lancer dans cette aventure

**Comment by alKODIque** [comment]
Alors je me rends compte avec tout ceci que j’ai tellement hâte de me débarrasser de Leia que j’ai l’automatisme de vouloir aller plus vite vers l’avant quand au fond, la dernière version de kodi que j’ai «vraiment « aimé » était Jarvis 😂😂😂 vaux mieux reculer que de se lancer vers des beta... mais tant que j’ai la chance de pouvoir utiliser vStream... j’ai pas le choix de continuer à utiliser kodi.
Merci à vous tous les devs! Une chance que vous êtes là :))

**Comment by MX10-AC2N** [comment]
Y-a-t-il une version compatible avec Kodi 19 car pour ma part Vstream est impossible a installer, je suis sous la toute dernière mise a jour de Kodi 19, celle du 23/03/2020..

**Comment by sizanic** [comment]
@MX10-AC2N  tu es au bon endroit cette fois pour parler de ce sujet.

Mais prends le temps de lire tous les échanges ici et tu aura ta réponse.

**Comment by Arias800** [comment]
Les choses avancent mais ce n'est pas une opération qui se fait simplement.

**Comment by MX10-AC2N** [comment]
@sizanic Merci, j'avais déjà pris le temps de lire tous les échanges mais comme ma version de kodi est plus récente que celle dite fonctionnelle avec Kodi, je suis bloqué.. Je n'ai pas envie de repartir d'une install vierge.. Bref waiting..
@Arias800 Merci, cool de voir que vous êtes déjà sur le coup.. J'espère que l'on pourra rapidement retrouvé Vstream sous Kodi 19.. Bon courage et encore merci pour tout ça...

**Comment by Arias800** [comment]
Bon bah pour le moment il serai impossible de faire un addon fonctionnent sous python 3 et python 2 en même temps. LOL

**Comment by sizanic** [comment]
@MX10-AC2N 
oui, c'est bien ça, ta version est trop récente donc tu avais la réponse : ça ne peut pas fonctionner.
Et ce qu'il fallait aussi comprendre enter les lignes, c'est que c'est pas pour maintenant, et que si tu veux Vstream, il te faut rester sous KODI 18.

Par contre si tu es sous Windows, tu peux installer une version 18 en même temps que ta version 19, dans un autre répertoire.

**Comment by MX10-AC2N** [comment]
@sizanic  Bon du coup retour sous Kodi 18, c'est bon de retrouvé Vstream... J'espère que vous arriverez a faire se passage vers Kodi 19.. Bon courage et encore merci...

**Comment by Arias800** [comment]
Je ferme cette issue, je continue a donner des infos sur celle la : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2897
