### ISSUE TITLE
Responsable des Mises à jour

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2726]
Bonjour,

suite au départ de @johngf, quelques cartes "Administrateur" sont à redistribuer.
@TmpName est le seul pour l'instant à gérer les mises à jour.

J'en appelle à : 
@razorex 
@Arias800 

Etes-vous volontaires pour en produire de temps en temps ?
Perso je veux bien.
Mais je veux recenser les autres courageux :)

@TmpName  tu faisais comment avec John pour vous mettre d'accord sur la prochaine maj à faire ?

**Comment by TmpName** [comment]
Aucun accord ^^.
Lui faisait les ponctuelle quand il en avait envie, et quand ca faisait trop de temps sans la majeure, c'est moi qui m'y collait.
Et la novembre 2019, ca fait longtemps, donc la c'est sur, c'est pour moi.

**Comment by razorex** [comment]
Salut,
déçu d'apprendre la nouvelle, pour ma part si je peux aider pas de souci, je rappelle tout de même au passage que je ne suis programmeur. Mais si je peux mettre mon temps au service de la communauté vStream.

**Comment by sizanic** [comment]
Salut,
sans que tu sois programmeur, tes contributions sont largement satisfaisantes.
Des non-programmeurs comme toi on en veut plein ! 😉

**Comment by sizanic** [comment]
@razorex 
tu es très actif, quel environnement utilise-tu pour développer ?

N'es-tu pas interessé par cela : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2739

J'ai besoin de retour d’expérience pour l'enrichir.

Je note que tu es volontaire pour soutenir la communauté.
Si elle s'agrandit, je demanderai aux nouveaux de passer par des Pull Request et j'aurai besoin de reviewer.

**Comment by razorex** [comment]
@sizanic mon environnement de travail c'est Notepad++ Regex101 et google. lol

**Comment by TmpName** [comment]
XD, comme moi.
En fait mon probleme c'est que j'ai kodi sur un petit PC passif qui me sert de TV, pas sur qu'il puisse encaisser cet environnement (il a deja du mal avec VNC)

Mais je le testerais au passage de kodi 19, la vu le bordel que ca risque d'etre, pour le deboguage je vais pas trop avoir le choix.

Par contre suis pas sur qu'on ait besoin de reviewer, la beta est faite pour ca, combien de fois on a validé un fichier qui a tout mit en panne ....
Je pense que de laisser une validation pour quelques codes, le temps que la personne gere le process, apres on peut la lacher. Faut juste faire gaffe avant de valider une MAJ.

**Comment by TmpName** [comment]
Alors du coup, un motivé ^^ ?
Ensuite je refait un grosse MAJ ou vous pensez qu'un petite ca va aussi refaire les nouveaux repertoire ?

**Comment by sizanic** [comment]
Si tu parles du repertoire cloudscraper, je pense en effet qu'on est obligé de repasser par une grosse MAJ.

Je vais m'y coller ce WE en suivant cette procédure : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour-(admin)


Est-ce que tu peux la regarder de nouveau en détail pour voir s'il ne manque rien.

**Comment by TmpName** [comment]
Tu tentes la grosse direct du coup ? Sans tester la petite ?
C'est long a faire ...

**Comment by sizanic** [comment]
je pense que la petite ne va pas embarquer le dossier /cloudscraper/

 ça n'a pas l'air si long d'après la procédure.

**Comment by sizanic** [comment]
J'ai suivi la procédure, au milieu de cette page : 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour-(admin)#mise-%C3%A0-jour-total

En ne suivant que la partie "Mise à jour totale" et je confirme que ce n'est pas long.

Mais je suis tout de même bloqué car je ne suis pas autorisé à commiter sur master.

**Comment by TmpName** [comment]
Ha bon ?
Je regardes ca.

Mais tu as deja tout fais ?
- Virer les fichier inutiles
- Mis a jour le fichier xml  en fonction des fichiers en plus ou en moins
- créer les fichier via le code python
- ziper et uploder tout le bouzns
- ect ...

Et tu trouves ca pas long ?

**Comment by sizanic** [comment]
Quels fichiers inutiles ?

**Comment by TmpName** [comment]
T'inquietes, j'extrapole, y a rien du tout, mais en general on en profite pour virer les hosts/sites HS.
La derniere date de 15 jrs, si il y en a c'est ma faute.

**Comment by sizanic** [comment]
On est au moins deux pour les MAJ ...
