### ISSUE TITLE
[BUG] - FullStream -> recherche -> Page suivante

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2728]
Lors d'une recherche sous FullStream, le lien **Suivant** ne fonctionne pas.
Il ne fait rien.

Exemple avec la recherche "joker".

**Comment by TmpName** [comment]
Quelqu'un est dessus ?

**Comment by TmpName** [comment]
Je viens de regarder, je pense qu'on va laisser comme ca ^^

En fait il faut modifier la requete POST en rajoutant search_start = numero de page.
Un poil chiant a mettre en place juste avec un lien "suivant"

**Comment by sizanic** [comment]
Merci pour l'analyse et la description de la correction.
Du coup peut être qu'un courageux le fera.

**Comment by TmpName** [comment]
Le truc c'est que en pesant ce que ca apporte et les bidouilles a faire pour que ca remarche, suis pas sur que ca vaille le coup.

**Comment by sizanic** [comment]
Il faut faire quelque chose car je viens de relancer une recherche, elle ne marche pas du tout.
Quelque soit ce qu'on cherche, c'est toujours les mêmes résultats : les films de la page d'accueil !

**Comment by sizanic** [comment]
Je m'en occupe.

**Comment by sizanic** [comment]
Terminé.

Par contre est instable avec la version CloudFlare en place...
