### ISSUE TITLE
[EVOL] - VF_SPACE - Ajout de l'année et de la qualité

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2729]
On est à la recherche de développeurs,
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2727

Pour celui qui veut s'y mettre, voici une petite évolution pour celui que ça tente.

Pour FULLSTREAM, la pochette du film et l'année sont à récupérer.

**Comment by yodidon** [comment]
J’ai poster des correctif pour la pochette le titre l’année et la qualité ( encore un petit soucis avec la pochette à finaliser

**Comment by TmpName** [comment]
Ha c'est deja posté ?
Mince j'ai pas vu, c'etait avant la MAJ ?

**Comment by sizanic** [comment]
c'est pas dans la beta, ça dort dans cette branche : 
https://github.com/yodidon/venom-xbmc-addons/commits/patch-7/plugin.video.vstream/resources/sites/fullstream.py

Mais en effet c'est pas terminé, il manque les pochettes.

![Debug Blank](https://user-images.githubusercontent.com/47307622/74781868-a8e54a00-52a2-11ea-92f4-790427b9b68c.JPG)

mais dès que @yodidon  aura un bon environnement de travail il pourra le terminer :)

**Comment by yodidon** [comment]
@sizanic  avec grand plaisir :)

**Comment by yodidon** [comment]
de mon coté je n'arrive plus a acceder a fullstream, l'url est passer en w3 mais il me semble qu'il y ait un autre souci

**Comment by sizanic** [comment]
Dans Vstream on a supprimé la source Fullstream.
Elle est remplacée par vf_space.

vf_space est bien en w3.

**Comment by sizanic** [comment]
La pochette s'affiche bien.
ce qu'il manque c'est : 
- la qualité 
- l'année

**Comment by yodidon** [comment]
Ok je regarde ça

**Comment by yodidon** [comment]
Fait

**Comment by sizanic** [comment]
Impec'
