### ISSUE TITLE
ZT TIREXO problème au 1er click

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#2730]
sur pc et box android 
concerne ZT TIREXO
le 1er clic sur uptobox à pour réponse,  un vide
il faut revenir (1fois) en arrière et cliquez de nouveau sur uptobox pour avoir apparaître un lien uptobox fonctionnel

**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by TmpName** [comment]
Ha bon ca marche ?
Je croyais que c'etait HS a cause de cloudflare en ce moment ,

**Comment by kris06** [comment]
oui ça fonctionne sur smartphone 
 


----- Mail original -----
De: "TmpName" <notifications@github.com>
À: "Kodi-vStream/venom-xbmc-addons" <venom-xbmc-addons@noreply.github.com>
Cc: "kris06" <christian.gross@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 14 Février 2020 17:36:10
Objet: Re: [Kodi-vStream/venom-xbmc-addons] ZT TIREXO problème au 1er click (#2730)



Ha bon ca marche ? 
Je croyais que c'etait HS a cause de cloudflare en ce moment ,

**Comment by kris06** [comment]
et tablette android

----- Mail original -----
De: "TmpName" <notifications@github.com>
À: "Kodi-vStream/venom-xbmc-addons" <venom-xbmc-addons@noreply.github.com>
Cc: "kris06" <christian.gross@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 14 Février 2020 17:36:10
Objet: Re: [Kodi-vStream/venom-xbmc-addons] ZT TIREXO problème au 1er click (#2730)



Ha bon ca marche ? 
Je croyais que c'etait HS a cause de cloudflare en ce moment ,

**Comment by Che-debarras** [comment]
J'ai un smartphone et box et non ça ne marche pas ya erreur de decryptage de lien.

Tu est sous quel version de vstream?

**Comment by TmpName** [comment]
Ca en est ou avec les dernieres versions ?

**Comment by kris06** [comment]
probleme de lien au 1er clic de zt
https://www.youtube.com/watch?v=1ChURlozPXw&feature=youtu.be

**Comment by sizanic** [comment]
> Cette vidéo est privée.

**Comment by kris06** [comment]
Je l'ai passé en publique

**Comment by TmpName** [comment]
Oui je l'ai vu aussi, le premier essais rate mais crée le cookie et du coup ca marche du premier coup au second.

**Comment by razorex** [comment]
Cette issue est elle soldé???????

**Comment by kris06** [comment]
Bjr non le problème persiste

**Comment by razorex** [comment]
Du coup @TmpName on ne peut pas anticipé la création du cookie???

**Comment by Arias800** [comment]
Le soucis c'est qu'une requête en parametre un multipart doit être effectuer avec le paramètre `files` de requests, hors Cloudscraper ne prends pas en charge ce paramètre.

**Comment by TmpName** [comment]
Ha merde, c'etait ca ?
Pourtant ca marchait avec urllib avec des commande de bases, y a pas un autre moyen avec request ?

**Comment by Arias800** [comment]
C'est la seul raison qui explique que le décryptage échoue que la 1ere fois. Visiblement en utilisant MultipartEncoder il devient possible de d'utiliser `data` et donc logiquement ça devrai marcher après. https://stackoverflow.com/a/12385661

**Comment by TmpName** [comment]
Sinon un gros truc crade.

Dans le code de CF des qu'on a le cookie sur l'url est protect1 on quitte, et dans le code de tirexo si on a pas la page au premier essais on refait un passage ?

**Comment by TmpName** [comment]
Par contre y a un truc que je comprend pas j'ai ca dans les logs

```
2020-03-26 17:50:51.899 T:464  NOTICE: 	[PLUGIN] vStream: Page ok
2020-03-26 17:50:51.986 T:464  NOTICE: 	[PLUGIN] vStream: Sauvegarde cookies: 
2020-03-26 17:50:52.277 T:464  NOTICE: 	[PLUGIN] vStream: Page protegee par cloudflare
```

Pourquoi ca reboucle apres avoir decodé la page ?

**Comment by Arias800** [comment]
Je pense que c'est liée au morceau de code que j'avais ajouter au moment où ils changaient tout les jours le nombre de fois où il faillais passer leurs protection xD

**Comment by TmpName** [comment]
Yep je viens d'effacer mon post.
Du coup je viens de trouver une astuce je pense.

Dans ta boucle, il te suffit de relire les cookies, si ils ont chnagé, tu charge les nouveaux

**Comment by kris06** [comment]
Beaucoup de travail pour un clic désolé je suis l'initiateur qui a souligné ce défaut. Je suis peut-être trop perfectionniste mais au fond , je suis ravi de constater que chacunes de vos interventions apportent toujours des améliorations. 
encore merci à vous tous

Ps j aimerais juste savoir si  c'est bien le trafic lié â  cette periode tres particuliere que bous traversons qui provoque mets tirexo et zone hors service ...?

**Comment by Arias800** [comment]
Bon je pense que j'ai trouver un bon compromis : 
- On tente de passer leurs protection une 1ere fois.
- Si ça bloque on récupère les nouveaux cookie (car ils ont correctement créer même si la protection n'est pas passer).
- Et on refait une requête pour valider le tout.

Oui la période actuel ne les aides absolument pas, du coup leurs serveurs sont régulièrement hs xD

**Comment by TmpName** [comment]
Moi j'aurais juste fais un truc de ce genre

```
    cookies = GestionCookie().Readcookie('www_dl-protect1_co')

    sHtmlContent = exectProtect(cookies, url)

    while (re.search('<input type="submit" class="continuer" name="submit" value="Continuer" />', sHtmlContent)):
        if passe < 4:
            sHtmlContent = exectProtect(cookies, url)
            passe = passe + 1

            cookies = GestionCookie().Readcookie('www_dl-protect1_co')
                        
        else:
            break
```

**Comment by Arias800** [comment]
Ça revient au même non ? La différence c'est juste que je revérifie pas le cookie a chaque fois et en sois c'est pas utile de le vérifié a chaque fois.
```
    passe = 0

    # 1ere Requete on tente de voir si ca passe du 1er coup
    cookies = GestionCookie().Readcookie('www_dl-protect1_co')
    sHtmlContent = exectProtect(cookies, url)

    while (re.search('<input type="submit" class="continuer" name="submit" value="Continuer" />', sHtmlContent)):
        if passe == 0:
            cookies = GestionCookie().Readcookie('www_dl-protect1_co')
            passe = passe + 1

        elif passe <= 3:
            #On brute force pour voir
            sHtmlContent = exectProtect(cookies, url)
            passe = passe + 1

        else:
            break

```

**Comment by TmpName** [comment]
Ben je pensais au cas ou le bon cookie n'arriverais pas au second mais troisieme essais.
