### ISSUE TITLE
[TIREXO] - Il manque des résultats dans la recherche

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#2732]
sur pc box android et smartphone
la recherche du film Titanic (de 1998) ne trouve aucune réponse !
Titanic apparaît pourtant sur ZT tirexo
https://www2.zone-telechargement3.vip/films-gratuit/5192-titanic-HDLight%201080p-MULTI.html

il y a aussi un bug récurent sur les bandes annonces exemple
Au-delà du désespoir (de 1991)
la bande annonce de ce film ne correspond pas alors que le lien allociné se trouve bien dirigée sur ZT tirexo  https://www2.zone-telechargement3.vip/films-gratuit/524396-au-dela-du-desespoir-DVDRIP-MULTI.html 

il y a de nombreux films  dans ce cas de figure..

**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by sizanic** [comment]
description du bug Titanic : 
Il y un filtre qui supprime les doublons de résultats pour les films qui portent le même nom,
Car souvent c'est le même film dans une qualité différente.

Il faut modifier ce filtre pour ajouter la dateDuFilm également comme critère.

**Comment by sizanic** [comment]
Pour la bande annonce, on n'utilise pas allociné, mais TMDB.
Le probleme c'est qu'avec que le titre il y a plusieurs résultats et ce n'est pas forcement le bon.
Il faut ajouter l'année lorsqu'on recherche les infos sur le film.

**Comment by sizanic** [comment]
Je prends la correction des deux bugs.

**Comment by kris06** [comment]
merci pour votre réactivité
j'aurais aimé posséder vos connaissances pour vos aider dans cette tache


----- Mail original -----
De: "sizanic" <notifications@github.com>
À: "Kodi-vStream/venom-xbmc-addons" <venom-xbmc-addons@noreply.github.com>
Cc: "kris06" <christian.gross@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 14 Février 2020 20:12:42
Objet: Re: [Kodi-vStream/venom-xbmc-addons] RECHERCHER SUR ZT TIREXO problème avec la réponse à la requête  (#2732)



Je prends la correction des deux bugs.

**Comment by sizanic** [comment]
C'est corrigé pour Titanic.

Reste le probleme de la bande annonce ...

**Comment by Che-debarras** [comment]
Qu'en est il du problème de erreur de decryptage de lien ?

**Comment by sizanic** [comment]
> Qu'en est il du problème de erreur de decryptage de lien ?

Le sujet est suivi ici :  https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2720

**Comment by sizanic** [comment]
J'ai regardé pour le problème de la bande annonce.
On la recherche sur Youtube.
Youtube nous retourne une autre vidéo car cette bande annonce n'existe pas sur Youtube sous le titre "Au dela du desespoir". Mais seulement sous le titre original "Our sons", avec une BO en VO.

Modification très difficile,
Donc pas de correction prévue pour l'instant ...

**Comment by sizanic** [comment]
@kris06 Pour les autres films avec ce même problème de BO, ce serait pas parmi cette liste par hasard ? 😉 
h t t p s://www 2.zone - telechargement 3 .vip/user/Kris06000/news/

Et fais attention quand tu réponds par mail, j'ai édité ton message du 14/02, il y avait ton adresse mail en clair.

**Comment by TmpName** [comment]
Ha oui, c'est la misere pour trouver ce film sur youtube.
Comment ca se fait sur une plate forme aussi complete  de ne pas trouver une bande annonce ...

**Comment by kris06** [comment]
bonjour et merci sizanic je vais cesser de répondre par mail
oui il s'agit bien de cette liste mais il y a bien d'autres films dont la bande annonce n'est pas reliée au titre..

par ailleurs, j'avais signalé un problème qu'un de tes collaborateurs avait traité à propos de l’apostrophe, cependant le problème persiste...  

En effet, quant on recherche mourir d'aimer sur tirexo on ne trouve rien alors que si tu retires l'apostrophe à mourir d aimer ,  tu trouves les 2 films....

A la suite de maj  0.7.6 j'ai remarqué que tous mes appareils ne m'ont pas obligés à faire la mise à jour habituelle, elle s'est faite toute seule ! Est ce que cela signifie qu a présent les maj seront automatique ? et qu'il n'y aura plus besoin de la faire sois-même ?

cette amélioration de vstream est très attendue...
bien à toi

**Comment by sizanic** [comment]
Bonjour,

Pour la bande annonce, on ne va rien faire pour l'instant, trop de travail, mais on se le note pour plus tard. Le problème est que youtube nous retourne un résultat et c'est difficile de comprendre que ce n'est pas le bon, pour pouvoir basculer sur un autre moteur de recherche comme allociné par exemple. Ou alors il faudrait qu'on passe tout le temps par allociné, c'est à étudier.

Pour l'apostrophe, c'est moi qui l'avais corrigé, mais seulement pour ZT et pas pour TIREXO.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2718
Je n'ai pas encore traité le dernier commentaire que j'ai laissé et qui était : 
> Je vais voir pour l'appliquer également à tous les sites.

Je commencerai par TIREXO :) 

Il existe plusieurs sortes de mises à jour : 
https://kodi-vstream.github.io/docs/update/

Si tu as installé le repository en plus de l'addon, tu auras automatiquement les mise à jour **majeures** : 
les versions 0.7.5, 0.7.6, 0.7.7, etc.

Sinon, il reste à faire manuellement les mise à jour **intermédiaires** : 
0.7.54, 0.7.55, 0.7.56, etc ...

Cdt

**Comment by sizanic** [comment]
En mettant en place la correction des accents sur TIREXO, je remarque que ça fonctionne sur ZT seulement par une recherche sur la source directe, et pas sur une recherche globale.

Je corrige cela en même temps ...

**Comment by kris06** [comment]
Et bien je te remercie pour tes réponses toujours précises. Comme tu peux le constater, je m’intéresse beaucoup à ton/votre travail et aux améliorations qui pourraient être apportées à vstream

En effet , il serait à mon sens plus judicieux d'utiliser Allociné comme le fait d'ailleurs, tirexo pour les bandes annonces ,d'autant plus qu'il suffit juste de reprendre le chiffre indiqué sur la terminaison du lien :  214232 pour le film au delà du désespoir 
http://www.allocine.fr/film/fichefilm_gen_cfilm=214232.html

Ceci dit, les B.A. me semblent quand même moins importantes que de profiter un jour d'une automatisation des mises à jour intermédiaires... 
A ce propos, y a t'il un projet en cours de développement pour cette future amélioration ?

**Comment by Arias800** [comment]
Alors passer par Allociné, pourquoi pas, mais il faut comprendre que ça ne réglera potentiellement pas les problèmes de détection pour les films ayant des noms similaire. Car pour trouver une bande annonce, Vstream fait une recherche avec le nom du film et il prends le 1er liens disponible. Donc passer par Allociné ne supprimera pas le problème des conflits. Mais effectivement ça peut éviter de tombes sur des choses qui n'ont rien a voir.

En ce qui concerne l'automatisation des mises à jour intermédiaires, je suis contre, et la raison est simple: la mise a jour des fichiers et hosters peut réécrire les fichiers que l'on est entrain de créer ou modifié en local, donc ça peut faire perdre potentiellement des heures de travail. ^^

**Comment by Arias800** [comment]
Bon je viens d'essayer et maintenant je me rappel pourquoi j'avais abandonner le scrape d'Allocine : Car leurs site est nul et encore je pèse mes mots. D'une page a l'autre le code n’arrête pas de changer, aucune API, bref inutilisable.

**Comment by kris06** [comment]
Si selon vous la mise à jour  intermédiaire automatique  n'est pas souhaitable pourriez-vous dans ce cas développer une notification à l'ouverture de kodi et non à l'ouverture de vstream.?

En effet, nous sommes très nombreux à utiliser vstream à partir des sources enregistrées dans les favoris si bien que nous ne pouvons observer votre notification habituelle.

Aussi, il serait utile de forcer l’affichage de cette notification et ne pas la faire disparaître jusqu'à l'exécution de ladite mise à jour…

Je me tue à dire sans cesse à mes amis qu'il doivent  ouvrir vstream pour procéder à cette opération, si opération il y a... !

Enfin vous avouerez quand même la  mise à jour intermédiaire automatique réglerait une fois pour toute cette histoire qui suscite l'incompréhension de nombreux utilisateurs et qui pour certains, se perdent à vouloir mettre à jour !'addon de vstream pensant ici avoir réglé l'ensemble des opérations...

A vous lire.

**Comment by TmpName** [comment]
Ben si ca marche, y a pas besoin d'aller voir dans vstream, si plus aucun films ne marche suffit d'aller voir si il y a une MAJ proposée, c'est pas une obligation.

**Comment by Arias800** [comment]
Alors ce qui peut être tester c'est de basculer le code de vérification de la maj dans le service.py. Et logiquement ça devrai exécuter la vérification au lancement de Kodi ^^

**Comment by kris06** [comment]
oui c'est une idée qu'il faut essayer, mais comment retenir l'affichage de cette notification jusqu’à l'exécution de ladite mise à jour…

**Comment by Arias800** [comment]
Je ne pense pas que l'on puisse maintenir une notification aussi longtemps (et je sais même pas si on a un réel contrôle sur la durée) ^^

**Comment by kris06** [comment]
dans ce cas, essayez de rappeler cette notification à chaque ouverture de kodi 
allongez aussi le délais d'affichage si possible

**Comment by sizanic** [comment]
Pour la mise à jour automatique, si on ne le fait pas c'est surtout que cela necessite une grande charge de travail pour construire les versions majeures.

Quelqu'un doit si coller, et en plus il n'y plus qu'une personne qui sais le faire.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2726

De plus on veut garder un controle humain pour s'assurer qu'au moment de le faire que la version est stable.
Si on l'automatise (genre tous les 15 jours), une version instable peut être déployée à tort.
Une version instable peut arriver car tout le monde à droit de modifier le code :) 

@Arias800  si tu veux pas que la mise à jour écrase ton code, il faut la désactiver :)

Je penche pour la notification au lancement de KODI.

**Comment by sizanic** [comment]
Je propose de continuer se sujet ici : #2745 

Car je vais bientôt cloturer cette issue.

**Comment by Arias800** [comment]
@sizanic au lieu d'utiliser la lib urllib dans les fichiers site il vaut mieux utiliser les fonction commune a Vstream qui se trouve dans le fichier util (ligne 225 a 241). Elle font la même chose, a la différence que lors du passage en python 3 au n'aura plus a modifié les fichier un par un car tout les appel au fonction serons centralisé. ^^

**Comment by sizanic** [comment]
Je suis d'accord.
J'ai vu ces fonctions au moment du commit du dernier fichier, c'était trop tard.
Je referai une passe pour modifier.

Et pour urllib2, on fait quelque chose ?

**Comment by Arias800** [comment]
J'ai prévu de rajouter les fonctions d'urllib 2, faut juste que je trouve un moyens efficace de le faire ^^

**Comment by kris06** [comment]
je vois que les choses avance,, même si les mises à jour intermédiaires ne sont pas prête de voir le jour,, la notification  à l'ouverture de kodi sera déjà une belle avancée.
merci pour votre travail.

**Comment by TmpName** [comment]
D'ailleurs a ce sujet @Arias800 toi qui a deja commencé a regarder, pour la migration.
On va pouvoir rester sur urllib ou devoir tout changer et du coup passer a request ?

**Comment by Arias800** [comment]
Alors du coter d'urllib ça ne devrai pas poser de problème, surtout si on regroupe les fonction entre elle. Par contre la où ça me fait peur c'est l'encodage, pour ça on va pleurer pour trouver un équilibre entre python 2 et 3 xD

**Comment by TmpName** [comment]
Et c'est la que me dit que ca va etre utile le tuto de @sizanic , trop de mauvais souvenir avec ca....

**Comment by Arias800** [comment]
Oui c'est sur, après dans mon fork il y quelque chose de plus ou moins fonctionnel, donc on a déjà une base xD

**Comment by TmpName** [comment]
A ce sujet @Arias800 j'ai un code qui marche en python3 mais pas en python2 ^^.

Si tu vois le probleme, VSlog(torrent) = none.

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/disneyhd_tk.py

Surement au niveau du format du fichier telechargé.

**Comment by kris06** [comment]
Salut il faudrait m'expliquer pourquoi tout a coup et depuis votre mise a jour 0.7.7  on ne retrouve plus rien à partir de la recherche sur zt tirexo

Zt étant indisponible sur vstream en raison d'un changement d url que vous n avez pas mis a jour ,
j ai pris soins de la changer moi même. Cette adresse est desormais
https://www2.zone-telechargement.monster 

Cependant, je  constate que la liste des films par catégories  est accessible mais aucune recherche
 n'aboutissent...

Cette nouvelle  url  n est pas un clone et pour cause,  je retrouve à  partir  de mon compte sur le site  zt en question, tous les films que je partage...

**Comment by sizanic** [comment]
Salut @kris06 ,

On a passé tirexo en '.monster' il y a 4 jours, mais était encore en 'www'.
La version 0.7.7 a 3 jours, avec cette correction d'adresse.

Si aujourd'hui ils sont passés en 'www2', qu'est ce que tu veux qu'on t'expliques !?
Qu'on va pas assez vite ? désolé.

> j ai pris soins de la changer moi même

Bah non, je vois pas ta modif : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/tirexo.py


Si quelque chose ne marche plus, ne demande pas d'explication : 
corrige-le toi-même.

On fait du développement communautaire ici !

Si tu n'as pas les compétences d'apporter la correction pour les recherches,
=> ouvre un nouveau sujet.

Tu avais ouvert ce sujet, à la recherche de TITANIC.
Après correction, on le trouvait bien.
=> Ce sujet est donc résolu !
On va le cloturer.

**Comment by kris06** [comment]
Je suis désolé que tu le prennes comme cela mon but n’étais pas de réprimander qui que soit et si je t’ai blessé je m’en excuse

Je voulais juste t’(vous) informer que la recherche partir de tirexo ne fonctionne plus ce qui est gênant surtout lorsqu’on possède tout un catalogue enregistré dans le marque page…

Ca ne me dérange pas de faire de corriger moi-même de l’url maintenant que tu m’a fourni le chemin

Cependant je m’interroge de savoir si  la mise à jour de l url suffit à remettre en service tous les services de tirexo puisque la fonction recherche ne marche plus… ??
Si tu peux m’en dire plus je te remercie

Bien à toi
Kris

**Comment by sizanic** [comment]
oui, je sais que tu ne voulais pas être blessant.
Mais ce n'est pas de la faute de la 0.7.7.
C'est juste que le site a changé dans la même période.

N'hésite pas à faire la modif du lien, tu peux éditer le fichier.
Si tu ne peux pas l'enregistrer, fais un pull request.
Un "admin" le verra.

**Comment by TmpName** [comment]
Perso je ne regarde jamais cette source, mais c'est recent ce changement regulier d'url ?
ZT a un systeme de changement automatique de host, ce serait utile ou pas ?

**Comment by sizanic** [comment]
Tu devrais la regarder, elle est pas mal.

Si je regarde les derniers changements d'adresse (ceux qu'on a mis à jour, on a pu en louper) : 
05/03/20
01/03/20 https://github.com/Kodi-vStream/venom-xbmc-addons/commit/da69cb82acc0cc39d5fe0f0e3d684cc145aa3846#diff-81630a44ab993887374263566538b0b3
22/02/20 https://github.com/Kodi-vStream/venom-xbmc-addons/commit/5c67f40454283ab2b179d8225c6b49ac7e3f1605#diff-81630a44ab993887374263566538b0b3
09/02/20 https://github.com/Kodi-vStream/venom-xbmc-addons/commit/69d7454bd1c7ec3d9b3dc04566b9840e4fa1611f#diff-81630a44ab993887374263566538b0b3

=> soit 2 fois par mois.

Je pense en effet qu'on peut mettre en place le système de changement de host par "setting" (si c'est bien à ça que tu penses).

**Comment by TmpName** [comment]
Yep, c'etait ca, mais je passe jamais par ZT non plus ^^, donc niveau efficacité je sais pas si ca vaut le coup.

**Comment by Arias800** [comment]
Mis en place, on verra bien si ça améliore les choses.
