### ISSUE TITLE
LiveTv (Beta version): Accelerer l'interface

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2733]
Bonjour @sizanic 

Je viens de finir la version beta de LiveTv selon "mes besoins". :)
Cette version utilise multi-threads pour resoudre les liens et  les afficher directement sans besoin l'affichage de la page "showHosters". 

Le script suivant est besoin pour multi-threads
 "script.module.futures"

Merci

Code:
h t t p s://pastebin.com/FbuDJ3hJ

**Comment by sizanic** [comment]
OK, je regarde ça ce soir.

Tu peux m'en dire plus sur "tes besoins" ?
Pour une meilleure intégration dans un skin, quelque chose comme ça ?

**Comment by sviet2k** [comment]
Mes besoins: Afficher le plus vite possible les liens valides.
Ex: Je deteste de cliquer une dizaine de fois pour avoir enfin un lien valide. :)
Dans Vstream, j'avoue que je n'aime pas la page "ShowHosters". Selon moi, c'est plus convivial d'afficher la page de matches, puis la page des Liens Direct et joue le lien.

**Comment by sizanic** [comment]
Je m'en doutais que c'était pour afficher le premier lien valide.
Sauf que chercher ce lien valide c'est masquer le vrai problème.

Il aurait été mieux de réparer les liens invalides.
C'est ce que j'ai fait sur la dernière version.

Je vais faire un tuto pour expliquer comment développer le décodage des liens liveTV, pour les prochains liens invalides.


Je vais regarder avec attention ce que tu as fait pour voir si on peut l'appliquer de façon générale dans Vstream.

**Comment by sizanic** [comment]
J'ai pas réussi à importer "script.module.futures".
Alors je l'ai supprimé pour tester quand même (en simple thread).

Je comprends pourquoi tu mets en place un multithread.
Tu essayes de résoudre tous les hosters !
Et tu ne proposes que ceux qui fonctionnent.

En réalité, tu affiches la page hoster, mais elle ne contient que ceux qui sont résolus.
Je pense qu'on peux perdre en fluidité si il y beaucoup de hoster.
Alors qu'on ne gagne pas en navigation.

Dans le même genre et plus fluide, je partirai plus sur une méthode qui vérifie seulement le nom du hoster sans essayer de le résoudre :
On liste les hoster ['footballreal.xyz', 'dailydeports.pw', ...]
Et on check que l'url contient un des hoster, sinon on le retire.
Donne le même résultat en plus rapide.

Et si au moment de lancer le hoster, on ne sait plus le résoudre (code obsolete car le site à changé), et bien il faut se relever les manches et le corriger.
Sinon on masque le probleme, la liste des résultats diminue tout doucement sans qu'on s'en apercoivent, et un beau jour il n'y a plus résultats !

**Comment by sviet2k** [comment]
La liste des hosters est une bonne solution mais c'est tres laborieux et ennuyant de maintenir correctement la liste des cinquantaines des noms des hosts. C'est a eviter cette solution.

Pour la qualite de decodage,  on doit creer des "Unit Test" au lieu de tester manuellement en cliquant les liens. Mais si tu veux, tu peux afficher aussi des liens invalides. (Je veux pas afficher les liens invalide dont je masque ces liens). En plus La Liste ne resoudre pas le probleme de faire perdre a l'utisateur beaucoup de minutes et de click pour pouvoir trouver un lien valide. Ex: Cinemay affiche 10 liens gounlimited mais juste un lien qui est valide.

Avec multi threads = 10, on perd une seconde pour resoudre les 10 liens. Je ne vois pas comment ca va nuire a la navigation. Personnelement, je suis pret a attendre 2,3 seconds de plus pour recevoir les  liens valides au lieu d'afficher 50 liens non-resolus en une seconde.

C'est dommage si VSTream n'utilise pas le multi-thread pour accelerer la navigation comme les autres add-on des series americaines.

**Comment by TmpName** [comment]
Malheureusement on a deja testé, pas fiable.

- certains site demandent un decodage pour acceder aux liens finaux (avec tempo)
- certains hebergeurs demandent plus de "1 secondes" pour etre sur , et apres 30/40s quand ca demarre, on a encore un message d'erreur apres. Pour avoir tout les liens j'ai du passer mon timeout a 60s.
- les hebergeurs bloquent les connexion multiples, donc certains ne vont pas permettre de tester 10 de leurs liens en une fois.

Gounlimited est treeeeees lent, il me plante meme kodi a certain moment, donc je me vois pas lancer 10 requetes dessus en plus de ca en multi-thread vu la stabilité de kodi.

**Comment by sviet2k** [comment]
C'est dommange qu'on ne peut pas appliquer multi-thread pour VStream.

Personnelement, j'ai applique multi-thread pour un addon (series americaines) et ca marche tres bien. (Le site WatchSeries retourne une centaine de liens pour une episode :) et le addon prends 4,5 secondes pour retourner les 15 premiers liens valides)

Merci pour votre temps 👍

**Comment by TmpName** [comment]
Les americains ont de meilleurs serveurs que nous ^^.

Depuis la derniere razia, ca pique pas mal. openl..d me manque

**Comment by yodidon** [comment]
Il faut se mutualiser et herbeeger 😱

**Comment by TmpName** [comment]
Tu te proposes comme hebergeur ?
Tu prend les paiements en pizza ?

**Comment by yodidon** [comment]
Alors une semaine pizza, une semaine kebbab....

Envoyé de mon iPhone

**Comment by sizanic** [comment]
@sviet2k  Pour LiveTV en tout cas je suis contre.
C'est vrai qu'il y à 15 jours, il fallait se taper 15 liens invalides pour trouver un match.
Et au final on se retrouve avec une retransmission en russe.

Avec ta proposition, on exclut les premiers liens et on va tout de suite sur la match en Russe (mais peut-être que c'est ta langue recherchée).
Et puis quand on ne saura plus décoder le match en russe, on se retrouvera avec des commentaires chinois.
Jusqu'au jour où on aura plus rien.

Je préfère corriger les premiers liens pour avoir un match en bonne qualité et en français.

Et j'ai l'impression que tu as le niveau pour ça.
Alors aide-nous à maintenir l'addon :)

**Comment by sviet2k** [comment]
Je pense que tu ne comprend pas mon code. Le but de mon code est identifier tout de suite les Hosts resolus (i.e. les Hosts que vstream est capable de resoudre: peut etre les machs en francais ou anglais ou russes ...) et les Hosts non-resolus. Mon code n'elimine rien. Il montre juste la capacite de resoudre les Hosts de liveTV. Et a partir de la, tu peux afficher seulement les hosts resolues ou aussi les hosts non-resolues ave couleur difference. 

En tous cas, personnellement, j'uilise pas le livetv si je dois clicker 20 fois pour pouvoir voir le match.

**Comment by sizanic** [comment]
Je comprends très bien.
Et je dis que ton code n'est pas utile si tous les hosts sont de la même couleur parce qu'ils sont tous résolus. Parce ce qu'on va s'appliquer à toujours corriger ceux qui ne fonctionnent plus.

Maintenant l'idée de la couleur est bien comme ça on sait ceux qui fonctionnent plus et qu'il faut corriger :) 
J'ai corrigé beaucoup de host dernièrement et tu ne devrais plus devoir cliquer 20 fois.
Je vais publier un TUTO sur comment corriger les hosts LiveTV et je compte sur toi pour en développer.
