### ISSUE TITLE
Bug Source 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2736]
**Décrivez le bug**
_Je referais un checkup ce weekend pour mettre a jour les bugs (même si je pense qu'il n'y a plus trop de souci depuis le bon travail de Arias800)_

Je supprime au fur et a mesure les bugs corrigés pour ne laisser que les bugs à corriger.

DERNIER COMMIT EN DATE INSTALLÉ EST CELUI DE 0vni-Crea **_74af047a_**

En cherchant la saison 6 de Vikings j'ai rencontré les problèmes ci-dessous:

- **tvseriestreaming** : pas de lien host dans les dossiers des épisodes 
- **Adkami** : pas de lien host POUR LES SERIE (difficile à scraper)
- **Dpstreaming.cx**  : lien host prostream ne fonctionne pas

**Votre system**
 - OS: [Windows, Android]
-  Appareil [PC, Z6+]
 - Version Kodi  [17 et 18]
- Version Vstream 0.7.6

**Comment by gratoQ** [comment]
la mise a jours a fait disparaitre le site docu_fr alors qu'il fonctionne

**Comment by tuego72** [comment]
je viens de faire la maj et zone telechargement ne fonctionne plus et il fonctionnais juste avant

**Comment by gratoQ** [comment]
@tuego72 pour zt et tix #2731

**Comment by TmpName** [comment]
@tuego72 je viens de tester, j'ai encore ces 2 sources de mon coté ?

**Comment by Che-debarras** [comment]
J'ai mis a jour comme dit dans mon poste et les 2 sources docu .fr et wiflix sont bien visible et pour moi ZT fonctionne également

**Comment by tuego72** [comment]
@gratoQ  c'est quoi ton problème? Je reporte un problème dans Issues c'est à ça que ça sert non

**Comment by spank-max** [comment]
Bonsoir, maj effectué: zt et tirexo re-fonctionne. wiflix et docu.Fr sont visible. Merci a vous
Test effectuée depuis une box tv sous android 9

**Comment by tuego72** [comment]
il fonctionne maintenant y a du avoir un bug avec le site dsl

**Comment by gratoQ** [comment]
j'ai du refaire la mise a jour pour que les sites apparaissent.

**Comment by razorex** [comment]
Pour  Series-Streaminghd et Planet streaming les liens sur le sites aussi ne fonctionnent pas.
tvseriestreaming  est désactivé.

**Comment by Arias800** [comment]
Du coup Tirexo est corriger ^^

**Comment by TmpName** [comment]
Je viens d'ameliorer "tvseriest reaming".
Ca marche mieux, mais j'ai pas tout testé.

**Comment by TmpName** [comment]
Dpstreaming a fermé donc reste plus que adkami a regarder ?
