### ISSUE TITLE
ZT probleme 

### ISSUE THREAD

**Issue by christophe006** [Kodi-vStream/venom-xbmc-addons#2737]
Depuis la derniere MaJ auto de vstream qui date de hier (16/02) ZT ne fonctionne plus du tout.
Aucun lien n'apparait tout simplement.
Sur Kodi 18 et avec la version precedente de vstream tout fonctionne correctement.

**Votre system**
 - OS: Android
-  Appareil : Android box Beelink
 - Version Kodi  : SPMC
- Version Vstream : derniere MaJ

**Comment by Che-debarras** [comment]
Ya un sujet sur le bug source, je pense qu'il ne faut pas créer d autre surtour sur zt et tirexo car c'était déjà signalé.

**Comment by sizanic** [comment]
Probleme suivi ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2720
