### ISSUE TITLE
Comment developper/tester VSTream sans Kodi

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2738]
Salut les copains, :)

J'aimerais partager avec vous ma facon de developper ou tester les addon.
Mon approche est de "mock" tous les methodes non-besoin (xbmc, xbmcgui etc...)

Ex: Je veux developper multi-thread pour liveTv.
Je creer un fichier vstream_mock.py qui contient toutes les fonctions que je n'ai pas besoin. Ex: cHosterGui, cGui etc ...
h t t p s://pastebin.com/kXp13rDV
Note: Ce fichier est aussi re-utilise pour developper les autres vstream sites.

Je creer un py fichier qui contient seulement showMovies3 and showHosters que je veux modifier.
h t tp s://pastebin.com/kKYTCuHw 
Dans ce fichier j'importe vstream_mock comme suit:
from vstream_mock import cGui, cInputParameterHandler, cRequestHandler, cParser, cOutputParameterHandler, cHosterGui, progress, VSlog

Et a la fin du fichier, j'execute les deux fontions pour developper/tester (utilise debug in eclipse)
showMovies3()
showHosters()

J'espere que c'est utile pour la communaute.

Merci

Example de test:
Tester ce LiveTv lien: h t tp://livetv.sx/frx/eventinfo/905345_chateauroux_lens/

Voici les liens decodes:
h t t p://78.142.19.38:8080/hls/streama118273/index.m3u8?st=0F6Z2Nnl5msZ2XiVQP5-kw|User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0&referer=h  ttp://emb.apl4.me/player/live.php?id=118273&w=700&h=480

h t t p://185.233.186.251:8080/hls/streama117978/index.m3u8?st=8dZjwpdMxbvNSMfFVy2oHw|User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0&referer=h t tp://emb.apl4.me/player/live.php?id=117978&w=700&h=480

h t t p://78.142.19.55:8080/hls/streama117974/index.m3u8?st=IsTFWklzVsUgFMOLhvkOMA|User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0&referer=h ttp://emb.apl4.me/player/live.php?id=117974&w=700&h=480

h t t p s://telerium.tv/ingest09/33412.m3u8?sf=MTVwczEwU2JE&token=yDDSSxtlCFfvv7O6lE1LNw&expires=1581974967&rnd=33412|referer=h t tps://telerium.tv/embed/33412.html

**Comment by sizanic** [comment]
OK mais du coup, sans KODI, tu peux pas voir le résultat : 
- le titre qui s'affiche bien
- la pochette
- etc.
Et surtout :  lancer la vidéo !

**Comment by sizanic** [comment]
Avec ma méthode (avec Kodi), je peux passer en DEBUG à la volée pendant que KODI est lancé.
Puis le désactiver pour continuer sans.

Une discussion ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2727

**Comment by sviet2k** [comment]
Cette methode a le but de developper et tester la logique du addon et non l'integration de l'addon avec Kodi gui. En tous cas, c'est une autre methode pour developper un addon pour les personnes qui ne veut pas faire des clicks sur kodi pour corriger un bug de logique ou ameliorer le code.

En plus, cette methode peut te donner l'option de developper un test rapide sur la qualite de toutes les sites de vstream avec un seul py. Tu roule ce test une fois par jour pour avoir les informations suivantes:

- Nombre de sites que Vstream peut afficher les series/movies
- Nombre de sites que Vstream peut afficher les episodes
- Nombre de sites que Vtream peut faire la recherche
- Nombre de liens par episode par site que Vstream peut decoder
- Quel hosters ne fonctionnent plus
etc ...

J'assume il n'y a uncun test pour addon vstream. C'est fort possible que je suis trompe.

**Comment by TmpName** [comment]
Moi, je vais encore faire le vieux con, mais j'aime bien le coup du fichier mock.

Pour la methode de @sizanic, j'ai pas encore testé, ca l'air lourd (j'aime bien les trucs rapides) mais ca a l'air trop beau pour etre possible.

**Comment by yodidon** [comment]
Je crois que la méthode de @sizanic  et vraiment bien surtout quand on apprend enfin si j’arrive à la mettre en œuvre je sent que j’y suis presque ....

**Comment by TmpName** [comment]
Yep, pour les debutants, c'est le top.
Faut que je m'y penche, rien que pour la curiosité.

**Comment by sizanic** [comment]
Un tuto ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2739

faite-moi des retours.
