### ISSUE TITLE
DisneyHD

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2741]
Salut,
qq'un pourrait regarder la récupération des liens hosters 
ex: [la bande a picsou](https://disneyhd.cf/s-541)
merci

**Comment by TmpName** [comment]
Suis dessus

**Comment by TmpName** [comment]
Heu, alors du coup j'attend confirmation de quelqu'un d'autre.
Mais les videos de ce site sont recuperée par p2p, donc pas vraiment secure.

Du coup j'ai laisse en pause pr le moment.

**Comment by sizanic** [comment]
A première vue, on pourrait croire en effet.

![image](https://user-images.githubusercontent.com/47307622/75096937-016b5e80-55a5-11ea-9b50-ea90f028a6c7.png)

Mais en cherchant un peu on devrait pouvoir retrouver la vidéo direct : 
 
![image](https://user-images.githubusercontent.com/47307622/75096953-37a8de00-55a5-11ea-83e4-c06fe4005da1.png)

exemple : 

h t t p s://d hd tks.ga/the_mandalorian/s1/101.mp4

**Comment by TmpName** [comment]
Ben j'ai pas compris comment marche leur truc.
C'est peu etre leur serveur qui fait le f2p alors ...

- Sinon a partir du lien magnet on peut recuperer le lien du torrent.
- A partir du fichier torrent on peux recuperer l'url du fichier (je suis passé par ht tps://w ww.tools4noobs.com/) a voir un code python pour faire pareil.

**Comment by Arias800** [comment]
Oui le site fonctionne en F2P, en réalité ils utilisent une technologie qui permets de lire des flux torrent comme des vidéo en streaming (pour plus d'info : https://korben.info/webtorrent-streamer-bittorrent-directement-vos-pages-web.html)

**Comment by TmpName** [comment]
Mais par contre l'url donnée par @sizanic fonctionne.
A croire que le site fait le f2p, et donne une url fonctionnant en http. J'arrive a avoir la video en utilsant juste le lien http.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
from urllib.parse import unquote
import bencode


file = open('html.txt','r')
mystr = file.read()
file.close()

match = re.findall('data-maglink="([^"]+)', mystr)[0]
match = unquote(match)

folder = re.findall('ws=(https[^&]+)', match)[0]
torrent = re.findall('xs=(https[^&]+)', match)[0]

print (folder)
print (torrent)

import urllib.request as ur
 
page = ur.urlopen(torrent)
torrent_data = page.read()

torrent = bencode.decode(torrent_data)
print("url-list: ", torrent[0][b'url-list'])
```

**Comment by TmpName** [comment]
Put1 on se croirait au taff, on vient de m'assigner du boulot ...

Sinon je continu mes tests, mais je vois toujours pas pourquoi on a ce resultat ...

**Comment by TmpName** [comment]
Bon ben ca marche
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


#https://dhdtks.ga/la_bande_a_picsou_1987/s3/301.mp4
#https://dhdtks.ga/la_bande_a_picsou_1987/301.mp4

import re
from urllib.parse import unquote
import bencode


file = open('html.txt','r')
mystr = file.read()
file.close()

match = re.findall('data-maglink="([^"]+)', mystr)[0]
match = unquote(match)

folder = re.findall('ws=(https[^&]+)', match)[0] + '/'
torrent = re.findall('xs=(https[^&]+)', match)[0]

print (folder)
print (torrent)

import urllib.request as ur
 
page = ur.urlopen(torrent)
torrent_data = page.read()

torrent = bencode.decode(torrent_data)

files = torrent['info']['files']
name = torrent['info']['name']

for i in files:
    print (folder + name + '/' + i['path'][0])
```

Ca donne une liste de fichier a lire en http, testé pour picsou, je comprend plus rien ...

Je vais essayer de l'integrer au code de Vstream

**Comment by Arias800** [comment]
@TmpName j'ai une version fonctionnel, par contre j'ai du changer le remplacer le code que tu utilisais pour les fichiers torrent : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/disneyhd_tk.py

**Comment by TmpName** [comment]
Bon ben j'ai fais 2/3 tests c'est fini je pense du coup.

Par contre tu comprend toi comment ca marche ? d'un fichier torrent on se retrouve a faire du ddl ?

**Comment by Arias800** [comment]
A mon avis c'est un liens ddl qui a été convertie en torrent. La 1er personne qui se connecte récupère le flux du serveur (elle lit le fichier comme un fichier de ddl classique) tout en le streamant, et lorsqu'une autre personne ce connecte, elle recois le flux de la personne précédente comme un système de p2p classique. Mais après c'est que mon hypothèse.

**Comment by sizanic** [comment]
Je comprends pas, on est pas censé récupérer un fichier .mp4 ?

**Comment by Arias800** [comment]
C'est bien ce que le code fait. Ce que j'ai expliquer c'est la manière dont fonctionne le site. Nous ce qu'on fait c'est qu'on récupere le lien torrent, on le décrypte et on reconstitue les liens mp4

**Comment by TmpName** [comment]
Donc au final on fait du DDL,, mais a partir d'un lien torrent, la je comprend pas du tout comment ca marche.
Hier j'ai essayé de passer par le torrent, et y a tellement peu de source que ca bouge pas, c'est impossible de passer par du p2p pour ce genre de video.
