### ISSUE TITLE
vstream et openvpn

### ISSUE THREAD

**Issue by jackleinad** [Kodi-vStream/venom-xbmc-addons#2742]
Description
Quand openvpn(zomboided) est lancé les recherche avec vstream sont impossible ou Ultra lente.

Mon système
 - OS:  LIBREELEC 9.2.0
-  Appareil : Raspeberry pi4 B
 - Version  KODI 18
- Version Vstream 0.7.6

Je vais essayer du vous faire log. sinon openvpn (vpn hidemyass dans mon cas) fonctionne bien avec tous le reste de kodi : iptv 
Ca plante uniquement sur les extensions comme vstream ou youtube .
le seule moyen que j'ai trouvé et de coupé le vpn lors de l'utilisation de ces extensions (sniff)

Avez vous une idée ?

Merci d'avance

**Comment by sizanic** [comment]
Non, perso, pas d'idée.
As-tu avancé sur ton diagnostique ?
Es-tu toujours coincé ?

Je n'utilise pas de VPN pour Vstream.
Je ne suis pas persuadé de l’intérêt d'un VPN.

**Comment by Arias800** [comment]
Au pire tu peut reproduire le bug et nous donner les logs pour voir si il n'y a pas un blocage quelque part ^^

**Comment by jackleinad** [comment]
Bonsoir merci pour vos réponse je pense avoir réussi a faire un log voici le lien : https://slexy.org/view/s2NXzlgefX
j'ai activer le vpn sur le log 17/03/20 a 20h06 et j'ai lancé une recherche qui a durer des lustres.
Alors que juste avant j'ai fait la mème recherche qui a prit 5 min.
Merci d'avance pour votre aide

**Comment by TmpName** [comment]
Ha wé quand meme ^^.
Alors deja pas de bol, y a pas d'info qui expliquent pourquoi c'est aussi long.
2020-03-17 20:35:14.167 T:2516661104  NOTICE: 	[PLUGIN] Vstream: Load Recherche: stremingdvx
2020-03-17 20:36:17.986 T:2516661104  NOTICE: 	[PLUGIN] Vstream: Load Recherche: stramingk_com

On voit juste que la recherche a duré 3 mn.

2 questions sinon:
- Les resultats ont marché ? pour savoir si c'est lent ou inaccessible.
- A un autre moment de la journée, ca marche sans probleme ?

Franchement j'ai beau comparer entre un site rapide libertilnd et un lent, je ne vois pas pourquoi ca changerait.

**Comment by jackleinad** [comment]
Bonsoir pour répondre au deux questions
1)Quand je lance une recherche avec le vpn activé j'ai pas de résultat sur chaque site.
2)Peu importe le moment de la journée le résultat est le même.

**Comment by TmpName** [comment]
Ok donc ca doit etre car les sites sont inaccessible ? Les sites les plus long sont ceux sans resultats ? Si c'est ca probleme de dns pour moi.

**Comment by jackleinad** [comment]
Salut je viens de refaire l'essai il faut environ 2 min pour scanner tous les sites lors d'une recherche sans vpn. Avec le vpn actif je passe a 11 min et quelques résultats en fonction des sites.
Pour le dns j'ai regardé dans les paramétrage j'ai rien vu. Je suppose que par défaut il utilise ce de google 8.8.8.8 et 8.8.4.4 . Comment je peux le vérifier sur kodi librelec ?

**Comment by jackleinad** [comment]
Sur leur page github :  https://github.com/Zomboided?tab=repositories
il y a un script de 2017 pour une histoire de config dns . je sais pas si c'est encore d'actualité ?

**Comment by TmpName** [comment]
Ben le vpn utilise le dns que tu as sur tu as configuré sur ta machine non ?
Ou ca passe par leur VPN aussi ?

**Comment by jackleinad** [comment]
Bonjour j'ai essayé de comprendre le fonctionnement du dns sur libreelec.
J'ai configuré ma connexion etehernet du raspberry4b en manuel IPV4 ma passerelle par def 192.168.1.1(box) et en dns j'ai mi ceux de google pour essai. dns1 8.8.8.8 et dns2 8.8.4.4.
J'ai retenté une recherche d'un film sous vstream avec le vpn activé le résultat est identique
(recherche ultra lente avec des résultats variable au niveaux des sites de stream)
Après je ne sais pas comment Zomboided (openvpn) configure ma connexion vpn (hydemyass).Dans l'interface graphique je vois rien de paramétrable au niveau dns .  
J'ai essayé avec putty en shh de lancer les commandes ifconfig et iwconfig . la première fonctionne mais la second non. Je suis novice avec Linux. 
Je ne sais pas accéder au dossier /storage/.kodi/addons/service.vpn.manager/
car il devrait y avoir les fichier location.txt et append.txt qui je pense me permettrait une fois modifié d'avoir le dns souhaité sur le vpn.

**Comment by yodidon** [comment]
En ssh tu n’arrive pas jusqu’au dossier ?

**Comment by jackleinad** [comment]
ben non yodidon mais je m'y prend peu être mal aussi je vais faire une copie d'écran. un instant

**Comment by yodidon** [comment]
Ok

**Comment by jackleinad** [comment]
https://zupimages.net/up/20/15/agp8.jpg
ben j'y comprends rien la ca fonctionne pour le premier dossier?

**Comment by jackleinad** [comment]
je trouve pas les fichier txt location et append.txt
https://zupimages.net/up/20/15/inpf.jpg
la le deuxième chemin d’accès ne fonctionne pas

https://zupimages.net/up/20/15/b2j0.jpg
doc en anglais ici https://github.com/Zomboided/service.vpn.manager/wiki/09.-User-Defined-VPNs

**Comment by yodidon** [comment]
Mais tu utilise un addon spécifique pour ton vpn ?

**Comment by jackleinad** [comment]
oui zomboided openvpn

**Comment by yodidon** [comment]
Je n’ai pas de confirmation donc rien de sûr mais as tu regarder dans le dossier de l’addon

**Comment by jackleinad** [comment]
juste la https://zupimages.net/up/20/15/inpf.jpg

**Comment by yodidon** [comment]
Vas jusqu’à /addons/ et fait un ls

**Comment by yodidon** [comment]
Et si tu galère sur ssh tu dois pouvoir accéder à ton libreelec directement en montant le disque sur ton réseau

**Comment by jackleinad** [comment]
ok
https://zupimages.net/up/20/15/s5qs.jpg

https://zupimages.net/up/20/15/yrwr.jpg

voila

**Comment by yodidon** [comment]
Pour te simplifier la vie , active smb sur ton Kodi et tu verras ton disque libreelec sur Windows comme un disque standard

**Comment by jackleinad** [comment]
voila https://zupimages.net/up/20/15/eabt.jpg

**Comment by yodidon** [comment]
Difficile de t’aider je n’ai pas de vpn, je vais me renseigner

**Comment by jackleinad** [comment]
ok super merci . Mais il y a pas d'urgence.

Merci pour ton aide

**Comment by jackleinad** [comment]
Bonjour j'ai essayé de tester la connexion du raspberrypi 4b (vpn actif)
je vous ai fait une petite vidéo avec des cmd linux sous putty.
https://1fichier.com/?9b8bqspazay0ra6pn2n3  mot de passe : vstream
