### ISSUE TITLE
Temporisation du défilement des informations

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#2744]
Pourriez vous corriger la temporisation du défilement sur les informations des films ? Il est presque impossible de pouvoir lire les résumés tellement ce défilement est rapide.

L’ouverture d’une simple fenêtre plus LARGE que celle proposée, permettrait d’afficher l’intégralité des résumés, ou voir même de laisser à l’utilisateur la liberté de pouvoir dérouler lui-même ce résumé avec son navigateur…

**Comment by TmpName** [comment]
Ca c'est pas qui geront, mais kodi, suis pas sur que ce soit reglables et peut etre meme que ca depend des themes.

**Comment by kris06** [comment]
![Screenshot_20200222-165400_Kodi](https://user-images.githubusercontent.com/31409100/75095406-9580fa00-5594-11ea-9ad9-99a5c6919d28.jpg)

**Comment by TmpName** [comment]
Ok, donc c'est bien celui la.
Par contre je vois pas le plus large ?

Ca se trouve dans le fichier DialogInfo2.xml.

Et je pense qu'il ya moyen de modifier les reglage du scrolling
>autoscroll time="3000" delay="4000" repeat="5000">true</autoscroll>

**Comment by kris06** [comment]
Merci pour tes infos je ne te caché pas quelles sont trop techniques pour moi.

Je faisais remarqué précédemment qu'une fenêtre plus large résoudrait l'affichage minimaliste des résumés.

 En effet ces 4 lignes oblige un défilement du texte alors qu'il me semble  pas nécessaire.  Une fenêtre large présentant lle résumé d'un coup serait plus judicieux.
 La capture  que je t ai  envoyé évoque suffisamment mon raisonnement. 
Pourquoi consacré les 3 quarts de l'écran pour une image alors que c'est l'information du résumé qui nous intéresse ici, résumé illisible  en raison d'un ddéfilement trop rapide.....

**Comment by kris06** [comment]
j'ai essayé de modifier les paramètres  que vous m'avez indiquez (autoscroll time="3000" delay="4000" repeat="5000">true)  
mais cela ne change rien curieusement,  je cherche encore..

**Comment by TmpName** [comment]
Alors pour info, on avait bidouillé un hack qui affiche la page de resumé en premier, car c'etait la page qu'on preferait.
C'est l'id 36 > ligne 627

Je pense qu'il faudrait virer la ligne
`<scroll>false</scroll>`

Et le rajouter par la, faut s'inspirer du code deja en place.

Mais en fait quand tu parlais de largeur, chez moi c'est une hauteur.

**Comment by TmpName** [comment]
@kris06 alors je comprend pas, tu m'as mit le doute, du coup j'ai fais la meme recherche pour le meme film, et chez moi tout est affiché, j'ai meme de la marge.
Tu as quoi comme resolution d'ecran ?

**Comment by kris06** [comment]
j’utilise kodi sur 4 appareils

-mon téléviseur relié à ma freebox android mini4k  (resolution d'un téléviseur 1080x1920 )
-mon pc resolution 1600x900
-mon vidéoprojecteur équipe d'une interface android (résolution 1080x1920)
-mon téléphone android (1920x1080)

Pour ces 4 appareils,  les informations pour les films sont présentées comme l'image que je vous ai adressé aucune différence 

si le format de cette fenêtre d'information est gérée dans les paramètres dans vstream, vous devez pouvoir être en mesure d’améliorer ce défilement voir le faire disparaître au profit d'une fenêtre plus haute présentant les informations  dans sont intégralité. (pas besoin d'un  défilement inutile)

**Comment by TmpName** [comment]
Ben doit y avoir autre chose qui impacte le resultat car moi j'ai

![b1](https://user-images.githubusercontent.com/8311559/75365851-b8bde900-58b5-11ea-8ad9-977790b0ade6.jpg)

**Comment by kris06** [comment]
Ce sont les polices par défaut sur les 4 appareils 
Non ce n est pas qu'une ligne dans d autres résumés il y en a bien d'autres

**Comment by kris06** [comment]
Enfin l idée était de réduire le défilement trop raapide et qui rend difficile la lecture des  lnfos 

Si vous ne pouvez pas changer ce paramètre  changez la hauteur de la fenêtre et voilà tout

**Comment by Arias800** [comment]
J'ai trouver comment faire pour modifié la vitesse. J'ai doubler les valeurs, donc ça serai bien si tu peu essayer la beta et donner ton avis pour qu'on puisse ajuster.

**Comment by Arias800** [comment]
@kris06 La modification est suffisante ou c'est trop lent maintenant  ?

**Comment by kris06** [comment]
Bonjour c'est parfait je re remercie. Et merci également pour le 1er clic de tirexo.

Quand aurons nous le retour de  tirexo et zone qui sont depuis le confinement, hors service ?

**Comment by Arias800** [comment]
Normalement les sites en eux même fonctionne avec la dernière version de Vstream (Uptobox par contre va demander beaucoup plus de temps https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2793)

**Comment by kris06** [comment]
De quelle version de Vstream parles- tu  0.7.8 ?   

Je ne sais pas comment vous arrivez à faire fonctionner zone téléchargement, aucun lien ne fonctionnent, y compris le streaming sur tirexo  et ceci depuis le confinement.

**Comment by Arias800** [comment]
Oui, dans la 0.7.8 les sites fonctionnent, par contre Uptobox (et uptostream) eux ne marche pas.

**Comment by kris06** [comment]
Et bien non quel que soit l'appareil box Android PC  smartphone.. et meme avec en vpn aucun lien ne fonctionnement sur zone et tirexo  (kodi 18.6)

**Comment by Arias800** [comment]
Effectivement j'ai fait une correction de Tirexo après que la mise a jour 0.7.8. Donc du coup c'est normal, par contre zt devrai fonctionner. Il faudrait des log pour voir d’où peut venir le probleme.

**Comment by kris06** [comment]
Je veux bieb te les envoyer mais comment capturer ces log ? J'ignore le précéder...

**Comment by kris06** [comment]
Si ta correction concernant tirexo concerne l'un de ces 3 fichiers 
Tirexo.py
Tirexo.pyo
Tirexo.png
Je veux bien que tu puisses me les envoyer  je pourrais les intégrer 
Je te remercie

**Comment by TmpName** [comment]
Tu as toute les version ici https://github.com/Kodi-vStream/venom-xbmc-addons/commits/Beta/plugin.video.vstream/resources/sites/tirexo.py

Et tu peux meme voir les dernieres modifications pour etre sur de les avoir.

**Comment by kris06** [comment]
merci, j'ai repris les 1057 lignes de mise à jour de tirexo par arias800 que j'ai remplacées dans le fichier tirexo.py  mais ca change rien, aucun lien ne demmarre..

**Comment by Arias800** [comment]
Pour donner les logs c'est facile :
- Tout d'abord il faut reproduire le bug
- Ensuite il faut allez dans les paramètre de Vstream et selectionner "Upload Kodi Log".
- Il ne reste qu'a nous communiquer l'ID qui est afficher dans le popup.

**Comment by kris06** [comment]
logs
zone téléchargement    http://slexy.org/view/s20t1ryBBZ
tirexo                             http://slexy.org/view/s208WbqBFY

**Comment by Arias800** [comment]
Le problème c'est bien Uptobox et Uptostream qui ne fonctionne pas, c'est normal vu qu'ils ne sont pas encore réparer (voir ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2793)

**Comment by kris06** [comment]
autant pour moi,  je répondais à ton message  :
(Normalement les sites en eux même fonctionne avec la dernière version de Vstream (Uptobox par contre va demander beaucoup plus de temps #2793)

Je vais être patient, merci  beaucoup de tes infos
