### ISSUE TITLE
Notification pour les mises à jour manuelles

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2745]
> Demande de @kris06 

Si selon vous la mise à jour  intermédiaire automatique  n'est pas souhaitable pourriez-vous dans ce cas développer une notification à l'ouverture de kodi et non à l'ouverture de vstream.?

En effet, nous sommes très nombreux à utiliser vstream à partir des sources enregistrées dans les favoris si bien que nous ne pouvons observer votre notification habituelle.

Aussi, il serait utile de forcer l’affichage de cette notification et ne pas la faire disparaître jusqu'à l'exécution de ladite mise à jour…

Je me tue à dire sans cesse à mes amis qu'il doivent  ouvrir vstream pour procéder à cette opération, si opération il y a... !

Enfin vous avouerez quand même que la  mise à jour intermédiaire automatique réglerait une fois pour toute cette histoire qui suscite l'incompréhension de nombreux utilisateurs et qui pour certains, se perdent à vouloir mettre à jour !'addon de vstream pensant ici avoir réglé l'ensemble des opérations...

_Originally posted by @kris06 in https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2732#issuecomment-589955276_

**Comment by sizanic** [comment]
> Idée de @Arias800 

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2732#issuecomment-589959347

> Alors ce qui peut être tester c'est de basculer le code de vérification de la maj dans le service.py. Et logiquement ça devrai exécuter la vérification au lancement de Kodi ^^

**Comment by TmpName** [comment]
Ben le truc c'est que cette mise a jour n'est pas indispensable. Moi sauf quand je veut corriger le code je m'en sert pas, quand un site ne marche pas, j'en prend un autre.
En general, les MAJ auto sont a eviter, toujours attendre 1 semaine minimum, que les pressés fassent les cobayes avant d'en installer une.

Si la personne n'a pas de problemes pour ses films, elle a pas besoin de mette a jour, si elle a des problemes, elle le verra sans notifications.

Tu imagines ce que cela peut faire en traffic sur le serveur de github, juste pour mettre a jour des fichiers qui ca se trouve sont sur une machine dont la personne ne se sert meme pas de kodi.

Si cette mise a jour etait vitale, elle serait en MAJ complete et serait a 100% automatique.

**Comment by sizanic** [comment]
Je suis assez d'accord avec @TmpName 

Si on parle de ce sujet c'est parce que la dernière mise à jour complète était très ancienne (de novembre) et qu'il y avait eu de grosses corrections depuis.
Donc on essayes de se rabattre sur les mises à jour semi-auto.

Alors qu'il faut regler le probleme de base : proposer des maj complete et automatique plus souvent.
-> Mais toujours lorsqu'on est sûrs de la stabilité, après les tests par ceux qui installent les mise à jour intermédiaires.
-> on devrait être dans l'ordre du mensuel.

Le problème venait qu'il y a moins de personne pour s'en occuper.
Ca devrait aller mieux maintenant, c'est suivi par ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2726
