### ISSUE TITLE
Tester Vstream

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2747]
Bonjour @TmpName ,

J'aime bien contribuer un peu a vstream, l'unique addon en francais. 👍, selon ma capacite.
J'ai un code de test de Voirfilm (mon site prefere) qui me donne a peu pres si Voirfilm marche et combien de "Direct Link" que Vstream peut resoudre. En us seul mot la qualite de VoirFIlm.

Si tu as le temps et tu pense que c'est utile, je vais essayer de le faire plus generique pour qu'on puisse tester aussi les autres sites.

Mon Test Code est totalement independant avec Kodi. Je mock tous les modules qui a besoin Kodi comme comaddon etc,...

Merci

**Comment by sizanic** [comment]
Salut @sviet2k, 
ça m'interesse aussi.
Tu as une branche avec ton code ?

Peux-tu aussi revoir un peu le titre de ce sujet, il est trop générique :) 
Genre : "Test automatique des liens DirectLink"

**Comment by eco-plus** [comment]
alors @TmpName sera surement d'accord avec moi .
 - vstream n'est pas fait pour **bombarder** les sites internet de requêtes pour votre confort.
 - si vous voulez que les sites mettent en place **des systèmes de protection difficile ou impossible** à passer avec Kodi (recaptcha etc.. ) continuer comme ça.
 - je n'appelle pas ça contribuer...  

johngf

**Comment by sviet2k** [comment]
Salut @eco-plus ,

Ce test ne bombarde pas les sites. Il fait exactement les memes nombres de requetes qu' un utilisateur de Vstream pour un site. Ce test simule automatiquement les etapes d'un utilisateur:
Un requete pour avoir les series
Un requete pour avoir les saisons d'une serie
Un requete pour avoir les episodes d'une saison
Un requete pour avoir les hosts d'un episode etc ...
Et afficher les resultats de test pour chaque etapes.

Bien sur que mon design tienne compte les nombres de requetes. En plus, j'ai l'intention de mettre un sleep par etape de test pour ralentir au max les requetes.

Et plus important, ce test va etre utilise pour controler la qualite de vstream apres une modification ou un nouveau developement. On peut l'utilise aussi comme un outil de development pour vstream. Le but ultime de ce test est de renforcer la qualite de vstream. Ce n'est pas pour mon confort. Et bien sur, on ne roule pas ce test a chaque heure.
Avec ce design, je ne pense pas qu'il va 'nuire' les sites.

Je suis un peu surpris que tu assumes tout de suite que ce test est un 'avion de bombardement' de requetes :) sans connaitre les details.

**Comment by TmpName** [comment]
Ben ce qui doit choquer @eco-plus c'est que voirfilm (qui est aussi mon site preferé en passant ^^) n'affiche pas une liste de liens finaux.
A chaque fois l'utilisateur doit selectionner un host, et a ce moment le site fait une requete pour avoir le lien.

Autrement dit dans la realité, il est tres rare que quelqu'un fasse plus de 2/3 requetes espacée de moins de 1mn, surtout si le lien n'est pas mort.

Donc je n'ai pas vu ton code, donc je ne m'avance pas, mais je craint aussi un "bombardement"

**Comment by sviet2k** [comment]
Je suis d'accord avec @eco-plus: c'est pas mal frustrant pour ne pas avoir les liens finaux dans voirfilm mais ce n'est pas trop difficile de corriger ca. Je vais  le voir ce soir.

T'as raison @TmpName que dans la realite, c'est 2,3 req par minutes max. Pour mon test c'est 15 sec par req -> a peu pres 5,6 req en une minute et demie. Je ne pense pas que le serveur du site va considerer ca comme bombardement. Mais on peut aussi augmenter a un req par minute et arrive a 5 minutes pour tester une serie. C'est un test automatique donc la performance n'est pas tres important.

Pour tester le decodage, j'utilise votre hoster.py et rouler ca sequentiellement. Pas a la chaine.

Voici un apercu du resultat du test pour cinemay (J'evite voirfilm :) )
Input est le lien Series de cinemay. Le test prend 'High Maintenance - Saison 4 EP 2' par hasard pour faire le test.

=== Test: Cinemay Found 31 Medias
=== Media: High Maintenance - Saison 4 (2/2) Run 2
High Maintenance - Saison 4 - showSeries - Found 1 Medias - [https://www.cinemay.li/series/18820-high-maintenance-saison-4.html]
S4E2  - showSeriesHosters - Found 1 Hosts - [https://www.cinemay.li/series/18820-high-maintenance-saison-4.html]
   From 1 Hosts Found 16 Hosts can be decoded
   Start decoding ...
      Not found: https://uptostream.com/iframe/yd95qfw8dkzw
      Not found: https://jetload.net/e/6VKfJVFZ5LP7
   Host OK: ['Allow_redirects', 'Frenchvid'], Error: []
   Non-Support Hosts: ['hqq.tv']

Je voudrais partager le code avec toi. Est ce que je peux donner le lien ici ou tu prefere que je t'envoie par email ?

Merci

**Comment by TmpName** [comment]
Avec qui ?

Pour info, on est pas systematiquement copain avec ces sites ^^. Je pourrais ecrire une petite histoire sur les protections qu'ils ont utilisé (la protection flash de kepliz, un autre site qui modifiait leur code en fonction de la modif qu'on faisait le jour meme (flash.tv), il y a meme une protection sur voirfilm qui donne de mauvais lien pour faire croire que le site est mort, qui ne nous concerne pas, sinon ils l'auraient deja corrigé, mais qui est la).
Vstream est une grosse machine, detrompes toi, si tu penses que ces sites nous ignore.

Sinon ton code est tres bien, mais de mon coté il y a deja @Che-debarras qui fait des listes de trucs HS regulierement ^^.

Apres si quelqu'un veut mettre en place chez lui un robot pour tester les fichiers HS de Vstream ....

**Comment by sizanic** [comment]
Je trouve pas mal l'idée d'avoir un robot qui testes les sites.

Ca éviterait que les sites cassés soient détectés avec du retard par nos utilisateurs et remontés dans des sujets ici.
Mais ce serait juste un test de non-régression en testant les regex.
Donc ne rechercher qu'un seul fichier par source.

Pour chaque site, on détermine un film et une série et on essaye de l'atteindre.
Lancer ce robot une fois par jour suffirait.

Je suis également contre une utilisation de ce code dans VStream.


@eco-plus : re-bienvenue avec ce nouveau pseudo, on en parle ou pas ?
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2726

**Comment by sviet2k** [comment]
Le code est deja fait. Je le partage quand meme si ce n'est pas utile pour vous autres ^^ :).
J'ai beaucoup de plaisir en lisant le code de vstream.
Et je ne suis pas capable de mock le hoster.py. C'est moins difficile si on bouge le methode checkhoster dans un nouveau module.

Url:
h ttps://github.com/sviet2k/zip/blob/master/test_vstream.zip?raw=true
unzip dans le root dir de vstream pour avoir le mock dir et le test_stream.py.
Modifier le 'sites' dans test_stream selon les besoins et rouler test_stream.py

Encore merci pour le vstream. 👍

**Comment by sizanic** [comment]
Je l'ai récupéré pour suivre ma piste, pour mettre en place un test quotidien automatique.
