### ISSUE TITLE
UPTOBOX, compte premium

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2748]
Bonjour,
Lorsque nous naviguons dans la section « Sources » de vStream, nous avons celle de Uptobox qui est présente. Cependant, il n,y a pas de metadata associées aux fichiers que nous y avons hébergé. De ce fait, même si nous choisissons cette source dans les paramètres de vStream, lors d’une recherche, nous n’avons aucun résultat 

Je ne sais pas comment coder, ni la façon de procéder pour pouvoir faire en sorte que cette source soit également « scrapper » mais s,il y a possibilité de le faire, j’aimerais beaucoup que cette fonctionnalité soit possible :))

Je vous remercie de l’attention portée mon message
Au plaisir!

**Comment by TmpName** [comment]
Alors je vais pas pouvoir m'en occuper, mais suis pas sur que ce soit faisable.

Il y a plusieurs type de repertoire possible dans vstream, il y en a pour les film et les serie par exemple qui sont scrappé, et d'autre pour des "dossier" ceux la ne le sont pas et c'est ce type qui a ete choisit par le createur du code et il avait surement une raison.

Sinon il y a une nouvelle version a tester (mais sans media pour sur) https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2660#issuecomment-590507948

**Comment by alKODIque** [comment]
D’accord, je comprends
Merci beaucoup pour le lien en référence 

Je vais aller y jeter un coup d’oeil

**Comment by isandard** [comment]
je précise que ma modif n'est pas pour scrapper mais juste pour classer differement dans les repertoires au niveau de l'affichage.
Le but c'est que si tu classes tes séries bien comme il faut par nom, tu crées une playlist en 2 secondes.
