### ISSUE TITLE
Zone Telechargement

### ISSUE THREAD

**Issue by arzaz** [Kodi-vStream/venom-xbmc-addons#2749]
ZT est out sur shield tv kodi 18.5

**Comment by jesusisback66** [comment]
out pour moi aussi nvidia sheild kody 17.6

**Comment by alKODIque** [comment]
Je suis sous Leia 18.5, Nvidia Shield.
VStream avec la dernière bêta...

Je réussi à voir le contenu mais j’ai le message « erreur décryptage du lien » lorsque je veux visionner liens uptobox

**Comment by Arias800** [comment]
Corriger dans la beta, depuis hier ils n’arrêtent pas de changer la protection du coup je doit complexifier le code a chaque fois ^^

**Comment by ludopotte** [comment]
Beta télécharger mais pour ZT ça change rien

**Comment by jesusisback66** [comment]
zt a encore changer le cloudflare apparament sa fonctionné jusqu'a 20h hier

Le mer. 26 févr. 2020 à 20:30, Ludo Potte <notifications@github.com> a
écrit :

**Comment by TmpName** [comment]
Pas de soucis avec CF de mon coté.

**Comment by Arias800** [comment]
C'est pas un soucis de CF mais un soucis de changement de code du coté de dl protect. Normalement le code qui est dans la beta fonctionne.

**Comment by ludopotte** [comment]
Moi j'ai toujours le Message d'erreur

**Comment by arzaz** [comment]
Toujours rien sur shield, il m'affiche "Aucune information"

**Comment by ludopotte** [comment]
Je viens de régler le Problème. Il faut juste effacer les données de Kodi et ensuite ré-installer vstream, ensuite mon patch et ça re fonctionne comme avant.

**Comment by arzaz** [comment]
quel patch?

**Comment by ludopotte** [comment]
Mon Patch est disponible au http//github.com/ludoptte/vStream

**Comment by arzaz** [comment]
toujours rien meme avec le patch

**Comment by BigLittleUser** [comment]
Bonjour a tous.

Et merci pour tout le boulot!! Je ne suis pas dev mais plutôt system mais j'espère un jour arriver  à dégager du temps pour me mettre au python et je viendrais vous rejoindre car le projet est super. 

Bref, je post ici car je viens vous parler d'un pb lié à ZT.
Je suis sur shield avec Kodi 17.6 Vstream 0.7.6  avec compte premium uptobox.

Descriptif du pb:
recherche sur Alita : battle angel  (en cliquant sur le poster) -> pas de résultat ZT
recherche manuelle alita --> plein de sources ZT
Je pensais que c'est les ":" mais non
recherche " the magicians" --> pas de sources
Recherche "magicians" -- > des sources

Voila, je n'ai pas fais de mise à jour manuelle ou semi-auto (je sais pas trop à quoi correspond semi-auto) .
Peut etre mon post est redondant.. dans ce cas j'en serai vraiment dsl.

Amicalement à tous les bosseurs de ce beau projet.

**Comment by sizanic** [comment]
Bonjour @BigLittleUser 

J'ai corrigé le souci des caractères spéciaux lors de la recherche sur ZT, mais il y a seulement quelques jours. (c'était suivi ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2732)

La correction n'est pas dans la version 0.7.6, ni dans une version disponible par la mise à jour semi-auto. Tu n'as plus qu'a attendre.

La mise à jour semi-auto, c'est un menu "Mise à jour disponible" qui apparait en haut lorsque tu arrives sur la page d'acceuil de VSTREAM.

La prochaine fois que tu verras ce message, fais la mise à jour et tu aura la correction.

Tu sera le bienvenue pour nous aider.

**Comment by BigLittleUser** [comment]
Merci pour ta réponse Sizanic. 
:-)

**Comment by sizanic** [comment]
Une mise à jour 0.7.7 est disponible, elle est automatique.

je confirme trouver des résultats sur ZT pour : 
Alita : battle angel
the magicians

**Comment by BigLittleUser** [comment]
Bonjour,

Yep, Super boulot !! ça fonctionne de nouveau.

Merci à tous :-)

**Comment by razorex** [comment]
Clos
