### ISSUE TITLE
PAPSTREAM- Ne retourne pas les bons résultats de recherche

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2751]
La recherche avec papstream ne donne pas les bons resultats de recherche.

**Comment by yodidon** [comment]
@sizanic j'ai justre fait une modif de urlmain et du regex(surement pas utile), je n'arrive pas à reproduire un problème de recherche...,  j'ai une question qui j’espère ne te paraîtra pas trop nul....
Pourquoi je n'affiche pas sThumb au vu de mes résultats sur la capture d'écran, j'ai fait vstream=>source=>papstream=>rechercher=>1917.le titre s'affiche bien mais pas le poster, 
![Capture](https://user-images.githubusercontent.com/39896943/75597580-8e775180-5a96-11ea-957f-62b8b708d6e0.PNG)
Merci

**Comment by TmpName** [comment]
Ben bonne question.
Je viens de tester ton lien est il est bon.
J'ai pas vu de protections cookie non plus, le je vois pas, peut etre un soucis dans kodi ou le coeur de Vstream.

**Comment by sizanic** [comment]
Je veux bien ton fichier source pour récupérer ta correction sur la recherche.

Sinon, je n'arrive pas à trouver le film 1917.

ça le fait que pour ce film ?

**Comment by yodidon** [comment]
> Je veux bien ton fichier source pour récupérer ta correction sur la recherche.
> 
> Sinon, je n'arrive pas à trouver le film 1917.
> 
> ça le fait que pour ce film ?

non pas que sur 1917, sur les resultats de recherche en général.

[papstream.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4270654/papstream.zip)

**Comment by sizanic** [comment]
Je viens de tester ton fichier.
La recherche fonctionne bien, je retrouve les films que je cherche.

Mais j'ai bien les posters également !

**Comment by yodidon** [comment]
Tu as le poster sur la page de résultat ?

Envoyé de mon iPhone

**Comment by yodidon** [comment]
bizarre oui je viens de retester avec d'autre titre et j'ai bien le thumb qui s'affiche bon alors peut être ais je enfin réparé un fichier ....

**Comment by yodidon** [comment]
une autre question... sur papastream j'ai essayé de différencier l'affichage avec ou sens recherche, je m'explique lorsque l'on recherche les éléments n'affiche ni le desc ni la qualité sur le site alors que sur la page genaral des films je peux récupérer le desc et la qualité. je me suis un peut perdu dans le code y a t'il un moyen facile de dire , si pas recherche afficher plutôt ça ?
Bon c'est pas trop claire mon explication mais ...

**Comment by TmpName** [comment]
Oui si c'est dans le fonctiion showmovie().
J'ai pas pu te trouver un exemple mais le test est tout simplement
>if sSearch:

Tu peux mettre un pattern different pour le cas avec recherche ou celui sans.

Tu peux aussi utiliser if len(aResult[1]) > 4:  pour savoir plus tard si tu as utilisé un pattern qui recuperes 4 info ou plus.

**Comment by yodidon** [comment]
super merci, j’étais aller dans cette direction mais une erreure sur la condition ...

**Comment by razorex** [comment]
j'étais aussi sur papstream. chez moi tout fonctionne, j'ai même remis le sinopsys pour les films

**Comment by razorex** [comment]
Le fait d'avoir corrigé l'url_main à reglé ton pb d'affichage de sthumb, puisqu'on l'utilise dans showmovies
            sThumb = URL_MAIN[:-1] + aEntry[0]

**Comment by yodidon** [comment]
oui j'avais bien noté que je le récupérais sur showmovies mais dans l'exemple au dessus pour le films 1917 malgré que l'url du sThumb soit ok elle n'affiche rien. et bien sur comme je suis fainéant je tapais simplement ce titre.
pour le synopsis je veux bien, si tu est d'accord, regarder ce que tu as fait

**Comment by razorex** [comment]
[ici](https://pastebin.com/PSma3SaV) sur pastebin

**Comment by yodidon** [comment]
Merci

**Comment by sizanic** [comment]
Profitez-en pour supprimer ces deux lignes inutiles, dans showMovies : 
        oRequestHandler.addParametersLine('do=search')
        oRequestHandler.addParametersLine('subaction=search')


Car si vous regardez le code de addParametersLine, chaque appel supprime le paramètre précédent, il n'y a que la dernière ligne qui est pris en compte et qui est auto-suffisante : 
        oRequestHandler.addParametersLine('story=' + sSearch)

**Comment by yodidon** [comment]
J’avais vue ça en debug mais je ne savais pas trop si c’était normale , je prend cette info merci 

Envoyé de mon iPhone

**Comment by yodidon** [comment]
Dans un autre contexte et à titre personnel, j’essaie d’ajouter une description dans les cas ou elle n’existe pas , j’essaie d’utiliser pour ça urllib2 mais je suis bien loin de mon résultat, sur un site qui regroupe une grande base de données sur les films , bref , je trouve que la ou le synopsis est le plus important c’est lorsque l’utilisateur navigue sur les films récemment ajouté. Et malheureusement beaucoup de site n’offre pas cette info

Envoyé de mon iPhone

**Comment by sizanic** [comment]
Cette fonction existe déjà dans Vstream.

Dans les paramètres de Vstream, onglet Général, "Recherche les métadonnées"

Ca va chercher sur le site TheMovieDB.org : 
La description, le poster, l'année, le genre et la note.

Exemple : 
https://www.themoviedb.org/search?query=Jumanji%20%3A%20Next%20Level&language=fr-FR

**Comment by yodidon** [comment]
Oui mais soit j’ai fait une erreur de mon côté les résumés sont anglais

**Comment by sizanic** [comment]
Avec ton code ou avec la fonction de base de Vstream ?
Ne te lance pas à refaire une fonction qui existe déjà.
Il faut plutot corriger celle qui existe.

**Comment by yodidon** [comment]
C’était bien un problème dû à ma config ( skin qui passait en anglais) donc effectivement aucune raison d’ajouter quoi que ce soit de ce côté. Et oui il vaut mieux corriger ce qui existe. Merci en tout cas :)

**Comment by yodidon** [comment]
Une question qui n’a rien avoir mais qui me tiens à cœur , pensez vous qu’il soit possible de faire une formation python à distance, j’en ai trouvé une mais je me demande si c’est jouable en ligne avant d’accepter

**Comment by sizanic** [comment]
ça dépend de tes besoins.

si c'est que pour Vstream, c'est vraiment pas la peine.

Le plus dur est déjà fait.
Il n'y a plus qu'à adapter du code existant.
Un peu de recherche sur google suffit pour avoir de la doc sur une fonction python en particulier.

Je suis pas du tout développeur pyhton à la base.

**Comment by TmpName** [comment]
Yep, je pense pareil. Moi non plus j'ai jamais "etudié" le python.

C'est un hobby, pas un metier, tu fais ca pour t'amuser, prend pas des cours pour ca.
Franchement, un peu de recherche, de bidouilles, d'echecs et ca avance, tu mettras juste plus de temps.

**Comment by Arias800** [comment]
Dans mon cas je ne savais même pas programmer (je ne connaissait même pas les bases) , j'ai tout appris avec python et Vstream xD

**Comment by TmpName** [comment]
Pareil, j'ai decouvert le python avec Vstream, je detestais ca (je viens du monde du c++, le python c'est pas terrible a coté, enfin sur le coup)
Et now je pourrais plus m'en passer

**Comment by sizanic** [comment]
On en est où de la correction de ce bug ?

**Comment by yodidon** [comment]
il y a du avoir une incompréhension de ma part, la modif de l'url suffisait a regler le bug. je n'ai pas du faire ce qu'il faut pour qu'elle soit prise en compte ?

**Comment by sizanic** [comment]
Pour moi ce qu'il y avait à faire, à travers nos échanges : 
 - changer l'URL (que tu as fait)
 - intégrer les modifs de razorex pour le retour des synopsis (voir pastebin) https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2751#issuecomment-593082547
 - intégrer ma suggestion sur la suppression de lignes en trop.https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2751#issuecomment-593108362


Dans tous les cas, si tu a des modifications à soumettre pour être prise en compte, tu te mets sur ta branche (patch-xx) et utilise l'action "New Pull request" -> "Create Pull Request".

Seulement comme ça nous pourrons intégrer ton code dans le projet Vstream.
(sinon il n'est que brouillon de ton côté)

**Comment by yodidon** [comment]
Ok désolé j’avais pas suivi la démarche.


Envoyé de mon iPhone

**Comment by sizanic** [comment]
Pas de souci, tu pouvais pas la deviner.
Il faut s'y connaitre en github.
J'ai prévu de faire un petit tuto sur "Comment soumettre une modification".

**Comment by razorex** [comment]
j'ais posté la mienne

**Comment by TmpName** [comment]
Lol, vous allez trop vite, je suis pas toutes les modifs moi.

**Comment by yodidon** [comment]
Lol la version de razorex contient les modifs a prendre en compte pour que tout fonctionne , à mon sens on peut dire que c’est resolu

**Comment by yodidon** [comment]
Je pense que l’on peut clôturer comme résolu non ?

**Comment by razorex** [comment]
ok je clos
