### ISSUE TITLE
STREAMAY - Pas les bons resultats de recherche

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2752]
La recherche avec STREAMAY ne retourne pas les bons résultats de recherche.

**Comment by sizanic** [comment]
Ce ticket n’intéresse personne ?

@yodidon  ?

**Comment by Arias800** [comment]
Le problème c'est que la recherche ne marche pas sur le site de base, peut importe ce que tu tape le résultat est toujours le même ^^

**Comment by sizanic** [comment]
ah OK.
Comme ça c'est dit.

Du coup, on pourrait masquer la recherche de notre côté en attendant ...

**Comment by Arias800** [comment]
Oui si tu veut ^^

**Comment by sizanic** [comment]
Je ne sais pas si ça c'est remis à fonctionner temporairement.
Mais après une petite correction, ça fonctionne de nouveau.
