### ISSUE TITLE
LIBERTYLAND - Pas de résultat de recherche bug

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2754]
La recherche avec LibertyLand ne retourne pas de résultat.

**Comment by TmpName** [comment]
Corrigé

**Comment by sizanic** [comment]
merci, mais je voulais proposer ces petits bugs à des nouveaux développeurs 😁

**Comment by yodidon** [comment]
j'ai n'ai pas encore regarder la correction pour voir ce que je trouvais et je suis pas encore pret... je vois bien la recuperation de "categorie" et "mot_search" bon je continue
