### ISSUE TITLE
STREAMDIVX - pas de résultat de recherche.

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2755]
La recherche avec STREAMDIVX ne retourne pas de résultat.

**Comment by Che-debarras** [comment]
Pourquoi ne pas faire un seul post avec la liste des sources qui ont ce bug et barrer la source résolu pour eviterde faire plusieurs posts pour un même bug.

**Comment by TmpName** [comment]
Sinon pour ce site, pas faisable.
Leur moteur de recherche ne fait pas avec les titres.

**Comment by sizanic** [comment]
@Che-debarras  avec de tout petits bug, j'incite des développeurs juniors à venir nous aider.

**Comment by sizanic** [comment]
Je viens de trouver une petite astuce pour retrouver quelque résultats.
c'est d'utiliser les tags.
URL/tags/mot+rechercher

exemples : 
/tags/edge+of+tomorrow
/tags/expendables+3/
/tags/inseparables

**Comment by sizanic** [comment]
@yodidon  tu prends ?

Il faut modifier URL_SEARCH_MOVIES
Et tester la recherche depuis la source (remettre le menu que j'ai mis en commentaire), et depuis la recherche globale (racine de Vstream).

**Comment by yodidon** [comment]
@sizanic  j’ai commencé à regarder , et c’est encore dur pour moi, je vais encore bosser

**Comment by razorex** [comment]
je comprend pas chez moi ca marche la recherche????

**Comment by sizanic** [comment]
Je prends la correction.

**Comment by sizanic** [comment]
Fini.
+ au passage, une correction pour nettoyer les descriptions.
