### ISSUE TITLE
Téléchargement de la version Beta vstream 

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2757]
maintenant lorsque l'on va sur la page pour télécharger la version beta de vstream
![Sans titre](https://user-images.githubusercontent.com/40530593/75631679-f7f47e80-5bc2-11ea-8ba9-4124e43f9b82.png)
 (github) on a un warning , le lien du site a changer est ce normal ?

**Comment by alKODIque** [comment]
Rien n’a changé. C’est ton navigateur qui te retourne un avertissement de contenu dangereux. S’il le faisait pas avant, c’est que tu dois avoir changé quelque chose au niveau des paramètres de sécurité de ton navigateur... Ceci dit, situ va au bas de ton message, tu verras une option qui te permettra « d’aller quand même sur la page malgré le risque »

**Comment by alKODIque** [comment]
Le lien ici, si jamais tu n’y arrives pas:

https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/plugin.video.vstream

**Comment by sizanic** [comment]
Par où vous passez ???

C'est le site https://minhaskamal.github.io qui retourne l'avertissement de contenu dangereux.

Vous pouvez pas aller directement sur le vrai site de Vstream ??
Qui n'a pas changé et qui est : 
https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/plugin.video.vstream

**Comment by sizanic** [comment]
Vous y accéder également en haut de cette propre page : 

![image](https://user-images.githubusercontent.com/47307622/75635662-31a3a480-5c18-11ea-8629-35175ae9edae.png)

**Comment by alKODIque** [comment]
@sizanic  
Comme tu dis, rien n’a changé. C’est qu’il ne comprends pas que c’est un avertissement de son navigateur.. Ses paramètres de confidentialité ont changé

**Comment by KodiTopQuebec** [comment]
j y vais avec chrome , aller sur le site officiel , ensuite aller au bas et cliquer sur télécharger  beta , vous verrez ce message et oui le site deviens le même que dit plus haut , si j y vais par edge cela ne me le fait pas , j y vais presque qu a tout les jours pour télécharger la beta , mais la j'ai ce message par google chrome

**Comment by alKODIque** [comment]
@KodiTopQuebec 
Je viens de faire exactement ce que tu dis... sur iOS, sur Android , sur PC...
Rien a changé.  Il est possible que tu as eu une mise à jour  qui a changé sans prévenir tes paramètres... regarde dans tes paramètres de chrome si les liens « https » et « HTTP » sont autorisés. C’est peut-être la cause de ton soucis

**Comment by KodiTopQuebec** [comment]
je viens de le faire tester par un ami , et lui aussi maintenant s il passe par google chrome il a cette avertissement ,étrange ...

**Comment by alKODIque** [comment]
Le problème vient clairement de chrome alors aucun lien avec vStream, le git de vStream ni le site de vStream.... Tu l’as expérimenté toi même: tu dis que ça fonctionne avec Edge...

**Comment by alKODIque** [comment]
Chrome ma déjà fait le coup des paramètres qui changent sans pré avis après une mise à jour. Je mettrais ma main au feu que ton soucis vient de la

**Comment by KodiTopQuebec** [comment]
@alKODIque ,merci je vais fouiller ici pour voir mes paramètres, au pire je vais passer maintenant par edge

**Comment by Arias800** [comment]
Ce genre d'avertissement c'est gérer par le navigateur et il ne faut aucun action de l'utilisateur pour que ça apparaisse. Donc sois il y a quelque chose de dangereux sur le site , sois c'est un faux positifs ^^

**Comment by sizanic** [comment]
voir aussi du coté d'autres alternatives : 
https://kinolien.github.io/gitzip/

ou la solution avec GitBrowser sur le repo de @ludopotte
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2700

**Comment by razorex** [comment]
il faut déclarer le site comme sure sur chrome
