### ISSUE TITLE
skstream HS

### ISSUE THREAD

**Issue by yodidon** [Kodi-vStream/venom-xbmc-addons#2760]
l'url n'est plus accessible.
j'ai commencé quelques modifs mais ça ne donne rien, je suis a la recuperation des info stitle  sthumb et slang, mais l'url bloque.
voila ce que j'ai essayé de faire
https://github.com/yodidon/skstream.git
je viens de retester l'url mais je crois que c'est un fake finalement désolé

**Comment by TmpName** [comment]
Lol, wé je crois que c'est encore une impasse.
Suis pas sur mais perso j'ai fais 3 tests a chaque fois impossible de lancer une video et des pub de partout.

Mais ca doit etre recent.

Ce qu'on fait en general, on attend un peu, mais on place un return False en debut de fichier avec la date, si tjours pas de retour apres quelque moi, poubelle.

**Comment by razorex** [comment]
j'ai une nouvelle url mais il faut reprendre bc du code et je m'y suis pas encore mis

**Comment by yodidon** [comment]
On peut diviser le job si tu veux , par exemple je m’occupe des regex et de leurs résultats


Envoyé de mon iPhone

**Comment by TmpName** [comment]
De quel site ? ww_w.skstr_eam.ink ?
Tu as pu lancer une video avec un navigateur ? moi j'y arrive pas.

**Comment by yodidon** [comment]
Non ce site est une erreur de la part et ne retourne que de la m....

**Comment by TmpName** [comment]
Du coup on le passe en site off ? Ou tu veux essayer de le retrouver ? Moi perso, je l'ai pas revu.

**Comment by yodidon** [comment]
Je n’ai rien trouvé non plus alors oui site Idf pour moi😒

**Comment by TmpName** [comment]
vendu
