### ISSUE TITLE
install Vstream from last repository 0.0.3

### ISSUE THREAD

**Issue by ivanParis** [Kodi-vStream/venom-xbmc-addons#2761]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  
 - Version Kodi  [18]
- Version Vstream repository 0.0.3

Bonjour, j'ai récupéré le repository (https://github.com/Kodi-vStream/venom-xbmc-addons/raw/Beta/repo/repository.vstream/repository.vstream-0.0.3.zip)
Dans kodi j'installe le repository mais lorsque je vais dans le addon pour installer Vstream. Il télécharge correctement mais lorsqu'il veut faire l installation il me met "installation failed"

Can you fix it.
I can't use vstream.
I have the same probleme with windows 10 an Android

**Comment by tochy83** [comment]
Bonsoir,
J'ai exactement le meme problème (je suis sur android)

**Comment by sizanic** [comment]
C'est parce qu'une nouvelle version est en cours de déploiement, il faut attendre ...

**Comment by sizanic** [comment]
Ca devrait être bon maintenant.

Merci de confirmer.

**Comment by tochy83** [comment]
Oui c'est bon maintenant. Merci bien de nous avoir tenu informé
