### ISSUE TITLE
filmzenstream

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2765]
des liens ne fonctionnent pas sur vstream alors que sur le site oui ex: jumanji le lien [ici](https://filmzenstream.online/regarder-jumanji-the-next-level-2019-film/).
Le lien pour le hoster est bon
j'ai ces erreurs
ERROR: ffmpeg[824]: [mov,mp4,m4a,3gp,3g2,mj2] error reading header
 ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file ?ttps://vidzstore.com/upload/2020/Mar/209133861.mp4
ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer

**Comment by TmpName** [comment]
C'est normal le "?" a la place du "h" ?

**Comment by razorex** [comment]
oui c'est normal je voulais pas mettre le lien http... lol

**Comment by TmpName** [comment]
Yep, pour moi c'es tjuste ca, quand j'ai voulu faire sur firefox j'ai mit plusieurs minutes pour avoir la video, sur Kodi j'ai du la monter pour arriver a 1 mn, donc a ce moment la, c'est mort.

**Comment by razorex** [comment]
Clos
