### ISSUE TITLE
Listes de Site A Trier

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2768]
Je publie sous "idée" même si cela peut etre lié aux bugs ou manque de source 

https://www.phonandroid.com/time2watch-et-35-autres-sites-de-streaming-pirate-sont-desormais-bloques-en-france.html

Visiblement certains sites sont ou seront bloqués par les FAI listées dans ce lien.

Certains semblent intéressantes et je suis sûr qu'ils trouveront un moyen de contourner le blocage comme c'est deja le cas pour time2watch.

Je me demandais si certaines de ces sources peuvent etre ajouté sur vstream tel que time2watch et autres qui apportes du neuf en terme de qualité et film.

NB: si quelqu'un a des sources asiatique vostfr en film serie drama je pense que cela interessera bcp de personne

Merci

**Comment by Arias800** [comment]
Time2watch c'est impossible de l'ajouter a Vstream a cause de Recaptcha ^^

**Comment by sizanic** [comment]
@Che-debarras 
Je te propose de modifier ton sujet pour y lister tous les sites.
On s'appliquera à dire pour chaque site si c'est faisable ou pas, si déjà fait, ou si c'est un clone.

Le titre pourrait être "Liste de sites à trier".

C'est une démarche pour identifier les sites intéressants.

**Comment by yodidon** [comment]
Difficile de récupérer les « vrais » site (pas de lien) , mais je regarderais si je vois quelques source

**Comment by Che-debarras** [comment]
> @Che-debarras
> Je te propose de modifier ton sujet pour y lister tous les sites.
> On s'appliquera à dire pour chaque site si c'est faisable ou pas, si déjà fait, ou si c'est un clone.
> 
> Le titre pourrait être "Liste de sites à trier".
> 
> C'est une démarche pour identifier les sites intéressants.

Oui j'y est pensé justement je vais refaire un post et clore celui ci.

**Comment by TmpName** [comment]
Heu, faites gaffe a pas transformer l'issue en annuaire warez.
Si on pouvait eviter de sortir en top 10 d'annuaire de ce genre sur google, ce serait sympa

**Comment by Che-debarras** [comment]
> Heu, faites gaffe a pas transformer l'issue en annuaire warez.
> Si on pouvait eviter de sortir en top 10 d'annuaire de ce genre sur google, ce serait sympa

Ok dans ce cas je retire tous les sites et je ne laisse que le lien de l'article.

**Comment by yodidon** [comment]
Je suis complètement d’accord avec @TmpName , il serait judicieux d’adopter une convention pour écrire ce type de post

**Comment by sizanic** [comment]
Peut-être peut-on maintenir un fichier python dans une branche à part.

**Comment by TmpName** [comment]
Moi je rajoute un " " ou un "_" au milieu du nom, en general ca suffit pour que les moteur de recherche ne voyent pas le lien.

**Comment by sizanic** [comment]
On n'a plus qu'a se lancer dans du Leet Speak 🙃 
https://fr.wikipedia.org/wiki/Leet_speak

Du coup, on remet la liste avec quelques règles de nommages ?

**Comment by yodidon** [comment]
A enfin un truc de ma génération 😜

**Comment by TmpName** [comment]
Lol, tu en veux du leet speak, la derniere serie que j'ai vu c'etait NOS4A2

**Comment by DaX59** [comment]
4f752073696e6f6e206f6e20c3a96372697420656e2068657861

**Comment by yodidon** [comment]
Ha ouiiiiii

**Comment by DaX59** [comment]
Je vous laisse checker : 
68747470733a2f2f706173746562696e2e636f6d2f514d535154766868

**Comment by yodidon** [comment]
Merci pour la liste ça en fait du boulot :)

**Comment by sizanic** [comment]
pas compris ...

**Comment by DaX59** [comment]
@sizanic , un petit indice
http://www.unit-conversion.info/texttools/hexadecimal/
Technique utilisée pour masquer les liens

**Comment by gratoQ** [comment]
sa sert a rien dès qu'un github est public il est référencé sur google et tous ceux qui viennent ici avec zt ne fonctionne pas etcétéra n'arrange rien.

**Comment by TmpName** [comment]
Je suis d'accord.
Mais il ya une difference entre avoir 2 3 liens qui pointe vers un site warez, qu'un annuaire complet.

**Comment by yodidon** [comment]
Apriori pour l’instant ce n’est pas encore en tête de Google alors il faut être vigilant

**Comment by DaX59** [comment]
Si vous voulez récupérer mon pastebin et ensuite je supprime le lien même si codé en Hexa, c'est plus sûr

**Comment by sizanic** [comment]
Merci pour la liste.

Mais l’intérêt de ce sujet ("Listes à trier") est de pouvoir trier la liste ensemble pour en sortir des sites intéressants (=> Créer de nouvelles sources Vstream).

Sous ce format c'est un peu figé.
Dans la liste je vois plusieurs clones. Comment je peux en faire part ?

**Comment by yodidon** [comment]
Pour cette liste de mon côté j’ai commencé à regarder et à en préparer une qui me paraissait ni clone ni fake, peut être , comme le dit @sizanic un moyen d’organiser le contenue serait pas mal

**Comment by sizanic** [comment]
@yodidon 
déjà deux fois tu avais commencé un site qui était un clone.
Cette fois, dis-nous sur quel source tu travailles et on te donnera notre avis.

**Comment by yodidon** [comment]
1streamings

**Comment by TmpName** [comment]
v_vw. n1streaming.c om ?

**Comment by yodidon** [comment]
Oui

**Comment by TmpName** [comment]
Et tu as pu acceder a une video ?

**Comment by yodidon** [comment]
Oui , pas toi ?

**Comment by sizanic** [comment]
moi j'ai essayé.
doctor sleep => KO (que des liens obsolètes)
Spenser Confidential -> OK (plusieurs liens fonctionnent)
Ça : Chapitre 1 -> OK également


Par genre => que la première page ok
les autres pages n'ont pas la bonne URL (peut-être qu'en cherchant on la retrouverai)

Pour la recherche => il faut ajouter un % devant le terme recherché pour avoir des résultats.

**Comment by TmpName** [comment]
Bon ben j'ai la maffre alors ^^

**Comment by sizanic** [comment]
maffre ??

Ah oui, ok : https://fr.wiktionary.org/wiki/porter_la_maffre 

dsl, je suis parisien :)

**Comment by yodidon** [comment]
je viens de terminer le nouveau site, il fonctionne si ce n'est certain host ne marche pas. Je vous le propose ?

**Comment by sizanic** [comment]
Bah bien sûr !

Mais sur GIT, dans une nouvelle branche.

Pas sur pastebin, stp, sinon on ne pourra pas te faire de retour.

**Comment by razorex** [comment]
Vous avez regarder la liste de @Che-debarras y en a pas mal sur vStream

**Comment by yodidon** [comment]
Oui c’est de cette liste que j’ai pris onestreaming qui est devenu  yourfilms et qui était hs  hier ...
