### ISSUE TITLE
Recherche sur ZT tirexo est hors service

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#2769]
kodi 17.6 android et Windows

Depuis la mise à jour 0.7.7  la recherche sur  ZT Tirexo  ne fonctionne plus.
En effet, la liste des films par catégories est accessible mais plus aucune  recherche n aboutit

**Comment by Arias800** [comment]
Bon c'est corriger dans le bêta. Pour le changement d'url j'ai carrement mis le même système que pour zt. Par contre il faut installer la beta en entière pour que le site fonctionne.

**Comment by BENJI97200** [comment]
@Arias800 .....Slt,Zt et tirexo ne fonctionnent plus ....Aucune information (sur nvidia shield tv)

**Comment by sizanic** [comment]
En effet avec Tirexo, plus aucun film de proposer.
Toutes les listes sont vides.

=> Mais je n'ai pas testé avec la beta qui vient juste d'être mise à disposition avec la correction sur l'URL.

Sous ZT, par contre j'ai bien les films, et j'arrive à en lancer.

[ANDROID]

**Comment by BENJI97200** [comment]
Sur s10+ zt se lance mais pas sur nvidia

**Comment by kris06** [comment]
normal l url a encore changée aujourd'hui     https://www2.zone-telechargement4.vip/  
mais elle n'est pas dans le beta

**Comment by BENJI97200** [comment]
@sizanic ....Zt et tirexo fonctionnent,c est juste le chemin qui changé pour nvidia shield(en tout cas pour moi) ....Il faut faire sources et choisir tirexo ou zt car en passant directement par films hd ou derniers ajouts on obtient aucune information....

**Comment by kris06** [comment]
Toujours aucune recheche possible sur tirexo (alors quelle fonctionne en recherche globale) 
L'intérêt de  tirexo  c'est justement de pouvoir rechercher dans son catalogue gigantesque... Si vous cherchez un film vous le trouverez à coups sur cette source..

Merci à vous de pouvoir réactiver la recherche ... 

Par ailleurs il n'est plus possible de voir les bandes annonces y compris sur zone...

**Comment by TmpName** [comment]
Je viens de tester, Tirexo/film/recherche/blade et ca a marché de mon coté.

**Comment by kris06** [comment]
Je ne comprends pas sur mes appareils box  Android,  pc windows  vidéoprojecteur sous interface Android et téléphone android 
sous krypton 17.6 ou sous lea 18.5 présentent le meme problème ..

Dans le doute et puisque tu me dis que cela fonctionne pour toi, j'ai réinstallé kodi et vstream sur mon telephone mais ça ne change rien 
Tirexo/film/recherche/blade  NE TROUVE RIEN !

**Comment by sizanic** [comment]
Est-ce que vous êtes sur la même version de Vstream ?
C'est pas la version de Kodi qui compte.
Vstream 0.7.7 basique ou patché ?

**Comment by sizanic** [comment]
J'ai des résultats pour "blade", mais j'utilise la version de la branche Beta.

**Comment by kris06** [comment]
Vstream 0.7.7 basique je suppose
addon ci joint que je mets à jour 

http://82.253.135.84:29364/share/vPRQsbmOKAWZmLSO/plugin.video.vstream-0.4.6.zip

**Comment by sizanic** [comment]
Tu es sur la version normale puisque tu dis avoir tout réinstallé.

A moins que tu réinstalles manuellement une version que tu a modifié qui contient la correction sur Tirexo (la version Beta modifiée par Arias800 qui est mentionnée dans la première réponse de ton sujet, en haut de cette page).

Sinon, si tu utilises la version qui n'est pas corrigée et qui ne fonctionne pas, et bien elle ne fonctionne pas.

Pour ton zip, je ne sais pas ce que tu as voulu nous envoyer mais tu t'es trompé.

**Comment by kris06** [comment]
Mon lien menait vers addon classique de vstream. En effet., j'attendrais la corrections d arias800 que j'avais manqué de lire.
Merci à toi

**Comment by kris06** [comment]
C'est infernal zt tirexo change son url tous les jours maintenant

**Comment by kris06** [comment]
C'est infernal ZT tirexo change son url tous les jours maintenant
https://www.zone-warez.com/

**Comment by Arias800** [comment]
C'est corriger, mais après c'est un cas exceptionnel car ils ont subit un blocage DNS ^^

**Comment by dbast57** [comment]
bonjour,

Je suis désolé et surtout très novice !!

Ou trouve t'on la correction en téléchargement ?

merci pour votre super travail

David

**Comment by TmpName** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/tirexo.py

Sinon faut attendre la MAJ.

**Comment by dbast57** [comment]
Merci beaucoup

Mais quand je suis sur le lien, que dois je faire ?
Peux t on télécharger une version ?

**Comment by sizanic** [comment]
@dbast57 
Si tu es novice, vaut mieux que tu attendes la mise à jour plutot que d'essayer d'injecter manuellement ce fichier dans ton application KODI.

Il reste bien d'autres sources encore fonctionnelles pour te permettre d'attendre cette mise à jour.

**Comment by dbast57** [comment]
Merci sizanic

J'aurais souhaiter apprendre, si on peut m'expliquer ou m'indiquer un tuto

Bonne soirée

**Comment by sizanic** [comment]
Un petit d'aide sur les mises à jour ici : 
https://kodi-vstream.github.io/docs/update/

Concernant la mise à jour manuelle d'un fichier, sous Windows, il faut aller le remplacer ici : 
C:\Users\\_MyName_\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\\
(dossier \appdata est caché, il faut activer la visibilité des fichiers cachés)

**Comment by dbast57** [comment]
Merci beaucoup

Je vais essayer cette après midi

Je ne risque rien d'essayer

Bonne journée

**Comment by kris06** [comment]
Salut si tu eq pressé er c'est uniquement tirexo que tu veux réactiver je peux te le faire a distance via teamviewer... contacte moi en privé via mon adresse christian...

**Comment by kris06** [comment]
Plus de lien fonctionnel sur tirexo  
.py en beta
Android 18.6 ou 17.6

**Comment by Arias800** [comment]
Je m'en occupe, par contre ils ont fait des modif dans l'affichage des pages donc ca peut prendre un moment a tout corriger.

**Comment by Arias800** [comment]
Corriger dans la beta

**Comment by kris06** [comment]
Merci cher ami le beta fonctionne
Avec ces mesures de confinement le trafic s'est  décuplé et les serveurs sont saturés le soir

**Comment by dbast57** [comment]
Je vous remercie beaucoup pour votre travail

Bonne journée à vous tous et prenez soin de vous et de votre famille

**Comment by kris06** [comment]
Est-ce que l'un d'entre vous pourrait m'indiquer la ligne chargée d'annoncer la notification des mises à jour (majeures ou intermédiaires) . Je ne l'ai pas trouvé.

**Comment by TmpName** [comment]
@kris06 tu as regardé dans le fichier about.py ?

Sinon le test se fait dans le fichier home, ligne 38 pour afficher ou non la nouvelle icone pour les intermediaires.

Pour les majeures, c'est kodi qui gere.

**Comment by kris06** [comment]
Salut et merci pour tes informations,

J’utile un petit programme perso installé qui adresse une notification (pop-pup) de mise à jour sur l’écran de mes amis. Ce petit programme est mineur au regard de ton travail et celui de tes collaborateurs

Mon programme fonctionne de la façon suivante :

-	Suppression du fichier settings xml   (permet de lancer la réinitialisation de la mise à jour)   
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.vstream/settings.xml)_

-	En l’absence de ce fichier settings.xml mon programme adresse un pop-up sur l’écran de mes 
        amis.
-	Téléchargement du settings.xml et réinstallation du fichier supprimé.

Cependant, mon programme ne fait pas la différence entre mise à jour majeure et intermédiaire.
A ce propos comment la reconnaître ?  Pourrais-tu me dire si l’intermédiaire se trouve indiquée par cette quatrième décimale, ici le 3  dans cet exemple 0.7.5**3**    ?

Par ailleurs, mon système me pose un problème lorsque vous passez de 0.7.6  vers  0.7.7 
En effet,  dans cette situation (0.7.6  vers  0.7.7)  et après la suppression du fichier settings.xml,  ce fichier se réinstalle automatiquement du coup , la réinitialisation de la mise à jour ne se propose pas et par conséquent mon pop-up indique quand même qu’il y faut effectuer la mise à jour…

En conclusion, j’aimerais comprendre comment je peux différencier la mise à jour majeure  et l’intermédiaire   ? 

Je te remercie
Kris

**Comment by TmpName** [comment]
Pour les majeure c'est kodi qui gere, donc tu ne pourras rien faire en modifiant le code de Vstream.
Pour les mineures oui, c'est toujours de la forme 0.X.X.XX

**Comment by kris06** [comment]
salut j'ai bien noté tes infos et je te remercie

impossible de visionner un film sur ZT tirexo  ET  zone téléchargement  ce matin alors que VF space fonctionne...
 S'agit'il d'un problème de saturation du réseau ?
