### ISSUE TITLE
Bande annonce hs 

### ISSUE THREAD

**Issue by Grum31** [Kodi-vStream/venom-xbmc-addons#2770]
**Décrivez le bug**
La bande annonce provoque une erreur vstream 

**Votre system**
 - OS: [Android TV 6]
-  Appareil [H96 pro plus]
 - Version Kodi  [18] idem sur SPMC
- Version  vstream 0.7.7

**Nous devons le reproduire**
Pour cela il nous faut:
- Tous

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by TmpName** [comment]
La clé API n'est plus valide

**Comment by sizanic** [comment]
Qu'est-ce que cette clé API ?
Ne peut-on pas la réactiver ?
C'est payant ?
Ne peut-on pas en avoir une autre ?

**Comment by TmpName** [comment]
Nope c'est gratuit, mais si trop de monde l'utilise, ils peuvent la bloquer (bon la pour le coup elle a tenu longtemps)
Oui c'est re-activable, on peut soit retrouver les mot de passe qui traine peut etre sur une issue, soit re-faire une clé.
Mais ca risque de se reproduire.

**Comment by sizanic** [comment]
La solution de contournement a l'air de bien fonctionner.

A voir à l'usage...

**Comment by paololito** [comment]
Bonjour même problème . est ce que il y 'a une solution ?

**Comment by sizanic** [comment]
Le problème à été corrigé, il faut attendre la mise à jour pour qu'elle soit déployée sur vos équipements ...

**Comment by paololito** [comment]
ok Merci , J'attends la mise à jour

**Comment by Grum31** [comment]
Ok merci
Ça re fonctionne avec la bêta maj

**Comment by sizanic** [comment]
Je rouvre le sujet tant qu'il n'est pas encore disponible dans une mise à jour. 
Évitant également qu'on se repose la question.

**Comment by paololito** [comment]
bonjour, je vois plus haut que avec la beta MAJ cela fonctionne , une question de débutant : ou telecharger la beta MAJ  ?  Merci pour votre aide et votre travail .

**Comment by lukingx** [comment]
Salut l'équipe ,Moi j'ai toujours le même soucis , faut faire quoi exactement ? Je suis sur box TV minix , merci a vous.

**Comment by TmpName** [comment]
Je fais une MAJ partielle d'ici vendredi si personne ne s'y colle.
Normallement avec du bol je vais avoir du temps libre tres bientot.

**Comment by Laurentfincher** [comment]
Du coup comment avoir à nouveau les bandes annonces ? Ce n'est pas clair.
.

**Comment by TmpName** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2802

**Comment by victore447** [comment]
Bonjour,
Pour les bandes annonce cela vient de youtube via google.
Depuis peux dans kodi il n'est plus possible d'acceder à ces données youtube (favoris etc..) 
et tout est bloquer par google.Il faut refaire ça propre clee Api youtube pour 
pouvoir utiliser youtube dans kodi sans avoir acces à ces favoris etc..et vstream....

Exemple d'un Lien en video pour creer l'Api youtube: https://www.youtube.com/watch?v=DcgXSxPkbvY
Lien de la console pour creer son Api: https://console.developers.google.com/?hl=fr&pli=1

Une fois votre clée Api creer il faut aller sur l'addon youtube puis sur vstream,general puis Api et recopier votre clee 
Api creer dans la console google.

Pour les infos des medias de vstream j'ai remarquer que cela ne fonctionne plus aussi.
J'ai activer "use extendedinfo" dans vstream mais les infos des films et series etc.. sont en anglais.
Pour cela il faut aller sur vstream,general,et cocher Use extendedinfo.
