### ISSUE TITLE
Comment voir qu'URL Resolver fonctionne

### ISSUE THREAD

**Issue by Thatchantique** [Kodi-vStream/venom-xbmc-addons#2771]
Je suis nouveau et j'avoue avoir eu du mal à configurer URL Resolver.
Pour éviter tous risque lié à mon FAI je souhaiterais faire en sorte de passer uniquement par URL Resolver.
Merci par avance.

**Comment by gratoQ** [comment]
sauf que url resolver n'est pas un vpn ou un proxy, il sert a récupérer l'url des hosts non pris en charge par vstream (débrideur etc...)

**Comment by ludopotte** [comment]
Pour configurer URL Resolver sur vStream, il faut que tu ailles dans les Paramètres de vStream , Rubrique "Premium/Login"", coche "Passer par UrLResolver" et "Configuer UrlResolver" avec un debrideur (Alldebrid etc...)

**Comment by gratoQ** [comment]
tu sais lire @ludopotte ou t'es un robot qui spam le github avec des conneries.
il pense que url resolver va le protéger, c'est faux.

**Comment by ludopotte** [comment]
Oui URL Resolver vas pas le protéger car il y a deja un vpn dans Kodi et je spam pas github avec des conneries gratoQ

**Comment by gratoQ** [comment]
déjà il n'y a pas de vpn dans kodi...

**Comment by ludopotte** [comment]
Mon Patch a la Noix comme tu dis @gratoQ sert à avoir vStream à jour manuellement et il sert a beaucoup de gens.

**Comment by gratoQ** [comment]
débile de supprimer les messages.
