### ISSUE TITLE
annuaire-telechargement.best

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#2778]
Bonjour,
Voici 
ht tps://w ww.annuaire-telechargement.best/  qui n'est pas présent dans vstream.

De plus j'ajoute que le lien tel que zone-telechargement ne proposent pas de lecture videos et le message est "pas de streaming sans premium" alors que quand on se rend sur le site via navigateur web on peut lire gratuitement en streaming les videos du site.

Merci pour votre réponse.

**Comment by alKODIque** [comment]
cool ce site :))

**Comment by BENJI97200** [comment]
Salut....C est vrai qu il est top ce site ,je ne le connaissais pas,possibilité de l ajouter sur vstream???

**Comment by Arias800** [comment]
Non on ne va pas ajouter ce site. Il y a 2 zt c'est déjà assez compliquer des les maintenir a jour.

**Comment by BENJI97200** [comment]
@Arias800 .....slt,merci je comprend

**Comment by TmpName** [comment]
Loooool, non sans deconner ? Petit joueur !

**Comment by Arias800** [comment]
Bah vas y je te laisse la charge des 2 zt alors, vu que tu a hâte d'avoir 50 messages par jours en cas de bug avec en bonus des bug bizarre a gérer :p

**Comment by BENJI97200** [comment]
@TmpName .....impressionnes  nous ajoute ce site...lol

**Comment by TmpName** [comment]
XD.

Je fais deja le mort pour les deux autres ^^. Apres il est peut etre plus stable que les deux autres, a garder sous le coude pour voir.
