### ISSUE TITLE
Plus de bande annonce sur vstream

### ISSUE THREAD

**Issue by lukingx** [Kodi-vStream/venom-xbmc-addons#2780]
Bonjour je n'ai plus aucune bande annonce sur vstream , je suis le seul ? Que ce soit sur portable ou sur appareil Android , merci a vous .

**Comment by sizanic** [comment]
C'est corrigé, voir ce sujet : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2770

**Comment by Laurentfincher** [comment]
Problème toujours d'actualité sous libreelec
