### ISSUE TITLE
Evolution Logo

### ISSUE THREAD

**Issue by yodidon** [Kodi-vStream/venom-xbmc-addons#2783]
Une insomnie et je me demandais si le logo de vstream ne pourrait pas évoluer, surement aucun intérêt mais j'y pensais donc je propose...
![Vstream-logo](https://user-images.githubusercontent.com/39896943/76813042-05cb1600-67f7-11ea-8028-fdbb0ccc1fc5.png)
![Vstream-logo2](https://user-images.githubusercontent.com/39896943/76813102-2eeba680-67f7-11ea-8fb3-b19a21093ea6.png)

**Comment by TmpName** [comment]
Lol, a un moment il me fallait un logo pour des tshirts, c'est con que je t 'ai pas connu a ce moment.

Le deuxieme fait "too much" pour moi par contre.

Apres faut voir ce que ca donne dans le plugin, me souvient que lordvenom avait galéré pour trouver un truc ni trop sombre, ni pas assez, et assez discret pour ne pas perturber l'affichage.

**Comment by yodidon** [comment]
À mince le deuxième était mon préféré... lol

**Comment by TmpName** [comment]
Suis pas une reference non plus ^^
J'aime les truc austeres, pas flashy.

**Comment by sizanic** [comment]
Le premier en effet. Le 2eme est trop amélioré.
Et sur une seule ligne car ceux qui ne connaissent pas verront juste le mot STREAM avec un drôle d'accent sur le E.

Et je ne sais pas s'il faut rester dans l'esprit d'origine du nom où seul le S est en majuscule : vStream.

**Comment by sizanic** [comment]
Plus qu'un logo, l'image Fanart est utilisée derrière les descriptions avec certains Skin.
Il faut donc qu'elle soit sobre pour pas alourdir l'affichage.

J'en avais discuté ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2501
Je proposais déjà que la communauté fasse des propositions.

Il faut que tu vérifie comment l'image s'intègre avec plusieurs skins et types d'affichages.

**Comment by razorex** [comment]
J'ai testé le 2 et effectivement l'écriture est trop haute. Et sur une ligne aussi ce serait mieux

**Comment by yodidon** [comment]
Oui la définition n’est pas encore adapter, étrangement le fan art est en 16/10 eme si l’idée peux intéresser je veux bien modifier ou même faire d’autres propositions

**Comment by sizanic** [comment]
Propose déjà le 1er , sur une même ligne et avec seulement le S en majuscule.

**Comment by yodidon** [comment]
ok mais le fanart est en maj ...

**Comment by yodidon** [comment]
![fanart_V2](https://user-images.githubusercontent.com/39896943/77012552-72b4ec00-696e-11ea-8887-7f1ec2d56f7f.jpg)

**Comment by yodidon** [comment]
optimisé pour skin par defaut + icon
![fanart](https://user-images.githubusercontent.com/39896943/77017033-9cbfdb80-6979-11ea-9b3e-9afc0ea30639.jpg)
![icon](https://user-images.githubusercontent.com/39896943/77017045-a2b5bc80-6979-11ea-93c3-945759c4efc2.png)

**Comment by yodidon** [comment]
on peut aussi faire style bobo parisien ...
![fanart_soft](https://user-images.githubusercontent.com/39896943/77017387-ad248600-697a-11ea-8981-65f89c17a177.png)

**Comment by gratoQ** [comment]
Personne ose te le dire, mais ils sont tous horrible fait quelque chose de discret.

**Comment by yodidon** [comment]
D’accord merci @gratoQ  je vais voir pour plus discret, et je comprends qu’ils soient horribles...

**Comment by TmpName** [comment]
Lol, il est comme moi, il prefere le style minimaliste.
Mais bizarrement le "bobo parisien" moi j'aime bien, c'est le plus discret pour le moment aussi.

**Comment by yodidon** [comment]
Oui je comprends mais horrible j’avoue je m’y attendais pas ...

**Comment by razorex** [comment]
bah moi j'aime bien l'effet béton. Sauf que trop bas,,,,, mdr en fait centre vStream.
Pour les  critiques il ne faut pas oublier qu'il est en arriere plan donc pas très visible et certaines interface le vire carrément.

**Comment by yodidon** [comment]
Plus "angulaire"
![fanart4](https://user-images.githubusercontent.com/39896943/77116678-d30c6200-6a30-11ea-8dbf-a619b976aa55.png)

**Comment by TmpName** [comment]
Hu ....
Je reste sur mon choix "bobo parisien" ou "effet beton"
