### ISSUE TITLE
Lib utils

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2784]
@Arias800 tu a modifié la lib utils pour ajouté (et supprimer de voirfilms).
`def Noredirection(UA, host, sUrl):
    class NoRedirection(urllib2.HTTPErrorProcessor):
        def http_response(self, request, response):
            return response

        https_response = http_response

    opener = urllib2.build_opener(NoRedirection)
    opener.addheaders = [('User-agent', UA)]
    opener.addheaders = [('Referer', host)]
    response = opener.open(sUrl)
    sHtmlContent = response.read()
    redirection_target = sUrl
    if response.code == 302:
        redirection_target = response.headers['Location']
    response.close()
    return sHtmlContent, redirection_target`
Ma question, on laisse dans la lib ou dans voirfilms??
parce que tu la mis puis enlevé mais pas remis dans voirfilms.

**Comment by Arias800** [comment]
Oui je viens de voir ça, c'est un oublie, j'ai corriger. Car j'ai trouver un moyens plus propre d'utiliser `urllib2.build_opener` pour simplifier le passage en python 3

**Comment by razorex** [comment]
zut je l'ai remis dans la lib, je m'occupe de la retirer

**Comment by Arias800** [comment]
J'ai deja fait tout corriger aussi bien sur le site que dans util ^^

**Comment by razorex** [comment]
ok pour le quotesafe???

**Comment by Arias800** [comment]
Quel quotesafe ?

**Comment by razorex** [comment]
tu a créer cette lib dans util:
`def QuoteSafe(sUrl):
    return urllib.quote(sUrl, safe = ':/')`
pour remplacer

**Comment by razorex** [comment]
dsl tu l'a juste modifié.

**Comment by Arias800** [comment]
Bon je viens de voir le quote restant de voirfilm, maintenant urllib est totalement dégager du fichier site xD

**Comment by razorex** [comment]
ok
