### ISSUE TITLE
ZT : liens s'affichent, mais tournent dans le vide quand in clique dessus

### ISSUE THREAD

**Issue by Rikikisifreddo** [Kodi-vStream/venom-xbmc-addons#2785]
Bonjour, 
Sur fire stick, kodi 17.6 et après maj de vstream aujourd'hui, la recherche zt fonctionne, mais quand je clique sur un lien, ça tourne sans arrêt, sans aucune erreur annoncée.

**Comment by yodidon** [comment]
de quelle version de mise à jour ?

**Comment by Rikikisifreddo** [comment]
0.7.7

**Comment by yodidon** [comment]
Corriger dans la bêta , disponible dans la prochaine MAJ

**Comment by Rikikisifreddo** [comment]
Ça refonctionne sans avoir eu de maj. Coronavirus sûrement...

**Comment by yodidon** [comment]
Oui sûrement :)

**Comment by arzaz** [comment]
Avec la dernière beta, ZT ne se lance pas et TIREXO vide sur Shield tv Kodi 18.6

**Comment by alKODIque** [comment]
@arzaz 
J’ai le même bug, en rétrogradant sur la version du dépôt, ZT fonctionne à nouveau

**Comment by thorsten68** [comment]
il faut installer celle la du coup ?
plugin.video.vstream-0.7.7.zip
