### ISSUE TITLE
F r e n c h - s t r e a m séries ne marche pas

### ISSUE THREAD

**Issue by shmox75** [Kodi-vStream/venom-xbmc-addons#2787]
Bonjour à tous, je suis sous android sous kodi 18.6 et ça fait un petit moment que quand je clique sur une série (dernier ajout) sur f r e n c h - st re am il ne se passe rien.
La partie films ça marche très bien par contre :)

**Comment by TmpName** [comment]
Alors je sais pas trop.
De mon coté ca a marché, mais dans tout les cas @razorex a fait une grosse modif sur le fichier il y a 7h.

**Comment by yodidon** [comment]
pour moi ça marche avec la beta

**Comment by razorex** [comment]
oui j'ai apporté des corrections

**Comment by TmpName** [comment]
J'arrive pas a voir si c'est utile.
On vire ?

**Comment by shmox75** [comment]
> oui j'ai apporté des corrections. le premier épisode de chaque séries n'est pas dispo car bloqué par cette instruction
> ` if sData == 'episode1': #episode final au lieu du 1er donc pour le moment`
> `return`

Oui je crois que c'est le premier épisode, je n'ai pas compris pourquoi ? c'est le site ou vstream le soucis ?

**Comment by yodidon** [comment]
Il semblerais que ce soit le site qui renvoie ça

**Comment by shmox75** [comment]
> Il semblerais que ce soit le site qui renvoie ça

Je ne sais pas je crois (j'ai essayé au pif) que sur le site ça semble marcher. A moins que certains liens sont morts, mais bizarre que ce soit toujours le premier épisode :/

**Comment by TmpName** [comment]
On vera a l'usage, peut etre dans le cas ou il il n'y a qu'un seul episode, mais quand j'ai testé c'est passé aussi.

**Comment by razorex** [comment]
en faite cette modif a été faite parce qu'il y a un décalage l'épisode 1 serais en faite le dernier.
perso moi j'aurais mis du texte dans showhoster pour le préciser.

**Comment by TmpName** [comment]
Mais tu as pu voir ce bug  de ton coté ?

**Comment by razorex** [comment]
c'est pas un beug c'est un décalage sur le site. Perso je libérerais l'épisode tout de même.

**Comment by TmpName** [comment]
J'ai de la mer2 devant les yeux je le vois pas ce decalage ....

La je teste avec "Le Voyageur - Saison 1", il n' y a que 2 epsiodes, mais je vois pas de decalage.

**Comment by razorex** [comment]
quand tu regarde l'épisode 1 c'est le même que le 2, lance le fichier

**Comment by TmpName** [comment]
Haaa ok, donc la je comprend mieux, mais du coup on y peut rien.

**Comment by razorex** [comment]
oui ce n'est pas dans notre cours

**Comment by yodidon** [comment]
Et sur ce site sauf erreur y’a plus de titre ni de thumb ?

**Comment by razorex** [comment]
Ah je viens de voir que a nouveau il y a un souci avec ce site

**Comment by yodidon** [comment]
Oui j’étais déçu mais j’ai rien de bien terrible , plus de titre sur leur page

**Comment by razorex** [comment]
Bon la source revient à un état de fonctionnement correct donc je ferme cette issue
