### ISSUE TITLE
Santé

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#2788]
Merci pour votre travail.

Prenez soin de vous et de vos familles en cette difficile période.

Courage à toutes et tous

**Comment by TmpName** [comment]
De meme :)
Moi de mon coté ca bosse encore, mais les villes sont desertes, donc je pense que ca devrait aller.

**Comment by razorex** [comment]
Moi çà fait plusieurs jours que je suis confiné et ben j'ai jamais autant eu hâte de retrouvé le travail ;-)
Bon je close cette issue.
PS: j'ai appris que les magasins ne servait lus d'alcool ptdr

**Comment by TmpName** [comment]
Plus d'alcool ?
Merde vais ressortir mon alambic maison, avec des patates, au moins ca me fera des legumes.
