### ISSUE TITLE
Hoster Vizplay

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2789]
Sur ianime un nouvel hoster Vidzi.
Url [ici](https://www.ianimes.org/6b45cf467a9c88001159a826e92c7437.htm)

**Comment by TmpName** [comment]
Il y est deja sur Vstream, peut etre pas fonctionnel.
Je teste

**Comment by razorex** [comment]
oups dsl c'est vizplay
le nom c'est hack root

**Comment by TmpName** [comment]
Bon ben apres m'etre fait chier a tester recaptcha, m'etre mangé des kilos de pub et essayé de comprendre le code de malade qu'ils ont foutu me suis rendu compte que c'etait simplement netu (qui vient juste de revenir)

Du coup je fais la modif de suite.

**Comment by yodidon** [comment]
Je suis curieux de comprendre comment fonctionne les hosters

**Comment by razorex** [comment]
dsl

**Comment by TmpName** [comment]
Lol, c'est pas un probleme @razorex 
Now au moins ca fonctionne.

**Comment by yodidon** [comment]
@TmpName  je vais essayer de comprendre avec un exemple pour l’instant ça reste flou la méthode qui permet d’extraire le lien

**Comment by TmpName** [comment]
Ben quand tu as du bol, c'est la meme methode que tu utilises pour recuperer les titres des films, un simple regex.

**Comment by yodidon** [comment]
> Ben quand tu as du bol, c'est la meme methode que tu utilises pour recuperer les titres des films, un simple regex.

Le truc c’est que pour afficher la page Sur les site avec le code du hoster c’est un peux galère

**Comment by TmpName** [comment]
Pas compris, tu cherches a afficher le code html de la page qui lance la video pour recuperer le lien video ?

**Comment by yodidon** [comment]
Oui tout comme j’affiche le code des pages pour les titres et autres ...

**Comment by TmpName** [comment]
Ben alors je pense que ca doit etre la meme methode.
De mon coté
- Firefox a jour + console developpeur + afficher source
- Vielle version de frefox + httpfox + afficher source

Et il faut chercher dans la page (quand c'est en clair) un lien direct vers la video.

**Comment by razorex** [comment]
Oui @yodidon c'est chaud les hosters. si tu veus vraiment te lancer prend un site présent dans vstream analyse le hoster

**Comment by razorex** [comment]
on clos
