### ISSUE TITLE
MISE A JOUR 7.7.1 VSTREAM NON FONCTIONNEL

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2792]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4363406/kodi.log)
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

Je viens tout juste d,installer la nouvelle MAJ officielel de vstream et puis plus rien ne fonctionne. Incapable de voir les liens a l,interieur d'unesource ou encore d'ouvrir certaines sources.  Mon dernier log est attache

J'utilise une Nvidia Shield
Kodi Leia 18.6

**Comment by razorex** [comment]
Ouah tu a plein d'erreur

**Comment by alKODIque** [comment]
@razorex 
Je sais!

Mais que ce passe-t-il et le pourquoi.... ça je ne sais pas

**Comment by Arias800** [comment]
C'est liée a cette modif mais faut trouver pourquoi : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/efec892543ed0faab9562e135bd90120750cb2d7#diff-7ad29b67df78b514d82203e04cf89769

**Comment by razorex** [comment]
je regarde sinon on fais un reverse...

**Comment by alKODIque** [comment]
grand merci pour ton aide @razorex  et    reponse rapide

**Comment by Arias800** [comment]
Je croit que j'ai trouver. En faite ca bloque la recherche visuel.

**Comment by Arias800** [comment]
C'est bon j'ai trouver, @razorex j'envoie la correction.

**Comment by Arias800** [comment]
C'est bon c'est corriger dans la bêta : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/651c9747ed8f515b8e6fa6e640fe96f502b59e09

**Comment by alKODIque** [comment]
Merci @Arias800 
Je teste et vous reviens si problème

**Comment by razorex** [comment]
ok je vois mon erreur, bizarre que çà marchais chez moi.

**Comment by alKODIque** [comment]
Je confirme qu’avec la correction, ça fonctionne pour moi

Encore merci !
