### ISSUE TITLE
ZONE-TELECHARGEMENT.STREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#2794]
Zone Annuaire viens de créé un Site de Streaming nommé "Zone-telechargment.stream"
au https://www.zone - telechargement . stream/. Est-ce qu'on pourrais l'avoir dans vStream ?

**Comment by sizanic** [comment]
Alors oui c'est un site officiel de ZT, il le décrive ici : 
https://www.zone - annuaire . com/new/69913-nouveau-site-streaming.html

On y retrouve les même films mais un seul lien pour regarder en streaming.

C'est un lien uptostream, et le site Z_Annuaire propose aussi un lien uptostream.
Si c'est le même, il n'y a pas d’intérêt (surtout qu'il est proposé en premier).

Mais je vois peut-être une petite différence.
En passant par Zone Annuaire, j'ai un message qui me dit que je peux regarder le flux uptostream en tant qu'invité, donc limité dans la durée !

Je n'ai pas ce message en passant par le nouveau site ZT.stream.

Alors si ça veut dire qu'on passe par leur compte, là c'est intéressant de récupérer le flux.

-> quelqu'un peut le confirmer ?

**Comment by ludopotte** [comment]
Je confirme @sizanic tu peux récupérer le flux sur Zone Annuaire que sur Zone-Telechargement.stream tu peux pas.
