### ISSUE TITLE
Problème avec affiche

### ISSUE THREAD

**Issue by yodidon** [Kodi-vStream/venom-xbmc-addons#2800]
Petit question,
Si je récupère bien le lien de l’affiche mais il ne s’affiche pas sur vstream.
Si je colle le lien dans chrome message d’erreur
Si je colle le lien dans Firefox l’affiche s’affiche bien.
Dans quel direction je dois chercher ?

**Comment by razorex** [comment]
Tu est sur de récupérer le bon lien? avec le regex????

**Comment by yodidon** [comment]
Oui j’ai bien le bon lien c’est sûr french stream

**Comment by yodidon** [comment]
Heu oui streammavie pardon

**Comment by sizanic** [comment]
J'avais le même problème avec Zu_Stream hier.
L'url de l'affiche est bien celle récupérée par Vstream (copier/coller depuis Eclipse 😉  ) et une fois coller dans chrome, l'image s'affiche.

Plus le problème aujourd'hui.

Mais hier il y avait une protection CloudFlare  qu'il n'y a plus aujourd'hui.
Donc je me dis qu'une fois passé la protection avec le navigateur on peut accéder aux affiches.
Mais pas avec Vstream, alors qu'on a réussi à récupérer les titres et les descriptions.

**Comment by razorex** [comment]
moi dans mon log j'ai çà: alors comment faire??
`CTextureCacheJob::GetImageHash - unable to stat url http://streamavie.com/wp-content/uploads/2020/03/2kNnf7BwRCEm4bcFkdiE0T4U25s-185x278.jpg`

**Comment by Arias800** [comment]
Alors le liens de @razorex pointe vers rien, donc forcement ca ne s'affiche pas xD
Il y a par contre un problème récurent dans l'affichage des images : c'est quand Cloudflare est activer puisque Kodi ne décode pas CF.

**Comment by razorex** [comment]
@Arias800 pourtant depuis le fichier source  clic droit ouvri çà marche, par contre copier coller non..

**Comment by TmpName** [comment]
C'est a cause des cookies je pense.
Regardes si dans un de tes 2 tests il manque pas les cookies dans la requete.

A une epoque on utilisait la fonction GetHeadercookie() qui est dans le fichier cloudflare pour recuperer les images bloquées. Mais ca faisait tres lourd pour une protection provisoire.

**Comment by razorex** [comment]
Nekosama aussi a le même pb de cloudflare donc pas de thumb
