### ISSUE TITLE
Hello J'ai plus rien suis je le seul (Polynésie Française)

### ISSUE THREAD

**Issue by pplanteg** [Kodi-vStream/venom-xbmc-addons#2801]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [ Android]
-  Appareil [MXQ4]
 - Version Kodi  [18]
- Version Vstream LAST

**Nous devons le reproduire**
Pour cela il nous faut:
- TOUS
- TOUS

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by alKODIque** [comment]
Étant une utilisatrice de UPTOBOX Premium, je suis également à la recherche de liens fonctionnels puisque ça ne fonctionne plus.... C’est effectivement difficile de trouver des sources mais je m,en tire assez bien avec Film i l l i m i t e pour les films et kaydo pour les séries. Par contre le temps de démarrage est souvent très long

**Comment by ludopotte** [comment]
Faut utiliser la Source "Zone-Telechargement" et Tirezo

**Comment by Arias800** [comment]
@pplanteg Il nous faudrait les logs pour avoir une indication sur l'origine du problème.

**Comment by razorex** [comment]
@alKODIque kaydo ne fonctionne pas chez moi tu a changé tes DNS??

**Comment by sizanic** [comment]
Hello @pplanteg  tu n'es pas le seul.

Nous travaillons sur la résolution de plusieurs causes.
Il faudra attendre les mises à jours ...
