### ISSUE TITLE
Bande annonce ne fonctionne pas sous libreelec

### ISSUE THREAD

**Issue by Laurentfincher** [Kodi-vStream/venom-xbmc-addons#2802]
Salut, 
Je suis sous raspberry pi 4 avec la version libreelec 18.6 leia soit la 9.2.1 et les bandes annonces ne fonctionnent pas. Vstream le signale une erreur. Je suis sous la version 0.0.3

J'ai regardé sur les forums, je ne sais si ce problème est isolé ou non
Merci

**Comment by TmpName** [comment]
Tu as quelle version de Vstream ?
Tu as eu la version intermediaire ?

**Comment by razorex** [comment]
@Laurentfincher merci de nous tenir informer que l'on fasse vivre cette issue??

**Comment by sizanic** [comment]
Pour lire la version, il faut afficher la fenêtre paramètres de Vstream.
La version est dans l'onglet "A propos".

Je suis en version 0.7.72 et la Bande Annonce se lance.
Mais c'est vrai qu'elle ne démarre pas aussi vite qu'avant, il faut attendre parfois 5 secondes.
