### ISSUE TITLE
Netu pas de buffering 

### ISSUE THREAD

**Issue by mickve** [Kodi-vStream/venom-xbmc-addons#2803]
**Décrivez le bug**
Bonjour , netu démarre nickel , le problème vient du buffering ! Pas de chargement en mettant pause! Alors que sur les autres hosters je n ai pas ce soucis! Une solution ?

**Votre system**
 - OS: android
-  Appareil :beelink gt king 
 - Version Kodi 18.6
- Version Vstream 

**Nous devons le reproduire**
Pour cela il nous faut:
- Série streaming hd ou autre
- Prodigal son
- Netu

**Comment by TmpName** [comment]
C'est normal, c'est le mode de fonctionnement de netu.
Il ne fournit pas un fichier que tu peux mettre en buffer, mais un m3u qui pointe vers plein de petit fichiers.

**Comment by razorex** [comment]
close
