### ISSUE TITLE
Nouveaux hosters

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2804]
De nouveaux hosters peut être éphémères.
-Sur mesfilms [lien vers le hoster ](https://www.core1player.com/v/0z1jmulxyq24j-p) Core1player
 mais aussi le film [Hors normes](https://www.mesfilms.stream/film/hors-normes/) Dood.watch
-sur streamink le même [lien vers le hoster](https://dood.watch/d/gojl794c5woe) Dood.watch

j'ai aussi Hydrax si çà parle a qqun mais sur un site pas encore dans vStream.
PS c'est peut etre l'occasion de détaillé un hoster en pas à pas pour que ceux qui le désire puissent comprendre la démarche.

**Comment by razorex** [comment]
J'en profite streamz ne fonctionne pas chez moi j'ai la "pub" streamz qui me dit de desactiver mon adblock et vous????

**Comment by sizanic** [comment]
c'est quelle source streamz ?

**Comment by TmpName** [comment]
@yodidon en a trouvé un autre "supervideo" mais je sais pas encore ou.
Apres pour le coté ephemere faut voir le nombre de sites qui s'en servent ou le nbre de film dessus.
Certains hosters se font en 15mn.

La par contre j'ai pas trop d'idée, plutot dood.watch qui est au moins sur 2 sites, le temps d'avoir des infos sur supervideo ?

**Comment by razorex** [comment]
c'est normal je le trouve que sur un site et il est pas dans v>Stream
je vous donne un [lien](https://streamingk.net/vampires-2020-saison-1-complete-streaming-telecharger/) pour streamz

**Comment by razorex** [comment]
Dood est sur plusieurs sources

**Comment by razorex** [comment]
j'en profite peut on faire un re.sub sur:
`https://cut-urls.com/st?api=d6e46f2fcd4bfed906a9f3ecbbb6830e862b3afb&amp;url=`
j'ai fais des test mais çà ne fonctionne pas:
`https:..cut-urls.com.st?api=\w+&amp;url=`
j'ai même mis l'url complete çà fonctionne pas non plus???

**Comment by razorex** [comment]
du coup oui j'ai été trop vite les liens streamz sont à viré.
j'aurais du vérifier avant de demander

**Comment by razorex** [comment]
j'en profite encore regex101 n'est plus accessible chez moi.

**Comment by TmpName** [comment]
Pkoi ils sont a virer ?
Suis en train de regarder la protection de streamz
Les fichiers marchent

- a condition de virer l'anti-pub
- la premier page contiendrait le code de la video dans un packed code
- puis on se retrouve avec une nouvelle page mais sans le code, du coup "voir le code source ne marche plus)

En fait il faut afficher toute les requetes et regarder la code source de la premier page.

Mais il pique comme site, y a du taff dessus, tu es sur qu'il vaut le coup ?

**Comment by razorex** [comment]
ok dsl alors fait I'm sorry.
Je sais pas s'il en vaut le coup, il est présent sur bcp de sources.
Après s'il est compliqués c'est peut etre qu'il va durer!!!!

**Comment by razorex** [comment]
Le fichier 'sites.json' sur le Git normalement ne sert plus à rien donc on supprime??

**Comment by yodidon** [comment]
Supervideo je la vois sur film illimité, l’URL me paraissait simple mais je n’ai pas réussi à le faire fonctionner

**Comment by MX10-AC2N** [comment]
Slt a tous, je suis pas sûr d'écrire au bonne endroit mais je vois que le sujet est récent donc j'en profites
https://films-pour-enfants.com/index.html
Voici un lien vers un site de vidéo légale mise à disposition pour les enfants bien classé par age, serait-il possible d'ajouter ce site au source de Vstream..
Autre chose : J'ai fait un update de Kodi vers la dernière version test, je suis donc sous Kodi 19 qui est passé en Python 3 d'où pas mal de galère avec tous mes add-ons et surtout le meilleur de tous Vstream qui n'est pas du tout compatible... Y-a-t-il un mise à jour de prévue vers python 3 pour Vstream.. Ne serait-il pas temps d'y penser..?
Merci, have a nice day..

**Comment by razorex** [comment]
@MX10-AC2N pas de monté de version en python 3 pour l'instant.

**Comment by razorex** [comment]
Du coup je reviens avec sendvid (frenchvid) sur mamcin il ne fonctionne pas.
J'ai corriger le fichier source mais il faut regarder du côté du hoster
un [lien](https://sendvid.com/embed/erero6xm) vers le hoster
Un [lien](https://www.mamcin.com/non-classe/plus-belle-la-vie-episode-4025-1/) vers la source si toutefois le précédent ne fonctionnait plus.

**Comment by TmpName** [comment]
Donc streamz je viens de retester, a mon avis on va pouvoir s'inspirer de flashx
Il suffit de faire une bonne requete, et le site memorise notre ip, apres ca la video fonctionne sur Vstream.

Faut juste trouver la requete, la du coup j'attend que ca me remette la video a la con pr chercher la bonne requete.

**Comment by TmpName** [comment]
@yodidon la ca va, c'est penard et c'est interessant pour toi.
Je viens de regarder le code pour supervideo, en fait la personne cache son code en utilisant la technique du packer.
Regardes en bas de la page, tu vas trouver quelque chose qui commence par 
`<script type='text/javascript'>eval(function(p,a,c,k,e,d)`

Tu peux faire un copier coller du code JS et le tester sur cette page http://matthewfl.com/unPacker.html

Et comme c'est un truc hyper classique Vstream possede deja l'outil pour le decoder, en exemple regardes le hoster beeload.

**Comment by razorex** [comment]
Recréer un hoster pour sendvid!!!.

**Comment by TmpName** [comment]
@Razorex yep je pense que c'est le mieux, vu qu'il sert pour plusieurs, et je connais pas les autres.

Tu es dessus la ?

Sinon je pense qu'on pourrait virer des hosters
- beeload
- cloudcartel
- Freshstream
- Pixsil

**Comment by razorex** [comment]
non je te laisse faire sendvid j'ai pas les compétences.

**Comment by TmpName** [comment]
Loool, tu parles.

**Comment by razorex** [comment]
Non je ne maitrise pas les hosters.
j'ai fait place net pour ces 4 hosters

**Comment by TmpName** [comment]
J'ai mit une version de sendvid qui marche pour mamcim

La je surveille streamz.

**Comment by razorex** [comment]
J'ai fais un replace au lieu d'un re.sub mais si la chaine de caractère change on affichera un hoster incohérent mais ca fonctionnera tjrs

**Comment by TmpName** [comment]
Bon nouvelle version de streamz. Pas pu tester car ca met 10 plombe a charger, mais j'ai une vraie url au lieu de celle qui donne sur la fausse video.

**Comment by TmpName** [comment]
@yodidon tu as trouvé pour supervideo du coup ?

**Comment by yodidon** [comment]
Pas encore 😞 j’ai un peu craquer sur ce hoster mais je vais m’y remettre ...

**Comment by TmpName** [comment]
Put1 j'ai jamais eu autant de posts a lire sur Vstream en une fois, et pourtant je passe presque tout les jours.

Trop de temps libre avec le confinement ^^.

Sinon, tu devrais t'en sortir en comparant avec l'exemple que je t'ai mis

**Comment by yodidon** [comment]
Oui j’ai commencés a regarder les trop de bières et les yeux qui piquent....

**Comment by yodidon** [comment]
Bon pour super vidéo j’y suis presque je crois que mon problème est le faite de gérer plusieurs format (720 et 1080) en effet mon regex renvoie 2 résultats mais je n’arrive pas à les afficher pour la sélection

**Comment by razorex** [comment]
Non il te reste de la bière.... moi je vais bientôt être en rupture lol.
Tu utilise le tableau d'affichage des qualités????

**Comment by TmpName** [comment]
Y a pas un exemple en commentaire pour le tableau des qualitées en bas du fichier ?

**Comment by yodidon** [comment]
Pour ma bières vous êtes les bienvenus, après faut aimer être au milieu de nul part mais dans les pins et prêt de l’océan :)
Je n’ai pas vu pour l’exemple je vais m’y remettre j’ai dû passer à côté

**Comment by TmpName** [comment]
En bas de la page > https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_un_hebergeur.py

Ca va tu as l'air bien placé, foret et ocean, me dit pas que tu as aussi la montage a moins de 200 km ?

**Comment by yodidon** [comment]
Pas 200 non mais 280 km ...

**Comment by yodidon** [comment]
j'ai bien trouvé le code pour afficher le tableau de format par contre ça ne fonctionne toujours pas :( je n'arrive pas à debugger....

**Comment by TmpName** [comment]
Met le code en ligne sur ton fork ?

**Comment by razorex** [comment]
Du coup je fais une relance pour core1player et dood personne veut s'y coller??

**Comment by yodidon** [comment]
> Met le code en ligne sur ton fork ?

Ok je fait ça

**Comment by yodidon** [comment]
> Du coup je fais une relance pour core1player et dood personne veut s'y coller??

Je veux bien essayer de regarder mais j’ai peur de pas être à la hauteur

**Comment by razorex** [comment]
Termine le tiens déjà, le reste çà attendra, tu a l'air plus doué que moi, mais partage ton fichier comme te la dit @TmpName.
merci pour ta proposition

**Comment by TmpName** [comment]
@razorex ben demain je prend le premier, core1player, toujours visible sur strmingk ?

**Comment by yodidon** [comment]
voila et merci pour votre aide ..
https://github.com/yodidon/supervideo.git

**Comment by yodidon** [comment]
Je viens de trouver mon problème le hoster marche 🤩

**Comment by razorex** [comment]
Du coup plusieurs hoster ne fonctionne plus et c'est côté vStream. 
Uptostream dans hoster : `window\.sources` deviendrait `window\.troll` mais j'arrive pas à voir après le décodage base64.b64decode.
netu, vumeo et d'autres.

**Comment by razorex** [comment]
Du coup pb de regex??

**Comment by yodidon** [comment]
Non bien plus bête ...j’avais pas importé le Cpaker et je plaçais mal le unpack ... :)

**Comment by razorex** [comment]
non @TmpName c'est sur mesfilms prend les liens  au début de l'issue ils sont encore valide.

**Comment by yodidon** [comment]
dood.watch c'est pas de la tarte pour mon niveau ....

**Comment by TmpName** [comment]
Core1player c'est bon c'etait frenchvid.
Pour Up2strm laisse tomber pour le moment, l'url dans troll est une blague ^^
Il faut decoder le JS.

**Comment by TmpName** [comment]
Pour dood ca pique un peu effectivement, je commence a me dire si ce serait pas plus facile de passer par leur fonction de dl.

- La page renvoit sur une autre page du type > dood.watch/e/ID
- Appel a la page >dood.watch/dood?op=get_md5&hash=XXXXXXXXXXx trouvable dans le code html
- Convertion de cette chaine avec la fonction openPlay()
-  Rajout a la fin de l'url le resultat de la fonction makePlay()

Fonction Makeplay 
```
function makePlay() {
  var pix_color = "";
  var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  var l = possible.length;
  var o = 0;
  for (; 10 > o; o++) {
    pix_color = pix_color + possible.charAt(Math.floor(Math.random() * l));
  }
  return pix_color + "?token=b5utfd6h2jorvsp55gyyqwly&expiry=" + Date.now();
}
;
```

Fonction Openplay
var _0xc771 = ["1", "replace", "Z", "a"];
/**
 * @param {?} att
 * @return {?}
 */
function openPlay(att) {
  /** @type {string} */
  var str = atob(att[_0xc771[1]](/\//g, _0xc771[0]));
  /** @type {string} */
  str = atob(str[_0xc771[1]](/\//g, _0xc771[2]));
  /** @type {string} */
  str = atob(str[_0xc771[1]](/@/g, _0xc771[3]));
  return str;
}
;

**Comment by Arias800** [comment]
Ils sont pénible a mettre du js de partout xD

**Comment by Arias800** [comment]
Bon bah du coup j'ai un code fonctionnel en passant par leurs fonction de dl xD

**Comment by Arias800** [comment]
J'ai ajouter Dood https://github.com/Kodi-vStream/venom-xbmc-addons/commit/e2a18e8ceb71913ef7e828813cb2b45d4baa6e07

**Comment by yodidon** [comment]
J'ai regarder le code , pas simple encore mais je commence à suivre, par contre je n'arrive pas à comprendre ça:
def __getIdFromUrl(self, sUrl):
        sPattern = "id=([^<]+)"
        oParser = cParser()
        aResult = oParser.parse(sUrl, sPattern)
        if (aResult[0] == True):
            return aResult[1][0]

        return ''

**Comment by TmpName** [comment]
Ca retourne le "id" d'une url.
"site.com/sefsdfddsfd?id=abcde" > ca retourne "abdce"

**Comment by razorex** [comment]
Du coup sur cinemay il y a vidload en hoster: un lien [ici](https://www.cinemay.li/films/19028-downhill.html) sous l'appellation french. Sauf erreur c'est en méthode POST.
si on peut me donné un hoster qui me servirait d'exemple je vais tenter de le faire. Sinon libre à vous..

**Comment by TmpName** [comment]
ClickOpen fait une requete post

**Comment by razorex** [comment]
Bon je ne fais voit pas ce que je dois récupérer la dedans... 
`var player=videojs("olvideo");

player.on("progress",function(){var e=Math.floor(100*player.bufferedPercent());console.log(e),document.getElementById("axqACoWkROKI")?7<=e&&e<8&&$.ajax({method:"POST",url:"/api/deep/",data:{fileId:"116445",reffer:"*ttps://www.cinemay.li/films/19028-downhill.html",tracker:"1928c9ed5c51daa487daf6e13aac7c95",percent:e}}):7<=e&&e<8&&$.ajax({method:"POST",url:"/api/deep/",data:{fileId:"116445",adblock:"1",reffer:"*ttps://www.cinemay.li/films/19028-downhill.html",tracker:"1928c9ed5c51daa487daf6e13aac7c95",percent:e}})});
player.on('play', function() {
$.ajax({
method: "POST",
url: "*ttps://www.vidload.net/vid/count.php",
data: { shorturl: "702b5202c1bbdde9"}
});
});`

**Comment by sizanic** [comment]
A partir du shorturl : 

*ttps:// www.vidload. net/e/702b5202c1bbdde9

**Comment by sizanic** [comment]
Je pense qu'il n'y a rien à récupérer.

Cherche plutôt de ce coté : 

en haut de la page /vid/702b5202c1bbdde9
tu récupère les valeurs de 
token=valeurToken
crsf=valeurCrsf

Puis tu appeles, en passant le cookie,
*ttps://www.vid load.net/ vid/
gone=valeurToken&oujda=valeurcrsf

ça va te retourner le mp4

(je n'ai pas testé, c'est juste en visualisant les url qui mènent à la vidéo)

**Comment by sizanic** [comment]
@razorex  t'as pu avancer sur ce hoster ?

**Comment by razorex** [comment]
non @sizanic et je n'y arriverais pas.

**Comment by sizanic** [comment]
Je vais essayé de le faire ce soir.

**Comment by sizanic** [comment]
Ce que j'avais imaginé : 

> en haut de la page /vid/702b5202c1bbdde9
> tu récupère les valeurs de
> token=valeurToken
> crsf=valeurCrsf
> 
> Puis tu appeles, en passant le cookie,
> *ttps://www.vid load.net/ vid/
> gone=valeurToken&oujda=valeurcrsf
> 
> (c'est peut être un POST)
> -> ça va te retourner le mp4

J'ai fait ce que j'ai dit, même pas besoin de passer le cookie : 
(petite subtilité, il y a un retour à la ligne à la fin du lien retourné)

```
    def __getMediaLinkForGuest(self):

        oRequest = cRequestHandler(self.__sUrl)
        sHtmlContent = oRequest.request()

        sPattern =  'var token="([^"]+)".+?var crsf="([^"]+)"'
        oParser = cParser()
        aResult = oParser.parse(sHtmlContent, sPattern)
        if (aResult[0] == True):
            aEntry = aResult[1][0]

            oRequest = cRequestHandler('https://www.vidload.net/vid/')
            oRequest.addParameters('gone', aEntry[0])
            oRequest.addParameters('oujda', aEntry[1])
            oRequest.addParameters('referer', self.__sUrl)
            oRequest.setRequestType(cRequestHandler.REQUEST_TYPE_POST)

            resolvedUrl = oRequest.request().replace('\r\n', '')
            return True, resolvedUrl

        return False, False
```

Et voilà !!

Hoster **vidload** => OK

**Comment by sizanic** [comment]
Voilà comment j'ai fait, **le secret est de partir de la fin.**
=> Aller jusqu'au mp4 et remonter les url.

Prérequis : utiliser Chrome

**1 - Récupérer le lien VidLoad**
Rien de compliquer.

![image](https://user-images.githubusercontent.com/47307622/78309900-9e2dfe00-754c-11ea-9f33-cc7cd03231c6.png)

**2 - L'ouvrir dans un nouvel onglet du navigateur**
Afficher les outils de développement Chrome avec Ctrl + Maj + i.
Afficher l'onglet de développement **Network**

Lancer la vidéo et analyser le network : 
![image](https://user-images.githubusercontent.com/47307622/78310275-b5212000-754d-11ea-9e7f-22cd087849f8.png)


Je vois un fichier mp4, je cherche dans les liens précedents d'où peut venir l'url de ce mp4. Il n'y a qu'un seul lien juste au dessus, et je trouve rapidement que le lien mp4 est la réponse du lien vid/ .

**3 - Analyse de la requête**

Il me suffit donc de recréer cette url /vid pour obtenir le fichier mp4.

Je regarde ce lien /vid : 
L'url et la méthode : 

![image](https://user-images.githubusercontent.com/47307622/78310592-b141cd80-754e-11ea-81f5-38fae15e3baa.png)


et les paramètres : 

![image](https://user-images.githubusercontent.com/47307622/78310687-febe3a80-754e-11ea-9663-4d7897e087f2.png)


**4 - Obtenir les paramètres**

Je dois trouver comment obtenir les valeurs de **gone** et **oujda**.

En terme de navigation, je suis arrivé jusqu'ici depuis l'étape 2.
Les paramètres ne se trouvent donc pas sur le site cinemaay mais bien depuis l'url de l'étape 2.

En fait, lorsque j'ouvre les outils de dev, j'ai déjà raté des trames.
Alors je rafraîchie la page (F5 ).

![image](https://user-images.githubusercontent.com/47307622/78311086-2b268680-7550-11ea-89bc-e6429f76f235.png)


La première requete est bien l'url de la page sur laquelle je me trouve.
Et dans cette page, dans la réponse en version html, je retrouve rapidement les paramètres !


**5 - TUTO**

Oui, il faudrait que je sorte ces explications de ce sujet pour en faire un tuto.

**Comment by TmpName** [comment]
Lol, Beau tuto :)

**Comment by sizanic** [comment]
Donc tu l'a pas lu jusqu'au bout, c'est le point 5 ! :wink:

**Comment by razorex** [comment]
Pu.... sa démarre mal j'utilise firefox.. Bon j'ai testé sur chrome c'est pas aussi clair que chez toi. C'est pas gagné mais merci pour tes explications.

**Comment by TmpName** [comment]
@razorex tu as la meme chose sur firefox mais c'est ctrl + maj +  E (pour le network)

**Comment by razorex** [comment]
lo je sais @TmpName je blaguais
