### ISSUE TITLE
Zone telechargement HS

### ISSUE THREAD

**Issue by f3n3k** [Kodi-vStream/venom-xbmc-addons#2805]
ZT ne fonctionne pas
quand on clique sur ZT dans la section film HD, on obtient un message 
Aucune information

et donc la liste est vide

Merci par avance

Cordialement et merci pour cette app ;)

**Comment by sizanic** [comment]
Je n'ai pas ce probleme.
Je suis toujours en version 0.7.7.
Quelle version utilises-tu de Vstream (0.7.71 ou 0.7.72 ?)

-> Le problème est-il toujours présent aujourd'hui ?

Dans ZT, il y a bien un souci avec les liens upToStream et UpToBox qui ne fonctionnent plus, la discussion sur leur résolution est ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2793

**Comment by f3n3k** [comment]
Je suis en 0.7.7, et non quand je clique sur film qualité HD, ensuite Zone téléchargement, j'ai ensuite une liste vide et c'est marqué Aucune information.

**Comment by Mobius69** [comment]
Idem en 0.7.72 
Uptobox en passant par ZT j'ai le message fichier introuvable quasi immédiatement en lançant le lien uptobox

**Comment by ludopotte** [comment]
Moi sur ZT, j'ai le lien uptobox qui fonctionne mais à la place de la vidéo, j'ai une pub

**Comment by whynotnow2** [comment]
Même souci. Ça marche en version 720p et pas 1080p

**Comment by f3n3k** [comment]
Merci pour la pollution de mon post, bref pas de solution...

**Comment by Arias800** [comment]
Va dans les paramètres de Vstream, ensuite dans l'onglet A propos. Est ce que dans Version tu a bien la version 0.7.72 ?

**Comment by Mobius69** [comment]
@Arias800 ça ne fonctionne pas en 0.7.72

**Comment by Arias800** [comment]
Pour info c'est pas le même problème ,toi c'est un problème liée a uptobox tandis que lui c'est un problème liée a zone telechargement. Donc merci d'allez dans une issue qui parle du même problème que toi : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2793

**Comment by Mobius69** [comment]
Au temps pour moi!!!

**Comment by f3n3k** [comment]
Hélas, j'ai voulu tout réinstaller et j'ai un soucis de dépendance maintenant...
J'ai tout remis à zero, reinstall Kodi, install le repo vstream, mais hélas maintenant quand je veux installer Vstream, il me dit qu'il ne peut pas car il manque les dépendance suivantes:
URLResolver
Simplejson
F4mproxy

**Comment by Arias800** [comment]
URLResolver et F4mproxy sont des dépendances optionnel donc ils ne bloquent pas l'installation par contre c'est Simplejson qui bloque tout. Peut etre que c'est un soucis temporaire du coté de Kodi, car l'installation des dépendance est gérer automatiquement par Kodi.

**Comment by f3n3k** [comment]
C'est bon l'installation c'est faite, mais toujours la dépendance F4mproxy qui manque, comment l'ajouter ?
Sinon je suis bien en 0.7.72 et enfin Zone téléchargement est accessible ;)

Merci Arias800, mais si tu as une aide pour le F4mproxy

**Comment by Arias800** [comment]
F4MProxy et F4MTester sont disponible ici : https://kodi-vstream.github.io/repo/
Je marque l'issue comme résolu.

**Comment by f3n3k** [comment]
Merci encore à toi Arias800 !!!!!

**Comment by Mobius69** [comment]
@Arias800  j'ai une question: a quoi servent f4mproxy et f4mtester stp?
Ils ne sont pas installés chez moi.
Par avance merci !

**Comment by Arias800** [comment]
Ils servent seulement pour l'iptv. C'est d'ailleurs pour ça qu'ils optionnel.

**Comment by Mobius69** [comment]
Ah ok merci donc ça me sera utile avec PVR IPTV simple client ou j'ai un abonnement iptv j'imagine.
Merci pour l'info!

**Comment by Arias800** [comment]
Ce ne sera pas utile puisque IPTV Simple Client n'utilise pas ses 2 addons.

**Comment by Mobius69** [comment]
Ok merci
