### ISSUE TITLE
Proposition de site pour source vidéo spécial enfants

### ISSUE THREAD

**Issue by MX10-AC2N** [Kodi-vStream/venom-xbmc-addons#2806]
Bonjour a tous,
N'ayant pas les compétences pour ajouter une source.py je crée ce post.
Je vous propose donc le site    htt ps://films-pour-enfants.com/
c'est un site dont j'ai eu le lien par un mail de la maitresse de mon fils qui est en CP, toute les vidéos sont gratuites et sont classé par ages.
Je ne sais pas s'il est possible d'intégrer ce site dans les sources Vstream mais je pense qu'il intéresserait bon nombre de parents qui cherche des contenus pour leurs enfants autre que ce que l'on trouve habituellement..
Le site mérite en tout cas d'aller y jeter un oeil..
A bon entendeur, et surtout a bon encodeur..
Merci a vous..

**Comment by razorex** [comment]
Du coup j'ai commencé à regarder @MX10-AC2N , pour info il y a "YOUTITOU" sur vStream qui propose le même type de contenu.

**Comment by MX10-AC2N** [comment]
Merci @razorex , en effet il y a déjà YOUTITOU mais je trouve les contenus pas top, top.. Alors que sur films-pour-enfants.com on a des Enseignants de l'école primaire et producteurs de films d'animation, dont le travail les a conduits à s'intéresser à la dimension éducative des films et des courts-métrages pour le jeune public. Vraiment pour le coup je trouve ce site super intéressant et surtout avec des contenus exclusifs..
J'espère qu'une intégration dans Vstream sera possible.. Bon courage et encore merci...

**Comment by razorex** [comment]
@MX10-AC2N est ce que tu veut que l'on récupère la fiche pédagogique?????

**Comment by razorex** [comment]
Bon source en place

**Comment by MX10-AC2N** [comment]
@razorex 
je n'arrive pas a trouver la source, pourtant Vstream mis a jour d'hier..

**Comment by TmpName** [comment]
Salut. C'est normal, il faut qu'on valide une MAJ ou que tu copie le fichier toi meme.

**Comment by MX10-AC2N** [comment]
@TmpName Merci, et est-ce qu'une validation de MAJ est prévu prochainement ? Sinon peux-tu m'expliqué vite fait la manip pour copié le fichier moi-même..

**Comment by TmpName** [comment]
Le fichier est la https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/filmspourenfants.py
A copier avec la methode que tu veux au meme endroit sur ta machine

Pas de dates prevues pour la MAJ, je sais meme pas si on fait une petite ou une grosse.

**Comment by MX10-AC2N** [comment]
@TmpName d'acc, je vais tenter la manip du coup.. Merci encore.. Et bon courage en ces temps de confinement..
