### ISSUE TITLE
La navigation se fait bien mais je n'aboutis à aucun film

### ISSUE THREAD

**Issue by bdeblock** [Kodi-vStream/venom-xbmc-addons#2807]
Bonjour, quand je navigue via n'importe quel chemin (flim, série, documentaire), j'arrive jusqu'au titre voulu et quand j'essaye de le lancer avec "ok", il m'affiche la page Videos/VStream:vu avec un dossier et ".." donc retour en arrière ou quand j'essaye info et lire la vidéo, ça tourne et ne charge rien.
Ci joint mon fichier log (où j'ai essayé de lancer plusieurs séries / documentaires).
Merci par avance de votre aide.
[kodi_vStream.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4385865/kodi_vStream.log)

**Comment by razorex** [comment]
ton souci devrait être réglé avec la prochaine mise a jour.

**Comment by bdeblock** [comment]
Merci, j'attends donc la mise à jour pour je l'espère clore ce fil

**Comment by TmpName** [comment]
@razorex tu parles de la derniere ou faut en refaire une ?
Je viens de lire le log, y a de gros prb de config ?

**Comment by razorex** [comment]
non @TmpName  je compte surtout sur le fait qu'il n'ai pas la dernière version 0.7.72.
J'ai regardé mes log je n'ai rien vu

**Comment by TmpName** [comment]
Nope je parlais de son log ^^.
Et y a des problemes avec la Version 0.7.72 ? je tourne avec, j'ai encore rien vu ? (Elle a peine 5 jours)

**Comment by razorex** [comment]
Non justement elle corrige mes erreurs..

**Comment by bdeblock** [comment]
J'ai installé la dernière version 0.7.72 avant d'envoyer mon log. Donc d'après ce que je comprends, le problème n'est pas au niveau de vStream mais comme indique @TmpName  "Je viens de lire le log, y a de gros prb de config (et des erreurs dans plusieurs plugins) ?". Une piste pour corriger ces erreurs ?

**Comment by TmpName** [comment]
Ben franchement c'est juste un gros bordel, un exemple d'erreur

>INFO: ADDON: cpluff: 'Could not read plug-in directory /usr/lib/kodi/addons: No such file or directory'

> erreur dans l'addon service.tvh.manager

> erreur dans trakt

> ERROR: CVideoPlayer::OpenInputStream - error opening 

Quand tu essayes un lien de Vstream

>2020-03-26 08:47:39.517 T:1461711584   ERROR: COMXImageFile::GetCodingType error unsupported image format

Des problems pour lire des images

>2020-03-26 08:45:02.652 T:1410331360   DEBUG: CAddonSettings[plugin.video.vstream]: failed to find definition for setting home_update. Creating a setting on-the-fly...

En boucle, comme si ton kodi avait un probleme de droit sur le fichier, il arrive pas a mettre en place les setting.

**Comment by bdeblock** [comment]
Ok, je n'ai pas grand chose sur mon kodi donc je fais le ménage dans mes add-ons. Comme le problème vient de moi, je clos également le sujet. Merci pour votre aide et pour l'appli.

**Comment by TmpName** [comment]
J'ai pas dit que le probleme ne venait que de toi, mais il y a quelques soucis sur ta machine oui.
