### ISSUE TITLE
Débit de lecture flux video est très bas

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#2808]
Bonjour a tous
J ai un souci .
Lorsque je lance la lecture d une video en streaming depuis kodi (par exemple un film ou serie dans vstream), le debit ne depasse pas les 800ko/s 
Je viens de lancer la lecture de ce même film avec vlc player et mxplayer et là , la lecture est a pleine vitesse 1,6 mo/s .
J ai même désinstallé kodi mais c'est toujours la même chose.
J ai installé l addon speedtest et le resultat est ok
![20200326_134949](https://user-images.githubusercontent.com/42334843/77649209-bc529780-6f69-11ea-9885-8d2a812ba82b.jpg)

Donc a priori kodi n est pas le problème, mais c'est vstream
Est ce un problème de paramétrage ?

Merci de votre aide

J ai essayé avec plusieurs films et serie ex : 
L episode 9 de Picard en 1080p ( zone téléchargement)
Le film Bloodshot en 1080p   ( zone téléchargement)

Et les deux ne depassent pas les 824ko/s , en les lisant depuis Vstream , mais atteignent 1,6mo/s dans des lecteurs externes (mx player et vlc)

Vstream 0.7.72
Kodi 18.6
Android 7.1.2
3goRam
![20200326_140600](https://user-images.githubusercontent.com/42334843/77649954-fbcdb380-6f6a-11ea-8914-05c2cbb25da8.jpg)

J ai même désinstallé et réinstallé kodi

**Comment by TmpName** [comment]
Hello, le film saccade ?

**Comment by falciatrice10** [comment]
Ben oui a 800k , ce n est oas suffisant

**Comment by TmpName** [comment]
Tu aurais pas un autre addon de streaming pour savoir si ca vient de Vstream ou du moteur de rendu video de kodi ?

**Comment by falciatrice10** [comment]
T en as un a me proposer ?

**Comment by TmpName** [comment]
Venom et exodus ?

**Comment by falciatrice10** [comment]
> Venom et exodus ?

Pareil, ca ne depasse pas les 826ko/s

**Comment by TmpName** [comment]
OK, donc faut voir si il n'y a pas des setting speciaux dans kodi.
Tu connais le fichier advancedsettings.xml ?

**Comment by falciatrice10** [comment]
> OK, donc faut voir si il n'y a pas des setting speciaux dans kodi.
> Tu connais le fichier advancedsettings.xml ?

Non, non

**Comment by sizanic** [comment]
Regarde dans les paramètres de KODI : 
Système -> Accès internet -> Limiter la bande passante

=> C'est bien sur NON ?

**Comment by falciatrice10** [comment]
> Regarde dans les paramètres de KODI :
> Système -> Accès internet -> Limiter la bande passante
> 
> => C'est bien sur NON ?

Elle est mise sur NON.

**Comment by falciatrice10** [comment]
Pensez vous que ça puisse venir de urlresolver ? Une mauvaise configuration peut etre ?

**Comment by TmpName** [comment]
Ben il te suffit de tester sans lui. Qu'ils aient negocié un debit non bloqué mais bridé ....

Sinon https://kodi.wiki/view/Advancedsettings.xml

Moi je testerais ici https://kodi.wiki/view/HOW-TO:Modify_the_video_cache le tag readfactor, c'est la valeur avec laquelle kodi rempli le cache.

**Comment by lebigboss** [comment]
Ça vient de ton fichier advancedsettings.xml
Configure le comme ça 
![Screenshot_20200405-185608](https://user-images.githubusercontent.com/12912677/78504722-46bba800-776f-11ea-9703-383901d239d1.jpg)

**Comment by falciatrice10** [comment]
Bonjour
J ai dû tout formater et réinstaller le firmware.
Maintenant ce problème est réglé
Merci pour tout
