### ISSUE TITLE
alldebrid + vstream

### ISSUE THREAD

**Issue by snake83910** [Kodi-vStream/venom-xbmc-addons#2809]
bonjour 
je n'arrive pas a faire marcher alldebrid sur vstream

**Comment by alKODIque** [comment]
@snake83910 
Je suis une abonnée premium de UTB mais depuis leurs récents changements ponctuels qui causent des problèmes avec vStream, je partage un compte Alldebrid avec ma fille. je n’ai aucun problème à l’utiliser à l,intérieur  de vStream alors est-ce possible que tu aies mal fait la configuration?

vStream offre la possibilité d’utiliser URLresolver seulement... la configuration de ALLDEBRID se fait donc à l’intérieur de cet additiel et non via vStream. 

Via URLresolver, dans la section « Universal Resolver » configurer ALLDEBRID COMME SUIT:
1- Priority: 90
2- Enabled: cocher
(Cocher ensuite les autres paramètres qui te concerne)
Tout de suite après, (et c’est très important) :cliquer « sauvegarder »
Revenir ensuite sur la même écran de configuration et seulement là, clique sur « (Re)Authorize M’y account » puis, « ok »

Une fois ton compte ALLDEBRID, autorisé, retourner dans les paramètres de vStream , section « Premium/Login » et tout au bas de la page, cocher « Passer par URLresolver ». Ne pas oublier de sauvegarder le paramètre en appuyant sur « ok »
Et voilà... 
il est important de suivre l’ordre précis de ces étapes pour que Alldebrid fonctionne

**Comment by Lioon2** [comment]
Bonjour,

Alldebrid va changer son api à partir du 1er mai, est-ce que ça change quelque chose pour vstream? https://docs.alldebrid.com/v4/#general-informations 
je dois peut être me rapprocher de urlresolver?

Merci

**Comment by TmpName** [comment]
Oui, Vstream ne l'utilise pas, c'est urlresolver qui peut etre utilisé (et qui s'en sert), mais la on ne le gere pas non plus.

**Comment by sizanic** [comment]
@Arias800  viens de faire une correction du coup pour passer l'API alldebrid en V4, pour la source extrm_down.

Je ne sais pas si il peut nous en dire plus ...

**Comment by Arias800** [comment]
Oui c'est pour basculer sur l'API V4, mais de toute façon elle est juste utiliser pour extreme download. Le reste c'est pas Vstream qui gère.
