### ISSUE TITLE
Android a encore frapper

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2810]
Comme toujours Android a des bugs très bizarre. Et cette fois c'est "cloudscraper" qui pose problème. La raison ? Le nom du dossier, il suffit de le renommer en "cloudscrape" pour que l'appareil veuille bien accepter le dossier.
Donc du coup est ce que quelqu'un peu s'occuper de renommer le dossier ? (vu que l'on ne peut pas le faire depuis le site).

**Comment by ludopotte** [comment]
[https://github.com/ludopotte/vStream[](url)

**Comment by ludopotte** [comment]
J'ai renommé le Dossier "cloudscraper" disponbile dans mon Patch au https://github.com/ludopotte/vStream/

**Comment by TmpName** [comment]
Ben le soucis c'est que
1 - faut changer les appel dans le code
2 - c'est une lib externe, le but c'etait de la supporter officiellement, et de profiter des MAJ.

Y a pas moyen de contourner ca ?

**Comment by Arias800** [comment]
Si il y a une solution de contournement je ne l'ai pas trouvé. Je pense que c'est surtout un problème de nombre de caractère.

**Comment by TmpName** [comment]
En place, mais pas testé, j'espere que ca va pas foutre le bordel.

A mon avis la prochaine MAJ va devoir etre complete ....
