### ISSUE TITLE
Uptobox problem - filename and direct subtitle download

### ISSUE THREAD

**Issue by simpajunky** [Kodi-vStream/venom-xbmc-addons#2812]
Dear sir,
I cannot directly download movie subtitle bcs when i play a movie it plays with name Uptobox (no full name of movie) so i need manually search for subtitle. Can you fix direct subtitle download without typing via keyboard on remote tv adapter.
Thanks

**Comment by sizanic** [comment]
@simpajunky 
this answer is not for you but to the dev team about your request.

Pour traduire, les sous-titres ne se chargent pas car au moment de lancer le film, ce n'est pas le nom du film mais le nom du host (exemple : uptobox).

Pas la peine de lui demander pour quelle source, le cas est visible dans plusieurs sources.

Il faudrait voir si on peut passer le nom du film dans tout les cas lorsqu'on appele le téléchargement des sous-titres.

**Comment by TmpName** [comment]
C'est pour les cas ou les sous titre ne sont pas sur la video originelle ?
En utilsant la fonction de kodi pour les ST ?

**Comment by yodidon** [comment]
sauf erreur avec opensubtitle ça fonctionne

**Comment by TmpName** [comment]
Or perhaps https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2877
