### ISSUE TITLE
Fichier introuvable

### ISSUE THREAD

**Issue by freddykrueger59** [Kodi-vStream/venom-xbmc-addons#2813]
Bonjour
Depuis quelques jours je n'arrive plus à regarder quoi que ce soit
A chaque fois que je clique sur un lien j'ai comme réponse fichier introuvable
Savez vous quel est le problème  ?
J'ai essayé sur plusieurs Host comme ZT , TIREXO, KEPLIZ etc...
Je précise que j'utilise principalement les liens Uptobox
Merci pour votre aide

**Comment by yodidon** [comment]
Sur quelle version de Kodi et vstream ?

**Comment by TmpName** [comment]
Si tu n'utilises que up2box > https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2793

**Comment by freddykrueger59** [comment]
Oui je n'utilise que Uptobox sans debrid

**Comment by Che-debarras** [comment]
C'est le même bug que j'ai signalé ça concerne pas que uptobox  et pas mal de souce mais ya eu des corrections notamment gounlimited j'ai pas retester les autres (netu frenchvid mixdrop etc.. qui bug)
J'essayerais des que j'ai le temps de faire un bilan

**Comment by sizanic** [comment]
@freddykrueger59 

Le sujet est déjà suivi dans ces deux threads : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2793
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2811

Si tu es d'accord, merci de cloturer ce sujet.

**Comment by freddykrueger59** [comment]
> @freddykrueger59
> 
> Le sujet est déjà suivi dans ces deux threads :
> #2793
> #2811
> 
> Si tu es d'accord, merci de cloturer ce sujet.

D'accord .merci beaucoup pour votre aide
