### ISSUE TITLE
Bug Gounlimited

### ISSUE THREAD

**Issue by adsav1** [Kodi-vStream/venom-xbmc-addons#2814]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

Plus aucun fichier ne se lance via l'hebergeur Gounlimited sur le site Serie Stream HD

**Votre system**
 - OS: AndroiD
-  Appareil Freebox mini 4k mais c'est pareil sur tous
 - Version Kodi  [16.17.18]
.- Version Vstream 0.7.7

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site Seriee Stream HD
- Le titre du fim/serie Tous
- Le nom du host (openload/vidzi) Gounlimited

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by yodidon** [comment]
Gounlimited est hs pour le moment

**Comment by adsav1** [comment]
Savez vous quand cela sera t-il réparé?

**Comment by yodidon** [comment]
Pas d’info pour le moment, de  nouveaux hoster ont été ajouté , ils seront présent lors de la prochaine Màj

**Comment by razorex** [comment]
Gounlimited fonctionne chez moi, j'ai poster une correction, et çà marche je viens de lancer un lien

**Comment by yodidon** [comment]
Alors il sera corrigé dans la prochaine , MAJ désolé pour cette contre information.

**Comment by adsav1** [comment]
Savez vous quand aura lieu la prochaine MAJ?

**Comment by razorex** [comment]
@adsav1 Normalement tu l'aura avec la mise à jour régulière, après il se peut que ce soit les liens sur la source que tu a utiliser qui ne fonctionne plus au quel cas on ne pourra rien faire, tu devra t'orienter vers une autre source.
