### ISSUE TITLE
Recherche de mot clé 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2817]
Bonjour

J'ai remarqué que quand on recherche une serie ou un film , la recherche se fait pour chaque mot, par ex City on Hill, les résultats comportes tous les titres qui on le mot City tous les titres qui ont le mot hill

Donc comment faire pour cherche l'expression "doom patrol"  et non pas doom et patrol séparément 

Les sites concernés sont
Cinemay
I-Anime
Otaku
StrmngK
Tirexo
ZT
Merci

**Comment by yodidon** [comment]
a ma connaissance cela dois se produire sur 3 ou 4 sites. si tu peux les repérer

**Comment by sizanic** [comment]
Oui, il faut la liste, car Il faut les traiter individuellement, chacun à sa spécificité.

**Comment by razorex** [comment]
sans compter que certaines sources ont une recherche pourri.

**Comment by yodidon** [comment]
Et je dirais même que certaines ne pourrons pas donner satisfaction j’ai regarder et ouï certaine méthode de recherche ne permette pas de trier

**Comment by razorex** [comment]
si c'est possible de faire un trie a mettre en places ur les sources qui retourne des résultats pas top.
pour info pour toi:
`#Si recherche et trop de resultat, on nettoye`
            `if sSearch and total > 2:`
                `if cUtil().CheckOccurence(sSearch.replace(URL_SEARCH[0], ''), aEntry[2]) == 0:`
                    `continue`
Certaines sources recherche tout azimut même dans le synopsis alors que nous user lamda de vStream c'est le titre que l'on recherche

**Comment by yodidon** [comment]
Oui mais pour donner mon avis il m’est arrivé de regarder un film ou autre que je n’aurais jamais regarder s’il n’était pas apparue sur ces recherche mais bon c’est vrais que l’on peut trier techniquement et même sur le nom rechercher et comparer au résultat

**Comment by razorex** [comment]
je suis d'accord avec toi pas facile de trouver un consensus.
après ce filtre ne supprime pas tout.

**Comment by yodidon** [comment]
A mons avis c’est pas si grave d’avoir des résultats , ce qui est plus pénible c’est quand il n’y en a pas, je comprend que les utilisateurs sont habitués a même que le logiciel leur propose des titre soit disant en fonction de ce qu’il ont regarder , moi je suis pas pour ...

**Comment by razorex** [comment]
Après le problème, pour moi, c'est que si tu recherche sur une source pas de souci. Mais dans le cas d'une recherche globale il faut filtrer sinon la recherche mettra du temps et il y aura des centaines de résultat. C'est peut être  une "option" a mettre en place.

**Comment by TmpName** [comment]
Et ca aide en cas de faute de frappe que la recherche ne soit pas trop "precise".

**Comment by Che-debarras** [comment]
Jai maj les sites qui sort des résultats plus qu'il n'en faut

**Comment by TmpName** [comment]
Du coup on cloture ?
