### ISSUE TITLE
nouvelles sources aux contenu HD

### ISSUE THREAD

**Issue by fagmixy** [Kodi-vStream/venom-xbmc-addons#2818]
bonsoir
est t'il possible d'ajouté les hosts qui utilisent un serveur local avec de multiples qualités
comme hdss.to , dpstream.top et jetanime.co
avec d'autres sources qui diffusent le contenu en HD comme
hds-streaming.com , fullstream.to , 6.french-streaming.com , stream-complet.to
est si c'est possible d'intégré le serveur streamax  au multiples qualités du host officielfilmillimité
merci beaucoup

**Comment by razorex** [comment]
Salut.
Alors stremax et déjà présent dans les hosters et pour info officielfilmillimité est une source.
Donne un titre de film??
Fullstream.to je l'ai commencé faut que je le termine..
Streamcomplet si tu avais regardé est déjà présent!!

**Comment by Wolsey20** [comment]
Bonjour,

il serait possible d'ajouter zone-warez.com et ddl1.best

Merci

**Comment by sizanic** [comment]
zone-warez.com a subit plusieurs changement de nom.

Il existe déjà dans vSteram sous le nom **tirexo**

**Comment by sizanic** [comment]
ddl1.best n'est pas un peu trop lent à répondre pour être intéressant ?
Ou c'est seulement en ce moment ?

**Comment by Wolsey20** [comment]
Merci pour ta réponse

**Comment by sizanic** [comment]
@Wolsey20 

Pour info, ddl1.best a été ajouté et sera disponible dans la prochaine mise à jour.

(zone -warez y est déjà sous le nom Tirexo) 

Merci encore pour tes propositions de sources.
