### ISSUE TITLE
Le site I anime ne marche plus

### ISSUE THREAD

**Issue by Hileb** [Kodi-vStream/venom-xbmc-addons#2819]
Je veux regarder des animes avec le site I anime (car il est très complet) en vf mais pour n'importe quel anime lorsque je veux lancer un épisode, il y a marqué : aucune information. Il y a quelque jours ça marchait mais plus maintenant, merci de m'aider s'il vous plait.

**Votre system**
 - OS: Android
-  Appareil: Samsung Galaxy J2
 - Version Kodi: 18.6
- Version Vstream: 0.7.7

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : I anime
- Le titre du fim/serie: D'abord Naruto mais le reste aussi
![Screenshot_20200401-220625](https://user-images.githubusercontent.com/63018408/78181681-191be980-7465-11ea-9e9e-d6b2a192661a.jpg)

**Comment by yodidon** [comment]
Ok je peux regarder ça dans 15 à 20 min

**Comment by Hileb** [comment]
D'accord merci

**Comment by yodidon** [comment]
Pour faire plus simple , je suis pas expert en anime je vais me lancer sur juste naruto

**Comment by yodidon** [comment]
Oula ça pique un peut sur ce code ...

**Comment by Hileb** [comment]
Pourquoi ?

**Comment by yodidon** [comment]
Il est pas simple ... je crois que je vais avoir besoin d’aide la

**Comment by yodidon** [comment]
Je me suis focalisé sur la méthode avec évaluation fonction mais je suis perdu ....

**Comment by yodidon** [comment]
Même sur le site c’est la guerre pour lancer une vidéo 😱

**Comment by yodidon** [comment]
@Hileb le titre complet que tu cherchais c’est bien « d’abord naruto » ?

**Comment by yodidon** [comment]
Sinon en attendant tu peux toujours voir sur Keko sama si tu trouves ton bonheur

**Comment by Hileb** [comment]
@yodidon  c'est "Naruto" mais quand j'ai vu que ça marchait pas j'ai essayé pour d'autres animes et aucun ne marchait avec le site I anime

**Comment by Hileb** [comment]
Je viens de voir neko sama ça a l'air super mais c'est dommage qu'il n'y est pas de vf

**Comment by sizanic** [comment]
@yodidon  j'ai entendu ton appel à l'aide et comme je veux encourager ta motivation, j'ai regardé.

Et voilà c'est corrigé (https://github.com/Kodi-vStream/venom-xbmc-addons/commit/ab798ab6ef3672fb16229f2f31d34eaaef79b99d)

**Comment by Hileb** [comment]
Ça ne marche toujours pas

**Comment by sizanic** [comment]
Si tu n'a pas installé manuellement le fichier corrigé dans ton installation de KODI, c'est normal.
Sinon,  il faut attendre une mise à jour.

**Comment by yodidon** [comment]
@sizanic merci, une question, tu arrivais à debugger avec eclipse ? Moi pas moyen d’afficher les variables ???

**Comment by Hileb** [comment]
@sizanic  Comment faire pour installer manuellement le fichier ?
Ou sinon si je desinstalle et ré installe ça devrait marcher peut être.

**Comment by sizanic** [comment]
@Hileb non, la reinstallation ne fera rien.
Sous windows, tu peux essayer de copier le fichier à la main, il est ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/ianime.py

Sous Android, trop dur, il faudra attendre une mise à jour.


@yodidon 
Oui, c'est bien grâce à Eclipse que j'ai trouvé si vite.
Pour pas polluer ce sujet, repose-moi ta question ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2739

**Comment by yodidon** [comment]
@hileb tu peux trouver ton dossier où se trouve Kodi en regardant ici 
https://kodi-vstream.github.io/docs/folder/
Ensuite tu récupères le fichier sur github (dans le dossier ressource>site ) et tu le colle au même endroit sur ton install

**Comment by noraef** [comment]
Bon, bah, ça remarchait en mettant le fichier de la beta, et au bout de quelques heures, ça ne re-marche déjà plus...

**Comment by sizanic** [comment]
Pour moi ça fonctionne.
Quand ça n'allait pas, on ne voyait pas les liens hosts.
Avec la correction, on les voit.

Si maintenant le host ne fonctionne pas, ce n'est pas un problème I-anime.

Voila des exemples qui se lancent : 
film(liste) -> A -> alpha -> GoUnlimited.
animés(VF) -> A -> Accel world -> S001E001 -> GoUnlimited.

**Comment by noraef** [comment]
Ah non, mais mon problème, ce ne sont même pas les hosts : je n'arrive même pas jusque là...
Si je vais dans : Animes -> Animes (Vf) -> I anime, j'ai l'animation de progression qui apparait une demi-seconde, et ça me renvoie à la liste des sites, sans que je puisse même rentrer dans I-anime...

Et ce n'est même pas le site qui jette mon IP, vu qu'en passant par mon laptop, le site est accessible, et les videos se lancent sans problème... vraiment bizarre que ça marche chez toi et pas chez moi.

A toute fins utiles, j'utilise vStream 0.7.73 avec juste le fichier ianime.py de la beta mis dans mon /storage/.kodi/addons/plugin.video.vstream/resources/sites/ à la place de celui d'origine, sur LibreElec 9.2.2. J'ai même essayé de désinstaller/réinstaller vStream, et nettoyer le cache de vStream : aucun changement. Tout fonctionnait cet après-midi sans problème, puis d'un seul coup, même plus accès au répertoire I anime, comme décris plus haut...

**Comment by TmpName** [comment]
Il doit y avoir un probleme avec la protection CF
Je viens de tester, ca marche chez moi, mais ca a mit du temps car il y  avait la protection

@noraef > log.

**Comment by noraef** [comment]
Ci-joint le log pour boot -> vStream -> Animes -> Animes (Vf) -> I anime
Et en effet, ça a l'air de foirer avec cloudflare...
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4427047/kodi.log)

**Comment by TmpName** [comment]
>cannot import name cloudscrape

Ya un loupage sur les fichiers, tu as la vielle version qui s'apelle cloudscrapeR

**Comment by noraef** [comment]
Pourtant, c'est une installation toute fraîche d'hier soir, venant du repo officiel, config remize à zéro, avec seulement le script Ianime mis à jour... Donc, techniquement, cette vieille version, bah c'est l'officielle. De toute façon, j'ai installé la beta, et ça remarche : dommage qu'elle ne soit plus dans le repo depuis un moment et qu'il faille la choper en manuel...

**Comment by TmpName** [comment]
Oui mais tu n'est plus sur l'officielle.
Sur l'officielle le repertoire est "cloudscraper"
Sur la beta ca devient "cloudscrape", et donc le nouveau fichier ne tourne que sur la beta.

**Comment by noraef** [comment]
Oui, je me disais que ça devait être quelque chose du genre : mais quite à commencer à faire un frankenstein avec 36 fichiers de la beta, je me suis dit autant y passer directement. J'ai crû comprendre que vous n'étiez pas fan que tout le monde se mette à utiliser la beta, mais mon plus gros problème est que ce que je cherchais n'était dispo que sur Ianime (c'est le problème avec les scrapers : on est tributaires des changements à la source)... En tout cas, merci beaucoup pour votre super boulot : particulièrement pratique en ce moment !

**Comment by chrysal** [comment]
Bonjour, je suis sur la version 0.7.7 et en utilisant le fichier suite au commit de sizanic cela fonctionne pour moi.
Je cherchais à faire la correction moi même mais je ne savais pas trop par où commencer. Merci.

**Comment by sizanic** [comment]
Bonjour, @chrysal ,
tu cherchais à faire la correction toi-même !
Bonne nouvelle !

On recrute 😉 

N'hésite pas à t'y mettre à une autre occasion.

Pour commencer, tu peux regarder par là : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2739

**Comment by sizanic** [comment]
Disponible dans la version 0.7.8, en mise à jour automatique.
