### ISSUE TITLE
Otakufr.com indisponible

### ISSUE THREAD

**Issue by teclis33** [Kodi-vStream/venom-xbmc-addons#2821]
**Décrivez le bug**
Plus aucun accès au site otakufr dans la section animés

**Votre system**
 - OS:  Android et Windows
-  Appareil : mxIII, xbox one et ordi
 - Version Kodi  18.6
- Version Vstream 0.7.7

**Comment by razorex** [comment]
@teclis33 pb déjà abordé
vStream: Page protegee par cloudflare
vStream: Pas de cookies présent sur disque

**Comment by Arias800** [comment]
Normalement c'est corriger dans la beta.

**Comment by teclis33** [comment]
Ha ok j'avais pas vu que déjà abordé. Mais merci pour la réponse. J'attendrai la version définitive qui résout le problème

**Comment by razorex** [comment]
@Arias800 j'ai la beta est çà marche pas!!!

**Comment by Arias800** [comment]
Retélécharge le bêta, car je vient d'essayer et ça fonctionne. Si ça ne fonctionne pas donne moi tes logs.

**Comment by razorex** [comment]
Non çà marche tjrs pas sous android avec la bêta pas le temp de regarder le log de ma box.

**Comment by Arias800** [comment]
Apparemment c'est une nouvelle couche de protection que Cloudflare a créer.

**Comment by teclis33** [comment]
J'avais installé la beta sur vos conseils, cela fonctionnait jusqu'à aujourd'hui. Je confirme qu'il est de nouveau impossible d’accéder au site.

**Comment by TmpName** [comment]
A retetester avec le nouveau code CF, mais utiliser l'issue generale, la je fais du netoyage.
