### ISSUE TITLE
Uploaded

### ISSUE THREAD

**Issue by arzaz** [Kodi-vStream/venom-xbmc-addons#2823]
Comment lire les films avec le host uploaded?
Pour info j'ai un compte premium.
Merci

**Comment by TmpName** [comment]
Ca ne marche pas ?
Tu as un messsage d'erreur ?

**Comment by arzaz** [comment]
Si je comprends bien, avec uploaded je ne peux pas streamer directement comme uptobox?
Pour info ma question concerne uploaded avec vstream mais non pas sur navigateur.

**Comment by TmpName** [comment]
Ben si le fichier est un fichier video si, ca marche pas ?

**Comment by TmpName** [comment]
Des news ?
