### ISSUE TITLE
Site FilmStreamVK ne fonctionne plus

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2824]
Le site est en Timeout.

Vérifier si l'adresse n'a pas changée vers : 
 .ttps://filmstreamvk.bz/

qui lui même à l'air d'être un clone de : 
.ttps://w5.dpstream.info/

**Comment by chrysal** [comment]
Je n'ai pas été plus loin que la fonction showLinks, je n'ai pas compris le mécanisme entre tagbucket et adsrv4k, et je me suis demandé si je ne faisais pas fausse route surtout.

**Comment by sizanic** [comment]
Tu peux retrouver un exemple pour doodplay dans la source ZuStream.

**Comment by chrysal** [comment]
J'ai mis un fichier qui fonctionne chez moi ici (loin d'être parfait je pense) : https://pastebin.com/U6qEbGxf.
Je ne savais pas trop si je pouvais faire un commit ou pull requests directement ... du coup je me suis dit que ça pourrait quand mettre permettre de partager le fichier, désolé si ce n'est pas la bonne méthode.
J'ai mis un git diff ici si besoin : https://pastebin.com/BAbVsRuG

**Comment by yodidon** [comment]
@chrysal j'ai l'impression que le showlink ne marche pas

**Comment by yodidon** [comment]
@chrysal en faite c'est le site qui ne propose quasiment aucun lien, tu as déjà réussi à lancer un film ?

**Comment by chrysal** [comment]
@yodidon oui j'ai fait une recheche sur divergente et c'était fonctionnel (les films se lancaient) et dans la partie film (dernier ajout) j'avais testé le Tarzan qui fonctionnait;
Je te confirme qu'il y a plusieurs d'entrées sans lien.

**Comment by yodidon** [comment]
@chrysal  a suivre si le site se met à jour, j’ai pour l’instant juste mis replace sur le titre ( pour enlever streaming...) , j’ai pas regarder sur la recherche ni sur les genre mais cool en tout cas

**Comment by chrysal** [comment]
@yodidon tu pourrais m'envoyer ton diff juste pour que je comprenne ce que tu as changé, j'avais pas vue de "streaming XX".

**Comment by yodidon** [comment]
@chrysal  Rien de fou juste quand tu affiches les résultats title= aResut[x] 
Je rajoute title=aResult[x].replace(‘streaming’, ‘ ‘)pour supprimer le mot

**Comment by chrysal** [comment]
@yodidon, ok merci.
Je pense pas avoir les droits de faire un commit, je ne connais pas trop la procedure à suivre dans ces cas là ...

**Comment by yodidon** [comment]
@chrysal tu vas sur le code tu fais éditer et après avoir modifier tu fais un pull request

**Comment by chrysal** [comment]
Voilà j'éspere que c'est ce qu'il fallait faire (c'est une premiere), j'ai ajouté le replace dont tu parlais dans le showLinks, du coup j'ai rajouté un commentaire en te mentionnant ainsi que l'issue.

**Comment by yodidon** [comment]
@chrysal je suis pas sûr que tu es bien placé le replace() on regarde ça si tu veux après le diner

**Comment by chrysal** [comment]
ok je l'ai retiré du coup :)

**Comment by yodidon** [comment]
@chrysal si tu passe sur Discord ça sera peut-être plus simple pour discuter

**Comment by sizanic** [comment]
@chrysal  si tu veux cherche à mettre en place des catégories de films, il y a celles-ci : 
/imdb/
/tendance/

**Comment by sizanic** [comment]
Bon en fait la structure de ce site est un peu la même que ZuStream.

Les séries se trouvent ici : 
/series/

Il y a même les catégories /network/

J'ai pas trouvé l'url pour les séries par genre.

**Comment by yodidon** [comment]
@chrysal si tu veux on peut regarder je suis op...

**Comment by chrysal** [comment]
@yodidon, j'ai ajouté un webhook via ce modop : https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22, mais je ne sais pas ce qu'il faut faire après ...
Je ne connais pas discord(dsl).

@sizanic effectivement j'avais cliqué sur le lien serie qui pointait sur dpstream du coup je l'avais exclu et je n'avais pas vu les catégories imdb et tendance

**Comment by yodidon** [comment]
@chrysal 
https://discord.gg/mCFkWz

**Comment by yodidon** [comment]
@chrysal j’ai fait quelque modif sur ton code juste pour exemple si tu veux continuer 👍

**Comment by chrysal** [comment]
@yodidon je continuais les modifs aussi de mon coté par exemple pour la partie serie et description.
Du coup je vais regarder tes commit pour reprendre tes modifs.

**Comment by yodidon** [comment]
@chrysal c’est une excellente nouvelle et j’ai hâte que tu partages

**Comment by yodidon** [comment]
@chrysal il y a aussi par exemple dans le regex de recherche la possibilité d'ajouter la description
