### ISSUE TITLE
Problème liens

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#2825]
Bonjour, 
Depuis hier soir sur la plupart des sites testés (ZT particulièrement) lorsque je veux lancer un lien, rien n'aboutit, je m'explique : 
Je fais ma recherche, je choisis mon film, je sélectionne la qualité et si je clique sur l'hébergeur (Upt, 1Fi, etc) la roue commence à tourner et plus rien, comme si la demande n'aboutissait pas.
Je suis sur Kodi 18.6 et VStream dernière version, le tout sur une X96 Max.

**Comment by Niconimes** [comment]
Nb: sur KEPLIZ mon souci est différent en fait, lorsque je clique sur mon lien j'ai une fenêtre rapide qui s'ouvre d'URL RESOLVER avec un message me disant 'Daily view limit reached' puis s'eteind et là c'est la fenêtre VStream qui s'ouvre (Erreur: fichier introuvable)

**Comment by TmpName** [comment]
Salut, tu n'aurais pas les logs ?
Ou au moins juste les lignes avec un message d'erreur ?

**Comment by SubToaD** [comment]
Salut,
Kodi 18.5 sous W7
Même problème depuis la mise à jour hier, Urlresolver ne trouve plus grand chose, je ne sais pas si ca a quelque chose a voir mais uptobox demande un pin de sécurité (j'ai realdebrid, le compte marche : par exemple ZT/uptobox en lecture directe sur realdebrid)
J'ai resynchro urlresolver avec realdrebrid ca n'a rien changé

Je colle le log ici, j'ai lancé U-235 en 1080 avec rapidgator (pas de vignette urlresolver qui s'affiche)
PB autour de la ligne 16401
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4431229/kodi.log)

Et merci pour le formidable boulot que vous faite ici :)

**Comment by terriblinho** [comment]
Salut, 

J’ai exactement le même problème que l’ami en haut avec Kodi 18.5 sous iPad !

merci pour le super boulot effectué :)

**Comment by Niconimes** [comment]
> Salut, tu n'aurais pas les logs ?
> Ou au moins juste les lignes avec un message d'erreur ?

Comment dois je faire? c'est une box Android

**Comment by SubToaD** [comment]
@Niconimes tu vas dans paramètre/systeme/journalisation => activer le debogage
des ecritures apparaissent en haut de l'écran avec le repertoire des log
fermes kodi, réouvre et vas ouvrir un hoster de film sur le site que tu veux
refermes kodi et copie le kodi.log du repertoire mentionné
pour arrêter suffit d'arreter le mode debogage

**Comment by SubToaD** [comment]
finalement en repassant à la 0.7.7 du repo ça remarche !

**Comment by razorex** [comment]
@TmpName le mien`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ZeroDivisionError'>
                                            Error Contents: float division by zero
                                            Traceback (most recent call last):
                                              File "C:\Users\*****\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\player.py", line 169, in onPlayBackStopped
                                                pourcent =  float('%.2f' % (self.currentTime / self.totalTime))
                                            ZeroDivisionError: float division by zero`

**Comment by sizanic** [comment]
Ma modif corrige ce problème.
Tu ne l'a pas.
La preuve, c'est qu'à la ligne 169 ce n'est plus ça maintenant.

**Comment by razorex** [comment]
oups dsl oui. je l'ai mis en copier/coller  cette nuit, j'avais oublié. Et du coup j'ai fais un copier/merdé
Du coup je viens de mettre la bêta.

**Comment by razorex** [comment]
Du coup je profite de ce poste je travail sur un hoster et vstream me répond çà, l'url est correct.
`vStream: Erreur: Connexion Impossible ([Errno 10060] Une tentative de connexion a �chou� car le parti connect� n�a pas r�pondu convenablement au-del� d�une certaine dur�e ou une connexion �tablie a �chou� car l�h�te de connexion n�a pas r�pondu),https://c3.videobin.co/oudvgpbkkftk2yixv5yoeazqdk7qhoozrnr7xqedr3uk4jpwmsw4ftcxg6ba/v.mp4` on peut augmenter ce temps de réponse.
PS: En rapport avec ce post parfois je clique 2 fois sur le hoster pour avoir un retour, pas d'exemple en tête.

**Comment by sizanic** [comment]
Oui, l'url est correcte, la vidéo a commencée dès que je l'ai coller dans VLC.

Mais qu'une seule fois !
En restant ensuite, j'ai aussi en timeout.

En collant l'adresse dans chrome, il me propose de télécharger le fichier.
=> mais une fois sur cinq, je pars aussi en timeout.

Je ne pense pas qu'augmenter le temps de réponse change quelque chose.

Tente plutôt une boucle pour essayer plusieurs fois.

**Comment by razorex** [comment]
oui J'ai fais comme toi, et même résultat. Un loop... oui

**Comment by Niconimes** [comment]
Tout à l'air de refonctionner parfaitement, merci vous êtes au top 👍

**Comment by sebi0606** [comment]
Non rien ne Marche les gars zt tirexo les liens uptobox ne fonctionne pas @Niconimes je sais pas où tu as vu que ça marche ?
Merci d'avance de regarder si vous pouvez

**Comment by ethanael83** [comment]
Bonsoir, pareil pour moi, rien ne marche, le hoster Uptobox ne marche plus non plus. Je suis sous Android Mi Box

**Comment by TmpName** [comment]
Pour up2XXX, y a deja une reponse.
