### ISSUE TITLE
Probleme apres MAJ partielle

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2826]
Tout les sites avec protection CF out.
Suite au probleme de changement de nom du repertoire.
Du coup je vais lancer une MAJ complete "en version rapide"

PS:
La prochaine fois, les android, ils attendront.

**Comment by razorex** [comment]
Non çà marche tjrs pas sous android avec la dernière bêta pas le temps de regarder le log de ma box.

**Comment by TmpName** [comment]
Apres la MAJ kodi ? La c'est con, fait ****

Quelq'un aurait des logs ?

**Comment by Arias800** [comment]
Avec mon appareil Android j'ai pas pu reproduire le bug, donc je peut pas aider.
J'attends la réponse d'une personne sur Discord pour voir si elle peut reproduire le bug .

**Comment by TmpName** [comment]
Moi j'arrive pas a forcer la MAJ kodi .....

**Comment by Arias800** [comment]
Le problème a l'air de venir d'un changement de cloudflare `2020-04-05 18:59:22.638 T:5524   ERROR: RuntimeError: !!Loop Protection!! We have tried to solve 3 time(s) in a row.`

**Comment by Arias800** [comment]
En remplaçant la ligne` s = cloudscrape.create_scraper(browser={'custom': 'ScraperBot/1.0'})` par  ` s = cloudscrape.create_scraper(browser=)` ca refonctionne sous Windows

**Comment by TmpName** [comment]
Ha oui j'ai vu que la derniere mise a jour de la lib bougeait des trucs dans le cypher.

**Comment by Arias800** [comment]
@razorex Teste avec la derniere version du fichier de Cloudflare.
