### ISSUE TITLE
uptobox authentification rate

### ISSUE THREAD

**Issue by isandard** [Kodi-vStream/venom-xbmc-addons#2831]
**Décrivez le bug**
uptobox authentification erreur
**Votre system**
 - OS: [Windows, Android]
-  Appareil [mibox 3 pour android et windows pc standard]
 - Version Kodi  [17sous androidTV et 18.2 sous windows]
- Version Vstream 0.78

**Nous devons le reproduire**
Pour cela il nous faut:
Uptobox que ce soit les liens ou carrement mon compte

**Log**
https://slexy.org/view/s20HF83EYL

Un truc qui est bizzare c'est que j'ai l'impression que uptobox est passé en mode Cloudflare.
Est ce que ceci explique cela ?

**Comment by isandard** [comment]
je rajoute un second log au cas où :
https://slexy.org/view/s2EN2LLITq

**Comment by isandard** [comment]
ce matin sans rien toucher, ca marche.
Par contre je vois plus le cloudflare sur uptobox.

**Comment by TmpName** [comment]
Ca re-marche ?
Up2XXX remarche ?

**Comment by rgalich** [comment]
Effectivement j'ai eu le même problème hier. C'est probablement lié à cloudflare. Pour ma part uptobox a toujours fonctionné. C'est uptostream qui ne fonctionne pas par contre.

**Comment by sebi0606** [comment]
Salut @TmpName oui pour uptobox sauf sur tirexo plus rien ne marche même les liens 1 fichiers

**Comment by TmpName** [comment]
Et up2strm deconne encore lui par contre ?

**Comment by rgalich** [comment]
Je viens de vérifier. Je vais sur mon compte puis mes fichiers uptobox. J'ai bien le message authentification réussi. Je peux lancer via uptobox mais pas via uptostream. J'ai le message 'fichier introuvable'. Je suis premium uptobox.

**Comment by isandard** [comment]
ah oui je teste jamais en uptostream toujours en direct uptobox.
Mais hier soir c'etait authentification raté alors que sur le navigateur ca marchait ( et c'est là que j'ai vu le truc de cloudflare)

**Comment by Torped00** [comment]
Bonjour,
Déjà un énorme merci pour tout ce que vous faites. J'apporte juste mon petit plus concernant Uptxxstrxx avec source ZT à date d'aujourd'hui:
Sous différent appareils Android 
18.2 et 18.6 
Il voit les liens, reconnaît mon compte premium mais me dis fichier introuvable
Sous Windows 8
Il voit les liens mais quand je clique sur un épisode ça mouline dans le vent sans succès. Ni connexion upto OK ni possibilité de voir l'épisode
Sous Xbox one
Même symptômes que windows... 
Voilà je sais pas si ça peut aider....

**Comment by alKODIque** [comment]
Présentement, même Alldebrid ne décode pas les liens UPTOBOX... vStream ou non...

**Comment by alKODIque** [comment]
C’est revenu sur Alldebrid

**Comment by BENJI97200** [comment]
Bjr....vous avez le mm problème.....sur uptostream fichier introuvable ? J ai un compte premium uptobox ...merci

**Comment by chaiba2006** [comment]
Salut. Moi aussi toujours le même problème même avec la version 8'0 de vstream. Uptobox ou uptostream me met fichier introuvable.. Je suis sur kodi 18.6 android tv. 
Merci

**Comment by TmpName** [comment]
@chaiba2006 avec ou  sans debrideur ?
Tu es sur que le fichier est present sur le site ?

**Comment by chaiba2006** [comment]
> @chaiba2006 avec ou sans debrideur ?
> Tu es sur que le fichier est present sur le site ?

J'ai un compte uptobox premium 
Oui le fichier exist sur le site w même jai tester avec des fichier sur mon compte

**Comment by TmpName** [comment]
Et tu fais avec ou sans debrideur ?
Essayes avec up2stream aussi stp.
Tu aurais quelque chose dans les logs ?

**Comment by chaiba2006** [comment]
Non j'ai pas de debrideur
Maintenant c ok sur uptobox mais uptostream toujour me fait fichier Introuvable

**Comment by TmpName** [comment]
Ca remarche ca depuis ?
