### ISSUE TITLE
Vstream ne fonctionne pas sous Nodi

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#2832]
Bonjour à tous
Je viens d'installer NODI pour voir ce que c'était.
J'ai aussi installer vstream depuis le repo mais impossible de lancer j'obtiens un message d'erreur
Voici le lien pour le fichier de log
Https://pastebin.com/tqgramqz
Merci

**Comment by lebigboss** [comment]
J'utilise que Nodi et ça fonctionne très bien.
Par contre tu dois installer le dossier Vstream manuellement.

**Comment by yodidon** [comment]
Sur nodi a partir du repo tu dois pouvoir installer vstream

**Comment by sizanic** [comment]
C'est le même problème que ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2829

En fait la derniere version 0.7.8 ne s'installe plus directement sur android.

Mais elle peut s'installer sur une mise à jour d'une version précedente.

**Comment by falciatrice10** [comment]
> C'est le même problème que ici : #2829
> 
> En fait la derniere version 0.7.8 ne s'installe plus directement sur android.
> 
> Mais elle peut s'installer sur une mise à jour d'une version précedente.

Effectivement, j avais installé directement la  078.
Je vais essayer une ancienne version si j en trouve une

**Comment by sizanic** [comment]
J'en ai postée une ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2829

**Comment by falciatrice10** [comment]
Merci beaucoup, ça fonctionne maintenant

**Comment by yodidon** [comment]
Cool 👍
