### ISSUE TITLE
Extreme-down - Les séries ne sont pas regroupés par saisons

### ISSUE THREAD

**Issue by DaX59** [Kodi-vStream/venom-xbmc-addons#2833]
Salut à toute l'équipe et d'abord, merci pour le travail fourni.

Je voulais remonter quelques points sur la partie recherche des séries.
Sur ZT et Tirexo, la recherche nous trouve des jeux, films et musique, n'est il pas possible de filtrer en utilisant les filtres comme sur ZT ?

Sur Tirexo, j'ai aussi pas mal de résultats non désirés, par exemple, quand on cherche "walking", on retrouve Astérix et pleins d'autres résultats a priori sans lien avec le mot "walking".

Sur extremed**n, si on garde l'exemple de walking, ça me trouve bien les walking dead et me donne en résultats, toutes les qualités dispos mais quand on en sélectionne une, on retombe sur un menu de choix de qualité, c'est normal ? Y'a pas doublon ?

Remarque générale sur plusieurs sites, la recherche nous trouve toutes les saisons, il serait pas mieux de d'abord nous montrer les résultats par nom de série puis quand on clique dessus, avoir toutes les saisons ? C'est une genre de mise en forme pour éviter les résultats à rallonge. Sur les recherches de "voirfilms", ça fonctionne déjà comme ça.

**Comment by TmpName** [comment]
Pour le dernier point, c'est pas nous geront, c'est le site lui meme, nous on utilise leur moteur de recherche, et on on affiche les resultats. A tout les sites ne presentent pas de la meme maniere.

**Comment by yodidon** [comment]
Oui il y a pas mal de souci sur les recherches dans certain site, malheureusement ce n’est pas trop gerable sans prendre le risque de perdre les résultats

**Comment by sizanic** [comment]
Pour ExtremDown, comme le dit TmpName, on ne peut rien faire si cela correspond à la hierarchie sur le site d'origine.
Mais parfois on peut (comme cela a été fait pour les films dans ZT qui ne propose pas toutes les qualités dans les résultats mais seulement ensuite).

J'ai regardé le format des résultats d'extremDown et on peut faire quelque chose.


Pour Tirexo, j'ai créé cette issue : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2837

**Comment by Arias800** [comment]
C'est déjà le cas dans Extreme Download, vu que je me suis baser sur le site de zt pour le faire xD

**Comment by sizanic** [comment]
Je parle de ce que j'ai mis en place il y a 3 semaines sur ZT : 
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/048636b71db74734a75e9337c72319783e171601#diff-10b0004289fc0811565a2dee8686a508

Et de l'améliorer pour le mettre au niveau des séries.

**Comment by Arias800** [comment]
Pourquoi, faut deja que je mettent a jour Extreme Download car je vient de voir qu'il y a des choses qui fonctionne plus correctement sur le site

**Comment by Arias800** [comment]
C'est implémenter dans Extreme Download.
