### ISSUE TITLE
vstream erreur 

### ISSUE THREAD

**Issue by Mobius69** [Kodi-vStream/venom-xbmc-addons#2835]
Bonsoir
J'ai du désinstaller et réinstaller kodi 18.6 sur mon android tv, j'y ai réinstallé vStream qui visiblement est passé en 0.7.8 et là j'ai un message vStream erreur consulter le journal pour plus d'informations.
J'avais lancé vStream 15 minutes avant désinstallation et réinstallation  et tout fonctionnait nickel. Mais la plus rien ne fonctionne. 
Quelqu'un peut-il m'aider s'il vous plaît? 
Par avance un grand merci.

**Comment by yodidon** [comment]
Sauf erreur il te fait installer une version plus ancienne et mettre à jour, mais à confirmer

**Comment by Mobius69** [comment]
J'étais en 0.7.73 je crois avant de tout désinstaller et réinstaller tout fonctionnait bien.
Ce ne serait pas la 0.7.8 qui ferait tout capoter?

**Comment by yodidon** [comment]
Non la o.7.8 apporte de vrais améliorations sur l’obtention des ressources

**Comment by Mobius69** [comment]
Je refais une installation complète de kodi et de vstream pour voir si ça fonctionne

**Comment by yodidon** [comment]
Tu peux toujours récupérer la bêta à l’adresse fourni par arias800:
https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by Mobius69** [comment]
Merci, j'avais sous clef un plugin vidéo qui me ramenais à la 0.7.5 et j'ai fait l'update vers la 0.7.8 et tout refonctionne!!!! Merci Yodidon tu m'as donné un cap dans une excellente direction!!!

**Comment by yodidon** [comment]
J’en suis ravi 👍

**Comment by Mobius69** [comment]
Au top merci encore!
