### ISSUE TITLE
ReplayTVStreaming ne reponds plus

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2839]
Le site n'est plus accessible.
Je désactive la source.

Sauf si l'url à changé et que quelqu'un connait la nouvelle adresse.

**Comment by TmpName** [comment]
Pas trouvé, mais a l'air recent, le site est encore sur google.

**Comment by sizanic** [comment]
Oui, ça date d'hier.
Il répondait encore quelques minutes avant que je mette le message.

**Comment by TmpName** [comment]
Lol, si ca c'est pas etre reactif !
