### ISSUE TITLE
Bug ouverture vstream

### ISSUE THREAD

**Issue by saifouuu** [Kodi-vStream/venom-xbmc-addons#2841]
**Décrivez le bug*
Impossible d'ouvrir vstream. Une fois que j'appuie sur l'extension un message d'erreur s'affiche me disant d'aller voir dans le journal pour plus d'informations mais rien n'apparaît sur le journal. 

**Votre system**
 - OS: [Windows, Android]
-  Appareil [one plus 7]
 - Version Kodi  [18.6]
- Version Vstream
![Screenshot_20200409-041322](https://user-images.githubusercontent.com/63381759/78850831-7c36ee80-7a18-11ea-8155-e544a4e67532.jpg)

**Comment by Arias800** [comment]
Il y a déjà la réponse ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2829
Merci de vérifier qu'il n'y a pas d'issue déjà ouvert pour ton problème.

**Comment by sizanic** [comment]
Et également ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2842
