### ISSUE TITLE
impossible d'installer Vstream depuis 2 jours

### ISSUE THREAD

**Issue by yoannfigaro** [Kodi-vStream/venom-xbmc-addons#2842]
bonjour a tous 
depuis deux jours impossible d'installer Vstream sur ma box android 8.1
j'ai essayé de mettre la version KODI 16.1 ou 18.3 il installe Vstream ensuite quand je le lance il me dit erreur voir le journal 

j'ai installé Vstream sur plusieurs box j'ai jamais eu le moindre souci jusqu'a hier grrrrr

je sais que Vstream fonctionne car sur ma box dans ma chambre tout fonctionne nikel 
c'est vraiment a l’installation du repo 

merci pour votre aide

**Comment by yodidon** [comment]
Il faut que tu essaie avec une version plus ancienne de vstream puis une mise à jour si ça fonctionne

**Comment by yoannfigaro** [comment]
plus ancienne que 16.1 ??
j'ai jamais eu le moindre souci avec cette version 
aurais tu un lien pour une version qui fonctionne ?
merci

**Comment by yodidon** [comment]
16.1 correspond à la version de Kodi, vstream est indépendant de Kodi et donc n’as pas de rapport avec ce 16.1. Tu peux rester sur Kodi 18.5 mais prendre une version antérieure de vstream
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2829#issuecomment-610059515

**Comment by yoannfigaro** [comment]
désolé j'ai mal lu ta réponse
tu prends quel version ??
merci

**Comment by yodidon** [comment]
Une fonctionnelle 
https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by zicmama** [comment]
Oh @yodidon pourquoi tu mets cette redirection dans les liens que tu publies?
T'es relou !!!

**Comment by yodidon** [comment]
Pardon ?

**Comment by yodidon** [comment]
@zicmama  peux tu m’éclairer sur le souci, je ne comprends pas où se trouve le problème merci à toi

**Comment by Arias800** [comment]
@zicmama c'est le liens qui permet simplement de récupérer les fichiers de la beta. Liens qu'on a toujours utiliser et qui est accessible depuis longtemps sur la page d’accueil du github, donc je ne vois pas le probleme xD

**Comment by yodidon** [comment]
@yoannfigaro le lien c’est celui de la bêta mais il devrait régler ton problème désolé pour cette inversion

**Comment by yodidon** [comment]
> Oh @yodidon pourquoi tu mets cette redirection dans les liens que tu publies?
> T'es relou !!!

@zicmama lorsque l’on mets quelqu’un en faut, la moindre des choses c’est de lui répondre merci à toi

**Comment by yoannfigaro** [comment]
je test et je vous dit quoi merci

**Comment by yodidon** [comment]
Super merci

**Comment by Arias800** [comment]
@yodidon on se calme, il répondra quand il voudra xD

**Comment by yodidon** [comment]
Oui désolé mais juste un excès d’injustice pas de soucis je me remet à ma place

**Comment by sizanic** [comment]
Le lien de la beta est pour beaucoup bloqué par le navigateur.
Il est possible d'installer la version officielle précédente ici, la  : 
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.7.7

Ensuite elle se mettra à jour toute seule.

**Comment by yoannfigaro** [comment]
bonjour a tous alors voila les nouvelles 
quand j'installe Vstream tout se passe bien,par contre des que je le lance il me dit erreur lire le journal 
et ca depuis quelques jours je parle bien-sur d'une nouvelle installation de Vstream pas un déjà installé
donc voila ce que je dois faire pour que tout fonctionne
1 instal le repo Vsream
2 je reste appuyé dessus pour avec accès au menu
3 je clik sur information__configurer 
4   et la en bas a droite je clik sur D'ORIGINE et je fais ok
et voila mon Vstream de nouveau opérationnel
je precise que j'ai testé sur 2 box android neuve TANIX TX3 MINI
et j'ai du faire la meme manip

bonne journée a tous

**Comment by sizanic** [comment]
Nouvelle mise à jour 0.7.9 disponible corrige les problèmes d'installation ...
