### ISSUE TITLE
Tirexo hs 

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#2843]
Bonsoir à tous tirexo hs apparement souci de cloudfare vous êtes au courant ?
Les liens ne s'ouvrent plus
merci d'avance
Prenez soin de vous

**Comment by sizanic** [comment]
Je ne constate pas ce problème ...

**Comment by BENJI97200** [comment]
@sebi0606 ....Slt....Encore un problème de Dns je pense ,Avec un vpn fonctionne ....Sans Non(aucune information)

**Comment by sebi0606** [comment]
Salut @sizanic et @BENJI97200 j'avais changé les dns pour essayer même souci et sur fire stick nvidia shield et tablette a'droid  du coup j'ai desinstallé kodi et fait une réinstalle et ça remarche 👍 merci en tout cas pour vos réponses
Prenez soin de vous 🙏
