### ISSUE TITLE
erreur db.py à l'ouverture de l'extension vStream

### ISSUE THREAD

**Issue by dodoremi** [Kodi-vStream/venom-xbmc-addons#2845]
Bonjour à l'équipe Kodi-vStream et bravo pour votre investissement.

**Décrivez le bug**
Je viens d'installer Kodi et vStream. Dans Kodi, lorsque je clique sur l'extension vStream, une erreur s'affiche :
VStream erreur
Consulter le journal pour plus d'information
Puis, l'écran Vidéo de kodi s'affiche avec les 3 liens "Fichiers", "Lises de lecture" et "Extensions Vidéos"

Dans le log je vois ceci
2020-04-10 22:19:02.468 T:7080  NOTICE: 	[PLUGIN] vStream: SQLITE 3 as DB engine
2020-04-10 22:19:02.474 T:7080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\plvt6612\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 6, in <module>
                                                from resources.lib.gui.hoster import cHosterGui
                                              File "C:\Users\plvt6612\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\hoster.py", line 4, in <module>
                                                from resources.lib.gui.gui import cGui
                                              File "C:\Users\plvt6612\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\gui.py", line 4, in <module>
                                                from resources.lib.gui.guiElement import cGuiElement
                                              File "C:\Users\plvt6612\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\guiElement.py", line 16, in <module>
                                                class cGuiElement:
                                              File "C:\Users\plvt6612\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\guiElement.py", line 21, in cGuiElement
                                                DB = cDb()
                                              File "C:\Users\plvt6612\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\db.py", line 40, in __init__
                                                VSlog('Erreur: Impossible d\'écrire sur %s' % self.REALDB )
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)

Je reproduis systématiquement le problème en désinstallant/réinstallant kodi et vStream.
J'ai également le même problème avec la version 18.3 de kodi (qui fonctionne bien avec vStream sur mon autre PC).

**Votre system**
 - OS: Windows 10 - kernel Windows 10.0.16299
-  Appareil : PC HP EliteBook
 - Version Kodi  18.6 Git 20200229-8e967df921
- Version Vstream 0.7.8 by Venom, TmpName, Arias800, Razorex, Kodigoal, Sizanic, Yodidon

**Log**
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4463406/kodi.log)

**Image**
![image](https://user-images.githubusercontent.com/63420122/79022652-bf12d680-7b7e-11ea-8b84-c09164eb7744.png)

**Plus**
Un grand merci

**Comment by razorex** [comment]
DSL pour toi. c'est ma faute j'ai fais bc de modifs. si tu sais faire installe une version antérieur ou installe la bêta

**Comment by razorex** [comment]
@TmpName du coup peut être faudrait il faire une 0.80

**Comment by sizanic** [comment]
Bonjour @dodoremi ,

Je salut ta motivation à avoir aussi bien détaillé.
Avec copie d'écran, et un fichier de log.

Mais tu n'as pas vu que ce problème est déjà décrit plusieurs fois, avec les titres : 

- **impossible d'installer Vstream depuis 2 jours** : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2842
- **Bug avec OSMC - Kodi 18.6** : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2829

Merci de te référer à ces issues où est décrit le contournement.

**Comment by sizanic** [comment]
> @TmpName du coup peut être faudrait il faire une 0.80

Peut être attendre la correction UpToBox qui a l'air d’être bientôt prête.

**Comment by razorex** [comment]
Oui @sizanic

**Comment by razorex** [comment]
Par contre de moi j'ai pas d'info pour la correction d'uptobox, il faut vraiment que l'on communique..

**Comment by sizanic** [comment]
Je fais référence à ça : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2793#issuecomment-611885389

le dernier message d' @eco-plus  : 
> mon code fonctionne ...

**Comment by razorex** [comment]
dsl oui c'est moi qui ne suis pas.

**Comment by dodoremi** [comment]
Hello vStream team, comme l'indique @razorex l'installation de la version 0.7.7 suivie d'une mise à jour permet d'éviter mon problème initial.
Bon maintenant, je n'ai pas beaucoup progressé puisque vStream semble ne pas réussir à se connecter aux sites de téléchargement.
Dans les log, je vois cette ligne régulièrement
DEBUG: CSettingsManager: requested setting (plugin_streamelite) was not found.
ce qui semble aboutir à cette erreur pour chaque site de téléchargement
NOTICE: 	[PLUGIN] vStream: Erreur: Connexion Impossible ([Errno 11001] getaddrinfo failed)

(un peu comme cet ancien issue #1603)

Bon je creuse dans GitHub pour voir s'il n'y a pas un issue qui pourrait m'aider ...

En tout cas, merci à tous, vous faites du super boulot, je suis fan.

**Comment by dodoremi** [comment]
En désactivant mon serveur proxy, vStream fonctionne correctement.
