### ISSUE TITLE
Nouveau Hoster dustreaming

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2846]
@yodidon

Pour résoudre ce hoster,
tu lances la vidéo.

Tu cherches le flux mp4 et tu remontes les urls :

ici, le lien mp4 est donné le champ location de du lien juste au dessus redirector?token...

![image](https://user-images.githubusercontent.com/47307622/79030507-99df9180-7b99-11ea-9526-1302478631e7.png)

Et le lien director?token est obtenu par cette url : 

![image](https://user-images.githubusercontent.com/47307622/79030586-0c507180-7b9a-11ea-875b-97e7d391f4fc.png)

Ce n'est pas la même que la tienne.
/v/ est remplacé par /api/source/

et s'appelle avec ces parametres : 

![image](https://user-images.githubusercontent.com/47307622/79030666-681afa80-7b9a-11ea-9453-ff06c0897e2f.png)

_Originally posted by @sizanic in https://github.com/Kodi-vStream/venom-xbmc-addons/pull/2844#issuecomment-612276564_

**Comment by yodidon** [comment]
Super explication merci @sizanic je vais regarder ça et me remettre sur ce hoster voir si je m’en sors

**Comment by yodidon** [comment]
J'ai encore beaucoup à comprendre.
pour l'instant je tatonne beaucoup et à chaque essai je me retrouve avec ce résultat:

![dustreaming2](https://user-images.githubusercontent.com/39896943/79041515-d12d5d00-7bf0-11ea-9116-64add578170a.PNG)

**Comment by sizanic** [comment]
Ça c'est bien.
Après dans le code showHoster, tu remplaces manuellement /v/ par /api/source/ et rajoutes les deux paramètres. Et t'appelles cette nouvelle URL.

**Comment by yodidon** [comment]
J’ai fais ça mais dans le code du hoster, je pensais que c’était la qu’il fallait le faire , je suis nul rrrrrr

**Comment by sizanic** [comment]
En fait t'as raison c'est dans le hoster qu'il faut le faire.
Comme ça toutes les sources qui utilisent ce hoster n'auront pas à le faire avant d'appeller le hoster.

**Comment by sizanic** [comment]
Ce que tu montres pour l'instant c'est bon, faut voir le hoster.

Est-ce que tu peux le pusher dans une branche ?

**Comment by yodidon** [comment]
c'est fait mais c'est surement n'importe quoi ce que j'ai fait ...

**Comment by razorex** [comment]
ca ressemble au code de frenchvid

**Comment by sizanic** [comment]
> c'est fait mais c'est surement n'importe quoi ce que j'ai fait ...

Si ça fonctionne c'est le principal 😉 

Si tu veux l'améliorer, voilà mes conseils : 
Sort cette ligne de setUrl : 

`self.__sUrl = self.__sUrl.replace('/v/', '/api/source/')`

`setUrl ` doit contenir l'url brute, tel qu'elle à été fournie.
`setUrl ` est ce qu'on appelle en programmation un setter.
Renseigne toi la définition des getter() et setter().

Je ne pense pas que le str() soit utile car on est censé recevoir une chaîne de caractère.

ce qui donne : 
```
def setUrl(self, sUrl):
    self.__sUrl = sUrl
```
Cette ligne, 
`self.__sUrl = self.__sUrl.replace('/v/', '/api/source/')`
c'est lorsqu'on va utiliser l'url qu'il faut la mettre en place, donc à déplacer dans __getMediaLinkForGuest()

**Comment by yodidon** [comment]
Merci @sizanic mais du coup comment sUrl est transporté, je veux dire par la comment le reste du programme le récupère ? (Désolé si c’est bête comme question)

**Comment by sizanic** [comment]
Mais il fonctionne ton code ou pas ?

**Comment by sizanic** [comment]
Exemple de problème en ayant modifié self.__sUrl : 

ici c'était l'url de base qu'il faut passer dans refer, mais c''est trop tard tu l'as modifié : 

            return True, api_call + '|User-Agent=' + UA + '&Referer=' + self.__sUrl

**Comment by sizanic** [comment]
> comment sUrl est transporté,

Il n'a pas besoin d'etre transporté, il n'est qu'une étape intermédiaire : 

        sUrl = self.__sUrl.replace('/v/', '/api/source/')
        oRequest = cRequestHandler(sUrl)

**Comment by yodidon** [comment]
Ok je vois et non il ne fonctionne pas je n’ai pas la modif du replace en tout cas sur eclipse j’ai toujours l’URL avec /v/

**Comment by sizanic** [comment]
![image](https://user-images.githubusercontent.com/47307622/79030666-681afa80-7b9a-11ea-9453-ff06c0897e2f.png)

**Comment by yodidon** [comment]
J’ai pas close ?????

**Comment by sizanic** [comment]
Pour le close, ça arrive après un repas du dimanche de pacques bien arrosé, le bouton est juste à coté du 'Comment'. 😉 🍷 

quand t'appeles /api/source, un point d'attention que j'ai raté, il faut faire POST : 

![image](https://user-images.githubusercontent.com/47307622/79069976-ab788480-7cd2-11ea-9f22-7b95a8cfb493.png)


Ce qui donne : 

```
    def __getMediaLinkForGuest(self):
        api_call = ''
        oParser = cParser()

        sUrl = self.__sUrl.replace('/v/', '/api/source/')
        oRequest = cRequestHandler(sUrl)
        oRequest.addHeaderEntry('Referer', self.__sUrl)
        oRequest.setRequestType(cRequestHandler.REQUEST_TYPE_POST)
        oRequest.addParameters('r', '')
        oRequest.addParameters('d', 'dustreaming.fr')
        sHtmlContent = oRequest.request()
```

**Comment by yodidon** [comment]
ok ok , du coup ça avance un peut, ça ne se lance pas mais par contre je n'ai plus de message d'erreur... :)

**Comment by sizanic** [comment]
Après, comme dit @razorex , ça ressemble à Frenchvid.
Y'a plus qu'à piquer de Frenchvid le bout de code pour traiter le json et proposer les qualités et on se retrouve avec : 


```
    def __getMediaLinkForGuest(self):
        api_call = ''

        sUrl = self.__sUrl.replace('/v/', '/api/source/')
        oRequest = cRequestHandler(sUrl)
        oRequest.setRequestType(cRequestHandler.REQUEST_TYPE_POST)
        oRequest.addHeaderEntry('Referer', self.__sUrl)
        oRequest.addParameters('r', '')
        oRequest.addParameters('d', 'dustreaming.fr')
        sHtmlContent = oRequest.request()
        
        page = json.loads(sHtmlContent)
        if page:
            url = []
            qua = []
            for x in page['data']:
                url.append(x['file'])
                qua.append(x['label'])

            if (url):
                api_call = dialog().VSselectqual(qua, url)

        if (api_call):
            return True, api_call

        return False, False
```

Et voilà !

**Comment by sizanic** [comment]
Cherches plus, c'est fini 😉 
J'ai donné le code juste au dessus.


Tu veux bien que je me charge de le mettre dans la beta ?

**Comment by yodidon** [comment]
Ok oui ...

**Comment by yodidon** [comment]
en meme temps c'est mieux car moi ça ne fonctionne toujours pas ...

**Comment by sizanic** [comment]
Et voilà : 
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/e7e95441bd84ae3c973ea668041c7432996cae29

**Comment by yodidon** [comment]
j'etait resté sur 
def setUrl(self, sUrl):
        self.__sUrl = sUrl
du coup ça ne fonctionnais pas ...
Merci  @sizanic  en tout cas pour ces précieux conseils
