### ISSUE TITLE
Lien Netu et Cloudvid

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#2847]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: Android
-  Appareil Belink GT1
 - Version Kodi  18.6
- Version Vstream 17.8

La plupart des liens Netu et Clouvid ne fonctionnent pas.
Cela sur plusieurs sites.
Merci.
Joyeuses Pâques à toute l'équipe.

**Comment by TmpName** [comment]
Pour netu, je crois qu'ils ont remit en place la protection recaptcha.
Pour cloudvid je cherche un lien valide pr tester.

**Comment by Papounet58** [comment]
Merci

**Comment by TmpName** [comment]
Par contre si tu avais un endroit ou trouver des liens cloudvid fonctionel ?

**Comment by Papounet58** [comment]
Je regarderai

**Comment by razorex** [comment]
@TmpName j'ai dissocier clipwatching de cloudvid, et du coup corriger le regex de clipwatching. Peut être que sa résoudra une partie des pb.

**Comment by Papounet58** [comment]
Certains liens anciennement cloudvid et maintenant clipwatching
fonctionnent.
Merci pour la réactivité.

**Comment by Che-debarras** [comment]
Sauf sur planetstrmng le clipwatching ne fonctionne toujours pas mais les autres sources ça a l'air de marché

**Comment by Papounet58** [comment]
A partir de la seconde page sur Planetstre les liens clipwatching
fonctionnent.

Le dim. 12 avr. 2020 à 16:48, Che-debarras <notifications@github.com> a
écrit :

**Comment by eco-plus** [comment]
sa sert a rien de dissocier les 2 c'est le meme hébergeur !

**Comment by Che-debarras** [comment]
@razorex 

J'ai clos mon post maks juste pour te dire que ton idée à résolu les problèmes de clipwatching sur les sources que j'avais mentionné sur mon recap' de bug.

Merci beaucoup pour cette correction,  👏

**Comment by razorex** [comment]
`sa sert a rien de dissocier les 2 c'est le meme hébergeur !
@razorex tu avais juste a ajouter en bas une 3eme verification`
@eco-plus oui c'est ce que j'avais fait au début. mais l'avantage c'est que çà évite les retours du genre cloudvid est hs au moins la ça me parait plus clair pour travailler à l'avenir dessus, peut être est-ce une erreur de ma part.
@Che-debarras n'applaudis pas trop vite c'est surtout internet qui passe mieux m'a modif n'a que peu apporter.

**Comment by Che-debarras** [comment]
@razorex 
Quel modestie,déjà les videos se lancent même si certains lagguent ou freeze mais ça c'est du a ma connexion adsl en wifi pourri à certains moment de la journée enfin je crois.

T'as le mérite d'avoir déterrer des liens enfin bcp de liens non fonctionnelle.

**Comment by razorex** [comment]
Malheureusement c'est hors de notre contrôle, moi aussi j'aimerais que çà soit immédiat

**Comment by Che-debarras** [comment]
> Malheureusement c'est hors de notre contrôle, moi aussi j'aimerais que çà soit immédiat

J'ai réduit la résolution de ma box tv et de kodi en HD tous les 2 pour limiter la résolution de la video qui est passé en SD+ cela semble apporté une amélioration au dépend de la qualité mais on peut visionner la video d'origine HD en SD+ sans freeze.

Si cela peut aider les gens qui ont un problème de freeze (diminuer la résolution de la tv ou box tv)
