### ISSUE TITLE
Recap des bugs

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2849]
**Décrivez le bug**
Mise à jour avec dernier commit **959b239 de Razorex**

J'ai fait un checkup pour les problèmes de sources et d'hébergeurs ci-dessous pour eviter les doublons de posts.

**_Dossiers vides pour:_**
- Filmstrmvk (film) (openload, Dustrm)
- Tv_serie_strmg (série)
- StrmngDivx (film, épisodes de serie)
- StrmySerie (vidcloud)

**_Dossiers qui s'ouvrent pas:_**
- Kaydo (toutes catégories)
- Tirexo (hosters) 
- SeriesStrmg (toutes catégories)

**_Autre bug_**
- Kaydo :Marqué comme vu alors que non vu
- planetstrmng : absence de Estrm, vidoza et Verystrm (présent et fonctionnelle sur le site mais pas sur vstream 

**_Les Hosts K.O:_** 
- Dustrmng (filmstrmngVk)
- Clipwatching (strmngseries, planetstrm, dpstrmng, seriestrmngwtch)
- Netu (toutes les sources)  **_pb de recapcha_** (patience!)
- Frenchvid (quasi toutes les sources)
- Doodstream (toutes les sources)
- Mixdrop (Filmstrmvk, planetstrmng)
- Allow_redirect (ianime, k-strm)
- Prostrm (k-strm)
- LIen_direct (Mega/openload/verystream) (toutes les sources)
- Vidlox (strmayserie,voirflm)

**Votre system**
 - OS: [Windows, Android]
-  Appareil [Win10, Z6+]
- Version Kodi  [18,19]

**Comment by razorex** [comment]
Pas d'accord avec toi a cet instant je regarde un film sous uptostream et frenchvid fonctionnais encore il y a une heure.

**Comment by razorex** [comment]
Cinemay c'est bon aussi, regulierement sous cloudflare.

**Comment by Che-debarras** [comment]
J'ai testé toute les sources, chaque catégorie (film serie animé) et chaque hosts et Frenchvid n'a marché qu'une fois ou 2 sur l'ensemble des sources et categories present sur vstream

J'ai le detail des bugs par source si tu veux
Frenchvid a marché pour Ianime  et frenchstrm
Mais ne marche pas pour strmdivx vfspace strmcplt
Il a aussi arrêté de marché d'un seul coup pour Kaydo

Pour uptostream (sans compte) 
Il ne marche pas pour cinémay frenchstrm libertyland ZT et tirexo 

Donc je sais pas quel maj tu as et ta config mais non cela ne marche sur une majeur partie des sources 

Jusqu'à présent je n'ai eu aucun souci et je bidouille pas ma box  a part les maj manuelle de vstream

**Comment by razorex** [comment]
il y a plusieurs Hoster "cachés" sous Frenchvid c'est pk si tu donne le lien çà aiderait.
J'ai corriger un hoster qui ce cachais sous le nom de cloudvid, clipwatching peut être aura tu moins de pb avec ce hoster (cloudvid) car dorénavant clipwatching en hoster existe.
PS je test toujours mes sources.

**Comment by sizanic** [comment]
Merci @Che-debarras pour ce travail complet de synthèse.

Le retour de chacun est le bienvenue, s'il faut préciser des détails.

Comme par exemple uptostream, il faut préciser avec ou sans compte.

**Comment by sizanic** [comment]
Cette nouvelle présentation pour suivre la recap est mieux, il faut garder une section OK plutôt que de supprimer de la liste des KO.

**Comment by razorex** [comment]
Et tu allez sur voir sur les sites de ces sources???

**Comment by Che-debarras** [comment]
J'ai rajouté comme le dit sizanic si c'est avec compte ou pas. Mais moi j'utilise vstream et les hosts sans compte depuis toujours

J'ai aussi précisé les sources où j'ai rencontré ces bugs.

Je vérifierai demain les sources par navigateur internet car comme kaydo c'est un problème de leur site internet,  une page de debugging s'ouvre.

Bon weekend et merci pour votre aide
NB: ces derniers temps j'ai bcp utilisé frenchvid et ça a toujours bien marché mais ces derniers jours je dois cliquer plusieurs fois pour que la video se lance mais aujourd'hui ca ne repond plus sauf pour 2 sites que je n'utilise jamais.

Je revérifierais demain pour voir si c'est revenu a la normal et je mettrais a jour les bugs résolu.

**Comment by razorex** [comment]
On va regarder tout ca . merci

**Comment by razorex** [comment]
Du coup j'ai fais une correction de redirection sur cinemay pour opsktp mais le hoster ne fonctionne pas tout de même fsimg ==> Frenchvid.

**Comment by kleenex31** [comment]
Il a fallu que je désinstaller vstream de mon kodi. Une fois que j'ai réussi à le réinstaller, ça me dit vstream error(check the log for more information) quelqu'un peut m'aider?!!?

**Comment by yodidon** [comment]
@kleenex31 essai avec cette version et dis moi
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.7.7

**Comment by kleenex31** [comment]
Lors de ma réinstallation de vstream, pu rien ne fonctionne. Ça me marque vstream error. Quelqu'un peut m'aider à la réinstallation

**Comment by kleenex31** [comment]
En passant par downloader ou?

**Comment by yodidon** [comment]
Installer depuis un zip

**Comment by kleenex31** [comment]
Merci du tuyau. Ça l'a fonctionné

**Comment by yodidon** [comment]
Il faudra ensuite mettre à jour

**Comment by kleenex31** [comment]
Parfait! Merci!

**Comment by Che-debarras** [comment]
Ne peut on pas laisser les posts propres je veux dire éviter de poster des bugs non lié au sujet?
Ouvrir un autre post pour les problèmes d'installation
@kleenex31

**Comment by Che-debarras** [comment]
> Du coup j'ai fais une correction de redirection sur cinemay pour opsktp mais le hoster ne fonctionne pas tout de même fsimg ==> Frenchvid.
> Ps: mon log me retourne cette url:`Error, could not open file https://www2193.o0-5.com/token=FCpUsW-3-dZhoP3ZHA753Q/1586657747/2a01:cb10::/78/8/63/be2d3d2ab1a7394c83eed68c8ddb3638-1080p.mp4` du coup quand je la colle dans le navigateur sa fonctionne!!!!!!
> 
> Edit: en fait çà marche mais avec beaucoup de mal

Tu parles bien de frenchvid?

**Comment by yodidon** [comment]
Vidoza est pour ma part fonctionnel

**Comment by Che-debarras** [comment]
> Vidoza est pour ma part fonctionnel

J'ai mis a jour avec les correctifs de Sizanic et revérifier ceux qui bug et certains sont résolus et des précisions pour certains.

J'espère que cela ne vous fait pas trop de travail
Merci

**Comment by eco-plus** [comment]
@Che-debarras au bout de 30s kodi stop tout, il faut mettre un timeout a 60s dans le fichier advancedsettings.xml mais sa sert a rien parce que si l'host galère a te donner une page html, il galérera pour la video. (surchargé)
- a mettre a jour > [vid fast](https://gist.github.com/eco-plus/01b885b35728f33ea1b7253850bff8fc)

**Comment by Che-debarras** [comment]
> @Che-debarras au bout de 30s kodi stop tout, il faut mettre un timeout a 60s dans le fichier advancedsettings.xml mais sa sert a rien parce que si l'host galère a te donner une page html, il galérera pour la video. (surchargé)
> 
> * a mettre a jour > [vid fast](https://gist.github.com/eco-plus/01b885b35728f33ea1b7253850bff8fc)

Je dois installer ton vidfast.py c'est ça ? 
Oui effectivement s'il galere pour une page internet j'imagine même pas pour une vidéo 

J'ai juste listé les bugs pour faciliter le travail des devs et pas être embêter avec plein de poste car pour par ma part j'utilise très peu de source quand frenchvid et mixdrop et clipwatching fonctionne (plntstrm et seriestrmngHd, kaydo) et au pire y'avais les uptostrm/Uptobox)

Mais vu que aucun de marchais j'ai du faire un post de bug car ces sources ont de bonne résolution HD pour les film et séries

**Comment by razorex** [comment]
@Che-debarras j'ai mis la modif de vidfast dans la beta.
-Papstream vidtodo en fait c'est un nouveau clone ==> viddoto, que j'ai rajouter dans la lib hoster.
PS: pour l'instant je n'arrive pas à lancer un lien pourtant le hoster et bon on récupere bien le mp4.
`ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file https://s13.vidtodo.com/2fb37bjr2ahryyflg7i6otiaxrfl7nyu3conrmaunlwj4lvnf22zwlrhd2aq/v.mp4
2020-04-12 11:30:04.072 T:5780   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer`

**Comment by Che-debarras** [comment]
J'ai mis a jour ce qui est résolu 
Je supprimes ce qui sont OK et RÉSOLU ?

**Comment by razorex** [comment]
@Che-debarras pb de DNS sauf erreur, comme pour tv_seriestreaming.

**Comment by Che-debarras** [comment]
> @Che-debarras pb de DNS sauf erreur, comme pour tv_seriestreaming.

Je change le dns comme d'habitude,  lequel utilse tu pour accéder à ces 2 sites car j'ai essayé plusieurs dns et même sans impossible d'accéder à  kaydo ou tvseriestrmng

**Comment by yodidon** [comment]
Pour moi kaydo fonctionne avec un dns 1.1.1.1 ou 8.8.8.8 je sais plus je regarderais ce soir (le site je parle hds) mais j’ai la protection ddos et je me demande si c’est pas de là que viens le souci sous vstream

**Comment by TmpName** [comment]
Netu, on a signalé que la protection captcha etait de retour.

**Comment by Che-debarras** [comment]
@TmpName Oui mais avant il été désactivé donc peut être le re désactiver jusqu'à sa correction. Je ne fais que signalé pour être exhaustif (je n'attends pas de correction pour ce host ni pour vidlox qui n'ont jamais marché). Je fait le taggue avec Recapcha posant problème 


@yodidon j'ai utilisé les 2 dns (google, cloudfare et même open dns et bien d'autres ) mais sans succès on a pas accès aux films et series. Donc ton ddos semble être la solution

**Comment by razorex** [comment]
pour vidlox il faut faire une modif du hoster pour récupérer ce lien:
![url](https://user-images.githubusercontent.com/26149640/79070350-8b969000-7cd5-11ea-889a-73834742da27.PNG)
et le rename en `https://c16.vidlox.me/hls/oudvhpv35jtk2yixv65owbrgjkzzs6bydh3k6e4p4nctksucsp5o2a5wihya/index-v1-a1.m3u8`
mais je vois pas comment on créer cette url!!

**Comment by sizanic** [comment]
Ce n'est pas dans le fichier .ts ?

**Comment by razorex** [comment]
du coup j'ai 3 fichiers
![dest](https://user-images.githubusercontent.com/26149640/79071636-1af37180-7cdd-11ea-8521-e9cf5bac6755.PNG)
master index et seg

**Comment by razorex** [comment]
Je pense qu'il faut utiliser UA??
![UA](https://user-images.githubusercontent.com/26149640/79071749-a836c600-7cdd-11ea-88b9-377e30d96eb3.PNG)
et mettre en forme avec les retours de request header

**Comment by Che-debarras** [comment]
La mise a jour rend les liens hosts visible mais tout comme frenchvid il y a echec de lecture pourtant sur le site ça fonctionne bien , testé avec city on hill sur filmstreamvk

**Comment by razorex** [comment]
J'ai fais une correction sur clipwatching en rapport avec planetstreaming @Che-debarras

**Comment by Che-debarras** [comment]
> J'ai fais une correction sur clipwatching en rapport avec planetstreaming @Che-debarras

Malheureusement il ne fonctionne pas cet correction,  j'ai essayé plusieurs film et sans succès sauf 1 : bad boys for life qui a marché mais je du cliquer 2 ou 3 fois pour le lancer

**Comment by eco-plus** [comment]
@Che-debarras 
- 1 : frenchvid et Dustreaming, quand on arrive enfin a lancer une video, ces 2 hosts resolve a nouveau le lien alors que la vidéo est deja en lecture et du coup ça plante 
>> c'est parce que tu clique 2 fois d'affiler sur le lien au lieu d'une.

- 2 "mais j'ai du cliquer 2 ou 3 fois pour le lancer" c'est pas a cause de vstream
 >>  c'est les serveur qui sont surchargé donc ça sert a rien de le dire ici

edit: c'est vrai les hosters il y a plus grand chose qui fonctionne correctement soit fichier introuvable ou les hosts sont surchargé et ça finis en timeout ou ça freeze meme  en 360p lol

**Comment by eco-plus** [comment]
et je sais pas si vous avez remarqué mais il y a plusieurs fois le meme site sur vstream.
 - dp streaming
 - serie streaming watch
 - streaming series
etc.. tous ceux avec protecstreambypass le décodage de 5 seconde.
ce sont les memes liens hébergeur.

**Comment by TmpName** [comment]
Oui ^^.
Quand tu fais la recherche globale, m'en suis rendu compte aussi.

Mais j'ai pas reagardé si ils se volaient les liens, je crois qu'il n'y a pas le meme catalogue sur les sites.

**Comment by Che-debarras** [comment]
@eco-plus

Pour ton 1: sérieusement si c'est pour sortir une bêtise pareil faut mieux pas repondre. Évidement que non je clique pas 2 fois de suite. 

Pour ton 2 : la pareil tu sers a rien a part critiquer inutilement, c'est un problème de vstream car le site internet ça marche parfaitement.

Pour ta conclusion : jamais 2 sans 3, tu donnes avis personnel qui ne sert a rien et tout ton message est pas productif.

Je t oblige pas a repondre ni a corriger ses bugs donc si ça t'intéresse pas abstiens toi de repondre et de critiquer les  postes.

Ton poste sur le fait que les même hébergeurs aussi n'est pas productif mn

Bref tu semble critiquer vstream son contenu et les gens qui participent à l'améliorer.
Le débat est clos merci de s'abstenir de critiquer si tu n'apportes rien

**Comment by sizanic** [comment]
@Che-debarras 
vous vous êtes mal compris je pense.

Car ne te fies pas à l'ancienneté de @eco-plus sur git, il a assez participer à vStream dans le passé pour ne pas le dénigrer. (Si je ne me trompe pas)



Sur la question du partage des bibliothèques, il faut savoir si les sites proposent exactement la même bibliothèque et les mêmes hosts derrière.
On peut alors considérer avoir affaire à des clônes.
Et il faut se demander de l'interêt de les garder tous.
(sauf par sécurité si celui qu'on garde venait à tomber)

**Comment by yodidon** [comment]
Je pense que t’avoir dès sources au cas où est une bonne idée , nous savons tous qu’elles peuvent disparaître très rapidement.
Je proposerais même que l’on ait dès source prêt à être utilisé dans le cas où. Par exemple en ce moment je suis sur 2 sources que je surveille et qui fonctionne plutôt bien. Et une particulièrement qui serait le remplaçant de kaydo. Je ne l’es pas encore fini les hoster sont assez dur pour mon niveau mais j’y travail et je me dis qu’elles pourront être utile en temps voulu.
Pour ce qui est des bibliothèques, il est évidant que chacun des sites essaient d’avoir le dernier film et en ce moment pour bien connaître le milieux les sorties des films vont chuter très rapidement ce qui va sans aucun doute faire apparaître énormément de ressemblance de bibliothèque.

**Comment by eco-plus** [comment]
alors pour mon 1:
 -  je confirme ça m'est deja arriver de cliquer 2 fois avec la telecommande sans faire gaffe est ça plante.
 - malgré le faite que je te l'ai déjà dit tu n'as pas l'air d'avoir compris >> kodi stop tout au bout de 30s si il n'obtient pas la réponse donc vstream n'y est pour rien.

pour mon 2:
 - ça marche "parfaitement" sur le site, oui sans doute 10 , 20 seconde et après ça bug mise en cache ,freeze etc.. j'ai eu l'expérience hier en fixant vid fast
 - n' oublie pas avant de dire que ça fonctionne pas sur vstream qu'on utilise le meme liens final donc...

ma conclusion aussi: 
 - la plupart des hébergeurs de vidéo aujourd'hui sont en carton, il est parfois impossible de regardé un film ou une série selon les heures, encore pire si on choisis de la qualité.
pour au final avoir des gens comme toi arrivent et viennent dire ça marche pas!

et de 3 tu ne participe en rien au projet, tu n'as aucune idée du fonctionnement de kodi et vstream,
au lieu de venir ici dire ceci cela fonctionne pas, essaie de le réparé.

**Comment by sizanic** [comment]
@eco-plus 
Je ne dirais pas que @Che-debarras ne participe en rien au projet.

Les diagnostiques qu'il fait (et qui sont assez poussés) et qu'il rend compte ici est sa façon de participer.
Il n'a sans doute pas les compétences techniques de développer et participe comme il peut.
(perso, je me sers de ses comptes-rendus pour choisir mes prochaines corrections)


En fait vous êtes complémentaire.
Revenez sur un échange plus collaboratif s'il vous plait.

Serrez-vous la main, et on avance !!

**Comment by Che-debarras** [comment]
A @eco-plus 

1- je repète je ne clique pas 2 fois de suite je fait gaffe justement mais ce que tu comprends pas c'est que le lien considère 2 clique de suite alors que c'est pas le cas.
Ton avis sur le kodi stop au bout de 15 sec ou 30sec ne tient pas la route car justement quand je clique 1 fois et quil stop pour dire fichier introuvable,  et bien ce 1er clique n'est pas stoppé et le fichier n'est pas introuvable. 
Il se lance quand même après  in 2eme clique et pendant que ce 1e clique a finalement lancé la vidéo,  c'est le 2e clique qui s'affiche en demandant de choisir la qualité et là on si on annule la 2e clique il plante et pareil si on choisi de garder la 2e clique

Donc je pense que cette histoire de 2e clique c'est vstream, on a le même problème avec uptobox,  1 clique : dossier vide et 2e clique fichier trouvé.

On a aussi le meme avec les paramètres de vstream quand on supprime les caches, il fait le boulot mais une 2e fenêtre s'ouvre pour la même chose.

2- pour moi ca  de bug pas apres 10 20 ou 30 il se lance parfaitement sans freeze si on choisi la bonne source le bon host, le vidfast cest normal mais tu fais une exception une généralité avec un host que personne utilise donc non on utilise pas les meme lien au final car pas les même films pas les meme sources pas les memes hosts
Je vois que tu es du genre a tout ramener a ta facon d'utiliser kodi ou tes propres soucis avec kodi

Jusqu'à ce weekend j'ai jamais eu de souci avec kodi, je t'invite a verifier mes posts je posts uniquement quand plus rien ne marche car ya toujours une source ou un host qui fonctionne pour le film ou la série.

Je peut t'envoyer une capture d'écran que tu vois que j'ai mis en favori plusieur sources pour une serie (j'en ai jusqu'a 15 sources  et quand aucun ne marche je post le bug)

Conclusion : tes explications ne tiennent pas la route et les gens comme moi qui viennent dire que ca marche pas nous somme nombreux et c'est le principe de ce site sinon dans ce cas fermer la section bug idee etc.. si les gens comme moi sont inutile

Ton 3 confirme que tu es juste la pour te défouler surement a cause du confinement qui commence a te rendre de mauvaise humeur et agressif 
Et si seul les bug été  pour les devs et pas les utilisateurs alors faut interdire l'accès a ce qui utilise vstream et sans les utilisateurs je vois pas comment vstream pour exister.

Et vu ton historique tu na jamais contribué a vstream ni poster avant ce weekend 
Donc c'est plutot les gens comme toi qui ne font rien de productif et passe leur donne a critiquer les autres sans raison.

Bref on va clore cette discussions car je vois que tu est de mauvais foi et que ton avis semble perturbé par le confinement 

Et @sizanic @eco-plus a bien résumé le problème sois plus collaboratif sinon je peux arretez de lister les bugs si ça dérange mais vous aurez des dizaines d'autres,  j'ai juste voulu éviter que les devs sont submergés pas ces dizaines de bugs.

Sur ce. Merci de ne plus répondre sauf si c'est pour t'excuser ou avoir des propos plus respectueux et plus productif.

Gardons ce post propre aussi je demanderais bien de supprimer les posts de @eco-plus et les miens sur ce litige.

Merci bonne journée

**Comment by sizanic** [comment]
1 - Pour le double-clic, eco-plus est resté courtois en t'expliquant que ça lui est déjà arrivé par une mauvaise utilisation de la télécommande.
Ton explication est maintenant plus clair. 1er clic -> fichier introuvable, 2eme clic, 2 réponses car le premier à fini par réagir.
Pour la dernière partie, c'est ton interprétation. Ce n'est pas forcement parce que le premier clic à fini par réagir. Je pense que c'est ce qu'Eco-plus essaye de t'expliquer.
(et je note qu'il y a bien eu 2 clics).

Si eco-plus est bien la personne que je crois, je t'ai dis de ne pas te fier à son historique avant de l'accuser de n'avoir rien fait de productif ...


@eco-plus, che-debarras ne passe pas son temps à dire que ça marche pas. Il prends du temps pour vraiment analyser (et tente parfois des explications mais peut se tromper). Son travail est vraiment utile pour nous les développeurs (donc pour toi).

**Comment by TmpName** [comment]
En passant je viens de mettre une nouvelle version de Doodstream, avec un lien pr tester, car beacoup sont mortes (L'ancienne methode a une faille, elle ne marche que si il y a un lien de dl, et je n'ai pas trouvé comment le forcer quand c'est une page embed)

Pas sur que ca tienne dans le temps par contre
