### ISSUE TITLE
kaydo injoignable

### ISSUE THREAD

**Issue by yodidon** [Kodi-vStream/venom-xbmc-addons#2850]
sauf erreur , impossible d'aller sur kaydo

**Comment by Che-debarras** [comment]
J'ai fait une récapitulative des bugs où le problème est mentionné et que c'est du au site internet  qui ont un problème et donc non lié a vstream

Il faut vérifier avant les posts avant de poster

**Comment by yodidon** [comment]
Merci pour cette info mais je ne crois pas que ce soit lié à un problème réellement et il me semble nécessaire donc d’ouvrir cette discutions qui apportera peut-être une réponse du côté de cloudflare

**Comment by razorex** [comment]
Kaydo moi il y a déjà longtemps que je n'ai plus accès comme tv_seriestreaming. Sauf erreur c'est un pb de DNS. Erreur 10061

**Comment by TmpName** [comment]
Perso quand j'y allais une fois sur deux j'etais bloqué par un captcha, sans savoir pourquoi.

**Comment by Che-debarras** [comment]
Moi j'y vais souvent jusqu'à vendredi ça a buggué  (je parle des series) avec frenchvid et j'utilisais une application qui change le dns mais depuis samedi plus rien ne marche
