### ISSUE TITLE
Problème d’installation addon

### ISSUE THREAD

**Issue by yodidon** [Kodi-vStream/venom-xbmc-addons#2851]
Il a fallu que je désinstaller vstream de mon kodi. Une fois que j'ai réussi à le réinstaller, ça me dit vstream error(check the log for more information) quelqu'un peut m'aider?!!?

_Originally posted by @kleenex31 in https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2849#issuecomment-612551563_

**Comment by Che-debarras** [comment]
J'ai eu le même souci apres une mise a jour j'ai du installer une ancienne version qui marche puis fait une maj manuel et tout est revenu dans l'ordre

**Comment by yodidon** [comment]
Ce problème a été résolu je l’ai juste déplacé merci @Che-debarras

**Comment by samilarson86** [comment]
Bonjour à tous,

J ai eu le même problème d installation de vstream et je suis passé par une ancienne version de kodi et de vstream pour solutionner. Toutefois la source otaku.fr a disparue ... Si vous avez une idée pour solutionner je suis preneur ( c était une source de contenus particulièrement géniale). Merci aux développeurs pour le travail qu ils réalisent.

**Comment by sizanic** [comment]
Nouvelle mise à jour 0.7.9 disponible, elle corrige les problèmes d'installation ...
