### ISSUE TITLE
Recherche tirexo  : incohérences et dysfonctionnements

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#2852]
Je ne souhaite pas vous envahir encore avec ce sujet cependant, la recherche tirexo présente des incohérences, des dysfonctionnement que je souhaite vous signaler.

En effet à la recherche des éléments suivant,  il n'a aucun résultat alors que les documents existent : (pour exemples) 

Recherche tirexo BARBRA STREISAND aucun résultat ,alors qu’on trouve les films avec BARBRA ou STREISAND
Recherche globale BARBRA STREISAND on trouve tous les films  

Recherche tirexo MOURIR D’AMER aucun résultat avec ou sans apostrophe 
alors qu’on trouve les 2 films avec AIMER OU MOURIR
Recherche globale MOURIR D’AMER on trouve les 2 films 

Recherche tirexo ET TA SŒUR aucun résultat 
alors qu’on trouve le film et la pièce de théâtre avec SŒUR
Recherche globale ET TA SŒUR aucun résultat , alors que les 2 documents sont trouvés sous autre catégories.

tirexo étant la référence en matière de catalogue, il est très regrettable qu'une recherche soit veine alors que les documents sont disponibles...

En espérant que vous puissiez corriger ces anomalies., merci encore pour votre travail et les améliorations permanentes que vous apportez à vstream pour le confort de nous tous.

kris

**Comment by sizanic** [comment]
En effet, et en plus de ne pas retourner les résultats attendus, tirexo en retourne qui ne correspondent pas du tout. Et il y a aussi dans les retours : des jeux, films et musique.

**Comment by LordVenom** [comment]
@kris06 merci pour le rapport de bug.
