### ISSUE TITLE
Creation d'une fonction

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2853]
Je remarque que plusieurs hosters proposent plusieurs lien sauf que l'on en récupère que 1.
ex clipwatching `["https://s570.clipwatching.com/zx5x7hhqbf2dxcne4z2sbgv3zqlxfe5t2nw4jfp3caqicyhuxsxtr2bqr6oa/v.mp4","https://s570.clipwatching.com/zx5x7hhqbf2dxcne4z2sbgv3zqlxfe5t2nw4jfp3cyricyhuxsx3rba63vga/v.mp4"]`
comme on peut le voir il y a deux url différente mais on ne récupere que la premiere.
L'idée, sauf si elle existe déjà, créer une fonction dans commaddon.dialog qui s'appelerait 'VSselecturl'
qui récupérerait plusieurs url. Qu'en penser vous?????

**Comment by Che-debarras** [comment]
Est ce que les sites internet utilisant clipwatching font le basculement automatique vers le 2e lien si le 1er est mort?
Car je me demande si dans planetstrmng par exemple le 1e lien fonctionne pas mais le 2e si
Le site internet récupère le 2e lien tandis que vstream ne peut pas.

Car j'ai beau cliquer sur host dans planetstrmng c'est fichier introuvable mais sur le site internet il en trouve une

**Comment by razorex** [comment]
j'ai testé en copiant les deux liens dans un navigateur et ils sont fonctionnel les deux.

**Comment by razorex** [comment]
ex tu vois il est marqué verystrem alors que le lien est jetload:
`<a href="https://jetload.net/e/T1zIx1m2qITm" title="Regarder Pinocchio (2019) Avec" target="seriePlayer" class="fstab"><i class="fa fa-youtube-play"></i> VeryStream&nbsp;&nbsp; </a>`

**Comment by sizanic** [comment]
Pourquoi ne pas utiliser `dialog().VSselectqual(qua, url)` ?

Le tableau de qualités à fournir n'est que du texte.
Si on ne connait pas les qualités, il suffit de fournir des textes génériques : ['Lien 1', 'Lien 2']

**Comment by razorex** [comment]
j'y avais aussi pensé. pk pas. Après je mettais dis une fonction, une utilisation.

**Comment by razorex** [comment]
mais maintenant que tu me montre la liste çà parait évident...

**Comment by sizanic** [comment]
Oui, une fonction -> une utilisation.

Mais il y a des chances qu'ici ce soit deux qualités différentes mais on n'arrive pas à savoir lesquelles.

Alors les textes génériques pourraient être ['Qualité 1','Qualité 2'].
Et alors ce serait propre d'utiliser VSselectqual.

**Comment by razorex** [comment]
Il y a easyload en hoster sur ce site (sous Mystream).
une url `https://easyload.io/e/B7dKoMD8dn` j'ai beau essayer j'y arrive pas

**Comment by eco-plus** [comment]
@razorex en réponse a ton 1er post ,si il n'y a pas de différence de qualité entre les 2 urls ou alors la qualité est du 240p ça sert a rien.

**Comment by sizanic** [comment]
> Il y a easyload en hoster sur ce site (sous Mystream).
> une url `https://easyload.io/e/B7dKoMD8dn` j'ai beau essayer j'y arrive pas

@razorex 
easyload est un nouvel host ? -> crée une nouvelle issue.

@eco-plus
Les deux liens sont des mp4 et on n'a aucune information de qualité. On ne peut pas savoir si ce sont les mêmes ni si ce sont des basses qualités. On ne peut que les proposer et l'utilisateur les testera l'une après l'autre.

@razorex 
Tu mets VSselectqual dans clipwatching du coup ?
Puis clore cette issue.

**Comment by razorex** [comment]
Dsl d'avoir trainer. du coup oui j'en ai terminer. pour info je n'ai vu que sur planet streaming que l'on proposait 2 liens donc du coup il n'y a que la que l'on propose une sélection.

**Comment by sizanic** [comment]
impec.
Je me suis permis un petit commentaire sur ton code.

**Comment by eco-plus** [comment]
#2847

**Comment by Che-debarras** [comment]
> Dsl d'avoir trainer. du coup oui j'en ai terminer. pour info je n'ai vu que sur planet streaming que l'on proposait 2 liens donc du coup il n'y a que la que l'on propose une sélection.

@razorex 

J'ai clos mon post maks juste pour te dire que ton idée à résolu les problèmes de clipwatching sur les sources que j'avais mentionné sur mon recap' de bug.

Ex: avec city on hil s01ep3 sur strmngserie on avait que 2 liens non fonctionnelle alors qu'avec ta correction on n'a 4 liens dont 2 est fonctionnelle.

Chapeau l'artiste 👏👏👏👏👏👏👏

Ce correctif ideal peut il être appliqué à d'autre hoster comme Frenchvid, mixdrop Dustreaming etc... ce qui bloque 

Merci un pei, beaucoup, passionnément,  à la folie 🙃
