### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2856]
Question idiote mais comment met on le repository à jour??
Faut il juste remplacer le zip??

**Comment by sizanic** [comment]
Le mettre à jour dans une installation de Kodi ?
Comme tous addon, dans la boite d'information du repository, avec le bouton "mettre à jour", si tu n'as pas activé "Mise à jour auto."

**Comment by razorex** [comment]
non sur le git.

**Comment by TmpName** [comment]
Ha oui, bonne question.
Je pense que les fichiers addons.xml et addons.md5 ne sont utiles que pour les plugins.

Apres ca doit marcher pareil, en editant le fichier  addon.xml qui se trouve dans.

**Comment by razorex** [comment]
oui c'est à l'instal que tu le décompresse dans kodi. Du coup je me dis que j'ai juste à remplacer les fichiers et PR le zip. je vais rename l'autre pour ne pas le perdre.

**Comment by razorex** [comment]
c'est PR

**Comment by TmpName** [comment]
Par contre je viens de passer le lien sur une issue

Officiellement ton fichier n'apparait pas dans la home page, ni dans les releases.

Le lien officiel est toujours https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.0.3

**Comment by razorex** [comment]
Du coup j'ai remplacé le zip de la release, sans renumérotation.le lien est opérationnel. Mais cheloux de gérer le Repository à deux endroit.

**Comment by TmpName** [comment]
Ben pareil, j'ai vu ca hier, ca fait beacoup de manip.

Edit:
Ca marche pas ^^, enfin si mais je tombe encore sur la vielle version, en bleu non degradé.

**Comment by razorex** [comment]
ben moi j'ai essayer je tombe sur la nouvelle??
Ton lien est bon regarde la taille du fichier elle est différente.

**Comment by TmpName** [comment]
Ben c'est dans le fichier, quand je regardes les images, j'ai la vielle version.
C'est chez moi que ca deconne ?

**Comment by razorex** [comment]
Ben je viens de retester le téléchargement du repository depuis la page d’accueil de vStream.
on a bien le dernier fanart et icon dans le zip. Tu a installé le nouveau repo et tu a encore les anciens @TmpName ????? va voir dans le dossier repo vstream de kodi.
![fanart](https://user-images.githubusercontent.com/26149640/79633872-815a1300-8167-11ea-81b9-fc13ef19ce56.jpg)

**Comment by razorex** [comment]
Je confirme c'est drole une fois on affiche le nouveau, tu entre dans le dépots, tu ressort et kodi à repris le vieux, sa dois venir du cache de kodi.

**Comment by TmpName** [comment]
boa, tant que ca marche.
