### ISSUE TITLE
Fresh install k.o ?

### ISSUE THREAD

**Issue by PunkyBust** [Kodi-vStream/venom-xbmc-addons#2857]
Hello à tous, 

J'ai eu des soucis d'authentification sur 1 fichier et uptobox via mes comptes premium, j'ai donc refais une install au propre de kodi constatant que sur mon téléphone je n'avais pas ce comportement. 
Malheureusement le nom de domaine du repo (vstream.ml) ne semble plus existant et en récupérant le zip sur le github je parviens à finalement installer vstream mais impossible de le démarrer j'ai tout de suite une erreur (vstream error). 
Impossible de generer un log dans vstream j'ai la même erreur. C'est comme si vstream n'était pas totalement complet (ex: le changelog et à propos vide, rapport de log non fonctionnel, auteur inconnu) 
Ce problème est présent uniquement lors de l'installation pas lors de la mise à jour. 
Je n'ai donc malheureusement pas de log verbeux à vous partager. 
Avez-vous une idée du problème à savoir que j'ai été en capacité de reproduire ce comportement aussi bien sur firetv que sur smartphone.  
Merci à vous 😊

 - OS: [Windows, Android]
-  Appareil : Fire Tv et Smartphone Android 9
 - Version Kodi  18
- Version Vstream 0.7.8 et repo 0.0.3

**Comment by PunkyBust** [comment]
![IMG-20200414-WA0000](https://user-images.githubusercontent.com/63625157/79180730-f4cbef80-7e0a-11ea-8825-835ae5bade7b.jpg)

**Comment by PunkyBust** [comment]
![IMG-20200414-WA0001](https://user-images.githubusercontent.com/63625157/79180916-6f950a80-7e0b-11ea-8ed6-f257044a2ac7.jpg)

**Comment by PunkyBust** [comment]
J'ai reussis à chopper quelque logs intéressants.

**Comment by yodidon** [comment]
Tu peux essayer d’installer cette version et ensuite de mettre à jour.
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.7.7

**Comment by sizanic** [comment]
Oui, le bon titre à choisir était bien : "Fresh install k.o"

La solution de @yodidon est la bonne.

Sujet déjà abordé ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2842 - impossible d'installer Vstream depuis 2 jours

**Comment by PunkyBust** [comment]
Hello,
Merci à vous ! Nickel en passant par le 0.7.7 puis update c'est nickel.
A bientôt, merci pour votre travail

**Comment by tuego72** [comment]
Nous on a fait settings, click sur default ensuite ok et ça fonctionne je ne sais même pas pourquoi^^

**Comment by PunkyBust** [comment]
Ok bon à savoir @tuego72
