### ISSUE TITLE
Installer Vstream

### ISSUE THREAD

**Issue by yassininho** [Kodi-vStream/venom-xbmc-addons#2858]
J’arrive pas à installer Vstream, ni en téléchargeant le .zip ni en utilisant l’adresse http://www.viphosting.sit/depot

 - OS: [Android]
-  Appareil [Box android mecool]
 - Version Kodi  [18.6]
- Version Vstream 7.8

**Comment by TmpName** [comment]
Alors je me souvient plus ou se trouve cette adresse, meme si je l'ai deja vu, mais un conseil ne va plus sur ce site.
Essayes avec cette adresse https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.0.3

**Comment by sizanic** [comment]
Oui, installe le repo officielle.
Puis installe vStream depuis ce repo.
Et comme tu aura installer le repo, les mise à jour de vStream seront automatiques.

**Comment by yassininho** [comment]
Merci pour vos réponses, malheureusement même avec le repo officiel, ça ne fonctionne plus

**Comment by razorex** [comment]
@TmpName  et @sizanic est-ce  que çà peut être du à mon PR sur le repository????

**Comment by sizanic** [comment]
A toi de nous le dire.
Est-ce que tu a essayé d'installer ton repo à partir d'une installation neuve de kodi.
C'est le genre de test qu'il faut faire après une telle modif !

**Comment by razorex** [comment]
Euh, j'ai fais des test mais non je n'ai pas désinstallé kodi puis tout remis.... Tu le fais toi??
Si tu veus je ferais une liste des tests éffectué.
a cet instant j'ai supprimé le repo de vStream ainsi que l'addon (et mes modifs en cours au passage).
Après j'ai télécharger le repo que j'ai installé puis j'ai installé vStream.... pas de souci

**Comment by razorex** [comment]
bon j'ai parlé trop vite c'est le même souci que les autres fois les éééééé
`VSlog('Erreur: Impossible d\'écrire sur %s' % self.REALDB )`

**Comment by sizanic** [comment]
Oui mais cette erreur c'est parce que ça essaye d'installer la dernière version qui a toujours le bug.
Donc tout est bien normal.

Et ton test est bon. Par "installation neuve", je voulais dire sans vStream et sans le repo.
Je voulais faire ce test mais je suis avec le pc du mon taff (sans kodi) et pas mon perso.

**Comment by razorex** [comment]
@yassininho est-ce que tu a l'icone de vStream dans tes addons?????

**Comment by razorex** [comment]
oui parce que l'a tu m'a fais peur, je vais pas systématiquement désinstallé. Il est vrai que comme nous apportons les corrections nous n'avons pas tjrs tout les cas de figure dont celui d'un nouvelle user.

**Comment by sizanic** [comment]
Si @yassininho à installer le repo depuis ce lien : 
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.0.3

=> ce n'est pas ton repo modifié @razorex

**Comment by razorex** [comment]
non c'est l'ancien

**Comment by sizanic** [comment]
tu n'a pas vu le dernier message ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2856

**Comment by sizanic** [comment]
Le test dont je parlais c'est d'installer le dernier repo depuis internet comme le ferait un nouvel utilisateur. Et vérifier l'icone (si c'est bien la modif que tu as faite).

**Comment by razorex** [comment]
pas sur que l'on gere git comme il faut.

**Comment by razorex** [comment]
un user télécharge le repo puis fait une install depuis le zip sous kodi.
ps ce n'est pas le lien du Master??

**Comment by razorex** [comment]
Bon même avec ce lien après avoir tout enlever çà marche quand même le pb c'est tjrs les ééé.
traité mais entre deux eaux

**Comment by sizanic** [comment]
@yassininho 
tu n'a pas un problème d'installation de vStream mais un problème de lancement de vStream.

Sujet abordé ici : 
- https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2842 -  impossible d'installer Vstream depuis 2 jours
- https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2857 - Fresh install KO
- https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2845 - erreur db.py à l'ouverture de vStream
- https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2829 - Bug avec OSMC - Kodi 18.6 


La solution est d'ouvrir la fenêtre des paramètres de l'extension et d'appuyer sur 'D'origine' en bas à droite.

**Comment by sizanic** [comment]
@razorex  pour le problème des accents, il a été réglé en effet en enlevant l'accent.
Puis tu a remplacé le texte (alors sans accent) par un `self.ADDON.VSlang(30039)`
Et derrière ce 30039, tu a remis un texte avec un accent !

-> T'es-tu assuré que ce retour d'accent ne posera pas de problème sur une install fresh de Kodi (sans vStream) sur Android ?

**Comment by razorex** [comment]
@yassininho peut tu installer vStream depuis ce lien [vStream](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/repo/plugin.video.vstream/plugin.video.vstream-0.7.7.zip) c'est une version antérieur qui te permettra de contourner le pb.
oui je sais @sizanic c'est moi qui ai fais les corrections. Par contre ta méthode ne fonctionne pas je viens de tester.

**Comment by razorex** [comment]
oui j'ai remis un accent comme il en a (avait) dans d'autres fichiers. Bon çà pose tout de même souci même en l'ayant mis dans les strings..
C'est vrai que j'aurai du tout désinstaller vStream non je ne l'ai pas fais.. cet accent (Français) est présent depuis longtemps.

**Comment by razorex** [comment]
`File "C:\Users\Herve\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\db.py", line 40, in __init__
                                                VSlog(self.ADDON.VSlang(30039) % self.REALDB)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)`

**Comment by sizanic** [comment]
J'ai pas testé ma technique, ce sont des retours d'utilisateurs, je me suis appuyé sur ces deux sources :  

ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2842#issuecomment-612378566
et ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2857#issuecomment-613568539


Oui je sais que c'est toi qui a fait les corrections.
Tu a enlevé l'accent :+1: 
puis tu l'a remis :thinking: 


Il y a des accents dans d'autres fichiers mais sans doute pas pour du log. Et c'est l'utilisation d'un accent dans VSlog qui a l'air de poser problème.

Un log c'est plus pour du debug ou des traces, le texte n'a pas besoin d'être dans une ressource.

**Comment by razorex** [comment]
ok oui tu a raison inutile dans les logs. ces post dates d'il y a plusieurs jours je pensais (a tord) que leurs pb était d'avant.... comme bc je pense. mon transfert  de é ces fait après. donc ok on vire des logs. je m'en occupe je vais mettre la version anglo-saxon.

**Comment by razorex** [comment]
Par contre c'est bizarre il 'y a que dans la db que çà pause souci alors qu'il il y a plein d'accent dans les logs..

**Comment by sizanic** [comment]
@chrysal  a une piste ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2829#issuecomment-611687735

Un souci d'encodage UTF-8.
A mettre en oeuvre avec soin.

**Comment by razorex** [comment]
Oui j'avais vu son commentaires.

**Comment by razorex** [comment]
Du coup pour des log pas forcément utile de rajouté des modifs dans vStream, comme tu en a fait la remarque. Au pire on traduit en english comme çà plus d'accent et c'est très rapide à faire.

**Comment by yassininho** [comment]
> @yassininho peut tu installer vStream depuis ce lien [vStream](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/repo/plugin.video.vstream/plugin.video.vstream-0.7.7.zip) c'est une version antérieur qui te permettra de contourner le pb.
> oui je sais @sizanic c'est moi qui ai fais les corrections. Par contre ta méthode ne fonctionne pas je viens de tester.

Salut j'ai telechargé le .zip que tu m'as conseillé :"failled to install add-on from zip file the dependency on repository: vstream version 0.0.3 ...."

**Comment by sizanic** [comment]
Ici même, sur la page d'accueil officielle de l'addon vStream : 
https://github.com/Kodi-vStream/venom-xbmc-addons

en bas de la page il y a un paragraphe **Installer !**

![image](https://user-images.githubusercontent.com/47307622/79481821-45f90080-8010-11ea-9e07-9f47882137f8.png)

Tu installes le zip. : c'est le _repository vstream version 0.0.3_.

Ensuite tu installes l'addon vStream version 0.7.7 depuis le zip disponible à cette adresse : https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.7.7 

(Il passera ensuite tout seul en version 0.7.8 fonctionnel)

**Comment by razorex** [comment]
J'ai testé tout a l'heure une installe  a neuf ras..

**Comment by razorex** [comment]
me suis mal exprimer instal comme tu l'a décrite @sizanic et ras

**Comment by stek23** [comment]
bonsoir 
j avais le meme probleme et avec le lien de yassininho,ca marche.
merci

**Comment by dan4400** [comment]
Bonjour 
Ça fais depuis 2 jours que j'essayé d'installer Vstream sur Kodi et grâce au lien de @sizanic tout bon en 30 secondes.
Par contre j'ai un petit soucis. J'ai la liste des films mais dès que je veux en lire un j'ai toujours le message d'erreur Erreur: Fichier introuvable.
Est-ce que quelqu'un a déjà rencontré ce soucis ? 

Je vous remercie d'avance et vous souhaite mes salutations.

**Comment by TmpName** [comment]
Faudrait que tu lances une video, attende le message d'erreur et regardes tes logs.
Tu devrais voir des message d'erreur a nous passer.

Tu as essayé sur un autre site ou tu ne fais que avec le meme ?

**Comment by dan4400** [comment]
Ca me fais avec tout les films et j ai essayé plusieurs liens.

**Comment by sizanic** [comment]
Si tous les films que tu testes se termine par UpToStream ou UpToBox, c'est normal.

Le nom à la fin du titre s’appelle un hoster.
Vérifie ici #2861 que les hosters que tu essayes ne font pas partie de la liste des hosters KO.

**Comment by sizanic** [comment]
Nouvelle mise à jour 0.7.9 disponible corrige les problème d'installation ...
