### ISSUE TITLE
Fenetre chargement des liens 

### ISSUE THREAD

**Issue by benking110181** [Kodi-vStream/venom-xbmc-addons#2860]
Salut comment faire pour que la fenetre de notification de chargement des liens lorsque l on mais sur certaine skin au menu n apparaîsse pas ? Faut il demander au skinner ou cela est un reglage a faire dans vstream .

**Comment by TmpName** [comment]
Tu aurais un screen de cette fenetre stp ?

**Comment by benking110181** [comment]
Non mais c quand tu met en widget un liens vers une page de vstream elle n apparait pas sur accueil mais quand tu va dans paramètres ou plein ecran video ou musique

**Comment by benking110181** [comment]
Il y a le nom du site genre zone t. Ou extrême d. En dessous loading : et la progression du chargement des liens correspondant et en dessous le seul bouton cliquable " annuler "

**Comment by benking110181** [comment]
Elle est présente aussi quand tu rentre dans films titre ou autre et ell charge les liens des widgets ou sous menu de la skin mais elle est en plein milieu de ecran et meme une fois charger elle réapparaît avec loading x/100 de tout les liens

**Comment by benking110181** [comment]
![20200418_123938](https://user-images.githubusercontent.com/25104031/79635530-caaf6000-8171-11ea-94b4-35fab22fee50.jpg)

**Comment by TmpName** [comment]
Alors celle la c'est bien Vstream.
Par contre elle a une utilité, le bouton annuler. Si ca met 5mn pour tout afficher et que la fenetre est desactivée tu risques de t'ennuyer.

**Comment by benking110181** [comment]
Le problème c'est quelle revient en permanence meme en laissant kodi lancer pendant des heures il y a pas moyen de la reduire ou de l afficher comme les maj des bibliothèques

**Comment by benking110181** [comment]
Et si tu va dans ta liste de film par exemple comme elle prend le dessus tu ne peut rien faire en attendant quelle charge et ca arrive de souvent d'annuler par accident juste en faisant ok pour rentrer dans une catégorie ou autre

**Comment by sizanic** [comment]
> Non mais c quand tu met en widget un lien vers une page de vstream

C'est ton skin qui raffraichit les widgets de façon périodique.
Regarde si t'as pas des paramètres dans ton skin ou sur le widget.

vStream ne peut pas savoir si ce refresh vient d'une demande d'un widget oui si tu rentres dans un dossier depuis vStream. On ne peut pas la desactiver pour certains cas et pas pour d'autres.

Et si on la desctive tout le temps, comme le dit @TmpName : 
> Si ca met 5mn pour tout afficher et que la fenetre est desactivée tu risques de t'ennuyer.

**Comment by DaX59** [comment]
Par contre, on pourrait peut-être avoir un timer pour zapper si une source met trop de temps à répondre ? Hier j'ai ma page de recherche qui a bloqué sur extrême pendant un loooooong moment, j'ai du redémarrer Kodi.

**Comment by TmpName** [comment]
Ben j y ai pensé aussi mettre un timeout pour la recherche globale.

Mais ca demande a retoucher tout les fichiers, et ca ne marchera pas dans tout les cas, kodi est bancale, ca freeze tout le temps, dans ton cas il y a deja un timeout (mais trop long) donc meme sans modif ca aurait du s'arretter, la c'etait kodi qui est parti en sucette, d'avoir mit un timeout reduit n'aurait pas changé grand chose.

Moi ca m'arrive meme parfois pendant la lecture du fichier.

**Comment by sizanic** [comment]
Je pense aussi que dans ce cas ce serait resté bloqué.

**Comment by sizanic** [comment]
@benking110181 

Dans la dernière Beta, j'ai apporté une amélioration à ce sujet.
La fenêtre de chargement a été retirée de certains endroits.
