### ISSUE TITLE
SUIVI DES BUGS

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2861]
**ATTENTION**
**Cette liste ne doit être tenue à jour que par les développeurs.**

Si vous corrigez un bug : 
- vous le signaler en commentaire.
- vous modifiez cette liste

Pour toute personne qui pense avoir trouvé un bug, vous le signaler en commentaire et un développeur l'ajoutera à la liste s'il s'avère réel.

Avant de signaler un host qui ne fonctionne pas, pensez à vérifier qu'il n'est pas corrigé dans la beta.

**_Environnement_**
Mise à jour avec dernier commit **e4c3616 de @sizanic **
- OS: [Windows, Android]
- Appareil [Win10, Z6+]
- Version Kodi  [18,19]

**_Sources KO_**

- 

**_Les Hosts KO:_** 
- Netu : toutes les sources **_pb de recapcha_** (patience!)
- Vidlox : toutes les sources (ex :  k-strmng, film : atlantic rim ressurection)
- Doodstream : StrmngK
- Uptostream : Papstrmng, FlmstrmVK
- Mystrm : KStrmng (serie) , Papstrmng (serie) , FlmstrmVK
- OnlyStrm : FlmstrmVK
- Mixdrop : StrmngK
- Prostream : k-strmng
- LIen_direct (Mega) : StrmaySeries
- Upvid : Papstrmng
- Vidoza : Papstrmng, 
- Vidtodo : Voirflm, Papstrm

**_Les Hosts Corrigés_**
- vidfast : flmillmt, Wflx
- Vidoza : Voirflm
- Strmz : StrmngK
- Allow_redirect : k-strmng
- Upstrm :, K-Strmng (Serie), VF.Spce
- Uptostream : K-Strmng (Serie), LibrtyLnd (Série), StrmngK
- Clipwatching : StrmngSeries)

**_Dossiers vides pour:_**
- Adkami 
- Filmstrmvk (catégorie Canal+,Netflix,Youtube Prems)
- Tv_serie_strmg (série derniers ajout, populaire, www)
- KStrmng (SERIE GENRE,ANNÉE, ALPHABÉTIQUE)  
- StrmngDivx (film, épisodes de serie)
- StrmySerie (upstream)
- Kaydo ( CATÉGORIE  DE FILM PAR GENRE)
- ZT (toutes catégories)
- Strmngk (NOUVEAU HOST : vidia)
- StrmngSeries (doodstrm)

**_Dossiers qui s'ouvrent pas:_**
- iAnime
- Kaydo (TOUTE CATÉGORIE  DE FILM SAUF LES + COMMENTÉS, EPISODE DES SERIES)
- Tirexo (source) 
- SeriesStrmg (toutes catégories)
- Zustrm (toutes catégories M)

**_Recherches KO_**
- ianime / trouve des films si on recherche les séries
- kepliz / filtrer par le titre
- libertyland
- mesfilms
- series-streaming
- TIREXO / melange de genre
- streamcomplet 
- streamay_bz

**_Autre bug_**
- Kaydo :Marqué comme vu alors que non vu

**Comment by Che-debarras** [comment]
Tu a réouvert mon post, sache qu'il y a des changements dans les bugs.

Doodstream ok pour Dpstrmng / ko : seriestrmngwtch / vide : seriestrmng
Clipwatching ok pour Dpstrmng & seriestrmngwtch & seriestrmng / ko : planetstrmng 
Mixdrop ok planetstrmng & seriestrming 

Kaydo s'ouvre mais pas le dossier final pour voir le lien host
Pareil pour dossier vide de filmstreamvk ce n'est plus le cas c'est résolu hormis openload je ne trouve plus de film avec ce host ou désactivé par vous même.
De même je ne trouve plus de series avec mixdrop sur filmstreamvk car dossiers des series ou categories des séries vides sauf si Dustreaming 
On dirait que les dossiers Dustreaming vide sont résolus maais du coup les autres sont vides

Filmstreamvk,  au bout de 3 cliques sur suivant on revient à la 1e page

NB : je reverrais un checkup si tu veux pour que ce soit plus concis

**Comment by sizanic** [comment]
@Che-debarras 
oui  j'ai rouvert ton post.
Et je compte sur tes retours pour le maintenir à jour.
Tu peux le modifier directement avec le même niveau de détail que tu viens de décrire dans ton commentaire car je sais que tes tests sont poussés donc valables.

Il faut garder un paragraphe pour lister tout ce qui est "Corrigé dans la beta" tant qu'une mise à jour n'est pas disponible.

**Comment by Che-debarras** [comment]
Ça marche. S

Si je l'ai fermé c'est surtout parce sue les bugs ont été resolus sur ce que j'appelle les hosts majeurs (Frenchvid,  Mixdrop, et clipwatching sur une grande partie des sources)
Il y a les hosts mineurs (vidfast,vidcloud, vidtodo, vid...vudeo) qui sont rares et rarement fonctionnels
Et les nouveaux hosts qui sont résolus (Dustreaming et Doodstreaming).

Je suis juste confus pour frenchvid et clipwatching qui ne fonctionne pratiquement pas voire jamais sur une souce comme planetstrmng ou mystream sur filmstreamvk (série the witcher).

Mais je revérifierais tous ça demain et je tiens a préciser que je suis très reconnaissant de votre addon et votre effort a corriger les bugs et à considérer nos retours de bugs.

Jaurais aimé faire plus mais j'ai pas de connaissance en développement.

**Comment by razorex** [comment]
Clipwatching sur planetstream ==> çà fonctionne mais il est vrai que c'est avec bc de mal.
                     sur dpstreaming ==> çà fonctionne, des liens sont morts comme ailleurs.

**Comment by sizanic** [comment]
> Filmstreamvk, au bout de 3 cliques sur suivant on revient à la 1e page

C'est corrigé

**Comment by Che-debarras** [comment]
> Clipwatching sur planetstream ==> çà fonctionne mais il est vrai que c'est avec bc de mal.
> sur dpstreaming ==> çà fonctionne, des liens sont morts comme ailleurs.

Justement mais sur le site ça marche et ya des hosts présent sur le site mais pas sur vstream comme indiqué sur le suivi des bug : estream vidoza verystream,  sur vstream on a plutot netu mixdrop clipwatching 

Est ce que ce sont les mêmes hosts?

**Comment by razorex** [comment]
Il y en a 2 nouveu qu'il faut que l'on ajoute easyload et hls.
La liste sur le site @Che-debarras (il ne faut pas ce fier au nom que le site affiche)
![host](https://user-images.githubusercontent.com/26149640/79632372-fd9c2880-815e-11ea-8e4b-ce5357bc8710.PNG)
la vérité: a gauche l'url du host et à droite le nom affichés sur le site.
![real](https://user-images.githubusercontent.com/26149640/79632373-fe34bf00-815e-11ea-8a7a-d5458e260b98.PNG)
tu remarquera que clipwatching est affiché en tant que vidoza.
 estream==>mixdrop

**Comment by TmpName** [comment]
frenchvid a fonctionne chez moi ce matin, mais comme il y a plusieurs hoster en 1, vous faites les tests sur quel site pour l'avoir HS ?

**Comment by Che-debarras** [comment]
> frenchvid a fonctionne chez moi ce matin, mais comme il y a plusieurs hoster en 1, vous faites les tests sur quel site pour l'avoir HS ?
> Vidlox, gros JS a dechiffrer mais site pourri, jamais pu lancer une video de mon coté.

Je suis en train de refaire un checkup après les dernières corrections  et pour l'instant frenchvid fonctionne sur filmzenstrem,kstreamng. Donc pas de bug pour l'instant mais j'en suis qu'a Planetstrem.

Je continue les autres sources et je partagerai le bilan

**Comment by Che-debarras** [comment]
**Décrivez le bug**
Mise à jour avec dernier commit **6de263e de @sizanic **

J'ai fait un checkup pour les problèmes de sources et d'hébergeurs ci-dessous pour eviter les doublons de posts.

**_Dossiers vides pour:_**
- Adkami
- Filmstrmvk (catégorie Canal+,Netflix,Youtube Prems)
- Tv_serie_strmg (série)
- KStrmng (serie)
- StrmngDivx (film, épisodes de serie)
- StrmySerie (upstream)
- Papstrmng (vidtodo)

**_Dossiers qui s'ouvrent pas:_**
- iAnime
- Kaydo (toutes catégories)
- Tirexo (source) 
- SeriesStrmg (toutes catégories)
- ZT (toutes catégories) 

**_Autre bug_**
- Kaydo :Marqué comme vu alors que non vu
- planetstrmng : absence de Verystrm (présent et fonctionnelle sur le site mais pas sur vstream 

**_Les Hosts K.O:_** 
- Netu : toutes les sources **_pb de recapcha_** (patience!)
- Vidlox : toutes les sources
- Vidfast : toutes les sources
- Clipwatching : StrmngSeries)
- Doodstream : StrmngK, StrmnngSeries
- Frenchvid : Zufilm
- Upstrm : Zufilm, K-Strmng (Serie), VF.Spce
- Uptostream : Zufilm, K-Strmng (Serie), LibrtyLnd (Série), Papstrmng, StrmngK, FlmstrmVK
- Mystrm : KStrmng (serie), Papstrmng (serie) , FlmstrmVK
- OnlyStrm : FlmstrmVK
- Mixdrop : StrmngK
- Strmz : StrmngK
- Allow_redirect : k-strmng
- Prostrm : k-strmng
- LIen_direct (Mega) : StrmaySeries
- Upvid : Papstrmng
- Vidoza : Papstrmng,  Voirflm
- Vidtodo : Voirflm


NB : au niveau Host ya 10 sources qui bugguent sur les 35 testées


**Votre system**
- OS: [Windows, Android]
-  Appareil [Win10, Z6+]
- Version Kodi  [18,19]

**Comment by Che-debarras** [comment]
@sizanic 
Peut-être remplacé ton 1e post avec mon checkup mise a jour.
(Je n'ai pas testé les iptv ni les sourcs replay,sport etc.. désolé)

**Comment by TmpName** [comment]
@Che-debarras put1 tout ca ? tu es sur pour les hosts ? Y en a plein qui fonctionnent chez moi.

**Comment by razorex** [comment]
Pour verystream je t'ai expliqué @Che-debarras que sur le site il est affiché verystream mais en fait le lien c'est hlsplay, a tu lu mon post ou alors je n'ai pas été clair???

**Comment by Che-debarras** [comment]
> @Che-debarras put1 tout ca ? tu es sur pour les hosts ? Y en a plein qui fonctionnent chez moi.
> 
> Tv_serie_strmg (série) > site HS
> KStrmng (serie) > ok chez moi
> StrmngDivx (film, épisodes de serie) > non fonctionnel sur le site non plus.
> Papstrmng (vidtodo), encore un clone, j'ai fais la modif, mais pas pu tester lien HS.

Oui je suis sûr mais je dis pas la source est hs juste les host mentionné, testé plusieur series sur kstrmng et c'est  hs pour ces hosts.


@TmpName c'est quoi ta config? Quel version de kodi et quel version de vstream? 
Moi box tv android 7 kodi 18 et dernier version de vstream

**Comment by sizanic** [comment]
> Peut-être remplacé ton 1e post avec mon checkup mise a jour.
> (Je n'ai pas testé les iptv ni les sources replay,sport etc.. désolé)

Je vais mettre à jour, merci pour ce travail.
Pas besoin de tester les replay, sports, et encore moins les IPTV.

Mais je vais aussi croiser avec les retours de @razorex et les miens.

Par exemple, j'ai bien des dossiers pour 
Filmstrmvk (catégorie Canal+,Netflix,Youtube Prems)

**Comment by sizanic** [comment]
Pour info, une nouvelle source à tester : 
ZT.stream 😉

**Comment by Che-debarras** [comment]
J'ai bien les dossiers aussi pour filmstrmvk, y compris les dossiers de series et meme de episode mais ya aucun lien host pour pratiquement toutes les series

De plus sur le site de la source la catégorie renvoie sur dpstrm.info qui semble être a jour met pas sur vstream et sur ce dpstrm.info the witcher fonctionne grâce a uqload non present sur vstream

**Comment by TmpName** [comment]
Machine windows / kodi 18 / Dns google / mais version de vstream perso.

**Comment by sizanic** [comment]
dpstrm.info est un autre site, nous n'avons pas développé cette source.
Il faut rester sur vK pour comparer.
Pour les séries : h ttps://filmstreamvk.bz/series

**Comment by Che-debarras** [comment]
@TmpName je crois que le fait que tu as ta propre versionnde Vstream explique pour quoi cela marche
Moi j'ai toujours utilisé la versoonndu github et pour répondre aussi  à @sizanic oui je vais directement sur le site.
Je récupère l'adresse du site sur le fichier.py de la source dans le github et je l'ouvre avec un navigateur

C'est pour cela que avec flmstrmvk si on clique sur séries on est automatiquement redirigé sur dpstrm.info et je ne vois pas non plus les categories netflix canal+ etc.. sur le site directement.

Jusqu'ici je compare de la sorte pourquoi y a un souci ?

**Comment by TmpName** [comment]
Sinon Je pense qu'on peut virer speedvid ?

Tu as un site avec vidlox ou vidfast HS qui fonctionne sur navigateur ?

Mixdrop reparé, c'est juste que certain site utilise la page "enbed" et d'autre non, donc le meme hoster mache sur certain site et pas d'autre.

**Comment by Che-debarras** [comment]
@TmpName pour vidfast j'ai rectifié c'est corrigé avec la dernier modif d e@sizanic désolé maos pour vidlox sur k-strmng film atlantic rom ressurection hs sur vstream mais ok sur le site

**Comment by sizanic** [comment]
> C'est pour cela que avec flmstrmvk si on clique sur séries on est automatiquement redirigé sur dpstrm.info et je ne vois pas non plus les categories netflix canal+ etc.. sur le site directement.
> Autant pour moi, je dois manuellement ajoutera categories sur l'adresse du site flmstrmvk+ netflix pour avoir la page sir le navigateur

Normalement c'est la bonne méthode de parcourir le site. mais parfois on fait mieux que le site lui-même. On arrive à retrouver des catégories qui ne sont pas visibles sur le site.
Et on ne suit pas les redirections vers d'autres sites.
Donc ici on n'utilisera que les séries dispo sur ce site, sinon il faudrait développer une nouvelle source pour analyser dpStrm.info.

**Comment by jesusisback66** [comment]
pour resumé en gros y a rien qui fonctionne ?

**Comment by sizanic** [comment]
bah non, en gros y'a pratiquement tout qui fonctionne.
Là on parle des derniers cas particuliers.

**Comment by Che-debarras** [comment]
@sizanic pour Dpstrmnginfo pas la peine c'est un clone de flmstrmvk mais ya des liens hosts qui manquent sur vstream mais présent sur le site 

@jesusisback66 comme dit @sizanic c'est les derniers cas particuliers pour parfaire Vstream mais tu peux largement te faire plaisir et trouver tous ce que tu veux avec les autres sources ou liens. 
Ces bugs ne gênent en rien l'utilisation de vstream c'est pour parfaire et nettoyer vstream je suppose.

Et ça marche tellement bien que 2 nouvelles sources sont ajoutées donc longue vie à  Vstream 😉

**Comment by sizanic** [comment]
Et ça marche tellement bien que je vais préparer une mise à jour officielle pour passer en 0.7.9 😉

**Comment by jesusisback66** [comment]
euh vous etes sur j'ai rien qui fonctionne moi sous librelec avec la beta ?

**Comment by sizanic** [comment]
vraiment rien de rien ne fonctionne ? 🤔 

Il nous faudrait un bout de log pour comprendre.

Car ce n'est pas l'ajout des nouvelles sources ou la correction de certains hosters qui auraient tout cassé !

**Comment by jesusisback66** [comment]
@sizanic  autant pour moi j'ai verrifié ma config et zt stream fonctionne mon dns avais bouger " pk je ne sais pas "

**Comment by yodidon** [comment]
sur la question Strmngk (NOUVEAU HOST : vidia)
j'ai ajouté ce hoster qu fonctionne mais (oui toujours mon mais) je récupère que le premier segment , quelqu'un a une idée pour implémenter la valeur "seg-1-v1-a1.ts"pour passer à "seg-2-v1-a1.ts" etc... (je mets le code sur ma branche -3)
merci pour votre aide

**Comment by sizanic** [comment]
@yodidon 
je trouvé ton problème avec vidia.

Crée un nouveau sujet et je te répondrais dedans.
(ici le sujet est "suivi des bugs " pas "nouveau hoster vidia")

**Comment by yodidon** [comment]
@sizanic ok fait merci

**Comment by sizanic** [comment]
@Che-debarras 
J'ai remplacé mon poste avec ton commentaire que tu maintenais à jour.
Tu peux maintenant éditer directement le premier post.

Pour ce sujet :
**Dossiers vide**
- Strmngk (NOUVEAU HOST : vidia)


Tu veux dire que le dossier est vide lorsqu'il n'y a que le hoster vidia, mais c'était valable tant que vidia n'était pas encore disponible. Comme vidia est maintenant dispo, on peut supprimer ce constat ?

**Comment by sizanic** [comment]
@TmpName : 
> Mixdrop reparé, c'est juste que certains sites utilisent la page "embed" et d'autres non, donc le même hoster marche sur certains sites et pas sur d'autres.

Quelqu'un a un exemple de chaque, qu'on puisse développer une solution commune ?

**Comment by Che-debarras** [comment]
> @Che-debarras
> J'ai remplacé mon poste avec ton commentaire que tu maintenais à jour.
> Tu peux maintenant éditer directement le premier post.
> 
> Pour ce sujet :
> **Dossiers vide**
> 
> * Strmngk (NOUVEAU HOST : vidia)
> 
> Tu veux dire que le dossier est vide lorsqu'il n'y a que le hoster vidia, mais c'était valable tant que vidia n'était pas encore disponible. Comme vidia est maintenant dispo, on peut supprimer ce constat ?

Je vais retester ces bugs après cette maj majeur de vstream 0.7.9 et je vous dis quoi poir Vidia, Dood etc..
J'étais un peu pris avec la dernière saison de Suits apparue ce week-end 😉

**Comment by sizanic** [comment]
> J'étais un peu pris avec la dernière saison de Suits apparue ce week-end

Non mais sérieux, quoi ! Y'a des priorités dans la vie, tu nous refais plus jamais ça, on compte sur toi pour vStream :wink: 

-> Il faut créer un nouveau sujet **Suivi des bugs 0.7.9**

**Comment by Che-debarras** [comment]
> > J'étais un peu pris avec la dernière saison de Suits apparue ce week-end
> 
> Non mais sérieux, quoi ! Y'a des priorités dans la vie, tu nous refais plus jamais ça, on compte sur toi pour vStream 
> 
> -> Il faut créer un nouveau sujet **Suivi des bugs 0.7.9**

Ok je vais créer un nouveau sujet , tu as gagné je culpabilise 😥 quoique faut bien tester ces bugs à long terme 😋.
Justement sans vous j'aurais galéré durant ce confinement.

Blague a part, je me demandais a quel frequence ce suivi peut etre fait?
1 fois pas semaine ou mois ou la veille d'une mise a jour majeur pour Master?
Je trie les bugs par hosts est ce idéal ou mieux par Source? Ou les 2.

**Comment by yodidon** [comment]
Je trouve plus pratique d’avoir le souci de hoster sur la source , ça permet de regarder plus vite ou se trouve le problème

**Comment by sizanic** [comment]
Tu veux dire que si un hoster ne fonctionne pas que pour une source, il vaut mieux lister les sources et indiquer le hoster qui ne fonctionne, par exemple : 

**Source KO**
- source1.com (hoster hostream)

Plutôt que par hoster : 

**Hosters KO**
- hostream (Source source1.com)

**Comment by Che-debarras** [comment]
Depuis 0.7.9 
zustrm et strmnk corrigé (doodstrm, mixdrop,vidia corrigé 
Flmstrmvk bcp de lien absent mais HS sur le site mais uqload et autre lien Dustrm et mystram corrigé 
Papstrm aucun lien fonctionnel idem pour kstrming (series) avec erreur de connection en notif

Donc ya vraiment pas mal de chose corriger apart les sources qui s'ouvrent pas ou vide.

Je referais un post  plus complet dans la semaine.

J'ai une petit faveur est ce que kaydo fonctionne pour certains ?

**Comment by sizanic** [comment]
oui, il faut garder une section Host si ça concerne toutes les sources, car dans ce cas c'est bien le host qui un probleme.

Si c'est une source qui utilise mal le host, il faut le mettre au niveau de cette source.


Kaydo ne peut pas fonctionner, le site ne réponds pas : h ttps://hdss. to/

**Comment by Che-debarras** [comment]
> oui, il faut garder une section Host si ça concerne toutes les sources, car dans ce cas c'est bien le host qui un probleme.
> 
> Si c'est une source qui utilise mal le host, il faut le mettre au niveau de cette source.
> 
> Kaydo ne peut pas fonctionner, le site ne réponds pas : h ttps://hdss. to/

Merci c'est ce que je pensais pour les hosts et pour kaydo.
Merci encore pour ton aide et tes avis @sizanic

**Comment by TmpName** [comment]
> 
> 
> @TmpName :
> 
> > Mixdrop reparé, c'est juste que certains sites utilisent la page "embed" et d'autres non, donc le même hoster marche sur certains sites et pas sur d'autres.
> 
> Quelqu'un a un exemple de chaque, qu'on puisse développer une solution commune ?

Ben en fait l'url est du type /e/ pour les video "embed" et tu as par exemple /d/ pour celle dans une page complete.

Si tu fais une recherche avec "/e/" tu vas trouver au moins 2/3 hosts avec ca dans la fonction seturl()

Sinon, vidlox moi de mon coté je laisserais en attente, faut trouver l'astuce dans un gros fichier JS, mais de toute facon je suis pas arrivé a lancer une seule video avec encore.

**Comment by Che-debarras** [comment]
@TmpName 

> mais de toute facon je suis pas arrivé a lancer une seule video avec encore.

Ta pas essayer VIDLOX avec la source et le film que j'ai cité :
 _**K-strmng, film : atlantic rim ressurection**_

**Comment by sizanic** [comment]
Les bugs sont maintenant suivi ici : #2870

**Comment by TmpName** [comment]
@Che-debarras C'est bon vidlox refonctionne,, j'ai les boules de ne pas avoir vu ca plus tot, c'etait vraiment tout con, le code fonctione encore 15 mois apres.

**Comment by sizanic** [comment]
Cet ajout `/8m8p7kane4r1.html` est vraiment quelque chose qui ne va pas bouger pendant des mois ?
Il n'y a pas de moyen de le retrouver en dynamique ?

**Comment by TmpName** [comment]
Faut juste une url, j'ai pensé faire un truc aleatoire, mais quand le mec va regarder les logs il risque de s'apercevoir de quelque chose ^^.

Au pire garder une base potable style vvv.strmenfolie.com et mettre le reste en aleatoire, mais pareil faut pas qu'ils aient l'idee d'aller voir ce qu'est ce site qui leur ramene des visiteurs.
