### ISSUE TITLE
Probleme Zone Telechargement et Tirexo

### ISSUE THREAD

**Issue by Jojo31780** [Kodi-vStream/venom-xbmc-addons#2862]
Bonjour tout d'abord merci pour votre boulot. J'utilise Vstream tout les jours! 
Par contre depuis quelqes jours plus de resultats lors de recherche de sources sur Zone telechargement.  Cela mouline et rien ne se passe ou affichage Aucune Information. 
Sur Tirexo: affichage des films mais quand je vais jusqu'à Sélectionner Uptobox cela mouline mais rien ne se passe! 
Mise a jour 0.7.8...système Amazon fire stick.
Merci....

**Comment by sizanic** [comment]
UpToBox ne fonctionne plus sur aucune source.
Une correction sera disponible dans une mise à jour dans quelques jours.

Je viens de faire une recherche sur ZT et j'ai eu des résultats...
(sous windows et sous Android)

Toujours ce problème ?

**Comment by sizanic** [comment]
Je viens de retester et je n'ai plus rien sur ZT.
Je vais sur le site et je tombe sur un double capcha à base de reconnaissance d'image.
Aie aie aie :(

**Comment by Jojo31780** [comment]
Ah dommage. J'avais utilisé la beta pour retrouver uptostream et au final plus de uptobox plus de Zone telechargement et plus Tirexo! Va falloir chercher d'autre sources. Merci les développeurs. Great work

**Comment by sizanic** [comment]
Tu n'avais pas dit que tu utilisais la beta.
Uptobox et uptostream sont corrigés dans la beta.

**Comment by arzaz** [comment]
voici le nouveau site de ZT
https://www.zone-telechargement.stream/

**Comment by lebigboss** [comment]
@arzaz c'est juste la version stream de ZT

**Comment by Jojo31780** [comment]
J'ai testé la beta et la 0.7.8 et cela ne fonctionne pa. Ni tirexo ni ZT... ni uptobox...

**Comment by sizanic** [comment]
La version stream de ZT peux être une bonne alternative à cause des nouveaux captcha...

**Comment by BENJI97200** [comment]
@Jojo31780 ...slt zt passe pour moi avec vpn ,tirexo ne passe pas

**Comment by tibos93** [comment]
Salut a tous, effectivement ne passe pas pour moi avec vpn et sans vpn ni tirexo ni ZT , en cas je vous donne la force merci pour votre boulot grâce à vous je suis un utilisateur hebdo heureux j'utilise vstream depuis le début.
 A +

**Comment by tibos93** [comment]
pour info connexion impossible https 503 sur tirexo 
A+

**Comment by tibos93** [comment]
@Jojo31780 ton vpn est par d'ou hors UE ? ou pas merci ?

**Comment by sizanic** [comment]
La version Stream de ZoneTelechargement est maintenant disponible dans la Beta !! 😉

**Comment by stanler2659** [comment]
> La version Stream de ZoneTelechargement est maintenant disponible dans la Beta !! 😉

Sauf que les liens fonctionne pas ... sa dit no information en rouge ..

**Comment by BENJI97200** [comment]
Pour moi la bêta bug vstream,erreur consulter le journal......(kodi 18.6 nvidia shield tv)...obligé de désinstaller vstream et réinstaller

**Comment by ludopotte** [comment]
En Effet, ZT ne marche plus vu que Google bloque le site, Tirexo marche pas non plus vu qu'il marche mal sur internet et ZT Stream marche mais il faut avoir un Compte Uptobox et suivre les Instructions pour visionner.

**Comment by lebigboss** [comment]
Merci pour l'ajout de la version stream de ZT. Elle fonctionne très bien, les liens uptobox aussi et la qualité est vraiment bonne en faite. Il y a même des fichiers 4k.
Par contre le ZT ne s'affiche plus du tout, cloudfare bloque encore

**Comment by zebraheart** [comment]
Bonjour, pour ma part en belgique le site est accessible, par contre il est protégé par un captcha de reconnaissance d'objet, ce qui rend le site inutilisable sur kodi 😣

**Comment by sizanic** [comment]
> Merci pour l'ajout de la version stream de ZT. Elle fonctionne très bien

Merci. Il fallait bien faire quelque chose pour ce problème de captcha sur ZT.

> ZT Stream marche mais il faut avoir un Compte Uptobox.

Normalement non. As-tu pris que le fichier de la source ou toute la branche Bêta ?

> Pour moi la bêta bug vstream,erreur consulter le journal

C'est avec la version normale ce problème, pas la bêta. Plus d'info ?

> je profite aussi de ce 1er message pour remercier infiniment tout ceux qui travaillent aux maj et bugs, surtout en cette periode

De rien, c'est notre contribution 😁

**Comment by stanler2659** [comment]
> La version Stream de ZoneTelechargement est maintenant disponible dans la Beta !! 😉

Que veux tu dire par juste l’as tu prit que le fichier de la source ou toute la bêta ? 

Moi j’ai downloader le zip de la bêta du GitHub !

**Comment by sizanic** [comment]
Bien. Mais normalement pas besoin de compte Uptobox dans cette version 🤔

**Comment by stanler2659** [comment]
> Bien. Mais normalement pas besoin de compte Uptobox dans cette version 🤔

Premièrement sur cette version les liens 1080p multi fonctionne pas sa nous indique no information en rouge et certain lien 720p qui affiche le lien qui seraient normalement débridé par real debrid quand je click dessus j’ai un message qui me dit que je doit pair avec l’adresse uptobox .... 

Donc pour ma part ZT stream fonctionne pas du tout tk pour l’instant !

**Comment by lebigboss** [comment]
@stanler2659  Si, les liens 1080p fonctionnent pour certains cas, il y a aussi des liens 2160p pour la série ''Better Call Saul'' par exemple. 
Et si quand tu clique sur un format et qui affiche en rouge ''aucune information'' c'est parce qu'il est plus disponible sur le site de streaming.

Et puis pour certains, il y a aussi ExtremDown qui offre des liens en qualité supérieure. Sinon vous pouvez utiliser l'outil de Vstream le ''hoster direct'' que j'utilise souvent, c'est très simple sur Android.

**Comment by sizanic** [comment]
Tu peux m'en dire sur le hoster direct, comment récupérer le lien (sur vStream ?) Et il faut le ressaisir au clavier ?

**Comment by lebigboss** [comment]
@sizanic Tu va sur le site, tu récupères le lien (Tout ça avec un smartphone ou une tablette) et tu utilise l'application Kore

![Screenshot_20200419-120801](https://user-images.githubusercontent.com/12912677/79685125-78844280-8236-11ea-8f8a-e3d09f86bb94.jpg)
 
Une fois que tu as le lien il te reste plus qu'à le copier coller sur le clavier et faire envoi

![Screenshot_20200419-121116](https://user-images.githubusercontent.com/12912677/79685174-ea5c8c00-8236-11ea-9fda-f347ff5eee9f.jpg)

**Comment by sizanic** [comment]
Merci 
Mais du coup c'est encore plus compliqué que je pensais. (Pas pour moi mais je ne peux pas diffuser cette astuce à ma famille/amis)

**Comment by lebigboss** [comment]
Lolll oui au début c'est compliqué et pas a la porté de tous. Mais c'est une très bonne alternative

**Comment by zebraheart** [comment]
> @sizanic Tu va sur le site, tu récupères le lien (Tout ça avec un smartphone ou une tablette) et tu utilise l'application Kore
> 
> ![Screenshot_20200419-120801](https://user-images.githubusercontent.com/12912677/79685125-78844280-8236-11ea-8f8a-e3d09f86bb94.jpg)
> 
> Une fois que tu as le lien il te reste plus qu'à le copier coller sur le clavier et faire envoi
> 
> ![Screenshot_20200419-121116](https://user-images.githubusercontent.com/12912677/79685174-ea5c8c00-8236-11ea-9fda-f347ff5eee9f.jpg)

Ca marche avec realdebrid ?

**Comment by lelensois** [comment]
Salut comment fait tu pour récupérer le lien sur extrem ?

**Comment by tibos93** [comment]
@stanler2659 Merci pour ta version, je ne comprenais pas pourquoi je récupéré pas le stream de ZT.
Fonctionne nickel pour moi plus que a testé si alldebrid fonctionne et sans vpn!!
Même 1080p
A+

**Comment by tibos93** [comment]
Je vous informe que urlresolver ne fonctionne pas avec la bêta ou alors je ne connais pas la solution y'a t'il une version de urlresolver a installé ?? 

Merci.

A+

**Comment by BENJI97200** [comment]
Slt a tous ,merci pour le boulot que vous faites...
Ine question c est possible d avoir une recherche dans son compte uptobox sur kodi,comme on a sur navigateur ??? Merci

**Comment by ludopotte** [comment]
Pour Régler les Bugs de Zone Telechargement et Tirezo, voici 2 Méthodes si dessous ; 
Méthode 1 : Avoir un Compte Uptobox gratuit ou payant et le paramétrer dans vStream 
en mettant le Mode par Défaut "Passer en Streaming via Uptostream"
Méthode 2 : Désinstaller Kodi et vStream et ensuite tout ré-installer avec mon Patch en option.

**Comment by lelensois** [comment]
Salut la communauté,
Quelqu'un a testé la soluce de Ludopotte
Par avance merci de vos réponses

**Comment by sizanic** [comment]
C'est quoi ton patch ?
La beta qui corrige l'accès à Uptobox ?
Parce que la version officielle 0.7.9 de vStream contient cette correction.

Il suffit donc d'installer la dernière version de vStream pour avoir accès aux liens UpToBox, sans rien d'autre...

**Comment by ludopotte** [comment]
Zone-Annuaire.com s'est retrouvé en maintenance pour des raisons indépendantes de notre volonté.
Inutile de rentrer dans les détails mais sachez que le staff technique est à pied d'oeuvre pour remettre le site sur pied.

Zone Annuaire est maintenant opérationnel à 90% et malheureusement, la page "CAPTCHA" est pour le moment nécessaire pour assurer le fonctionnement du site dans de bonnes conditions.

Nous sommes les premiers désolés de ce désagrément qui a duré trois jours au moins. Nous sommes évidemment conscients que lorsqu'on ne sait pas ce qu'il se passe, l'énervement peut très facilement nous envahir et c'est compréhensible surtout avec les Evènements très difficiles que nous vivons.... partout dans le monde.

Voilà pourquoi, plutôt que de se laisser prendre par ses émotions, autant voir les choses autrement et encourager ceux qui se battent au quotidien, je dis bien tous les jours, pour que le site Z-A perdure aussi longtemps que possible.

Merci pour votre calme en ces moments difficiles, pour votre patience, votre compréhension, .... on en a besoin pour garder VOTRE/NOTRE Z-A hors de l'eau ! ;)

Nous espérons tous un retour à la normal aussi vite que possible. Merci pour votre attention chers utilisateurs(trices) !

**Comment by sizanic** [comment]
Merci pour ces infos @ludopotte 

> la page "CAPTCHA" est pour le moment nécessaire

Cela veut dire qu'elle sera retirée ensuite ?

**Comment by ludopotte** [comment]
Je sais pas du tout @sizanic, ça dépendra de développeurs du Site.

**Comment by sizanic** [comment]
> Inutile de rentrer dans les détails mais sachez que le staff technique est à pied d'oeuvre pour remettre le site sur pied.

Tu avais l'air d'être au courant c'est pour cela que je te demandais.

Le site ne réponds plus, nouvelle maintenance ?

**Comment by mannou78** [comment]
Bonjour tout le monde,

Des nouvelles par rapport a Zone Annuaire  ? Le site est encore non dispo dans VStream, est ce que le probleme est relie au niveau "CAPTCHA" mis en place  ?  Vous pensez que le probleme sera resolu bientot

Encore merci pour le super travail que tout le monde fait !!!!

**Comment by arzaz** [comment]
Bonjour,
Le site ZT est de retour depuis hier sur PC mais pas sur vstream?
Prière de mettre a jour vstream

**Comment by sizanic** [comment]
Prière de revoir ta formule de politesse 😥

**Comment by Arias800** [comment]
Il était revenu, mais ça n'a pas durée longtemps xD
Par contre la protection qui a été mise en place sur le site utilisais un token générer par du js, donc a voir la complexité du système.

**Comment by arzaz** [comment]
Zone Annuaire marche parfaitement en passant le site web sur PC, mais avec vstream rien qui s'affiche?

**Comment by Arias800** [comment]
Comme je l'ai dit dans mon message précédent,le site est hs pour le moment (capture d'écran prise a l'instant) ![image](https://user-images.githubusercontent.com/24809312/81479866-63437800-9226-11ea-8810-b8d76ac1f2f8.png)

**Comment by arzaz** [comment]
Chez moi ce n'est pas le cas j'ai accès direct et sans captcha
![image](https://user-images.githubusercontent.com/9026875/81480458-e3b3aa00-9221-11ea-9cad-95c29c4b0e4c.png)

**Comment by Arias800** [comment]
Ils viennent de le remettre en ligne. @TmpName tu peut jeter un œil a leurs protection, car je n'arrive pas trop a comprendre comme elle marche xD

**Comment by sizanic** [comment]
Ne fonctionne pas chez moi non plus.
J'ai un spinner qui tourne en boucle, la page se recharge en boucle.
Je n'arrive jamais sur le site.
En utilisant l'adresse wvv comme sur l'image.

**Comment by sizanic** [comment]
Et maintenant le beau captcha sur ZT-Stream aussi !

= blocage vStream :((

**Comment by TmpName** [comment]
Pareil pr moi ^^
Captcha, bon celui la je crois qu'il y a une api pour le contourner si on crée un compte je sais plus ou.
Mais reste a savoir si il va rester
On est que 2 avec le captcha ?

**Comment by TmpName** [comment]
Ils ont mit des protections venant de stormwall.pro a base de recpatcha invisible.

**Comment by Arias800** [comment]
C'est "marrant" parce que hier soir c'était pas le même système que stormwall proposait (c'était un token a envoyer en tant que cookie) xD

**Comment by TmpName** [comment]
Suffit d'attendre, dans 5 jours ca aura changé.

**Comment by tibos93** [comment]
Je passe actuellement par xtrem-down pour le moment fonctionne très bien. et aucun pb avec le resolver.

**Comment by arzaz** [comment]
@TmpName 
Peut-on s'attendre a une mise a jour aujourd'hui de ZT?

**Comment by TmpName** [comment]
@Arias800 a corrigé la protection CF, donc c'est deja un debut d'amelioration, mais perso je touche rarement a cette source, sinon j'en dors pas la nuit.

**Comment by TmpName** [comment]
Y en a un qui pense que ca vaille le coup de bypasser le code de stormwall ?

**Comment by sizanic** [comment]
Ca dépend.

C'est quoi le "code de stromwall" ?
:laughing: 

Jamais entendu parler.

**Comment by Arias800** [comment]
C'est ça xD https://static.stormwall.pro/jsav1.3.js
Ça dépends si le code est lourd ou pas, car visiblement zt est partie pour conserver cette protection pendant un moment. Mais si le code est lourd ca ne vaut pas le coup pour un seul site.

**Comment by ludopotte** [comment]
Est-ce que ZT va être corriger dans vStream ou disparaître de vStream ainsi que ZT Stream ?

**Comment by TmpName** [comment]
Ben j'ai jete un oeuil, le code est basique.
Je regarde plus en profondeur, mais je vais pas y passer des heures pr que ce soit changé dans 15 jours ...

**Comment by TmpName** [comment]
Bon j'ai commencé a nettoyer et ca al'air faisable, surtout si le code ne change pas

J'en suis la https://hastebin.com/ipexilamix.xml

**Comment by sizanic** [comment]
Si ça pouvait être dans la maj qui se prépare ce serait bien...

**Comment by TmpName** [comment]
Nouvelle version https://hastebin.com/uyebuqexiv.xml

Il n y a plus que 3 fonctions, tout le reste c'est du vent

**Comment by Arias800** [comment]
Faut vraiment que je m'entraine a faire ce genre de chose xD

**Comment by TmpName** [comment]
Dernier essais pour ce soir, plus que 2 fonctions https://hastebin.com/afoqutuqor.xml

**Comment by TmpName** [comment]
Et la version python https://justpaste.me/eLic

En esperant que le code n'est pas changé.
