### ISSUE TITLE
Hoster HLSplay

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2863]
Du coup depuis le lien, je trouve bien le mp4 et le lien final.
![lien](https://user-images.githubusercontent.com/26149640/79669328-120e0e80-81bb-11ea-985d-0d057f99829f.PNG)
on retrouve bien le md5 et le expire que termine notre url:
![md5](https://user-images.githubusercontent.com/26149640/79669366-4e416f00-81bb-11ea-813c-68bd33690640.PNG)
mais entre le lien de départ et le lien final je ne fais pas le lien.
Je sais c'est toujours les mêmes questions

**Comment by razorex** [comment]
si je retrouve cette input
`<input type="hidden" name="_csrf" value="rlK67yic-CSHQjgG_1wMPiSZFmUuuXxXo1-s">`
et en la remontant je retrouve ceci

`
  | url:'/v1/API/View-Counter',
  | method:'POST',
  | data:{file_id:'2045697',
  | hash_id:'m6UipOTAuMTI1LjI0OS4xNjY=dXWL3ryI0R',
  | referer:document.referrer,
  | file_owner:'7368',
  | _token:the_token,

`

**Comment by TmpName** [comment]
Tu as testé en bloquant recapaptcha ? (je bloque www.google.com)
Je pense que ces liens sont protgegé, moi j'ai pas pu obtenir ton lien.

**Comment by razorex** [comment]
Ah oui j'ai vu du `grecaptcha.execute('6Lc90MkUAAAAAOrqIJqt4iXY_fkXb7j3zwgRGtUI', {action: 'secure_url'}).then(function(token)`
mais non je ne l'ai pas bloqué.

**Comment by TmpName** [comment]
Tu connais le fichier hotst ? Sinon il y a un addon pour faire ca a la volée.
Tu rajoutes simplement www.google.com a la liste pour les tests, et le site sera bloqué.

Si j'ai raison la video ne marchera pas (effaces les cookies au cas ou).

Apres ca peut venir du site, j'ai de gros probleme avec pas mal de site en ce moment. j'ai l'impression que le confinement defonce des serveurs.

**Comment by TmpName** [comment]
C'es toujours d'actualité ?
