### ISSUE TITLE
nouvel hoster vidia

### ISSUE THREAD

**Issue by yodidon** [Kodi-vStream/venom-xbmc-addons#2866]
ur la question Strmngk (NOUVEAU HOST : vidia)
j'ai ajouté ce hoster qu fonctionne mais (oui toujours mon mais) je récupère que le premier segment , quelqu'un a une idée pour implémenter la valeur "seg-1-v1-a1.ts"pour passer à "seg-2-v1-a1.ts" etc... (je mets le code sur ma branche -3)
merci pour votre aide

**Comment by sizanic** [comment]
Peux-tu aussi mettre "vidia" dans le titre, on doit savoir de quoi ça parle sans entrer dedans.

Un fichier .m3u est fichier qui donne des bouts de fichier .ts.
C'est le lecteur vidéo qui va s'occuper d'assembler ces bouts de fichier.
Tu ne dois pas t'en occuper.

Tu dois fournir au lecteur vidéo un fichier m3u.

Dans ton cas, récupère le fichier master.m3u et tu verras qu'il fait référence à d'autres fichiers m3u : 

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=542336,RESOLUTION=720x404,FRAME-RATE=25.000,CODECS="avc1.64001e,mp4a.40.2"
https://root.filescdn.co/hls/dcpxkmgjtzu4iw4yi4gjc6p76l6fjbxknni5r4k4nq3ccdumyxgcu2qv7z4a/index-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=45202,RESOLUTION=720x404,CODECS="avc1.64001e",
URI="https://root.filescdn.co/hls/dcpxkmgjtzu4iw4yi4gjc6p76l6fjbxknni5r4k4nq3ccdumyxgcu2qv7z4a/iframes-v1-a1.m3u8"

```


C'est le premier qui nous intéresse, celui qui est noté "STREAM".
Si tu télécharge ce fichier "index-v1-a1.m3u8" tu retrouvera tes bouts de fichiers au format .ts.

```
#EXTM3U
#EXT-X-TARGETDURATION:20
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:20.000,
seg-1-v1-a1.ts
#EXTINF:20.000,
seg-2-v1-a1.ts
#EXTINF:20.000,
seg-3-v1-a1.ts
...
```
On voit que c'est des bouts de fichier de 20 secondes.

Mais comme je te l'ai dit au début, ce n'est pas les .ts qu'il faut récupérer, mais le fichier m3u qui contient la liste, donc => index-v1-a1.m3u8

**Méthode crade**
tu changes ta ligne 
`            api_call = aResult[1][0].replace(',','').replace('master.m3u8','seg-1-v1-a1.ts')`
par
`            api_call = aResult[1][0].replace(',','').replace('master.m3u8','index-v1-a1.m3u8')`

Mais je n'ai testé qu'avec un seul fichier et ce n'est pas sûre que cette règle de nommage soit toujours respectée.

**Méthode propre**
petite regex dans le fichier master pour trouver l'url STREAM du bon fichier m3u.

**Comment by yodidon** [comment]
merci @sizanic  j'etais arrivé jusqu'a "index- v1-a1" mais je laissais l'extention ts , il faut que je soit plus figilant ... merci encore
