### ISSUE TITLE
kodi + iso bluray 3d ?

### ISSUE THREAD

**Issue by thorsten68** [Kodi-vStream/venom-xbmc-addons#2868]
quelqu'un sait comment lire des fichiers iso 3d ?
je suis sur shield, pas de soucis avec les mkv 3d mais les iso j'y arrive pas
si quelqu'un a a un tuyau...
Merci pour le taf !

**Comment by Che-debarras** [comment]
J'ai lu quelque part qu'il faut installer un build de kodi pour cette option car kodi ne lis pas les iso 3d sinon il me semble que vlc lis ces iso 3d.
Ça n'aide peut-être pas mais google sera mieux t'aider , des sites en anglais t'aideront et d'après ce que j'ai aperçu c'est possible sur rpi et Windows mais pas android
