### ISSUE TITLE
Nouvelle source hds-stream

### ISSUE THREAD

**Issue by yodidon** [Kodi-vStream/venom-xbmc-addons#2869]
Vous avez une idée quand l'option afficher code source est grisé ?
Merci

**Comment by sizanic** [comment]
Sous chrome, tu peux mettre `view-source:` devant ton url.

**Comment by yodidon** [comment]
ça veut rien savoir... impossible de récupérer ce code c'est peut être impossible en fait

**Comment by sizanic** [comment]
si ça te retourne la même page, tu serais  pas déjà sur une page source ?
donne l'url pour voir.

**Comment by yodidon** [comment]
Non juste impossible d’afficher , c’est sur un .mp4

**Comment by sizanic** [comment]
pas compris, t'essaye vraiment d'afficher le contenu d'une url qui se termine par .mp4 ???

**Comment by yodidon** [comment]
Oui 😞

**Comment by sizanic** [comment]
Colle ton url dans VLC et tu verras le contenu.

**Comment by yodidon** [comment]
En faite c’est la dernière url après le clique sur un hoster j’essaie de remonter comme tu me l’a conseillé comme tu peux le voir je suis bien nul...👎

**Comment by sizanic** [comment]
lorsque tu es sur cette url, c'est pas la source qu'il faut afficher mais le header. C'est là que tu retrouve l'url précedente, dans le parametre referer.

Exemple ici avec cette page : 
![image](https://user-images.githubusercontent.com/47307622/79807137-57bd0980-836a-11ea-9090-1be1dab35431.png)

**Comment by yodidon** [comment]
Oui merci @sizanic

**Comment by TmpName** [comment]
Oui le lien mp4 est un fichier video, pas une page html, donc pas de code.

**Comment by yodidon** [comment]
J’avoue que si j’avais juste réfléchi 2 secondes mais bon .....

**Comment by sizanic** [comment]
Mais du coup t'avance maintenant ?

**Comment by yodidon** [comment]
Oui je crois , j’ais encore quelque soucis avec les hoster mais j’ai bien avancé, rien de tel qu’une bonne nuit pour retrouver un esprit plus logique ...

**Comment by yodidon** [comment]
J’essaie de comprendre ce qu’est le « provisonal header «

**Comment by sizanic** [comment]
Je ne sais pas et je ne crois pas qu'on s'en soit déjà servi.

Tu pourras changer le titre de cette issue, avec le nom du host ou de la source sur laquelle tu travailles, ce sera plus facile pour nous de comprendre le contexte si on veut t'aider. Merci.

**Comment by yodidon** [comment]
Oui pas sûr que ce soit nécessaire, là je bataille avec wp-admin/admin-Ajax

**Comment by Arias800** [comment]
J'avais déjà utiliser hds stream pour remplacer Kaydo avant de changer pour hdss to :  https://github.com/Kodi-vStream/venom-xbmc-addons/blob/def4e4b408817c638e34e5d592257cdc3a627819/plugin.video.vstream/resources/sites/kaydo_ws.py

**Comment by yodidon** [comment]
C’est ce qui me semblait, alors peut-être que je fais ça pour rien 😞

**Comment by Arias800** [comment]
Non si tu pense qu'il vaut le coup tu peu le mettre, comme nouvelle source vu que hdss marche bien. J'avais arrêter de l'utiliser car ils s'avaient arrêter de le mettre a jour, donc il était devenu inutile.

**Comment by yodidon** [comment]
Ça fait 4-5 jours que je le regarde et il semble être à jours 
Maintenant je suis loin de le proposer mais j’avance à petit pas

**Comment by sizanic** [comment]
> C’est ce qui me semblait, alors peut-être que je fais ça pour rien

C'est exactement pour ça qu'il faut donner du contexte à tes demandes.


C'est exactement sur quelle url que tu travailles ?

Car de mon côté j'ai également cherché un remplaçant de Kaydo avec une adresse hdss.

Et j'en trouve trop et je pense qu'aucun n'est un clone qui permet de changer juste l'adresse sans changer le code : 

h ttps://ww4.hds-stream.to/
h ttps://wwv.hds-streaming.la/
h ttps://tv.hds-stream.com/
h ttps://www3.hdss.pro/
h ttps://hds.mobi/hdss-to-v1/
h ttps://wwv.hdssgratuit.co/
h ttps://w8w.hds-streaming.tv/
h ttps://ww4.hds-streamingvf.com/
h ttps://www.hds.lc/

**Comment by yodidon** [comment]
c'est ww4.hds-str_eam.to
et j'arrive jusqu'a lancer les films sur vstream mais  mon affichage de showlink est horrible ....

**Comment by sizanic** [comment]
Fait tourner
-> patch-3

**Comment by yodidon** [comment]
c'est vraiment du working progress la ....

**Comment by yodidon** [comment]
Il y chrysal qui travail dessus et a apporté des éléments pour la recherche mais pas encore inclus dans le code sur patch-3

**Comment by yodidon** [comment]
j'ai essayé un truc un peut bancal pour l'affichage mais on dirait que ça marche ...

**Comment by yodidon** [comment]
oula j'avais pas vu toutes les affiche sont décalé zut

**Comment by sizanic** [comment]
T'en est où de cette source ?
Je peux la tester, ou elle est toujours en "Work In Progress" ?

**Comment by yodidon** [comment]
> T'en est où de cette source ?
> Je peux la tester, ou elle est toujours en "Work In Progress" ?

Tu peux tester sur films dernière ajout le reste je m’y suis pas collé je voulais être sûr que ça fonctionne avant de mettre toute les fonctions

**Comment by sizanic** [comment]
- 1er test :
Je tombe sur une protection CloudFlare.
J'ai du aller sur le site pour passer la protection avant de retourner sur vStream pour aller plus loin.


Question : 
comment as-tu déterminé cette liste de host, de façon empirique ?
```
            if '1' in dNum :
                sHost = 'Frenchvid'
            elif '2' in dNum :
                sHost = 'MyStream'
            elif '3' in dNum:
                sHost = 'UqLoad' 
```

En règle générale, si on ne sait pas, on ne met pas (car ça peut changer).

**Comment by yodidon** [comment]
Oui c’était du bricolage pour évider l’es lien 1 2 3 etc et j’ai essayer une 6 films au hasard  et c’était constant, et puis je le suis dis que c’était pas trop grave je pourrais changer...

**Comment by yodidon** [comment]
Pour cloudfare je ne’ais pas rencontrer ce soucis

**Comment by sizanic** [comment]
L'histoire des numérotations des serveurs, ça m'a rappeler la source zuStream.
C'est ce qu'on a fait, on a mis des numéros.

En fait les sites sont tellement proches, que j'ai modifié la source zuStream et j'ai mis l'URL hds dans URL_MAIN.

Essayes et tu verras ...

(j'ai souvent des erreurs 503 dû à la protection)

**Comment by yodidon** [comment]
je me suis plutot inspirer de streammavie pour les hoster

**Comment by sizanic** [comment]
T'as essayé de mettre 
`URL_MAIN = h ttps://ww4.hds-stream.to/`
dans la source zuStream (à la place de zustream.biz) et de parcourir zuStream dans Kodi ...

**Comment by yodidon** [comment]
Non je vais regarder

**Comment by yodidon** [comment]
avec zustream j'ai une erreur 503

**Comment by yodidon** [comment]
bon je crois qu'il faut que je me rende a l’évidence et que je reste sur du basique, verifier si l'année s'affiche le poster ou la qualité, voir si l'url est toujours ok, et laisser le reste au plus compétant , et je n'y vois pas la un sous travail mais à chacun ses compétences

**Comment by sizanic** [comment]
Avance un maximum, on terminera.

**Comment by yodidon** [comment]
@sizanic l'erreur 503 semble corrigé, je vais donc le terminé complètement avant de passer à autre chose.

**Comment by sizanic** [comment]
Sans erreur 503, essaye comme je t'ai dis d'utiliser le code zuStream.

**Comment by Che-debarras** [comment]
Hds-strm fonctionne mais pas les hosts vidoza uqload et ya un dossier host "Unknown....ww6" dans certain cas comme la série Bodyguard

**Comment by yodidon** [comment]
Oui pour vidoza par contre Uqload fonctionne chez moi , je regarderais pour le ww6 ça doit être le lien direct je corrigerais
