### ISSUE TITLE
Filtrage des résultats - Masquer les sources vides

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2871]
J'ai mis en place dans la beta un filtrage lors de la recherche globale.

Seules les sources qui retournent des résultats sont affichées.
Les sources qui ne retournent pas de résultat ne sont pas affichées.

=> Vous m'en direz des nouvelles :)

L'idée avait été soumise ici et tout le monde avait l'air d'accord : #1637

**Comment by sizanic** [comment]
On verra s'il y a des retours avec l'utilisation de la version 0.8.0 ...

**Comment by yodidon** [comment]
@sizanic  je trouve ça très bien , il reste encore des sites dont la recherche est super grossière, j’avais déjà corrigé quelque un mais là il y en a un particulièrement qui retourne des résultats trop inutiles (télécharger -stremng), je vais essayer de regarder aujourd’hui mais si c’est lier au site je pense qu’on peut le retirer de la recherche général
