### ISSUE TITLE
Favori dans vstream

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2872]
Je met ça dans autre car je sais pas si c'est un bug ou une idée mais je ne vois pas de catégorie favoris dans vstream

Le marque page lui c'est just un titre pour qu'il aille cherche dans tous les sources
Libraire il ne s'ouvre pas ce qui explique pourquoi je parle de bug.
Mais l'idée est peut on importer les favoris de Kodi dans vstream si oui comment , si non peut on ajouter cette fonction?

Sur kodi les favoris sont des vignettes et dure a gérer alors que si dans vstream c'est dans une catégorie on pourra les afficher différemment et peut-être les classer en fonction de film serie ou animé pour s'y retrouver.

Donc désolé si cette fonction existe déjà mais je la vois pas sur vstream et librairie refuse de s'ouvrir apres avoir mis un titre en librairie.

Merci

**Comment by yodidon** [comment]
pour avoir essayer , la fonction favoris et lié a kodi, après plusieurs essais j'ai abandonné, mais je trouve l'idée plutôt intéressante

**Comment by Che-debarras** [comment]
> pour avoir essayer , la fonction favoris et lié a kodi, après plusieurs essais j'ai abandonné, mais je trouve l'idée plutôt intéressante

Ya des addon qui le font ? Il suffit pas juste de leur piquer leur script lol?

**Comment by sizanic** [comment]
> Le marque page lui c'est juste un titre pour qu'il aille cherche dans tous les sources

Je ne sais pas comment tu as testé les marques-pages de vStream mais pas du tout.
Sauf si tu as mis en marque-page un film venant de la source TheMovieDb car c'est ce que fait cette source (une recherche globale). Mais sinon, le marque page garde le lien du film dans le source où tu te trouves.

>dure a gérer alors que si dans vstream c'est dans une catégorie on pourra les afficher différemment et peut-être les classer en fonction de film serie ou animé pour s'y retrouver

Eh bien c'est ce que fait le marque-pages, il les trie par catégorie.


> Donc désolé si cette fonction existe déjà 

Ou alors j'ai pas compris ce que tu veux faire mais ça existe déjà.

**Comment by Che-debarras** [comment]
Tu as tous compris mais pour les series il ne garde que le nom pour une recherche globale mais je voudrais qu'il garde le nom et sa source pour le garder en favori comme celui de kodi en page d'accueil sauf quil serai dans une categorie dans vstream.

**Comment by sizanic** [comment]
Non, je comprends pas pourquoi tu parles de recherche globale.
Si je mets dans les marques-page la saison d'une série, lorsque j'ouvre ce marque-page, je retrouve les épisodes de ma série. Le marque-page n'est pas juste un nom qui permet de relancer une recherche globale.
A aucun moment la recherche n'est lancée dans la gestion des marques-pages.

Quand tu ajoutes un lien dans marque-pages, tu le retrouve dans la catégorie Film ou Séries par le menu "Marque-page" à la racine de Vstream.

Tu ajoutes ce dossier Marque-page dans tes favoris Kodi et tu l'auras directement en page d'accueil de Kodi.

**Comment by Che-debarras** [comment]
C'est bizarre j'ai mis un film dans marque page et quand je le clique il me fait une recherche

**Comment by sizanic** [comment]
Soit tu as ajouté ce lien depuis la source TheMovieDb, soit depuis le dossier "Historique" de vStream. Le dossier "Historique" est l'historique des recherches et permet de relancer une recherche.

Car si le lien n'est plus valide, tu tomberas sur une erreur ou un message "Aucune information".

Il est possible d'importer, un  par un, un marque-page de vStream dans les favoris de Kodi (menu contextuel lorsque tu es dans le dossier marque-page).

Mais le contraire n'est pas possible (Favoris -> Marque-page).

Ce que tu peux faire c'est d'ajouter le dossier "marque-page " (menu contextuel sur le dossier lui-même) dans les favoris. Tu auras un accès aux marques-pages depuis les favoris en un clic.

**Comment by Che-debarras** [comment]
Visiblement ce n'est pas possible (favoris->marque page) 
Merci pour ton aide. Donc je clos ce sujet.

**Comment by sizanic** [comment]
@Che-debarras 
J'ai eu le même fonctionnement que tu décris, ça ma lancé une recherche alors que je venais de mettre un marque-page depuis un lien hoster.

Je vais regarder ça de plus prêt ...

**Comment by sizanic** [comment]
J'ai pas réussi à le reproduire ...

**Comment by TmpName** [comment]
La drogue, l'alcool, les femmes, ...
