### ISSUE TITLE
Clef token Alldebrid

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#2875]
Bonjour à tous 
Je cherche la clef token de mon compte alldebrid, elle n y est pas au niveau de Account informations .
Une petite idée ?
Merci

**Comment by Arias800** [comment]
Elle ce trouve sur cette page : https://alldebrid.fr/apikeys/

**Comment by falciatrice10** [comment]
Il faut la creer ? Je ne la trouve pas sur cette page : https://alldebrid.fr/apikeys/

**Comment by Arias800** [comment]
Comme tu veux, si tu veut la créer tu peut. Mais normalement dans la deuxieme ligne du tableau du bas il y en a une qui sert a Alldebrid, et logiquement elle fonctionne.

**Comment by falciatrice10** [comment]
pwa-2.0.1 ?????

**Comment by Arias800** [comment]
Tu prends la dernière qui se trouve dans le dernier tableau.
![image](https://user-images.githubusercontent.com/24809312/80231140-3ce0e280-8653-11ea-9d93-2afa5dc47b66.png)

**Comment by falciatrice10** [comment]
Je prends donc celle-ci (service) ?
[URL=https://www.directupload.net][IMG]https://s12.directupload.net/images/200424/ltnheany.jpg[/IMG][/URL]

**Comment by Arias800** [comment]
Oui, en tout cas j'ai utiliser celle la pour mes teste et ca fonctionnais.

**Comment by falciatrice10** [comment]
![20200424_171011](https://user-images.githubusercontent.com/42334843/80233560-8f6bd000-864e-11ea-9415-1b53c1663989.jpg)

**Comment by BENJI97200** [comment]
@Arias800 ,slt ,tu peux me dire comment réinitialiser le token stp sur extrem download? Il se trouve où ds le stockage interne?

**Comment by Arias800** [comment]
Ce que tu peut faire c'est dans settings.xml de modifier la ligne:
 `<setting id="token_alldebrid" type="text" label="Token Alldebrid" default="" visible="false"/>`
par:
 `<setting id="token_alldebrid" type="text" label="Token Alldebrid" default="" visible="true"/>`
Comme ca l'option sera visible dans les paramètres et tu pourra donc modifier le token comme tu le souhaite.

**Comment by BENJI97200** [comment]
@Arias800 ....Slt ...et merci pour ton aide ,j ai fais comme tu as dis et ça fonctionne....Merciiii

**Comment by BENJI97200** [comment]
@Arias800 ....je ne comprend pas ,je l ai fait sur ma xiaomi box ,ça a fonctionné et ne fonctionne pas sur ma shield tv....désolé de t embeter
