### ISSUE TITLE
Pas de sous-titre avec ZT-Stream

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2877]
_Originally posted by @Torped00 in https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2870#issuecomment-619123832_

Bonjour,
J'ai relevé un truc sur la source ztstream, je suis premium uptobox, ça ça fonctionne il reconnaît mon compte. Le problème est quand je choisi de regarder des séries VOSTFR EN 720, il n'y a pas moyen d'activer les sous-titres comme avant dans la source ztelech***, je dois choisir la version webrip pour avoir les sous titres incrustés dans la vidéo mais la qualité est moindre. Vous pensez que ça se corrige ?

Merci pour votre taf les gars en tout ça.

**Comment by TmpName** [comment]
Ha oui mince ca a ete desactivé lors du  changement du hoster.

**Comment by lebigboss** [comment]
Sur quel programme tu n'as pas de sous titre ? Parce que j'ai mis un truc au hasard et ça fonctionne

**Comment by Torped00** [comment]
Quand il s'agit de mettre des séries en VOSTFR en qualité 720 minimum. Je ne parle pas des sous-titre incrustés dans la vidéo mais bien ceux qu'on gère via Kodi.

**Comment by lebigboss** [comment]
Ok je comprends pas, parce que sur ZT en 720p ça propose soit du french ou du VOST, jamais du multi

**Comment by Torped00** [comment]
Je t'invites à tester le cas.
Source ztstream 
Section series VOSTFR 720
Choisi une série que tu veux voir en qualité 720.ca sera forcément en anglais. Normalement, il est possible de télécharger la piste de sous-titre en même tps et là c'est. Plus le cas.

**Comment by TmpName** [comment]
Ben justement, avec up2stream je comprend ils separent la video des sous titres, quand tu vas sur le site tu peux choisir.

Mais up2box, ...... c'est juste des fichier a DL.

**Comment by Torped00** [comment]
Salut,
On parle de la même chose, j'ai bien dis source ztstream donc ce sont des liens up2stream. Sur le site lorsqu'en tu lancés une vidéo VOSTFR en qualité autre que hdrip ou webrip il n'y a pas les sous titre incrustés il faut sélectionner la piste de sous titres et l'activer. Cette manipulation qui était possible sur la source zone téléchar* dans vstream ne l'est pas dans ztstream, on peut pas les activer.
Je suis assez clair ?

**Comment by TmpName** [comment]
Ha mince j'avais pas compris.
Par contre pas de bol, j'ai voulu tester et a chaque fois les ST etaient dans la video, now plus de credit.

Tu aurais un titre de film ? ou mieux le lien up2strm ?

**Comment by Torped00** [comment]
Merci pour ton aide. Mais il s'agit de série VOSTFR plutôt. Je te donne un lien en exemple quand ZT fonctionnera de nouveau. Car la g erreur 524 ou 502 sur cloud fare. Je sais pas si c que chez moi... J'ai tenté avec et sans VPN c pareil.

**Comment by Torped00** [comment]
Ca refonctionne,

Voila un épisode de Harley Queen en qualité HD (Tu peux choisir de 360 à 720)
https://www.zone-telechargement.stream/70394-telecharger-harley-quinn-saison-2-saison-2-hd-720p-vostfr.html
https://zt-protect.net/telecharger/bFZBZmxFdW1CeFZKYTNPMlBiRUxKaXA1SGMrOW9mWW9RQUR6RG1GMzVnR2RoMjVDemZndXFmMFUvSGpubmw5Qw==%7D?_token=xCilGZei5icEUdRmoVm1xWwP8CDi6Tw9OBx32XwH
Comme tu peux voir on peut sélectionner une piste de ST indépendante pour l'ajouter à la vidéo:
![image](https://user-images.githubusercontent.com/37884505/80915988-19eeb680-8d56-11ea-86ee-1de3b6de47e6.png)
Il etait aussi possible d'activer les ST automatiquement comme le preconise la configuration de VSTREAM
La meme video en WEBRIP les ST sont incrustés mais la qualité est moins bonne:
https://www.zone-telechargement.stream/70399-telecharger-harley-quinn-saison-2-saison-2-webrip-vostfr.html
https://zt-protect.net/telecharger/bFZBZmxFdW1CeFZKYTNPMlBiRUxKcmMxUnBwZ3h5THFnbXVIR25nTTJTNkhNKzlZTWlvY3BRdTBJYWNwV1BHMg==%7D?_token=xCilGZei5icEUdRmoVm1xWwP8CDi6Tw9OBx32XwH
Et comme tu vois il n'y a pas de bouton pour "incruster" les sous titres:
![image](https://user-images.githubusercontent.com/37884505/80916122-1b6cae80-8d57-11ea-993d-3d1ecc3319a9.png)

J'espere etre suffisamment clair

**Comment by TmpName** [comment]
Je viens de le reactiver pour les premium, tu as le nouveau code a tester ici https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/uptostream.py

Normallement ca remarche comme avant, mais j'ai pas pu tester.

**Comment by TmpName** [comment]
Alors je viens de le reactiver pour les premium, ca devrait remarcher comme avant, mais pas pu tester.

Pr contre avant ca ne se lancait que quand il y avait VOSTFR dans le titre, maintenant c'est a chaque fois que des fichier sous titre se trouvent dans la page.

**Comment by Torped00** [comment]
Re,
Si je comprend bien, je dois juste modifier ce bout de code dans le hoster ?
Bon de toute façon la source est dead en ce moment, test sur mon tel en 4g, sur Android et sur Windows...

**Comment by sizanic** [comment]
Ne modifie rien toi-même dans les fichiers.
Installe la Beta à partir d'un zip.
