### ISSUE TITLE
Poster films on Kepliz

### ISSUE THREAD

**Issue by saidma** [Kodi-vStream/venom-xbmc-addons#2878]
![15877778297018129000892812598786](https://user-images.githubusercontent.com/18542801/80267978-375fb880-86a4-11ea-8050-411461266088.jpg)
La source Kepliz n'a pas de couvertures de films
Vstream/Sources/Kepliz

**Comment by yodidon** [comment]
Elles sont longues a charger

**Comment by gratoQ** [comment]
mais non c'est juste qu'il n'y en a pas sur le site lui même.

**Comment by razorex** [comment]
oui pas présente sur la première page, il faut sélectionner le film dans la source pour le voir.

**Comment by saidma** [comment]
Mais, reste un bug

**Comment by saidma** [comment]
> oui pas présente sur la première page, il faut sélectionner le film dans la source pour le voir.

Mais, reste un bug

**Comment by TmpName** [comment]
Qu'elles n y soient pas sur la premiere page ?

**Comment by razorex** [comment]
@saidma c'est le site qui est structuré ainsi, nous on ne récupère que les infos disponible, le poster n'est disponible qu’après sélection du film.
exemple
![Capture](https://user-images.githubusercontent.com/26149640/80306486-ec3cc700-87c3-11ea-87cf-119fe79ef58b.PNG)

**Comment by saidma** [comment]
> @saidma c'est le site qui est structuré ainsi, nous on ne récupère que les infos disponible, le poster n'est disponible qu’après sélection du film.
> exemple
> ![Capture](https://user-images.githubusercontent.com/26149640/80306486-ec3cc700-87c3-11ea-87cf-119fe79ef58b.PNG)

Ok. Pas de soucis donc. Merci beaucoup pour la contribution!
