### ISSUE TITLE
Streamingk HS

### ISSUE THREAD

**Issue by forzakeb** [Kodi-vStream/venom-xbmc-addons#2880]
Bonjour à tous,
depuis quelques jours tous les raccourcis de ce site renvoient une erreur 503 pour chaque catégorie.
Le site lui semble ok.

Bon courage

**Comment by Che-debarras** [comment]
Ya un post déjà concernant les bugs #2870 
Si tu as un bug il faut le signaler sur ce sujet
Mais en lisant ce sujet tu verras qu'il est corrigé dans la bêta 
Donc faut patienter une maj ou installer la maj beta manuellement 
Tous est  écrit sur #2870

**Comment by forzakeb** [comment]
Merci de cette réponse,
désolé pour ce rapport, je serrai plus vigilant la prochaine fois.
