### ISSUE TITLE
Liens vides extrem down

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2883]
Bonjour ,
Je suis sous kodi Leia 18.6 sur Nvidia Shield.
J’ai installé la toute dernière beta de vStream.
Je possède un compte alldebrid puis j’ai inscrit mon Token (depuis longtemps) tel que demandé par la source Exteme Down. Par contre, tous les Liens sont vides, peu importe le hoster choisi.
Est-ce un bug dont vous êtes au fait?

Je n’utilise pas extrem down de façon régulière mais la dernière fois que je l’ai fait ça fonctionnait bien 

Merci a vous pour votre excellent travail

**Comment by sizanic** [comment]
Les bugs dont nous sommes au fait sont référencés ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2870

Vérifie que les hoster que tu essaies ne sont pas corrigés dans la liste du premier post.
