### ISSUE TITLE
erreur streamingk

### ISSUE THREAD

**Issue by fpodev** [Kodi-vStream/venom-xbmc-addons#2884]
**Décrivez le bug**
Bonjour, quand je selectionne cette source elle ne s'ouvre pas. Log ci-dessous

**Votre system**
 - OS: [Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [18.6]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
![IMG_20200426_134901](https://user-images.githubusercontent.com/9036717/80306751-6caff780-87c5-11ea-8531-f88ca3e17219.jpg)

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Che-debarras** [comment]
#2870

**Comment by sizanic** [comment]
pas mieux 😉

**Comment by TmpName** [comment]
En tout cas, j'appreci le coup des logs ^^.
A defaut de pouvoir faire passer le fichier, la capture avec le telephone est tres bien.

**Comment by fpodev** [comment]
On fait ce que l'on peut.  C'était le moins chiant à faire. Car je suis un peut une faignasse quand même 😊

**Comment by fpodev** [comment]
Au passage mamcin ne fonctionne plus aussi. Voilà. 😛

**Comment by TmpName** [comment]
Suite https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2894
