### ISSUE TITLE
changement de URL Free téléchargement

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2886]
Bonjours pourriez-vous aller changer l'URL dans free téléchargement 

 URL a changer voir la photo ci jointe a la ligne 21
![Sans titre](https://user-images.githubusercontent.com/40530593/80312336-b6dbad80-87b2-11ea-88c2-5f1bffc87aff.png)
 et faire la correction merci

**Comment by LeGmask** [comment]
Fait une pr 😉

**Comment by KodiTopQuebec** [comment]
![Sans titre](https://user-images.githubusercontent.com/40530593/80397877-d6dba180-8884-11ea-8a60-afe90fcc4f81.png)
  
ici c est la nouvelle adresse de free téléchargement , j ai vu que vous avez jouer dessus qui est sur la beta et depuis cette modification free ne fonctionne plus a partir de vstream , pourquoi ne pas changer l'URL avec la nouvelle adresse ? je vous envoie une photo que j ai mis pour démontrer la nouvelle adresse , merci

**Comment by sizanic** [comment]
@KodiTopQuebec 

J'ai testé cette nouvelle adresse dans vStream.
Son système de captcha avec saisie d'un code au clavier n'est pas top.
Et pratiquement tous les liens sont morts.
=> Tu as réussi à voir un film ?

Le site n'est pas utilisable directement car les liens de téléchargements/visionnage ne sont visibles sur la page.
Du coup il ne risque pas de perdurer encore longtemps.

Qu'apporte vraiment ce site de plus que ceux qu'on propose déjà ?
(par rapport à FilmStreamVK ou ZT-Stream par exemple)

**Comment by KodiTopQuebec** [comment]
@sizanic , tu as été capable d aller changer l adresse dans le plugin de vstream pour l essayer ? oui j étais en mesure de lire mes films avec débrideur avec ce changement d adresse , j'allais a l onglet hd light , mais la quelqu un a jouer dans le code pour free et depuis ce temps ça ne fonctionne plus

**Comment by KodiTopQuebec** [comment]
merci a celui qui a changé lURL dans free téléchargement maintenant il fonctionne avec la beta

**Comment by sizanic** [comment]
Oui c'est moi.
Mais je continue à douter de l'intérêt de cette source.
Beaucoup trop de liens morts...
Et un captcha à saisir.

Pour info, j'ai juste changé l'adresse et rien d'autre, donc personne ne s'amuse à "jouer" dans le code 🤔

**Comment by Arias800** [comment]
Hier j'ai désactiver le site pour les raisons suivantes : 
```
Site qui sert comme panneau d'affichage pour leur site payant.
Beaucoup de liens renvoie sur leurs ancien domaine.
Beaucoup de contenu payant.
```
Le site est totalement inutile était donner que ce qui est accessible gratuitement c'est des qualité équivalente au streaming xD

**Comment by sizanic** [comment]
@Arias800 , j'avais bien vu les raisons pour lesquelles tu avais désactivé cette source : 

> Beaucoup de liens renvoie sur leur ancien domaine.
> Beaucoup de contenu payant.

Mais pour moi ce n'était pas les bonnes raisons.
Je me suis dit que tu n'avais pas cliqué sur les bons liens car je ne suis tombé sur aucune redirection que tu cites, mais bien vers des hosters.

Mais malgré cela : 
Beaucoup trop de liens morts...
Et un captcha à saisir.


Edit : en effet quand je choisis de la haute qualité ça m’emmène vers un autre site ...

@KodiTopQuebec  on est désolé mais on ne va pas maintenir ce site sur vStream.

A moins que tu es de bons arguments, mais on doit faire des choix car on commence à avoir beaucoup de sources et la plupart sont bien plus intéressante que celle-ci.

**Comment by Arias800** [comment]
Oui effectivement je n'avais pas mis les détail donc les voici (j'ai passer plus d'une heures sur le site donc je pense avoir un point de vu suffisamment globale) :
- Tout les liens accessible sont au mieux des web-dl. Donc des flux récupérer depuis les services de SVOD, en sois les sites de streaming le font aussi.
- Parmi ces liens là il y en a pas mal qui redirige vers leurs ancien nom de domaine, qui n'est plus en activité.
- Tout les rip de Bluray (donc l'interets principale du DDL) redirige tous vers un site proposant du contenu payant, il est bien sur évident que jamais on ne proposera du compte disponible sur un site illégal payant.

Donc voilà pourquoi ce site est un panneau publicitaire xD.

**Comment by sizanic** [comment]
Je te rejoins sur ton opinion.
J'ai également passé du temps sur le site pour essayer d'y trouver un interet, afin de répondre à la demande de @KodiTopQuebec .

Mais je n'en ai pas trouvé.
Je confirme ton choix d'enlever cette source de vStream.

**Comment by KodiTopQuebec** [comment]
pour la je vous dit que présentement je peux écouter des films en 1080 dolby 5.1 a partir de cette adresse dans kodi a partir de cette source , et moi ce que je veux est d avoir du son dts ou dolby 5.1  et non du 2.0 comme les autres sources , pour moi je n ai aucun captcha a entrer comme dit plus haut , oui il y a des liens qui sont mort mais ceux qui fonctionnent au moins j utilises mon compte realdebrid pour obtenir mon 5.1 je vous fait des screens shot et comment s y rendre pour que ca fonctionne, 

je me dit vaut mieux avoir un site qui n est pas parfait que présentement zone téléchargement ne fonctionne pas du tout , free téléchargement (si on ne change pas lURL) ne fonctionne pas non plus , et il reste tirexo que lui fonctionne mais avec du contenu pas très a jour , donc comme conclusion il nous reste rien de bon pour du contenu 5.1 dans vstream avec un compte débrideur 

je n aurais pas demandé de changer l'adresse si mes tests ici n'aurais pas été concluant , il y a une marche a suivre a faire mais au moins ça marche

**Comment by KodiTopQuebec** [comment]
pour ce film en 1080 dolby 5.1 voici la procédure 

ouvrir free téléchargement ,aller a film ,choisir film HD 720 & 1080p(derniers ajouts) , il y a 2 liens pour bloodshot (HD) prendre le 1 er , choisir nitroflare  et le film commence comme la photo 

![Sans titre](https://user-images.githubusercontent.com/40530593/80493234-24164c80-8933-11ea-959a-904ccb967c3f.png)

**Comment by KodiTopQuebec** [comment]
ici même procédure que dit plus haut , 1080 dolby 5.1 pour le film Rendez-vous chez les Malawas

![Sans titre](https://user-images.githubusercontent.com/40530593/80493795-db12c800-8933-11ea-8d4f-9b3be4b0b589.png)

**Comment by KodiTopQuebec** [comment]
même procédure , il y en a plein de film qui démarrent pourtant avec cette procédure , et je tiens a voir des liens avec cette qualité ( vidéo et audio) , ici c est le film La Famille Willoughby en 1080 dolby digital plus  5.1

![Sans titre](https://user-images.githubusercontent.com/40530593/80494011-288f3500-8934-11ea-9c1b-6873a3d75f5d.png)

**Comment by sizanic** [comment]
Merci pour tous ces screenshots, mais ce type de description nous suffit : 

> aller a film ,choisir film HD 720 & 1080p (derniers ajouts) , il y a 2 liens pour bloodshot (HD) prendre le 1 er , choisir nitroflare et le film commence

Je ne sais pas si ça vient de ton debrideur mais moi j'ai pas le lien.

Directement depuis le site, je ne vais pas loin non plus. Arrivé sur Nitroflare, pas de lien Stream, et il faut un compte premium pour télécharger.

si ce que tu recherches est de la qualité de son 5.1, j'avoue qu'après quelques recherches sur d'autres sources, je n'en ai pas trouvé (mais j'ai pas fini et je cherche encore).

**Comment by yas06** [comment]
salut j ai fait la modif sur free telechargement effectivement j ai les liens 1fichier nitro  ( j ai un compte real-debrid)
depuis que zt et tirexo sont hs il reste que cette source pour des liens de qualite

**Comment by KodiTopQuebec** [comment]
@yas06 , maintenant si tu met la version beta tu auras cette adresse la et aussi tirexo va fonctionner de nouveau , reste juste le ZT ( qui est le meilleur)

**Comment by chataigne73** [comment]
> @yas06 , maintenant si tu met la version beta tu auras cette adresse la et aussi tirexo va fonctionner de nouveau , reste juste le ZT ( qui est le meilleur)

Il y a aussi extremedown qui propose des liens 5.1

**Comment by lebigboss** [comment]
Donc, si j'ai bien compris, il faut un abonnement nitroflare pour utiliser sinon c'est des liens payants ?
Sinon il faudrait ajouter un texte en rouge à l'accueil de la source pour le préciser, ça évitera que les gens viennent demander pourquoi uptobox ou 1fichier ne fonctionne pas.

**Comment by KodiTopQuebec** [comment]
@yas06 , sur un pc extrem down peut faire le travail , mais  a partir d'une boite ce n est pas plaisant , copier l adresse pour le coller dans vstream 

@lebigboss , tout les sources qui utilisent un compte débrideurs sont déjà identifiées en mauve dans vstream , pour que ça fonctionne, ça prend un compte débrideur payant comme realdebrid

**Comment by Arias800** [comment]
Alors non, les sites en violets c'est les site en DDL. Il ne nécessite pas forcement un débrideurs. Personnellement je suis contre l'ajout d'une source a moitié fonctionnel et qui en plus fonctionne pour la moitié (et encore) des utilisateurs.

**Comment by sizanic** [comment]
> les sites en violets c'est les site en DDL

Il y a vraiment un code couleur ??
Les sources dont le nom est en mauve dans la liste veut dire qu'on peut y retrouver les liens en Download, c'est ça ?
Qui sait ça ?!


> je suis contre l'ajout d'une source a moitié fonctionnel

J'ai envie de dire la même chose.
Mais pour l'instant ça marche, et tant qu'il faut juste changer l'URL ça va.
Alors pourquoi pas, pour ces quelques utilisateurs intéressés par cette source pour ce qu'elle vaut.

Mais le jour où ils changent tous le site et n'est plus compatible, alors là je pense qu'on ne va pas forcement la maintenir ...

**Comment by Arias800** [comment]
Oui le violets signifie que c'est du DDL. C'est un code implicite, mais ca ce remarque assez facilement je trouve. Sinon pour Free Telechargement en réalité il y a des modification a faire de certain regex de mémoire, car il y a des trucs qui sont récupérer alors que ça ne devrai pas être le cas.

**Comment by sizanic** [comment]
Le violet se remarque rapidement, mais on ne fait pas la relation rapidement avec le DDL :(

Encore maintenant j'ai du mal à comprendre.
Qu'est-ce que ça veut dire ?
Qu'on va y trouver des host comme 1fichier, et qu'il faut passer par _DL et lire_ pour lire ?

**Comment by Arias800** [comment]
Ça veut juste dire que c'est un site de téléchargement, c'est tout.

**Comment by sizanic** [comment]
Je ne comprends ce que tu veux dire par "site de téléchargement" ?

Si je vais sur Zone - Annuaire qui est en violet sur vStream, je sélectionne Star-wars, on me propose un lien Uptobox, je clique dessus et je vois le film en **Streaming**.

Il est vrai que le lien Uptobox s'appelle **télécharger** mais c'est tout, à aucun moment je télécharge.

**Comment by Arias800** [comment]
Uptobox c'est du un hoster qui propose du téléchargement, l'option "Streaming" c'est tout simplement le liens Uptostream qui est automatiquement générer par Vstream (il suffit de changer "uptobox" par "uptostream").

**Comment by sizanic** [comment]
> Si je vais sur Zone - Annuaire qui est en violet sur vStream, je sélectionne Star-wars, on me propose un lien Uptobox, je clique dessus et je vois le film en Streaming.

Ce que je décris ici c'est sur le site directement par un navigateur, pas par vStream.

Je vois bien le film en streaming directement sur le site. On ne me propose pas de fichier à télécharger.

Alors pourquoi on dit que c'est un site de téléchargement en le mettant en violet sur vStream ?

Et même si c'était un site avec que des fichiers à télécharger, pourquoi on veut les différencier dans vStream ?

**Comment by Arias800** [comment]
Le pourquoi, je ne le connait pas (c'était déjà comme ça quand je suis arriver), j'imagine que c'est pour séparer le téléchargement (qui demande généralement un abonnement) du streaming (qui n'en nécessite pas).
Ensuite le player qui est afficher sur Uptobox c'est juste un iframe contenant le liens uptostream. Mais sinon, si Uptobox propose (c'est meme le but de l'hébergeur) de télécharger.
![image](https://user-images.githubusercontent.com/24809312/80974326-db71fe00-8e20-11ea-9e06-d7149f4e4a80.png)

**Comment by sizanic** [comment]
OK donc dans vStream, si j'utilise le menu **Télécharger** sur ce type de lien je devrais pouvoir télécharger la vidéo.

Si on veut proposer aux utilisateurs de vStream un moyen d'indiquer quelles sont les sources qui proposent du téléchargement, je propose quelque chose de différents que la couleur.  Dès la page d'accueil de vStream, il faudrait une section "Téléchargement", pour y proposer les host en question.

**Comment by Arias800** [comment]
Il y a déjà un menu "Telechargement" qui permets de voir les fichiers télécharger. Donc le menu ferai doublons. Ensuite dans tout les cas les sources continueront d'apparaitre parmis toutes les autres dans le menu sources. Même chose au moment de la recherche. Donc rajouter un menu ne changera rien. Sans compter que le menu de Vstream est déjà suffisamment remplis xD

**Comment by sizanic** [comment]
Dans le dossier Films, il y a un sous-dossier Sources.
Dans le dossier Séries, il y a un sous-dossier Sources.
Dans le dossier Docs, il y a un sous-dossier Sources.
Dans le dossiers Animés, il y a un sous-dossier Sources.
etc.

Sur le même principe, dans le dossier Téléchargement, avoir un dossier Sources.

Parce que je ne crois vraiment pas que le code couleur soit connu et respecté.
Par exemple ZT-Stream est en violet !!

**Comment by Arias800** [comment]
> Par exemple ZT-Stream est en violet !!

C'est toi qui l'a fait je te rappel :p

Pour moi mettre des sous menu de partout n'est pas la solution, déjà que Vstream est une usine a gaze xD
Sinon ça ne règle pas les problèmes que j'ai citer plus haut :

> Ensuite dans tout les cas les sources continueront d'apparaitre parmi toutes les autres dans le menu sources. Même chose au moment de la recherche.

**Comment by sizanic** [comment]
> > Par exemple ZT-Stream est en violet !!
>
> C'est toi qui l'a fait je te rappel :p

Oui, je sais que c'est moi :D
C'est la preuve que même un développeur ne sait pas à quoi correspond la couleur, alors les utilisateurs...
Et je suis également utilisateur depuis des années et je n'ai jamais capté.

Et il faut que la source apparaisse avec les autres, et dans la recherche. Ce n'est pas un problème.

Maintenant je dis pas qu'il faut vraiment créer ce sous-menu, je dis que ce serait plus simple.
Car le code couleur n'est vraiment pas respecté.

Si une source qui propose des liens UpToBox est candidate à la couleur, alors il en manque plein.

**Comment by Arias800** [comment]
En vrai c'est gadget comme truc, c'est même pas vraiment utile. L'avantage du code couleurs c'est que si la personne le comprends c'est bien, mais si elle ne le comprends pas c'est pas grave. Puisque ça ne change en rien l'utilisation de Vstream. C'est que du bonus xD

**Comment by TmpName** [comment]
Oui, moi ca me sert aussi, j'ai pas de premium, donc je dis "en violet tu y vas pas", car generallement ce sont des DLs

Et des sites proposent sur la meme page DL + Streaming

Dans ma tete indirectement c'est plutot violet = premium, car sans ca uptobox/onefichier et ect, tu peux mettre une croix dessus.

**Comment by sizanic** [comment]
> Et des sites proposent sur la meme page DL + Streaming

Du coup il ne faut pas s'empecher de se rendre sur des sites violet car on peux y trouver du streaming ;)


> Dans ma tete indirectement c'est plutot violet = premium, car sans ca uptobox/onefichier et etc, tu peux mettre une croix dessus.

Je n'ai pas de premium, et quand je vois du uptobox je suis content car je sais que je vais récupérer le flux streaming de uptostream. Et onefichier en "DL et Lire" fonctionne bien aussi.
Donc les sites violet sont très intéressants aussi pour ceux qui n'ont pas de compte premium :)

Maintenant je comprends mieux l'interet de les différencier si c'est pour repérer les sites **premium**. Ceux qui ont un compte veulent l'utiliser et aller sur les sites qui le proposent.

**Comment by TmpName** [comment]
> > Et des sites proposent sur la meme page DL + Streaming
> 
> Du coup il ne faut pas s'empecher de se rendre sur des sites violet car on peux y trouver du streaming ;)

Yep, mais les site proposant dl+strming sont en bleu, seul ceux ne proposant que du DL sont en violet/rose

**Comment by yas06** [comment]
salut a vous le code couleur violet correspond a des liens sur des hoster payant dit premium 
1fichier,nitroflare,uptobox,rapidgator
les sites qui reference ces liens ont était mis au debut  en violet pour les différencier des autres a savoir que si tu na pas de compte premium les liens ne fonctionne pas ou tu les vois pas

**Comment by arzaz** [comment]
Les hosts ne s'affichent plus sur le site Free téléchargement?

**Comment by Arias800** [comment]
Je viens de corrigé quelque chose, donc les hosters devrai de nouveau apparaitre.

**Comment by LordVenom** [comment]
@KodiTopQuebec  nous non toi oui.

**Comment by KodiTopQuebec** [comment]
@LordVenom , mais de quoi tu parles ? tu commentes un vieux post du 26 avril 2020. il serait temps que tu sois  a jour dans tes commentaires , tu sais que ca change très vite et on ait rendu le 28 septembre 2020

**Comment by LordVenom** [comment]
Ben oui je fait le ménage, un coup de ral le bol tu connais ça je suis sure. tout ce qui a pas de réponse ou qui et hors code ça dégage.
