### ISSUE TITLE
SUIVI DES BUGS 0.8.0

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#2889]
**Environnement de test**
Dernier commit 
- OS: [Windows, Android]
- Appareil [Win10, Z6+]
- Version Kodi  [18,19]
- Version Vstream 0.8.0

**_Les Sources K.O._**
- Adkami (dossiers **vides**)
- hdsstrm (saisons et épisodes et manquantes )

**_Les Hosts K.O._** 
- Netu  **_pb de recapcha_**
- Vidtodo
- Prostrm
- Pstrm
- Mega 
- Vidlox (host)
- lien direct

**_Autre bug_**
- Kaydo :Marqué comme vu alors que non vu
- Adkami (Dossiers Hosts vides+ besoin d'ajouter les différentes catégories du site (_dernier ajout, serie, année etc_)?
- iAnime (dossiers ne s'ouvrent pas) PB DE CLOUDFARE -> _il faut retenter jusqu'à 5 fois et ça ouvre le dossier des hosts_
- Tirexo (dossiers ne s'ouvrent pas) PB DE CLOUDFARE -> _il faut retenter jusqu'à 5 fois et ça ouvre le dossier des hosts_

**_Les Hosts et sources Corrigés_**

_Ces corrections seront disponibles dans une prochaine mise à jour.
Il est possible de les tester en installant une version Beta._

* TODO

**Comment by ANNIEM83** [comment]
salut @sizanic est ce qu il faut l installer manuellement ou est elle disponible directement sur kodi merci:)

**Comment by sizanic** [comment]
Va s'installer directement sous Kodi, sans rien faire.

**Comment by ANNIEM83** [comment]
merci:)

**Comment by Che-debarras** [comment]
@sizanic 

> Aucune vidéo disponible" serait mieux? 

Oui

Pour Hdsstrm oui ya des saisons manquantes 
Ex : good girls s02 et s03, the sinner s03, stranger things s03,  vicking s04 s05 etc...

Quand on clique sur suivant pour aller a la 3e page on revient à  la 1e page

**Comment by kris06** [comment]
ZT  tirexo sur 0.8.0 (PC)  est à nouveau accessible merci, cependant aucun lien fonctionne...

**Comment by sizanic** [comment]
Probleme de protection ClouFlare avec Tirexo.

Le problème discuté ici (rechercher Tirexo dans la page) n'a pas été mentionné comme résolu : #2870

J'ai mis à jour le premier post pour s'en rappeler.

**Comment by Mokoman30** [comment]
Otaku toujours HS aussi depuis un bon moment

**Comment by TmpName** [comment]
Vidlox marche pas ? vous avez testé ou ?

**Comment by Che-debarras** [comment]
> Vidlox marche pas ? vous avez testé ou ?

Sur Kstrmng testé  sur Atlantic Rim Résurrection le lien vidlost fonctionne.

**Comment by yodidon** [comment]
@Che-debarras  pour le host « lien direct « 
Peux tu tester le cahier noir sur kaydo et me dire de ton côté ? ( pas encore sur androïde mais Windows et libreelec )
Merci

**Comment by kris06** [comment]
C'est très bizarre votre mise à jour 0.8.0 ne s'installe pas automatiquement elle est même pas notifiée à l'ouverture de vstream il faut passer par les paramètres pour l' installer. ( ça concerne mes 4 appareils sous Android et PC)

**Comment by yodidon** [comment]
> Quand on clique sur suivant pour aller a la 3e page on revient à la 1e page

si c'est sur Série il n'y a que 2 pages, d'ou le retour

**Comment by sizanic** [comment]
> > Quand on clique sur suivant pour aller a la 3e page on revient à la 1e page
> 
> si c'est sur Série il n'y a que 2 pages, d'ou le retour

Non ce n'est pas normal. Il faut corriger la regex.

**Comment by sizanic** [comment]
> C'est très bizarre votre mise à jour 0.8.0 ne s'installe pas automatiquement

Je pense qu'il faut attendre ...

**Comment by yodidon** [comment]
> > > Quand on clique sur suivant pour aller a la 3e page on revient à la 1e page
> > 
> > 
> > si c'est sur Série il n'y a que 2 pages, d'ou le retour
> 
> Non ce n'est pas normal. Il faut corriger la regex.
Je n’ai pas dit que c’était normal ? J’ai juste donné la cause

**Comment by kris06** [comment]
Tirexo (ex  zone-ware.com) vient  à  nouveau changer son url , désormais tirexo.com

Ça en devient presque une hystérie que d’en changer toutes les semaines…
Du coup la modit de sizanic ou d arias800 (je ne sais plus) à propos du changement d’url, ne s’adapte pas automatiquement pas avec cette dernière adresse

**Comment by Arias800** [comment]
J'ai désactiver pour le moment la détection automatique, car l'adresse principal (zone-warez .com) était très lente a répondre. J'ai fait cela puisque l'adresse était stable et n'a pas été changer depuis longtemps. Et a mon avis la nouvelle ne va pas changer pendant un moment. Donc je vais laisser comme ça, et ne pas remettre la détection automatique qui posais plus de problème qu'autre chose, si jamais l'adresse se remets a changer régulièrement alors je réactiverai la détection automatique.

**Comment by sizanic** [comment]
Tu as mis à jour l'adresse à deux endroits mais sans mettre deux fois la même adresse :thinking: 
(je sais qu'une des deux n'est pas utilisée)

Sans parler de la détection automatique, est-ce que la fonction GetURL_MAIN() n'utilise pas également un paramètre "tirexo" dans le fichier settings.xml (\userdata) qui permet à chacun de changer l'adresse sans modifier le fichier source ?

**Comment by kris06** [comment]
En effet merci , j'ai l'impression que tirexo vous pose plus de problèmes que les autres sources… (voir différents problèmes que j’ai déjà signalés)

C’est dommage qu’il soit , tirexo est  une fois sur deux HS et je ne parle pas ici d’url.

tirexo a lui seul pourrait presque être indexé exclusivement à la fonction recherche de vstream, car c’est bien le seule source qui possède pratiquement tous les titres…

quand pensez-vous réactiver tirexo à 100% ?

**Comment by Arias800** [comment]
Oui j'ai mis les deux adresse dans le fichier car pour le moment je teste avec une adresse fixe. Mais j'ai quand même mis l'URL_HOST au cas où il faudrait réutiliser GetURL_MAIN() (gains de temps vu que l'adresse sera déjà dans le fichier xD).

Dans le cas présent le changement d'adresse dans le fichier était obligatoire vu qu'ils ont changer l'url principal (celle qui est utiliser dans URL_HOST). Le fonctionnement du parametre "tirexo" est simple :
- On se connecte URL_HOST.
- On récupère la redirection.
- On inscrit l'url dans "tirexo".

Le soucis c'est que dans le cas présent l'adresse qui sera inscrit dans le paramètre sera pas bonne vu que se sera "tirexo com" (car zone-warez renvoie vers tirexo.com) . Hors Kodi n'arrive pas bien a gérer les redirection automatiquement.

Le soucis c'est que Tirexo est régulièrement en panne du coter du site, donc on ne peu pas faire grand chose quand il est inaccessible xD

**Comment by sizanic** [comment]
> tirexo a lui seul pourrait presque être indexé exclusivement à la fonction recherche de vstream, 

Tu peux ajouter la lien de Recherche de Tirexo dans tes favoris KODI comme ça tu l'auras directement en page d'accueil :wink: 

> quand pensez-vous réactiver tirexo à 100% ?

Je pense que tu ne parles pas de l'adresse qu'on a déjà changé si tu récupères la Beta, mais du problème CloudFlare.

Je ne pense pas que quelqu'un soit dessus pour l'instant, on ne peut pas te donner de date, on travaille comme on le sent :smile:

**Comment by sizanic** [comment]
> Le fonctionnement du parametre "tirexo" est simple :
> 
> * On se connecte URL_HOST.
> * On récupère la redirection.
> * On inscrit l'url dans "tirexo".

Il me semblait qu'un moment on pouvait utiliser le paramètre autrement.
En y mettant soi-même manuellement l'adresse qu'on voulait.

**Comment by Che-debarras** [comment]
> @Che-debarras pour le host « lien direct « 
> Peux tu tester le cahier noir sur kaydo et me dire de ton côté ? ( pas encore sur androïde mais Windows et libreelec )
> Merci

@yodidon  le lien direct sur kaydo fonctionne sur android je testerai sur les autres sources et je vous tiens au courant.

**Comment by Arias800** [comment]
Pour tout ce qui est Cloudflare c'est le module de Venomous et il est en train de travailler sur la nouvelle version de Cloudflare.
Oui logiquement on peu modifié les paramètre manuellement, sauf que au final ça revient au même. C'est meme plus simple de modifier le fichier site.

**Comment by Che-debarras** [comment]
> Pour tout ce qui est Cloudflare c'est le module de Venomous et il est en train de travailler sur la nouvelle version de Cloudflare.
> Oui logiquement on peu modifié les paramètre manuellement, sauf que au final ça revient au même. C'est meme plus simple de modifier le fichier site.

@Arias800 ça tombe bien que tu en parles du cloudfare car je pense faire un checkup une fois cloudfare corrigé et pour pas vous imposer du travail imposant car vous avez fait un travail énorme pour fournir la 0.8.0

Sauf si vous vous ennuyez 😉 j

**Comment by kris06** [comment]
Je sais tout cela à propos des favoris, je sais aussi que vous bossez pour le plaisir de nous tous et je vous en remercie, encore. Je voulais juste souligner ici, l’intérêt de cette source qui me semble indispensable dans le catalogue de vstream.

Pour ma part, je change l'adresse manuellement dans tirexo.py lorsque que c’est nécessaire et  c'est  aussi ce fichier py  que je partage avec mes amis et qui vient s’installer dans vstream par le moyen que je vous ai déjà décrit à propos de mon robot android

**Comment by yodidon** [comment]
> > Quand on clique sur suivant pour aller a la 3e page on revient à la 1e page
> 
> si c'est sur Série il n'y a que 2 pages, d'ou le retour

j'ai fait une correction qui fonctionne même si c'est pas la meilleure

**Comment by Che-debarras** [comment]
> > > Quand on clique sur suivant pour aller a la 3e page on revient à la 1e page
> > 
> > 
> > si c'est sur Série il n'y a que 2 pages, d'ou le retour
> 
> j'ai fait une correction qui fonctionne même si c'est pas la meilleure

StrmySerie à 2 categories identique serie dernier ajout qui n'a pas les pages suivantes et serie qui a les pages suivantes 

Sur cette source les liens directes (dossier Mega) sont soit vides sont liens non fonctionnelle

**Comment by yodidon** [comment]
> > > > Quand on clique sur suivant pour aller a la 3e page on revient à la 1e page
> > > 
> > > 
> > > si c'est sur Série il n'y a que 2 pages, d'ou le retour
> > 
> > 
> > j'ai fait une correction qui fonctionne même si c'est pas la meilleure
> 
> StrmySerie à 2 categories identique serie dernier ajout qui n'a pas les pages suivantes et serie qui a les pages suivantes
> 
> Sur cette source les liens directs (dossier Mega) sont soit vides sont liens non fonctionnelle mais le site indique que c'est des liens de téléchargement pas de streaming

pour ce qui est de page suivantes c'est le site qui est fait comme ça apparemment et comme les séries sont surement classé par ordre d'ajout ça concorde, ou sinon il faut reccuperer ce qu'ils appellent Derniers épisodes Séries-TV ajoutés, mais ce sera une liste d'épisodes en vrac pas sur de l’intérêt,  la question est garde t'on les 2 ?

**Comment by yodidon** [comment]
> > > > Quand on clique sur suivant pour aller a la 3e page on revient à la 1e page
> > > 
> > > 
> > > si c'est sur Série il n'y a que 2 pages, d'ou le retour
> > 
> > 
> > j'ai fait une correction qui fonctionne même si c'est pas la meilleure
> 
> StrmySerie à 2 categories identique serie dernier ajout qui n'a pas les pages suivantes et serie qui a les pages suivantes
> 
> Sur cette source les liens directs (dossier Mega) sont soit vides sont liens non fonctionnelle mais le site indique que c'est des liens de téléchargement pas de streaming

pour les host qui ne sont pas traité j'ai mis un filtre, a voir si c'est bien ...

**Comment by sizanic** [comment]
> pour les host qui ne sont pas traité j'ai mis un filtre, a voir si c'est bien ...

Bien sûr que c'est bien , c'est ce qu'on essaye de mettre dans toutes les sources :smile:

**Comment by sizanic** [comment]
> j'ai fait une correction qui fonctionne même si c'est pas la meilleure

Pour la gestion des pages suivantes, ta correction est bien.
Juste un problème en arrivant à la dernière page. J'ai modifié.

**Comment by Che-debarras** [comment]
En dehors des bugs des sources, la recherche similaire ne retourne des résultats que sur 1 ou 2 sourcs voire 3 alors que la recherche globale en retourne beaucoup plus.
C'est lié à vstream ou a kodi?

**Comment by yodidon** [comment]
> > j'ai fait une correction qui fonctionne même si c'est pas la meilleure
> 
> Pour la gestion des pages suivantes, ta correction est bien.
> Juste un problème en arrivant à la dernière page. J'ai modifié.

Pas vu le problème :)

**Comment by sizanic** [comment]
Arrivé à la dernière page , ça propose encore un "suivant" qui ramène à la page précédente.

**Comment by yodidon** [comment]
> Arrivé à la dernière page , ça propose encore un "suivant" qui ramène à la page précédente.

Avec ma modif il n’y a plus de suivant sur la dernière page ? C’est pas ce qu’il faut ?

**Comment by Che-debarras** [comment]
> Arrivé à la dernière page , ça propose encore un "suivant" qui ramène à la page précédente.

Ya le meme souci avec Tirexo

**Comment by sizanic** [comment]
Si, c'est ce qu'il faut mais ce n'est pas ce que j'avais.

**Comment by TmpName** [comment]
Dsl je me repete mais donc
Vidlox , on considere que c'est bon ?
Vitodo, vous auriez un site avec lien fonctionnel, moi c'est mort a chaque fois.

**Comment by sizanic** [comment]
Vidlox, d'après le dernier test positif de @Che-debarras ça fonctionne sur dpStraem.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2889#issuecomment-620346475

Donc il est correct en tant que host.

Si il y a un problème avec un autre site, ça vient du site qui l'utilise mal.
Il faut corriger la source de ce site, mais pas le host.

=> Host Vidlox OK pour moi.

Ton avis le @che ?

**Comment by yodidon** [comment]
Pas facile de trouver ou sont les host K.O , je navigue sur les sources
 mais je trouve pas :(

**Comment by TmpName** [comment]
Pareil pour vitodo, c'est pour ca que lui je l'ai laché, pas possible de trouver un lien valide pr tester.

**Comment by yodidon** [comment]
Oui d’où l’idée d’ajouter le site sur lequel il a été testé

**Comment by DaX59** [comment]
Salut,
dans d'autres fils j'avais cru comprendre que certains avaient des problèmes avec Alldebrid.
Ca viendrait pas du fait qu'ils aient modifié leur API ? 

> Une annonce pour signaler à tous les développeurs d'outils externes utilisant Alldebrid (via notre API), que la version finale de notre API est détaillée ici => https://docs.alldebrid.com/v4/#general-informations

Si votre outil n'utilise pas la V4 de notre API, il faudra vous mettre à jour avant le 1 Mai, date à laquelle toutes les anciennes versions de notre API seront désactivées.

N'hésitez pas contacter notre support pour toutes questions relatives à notre API.

**Comment by Rikikisifreddo** [comment]
Zt, tirexo et zt stream sont plus dispos, "aucune information", deuis la maj. (fire stick tv). C'est normal donc ?

**Comment by yodidon** [comment]
@Rikikisifreddo  oui , la protection cloudfare n’est pas encore résolue

**Comment by gratoQ** [comment]
46 issue c'est du jamais vu il y a plus de pilote dans l'avion le crash n'est pas loin.

**Comment by razorex** [comment]
Enstream n'affiche plus les hosters

**Comment by sizanic** [comment]
> 46 issue c'est du jamais vu il y a plus de pilote dans l'avion le crash n'est pas loin.

Ce serait vrai si chaque issue était vraiment la déclaration d'un bug (si on reprend la définition de issue).

Mais beaucoup d'issues sont plutôt utilisés ici comme nouveau sujet comme sur un forum de discussion 🤔 

donc beaucoup d'issues veut dire beaucoup de discussions veut dire que beaucoup de personnes sont intéressées pour faire vivre cette extension !!

**VIVE VSTREAM !!**

**Comment by yodidon** [comment]
Pour enstream changement d'URL et surtout arrivé de cloudfare ....

**Comment by isandard** [comment]
Venomous a patché en version 1.2.36 mais je ne sais pas si tout est corrigé où si il y a eu une modification encore depuis.

**Comment by yodidon** [comment]
@isandard malheureusement c’est pas encore ça ...

**Comment by Mokoman30** [comment]
Bonsoir les gars, svp sa fais 1 ans que j arrive plus a regarder sur tvreplay quoi que ce soit sur buzzmonclick ou topreplay toujours  (no informations) sa n as jamais été régler :/

**Comment by TmpName** [comment]
Pour topreplay, je viens de verifier c'est mort, recaptcha.

Va vraiment falloir s'y pencher sur recaptcha, ca tient jamais, mais on le vois partout.

**Comment by Arias800** [comment]
Tu est motivé pour vouloir t'attaquer a Recaptcha xD

**Comment by TmpName** [comment]
Pas le contourner ^^, j'ai pas 2 an de vie a foutre en l'air.

Mais utiliser une application externe, surtout pr le captcha invisible.

**Comment by Arias800** [comment]
C'est bien ce que je me disais xD
Oui un système D un peu dans le même style que ça : https://www.youtube.com/watch?v=9FdvTXVGI7I&feature=youtu.be

**Comment by TmpName** [comment]
Oui, mais comme c'est le captcha invisible, doit moyen de tout faire en "invisible"

**Comment by Arias800** [comment]
J'ai bricoler un truc pour avoir une idée de ce qui peut etre fait, et j'avoue que je suis assez surpris xD
Pour l'utiliser il suffit d'avoir l'addon Tapermonkey et de mettre le script a l'intérieur de l'addon (pour le moment il est utilisable que sur Extreme download).
https://github.com/Arias800/Fichier-divers/blob/master/Recaptcha.user.js
Le script va automatiquement appuyer sur le bouton pour valider et il va afficher le token de recaptcha dans la console.

**Comment by TmpName** [comment]
Par contre moi je tourne sur firefox, c'est un peu lourd a lancer juste pr lire un captcha ...
Pour moi c'est vraiment ca le point noir, et en navigateur headless c'est pas aussi simple que le "vrai navigateur"

**Comment by Arias800** [comment]
Le problème d'un navigateur headless c'est que le captcha était (je sais pas si c'est toujours le cas) automatiquement bloquer car il détectait que c'etait un headless (notamment avec l'UA).

Il devrai mais visiblement il ne le fait pas xD

**Comment by Che-debarras** [comment]
> J'ai fait une recherche en mettant le dns de clouflare 1.1.1.1 et ceux de opennic j'ai le même résultat 5 sites dont la recherche Renvoi l'erreur 503 :
> Entstream
> Hdstream
> Papstream
> Streamingk
> Zone téléchargement

2902

**Comment by kris06** [comment]
Salut très heureux de voir le retour de tirexo malheureusement les liens ne fonctionnent pas erreur 503. S'agit-il d'un bêta en cours ?

**Comment by yodidon** [comment]
@Che-debarras , pour hds-stream, avec une modif de cloudscraper, chez moi ça fonctionne

**Comment by Che-debarras** [comment]
> @Che-debarras , pour hds-stream, avec une modif de cloudscraper, chez moi ça fonctionne et aussi Streamingk

Je ne fais que signaler les bugs pour le suivi et une correction générale pour tout le monde 

En plus de ces sources il y a dans mon compte tmdb qui n'ouvre pas notre liste.

Donc ce serait bien de les rajouter dans les sources qui bugguent

**Comment by yodidon** [comment]
Oui la correction devrait être dans la bêta

**Comment by yodidon** [comment]
hds-stream, je pense que l'on peut le mettre en corrigé

**Comment by sizanic** [comment]
Dans d'autres issues, j'entends parler d'une mise à jour partielle.
Mais elle n'a pas l'air de venir :)

Si vous n'êtes pas pressé, je peux me lancer dans une mise à jour complète ce weekend.
ça vous intéresse ?

**Comment by Arias800** [comment]
C'est moi qui l'ai retarder un petit peu a cause des modification de python 3. Mais logiquement il ne devrai pas y avoir de bug puisque j'ai pas encore fait les modifications qui risque de tout casser xD

**Comment by sizanic** [comment]
J'ai l'impression que @razorex est en train de les faire ces modifications.
Il faut peut-être l'arrêter pour figer une version avant.

**Comment by razorex** [comment]
Bah tu viens de dire ce week-end @sizanic

**Comment by sizanic** [comment]
Oui, je voudrais créer une mise à jour tant que la version est stable.
Il faudrait donc attendre _**après**_ cette mise à jour pour continuer les développements risqués sur du code compatible python 2/3.


En même temps, @TmpName veut faire une MAJ partielle aujourd'hui.

@TmpName t'en es où, tu la fais ou pas ?
Moi j'attendrais au moins ta correction sur ZA.

**Comment by razorex** [comment]
Bah je pense en avoir fini.

**Comment by Ovni-crea** [comment]
Zone annuaire ont enlevé la redirection du coup tout refonctionne (pour l'instant) mais ne le mettez pas en corrigé pour l'instant on ne sait jamais si il le remette

**Comment by TmpName** [comment]
Ben elle est dispo depuis hier.
D'ici 4 jours on saura si elle peut poser probleme ^^

**Comment by Rikikisifreddo** [comment]
Salut. En fait chez moi, sur fire stick, c'est tout vstream qui donne plus rien. Aucune source ne fonctionne.

**Comment by sizanic** [comment]
> Salut. En fait chez moi, sur fire stick, c'est tout vstream qui donne plus rien. Aucune source ne fonctionne.

Un peu plus de contexte, stp 
Avec la beta ?
Quel type d'erreur ?
Etc.

**Comment by Rikikisifreddo** [comment]
La bêta ? J'avais la version avant celle qui vient de sortir. Je parvenais à obtenir un résultat sur tirexo je crois, mais dès que je cliquais dessus, "aucune information". Là, j'ai fait la dernière maj proposée 0.8.1 me semble-t-il. ZT :"aucune information", tirexo ne fonctionne pas du tout, tout comme de nombreux autres sites.

**Comment by kris06** [comment]
Ça fait longtemps que tirexo  et ne marche plus cher ami les autres sources sont en services pour la plupart.
