### ISSUE TITLE
Fonction Download and play manquante

### ISSUE THREAD

**Issue by Jaytec007** [Kodi-vStream/venom-xbmc-addons#2890]
Windows 10

Salut la fonction Download and play n est plus disponible comme avant sur la version 0.8.0.
Sans compte premium avec les liens 1fichier cette fonction est la seule pour y avoir acces

**Comment by sizanic** [comment]
Il faut activer l'option dans la paramètres de vStream : 
Enregistrement / Activer l'enregistrement.


Penses à utiliser un DNS si tu telecharges.

**Comment by TmpName** [comment]
Ha, j'ai pas vu ca.
Pkoi c'est plus dans le menu, ca derangeait ?

**Comment by sizanic** [comment]
Actif par défaut, ça incites les personnes à télécharger.


J'ai eu une mauvaise expérience au début de mon utilisation de vStream.
J'ai téléchargé une fois.
J'ai reçu une lettre d'Hadopi !! 😱

**Comment by Jaytec007** [comment]
L option enregistrement est activer, je l ai desactiver et reactiver pour voir si sa embarquerais mais l option DL and play est toujours pas la. J ai reinstaller la version 0.7.9 et l option est revenu

**Comment by sizanic** [comment]
En effet, petite boulette.
C'est corrigé dans la Beta, dsl.

**Comment by Jaytec007** [comment]
Pas de probleme hehe il y a t il un endroit ou ont peux telecharger le beta ou faut attendre la prochaine version? C est pas la fin du monde s il faut attendre je peux utiliser le 0.7.9 en attendant

**Comment by Arias800** [comment]
L'option Enregistrement est utiliser pour l'IPTV, pas pour l'option download and play xD

**Comment by Jaytec007** [comment]
C'est possible mais pour les liens 1fichier quand ont a pas de compte premium tu peu utilisé Download and play et après quelques secondes de buffering ca fonctionne

**Comment by gratoQ** [comment]
@sizanic remet le fichier comme avant pas besoin d'activer d'option pour ceux qui dl
et a mon avis si tu as reçu une lettre ça viens d'ailleurs torrent etc...

**Comment by sizanic** [comment]
> @sizanic remet le fichier comme avant pas besoin d'activer d'option pour ceux qui dl
> et a mon avis si tu as reçu une lettre ça viens d'ailleurs torrent etc...

J'ai remis comme avant.
En effet, je me rappelle maintenant, la lettre venait d'une autre activité. :disappointed: 

> comme dit @Arias800 l'enregistrement c'est pour l'ip tv

Ce n'était pas précisé.

> donc arrêter de faire n'importe quoi les nouveaux merci.

C'est ironique ? :thinking: 


> il y a t il un endroit ou ont peux telecharger le beta

Le dernier lien en bas de cette page : https://github.com/Kodi-vStream/venom-xbmc-addons
"Télécharger Bêta"

**Comment by Arias800** [comment]
D'autant plus que la fonction enregistrement de l'iptv est plus ou moins abandonner (trop complexe a mettre en place avec Kodi) donc c'est logique de ne pas savoir xD

**Comment by TmpName** [comment]
>En effet, je me rappelle maintenant, la lettre venait d'une autre activité. 

Ha wi me souvient, et pas eu de soucis avec les cartels colombien ?

**Comment by sizanic** [comment]
> Ha wi me souvient, et pas eu de soucis avec les cartels colombien ?

non pas cette activité là, encore une autre, celle-ci c'est bon :)

J'avais testé ça : 
http://planetedata.windows8.free.fr/telecharger_un_torrent_avec_l_interface_freebox_os_2358.htm

**Comment by Arias800** [comment]
Ah bah ça c'est ton FAI qui ta balancer à la Hadopi xD

**Comment by TmpName** [comment]
Faut prendre des FAT corses, ils balancent pas eux.
