### ISSUE TITLE
Bande Annonce VF

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2891]
Les bandes annonces sont anglais , y a t'il un moyen de les avoir en français ?

Je souhaiterais savoit quel addon ou astuce habilnage vous utiliser pour etre averti des nouvelles episodes ajouté à une serie? 

Au pire quel habillage de kodi est le plus adapté pour vstream

Merci

**Comment by gratoQ** [comment]
pour les BA's, vstream prend la 1ere qu'il trouve sur youtube donc c'est très aléatoire comme les métadonnées.
pour le reste il n'y a rien de fiable comme addon

**Comment by Che-debarras** [comment]
Serait il possible dans la recherche de filtrer pour qu'il affiche des BA VF et VOSTFR? Ou faire la recherche sur un site spécialisé de BA ?
Merci 

Pour ma 2e question même si c'est pas fiable je suis preneur

**Comment by sizanic** [comment]
> Les bandes annonces sont anglais

Toutes ?
Ou plutôt "certaines et très peu" de bandes annonces sont en anglais.

> Serait il possible dans la recherche de filtrer pour qu'il affiche des BA VF et VOSTFR?

Nous aussi on prefere en FR, on a fait ce qu'on a pu.

> Ou faire la recherche sur un site spécialisé de BA ?

Tu en connais ?

> Quel addon ou astuce vous utiliser pour etre averti des nouvelles episodes ajouté à une serie ?

Je ne sais pas si trakt peut faire ça. Mais dans tous les cas, ça voudrait pas dire que ce nouvel épisode est disponible parmi toute les sources proposées :thinking:

**Comment by TmpName** [comment]
Yep trakt le peut, j'avais un addon pas mal en plus a l'epoque, mais c'etait les sortie americaine, et a final au bout de 15 jours je m'en servait plus, impossible de suivre, les series s'enchainent trop vite, me faudrait 10 an de confinement pour pouvoir suivre le rythme.

**Comment by Che-debarras** [comment]
Non a filmactu ou bandeannonce.fr
Je vais voir avec trakt
Merci

**Comment by TmpName** [comment]
Je trouve pas ^^
Bande annonce et out chez moi, et le premier je trouve pas l'adresse.

**Comment by Che-debarras** [comment]
> Je trouve pas ^^
> Bande annonce et out chez moi, et le premier je trouve pas l'adresse.

https ://www.bandes-annonces.fr
https ://cinema.jeuxactu.com/bande-annonce.htm

Chez moi les 2 fonctionnent

**Comment by sizanic** [comment]
A l'air facile à mettre en place celui-là : 
https ://www.bandes-annonces.fr

Mais j'ai tenté au hasard de voir la bande annonce de Jurassic World, j'ai pas réussi :(


Tu peux nous donner un exemple de bande annonce que tu as eu en anglais et qui serait en français sur ce site, stp ?


Plutôt qu'une fenetre contextuelle de choix, je partirai plutôt sur tenter un site, puis partir sur l'autre automatiquement si on ne trouve pas.

**Comment by Che-debarras** [comment]
Par exemple voyage de dolittle , sur planetstrmng il refuse de trouver une bande annone mais sur le site BA.com il y a une version VF de la BA.
Ya d'autres films qui refusent de chercher une bande annonce et pourtant ce film a une B.A sur YouTube du site filmactu

**Comment by TmpName** [comment]
On peut mettre une option dans la config de vsteam ou l'utilisateur choisit son site, comme ca pas de prise de tete.

Faut juste trouver un site fiable.

**Comment by sizanic** [comment]
J'ai trouvé comment on peut récupérer une meilleure bande annonce de Youtube.

J'ai testé avec "le voyage de dolittle" et ça passe bien.

Ce sera prêt dans la semaine.

**Comment by TmpName** [comment]
C'est quoi l'astuce ? un champs en plus ?

**Comment by gratoQ** [comment]
il faut savoir que pour certain film,aucune bande annonce n'est trouvable en fr sur le net.

**Comment by sizanic** [comment]
> C'est quoi l'astuce ? un champs en plus ?

J'aurai bien aimé 😄 

Dans le cas du "voyage de dolittle" la premiere vidéo youtube n'est pas la vidéo officielle, mais celle de filmsActu. 
La vidéo officielle de "_Universal Pictures France_" arrive en 4eme position : 
https://www.youtube.com/watch?v=1Kukjr0u5lI

Je ne sais pas si filmsActu a mal utilisé Youtube pour upoader leur vidéo mais vStream n'arrive pas à décoder la page associée (on arrive sur une erreur 503).

Pour retrouver la vidéo officielle , je suis aller interroger le site themoviedb
https://www.themoviedb.org/movie/448119-dolittle?language=fr-FR

Vous remarquerez que dans l'URL de la BA, la key est l'id de la vidéo youtube : 
https://www.themoviedb.org/video/play?key=1Kukjr0u5lI

J'ai fais ça proprement pour interroger TMDB, en utilisant la librairy de vStream qui gére les metadata de TMDB (le fichier tmdb.py).

Donc pour la recherche de la BA, j'ai ajouté ces lignes

```
                meta = cTMDb().get_meta(self.metaType, self.search, year=self.year)
                if meta and 'trailer_url' in meta:
                    urlTrailer = meta['trailer_url']

```

Et dans tmdb.py, j'ai également revu la gestion des BA proposée par TMDB, car il en propose plusieurs et en plusieurs langue, il fallait retrouver la BA en FR.


=> c'est dans la Beta.

**Comment by TmpName** [comment]
Lol, ha wé, quand meme

**Comment by Che-debarras** [comment]
Ça à l'air de bien fonctionner,j'ai testé 2 autres films mais pas de bol B.A en V.O mais c'est normal car meme sur navigateur ils ne sont pas en VF, ni VOSTF.

Merci

**Comment by sizanic** [comment]
Tu as vérifié sur TheMovieDB ?
Quels films ?

**Comment by Che-debarras** [comment]
> Tu as vérifié sur TheMovieDB ?
> Quels films ?

The night clerk par ex

**Comment by sizanic** [comment]
En effet, sur TMDB, pas de BA du tout : 
https://www.themoviedb.org/movie/526007-the-night-clerk?language=fr-FR

Sur YT, que des BA en VO.
=> Donc dans vStream, une BA en VO.

**Comment by sizanic** [comment]
- Des exemples où vStream ne trouve une BA qui existerai pourtant ?
- Trouvez-vous que les BA se lancent plus rapidement maintenant ?
- Pensez-vous que ce soit vraiment utile de laisser le choix de la qualité ? Que pensez-vous de lancer par défaut la qualité 720p ?

**Comment by TmpName** [comment]
Plus ou moins rapidement, je peux pas dire meme sur youtube c'est variable, et perso c'est toujours plus rapide que la moyenne.

Choissir la qualité me derange pas non plus, mais c'est vrai que sur youtube 720p ca passe toujours, je sais pas si il y a des machines ou ca peut prendre plus de temps que le 360p. 
Mais du coup tu vas "patcher" ou ? Ca va impacter les videos normales aussi ?

**Comment by yodidon** [comment]
@sizanic 
Pour la qualité, dans mon cas (sûrement rare) je ne peux pas lire du 720 p dû à ma connexion limité par moment ( et oui encore des zone blanche dans notre merveilleux pays)
Pour la suite je dirais mais j’ai pas encore assez de recule
