### ISSUE TITLE
vstream  enregistrement/recording

### ISSUE THREAD

**Issue by mica1234567** [Kodi-vStream/venom-xbmc-addons#2892]
**Décrivez le bug**
enregistrement n'est pas accessible dans le menu quand on appuie sur raccourci C
it is not possible to record anymore 

**Votre system**
 - OS: [, Android]
-  Appareil [raspberry]
 - Version Kodi  [17.]
- Version Vstream 8.0

**Comment by TmpName** [comment]
Perhaps https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2890

**Comment by mica1234567** [comment]
merci pour cette reponse rapide

bonne soiree
