### ISSUE TITLE
Vstream ne s'exécute pas sur Android TV Box

### ISSUE THREAD

**Issue by keke2040** [Kodi-vStream/venom-xbmc-addons#2893]
**Décrivez le bug**
J'ai installé Vstream sur le Kodi de mon Android TV Box à l'aide du zip téléchargeable sur ce site comme je l'avait déja fait à de multiples reprises sur mes autres appareils (tv, nas, tel,...).
Seulement cette fois-ci vstream s'affiche dans mes extensions mais n'est pas exécutable (les onglets exécuter et configurer sont grisés lorsque je lance l'appli dans le dossier système/extensions). Pour info, j'ai le même problème avec une autre extension (chorus2 interface web). 
Auriez-vous une idée sur l'origine du problème?

**Votre system**
 - OS: [Android]
-  Appareil [X96 Max]
 - Version Kodi  [18.4]
- Version Vstream Venom 0.0.3

**Comment by lebigboss** [comment]
On va surement te demander des logs, même si je pense que ton problème vient plutôt de Kodi.

**Comment by TmpName** [comment]
Exactement

**Comment by Grum31** [comment]
Vstream 0.0.3??? Ça c’est le repository. As tu installé  l appli vstream à l aide du repository?
J’ai aussi une box chinoise avec une rom Android tv et ça marche bien

**Comment by sizanic** [comment]
> vstream s'affiche dans mes extensions mais n'est pas exécutable (les onglets exécuter et configurer sont grisés lorsque je lance l'appli dans le dossier système/extensions)

-> ça correspond au repository
