### ISSUE TITLE
streamingK ne fonctionne pas de nouveaux

### ISSUE THREAD

**Issue by fpodev** [Kodi-vStream/venom-xbmc-addons#2894]
**Décrivez le bug*
Bonjour, après avoir fonctionné un certain temps, il replante. 

 Et voici la capture 🥳
![IMG_20200502_184256](https://user-images.githubusercontent.com/9036717/80870556-75ae3680-8ca7-11ea-935f-05fbdb1c81ac.jpg)

**Votre system**
 - OS: Android tv
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [18.6]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by TmpName** [comment]
La protection CF a changé, pas encore stable, si tu essayes plusieurs fois ca devrait passer.

**Comment by razorex** [comment]
J'ai mis en place un clone

**Comment by Arias800** [comment]
Je vient de mettre a jour Cloudflare, il est possible que ca est temporairement corriger le problème.
