### ISSUE TITLE
Tirexo- Error 503- Changement nom de domaine

### ISSUE THREAD

**Issue by mannou78** [Kodi-vStream/venom-xbmc-addons#2895]
**Décrivez le bug**
La source tirexo ne semble plus fonctionner de nouveaux.

Ils ont change le nom du domaine a www2.tirexo.org au lieu de https://www2.tirexo.com

**Votre system**
 - OS: Android
-  Appareil Invidia
 - Version Kodi  18.6
- Version Vstream 0.80

**Nous devons le reproduire**
Essayer d utiliser la source tirexo

**Log**
vStream: Erreur: Connection Failed (503),https://www2.tirexo.com/film-ultra-hd-x265/

**Comment by Arias800** [comment]
Le problème n'est pas liée au nom de domaine, j'attends que le module de Cloudflare sois corriger pour le mettre a jour.

**Comment by TmpName** [comment]
Et c'est mal barré, je me suis retrouvé avec un captcha apres la verif CF ....

**Comment by Arias800** [comment]
Apparemment Venomous a trouver comment CF déclenche le captcha et il a l'air d'avoir une idée de contournement. Par contre on n'a pas fini d'avoir des issues si jamais ils mettent le captcha sur Tirexo xD

**Comment by lebigboss** [comment]
Surtout c'est pas .com mais .org aujourd'hui et on attend le fameux .ninja .......

**Comment by isandard** [comment]
et hop c'est repassé à .com.
Girouette inside.

**Comment by TmpName** [comment]
Lol, des cascadeurs professionnel, surtout ne pas essayer chez vous.

**Comment by sizanic** [comment]
Faudrait qu'on se fasse un petit générateur d'URL.
Qui teste chacune des possibilités : 
- www, wvw, wvv, wwww, www2, ...
- .com, .org, .net, .ninja, ...


Et pourrait être utilisé par plusieurs sources ...

**Comment by TmpName** [comment]
Ben de lancer une requete sur la derniere url et de memoriser la nouvelle en cas de changement permet d'avoir une url fiable en une seule requete.
Les urls que tu testes peuvent partir en timeout et mettre jusqu'a 30/60s a repondre.
