### ISSUE TITLE
Cinemegatoil Vstream 

### ISSUE THREAD

**Issue by Cikai91** [Kodi-vStream/venom-xbmc-addons#2898]
**Décrivez le bug**
Lien dans Cinemegatoil ne fonctionnent pas . 
La liste des films est bien disponible.

**Votre system**
 - OS: [Android]
-  Appareil [box Android ]
 - Version Kodi  [17.6]
- Version Vstream 0.8.0

**Nous devons le reproduire**
Pour cela il nous faut:
- Cinemegatoil

Le site a l'air intéressant mais aucun lien est dispo ... Est ce normal ? 
Pour information c'est la première fois que j'essaie ce site. 

Merci a vous

**Comment by Ovni-crea** [comment]
@Cikai91 c'est normal c'est à cause des liens keeplinks il y a recaptcha dessus malheureusement

**Comment by TmpName** [comment]
Ha oui, du coup on vire le site ?

**Comment by yodidon** [comment]
On essaie pas de voir si ça bouge ?

**Comment by TmpName** [comment]
Si, perso je sais pas depuis quand c'est en place, on peut laisser quelques semaines.

Au pire on desactive juste le site en mettant une date.

**Comment by yodidon** [comment]
Oui c’est une bonne alternative

**Comment by TmpName** [comment]
je m'y colle, du coup je cloture, attente de voir comment le site evolu.

**Comment by yodidon** [comment]
Ok 👍

**Comment by Arias800** [comment]
J'ai réactiver le site, car le recaptcha qui est sur KeepLinks est passable via ma méthode.

**Comment by Cikai91** [comment]
Arias, peut tu me donner ta méthode stp ? 
Je l'ai pas trouvé

**Comment by Arias800** [comment]
J'ai implémenter le code dans le script. Le script récupère automatiquement les images et les affiches. Ensuite il suffit a l'utilisateur de choisir les bonne images. Le script s'occupe du reste.

**Comment by Cikai91** [comment]
Merci je vais tester .

**Comment by Cikai91** [comment]
C'est parfait 
On peut passer keepslink avec le choix des des images.
Mais fichier introuvable par la suite lorsqu'on sélectionne Uptobox par exemple
