### ISSUE TITLE
Utiliser l'Addon soundcloud 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2899]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Soundcloud ne fonctionne plus et ils ont pas mal changé le site du coup je me demande si on peut lire les liens avec l'addon soundcloud (sachant que c'est dans le dépo officiel de kodi)

**Comment by gratoQ** [comment]
t'es au courant que c'est pas un forum kodi ici ?

**Comment by Ovni-crea** [comment]
@gratoQ Je parle du hoster Soundcloud pas de l'addon et là je propose de passer par l'addon car le hoster ne fonctionne plus et ça pourrait leurs faire gagner du temps

**Comment by TmpName** [comment]
Y a un site qui utilise ce hoster ?

**Comment by Ovni-crea** [comment]
@TmpName Oui c'est lsdb qui utilise ce hoster

**Comment by TmpName** [comment]
Bon j'ai mit une nouvelle version mais qui ne marchera pas longtemps
Il ya une liste de lien et je prend celui avec "48-", mais evidement ce ne sera pas toujour le cas, donc faut trouver un moyen de trouver le bon ou au pire tous les charger.

**Comment by Ovni-crea** [comment]
@TmpName D'accord merci pour tout
