### ISSUE TITLE
Information concernant Zone-annuaire (08/05/2020)

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2901]
BONJOUR/BONSOIR À TOUT LE MONDE.

PS : [ Note temporaire / provisoire : SITE INACCESSIBLE pour le moment. PASSEZ PAR Z-T-Stream svp en attendant, merci. ]

DORÉNAVANT, VOUS DEVRIEZ POUVOIR VOUS CONNECTER SUR Z-A SANS AVOIR À FAIRE AU CAPTCHA (TEST VIA CAPTURE IMAGE) DONT LE SEUL ET UNIQUE BUT ÉTAIT DE CONTENIR DES ATTAQUES INCESSANTES, CES DERNIERS JOURS.

MALHEUREUSEMENT, CERTAINS D'ENTRES VOUS NE POURRONT TOUJOURS PAS COMMENTER OU ENVOYER DES MESSAGES (VIA MP) MAIS NOUS METTONS TOUT EN OEUVRE POUR DISSOUDRE TOUTES LES MAUVAISES ONDES.

POUR ÊTRE PLUS CLAIR ET POUR FAIRE TAIRE TOUTES SORTES DE SPÉCULATIONS, NOTEZ BIEN QUE LE SITE Z-A (COMME BEAUCOUP D'ENTRE VOUS L'ONT/L'AVAIENT DEVINÉ) A SUBIT UNE ATTAQUE ET CONTINUE ENCORE DE L'ESSUYER.
NOUS FAISONS NOTRE POSSIBLE POUR CONTRER CES AGISSEMENTS DÉPLORABLES PORTÉS CONTRE Z-A.
NOUS POUVONS POUR LE MOMENT CONTENIR LA CYBERATTAQUE ET NOUS ESPÉRONS, BIEN ENTENDU, L'ÉTOUFFER POUR DE BON !

NOUS TENONS À NOUS EXCUSER DE NE PAS L'AVOIR DIT CLAIREMENT ET PLUS TÔT MAIS LE CONTEXTE NE LE PERMETTAIT PAS TROP, À CE MOMENT-LÀ.

MILLE MERCIS AUX NOMBREUX QUI N'ONT EUS DE CESSE DE NOUS ENCOURAGER ET POUR CEUX QUI S'EMPORTAIENT, VOUS AVIEZ SIMPLEMENT DÉMONTRÉ QUE VOUS TENIEZ BEAUCOUP AU SITE Z-A ET CELA N'EST PAS RIEN. DONC NE VOUS SENTEZ PAS MAL À L'AISE CAR DU RESTE ET JE LE RÉPÈTE, NOUS N'AVIONS PAS PRÉCISÉ CLAIREMENT LA NATURE DU PROBLÈME RENCONTRÉE PAR VOTRE/NOTRE SITE Z-A !

APRÈS LA TEMPÊTE, LE CALME ? JE L'ESPÈRE, NOUS L'ESPÉRONS TOUS TRÈS FORT ! VIVE Z-A !

Source:http s://www.forumzt.com/infos-at-f155/cyberattaque-dirig-e-contre-zone-annuaire-com-z-a--t6301.html

**Comment by sizanic** [comment]
Merci pour l'info.

Et par la même occasion, ils nous ont mis le beau captcha sur ZT-Stream.

= blocage vStream :((

**Comment by Cikai91** [comment]
Bah c'est cool ça !
Nous allons avoir une mise a jour pour zone annuaire ?

**Comment by Ovni-crea** [comment]
@TmpName  bon zone annuaire refonctionne ils ont supprimé la redirection du coup je close l'issue
