### ISSUE TITLE
Impossible de trouver un lien valide !!! 

### ISSUE THREAD

**Issue by peto51** [Kodi-vStream/venom-xbmc-addons#2902]
Bonjour, 
Depuis quelques temps je n'arrive plus à trouver de lien pour voir un film en streaming. 
Je m'explique : ce soir je voulais voir le film çà chapitre 2, assez répandu sur les sites de download, la recherche affiche déjà 4 sites sur laquelle la connexion est impossible. 
Lorsque la recherche est terminé, je fais chaque lien sur 10, 15 site différents en y passant à peu près 1 heure mais aucun lien ne m'a donné satisfaction, fichier introuvable ou ne se la'ce pas (sachant que je prend que du DVD-rip, hdrip et hdrip). 
J'ai pourtant un compte uptobox et 1fichier mais même ceux là, impossible de les lire. 
Je voudrais préciser que j'ai pas une super connexion (2 mega Max) mais ça ne m'a jamais empêché de regarder les films d'habitude. 

Depuis quelques mois, je trouve que l'addon Vstream est difficilement utilisable voir même est un échec la plupart du temps.
J'ai même essayé de trouver les liens uptobox et 1fichier sur le téléphone et le basculer sur l'addon mais les liens ne se lance.
uptobox "fichier introuvable" alors qu'il est bon. 
1fichier ça mouline pendant quelques secondes et ça s'arrête. 
C'est dommage je trouve que l'addon à un vrai potentiel mais là je suis forcé de me débrouiller sans, pour l'instant. 
Je guette les mise à jour, mais ça ne s'ameliore pas. 
Est ce qu'il y a que moi qui constate tout ses bugs ? 

Si vous avez besoin de plus d'info, je pourrais vous détailler une recherche parmi d'autre qui n'aboutit pas. 

 - OS: Coreelec officiel 9.2.2
-  Appareil : Odroid n2
- Version Vstream 0.8.0

**Comment by yas06** [comment]
salut apparemment beaucoup de site sont down si tu a un debrideur passe sur free telegargement c ok  si tu na pas de debrideur passe sur kepliz c ok

**Comment by razorex** [comment]
çà chapitre 2 ==> trouve sur cinemay hoster frenchvid en 720p, trouvé en recherche global et il se lance @peto51 
Pareil sur filmillimite ==>dood en 720p et clickopen en 1080..
j'ai testé les 2 premiers résultats..

**Comment by gratoQ** [comment]
@peto51 a raison plein de site sont hs ou erreur 503 ou lien vide  le soir c'est pénible la recherche

**Comment by peto51** [comment]
merci pour vos liens.
Tout ça pour dire que je ne le trouve pas super fonctionnel.
je conçois que le boulot fait sur cette addon est énorme, il me semblait que l'année dernière je prenais pas autant de temps pour trouver un film.
j'utilise souvent zone-annuaire ou wawacity pour mes recherches dommage qu'ils ne soit pas présent sur vstream.
razorex : ma connexion est trop juste pour le 720p, on ne choisi pas sa connexion internet :)

**Comment by Arias800** [comment]
Les problème viennent souvent d'élément externe sur lequel on a aucun contrôle :
- Cloudflare pour Tirexo
- Recaptcha pour Wawacity
- Les attaques que Zone Telechargement subit

Donc on ne peut pas faire de magie. Pour le coup ont subit autant que vous xD

**Comment by peto51** [comment]
pour wawacity c'est la page wInk.ec lorqu'on genere le lien ? Recaptcha c'est quoi ? si je vais sur le site depuis mon navigateur il ne me demande pas de captcha.
Pour zone annuaire c'est zt protect qui genere le lien qui pose probleme ?

**Comment by Arias800** [comment]
Oui c'est au niveau de la page wInk.ec. Recaptcha c'est le captcha de Google (celui où il faut sélectionner plusieurs images), seulement il existe une version dite "invisible" qui ne nécessite aucune action de l'utilisateur. C'est cette dernière qui est utiliser pour Wawacity.

Dans le cas de zone annuaire pour le moment c'est le site qui pose problème car il est instable. Ils ont d'ailleurs déployer Recaptcha sur le site depuis hier.

**Comment by peto51** [comment]
Le captcha ne peut pas être fait manuellement dans vstream comme j'ai deja vu sur certain liens ?

**Comment by Arias800** [comment]
Non impossible

**Comment by peto51** [comment]
ok, j'essai juste de comprendre si on peut améliorer la chose.

**Comment by peto51** [comment]
Je sais que mon débit internet doit être en grande partie la cause du fait que certain liens ne se lance pas.
En général avec 1fichier et uptobox ça fonctionne à part si je selectionne uptostream, il me dit fichier introuvable alors que le lien est valide.

**Comment by TmpName** [comment]
Tu aurais les logs pour le test avec up2strm ?
Essayes en desactivant le premium.

**Comment by peto51** [comment]
j'ai desactivé le premium et ça fonctionne en uptostream

**Comment by TmpName** [comment]
Donc surement le meme soucis que la https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2831

**Comment by Che-debarras** [comment]
Pour les erreur 503 pensez a tester avec DNS car sans cela beaucoup de site sont hs durant la recherche globale et je pense que cela doit etre obligatoire désormais

**Comment by peto51** [comment]
Qu'est ce qu'il faut utiliser comme DNS pour améliorer la recherche ?

**Comment by peto51** [comment]
> çà chapitre 2 ==> trouve sur cinemay hoster frenchvid en 720p, trouvé en recherche global et il se lance @peto51
> Pareil sur filmillimite ==>dood en 720p et clickopen en 1080..
> j'ai testé les 2 premiers résultats..

Je n'arrive à lancer les liens que tu dis, ça mouline quelques secondes et ça s'arrête sans lancer la vidéo et surtout sans message d'erreur

**Comment by Che-debarras** [comment]
Une application qui s'appelle Dns changer si tu est sur android box
Ou aller sur les paramètres reseau de coreelec pour ajouter les adresses dns

J'ai pratiquement pas de err503 sauf pour 3 ou 4 sources sur les 30 mais en general c'est un problème du site tel que otaku tirexo mais ya plus de 20 sources qui marchent sans problèmes

**Comment by TmpName** [comment]
Pour info, si votre probleme concerne les DNS, quelqu'un a poposé une modif qui va vas rendre possible de changer son serveur dns uniquement pour Vstream, mais par contre pas encore de mode d'emploi.

Sinon @peto51 regardes dans tes logs si tu n'as pas un message d'erreur, car les cause possibles sont multiples.

**Comment by peto51** [comment]
J'ai fait une recherche en mettant le dns de clouflare 1.1.1.1 et ceux de opennic j'ai le même résultat 5 sites dont la recherche Renvoi l'erreur 503 : 
Entstream
Hdstream
Papstream
Streamingk
Zone téléchargement

**Comment by Che-debarras** [comment]
> J'ai fait une recherche en mettant le dns de clouflare 1.1.1.1 et ceux de opennic j'ai le même résultat 5 sites dont la recherche Renvoi l'erreur 503 :
> Entstream
> Hdstream
> Papstream
> Streamingk
> Zone téléchargement

Oui le compte est bon lol c'est les 3 ou 4 hosts qui ont une erreur de connection qui corriger mais ya de quoi faire avec les autres notamment dpstrm pour les series et plntstrm ou kaydo pour les films

**Comment by peto51** [comment]
Donc j'ai fait le test avec ça chapitre 2, que je n'ai toujours pas vu 😁😁. 

J'ai fait une recherche et au hasard j'ai pris sur film illimité le lien netu dans vstream, il cherche et me dit fichier introuvable donc je me suis rendu sur le site de film illimité avec mon téléphone et j'ai fait la même recherche et le lien netu fonctionne et est lisible sur le téléphone. 

Donc je vais essayé de voir au niveau des logs pour voir ce qui cloche, si vous pouvez me dépanner je vous posterais les logs avec les éventuels erreurs.

**Comment by TmpName** [comment]
Tu es pas chanceux, on dirait une boussole qui indique le sud, Netu est HS pour longtemps.

**Comment by peto51** [comment]
en tout cas hier il marchait quand j'ai testé.

**Comment by peto51** [comment]
je vous poste ici le log avec les test de lecture sur plusieurs sources différente :

[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4624789/kodi.log)

il y'a plusieurs fois l'erreur CPythonInvoker qui revient mais je ne saurais pas identifier la source du problème.

Si quelqu'un peut me venir en aide...

**Comment by TmpName** [comment]
Ha bon ? bon ok j'avou je decouvre Vstream ....
Sinon pour ton bug, le fichier est bien trouvé, mais c'est kodi qui l'air de galerer (probleme de format ?)
Un test a faire, telecharger le fichier au lieu d'essayer de le streamer, et essayer de lire le fichier du disque.

**Comment by peto51** [comment]
J'ai testé aussi d'utiliser un lecteur externe comme VLC pour lire les films sur mon ordi et certains que je n'arrive pas à lire sur Coreelec fonctionne. 
Je pense que c'est le lecteur de kodi qui foire ou alors il y'a un temps donné pour lire le fichier et après il abandonne car sur VLC ca met une bonne minute pour charger le lien.

**Comment by peto51** [comment]
Le fichier que je stream est un lien vidlox, je n'arrive pas à le télécharger, je ne sais pas si c'est possible...

**Comment by peto51** [comment]
Au temps pour moi, j'ai pu télécharger le fichier a partir de vidlox et du coup il est bien lisible par kodi donc ce n'est pas à priori un problème avec le lecteur de kodi.

**Comment by TmpName** [comment]
Et merde, j'etais sur de mon coup ...
Tu l'as telechargé a partir de Vstream ? et du coup lu a partir de la partie "download" ? (C'est juste une question, refais pas le test)

Dans les parametres de Vstream (au moins a une epoque) tu pouvais changer le lecteur de kodi.

Et oui il y a un timeout, au bout d'un moment tu as une erreur, mais tu as fais un test sur up2strm, tres bon site, jamais de timeout, et tu aurais pas le meme message d'erreur, la ca ressemble vraiment a un message d'erreur de lecture.

Tu as activé les logs dans les parametres de Vstream ? car il ya moyen de l'avoir "plus fournis".

**Comment by peto51** [comment]
Non je n'ai pas pu à partir de vstream c'etait un lien vidlox, je l'ai téléchargé depuis l'ordi et lui sur mon odroid et impeccable. 
Et le Time Out je peux le changer, rajouter du temps.

**Comment by sizanic** [comment]
> je vous poste ici le log avec les test de lecture sur plusieurs sources différente :
> [kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4624789/kodi.log)
> 
> il y'a plusieurs fois l'erreur CPythonInvoker qui revient mais je ne saurais pas identifier la source du problème.
> Si quelqu'un peut me venir en aide...

CPythonInvoker c'est pas grave, c'est des warning.

La vrai erreur c'est ça : 
TypeError: argument 1 must be string without null bytes, not str
ERROR: Playlist Player: skipping unplayable item: 0

Je vois l'erreur dans cette url : 
https%3A%2F%2Fhqq.tv%2Fplayer%2Fembed_player.php%00vid%3DKEKpLxWgIInN%26autoplay%3Dno


J'aimerai la reproduire pour la corriger.

Tu sais dans quelle source tu étais pour récupérer ce lien netu ?

**Comment by TmpName** [comment]
Il n'a pas activé tout les log @sizanic mais il a lancé 2 video juste avant, dont un lien up2strm.
Les ficiers existaient, le lien a ete decodé, mais les deux ont planté en 
>2020-05-13 23:23:38.366 T:3529446272   ERROR: OpenDemuxStream - Error creating demuxer

C'est surtout ca qui me fait penser a un probleme de lecteur.

**Comment by peto51** [comment]
j'ai fais des test en ouvrant le film sur le host vidlox sur le site stream complet avec les log de vstream activer : [vstream17.05.20.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4639984/vstream17.05.20.log)

Je vous ai mis également les logs de kodi :
[kodi17.05.20.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4639986/kodi17.05.20.log)

le fichier fonctionne bien sur le site de streamcomplet 
[impr_ecran_vidlox_stream_complet](https://user-images.githubusercontent.com/56508973/82141067-a6f43e00-9833-11ea-9a77-1b6a8a6978d7.jpg)

alors pourquoi est ce que je n'arrive pas à le lire sur l'addon vstream ???

**Comment by TmpName** [comment]
Les 2 premier logs sont les memes ?
Pour avoir plus d'info il faudrait activer les logs, tu peux faire ca dans les options de vstream et dans kodi.
Tu as essayé de changer le lecteur dans les option sde Vstream ?

**Comment by peto51** [comment]
oui ce sont les logs qui se sont passé au même moment, celui que j'ai upload avec l'addon vstream et celui de kodi récupérer sur l'ordi avec les logs vstream qui se sont ajouté.
j'ai mis VLC comme lecteur de kodi mais sur mon ordi et les videos vidlox se lisent mais sur odroid je ne peux pas mettre de lecteur externe.

**Comment by Ovni-crea** [comment]
Il y a aussi streamingdivx qui ne fonctionne plus avec cloudflare par contre Streamingk aucun soucis @Che-debarras
