### ISSUE TITLE
Clone vstream

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2903]
Je me demandais si vstream de ludopotte est un clone ou c'est le même que le votre?
Car j'ai l'impression qu'il compile les mises a jour de la beta pour en faire des betas mineurs installables ou des patch.

Vu que désormais j'installe les plugins avec git browser est ce que installer ses patchs permettent d'avoir vos dernieres corrections car je pense qu'il les puise de votre beta ppur faire son zip.

**Comment by Arias800** [comment]
Il mets simplement la beta en zip. La seul chose qui change c'est juste le logo d'Enstream car il a choisis de faire un logo alternatif.

**Comment by Che-debarras** [comment]
Ok car c'est agaçant de ddl les beta manuellement et de copier coller les fichiers.
Avec github briwsersur kodi on peut apparemment installer les zip et donc s'il compile déjà les maj beta ça fait gagner du temps. 

Merci pour la réponse si rapide

**Comment by razorex** [comment]
Tu télécharge le zip, sur notre Git en bas de la page d’accueil et depuis Kodi tu fais installer depuis un zip @Che-debarras !!! pas besoin de faire un copier coller.

**Comment by Che-debarras** [comment]
Merci @razorex
