### ISSUE TITLE
Intégration Uptobox dans la bibliothèque 

### ISSUE THREAD

**Issue by slimooo** [Kodi-vStream/venom-xbmc-addons#2907]
Bonjour,

vStream est super pratique, merci pour le boulot.

Je l'utilise pour streamer depuis mon compte uptobox.

Une frustration : les films et vidéos ne sont pas synchronisés avec ma bibliothèque. C'est dommage je dois passer par l'addon osmosis.

Est-il possible d'ajouter une fonctionnalité des synchronisation des films vstream avec la bibliothèque?

**Comment by sizanic** [comment]
Cela doit être possible, car @isandard se plaint ici que les fichiers sont affichés par date d'ajout et pas par nom : #2660

**Comment by alKODIque** [comment]
En fait, la seule façon de synchroniser nos fichiers uptobox avec la médiathèque de kodi (sans l’utilisation d’un addon externe) est de prendre les fichiers un a un comme il faut le faire avec ceux de toutes les autres sources de vStream... Alors pour les séries tv, ça demande un travail très long...

De mon côté, J’utilisais  l’addon  “library integration tool”. Mais j’ai récemment souscrit a un abonnement alldebrid et ça à réglé mon soucis puisque Alldebrid propose maintenant un dossier https que nous pouvons intégrer directement a la library de kodi.

**Comment by slimooo** [comment]
> 
> 
> En fait, la seule façon de synchroniser nos fichiers uptobox avec la médiathèque de kodi (sans l’utilisation d’un addon externe) est de prendre les fichiers un a un comme il faut le faire avec ceux de toutes les autres sources de vStream... Alors pour les séries tv, ça demande un travail très long...
> 
> De mon côté, J’utilisais l’addon “library integration tool”. Mais j’ai récemment souscrit a un abonnement alldebrid et ça à réglé mon soucis puisque Alldebrid propose maintenant un dossier https que nous pouvons intégrer directement a la library de kodi.

J'ai essayé library integration tool, ça fonctionne parfaitement avec les films mais les séries ne sont pas détectées :s

**Comment by alKODIque** [comment]
Moi non plus les séries n’étaient pas détectés avec LIB 😔

**Comment by speedjeje** [comment]
Salut,
La "meilleure" solution que j'ai trouvée pour ton problème (j'avais le même à la base), c'est d'utiliser AddToLib comme expliquer là par Arias800 :

[http://kodi-fr.rf.gd/showthread.php?tid=30](url)

Sinon, depuis hier ne rencontres-tu pas des problèmes pour lire tes fichiers hébergés sur ton compte Uptobox depuis vStream ?

**Comment by slimooo** [comment]
Salut,

J'avais essayé add to lib mais chez moi ça ne fonctionne pas. J'ai essayé plusieurs solutions mais aucune n'est pleinement satisfaisante. Par exemple Library Integration Tool considère les séries de mes dossiers UpToBox comme étant des films (bizarrement ce n'est pas le cas quand on sélectionne le dossier séries inclus par défaut dans vstream).

Aujourd'hui je fonctionne comme ça :

1) Pour les films, j'utilise OSMOSIS en suivant j'ai suivi le tuto : http://kodi-fr.rf.gd/showthread.php?tid=27&pid=591

2) Pour les séries j'utilise pseudolibrary, mais je dois faire les mises à jour à la main :s

C'est vraiment pas l'idéal mais à défaut ça fonctionne

**Comment by sizanic** [comment]
> C'est vraiment pas l'idéal mais à défaut ça fonctionne

tu parles que c'est pas l'idéal 🤔 
Dans le tuto faut modifier le code de vStream et désactiver les mises à jour 😱 

@vic1997 avait pourtant travaillé avec les développeurs de vStream.
Mais j'ai l'impression que ce n'était pas allé jusqu'au bout.

@vic1997  c'est l'occasion de relancer le sujet.
tu pourrais nous en redire plus sur le blocage ?

**Comment by vic1997** [comment]
Bonjour, oui ça fait très longtemps qu'on en avait parlé, je n'utilise plus ce plug-in ni même Kodi ou Uptobox depuis, du coup je ne pourrais pas vous donner un nouveau moyen autre que ce sur j'avais fais à l'époque, comme sur le lien qui a été envoyé.
Pour ce qui est des développeurs de vStream, j'avais déjà demandé et ça avait été refusé par eux car pour eux ce n'est pas le but de vStream et que ce n'est pas à eux de s'occuper de cette partie là.
Je n'ai donc pas de nouveau moyen pour réaliser ça et j'ai jamais réussi à le faire intégrer dans vStream car les développeurs ne voulaient pas.

**Comment by speedjeje** [comment]
Alldebrid propose maintenant un dossier https que nous pouvons intégrer directement a la library de kodi.

Tu peux nous expliquer le fonctionnement, voir si on peut bidouiller quelque chose avec Uptobox ?

**Comment by alKODIque** [comment]
Ce que j'ai fait c'est que j'ai ajouté en bloc mes fichier uptobox a Alldebrid. Ensuite, j'ai ajouté directement a ma library kodi mon lien https Alldebrid (via les paramètres de medias) puis je scrape ma source qui s'intègre donc a la médiathèque de kodi.... mais ceci ne fonctionne que pour les films puisque Alldebrid, via son dossier https, propose seulement 2 dossiers parents qui sont "liens magnets" et "fichiers sauf gardés " et puisque pour scraper adéquatement un dossier, je dois mensionner ce qu'il y a a l'intérieur (films ou séries)... Alors pour je réserve mon dossier magnets pour les séries....

C'est un processus long et un peu pénible mais ça fonctionne. 

J'aimais bien avant la fonctionnalité dans vStream qui permettait d'ajouter un lien directement dans notre compte uptobox... il a disparu depuis quelque temps. Est-ce qu'il y a une possibilité de remettre cette fonctionnalité?? C'était accessible via le menu contextuel

**Comment by alKODIque** [comment]
J'oubliais...
Le dossier https de Alldebrid a la même forme qqu'un "index of/". En fait, ça en est un. En seulement, la dernière partie du lien est notre token: https://myfiles.alldebrid.com /xxxxxxxxx
(Xxxxx) etant le token
