### ISSUE TITLE
Répertoire site - VSTREAM

### ISSUE THREAD

**Issue by Kasper1n** [Kodi-vStream/venom-xbmc-addons#2909]
Bonjour à tous,

Je suis en train d'essayer de créer une source pour VSTREAM mais je ne trouve pas le répertoire "SITE"
j'ai installé KODI Leia sous windows.

Merci pour votre aide.

**Comment by yodidon** [comment]
C’est dans appdata, romening Kodi addon vstream ressource, site

**Comment by yodidon** [comment]
https://kodi-vstream.github.io/docs/folder/
Plus clair sur ce lien avec d’autre info qui pourraient t’intéresser

**Comment by Kasper1n** [comment]
@yodidon merci beaucoup pour ta réponse rapide

**Comment by sizanic** [comment]
Il faut aussi t'assurer que la source n'existe pas déjà (n'est-ce pas yodidon :stuck_out_tongue_winking_eye: )

Par exemple, le site time2watch vient d'etre ajouté il y a une demi-heure.
Et il existe aussi beaucoup de clones dans au moins une version est déjà traité dans vStream.

Donc le mieux est de nous dire ici sur que site tu veux travailler pour éviter de travailler pour rien.

**Comment by Kasper1n** [comment]
Merci à tous,

pour répondre sizanic, il s'agit de ce site : https://wuw.wiflix.net/

Possible d'avoir de l'aide?

**Comment by yodidon** [comment]
C’est pas un clone de Wiflix déjà sur Kodi ?

**Comment by sizanic** [comment]
c'est pas le clone de wiflix,
C'EST Wiflix


Si tu te rends à l'adresse utiliser par vStream 
https://vvw.wiflix.net/
tu es redirigé sur cette adresse : 
https://wuw.wiflix.net/


@Kasper1n 
tu ne vois pas déjà la source Wiflix dans vStream ??

**Comment by Kasper1n** [comment]
@sizanic 
Non pas par défaut,  tu sais ou je peux la DL ?

Je me permets d'ajouter un autre site très populaire : http://malcolm-streaming.com/

**Comment by yodidon** [comment]
Tu as installé vstream ?

**Comment by Kasper1n** [comment]
Oui je l'utilise depuis quelques années

**Comment by sizanic** [comment]
Lorsque tu arrives dans le menu principal de vStream, il y a un menu "Sources" en bas avec la liste de toutes les sources. Regarde du coté de la lettre 'W' 😉

**Comment by Kasper1n** [comment]
Lol,  pas de trace d'ailleurs aucune config à w.

**Comment by sizanic** [comment]
Malcom streaming, c'est assez restreint comme source 🤔

**Comment by sizanic** [comment]
Tu as quelle version de vStream ?

**Comment by Kasper1n** [comment]
@sizanic 
Version 0.0.3

Malcolm c'est une valeur sûre ;)
7 saisons de pure bonheur

**Comment by sizanic** [comment]
0.0.3 c'est la version du REPO, pas de l'addon vStream.

**Comment by sizanic** [comment]
Si tu as le repo 0.0.3, c'est bien.
Si l'addon est en "mise à jour automatique" c'est mieux, tu devrais alors avoir la bonne version.

Tu as quelle version ?

**Comment by Kasper1n** [comment]
@sizanic  c'est visiblement la 0.8.0

**Comment by sizanic** [comment]
Et le menu "sources" est bien le dernier de la liste, après "marque-pages" et "historique" ?
Et dans ce menu, tu ne vois pas "Wiflix" entre "VoirFilms" et "Youtitou" ?

**Comment by Kasper1n** [comment]
Bonjour à tous,

@sizanic bonjour, je t'assure je n'avais pas cette source (fausse manip, mauvais instillation ?)

Je viens de réinstaller et c'est désormais "ok"

**Comment by TmpName** [comment]
Lol Malcom, j'adore aussi ^^

**Comment by sizanic** [comment]
Moi aussi.
Mais de là à développer la source 🤔

**Comment by TmpName** [comment]
Ben si il la fait lui meme, c'est pas genant, y aura moins de boulot que avec ZT.
Pas de recherche globale non plus.

**Comment by Kasper1n** [comment]
Bonjour à tous,

@TmpName 
@sizanic 


Je vais bien essayer à condition qu’on m’aide un peu dans la démarche 😁

**Comment by sizanic** [comment]
Il y a bien une source dédiée à "plus belle la vie" !!

**Comment by sizanic** [comment]
> Je vais bien essayer à condition qu’on m’aide un peu

La procédure est ici :
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source

La première étape c'est bon, cette source n'existe pas (Malcom, pas wiflix :wink: )
Crée maintenant un nouveau fichier dans le dossier source en partant du squelette qui est proposé.

Tu peux mettre les urls en dur pour les liens vers les saisons.
Mais ensuite il faut utiliser des expressions régulière pour analyser la page web et retrouver le titre et le lien de la vidéo.

La création du fichier suffit pour le voir dans les sources de vStream, dans KODI.

**Comment by Kasper1n** [comment]
@sizanic 
Tu peux me conseiller une source qui ressemble au canevas du site streaming Malcolm?

Merci

**Comment by TmpName** [comment]
Ben justement le truc, c'est mieux de partir sur le fichier decrit dans la procedure, il est basique, mais plein de commentaire.

**Comment by sizanic** [comment]
En fait je viens de voir le fichier en question et il est en effet trop complet pour toi.
Les trois-quart sont inutiles !!

Pars de Mamcin.py

**Comment by kar2013** [comment]
@sizanic 
Merci je regarde

**Comment by kar2013** [comment]
@TmpName 
@sizanic 

Comme conseillé, je me base sur la config Mamcin.py, pour m'aider svp pouvez-vous me préciser le fonctionnement général 

Si j'ai bien compris la fonction def showMovies(sSearch = ''): (ligne 61) cherche tous les épisodes de la page visée.

Une fois tous les liens scrapés on cherche toutes les autres pages avec la fonction def __checkForNextPage(sHtmlContent): (ligne 113)

Mais cela ressemble à tout sauf à une boucle

**Comment by yodidon** [comment]
Il faut faire l’a pattern avec par exemple regex101 et définir les résultats pour sUrl, sTitle, sThumb etc.... après on renvoie ver def showshosters en fonction de la page des liens , si les hoster sont sont connus par vstream ça roule sinon il faut faire le fichier du/des hosters( pour info je suis le plus nul dans le coin , mais je galère tellement que je peux donner quelque avis pour débuter...)

**Comment by Kasper1n** [comment]
@yodidon 
A quoi correspond la variable Sthumb ?

**Comment by sizanic** [comment]
__checkForNextPage
Ça sert à proposer un lien "Suivant" donc ce n'est pas une boucle.
Lorsqu'on clique dessus on revient dans showMovies avec la page suivante.
Mais toi t'as pas besoin car tous les épisodes sont sur la même page ?

Et ne t'en sert pas pour la liste des saisons, mets les urls vers les saisons en dur.

**Comment by yodidon** [comment]
L’URL de l’affiche du film/ serie

**Comment by Kasper1n** [comment]
Bonjour à tous,

@sizanic 
@yodidon 
@TmpName 

Vous pouvez svp me dire si vous avez des astuces pour repérer les liens de téléchargement 

Je ne les vois pas sur le site de streaming de Malcom

**Comment by yodidon** [comment]
@Kasper1n  peux tu me redonner le lien ?

**Comment by Kasper1n** [comment]
@yodidon 
Le lien en question :    http://malcolm-streaming.com/

**Comment by yodidon** [comment]
les hoster sont lister ici

<li class="active"><a href="#mystream" data-toggle="tab">Version française</a></li>
--
  | </ul>
  | </li>
  | </ul>
  | <div class="tab-content">
  | <div class="embed-container tab-pane fade active in" id="mystream">
  | </div>
  | <div class="embed-container tab-pane fade " id="mystreamvostfr">
  | </div>
  | <div class="embed-container tab-pane fade " id="upvid">
  | </div>
  | <div class="embed-container tab-pane fade " id="upvidvostfr">
  | </div>
  | <div class="embed-container tab-pane fade " id="openload">
  | </div>
  | <div class="embed-container tab-pane fade " id="openloadvostfr">
  | </div>
  | <div class="embed-container tab-pane fade " id="streamango">
  | </div>
  | <div class="embed-container tab-pane fade " id="streamangovostfr">
  | </div>

**Comment by Kasper1n** [comment]
@yodidon 
Ton lien ne fonctionne pas

**Comment by yodidon** [comment]
LA non plus ?

**Comment by yodidon** [comment]
ça donne un lien comme ça je crois
h-t-t-p://malcolm-strea-ming.com/lecteur/16/?id=mystream

**Comment by Kasper1n** [comment]
@yodidon
@sizanic 

Non malheureusement c'est pas la bonne structure

**Comment by yodidon** [comment]
Ha ok bah ça marche chez moi , j’ai du avoir de la chance ...

**Comment by Kasper1n** [comment]
ça me revoit à la page de l'épisode mais cela ne lance pas la lecture

**Comment by yodidon** [comment]
Ça oui bien sûr il faut ensuite le passer dans la moulinette des hoster de vstream, par exemple mystream est gérer par vstream ( dans le dossier des hoster)

**Comment by yodidon** [comment]
Si tu regarde avec l’outil développer =>network de chrome (ou autre) tu verras le dérouler dès acquisition des url

**Comment by sizanic** [comment]
Lorsque tu arrives sur la page d'un épisode, prenons par exemple l'épisode 17 de la saison 4.
`sEpisodeURL = 'http://malcolm-streaming.com/saison-4/episode-17/le-testament-impossible'`

Tu recherche cette partie dans la page (c'est à la fin) : 

```
searchCacheInit();
      ajaxTab("/lecteur/81/?id=","#mystream", null);
```

Avec ça tu construis cette url : 
`sUrl = 'http://malcolm-streaming.com/lecteur/81/?id=mystream'`

Tu dois appeler cette URL, mais en passant l'url de l'épisode dans le rerefer : 

```
        oRequestHandler = cRequestHandler(sUrl)
        oRequestHandler.addHeaderEntry("Referer", sEpisodeURL)
        sHtmlContent = oRequestHandler.request()
```

sHtmlContent va te retourner ceci : 

`<IFRAME SRC="https://embed.mystream.to/l2arvy5beit5" allowfullscreen="true"></IFRAME>`

Il te restes à récupérer le sHosterURL avec un SRC="(.+?)"

**Comment by Kasper1n** [comment]
@sizanic  merci pour toutes ces précisions

Mais je ne vois pas cette partie dans la config de base  Mamcin `oRequestHandler.addHeaderEntry("Referer", sEpisodeURL)`

C'est dans quelle fonction ?

**Comment by TmpName** [comment]
C'est une option necessaire dans ce cas, dans le code de base on fait juste
```
        oRequestHandler = cRequestHandler(sUrl)
        sHtmlContent = oRequestHandler.request()
```

**Comment by yodidon** [comment]
C’est lier à la config de ton site

**Comment by sizanic** [comment]
> Mais je ne vois pas cette partie dans la config de base Mamcin `oRequestHandler.addHeaderEntry("Referer", sSaisonURL)`

C'est dans showHoster( ) que tu dois ajouter cette ligne.
Le probleme c'est que tu n'as plus l'URL de base à ce moment-là.
Tu dois donc la passer en paramètre
`            oOutputParameterHandler.addParameter('referer', sUrl)`

Et la récupérer ensuite.
`    sSaisonURL = oInputParameterHandler.getValue('referer')`

(c'est l'url de la saison qu'il faut)

Des exemples dans les sources : 
streamavie
filmstreamvk_com
zustream

**Comment by sizanic** [comment]
J'ai mis à jour le fichier exemple : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_une_source.py

**Comment by Kasper1n** [comment]
Bonjour à tous,


J'essaye mais sans succés, je dois faire n'importe quoi pouvez-vous svp me dire là ou je suis planté.
Je n'ai travaillé que sur la base d'un épisode pour comprendre (cf.Url utilisée)

https://pastebin.com/raw/mAs5MyxP

L'histoire du Refere me pose problème ainsi que la concaténation de l'Url de l'épisode pour l'envoyer dans la fonction du hoster.

**Comment by TmpName** [comment]
Encore un exemple.

Je t'ai mis la fonction VSlog() qui permet d'afficher des trucs en log, pratique pour sy retrouver.

Puis je suis parti de ce regex https://regex101.com/r/uLXXAd/1

Pour arriver a ce code https://hastebin.com/xomijuvala.py

Now ca affiche une liste d'episode avec leur image.

**Comment by Kasper1n** [comment]
@TmpName 
Merci pour ton aide.

Quelqu'un peut me préciser comme faire parler la fonction Vlog il faut un environnement de dev ou je peux y acceder dans vstream?

**Comment by sizanic** [comment]
vLog ajoute les infos dans le fichier de log de KODI, qui se trouve ici : 
C:\Users\UserName\AppData\Roaming\Kodi\kodi.log


Sinon, si tu te le sens, le tuto pour mettre en place un environnement de dev est ici : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki

**Comment by yodidon** [comment]
Je ne peux que te conseiller le lien de @sizanic  qui a considérablement fait évoluer le dev

**Comment by yodidon** [comment]
Au pire yodidon#6057 si je peux aider

**Comment by Kasper1n** [comment]
@yodidon 
Merci je vais suivre le lien à quoi sert l'ID yodidon#6057
Désolé je découvre Github?

**Comment by yodidon** [comment]
Pseudo discord

**Comment by yodidon** [comment]
> Lorsque tu arrives sur la page d'un épisode, prenons par exemple l'épisode 17 de la saison 4.
> `sEpisodeURL = 'http://malcolm-streaming.com/saison-4/episode-17/le-testament-impossible'`
> 
> Tu recherche cette partie dans la page (c'est à la fin) :
> 
> ```
> searchCacheInit();
>       ajaxTab("/lecteur/81/?id=","#mystream", null);
> ```
> 
> Avec ça tu construis cette url :
> `sUrl = 'http://malcolm-streaming.com/lecteur/81/?id=mystream'`
> 
> Tu dois appeler cette URL, mais en passant l'url de l'épisode dans le rerefer :
> 
> ```
>         oRequestHandler = cRequestHandler(sUrl)
>         oRequestHandler.addHeaderEntry("Referer", sEpisodeURL)
>         sHtmlContent = oRequestHandler.request()
> ```
> 
> sHtmlContent va te retourner ceci :
> 
> `<IFRAME SRC="https://embed.mystream.to/l2arvy5beit5" allowfullscreen="true"></IFRAME>`
> 
> Il te restes à récupérer le sHosterURL avec un SRC="(.+?)"

@sizanic  je n'arrive pas a comprendre pourquoi il faut utiliser le referer dans ce cas .

![CaptureB](https://user-images.githubusercontent.com/39896943/82162388-5963e980-98a4-11ea-80c6-494194e4fbda.PNG)
![CaptureA](https://user-images.githubusercontent.com/39896943/82162397-67196f00-98a4-11ea-84cd-683c262537b3.PNG)

**Comment by sizanic** [comment]
Lorsque tu copies l'URL ../lecteur/151/.. (de ta deuxieme image) et tu la colles dans un navigateur, tu n'auras pas la response de la premiere image. Ton URL est refusée car il manque une information.

Par le copier/coller, tu a changé le contexte de l'URL. C'est comme ça qu'on teste s'il manque des infos pour appeler une url.

**Comment by yodidon** [comment]
Exact oui, mais pourquoi referer alors ? j'ai du mal a comprendre l'utilisation de referer en fait

**Comment by sizanic** [comment]
Lorsque tu arrives à l'adresse ../lecteur/151/ le serveur WEB en face qui doit te répondre va te demander d'où tu viens. C'est ce que tu indiques dans le referer.

C'est une sorte de protection, tu dois montrer patte blanche.
Il veut vérifier que tu es arrivé ici en passant par une certaine page web.

**Comment by yodidon** [comment]
Ha ok je comprend le pourquoi 👍 donc si je récupère le referer de la page de l’épisode alors il pense que j’ai bien suivi le cheminement des url

**Comment by yodidon** [comment]
j'ai compris l'idée mais ça ne fonctionne pas quand je met  l'url de l'épisode dans le rerefer .
pas de host trouvé (a part face book...)

**Comment by sizanic** [comment]
Ca se voit déjà dans le sHtmlContent que tu n'a pas le bon résultat.

Ca veut dire que le referer n'est peut-être pas suffisant.


![CaptureA](https://user-images.githubusercontent.com/39896943/82162397-67196f00-98a4-11ea-84cd-683c262537b3.PNG)

Quand tu es ici, déroule bien le Headers jusqu'au Request Headers pour être sur des parametres à passer. Faut peut-être passer en plus le User-agent.


![image](https://user-images.githubusercontent.com/47307622/82164531-6804cd80-98b1-11ea-8ac8-a8d9165ed6b8.png)

Va voir la source MesFilms pour l'exemple.

**Comment by yodidon** [comment]
@sizanic merci tu viens de me faire comprendre , je me suis dû coup documenté, et j’ai enfin saisi ce que cela entraînait dans la constitution de la page. J’y étais pas du tout sur le referer et le header.
C’est plus clair et plus intéressant que de faire un copier coller , cool 👍 merci

**Comment by yodidon** [comment]
Encore merci pour tes explication @sizanic 
![referer](https://user-images.githubusercontent.com/39896943/82203194-43d1dc80-9903-11ea-8afd-2d2c00b5ed89.PNG)

**Comment by Kasper1n** [comment]
Salut à tous,

@yodidon 
@sizanic 

Je viens d'installer l'environnement de dev,mais je rencontre pas mal d'erreurs visiblement liées aux imports de librairies.


`Traceback (most recent call last):
  File "C:\Kodi\addons\plugin.video.vstream\resources\sites\Malcolm_VF.py", line 5, in <module>
    from resources.lib.gui.hoster import cHosterGui
  File "C:\Kodi\addons\plugin.video.vstream\resources\lib\gui\hoster.py", line 4, in <module>
    from resources.lib.gui.gui import cGui
  File "C:\Kodi\addons\plugin.video.vstream\resources\lib\gui\gui.py", line 4, in <module>
    from resources.lib.gui.guiElement import cGuiElement
  File "C:\Kodi\addons\plugin.video.vstream\resources\lib\gui\guiElement.py", line 4, in <module>
    from resources.lib.comaddon import addon, xbmc
  File "C:\Kodi\addons\plugin.video.vstream\resources\lib\comaddon.py", line 4, in <module>
    import xbmcaddon, xbmcgui, xbmc
ModuleNotFoundError: No module named 'xbmcaddon' `

Vous avez une idée pour résoudre ça ?

**Comment by milkibreizh** [comment]
bonjour
désolé je m'incruste
 @Kasper1n 
j'ai eu le même problème que toi mais tu dois peu être démarrer le remote debugger
(start debug server) et lancer kodi et ne pas essayer de lancer le debuger interne
ne pas oublier la fenêtre de debug.

Moi ca marche nickel en suivant la procédure "a la lettre" de sizanic
sauf l'emplacement de la lib "Lib\pysrc" si tu est en 32 ou 64 
C:\Program Files\Kodi\.......


bon après je n'ai jamais codé et je voulais commencé par le python....
mais je crois que je vais revenir à de chose plus simple du genre "hello world"
 
Un grand merci à toute l’équipe pour ce formidable addon

**Comment by Kasper1n** [comment]
@milkibreizh
J'ai essayé par contre dans mon fichier defaut.py je n'ai pas 'Remote_DBG' mais juste 'DEBUG'

C'est normal

**Comment by sizanic** [comment]
> je n'ai pas 'Remote_DBG' mais juste 'DEBUG'

Exact, je n'ai pas mis à jour le tuto après une  modif du code.

Je viens de le faire, merci pour l'info.

**Comment by sizanic** [comment]
> je rencontre pas mal d'erreurs visiblement liées aux imports de librairies.

Tu n'as ce problème que dans la source Malcolm ?

Sinon, vérifie bien le chemin de ton projet (étape 7).

**Comment by Kasper1n** [comment]
> > je rencontre pas mal d'erreurs visiblement liées aux imports de librairies.
> 
> Tu n'as ce problème que dans la source Malcolm ?
> 
> Sinon, vérifie bien le chemin de ton projet (étape 7).

Non au lancement du debug (en cliquant sur le cafard).

J'ai désormais les erreurs suivantes :


`pydev debugger: starting (pid: 6996)
Traceback (most recent call last):
  File "C:\****\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevd.py", line 3129, in <module>
    main()
  File "C:\****\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevd.py", line 3122, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\****\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevd.py", line 2195, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\****\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevd.py", line 2202, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\****\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\****\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 5, in <module>
    from resources.lib.gui.hoster import cHosterGui
  File "C:\****\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\hoster.py", line 4, in <module>
    from resources.lib.gui.gui import cGui
  File "C:\****\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\gui.py", line 4, in <module>
    from resources.lib.gui.guiElement import cGuiElement
  File "C:\****\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\guiElement.py", line 4, in <module>
    from resources.lib.comaddon import addon, xbmc
  File "C:\****\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\comaddon.py", line 4, in <module>
    import xbmcaddon, xbmcgui, xbmc
ModuleNotFoundError: No module named 'xbmcaddon'`

**Comment by yodidon** [comment]
Tu es sur quel os ?

**Comment by milkibreizh** [comment]
bonjours 
@sizanic 
Remote_DBG ou DEBUG
il faut mettre Remote_DBG !
moi ca marche avec DEBUG ou Remote_DBG 
je change juste le nom de la variable

si je mets DEBUG j'ai l'impression que cela marche...cela as un incidence sur les autres modules ?

@Kasper1n 
je ne clique pas sur "le cafard AVEC UN P" car je suis bigleu et mes icones sont tout riquiqui

menu> pydev->start debuger server

**Comment by sizanic** [comment]
C'est le tuto qui n'était pas à jour, il ne faut pas modifier le nom, et laisser DEBUG.
(changer le nom n'aura pas d'influence sur les autres modules).

@Kasper1n 
Est-ce que dans le chemin de tes fichiers (là où tu a mis des étoiles) tu n'aurais pas un nom avec un accent ?

**Comment by sizanic** [comment]
@yodidon 
j'ai ajouté deux petites astuces à la du tuto 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Debugger-avec-Eclipse

**Comment by milkibreizh** [comment]
@sizanic
Merci pour le renseignement
bonne nuit à tous et bon courage

**Comment by yodidon** [comment]
> @yodidon
> j'ai ajouté deux petites astuces à la du tuto
> https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Debugger-avec-Eclipse
Oui j’avais machinalement fait ces manipe, faut dire que je n’arrête plus d’utiliser eclipse c’est vraiment l’outil le plus bénéfique pour la compréhension

**Comment by Kasper1n** [comment]
Salut à tous,

@sizanic 
@yodidon 


Tant qu'on est dans la complétion du tuto debugger avec eclipse.

Je pense utile d'ajouter quelques lignes sur l'erreur lié à l'interpreter au moment de la création du projet.

**Comment by sizanic** [comment]
Je ne me souviens pas d'erreur à la création de mon projet.

Quelles erreurs as-tu eu ?

**Comment by Kasper1n** [comment]
`Projet interpreter not found`

**Comment by milkibreizh** [comment]
Salut 

j'ai des erreurs semblables a Kasper1n 20 mai 2020 17:19
Mais j'arrive comme même a debugger et à mettre des points d’arrêt sur les modules du répertoire site

par  exemple l'erreur
 File "C:\Users\dams\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 5, in <module>
    from resources.lib.gui.hoster import cHosterGui
correspond à une erreur dans le module lié a l'impossibilité d'importer xbmc

179
180        xbmc.executebuiltin('Container.Refresh')
181

dans le module
resources.lib.comaddon j'ai
import xbmcaddon, xbmcgui, xbmc
avec comme indication 
Unresolved import: xbmc    et aussi xbmcgui  xbmcaddon

+erreur aussi lié à xbmcplugin

Mais j'ai cru que c’était normal en pensant que seul l'application KODI connait ces libraires et pas l’interprétateur python.

https://kodi.wiki/view/HOW-TO:Debug_Python_Scripts_with_Eclipse
j'ai tenté sans succes
2.3.5 Setting up Predefined Completions (optional)
mais pas tenté
3.4.2 Modify PyDev source in order to support XBMC paths
avec pydevd_file_utils.py 

je dis juste cela pour info car j'ai du faire une bourde quelque part 
étant donné que personne n'as de souci pour importer les lib xbm

ps: désolé d’être hyper bavard et non concis

**Comment by sizanic** [comment]
> "C:\Kodi\addons\plugin.video.vstream\resources\lib\gui\hoster.py", line 4, in <module> from resources.lib.gui.gui import cGui File "C:\Kodi\addons\plugin.video.vstream\resources\lib\gui\gui.py", line 4, in <module> from resources.lib.gui.guiElement import cGuiElement File "C:\Kodi\addons\plugin.video.vstream\resources\lib\gui\guiElement.py", line 4, in <module> from resources.lib.comaddon import addon, xbmc File "C:\Kodi\addons\plugin.video.vstream\resources\lib\comaddon.py", line 4, in <module> import xbmcaddon, xbmcgui, xbmc ModuleNotFoundError: No module named 'xbmcaddon'

En effet, je n'y prétais plus attention, mais ces erreurs existent.
1 - Il ne faut pas en prêter attention
2 - je vais ajouter une note dans le tuto


> Projet interpreter not found

Alors ça par contre, ça à l'air plus grave.

**Comment by Kasper1n** [comment]
> Projet interpreter not found

> Alors ça par contre, ça à l'air plus grave.

@sizanic 
Pas forcément, c’est juste qu’à l’étape 5, il faut aller chercher l’exécutable du répertoire de l’installation et non l’exécutable d’installation.

C’est précisé mais peut-être pas assez je me suis fait piégé 😅

**Comment by milkibreizh** [comment]
@sizanic 

Bon bah c'est super rassurant car j'étais encore en train de trouver une solution
improblable.
car sur certains point de débogage j'étais ennuyé 

j'ai modifié le fichier pydevd_file_utils.py
comme indiqué en 
3.4.2 Modify PyDev source in order to support XBMC paths
mais cela n'as rien changé et j'ai pas eu de bug sur ce fichier


Du  coup je ne peux pas tout déboguer

Par exemple dans la classe home

  class cHome:
     addons = addons

     def load(self):

         oGui = cGui()

bp>        if (addons.getSetting('home_update') == 'true'):

.....
 je ne connais pas la valeur addons.getSetting('home_update')
mais je sais quelle valeur elle a après évaluation au breakpoint (c'est mieux que rien)
bon après cela n'as trop d'importance car je suis de toute façon
largué dans le code..
mais je voulais savoir surtout comment marchais  en gros
le traitement des fichiers sites par le programme

j'étais intéressé pour faire les sites que j'utilise sur firefox 
https://wwv.enseries.io
https://wvw.streamingdivx.club/
https://wwv.filmgratuit.net/
et
enstream mais vous le faites
mais voilà 2 semaines que cloudfare s'en mêle 
je sais pas ce qui s'est passé mais ils on tous décidé de passer par  cloudfare 

bon bah comme toujours je radote et j'en profite donc pour
souhaitez un grand merci à tout l'équipe qui consacre son temps
à nous donner du bon temps.

bonne nuit

**Comment by sizanic** [comment]
> Par exemple dans la classe home
> 
> class cHome:
> addons = addons

**MAIS QU'EST CE QUE TU FAIS LA !!!**


Tu t'es complètement perdu. 😆 

Suis cette procédure : 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source


Tu dois juste créer un fichier qui porte le nom de ton site (ex : filmgratuit.py) que tu places dans le dossiers "resources/sites" de vStream. et c'est seulement dans ce fichier que tu mets tes points d’arrêts.

Ne t'occupes pas des autres fichiers !

Par contre la première étape c'est bien de vérifier si on ne fait pas déjà ces sites.

Bien vu pour enstream.
Mais streamingdivx également.

**Comment by milkibreizh** [comment]
bonjour

oui ,j'ai fait fait une bourde en effectuant une recherche dans le répertoire site
avec le mot clef streamingdivx.club et non streamingdivx

**Comment by sizanic** [comment]
@Kasper1n 
tu en es où de ta source Malcolm ?

**Comment by LordVenom** [comment]
Aucune réponse de @Kasper1n la prochaine fois envoyer au Wiki trop de temp pour rien c'est déprimant.
