### ISSUE TITLE
Ameliorer le repo

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2910]
Bon j'arrive pas a faire un truc fonctionnel mais bon.
Vstream est maintenant capable d'utiliser un serveur dns, mais il faut pouvoir installer une lib speciale.
Donc pour faciliter le truc, j'ai essaye de la rajouter au repo de Vstream, sans succés

https://kodi-addons.club/addon/script.module.dnspython/

En passant je suis tombé sur la version kodi de la lib de venomous, celle la aussi du coup pourrait etre rajoutée

**Comment by razorex** [comment]
@TmpName Tu veux mettre le zip de dns python dans le zip du repo vStream??

**Comment by sizanic** [comment]
Non, il a essayé un import depuis un fichier addon.xml.

@TmpName peux-tu nous remettre ici le code que tu a essayé.
Je pense que c'est la bonne piste.
Tu a du faire un revert, il n'y a même plus la trace dans l'history.

On va essayer de regarder.

**Comment by razorex** [comment]
Je me doutais mais je posais tout de même la question..

**Comment by TmpName** [comment]
Il y a un de mes tests ici https://github.com/Kodi-vStream/venom-xbmc-addons/blob/32c0cdd9fc4e5ed88a8f0d31b58b138554c37e3d/repository.vstream/addon.xml

Le copier/coller vient d'un autre repo ou ca marche.

Mais j'ai essayé en local surtout, au mieux aucune difference, au pire le repo disparait de kodi.

Et pour le coup du zip, je sais pas, normallement on peut utiliser le lien officiel, pas besoin de l'avoir chez nous.

**Comment by sizanic** [comment]
> Je pense qu'il y a un truc avec` <addon> et <addons>`

Je pense le contraire.
Tu dois avoir qu'une seule section addon, c'est la description de l'addon.

https://kodi.wiki/view/Addon.xml


Je verrais plutot l'utilisation d'une section \<requires> .

**Comment by sizanic** [comment]
Lorsque je regarde ces exemples : 

https://github.com/gnoling/kodi.addons/blob/master/addons.xml
https://github.com/irmu/arda/blob/master/_zips/addons.xml

je pense que tu as mal décris l'addon à importer.
Il manque les chemin vers le git de CS

les sections 
```
<info 
<checksum 
<datadir zip=
```

**Comment by TmpName** [comment]
Ben je trouve pas de tuto clair. Je ne sais pas les champs obligatoire ou pas.
Le code que j'ai c/c viens d'un repo fonctionnel.

Par exemple le checksum, pas sur que ce soit obligatoire.

**Comment by TmpName** [comment]
Amelioré par @Ovni-crea
