### ISSUE TITLE
MAJ des Liens

### ISSUE THREAD

**Issue by AxelGwa** [Kodi-vStream/venom-xbmc-addons#2912]
Bonjour

J'utilise Vstream sur Kodi Leila sous Windows 7 et depuis quelques temps Vstream ne me propose plus au lancement la maj des liens (en vert dans la liste habituellement)

Peut-on le faire manuellement ? ou est-ce normal car il n'y a pas eu de maj dernièrement ?

Je suis en version 08 et à noter que la station est en permanence allumée avec Kodi lancée.

Merci

**Comment by TmpName** [comment]
La MAJ des liens ?
Tu parles de la mise a jour sur la homepage de Vstream ?

**Comment by AxelGwa** [comment]
Bonjour
Oui quand tu lance vstream il te propose la liste habituelle : films, recherches, outils ... etc  ... et en début de liste parfois il est proposé" mise à jour disponible" qui quand tu sélectionnes met à jour la suppression et l'ajout des liens.
ça fait un bon moment que je n'ai plus de mise à jour de proposé
Je ne parle pas de la mise à jour de Vstream en lui même

**Comment by TmpName** [comment]
Haa ok, alors ca c'est normal, c'est une mise a jour ponctuelle, qui n'est verifiés que tout les 4 jours et qui se declenche en cas de nouvelle beta, et comme il y a eu une grosse maj il ya 20 jours, ca n'a pas bougé depuis.

**Comment by sizanic** [comment]
Oui, depuis plusieurs mois, on n'a fait que des mises à jour Majeures qui s'installent toutes seules.
Pas de mises à jours intermédiaires qui nécessitent d'être lancées manuellement.

La 0.8.0 est bien la dernière.

**Comment by AxelGwa** [comment]
Ok merci pour la réponse rapide; je pensais avoir un pb d'installation.
Encore merci pour ce super AddOn qui fonctionne super bien et le travail de maj et de développement que vous faites dessus.
Pour info, résident aux Antilles, ç'est une alternative a une offre satellite / fibre hors de prix et très limitée.
