### ISSUE TITLE
j'ai besoin d'aide 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2913]
J'ai un problème sur `elif 're.zu-lien.com' in sHosterUrl:` à la ligne 434 j'arrive pas a faire fonctionner le code il y a que gounlimited qui fonctionne 
PS: j'ai testé le code individuellement et ça fonctionne 
![Capture d’écran (2)](https://user-images.githubusercontent.com/13500478/82126277-0444ac80-97ac-11ea-8454-5f903647e83c.png)

**Comment by TmpName** [comment]
La ligne 434 n'est jamais atteinte
Si tu as "re.zu-lien.com" dans le sHosterUrl c'est la ligne 411 qui est traitée, du coup la 434 n'est jamais atteinte.

**Comment by Ovni-crea** [comment]
@TmpName merci j'ai terminé maintenant
