### ISSUE TITLE
Connexion compte Time2Watch

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#2916]
Le site Time2Watch à l'air d'avoir modifié le fonctionnement de la connexion au site. J'ai commencer a corriger le problème, mais je n'arrive pas a comprendre ce qui manque pour réussir a se connecter.
Une choses est sure, il n'y a pas d'utilisation de js. Donc le problème doit ce situé au niveau du headers, mais je n'arrive pas a trouver l'origine du problème.
Si quelqu'un a une idée je suis preneurs.
Début de correction : https://github.com/Arias800/Fichier-divers/blob/master/test/time2watch.py

**Comment by sizanic** [comment]
perso, je suis pas trop dispo ...

@yodidon  tu maîtrises les headers maintenant, non ? :wink:

**Comment by yodidon** [comment]
@sizanic , maitrise c’est peut-être un grand mot mais j’ai compris le fonctionnement et surtout l’intérêt. Jusqu’à présent j’imaginais que le referer reprenait l’entièreté de la page précédant et j’avais du mal à comprendre l’intérêt de cette fonction, mais là la lumière c’est allumé et après quelque lecture sur le header et sont fonctionnement je comprend mieux ce que tu voulais dire par « ajouter le referer »

**Comment by yodidon** [comment]
@Arias800  Je n'ai pas rencontré de problème ? a quel moment il y a un souci

**Comment by lebigboss** [comment]
C'était toi @Arias800 lolll
![Screenshot_20200519-003733](https://user-images.githubusercontent.com/12912677/82266095-056f0880-9969-11ea-8fb0-71ea1541b799.jpg)

**Comment by Arias800** [comment]
@yodidon normalement Vstream doit tenter de se connecter a Time2 Watch qu'une seule fois, or la il tente de se connecter a chaque passage dans showMovies, ce qui montre que la connections échoue.
![image](https://user-images.githubusercontent.com/24809312/82290193-9b755400-99a6-11ea-9a11-0237e9aadf33.png)

**Comment by TmpName** [comment]
Il manquerait des cookies, moi de sauvegardé je n'ai que __cf_bm,  _t2w, __cfduid, si je n'utilise que ceux la, la connexion est a refaire.

**Comment by Arias800** [comment]
J'ai mis a jour le fichier du dessus avec les requêtes qui passe par RequestHandler, en récupérant et renvoyant les cookies a chaque fois, et en revérifiant les headers. Mais rien ne change, je comprends vraiment pas où ça bloque xD

**Comment by yodidon** [comment]
J’ai testé et j’ai eu l’impression que le token lors de la connexion ne correspondait pas. Je peux pas réessayer ce soir mais demain je regarde à nouveau

**Comment by TmpName** [comment]
Mais tu le vois dans Vstream ce cookie ?

Sinon j'ai pas fini mais
- j'ai corrigé un bug dans Vstream (Requesthandler) qui faisait sauter un cookie.
- Tu as une faute de frappe ici
`        data = 'username=' + ADDON.getSetting('hoster_time2watch_username') + '&pwd=' + ADDON.getSetting('hoster_time2watch_password') + "&token=" + aResult[1][0]`

Ensuite je pense qu'il faut faire un truc pr gerer les cookies, il fait choisir le bon cookie en cas de double, le dernier, et fusionner ceux de 2 requetes successive. Style dans Gestion cookie.

Et a mon avis faut faire 2 passes, une passes sans cookie, on recupere le token , deuxieme passe avec les precedent cookie et ce token.

**Comment by TmpName** [comment]
J'ai rajouté une fonction.
Now on peut faire

>Cookie = GestionCookie().MixCookie(Cookie,oRequestHandler.GetCookies())

Par contre j'ai pas regardé la reaction en cas de double cookie.

Coté code, j'obtien le coockie "last_url" mais toujours pas le bon.

**Comment by TmpName** [comment]
Et j'ai pas pu investiguer mais je pense qu'il faudrait bloquer la redirection aussi
la page "login" renvoit sur la page "last", et c'est la page "login" qui donne le bon cookie, pas "last"

**Comment by yodidon** [comment]
> Mais tu le vois dans Vstream ce cookie ?
> 
> Sinon j'ai pas fini mais
> 
> * j'ai corrigé un bug dans Vstream (Requesthandler) qui faisait sauter un cookie.
> * Tu as une faute de frappe ici
>   `        data = 'username=' + ADDON.getSetting('hoster_time2watch_username') + '&pwd=' + ADDON.getSetting('hoster_time2watch_password') + "&token=" + aResult[1][0]`
> 
> Ensuite je pense qu'il faut faire un truc pr gerer les cookies, il fait choisir le bon cookie en cas de double, le dernier, et fusionner ceux de 2 requetes successive. Style dans Gestion cookie.
> 
> Et a mon avis faut faire 2 passes, une passes sans cookie, on recupere le token , deuxieme passe avec les precedent cookie et ce token.

Non justement je le vois pas sur vstream

**Comment by Arias800** [comment]
Bon, finalement c'est bon. Ils ont modifier le système de connexion et cette fois ça passe sans poser de problème a Vstream.

**Comment by yodidon** [comment]
Ha ok je regarde ça m’intéresse
