### ISSUE TITLE
Vstream et IPTVSOURCE

### ISSUE THREAD

**Issue by weednbeer** [Kodi-vStream/venom-xbmc-addons#2917]
**Décrivez le bug**
Salut a tous! J'ai fait énormément de test pour ce foutu IPTV... Par enable et les 2 addons dans Kodi pour le stream... Rien a faire ça démarre JAMAIS... f4m load le proxy puis rien!!! Je suis désespéré

**Votre system**
 - OS: [Win10 XBOX ONE]
-  Appareil [XBOX UWP]
 - Version Kodi  [18.6]
- Version Vstream 0.8.0

**Nous devons le reproduire**

**Log**
Https://slexy.org/view/s21SZNIFI0

**Comment by razorex** [comment]
Oui plus grand chose fonctionne en iptv, manque de suivi, et malheureusement plus personne ne gère.
Quelque source fonctionne encore mais très peu. Tu recherche quel contenu???
Sport, tv???

**Comment by weednbeer** [comment]
Pas mal les deux... Les évènements quand il en a aussi :)

**Comment by Che-debarras** [comment]
Les iptv sont poursuivis pour illégalité plus sévèrement ces derniers temps d'où difficile de trouver des sites mises à  jour.
J'utilise ces 3 là :
https://iptvcat.com
https://ahlakid.com
https://www.iptvm3ulist.com/playlists/
https://iptvm3uplaylist.xyz/amp/

Le 1e est pas mal car on crée sa propre playlist

**Comment by sizanic** [comment]
Oui pour les chaines en iptv, vaux mieux passer par perfectPlayer.
KODI n'est pas très bien adapté, dès qu'il y a une microcoupure la vidéo s'arrete.

Et pour le sport, il y a la source "LiveTV", catégories "les matchs en directs" qui est encore mieux que IPTV.
C'est regroupé par sport, tu n'as pas à te soucier de la chaine. Dans l'esprit VOD de vStream !
Pour chaque retransmission sportive, plusieurs flux sont proposés, correspondant à plusieurs chaines (dont des chaines qu'on ne serait pas aller voir en IPTV).

ça ne propose que les sports qui ont des retransmissions de prévues (donc un peu vide en ce moment).
=> Et pas de coupures comme en IPTV !

(mais la qualité est souvent moins bien, et parfois c'est une chaine étrangère lorsque les flux iptv français sont saturés)

**Comment by weednbeer** [comment]
Ok moi je suis xbox one... Mode développeur j'essais beaucoup de chose comme IAGL que j'essais de incorporé a Kodi ... En version non store de Windows car bloqué pour les émulateurs en version original sur le xbox pour que Kodi reste sur le store... En tout cas perfect players est sûrement pas sur xbox lol

**Comment by Che-debarras** [comment]
> Ok moi je suis xbox one... Mode développeur j'essais beaucoup de chose comme IAGL que j'essais de incorporé a Kodi ... En version non store de Windows car bloqué pour les émulateurs en version original sur le xbox pour que Kodi reste sur le store... En tout cas perfect players est sûrement pas sur xbox lol... Je sais que le streaming n'a rien avoir avec le mode développeur

Vstreal fonctionne sur Xbox one S?

**Comment by Arias800** [comment]
Oui, ca fonctionnne sans probleme.

**Comment by sizanic** [comment]
Ce serait quand même dommage que KODI (et ses addons) ne fonctionne pas sous Xbox, vu qu'à l'origine c'est prévu pour Xbox.

Avant de s'appeler KODI lorsque que c'est passé en multi-plateforme, ça s'appelait XBMC car c'était développé pour Xbox (XBMC = XBox Media Center !) :smile:

**Comment by weednbeer** [comment]
Ouii je m'en rappelle!!!! Mais la seul.chose qui fonctionne moin ou pas ces justement le streaming et malheureusement les émulateurs... Ca deviendrais l'application parfaite pour xbox one.... J'essais de faire des test en mode développeur... Ces bien beau sur le store qui le mette pas avec les ému pcq Kodi veux rester sur le store mais en mode développeur on peux faire roulé les ému avec liberto et retroarch... Mais je tien à le faire rouler dans Kodi car  IAGL est magique et que tu a juste a téléchargé le ton direct ... Ya des video des jeux direct... En tout cas... Ca l'air fort... J'ai parler sur le Github direct de zachmorris(le addon IAGL) et je crois qui lui aussi travail la dessus mais pas sur.. le problème en xbox one ces que Kodi ne ouvre pas d'application en arrière plan... Et juste ça ça l'empêche tout je crois

**Comment by Che-debarras** [comment]
> Oui, ca fonctionnne sans probleme.

Merci  c'est bon a savoir.

**Comment by Arias800** [comment]
Bon je vient de jeter un œil et il s’avèrent que les sites d'iptv ne propose presque plus de liens fonctionnel, surement a cause de toutes les arrestation qui ont régulièrement lieux.

**Comment by weednbeer** [comment]
Surement! Dommage c'étais le complément de vstream lol.... Il devrait l'enlever tant qu'à ca

**Comment by Sphinxroot** [comment]
jai quelque liste sur mon git si ca peut interresser ;)

**Comment by Che-debarras** [comment]
> jai quelque liste sur mon git si ca peut interresser ;)

@Sphinxroot merci , si tu pouvez faire une liste special francophone (belgique France suisse canada algerie maroc tunisie) car les chaines internationales des différents pays c'est dure à gerer sur perfect player.

**Comment by Sphinxroot** [comment]
@Che-debarras  toute mes listes sont formater pour kodi alors pour ton player jai aucune idee du format utiliser ...  jai europe fr et francais monde qui a des channels d afrique ect  beaucoup ont des liens expirables ou sequentiels alors impossible pour le moment de les inclures dans une liste ou du moin jai pas encore trouver l astuce pour .

**Comment by Che-debarras** [comment]
> @Che-debarras toute mes listes sont formater pour kodi alors pour ton player jai aucune idee du format utiliser ... jai europe fr et francais monde qui a des channels d afrique ect beaucoup ont des liens expirables ou sequentiels alors impossible pour le moment de les inclures dans une liste ou du moin jai pas encore trouver l astuce pour .

Pour le player que j'utilise,  il utilise le même format même plus (m3u, xtreamcode,  serveur pc...).

Je sais que c'est pas evident l'iptv.

**Comment by LordVenom** [comment]
Aucune réponse de @weednbeer merci de rien.
