### ISSUE TITLE
Hentai Ianime.py

### ISSUE THREAD

**Issue by Fullpom** [Kodi-vStream/venom-xbmc-addons#2918]
Bonjour, pourriez-vous intégrer la catégorie hentai du site Ianime svp. Si vous ne le voulez pas pour une raison ou pour une autre, pourriez-vous m'expliquer comment faire sur mon propre anime.py (désolé je suis pas vraiment doué de base et je n'arrive pas a comprendre le code).
Merci

**Comment by Che-debarras** [comment]
Il faut plutôt intégrer les DRAMAS.

**Comment by Fullpom** [comment]
On sort du cadre du manga là mais bon, chacun ses goûts.
Ce qui serait génial, c'est de pouvoir le faire nous même mais je doute qu'il suffise d'1 ligne de code
J'ai déjà essayé et la gestion des genres "films" (ou c'est assez clair dans le .py)  n'est pas gérée pareil que les genres "animes"

**Comment by TmpName** [comment]
Ben il ya des chances que ca marche en changeant une seule ligne de code.
J'ai pas testé mais essayes deja en rentrant le liens dans un menu, en prenant example sur celui des series

**Comment by Fullpom** [comment]
J'ai essayé de différentes manières mais ça n'a jamais donné ce que je recherche c'est pourquoi je me tourne vers ceux qui savent.
Si je prend exemple sur les séries, j'arrive bien a rajouter un genre mais qui ne renvoie que du vide.

**Comment by yodidon** [comment]
Où est ton code ?

**Comment by Fullpom** [comment]
Désolé, je fait la modif en direct sur le ianime.py qui est stocké sur mon smartphone. Ça me permet de tester rapidement et de ne pas encombrer le github avec mes bidouilles qui ne fonctionnent pas de toute façon

**Comment by yodidon** [comment]
Tu peux pas le faire parvenir ?

**Comment by TmpName** [comment]
C'est pas au genre qu'il faut toucher
Regardes plutot les lignes 30 et 27

Et du coup la ligne 163 et l'autre

**Comment by Fullpom** [comment]
C'est super, ça marche en modifiant la ligne 27 ou 30 (je ne suis pas fan de séries de ce site de toute façon). Merci beaucoup.
Par contre, je ne vois pas le rapport avec la ligne 163 que je ne comprend pas vraiment mais bon, tant que ça marche. Merci encore

**Comment by Che-debarras** [comment]
@Fullpom 
Peux tu me dire comment tu as resolu le problème stp j'aimerais rajouter Dramas donc tu modifies quoi sur la ligne 27 ou 30?

**Comment by Fullpom** [comment]
En fait tu remplace lien soit des films soit des séries. Pour les séries, tu devra donc remplacer la ligne 30 par:
SERIE_SERIES = (URL_MAIN + 'drama.php?liste=' + RandomKey, 'ShowAlpha')
Bien sûr, a partir de là, tu n'a plus accès au séries mais il y a de meilleurs sites pour ça de toute façon.

**Comment by Che-debarras** [comment]
@Fullpom 
Tu modifies comment ce .py sur ton smartphone avec quel appli?
Si on ajoute cette ligne au lieu de la remplacer ça marche? Pour garder les séries ?

**Comment by Fullpom** [comment]
J'utilise ES explorateur de fichiers mais c'est juste un fichier texte donc facilement modifiable par n'importe quoi.
Je doute que tu puisses juste duppliquer la ligne. Vstream a l'air d'être basé sur film/series/anime et il faudrait revoir beaucoup de choses si tu veux en intégrer un 4e

**Comment by Che-debarras** [comment]
> J'utilise ES explorateur de fichiers mais c'est juste un fichier texte donc facilement modifiable par n'importe quoi.
> Je doute que tu puisses juste duppliquer la ligne. Vstream a l'air d'être basé sur film/series/anime et il faudrait revoir beaucoup de choses si tu veux en intégrer un 4e

Ok j'ai installer une appli qui permet d'éditer les fichiers py sur android
Et oui j'aimerais plutôt ajouter drama plutôt que de le remplacer. Merci pour ton aide

**Comment by yodidon** [comment]
Oui tu peux ajouter drama et ne pas supprimer le reste

**Comment by TmpName** [comment]
Ben oui lol, j'avais mis ces lignes pour prendre exemple (et rajouter un menu), pas pour les remplacer, c'est pour ca que tu n as pas eu besoin de copier la ligne 163.

**Comment by Che-debarras** [comment]
Une question pour ma curiosité.
J'ai réussi à avoir le menu Drama et son contenu mais je n'ai aucun lien dans le dossier d un drama
C'est dans quel ligne du code qu'il faut modifier ?

**Comment by yodidon** [comment]
Oui c’est la paterne qui est là même que catégorie, regarde if drama in url

**Comment by Che-debarras** [comment]
> Oui c’est la paterne qui est là même que catégorie, regarde if drama in url

J'ai pu prendre ton patch @yodidon mais il risque d'être remplacé si je met à jour la beta.
Donc est ce que ton patch sera inclus sur la version beta?

**Comment by yodidon** [comment]
Oui je le passerais sur la bêta
