### ISSUE TITLE
Drama sur iAnime

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2919]
Possible d'ajouter la categorie drama sur ianime?

**Comment by yodidon** [comment]
@Che-debarras je met le code avec drama sur la branch Yodidon patch 3( pas sur la bêta j’ai pas vérifier que j’avais la dernière version avant)

**Comment by yodidon** [comment]
J’ai mis à jour le code sur yodidon-patch-3 pour qu’il soit valide sur la version bêta

**Comment by razorex** [comment]
compare ton fichier avant le PR @yodidon

**Comment by yodidon** [comment]
J’ai pas fait de pr??

**Comment by razorex** [comment]
oui mais quand tu colle ton fichier tu peux voir les différence avant de pr.
s'il y a juste tes modifs c'est que tu avait la dernière version.

**Comment by yodidon** [comment]
Oui ça je sais effectivement, c’est pour ça que j’ai re modifier pour être ok avec la beta

**Comment by razorex** [comment]
exemple
![preview](https://user-images.githubusercontent.com/26149640/82592793-bcee5f80-9ba1-11ea-900a-dd3c9b7efdb5.PNG)

**Comment by yodidon** [comment]
Tu as vu que n truc qui cloche avec la version ?

**Comment by razorex** [comment]
non ce n'était qu'un exemple on a posté en même temp

**Comment by yodidon** [comment]
Ha ok tu me rassure 😜

**Comment by Che-debarras** [comment]
J'ai installé ta maj @yodidon pour drama mais les dossiers sont vides sans aucun lien host sauf pour le 1e drama en liste.
Est il possible d'avoir les dramas en liste alphabétique ?
Merci

**Comment by yodidon** [comment]
pourtant j'en ai essayer 2 ou 3 au hasard et ça fonctionnait. je regarde

**Comment by Che-debarras** [comment]
> pourtant j'en ai essayer 2 ou 3 au hasard et ça fonctionnait. je regarde

Sur ton git ça marche mais pas sur la version beta

**Comment by yodidon** [comment]
J’aurais oublié un truc, là je regarde et ça marche mais effectivement j’ai pas essayé avec la bêta je vérifie

**Comment by yodidon** [comment]
il y a eu une modif sur la beta ,la ligne 430, je crois que ça viens de la , je verifie et reviens vers toi

**Comment by yodidon** [comment]
si tu peux essayer la avec la modif faite sur la beta

**Comment by yodidon** [comment]
je pense que ça ne fonctionnera pas, je vais voir avec @sizanic , je crois que c'est lui qui a fait une modif sur les anime. voir si on met un solution intermédiaire ou s'il faut que je change la récupération des dramas

**Comment by Che-debarras** [comment]
> je pense que ça ne fonctionnera pas, je vais voir avec @sizanic , je crois que c'est lui qui a fait une modif sur les anime. voir si on met un solution intermédiaire ou s'il faut que je change la récupération des dramas

Mais les dramas ne sont pas des animés,  ils sont une categories a part comme film, serie, animé et une 4e drama ?
Vu le conseil avant de remplacer la ligne de code de Serie ou Animé. 

Ta dernière maj n'a pas fonctionné.
Merci pour ton aide

**Comment by yodidon** [comment]
lonsqu'on arrive a la section episode des drama, la base de l'url est la même que les manga

**Comment by Che-debarras** [comment]
> lonsqu'on arrive a la section episode des drama, la base de l'url est la même que les manga, et oui c'est le fichier gui.py qui a été modifié

Ok merci. 
Sinon tu sais si des sources peuvent être rajoutés ou l'équipe Vstream est déjà oqp avec les modifs py3 et cloudfare etc..? Car j'aimerais voir de nouvelles sources Drama comme Dramapassion dramacoreen et dramavostf , çà rajouterais de ma diversité a vstream surtout que otaku ou ianime ou adkami beug ou sont sans drama

**Comment by yodidon** [comment]
J’en ai ajouté une la semaine dernière , mais oui je peux regarder , je suis pas trop au point pour py3 et cloudfare

**Comment by sizanic** [comment]
Dans gui.py, j'ai créé un addAnim, qui est une copie de addTV.
La différence est lorsqu'on recherche les métaDonnées, on recherche les séries de type Animation.

Voici l'exemple avec ianime, dans la section "animés (Liste)", lettre "B"

Avec addTV :  
![image](https://user-images.githubusercontent.com/47307622/82711830-d4ebdf00-9c86-11ea-9c30-eef00c5787e7.png)


Avec addAnime : 

![image](https://user-images.githubusercontent.com/47307622/82711923-0d8bb880-9c87-11ea-9fdf-71885f22ea92.png)


J'ai remis addAnime pour les animes, et fais une modif spécifique pour les dramas.

**Comment by Che-debarras** [comment]
Avec asia insane on a le même souci aucun lien host pour les drama ou film...comme ianime

**Comment by sizanic** [comment]
Je viens de tester iAnime (Dramas), pour Prison school S01E01, j'ai 4 hosts (upstream, dood, streamz, gounlimited).
Pas toi ?

**Comment by yodidon** [comment]
Je re testerais , mais avec la modif sur gui, je n’ai plus accès au drama , mais peut être ais je pas tout remis j’essaie demain

**Comment by yodidon** [comment]
oups pas vu que tu avais fait une modif, merci

**Comment by Che-debarras** [comment]
J'ai testé la correction sur gui et ça ne résout pas le problème,  beaucop de drama sans host.

**Comment by sizanic** [comment]
> J'ai testé la correction sur gui

La modification sur gui n'est pas censée être une correction. Elle n'a rien à voir avec le problème ici. Il faut arrêt de citer gui dans ce sujet.


> beaucoup de drama sans host

Donc d'autres avec des hosts ?
Un exemple svp.
Les hosts sont présents sur le site ?

**Comment by yodidon** [comment]
@sizanic , pour gui c’est moi qui est induit en erreur , désolé, mais mes tests pour je ne sais quelle raison m’ont fait croire que c’était lié. Je referais ces tests pour revoir mon diagnostic

**Comment by Che-debarras** [comment]
> > J'ai testé la correction sur gui
> 
> La modification sur gui n'est pas censée être une correction. Elle n'a rien à voir avec le problème ici. Il faut arrêt de citer gui dans ce sujet.
> 
> > beaucoup de drama sans host
> 
> Donc d'autres avec des hosts ?
> Un exemple svp.
> Les hosts sont présents sur le site ?

Oui j'ai cité plus haut les exemples de  "Minna" ou le dernier de la 1ere page " l'amour des legendes" et bien d'autres, le hosts sont bien présents sur le site

**Comment by Che-debarras** [comment]
> > J'ai testé la correction sur gui
> 
> La modification sur gui n'est pas censée être une correction. Elle n'a rien à voir avec le problème ici. Il faut arrêt de citer gui dans ce sujet.
> 
> > beaucoup de drama sans host
> 
> Donc d'autres avec des hosts ?
> Un exemple svp.
> Les hosts sont présents sur le site ?

Oui les hosts sont présents mais je pense que les liens sont hs ce qui expliquerait pourquoi vstream les affiches tel que openload youwatch thevideo viki etc..

**Comment by razorex** [comment]
@sizanic c'est normal que tu n'ai pas les mêmes poster pour babylon??
surtout que moi j'ai çà!! pas d'année pas de sdesc..... et le poster du site.
![babyln](https://user-images.githubusercontent.com/26149640/82733830-fa282e00-9d16-11ea-9727-aa866d090d27.PNG)

**Comment by sizanic** [comment]
> pas d'année pas de desc..... et le poster du site.

ça c'est le comportement si tu n'actives pas les métadonnées.

**Comment by razorex** [comment]
oui du coup tu n'a pas toujours les bonnes info non????
Oui c'est vrai je n'utilise pas cette option.
Du coup je comprend mieux pourquoi tu tiens au meta. Tu te fais un vStream perso.

**Comment by Che-debarras** [comment]
> > pas d'année pas de desc..... et le poster du site.
> 
> ça c'est le comportement si tu n'actives pas les métadonnées.

Dis ton habillage est un truc perso ou on peut le ddl sur une source?

**Comment by sizanic** [comment]
> du coup tu n'a pas toujours les bonnes info non????

Si, c'est bon maintenant.

> ton habillage est un truc perso

Non, pas un habillage en particulier.
Rien qu'en utilisant Esturay, il y a un mode d'affichage "Fanart" : 

![image](https://user-images.githubusercontent.com/47307622/82738723-33be6080-9d3a-11ea-9a38-4d4e153fb457.png)


![image](https://user-images.githubusercontent.com/47307622/82738801-ca8b1d00-9d3a-11ea-9064-607728be645b.png)

![image](https://user-images.githubusercontent.com/47307622/82738820-f0182680-9d3a-11ea-8ae3-9d1dfdccd113.png)

**Comment by Che-debarras** [comment]
> > du coup tu n'a pas toujours les bonnes info non????
> 
> Si, c'est bon maintenant.
> 
> > ton habillage est un truc perso
> 
> Non, pas un habillage en particulier.
> Rien qu'en utilisant Esturay, il y a un mode d'affichage "Fanart" :
![82711923-0d8bb880-9c87-11ea-9fdf-71885f22ea92](https://user-images.githubusercontent.com/44464129/82740326-17c1bb80-9d48-11ea-8573-3870371077a0.png)

C'est plus cette présentation qui m'intéresse. Merci quand même.

**Comment by yodidon** [comment]
> dramavostf

**Comment by yodidon** [comment]
> j'aimerais voir de nouvelles sources Drama comme Dramapassion dramacoreen et dramavostf , çà rajouterais de ma diversité a vstream surtout que otaku ou ianime ou adkami beug ou sont sans drama
@Che-debarras  pourquoi pas, je propose que l'on ajoute dans le menu series (home) , un menu séries Dramas . Si c'est ok pour tous le monde , j'ai deja fais les modifs sur mon vstream et ça fonctionne. Je regarde les sites proposés et j'essai de les ajouter.
A voir si c'est utile, dites moi.

**Comment by razorex** [comment]
Asia Insane est corrigé.
Pour l'ajout dans le menu home, une règle avait cours il faut 4 source minimum.
pour info les dramas regroupe films et séries.

**Comment by yodidon** [comment]
Oui j’ai vue qu’il y avait des films aussi, à ce jour si on compte ianime asia insane et celui que je code dramavostfr ça ferait 3 sources , mais pas tous ont des films

**Comment by razorex** [comment]
Il faudrait aussi que tu traite, si c'est possible, le second hoster de Asia Insane (multiup)

**Comment by Arias800** [comment]
Pour le moment ne faites plus modif sur Asia Insane, car je suis entrain de faire beaucoup de modif sur le code, avec en autre la prise en charge de multiup.

**Comment by razorex** [comment]
ah tu a vu que je viens de PR dessus

**Comment by Arias800** [comment]
Oui j'ai fusionner les deux. C'est pour ca que je prévient car sinon ca risque d'etre compliquer de tout rassembler a chaque fois xD

**Comment by razorex** [comment]
Pour moi j'en reste la pour l'instant avec Asia

**Comment by yodidon** [comment]
Du coup vous êtes ok pour ajouter drama sur le menu home ? Je continue ?

**Comment by Arias800** [comment]
Je suis pas sur que ce sois utile de le mettre directement dans le menu Home. Car apres ca fait beaucoup d'element pour rien, je trouve qu'il y a deja beaucoup de chose sur le menu home xD

**Comment by yodidon** [comment]
Oui au départ j’étais parti pour le mettre en sous menu de série , mais je m’aperçois qu’il y a quelques films dans cette catégorie

**Comment by razorex** [comment]
C'est contradictoire avec ce que je viens de faire mais je voulais proposer une réorganisation des menus Qui allégerais le home.

**Comment by yodidon** [comment]
Comme vous voulez moi je suis, j’ai l’impression que les drames sont assez demandés . Je suis plutôt chaud pour avancer sur ce sujet car il me fait voir différents côtés de vstream

**Comment by razorex** [comment]
@Arias800 tu a Fusionner nos sources!!!!!! y a erreur je pense car les dramas c'est films et séries.

**Comment by yodidon** [comment]
@razorex c’est quoi ta direction sur les menus home

**Comment by razorex** [comment]
Films ==> on liste les sources
Selection d'une sources ==> accès au menu listant les sous menus films.
tu peux déjà le faire via sources mais c'est plus large.

**Comment by Arias800** [comment]
Après en sous menu, pourquoi pas ça ne me dérange pas. Par exemple dans le menu serie, rajouter une option drama.

Sur le site dans "Les Dramas" il n'y a que des séries. et pour info le terme "Dramas" est liée au série https://fr.wikipedia.org/wiki/Drama_(s%C3%A9rie) xD

**Comment by yodidon** [comment]
Oui je suis d’accord avec @Arias800 et d’où ma premiere idée de le mettre en sous menu de serie

**Comment by yodidon** [comment]
C’est d’ailleurs dans ce sans que j’ai dev , un sous menu dans serie

**Comment by yodidon** [comment]
@razorex je comprend pas bien , il faut peut-être que je sois devant vstream pour mieux comprendre

**Comment by razorex** [comment]
@Arias800  tu me la joue Bernard Pivot!!!

**Comment by Che-debarras** [comment]
Désolé de vous embêter avec ça mais ya t'il moyen que vous mettez une option pour désactiver les films et series porno érotiques adulte ? ( genre un tag de ces catégories qu'on pourrait filtrer dans les paramètres svp)

Vstream est un bon outils familial mais avec ce genre de video, le contrôle parenrale est necessaire.

Merci de votee compréhension

**Comment by yodidon** [comment]
Pour ma part quand il y a ce type de catégories je ne l’es ajoute pas

**Comment by Che-debarras** [comment]
> Pour ma part quand il y a ce type de catégories je ne l’es ajoute pas

Il s'y sont maintenant, après chacun ses goûts mais au moins laisser la possibilité de désactiver ces genres de videos (adulte, erotic, hentai et ecchi, gay..)

He pense que mettre des dessins animés pour enfants et ce genre de contenu adulte c'est contradictoire.

Je suis sûr qu'il y a des addons spécialisés et je trouve que cela nuirait à l'image de vstream de se lancer dans ce genre mais si ya un contrôle parental ça plairas aux parents

**Comment by sizanic** [comment]
> Je suis sûr qu'il y a des addons spécialisés et je trouve que cela nuirait à l'image de vstream de se lancer dans ce genre mais si y a un contrôle parental ça plairas aux parents

Bien sûr qu'il y a des addons spécialisé ( :smiling_imp: pour ceux qui comprendront la référence).

Et vStream ne se lancera pas dans ce genre !
Même avec un controle parentale.

Je ne connais pas les dramas mais je retrouve bien ces catégories (erotic, hentai, ecchi) dans les animes, si c'est à ça que tu fais référence.

Et je suis d'accord avec toi, ça ne va pas, trop accessible !! 

Il faudrait proposer quelque chose.

**Comment by Che-debarras** [comment]
@sizanic 
Les dramas c'est juste l'autre nom pour series tv asiatiques,  tout comme les mangas sont les dessins animés asiatiques
Ces dramas mettent plus l'accent sur l'intrigue et le scenario et moins sur les actions physiques entre les personnages.

Et oui c'est dans les animés que ces genres pour adultes sont apparus depuis les maj pour py3 et amelioration.

J'y connais pas trop mais il suffit pas de retirer les lignes de codes qui les faits affichés ou tagué ces dossiers d'un  "+18" que vstream pourra désactiver l'affichage dans les paramètres vu qu'on peut désactiver une source ne peut on pas désactiver ces genres?

Sinon oui trop accessible, car si on cherche un genre particulier les gosses seront tentés de cliquer sur ces genres inappropriés et là le drame arrivera

**Comment by yodidon** [comment]
Je n’ai pas tester mais es que lors des recherche ils n’apparaissent pas non plus ? Sinon c’est la galère

**Comment by Arias800** [comment]
Alors si jamais c'est liée au catégorie alors oui c'est possible. 
Par contre si c'est le site qui en propose tout seul et qu'il n'y a pas de filtrage de base alors ca risque d'etre compliquer.
Tu aurai un exemple de source oà il y a du contenu +18 pour voir ce que l'on peu mettre en place ?

**Comment by yodidon** [comment]
Moi je pense que le plus simple est de bannir toutes source qui afficheraient des éléments non souhaitables sans qu’on puisse en avoir le contrôle (je pense pas qu’il y en ait), en général sur ce que j’ai pu voir , elles sont rengées dans une catégorie bien spécifique et ne débordent pas sur les autres catégories, seul choses que je n’ai jamais testé est sur les recherches, apparaissent elles ? Je vais essayé quelque tests .

**Comment by Arias800** [comment]
Oui normalement c'est classifié, c'est même rare que ce sois sur des sites non spécialiser. C'est pour ca que si ca n'apparait pas sur les recherche alors c'est possible. Ou alors si ca apparait sur les recherches ont récupère les genres et ont filtres les genres.

**Comment by yodidon** [comment]
Oui récupération du genre et filtrage en fonction

**Comment by Arias800** [comment]
Oui, faut juste que les genres sois cohérent et bien mis a jour.

**Comment by Che-debarras** [comment]
> Oui normalement c'est classifié, c'est même rare que ce sois sur des sites non spécialiser. C'est pour ca que si ca n'apparait pas sur les recherche alors c'est possible. Ou alors si ca apparait sur les recherches ont récupère les genres et ont filtres les genres.

Il ne sont pas apparus sur les recherches globale en tout cas

**Comment by yodidon** [comment]
Bon bonne nouvelle , donc on ajoute alors ?

**Comment by Che-debarras** [comment]
Visiblement  c'est corrigé les genres adultes on disparu sur asian insane (il porte bien son nom lol) j'aurais aimé aussi désactiver Ecchi dans iAnime mais c'est peut-être trop demandé

**Comment by LordVenom** [comment]
> Possible d'ajouter la categorie drama sur ianime?

La question est comment tu peux le faire, pas si nous ont peux le faire.
