### ISSUE TITLE
Information concernant cloudflare 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2920]
Je voudrais savoir est ce que c'est résolue les problèmes de cloudflare parce que je code un site et j'ai une erreur cloudflare et avec tout les issues ouvert je me perds facilement ^^

**Comment by yodidon** [comment]
non pas encore

**Comment by Che-debarras** [comment]
Est ce que tous ces maj Py3 signifie que vstream est ou sera bientôt compatible Kodi 19?

**Comment by razorex** [comment]
Non pas encore @Che-debarras , c'est le plus facile qui viens d’être fait.
