### ISSUE TITLE
Problème sur vstream et souci premium

### ISSUE THREAD

**Issue by kaim71** [Kodi-vStream/venom-xbmc-addons#2921]
Salut à toute l équipe j espère que tout le monde va bien et est en bonne santé.( un revenant)
Salut venom et tpname
J ai remarqué 2 choses qu il y a un conflit avec uptobox même avec mon compte premium, les liens ne s ouvrent plus uptostream pareil.
Les sources les plus connus sont obsolètes. 
Sous Windows et android
Je voulais juste savoir si c normal et aussi il y a au moins 2 mois que les mises à jours ne s affichent plus peut être est ce la raison.
Big up à toute l equipe.

**Comment by TmpName** [comment]
Hello, alors tu as le compte rendu ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2889 mais en bref
- Gros probleme avec cloudflare.
- up2strm et up2box fonctionnent au moins sans premium, avec, je sais pas, il y a une issue dessus si tu veux donner des infos.
- La derniere grosse MAJ a un peu moins d'un mois.

**Comment by kaim71** [comment]
Merci pour ta reponse 
Le message vient que vstream ne reconnait pas uptobox.
Je vais te mettre une capture d ecran

**Comment by kaim71** [comment]
![Screenshot_20200522-203717_Kodi](https://user-images.githubusercontent.com/65750288/82699189-731e7b80-9c6c-11ea-9026-73709fee01f1.jpg)

**Comment by kaim71** [comment]
Erreur connexion 503 htt

**Comment by yodidon** [comment]
Erreur cloudfare

**Comment by kaim71** [comment]
Et des fois il met uptostream rate

**Comment by TmpName** [comment]
Je pense que @yodidon a raison, le nom est en orange, tu es encore sur le site.
Si tu etais sur le lien final le nom serait en bleu (streaming) ou rose (DL)

**Comment by Che-debarras** [comment]
Ya le meme souci sur asia insane sauf qu'il y a pas d'erreurs 503 mais lien absent vide

**Comment by yodidon** [comment]
Pour Aqua j’ai pas trop cherché, juste fait. Un truc fonctionnel

**Comment by kris06** [comment]
Salut TmpName  et tous le monde,

Mon projo embarque une interface Android 6.0 Version GMUI : 3.2.0 et qui produit des ralentissements et des blocages sur kodi 18(1.2.3.4.5.6.7)
 
J’ai voulu tester la nouvelle mise à jour 18.7 mais le problème reste identique.
Je dois repasser sur kodi 17.6 qui fonctionne parfaitement, mais il me faut rapatrier 
Le contenu de mon « Marque pages »   Aurais-tu la gentillesse de me m’indiquer le chemin de ce fichier ou dossier, je ne l’ai pas trouvé… ? 

Par ailleurs, pourrais-tu/vous/ réactiver dans votre prochaine mise à jour, la source Pirvox ?
En espérant retrouver également à cette occasion, la remise en service de Zone téléchargent  -  ZT stream et tirexo.

Je te remercie
kris

**Comment by TmpName** [comment]
Pirvox est toujours la > kepliz

Tu parles des marques pages de vstream (userdata\addon_data\plugin.video.vstream\vstream.db) ou de kodi ?

**Comment by kris06** [comment]
Kepliz est la en effet mais ne fonctionne plus depuis quelques jours 

Je parle du marques pages de kodi celui ou l'on enregistre les films â partir des sources dans le sous menu qui apparaît  en appuyant long sur ok de la telecommande. Voir capture ecran jointe
![Screenshot_20200524-144833_Kodi](https://user-images.githubusercontent.com/31409100/82754554-d70c8580-9dcd-11ea-8d79-e857af0387d3.jpg)

**Comment by kris06** [comment]
Si je réinstalle kodi 17 je vais perdre tout le contenu enregistré dans mon marque pages.

**Comment by Wolsey20** [comment]
Bonjour,

j'ai aussi le problème avec uptostream premium qui ne marche pas (erreur : Fichier introuvable) mais quant je désactive mon compte uptobox premium tout remarche j'ai bien accès au fichier.
Et quant je choisis uptobox au lieu de uptostream j'ai bien accès aussi au fichier, mais vu mon débit adsl pour voir des fichiers en 1080p sans saccade je suis obligé de passer par uptostream.

**Comment by TmpName** [comment]
Kepliz a été modifié il y a 5 jours, donc je pense qu'il a deja ete corrigé.

Pour uptostream, je peux pas savoir, j'ai essayé avec un compte gratuit, ca a marché. Essaye de te connecter via navigateur sur la meme page avec sans compte pour voir si il ya une difference, sur le meme lien.

**Comment by Wolsey20** [comment]
Le bug viens bien de de vstream le mode premium de uptostream ne marche pas il  n’y a que mode gratuit qui marche.

**Comment by kris06** [comment]
Et bien merci TmpName est xe qu'on aura aussi a la prochaine maj  ZT stream et tirexo.?

**Comment by razorex** [comment]
Il y a mauvaise interprétation les marques pages c'est vStream et non kodi (Ajouter aux favoris). @kris06 tu peux sauvegarder tes databases (import/export) avant de changer deversion de kodi.

Il me semble même que kodi te propose de les conserver.

**Comment by razorex** [comment]
@TmpName du coup c'est vrai qu'il y a longtemp qu'il n'y a pas eu de version intermédaire...

**Comment by kris06** [comment]
Un grand merci razorex , en effet dans les paramètres de vstream on trouve dans outils,  import export du marque pages de l' historique etc...

**Comment by razorex** [comment]
Il est vrai aussi que le hoster de kepliz beug..

**Comment by kris06** [comment]
Oui j'attend surtout la réactivation de zt tirexo ( erreur 503 ) et de zone de téléchargement

**Comment by sizanic** [comment]
> le mode premium de uptostream ne marche pas il n’y a que mode gratuit qui marche.

Vous avez essayé avec la Beta ?


Ma dernière modif du 15/05 corrige un problème d'URL qui faisait tomber une erreur 503 en premium seulement.

**Comment by sizanic** [comment]
salut @kaim71 

Est-ce que tu peux revoir le titre de ton sujet, stp.

J'avais les réponses à tes questions depuis 3 jours mais je ne suis pas venu lire un sujet qui s'appelle juste "news" :thinking:

**Comment by kaim71** [comment]
OkEnvoyé de mon Galaxy S9+ Orange
-------- Message d'origine --------De : sizanic <notifications@github.com> Date : 25/05/2020  00:31  (GMT+01:00) À : Kodi-vStream/venom-xbmc-addons <venom-xbmc-addons@noreply.github.com> Cc : kaim71 <phaconcept@orange.fr>, Mention <mention@noreply.github.com> Objet : Re: [Kodi-vStream/venom-xbmc-addons] News (#2921) 

salut @kaim71

Est-ce que tu peux revoir le titre de ton sujet, stp.

J'avais les réponses à tes questions depuis 3 jours mais je ne suis pas venu lire un sujet qui s'appelle juste "news" 🤔



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2921#issuecomment-633310109",

"url": "https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2921#issuecomment-633310109",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by TmpName** [comment]
Ha oui le hoster googlevideo deconne.
Y a plus de cookies, doivent utilser le UA now.


Sinon pour la maj, oui devrait y avoir une dans la semaine.

**Comment by Wolsey20** [comment]
> Vous avez essayé avec la Beta ?
> 
> Ma dernière modif du 15/05 corrige un problème d'URL qui faisait tomber une erreur 503 en premium seulement.

Oui j'ai essayer la dernière Beta

**Comment by kaim71** [comment]
Salut les gars je me suis mis sur un ordi ou la mise à jour 0.8.0 n avait pas été faite et deviner quoi uptobox marche en premium et en streaming.
A vos doigt de fées

**Comment by kaim71** [comment]
J ai fait cela pour vérifier  c un coup dechance

**Comment by kaim71** [comment]
Il met authentification reussi à tout les coups

**Comment by kaim71** [comment]
Sur windows et pc

**Comment by Wolsey20** [comment]
Je fais un essai sur un lien qui propose que uptostream (authentification premium réussie) et la ça marche.
J'ai fait un autre essai sur un lien uptobox, vstream me demande de choisir entre uptostream et uptobox et la uptostream (authentification premium réussie) ne marche pas (erreur : Fichier introuvable).
Dans les paramètres de vstream j'ai changé pour mettre passer en streaming via uptostream mais j'ai toujours la même erreur.

**Comment by sizanic** [comment]
> J ai fait cela pour vérifier c un coup de chance
> Il met authentification reussi à tout les coups

On comprend pas si c'est bon ou pas.
C'est un coup de chance et ça n'a marché qu'une seule fois ?
"Authentification reussi à tout les coups" veut dire que ça marche tout le temps ?

Si ça se connecte tout le temps en 0.8.0 et pas avec la dernière Beta c'est qu'il y a une régression ?

**Comment by sizanic** [comment]
> J'ai fait un autre essai sur un lien uptobox, vstream me demande de choisir entre uptostream et uptobox et la uptostream (authentification premium réussie) ne marche pas (erreur : Fichier introuvable).

Je vais refaire un test en suivant ce process (uptobox vers uptostream).


>uptostream (authentification premium réussie) ne marche pas (erreur : Fichier introuvable).

Qu'est ce que ça veut dire ?
Il y a un premier message "authentification premium réussie" et derrière un autre message "Fichier introuvable" ?

**Comment by Wolsey20** [comment]
> Qu'est ce que ça veut dire ?
> Il y a un premier message "authentification premium réussie" et derrière un autre message "Fichier introuvable" ?

ça veut dire que j'ai bien été authentifier en premium mais le fichier et introuvable
![2020-05-27 (6)](https://user-images.githubusercontent.com/39297004/82955959-1bf01200-9fb0-11ea-918e-b1edf5c835ca.png)
![2020-05-27 (7)](https://user-images.githubusercontent.com/39297004/82955979-227e8980-9fb0-11ea-9e41-13c864b3f946.png)

**Comment by amidevous** [comment]
moi uptobox en premium et sans premium marche pas tester sur 3 système

uptostream marche en gratuit si ont na pas expirer le quota 120 minutes par jours

uptostream ne marche pas en premium

une solution provisoire utiliser urlresolver

https://github.com/tvaddonsco/script.module.urlresolver

il fonctionne en premium avec mais sa utilise l'api streaming

donc uptostream mais vous devais saisir un pin sur le site de uptobox en état authentifier premium

a l'ouverture de saque vidéo a voir si ont peux pas le charger directement avec le token

car si ont changer l'api avec son token premium sa donne le lien directe dans la réponse json

sa peux être une solution de résolution en tous cas

mais faudrait mettre sont token au lien de sont user mot de passe

https://docs.uptobox.com/#generate-a-download-link

exemple lien

https://uptobox.com/5naqi1wyfds8

https://uptobox.com/api/link?file_code=5naqi1wyfds8&token=privatetoken

resultat

{"statusCode":0,"message":"Success","data":{"dlLink":"http:\/\/www20.uptobox.com\/dl\/privategentoken\/Terminator.2.Judgment.Day.1991.Theatrical.Cut.MULTi.2160p.UHD.BluRay.REMUX.HEVC-zone-telechargement.lol.mkv"}}

https://docs.uptobox.com/#pin-authentication

exemple lien

https://uptostream.com/5naqi1wyfds8

https://uptobox.com/api/streaming?file_code=5naqi1wyfds8&token=privatetoken

{"statusCode":0,"message":"Success","data":{"subs":[],"streamLinks":{"2160":{"eng":"https:\/\/www38.uptostream.com\/privategentoken\/2160\/0\/video.mp4","fre":"https:\/\/www38.uptostream.com\/privategentoken\/2160\/1\/video.mp4"},"1080":{"eng":"https:\/\/www38.uptostream.com\/privategentoken\/1080\/0\/video.mp4","fre":"https:\/\/www38.uptostream.com\/privategentoken\/1080\/1\/video.mp4"},"720":{"eng":"https:\/\/www38.uptostream.com\/privategentoken\/720\/0\/video.mp4","fre":"https:\/\/www38.uptostream.com\/privategentoken\/720\/1\/video.mp4"},"480":{"eng":"https:\/\/www38.uptostream.com\/privategentoken\/480\/0\/video.mp4","fre":"https:\/\/www38.uptostream.com\/privategentoken\/480\/1\/video.mp4"},"360":{"eng":"https:\/\/www38.uptostream.com\/privategentoken\/360\/0\/video.mp4","fre":"https:\/\/www38.uptostream.com\/privategentoken\/360\/1\/video.mp4"}},"assetId":"41ce3bf2e5100c4a178fe5418800c6cb","duration":8243}}

je pense donc qu'i faudrait faire le script en utilisant cette api plutôt

car le script qu'on a utilise le site hors sur le site y pas de changement a chaque fois

mais l'api elle reste la même et elle justement faites pour les intégration

**Comment by TmpName** [comment]
Yep, je pense aussi, soucis moi j'ai pas de premium, donc je peux essayer de faire le code en aveugle mais il faudra au moins que tu le testes, si personne avec un premium ne s' y colle ?

**Comment by TmpName** [comment]
Bon debut du fichier > https://github.com/TmpName/Fichier_en_vrac/blob/master/uptobox.py

Mais du coup, le login et mot de passe ne servent plus a rien ?

Pour le moment la clé API est a mettre en dur sans le code (donc ne pas faire de copier coller de votre code sans virer la ligne)

**Comment by LordVenom** [comment]
Pas de réponse de @kaim71 merci de rien.

**Comment by kaim71** [comment]
Salut les gars désolé pour ma non participation mais entre la future perte de travail et les ennuis en ce moment..Je suis débordé je vous passe un grand bonjour et big up pour votre travail.Envoyé de mon Galaxy S9+ Orange
-------- Message d'origine --------De : Lord Venom <notifications@github.com> Date : 29/09/2020  05:11  (GMT+01:00) À : Kodi-vStream/venom-xbmc-addons <venom-xbmc-addons@noreply.github.com> Cc : kaim71 <phaconcept@orange.fr>, Mention <mention@noreply.github.com> Objet : Re: [Kodi-vStream/venom-xbmc-addons] Problème sur vstream et souci premium (#2921) 

Pas de réponse de @kaim71 merci de rien.

**Comment by LordVenom** [comment]
Merci de ton retour ça fait plaisir d'avoir une personne polie en face, pas de soucis prend soin de toi et de ta famille.

**Comment by kaim71** [comment]
Je reviendrai après et merci de ta compréhension Envoyé de mon Galaxy S9+ Orange
-------- Message d'origine --------De : Lord Venom <notifications@github.com> Date : 29/09/2020  05:52  (GMT+01:00) À : Kodi-vStream/venom-xbmc-addons <venom-xbmc-addons@noreply.github.com> Cc : kaim71 <phaconcept@orange.fr>, Mention <mention@noreply.github.com> Objet : Re: [Kodi-vStream/venom-xbmc-addons] Problème sur vstream et souci premium (#2921) 

Merci de ton retour ça fait plaisir d'avoir une personne polie en face, pas de soucis prend soin de toi et de ta famille.
