### ISSUE TITLE
Liste tmdb inaccessible 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2922]
**Décrivez le bug**

Dans Compte/tmdb/ma liste : impossible d'ouvrir le dossier pour voir sa liste mais les autres catégories s'ouvrent bien

**Votre system**
 - OS: [Android]
-  Appareil [Z6 Plus]
 - Version Kodi  [18]
- Version Vstream 0.8.0

**Comment by Arias800** [comment]
Il y a un accent dans le nom d'une de tes listes ?

**Comment by Che-debarras** [comment]
> Il y a un accent (ou tout autre caractère spécial ) dans le nom d'une de tes listes ?

Non pas du tout "film non vu" j'ai qu'une liste créé.Avant ça j'avais mis un nom avec 1 seul mon "film"
La liste a été créé a partir du site internet sur smartphone si cela peut aider.

**Comment by Arias800** [comment]
D'accord, c'était pour vérifié au cas où, car normalement le problème des accents est corriger dans le bêta, mais il se peut que ca puisse encore bloquer de temps autre.
D’après mes tests le code pour accéder au liste fonctionne bien, a une exception prêts. Si les listes sont en privées alors il faut que tu créer une clé d'api sur ton profil tmdb et que tu la rentre des les paramètres de Vstream pour pouvoir accéder au contenu des listes.

**Comment by Che-debarras** [comment]
> D'accord, c'était pour vérifié au cas où, car normalement le problème des accents est corriger dans le bêta, mais il se peut que ca puisse encore bloquer de temps autre.
> D’après mes tests le code pour accéder au liste fonctionne bien, a une exception prêts. Si les listes sont en privées alors il faut que tu créer une clé d'api sur ton profil tmdb et que tu la rentre des les paramètres de Vstream pour pouvoir accéder au contenu des listes.

Je vais tester
