### ISSUE TITLE
Problème avec cloudflare et le site que je code 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2923]
**Décrivez le bug**
Sur le site cloudflare est normal mais dans mes logs ils me disent qu'il y a recaptcha qui est détecté ce n'est pas normal il faut que j'ajoute quelque chose sur le code ou pas ?

**Votre system**
 - OS: [Windows,]
 - Version Kodi  18

Ps: Cloudflare n'est toujours pas corrigé avec dl protect sur tirexo

**Comment by Arias800** [comment]
Ça a l'air d’être un problème de ssl pour les site ou cloudflare ne marche pas. Faudrait essayer sous Kodi 17 pour voir.

**Comment by ludopotte** [comment]
Je viens d'essayer avec SPMC et ça marche pas.

**Comment by Ovni-crea** [comment]
Pareil sur kodi 17 j'ai ça comme erreur 
`11:54:45.968 T:2820  NOTICE: 	[PLUGIN] vStream: SQLITE 3 as DB engine
11:54:45.991 T:2820  NOTICE: 	[PLUGIN] vStream: load site tirexo and call function Display_protected_link
11:54:46.031 T:2820  NOTICE: 	[PLUGIN] vStream: SQLITE 3 as DB engine
11:54:48.246 T:2820  NOTICE: 	[PLUGIN] vStream: Page protegee par cloudflare
11:54:48.249 T:2820  NOTICE: 	[PLUGIN] vStream: Headers present {'Accept-charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7', 'Accept-language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3', 'User-agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0'}
11:54:48.253 T:2820  NOTICE: 	[PLUGIN] vStream: url https://www2.tirexo.com/link-6072989.html
11:54:48.256 T:2820  NOTICE: 	[PLUGIN] vStream: cookies passés : __cfduid=d8053ee41aea3119a9ad5f7f19e3bc42c1590314087
11:54:48.259 T:2820  NOTICE: 	[PLUGIN] vStream: post data :
11:54:48.264 T:2820  NOTICE: 	[PLUGIN] vStream: Pas de cookies présent sur disque
11:54:49.800 T:2820  NOTICE: 	[PLUGIN] vStream: could not load site: tirexo error: Detected the new Cloudflare challenge.
11:54:49.800 T:2820   ERROR: Traceback (most recent call last):
11:54:49.800 T:2820   ERROR: CloudflareChallengeError: Detected the new Cloudflare challenge.
11:54:49.808 T:2820  NOTICE: 	[PLUGIN] vStream: Table initialized`

**Comment by Arias800** [comment]
C'est parce que ça déclenche le nouveau challenge que venomous n'a pas encore corriger.

**Comment by Ovni-crea** [comment]
@Arias800 à d'accord je comprends mieux maintenant bon on a plus qu'a attendre une correction

**Comment by Ovni-crea** [comment]
@Arias800  J'ai fait la mise a jour de cloudscraper en 1.2.40 le soucis avec tirexo n'est toujours pas réglé ni meme ma source j'ai ça comme erreur maintenant
`[PLUGIN] vStream: could not load site: tirexo error: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.`

**Comment by TmpName** [comment]
Ben si il fait ca. Il a de forte chance que quelqu'un reprenne son code et gratos. quitte a profiter d'une fuite.

**Comment by Arias800** [comment]
En sois le fait de ne pas le mettre opensource je comprends puisque c'est pour compliquer la tache au mecs de Cloudflare. Mais par contre ne pas le proposer gratuitement c'est totalement stupide xD

**Comment by TmpName** [comment]
C'est clair, c'est pas du niveau d'un contournement de recaptcha.
C'est chiant a faire, mais pas dur pr un motivé, si il passe ca en payant, la version gratuite va sortir derriere.
Plein de projets gratuits se servent de son code, pas possible de mettre une partie payante.

**Comment by Arias800** [comment]
Oui, surtout qu'en plus il a récupérer pas mal de dons avec ce module. Donc le passer en partie payant c'est un peu immorale xD

**Comment by Ovni-crea** [comment]
@Arias800 ouais c'est ce que j'ai lu à la fin du topic sur son github  à l'issue `new cloudflare challenge` tout en bas c'est ce qu'il a écrit mais bon j'espère vraiment qu'il va pas le faire payant sinon c'est un peu embetant ^^

**Comment by Ovni-crea** [comment]
bah maintenant on peut ajouté enstream qui est concerné avec le nouveau challenge :(

**Comment by TmpName** [comment]
Ca depend de la charge serveur aussi.
Ca peut se declencher tout seul, et s'eteindre le lendemain.

**Comment by Ovni-crea** [comment]
@TmpName Peut être mais j'ai l'impression que cloudflare mets à jour sa protection il y a 3 jours environ tirexo fonctionnait c'était dl protect qui était concerné et la actuellement c'est tirexo complet enfin bref de toute façon pas trop le choix d'attendre ^^

**Comment by Ovni-crea** [comment]
@TmpName bon on a eu un peu plus de nouvelle apparemment c'est bien payant malheureusement :(

**Comment by TmpName** [comment]
Je cloture cette issue, vu qu'elle continue aileurs.
