### ISSUE TITLE
Vostf vs Vf

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2924]
Cette demande de fonctionnalité n'est pas lié a un problème mais plutôt un inconvénient pour lire les épisodes à la suite etc..

Je me demandais si on pouvait séparer la vostf et la vf des episodes (series, drama, animés) dans des sous dossiers séparés?
En espérant que cela ne soit pas un surplus de travail
Merci

**Comment by TmpName** [comment]
Et comment tu fais quand tu as plusieurs hosters sur la meme page, avec une fonction de lecture automatique ?

**Comment by sizanic** [comment]
>mais plutôt un inconvénient pour lire les épisodes à la suite

Parce que tu arrives à le faire ??

**Comment by Che-debarras** [comment]
> > mais plutôt un inconvénient pour lire les épisodes à la suite
> 
> Parce que tu arrives à le faire ??

@sizanic 
Non justement d'où l'inconvénient mais c'est possible car ya la fonction (lire a partir de cette episode) 
Et je teste des addons de programme et de skin qui pourrais afficher que les séries récents ou de mon marque page en page d'accueil pour etre averti des les récents series et episodes.

@TmpName 
Une vidéo sera plus parlant:
https://m.youtube.com/watch?v=hd18y8_MxEA

**Comment by sizanic** [comment]
>un inconvénient pour lire les épisodes à la suite etc..
> Je me demandais si on pouvait séparer la vostf et la vf des episodes (series, drama, animés) 

Je ne vois pas où est l’inconvénient :thinking: 
Si tu peux lire des vidéos à la suite, apres la lecture du dernier épisode en francais, lorsque ça enchaîne sur le premier épisode en VO, tu t'en aperçois vite et tu arrete la lecture ! C'est que t'a fini la saison !

Et avant que ça devienne un inconvénient, il faudrait déjà pouvoir enchaîner les épisodes.
On ne va pas mettre en place des sous-dossiers si on ne  peux même pas utiliser cette fonction.

**_lire a partir de cette episode_**
C'est une fonction de KODI, elle n'est pas adaptée à vStream.
Elle n'est utilisable que si les vidéos se lancent directement sans choisir un hoster d'abord.

Dans ta vidéo, il désactive les hosters.
Moi dans mes séries, j'ai souvent trois hosters (upstream, dood, gounlimited).

Et bien parfois j'utilise dood pour un episode, et gounlimited pour un autre épisode.
Donc désactiver deux hosters pour en ne laisser qu'un ne serait pas une solution souple.


Et quand bien même, si tu ne laisses qu'un seul hoster, il est quand même tous seul dans le dossier de l'épisode.
La fonction **_lire a partir de cette episode_** ne s'active pas sur les dossiers des épisodes mais sur la video.

=> Il faudrait que les liens de tous les épisodes soient dans le même dossier. Et qu'il n'y ait qu'un seul lien par épisode après avoir désactivé des hosters.

On en est loin, ce n'est pas juste créer de nouveaux dossiers qui suffit.

**Comment by Che-debarras** [comment]
@sizanic 

Je me doute bien que ce  n'est pas juste creer de nouveau dossier et je pense que c'est plus lié a une éventuelle évolution de  vstream a l'image de addon venom ou placenta qui justement affiche tes liens de tous les épisodes dans le meme dossier.

Je voulais juste avoir votre avis sur la question, si c'est pas possible vous pouvez clore la discussion

**Comment by sizanic** [comment]
> qui justement affiche tes liens de tous les épisodes dans le meme dossier.

Je voudrais bien voir ça :thinking: 

Je viens d'essayer avec Exodus (autre clone) on voit bien les episodes mais lorsqu'on en choisit un, on arrive sur la liste des hosts. Donc pour enchainer sur un autre episode, il faudrait ressortir de cette liste de hosts.

**Comment by Che-debarras** [comment]
@sizanic
On peut mettre le dossier de la serie en playlist et non cliquer sur une episode a mettre en playlist comme vstream
Donc je suppose qu'une fois le dossier en entier en playlist il lis les épisodes a la suite mais avant de lancer il te propose le choix du host.
Je vais essaye de faire une capture écran demain

**Comment by sizanic** [comment]
Mais du coup, avec VStream, je devrais pouvoir : 
- episode1/ hosts/dood -> ajout playlist
- episode2/ hosts/upstream -> ajout playlist
- episode3/ hosts/gounlimited -> ajout playlist
- episode4/ hosts/dood -> ajout playlist
- etc.

Ensuite je lance ma playlist en lecture automatique (lire a partir de cette episode).

Mais pour être sûr de ma playlist, il faudrait que je teste quelques secondes de chaque host pour être sur d'en prendre un qui fonctionne.

**Comment by sizanic** [comment]
> une fois le dossier en entier en playlist il lis les épisodes a la suite mais avant de lancer il te propose le choix du host.

Je n'y crois pas une seconde. Si le système te donne la main pour choisir le host, à la fin de la lecture, il y a peu de chance qu'il reprenne la main à son tour pour passer sur un autre fichier.

**Comment by Che-debarras** [comment]
Je vais clore cette discussion car je pense être mal compris sur ce que je disais.

Désolé
