### ISSUE TITLE
Accès compte Uptobox Premium

### ISSUE THREAD

**Issue by speedjeje** [Kodi-vStream/venom-xbmc-addons#2927]
**Décrivez le bug**

Hello la Team,
Depuis hier soir (et la mise à jour en version 0.8, je n'ai plus accès mon compte Uptobox Premium depuis vStream alors que j'y accède depuis n'importe quel navigateur.
Ce bug n'est présent que sur la version de vStream que j'ai mise à jour en version 0.8
Les "autres" vStream (sur tablette ou téléphone) fonctionnent parfaitement ...
L'authentification se fait mais j'ai un message "Fichier introuvable"
J'ai désinstallé et réinstallé vStream sans succès !!
Merci de votre aide.
@+

**Votre system**

- OS: OSMC
- Appareil Raspberry Pi
- Version Kodi  18.06
- Version Vstream 0.8.01

**Comment by TmpName** [comment]
Hello, et les autres sont sous quelle version ? 0.8.0 ou 0.8.01 ?

**Comment by speedjeje** [comment]
Je viens de vérifier les mises à jour ont été faites ...
Donc, toutes sont sont 0.8.01 et toutes fonctionnent normalement sauf vStream installée sur OSMC Raspberry Pi.

**Comment by TmpName** [comment]
Alors la c'est bizarre.
Tu pourrais essayer de faire passer quelques log (en les activant d'abord) ?

**Comment by speedjeje** [comment]
Encore, plus bizarre ... je viens de tester sur mon vieux RP1 sous OSMC également et ça ne fonctionne pas non plus ...
Problème d'OSMC plutôt que vStream ?
Je m'occupe des log mais pas avant demain ou mardi !!
Merci

**Comment by isandard** [comment]
Personnellement sur Kodi 17 avec la dernière mise à jour non bêta, pas de soucis.
J'ai accès à tout les fichiers de mon compte premium.

**Comment by speedjeje** [comment]
J'ai installé Batocera sur une autre carte et aucun soucis, non plus ... 😤

**Comment by speedjeje** [comment]
Alors, en fait, j'ai accès aux fichiers puisque la liste des fichiers s'affiche dans chaque dossier Uptobox mais la lecture ne se lance pas et si je choisis Uptostream ça m'affiche "fichier introuvable " ...

**Comment by isandard** [comment]
Ah ca j'ai pas vérifié car je passe toujours en direct et jamais par stream.
Je suis au boulot je regarderais ça ce soir pour confirmer en premium.

**Comment by isandard** [comment]
voila apres verif chez moi :
Kodi 17 sur android TV
Vstream 0.8.01 => uptobox direct => OK
Uptostream => Fichier Introuvable

Sur une autre box Android TV :
Kodi 18.7
Vstream 0.8 ( sans la derniere MAJ ) 
Même resultat Uptobox direct => OK
Stream => Fichier introuvable.

**Comment by speedjeje** [comment]
Je passe aussi toujours en direct, j'ai testé via Uptostream suite au problème !
En fait, le problème n'est présent que sur OSMC ....

**Comment by isandard** [comment]
non sur kodi de base aussi

**Comment by speedjeje** [comment]
Sans solution ou idée pour ce problème, j'ai créé une nouvelle install sous LibreElec et ça fonctionne nickel ...
Donc, je pense vraiment que le problème vient d'OSMC, même si j'ai lu que le même problème existait sous Xbox
