### ISSUE TITLE
Marqué Vu et Non Vu 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2928]
**Décrivez le bug**
Je ne suis pas trop sitcom mais en regardant Space Force si on arrête la lecture dès le début du générique de fin, l'épisode est marqué comme partiellement vu au lieu de vu entierement ✔ sur dpstrmng.

*Votre system**
 - OS: [Android]
-  Appareil [Vorke Z6]
 - Version Kodi  [18.7]
- Version Vstream 0.8.0.1

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : Dpstrmng
- Le titre du fim/serie : Space Force
- Le nom du host (openload/vidzi) : Mixdrop

**Comment by TmpName** [comment]
Ha oui, mais ca doit le faire sur toute les sources, tout les hosts, non ?

**Comment by sizanic** [comment]
Oui, la règle est la même pour tout le monde.

Il faut arrêter la lecture au delà de 90% pour être considéré comme "VUE".

**Comment by Che-debarras** [comment]
> Oui, la règle est la même pour tout le monde.
> 
> Il faut arrêter la lecture au delà de 90% pour être considéré comme "VUE".


Oui c'est pour tout les hosts mais on peut pas modifier ces 90%?

**Comment by TmpName** [comment]
A la main dans le fichier player.py

**Comment by sizanic** [comment]
Le générique dure vraiment plus de 10% de l'épisode ? 🤔

**Comment by Che-debarras** [comment]
> Le générique dure vraiment plus de 10% de l'épisode ?

Oui episode dure 36-37 minute et la serie se termine a 32 grosso modo

**Comment by sizanic** [comment]
> Parait que advance setting xml

non, désolé, c'est en dur dans le code.

> episode dure 36-37 minute et la serie se termine a 32

pas de chance => 32/36 = 88.89 %


On pourrait le changer dans le code, mais combien mettre ?
Si on descend à 85%, faut voir ce que ça donne pour un film de 2 heures :

120 * 0.85 = 102
Donc un gars qui arrete la lecture de son film de deux heures au bout d'une 1h40, on va lui dire que c'est fini alors qu'il lui reste 20 minutes de film !

Alors qu'avec 90%, il en est à 1h50. Un film de deux heures doit bien avoir au moins 7 minutes de générique. Donc là il est bien à la fin.


En fait, le pourcentage n'est peut-être pas la bonne solution car un générique n'est pas proportionnelle à la durée du film (surtout avec une série).

On serait plutôt avec quelque chose comme ça : 
Durée vidéo  (Durée générique)  - %
30 (5) - 84%
60 (6) - 90%
100 (10) - 90%
120 (10) - 92%
180 (10) - 95%
240 (10) - 96%

Une règle que je vois pour déterminer la fin de la lecture : 
Si video < 60 minutes, il doit rester moins de 6 minutes
Si video > 60 minutes, il doit rester moins de 10 minutes

=> On n'utilise plus un pourcentage mais une durée restante, qui dépend de la durée totale.

**Comment by sizanic** [comment]
@Che-debarras 
On n'a pas trop de solution à mettre en place rapidement,
si ce n'est de te proposer de faire un petit avance rapide lorsque tu arrives au début du générique :)

**Comment by yodidon** [comment]
Ne peut on pas calculer le coefficient en fonction de la durée ?
Si on estime que lorsqu’il ne reste plus que 10 min alors on considère que c’est comme terminé, on a un coefficient x=10/durée totale. Il faudrait du coup calculer à chaque fois le coeufficient et avoir aussi la durée totale

**Comment by yodidon** [comment]
ça ferait un truc un peux comme ça ?
        if self.totalTime > 0:
            coef = float('10/ self.totalTime)
            Actuel = self.currentTime *coef
        if (actuel>= 10):

**Comment by Che-debarras** [comment]
> @Che-debarras
> On n'a pas trop de solution à mettre en place rapidement,
> si ce n'est de te proposer de faire un petit avance rapide lorsque tu arrives au début du générique :)

Merci j'y ai pas pensé et au pire je le fais manuellement en cliquant marqué comme vu.
J'ai cru à un bug mais si c'est parce que le générique dépasse les 10% alors désolé pour ce post.
Ils doivent être rare les series qui ont un générique de fin de plus de 10%.

**Comment by sizanic** [comment]
>si on fait un truc comme ça ?(le cas où on détermine que c'est fini a partir de 10 min de la fin...)
...
if (Cal<=600):

oui, tel que cet algo,  il est facile de savoir qu'il ne reste que 10 min, la question est de savoir quand est-ce qu'on applique cet algorithme. Dans quels cas il faut calculer ces 10 min ?

>Ils doivent être rare les series qui ont un générique de fin de plus de 10%.

Oui, mais l'algorithme est le même que ce soit pour les séries ou les films. Et il y a à l'inverse un problème pour les films > 3 heures.

C'est pour ça que je propose un algorithme qui dépend de la durée total (et pas d'un pourcentage) : 

considéré comme VU: 
- Si video < 60 minutes, il doit rester moins de 6 minutes
- Si video > 60 minutes, il doit rester moins de 10 minutes

**Comment by sizanic** [comment]
Pas de solution générique pour ce désagrément ...
