### ISSUE TITLE
Source existante?

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2929]
J’ai bien lu la procédure pour proposer une nouvelle source (site)... en seulement, puisque c’est la toute première fois que je fais la tentative de me lancer dans cette aventure, j’aimerais bien être certaine de savoir si la source que je veux proposer existe déjà sous un autre nom... Il s’agit de:

ht tp :// www . cpasmieux . org

Merci :)

**Comment by TmpName** [comment]
Ben je suis de l'avoir vu a un moment, attend un autre avis.
Sinon je viens de la tester, tu risques d'avoir un probleme avec la protection cloudflare en ce moment (pas sur que ca dure).

Tu vas rigoler pr recuperer le lien final, mais a part la protection CF qui est aleatoire, j'ai rien vu de bloquant.

Par contre CF est un gros prb en ce moment, ca risque de te bloquer direct, au moins tu perdras pas ton temps pr rien.

**Comment by alKODIque** [comment]
> Ben je suis de l'avoir vu a un moment, attend un autre avis, mais la elle n' y est plus.
> Sinon je viens de la tester, tu risques d'avoir un probleme avec la protection cloudflare en ce moment (pas sur que ca dure).
> 
> Tu vas rigoler pr recuperer le lien final, mais a part la protection CF qui est aleatoire, j'ai rien vu de bloquant.
> 
> Par contre CF est un gros prb en ce moment, ca risque de te bloquer direct, au moins tu perdras pas ton temps pr rien.

Oui j'ai lu beaucoup ici tous les ennuis que vous rencontrez a cause de ce satane cloudflare.. je vais attendre un peu dans ce cas voir si le site est la pour rester et surtout, ce qui va arriver avec cloudflare.

Merci :)

**Comment by sizanic** [comment]
> Ben je suis sur de l'avoir vu a un moment, attend un autre avis, mais la elle n' y est plus.

Il me semblait aussi l'avoir vu, mais ça doit être parce que maintenant tous les sites se ressemblent, et même les noms se ressemblent.

> Sinon je viens de la tester, tu risques d'avoir un probleme avec la protection cloudflare en ce moment

J'ai pensé la même chose en arrivant sur le site : clouflare ! cloudflare !
