### ISSUE TITLE
Maj f4mproxy et urlresolver pour Kodi 19

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2930]
Je ne savais pas où l'écrire mais une des maj indique f4mproxy et urlresolver incompatible python 3.

Mais il ya eu des maj de ces 2 addons : voici les 2 liens d un site qui a pas mal de addon de derniers versions 

https://kodi-addons.club/addon/script.module.urlresolver/
https://kodi-addons.club/addon/script.video.F4mProxy/

Si tu a deja ces dernieres version sur ta config je suis désolé et tu peux clore ce post sinon je pense que ces derniers maj de f4mproxy 3.0.11 et de urlresolver 5.0.67 sont peut etre compatibles py3
Et f4mtester aussi est en 3.0.11. 
Si ça peut aider.

Perso j'ai testé sur kodi 19 (version de nov et dec) et l'addon est installé de même que les dependances mais les sources ne s'ouvrent pas ex dpstrmng.

**Comment by Arias800** [comment]
Alors non les deux addons ne sont pas compatible pour le moment.
C'est possible que tu me donne les logs pour voir d'ou vient le probleme avec dpstrmng ?

**Comment by Che-debarras** [comment]
> 
> 
> Alors non les deux addons ne sont pas compatible pour le moment.
> EDIT: Normalement dpstrmng s'ouvre avec le changement que je vient de faire dans la beta.

J'ai installé sur mon smartphone kodi 19 apk du 24nov19 et ces 2 addons sont compatibles et je vais voir jusqu'a quel version de kodi 19 ça reste compatible car  tu as raison sur le dernier apk du mois de mai ya une incompatibilité.

**Comment by Che-debarras** [comment]
> Alors non les deux addons ne sont pas compatible pour le moment.
> EDIT: Normalement dpstrmng s'ouvre avec le changement que je vient de faire dans la beta.

Ils sont compatibles jusque la version KODI Du 11.10.2019 mais effectivement les versions suivantes rendend ces addons incompatibles.

Par contre f4mproxy est une dépendance de f4mtester donc si l'un n'est pas compatible l'autre aussi.

Juste une question : sont il nécessaire pour le streaming des series et films?

**Comment by Arias800** [comment]
Non ils sont utiliser uniquement pour l'iptv. Donc pour le moment ils ont automatiquement désactiver sous Kodi 19.

**Comment by Che-debarras** [comment]
> Non ils sont utiliser uniquement pour l'iptv. Donc pour le moment ils ont automatiquement désactiver sous Kodi 19.

Merci pour l'info c'est ce que je pensais aussi.

Vstream fonctionne a l'identique sur kodi 19? Malgré l'absence de urlresolver ?

**Comment by Arias800** [comment]
Oui, je suis entrain de corriger les sites au cas par cas. Mais le cœur de Vstream a été porter sous Kodi 19 donc tout devrai en théorie fonctionner (pour le moment il y a juste le menu contextuel qui ne marche pas correctement).

**Comment by razorex** [comment]
Et les outils dans les paramêtres.

**Comment by Arias800** [comment]
C'est vrai que j'ai pas tester ca xD

**Comment by sizanic** [comment]
> Non ils sont utiliser uniquement pour l'iptv.

On en profite pour retirer l'IPTV de vStream ? 🤔

**Comment by TmpName** [comment]
Ben les chaines classiques comme france 2 / 3 ne marchent plus non plus ?
En ce moment je me sert d'un autre plugin donc j'ai pas testé ?

**Comment by Arias800** [comment]
Les chaînes officielles fonctionne (normalement). D'ailleurs faut que je continue d'en ajouter xD

**Comment by Che-debarras** [comment]
> Les chaînes officielles fonctionne (normalement). D'ailleurs faut que je continue d'en ajouter xD

Uniquement des chaines Tnt gratuite?

**Comment by Che-debarras** [comment]
> > Les chaînes officielles fonctionne (normalement). D'ailleurs faut que je continue d'en ajouter xD
> 

Uniquement des chaines Tnt gratuite ?
Uniquement des chaines de France?

**Comment by Che-debarras** [comment]
> Alors non les deux addons ne sont pas compatible pour le moment.
> EDIT: Normalement dpstrmng s'ouvre avec le changement que je vient de faire dans la beta.

Dpstrmng ne s'ouvre plus sur kodi 18 du coup

**Comment by TmpName** [comment]
Ha ok donc ca expliquerait https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2932#issuecomment-637815316

**Comment by razorex** [comment]
DPstreaming est passé sous CF

**Comment by Che-debarras** [comment]
#2897 
Oui j'ai sur la page web et j'ai installé les anciens versions de kodi et le problème est toujours la donc apparemment c'est du a CF.
Ya moyen de contourner CF pour que Dpstrmng soit fonctionnelle ou une correction est en cours pour cette source?

Merci

**Comment by Ovni-crea** [comment]
@Che-debarras Je sais pas faut voir avec @Arias800 il s'occupe souvent de cloudflare d'ailleurs sachant que venomous à fait la correction mais il faut le payer pour l'avoir 
(PS: Dpstrmng n'est pas le seul concerné en plus )

**Comment by Che-debarras** [comment]
> @Che-debarras Je sais pas faut voir avec @Arias800 il s'occupe souvent de cloudflare d'ailleurs sachant que venomous à fait la correction mais il faut le payer pour l'avoir
> (PS: Dpstrmng n'est pas le seul concerné en plus )

Oui je patiente la correction et c'est serieux ce paiement. Effectivement Dpstrmng n'est pas le seul.
Je fais souvent des bilans de bugs et vu que CF est la cause principale de ces bugs je n'en ai pas fais.
Justement j'attendais la correction CF qui devait être fait par ce dev mais j'ignorais qu'il fallait payer. Cest pas cool de sa part enfin si c'est vrai

**Comment by Ovni-crea** [comment]
@Che-debarras bah à la base ce n'étais pas payant c'est un module open source venomous n'a fait que de le reprendre alors certes au début gratuit mais après payant (enfin une partie payant ) mais bon après il le mérite quand même pour le travail qui l'a fait

**Comment by Che-debarras** [comment]
> @Che-debarras bah à la base ce n'étais pas payant c'est un module open source venomous n'a fait que de le reprendre alors certes au début gratuit mais après payant (enfin une partie payant ) mais bon après il le mérite quand même pour le travail qui l'a fait

Ya pas d'alternative ?

**Comment by Ovni-crea** [comment]
@Che-debarras Je ne sais pas faudrait faire des recherches sur github pour voir si il y a un module ou autre part

**Comment by razorex** [comment]
Pour info:
la source "iptv" propose des contenus en m3u8 et en français mais il faut revoir la source.

**Comment by Che-debarras** [comment]
> Pour info:
> la source "iptv" propose des contenus en m3u8 et en français mais il faut revoir la source.
> Pas trop le temps aujourd'hui.

Ya une source  qui est souvent maj "ahlakid" si intéressé ne pas inclure les playlists adultes svp

**Comment by Ovni-crea** [comment]
@Che-debarras  Désolé on peut pas ajouté ton site c'est en .rar leurs fichiers + il y a une redirection avec recaptcha après je sais que kodi 18 lie les .rar si jamais tu arrives à faire quelque chose 
je te passe le fichiers `https://github.com/Ovni-crea/Source-vstream/blob/master/Sites/ahlakid_com.py`

**Comment by Che-debarras** [comment]
> @Che-debarras Je ne sais pas faudrait faire des recherches sur github pour voir si il y a un module ou autre part

Ce que venomous partage sur son github ne suffit pas, il a apporté des modifs sur cloudscraper ya 10jr pour la version master et ya 3jr pour la version beta. Aucun des 2 ne permet a vstream de bypasser cloudfare?

**Comment by Arias800** [comment]
Non ça ne corrige pas le problème.
Venomous fait maintenant payer pour avoir accès a son code de Cloudflare. J'ai bricoler une version de Js2Py qui tourne sous Kodi, je suis entrain de voir si je trouve un code de Cloudflare qui fonctionne.

**Comment by Che-debarras** [comment]
> Non ça ne corrige pas le problème.
> Venomous fait maintenant payer pour avoir accès a son code de Cloudflare. J'ai bricoler une version de Js2Py qui tourne sous Kodi, je suis entrain de voir si je trouve un code de Cloudflare qui fonctionne.

Ok merci, j'ai mis une liste de sources qui bug, penses tu qu'ils soit tous liées à CF?

**Comment by razorex** [comment]
Oui très certainement du à CF

**Comment by Che-debarras** [comment]
> Oui très certainement du à CF

Par exemple, strmng.watch est passé cette nuit à  une protection CF? Car je ne vois pas la page de CF sur le site web contrairement à dpstrm.
J'ai vraiment pas de bol, dès que je trouve une source de remplacement pour ma série, il bascule en CF.

**Comment by TmpName** [comment]
Mais en fait ne fait que  (rendre payante) ne pas diffuser la partie en natif ? Ou toute la lib ?
Le reste du code est fonctionnel ? Ca ne pourrait pas passer avec la lib JS de Vstream ?

**Comment by razorex** [comment]
On ne pourrait pas désactiver aussi les sources en attendant qu'il y ait une solution????

**Comment by Arias800** [comment]
Apparemment il ne va plus du tout proposer de correctement pour la v2 de Cloudflare, donc a terme il ne va plus mettre le lib gratuite a jour.
Je sais pas si ça peu fonctionner avec la lib JS de Vstream, c'est juste que je cherchais un autre module mis a jour. Mais visiblement il n'y en a pas xD

**Comment by TmpName** [comment]
Ben ca faisait du taff en moins ...
Pourvu que quelqu'un d'autre se lance la dedans. Pour le moment j'ai pas vu la moindre annonce officielle venant de lui.

**Comment by Arias800** [comment]
Je pense que c'est difficile de faire plus claire, pour avoir accès a la partie du code qui résous la v2 il faut le contacter sur Discord et il va donner les infos pour payer ![image](https://user-images.githubusercontent.com/24809312/83948165-c91e2200-a81b-11ea-9fb5-fa3f78220997.png)

**Comment by TmpName** [comment]
Mais c'est juste un commentaire dans une issue.
Si c'etait officiel se serait sur la page de garde de la lib. Il y a deja 2 personnes qui ont re ouvert des issues comme quoi la lib ne marche pas et qui sont sans commentaires.

**Comment by Arias800** [comment]
Il vient de réouvir une issue par rapport a ça xD

> Can you people stop raising tickets when you get the error Detected the new Cloudflare challenge
> 
> This is a valid exception!!
> 
> I am not publicly releasing code solving for cloudflare v2 challenge system, nor am i doing it for free.
> 
> You are more than welcome to discuss the price on discord etc...

**Comment by TmpName** [comment]
Ok ben la, il va se faire foutre.

**Comment by Arias800** [comment]
Oui, surtout que les cookies ont l'air de durée par mal de temps.

**Comment by TmpName** [comment]
Peut etre https://docs.j7k6.org/bypass-cloudflare-protection-webscraping-python-selenium/

**Comment by Arias800** [comment]
C'est tout le problème, pour le moment il n'y a pas de bypass de Cloudflare qui marche, même avec js2py.

@Che-debarras Concernant l'iptv :
- Oui les chaines officiel sont des chaines qui sont disponible de base gratuitement et légalement sur internet. Pour le moment il n'y en a que des Francaises mais je suis pas contre l'ajout de chaine étrangère.
- Pour les chaines payante je vient d'ajouter une source qui propose pas mal de chose et qui est assez stable.

**Comment by Che-debarras** [comment]
> 
> 
> C'est tout le problème, pour le moment il n'y a pas de bypass de Cloudflare qui marche, même avec js2py.
> 
> @Che-debarras Concernant l'iptv :
> 
>     * Oui les chaines officiel sont des chaines qui sont disponible de base gratuitement et légalement sur internet. Pour le moment il n'y en a que des Francaises mais je suis pas contre l'ajout de chaine étrangère.
> 
>     * Pour les chaines payante je vient d'ajouter une source qui propose pas mal de chose et qui est assez stable.

Merci pour cette nouvel source et désolé de vous embéter avec çà encore une fois mais y a t'il moyen de désactiver des chaines sur cette nouvel source (y a une chaine qui dérange lol)

**Comment by Arias800** [comment]
Effectivement je l'avais pas vu, mais du coup c'est fait xD

**Comment by Che-debarras** [comment]
> 
> 
> Effectivement je l'avais pas vu, mais du coup c'est fait xD

merci infiniment  esperons que cette source dure et disparait pas comme frstonetv

**Comment by Ovni-crea** [comment]
@TmpName @Arias800 j'ai réussi à faire marcher selenium et je peux vous dire qu'il y a vraiment un potentielle

**Comment by Ovni-crea** [comment]
bon j'ai un problème avec selenium impossible de résoudre recaptcha je sais pas si j'ai oublié quelque chose donc je vous passe le morceau du code 
`if URL_PROTECT in sUrl:
        driverPath = get_driver_path('chromedriver')
        options = webdriver.ChromeOptions()
        options.add_argument("start-maximized")
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        driver = webdriver.Chrome(driverPath, chrome_options=options)
        options.headless = True
        driver.get(sUrl)
        time.sleep(30)

        page_source = driver.page_source
        driver.close()

        print(page_source)
        VSlog(page_source)
` 

voila quand je veux résoudre le captcha il ne le valide pas malgré que j'ai bon 
si quelqu'un a une solution je le remercie 👍

**Comment by TmpName** [comment]
Houla tu es motivé, moi je pensais m'en servir pour CF, pas encore recaptcha ^^.

La je peux pas tester, je jetterais un oeil plus tard.

**Comment by Ovni-crea** [comment]
@TmpName d'accord pas de problème :)
