### ISSUE TITLE
Liens premium VS version beta

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2932]
Bonjour,

Tantôt, j’ai installé la nouvelle bêta puis il n’y avait ensuite plus aucun lien, d’aucune source qui voulait s’ouvrir. Je possède un compte alldebrid donc j’utilise URLresolver avec vStream.  J’ai dû revenir à la version du dépôt pour que vStream fonctionne a nouveau. 

Malheureusement, il m’est impossible de vous faire parvenir mon log puisque j’ai éliminé mon dossier temp (mon cache)...

Je suis sous Nvidia Shield, Leia 18.7.
J’ai aussi un compte premium Uptobox (dont les dossiers ne voulaient plus ouvrir avec la nouvelle bêta)

S’il vous est impossible de voir le problème sans log, je pourrais peut-être réinstaller la bêta pour vous l’envoyer, juste a m’aviser

Merci!

**Comment by TmpName** [comment]
Tu veux dire que la version normale fonctionne, mais pas la version beta ?

Normalement dans 4 jours tu vas avoir une MAJ qui va te proposer la version beta qui date de 6 jours.

**Comment by alKODIque** [comment]
Non..
Je veux dire que j’ai téléchargé la beta (hier) via votre github section “participer directement au projet” donc les tout derniers commits y etaient. Je crois que lorsque j’ai téléchargé, le dernier commit intégré était:
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/e86464ff40c54d01b6f231a446179604b73945f7

**Comment by Che-debarras** [comment]
> Non..
> Je veux dire que j’ai téléchargé la beta (hier) via votre github section “participer directement au projet” donc les tout derniers commits y etaient. Je crois que lorsque j’ai téléchargé, le dernier commit intégré était:
> [e86464f](https://github.com/Kodi-vStream/venom-xbmc-addons/commit/e86464ff40c54d01b6f231a446179604b73945f7)

Idem pour moi la Beta fonctionnait bien jusqu'a une correction de dpstrmng pour kodi 19 du coup sur kodi 18 la source ne s'ouvre plus.
Je visionnais man in the high castle sur dpstrm et depuis lundi erreur 503

**Comment by razorex** [comment]
DPstreaming est passé sous CF

**Comment by Arias800** [comment]
Il faut des logs pour pouvoir localiser le problème, car personne parmi les développeurs actif n'utilisent UrlResolver.

**Comment by alKODIque** [comment]
D'accord, je vais ré-installer la bêta, urlresolver, activerai le debug et vous fait parvenir le tout dès que j'en ai la chance ce soir (je suis au Québec alors cette nuit pour toi hihi!)

**Comment by alKODIque** [comment]
Re-moi...

Et bien je dois me retracter...
Je viens d'installer a nouveau la toute derniere beta puis surprise! je suis capable d'utiliser mon debrideur.  Je joins quand-meme mon log, au cas ou il vous serait utile et merci encore pour le soutien.

Un jour, a titre d'anecdote, j'ai du communiquer avec un plombier car ma toilette etait completement bouchee, rien a y faire. Puis, lorsqu'il est arrive, il tire la chasse et MAGIE! tout fonctionne a merveille  :P  Je me sens un peu dans cette meme situation hihi
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4821355/kodi.log)

**Comment by TmpName** [comment]
Lol, si tu savais combien de fois je me suis retrouvé a la place du plombier, face a une personne qui ne savais vraiment pas quoi repondre,, et moi a me demander si j y facture quelque chose ou pas ....

**Comment by alKODIque** [comment]
Je compatis (insérer ici un petit sourire niais)

**Comment by alKODIque** [comment]
Et bien..
Je ne fait pas appel "au plombier ", soyez sans crainte...
Mais après redémarrage de ma shield, sans rien avour changé, ABSOLUMENT RIEN, Urlresolver est devenu "orphelin" dans ma liste de dependances... Alors plus moyen d'ouvrir un dossier contenant des liens dans vStream, a moin d'enlever (décocher) de passer par urlresolver dans les paramètres......

Je sais qu'il vous faut un log...
Je n'en ai pas conservé... Sur un coup de tête d'impatience, j'ai plutôt réinstallé ma version bidouillée ou j'ai remplacé par Resolvurl, tout est revenu a l'ordre.

C'était seulement pour que vous sachiez.
Je ne vous dérange plus avec ce point a moins d'avoir un log et de remplir une issue en bonne et due forme  ;)

**Comment by Arias800** [comment]
J'ai fait une modif dans la beta, peut être que ca peu corriger le problème.

**Comment by alKODIque** [comment]
Ho!
Merci , je vais tester :)

**Comment by Arias800** [comment]
Je garantie rien, mais au moins ca permets d'etre sure que le probleme ne vient pas de Vstream.

**Comment by alKODIque** [comment]
C'est quand-meme étrange.
L'impression que j'ai eu, c'est qu'après redémarrage kodi ne reconnaissais plus "urlresolver" en tant qu'addon.

**Comment by Arias800** [comment]
Ça peut se produire si Kodi decide que Vstream n'utilise plus UrlResolver. Et dans ce cas la il le désactive.

**Comment by alKODIque** [comment]
Ceci peut-il expliqué le fait que urlresolver n'apparaissait pas dans le log que je t'ai fait parvenir il y a quelque jour ? (Lorsque tu me disait qu'il n'était pas installé et que c'était pour cette raison que ca fonctionnait pas)  car je te certifie qu'il était bel et bien installé... mais beaucoup de "unknow addon"  dans mon log

**Comment by Arias800** [comment]
C'est possible. En tout cas si ca se reproduit encore avec la beta, c'est que ca vient de Kodi

**Comment by alKODIque** [comment]
Juste petite question avant...
Si, dans addon.xml, on ajoute "optional=true" dans import addon urlresolver

**Comment by alKODIque** [comment]
Fonctionne pas 
:(

**Comment by alKODIque** [comment]
Lorsqu'url resolver a été installé, erreur dans defautlpy line 184 dans parse URL donc incapable de "display_protected_link

Puis erreur dans resolver.py line 20, setDisplayName

Désolée... sur ma shield plus compliqué aller récupérer et envoyer mon log. 

Mais je m'en vais le faire de ce pas  :)

**Comment by alKODIque** [comment]
Je sais pas s'il t'es possible de voir sur ma version vs la nouvelle beta les fichiers differents qui font en sorte que ca ne fonctionne pas... je n'ai malheureusement pas accès a un ordi cette semaine et je n'ai que firefox installé sur ma shield donc j'utilise editpad en ligne pour faire des changements et ca a aucune fonction... (a moins que tu connais un autre outil en ligne ou je pourrais bidouiller et ainsi te libérer sur ce problème qui en fait, ne touche pas la majorité de vos utilisateurs)

Voici ma version personelle en pj. Avec resolveurl mais c'est pareil qu'avec urlresolver )
https://u.pcloud.link/publink/show?code=XZgCFIkZwyBVbrKAC78s3tjVW9tmS4AhOick

Merci pour tout :)

**Comment by alKODIque** [comment]
J'ai réussi a localiser le fichier qui causait problème.. il s'agit du fichier "defautl.py"
Et ça concorde car la date à laquelle la dernière modification de ce fichier a eu lieu dans l'historique de la beta, semble être la date à laquelle urlresolver a cessé de fonctionner pour moi en devenant "orphelin" dans la liste des dependances de kodi.

Ce que j'ai fait:
- j'ai téléchargé la dernière bêta depuis le github
- j'ai désarchivé le dossier (plugin.video.vstream)
- j'ai remplacé le fichier "default.p"
Par celui annexé ici
- j'ai archivé a nouveau.

Je me suis assuré après avoir installé que je n'avais plus le problème en redémarrant ma shield... la dernière fois, même vStream fonctionnait, lorsque je redémarrais urlresolver devenait "orphelin" dans la liste de dependances alors il était impossible de l'appeler dans vstream.

Maintenant, tout fonctionne

**Comment by Arias800** [comment]
Bizarre le default py c'est le même que celui de la beta d’après github xD
Par contre dans les logs il est belle et bien exécuter: 
`2020-06-25 14:42:29.481 T:15389  NOTICE: URLResolver: Initializing URLResolver version: 5000.0.67a`
Essaye avec une version d'UrlResolver qui est inférieur a 5.1.0. Car si ca se trouve c'est leur implementation de Python 3 qui pose probleme.

**Comment by alKODIque** [comment]
Oui très bizarre..
Mais bel et bien la cause...
Les changements sont très minimes dans default py.. des espaces seulement a ce que je comprends

**Comment by alKODIque** [comment]
En y pensant bien, je ne pense pas que ca fonctionne si j'utilise une version inférieure a 5.1 puisque lorsque je j'utilise resolvurl sur ma version de vstream au lieu de urlresolver j'obtiens également exactement la même chose avec Resolvurl v5.0.00

**Comment by Arias800** [comment]
Je vient d'essayer sous Kodi 18.7, sous Windows, avec la toutes dernieres version d'UrlResovler et la dernière bêta de Vstream. Tout fonctionne. Donc c'est peu etre encore un problème d'Android xD

**Comment by Arias800** [comment]
Par contre car c'est pas normal : 
![image](https://user-images.githubusercontent.com/24809312/85920921-49163580-b878-11ea-8db5-59431b99cd3e.png)
Faut que je cherche d'où ca vient.

**Comment by Arias800** [comment]
@alKODIque J'ai fait une modification dans la beta. Normalement ca résous le probleme d'ouverture des liens qui ont des accents dans le titre.

**Comment by alKODIque** [comment]
> @alKODIque J'ai fait une modification dans la beta. Normalement ca résous le probleme d'ouverture des liens qui ont des accents dans le titre.

Je vais tester et te reviens!

Merci @TmpName 
Tu sais si tu veux tester avec Alldebrid, j'ai droit a 5 adresses ip sur mon compte ;)

**Comment by alKODIque** [comment]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4841310/kodi.log)

Malheureusement,
probleme n'est toujours pas regle pour urlresolver...
dans mon log, tu verras lorsque je suis a l'interieur de extreme down, j'essaie d'ouvrir le dossier d'un lien uptobox et il refuse d'ouvrur. puis je "decoche" dans les parametres "passer par urlresolver" et la, le film debute sans soucis grace a mon compte premium uptobox...

Juste par curiosite, je vais aller interchanger mon fichier default py comme j'expliquais la derniere fois et reviens annexer mon log

**Comment by alKODIque** [comment]
[defaultpychange.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4841390/defaultpychange.log)
[default-et addon-xml change.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4841391/default-et.addon-xml.change.log)
[addon.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4841392/addon.txt)
[default.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4841393/default.txt)


voila.

**Comment by Arias800** [comment]
Le problème c'est que l'on peut pas obliger l'installation d'UrlResolver :/

**Comment by alKODIque** [comment]
Oui je sais... seulement a mettre la ligne optional=true
Ca fonctionne aussi

**Comment by alKODIque** [comment]
> @alKODIque J'ai fait une modification dans la beta. Normalement ca résous le probleme d'ouverture des liens qui ont des accents dans le titre.

Je sais pas si ça peut aider... avec un autre addon, j'avais le même problème pour les liens qui avaient des caractères accentués (TheMovieDb helper) Jurialmunkey (le dev) m'a dit ceci:

@alKODIque - What is your player file? I think this is due to not using a {*_url} type key in your player e.g. from just using {title} instead of {title_url}

Il a quand-même fait une modification a son script qui a réglé le problème.  Tu peux la trouver ici:

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/2b61be8ef9ef2a63ca7ae88796c84eed681583c6

Je reviens sur les caractères accentués car dans mon compte uptobox, je peux pas ouvrir les liens justement qui comportent des mots avec accents

**Comment by Arias800** [comment]
Donc logiquement cette version d'addon xml corrige le problème : https://github.com/Arias800/Fichier-divers/blob/master/addon.xml
Je vais voir pour corriger le probleme d'accents dans "mon compte uptobox".

**Comment by alKODIque** [comment]
> Donc logiquement cette version d'addon xml corrige le problème : https://github.com/Arias800/Fichier-divers/blob/master/addon.xml
> Je vais voir pour corriger le probleme d'accents dans "mon compte uptobox".

Logiquement oui.
Mais attention a la version urlresolver... le 500.0.0 c'est une version custom ou il n'y a pas de Indigo comme dependance.. il me semble que la version officielle c'est quelque chose du genre 5.1.?

**Comment by Arias800** [comment]
Oui, mais ça n'a pas l'air de poser problème. Je vient d'essayer sur Windows avec la dernière version d'UrlResolver et ça n'a pas bloquer.

**Comment by alKODIque** [comment]
C'est peut-être du au fait que c'est optionnel... espérant que kodi ne le vire pas au prochain démarrage et/ou mise a jour de vstream..

**Comment by Arias800** [comment]
Du coup j'ai appliquer la modification et ont verra bien xD

**Comment by alKODIque** [comment]
Ça fonctionne bien pour moi :)
Redémarrage inclu. UrlResolver est toujours utilisé dans ma liste de dependances kodi  :)

**Comment by Arias800** [comment]
Bon bah je comprends pas pourquoi ça ne marchais plus. Mais bon vaut mieux pas chercher a comprendre xD
Je passe en résolu, si ca recommence n’hésite pas a ré ouvrir l'issue.

**Comment by alKODIque** [comment]
Comme c'est agréable voir cette isdue "closed" 😂😂😂

Énorme merci pour tout le travail et patience 👍

**Comment by Arias800** [comment]
C'est surtout grâce a toi que ça a pu être corriger. Tu a fait tout le travail a ma place xD

**Comment by alKODIque** [comment]
...travail très modeste par rapport a tout ce que vous faites ;)

**Comment by alKODIque** [comment]
Hé!
Compte uptobox, pour les titres avec lettres accentués... c'est aussi fonctionnel maintenant 
Tu es un King!! 👍👍
