### ISSUE TITLE
 1 seule resultat de recherche sur ht__ _tps://h  dss.  to/ 

### ISSUE THREAD

**Issue by milkibreizh** [Kodi-vStream/venom-xbmc-addons#2933]
Bonjour

**Décrivez le bug _____ recherche limitée
**Le nom du site_______ht___tps://hdss.  to/ 

Quand on effectue une recherche à partir de hdss le resultat n'affiche qu'un seul résultat

exemple  sSearch='ted'
fichier:kaydo_ws.py
showMovies() 
avec
sPattern = 'Title">Search<.+?<a href="..etc
Ne permets de trouver que le premier résultat de la page ici le film disjoin**ted**
alors que l'on a  bien les infos du film ted ted sur la page 
(en utilisant par exemple  le pattern de non recherche)

est-ce pour limiter le nombre de recherche ou essayer de rendre plus cohérente la recherche ?
fichier site verifié kaydo_ws.py.py  sur
venom-xbmc-addons/plugin.video.vstream/resources/sites
et sur la bêta

Bon courage à toutes l'équipe

**Comment by Che-debarras** [comment]
La fonction recherche a toujours été compliqué sur vstream.
Quand je faire recherche similaire c'est pareil il ne trouve que une poignée de source alors que une recherche globale m'en trouve plein.

Je ne sais pas comment ca marche la recherche mais si comme google on peut avoir que le titre contenant le mot exacte ce serait cool

Leboncoin a une fonction de rechercher que dans le titre, Google permet de rechercher le mot ou l'expression exacte en le mettant entre "guillemet"

Ya pas moyen de piquer leur script lol ?

**Comment by sizanic** [comment]
On utilise le moteur de recherche du site.
C'est donc l'algorithme de ce moteur qui est utilisé.

Si sur le site, la recherche renvoie plusieurs résultats et pas vStream, on va regarder ce cas de plus près ...

**Comment by milkibreizh** [comment]
Oui en effet  la recherche renvoie plusieurs résultats et pas vstream
mais j'ai cru que c’était volontaire justement. 
vstream affiche seulement le premier résultat de la page que le site veux bien nous fournir
pour être honnête je n'ai pas vérifie sur une recherche global pensant que vstream rassemblait
tous les résultats pour chaque sites (selectionnés)

ce qui viens au problème du nombre de resultats à limiter pour des recherches comme "les"
j'essaye de faire un fichier site (:h   tt -ps://w  vv.vkstrea  m.o rg/ sans intérêt  car redondant comme ressource de site de séries,et si cela se trouve c'est un clone  ou deja fais mais qu'importe ...c'est pour me faire la main)
et je me posais la question justement si je dois limiter la recherche

**Comment by sizanic** [comment]
Ce n'est pas volontaire, on va regarder.

Et comme tu veux te faire la main, TU peux regarder :)

La limitation mise ne place pour la recherche globale, c'est qu'on ne prend que la première page des résultats de chaque site (on retire le lien "Suivant >>>" ).

Il est également possible qu'on mette en place un filtrage lorsqu'il y a trop de résultats (recherche global ou pas) pour enlever les résultats dont le titre est trop éloigné.

On ajoute ce code qui compare le titre et le mot recherché : 

```
            if sSearch and total > 3:
                if cUtil().CheckOccurence(sSearch, sTitle) == 0:
                    continue
```

Il y a un exemple dans filmsStreaming et extrem_Down.

Le site que tu essaie de traiter, le lien m'a fait penser à celui-là : https://film stream vk.bz/series/
mais ce n'est pas un clone 👍

**Comment by milkibreizh** [comment]
cela y ressemble
si cela vous intéresse je peux vous faire partager mon fichier..qui ne m'appartiens pas vu que j'ai tout pomper
sur les autres fichiers sites pour comprendre et le créer.
je suis sur la dernière ligne droite récupérer les hosts
pour le lecture de la video.....

et j'ai quelques bins avec def __checkForNextPage
et j'ai remarqué que sur d'autres fichiers sites il y avait un problème avec cette fonction
mais je ne sais plus lequel..a noté que sont peut être des sites qui ne fonctionne pas avec les host 
et qui ne sont peut être pas mis a jours pour cela,car je ne m'occupe que de la navigation du menu pour le moment....et cela se trouve je vais être coince pour la lecture ..mais c'est pas grave j'aurais comme mème appris des petites choses sur les rgex

Après rajouter une source redondante c'est du boulot en plus pour pas grand chose
Bon courage

**Comment by milkibreizh** [comment]
Désolé j'ai répondu trop vite
"La limitation mise ne place pour la recherche globale, c'est qu'on ne prend que la première page des résultats de chaque site (on retire le lien "Suivant >>>" )."
ce qui explique mon questionnement sur d'autre sites
et j'avais déja bien noté  la fonctionCheckOccurence
je vais essayer de remettre les mains dans le camboui ce week end
....pour pas perdre la main
car là je suis plutôt en train de regarder les bases de la programmation python
