### ISSUE TITLE
Kodi vstream 0.8.0

### ISSUE THREAD

**Issue by Edwydge** [Kodi-vStream/venom-xbmc-addons#2935]
Après misez jour vstream puis mise à jour des sources peut importe le films que je charge dans n'importe quels sources c'est en vo je n'arrive pas a avoir en vf même sur french-stream je con prends pas et cela depuis la mise à jour c'est quoi le soucis vous pourriez m'aider merci d'avance
t

**Comment by TmpName** [comment]
Donc si tu vas dans Frenchstrm / film / dernier ajout / le voyage du pelerin tu l'as en VO ?

**Comment by razorex** [comment]
Pas de réponse on clos l'issue.
