### ISSUE TITLE
Playlist sous youtube

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2936]
Je viens d'ajouter une source "zone_Streaming", le hoster est Youtube.
Pour les séries et les émissions, youtube utilise un système de playlist.
Est-ce que quelqu'un se sent de regarder comment la récupérer???

**Comment by milkibreizh** [comment]
bonjours
...désolé de m'incruster
est ce a voir avec
ht___tp://www.zone-streaming.fr
parce que j'avais l'intention de faire ce fichier source sur ce après avoir finit 
un site ht__tps://wvv.vkstr_eam.org/ ou il me reste a résoudre 2 hosts inopérants 

mais je dois confondre car ce site n'as pas bcp de ressources

**Comment by milkibreizh** [comment]
Et oui je suis pas trop malin j'avais pas regarder si le fichier était présent sur le site
mais je sais pas trop comment vous mettez a jour vos fichiers... désolé
c'est bien le site...
a+ et bon courage

**Comment by razorex** [comment]
Oui @milkibreizh c'est bien pour lui. je l'ai fais ce matin.

**Comment by TmpName** [comment]
Ha oui, je viens de voir, merde c'est con, c'est la ou l'api de youtube serait utile ^^

**Comment by razorex** [comment]
J'imagine qu'il y a un message la dessous @TmpName mais tu aurais pas un site qui pourrait me servir d'exemple... je trouve bien une page youtube qui en parle mais l'intégrer pour moi c'est du chinois..

**Comment by TmpName** [comment]
Alors moi ce que je ferais je traiterais les lien du type https://www.youtubeXXXX/embed/videoseries?list=Id_de_list dans la source.

Il te faut charger la page https://www.youtubeXXX/list_ajax?style=json&action_get_list=1&list=Id_de_list

Dedans tu trouve un json avec plusieurs partie dont par exemple
"title": "SKAM FRANCE EP.5 S6 : Jeudi 21h42 - Je savais pas ça",
"encrypted_id": "Q27EoOVHwrc"

Et le lien sera donc youtube.com/watch?v=Q27EoOVHwrc

**Comment by razorex** [comment]
Bon je reviens vers ce sujet.
j'ai trouvé çà dans une source dans les trash (streamingvoirfilms) est ce utilisable???
j'ai tenté mais j'ai des ERROR
```
page = json.loads(sHtmlContent)
if page:
    for x in page:
        sUrl = page[x]["url"]
        sTitle = page[x]["title"].encode('utf-8')
        sThumb = page[x]["img"]
```

**Comment by razorex** [comment]
@TmpName Du coup j'utilise la méthode traditionnelle (sans json) mais je n'ai jamais le même résultat pour la même série, peut être à çà que sert json!!

**Comment by TmpName** [comment]
Ben le Json facilite le boulot, tu as l'erreur sur quelle ligne ? Le code est en ligne ?
Sinon de memoire il ya un soucis dans l'architecture du JSON. Le premier "onglet de classement" est "video", c'est pour ce que j'ai dans mon exemple
>List_video = page['video']

**Comment by razorex** [comment]
Bon galere, j'ai écrasé mon fichier qui fonctionnait à moitié.
Du coup je tente avec le json et j'ai cette erreur:
```
[PLUGIN] vStream: https://www.youtube-nocookie.com/list_ajax?style=json&action_get_list=1&list=PLoFKFNRfJ7p1UcHn1m0H6RBsmPr6sO3FE
[PLUGIN] vStream: ZxY2xZHDeAg
[PLUGIN] vStream: https://i.ytimg.com/vi/ZxY2xZHDeAg/default.jpg
[PLUGIN] vStream: SCREAM - Autopsie d'une mort culte
[PLUGIN] vStream: could not load site: zone_streaming error: 'dict' object is not callable
ERROR: Traceback (most recent call last):
ERROR:   File "C:\Users\???\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 184, in parseUrl
ERROR:     function()
ERROR:   File "C:\Users\???\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\zone_streaming.py", line 325, in showHosters
ERROR:     sUrl = page(i["encrypted_id"])
```
En plus je pense que l'on ne récupérerais qu'une vidéo et non pas la liste:
Exemple de [json](https://gist.github.com/razorex/0e0542b22dd777edf7c5cd3c05ac35dc)
Ma [source](https://gist.github.com/razorex/9d5042727b49c6ee76ed679685a4a01b)

**Comment by razorex** [comment]
C'est bon j'ai trouvé.

**Comment by TmpName** [comment]
Oups mince, désolé, j'ai mis le topic de coté et je t'ai oublie.

**Comment by razorex** [comment]
Pas grave çà m'a fait chercher
