### ISSUE TITLE
HelpOnRefere & Uq Load

### ISSUE THREAD

**Issue by milkibreizh** [Kodi-vStream/venom-xbmc-addons#2938]
bonjour 

j'essayais de faire un site et j'ai un problème avec uq load 
j'ai remarquer  que les autres sites utilisant qload utilisait un refere

pour mon showhoster      
     
    for aEntry in aResult[1]:
	    sHosterName= aEntry[1]           #group1 :'nomhost'
            sHosterUrl = URL_MAIN+aEntry[0] #group2 :'/streaming/aHR0c.........'
            oHoster = cHosterGui().checkHoster(sHosterName)
            
            if (oHoster != False):
                if (str(oHoster).find('uqload')>0):                
                    oRequestHandler = cRequestHandler(sHosterUrl)
                    oRequestHandler.addHeaderEntry('Referer', sUrl)
                    oRequestHandler.request()
                    sHosterUrl = oRequestHandler.getRealUrl()
               
                oHoster.setDisplayName(sMovieTitle)
                oHoster.setFileName(sMovieTitle)
                cHosterGui().showHoster(oGui, oHoster, sHosterUrl, sThumb)

je recois bien les fichiers sHosterUrl ht  tps://uql  oad.com/em  bed-df gss.html pour ql oad 
mais j'ai rien à la lecture
dans ce fichier j'ai comme info
'ht   tps://me___ga01.uq   load.com/3rfk.................syoq/v.m p4'
mais si je colle le lien j'ai error_wrong ip
et aussi un 
'$.get('https://uqlo........a ne plus en finir')

je suis un peu ( hyper bcp) largué du coup   car  cHosterGui().showHoster est une boite noire
pour moi ou je mets des liens

je demande pas pas que l'on me mâche le travail ,ce n'est pas le but,
mais une ou deux explications,moins longue que le roman que j’écris actuellement serait le
bien venue

a+

**Comment by sizanic** [comment]
le lien .mp4, si tu mets cette url dans VLC, as-tu la vidéo ?

**Comment by milkibreizh** [comment]
@sizanic 

merci de t'intéresser à mon problème..car tu as sans d'autres chat à fouetter

vlc échoue

1 methode direct
2020-06-05 09:06:26.426 T:8512  NOTICE: 	[PLUGIN] vStream: Hoster - play ht_tps://wvv.vkstr_eam.org/strea__ming/aHR__0cHM
2020-06-05 09:06:27.682 T:8512  NOTICE: 	[PLUGIN] vStream: Player use setResolvedUrl() method
2020-06-05 09:06:27.697 T:8252  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.vstream/?site=cHosterGui&%%6L
2020-06-05 09:06:28.035 T:10432  NOTICE: Creating InputStream
2020-06-05 09:06:28.088 T:8512  NOTICE: 	[PLUGIN] vStream: player started
2020-06-05 09:06:28.544 T:10432  NOTICE: Creating Demuxer
2020-06-05 09:06:28.596 T:10432   ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file ht____tps://stream___meme_fichier./v._mp4


2 methode ou je mets le le lien embed methode(refere)....je crois que j'obtiens comme 1

3 methode ou je mets le mp4 que j'ai extrait du fichier embed..

2020-06-05 09:08:14.845 T:1292  NOTICE: 	[PLUGIN] vStream: load site cHosterGui and call function play
2020-06-05 09:08:14.850 T:1292  NOTICE: 	[PLUGIN] vStream: Hoster - play ht____tps://stream___meme_fichier./v._mp4
2020-06-05 09:08:15.242 T:1292  NOTICE: 	[PLUGIN] vStream: Erreur: File not found


on retrouve ht____tps://stream___meme_fichier./v._mp4

j'ai fouillé pour la première fois dans les outils web de firefox et
pour le fichier embed q__load  j'avais comme paramètre de sécurité
le certificat emis à/ par par etait Cloudflare, Inc.contrairement aux autres host qui marchent

donc si cela est la cause il vaut mieux fermer mon issu
vous en avez deja pas mal déjà à votre charge ;-)

Autrement j'ai pas essayer de faire passer des paramètres de cookies
mais j'y crois pas trop

a+

**Comment by yodidon** [comment]
wrong ip je dirais UA non ?
un truc du type
UA = 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36'
 if (api_call):
            return True, api_call + '|User-Agent=' + UA + '&Referer=' + self.__sUrl
sur le fichier du hoster peut être

**Comment by yodidon** [comment]
j'aurai du regarder avant le hoster est deja la et avec le UA et tous désolé

**Comment by yodidon** [comment]
peut etre qu'avec le site on pourrait regarder ce qui s'y trouve :)

**Comment by sizanic** [comment]
@milkibreizh 
Mets-nous à disposition ton fichier complet, stp.
On pourra te donner plus facilement de bons conseils.

**Comment by milkibreizh** [comment]
@sizanic 
mon fichier.....c'est un bordel sans nom

@yodidon 
inutiles d’être désole j'avais pas regardé les hosters avant sur mes précédent post 
mais En voulant justement passer les cookies j'ai compris (,enfin je crois?)
qu'il fallait peu être modifier le hoster car il n'y a pas de passage de cookies dans
def __getMediaLinkForGuest(self):


donc je vous remercie de votre attention je vais faire des testes sur le hoster
q__load (passage de cokkies/ + paramatres headar) etc

et je vous redonnerais des nouvelles .....demain...
c'est pas par impolitesse mais vu à la lenteur duquelle
 je code + mon temps libre dispos + nettoyage de mon fichier
 je préfère prendre des précautions

ma seule question en attendant pour être certain :
les passages de cookies ne peuvent se faire que dans le hosters ?

En vous remerciant de la ponctualité ,et de la qualité de votre aide


a+

**Comment by sizanic** [comment]
Pour pas que tu partes dans une mauvaise direction, passe ton fichier.
On est vraiment pas là pour juger de la qualité, mais pour donner un coup de main.
Et là on peut pas sans ton fichier.

**Comment by milkibreizh** [comment]
bonjours
@sizanic  @yodidon 
ou autre

 cela ma calmé un peu calmé pour passer les cookies dans le hoster
il faut les extraire pour les renvoyer en les parsant 
j'ai crue qu'un copier coller suffisait pour le 
    'http:' + api_call + '|User-Agent=' + UA + '&Cookie=' + cookies
cela doit être faisable mais j'ai pas encore approfondi mon enquête
du coup avant d'aller plus loin

ajouter_une_source.py (nom pratique pour la navigation)
h_ttps://pastebin.com/3EqqmysP

pour les hosters quand je dis ok c'est que j'ai lue au moins une fois une video
à noté que sur mon navigateur je ne peu lire les fichier  u_qload que si je désactive mon vpn

 u_qload  jamais
 m_ystream ok
 v_idoza ok
u_pvid  (probleme aussi )
v_idlox  ok
c_lipwatching ok 
g_ounlimited ok
m_ixdrop	    ok

prenez votre temps tout de même je ne suis pas si pressé que cela
car en attendant il y a pleins de trucs que je dois comprendre
sur python.

**Comment by TmpName** [comment]
Ca doit venir du VPN, car je viens de tester de mon coté, la video est passée sans probleme et sans cookies.

**Comment by milkibreizh** [comment]
@TmpName 
quand j'ai une vidéo qui ne marche pas je désactive toujours mon vpn pour revérifier en mode normale
j'ai pensé au dns vu ta réponse
1111 1001
8888
mais non
je suis sous windows 10

tu as aussi le hoster u_pvid  qui marche aussi ?(question idiote)
dans les options de vstream ou de kodi j'ai du modifier un trucs
ou peu être les depences ne sont pas a jour
mais j'ai verifié pourtant (peu etre mal)

ton information m'est utile car je sais ou ne pas chercher
mais je ne sais pas ou chercher  
il faut que je teste sur un autre appareils

Merci du tuyaux
bon après se site n'apporte rien a vstream en quand que nouvelle source

**Comment by sizanic** [comment]
> quand j'ai une vidéo qui ne marche pas je désactive toujours mon vpn pour revérifier en mode normale

Il faut d'abord vérifier que la vidéo est accessible sur le site 😄 

Sinon, ta source est propre.
Juste revoir le nommage des saisons dans le titre.

**Comment by milkibreizh** [comment]
@sizanic 
dans ma source j'ai
https://wvv.vkstream.org/serieTv-les-100-saison-2-episode-1-vostfr
j'avais oublié de notifier que c'etait un exemple de lien lu
avec firefox et ensuite avec kodi (sans vpn)
si je fais mes testes à l'envers je suis mal barré :-;

c'est bizard cette histoire j'ai collé le lien mp4 sur un ubuntu 16.04 et j'ai eu la mème erreur
en pensant que c'etait win 
error_wrong_ip..(message afficher par le site
avec le lien hhtps://mega...up/gg/v.mp4 

et tous les hosts marchent au moins une fois chez vous ?
Bon je crois que l'on va en resté là je vais peaufiner le site
car là je vois pas a part ma box orange qui me joue des tours de routeur
ou kodi

tu peux fermer car si c'est de mon coté et si la source est a peu prés fonctionnelle
c'est l'essentiel..au moins j'aurais validé mon premier essai .
bon après j'aurais biens voulu vous rendre service en faisant un site
complémentaire de vstream mais je ne trouve pas de site avec bcp de ressource

merci pour tous
et à toutes l'équipe
 a+

**Comment by TmpName** [comment]
Lol ben de rien, c'est toi qui bosse, merci a toi.

**Comment by milkibreizh** [comment]
@TmpName 

et c'est toi qui me remercie? 
celui qui a posté je ne sais pas combien d'amélioration au projet
ya kipproko car c'est vous :toutes l’équipe qui m'apportent de l'aide et non l'inverse

comment je le disais auparavant le post peu être clos (je ne sais pas si j'ai le droit de le fermer)
bien que je suis un peu embêté car je ne peux pas faire de rapport d'erreur fiable sur la validite
des hosts pour vous aider

**Comment by TmpName** [comment]
Mais j'ai pas suivi, tu as fini le code ?

**Comment by milkibreizh** [comment]
@TmpName 

c'est surtout que tu as du te perdre dans mes trop longues explications
qui au finale rendent confuses mes explications :-)

non je n'ai pas finit la source
il faut que je modifie les renommages des menus 

mais comme je le disais c’était juste un teste pour moi  pour voir 
comment créer un fichiers 
Si vous êtes intéressé par la source je la finirais au plus tôt.
mais ce sera de la maintenance de plus pour pas grand chose

**Comment by yodidon** [comment]
Cool que tu t’y mettes , tu verras c’est plutôt intéressant à faire

**Comment by milkibreizh** [comment]
@yodidon 
le problème c'est que je viens de débuter en programmation
c'est certes intéressant mais je doute d'avoir donc le niveau pour vous aider
cela vas plutôt être le contraire...et j'ai pas non plus envie de vous faire 
perdre votre temps..
mais je n’hésiterais a poser des question si je reste bloqué trop longtemps
ou j'essayerais  au mieux de faire remonter des issues
a+

**Comment by sizanic** [comment]
@milkibreizh 
Ta source est fonctionnelle et on n'en demande pas plus.

Ton niveau et donc suffisant pour nous aider à ajouter des sources.

Pourquoi penses-tu que ta source n'est pas à intégrer dans vStream ?
Pourquoi penses-tu qu'elle vient en doublon ?
Est-ce un clone d'une source déjà prise en compte ?


> et j'ai pas non plus envie de vous faire perdre votre temps

Tu ne nous fait pas perdre notre temps si tu utilises ensuite nos retours pour t'améliorer. C'est pour nous du temps bien investie 👍

**Comment by milkibreizh** [comment]
@sizanic 

autrement oui ma source fait en effet doublon sur les résultats de recherche de vstream
et ok je vais essayer de m’améliorer en vous faisant perdre du temps ;-)

bonne soirée à l'equipe

**Comment by razorex** [comment]
TA source est dans mon stock.. Doublon ne veut pas dire clone.. il est très fréquent que des sources ce ressemblent(la recherche normale) . Et le principale c'est que tu ai compris.

**Comment by yodidon** [comment]
> @yodidon
> le problème c'est que je viens de débuter en programmation
> c'est certes intéressant mais je doute d'avoir donc le niveau pour vous aider
> cela vas plutôt être le contraire...et j'ai pas non plus envie de vous faire
> perdre votre temps..
> mais je n’hésiterais a poser des question si je reste bloqué trop longtemps
> ou j'essayerais au mieux de faire remonter des issues
> a+

En ce qui concerne ton niveau , je suis aussi débutant, et petit à petit avec les conseils de chacun j’avance, loin d’être au niveau de l’équipe mais assez pour prendre du plaisir. Et tout le monde m’aide même quand mes questions sont « idiotes » :)

**Comment by milkibreizh** [comment]
ok merci pour les encouragements je vais essayé de m'accrocher
@razorex 
mais avec un peu plus de rigueur    :smile:
a+

**Comment by milkibreizh** [comment]
@razorex 
ton stock n'est pas a jour 
le fichier que j'ai posté marche un peu près mais pour le nommage des series épisodes ya un bins
celui ci est plus recent c'est celui que j'utilise mais j'ai pas finit a cause de cette histoire de fichier.xml
il faut que j'extrais la description et il y a des instructions un peu bête dans mon fichier que j'ai faite
par méconnaissance du langage de programmation
https://pastebin.com/ard1hB3T

**Comment by milkibreizh** [comment]
Erreur liée à une mauvaise gestion des liens dans le hoster
problème résolu par @razorex
