### ISSUE TITLE
Streamavie recup du hoster

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#2941]
Si quelqu'un peu regarder j'arrive a voir le lien final, d'ou correction de la regex, mais je comprend pas comment on le "formate" suis vraiment mauvais sur ce point.. et même d'autres lol

**Comment by TmpName** [comment]
Le probleme vient de l"url dans URL_MAIN, utilises https

"Content-Type" n est pas bon, mais tu peux le virer ainsi que tout les autres headers, dans mes test j'ai utilisé que le referer et l'UA

Si tu veux alleger le code mixe dPost , dNum , dType dans la fonction showLink() comme ca tu auras a passer un seul parametre au lieu de 3.

Sinon rien de special ca a marché du premier coup, le code etait bon.
