### ISSUE TITLE
Erreur de lecture de beaucoup de liens (certficat SSL expiré) sous certains OS

### ISSUE THREAD

**Issue by mifrey00** [Kodi-vStream/venom-xbmc-addons#2943]
Ce problème n'est pas dû à vstream mais j'indique ici une solution car ça va sûrement en agacer plus d'un.

Depuis fin mai la plupart des liens streaming (de différents serveurs) ne s'ouvrent plus chez moi (je suis sous OSMC sur Raspberry Pi).  Les logs kodi indiquent une erreur de certificat SSL.

```
$ tail -f -n 50 ~/.kodi/temp/kodi.log
…
2020-05-31 21:23:12.851 T:970953440   ERROR: CCurlFile::FillBuffer - Failed: Peer certificate cannot be authenticated with given CA certificates(60)
…
```

Un essai avec curl indique qu'un certificat a expiré.

```
$ curl -v  https://fs23.upvid.org
* Rebuilt URL to: https://fs23.upvid.org/
*   Trying 45.178.4.67...
* TCP_NODELAY set
* Connected to fs23.upvid.org (45.178.4.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: certificate has expired
...
```

Alors que le même lien avec Firefox sous Windows et Ubuntu s'ouvre sans problème. En analysant la chaîne de certificats envoyés par le serveur on se rend compte qu'il y en a un (le 3e) qui a expiré le 30 mai.  C'est un certificat délivré  pour "USERTrust ECC Certification Authority" par "AddTrust External CA Root".

```
$ openssl x509 -sha256 -fingerprint -text < /tmp/3.cert
SHA256 Fingerprint=C2:B2:5B:AD:6F:6E:D6:52:16:CA:DA:D7:42:0B:E9:A3:C7:87:B7:78:9F:4C:02:22:C3:5A:25:74:BB:AC:E9:2A
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            76:d8:b7:86:d1:f3:52:4f:ee:95:3e:71:40:3d:99:d5
    Signature Algorithm: sha384WithRSAEncryption
        Issuer: C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
        Validity
            Not Before: May 30 10:48:38 2000 GMT
            Not After : May 30 10:48:38 2020 GMT
        Subject: C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust ECC Certification Authority
...
```

Et le certificat qui authentifie Addtrust qui est le CA root se trouve dans le trust store et a aussi expiré le 30 mai.

```
$ openssl x509 -sha256 -fingerprint -text < /etc/ssl/certs/AddTrust_External_Root.pem
SHA256 Fingerprint=68:7F:A4:51:38:22:78:FF:F0:C8:B1:1F:8D:43:D5:76:67:1C:6E:B2:BC:EA:B4:13:FB:83:D9:65:D0:6D:2F:F2
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
        Validity
            Not Before: May 30 10:48:38 2000 GMT
            Not After : May 30 10:48:38 2020 GMT
        Subject: C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root 
…
```

Ma version de curl et openssl testent cette chaîne de certificats et la vérification échoue donc. 

D'autres versions (et Firefox) testent une autre chaîne qui est valide. En effet mon trust store contient aussi un certificat self-signed de "USERTrust ECC Certification Authority" qui lui est valide jusqu'en 2038.  Cette chaîne devrait donc être bonne.

```
$ openssl x509 -sha256 -fingerprint -text < /etc/ssl/certs/USERTrust_ECC_Certification_Authority.pem
SHA256 Fingerprint=4F:F4:60:D5:4B:9C:86:DA:BF:BC:FC:57:12:E0:40:0D:2B:ED:3F:BC:4D:4F:BD:AA:86:E0:6A:DC:D2:A9:AD:7A
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            5c:8b:99:c5:5a:94:c5:d2:71:56:de:cd:89:80:cc:26
    Signature Algorithm: ecdsa-with-SHA384
        Issuer: C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust ECC Certification Authority
        Validity
            Not Before: Feb  1 00:00:00 2010 GMT
            Not After : Jan 18 23:59:59 2038 GMT
        Subject: C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust ECC Certification Authority
...
```

Le problème sera résolu lorsque les serveurs n'enverront plus de certificats expirés.  En attendant, pour forcer curl à tester cette autre chaîne valide, on peut simplement retirer le certificat "AddTrust External CA Root" du trust store.  Sous OSMC Raspberry qui est basé sur Debian, on édite le fichier /etc/ca-certificates.conf et on met un “!” devant la ligne “mozilla/AddTrust_External_Root.crt”, puis on regénère les certificat du store avec  "sudo update-ca-certificates".

Plus d'infos ici https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration

**Comment by speedjeje** [comment]
Ok, je vais tester ça.
Merci !

**Comment by TheHight** [comment]
Une idée de comment faire sur Xbox ? Même si je le sens mal vu que c'est pas très accessible comme os...
