### ISSUE TITLE
Impossible d’installer Vstream 

### ISSUE THREAD

**Issue by Lemuri204** [Kodi-vStream/venom-xbmc-addons#2944]
Bonjour, 

J’essaye depuis quelques jours d’installer Vstream sur la télévision sous android. Cependant lorsque je veux accéder au dépôt, il n’y a aucun fichier à l’intérieur. 
J’ai bien suivi le tuto d’installation, je n’arrive pas à voir d’où viens le problème. 

Merci par avance :)

**Comment by sizanic** [comment]
Bonjour ,

Dis-nous en un peu plus sur l'étape où ça coince.

Tu as installé le repo 0.0.3 et dans le dossier "Extension vidéos" tu n'as pas l'extension vStream ?

**Comment by razorex** [comment]
22 jours sans retour d'info. on clos
