### ISSUE TITLE
Depuis un bout les sources DDL1 , time2watch , extreamdown

### ISSUE THREAD

**Issue by KodiTopQuebec** [Kodi-vStream/venom-xbmc-addons#2945]
Depuis un bout les sources DDL1 , extreamdown et time2watch avec un compte débrideur (realdebrid) ne fonctionnaient plus 

je met toujours la dernière version beta et ce parfois 3 fois dans la même journée , tellement que j aime être a jours lorsque il y a un correctif 

mais la a ma grande surprise , j installe une plus vieille version de mon backup de kodi et par magie tout mes sources dite plus haut fonctionnent

la pour faire le test je met la version beta d'aujourd’hui  et plus rien ne fonctionne , donc il y a quelqu un qui a modifié quelque chose dans les bêtas sans tester ses changements .... et je vous le dit c est depuis un bon bout que les sources dites plus haut ne fonctionne plus et pas juste pour moi , j'ai quand même un groupe de plus de 2600 membres donc le problème ne vient pas juste de chez moi 

donc je me dis ok voyons voir si je retourne a mes addons et met vstream a jour ( sans la beta ) juste cliquer sur le bouton mettre a jour et tatam mes sources fonctionnent a l exception de time2watch car sur la version dite officiel cette source n'est pas la , elle est seulement la après qu il y ait eu une beta 

Pour la je ne suis pas en mesure de vous dire quel version de beta que j'ai présentement pour que tout mes sources fonctionnent , par contre il y a eu un changement par un dev et de toute évidence n a pas vérifier si ses correctifs fonctionne

merci du support apporter a votre addon , mais svp corriger l'erreur pour retrouver nos sources fonctionnelles avec nos débrideurs lors de votre correctif beta

**Comment by lebigboss** [comment]
Les bêta sont juste pour des tests, si tout fonctionne avec les versions officiel, il y a pas de raison d'installer de bêta.
Normalement les derniers bêta sont faites pour Kodi 19.

**Comment by alKODIque** [comment]
Pourquoi installer les bêta si ce n'est pour tester et aider a déceler des bugs??? Ils y a plusieurs jours que ces problèmes ont été discutés pourtant... Tu ne lis pas les autres issues??  

La version bêta sert présentement aux tests pour kodi v19. Alors si ton seul but est d'avoir tes sources fonctionnelles, tu n'es évidemment pas un candidat pour les bêtas... Il faut demeurer avec la version stable et tout a fait fonctionnelle avec kodi 18.

**Comment by alKODIque** [comment]
Ha et si tu tiens absolument a avoir les sources a jour dont time2watch, il y a ludopotte qui maintient un patch  a jour pour ça..  ici: (le dernier en date d'aujourd'hui)

https://github.com/ludopotte/vStream/blob/master/patch.vstream-0.8.01.8.zip

**Comment by isopek** [comment]
Bonsoir, 
Pareil pour moi j'ai une android box, sur la plupart, le clique vers le lien de stream tourne en rond ou ne s'ouvre simplement pas.
Est-ce un probleme connu, peut-on m'aider plz 

Merci par avance

**Comment by razorex** [comment]
Bon déjà les système exotique comme Android sont peut être les plus fréquent (la cause du pb peut être!!). Moi ce qui me fait me poser une question c'est pkoi avec une version qui pousse vers py3 çà ne passe plus (çà veux peut être dire que l'on a perdu une compatibilité py2).. la course a kodi 19 n'est pas lancé....

**Comment by alKODIque** [comment]
Je suis probablement dans ke champ et ça a sûrement un tout autre lien mais pour moi, ça a commencé directement après ce commit: https://github.com/Kodi-vStream/venom-xbmc-addons/commit/49ee41f758b6158dc7528ca3b128af52b35df4ec

**Comment by razorex** [comment]
DDL1 corriger

**Comment by sizanic** [comment]
@KodiTopQuebec 
> tout les sources dites plus haut, j'ai réussi a les faire fonctionner avec des correctifs dans le XML, j'ai même fait un tutoriel pour mes 2600 membres

Cela m’intéresse aussi.
Quelle est cette modification? Nous pouvons l'intégrer en natif dans vStream.
.
.
>aucun rapport pour le CF pour la

Veux-tu dire que tu a trouvé un moyen d'accéder à ces sources sans être confronté à CF ?
.
.
 
> souvent justement la version officiel n était plus fonctionnelle pour certaines source et on mettait la beta et tout revenait en ordre

Ce n'était pas le cas ici, il ne faut pas se précipiter sur la beta dès la première erreur.
Perso je suis toujours en 0.8.0, je ne suis même pas passé en 0.8.01.
Et j'ai assez de résultats pour trouver ce que je recherche. Ainsi que ma communauté.
.
.

> car la beta était la pour corriger les changements

Non, encore une fois.
Par définition une beta n'est pas stable !

**Comment by Bikkedj** [comment]
Hello à tous.
Bon cette fois j'arrive plus à rien. 
Utilisateur depuis des années sur shield, je me suis toujours démerdé pour faire tourner vstream (grâce à vous) mais là je m'en sors plus, je n'ai plus aucune source. J'ai un Premium 1fichier donc adepte de zone telech, tirexo ou ddl1. 
Après tellement de bidouilles j'ai tout desinstallé et réinstallé mais rien n'y fait, j'ai aucun lien. 
J'ai essayé l'officiel, bêta ou le patch de ludopotte. Cette fois je Calle.
Kodi 18.7  sur Android shield tv
Je pars du repo vstrean 0.0.3
Puis j'installe à partir des zip que je trouve ici. 
Je pige pas pourquoi rien ne va.
Désolé de faire le boulet, je suis pas super balaise.
Si quelqu'un veut bien me dire comment je pourrais avoir une version qui tourne ça serait super cool. 
Merci pour votre taf !

**Comment by TmpName** [comment]
Alors je crois qu'il n y a plus ni Tirexo, ni ZT, ni ddl, donc a mon avis c'est normal dans ton cas.

**Comment by alKODIque** [comment]
@TmpName 
Il y a eu panne hier sur le site ddl1. Il n'était plus accessible. C'est revenu depuis.
Pour ZT et zt-stream, une "faille dans la matrice" a fait en sorte qu'ils étaient a nouveau accessibles via vStream. Probablement une panne cloudflare de leur côté. Présentement, bien que ZT soit revenu sous sa protection cloudflare, zt-stresm présente encore des liens disponibles.

Pour Tirexo. Depuis qu'ils ont mis en ligne, il y a de cela environ 1 semaine, Une version .net et .org, ces domaines ne sont pas sous cloudflare... peut-être pourrait-il maintenant être accessible dans vStream?
