### ISSUE TITLE
Recherche globale sur de nouvelles sources  enable/disable

### ISSUE THREAD

**Issue by milkibreizh** [Kodi-vStream/venom-xbmc-addons#2946]
bonjours

je n'arrive pas à activer la recherche globale sur de nouvelles sources

dans le menu option ENABLE/DISABLE source 
j'ai bien le nom des nouvelles sources 
je valide bien le premier et le deuxième ok
mais rien ne se passe 
les sites sources d'origines s'activent et se désactivent bien

si je fais une copie integrale du fichier  adkami.py,par exemple,
et que je le renomme adkami2.py /avec identifier =adkami2 label=Newadkami (+ teste je change l'url)
c'est le même constat

j'ai modifier le fichier setting xml car les nouvelles ressource n'apparaissent pas 
mais rien

mais étant donnée qu'il n'as jamais été modifié
c'est juste un fichier en lecture seule qui doit servir à initialiser quelque chose (la bd) ou je
ne sais pas quoi...( j'ai pas tout réinstaller et modifier le fichier avant de faire un  
premier lancement)

merci de votre aide

**Comment by razorex** [comment]
Bon alors après essai:
Pour la recherche globale et l'activation/désactivation il faut que la source soit dans le fichier setting.
Si absent du setting la source est "présente" dans les logs mais pas de retour résultat, alors que si présente il y a retour de résultats.
A savoir que quand tu active/désactive une source c'est le fichier setting que crée Kodi qui ce modifie.
Kodi==> userdata==>addon_data==>plugin.video.vstream

**Comment by milkibreizh** [comment]
@razorex 
A quel idiot j’étais dans le fichier setting qui est  dans Kodi
C:\User\....\Kodi\addon\plugin.video.vstream\resources

bon maintenant que tu me dis cela cela 
doit être un fichier qui charge les settings de vstream
et pendant tout ce temps je l'ai pas vu ce fichier ?je suis vraiment bigleu :-)

j'ai pas de kodi sous la main je vais voir cela ce soir

merci

**Comment by milkibreizh** [comment]
bonjours
cela marche enfin:

Ajout id/ bool dans le fichier settings.xml
(@razorex merci pour l'info ,Kodi==> userdata==>addon_data==>plugin.video.vstream ):

`<setting id="plugin_ajouter_une_source">true</setting>`

Maintenant kodi prends bien en compte les parametres du menu
la petite croix reste bien active ou non active 
(valeur du paramatre true ou false pour le nouvel id créé)
 
le site apparait bien cette fois ci dans le log des recherches globales et
je retrouve ainsi les resultats escomptés 

je regardais dans le mauvais fichier de configuration

A moins qu'il y ait un inconvenu de méthode 
de mon coté l'issue semble avoir été resolue

merci

**Comment by razorex** [comment]
Pour être clair quand tu crée une source pas utile au début de la mettre dans le setting, une fois que ta source est "totalement" opérationnel tu la déclare dans le fichier setting de vStream (dans le dossier resources). Kodi va lire ce fichier au démarrage de vStream et créer son fichier setting, celui qui est sous Kodi==> userdata==>addon_data==>plugin.video.vstream

**Comment by milkibreizh** [comment]
@razorex 

tu avais été déjà été très très clair 
sur ton post précédent
et j'avais donc un gros gros doute justement
sur ma méthode inconvenue

car la méthode que tu m'indiquais était bien celle que j'avais faite
des le debut sans que cela puisse marcher d’où ce bricolage


j'ai retenté en prenant soins
de supprimer l'id que j'avais rajouter dans le userdata de kodi

et cela marche (sans bricolage)

A mon avis j'ai du oublier d'ajouter le terme 'plugin_' dans l'id
que j'avais remarqué et ajouté pourtant
ou fait une erreur dans le label..!
mais c'est certainement du à un très gros manque de rigueur de ma part  :disappointed:

mieux vaut donc que tu ferme l'issu au plus tôt pour éviter que tous le monde vois dans cette
longue discussion que le problème ne venait que de moi  :laughing:

merci

**Comment by razorex** [comment]
Ok
