### ISSUE TITLE
Qui utilise le build xenon 2 et qui a un problème avec url resolver (orphaned)

### ISSUE THREAD

**Issue by stanler2659** [Kodi-vStream/venom-xbmc-addons#2949]
**Décrivez le bug**
J’utilise xénon 2 comme build et quand j’installe le scripte url resolver en zip file sa install bien ! J’installe vstream ok ! Si je fait lupdate de url resolver par xénon paff url resolver devient impossible à configurer et si j’installe la bêta de vstream en zip file bien url resolver devient orphaned ...

J’ai passer des heures à essayer de comprendre pk y devient toujours orphaned :/ 
J’aurais bien aimé que vstream utilise resolver url à la place tout problème de malware avec tva addons serait réglé... la plupart des build retire url resolver du à ça ... 
j’ai besoin d’aide car j’aime bien le build de xénon et le problème de url resolver avec ce build reste la :( 

**Votre system**
 - OS: [Windows, Android] Android 
-  Appareil [nvidia shield, Ultra] Nvidia shield 2017
 - Version Kodi  [16.17.18] 18.7
- Version Vstream dernière version 

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**

https://imgur.com/a/TaoMPXY

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by alKODIque** [comment]
Est=ce possible que ton build utilise plutot le scrip ResolveURL et non URLresolver ?

**Comment by stanler2659** [comment]
> Est=ce possible que ton build utilise plutot le scrip ResolveURL et non URLresolver ?
> 
> EDIT: ha désolée, j'avais pas vu la partie ou tu parles de ResolveURL

Ouais le build utilise resolver url pour partout mais vstream utilise url resolver qui demande d’être configuré or vstream mais url resolver devient banni par presque tous les build du au malware qui fait installé par tva addons ! 

Je sais pas si c’est xénon qui fait en sorte que quand je met la bêta sa le met orphaned mais je catch pas :/ si les programmeurs de vstream pourraient mettre resolver url à la place sa règlerait ce genre de problème ... malware et orphaned ! 

Car la je sais pas du tout comment régler ce problème ...

**Comment by alKODIque** [comment]
Ha je sais... 
TV-Addons et ses bonnes idées grrr...  Disons que je ne les porte pas vraiment dans mon coeur....

De mon côté, j'ai enlevé la dépendance qui nous contraint à installer indigo dans urlresolver et rezipé le tout pour partager... si tu veux je te fait parvenir mon lien.

Quant au problème de ton build, je ne peux malheureusement pas t'aider puisque je n'en utilise pas. Je préfère faire mon propre built et de cette façon je garde plein contrôle sur mon installation.

**Comment by stanler2659** [comment]
> Ha je sais...
> TV-Addons et ses bonnes idées grrr... Disons que je ne les porte pas vraiment dans mon coeur....
> 
> De mon côté, j'ai enlevé la dépendance qui nous contraint à installer indigo dans urlresolver et rezipé le tout pour partager... si tu veux je te fait parvenir mon lien.
> 
> Quant au problème de ton build, je ne peux malheureusement pas t'aider puisque je n'en utilise pas. Je préfère faire mon propre built et de cette façon je garde plein contrôle sur mon installation.

Ouais j’ai le lien aussi sans indigo arias a fait le fichier script ! Et sa fonctionne seulement quand je met la bêta zip de vstream url resolver devient en mode orphaned ... je pense pt arrêter d’utiliser le build xenon a cause de ca meme si j’aimais bien l’interface!

**Comment by razorex** [comment]
Moi çà m'interesse le script d' @Arias800

**Comment by Arias800** [comment]
C'est pas un script mais un simple guide où j'ai détailler les étapes :
[Installer_URLResolver_sans_Indigo.pdf](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4809767/Installer_URLResolver_sans_Indigo.pdf)
