### ISSUE TITLE
SVP changer urlresolver pour resolveurl

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2950]
Bon,
Je sais que le sujet a été abordé a quelques reprise mais je me permet de le faire à nouveau puisque ça devient presque nécessaire de faire la modification..
Je sais que vous travailler tous d'arrache-pied a améliorer vStream, sans parler des difficultés que vous rencontrez avec CloudFlare...

Sur cette page: 
https://github.com/jsergio123/script.module.resolveurl#scriptmoduleresolveurl

Il est expliqué comment faire la transition. Je m'offre a vous aider, si il vous est impossible d'y jeter un oeil..  j'ai un compte debrideur pour tester le résultat et même que si l'un d'entre-vous peut me dire ou exactement dans le fichier xml je doit ajouter les lignes:

requires
    <import addon="xbmc.python" version="2.1.0"/>
    <import addon="script.module.resolveurl" version="5.0.00"/>
/requires
Ainsi que:

import resolveurl as urlresolver
resolved = urlresolver.resolve(url)

Et bien je le ferai avec plaisir et vous ferai ensuite parvenir un pull request.. 

Merci beaucoup d'avoir pris le temps de lire cette demande a nouveau

Et Grand Merci pour votre travail

**Comment by alKODIque** [comment]
Sous ma version (ou je suis partie du patch offert par ludopotte car il n'est plus possible d'utiliser de debrideur lorsque nous sommes sous Android depuis vos modifications à la bêta, j'ai réussi à changer la dependance pour resolvurl..

**Comment by Arias800** [comment]
> ça devient presque nécessaire de faire la modification..
En quoi ? Car resolveurl c'est un fork de UrlResolver. Toutes les modification appliquer a resolveurl son appliquer sur UrlResolver au bout de quelques temps.

Je suis pas contre faire cette modification, mais temps que personne ne donne de raison valable, on ne la fera pas. Sans compter que UrlResolver est bien plus simple a obtenir que resolveurl (qui ne propose pas de zip directement téléchargeable).

**Comment by alKODIque** [comment]
Urlresolver exige l'installation forcée de Indigo..  puis a son tour indigo apporte son lot de trucs que nous ne voulons pas sur notre installation. 

 une tres grande majorité d'additiels ont fait le changement vers resolveurl. Les plus utilisés l'ont tous fait.  
Pour le zip, j'ai ceci:

https://u.pcloud.link/publink/show?code=XZSqAUkZtXE31o3wzqfaUHyzhMy3b8aaK7oX

(Désolée, je suis sur mon iphone)

C'est le développeur qui a pris en charge officiellement le maintien du script.

Merci de ton temps, et pas de soucis si jamais vous n'avez pas le temps de faire la modification maintenant... 

De mon côté, je n'utilise aucun autre addon que vStream puis comme j'ai reussi à bidouiller quelque chose pour me débarrasser de urlresolver ... de plus, il est facile d'enlever la dependance d'indigo... mais la plus part des utilisateurs ne savent pas comment le faire et sont donc envahis des "malwares" de TVaddons... je trouve ça dommage car étant donné le manque de connaissance, ils associent ce fait a vStream quand c'est pas dutout le cas. Il n'y a aucun autre additiel qui arrive même à la cheville de vStream! Côté durée de vie, maintien, soutien et qualité, vous êtes loin devant!

**Comment by Arias800** [comment]
Alors, Indigo n'est pas un malware, c'est plus un pup (potential unwanted program) qu'autre chose. Mais c'est sur qu'ils ne sert a rien. J'ai d'ailleurs fait un tutoriel pour l'enlever, et il ne demande aucun connaissance. Sans compter que les gens peuvent se partager le fichier "corrigé" entre eux.
Ensuite non Resolveurl n'est pas maintenu par la personne qui est a l'origine de l'addon.
UrlResolver est mieux mis a jour que ResolverUrl, car il a les modification de ResolverUrl d'intégrer ainsi que d'autres.
On a bien préciser, dans le menu réglage, que Vstream n'est pas affilié a UrlResolver. Si les gens ne savent pas lire c'est pas mon problème xD

**Comment by alKODIque** [comment]
D'accord, je respecte votre point de vue

Merci pour le retour

**Comment by Arias800** [comment]
C'est pas une modification a faire a la légère, car ça peu bloquer beaucoup de personne qui peuvent ne pas comprendre qu'ils doivent changer d'addon, ni comment procéder.

**Comment by alKODIque** [comment]
Je comprends très bien... pas de soucis! :)
