### ISSUE TITLE
Time2Watch

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2951]
![C1049C2B-E14E-45A4-B3DE-495C9D8F81EC](https://user-images.githubusercontent.com/49578130/85325397-8dc95780-b499-11ea-931b-fd5b37edc78d.png)
Bonjour à vous,

Le site Time2Watch a changé son procédé de verification par image (captcha) .. Maintenant, les dossiers contenant les liens dans vStream ne s'ouvrent plus pour moi
 - OS: Android
-  Appareil Nvidia Shield
 - Version Kodi  18.7
- Version Vstream: 8.01

**Comment by Ovni-crea** [comment]
ça va être compliqué ils utilisent recaptcha maintenant peut être que c'est compatible avec la méthode de @Arias800

**Comment by Arias800** [comment]
Faut que je recode une partie de l'affichage, donc je pense que je m'en occuperai ce week-end.

**Comment by alKODIque** [comment]
Merci beaucoup :)

**Comment by yas06** [comment]
merci c cool car c est vraiment une bonne source

**Comment by Arias800** [comment]
Corriger dans le beta : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/0f468eebf467a13d1389bf9163fac25dd6804733

**Comment by alKODIque** [comment]
Merci!

**Comment by alextreme7711** [comment]
Arias800,
comment ont s'y prend avec ton update dans Vstream svp
Merci!

**Comment by yas06** [comment]
salut merci beaucoup arias800 pour ton travail
alextreme7711 moi avec le compte(T2W) activer j ai jamais eu les liens j ai compte realdbrd
 je vais tester la mise a jour d arias voir si c ok 
spmc/android tv/

**Comment by yas06** [comment]
salut j ai tester la beta ca fonctionne mais bizarement quand j active le resolver que ce soit sur pc ou android plus de liens vu que j ai real debrid je vois plus aucun liens 
est ce que vous ca fonctionne si oui quel version de urlresolver avez vous ?

**Comment by alKODIque** [comment]
Et bien voilà,
J'avais exactement le même problème 

Voir ici:

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2932

**Comment by yas06** [comment]
salut bon j ai pris la dernière beta toujours pas de liens donc j ai bien lu alKODIque ton post j ai recup ton fichier txt je l ai mis dans vstream c bon j ai les liens mais pas tous, c trop bizzard j ai mis sur mon drive les fichier vstream et url resolv dernier version sans indigo si tu veut tester dit moi si je met le lien du drive ici

**Comment by alKODIque** [comment]
J'ai moi une version de vStream ou j'ai changé la dependance vers resolveurl au lieu de urlresolver. Ça fonctionne très bien.. la voici si tu la veux.

Je viens de voir que @TmpName  a fait quelques maj a la beta concernant ce fâcheux problème de resolver... je vais tester Ce qui en résulte! Il a installé urlresolver pour tester :))

**Comment by stanler2659** [comment]
> @yas06
> 
> Tu es sous Android?
> 
> J'ai moi une version de vStream ou j'ai changé la dependance vers resolveurl au lieu de urlresolver. Ça fonctionne très bien.. la voici si tu la veux.
> 
> Je viens de voir que @TmpName a fait quelques maj a la beta concernant ce fâcheux problème de resolver... je vais tester Ce qui en résulte! Il a installé urlresolver pour tester :))
> 
> https://u.pcloud.link/publink/show?code=kZNOjIkZiF7O05zBbWLKqK9cVrq4FHK6HnGk

WoW tu as une version vstream qui fonctionne avec resolver url au lieu de url resolver ? Si oui je veux ça svp ! Tu peux me l’envoyer sur mon gmail stanler2659@gmail.com

Sinon je suis sur discord aussi le discord de vstream !

**Comment by alKODIque** [comment]
Oui effectivement!
On a qu'à installer mais attention, j'ai retiré la dependance au repo officiel pour éviter que urlresolver ne revienne.. 
Tu peux conserver le lien, jusqu'à maintenant je mets a jour lorsqu'il y a des changements dans la bêta régulièrement...

**Comment by stanler2659** [comment]
> Oui effectivement!
> On a qu'à installer mais attention, j'ai retiré la dependance au repo officiel pour éviter que urlresolver ne revienne..
> Tu peux conserver le lien, jusqu'à maintenant je mets a jour lorsqu'il y a des changements dans la bêta régulièrement...

Super merci est ce que je dois deleter ma version avant de mettre celle ci ou je peux installer par dessus ? 

Je vais devoir aller dans les settings de compte universelle Et sa va passer par resolver url au lieu de url resolver ?

**Comment by alKODIque** [comment]
Tu n'as qu'à installer par dessus puis tu fais exactement comme a l'habitude pour autoriser ResolveUrl a l'intérieur de vStream dans les paramètres.
J'ai aussi déposé a l'intérieur de mon dossier (accessible via le lien) le dépôt de resolveurl pour profiter des dernières maj de resolveurl.

Dis-moi si tu rencontres des problèmes d'installation. Je n'ai rien testé dutout sous Windows. Seulement sur ma shield (Android)

**Comment by stanler2659** [comment]
> Tu n'as qu'à installer par dessus puis tu fais exactement comme a l'habitude pour autoriser ResolveUrl a l'intérieur de vStream dans les paramètres.
> J'ai aussi déposé a l'intérieur de mon dossier (accessible via le lien) le dépôt de resolveurl pour profiter des dernières maj de resolveurl.
> 
> Dis-moi si tu rencontres des problèmes d'installation. Je n'ai rien testé dutout sous Windows. Seulement sur ma shield (Android)

Super je suis sur shield aussi je test ça tentot merci énormément :) viens me jaser sur le discord de vstream si possible !

**Comment by alKODIque** [comment]
Tu peux me donner le lien pour discord?
Je possède l'appli mais je suis pas familière avec

**Comment by stanler2659** [comment]
> Tu peux me donner le lien pour discord?
> Je possède l'appli mais je suis pas familière avec

https://discord.gg/4Df6nM

**Comment by alKODIque** [comment]
Salon en lecture seulement c'est inscrit

**Comment by stanler2659** [comment]
> Salon en lecture seulement c'est inscrit

Donne moi ton nickname sur discord je vais te chercher !

**Comment by yas06** [comment]
salut oui je suis sur android principalement je vous rejoins sur discord

**Comment by Che-debarras** [comment]
Maj beta de vstream ne s'installe plus car il ne trouve pas la dependance urlresolver pourtant installé
