### ISSUE TITLE
CF & sources

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2961]
**Décrivez le bug**

Je viens de vérifier tirexo ne semble pas utiliser cloudfare avec sa version 3  et son nouveau lien https:/ /ww w.tirexo .com.
On ne voit pas la page de protection cloudfare si on va directement sur le lien mais avec votre lien sur tirexo.py on a cette protection cloudfare 

De même pour hdstrm, pour papstrm et dpstrm m, je ne vois pas de protection cloudfare sur leur page d'accueil

Donc ces 4 sources devraient fonctionner sur vstream sans sélénium ou cloudfare non?

**Comment by razorex** [comment]
oui elle fonctionnent

**Comment by Che-debarras** [comment]
> oui dpstream, hds, papstream fonctionnent sans selenium

Sauf que leur dossier sont vide comme indiqué sur le suivi de bug.
S'il est possible de corriger quand vous aurez le temps

Et tirexo?

**Comment by Ovni-crea** [comment]
@Che-debarras Si ils ont toujours cloudflare c'est juste que tu as les cookies du coup tu ne les vois plus si tu veux savoir vraiment passe en navigation privé et tu tests

**Comment by Ovni-crea** [comment]
Bon pour les autres ça va ont peux réglé ça par contre pour papstream j'ai pas de problème avec

**Comment by razorex** [comment]
Chez moi çà marche

**Comment by Ovni-crea** [comment]
@razorex Dpstreaming c'était l'urlmain qui faut changer

**Comment by Che-debarras** [comment]
> @Che-debarras Si ils ont toujours cloudflare c'est juste que tu as les cookies du coup tu ne les vois plus si tu veux savoir vraiment passe en navigation privé et tu tests
> 
> Edit: bon je viens de voir c'est très bizarre pour tirexo en revanche dl protect utilise toujours cloudflare donc c'est peut être temporaire

Tu parles des cookies sur vstream?

**Comment by Ovni-crea** [comment]
@Che-debarras bah en fait tu as raison tirexo ont désactiver le compte à rebours mais sur dlprotect non donc on reste quand même sur selenium vu que dl protect utilise aussi la v2 de cloudflare

**Comment by Ovni-crea** [comment]
![ggstezse](https://user-images.githubusercontent.com/13500478/85898406-7f15d400-b7fc-11ea-84e9-533e52240c93.PNG)
Regarde si je désactive selenium ça donne sa

**Comment by alKODIque** [comment]
> ![ggstezse](https://user-images.githubusercontent.com/13500478/85898406-7f15d400-b7fc-11ea-84e9-533e52240c93.PNG)
> Regarde si je désactive selenium ça donne sa
> 

Le lien de tirexo n'a pas a y voir? C'est maintenant www et non www2

**Comment by Ovni-crea** [comment]
@alKODIque bon ça fonctionne mais dlprotect ne fonctionne pas donc ça ne sert à rien on est quand même bloqué par cloudflare

**Comment by alKODIque** [comment]
> @alKODIque bon ça fonctionne mais dlprotect ne fonctionne pas donc ça ne sert à rien on est quand même bloqué par cloudflare

Oui je vois..
Sur leur site, malgré le fait qu'il y a maintenant l'option de copier-coler le lien directement dans la page, une fois fait, cloudflare embarque..

Demande-moi si j'aime cloudflare loll
Ya jdownloader qui ont un gros soucis aussi avec cf... ils ont même invité les sites à le laisser tomber... ça va peut-être aider la cause  ;)

**Comment by Ovni-crea** [comment]
les gars laiiser tombé il y a une grosse panne chez cloudflare `https://www.cloudflarestatus.com/`

**Comment by Ovni-crea** [comment]
@alKODIque De toute façon cloudflare ça devient pire en pire vous allez voir d'ici là ils vont forcer avec hcaptcha ont va rien comprendre

**Comment by Che-debarras** [comment]
> > ![ggstezse](https://user-images.githubusercontent.com/13500478/85898406-7f15d400-b7fc-11ea-84e9-533e52240c93.PNG)
> > Regarde si je désactive selenium ça donne sa
> 
> Le lien de tirexo n'a pas a y voir? C'est maintenant www et non www2

C'est ce que j'ai mentionné dans mon 1e post le lien a changé.

Sauf que je pense que les plus nombreux a utiliser kodi et vstream sont sur android car ce sont des appareils mobile ou branché sur tv.

Si les sources sont inaccessibles sur android, vstream sera moins utilisé voir pas du tout a long terme non?
Faut pas que la compatibilité android s'arrête.

**Comment by Ovni-crea** [comment]
@Che-debarras Je sais mais on a pas le choix c'est pas de ma faute si android fonctionne différemment et puis bon c'est pareille faut dire aux sites d'arrêter d'utiliser cloudflare je sais pas si t'es au courant des news mais le pdg de cloudflare surveille github si jamais ont fait un script qui contourne cloudflare on peux dire adieu à Vstream (bon j'abuse mais quand même ) Si jamais le pdg en a marre il a juste a supprimé le github 
J'aurais vraiment aimé trouvé la solution ultime mais malheureusement non

**Comment by Che-debarras** [comment]
> @Che-debarras Je sais mais on a pas le choix c'est pas de ma faute si android fonctionne différemment et puis bon c'est pareille faut dire aux sites d'arrêter d'utiliser cloudflare je sais pas si t'es au courant des news mais le pdg de cloudflare surveille github si jamais ont fait un script qui contourne cloudflare on peux dire adieu à Vstream (bon j'abuse mais quand même ) Si jamais le pdg en a marre il a juste a supprimé le github
> J'aurais vraiment aimé trouvé la solution ultime mais malheureusement non

Non je reproche à personne la situation, juste que c'est dommage que ce CF pose problème et effectivement j'allais le dire. 

C'est quoi l'intérêt de CF sur les sites de streaming?
Venomous a un script poir contourner et il fait payer donc je pense que s'ils surveiller github, il serait deja sur le github de venomous.

Enfin bref j'espère qu'une autre solution arrivera un jour.

Même pour Chrome sur coreelec et libreelec c'est que pour les portages windows car sur android n'a pas de gestionnaire de fenetre.

**Comment by Ovni-crea** [comment]
@Che-debarras L'intérêt de CF c'est de protégé les sites contre des attaques DDOS pour ce qu'il est de venomous justement il est sur son github mais il le laisse pour se moquer de lui (pour être plus poli ^^) 
htt ps://twitter.com/eastdakota/status/1273277839102656515

Moi aussi j'espère vraiment une solution ultime (ou même la fin de  cloudflare  je ne serais pas contre)

**Comment by alKODIque** [comment]
> > > ![ggstezse](https://user-images.githubusercontent.com/13500478/85898406-7f15d400-b7fc-11ea-84e9-533e52240c93.PNG)
> > > Regarde si je désactive selenium ça donne sa
> > 
> > 
> > Le lien de tirexo n'a pas a y voir? C'est maintenant www et non www2
> 
> C'est ce que j'ai mentionné dans mon 1e post le lien a changé.
> 
> Sauf que je pense que les plus nombreux a utiliser kodi et vstream sont sur android car ce 
> C'est ce que j'ai mentionné dans mon 1e post le lien a changé.
> 
> Sauf que je pense que les plus nombreux a utiliser kodi et vstream sont sur android car ce sont des appareils mobile ou branché sur tv.
> 
> Si les sources sont inaccessibles sur android, vstream sera moins utilisé voir pas du tout a long terme non?
> Faut pas que la compatibilité android s'arrête.



> > > ![ggstezse](https://user-images.githubusercontent.com/13500478/85898406-7f15d400-b7fc-11ea-84e9-533e52240c93.PNG)
> > > Regarde si je désactive selenium ça donne sa
> > 
> > 
> > Le lien de tirexo n'a pas a y voir? C'est maintenant www et non www2
> 
> C'est ce que j'ai mentionné dans mon 1e post le lien a changé.
> 
> Sauf que je pense que les plus nombreux a utiliser kodi et vstream sont sur android car ce sont des appareils mobile ou branché sur tv.
> 
> Si les sources sont inaccessibles sur android, vstream sera moins utilisé voir pas du tout a long terme non?
> Faut pas que la compatibilité android s'arrête.

J'appuie!
Mais je comprends aussi que la majorité des développeurs developpent via windows... alors c'est normal qu'android passe en dernier pour eux... 

Bref, je me sens quand-même choyée d'avoir accès à vStream gratuitement malgré les limitations grandissantes via android

**Comment by Che-debarras** [comment]
> EDIT: Je ne te reproche rien je sais que c'est d'avoir une très bonne source et on te l'enlève :(

J'ai habitude mais c'est chiant de changer, là pour les series je suis sur DpStrmng pour les series (avant c'étaitseriestrmngHD mais avec netu qui marche jamais.
Bref, l'avantage avec Vstream c'est qu'il y a de nombreuses sources  quitte a regarder une saison chez l'un et une saison chez l'autre.

**Comment by Arias800** [comment]
C'est pas une question qu'Android passe en dernier, c'est juste que c'est infâme de développer avec xD
Pour Netu c'est recaptcha le problème. Ont réfléchit aussi a une moyens de contournement, mais pour le coup c'est encore plus compliquer que CF xD

**Comment by razorex** [comment]
Pour info hdstream est corrigé.

**Comment by amidevous** [comment]
> 
> 
> > > ![ggstezse](https://user-images.githubusercontent.com/13500478/85898406-7f15d400-b7fc-11ea-84e9-533e52240c93.PNG)
> > > Regarde si je désactive selenium ça donne sa
> > 
> > 
> > Le lien de tirexo n'a pas a y voir? C'est maintenant www et non www2
> 
> C'est ce que j'ai mentionné dans mon 1e post le lien a changé.
> 
> Sauf que je pense que les plus nombreux a utiliser kodi et vstream sont sur android car ce sont des appareils mobile ou branché sur tv.
> 
> Si les sources sont inaccessibles sur android, vstream sera moins utilisé voir pas du tout a long terme non?
> Faut pas que la compatibilité android s'arrête.

regarde ici tirexo et zt fonctionnelle sur android

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2956#issuecomment-667546465
