### ISSUE TITLE
mise a jour

### ISSUE THREAD

**Issue by drec78** [Kodi-vStream/venom-xbmc-addons#2963]
salut pourquoi les sites allfilm et channel stream n'apparaisse pas sur vstream  la mise a jour automatique est active mais rien est affiche merci a vous

**Comment by TmpName** [comment]
C'est parce qu'il ne sont que sur la beta encore, pas encore officiels.

**Comment by Che-debarras** [comment]
> C'est parce qu'il ne sont que sur la beta encore, pas encore officiels.

Pour infos les maj manuels de la beta ne s'installent pas car message de dependence non trouvé,  celle de urlresolver alors qu'il est installé

**Comment by Arias800** [comment]
C'est corrigé, par contre il faut obligatoirement la toute dernière version d'UrlResolver.

**Comment by Che-debarras** [comment]
> C'est corrigé, par contre il faut obligatoirement la toute dernière version d'UrlResolver.

C'est laquelle la dernier version? 5.1.1.?

**Comment by Arias800** [comment]
Oui, c'est la 5.1.1.

**Comment by Che-debarras** [comment]
> Oui, c'est la 5.1.1.

Merci et effectivement l'installation de beta est corrigé, pas de pb de dependance

**Comment by Che-debarras** [comment]
> salut pourquoi les sites allfilm et channel stream n'apparaisse pas sur vstream la mise a jour automatique est active mais rien est affiche merci a vous

De toute façon les chaines de channel stream ne marche plus

**Comment by alKODIque** [comment]
A totre informatif, je viens de vour que tvaddons a retiré sa dépendance forcée a Indigo dans urlresolver. De plus, il rend disponible les dernières versions à jour de UrlResolver ET de ResolveUrl via:

https://fusion.tvaddons.co/kodi-scripts/

A+
