### ISSUE TITLE
Netu et zt hs ? 

### ISSUE THREAD

**Issue by Gayed92** [Kodi-vStream/venom-xbmc-addons#2965]
Bonjour j'ai plus accès à netu sur certains fournisseurs qui proposait aussi goudlulited un truc comme ça mais je voulais savoir depuis maintenant un mois j'ai plus tirexo, zt! Ça ouvre mais y a aucune série pourtant j'utilise un Vpn ! Avez vous ce problème avec vstream ? Merci

**Comment by TmpName** [comment]
Alors neta, oui c'est normal, et ca reviendra pas avant un moment.

Tirexo, @Ovni-crea est sur une version speciale qui marchera sur tout sauf android.

ZT encore en attente, pour le meme soucis que Tirexo.

**Comment by Gayed92** [comment]
Merci tmp pour l'info ! Il me semble que tirexo fonctionnait sur Android ya 2 mois pourtant mais je vais patienter reste pas grand chose en français

**Comment by TmpName** [comment]
Ben y a quand meme plusieurs dizaines de sources dispos.
