### ISSUE TITLE
two word concatenation on research

### ISSUE THREAD

**Issue by devzhr** [Kodi-vStream/venom-xbmc-addons#2967]
**two word concatenation on research**

when I have done in the search for a film has a name composed for example **the red cross** I find other films has that the word **the** and others has that the word **cross** normally if there is not a film has all 3 words at the same time

**Comment by milkibreizh** [comment]
hi
the results are  the sum results of each site who process they own research  .
you can disabled or enable  this global search
in a menu
vtsream can't control the research  result  of each site
