### ISSUE TITLE
problème mise à jour 8.0.01

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#2969]
j'ai reçu il y a déjà 4 jours la mise à jour  8.0.01 sur mon projecteur (interface android)
MAIS JE NE RECOIS PAS  cette mise à jour sur mes autres appareils :

sur ma frebox  freebox mini 4k (android)   kodi 18.7
sur ma tablette android  kodi 18.7
sur mon téléphone android  kodi 18.7

généralement elles arrivent parfois en différées mais 4 jours me parait inhabituel ...

**Comment by TmpName** [comment]
Et ils sont sur quelle version de Vstream ? Parce qu'elle date de 1 mois, ils ont deja du etre mit a jour il y a longtemps.

**Comment by kris06** [comment]
salut tmpName   version 8.0.0

**Comment by TmpName** [comment]
OK, alors j'ai le meme soucis. Quelqu'un peut confirmer ?

Dans les options de Vstream, dans "A propos / sources", la version affichées est la 0.8.0.0

**Comment by TmpName** [comment]
Ok alors je viens de faire une modif sur le fichier about.py, si tu veux l'editer de la meme maniere pr tester.

Par contre d'ou vient ce bug, et pourquoi tout le monde n'est  pas touché ......

**Comment by kris06** [comment]
beaucoup de sources ne fonctionnent plus sur version 8.0.0  ou en 8.0.01     ...
merci

**Comment by Che-debarras** [comment]
> beaucoup de sources ne fonctionnent plus sur version 8.0.0 ou en 8.0.01 ...
> merci

Essaye d'installer la bêta  mais surtout oubli pas de changer le DNS  car beaucoup fonctionne qu'avec changement de DNS

**Comment by kris06** [comment]
merci CHE

Pourrais tu m'adresser le lien de la beta je ne la trouve pas
je te remercie
kris

**Comment by TmpName** [comment]
Ben https://github.com/Kodi-vStream/venom-xbmc-addons
Si c'est pas la beta par defaut (c'est le cas chez moi, mais c'est peut etre un reglage), dans "branch" tu prends "beta" au lieu de "master"

**Comment by kris06** [comment]
Salut,  je suis ravi de du retour de zone de téléchargement  cependant, tirexo est depuis longtemps inaccessible....
Ou presque, à présent,  la liste des films est visible, mais les liens uptobox (ou autres) restent sans effet...  
Est ce que tirexo fonctionne pour vous ? ou s'agit d'une correction prochaine ? 
merci

**Comment by Che-debarras** [comment]
> Salut, je suis ravi de du retour de zone de téléchargement cependant, tirexo est depuis longtemps inaccessible....
> Ou presque, à présent, la liste des films est visible, mais les liens uptobox (ou autres) restent sans effet...
> Est ce que tirexo fonctionne pour vous ? ou s'agit d'une correction prochaine ?
> merci

Je pense que les problèmes de uptobox sont liés a uptobox et non a vstream, chez moi sur zt certaines marches
Fait une recherche du film the old guard sur les 2 sources zt et vois si ça marche.
Moi cela a marché hier.

**Comment by kris06** [comment]
Ma question reposait essentiellement sur tirexo où je trouve bien ton film  the old guard mais le lien uptobox reste sans effet... En revanche il fonctionne parfaitement sur ZT ( source uptobox)

Pourquoi tirexo ne fonctionne plus depuis des mois ?
Enfin, n'y aurait il pas un moyen de contourner la limite de 72 minutes d' uptobox qui est particulièrement  frustrante lorsqu'un film est interrompu....

merci CHE,

**Comment by Che-debarras** [comment]
> Ma question reposait essentiellement sur tirexo où je trouve bien ton film the old guard mais le lien uptobox reste sans effet... En revanche il fonctionne parfaitement sur ZT ( source uptobox)
> 
> Pourquoi tirexo ne fonctionne plus depuis des mois ?
> Enfin, n'y aurait il pas un moyen de contourner la limite de 72 minutes d' uptobox qui est particulièrement frustrante lorsqu'un film est interrompu....
> 
> merci CHE,

Pour tirexo ça été expliqué qu'il faut contourner Cloudfare et pour l'instant la seul solution c'est Selenium.
Il y a un tuto qui explique comment l'utiliser mais si tu est sur android Selenium ne marche pas et ne marchera probablement jamais.

Donc pour android, tirexo est inutilisable avec ou sans Selenium et sans contourner cloudfare.
Que quelqu'un me corrige si je me trompe.

Pour les 72min tu dois sois d'inscrire sur le site uptobox et avoir un compte premium payant.

Tu peux aussi changer de IP (ya des applications qui change l'IP) et tu retrouve tes 72min

NB: je crois que la limite cest 120min et non 72min si je dis pas de bêtises.

Saches qu'il y a près de 40 sources sur Vstream, il ne faut pas rester bloquer sur les sites sous cloudfare qui sont aux nombres de 4 ou 5.

J'utilise jamais uptobox ni tirexo ni les sources ZT et pourtant je trouve tous ce dont j'ai envie.

**Comment by kris06** [comment]
en effet, je sais bien qu'il y a bien d'autres sources cependant,  tirexo reste la référence en terme de catalogue. Je suis un cinéphile et il n'y a rien d’équivalent ,  tu trouves tout ce que tu cherches sur tirexo , voir même l'improbable...

Quant aux changements d'IP, tu parles ici surement des vpn ?   ce dernier n'étant pas évident avec une freebox sous android..

je te remercie quand même d'avoir pris le temps de me répondre et te souhaite un bon WK
Kris

**Comment by alKODIque** [comment]
Film Streaming ne fonctionne plus de mon côté.

L'adresse Y faisant référence n'est plus accessible non plus sur le net.

Je ne sais pas si c'est récent et ne voit pas non plus si une autre adresse est dispo

**Comment by Che-debarras** [comment]
> Quant aux changements d'IP, tu parles ici surement des vpn ? ce dernier n'étant pas évident avec une freebox sous android..

Si tu peux installer des applo comme expressvpn ou tunnelbear ou simplement Hola Vpn, tu choisis le pays et tu laisee l'application en tâche de fond

Après on utilise plus des pc, ou tablette ou des box tv du coup jtinvite à acheter une box tv ou nvidia shield si tu as du mal avec la freebox ou peut etre ta tv est une android tv et tu install une appli vpn

**Comment by Che-debarras** [comment]
> Film Streaming ne fonctionne plus de mon côté.
> 
> L'adresse Y faisant référence n'est plus accessible non plus sur le net.
> 
> Je ne sais pas si c'est récent et ne voit pas non plus si une autre adresse est dispo

Non c'est pas récent je l'ai mis dans la liste des sources qui bug dans mon suivi 0.8.0.1

**Comment by alKODIque** [comment]
@kris06 
Uptobox n'a aucun problème.
Pour compléter les explications que @Che-debarras t'a donné, il faut bien comprendre ce qu'est vStream Et ce qu'il n'est pas...
vStream agit un peu comme un gros "scraper". C'est a dire qu'il récupère ce qui est déjà existant sur le net et le rend accessible sur kodi. Il ne crée rien, il ne transforme rien. Si un lien ne fonctionne pas sur le net, il ne fonctionnera pas plus sur vStream. Des liens morts, il y en a plusieurs... Si un site change d'adresse, il ne sera plus accessible via vStream tant qu'un développeur n'aura pas corrigé la source.  Nous avons la chance d'avoir une équipe très réactive qui gère les problèmes rapidement.. Suffit de cenir voir ici les issues partagées et la réactivité des développeurs qui prennent le temps d'expliquer et d'aviser des mesures qu'ils prennent pour satisfaire les utilisateurs

**Comment by alKODIque** [comment]
> > Film Streaming ne fonctionne plus de mon côté.
> > L'adresse Y faisant référence n'est plus accessible non plus sur le net.
> > Je ne sais pas si c'est récent et ne voit pas non plus si une autre adresse est dispo
> 
> Non c'est pas récent je l'ai mis dans la liste des sources qui bug dans mon suivi 0.8.0.1

Oupsss
Je doit mieux pratiquer ce que je prêche alors hihi (ref mon commentaire précédent)
