### ISSUE TITLE
Plantage de Kodi au lancement de Vstream

### ISSUE THREAD

**Issue by cedricam** [Kodi-vStream/venom-xbmc-addons#2970]
Plantage de Kodi au lancement de vstream.(Voir PJ)

 - OS: Linux Fedora 32
-  Appareil nvidia geforce/Intel
 - Version Kodi  18
- Version Vstream last
[bug.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4874825/bug.txt)

**Comment by TmpName** [comment]
Mais je suis pas sur que le bug vienne de vstream

>script.skin.helper.service
>script.module.metadatautils
