### ISSUE TITLE
Changement nom de Domaine ZT-ZA 

### ISSUE THREAD

**Issue by arzaz** [Kodi-vStream/venom-xbmc-addons#2972]
Désormais ZT a changer de nom de domaine: https://www.zt-za.com/
Abréviation : ZT(Zone-Telechargement)-ZA(Zone-Annuaire).COM

**Comment by Ovni-crea** [comment]
@arzaz Justement je suis en train de le faire par contre ils utilisent cloudflare

**Comment by Che-debarras** [comment]
Peut etre le remplacer par Zone annuaire.best et zone téléchargement.buzz (ce dernier est pas top mais bon)

Sinon chez moi ZT tlchrgmnt  fonctionne toujours

**Comment by Ovni-crea** [comment]
@Che-debarras `https://www.zone-annuaire.com/` ça fonctionne encore chez toi ?

**Comment by Che-debarras** [comment]
> @Che-debarras `https://www.zone-annuaire.com/` ça fonctionne encore chez toi ?

Oui toujours pourquoi?

**Comment by Ovni-crea** [comment]
@Che-debarras Je crois que c'est un problème de cache de toute façon @TmpName à merger la désactivation de ZTSTRM et je pense pas qu'il va vouloir garder un site à moitié fonctionnelle (sur navigateur impossible d'y accéder )

**Comment by Che-debarras** [comment]
> @Che-debarras Je crois que c'est un problème de cache de toute façon @TmpName à merger la désactivation de ZTSTRM et je pense pas qu'il va vouloir garder un site à moitié fonctionnelle (sur navigateur impossible d'y accéder )

Tu veux dire que si je supprime le cache de kodi et vstream, je devrais plus avoir ces 2 sources fonctionnelles ?
Pour moi il est fonctionnelle a 100pr100 et je dois pas être le seul, peut-être lle seul bon côté d'être sur android lol

Bref, pourquoi ne pas juste les désactiver par défaut et laisser l'utilisateur l'activer par lui-même si besoin?
C'est comme N1.strm ou d'autres qui bug mais ils sont quand même utilisable.
Justement sur un autre sujet on conseille de désactiver les sources indésirables.

**Comment by alKODIque** [comment]
J'ai supprimé le cache de mon côté. Et de kodi, et de vStream.
ZT fonctionne toujours à merveille

**Comment by alKODIque** [comment]
@Che-debarras 
J'ai exactement le même résultat que toi avec mon débrideur (si j'ai bien compris tes explications

**Comment by Ovni-crea** [comment]
@alKODIque @Che-debarras Bon si zone telechargement fonctionne alors on le garde j'écrirais de ne pas le merger pour l'autre trop tard @TmpName  la validé vous gardez le meilleure finalement

**Comment by Ovni-crea** [comment]
Ah bah les gars je comprends pourquoi ça fonctionne `https://www.forumzt.com/infos-at-f155/nouveau-domaine-pour-un-site-reconnaissable-et-plu-t6613.html`

**Comment by Che-debarras** [comment]
> @Che-debarras
> J'ai exactement le même résultat que toi avec mon débrideur (si j'ai bien compris tes explications
> https://imgur.com/gallery/tejTpv0
> https://imgur.com/gallery/ic4fnu7

Tout a fais ça marche bien, je vois pas pourquoi les supprimer

Sinon c'est quoi ton skin de kodi stp?
Je constate que tu as pas les mêmes icones des sources notamment ZTstream

**Comment by Ovni-crea** [comment]
@Che-debarras Malheureusement d'après les admins de zt oui

**Comment by Che-debarras** [comment]
> @Che-debarras Malheureusement d'après les admins de zt oui

Espérons un remplacement avec les clones .best

**Comment by alKODIque** [comment]
@Che-debarras 
C'est que j'ai changer quelques icônes afin qu'elles soient toutes uniformément du style transparent ;)

Mon skin c'est Arctic-Horizon
Disponible ici:
https://github.com/jurialmunkey/skin.arctic.horizon

**Comment by alKODIque** [comment]
@Ovni-crea 
D'accord! Tout s'explique alors :)

Merci!

**Comment by Che-debarras** [comment]
> @Che-debarras
> C'est que j'ai changer quelques icônes afin qu'elles soient toutes uniformément du style transparent ;)
> 
> Mon skin c'est Arctic-Horizon
> Disponible ici:
> 
> https://github.com/jurialmunkey/skin.arctic.horizon
> 
> J'ai quelques tutos pour ses réglages si ça t'intéresse ici:
> 
> https://u.pcloud.link/publink/show?code=kZnY2UkZOwaTvP7tOKB6yLhHsow1LLgpFftX

Merci beaucoup et oui des icônes uniformes ce serait plus agréable.
Pourrait tu les partages si ce n'est pas trop demandé

**Comment by alKODIque** [comment]
@Che-debarras 
Aucun problème pour les icônes.
Par contre, ce sont pour la plupart exactement les mêmes que celles déjà incluses dans vStream que j'ai simplement rendu transparentes avec un petit logiciel disponible gratuitement sur le net. Puis le rendu pour une ou deux d'entre elles n'est pas super alors lorsque j'en ai l'occasion, je re-transforme a nouveau 

Ce que je vais faire, c'est que je mettrai en évidence le dossier d'icônes que j'utilise dans mon lien de partage que je t'ai envoyé plus haut donc tu pourras y jeter un oeil de temps à autre et prendre celles qui te conviennent. (Tu verras qu'il y a la date de la dernière mise à jour inscrite au côté de chaque dossier) 
Je te tiendrai au courant lorsque j'aurai mi à disposition mon dossier d'icônes  :))
A+

**Comment by Che-debarras** [comment]
Je sais que dès le 15juillet les 2 sources ZT ne marcheront plus mais pour l'instant les film et séries qui étaient pas dispo hier le sont maintenant donc sans doute un délai avant quil soit accessible sur ces 2 anciens sites par rapport au nouveau.

NB: ce serais idiot de leur part de les supprimer car ya toujours une course pour interdire les sites de streaming donc il devraient garder ces 2 sources au cas où.

**Comment by alKODIque** [comment]
@Che-debarras 
Fait pour les logos. dosssier: "images & logos" via le lien partage plus haut
