### ISSUE TITLE
Possibilité de changer emplacement de la médiathèque 

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2977]
Bonjour à vous :)

Je me demandais pourquoi la possibilité de changer l'emplacement par défaut de la médiathèque de vStream est impossible Via les paramètres .. 

De mon côté, je suis allé Changer pour "True" au lieu de "False" dans le fichier setting afin de vérifier s'il y avait problème et puis j'ai testé. Tout fonctionne bien en ayant changé l'emplacement vers mon stockage externe. Les films et les séries s'y ajoutent et aucun problème non plus pour le visionnage.

La raison pour laquelle j'aime bien avoir la médiathèque a autre part que dans addondata, c'est que si j'ai a désinstaller vStream, j'ai toujours mes films et séries disponibles sans devoir aller faire un copier-coller des dossiers vers mon stockage externe avant de supprimer l'addon. Très pratique avec un compte uptobox puisque les liens demeurent... (Je sais que faire l'ajout de médias directement via un site est risqué puisque les liens sont parfois éphémères)

Je suis sous Leia 18.2
vStream 0.8.0.1
Android, nvidia Shield

S'il y a une raison particulière pour que la zone soit "grisée" dans les paramètres, svp m'en aviser

Merci a toute l'équipe pour votre travail :)

A+
[settings.xml.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4902676/settings.xml.txt)

**Comment by TmpName** [comment]
Tiens bonne question, quelqu'un se souvient ?

**Comment by alKODIque** [comment]
@TmpName 
Bah je crois que la majorité des utilisateurs vStream n'utilisent pas cette fonctionnalité alors ce n'est pas bien grave si elle n'est pas accessible par défaut...  Si vient le temps ou plusieurs en seront affectés alors peut-être vaudra-t'il la peine de s'y attarder mais d'ici là, voys avez d'autres priorités à gérer!!
😉

**Comment by TmpName** [comment]
Sisi, je peux corriger ce de suite, d'ailleurs c'etait comme ca a l'origine, mais il ya forcement du se passer un truc a un moment pour que ca change.

**Comment by alKODIque** [comment]
@TmpName 
Effectivement,
Je me souviens sous jarvis/Krypton 
Qu'il était possible de le faire..

**Comment by TmpName** [comment]
Bon ben pas d'autre avis, du coup https://github.com/Kodi-vStream/venom-xbmc-addons/commit/3d55fa604a8f51a7a4ceb93570d19ce21c7b48eb#diff-fb6bba62cf0677e7befd217dd0a6e37f

**Comment by alKODIque** [comment]
Super!
Merci! Ça m'évitera de faire le changement à chaque mises à jour 😝
