### ISSUE TITLE
Addon limité aux comptes premium

### ISSUE THREAD

**Issue by speedjeje** [Kodi-vStream/venom-xbmc-addons#2978]
Bonjour la Team,
Une petite question d'un newbie comme moi ... est-il possible (sans trop s'y connaître) de créer un addon (vStream like) qui serait limité à la partie "Mes Comptes" dans vStream ?

Je m'explique :

J'utilise (quasi exclusivement) vStream pour sa fonctionnalité d'accès à mon compte UpToBox Premium.
Donc, je me demandais s'il était possible que je modifie les fichiers de l'addon pour n'avoir uniquement que cette fonctionnalité et pas la foule d'autres possibilités offertes par vStream ?

Merci pour la réponse et surtout MERCI pour cette magnifique extension !!!!

**Comment by Che-debarras** [comment]
> Bonjour la Team,
> Une petite question d'un newbie comme moi ... est-il possible (sans trop s'y connaître) de créer un addon (vStream like) qui serait limité à la partie "Mes Comptes" dans vStream ?
> 
> Je m'explique :
> 
> J'utilise (quasi exclusivement) vStream pour sa fonctionnalité d'accès à mon compte UpToBox Premium.
> Donc, je me demandais s'il était possible que je modifie les fichiers de l'addon pour n'avoir uniquement que cette fonctionnalité et pas la foule d'autres possibilités offertes par vStream ?
> 
> Merci pour la réponse et surtout MERCI pour cette magnifique extension !!!!

Il me semble que tu peux désactiver toutes les sources pour qu'il n'affiche que MON COMPTE UPTOBOX
sinon tu met cette source en favorien tête de liste c'est que je fais pour mes sources préférées

**Comment by TmpName** [comment]
Oui c'est ce que j'allais dire, tu peux faire ca proprement definitivement via les options.
Sinon "a la crade", tu vas dans le repertoire "sites" et tu effaces tout les autres.

**Comment by speedjeje** [comment]
Ah OK OK, merci pour les réponses
Je vais naviguer dans les options pour voir ça
Merci
