### ISSUE TITLE
Ajouter un sous titre & getMediaLink

### ISSUE THREAD

**Issue by milkibreizh** [Kodi-vStream/venom-xbmc-addons#2979]
Bonjours
j'ai une question concernant les  sous titres

l'instance  du player vstream :hoster. py /def play(self):..oPlayer = cPlayer()
utilise les paramètres de la fonction  aLink = oHoster.getMediaLink()
pour  ajouter  un sous titre. 
il correspond ,si il existe,au 3 eme paramètres aLink[2]
Donc si j'ai des hosters deja connus je ne peux  pas passer 
des sous titres avec la vidéo
dans un répertoire connu
ou
une url pointant sur un fichier srt.
A moins de recréer un nouvel hoster implantant la fonction 
getMediaLink() qui devra retourner True,url,sub
??? 
il n'y a pas un autre moyen d'accéder à l'attribut
oPlayer.AddSubtitles
pour l'instance du player vstream ?

**Comment by TmpName** [comment]
Houla, tu y vas fort un dimanche, j'ai pas du tout compris ce que tu essyes de faire ^^.

Qu'appelles tu un hoster deja connu ?

La fonction oHoster.getMediaLink() recupere les sous titre du hoster, si tu veux en utiliser d'autres part, tu passes directement par kodi, tu n'es pas obligé d'utiliser ceux la.

**Comment by milkibreizh** [comment]
@TmpName 

j'ai un fichier mp4 et un fichier srt je veux juste
que vstream charge directement le mp4 avec le fichier

j'ai essayer d'utiliser directement avec xbmc.Player ;xbmc.Player().setSubtitles
 mais j'ai pas réussi c'est pour cela que j'utilise le oPlayer = cPlayer() du fichier
hoster. py

**Comment by milkibreizh** [comment]
je ne veux pas utiliser les sous titres proposé par kodi lors de la lecture
mais directement jouer le mp4 avec le fichier connu
donc pour le site viki par exemple cela marche mais j'ai du 
créer un hoster

**Comment by TmpName** [comment]
Mais le fichier sous titre vient de la meme page que le mp4 ?

**Comment by milkibreizh** [comment]
@TmpName 

désolé de te déranger un dimanche par hyper beau temps

j'expliques

je fais le site viki
on peu récupérer les fichiers sous titres d'une video en effectuant une requête

j'ai fais une requête donc pour récupérer les titres que j'ai mis dans un dossier
path = xbmc.translatePath('special://temp/vstream/Frenchtitre.srt')

et je me retrouve avec se fameux checkoster.......!!

**Comment by milkibreizh** [comment]
autrement cela marche tres bien

mais justement imaginons que je fasse un site avec un host comme qload
et que pour une qqle astuce je connais deja le fichier srt

bah le hoster uqload ne prend en charge mon fichier srt a moins de le modifier

**Comment by milkibreizh** [comment]
@TmpName 
Et en bidouillant le fichier hoster qui extrait le mp4 ?
oui par exemple en modifiant le hoster pour les liens direct le site viki marcherais
drirectement il suffit d'ajouter un checksub ou un truc de se genre a l'appelle de getMediaLink()
mais je suis sensé pas toucher  ce fichier

**Comment by TmpName** [comment]
Pas de soucis, si je repond, c'est que je ne profite pas du beau temps ^^

Donc si j'ai bien compris, tu es sur le site viki, site qui n'utilises pas de hosters, vu que les video sont sur leur propre serveur.
Partant de la tu as 2 solutions, faire un hoster viki ou utiliser le hoster lien_direct.

Si tu fais un hoster viki, tu peu recuperer les liens des sous titres en meme temps que la video, et donc avoir les  2 en meme temps sur kodi.

Si tu es sur uqload, tu auras forcement des st pour le fichier uqload. Tu imagines a quel point cela complique le code de chercher d'apres le nom (qui peut etre n'importe quoi) sur ton disque dur si des sous-titres seraient compatible et surtout synchronisés ?

**Comment by milkibreizh** [comment]
@TmpName 

tu as raison pour uqload mais c'etais un (mauvais exemple)
moi je m'y connais pas trop en site de streaming
là il s'avére que le site donne le sub 

donc là en faite je viens presque de finir le site 

mais bon j'ai tout pompé sur vrai le viki@ add on
je l'ai juste adapté
si il y a problème concernant la copie et éviter de s’acager le travail
de l'auteur je peux ne pas la proposer
justement le seul élément important que j'ai copier est qu'il faut une clef
pour avoir les titres
autrement le  est tout à  faisable en requête normale
(bien que je n'ai pas trouvé comment faire une requête non api pour
charger la video c'est un fichier type mpd
https://github.com/peak3d/inputstream.adaptive

allez c'est l'heure de l’apéro je suis a la bourre (encore une fois) !!
bonne soirée

**Comment by milkibreizh** [comment]
je clos le poste
on est donc bien obligé de passer par les hosts (fichiers)
je reste donc sur ma première solution trouvée 
création d'un fichier host viki
mon but était juste de trouver une solution en créant un fichier site en évitant de créer
ou modifier d'autres fichiers tierce
merci @TmpName qui devrait un peu profiter du beau temps  ^^
