### ISSUE TITLE
Regrouper les sources Premium

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2980]
Bonjour!
Il y a plusieurs utilisateurs vStream qui, malgré l'identification des sources Premium (Fushia) ne comprennent pas  qu'il s'agit, justement, de sources donnant accès à des liens premium.

Je me demandais s'il serait possible de faire un regroupement ou encore un sous-groupe de ces sources dans le menu principal de vStream. En gros, s'il serait possible qu'à la place de voir "Sources", on puisse voir "Sources Premium" ET "Sources gratuites"...
Enfin, quelque-chose de la sorte...

Merci à vous :)
A+

**Comment by TmpName** [comment]
Ben y a deja eu un debat la dessus ^^.
En fait non, ce ne sont pas que des liens premiums, a l'origine c'etait les sites qui proposaient des telechargements, uptobox et onefichier proposent des comptes gratuits qui fonctionnent aussi.

Ensuite il y a le debat de ceux qui crient aux scandales si ils doivent faire un clic de plus en 2h de film, ici pour choisir premium/gratuit.

Pour moi l'utilisateur se fait avoir une fois, puis comprend le systeme pour les prochaines fois.

**Comment by alKODIque** [comment]
Ouais, en fait rien n'est jamais simple, je comprends..
Pas évident, faut essayer de plaire à la majorité tout en sachant qu'il est impossible de plaire à tout le monde!
Merci de ton retour, c'est apprécié :)
