### ISSUE TITLE
Listes personnelles compte TMDB

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2981]
Il m'est impossible de voir mes listes personnelles TMDB via mon compte avec vStream.
Je clique et puis rien ne se passe
voici la partie de mon log qui démontre l'erreur en attaché

Kodi Leia 18.7
nvidia shield
vStream 0.8.01 
![BCB3C481-A86A-47CB-BD8B-E2149B9F1463](https://user-images.githubusercontent.com/49578130/87998903-426d8d80-cac7-11ea-8fde-df5e3c8017b5.png)

**Comment by TmpName** [comment]
Alors la je me souvient plus trop mais

- tu vas dans "mes comptes"
- puis TMDB
- la tu vois ecrit "bonjour X" avec ton speudo
- Ensuite ?

**Comment by alKODIque** [comment]
@TmpName 
Alors voilà 
Lorsque j'appuie sur épisode noté, c'est normal qui ait rien puisque je n'en note pas hehe)

https://u.pcloud.link/publink/show?code=XZxVJakZ7bKgRCwLsfuBOyeBCBJ4JkpqE2jy

**Comment by sizanic** [comment]
Je n'ai pas de compte TMDB.

J'ai relu les dernières modifs, je n'ai pas vu de choses bizarres.

Par contre, à la lecture du code, je pose cette question : 
As-tu des caractères spéciaux dans tes noms de listes ?

**Comment by alKODIque** [comment]
> Je n'ai pas de compte TMDB.
> 
> J'ai relu les dernières modifs, je n'ai pas vu de choses bizarres.
> 
> Par contre, à la lecture du code, je pose cette question :
> As-tu des caractères spéciaux dans tes noms de listes ?

@sizanic 
Voilà! Tu as exactement ciblé le problème. D'ailleurs, il n'y a pas si longtemps je crois que Tmp_name ou @Arias à réglé exactement ce même problème avec les caractères accentués via le compte Uptobox 

J'aurais dû y penser  🤔 

![E3BAE392-284E-4C06-92DE-52FDD5FA7D4E](https://user-images.githubusercontent.com/49578130/88113940-d64f6000-cb80-11ea-928f-78b0c4f6696d.png)

**Comment by sizanic** [comment]
Alors ton problème est dans "Séries Québécoises", c'est un problème d'accent lorsque les acteurs parlent. 😆 
(désolé)

Sérieusement, je ne peux pas régler le problème sans compte.
Faut que quelqu'un d'autre s'y colle.

Si c'est bien ça, ça se passe dans tmdb.py, dans la methode _call (ligne 800), faut revoir les deux dernières lignes : 

```
        if '/lists' in action:
            try:
                name = unicode(name, 'utf-8')
            except:
                pass

            name = unicodedata.normalize('NFD', name).encode('ascii', 'ignore').decode('unicode_escape')
            name = name.encode('utf-8')
```

**Comment by alKODIque** [comment]
@sizanic 
Ha ha ha 😆 
Si tu savais les efforts que je fais pour au minimum utiliser un français "international " lorsque je communique avec mes cousins sur le net 🤣

Merci pour l'info, je regarde au niveau du code pour uptobox si je peux me démerder avec ce que tu m'a donné 

Je te tiens au courant 

A+

**Comment by alKODIque** [comment]
Voila, ça a fonctionné
Merci @sizanic 
et voici mon fichier
[tmdb.py.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/4956964/tmdb.py.txt)

**Comment by alKODIque** [comment]
Arfff
Ca a marché à moitié 

J'ai pas toutes mes listes 😢

**Comment by sizanic** [comment]
vu ta modif, je pense que tu as celles sans accents.

**Comment by alKODIque** [comment]
J'ai réglé ça bien proprement..hehe
J'ai retiré tous les caractères accentués de mes listes...

Les .encode .decode name blablabla ont des milliers de combinaisons possibles et même si je me force à comprendre la logique kodi veut juste pas. 

Avant de tout balancer par la fenêtre, j'ai décidé de faite la grève aux accents \o/

J'ai de belles listes épurées maintenant 
![1799C66B-314F-474C-AFE5-C1BFAEF5CC96](https://user-images.githubusercontent.com/49578130/88129694-bb8fe200-cba6-11ea-8251-5a476172a072.png)

**Comment by LordVenom** [comment]
Hi, rien a voir mais c'est quoi le nom de ton skin ?

**Comment by alKODIque** [comment]
@LordVenom 
C'est Arctic-Horizon par Juralmunkey.
Le skin prend tout son sens avec l'usage de son addon TheMovieDb Helper qui y est intégré.. Vraiment une expérience qui frôle la perfection.. Fait du bien j'avais pas apprécié Kodi comme ça depuis Jarvis 😁

Voilà un vidéo que j'ai mis en ligne qui donne exemple de ce que ça donne en fluidité:

https://youtu.be/PlhdYstaiic

**Comment by LordVenom** [comment]
Oui sympas comme theme, je vais tester ça

note: Beaucoup de dépendance ce skin dommage.

**Comment by LordVenom** [comment]
Alors j'ai tester et la fluidité c'est ta shield avec mon pc de salon c'est la PLS.

Bon il date un peux https://www.ldlc.com/fiche/PB00119347.html

Me reste deux choix ou je me prend une shield ou je modifie le theme pour virer tous c'est effet moyennement utile et surtout tous c'est gadget importer.

**Comment by sizanic** [comment]
Sur ta vidéo https://youtu.be/PlhdYstaiic , à 0:33, la recherche dans vStream est très rapide.
Ce n'est pas une recherche globale mais sur une source en particulier ?

**Comment by alKODIque** [comment]
> Oui sympas comme theme, je vais tester ça
> 
> note: Beaucoup de dépendance ce skin dommage.

Ha tu vois, moi je trouve qu'il y a très peu de dépendances comparé a tout ce qu'il y a comme skin.. surtout et en particulier les non-officielles.. tout est traité via TheMovieDb Helper pour les informations de medias et pour le reste nous n'avons que skin shortcut pour les raccourcis et widget mais que seulement estuary n'utilise pas je crois  et la plupart du reste est optionnel 

Pour la fluidité, certainement qu'une shield est rapide mais ça a beaucoup à voir aussi avec la manière dont est configuré le skin, la quantité de widgets et ce que l'on choisi comme widget. De plus, puisque tout est peuplé par TheMovieDb Helper, l'actualisation dépend de la vitesse du site TMDB..
J'ai aussi remarqué un fait non négligeable, puisque le "service monitor" est assuré par TheMovieDb helper, si nous avons un autre skin d'installer et qui lui utilise "skin helper service widget", et bien ce dernier n'est pas codé pour faire la différence si le skin que nous utilisons l'utilise ou pas alors si nous le désactivons pas, nous avons donc 2 services qui roulent en même temps.

**Comment by alKODIque** [comment]
> Sur ta vidéo https://youtu.be/PlhdYstaiic , à 0:33, la recherche dans vStream est très rapide.
> Ce n'est pas une recherche globale mais sur une source en particulier ?

Oui, il s'agit bien de la recherche globale . Je ne me souviens plus exactement quels étaient les sources activées, mais je n'en ai jamais plus que 3 au maximum.. La plupart du temps que 2. Ceci jumelé  au  fait que j'évite le plus possible de vider mon cache dans kodi  (je le fais que dans de très rare nécessité) aide beaucoup a la vitesse et fluidité..

**Comment by alKODIque** [comment]
@LordVenom 
En passant, c'est bien de te revoir de temps à autre par ici  :)
Bien que j'ai bien compris les motifs de ta décision de quitter il y a quelques temps, j'appréciais les échanges que nous avions !! 

A+

**Comment by LordVenom** [comment]
Tu as mis tes api, tu as désactiver les source inutile, merde y à quelqu’un qui a écouter ceux qu'on dit depuis des lustres XD.

Oui je suis la, je vous lis, je vous vois HAHAHAHAHAHAHAH

**Comment by alKODIque** [comment]
Blague à part et pour en revenir au sujet du problème d'accès aux listes via TMDB, juste pour aviser que même en ayant retiré tous les caractères accentués de mes listes personnelles, je ne peux pas y accéder depuis que j'ai installé la dernière bêta (a l'instant) . 

Jai donc  remis mon fichier avec la petite modification  que j'y ai fait  hier (partagé a @sizanic ) et c'est à nouveau possible .

**Comment by TmpName** [comment]
Oui la modif a été faite apres (ou pendant que je bricolais la maj).

Mais pas de soucis, chez toi tu as le dernier fichier, les autres l'auront a la prochaine partielle.
