### ISSUE TITLE
Besoin d'aide pour easyload 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#2985]
Voici le code decodé en base64 `{"file":{"id":1214885,"hls":0,"name":"Action 23-07-2020 15-00-18.mp4","mimeType":"video\/mp4","size":194227,"extension":"mp4"},"user":{"id":10113,"account_type":0,"vid_title":0,"ad_mode":0,"ad_force":0,"player_type":0,"player_subtitle_enable":1,"player_playback_enable":1,"custom_ad_enable":0,"custom_ad_code":{},"player_logo_enable":1,"player_logo_url":"\/images\/playerlogo.png","download_enable":1,"subtitle_setting":"{\"backgroundColor\":\"#000\",\"backgroundOpacity\":\"0\",\"color\":\"#FFF\",\"edgeStyle\":\"uniform\",\"fontFamily\":\"script\"}"},"downloads":{"0":{"src":"YAEEB\u000f\u001e\u001aTTBL]ZPQ\u001f\\^\u001aXXPRT\u001a\u0001\u001a\u0005\u0006\u001ePicwV\\o\u0002{wYGdZ]ebywhb_|\u0001gKwFWygb{dR\u0002d\u0002`KVt{hg_xHWt]Kx\\QAc\u0003\u0001CQtAvQfgIoi]dg[s\u0004cww^gvMt`\\c@cv\u0000~W_Yi`HFG~\u0000{ZTKssbyd\u0001f\\AZor\f]{[QG`\\]\u0003QfEuWddFx[w\u0003ViEuW\u0002t\u0000Veg]PusQwEifgc\u0000dgEK`fE\u0001`f\u0001\u0004g\u0000wH`\u0003\u0004^QuwXo[c\u0001di]T\\Yhd\u0001Z\u0003fZczf\f\\xiZ\u0003c\u0000^Id\u0000t\u0002TZ\favg`\u0003AhW\u0003Ex{ygvxw]|fvA}Qr\r\u0004WZwbfQ\u0003PdQvTgc~Qvg\u0003aZcXg\\`FxtsEQ\u0003s\\d\u0000c}Pyl\u0001d\u0001\u0000\u0004{dBH{y]ay\u0000s\u0002VfQYd\u0003Y_c\u0003x\u0000{KAWiZKo\u0002QA`uQ}Q\u0003x\u0005~KwsT\u0002o\\gdQuV[R\u0003{gs|ou]\\ldVCc[QKV\u0001Y`W\u0001`\u0000Q[t\u0002{uwzb\\\r\b","resolution":null,"type":"video\/mp4"}},"streams":{"0":{"src":"YAEEB\u000f\u001e\u001aTTBL]ZPQ\u001f\\^\u001aXXPRT\u001a\u0001\u001a\u0005\u0006\u001ePicwV\\o\u0002{wYGdZ]ebywhb_|\u0001gKwFWygb{dR\u0002d\u0002`KVt{hg_xHWt]Kx\\QAc\u0003\u0001CQtAvQfgIoi]dg[s\u0004cww^gvMt`\\c@cv\u0000~W_Yi`HFG~\u0000{ZTKssbyd\u0001f\\AZor\f]{[QG`\\]\u0003QfEuWddFx[w\u0003ViEuW\u0002t\u0000Veg]PusQwEifgc\u0000dgEK`fE\u0001`f\u0001\u0004g\u0000wH`\u0003\u0004^QuwXo[c\u0001di]T\\Yhd\u0001Z\u0003fZczf\f\\xiZ\u0003c\u0000^Id\u0000t\u0002TZ\favg`\u0003AhW\u0003Ex{ygvxw]|fvA}Qr\r\u0004WZwbfQ\u0003PdQvTgc~Qvg\u0003aZcXg\\`FxtsEQ\u0003s\\d\u0000c}Pyl\u0001d\u0001\u0000\u0004{dBH{y]ay\u0000s\u0002VfQYd\u0003Y_c\u0003x\u0000{KAWiZKo\u0002QA`uQ}Q\u0003x\u0005~KwsT\u0002o\\gdQuV[R\u0003{gs|ou]\\ldVCc[QKV\u0001Y`W\u0001`\u0000Q[t\u0002{uwzb\\\r\b","resolution":"HD","type":"video\/mp4"}},"subtitles":{},"poster":"https:\/\/easyload.io\/image\/0\/43\/eXVFcmZ3NFlvQkhTWHBYWnI0RzBwbDJ3UzhTRm9RbFZtcVZVck9ZSkR2ZVVUUmQwLzJPbDkwTnBhTm5mN3lPdFRXMUFRQUJ5b3RyNFBqd0w4dGNzRWtCTmxYUTI1anFtdkZmVklURFRWZzB2S2FXQ3N5ZjJwY0wyYU9nL0FSWHAralBHQXQ2L04xY0JMcWs5Q3BWeG91cTExdmJZSE5LYmFCdFBBR09vMU84a1NjcHk3bW80STRvRklyTDJtb0pGT0UzZ1NpZWhyRFNLdWxkcVA5WXd3eUJ6VDZVaElkVmhQMzdEVHU1SUNhc05YQnl6VGRDTUQ3dk5MaWhxTHRTQkNlRTNLZzJDRjBWQzRWVmdpQm5lUnZ1NmZyVk14VWRpWEpnV094Wlhra1U9"}`

Vous pouvez me dire comment on decode ça sa serait cool 👍

**Comment by TmpName** [comment]
Tu aurais un site/film qui utiliserait ce host ?
Car a  mon avis il y a un code quelque part pour decoder le lien, ca ne ressemble pas a un codage classique, beacoup trop d 'unicode.

**Comment by Ovni-crea** [comment]
@TmpName `https://easyload.io/f/xWl62mZPl6/Action_23_07_2020_15_00_18_mp4` tient il me sert de test j'ai vu que adkami utilise se site 

PS: Sur un autre hoster qui s'appelle gotochus j'ai réussi à le faire fonctionnait mais il m'ouvre 2 dialog de qualité c'est un bug ou c'est moi qui a merdé ?

**Comment by TmpName** [comment]
Alors j'ai l'impression que dans la page il ya une redirection vers

`htt_ps://easyload.io/e/xWl62mZPl6/Action_23_07_2020_15_00_18_mp4`


Qui renvoit sur
`h_ttps://www-20.contentcdn.art/eXVFcm3NFlvQkhTHBYWn0RzBwbHRSNUg3Q3UzcENYRnMybhzMmdpV24rdEtGdWRxZXhURjF5VFBoRGxEmVqVG5ObnlXUysvK1NkazFBWQ0SmtkZC9lNjdvUmh2dWpDbUQwMjB2cXpDb3A1cTRleDFNdFXSVV1QVpzUW0UW45R1ByU2odDBiZjV0QXhNamlYQ0o2SVNOW9mMXo2V1kxQ1A3ak9NTGJVU2tYb2pIHRGFhMSGLdC85dEtvZk9BbHZsWDFsaFY2QWtsTTkwUHE1OTNKNmM0elduakIQmZPaVdXMEh2Ym9vSlBVTnJUaEhZUGd2UGk3dVZJdjhEYnNac09yMjdHYy9XSUFXRVFVaGtxemQamJRb24zWGlUEhNkk9`

**Comment by razorex** [comment]
j'ai vu ce hoster est sur plusieurs source

**Comment by Ovni-crea** [comment]
@TmpName J'ai décodé en Json et ça me donne sa 
`2020-07-27 16:10:17.044 T:13528  NOTICE: 	[PLUGIN] vStream: {u'poster': u'https://easyload.io/image/0/43/eXVFcmZ3NFlvQkhTWHBYWnI0RzBwbDJ3UzhTRm9RbFZtcVZVck9ZSkR2ZVVUUmQwLzJPbDkwTnBhTm5mN3lPdFRXMUFRQUJ5b3RyNFBqd0w4dGNzRWtCTmxYUTI1anFtdkZmVklURFRWZzB2S2FXQ3N5ZjJwY0wyYU9nL0FSWHAralBHQXQ2L04xY0JMcWs5Q3BWeG91cTExdmJZSE5LYmFCdFBBR09vMU84a1NjcHk3bW80STRvRklyTDJtb0pGT0UzZ1NpZWhyRFNLdWxkcVA5WXd3eUJ6VDZVaElkVmhQMzdEVHU1SUNhc05YQnl6VGRDTUQ3dk5MaWhxTHRTQlZFc0dFRnRWZTBZSVF3VFdkV2xwRWpvam9Yb1FwRkEraGF4a0ZoVm9DZ1E9', u'downloads': {u'0': {u'src': u'YAEEB\x0f\x1e\x1aTTBL]ZPQ\x1f\\^\x1aXXPRT\x1a\x01\x1a\x05\x06\x1ePicwV\\o\x02{wYGdZ]ebywhb_|\x01gKwFWygb{dR\x02d\x02`KVt{hg_xHWt]Kx\\QAc\x03\x01CQtAvQfgIoi]dg[s\x04cww^gvMt`\\c@cv\x00~W_Yi`HFG~\x00{ZTKssbyd\x01f\\AZor\x0c]{[QG`\\]\x03QfEuWddFx[w\x03ViEuW\x02t\x00Veg]Pus\x7fQwEifgc\x00dgEK`fE\x01`f\x01\x04g\x00wH`\x03\x04^QuwXo[c\x01di]\x7fT\\Yhd\x01Z\x03fZc\x7fzf\x0c\\xiZ\x03c\x00^Id\x00t\x02TZ\x0c\x7fav\x7fg`\x03AhW\x03Ex{ygvxw]|fvA}Qr\r\x04WZ\x7fwbfQ\x03PdQvTgc~Qvg\x03aZcXg\\`FxtsEQ\x03s\\d\x00c}Pyl\x01d\x01\x00\x04{dBH{y]ay\x00s\x02VfQYd\x03Y_c\x03x\x00{K\x7fAWiZKo\x02QA`t\x0cd`vQb`egfQ\x00Ye`tMhWKgGgwR\x01Vg]yQ\x03\x7fubgY]Qy\x7fPa[\x7f[c\x03EAb_c[cZ^\x08', u'resolution': None, u'type': u'video/mp4'}}, u'token': u'MTU5NTg1OTAxODdmOWYyNjkwNjVhNzkxNjM4ZDM0ZTNiOGZiNDQ2YmI3NWI4ODA5YjFxZmhNenpzNUUwUmZ1MnhxdDhMN1BRMEhjM2pEellHNw==', u'streams': {u'0': {u'src': u'YAEEB\x0f\x1e\x1aTTBL]ZPQ\x1f\\^\x1aXXPRT\x1a\x01\x1a\x05\x06\x1ePicwV\\o\x02{wYGdZ]ebywhb_|\x01gKwFWygb{dR\x02d\x02`KVt{hg_xHWt]Kx\\QAc\x03\x01CQtAvQfgIoi]dg[s\x04cww^gvMt`\\c@cv\x00~W_Yi`HFG~\x00{ZTKssbyd\x01f\\AZor\x0c]{[QG`\\]\x03QfEuWddFx[w\x03ViEuW\x02t\x00Veg]Pus\x7fQwEifgc\x00dgEK`fE\x01`f\x01\x04g\x00wH`\x03\x04^QuwXo[c\x01di]\x7fT\\Yhd\x01Z\x03fZc\x7fzf\x0c\\xiZ\x03c\x00^Id\x00t\x02TZ\x0c\x7fav\x7fg`\x03AhW\x03Ex{ygvxw]|fvA}Qr\r\x04WZ\x7fwbfQ\x03PdQvTgc~Qvg\x03aZcXg\\`FxtsEQ\x03s\\d\x00c}Pyl\x01d\x01\x00\x04{dBH{y]ay\x00s\x02VfQYd\x03Y_c\x03x\x00{K\x7fAWiZKo\x02QA`t\x0cd`vQb`egfQ\x00Ye`tMhWKgGgwR\x01Vg]yQ\x03\x7fubgY]Qy\x7fPa[\x7f[c\x03EAb_c[cZ^\x08', u'resolution': u'HD', u'type': u'video/mp4'}}, u'user': {u'custom_ad_enable': 0, u'account_type': 0, u'player_logo_enable': 1, u'custom_ad_code': {}, u'download_enable': 1, u'player_subtitle_enable': 1, u'ad_force': 0, u'ad_mode': 0, u'player_type': 0, u'subtitle_setting': u'{"backgroundColor":"#000","backgroundOpacity":"0","color":"#FFF","edgeStyle":"uniform","fontFamily":"script"}', u'player_logo_url': u'/images/playerlogo.png', u'player_playback_enable': 1, u'vid_title': 0, u'id': 10113}, u'file': {u'mimeType': u'video/mp4', u'name': u'Action 23-07-2020 15-00-18.mp4', u'extension': u'mp4', u'hls': 0, u'id': 1214885, u'size': 194227}, u'subtitles': {}}
`
ducoup je fais quoi après

**Comment by TmpName** [comment]
Et simplement en utilisant la redirection de htt_ps://easyload.io/e/xWl62mZPl6/Action_23_07_2020_15_00_18_mp4 ca marche pas ?

**Comment by Ovni-crea** [comment]
Non ça ne marche pas c'est exactement la même chose

**Comment by Ovni-crea** [comment]
@TmpName Bon je ferme le topic en  fait j'ai l'impression que les fichiers ne reste pas longtemps voir il est quasi jamais utilisé

**Comment by Ovni-crea** [comment]
@TmpName Bon en faite je pense que c'est fait exprès donc je préfère fermé le topic de toute façon easyload leurs fichier ne reste pas longtemps

**Comment by TmpName** [comment]
Ca me rassure car j'etais pas franchement motivé ^^. Coup de bol que ce soit pas le hoster number one.
