### ISSUE TITLE
Recherches en async?

### ISSUE THREAD

**Issue by keethesh** [Kodi-vStream/venom-xbmc-addons#2986]
Premierement, merci beaucoup pour cet addon! Mais je trouve que la recherche est un peu lente. Je peux faire les modifications nécessaires moi-même, mais je n'arrive pas a trouver les fichiers ou est située la fonction pour faire les recherches. Pour ca, je compte convertir certaines fonctions en async. Je serai ravi de vous aider, si vous pouvez me dire ou sont les fichiers a changer!
Merci beaucoup!

**Comment by milkibreizh** [comment]
certaines fonctions en async ?
a part les requêtes je vois pas trop
tu vaudrais par exemple effectuer en asynchrone la recherche gobale
qui effectuent plusieurs requêtes
autrement il a une solution simple et efficace tu ne sélectionnes que 3 à 5 gros sites dans ta recherche
et tu auras le résultat   escompté à 94 % au lieu de 98 % si tu mets tous les sites
cela me fais penser que l'on pourrait ajouter une option avec
un recherche avec ses favoris (2 ou 3 sites)
puis une deuxième liste de recherche plus fournit (dans le cas échéant ou le film n'est pas trouvé ?)

**Comment by milkibreizh** [comment]
@keethesh 
pour savoir comment ca marche ya pas de secret
faut debuger
et tu parles d'une fonction mais comment est tu sure que la modification
que tu veux faire n'affecteras pas les autres fichiers ?
c'est peu être possible mais rien n'est sure

**Comment by milkibreizh** [comment]
bon j'ai regardé vite fais si cela peu t'aider
dans le fichier default.py tu à la recherche
292 def searchGlobal():
et
def _pluginSearch(plugin, sSearchText):

il charge les plugins qui correspondent au fichiers des répertoires sites

**Comment by keethesh** [comment]
> certaines fonctions en async ?
> a part les requêtes je vois pas trop
> tu vaudrais par exemple effectuer en asynchrone la recherche gobale
> qui effectuent plusieurs requêtes
> autrement il a une solution simple et efficace tu ne sélectionnes que 3 à 5 gros sites dans ta recherche
> et tu auras le résultat   escompté à 94 % au lieu de 98 % si tu mets tous les sites
> cela me fais penser que l'on pourrait ajouter une option avec
> un recherche avec ses favoris (2 ou 3 sites)
> puis une deuxième liste de recherche plus fournit (dans le cas échéant ou le film n'est pas trouvé ?)
> 
> 

Je parlais des requetes, car je suppose que ce qui est lent quand on fait une recherche, c'est attendre la réponse de chaque site?

**Comment by milkibreizh** [comment]
@ keethesh 

c'est exactement cela
dans def searchGlobal(): on remarque
que vstream attente la fin de chaque requête de chaque site
car ce sont les fichiers sites qui effectuent la recherche
puis vstream affiche les resultats en conséquence
moi je ne peux pas t'aider davantage
car je ne connais pas comment marche vstream
je ne connais qu'approximativement comment faire un module site
..il va falloir que la team de vstream te donne davantage
d'information..
tu veux utiliser quel module pour utiliser tes taches asynchrones 
une lib interne ou externe ?

**Comment by TmpName** [comment]
Ben quelqu'un a deja proposé un truc, mais il a pas du apprecier ma reponse https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2520

**Comment by keethesh** [comment]
@milkibreizh je pensais utiliser aiohttp, une librairie externe, et qui marche tres bien.

**Comment by keethesh** [comment]
@TmpName du coup j'essaye quand meme? Ou ça ne vaut pas le coup, car dans tous les cas ça ne va pas être ajouté?

**Comment by TmpName** [comment]
Ben tu peux t y risquer, si ca marche on va pas refuser le code. Mais je te previens Kodi est juste une horreur codé au lance pierre, pas du tout concu pour le multithread.

**Comment by milkibreizh** [comment]
@keethesh 

'du coup j'essaye quand meme? Ou ça ne vaut pas le coup'

cela vaudrais toujours le coup si tu prends du plaisir à coder
alors je te souhaites bon courage

**Comment by Ovni-crea** [comment]
@keethesh Si jamais ça fonctionne j'aurais peut être besoin de toi pour recaptcha lol ^^
