### ISSUE TITLE
Kepliz et googlevideo

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#2987]
Plus de video sur kepliz

Vstream : version 0.8.1

La video demarre, le player s'affiche, mais bloque avec erreur 403

```
2020-07-28 18:14:43.451 T:1276  NOTICE: Creating InputStream
2020-07-28 18:14:43.676 T:1292  NOTICE: 	[PLUGIN] vStream: player started
2020-07-28 18:14:43.952 T:1276   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
```

Edit:
En fait ca a l'air de marcher si on lance 2 fois de suite la lecture.

**Comment by Che-debarras** [comment]
> Plus de video sur kepliz
> 
> Vstream : version 0.8.1
> 
> La video demarre, le player s'affiche, mais bloque avec erreur 403
> 
> ```
> 2020-07-28 18:14:43.451 T:1276  NOTICE: Creating InputStream
> 2020-07-28 18:14:43.676 T:1292  NOTICE: 	[PLUGIN] vStream: player started
> 2020-07-28 18:14:43.952 T:1276   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
> ```
> 
> Edit:
> En fait ca a l'air de marcher si on lance 2 fois de suite la lecture.

Oui certains host sont capricieux comme googlevideo ou mystream ou frenchvid

**Comment by milkibreizh** [comment]
@Che-debarras 

c'est vrai les hosts sont peu être capricieux 
mais si tu mets l'url mis dans le ohoster qui ne marche pas dans vstream 
elle marche ds firefox avec ,
il est vrai un temps de réponse assez long 
donc il faut trouver la raison pourquoi  vstream 
fait moins bien le boulot qu'un renard bien futé

**Comment by TmpName** [comment]
Ben je vais essayer de faire une requete HEAD avant de faire faire la vraie requete par Vstream, car ca me le fait dans 100% des cas, et depuis plusieurs jours.

**Comment by milkibreizh** [comment]
@TmpName 
desolé pour mon observation :
c'est plus facile de constater
que de trouver les solutions

**Comment by TmpName** [comment]
Bon rien a faire, si j'essaye de lire la video avec request ca marche, pas d'erreur 403.
Si je met un timeout et que de suite apres j'essaye via kodi erreur 403.
