### ISSUE TITLE
LiveTV peut pas resoudre MLB wiz1.net

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2988]
Bonjour,

La plupart des matchs de Hockey et Baseball ont des wiz1.net liens.
(Ex: h ttp://wiz 1.net/chan nel20?61612516 -> h ttp://198. 144.159. 43/hls17 /playlist.m3u8)
 
j'ai essayé mais sans succès de résoudre le lien. :(

@TmpName , as tu un peu de temps pour m'aider ? 👍 

Merci en avance de ton aide,
sviet

**Comment by Ovni-crea** [comment]
@sviet2k je vais regardé ça

**Comment by Ovni-crea** [comment]
@TmpName Dit j'ai besoin d'aide c'est quoi le regex pour ça ?
https://pastebin.com/jRv43ir9

**Comment by sviet2k** [comment]
Merci beaucoup pour ton aide @Ovni-crea 
Je peux t'aider pour le regex mais je ne comprend pas de quoi tu veux chercher dans le pastebin. Tous les "var"?

**Comment by Ovni-crea** [comment]
@sviet2k d'accord merci

**Comment by TmpName** [comment]
Alors c'est crypté avec jsunfuck mais effectivement c'est assez aleatoire comme code
Parfois le fichier jsunfuck.py  suffit pour decoder, sinon il faut carrement passer par JSparser.py.

Il faut avoir apres si le code est constant ou pas, mais dans les cas faut decoder d'abord l'integralité de la page au moins pour voir si ca change

```
var MSbVbNKhKQ = "WjRlbHJLUExwNWRZcGJDaW90aHNXSEd1blo3YmxJaDVyNlNocTJ4V2NxdW0wTmVmaG;JQbDBOTGJtb3Q2MjlET3FtTlhvZHVpb2R5WlZubmFvOHluWllkMnFOTE1wcGxjb3RyU29xbz0_";
var feSTRaZKiT = MSbVbNKhKQ.split(";");
function TVhVTgZcTT(gfLiaMWLUh){
 eval(gfLiaMWLUh);
 }

 var _0x3703=['<iframe src="http://www.'+'sawlive.tv'+'/embedm/'+'stre' +'/'+feSTRaZKiT[1]+'/'+feSTRaZKiT[0]+'" width="640" height="460" scrolling="no" frameborder="0" allowtransparency="true" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen"></iframe>',"\x77\x72\x69\x74\x65"];_0x3704 = [_0x3703[0].replace("/strea/",, (false0)[italics]()10stream+(false0)[italics]()[10]),_0x3703[[+[]]+[]].replace("/stre/", (false0)[italics]()10stream+(false0)[italics]()[10])];
TVhVTgZcTT(document[_0x3703[1]](_0x3704[1]))
```

Bon je me suis raté sur la fin, mais le code va ressembler a ca.

**Comment by boxkim14** [comment]
Merci @TmpName de nous donner un coup de main 👍 

J'ai déja decodé cette partie et le code est constant: (pars[1] = feSTRaZKiT[1])
url3 = 'h ttp://www.sawlive. tv/embedm/stream/%s/%s' % (pars[1], pars[0])

A partir de ce url3, j'ai unpack les packed mais les resultats du Unpack pointent vers un rtmp link au lieu d'un playlist m3u8.

**Comment by boxkim14** [comment]
Merci beaucoup les gars. J'ai trouvé.

Dans le 'unpack', il y a cette fonction:
var gaskd="";jameiei.forEach(yweytw=>gaskd+=String.fromCharCode(yweytw)
Juste chr() la variable jameiei pour avoir le m3u8.

Encore merci.
