### ISSUE TITLE
menu tvshow (Top Rated)

### ISSUE THREAD

**Issue by milkibreizh** [Kodi-vStream/venom-xbmc-addons#2989]
j’étais en train de mettre à jours des sources sites
pour qu'elles soient compatibles et surtout ne ralentissent 
pas la recherche globales du menu et je viens juste de constater 
qu'il n'y a pas de fonction SERIE_NOTES 
pour un menu tvshow (Top Rated)

bon c'est vrai que je cherche la petite bête
et que c'est vraiment pas grave

**Comment by TmpName** [comment]
Lol, mais tu passes ta vie a te justifier ^^

La je sais pas, me suis jamais servis de FILMS_NOTES, peut etre car peu de site proposent cette section, apres c'est pas trop dur a rajouter si tu veux essayer.

**Comment by milkibreizh** [comment]
@TmpName 
je m'excuse de m’excuser pour m'excuser encore une nouvelle fois^^

bah j'avais déjà vaguement essayé de rajouter un menu à vstream, je sais plus pourquoi d’ailleurs,
le  menu visuel c'est pas compliqué...mais affecté un fonction à ce menu j'ai pas réussi 
..puis ya cette histoire de vslang pour que les menu soit compatible sur d'autres sys/lang 
ou  chaque menu à un number ,c'est pas une histoire de setting encore? ..j'ai pas réussi
à trouver de concordance pour l'attribution des nombres dans les menus.

 je vais réessayé un de ses 4 juste pour voir comment cela marche
mais c'est vrai c'est pas vraiment utilisé..
ya un top serie sur le site papystream je crois
je m'y suis connecté hier ..et bah là cela ne marche plus ?




.

**Comment by milkibreizh** [comment]
BON en faite tu avais raison c’était pas trop dur a faire..
mais il fallait comprendre comment marche les menus

home.py
def showSeries(self):
.....

'MOVIE_NOTES')
        oGui.addDir(SITE_IDENTIFIER, 'callpluging', '%s (%s)' % (addons.VSlang(30121), 
addons.VSlang(30104)), 'notes.png', oOutputParameterHandler)

**Comment by milkibreizh** [comment]
oups
'MOVIE_NOTES' enfin je voulais dire  'SERIE_NOTES'
