### ISSUE TITLE
Quelques problèmes de sources

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2991]
Bonjour!

J'ai remarqué aujourd'hui que:

- DDL: Tous les dossiers de liens ne s'ouvrent plus. Je me rend jusqu'au hoster puis ça bloque

- TIREXO: Pour les films, tout fonctionne a merveille. Par contre, je n'ai plus aucune série de disponible.. Tout est rouge dès l'entrée dans le menu

Je suis sous kodi Leia v18.8
Dernière beta de vStream
Nvidia Shield (Android)
Abonné Alldebrid

Merci pour votre travail et A+

**Comment by kris06** [comment]
salut a tous et un grand merci aux développeurs pour ce retour de tirexo,  cependant seulement quelques films fonctionnent (peu)
sur LEA 18.7 androïd et pc  vstream 0.8.1  
est ce que la beta règle ce problème ?

**Comment by Ovni-crea** [comment]
@kris06 Oui et Non d'un coté on a dl protect qui désactive/réactive recaptcha et tirexo qui font pareil avec cloudflare et certains problème avec les regex mais tu peux tester peut être que ça va résoudre le problème
