### ISSUE TITLE
Premium Alldebrid vs UrlResolver

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#2992]
@Ovni-crea 
J'ai remarqué que lorsque j'utilise l'option "Passer par Alldebrid", et bien il y a certain hoster qui ne sont pas pris en charge. Aussi, lorsqu'on arrive dans le dossier de liens, nous be voyons pas quel hoster nous choisissons car c'est inscrit seulement "Alldebrid" au bout.

Lorsque je remet l'option "Passer par Urlresolver", les liens qui ne fonctionnaient pas avec l'option "Alldebrid"  fonctionnent.. aussi, il m'est possible de voir quel hoster je sélectionne puisque au bout de mon lien c'est inscrit (exemple) RSVL-UPT (contrairement à seulement "ALLDEBRID" 

Jessaierai de te faire un listing des hosters ou j'ai remarqué l'issue dès que possible mais je sais qu'il y a "Vudeo" qui n'est pas fonctionnel avec "Alldebrid" mais qui l'est avec UrlResolver

merci beaucoup pour ton travail!
A+

**Comment by Ovni-crea** [comment]
@alKODIque Perso je préfère pas y toucher puisque c'est dans le coeur de Vstream mais normalement je dois rajouter un site alldebrid qui affichera tes liens + les torrents + afficher la disponibilité de l'hébergeur du débrideur

**Comment by alKODIque** [comment]
@Ovni-crea 
super la source Alldebrid dans la beta :))
Mais le temps de chargement est très long.. crois-tu qu'il serait possible de trier par page? un peu comme le permet la source uptobox premium.. s'il y aurait environ 20 items par page se serait vraiment génial! 
Si nous avons des milliers de médias, sinon, c'est vraiment très long à loader

Merci!!

**Comment by Ovni-crea** [comment]
@alKODIque Je pense que je peux faire quelque chose pour ça je vais voir

**Comment by Ovni-crea** [comment]
@alKODIque C'est bon c'est dans la bêta tu me dis ce que t'en penses

**Comment by alKODIque** [comment]
@Ovni-crea 
Je viens tout juste d'installer et ça fonctionne à merveille! Il n'y a plus d'attente!

merci beaucoup! :)

**Comment by alKODIque** [comment]
@Ovni-crea 
Voici un logo Alldebrid 
Prends ke comme étant ma (très) modeste contribution XD
https://u.pcloud.link/publink/show?code=XZhtc3kZgeQ2pS0qYGRPgrOgX10lxHuGuaVX

**Comment by Ovni-crea** [comment]
@alKODIque Merci
