### ISSUE TITLE
Chargement des sources

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#2994]
Salut à tous,
Je voulais proposer une chose à propos du chargement des sources qui se mettent au premier plan comme ceci 
![Screenshot_20200802-184155](https://user-images.githubusercontent.com/12912677/89127734-400c2a00-d4f0-11ea-893d-256a98d46858.png)

Je voulais savoir si il serait possible de mettre ces chargements en tâche de fond, comme sur certains addons.
Pour qu'on puisse naviguer dans les menus en même temps sans devoir annuler le chargement.

**Comment by Ovni-crea** [comment]
@lebigboss Oui faut juste supprimer quelque ligne dans le code du fichier site pour l'enlever

**Comment by lebigboss** [comment]
@Ovni-crea  Merci je croyais que c'était plus compliqué que ça.
Maintenant reste à savoir si ça va se faire

**Comment by lebigboss** [comment]
@Ovni-crea  Dit moi, tu peux me dire les lignes concernés, j'ai pas trouvé

**Comment by TmpName** [comment]
Moi je pense pas.
Tu demandes a Vstream de faire une recherche, ok, mais si tu pars dans un autre menu, c'est que tu annule la recherche pour faire autre chose, il ne vas pas t'afficher les resultats alors que tu trouves dans les dernieres series en cours sur ton disque dur ?

**Comment by Ovni-crea** [comment]
@TmpName Je crois qu'il veut juste enlever la barre de progression 
@lebigboss Par contre oui en même temps faire autre chose dessus tu ne peux pas tout ce que je peux te proposer c'est d'enlever la barre de progression

**Comment by alKODIque** [comment]
@lebigboss 
Je crois comprendre ce que tu veux dire et je suis d'accord avec toi...

En fait, c'est la fenêtre de chargement qui est trop imposante. D'ailleurs, y'a qu'a voir lorsque nous voulons mettre en page d'accueil des widgets provenant de cStream. Personellement ça fait des lustres que je ne fais plus justement à cause de cette grosse fenêtre qui, cgaque fous que nous cgangeons de page apparaît et orends toute la place dans l'ecran.

Il serait intéressant de pouvoir mettre (comme sur certains skin ou addon) cette fenêtre plus petite pour qu'elle ne nuise pas.. en anglais j'ai vu que ça s'appelait "minimal busy loader"... on voit donc seulement un petit cercle de chargement dans un coin supérieur ou inférieur de l'écran qui ne nuit pas dutout

**Comment by alKODIque** [comment]
PS: Pour régler ce problème sur l'écran d!accueil, je choisis toujours mes widget via d'addon TheMovieDb Helper auquels vStream y est intégré comme player. Alors puisque je vois que tu utilises auramod ( a moins que ce soit Bingee) comme skin, il y est déjà intégré allrs ce serait encore plus facile pour toi de le faire.. Tu ne verras plus la fenêtre de chargement ensuite

**Comment by lebigboss** [comment]
Oui c'est ça, sur l'addon backup tu as cette option
![Screenshot_20200805-170422](https://user-images.githubusercontent.com/12912677/89429461-de40ff80-d73d-11ea-93a9-047519a2050b.png)

Ça permet de naviguer en même temps

**Comment by TmpName** [comment]
Ha ok, j'avais pas compris, je pensais que c'etait une recherche.
Mais dans ce cas, la reponse est pas mieux ^^, non cette fenetre ne sera pas supprimée de maniere definitive car elle est indispensable, a cause du bouton annuler.

**Comment by lebigboss** [comment]
Ok pas de soucis, je vais me débrouiller comme ça
