### ISSUE TITLE
Ajout de RSLVR-UPTOBOX dans les noms des films

### ISSUE THREAD

**Issue by b0bba** [Kodi-vStream/venom-xbmc-addons#2996]
**Décrivez le bug**
Les films ajoutés sur mon dossier Uptobox non premium sont visibles dans vstream avec un nom modifié. Rubrique mes comptes / uptobox

Vstream ajoute RSLVR-UPTOBOX

DOCTOR SLEEP (2019) DEVIENT DOCTOR SLEEP RSLVR-UPTOBOX (2019)

Cela pose un problème pour scraper ensuite automatiquement.

**Votre system**
 - OS: [Android]
-  Appareil [Xiaomi mibox]
 - Version Kodi  [17 leia]
- Version Vstream derniere

**Nous devons le reproduire**
Compte Uptobox gratuit
Uploader un film au format nom (année) sur le compte Uptobox
Voir le film sur mes comptes / uptobox

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Non

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by milkibreizh** [comment]
moi je sais pas ou est le bug mais
class cHoster(iHoster):

    def __init__(self):
        self.__sDisplayName = 'RSLVR-'
comme si le nom affiché qui doit être affiché pour le l'instance du hoster upbox n'avais pas réussi
et avais donc garder le nom de la classe d'initalisation

**Comment by Ovni-crea** [comment]
@b0bba T'as activé URLRESOLVER ?

**Comment by b0bba** [comment]
> @b0bba T'as activé URLRESOLVER ?

Oui j'ai un compte premium alldebrid.

**Comment by Ovni-crea** [comment]
@Ovni-crea Ouais il y a un problème normalement il doit afficher un truc du style `RSLVR-AllDEBRID` un truc comme ça

**Comment by Ovni-crea** [comment]
@b0bba C'est sûr qu'elle source le problème en particulier ?

**Comment by alKODIque** [comment]
@Ovni-crea 
@b0bba 

je crous que le problème qui tente d'être expliqué vient du fait que lorsqu'on utilise un addon type "library integration tool" pour ajouter automatiquement des films/séries à la médiathèque de kodi, la codification de couleur est tenu en compte dans le baming des dossiers et fichiers .strm créés .. 

Par exemple, le film "Joker" sera nommé "[COLOR lightseagreen]Joker[COLOR] et en ce qui concerne les épisodes, c'est encore pire...
[COLOR nomdecouleur]S01E01[COLOR]NOM DE LA SERIE][COLOR couleurdifferente]RSLVR-UPTOBOX[COLOR]

ceci a pour effet de rendre la reconnaissance des épisodes impossible par kodi car le E01 devient séparé de S01

**Comment by Ovni-crea** [comment]
@alKODIque ah ouais ça par contre je sais pas si ça viens de chez nous ou le module externe faut que je regarde le code de vstream (même si ça va être chaud à trouver le problème)

**Comment by b0bba** [comment]
> @Ovni-crea
> @b0bba
> 
> je crous que le problème qui tente d'être expliqué vient du fait que lorsqu'on utilise un addon type "library integration tool" pour ajouter automatiquement des films/séries à la médiathèque de kodi, la codification de couleur est tenu en compte dans le baming des dossiers et fichiers .strm créés ..
> 
> Par exemple, le film "Joker" sera nommé :
> 
> [COLOR lightseagreen]Joker[COLOR]
> 
> et en ce qui concerne les épisodes, c'est encore pire:
> 
> [COLOR nomdecouleur]S01E01[COLOR]NOM DE LA SERIE[COLOR couleurdifferente]RSLVR-UPTOBOX[COLOR]
> 
> ceci a pour effet de rendre la reconnaissance des épisodes impossible par kodi car le E01 devient séparé de S01

Sans parler d'intégration a la médiathèque de Kodi, directement dans vstream les noms sont ajoutés.

C'est donc bien vstream qui ajoute ces noms

**Comment by milkibreizh** [comment]
@Ovni-crea 
il faut pas debuger ici a partir de checkhoster?

le hoster.py

```
def checkHoster(self, sHosterUrl):
		# L'user a active l'url resolver ?
        if self.ADDON.getSetting('UserUrlResolver') == 'true':
            import urlresolver
            hmf = urlresolver.HostedMediaFile(url=sHosterUrl)
            if hmf.valid_url():
                tmp = self.getHoster('resolver') # resolver.py
                RH = sHosterUrl.split('/')[2]    # exemple url uptbobx
                RH = RH.replace('www.', ''
                tmp.setRealHost(RH.split('.')[0].upper()) # def setRealHost
                return tmp # retourne uptbox	
```


resolver.py
```
class choster
 def __init__(self):
        self.__sDisplayName = 'RSLVR-'
        self.__sRealHost = '???'
        self.__sFileName = self.__sDisplayName
        self.__sHD = ''
```
```

def setRealHost(self, sName):
        self.__sRealHost = sName # UPTOBOX

self.__sDisplayName = sDisplayName + ' [COLOR violet]'+ self.__sDisplayName + self.__sRealHost + '[/COLOR]'

```

ce qui donne bien un truc du genre
 DOCTOR SLEEP RSLVR-UPTOBOX

**Comment by TmpName** [comment]
Normallement si "RSLVR-" est rajoute entre crochets ou parentheses, c'est pas automatiquement filtré ?

**Comment by milkibreizh** [comment]
le truc ...self.__sDisplayName = 'RSLVR-
et je disais seulement qu'il fallait debuger  a partir de là autrement je ne sais pas du tout
ce qui se passe après, et comment c'est filtré ..d'ou l'interet de debuguer justement

**Comment by b0bba** [comment]
Precision, je ne sais pas si ce sera utile.

Le film DOCTOR SLEEP (2019).MKV devient DOCTOR SLEEP RSLVR-UPTOBOX (2019).MKV

Quel est l'intérêt d'ajouter cela pour ses propres films sur son propre compte Uptobox?

**Comment by Arias800** [comment]
Je déterre l'issue, le RSLVR- est rajouté automatiquement pour différentier quel code est utilisé :
- Sans RSLVR ça veut dire que c'est le code de Vstream et donc que l'ont peu corrigé le bug.
- Avec ça veut dire que c'est Url Resolver et que l'ont ne s'en occupe pas.
