### ISSUE TITLE
Ajouter ses propres sources publiques

### ISSUE THREAD

**Issue by b0bba** [Kodi-vStream/venom-xbmc-addons#2997]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
J'ai plein de potes qui hébergent des films sur des hosters et ils les partagent en public.

Ce que je fait c'est que j'utilise le remote upload pour copier les films qui m’intéressent sur mon compte uptobox . Puis ensuite je mate sur vstream.
Comme je suis feignant, je souhaite pouvoir chercher directement chez eux sans avoir à effectuer cette synchro. 

**Décrivez la solution que vous souhaitez**
Pouvoir ajouter des sources publiques uptobox directement depuis l'addon. En gros pouvoir ajouter ses propres sources.

Thx

**Comment by alKODIque** [comment]
SOLUTION  est dans la beta avec la source pastebin

**Comment by sizanic** [comment]
Oui, mais faut convertir avec l'outil de @noway80

Comment ça fonctionne ?

**Comment by alKODIque** [comment]
Il m'avait donné une copie de son code et une exe mais il l'a fait évoluer depuis...
En fait, il faut donner notre TMDB API et l'entrer dans un fichier txt. C'est ce qui permet d'extraire les informations des médias. Lorsqu'on l'exécute, ça génère un fichier extract qui prend la forme du format a donner dans pastebin
[Uploading build.zip…]()

**Comment by alKODIque** [comment]
Il m'avait donné une copie de son code et une exe mais il l'a fait évoluer depuis...
En fait, il faut donner notre TMDB API et l'entrer dans un fichier txt. C'est ce qui permet d'extraire les informations des médias. Lorsqu'on l'exécute, ça génère un fichier extract qui prend la forme du format a donner dans pastebin
[Uploading build.zip…]()

**Comment by noway80** [comment]
La question : c est pour partagé ?
Si oui je peux le faire , si non je ne doit pas avec accès aux liens

**Comment by sizanic** [comment]
Je pense que ton outil sera mis à disposition sur ce repo.
Prépares-en une version stable.
Avec @alKODIque et moi, on te fera nos retours avant diffusion.

**Comment by alKODIque** [comment]
ha super l'idée de rendre l'outil disponible dans le dépôt

**Comment by sizanic** [comment]
@b0bba 

Ta solution est ici : #3045

**Comment by LordVenom** [comment]
Pas de nouvelle de @b0bba ?

**Comment by sizanic** [comment]
Solution disponible avec la source Pastebin.
