### ISSUE TITLE
Afficher les etapes pendant le load hoster.

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#2998]
Bonjour, je suis nouveau ici, je suis pas sur de faire bien mon post, d'avance merci de votre compréhension :)

- bref certain hosts ont un certain temps d'attente, ceux qui me chagrine c'est d'avoir un écran load sans savoir ceux qui ce passe,
possible ou pas ? Une popup load en arriere plan qui détaille les étapes [appel à un ami, 50/50, vote du public] :) ou [request, décode, lancement].

Note: Merci @alKODIque 200€ de moin :p)

**Comment by milkibreizh** [comment]
@LordVenom 

j'ai essayé de faire le popup load avec un appel à un ami + option musique en background..
faut juste que je passe le code à tmpName pour qu'il vérifie le truc^^

**Comment by TmpName** [comment]
Le pseudo me rapelle quelque chose ...

Sinon quand on lance un host (dans la plupart des cas, y en a qui sont speciaux) le temps d'attente est a 95% le temps que le site commence a balancer la video non ?

Donc au final on ne verrait qu'une seule etape ?

**Comment by alKODIque** [comment]
@LordVenom 
Alors faudra m'expliquer comment diable ais-je pu te faire épargner 200€! J'suis incapable de le faire pour mou- même en général 😂😂😂

**Comment by LordVenom** [comment]
Épargner, a non dépenser :'( je me suis prix une Shield.

**Comment by alKODIque** [comment]
@LordVenom 
Ho! Je vois!! Alors dans ce cas, voilà une dépense que tu ne regretteras pas! 
Comment trouves-tu ton expérience jusqu'à maintenant?

**Comment by LordVenom** [comment]
J'ai pas compris le geforce now lol, même si j'ai les jeux sur steam faut que je paye un abonnement ?

-- CONTRE
- Je peux même pas jouer au jeux gratos sans abonnement, 5€49 pour juste fournir un serveur puisque les jeux reste payant via steam et les pauvre jeux gratuit avec gforce now ça relever des jeux gratos du xbox live c'est de la merde :)
- Ne me dite pas de jouer au jeux android c'est pas des jeux c'est des pubs.
- Android et son système de tache beurk et la avec la télécommande dur de trouver les applis lancer qui ce relance au démarrage en plus.

-- POUR
- C'est Fluide
- Y a un port ethernet
- y a des port usb
- Kodi tourne (pas encore fait beaucoup de test)

**Comment by alKODIque** [comment]
pour le gaming, j'ai aucune idée!!
Je ne game pas dutout...
Pour la télécommande, je te conseille fortement la Rii Mini i8. Un indispensable

Pour le reste, Avec un explorateur de fichiers digne de ce nom, tu peux réaliser beaucoup de trucs (J'utilise FX, j'aime bien)

Et pour la fluidité, je crois pas qu'il y ait mieux. J'inclus Kodi!

**Comment by Arias800** [comment]
@LordVenom pour Geforce Now il y a deux cas de figure :
- Le mode gratuit (la session dure 1 heure au bout d'une heure le serveur te dégage et tu as un accès normale au serveur).
- Le mode payant (la session dure 6 heures, tu as un accès prioritaire au serveur et tu bénéficies de la technologie du RTX).
