### ISSUE TITLE
Affiche de film pour Kplz

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#2999]
Est il possible d'avoir les affiches des films pour ma sources kplz?
On a un 1e dossier de film qui ne montre pas l'affiche
Mais quand on clique dessus on a un sous dossier avec le titre du film et son affiche est visible
Et enfin un sous sous dossier avec les hosts

Est il possible de faire de ce sous dossier avec affiche le 1e dossier poir avoir les affiches des films?

**Comment by milkibreizh** [comment]
@Che-debarras 
c'est qu'il n'y a pas de liens à scraper dans les premiers résultats
j'ai pas fait toutes les requetes mais il n'y pas d'image sur le site
sinon faut se taper les 21 de requêtes de plus pour chaque images
...ou faire en tache de fonds des recherches apres le premier
resultat..moi je sais pas faire

**Comment by milkibreizh** [comment]
et si tu recupere l'image du sous dossier cela vas pas faire bordélique
d'avoir un film avec une image et pas les autres quand tu reviens sur le premier résultat

**Comment by TmpName** [comment]
Oui kepliz ne propose pas d'affiches sur le site au depart, donc y en a pas sur Vstream.

**Comment by Che-debarras** [comment]
Effectivement c'est l'affiche du sous dossier dont je me demandais s'il pouvais etre sur le dossier principal Ou faire de ce sous dossier le dossier principal car vous que kplz n'a pas d'affiche mais comme ces sous dossiers ont ils l'affiche du film

NB: si c'est pas possible ya pas de souci et merci de vos reponses

![Screenshot_20200808-205810_Kodi](https://user-images.githubusercontent.com/44464129/89717816-43088e00-d9ba-11ea-8353-74753502c1be.jpg)


![Screenshot_20200808-205817_Kodi](https://user-images.githubusercontent.com/44464129/89717800-23716580-d9ba-11ea-91d0-a7dbcf8acbe9.jpg)

**Comment by sizanic** [comment]
Active l'option "Recherche les Métada" dans les parametres de vStream et tu auras les images.
La page est un peu plus longue à charger la premiere fois mais ensuite c'est plus rapide.

**Comment by Che-debarras** [comment]
@sizanic merci pour l'info mais la dernière fois que j'ai testé recherche des meta j'ai eu des affiche qui ne correspondait pas vraiment (je sais pas sk ce problème est toujours présent mais si ya que ça comme solution je  ai pas le choix

Merci

**Comment by sizanic** [comment]
> la dernière fois que j'ai testé recherche des meta j'ai eu des affiche qui ne correspondait pas vraiment (je sais pas sk ce problème est toujours présent 

Donnes moi les exemples car j'avais améliorer ce système, je vais regarder.

**Comment by sizanic** [comment]
Ah oui, il faut que tu vides ton cache depuis la dernière fois pour que ça aille chercher les nouvelles affiches. Sinon ça continue d'utiliser les anciennes qui sont mauvaises.

**Comment by Che-debarras** [comment]
@merci si ya pas d autre solution on peut clore le sujet

**Comment by sizanic** [comment]
Donc c'est mieux après avoir vidé le cache ?

**Comment by Che-debarras** [comment]
> Donc c'est mieux après avoir vidé le cache ?

Je pense que oui pour l'instant 
Je clos le sujet et je rouvrirai si des affiches sont pas le bon
Mals c'est vrai que c'est plus long a charger
