### ISSUE TITLE
Alldebrid 

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3003]
Lorsque j'active Alldebrid et que disons, je choisi un film du hoster liendirect de kaydo (qui n'est pas un premium), il est impossible de lire le média.. par contre, si je passe par urlresolver, ça fontionne (liendirect revient de couleur bleu pour indiquer qu'il ne s'agit pas d'un lien premium. Avec Alldebrid d'activer, peu importe le lien choisi - premium ou pas, nous voyons "Alldebrid" en rose au bout du media)

**Comment by LordVenom** [comment]
Tu t'est pris un vent la... lol tu en est ou de cette histoire ?

**Comment by alKODIque** [comment]
@LordVenom 
au même endroit 😂😂😂 mais ça ne me cause pas assez de soucis pour que je vienne ici voir s'il y a du développement 😛

**Comment by boulete31** [comment]
Mode déterrage on :)
J'ai le même problème de mon coté, rien ne fonctionne avec alldebrid direct dans vstream, ça fonctionne bien si utilisation de urlresolver...

Savez-vous comment utiliser alldebrid sans urlresolver ?

Merci
