### ISSUE TITLE
UrlResolver

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3004]
Bonjour a tous,
Au risque de déplaire à @Arias800 pour ramener au tapis ce problème, :p 

Le problème de dépendance de UrlResolver dans vStream n'est pas réglé.... puisque la version importée dans addon.xml est fixée à 5.1.1

Si je peux me permettre une suggestion, ce serait d'importer à même le dépôt de vstream...
Je m'explique.

Lorsque j'avais 'modé' vStream afin qu'il prenne en charge ResolveUrl au lieu de UrlResolver, j'ai fait les modifications suivantes:

1 - iNCLURE jugal au dir du dépôt vStream afin de toujours avoir la dernière version de ResolveUrl:

`dir
    <info compressed="false">https://raw.githubusercontent.com/Gujal00/smrzips/master/addons.xml</info>
    <checksum>https://raw.githubusercontent.com/Gujal00/smrzips/master/addons.xml.md5</checksum>
    <datadir zip="true">https://raw.githubusercontent.com/Gujal00/smrzips/master/zips/</datadir>
/dir`

2 - Inclure le Script a addon.xml de vStream:

`<requires>
    <import addon="xbmc.python" version="2.1.0"/>
    <import addon="script.module.resolveurl" version="5.0.00"/>
</requires>`

Et là, je sais que la croyance est que UrlResolver est mieux maintenu que ResolveUrl... C'était peut-être le cas jadis, mais aujourd'hui ce ne l'est plus dutout!!! Pour preuve, UrlResolver Fork maintenant les modification directement via ResolveUrl et ne s'en cache pas.... D'ailleurs, il y a eu aujourd'hui même une mise à jour de ResolveUrl ce qui n'est pas le cas de UrlResolver. 

Aussi, bien que l'idée de ne pas forcer les utilisateurs a intaller des addons tiers soit louable, nous parlons ici d'un composant nécessaire au bon fonctionnement de vStream. Je trouve ça vraiment chiant de toujours devoir faire une modification manuelle lorsque j'installe la nouvelle beta de vStream afin que UrlResolver soit fonctionnel a nouveau. Vraiment très très chiant loll

SVP, Si vous refuser toujours de changer pour ResolveUrl,  pouvez vous revoir la fonctionnalité afin que UrlResolver fonctionne correctement et demeure fonctionnel lorsqu'il y a mise a jour de version? (C'est à dire, faire aussi la modif dans le dir du dépot de vStream... vous pourrez même rendre UrlResolver optionnel dans addons.xml ensuite en indiquant optional= true au lieu de 'requires')

Merci beaucoup et désolée @Arias800  de ramener ce sujet ... 
A+

**Comment by alKODIque** [comment]
Je viens de voir qu'il est possible aussi de:


- Importer ResolveUrl et l'utiliser comme vous le feriez avec UrlResolver:

`import resolveurl
resolved = resolveurl.resolve(url)`

- Ou nous pouvons importer ResolveUrl en tant que UrlResolver dans notre addon qui utilise UrlResolver:

`import resolveurl as urlresolver
resolved = urlresolver.resolve(url)`

**Comment by codegittest** [comment]
Hello, me too interresting to flush tvaddons repo to install the old good urlresolver (and the indigo shi. dependancy). Whatever, since dev work seem to be done first on the resolveurl (and clean code) I would like to use it like u with vstream addon. No problem to edit repo xml, this repo don’y update so often. But I have some difficult to edit the addon to work with the resolveurl.
I would really apppreciate if someone could help me and give me somes details about where you put these code « import resolveurl as urlresolver resolved = urlresolver.resolve(url )».
Thanks !

**Comment by codegittest** [comment]
Désolé, je suis habituellement sur des forums anglais et j’ai écrit en anglais par habitude. En gros, je voulais moi aussi basculé à la version resolveurl au lieu de la traditionnelle verion de urlresolver. Urlresolver ne serait plus la version code source (copié de resolveurl) et aurait peut-etre aussi un code « moins propre », surtout lorsque cette version proviens d’un dépot tel que tvaddons (qui install des dépandency comme indigo qui ne sont pas requis).
Donc, j’ai éditer addon.xml du dépot vstream et du addon mais je ne sais pas quel fichier éditer et ou l’on doit mettre cette ligne de code (default.py ? service.py ?):

import resolveurl as urlresolver resolved = urlresolver.resolve(url )

Votre aide serait très apprécié !
Merci !

**Comment by alKODIque** [comment]
Bonjour @codegittest 
Voici les fichiers que j'avais modifié lorsque j'ai fait cette même modification par le passé:

FICHIERS A CHANGER DANS VSTREAM:

- addon.xml
- settings.xml (Dans ressource)
- runscript.py (dans ressource/lib)
- Hoster.py (dans ressource/lib/gui)
- String.po (english) (dans ressource/langage)
- String.po (french) (dans ressource/langage)
- resolver.py (dans ressource/hoster)
- Default.py (raison inconnue)
- jsunpack.py (ajout)
- Retirer unwise.py

**Comment by codegittest** [comment]
Bonjour,
Merci pour votre réponse! Je ne pensais pas avoir a modifier autant de fichiers, je pensais qu’en faisant passer resolveurl pour urlresolver (dans le main code) tout le plugin pourrait continuer a fonctionner avec le vieux nom (urlresolver) et ainsi plus facile a modifier lorsque tout est écrasé dans les mises a jour?
Sur le site « https://github.com/jsergio123/script.module.resolveurl », la facon semble pointer sur cette façon de faire ?

Par ailleurs, je me souvient d’un petit logiciel « macro magic », a une certaine époque, il permettait d’enregistrer une série de changement et de reproduire par la suite mais je n’ai pas utilisé depuis plus d´une 10aine d’années...

A+
