### ISSUE TITLE
Source Alldebrid

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#3007]
Salut à tous.
Pour la source Alldebrid j'ai bien ma médiathèque afficher mais quand je veux lire un lien, il me dit échec de lecture.

**Votre system**
 - OS: Android
-  Appareil nvidia shield
 - Version Kodi  18 et 18.8
- Version Vstream Dernière

**Comment by Ovni-crea** [comment]
@lebigboss  il faut désactiver alldebrid dans les paramètres il va lire en lien direct

**Comment by lebigboss** [comment]
@Ovni-crea  D'accord merci
J'étais pas au courant et c'était pas évident loll
C'est bon ça fonctionne

**Comment by Ovni-crea** [comment]
@lebigboss De rien c'est vrai qu'il faudrait que je modifie cela car dans le site alldebrid on tombe sur les serveur ovh de alldebrid
