### ISSUE TITLE
Problèmes sites

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#3012]
Problèmes sur certains sites:

Planet Stream ne s'ouvre pas
Télécharger-Streaming renvoie " aucune information "
9Docu plus de liens Gounlimited dispo à la place liens Netu qui ne fonctionnent pas

Merci à vous.

Bonne soirée

**Comment by TmpName** [comment]
Salut, essayes plutot de singaler les problemes ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2990
Il y en a qui tiennent une liste, ca leur evite de devoir chercher partout.

**Comment by Ovni-crea** [comment]
@Papounet58 9docu est réglé

**Comment by Papounet58** [comment]
Merci à toi pour l'efficacité.

Bonne soirée.

**Comment by kris06** [comment]
salut à tous, pour information et en attendant la prochaine mise à jour
les sources suivantes ne fonctionnent plus :

ZT zone téléchargement
Zustrem
Zone films
Wiflix
Voir film
Pirvox kepliz
French stream
DDL

sur kodi 18.8 android et pc

**Comment by TmpName** [comment]
Je viens de corriger kepliz (mais faut encore selectionner 2 fois le film)
Pas vu de soucis sur voirfilm ni Wiflix

**Comment by Che-debarras** [comment]
Tout est dis sur #2990 
@kris06 il faut changer le dns
Pour moi kepliz, vorfilm, zustream,wiflix frenchstream fonctionnent parfaitement
