### ISSUE TITLE
Soucis tirexo avec hcaptcha !!!!!

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#3016]
**Décrivez le bug**
@TmpName 
Je tombe sur hcaptcha et si je valide je reste dans la boucle 

**Votre system**
 - OS: [Windows]
-  Appareil [PC]
 - Version Kodi  [18]
- Version Vstream la dernière 

**Plus**
`https://streamable.com/dj0jyf` voici une video de ce que ça fait

**Comment by TmpName** [comment]
Et ca marche sur le site normal ?
Moi j'ai voulu tester hier, et j'ai eu le meme probleme sur firefox.

Edit:
je viens de tester et c'est passé avec kodi.

**Comment by Ovni-crea** [comment]
@TmpName Pareil il est 1 heure du matin ça passe aussi pour le navigateur normal ça passe
