### ISSUE TITLE
Besoin d'aide pour zonefilms_co

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#3018]
Bon voila c'est sur la partie showHoster je voudrais rajouter les liens téléchargement le problème c'est une fonction post le bouton mais quand je récupère value j'en ai 2 du coup comment je fais pour créer un dialog qui choisira le lien de téléchargement à résoudre ?

**Comment by TmpName** [comment]
J'ai pas suivi ou tu en es.
Tu cliques sur un lien de dl, ca ouvre une nouvelle page avec une protection de lien.
Puis appres une manip le lien apparait.

**Comment by milkibreizh** [comment]
@Ovni-crea 
tu créer un classe a partir de la classe dialogue
import xbmcgui

et ensuite tu créer deux listes une pour l'affichage de tes liens ex: liens 1,lien 2
et une autre pour les données qui y sont associé
  exemple 
    sdata1='https//uneadrsse.com/trala ; postdata'  faire split ';' pour recuperer liens + posdata
    list_namelink=['liens1','liens2']  # nom qui sera affiché 
    list_postdata =['sdata1','sdata2'] # donnée retourné

tu n'a plus qu'a créer une fonction def SelectLink qui fera la selection


def SelectLink(list_namelink,list_postdata):  
   
    postdata = oDialog().VSselect(list_namelink,list_postdata ,'veuillez selectionner le lien :')
    return postdata # retourne sdata1 ou sadta2
   
    
```
class oDialog(xbmcgui.Dialog):
      def VSselect(self, list_alias, list_toreturn,sTitle):
```

        if len(list_toreturn) == 0:
            return ''
        if len(list_toreturn) == 1:
            return list_toreturn[0]

        ret = self.select(sTitle, list_alias)
        if ret > -1:
            return list_toreturn[ret]
        return '' 
`
Enfin si j'ai bien compris ce que tu voulais faire

**Comment by milkibreizh** [comment]
il n'y a peu être pas vraiment besoin de faire un classe par contre..

**Comment by TmpName** [comment]
Ha oui, j'allais dire que la fonction existait deja VSselectqual(), mais elle affiche un message au sujet de la qualitée donc je sais pas si ca va aller ?

**Comment by milkibreizh** [comment]
@TmpName 
oui c'est quasiment la même
sauf que cette classe permet de mettre n'importe quoi pour le titres de la fenêtre

**Comment by milkibreizh** [comment]
après j'ai peu être compliqué inutilement les choses
dans list_postdata on peu juste mettre les strings 'cas1' cas2'  et selon le cas on fait un truc

**Comment by sizanic** [comment]
>  comment je fais pour créer un dialog qui choisira le lien de téléchargement à résoudre ?

Tu veux faire porter à l'utilisateur le choix du lien qu'il faut ensuite résoudre ?
On ne peut pas le déduire automatiquement ?

**Comment by Ovni-crea** [comment]
@milkibreizh je viens de tester ça ne fonctionne pas à cause de la requete post qui ne dois pas être bon ou qu'il manque un headers

**Comment by milkibreizh** [comment]
@Ovni-crea 
avant toute conclusion et pour être certain je te mets le code complet du fichier
**streaming_zonefilms_chb.py** qui marche sur mon système
je n'ai rien modifié pour les requêtes
https://pastebin.com/bmbRwFCR

Recherche;  : ok
Films (derniers ajouts); URL_MAIN + 'liste-films ;: ok
Films (genres); requete post; ok 
(pas fait les series)

quand vstream échoue c'est qu'il n'y avait pas de fichier
le lien host est constaté mort dans le navigateur

pour les genres bcp de  liens host sont morts
j'ai réussi à en un trouvé 1 dans aventure 
/films/2124/Pokemon-Detective-Pikachu
et il marche dans kodi (mystream)

Bon courage

**Comment by milkibreizh** [comment]
et en effet tu peux essayé  de compléter les headers que tu vois dans ton navigateur si tu debug
sur un fichier....qui marche
