### ISSUE TITLE
Tel_rium

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#3021]
L'hoster qu'utilise le site channel_tream a l'air d'utiliser du JS.
@TmpName a ton avis c'est pas trop lourd comme code pour Kodi ?

**Comment by bipbip182** [comment]
Bonjour,

Merci pour votre contribution à ce projet, j'ai analysé le site channel stream et vous trouverez dans ma pull request, une version pour récupérer le flux depuis tel_rium.
venom-xbmc-addons/pull/3027

**Comment by Arias800** [comment]
Merci ca a été mis dans la beta. Donc je ferme l'issue.
