### ISSUE TITLE
Spoilers Alerte

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#3024]
Bon il est tard, j'ai encore lu un article sur vStream et j'ai les poils hérissés (pas de mauvais jeux de mots merci :) donc ont vas cassé du mythe la :

- Non vStream n'utilise pas les Torrents.
- Non vStream n'est pas associer avec une marque, un boitier android, un débrideur même pas Kodi.
- Non vous n'avez pas besoin d'un VPN (NON NON NON et NON et RE-NON)
-- Sauf pour l' IPTV localiser je suis pas sure qu'il y en est sur vstream (si vous habiter a l’étranger et voulais vous faire passer comme connecter en France en gros 1 cas sur 1M)
- Des sites son bloqués par votre FAI changer vos dns pour des gratuits c'est tout.
- Pour éviter la Hadopi NON, comment les gens ce sont fait prendre, uniquement sur le réseaux peer to peer.
la hadopi à partager des films (pas les vrais films bien sur, des fichier renommés) bref il ont partager le film et puisque c'est du peer to peer il avais direct l'ip connecter simple et efficace.

Comment fonctionne vstream 

- Connexion au site (récupération d'un lien pas illégal.)
- Connexion au serveur d'upload (il donnerons jamais votre ip ils sont même pas en France)
- Connexion à tmdb (the movie database) (demander une information sur un film ne prouve rien)

Fin.

**Comment by sizanic** [comment]
C'est quel article qu'on rigole ?

**Comment by alKODIque** [comment]
😂😂
J'avoue que j'ai googlé sans trouvé !! 😝

**Comment by LordVenom** [comment]
https://www.vpnblog.net/meilleures-extensions-kodi/

`
Vstream est une extension très populaire en France. Utilisant le réseau Torrent il est très conseillé d’ être connecté derrière IPVanish  au moment de votre Streaming via Vstream.
`

**Comment by alKODIque** [comment]
haha!!
Bien sûr! Tout le monde sait que vStream utilise kes réseaux de torrents 🤪
Et nous sommes d'accord qu'il est évident que l'auteur n'est pas affilié au sus-mentionné vpn hein! 😝😂😂

**Comment by TmpName** [comment]
Lol, en fait ces sites sont sponsorisé par les sites de VPN, donc ils font de la pub.

**Comment by sizanic** [comment]
Cet article n'est pas mal non plus : 
https://www.cnetfrance.fr/news/iptv-illegale-ou-comment-acceder-a-1400-chaines-de-tv-et-1600-films-vod-pour-25-euros-par-an-39879133.htm

Ça commence bien :
`vStream, un add-on qui permet d'accéder aux vidéos stockées sur les plateformes de streaming illégal et de de téléchargement direct telles que DDL Island ou Zone Telechargement 
`

Mais juste avant de parler d'un autre produit "très" intéressant 🤔, un peu de désinformation :
```
* La qualité des vidéos n'est pas toujours au rendez-vous,
* les sites d'où proviennent les flux IPTV et les films en streaming illégal ferment régulièrement ( bon ça c'est vrai)
* et il est facile de voir sa Box infectée par un virus, à force de se promener sur tous ces sites pirates
```

ALORS LA, NON !!


vStream ne fait que afficher du texte et récupérer des liens vers des images et des vidéos, que Kodi affichera en tant que lecteur multimédia.

A aucun moment, vStream ou Kodi ne vont télécharger des applications Android ou des exécutables pour Windows. Aucun virus ne peut s'installer en utilisant Kodi et vStream 

Par contre c'est en allant directement sur les sites de streaming et de téléchargement direct qu'il serait possible d'attraper de mauvais fichiers.

Kodi et vStream est au contraire une **solution** pour ce protéger des virus !
