### ISSUE TITLE
Bug paramètres vstream

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3029]
**Décrivez le bug**

_Depuis les dernières maj impossible de supprimer le cache de vstream via outils dans paramètres 
Peut on supprimer le cache manuellement si oui quel est le dossier du cache vstream_ RÉSOLU en restaurant un backup directement sur leia 18.8  apk nightly du 20200811 (11 août)

0n a une notification d'erreur de fichier introuvable sauf que la video est trouvé et se joue donc il devrait pas y avoir ce msg d'erreur 

_La source kaydo plante kodi si on lance une video (lien direct), kodi crash et on doit le relancer (meme problème sur smartphone box tv et tv android)_ RÉSOLU en restaurant un backup directement sur leia 18.8 apk nightly du 20200811 (11 août)(mais les kaydo ne fonctionnent tjrs pas)

Quand on fait une recherche impossible d ouvrir le film ou serie dans serieStreamwatch

**Votre system**
 - OS: [Android]
-  Appareil [box tv]
 - Version Kodi  [18.8]
- Version Vstream 0.8.1

**Comment by alKODIque** [comment]
@Che-debarras 
Sous windows 10 

j'ai également le même message que tu décris (fichier introuvable) puis tout de suite après, le média se lance bien.  
pour la source kaydo, ça m'est aussi arrivé hier mais c'est aléatoire (avec lien direct)

pour le cache, j'ai pas testé encore mais je regarderai si c'est la même chose ..

**Comment by TmpName** [comment]
Sur quelle hebergeur le cas
> (fichier introuvable) puis tout de suite après, le média se lance bien, ce serait pas up2strm ?

**Comment by alKODIque** [comment]
> ce serait pas up2strm ?

j'avoue que presque tout ce que je visionne est sur uptobox... alors ça aurait très bien pu être le cas. Par contre, je viens à l'instant de lancer "Je veux juste en finir" via la source voirfilms, et avec l'hébergeur vidoza: même message "fichier introuvable"

A noter que mes médias sont lancés avec URLRESOLVER..

**Comment by alKODIque** [comment]
@TmpName 
Pour faire suite a mon dernier message
[log.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5177775/log.txt)

**Comment by TmpName** [comment]
Y a pas d'erreur dans le fichier log, c'est juste un truc standard.
Sinon toujours aucun problemes de mon coté.

**Comment by Arias800** [comment]
J'ai fait une modification du fichier settings.xml, ca corriger ces options sous Kodi 19. Mais je ne sais pas si ca fera de même pour Kodi 18.

**Comment by milkibreizh** [comment]
pareils pour kaydo
problème au niveau du player les fichiers .m3u8 crash kodi
alors qu'avant non...( j'avais auparavant des erreurs demux)

**Comment by milkibreizh** [comment]
@Che-debarras 
"Depuis les dernières maj impossible''
depuis le dernière modife de kaydo..ou cela marchais un peu pour toi
je n'ai mis à jour que les fichiers sites...
donc le problème ne doit pas se situer là

**Comment by Che-debarras** [comment]
Pour la notif fichier introuvable c'est pour toute les hosts que j'ai pu lancer 
Pour le crash de kodi @milkibreizh je n'ai pas compris ta question
Mais ça marché quand @TmpName avais corrigé le bug de dossier qui S'ouvrent pas
Mais apres quelque maj ca crash kodi

**Comment by milkibreizh** [comment]
@Che-debarras 
'il y a 15 jours je n'ai rien changé sur mon system vstream..
je n'ai mis à jours que les fichiers sites qui n'ont aucune incidence sur le fonctionnement de vstream
 et maintenant kaydo , qui n'as pas été modifié depuis 2 semaines, crash kodi ...
donc les autres modifs sur vstream depuis 10j ont peu de chance d'avoir pu altérer le fonctionnement de la source
autrement le problème me dépasse totalement..faudrait jeter un coup d'yeux pour
savoir pourquoi les fichiers m3u8 deviennent illisibles et crash kodi

**Comment by Che-debarras** [comment]
J'ai deja résolu le problème du cache qui refusais de se supprimer,  il fallait réinstaller la version 17.6 avant 18.8.

Pendant que j'écrivais ce msg j'ai trouver un issue 👍 https://github.com/xbmc/xbmc/issues/17120#issuecomment-595309600

Il y a un build de kodi expres ki repare le bug c'est une version 18.7

**Comment by milkibreizh** [comment]
@Che-debarras 
merci mais c'est une issue sans issue pour windows 10
il faudrait que je teste au hazards plusieurs versions de kodi
mais j’avoue avoir la flemme de le faire juste pour un site
...bien que je l'ai déja fait justement pour celui-ci ayant  installé
un autre version de kodi ..mais cela à été sans effets...enfin presque  :cry:

**Comment by Che-debarras** [comment]
> @Che-debarras
> merci mais c'est une issue sans issue pour windows 10
> il faudrait que je teste au hazards plusieurs versions de kodi
> mais j’avoue avoir la flemme de le faire juste pour un site
> ...bien que je l'ai déja fait justement pour celui-ci ayant installé
> un autre version de kodi ..mais cela à été sans effets...enfin presque 😢

@milkibreizh 
Je vais tester les différentes versions (17.6 puis les 18 de leia et les 19 de Master et ce fameux 18.7 du forum qui soi disant fixe le problème. 

Je vous tiens au courant.

Est ti possible de voir le bug de strmwatch qui s'ouvre pas apres une recherche globale ? (Il y a un 2 eme source mais je me rappelle plus laquelle)

**Comment by milkibreizh** [comment]
@Che-debarras 
helas je suis incompétent en ce qui concerne les backups de vstream je ne connais qu'un peu le codage pour
les sites..le reste du code de vstream c'est du chinois pour moi et je ne suis pas sure de connaitre  la moities des menus
de vstream
cela étant je te remercie de faire des testes pour essayer de résoudre les bugs de vstream espérant qu'une personne te donne
le bon tuyaux

**Comment by sizanic** [comment]
Moi je pourrais t'aider mais il faut m'en dire plus.
Ce que tu essayes de faire c'est supprimer le cache des métadonnées ?
(**"Vider le cache de vStream"**)

As-tu un log à me transmettre ?

Et juste pour savoir, pourquoi veux-tu vider ce cache ?

>On a une notification d'erreur de fichier introuvable sauf que la video est trouvé et se joue donc il devrait pas y avoir ce msg d'erreur

Vider le cache des métadonnées ne t'aidera pas pour ce message.

As-tu le message même si tu n'actives pas l'option "Recherche les Métadonnées" ?

**Comment by alKODIque** [comment]
@sizanic 
sur ce commentaire: https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3029#issuecomment-687572525

il y a le log (partie du log) qui fait référence au message d'erreur qui précède le lancement de chaque vidéo pour moi également - tel que @Che-debarras  l'explique.. 
je peux, un peu plus tard, reproduire et envoyer mon log complet si ça peut aider.. mais je crois pas que ça ait un lien avec les métadonnées?

**Comment by Che-debarras** [comment]
@sizanic 

Je me suis aperçu de la disparition de sources ou autre bug apres une maj manuelle de la beta.
Vider le cache m'est quasiment devenu obligatoire si je veux que les changements des maj beta s'appliquent

Apres si je suis le seul avec ce bug n'en tenez pas compte.

Ya le bug que j'ai en commun avec @alKODIque qui gêne un peu car on a une notification qui dis fichier introuvable alors qu'il le trouve et le lance.

Et l'autre souci qui  en faisant une recherche globale sur les sources certains résultats ne S'ouvrent pas comme strmngwatch.

Je comprend que avec cette rentrée vous etes sûrement oqp donc  je vous remercie du temps que vous partagez 
Je vais refaire une install clean a partir de leia 18.8 de Google store et voir si apres chaque addon ajouté  j'ai ce problème de cache ou kodi crash avec kaydo. (J'ai max 3 addons vstream viki et backup + dependances je vois pas trop où peut-être  le souci)

**Comment by milkibreizh** [comment]
@Che-debarras 
pour info
dans ton log je vois ligne 326 error sPost = decode(aResult[1][0])
ton fichier date donc du Commits du juillet 15, 2020
ce n'est pas celui de la version récente
..

**Comment by milkibreizh** [comment]
.....je parlais du fichiers kaydo_ws

**Comment by Che-debarras** [comment]
Pour le problème de cache RÉSOLU avec une fraiche installation de Kodi leia 18.8 nightly du 20200811 (11 août) pour ce qui aurait le meme souci.

@milkibreizh 
J'ai mis a jour avec les derniers commit d'hier et donc j'ai la plus récente.
Peut tu vérifier si sur la beta c'est bien la plus recente ou ou cette du 15juillet?
Elle date de quand la plus recente ?

**Comment by milkibreizh** [comment]
@Che-debarras
kodi/userdata/addon_data/plugin.video.vstream/vstream.db
il existe au moins dans ton répertoire ce fichier ?

**Comment by milkibreizh** [comment]
@Che-debarras 
je viens de vérifier la version beta donne bien 
les toutes dernières version des fichiers sites corrigés
donc tu ne devrais plus avoir dans ton log pour kaydo
 ligne 326 error sPost = decode(aResult[1][0])

tu tiens le bon bout mais la ficelle reste tout de même bien longue...lol

**Comment by sizanic** [comment]
Le chemin "Android" du fichier : 

`/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.vstream/vstream.db`


D'après le code, s'il n'existe pas on essaye de le créer.
Si on n'arrive pas à le créer, cela trace ce log : 

`2020-09-08 13:19:06.318 T:2911  NOTICE: 	[PLUGIN] vStream: Error: Unable to write to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.vstream/vstream.db
`

que l'on voit dans ton fichier de log.

donc on ne trouve pas le fichier et on n'arrive pas à le recréer 🤔 

>Pour le problème de cache RÉSOLU avec une fraiche installation de Kodi leia 18.8

Ce code n'a pas bougé dernièrement, donc que le problème vienne de Kodi est une bonne piste.

**Comment by Che-debarras** [comment]
@sizanic @milkibreizh 

J'ai résolu le pb de cache j'ai formaté kodi et restorer un backup directement sur kodi 18.8 de Août.

Par contre visiblement la beta na pas la derniere version de kaydo dont parle @milkibreizh

**Comment by milkibreizh** [comment]
@sizanic 
tu fais allusion au poste que j'ai effacé en demandant @Che-debarras  si son fichier existait
...
mais même si cela marche maintenant....pourquoi avait il une erreur ?
Unable to write
Unable to acess

**Comment by milkibreizh** [comment]
@Che-debarras 

si je suis sure à 99.9999% sur d'avoir les dernières modifs de kaydoo 
h__ttps://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by sizanic** [comment]
>Unable to write
Unable to acess


Si sans changer le code ça ne fonctionne pas avec une version de kodi puis fonctionne avec une autre version, je ne peux que supposer qu'entre deux versions ils ont changé quelque chose (une bibliothèque ? une autorisation d'accès aux fichiers Android ? ...)

**Comment by Che-debarras** [comment]
@milkibreizh 
Je pense que c'est un souci de kodi 18.8 de Google store (apk de juillet) car il disparaît avec la version apk de Aout.
J'ai cru que c'était la nightly le problème alors j'ai installé que des versions release de 17.6 a 18.8 mais ce pb de cache était toujours là 
J'ai cru un souci vstream
Mais la avec la version dmleia de Aout c'est résolu donc ya surement un truc dans les modif de vstream qui est devenu problematique avec kodi et qui a été corrigé dans la nightly de Août.

Sinon j'ai mis mon log avec la maj beta d'aujourd'hui donc ya bien normalement la dernière version de kaydo.py

**Comment by Che-debarras** [comment]
> @Che-debarras
> 
> si je suis sure à 99.9999% sur d'avoir les dernières modifs de kaydoo
> h__ttps://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

Le 0.0001 est important donc ya pas un doute que la version kaydo uploadé est pas un recent corrigé mais un ancien ou le meme sans correction ?
Parce que j'ai supprimé kaydo.py et kaydo.pyo et copier coller celui de la beta et j'ai beau cliquer x fois ça change rien, les liens marchent pas.

Peux tu vérifier le.fichier.py de kaydo de la beta et vérifié que c'est bien une version corrigé identique au tien ?

**Comment by milkibreizh** [comment]
@Che-debarras 
j'ai verifier ton log il semble correspondre au comportement du denier fichier
mais je peux pas te donner un exemple de film qui marche justement parce cela ne 
marche pas chez moi..
https://pastebin.com/fYFA7hqx
htt__ps://hdss.to/phineas-et-ferb-le-film-candice-face-a-lunivers/ marche dans le navigateur

vlc n'arrive pas non plus a jouer le fichier m3u8.. mais il n'y a pas d'erreur observé..c'est comme si il lisais un flux vide
c'est cela qui me chagrine le plus
il doit avoir un bins dans le format

**Comment by milkibreizh** [comment]
@Che-debarras 
pour les 0.0001
c'est que je me suis toujours posé la question qu'en est t'il vraiment de la réalité ?  :expressionless:

**Comment by Che-debarras** [comment]
> @Che-debarras
> pour les 0.0001
> c'est que je me suis toujours posé la question qu'en est t'il vraiment de la réalité ? 😑

@milkibreizh sauf que pour @TmpName kaydo semble marcher pour lui
C'est ironique quand ça marche pour moi ça marche pas pour lui
Et quand ça marche pour lui ça marche plus pour moi
C'est a n'y rien comprendre 🥴

**Comment by alKODIque** [comment]
Voici le message d'erreur qui aparait avant chaque média lancé dans vStream (peu importe la source et l'hébergeur):
![screenshot018](https://user-images.githubusercontent.com/49578130/92545588-79863280-f21e-11ea-950b-5dde73b0da40.png)

Puis tout de suite après, le film se lance:
![screenshot020](https://user-images.githubusercontent.com/49578130/92545618-89057b80-f21e-11ea-8937-bfbf0e31457c.png)

**Comment by yodidon** [comment]
effectivement je l'ai aussi

**Comment by milkibreizh** [comment]
le problème peu peu être résolu pour
certains
mais cela risque de ne pas ma marcher pour d'autres
dans le fichier 
Kodi\addons\plugin.video.vstream\resources\lib\player.py
il faut supprimer ou mettre en commentaire
```
117  if xbmc.getInfoLabel('system.buildversion')[0:2] >= '19':
118         xrange = range
```
mise en commentaire
```
117  #if xbmc.getInfoLabel('system.buildversion')[0:2] >= '19':
118         #xrange = range
```
mais le bins c'est que justement ce code a été rajouté 
 pour ne pas avoir 'file not found' , tout dépend
de la version du build semble t'il

**Comment by alKODIque** [comment]
Ce problème de message d'erreur est résolu pour moi aujourd'hui :)
Merci a toute l'équipe!
