### ISSUE TITLE
Problème UrlResolver 

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3030]
Bonjour à tous,
J'ai un souci je pense avec UrlResolver, mon abonnement chez Real Débrid était terminé, je l'ai donc réactivé aujourd'hui et là je me retrouve avec le message: pas de streaming sans premium.
Pour info je suis sous Android, Kodi 17.6 Krypton et dernière version de Vstream.
J'utilisais UrlResolver en 5.1.4 et j'ai trouvé une version plus récente 5.1.6 mais aucune différence.
La plupart des liens ne sont pas pris en charge et donc n'affichent pas le RSVR..
Je sais que UrlResolver ne dépend pas de vous mais auriez vous une idée d'un truc que j'aurai raté ?
Nb: bien sûr j'ai réactivé mon compte Real debrid via URL...

**Comment by alKODIque** [comment]
@Niconimes 
En ce qui me concerne, lorsque j'ai un ennui semblable au tien, il faut que j'aille ré-télécharger la cersion 5.1.1 (version demandée par vStream dans l'addon). ensuite, il faut que j'aille enlever le cache de vStream manuellement (supprimer le fichier video_cache.db) et enfin, supprimer la cache dans les paramètres de URLRESOLVER . 

Une fois fait, tu peux aller autoriser urlresolver via les paramètres de vStream puis redémarrer kodi 
Ensuite seulement, tu peux installer la dernière version de urlresolver.

pour info, les versions à jour des resolvers se retrouvent ici: 
https://fusion.tvaddons.co/kodi-scripts/

A titre informatif, pourquoi es-tu toujours sous krypton?? La dernière version de kodi est Leia 18.8 et la version 19 arrive bientôt!

**Comment by Niconimes** [comment]
> @Niconimes
> En ce qui me concerne, lorsque j'ai un ennui semblable au tien, il faut que j'aille ré-télécharger la cersion 5.1.1 (version demandée par vStream dans l'addon). ensuite, il faut que j'aille enlever le cache de vStream manuellement (supprimer le fichier video_cache.db) et enfin, supprimer la cache dans les paramètres de URLRESOLVER .
> 
> Une fois fait, tu peux aller autoriser urlresolver via les paramètres de vStream puis redémarrer kodi
> Ensuite seulement, tu peux installer la dernière version de urlresolver.
> 
> pour info, les versions à jour des resolvers se retrouvent ici:
> https://fusion.tvaddons.co/kodi-scripts/
> 
> A titre informatif, pourquoi es-tu toujours sous krypton?? La dernière version de kodi est Leia 18.8 et la version 19 arrive bientôt!

Salut et merci pour ta réponse je vais essayer de voir ça ce matin.
Pour Kodi c'est tout simplement parce que j'étais sur Leia et j'avais beaucoup de soucis avec plusieurs sites et différents hosters qui ne passaient pas du tout été faisant une installation propre avec juste Krypton et Vstream tout fonctionnait parfaitement jusqu'à hier soir.

**Comment by Niconimes** [comment]
Finalement, beaucoup de liens apparaissent comme morts, aurais-tu un lien vers UrlResolver 5.1.1, je le cherche de partout en vain...
