### ISSUE TITLE
Compte TRAKT personnel

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3031]
Dans notre compte Trakt personnel, la section 'Historique' ainsi que 'calendrier des sorties VO' renvoie un message d'erreur et ne s'ouvre pas

En pièce jointe, il y a les lignes concernées de mon log.

Windows 10
Kodi 18.8 
vStream 8.1 (avec nouvelle beta)
[new 1.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5177325/new.1.txt)

**Comment by TmpName** [comment]
Aucun probleme de mon cote, tu as encore mis des accents partout ^^ ?

Il faudrait que tu change la fonction getLocalizedTitle() dans le fichier trakt par

```
    def getLocalizedTitle(self, item, what):
        headers = {'Content-Type': 'application/json', 'trakt-api-key': API_KEY, 'trakt-api-version': API_VERS,
                   'Authorization': 'Bearer %s' % self.ADDON.getSetting('bstoken')}

        if not 'episode' in what:
            request = urllib2.Request(URL_API + '%s/%s/translations/fr' % (what, item['ids']['slug']), headers = headers)
        else:
            show_title = self.getLocalizedTitle(item['show'], 'shows')
            t_values = (item['show']['ids']['slug'], item['episode']['season'], item['episode']['number'])
            req = URL_API + 'shows/%s/seasons/%s/episodes/%s/translations/fr' % t_values
            request = urllib2.Request(req, headers = headers)

        response = urllib2.urlopen(request)
        aliasContent = response.read()
        response.close()

        aliases = json.loads(aliasContent)
        title = next((title for title in aliases if title['language'].lower() == 'fr'), item)['title']

        return title if 'episode' not in what else show_title + ' - ' + title
```

Ca va afficher la ligne ou ca plante dans les logs

**Comment by alKODIque** [comment]
héhé
C'est la faute de l"office de la langue française si ya des foutus accents partout :p Moi j'essai seulement d'écrire sans trop faire de fautes lol

Noté pour les lignes a changer, je te reviens dès que possible a cet effet

Merci :)

**Comment by alKODIque** [comment]
@TmpName 
Bon, je m'y met.. Et tu souhaites que je t'envoie mon log une fois que j'aurai testé après avoir modifié les lignes que tu as mentionné, c'est bien ça?

Pour info,  j'ai bien retiré tous les caractères accentués dans mes listes perso TMDb. Mais je ne peux quand-même pas entrer dans le dossier via vStream a moins de remplacer le fichier avec celui que j'avais modifié. Pour Trakt, j'ai pas ajouté d'accents, puisque c'est la catégorie Calendrier des sorties VO. Les titres sont donc ceux pré-établis..

**Comment by alKODIque** [comment]
@TmpName 
lorsque je modifie le fichier Trakt.py en changeant les lignes que tu m'as mentionné plus haut, je ne suis plus capable d'ouvrir Trakt ensuite...

**Comment by alKODIque** [comment]
Si tu as la chance, peux=tu m'indiquer ou j'ai merder?

Merci :)
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5180884/kodi.log)
[trakt.py.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5180888/trakt.py.txt)
[traktmod.py.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5180889/traktmod.py.txt)

**Comment by TmpName** [comment]
```
Faut virer aussi le 
        except:
            return item['title']
```

**Comment by alKODIque** [comment]
@TmpName 
en retirant ces lignes, j'ai le même problème ou Trakt ne s'ouvre pas...
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5192195/kodi.log)

**Comment by TmpName** [comment]
>IndentationError: unexpected unindent

Attention aux espaces, un espaces de plus ou de moins et ca marche plus, et tabulation n'est pas la meme chose que espace.

https://privatebin.net/?79bd52cc90661752#2itreaaHY71EUsAJFiKeFQxujg6UGGxSNTLHgv9KefkY

**Comment by alKODIque** [comment]
ho!
merci pour le fichier, je viens de voir! 
mais je suis sur mon iphone et en déplacement... j'espère arriver à temps pour télécharger!

Question hors contexte: est-ce que privatebin permet d'éditer nos paste en conservant son même identifiant ?

**Comment by alKODIque** [comment]
@TmpName 
j'ai copier ton fichier dans mon cloud via mon iphone..
Merci beaucoup et je prends note concernant tes explications espacements et tabulation.. 
c'est apprécié!

**Comment by TmpName** [comment]
@alKODIque non, je pense pas, c'est vraiment un truc basique, et qui ne garde pas longtemps les fichiers ^^.
Dis moi si tu l'as raté.

**Comment by alKODIque** [comment]
@TmpName 
je l'ai bien!
je n'ai seulement pas encore pris le temps remplacer dans vStream :p 
nerci pour l'info concernant privatepaste ;)
je te tiens au courant pour la suite comne tu dois t'en douter huhi
