### ISSUE TITLE
Compte personnel TMDB

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3032]
Il y a un problème avec l'affichage des caractères accentués faisant en sorte que nos listes personelles TMDb ne s'affichent pas.
Le problème a déjà été mentionné ici: https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2981

Cependant, le problème n'est pas résolu

Merci!

**Comment by TmpName** [comment]
Et ici pareil que pour trakt

```
        if '/lists' in action:
            try:
                name = unicode(name, 'utf-8')
            except:
                pass

            name = unicodedata.normalize('NFD', name).encode('ascii', 'ignore').decode('unicode_escape')
            name = name.encode('utf-8')
```

A remplacer par
        if '/lists' in action:
```
            name = unicode(name, 'utf-8')
            name = unicodedata.normalize('NFD', name).encode('ascii', 'ignore').decode('unicode_escape')
            name = name.encode('utf-8')
```

La premiere ligne est surement a modifier

**Comment by LordVenom** [comment]
Pas de nouvelles bonne nouvelle.

**Comment by alKODIque** [comment]
je reviens sur cette issue car je viens de remarquer que pour l'affichage de mes listes personnelles TMDb, celles qui ont des caractères accentués ne s'affichent plus à nouveau... Je me souviens que ça avait été réglé il y a quelques temps. 
C'est malheureusement revenu

j'ai la dernière bêta sur nvidia shield 
kodi 18.9
