### ISSUE TITLE
Recherche visuelle

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3033]
Sous la section recherche visuelle, Recherche (TMDb), j'ai remarqué quelque chose d'étrange...🤣

Lorsque je fais une recherche par nom d'acteur / actrice:
- Si je recherche ''Brad Pitt'', je n'ai aucun résultat
- Si je recherche ''Angelina Jolie'', je n'ai aucun résultat

Par contre:
- Si je recherche seulement ''Brad'' ou ''Pitt'', là j'ai des résultats
- Si je recherche seulement ''Angelina'' ou ''Jolie'', là j'ai des résultats

C'est comme ces exemples, peu importe le nom d'acteur - actrice: La recherche retourne des résultats seulement si nous indiquons un prénom ou un nom. Pas les 2 😂😆

**Comment by milkibreizh** [comment]
oui exact et même pour d'autres recherche
dans les fonctions showsearch exemple
def showSearchActor()/showSearchMovie():
il faut juste mettre
sSearchText=sSearchText.replace('  ','+')

mais je préférés pas trop toucher cette source..

autrement en attendant de tu peux chercher avec :
Brad+Pitt
ou rambo+lastblood
brad+Angelina =  :broken_heart:

**Comment by alKODIque** [comment]
@milkibreizh 
Je n'avais pas remarqué, mais tu as réglé alors grand merci à toi! 🤗
