### ISSUE TITLE
Pb Tirexo et ZT

### ISSUE THREAD

**Issue by Jojo31780** [Kodi-vStream/venom-xbmc-addons#3036]
bonjour, 

Version Kodi 17.6
Vstream 0.8.1
Firestick Amazon

Depuis plusieurs jours impossible d'obtenir des resultats de recherche avec Tirexo, Zone telechargement, Zu stream. Est ce qur vous me conseiller d'utiliser la version beta? Merci beaucoup pour votre aide! Top l'équipe vstream meilleur addon pour moi.

**Comment by milkibreizh** [comment]
@Jojo31780 
teste avec
Version Kodi 18.6
Vstream 0.8.1
wind10
tu peux toujours essayer mais j'ai pas eu de soucis de mon coter pour Zone téléchargement, Zu stream
pour les résultats de la recherche
tu as testé les deux types de recherche en allant sur le dossiers site et en faisant une recherche générale
sinon si tu arrives bien à te connecter avec un navigateur.

**Comment by Jojo31780** [comment]
Merci Milki.
J'ai essayé avec kodi 18.6 et même résultat.
Pb de connection lors de recherche zone téléchargement et tirexo la roue tourne et reste sur le fichier tirexo. Recherche dossier ou générale. Je vais essayer la beta ce week end. 
Merci..

**Comment by milkibreizh** [comment]
@Jojo31780 
pour tirexo 
il te faut la version Chrome version 83 (par contre je sais pas si c'est (>=version 83 )
(...et je parle bien des résultats de la recherche et non pas les sous dossiers de cette recherche )
autrement tu active le log de kodi et tu le mets en pastbin ou autre si tu peux

**Comment by milkibreizh** [comment]
@Jojo31780
par exemple pour zone téléchargement 
est ce que tu as accès aux résultats, 
Films / Films (derniers ajouts)/ .. résultats,

**Comment by Jojo31780** [comment]
Salut mikii.
Pour zone telechargement j'ai aucune information qui apparaît. Avec le message connection impossible erno  111.
Pour tirexo etant sur amazon firestick je ne sais pas comment utiliser Chrome version 83.
Merci pour ton aide.

**Comment by TmpName** [comment]
Je crois que ca ne marche sur android non ?

**Comment by milkibreizh** [comment]
@TmpName 
bah  j'ai regardé sur le post de selenium c'est pas trop clair
sans doute que non pour tirexo mais j'ai pas trouvé une confirmation nette de cela
et pour zone téléchargement je n'ai pas d'erreur de connexion sur mon système pour
les premières requêtes !?

@Jojo31780 
tu n'as plus de souci sur  Zu stream ?
mais j'aurais voulu savoir au moins si tu y arrives sur un navigateur
sinon  non : tu peux essayé de changer de dns
sinon oui :peu être que tu as un logiciel installé,ou un add on qui t’empêche
d’accéder au site

Autrement quel type de connexion as tu
et est ce que tu peux par exemple utiliser
le même routeur (exemple livebox,boitier sfr)
sur un autre ordinateur pour comparer si tu as la connexion
des sites sur d'autres machine avec un navigateur

Comme dis @TmpName pour Chrome version 83
cela est peu être inutile ,mais je pensais que tu avais déjà
chrome d'installé sur ton système et que le teste 
avec le patch ne coutait donc rien

**Comment by milkibreizh** [comment]
@TmpName 
bah  du coup pour  zone_telechargement_ws.py et android
 #2975...le pr qui est là depuis des lustres que j'en
faisais même plus  attention ^^

**Comment by TmpName** [comment]
Oui je l'ai vu aussi^^, mais j'ai toujours pas touché.

Pour tirexo, le probleme c'est pas chrome, mais selenium, je crois que ca ne peut pas marcher sur android.

**Comment by alKODIque** [comment]
Je be sais pas si vous êtes au courant, mais la source zt dans la version disponible dans le dépôt officiel de vStream fonctionne toujours, tandis que sur la bêta non.. j'ai essayé de remplacer le fichier py dans la bêta (fichier zt dispo dans le dépôt) mais ça ne fonctionne pas...  probablement un fichier de setting a été changé (?)
Je sais que le lien provient de l'ancienne adresse toujours en fonction de zt. il avait été conservé..
Avez-vous une idée d'où provient le bug?

**Comment by Jojo31780** [comment]
Pour ma part en voulant installer la beta: plugin video vstream j'ai ce message: la dependance de script.module.urlresover version 5.1.1et pas d'installation. Pourriez vous m aider s'il vous plait? Merci beaucoup

**Comment by Che-debarras** [comment]
> Pour ma part en voulant installer la beta: plugin video vstream j'ai ce message: la dependance de script.module.urlresover version 5.1.1et pas d'installation. Pourriez vous m aider s'il vous plait? Merci beaucoup

@Jojo31780 https://fusion.tvaddons.co/kodi-scripts/

**Comment by alKODIque** [comment]
@Che-debarras 
je vais vérifier si en corrigeant, la source redevient fonctionnelle... car comme tu dis, ça ne fonctionne pas non plus pour moi via le navigateur

**Comment by milkibreizh** [comment]
@Jojo31780 
avant de régler les problèmes sur vstream
est ce que tu obtiens ,au moins des résultats sur un navigateur ?
car on ne sait toujours pas

**Comment by milkibreizh** [comment]
de plus si tu pouvais nous donner la valeur de ton log

[PLUGIN] vStream: load site zone_telechargement_ws and call function load
2020-09-13 22:05:10.697 T:3552  NOTICE: 	[PLUGIN] vStream: ZT url  >> https://w__wvw.zone-annuaire.com/ sauvegarder >> h__ttps://wwvw.zone-annuaire.com/

et j'ai bien des resultats avec h_ttps://wwvw.zone-annuaire.com/nouveaux-films/

**Comment by Che-debarras** [comment]
@milkibreizh 
Moi avec navigateur j'ai pas le site avec wwvw.... mais avec www.zt-za... j'ai accès au site
Avec zone-annuaire on y a plus accès depuis un bout de temps,  il a pas fermé pour devenir zt-za? On a pas accès a zone annuaire sur navigateur

**Comment by alKODIque** [comment]
mais pourquoi est-ce toujours accessible dans la version non-beta de vStream?

**Comment by lebigboss** [comment]
@alKODIque  Le problème c'est que Time2watch ne fonctionne pas sur la stable et il n'y a pas Alldebrid.
Mais c'est vrai que ZT fonctionne et aussi DDL1 ne fonctionne pas du tout sur la bêta mais sur la stable tu peux accéder aux releases mais pas les débridés.

Ça ne concerne peut être pas que ZT

**Comment by milkibreizh** [comment]
@alKODIque 

si tu veux utiliser lune version site py de Vstream 0.8.1
dans une version beta il faut que tu renomme

version qui sera compatible avec la recherche globale
nom du fichier zone_telechargement_ws.py
SITE_IDENTIFIER = 'zone_telechargement_ws'
SITE_NAME = '[COLOR violet]Zone-Telechargement[/COLOR]'

un second fichier qui marcheras seulement dans le menu site
zone_telechargement_ws_teste.py
SITE_IDENTIFIER = 'zone_telechargement_ws_teste'
SITE_NAME = '[COLOR violet]Zone-Telechargement 2[/COLOR]'

ou il faut que tu remplace le fichier

tu peux essayé de tester en mettant et  remplacant le fichier requestHandler.py 
mettre version 0.8.1 dans  beta
addons\plugin.video.vstream\resources\lib\handler\requestHandler.py

**Comment by Jojo31780** [comment]
Bonjour, Merci pour vos réponses
@milkibreizh : J'ai enfin essayé h_ttps://wwvw.zone-annuaire.com/nouveaux-films/ sur mon navigateur et voici la page qui s'affiche:
Ce site est inaccessibleImpossible de trouver l'adresse IP du serveur de h_ttps.
Essayez d'exécuter les diagnostics réseau de Windows.
DNS_PROBE_FINISHED_NXDOMAIN

Sinon pour le log tu peux me donner la procédure s'il te plait? Log vstream je suppose le truc c'est que comme j'utilise Un firestick non connecté à un PC difficiel de faire un copier coller! Je ferai une photo
Désolé je suis pas du tout un pro mais par contre fan de vstream. 
Merci

**Comment by breizhou13** [comment]
dans les options de vstream, tu peux uploader le log et il te donne une adresse pour voir le log.
C'est ce qu'il te demande...

**Comment by Jojo31780** [comment]
Merci Breizhou. Voici url de ma log: https://slexy.org/view/s20ZzVzQAc

Merci

**Comment by milkibreizh** [comment]
@Jojo31780 
j'ai vu ton fichier 
mais est ce que tu as mis sur enable log record dans le menu
j'ai pas eu le temps de te préciser la procédure
merci @breizhou13 

...de toute facon je pense qu'il faut faire le bilan
du fichier py pour savoir si il marche ou non
et dans quel condition
car il y a eu une modification du fichiers récemment
donc si c'est pour faire tout un tralala  pour arriver à rien....

il faut que tu teste l'addresse
hachetétéps://www.ZT-ZA.com/ sur ton navigateur
avant de tester sur vstream avec le nouveau fichier


bah déso lol lé pour le truc mais j'suis pas un pro aussi

**Comment by arzaz** [comment]
Les hosts (uptobox, uploaded..) ne se lancent plus avec ZT sur Android?

**Comment by GravuTrad** [comment]
Tirexo et ZT viennent de fermer. Je pense que les plugin peuvent être supprimés....

**Comment by sizanic** [comment]
Oui, on va les enlever 👍
