### ISSUE TITLE
Aucun lien Vstream ne marchent

### ISSUE THREAD

**Issue by Este34000** [Kodi-vStream/venom-xbmc-addons#3041]
Bonjour à tous,
Je me sers depuis aujourd'hui de Kodi, sur ma box Android xiaomi et de Vstream en version 0.8.1 .

Seulement, aucun lien proposé par Vstream ne marche, je m'explique :
- Soit un message d'erreur Errno 111 apparaît, suivi d'un irl "wwvw"
- Soit la roue tourne mais rien n'apparaît 
- Soit l'on me demande un hoster et de remplir les captchas manuellement
- Soit il y a juste écrit : Aucune information. 
- Et encore divers messages d'erreur dont j'ai oublié le texte ....

Sur des add-ons tels que Venum ou Exodus, tout marche correctement, donc je ne comprends pas le problème...
Je ne m'y connaît pas trop dans ce domaine, j'espère avoir une réponse rapide et claire. 
Merci pour le temps que vous m'accorderez.

**Comment by Che-debarras** [comment]
Il faut lire #2990 
Il est impossible que aucune source ne marchent donc
1 faut installer la bêta 
2 il faut changer le DNS moi j'utilise une appli DNS changer
Les 2 deja va te résoudre bcp le problème 
3 Ensuite sur #2990 ya la liste des sites qui marchent pas 
Et faut patienter car les développeurs de vstream ont une vie,
4 Pour l'histoire de la roue qui tourne c'est pareil que 3 ya des liens HS
5 quant a aucune information c'est lié à  3 et 4 
Et 3,4, 5 sont des problèmes du sites et non de vstream car les liens sont soit HS soit ya une protection du site qui empêche Vstream d'avoir accès

Je pense avoir tous résumé et ça cest le quotidien de vstream d'où le suivi des bugs 

Donc essaye de faire le 1 et 2 et je pense que tu auras pas mal de sources qui marchent sauf ceux cités sur #2990

**Comment by Este34000** [comment]
Super je vais essayer, j'ai cependant une derniere question, j'ai le .zip de la beta, je dois laisser la version classique, comme si la bêta était une extension de Vstream ou la supprimer ?

**Comment by Che-debarras** [comment]
Sur kodi tu clique sur installer par zip et ça va le mettre a jour par dessus

**Comment by yodidon** [comment]
@Che-debarras  trop parfait comme réponse super 👍

**Comment by LordVenom** [comment]
Pas de réponse de @Este34000 merci de rien,

Y a vraiment un addon qui s'appelle venum? .... lol
