### ISSUE TITLE
Recherche globale sur les 40 sources

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3043]
**Décrivez le bug**
Après la mise a jour manuel beta d'aujourd'hui la recherche globale est incomplete: elle s'arrête à  K strmng
J'ai cherché  FBI et je n'ai que des résultats jusque Kstrmng alors que je sais que dans les autreq ya la serie
J'ai vérifié sur zustrm individuellement les source  comme zustrm et il trouve la serie 

**Votre system**
 - OS: [Windows, Android]
-  Appareil [z6+, s8]
 - Version Kodi  [18.8]
- Version Vstream beta dernier commit

**Comment by Che-debarras** [comment]
Problème résolu par @sizanic avec ke commit a060091
Donc je clos cette issue

**Comment by sizanic** [comment]
Ce commit ne peux pas avoir réglé le problème 🤔

**Comment by milkibreizh** [comment]
@Che-debarras 
vers 22h00 hiers j'ai fait un teste en téléchargeant une beta
et j'ai pas eu de de problème sur win 10 ...
ce qui me rassure car tu avais testé android et surtout
et je voyais vraiment pas ou pouvais être le bins

**Comment by milkibreizh** [comment]
et surtout windaube

**Comment by milkibreizh** [comment]
et du coup tu avais quel version de la beta parce que les modifes de sizanic n'ont rien a voir
avec cela .....j 'en ai pas eu besoin comme le précise @sizanic .... 🤔
j'ai regardé un peu les commits entre temps pour voir....mais bon l'essentiel  c'est que cela marche
bonne journée !
