### ISSUE TITLE
Installation VSTREAM

### ISSUE THREAD

**Issue by dreamjeff1** [Kodi-vStream/venom-xbmc-addons#3044]
Configuration : Raspberry PI 4 / LibreELEC 9.25 / Kodi 18.8.
 Bonjour à toutes et tous
Suite à des problèmes d'accès aux sites de streaming depuis 3/4 jours , j'ai essayé de désinstaller puis de réinstaller VSTREAM.

J'ai mis à jour le repo (venom 0.04) mais quand je tente de réinstaller Vstream j'ai un message d'erreur 
la dépendance de script.module.urlresolver version 5.1.1 n'a pas pu être satisfaite.

Par ailleurs j'ai essayé de désinstaller le module URLresolver mais j'ai un autre message d'erreur 
URLResolver est utilisé par les extensions suivantes : Python Koding AIO , cette extension ne peut être désactivée.

Si quelqu'un a une idée , elle sera la bienvenue.  je remercie la team VSTREAM pour son travail.

**Comment by razorex** [comment]
Salut @dreamjeff1  regarde ta version de Urlresolver et si tu n'a pas la 5.1.1 installe la avant de réinstaller vStream

**Comment by dreamjeff1** [comment]
Bonjour

Suite à votre message ,j 'ai eu un doute car lorsque j'essayais d'installer vstream il indiquait dans les dépendances que URLresolver 5.1.1 était installé et optionnel mais j'ai quand même réinstallé URLresolver en version 5.1.1 via un fichier zip puis réinstallé vstream et cela a fonctionné. Le problème est donc résolu , merci encore pour votre aide.

Bonne soirée
