### ISSUE TITLE
Venom.xbmc.addons.beta.zip

### ISSUE THREAD

**Issue by Abeillefan** [Kodi-vStream/venom-xbmc-addons#3048]
Bonjour :) , 

Je n'arrive pas à installer ce fichier venom-xbmc.... Addons  beta .zip. 
Je suis débutante, pouvez-vous m'expliquer pourquoi? Ça dit échec de l'installation ( installer à partir d'un fichier zip. ) 
Jai du reseter Kodi et ça fonctionne moins bien que ça fonctionnait avant...  Lorsque j'ouvre des liens 
comme  kaydoo n'ouvre pas, certains sont vident, mon URL resolver ne semble pas fonctionner ... Bref je n'arrive plus à écouter la série que j'écoutais " The widow"  parfois ça tourne et n'ouvre pas et la majorité du temps ça dit échec. :( 

**Votre system**
 - OS:  Android
-  Appareil Abox / Kodi
 - Version Kodi  18.8 Leia
- Version Vstream repository 0.03 
Plugin 0.8.1 
0.0.4 Venom

Merci :)

**Comment by Che-debarras** [comment]
Tu te trompe de addon , celui de vstream est- sur cette page:

01. Tu télécharges et installe le repo 
02. Piis de Kodi, tu installes vstream à partir du repo
03. Ensuite tu vas sur cette page:
04. https://github.com/Kodi-vStream/venom-xbmc-addons
05. Tout en bas ya "telecharger la beta"
06. Tu la télécharges et tu installes avec kodi via "installer par zip"
07. Cela va mettre à jour la version Vstream du Repo (RC) en version Bêta
08. Cette version bêta a quelques corrections de bugs mais pas tous.
09. Ceux qui bug encore sony listés sur #2990 dont le bug de kaydo.
10. IL EST OBLIGATOIRE DE CHANGER LE DNS SINON CERTAINS SOURCES NE FONCTIONNERONT PAS

**Comment by Abeillefan** [comment]
Bonjour @Che-debarras , merci de ton retour. 

Ai-je le bon repo?  
Vstream Repository Venom 0.0.4 ? 
Ensuite du Repo , version 0.8.1 ? 

Car quand j'installe la version Beta à partir d'installer par zip...  qui est : 

Plugin.video.vstream     .zip , le message est : 

La dépendance envers script module .urlresolver version 5.1.1 n'a pas pu être remplie 

? 

Merci de ta patience

**Comment by Che-debarras** [comment]
> Bonjour @Che-debarras , merci de ton retour.
> 
> Ai-je le bon repo?
> Vstream Repository Venom 0.0.4 ?
> Ensuite du Repo , version 0.8.1 ?
> 
> Car quand j'installe la version Beta à partir d'installer par zip... qui est :
> 
> Plugin.video.vstream .zip , le message est :
> 
> La dépendance envers script module .urlresolver version 5.1.1 n'a pas pu être remplie
> 
> ?
> 
> Merci de ta patience

Tout est correcte.
Ce proble de urlresolver est courant
Maintien un long clic sur l'addon vstream pour faire apparaître "
INFORMATION
DÉSACTIVER
PARAMÈTRES 
clique sur Information puis sur dependance et sur la fenêtre qui s'ouvre clique sur Urlresolver et installe le si il est pas installé ou fait mise a jour pour réinstaller

Si ça marche pas tu trouves les plugins ici:
https://fusion.tvaddons.co/kodi-scripts/

**Comment by LordVenom** [comment]
@Abeillefan C'est réserver au codeur au rapport de bug en gros au dev.
