### ISSUE TITLE
Suivi des bug abandonné ?

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3050]
Je ne cherche pas a critiquer ni mettre la pression mais le suivi des bugs ne donne rien et semble abandonné.

Beaucoup de temps ont été mis au profit de tirexo et selenium et la c'est le pastebin qui semble être chronophage.

J'ai l'impression que l'évolution de vstream se dirige vers une source unique de liens a partager et non plus une liste de source divers et variés qui faisait l'utilité de vstream.

Donc je me pose la question et je pense beaucoup d'autres personnes aussi, est ce que les sources de vstream sont abandonnées au profit de Pastebin?
NB: je ne ferais plus de checkup et suivi de bug vu que celas semble inutile désormais avec le pastebin et le manque de temps pour les corrections de bugs.

Ceci dit merci à la team 

Cela fait je pense 2 mois que aucune sources ne soit corrigées. Apres Kaydo voila kepliz.

Pensez vous avoir un temps pour corriger les bugs ou pastebin est la priorité ?

Désolé pour ce msg mais bcp de sources ne fonctionnent plus.

**Comment by sizanic** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2990#issuecomment-698615092

**Comment by Arias800** [comment]
En ce qui me concerne ma priorité reviens a mes études. Et lorsque j'ai du temps je m'occupe de py3 puisqu'il reste encore un bug a corrigé.

**Comment by yodidon** [comment]
j'etais absent mais je veux bien regarder ce que jepeux faire sur les source qui ont des soucis, alors non je crois pas que le suivi des bugs soit inutile bien au contraire. alors merci @Che-debarras pour ce super boulot et je ferais le maximum.

**Comment by Che-debarras** [comment]
@sizanic 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2990#issuecomment-698752370

@Arias800 
Il y a pas de souci , je ne demande pas de changer vos priorités encore moi celui de votre vie perso et pro. 
Que je répète souvent d'ailleurs dans mes messages que vous etes libres de faire comme bon vous semble et que quoique vous fassieze je reste reconnaissant pour cette addon même si elle évolue dans une direction moins pratique et moins diversifiée qu'avant Tirexo et Pastebin.

Par ex les maj majeur d'après votre github été entre 1 mois dans le meilleur des cas et 3 mois dans le pire des cas et la on entame le 4e mois sans maj. Je ne fais qu'une constatation et je pensais que le suivi des bugs pourrait faciliter un peu mais tirexo/selenium/pastebin m'ont fait comprendre que c'est une perte de temps de checker les bugs pour l'instant et le mieux est de pas vous embeter avec un suivi de bug qui ne trouvera pas sa place dans votre emploi du temps.

@yodidon 
Je te remercie mais je demande pas a corriger absolument les bugs je voulais juste savoir si ça faut encore le coups  de faire ce suivi car ce n'est pour l'instant pas la priorité au vue de l'évolution de vstream et des vies perso et pro de chacun.
Tout est sur ce lien: https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2990#issue-668575983

Merci à  tous.

**Comment by milkibreizh** [comment]
@Che-debarras 

il y a beaucoup de problèmes qui ne sont pas des bugs au sens strict du terme
- CF ne peu être considéré comme un bug
- un site qui n'as plus d'url non plus
- ou un site avec une protection quelconque non plus
- ou peu etre que cela peu être du a un probleme externe a vstream
(dans le cas de problème de liens direct avec des fichiers m3u8 kaydo?)

autrement j'avais pas fais gaffe à mesfilms je viens de faire un pr
et oui ce serait bien de refaire un check comme dit @yodidon
je regarderais ce qui est faisable aussi à mon niveau

**Comment by Che-debarras** [comment]
@milkibreizh 
Oui CF c'est pas un bug et comme je l'ai dis dans un comm pour moi ce n'est pas genant car c'est des sources avec uptobox comme tirexo que j'utilise jamais

Refaire un check c ske je fais mais entre le temms que je le reporte et le temps que vous jeter un coup d'oeil le problème a soit disparu soit changer 

Par ex des fois le dossier est vide des fois il s'ouvre pas
Ddl ne s'ouvrait pas maintenant il s'ouvre 
Kaydo crasher kodi maintenant non
C pour ça que j'ai fais ce poste car je voulais savoir si ca vaut le coup ce suivi
Ya le problème de notification de fichier introuvable qui moi et @alkodique avions signaler.
Etc...

Ce que j'essaie de dire c que les problèmes s empile et que le peu de temps libre que vous avez apres votre vie person et pro semblent se focaliser sur tirexo/selenium puis maintenant Pastebin.

A la base c'était juste une demande d'une personne pour sa liste de pastebin et c'est devenu general au point que c'est plus important que corriger les problèmes.

J'ai rien contre les évolutions mais si ce la est au depends du reste c dommage mais encore une fois j'accepte vos choix de développement

**Comment by Papounet58** [comment]
Pour ma part je suis content du travail accompli par la communauté.
M'occupant d'une épouse handicapée depuis bientôt 21 années,
cela me permet de lui offrir un accès libre à la culture.
Offrir la culture aux plus fragiles d'entre nous n'a pas de prix.
Je suis conscient du travail considérable mené par les bénévoles.
Étant moi-même bénévole je connais la richesse du don de soi.
Merci pour ce que vous faites même si cela n'est pas facile tous les jours.
Pour l'instant le nombre de sources dispo permet de trouver dans la plupart des cas ce que l'on désire.
Il faut parfois chercher un moment mais la gratuité est à ce prix.
Gratuité ne veut pas dire devoir.
Merci à vous et longue vie à Vstream.

**Comment by milkibreizh** [comment]
...merci @Papounet58 

@Che-debarras le gentil genereux
- bah moi j'ai moins de chance car kaydo plante toujours mon kodi
et tu n'as rien installé entre temps....?
- pour le problème de notification de fichier introuvable cela peu être résolue assez facilement
- pour ddl ya comme un truc a modifier mais je retrouve plus le post ou je l'avais signalé
 et pour le reste bah on compte toujours  sur toi

@Che-debarras le méchant vilain
c'est pas très trés très classe :thumbsdown:
 :weary:

...désolé @Papounet58

**Comment by TmpName** [comment]
Ben de mon coté, je me sert de Vstream tout les jours, mais je n'utilises jamais up2box, et tres rarement up2strm.
Je ne me sert jamais de tirexo et je n'ai pas le temps de me pencher sur CF en ce moment.

Kepliz fonctionne tres bien.
Kaydo n'a jamais marché plus de 15jours consecutifs chez moi.

Je trouve tout les films et serie que je veux voir, et tout les fichiers hosters fonctionnent.

Perso si je dois corriger des trucs, c'est pas des sources que je vais corriger, mais des sources que je vais supprimer. Il y en a trop a gerer.

Je n'ai aucun probleme avec la version en cours. Quand je me met a corriger le code, ce qu'il y a vraiment un truc qui ne marche pas.

**Comment by sizanic** [comment]
je n'ai également aucun problème avec la version en cours.

La 0.8.1 du 22 juillet !
(_donc qui n'a que 2 mois et non pas 4 comme certain le mentionne_).

J'y trouve mes séries et mes films.

**Comment by Che-debarras** [comment]
@milkibreizh 
Pour kaydo j'ai tout désinstallé meme kodi puis réinstaller la derniere version de kodi leia beta du 11.08 et restorer mon dernier backup et la kaydo crash plus kodi et le problème avec le cache a été résolu 

Pour la not8de fichier indésirables je pense que oui il peut etre  résolu 

Pour ddl il a cessé de fonctionner mais il a remarche début  de semaine voir weekend avant les modif d'hier en tout cas chez moi

Non je suis pas vilain mais j'ai beau expliquer que je reproche rien er que je suis reconnaissant, je vois ce commentaire qui dis faut etre reconnaissant.
Donc désolé on es bien la pour faire un retour des problèmes de vstream et le problème que moi j'ai vu c'est le peu de temps passer a la résolution des bugs au profit de selenium puis pastebin.

Ça va pas chercher plus loin,  je n'ai mentionné personne a accuser et je radote en disant que ce peu de temps est compréhensible et acceptable pour X raisons mais cela n'empêche pas d'être un peu déçu de l'évolution de vstream même si ce n'était pas volontaire,  les faits sont là. 

@TmpName 
Je suis comme toi j'utilise tout les jours et jamais de source avec uptobox ou uptostrm sauf si c le seul host qui propose l'épisode mais c pratiquement jamais car on trouve dans d'autre source et host.

Je pense qu'on a pas les meme config ce qui explique les différences,  car moi je suis sur android et je sais que moi kaydo marchait quand toi non et la kaydo ne fonctionne pas car pb m3u8.

Kepliz sur box android montre un dossier vide

Tout les fichiers hoster ne fonctionne pas sur android ex cloudvid ou estream

Comme tu dis cher @TmpName oui ya des sources a supprimer car ne sont plus mise a jour mais yen a a corriger aussi lol kepliz kaydo DPstrm planetstrmng,, ceux qui ont des url changé 

@sizanic 
Pour repondre a ton autre message je ne fait aucune erreur dans mon constat et je continuerai a faire le suivi evidement
Et je n'ai jamais dis que vstream ne fonctionne pas je dis que des bugs s'accumulent et que ya plus de temps consacré a leur correction.

Si j'ai parlé de 4 mois c'est pour les maj majeur de l'addon , tu le dis toi meme @sizanic 22 juillet a 22 septembre cela fait 3 mois et on est le 26 donc on entame le 4e mois sans maj majeur.
Tout simplement parce que aucune correction ne permet une maj majeur et je me souvient que ce 22 juillet yavait que le pb de CF et ca touché 3 sources. 

Je comprends que ce constat n'est pas très positif mais c'est malheureusement la réalité que Selenium puis pastebin a été la raison pour laquelle ces bugs se sont accumulés et qu'il y a pas eu de correction.

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2908#issue-616877499
Il y a eu plus de 2500 commentaires depuis mai a aujourd'hui pour cette évolution en incluant les 2 autres issue sur développement et le partage de pastebin
Les autres qui parles de bug a corrige ne dépasse meme pas les 50e comment 

D'autres ont signalé des bugs et j'ai dirigé vers le suivi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3012#issue-679806865
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2991#issue-668576083
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2987#issue-667221314
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3018#issue-682006144

Donc ne me j'étais par la pierre @alkodique @Papounet58 

Je terminerai sur la parole de @sizanic concernant ce pastebin comme quoi mon constat sur l'évolution n'est pas que dans ma tête :

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2908#issuecomment-628673297

@sizanic a bien expliqué que vstream scrappe plusieurs source et que faut etre sur que ce pastebin oit utilisé ,mais c'est pas le cas c'est a peine créé et pas encore de partage ou que du upto que cette creation de source prend la priorité.

Du coup je me demande l'intérêt de ce pastebin car je pense que tres peu de gens l'utiliseront ou l'utilise car faut deja trouver les ID et les recopier et les utilisateurs lambda ne sauront pas le faire , faudra les chercher sur un site, les recopier car kodi fait pas de copier coller et ensuite avoir un debrideur car du uptobox. 

Vstream est je pense utiliser pour regarder les series et films a venir recent , c'est le streaming  que les gens cherche alors que pastebin c'est une vidéothèque de ce qui est ancien meme si y a du recent, ya forte chance qu'on le trouve sur les 44 sources de vstream.

En plus de creer cette source, va falloir creer un forum ou autre pour centraliser les ID pastebin du coup on s'éloigne de ce qu'est vstream,  un scrapper de plusieurs sources.

Je préfère avant où les sources sont corrigées ou remplacées mais la on ne corrige plus on remplace plus on crée une source compliquée pour l'utilisateur final dans sa majorité.

De plus jusqu'ici pour moi vstream est legal car il les développeurs ne partagent pas et héberge pas de film et de serie etc... mais avec le pastebin vous partager ce que vous possédez et ça c'est pas très legal et ça risque de causer un souci.

Partager des sites internet ou scrapper des liens ya aucun soucis car google aussi partage des site et des liens.

Mais partager ses films series je pense pas que ce soit légale car cela fait de vstream un clone de Zt-za, ou zone-annuaire ou zonetelechargement ou tirexo car vous partager des oeuvres que vous posseder sur uptobox donc ce qui partage ces pastebin ce sont des serveurs pour vstream tout comme c'est le cas pour zone téléchargement et evoluer vstream vers ce coté wareez risque de mettre fin a vstream.

 Depuis Mai jusqu'à aujourd'hui vous avez passer 5 mois a créer une source uptobox avec comme serveur les participants qui partage leur videotheque personnel alors qu'il  y a tirexo , time2watch, zt, zt tlchrgmnt,  ddl, ED... qui existe deja.

Désolé pour ce long msg et je vais le clore mais j'espère que vous mediterais sur ce pastebin qui est une mauvaise idée et sonneras le glas de vstream

**Comment by TmpName** [comment]
@Che-debarras pour kepliz, j'ai ouvert une issue a ce sujet, j'y ai vraiement passé du temps, mais impossible de faire un truc propre dans le fichier hoster.

le plus simple et de faire un back et de recommencer pour avoir les liens.

Entre autre, j'ai essayé :
- de lire que les entete du fichier avec une requete HEAD
- de lire les premier octet du fichier et de repasser la main a kodi

Il faudrait voir avec wireshark les commandes envoyées par kodi pour voir ce qu'ils fouttent dans leur requete.

**Comment by milkibreizh** [comment]
@TmpName 
la dernière fois que j'ai voulu faire kepliz je suis arrivé dans le showhoster3
et pour le résultat de la deuxième requête
416 data = oRequestHandler.request()
 je n'ai vu comme source qu'un m3u8 qui faisait le même effet que kaydo
c'est a dire planter kodi après j'ai pu me planter,auuussi
...
il y a un autre lien m3u8 mais qui sert seulement de teste
https://github.com/video-dev/hls.js/issues/2322

**Comment by sizanic** [comment]
@Che-debarras 

Alors déjà pour commencer et être clair,
je te confirme que nous apprécions tous ton travail.
Nous savons que tu ne reproches rien à personne et que tu es reconnaissant.


Et je voudrais bien clore ce débat ici, et te laisser tranquille pour que tu puisse continuer à tester vStream et entretenir l'état des lieux.


**MAIS**

Mais je me dois de te répondre car tu ne peux pas terminer cet échange en avancant des arguments biaisés.


>tu le dis toi meme @sizanic 22 juillet a 22 septembre cela fait 3 mois et on est le 26 donc on entame le 4e mois sans maj majeur.

non, je dis que cela fait 2 mois plein (presque jour pour jour à 3 jours près)
22 juillet au 22 aout => 1 mois
22 aout au 22 septembre => 1 mois

1 + 1 = 2



>Il y a eu plus de 2500 commentaires depuis mai a aujourd'hui pour cette évolution en incluant les 2 autres issue sur développement et le partage de pastebin ... Les autres qui parles de bug a corriger ne dépasse meme pas les 50 commentaires

Les 2500 commentaires ne devraient pas être dans une issue de github, car il ne s'agit pas d'un bug.
Il s'agit d'un développement, et ce ne sont donc pas des commentaires de bug mais des échanges entre développeurs.

Il ne faut donc pas comparer le nombre de commentaires de ce sujet avec les autres sujets.

Et lorsque je dis "entre développeurs", je parle que de _un seul_ développeur de vStream, l'autre développeur ne développe pas sur vStream.


>Du coup je me demande l'intérêt de ce pastebin car je pense que tres peu de gens l'utiliseront

Voici les premiers chiffres, sachant que les pastes n'ont été partagés que depuis 10 jours (https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3045) (même si créés plus tôt)  : 

![image](https://user-images.githubusercontent.com/47307622/94343198-d6ebf300-0016-11eb-90db-9ec2c8734957.png)

![image](https://user-images.githubusercontent.com/47307622/94343221-fb47cf80-0016-11eb-921f-eedeeb201c64.png)



>En plus de creer cette source, va falloir creer un forum ou autre pour centraliser les ID pastebin du coup on s'éloigne de ce qu'est vstream, un scrapper de plusieurs sources pour devenir une source style Zone-telchrmg.

vStream va continuer à être ce qu'il est car pastebin n'est pas destiné à remplacer les autres sources.
Toutes les autres sources vont rester.
Ce n'est qu'une fonctionnalité supplémentaire. On ne va pas t'obliger à l'utiliser si tu ne veux pas.

Il y a de l'IPTV dans vStream qui est très peu utilisé.
Est-ce que cela a changé la philosophie de vStream ? **Non** !

Et le forum d'échange se porte très bien, merci.


>J'ai toujours vu Vstream comme un moteur de recherche.
Mais partager ses films series que vous heberger, je pense pas que ce soit légale car cela fait de vstream un clone de Zt-za car vous partager des oeuvres que vous posseder sur uptobox donc ceux qui partage ces pastebin ce sont des serveurs pour vstream tout comme c'est le cas pour zone téléchargement qui ont du fermer pour avoir partager des oeuvres.

Tu as raison de te poser ces questions. On se les est posées aussi.
Mais vStream garde la même philosophie technique dans ce cas.
Les liens uptobox ne sont pas partagés ici sur un site comme ZT.com mais partagés sur une page du site pastebin.com.
Et vStream récupère ces liens sur pastebin.com de la même façon qu'il les récupérait sur ZT.com.
Donc tout comme ZT qui hébergeait les liens, c'est ZT qui a été inquiété et pas vstream.
C'est le même contexte ici.
Et tu le résume parfaitement : 
>ceux qui partage ces pastebin ce sont des serveurs pour vstream tout comme c'est le cas pour zone téléchargement qui ont du fermer

=> ce n'est pas vStream qui a fermé

>je n'ai mentionné personne a accuser

je ne l'ai pas pris pour moi personnellement.
Mais comme je suis le seul être intervenu sur la source pastebin et que tu penses que tous les efforts n'ont été portés que sur cette source (et uptobox par association), tu comprends pourquoi c'est moi qui te répond.



>je radote en disant que ce peu de temps est compréhensible et acceptable pour X raisons mais cela n'empêche pas d'être un peu déçu de l'évolution de vstream même si ce n'était pas volontaire

Quelle évolution ? vStream n'évolue pas vers un autre chose et reste ce qu'il est : 
> un scrapper de plusieurs sources

Et pour finir, même si tu penses que cette source ne propose pas de films très récents (ce qui est à vérifier), elle propose au moins un catalogue de films **4K** qu'on ne retrouve pas sur d'autres sources.
Elle a donc tout autant sa place avec les autres sources car elle élargit le catalogue de vStream.

**Comment by Che-debarras** [comment]
Désolé mais si tu veux clore le débat faut juste conclure que ce pastebin a la priorité sur les autres sources.
Peu importe le nombre de devs ,de vstream ou autre, la priorité doit être de corriger les bugs avant toi-même 
Ce n'est qu'une fois corrigé qu'il es possible d'ajouter un des fonctions mais ça tu refuse d'accepter que les bugs ont été mis de côté

Donc stp ne repond pas, débat clos.

**Comment by TmpName** [comment]
@milkibreizh pour kepliz
Ca plante sur toute les machines ou uniquement android ?
A chaque fois ?

**Comment by milkibreizh** [comment]
@TmpName 

cela plante parce dans le hoster3 la recherche du lien hoster échoue

j'ai pris le résultat de la deuxième requête ou il y avait un m3u8
j'ai pas vu d'autres ressource de liens

```
data = oRequestHandler.request()
sPattern = '(?:file)|(?:s
....
 if (aResult[0] == True):
else:
     sPattern = 'src="([^"]+)m3u8'

```

https://pastebin.com/D82a9q2S
j'ai testé le résultat m3u8 sur un player online
http://player.streamingtvguides.com/
et cela marche..pas sur kodi

**Comment by milkibreizh** [comment]
@TmpName 
 j'oubliais ya encore personne qui a testé ce fichier à part moi
donc si tu pouvais tester, a moins qu'il y est un truc déjà de faux
dans ma source

**Comment by TmpName** [comment]
ok donc kepliz encore HS.

Ton code est bon juste le format du m3u qui ne doit pas etre compatible nativement avec kodi.
Essayes le lien sur vlc ou media player classic, il ne marchera pas non plus.

J'ai essayé en simulant le User-agent, marche toujours pas.

**Comment by milkibreizh** [comment]
@TmpName 
et donc quoi?
ya pas d'autres liens? c'est le seul lien final valide ?
 on laisse tomber en attendant que le site rechange de type de ressource ?

j'ai entendu parlé de fichiers m3u8 qui étaient incompatibles
sur certain système mais pas sur toutes les versions et toutes les plateformes 
de kodi  à la fois.

**Comment by milkibreizh** [comment]
il faudrait que d'autre personne teste ?
j'ai mis mon lien dans l'issue des bugs
mais celui ci à été noyé dans les discussions

**Comment by yodidon** [comment]
> il faudrait que d'autre personne teste ?
> 
> j'ai mis mon lien dans l'issue des bugs
> 
> mais celui ci à été noyé dans les discussions
> 
> 

Dès que je récupère  internet je m’y remets....

**Comment by alKODIque** [comment]
Suivi global à nouveau possible ici: 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3057#issue-709887203

**Comment by Che-debarras** [comment]
> ok donc kepliz encore HS.
> 
> Ton code est bon juste le format du m3u qui ne doit pas etre compatible nativement avec kodi.
> Essayes le lien sur vlc ou media player classic, il ne marchera pas non plus.
> 
> J'ai essayé en simulant le User-agent, marche toujours pas.

Ce lien https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 marche avec kodi et aussi avec vstream grâce à hoster direct donc pour moi vstream et kodi lisent les m3u8 @TmpName.
Donc la fonction hoster direct (à condition qu'il y a d'autres tests avec d'autres fichier m3u8) si elle lis les fichiers alors le problème serait plus du côté de la source.py

**Comment by Che-debarras** [comment]
@TmpName @yodidon 
> ok donc kepliz encore HS.
> 
> Ton code est bon juste le format du m3u qui ne doit pas etre compatible nativement avec kodi.
> Essayes le lien sur vlc ou media player classic, il ne marchera pas non plus.
> 
> J'ai essayé en simulant le User-agent, marche toujours pas.

Ce lien https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 marche avec kodi/vstream grâce à hoster direct donc pour moi vstream et kodi lisent les m3u8 .
Donc la fonction hoster direct (à condition qu'il y a d'autres tests avec d'autres fichier m3u8) si elle lis les fichiers alors le problème serait plus du côté de la source.py

J'ai testé ce test-stream: https://hls-js-dev.netlify.app/demo/
Avec le lien d'un extrait de la source kaydo ci dessus:
https://lb.bidzen.co/hls/d64e21466e94ba26c7ba67824e384d30/d64e21466e94ba26c7ba67824e384d30.m3u8

Il marche sur le site de test mais pas sur vstream hoster direct contrairement à  x36xhzz.m3u8.
Le problème ne vient il pas du hoster Vidzen devenu lb.bidzen.co dans la lecture ? Je ne vois pas ce hoster dans le dossier host de vstream ni d'exception sur le liendirect.py
