### ISSUE TITLE
Bug de la bêta

### ISSUE THREAD

**Issue by mickve** [Kodi-vStream/venom-xbmc-addons#3054]
**Décrivez le bug**
J ai fais la mise à jour ce matin via la bêta et il manque des section ( série ,animé, videos du net,etc...)

**Votre system**
 - OS:Android
-  Appareil beelink gt king
 - Version Kodi  [18.1]

Avant mise à jour beta:
![image](https://user-images.githubusercontent.com/48685663/94340870-61c3f200-0005-11eb-99d2-711b543d2967.jpeg)

Après mise à jour bêta:
![image](https://user-images.githubusercontent.com/48685663/94340873-756f5880-0005-11eb-8658-1c31cece65b1.jpeg):

**Comment by Che-debarras** [comment]
#2990

**Comment by sizanic** [comment]
en cours de correction ...

**Comment by sizanic** [comment]
c'est corrigé
