### ISSUE TITLE
Propositions pour améliorer la fenêtre d'information

### ISSUE THREAD

**Issue by benking110181** [Kodi-vStream/venom-xbmc-addons#3056]
Dans la configuration de vstream il y a encore option extendedinfo et il encore utiliser ? Quand je l'activer j'ai de mauvaise info dans certains site comme extrême d.. Ne pourrais ton pas le remplacer par TheMovieDB Helper ?
Qui peut lui rechercher dans vstream et 
sinon ajouter bouton marque-pages  dans fenetre information de vstream comme le bouton synopsis etc

**Comment by alKODIque** [comment]
@benking110181 
J'ai déjà proposé exactement la même chose que toi :) 
Lorsque la nouvelle fenêtre d'info a été conçue par @LordVenom , nous avons aussi eu un échange sur le sujet, et je sais pas si tu as jeté un oeil sur le wiki proposé par l'aiteur du plugin Themoviedb Helper, mais c'est pas mal compliqué à intégrer !!!

**Comment by LordVenom** [comment]
Je pense que ce serais mieux de ce passer d'un plugin tiers et d'améliorer la fenêtre d'info de vstream.

**Comment by alKODIque** [comment]
Complètement d'accord avec toi @LordVenom  ❤️

**Comment by sizanic** [comment]
D'accord également,
mais quelles améliorations peut-on encore ajoutée ?

Le bouton "Marque-pages" est une bonne idée.
D'autres ?

**Comment by benking110181** [comment]
Je c est pas si ca ferait doublon mais un bouton watchlist de trakt

**Comment by benking110181** [comment]
Un bouton lire ou parcourir, les boutons en haut et si possible une option dans vstream ou je c pas mais avoir la possibilité d'ouvrir cette fenêtre info au premier clic sur pochette comme kodi afficher informations

**Comment by sizanic** [comment]
> Je c est pas si ca ferait doublon mais un bouton watchlist de trakt

Tout le monde n'a pas trakt, il est préférable de garder des fonctionnalités intra-Vstream.

L'intégration vers d'autres systèmes (trakt, tmdb, Uptobox,...) est disponible par le menu contextuel. On ne peut pas en favoriser un plutôt qu'un autre.

**Comment by benking110181** [comment]
Et faire en sorte que c bouton spécifique s affiche que quand un compte et active c pas possible car trakt et relié a tmdb et ce nest pas des comptes Premium comme uptobox

**Comment by benking110181** [comment]
Intra vstream il y a bien une section pour track dans les config vstream ?

**Comment by sizanic** [comment]
oui, en effet 😄 
mais Trakt est bien un système externe à vStream.

C'est mon avis.
Je suis ouvert à toutes proposition.

Pour écouter d'autres avis et recevoir d'autres propositions, on pourrait renommer ce sujet en "Propositions pour améliorer la fenêtre d'information".

**Comment by LordVenom** [comment]
Ne pas confondre trakt addon et trakt api qui peux être intégrer dans vstream.

**Comment by sizanic** [comment]
oui, l'API trakt, qui permet d'interagir avec son compte trakt.
Comme pour les API Uptobox que vStream intègre aussi.

Je dis que si nous mettons trakt, la même question se pose pour les autres comptes qui sont accessibles par API.

Si cette proposition est retenue, nous pouvons bien sûr faire en sorte que le bouton n'apparaisse que pour ceux  qui ont un compte.
(Personnellement je n'ai pas de compte, donc je ne m'occuperai pas de ce dev).

**Comment by alKODIque** [comment]
@LordVenom @sizanic 

Petite idée ''concept" ^^ de mon cru héhé

(Voir images)

- Bouton ''TMDb'' pour ajouter a notre liste perso
- Bouton ''Trakt'' pour ajouter a notre compte
- Bouton ',Recherche'' pour démarrer / chercher le film sans quitter la feêtre d'info
- Déplacement de ''Fermer'' avec les autres boutons

:) 

AVANT:

![Fenetre AVANT](https://user-images.githubusercontent.com/49578130/95372976-50eb6a00-08aa-11eb-89d7-1df9c5f7f7b6.png)

APRES:

![Fenetre APRES](https://user-images.githubusercontent.com/49578130/95372971-4f21a680-08aa-11eb-874d-e845a59e1356.png)
