### ISSUE TITLE
SUIVI - BUGS A CORRIGER SUR LA BÊTA (v0.8.1 vers v0.8.2)

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3057]
**État d'avancement / Sources fonctionnelles:**

1. - Alldebrid 
2. - All Films 
3. - Filmzentream
4. - French-stream
5. - Gum-Gum-Streaming 
6. - HDS-stream 
7. - I Anime
8. - K-Streaming
9. - K Streaming Film
10. - K Streaming Série 
11. - Les débiles
12. - Les docus 
13. - Libertyland
14. - Mamcin 
15. - Mes Films
16. - My Stream
17. - 9Docu
18. - Otaku-Attitude
19. - OtakuFR
20. - PapStream
21. - PasteBin
22. - Neko Sama
23. - Série-Streaming-Watch 
24. - SpiOn
25. - StreamAy Séries
26. - StreamComplet 
27. - StreamDivx
28. - Télécharger-streaming 
29. - Time2watch (Demande parfois 2 essais pour choisir le captcha)
30. - VF.Space
31. - Videobuzzy 
32. - Voir HD
33. - Wiflix
34. - YouTitou
35. - Zone Streaming - (La majorité des médias n'ont pas de pochette)
36. - Zustream

**SOURCES PRÉSENTANT DES PROBLÈMES:**

**ADKAMI** - Les dossiers sont vides. Message: ''Aucune information''
**ASIA INSANE** - Les dossiers sont vides. Message: ''Aucune information''
**BuzzMonClick** - Les dossiers sont vides. Message: ''Aucune information''
**DP Streaming** - Impossible d'ouvrir les dossiers séries et d'en voir le contenu
**EnStream** - Impossible d'ouvrir les dossiers contenants les liens des films
**Film illimité** - Impossible d'ouvrir les dossiers films et d'en voir le contenu
**Filmstreamvk** - Impossible  d'ouvrir les dossiers contenant les liens des films
**Free-Téléchargement** - Les dossiers sont vides. Message: ''Aucune information''
**Kaydo** - Liens direct ne s'ouvrent pas
**Kepliz** - Les dossiers sont vides. Message: Aucune information
**N1 Streaming** - Les dossiers sont vides. Message: ''Aucune information''
**Planet Streaming** - Les dossiers Films ne s'ouvrent pas 
**Série-StreamingHD** - Le Hoster de la source étant Netu, aucun lien ne fonctionne
**Streamavie** - Les dossiers ne s'ouvrent pas. Message : ''Connexion Impossible''
**Streaming-planet** - Le hoster étant Netu, les liens ne fonctionnent pas
**Streaming-Séries** - Plusieurs hosters sont utilisées par la source.  La majorité sont non fonctionnel. J'ai réussi a démarrer les liens ClipWatching seulement
**Streamingdivx** - Les dossiers contenant les liens de films ne s'ouvrent pas
**StreamingK** - Les dossiers films ne s'ouvrent pas
_**Tirexo** - Fonctionne avec Selenium (non testé étant sur ma shield)_
**TopReplay** - Dossiers vides. Messages: ''Aucune information''
**TORO** - Les liens ne démarrent pas  (Attente infinie lol)
**TV_seriestreaming** - Les dossiers ne s'ouvrent pas 
**Vkstream** - Dossiers vides. Message: ''Aucune information''
**VoirFilms** - La majorité des hosters ont les dossiers vides (Message: ''Aucune information'') Les liens uptostream sont fonctionnels

_**Zone-Téléchargement** - Est présentement fonctionnel pour moi avec les correctifs apportés par @Arias800  ici: https://github.com/Kodi-vStream/venom-xbmc-addons/commit/d54f36227053f7cbffcff2e5346ef1ba65c50c84 Je laisse ici le temps de vérifier la stabilité et que d'autres utilisateurs confirment également :)_

**SOURCES NON VÉRIFIÉES:**

Robin des Droits + Toutes les sources IPTV

**Comment by alKODIque** [comment]
Est-ce normal que je ne sois plus capable d'ajouter un film à la médiathèque de kodi à l'aide de la fonctionnalité offerte par vStream via le menu contextuel ?

Il y avait longtemps que je n'avais pas essayé puis en faisant l'essaie quelques fois aléatoirement, j'obtiens chaque fous un message d'erreur et ça ne fonctionne donc pas.

J'envoie un log si vous avez besoin

**Comment by Arias800** [comment]
J'ai une correction deja prête, j'essaye juste de corriger quelque chose avant de poster cette version.

**Comment by Arias800** [comment]
C'est corrigé dans la beta @alKODIque

**Comment by alKODIque** [comment]
> C'est corrigé dans la beta @alKODIque

Corrigé et fonctionnel!
Merci a toi 😊

**Comment by Che-debarras** [comment]
L'ancien suivi (qu'il faut remettre a jour avec un autre checkup):
**Décrivez le bug**

**Nouveau URL pour*
1. Planet-streaming1 .com (payt .com, synergyprofile .com wvw.planet-streaming1.com)
2. Filmstrmngvf (filmstrmngvf.to )

**Host qui se lance pas ou vide*
1. Tvstrmng (les dossiers host contienne tous un lien host Estream HS)
2. Kaydi (Lien direct) ET FAIT PLANTER KODI (
3. Filmzenstrm aucun lien vidzstore ne fonctionne 

**Dossiers ou liens qui ne s'ouvrent pas*: 
1. DDL RÉSOLU 
2. DPstrm (url de secours : ww1 .series- en-streaming. xyz)
3. Plntstrmng (new url)
4. Tirexo (cloudfare)
5. Strmngwatch (apres une recherche globale des sources)
6. Tvstrmng

**Dossiers vides* 
1. N 1strm
2. Kepliz (sauf catégorie Spectacle)
3. Mesflm RÉSOLU 
4. Zone flm RETIRÉ DE VSTREAM 
5. Zone flm co RETIRÉ DE VSTREAM 
6. Strmavie (site introuvable sur navigateur)
7. ZTlchrgmnt
8. Vkstrm (présence de captcha)

Je sais que j'ai dis que je viendrais plus ici mais j'ai vu ce suivi et je ne peut pas m'en empêcher d'aider (c'est plus fort que moi).

1- une grande partie des bugs se corrige en changeant le DNS ce qui explique les dossiers vides
2- il faut tester chaque categorie car pour Kepliz , la catégorie Spectacle affiche bien les hosts googlevidep
3- il ne faut jamais tester la premiere film de la liste car il se peut le host soit pas encore accessible mais prendre un film d'hier ou avant hier et vous verrez que le host est présent et fonctionne 
4- streamavie je l'ai signalé : le site n'existe plus
5- vérifier sur un navigateur si le lien host existe ce qui explique qu'il ne soit pas present  ex voirfilms certains host vide car pas present sur le navigateur

Suivez ces 5 conseils, vous verrez que la majorité des bugs listés ne le sont pas apres DNS changé et une vérification des liens sur navigateur.
C'est pour ça que j'ai pas trop fait de suivi des hosts car la plupart c'est parce que le lien a disparu du site web ou le site web disparu.

Je pense avec ces conseils vous allez reduire le nombre a maximum 10 sources à  corriger
Et vous verrez aussi le temps que ça prend a tester chaque sources, chaque categorie, 2 ou 3 films pour etre sur, chaque host et leur site web.

Donc cher @alKODIque (puisque c'est toi qui t'es dévouée à le faire) tu feras un retour sur le temps que ça prend pour vérifier tout ça.

Je passais juste pour corriger ce suivi qui n'a surement pas le DNS changé qui est maintenant obligatoire.

Bon courage. Et merci

**Comment by kris06** [comment]
Salut à tous et merci encore pour votre super boulot. J'attends impatiemment  comme chacun de nous,  la prochaine mise à jour
Cependant , j'utilise vstream depuis 4 ans, mais je n'ai jamais vu extrême download fonctionner !

Que signifie au juste  : "Mettre le liens du hoster apres avoir repasser le recaptchas manuelement "   ???
merci

**Comment by Bilal54** [comment]
Bonsoir à tous, pouvez-vous me faire un petit tuto pour faire fonctionner time2watch chez moi svp ? J'ai fait pas mal de recherches mais je ne comprend pas trop l'histoire de url resolver etc.
Pour l'instant j'ai installé kodi ainsi que vStream à partir de la source https://kodi-vstream.guthub.io/repo et je ne sais pas pourquoi time2watch et quelques autres sont écrits en rose. Ensuite quand je navigue dans time2watch, que je choisi par exemple un animé tout est écrit en rouge.
J'ai essayé de configuré vStream (ajout compte time2watch, uptopbox etc) mais au final impossible de lancer qqchose. :/

**Comment by milkibreizh** [comment]
@Bilal54 
je n'ai pas les compétences pour bien t'expliquer clairement ce que tu demande
par contre tu auras plus de chance d'avoir une réponse clair et précise si tu créé
une nouvelle issue ( ou éventuellement tu post ici #3058 )

car cette issue est 'closed'

merci et surtout bonne soirée

**Comment by Bilal54** [comment]
> @Bilal54
> je n'ai pas les compétences pour bien t'expliquer clairement ce que tu demandes
> par contre tu auras plus de chance d'avoir une réponse claire et précise si tu créés
> une nouvelle issue ( ou éventuellement si tu n'y arrives pas tu postes ici #3058 )
> car cette issue est 'closed'
> merci et surtout bonne soirée

Ah ok merci je vais faire ça 👍

**Comment by yodidon** [comment]
sur kaydo il semblerait que la ligne 362 ne reconstruise pas la bonne sHosterUrl j'arrive pas a trouver ou recuperer les bonnes info.

**Comment by yodidon** [comment]
Toro fonctionne

**Comment by TmpName** [comment]
Sur kaydo le lien est bon, si tu le testes sur h ttps://ww w.hlsplayer.net/ il passe sans problem.

**Comment by TmpName** [comment]
Et je viens de voir que bidzen ne fait que renvoyer vers des video google (donc meme hoster pour kepliz et kaydo)
Donc au pire si on arrive a convertir le lien bidzen en lien google ca devrait passer.

**Comment by milkibreizh** [comment]
@TmpName 

les urls 1 pixel sur 1 pixel 
c'est l'url des requêtes qu'il y a  dans le fichier m3u8

ht_tps://lb.bidzen.co/hls3/3fc31bceb7f60a3-0.html?msKey=m13
te renvoie
nom 3fc31bceb7f60a-0.html
dimension 1*1
type image/png

**Comment by milkibreizh** [comment]
@TmpName 
j'avais pas fait gaffe désolé
https://lh3.googleusercontent.
aussi

**Comment by yodidon** [comment]
moi l'url final que je trouve donne ca 

ht--tps://lb.bidzen.co/playlist/224063b34b3b1250e6f8f6765c96d3ed/1601743133005.m3u8
ce qui ne correspont pas a la construction faite a la ligne 362 ??

**Comment by milkibreizh** [comment]
@yodidon 

normalement cette url correspond a la la requête pour la list des formats 
car en faite il y a deux fichiers m3u8

#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=500000,RESOLUTION=480x360
/hls/b3a6fdeac728c41a11bb34c59ec8d842/b3a6fdeac728c41a11bb34c59ec8d842.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1500000,RESOLUTION=1280x720
/hls/6e758048ce9ac39c2d231d324fc09c51/6e758048ce9ac39c2d231d324fc09c51.m3u8

j'ai déjà essayé d"utiliser cette url ca plante pareil kodi
dans vsream on utilise qu'une seul format des deux format je crois que c'est le 1280x720

donc on final tu va tombé sur
https://lb.bidzen.co/hls/6e75.......

**Comment by milkibreizh** [comment]
@yodidon 
par contre ligne j'ai
362 sHosterUrl= ht__tps://lb.bidzen.co/public/dist/index.html?id=aac0 ????
c'est quoi le film de ton url?tu n'as rien modifié?

**Comment by yodidon** [comment]
@milkibreizh 
oui j'ai essayer de récupérer dans un tableau de choix des formats mais sans succes

**Comment by yodidon** [comment]
@milkibreizh 
362 sHosterUrl = 'https://' + sHosterUrl.split('/')[2] + '/hls/' + sHosterUrl.split('id=')[1] + '/' + sHosterUrl.split('id=')[1] + '.m3u8'

**Comment by milkibreizh** [comment]
@yodidon 
tu fait un reggex et tu ajoute  deux liens au hoster c'est pas  possible ?
ou tu utilise un dialogue (mais que je trouve plus lourd) et tu le met dans le hoster

mais je voudrais savoir déjà comment tu a réussi a avoir la playlist
car moi je l'ai pas

**Comment by milkibreizh** [comment]
@yodidon 
je n'ai jamais trop regardé cette histoire de format car c'esr vrai qu'au final cela a jamais marché
donc j'ai pas voulu rajouté des problemes au probleme

**Comment by yodidon** [comment]
ici
![Capture d’écran 2020-10-04 à 17 48 50](https://user-images.githubusercontent.com/39896943/95020254-5b1f2580-066a-11eb-9f67-6397b41d3e65.png)

**Comment by yodidon** [comment]
pour le tableau j'ai utilisé le code dans le hoster lien direct , la partie if playlist in URL

**Comment by milkibreizh** [comment]
@yodidon 
oui mais ton url final 
a ok tu vas dans le hoster
moi dans c'est cas je prefer pas trop touché j'aurais fait juste un pattern
`EXT.*?RESOLUTION=([^\/]+).+?hls.([^\/]+)`
j'aurais construis les url
pour les mettre ensuite  dans le hoster avec l'information qualité

**Comment by milkibreizh** [comment]
@TmpName 

> Mais j'ai pas trouvé, les urls me renvoient sur des png de 1 pixel sur 1 pixel

(j'ai oublié de réediter mon post effacé)
pour moi les urls qui ne renvoient que des png de 1 pixel sur 1 pixel
sont liée aux requêtes contenu dans les fichiers m3u8
même celles ayant  pour addresse h__ttps://lhx.googleusercontent

**Comment by ANNIEM83** [comment]
bonsoir merci pour ce travail que vous faites je suis sur apptv je ne sais pas comment installer la bêta mais j attends patiemment la mise à jour pour pouvoir réutiliser zone téléchargement c est la seule source qui donne du hd sur la liste 😊

**Comment by TmpName** [comment]
Yep meme les liens de google donne ca ...
Y en a pas un qui aurait sous le code un lien google (fonctionnel) pour faire des tests ?

**Comment by yodidon** [comment]
Le comportement est le
Même sur kepliz, pas moyen de lire ce m3u8

**Comment by TmpName** [comment]
Pour moi c'est les memes, kaydo doit aussi utiliser des liens googles.
Et je me demande si le probleme ne viendrait pas de google (et non pas kaydo/kepliz), c'est pour ca que je cherche un lien google pour etre sur.

**Comment by yodidon** [comment]
Je vais regarder ici ce que c’est 
https://github.com/globocom/m3u8

**Comment by yodidon** [comment]
a part pouvoir lancer la video m3u8 sur https://www.hlsplayer.net/ j'ai pas trouver de mieux...

**Comment by TmpName** [comment]
Pas mieux, mais si on arrive a trouver une video google qui plante aussi on saura d'ou vient le probleme.
Au lieu de chercher des lecteur de m3u8, suffira de chercher des codes python pour lire des videos google (et c'est pas les projets qui manquent)

Seul probleme, tout les liens donnent les lien google "decodés" (ou en bidzen), et affichés en "lien direct" dans Vstream donc impossible de tester. Il faudrait un lien comme ceux de kepliz avant qu'ils passent par des liens bidzen direct.

**Comment by milkibreizh** [comment]
@yodidon 
Pas mieux aussi !
à part  avoir réussit à mettre à la poubelle du premier coup de souris le fichier kaydo.py j'ai pas trouver de mieux
...moi j'avoue je comprends pas trop ..c'est bien kodi qui lit les fichiers m3u8 et non pas vstream,
et si cela plante avec  video google c'est bien le hoster google de vstream et pas kodi.

a la limite modifier le m3u8 oui

**Comment by milkibreizh** [comment]
@TmpName 
mais quand tu dis qui plante ok c'est pour de vrai,se ne serait pas liée a vstream tu veux dire ?
cela va etre chaud a savoir pourquoi cela plante ya 1000 raisons
et pareils pour en trouver une

**Comment by milkibreizh** [comment]
pas certains mais mon impression c'est que quand il y a une redirection d'url qui n'est pas dans le fichier m3u8
kodi plante et les urls googles sont des redirections d'url

**Comment by TmpName** [comment]
Oui c'est bien kodi, mais le probleme c'est que les m3u8 sont vraiment des fourre touts, il peut se passer n'importe quoi, et en plus on jongle entre 2 hosters, google et bidzen).
Perso j'ai pas envis de comparer les requetes entres un lecteur qui fonctionne et une autre qui ne fonctionne pas pour trouver la petite bete.

J'ai essayé de trouver des vieux lien de video google (sur google justement) mais toutes les videos etaient HS.

**Comment by milkibreizh** [comment]
@TTmpName

mais j'avoue ne pas comprendre exactement comment tu pourrais
parvenir a résoudre le problème même si tu savais exactement ou il
est?
tu crois qu'en utilisant des libs spécifiques de google cela résoudrait
le problème de la lecture du m3u8

**Comment by yodidon** [comment]
ce qui se rapproche le plus c'est ce que l'on trouve pour l'iptv....

**Comment by TmpName** [comment]
Bon je laisse tomber, j'ai passé quelques sources dans Vstream, impossible d'en trouver une tournant avec google video. Faut que je vire les sources HS.

Le truc c'est que c'est plus facile de trouver la solution en cherchant sur internet "comment lire video google" que "comment lire video m3u8", m3u8 ca ne veux rien dire.

**Comment by yodidon** [comment]
Oui je lâche l’affaire aussi et pourtant kepliz faisait partie de mes préférés... mais de mon côté pas de solutions

**Comment by TmpName** [comment]
Mais je comprend pas comment VLC ne puise pas le lire, c'est son boulot quand meme.

**Comment by milkibreizh** [comment]
> Mais je comprend pas comment VLC ne puise pas le lire, c'est son boulot quand meme.

bah justement hier j'ai regardé le log de vlc
il prend bien bien la redirection de la première url

url tps://lhx.googleusercontent.com/prox
puis on a l'impression que des qu'il veux lire les données de cette url
il plante ...il ne vas pas plus loin
_adaptive error: Failed to create demuxer 0000000000000000 Unknown_

**Comment by milkibreizh** [comment]
j'avais pas vu L'UA dans vlc dommage qu'on ne puisse pas mettre un header plus complet
du genre avec des cookies mais je crois que ce n'est pas utilisé pour un histoire de script et de sécurité 
je cherchais justement un autre player m3u8 à installé sur l'ordi ,et qui marche,pour écarter l’hypothèse qu'il faut des paramétrés supplémentaires que seul les lecteurs online peuvent posséder (cokkies ,user agent)
car jusque ici c'est les seuls qui arrivent à lire les fichiers

**Comment by TmpName** [comment]
Ben les cookies aussi sont gerés, j'ai vu passer ca dans les logs de VLC.

Mais oui il y a une subtilité non presente sur les lecteur locaux, et la je vois pas.

**Comment by kris06** [comment]
Salut les gars, à quand la prochaine mise à jour ? plus que 4 sources films en service... 
streamcomplet - zustream - allfilms - vfspace     https://www.dropbox.com/s/unihgmljwk6dld5/kodi.jpg?dl=0
Merci à vous pour vos informations.

**Comment by yodidon** [comment]
La prochaine mise à jours arrive très vite, malheureusement certaines sources ne sont plus réparables.

**Comment by milkibreizh** [comment]
@yodidon 
> certaines sources ne sont plus réparables.

et d'autres sources comme 4kst-reamz qui ne sont plus du tout récupérables :joy:

**Comment by yodidon** [comment]
Je vais la refaire 🥶

**Comment by yodidon** [comment]
Voilà refait enfin presque j’ai loupé la recherche elle marche pas et là je suis claqué...

**Comment by milkibreizh** [comment]
@yodidon 
ht_tps://pastebin.com/0tmvk8Cq
j'ai pas mis de filtre de recherche et donc ya pas URL_SEARCH_SERIE pour le global
_Pastebin’s SMART filters have detected potentially offensive or questionable content ahead._ 
je sais pas ce que c'est ce truc j'ai pas cela sur mes autres pastes

**Comment by yodidon** [comment]
@milkibreizh merci, mais du coup on est 2 à faire la même source?

**Comment by milkibreizh** [comment]
@yodidon 
Non pas du tout ... je l'ai fait pour tester pour savoir ce qu'elle avait comme ressource, il doit manquer des trucs dans ma source comme separer les hoste FR et vost et d'autres trucs et j'ai pas tout testé

**Comment by milkibreizh** [comment]
@yodidon 
cette source est bien , j'ai l'impression que les films et serie sont récent et les liens mise a jours
ce que je redoute le plus c'est les liens morts des sites qui ne sont pas enlevé ...c'est pénible

**Comment by sizanic** [comment]
>ht_tps://pastebin.com/0tmvk8Cq
_Pastebin’s SMART filters have detected potentially offensive or questionable content ahead._
je sais pas ce que c'est ce truc j'ai pas cela sur mes autres pastes


Pour éviter ce message, passe directement en mode /raw
ht_tps://pastebin.com/raw/0tmvk8Cq
