### ISSUE TITLE
Suivi des bugs v0.8.2 pour une v0.8.3

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3058]
> Ça serait sûrement plus simple si cette issue était moderé

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3096#issuecomment-716489454

Trouver vous quelqu'un de modéré si ma personne ne vous convient pas.

**Comment by TmpName** [comment]
Ben le soucis c'est que m3u8, c'est vaste, tu peut y mettre n'importe quoi dedans.
Ton deuxieme lien, marche tres bien sur site html mais pas dans VLC ou media player classic (kodi utilise le meme systeme) donc ca ne me surprend pas que le code ne marche pas dans kodi)

Le host pourrait bloquer si par exemple l'user agent n'est pas bon, mais tu aurais une erreur du type 403 ou 404 (mais j'ai quand meme testé), donc je pense vraiment a un format non géré par kodi, j'ai exploré aussi du coté du plugin inputstream (au pif) mais rien a voir

>NB (HS) : kodi matrix a un plugin ffmpegdirect qui pourrait lire les m3u8 et hls mais il n'est pas présent sur leia donc possible que ces liens direct de kaydo se lise sur kodi matrix et si c'est pas le cas cela prouverai que le problème vient du host vidzen

Ben il se pourrait bien qu'un autre plugin puisse lire ce format, mais la par contre j'ai pas testé.

Mais si arrive a faire lire ce fichier m3u8 dans VLC par exemple, c'est bon, ca devrait passer dans kodi.

**Comment by TmpName** [comment]
Ok donc nouvelle section ^^
**Site a supprimer, car HS et pas de nouvelle URL:**
- TVserieStrm (il marche chez toi, moi l'url ne donne rien)
- strmavie.com, personne n'a vu d'url alernative, c'est assez specifique comme contenu
- N1stm
- filmillimt

**Comment by Che-debarras** [comment]
> Ok donc nouvelle section ^^
> **Site a supprimer, car HS et pas de nouvelle URL, ou captcha:**
> 
> * TVserieStrm (il marche chez toi, moi l'url ne donne rien)
> * strmavie.com, personne n'a vu d'url alernative, c'est assez specifique comme contenu
> * N1stm
> * filmillimt
> 
> Je les vire dans la semaine, si personne ne trouve a redire.
> 
> Vidzstore ok chez moi.
> C'est quoi la nouvelle url de Filmstrmngvf ?

Tvseriesstrmng semble être devenu https :// voirseriestreaming .c0m
N1strmng semble être devenu 01strmng
Flmstrmngvf semble etre devenu https://filmstreamingvf.onl
Filmllmte et strmAvie a supprimer effectivement 

Vidzstore ne fonctionne pas sur android 
J'ai testé le film Tenet qui fonctionne sur navigateur mais pas sur vstream

**Comment by LordVenom** [comment]
Avec tous le respect que j'ai pour les retours de rapport de bug, vas falloir ce calmer sur les posts, j'ai vraiment mieux a faire que de gérer les issues du github.

**Comment by TmpName** [comment]
J'ai testé les changement d'url, tout a refaire, donc pour moi c'est pas un changement d'url.

**Comment by TmpName** [comment]
Debut du replacement de n1strm par la nouveau site, mais je commence deja a regretter, y a presque que des saisons 1 .....

**Comment by Che-debarras** [comment]
> Debut du replacement de n1strm par la nouveau site, mais je commence deja a regretter, y a presque que des saisons 1 .....

Il me semble que @milkibreizh avait deja travaillé sur cette source dans une autre discussion.

Sinon j'ai vérifié sur la version web , il y a beaucoup de saions 1 car c'est des nouvelles series qui debutent.
Esprit criminel a 15 saisons, Empire en a 6, young sheldon en a bien 3. Donc ya pas mal de nouvelles series qui débutent. 
Maintenant les sites comblent le peu de series avec des series étranges voir des dramas coréens.

Merci pour la maj.

**Comment by milkibreizh** [comment]
@TmpName 
> Debut du replacement de n1strm par la nouveau site, mais je commence deja a regretter, y a presque que des saisons 1 .....`
nouveau site ?
si c'est celui la w___ww.01streaming.net je le connais au moins depuis 2 mois
pour moi ces deux sites n'ont  vraiment strictement rien à voir

**Comment by TmpName** [comment]
Nope c'est un .net > https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/n1streaming.py

Dis moi si tu es deja dessus ou pas, je le continu demain soir sinon.

**Comment by milkibreizh** [comment]
je l'ai fait ya deux semaine mais j'ai mis pleins de bidouille ?
h__ttps://www.01streaming.net/

**Comment by milkibreizh** [comment]
non vers le 4 septembre

**Comment by milkibreizh** [comment]
je sais pas cela va prendre autant de temps de le mettre normalisé vstream
que de partir de ton fichiers
regarde le bordel !
https://pastebin.com/Aa7eDwTD

par contre il y a tous les patterns pour tous les menus

**Comment by milkibreizh** [comment]
mais de toute facon ce n'est pas le meme site c'est une autre source

n1streaming.co - Registered at Namecheap.com
Registration Date: 	Sep 26, 2019, 
Expiration Date: 	Sep 26, 2020, 

 01streaming.net Domain Registrar: 	Dynadot, LLC 
Registration Date: 	Apr 20, 2020,
Expiration Date: 	Apr 20, 2021,

**Comment by milkibreizh** [comment]
@TmpName 
du coup laisse tombé je vais partir de ton fichier et je rajouterais les éléments
essentiel au fur et a mesure sans mettre mes codes susceptibles de compliquer
les choses pour 2 ou 3 options de plus.
j'essayerais de faire de mon mieux mais c'est pas moi qui code le plus proprement
il faut aussi pouvoir maintenir le code surtout sur ce site
que j'ai vu changer deux ou trois fois en un moi

**Comment by milkibreizh** [comment]
@TmpName 
ca y est j'ai finit la source j'ai mis le minimum
par contre ya pas de desc pour les films car j'ai laissé ton hoster 
MOVIE_ANNEES = (True, 'showMovieYears')
MOVIE_GENRES = (True, 'showMoviesGenres')
SERIE_GENRES = (True, 'showSeriesGenres')
+showsaison 
( oui ya pas que une saison  à chaque fois :grin:)
faut tester les bugs maintenants

**Comment by mannou78** [comment]
Je m excuse si j ai rate la solution mais ZT Sous android comment le faire marcher. J ai telecharge la version beta et ca fonctionne toujours pas Merci bcp !!

**Comment by Che-debarras** [comment]
> Je m excuse si j ai rate la solution mais ZT Sous android comment le faire marcher. J ai telecharge la version beta et ca fonctionne toujours pas Merci bcp !!

Le premier reflexe à avoir c'est de vérifier si le DNS a été changé
Moi sur ma box tv j'utilise DNS changer et je demarre jamais kodi sans activer cette appli

Et le 2e réflexe est de lire le 1e post de ce sujet qui informe des bugs et des solutions notamment le DNS.

**Comment by TmpName** [comment]
@milkibreizh lol, ben tu sais quoi, je te la laisse now ^^, ou alors tu me dis ce qui peut poser probleme, car la ce n'est plus du tout la ou je l'avais laissée.

Par contre je devrais la tester ce soir. Y a une serie que je suis dessus.

**Comment by milkibreizh** [comment]
@TmpName 
bah je peux pas dire plus que les commentaires que j'ai laissé lors du pr...
surtout que j'ai encore écrit un roman...pas vu de bug encore

**Comment by milkibreizh** [comment]
@TmpName 

> car la ce n'est plus du tout la ou je l'avais laissée

mais j'ai à peine modifié le showmovie
et j'ai laissé le showHosters / ShowEpisodes tel quel

tu devrais pouvoir t'y retrouver même les yeux fermés te connaissant :grinning:

**Comment by Che-debarras** [comment]
O1strmng alias n1strmng n'affiche pas toutes les saisons
Ex westworld saisons 2 et 3 pas visibles
Surment d'autres series

**Comment by milkibreizh** [comment]
> O1strmng alias n1strmng n'affiche pas toutes les saisons

en effectuant une recherche "westworld" on devrait obtenir
westworld[serie]
puis l'affichages des 3 saisons
s03/S02/s01

Autrement  sur l'avant dernier pr il est impossible
en effet d'afficher toutes les saisons
la version récente possède les menus films (genre) serie (genre) 
mais elle n'as été testée que sur windows10 
kodi 18.6 pour l'instant

sinon il faudrait  préciser par quel menu l’accès aux séries ou films à été effectuée
pour pouvoir vraiment cibler le comportement du bug
que je n'arrive pas a créer en tous cas sur ma config

par exemple a tester
Menu série
l’éternelle sorcière
j'ai bien les 2 saisons et les épisodes

**Comment by Che-debarras** [comment]
Je confirme que n1stremng alias o1strmng sur android n'affiche pas toutes les saisons.
Je suis aller dans la source,  j'ai cherché westworld qui est a de nombreuses pages plus loin

D'ailleurs : ya pas le numéro des pages et je pense que parfois les pages se  répètent.

J'ouvre westworld et je voit que la saison 1.
J'ai aussi fait une recherche sur la source,  ya que la saison 1
J'ai aussi fait une recherche globale sur tous les sourcs et ya que saison 1

**Comment by milkibreizh** [comment]
> Je confirme que n1stremng alias o1strmng sur android n'affiche pas toutes les saisons.
pour 01 streaming
tester : Menu>Séries (Genres) >Action >Ash vs Evil Dead

**Comment by TmpName** [comment]
Attendez, vous voulez dire que Vstream n'affiche pas les memes resultats pour O1strmng selon la machine ?

**Comment by Che-debarras** [comment]
@TmpName 
Non, @milkibreizh demande à  tester Et moi jai testé westworld sur box android et on n'a qu'une seule saison.
Qui a toutes les saisons de westworld sur sa machine android?

**Comment by milkibreizh** [comment]
> Attendez, vous voulez dire que Vstream n'affiche pas les memes resultats pour O1strmng selon la machine ?

testé chez un ami et j'ai même pas eu le temps de prendre l'apero :weary:
kodi 18.6 |android TV 
os 8.0.0 |vstream beta
aucun soucis

**Comment by Che-debarras** [comment]
Sauf que 18.6 ce n'est pas la derniere version de kodi.
Ya eu 18.7 et 18.8 et le crash de k@ydo a lieu avec les versions avant 18.8
J'ai 18.8 sur 2 box tv, sur mon smartphone et sur une android tv et il manque des saisons.

@milkibreizh est il possible d'avoir une capture écran que les 3 saisons de westworld sont bien présent sur vstream avec la source n1strmng?

**Comment by milkibreizh** [comment]
@Che-debarras 
je  ne comprends pas pourquoi tu me demandes que je fasse une capture d’écran
par contre je voudrais bien que tu me fasse une capture d’écran de ton menu
pour voir si il est ordonnée comme le mien

**Comment by Che-debarras** [comment]
C'est bon désolé c'est encore la maj beta qui ne s'applique pas.
Je ne comprend pas pourquoi a chaque fois je fais une mah beta, les modifs ne s'applique pas meme en nettoyant le cache de vstream ou de kodi.

J'ai du supprimer le dossier site de l'addon kodi et le remplacer par celui du zip de la version bêta car apparemment la maj via zip ne fonctionne pas.

Est ce un souci du plugin beta ou de kodi? Est ce vous avez ce souci ou la maj via zip applique les modifs sans devoir supprimer au préalable les fichiers py et pyo?

**Comment by milkibreizh** [comment]
super la confiance

<img width="741" alt="Capture" src="https://user-images.githubusercontent.com/65681507/94845774-71d23c00-0420-11eb-9cfd-4fad7bfd20fb.PNG">

**Comment by benking110181** [comment]
je viens de test sur shield a jour et je n'ai que la saison 1 kodi 18.8

**Comment by Che-debarras** [comment]
> je viens de test sur shield a jour et je n'ai que la saison 1 kodi 18.8

C'est parce que comme moi la maj n'a pas été appliquée par kodi.
Il faut que tu ailles dans le dossier addon de vstream et tu supprime le dossier "site" et tu colle le dossier site de la fichier zip que tu a télécharger.

Le gestionnaire de fichier de kodi te permet de:
A droit de choisir ton fichier plugin.video.vstream.zip beta que tu a télécharger 
Tu y clique pour acceder au fichier a l'intérieur jusqu'au dossier "Site
Tu fais la meme chose a gauche en allant a Android/data/org.xbmc.kodi/file/.kodi/addons/plugin.video.vstream//ressouces et la tu supprime le dossier "Site"
Tu va a droite tu sélectionnes le dossier "site"de la beta télécharger en restant appuyer pour avoir une fenetre 
Cette fenêtre te permet de copier ce dossier "site" sur le dossier de gauche.

Et tu redémarres kodi.

En espérant que ce soit claire et là tout les maj sont appliquées.

Malheureusement va falloir faire ça a chaque fois vu que kodi ne semble pas appliquer les maj beta de vstream

**Comment by benking110181** [comment]
c clair enfin y a plus facile pour le faire mais c bon.
Par contre il ne prend pas les mise a jour que pour certain sites parce qu'il applique les maj d'autres sources et ca le fait depuis quand?

**Comment by Che-debarras** [comment]
> c clair enfin y a plus facile pour le faire mais c bon.
> Par contre il ne prend pas les mise a jour que pour certain sites parce qu'il applique les maj d'autres sources et ca le fait depuis quand?

Je sais qu'il y a plus facile mais la tu es certain que ta les nouveaux fichiers de la beta
Exactz ça prend les maj pour certains et pas d'autres et je dirais depuis quelque mois voire kodi 18.7
Je sais pas si c'est lié au fait que vstream est sur la liste noire de kodi.

Mais ça depend les personnes je pensais etre le seul mais visiblement non.

Je pense que je vais faire une maj manuelle en supprimant le dossier plugin.video.vstream et copier coller celui du fichier zip de le beta grâce au gestionnaire de fichier. C plus long mais c plus sûr

**Comment by benking110181** [comment]
que celui du addon pas addon data

**Comment by Che-debarras** [comment]
> que celui du addon pas addon data

Oui que addon. Pas celui de addon beta

**Comment by benking110181** [comment]
juste pour etre sur ca fait la meme chose que tu copie l'interieur du zip et colle que installer par zip fonction kodi ? parce que ca m'arrivai sur ma shield j'ai accé direct au repertoire interne sur mon pc de copier collé direct l'interieur du zip

**Comment by Che-debarras** [comment]
> juste pour etre sur ca fait la meme chose que tu copie l'interieur du zip et colle que installer par zip fonction kodi ? parce que ca m'arrivai sur ma shield j'ai accé direct au repertoire interne sur mon pc de copier collé direct l'interieur du zip

Oui copier coller le zip dans le dossier addon ou maj par zip c'est la même chose
Kodi va décompresser et copier coller le dossier plugin.video.vstream du dossier zip dans le dossier addon de kodi où ya tous tes addons.

**Comment by benking110181** [comment]
alors les problèmes que certain on pour accéder a z t par exemple sur android pourrai venir de cela aussi si tu le c pas tu peut pas remarquer que la maj et pas bien passé ou copier coller et c que sur android?

**Comment by Che-debarras** [comment]
> alors les problèmes que certain on pour accéder a z t par exemple sur android pourrai venir de cela aussi si tu le c pas tu peut pas remarquer que la maj et pas bien passé ou copier coller et c que sur android?

C'est vrai aussi mais en general c'est le DNS qui a pas été changé mais tu marques un point. 

As tu toi aussi une recherche globale incomplète ? 
Je lance la recherche sur westworld et il s'arrête le résultat a kstrmng serie.
C'est un ancien bug qui a été corrigé mais il refait surface

**Comment by benking110181** [comment]
j'ai eu des souci avec la recherche globale sur certain films et sur certaine source le films je suis sur qu'il etait la

**Comment by benking110181** [comment]
attend je copie colle je vais test ensuite

**Comment by benking110181** [comment]
time 2 watch j'ai vu sur discord des messages passais que ca ne marcher pas

**Comment by benking110181** [comment]
westworld c bon maintenant merci pour l'info il faudrait que tu fasse une issue pour les possesseurs android c vraiment bon a savoir et ca peut regler d'autre probleme

**Comment by benking110181** [comment]
pour la recherche globale ca doit dépendre des sources activer tu les a toutes activé toi

**Comment by milkibreizh** [comment]
> Je lance la recherche sur westworld et il s'arrête le résultat a kstrmng serie

essaye d'enlever mystream j'ai l'impression que c'est lui qui fou le bordel
je l'avais pourtant testé en recherche global quand le site était inaccessible

**Comment by Che-debarras** [comment]
> westworld c bon maintenant merci pour l'info il faudrait que tu fasse une issue pour les possesseurs android c vraiment bon a savoir et ca peut regler d'autre probleme

Je ferais une remarque sur le 1e poste 
Sinon time2watch fonctionne que pour les films 
Merci de l'avoir signalé je le met sur la liste

**Comment by Che-debarras** [comment]
> pour la recherche globale ca doit dépendre des sources activer tu les a toutes activé toi

Ils sont tous activés par defaut je pense

> 
> essaye d'enlever mystream j'ai l'impression que c'est lui qui fou le bordel
> je l'avais pourtant testé en recherche global quand le site était inaccessible

Tu veux dire désactiver ?

**Comment by milkibreizh** [comment]
oui quand le resultat s'arrete soudainement cela peu être du a une source qui fait disjoncter la recherche globale

**Comment by milkibreizh** [comment]
@Che-debarras 
bah si tu veux le supprimer on peu
mais c'est une source on ne sait jamais quand elle marche
le bug doit etre corrigeable
..mais pas ce soir

**Comment by milkibreizh** [comment]
@Che-debarras 
je suis d'avis en tous cas de la supprimer si personne ne se sert de cette source

**Comment by Che-debarras** [comment]
> @Che-debarras
> je suis d'avis en tous cas de la supprimer si personne ne se sert souvent de cette source

J'ai fait une recherche d'une serie et il marque site inaccessible 
Je le met dans la liste des bugs

**Comment by milkibreizh** [comment]
@Che-debarras 

c'est pas un bug..souviens toi d'autant plus que c'est une source que tu a proposée
le site est parfois accessible parfois non
on peu surveiller son cycle d'apparition sur deux ou 3 jours par exemple
 et si c'est pas convainquant....poubelle

**Comment by milkibreizh** [comment]
par contre le bug c'est quelle ne devrait pas arrêter la recherche globale même quand le site est inaccessible

**Comment by milkibreizh** [comment]
je vais désactiver la source en pr et je verrais bien apres

**Comment by Papounet58** [comment]
Le site Planet Stream fonctionne à nouveau.
Seuls des liens Netu sont dispo donc pas possible de lancer une vidéo.
Merci pour votre travail.

**Comment by Che-debarras** [comment]
Time2watch refonctionne avec un pti souci: le dernier dossier vostfr de chaquz épisode et de plusieurs series ne S'ouvre pas mais les autres dossier vostfr ou vr s'ouvrent

**Comment by TmpName** [comment]
Planet Strm je viens de jeter un oeil, franchement je le sens pas du tout sur le long terme.

**Comment by milkibreizh** [comment]
le liens en question n'apparait pas dans le navigateur
c'est un lien invalide et il n'y a aucune vidéo qui y est associée
donc ce n'est en effet qu'un petit souci

**Comment by milkibreizh** [comment]
je le sens pas du tout,tout de suite

**Comment by milkibreizh** [comment]
@TmpName 
j'en profite que tu sois la ya un pattern hs sur Time2watch
j'ai mis
ligne  454
`sPattern = '<span style="margin-left: 20px;">(.+?)</span>|<span style="margin-left: 35px;">(.+?)<.+?<span class="fa arrow">|setfatherasseen.+?<i class="fa fa-download fa-fw">.+?<b>(.+?)</b>.+?var hash_.+?= "(.+?)"'
`
en faite le bute du jeux c'est d'exclure le lien qui a la propriété display: none
car il fait planter tirexo

mais meme si se pattern marche je le trouve tordu

**Comment by milkibreizh** [comment]
@TmpName 
j'ai rajouter `|setfatherasseen.+?` pour exclure le lien

**Comment by Che-debarras** [comment]
> Planet Strm je viens de jeter un oeil, franchement je le sens pas du tout sur le long terme.

Pour moi depuis longtemps il n'est plus fiable.
Il était associé avec seriestrmnghd qui n'est plus a jour depuis des mois
Tout comme le clone strmngplanet qui na que du Netu.

Mon avis serais de les désactiver a moins de trouver une solution pour Netu.
Est ce que Netu marche avec un player externe ?

**Comment by Arias800** [comment]
Le problème de Netu c'est qu'il est protégé par Recaptcha.
@milkibreizh fait un pr avec ce pattern (c'est pas grave s’il est tordu car de toute façon le site est compliqué de base) xD

**Comment by milkibreizh** [comment]
@Arias800 
c'est pas le pattern d'origine que je trouve tordu c'est la chaine 'setfatherasseen' en qui j'ai pas du tout confiance
car cela pourrait peu être changé dans le temps par setmotherasseen^^

**Comment by TmpName** [comment]
Je pense comme aria800, franchement te prend pas la tete.
Tu pourrais prendre le bloc precedent et juste rechercher si "display: none;" est dedans, mais ils peuvent chnager aussi les balises html donc tu vas galerer pr attraper le bon bloc.

J'ai testé ta methode est simple, elle marche et est facilement modificable.

Tu pourrais faire plus complexe, mais ca peut se "casser" aussi vite. Moi je laisserais comme ca.

**Comment by Che-debarras** [comment]
J'ai mis a jour le 1e poste
Visiblement Zustrm esf peut etre passé sous CF a la minute où j'écris car les dossiers ne S'ouvrent plus, et parce que la version navigateur affiche cloudfare et que la recherche de film et serie ne donne aucun resultat.

ZTLCHRGMNT non plus ne fonctionne plus

**Comment by milkibreizh** [comment]
je confirme pour Zustrm encore CF notre Clown Favori qui nous fait encore des blagues à deux balles

**Comment by milkibreizh** [comment]
Zustrm maintenant ok

**Comment by Che-debarras** [comment]
Voirhd inaccessible

**Comment by milkibreizh** [comment]
voirhd..
la date d'expiration de son enregistrement était prévue
Domain Expiry Date
2020-10-08T17:19:19+02:00
....faut surveiller si il réapparait sait-on jamais
par contre il y a un vrai clone  pour vkstream ( même code html des pages et même nombre de source a 99%)
h_ttps://wvw.voirseries1.co/ donc c'est reparti pour lui

**Comment by TmpName** [comment]
Au sujet de la source Mystrm ?
Elle a été supprimée ? Elle fonctionne chez moi (vielle version de Vstream)

**Comment by milkibreizh** [comment]
@TmpName 
Mystrm
j'ai testé la page les jours  1 a 2 fois pendant 10 jours sur le navigateur et je ne l'ai jamais vu répondre et donc je l'ai mis a la poubelle pensant qu'il était définitivement inaccessible
le site remarche  c'est vrai...mais il n'est pas fiable comme site ,il marche ,il marche pas on sait jamais

Autrement  depuis 3 4 jours pour allfilms tu as  Account Suspended
et toro  fait encore ses siennes mais il devrait peu être revenir
voirhd est revenu il y a  3 4 jours

**Comment by TmpName** [comment]
Yep j'ai vu pour voirhd.
Pour les autes c'est recent, donc je laisse comme ca.

**Comment by Che-debarras** [comment]
Je confirme voirhd est revenu
Zt ne fonctionne pas , impossible d'ouvrir les les films ou series 

Par contre une maj a jour du host mystrm (a pas confondre avec la source mystrm supprimé) a été faite et du coups l'host ne marche plus.

J'ai regardé toute la saison 5 de magicians sauf les 2 derniers épisodes et depuis ce matin plus rien ne marche

**Comment by Arias800** [comment]
En ce qui concerne mystrm je l'ai corrigé car il ne fonctionnait plus (du moins sur Windows). Mais visiblement Kodi se comporte différent sur Android (j'ai testé le même film sur la même source au même moment). Donc je vais voir pourquoi ca ne marche pas.

**Comment by Arias800** [comment]
@Che-debarras Je viens de corrigé Mystream sous Android.

**Comment by Che-debarras** [comment]
@Arias800 
Désolé apres vérification le host mystrm ne fonctionne toujours pas

**Comment by Arias800** [comment]
Essaye avec ce fichier et donne moi les logs, car j'ai testé avec mon téléphone et ma shield et ça fonctionne sur les deux : https://github.com/Arias800/Fichier-divers/blob/master/mystream.py

**Comment by Che-debarras** [comment]
Ce fichier que tu propose n'est pas le meme que celui que tu a mis sur la beta.
Celui de la beta que ta mis fait 3.55kb et celui sur ton fichiers-divers 3.62kb
Et celui que je remet pour refonctionner mystrm fait quant a lui 3.63kb 
Enfin bref, celui de ton lien ci dessus semble  fonctionner mais pas la version beta

**Comment by Arias800** [comment]
C'est le même fichier, la différence c'est que j'ai juste rajouter des messages dans les logs pour comprendre d'où pouvait venir le problème de ton côté. Donc logiquement il n'y aucun changement qui peut justifier le fait que ca remarche chez toi, c'est quand même bizarre.
![image](https://user-images.githubusercontent.com/24809312/96688690-c1ea5180-1381-11eb-8008-34d82102cc0d.png)

**Comment by Che-debarras** [comment]
> C'est le même fichier, la différence c'est que j'ai juste rajouter des messages dans les logs pour comprendre d'où pouvait venir le problème de ton côté. Donc logiquement il n'y aucun changement qui peut justifier le fait que ca remarche chez toi, c'est quand même bizarre.

J'ai comparé les 3 fichiers et l'autre différence c'est la ligne 115 final_data qui n'est pas la même
Le plus important c'est que cela marche.

**Comment by kris06** [comment]
salut à tous et merci pour la maj 0.8.3 ,  j'ai eu la surprise de voir apparaitre la nouvelle source WAWA CITY, malheureusement, 
aucun lien ne fonctionne....
vstream lea 18.9  sur pc et android

**Comment by kris06** [comment]
pour information, la recherche similaire à partir du marque page n'est plus accessible 
kodi  18.9 android et pc

**Comment by sizanic** [comment]
> pour information, la recherche similaire à partir du marque page n'est plus accessible
> kodi 18.9 android et pc

J'ai vu ça aussi, je vais regarder ce point.

**Comment by sizanic** [comment]
@kris06 
C'est corrigé dans la Beta.

**Comment by kris06** [comment]
Merci beaucoup Pourquoi wawacity n a aucun liens qui fonctionnent?Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : sizanic <notifications@github.com> Date : 10/12/2020  19:33  (GMT+01:00) À : Kodi-vStream/venom-xbmc-addons <venom-xbmc-addons@noreply.github.com> Cc : kris06 <christian.gross@free.fr>, Mention <mention@noreply.github.com> Objet : Re: [Kodi-vStream/venom-xbmc-addons] Suivi des bugs v0.8.2 pour une v0.8.3 (#3058) 

@kris06

C'est corrigé dans la Beta.

**Comment by sizanic** [comment]
Ce sujet est clos.
Merci de créer un nouveau sujet pour déclarer un nouveau problème.

**Comment by kris06** [comment]
Bonjour, j'ignore ce qui se passe avec votre dernière mise à jour 0.8.3 mais tous les liens sont en 360 ou 480p quelque soit le choix de la définition... 
sur Android ou pc kodi 18.9
