### ISSUE TITLE
Lecture fichier M3U8 (k@ydo/hd$$)

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3060]
**Décrivez le bug**
Je propose de discuter ici du probleme de m3u8 afin d'apporter des idées pour resoudre ce souci avec comme point de depart la discussion qui suit:

**### Actu: il semble que sur le site web (navigateur) les videos ne se lance plus sans doute un souci avec vidzen. 
Donc ce sujet n'est pas urgent**

@TmpName @yodidon 

> ok donc kepliz encore HS.
> 
> Ton code est bon juste le format du m3u qui ne doit pas etre compatible nativement avec kodi.
> Essayes le lien sur vlc ou media player classic, il ne marchera pas non plus.
> 
> J'ai essayé en simulant le User-agent, marche toujours pas.

Ce lien h_ttps://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 marche avec kodi/vstream grâce à hoster direct donc pour moi vstream et kodi lisent les m3u8 .
Donc la fonction hoster direct (à condition qu'il y a d'autres tests avec d'autres fichier m3u8) si elle lis les fichiers alors le problème serait plus du côté de la source ou hoster.

J'ai testé ce test-stream: ht_tps://hls-js-dev.netlify.app/demo/
Avec le lien d'un film "société secrète de la royauté "extrait de la source kaydo ci dessus:
htt_ps://lb.bidzen.co/hls/d64e21466e94ba26c7ba67824e384d30/d64e21466e94ba26c7ba67824e384d30.m3u8

Il marche sur le site de test mais pas sur vstream hoster direct contrairement à x36xhzz.m3u8.
Le problème ne vient il pas du hoster Vidzen devenu lb.bidzen.co dans la lecture ?! Je ne vois pas ce hoster dans le dossier host de vstream ni d'exception sur le liendirect.py?!

NB (HS) :  kodi matrix a un plugin ffmpegdirect qui pourrait lire les m3u8 et hls mais il n'est pas présent sur leia donc possible que ces liens direct de kaydo se lise sur kodi matrix et si c'est pas le cas cela prouverai que le problème vient du host vidzen

**Comment by Che-debarras** [comment]
La reponse de @TmpName 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3058#issuecomment-700143296

**Comment by Che-debarras** [comment]
Apres quelqie recherche sur le net, certains parles de scripts permettant de lire des fichiers m3u8

Donc J'ai également testé 2 scrips lié à HLS et m3u8
https://mirrors.kodi.tv/addons/leia/service.nhl-hls-proxy/service.nhl-hls-proxy-0.0.3.zip
https://mirrors.kodi.tv/addons/leia/script.module.m3u8/script.module.m3u8-0.3.7.zip

Malheureusement sans succès. 

J'ai aussi lu sur le forum de kodi un script m3u8 parser qui permettrait de lire les m3u8:
https://kodi.wiki/view/Add-on:M3u8 mais je n'ai pas trouver de release zip installable (sous forme de ficher .py).

Matrix semble avoir un plugin ffmpegdirect qui lirait ces m3u8 donc a tester.

Si vous avez d'autres idées ou suggestions

**Comment by Che-debarras** [comment]
Je clos ce sujet pour l'instant :
Il semble que sur le site web (navigateur) les videos ne se lance plus sans doute un souci avec vidzen.Donc ce sujet n'est pas urgent

**Comment by TmpName** [comment]
Yep, je viens de retester, en panne chez le site, donc peut etre deja un changement a venir

**Comment by Che-debarras** [comment]
J'ouvre à nouveau ce sujet car hier Mardi 29 septembre la source a fonctionné et j'ai pu testé quelques film et vu 2 episodes de Wesworld.

Malheureusement aujourd'hui il ne fonctionne plus mais le site web sur navigateur fonctionne.

Du coup vu que kodi et vstream lis les fichiers, est ce que ce ne serait pas une protection du site ?

**Comment by Che-debarras** [comment]
J'ouvre à nouveau ce sujet car hier Mardi 29 septembre la source a fonctionné et j'ai pu testé quelques films et vu 2 episodes de Wesworld.

Malheureusement aujourd'hui il ne fonctionne plus mais le site web sur navigateur fonctionne.

Du coup vu que kodi et vstream lis les fichiers m3u8 est ce que ce ne serait pas une protection du site un peu comme Netu ou les liens de la source E.D?

NB: ya des url dite blob qui integre des videos m3u8, pensez vous que ce site utilise ce systeme blob? 
En cherchant a lire le fichier .m3u8 il affiche plusieurs lien .html?msKey=m11
Cela ferait reference a des scripts de Microsoft Edge et vu que k@yd0 recommande ce navigateur je me demande si c'est pas lié

https://webdevdesigner.com/q/playing-m3u8-files-with-html-video-tag-123901/

C'est surement hors sujet mais bon j'essaye de comprendre leur delire de ces sites ou hosts à empêcher dextraire les videos.

**Comment by TmpName** [comment]
>2020-09-30 17:30:54.230 T:17183 ERROR: Could not find suitable input format: x-directory/normal

moi ce message d'erreur me fait dire que le fichier n'est pas comprit par kodi, par exemple > https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2656

> Du coup vu que kodi et vstream lis les fichiers m3u8
Pas tous, un fichier m3u8 peux contenir d'inporte quoi.
