### ISSUE TITLE
Ajout sous menu "films Fr" dans extreme down

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#3062]
Bonjour a tous
Pourriez vous ajouter un sous menu/catégorie " Film Fr " qui engloberait uniquement les films en français (720p, 1080p, multi ....) Comme c'est le cas pour la rubrique series .
Merci et bonne continuation

**Comment by sizanic** [comment]
Bonjour @falciatrice10

Il faut considérer vStream comme un navigateur Internet allégé.
Ainsi, les menus que tu retrouves dans vStream sont ceux disponibles sur le site.

Pour les séries : 
![image](https://user-images.githubusercontent.com/47307622/94877604-4882d180-045b-11eb-8690-f7fa1a144bea.png)

On retrouve bien le même menu que vStream.
Sur vStream : 
- le menu "Séries(VF)" correspond sur le site à "Séries SD VF"
- le menu "Séries(VOSTFR)" correspond sur le site à "Séries SD VOSTFR"


Pour les films, le menu du site : 
![image](https://user-images.githubusercontent.com/47307622/94877950-51c06e00-045c-11eb-8971-0280346ba64e.png)


Sur vStream : 
- le menu "Films(VOSTFR)" correspond sur le site à "SD VOSTFR"
- le menu "Bluray VOSTFR" correspond sur le site à "1080p VOSTFR"

Tous les autres menus sont du FR.


>Pourriez vous ajouter un sous menu/catégorie " Film Fr " qui engloberait uniquement les films en français (720p, 1080p, multi ....) Comme c'est le cas pour la rubrique series .

Non, ce n'est pas le cas pour les séries.
Dans le menu "Séries (FR)", il n'y a que du SD.
Dans le menu "Séries (VOSTFR)", il n'y a que du SD.

**Comment by falciatrice10** [comment]
Bonjour
Dinc pas moyen de regrouper tous les hd ensemble ?

Merci

**Comment by sizanic** [comment]
On ne peut pas faire mieux que ce que propose le site.
On ne peut pas ajouter des menus qui n'existent pas sur le site, car chaque menu correspond à une page du site.
Il n'y a pas de page sur le site qui regroupe tous les HD.
Il n'y a pas de page qui regroupe tous les VF ou toutes les vostfr.

**Comment by sizanic** [comment]
> Donc pas moyen de regrouper tous les hd ensemble ?

non, pas moyen non plus.
