### ISSUE TITLE
Fixer type affichage

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#3063]
Bonjour
Il y a un petit souci de navigation entre les pages, il faut qu a chaque fois que je passe à la page suivante , je dois modifier l affichage de la page (grande liste, poster ....)
Est ce possible de verouiller l affichage ?

Merci

**Comment by sizanic** [comment]
C'est normalement du paramétrage avec ton skin de Kodi.

Si vraiment tu ne peux pas avec ton skin, tu peux forcer le mode d'affichage avec vStream.
Dans les paramètres de vStream, onglet Général -"Activer vue personnaliser".
Tu choisis : 50 = liste / 51 grande liste / 500 icone / 501 gallerie / 508 fanart

**Comment by sizanic** [comment]
Bien sûr, si tu gères l'affichage avec vStream mais que tu sélectionnes un mode qui n'est pas présent dans ton skin, celui-ci reviendra en mode par défaut, le mode liste.

Par exemple, si tu forces le mode 508 mais que ton skin ne gère pas l'affichage "fanart", tu aura le mode "liste".

Est-ce que maintenant ça fonctionne pour toi ?

**Comment by falciatrice10** [comment]
Il n y a pas le mode mur d infos

**Comment by sizanic** [comment]
Les valeurs que j'ai données sont les valeurs du skin par défaut de KODI.


Ensuite, en fonction de son skin, on peut mettre les valeurs supportées par le skin.

voici des exemples à partir de deux skins différents :

```
List = 50
VideoInfoWall = 51
Thumbnail = 52
LowPanel = 55
ShiftFixedList = 57 
Fanart = 59
VideoWall = 500
AddonWall = 520 
VideoLowList = 501 
VideoEpisode = 502 
Gallery = 504
Panel = 505
BigList = 507
Wall = 509

```

```
50=List
51=Big List
52=Media Info
54=Media Info 2
501=Big Icons
53= Grid View
502= Grid View 2
57=Fanart 1
59=Fanart 2
510= Fanart 3
```

**Comment by sizanic** [comment]
Il semblerait que "mur d'info" soit 54.

**Comment by sizanic** [comment]
Pur info avec le skin Unity : 
Informations du media 2 : 503
