### ISSUE TITLE
Question fonctionnement vStream

### ISSUE THREAD

**Issue by Bilal54** [Kodi-vStream/venom-xbmc-addons#3065]
Bonjour à tous, pouvez-vous me faire un petit tuto pour faire fonctionner time2watch chez moi svp ? 
J'ai fait pas mal de recherches mais je ne comprend pas trop l'histoire de url resolver etc.

Pour l'instant j'ai installé Kodi ainsi que vStream à partir de la source https://kodi-vstream.guthub.io/repo et je ne sais pas pourquoi time2watch et quelques autres sont écrits en rose. Ensuite quand je navigue dans time2watch et que je choisi par exemple un animé tout est écrit en rouge.

J'ai essayé de configuré vStream (ajout compte time2watch, uptopbox etc) mais au final impossible de lancer qqchose. :/

Merci d'avance !

**Comment by Bilal54** [comment]
Personne ? :/

**Comment by yas06** [comment]
salut instal la  version bêta t2w fonctionne est les site en violet généralement c des host premium genre 1f upto rapidg

**Comment by Bilal54** [comment]
> salut instal la version bêta t2w fonctionne est les site en violet généralement c des host premium genre 1f upto rapidg

D'accord mais je fais ça comment ?

**Comment by yas06** [comment]
> D'accord mais je fais ça comment ?
beta dispo ici  
https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream

**Comment by Bilal54** [comment]
Merci beaucoup je vais tester ça !! :)

**Comment by Bilal54** [comment]
Encore merci ça fonctionne parfaitement !
