### ISSUE TITLE
probleme recherche globale

### ISSUE THREAD

**Issue by benking110181** [Kodi-vStream/venom-xbmc-addons#3068]
il n' y aurai pas un problème de recherche globale je la trouve de moins en moins précise il m'affiche des résultats avec des nom qui n'ont rien a voir ou il faut lancer 2 fois la recherche et pour certaines source activées ca peut bloquer

**Comment by milkibreizh** [comment]
@benking110181 
bonjour
> il m'affiche des résultats avec des nom qui n'ont rien a voir 

Vstream affiche les résultats de la recherche qui est effectuée  par le site
hélas il y a des sites qui renvoient parfois n'importe quoi
si tu vois qu'il y a un décalage entre la recherche sur le site et celui dans vstream
alors en effet il y à un souci

> pour certaines source activées cela peut bloquer

lesquelles? 
tu parles du blocage du résultat,?
de l’arrêt de la recherche ?
tu n'as plus aucun resultats ?
et quelle comportement à cette 
source quand tu l'utilise directement

le problèmes de la recherche globale
sont liées ,le plus souvent,au comportement de chaque source
et non au moteur de la recherche globale de vstream

il faut donc voir cas par cas c'est pour cela que je te demandais
plus de précision

merci

**Comment by benking110181** [comment]
bonjour merci pour ta réponse je vais faire des test et reviendrai en dire plus

**Comment by milkibreizh** [comment]
@Che-debarras 
2a 2b 2c
ce n'est pas vraiment de mes compétences car il s'agit du fonctionnement interne de vstream
que je ne maitrise pas..je ne le connais qu'en gros et cela est suffisant pour créer de très gros bugs
si je mets mon gros nez dedans
autrement on peu filtrer le résultat au niveau de la source certaines le font d'autres non.
cela revient ou développeur de la source de choisir,si il met un filtre ou pas
peu être par contre qu'il y a comme même certaines sources qu'il faudrait corriger
mais là,encore une fois on est dans le cas par cas.

**Comment by milkibreizh** [comment]
@Che-debarras 
strmwatch résolu 
(time2watch problème trouvé et résolu mais je ne suis pas sur de la fiabilité de mon code donc pas de pr)

**Comment by Che-debarras** [comment]
Time2watch pas résolu, le dossier vostfr 1080p ne s'ouvre pas
