### ISSUE TITLE
Problème Lecture de séries ou films depuis TMDB

### ISSUE THREAD

**Issue by toadnam** [Kodi-vStream/venom-xbmc-addons#3077]
Bonjour,

J'ouvre une issue parce que cela ne fonctionne toujours pas comme avant...
Avant j'utilisais le player Pastebin qui allait me chercher dans mes sources pastebin ma série ou mon film.
Depuis la dernière mise à jour beta, impossible de trouver quoi que ce soit via TMDB .
Je clique sur Mulan depuis TMDB puis lecture puis play with pastebin ne marche plus. (j'attends d'avoir un retour de @benking pour modifier mon fichier pastebin.json)
J'ai essayé en attendant de suivre les conseils de @alkodique pour que ca fonctionne et là non plus sans résultat...
Je précise que dans sa méthode j'ai enlevé dans custom search list les rechercher films vstream et rechercher séries vstream et qu'il me reste que TMDB Films et TMDB Séries.
Quand je clique sur le film ou série depuis le résultat de ma recherche (TMDB Films ou TMDB Séries), je clique sur lire puis il essaye de faire sa recherche, je vois qu'il cherche dans les sources que j'ai sélectionné mais aucun résultat.. :-(
Je vous mets en pièce jointe mes deux players et vous me dites où est ce que ca bloque svp ca serait top.
[players.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5339274/players.zip)

Par avance merci, en attendant je continue d'alimenter mon pastebin ;-)

**Comment by toadnam** [comment]
Alors grace à @alKODIque qui m'a envoyé son vstream.json , j'ai bien le résultat et ensuite j'ai mes sources qui apparaissent. Merci à elle.
voici le bon vstream.json qui va bien [vStream.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5339360/vStream.zip)
est ce que quelqu'un peut m'aider à corriger le player pastebin qui je trouve est très pratique et beaucoup plus rapide que le vstream.json ?
voici le pastebin.json : 
[Pastebin.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5339388/Pastebin.zip)

Merci pour tout le boulot que chacun fait en tout cas !!

**Comment by sizanic** [comment]
Dans ton pastebin.json, remplace partout (4 fois) : 

`PASTE_ID`

par 

`%26pasteID%3dPASTE_ID`

**Comment by alKODIque** [comment]
> Dans ton pastebin.json, remplace partout (4 fois) :
> 
> `PASTE_ID`
> 
> par
> 
> `%26pasteID%3dPASTE_ID`

Je l'ai en zip si ça peut être utile :)

**Comment by sizanic** [comment]
alors perso, j'ai donné cette solution sans la testé 🤔 
@alKODIque c'est bien ce que tu as ?

**Comment by alKODIque** [comment]
> alors perso, j'ai donné cette solution sans la testé 🤔
> @alKODIque c'est bien ce que tu as ?

heuuu j'ai pas vu le tien haha!!
Mais celui que j'ai fonctionne et cest bien le remplacement que j'avais fait.
(perso, sur mon fichier je nai conserver que les "Search pastebin" mais j'ai remis les "play" ... donc ça va donner 2 choix de player pastebin:
1- search pastebin 
2- Play with pastebin

**Comment by toadnam** [comment]
> Dans ton pastebin.json, remplace partout (4 fois) :
> 
> `PASTE_ID`
> 
> par
> 
> `%26pasteID%3dPASTE_ID`

ca marche merci!

**Comment by sizanic** [comment]
@alKODIque 
je n'ai pas fourni de zip.
c'est ça la solution que j'ai suggéré : 
`%26pasteID%3dPASTE_ID`


@toadnam 
je te laisse clôturer le sujet si tu n'as plus de question (en rapport avec ce sujet 😄  ).

**Comment by toadnam** [comment]
Film recherché Mulan le Film (parce que je sais qu'il y en a plusieurs et dont chez certains en 4k ;-)
si je fais recherche avec pastebin, nickel je tombe sur les résultats de toutes mes sources pastebin . (dossier FILM créé dans pastebin avec toutes les sources pastebin)
si je fais play with pastebin j'ai quand meme un resultat mais un seul...pourquoi?

**Comment by sizanic** [comment]
Je ne sais pas comment fonctionne la fonction : "**_Play with pastebin_**"

Mais elle n'est pas censé lancer automatiquement le film ?
Donc sans doute en lançant le premier film qu'elle trouve.

Si elle ne lance pas le film, quel est son intérêt par rapport à "Search with pastebin" ?

Sans doute pour cela que alKODIque dit qu'elle n'a conservé que "search".

@alKODIque 
est-ce qu'avec d'autres sources, le lancement automatique du film fonctionne et ce n'est que avec pastebin qu'il y a ce problème (si problème il y a) ?

**Comment by toadnam** [comment]
> Je ne sais pas comment fonctionne la fonction : "**_Play with pastebin_**"
> 
> Mais elle n'est pas censé lancer automatiquement le film ?
> Donc sans doute en lançant le premier film qu'elle trouve.
> 
> Si elle ne lance pas le film, quel est son intérêt par rapport à "Search with pastebin" ?
> 
> Sans doute pour cela que alKODIque dit qu'elle n'a conservé que "search".
> 
> @alKODIque
> est-ce qu'avec d'autres sources, le lancement automatique du film fonctionne et ce n'est que avec pastebin qu'il y a ce problème (si problème il y a) ?

oui je pense que ca doit etre ca, il montre la première source qu'il trouve pour le lire.
Je vais laisser par defaut play with pastebin et si je ne suis pas satisfait de la qualité à ce moment-là je basculerai sur search with pastebin afin de basculer sur une autre qui correspond à ce que j'ai envie.

**Comment by alKODIque** [comment]
je n'avais pas pris connaissance des dernières discussions.

En fait, les players fonctionnants avec vStream ne fonctionnent pas bien avec la commande "play". 

A cause de la particularité de vStream qui récupère des liens streaming dans des dossiers. La commande "play" va fonctionner avec des addons comme seren , exemple, qui eux offrent des liens selon la configuration que nous avons déjà fait via l'addon. (ex: nos préférences de liens de lien premium "Real-debrid", de qualité, des liens magnets, etc..) le "play" doit choisir le lien qui répond aux critères établis d'avance. vStream ne nous permet pas de configurer nos choix quant a lui.

Avec vStream, (le player que tu utilisais pastebin) faut passer par l'étape "keyboard"  et cette façon apporte toujours des problèmes et bugs... Le keybord a souvent des fonctionnalités qui sont intégrées au skin utilisé, parfois autocompletition, etc... donc: le "play" est a éviter .  

Il faut privilégier avec vStream un player basé sur "search" qui lui, bien qu'il soit moins précis, n'apportera pas de bug et selon les sources choisies dans vStream, basera sa recherche sur celles-ci. 

Si tes sources ont bien identifié ce qu'est une Série et ce qu'est un Film, tu trouveras ce que tu cherche mais il te faudra plus de "clics" - ta recherche va s'arrêter au titre d'une série par exemple. Même si a la base tu as cliqué sur un épisode.

le code du player qui a été pris pour les commandes "play" dans le fichier que tu avais sont désuet aussi. A en voir le format, (priorité 500) - on voit que cest les vieux players utilisés pour les addons ExtendedInfo Mod, Meta, Metalliq, qui dans ce temps, appelaient également de vieilles versions d'API... (même dans ce temps ils déconseillaient d'utiliser l'étape du keyboard  dans nos player) 

Donc! (ouf méchant roman hein!!)

Ce fameux player "pastebin" est basé sur un vieux code  qui fonctionnait avec d'anciens addons qui appelaient d'anciennes versions d''API TMDb et qui semble être conçu pour reconnaître  un ancien  type de classification d'addon  "zonal" qui n'a plus lieu d'être.

Bref, faut se compter chanceux si il fonctionne bien de temps en temps. 

La morale de mon long et ennuyeux discours décousu: 

Prendre le player vStream qui lui utilise la recherche globale qui elle se chargera toujours de scruter les sources de la bonne façon :p et surtout: pas d'étape "keyboard" qui est buggy!

**Comment by benking110181** [comment]
ht                
tps://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

**Comment by toadnam** [comment]
> je n'avais pas pris connaissance des dernières discussions.
> 
> En fait, les players fonctionnants avec vStream ne fonctionnent pas bien avec la commande "play".
> 
> A cause de la particularité de vStream qui récupère des liens streaming dans des dossiers. La commande "play" va fonctionner avec des addons comme seren , exemple, qui eux offrent des liens selon la configuration que nous avons déjà fait via l'addon. (ex: nos préférences de liens de lien premium "Real-debrid", de qualité, des liens magnets, etc..) le "play" doit choisir le lien qui répond aux critères établis d'avance. vStream ne nous permet pas de configurer nos choix quant a lui.
> 
> Avec vStream, (le player que tu utilisais pastebin) faut passer par l'étape "keyboard" et cette façon apporte toujours des problèmes et bugs... Le keybord a souvent des fonctionnalités qui sont intégrées au skin utilisé, parfois autocompletition, etc... donc: le "play" est a éviter .
> 
> Il faut privilégier avec vStream un player basé sur "search" qui lui, bien qu'il soit moins précis, n'apportera pas de bug et selon les sources choisies dans vStream, basera sa recherche sur celles-ci.
> 
> Si tes sources ont bien identifié ce qu'est une Série et ce qu'est un Film, tu trouveras ce que tu cherche mais il te faudra plus de "clics" - ta recherche va s'arrêter au titre d'une série par exemple. Même si a la base tu as cliqué sur un épisode.
> 
> le code du player qui a été pris pour les commandes "play" dans le fichier que tu avais sont désuet aussi. A en voir le format, (priorité 500) - on voit que cest les vieux players utilisés pour les addons ExtendedInfo Mod, Meta, Metalliq, qui dans ce temps, appelaient également de vieilles versions d'API... (même dans ce temps ils déconseillaient d'utiliser l'étape du keyboard dans nos player)
> 
> Donc! (ouf méchant roman hein!!)
> 
> Ce fameux player "pastebin" est basé sur un vieux code qui fonctionnait avec d'anciens addons qui appelaient d'anciennes versions d''API TMDb et qui semble être conçu pour reconnaître un ancien type de classification d'addon "zonal" qui n'a plus lieu d'être.
> 
> Bref, faut se compter chanceux si il fonctionne bien de temps en temps.
> 
> La morale de mon long et ennuyeux discours décousu:
> 
> Prendre le player vStream qui lui utilise la recherche globale qui elle se chargera toujours de scruter les sources de la bonne façon :p et surtout: pas d'étape "keyboard" qui est buggy!
> Et si tu veux seulement rechercher dans pastebin, alors sélectionne seulement cette source dans les paramètres de vstream

Merci pour toutes ces précisions ! je comprends mieux tout ceci :)


> ht
> tps://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

merci pour le wiki ;-)

**Comment by Louis-Petit** [comment]
Pour suivre car j'ai a peu près la même galère
