### ISSUE TITLE
Evolution esthétique de vstream avec le passage a kodi matrix ?

### ISSUE THREAD

**Issue by benking110181** [Kodi-vStream/venom-xbmc-addons#3079]
Le logo et le fan-art date un peu de kodi 16 ou non pas beaucoup changés serait il possible de les remettre au gout du jour ?
Le passage a kodi matrix et surtout une evolution esthétique ( a ce que j'ai compris )  transparence etc. et python 3...
Vstream va t'il avoir droit à c'est memes évolutions est en profiter pour revoir l'esthétisme  entier de l'addon ?

**Comment by Louis-Petit** [comment]
J'avais déjà posté la même chose que toi dans la boîte à idées... en effet ça serait sympa 😊

**Comment by TmpName** [comment]
quelqu'un a essayé ^^ https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2783

**Comment by benking110181** [comment]
Pourquoi pas des fanart pour les sites, mettre les icon fanart etc dans un dossier extra comme les autre addon 
changer la couleur corail dans les titres entre parenthèse ou enlever. 
Plus de transparence dans les boutons, 
avoir affiche de film toujours présente jusqu'au choix du lien dans toutes les sources , épisodes pareil
avoir les infos de tmdb dans dans toutes les sources, les notations etc pour ce qui on des compte trakt en plus d'améliorer la fenêtre d'information... Si possible bien sur

**Comment by benking110181** [comment]
Avoir les mêmes catégories dans toutes les sources : recherche/films/series/animes/autres
Et des sous dossier avec films derniers ajouts, films qualité,  (films par acteur depuis tmdb)...
Ça faciliterait la création de widget et raccourci

**Comment by benking110181** [comment]
Avoir la fenetre d'information kodi quand on tape i sur kodi pc sur les widgets vstream

**Comment by alKODIque** [comment]
@benking110181 
Les informations ne pourront jamais être lrs memes dans toutes les sources: vstream est en quelque sorte un "scraper " alors il affiche ce qu'il y a comme info sur chacune des sources qu'il "scrape".

**Comment by benking110181** [comment]
Impossible n'est pas français ...

**Comment by alKODIque** [comment]
@benking110181 
Alors dans ce cas: vas-y et lance toi!! hihi

**Comment by benking110181** [comment]
D'autres addon le font deja, il affiche en premier les catégories tmdb, movie/tvshow.. puis popular genre etc   puis le film avec les informations de tmdb et ensuite te propose tous les liens disponibles pour le film

**Comment by sizanic** [comment]
> Avoir la fenetre d'information kodi quand on tape i sur kodi pc sur les widgets vstream

J'ai ajouté la fenêtre d'information accessible depuis les widgets, je vais voir si on peut associer un raccourci.

**Comment by alKODIque** [comment]
> D'autres addon le font deja, il affiche en premier les catégories tmdb, movie/tvshow.. puis popular genre etc puis le film avec les informations de tmdb et ensuite te propose tous les liens disponibles pour le film dans toutes les sources trier par qualité ou par source

oui @benking110181 tu as raison pour les autres addons... et je voulais dire l'affichage des informations uniformes à l'intérieur de chacune des sources car c'est ce que j'avais compris que tu demandais. Par contre, vStream offre déjà cette option non? le regroupement d'informations via TMDb?

**Comment by benking110181** [comment]
Prenons l'exemple de l'addon venom ou fe il te propose plus d'informations sur le films la durée certification...de TMDB, notations si trakt omdb ...  le premier menu ressemble à vstream film séries etc sauf que c est la façon d'afficher les informations et aussi les liens au final qui sont pas les mêmes puisque qu'il scrap toutes les sources une fois le film choisi

**Comment by benking110181** [comment]
Certain on meme des addon en dépendance donc pas obligatoire a installer si tu veut associer tes comptes tmdb trakt ...
Ou scrapper pour avec hoster et torrent

**Comment by benking110181** [comment]
Donc u2p pourrais être ce nouveau scraper si il scrap toutes les sources vstream ou que les nouvelles sources , 
pour regrouper tous les liens possibles pour un film  et vstream scrap tmdb pour les infos comme le fait kodi a l'origine avec tes fichiers locaux avec le scrapper tmdb incorporé  et rassemble les deux

**Comment by benking110181** [comment]
Ou avoir la possibilité d'intégrer une source vstream a ca bibliothèque kodi comme ça c est lui qui fait tout

**Comment by sizanic** [comment]
> > Avoir la fenetre d'information kodi quand on tape i sur kodi pc sur les widgets vstream
> 
> J'ai ajouté la fenêtre d'information accessible depuis les widgets, je vais voir si on peut associer un raccourci.

J'avais mal lu, je pensais que c'était la fenêtre d'information de vStream que tu voulais depuis les widget.

Mais en effet, c'est déjà bien celle de KODI qui s'ouvre sur le raccourci des vignettes (hors widget de l'accueil).


J'ai regardé pour essayer d'ouvrir la fenetre de vStream, mais pour les raccourcis, les seules actions possibles sont celle de KODI, parmi cette liste : 
https://kodi.wiki/view/Action_IDs


Alors j'ai quand même essayé d'ouvrir la fenetre d'info de KODI par cette méthode :

On associe l'action choisie avec une touche grâce à cette méthode : 
https://kodi.wiki/view/Keymap

Dans un fichier nommé "keymaps.xml" et déposé dans le dossier userdata.
Sous Windows, c'est ici : 
C:\Users\MyName\AppData\Roaming\Kodi\userdata\keymaps\keymaps.xml

Contenu du fichier : 

```
<keymap>
  <global>
    <keyboard>
	  <i>Info</i>
    </keyboard>
  </global>
</keymap>
```

Mais ça n'a rien donné, il manque peut-être quelque chose.
Dans tous les cas, pour ouvrir la fenetre d'info de kodi, c'est du parametrage KODI.
