### ISSUE TITLE
Source Pastebin - Pagination

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3082]
Bonjour :)
J'ai remarqué depuis peu, que la dernière page contenant des médias dans la source Pastebin offre quand-même la possibilité de passer à une page suivante. Est-ce que c'est normal ou bien est-il possible de retirer la flèche blanche qui mène vers une page vide ?

Pour mieux comprendre, voici un exemple de ce que je veux dire ici:  http://u.pc.cd/MtiitalK

Mon installation: 
Kodi 18.8
vStream 0.8.1 (dernière bêta installée depuis quelques heures)
Nvidia Shiel (Android)

**Comment by sizanic** [comment]
ça ne se reproduit plus sur cette même liste mais c'est parce que tu as ajouté un film, il y donc bien un film sur la page 2 maintenant 😄 
Et la deuxième page est bien la dernière sans possibilité de passer sur une suivante.


Mais avant tu avais juste 20 films et la pagination est réglée sur 20.

Il semble donc que la possibilité de passer à la page suivante s'affiche par erreur seulement lorsque la dernière page contient exactement 20 films !

On va regarder ...

**Comment by milkibreizh** [comment]
cela doit être la
 if nbItem % (ITEM_PAR_PAGE **+1** ) == 0:
                numPage += 1

**Comment by sizanic** [comment]
Je vais tester ça...

**Comment by milkibreizh** [comment]
@sizanic 
j’espère que c'est ici le pb car j'ai pas testé :worried:
mais si item =21 avec max 20 on passe a la page suivante avec la formule

**Comment by sizanic** [comment]
Tant fais pas je testerai avant.

Surtout que je ne pense pas que ça suffise.
Tu as juste passé la limite à 21, donc si on tombe sur 21 films, c'est le même problème.

J'utilise MODULO donc dès que je suis sur un multiple de 20, je mets un bouton "Suivant".
Mais si j'ai juste 20 il ne faut pas.
Donc il faut ajouter un code pour savoir si on est pas au bout.

**Comment by milkibreizh** [comment]
je m'en fait pas j'ai laissé tombe mais en effet j'avais finit par un truc du genre
if nbItem % ITEM_PAR_PAGE == 0 and numPage*ITEM_PAR_PAGE < len(movies):
c'est que je suis en train de regarder une serie sur vstream pour tester...
et je regarde si la série de ne s'arretes pas en cour de diffusion...je suis obligé de regardé toute la série
et c'est long comme teste;^^

**Comment by alKODIque** [comment]
@milkibreizh 
J'espère que tu as choisi une bonne série dans ce cas 😂😝

**Comment by milkibreizh** [comment]
@alKODIque 

> J'espère que tu as choisi une bonne série dans ce cas

j'ai viens de finir la série de bug
et maintenant j'entame la série de bugs mais il y a plus d'épisodes...😝

@sizanic 
cela semble marcher
`if nbItem % ITEM_PAR_PAGE == 0 and numPage*ITEM_PAR_PAGE < len(movies):`

ou...len(listReal),len(listActeur)...

**Comment by sizanic** [comment]
ça c'est bien !
Et j'y ai vraiment cru ! 😄 
Puis j'ai testé et ça ne fonctionne pas 😞 

Mais je vais laisser quand même ton code qui règle certains cas, mais pas tous.

**_Qu'est ce qui ne fonctionne pas :_** 
Par exemple, je suis dans la liste de l'année 2005.
Ma pagination est réglé sur 15 (pour rappel, elle est réglable mais je laisse par défaut).
Et il y a 15 films justement dans mon pastebin qui sont de 2005.

Alors le code recherche les films et trouve les 15.
Mais le 15eme n'est pas le dernier film de mon pastebin !
Donc le code n'est pas arrivé à `len(movies)` et l'action "Suivant>>" est proposée.
En cherchant les suivants, on parcours la fin du fichier pastebin et finalement on ne trouvera plus de films de 2005.

=> Il était impossible de savoir que dans le reste du fichier il n'y avait pas de film correspondant aux critères de recherche.

Ce critère de filtre peut être l'année, la saga, le réalisateur, l'acteur, une liste perso, etc, etc,
-> Soit l'ensemble des menus disponibles en fait !

Donc à moins que le dernier film dans le pastebin soit également le dernier film correspondant au filtre en cours, on ne peut pas savoir s'il faut afficher ou pas le bouton "Suivant".

Il n'y a pas de solution.

Mais il faut aussi relativiser en se rappelant que le problème n'apparait que lorsque le nombre de films correspondant au filtre est un multiple de la pagination !
Ce n'est donc pas systèmatique.
Et ce n'est pas très gênant.

**Comment by milkibreizh** [comment]
@sizanic 
Et j'y ai vraiment cru ! aussi 😄 😄
et donc quand on arrive nbItem % ITEM_PAR_PAGE == 0 il est impossible de prévoir,dans certains cas, la suite a moins
d'avoir fait une analyse complète ou une pré recherche avant (et donc longue et presque inutile) si je comprend bien...

> Mais il faut aussi relativiser

je sait bien que c'est pas grave mais c'était plus pour le fun et un peu mieux comprendre ton code ^^

**Comment by sizanic** [comment]
t'as tout compris et bien résumé, on ne va pas faire cette pré-recherche.

@alKODIque 
comme tu as ouvert ce sujet, est-ce que ça te va comme réponse ?

**Comment by alKODIque** [comment]
@sizanic bien entendu. c'est pas grave dutout, faut tomber dessus par pur hasard et ça arrivera pas souvent 

De plus, vous m'avez évité un aller-retour à la bibliothèque: J'ai plein de lecture juste ici dans cette issue 😄😜

**Comment by sizanic** [comment]
Par contre la modif fonctionne bien pour réalisateurs, acteurs et liste des sagas.
Car le nombre d'éléments est établie à l'avance.
