### ISSUE TITLE
Zt ne fonctionne pas

### ISSUE THREAD

**Issue by freddykrueger59** [Kodi-vStream/venom-xbmc-addons#3084]
Bonjour a tous 
J'aimerais savoir si zt fonctionne pour vous ? Chez moi là recherche fonctionne j'ai bien les résultats mais aucune réaction quand je clique sur un lien.
Quelle est la source pour vous qui égale Zt ? 
Merci pour votre aide et tout le travail que vous faites

**Comment by thorsten68** [comment]
Hello freddy. Je suis dans le même cas que toi sur Android. J'ai tout essayé, testé différentes versions, et je galère également avec d'autres sources (tirexo, time2watch)
J'essaie tout seul parce que j'ai pas envie de faire la pleureuse ici à chaque fois, mais là j'arrive à rien.
Je colle mon log si ça peut servir (regarder tout en bas avec le film radioactive) si ça peut aider. 
Quand j' arrive sur un lien 1fichier ça fonctionne, mais la plupart du temps les recherches fonctionnent mais je n'arrive pas jusqu'au bout, sur le dernier lien à cliquer. 
Si quelqu'un peut jeter un œil ça serait top. 
Merci d'avance 
https://slexy.org/view/s21hlO1j7U

**Comment by thorsten68** [comment]
J'ai testé la bêta et même ludopotte et je suis revenu à la 0.7.9 pour voir, après avoir tout supprimé. Rien n'y fait

**Comment by pics76** [comment]
J'ai réussi à bidouiller le code pour que ça fonctionne. C'est de la bricole mais le résultat est là !

Les pros feront certainement une écriture plus propre.

Dans le fichier zone_telechargement_ws 

Ajouter     
    sUrl = sUrl.replace('wwvw.zone-annuaire.com', 'www.zt-za.com')
juste après 
   sUrl = oInputParameterHandler.getValue('siteUrl')
    
Mettre en commentaire ce bout de code : 

    #Dl Protect present aussi a cette étape.
    #oParser = cParser()
    #sPattern = '<form action="(.+?)".+?type="hidden" name="_token" value="(.+?)">'
    #result = oParser.parse(sHtmlContent, sPattern)

    #if (result[0]):
    #    RestUrl = str(result[1][0][0])
    #    token = str(result[1][0][1])

    #cookies = GestionCookie().Readcookie(RestUrl.split('/')[2])
    #oRequestHandler = cRequestHandler(RestUrl)
    #oRequestHandler.addHeaderEntry('User-Agent', UA)
    #oRequestHandler.addHeaderEntry('Accept-Encoding', 'gzip, deflate')
    #oRequestHandler.addHeaderEntry('Cookie', cookies)
    #oRequestHandler.addHeaderEntry('Referer', RestUrl)
    #oRequestHandler.addParameters('_token', token)
    #sHtmlContent = oRequestHandler.request()

**Comment by Arias800** [comment]
Je suis en train de réécrire le code de protection, car c'était de la bidouille.

**Comment by freddykrueger59** [comment]
Merci j'ai hâte que cela refonctionne . Pourras tu me dire quand celà sera le cas et que dois je faire . merci

**Comment by Arias800** [comment]
J'ai mis dans la bêta une version deja bien plus stable que la précédente, même si il reste surement des ajustements a faire.

**Comment by thorsten68** [comment]
Je vais essayer ça. Merci beaucoup pour le boulot et la réactivité

**Comment by thorsten68** [comment]
Mon log t'as aidé du coup arias ?

**Comment by Arias800** [comment]
En partie, de toute façon j'avais deja prévu de réécrire le code.

**Comment by freddykrueger59** [comment]
Je viens d'essayer la bêta et ça ne fonctionne pas chez moi . Je parle de zt et tirexo

**Comment by Arias800** [comment]
Je parle que de ZT, Tirexo lui est protégé par recaptcha donc je peux rien faire.
Je viens de refaire une correction, essaye avec la beta pour voir.

**Comment by freddykrueger59** [comment]
A priori ça fonctionne . Je viens de tester sur mon téléphone . Je fais plus de test après le taf .merci beaucoup

**Comment by thorsten68** [comment]
Pour moi ça n'a pas changé. J'ai installé la bêta après les modifications d'arias mais pas de changements 😢
https://slexy.org/raw/s2IeIQgxyy

**Comment by milkibreizh** [comment]
@thorsten68 
Zone-Telechargement[
c'est pas perdu !!! car ton fichier log indique que ton fichier téléchargement_ws.py  date du Commits on Jul 15, 2020 par rapport aux erreurs ce n'est pas la  version de la bêta..donc le souci ne vient que de l'installation,

**Comment by milkibreizh** [comment]
@thorsten68
exemple de problème d'installation résolu
#https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3058#issuecomment-702302091

**Comment by pics76** [comment]
le problème est résolu en revanche seule une seule qualité de flux est proposée (ZT)

**Comment by Arias800** [comment]
Oui je sais, il faut que je corrigé ça.

**Comment by Arias800** [comment]
@pics76 C'est corrigé dans la bêta.

**Comment by pics76** [comment]
impeccable de mon côté. Merci !

**Comment by thorsten68** [comment]
OK merci je vais tester ça

**Comment by thorsten68** [comment]
J'y arrive toujours pas. Pourtant j'ai tout desinstallé, y compris kodi et réinstallé avec la dernière version bêta.
Toujours le même soucis. Il cherche un fichier qui n'est pas au bon endroit ?
https://slexy.org/raw/s2VSqYe9VQ

**Comment by milkibreizh** [comment]
@thorsten68 

> j'ai tout desinstallé,

c'est toi qui à désinstallé manuellement  en supprimant le dossier plugin.video.vstream  ou c'est le logiciel ?
car dans ton log tu n'as pas le chargement des fichiers pastebin voirhd filmstoon et tu ne devrait pas avoir le fichier tfarjo.py
cela ressemble encore a la version  du commit Commits on Jul 15, 2020

**Comment by thorsten68** [comment]
J'ai supprimé dans un premier temps le dossier Plugin.video.vsteam que j'ai trouvé en suivant ceci : Gestionnaire de fichiers
Dossiers du profil
Addon_data
Plugin vidéo vstream
Puis réinstallé la bêta à partir du zip mais ça a rien changé. 
Du coup a force de bidouiller dans tous les sens je me suis dit je savate tout et je réinstalle tout. 
Mais la non plus ça l'a pas fait 😔🪓

**Comment by milkibreizh** [comment]
@thorsten68
c'est pas celui ci tu a deux dossiers plugin.video.vstream

celui qui contient la mise ajour et qui pose problème
Android/data/org.xbmc.kodi/file/.kodi/addons/_**plugin.video.vstream**_

celui qui un gère l'addon
Android/data//org.xbmc.kodi/file/.kodi/user?/..../addon_data/plugin.video.vstream (je sais pas trop j'ai pas android)

un fois que le dossier _**plugin.video.vstream**_  sera mis à jour/remplacé cela le fera
autrement .... ça c'est plus pratique je trouve personnellement  :iphone:   :pick:

**Comment by pics76** [comment]
Il y a un problème sur ZT pour récupérer tous les épisodes d'une série. Seul le premier est accessible.

**Comment by Arias800** [comment]
Bon j'ai de nouveau corrigé le site, mais c'est devenu un purge a utilisé par exemple il faut cliquer plusieurs fois sur les mêmes qualités pour les validés (c'est comme ca que fonctionne le site maintenant).
