### ISSUE TITLE
Nouvelles Sources vStream

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3085]
J'ai trouver 2 Nouvelles Sources intéressantes de Streaming nommés 
"DP Stream HD" disponible au htt ps://serie.dpstreamhd.com/
et Cinemey disponible au ht tps://cinemey.com/

Est-ce possible de les avoir dans vStream s'il vous plait ?
Cordialement,
Ludo Potte

**Comment by alKODIque** [comment]
Cinemey est vraiment bien!

Via mon iPhone, je suis allé sur le site et j'ai cliqué par hasard sur une film. Il a débuté sans que j'aille a passer et éviter de la pub ou lien demandant de s'abonner à un truc louche. C'est rare!

Est-ce nouveau ce site? 
A ne pas confondre avec le "Cinemay" que nous connaissons, c'est bien "Cinemey"

**Comment by milkibreizh** [comment]
@ludopotte 
j'ai déjà fait les sources
h___ttps://filmz-streaming.com/
h___ttps://serie.dpstreamhd.com/

c'est les mêmes site ya juste 2 trois bricoles à peine a changer au niveau du code
elle fournissent les même sources 
mais de mon avis le site https://filmz-streaming.com/ me semble
plus fiable après si tu veux absolument serie.dpstreamhd c'est pas grave

pour ht tps://cinemey.com/
à priori 4 requêtes avec captcha pour arriver au host  ca doit pas être un truc pour moi  :confused:

**Comment by yodidon** [comment]
Cinemey il me semble que nous l’avions s déjà traité non ?

**Comment by milkibreizh** [comment]
Cinemay

**Comment by yodidon** [comment]
Cinemey et pas retenu pour je sais plus quoi mais à vérifier

**Comment by milkibreizh** [comment]
@yodidon 
Cinemey
ca a l'air d'etre le bordel au niveau du host avec l'api catcha de google..moi je tente même pas

**Comment by yodidon** [comment]
@milkibreizh oui je regarde la j’ai retrouver le vieux code déjà fait et c’est le bazar pas sûr que ce soit jouable.... et j’avoue être super soûler d’avoir supprimer le fichier final de 4kst-reamz....

**Comment by ludopotte** [comment]
@milkibreizh Oui j'aimerais bien avoir les 2 Sources dans vStream si c'est possible.

**Comment by TmpName** [comment]
Cenemay je confirme, si je bloque google, le site ne marche pas, a eviter.

**Comment by milkibreizh** [comment]
@ludopotte 
bah on va voir pour les deux 
j'avais zappé que h___ttps://fil_mz- n'avait pas de série
mais il faudra attendre car je crois qu'il y a du ménage a faire au niveau du dev
avant de mettre de nouvelle source je vais les garder bien au chaud en attendant^^
@yodidon 

> et j’avoue être super soûler d’avoir supprimer le fichier final de 4kst-reamz

crois en mon expérience boire et te souler ne changeras rien aux problèmes  :smile:

**Comment by yodidon** [comment]
Trop tard @milkibreizh ...
![Uploading image.jpg…]()

**Comment by milkibreizh** [comment]
@yodidon 
ton image fait 4 GO j'vois rien
<img width="212" alt="Captureyodi" src="https://user-images.githubusercontent.com/65681507/96349338-4487be00-10af-11eb-824e-a213c87960bb.PNG">

**Comment by yodidon** [comment]
![E0502AF8-ACF7-472F-ACA2-1AAC1217F3D4](https://user-images.githubusercontent.com/39896943/96349453-1ce52580-10b0-11eb-872d-cadcf74e8d98.jpeg)

**Comment by milkibreizh** [comment]
10 GO !!!!!!!!!! ton image
mais ou sont les bouteilles vides ? 😄

**Comment by yodidon** [comment]
![image](https://user-images.githubusercontent.com/39896943/96349571-c7f5df00-10b0-11eb-8f36-84b697215d1d.jpg)

**Comment by milkibreizh** [comment]
c'est de la grenadine

**Comment by yodidon** [comment]
Oui mais pour les grands enfants ...😜

**Comment by TmpName** [comment]
C'est bien avec le flou, on a l'impression d avoir bu aussi.

**Comment by milkibreizh** [comment]
> Cinemey et pas retenu pour je sais plus quoi mais à vérifier

h__ttps://ci__nemey.com/
mais on c'est affolé pour rien ,je viens de finir presque la source le captacha...
c'est seulement pour ceux qui essaye d' appuyer sur le bouton :grin:

et le hazard fait aussi que cette source se faite comme
h___ttps://fil_mz-streaming.com/
h___ttps://se_rie.dpstreamhd.com/
et donc j'en est aussi profité pour faire aussi
h__ttps://dpstream.ch/
il on tous les 4 des similarités frappantes quasiment mêmes films
des la première page,et mème pour le code c'est les mème signatures 
sauf qu'il faut se retaper tous les patterns à chaque fois 
pour chaque site :confused:

**Comment by Bilal54** [comment]
Bonjour,
Pour les animés il y a un excellent site : https://www.animecomplet.org/derniers-episodes/
Depuis des années aucun problème, contenu très conséquent avec une très grande réactivité pour l'ajout des nouveaux épisodes etc...
Je ne sais pas si c'est possible d'ajouter ce site mais si oui ce serait vraiment le top du top pour les animés <3

**Comment by milkibreizh** [comment]
@Bilal54 
Dare mo kono shigoto o shitakunai nonara ,watashi ga yarimasu :expressionless:

**Comment by milkibreizh** [comment]
Owarimashita  😑

**Comment by teclis33** [comment]
Otakufr etant très difficile d'accès, serait il possible d'ajouter vostfree.com dans la section manga ?

**Comment by milkibreizh** [comment]
@teclis33 
ce site propose t'il des videos pour tout publique ?
j'ai un peu doute car j'ai suis tomber sur  une (seule )video du genre pour publique de 16 ans
..c'est pas méchant mais faut penser au jeune publique 
 je ne connais pas assez les mangas et je peux pas contrôler toutes les videos du site
et en cas de doute je peux seulement te proposer la source ,si je la fais, dans un fichier
si j'avais la liste des séries il me suffirait de filtrer,mais il n'y a aucune info sur le site
pour le faire

**Comment by ludopotte** [comment]
Je viens de trouver un Site intéressant de Streaming nommé "Ciné974" qui serait possible d'avoir dans vStream au https://www.cine974.com/streaming/

**Comment by milkibreizh** [comment]
c'est pas plutôt un site d'information car j'ai pas vu de liens pour des vidéos complètes 
et les quelques liens pour les vidéos complètes amène à un site ou il faut s'inscrire
j'ai loupé qqle chose ?

**Comment by ludopotte** [comment]
Oui tu as rien loupé milkibreizh mais y'a des Vidéos directement depuis YouTube.

**Comment by teclis33** [comment]
> @teclis33
> ce site propose t'il des videos pour tout publique ?
> j'ai un peu doute car j'ai suis tomber sur une (seule )video du genre pour publique de 16 ans
> ..c'est pas méchant mais faut penser au jeune publique
> je ne connais pas assez les mangas et je peux pas contrôler toutes les videos du site
> et en cas de doute je peux seulement te proposer la source ,si je la fais, dans un fichier
> si j'avais la liste des séries il me suffirait de filtrer,mais il n'y a aucune info sur le site
> pour le faire

Je ne suis jamais tombé sur une vidéo hentai ou autre, le site référence exactement les mêmes manga que otakufr, cela m'étonne ... Pourrais tu me dire sur quelle vidéo tu es tombé que je vérifie.

**Comment by sizanic** [comment]
pour des nouvelles sources asiatiques, on retrouve dans ce sujet #2547 où @Makoto83 avait proposé deux sources déjà fonctionnelles.

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2547#issuecomment-498057831

Normalement elles le sont toujours.

Sky-Animes.com (code de la source : https://pastebin.com/H76XZ5Le)
Anime-Ultime.net (code de la source : https://pastebin.com/YFANy9pD)

Il faudrait terminer le travail d'intégration dans vStream.

**Comment by milkibreizh** [comment]
@ludopotte 
bah si j'ai loupé qqle chose c'est un site d'information spécifique destiné aux films présents dans les cinémas 
de l'ile de la réunion après je n'ai rien contre la réunion,au contraire j'aurais bien voulu passer qqles vacances là bas 
mais si le source doit être faite, je pense quelle le sera en ne prenant  que les infos générales 
car si on mets par exemple Le programme, et les infos du Cinéma Royal à St Joseph de l' île de La Réunion
il risque d'y avoir des jaloux..mais si tu habites la bas exceptionnellement  je la ferais complètement mais tu devras m'inviter
tout un week chez toi pour que je vérifie si les horaires d'ouverture sont bien respectés^^

pour ht tps://filmgratuit.eu/ c'est un site qui n'est plus mis a jours et ya 3 series et 150 films
je te remercie de fournir des liens mais la je vois pas l'utilité...j'ai loupé qqle chose^^ ?

@teclis33 
> Pourrais` tu me dire sur quelle vidéo tu es tombé que je vérifie

je ne l'ai pas retrouvée si cela se trouve c’était la seule...car j'en ai pas vu d'autres 
après il n'y a  pas de scène obscène mais on voit une fille nue qui sort de sont de son lit,
rien de plus ,mais c'est suffisant pour que des parents estiment que leur enfants 
ne voient pas voir le truc autrement si c'est validé par les développeurs de vtream elle sera faite.

**Comment by Arias800** [comment]
J'ai déjà regarder du contenu sur cette source et je ne suis jamais tomber sur du contenu hentai (et normalement il ne devrait pas en avoir car c'est en règle générale sur des sites spécialisés).

**Comment by milkibreizh** [comment]
bon bah ok c'est validé ...si cela se trouve c'etait juste une fille habillée qui était déguisée en nue

**Comment by yodidon** [comment]
> pour des nouvelles sources asiatiques, on retrouve dans ce sujet #2547 où @Makoto83 avait proposé deux sources déjà fonctionnelles.
> 
> [#2547 (comment)](https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2547#issuecomment-498057831)
> 
> Normalement elles le sont toujours.
> 
> Sky-Animes.com (code de la source : https://pastebin.com/H76XZ5Le)
> Anime-Ultime.net (code de la source : https://pastebin.com/YFANy9pD)
> 
> Il faudrait terminer le travail d'intégration dans vStream.
@sizanic
Tu veux que l’on avance sur ces codes ?
Je veux bien en prendre au moins 1

**Comment by Makoto83** [comment]
Faites vous plaisir ;) ça fait plus d'un ans déjà mais je pense qu'il y a certainement la possibilité d'améliorer un peu le code :D

**Comment by TmpName** [comment]
Pour info du hentai on en trouve sur adkami ^^.

**Comment by Arias800** [comment]
Pour adkami ils préviennent avec un message, par contre sur Ianime il n'y a effectivement pas de message.
Mais c'est récent comme ajout, car jusqu'a maintenant il n'y en avait pas et ils évitaient de mélanger les sites xD

**Comment by sizanic** [comment]
Personne pour tester les deux sources d'animes que j'ai donnés ? 🤔

**Comment by yodidon** [comment]
@sizanic  comme je te le disais, je veux bien m’y mettre

**Comment by Che-debarras** [comment]
> Personne pour tester les deux sources d'animes que j'ai donnés ? 🤔

Si j'ai testé mais les dossiers des catégories ne S'ouvrent pas donc pas accès au lien 
C'est des sources de mangas donc ne pas oubliés de désactiver ou caché les contenu adultes s'il y en a

**Comment by sizanic** [comment]
@yodidon 
J'avais pas vu ta réponse.
oui, il faudrait terminer le travail de @Makoto83 
(Le plus gros a l'air d'être fait)

@Makoto83 
Merci pour ton travail, je n'ai pas eu le temps de regarder alors je poste ici pour en appeler à la communauté de développeurs.

@Che-debarras 
en effet, il faut rappeler la consigne de la censure qu'on s'applique à mettre en œuvre pour vStream.

Je peux pas m'occuper directement de la source, mais je pourrais t'aider @yodidon

**Comment by milkibreizh** [comment]
@yodidon 
si tu veux finir les deux sources c'est ok ,car je dois  encore contrôler et finir aussi certaines  sources
mais si tu veux que j'en regarde une je peux toujours essayer devoir si je peux faire qqle chose.
ou sinon n’hésite pas à poser des questions,chacun essayeras de t'aider comme il le peut
nb: je ne sais toujours pas si tu veux faire la source 4_kstream

**Comment by Che-debarras** [comment]
Ya la source toonAnime que j'osais pas demandais car il utilise  sibnet et voila que le host vient d'être créer.
Je suis pas fan de manga mais pour ceux qui cherche de nouvelle source ca peut vous intéresser

**Comment by yodidon** [comment]
Bon j’ai commencé mais pas simple de savoir ce qui est acceptable ou pas il y a beaucoup de genre et je vais essayer de trier ce qui ne doit pas être référencé dans vstream

**Comment by milkibreizh** [comment]
@yodidon 
j'essaye aussi de faire pareils pour les mangas si il y a des genres  douteux je ne les mets pas, 
par contre pour filtrer une recherche de résultat tu ne peux pas toujours faire grand chose 
tu fait laquelle actuellement ?
nb: je ne sais toujours pas si tu veux faire la source 4_kstream...... :interrobang:

tooanime je l'avais déjà faite  en gros ,et elle contient encore des bugs .Pour choisir les hosts au 
niveau du code c'est un peu comme vost free mais étant un noob en programmation, le code que 
j’ai fais donne un foutu gros bazars sans nom et il faudrait peu être que qql'un d’autre la fasse pour ne pas  
se retrouver avec 2 sources complétements brouillonnes ou sinon j' essayerais d'arriver à la finir,  
dans le cas ou qlqu'un la demanderais

**Comment by yodidon** [comment]
Je fais Sky anime et pour 4_stream j’ai plus le code

**Comment by milkibreizh** [comment]
>  4_stream j’ai plus le code

tu l'as perdu avec le crash de ta machine ? 
oui mais c'est bete  c'est toi qui a choisi et commencer à la faire cette source sinon tu peux reprendre
le code que j'avais fait pour t'aider un peu, cela ne me dérange pas du tout

Sky anime,j'ai pas regardé cette  sources en details mais si tu a le moindre soucis n’hésite pas
 j'essayerais de prendre du temps pour t'aider et donc pour l'autres sources elle semble être ok  ?

**Comment by Che-debarras** [comment]
Question HS:
Qu en est il de Viki, il n'est pas sur vstream officiellement mais il ne fonctionne plus
Même l'addon Viki ne fonctionne plus depuis qu'on se rapproche de kodi 19,
De meme que filmtoon qui a changé de url  qui est .in et non .cam

**Comment by milkibreizh** [comment]
pour l'addon viki j'ai pas trop regardé mais  il est hs quelque soit la version de kodi
je ne pense pas avoir trop le temps pour l'instant de m'en occuper car c'est pas une source de vstream
,par contre à l’adresse  cam il y a  maintenant  filmstoon ,mais ce n'est pas seulement l'url qu'il faut changer
c'est tout le code de la source  qu'il faut refaire, le site n'est pas du tout codé de la même façon
 je ferais donc une mise à jour dès que possible

**Comment by yodidon** [comment]
> > 4_stream j’ai plus le code
> 
> tu l'as perdu avec le crash de ta machine ?
> oui mais c'est bete c'est toi qui a choisi et commencer à la faire cette source sinon tu peux reprendre
> le code que j'avais fait pour essayé de t'aider un peu, car ce jour la je crois que tu était fatigué..,
> cela ne me dérange pas du tout
> Sky anime,j'ai pas regardé cette sources en details mais si tu a le moindre soucis n’hésite pas
> j'essayerais de prendre du temps pour t'aider et donc pour l'autre source elle semble être ok ?

merci @milkibreizh  mais sur ce type de source je crois que je m'en sortirais .. bon j'avoue je suis pas au top mais bon j'arrive a faire 2,3 trucs

**Comment by Che-debarras** [comment]
> pour la source viki j'ai pas trop regardé mais elle est hs quelque soit la version de kodi

Pourtant elle fonctionnais bien en kodi 18.7 je pense,  meme l'addon Viki ne marche plus depuis 18.9 donc ya du avoir un changement sur kodi qui l'empêche de fonctionner
https://forum.kodi.tv/showthread.php?tid=148429&page=38 : forum qui en parle et jattend la reponse du dernier msg car un gars dis qu'il a resolu le souci.
Mais si tu y arrive il sera une source de Vstream ou il est pas accepté par l'équipe de vstream ? Car il a fonctionné pas mal de temps sur android avant kodi 18.9

**Comment by milkibreizh** [comment]
le vrai plugin viki plante parce qu'il n’existe plus de 360p et de 480p dans la requete des vidéos ,
et il force une requete 480p..la requete ne donne que du mdp mpeg dash et pour le lire ce fichier 
sur vstream il faut modifier l'host. viki.py et mettre la valeur `bsupportedMdp = True`

Mais de mon coté cela n'as jamais marché et je n'ai jamais réussi à savoir
comment lire ses fichiers sur kodi.A savoir pourquoi il n'existe plus les autres
formats  il faudra que je vois cela mais hélas j'ai pas trop de temps à consacrer
à mes sources je ne suis que sur les sources de vstream actuellement

intégré viki à vstream je sais pas trop ..faut voir la suite

**Comment by Che-debarras** [comment]
@milkibreizh 
Ok c'est dommage car viki est une excellente source pour les dramas
J'espère que ce sera inclus un jour ou que le vrai addon soit corrigé
Merci quand meme

**Comment by Arias800** [comment]
Le site Anime-Ultime a été ajouter, je peux m'occuper de skyanimes dans la foulé.

**Comment by yodidon** [comment]
Je l’ai ajouté il y a quelque jour mais peut-être n’est il pas bien ?

**Comment by Arias800** [comment]
Je n’avais pas vu que tu l'avais ajouté. Donc j'ai rien dit :p

**Comment by yodidon** [comment]
Pas de soucis mais il est peut-être pas optimisé, je m’efforce de comprendre les fonctionnements des animes et dérapas pour bien les répertorier mais je suis pas encore bien au faite...

**Comment by milkibreizh** [comment]
ceux qui raffole des animes sont gatés j'ai encore 3 sites à finir mais j'ai pas trop le temps de les fignoler hélas
car ya toujours un bins au dernier moments ou je les teste complétement.
sinon je vais faire peu être  les mettre comme même car elles sont fonctionnelles mais imparfaites..
car Autrement à ce rythme je risque de ne jamais les mettre
autrement pour les sources demandées par @ludopotte cinemay et serie.dpstreamhd.com
elles sont faite  mais j'ai l'impression qu'il n'y a plus de mise à jour sur les des deux sites depuis 2 semaines
(ceux qui confirment bien que c'était bien des clones ou qu'elle on été faite par les mêmes personne)
donc je pense pas qu'il faille les mettre j'en suis désolé@ludopotte ..mais je peux toujours la mettre 
en pastbin si quelqu'un veux vraiment le code..de plus sur les film récents il n'y as que de la VO sans sous titres
Après si les sites se réveillent je proposerais les sources

> je m’efforce de comprendre les fonctionnements des animes et des dramas pour bien les répertorier mais je suis pas encore bien au faite.

je ne suis donc pas le seul  :smile:

**Comment by milkibreizh** [comment]
@Arias800 
j'ai un problème avec la source Anime-Ultime cela est sans doute du
encore au decodage n'etant pas sous le systeme que toi je peux pas toucher la source
j'avais en faite aussi refait la source (mais j'arrive jamais a les finir)
maist je voulais ajouté quelques menus

moi j'ai laisse le systeme de l'ancienne source pour le décodage
même si cela  paraissait lourds cela marchait bien donc j'ai gardé le code
et je suis surtout pas un as de l'encodage décodage
 il faudrait le confirmer mais ta source  ne peu fonctionner qu'avec kodi 19
voila  ma source j'avais pas finit de le mettre à jour pour les menus dans home


https://pastebin.com/0Qn36t9z

**Comment by Arias800** [comment]
Alors je fais du tri dans le code, car beaucoup de choses ne servent à rien.
Par exemple faire de multiple variable pour la recherche ne sert à rien car tout est a regroupé dans URL_SEARCH_SERIES.
J'ai réglé le souci de l'encodage.
J'ai affiché la qualité du lien finale.
J'ai testé et garder tous tes ajouts (Genre, années).
https://github.com/Arias800/Fichier-divers/blob/master/anime_ultime.py

**Comment by milkibreizh** [comment]
oui merci d'avoir pris le temps de regarder ma source
 j'avais séparé les recherches animes,drama, toka..pour que les personnes
fasse une recherche spécifique car même si cela reste des series quand ils utilsent
le site directement c'est préférable de séparer les types c'est pour cela qu'il y avait d'autres variables
Apres sur la  recherche global  il faut mettre en effets tous les résultats dans URL_SEARCH_SERIES 
 j'ai pas l'intention de modifier ton pull c'était pour montrer l'ajout qui pouvait être fait 
pour les années et les genre et mon code de tout facon etait imparfait et était à  finir
..apres comme je le disais cela doit être un peu lourdingue de testé deux system à la fois
moi j'arrive déjà pas avec un seul

**Comment by Arias800** [comment]
C'est pas bien compliqué d'avoir les deux versions en parallèle, il faut juste que je n'oublie pas de changer le nom des dossiers. Sinon je ne fais qu'utiliser Kodi 19 qui fonctionne bien mieux que Kodi 18.

**Comment by Che-debarras** [comment]
Animeultime , fonctionne et bien que les hentais ont été supprimés,  il y a quand meme la catégorie et 1 hentai avec 1 épisodes qui na pas été retiré

**Comment by milkibreizh** [comment]
@Che-debarras 

> Sinon tu peux toujours faire french strm.lol ou hds.fm

c'est  mon avis mais dans hds.fm il y a bcp trop de liens qui n'aboutissent pas meme si les liens récents sont peu être bons
 je sais même pas si on arrive a 50% de bons liens quand on fait une recherche normale
hds_fm.py    
h_ttps://pastebin.com/VPfsWVWk

french_stream_lol.py  
h_ttps://pastebin.com/wyi78PFW

**Comment by Che-debarras** [comment]
Excellent @milkibreizh 

J'ai testé frnchstrm.lol, il semble marcher sauf concernant ces hosts:

1. Allvid ne se lance jamais  et Playzer  (ex broken heart gallery) qui est vide
2. Yen a un autre host qui est vide ex Stronger than world , il a pas de nom que des chiffres
3. Ya aussi le nom des hosts qui est ecrits avec des lettres ou chiffre en plus 
4. Dans series ya le dossier uqload des 1e episodes qui ne s'ouvre pas
5. Ya aussi une liste de recherche similaire avec les episodes qui peut etre très longue comme pour la serie "Des"
6. Des fois sur certains series (Surtout les series Asia)  il ne trouve aucun episode ex Private Lives 

Pour hds.fm 
Le contenu se présente pareil avec des recherches similaire et des résultats actuelles 
Donc je pense que les bugs de frnchstrm mentionné ci dessus doivent surement se retrouver sur hds.fm

Il y a au moins 3 a 5 host sur ce site : uqload, mystrm,uptobox,netu,vidlox
Netu marche jamais mais si @Arias800 y arrive cela fera sûrement 3/5 ok

Si tu dis que ya meme pas 50% qui marcheront c'est parce que tu es tombé sur les films dont le film a été retiré du host.
Dans tout les cas tu es sur d'avoir au moins 1 ou 2 qui fonctionne voir 3 car Vidlox met du temps a répondre.

Pour rappel hds.fm c'est Kaydo qui lui ne marche plus (a revérifier car il a changé d url, chez moi il marchait avant sa disparition) qui avait uniquement 1 seul lien et non jusqu'à 5 comme hds.fm

merci pour ces 2 sources surtout hds.fm car c'est du kaydo qui fonctionne sans meme changer dns ni de fichier m3u8 je ne sais quoi avec meme qualité de kaydo

**Comment by milkibreizh** [comment]
@Che-debarras 
oui il faut que  que  je revois cela j'ai fait les sources hiers et je sais qu'elles ne sont pas au point
mais je les ait mis en pastbin en attendant ,car je sais pas quand j'aurais du temps libre pour les continuer

**Comment by Che-debarras** [comment]
> @Che-debarras
> oui il faut que que je revois cela j'ai fait les sources hiers et je sais qu'elles ne sont pas au point
> mais je les ait mis en pastbin en attendant ,car je sais pas quand j'aurais du temps libre pour les continuer

Je ne cesserai de répéter qu'il y a aucun souci, pas d'urgence, Prend tout le temps que tu veux.
Tu peux m'envoyer tes pastebin ou .py sur discord comme ca je suis alerté et je testerais

**Comment by milkibreizh** [comment]
@Che-debarras 
ok pas de souci mais je mettrais les mises a jour ici ou direct dans vstream selon l’avancement....j'utilise pas discord

**Comment by milkibreizh** [comment]
@Che-debarras 
j'ai regardé pour les bugs alors je crois avoir trouvé le problème des chiffres bizarre
mais c'est pas sure que se soit résolus 
pour le hoster Allvid, celui ci ne peu pas se lancer car c'est un site non sécurisé
et Playzer c'est un host qui ne semble pas marcher ou qui parait tjrs sans lien

 et dans le cas que tu as cité pour les séries il n'y a pas de résultat car se sont
des hosts netu que jai filtré avant le résultats mais c'est fort possible qu'il y est des bugs comme même sur les séries
j'avais fait une inversion vost/ vf ds le resultat
j'ai fais un mise a jour partielle des fichiers sur pastbin

**Comment by TmpName** [comment]
>pour le hoster Allvid, celui ci ne peu pas se lancer car c'est un site non sécurisé

J'ai pas suivi ?

**Comment by milkibreizh** [comment]
ceci concerne la source  french-stream.lol
quand j'ai fait mes teste je suis tombé sur allvid et sur le navigateur j'avais site non sécurisé
mais je ne sais plus par contre si c’était une adresse ou un requete de la forme h_ttps://......com/allvid/newPlayer.php?id=

**Comment by Che-debarras** [comment]
@milkibreizh 
Ils seront inclus dans la beta prochainement?

**Comment by milkibreizh** [comment]
je les mettrais sans doute dans vstream après le prochain check up.

**Comment by TmpName** [comment]
>quand j'ai fait mes teste je suis tombé sur allvid et sur le navigateur j'avais site non sécurisé

Ca vient du navigateur ca. Tu aurais pas un film ou un site pour tester ?

**Comment by milkibreizh** [comment]
> Ca vient du navigateur ca.

non mais hiers j'ai retesté les liens que j'avais dans l’historique de mon navigateur
et allvideo n'est plus maintenant non securisé de toute façon je ne filtre pas allvideo
mais  je tombe toujours sur des liens videos vides

>  Tu aurais pas un film ou un site pour tester ?

lien vide bloquant
h___ttps://opsktp.com/allvid/newPlayer.php?id=d8217f9e-49d9-4111-9c6b-2cda49431e96

ces liens existent dans h___ttps://french-stream.lol/
c'est que tous les liens que j'ai trouvé sont morts et il s'agit de liens qui vont être utilisés
par l'host allow_redirects  hors il y a un souci dans cette hoster car quand il n'y a pas de lien
  **vstream se bloque parfois**
on constate que le résultat de la première requete de l'host allow_redirects  donne comme résultat
l'url de la requete
Donc n’étant pas sur de moi je suis obligé de checker toutes les urls qui vont dans l'hoster host allow_redirects 
en effectuant une première requete identique à celle de l'hoster 'host allow_redirects  et vérifier si le résultat de la requete
 est correct
```

        session = requests.Session()  
        resp = session.head(url, allow_redirects=True)
        sHosterUrl = resp.url

```
et si url = sHosterUrl je n’envoie  pas le lien dans l'hoster

je pourrais à la place résoudre complétement l'host mais le souci c'est que dans le  def checkHoster la condition 
des  liens mp4 sont mis à la fin ,et les hosts résolus donnent des liens qui vont être redirigés dans des hosters car ils contiennent le nom de l'host alors que les liens sont définitivement résolus...et cela plante

la solution de tout ce gros blabla serait de modifier l'host allow_redirects 
mais sur la condition url = resp.url = plantage 
je ne suis pas vraiment sur que se soit valide a 100% pour tous les cas

**Comment by TmpName** [comment]
Alors la j'ai pas tout suivi encore ^^

J'ai voulu tester ton lien, erreur 404, chez moi, le hoster allvid fonctionne ou pas sur Vstream ?
Oui, quand ca se bloque c'est souvent car Vstream telecharge la video de 800M au lieu de la page html de 200ko

>et les hosts résolus donnent des liens qui vont être redirigés dans des hosters car ils contiennent le nom de l'host alors que les liens sont définitivement résolus

La ce devrait pas

```
        # Recuperation du host
        try:
            sHostName = sHosterUrl.split('/')[2]
        except:
            sHostName = sHosterUrl
```

Du coup si tout vas bien ca regarderait "opsktp.com" pas "allvid"

- L'url est au depart h___ttps://opsktp.com/allvid/newPlayer.php?id=d8217f9e-49d9-4111-9c6b-2cda49431e96
- Elle est recoonue par "opsktp" comme "allow redirect"
- La personne clique dessus
- sHosterUrl donne soit une url a decoder, soit une url deja decodée, ca ne peut pas bloquer c'est juste une requete HEAD, ca recupere juste des infos.

Si c'est a decoder ca passe par le hoster "allvid" car l'url est du genre h_ttp:://allvid.com/video
Sinon par le lien direct car la video est du type h_ttp://video.mp4

C'est ou que ca deconne ?

**Comment by milkibreizh** [comment]
> La j'ai pas compris non plus, 

Sinon a trop parlé jai noyé l'essentiel car c'est bien ici qu'est l'essentiel
h_ttps://opsktp.com/allvid/newPlayer.php?id=d8217f9e-49d9-4111-9c6b-2cda49431e96 
bloque vstream et la roue tourne sans jamais s'arretter a moins d'un escape
et le lien en question donne sur le navigateur 404 not found
et on remarque que pour d'autres urls ou cela bloque et il n'y as pas de liens aussi valident
et on a toujours url = resp.url dans l'hoster allowredirect.py

...bon c'est vrai j'avoue il faut pas non plus que j'en fasse un fromage ^^

> mais tu peux changer.

La j'ai pas compris non plus, 

dialogue de sourd^^

**Comment by TmpName** [comment]
Ca y est je viens de comprendre ^^
En fait ca fait une boucle.

Donc oui je vois 2 solutions.
- La tienne` if url = sHosterUrl > return False`, ca voudrait dire que la redirection ne se fait pas
- Si trop agressif, au cas ou, mais je vois pas pkoi ta methode ne serait pas bonne, `if 'opsktp' in  sHosterUrl > return False`
