### ISSUE TITLE
Bug Dossier Zone Téléchargement (ZT)

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3089]
Bonsoir, tout d'abord merci pour cette nouvelle version de notre Addon favori qui permet enfin de pouvoir utiliser ZT sans captcha qui bloque mais je me suis rendu compte d'un souci; lors d'une recherche de série (exemple Evil S01) on trouve bien le dossier mais lorsque qu'on clique dessus, au lieu d'ouvrir les épisodes il ouvre l'épisode 1 et rien d'autre.
Pour ce qui est des films à priori ça fonctionne à merveille d'après ce que j'ai pu tester.

Merci encore pour votre super boulot.

**Votre system**
 - OS: [Android]
-  Appareil [X96 Max]
 - Version Kodi  [18.8]
- Version Vstream 0.8.2

**Comment by thorsten68** [comment]
Alelouia merci arias sur cette nouvelle version mon problème est réglé également. Plus de soucis sur zt.
Je t'aime❤️

**Comment by Niconimes** [comment]
> Alelouia merci arias sur cette nouvelle version mon problème est réglé également. Plus de soucis sur zt.
> Je t'aime❤️

Vu ta réaction, je suppose que tu n'as pas le même souci que moi au niveau de l'ouverture d'un dossier de série ?

**Comment by thorsten68** [comment]
J'ai pas essayé.

**Comment by Che-debarras** [comment]
D'après ce que j'ai remarqué il y a parfois 2 dossiers pour les series :
Un qui te permet de visionner ou télécharger chaque episode
Un autre qui te permet de télécharger toute la saison en 1 seul lien
Donc peut etre que celui que tu choisis est le dossier pour ddl la saison
Choisi l'autre dossier s'il existe
Sinon il se peut que seul l'épisode 1 existe surtout si nouvelle serie en VF .

**Comment by Arias800** [comment]
@Niconimes Ca a été corrigé dans la bêta par @milkibreizh .

**Comment by Niconimes** [comment]
> @Niconimes Ca a été corrigé dans la bêta par @milkibreizh .

Super merci Arias 👍

**Comment by Manucciu** [comment]
Bonjour,

Chez moi ça marchait plus ça ne marche plus ça refait comme avant, un seul fichier après la recherche on a plus tous les épisodes.

**Comment by Arias800** [comment]
Je viens d'essayer et ça fonctionne, peut être que c'était un problème temporaire.

**Comment by Manucciu** [comment]
Slt Arias800, alors essaye en recherchant la série "see" tu verras que ça marche pas, j'ai l'impression que ça marche sur résultats de la première page et pas celle d'après.

**Comment by milkibreizh** [comment]
oui exact le next page n'est pas utilisé normalement dans une recherche,c'est rectifié

**Comment by Manucciu** [comment]
je viens de test et ça marche !
merci milkibreizh
