### ISSUE TITLE
recherche ExtremeDown

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#3090]
Bonjour à tous,
C'est simple, la fonction recherche de ExtremeDown ne fonctionne pas, elle ne donne aucun résultat.
C'est possible de fixer ce problème ?

Merci à vous

**Comment by sizanic** [comment]
C'est en cours de correction.

**Comment by Che-debarras** [comment]
En attendant fais une recherche global sur l'ensemble des sources et tu verras que tu aura des resultats avec Xtrmdown

**Comment by lebigboss** [comment]
@sizanic  Merci 🤗🤗

@Che-debarras  Justement je fais que des recherches global, je comprends pas pourquoi moi j'ai rien alors

**Comment by sizanic** [comment]
C'est corrigé sur la beta.
Avec une amélioration, la possibilité de rechercher par type : Films/Séries/Animes/Autres.

**Comment by lebigboss** [comment]
Au top merci beaucoup @sizanic
