### ISSUE TITLE
Probleme URLResolver avec la dernière mise à jour

### ISSUE THREAD

**Issue by lil78711** [Kodi-vStream/venom-xbmc-addons#3091]
salut depuis la nouvelle mise a jour uptobox ne marche pas  probleme urlresolv j'ai beau remettre mes identifiant uptobox rien ne change  et c'est pas que uptobox meme d'autre  que dois je faire merci

**Comment by Louis-Petit** [comment]
Dans tes paramètres Vstream, assure toi d'être en "rester en direct uptobox"

**Comment by lil78711** [comment]
c'est fait mais c'est un problem urlresolv

**Comment by lil78711** [comment]
URL Resolver gros probleme suis je le seul

**Comment by lebigboss** [comment]
Vous êtes sur quel version de urlresolver ?

**Comment by ato18** [comment]
Bonjour, j'ai également le même problème depuis la maj

**Comment by Che-debarras** [comment]
Je confirme un seul lien apparaît pour chaque host dans ZT et pourtant j'ai aucun compte uptobox et rien rien changé dans les paramètres.
Seul le 1e épisode est affiché
