### ISSUE TITLE
pastebin

### ISSUE THREAD

**Issue by lil78711** [Kodi-vStream/venom-xbmc-addons#3092]
salut comment marche  pastebin j'ai beau mettre l'id mauvais format

**Comment by lebigboss** [comment]
Il faut d'abord mettre le nom du dossier et ensuite tu ajoutes le code PasteBin, c'est à dire enlevé l'URL

**Comment by sizanic** [comment]
L'erreur "mauvais format" peut arriver également lors de l'ajout d'un id dans un groupe qui contient déjà un autre id non compatible.
Essaie de supprimer complétement le groupe et recommence.

**Comment by lil78711** [comment]
un exemple de lien a mettre svp

**Comment by lil78711** [comment]
mon lien https://pastebin.com/7cUmgMmm

**Comment by sizanic** [comment]
Ton fichier ne respecte pas le format attendu.

Pour exemple, des liens compatibles sont regroupés ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3045

Tu y trouvera également un tuto qui t'explique le format à respecter.
