### ISSUE TITLE
Trakt.TV

### ISSUE THREAD

**Issue by Manucciu** [Kodi-vStream/venom-xbmc-addons#3093]
Bonjour,

Trakt.tv ne remonte plus ce qu'on a vu, c'est bien dommage car c'est pratique

**Votre system**
 - OS: [Windows et Android]
-  Appareil [MI BOX et PC]
 - Version Kodi LEIA
- Version Vstream 0.8.2

**Nous devons le reproduire**
Pour cela il nous faut:
vstream et compte trakt.tv
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5410548/kodi.log)

LOG
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5410552/kodi.log)

**Comment by TmpName** [comment]
Tu as lancé trakt ?
Je ne vois aucun appel a lui dans tes logs ?

**Comment by Manucciu** [comment]
Il est bien lancé pourtant, j'ai une erreur quand je vais sur le calendrier, je l'ai enlevé et remit mais rien n'apparait dans les logs sur trakt effectivement juste ça quand je veux voir le calendrier

https://slexy.org/raw/s21cOgPE65?token=ed6710eb0a3065d7d37cdbf29a7e9884337a721d540f33f600c48a5daef6ab40&ts=1603218720

**Comment by TmpName** [comment]
Alors y avait un bug qui faisait tout planter, et qui n'affichait pas le total des series suivies.

Dis moi si c'est mieux de ton coté, tu devrais deja avoir moins d'erreurs, mais moi de mon coté c'est plus a jours depuis au moins 2 ans, ca a marché quand la derniere fois pour toi ?

**Comment by Manucciu** [comment]
Bonsoir,

Tout d'abord permet de te remercier d'avoir jeté un œil au code. Je t'avoue que c'est la première fois que j'utilise Trakt.TV après je trouve ça super pratique, pour savoir ce que j'ai vu et les listes de séries que ça peut me conseiller en fonction de ce que j'ai vu si en plus ça le fait en auto, c'est génial.

Voila, je testerais tout ça demain.
Merci encore

**Comment by TmpName** [comment]
Le truc, c'est que chez moi aussi ca met pas a jour.
Et je me demande si ca a pas été desativé, c'est pour ca que je te demandais quand est ce que ca marchait pour la derniere fois.

**Comment by alKODIque** [comment]
Bonjour @TmpName 
Je me permet de venir indiquer ce que j'ai également comme expérience, concernant l'intégration Trakt à l'intérieur de vStream. 

Effectivement, comme mentionné plus haut, j'ai remarqué qu'il était impossible d'ajouter, via le menu contextuel, un média a vue/non vu ou a liste de Trakt. Par contre, une fois que nous en sommes rendu au lien du média, bien que les choix ''vu / non vu''  disponibles au menu contextuel ne proviennent pas de vStream, il nous est possible d'ajouter l'élément a Trakt. Et ceci fonctionne car ensuite, à l'intérieur de vStream, je vois bien mon élément indiqué en tant que ''Vu'' avec le petit crochet blanc en bas de la pochette..

J'ai aussi remarqué que malgré le fait que tous les menus ouvrent, même mes listes personnelles, c'est lorsque je désire ouvrir les dossiers de séries télé que j'obtiens des erreurs.  Pour les films, ça se passe bien en général. Par exemple, lorsque je me rend dans me listes personnelles, je réussi sans problème a ouvrir une liste contenant des films, mais obtiens toujours un message d'erreur lorsqu'il s'agit d'une liste contenant des séries télé.  Ceci n'a pas de lien avec le fait que la liste en question contienne des caractères accentués ou non, puisque j'ai essayé avec les 2: 

- Pour les films, avec ou sans caractères accentués, les dossiers ouvrent.  

- Pour les séries, que le nom du dossier en ait ou non, il ne s'ouvre pas et génère un message d'erreur.

Pourtant, je suis bien en mesure de visualiser les épisodes à l'intérieur de mon dossier ''Sorties VO''....

Le premier log que j'ai attaché , j'y ai inclu les lignes d'erreurs lorsque j'ouvre le menu contextuel pour choisir ''TRAKT'' .  Il semble que Kodi ne trouve pas la fonction a attribuer à cet option.

Le 2e Log démontre ce qui arrive lorsque j'essaie d'ouvrir un dossier de Séries télé et que j'ai un message d'erreur.

Finalement, j'en profite pour t'attacher mon fichier TMDb.py ou j'ai modifié des lignes pour être en mesure d'ouvrir mes listes personnelles.  La correction n'est pas parfaite puisque elle permet d'ouvrir le dossier seulement si nos listes ne contiennent aucun caractère accentués.  Par contre, en attendant la solution qui fera en sorte que ces derniers s'affichent correctement, ce serait apprécié de l'inclure à vStream.  Entre cette solution ou rien dutout... c'est un moindre mal hihi!!

J'espère que mon intervention pourra aider à résoudre quelques=un des soucis rencontrés! 
Merci et A+ :)


[LOG1.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5427045/LOG1.txt)
[LOG2.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5427046/LOG2.txt)
[tmdb.py.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5427047/tmdb.py.txt)

**Comment by milkibreizh** [comment]
pour le log 1

> erreurs` lorsque j'ouvre le menu contextuel pour choisir TRAKT

...
818       ret = self.DIALOG.select('Trakt', lang)
DIALOG = dialog()
avec la classe dialog() on utilise VSselect et la sélection se fait plutôt ainsi (list,label)
donc on devrait avoir ret = self.DIALOG.VSselect( lang,'Trakt')
 le code marcherais si DIALOG était un instance direct de xbmcgui ,DIALOG = xbmcgui.Dialog()
faut voir aussi
1047 ret = self.DIALOG.select('Sélectionner un Moteur de Recherche', 

pour les autres soucis d'encodage je vois que c'est tjrs la même galère sous python :grin:

**Comment by alKODIque** [comment]
@milkibreizh 
> le code marcherais si DIALOG était un instance direct de xbmcgui ,DIALOG = xbmcgui.Dialog()

Ha, dela la raison pour laquelle lorsque j'arrive au lien, et que je sélectionne "vu/non vu" via le menu contextuel, ça fonctionne. Car c'est un dialogue de kodi  et non vStream que l'action se fait, c'est bien ça?

**Comment by milkibreizh** [comment]
@alKODIque 
bah je sais pas pour le dialog "vu/non vu
 moi j'ai seulement regardé ton log et la fonction qui avait créée le problème 
est bien à  la ligne 818  du fichier  trakt.py" de vstream..

**Comment by milkibreizh** [comment]
.....c'est un menu de vstream pas de kodi

**Comment by Arias800** [comment]
@alKODIque Est-ce que tu peux tester mon fichier de Trakt, car j'ai modifié pas mal de choses donc je voudrai savoir si ca tourne correctement avant de le mettre dans la beta.
https://github.com/Arias800/Fichier-divers/blob/master/trakt.py

**Comment by alKODIque** [comment]
Oui!
Avec plaisir ;)

Je te reviens bientôt

**Comment by alKODIque** [comment]
@Arias800 
Donc j'ai pas su attendre au matin :p 

J'ai essayé tout ce qui ne fonctionnait pas dans ce que j'ai décris plus haut, puis avec tes corrections tout est fonctionnel.  Je vois meme dans mon historique un film que j'ai visionné aujourd'hui :)

Je peux aussi entrer à l'intérieur des dossiers de mes listes de séries, ouvrir le menu contextuel et les choix d'ajouts aux listes, retrait, etc,,, fonctionnent toutes :)

J'ai testé a l'intérieur de mon compte Trakt, et via 2 autres sources au hasard. Avec les films et avec les séries. Je n'ai pas rencontré de problème :) 


Merci beaucoup!

![trakt1](https://user-images.githubusercontent.com/49578130/96972140-19a0ce00-14e4-11eb-9dc5-46c3ff44b564.png)
![trakt2](https://user-images.githubusercontent.com/49578130/96972144-1a396480-14e4-11eb-8058-bf657d4cff3f.png)

**Comment by Arias800** [comment]
Donc je le mets dans la bêta et je clôture l'issue. N'hésite pas à la recouvrir si jamais tu trouves un bug.
