### ISSUE TITLE
Uptobox et 1fichier ne fonctionne plus sur vstream

### ISSUE THREAD

**Issue by maxime1321** [Kodi-vStream/venom-xbmc-addons#3095]
Bonjours je suis nouveau ici je ne sais pas quoi faire avec cela j’ai un firestick tv sur kodi 18.8 vstream 0.8.2 j’ai des comptes uptobox et 1fichier mais ca marque toujours fichier introuvable quand j’essaye de lancer pourtant ca fonctionnais tres bien il ya quelque jours je reussis a me logger voir mes fichiers mais au moment de lancer introuvable quand je vais avec le navigateur mes fichiers fonctionne

**Votre system**
-  Appareil firestick
 - Version Kodi 18.8
- Version Vstream 0.8.2

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
http://www.vstream.ml/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by sizanic** [comment]
Si cela fonctionnait il y a quelques jours, c'est peut-ètre dû à la mise à jour 0.8.2 qui s'est installé il y a deux jours.

Il arrive qu'après une mise à jour, certains paramètres de vStream doivent être de nouveaux configurés.

Dans les paramètres de vStream, assure-toi d'avoir l'option ''Rester en direct avec uptobox''.
![image](https://user-images.githubusercontent.com/47307622/96884080-6b643c80-1481-11eb-9eb1-dfefac659d58.png)


Pour rappel, sur la page de ton compte Uptobox, assure-toi d'avoir désactivé l'option ''Téléchargement direct''.

![image](https://user-images.githubusercontent.com/47307622/96884141-77e89500-1481-11eb-890a-14dd9cd2d334.png)

**Comment by maxime1321** [comment]
Ok merci je verifie apres ma journée de boulot dans uptobox c’est bel et bien desactivé reste a verifier dans les parametres de vstream

**Comment by maxime1321** [comment]
En effet il etait desactivé par contre toujours rien as tu une autre piste de solution ?

**Comment by Che-debarras** [comment]
⚠️ Rapporter les bugs sur #3058 quand il s'agit de sources ou lien ⚠️

**Comment by BENJI97200** [comment]
Bjr pour moi aussi ne fonctionne plus après mise à jour Kodi 18.9(authentification rate).   Une solution svp???

**Comment by TmpName** [comment]
Tu aurais quelques logs ?
au moins les messages d'erreur ?

**Comment by BENJI97200** [comment]
@TmpName ...bjr ,j ai désinstallé et réinstallé...dc fonctionne mnt...merci

**Comment by TmpName** [comment]
Ok, tant mieux alors ^^, je cloture.
