### ISSUE TITLE
Extreme down ne marche pas ?

### ISSUE THREAD

**Issue by denseye73** [Kodi-vStream/venom-xbmc-addons#3096]
Sur extreme down tout fonctionne correctement jusqu'à l'affichage des différents hosters (Uptobox, uploaded, ...).
Mais quand je clique sur un des hosters il ne se passe rien!
Je suis tout seul dans ce cas?

**Comment by Che-debarras** [comment]
Rapporter les bugs sur #3058 quand il s'agit de sources ou lien

**Comment by denseye73** [comment]
c'est bon ça marche en automatique en entrant le bon token alldebrid

**Comment by Che-debarras** [comment]
> c'est bon ça marche en automatique en entrant le bon token alldebrid



> c'est bon ça marche en automatique en entrant le bon token alldebrid

Ce alldebrid est payant? Ou on peut l'utiliser en version free avec ce token ?

**Comment by Arias800** [comment]
Passé les raccourcisseurs d'url c'est autoriser pour les comptes gratuits (c'est la seule option qui est gratuite).

**Comment by sizanic** [comment]
> ⚠️ Rapporter les bugs sur #3058 quand il s'agit de sources ou lien ⚠️

oui, lorsqu'un bug est avéré.

La procédure serait plutôt : 
1 - Vérifier que le bug n'est pas référencé dans le ticket #3058 
2 - Créer une nouvelle issue pour en discuter
3 - S'il s'agit bien d'un bug, alors seulement on ajoute la description du bug à l'issue #3058


Le principe de vStream repose exclusivement sur des sources et des liens.
Si tous les bugs que l'on veut signaler concernant des sources et des liens doivent être saisis sur l'issue #3058, alors on devrait tous saisir dans cette unique issue.
Elle serait très rapidement difficile à gérer, on parlerait de plein de sujets (sources et liens) en même temps.
Et lorsqu'on veut répondre, il faut à chaque fois référencer la source, le lien ou une discussion antérieure.

Par exemple dans le cas de cette issue ici présente (#3096), une réponse a été apportée.
Il est intéressant que les échanges ne soient pas aller polluer l'issue #3058
On va pouvoir la cloturer.

L'idée de l'issue #3058 est bien mais elle doit seulement permettre de centraliser les bugs avérés (après analyse).

**Comment by Che-debarras** [comment]
@sizanic 
Cloturer #3058 ?
Ya des bugs encore en attente et la maj Master 0.8.2 ne contient pas toutes les corrections de la beta 0.8.2 notamment la correction de Mystream et autre.
Je suppose qu'il sera clôturer après après une autre maj dr Master?

**Comment by sizanic** [comment]
non, cloturer celle-ci même, la #3096 😄 

Mais pour la #3058 maintenant que tu parles cloture, n'aurions-nous dû pas la cloturer 🤔 
Et en créer un nouvelle en y reportant les bugs restants de la v0.8.2.

**Comment by milkibreizh** [comment]
> Et en créer un nouvelle en y reportant les bugs restants de la v0.8.2

Che-debarras mais  à jour le résumer des bugs en modifiant l’entête de la page 
à chaque résolution de bug ou apparition de nouveau bug
donc la majorité des bugs restant y sont
faut juste confirmer que chaque bug et chaque résolution 
soit conforme à ce qui tout  les utilisateurs ont en effet 
comme problèmes ou comme problème résolus

**Comment by sizanic** [comment]
c'est comme on veut, c'était juste pour repartir sur une issue propre sinon elle ne se termine jamais.
L'entête est à jour mais le nombre d'échange augmente sans fin.

**Comment by yodidon** [comment]
C’est vrai que pour savoir ce qui est résolu il faut parfois suivre les échanges , alors une nouvelle issue peut-être serais la bonne idée, mais il faudrait une issue sur les résolutions pour pas polluer, et si possible modifier l’issue des buts en fonction des résolutions

**Comment by milkibreizh** [comment]
,c'etait juste pour dire que l'on pouvait au moins partir
du résumer des bugs de l'issu #3058 en discuter sur chaque point et  mettre la conclusion
sur une autre issue .mais on peu aussi  partir de zero...

**Comment by yodidon** [comment]
Ça serait sûrement plus simple si cette issue était moderé

**Comment by milkibreizh** [comment]
oui mais il faut qql' un de modéré 😄

**Comment by Che-debarras** [comment]
> > Et en créer un nouvelle en y reportant les bugs restants de la v0.8.2
> 
> Che-debarras met à jour le résumer des bugs en modifiant l’entête de la page
> à chaque résolution de bug ou apparition de nouveau bug
> donc la majorité des bugs restant y sont
> faut juste confirmer que chaque bug et chaque résolution
> soit conforme à ce qui tout les utilisateurs ont en effet
> comme problèmes ou comme problème résolus

Exactement je met a jour le 1e post a chaque modification de la beta.
Des que un fichier est modifié concernant les sources ou liens je reteste et je confirme si c'est résolu 
C'était le cas pour le hoster Mystrm par ex ou la source ZT.

Ya pas  besoin de lire les échanges mais juste le 1e post que je met a jour apres chaque commit.
J'ai arrêté de mettre l'ID du commit mais peut-être le remettre  comme ça les tous le monde sera que c'est la conclusion des derniers modif publié sur la beta.

De même quand une personne reporte un bug je le met sur la 1e issue enfin su c'est avéré car bcp ne semble pas changer leur dns ni vérifier si sur un navigateur la source ou le host fonctionne.

Je met le mot résolu sur le 1e post et si ya pas le mot résolu c'est que le bug est toujours là.

Les échanges doivent être utilisés pour rapporter les bugs donc ça pollue pas surtout que pour etre honnete ya pratique pas de bugs si ce n'est Cloudfare (tirexo, zt) ou m3u8 (kaydi).

Mais je comptais clore l'issue #3058 apres la correction des autres bugs :
Kepliz,
GoUnlmtd 
Strmtape
Vidlox
Toro
AllFlm

Surtout que toutes les modifications pour la v0.8.2 n'ont pas été mergé avec la Master , n'ont pas pas apporté de correction donc pour mois cela reste tjr du 0.8.1 pour ma master et 0.8.2 pour la beta.

Donc je me dis avec ces corrections ci-dessus faite et mergé avec la master on pourra passer a un nouvelle issue pour une v0.8.3 qui apportera des corrections ou des améliorations car la 0.8.2 n'apporte aucune correction a la 0.8.1 de master.

Ce n'est que mot avis et désolé pour ce long message mais crée un autre issue qui fera juste copier coller le 1e poste

> oui mais il faut qql' un de modéré 😄 😑
@milkibreizh 
Je pense que tu devrais faire attention a ce que tu dis pour ne pas troller et recrée une ambiance negative avec tes sous-entendus
J'ai fait l'effort de tourner la page mais si tu relances le sujet la dessus je craint que cette fois sur le suivi des bug faudra trouver un autre volontaire.

**Comment by Che-debarras** [comment]
> oui mais il faut qql' un de modéré 😄 😑

@sizanic @milkibreizh 
Visiblement je ne suis pas modéré
Bonne chance pour le suivi

**Comment by yodidon** [comment]
Pas compris moi ?

**Comment by sizanic** [comment]
>>Che-debarras met à jour le résumer des bugs en modifiant l’entête de la page
à chaque résolution de bug ou apparition de nouveau bug
donc la majorité des bugs restant y sont
faut juste confirmer que chaque bug et chaque résolution
soit conforme à ce qui tout les utilisateurs ont en effet
comme problèmes ou comme problème résolus

>Exactement je met a jour le 1e post a chaque modification de la beta.
Des que un fichier est modifié concernant les sources ou liens je reteste et je confirme si c'est résolu
C'était le cas pour le hoster Mystrm par ex ou la source ZT.
Ya pas besoin de lire les échanges mais juste le 1e post que je met a jour apres chaque commit.
J'ai arrêté de mettre l'ID du commit mais peut-être le remettre comme ça les tous le monde sera que c'est la conclusion des derniers modif publié sur la beta.
De même quand une personne reporte un bug je le met sur la 1e issue enfin su c'est avéré car bcp ne semble pas changer leur dns ni vérifier si sur un navigateur la source ou le host fonctionne.
Je met le mot résolu sur le 1e post et si ya pas le mot résolu c'est que le bug est toujours là.
Les échanges doivent être utilisés pour rapporter les bugs donc ça pollue pas surtout que pour etre honnete ya pratique pas de bugs si ce n'est Cloudfare (tirexo, zt) ou m3u8 (kaydi).
>
>Mais je comptais clore l'issue #3058 apres la correction des autres bugs :
Kepliz,
GoUnlmtd
Strmtape
Vidlox
Toro
AllFlm

>Surtout que toutes les modifications pour la v0.8.2 n'ont pas été mergé avec la Master , n'ont pas pas apporté de correction donc pour mois cela reste tjr du 0.8.1 pour ma master et 0.8.2 pour la beta.

Comment ça ? Du code n'a pas été mergé ?
As-tu un exemple car normalement la procédure pour une mise à jour prévoit que tous le code de la beta soit mergé.

Et lorsqu'on installe la dernière version de vStream, elle est bien estampiller 0.8.2.
Donc on ne peut pas dire que la master est en 0.8.1 si on veut faire référence à des bugs existants.


>Donc je me dis avec ces corrections ci-dessus faite et mergé avec la master on pourra passer a un nouvelle issue pour une v0.8.3 qui apportera des corrections ou des améliorations car la 0.8.2 n'apporte aucune correction a la 0.8.1 de master.

A confirmer.
Je vais vérifier les deniers merges sur la master...

>Ce n'est que mon avis et désolé pour ce long message mais crée un autre issue qui fera juste copier coller le 1e poste

>>oui mais il faut qql' un de modéré 😄 😑
@milkibreizh

>Je pense que tu devrais faire attention a ce que tu dis pour ne pas troller et recrée une ambiance negative avec tes sous-entendus. J'ai fait l'effort de tourner la page mais si tu relances le sujet la dessus je craint que cette fois sur le suivi des bug faudra trouver un autre volontaire.

Nous aussi on a tourné la page, c'était justement une façon de dire que maintenant on préfère en rire.

**Comment by milkibreizh** [comment]
> Visiblement je ne suis pas modéré
> Toujours les mêmes qui manquent de respect

je disais cela dans un cas general ,sans viser personne particulièrement ,
mais justement en parlant de tout le monde
c’était une blague ...une blague certes lourdos..mais une blague
et je ne m'attendais vraiment pas du tout à cette interprétation de ce que j'ai ecrit
sinon je ne l'aurais pas fait...et j'en vois pas vraiment  l’intérêt
