### ISSUE TITLE
ZT ne marche plus

### ISSUE THREAD

**Issue by Manucciu** [Kodi-vStream/venom-xbmc-addons#3097]
je crois que ZT à changer un truc j'ai une erreur sur mon kodi ZT ne mets plus aucun lien, ou ça vient que de moi

[20:08]
[PLUGIN] vStream: ZT pas besoin d'url
2020-10-25 20:05:43.919 T:5572  NOTICE:     [PLUGIN] vStream: Erreur decodage Stormwall

**Comment by milkibreizh** [comment]
@Manucciu 
oui exact cela marchait et plus maintenant...et on a bien l'erreur que tu cites :frowning2:

**Comment by Che-debarras** [comment]
Veuillez svp écrire sur #3058 sinon je vois pas l'intérêt de centraliser les bugs sur un sujet si chacun rédige un sujet par problème ou par bug.

Pour ZT c'est aléatoire des fois ça marchent des fois non, il faut revenir en arrière et cliquer plusieurs fois.

Sans doute un problème de chez eux voir un changement de url a venir pour tirexo.pro.

Mais j'ai eu ce problème et en cliquant plusieurs fois  les liens finissent par revenir (pensez aussi a vider le cache de vstream et kodi) cat j'ai eu 3 fois ce souci et en insistant les liens reviennent.

Les bugs sont listés sur #3058

**Comment by Arias800** [comment]
Pour le moment ils ont activé Recaptcha sur Stormwall, donc on ne peut rien faire.

**Comment by milkibreizh** [comment]
j'ai bien vu 
et je me suis pris la tete sur le recaptcha mais je ne retrouve que la moitié des paramètres de requêtes à chaque fois :grimacing:

**Comment by thorsten68** [comment]
Bordel si seulement ça arrêtait de changer tous les 2 jours 😭😭
