### ISSUE TITLE
Upstream ne fonctionne plus

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#3098]
Le hoster Upstream semble ne plus fonctionner.
Voir 9Docu.

Merci à vous.

Prenez soin de vos familles et de vous-même.

**Comment by milkibreizh** [comment]
@Papounet58 
c'est réglé
le hoster Upstream  était à moitier HS
tu vas pouvoir t'occuper de ta famille devant tes programmes préférés ^

**Comment by Papounet58** [comment]
Merci à toi pour la rapidité.
Bonne journée.
Prends soin des tiens et de toi.

Le mer. 28 oct. 2020 à 03:41, milkibreizh <notifications@github.com> a
écrit :
