### ISSUE TITLE
Trakt limitation trafic

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#3099]
J'ai reçu un mail destinée a tous ceux qui utilise l'api trakt.

Salut,
A partir du 27 octobre 2020, nous appliquons une limitation du trafic pour toutes les applications API. Vous avez créé une application API Trakt, et nous voulions vous le faire savoir. Si vous avez des questions, veuillez poursuivre la discussion dans le cadre du projet API GitHub.

POURQUOI DES LIMITES TRAFIC SONT-ELLES APPLIQUÉES ?
Au cours des derniers mois, les performances de Trakt ont été affectées par une énorme augmentation du trafic API et des applications mal codées. Afin de stabiliser l'API et d'augmenter les performances pour tous, nous avons mis en place une limitation. L'API Trakt est libre d'utilisation, et la limitation du trafic nous aidera à la maintenir.

DE QUELLES MISES À JOUR MON APPLICATION A-T-ELLE BESOIN ?
Votre application devra gérer le code d'état HTTP 429 et les en-têtes qui sont envoyés lorsque la limite de débit est dépassée. Ce code peut être intégré à votre bibliothèque d'API ou vous pouvez avoir besoin de personnaliser votre code pour le gérer. Les documents de l'API contiennent plus de détails.

QUELLES SONT LES LIMITES ?
/sync/history/* 2 appels par seconde 
Toutes les méthodes API 1 000 appels toutes les 5 minutes 

Toutes les limites sont par utilisateur. 

ENSUITE
Nous prévoyons d'ajuster les limites jusqu'à ce que nous trouvions un équilibre entre de bonnes performances et un impact minimal des applications. L'objectif est de prévenir les abus des API, mais de permettre aux utilisateurs d'utiliser les applications normalement. Nous tiendrons à jour les documents de l'API avec les limites tarifaires actuelles.

**Comment by LordVenom** [comment]
Bon il partage pas le trafic de notre api donc comment on fait pour savoir si ça tourne beaucoup ou pas, un peux con quand même.

**Comment by lebigboss** [comment]
Le 27 c'était hier, enfin aujourd'hui on est le 28.
Donc ça a changé quelque chose pour vous ? 
Moi je vois pas où alors on est pas concernés

**Comment by Arias800** [comment]
1000 appels toutes les 5 minutes c'est large xD
