### ISSUE TITLE
aide pour ajouter un site

### ISSUE THREAD

**Issue by zombiB** [Kodi-vStream/venom-xbmc-addons#3100]
Salut à  tous , 
j'essaie de faire fonctionner ce site avec l'addon mais je n'arrive pas  à afficher le lien du video

https://pastebin.com/raw/ywhVaNkU

est-ce que vous pouvez m'aider svp ?
merci

**Comment by sizanic** [comment]
Je voudrais bien t'aider mais je n'arrive pas à accéder au site.

**Comment by lebigboss** [comment]
Le site est Out

**Comment by sizanic** [comment]
>j'essaie de faire fonctionner ce site avec l'addon 

C'est vraiment pour l'addon vStream que tu essaie de le faire fonctionner ?
Il y a vraiment du contenu francophone sur ce site ?

Ou est-ce plutôt pour ton addon :
https://github.com/zombiB/zombi-addons/tree/master/plugin.video.matrix/resources/sites

**Comment by milkibreizh** [comment]
en utilisant un vpn on peu accéder au site
tu est bloqué où ?

pour le menu il faut que tu remplaces 'showSeriesSearch' par MOVIE_NEWS[1] et 'h_ttp://venom/' par MOVIE_NEWS[1]
et il faut rajouter pour la recherche
URL_SEARCH= ('ht__tps://open.egybest.asia/explore/?q=','showMovies')
URL_SEARCH_MOVIES = (URL_SEARCH[0], 'showMovies')
et il te manque la fonction def showSearch(): à definir
sinon pour le hoster tu as de la chance de pouvoir récupérer le /dostream?k=bec3
il faut encore faire une requête tu vas obtenir un fichier avec un liste de fichier mu3 qu'il faut extraire
h__ttps://o5-nv9-s-x4pm.vid......stream.m3u
de mon coté je n'arrive pas a avoir de bon résultât avec la requête h_ttps://open.egybest.asia/watch/?v=sRRR 
j'ai l'impression qu'il  manque des paramètres de cookies et c'est du cloudfare,il faut peu être rajouter 
le __cf_bm= dans les cookies..? bonne continuation pour ton addon^^

**Comment by sizanic** [comment]
je n'ai pas de vpn.
@milkibreizh tu vas pouvoir nous dire, il y a bien du contenu francophone sur ce site ?

**Comment by milkibreizh** [comment]
bah disons que les sous titres sont en anglais..
mais j'ai pas tout regardé but i dont speak english but i read it

**Comment by sizanic** [comment]
oui, c'est ce qu'il me semblait, cette source ne terminera pas dans vStream ...

**Comment by zombiB** [comment]
> > j'essaie de faire fonctionner ce site avec l'addon
> 
> C'est vraiment pour l'addon vStream que tu essaie de le faire fonctionner ?
> Il y a vraiment du contenu francophone sur ce site ?
> 
> Ou est-ce plutôt pour ton addon :
> https://github.com/zombiB/zombi-addons/tree/master/plugin.video.matrix/resources/sites

j'aurai du le préciser , oui c'est pour mon petit addon qui est un clone de vstream et qui fonctionne pareil c'est pourquoi g  cherché l'aide pour le code mais je savais pas que le site est géolocalisé dsl   :) 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/549

**Comment by zombiB** [comment]
> en utilisant un vpn on peu accéder au site
> tu est bloqué où ?
> 
> pour le menu il faut que tu remplaces 'showSeriesSearch' par MOVIE_NEWS[1] et 'h_ttp://venom/' par MOVIE_NEWS[0]
> et il faut rajouter pour la recherche
> URL_SEARCH= ('ht__tps://open.egybest.asia/explore/?q=','showMovies')
> URL_SEARCH_MOVIES = (URL_SEARCH[0], 'showMovies')
> et il te manque la fonction def showSearch(): à definir
> sinon pour le hoster tu as de la chance de pouvoir récupérer le /dostream?k=bec3...
> il faut encore faire une requête avec celle ci et tu vas obtenir un fichier avec un liste de liens mu3 qu'il faut extraire
> h__ttps://o5-nv9-s-x4pm.vid......stream.m3u
> de mon coté je n'arrive pas a avoir de bon résultât avec la requête h_ttps://open.egybest.asia/watch/?v=sRRR.. .
> j'ai l'impression qu'il manque des paramètres de cookies et c'est du cloudfare,il faut peu être rajouter
> le __cf_bm= dans les cookies..? bonne continuation pour ton addon^^

oui c'est compliqué comme site enfin un ami m'a aidé pour trouver la solution et afficher le hoster
merci pour ton encouragement  ^_^

**Comment by milkibreizh** [comment]
@zombiB 
bah du coup j'ai regardé un peu ton code...j'aurais pas trouvé
...je crois qu'il a qqles trucs qu'on vas cloner :wink:

**Comment by zombiB** [comment]
> @zombiB
> bah du coup j'ai regardé un peu ton code...j'aurais pas trouvé
> ...je crois qu'il a qqles trucs qu'on va cloner

oui avec plaisir ^^
