### ISSUE TITLE
Plus d'accès aux IPTV

### ISSUE THREAD

**Issue by mmtest1** [Kodi-vStream/venom-xbmc-addons#3101]
Bonjour,
depuis la dernière mise à jour de vstream l'accès aux iptv n'est plus disponible. J'utilisais régulièrement les sources iptv officielles mais la liste n'est plus accessible. Pour les autres sources l'accès au lien final n'est plus disponible.

**Votre system**
 - OS: Raspberry Pi OS Buster
-  Appareil : Raspberry pi 4 4Go RAM
 - Version Kodi  18.7
- Version Vstream 0.8.2 Officiel

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : Télévision - Iptv (officiel)
- Le titre du fim/serie : pas d'accès à la liste des chaînes

**Log**
si je suis le seul à rencontrer le bug je peux fournir un fichier log ce soir

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

merci pour le suivi et cette EXCELLENTE extension

**Comment by Arias800** [comment]
C'est corrigé.
