### ISSUE TITLE
Le nouveau menu "information" ne fonctionne plus sous SPMC

### ISSUE THREAD

**Issue by Digidix** [Kodi-vStream/venom-xbmc-addons#3103]
Bonjour tout le monde !

Depuis la dernière Maj de Vstream, le menu information n'est plus compatible avec SPMC.

En effet, je n'ai plus les infos des films quand je fais appuie long sur un lien puis information.

À la place du synopsis, j'ai un fond noir et à la place de la jaquette le message "not Available", avec en bas à gauche l'inscription "based on skin artic horizon".

J'ai presque tout essayé même réinstaller SPMC et Vstream sans succès.

Je reste sur SPMC car il est optimisé pour mon boitier Android TV sous Amlogic, et Kodi ne prend pas en compte ce type de processeur et fait crasher mon boitier TV.

J'utilise également SPMC pour mes autres périphériques Android car il est beaucoup plus fluide que Kodi.

J'espère que vous pourrez régler ce petit problème, qui devient vite embêtant à la longue, et malheureusement il n'y a pas d'autre alternative à l'excellent SPMC pour Android (mis à part les systèmes du genre Libreelec mais ce n'est pas très adapté pour les tablettes pour une utilisation "familiale").

Je file sur mon boitier TV pour mettre un fichier log.

Merci !

Votre système :

OS : Android (TV 7.1.2 et Android 9)

Appareil : Multi

Version Kodi : SPMC 16.7.4

Version Vstream : 0.8.2 Officiel

Le nom du site : Tous

Log : https://slexy.org/view/s20NT35oUW

**Comment by sizanic** [comment]
bonjour,

Jen 'ai rien trouvé de pertinent à la lecture de ton log : 

```
[PLUGIN] vStream: load site cGui and call function viewInfo
[PLUGIN] vStream: SQLITE 3 as DB engine for tmdb
WARNING: CSkinInfo: failed to load skin settings
ERROR: CGUITextureManager::GetTexturePath: could not find texture 'OverlayUnwatched.png'
ERROR: Previous line repeats 27 times.
NOTICE: 	[PLUGIN] vStream: SQLITE 3 as DB engine for db
```

Ce qui concerne la texture 'OverlayUnwatched.png', ce message apparait déjà plusieurs fois avant l'accès à la fenetre d'information, ce n'est pas spécifique à cette action.

La seule piste est ceci : 
WARNING: CSkinInfo: failed to load skin settings

Mais ce n'est pas une erreur, juste un warning, et une rapide recherche sur internet ne le cite pas comme gênant.
- Pour autant, peux-tu essayer avec un autre skin.
- Ou essayer d'activer "Extendedinfo" dans les parametres de vStream.

**Comment by Digidix** [comment]
Je trouvais aussi que le log n'était pas très parlant !

Concernant le skin, j'ai déjà essayé tous les skins dispo dans SPMC sans résultat.

Pour "Extendedinfo", la seule option que je n'avais pas testé car c'est un addon abandonné, effectivement ça fonctionne mais ce n'est pas l'idéal.

En effet, pour chaque demande d'information sur un film, il met plus de quinze secondes à chaque fois pour s'ouvrir, et cela peu importe le réglage dans "Extendedinfo".

A lire ça paraît peu mais à l'usage c'est plutôt gênant.

La seule solution serait de mettre un autre addon comme "Extendedinfo" mais plus récent et suivi par son dév.

Du coup aurais-tu une idée pour un addon à jour, qui viendrait rendre plus agréable ce menu "information" ?

**Comment by sizanic** [comment]
Jai voulu regarder le probleme pour le corriger en installant SPMC sur mon PC.
Mais ça n'existe pas 😆 

je ne peux pas le corriger facilement, désolé.

Je ne connais pas d'autre addon qui peuvent te proposer une fenetre d'information.
(je pensais à tmdb mais je n'ai pas réussi)

**Comment by Digidix** [comment]
La seule solution serait comme tu le dis qu'un dév comme toi ou Arias essaye directement avec SPMC, soit sur un périphérique Android ou éventuellement sur PC avec un émulateur Android, sinon effectivement je pense qu'un bug comme celui-ci, avec si peu de log, est quasiment impossible à trouver !

En tout cas merci d'avoir passé du temps sur ce problème, et merci infiniment pour tout ce que tu apportes à Vstream depuis que tu as rejoint l'équipe !

**Comment by Arias800** [comment]
SPMC n'est plus en développement. Donc ont ne peut pas assurer continuellement le support de Vstream sur SPMC (au bout d'un moment ca va forcément coincé). https://twitter.com/koying/status/975425129239990273

**Comment by Digidix** [comment]
Salut Arias !

En effet, SPMC n'est plus mis à jour depuis 2018, je me doutais bien que ça risquait de ne plus fonctionner de manière optimale au bout d'un moment.

Je souhaitais juste voir avec vous si ce problème pouvait être résolu de manière "simple", mais ce n'est pas le cas.

Je vais du coup voir du côté de LibreELEC.

Je clore donc ce sujet et vous remercie tous les deux une nouvelle fois :thumbsup:
