### ISSUE TITLE
Time2watch

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3107]
Salut à tous, visiblement Time2watch a un souci et donc les liens ne sont plus accessibles via notre Addon favori.
J'ai cherché sur le net et je suis tombé sur une annonce de leur part sur leur compte twitter que je vous partage.
Désolé j'aurai bien fais la manip mais je ne suis pas assez calé, si une âme charitable pourrait modifier la beta avec cette modif ce serait génial.
![IMG_20201105_110918](https://user-images.githubusercontent.com/43355451/98227637-d3258780-1f57-11eb-96ca-db786d0752bf.jpg)

**Comment by Arias800** [comment]
C'est pas utile de faire de modif de notre coter car tout va se faire automatiquement du coter des DNS.

**Comment by Niconimes** [comment]
> C'est pas utile de faire de modif de notre coter car tout va se faire automatiquement du coter des DNS.

Ok donc si je comprends bien ça va revenir à la normal tout seul.
Merci pour ta réponse Arias, je clôture l'issue du coup 👍
