### ISSUE TITLE
PATCH PROVISOIRE DE VSTREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3108]
vStream à son Patch Provisoire à créer soi-même disponible en Fichier Zip
au https://github.com/ludopotte/vStream/releases/tag/patchprovisoire

**Comment by sizanic** [comment]
@ludopotte 

Si j'analyse le tuto que tu fournis avec ton patch provisoire :

```
Pour créer le Patch Provisoire de vStream, suivez les Etapes si dessous :

Etape 1 : telechargez la Beta de vStream en copiant/collant le Lien si dessous entre parenthèse.
(https://github.com/Kodi-vStream/venom-xbmc-addons/archive/Beta.zip)

Etape 2 : decompressez la Beta et prenez le Fichier "plugin.video.vstream",
ensuite copier/coller les Fichiers à leurs emplacements indiqués
inclus dans ce dossier.

Etape 3 : compressez le Dossier ""plugin.video.vstream" et apres installer le Patch dans Kodi.
```

Ce que tu proposes, c'est de prendre le patch officiel et de modifier certains fichiers (ceux que tu fournis dans le zip).

Tu décris ici sur le github officiel de vStream une méthode pour avoir un vStream moddé par tes soins ! 🤔 

Je ne pense pas que ce soit ton objectif !
Pourquoi les fichiers que tu fournis devraient être installés par dessus la Beta officielle ?

**Comment by ludopotte** [comment]
Pour te faire simple, pour utiliser mon Patch faut l'installer par dessus vStream et j'ai mis a disposition les Fichiers pour le Patch Provisoire pour que les gens peuvent mettre à jour eux même vStream quand moi j'ai pas mis à jour mon Patch. Mon but est de partager pour que vStream marche bien pour le plus grand nombre.

**Comment by sizanic** [comment]
je comprends l'objectif mais je comprends pas pourquoi toutes ces étapes.

Car avec seulement ces étapes :
-  telechargez la Beta de vStream 
- decompressez la Beta
- compressez le Dossier ""plugin.video.vstream" et apres installer le Patch dans Kodi.


ça suffit, c'est forcement à jour !

Tu insères une étape au milieu pour incorporer des fichiers.
D'où viennent ces fichiers?

En téléchargeant ce lien (étape 1) : 
https://github.com/Kodi-vStream/venom-xbmc-addons/archive/Beta.zip

=> C'est FORCEMENT les derniers fichiers à jour !!

**Comment by ludopotte** [comment]
Les Fichiers que je propose dans le Patch Provisoire sont les Fichiers que j''ai fait pour avoir un meilleur visuel de certains Logos Sources par rapport au bugs etc... Je modifies pas les Fichiers des Développeurs.

**Comment by sizanic** [comment]
oui, j'ai bien vu que ce ne sont que des logos (donc l'intérêt est assez limité).

Donc tu proposes bien ici une procédure pour "patcher" la version officielle. Une sorte de "vStream-MOD".

On ne peut pas te laisser diffuser ici une procédure qui consiste à prendre les fichiers officiels, pour y insérer des fichiers à ta sauce.
Même si dans ce cas ce ne sont que des logos, c'est par principe.

**Comment by sizanic** [comment]
Si par contre tu veux que certains de tes logos deviennent des logos officiels, tu peux nous les soumettre.

**Comment by ludopotte** [comment]
Ok je suis la pour aider la Communauté e vStream et je respect le principe des modifications officielles dans la Beta. Explique moi alors comment mettre mes Logos dans la Beta pour que les gens puissent en bénéficier s'il te plait ?

**Comment by sizanic** [comment]
Je sais que ça part d'un bon sentiment, c'est d'ailleurs pour ça que je veux exactement comprendre ce que tu essaies de faire pour qu'on trouve la meilleure solution.

Dans tous les cas, si tu veux mettre **tes** logos personnalisés à disposition de ta communauté, ça ne peut pas être sur le git officiel.

> comment mettre mes Logos dans la Beta pour que les gens puissent en bénéficier 

Je ne comprends pas le bénéfice apporté ?
Pourquoi les gens voudraient des logos différents ?

Tu patches les logos pour mettre en avant que c'est une version Beta ?

**Comment by ludopotte** [comment]
Mon Patch est la version Beta pris sur le Github Officiel avec juste mes logos modifiés par rapport au bugs que les gens et moi avant rencontrer en discutant via discord.

**Comment by sizanic** [comment]
Désolé je ne comprends pas.

> Mon Patch est la version Beta pris sur le Github Officiel avec juste mes logos modifiés par rapport au bugs que les gens et moi avant rencontrer en discutant via discord

Logos modifiés par rapport aux bugs ?
Donc si la Beta contient une correction sur Tirexo par exemple, tu va changer le logo de Tirexo pour indiquer que la source est corrigée dans la beta ?
Il y a vraiment des gens qui vont suivre toute ta procédure pour que logos soient changés et comprennent que la beta contient une correction sur cette source ?

Je voudrais vraiment comprendre à quel besoin tu réponds, car peut-être pouvons mettre en place quelque chose d'officiel dans la Beta pour y répondre.

> pour les gens qui connaisse rien en informatique

Il y a une façon plus simple que de passer par : un zip / dezip / ajout de fichier/ rezip/ clef USB / installer depuis un zip.

> qui veulent avoir vStream mis à jour pour un bon fonctionnement.

NON, une Beta ne garantie pas un bon fonctionnement.

Depuis plusieurs années d'utilisation, je n'ai jamais eu besoin d'installer une beta pour avoir accès à du contenu.

**Comment by ludopotte** [comment]
On pourrais voir oui pour mettre en place quelque chose d'officiel dans la Beta pour y répondre et je change pas tous les logos des Sources mais quelques unes que j'ai sélectionnées. Tu as qu'as télécharger le Patch Provisoire et tu verra par toit même. J'ai pas mal discuter avec des Gens qui utilisent vStream et ils ont trouver mon Patch pratique donc je continuerais à le faire.

**Comment by sizanic** [comment]
Je trouve aussi ton patch pratique (le complet, j'ai récupéré le 8.2.35)
Car il est facile de le mettre en place : 
J'utilise un addon qui installe directement depuis github (et cette technique est vraiment LA technique accessible pour des personnes qui ne maîtrisent pas l'outil informatique)

Par contre je ne savais pas que ton zip contenait des fichiers modifiés par rapport aux vrais fichiers officiels :(

> Tu as qu'as télécharger le Patch Provisoire et tu verra par toi même

j'ai téléchargé pour essayer de comprendre et si je te questionne c'est justement parce que je ne comprends pas pourquoi ce sont ces logos modifiés que tu proposes dans le patch.
Quels rapports avec des corrections de la beta ??

Pourquoi proposer ce logo pour filmspourenfants.png.
Il n'y a pas eu de correction dans la beta.
Et ce n'est pas un logo mais une copie d'écran.
Pareil pour enStream.
(tout ça ressemble vraiment plus un vStream MOD)

Il n'y a vraiment que le Fanart.jpg qui renseigne sur le coté Beta.
Mais il ne devrait y avoir que ça.
Et pour ça on peut mettre en place quelque chose d'officiel.

Et on pourra également promouvoir ton patch complet si il ne contenait aucun fichier modifié par toi.

**Comment by ludopotte** [comment]
Ok je suis d'accord pour promouvoir mon Patch Complet dans fichiers modifiés. Comment on procedes ?

**Comment by sizanic** [comment]
Si aucun fichier n'est modifié dans ton zip global, la technique de diffusion la plus simple est la mise à jour par Kodzi / Github.

**_Préparation - A FAIRE UNE SEULE FOIS_**

- "Ajouter une source" -> "https://mrkodz2.github.io/repo/" avec le nom "Kodzi"
- "Extensions" / "Installer à partir d'un fichier ZIP" / source «Kodzi» et sélectionnez le fichier repository.thekodz-2.0.0.zip
- "Extensions" / "Installer à partir du dépôt" -> ‘’The Kodz Repository 2’’ / "Extensions programme" -> Installer Kodzi
- "Extensions" / "Programmes" / Ouvrir Kodzi -> "search Github" / "search Github username" / ludopotte
- "ludopotte" / sélectionner la ligne "vStream" (sans entrer dedans) -> Menu "Ajouter aux favoris".
- Favoris de KODI / favoris "vStream" (KODZI) -> Renommer en "vStream - Install Beta"

**_Installation de la Beta Ludopotte_**

- Depuis les favoris de KODI -> lancer le favoris "vStream - Install Beta"

**-> Chacune de tes nouvelles Beta est proposée en un seul clic !**

<br>
Je sais que tu connais cette technique.
Mais tu sais également que nous ne voulons pas trop la diffuser pour éviter que tout le monde se mette à installer des Beta.

Lorsque je parle de faire la promotion, c'est surtout te laisser en parler (modérément) et te laisser ton canal dans le discord.

La procédure que je viens de décrire ici est également une publicité pour ceux qui suivent le sujet 😆 


Concernant la mise en place de quelque chose d'officielle, l'objectif est bien d'informer qu'il s'agit d'une Beta ?

Que dirais-tu d'une pop-up qui s'ouvre au lancement de vStream "Vous utilisez vStream en version Beta 8.2.35 !".
(car changer le logo n'est pour moi pas suffisant, beaucoup utilisent vStream en widget sur la page d'accueil de KODI sans jamais retourner dans les menus vStream).

La seule modif que tu continuerais à faire est celle dans addon.xml (numéro de version).


Je m'avance peut-être sur la faisabilité de cette popup, mais est-ce bien dans l'idée que tu as de cette évolution ?

**Comment by TmpName** [comment]
C'est qu'on pas mit de license au projet, donc c'est la fete du slip.
La version patchée, les gens font ce qu'ils veulent, c'est toujours Vstream en plus

Par contre oui, si les gens preferent tes modifications, proposes les ici, elle seront officielles, et de maniere fixe et durable.

Si c'est refusé, rien t'empeche de le faire de ton coté, mais je vois pas pkoi ce serait refusé officiellement.

**Comment by Che-debarras** [comment]
> J'utilise un addon qui installe directement depuis github (et cette technique est vraiment LA technique accessible pour des personnes qui ne maîtrisent pas l'outil informatique)
> 

C'est quoi LA technique stp car ca éviterais de passer par un navigateur pour ddl la beta et ensuite l'installer sir kodi.
Si on peut directement le faire par kodi via un addon ce serait plus simple donc je te serais reconnaissant si tu partager cette addon stp.

Merci

**Comment by sizanic** [comment]
> C'est quoi LA technique stp car ca éviterais de passer par un navigateur pour ddl la beta et ensuite l'installer sir kodi.
> Si on peut directement le faire par kodi via un addon ce serait plus simple donc je te serais reconnaissant si tu partager cette addon stp.
> Merci


https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3108#issuecomment-728137725

😆

**Comment by sizanic** [comment]
> Pour moi, la version patchée, les gens font ce qu'ils veulent, c'est toujours Vstream en plus

Oui, tant que ce ne sont que des logos qui sont modifiés, c'est toujours vStream.
Et on fait confiance à ludopotte pour que ce soit les seules modifs.
Mais on n'est pas à l'abri que demain quelqu'un d'autre propose un zip avec des fichiers python modifiés !
(Il faut donc rester prudent.)

Le mieux étant que ce patch ne contienne pas de modification, donc si on peut les intégrer en natif c'est mieux 👍 

@TmpName 
La question se pose pour les patchs de Ludopotte car tous ses patchs sont diffusés sur le discord officielle de vStream.
(s'il ne les gardait que chez lui, il pourrait bien sûr les modifier à souhait)

Il faut comprendre que quelqu'un qui se rend sur le discord officiel et clique sur un lien qui lui permet de télécharger un zip, il sera persuadé d'avoir la version Beta officielle, c'est trompeur.

**Comment by ludopotte** [comment]
Merci de l'intérêt que vous porter pour mon Patch et ca y est, j'ai appliqué les Conditions et l'installation pour le Patch d'après les Mots de sizanic

**Comment by Che-debarras** [comment]
> > C'est quoi LA technique stp car ca éviterais de passer par un navigateur pour ddl la beta et ensuite l'installer sir kodi.
> > Si on peut directement le faire par kodi via un addon ce serait plus simple donc je te serais reconnaissant si tu partager cette addon stp.
> > Merci
> 
> [#3108 (comment)](https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3108#issuecomment-728137725)
> 
> 😆

@sizanic 
C'est la version de ludopotte pas la version officielle de la beta.Comme dit @TmpName c'est trompeur.
Je pensais que tu parlais d'une méthode pour installer officiellement la beta de vstream pas celle de ludopotte

Toi meme tu te pose des questions sur l'installation dune version non officielle et modifié qui est le coeur du débat sur cette conversation.
Et la tu me donne une autre méthode que celle que tu utilses car visiblement tu ne souhaites pas la partager.
J'ai remarqué ta modifié ton commentaire que j'ai cité dans mon message où tu dis clairement que tu utilise un addon pour télécharger la maj officielle de ton github.

Mais bon si tu veux pas la partager ya pas de souci mais ne fait pas passer une autre methode pour installer une version non officielle et modifié.

Tu a sûrement tes raisons pour pas la partager mais pas la peine de mentir 😌

**Comment by milkibreizh** [comment]
> Tu a sûrement tes raisons pour pas la partager mais pas la peine de mentir 😌

je comprends pas pourquoi il y a le lien #3108 (comment) et donc on a bien le liens
et ,au pire,je comprends de dire que c'est un menteur alors que c'est omettre une methode
qui est au plus l'explication d'un exemple de l'adon kodzi...**donc c'est pas un secret d'etat**
faut juste savoir lire et savoir utiliser google

>  donc je te serais reconnaissant si tu partager cette addon stp

il te donne la methode et toi tu l'insulte
merci d' etre un peu plus respectueux des raisons de chacun

**Comment by Che-debarras** [comment]
@milkibreizh ca devient agacant quand tu cherches a jouer le gentil toutou toujours prêt a me mordre lol
Puisque mon message ne s'adresse pas a toi,abstient toi de repondre et tu n'est pas @sizanic pour savoir si c'est une omission ou une réelle intention

Si tu avais lu son message avant que @sizanic ne le modifie tu aurais clairement compris qu'il a La technique personnelle pour installer vstream beta depuis un addon.

Mais apres ça modification de son commentaire , on pense qu'il parle de Kodzi mais ce n'est pas le cas surtout que @sizanic n'installe pas la version modifiée moddé de Lulopotte et d'ailleurs lui meme et @TmpName déconseillé d'installer le mod de lulopotte

Donc veux tu biens soit ne pas repondre soit d d'arreter de fayoter sans reflechir?
Ne repond pas a mes messages qui te sont pas concernés.

Sur ce qu'il partage ou pas sa technique ou que c'est un secret d'état ca me derange pas mais a mentir en modifiant son comm je trouve pas ça mature.

Sur ce débat clos.

**Comment by milkibreizh** [comment]
d d'arreter de fayoter sans reflechir
tu arrete de m'insulté stp encore une fois

et je signale que c'est pas la premirer fois que tu m'insulte   
ne serait qu'avec cette fameuse phrase ou tu t'es senti insulté et tu n'as pas cessé de ressassé le truc
on doit accepté tes remarques
mais 
tu acceptes aucunes remarques

j'ai des courrier long comme le bras que tu as effacé ou on voit que tu n'arrete pas de critiqué tous le monde 
Sur ce débat clos.

**Comment by Che-debarras** [comment]
> d d'arreter de fayoter sans reflechir
> tu arrete de m'insulté stp encore une fois
> 
> et je signale que c'est pas la premirer fois que tu m'insulte
> ne serait qu'avec cette fameuse phrase ou tu t'es senti insulté et tu n'as pas cessé de ressassé le truc
> on doit accepté tes remarques
> mais
> tu acceptes aucunes remarques
> 
> j'ai des courrier long comme le bras que tu as effacé ou on voit que tu n'arrete pas de critiqué tous le monde
> Sur ce débat clos.

Ce sera clos quand tu cesseras de te mentir a toi même et en arrêtant de me repondre quand je m'adresse a une autre personne, ta pas a intervenir dans une conversation qui ne te concerne pas.
Ainsi sans messages de ta part me concernant je te reprocherais pas de me manquer de respect donc garde le silence et chacun vie sa vie

Regarde a cause de toi, tu trolls et pollue ce sujet avec tes remarques.
Donc 🤐 ne repond plus et ne me mentionne plus et tout ira bien.

**Comment by sizanic** [comment]
@Che-debarras 
Puisque c'est à moi que tu t'adresse et que c'est moi que tu traites de menteur dès ta réponse sans chercher à comprendre.

Je te répond.

Déjà, voici comment apparait un message modifié : 
![image](https://user-images.githubusercontent.com/47307622/99415317-f78a4800-28f7-11eb-8856-dcc7d903e358.png)

Voici le message où je dis clairement que j'utilise un addon, il n'a jamais été modifié : 
![image](https://user-images.githubusercontent.com/47307622/99415995-aa5aa600-28f8-11eb-90da-ddb878365b6c.png)

Voici le message où je donne la méthode, il n'a jamais été modifié 
![image](https://user-images.githubusercontent.com/47307622/99416225-eaba2400-28f8-11eb-957e-0a07a6a1f1f8.png)

<br>

> J'ai remarqué ta modifié ton commentaire que j'ai cité dans mon message où tu dis clairement que tu utilise un addon pour télécharger la maj officielle de ton github.

Voici le message en question où tu cites mon commentaire : 

![image](https://user-images.githubusercontent.com/47307622/99416402-176e3b80-28f9-11eb-9235-cefc325d877a.png)

Et voici donc le commentaire en question : 

> J'utilise un addon qui installe directement depuis github (et cette technique est vraiment LA technique accessible pour des personnes qui ne maîtrisent pas l'outil informatique)

SAUF que tu en as oublié un bout, toute la première partie, le voici dans son intégralité et il n'a PAS SUBIT DE MODIFICATION : 

>Je trouve aussi ton patch pratique (le complet, j'ai récupéré le 8.2.35)
Car il est facile de le mettre en place :
J'utilise un addon qui installe directement depuis github (et cette technique est vraiment LA technique accessible pour des personnes qui ne maîtrisent pas l'outil informatique)


Je reformule en une seule phrase si tu n'arrives à comprendre la formulation précédente : 

**_J'utilise un addon qui installe directement depuis github, il est donc facile pour moi de mettre en place ton patch._**


Jamais je ne dis que j'ai une technique pour mettre à jour le patch officiel 🤔 

A quoi ça me servirait ! 
J'ai le code complet de vStream sur ma machine en local (toujours à jour, fichier par fichier) !


> Sur ce, qu'il partage ou pas sa technique ou que c'est un secret d'état ca me derange pas mais a mentir en modifiant son comm je trouve pas ça mature

Moi ce que je ne trouve pas mature, c'est de sortir des bouts de phrases d'un contexte et traiter les gens de menteur sans preuve !

Continue à être parano en croyant à tes propres mensonges, ça ne nous dérange pas.
(et pour ton info, que tu ne fasses plus le suivi nous importe peu, c'est même mieux)

**Comment by sizanic** [comment]
désolé @Arias800 
je me devais un droit de réponse.
