### ISSUE TITLE
Bug de recherche

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#3119]
Vstream version officielle et aussi beta du 22 11 2020
Nodi v18
kodi v 18.8 et v18.9

Samsung s9+ android9
  et box android kiii pro android 7.1

Bonjour a tous
Il ya un bug de la fonction de recherche , j ai essayé dans extreme down (pas encore essayé dans zt)

Donc lorsque je parcours la liste des mangas, il y a bien l episode  E854 de one piece
Mais lorsque je lance une recherche avec mots clefs : E854  ou one piece, il ne s affiche pas dans le resultat de recherche
![Uploaded with Directupload Image Sharer](https://s12.directupload.net/images/201123/v5slmvd7.jpg)

![Uploaded with Directupload Image Sharer](https://s12.directupload.net/images/201123/4m9cgtcf.jpg)
Resultat obtenu
![Uploaded with Directupload Image Sharer](https://s12.directupload.net/images/201123/2tbxi3ov.jpg)

![Uploaded with Directupload Image Sharer](https://s12.directupload.net/images/201123/to42a4kz.jpg)
Resultat obtenu
![Uploaded with Directupload Image Sharer](https://s12.directupload.net/images/201123/re6vac9w.jpg)

**Comment by Che-debarras** [comment]
Je crois que ce problème se généralise car c'est aussi le cas pour french strm par exemple et avant ça c'était wawacity

**Comment by Arias800** [comment]
Si tu tape le numéro de l'épisode ca ne marche pas sur le site, donc Vstream n'affichera rien. Par contre je viens de tester One Piece (sur extreme down) et ça fonctionne chez moi. Donc essaye avec la beta vu que j'ai corrigé la recherche hier d'extreme down, peut être que ca vient de la.

**Comment by falciatrice10** [comment]
Autre problème avec extreme down
En navigant dans le site (navigateur dolphin ou autre) dans la section Mangas et Animés/series vf , je trouve One Piece - FRENCH (E869 à 891)
Mais en parcourant la liste de tous les mangas (dans vstream) je ne  la trouve pas (meme en passant par le recherche)
[URL=https://www.directupload.net][IMG]https://s12.directupload.net/images/201123/qyvzb9qd.jpg[/IMG][/URL]

**Comment by Arias800** [comment]
@Che-debarras Essaye avec la beta, normalement tu devrais réussir a trouvé ce que tu cherches sur French-Stream.
@falciatrice10 C'est corrigé dans la beta.

**Comment by falciatrice10** [comment]
Je viens de télécharger la nouvelle beta, c'est pire qu avant 🤣🤣🤣
Dans extrême down, section animes
J ai lancé 2 recherches la premiere avec les mots clef "one piece" et la deuxieme mot clef "e854"
Et dans les deux cas ca renvoie une liste vide.

**Comment by Arias800** [comment]
Je t'es déjà dit que mettre "e854" ne sert a rien car ca ne marche pas sur le site. Sinon je pense que j'ai trouvé d'où ca venais et vient de le corrigé.

**Comment by Che-debarras** [comment]
> @Che-debarras Essaye avec la beta, normalement tu devrais réussir a trouvé ce que tu cherches sur French-Stream.
> @falciatrice10 C'est corrigé dans la beta.

J'ai toujours utilisé la beta mais je vais retester

**Comment by Arias800** [comment]
C'est parce que je vient de faire une modif.

**Comment by falciatrice10** [comment]
Je viens de tester la nouvelle bêta.
Je lance la recherche dans la section animés ,mot clef : one piece. Resultat : vide

**Comment by Che-debarras** [comment]
> C'est parce que je vient de faire une modif.

J'ai testé avant ta modif aucun resultalt pour frenchstrm 
Mais ta modification corrige le problème donc ok pour frenchtrm

Par contre pour ED ce n'est pas résolu il trouve rien

**Comment by falciatrice10** [comment]
En lançant la recherche avec mot clef : one. J'obtiens une longue liste de resultats.
Mais comme je l ai dit dans le commentaire precedent, avec comme mot ckef : one piece.  Resultat : liste vide

**Comment by Che-debarras** [comment]
> En lançant la recherche avec mot clef : one. J'obtiens une longue liste de resultats.
> Mais comme je l ai dit dans le commentaire precedent, avec comme mot ckef : one piece. Resultat : liste vide

Ça toujours été comme ça je pense,  j'ai toujours limité mes mots clefs à un seul mot et je prence le mot le plus pertinent 
Dans ton cas j'aurais plutôt cherche Piece et cliqué sur série et voire ce que ca donne
Mais mettre 2 mot clef ça fausse le résultat

**Comment by Arias800** [comment]
En faite le probleme c'est que certain site renvoie tout et n'importe quoi, c'est pour ca que dans certain fichier site de Vstream il y a ce code :

```
            if sSearch and total > 5:
                if cUtil().CheckOccurence(sSearch, sTitle) == 0:
                    continue
```
Pour faire court ca limite le nombre de résultats en recherchant les mots clés précis dans les titres. Et forcement Vstream peu avoir un peu de mal a certain moment (et c'est d'ailleurs encore plus vrai pour les animés). C'est quelque choses qui est sûrement améliorable.

**Comment by Che-debarras** [comment]
Jai supprime le cache et meme le dossier plugin video vstream etcopier coller le dossier plugin video vstream du zip dans le dossier Kodi.
Le tout grace au gestionnaire de fichier de Kodi

Et la j'ai les résultat sur ExtrmDownload et frenchstrm etc mais pas pour Cinemay 
Mais pour ce dernier j'ai toujours eu besoin de relancer la recherche pour qu'il apparaît ses resultats car je crois qu'il a été dit que cette source tarde a repondre 

Donc je pense que c'est résolu si on oubli ce pb de mot clef

**Comment by falciatrice10** [comment]
Autre problème avec extreme down
En navigant dans le site (navigateur dolphin ou autre) dans la section Mangas et Animés/series vf , je trouve One Piece - FRENCH (E869 à 891)
Mais en parcourant la liste de tous les mangas (dans vstream) je ne  la trouve pas (meme en passant par le recherche)
![Uploaded with Directupload Image Sharer](https://s12.directupload.net/images/201123/qyvzb9qd.jpg)

**Comment by Che-debarras** [comment]
Moi je le trouve sur ED

**Comment by Drakod** [comment]
yop,

le problème va j'usqua pastebin : aucun retour de recherche avec la beta , quand je tape un mot clé ya 0 retour 

=> par contre c'est ok avec l'officiel il trouve bien ce que j'ai demandé

**Comment by Che-debarras** [comment]
> yop,
> 
> le problème va j'usqua pastebin : aucun retour de recherche avec la beta , quand je tape un mot clé ya 0 retour
> 
> => par contre c'est ok avec l'officiel il trouve bien ce que j'ai demandé

La beta aussi le trouve si tu suis mon message précédent

**Comment by Drakod** [comment]
je parlais en général,  

aucun résultat pour n'importe quelle recherche avec la bêta,   ( pour pastebin)

alors qu'avec l'officiel sa fonctionne bien

**Comment by Che-debarras** [comment]
> je parlais en général,
> 
> aucun résultat pour n'importe quelle recherche avec la bêta, ( pour pastebin)
> 
> alors qu'avec l'officiel sa fonctionne bien

Ton problème parlais de ExtrmDown qui a le résultat de ce que tu cherches avec la beta avant les maj de Arias800

Pastebin est different des autres sources donc faut le différencier des autres qui sont des sources internet alors que pastebin est un fichier et donc la résolution n'est pas le même je suppose.

C'est pour ça que tu peux pas dire en general car pastebin est une exception mais les autres sources en beta fonctionne bien avant les maj Arias800.

J'utilise pas pastebin car c'est des liens où faut un compte et debrideur et il est long a afficher les résultats mais précise bien que c'est juste pastebin le souci

**Comment by sizanic** [comment]
@Drakod 
Le problème a été identifié et est en cours de correction.
Il affecte bien plusieurs sources, Pastebin y compris.

Car même si Pastebin ne repose pas sur la même architecture que les autres sources, la partie du moteur de recherche qui filtre les résultats est commun.

Même sans connaître ce détail, tu peux dire "en général" si tu le constates sur plusieurs sources.
Alors même que ton propos était de dire que toutes les recherches "en général" sur Pastebin ne retournent aucun résultat (et pas en général sur toutes les sources).


> le problème va jusqu'à pastebin

Merci d'avoir apporté ce détail supplémentaire sur la porté du problème.

**Comment by Drakod** [comment]
bonsoir , juste pour vous dire qu'avec la derniere version beta , on a toujours le probleme 

bisous 👍

**Comment by TmpName** [comment]
Du coup je suis un poil perdu
Recherche de "one piece" sur lequel des 2 sites ?
