### ISSUE TITLE
Bug avec la bêta

### ISSUE THREAD

**Issue by mickve** [Kodi-vStream/venom-xbmc-addons#3120]
**Décrivez le bug**
 Bonjour,Quand je fais une mise a jour via la bêta aujourd'hui je n ai accès à aucun site et quand je remet la mise a jour bêta que j ai faite hier ça fonctionne.

**Votre system**
 - OS:android 
-  Appareil beelink Gt king
 - Version Kodi 18.9
- Version:0.8.2

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Arias800** [comment]
Vu la grosse modification que je viens de faire c'est absolument pas étonnant. Il me faudrait des logs pour que je puisse voir d'où vient l'erreur.

**Comment by Che-debarras** [comment]
Je confirme aucune source ne s'ouvre ou vide
Meme bizarre ya le retour de voirhd qui devait etre supprimée non?

**Comment by Arias800** [comment]
J'ai corrigé la fonction des requêtes, normalement la grosse majorité des sources devrai s'ouvrir. Il y a certain site qui ne s'ouvrent pas que je vais corriger après la maj partiel (car sinon ca va faire un sac de noeud ingérable xD).

**Comment by Che-debarras** [comment]
> J'ai corrigé la fonction des requêtes, normalement la grosse majorité des sources devrai s'ouvrir. Il y a certain site qui ne s'ouvrent pas que je vais corriger après la maj partiel (car sinon ca va faire un sac de noeud ingérable xD).

Merci sinon as tu regardé si tu as le temps le lien www1 hds fm pour hdss to ?
Je pense qu'il n'a pas CF et ressemble a hdss avec film et serie bien a jour 
Qu en dit tu?

**Comment by yodidon** [comment]
Pour www1 hds fm de mon coté marche pas ..

**Comment by Che-debarras** [comment]
> Pour www1 hds fm de mon coté marche pas ..

Effectivement il ne marche plus alors que je venais de regarde un film juste avant de donner le lien
Ben tanpis désolé et l'autre lien il marche pour vous car moi oui

**Comment by yodidon** [comment]
c'est quoi comme url l'autre ?

**Comment by Che-debarras** [comment]
> c'est quoi comme url l'autre ?

Hds.fm refonctionne 
L'autre c'est https //v1 .hds-s treaming .tv
Les 2 sont des remplacements potentiel pour kaydo qui a disparu et na pas de nouveaux url sauf des url avec Cloudfare
Donc je propose ces 2 la pour le remplacer

**Comment by milkibreizh** [comment]
j'ai deja fait la source wnw.hds-stream.tv qui est compatible avec d'autres url
comme https://v1.hds-streaming.tv/ au niveau du code ya juste l'url a changer
le code est stable depuis plus de deux sauf que des fois il arrive que les sources soient sous  cf
et ya q'un seul host downparadise c'est un peu l'inconvenient de cette source bien que les liens
ne soient pas si pourris que cela

**Comment by Che-debarras** [comment]
@milkibreizh exactement ce que je pense c'est pour ca que l'autre lien hds.fm est plus intéressant mais aujourd'hui il deconne tantot il fonctionn tantot non.

Donc ces les 2 clones de kaydo qui nont pas ou rarement CF sinon ya hds.lc qui lui a CF tout le temps.

Donc j'espère que hds.fm cessera de bugguer d'ici demain

**Comment by milkibreizh** [comment]
pour hds.fm j'ai pas eu le temps de la regarder mais si c'est encore un site avec downparadise
il devrait pas avoir grand chose a faire pour la rendre compatible avecc le code w___nw.hds-stream.tv 
autrement il faut tout se taper tout un nouveau code

**Comment by yodidon** [comment]
C’est bien down paradise

**Comment by milkibreizh** [comment]
down paradise oui c'est cela ya pas de difficulté pour le resoudre c'est du genre '/v/','/api/source/'

je peux toujours mettre w___nw.hds-stream.tv je l'ai pas testé depuis longtemps si cela se trouve
ya plus cf depuis longtemps

**Comment by yodidon** [comment]
En tout ça les regex pour hds sont à refaire. Après les autres je sais pas à tester

**Comment by milkibreizh** [comment]
> En tout ça les regex pour hds sont à refaire. Après les autres je sais pas à tester

mais c'est pas hds...ya pleins de site qui sont ressemble mais celles ci contients des films que kaydo ne contient pas
et inversement  et surtout tu vois tout de suite si c'est pareil avec les hosters finaux

**Comment by yodidon** [comment]
Oui je sais bien

**Comment by yodidon** [comment]
Template  de wp

**Comment by Che-debarras** [comment]
@milkibreizh 
J'ai passé un peu ma journée a trouver le nouveau url de kaydo et j'en ai trouver plusieurs qui ressemblent 
Mais j'ai retenu 4 url qui sont mis a jour récemment avec les episodes et film d'aujourd'hui 
Car effectivement le kaydo qu'on avais sur vstream été un clone du vrai kaydo je pense et qui est moins fourni
Mais depuis 2 autres sont apparus , les 2 que j'ai donné url qui semble eux mieux fourni et pas de cloudfare apparemment.
Les 2 autres qui sont très  réactifs pour les dernlers films et series ont cloudfare.

Voila donc on ne peut que prendre des clones sans CF et ya ces 2 là qui sont potable par rapport a tous ce que j'ai pu voir.

**Comment by milkibreizh** [comment]
@Che-debarras 
je sais pas pour l'url hds.fm j'ai jamais reussit a me connecté correctement
quand cela marche l'acces au page est rapide...car j'ai  regardé l'historique de ce site dans le passé
j'ai pas trop trop confiance mais l'historique ne veux rien dire elle peu s'averer stable apres

**Comment by Che-debarras** [comment]
> @Che-debarras
> je sais pas pour l'url hds.fm j'ai jamais reussit a me connecté correctement
> quand cela marche l'acces au page est rapide.?..car j'ai regardé l'historique de ce site dans le passé
> j'ai pas trop trop confiance mais l'historique ne veux rien dire elle peu s'averer stable apres

Oui c'est comme kaydo vraiment un clone j'ai eu aucun mal a part les pubs vu que sur navigateur j'ai pas de bloqueur 
J'ai vu que ya les toutes dernières épisodes et film 
Mais des qu'il refonctionne je te préviendrai

**Comment by milkibreizh** [comment]
> Template de wp
exact host idem vidplayer

**Comment by milkibreizh** [comment]
filmoflix je sais que j'ai dans ma liste mais je sais plus les resultats que j'avais sur celle ci
car je teste la faisabilité ,les mises a jours,et le % de lien mort avant de faire les sources

**Comment by Che-debarras** [comment]
Ok @milkibreizh apparemment tu es sur tout les fronts.
D'après ce que jai vu les liens semblent marcher et plusieurs choix de host
Et ya les derniers episodes et film comme Ip man4 ou s17e03 de grey ou s2e08 de warrior

En tout cas merci d'avance si tu réalises ces sources

**Comment by milkibreizh** [comment]
oui mais j'ai pas fait la source filmoflix et je crois que j'ai fait aucun teste je peux donc m'avancé en disant que je peux la faire

**Comment by yodidon** [comment]
Je mets en standby je verrais ce qu’il reste à faire

**Comment by milkibreizh** [comment]
filmoflix a priori ya pas de piege pour les hoster la voie semble libre

**Comment by milkibreizh** [comment]
@yodidon 
tu veux faire la source filmoflix sinon je commence a la fais ce soir....je te mets la pression^^

**Comment by yodidon** [comment]
Vas y pas de soucis

**Comment by milkibreizh** [comment]
oui cela craint si je prends tout pour ma pomme
autremment tu peux faire dans ce cas la 4k..car celle ci est tjrs en stand by

**Comment by yodidon** [comment]
Non te prends pas la tête fais fais

**Comment by milkibreizh** [comment]
je te parlais de la 4k je crois avoir retrouvé une partie de ton code je crois qunad tu l'as commencé cela t'intersse

**Comment by yodidon** [comment]
Oui je regarderais ça

**Comment by milkibreizh** [comment]
Ok autrement pour skyanime je crois que l'url que l'on retrouve et qui est valide correspond en faite
a l'url que l'on rentre manuellement c'est pour cela qu'il y a reference sur celle ci,autrement si tu reinitialise
le navigateur tu n'obtiens plus les url valident sans accent

**Comment by milkibreizh** [comment]
> Ok @milkibreizh apparemment tu es sur tout les fronts.

j'allais oublir....... c'est arias800 qui est plutôt sur tous les fronts ces temps-ci ... un gand merci

**Comment by Che-debarras** [comment]
> 
> > apparemment tu es sur tout les fronts.
> 
> j'allais oublier....... c'est arias800 qui est plutôt sur tous les fronts ces temps-ci ... un gand merci

Non pour moi @Arias800 est a l'avant-poste qui prépare le terrain pour kodi 19 et combattre ses bugs et 😌

Hds . Fm refonctionne et je dois dire la qualité y es et pas j'ai eu droit qu a une seule pib3en cliquant Play et la video se lance quasi en meme temps avec la pub 
![Screenshot_20201123-211938_Samsung Internet](https://user-images.githubusercontent.com/44464129/100011446-0aa68780-2dd2-11eb-8714-89639e74a464.jpg)

**Comment by Che-debarras** [comment]
Un autre qui disparair des radars lol french-strm qui semble peut etre avoir changer de url pour french-stream.lol. 
Ya vraiment une chasse au site de strmng ces temps ci.

**Comment by Che-debarras** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3106#issuecomment-733262036

Ya d autre bugs de la beta #3106 donc la disparition des "é" de tous les mots

**Comment by sizanic** [comment]
@Arias800 
ce qui fait sauter les accents, ce qui est génant pour les regex entre autres.

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/b7731f107c1ddc4c022af6fd972950d7109a1776#commitcomment-44509583

**Comment by milkibreizh** [comment]
@Arias800 
j'ai des soucis avec les versions recente, sur la source filmoflix je suis obligé de changer le fichier requesthandler.py
pour qu'elle fonctionne mais c'est juste pour une seule requete celle qui donne acces au host j'ai pas fait attention en creant la source..si j'avais su j'aurais attendu
et pareils la source animecomplet marche bien mais seulement sur des beta d'une semaine
(je sais pas trop l'origine par contre j'essayerais d'appronfondir le truc)

**Comment by Che-debarras** [comment]
@milkibreizh 
Pas de souci si frenchmanga c'est pas possible surtout ya que du Netu donc il sera pas lisible.

Merci

**Comment by milkibreizh** [comment]
de tout toute facon c'est plus le moment de faire de nouvelle source
il faut résoudre le probleme du wrapper des requetes de vtsream qui a changé

**Comment by yodidon** [comment]
Je viens de finir 4K pas essayer avec la nouvelle bêta ....

**Comment by Che-debarras** [comment]
> de tout toute facon c'est plus le moment de faire de nouvelle source
> il faut résoudre le probleme du wrapper des requetes de vtsream qui a changé

Mais j'ai remis une ancienne version de beta donc ya pas ce pb de wrapper
Si vous voulez pour tester vos sources les partager ici et on vous fait un retour

**Comment by milkibreizh** [comment]
non mais tu peux essayer comme meme j'ai eu le souci que sur une seule requete...j'ai pas eu de bol
mais j'ai plus aucune serie du coup et j'arrive pas 
quand je disais c'est pas le moment de faire des sources c'est avec la version actuelle

**Comment by yodidon** [comment]
Merci @Che-debarras elle fonctionne sur l’avant dernière bêta il faut que je test juste sur la nouvelle

**Comment by milkibreizh** [comment]
@Che-debarras 
et donc tu n'as pas de souci sur android avec filmoflix ?

**Comment by yodidon** [comment]
Par contre effectivement pas testé sur androïde

**Comment by milkibreizh** [comment]
yodidon si ta source fonctionne sur le recente c'est parfait...

**Comment by Arias800** [comment]
Le système de requêtes va rester comme il ait, du moins dans les grandes lignes, car ça va nous faciliter la vie dans le future. Mais oui il est pas tout à fait fini sous Kodi 18.

**Comment by milkibreizh** [comment]
@Arias800 
non mais j'ai resolu mon probleme il faut juste completer un hearder sur cette version de la requete
comme je le precisais j'avais pas fait toutes les possibilité de la requete
fallait ajouter **'Content-Type', 'application/x-www-form-urlencoded'**

**Comment by sizanic** [comment]
> Le système de requêtes va rester comme il ait, du moins dans les grandes lignes, car ça va nous faciliter la vie dans le future. Mais oui il est pas tout à fait fini sous Kodi 18.

@Arias800 
Sauf qu'on devait sortir une mise à jour en 18.
Et maintenant on ne peut plus, trop de régression 🤔 

Alors qu'il n'y a que ce probleme de décodage à régler pour python2 :

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/b7731f107c1ddc4c022af6fd972950d7109a1776#diff-c915646327fbdbd88c93755864ce45b0fb085e039a67f65f02e100956e850668


```
#Python 2 a besoin de ce decodage.
            try:
                sContent = sContent.encode('ascii', 'ignore').decode('ascii')
            except:
                pass
```

python a bien besoin d'un décodage spécifique mais il semblerait que ce ne soit pas celui-là 😄

**Comment by Arias800** [comment]
C'est une maj partiel qui est prévu, et elle ne concerne que les sites et les hosters. Donc ce problème d'encodage ne va pas exister dans la maj (vu qu'il va garder les fichier local pour le coeur de Vstream).

**Comment by sizanic** [comment]
Je pense que la maj partielle contient tous les fichiers modifiés, sauf qu'il faut l'installer à la main (lien dans le menu vStream) plutôt que par un déploiement automatique.

Bien que le tuto de la MAJ précise : _On se limite aux Sources et Hosters._
Je ne vois pas comment techniquement cette imitation est mise en oeuvre 🤔 


si je regarde par exemple la mise à jour partiel de 0.8.1 à 0.8.01
par le fichier 
https://api.github.com/ ... /compare/0.8.0...0.8.01

Dans la section [files]
je retrouve en plus des sources et des hosts  : 
```
"filename": "plugin.video.vstream/resources/lib/cloudflare.py",
"filename": "plugin.video.vstream/resources/lib/aadecode.py",
"filename": "plugin.video.vstream/resources/lib/comaddon.py",
etc..
```

Et dans le code checkdownload(self): , il n'y a pas de recherche /sites/ ou /hosters/ dans le nom des files, ce qui pourrait les exclure.

**Comment by milkibreizh** [comment]
j'ai remarque que des sources avait des soucis avec getRealUrl()
ceux que j'ai vu son corrigeable par exemple il est tjrs possible de recuperer le lien du host dans le fichier
et d'autres utilise getrealurl pour generer une requete avec urlmainresultat ya des bugs
mais je pense qu'il faut au moins voir comment faire marcher getreal plutot
que de refaire toutes les sources sans getRealUrl()

**Comment by Arias800** [comment]
Il y a tout les fichiers qui sont mis dans la mise à jour, mais normalement Vstream est censée ne remplacé que les fichiers site et hoster. Le code a toujours fonctionné comme ça et il n'y a pas de raison que ça n'est changer (ce code existait déjà avant que je participe a Vstream donc j'ai jamais cherché comment il fonctionnait).

**Comment by LordVenom** [comment]
Oui j'avais fait la modif logiquement la mise a jour partielle contient tous les fichiers la limitation site / hoster faisais plus chier qu'autre chose.

**Comment by sizanic** [comment]
La seule vérification qui est faite pour filtrer les fichiers à mettre à jour est : 

`if 'plugin.video.vstream' in i['filename']:`

donc je ne suis pas si sûr que toi sur le "est censé ne remplacer".

Moi aussi le code existait avant, mais il me semble avoir déjà vu du code que j'avais ajouté en dehors des sources qui s'était installé lors d'une mise à jour mineure.

**Comment by sizanic** [comment]
> Oui j'avais fait la modif logiquement la mise a jour partielle contient tous les fichiers la limitation site / hoster faisais plus chier qu'autre chose.

Merci de ta réponse, j'arrête alors de rechercher.
J'en était à deux ans en arrière sur les modifications :)

**Comment by LordVenom** [comment]
c'est les info qui date la sur le coup ton résonnement était bon 

si tu compare avec l'api github 0.8.0...0.8.01 et que y a pas de filtre dans le code y a forcement tout :)

**Comment by Arias800** [comment]
D'accord, donc j'avais loupé des morceaux d'information xD

**Comment by Che-debarras** [comment]
> @Che-debarras
> et donc tu n'as pas de souci sur android avec filmoflix ?

Sile seul souci c'est que tout les dossiers des host pour tout les series sont vide 
Ya que les films où tout est ok

**Comment by milkibreizh** [comment]
je peux pas tester je connaissais pas trop le site et c'est  la premiere fois que je le vois sous CF a l'instant
je l'aurais pas suspecter  j'ai ete sur le site une 20 en de fois depuis 1 ou 2 mois
normalement cela marche avec la nouvelle requete..a moins que je me sois embrouillé avec les versions lors des testes
donc je verrais plus tard

**Comment by Che-debarras** [comment]
> je peux pas tester je connaissais pas trop le site et c'est la premiere fois que je le vois sous CF a l'instant
> je l'aurais pas suspecter j'ai ete sur le site une 20 en de fois depuis 1 ou 2 mois
> normalement cela marche avec la nouvelle requete..a moins que je me sois embrouillé avec les versions lors des testes
> donc je verrais plus tard

Oui je viens d'aller voir sur navigateur ya CF effectivelent et j'ai testé sur Vstream, on n'a plus accès à la source, ils ne S'ouvrent pas.
Esperons qu'il retire ce CF
Sinon tu peux toujours faire  french strm.lol ou hds.fm si tu a du temps et je suis dispo sur discord pour tester tes fichiers

**Comment by milkibreizh** [comment]
> Sinon tu peux toujours faire french strm.lol ou hds.fm 

ok si elle sont faisables je vais les rajouter a ma liste des sites  a faire
mais est ce que tu connais bien le site et a tu testé le pourcentage de liens qui marchent
et j'imagine qu'elles on des films recents/serie
en tous cas je ne les ferais pas aussi rapidement que filmoflix car j'ai pas trop le temps ces temps ci
 sinon peu être que cela interréssera @yodidon  de les faire

**Comment by Che-debarras** [comment]
@milkibreizh 
Pour les series et film que je regarde je n'ai jamais eu de souci
Ces 2 sites sont comme les 2 deja sur vstream (frenchstrm et kaydo)
Sauf que ils ont soit plus de host donc plus de chance de visionner 
Mais surtout il sont plus réactifs pour les derniers films et series

Et puis sur vstream ya des sources qui ont des liens morts ou plus mise a jour où qu'un seul host qui est d'ailleurs Netu.

Sur un autre comm j'ai mentionné plusieurs sources qui ne fonctionne pas ou plus (+ les sites avec CF) car sources qui S'ouvrent pas ou vides.

Donc c'est pour cela que je te remercie toi et yodidon de  veiller au renouvellement de ces sources

**Comment by sizanic** [comment]
Correction sur la Beta pour le problème général introduit récemment.

@Arias800
du coup, ma correction n'est sans doute pas optimisée pour python 3, mais comme je n'ai pas suivi les règles à mettre en place pour cette compatibilité, je te laisserai regarder.

**Comment by Arias800** [comment]
Logiquement Netu devrai pourvoir refonctionner sur Vstream, faut juste que j'essaie de passer le captcha et que je comprenne l'encodage qu'ils le utilisent xD

**Comment by Che-debarras** [comment]
@sizanic 

Ta modification pour request handler ne fonctionne toujours pas il fait disparaître les hosts
Je dis bien fait disparaître car l'ancien fichier py de 13.49kb fonctionne parfaitement

**Comment by sizanic** [comment]
J'ai ouvert quelques sources et il y avait des hosts.
Je veux bien un exemple d'une source où les hosts ont disparus.

**Comment by Che-debarras** [comment]
> J'ai ouvert quelques sources et il y avait des hosts.
> Je veux bien un exemple d'une source où les hosts ont disparus.

Je retire ce que j'ai dis, j'ai réinstallé fraîchement ta modif et les hosts sont là
Je viens de m'apercevoir que j'étais sur 4kstrm de Yodidon 
Il marche avec l'ancien requesthandler mais pas avec le nouveau.

**Comment by yodidon** [comment]
A mince et j’ai pas suivie ce qui avait changé...

**Comment by Che-debarras** [comment]
> A mince et j’ai pas suivie ce qui avait changé...

J'allais justement t'écrire pour la modif de requesthandler qui rend tes dossiers hosts vides.
Et apres plus de vérification meme avec l'ancien,  bien que j'ai quasi tout les host il se peut qu'il en manque
Ex Burden of Truth s03e01 dossiers vides mais bien present sur le navigateur mais tout bon les autres episodes

Mais bon avec le nouveau fichier de @sizanic ya plus aucun host

**Comment by milkibreizh** [comment]
> A mince et j’ai pas suivie ce qui avait changé...

comme je le précisais il faut faire gaffe au header et  **getRealUrl() est inutilisable**
pour avoir les hosts du site 4kstrm je sais que l'on peu utiliser cette fonction c'est peu être pour cela que ta
source ne fonctionne pas

**Comment by Che-debarras** [comment]
> @yodidon
> 
> > A mince et j’ai pas suivie ce qui avait changé...
> 
> comme je le précisais il faut faire gaffe au header et **getRealUrl() est inutilisable**
> pour avoir les hosts du site 4kstrm je sais que l'on peu utiliser cette fonction c'est peu être pour cela que ta source ne fonctionne pas

Sa source marche avec l'ancien requesthandler depuis hier et meme maintenant ca marche plutôt bien mais ya comme une incompatibilité avec le nouveau fichier.

**Comment by Arias800** [comment]
getRealUrl() c'est un oublie de ma part, après que la requête sois faites il faut rajouter : 
`self.__sRealUrl = oResponse.url` dans requestsHandler. D'ailleurs si ça ce trouve requests prends la redirection sans utiliser getRealUrl(). Donc faut tester sans pour voir.

**Comment by milkibreizh** [comment]
dans le def __callRequest(self): j'ai mis en effet

> 159 sContent = oResponse.content
> 160 self.__sRealUrl = oResponse.url
> 

et cela semble marcher pour certains cas qui ne marchais pas avant
pour avoir l'hoster..apres j'ai bricolé j'ai mis la valeur ou elle me semblait un peu pres justifiée

**Comment by sizanic** [comment]
@Arias800 
Je me demande si il n'y a pas une erreur ici : 

![image](https://user-images.githubusercontent.com/47307622/100399986-2ff6f800-3055-11eb-8d72-176b0672f2c5.png)


La variable 'e' existe-t-elle à la ligne 201, car elle n'est initilisée que si on rentre dans l'exception à la ligne 172.
Je me trompe ?
Car le 'if' (l.190) n'est pas dans le corps de l'exception 🤔

**Comment by Arias800** [comment]
C'est vrai que c'est un morceau de code que j'ai oublié de modifier.

**Comment by Che-debarras** [comment]
Sujet a fermer je  crois non?
Problème résolu

**Comment by Arias800** [comment]
Vu qu'il n'y a plus de réponse je vais partir du principe que c'est corrigé.
