### ISSUE TITLE
Hebergeurs (ZT, Zu, Planet streaming...) inaccessibles

### ISSUE THREAD

**Issue by Rikikisifreddo** [Kodi-vStream/venom-xbmc-addons#3121]
Bonjour,
Je suis sur fire stick, Android, kodi 17,6 (ou 18,9), vstream et urlresolver à jour. Sans faire aucun changement, je n'ai plus accès à la majeure partie des hebergeurs (Erno ou "aucune information" ou "fichier introuvable lorsque je clique sur le fichier voulu). C'est que chez moi ou i'y'a à nouveau un soucis général ?

**Comment by bast69** [comment]
Bonjour, 
De mon côté c'est papstream qui n'est plus fonctionnel.

**Comment by Che-debarras** [comment]
> Bonjour,
> De mon côté c'est papstream qui n'est plus fonctionnel.

Pensez a vérifier sur un navigateur avec dns changé,  vous verrez que le problème viens du site et non de vstream

Lire aussi les autres sujets sur les sources qui fonctionne qu avec Cloudfare que vstream et kodi ne prenne pas en charge.

Apres ces 2 vérifications,  vous constaterez que vstream n'y est pour rien et cela permet au devs de pas etre surcharger de demande.

Les sites ont des soucis a cause des plaintes si vous lisez les articles DMCA en fin de page de google donc ils disparaissent pour changer de url ou de protection et reviennes plus tard.

**Comment by Che-debarras** [comment]
Sujet a fermer je pense non?

**Comment by bast69** [comment]
J'ai changé de DNS, essayé avec différent appareils et différent DNS. Le problème sur papstream est toujours présent

**Comment by TmpName** [comment]
papystrm est out pour moi.

**Comment by Che-debarras** [comment]
@bast69 @TmpName 

Ne le prenez pas mal mais pourquoi vous ne vérifiez pas sur le navigateur si le site est pas lui meme HS?

Je l'ai précisé pourtant des le début en reponse au 1e comm mais malgré cela ça insiste a reporter ce faux bug

Je sais pas si c'est de la fainéantise a aller voir sur un navigateur ou une mefiance mais je trouve cela bizarre de reporter des bugs sans faire un minimum d effort

![Screenshot_20201128-131009_Samsung Internet](https://user-images.githubusercontent.com/44464129/100515333-9ece7100-317b-11eb-8a39-0147f545b572.jpg)
![Screenshot_20201128-131043_Samsung Internet](https://user-images.githubusercontent.com/44464129/100515336-9f670780-317b-11eb-9368-eedb5a4056ad.jpg)
![Screenshot_20201128-131542_Samsung Internet](https://user-images.githubusercontent.com/44464129/100515374-eead3800-317b-11eb-849b-612a9a42425f.jpg)

Avec Dns ou sans le site est HS , que ce soit wifi ou 4g site hs

Donc si le site est HS il le sera sur vstream.

**Comment by bast69** [comment]
@Che-debarras je pensais que mon dernier message serait compréhensible 😅
C'est bien le site qui est down

**Comment by TmpName** [comment]
Lol, quand je disais qu'il etait out, je voulais dire sur navigateur, tu m'as deja vu reclamer ou un correctif sur une source, ou prevenir d'un mauvais fonctionnement  ?

**Comment by Che-debarras** [comment]
J'avoue que pour toi @TmpName cela m'a paru bizarre effectivement 
J'ai pas fait gaffe sur le coup des pseudo mais plus des messages

Car dans vos 2 messages vous dite pour moi au lieu de pour tout le monde
Ou meme vous ne mentionnez pas "sur le navigateur donc cela est confus 
On comprend plus que cest pour votre config que cela ne marche pas

C'est comme le souci de uptobox et la résolution des videos
Ca prend 1 minute de vérifier sur navigateur avec son tel pc ou tablette
Et de voir que on a pas accès a toute les résolutions de la video

Ou les problemes de cloudfare qui est mentionné depuis des mois
Mais les gens continuent de rapporter l'inaccessibilité de ces sources

J'ai l'impression que les gens des qu'ils ont un pb le poste ici directement 
Et laisse les devs se démerdez a trouvé d'où vient le probleme 
Et perdent leur temps a s apercevoir que le problème viens du site 

Les gens ne renseignent meme plus leur config pour cibler le probleme

Désolé de vous embêter avec ça mais si les gens ne font pas un minimum d'efforts pour que les devs puissent se focaliser sur les vrais problèmes alors ils ne sont pas très reconnaissants et surcharge les demandes inutilement

**Comment by bast69** [comment]
@Che-debarras  Mon domaine de prédilection est le réseau, du coup je fais tous les tests en amont et j'attends quelques jours pour être sûr que cela ne soit pas temporaires au niveau du site web :)
