### ISSUE TITLE
Nom d'équipe vStream

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#3122]
![Sans-titre-1](https://user-images.githubusercontent.com/4380112/100247521-b5d25080-2f3a-11eb-8886-8eea58363165.png)

![Sans-titre-2](https://user-images.githubusercontent.com/4380112/100247566-be2a8b80-2f3a-11eb-810f-964446590532.png)

Va falloir vous trouver un nom de team ou quelque chose la les pseudo finirons par plus passer lol. Mon idée c'est un nom de team pour l'auteur général et dans l'information la ont peux mettre tous les pseudo.

**Comment by sizanic** [comment]
Beaucoup de nouveaux développeurs nous ont rejoint récemment dans notre aventure,
et ils méritent tous d'être cités pour leur travail.

L'idée est de lister tout le monde dans la fenêtre d'information (deuxième écran ci-dessus).

Et dans le première écran, nous retirons les noms pour proposer plutôt un nom de Team !


vStream est quand même une extension de référence !

Et nous ne sommes pas identifié comme équipe par la communauté KODI 🙀 

A vos propositions !!

**Comment by Che-debarras** [comment]
Je pense le plus simple c'est de créer un pseudo avec les initiales de chacun:

1. Ca donnerait S.K.A.R.Y T.V Team
2. Ou Un pseudo : K. T.R.A.V.Y.S  & Co (Co pour les prochains collaborateurs) 
3. Ou simplement : vTeam qui ressemble a vStream
4. Ne peut on pas juste garder VSTREAM genre : vStream Team

Mes propositions ne sont pas originales mais A t'il vraiment besoin d'un pseudo car votre réputation n'est plus à faire.
Je pencherais pour le 4 tout simple

**Comment by sizanic** [comment]
Avec 1 et 2 on ce confronte au même problème de liste qui grandit.
3 - vTeam, j'y avais pensé aussi 😄 car ça se rapproche mais finalement c'est aussi son inconvenant que ce soit trop proche.
4 - "vStream Team", en effet, vu qu'il n'y a qu'un seul produit de développé 🤔  mais ce n'est pas vraiment un nom du coup.

Personnellement, je ne suis pas pour qu'on trouve absolument un nom (en effet, la réputation de l'addon nous précède 😄 ).
Un nom de team est vraiment nécessaire lorsqu'il y a plusieurs produits.

Mais si quelqu'un trouve un truc qui accroche vraiment, à voir ...

**Comment by Che-debarras** [comment]
@sizanic 
Exactement vous n'avez qu'un seul produit et de tres bonne reputation

Je pense le 4 conviendrait car c'est general surtout que le nombre de devs évolue

Le 1 et 2 ne grandit pas car ce sont les devs qui sont la depuis tres longtemps  et qui apparaissent souvent en activité dans le github (les autres dans la description (et si ça grandit ya "& Co" que vous détaillez dans la description)

Le 3 c'était juste pour raccourcir la longue liste de contributeurs car comme avec le 4, on generalise en incluant les anciens comme les nouveaux dans la team qui sont détaillées dans la description.

Je pense que les mieux placés pour trouver un nom de team c'est les devs qui y travail ou vous mettre d'accord pour limiter les noms a 2 max:

J'aurais mis Arias800 et Sizanic car vous etes les 2 les plus actives sur le github (et les autres dans la description)

NB: cela ne minimise pas l'implication des autres.

**Comment by yodidon** [comment]
De mon côté je serais plus pour garder l’historique, enfin celle que je crois connaître et l’idée du 100% français, ce qui pourrait donner :
• LV-collectif ou collectif-LV
• LV-groupe ou groupe-LV
Sans plus de conviction 😅

**Comment by sizanic** [comment]
Si je comprends bien ta proposition :
100% fr -> "Collectif" au lieu de Team.
LV -> pour LordVenom ?

**Comment by yodidon** [comment]
On ne peut rien te cacher @sizanic  😊

**Comment by Che-debarras** [comment]
@yodidon c'est plus un souci esthétique sur la longueur que sur l'originalité du nom.
J'ai installé plein d d'addon et je retient pas le nom des devs saif vstream car je suis vitre github
Donc ce qui ont vstream et le mette a jour connaissent les noms sans meme regardé les infos sur l'addon 
Donc peut importe le nom ou les noms a mettre cela ne sera pas d'une grande utilité voire ni lu retenu 

Je suis dac avec toi pour l'historique mais les 4 cités dans mon précédent mails contribuent énormément et sur ces 4 là je crois le plus ancien c'est @sizanic donc je pense mettre que son nom est suffisant avec ou pas Arias800

**Comment by yodidon** [comment]
@Che-debarras a mon avis et seulement pour dire ce que je pense être , aucun des Debs ne le fait pour avoir son nom en tête, et reprendre les fondamentaux me paraît le plus normale et cohérent.
Que personne ne retienne oui je suis d’accords, mais que chaque dev se souvienne c’est juste l’idée

**Comment by yodidon** [comment]
Et séparer l’équipe du nom de l’admin prends tout son sens si on se rapproche du fondement de cet addon

**Comment by LordVenom** [comment]
Perso je serais partis sur un truc qui rappelle github (Kodi-vstream) (Github-addon-vstream) (GitStream) (GitVstream)  mais j'ai pas plus d'idée.

**Comment by Che-debarras** [comment]
@yodidon 
Tout a fait dac avec toi sur l'historique afin que les nouveaux devs savent de qui est a l'origine de l'addon et dans ce sens oui il faut séparer le nom de l'addon de celui des devs

Donc je dirait qu'on mette les 2/3 noms les plus actifs ou les 2/3 les plus anciens cela réduirait le nombre des noms

Mais je suis ok finalement avec toi qu'il faut mettre les devs principals et initiales du projet afin de pas se sentir se faire réapproprier leur projet ni oublier a qui ont le doit ce magnifique addons.

👍

**Comment by Che-debarras** [comment]
> Perso je serais partis sur un truc qui rappelle github (Kodi-vstream) (Github-addon-vstream) (GitStream) (GitVstream) mais j'ai pas plus d'idée.

Je pense que mettre "venom-vstream-addon" permettra de chercher sur Google le github plus facilement

**Comment by LordVenom** [comment]
Non ça me gène d'avoir mon pseudo la tout seul un nom d'équipe a l'arrache peux importe c'est juste que cette ligne de pseudo c'est vraiment moche.

**Comment by Che-debarras** [comment]
> Non ça me gène d'avoir mon pseudo la tout seul un nom d'équipe a l'arrache peux importe c'est juste que cette ligne de pseudo c'est vraiment moche.

C'est pas ton nom,  c'est le nom du github , l
Et le tien cest LordVenom pas venom 🙃

**Comment by TmpName** [comment]
Moi je trouvais marrant de prendre les initiales, mais faudrait tout refaire a chaque nouveau.
Donc je prendrais un truc fixe et standard pour la Team, vu que comme dit en debut, on peut mettre plus de pseudos dans les infos.

**Comment by sizanic** [comment]
Je vote aussi pour un truc comme "venom-vstream-addon" 
qui est dérivé du vrai repo "Venom Xbmc Addons".

- ça permet une cherche sur Google
- il y a une petite référence au créateur initiale (ce n'est pas "LordVenom " en entier)

Mais est-ce que le 'v' de vStream n'est-il pas déjà une référence à Venom 🤔

**Comment by Che-debarras** [comment]
@TmpName 
Pour les initiales faut juste prendre les initiaux au projet et dans la description expliquer les initiales  suivit des autres collaborateurs 
Mais pour pas vexer qui sera pris ou non comme initiales je pense que prendre le nom du github c'est plus simple

@sizanic 
Je me suis tromper car c'est venom-xbmc-addons que je voulais ecrire ppur que les gens fasse le lien avec le github
(Je sais pas pkoi jai mis vstream au lieu de xmbc)

V pour Venom honnêtement qui le sais a part ce qui vous suit depuis le debut? J'ai tjrs pensé que c'était pour video au lieu de videoStream.

Donc je pense que clairement mettre Venom en entier comme dans venom-xbmc-addons mettra plus le doute  sur le createur

**Comment by sizanic** [comment]
Pour le V de vStream, c'est seulement maintenant que je me pose cette question, je n'y avais jamais pensé avant non plus 😄 



Pour venom-xbmc-addons / venom-vstream-addon
Je me suis douté que tu t'étais trompé car je n'ai pas vu l'erreur tout de suite.

Et dans un premier temps, je me suis dit que c'était pas mal, car XBMC sonne un peu vieux.
Et même avec venom-vstream-addon, on se retrouve ici par une recherche google.
Mais ce n'est pas vraiment un nom de team (ou de collectif 😉 ), ça dit juste que vStream est un addon qui vient de venom.


Donc, quitte à ne pas prendre un nom d'équipe, autant prendre le vrai nom du repository github : **venom-xbmc-addons**

**Comment by LordVenom** [comment]
Ha je suis démasquer, j'ai pas chercher plus loin que la première lettre de mon pseudo mais pour ma défense ça marchait bien vStream :)

Ben si personne ne trouve de nom d'équipe oui le nom du github c'est une bonne solution pour une recherche sur google effectivement. peux être rajouter faire un truc genre Github(venom-xbmc-addons).

**Comment by Che-debarras** [comment]
@sizanic 
Oui cest pas pas un nom de team mais c'est le nom de la où se trouve la team
Mettre les noms sert a savoir qui a fait l'addon mais aussi a contacter si besoin
Donc quoi de mieux que l'endroit où se trouve la team pour les retrouver et les contacter 

Hs:
J'avais aussi l'idée de "By V.S.T.R.E.A.M" Pour:
Venom
Sizanic
TmpName
Razorex
E
Arias800 
Milkibreizh 

Mais personne avec un E lol (dommage que Yodidon n'a pas un pseudo avec un E) mais quand meme une sacré coïncidence

**Comment by TmpName** [comment]
Lol, ca c'est marrant, tu parles d'un hazard.

>Ha je suis démasquer, j'ai pas chercher plus loin que la première lettre de mon pseudo mais pour ma défense ça marchait bien vStream :)

C'est clair que si tu avais eu un pseudo qui commencait par X, ca aurait fait louche .....

**Comment by sizanic** [comment]
Essai avec "venom-xbmc-addon".
A voir si convient pour l'instant.
