### ISSUE TITLE
Problème sur ZT,extreme-down

### ISSUE THREAD

**Issue by jaja68** [Kodi-vStream/venom-xbmc-addons#3123]
Bonjour à tous,

Lorsque je fais une recherche de film ou séries sur ZT, il me met .. et en dessous aucune information.
Sur extreme-down lorsque je sélectionne un film ou séries lorsque j'arrive sur un hébergeurs(Uptobox; Uploaded etc...) il me met le message "Mettre le lien du hoster après avoir passer les Recaptchas manuellement".  

 - OS: Android TV 8.2.1
-  Appareil : Nvidia shiel TV
 - Version Kodi v18.9 "Leia"
- Version Vstream officielle installer à partir de repository.vstream-0.0.3.zip

Site ZT et extreme-down
tous films et séries

**Log**
http://slexy.org/view/s20gERGSab

**Image**
![Screenshot_20201125-185453](https://user-images.githubusercontent.com/75037091/100265651-dd341800-2f50-11eb-9dbd-3eb1b83d37f8.png)
![Screenshot_20201125-185426](https://user-images.githubusercontent.com/75037091/100265664-e1603580-2f50-11eb-8275-0a75320f32a5.png)

Avez vous les mêmes problèmes ?

Merci d'avance pour votre aide.

Salutations.
jaja68

**Comment by Che-debarras** [comment]
Sujet a fermer non?

**Comment by TmpName** [comment]
Je sais pas, jamais testé, c'est le fonctionnement normal ?

**Comment by Che-debarras** [comment]
> Je sais pas, jamais testé, c'est le fonctionnement normal ?

Oui zt non, normalement on a comme wawacity
Il affiche les captcha a sélectionner (bus velo etc  )
Mais j'ai pas testé 
Donc il se peut que ce soit revenu a l'ancienne méthode de copier coller le lien host pris sur le site internet via un navigateur et revenu le copier coller sur cette fenêtre.

**Comment by jaja68** [comment]
Bonsoir,

Quelqu'un d'autre aurait le même problème avec ZT et extreme-down sur une nvidia shield TV ?

A-t-il une solution à ces problèmes ?

Merci d'avance pour votre aide et conseils.

Salutations.
jaja68

**Comment by jaja68** [comment]
Bonsoir,

cela refonctionne depuis aujourd'hui pour ZT et ED, merci pour votre travail et votre aide.

Salutations.
jaja68
