### ISSUE TITLE
visionnage limité a 480p

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#3124]
Bonjour
Pour une raison que j ignore, tous les nouveaux épisodes de series partagées sous uptobox (zone téléchargement et extrême download) ne sont plus accessibles/visionnables dans vstream qu en 360p ou 480p.
Je viens encore d essayer : The Mandalorian - Saison 02 MULTi 1080p  ep5  (extrême download)

**Comment by Che-debarras** [comment]
Le problème viens pas de vstream car si tu vas sur le navigateur tu aura la meme resolution, le 720p et 1080p sont pas presents.
Cela depend des sources

**Comment by Popoffake** [comment]
Avec mon compte uptobox premium, je n'ai pas ce problème (le Mandalorian episode 5 de extreme-download est bien en 1080p).
En revanche, avec le compte gratuit d'un ami (et les mêmes paramètres vstream), je me retrouve à devoir faire le choix entre 360p et 480p. À passer par uptostream, donc.

**Comment by Che-debarras** [comment]
> Avec mon compte uptobox premium, je n'ai pas ce problème (le Mandalorian episode 5 de extreme-download est bien en 1080p).
> En revanche, avec le compte gratuit d'un ami (et les mêmes paramètres vstream), je me retrouve à devoir faire le choix entre 360p et 480p. À passer par uptostream, donc.

Je crois que meme avec uptostream on a pas les 720 1080p 
Je crois que c'est reserver au premium

**Comment by falciatrice10** [comment]
Bonjour
Juste pour vous dire que je viens de souscrire un abonnement a uptobox et que depuis j'ai de nouveau accès aux 720p et 1080p.

Merci les gars et bonne continuation
