### ISSUE TITLE
Accès Outils / Librairie

### ISSUE THREAD

**Issue by alex83100** [Kodi-vStream/venom-xbmc-addons#3125]
Le répertoire  Outils / Librairie sous Vstream ne s'ouvre plus (test avec la beta idem).

voici mon log : 2020-11-27 18:03:24.068 T:31013   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=getLibrary&sFav=getLibrary&site=cLibrary&siteUrl=http%3a%2f%2fvenom&title=Librairie
2020-11-27 18:03:24.072 T:29366   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=getLibrary&sFav=getLibrary&site=cLibrary&siteUrl=http%3a%2f%2fvenom&title=Librairie) failed

J'ai testé sous android et sous windows, même problème.

Je n'ai pas de problème pour y accéder à partir du gestionnaire de fichiers de kodi dans lequel je vois bien le contenu. 
L'ajout dans la librairie à partir de Vstream fonction correctement également.

**Comment by Arias800** [comment]
C'est parce que Vstream utilisait une fonctionnalité de Kodi qui ne marche plus. J'ai commencé un code que j'ai mis dans la beta. Mais c'est encore en cours.

**Comment by Arias800** [comment]
Normalement ca devrai fonctionner dans la nouvelle version de Vstream.

**Comment by alex83100** [comment]
Bonjour, l'accès au répertoire librairie refonctionne, merci beaucoup. Par contre j'ajout de films dans la librairie à partir de Vstream enlève les espaces dans le nom. Exemple Jours de Tonnerre [fullHD] uptobox donne jourdetonnere. Bien entendu on peut modifier le nom à la main avant de valider et rajouter aussi l'année du film pour permette le film d'être reconnu par le scrapper.

**Comment by Arias800** [comment]
C'est discuté ici : https://github.com/Kodi-vStream/venom-xbmc-addons/pull/3167
Donc je ferme cette issue.
