### ISSUE TITLE
gestion timeout

### ISSUE THREAD

**Issue by zicmama** [Kodi-vStream/venom-xbmc-addons#3126]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Quand on lance une recherche, il arrive que des sources soient inaccessibles...
Il faut aller dans les paramètres de l'appli pour la "décocher".

**Décrivez la solution que vous souhaitez**
Je me demandais s'il serait envisageable de repérer ces erreurs et timeout pour le réduire et limiter l'attente?
Voir décocher la source si l'erreur persiste. Et peut-être envoyer une issue sur git?

Je ne sais pas si tout ce que j'imagine est possible, mais si quelqu'un peut me confirmer et m'indiquer où chercher dans le code pour insérer cette fonctionnalité, la fluidité d'usage de Vstream en serait améliorée
merci

**Comment by sizanic** [comment]
Une source peut être inaccessible un jour puis revenir le lendemain.
Une source peut avoir mis en place une protection cloudFlare, puis la retirer un autre jour.
Une source peut avoir changer d'adresse et une mise à jour va corriger cela.
etc.

Il est difficile de mettre en place un système qui va décider automatiquement d'écarter telle ou telle une source.

La seule solution reste de "décocher" manuellement.

Beaucoup de personnes ne cochent que leurs 3 ou 4 sources préférées (repérées par leur expérience et leurs besoins en séries ou films ou animés).

> Voir décocher la source si l'erreur persiste.

L'idée c'est quoi ?
Mettre en place des compteurs d'erreurs pour chaque source.
On la désactive apres un certain nombres d'erreurs.

Comment se réactive-t-elle ?
Comment sait-on que la source est revenue opérationnelle ?

Il faut retourner "cocher" la case manuellement 😄

**Comment by TmpName** [comment]
Pas mieux, l'outil le plus fiable c'est l'utilisateur, ergonomie ok, mais au bout d'un moment c'est plus performant.

**Comment by zicmama** [comment]
>  Mettre en place des compteurs d'erreurs pour chaque source.
je pense que cela reviendrai à faire cela. Et régler les niveaux de "timeout".
par exemple: 30s puis 20s, 10s, 0s... aléatoirement les sources 0s seraient réactivées pour palier aux fausses alertes.

> Il faut retourner "cocher" la case manuellement
exactement. dans ce cas l'expérience utilisateur me parait meilleure.

Effectivement laisser l'utilisateur se débrouiller est aussi une option.

**Comment by milkibreizh** [comment]
> Je ne sais pas si tout ce que j'imagine est possible

justement , il y a  autant de façon possible de créer un code  
et d’insérer un code  dans les fichiers que celui de créer une méthodologie
de code pour obtenir une fonctionnalité
donc l**e code impliqué** varie selon le choix de la méthode choisie mais elles pourrait se situer
dans le default.py, def searchGlobal() attention celle ci ne gère pas les requetes mais attend le resultats
de fonctions ,ou dans le fichier requesthandler (ex;timeout ou autres),ou dans la modification du code des sites
ou dans la modification de plusieurs fichiers à la fois,....etc
