### ISSUE TITLE
Proposition site Football

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#3129]
Bonjour, je voulais vous proposer deux source pour voir des matchs de football en replay.
Surtout pour remplacer Robindesdroits, le seul truc c'est que les sites sont pas francophones mais ils proposent aussi des matchs de Ligue 1.

Le premier:
ht tps://galatamanhdfb.blogspot.com/
![Capture du 2020-11-30 08-46-50](https://user-images.githubusercontent.com/12912677/100582325-5fbe2e00-32e9-11eb-99fc-bf5edf80ccb2.png)
Il propose tout les grands match des 5 championnats et les coupes d'Europe en lien direct inclouddrive (dispo sur alldebrid).
C'est en 1080i.

Le deuxieme:
ht tps://hdmatches.net/
![Capture du 2020-11-30 08-47-17](https://user-images.githubusercontent.com/12912677/100582559-b7f53000-32e9-11eb-85ea-2e7e6dfbf008.png)
Il fait la même chose mais en streaming en 720p et il propose les highlights des matchs, aussi des matchs de Ligue 1 contrairement à l'autre qui propose seulement les matchs du PSG.

Voilà, merci à vous pour votre aide.

**Comment by sizanic** [comment]
Salut,

Le premier passe par inclouddrive 🤔 
On n'a pas ce hosters dans vStream.
Faut voir, mais en testant en ligne : 
sans compte, on attend 45 secondes, puis il faut saisir un captcha.

Quand au deuxième, je n'ai pas réussi à voir une seule vidéo.

**Comment by milkibreizh** [comment]
si dans le deuxieme tu as bien des videos ,tu as des liens streaming a prendre a l'adresse https://bomurl.com
avec temps d'attente

**Comment by sizanic** [comment]
j'ai attendu plusieurs fois bomurl, et finalement les liens étaient périmés 😢

**Comment by milkibreizh** [comment]
@sizanic 
pas de bol , il est vrai qu'il y a plusieurs types de liens dont le résultat est incertains
mais au moins cela t'éviteras la tentation de vouloir jouer au loto foot^^

**Comment by lebigboss** [comment]
> Salut,
> 
> Le premier passe par inclouddrive 🤔
> On n'a pas ce hosters dans vStream.
> Faut voir, mais en testant en ligne :
> sans compte, on attend 45 secondes, puis il faut saisir un captcha.
> 
> Quand au deuxième, je n'ai pas réussi à voir une seule vidéo.

En faite inclouddrive est dans alldebrid.
Sinon il y a ce site fullmatchsports.co qui fait un peu tous les sports et qui a des liens 1fichier et Uptobox

**Comment by milkibreizh** [comment]
> Sinon il y a ce site fullmatchsports.co qui fait un peu tous les sports

le lien nba-full-game est hs 😢

**Comment by Niconimes** [comment]
Perso quand je veux mater un match j'utilise ce site: https://www.streamonsport.info/
Par contre c'est du live, je ne sais pas si vous pouvez l'intégrer à Vstream ou si il faut absolument que ce soit du "Replay" pour ça 🙄

**Comment by sizanic** [comment]
Il y a déjà du live dans vStream, par le site liveTV.
À voir s'il peut venir en complément.

**Comment by milkibreizh** [comment]
streamonsport
> Il y a déjà du live dans vStream, par le site liveTV.

il s'agit plus d'un site qui s'apparente à channelstream en un peu moins complet
pour les chaines tv type généraliste et possède d'ailleurs les mêmes liens finaux 
par contre au niveau des chaines sportives il possède 2 hosters possibles en plus
ce qui n'est pas négligeable

**Comment by sizanic** [comment]
Je vais jeter un œil ...

**Comment by milkibreizh** [comment]
autrement je venais de finir  la source..mais je sais pas si il peu apparaitre des hosters non résolus
j'en est toujours vu que 3 et j'ai un doute sur un 4 eme mais il est résolu normalement
