### ISSUE TITLE
Menu Favori personnalisable 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3130]
La demande de fonction n'est pas liée à un problème mais plus à un complément de fonction lié à l'activation des sources.

On peut désactiver les sources dans les paramètres afin que la recherche globale ne les prend pas en compte.

Mais serait il possible de faire en sorte que  c'est sources désactivés aient aussi leur affiche d'icônes désactivées.

Par exemple la personne qui n'utilise ni les sources de docu ou video de buzz ni iptv , que seule les sources de films et series soient affichées.

Car l'affichage "Mur" montre trop de sites surtout si on utilise que 3 ou 4 pour les films et 3 ou 4 pour les series et 3 ou 4 pour manga.

Ou avoir une categorie :  Favoris où on peut y mettre nos sources et categories préférée qui sera surement amener a changé avec le temps

**Comment by TmpName** [comment]
Tu parles de "toutes les sources" ?

**Comment by Che-debarras** [comment]
> Tu parles de "toutes les sources" ?
> Si c'est ca, non, ici c'est justement le seul endroit ou tout les sites apparaisent, quelque soit les reglages justement.
> 
> Par contre le coup des favoris, c'est pas bete. Dans les favoris ? une pages speciale ? Y a pas deja une option dans kodi qui fait ca ?

Version longue :
Non ya marques page mais c'est que pour les titres pas pour les sources.
Oui ya favori de Kodi mais si on le met en favori kodi il sera noyé entre les films et series mis en favori car c'est mis par ordre chronologique 
Et il faudra modifier l'emplacement de ces sources favoris pour les mettre au debut de liste
Si ya eu bcp de films et series mis en favori ce sera long le déplacement jusqu'en tete de liste surtout si ya plusieurs sources mis en favori

mais si c'est inclus dans vstream on pourra ensuite mettre ce dossier favori de vstream dans favori de kodi  et ce sera plus simple de déplacer 1 seul dossier en tete de liste contenant tous les sources favoris.

Je sais pas si je suis clair.

Mais je pense un dossier favori dans vstream serait pas mal
Surtout avec une recherche uniquement dans ces favoris pour limiter les recherches
Car si comme moi on mate pas les animés,  on est pas embeter avec les 10aines de resultats trouvé inutile

Verstion courte 
Ex: dans Vstream/favori on pourrait avoir
Un dossier film et un dossier Serie et un dossier Animé , un dossier Spectacle etc..
Et on y place un sous dossier sois la source entière ex Tirexo soit la categorie ex film 4k ou Film asia ou Serie VF etc..
Le top si la recherche peut se limiter soit au dossier soit au sous dossier

Désolé du long message

**Comment by sizanic** [comment]
Dans vStream, il y a déjà un classement Films/series/animes/docs/...
C'est même la page d'acceuil de vStream 🤔 

Et chacun de ces dossiers, propose un menu source.

A la rigueur, ce qu'on peut faire de simple, c'est lorsqu'on passe par ce menu Films/sources ou Séries/source, c'est de présenter seulement les sources qui sont actives dans les parametres.

Et si on veut voir TOUTES les sources (mêmes celles désactivées), il faut passer par le menu Sources de la racine de vStream.

Donc dans tes favoris de KODI, tu peux mettre le dossier : vStream/Films/Sources

**Comment by Che-debarras** [comment]
@sizanic 
Oui mais dans ce dossier film(ou séries)/source ce sont des sources deja présent et on ne peut pas vraiment le personnaliser. Certes c'est un bon début 

mais l'idée est de faire comme pastebin, d'y mettre pas uniquement les sources mais les catégories qu'on souhaite.

Dans film yaura la ou les sources mais celui qui regarde que la VF et jamais la Vostf, ce serait bien de ne afficher la categorie vostf,  ou exclure les categories Peplum.

Tous ca en un seul dossier (fusionner film/source et Serie/Source) afin d'avoir une vue de l'ensemble de toute les sources et categories favoris qu'on utilise le plus souvent.

Et quand yaura une autre source, on incluera la source ou une categorie  de cette source ou en exclure une dans le menu contextuel sans bidouiller les paramètres de vstream

Pour faire simple c'est le dossier favori de kodi mais inclus dans l'addon vstream et je sais que d'autres addon le fait comme Catchup TV.

**Comment by milkibreizh** [comment]
> A la rigueur, ce qu'on peut faire de simple, c'est lorsqu'on passe par ce menu Films/sources ou Séries/source, c'est de présenter seulement les sources qui sont actives dans les parametres.

il y a aussi assez simple,mais cela rejoint le meme principe sauf que l'on ne filtre pas la source
selon sa categorie , dans le menu home il suffit de rajouter un menu qui ajoute les sources selectionnées grace a une fonction qui ressemble a celle de recherchehandler. getAvailablePlugins()en recuperant l'id et le nom de la source, et en affectant la fonction 'load' par defaut on  peu créer un dossier ou on a acces direct aux sources sélectionnées pour le globale 
c'est ce que je rajoute parfois comme code et ya vraiment pas grand chose a faire.....
peu de  code  peu de bug
mais si cela se trouve cela existe déjà..tant pis

**Comment by Che-debarras** [comment]
Donc pensez vous qu'un menu favori est possible?

**Comment by sizanic** [comment]
>L'autre avantage ça pourrait alleger le menu car le Menu Films/series/animés/docu/sport/video du net ne sera plus necessaire vu que tout cela seront dans Favori personnalisé par l'utilisateur.

Et ceux qui personnalisent pas 🤔 

> Tous ca en un seul dossier (fusionner film/source et Serie/Source et Anime/source etc..) afin d'avoir une vue de l'ensemble de toute les sources et categories et fonction favoris qu'on utilise le plus souvent.

Si je recherche un film, je vais dans la section Film, tout fusionner me proposera trop d'info par rapport à mon besoin 🤔 


J'ai l'impression que ce que tu décris, c'est déjà ce que permet de faire la personnalisation de certains skins.
Et je pense d'ailleurs que c'est à la responsabilité du skin ou à des addons spécialisés (exe: node Editor) de gérer cette personnalisation.

**Comment by Che-debarras** [comment]
> 
> Et ceux qui personnalisent pas 🤔
> 

Le dossier Favori sera vide toute comme ceux qui font pas de marquepage ou de librairie mais je suis sûr que les gens l'utiliseront pour y mettre leur site ou catégorie préférées,  se faire un menu personnalisé.

> 
> Si je recherche un film, je vais dans la section Film, tout fusionner me proposera trop d'info par rapport à mon besoin 🤔
> 

Le but est de chercher le film ou la serie dans les sources mises en favori et pas dans l'ensemble des sources de films ou de serie
Donc yaura moins d'infos vu que moins de sources , moins de catégorie

> J'ai l'impression que ce que tu décris, c'est déjà ce que permet de faire la personnalisation de certains skins.

Oui peut-être mais il me semble que Vstream se voulait etre autonome et ajouter juste un menu favori ça eviterais d'installer un skin.

> Et je pense d'ailleurs que c'est à la responsabilité du skin ou à des addons spécialisés (exe: node Editor) de gérer cette personnalisation.

Là tu parles de personnalisation esthetique, visuelle et c'est pas l'idée surtout que ça demande d installer des skins, les tester, les paramètrer alors que la c'est juste un clic "mettre en favori Vstream" et c fini.

Mais bon pas de souci,  c'est juste une idée.

**Comment by sizanic** [comment]
Je ne suis pas contre toute nouvelle idée.
Pour l'instant je "challenge" l'idée pour bien la comprendre.

>Pour résumé, l'idée est tous ce que contient vstream peut etre mis en favori ( un élément du menu d'accueil, une source, une categorie, un pastebin, une fonction etc..) pour un accès rapide et personnalisé

C'est déjà le cas pour mettre en favoris de KODI.
Chez moi, ce n'est pas mélangé avec des films que je ne me sers que des marques-pages vStream pour sauvegarder les liens vers des films.

**Comment by Che-debarras** [comment]
@sizanic 
Le favori de kodi est limité comme je l'ai expliqué dans un post.
Et tu confirme que tu es obligé d'utiliser un autre menu Marque-page pour tes films pour les séparer.

Sauf que l'idée n'est justement de pas les séparer afin de ne pas cliquer en arrière pour aller sur marque page ou favori de kodi.

Tous ce trouve dans la meme page : la source préférée,  la catégorie préférée, la fonction préférée ou la saison/film/épisode préférée. 
On jonglera moins entre favori de kodi,  hoster direct,  librairie, les sources etc.

Je sais que tout peut etre mis en favori de kodi mais si le lien est mort apres la fermeture du site comme Planetstrmng où j'ai plein de film en favori mais tous HS.
Il m'est impossible de faire une recherche dans vstream car kodi est indépendant de Vstream et je suis obliger de quitter favori, aller dans vstream et recherche globale 

ALors que si cetait dans un menu favori menu si le lien est mort ou le film a disparu, on va sur la source ou la fonction recherche globale ou le ID pastebin mis en favori sur la même  page pour le rechercher ou même un seul clique dans un menu contextuel pour une recherche similaire et c fait 
Et si on trouve pas et bien on a host direct dans ces favoris pour importer un lien 

Je te remercie de challenger l'idée mais pas de souci, je pensais pas qu'il aurait fallu autant d'explications pour un simple menu favori et son intérêt.

Merci d'avoir lu. Je clos cette idée.

**Comment by milkibreizh** [comment]
> Pour l'instant je "challenge" l'idée pour bien la comprendre.

 l'idée de rajouter un menu spécifique  a déjà été demandé je crois auparavant par d'autres utilisateur
donc sans doute qu'en effet il y a un besoin...les gens veulent tout avoir dans vstream
on peu pas leur reprocher cette habitude et j'ai aussi cette "mauvaise" habitude
par exemple pour séparer certaines sources je dois mettre une variable supplémentaire
dans chaque fichier pour qu'elles s'affichent..et certains me dirons en effets qu'il y a un menu Favoris
...du coup moi je serais pas contre d'avoir au moins un dossier ou on peu 
mettre des sources sélectionnées et au plus dans lequel il existe un moyen 
de faire une recherche dans celui ci
 j'ai deja codé le truc pour eviter de tager les sources mes j'ai obtenu
un code pourri pour conserver les données et je suis obligée de remettre
le code a chaque fois des que je suis sur une nouvelle version

**Comment by TmpName** [comment]
Ben perso je ne me sert pas des favoris de kodi donc je sais pas du tout a quoi ca ressemble.

Mais je pensais a mettre dans les marque pages une rubrique "site" ou on pourrait mettre les sites qu'on voudrait, c'est tout con, mais peut etre ridicule (inutile) comparé a la fonction integrée a kodi ?

**Comment by sizanic** [comment]
@Che-debarras 

> Le favori de kodi est limité comme je l'ai expliqué dans un post.
Et tu confirme que tu es obligé d'utiliser un autre menu Marque-page pour tes films pour les séparer.

**ABSOLUMENT PAS** 🤔 
Merci de ne pas déformer mes propos : 
_Chez moi, ce n'est pas mélangé avec des films car je ne me sers que des marques-pages vStream pour sauvegarder les liens vers des films._

Je ne suis obligé de rien !
Je ne me sers que des marque-pages de vStream **sans obligation** mais bien parce que je les trouve mieux que les favoris de KODI.
En utilisation en widgets :
- Films et séries sont séparés
- Il y a les infos tmdb
- il y a le menu avec les actions vStream : Information / Bande annonce / Recherche similaire

Je ne ferme pas la porte à ton idée.
Ce n'est pas ma priorité pour le moment de me lancer dans ce genre de développement, mais si quelqu'un veut le faire, y'a pas de problème.
(faut juste que l'idée soit bien comprise et c'est l'idée que je veux finaliser).

**Comment by sizanic** [comment]
@TmpName 
>Ben perso je ne me sert pas des favoris de kodi donc je sais pas du tout a quoi ca ressemble.

ça je le **confirme**, utiliser les favoris de KODI pour vStream n'est pas interessants.

>Mais je pensais a mettre dans les marque pages une rubrique "site" ou on pourrait mettre les sites qu'on voudrait, c'est tout con, mais peut etre ridicule (inutile) comparé a la fonction integrée a kodi ?

Je proposais laisser le menu **Sources** déjà présents dans chauqe rubrique Films/Series/Docs, mais que n'apparaisse que les sources qu'on a activées.

ça donnera déjà un menu plutôt propre sans besoin de personnaliser.

**Comment by milkibreizh** [comment]
@sizanic 
> Je proposais laisser le menu Sources déjà présents dans chauqe rubrique Films/Series/Docs, mais que n'apparaisse que les sources qu'on a activées.

oui mais cela ne risque t'il pas de bataillé entre
ceux qui  voudrons que n'apparaisse que les sources qu'on a activées.
et d'autres qui voudrons que tous les sources apparaissent 
(a moins de t'avoir mal compris)

je suis plutôt du même avis que @TmpName 

> une rubrique "site" ou on pourrait mettre les sites qu'on voudrait

comme cela ne généras ni les habitudes  des uns ni  des celles autres

**Comment by sizanic** [comment]
Alors je viens de vérifier et ce que j'éssaye d'expliquer depuis le début est EXACTEMENT ce qui est déjà en place 😆 

En désactivant une source dans les paramètres, cela est pris en compte : 
- dans les recherches globales
- masque cette source dans les autres menus Films/séries/animes/doc, etc.

=> Sauf dans le menu sources qui est à la racine, on y retrouve toutes les sources.

Après, vouloir un menu pour y mettre nos sources préférés, alors qu'il y a quand même de grandes chances que nos sources préférés soient les mêmes que celles qu'on utilise pour la recherche 🤔 

Actuellement, j'active mes sources dans les paramètres : 
- si je veux utiliser mes sources préférés pour recherche une nouveauté en films, je me rend dans le menu vStream : Films/Derniers ajouts, et seuls mes sources préférées qui proposent des "derniers ajouts" sont proposés.
- Si je recherche un genre d'animés, pareil, je me rends dans le menu Animés/Genres, et seules mes sources préférées qui proposent des genres d'animés sont proposées.
- etc.

Tout cela est déjà le fonctionnement actuel.
A condition qu'on dise que les sources actives dans les paramètres sont nos sources préférés.
Et il y a de grandes chances, non ?

Alors que : 
- Si on a une dizaine de sources préférées qu'on regroupe dans un seul endroit, il faudra se rappeler laquelle sert à quoi. Alors que les menus actuels tris déjà par type de contenu (ce que j'explique ci-dessus).
- Si on a que 3 sources préférés, autant les mettre au début des favoris de KODI. et ils n'y bougent plus.

**Comment by TmpName** [comment]
>Je proposais laisser le menu Sources déjà présents dans chauqe rubrique Films/Series/Docs, mais que n'apparaisse que les sources qu'on a activées.

Je viens de decouvrir que tout les sites en rapport apparaissaient dedans, j'avais pas vu le menu "sources"

Du coup ca change tout, mais si je suis chiant, je voudrais avoir uniquement 3 sites en favoris, parce que de faire 4 manip sur ma telecommande ca m'epuise pour les retrouver, et j'aime bien uniquement ces 3 sites pour leur qualitée, MAIS je veux quand meme faire mes recherches sur tout les sites ....

**Comment by Che-debarras** [comment]
@sizanic 
On utilise pas tous vstream comme toi, si tu vois pas l'intérêt d'un menu favori ne force pas les autres a y voir aucun intérêt.
J'ai clos le sujet car visiblement apres 2 longs messages de ma part expliquant en detail le fonctionnement et l'intérêt d'un menu favori, tu n'arrive toujours pas a comprendre vu que tu ne cesses de parler de source quand je te parle de categorie,  outils, recherche .

J'ai compris que toi tu veux aller dans tout tes menus pour chercher ce que tu cherche et moi je parle de rassemble tous les menus préférés en un seul menu.

Donc tu veux pas de menu favori car c'est pas comme ça tu l'utilise et tu veux pas qu'on l'utilise différemment donc OUBLIONS CETTE FOLLE IDÉE SAUGRENUE QUE J'AI EU.
