### ISSUE TITLE
Venom  in real life

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#3133]

**Comment by TmpName** [comment]
Lol, j'ai eu peur, quand j'ai lu les premieres lignes j'ai cru que j'etais sur adopteunmec.com.

**Comment by LordVenom** [comment]
Merci pour le vent ça fait plaisir... 4ans de dev et de support, bravo!

**Comment by yodidon** [comment]
Hein ?

**Comment by LordVenom** [comment]
Sauf toi :)

**Comment by yodidon** [comment]
Ha ok personne n’est passé ?

**Comment by LordVenom** [comment]
Nop ça leur rapporte rien il s'en tape.

**Comment by milkibreizh** [comment]
je comprends pas,il me semble bien pourtant avoir cliqué sur le lien l'autre  jour ^^

**Comment by yodidon** [comment]
Peut-être sont il pris c’est pas toujours évident, par contre j’ai cherché le jeux mais pas trouvé l’instal (j’ai cherché pour Mac OS)?

**Comment by LordVenom** [comment]
Non mais c'est bon, je veux forcer personne à passer ou à follow.

**Comment by yodidon** [comment]
J’essaierai sur pc il me paraît cool et accessible

**Comment by LordVenom** [comment]
dsl yodidon mais le but c'est pas le jeux mais juste passer dire coucou ce que tu as fait merci.

**Comment by yodidon** [comment]
Dac

**Comment by milkibreizh** [comment]
h

**Comment by TmpName** [comment]
Bon ben désolé, j'avais pas compris que cela te prennait autant a coeur, de mon coté je ne connais pas du tout twitch, donc j'ai été voir, mais j'ai pas compris ce que je devais faire.

Dans tout les cas, ta place restera libre ici ^^.
