### ISSUE TITLE
wawacity inaccessible 

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3134]
aucun lien n'est  fonctionnelle sur wawacity , pouvez vous explorer ce dysfonctionnement ?  merci

**Votre system**
 - OS:windows et android
 - Version Kodi   18.9
- Version Vstream

**Comment by bzkdjc** [comment]
Tout ce qui est listé dans Wawacity conduit à une page vide "No information" après qu'on ait passé avec succès les Captcha. 
Depuis quelques jours et toujours actuellement ce 22 juin 2022.
