### ISSUE TITLE
Ajout des listes aimées sur Trakt via Vstream

### ISSUE THREAD

**Issue by KoRnEr007** [Kodi-vStream/venom-xbmc-addons#3135]
Hello,

Maintenant, que trakt est intégré a Vstream, j'ai vu qu'on avait possibilité des récupérer ses propres listes.
Pourrait on ajouter les "liked lists" aussi svp ?
Je pense que c'est possible car l'addon tmdb helper le fait .

Merci par avance. Et bonnes fêtes
Jon

**Comment by Arias800** [comment]
C'est fait : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/88516e63d09aa8a11c70ac14be26b35f84c54f59

**Comment by KoRnEr007** [comment]
J'ai testé la fonctionnalité dans la 0.8.4 j'ai une erreur quand je clique sur le lien

addons\plugin.video.vstream\resources\lib\trakt.py", line 343, in getLists
                                                url = URL_API + 'users/' + List['list']['user']['name'] + '/lists/' + List['list']['ids']['slug'] + '/items'
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
                                            -->End of Python script error report<--

**Comment by Arias800** [comment]
Comme toujours, sans exemple je ne peut rien faire.

**Comment by KoRnEr007** [comment]
On peut fermer ce ticket 
la suite sur celui d'alko
