### ISSUE TITLE
VSTREAM SUR FACEBOOK

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3136]
Je viens de créer une Page Facebook de vStream pour la Communauté au https://www.facebook.com/vstreamkodi

**Comment by sizanic** [comment]
Merci, mais ...
La page fait très "Officielle".
Qui va la maintenir ? 🤔

**Comment by KoRnEr007** [comment]
Et ben vous aimez facebook ....

**Comment by ludopotte** [comment]
De rien et c'est moi qui va la maintenir en mettant les Liens de téléchargement du repository, beta etc... pour la commuanuté.

**Comment by sizanic** [comment]
A part rendre plus accessible les **2 liens officiels** de téléchargements (repo et **version officielle**), quel autre utilité de cette page ?

Je pensais que cette issue serait plutôt pour nous proposer de créer et maintenir cette page.
Et que ce serait discutée.

Mais là tu l'a déjà créée et tu nous informes juste 🤔 
A moins que tu es déjà discuté de cette démarche avec d'autres membres de la team ?

**Comment by ludopotte** [comment]
J'ai crée cette Page Facebook pour la Communauté en parallèle du Serveur Discord car pas tout le Monde est sur Discord. Je penses qu'avec cette Page, les Gens pourront poser leurs Questions et autres par rapport à vStream plus simplement et j'ai pas encore parler avec les autres membres de la Team.

**Comment by alKODIque** [comment]
he bien 🤷🏻‍♀️

**Comment by sizanic** [comment]
Le serveur Discord a été créé par la Team, il est administré par la Team (@Arias800) et est modéré par la Team vStream.

Si ce n'était pas le cas, le serveur Discord serait fermé tout de suite !

Pour info, l'avis de @LordVenom à ce sujet : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2367#issuecomment-700413059

Si tu ne connais pas Venom, c'est le 'V' de vStream 🤔 

Ta page facebook ne remplit pas ces conditions !

Ta page n'est pas administrée par la team vStream.
Si c'était le cas, il n'y aurait pas de lien vers un patch.
Car en plus de ne pas être un patch officiel,
=> NOUS NE VOULONS PAS que les patchs soient facilement récupérables.

Ca doit rester confidentiel, pour des beta-testeurs avertis !
C'est une règle définie par la Team.

Et comme aucun membre de la team n'est modérateur sur ta page, nous ne pouvons pas enlever ce lien.

En plus de fournir un lien vers ta propre page Github (indépendante de la page officielle vStream),
il y a d'autres liens sur TA page facebook que nous ne validons pas.

Un lien Pastebin par exemple qui donne accès à tes autres liens de ton propre compte pastebin :
"ELSA ESNOULT CHANTE NOEL" 🤔 


@ludopotte 
ton attention était louable, mais elle doit être discutée avec la Team pour savoir : 
- veut-on vraiment une page facebook ?
- que met-on dessus ?
- qui administre ?
- qui modère ?


En attendant de répondre à toutes ces questions, je ne peux pas t'interdire d'avoir une page Facebook, mais merci de ne pas la faire apparaître comme LA page officielle vStream.

Avec un encart qui reprend des informations telles que :
- Non officielle
- maintenu par un passionné

**Comment by ludopotte** [comment]
Ok je comprends tout à fait et moi c'est juste question de Partage et d'entraide. Est-ce que la rubrique "patch-vstream" du discord officiel de vStream va etre fermer ?

**Comment by TmpName** [comment]
Oui @ludopotte tu peux faire ce que tu veux, en plus tu es motivé, on va pas te bloquer, mais faut juste faire la difference entre "officiel" et "perso".

Dans le second cas, tu fais ce que tu veux, c'est a toi, mais il faut bien que les gens comprennent. On est pas responsable de ce qu'il y aura dessus, ce sera ta page.

**Comment by ludopotte** [comment]
Oui bien @TmpName mais le contenu de cette Page sera en lien avec l'extension et les informations de la Page Github de vStream.
