### ISSUE TITLE
Images pour decripter un lien

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3139]
Bonsoir,

Je vais essayer d'être clair même si c'est pas des plus simples, j'ai un souci avec les images qui cachent les liens sur de nombreux sites.
Exemple : Wawacity avec des trucs du genre où sont les deux de circulation, il faut alors choisir les bouts d'images concernés.
J'aimerai savoir si je suis le seul à ne pas y arriver.

Nb: je cherche sur quel autre site j'ai le même souci mais je ne trouve pas tout de suite

**Comment by Arias800** [comment]
Tout le processus de vérification est géré sur les serveurs de Google. Vstream ne peut pas agir dessus.
