### ISSUE TITLE
Listes TRAKT - Problème à l'ouverture

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3140]
@Arias800 
Grand merci pour les ajouts de listes Trakt
Cependant, je rencontre un problème (oui, encore! :p ) à l'ouverture des listes aimées et de mes listes personelles. Par contre, aucun problème pour les listes tendances et populaires!

Voici mon log en pièce attachée
[kodi.log.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5685404/kodi.log.txt)

**Comment by Arias800** [comment]
Je n'arrive pas à reproduire le bug, donc faut voir si quelqu'un réussit a le reproduire xD

**Comment by TmpName** [comment]
Ca devrait passer en faisant
`i.get('collected_at','')`
a la place de
`i['collected_at']`

Y aura une valeur vide, mais plus de bloquage.

**Comment by KoRnEr007** [comment]
Moi je reproduis le prb avec mes listes aimées, par contre mes listes personnelles fonctionnent (mais j'en ai qu'une)

**Comment by alKODIque** [comment]
Je crois que lorsqu'il y a un caractère du type ''&'' ou ' #' dans le titre de média de notre liste trakt, ça bloque... exemple, ouvrir une liste qui contient ce film: https://www.themoviedb.org/movie/397422-rough-night

**Comment by Arias800** [comment]
Corrigé dans la beta.

**Comment by alKODIque** [comment]
@Arias800 
Merci 🙏 
Tout fonctionne à merveille à présent 👍

**Comment by alKODIque** [comment]
Petite question...
Serait-ce possible d’ajouter une pagination à l’intérieur des listes? Celles comportant plus de 50 items sont très longues à afficher

Merci!

**Comment by KoRnEr007** [comment]
J'ai toujours une erreur que je tente d'aller sur mes listes trakt liked sur vstream 0.8.5 / Android Shield pro / SPMC
34:12.392 T:172045321456  NOTICE: 	[PLUGIN] vStream: load site cTrakt and call function getLists
17:34:13.174 T:172045321456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'NoneType' objects
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.vstream/default.py", line 370, in <module>
                                                main()
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.vstream/default.py", line 49, in __init__
                                                self.parseUrl()
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.vstream/default.py", line 146, in parseUrl
                                                if isTrakt(sSiteName, sFunction):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.vstream/default.py", line 289, in isTrakt
                                                exec("oTrakt." + sFunction + "()")
                                              File "<string>", line 1, in <module>
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.vstream/resources/lib/trakt.py", line 343, in getLists
                                                url = URL_API + 'users/' + List['list']['user']['name'] + '/lists/' + List['list']['ids']['slug'] + '/items'
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
                                            -->End of Python script error report<--
17:34:13.258 T:171988923632   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=getLists&sFav=getLists&site=cTrakt&siteUrl=https%3a%2f%2f&title=Mes%20listes%20aimer&type=liked-lists
17:34:13.260 T:171988923632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=getLists&sFav=getLists&site=cTrakt&siteUrl=https%3a%2f%2f&title=Mes%20listes%20aimer&type=liked-lists) failed

**Comment by TmpName** [comment]
Tu pourrais pas rajouter juste avant cette ligne

`VSlog(List)`

pour avoir
```
                if sType == 'liked-lists':
                    VSlog(List)
                    url = URL_API + 'users/' + List['list']['user']['name'] + '/lists/' + List['list']['ids']['slug'] + '/items'
                else:
```
Ca va rajouter des infos dans les logs

**Comment by Arias800** [comment]
@KoRnEr007 Corrigé dans la beta.
@alKODIque C'est fait, j'ai mis la limite a 20 éléments par page.
