### ISSUE TITLE
ZuStrm

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3144]
**Décrivez le bug**
Les liens hosts sont absents quelques soit la série episode ou host, aucun lien ne s'affiche

**Votre system**
 - OS: [Android]
-  Appareil [box tv android ]
 - Version Kodi  [18.9]
- Version Vstream 0.8.4

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : ZUSTRM
- Le titre du fim/serie : Série EXPANSE
- Le nom du host (openload/vidzi) TOUS

**Comment by milkibreizh** [comment]
l'url du site à changée Série EXPANSE = ok
(il semble cependant qu'il y est un problème sur certains liens directs...chose à revoir)

**Comment by Che-debarras** [comment]
@milkibreizh 

Le seul qui ne se lance pas c'est uptostrm et uptobox sinon les autres ça à l'air d'etre ok

**Comment by milkibreizh** [comment]
oui les liens directs qui posent problemes sont uptostrm  qui donne du uptobox  et avec ces liens il y a refus de connection

**Comment by Che-debarras** [comment]
> oui les liens directs qui posent problemes sont uptostrm qui donne du uptobox et avec ces liens il y a refus de connection

Ya une solution?

**Comment by milkibreizh** [comment]
c'est l'host uptostream qui semble poser problème en attendant tu peux essayer
 l'avant derniere version du host du cCommits on Nov 21, 2020
elle semble mieux marcher (sur mon systeme w10 kodi18) mais si il y a eu des modifications du host il doit y a une raison..j'ai pas trop suivi le truc
et je préférés pas toucher cet host,quand arias sera au courant il devrait résoudre le truc comme à son habitude^^
