### ISSUE TITLE
Avis de recherche: disparition des "é"

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3145]
**Décrivez le bug**
20 décembre ,  nous apprenons la disparition d'une lettre, membre éminent de  l'alphabet.

Cette lettre aurait été vue la dernière fois dans La description des titres, il portait un accent sur la tête.

Donc si une personne a la moindre information concernant la disparition soudaine du "é" veuillez contacter la team vstream.

**Comment by yodidon** [comment]
j'en ai vu passer sur la version 0.8.4 dans 4kstreamz Films(Par ann_é_es) je ne sais pas s'il restera longtemps alors profites en rapidement ....

**Comment by Che-debarras** [comment]
> j'en ai vu passer sur la version 0.8.4 dans 4kstre--am-z Films(Par ann_é_es) je ne sais pas s'il restera longtemps alors profites en rapidement ....

Autant pour moi, ils ont disparus de la catégorie Films en salle de la recherche visuelle

**Comment by razorex** [comment]
Peu de gens aiment les accents pourtant ils font parties du patrimoine Français (et oui un c cédille)..

**Comment by TmpName** [comment]
harrrrr, mon coeur s'est arrette quand j'ai vu la cedille.

**Comment by razorex** [comment]
Même le traducteur de google chrome l'utilise....

**Comment by TmpName** [comment]
Mais lui il lit et ecrit meme le chinois, moi je boycotte, comme ca on a une chance que ca disparaisse dans 5000/10000 ans.

**Comment by razorex** [comment]
Oauh!!! Nonnn soyons fière de nos origines, de toute façon dans 5000 ans on aura des traducteurs implanté dans nos cerveaux, 
façon(et oui encore un c cédille) star trek ptdr...
Et même mes fautes d’ortographe (voulu la faute lol) seront corrigées.......

**Comment by sizanic** [comment]
> harrrrr, mon coeur s'est arrette quand j'ai vu la cedille.

oui, on sait, il n'y a que ta vieille prof de français qui mets des cédilles en 2020 🤣 

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/fd00b93a9a45b816e8a25cb68018a76482333de5#r40821327

**Comment by sizanic** [comment]
> Autant pour moi, ils ont disparus de la catégorie la recherche visuelle sur certaines catégories.

Non reproductible avec la dernière version 0.8.6.
