### ISSUE TITLE
Frnchstrm.lol

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3149]
**Décrivez le bug**
Les catégories films et series etc. Ne s'ouvrent pas 

Autre problème avec frnchstrm.lol les saisons sont mélangés PENDANT LA RECHERCHE GLOBALE
Ex : S01 de star trek discovery c'est la S03 et les 2 autres saisons ne sont pas étiquetées S02 ou S01

**Votre system**
 - OS: [Android]
-  Appareil [box tv android]
 - Version Kodi  [18.9]
- Version Vstream 0.8.4

**Comment by milkibreizh** [comment]
je n'ai pas ce bug sur mon win10 kodi18 Vstream 0.8.4 beta

**Comment by Che-debarras** [comment]
> je n'ai pas ce bug sur mon win10 kodi18 Vstream 0.8.4 beta

J'ai oublié de preciser que ce bug n'a lieu que en fin de journée (en soirée) donc je pense que c'est un problème du site  non?

**Comment by milkibreizh** [comment]
Pour l'instant c'est pas trop LOL c'est du cloudfare que j'ai eu et j'avoue que je l'avais pas vu venir celui là,
je l'ai eu 5 minutes et puis c'est revenu. Autrement si c'est pas lui, ce qui est fort possible, car il suffit d'un rien
pour que le code ne fonctionne plus, il faut attendre que ca bug sans qu'il y est CF pour changer le code si nécessaire...
affaire à suivre...en fin de journée

**Comment by Che-debarras** [comment]
Autre problème avec frnchstrm.lol les saisons sont mélangés
Ex : S01 de star trek discovery c'est la S03 et les 2 autres saisons ne sont pas étiquetées S02 ou S01

**Comment by milkibreizh** [comment]
je n'ai jamais réussi jusqu’ici à voir le bug 
_Les catégories films et series etc. Ne s'ouvrent pas_
est il réapparu ?

**Comment by Che-debarras** [comment]
Je pense que ça été corrigé 

Merci
