### ISSUE TITLE
nouvelles adresses pour extreme down et zone-telechargement

### ISSUE THREAD

**Issue by GR33ZY99** [Kodi-vStream/venom-xbmc-addons#3151]
Les sources extreme down et zone téléchargement sont inaccessible.
Les listes de films, séries et mangas ne s'affichent plus

Il semble que les 2 sources ont de nouvelles adresses:
h t t p s : / / w w w . extreme-down.tv
h t t p s : / / w w w . zone-telechargement.pro

Pouvez vous mettre à jour les adresses dans vstream?

Merci d'avance

**Votre system**
 - OS: Android
-  Appareil nvidia shield
 - Version Kodi 18.9
- Version Vstream 0.8.4

**Comment by Nash233** [comment]
non,
l adresse de Zt est www.zt-za.com

c est juste qu elle est bloquée par les fai francais.. passe par un vpn ou change tes DNS...

**Comment by GR33ZY99** [comment]
Merci pour cette réponse.
J'ai essayé avec un VPN et ca fonctionne.

**Comment by freddykrueger59** [comment]
Bonjour
Moi j'ai un soucis différent avec les mêmes sources
J'ai 2 firestick sur lesquelles ça fonctionne
Par contre ça ne fonctionne ni sur ma TV Android ni sur mon téléphone
Sauriez vous m'aiguiller ?
Merci

**Comment by TmpName** [comment]
Ca depend du message d'erreur, mais en general si tu accedes a une url sur une machine et pas une autre, il te faut jeter un oeuil du coté du DNS resolver.

**Comment by freddykrueger59** [comment]
> Ca depend du message d'erreur, mais en general si tu accedes a une url sur une machine et pas une autre, il te faut jeter un oeuil du coté du DNS resolver.

Merci beaucoup pour ton aide mais c'est quoi dns resolver ?

**Comment by TmpName** [comment]
Suite à des blocages plutôt agressif des FAI, il peut être utile pour vous de changer vos DNS, plus d'infos par exemple sur ce lien: https://www.numerama.com/tech/208908-comment-changer-ses-dns-ubuntu-macos-windows.html

**Comment by freddykrueger59** [comment]
> Suite à des blocages plutôt agressif des FAI, il peut être utile pour vous de changer vos DNS, plus d'infos par exemple sur ce lien: https://www.numerama.com/tech/208908-comment-changer-ses-dns-ubuntu-macos-windows.html

D'accord mais mais quatre appareils sont sur le même fai .

**Comment by freddykrueger59** [comment]
Or juste deux sur les quatres fonctionnent

**Comment by freddykrueger59** [comment]
Quand au message d'erreur je n'en ai pas . C'est juste que lorsque je clique sur zone t ça ne réagit pas je n'arrive pas à accéder aux catégories

**Comment by TmpName** [comment]
Essayes d'acceder au site par navigateur, c'est fiable a  100%
Ca depend pas du navigateur, mais de la configuration de la machine, j'ai 2 PC cote a coté, l'un avec le DNS par defaut, l'autre avec ceux de google, meme FAI, un seul peut acceder aux sites.

**Comment by freddykrueger59** [comment]
Ah d'accord je vais essayer alors .merci pour ton aide .je te tiendrais
informé
Joyeux Noël

**Comment by freddykrueger59** [comment]
Bonsoir hier j'ai chant mes dns et effectivement ça fonctionnait nickel et ce soir j'ai les liens ,je peux choisir la résolution mais après plus rien 
Je n'utilise que les liens uptob.. car je n'ai pas de debrideur
