### ISSUE TITLE
Anim.Ultim.

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3154]
**Décrivez le bug**

Anime ultime
Ya un décalage des series entre la liste des épisodes et le dossier.

Quand on clique sur un Drama, le contenu est en faite les episodes du Drama précédent 

Ex : Drama intitulé  881 [Film] contient les episodes du Drama intitulé  49

Il se peut que ce bug touche toutes les categories de la source

**Votre system**
 - OS: [Android]
-  Appareil [K3]
 - Version Kodi  [18.9]
- Version Vstream 0.8.4

**Comment by milkibreizh** [comment]
corrigé mais j'ai pas testé sur de nombreux liens, à voir si il n'y a pas des cas ou il y a une erreur

**Comment by milkibreizh** [comment]
plus personne ne semble trouver de liens décalés ...
