### ISSUE TITLE
LIEN KEPLIZ HORS SERVICE 

### ISSUE THREAD

**Issue by higuelzim** [Kodi-vStream/venom-xbmc-addons#3156]
Bonjour, Depuis un moment je constate que les liens google sur Kepliz ne s'affichent plus (360p &720p)

Pouvez vous voir de votre coté si c'est le cas pour tout le monde

Par avance Merci

**Comment by yodidon** [comment]
Oui kepliz ne fonctionne plus pour le moment, pas encore résolu

**Comment by higuelzim** [comment]
Merci bcp pour le retour

**Comment by Kpliz** [comment]
Récupéré le lien m3u8  ,  mais la vidéo ne se lance pas via hoster 'lien direct'
Voir log:
https://pastebin.com/qaepqvBi

Ya t' il moyen de lire ce m3u8 ou non ? ca a l'air special... 
Merci.

**Comment by milkibreizh** [comment]
kodi n'arrive pas,en effet à lire ce type de fichier 
mais en effet il y a peu être un post traitement ou un procéder qui existe pour qu'il le lise
mais jusqu’ici ici rien n'as été trouvé
autrement si il s'agit des limites intrinsèques du lecteur de KODI comme on le pense..on ne peu rien faire

**Comment by Che-debarras** [comment]
Sauf que le problème est que pas mal de film etc sont vide.
J'aurais espèrer voir les liens dans les films serie Spectacle 
Car qui sait un jour kodi lira les m3u8 ou une soluce arrivera
C'est comme netu, il est present bien qu'il marche pas
Donc si on pouvez voir les liens cest deja un debut

Nb: je sais que chez moi dans de rare cas certains films se lisais
Tout comme kaydo qui parfois marchait chez moi
Mais depuis plus aucun host s'affiche,  tout a disparu.

**Comment by Kpliz** [comment]
@milkibreizh ok merci pour l'info.

**Comment by TmpName** [comment]
Ben le truc c'est si on corrige, on va quand meme avoir des issue comme quoi ca ne marche pas, donc on va pas reparer la source, pour qu'elle ne marhce pas et avoir quand meme des issues.

J'ai retenté aussi, il ya 3 jours, meme resultats.

Par contre si quelqu'un veut tester pour voir si c'est fiable

`http://50.7.179.166/y/file.php?v=nomdufilmsansespace.mp4`

**Comment by Kpliz** [comment]
@TmpName  De mon côté,  après avoir tester plusieurs noms de film,  ca ne lance rien via le navigateur (lecteur mais sans vidéo) ou via vStream.

**Comment by milkibreizh** [comment]
> Par contre si quelqu'un veut tester pour voir si c'est fiable

non, mais cela marche pour toi ?

**Comment by TmpName** [comment]
Ben oui ^^^
`http://50.7.179.166/y/file.php?v=thelie.mp4`

**Comment by yodidon** [comment]
Oui ça fonctionne aussi chez moi

**Comment by Kpliz** [comment]
Pour ce film oui,  pour les autres non...  ^^

**Comment by TmpName** [comment]
ha yep, ca marche pour les vieux avant leur bug. Pas ceux qu'il a rajoute apres ...

**Comment by Che-debarras** [comment]
> ha yep, ca marche pour les vieux avant leur bug. Pas ceux qu'il a rajoute apres ...

Exactement les anciens avant marché puis ya eu une modif qui ne lit plus oi qui s'affiche plus.

Ya pas un clone qui n'utilise pas m3u8?

**Comment by Che-debarras** [comment]
Tout comme kaydo qui a changé pour url wvw.hds.lc
Donc a voir si kepliz a pas une autre url

**Comment by Arias800** [comment]
J'ai fait le tourne de tous les clones que je connais et ils utilisent tous les même liens.
Donc pour le moment je ferme vu que ce n'est pas corrigeable.
