### ISSUE TITLE
Erratum kaydo vide

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3158]
**Décrivez le bug**
Avant la mise a jour on avait les categories, les titres de films et serie et meme les dossiers des hosts bien que vide
Et depuis la mise a jour on a plus rien, quand on ouvre la source c'est vide
Je pense que juste changer url n'est pas suffisant faut refaire la source

**Votre system**
 - OS: [Android]
-  Appareil [k3]
 - Version Kodi  [18.9]
- Version Vstream 0.8 4

**Comment by milkibreizh** [comment]
tu n'as toujours pas accès au contenu des menus ?

**Comment by Che-debarras** [comment]
> tu n'as toujours pas accès au contenu des menus ?

Désolé erreur de ma part c'est pas plntstrmng le pb c'est kaydo, c'est lui qui a ses dossiers vides suite a un changement url dans le fichier.py

**Comment by milkibreizh** [comment]
les dossiers sont maintenant visibles
