### ISSUE TITLE
Accès compte Uptobox

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3159]
Bonjour,

J'ai la bêta de vStream fraîchement installée puis je me rend compte qu'il est impossible d'entrer à l'intérieur de mon compte uptobox.  Je vois bien le popup indiquant que le mode premium est activé, j'ouvre puis une fois aux dossiers ''Recherche'' et ''Mon dossier'', impossible d'aller plus loin.

En version stable, il n'y a aucun problème à y accéder.

Je suis sous nvidia shield
Kodi Leia 18.9
vStream 0.8.4 (beta)

Merci beaucoup à l'équipe pour votre travail !
alKODIque :)

Voici mon log 
[log.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5747268/log.txt)

**Comment by milkibreizh** [comment]
je peux pas tester essaye avec ce fichier je crois avoir vu une erreur
mais je sais pas si cela à avoir avec ton soucis
https://pastebin.com/2rX89q9s

**Comment by sizanic** [comment]
J'ai le même problème, je vais tester ta modif

**Comment by sizanic** [comment]
testé !
ça fonctionne bien avec ta modif 👍

**Comment by milkibreizh** [comment]
c'est def showFile(sSearch='') que j'ai rajouté
la variable sSearch est initialisé nulle part ;if sSearch: = bug

**Comment by sizanic** [comment]
oui, c'est bien ça.
J'ai vu, ta correction est correcte.
Tu peux la commiter.

**Comment by milkibreizh** [comment]
ok

**Comment by razorex** [comment]
en octobre 2018 c'était déjà pas là lol

**Comment by alKODIque** [comment]
Merci beaucoup!!
Probleme résolu pour moi aussi :)
