### ISSUE TITLE
Info sur Themoviedb helper:

### ISSUE THREAD

**Issue by Djej30** [Kodi-vStream/venom-xbmc-addons#3160]
Info sur Themoviedb helper:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper

Mon fichier « player » de vStream:

{ "name" : "vStream", "plugin" : "plugin.video.vstream", "search_movie" : "plugin://plugin.video.vstream/?function=showSearch&sCat=1&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(Films)&action=activate&searchtext={title}/", "search_episode" : "plugin://plugin.video.vstream/?function=showSearch&sCat=2&site=globalSearch&siteUrl=http%3a%2f%2fvenom&title=Recherche%20(S%c3%a9ries%2fAnim%c3%a9s)&action=activate&searchtext={showname}/" }

_Originally posted by @alKODIque in https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2683#issuecomment-561298895_

**Comment by sizanic** [comment]
Bonjour @Djej30 ,
est-ce qu'il y a une question ? 🤔

**Comment by milkibreizh** [comment]
j'ai lu le post #2683 mais je suis désolé j'arrive pas a saisir ton objectif , seulement trop vaguement,
que veux tu faire exactement

**Comment by Djej30** [comment]
Bonjour 
Je vais commencer du début.
Avec un raspberry pi 4 et librelec j'essaie de faire une box tv complète et simple d'utilisation pour moi et ma famille (notamment mes 3 enfants).
Pour cela j'ai appliqué l'habillage auramod, qui ressemble beaucoup à Netflix. Aura mod utilisé a la base tdmb helper et propose des widgets et sous menu en lien avec cette extension. 
Par exemple, dans films il peut y avoir un widget "populaires" avec les miniatures des films, leur résumé, la ba etc.. et également un bouton "play".
De base ce bouton play permet un lancement de YouTube. Il existe des fichiers json qui permettent , si vous installer l'extension correspondante, de la sélectionner a la place de YouTube.
Ex: j'installe l'extension Netflix sur Kodi, je télécharge le fichier netflix.json que je place dans le fichier player de tdmb helper et je peux ainsi choisir Netflix quand j'appuie sur play de la fiche d'un film.

**Comment by Djej30** [comment]
J'avais trouvé cette ligne de code pour créer  le fichier joint pour vstream mais cela ne fonctionne pas et par erreur je l'ai copié ici.
Voilà 😁

**Comment by milkibreizh** [comment]
il faudrait que tu vois comment est organisé le fichiers json pour l'adapter au données de vstream
autrement c'est pas grave si tu as fait une erreur de copie😁

**Comment by sizanic** [comment]
Ces lignes sont normalement correctes pour être utilisées avec TMDBHelper si tu les places dans un fichier vStream.json.

**Comment by Djej30** [comment]
Je vais réessayer

**Comment by Djej30** [comment]
Re 
Cela ne marche pas, j'ais un message : themoviedb helper erreur.

**Comment by milkibreizh** [comment]
tu as bien la fenêtre **Choose Action** avec la liste qui contient l'element **Search vStream**
et c'est bien après quand tu selectionnes que cela ne marche pas ?

**Comment by Djej30** [comment]
Non j'ais le message avant la fenêtre, celle ci ne s'ouvre pas

**Comment by Djej30** [comment]
Autant pour moi, je suis reparti de zéro et jais la fenêtre
 qui s'affiche

**Comment by milkibreizh** [comment]
donc cela marche oui ? non ?

**Comment by Djej30** [comment]
Oui cela marche.
J'ais maintenant des widgets avec tmdb avec les informations les trailers etc et quand je clique sur play j'ai la fenêtre pour sélectionner vstream. Je vais voir si je peux faire en sorte que la recherche démarre dé suite sans ouvrir la fenêtre.

**Comment by Djej30** [comment]
Tout est ok. la recherche se lance direct en appuyant sur play.
Merci pour vos conseils et merci a @alKODIque pour sa ligne de codes.

**Comment by alKODIque** [comment]
> J'avais trouvé cette ligne de code pour créer le fichier json pour vstream mais cela ne fonctionne pas et par erreur je l'ai copié ici.
> Voilà 😁

Si mon fichier player ne fonctionne pas via Auramod, c'est parce que cet habillage n'est plus entretenu par son développeur depuis plusieurs mois. Or, le développeur de Themoviedb helper a fait récemment de grosses modifications à l'addon et que malheureusement, Auramod ne supporte pas puisque l'habillage est dependant de cet addon. Il n'a donc pas adapté son codes aux modifications de TheMovieDb helper. 

Si tu utilises un autre skin, ou bien que tu utilises le player directement dans l'addon (sans passer par ton habillage Auramod) il fonctionne très bien. il suffit de le paramétrer selon les nouvelles exigences

**Comment by Djej30** [comment]
@alKODIque  Cela fonctionne toujours même sur Aura mod. Par contre pour les animés, les recherches ne se font pas toujours sur les liens dédiés (ex otaku.fr ou ADKami) et du coup les résultats ne sont pas top.

**Comment by karimgharbi5** [comment]
j'ai utiliser ce fichier json et ca marcher mais il y a un probleme quand je clique sur un épisode il refais la recherche de toute la serie y a t-il une solution pour ce probleme svp

**Comment by karimgharbi5** [comment]
je veux juste que quand je clique sur la serie dans tmdb helper il fais la recherche sur vstream
