### ISSUE TITLE
Frnchstrm error connexion D.A

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3161]
**Décrivez le bug**
Frnchstrm (catégorie film dernier ajout vide,  erreur de connexion) mais le reste ok

 - OS: [Android]
-  Appareil [k3]
 - Version Kodi  [18.9]
- Version Vstream 0.8 4

**Comment by milkibreizh** [comment]
le lien /films-streaming/ correspondant au dernier ajout ne donne rien non plus dans le navigateur
il faut peu être attendre un peu pour que le site refasse fonctionner ce lien

**Comment by milkibreizh** [comment]
le lien est redevenu fonctionnel 
cela peu évidement revenir mais on ne peu faire autre chose que d'attendre que le site remettent ses liens à jours
