### ISSUE TITLE
Wawa.c.i.t.y

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3163]
**Décrivez le bug**
Les dossiers host de streaming ex mystream ou vidoza etc.. ne s'ouvre plus et  il y a pas de proposition de recaptcha d'image 

 - OS: [ Android]
-  Appareil [k3]
 - Version Kodi  [18.9]
- Version Vstream 0.8.4

**Comment by yodidon** [comment]
je regarde mais je crois qu'il y a un dl protect a passer

**Comment by Che-debarras** [comment]
> je regarde mais je crois qu'il y a un dl protect a passer

Non justement c'est le probleme il ne propose plus de dlprotect a passer

**Comment by kris06** [comment]
Salut j'étais super content de voir apparaitre wawa-city sur votre maj 0.8.3 puis 0.8.4, cependant, aucun lien ne fonctionnent ... Pensez vous corriger cette anomalie sur la prochaine mise à jour ?

**Comment by yodidon** [comment]
En faite le captcha ne fonctionne plus (librecaptcha)

**Comment by milkibreizh** [comment]
non mais j'ai fait un pr il faut juste le valider encore un truc d'encodage....
la modification  du dialogue du 'e' en 'è' "Est-ce que cette image est en lien avec le thème"
à causée le  problème

**Comment by yodidon** [comment]
@milkibreizh , j'avais vu ton pr, mais pour moi ça ne donne rien.

**Comment by Che-debarras** [comment]
Ya quand même une 20aine d'image a vérifier et cliquer
Ca va plus vite en passanr par host direct

**Comment by Arias800** [comment]
Comme déjà expliquer précédemment ont ne peut rien faire par rapport au nombre d'images a vérifié.
