### ISSUE TITLE
Bandes annonces definitions

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3165]
Afin de simplifier les manipulations, ne pourrions nous pas,  recevoir la lecture automatique d'une résolutions par défaut des  bandes annonces ? 

En effet,  je trouve quelque peu inutile, l'ouverture de cette fenêtre qui nous propose de choisir une résolutions  pour  la lecture de la bande annonce

720p me parait ideal...

**Comment by TmpName** [comment]
Bande de feneant.

J'ai modifié un truc, en supposant que ce soit a 100% des videos de youtube.

**Comment by milkibreizh** [comment]
ce n'est pas de la fainéantise
c'est parce qu'a chaque nouvelle année les gens veulent prendre de bonnes résolutions

**Comment by kris06** [comment]
Merci beaucoup la nouvelle formule est parfaite
