### ISSUE TITLE
Mystrm/vidoza limitation de résolution ?

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3169]
**Décrivez le bug**

Je ne sais pas si c'est un bug ou si mystrm suit le meme principe de uptlstrm concernant la limitation des résolutions pour les non premium.

Mais sur wawa.city mystream et vidoza etc... pour les series en 1080p ne s'affiche que en 720p.

Une explication ?

**Votre system**
 - OS: [Android]
-  Appareil [k3]
 - Version Kodi  [18.9]
- Version Vstream 0.8.4

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : wawacity
- Le titre du fim/serie : vikings s06
- Le nom du host (mystrm, vidoza)

**Comment by TmpName** [comment]
Sur Vstream ou le site ?
J'ai voulu tester ma video etait bien en 1280*720*25

**Comment by Che-debarras** [comment]
@TmpName 
Justement sur le site les videos sont en 1080p mais sur vstream comme tu le constate il sont en 720p.
Je ne visionne que mystream car c'est là où ya la meilleur qualité mais je me suis rendu compte qu'il reste sur 720p max et jamais 1080p 

J'ai pas de compte uptobox mais jaurais aimé comparer mystream d'un episode  HD avec le meme episode HD avec uptostream voir si uptostream va jusqu'à 1080p .

(En HD sur wawacity les videos sont en 1080p comme l'indique leur nom de fichier mais sur vstream il sont streaméen 720p).

Et j'utilise host direct car la source wawacity ne marche plus)

**Comment by milkibreizh** [comment]
> la source wawacity ne marche plus

la source wawacity devrait remarcher mais  il faut attendre car j'ai fait un pr

**Comment by TmpName** [comment]
La j'ai pas la Tv dispo pous tester, mais tu as essayer d'utiliser la fonction de telechargmenet de vstream, pour voir si le fichier etait vraiment en 720p ? (Sur vidoza)

**Comment by Che-debarras** [comment]
@milkibreizh 
Oui il fonctionne mais on doit toujours vérifier au moins une 20aines d'images avant d'avoir le lien.
Sinon la résolution est tjrs du 720p max alors que les fichiers sont du 1080p.

Apres celui ci ya 2 autres postes d'utilisateurs qui remarque l'absence de 1080p sur les sources (et de 4k).

**Comment by milkibreizh** [comment]
Pour s03e01  - VF / VF HD vidlox je n'ai pas de lien final validant une video lisible sur le navigateur
donc c'est bien des liens morts
il faut que je trouve une video lisible dans le navigateur et qu'il ne le soit pas par vstream pour
trouver une anomalie
Pour la résolution des films  j'ai lu les issues mais il faut voir cela aussi d'un peu plus près

**Comment by Che-debarras** [comment]
Personnellement y a pas pas vraiment de lien mort sur ce site sauf si film tres ancien.

**Comment by yodidon** [comment]
Oui et pour moi souvent les images demander ne sont pas présentes, et pas de possibilité d’avancer ( thème vélo et seulement une voiture en photo...) bref une source assez pénible à utiliser à mon avis

**Comment by milkibreizh** [comment]
après tout est relatif cela reste toujours du tout cuit pour avoir des videos  ,si quelqu'un veux obtenir un film
bien précis c'est  moins fatiguant de cliquer 11 fois sur une photo de vélo que de faire 11 klm en vélo
c'est surtout pour celui qui ne sait pas vraiment ce qu'il veut et qui clique au hazard pour regarder des films

@yodidon 
est ce que les images non présentes est un problème connu?

**Comment by Arias800** [comment]
C'est pas un bug. En faites Recaptcha envoie de temps a autre des images qui ne correspondent a rien, sauf que sur le site il y a un bouton "ignorer" hors je n'ai pas encore réussi à l'implémenter dans le lib.

**Comment by yodidon** [comment]
Ok merci pour les infos
