### ISSUE TITLE
SOURCE ZONE STREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3171]
Bonjour,

Je suis entrain de créer une Nouvelle Source nommée "Zone Stream" mais elle fonctionne pas.
Pourriez-vous m'aider s'il vous plait en regardant le Code de cette Source au https://pastebin.com/hkqEhPa3
Merci d'Avance !

**Comment by yodidon** [comment]
@ludopotte  oui je viens de regarder , il y a quelque erreurs , si tu veux je peux te dire ce que j'ai vue et corrigé

**Comment by ludopotte** [comment]
Merci @yodidon et je veux bien oui car je veux créer cette Source pour la Communauté. Dis-moi tout.

**Comment by yodidon** [comment]
Tu es sur discord ? Pour éviter de polluer le sujet ici ?

**Comment by ludopotte** [comment]
Oui je suis sur Discord et ca sera mieux sur Discord en effet.

**Comment by milkibreizh** [comment]
> Tu es sur discord ? Pour éviter de polluer le sujet ici ?

et ben tant pis je vais polluer ici car  on ne sait pas ou vous en êtes,ici , tous les 2:
@yodidon 
j'ai viens d'essayer de voir cette source au debugger et le soucis c'est qu'il faut résoudre des hosts qui ne semblent
 pas si simples .il y en a un ou deux simples,(et encore je suis pas sur donc il n'y a que proton video )ce qui fait que parfois tu as des films que tu ne peux pas lancer car il apparait  parfois seulement les hosts non résolus,ceux qui peuvent être résolus n'apparaissent pas toujours...de plus mais à revérifier tous les séries c'est du netu et pour la résolution des hosts je crois que le problème viens de la fonction eval w.i.s.e un fonction qui renvoie sa propre fonction avec les 4 paramétres qui vont  sans cesse changer de façon récursives j'usqu 'à peu être afficher les valeurs finales.....enfin j’espère me tromper en disant que c'est bien cette fonction qui détermine les paramètres des hosts..un truc à bien pu m' échapper



....

**Comment by yodidon** [comment]
Merci @milkibreizh , l’idée était surtout de coder une source , pas forcément trouver la source , donc il avance et comprend le principe et si cette source n’est jamais utilisée elle aura l’avantage de l’avoir lancé.

**Comment by milkibreizh** [comment]
oui c'était juste pour prévenir car j'avais jeté un coup d'yeux,et je savais pas ou @ludopotte en était
il n'est bien sur jamais inutile de s'entrainer à faire des sources sans faire pour autant faire la résolution des hosts il y a déjà assez de choses à apprendre au début...chaque chose en son temps..
pour les hosts  sans doute qu'ils sont resolvables je parlais juste pour moi  de ce que j'avais debuggé,cette source
devrait sans doute être utilisable
autrement @ludopotte peu poser des questions, il n'y à aucune question idiote. 
c'est seulement les réponses qui peuvent l’être

**Comment by yodidon** [comment]
Oui tu as bien raison @milkibreizh , il commence et se pose plein de questions j’imagine, notre discutions sur discord n’avais rien de privé mais plus simple pour commencer, après avoir regarder son code je me suis dit que certaine chose étaient plus simple a expliqué pas ce biais.

**Comment by ludopotte** [comment]
Merci @yodidon et @milkibreizh pour votre soutien et aide mais si vous avez des conseils ou autres, je suis preneur.

**Comment by milkibreizh** [comment]
il faut ne faut pas que tu t'intiquietes le plus dur c'est les premières sources
bien que tu auras toujours un pourcentages de sources qui seront toujours difficiles à faire
car on est pas des programmeurs

**Comment by sizanic** [comment]
@ludopotte 
Je t'aurai bien aidé moi-même.

Mais je vois que tu es entre de bonnes mains 😄 

N'hésitez pas à me solliciter sinon.

**Comment by ludopotte** [comment]
Merci @sizanic et j'hésiterais pas à te contacter avec plaisir pour que tu m'aide.

**Comment by sizanic** [comment]
@ludopotte 

où en es-tu avec cette source ?
Ce ticket est-il toujours d'actualité ?
As-tu toujours besoin d'aide ?

Sinon, merci de clore ce ticket.

**Comment by ludopotte** [comment]
@sizanic 

Tu peux clore ce Ticket car je me débrouille pour cette Source via Discord.
