### ISSUE TITLE
Beta vs Kodi Matrix

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3172]
Bonjour, 
aujourd'hui J'ai refait un test vStream en installant Kodi v19 dans sa dernere Pre-release.

Voici mon log qui démontre les erreurs que je rencontre, soit:

- Incapable d'ouvrir mon dossier (compte Premium) Uptobox;
- Source PasteBin - Impossibilité d'ajouter des Ids / pastes... erreur: ''erreur initialisation'' (je me suis assuré que mes pastes étaient bel et bien fonctionnels)

Kodi 19 beta 2
Vstream 0.8.4 beta
nvidia shield - android

Merci et bonne journée! :)
[kodi.log.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5780967/kodi.log.txt)

**Comment by Arias800** [comment]
Normalement les deux problèmes sont désormais corrigés dans la beta.

**Comment by PassionFlix** [comment]
@Arias800 Salut,
Si je peuxme permettre, je viens de tester Matrix et la dernière bêta
j'arrive a rentrer dans mon compte premium uptobox et accéder a mes dossiers et fichiers mais j'ai un msg d'erreur qui apparait
2021-01-11 21:25:48.803 T:4920     INFO <general>: 	[PLUGIN] vStream: Utilise compte premium pour hoster uptobox
2021-01-11 21:25:48.951 T:4920     INFO <general>: 	[PLUGIN] vStream: Cookies non valables
2021-01-11 21:25:49.085 T:4920     INFO <general>: 	[PLUGIN] vStream: Erreur: Connexion Impossible (302),https://uptobox.com/?op=login&referer=homepage
2021-01-11 21:25:49.093 T:4920     INFO <general>: 	[PLUGIN] vStream: Auhentification reussie

Si tu veux mon log
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5798192/kodi.log)

**Comment by sizanic** [comment]
> Source PasteBin - Impossibilité d'ajouter des Ids / pastes... erreur: ''erreur initialisation''

Corrigé dans la Beta.

**Comment by Arias800** [comment]
@PassionFlix c'est liée a la manière dont requests gère les messages d'erreur.
Je n’ai pas le temps de m'en occupé et comme c'est mineur ce n'est pas ma priorité.

**Comment by 0x0040** [comment]
Le fichier resources/hosters/uptostream.py ne marche pas sous Matrix/Python 3.
Selon moi, le problème vient de :
- xrange qui n'existe plus sous Python3
- la fonction base64.b64decode dont le résultat change entre Python3 (bytes)/Python2 (str)

**Comment by TmpName** [comment]
Je n'ai pas de compte pr tester @0x0040 Mais rajoutes ca dans le fichier pr tester

```
try:
    xrange
except NameError:
    xrange = range
```

en tete du fichier

Et essayes en remplacant

`data = base64.b64decode(data)`

par 

`data = base64.b64decode(data.encode())`

**Comment by Arias800** [comment]
J'ai mis une version en teste dans la beta, ça devrai régler le problème.
