### ISSUE TITLE
Source en 1080p/4k

### ISSUE THREAD

**Issue by shkope** [Kodi-vStream/venom-xbmc-addons#3175]
bonjour, ya t-il des sources qui propose des films en 1080p/4k ?
tres souvent je ne trouve que du 720p maximum..
merci!

**Comment by sizanic** [comment]
Bonjour,

Si tu utilises des liens Uptobox, tu sera effectivement limité en résolution si tu n'as pas de compte.
Avec un compte premium Uptobox ou Alldebrid, les mêmes liens sur les mêmes sites seront en 1080p (pas tous mais beaucoup).

**Comment by Che-debarras** [comment]
> bonjour, ya t-il des sources qui propose des films en 1080p/4k ?
> tres souvent je ne trouve que du 720p maximum..
> merci!

Justement je me pose la question sur un de mes posts concernant wawacity
Les episodes HD sont clairement du 1080p mais sur vstream ils sont en 720p max
Et je parle pas de uptobox mais de mystrm ou vidoza
Je pense que quelque chose limite la résolution

**Comment by shkope** [comment]
donc pour avoir du 1080p il faut avoir un compte premium ?
autant s'abonner a netflix lol

**Comment by TmpName** [comment]
Il est ou le probleme ? le 720p passe tres bien sur une TV 4k.
Surtout que j'ai plein de source qui n'existent meme pas en 1080p.


> Batwoman.S01E06.FRENCH.1080p.BluRay.x264-Wawacity.vip.mkv
> C'est bien du 1080p sur wawacity mais sur vstream on a 1280px720p max


J'ai voulu tester lien HS, pas un autre exemple ou la video sur Vstream n'a pas la meme resolution que celle sur navigateur ?

**Comment by thorsten68** [comment]
Sur un vidéo-projecteur promis on fait bien la différence entre un 4k et un 1080p
Je cherche aussi des films en grosse qualité, ayant un Premium 1fic et la fibre ça passe bien, mais peu de site pour les trouver. Wawa ça marche pas, tirexo non plus. Ztza c'est encore le mieux mais souvent des soucis
P. S: je ne me permettrais pas de critiquer votre taf

**Comment by TmpName** [comment]
Il y a pas de soucis, c'est juste que ca me fatigue ce formatage, tu prend un bon film comme "mon nom est personne" qui n'existe pas en 4k (perso j'ai galere comme un porc pour trouver un truc potable), ben ce film la "ne rend pas bien sur l'ecran".
Par contre une bonne bouse filmé en 4k, ca c'est le top.

La qualité d'un film se note par rapport a sa resolution maintenant. Franchement j'ai connu la TV cathodique en noir et blanc, pourquoi mon oeuil n'a pas muté comme tout les autres pour ne plus le supporter ?

**Comment by sizanic** [comment]
vStream n'est pas responsable des qualités mises à dispositions par les différents sites, ni de la nécessité d'avoir un compte premium.

Voir ce sujet : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3179
qui répond également à la question.
