### ISSUE TITLE
Compte Uptobox premium et jackets des films description

### ISSUE THREAD

**Issue by glardz95** [Kodi-vStream/venom-xbmc-addons#3177]
Bonjour,

J'ai un compte Uptobox premium, je regards mes films uptobox depuis vstream
J'aimerai savoir comment avoir les jackets des films et description des films,

Je sais qu'il y a oxmosis mais je ne sais pas si cela fonctionne, auriez vous un add-on pour le jackets des films et description pour vstream ?

**Comment by TmpName** [comment]
Ca suffit pas d'activer juste les metas ?

**Comment by yodidon** [comment]
Chez moi ça a suffit 👍

**Comment by glardz95** [comment]
C'est a dire activer les méta ?, Je suis nouveau sur vstream, pourriez vous m'indiquer comment faire, merci

**Comment by yodidon** [comment]
Dans la configuration de vstream tu as cette option

**Comment by glardz95** [comment]
Je viens d'activer search metadata (slowed vStream) mais toujours rien, 

Quand je vais dans vstream>my account>Uptobox>mes fichiers et dossiers, j'ai toujours pas l'affiche et les resumés

**Comment by alKODIque** [comment]
> Je viens d'activer search metadata (slowed vStream) mais toujours rien,
> 
> Quand je vais dans vstream>my account>Uptobox>mes fichiers et dossiers, j'ai toujours pas l'affiche et les resumés


Malheureusement, vStream ne récupère pas les informations de ton compte uptobox premium. Même en activant les metadonnees, ce ne sera pas plus efficace. A l’intérieur de ton compte UPTOBOX, ce ne sont que des liens. Donc, vStream récupère les liens. Il faut comprendre que vStream agit un peu comme un moteur de recherche: il te donne l’information qu’il trouve à l’endroit demandée.Si elle n’est pas présente, il ne peut pas te la donner...

**Comment by glardz95** [comment]
Ce qui veut dire que pour chaque lien Uptobox je dois créer des metadonnées ?

**Comment by sizanic** [comment]
Très bien résumé @alKODIque 
pour la partie théorique.

Dans la pratique, pour bien comprendre comment vStream obtient les métadonées à partir d'une source sur un site comme ZT par exemple : 
- par la navigation dans les menus, vStream sait s'il s'agit d'un film ou d'une série.
- le titre du film est propre sur le site (rien que le titre)
- l'année du film est affichée dans un coin de la page, à coté de la pochette, vStream analyse la page pour retrouver cette information.

Donc vStream à les information : **Film + Titre + Année.**
Ce sont les données nécessaires pour une recherche des métadonnées.

Il est difficile d'extraire les données minimum d'un lien uptobox qui se présenterait sous cette forme : 
_Step.up.revolution.2012.3d.multi.1080p.bluray.dts.x264-jass-zone-telechargement.ws.mkv_

**Comment by glardz95** [comment]
Même si on utilise plex a la place de kodi ?

**Comment by sizanic** [comment]
Il existe une version de vStream sous Plex ?

**Comment by glardz95** [comment]
Non il n'y a pas de vStream sous plex, je voulais dire si on utilise plex a la place de kodi, plex peut il trouver des affiches et resumer à partir de Step.up.revolution.2012.3d.multi.1080p.bluray.dts.x264-jass-zone-telechargement.ws.mkv

**Comment by sizanic** [comment]
> Non il n'y a pas de vStream sous plex,

Je me disais bien aussi, vu qu'ici c'est la team de développement de vStream pour KODI.

On ne connait pas Plex ici 😄 

Personnellement, je n'ai jamais utilisé Plex.
Je ne peux pas te dire.

**Comment by glardz95** [comment]
Auriez vous un autre moyen pour recupérer les jackets sans passer par les méta données ?

**Comment by sizanic** [comment]
Peut-être en installant l'addon tmdbHelper, mais je ne suis vraiment pas sûr, le problème doit être le même.
@alKODIque va nous confirmer ça.


Sinon, tu peux passer par la source Pastebin.
Rends toi sur le Discord "Pastebin" : https://discord.gg/Q8PEWuN
Il y a un salon "Comment partager" qui t'explique comment rendre tes liens uptobox visibles dans vStream.
Et tu auras bien toutes les métadonnées en passant par ce moyen.

**Comment by sizanic** [comment]
En complément de theMovieDB, il faut peut-être aussi utiliser l'addon : 
_Universal Movie scraper_

**Comment by alKODIque** [comment]
@sizanic 
Et bien via kodi directement et/ou en passant par tmdb helper, ce n'est pas possible non plus de récupérer les liens de son compte uptobox. Contrairement à vStream, ni Kodi ni TMDb helper peut décrypter les liens présents dans notre compte. donc les liens ont l'apparence suivante: 
https://uptobox.com/qeffhgdejju

donc Plex ne pourra pas voir non plus, ni aucun autre média centre s'il n'est pas équipé d'un outil pouvant décrypter les liens. 

Pour revenir à Kodi, admettait que les liens uptobox soient décryptés et présentés sous la forme du lien que tu mentionne plus haut, à ce moment oui, il pourra le lire et extraire les métadonnées,  au même titre qu'il le fait avec les dossiers http// (tel que nos dossiers Alldebrid- pour les abonnés, ainsi que les index of// que l'on trouve sur le net)

**Comment by sizanic** [comment]
> via kodi directement et/ou en passant par tmdb helper, ce n'est pas possible non plus de récupérer les liens de son compte uptobox. 

Je ne pensais pas à la récupération de lien avec tmdbhelper, mais juste à du scrapping.

Avec "_Universal Movie scraper + tmdb_" il devrait être possible de scrapper un nom de fichier : 
Step.up.revolution.2012.3d.multi.1080p.bluray.dts.x264-jass-zone-telechargement.ws.mkv

**Comment by alKODIque** [comment]
oui, j'ai modifié mon commentaire car c'est bien ce que je voulais dire. mais les liens uptobox n'ont pas cette forme puisqu'ils sont cryptés à la base

**Comment by sizanic** [comment]
Lorsque je vais sur mon compte upto en passant par vStream / comptes / Mes fichiers, c'est bien le nom du fichier qui apparait, et pas le lien upto : 
Step.up.revolution.2012.3d.multi.1080p.bluray.dts.x264-jass-zone-telechargement.ws.mkv

Donc un scrapper devrait pourvoir se débrouiller.

**Comment by alKODIque** [comment]
oui absolument! si (et seulement si) le lien est intégré à la médiathèque par défaut de kodi 

il est possible d'utiliser la fonctionnalité via vStream mais ce n'est pas convivial puisque il faut le faire un lien a la fois (imagine les séries!!!)

**Comment by alKODIque** [comment]
Ha!
il y a présentement des outils tels que Library Integration tools qui le font, mais je ne conseille pas puisque l'addon nest plus entretenu et écrit en python 2... donc la médiathèque crée grâce à cet outil deviendra inutilisable lorsque kodi passera en v19. 

il y a également l'addon Osmosis qui peut être une solution puisque il a été repris par "KodiNerds" et adapté python 3!

**Comment by glardz95** [comment]
Comment puis je appeler la fonctionnalité offerte par vStream pour l'ajouter a la mediathèque ?

**Comment by alKODIque** [comment]
Appui long sur le lien que tu veux ajouter et sélectionner “ajouter à la médiathèque” via le menu contextuel. Mais attention! Il te faudra également renommer ton fichier adéquatement pour les séries … c’est très pénible: pour chaque épisode, tu dois faire 2 manipulations: 
1- taper le nom de la série 
2- taper le nom de l’épisode 

et attention! Chacun des épisode, lors de la manipulation no 1 doit respecter la casse sinon un dossier différent de série se crée...

Pour les films, de mémoire ça fonctionne bien, mis à part le fait qu’il faille les entrer un à la fois

**Comment by glardz95** [comment]
J'ai bien ajouté fait ajouté dans la mediathèque puis ensuite je vais ou pour voir la vidéo ?

**Comment by alKODIque** [comment]
maintenant il ne te suffit que d’aller récupérer ton dossiers “films” et ton dossier “séries” créé par vStream via les paramètres de kodi comme tu le fais pour tes médias personnels. Il se trouve par défaut dans le dossier addon_data de vStream

Voir le forum kodi.tv pour la procedure d’ajout à la médiathèque

**Comment by glardz95** [comment]
Je suis parti dans vStream>tools>library,>films, je vois mon film avec uniquement des lettres et des chiffres mais pas de jacket ni resumé

**Comment by alKODIque** [comment]
C’est normal, tu es demeuré à l’intérieur de vStream et comme expliqué plus haut, vStream ne lis pas les metadonnees pour ton compte UPTOBOX.

Maintenant que tu as ajouté ton lien à la médiathèque, tu dois sortir de vStream car pour la suite, c’est des fonctionnalités de base assurées par Kodi dont tu as besoin. VStream n’entre plus en jeu. 

C’est pourquoi je te réfère au forum kodi.tv pour la suite car la procédure pour ajout de média est la même peu importe le dossier ajouté.

**Comment by glardz95** [comment]
J'ai vérifié sur le forum de kodi.tv mais il ne parle pas des library films de vStream, je comprends que vStream transforme le lien mais il est nul part sans vStream, je n'arrive pas a voir les liens que j'ai transforme dans kodi, pourriez vous m'aider, merci
