### ISSUE TITLE
CHAINE YOUTUBE DANS VSTREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3178]
Bonjour,

Est-ce que c'est possible de créer une Source d'une Chaine YouTube pour l'avoir dans vStream ?

Cordialement,
@ludopotte

**Comment by TmpName** [comment]
Hello, ben de mon coté j'utilises tout simplement l'addon youtube, tout est fini dedans.

**Comment by ludopotte** [comment]
Ok @TmpName mais j'aimerais bien partager des Chaînes de YouTubeur pour leurs contenus.
