### ISSUE TITLE
Où trouver du contenu 4k

### ISSUE THREAD

**Issue by glardz95** [Kodi-vStream/venom-xbmc-addons#3179]
Bonjour,

J'essaie de voir du contenu 4k sur vStream depuis zt-za mais je ne vois que du contenu 1080p max, aurait il un moyen de voir du contenu 4k comme dans le site internet zt-za ?

**Comment by sizanic** [comment]
Bonjour,

Peux-tu nous donner un lien d'exemple qui est en 4K sur ZT-ZA ?

**Comment by glardz95** [comment]
Dans la rubrique ultra hd 4k

https://www.zone-annuaire.top/?p=films&s=ultra-hd-4k

**Comment by yas06** [comment]
salut zone annuaire .top c un clone sinon pour repondre 
source vstream  zt  ,extreme down ,wawacity on une categorie 4K dans film
free telechargement a une categorie uhd 4K
ps faut un debrideur tout les liens 4k son chez des 1fi,upto,rapidgat,  ect

**Comment by glardz95** [comment]
salut, merci, je viens de voir, par contre j'ai des soucis avec les capcha, la page du capcha me demande véhicule, je clique sur tout les véhicules mais cela ne marche pas, de mémé pour les thèmes.

**Comment by KoRnEr007** [comment]
Sinon y en a sur la source pastebin.

**Comment by glardz95** [comment]
Comment utilise t'on une source pastbin ?

**Comment by alextreme7711** [comment]
C est quoi la source pastbin??

**Comment by Che-debarras** [comment]
Si ya moyen d'installer toutes les pastebins en 1 fois ce serait cool car yen a tellement.
Donc si vous avez une méthode pour installer All in One je serais preneur et reconnaissant

**Comment by KoRnEr007** [comment]
@Che-debarras nous donnons un zip sur le discord pour faciliter l'installation et la configuration

**Comment by Che-debarras** [comment]
> @Che-debarras nous donnons un zip sur le discord pour faciliter l'installation et la configuration

Je trouve pas le zip sur discord

**Comment by sizanic** [comment]
Dans le salon "tuto".

**Comment by Che-debarras** [comment]
@sizanic par contre ca supprime les favoris 
Ya moyen de les récupérer ?

**Comment by sizanic** [comment]
Il y a une fonctionnalité de sauvegarde/restauration des favoris, disponible dans les paramètres de vStream.

Si elle ne fonctionne pas, je t'invite à créer un autre ticket 😉 

J'irai voir l'addon en question ...

**Comment by Che-debarras** [comment]
> Il y a une fonctionnalité de sauvegarde/restauration des favoris, disponible dans les paramètres de vStream.
> 
> Si elle ne fonctionne pas, je t'invite à créer un autre ticket 😉
> 
> J'irai voir l'addon en question ...

Pour l'addon en question faut lire le lien car ce dev fait payer sa source personnelle (il faut se logger avec un compte mais c'est payant) .
Quand je lis ça je peut que vous remercier pour le temps le travail les efforts que vous faites tous pour un addon gratuit car bcp tombe dans le bizness (cloudflarescraper,cet addon ou ce fameux application watch3d).

Triste nouvelle année

**Comment by Che-debarras** [comment]
@glardz95 
Tu a maintenant du 4k sur Zt avec uptobox si le film a bien été uploadé 
Car j'ai testé et ils sont bien en 4k mais tu peut tomber sur du sd ou hd
En gros uptobox ne limite plus la résolution

**Comment by sizanic** [comment]
>@glardz95 
Comment utilise t'on une source pastbin ?

> @alextreme7711 
C est quoi la source pastbin??


La source Pastebin permet de partager des liens uptobox entre particuliers.

Voir le premier message de ce sujet :
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3045

**Comment by sizanic** [comment]
La question posée pour ce ticket a été répondue.

Je clos cette demande.
