### ISSUE TITLE
Kodi prend un film pour une musique !

### ISSUE THREAD

**Issue by Digidix** [Kodi-vStream/venom-xbmc-addons#3182]
Bonjour,

Je souhaite savoir si d'autres personnes ont le même problème que moi, c'est-à-dire lorsque j'essaye de lancer la lecture d'un film en Blu-ray 1080p multi (peu importe le site), très souvent Kodi me lance la bande sonore du film, avec sur mon ecran la pochette du film et un cd qui tourne comme si j'avais mis un cd de musique.

Si je lance un film en 1080 sans l'inscription Blu-ray multi pas de problème.

Pour savoir si vous avez le même problème, il suffit de regarder, par exemple, le film 1917 :

menu -> sources -> ZT -> films -> exclus -> 1917 -> Blu-ray 1080p multi -> upto ou 1f

À savoir que j'ai essayé presque tous les réglages possibles sans succès et que le problème arrive sur mes deux périphériques, une tablette sous Android 9 et une box tv sous coreelec, Kodi leia avec juste le skin Aeon Nox: SiLVO et V stream d'installés, installation récente.

Je pense bien évidemment que le problème est plus du côté de Kodi, mais si je poste sur le forum de Kodi on va de suite me dire que l'addon n'est pas légale, etc...

Merci !

**Comment by Arias800** [comment]
Impossible de reproduire le problème. Je pense que tu ferai mieux de faire une installation propre de Kodi.

**Comment by JamesTurner765** [comment]
Bonjour. J'ai eu pareil sur zt oui. Mais dans mon cas c'est juste qu'au lieu de sélectionner les lien dans la catégorie premium du bas j'ai sélectionné les lien de la première catégorie.

**Comment by Digidix** [comment]
Merci à vous deux pour votre retour !

Effectivement, si je prends les liens premium en dessous des premiers liens, ca semble fonctionner correctement, du coup je ne sais pas ce qui déclenche ce "bug", mais depuis tout est ok, donc ca ne semble pas provenir de l'installation de Kodi ou Vstream (fresh install récente).
