### ISSUE TITLE
Uptostream ne marche pas

### ISSUE THREAD

**Issue by pixelroll** [Kodi-vStream/venom-xbmc-addons#3183]
**Décrivez le bug**
Bonjour, 

quand je sélectionne uptostream, kodi me dit que le fichier est introuvable.
Hors j'ai besoin d'uptostream pour avoir les sous titres car sur uptobox ils n'y sont pas (sur zone de téléchargement).
 Je ne possède pas de compte premium mais un gratuit.
Comment faire pour que uptostream marche et ainsi avoir les sous titres ?

Merci.

 - OS: [Windows, Android]: android tv
-  Appareil [nvidia shield, Ultra]; xiaomi tv stick
 - Version Kodi  [16.17.18]: 18
- Version Vstream : 0.8.4
- Le nom du site: zone de téléchargement
- Le titre du fim/serie: Dr. stone
- Le nom du host : uptostream

**Comment by milkibreizh** [comment]
j'ai fait une modification du host mais elle ne concerne pas tous les types de fichiers Uptostream
cette modification ne vas pas forcement donc résoudre ton problème mais tu peux déja tester la beta
pour voir

**Comment by pixelroll** [comment]
@milkibreizh merci mais même avec la version beta sa ne marche pas. 
Peut être je l'ai mal installé ?
J'ai pris le .zip proposé en bas du github et j'ai installé avec l'option zip sur kodi.
J'ai ensuite eu une notification comme quoi vstream avait été mit à jour.
Peut être fallait il tout désinstaller ?

**Comment by milkibreizh** [comment]
il vaut mieux désinstaller complétement vstream dans le doute si tu installe une beta
autrement tu peux teste deux liens valident

cinemay /film dernier ajout / l'un des nôtres > host uptostream
zustream/film/film dernier ajout/cosmoball HD VF/ cosmoball #2 HD VF / > host uptostream

normalement le premier lien devrait toujours fonctionner si tu utilises la mise à jour normale
tandis que le deuxieme liens n'est fonctionnel que dans la dernière bêta

**Comment by sizanic** [comment]
@pixelroll 

si tu reprends une nouvelle Beta à l'instant, as-tu toujours des difficultés à avoir les sous-titres avec Uptobox, ou à passer sous UptoStream ?

**Comment by sizanic** [comment]
@pixelroll

avec la nouvelle version 0.8.6 sortie hier, as-tu toujours des difficultés à avoir les sous-titres avec Uptobox, ou à passer sous UptoStream ?

Sinon, merci de clore ce ticket.

**Comment by sizanic** [comment]
Des corrections dans la dernière version.
