### ISSUE TITLE
Maj resolveurl pour doodstream et evoload

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3184]
Pensez vous que ces 2 maj de resolveUrl peut resoudre le souci de doodstream et evoload (source strmngprvs)

https:// github.com/jsergio123/ script.module.resolveurl/blob/master/lib/resolveurl/plugins/evoload.py

https:// github.com/jsergio123/ script.module.resolveurl/commit/2f232989c6844729483120ecc0234a28d1cc7864

**Comment by TmpName** [comment]
Il semblerait, le site originel est celui la je pense https://github.com/addon-lab/addon-lab_resolver_Project/

Pour evoload du moins, doodstream passe tres bien chez moi.

Si personne s'y colle je peux y jetter un oeuil demain.

**Comment by milkibreizh** [comment]
> Il semblerait, le site originel est celui la je pense https://github.com/addon-lab/addon-lab_resolver_Project/

je n'ai pas oublié de précisé dans la source evaload.py la provenance et donc ce lien pour le squellette du code principal et je n'ai pas utilisé en effet le lien de jsergio123 à part pour trouver le lien justement

**Comment by Che-debarras** [comment]
Autant pour moi mais vous avez raison il faut rendre a César ce qui appartient a César comme on dit.
Est ce qu'il sont visibles sur vstream?

**Comment by milkibreizh** [comment]
> Autant pour moi mais vous avez raison il faut rendre a César ce qui appartient a César 

tu pouvais pas savoir c'est jsergio123 qui a précisé sa source....donc j'ai été à la source^^
