### ISSUE TITLE
ZT pas capable de passer page no2 des filmes 4K  

### ISSUE THREAD

**Issue by alextreme7711** [Kodi-vStream/venom-xbmc-addons#3185]
Salut!
comme décrit dans l titre, je suis incapable de passer la page no2 ds ZT pour les filmes 4K
Kodi crash completement... je doit carrément fermer kodi et le restarter... tout fige et impossible de faire quoi que ce soit...
J ai fait un reset factory de la nvidia, j ai essayé avec Kodi 17.6 et même scenario...
En fait j étais curieux de savoir si j étais le seul...
Merci à l avance...

Os:Android
Nvidia shield tv
Kodi 18.9
vstream 0.8.4

**Comment by milkibreizh** [comment]
le problème a été réglé sur le bêta

**Comment by alextreme7711** [comment]
Oh!! yesss j essaie ca...Merci

**Comment by alextreme7711** [comment]
Je confirme... ca fonctionne!!
Merci enormément!!
