### ISSUE TITLE
Tirexo les liens ne s affiche plus

### ISSUE THREAD

**Issue by alextreme7711** [Kodi-vStream/venom-xbmc-addons#3186]
Allo!
les liens Tirexo ne s'affiche plus... en fait quand je clic sur filmes, et ensuite filme 1080p par exemple,
ya rien qui s affiche...
J passe par PIA vpn... j ai beau changé de région y a rien qui marche...
Merci

Os: Android
Nvidia shield TV
Kodi 18.9
Vstream 0.8.4

**Comment by Che-debarras** [comment]
Tirexo ne marche pas sur android depuis des mois car cloudfare si je me souviens bien.
Il marche sur Windows avec Selenium si j'ai bonne mémoire et si c'est toujours d'actualité

**Comment by alextreme7711** [comment]
Bon c est dommage, 
Merci pour l info!!!
