### ISSUE TITLE
(Android) Extreme-down plus de capcha et plus de liens...

### ISSUE THREAD

**Issue by alextreme7711** [Kodi-vStream/venom-xbmc-addons#3188]
Même avec le Vpn en changeant de region,
lorsque je clic sur un filme, y a plus de capcha et du coup, plus de liens non plus...
Merci!!

Os: Android
Nvidia shield TV
Kodi 18.9
Vstream 0.8.4
Vpn PIA

**Comment by lelooser** [comment]
Je n'ai plus les liens qui s'affichent depuis cette modif 43ca6c3 avec mon token allde brid gratuit. Est ce que c'est normal?
Du coup j'ai mis ça 0146184 en supprimant la modif 43ca6c3.

**Comment by sizanic** [comment]
Essayez d'activer le mode premium dans les paramètres : 

![image](https://user-images.githubusercontent.com/47307622/107701394-24f94e80-6cb9-11eb-8a71-2809eeed7df9.png)

**Comment by lelooser** [comment]
Merci @sizanic mais En activant le mode premium allde brid dans les paramètres de vStream, le lien s'affiche en all de brid et non en Up to box. Du coup ça ne marche pas car j'ai un compte gratuit sur all de brid et compte premium en up to box. Ça fonctionné bien avant cette modif. J'avais bien le lien en up to box.

**Comment by Arias800** [comment]
C'est corrigé dans la beta. Cette option ne n'aurai jamais du nécessité l'activation de d'Alldebrid dans les paramètre.

**Comment by sizanic** [comment]
> Cette option n'aurai jamais du nécessité l'activation de d'Alldebrid dans les paramètres.


En effet, l'option "token d'un compte gratuit" n'a pas besoin de l'option "Activer compte premium" 👍 
Mais il faudrait revoir comment on peut informer (dans l'écran des paramètres) qu'il est possible de mettre un token gratuit en gardant l'option "Activer" non active.

Car ça ne se devine pas 🤔 

Proposition de remplacement de texte : 
- "Activer"  -> "Activer Premium"
- "Token"    -> "Token Premium ou gratuit"


On comprend que "Activer" sert à activer le premium, mais qu'il est possible de renseigner un token premium ou un token gratuit.

**Comment by Arias800** [comment]
Oui, bonne idée. Car au moment où j'avais implémenté ça la question ne se posais puisque Vstream ne supportait pas Alldebrid en tant que débrideur.

**Comment by falciatrice10** [comment]
![20210316_173051.jpg](https://user-images.githubusercontent.com/42334843/111345251-6052b880-867d-11eb-97c4-b748bc0b4ebf.jpg)

J'ai toujours le captcha même avec le tojen alldebrid (extreme download,  liens uptobox)
