### ISSUE TITLE
PROBLEME AVEC ZONE TELECHARGEMENT

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3192]
Depuis le Changement d'Adresse du Site, il faut changer les DNS pour y avoir accéder sur Ordinateur et Android.
Pour cela, changer les DNS sur PC au https://www.futura-sciences.com/tech/questions-reponses/informatique-changer-serveur-dns-windows-10-11890/ et sur Android avec les Applications "Blokada" et Blokada Slim" au https://blokada.org/?lang=fr

**Comment by Arias800** [comment]
La protection Stormwall a changé, je bosse dessus.

**Comment by ludopotte** [comment]
Ok @Arias800 mais je fais un teste et il y a plus besoin de changer de DNS que ce soit sur Windows, Android et iOS

**Comment by alextreme7711** [comment]
De mon coté, j ai; ERREUR DECRYPTAGE DE LIEN...
ca c est remis a fonctionner hier, mais aujourd hui c est non fonctionnel...
Je sais pas si c est en rapport avec cette issue mais 
j ai essayé plusieurs DNS avec Blokada et rien ne marche...
**Merci pour votre travail!!** 

Android
nvidia shield
kodi 18.9
vstream 0.8.4

**Comment by ludopotte** [comment]
Bonjour @alextreme7711, pour régler ton problème faut que tu mette vStream à jour avec la Version 0.8.5 et après installe la Beta au https://github.com/ludopotte/vStream/

**Comment by alextreme7711** [comment]
Effectivement **ludopotte**, après avoir installer MAJ tout va no1!!
Merci infiniment!!!

**Comment by 0x0040** [comment]
Le commit https://github.com/Kodi-vStream/venom-xbmc-addons/commit/22ac85759f4dad1b3b89ac131d74f748abaf9844 de @Arias800 résolu le problème.
