### ISSUE TITLE
Proposition de nouvelles sources Animés

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#3196]
Bonsoir a tous alors voila j ai 3 proposition de lien animé pour les ajouts 

h_ttps://funeralforamanga.fr/  ==> Ajouté
h_ttps://www.jetanimes.com/  ==> Sous CloudFlare
h_ttp://animeresistance.co/

Merci la team Vstream pour tout

**Comment by amahmou** [comment]
Oui super proposition, les sources anime fonctionnelles  actuellement sont nulles , et www.ianimes.org + https://otakufr.co/ sont hors service. 

Merci d avance.

**Comment by milkibreizh** [comment]
il y a eut une correction sur la bêta pour otakufr
et ianime semble en effet HS

**Comment by Mokoman30** [comment]
Super je mettrais à jour si je trouve d autre source animé comme sa quand ianime e off ou autre on utilisera cela

**Comment by milkibreizh** [comment]
tu peux en effet nous proposer des sources d'animes
il y a vostrfree et toonanime en cours autrement

**Comment by amahmou** [comment]
https://dbanimes.com/
http://www.mavanimes.co/

**Comment by milkibreizh** [comment]
mavanimes c'est mort il y a cloudfare

**Comment by Mokoman30** [comment]
il faudrais trop trouver une solution contre le cloudfare

**Comment by amahmou** [comment]
https://anime-saikou.com/
http://lienanime.com/
https://www.lazonemanga.fr/manga?m_orderby=latest

**Comment by amahmou** [comment]
https://www.tvaddons.co/kodi-addons/show/script.module.cloudflare.scrape/ 

je n ai pas encore  essaye cette solution, mais c est une bonne piste

**Comment by Mokoman30** [comment]
je propose également quelque chose côté TV streaming etranger 

Xumo tv
Pluto Tv qui arrive en france également avec de la pub contre des chaînes gratuites mais on peut contrer les pub avec vstream

**Comment by TmpName** [comment]
Le code date de 2016, je ne pense pas qu'il fonctionne encore.

**Comment by Arias800** [comment]
Je viens de rajouter le site Vostfree. Il y a certains hébergeurs qui n'apparaissent pas puisque pour le moment je n'ai pas encore fait le code pour ces derniers mais il y a déjà pas mal d'hébergeurs qui marche.

**Comment by milkibreizh** [comment]
@Arias800 
si tu veux savoir comment se font la liste de tous les hosts il faut parser le fichier
https://vostfree.com/templates/Animix/js/anime.js
il te donne tous les 3 parametres pour construire l'host
par exemple tu peux créer une liste qui te me permettras de créer les hosts
ou tu peux directement utiliser le fichier
https://pastebin.com/W7DrvcAq    c'est mon brouillon
mais il y a des hosts qui ne sont jamais utilisés ou il faut regarder dans les années passés
et il n'est pas donc nécessaire que les hosts apparaissent pour les créer avec ce fichiers
mais faut comme même vérifier

**Comment by Arias800** [comment]
Non mais en faite c'est bon, je n’avais pas vu myvi était déjà géré par Vstream (je n'avais pas téléchargé la bêta depuis plusieurs mois).
Sinon le site fonctionne bien j'ai fait quelque chose de similaire a la difference que je parse tout dans la page directement xD

**Comment by milkibreizh** [comment]
oui mais tu détermine et construit les host par expérience de ce que tu obtiens 
alors que   le fichiers anime.js; c'est celui qui sert a générer l'url de tous les host dans le navigateur
dans ma source le tableau corressespond a un resultat de requete (qui n'est pas dans ma source)
je crois que c'est celle ci h_ttps://pastebin.com/k9x3sjdt

l'host myvitv a été fait récécement mais il y a aussi myvi .ru sur les deux sites on obtiens bien un fichier mp4 mais j'ai des rerror 412 precondition failed j'ai essaye d'extraire le mp4 normalement ou en utilisant 'ht_tp://myvi.ru/player/api/Video/Get/' + id + '?sig'(ou on a  lien  myvi.tv) mais toujours pareil error 412

**Comment by Mokoman30** [comment]
hello les gens nouveau site fait par Wiflix qu’on connais pour l animé cette fois c est : https://french-anime.com/

**Comment by Arias800** [comment]
@milkibreizh J'ai mis a jour le code avec la détection automatique, on verra le résultat xD
Le progress est vraiment pratique pour les séries comportant beaucoup d'entré (One Piece, Naruto ...)

French_anime utilise exactement les même liens que Vostfree. Je ne suis pas sûr que ça vaille le coup de l'ajouter.

**Comment by milkibreizh** [comment]
> @milkibreizh J'ai mis a jour le code avec la détection automatique, on verra le résultat xD

.....rassure moi tu as verifié^^


> Je ne suis pas sûr que ça vaille le coup de l'ajouter.

surtout que vostfree est assez stable au niveau du code j'ai jamais observé de changement 
par contre je l'ai deja vu sous cloudfare qqle temps

**Comment by Arias800** [comment]
Oui évidemment que j'ai testé, mais c'est pas sûre que ça fonctionne pour 100% des liens du site ahah

**Comment by milkibreizh** [comment]
je crois que cela marche bien un peu prés de loin exemple
 dernier ajout project scard mais cela est faisable a 95% des liens

**Comment by milkibreizh** [comment]
3 sources on été rajoutées en supplément de vostfree.com
h____ttps://voiranime.to/   et merci @Bilal54 pour son partage
h___ttps://funeralforamanga.fr/
h__ttps://dbanimes.com/

**Comment by Mokoman30** [comment]
Chouette Merci + on a de source animé moins on galère

**Comment by Che-debarras** [comment]
Ya french-manga.net ,site de frenchstrm.lol
