### ISSUE TITLE
Alldebrid en tant que "Source"

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3197]
Bonjour,

Lorsque nous indiquons l'URL de notre dossier multimédias de Alldebrid via les paramètres, puis que nous nous rendons ensuite dans la Source Alldebrid, il est impossible de visionner nos liens. 

Message d'erreur: "Fichier introuvable"

Kodi Leia 18.9
nVidia Shield 
vStream 0.8.5 bêta du 19/01 17h00 (heure du canada:p)

**Comment by alKODIque** [comment]
mon log: 
[kodi.log.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5839099/kodi.log.txt)

**Comment by sfOoca** [comment]
> Bonjour,
> 
> Lorsque nous indiquons l'URL de notre dossier multimédias de Alldebrid via les paramètres, puis que nous nous rendons ensuite dans la Source Alldebrid, il est impossible de visionner nos liens.
> 
> Message d'erreur: "Fichier introuvable"
> 
> Kodi Leia 18.9
> nVidia Shield
> vStream 0.8.5 bêta du 19/01 17h00 (heure du canada:p)

Bonjour,

J'obtiens les même résultats avec différentes versions de kodi/vstream et même sur différents hardware (pc-windows/firestick/smartphone-android).

Je précise que kodi 'de base' arrive à lire le contenu du dossier multimédia Alldebrid via les sources vidéos.
