### ISSUE TITLE
Amélioration fonction recherche de vstream

### ISSUE THREAD

**Issue by Fatal1ty69** [Kodi-vStream/venom-xbmc-addons#3198]
Salut à tous,

Avant d'exprimer mon souhaite d'évolution je tenais encore une fois à vous remercier pour le travail effectué.
Félicitations ... tout simplement

Aujourd'hui, j'aimerai vous proposer une amélioration de la fonction recherche.

En effet, trop souvent la recherche me renvoit bon nombre de résultat qui ne m'intéresse pas.

Je souhaiterai la modifier avec la règle de gestion suivante : 
Si je tape mission impossible il va me chercher "mission" ou "impossible" ==> J'aurait forcément de nombreux résultats

Si je tape "mission impossible" il va me chercher "mission" ET "impossible" ==> J'aurai seulement les résultats pour "mission Impossible"

L'utilisation des guillemets permets une recherche exact de l'ensemble des mots utilisés.

PS : question subsidiaire .... est-ce que les accents sont importants dans la recherche ?

Merci à vous et je reste disponible si besoin

**Comment by TmpName** [comment]
Ha oui la je pense qu'il y a du dossier.

Alors deja on ne peux pas gerer les resultats, on place des mots dans le moteur de recherche, et c'est le site qui choisit son mode de fonctionnement.
Donc si le site recherches TOUT les mots de taper "mission impossible" avec ou sans guillemets donnera le meme resulat.

Par contre on peut faire du filtrage coté Vstream, il ya deja une fonction sur certains sites, mais peut etre ameliorable.
Pour moi si la personne tape "mission impossible" avec ou sans guillemets, elle attend des resultats avec les 2 mots, sinon elle aurait juste tapé "mission" ou "impossible".
Peut la mettre de maniere generalisée ?

Pour la question subsidiaire, y en a pas, on ne met jamais de caracteres accentués sauf en cours de francais, si tu veux en mettre c'est a tes risques et perils.

**Comment by Fatal1ty69** [comment]
Intéressant ce que tu dis, je ne ne savais pas que la recherche de Vstream était lié à la recherche des sites.

Je suis plutôt d'accord avec toi sur le fait qu'une personne qui tape mission impossible souhaite voir les résultats de ces 2 mots.

Par ailleurs, avec le développement de la source Pastebin, peut-être avons nous plus de lattitude pour améliorer la recherche ?
Après, peut-être qu'il n'est pas préférable d'avoir  plusieurs modes de recherches en fonction des sources.

Merci pour la question supplémentaire ... j'arrêterai de mettre des accents mdr

**Comment by TmpName** [comment]
>Après, peut-être qu'il n'est pas préférable d'avoir plusieurs modes de recherches en fonction des sources.

Oui, 100% d'accord, ni avec un mode special activable via les options, sinon un utilisateur n'aura pas le meme resultat qu'un autre, et vas y les problemes que ca va lancer.

Actuellement la fonction s'apelle CheckOccurence(), et elle ne fait que compter le nombre de mot en commum.
Dans le code elle ne se declenche que si les resultats depassent X titres.

Personnellement je sus pour la faire migrer en :
- Ne se declenche que si le nombre de resultat depasse X
- Si TOUT les mots sont dans les resultats. (plus facile que d'utiliser un pourcentage de mots en commun)

**Comment by sizanic** [comment]
> Actuellement la fonction s'apelle CheckOccurence(), et elle ne fait que compter le nombre de mot en commum.
> Personnellement je suis pour la faire migrer ...


Tout à fait d'accord avec toi.
Il faut modifier cette fonction, elle est utilisée par plusieurs sources et c'est donc une modification qui sera généralisée.

Par contre je n'ai pas trop compris ce que tu proposes.

Je resterai sur l'idée des guillemets.
La fonction détecte les mots entre guillemets et considère que le résultat est trouvé si tous les mots concerné sont trouvés.

Actuellement, la fonction renvoi '1' si un seul des mots trouvé pour une recherche sur : mission impossible.
On change pour qu'avec la recherche "mission impossible", la fonction renvoi '0' si 1 seul des mots trouvé, mais renvoi 2 si les deux mots sont trouvés.

ça permet de ne pas changer le code de ceux qui appellent la fonction et qui attendent déjà un certain nombre en retour.

**Comment by TmpName** [comment]
Ben en fait je regarde comment la placer, et je vois pas mieux ^^.
Actuellement on a
```
            # filtre search
            if sSearch and total > 5:
                if cUtil().CheckOccurence(sSearch.replace(URL_SEARCH[0], ''), sTitle) == 0:
                    continue
```

On doit savoir si c'est une recherche ou pas > besoin de sSearch 
On doit connaitre le total de resultat > besoin de total
On doit connaitre quoi chercher, ici c'est sSearch.replace(URL_SEARCH[0], '') et sTitle, mais ca peut changer

Donc pas moyen de faire plus "global", ou alors je vois pas, pas moyen par exmple de mettre ca en tete de fonction avec moins de tests.

Je peux modifier la fonction pour retourner par example 100 pour tout les mots ou 50 pour la moitié, au lieu du nombre de mot.

Mais le soucis, c'est rien n'est fait pour les guillemets, la par contre, c'est pas prevu du tout.

On peux couper la poire en deux:
- Si plus de 2 avec tout les mots > on affiche que les 100%
- Sinon on affiche les 50 % ou plus .
- Si moins de 4 resultats > tous affichés si au moins 1 mots
