### ISSUE TITLE
Kodi 19.0 / plus d'historique de visionnage / pas de résultats de recherche

### ISSUE THREAD

**Issue by Rygo92** [Kodi-vStream/venom-xbmc-addons#3199]
Bonsoir.

J’ai dl la RC de Kodi 19 pour tester.
Pas de souci pour installer vStream, mes fichiers settings et base de données.
J’ai lancé 2/3 vidéos et ça fonctionne nickel sur pastebin en tous cas, je teste que ça dans mon cas. 

Petit détail, je n’ai plus mon historique de visionnage qui s’affiche. Perso j’aime bien l’avoir pour savoir où j’en suis dans une série, ce que j’ai déjà vu etc. En regardant en détail la base de données, on voit qu’avec la RC ça rajoute un « b » avant le nom de la série. J’ai testé sur plusieurs séries et ça le rajoute à chaque fois. Le trait rouge sur le screen marque le passage de la 18.9 à la 19.0 et on voit bien la différence. Du coup tout ce qu’on a vu avant n’est pas reconnu. 

Autre souci, j'ai tenté une recherche dans série avec le mot "game" pour "game of trone", aucun résultat sur kodi 19.0, la même recherche avec la même config sur kodi 18.9 me donne 4 résultats. 

Voilà j’espère que je suis assez clair dans mon explication.

![image](https://user-images.githubusercontent.com/77703379/105250286-c89f8500-5b79-11eb-9238-1d0b7417d189.jpeg)

**Comment by Arias800** [comment]
Je pense que j'ai corrigé le "b" dans les titres de l'historique, et peut être que ça a corrigé l'autre bug aussi.

**Comment by sizanic** [comment]
@Rygo92 

suite à la mise à disposition de la version 0.8.6 de vStream qui est sortie hier, peux-tu nous indiquer si ton problème est traité.

Merci de clore ce ticket dans ce cas.

**Comment by Rygo92** [comment]
L'historique de visionnage est réglé, j'ai remis ma base de données et c'est bien marqué vu pour les anciens, les nouveaux visionnages sont bons aussi, il n'y a plus de B. 

Cependant les recherches sont toujours aléatoires, je sais pas si c'est lié a la version matrix ou pas. 

Par exemple pour chercher le film "retour vers le futur" :
- recherche "retour" (j'ai essayé "back" aussi en vo) = 0 résultat pour ces films. 
- recherche "futur" = résultats ok. 

Pour la série "game of trones", quelque soit la recherche, pas de résultat.

D'autres films/séries fonctionnent parfaitement et d'autres rien a faire quelque soit le mot chercher. 

Voilà pour mon retour, ce sont des détails, perso si je trouve pas comme ça, je trouve autrement, félicitations pour cette mise à jour 😉

**Comment by sizanic** [comment]
Mais tu n'as aucun résultat avec quelles sources activées ?

**Comment by sizanic** [comment]
> c'est juste dans le but d'améliorer la chose s'il y a vraiment un bug là dessous

c'est pour ça que je vais pas te lacher pour que tu m'aides à reproduire le problème.

En passant par vStream/Rechercher :
J'ai effectué une recherche de "retour vers le futur" 
=> j'ai plus de  100 résultats !
Des films avec le mot "retour", d'autres avec le mot "vers" et d'autres avec le mot "futur".

- Par où passes-tu par ta recherche ?
- Quels résultats obtiens-tu en passant par vStream/sources/pastebin/rechercher ?
- Et en passant par vStream/sources/pastebin/"Films"/rechercher ?

**Comment by Rygo92** [comment]
Oui en tapant tous les mots ça ressort mais ne tapant que certains mots, ça ressort... ou pas. Ce qui n'est pas logique à mon avis.

Je t'ai mis le screen d'où je recherche donc j'ai pour les mots :
- retour : 78 résultats mais pas le films "retour vers le futur"
- futur : 25 résultats avec les films de la trilogie 

En cherchant dans série (ligne en dessous du screen), j'ai beau mettre n'importe quel mot pour game of thrones, aucun résultat.


![image](https://user-images.githubusercontent.com/77703379/106778766-9a747780-6646-11eb-98b3-add108ad69fd.jpeg)

**Comment by Rygo92** [comment]
Nous avons trouvé le pourquoi du comment sur le discord de pastebin. 

Pour trouver certains mots il faut mettre une majuscule ou non. 

Par exemple pour retour vers le futur :
- "Retour" il trouve, "retour" il trouve pas.
- "futur" il trouve, "Future" il trouve pas.

Pour casa del papel :
- "casa" il trouve, "Casa" il trouve pas. 
- "papel" il trouve, "Papel" il trouve pas.

Il n'y a pas de logique, ça peut être le premier mot de la série/film ou non, ça peut avoir une majuscule ou non. 

En fait pour être sûr d'avoir tous les résultats à chaque fois, il faudrait faire 2 recherches avec/sans majuscule. 

Il faudrait trouver une solution, si c'est possible, ou la case n'est pas prise en compte dans la recherche.

**Comment by sizanic** [comment]
Corrigé en BETA
