### ISSUE TITLE
Pastebin et Real Debrid

### ISSUE THREAD

**Issue by ZABAD2020** [Kodi-vStream/venom-xbmc-addons#3200]
Lorsque je fais une recherche dans Pastebin et que j'ai plusieurs choix pour le mème film (ex: 4k, HD, HD light) lorsque je fais mon choix le film va partir sans problème et je vais pouvoir le regarder.  Par contre, quand je vais voir sur mes téléchargements dans Real Débrid, l'ensemble des choix que j'avais dans ont été téléchargé sur leur site.  Donc au lieu de juste télécharger le HD light que j'ai choisis, il va télécharger le 4k et le HD aussi sur mon real debrid.   

J'ai fais plusieurs tests et lorsque je suis rendu a la dernière étape pour le choix de la qualité du film  ... malheureusement real debrid va télécharger les autres films aussi.

**Votre system**
 Les test ont été effectué sur un ordinateur windows, 10 kodi 18.9 avec la version beta 0.8.5.4 et la 0.8.5.5
 Les test ont été effectué sur une beelink gt1 mini 2,  kodi 18.9 avec la version beta 0.8.5.4 

**Nous devons le reproduire**
Pour cela il nous faut:
- Installer le Pac et faire une recherche générale dans Pastebin ou trouver un film comme wonder women qui offre plusieurs qualité vidée
- Wonder Women, wonder wheel etc etc etc 
- uptobox

![image](https://user-images.githubusercontent.com/77878360/105574595-9cb21880-5da0-11eb-8345-b03a7c8859d1.png)
![image](https://user-images.githubusercontent.com/77878360/106217109-7ca2af00-620f-11eb-97df-b43d9acb4799.png)

![image](https://user-images.githubusercontent.com/77878360/105574603-a76cad80-5da0-11eb-93a7-58f22b9ef048.png)
et voici d'autres test que j'ai fais 
![image](https://user-images.githubusercontent.com/77878360/105574614-b6536000-5da0-11eb-823d-2696b1abaf52.png)
![image](https://user-images.githubusercontent.com/77878360/105574618-bb181400-5da0-11eb-98b7-ede8915cdf5d.png)

![image](https://user-images.githubusercontent.com/77878360/105574627-c10df500-5da0-11eb-8ae7-c8c7becfbce0.png)

**Comment by sizanic** [comment]
Bonjour @ZABAD2020 

> lorsque je fais mon choix le film va partir sans problème et je vais pouvoir le regarder. Par contre, quand je vais voir sur mes téléchargements dans Real Débrid, l'ensemble des choix que j'avais dans ont été téléchargé sur leur site. 


En fait, realDebrid, comme son nom l'indique, est un "débrideur".
Il n'est pas un hebergeur comme uptobox, il n'heberge pas le film.

Cela veut dire que ce que tu vois ne sont pas des "téléchargements" mais bien des "débridages".
En d'autres termes, lorsque tu vois "Lien direct", c'est parce que vStream a demandé à realDebrid de lui donner le "lien direct" de la vidéo. Pour cela, realDebrid "débride" le lien : il demande à l'hebergeur (uptobox dans cas) de lui donner le lien direct vers la vidéo.

Il n'y a donc pas de "téléchargement" en arrière plan.
Ce que tu vois ce sont les demandes de débridages.
Ces demandes vont augmenter même si tu ne lances la vidéo d'un des liens.

Normalement il n'y a rien de gênant.
Car c'est la fonctionnalité principale d'un debrideur de renvoyer un lien vidéo à partir d'une adresse uptobox.

**=> Cela a-t-il généré un problème sur ton compte ?**

**Comment by ZABAD2020** [comment]
J'ai eu aucun problème sur mon compte pour l'instant mais disons que je n'utilise plus Vstream depuis que j'ai remarqué ce problème au cas ou.  Il m'est arrivé le même problème avec CinemaHD voila environ deux ou trois semaines, j'ai remarqué que lorsque je cliquais sur un lien tout les autres lien etait disponible dans la section téléchargement de mon real debrid.  3 jours plus tard real debrid a commencé à avoir des problèmes et disais être attaqué par ses compétiteurs au final ils ont trouvé que le problème était CinemaHD et l'ont Ban (temporairement a mon avis le temps de régler le problème).  

Comme tu dis, on ne parle pas ici de téléchargement direct par Real Debrid mais de debridage seulement.  A savoir si CinemaHD faisait une demande de download a real debrid ou seulement une demande de débridage = maheureusement j'en ai aucune idée.    Mais pour être certain que Vstream ne vive pas la même situation et bien j'ai fais un ticket ;)

**Comment by sizanic** [comment]
Tu as bien fait de prévenir, ça valait le coup qu'on se pose la question.
Sur tes copies d'écrans, il n'y pas les entêtes de colonnes, donc je ne sais pas à quoi correspond les compteurs.

Je ne pense pas que nous soyons dans le même cas que CinemaHD.

**Comment by ZABAD2020** [comment]
Voila l'entete de real debrid
![image](https://user-images.githubusercontent.com/77878360/106217067-65fc5800-620f-11eb-9409-0411b0dc0ba7.png)

**Comment by sizanic** [comment]
Merci pour les entetes, je me demandais à quoi correspondait les chiffres 35, 47, 40, 42 ...
Donc ce qu'on voit c'est l'historique des liens débridés.

Je comprends que si tu veux regarder un film qui propose 7 liens, cela fera 7 debridages.
Mais tu ne devrais pas regarder plus de 3 films dans une même journée.

=> Je ne pense pas que ça affole realdebrid si tu debrides 20 liens par jour.

**Comment by ZABAD2020** [comment]
en espérant que non lolll 

Merci pour tout !!!
