### ISSUE TITLE
Propose une solution pour cloudflare 

### ISSUE THREAD

**Issue by Ovni-crea** [Kodi-vStream/venom-xbmc-addons#3201]
**Décrivez la solution que vous souhaitez**
Salut Tout le monde excuser moi pour mon absence mais j'ai vu que dernièrement la solution avec selenium n'est plus trop fonctionnel 
`https://github.com/FlareSolverr/FlareSolverr` Faudrait faire quelque chose avec ceci sur jackett il fonctionne tres bien pour contourner cloudflare sur y.g.g

**Comment by Che-debarras** [comment]
Bcp tente de bypasser CF mais a long terme faut voir
https://pypi.org/project/cloudscraper/

**Comment by Ovni-crea** [comment]
@Che-debarras Je suis au courant de ce module mais le problème c'est la fameuse v2 de cloudflare avec javascript il se résous pas ou sinon faut avoir la version payant du module

**Comment by Che-debarras** [comment]
> @Che-debarras Je suis au courant de ce module mais le problème c'est la fameuse v2 de cloudflare avec javascript il se résous pas ou sinon faut avoir la version payant du module

Désolé je savais pas qu'il existait des modules payants, j'ai toujours cru que sur github c'était open source.
Dans ce cas je comprends

**Comment by TmpName** [comment]
La version payante n'est pas dispo sur github.
Mais perso j'ai arrette d'aller voir les infos sur ce fameux code, et je ne sais meme pas si ca marche vraiment.

**Comment by Ovni-crea** [comment]
@TmpName J'ai parlé de ça parce que selenium avec la v2 de cloudflare ça ne fonctionne plus donc je propose des idées

**Comment by TmpName** [comment]
Ha bon selenium ne marche plus ?

**Comment by Che-debarras** [comment]
Sur android ça n'a jamais marché

**Comment by Arias800** [comment]
C'est normal, Selenium ne marche pas sous  Android a cause du sandoxing entre les apps.

**Comment by Ovni-crea** [comment]
@TmpName Oui Mais plus maintenant je crois qu'ils utilisent un système comme recaptcha
