### ISSUE TITLE
Reprendre la lecture d’un média

### ISSUE THREAD

**Issue by Rygo92** [Kodi-vStream/venom-xbmc-addons#3204]
Bonjour.

Depuis la dernière version de vStream, il est impossible de reprendre la lecture d'un film ou d'une série en cours si l'on a quitté. Avant on avait un menu "reprendre à XX minutes" ou "recommencer à zero". 

Personnellement je suis sur vStream 0.8.5 sur Kodi 18.9 mais le bug est reporté par plusieurs membres sur le discord de pastebin.

Bon courage 😉

**Comment by TmpName** [comment]
C'est pas géré en direct par kodi ca ?

**Comment by sizanic** [comment]
Bonjour @Rygo92,

Comme tu l'as dit, cela a été remonté sur le Discord de "Pastebin".
Car je pense que ça ne concerne que les films/séries visualisés avec Pastebin.

On va voir ce qu'on peut faire ...


@TmpName 
Non, c'est bien vStream. (vStreamDB/resume)
Mais dans le cas de pastebin, ce sont les liens directs qui sont utilisés et vStream ne garde pas l'historiques de visualisation des liens directs.

**Comment by sizanic** [comment]
C'est traité.
Ce sera disponible dans la prochaine version.

**Comment by sizanic** [comment]
@Rygo92 
La version 1.2.0 de vStream est sortie et intègre cette amélioration.
