### ISSUE TITLE
problème de lecture via compte Trakt

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3205]
Bonjour :)

Je ne parviens pas à effectuer une recherche de films via mon compte Trakt à partir de vStream. 

Lorsque j'appuie sur un film, j'obtiens un message d'erreur et aucune recherche ne s'exécute.

Je n'ai que 2 sources d'activées pour la recherche globale (Pastebin et Zt)

Je joins mon log 

Merci ! :)
[kodi.log.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5865553/kodi.log.txt)

EDIT: oublié de mentionner que mes recherches sont effectuées à partir de mes listes personnelles Trakt

**Comment by sizanic** [comment]
bonjour,

suite aux dernières modifications, cette demande est-elle toujours d'actualité.

Merci de la clore le cas échéant.

**Comment by alKODIque** [comment]
Résolu
