### ISSUE TITLE
Recherche visuelle 

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3207]
Bonjour :)

Les menus à l'intérieur de la recherche visuelle ne s'ouvrent plus.
Je viens aussi de faire l'essai avec la nouvelle bêta et c'est aussi le même problème 

Je joins mon log
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/5870243/kodi.log)

**Comment by Manu21000** [comment]
même problème,  tous les menus ne sont pas impactés, la recherche "standard" fonctionne cependant.
la log Kodi mentionne ceci:
vStream: could not load site: themoviedb_org error: 'genres'
un problème de changement sur le "genre" ?

**Comment by chrysal** [comment]
Bonjour, 

Il est possible que l'API key ne soit plus valide sur le site themoviedb_org. 
Voici ce que j'obtiens dans le result (ligne 515) 

> result = {u'status_code': 7, u'status_message': u'**Invalid API key: You must be granted a valid key**.', u'success': False}

Cordialement

**Comment by yodidon** [comment]
> Bonjour,
> 
> Il est possible que l'API key ne soit plus valide sur le site themoviedb_org.
> Voici ce que j'obtiens dans le result (ligne 515)
> 
> > result = {u'status_code': 7, u'status_message': u'**Invalid API key: You must be granted a valid key**.', u'success': False}
> 
> Pour information j'ai fait un test avec une API Key valide (query ok avec l'url directement), j'ai modifié le settings.xml mais cela ne fonctionne pas chez moi, .
> Il doit y avoir quelque chose à faire dans le tmdb.py, je me suis arrété à la fonction getUrl
> 
> Cordialement

Bonjour, le problème d’api key est en cours de résolution.
Merci pour votre patience

**Comment by djdave51** [comment]
> 
> 
> > Bonjour,
> > Il est possible que l'API key ne soit plus valide sur le site themoviedb_org.
> > Voici ce que j'obtiens dans le result (ligne 515)
> > > result = {u'status_code': 7, u'status_message': u'**Invalid API key: You must be granted a valid key**.', u'success': False}
> > 
> > 
> > Pour information j'ai fait un test avec une API Key valide (query ok avec l'url directement), j'ai modifié le settings.xml mais cela ne fonctionne pas chez moi, .
> > Il doit y avoir quelque chose à faire dans le tmdb.py, je me suis arrété à la fonction getUrl
> > Cordialement
> 
> Bonjour, le problème d’api key est en cours de résolution.
> Merci pour votre patience

Du nouveau sur ce sujet, car la recherche visuelle, c'est tout de même bien pratique...?

Merci

**Comment by sizanic** [comment]
> Il est possible que l'API key ne soit plus valide sur le site themoviedb_org.
Voici ce que j'obtiens dans le result (ligne 515)
`result = {u'status_code': 7, u'status_message': u'Invalid API key: You must be granted a valid key.', u'success': False}`


La clef a été renouvelée dans la version 0.8.6 qui est sortie hier.
Cette clef par défaut se met en place à l'installation de vStream.

Il est donc nécessaire de désinstaller/réinstaller vStream pour mettre en place cette nouvelle clef.

**Comment by sizanic** [comment]
> Les menus à l'intérieur de la recherche visuelle ne s'ouvrent plus.

Non reproductible avec la dernière version 0.8.6.

@alKODIque 
Ticket toujours d'actualité ?
Sinon, à clore.

**Comment by djdave51** [comment]
Il faut réinstaller VSTREAM 0.8.6 à partir d'un zip?
Si oui ou puis je le télécharger?

**Comment by alKODIque** [comment]
Resolu! 
Avec version 0.8.6

**Comment by sizanic** [comment]
@djdave51 

si tu as installé proprement vStream à partir de son dépot, tu n'as rien à faire et le mise à jour s'installera toute seule d'elle-même.

**Comment by Manu21000** [comment]
Effectivement, problème corrigé,

merci à l'équipe pour la rapidité de la correction et aux contributeurs 
pour avoir fait avancer le sujet.

Longue vie à VStream \o/


Le 03/02/2021 à 16:07, sizanic a écrit :
