### ISSUE TITLE
Information source ZT

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#3209]
Bonjour il y a actuellement un problème sur la source ZT.
Explication : Quand on navigue dans la source et qu'on choisit une catégorie, exemple on navigue sur Films Blu-ray (720p & 1080p), puis on sélectionne une jaquette on peut seulement voir les liens Blu-ray 1080p, c'est à dire le premier lien qui s'affiche et impossible de naviguer sur les autres résolution car ça affiche une erreur.
Donc pour voir un lien s'afficher il faut cliquer sur la bonne catégorie à la base.

C'est juste une information.
Testé sur Bêta de ce matin et  sur box Android.

**Comment by Che-debarras** [comment]
C'est revenu a la normal testé a l'instant a 19:07 les liens sont visible quelque soit la langue ou résolution
