### ISSUE TITLE
Uptobox/strm

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3210]
**Décrivez le bug**
Uptobox et uptostream ne fonctionne plus sur pas mal de sources
Notamment zt ou frenchstrm.lol 

**Votre system**
 - OS: [, Android]
-  Appareil [s8]
 - Version Kodi  [18.9]
- Version Vstream o.85

**Comment by milkibreizh** [comment]
@Che-debarras 
tu peux tester la beta s.t.p il y a eu une correction mais je ne sais pas si cela résoudras ton problème

**Comment by Che-debarras** [comment]
J'ai testé et ça marche 

A noter que on a le retour des résolutions fullhd 1080p sur uptobox sans compte premium ni rien

**Comment by milkibreizh** [comment]
ok merci

**Comment by glardz95** [comment]
Je confirme, Uptobox ne fonctionne plus ainsi que le lien zt-za
