### ISSUE TITLE
VSTREAM NE S EXECUTE PAS DANS KODI

### ISSUE THREAD

**Issue by Morganeaj** [Kodi-vStream/venom-xbmc-addons#3211]
Bonjour a tous,  j'ai du reinstaller Vstream par erreur, du coup j'ai recuperer le zip et je l'ai passe en wifi sur kodi et l'appli est bien visible mais impossible de l'executer.... le bouton est grisé.... je pete un cable.... aidez moi.

merci bcp 

**Votre system**
Android tv
google tv
 - Version Kodi  [16.17.18]
- Version Vstream0.03

**Comment by yodidon** [comment]
je crois qu'il y ait des erreurs dans ta procédure même si j'avoue pas tout avoir compris...
tu dois télécharger le repository que tu trouve ici (le zip)https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.0.3 ensuit "installer depuis un zip" sur kodi et aller jusqu'à ce fichier zip précédemment téléchargé.
puis une fois installé, tu auras dans "installer depuis un depot" vstream repository.
une fois cliqué, tu auras extension vidéo et vstream , plus qu'a laisser installer et hop c'est bon.

**Comment by Morganeaj** [comment]
Salut, j'ai bien fait toute la manip, ce n'est pas la 1ere fois.
Je me rends compte que c'est tout mes addon que je ne peux pas installer, je viens de faire le test avec catch up tv, et c'est la meme l'addon est bien la mais pas possible de l'installer, je dois avoir un soucis de parametrage dans kodi vous ne croyez pas ?

**Comment by Morganeaj** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2893 j'ai vu que lui avait le meme soucis il y a qq mois

**Comment by yodidon** [comment]
je donnerais la même réponse:
version vstream 0.0.3 c'est la version du repository et pas de vstream donc je ne peux que te dire de bien refaire toute l'instal comme je te le dis juste avant et avoir version vStream:0.8.5

**Comment by sizanic** [comment]
@yodidon a raison de te rappeler la procédure d'installation, j'en aurais fait autant en voyant la description de ton problème, car tu précises : 

Version Vstream0.03

Sauf que vStream n'est pas en version 0.03, ça c'est la version du repository (depot).
Tu dois ensuite allez dans ce depot pour installer vStream qui est en version 0.8.5.

**Comment by sizanic** [comment]
Et en plus tu précises : 
Votre system
* Android tv
* google tv
* Version Kodi [16.17.18]

ça ne nous aide pas du tout !!

Quel version de KODI ???

**Comment by sizanic** [comment]
> #2893 j'ai vu que lui avait le meme soucis il y a qq mois

Et on lui avait donné la même réponse 🤔

**Comment by Morganeaj** [comment]
Bonjour a tous,
Alors j'ai installer la derniere version de kodi leia 18.9 je crois, ensuite depuis wifi files sender j'ai envoyé le repository.vstream-0.0.3.zip
J'ai ensuite activer les sources inconnu et lancer l'installation depuis un fichier zip
J'ai un message vstream installé. 
Je ne le trouve pas sur l'ecran principal lorsque je le cherche dans mes extensions il est bien la
Seul les cases desactiver, mettre a jour ou desinstaller sont accessibles
J'espere avoir été plus clair

Le tout sur une google tv

**Comment by Morganeaj** [comment]
Je viens de refaire toute l'instal et toujours le meme soucis... a ne rien y comprendre surtout que ca marchait avant....

**Comment by yodidon** [comment]
Et dans installer depuis un dépôt tu as vstream ?

**Comment by Morganeaj** [comment]
oui il est present

**Comment by yodidon** [comment]
Et quand tu clique dessus tu as bien extension vidéo ?

**Comment by Morganeaj** [comment]
C'est bon c reglé, en fait il n'etait pas installé, bug dans ma tete... merci bcp Yodidon :-)

**Comment by yodidon** [comment]
Oui parfois on se persuade d’avoir fait le bon truc mais on zappe un passage , ça m’arrive aussi 👍
