### ISSUE TITLE
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 13

### ISSUE THREAD

**Issue by zicmama** [Kodi-vStream/venom-xbmc-addons#3212]
**Décrivez le bug**
Erreur pour télécharger

**Votre system**
 - OS: [Linux]
-  Appareil [PC]
 - Version Kodi  [18.9]
- Version Vstream 0.8.5

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site: Cinemay
- Le titre du fim/serie "Les chose qu'on dit, les choses qu'on fait"
- Le nom du host (openload/vidzi): Uqload

**Log**
```
2021-01-28 11:19:47.691 T:140141334497024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 13: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/fred/.kodi/addons/plugin.video.vstream/default.py", line 370, in <module>
                                                main()
                                              File "/home/fred/.kodi/addons/plugin.video.vstream/default.py", line 49, in __init__
                                                self.parseUrl()
                                              File "/home/fred/.kodi/addons/plugin.video.vstream/default.py", line 140, in parseUrl
                                                if isDl(sSiteName, sFunction):
                                              File "/home/fred/.kodi/addons/plugin.video.vstream/default.py", line 272, in isDl
                                                exec("oDownload." + sFunction + "()")
                                              File "<string>", line 1, in <module>
                                              File "/home/fred/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 676, in AddtoDownloadList
                                                if (self.AddDownload(meta)):
                                              File "/home/fred/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 619, in AddDownload
                                                sTitle = self.__createTitle(sUrl, sTitle)
                                              File "/home/fred/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 341, in __createTitle
                                                sTitle = cUtil().FormatSerie(sTitle)
                                              File "/home/fred/.kodi/addons/plugin.video.vstream/resources/lib/util.py", line 206, in FormatSerie
                                                return string.encode('utf-8')
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 13: ordinal not in range(128)
                                            -->End of Python script error report<--

```

**Plus**

**Comment by TmpName** [comment]
Ha oui avec le telechargement, essayes avec cette modif https://github.com/Kodi-vStream/venom-xbmc-addons/commit/30397e1ec4634d257e0d82ae26944fb8cf9cc750#diff-3149e27b69f9b0a012b316270732cb253051fc33bc28e5bb4043192db94ed82e

**Comment by zicmama** [comment]
Merci. Avec l'inversion de lignes, l'erreur à disparu, mais j'obtiens "Téléchargement impossible"

cette ligne dans le log
```
2021-01-28 22:31:35.097 T:140142450546816 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
```

**Comment by zicmama** [comment]
Un fichier (sans les apostrophes) existe de taille 0 octet.
Pour essayer à nouveau, une alerte empêche de garder le même nom de fichier.
Obligé de mettre un nouveau nom à chaque tentative. Vu qu'il est vide, serait-il possible d'écraser le premier fichier?

**Comment by zicmama** [comment]
Pour la démo, Voici, accessibles depuis une passerelle, les liens ipfs/ipns que les amis gchange se partagent...
- Premier fichier "ASTROPORT"
http://oasis.astroport.com:10010/ipns/12D3KooWPTNwnpodLqBH5WcBfwFSJSdWbvqX7GeujjbmDmLY2D6N/.12D3KooWPTNwnpodLqBH5WcBfwFSJSdWbvqX7GeujjbmDmLY2D6N/FASTRXBIAN

Celui d'un autre noeud Kodi/Astroport http://oasis.astroport.com:10010/ipns/12D3KooWCMLWeSWE9ioAF2ZgNNfGTPjJLJ5EEL5kYZsi65LMrJry/.12D3KooWCMLWeSWE9ioAF2ZgNNfGTPjJLJ5EEL5kYZsi65LMrJry/FASTRXBIAN

Voici un stream : http://oasis.astroport.com:10010/ipfs/QmdP696MqLKJEXGm8vjyeAWZ2cghoqguzgaG9EpyUPbaHQ/Jon%20Hopkins%20-%20%27Open%20Eye%20Signal%27%20(Official%20Music%20Video).mp4

La magie IPFS en action!! Cela crée un hébergement p2p, décentralisé et évite que la source disparaisse.
Normalement le partage est entre amis, les liens sont en http://127.0.0.1 (Je ferme la passerelle d'ici qq jours)

**Comment by TmpName** [comment]
Aucun soucis de mon coté, autre chose dans les logs ?
J'ai testé le meme films, meme hebergeur et le dl a demarré.

**Comment by sizanic** [comment]
> Pour la démo, Voici, accessibles depuis une passerelle, les liens ipfs/ipns que les amis gchange se partagent...
> 
> * Premier fichier "ASTROPORT"


Quel rapport avec le sujet de cette issue ????

Ce hors sujet à propos de l'IPFs devient lassant.
Pourquoi ce SPAM !!

Voici un lien qui devrait t'intéresser : https://kodibeginner.com/creating-your-first-kodi-add-on/

**Comment by milkibreizh** [comment]
@zicmama 
tu peux arrêter tes simulations maintenant car on a bien deviné  que tu ne pouvait être qu'un bot^^

**Comment by zicmama** [comment]
@sizanic ce message n'était pas ici à l'origine. Quelqu'un l'a déplacé.

Je constate depuis l'arrivée de la nouvelle vague de contributeurs à Vstream des formes de pratiques assez éloignées de l'esprit du Libre. Votre façon d’accueillir ne me plaît pas! On dirait la police ;) Ou des admin de hoster ? Dans ce cas je comprends votre dénigrement... @milkibreizh et si j'étais plus qu'un bot ? 

Je respecte votre travail et surtout celui de @LordVenom @Arias800 @TmpName 
Mon intervention vise à prolonger leur volonté dans un espace numérique où nulle dictature ne pourra plus agir.

**Comment by sizanic** [comment]
Je trouve que mettre en place un réseau privé avec du contenu qui est retiré d'Internet pour le réserver à ce réseau, et réserver l'accès à certaines personnes capable d'installer la solution d'accès -> c'est plutôt ça qui semble être éloigné de l'esprit du libre.

Et sans parler de l'esprit du libre qui peut-être m'échappe, cette solution rendrait vStream fournisseur de contenus détenus par des particuliers.
Et ça ce n'est pas dans l'esprit de vStream.

**Comment by zicmama** [comment]
@sizanic je vois que tu n'es pas bien documenté sur ipfs. Le réseau créé n'est pas privé. Il comporte des passerelles qui permettre un mélange entre Intranet, Extranet et Internet. Tout ces concepts fusionnent. Le concept de LAN et WAN également. Ce sont bien quelques "particuliers" qui aujourd’hui font tourner les sources de streaming... Est-ce cela l'esprit de Vstream?

**Comment by Arias800** [comment]
Pour rappel l'origine de Vstream c'est ça : 
![image](https://user-images.githubusercontent.com/24809312/106381888-24f57680-63bc-11eb-9ead-8d13a2e154b3.png)
Ni plus ni moins.
source : https://www.looma.fr/interview-de-lord-venom-fondateur-de-l-extension-de-streaming-vstream-kodi/

Maintenant le principal problème de cette idée c'est qu'il faut que ce sois compréhensible pour une majorité, car je n'aime pas l'idée d'ajouter quelque choses qui n'est utilisable que par une minorité.
Ensuite a l'heure actuelle on est protégé du point de vue légal car ont ne fait que scraper, avec ton idée ça devient tout de suite autre choses puisque ça peut être considéré comme du recel (c'est en partie là-dessus que la Hadopi s'appuie pour sanctionner).

**Comment by sizanic** [comment]
> Je constate depuis l'arrivée de la nouvelle vague de contributeurs à Vstream des formes de pratiques assez éloignées de l'esprit du Libre...

> Je respecte votre travail et surtout celui de @LordVenom @Arias800 @TmpName


Tu as maintenant l'avis de @Arias800 , qui cite LordVenom dans son argument.

**Comment by Arias800** [comment]
Attends, je n'ai pas dit que je parlais a la place de LordVenom !
Je remets juste du contexte.

**Comment by milkibreizh** [comment]
> @milkibreizh et si j'étais plus qu'un bot

c'est certain mon humour trop lourdous n'est pas passé et heureusement pour moi il n'existe pas de ditcature de l'humour^^ 

par contre  le coup du dénigrement c'est un peu gratuit de dire cela,
c'est sans doute que tu n'as lu le post ou je disais comprendre ton enthousiaste 
et je t'encourageais à essayé de faire un addon étant sur que tu en avait la capacité..
et je ne vois pas,mais ce n'est pas une raison non plus,
comment je pourrais dénigrer quelqu’un qui fait des trucs que je 
ne sait pas faire ou que je ne connais pas trop cela n'aurais aucun sens

**Comment by TmpName** [comment]
Le sujet de IPF a deja été discuté dans les pull request, et je pense que tout le monde a le meme avis, ca ne se fera pas sur Vstream.

Sinon pour en revenir au bug de l'issue, ce ne serait pas toi qui changerait le nom du fichier ? quand la boite de dialogue apparait, essayes avec un titre d'un seul mot.

**Comment by sizanic** [comment]
@Arias800 
> Attends, je n'ai pas dit que je parlais a la place de LordVenom !
> Je remets juste du contexte.

Je ne dis pas que tu parlais en son nom, mais bien que tu le cites. Et ta citation reflète ce que pense lordVenom car ce sont ces propres mots.


@milkibreizh 
on n 'avait tous compris ton humour.

**Comment by sizanic** [comment]
vStream n'a pas pour objectif de permettre des téléchargements en masse afin de constituer une bibliothèque sur un réseau local.

> La techno ipfs fabrique un stockage maillé, auto-réparti, qui empêche toute censure...
On aura les 100To d'ici cet été... on vous tiendra informés.

Non, on veut pas être tenu au courant, car on ne veut pas vStream participe de près ou de loin à la mise en place de cette architecture.

Je cloture ce ticket car nous n'apporterons pas d'aide dans l'amélioration de cette fonctionnalité si elle doit être utilisée de cette sorte.
