### ISSUE TITLE
Mise à jour Stormwall

### ISSUE THREAD

**Issue by 0x0040** [Kodi-vStream/venom-xbmc-addons#3213]
La protection Stormwall de zt-protect vient, à nouveau, de changer !

**Comment by Arias800** [comment]
Ils ont remis l'ancienne version, donc je l'ai remis dans la beta xD

**Comment by Nash233** [comment]
looL bien vue ..

**Comment by 0x0040** [comment]
Ils viennent de rechanger !
Je pense donc qu'il faut faire quelques choses de plus agile.

**Comment by Arias800** [comment]
Ils alternent entre les deux. Je vais donc combiner les deux xD
