### ISSUE TITLE
Les site de DLL c'est fini pour moi.

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#3214]
D'abord une petite mise en contexte : Je n'utilise jamais les sites de DLL, je me suis retrouvé en charge de ces sites un peu par hasard. Ces sites sont les plus problématique et les plus complexes a corrigé du fait que les sites sont codé n'importe comment. Mais ce n'est même pas ça le problème.
J'avais deja gueuler plusieurs fois sur le Discord par rapport a ça, mais visiblement ça n'a pas suffi donc je le redis : J'en suis marre d'avoir une dizaine de messages chaque matin me rapportant que zt ne marche pas alors que j'ai prévenu que je bosse sur une correction. Parce que oui j'ai une vie à coter, je dors, je mange, j'ai mes études. Bref j'ai autre choses à foutre et je ne suis pas à votre service h24.

@LordVenom avait parlé d'un manque de reconnaissance, et je comprends maintenant totalement à quoi il faisait référence.

Donc j'ai pris une décision, qui a été longuement réfléchis : Je ne m'occuperai plus des sites de DLL.
Ça va sembler égoïste de ma part, je le sais, mais peu importe.
Je continuerai à participer a Vstream, je ne m'occuperai juste plus de ces sites.

**Comment by yodidon** [comment]
@Arias800 , tu as bien raison s’exprimer ton mécontentement, ces cité sont très difficiles à maintenir et ils mettent à chaque fois les utilisateurs en ébullitions, il faut je crois avertir sur leur utilisations qu’ellle peut être aléatoire et pas du tout stable, et peut être revoir la méthode de demande de corrections.
Tu fais déjà énormément pour Vstream et nous le savons bien, tu restes n des piliers du maintien en bonne forme de cet addon avec les autres dev. Alors je te soutiens pleinement dans ton argumentaire.

**Comment by Che-debarras** [comment]
Je plussoie comme on dit car vstream offre plusieurs sources et je n'ai jamais utilisé ce Zt ou tirexo et au pire ya toujours host direct en copiant collant le lien si on trouve pas
Mais maintenant les gens ne cherche plus ni leur films/series sur d'autres source ni meme les infos ou solutions sur github, ça veut leur source préférée.

Perso j'ai changé x fois de sources préférée grâce au devs qui corrige et apporte de nouvelles sources tel que frenchstrmng.lol meme si maintenant je suis plus sur wiflix et tous ca Grâce au nouveaux host HD evoload ou dood.

Les devs prennent leur temps pour cette addon, sa creation son amelioration son optimisation sa correction avec de nouvelles fonctions , alors nous devons prendre le temps pour aller cherchez notre films ou series dans d'autres sources surtout avec la fonction recherche globale qui prend 2 minutes.

Les bugs d'un source doivent etre cité ici et 1 seule fois et pas déranger les devs , ils consultent le github a leur temps libre et corrigeront a leur temps libre.
Donc je pense effectivement qu'il faut interdire les demande de correction en messagerie et garder tous cela sur github et utiliser discord que pour de l'aide sur le fonctionnement et renvoyer les gens sur github pour tout bug.

Sur ce je réitère mes remerciements aux devs et participants qui maintiennent cette addon et on ne saura jamais suffisamment reconnaissant pour ce boulot et la moindre des choses serait de ne pas imposer ou insister quoique ce soit et juste patienter

**Comment by Arias800** [comment]
Merci pour ton message.
Après les discussions liée au bug sur le Discord donne lieux a des discussions intéressante, mon message ne vise pas tout le monde. Juste une partie des personnes qui, je l'espère, se reconnaitront.

Là j'ai attaqué le refacto de Trakt (une grosse mise a jour du code de Trakt). C'est quelque choses que je voulais faire depuis longtemps, mais que je n'ai pas pu faire faute de temps.
Maintenant ce sera fait, et j'ai d'autres modification de prévus (comme l'ajout d'une option pour le contenu +18 par exemple).

Surtout qu'avec Pastebin les sites de DDL sont presque devenu obsolète car, que l'ont n'aime ou pas le système, c'est beaucoup plus stable et rapide que passé par ces sites.

**Comment by zicmama** [comment]
@Arias800 je te comprends, tous les gars (et les filles?) derrière Vstream sont des AS du streaming !! Même si je suis plutot du genre discret (et peu bavard en ligne) Je suis à chaque fois impressionné par le boulot qui est fait.
Pour solutionner tout ça des potes et moi on est en train de finir une amélioration qui devrait mettre tout le monde d'accord...
https://discord.com/channels/519198717463625764/520599849222275073/805077929289318411

With much LOVE
MERCI

**Comment by razorex** [comment]
Je pense que l'on fait vStream avant tout pour nous, et pour certains faire de la programmation, après de mon côté je prend, ou je tente de prendre, du recul par rapport au remarque qui nous sont retourné et qui ne sont pas toujours sympathiques. 
Donc pense au 99,9 % des gens qui ne ce plaignent pas, et garde courage. Tu n'est pas à la disposition de vStream et de ces utilisateurs, comme nous tous, donc fait les choses en fonction de ton temps disponible (gardes-en pour toi) pour vStream.
vStream fonctionne donc toute amélioration qui tu lui apporte est un plus et non indispensable.

**Comment by sizanic** [comment]
Pour moi vStream, ce n'est pas vDDL.

Dans ce sens, j'ai déjà soumis la volonté de supprimer la fonction "télécharger".
(Mais je comprend qu'elle peut servir à palier des soucis de lenteur de streaming).

J'aimerai que vStream reste une solution simple à utiliser pour exclusivement accéder à du Streaming.

Donc pour moi c'est plutôt une bonne nouvelle si on arrête le support des sites de download 😄 

Et comme je le dis, cela doit rester simple, donc vStream n'est pas non plus vIPFS 😉

**Comment by f3n3k** [comment]
Si c'est 2 sites de streaming ne sont plus accessible par votre app, je ne comprends pas l'intérêt alors, c'était les 2 seul site de streaming avec un contenu mis à jour tout le temps, là il ne reste que des vieux site de streaming avec des films datant de plusieurs mois... Ou dites moi vos sources alors... Pour ma part je suis déçu de ce choix...

**Comment by yodidon** [comment]
Il y a pas mal de sources qui sont bien actualisées, je suis étonné de lire que vstream ce résumerai a dll ou zt, c’est même limite en vers les dev qui essaient sans cesse d’apporter de nouvelles sources à jours

**Comment by f3n3k** [comment]
Fait partager alors ces "pas mal de sources", sur lesquels vas tu, qui soit si bien ? Je suis interrogatif.
Pour ce qui est des mises à jours, je suis désolé mais l'interface c'est pas top, très illisible, difficile de trouver ce qui est nouveau de l'ancien...

**Comment by yodidon** [comment]
Je pense que tu devrais trouver ton bonheur sur d’autre solution et éviter des messages inutilent, si tu as des propositions pour des améliorations nous comptons sur toi ...

**Comment by TmpName** [comment]
Alors je me sert de Vstream depuis le debut, et je ne me suis jamais servi des sites de ddl.

>vieux site de streaming avec des films datant de plusieurs mois

Vieux = plusieurs mois ? La y a un soucis, le cinema a été inventé en 1895, vieux chez moi c'est au moins 20 ans, a ton niveau le mieux c'est pas le streaming gratuit.

**Comment by f3n3k** [comment]
Les gars qui demande d'éviter les messages inutiles mais qui troll et ne répond à rien.
Je leur demande de partager leur connaissances mais ils répondent par la même question (méga lol)

Vous etes au courant sinon que le stream est présent sur les sites cités ou vous le faites vraiment exprès.

Bref j'ai compris c'est pas ici qu'on trouvera de l'aide et surtout des réponses valables.

GG les 2 gamins.

**Comment by Che-debarras** [comment]
Idem pour moi j'utilise vstream depuis assez longtemps et je n'ai jamals utilisé les sites de ddl.
J'avais posté un post ou mes souces préférées étaient des sites de streaming et non de ddl
Dire que ces sites de streaming n'a que des vieux films c'est que la personne n'a jamais consulté les autres sources.
J'utilise que frenchstrm.lol ou wiflx qui sont rapidement mis à jour avec les nouveaux films et series quasi le lendemain.
Je m'étonne de voir un message parlant du manque de maj de films et séries alors que vstream s'évertue de nol seulement corriger ces sources mais en plus de maj avec de nouvelles sources plus récentes. 

Je ne parle même pas des efforts faites par l'équipe pour trouver des solutions pour les sites ddl contre cloudfare, ou la prise en charge de nouveau host offrant la HD, ou de nouvelles fonctions comme Pastebin parmi tant d'autres.

Tous ce la ne nous coûte pas un centime alors que pour les devs cela leur coûte du temps donc je vois pas comment après tous cela on se permet de se plaindre et critiquer vstream dans sa forme ou son fond.

J'adhère à 1000% au comm de @TmpName pour qui la solution la plus appropriée est me service payant pour cette personne.

J'espère que l'équipe vstream save que la majorité des utilisateurs sont ne se plaint pas du moindre défaut ou que sais je car vstream est excellent et nous rend bien servi bien au dela de nos esperances et depuis toutes ces années nous vous somme reconnaissant d'être toujours active et dévoué et volontaire e car rappellons rien ne vous oblige à faire et partager cette addon.

Mille merci à vous

**Comment by Che-debarras** [comment]
> Les gars qui demandeNT d'éviter les messages inutiles mais qui trollENT et ne répondENT à rien.
> Je leur demande de partager leurS connaissances mais ils répondent par la même question (méga lol)
> 
> Vous êtes au courant sinon que le stream est présent sur les sites cités oU vous le faites vraiment exprès.
> 
> Bref j'ai compris QUE c'est pas ici qu'on trouvera de l'aide et surtout des réponses valables.
> 
> GG les 2 gamins.
> 
> edit: Vive les fautes, quand on veut faire le donneur de leçons, autant bien le faire hein ;)

**Comment by sizanic** [comment]
> Vous êtes au courant sinon que le stream est présent sur les sites cités où vous le faites vraiment exprès.

oui, merci on est au courant.
Mais si on essayait de maintenir ces deux sites c'était exclusivement pour ce qu'ils apportent en plus, le DDL.
Car pour le streaming il y a  bien d'autres sources qui sont plus facile à entretenir.
Comme vStream abandonne le DDL pour ce concentrer sur le streaming, on ne gardera que les sources dont on peut récupérer facilement les flux streaming.


> Bref j'ai compris c'est pas ici qu'on trouvera de l'aide et surtout des réponses valables.

Il faut poser ses questions avec respect pour avoir plus de chances d'avoir des réponses.
On a les réponses à tes questions mais on ne veut simplement pas te répondre.

**Comment by f3n3k** [comment]
A part Sizanic qui prend le temps de répondre sans troller, le reste c'est OSEF surtout avec les fautes et le suçage de bourliches gratos...

En tout cas c'est bizarre, frenchstrm.lol ne fonctionne pas, la fonction directhost c'est pas mieux avec des liens uptobox et compte premium, de plus de passer 3h à taper un lien qui ne fonctionnera pas au final (mdr)... Mais oui cela doit être moi qui devrais prendre un service payant... Petits blagueurs.

Apres les gars, que les devs arrêtent ou pas leur app, qu'ils le prennent bien ou mal, cela ne me changera strictement rien à ma vie, de plus que je l'utilise rarement au final car ca ne marche jamais correctement, donc je viens de temps à autre remonter les mêmes soucis en permanence, on me sort cela va fonctionner dans la prochaine beta et basta je passe à autre chose... Pourtant il y a quelques années, ça fonctionnait très bien et je l'installais à gauche et à droite pour faciliter l'accès à ceux qui me le demandaient, maintenant j'en parle même plus tellement c'est chiant et très peu fonctionnel...

Pour preuve, je suis passé ici car après plusieurs mois mis de coté, j'ai tenté le visionnage avec vstream et comme d'hab c'est KO, je viens ici, je vois les posts, je me marre direct en lisant ce post et je comprends le souci encore une fois... Donc oui pour moi il y a un gros problème de développement, se cacher derrière un souci de coding de 2 sites, et bizarrement des top sites, mouhaiiiii... Haaa oui car c'est du DDL soi-disant....

Désolé de m'exprimer sur un mécontentement que je trouve fondé, hein.

Perso je ne viens pas pour passer la crème et tenter d'être bien vu, à bon entendeur ;)

Sur ceux j'ai d'autres chats à fouetter, je vous laisse vous déchainer, je repasserai dans 6mois voir la suite des travaux.
Mais je vais quand même me taper chaque site de la liste et voir si je trouve vos fameuses pépites :)

**Comment by yodidon** [comment]
Désolé je n’ai toujours pas saisie quelle info tu remontais ? Et si tu parle de cloudfare pour un périr souci de coding, je comprend que tu as bien d’autres chats à fouter, j’aimerais tellement que pour moi cloudfare ne soit qu’un petit soucis de codage ...

**Comment by sizanic** [comment]
> A part Sizanic qui prend le temps de répondre sans troller, le reste c'est OSEF surtout avec les fautes et le suçage de bourliches gratos...

Désolé mais tu viens de me perdre également.
Tu ne peux pas accuser les autres de troller et troller encore plus dans la même phrase.
Répéter en boucle que tout le monde fait des fautes c'est hors sujet et n'a que pour seul but d'insulter les autres.
=> Y'a pas plus trolling que ça !


> Apres les gars, que les devs arrêtent ou pas leur app, qu'ils le prennent bien ou mal, cela ne me changera strictement rien à ma vie

On le prend mal, parce qu'on ne te doit rien et tu viens nous insulter.

> de plus que je l'utilise rarement au final car ca ne marche jamais correctement, donc je viens de temps à autre remonter les mêmes soucis en permanence, on me sort cela va fonctionner dans la prochaine beta et basta je passe à autre chose... 

Très bien, fais ça, passe à autre chose 👍 


> Donc oui pour moi il y a un gros problème de développement, se cacher derrière un souci de coding de 2 sites, et bizarrement des top sites, mouhaiiiii... Haaa oui car c'est du DDL soi-disant....


Tu penses vraiment que les développeurs se cachent derrière de fausses excuses pour ne pas améliorer vStream, sérieusement ?
Tu sais ce qu'ils te disent les développeurs.
Tu ne veux vraiment oublier personnes dans tes insultes, t'es incroyable !


> Perso je ne viens pas pour passer la crème et tenter d'être bien vu, à bon entendeur ;)

trolling, trolling, trolling


> je repasserai dans 6 mois voir la suite des travaux.

non, pas la peine.
