### ISSUE TITLE
Le site neko-sama ne fonctionne pas

### ISSUE THREAD

**Issue by alphan0x** [Kodi-vStream/venom-xbmc-addons#3216]
**Décrivez le bug**
Bonjour,
Lorsque j'essaie de regarder un animé sur Neko-Sama, je clique sur le nom de l'épisode et il est affiché "Aucune information".
J'ai essayé de regarder directement sur le site Web et l'épisode existe bien.
Pourriez-vous m'aider svp ?

Merci !

**Votre system**
 - OS: Android
-  Appareil : Xiaomi Mi Box 3
 - Version Kodi  : 18.9 Leia
- Version Vstream : 0.8.5

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : Neko Sama
- Le titre du fim/serie : Initial D second stage e09
- Le nom du host : N/A

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by milkibreizh** [comment]
il faudrait que tu installes une version bêta de vstream 
ou que tu attendes une nouvelles mise à jours de vstream 
.... qui ne devrait pas tarder
