### ISSUE TITLE
Problème installation vStream : dépendance de script.module.idna version 2.6

### ISSUE THREAD

**Issue by yoblondy** [Kodi-vStream/venom-xbmc-addons#3217]
Je tente en vain aujourd'hui d'installer Vstream (via le repo disponible), ce n'est pas ma 1ère fois. 

Je reste coincée au niveau de installer depuis un dépôt. 

Voici le message que je recois : 
"La dépendance de script.module.idna version 2.6 n'a pas pu être satisfaite"

Qu'est-il possible de faire pour l'installation ? 

Pour info installation sur tablette Android sous Kodi Leia 18.9 

Merci d'avance.

**Comment by milkibreizh** [comment]
as tu essayé de vider le cache de ton appli kodi ? il y a une menu  dans android ou tu peux vider le cache de tes apps

**Comment by yoblondy** [comment]
Je l'ai fait et ça ne semble pas régler le problème

**Comment by milkibreizh** [comment]
j'y croyais pas trop mais c'était à défault d'utiliser la méthode radicale de désinstaller kodi puis 
puis de réinstaller les extensions une par une par la suite...
il vaut peu mieux que tu attendes que quelqu'un proposes une solution moins radicale
car je crois qu'il en existe ..a moins que tu est peu d'extension pour tester
et quand tu fais un update du module idna ?

**Comment by yoblondy** [comment]
J'ai fait l'update du module idna, et ca marche !

Merci beaucoup pour ton aide, je n'y avais pas pensé :)

**Comment by djdave51** [comment]
J'ai le même problème. Comment tu as mis à jour le module idna?

**Comment by yoblondy** [comment]
J'ai utilisé ce lien en telechargeant le fichier zip (version 2.6) et ensuite installation dans Kodi (via installer depuis un fichier zip)  :

https://ftp.igh.cnrs.fr/pub/xbmc/xbmc/addons/krypton/script.module.idna/

**Comment by djdave51** [comment]
Ok je vais essayer

**Comment by alKODIque** [comment]
Présentement, le dépôt officiel de Kodi est touché par un problème qui fait en sorte que plusieurs personnes ne peuvent plus installer d'addon..
Le problème sera sans doute réglé sous peu mais si vous êtes présentement dans l'incapacité de télécharger un addon, voici le script qu'il faut ajouter pour être en mesure de le faire:
- Pour Kodi v17 Krypton: https://mirrors.kodi.tv/addons/krypton/script.module.idna/
- Pour Kodi v18 Leia: https://mirrors.kodi.tv/addons/leia/script.module.idna/
- Pour Kodi v19 Matrix: https://mirrors.kodi.tv/addons/krypton/script.module.idna/
- 
(Jusqu'à présent, ce problème n'a seulement été vu que pour les utilisateur Kodi v.18 Leia)

Une fois ce script téléchargé, vous serez capable, comme à l'habitude, de télécharger puis installer vos extensions

**Comment by Arias800** [comment]
Je mets le label information car ce n'est pas un bug de Vstream a proprement parlé.

**Comment by Che-debarras** [comment]
Ya aussi un autre changement pour ceux qui utilie un addon qui change le DNS, ya plantage systèmatique au lancement de Kodi.
Je suis obligé de désactiver le DNS CHANGER APP , relancer Kodi et une fois qu'il est bien démarrer je réactive LE DNS CHANGER en allant sur kodi/extension/extension android/dns changer et je reviens en arrière pour ravoir kodi qui était active en arrière plan.

Quelqu'un d'autre a ce souci?

**Comment by djdave51** [comment]
Le problème à l'air d'avoir été résolu car j'ai refait une installation sans prendre le module à part et cela a fonctionné

**Comment by amaranthe81** [comment]
Bonjour, je viens d'installer raspbian puis kodi 18 mais impossible d'installer vstream. Je peux installer depuis un fichier zip mais ensuite quand je veux installer depuis un depot celà me donne un message de probleme de dependance script module. l'installation du zip donné par Alkodique n'a pas résolu le problème. quelqu un a t il une idée? Merci

**Comment by alKODIque** [comment]
Les script kodi officiels se trouvent tous ici:  http://mirrors.kodi.tv/addons/leia/  (pour Leia)
En plus de Idna, il a été reporté que les scripts suivants peuvent aussi causer problème:
- script.module.yaml
- script,module.pytz
Peut-être essayerde les installer manuellement avant de faire l'installation vStream ?

**Comment by amaranthe81** [comment]
salut, merci pour votre réponse. Après install des script module concernés celà me renvoie quand même le meme message "dependance script.module urlresolver  n'a pas pu être satisfaite."
j'ai desinstallé kodi puis reinstallé et refait la procedure mais toujours même problème. bien que je constate que script module urlresolver est marqué comme installé alors que j'ai le même message d'erreur....

**Comment by alKODIque** [comment]
Essaie d'installer le module ici: https://fusion.tvaddons.co/kodi-scripts/

c'est que le module demandé par vStream n'est pas le URLresolver officiel fourni par Kodi.

**Comment by amaranthe81** [comment]
Bonjour,
merci beaucoup alKODIque ! l'installation du module ci -dessus à permis l'install de vstream. 

Pour résumer, ça peut servir , j'ai donc installé : 
sur raspberry pi os (pour Raspberry Pi 3) :
- Kodiv18 Leia
- module.idna [https://mirrors.kodi.tv/addons/leia/script.module.idna/](url)
- script.module.yaml
- script,module.pytz, les deux ici: [http://mirrors.kodi.tv/addons/leia/](url)
- [ https://fusion.tvaddons.co/kodi-scripts/](url)
- vstream repository 0.0.3 zip
Pour info, il m'a fallu quand même installer open wizard pour kodi pour ameliorer les problèmes de memoire tampon,sinon impossible de lire de vidéo. J'ai pas vraiment fait de réglage, mes compétences et en informatique et en anglais s'arretent là, mais ça semble fonctionner pour le moment. 
Toutefois, mon idée de départ était d'avoir et kodi et un navigateur internet ,ce qui explique ma démarche de passer par l os pour raspberry plutot que d'avoir juste kodi sur libreElec,( qui au passage fonctionne avec la même procédure décrite ci-dessus.)
si les vidéos fonctionnent sur kodi, c'est  une autre affaire sur le navigateur dans l os raspberry. Les problèmes de buffering corrigés par open wizard dans kodi se retrouvent quand j'utilise le navigateur de l'os rasp. Du coup quasi impossible de visionner une quelconque video, sur youtube ou sur arte.tv par exemple (je sais il existe un addon arte+7 mais il n'y a pas tout, allez savoir pourquoi...exemple "l'emission"quand l'histoire fait date" est présente sur le site arte tv mais pas dans l'addon arte+7 de ma nouvelle install (alors qu elle y était dans mon ancienne install LibreElec ) Et pour ce qui est de l'addon youtube, j'ai perdu un temps fou à essayer les histoire de API sans succés...
Donc petite bouteille à la mer , si quelqu un a une solution pour améliorer mon problème de mémoire tampon de mon os raspberry....
