### ISSUE TITLE
Problème installation vstream

### ISSUE THREAD

**Issue by stephcris1616** [Kodi-vStream/venom-xbmc-addons#3218]
Bonjour,
Lors de l'installation de vstream sur ma box Android x96mini via Kodi, le message "la dépendance de script.module.idna version 2..6 n'a pas pu être satisfaite" apparaît.
Vstream ne s'installe pas.

**Mon system**
 - OS: Android
-  Appareil x 96mini
 - Version Kodi  18.9 leia
- Version Vstream 0.8.5

![IMG_20210131_120323](https://user-images.githubusercontent.com/78300750/106381950-7e5da580-63bc-11eb-8fd7-71913f6cda89.jpg)

Je suis désespérée a l'approche d'un prochain confinement. Merci de votre aide.

**Comment by Arias800** [comment]
Tu as ta réponse ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3217#issuecomment-770359374

**Comment by stephcris1616** [comment]
Merci infiniment.
Ça fonctionne apparemment parfaitement bien.
Super !!!
