### ISSUE TITLE
informations ne fonctionne plus

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3219]
PLUS d'information sur les films et séries  ... 
Je ne se sais si cela a été signalé, je ne trouve pas.

Merci pour votre correction

 - OS: [Windows et Android]
-  Appareil pc - android tv  - freebox pop  et google tv
 - Version Kodi .18.9
- Version Vstream  0.8.5

**Comment by Arias800** [comment]
C'est corrigé dans la beta.

**Comment by sizanic** [comment]
Avec quelle option la fenêtre ne s'ouvre pas ?

![image](https://user-images.githubusercontent.com/47307622/106392079-9bac6700-63f0-11eb-8639-307b87bc6e5e.png)


Il existe trois choix pour la fenêtre d'information : 
- la fenêtre vStream
- la fenêtre du skin
- la fenêtre ExtendedInfo

**Comment by Arias800** [comment]
C'est l'affichage du skin qui ne fonctionne pas.

**Comment by kris06** [comment]
![info](https://user-images.githubusercontent.com/31409100/106393428-55a6d180-63f7-11eb-83d9-2c51f6eeb0c7.jpg)
