### ISSUE TITLE
recherche vocale : Fermeture intempestif de kodi

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3220]
Avez vous la possibilité de réparer cette anomalie qui bloque ou ferme KODI 1 fois sur 2,  à l'occasion d'une  recherche vocale ... ?
Je vous remercie

Freebox pop sous android tv - Google tv -  Android tv
vstream 8.5.3
kodi 18.9

**Comment by Arias800** [comment]
On n'a aucun contrôle là-dessus. C'est un problème qui existe depuis la 1ere version de Kodi 18.

**Comment by kris06** [comment]
merci pour votre réponse rapide, je m'en douté un peu. Dommage , en espérant une meilleure stabilité sur la future version kodi 19

----- Mail original -----
De: "Arias800" <notifications@github.com>
À: "Kodi-vStream/venom-xbmc-addons" <venom-xbmc-addons@noreply.github.com>
Cc: "kris06" <christian.gross@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 31 Janvier 2021 18:04:15
Objet: Re: [Kodi-vStream/venom-xbmc-addons] recherche vocale : Fermeture intempestif de kodi (#3220)





On n'a aucun contrôle là-dessus. C'est un problème qui existe depuis la 1ere version de Kodi 18.

**Comment by kris06** [comment]
erci pour votre réponse rapide, je m'en douté un peu. Dommage , en espérant une meilleure stabilité sur la future version kodi 19

**Comment by sizanic** [comment]
Je confirme, hors périmètre vStream.

Je cloture.
