### ISSUE TITLE
Catégorie Drama invisible et non fonctionnel

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3221]
**Décrivez le bug**

Les derniers maj beta font apparaître une catégorie supplémentaire sans nom entre Animés et documentaire lorsqu'on lance vstream (les menus d'accueil)
Ce menu sans nom n'ouvre pas , donc je me suis dis c'était pour les dramas peut-être ou juste une erreur

**Votre system**
 - OS: [, Android]
-  Appareil [k3 , S8+]
 - Version Kodi  [18.9]
- Version Vstream 0.8.5

**Comment by milkibreizh** [comment]
oui exact c'est bien le menu Dramas il a été fait très trés récemment peu être que tu as pris la bêta juste pendant
sa création ?

**Comment by Che-debarras** [comment]
> oui exact c'est bien le menu Dramas il a été fait très trés récemment peu être que tu as pris la bêta juste pendant
> sa création ?

J'ai pris toutes les maj beta jusqu'à aujourd'hui mais cette catégorie est invisible,  pas de nom et quand on veut l'ouvrir ya erreur.

C'est à  corriger ou déjà corrigé ?

**Comment by milkibreizh** [comment]
le soucis c'est que je n'ai pas de bug sur mon win10 pour voir où  la correction pourrait être faite

**Comment by Che-debarras** [comment]
> le soucis c'est que je n'ai pas de bug sur mon win10 pour voir où la correction pourrait être faite

Tu as la catégorie Drama dans l'accueil de vstream ?

**Comment by Arias800** [comment]
@Che-debarras j'ai fait une modif dans la beta et ça a corrigé le problème chez moi (même si c'était pas le but initiale xD). Par contre j'ai peut-être tout casser, donc essaye et redis-moi.

**Comment by milkibreizh** [comment]
? cela marchais avant sur mon système

**Comment by Che-debarras** [comment]
> @Che-debarras j'ai fait une modif dans la beta et ça a corrigé le problème chez moi (même si c'était pas le but initiale xD). Par contre j'ai peut-être tout casser, donc essaye et redis-moi.

J'ai testé la version 0.8.6, la catégorie drama apparait
Sauf que drama dernier ajout il est vide
Drama genre n'a que 3 sources (asian insane, animeultim,skyanim
Sources  yen a 3 aussi (asian insane, animultim et viki)

**Comment by razorex** [comment]
Le cache pose parfois souci. j'ai tester avant de PR sur 2 os et chez moi pas de soucis.

**Comment by milkibreizh** [comment]
@Che-debarras 
c'est donc ok ?
