### ISSUE TITLE
Erreur Decryptage du lien...

### ISSUE THREAD

**Issue by alextreme7711** [Kodi-vStream/venom-xbmc-addons#3222]
Erreur decryptage du lien lorque que j essai d ouvrir n importe quel lien sur ZT

Android
Nvidia shield tv
Kodi 18.9
vstream 0.8.5.6

**Comment by Niconimes** [comment]
Idem chez moi en version 0.8.5, sur box Android avec Kodi 18.9

Le dim. 31 janv. 2021 à 23:48, alextreme7711 <notifications@github.com> a
écrit :

**Comment by Che-debarras** [comment]
#3214
