### ISSUE TITLE
pastebin et tmdb (metadonnée)

### ISSUE THREAD

**Issue by amidevous** [Kodi-vStream/venom-xbmc-addons#3223]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: Android
-  Appareil KingBox V2
 - Version Kodi  18.9 leia
- Version Vstream 0.8.5

**Nous devons le reproduire**
je voulue tester la nouvelle fonction pastebin
je trouve que le principe et bien cependant les métadonnée ne sont pas charger sur le tmdb
sur les autres host c'est correctement charger depuis le tmdb
mais sur pastebin y a aucune information afficher alors que j'ai indiquer l'id tmdb

voici le pastebin utiliser

https://pastebin.com/raw/qEbufwU3

pouvez vous me dire s'il s'agit d'un bug a corriger

ou si y aune erreur dans le patebin bien que je ne pense pas

car les liens sont correctement charger seul les métadonnée ne sont pas charger

j'ai volontairement mis l'id du tmdb car quand celui ci n'est pas mis

il arrive très souvent que l'api tmdb ne renvoie pas le bon résultat a partir du nom

au niveau de vstream les métadonnée sont bien entendu activer

et j'utilise ma propre clés api tmdb

tmdb api info

https://api.themoviedb.org/3/tv/4614?language=fr&api_key=yourapikey

**Comment by sizanic** [comment]
Bonjour,

j'ai bien les informations issues de TMDB avec ton pastebin.

**=> Pour ce qui concerne les informations de la série.**

Tu ne peux pas avoir les informations au niveau des saisons ni au niveau de épisodes.
-> **Est-ce cela que tu cherches ?**


Je viens malgré tout d'apporter une petite correction dans vStream car je ne pouvais pas accéder à ton pastebin.
(mais c'est sans lien avec les informations de média).

**Comment by amidevous** [comment]
juste qui et la jaquette et le descriptif de la série sur le coté gauche comme pour les autres lien

donc juste le overview et poster_path

la y a absolument rien qui s'affiche sa reste vide et sa fait moche quand c'est vide

**Comment by sizanic** [comment]
![image](https://user-images.githubusercontent.com/47307622/106522107-7b0f0a80-64df-11eb-8228-e1fedc7d861e.png)

**Comment by sizanic** [comment]
Peut-être peux-tu faire comme moi et mettre une image afin de comprendre ce qui manque chez toi.

**Comment by amidevous** [comment]
et ta fait sa comment je vois aucun info qui indique comment mettre l'image dans la doc

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Voir-et-partager-sa-biblioth%C3%A8que-priv%C3%A9e

**Comment by sizanic** [comment]
je n'ai rien fait, ce sont les infos TMDB.
Peux-tu faire une copie d'écran de ce que tu obtiens pour que je comprenne ce qui te manque à l'affichage.

**Comment by amidevous** [comment]
ben justement moi j'ai rien c'est juste marquer pas d'info disponible

![index](https://user-images.githubusercontent.com/7959572/106525517-62edba00-64e4-11eb-8aca-d3b5547371fa.jpg)

![index2](https://user-images.githubusercontent.com/7959572/106525532-697c3180-64e4-11eb-927b-4b4c67fde171.jpg)

![index3](https://user-images.githubusercontent.com/7959572/106525552-726d0300-64e4-11eb-97a9-8cef1f2e21bb.jpg)

par contre je voudrais pas que ce soit afficher comme toi mais comme quand ont prend sur les autres site

c'est a dire ici

![index4](https://user-images.githubusercontent.com/7959572/106525734-bf50d980-64e4-11eb-845b-4fba305f40cf.jpg)


comme la sur dpstream hd


![index5](https://user-images.githubusercontent.com/7959572/106526357-be6c7780-64e5-11eb-9d79-e21ac80b6c09.jpg)

**Comment by sizanic** [comment]
Sur ton image DPStream, ce ne sont pas les infos de TMDB, ce sont des infos récupérées sur le site DPStream.

TMDB n'a pas d'info pour les saisons et les épisodes.

Qu'as-tu comme informations au niveau de la série avec DPStream ?
(remonte d'un niveau)

**Comment by amidevous** [comment]
y a l'image et la note c'est tous mais il faudrait justement faire en sorte de mettre les info tmdb a cette endroit en plus le site dpstream hd ne donne les même info si tu désactive les métadonnée le synopsis n'est pas le même la c'est celui du tmdb qui et marquer et non celui de dpstream hd

de plus le but de mettre l'id du tmdb c'est justement que les info s'affiche si rien qui s'affiche comme la je ne vois pas l'utilité de pouvoir mettre l'id du tmdb ni même l'utilité de mettre sur pastebin puisse si tu prend directement sur ton compte uptobox c'est le même résultat

**Comment by sizanic** [comment]
Est-ce que tu peux me montrer la page NCIS avec DPStreamHD, s'il te plait.
Que je me rendre vraiment compte de ce qu'il manque.

**Comment by sizanic** [comment]
Avec une clef TMDB correcte et la recherche des métadonnées activée, voila ce que j'obtiens avec ton pastebin https://pastebin.com/raw/qEbufwU3

![image](https://user-images.githubusercontent.com/47307622/106530031-d5ae6380-64eb-11eb-9e7c-09aa81ea0d77.png)


Et voici la recherche de la serie NCIS avec DPstreamHD : 

 
![image](https://user-images.githubusercontent.com/47307622/106530127-08f0f280-64ec-11eb-9ad7-79bf44df7fee.png)


et voici ce que j'obtiens si **je n'active PAS** les métadonnées avec pastebin.

![image](https://user-images.githubusercontent.com/47307622/106530266-49e90700-64ec-11eb-8e6e-ac3ddef4f74b.png)

et voici ce que j'obtiens si **je n'active PAS** les métadonnées avec DPstreamHD :
![image](https://user-images.githubusercontent.com/47307622/106530320-638a4e80-64ec-11eb-9087-bdbea8b24196.png)

**cette image te rappelle quelque chose ???**

<br>
<br>

> je ne vois pas l'utilité de pouvoir mettre l'id du tmdb ni même l'utilité de mettre sur pastebin puisse si tu prend directement sur ton compte uptobox c'est le même résultat

**=> ESSAYES DE MIEUX FAIRE ATTENTION A TES REGLAGES AVANT DE PORTER UN JUGEMENT SUR L'UTILITÉ DE METTRE L'ID TMDB**

**Comment by amidevous** [comment]
c'est ce résultat que je cherche mais ma clé tmdb et correcte mais sa met tous en vide

comme je t'es montrée la justement et je suis avec la version du dépôt 0.8.5

puisse sur android tu peux pas mettre à jour les fichier hors dépôt

enfin tu peux mais c'est un bordel faux utiliser un pc copier tous sur clè usb pour coller sur la box

**Comment by amidevous** [comment]
même sur la béta sur le pc j'ai essayer pour et j'ai le même résultat

![image](https://user-images.githubusercontent.com/7959572/106532774-1c528c80-64f1-11eb-9c57-95875827a457.png)
j'ai bien les métadonnée activer avec ma clé tmdb

y a un autre réglage a faire et qui indiquer nul par ou ?

**Comment by sizanic** [comment]
Essaye de vider le cache des métadonnées.

**Comment by amidevous** [comment]
sur le pc effectivement en vidant sa marche mais pas sur l'android

et pourtant je les mis a jour 0.8.6 peux être il faux lui laisse plus de temps

je verrait demain si sa ce trouve demain il chargera correctement tous seul

par contre pourquoi tous sa ne vide pas tous seul quand ont ferme kodi sa serait bien mieux

quand même si je ferme firefox il vide le cache tous seul

je vois pas pourquoi kodi ne fait pas pareil c'est bizarre sa quand même

**Comment by sizanic** [comment]
> par contre pourquoi tous sa ne vide pas tous seul quand ont ferme kodi sa serait bien mieux

bah non, c'est tout l'interet de ce cache, ça permet de garder les informations (affiches, descriptions) en local sans avoir besoin d'aller sur internet à chaque redémarrage.
Même après redémarrage de KODI, ces informations n'évoluent pas.
Donc une fois qu'on les a, il faut les garder.

> et pourtant je les mis a jour 0.8.6

ça ne dépend pas de la version, ça a toujours fonctionné.

> peux être il faux lui laisse plus de temps

non, c'est instantané.

> quand même si je ferme firefox il vide le cache tous seul

Ce n'est pas le même genre de cache, et pas pour faire la même chose.
Ce n'est pas comparable.

Si ca fonctionne sur PC mais pas sur android, vérifies bien ton ID.

**Comment by sizanic** [comment]
> sur le pc effectivement en vidant sa marche mais pas sur l'android

Ce n'est donc pas un problème de vStream.
Aucune correction n'est nécessaire.
Je clos cette issue.
