### ISSUE TITLE
Filtrage adulte

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3226]
**Décrivez le bug**
Je n'ai pas saisi la fonction de désactiver ou activer le filtrage adulte car en étant désactivé il y a toujours du contenu adulte surtout sur les sites de mangas tel que hentai ecchi manhua sho Ai, , yuri/yaoi +16 etc... des genre de mangas pour adulte

J'espèrait que cela désactive ces genres et leur contenu mais non, est il possible de desactiver ces genres ou leur contenu pour pas qu'ils s'affichent ?

L'idéal serait d'avoir une fonction qui désactive une source ou une des ses catégories ou sous catégories (ou un menu favori dans l'accueil pour y mettre nos sources et genre etc...propre a vstream).

Apres il suffit simplement de ne pas mettre ces genres dans le fichier .py

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Arias800** [comment]
Pour le moment il n'est appliqué que pour un site. J'ai pas encore pris le temps de l'appliquer sur d'autres vu que ça demande une application manuel.

**Comment by sizanic** [comment]
Comme il s'agit d'une évolution en cours de mise en place, il n'y a pas de réel problème.

Pour un meilleur suivi des tickets ouverts,
@Che-debarras , je t'invite à cloturer ce ticket.
