### ISSUE TITLE
Host HS : Mystrm et userload

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3227]
**Décrivez le bug**

Ya 2 host qui ne marche plus depuis le 0.8.6

Mystrm et userload

Et ce quelque soit le site

**Votre system**
 - OS: [, Android]
-  Appareil [k3]
 - Version Kodi  [18.9]
- Version Vstream 0.8.6

**Comment by TmpName** [comment]
Bon ben mystrm, c'est pas pour demain ^^.

Le fichier ne contient plus qu'un JSON, mais j'ai meme pas été foutu de trouver quel fichier JS le traite.

**Comment by milkibreizh** [comment]
userload on le trouve dans la source animecomplete mais je n'ai pas de bug ?ex E162 black clover vostfr ok
par contre mystrm j'ai bien l'host hs

**Comment by Che-debarras** [comment]
Je clos car mystream est résolu 
Quant a userload, c'est sur une source pas encore dispo en test de yodidon
Celui la meme qui a resolu mystrm.
