### ISSUE TITLE
Probleme d'ouverture

### ISSUE THREAD

**Issue by johnboisvert** [Kodi-vStream/venom-xbmc-addons#3228]
**Décrivez le bug**
lorsque j'ouvre vstream je vais dans populaire movie ca cherche 5 sec et ca arrete j'ai essayer avec mon autre box tous 2 Formuler Z8 et Formuler Z7 meme chose et 2 de mes amis fonctionne avec 2 box différente et ca fais meme chose 
version de kodi 18.9

savez vous si je peut faire quelque chose? j'ai essayer de réinstaller ca ne fonctionne pas 

merci 

ps: great job vous etes fort !!! MERCI

**Comment by Che-debarras** [comment]
Tu parles de recherche visuelle ? Parce que si c'est le cas tu a deja de la chance car chez moi il ne se passe rien.
Peu importe la categorie,  ya aucune recherche donc je me demande as tu installer la beta?

**Comment by johnboisvert** [comment]
Oui recherche visuel 
j'ai rien touché

**Comment by alKODIque** [comment]
Bonjour,
Tu fais probablement allusion au menu "Films Populaires" situé à l'intérieur de la Recherche visuelle...

en version 0.8.5, la clé API TMDb de vStream est devenue obsolète. Bien que vStream possède maintenant une nouvelle clé fonctionnelle pour l'addon depuis la mise à jour vers la version 0.8.6 (version actuelle); pour que cette dernière soit prise en compte, il faut désinstaller puis réinstaller vStream à nouveau afin que l'ancienne clé disparaisse des fichiers de données.

Alors puisque la recherche visuelle est propulsée par TMDb, ce menu deviendra accessible pour toi (y compris la section "Films populaires")  lorsque tu auras fait cette réinstallation de vStream.

L'autre méthode tout aussi fonctionnelle consiste à aller insérer ta propre clé API TMDb dans les paramètres de vStream (si tu en possède une) puis de nettoyer le cache de vStream par la suite. Ceci t'évitera de désinstaller et de réinstaller l'addon a nouveau en plus de te permettre d'accéder aux données de ton compte personnel TMDb.

Voilà :)

**Comment by johnboisvert** [comment]
Ojk merci beaucoup je vais essayer :)
