### ISSUE TITLE
Amélioration de Gui

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#3229]
Je précise juste que cette issue concerne principalement les contributeurs de Vstream.

Alors voilà, ça fait un moment que je me dis qu'avoir une fonction pour chaque type de contenu (addMovies; addAnimes...) c'est pas forcément pratique.
Donc pourquoi ne pas essayer de toutes les assembler en une seule. J'ai déjà commencé à faire des modifs, avec deux fichiers tests, pour voir ce qui peut être intéressant à faire.
Si vous avez des idées n'hésitez pas.
https://github.com/Arias800/Fichier-divers/tree/master/newGui

**Comment by sizanic** [comment]
je ne suis pas complètement convaincu de l'interet 🤔 

Il faut préciser le type dans le premier paramètre, ce qui ne fait pas forcement gagner en développement pour l'appelant.
Il faut continuer à faire des 'if' pour passer le bon paramètre plutôt que d'appeler la bonne fonction.

La responsabilité de la définition du type est déplacée à l'extérieur de la méthode.
Il ne faut pas se tromper avec le paramètre qui est du simple texte (A remplacer à la rigueur par des constantes).

Actuellement, on ne se souci pas du "Type" lorsqu'on appelle la bonne méthode.
addMovies va positionner le type "movies", addSeries le Type 'tvshows', etc..
La responsabilité du type est portée par la méthode.
=> Moins de risque de se tromper
=> Plus facile à maintenir car regroupé

Et en plus, il n'y a pas que le Type qui définie le contenu mais aussi le 'meta' et la 'cat'.

Ce que je trouverai plus intéressant, c'est que toutes les méthodes (addmovies, addanime, addseries,..) appelle un code commun pour l'initialisation de ce qui est commun, puis gère ce qui est spécifique.

Ce code commun ressemble à ta fonction `addNewDir`, il faut lui ajouter les paramètres 'meta' et 'cat'.


Ce qui donnerai : 

```
def addNewDir(self, Type, sId, sFunction, sLabel, sIcon, sThumbnail='', sDesc='', oOutputParameterHandler='', meta, cat):   
        oGuiElement = cGuiElement()
        cGui.CONTENT = Type
        oGuiElement.setSiteName(sId)
        oGuiElement.setFunction(sFunction)
        oGuiElement.setTitle(sLabel)
        oGuiElement.setIcon(sIcon)
        oGuiElement.setMeta(meta)
        oGuiElement.setCat(cat)
       ...

```

En procédant ainsi, on ne modifie pas l'appel des fonctions existantes mais juste leur contenu, ce qui donne : 

```
def addMovies(self, sId, sFunction, sLabel, sIcon, sThumbnail, sDesc, oOutputParameterHandler=''):
    addNewDir('movies', sLabel, sIcon, sThumbnail, sDesc, oOutputParameterHandler, 1, 1):

def addTV(self, sId, sFunction, sLabel, sIcon, sThumbnail, sDesc, oOutputParameterHandler=''):
    addNewDir('tvshows', sLabel, sIcon, sThumbnail, sDesc, oOutputParameterHandler, 2, 2):

def addAnime(self, sId, sFunction, sLabel, sIcon, sThumbnail, sDesc, oOutputParameterHandler=''):
    addNewDir('tvshows', sLabel, sIcon, sThumbnail, sDesc, oOutputParameterHandler, 4, 2):

def addMisc(self, sId, sFunction, sLabel, sIcon, sThumbnail, sDesc, oOutputParameterHandler=''):
    addNewDir('files', sLabel, sIcon, sThumbnail, sDesc, oOutputParameterHandler, 0, 5):

```

**Comment by sizanic** [comment]
Et sinon, on à déjà un endroit pour échanger sur du code entre dev 🤔

**Comment by TmpName** [comment]
Perso je penche plus pour l'idée de @sizanic, et pour les memes raisons.

**Comment by Arias800** [comment]
Le but c'est de limiter le nombre de lignes redondantes.
Après effectivement j'aime bien l'idée de Sizanic, j'avais effectivement pas pensé à faire comme ça et ça coïncide avec mon but initial.

Et j'ai fait l'issue ici, car le problème de la fonction discussion c'est que tout se mets a la suite et que c'est absolument pas pratique pour s'y retrouvé.

**Comment by razorex** [comment]
Rien à voir mais, peut être que je dis des conneries, est-ce que l'on ne peut pas aussi réduire cat et meta en un seul paramètre.
biensur il faudra harmoniser leurs "valeurs" ???

**Comment by TmpName** [comment]
La j'ai pas suivi ? en un seul parametre ? certaines parties du code dependent de kodi lui meme.

**Comment by razorex** [comment]
ok je pensais que cat étais  uniquement dans vStream.

**Comment by Arias800** [comment]
J'ai mis dans la beta un début de modification qui fonctionne chez moi.

**Comment by Arias800** [comment]
Est-ce que quelqu'un peut tester cette version sous Kodi 18, car il corrige [ce bug](https://github.com/Kodi-vStream/venom-xbmc-addons/commit/d7ddc0aa7253658dc1d3b246019a1676cf06c2d1#r46870997) sous Kodi 19. Mais je ne sais pas si ca fonctionne aussi sous Kodi 18.
https://github.com/Arias800/Fichier-divers/blob/master/newGui/gui.py

**Comment by razorex** [comment]
Bon ben c'est peut etre trop tard mais moi je suis sous kodi 18.5 (windows 7) et 18.7 (box android)  si jamais

**Comment by sizanic** [comment]
Ce code est maintenant opérationnel dans vStream 👍
