### ISSUE TITLE
Television: IPTV (Official) et IPTV(Sites) ne marchent plus depuis quelques mois

### ISSUE THREAD

**Issue by gergyverjux** [Kodi-vStream/venom-xbmc-addons#3230]
Système: KODI 18.9 Windows 10 - KODI RPi Libreelec
VStream 0.8.6

Sous Télévision>IPTV (Official) la plupart des chaînes ne marchent plus 
Sous Télévision>IPTV (Sites) la plupart des sources ne donnent plus de liens 

Par ex:  
IPTV (Official) > France 2 retourne une erreur 410
IPTV Sites > IPTVGratuit > no module named IPTVgratuit

**Comment by Che-debarras** [comment]
C'est pas tres fiable ces sites.
Pour iptv le mieux c'est l'application Rokkr

**Comment by sizanic** [comment]
On va supprimer l'accès à IPTV dans vStream.

vStream doit rester concentré sur le Streaming.

@gergyverjux 
Bonne nouvelle, il existe des chaines en "streaming", qui ont donc leur place dans vStream car elles ne sont pas diffusées en IPTV.

Retrouves-les dans les source "ChannelStream" et "Streamonsport".

**Comment by gergyverjux** [comment]
Merci @sizanic , même si je ne suis pas certain de comprendre la différence entre IPTV et streaming

**Comment by Arias800** [comment]
J'aimerai au moins gardé l'iptv des chaines officiels.

**Comment by gergyverjux** [comment]
> J'aimerai au moins gardé l'iptv des chaines officiels.
Mais elles marchent pour vous ? France 2, France 5 etc...

Moi aussi je regrette IPTV(officiels mais aussi Sites, il y avait de bonnes sources il y a quelques mois

**Comment by Arias800** [comment]
Pour les chaines de France télévision j'ai deja une correction de pretes.
Les sites malheureusement sont tous sois mort, sois sans liens stabe. Dommage.

**Comment by Arias800** [comment]
@gergyverjux Les chaines France TV remarche avec la correction que je viens de faire.

**Comment by sizanic** [comment]
> Merci @sizanic , même si je ne suis pas certain de comprendre la différence entre IPTV et streaming

Le streaming, c'est lire un flux de données au fur et à mesure qu'il est récupéré d'internet, et ce n'est pas réservé pour les flux vidéo. Il n'y pas d'étape de téléchargement.
C'est largement utilisé pour de la musique ou des films, sur les sites de streaming, la lecture des films ne se fait pas en IPTV.
On peut streamer directement un fichier vidéo comme un fichier .avi ou .mp4.
Pas besoin d'outil particulier, un lecteur vidéo suffit.

L'IPTV utilise la principe du streaming, mais pour des données spécifique à un flux vidéo.
C'est une surcouche technique, qui ajoute des contraintes.
C'est pour un certain format de données, et il faut un client IPTV, un outil qui sait décoder ce flux.

Un peu de lecture : 
https://box-android-tv.fr/streaming-vs-iptv-quelles-sont-les-differences/
https://www.iiro.eu/iptv/

**Comment by yodidon** [comment]
Kepliz utilise un m3u8 extinf, il n’y a pas de relation possible ?

**Comment by Arias800** [comment]
Non je ne pense pas. Kepliz a l'air d'être un cas à part.

**Comment by sizanic** [comment]
IPTV Officiel -> quelques corrections depuis
IPTV listes -> supprimées de vStream.
