### ISSUE TITLE
Impossible d'importer la BDD de vStream

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#3231]
Depuis les paramètres, l'action "Importer la bdd (marque-pages, historique)" ne fonctionne pas.
(ATTENTION, récupérer la Beta qui contient la correction pour l'export).

```
WARNING: RunScript called for a non-script addon 'plugin.video.vstream'. This behaviour is deprecated.
NOTICE: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
NOTICE: 	[PLUGIN] vStream: load site globalRun and call function sauv
NOTICE: 	[PLUGIN] vStream: SQLITE 3 as DB engine
ERROR: XFILE::CFile::Delete - Error deleting file C:\Users\User1\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\vstream.db
ERROR: XFILE::CFile::Delete - Error deleting file special://home/userdata/addon_data/plugin.video.vstream/vstream.db
ERROR: XFILE::CFile::Delete - Error deleting file C:\Users\User1\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\vstream.db
ERROR: XFILE::CFile::Delete - Error deleting file special://home/userdata/addon_data/plugin.video.vstream/vstream.db
```

**Comment by sizanic** [comment]
Le fichier db ne peut pas être écrasé car il est utilisé.
Et si on l'efface à la main avant de faire l'import, on se retrouve avec un fichier db vide.

**Comment by Arias800** [comment]
Je déterre cette issue.
Je suis en train de corriger ça en ajoutant un `__enter__` et un `__exit__` dans le code de la base de donnée et en utilisant `with` pour l'appeler.
Ça permet aussi de supprimer le `__del__ `(et donc par extension l'erreur qui apparaissait sur Android).
