### ISSUE TITLE
Rechargement de la page en boucle

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3232]
**Décrivez le bug**
Apres une recherche globale quand on clique sur un film ou serie  et qu'on revient en arrière il relance la recherche globale.
Meme en cliquant sur la serie/film , il ouvre pas la serie/film mais relance la recherche globale

Testé avec le mot Honor comme mot clef pour la serie your honor et sur 4kstrmz et zustrm ou filmstrmng.lol ça relance la recherche globale

J'abandonne la recherche globale et je vais directement dans ces sources et il se trouve que quand on clique une serie dans series dernière ajout, il recharge la page des series derniere ajout au lieu de l'ouvrir.

Donc je ne sais pas combien de source a ce bug, mais en gros ca recharge la page d'où on a cliqué  au lieu lleu de l'ouvrir et idem si on fait retour

J'ai remis une version beta qui date d'aujourdhui 12h34 c'est a dire jusqu'à cette maj 3c2be87

Et tout reviens normalement donc le problème viens des modifs apres ce commit

**Votre system**
 - OS: [, Android]
-  Appareil [kingbox k3]
 - Version Kodi  [18.o]
- Version Vstream 0.8.6 avec le dernier commit ( mod gui inclus)

**Comment by Che-debarras** [comment]
#3233

**Comment by Arias800** [comment]
Je viens de tester sous Android et avec les toutes dernières modifications je n'arrive pas à reproduire le bug.
Donc visiblement ça a été corrigé.

**Comment by Che-debarras** [comment]
Je teste et je réédite mon msg
