### ISSUE TITLE
Bug bêta

### ISSUE THREAD

**Issue by mickve** [Kodi-vStream/venom-xbmc-addons#3233]
**Décrivez le bug**
Bonjour j ai fais une mise à jour depuis la bêta et j ai plein de site qui marche pas.( pas d accès au host) sur les série,alors que quand je reviens sur ma mise a jour que j ai faites il y a 2 jours tout fonctionne.
**Votre system**
 - OS: [ Android]
-  Appareil [beelink gt king]
 - Version Kodi  [18.9]
- Version Vstream 0.8.6

**Nous devons le reproduire**
Pour cela il nous faut:
- french stream.lol et d autre
- Toute les séries
- Le nom du host (pas d accès)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by Che-debarras** [comment]
Lis #3232 et si c'est le même,  supprime ton sujet
