### ISSUE TITLE
Trakt et pagination 

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3235]
Bonjour :)

Lorsque je navigue à l'intérieur de mon compte Trakt, la pagination de 10 éléments par page fonctionne bien... en seulemnt, il m'est impossible d'aller au delà de la 2e page. Il n'est plus possible d'avancer par la suite.

exemple, indique avoir plus de 100 items.. je vois bien dans l'entête que je suis à la page 2/11 mais il n'y a plus de flèche au bout du 10e élément de la page 2 permettant d'aller vers la 3e page.

EDIT: j'ai oublié de mentionner  que je vis ce problème seulement avec mes listes personelles et mes listes aimées. Les listes populaires et tendances ne me causent pas cet ennui :) 

Je n'ai pas de log a donner puisque je n'ai pas de message d'erreur...

j'ai la bêta  d'installée  (il y a quelques heures) sur ma nvidia shield, toujours sous kodi 18.9 Leia

Merci :)

**Comment by Arias800** [comment]
Impossible à reproduire sur Kodi 19, faut voir si quelqu'un peu le reproduire sous Kodi 18.

**Comment by alKODIque** [comment]
C'est étrange.. j'ai vu que tu avais fait un commit pour Trakt alors j'ai téléchargé. J'ai réglé le nombre d'items à afficher à 25 puisque tu as ajouté cette fonctionnalité 👌

Et magie... je vois maintenant les pages subséquentes dans mes listes 🤷🏻‍♀️

Merci beaucoup @Arias800  pour ton suivi

**Comment by alKODIque** [comment]
Bonjour :) 

Je ne souhaite pas ré-ouvrir l'issue mais je me demandais si il était possible d'ajouter une pagination ailleurs que pour les listes? Via notre collection par exemple... Si nous possedons quelques milliers de films/series, nous ne pouvons pas entrer dans la section proposée car beaucoup trop d'items pour permettre l'ouverture ..

Merci :)

**Comment by Arias800** [comment]
C'est fait, normalement il y a une limite partout dans Trakt.

**Comment by alKODIque** [comment]
ça fonctionne bien partout dans Trakt
Merci beaucoup ☺️ 👍
