### ISSUE TITLE
impossible de lire les informations ...  deja signalé

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3236]
toujours 
![info](https://user-images.githubusercontent.com/31409100/107568468-51449a80-6be7-11eb-844b-cec6f60374af.jpg)
impossible de lire les info sur les films et series...  voir capture jointe

**Votre system**
[Windows, et  Android
 - Version Kodi  18.9
- Version Vstream 0.8.6

**Comment by sizanic** [comment]
Il faut une clef TMDB valide pour avoir les informations.

Soit tu crées ta propre clef que tu déclares dans les paramètres de vStream, soit tu utilises celle de vStream 0.8.6.
Pour cela, rends-toi dans les paramètres de vStream, dans l'onglet "Général", utilises l'action "D'origine".

**Comment by Niconimes** [comment]
> Il faut une clef TMDB valide pour avoir les informations.
> 
> Soit tu crées ta propre clef que tu déclares dans les paramètres de vStream, soit tu utilises celle de vStream 0.8.6.
> Pour cela, rends-toi dans les paramètres de vStream, dans l'onglet "Général", utilises l'action "D'origine".

Ça marche parfaitement, merci du tuyau 👍

**Comment by kris06** [comment]
Merci infirment, tout est en ordre à présent
