### ISSUE TITLE
Merci pour le support de ZT

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#3237]
Juste un petit remerciement à l'équipe de Vstream de continuer à supporter le ZT 👍 
C'est encore plus apprécié quand VoirF est sous cloud maintenant. :(

**Comment by milkibreizh** [comment]
pour  VoirFilm tu peux utiliser la source  Stream Complet et vérifier à l’adresse h__ttps://www.stream-complet.biz/
qu'elle contient quasiment les mêmes films et séries avec les mêmes liens,cette source a été faite justement dans le but
de se substituer au ressources de VoirF :-)

**Comment by lelooser** [comment]
La recherche sur ZT ne fonctionne pas pour moi. Est-ce que c'est lié à ligne 374 sur sPattern?

**Comment by sviet2k** [comment]
Merci beaucoup @milkibreizh.
J'aime bien le LOL:-) série dans VoirF

**Comment by peto51** [comment]
Pour moi la source ZT m'affiche "aucune information".
j'ai testé plusieurs DNS mais j'arrive au même résultat.

**Comment by peto51** [comment]
Pour moi les 3 vrais bonne sources que sont ; ZT, Wawacity et Tirexo aucun des 3 ne fonctionne, c'est vraiment dommage, du coup je cherche manuellement sur ses sites avec mon tel, je prend le lien uptobox, l'enregistre sur mon compte et ensuite dans vstream j'ouvre mes fichiers uptobox.
Ca fait quelques manipulations mais c'est ce que j'ai trouvé de plus pratique car la recherche sur vstream prend des heures a trouvé un lien valide, tant pis on se débrouille autrement.

**Comment by lelooser** [comment]
Z T fonctionne pour le moment mais pas la recherche. J utilise les DNS de quad 9. Je préfère Z T et Extrême down (avant la modif all debrid) mais celui qui a crée ces Source sur v stream ne tien plus a être sollicité déçu (trop de taf à cause du codage dégueux de ces sites ddl). Du coup quand ça bug, Je prend les liens sur les sites avec un navigateur et j'utilise hoster direct dans les outils V stream avec l'appli Kore. J'évite d'utiliser un navigateur web car c'est pas des sites fiables mais bientôt on aura plus le choix si la team ne s'occupe plus des sites ddl. Ça sera fini la haute qualité sur les sites de v stream. Y a aussi pastebin pour la FHD dolby dts... mais c'est galère à récupérer les codes sans vraiment savoir le contenu avant de les ajouter.
