### ISSUE TITLE
Affichage des pochettes

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3238]
![779E0A43-F37B-4D68-887A-954CD6BAECF0](https://user-images.githubusercontent.com/49578130/107607482-5d405480-6c07-11eb-8b06-9e9ea39e057e.png)
Bonjour :)

J'ai installé la bêta et depuis, lorsque je navigue à l'intérieur de vStream, peu importe la source que je choisi, la pochette du média affiché est la même pour tous les médias du dossier et correspond au premier film/série de la liste.

Seule la source Pastebin ne semble pas affectée. Pour les autres sources, c'est comme l'impression d'écran ici haut.

kodi 18.9
Nvidia Shield

**Comment by alKODIque** [comment]
Je préfère inscrire ici plutôt que de faire une édition de ma publication précédente...

- La recherche visuelle est fonctionnelle, je vois les bonnes jaquettes de films et series
- Les médias à l'intérieur de mon compte Trakt (listes) sont aussi ok
- La source Pastebin est ok

Le problème que j'ai décrit plus haut semble est présent seulement lorsque nous naviguons à l'intérieur d'une soure donc.

Voila :)

**Comment by sizanic** [comment]
Je n'ai pas ce problème avec zuStream par exemple.

**Comment by Arias800** [comment]
J'ai fait une modif, chez moi ça règle le problème.
Et sinon je ne vois pas du tout comment corrigé ce problème.
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/c803b2301e7f7d18bc77157ae0ce72a039276a09

**Comment by sizanic** [comment]
je vais regarder, car ta modif n'est pas propre.
Car certains site passe l'id TMDB car il le connaisse, et là tu l'enleve et ça relance une recherche TMDB.

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/c803b2301e7f7d18bc77157ae0ce72a039276a09#diff-bc2c1abecd6d7b9b727a9e3c00a8a0bd3beee11b3607d9c98a77cce26ff335a6R531

**Comment by Arias800** [comment]
Je sais quel n'est pas propre, j'ai juste pas de meilleurs idée pour le moment xD

**Comment by alKODIque** [comment]
> Je n'ai pas ce problème avec zuStream par exemple.

C'est étrange, sur ma shield, j'ai bel et bien ce problème sur zutream également 🤷🏻‍♀️ et je suis comme toi toujours sous kodi 18.9

Merci a vous 2 pour le suivi! 👍
C'est apprécié 😊

**Comment by sizanic** [comment]
Une correction dans la Beta.

A tester svp.

**Comment by Arias800** [comment]
Ça a effectivement résolu le problème chez moi.

**Comment by alKODIque** [comment]
Oui! Résolu pour moi aussi :)
