### ISSUE TITLE
Une idée qui pour lire les episodes en suivant 

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3239]
L'idée est simple, pour pouvoir lire les episodes en suivant comme netflix il faudrait que les episodes sois sur un meme dossier et non pas un dossier par episode.

L'idéal serair que les episodes soit trier par host pour avoir touts les episodes d'un host sois un meme dossier mais cela n'est pas obligatoire car il y a la fonction filtre de kodi qui affiche que le host filtré 

Je sais pas si je suis claire mais si on a tous les episodes quelque soit le host dans le meme dossier.
On filtre par exemple avec "DOOD" et tout seul les episodes hébergé par DOOD sont affiché et on fait "LIRE A PARTIR DE L'ÉPISODE" #1  et il lira les episodes de 1 au suivant.

Mals voila les sources ont des chaque episode dans un dossier séparé 

Donc serait il possible pour chaque sources de regrouper tous les episodes dans un même dossier pour pouvoir lire les episodes les uns après les autres automatiquement

**Comment by sizanic** [comment]
Nous savons que l'enchainement des épisodes est une fonctionnalité très attendue.

Merci pour cette idée.
Elle nous influencera peut-être dans nos choix de mise en œuvre.
