### ISSUE TITLE
Dialog notification

### ISSUE THREAD

**Issue by eco-plus** [Kodi-vStream/venom-xbmc-addons#3240]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.
Bonjour, l'utilisation de ce pop-up sur les récentes version de vstream est une mauvaise idée pour les sites car quand le site bug et ça arrive souvent ,il reste en place et est impossible à fermer.
voir photo

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.
![1613216645981](https://user-images.githubusercontent.com/61077544/107849297-a4db0200-6dfa-11eb-9698-59db0d2d1234.jpg)

**Comment by TmpName** [comment]
Alors pour une fois que je vois quelqu'un qui est comme moi encore sous confluence, j'arrive pas pour autant au meme resultat.

Tu fais comment pour provoquer ca ?

**Comment by eco-plus** [comment]
bah le site ne répondé pas donc retour arrière et bug ce genre de dialog ne peut être canceled.

**Comment by TmpName** [comment]
Mais tu as été ou ?
Moi sur les recherches quand ca scannes les sites, j'ai une fenetre au centre avec le bouton "annuler"

**Comment by sizanic** [comment]
Oui, avant de dire que c'est "une mauvaise idée", merci de donner plus de détails.

Car j'ai tellement de retour positif sur la mise en place de cette fonction que je ne pense pas être le seul à penser que c'est au contraire une bonne idée.

Et la solution n'est pas de revenir en arrière mais plutôt de corriger lorsque ça plante.
Mais pour ça il nous faudrait plus de détail.

Et sinon, il te reste toujours la possibilité de revenir avec l'ancienne version du sablier, il y a une option pour ça dans les paramètres.

**Comment by eco-plus** [comment]
via series dernier ajout / fr stream lol mais je suis sur que ça ferait pareil avec un autre.
Retour arrière avec la télécommande parce que le site mettait 3 plombe a répondre et le dialog c'est ouvert.
Obligé de redémarrer kodi pour le fermé.

**Comment by TmpName** [comment]
Ha, tu as activé l'option dans les parametres ?
Ok c'est pour ca que j'ai pas le meme resultat.

**Comment by sizanic** [comment]
@TmpName 
Non.
Pour la recherche, c'est toujours l'ancien sablier, il n'y a que pour la navigation dans les sources que c'est le nouveau.

@eco-plus 
Pour certaines sources connues pour être très longues, il faudrait forcer l'ancien dialog dans leur code. C'est ce que j'ai fait pour une source d'animes qui propose des centaines de vidéos par menu.
Stream lol est toujours long ?
