### ISSUE TITLE
Compte TMDb et QR Code

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3241]
Bonjour, petite idée que j'ai eu:

Je me demandais, puisque plusieurs utilisateurs ont une box pour kodi et non un ordi, la procédure pour référer notre code TMDb est très longue... 

Croyez-vous qu'il soit faisable d'utiliser le QR code pour accéder directement au lien généré par vStream au lieu de le taper manuellement? 

Quelques références pouvant aider:
https://github.com/lincolnloop/python-qrcode
https://pypi.org/project/qrcode/
https://kodi.wiki/view/Add-on:QR-Code
https://github.com/SchapplM/python-qrcode

**Comment by sizanic** [comment]
Bonjour,

Si je comprends l'idée, ce serait d'afficher un QRcode à l'écran afin que l'utilisateur le scan pour se rendre sur l'url qui permet de référencer son compte TMDB.

**Comment by alKODIque** [comment]
Oui exactement

**Comment by Arias800** [comment]
C'est fonctionnel dans la beta.
