### ISSUE TITLE
Host mystrm HS

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3243]
**Décrivez le bug**
Comme dit dans le titre le host mystream ne fonctionne plus du tout
Sur navigateur il marche mais pas sur vstream , dossier vide

NB: peut-être aussi streamtape sur certains films je pense 

**Votre system**
 - OS: [, Android]
-  Appareil [kingboxk3]
 - Version Kodi  [18.9]
- Version Vstream 0.8.6

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site frenchstrm.lol 
- Le titre du fim/serie monsterhunter 
- Le nom du host (mystream)

**Comment by milkibreizh** [comment]
@Che-debarras 
une correction a été faite ,cela concerne l'host (allow_redirects) pour le film  monsterhunter j'avais rien dans le navigateur 
mais pour les autres liens cela semblent remarcher comme auparavant

**Comment by Che-debarras** [comment]
@milkibreizh pourquoi seriestrmngwtcH a été désactivé ?
Il fonctionne

**Comment by milkibreizh** [comment]
@Che-debarras 
elle avait réactivée avant ton post cela ne marche pas ?

**Comment by Che-debarras** [comment]
Tu parle de mystream ou seriestrmwatch ?
La je remet les corrections et je test
