### ISSUE TITLE
Real Debrid

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3244]
Bonjour,
Encore une fois merci à tous de nous permettre de profiter de ce super Addon, vous êtes vraiment au top.

Depuis la nouvelle version de Vstream j'avais un message dès que je lançais un lien 1fichier du genre "pas de visionnage sans premium", j'utilisais donc d'autres liens car j'ai un compte Real Debrid et en fouillant dans les paramètres de Vstream je découvre dans premium/login que Real Debrid a fait une apparition avec "Token" juste au dessus de UrlResolver.
J'ai donc entré mon Token et là, les liens sont accessibles mais presque tous les autres m'affichent un message d'erreur (fichier introuvable) et si je désactive UrlResolver ils sont dispo (mais ne sont débridés).

Comment faire en sorte que ça fonctionne ? Je ne rentre pas mon "Token" ou j'ai raté quelque chose ?

Box Android
Kodi 18.9
Vstream 0.8.6

NB: à moins que mon problème soit lié à UrlResolver comme bien souvent ://

**Comment by sizanic** [comment]
Bonjour,

Le token est pour l'instant utilisée par les sources Extrem Down et Pastebin.
Il faut renseigner le token et activer le mode.

Pour les autres sources, il  faut continuer à utiliser URLResolver.

**Comment by Niconimes** [comment]
> Bonjour,
> 
> Le token est pour l'instant utilisée par les sources Extrem Down et Pastebin.
> Il faut renseigner le token et activer le mode.
> 
> Pour les autres sources, il faut continuer à utiliser URLResolver.

Salut et merci beaucoup pour ta réponse rapide, je vais tester ça, par contre je t'avoue que je n'ai pas encore pigé le coup des pastebin mais bon ça viendra, merci encore 👍

**Comment by TmpName** [comment]
Et tu as ce resultat sur tout les hosts ?
Pas plus d'infos en log ?

**Comment by Niconimes** [comment]
En l'occurrence sur ce test sur tous les hits testés oui, pour le log tu le récupères où s'il te plaît ?

**Comment by milkibreizh** [comment]
Dans
_Options > paramètres de l'extension >Outils > outils_

il faut activer les logs
_activer les enregistrements des logs_

il faut enregistrer ton log à l’adresse h ttps://slexy.org/
_Upload Kodi log>_
(cela va peu etre planté car il y a un petit bug)

il te suffit alors d’aller  à l’adresse indiquée pour obtenir ton log
_Url de votre log h ttps://slexy.org/view/xxxxx_

**Comment by Niconimes** [comment]
Super merci, je fais ça dès que les gosses ont fini leur film ^^

**Comment by Niconimes** [comment]
Voici le lien de mon log:
h ttps://slexy.org/view/s21ZNPIX0o

**Comment by TmpName** [comment]
>2021-02-18 13:09:37.752 T:8582   ERROR: URLResolver: ResolverError Error - From: uptobox Link: https://uptobox.com/96djxmn472zl: The requested video was not found or may have been removed.
>2021-02-18 13:50:03.600 T:8980   ERROR: URLResolver: ResolverError Error - From: uptobox Link: https://uptobox.com/nvham7vi4721: The requested video was not found or may have been removed.
>
2021-02-18 15:14:51.041 T:9603   ERROR: URLResolver: ResolverError Error - From: uptobox Link: https://uptobox.com/mw00yw7ly5tg: The requested video was not found or may have been removed.

Le lien 1fichier a marché, le lien evoload aussi, uqload aussi, 

Un autre a rété
>2021-02-18 22:43:32.613 T:14310   ERROR: URLResolver: URLError Error - From: evoload Link: https://evoload.io/xxxxx: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> (ENCODED)
2021-02-18 22:43:32.624 T:14310  NOTICE: 	[PLUGIN] vStream: Erreur: Fichier introuvable

Evites uptobx et uptostrm, ou alors verifis si sur le site les liens existent vraiment.

**Comment by Niconimes** [comment]
> > 2021-02-18 13:09:37.752 T:8582   ERROR: URLResolver: ResolverError Error - From: uptobox Link: htt ps://uptobox.com/xxxxx: The requested video was not found or may have been removed.
> > 2021-02-18 13:50:03.600 T:8980   ERROR: URLResolver: ResolverError Error - From: uptobox Link: htt ps://uptobox.com/xxxxx: The requested video was not found or may have been removed.
> > 2021-02-18 15:14:51.041 T:9603   ERROR: URLResolver: ResolverError Error - From: uptobox Link: htt ps://uptobox.com/xxxxx: The requested video was not found or may have been removed.
> > 2021-02-18 12:06:01.740 T:7843   ERROR: URLResolver: ResolverError Error - From: uptobox Link: ht tps://uptostream.com/iframe/xxxxx: The requested video was not found or may have been removed.
> 
> Le lien 1fichier a marché, le lien evoload aussi, uqload aussi,
> 
> Un autre a raté, mais comme le premier a fonctionné, on va dire faute a "pas de chance"
> 
> > 2021-02-18 22:43:32.613 T:14310   ERROR: URLResolver: URLError Error - From: evoload Link: htt ps://evoload.io/xxxxx: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> (ENCODED)
> > 2021-02-18 22:43:32.624 T:14310  NOTICE: 	[PLUGIN] vStream: Erreur: Fichier introuvable
> 
> Evites uptobx et uptostrm, ou alors verifis si sur le site les liens existent vraiment, soit c'est les liens qui n'existent pas, soit c'est le resolver qui est bancale.

Ok merci beaucoup pour ta réponse et merci encore pour votre boulot, je passe en résolu
