### ISSUE TITLE
Plus de rating/genre/description

### ISSUE THREAD

**Issue by mifrey00** [Kodi-vStream/venom-xbmc-addons#3245]
Depuis quelques semaines je n'ai plus de rating/genre/description pour la plupart des films.  Pour certains j'ai une description et pas de rating.  Sous Covenant, j'ai toujours ces infos.

![screenshot000](https://user-images.githubusercontent.com/10077480/108622707-dd9e5b00-743a-11eb-9d09-83bca09d21ef.png)

**System**
OSMC on Raspberry Pi
Kodi 18.9
Vstream 0.8.6

**Comment by TmpName** [comment]
Rien a voir avec https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3236 ?

**Comment by sizanic** [comment]
Je pense aussi que ce sont les métadonnées qui ne sont plus récupérées dans ce cas.

**Comment by mifrey00** [comment]
Merci c'était ça ! Ça marche après avoir créer ma propre API key.
