### ISSUE TITLE
Recherche via Pastebin

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3247]
Bonjour,

Je crois qu'il y a un bug côté recherche dans la source Pastebin...

Lorsque j'utilise la recherche globale de la source, j'obtiens biens les résultats de tous les contributeurs qui possèdent le média à l'intérieur de leur paste. Si, par contre, j'utilise la recherche à l'intérieur de mon dossier "Series" qui inclu les pastes de plusieurs contributeurs, et bien j'obtiens seulement 1 seul resultat... probablement la première trouvée?

Faire le test avec la série "Young Sheldon"... elle se retrouve dans différents pastes...

merci!

**Comment by TmpName** [comment]
C'est toujours d'actualité ?

**Comment by alKODIque** [comment]
> C'est toujours d'actualité ?

non, je clos puisque c'est réglé
