### ISSUE TITLE
Kodi matrix et vstream

### ISSUE THREAD

**Issue by micka9743038** [Kodi-vStream/venom-xbmc-addons#3249]
En passant à kodi matrix (maj), vstream ne marchait plus sur mon tel et ma tablette, mon problème venait du 120 hertz!
En effet après avoir mis le tel et la tablette en 60 hertz et réinstallation de kodi de l'ancienne version + vstream, la mise à jour s'est fait (kodi matrix) importation des extensions et là, vstream marchait et marche toujours.

J'ai cherché un moment alors si ça peut aider certain!

**Comment by TmpName** [comment]
Ha, ca ca va etre utile je sens ^^.
Et si tu rechanges les options apres, ca re plante ? c'est quoi comme probleme ?

**Comment by sizanic** [comment]
Merci pour l'info.
Donc rien à modifier côté vStream, je clos cette issue.
