### ISSUE TITLE
Suivi des Bugs (Sources et Host)

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3251]
**Décrivez le bug**
Cinemegatoil : dossier ne s'ouvre pas HS
Voirfilm : dossier ne souvre pas. CLOUDFARE
E.D : lien ne s'ouvre pas RÉSOLU 

ADkami: catégorie drama ne s'ouvre pas RÉSOLUE MAIS LA CATEGORIE LISTE (ordre alphabétique) ne contient que des dossiers vide quelques soit la lettre

Skyanime : lien direct ne se lance pas, ça semble charger  mais fini pasr avorté 

Frch-strm.lol : les dossiers film sont tous vides quelque soit la categorie (series ok)
01strmng : dossiers films et series et année vides (genre ok)

Viki: lien host ne fonctionne plus 
Dood ne fonctionne plus ex The mauritanian sur Cinemay (et les autres clones : frenchstrm, hdsm...sur navigateur cela marche)

Wiflix : dossier vide aucun lien/dossier host pour chaque films ou series

**Votre system**
 - OS: [Android]
-  Appareil [kingbox k3]
 - Version Kodi  [18.9]
- Version Vstream last one last commit du 27.02.2021

**Comment by TmpName** [comment]
Cinemegatoil : HS chez moi
Voirfilm : Protection CF suivi de site HS
E.D : la par contre j'ai pas trouvé 

>ERROR: ConnectionError: HTTPSConnectionPool(host='ww w.extreme-down.tv', port=443): Max retries exceeded with url: /films-new-hd/new-bluray-1080p/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000106CDE10>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

**Comment by Arias800** [comment]
Rajoute "oRequestHandler.disableSSL()" au niveau des requêtes qui pose problème.

**Comment by Che-debarras** [comment]
Changement domaine pour wflx

**Comment by Arias800** [comment]
Je viens d'essayer et j'ai du juste faire une petite modif a la ligne 711 (que j'ai mis dans la beta), mais à part ça oui ça fonctionne.

**Comment by TmpName** [comment]
Toujours pas de mon coté ^^

`ConnectionError: HTTPSConnectionPool(host='ww w.extreme-down.tv', port=443): Max retries exceeded with url: /films-new-hd/new-bluray-1080p/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000C4405F8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`

Je viens de regarder sur internet, ca pourrait venir de la config internet ...., mais pouquoi ca marche sur navigateur alors ?

**Comment by Arias800** [comment]
Peut-être que ça vient du fait que j'utilise Kodi 19 et qu'il gère mieux le ssl ?

**Comment by milkibreizh** [comment]
@TmpName 
j'ai pareils !! si je mets w ww.extreme-down.tv au lieu de www ^^...
plus sérieusement ...je n'ai pas ce message d'erreur sous kodi 18 (sauf si je mets une url qui n'existe pas)

**Comment by TmpName** [comment]
Lol.

Apres ca peut venir de chez moi. Chez Che-debarras ce ne s'ouvrait pas, mais c'etait peut etre le bug corrigé par Arias800

**Comment by milkibreizh** [comment]
@TmpName 
@Che-debarras a précisé que c'étaient les liens qui ne souvraient pas et donc i:l avait acces au premier dossier
la corrections con

**Comment by milkibreizh** [comment]
@TmpName
@Che-debarras a précisé que c'étaient les liens qui ne s'ouvraient pas et donc il avait accès au premier dossier
et la corrections concernait en effets les liens
mais toi tu n'as pas accès au site semble t'il... /films-new-hd/new-bluray-1080p/ 
je sais que cela peu arriver chez d'autres mais pour l'instant je n'ai jamais eu le cas dans lequel je pouvais me connecter sur
le navigateur sans pouvoir me connecter sur kodi (omis un bug de vstream)..
en faites je serais curieux d'avoir ce problème

**Comment by Che-debarras** [comment]
J'ai pas suivi la conversation mais cela est résolu avec la correction de @Arias800 
Effectivement j'avais accès au dossier film ou serie mais c'est le dossier Host qui s'ouvre paq.
Ca doit affiché les captcha a selectionner mais la correction d' @Arias800 a corrigé le bug.

J'ai mis a jour le 1e poste.

**Comment by milkibreizh** [comment]
@Che-debarras 
skyanime
le site à momentanément désactivé les dl
la date d'activation est prévue pour le 09 mars

pour ADkami en tout cas sur mon sys, j'ai certains resultats dans vstream pour les listes
mais c'est vrais que c'est très souvent vides car le site adkami fournit moins de ressources 
(a moins que tu parles de ne pas pouvoir obtenir  la liste des films commençant par A par exemple)
il manque toutefois qqles résultats  dans vstream qui sont affectés par exemple à l'host ru

**Comment by Che-debarras** [comment]
Pour la liste alphabétique j'ai la liste des drama mais sans aucun contenu d'épisodes, mais d'autres listes alphabétique sont vides.
Possible que cela soit du au site qui n'a plus ces dramas ou plus d'épisodes mais autant de dramas et autant d'épisodes manquants j'ai pensé a un bug
