### ISSUE TITLE
TopReplay : Capcha jamais accepté

### ISSUE THREAD

**Issue by Chris059** [Kodi-vStream/venom-xbmc-addons#3252]
**Décrivez le bug**
Lorsque l'on veut lancer une vidéo disponible sur topreplay, il y a une vérification Capcha sous forme de portion d'image à sélectionner selon la question affichée. Malheureusement, ça demande toujours une nouvelle question, c'est sans fin.. alors aucune possibilité de visionner les replay.

**Votre system**
 - OS: [Android 19]
-  Appareil [Belink gt-1 mini]
 - Version Kodi  [18.4]
- Version Vstream [0.8.6]

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : TopReplay
- Le titre du fim/serie : Pékin Express saison 14
- Le nom du host : TopReplay

**Log**

**Image**

**Plus**

**Comment by Arias800** [comment]
On n'a malheureusement pas de contrôle sur la longeure du captcha, par contre je viens de corrigé un qui faisait qu'il n'était pas validé correctement.
Le captcha marche d'ailleurs mieux sous Kodi 19.

**Comment by falciatrice10** [comment]
Bonjour 
Apres la mise a jour vers la v1.0 extreme download demande un captcha pour afficher les liens.
