### ISSUE TITLE
Resolver et VSTREAM

### ISSUE THREAD

**Issue by jaja68** [Kodi-vStream/venom-xbmc-addons#3254]
Bonjour,

Depuis que je suis passé en version 19 de Kodi, je n'arrive plus à utiliser de resolver.
Auparavant j’utilisai URLRésolver version 5.1.22 par tvaddons.
J'ai tenté d'utiliser RésolveURL version 5.1.25 par gujal mais cela ne fonctionne pas non plus.

Rencontrez vous le même problème ?

Merci d'avance pour votre aide ou conseil.

-  OS Android TV
-  Appareil nvidia shield Pro
 - Version Kodi 19
- Version Vstream 0.8.6

Salutations.
jaja68

**Comment by alKODIque** [comment]
Je crois que le soucis sera réglé lors de la prochaine mise a jour officielle puisque des correctifs a cet effet ont été apporté a la bêta.
