### ISSUE TITLE
Suivi Bugs (Source et lien UNIQUEMENT ) de v1.0.0

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3255]
**_Remarque uptobox/strm**-:
❗Kodi 18 activer uptobox premium fonctiolne sans ID ni MdP
❗Kodi 19 activer uptobox premium avec Identifiant et mot de passe

**_Problème d'affichage :_**
Viki: une lettre b' devant chaque titre de film

**_Problème lié à  Cloudfare:_**
⚠️ZT : source ne s'ouvre pas 
⚠️Tirexo/Voirfilm: sous-catégories ne s'ouvrent pas 
☑DDL : Sous-categories ne s'ouvrent pas

**_Bugs du Dossier vides:_** 
✅frenchstrm.lol : dossiers vides RÉSOLU 
☑Kaydo : catégories qui s'ouvrent pas 
☑Adkami : bcp trop de dossiers vides du au licenciement des oeuvres ou bug à résoudre - **A supprimer?**

**_Bug de Host HS:_**
☑Zustrm.co: lien direct & GoUlmtd HS
☑Otaku-Att : lien direct HS
☑Viki : kodi 18.9, aucun dossier Series/Film ne s'ouvrent
☑Viki : Kodi 19 films/series manquants et dossiers films vident
☑Funeral4manga : dossier host Saruch.co & Allvid vide
☑Animecplt : Dossier host Ninjastrm & Google Vides
❗ saruch.co et ninjastream sont INCLUS urlresolver

🔹️**Pour les fans de dramas de Net_flix il y a ce site intéressant comme Zustrm.co il a pas mal de lien host : myasietv,co (avec 3 autres url de secours : bondrama,com /kdramavostfr,com /dramacoreen,cc)**

🔹️ **suggestions de sites qui pourrait remplacer strmcplt qui ne sont pas viable: 33seriesstrmng, seriesite,com, zoneseries.strm, Serie-strmng.io ou ❗ Clone Strmcplt : strmcplt.al ou strmcplts.me, filmcplt.al ou .ws**

🔹️**suggestions de site  manga: hdstr_eam.cool**

**Votre system**
 - OS: [Android 6.0 & 7.0 & 9.0]
-  Appareil [kingboxk3 ,Vorke z6 S8+]
 - Version Kodi  [18.9]
- Version Vstream v1.0.0 (inclus commit 5189f17 )

**Comment by TmpName** [comment]
01strmng, j'ai voulu corriger, mais ca deconne aussi sur le site, erreur 404

**Comment by Che-debarras** [comment]
> 01strmng, j'ai voulu corriger, mais ca deconne aussi sur le site, erreur 404
> Wiflix devrait remarcher.

Tu veux dire quoi par erreur 404? Tu n'as pas accès au site? Parce que moi j'ai accès. Y a pas d'erreur 404.

**Comment by TmpName** [comment]
La page d'acceuil oui mais cliques sur le menu, film ou serie.

**Comment by TmpName** [comment]
French-strm-lol devrait remarcher aussi.

**Comment by Che-debarras** [comment]
> La page d'acceuil oui mais cliques sur le menu, film ou serie.

Exact , je pensais que dans la catégorie film y'aurait les derniers films et mes plus vues e dans series les plus vues, les derniers saisons et derniers episodes.
En gros ce qu'on voit en page d'accueil car les liens sont tous fonctionnel (testé  Un prince a new york 2)..

Je vais installer tes mises à jour te de confirmer que ça marche

**Comment by TmpName** [comment]
Correction pr les serie pr wiflix

**Comment by Che-debarras** [comment]
MERCI à @razorex d'avoir ajouter zustrm.co et j'ai maj les bugs corrigés et changés.

**Comment by sizanic** [comment]
La nouvelle mise à jour de vStream vient de sortir.

Encore merci à toi pour le maintien de cet état des lieux qui nous aide à y voir plus clair.

Pour info, en plus de l'ajout des nouvelles sources et corrections des certaines sources (lorsque cela était possible), cette mise à jour apporte ces nouveautés : 
- **UrlResolver** : compatibilité Matrix
- **TRAKT** : Pagination dans les menus
- **TMDB** : Affichage d'un QR Code pour activer la clef API
- **Recherche sous Matrix** : Insensibilité à la casse des lettres

**Comment by Che-debarras** [comment]
@sizanic pas de souci, j'avais lu sur un poste que tu a ecris qu'une maj majeur aller venir alors je me suis dis un checkup serait opportun.
Pas hésiter à me solliciter si un état des lieux dois être fait, je serais ravi de le faire.
Je vais vérifier une dernière fois les bugs avec cette version 1.0.0 et je modifierait le 1e post ou je ferait un autre.
Merci à l'équipe pour votre travail et temps.

**Comment by razorex** [comment]
Perso je pense que oui, une fois corrigé supprime le commentaire, nous de notre côté on met un com a la fin pour que tu sache et après tu gère, tu sera le phare qui nous oriente lol....

**Comment by sizanic** [comment]
oui, supprime ce qui est **RÉSOLU**

**Comment by Mokoman30** [comment]
J arrive pas à mettre a jour le 1.0.0 je suis sur kodi 19 il demande le f4m incompatible

**Comment by sizanic** [comment]
Bonjour @Mokoman30 

Malgré le titre de ce sujet, il est plutôt dédié aux problèmes avec les sources exclusivement.
Peux-tu créer un nouveau sujet stp ?

**Comment by Che-debarras** [comment]
> oui, supprime ce qui est **RÉSOLU**

@razorex @sizanic  
C'est plus leger comme ça. Les bugs sont désormais surtout des hosts Hs

**Comment by Che-debarras** [comment]
Edit : frnchstrm.lol est passé sous CF. Les meilleurs sites passent sous CF. Ya vraiment rien qu'on puisse faire?

**Comment by falciatrice10** [comment]
Bonjour
Autre problème : 
Dans extreme download , maintenant en appuyant sur un lien j obtiens des captchas.

**Comment by Che-debarras** [comment]
> Bonjour
> Autre problème :
> Dans extreme download , maintenant en appuyant sur un lien j obtiens des captchas.

Ça toujours été le cas non? Comme w.w.city il faut passez par des captchas.

**Comment by falciatrice10** [comment]
Bonjour
Non il n y avait pas de captchas avant.

**Comment by sizanic** [comment]
Je suis aller directement sur le site et j'ai pu accéder à des liens sans passer par un patcha.
Il faut qu'on vérifie pourquoi nous l'avons ajouté ? 🤔

**Comment by Arias800** [comment]
Il y a toujours eu le captcha et il y est toujours (c'est la version invisible).
Par contre avoir un token Alldebrid permets de le contourner.

**Comment by falciatrice10** [comment]
> Il y a toujours eu le captcha et il y est toujours (c'est la version invisible).
> Par contre avoir un token Alldebrid permets de le contourner.

J avais un compte alldebrid mais il a expiré il y a plus d un an

**Comment by Arias800** [comment]
Ça n'a pas d'importance. Ça fonctionne aussi avec un compte gratuit.

**Comment by falciatrice10** [comment]
> Ça n'a pas d'importance. Ça fonctionne aussi avec un compte gratuit.

Il n y a plus de captcha mais j obtiens :file not found

**Comment by falciatrice10** [comment]
En plus j'ai déjà un abonnement uptobox fonctionnel, donc il va y avoir conflit avec alldebrid, non ?

**Comment by Che-debarras** [comment]
@falciatrice10 
C'est normal le host uptobox et uptostream ne fonctionnent plus sur vstream, je l'ai mis dans la liste à corriger.

**Comment by Che-debarras** [comment]
@Arias800 j'ai testé ta correction pour uptobox et uptostrm mais sur android cela ne fonctionne toujours pas. On a fichier introuvable.

**Comment by Che-debarras** [comment]
Ya un souci assez bizarre concernant les host dood et allow_redirect
Ex J. S. justice ligue se visionne sur ces 2 hosts sur le website mais pas vstream
Alors que d'autres films fonctionnes sous ces 2 hosts ex finding love ou centigrade.
Est du au fair qu'il dure 4heures et ces host ne le supporte pas? Car abcvideo ou uqload evoload lise parfaitement J. S justice ligue

**Comment by falciatrice10** [comment]
Bonsoir 
Il n y  a pas d autres moyen pour regarder les liens uptobox (tout en profitant du compte premium) sous kodi ?
Merci

**Comment by Che-debarras** [comment]
> Bonsoir
> Il n y a pas d autres moyen pour regarder les liens uptobox (tout en profitant du compte premium) sous kodi ?
> Merci

Avec vstream non faut attendre que ce soit résolut
Sinon essaie de trouver un addon de lecture qui les liens une application comme vlx
Ou utilise host direct avec les liens de w.w.city en prenant les liens de mystrm ou vidoza qui sont les même fichiers et de très bon qualité 
Ce sont les mêmes fichiers

**Comment by falciatrice10** [comment]
Vlx ? C'est un addon kodi ?

**Comment by falciatrice10** [comment]
J'ai trouvé un addon **echo player**
Le seul inconvénient est que je dois a chaque fois me connecter à **uptobox.com/pin**  et entrer un code.

**Comment by Che-debarras** [comment]
> Vlx ? C'est un addon kodi ?

Désolé erreur de frappe je parle de VLC ou n'importe quel lecteur de video.
Mais comme je dis ya d'autres sources et d'autres liens
Pourquoi se focaliser sur uptobox?
Faut juste patienter.

**Comment by falciatrice10** [comment]
> > Vlx ? C'est un addon kodi ?
> 
> Désolé erreur de frappe je parle de VLC ou n'importe quel lecteur de video.
> Mais comme je dis ya d'autres sources et d'autres liens
> Pourquoi se focaliser sur uptobox?
> Faut juste patienter.

Bonjour 
C'est parce que j'ai un compte premium

**Comment by Che-debarras** [comment]
@Arias800 j'ai testé ta correction pour Viki sur android et cela ne marcr toujours pas, fichier ntrouvable et mais sur l'addon viki version 0.18.4.10 les liens fonctionnent. Peut-être utiliser la dernière version pour voir où ça cloche?

https://mega.nz/folder/fCA3SYLD#BwCyHxc5EDMixG0FpGpMdA

Ya 1 version pour kodi 18 et une autre pour kodi 19

**Comment by Arias800** [comment]
C'est corrigé dans la beta.

**Comment by Arias800** [comment]
Psteam est aussi corrigé dans la beta.

**Comment by Che-debarras** [comment]
@Arias800 désolé pour viki c'est toujours pas résolu  mais pstream si c'est résolu

**Comment by Che-debarras** [comment]
> Ca marche chez moi car j'utilise Kodi 19, donc faut attendre que quelqu'un le corrigé sous Kodi 18.

Si j'ai compris,  viki et uptostream/box fonctionne sur Kodi 19?
Est ce que d'autres bug de mon premier post fonctionne sur kodi 19?

**Comment by Che-debarras** [comment]
L'addon viki v0.19.4.15 règle le problème des sous-titres pour kodi 19 donc peut-être implanter cette correction à la source Viki?

**Comment by Arias800** [comment]
Les sous-titres de Viki sont corrigé sous Kodi 19, j'avais effectivement pas vérifié si ils s'affichaient ou pas.

**Comment by Che-debarras** [comment]
> Les sous-titres de Viki sont corrigé sous Kodi 19, j'avais effectivement pas vérifié si ils s'affichaient ou pas.

Je vais tester mais pour kodi 18.9 pas moyen de le corriger?

**Comment by Arias800** [comment]
Le problème, c'est qu'il faut que je réinstalle Kodi 18, que j'intervertisse les dossiers de Kodi...
Puisqu'il n'y a pas moyens d'avoir deux version installé en même temps.

**Comment by Che-debarras** [comment]
> Le problème, c'est qu'il faut que je réinstalle Kodi 18, que j'intervertisse les dossiers de Kodi...
> Puisqu'il n'y a pas moyens d'avoir deux version installé en même temps.

Je confirme que ta correction résout le problème pour kodi 19.
Je pense passer à kodi 19  vu que mes addons sont compatibles.

**Comment by sizanic** [comment]
> Le problème, c'est qu'il faut que je réinstalle Kodi 18, que j'intervertisse les dossiers de Kodi...
> Puisqu'il n'y a pas moyens d'avoir deux version installé en même temps.

Sur PC tu peux avoir deux versions, il faut en installer un des deux en version "Portable".
Sur Android ou Autre, un KODI19 et pour une version antérieur : installer NODI ou SPMC ou autre clone.

**Comment by Arias800** [comment]
Oui je viens de découvrir que Kodi a un mode "Portable".

**Comment by Arias800** [comment]
Visiblement les liens Viki ne sont pas correctement supporté sous Kodi 18, car les liens obtenu sont les bons, mais Kodi n'arrive pas à les lires.

**Comment by Che-debarras** [comment]
> Visiblement les liens Viki ne sont pas correctement supporté sous Kodi 18, car les liens obtenu sont les bons, mais Kodi n'arrive pas à les lires.

Sauf que l'addon viki 0.18.4.10 de majide fonctionne sous kodi 18.9 donc je suppose vue que c'est les mêmes liens kodi peut lire ces liens viki en v18.

La version 0.18.4.10 est disponible ici https://mega.nz/folder/fCA3SYLD#BwCyHxc5EDMixG0FpGpMdA

**Comment by Arias800** [comment]
Je viens d'essayer et les liens ne fonctionne pas n'ont plus avec cette addon.

**Comment by Che-debarras** [comment]
> Je viens d'essayer et les liens ne fonctionne pas n'ont plus avec cette addon.

Si l'addon marche aussi bien sur kodi 18 et 19 voici un screenshot
![20210410_161457](https://user-images.githubusercontent.com/44464129/114272957-866b3e80-9a18-11eb-9c08-a88db4196faa.jpg)

Par contre ta dernière mise a jour d'aujourd'hui pour viki ne permet plus d'ouvrir les catégories sur viki en kodi 19

**Comment by Arias800** [comment]
Je réitère ce que j'ai dit, ça ne fonctionne pas chez moi (j'ai réessayés pour être sur).
Et pareil le bug des catégories n'est pas reproduisible chez moi.
Donc je peux pas corrigé.

**Comment by Che-debarras** [comment]
> Je réitère ce que j'ai dit, ça ne fonctionne pas chez moi (j'ai réessayés pour être sur).
> Et pareil le bug des catégories n'est pas reproduisible chez moi.
> Donc je peux pas corrigé.

Ok chez moi l'addon fonctionne en kodi 18 ou 19 et ta correction d'hier fonctionne sur kodi 19 donc je passe sur kodi 19 comme ça le problème est résolu

**Comment by TmpName** [comment]
Pour info je suis sous kodi 18.1 et ca marche pas non plus, mais il y a plein de dependances qui entrent en jeux pour ce type de liens....

**Comment by Che-debarras** [comment]
> Pour info je suis sous kodi 18.1 et ca marche pas non plus, mais il y a plein de dependances qui entrent en jeux pour ce type de liens....

Ok donc je reste en en 18.9 car même si viki fonctionne en kodi 19 (que ce soit la source vstream ou l'addon de Majide) .
Ya le souci des allow direct host direct et uptostrm/box qui ne marche plus sur kodi 19

**Comment by Arias800** [comment]
Uptobox fonctionne, c'est juste leurs api qui fait n'importe quoi donc il n'y a rien n'a corrigé.
J'ai mis un début de correction pour mystrm mais j'ai une erreur 403, ça doit être un problème d'headers.
Je ne sais pas d'où il vient.

**Comment by Che-debarras** [comment]
> Uptobox fonctionne, c'est juste leurs api qui fait n'importe quoi donc il n'y a rien n'a corrigé.
> J'ai mis un début de correction pour mystrm mais j'ai une erreur 403, ça doit être un problème d'headers.
> Je ne sais pas d'où il vient.

J'ai mis à jour et ta correction mystrm fonctionne.

Quant à viki il ne fonctionne pas les sous titres soit il ne s'affiche pas soit il affiche les sous-titres de la video précédente comme si il y avais un decalage dans le chargement des sous-titres

Si tu te bases sur l'addon de Majide il est complètement beugué, visiblement il ne veur plus la corriger sauf pour lui meme.
Sur son addon et la source il manque pas mal de film et serie ex film populaire y'en a que 4 alors qu'il y'en a des dizaines en vostf ou eng.
Finalement faudrait peut-être supprimer ce Viki, il y a une application android

**Comment by Arias800** [comment]
Je ne me base pas sur le code de Majide (par contre la personne qui à ajouter le site a Vstream s'en n'est servi).

Pour ce qui est des sous-titres ce n'est pas un bug. Il faut savoir que, sur le site, les sous-titres sont disponibles même lorsqu'ils ne sont pas 100% terminé (ici ils sont fini a 78%).
![image](https://user-images.githubusercontent.com/24809312/114542678-7d68b000-9c58-11eb-99fe-cdb2c4e32682.png)

Ce que fait l'addon, c'est que lorsque les sous-titres ne sont pas fini, ils les ignorent et ne remplace pas ceux de l'épisode précédent. Et comme les sous-titres sont stockés localement, alors Vstream charge les derniers sous-titres stocké, à savoir ceux de l'épisode précédent.

**Comment by Arias800** [comment]
J'ai mis une nouvelle versions en ligne :
- Si il y a des sous-titres français fini a 100%, alors Vstream les utilises.
- Si il n'y a que les Anglais qui sont fini a 100%, alors Vstream charge les sous-titres Anglais (avec un message qui prévient l'utilisateur).
- Si il n'y a aucun sous-titre, l'utilisateur est prévenu, mais la vidéo reste lisible si il le souhaite.

**Comment by Che-debarras** [comment]
> J'ai mis une nouvelle versions en ligne :
> 
> * Si il y a des sous-titres français fini a 100%, alors Vstream les utilises.
> * Si il n'y a que les Anglais qui sont fini a 100%, alors Vstream charge les sous-titres Anglais (avec un message qui prévient l'utilisateur).
> * Si il n'y a aucun sous-titre, l'utilisateur est prévenu, mais la vidéo reste lisible si il le souhaite.

Excellent les avertissement,  je valide , j'achète lol.
J'ai 2 questions: 
Pourquoi il n'y a que 4 films dqns films populaires alors que viki affichent des dizaines
Pourquoi le film fate of swordman par exemple refuse de se lancer que ce soit avec ou sans sous-titres (il est pourtant bien sous-titré en francais)

**Comment by Arias800** [comment]
C'est corrigé pour fate of swordman.
Pour ce qui est des tendance ça vient du fait que cette partie de l'api n'est plus entretenu, faudrait que je cherche si il y a un équivalent.

**Comment by Che-debarras** [comment]
> C'est corrigé pour fate of swordman.
> Pour ce qui est des tendance ça vient du fait que cette partie de l'api n'est plus entretenu, faudrait que je cherche si il y a un équivalent.

Oui j'ai parfois une alerte sur kodi concernant l'api

**Comment by Che-debarras** [comment]
**Pour  résumer les bugs restants sont :** 
+ Lien direct HS (netu et GoUlmntd just pour infos)
+ Viki (dossiers film vides et dossiers épisodes ne s'ouvrent pas)
+ Host non supporté (saruch, ninjastem,google, allvid)
+ kaydo (catégories ne s'ouvrent pas)
+ cloudfare qu'on ne peut rien faire (ZT TIREXO DDL VOIRFLM)

**Comment by Che-debarras** [comment]
Uptobx/strm ne fonctionne plus sur kodi 18 mais sur kodi 19 ok ex mortal kombat sur zustream , ok sur kodi 19 , hs sur kodi 18.9

**Comment by TmpName** [comment]
Dans les sites HS (du moins chez moi)
- Voir film
- sokrostrm
- cinemEy

**Comment by sizanic** [comment]
Le site "4k streamz" n'a pas l'air de répondre.
Changement d'adresse 🤔

**Comment by TmpName** [comment]
Ok bon autant pour moi, VF est sous cloudflare et les 2 autres fonctionnent aujourdhui ....

**Comment by Che-debarras** [comment]
Y a un souci danq la recherche, j'ai lancé un titre en tant que série et il s'arrête à la 33e source comme si il n'avait pas accès au 34ème source et on est obligé de forcer l'arrêt de kodi pour revenir sur le menu de kodi et vstream

**Comment by Arias800** [comment]
J'ai une petite idée de ce qui génère le bug, je m'en occupe.

**Comment by Che-debarras** [comment]
Frenchstrm.lol : dossiers qui ne s'ouvrent avec message d'exécuter flaresolverr
Mais ce soir, il n'y a plus cette notification et les dossiers sont vides

**Comment by sizanic** [comment]
o1 serie streaming 
Cette source ne fonctionne plus alors que les liens sont accessibles sur le site.
A voir 🤔

**Comment by sizanic** [comment]
otaku attitude, les catégories sont vides.
Je n'ai pas le temps de m'en occuper, j'informe juste de ceux que je repère.

**Comment by sizanic** [comment]
Pluto TV
Les sous-catégories de la VOD ne sont pas accessibles.

**Comment by yodidon** [comment]
Je regarde si je peux réparer

**Comment by TmpName** [comment]
o1 serie streaming , devrait remarcher, pas fait les details.

**Comment by yodidon** [comment]
pour pluto tv, j'ai corrigé mais pas sur que la méthode soit super (l'appel addTv ne recevait pas d'url et donc ne marchait pas

**Comment by sizanic** [comment]
> pour pluto tv, j'ai corrigé mais pas sur que la méthode soit super (l'appel addTv ne recevait pas d'url et donc ne marchait pas)

J'ai terminé un truc propre qui : 
- gère l'enchainement des épisodes
- permet la mise en marque-pages


> o1 serie streaming , devrait remarcher, pas fait les details.

OK pour o1 serie streaming

> Otaku attitude devrait remarcher

Pas chez moi.
Failed: Peer certificate cannot be authenticated with given CA certificates(60)
