### ISSUE TITLE
Recherche visuelle - Affichage des genres

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3256]
Bonjour,

Je viens de remarqur un bug dans l'affichage des genres en passant par la recherche visuelle. Pour chacun d'eux, il y a un 'b' inscrit devant. 

Par exemple, le genre 'Action' devient: b'Action' (et lorsqu'il y a un caractère spécial... voir impression d'écran)

![Screenshot_20210310-100515](https://user-images.githubusercontent.com/49578130/110651212-3edb6380-8189-11eb-8ec1-1c2f690c1440.png)

Je suis sous Kodi Matrix, Nvidia Shield avec la dernière bêta de vStream

Merci :)

**Comment by yodidon** [comment]
Corrigé sur la bêta
