### ISSUE TITLE
Problème site 9docu

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#3257]
Bonjour à toutes et tous,

Le site 9docu est à nouveau inaccessible: aucunes informations

Le site internet fonctionne

Bonne soirée

**Comment by yodidon** [comment]
Ok je regarde ça si je vois quelque chose merci

**Comment by yodidon** [comment]
Malheureusement protection cloudfare sur le site :)

**Comment by Papounet58** [comment]
Merci d'avoir regardé.
Étant résident Belge cela devient difficile de voir des Replay de chaines Françaises.
J'espère que cela s'arrangera un jour.
Merci pour votre travail.
