### ISSUE TITLE
Recherche visuelle

### ISSUE THREAD

**Issue by philac28230** [Kodi-vStream/venom-xbmc-addons#3261]
Bonjour, 
Depuis le passage à Kodi 19, seulement deux pages sur la recherche visuelle ! 
Cordialement

**Votre system**
 - OS:  Android
-  Appareil Tv e & Gsm
 - Version Kodi 19
- Version Vstream 1.0

**Comment by TmpName** [comment]
La je pense que quelques log seraient utiles .

**Comment by philac28230** [comment]
Bonsoir,

De quels log parlez vous ?

Cordialement

**Comment by sizanic** [comment]
UP

**Comment by Arias800** [comment]
Corrigé dans la beta.

**Comment by philac28230** [comment]
Ok, thanks. Possible d'avoir la beta ?

**Comment by sizanic** [comment]
La beta est disponible en bas de cette page : https://github.com/Kodi-vStream/venom-xbmc-addons

(ne pas tenir compte du warning)

**Comment by philac28230** [comment]
C'est bon, je viens de télécharger la béta !

Bonne journée
