### ISSUE TITLE
Absence option « Marquer vu / non vu »

### ISSUE THREAD

**Issue by Rygo92** [Kodi-vStream/venom-xbmc-addons#3262]
Bonjour et déjà merci pour la dernière version de vStream. J'ai déjà signalé le bug sur le discord mais il est peut être plus pratique pour vous d'avoir une trace ici. 

Je n'ai plus l'option "marquer comme vu / non vu" dans le menu contextuel sur le dossier de la saison d'une série ou sur le dossier de l'épisode. Cette option est par contre bien présente quand je suis sur le lien direct.

Là par exemple je viens de finir les 10 épisodes d'une saison qui sont marqués automatiquement comme vu, mais la saison ne s'est pas marqué comme vu et je ne peux pas le faire manuellement. Pas pratique pour savoir où on en est. A savoir que je n'utilise que pastebin, je ne sais pas si c'est aussi le cas sur les autres sources. 

En pièce jointe, une photo du menu contextuel quand on est sur une saison.

✌️

![image](https://user-images.githubusercontent.com/77703379/111036259-a5c57a80-841e-11eb-8092-c2a8bc89ee13.jpeg)

**Comment by Che-debarras** [comment]
Ca dépend des sources.
Il faut que dossier soit le dossier contenant les liens pour pouvoir mettre vu ou non vu.
Si entre le dossier et le lien ya un autre sous dossier entre les 2 c'est ce sous dossier qui sera marqué vu/non vu pas le dossier.
J'ai le même souci avec une autre source et c'est comme ça que je l'ai interprété que seul le dossier contenant les liens peuvent être marqués.
Après faut aussi voir en redémarrant kodi ou en quittant la source car la des fois ça affichent vu et pas directement en cliquant la fonction.

Je sais pas si c'est un bug mais vu que ce marquage marche sur toutes les autres sources je pense que c'est lié au site.

**Comment by Rygo92** [comment]
Si je mets ce message aujourd'hui c'est que c'était valable avec l'ancienne version et ce n'est plus valable avec la mise à jour d'hier. Je sais qu'avant il fallait sortir des dossiers et revenir pour que les "vus" apparaissent mais aujourd'hui nous ne pouvons plus le faire. Marquer la saison entière était possible sur le dossier de la saison et c'était très pratique sur les séries avec de nombreuses saisons pour savoir exactement où l'on en est.

**Comment by sizanic** [comment]
Je pense qu'il  y a vraiment une régression.
Ce qui ne serait pas étonnant vu les dernières modifications qui ont été faites, certaines pourraient avoir eue un impact.
On va regarder.

**Comment by razorex** [comment]
addMovies, addTV, addLink etc ne donne pas les mêmes options en fonction du skin de kodi.
sa me prend aussi la tête de mon côté car chacun fait des modifs pour que sa passe chez lui..

**Comment by yodidon** [comment]
> addMovies, addTV, addLink etc ne donne pas les mêmes options en fonction du skin de kodi.
> sa me prend aussi la tête de mon côté car chacun fait des modifs pour que sa passe chez lui..
> et si tu active les meta ben c'est pire, non pas pire car tu n'utilise plus les info collecté par vstream (pas toutes)
> Malheureusement ce n'est pas de la faute de vstream.

Comment ça ? Je comprend pas bien, c’est pourtant plutôt suivi non ?

**Comment by sizanic** [comment]
> addMovies, addTV, addLink etc ne donne pas les mêmes options en fonction du skin de kodi.

Normalement non, quelque soit le "add" ça ne dépend pas du skin.
Les raccourcis que vStream veut mettre doivent toujours apparaître, le skin ne prend pas le dessus.

**Comment by Arias800** [comment]
En faite, c'est pas vraiment un bug.
Le menu "Marqué Vu" apparait si :
- Il y a des meta (1,2,3,4)
- Si sCat est égal a 5.

Hors addEpisode n'a pas de meta et a un sCat égal a 2. Donc il ne s'affiche pas, c'est normal.

Pour modifier ça il y a plusieurs possibilité :
- Mettre sCat a 5 pour addEpisode.
- Afficher le "Marqué vu" quand sCat est égal a 2 ou 5.
- Rajouter des metas pour les épisodes, mais c'est l'option la plus complexe.

**Comment by sizanic** [comment]
J'avais apporté les dernieres modifs sur ce sujet, je vais regarder de nouveau pour apporter la meilleure  modif.

Je m'en occupe.

**Comment by sizanic** [comment]
il y a une autre possibilité.
Ne pas tester le meta, mais juste : 
`if cGui.CONTENT in ('movies', 'tvshows', 'episodes'):`


c'était comme cela dans une version précédente mais cela posait un autre problème.
Je suis en train de regarder.

**Comment by sizanic** [comment]
J'ai apporté une correction.
