### ISSUE TITLE
Token alldebrid (fichier source ? ) 

### ISSUE THREAD

**Issue by yamoky** [Kodi-vStream/venom-xbmc-addons#3263]
Salut,
Comme vous le savez tous il est impossible (perso je n'ai jamais réussi) à faire un copier coller sur Android.
Donc j'aimerais accéder au fichier source de vstream dans kodi (Android) pour mettre le token de alldebrid vue que urlresolver est hs.

Si vous savez ou mettre ce token, n'hésitez pas, je pense que vous allez aider pas mal de monde.

Merci beaucoup par avance.

**Comment by sizanic** [comment]
Salut,

Le token se renseigne dans les paramètres de vStream.
Pas dans son code 🤔 

![image](https://user-images.githubusercontent.com/47307622/111052009-9d3d6600-8457-11eb-9fe7-80c23bd49257.png)

**Comment by yamoky** [comment]
> Salut,
> 
> Le token se renseigne dans les paramètres de vStream.
> Pas dans son code 🤔
> 
> ![image](https://user-images.githubusercontent.com/47307622/111052009-9d3d6600-8457-11eb-9fe7-80c23bd49257.png)

Salut, 
Merci pour ce renseignement. Mais malheureusement je ne veux pas passer par kodi directement. 

Mais par le fichier du code source de kodi.

**Comment by sizanic** [comment]
Je viens de comprendre ce que tu recherches.
Ce n'est pas le fichier du code source, mais le fichier des propriétés qui contient ce code une fois qu'on l'a renseigné.

C'est dangereux de modifier directement ce fichier à la main, tu risque de le corrompre et de perdre tous tes paramètres.

Après ce message d'avertissement, à toi de voir, c'est celui-ci : 
\Android\data\org.xbmc.kodi\files\.kodi\userdata\addon_data\plugin.video.vstream\settings.xml

Le paramètre à modifier : 
<setting id="hoster_alldebrid_token">XXXX</setting>

=> tu dois utiliser un navigateur de fichiers qui permet de voir les fichier cachés.
=> A tes risques et périls !

**Comment by yamoky** [comment]
> Je viens de comprendre ce que tu recherches.
> Ce n'est pas le fichier du code source, mais le fichier des propriétés qui contient ce code une fois qu'on l'a renseigné.
> 
> C'est dangereux de modifier directement ce fichier à la main, tu risque de le corrompre et de perdre tous tes paramètres.
> 
> Après ce message d'avertissement, à toi de voir, c'est celui-ci :
> \Android\data\org.xbmc.kodi\files.kodi\userdata\addon_data\plugin.video.vstream\settings.xml
> 
> Le paramètre à modifier :
> XXXX
> 
> => tu dois utiliser un navigateur de fichiers qui permet de voir les fichier cachés.
> => A tes risques et périls !

OK merci beaucoup.
Je vais faire attention, j'ai cloner le dossier de vstream. (au cas où je fais de la merde 😅)

**Comment by yamoky** [comment]
![Screenshot_20210315_150649](https://user-images.githubusercontent.com/23269347/111166123-18aa2f00-85a0-11eb-9cc6-63eaacdcaf24.jpg)
Je viens de voir comment il fallait le mettre
Merci beaucoup encore 👌

**Comment by yamoky** [comment]
@sizanic
Si tu as aussi l'information pour mettre le code http média 😅
Car je de connais pas le code à mettre 🙏🏻😅
![Screenshot_20210315_151658](https://user-images.githubusercontent.com/23269347/111167571-8d319d80-85a1-11eb-9b97-f9b6e680ec46.jpg)

**Comment by sizanic** [comment]
C'est l'URL vers ton propre contenu personnel que tu héberges sur allDebrid.

Est-ce que tu héberges du contenu auquel tu voudrais accéder ?

**Comment by yamoky** [comment]
En gros, tu peux sauvegarder sur alldebrid des liens de film par exemple et y avoir accès n'importe où.

Je te renvoie vers ce lien qui explique tout.
https://alldebrid.com/help/fr/Outils%20Alldebrid/media-folder

**Comment by sizanic** [comment]
Je sais bien que ça sert à avoir accès à tes liens, c'est pour cela que je te demande : 
Est-ce que tu as du contenu sur ton compte alldebrid auquel tu voudrais accéder ?

Parce que sinon, tu n'as pas besoin de renseigner ce paramètre.

Si oui, c'est la même url que dans cette doc. (https://myfiles.alldebrid... )

**Comment by alKODIque** [comment]
> Salut,
> Comme vous le savez tous il est impossible (perso je n'ai jamais réussi) à faire un copier coller sur Android.
> Donc j'aimerais accéder au fichier source de vstream dans kodi (Android) pour mettre le token de alldebrid vue que urlresolver est hs.
> 
> Si vous savez ou mettre ce token, n'hésitez pas, je pense que vous allez aider pas mal de monde.
> 
> Merci beaucoup par avance.

@yamoky 
Pourtant, il est très facile de copier-coler des liens (ou n'importe quel texte) via Android. Il ne te suffit que d'utiliser ton cellulaire / iPhone pour y arriver.

Pour Android: l'apk Yatse est tout simplement génial.
Pour iPhone: l'app Sybu est pour moi la meilleure.
Sinon, l'app remote officielle de Kodi s'appele Kore et est disponible sur chaque OS

Une fois l'app Pairée a ton installation Kodi, rend toi sur le lien a copier-coler sur le navigateur de ton cell, comme tu le fait habituellement, copie-le et colle-le ensuite a l'aide du clavier virtuel de ton application (Yatse, Sybu ou Kore)

Puisque je possède un iPhone, j'utilise Sybu est c'est vraiment très utile surtout lorsqu'il faut copier-coler des no. de clé API personnels ;)

![th-28923628477-496x1074](https://user-images.githubusercontent.com/49578130/111348760-e27bb680-8656-11eb-8bfd-04f53c93ad56.jpg)
![2021-03-16 12-53-00](https://user-images.githubusercontent.com/49578130/111348805-ee677880-8656-11eb-815b-66be7a52163f.png)

**Comment by yamoky** [comment]
J'ai yaste (tout leurs addon) mais la c'est pas pour gérer une autre plate-forme (pc, Android tv,...)

De base tu ne peux pas faire de copier coller sur Android car si tu reste appuyer ça fait un back.
Et aussi, sur le clavier virtuel de kodi, il manque des symboles et le point pour faire un ".com" par exemple.

Et c'est aussi pour pré-enregistrés le fichier pour éviter devoir refaire la manipulation. 😉 Gains de temps

**Comment by alKODIque** [comment]
@yamoky 

Je me souviens pourtant que je n'avais pas de problème sur mon cell / tablette android en utilisant kore (sur le même appareil) avec l'écran de la télécommande "send to kodi" 
![15B7553B-8BDC-4264-BDA3-05F8DACC5B21](https://user-images.githubusercontent.com/49578130/111351701-d5ac9200-8659-11eb-8ed5-40dd68fa362e.jpeg)

**Comment by yamoky** [comment]
> @yamoky 
> 
> Je me souviens pourtant que je n'avais pas de problème sur mon cell / tablette android en utilisant kore (sur le même appareil) avec l'écran de la télécommande "send to kodi" 
> ![15B7553B-8BDC-4264-BDA3-05F8DACC5B21](https://user-images.githubusercontent.com/49578130/111351701-d5ac9200-8659-11eb-8ed5-40dd68fa362e.jpeg)
> 

![Screenshot_20210316_181942_org.xbmc.kodi.jpg](https://user-images.githubusercontent.com/23269347/111352204-3c46a580-8684-11eb-994c-92d3f4cfb5ed.jpg)![Screenshot_20210316_181936_org.xbmc.kodi.jpg](https://user-images.githubusercontent.com/23269347/111352210-3d77d280-8684-11eb-8ad6-3146e4ffa003.jpg)

Essaye d'écrire une adresse internet tu vas vite avoir un problème, je penses

**Comment by alKODIque** [comment]
tu n'as pas le popup "send text to kodi" qui apparaît?

**Comment by alKODIque** [comment]
une mauvaise configuration probablement...

**Comment by alKODIque** [comment]
Une fois que la télécommande fonctionne sur ton cell, tu peux pourtant l'utiliser pour coller du texte sur Kodi:

- Copie le texte que vous souhaitez coller
Sur Kodi

- clique sur le champ que tu souhaite remplir: Une fenêtre contextuelle est supposé apparaître
- Cliquez sur le champ "Texte à envoyer": Un bouton "Coller" est supposé apparaître
- Clique sur le bouton et le texte sera collé
- Cliquez sur Envoyer et le texte apparaîtra sur Kodi.

**Comment by yamoky** [comment]
Merci beaucoup dsl je pensais t'avoir répondu 😅

Maintenant vas falloir que je regarde ce que je dois faire pour réussir à faire la maj ! 

[Screenshot_20210331_010840_org.xbmc.kodi.jpg](https://user-images.githubusercontent.com/23269347/113069017-c122da80-91bf-11eb-9fcc-a33ea2042259.jpg)![Screenshot_20210331_010849_org.xbmc.kodi.jpg](https://user-images.githubusercontent.com/23269347/113069022-c4b66180-91bf-11eb-9f70-045955e9a3b5.jpg)
