### ISSUE TITLE
probléme erreur suppression bdd

### ISSUE THREAD

**Issue by BORDENEUVE** [Kodi-vStream/venom-xbmc-addons#3264]
bonjour
j utilise vstream la dernière version avec comme os windows 10, le problème  que j ai quand je veut vider le cache de vstream apres avoir valider j ai un message d erreur qui m indique (erreur suppression BDD) ,alors que sur windows 8.1 je n ai pas ce message
merci de votre réponse

**Comment by sizanic** [comment]
Bonjour,
Il n'y a pas de raison.

Il nous faudrait le fichier 'kodi.log' pour analyse du problème.

**Comment by yodidon** [comment]
Je n’ai pas réussi à reproduire  le problème sur mon w10

**Comment by BORDENEUVE** [comment]
voila quelque info
windows 10 1909(kernel windows nt 10.018362.1440)
cpu amd e1-6010 apu witch amd radeon r2 graphics
kodi version 19.0(19.0.0)
git 2010218-f44dfdf67
compilé le 2012-02-18
 
remarque j ai un ami qui rencontre le meme probleme avec comme consequence une lecture impossible des chaines de television
 
 
 
 
> Message du 14/03/21 20:28> De : "yodidon" > A : "Kodi-vStream/venom-xbmc-addons" > Copie à : "BORDENEUVE" , "Author" > Objet : Re: [Kodi-vStream/venom-xbmc-addons] probléme erreur suppression bdd (#3264)> >
>
> Je n’ai pas réussi à reproduire le problème sur mon w10
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3264#issuecomment-798965020", "url": "https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3264#issuecomment-798965020", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by sizanic** [comment]
Je ne le reproduis pas non plus avec mon Windows 10.
Je ne pense pas que ce soit un paramètre qui rentre en compte.
C'est juste cette installation qui a un problème.
Sans le fichier de log, on ne pourra rien faire.

> le meme probleme avec comme consequence une lecture impossible des chaines de television

Les seules chaines de télé dans vStream sont les liens iptv, ou les sources ChannelStream ou Streamonsport.
Mais dans tout les cas, aucuns n'utilisent le cache de vStream.

* Pourquoi essayes-tu de vider le cache de vStream ?
* Sais-tu au moins à quoi cela correspond ?


=> Quel problème as-tu à la base qui t'as donné l'idée de vider le cache ?


Je ne pense même pas que vider le cache va régler ton problème d'origine 🤔

**Comment by BORDENEUVE** [comment]
merci pour votre réponse  pouvais vous m indiquer la procédure pour faire une copie du fichier log
apres avoir choisit la chaine de télevision (iptv) la connection ce fait, la video commence et apres quelques secondes l image se fige ,méme dans certain cas la video ne demarre pas
je pensait que dans le cache il y avait un peu de video de stocké 
 
 
 
> Message du 14/03/21 21:33> De : "sizanic" > A : "Kodi-vStream/venom-xbmc-addons" > Copie à : "BORDENEUVE" , "Author" > Objet : Re: [Kodi-vStream/venom-xbmc-addons] probléme erreur suppression bdd (#3264)> >
>
> Je ne le reproduis pas non plus avec mon Windows 10.> Je ne pense pas que ce soit un paramètre qui rentre en compte.> C'est juste cette installation qui a un problème.> Sans le fichier de log, on ne pourra rien faire.

> le meme probleme avec comme consequence une lecture impossible des chaines de television

> Les seules chaines de télé dans vStream sont les liens iptv, ou les sources ChannelStream ou Streamonsport.> Mais dans tout les cas, aucuns n'utilisent le cache de vStream.

Pourquoi essayes-tu de vider le cache de vStream ?
Sais-tu au moins à quoi cela correspond ?

> => Quel problème as-tu à la base qui t'as donné l'idée de vider le cache ?
> Je ne pense même pas que vider le cache va régler ton problème d'origine 🤔
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3264#issuecomment-798974788", "url": "https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3264#issuecomment-798974788", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by sizanic** [comment]
Le cache de vStream n'est pas du tout un cache vidéo.
C'est kodi qui s'occupe de lire la vidéo et qui gère son cache.

Ce que fait le cache de vStream , c'est bien écrit dans la description : 
![image](https://user-images.githubusercontent.com/47307622/111088354-1657be80-8527-11eb-8cfe-e7312b4a5626.png)


**Vide le cache des métadonnées.**
donc ça supprime seulement les métadonnées : images des pochettes de films, et la description des films.
