### ISSUE TITLE
Kodi matrix

### ISSUE THREAD

**Issue by MisuIancu** [Kodi-vStream/venom-xbmc-addons#3265]
Bonjour,

Je suis passé de Leia à Matrix, aucun problème pour le vStream. Mais, j'ai de la misère avec le update à la version 1.0.0, plusieurs extensions introuvables.

Y a-t-il une solution?

Merci

**Comment by alKODIque** [comment]
@MisuIancu  
Tu fais sans doute référence au message indiquant les dépendances facultatives pouvant être installées par vStream. Ces dernières sont utilisables avec Kodi Leia seulement et non par Matrix. Tu n'as pas a ''cliquer'' sur ces dites dépendances. Il ne faut pas t'en préoccuper et tout se passera bien pour toi.

![f4mtuto](https://user-images.githubusercontent.com/49578130/111342425-d5f45f80-8650-11eb-9047-3c2786c183de.png)

**Comment by MisuIancu** [comment]
C'est exactement ça que je fais, mais le update ne se fait pas. Il y a un message :the dependency om xbmc.python version 2.1.0 coul not be satisfied. L'addon fonctionne mais c'est l'ancienne version  0.8.06 de memoire.

Merci.

**Comment by Leefax** [comment]
Hello à tous,  

De mon côté, maj impossible vers la 1.0.0 sur matrix. 
Les 2 erreurs lors de l'installation :
- "La dépendance de xmbc python version 2.1.0 n'a pas pu être satisfaite"
-F4m proxy qui a été pourtant désinstallé avec la maj :
" l'extension n'est pas compatible avec cette version de kodi" //peut être juste un message d'info ? 

Désinstall /Ré-install Vstream, en vain. 
Merci du coup de main 😊

**Comment by yodidon** [comment]
as tu supprimé manuellement les dossiers des addon qui te pose problèmes ?

**Comment by Leefax** [comment]
Je suis sur Mibox non root. Je cherche une alternative..

**Comment by MisuIancu** [comment]
Je vois qu’il y a bien du monde avec le même problème. On fait quoi? On retourne à Leia?

**Comment by yodidon** [comment]
Je suis sur qu’il y a une solution plus pérenne

**Comment by Leefax** [comment]
Ne desinstallez pas Vstream. Impossible de Ré-install, même en version antérieure.
J'ai les mêmes erreurs citées plus haut.
Je vais tenter de réinstaller Matrix.

**Comment by Arias800** [comment]
F4m proxy a été supprimé. Le problème ne se produit donc plus.
