### ISSUE TITLE
Base de donnée VSTREAM vs profiles

### ISSUE THREAD

**Issue by Rick407** [Kodi-vStream/venom-xbmc-addons#3266]
Bonjour,

J'ai remarqué un petit truc qui pourrait être utile pour ceux ayant plusieurs profiles.
Lorsque l'on crée un profile (pour avoir ses propres marque-page et historique), la base de donnée est unique est se crée sous le userdata de master profile même si on est dans un profile autre (exemple profile Rick).
Après lecture du fichier db.py, c'est normal car la BDD est créee en dure avec le chemin du userdata du master profile.

Afin de bénéficier de ses propres marques page, historiques etc. de plusieurs utilisateurs différents qui ont chacun leur profile, il serait bien de créer la base de donnée dans le userdata du profile lancé ou dans les parametres de kodi, de choisir l'emplacement de la base de données (encore mieux).

Ainsi, au même titre que certains addon (ex Net... ou Pri...), chacun retrouverait ses marks, historiques, skin.

Merci pour votre contribution.

Rick

**Comment by sizanic** [comment]
Remarque intéressante en effet.
On note pour regarder ce qu'on peut faire.

(a moins qu'une analyse précédente ait déjà eue lieu et qu'un autre développeur puisse te répondre).

**Comment by Rick407** [comment]
Bonjour,

J'ai trouvé comment faire aussi je partage mes modifications au cas ou certains seraient intéressés :)

J'ai modifié le fichier db.py comme suit:
class cDb:
    #ADDON = addon()
    # important seul xbmcvfs peux lire le special
    #DB = 'special://home/userdata/addon_data/plugin.video.vstream/vstream.db'

    #try:
        #REALDB = VSPath(DB).decode('utf-8')
    #except AttributeError:
        #REALDB = VSPath(DB)
        
    #debut test mise en place BDD dans le profile
    ADDON = addon()
    DB = ADDON.getSetting('BDD_folder')
    try:
        REALDB = VSPath(DB).decode('utf-8')
    except AttributeError:
        REALDB = VSPath(DB)
    #fin test mise en place BDD dans le profile

Ensuite, j'ai modifié le fichier settings.xml (sous resources) en rajoutant une ligne au niveau librairie:
<setting id="BDD_folder" enable="True" type="file" label="BDD" default="special://userdata/profiles/Pat/addon_data/plugin.video.vstream/vstream.db"/>

Ainsi, chaque personne ayant un profile créé, peut avoir ses propres marque pages, historique, favoris etc. Un peu à la manière Net... ou PRi...
Le tout avec avec un habillage Titan Bingie... Le top.

Bonne soirée.

Rick

**Comment by Rick407** [comment]
<setting id="BDD_folder" enable="True" type="file" label="BDD" default="special://userdata/profiles/Pat/addon_data/plugin.video.vstream/vstream.db"/>
La ligne dans le settings.xml

**Comment by sizanic** [comment]
Merci pour ce travail.
On va regarder pour l'automatiser.
Car pour l'instant avec ta solution, il faut venir modifier à la main le fichier settings à chaque nouvelle création de profil.

Et encore, je n'ai pas tout compris, car il n'y a qu'un seul fichier settings, donc qu'un seul paramètre 🤔

**Comment by Rick407** [comment]
Quand on modifie les paramètres de vstream sur librairie avec un nouveau profil comme chemin automatiquement il crée un fichier settings.xml dans le userdata du profil.Ainsi chaque profil a son propre fichier de paramètres qui est créé automatiquement comme pour le choix des sources.En fait chaque utilisateurs différent donne le chemin où trouver sa bdd ds les paramètres.On ne le fait qu'une seule fois par profil ce qui est bien si on veut déplacer sa bdd sur un NAS par exemple et ainsi pouvoir y accéder depuis un tel, tablette, ordi ou TV Le 17 mars 2021 22:27, sizanic ***@***.***> a écrit :

Merci pour ce travail.

On va regarder pour l'automatiser.

Car pour l'instant avec ta solution, il faut venir modifier à la main le fichier settings à chaque nouvelle création de profil.

Et encore, je n'ai pas tout compris, car il n'y a qu'un seul fichier settings, donc qu'un seul paramètre 🤔

**Comment by Rick407** [comment]
Je ferai un print screen la prochaine fois pour montrer.Le 17 mars 2021 23:03, Patrick Lachaise ***@***.***> a écrit :Quand on modifie les paramètres de vstream sur librairie avec un nouveau profil comme chemin automatiquement il crée un fichier settings.xml dans le userdata du profil.Ainsi chaque profil a son propre fichier de paramètres qui est créé automatiquement comme pour le choix des sources.En fait chaque utilisateurs différent donne le chemin où trouver sa bdd ds les paramètres.On ne le fait qu'une seule fois par profil ce qui est bien si on veut déplacer sa bdd sur un NAS par exemple et ainsi pouvoir y accéder depuis un tel, tablette, ordi ou TV Le 17 mars 2021 22:27, sizanic ***@***.***> a écrit :

Merci pour ce travail.

On va regarder pour l'automatiser.

Car pour l'instant avec ta solution, il faut venir modifier à la main le fichier settings à chaque nouvelle création de profil.

Et encore, je n'ai pas tout compris, car il n'y a qu'un seul fichier settings, donc qu'un seul paramètre 🤔

**Comment by Rick407** [comment]
Avec une image c'est mieux
![parmvstream](https://user-images.githubusercontent.com/80746871/111527904-e3593900-8779-11eb-96b2-adf4133925c9.JPG)
Il suffit de rentrer le chemin de la BDD et automatiquement, le fichier settings.xml du userdata est mis à jour avec le lien vers la BDD du profil.
Ainsi, la BDD, si elle est mise sur un NAS par exemple, peut être accédée depuis n'importe quel moyen (téléphone, tablette, pc, tv) et mise à jour.
C'est le même principe que la sélection des sources.

**Comment by osmoze06** [comment]
Bonjour, cette demande est très intéressante.
Pouvons-nous l'intégrer à une prochaine update ?

**Comment by osmoze06** [comment]
Le bu étant de pouvoir modifier le chemin d'accès de la DB vstream afin de la déplacer sur un disque réseau. Dans le but de pouvoir syncroniser entre plusieurs Kodi..

**Comment by Arias800** [comment]
Normalement ça fonctionne dans la bêta.
Tout est automatique, voila un exemple :

Profile de base :
![image](https://user-images.githubusercontent.com/24809312/117178424-4c504b00-add2-11eb-8edf-4d32b4ad1609.png)

Profile de test :
![image](https://user-images.githubusercontent.com/24809312/117178690-9cc7a880-add2-11eb-8b47-5d9ab5c51089.png)

**Comment by osmoze06** [comment]
On peut modifier le chemin de la bd Vstream dans la beta car je trouve pas :

**Comment by Arias800** [comment]
Je réponds à la demande initiale, toi, c'est totalement autre chose. Donc créer une issue différente s'il te plait, comme ça les choses sont bien ranger.

**Comment by sizanic** [comment]
> On peut modifier le chemin de la bd Vstream dans la beta car je trouve pas :
> 
> ![image](https://user-images.githubusercontent.com/33359510/117179470-6d656b80-add3-11eb-82e2-00413aafbb11.png)

Non. Ce qui a été fait c'est une gestion native des profils, pas avec du paramétrage de vStream.

C'est pour ça que c'est différent et que ça ne peut pas gérer le réseau.
Et qu'il te faut faire une autre demande.

**Comment by osmoze06** [comment]
Merci pour vos réponses. J'ouvre une issue différentes.
