### ISSUE TITLE
Kodi Matrix 19 vstream

### ISSUE THREAD

**Issue by Peur** [Kodi-vStream/venom-xbmc-addons#3267]
Bonsoir, 

Depuis l'installation automatique de kodi matrix 19 par google Play, je n'arrive plus du tout a faire fonctionner vstream 10.

Lorsque je veux voir un film j'ai le message '' Vstream Erreur File not found " 
Lorsque j'utilise mon compte premium 1fichier il dit la même chose.

Par moment, j'ai le message "PLAYBACK FAILED, One or more items failed to play."

Kodi installé sur ma tv Android et sur mon smartphone Samsung... Même problème.

Lors de la réinstallation/installation de vstream 1.0.0 ou la version antérieur, j'ai aussi le message suivant:
- Script.module.urlsolver Not Available
- Script.video.f4mproxy Not Available
- Script.module.dnspython Not Available
- Script.module.selenium Not Available
- 

Pouvez vous m'éclairer ?

Merci d'avance

Fred

**Comment by PanameFR** [comment]
Salut,

Oui, pour le moment Vstream a out. Le passage a kodi 19 a cassé pas mal de chose. Uptobox et 1fichier sont pour le moment inaccessible via Vstream. Pour Uptobox, je peux seulement voir les fichiers mais non les lire.
Faut attendre des mises à jour.

**Comment by Peur** [comment]
Ha ok, c'est ce que j'avais compris aussi. Mais j'ai vu pas mal de personne sur internet qui parlait que ca fonctionnait. Alors j'ai tenté pendant .... quelques heures ^^

Donc faut reprendre la version de Leia si je comprends bien en attendant ?

**Comment by alKODIque** [comment]
Non, vStream n'est pas "out" dutout!! il fonctionne mieux que jamais sous Matrix. aucun problème de lecture avec uptobox non plus.

Ceux pour qui ça ne fonctionne pas, c'est qu'ils avaient des addons sous Leia non compatibles avec Matrix lorsqu'ils ont mis à jour .. ceci a causé des problèmes de compatibilité qui affecte kodi en général.

Mais il est faux de dire que vStream est out. Ce n'est pas dutout le cas.

**Comment by Peur** [comment]
Hello alKODIque,

Concernant la version sur ma Tv, j'ai totalement désinstallé kodi pour réinstaller après.
Concernant mon mobile samsung, il n'a jamais eu kodi sauf avant hier la version Matrix.

Alors je ne comprends plus lol

**Comment by alKODIque** [comment]
Tu dois installer le dépôt de vStream avant d'installer l'addon.. c'est peut-être pour cette raison que ça ne fonctionne pas pour toi. Essaie de suivre ce tuto, il n'y a aucune raison pour que ça ne fonctionne pas pour toi: https://sites.google.com/view/alkodique/vstream

**Comment by PanameFR** [comment]
Personnellement, j'ai tout essayer pour refaire fonctionner ma librairie uptobox. Rien ne fonctionne. Je vais tout refaire pour être sur.

**Comment by alKODIque** [comment]
@PanameFR 

T'es tu assuré d'avoir choisi "Rester en direct avec Uptobox" dans les paramètres de vStream, sous ton nom utilisateur et mot de passe Uptobox?

**Comment by zicmama** [comment]
**Vstream coince encore**, parce que son code prend la rouille! La perpétuelle quête que mène Vstream pour rester connecter à ses Stream recommence. Rien de plus normal quand on comprend le jeu de la sourie et du chat qui se joue ici.

Il y a d'un côté la constante apparition/disparition des annuaires et des sources et le contournement des contre mesures.
De l'autre, l'évolution de Kodi lui même qui manifestement n'apprécie pas que ses addons ait la liberté d'opérer comme il le veulent.

**Et si nous arrêtions cette course folle?** C'est désormais possible en utilisant la version mise à disposition par Astroport/KODI
Il s'agit d'une source de streaming très spéciale qui s'ajoute à Vstream...

Cette fois, nous devenons nous-même les hébergeurs de nos copies de vidéos et les partageons uniquement à nos amis.
La source de streaming devient le groupe d'ami qui se réunit et active ses relations sur [gChange](https://gchange.fr) 

Chacun d'entre nous s'organise en essaim qui fabrique une vidéothèque entre amis qui se sauvegarde et se renforce à chaque nouvelle lecture et s’enrichit de tout ce que ses amis y partagent. Et c'est 100% légal ! 

Fini cette perpétuelle réécriture des codes pour contourner les codes qui empêchent de coder librement. Gràce à la technologie blockchain intégrée et au moteur ipfs, aucun code ne peut plus nuire. Il ne peut que nous rendre service. C'est l'arche numérique que construit [Astroport](https://astroport.com).

Le code BETA [disponible ici ](https://git.p2p.legal/axiom-team/astrXbian) s'installe sur PC (distribution Linux Debian ou dérivé) et sur Rapsberry Pi (distribution Xbian).

J'invite tous les curieux, les pionniers à s'inscrire sur le [réseau de %Maker CopyLaRadio](https://copylaradio.com) où nous échangeons les informations pour faire soit-même, proposer et vendre ses propres Application dans l'**Internet des gens**.

**Comment by Arias800** [comment]
Uptobox et Uptostream sont corrigé dans la bêta. Il y a eu un changement de code de Vstream qui a eu un effet boule de neige xD

**Comment by zicmama** [comment]
Vstream coince encore, parce que son code prend la rouille! La perpétuelle quête que mène Vstream pour rester connecter à ses Stream recommence. Rien de plus normal quand on comprend le jeu de la souris et du chat qui se joue ici.

Il y a d'un côté la constante apparition/disparition des annuaires et des sources et le contournement des contre mesures.
De l'autre, l'évolution de Kodi lui même qui manifestement n'apprécie pas que ses addons ait la liberté d'opérer comme il le veulent.

Et si nous arrêtions cette course folle? C'est désormais possible en utilisant la version mise à disposition par Astroport/KODI
Il s'agit d'une source de streaming très spéciale qui s'ajoute à Vstream...

Cette fois, nous devenons nous-même les hébergeurs de nos copies de vidéos et les partageons uniquement à nos amis.
La source de streaming devient le groupe d'ami qui se réunit et active ses relations sur gChange

Chacun d'entre nous s'organise en essaim qui fabrique une vidéothèque entre amis qui se sauvegarde et se renforce à chaque nouvelle lecture et s’enrichit de tout ce que ses amis y partagent. Et c'est 100% légal !

Fini cette perpétuelle réécriture des codes pour contourner les codes qui empêchent de coder librement. Gràce à la technologie blockchain intégrée et au moteur ipfs, aucun code ne peut plus nuire. Il ne peut que nous rendre service. C'est l'arche numérique que construit Astroport.

Le code BETA disponible ici s'installe sur PC (distribution Linux Debian ou dérivé) et sur Rapsberry Pi (distribution Xbian).

J'invite tous les curieux, les pionniers à s'inscrire sur le réseau de %Maker CopyLaRadio où nous échangeons les informations pour faire soit-même, proposer et vendre ses propres Application dans l'Internet des gens.

**Comment by PanameFR** [comment]
> Uptobox et Uptostream sont corrigé dans la bêta. Il y a eu un changement de code de Vstream qui a eu un effet boule de neige xD
> 
> EDIT: J'ai rien dit, il y a un autre truc a modifié. Je suis en train de regardé.

Pas de soucis, je regarde les issues et la bêta tout les jours pour voir si ça refonctionne. 
Que se soit via uptobox ou stream j'ai des erreurs me disant qu'il ne peut pas trouver le fichier. Ducoup je passe par uptostream et un(e) chromecast.

**Comment by alKODIque** [comment]
je comprends pas, je suis sous Matrix et les liens uptobox fonctionnent bien, de même que la lecture des liens en passant par mon compte uptobox..

**Comment by Arias800** [comment]
Je lache l'affaire, c'est du niveau trop elevé pour moi. @TmpName devrai surement avoir une idée pour corrigé ca.

**Comment by PanameFR** [comment]
> je comprends pas, je suis sous Matrix et les liens uptobox fonctionnent bien, de même que la lecture des liens en passant par mon compte uptobox..

Oui, perso je vois les liens. Je peux accéder à mes fichiers vidéo mais pas les lire. Mais que je sois sur uptobox ou uptostream, ça ne ce lance pas. Et un message d'erreur apparaît me disant que le fichier est introuvable. 
J'ai réinstallé mon KODI à 0, avec les nouveaux fichier d'installations de Vstream dispo sur le github.

**Comment by TmpName** [comment]
@Arias800 j'ai pas eu le temps de regarder encore, c'est quoi le soucis, du javascript encore ?

**Comment by Arias800** [comment]
Ouais, ca a l'air d'être le décodage qui merde. Mais je n’ai pas réussit à comprendre pourquoi.

**Comment by Peur** [comment]
Hello, je reviens vers vous suite à mon 1er post.

J'ai donc installer vstream et kodi Matrix tout propre sur tablette samsung (qui n'a jamais possédé Kodi)
J'ai bien suivi les étapes d'installation.

Résultat: Impossible de lire les fichiers 1fichier.com (compte premium) et apparemment idem pour UpToBox (pas de compte premium)

Que se soit pour aller regarder des films sur mon compte 1fichier.com ou de passer par la recherche sur les sites de streaming. Il ne fonctionnent pas.
Toujours la même erreur 'Fichier introuvable'.

Par contre sur les autres fournisseurs de streaming pas de problème ca fonctionne.

Je vous joins le fichier log de kodi.
Essai avec 1fichier.com (fichier not found) et avec uqload.com (fichier fonctionne)

[kodi.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6173556/kodi.txt)

**Comment by TmpName** [comment]
@Arias800 j'ai commencé, ces fourbe ont fait une version custom de base64decode ^^
```
    var getOwnPropertyNames = function(o) {

      var listeners = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=";
      var props = "";
      var bc = 0;
      var bs;
      var buffer;
      var n = 0;
      for (; buffer = o["charAt"](n++); ~buffer && (bs = bc % 4 ? bs * 64 + buffer : buffer, bc++ % 4) ? props = props + String["fromCharCode"](255 & bs >> (-2 * bc & 6)) : 0) {
        buffer = listeners["indexOf"](buffer);
      }
      return props;
    };


function myatob(input)  {
    let str = input
    let output = '';

   const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';

    for (let bc = 0, bs = 0, buffer, i = 0;
      buffer = str.charAt(i++);

      ~buffer && (bs = bc % 4 ? bs * 64 + buffer : buffer,
        bc++ % 4) ? output += String.fromCharCode(255 & bs >> (-2 * bc & 6)) : 0
    ) { buffer = chars.indexOf(buffer); }

    return output;
};

window.alert("1>" + myatob("YWJjZGU="));
window.alert("2 >" + getOwnPropertyNames("YWJjZGU="));
```

Ils ont modifie la chaine de caractere de base.
si quelqu'un a la version sans lib python, ca m'interesserais pour pas avoir a me la taper

**Comment by Peur** [comment]
@Arias800, 

Hello, j'ai pas tout suivi...

**Comment by Arias800** [comment]
@TmpName j'ai une autre idée, je teste et je te dit si ca fonctionne.

@Peur On n'est en train de discuter pour résoudre le probleme.

**Comment by Arias800** [comment]
@TmpName J'ai réécrit le code en passant par leurs API, donc plus de décodage nécessaire.

**Comment by TmpName** [comment]
Lol, ok, je laisse tomber alors. Utiliser leur API a quoi comme contrainte ?

**Comment by Arias800** [comment]
Aucun idée, il n'y a rien de marqué dans leurs documentation.
En théorie, il y a un système de code pin a rentré via navigateur. Mais avec Session ça passe sans avoir besoin de passé par un navigateur xD

**Comment by PanameFR** [comment]
Bonjour avez vous des nouvelles ? Avez vous réussis a fixer le problème ? Merci d'avance, et bon courage pour les futur ajouts que vous développerez.

**Comment by TmpName** [comment]
Ben ca marcherait sur kodi 19
Je regarde ce Week end pour kodi 18.

**Comment by Peur** [comment]
> Ben ca marcherait sur kodi 19
> Pas encore testé pour kodi 18

Kikou, 

Ca veux dire qu'il y a une nouvelle mise à jour ?

**Comment by sizanic** [comment]
non,
ça veut dire que ce sera disponible dans la prochaine mise à jour.

**Comment by TmpName** [comment]
Testé sur kodi 18, marche avec la derniere version mais du coup j'espere ne pas avoir cassé la version pour kodi 19

**Comment by Peur** [comment]
> non,
> ça veut dire que ce sera disponible dans la prochaine mise à jour.

J'ai hate ^^

**Comment by Peur** [comment]
Bonjour, 

Avez-vous appliquer la résolution du bug sur la dernière version (1.1.0) ? car je viens de mettre à jour et j'ai toujours le même souci.

**Comment by sizanic** [comment]
Bonjour,

oui, la 1.1.0 embarque bien la modification pour l'accès aux liens uptobox.

**Comment by TmpName** [comment]
Petit rappel, il faut rentrer un identifiant, un mot de passe et ne pas oublier de cocher la case pour que UP2strm/Box fonctionne correctement, meme en gratuit.

**Comment by Che-debarras** [comment]
Je confirme que même avec un identifiant et mot de passe uptobx et uptostrm ne fonctionne pas sur kodi 19 mais peut-être est dû à allowredirect car même mystrm ne fonctionne pas sous allow redirect.
Par contre sur kodi 19 meme sans ID et MdP uptobx et uptostrm fonctionne etc...

**Comment by Peur** [comment]
> Bonjour,
> 
> oui, la 1.1.0 embarque bien la modification pour l'accès aux liens uptobox.

Mon post de départ était pour 1fichier.com ;-)

**Comment by Che-debarras** [comment]
> > Bonjour,
> > oui, la 1.1.0 embarque bien la modification pour l'accès aux liens uptobox.
> 
> Mon post de départ était pour 1fichier.com ;-)
> J'ai toujours le même problème.
> ERREUR: file not found.

J'ai remarqué que sur vstream il faut activer les comptes premium 
Mais si tu es sur kodi 18 tu ne met pas de identifiant ni mot de passe
Par contre si tu es en kodi 19 faut mettre un identifiant et un mot de passe

Essaye de faire de même avec 1fichier selon que tu es en kodo 18 ou 19

**Comment by Peur** [comment]
> > > Bonjour,
> > > oui, la 1.1.0 embarque bien la modification pour l'accès aux liens uptobox.
> > 
> > 
> > Mon post de départ était pour 1fichier.com ;-)
> > J'ai toujours le même problème.
> > ERREUR: file not found.
> 
> J'ai remarqué que sur vstream il faut activer les comptes premium
> Mais si tu es sur kodi 18 tu ne met pas de identifiant ni mot de passe
> Par contre si tu es en kodi 19 faut mettre un identifiant et un mot de passe
> 
> Essaye de faire de même avec 1fichier selon que tu es en kodi 18 ou 19 et tiens moi au courant je le mettrai dans le suivi des bugs
> 
> Par contre si ça passe par allow_redirect cela ne marchera pas sur kodi 19, il faut corriger le allow_redirect


Oui j'ai bien activé le compte premium et j'arrive bien sur mon catalogue de films.

 Peu être à cause de cette bête =>'allow_redirect '. Je ne sais pas ou c'est et ce que je peux y faire.
Je vais chercher....

**Comment by Peur** [comment]
Hello, 

Bon ben beaucoup de post suite à ma demande de bug depuis 1 mois. Mais résultat retour à l'ancien kodi  :-(

**Comment by Arias800** [comment]
J'ai mis une correction pour 1fichier dans la beta, le problème, c'est que sans compte premuim c'est compliqué à corriger.

**Comment by Peur** [comment]
> J'ai mis une correction pour 1fichier dans la beta, le problème, c'est que sans compte premuim c'est compliqué à corriger.

Oui, je comprends cela ne dois pas être évident.

Vstream 1.2, 1fichier.com fonctionne toujours pas.

Erreur: Echec de lecture de un ou plusieurs fichiers.

Amicalement,

**Comment by amidevous** [comment]
l'api uptobox sa pas une bonne idée les gars car sa ne charge que les liens uptostream et non les uptobox

y a asser souvent des vidéo uptobox qui ne sont pas convertie en uptostream

et aussi si y a pas un minimum de vu sur uptobox y a que du sd et pas de hd sur les stream

**Comment by alKODIque** [comment]
@amidevous 

Pourtant, je n'ai absolument aucun problème avec les liens uptobox.  (en premium)

Il y a un paramètre à l'intérieur de vStream ou tu peux choisir l'option ''Rester en direct avec uptobox'' ou bien ''Passer en direct avec uptostream''. (voir image)

- En sélectionnant ''Passer en direct avec uptostream'', tu obtiendras plusieurs liens de qualité différentes pour un même média
- En sélectionnant ''Rester en direct avec uptobox'' tu obtiendras le lien d'origine uptobox donc un lien premium de très bonne qualité (4k, 1080p, etc)
- 
![Screenshot_20210810-220119](https://user-images.githubusercontent.com/49578130/128958506-e04a7ca4-31fb-4838-b80a-dc940062274c.png)

Tu mentionnes ceci: 
_et aussi si y a pas un minimum de vu sur uptobox y a que du sd et pas de hd sur les stream_

Et bien ca fait plusieurs années que j'ai un abonnement premium uptobox et jamais je n'ai vécu ce que tu mentionnes.. Plusieurs autres utilisateurs pourraient également te confirmer ce point. Je n'ai que du HD  

Tu as probablement un problème au niveau des réglages... 
Ou alors, tu possèdes peut-être un compte gratuit et non premium?
