### ISSUE TITLE
VSTREAM ERROR

### ISSUE THREAD

**Issue by jackbubble** [Kodi-vStream/venom-xbmc-addons#3268]
**Décrivez le bug**
Erreur en installant update Vstream venom-xbmc-addons -1.0.0

**Votre system**
 - OS: Android
-  Appareil TV Box
 - Version Kodi  [19.0]
- Version Vstream 0.8.6

**Error log
F4mProxy : extension n'est pas compatible avec cette version de Kodi

**Comment by TmpName** [comment]
Hello https://github.com/Kodi-vStream/venom-xbmc-addons/issues?q=F4mProxy
