### ISSUE TITLE
Kodi19 - URLresolver OK sur Win10 mais pas sur Android

### ISSUE THREAD

**Issue by lorenzolamas** [Kodi-vStream/venom-xbmc-addons#3269]
Hello,

J'ai fais une installation de Kodi 19 sur Windows 10 et pour faire fonctionner URLresolver 5.1.24, j'ai dû d'abord installer URLresolver  et ensuite Vstream 1.0  pour qu'il soit reconnu depuis le menu de Vstream (et qu'il soit fonctionnel)

Par contre sur Android, (Mi box S) c'est un autre histoire... j'ai beau essayer dans tous les sens, ça ne fonctionne pas, quand je vais sur "premium/login > configurer UrlResolver" Vstream plante.

J'arrive à configurer _UrlResolver_ si je passe par _Systeme_ > _Extensions_ > _Gérer les dépendances_ (en mode avancé)
Mais ce n'est pas fonctionel sur Vstream.

**Comment by Che-debarras** [comment]
Essaye avec celui ci 
https://github.com/tvaddonsco/tva-resolvers-repo/tree/master/zips/script.module.urlresolver
Car ya pas de version 5.1.24 , le dernier est 5.1.22

**Comment by lorenzolamas** [comment]
En effet, tu as raison, c'est bien depuis ce dépôt que je les installe. je vais tester...

**Comment by Che-debarras** [comment]
> En effet, tu as raison, c'est bien depuis ce dépôt que je les installe. je vais tester...
> 
> Edit: en effet ça marche beaucoup mieux ^^
> 
> encore merci =)

De rien et si c'est résolu, faut fermer le sujet je pense.
