### ISSUE TITLE
Problème d’installation Vstream sur Kodi Bbox

### ISSUE THREAD

**Issue by krn-tino** [Kodi-vStream/venom-xbmc-addons#3270]
Hello à tous !
Suite à des problèmes de box, j’ai dû réinitialiser ma bbox TV, perdant ainsi Vstrem/Kodi.
J’ai réinstallé Kodi sur ma box mais impossible d’installer Vstream dessus, j’ai tenté différent lien 
-https://viphosting.site/depot/
-http://www.vstream.ml/repo
-https://git hub.com/Kodi-vStream/venom-xbmc-addons
-http://spr.nu
-https://fusion.tvaddons.co

rien n’a faire ils ne mènent nul part...
Pouvez-vous m’aider?

**Comment by razorex** [comment]
Salut, a tu pensé à prendre le repository de vStream sur le git de vStream et non pas ailleurs???????

**Comment by krn-tino** [comment]
J’essaye de l’installer sur ma bbox Miami et du coup je ne peux pas télécharger le repository ailleurs... il faudrait que je puisse le faire durement depuis Kodi

**Comment by sizanic** [comment]
Essayer d'installer le repository est ce qu'il faut faire.

Mais parmi tous les liens que tu as essayé, aucun n'est le lien officiel.
Aucun n'est le bon, ce qui peut expliquer que ça te mène nul part.

Le seul et unique lien officiel du repo est :
https://kodi-vstream.github.io/repo/

**Comment by krn-tino** [comment]
Ah super ça a marché ! Merci beaucoup !

**Comment by sizanic** [comment]
J'ai mis à jour la page d'acceuil de vStream : 

https://github.com/Kodi-vStream/venom-xbmc-addons

**Comment by razorex** [comment]
elle était pas à jour @sizanic ????

**Comment by sizanic** [comment]
- La doc ne donnait pas le lien vers l'url du repo.
- Cette url ne contient pas la version 0.0.4 c'est vrai
- Mais la 0.0.3 va se mettre à jour tout seul

**Comment by razorex** [comment]
oui merci je sais qu'elle va ce mettre à jour seule.
Il ne faut pas transferer les pages du github.io ??? dans la to do list

**Comment by sizanic** [comment]
> oui merci je sais qu'elle va ce mettre à jour seule.

Je sais que tu le sais, c'est plus une information complémentaire pour ceux qui vont lire nos échanges


> Il ne faut pas transferer les pages du github.io ??? (dans la to do list)

Oui, on doit s'y mettre


> je te trouve un peu sec dans tes commentaires..

Ce n'était pas voulue.
J'ai voulu utiliser un format "énumération" pour séparer mes réponses, c'est ce qui donne des phrases courtes (et donc un effet un peu sec).
