### ISSUE TITLE
Beug marque page

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#3271]
**Décrivez le bug**
Quand je met une série de zustream (séries) en marque page, la première que je met de cette source n'a pas le titre et les suivantes j'ai le message d'info "Déjà présente" alors que c'est une autre série.
Du coup j'ai nettoyé la db avec le menu supprimer dans chaque marque page et aussi celui a la base de tout les marques pages.
je n'ai le problème qu'avec cette source, en plus dans le fichier vstream.db j'ai encore des datas et sa ne marche tjrs pas.

**Comment by Che-debarras** [comment]
J'ai le même souci avec frnchstrm.lol pas toi?
Je pense que d'autres sources ont ce souci

**Comment by TmpName** [comment]
J'ai corrigé le fichier bookmark pr eviter ca.
Pour le fichier zustream, essayes en reactivant les titres

```
            oOutputParameterHandler.addParameter('siteUrl', sUrl)
            # oOutputParameterHandler.addParameter('sMovieTitle', sTitle)
            oOutputParameterHandler.addParameter('sThumb', sThumb)
```

(Virer le  #)

**Comment by razorex** [comment]
oui c'est bien çà @TmpName
merci
