### ISSUE TITLE
uptostream hoster

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#3272]
Est-ce que uptostream (version Beta) marche sans premium account?
Sans premium, vstream a le mauvais tok: autoSubmitPin

Merci

**Comment by Arias800** [comment]
Oui ça fonctionne sans compte premium, mais par contre il faut un compte (un gratuit suffit).

**Comment by sviet2k** [comment]
Merci beaucoup @Arias800. Ça marche très bien avec un compte gratuit.
