### ISSUE TITLE
Ajout d'une liste de lecture XML perso

### ISSUE THREAD

**Issue by osmoze06** [Kodi-vStream/venom-xbmc-addons#3273]
Bonjour,
J'utilisais avant la mise à jour vers KODI 19 Matrix, le plugin LiveStreamsPro afin d'intégrer des listes de lecture IPTV au format XML.
L'addon est devenu incompatible et je n'ai rien trouvé d'équivalent pour faire le job.

Y a t'il un moyen depuis Vstream d'intégrer une liste XML (avec un lien web ou en local) en bricolant un peu ? (Il y a un moment, on pouvez intégrer des listes M3U de mémoire).

Si ce n'est pas possible, existe t'il un addon compatible KODI 19 ?

Merci pour votre aide.

**Comment by TmpName** [comment]
Si c'est du pur XML, avec juste des liens (LiveStreamsPro supporte des liens a la con avec regex par exemple) ca peut marcher nativement sur kodi.
J'utilise ca https://www.atlasweb.net/comment-configurer-pvr-iptv-client-simple-kodi/

**Comment by osmoze06** [comment]
Merci pour ta réponse @TmpName , IPTV Simple Client ne corresponds pas à ce que je cherche à faire car dans mon fichier XML, il y a des liens de catégories avec des descriptifs avant d'arriver aux liens de streaming etc...

(C'est exactement le même type de navigation que dans Vstream pour être précis).

Je ne connais que LiveStreamsPro qui permettait une navigation optimal mais qui n'est plus supporté :(

**Comment by zombiB** [comment]
Tu peux le faire en ajoutant le site dans le répertoire sites dans vstream tu doit seulement changer un peu dans le code, après le regex est le même

**Comment by osmoze06** [comment]
Cool, je vais essayer de faire ça alors. Je crois que j'ai vu un tuto quelques part il me semble pour ajouter un site... Je vais voir si je m'en sors. Merci zombiB

**Comment by sizanic** [comment]
Les tutos sont là :
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki

**Comment by osmoze06** [comment]
Merci sizanic, j'ai commencé la lecture mais ça me parait bien compliqué pour le peu de chose que je souhaites faire, à savoir, mettre un lien de type http://maliste.xml puis simplement naviguer dedans (des liens vers d'autres fichiers XML sont à l'intérieur).

Y a t'il un moyen simple de le faire ou dois-je passer par le script décris dans le tuto? Si quelqu'un peut m'aider pour débuter,
Merci beaucoup,

**Comment by sizanic** [comment]
Je pense que ce sera en effet très compliqué car pas adapté.

vStream a pour objectif de proposer des liens de streaming à partir de sites de streaming.
Et n'a pas du tout été pensé pour de l'IPTV, avec des outils comme la lecture de fichier xml.


N'as-tu vraiment trouvé aucune application qui te permette de lire tes fichiers XML ?
Des applications dont c'est plus le but.

**Comment by osmoze06** [comment]
Merci pour ta réponse. Malheureusement non, pas compatible sous Kodi Matrix, c'est bien là le problème.

**Comment by sizanic** [comment]
Je ne parle pas d'une extension de KODI.
Je parle d'une vraie application, d'un autre programme que KODI.

Des applications dont c'est plus le but de lire du XML qui contient des liens IPTV.

**Comment by osmoze06** [comment]
Les liens contenus dans mes fichiers XML appel l'extension Vstream pour les lires, du coup, je dois passer par un addon de Kodi obligatoirement. Je ne trouve rien d'équivalent à LiveStreamsPro sur KODI 19 malgré de nombreuses recherches.

**Comment by sizanic** [comment]
>J'utilisais avant la mise à jour vers KODI 19 Matrix, le plugin LiveStreamsPro afin d'intégrer des listes de lecture IPTV au format XML.
Les liens contenus dans mes fichiers XML appel l'extension Vstream pour les lire


Je ne comprend pas, tes liens appellent vStream qui va lire des flux IPTV ??  🤔 

Mais vStream n'est pas un player de vidéo.
Si tu lui donnes un lien, vStream renvoi ce lien à KODI, et c'est le lecteur de KODI qui lit le flux.

Je me demande si tu ne pourrais pas te passer vStream 🤔 

Il nous faudrait un exemple de lien et nous pourrions d'aiguiller vers une solution.

**Comment by osmoze06** [comment]
Voici un exemple de balise que j'utilise : 

`<item>
<title>[COLOR blue]DOCUMENTAIRE[/COLOR] - [COLOR green]Dans les parties les plus radioactives de Tchernobyl[/COLOR]</title>
<info>Les trois vidéaste de Mamytwink sont partis quatre jours dans la zone d'exclusion de Tchernobyl pour en explorer les moindres recoins.</info>
<link>plugin://plugin.video.vstream/?site=cHosterGui&amp;function=play&amp;title=Voici+votre+lien%3A++%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&amp;sHosterIdentifier=uptobox&amp;sTitle=Voici+votre+lien%3A++%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&amp;siteUrl=https%3A%2F%2Fuptobox.com%2F64qbrfl3llkb&amp;sFav=play&amp;sMediaUrl=https%3A%2F%2Fuptobox.com%2F64qbrfl3llkb&amp;sCat=4&amp;sId=cHosterGui&amp;sFileName=Voici+votre+lien%3A+&amp;sTitleWatched=voicivotrelien</link>
<thumbnail>http://test/DOCUMENTAIRES/thumbnail_02.jpg</thumbnail>
<fanart>http://test/DOCUMENTAIRES/thumbnail_02.jpg</fanart>
</item>`

**Comment by sizanic** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Voir-et-partager-sa-biblioth%C3%A8que-priv%C3%A9e

**Comment by osmoze06** [comment]
Merci sizanic, je vais regarder ça

**Comment by osmoze06** [comment]
Je viens de faire un test, je n'ai le droit qu'à "**format non supporté**" lorsque je faits "ajouter un code PasteBin" en suivant le tuto.
Exemple de test : 

https://pastebin.com/raw/**pwMzZbKH**.

Mon fichier PasteBin est pourtant correctement formaté : 

TITLE;URLS
Adieu les cons;'https://uptobox.com/quh94urooox9'

**Comment by osmoze06** [comment]
Je fais un test avec ce format dans PasteBin : 

CAT;TMDB;TITLE;YEAR;URLS
film;651881;Adieu les cons;2020;'https://uptobox.com/quh94urooox9'

Je n'ai pas de descriptif ni d'affiche en provenance de l'identifiant TMDB, le lien par ailleur ne se lance pas non plus pour lire la vidéo, une idée ?

**Comment by sizanic** [comment]
J'ai testé ton paste : pwMzZbKH

J'ai bien le descriptif et l'affiche. 
-> As-tu bien activé "Recherche des métadonnées" dans les parametres de vStream ?


Le lien ne se lance pas en effet, plusieurs raisons : 
1 - il ne faut pas de guillemet autour du lien : https://uptobox.com/quh94XXXoox9
2 - il y a un bug que je viens de voir en testant ton lien (je l'ai corrigé mais il faudra une prochaine version ou utiliser une version Beta)
3 - tu as eu la réponse sur Discord : il faut un compte Uptobox Premium 😉 

S'il faut un compte premium, c'est parce qu'avant toi, plusieurs personnes ont déjà chinés des liens uptobox et les ont tous rassemblé sur des comptes.
Ce compte Premium est nécessaire pour éviter que ces tous liens soient pompés.


Ce qui veut dire aussi pour toi c'est que si tu te prends un compte tu vas t'économiser la recherche fastidueuse de liens Uptobox alors qu'on les a tous déjà trouvé 😄 

Prends un compte Premium, utilises les codes pastbin disponibles sur Discord et profites !

**Comment by osmoze06** [comment]
Merci pour ton aide sizanic, j'ai eu un peu d'aide également sur Discord car je ne comprenais pas tout sur ce mode de fonctionnement.

C'est très intéressant et c'est ce qui se rapproche le plus de ce que j'avais avant.
Pour l'instant, je n'ai pas de compte premium Uptobox, c'est peut être pour cela que je n'arrive à rien...

La recherche de métadonnées est bien activée depuis l'onglet général des paramètres de vstream mais je n'ai rien quand je navigue dans ma source PasteBin.

**Comment by sizanic** [comment]
Si tu n'as pas les informations, il se peut que ce soir la clef TMDB qui ne soit pas bonne.
As-tu essayé d'en renseigner une autre à la place de celle qui était déjà fournie ?

vStream est fournie avec sa clef TMDB.
Pour la remettre utilises le bouton "d'origine" dans la fenêtre des paramètres de l'onglet "Général" de vStream.

**Comment by osmoze06** [comment]
Je pense que je dois avoir un bug car j'utilise la version 19.0 MATRIX, notamment avec les liens Uptobox qui ne sont plus lus non plus dans Vstream.
J'ai ouvert un ticket suite à ce problème : [https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3276].

**Comment by osmoze06** [comment]
Je vais repartir sur une installation fresh de Kodi en 19.0. Je vais réessayer la méthode avec PasteBin voir si ça fonctionne.

Pour résumé, on est bien d'accord que plus aucun liens Uptobox ne fonctionneront sans compte premium dans cette nouvelle version de Kodi, que se soit avec PasteBin ou autres hosters (si j'ai bien compris).

Avec la méthode PasteBin, puis je mettre d'autres liens que Uptobox, notamment des liens EVOLOAD que j'ai pour tester (car toujours pas de compte premium pour Uptobox pour ma part).
Est-ce possible d'avoir un exemple de structure TXT afin que je réalisé mes tests?
Merci pour votre aide à nouveau.

**Comment by sizanic** [comment]
> Pour résumé, on est bien d'accord que plus aucun liens Uptobox ne fonctionneront sans compte premium dans cette nouvelle version de Kodi, que se soit avec PasteBin ou autres hosters (si j'ai bien compris).

non, pas du tout 😆 

Pas besoin de compte pour les autres sources que Pastebin.
Et pour Pastebin, le compte premium n'est nécessaire seulement dans le cas d'utilisation des codes pastebin "PRO".
Les codes PRO sont les codes proposés sur le discord.

Pas besoin de compte pour un paste PERSO.
Et tu peux mettre autre chose que uptobox.


Le tuto pour créer ton fichier, avec des exemples de structure : 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Voir-et-partager-sa-biblioth%C3%A8que-priv%C3%A9e

**Comment by osmoze06** [comment]
Super merci beaucoup Sizanic pour ces éclaircissements... Je m'en vais tester tout ça.

**Comment by sizanic** [comment]
@osmoze06 est passé sur Pastebin, je ferme cette demande.
