### ISSUE TITLE
Hoster Direct : Lien Uptobox KO

### ISSUE THREAD

**Issue by osmoze06** [Kodi-vStream/venom-xbmc-addons#3276]
Bonjour,

Les liens Uptobox ne fonctionnent plus via l'outils "Hoster Direct".
Je n'obtiens que le message "fichier introuvable".

Merci pour votre aide.

**Comment by osmoze06** [comment]
Idem pour les liens Uqload...

**Comment by Che-debarras** [comment]
C'est valable pour tous les liens direct allow redirect ex host de frenchstrm.lol comme mystrmi

**Comment by yodidon** [comment]
@Che-debarras  pour ma part je n'ai pas réussi a lancer un lien mystm sur le site, donc je ne peux pas voir ce qui se passe.

**Comment by Che-debarras** [comment]
> @Che-debarras pour ma part je n'ai pas réussi a lancer un lien mystm sur le site, donc je ne peux pas voir ce qui se passe.

Sur kodi 18.9 les liens mystrm fonctionne sur frenchstrm.lol donc tu es sûrement en kodi 19?

**Comment by yodidon** [comment]
@Che-debarras  kodi 18 ou 19 peut importe puisque je n’arrive pas à lancer le lien sur le site lui même

**Comment by Che-debarras** [comment]
> @Che-debarras kodi 18 ou 19 peut importe puisque je n’arrive pas à lancer le lien sur le site lui même

Je sais pas quoi dire cest comme avec @Arias800 chez moi sur kodi 18.9 ça marche mais pas sur kodi 19.
Essaye le film thunder force

**Comment by Che-debarras** [comment]
Voici une photl de allow direct après avoir cliquer sur FBI S03 host uptobx en kodi 18.9 
![20210411_130949](https://user-images.githubusercontent.com/44464129/114302090-c6d5c580-9ac7-11eb-8156-7d2afd2f146a.jpg)

Voici uptobx en allow redirect avec le film thunder force en kodi 18.9
![16181396839508377923793566039185](https://user-images.githubusercontent.com/44464129/114302116-eff65600-9ac7-11eb-8034-f356091a3d77.jpg)

Donc comme voyez le problème viens de kodi 19 je pense

**Comment by Che-debarras** [comment]
> Bonjour,
> 
> Les liens Uptobox ne fonctionnent plus via l'outils "Hoster Direct".
> Je n'obtiens que le message "fichier introuvable".
> 
> Merci pour votre aide.

As tu activé uptobox premium dans les paramètres vstream?cela devrait marcher sur kodi 18 (kodi 19 non)

**Comment by Arias800** [comment]
Allow redirect et Hoster Direct ça n'a rien à voir, c'est deux fonction différente et elle n'interfère pas l'une et l'autre. Donc faut expliquer le problème clairement avec un exemple (et le site utilisé).

**Comment by osmoze06** [comment]
> > Bonjour,
> > Les liens Uptobox ne fonctionnent plus via l'outils "Hoster Direct".
> > Je n'obtiens que le message "fichier introuvable".
> > Merci pour votre aide.
> 
> As tu activé uptobox premium dans les paramètres vstream?cela devrait marcher sur kodi 18 (kodi 19 non)

Non, absolument pas, je n'ai pas de compte uptobox premium, est-ce là la source du problème ou une incompatibilité de version KODI?

**Comment by osmoze06** [comment]
Lorsque j'utilise la fonction Hoster Direct, j'y insert un lien Uptobox (non premium) mais testé sur PC qui fonctionne.

**Comment by Che-debarras** [comment]
> Lorsque j'utilise la fonction Hoster Direct, j'y insert un lien Uptobox (non premium) mais testé sur PC qui fonctionne.

Etape 1: Sur kodi 18 ou 19 tu es obligé d'activer le compte uptobox premium dans les paramètres vstream.
Etape 2 : Si tu es en kodi 18 ton identifiant et mot de passe ne sont pas nécessaires 
Etape 3 : Par contre si tu es en kodi 19 tu dois obligatoirement mettre ton identifiant et mot de passe

Une fois que tu as fait cela, va sur frenchstrm.lol et choisi un film uptobox et regarde si cela fonctionne 
Si cela fonctionne le problème n'est ni uptobox ni ton paramètres vstream mais bien u problème de hoster direct

Pour infos j'ai testé hoster direct avec un lien vidoza ça marche mais avec un lien vidlox ça ne marche pas donc je dirais que host direct est un peu aleatoire selon les hosts

**Comment by osmoze06** [comment]
Voici un extrait des logs : 

`2021-04-19 16:48:23.585 T:6781     INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-04-19 16:48:25.146 T:6781     INFO <general>: 	[PLUGIN] vStream: load site cHosterGui and call function play
2021-04-19 16:48:25.154 T:6781     INFO <general>: 	[PLUGIN] vStream: Hoster - play : https://uptobox.com/ ... /tql6qbto5154
2021-04-19 16:48:25.789 T:6781     INFO <general>: 	[PLUGIN] vStream: SQLITE 3 as DB engine for tmdb
2021-04-19 16:48:25.794 T:6781     INFO <general>: 	[PLUGIN] vStream: Utilise compte gratuit pour hoster: uptobox
2021-04-19 16:48:25.794 T:6330    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-04-19 16:48:25.796 T:6781     INFO <general>: 	[PLUGIN] vStream: UPTOBOX - no premium
2021-04-19 16:48:25.827 T:6781     INFO <general>: 	[PLUGIN] vStream: Utilise compte gratuit pour hoster: uptobox
2021-04-19 16:48:25.830 T:6781     INFO <general>: 	[PLUGIN] vStream: Erreur: Fichier introuvable`

**Comment by TmpName** [comment]
`Utilise compte gratuit pour hoster`

Mauvais setting, configure Vstream en l'activant.

**Comment by osmoze06** [comment]
Mon compte real-debrid est actif avec le token dedans, que dois-je faire, je n'ai pas bien compris ?

**Comment by TmpName** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3276#issuecomment-817650596

Meme avec un gratuit.

**Comment by osmoze06** [comment]
ahhhhhhh, ça y est, j'ai entré mon compte gratuit Uptobox et activé dans les paramètres Vstream / Compte. Je confirme que cela fonctionne enfin !
En effet, le comportement de Vstream est différent de la version de KODI 18.
Super, merci.

Pour résumé, pour ceux qui rencontre le problème avec KODI 19.0 Matrix : 

- Créer un compte gratuit ou premium sur Uptobox
- Le renseigner dans les paramètres Vstream / Compte

sans ça, bah ça marche pas...

**Comment by osmoze06** [comment]
J'avais comprise qu'il fallait un compte premium, j'avais pas saisi qu'on compte gratuit suffisait à débloquer la situation. Mea-culpa, merci beaucoup à tous pour votre aide. Je clôture le post 😉
