### ISSUE TITLE
Recherche visuelle ne fonctionne plus

### ISSUE THREAD

**Issue by hubsolo** [Kodi-vStream/venom-xbmc-addons#3278]
**Décrivez le bug**
Lorsque j’essaie de lancer une recherche visuelle d’un film ou d’une série, rien ne se passe.
La dernière fois que j’ai eu ça, j’ai changé l’api dans les paramètres pour mettre celui d’un post de bug précédent et ça a fonctionné.
J’ai vérifié et l’api est toujours le bon.
Y a-t-il un nouvel api?
Merci!

**Votre system**
 - OS: android
-  Appareil: raspberry pi
 - Version Kodi  17.6
- Version Vstream: 1.1.0

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site: tous.
- Le titre du fim/serie: tous
- Le nom du host (openload/vidzi): tous

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by hubsolo** [comment]
Rectification, tout fonctionne avec les films. C’est juste sur les séries.
Bizarre...

**Comment by hubsolo** [comment]
Hello,

Je suis passé sur libreelec 9.2.6 avec kodi 18.9 et vstream 1.1.0 et pourtant la recherche visuelle ne fonctionne toujours pas pour les séries.
Ça affiche bien les séries, mais lors de la sélection de l’une d’entre elles, il ne cherche pas les sources.

Merci.

**Comment by alKODIque** [comment]
> Hello,
> 
> Je suis passé sur libreelec 9.2.6 avec kodi 18.9 et vstream 1.1.0 et pourtant la recherche visuelle ne fonctionne toujours pas pour les séries.
> Ça affiche bien les séries, mais lors de la sélection de l’une d’entre elles, il ne cherche pas les sources.
> 
> Merci.

Sous kodi v19 matrix, sous windows et android, je n'ai aucun problème avec la recherche visuelle de vStream. Films et séries sont recherchées via les sources que j'ai sélectionnées

**Comment by hubsolo** [comment]
Merci.
Je viens de voir qu’avec un appuie long puis selectionnant « recherche » ça fonctionne sur les séries.
C’est seulement quand je sélectionne directement l’image d’une série, et il ne se passe rien.
Bizarre...

**Comment by alKODIque** [comment]
> C’est seulement quand je sélectionne directement l’image d’une série, et il ne se passe rien.
> Bizarre...

J'ai déjà rencontré une situation similaire, mais ceci se produisait seulement lorsque j'accédais a du contenu vstream via un widget. Le même contenu devenait accessible en passant par l'addon.
