### ISSUE TITLE
Kodi matrix + maj vstream 1.1.0 impossible (help plz) 

### ISSUE THREAD

**Issue by yamoky** [Kodi-vStream/venom-xbmc-addons#3279]
Bonjour, j'ai vue qu'il y avait des problèmes de maj de l'addon avec la kodi.

Je me suis dit que j'allais attendre la 1.1.0 mais je ne peux toujours pas la faire.

Pourriez-vous m'expliquer comment faire la maj svp ?

Je suis sur Android v10 

Y a t'il aussi un discord fr pour vstream ou d'autres extensions. (Perso je n'utilise que vstream) 😅

**Comment by sizanic** [comment]
Bonjour,

Il faudrait nous dire exactement quel est ton problème, car "Je ne peux pas faire la mise à jour" n'est pas assez précis pour qu'on te dise ce qui ne va pas  🤔 


Sinon, le discord de vStream est ici : https://discord.gg/KRsDT7PNHN

**Comment by sizanic** [comment]
Commence par nettoyer tes extensions obsolètes en passant par le menu :
Paramtères
Systeme
Extensions
Gérer les dépendances.
=> Désinstalles les extensions qui présentent une icone de balai.


> J'ai essayé en téléchargent la mise à jour sur github.

Non, Ne passes pas par là.

**Comment by yamoky** [comment]
Bon en fait c'était urlresolver pour bloquer la maj

Merci beaucoup 😉
Dsl d'avoir fait un poste pour ça 😅

La communauté de vstream est toujours au top.👍🏻👌
