### ISSUE TITLE
Intégrer Channelstream a pvr simple Client

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#3281]
Bonjour,
Je sais que cela est peut être compliquer sans fichiers m3u ou liens url mais je pose quand même la question.

 Est ce possible d'intégrer à l'addon  pvr simple client les sources de channelsStream  de la rebrique Télévision/Musique/TV (Source) de Vstream ?.
Exemple en vidéo de l"Addon Catch up TV and more sur ce sujet: https://youtu.be/o3NRq9Iw68A

L'addon catch up tv and more est intégrable a pvr simple client  via fichier m3u.Et les sources url de ces chaînes sont masquer dans ces fichiers m3u.Et appartement le développeur de catch up tv and more a une technique pour faire cela. 
Source Github de Catch up TV and more : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore

Merci pour votre reponse.

victore447

**Comment by TmpName** [comment]
Ben c'est mon avis personnel, mais c'est pas franchement le creneau de Vstream.
C'est comme coder une deuxieme application a l'interieur de la premiere, tout est a faire, et pour le support c'est pire.

**Comment by sizanic** [comment]
Je te rejoins @TmpName , ça sort de la vision fonctionnelle de vStream.

(la vidéo m'a quand même intéressé, je regarderais comment ils ont fait mais juste pour ma culture).

**Comment by Arias800** [comment]
J'avais codé un morceau de code faisant un truc similaire. En faite il cré un m3u8 local (contenant les chemin du plugin) et modifie les réglage de PVR Simple Client pour qu'il pointe vers ce m3u8 local pour que Kodi exécute les chemin de l'addon. Simple, mais efficace.

**Comment by sizanic** [comment]
ça pourrait valoir le coup d'y jeter un coup d'œil si on a déjà un socle de réalisé.

Je suis prêt à reprendre ton travail @Arias800 si tu n'est pas motivé à t'y replonger.

**Comment by Arias800** [comment]
Si tu veux, ça fait deux ans que je n’ai pas touché ce code. Je te préviens, c'est vraiment du prototype ahah
https://github.com/Arias800/Fichier-divers/blob/master/freebox.py

**Comment by sizanic** [comment]
Pour l'instant je suis pris sur deux autres grandes nouvelles fonctionnalités.
Mais je me le note pour plus tard...

@yodidon 
Je sais que tu essayais de coder un "channel TV".
N'y a t-il pas un lien avec tout ça ?

**Comment by yodidon** [comment]
Je ne pense pas , j’ai mis en stand bye , la source est trop changeante

**Comment by victore447** [comment]
**Rebonjour**,
Si cela peux aider,Il y a aussi L'addon service IPTV manager que les développeurs de catch- up tv Intégre a leurs repo pour synchroniser automatiquent les sources tv m3u vers IPTV simple client.

**Service IPTV manager:**
https://github.com/add-ons/service.iptv.manager
**Lien du guide Catch up TV de configuration du service IPTV manager:**
https://catch-up-tv-and-more.github.io/fr/live_tv_installation/

Enfin il y aussi d'autres développeurs comme Team Milhanos Leia Matrix qui font comme l'équipe de Catchup TV .
**Sources du repo pour Kodi:**
http://milhano.pt/fonte 
Source de leurs sites :
https://kodinfonline.weebly.com/repositorios1abcd.html

Victore447

**Comment by Che-debarras** [comment]
Peut-être rendre  vstream compatible iptv merge? Ce dernier recherche dans leq addons des playlists

**Comment by Che-debarras** [comment]
@victore447 
Ta liste m3u ne fonctionne plus, si tu peux m'aider

**Comment by sizanic** [comment]
Il n'y a aucune liste m3u ici car ici n'est pas lieu d'échange de listes m3u.

**Comment by alKODIque** [comment]
La solution pour accéder au contenu de la source channelstream via simple client pourrait peut-être être d'utiliser cet addon: https://github.com/PseudoTV/PseudoTV_Live

**Comment by lesueurnicolas27** [comment]
> Si tu veux, ça fait deux ans que je n’ai pas touché ce code. Je te préviens, c'est vraiment du prototype ahah https://github.com/Arias800/Fichier-divers/blob/master/freebox.py

merci
[README.md](https://github.com/Kodi-vStream/venom-xbmc-addons/files/13755084/README.md)
