### ISSUE TITLE
Sources codes Stalker/Stb dans Vstream

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#3282]
Bonjour,
J'ai remarquer que les sites TV Sources m3u  sont retirés de Vstream via rebrique TV (liens instables ou morts).

Voici par exemple 2 sources codes Stalker gratuits et stables pour voir toutes les chaînes payantes ou gratuites  du monde entier (**Certains marchent environ 6 mois voir plus d'un ans).**
- h t t p ://v pro.mi llenium-ott.com:25443/c/
- xx:xx:xx:xx:xx:xx
EXPIRE le 12.09.21
- h t t p://ww.spo ri ptv.ml:8080/c
- xx:xx:xx:xx:xx:xx
EXPIRE le 28.10.21
 
Toutes les versions de L'addon pvr Stalker ( https://github.com/kodi-pvr/pvr.stalker ) sont instables sur les KODI avec pratiquement tous les codes Stb emu mais ces Sources fonctionnent parfaitement avec les applis via liens ci dessous.
Stb Emu:
h t t p s://play.go ogle.com/sto re/ap ps/details?id=com.m v as.s t b.emu.free
OTT Navigator:
h t t p s://pl ay.google.com/store/apps/details?id=stu d i o.s c i l l arium.ottnavigator

3 Sites Fournissants les codes stalker:
ht  t p s://www.t a g h d outelive.com/?m=1
h t t p s://i p t v l i n  k seuro.blogspot.com/search/label/Stalker%20Portal?m=1
h t t  ps://ip t v x t reamcodes.com/category/free-s t b e mu-codes/

**Est ce possible d'intégrer ce genre de Sources Stalker  a Vstream via rebrique Télévision/Musique/TV (Source)?**

Merci pour votre réponse.

Victore447

**Comment by sizanic** [comment]
Bonjour

> Voici par exemple 2 sources codes Stalker gratuits et stables pour voir toutes les chaînes payantes ou gratuites du monde entier

ces sources sont gratuites car tu ne les a pas payées, mais si il y a une adresse MAC et une date d'expiration c'est qu'il s'agit d'un vrai compte que quelqu'un à payé.
**Diffuser des comptes qui ne sont pas les siens ne les rends pas gratuits**

<br>

> ces Sources fonctionnent parfaitement avec les applis via liens ci dessous

Et bien il faut continuer à utiliser ces appli qui sont des applications dédiées et spécialisées dans cette technologie.
vStream ne veut plus être diffuseur d'IPTV, ce n'est pas qu'une question de stabilité.
vStream va se concentrer sur le streaming.

> Est ce possible d'intégrer ce genre de Sources Stalker a Vstream via rebrique Télévision/Musique/TV (Source)?

non, il y a des applications pour ça (voir les liens dans le messages précédent)

**Comment by Che-debarras** [comment]
L'instabilité n'est pas due à l'application ou l'addon mais à la source iptv.
Les liens fournis dans tes sites sont des liens publics que tous le monde utilisent.
J'ai testé un lien sur l'application OTT et sur Perfectplayer et c'est instable.
Il faut avoir son propre abonnement iptv pour ne plus avoir cette instabilité 
Et faut avoir une excellente connection wifi.

J'ai longtemps cherché une solution (addons et applis) et la seule fois où c'était stable c'était avec un abonnement iptv unique.
Je t'invite à demander un lien iptv de TEST chez un fournisseur et tu verras que c'est stable.
Esssaye sinon l'addon xtreamcode ou livestreampro ou iptv merge

**Comment by victore447** [comment]
Bonjour,
**Che-debarras** si  le dernier message m'est adresser je suis ok pour les liens m3u (instables etc..).

**Par contre il y a une différence entre les liens m3u et les codes Stalker/code Stb emu si vous ne connaissez pas.**

- Le site https://www.taghdoutelive.com/?m=1 fourni de meilleurs sources que les autres sites.

- Les liens m3u de ce site qui fonctionnent sont stablent.
Par contre la majorité de ces liens supportent que une connection max a la fois (une personne) .
En clair si vous avez constater que un de vos liens m3u ne fonctionne plus c'est que il y a une personne dessus  (il faut essayer plus tard). Je m'en sert et fonctionnent parfaitement sur Kodi via l'addon  iptv simple client,l'addon playlist loader...et sur tous les applis etcc...

- **Pour les codes Stalker/code Stb emu voir mon premier message** .Le code Stalker de mon premier message a été masqué et donc vous ne pouvez pas constater le bon fonctionnement.

**Comment by sizanic** [comment]
Bonjour,

> Les sources m3u de ce site qui fonctionnent sont stables. Par contre la majorité de ces liens supportent que une connection max a la fois (une personne) .

Des personnes **ont achetés** un abonnement du genre "SmartIPTV" ou KingIPTV.
Pour éviter que la liste m3u qu'ils ont acheté **soit utilisée par d'autres**, cette liste (**pour laquelle ils ont payé**) est associée à l'adresse MAC (c'est comme une adresse IP) de leur équipement (boitier Android).

stbEmu permet de saisir l'adresse MAC associée à la liste m3u, afin de **se faire passer pour le propriétaire** de la liste.
Lorsque le propriétaire est déjà en train d'utiliser la liste, avec son équipement d'origine (celui qui à la vraie adresse MAC), c'est à ce moment là que tu ne peux pas **te faire passer pour lui** avec une adressse MAC **déguisée**.
Ce qui explique "une personne à la fois".

<br>

> Pourquoi je payerais un abonnement en perdant de l'argent (escrocs) alors que j'ai gratuitement tout en ligne qui fonctionne parfaitement.

<br>

relis les mots que j'ai mis en gras : 
QUI EST VRAIMENT L'ESCROC !!??

<br>


> Les codes Stalker de mon premier message ont étés masqué et donc vous ne pouvez pas constater le bon fonctionnement.


J'ai effacé les adresse MAC que tu as diffusée ici car elle appartiennent à des personnes qui ont acheté un abonnement.
**PAS DE RECELLE D'ADRESSES MAC SUR CE SALON**. Merci !
