### ISSUE TITLE
Bug affichage avec les dernières modifs de la beta

### ISSUE THREAD

**Issue by Rick407** [Kodi-vStream/venom-xbmc-addons#3286]
Bonjour, j'ai remarqué un soucis d'affichage et même d'accès avec le test de la nouvelle béta avec les dernières modifications effectuées depuis la dernière version valide.
Je m'explique.
Même si l'affichage est beaucoup plus agréable, malheureusement la fonctionnalité en est tout autre pour lancer une série.
Je précise que le problème n'a lieu que pour les séries.
Pour info, mon skin (on ne sait jamais...) est Titan Bingie Mod (dernière version pour Matrix).

Lorsque je sélectionne une série, l'affichage d'aprés devrais être soit lire (si on est positionné directement sur l'épisode voulu) sois proposer les différentes saisons.

En fait, au lieu de proposer "lire", le widget propose "plus d'épisodes" (ce terme n'était jamais apparu avant).
En cliquant sur "plus d'épisodes"... rien ne s'affiche.
En photo, c'est plus explicite.

Je ne pense pas que cela provienne du skin, car avec la dernière version stable, tout fonctionne.
![im1-ancien](https://user-images.githubusercontent.com/80746871/116999509-c3151780-acf0-11eb-9353-a081d4cfaf7e.JPG)

![im2-ancien](https://user-images.githubusercontent.com/80746871/116999526-c90af880-acf0-11eb-97c5-3aa37f9959fe.JPG)

![im3-ancien](https://user-images.githubusercontent.com/80746871/116999544-cf00d980-acf0-11eb-926d-718a1c49f326.JPG)

Sur les 3 images tout est fonctionnel.

Maintenant, avec la dernière béta:
![im1-nouveau](https://user-images.githubusercontent.com/80746871/116999591-e17b1300-acf0-11eb-8f9b-cde2800636fe.JPG)

![im2-nouveau](https://user-images.githubusercontent.com/80746871/116999614-e6d85d80-acf0-11eb-97bf-31f639c66216.JPG)

![im3-nouveau](https://user-images.githubusercontent.com/80746871/116999627-eb9d1180-acf0-11eb-84bc-27f163ce9784.JPG)

Bonne journée.

**Comment by sizanic** [comment]
Avec cette version, il faut défnir l'action par défaut:
![image](https://user-images.githubusercontent.com/47307622/117012763-8eed2700-acef-11eb-80c5-48827363f7a1.png)



Avant ce n'était pas pris en compte, mais maintenant il faut faire attention à ce qui est paramétré.

Dans cet exemple, l'action par défaut est sur "voir les informations", il faut choisir "lire" sinon.

**Comment by Rick407** [comment]
Oui je suis d'accord avec toi et j'avais déjà testé comme cela, mais... inconvénient on perd (dans l'affichage prévu) le "design" à la N...IX, comme sur l'image 5.
La il va (comme sur le skin par défaut) lancer la série après choix du hoster.
J'aimais bien l'affichage que je pouvais avoir façon N...ix, mais le plus important c'est que ça fonctionne ;)

Cette mise à jour permet maintenant de bénéficier des méta (qui ne s'affichaient pas sur tous les sites) avec les séries au même titre que les films (c'est du moins ce que j'observe). Or quand je vais sur une série (sur TMDB), j'ai aussi le résumé de l'épisode, ce que nous n'avons pas avec les différents sites. Est ce possible... dans le futur d'aussi les récupérer? Ce serait pas mal je trouve.
Quand pensez vous?
Encore bravo aux dev, pour le travail fourni.

**Comment by sizanic** [comment]
Pour la gestion de l'image 5, on a encore du travail pour que ça colle avec le skin.
Quant aux résumés des épisodes, c'est également un développement qui est prévu.

**Comment by sizanic** [comment]
L'état actuel de vStream ne permet pas mieux.
Pas de dysfonctionnement en utilisant les bonnes options.
Ce ticket peut être fermé.
