### ISSUE TITLE
Synchronisation DB Vstream entre plusieurs KODI

### ISSUE THREAD

**Issue by osmoze06** [Kodi-vStream/venom-xbmc-addons#3288]
Demande d'évolution concernant la synchronisation de la base de données Vstream entre plusieurs appareil d'un même réseau.

Le but étant d'arriver à faire la même chose que en natif sur Kodi via MySQL, à savoir : 

- La reprise de lecture (nouvelle fonction de la beta) sur un autre périphérique (des sources PasteBin, car les autres sources, ça fonctionne déjà)
- La synchronisation des marques pages

(A voir si il y a la possibilité de modifier le chemin d'accès à la DB pour la placer sur un chemin réseau en passant par advancedsetting.xml).

En vous remerciant pour votre aide sur ce sujet qui peut être intéressant 😉

**Comment by alKODIque** [comment]
Je lis ceci et puis je me dis, au lieu de développer un genre de stockage cloud complexe de bd vStream, pourquoi ne pas simplement utiliser une fonctionnalité déjà existante et très performante qui existe déjà à l'intérieur de vStream??

Je parles de Trakt!
l'option "ajouter a la liste de suivi" est exactement ce que fait les marques-pages: c'est la même chose.

De plus, c'est accessible via le menu contextuel de vStream. 

tout ce dont nous avons besoin c'est un compte Trakt connecté à vStream. 

Le classement, ensuite, se fait seul selon l'item. Soit film, séries, saison et même épisode si on le souhaite.

Nous pouvons aussi ajouter notre "watchlist" (liste  suivie) comme widget! 
en fait, marque-pages  =  liste de suivi...

(via le menu contextuel de vstream, il suffit de choisir Trakt, puis "Ajouter à liste à surveiller "

Nous pouvons ensuite retrouver nos "marques-pages" trakt sur tous nos apoareils et ce, non seulement pour cStream, mais peu importe l'outil utilisé pour visionner un média si ce dernier est également connecté à notre compte trakt..

**Comment by alKODIque** [comment]
J'en ajoute loll

En bonus, tu obtiendras des options super cool sans efforts que jamais les marques-pages de vstream vont t'offrir... comme le calendrier des prochines sorties télé! 
Lorsque tu ajoute une série a ta liste de suivi, le guide horaire vient automatiquement... Et tu le retrouveras aussi sur tous tes autres installations kodi si tu les connecte également a Trakt:

![screenshot00075](https://user-images.githubusercontent.com/49578130/117725380-0ec53680-b1b3-11eb-9f8f-796adec7123d.png)
![screenshot00076](https://user-images.githubusercontent.com/49578130/117725382-0f5dcd00-b1b3-11eb-8d77-e658c802c970.png)
![screenshot00078](https://user-images.githubusercontent.com/49578130/117725383-0f5dcd00-b1b3-11eb-83ba-76e2c80e40e0.png)

**Comment by alKODIque** [comment]
@sizanic ,
malheureusement, je ne peux pas te confirmer a 100% ta dernière question car je n'ai pas encore réussi à tout comprendre ce qui se passe pour mon intégration pour pouvoir affirmer sans le moindre doute que c'est bien le cas... j'ai encore des trucs à valider loll mais une chose est certaine: absolument tout ce qui est ajouté a la liste de suivi trakt se retrouve partout ou pas n compte trakt est connecté. que ce soit vStream, kodi, Emby, peu importe et ce, sur n'importe quel appareil.

**Comment by alKODIque** [comment]
j'oubliais.. la collection Trakt, ce n'est pas la liste de suivi trakt (watchlist) en gros, la collection represente les médias que l'on possède. La watchlist représente les médias que l'on suit!
Nous pouvons prendre un média faisant partie de notre collection et l'ajouter a notre watchlist (pratique pour les séries) et cest un peu l'effet de l'intégration de ces 2 éléments distincts que j'ai besoin de tester encore pour exactement cibler ce que chacun fait et ne fait pas....

**Comment by sizanic** [comment]
> car les autres sources dispos sur Vstream ça marche déjà

Tu as modifié l'emplacement des base de données de kodi ?

**Comment by osmoze06** [comment]
... bon en effet, je comprends pas comment ça marche Takt. Je l'ai installé partout et associé mon compte mais je vois pas comment je peux reprendre la lecture entre mes différentes TV.  Help me please 😂

**Comment by alKODIque** [comment]
En faisant quelques tests, j'ai trouvé un gros défaut à l'utilisation de la watchlist de Trakt en tant que marque-pages...

En effet, le piètre soutien en langue française du site Trakt a pour effet qu'il arrive fréquemment, lorsque nous ajoutons un film ou une série à notre watchlist, que nous nous retrouvons avec un film différent en bout de ligne... 

Par exemple, si en navigant dans vStream, on ajoute le film "Désolation" à notre watchlist Trakt, on se retrouve plutôt avec un film qui n'a aucun lien: soit le film "Le canyon des bandits" loll

Avec les marque-pages en natif de vStream, ceci n'arrive pas! nous avons toujours le bon média

**Comment by osmoze06** [comment]
Hello, bon, j'ai testé la méthode Trakt, ça fonctionne avec avec la source PasteBin : Il me dis bien quel est le prochain épisode à voir par la suite grâce au widget configuré.

Cependant, la position de lecture n'est pas retrouvé pour les films et les séries en cours de visionnage pour PasteBin...

Je ne peux pas non plus me servir des marque-pages Vstream car pas synchronisable contrairement au fichier "favourites.xml".

La seule solution fonctionnelle est de copier/coller le dossier vstream d'addon_data dans mes autres périphériques... Autant vous dire que c'est pas pratique du tout.
J'utilise un .bat pour ce faire pour l'instant... Mais si l'on pouvait simplement redéfinir le chemin de la base de donnée, ça pourrait être une belle avancé pour ceux qui ont plusieurs périphériques ;-)
