### ISSUE TITLE
UpNext - Enchainement des épisodes - A TESTER

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#3292]
Bonjour,

L'enchainement des épisodes est fonctionnalité prévue dans la prochaine version de vStream.

Pour valider son bon fonctionnement sur l'ensemble des sources de vStream, une aide serait la bienvenue.

**QUOI**
Le fonctionnement attendu : 
- le prochain épisode est proposé dans les 30 dernières secondes (se change dans l'addon upnext)
- le même hoster est utilisé
- la même langue est proposée (VF/VOSTFR/..)
- la même qualité est proposée

**COMMENT**
Je ne précise pas comment installer les modifications à tester car cela s'adresse à ceux qui savent.

Pour tester, il faut laisser écouler la vidéo au moins 10 secondes (pas forcement depuis le début).

Le premier épisode que vous lancez (pas forcement le premier de la saison) doit démarrer en moins de 5 secondes.
Ceci est une contrainte de l'extension upNext.
Pour lever cette contrainte (en cas de démarrage long), vous devez mettre en place ces deux modifications :

https://github.com/im85288/service.upnext/commit/817589a7d9b49b079a7dd8a6d10e62e2f0d5d180
(en espérant qu'elles soient rapidement disponibles dans une prochaine version)

### Sources déjà testées et opérationnelles
- 4k stream z
- Ad kami
- asia Insane
- cine may
- cine may_cc
- cine mey
- DDL
- db animes
- DP stream
- DP stream HD
- en stream (series)
- Extrem Down
- French stre am
- French Stre am_lol
- film Stream VK
- Funeral for a manga
- gum gum stream ing
- hds _fm
- hds stream
- i anime
- illimite strea ming
- k strea ming
- k Strea ming Serie
- LibertyLand
- neko sama
- o1 serie stre aming
- o1 strea ming
- pastebin
- serie strea ming
- series en strea ming
- Séries Stream
- stream complet
- strea ming series
- sky animes
- TV Serie Strea ming
- vf serie
- Voir films
- Voir series
- wi flix
- zu stream
- zu stream series

### Sources qui ne reprennent pas la bonne langue dans l'épisode suivant : 
- wiflix

### Sources qui ne reprennent pas le même hoster dans l'épisode suivant : 
-   stream pour vous

### Sources qui ne reprennent pas la même qualité dans l'épisode suivant : 
- Pastebin lorsque la qualité est sur le lien direct, OK si résolution au niveau de la série

### Sources qui ne gèrent pas l'enchainement : 
- ...

Dans l'attente de vos retours.

**Comment by Rick407** [comment]
Bonjour,

Un petit retour après un premier test effectué ce matin après installation de la béta.
J'ai aussi effectué les 2 modifications demandées au niveau de monitor et player de Up next.

Source: hds _fm
Série: Hand maid ...
Hoster: Uq load
Langue : VF
Episode1.

Le fonctionnement de UP next est pris en compte avec une info affichée 45s avant la fin de l'épisode (dans mon cas dans le générique).
A la fin du décompte, quelques secondes (moins de 5s) et l'épisode 2 est lancé.

Conclusion: fonctionnement OK avec la source choisie, avec bonne prise en compte de la série, l'épisode , la langue et le hoster.

En revanche, l'affichage comporte, chez moi, une ligne supplémentaire comme sur la photo ci-dessous et je trouve l'affichage un peu haut. Ce n'est pas gênant pour le fonctionnement de Up next mais il est vrai que l'on ne voit pas très bien ce qui est écrit et de plus l’écriture en blanc sur générique blanc, on a du mal à voir (peut être une autre couleur pour l'affichage).

Voici pour mon petit retour.
Bonne journée.
![IMG_20210515_104350](https://user-images.githubusercontent.com/80746871/118352147-e8b3e380-b570-11eb-823e-feaf7fc22d47.jpg)

**Comment by Nash233** [comment]
bonjour,
testé avec la source pastebin   Bloodlands s01 e03 a 04 en hd.
Aucun probleme , message a 20 secondes avant fin ( j ai renseigné cette duree dans l addons) et enchainement parfait...beau taf :) je continue et posterai en cas de soucis ;)

**Comment by sizanic** [comment]
Merci pour vos premiers retours.

L'affichage est géré par l'extension UpNext. Je pense que l'extension attend une image de fond mais vStream ne propose pas toujours de pochette (dépend de ce que donne le site).
Change dans le paramètre de l'extension pour mettre en mode simple.

Pour les sites que vous avez testé, je sais déjà que hds _fm et pastebin sont fonctionnelles, je les ai mis dans la liste.

j'ai déjà testé 13 sources tout seul et c'est beaucoup de travail, c'est donc de l'aide sur les autres sources dont j'ai besoin.

**Comment by sizanic** [comment]
Je viens de tester et validé : 
- en stream (series)
- db animes
- wi flix

**Comment by sizanic** [comment]
13 nouvelles sources de validées !

J'en suis à 26 sources compatibles.
Avec prise en compte des sites d'animes japonais, avec des séries qui n'ont pas forcement de saisons.

**Comment by sizanic** [comment]
C'est fini !
43 sources compatibles avec l'enchainement des épisodes !!!

**Comment by sizanic** [comment]
Disponible dans la dernière version 1.2.0.
