### ISSUE TITLE
recherche avancée

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3293]
Merci encore pour votre super boulot.
La recherche globale sur toutes les sources, mériterait  une belle avancée...

Ne pourriez-vous pas développer en résultat de cette recherche, un tri proposant la meilleure définition possible ? (720P , 1080P  etc..)
J’ignore si techniquement ce projet est  réalisable car je constate souvent des fichiers 1080P qui  en réalité, ne le sont pas. 

Salutations

**Comment by TmpName** [comment]
Ben tu as repondu toi meme ^^
On ne peut pas se fier non plus aux infos données par les sites. Vstream fonctionne comme un moteur de recherche, a partir d'un titre il cherche des liens, mais sans garanties.
Par contre par rapport aux sites qui proposent des resultats, tu peux avoir l habitude de preferer la qualité de l'un ou de l'autre.

**Comment by lil78711** [comment]
pour moi la fonction recherche met tres longtemps que j'abandonne de suite

**Comment by sizanic** [comment]
@lil78711 
> pour moi la fonction recherche met tres longtemps que j'abandonne de suite

Si ta recherche met trop longtemps c'est sans doute parce que la recherche est réalisée sur tous les sites proposés par vStream.

Un paramètre de vStream permet de choisir les sites utilisés par la recherche.
Ne laisser actifs que 5 sites suffit pour un résultat satisfaisant.
A toi d'aller les sélectionner.

Il est aussi connu qu'un mauvais paramétrage de DNS peut ralentir la recherche.

**Comment by sizanic** [comment]
@kris06 

Des modifications sur le moteur de recherche globale sont prévues.
Je t'invite à venir de nouveau nous faire part de tes impressions lorsqu'elles seront en place.

Par contre, elles ne concerneront pas un classement par qualité. Cela n'est pas possible, l'information fournie par les sites n'est pas pertinente.
