### ISSUE TITLE
playtube ne fonctionne pas

### ISSUE THREAD

**Issue by olliedarou** [Kodi-vStream/venom-xbmc-addons#3294]
ici qui fonctionne

https://github.com/vb6rocod/utils/blob/master/servere/tear_js.html

**Comment by TmpName** [comment]
Je peux m'occuper de la convertion, mais tu aurais un site qui propose cet hebergeur ?

**Comment by TmpName** [comment]
Bon j'ai trouvé un site "funeral for a manga", mais les video ne marchent pas, pas moyen d'en lancer une, meme avec lanti pub desactivé, et ca deconne encore plus sur firefox que Chrome.
Pour moi poubelle.

**Comment by sizanic** [comment]
> Bon j'ai trouvé un site "funeral for a manga", mais les video ne marchent pas, 

Cette source est déjà présente dans vStream, avec des vidéos qui se  lancent 🤔

**Comment by TmpName** [comment]
Ha ?
Bon ok, du coup c'est que ca vient du site, pas de l herbergeur ?
