### ISSUE TITLE
Problème extreme down sur Vstream

### ISSUE THREAD

**Issue by fabdu31** [Kodi-vStream/venom-xbmc-addons#3295]
Bonjour à tous,
Je suis tout nouveau sur vstream et je rencontre un problème avec extreme down sur Vstream
Tout fonctionne correctement jusqu'à l'affichage des différents hosters (Uptobox, uploaded, ...).
Mais quand je clique sur un des hosters il ne se passe rien!
J'utilise alldebrid et j'ai rentré la bonne clé dans vstream et dans urlresolver.
Quelqu'un peut-il m'aider?
Merci d'avance!

**Comment by fabdu31** [comment]
ci-joint le fichier d'extreme down que j'ai trouvé dans vstream.
Y a t il des modifications à apporter?
[extreme_down.docx](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6501125/extreme_down.docx)

**Comment by Niconimes** [comment]
Salut, personnellement ça fait très longtemps que j'ai laissé tomber cette
source malheureusement car on y trouve de tout et tous types de formats
mais avec mon débrideur ça fait très longtemps que ce n'est plus
fonctionnel. Comme pour toi je ne peux rien lancer, aucun lien ne s'affiche
quand tu cliques sur le nom de l'hoster. Par dépit je me suis rabattu sur
Wiflix qui est très correct sans pour autant égaler Extreme Down mais ça
fait le job. J'attends quand même de voir si un des toliers de Vstream te
répond, ce sera intéressant.

**Comment by sizanic** [comment]
Bonjour,

> ci-joint le fichier d'extreme down que j'ai trouvé dans vstream.
Y a t il des modifications à apporter?


Merci pour ce fichier, on le connaît bien, le fichier original vient de ce site ici-même 😄 
Tu peux le retrouver ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/plugin.video.vstream/resources/sites

Le fichier présent ici est d'ailleurs plus récent. Plusieurs modifications ont déjà été apportées depuis la version que tu as : 
https://github.com/Kodi-vStream/venom-xbmc-addons/commits/aa364827bc7b86989253abd5fd679a92df854fb7/plugin.video.vstream/resources/sites/extreme_down.py


Cela veut dire que des modifications ont déjà été apportés.
Il te faut maintenant attendre la prochaine version pour en profiter.

**Comment by Niconimes** [comment]
Salut Sizanic,

Cela veut donc dire que les liens sur ce site vont à nouveau être
fonctionnels sur la prochaine mise à jour? Si on télécharge la bêta ce
serait déjà actif?

**Comment by fabdu31** [comment]
Bonjour Sizanic,

Si je remplace le fichier .py par le dernier (tout en enlevant les lignes rouges) extreme down devrait marchait?

**Comment by sizanic** [comment]
il n'y a pas de lignes rouges si tu prends la dernière version du fichier (mon premier lien).

Mais peut-être que cette modification pourrait suffire : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/dca56ff812d4c93ccfd22145e7aed08c5a4143bc#diff-62ecb08ece2f3e0ca914ce336ecc5c8ffa371ddbdc4c83f549da95a2cb76731c

**Comment by sizanic** [comment]
> Salut Sizanic, Cela veut donc dire que les liens sur ce site vont à nouveau être fonctionnels sur la prochaine mise à jour? Si on télécharge la bêta ce serait déjà actif?

il y a des chances que ces modifications aient été mises-là pour quelque chose 🤔 
Tentes la Beta.

**Comment by Niconimes** [comment]
Super, merci je testes tout de suite et je reviens donner le résultat.

**Comment by Niconimes** [comment]
Bon je viens de tester :

1) lorsqu'on utilise la fonction: film / derniers ajouts les titres
apparaissent avec la qualité de celui ci et si on clique dessus rien ne
s'ouvre
2) lorsqu'on fait une recherche avec un titre les résultats s'affichent, si
on clique dessus on arrive au nom de l'hoster et lorsqu'on relique dessus
ça fait le même bug que Wawacity: des images à valider qui tournent en
boucle (genre captcha en photos) et impossible d'arriver à ouvrir le lien

**Comment by sizanic** [comment]
J'ai testé un lien uptobox car j'ai un compte et c'est bon.
Sinon, il faut utiliser un token alldebrid, même un token gratuit suffit.

Dans le cas de l'utilisation d'un token gratuit alldebrid, il faut le renseigner mais il ne faut pas cocher "Actif".

**Comment by Niconimes** [comment]
Perso je passe par un compte Real debrid tu penses que ça vient de là ?

**Comment by sizanic** [comment]
Attention lorsque tu nous réponds, il y a ton lien pour te désabonner, on est incité à cliquer dessus : 
![image](https://user-images.githubusercontent.com/47307622/118672733-c207de00-b7f8-11eb-8815-fa640669fe43.png)

**Comment by sizanic** [comment]
Mais avec toute la Beta ou juste une modification du fichier ?

**Comment by Niconimes** [comment]
J'ai installé la Bêta

**Comment by Niconimes** [comment]
> Mais avec toute la Beta ou juste une modification du fichier ?

J'ai installé la bêta. (Tu vois toujours mon lien de désinscription là ?)

**Comment by fabdu31** [comment]
Bon y'à rien à faire j'ai tout essayé...
J'ai essayé de changé le fichier .py avec tes liens...
J'ai essayé la version beta de vstream...
Et toujours pareil quand je clique sur les hosters il ne se passe rien...
Je ne comprends pas pourquoi...

**Comment by Niconimes** [comment]
> Bon y'à rien à faire j'ai tout essayé...
> J'ai essayé de changé le fichier .py avec tes liens...
> J'ai essayé la version beta de vstream...
> Et toujours pareil quand je clique sur les hosters il ne se passe rien...
> Je ne comprends pas pourquoi...

Pareil chez moi

**Comment by sizanic** [comment]
Extrem Down / Films / Nouveautés 2021 / Fast Color / Fast Color (french HDRip) / uptobox -> Le film démarre

**Comment by fabdu31** [comment]
Pas chez moi... Tu as de la chance...
Y a un réglage à faire dans les paramètres ?

**Comment by Niconimes** [comment]
> Extrem Down / Films / Nouveautés 2021 / Fast Color / Fast Color (french HDRip) / uptobox -> Le film démarre

Je viens de tester en prenant le même chemin et je me retrouve bloqué par ce "captcha" en images... Tu utilises la version Android ou Windows ?

**Comment by Niconimes** [comment]
Sachant que je n'utilise pas Alldebrid mais Real Debrid

**Comment by fabdu31** [comment]
Moi je n'ai même pas de captcha...
Je suis sous android TV (Nvidia Shield) avec alldebrid

**Comment by sizanic** [comment]
En effet, si je ne laisse que mon token alldebrid en désactivant mon compte uptobox, je ne peux plus lancer le film.

Pour realDebrid, je ne peux rien dire.

**Comment by Niconimes** [comment]
> En effet, si je ne laisse que mon token alldebrid en désactivant mon compte uptobox, je ne peux plus lancer le film.
> 
> Pour realDebrid, je ne peux rien dire.

Pour Uptobox c'est aussi un compte premium que tu as rentré ?

**Comment by fabdu31** [comment]
Pour ma part j'ai un compte premium uptobox et un compte premium alldebrid (tout deux rentrés dans les paramètres de vstream)

**Comment by fabdu31** [comment]
Il n'y a pas que extreme down qui ne fonctionne pas...
Free telechargement, Tirexo, Zone téléchargement et surement d'autres ne fonctionnent pas également...

**Comment by Niconimes** [comment]
> Pour ma part j'ai un compte premium uptobox et un compte premium alldebrid (tout deux rentrés dans les paramètres de vstream)

Si t'as un Alldebrid premium, je ne vois pas trop l'intérêt d'avoir aussi Uptobox en premium

**Comment by Niconimes** [comment]
> Il n'y a pas que extreme down qui ne fonctionne pas...
> Free telechargement, Tirexo, Zone téléchargement et surement d'autres ne fonctionnent pas également...

Le même constat chez moi, voilà pourquoi j'ai basculé sur Wiflix

**Comment by sizanic** [comment]
Peut-être un probleme avec alldebrid/extremDown, essayes avec juste uptobox.

**Comment by fabdu31** [comment]
idem ça ne fonctionne pas

**Comment by fabdu31** [comment]
c'est dommage c'est les meilleurs sources qui ne fonctionnent pas...

**Comment by fabdu31** [comment]
sais-tu s'il y a un tuto de disponible pour tout reinstaller afin que toutes les sources refonctionnent?
- vstream
- alldebrid
- urlresolver
- ....

**Comment by sizanic** [comment]
vStream porpose des liens mis à disposition par des sites qui : 
- changent d'adresses constamment
- ajoutent des protections
- changent le format des pages
- ...

Il n'y a aucune formule magique pour que tout refonctionne d'un coup !

Des modifications sont apportées à vStream pour suivre les modifications apportées par les sites.
Il faut attendre les mises à jour de vStream pour en profiter, le temps que les sites remettent de nouvelles protections.

**Comment by fabdu31** [comment]
ça je suis tout à fait d'accord.
Mais comment ça se fait que ça marche toi et pas chez moi??

**Comment by fabdu31** [comment]
ça je suis tout à fait d'accord.
Mais comment ça se fait que ça marche chez toi et pas chez moi??

**Comment by sizanic** [comment]
Parce que je passe par Uptobox et avec la Beta d'aujourd'hui.

**Comment by lebigboss** [comment]
Chez moi la source à toujours fonctionné, je l'utilise tous les jours sans problème avec Alldebrid.
C'est même devenu la source la plus fiable chez moi.
J'utilise souvent les bêtas

**Comment by fabdu31** [comment]
Bonjour le big boss
Je vois que que ça marche chez plusieurs personne. Il doit y avoir des réglages que j'ai mal fait...
Passes-tu également par URL resolver? Si oui quelle version? De quelle source?
Quel apikeys de alldebrid a-tu-mis dans les réglages de Vstream? C'est bien celle ayant pour nom ftp?
Merci de votre aide

**Comment by lebigboss** [comment]
Non j'utilise directement Alldebrid et bon ça fait plus de 1 an que j'ai rien changé mais normalement il faut juste prendre le token Alldebrid et l'ajouter

**Comment by fabdu31** [comment]
Qu'appelles-tu le token Alldebrid? Où est-ce que tu le trouves? Est-ce la même chose que l'apikeys?

**Comment by fabdu31** [comment]
Bonjour. Quelqu'un pour m'aider?

**Comment by yodidon** [comment]
Pour le token de alldebrid ?

**Comment by fabdu31** [comment]
oui

**Comment by yodidon** [comment]
Je n’utilise pas alldebrid mais j’imagine que sur ton interface alldebrid de ton compte tu dois pouvoir récupérer le token ?

**Comment by fabdu31** [comment]
Sais-tu si c'est la même chose que l'apikeys (ou clé API)

**Comment by Arias800** [comment]
Tu peux la trouver ici : https://alldebrid.fr/apikeys/
(il faut choisir celle nommée "service" ou en faire une, c'est au choix).

**Comment by yodidon** [comment]
Techniquement s on parle de token, c’est pas api key enfin à mon avis

**Comment by fabdu31** [comment]
ok!! Je teste merci beaucoup Arias800!!

**Comment by fabdu31** [comment]
Je n'avais pas inscris la bonne. J'avais rentré la clé ftp...

**Comment by yodidon** [comment]
Merci arias800 , donc c’est l’api key

**Comment by Arias800** [comment]
Effectivement, ça ne pouvait pas fonctionner.
Il faudrait que je fasse une documentation détailler, ça pourrait aider.

**Comment by fabdu31** [comment]
ça j'avoue je serai bien preneur!!!

**Comment by fabdu31** [comment]
bon ça ne change rien.  ça ne marche toujours pas.
J'ai installé la dernière version bêta de vstream. 
Changé mon token alldebrid comme Arias me l'a conseillé dans les paramètres de vstream.
Rentré mon identifiant et mot de passe uptobox dans les paramètres de vstream.
Configurer url resolver pour l'associer avec alldebrid.
Je n'arrive toujours pas à lancer les films sur extreme Down..
Pourquoi??

Arias800 si un jour tu as le temps de faire une doc détaillée pense à moi!

**Comment by Arias800** [comment]
Je vais reprendre depuis le départ.
Tu as un compte premuim alldebrid et uptobox rentré dans Vstream, donc tu n'as pas besoin d'Url Resovler.
Ensuite la clé, il faut la rentrer dans token.
![image](https://user-images.githubusercontent.com/24809312/119269698-4a232480-bbf9-11eb-997f-df93bd96b26e.png)

Maintenant tu devrais ne plus avoir de problème.

**Comment by fabdu31** [comment]
OK. J'ai désactiver url resolver.
J'ai vérifié j'ai bien rentré la clé alldebrid dans token.
Mais le problème persiste...

**Comment by fabdu31** [comment]
Je suis sous android TV (avec Nvidia Shield) est ce que cela pourrait venir de là?

**Comment by Arias800** [comment]
Non, normalement ça fonctionne correctement sous Android.
Décoche "Activer" pour Alldebrid.
![image](https://user-images.githubusercontent.com/24809312/119270250-11d11580-bbfc-11eb-8eee-699bce113e02.png)

**Comment by fabdu31** [comment]
ça ne change rien.
J'ai essayé plusieurs films (les derniers ajoutés et nouveauté 2021) et rien à faire.
Je vois la liste des différents hosters. Mais quand je clique rien ne se lance.

**Comment by Arias800** [comment]
Il me faut les logs. Utilise l'addon Kodi logfile Uploader et donne moi le lien.

**Comment by fabdu31** [comment]
Je n'y arrive pas non plus.
J'ai un message d'erreur : "Error posting the kodi.log file. This file is too large. Max size is 1MB."

**Comment by Arias800** [comment]
Bon, il va falloir le récupérer manuellement. Voilà le chemin pour accéder au fichier kodi.log : Android/data/org.xbmc.kodi/files/.kodi/temp

**Comment by fabdu31** [comment]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6528635/kodi.log)
[kodi.old.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6528637/kodi.old.log)

Je t'envoie les deux fichiers log présents dans les temp.
Encore merci de ton aide!!

**Comment by Arias800** [comment]
Il faut reproduire le bug avant de donner les logs (j'ai oublié de le préciser).

**Comment by fabdu31** [comment]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6528670/kodi.log)

Désolé je ne savais pas.. Je pensais que ça gardais en mémoire tout les bugs.
J'ai fait plusieurs manip avec et sans alldebrib / uptobox / urlresolver
J'espère que tu trouveras quelque chose...

**Comment by Arias800** [comment]
À chaque démarrage Kodi vide les logs précédent, pour éviter qu'ils soient trop gros.
Il y a une erreur, c'est déjà un bon début.
![image](https://user-images.githubusercontent.com/24809312/119272408-f8cd6200-bc05-11eb-9161-1ca355053ff9.png)

Visiblement, il y a un problème avec le token, remplace le fichier extreme_down par celui-là : https://github.com/Arias800/Fichier-divers/blob/master/extreme_down.py
et réessaye. Si ça ne fonctionne pas redonne-moi les logs et j'aurai plus d'information.

**Comment by fabdu31** [comment]
C'est quoi déjà le chemin de extreme_down.py?

**Comment by Arias800** [comment]
Normalement, c'est ca : Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites

**Comment by fabdu31** [comment]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6528765/kodi.log)

Toujours rien. Ci-joint nouveau log toujours avec plusieurs manip avec et sans alldebrib / uptobox / urlresolver

**Comment by Arias800** [comment]
Je m'en doutais, je regarde les logs et je te tiens au courant.

**Comment by fabdu31** [comment]
OK c'est super sympa. Merci beaucoup!

**Comment by Arias800** [comment]
Comme je m'en doutais, il y a bien un problème au niveau du token.
`{'status': 'error', 'error': {'code': 'AUTH_BAD_APIKEY', 'message': 'The auth apikey is invalid'}}`
Essaye en faisant ton propre token.
Sur https://alldebrid.fr/apikeys/, tu tapes un nom, par exemple Vstream et ça va te générer une nouvelle clé.
![image](https://user-images.githubusercontent.com/24809312/119274048-3cc46500-bc0e-11eb-8572-75f76d5d73fa.png)

**Comment by fabdu31** [comment]
Ok je vais essayer. Je garde le fichier extreme_down.py  que tu m'as envoyé?
Ou je remets celui de la beta?

**Comment by Arias800** [comment]
Tu peux remettre celui de base, le mien avait juste pour but d'afficher la réponse du site (pour avoir une idée plus précise du probleme).

**Comment by fabdu31** [comment]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6528896/kodi.log)

Bon j'ai créer le nouveau token que j'ai rentré sur vstream.
Toujours rien.
J'ai l'impression que c'est toujours un problème AUTH_BAD_APIKEY
De plus je ne sais pas si c'est normal mais il n'y a rien dans la colonne dernière IP sur alldebrid lors de la création de la nouvelle clé ni sur dernier client.
Ci-joint nouveau log. Pour info c'est toujours la version extreme_down.py que tu m'as envoyé
