### ISSUE TITLE
Channel stream

### ISSUE THREAD

**Issue by us-mereau** [Kodi-vStream/venom-xbmc-addons#3296]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Android]
-  Appareil [fire tv, smartphone xiaomi et tablette samsung]
 - Version Kodi  [19.1]
- Version Vstream 1.1.0

**Nous devons le reproduire**
Dans TV/musique, TV (source), La source Channel stream ne semble plus fonctionner sous appareil Android du moins.

**Comment by TmpName** [comment]
@Arias800 vient de faire une modif qui a resolu des problemes de mon coté, essayes avec le dernier fichier pour voir > https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/channelstream.py

**Comment by sizanic** [comment]
Je ne pense pas que récupérer seulement ce fichier peur suffire, j'ai fait d'autres ailleurs, récupérer toute la beta est préférable pour valider le bon fonctionnement.

**Comment by f28gin** [comment]
bonsoir à tous !
je confirme que le fichier modifié de @Arias800 corrige le problème !!

merci beaucoup

**Comment by us-mereau** [comment]
Étant quelque peu novice pourriez vous expliquer comment utiliser le fichier modifié de @Arias800  dans vStream sous Android ?

**Comment by yodidon** [comment]
Tu peux installer la bêta tu auras les dernières modifs

**Comment by us-mereau** [comment]
Yodidon, où tu trouve cette bêta et comment tu l installe. Car comme déjà indiqué je suis novice. Il faut installer ça comme une nouvelle source ?

**Comment by yodidon** [comment]
> Yodidon, où tu trouve cette bêta et comment tu l installe. Car comme déjà indiqué je suis novice. Il faut installer ça comme une nouvelle source ?

Tu as en bas de page https://github.com/Kodi-vStream/venom-xbmc-addons télécharger la bêta, tu installes via kodi fichier zip

**Comment by us-mereau** [comment]
merci Yodidon, ça fonctionne sur smartphone et tablette mais impossible de télécharger la bêta sur ma fire stick.

**Comment by yodidon** [comment]
Je n’ai pas de fire  stick stick, mais si tu as le zip, je tu ne peux pas utiliser une application de transfert de fichier en wifi par exemple ?

**Comment by us-mereau** [comment]
Merci, problème résolu avec adblink qui permet de connecter un PC a sa fire stick et d'y installer des fichiers.

**Comment by us-mereau** [comment]
Bonjour a tous, 
Il semblerait que les chaînes soit qqpeu mélangées sur channelstream bêta.
Canal cinéma c'est une chaîne histoire, OCS Max c'est Nickelodeon et sûrement d'autre je n'ai pas tous regardé. Une mise à jour est prévue ?

**Comment by sizanic** [comment]
Bonjour,
En effet, mais vStream ne fait que proposer les chaines du site officiel channelstream.
Et c'est comme ça sur leur site.

Je l'ai signalé sur leur Discord : https://discord.gg/2J4z6yy
