### ISSUE TITLE
Impossible d'installer vStream depuis le repo

### ISSUE THREAD

**Issue by c2haches** [Kodi-vStream/venom-xbmc-addons#3298]
Salut, je sais pas si c'est un bug à proprement parler et si le type d'issue est le bon mais je me lance quand même.

**Décrivez le bug**
Je n'arrive tout simplement pas à installer vStream depuis le repo en addon.
C'est-à-dire que j'ai réussi à installer le repo depuis l'option "Install from zip file", mais lorsque je vais chercher l'extension "vStream Repository", on ne me propose pas de l'installer mais seulement de désinstaller l'addon. 

**Votre system**
- OS: Android
- Appareil : Firestick TV
- Version Kodi : [18.6]  ARM 32bits
- Version vStream : 0.0.4

**Plus**
J'ai cherché le .zip depuis les releases sur Github : https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.0.3
J'ai également essayé de changer de version de Kodi (j'étais sur la v19 avant de passer sur la 18.6).
Mon Kodi est clean, dans le sens où je n'ai rien dessus, la première chose que j'ai faite après l'avoir installé c'est d'essayer d'ajouter vStream

![IMG20210525011439](https://user-images.githubusercontent.com/84750537/119417933-33fb8e00-bcf7-11eb-9aaf-e077aca2e212.jpg)
La photo est catastrophique mais je pense qu'elle parle d'elle-même : je ne peux pas installer vStream mais seulement désinstaller le repo.

C'est certainement tout bête comme problème, si ça se trouve y'a des étapes entières que j'ai sauté mais je vous avoue que je suis un peu bloqué, j'ai essayé de faire quelques recherches de mon côté mais ça n'a rien donné

**Comment by sizanic** [comment]
Salut.
"Install from zip file" permet d'installer le repo.
Pour installer vStream, maintenant que tu as installé le repo, il faut aller dans "installer depuis un repo" 🤔

**Comment by c2haches** [comment]
Bon Dieu je me sens incroyablement con.
Je savais que ça devait être un truc complètement débile du genre.

En tout cas merci, ça marche impec !
