### ISSUE TITLE
Bug ianime

### ISSUE THREAD

**Issue by Fullpom** [Kodi-vStream/venom-xbmc-addons#3299]
**Décrivez le bug**
Salut, les dossiers utilisant la sélection alphabétique sur le site ianime comme la section animé VF ne semble pas marcher.

**Votre system**
 - OS: [Android, xbmc, recalbox]
-  Appareil [redmi note 5, android tv, xbox one, rpi3]
 - Version Kodi  [19, 18.9]
- Version Vstream [1.1.0]

**Nous devons le reproduire**
Pour cela il nous faut:
- Ianime

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by TmpName** [comment]
Hello, essayes cette version si tu peux https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/ianime.py

**Comment by Fullpom** [comment]
Ça fonctionne, ou comment être rapide et efficace 👍. Merci beaucoup.
