### ISSUE TITLE
Lecture d'un flux m3u8

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#3302]
Salut,
J'essaie de remettre en place une source, qui me renvoit un fichier m3u8 que KODI n'arrive pas à lire.

Voici un exemple : 
http://103 .155. 93. 239/hls/f762999e701fc61285816b4cd2f7a10c/f762999e701fc61285816b4cd2f7a10c.m3u8
(sans les espaces dans l'adresse ip)

Mais Kodi n'arrive pas à le lire, ni VLC.
Il m'a pourtant l'air correct, surtout que chaque ligne du fichier prise individuellement se lit correctement dans VLC.

Une idée ?

**Comment by Arias800** [comment]
C'est les mêmes liens que Kepliz, c'est du pair-to-pair donc kodi et VLC ne savent pas les lires.

**Comment by TmpName** [comment]
D'ailleurs a ce sujet tu as des pistes de ton coté @Arias800 ?

Quelqu'un avait trouvé des sites Web avec des lecteurs online ou le fichier etait lisible, donc c'est possible en passant par un lecteur externe, mais imposible avec un lecteur local.
Dans la mesure ou kodi ne fait rien de plus que se baser sur le code des lecteurs locaux, j'ai peu d'espoir mais ca fait une sacré faille quand meme ...

**Comment by Arias800** [comment]
J'ai trouvé le lecteur de base de l'herbegeur, mais pour le moment il n'y rien n'a en tiré :
http://p2phlsplus vanlong stream/public/dist/index.html?id=effd8b5f0fc9e5244581926161d31ca7

**Comment by Che-debarras** [comment]
C'est quoi ton fichier m3u8? Un film?
Car laddon p2pstream le découpe en 932 fochier sur kodi et en appuyant play ça affiche un carré jaune

**Comment by sizanic** [comment]
Ouvre le fichier dans notepad et récupéré une des lignes, elle est lisible dans VLC, c'est 'l'armée des morts'.
Il manque pas grand chose, chaque ligne découpée est lisible individuellement.

**Comment by Che-debarras** [comment]
Kodi via host direct lis bien les m3u8 
Sur ce site : https://ottverse.com/free-hls-m3u8-test-urls/
J'ai testé tous les fichiers test de ce site et ils sont tous lisiblespar kodi
Les seuls qui ne fonctionnent pas ce sont ceux avec http car https sont lisibles

**Comment by TmpName** [comment]
>Il manque pas grand chose, chaque ligne découpée est lisible individuellement.

Tu as testé une des lignes dans VLC ? Et ca a marché ?

**Comment by TmpName** [comment]
>Il m'a pourtant l'air correct, surtout que chaque ligne du fichier prise individuellement se lit correctement dans VLC.

Je viens de tester, cjez moi j'ai le carré blanc aussi.

Tu as la video toi ?

**Comment by sizanic** [comment]
Un carré blanc dans un navigateur, oui 
Mais j'ai bien la vidéo avec VLC.

**Comment by Che-debarras** [comment]
Je suis comme @TmpName pas de video sur vlc mais carré blanc
Sur kodi j'ai des carré jaune avec p2pstream addon
Donc si tu as la video sur vlc et pas de carré blanc essaie l'addon p2pstream.
Peut-être que au lieu de carré jaune tu aura aussi la video. 😉

**Comment by TmpName** [comment]
Lol, put1, mais c'est pire que CF ce truc.
Et non je suis sous windows, peut etre une difference de version de VLC ...

**Comment by sizanic** [comment]
Je suis sous Windows.
Je télécharge ce fichier :
> http://103 .155. 93. 239/hls/f762999e701fc61285816b4cd2f7a10c/f762999e701fc61285816b4cd2f7a10c.m3u8

Je l'ouvre et dedans il y à ceci : 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:28
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:14.692643,
https://p2phlsplus.vanlong.stream/hls/f762999e701fc61285816b4cd2f7a10c/f762999e701fc61285816b4cd2f7a10c-0.html?msKey=m1
#EXTINF:12.819645,
https://p2phlsplus.vanlong.stream/hls/f762999e701fc61285816b4cd2f7a10c/f762999e701fc61285816b4cd2f7a10c-1.html?msKey=m1
#EXTINF:18.105667,
https://p2phlsplus.vanlong.stream/hls/f762999e701fc61285816b4cd2f7a10c/f762999e701fc61285816b4cd2f7a10c-2.html?msKey=m1
etc......
```


J'ouvre n'importe quel bout dans VLC, avec la commande "Ctrl+N" : 
https://p2phlsplus.vanlong.stream/hls/f762999e701fc61285816b4cd2f7a10c/f762999e701fc61285816b4cd2f7a10c-0.html?msKey=m1

Et je vois bien la vidéo.
Le format m3u est correct, la description juste avant correspond à la durée de la séquence, cette séquence dure 14.7 secondes.

Si j'ouvre ce fichier dans chrome, j'ai bien juste un point.

**Comment by Che-debarras** [comment]
> Lol, put1, mais c'est pire que CF ce truc.
> Et non je suis sous windows, peut etre une difference de version de VLC ...

J'ai testé pas mal d'addon sur kodi 17, 18 19 et 20 et rien à faire au pire ya un carré jaune ou au mieux  j'ai l'image sous forme gif de inializing player qui s'affiche sur kodi 19 et plus mais pas de lecture de film
![Screenshot_20210602-001940_Samsung Internet](https://user-images.githubusercontent.com/44464129/120397272-4c435c80-c338-11eb-9326-35f89e6e220d.jpg)

Pour rappel ya deja eu discussion a propos de jw player #2219

**Comment by sizanic** [comment]
> Pour rappel ya deja eu discussion a propos de jw player #2219

Je viens de parcourir ce sujet, et je ne penses pas que ça traite de la même chose.

J'arrive à avoir de la vidéo dans VLC, et VLC n'utilise pas le player jw 🤔 

Mais je vois bien une protection CF.
Et VLC arrive à passer cette protection 🤔

**Comment by Che-debarras** [comment]
> Mais je vois bien une protection CF.
> Et VLC arrive à passer cette protection 🤔

Tu es sur Android ou Windows ? Quel version de Kodi?

**Comment by TmpName** [comment]
VLC 3.0.11 sous windows, le lien marche pas, je l'ouvre avec media/ouvrir un flux reseau

**Comment by sizanic** [comment]
> VLC 3.0.11 sous windows, le lien marche pas, je l'ouvre avec media/ouvrir un flux reseau

Tout pareil, pourtant 🤔 
Sans doute que j'ai un codec en plus qui va bien.


![image](https://user-images.githubusercontent.com/47307622/120673542-8f661280-c493-11eb-93dc-c6542fd3ddd7.png)

**Comment by TmpName** [comment]
C'est probable, mais j'ai telecharge le fichier et meme dans kodi illisible, et pour rajouter des codecs dans kodi ...

**Comment by sizanic** [comment]
Oui, dans KODI c'est illisible, c'est bien là le problème, alors que j'y arrive avec VLC.

**Comment by sviet2k** [comment]
Quelques "hints" sur Android:
Ce m3u8 lien marche avec MX Player sous l'ancien Android 5 mais pas avec android 6 et plus. :)
Kodi lien discute de ce sujet: https://forum.kodi.tv/showthread.php?tid=349855

**Comment by sizanic** [comment]
Merci pour le lien 👍 

Il emmène vers d'autres discussions, comme celle-ci par exemple, qui a l'air de proposer un contournement : 
https://git hub.com/D4 aniel CB/plugin.video.Cinput/issues/1

Il faudrait voir dans quelle mesure on pourrait s'en inspirer.
Pour info, cela permettrait le retour de la source Kepliz (wonior).

**Comment by sviet2k** [comment]
La solution de Proxy pour enlever le PNG Header semble pouvoir fixer le problème.
Bonne chance. J'ai hâte de revoir le Kepliz. :)

**Comment by sviet2k** [comment]
Use this link format to send the stream to proxy:
proxy_url = 'hxxp://127.0.0.1:port>?u='  + <stream link>'

Here is the proxy code based on hxxps://git hub.com/D4 aniel CB/plugin.video.Cinput/issues/1
(Only for m3u8)

class ProxyHTTPRequestHandler(BaseHTTPRequestHandler):
    protocol_version = 'HTTP/1.0'

 class ProxyHTTPRequestHandler(BaseHTTPRequestHandler):
    protocol_version = 'HTTP/1.0'

    def do_GET(self):
        xbmc.log('=====Start Server url : %s' % self.path,xbmc.LOGINFO)
        p = urlparse(self.path)
        q = dict(parse_qsl(p.query))
        u = q['u']
        url = u[:-3] if u.endswith('-no') else u
        xbmc.log("====" + url,xbmc.LOGINFO)
        
        if '?msKey=' in url:
            res = requests.get(url).content[8:]
        else:
            res = requests.get(url).content.decode()
            res = res.replace('http','http://127.0.0.1:<port>?u=http')
            res = res.encode()
        self.send_response(200)
        self.send_header('Content-Length', len(ret))
        self.send_header('Content-Type', 'application/vnd.apple.mpegurl')
        self.end_headers()
        self.wfile.write(res)

**Comment by TmpName** [comment]
Yep, bonne infos, par contre j'ai rien compris, faut juste installer son plugin ?

**Comment by sviet2k** [comment]
Non. Il faut intégrer le code dans le service.py de vstream. Après dans le code du site (ex: kepliz), utilise le format suivant pour re-diriger le stream au proxy.
proxy_url = 'hxxp://127.0.0.1:portNb?u=' + stream link

**Comment by yodidon** [comment]
J’ai commencé à regarder mais pour l’instant pas très clair pour moi...

**Comment by sizanic** [comment]
> Non. Il faut intégrer le code dans le service.py de vstream. Après dans le code du site (ex: kepliz), utilise le format suivant pour re-diriger le stream au proxy.
> proxy_url = 'hxxp://127.0.0.1:portNb?u=' + stream link

@sviet2k  Tu saurais le faire ?
un petit coup de main est toujours le bienvenue.

**Comment by sviet2k** [comment]
Bien sûr, c'est mon plaisir si je peux vous aider, mais je ne peux pas livrer une solution finale, car je ne peux pas tester vtream.

Voici le fichier service.py (renommer zip par py) sans tester. :( Mais je peux vous aider à régler le problème.
[service.py.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6603422/service.py.zip)

Premièrement, j'ai besoin de votre aide pour tester le proxy:
Essayer de démarrer le vstream pour voir si vtream peut démarrer le proxy sans erreurs.

**Comment by TmpName** [comment]
Ben le soucis est la ^^.

Tu connais le fonctionnement de Vstream ?
On fait il n'y a pas de fichier python qui se lancent pour faire tourner un serveur en background. c'est kodi qui lance des scripts python (et qui attend un retour)
Apres c'est possible sous kodi, mais en general c'est des codes annexes qui sont lancés eux meme par les scripts lancés par kodi.
Ou alors démarrés a la main.

**Comment by Che-debarras** [comment]
> Voici le fichier service.py (renommer zip par py) sans tester. :( Mais je peux vous aider à régler le problème.
> [service.py.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6603422/service.py.zip)

Le fichier est corrompu, impossible à l'ouvrir 

> Premièrement, j'ai besoin de votre aide pour tester le proxy:
> Essayer de démarrer le vstream pour voir si vtream peut démarrer le proxy sans erreurs.

Ya til une source dispo sur vstream qui utilise m3u8? Peut-être réactivé kepliz pour les tests?

**Comment by sviet2k** [comment]
@Che-debarras: tu renommes juste le fichier, N'unzip pas:
mv service.py.zip srvice.py

@TmpName::
Oui, Le service.py de vstream va lancer le proxy quand on démarre le addon.

Tester:
Je ne sais pas comment tester sous vtream mais l'idée est::
Créer ce url:
url = 'hxxp://127.0.0.1:2424?u=hxxp://103 .155. 93. 239/hls/f762999e701fc61285816b4cd2f7a10c/f762999e701fc61285816b4cd2f7a10c.m3u8
Et teste ce url avec vstream

**Comment by Arias800** [comment]
Ça fonctionne correctement.
Je suis en train de voir si ont ne peux pas l'implémenter localement dans Kepliz, ça ne sert à rien de faire tourner le serveur si la personne n'utilise pas ce site.

**Comment by Che-debarras** [comment]
Je confirme j'ai testé avec host direct et cela marche sur android

**Comment by Arias800** [comment]
Et voilà, c'est en place.
Merci @sviet2k pour le coup de main.

Si Kepliz n'est pas activer dans les paramètres, alors le serveur ne se lance pas au démarrage de Kodi.
Kaydo c'est sur la liste des sites que je dois mettre a jour xD

**Comment by sizanic** [comment]
Wouah super !
Je suis content d'avoir lancer ce sujet et comment vous avez apporté une réponse collective ! 👍🏻

**Comment by Che-debarras** [comment]
> Et voilà, c'est en place.
> Merci @sviet2k pour le coup de main.
> 
> Si Kepliz n'est pas activer dans les paramètres, alors le serveur ne se lance pas au démarrage de Kodi.
> Kaydo c'est sur la liste des sites que je dois mettre a jour xD

Excellent kepliz marche 
Mais comme kaydo, la source est a refaire car quelque soit la catégorie : docu spectacle film on a la meme liste de film

**Comment by sviet2k** [comment]
Vous ne regardez pas le grand prix F1? :)

**Comment by TmpName** [comment]
Mais par contre quelqu'un se souvient a quoi servait l'ancien service qu'on avait ?

**Comment by Arias800** [comment]
C'est pour l'enregistrement des chaines IPTV.
Non je ne regarde pas la F1 personnellement @sviet2k :)

**Comment by Arias800** [comment]
Kaydo corrigé (pour le bug du genre documentaire, c'est un problème du site).

**Comment by Che-debarras** [comment]
> Kaydo corrigé (pour le bug du genre documentaire, c'est un problème du site).

J'ai testé Kaydo et cela marche , vraiment de plus en plus excellent vstream
Le retour de 2 bonnes sources.
Donc il n'y as pas de cloudflare , j'y ai accès
Dommage pour le bug des listes car on distingue plus les series des films
Mais bon c'est deja énorme

Merci à @sizanic , @sviet2k , @Arias800 , @yodidon pour avoir ressuscité 3 sources préférées (frnchstrm.RE, keplz et kaydo).

**Comment by sizanic** [comment]
> Mais comme kaydo, la source kepliz est a refaire car quelque soit la catégorie : docu / spectacle / film, on a la meme liste de film

Corrigé pour kaydo, les listes sont maintenant différentes (mais films et séries restent mélangés).
Je vais regarder pour kepliz si on peut faire qqchose.

**Comment by sizanic** [comment]
J'ai bien avancé sur les genres pour kepliz. Livraison ce soir.

**Comment by sizanic** [comment]
C'est bon Kepliz :
- les genres
- la recherche
- la pagination

**Comment by Che-debarras** [comment]
> Par contre, beaucoup de liens morts détectés pendant mes tests 😢

Aurait ty un exemple ou 2?
Par contre Kaydo ne marche plus,les dossiers d'un film ou serie ne s'ouvrent plus, pas d'accès aux hosts.
Pour kepliz ça semble ok

**Comment by sizanic** [comment]
Tu recherches "dead" -> 20 résultats -> la moitié n'a plus de liens valides.
Tous les films à partir de "Once Upon a Deadpool (2018)"

**Comment by sizanic** [comment]
J'ai également noté quelques difficultés avec Kaydo hier soir mais aujourd'hui tout semble fonctionner.

**Comment by sizanic** [comment]
@sviet2k 
@Arias800 
@TmpName 

Le log de KODI se remplit de trace : 
`2021-06-09 22:31:09.495 T:12448   ERROR: 127.0.0.1 - - [09/Jun/2021 22:31:09] "GET ?u=https://sali.hdss.nu/hls3/d048daf0110b0a3b572106/d048ddba7310b0a3b572106-1.html?msKey=m6 HTTP/1.1" 200 -
`

cela vient de l'utilisation de : 
` self.send_response(200)`


Car d'après la doc : 
https://docs.python.org/3/library/http.server.html : 
_Adds a response header to the headers buffer and logs the accepted request._

N'y a-t'il pas un moyen d'nvoyer la réponse sans avoir de log ?

**Comment by sviet2k** [comment]
Bon remarque @sizanic 
Le send_response n'est pas nécessaire. Enlève le,

**Comment by Arias800** [comment]
En faite, il s'avère qu'elle était utile. Du coup, je l'ai remplacé par la fonction `send_response_only` qui fait la même chose sans rien marquer dans les logs.

**Comment by Che-debarras** [comment]
Kaydo remarche
