### ISSUE TITLE
Flaresolverr et vstream (Android)

### ISSUE THREAD

**Issue by Che-debarras** [Kodi-vStream/venom-xbmc-addons#3306]
Je pense que le titre est assez facile à deviner,  cela concerne la notification sur vstream d'installer Flaresolverr.
Mais comme selenium,je me demande si ce F.S sera fonctionnel avec android car je vois queble PR à été accepté.
Cette question est dans le but de garder ou anhilier tout espoir de bypasser CF sur Android.

Merci pour tout info sur concernant ce Flaresolverr (et je n'impose pas une personne d'y travailler, juste savoir ce qu'il en ai de ce bypass).

**Comment by denseye73** [comment]
d'après ce que j'ai compris, il te faut une autre machine chez toi (windows ou Linux) pour faire tourner le serveur local Flaresolverr, et alors le bypass fonctionnera sur ta box android

**Comment by Che-debarras** [comment]
> d'après ce que j'ai compris, il te faut une autre machine chez toi (windows ou Linux) pour faire tourner le serveur local Flaresolverr, et alors le bypass fonctionnera sur ta box android

Ça n'a aucun intérêt d'utiliser une autre machine pour utiliser une box tv ou smartphone ou tablette.
Dans ce cas autant utiliser directement cette machine Linux ou windows ce sera plus simple.

J'ai du mal a comprendre la logique des gens à développer que des choses sur pc alors qu'une serie tv ou film est plus pratique sur une tv.

On a tous un smartphone tablette et box tv et tv avec android bien pratique pour regarder film et serie de part leur mobilité ou grand écran et autonomie.

Android est issue de Linux meme flaresolver parle de armv7 et ya eu bcp de script  pour contourner CF sur kodi donc normalement ce flaresolverr devrait pouvoir se faire sur android.

Ce n'est pas une absolue nécessité pour moi ce bypass de CF car j'utilise aucune source l'utilisant.

Mais le problème du host de dood qui soit disant utilise un CF (bien qu'il fonctionne sur kodi 19) et frnchstrm.lol aussi me fait demander si acheter une box windows (mini pc) n'est pas plus rentable car plus personne ne développe sur android

**Comment by Arias800** [comment]
C'est toujours le même problème, Android utilise un système de sandbox entre les applications.
Une application ne peux pas interagir avec une autre, c'est une mesure de sécurité que l'ont ne peux pas contourner.
Donc c'est impossible de piloter un navigateur internet sur Android de manière automatisé.
Passé par un intermédiaire est la seule solution qui existe et qui est réalisable.

**Comment by Che-debarras** [comment]
Donc flaresolverr ne sera pas compatible avec android pour vstream de maniere autonome ?
Passer par un pc  intermédiaire je trouve cela pas pratique a moins d'investir un box mini pc au lien de box android.

**Comment by Arias800** [comment]
Non, ça n'arrivera pas.
Et personne ne va se compliquer la vie à faire un code pour passé Cloudflare comme avant, le code change beaucoup trop rapidement pour que ce sois gérable. Les navigateurs autonomes sont les seules solutions viables.

Pour Dood je n’ai pas suivie la discussion, je vais lire ça et je te réponds.

**Comment by Arias800** [comment]
Je viens de tester pour Dood, et sous Kodi 20 il apparait aussi sous Cloudflare.
Par contre, via un navigateur ce n'est pas le cas. Je suis en train d'essayer de comprendre pourquoi.

**Comment by Che-debarras** [comment]
Oui je viens de test kodi 19, 19.1 et 20 et dood fonctionne malgré que selon toi et @sizanic le host apparaît sous CF 

donc je pense que cette mention CF pour ce host est un bug peut-être lié au CF du site (testé une source sans CF qui utilise dood et voir si il y a toujours la mention CF).

Et pourquoi a t'on accès sur kodi 19 et 20 si ce host est sous CF et pas  TX ou ZT ?

**Comment by Arias800** [comment]
Les cas sont pas comparable :
- Le site de Dood est accessible via navigateur sans que CF apparaisse, tandis que TX ou ZT sont protégé par CF même en utilisant un navigateur internet.

Peut-être que Cloudflare est mal implémenté sur Dood et que du coup via Kodi ça bloque a certains moments (l'host est inaccessible chez moi par exemple).
Peut-être que ça viens de la lib requests.

Il y a énormément de facteurs qui rentre en compte, et ça prendrait beaucoup de temps de chercher la raison.

**Comment by Che-debarras** [comment]
Je pense que le bug de cf sur dood est possible surtout qu'il change de url en .cx et que CF est présent dans dood depuis plus d'un an donc oui sûrement un bug qui fait planter sur kodi.
Mais cela n'explique pas pourquoi kodi 19 et 20 n'ont pas ce blocage.

Enfin bref, je vais clore ce sujet car j'ai décidé de passer à kodi 19 et 20 donc plus de problèmes 😉

**Comment by Arias800** [comment]
@Che-debarras je suis en train de tester une solution sur Android (pour passer Cloudflare), et j'aurai besoin de toi plus tard pour les tests 😉

**Comment by TmpName** [comment]
Tjours avec Flaresolver ?

**Comment by Arias800** [comment]
Non, avec une appli native Android que je suis en train de faire (en trichant avec les limites d'Android) xD

**Comment by Arias800** [comment]
Pour tester il faut :
- Cette version de requestsHander : https://github.com/Arias800/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/handler/requestHandler.py
- Installer cette application Android : https://github.com/Arias800/CloudVstream/releases/tag/1

Comment ça fonctionne ?
Si le code détecte Cloudflare, alors il sauvegarde l'url dans un fichier texte.
Il va ensuite lancer l'application Android qui va récupérer l'url que contient le fichier texte, et l'ouvrir en exécutant la page internet.
Une fois la page Cloudflare décrypter, l'utilisateur va retourner en arrière.
Le code source de la page va être enregistré dans un fichier HTML que Vstream va récupérer et exécuter.

Je suis en train de voir pour mettre un message lorsque Cloudflare est passé.
Tirexo ne marche pour le moment pas à 100%, la release est avant tout là pour avoir les 1ers retours sur le fonctionnement.
