### ISSUE TITLE
Bugs après la mise à jour 1.2.0

### ISSUE THREAD

**Issue by Digidix** [Kodi-vStream/venom-xbmc-addons#3307]
Bonsoir,

Avant tout, et une nouvelle fois, un grand merci à toute l'équipe pour le magnifique travail que vous faites sur Vstream.

Je me permets de remonter trois petits bugs après la mise à jour 1.2.0, en commençant par le moins important :

- 1 Petite faute de syntaxe dans le message extension requise, avec deux fois le mot être :

![Faute Up Next](https://user-images.githubusercontent.com/73746949/120119720-9cd08380-c199-11eb-94af-d046f2b0725d.png)

- 2 Dans le menu contextuel, il y a maintenant deux fois le choix information, il y a "information**s**" qui renvoie à l'info du film avec l'habillage du skin, et "information" qui ouvre l'info du film avec l'habillage Vstream :

Avant maj :

![Bug menu avant maj](https://user-images.githubusercontent.com/73746949/120119753-cab5c800-c199-11eb-86da-5c07df2eb7aa.png)

Après maj :

![Bug menu après maj](https://user-images.githubusercontent.com/73746949/120119760-d6a18a00-c199-11eb-984b-fdb9c47ab0f1.png)

Du coup, cela remonte un autre bug, celui que j'ai remonté sur Discord il y a un petit moment, concernant l'affichage de la durée, qui semble toujours d'actualité :

En effet, si je passe par le premier choix du menu contextuel, celui qui ouvre la fenêtre du skin, info heure/minute ok :

![Bug durée info skin](https://user-images.githubusercontent.com/73746949/120119787-f9cc3980-c199-11eb-91d3-c9376ccddf24.png)

Si je passe par le second choix du menu contextuel, celui qui ouvre la fenêtre gérée par Vstream, le bug est toujours là :

![Bug durée](https://user-images.githubusercontent.com/73746949/120119808-0cdf0980-c19a-11eb-8e25-87ddc94d34f4.png)

Parfois avec moins de chiffres :

![Bug durée après maj](https://user-images.githubusercontent.com/73746949/120119842-339d4000-c19a-11eb-9632-fecdf832ebf0.png)

Pour rappel, ce bug est présent sur trois périphériques totalement différents, malgré une installation propre et rien d'autre que Vstream.

Bug présent sur : Tablette Android avec Kodi 18.9, device avec CoreELEC, et Kodi 19.1 avec Windows 10 20H2.

- 3 Dernier problème, qui touche uniquement le device avec CoreELEC :

Si j'active Up Next, j'ai bien la fenêtre avec le choix pour passer à l'épisode suivant, mais lorsque je valide, l'épisode suivant se lance en arrière-plan, juste avec un écran noir.

Si j'essaye avec le panneau de gauche de le remettre en plein écran ou de stopper la lecture, mon appareil crash carrément et se fige, obligé de le re booter électriquement.

Du coup, pour l'instant, sur CoreELEC j'ai désactivé Up Next.

Merci !

**Comment by sizanic** [comment]
Bonsoir @Digidix,

Merci pour ces retours.

Je m'en vais corrigé le premier point de suite 👍 

Pour le 2eme point, les médias vStream sont maintenant mieux reconnus par le skin, ce qui lui permet de proposer sa propre fenêtre d'information**s**.
Le seul bug que je note est celui sur l'affichage de la durée.
On va regarder.


Pour le troisième point, cela nous sera très difficile de le reproduire en condition.
Je ne peux pas t'annoncer une correction rapide.

**Comment by sizanic** [comment]
Finalement pour le premier point, la faute de syntaxe, on ne fera rien.

Car ce n'est pas vStream qui affiche ce message, mais bien **KODI**.

Est-ce présent aussi en version 19 ou l'ont-ils corrigés ?

**Comment by Digidix** [comment]
> Est-ce présent aussi en version 19 ou l'ont-ils corrigés ?

Oui, c'est présent sur toutes les versions que j'ai testé (Kodi 18.9, CoreELEC, et Kodi 19.1).

> Pour le 2eme point, les médias vStream sont maintenant mieux reconnus par le skin, ce qui lui permet de proposer sa propre fenêtre d'information**s**.

Est-il possible de regrouper cela ou dans supprimer un (ou au moins avoir le choix dans les paramètres) pour éviter d'avoir un doublon et faire plus "propre" ?

> Le seul bug que je note est celui sur l'affichage de la durée.
> On va regarder.

Merci @sizanic !

**Comment by sizanic** [comment]
Pour la fenetre d'informations, on ne peut pas désactiver celle de KODI.
Mais un paramètre pour désactiver celle de vStream pourrait être intéressant.
On doit de toute façon revoir cette partie pour désactiver le choix "extended info" qui n'est plus supporté en version 19.

**Comment by GravuTrad** [comment]
Perso j'ai pleins de sources qui listent plus rien après cet update alors qu'elle marchaient juste avant sans l'update. Tout marche pour vous?

**Comment by GravuTrad** [comment]
Surement lié à ça: https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3300

**Comment by Digidix** [comment]
> Si j'active Up Next, j'ai bien la fenêtre avec le choix pour passer à l'épisode suivant, mais lorsque je valide, l'épisode suivant se lance en arrière-plan, juste avec un écran noir.
> 
> Si j'essaye avec le panneau de gauche de le remettre en plein écran ou de stopper la lecture, mon appareil crash carrément et se fige, obligé de le re booter électriquement.

@sizanic Apparemment, il s'agit de ce problème, et il y a une solution : https://github.com/im85288/service.upnext/issues/250#issue-820075876

Je ne pense pas que la solution soit intégrable à Vstream du coup.

**Comment by sizanic** [comment]
Dans cet exemple, l'épisode ne se lance pas du tout, et il ne peut pas se lancer d'après les explications.
Alors qu'ici l'épisode démarre bien mais en arrière plan (on entend le son mais on ne voit pas l'image).

Personnellement, il m'arrive aussi qu'un épisode se lance en arrière plan, même dès le premier épisode !
Car cela m'arrive même avec le lancement d'un film. 
Donc je ne pense pas que cela soit lié avec Upnext. Mais plutot dans la façon que vStream demande à KODI de lire la vidéo.
Mais ce phénomène est beaucoup plus systématique lorsqu'une vidéo est déjà en cours.

**Comment by Digidix** [comment]
@sizanic 
Après la mise à jour 1.3.0, les infos sur la durée sont de nouveau fonctionnelles, merci !

**Comment by Che-debarras** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3300#issuecomment-873665207
