### ISSUE TITLE
Merci 

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3308]
Bonsoir à tous,

Je vous ai souvent remercié pour votre boulot quand j'ai eu besoin de vos lumières suite à un souci; là j'ai vraiment galéré avec la nouvelle mise à jour qui ne me permettait plus de lancer quoi que ce soit et je me suis remis sur les bases (DNS 1.1.1.1 et activation IPV6 sur ma box). Après quoi, j'ai redémarré ma box, relancé Kodi puis notre Addon favori et là : Waowwww je n'ai jamais vu autant de sources accessibles, même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.

Donc voilà, pour une fois je voulais faire un post seulement pour vous remercier et vous féliciter pour ce taf incroyable que vous faites pour nous régaler à la maison. 

Merci, Merci et encore Merci 👍😉

**Comment by sizanic** [comment]
Merci beaucoup pour tes remerciements,
Ils nous touchent.

En effet, nous avons fait un travail pour rendre fonctionnelles toutes les sources que nous proposons.

Et je pense que tu apprécieras tout autant les dernières évolutions de cette nouvelle version : 

- UpNext : Enchainement automatique des épisodes
- Reprise d'un média commencé, même en changeant de source
- Métadonnées : informations média (pochette et description) pour les saisons
- Métadonnées : plus d'informations média pour les films et compatibilité avec plus de skins

**Comment by Niconimes** [comment]
> Merci beaucoup pour tes remerciements,
> Ils nous touchent.
> 
> En effet, nous avons fait un travail pour rendre fonctionnelles toutes les sources que nous proposons.
> 
> Et je pense que tu apprécieras tout autant les dernières évolutions de cette nouvelle version :
> 
> * UpNext : Enchainement automatique des épisodes
> * Reprise d'un média commencé, même en changeant de source
> * Métadonnées : informations média (pochette et description) pour les saisons
> * Métadonnées : plus d'informations média pour les films et compatibilité avec plus de skins

Vous avez fait un travail fabuleux, je suis dingue de votre Addon et quand c'est aussi réussi, il faut le dire.
Donc oui, un grand bravo et un énorme Merci pour tout ce temps et cet investissement que vous nous offrez 👍

**Comment by Che-debarras** [comment]
> Bonsoir à tous,
> 
> , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> 

Comment ça ZT fonctionne?

**Comment by Niconimes** [comment]
> > Bonsoir à tous,
> > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> 
> Comment ça ZT fonctionne? Il es sous Cloudflare

Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe

**Comment by Che-debarras** [comment]
> > > Bonsoir à tous,
> > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > 
> > 
> > Comment ça ZT fonctionne? Il es sous Cloudflare
> 
> Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe

Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF

**Comment by Niconimes** [comment]
> > > > Bonsoir à tous,
> > > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > > 
> > > 
> > > Comment ça ZT fonctionne? Il es sous Cloudflare
> > 
> > 
> > Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe
> 
> Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF

Oui absolument, si tu utilises source ça ne fonctionne pas pour aucunes catégorie mais en recherche globale ça fonctionne

**Comment by Che-debarras** [comment]
> > > > > Bonsoir à tous,
> > > > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > > > 
> > > > 
> > > > Comment ça ZT fonctionne? Il es sous Cloudflare
> > > 
> > > 
> > > Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe
> > 
> > 
> > Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF
> 
> Oui absolument, si tu utilises source ça ne fonctionne pas pour aucunes catégorie mais en recherche globale ça fonctionne

J'ai fait une recherche globale sur le film cruella et il ne trouve pas de film sur zt aucun résultats avec la recherche globale 
Donc zt est innacessible

**Comment by Niconimes** [comment]
> > > > > > Bonsoir à tous,
> > > > > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > > > > 
> > > > > 
> > > > > Comment ça ZT fonctionne? Il es sous Cloudflare
> > > > 
> > > > 
> > > > Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe
> > > 
> > > 
> > > Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF
> > 
> > 
> > Oui absolument, si tu utilises source ça ne fonctionne pas pour aucunes catégorie mais en recherche globale ça fonctionne
> 
> J'ai fait une recherche globale sur le film cruella et il ne trouve pas de film sur zt aucun résultats avec la recherche globale
> Donc zt est innacessible

Je reteste dès que je rentre à la maison, dans la soirée et je te dis ça

**Comment by Che-debarras** [comment]
> > > > > > > Bonsoir à tous,
> > > > > > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > > > > > 
> > > > > > 
> > > > > > Comment ça ZT fonctionne? Il es sous Cloudflare
> > > > > 
> > > > > 
> > > > > Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe
> > > > 
> > > > 
> > > > Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF
> > > 
> > > 
> > > Oui absolument, si tu utilises source ça ne fonctionne pas pour aucunes catégorie mais en recherche globale ça fonctionne
> > 
> > 
> > J'ai fait une recherche globale sur le film cruella et il ne trouve pas de film sur zt aucun résultats avec la recherche globale
> > Donc zt est innacessible
> 
> Je reteste dès que je rentre à la maison, dans la soirée et je te dis ça

Les sites sous CF ne donne aucun résultats hormis Wwcity.
Je suis sur kodi 18.9 donc est tu sur kodi 19 ou 20?

**Comment by Niconimes** [comment]
> > > > > > > > Bonsoir à tous,
> > > > > > > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > > > > > > 
> > > > > > > 
> > > > > > > Comment ça ZT fonctionne? Il es sous Cloudflare
> > > > > > 
> > > > > > 
> > > > > > Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe
> > > > > 
> > > > > 
> > > > > Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF
> > > > 
> > > > 
> > > > Oui absolument, si tu utilises source ça ne fonctionne pas pour aucunes catégorie mais en recherche globale ça fonctionne
> > > 
> > > 
> > > J'ai fait une recherche globale sur le film cruella et il ne trouve pas de film sur zt aucun résultats avec la recherche globale
> > > Donc zt est innacessible
> > 
> > 
> > Je reteste dès que je rentre à la maison, dans la soirée et je te dis ça
> 
> Les sites sous CF ne donne aucun résultats hormis Wwcity.
> Je suis sur kodi 18.9 donc est tu sur kodi 19 ou 20?

Kodi 19.1

**Comment by Che-debarras** [comment]
> > > > > > > > > Bonsoir à tous,
> > > > > > > > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Comment ça ZT fonctionne? Il es sous Cloudflare
> > > > > > > 
> > > > > > > 
> > > > > > > Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe
> > > > > > 
> > > > > > 
> > > > > > Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF
> > > > > 
> > > > > 
> > > > > Oui absolument, si tu utilises source ça ne fonctionne pas pour aucunes catégorie mais en recherche globale ça fonctionne
> > > > 
> > > > 
> > > > J'ai fait une recherche globale sur le film cruella et il ne trouve pas de film sur zt aucun résultats avec la recherche globale
> > > > Donc zt est innacessible
> > > 
> > > 
> > > Je reteste dès que je rentre à la maison, dans la soirée et je te dis ça
> > 
> > 
> > Les sites sous CF ne donne aucun résultats hormis Wwcity.
> > Je suis sur kodi 18.9 donc est tu sur kodi 19 ou 20?
> 
> Kodi 19.1

Je m'en doutais un peu car je doutais d'un "bypass" de kodi 19 comme c'est le cas avec le host Dood et viki presque sur kodi 19 et plus.
Donc je dois absolument passer sous kodi 19.1 sur mes box.

Merci

**Comment by Niconimes** [comment]
> > > > > > > > > > Bonsoir à tous,
> > > > > > > > > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Comment ça ZT fonctionne? Il es sous Cloudflare
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe
> > > > > > > 
> > > > > > > 
> > > > > > > Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF
> > > > > > 
> > > > > > 
> > > > > > Oui absolument, si tu utilises source ça ne fonctionne pas pour aucunes catégorie mais en recherche globale ça fonctionne
> > > > > 
> > > > > 
> > > > > J'ai fait une recherche globale sur le film cruella et il ne trouve pas de film sur zt aucun résultats avec la recherche globale
> > > > > Donc zt est innacessible
> > > > 
> > > > 
> > > > Je reteste dès que je rentre à la maison, dans la soirée et je te dis ça
> > > 
> > > 
> > > Les sites sous CF ne donne aucun résultats hormis Wwcity.
> > > Je suis sur kodi 18.9 donc est tu sur kodi 19 ou 20?
> > 
> > 
> > Kodi 19.1
> 
> Je m'en doutais un peu car je doutais d'un "bypass" de kodi 19 comme c'est le cas avec le host Dood et viki presque sur kodi 19 et plus.
> Donc je dois absolument passer sous kodi 19.1 sur mes box.
> 
> Merci

Avec plaisir 😉

**Comment by Niconimes** [comment]
> > > > > > > > > > Bonsoir à tous,
> > > > > > > > > > , même des sites que je n'arrivais plus à accéder comme Z T ou Wawa ity fonctionnent à merveille.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Comment ça ZT fonctionne? Il es sous Cloudflare
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Et bien ça ne fonctionne pas si tu utilises films/derniers ajouts/ZT, par contre si tu fais une recherche par nom de films et bien là ça passe
> > > > > > > 
> > > > > > > 
> > > > > > > Tu parles d'une recherche globale sur tous les sites? Car la recherche à partir de la source ne fonctionne pas, c'est CF
> > > > > > 
> > > > > > 
> > > > > > Oui absolument, si tu utilises source ça ne fonctionne pas pour aucunes catégorie mais en recherche globale ça fonctionne
> > > > > 
> > > > > 
> > > > > J'ai fait une recherche globale sur le film cruella et il ne trouve pas de film sur zt aucun résultats avec la recherche globale
> > > > > Donc zt est innacessible
> > > > 
> > > > 
> > > > Je reteste dès que je rentre à la maison, dans la soirée et je te dis ça
> > > 
> > > 
> > > Les sites sous CF ne donne aucun résultats hormis Wwcity.
> > > Je suis sur kodi 18.9 donc est tu sur kodi 19 ou 20?
> > 
> > 
> > Kodi 19.1
> 
> Je m'en doutais un peu car je doutais d'un "bypass" de kodi 19 comme c'est le cas avec le host Dood et viki presque sur kodi 19 et plus.
> Donc je dois absolument passer sous kodi 19.1 sur mes box.
> 
> Merci

Bon et bien visiblement je t'ai dis une bêtise, je n'ai plus aucuns résultats sur ZT, désolé 😭😭😭
