### ISSUE TITLE
Bandes annonces

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#3309]
Bonjour,

Malgré le téléchargement de la dernière Béta,
les bandes annonces ne fonctionnent plus.
Je suis sous Kodi 18.9

Merci à vous

Bonne journée sous le soleil

**Comment by TmpName** [comment]
Ha yep
```
                                              File "Kodi\addons\plugin.video.vstream\resources\lib\tmdb.py", line 988, in _cache_save_season
                                                self.dbcur.execute(sql_select)
                                            NameError: global name 'sql_select' is not defined
```

**Comment by Papounet58** [comment]
Merci TMPName pour ta réactivité.
Je viens de tester mais malheureusement cela ne fonctionne toujours pas.

Bonne journée à toi

**Comment by TmpName** [comment]
Il te faut aussi mettre a jour le fichier hoster youtube.py.
Si ca ne marche toujours pas, pourrais tu partager les logs ?

**Comment by Papounet58** [comment]
Bonsoir TmpName,

Avant téléchargement de la dernière Béta, j'avais une erreur " 400 " sur Youtube.
Après application de la dernière Béta cette erreur est disparue mais la bande annonce ne se lance pas.
Ne te prends pas la tête avec ce problème je peux chercher la bande annonce autrement.

Bon week-end à toi.

**Comment by yodidon** [comment]
Tu lances la bande annonce à partir du menu contextuel ?

**Comment by Papounet58** [comment]
Bonjour Yodidon,

J'utilise soit la fenêtre " information ", soit la fenêtre " bande annonce dans le menu.
La vidéo de la bande annonce ne démarre dans aucune des deux.

Bonne journée

**Comment by yodidon** [comment]
> Bonjour Yodidon,
> 
> J'utilise soit la fenêtre " information ", soit la fenêtre " bande annonce dans le menu.
> La vidéo de la bande annonce ne démarre dans aucune des deux.
> 
> Bonne journée

Salut,
Tu utilise la fenêtre information de vstream ou du skin ?

**Comment by TmpName** [comment]
Ca marche de ton coté @yodidon ?

**Comment by Papounet58** [comment]
J'utilise la fenêtre info de Vstream

**Comment by yodidon** [comment]
Ça fonctionne avec la fenêtre du skin

**Comment by TmpName** [comment]
Bon de mon coté je viens de tester avec les deux, par le menu, et par la fenetre information
Pas de soucis de mon coté pour kodi 18

**Comment by Papounet58** [comment]
Je viens de tester avec la solution de Yodidon et cela fonctionne avec la fenêtre info du skin.
Pour ce qui est de la fenêtre info de Vstream cela ne fonctionne pas.
Merci à vous deux.

**Comment by TmpName** [comment]
Tu aurais le message d'erreur venant des logs ?

**Comment by Papounet58** [comment]
Bonjour TmpName,

Je n'ai aucun message d'erreur qui apparait.
Je vais tâcher de voir dans les logs.

Bonne journée

PS: ne te casse pas la tête sur ce sujet.
Le travail fait est déjà considérable.
Merci pour cela.

**Comment by Digidix** [comment]
Bonjour, @TmpName @yodidon

Je viens de réinstaller Kodi 19.1 sur Android et effectivement, j'ai ce problème, du coup, je me permets de mettre un petit fichier log : [kodi[1].log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6683038/kodi.1.log)

Je précise que les bandes annonces ne fonctionnent pas quel que soit le chemin par lequel on essaye d'y accéder au début, après une "fresh install", toujours le message échec de lecture, puis à force d'essayer sur la fenêtre du skin ca demande l'extension YouTube et ca fonctionne, mais sur la fenêtre Vstream ou via le menu contextuel le bouton bande annonce reste toujours sans effet.

J'en profite pour vous demander si l'extension YouTube est nécessaire pour les bandes annonces ou pour autre chose dans Vstream, car il me semble qu'elle n'est plus dans les dépendances de Vstream, et il y a quelques semaines les bandes annonces fonctionnaient sans avoir besoin de YouTube me semble t'il, alors que maintenant installer YouTube semble nécessaire.

Merci !

**Comment by TmpName** [comment]
Pas de bol ^^, tu as oublie d'activer les logs dans kodi non ?
Et non, je viens de relire le code, ca n'a pas l'air d'utiliser le plugin youtube.
Et la mise a jour du plugin youtube a ete faite le lendemain de la publication de la derniere version de kodi.

**Comment by Digidix** [comment]
> tu as oublie d'activer les logs dans kodi non ?

Normalement, non, avant de copier le log, j'ai réinitialisé l'application Kodi dans Android, et juste installé Vstream, je pense que les logs sont activés par défaut non ?

As-tu besoin d'un nouveau log ?

> Et non, je viens de relire le code, ca n'a pas l'air d'utiliser le plugin youtube.

Du coup, pourquoi sur tous mes appareils cela demande maintenant d'installer l'extension YouTube ?

> Et la mise a jour du plugin youtube a ete faite le lendemain de la publication de la derniere version de Vstream.

Cela a t'il une incidence par rapport à Vstream ?

Merci !

**Comment by TmpName** [comment]
Non, justement c'est desactivé par defaut.

>Du coup, pourquoi sur tous mes appareils cela demande maintenant d'installer l'extension YouTube ?

C'est pas nous, https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/addons.xml je viens de verifier, pas de youtube dedans.

>Cela a t'il une incidence par rapport à Vstream ?

C'est le hoster youtube qui affiche les videos des bande annonces, et pas le plugin youtube comme j'ai dis avant, désolé, je voulais parler du hoster youtube.

**Comment by Arias800** [comment]
Je viens de faire une correction pour mieux extraire les liens de Youtube. Il faut voir si ça règle le problème.

**Comment by Digidix** [comment]
@TmpName @Arias800 @yodidon
Après la mise à jour 1.3.0, les BA sont de nouveau fonctionnelles, vous êtes au top merci !
