### ISSUE TITLE
Bug source pastebin

### ISSUE THREAD

**Issue by Bakitaro** [Kodi-vStream/venom-xbmc-addons#3310]
Bonjour, 
Depuis la dernière mise à jour 1.2.0 de Vstream j'ai eu un bug, il y a la sources de mes liens qui apparaît sur le titre de mes liens Pastebin .

![Screenshot_20210602-032619_Kodi](https://user-images.githubusercontent.com/85225851/120459484-86dce180-c398-11eb-95f2-de127ba8e70c.jpg)

**Comment by sizanic** [comment]
Est-ce que cela le fait pour toutes les séries ?
J'ai essayé tout les codes Pastebin connus et aucun ne propose cette série (sous ce format S01E04).

Je ne peux pas reproduire ce problème ...

**Comment by sizanic** [comment]
Je n'ai pas vu que le sujet était fermé, cela veut dire qu'il n'y a plus le problème ?
