### ISSUE TITLE
tirexo autre adresse

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3311]
nouvelle adresse ou clone ?   **https://ww w2.tire xo.club/**
les liens uptobox et 1fichier sont accessibles... !

salutation
Christian

**Comment by Che-debarras** [comment]
> nouvelle adresse ou clone ? **https://www2.tirexo.club/**
> les liens uptobox et 1fichier sont accessibles... !
> 
> salutation
> Christian

C'est deja l'adresse affichée sur 
![Screenshot_20210602-172624_Samsung Internet](https://user-images.githubusercontent.com/44464129/120508069-b0613180-c3c7-11eb-9940-e7fd7ae16a05.jpg)

**Comment by sizanic** [comment]
En effet, c'est l'adresse que nous utilisons depuis vendredi dernier, elle est donc utilisée dans la version 1.2.0 qui est sortie ce samedi.

**Comment by kris06** [comment]
en effet,  je croyais que vous étiez sur www.tirexo.al ,   désolé,

C'est bien dommage que tirexo  ne soit plus accessible..   En plus des blocages DNS des FAI qui sont devenus de plus en plus gênants...   En effet certains de mes amis ne peuvent pas changer le DNS sur les box orange.

Merci pour votre super boulot,
'PS Pouvez vous réactiver 9docu ? cette source n'est plus accessible , merci)

**Comment by sizanic** [comment]
> certains de mes amis ne peuvent pas changer le DNS sur les box orange.

le DNS ne se change pas sur la box, il se change sur l'équipement où est installé KODI : 
Par exemple, changement de DNS sur un boitier android : 
https://www.pcastuces.com/pratique/astuces/4885.htm
(à moins que KODI soit installé directement sur la box de l'opérateur, je sais que Free et Bbox ont des boxs android, mais Orange 🤔 )



> Pouvez vous réactiver à l'occasion, 9docu ?

On active les sources que l'on sait traiter.

**Comment by kris06** [comment]
j'avais trouvé ce tuto mais ca ne concerne pas les box sous android TV ni même le nouveau chromecast google TV. Le changement de DNS sur ces appareils ne changent rien.
 Il faut attaquer à la racine par l'interface de l'operateur. Très facile chez free,  mais impossible chez orange.

**Comment by kris06** [comment]
On peut supposer alors voir un jour disparaitre vstream (?) quand les FAI mettront  toutes les sources utilisées en liste noire....
D'ici là,  le génie de votre équipe trouvera surement la parade
bonne continuation
C.

**Comment by Che-debarras** [comment]
> On peut supposer alors voir un jour disparaitre vstream (?) quand les FAI mettront toutes les sources utilisées en liste noire....
> D'ici là, le génie de votre équipe trouvera surement la parade
> bonne continuation
> C.

Le changement dns se fait dans la box tv dans reglages internet sinon il y a des applications conne DNS CHANGER qui changes le dns.
Tu installes l apk et tu t'assure que c'est bien connecté avant d'ouvrir kodi.

**Comment by kris06** [comment]
Merci Che-debarras, je connais cette appli et d'autres, mais pas une seule restent connectées après rallumage de la box

**Comment by Che-debarras** [comment]
> Merci Che-debarras, je connais cette appli et d'autres, mais pas une seule restent connectées après rallumage de la box

Malheureusement non aucune application ne reste automatiquement connecté puisque tu éteint ta box donc faut relancer l'application.
Ensuite tu peux dans les reglages reseau/wifi/ paramètres ip , changer le DNS dans Statique 
Tu peux aussi le faire dans la gestion du routeur via le navigateur,  tu te connecte avec ton id et mdp qui sont en général Admin et code wifi, tu vas dans LAN reseau local lan et tu edite pour ajouter les dns primaire et secondaire comme sur pc.
Ou tu fais de même si tu es en wifi dans WZN réseau etendu.

**Comment by freddykrueger59** [comment]
Bonjour à tous
Chez moi pour tirexo il ne me trouve rien , j'ai no information quelque soit la catégorie 
Avez vous la solution ?
Merci et bravo pour votre boulot

**Comment by sizanic** [comment]
Bonjour,
Nous n'avons pas la solution pour l'instant.
Des pistes très difficiles à mettre en place sont discutées ici : 
#3302

**Comment by sizanic** [comment]
Bonjour,
Nous n'avons pas la solution pour l'instant.
La protection mise en place est difficile à contourner.
