### ISSUE TITLE
Recherche par source

### ISSUE THREAD

**Issue by thorsten68** [Kodi-vStream/venom-xbmc-addons#3313]
Hello
Toujours chapeau bas pour votre boulot !!

Pensez vous qu'il serait possible de faire des recherches en ajoutant un filtre par source (ou plutôt hébergeur)

Je cherche essentiellement des films ou séries sur 1fichier. S'il y avait un filtre dans la recherche ça serait cool !!
Merci

**Comment by TmpName** [comment]
C'est assez complique vu qu'on ne fait que faire une recherche sur le site, on pourrait filtrer les resultats, mais ca voudrait dire que aleatoirement tu pourrais avoir des resultats ou pas, et parfois tu ne le saurais que sur la derniere page.

Le plus simple pour toi c'est de reperer les sites qui propose cet hargergeur, et n'activer que ceux la.

**Comment by sizanic** [comment]
Ce n'est techniquement pas possible car le nom de l'hébergeur n'est disponible qu'au dernier moment.
Souvent, entre le résultat d'une recherche et l'hébergeur, il y a plusieurs pages à défiler.
