### ISSUE TITLE
Probleme sous titre opensubtitles 

### ISSUE THREAD

**Issue by eol103** [Kodi-vStream/venom-xbmc-addons#3315]
Bonjour
Opensubtitles ne trouve aucun sous titre pour les film même en recherche manuel (exemple wars)
Par contre, cela fonctionne très bien pour les séries.
avez vous le même problème ?

kodi 19.1 sous andriod tv, vstream dernière version

Merci d'avance

**Comment by eol103** [comment]
Bonjour
J'ai essayé avec subscene : même problème. fonctionne avec les séries et pas les films.
J'ai essaye sur Windows 10 avec kodi 19.0 et dernière version vstream officiel. : même problème.

Merci de vos retours et avis

**Comment by alKODIque** [comment]
Mais as-tu réglé correctement dans les paramètre kodi la façon dont tu veux que tes sous-titres soient affichés? Il y a un réglage qui demande quel fournisseur tu veux pour les films, et quel fournisseur tu veux pour les séries..

Si tu n'as pas sélectionné les films, alors peu importe ce que tu choisis, seules les séries seront sous-titrées.

**Comment by alKODIque** [comment]
Voir dans Paramètres / lecteur / langue

(C'est tout au bas de l'écran)

![Screenshot_20210617-112259](https://user-images.githubusercontent.com/49578130/122426897-9f372980-cf5e-11eb-9bd9-0f205242eff7.png)

**Comment by eol103** [comment]
Bonjour

Merci pour ton retour
J'ai reverifié et j'ai bien le service predefini Opensubtitles  pour les films et les series TV

**Comment by alKODIque** [comment]
Bonjour :)

Je continue a croire qu'il s'agit d'un problème de configuration et que ça n'a rien a voir avec vStream...

Ce qui se passe avec un addon de sous-titre, c'est qu'un simple réglage peut tout faire foirer lol

Par exemple, si tu as réglé comme quoi tu souhaites que les sous-titres soient téléchargés et mis dans le dossier du film mais, que tu ne possède pas de dossier puisque tu stream: il y aura des problèmes...

Un autre exemple, si tu as omis de sélectionner le langage, ton addon de sous-titre ne trouvera rien.

Il y a 3 emplacements de réglages pour les sous-titres:
- à l'intérieur des paramètres de kodi (lecteur, comme sur mon image plus haut)
- à l'intérieur de l'addon de sous-titres (opensubtitles dans ton cas)
- via le OSD (au moment de la lecture)

si les paramètres de 1 entrent en conflit avec les paramètres d'un autre... et bien c'est des problèmes également.

Il faudrait revoir l'intégralité de ce que tu as paramétré puis si tu as toujours des ennuis, peut-être vérifier alors du côté du forum kodi, section des sous-titres. Parce que ce n'est pas un problème vstream j'en suis certaine...
Voici le lien pour le support officiel: https://forum.kodi.tv/forumdisplay.php?fid=143

(aussi, as-tu tes identifiants open-subtitles?, j'ai déjà lu, il me semble, que ça évite un tas d'ennuis!)

Bonne chance!! :)

**Comment by eol103** [comment]
Bonjour
Merci de tes retours.
J'ai refait un test. Opensubtitles fonctionne bien avec un film en local (recherche de titres automatique et manuel ok).
Par contre, des que je passe par vstream, cela ne fonctionne plus (opensubtitles ne trouve aucun sous titre lors de sa recherche pour les film.)
Comme cela fonctionne bien avec vstream pour les series, c'est comme si vstream n'envoyait pas la bonne catégorie à opensubtitles (exemple fictif : films ou lieu de movies ??) et qu'alors, opensubtitles ne cherche pas dans sa categorie film, mais dans une autre inconnu ??

Sinon la question de départ est de savoir si cela fonctionne chez d'autres personnes et dans ce cas, tu as raison, c'est un probleme de version ou de parametre

Merci en tout cas d'avoir repondu

**Comment by TmpName** [comment]
je confirme, je passe par "telecharger des sous titres" et effectivement ca marche pour le series, et pas les films, pourtant si je fais en manuel ca trouve quelque chose.
La recherche manuelle ne change que le titre, pas les autres meta datas ?

**Comment by eol103** [comment]
Bonjour
Pour moi, le problème existe depuis au moins 2 versions de vstream (mais peut etre depuis la 1.0 mais pas sur)

**Comment by TmpName** [comment]
Bon ben j'ai fais quelques tests, mais je vois rien de flagrant

**Fonctionne**
DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin OpenSubtitles.org('plugin://service.subtitles.opensubtitles/','4','?action=search&languages=English&preferredlanguage=Unknown','resume:false')
DEBUG: ### [__main__] - action 'search' called
DEBUG: CAddonSettings[service.subtitles.opensubtitles]: loading setting definitions
DEBUG: CAddonSettings[service.subtitles.opensubtitles]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[service.subtitles.opensubtitles]: loading setting values
DEBUG: ### [OSUtilities] - Search String [ titre_de_film ]
DEBUG: ### [OSUtilities] - Hash Standard file
DEBUG: ### [OSUtilities] - OpenSubtitles module hash [7684fa308fb0cf] and size [7270160]

**Marche pas**
DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin OpenSubtitles.org('plugin://service.subtitles.opensubtitles/','20','?action=search&languages=English&preferredlanguage=French','resume:false')
DEBUG: ### [__main__] - action 'search' called
DEBUG: CAddonSettings[service.subtitles.opensubtitles]: loading setting definitions
DEBUG: CAddonSettings[service.subtitles.opensubtitles]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[service.subtitles.opensubtitles]: loading setting values
DEBUG: ### [OSUtilities] - Search String [ titre_de_film]

**Comment by TmpName** [comment]
Ok j'ai un poil avancé.
C'est au niveau des espaces, pour une serie on a "un+titre+de+serie" mais pour un film on a "untitredefilm" 
Pour xbmc.getInfoLabel("VideoPlayer.OriginalTitle")

**Comment by sizanic** [comment]
UP,
juste pour ne pas oublier ..

**Comment by TmpName** [comment]
Je viens de rejeter un oeuil et je comprend encore  moins ...

```
2022-04-03 15:21:07.410 T:2416     INFO <general>: 	[PLUGIN] vStream: load site vf_serie and call function showSxE
2022-04-03 15:21:08.592 T:2416     INFO <general>: 	[PLUGIN] vStream: __sCleanTitle : Pilote Saison 1 Episode 1
2022-04-03 15:21:08.592 T:2416     INFO <general>: 	[PLUGIN] vStream: sTitle : Pilote 
2022-04-03 15:21:08.592 T:2416     INFO <general>: 	[PLUGIN] vStream: __sFileName : 
2022-04-03 15:21:08.592 T:2416     INFO <general>: 	[PLUGIN] vStream: __sTitle : 
2022-04-03 15:21:08.618 T:2416     INFO <general>: 	[PLUGIN] vStream: __sCleanTitle : Ya Shivu vs Bolshom Dome Na Kholme Saison 1 Episode 2
```
puis
```
2022-04-03 15:21:10.403 T:980      INFO <general>: 	[PLUGIN] vStream: load site vf_serie and call function showHoster
2022-04-03 15:21:11.694 T:980      INFO <general>: 	[PLUGIN] vStream: __sCleanTitle : La Fabuleuse Mme Maisel Saison 1 Episode 1 
2022-04-03 15:21:11.695 T:980      INFO <general>: 	[PLUGIN] vStream: sTitle : La Fabuleuse Mme Maisel  [COLOR skyblue]Vudeo[/COLOR]
2022-04-03 15:21:11.695 T:980      INFO <general>: 	[PLUGIN] vStream: __sFileName : 
2022-04-03 15:21:11.695 T:980      INFO <general>: 	[PLUGIN] vStream: __sTitle : 
```
et
`
2022-04-03 15:27:19.831 T:1396    DEBUG <general>: ### [resources.lib.OSUtilities] - Search String [ Pilote+S01E01 ]`

Il semblerait que la recherche ne fasse pas sur la derniere page
