### ISSUE TITLE
Uptobox k.o sur plusieurs support.

### ISSUE THREAD

**Issue by PunkyBust** [Kodi-vStream/venom-xbmc-addons#3316]
**Décrivez le bug**
Hello à tous, je viens de remarqué que je n'arrive plus à lancer des vidéos uptobox que ce soit depuis l'espace mon compte sur mon repo perso ou depuis les autres hosters. 
Je me prend une erreur (fichier introuvable), depuis uptobox direct (browser web) pas de soucis le fichier se lance sur mon compte perso. 
J'ai testé depuis deux support ma shield et mon téléphone même comportement.
Également réaliser plusieurs reinstall et clean de kodi sans effet. 
Merci beaucoup pour votre temps :)  

**Votre system**
 - OS: [Android]
-  Appareil [nvidia shield]
 - Version Kodi  [19.1]
- Version Vstream 1.2.0

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : uptobox (premium account) 
- Le Film : les flingueuse 
- hoster : wawacity

**Log**
Voir pièces jointes 
![DSC_1493](https://user-images.githubusercontent.com/63625157/122638919-58306c00-d0f7-11eb-8384-18fc1ca688e3.JPG)
![DSC_1492](https://user-images.githubusercontent.com/63625157/122638931-64b4c480-d0f7-11eb-89ba-a7e570897995.JPG)
![DSC_1491](https://user-images.githubusercontent.com/63625157/122638939-6f6f5980-d0f7-11eb-82b9-927598f7a039.JPG)

**Plus**
Dans les logs je vois une erreur, comme quoi le cookies ne parvient pas à être setté, je suis pas experte en code alors je me permet de vous solliciter votre aide. Je remarque que la phase d'authent ne semble pas se faire ou échoue. 
Vous pensez qu'il a un lien avec les maintenances effectué cette semaine chez uptobox ?

Les erreurs matche sur les fonction "oHoster.getMediaLink()" et le set de cookies

**Comment by PunkyBust** [comment]
J'ai refais un test pour avoir un log plus clean, en lançant la lecteur depuis l'espace mon compte sur le média "12 Deadly Days"
Désolé pour le spamm :/

![DSC_1494](https://user-images.githubusercontent.com/63625157/122639089-2ff53d00-d0f8-11eb-9a1c-9f005871b2dc.JPG)
![DSC_1495](https://user-images.githubusercontent.com/63625157/122639092-397ea500-d0f8-11eb-96a5-f0abb980f70d.JPG)

**Comment by TmpName** [comment]
Alors j'ai corrigé cette erreur, mais maintenant ca ve te donner "authentification raté", donc ca va pas resoudre ton probleme.

**Comment by PunkyBust** [comment]
Bah écoute ça remarche nickel avec ton update, accès restauré du coup. 
Merci Tmp pour ta disponibilité !
Et merci à tous les contributeurs vstream j'adore votre solution.

**Comment by PunkyBust** [comment]
Resolved
