### ISSUE TITLE
Page suivante absente - Trakt

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3317]
Bonjour,
Un petit bug noté dans notre compte Trakt...

Si nous avons plusieurs listes aimées, et que nous avons laissé les paramètres par défaut qui est de 10 éléments par page, nous n'avons pas accès à plus de 10 éléments puisque l'option d'afficher la page suivante n'y est pas.
 (je parle bien du nombre de listes et non du nombre d'élément dans une liste)

Merci :)

EDIT: le problème est présent pour toutes les listes, sauf mes listes personelles... Pour celles-ci, je les vois bien toutes, même en laissant à 10 le nombre d'éléments par page dans les paramètres

**Comment by sizanic** [comment]
Traité ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3453
