### ISSUE TITLE
recherche

### ISSUE THREAD

**Issue by lil78711** [Kodi-vStream/venom-xbmc-addons#3318]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.
bonjour j'ai un probleme depuis la mise a jour  la recherche dure une plombe  pareil quand je clique sur une source seul "derniers films" ca met trop longtemps meme parfois que dalle arrive   je me pose la question si quelqu'un a eu le mme probleme ou si vous pensez que  c'est mon fournisseur qui bride ma connection merci a vous

**Comment by lil78711** [comment]
box android mx  kodi matrix

**Comment by TmpName** [comment]
Non je pense que les sites doivent etre saturés et mettre trop de temps a repondre.
Normallement tu as les sites qui defilent durant la recherche, reperes celui qui freine et desactive le pour voir.

**Comment by lil78711** [comment]
alors bizarre je suis connecte en cable ethernet avec un repetiteur  je les deconnecter et je suis passer en wifi et la ca marche

**Comment by TmpName** [comment]
Lol, la ca m'echappe aussi ...

**Comment by donguiza** [comment]
pour moi cette extension se lance aléatoirement avec Vstream parfois elle fonctionne parfois nn. je comprends pas pk

**Comment by sizanic** [comment]
Tu as peut-être une configuration différente entre ta carte Ethernet et ta carte wifi au niveau du DNS.
