### ISSUE TITLE
Un peu d'aide ?

### ISSUE THREAD

**Issue by freddykrueger59** [Kodi-vStream/venom-xbmc-addons#3320]
Bonjour et merci pour cet Addon et le boulot que vous faites .
Celà fait longtemps que je l'utilise mais depuis quelques temps ça ne fonctionne plus . J'utilise principalement 3 source qui sont Wawa , zt , et tirexo
J'ai bien accès aux catégories mais après plus rien ,aucun résultat 
Pourriez vous m'éclairer svp ?
Merci encore

**Comment by sizanic** [comment]
Bonjour,
Des discussions à propos de ces sources sont déjà en cours car reconnues comme ayant des soucis d'accès. : 
#3300 
#3311

**Comment by sizanic** [comment]
Nous corrigeons les sources au fur et à mesure.
Il faut attendre les mises à jours pour en profiter.
