### ISSUE TITLE
Uptobox

### ISSUE THREAD

**Issue by Jaunattend** [Kodi-vStream/venom-xbmc-addons#3321]
Bonjour.

Depuis le passage à la v 1.2 je n'arrive plus à accéder à ma bibliothèque Uptobox via Mes comptes. Quand je clique dans "Uptobox" sur "Mes fichiers et Dossier" j'ai une recherche qui n'aboutit pas et je reste dans le menu.

Je n'ai rien modifier de particulier et j'ai un compte premium enregistré. Quand je passe par hostdirect avec un lien de ma bibliothèque ça fonctionne impeccable en revanche.

Système :
 - Android
-  Shield
 - Kodi 19.1
-  Vstream 1.2

Merci pour votre super travail. 👍

**Comment by thorsten68** [comment]
Moi aussi sur shield et le même problème déjà signalé sur 1 fich
Retourné à la version 1.1 et du coup ça fonctionne à nouveau

**Comment by thorsten68** [comment]
#3305

**Comment by thorsten68** [comment]
Chez moi le problème est résolu avec la mise à jour 1.3
Merci pour le taf !!!!

**Comment by Jaunattend** [comment]
Salut, 

Le soucis est toujours présent après le passage en 1.3.

**Comment by TmpName** [comment]
Suite ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3377
