### ISSUE TITLE
problème notification chargement

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3322]
notification du chargement tourne en boucle sur HDS.to  ..
voir image jointe

 - Windows 
-  Appareil freebox et autres
 - Version Kodi  19.1
- Version Vstream 1.2.0

![007](https://user-images.githubusercontent.com/31409100/124251672-7c903d80-db26-11eb-9734-17ccb89e0d87.jpg)

**Comment by Che-debarras** [comment]
Ce  n'est pas que pour hds, j'utilise frchstrm.lol et wiflix et il arrive que cette notification s'affiche.
Je suis obligé de redemarer kodi pour la faire disparaître

**Comment by sizanic** [comment]
Le code a trop changé depuis.
Il faudra rouvrir un ticket si le probleme ne s'est pas corrigé par les différentes modifications apportées depuis.
