### ISSUE TITLE
Fichier introuvable 1fichier

### ISSUE THREAD

**Issue by tuncay8872** [Kodi-vStream/venom-xbmc-addons#3332]
Bonjour,

Il y a quand même une différence entre le 1.1.0 et la dernière version bêta pour 1fichier.

Avec la 1.1.0 nous n'étions pas obligé de désactiver dans les paramètres 1fichier "Forcer l'affichage du menu pour les téléchargements"

Et a cause de cela je n'arrive pas a sauvegarder les liens dans le compte.  Ca commence le téléchargement directement. 

Pourriez-vous voir cela svp ?

Cordialement.

 - OS: [Android]
-  Appareil [TV philips Android tv]
 - Version Kodi  [18.9]
- Version Vstream 1.3.1 beta de ce jour et comparaison avec 1.1.0

**Comment by TmpName** [comment]
Alors va falloir que tu m'explique.
Je viens de lire le code, apparement il rajoute "'&e=1" pour utiliser cette option.
Donc comment on devrait faire, quelle est l'url de depart et quel est l url que l'on doit utiliser ?

Le bug ne viendrait pas justement qu'il y aurait deja "'&e=1" dans l'url ?

**Comment by tuncay8872** [comment]
Salut
Quand l'option "forcer le menu d'affichage..." est activé, cela me met "fichier introuvable" avec Vstream beta. Avec vstream 1.1.0 ça ouvre bien la video

**Comment by TmpName** [comment]
Tu pourrais modifier ton fichier avec

```
            # L'option est activée : pour récupérer le lien direct il faut POSTer le formulaire demandant le download
            else:
                cookie = self.oPremiumHandler.AddCookies().replace('Cookie=', '', 1)
                VSlog(cookie)
                data = {
```

 et refaire passer quelques logs ?

**Comment by izno69** [comment]
Salut
Depuis la version 1.0 les fichiers ne sont plus lu...
J'ai le meme probleme. J'ai installé la 1.3.1 idem les fichiers sont sont visibles mais ne se lancent pas depuis mon rasperry sur librelec

**Comment by tuncay8872** [comment]
Pour l'instant utilise le 1.1.0
Je vais essayer d'aider demain pour que TmpName trouve :)

**Comment by Peur** [comment]
> Salut
> Depuis la version 1.0 les fichiers ne sont plus lu...
> J'ai le meme probleme. J'ai installé la 1.3.1 idem les fichiers sont sont visibles mais ne se lancent pas depuis mon rasperry sur librelec

Bonjour,

Je suis bien content que tu relance le sujet sur la non lecture des films sur 1fichier.com.

J'avais déjà posté le problème il y a quelques temps .. Mais aucune solution n'a pu être apporté.
Pour moi depuis la version Matrix de kodi, 1Fichier ne fonctionne plus... et ceux malgré les 3 dernières versions de mise à jour que vous avez mis en place.

Le problème se produit sur mes 4 appareils Android.
TV Thomson Android
Boitier Z28 Android
Boitier H96 Max Android
Téléphone Galaxy A45 5G

J'ai été obligé  de repasser en 18.9 et vstream 1.1.0 sur le Boitier Z28.

C'est un problème récurant depuis très longtemps quad même.

**Comment by TmpName** [comment]
La version de one fichier de Vstream 1.1.0 fonctionne chez toi ?
Et si tu utilises le meme fichier mais dans une version recente ? Je viens de regarder le code il n'y a rien de specifique a cette version.

**Comment by tuncay8872** [comment]
La seul façon pour que ça marche c'est kodi 18 avec vstream 1.1.0

Avec kodi 19 et vstream 1.1.0 ça met quand même "fichier introuvable"

J'ai installé uniquement vstream à kodi

La je vais essayer avec la beta vstream et kodi 18 + 19

**Comment by tuncay8872** [comment]
Avec la beta vstream Fichier introuvable avec kodi 18 et kodi 19

**Comment by tuncay8872** [comment]
Pour les logs je test uniquement sur kodi 18 ?

**Comment by TmpName** [comment]
Ben de mon coté je suis encore sous kodi 18, donc je pourrais pas comparer sous kodi 19

**Comment by Peur** [comment]
Mais sinon, c'est quand la version de vstream qui fonctionne avec Kodi 19 ?

**Comment by TmpName** [comment]
Ben quand y aura quelqu'un avec la version 19, un compte 1fichier pr tester et qui pourra se pencher sur le code ^^.
De mon coté je passerais pas sous kodi 19 avant 3 mois.

**Comment by sizanic** [comment]
J'ai pas mieux comme réponse.

Et ce n'est pas non plus dans la liste mes priorités.

Les personnes trop pressées peuvent venir participer ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/onefichier.py

**Comment by Peur** [comment]
> J'ai pas mieux comme réponse.
> 
> Et ce n'est pas non plus dans la liste mes priorités.
> 
> Les personnes trop pressées peuvent venir participer ici :
> https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/onefichier.py

Désolé te t'avoir froissé. Ce n'était pas mon but.

Je ne me sens pas pressé vu que cela fait plus de 5 mois que ce ne fonctionne pas ^^

Et j'avoue être très surpris que le problème de 1fichier ne soit pas une priorité pour la Team Vstream. Etant donné qu'à peu près 40% des liens fournis viennent de 1fichier.com. 

Résultat on pourrait avancer que Vstream ne fonctionne qu'à 60% depuis 6 mois malgré les mises à jours successives.

Espérant que notre conversation ai pu être constructive pour le bien de ce superbe Addon.

Fred

**Comment by alKODIque** [comment]
@Peur 
J'ai plutôt l'impression que les gens utilisent beaucoup plus les services d'un débrideur (Alldebrid, Real-Debrid..) ou préfèrent l'hébergeur Uptobox à 1Fichier..
Ce qui rend vStream fonctionnel à 100%
;)

**Comment by sizanic** [comment]
Bonjour Fred.

tu ne m'as pas froissé 👍 
c'est juste que ta question était mal posée.
Nous n'avons aucune idée de quand cela sera corrigé.

Quand à tes chiffres, ils ne sont pas bons.
Car si 40% des liens proposés sont des liens 1fichier, il faut prendre en considération que seulement 2 % des utilisateurs de vStream utilisent ce service (estimation personnelle, comme la tienne 😉 ).

Donc le souci ne touche que ces 2% d'utilisateurs, qui peuvent toujours se rabattre sur les 60% autres liens 😄 

J'estime donc vStream fonctionnel à plus de 95% sur cette partie (lien disponibles/utilisables)

Tu comprendras que nous ne considérons pas ce dysfonctionnement comme une priorité.

**Comment by Arias800** [comment]
Il faut prendre en compte quelque chose, on n’est pas une équipe au sens structurel du terme.
On n'a tous des préoccupations différentes sur l'addon. D'autant plus qu'on est peu nombreux comparer au travail que demande le maintien de l'addon.

**Comment by Arias800** [comment]
Et je parle même pas du fait qu'il faut que l'ont doit attendre a 50 ans après chaque test à cause des limitations à la con de l'hébergeur.

**Comment by MalibuKoKo** [comment]
Hello,

Effectivement, j'ai moi aussi le problème depuis quelques semaines ... je m'étais résigné à lancer le tout via vlc mais ce n'est pas des plus pratique :-(

Merci à @tuncay8872 pour la version encore fonctionnel ( 1.1.0 ).

J'ai testé de mon côté sous Kodi 18.9 ( histoire d'éliminer le problème de KODI 19 ). En testant commit après commit j'ai trouvé celui qui est responsable de ce bug et c'est le commit : be10169d855c0c8012c045b21f2eea1de4d6c710

Si on repasse sur le précédent commit: 905a6d9f48dd49995177bea5ce01be795d588617 ... tout fonctionne bien.

Il y a eu visiblement une grosse grosse refacto, cf. https://github.com/Kodi-vStream/venom-xbmc-addons/commit/be10169d855c0c8012c045b21f2eea1de4d6c710

@Arias800 @TmpName 
Je regarde si je peux vous aider à corriger ça.

**Comment by Peur** [comment]
> Hello,
> 
> Effectivement, j'ai moi aussi le problème depuis quelques semaines ... je m'étais résigné à lancer le tout via vlc mais ce n'est pas des plus pratique :-(
> 
> Merci à @tuncay8872 pour la version encore fonctionnel ( 1.1.0 ).
> 
> J'ai testé de mon côté sous Kodi 18.9 ( histoire d'éliminer le problème de KODI 19 ). En testant commit après commit j'ai trouvé celui qui est responsable de ce bug et c'est le commit : [be10169](https://github.com/Kodi-vStream/venom-xbmc-addons/commit/be10169d855c0c8012c045b21f2eea1de4d6c710)
> 
> Si on repasse sur le précédent commit: [905a6d9](https://github.com/Kodi-vStream/venom-xbmc-addons/commit/905a6d9f48dd49995177bea5ce01be795d588617) ... tout fonctionne bien.
> 
> Il y a eu visiblement une grosse grosse refacto, cf. [be10169](https://github.com/Kodi-vStream/venom-xbmc-addons/commit/be10169d855c0c8012c045b21f2eea1de4d6c710)
> 
> @Arias800 @TmpName
> Je regarde si je peux vous aider à corriger ça.


Serais tu le sauveur des minorités ?

**Comment by MalibuKoKo** [comment]
C'est fonctionnel pour moi, je vous laisse réviser la pull request: https://github.com/Kodi-vStream/venom-xbmc-addons/pull/3337

**Comment by TmpName** [comment]
Je viens de valider le PR, mais ca change vraiment quelque chose ?
Pour moi ca avait un impact qu'en cas d'erreur, donc quand ca ratait ?

**Comment by MalibuKoKo** [comment]
> Je viens de valider le PR (l'oubli devait venir de moi en plus), mais ca change vraiment quelque chose ?
Pour moi ca avait un impact qu'en cas d'erreur, donc quand ca ratait ?

La correction que j'ai apporté c'est ajouter les dépendances qui avaient été enlevés, donc forcément sans ces dépendances il était levé une exception.

Donc oui ça change tout ... du code qui dépend d'une dépendance ne peut pas être exécuté si la dépendance n'est pas là ...

Si ta question est de comprendre pourquoi ce bout de code est là c'est justement ce qui est indiqué

> La partie ci-dessous permet d'utiliser l'option "Forcer l'affichage du menu pour les téléchargements" permettant notamment de choisir depuis l'interface web de télécharger ou d'ajouter un fichier. Pour cela, on va ajouter le paramètre e=1 (cf. https://1fichier.com/hlp.html#dev ) à la requête permettant d'obtenir le lien direct

Si l'option est activée pour récupérer le lien direct il faut POSTer le formulaire demandant le download.


Un dernier point, la correction apportée ne fonctionne pas sous Kodi 19 (problème avec urllib et urllib2), du coup j'ai essayé d'utiliser urllib3

cf. patch ci-dessous :
[3332.patch.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/6870200/3332.patch.txt)

la vidéo se lance sous Kodi 18.9 et Kodi 19 mais par contre j'ai un cercle de chargement qui reste au premier plan ...

Une idée ?

**Comment by sizanic** [comment]
Le cercle de chargement peut arriver avec un mauvais player.
As-tu le player par défaut : 
![image](https://user-images.githubusercontent.com/47307622/126818814-cad5440a-e50f-446c-a394-425151e0daaf.png)

**Comment by MalibuKoKo** [comment]
@sizanic : effectivement c'était bien le paramètre concernant le player ... je sais pas pourquoi j'ai touché à ça.

Nouvelle pull request : https://github.com/Kodi-vStream/venom-xbmc-addons/pull/3341

J'utilise **urllib3** et d'après mes tests ça fonctionne bien sous Kodi 18.9 et Kodi 19.

**Comment by MalibuKoKo** [comment]
Un dernier point, je vois que **urllib3** est utilisé à certains endroits, par exemple :
[plugin.video.vstream/resources/lib/cloudscrape/help.py](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/cloudscrape/help.py)

Mais le fichier [plugin.video.vstream/addon.xml](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/addon.xml) ne précise pas de dépendance à **urllib3**.

Ne faudrait il pas ajouter dans le bloc XML /addon/requires la ligne ci-dessous ?
`<import addon="script.module.urllib3"/>`

**Comment by TmpName** [comment]
Ben c'est pas une lib presente par defaut ?

**Comment by Peur** [comment]
Hello,

De nouveau, Vstream et 1fichier.com fonctionnent.

**Merci** à tous ceux qui ont participé à la réparation.

**Comment by Arias800** [comment]
Je ferme vu que ça remarche.
