### ISSUE TITLE
INFORMATIONS ZONE TELECHARGEMENT !

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3333]
Pour ceux qui veulent télécharger illégalement des séries, films ou jeux vidéo, Zone-téléchargement est l’adresse incontournable. Cependant, l’adresse change régulièrement… Informations Complémentaires au h ttps://www.meilleure-innovation.com/quelle-est-la-nouvelle-adresse-officielle-de-zone-telechargement/#nvurlzt2020

**Comment by TmpName** [comment]
La je suis désolé, mais c'est du pur warez, pas trop d'interet dans le developpement d'une l'application.
