### ISSUE TITLE
Tirexo

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#3334]
Salut les gars, je sais pas si vous avez vue mais la source Tirexo est sans CF depuis 2 semaines maintenant.
On peut afficher les pochettes dans Vstream mais pas avoir les liens.
Si vous avez le temps où d'autres choses à faire il y a pas de souci mais juste savoir si vous comptez mettre à jour la source ?

Merci à vous d'avance

**Comment by Che-debarras** [comment]
Ya deja pas mal de source a corriger avec juste changement url, mais bon

**Comment by lebigboss** [comment]
Merci à @Arias800  d'avoir ajouter Tirexo.
Merci beaucoup

**Comment by sizanic** [comment]
Je viens de changer l'adresse de Tirexo avec la nouvelle, et maintenant plus aucun film ne s'affiche 😆 
Des modifications semble nécessaire.

**Comment by lebigboss** [comment]
@sizanic  saboteur !!! Assassin !!!

Lollll bon bah j'attendrai alors

**Comment by sizanic** [comment]
j'ai fait les corrections nécessaire hier, et au moment de mettre à jour le fichier dans l'extension, j'avais plein de conflits car je n'étais pas partie de la dernière version du fichier.

Donc ce soir c'est gestion des conflits pour ne pas perdre les modifications faites par les autres !

**Comment by sizanic** [comment]
Bon bah finalement, un autre dev est passé avant moi et tout à été corrigé.

**Comment by lebigboss** [comment]
@sizanic  un dev masqué ?? 

Après il y a encore des soucis sur Tirexo, tout ne fonctionne pas parfaitement mais c'est déjà pas mal.
Merci à vous

**Comment by Azertixe** [comment]
Bonsoir. Pour moi ça ne marche toujours pas.
Les liens n'apparaissents pas. J'ai juste un message "Qualités disponibles pour ce film" et rien en dessous 😭

**Comment by sizanic** [comment]
Bonsoir,
Lorsque l'on dit que c'est corrigé, c'est dans la version en cours de développement.
Ce n'est donc pas disponible dans la version officielle.
=> a moins que tu es installé une version Beta pour tester ?

**Comment by Azertixe** [comment]
Bonsoir. Tout s'explique 😁
Comment est-ce qu'on installe la version bêta ? 
Mercipar avance

**Comment by sizanic** [comment]
La version Beta doit être utilisé pour nous aider à chercher des bugs, pas pour utiliser des corrections en avant-première.
Une version Beta peut être instable.

Nous publions une version par mois.

Une nouvelle version ne devrait plus tarder.
Il serait plus sain d'attendre cette version que de tenter d'installer une version Beta.

**Comment by Che-debarras** [comment]
@sizanic 
Tu dis ne pas devoir recevoir mes reports de bugs car je vous payes pas mais tu te gene pas pour t'en servir.
Je suis pas payé non plus pour faire ce suivi qui t'arrange.
Jte trouve pathétique d'avoir copier coller mon suivi sans ma permission et en plus meme ici tu dis que la beta c'est pour le report de bug

Tu es plein de contractions et le fait de me critiquer et d'utiliser mon suivi montre que tu es hypocrite.
Profite bien de ce suivi de bug que tu t'es approprié contre mon gré mais il n'en aura plus d'autres.

**Comment by TmpName** [comment]
@Che-debarras
J'ai deplacé ton post https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3330

Car pas besoin de declencher des guerres partout.

**Comment by Che-debarras** [comment]
J'ai décidé de reporter ton comportement car tu n'as pas le droit d'utiliser le compte des autres pour republier leur messages.
Donc tu peut mettre mes msg off topic mais si tu a une fierté tu utiliserais pas mes suivis et mes messages.

Donc je vais signaler ton comportement et pour quelqu'un qui veut pas de mes reports bizarre que tu en meurt d'envie de les utiliser

**Comment by Che-debarras** [comment]
Tu essaie de supprimer mes messages pour le museler mais quand il s'agit de mon aide tu vas deterrer mes msg supprimés pour les utiliser toi qui dis que je ne doit pas reporter de bug car je te paye pas.

Tu as cru que mal me parlé aller te faire profiter de mon temps libre de mon suivi comme si j'étais ton employé ?

Je suis pas payé pour faire le suivi et pourtant je le fais de bon coeur pour aider alors que les corrections n'a aucune importance pour moi car bugs ou correction na aucun impact sur mon kodi.

Ta prémédité que j'allais plus partager mon suivi que tu tes précipitez a le copier mais bon j'ai signalé ton comportement abusive d'utiliser le compte des autres pour republier leur messages supprimés dont tu n'est ni l'auteur ni le propriétaire 

Donc jte conseil de les supprimer immédiatement et de ne plus utiliser mon travail sans ma permission (et puis sois honnête avec toi meme)

**Comment by KoRnEr007** [comment]
Ah mince, on peut etre payé dans ce projet ?
j'ai loupé qqch ....

**Comment by Che-debarras** [comment]
> Ah mince, on peut etre payé dans ce projet ?
> j'ai loupé qqch ....

D'après les @sizanic ils ne sont pas payés pour corriger les bugs donc on ne doit pas les reporter.
Donc selon sa logique,  cela doit être dans les 2 sens: on est pas payé non plus pour reporter les bugs 
Et dans cette logique,  la version beta ne devrait pas existe ni meme "issues" ne devrait pas exister.

Bref la logique de @sizanic n'a jamais tenue la route son pseudo aurait du etre "titanic" car à chacune de ses remarques ou logiques il sombre dans le large.

S'il a pas besoin de nos reports qu'il ne vient pas utiliser mon suivi. Mais le fait de les republier prouvent qu'il en a besoin. 
Donc soit il descend de son piedestal et commence a respecter ce qui aide soit il se tais et n'utilise pas le travail des autres.

Qu'il soit honnête avec lui même et qu'il supprime mon suivi et mes message (de toute façon j'ai reporté son comportement abusive)

**Comment by KoRnEr007** [comment]
Mais tu as reporté à qui son comportement ?
Sizanic a fait beaucoup de dev, il continue a en faire beaucoup sur pastebin. Car c'est une source dite fiable car elle est quasi maitrisée à 100% par rapport a ZT tirexo etc qui eux peuvent changer tous les matins leurs parametres de sécurité.

Bon je ne comprend pas trop ce que tu lui reproches mais j'ai pas trop suivi l'histoire.

Je pense que si il a effacé tes messages c'est qu'il devait y avoir une bonne raison.

**Comment by TmpName** [comment]
Bon alors, deja pour info le github est pour le developpement, pas pour le reglement de compte, donc je vais laisser cette issue ouverte le temps que cela se termine et je ferme tout apres.

>car tu n'as pas le droit d'utiliser le compte des autres pour republier leur messages

Il n'a quand meme pas publie quelque chose sous ton pseudo ? A moins d'avoir accé a ton compte.

Ensuite, personne n'est payé, les developpeurs ne gagnent rien de plusa corriger les bugs que les users a les signaler. C'est juste un passe temps, comment on peut autant se prendre le tete avec un passe temps ?

Tout est "open" sur github, si quelqu'un ne veut pas que quelque chose soit re-utilisé, il suffit de le signaler, sinon c'est public et re-utilisable, surtout que tout est tracé et daté, donc pas dur de justifier la proprieté du concept.

**Comment by Arias800** [comment]
Et je rappelle un truc : Sur le Discord il y a TOUT les logs du github, y compris les messages supprimés.

**Comment by Che-debarras** [comment]
> Mais tu as reporté à qui son comportement ?

Au modérateur de Github qui possède le site. Il n'appartient pas aux utilisateurs comme toi ou moi ou sizanic.
Tu crée un compte mais le site ne t'appartient pas, donc tu peux pas jouer avec les comptes des autres ou le messages des autres.
Si tu effaces un msg,  sizanic n'a pas le droit de le republier ou utilisé ton compte pour republier un msg que tu as supprimé 

> Sizanic a fait beaucoup de dev, il continue a en faire beaucoup sur pastebin. Car c'est une source dite fiable car elle est quasi maitrisée à 100% par rapport a ZT tirexo etc qui eux peuvent changer tous les matins leurs parametres de sécurité.

Mais on s'en fout de ce qu'a fait sizanic ça ne lui donne pas le droit de manquer de respect au gens et de profiter du travail des autres sans leur consentement ou d'utiliser le compte des autres pour deterrer des messages supprimés 

> Bon je ne comprend pas trop ce que tu lui reproches mais j'ai pas trop suivi l'histoire.

Si tu comprends pas c'est que tu n'as pas lu les messages de sizanic qui depuis quelques jours semble vouloir le manquer de respect et surtout parce que j'ai supprimé mon issue et qu'il a republié sans mon accord.
C'est pas la première fois que je sizanic me manque de respect , c'est devenu son passe temps desormais

> Je pense que si il a effacé tes messages c'est qu'il devait y avoir une bonne raison.
Non justement,  son hypocrisie ou son immaturité c'est qu'il peut supprimer mes messages qui le remet en cause mais il a pas su accepter que je supprime mon suivi de bugs 1.3.1 dont il a republié sans mon accord.
Comme il a dis que je ne le paye pas pour corriger des bugs alors il est  normal que je ne reporte aucun bug donc j'ai supprimé mon suivi de bug.

Mais il est tellement contradictoire et hypocrite qu'il a déterré mon suivi

**Comment by alKODIque** [comment]
@TmpName
Che est tellement hors contexte qu'il a confondu le fait que tu as déplacé son commentaire... il en veut tellement a sizanic qu'il croit que c'est lui... 
Bref, je suis d'accord avec toi que github est open... mais ca ne justifie pas de laisser des gens insulter les autres comme Che debarras le fait..  depuis longtemps!! Comme plusieurs, j'en ai été victime. Alors si quelqu'un doit être dénoncé ici, c'est bien lui!!

**Comment by Che-debarras** [comment]
> Il n'a quand meme pas publie quelque chose sous ton pseudo ? A moins d'avoir acces a ton compte.

Si justement car le suivi contient mon pseudo et j'ai bien supprimé le message et le suivi mais il a tout republié 

> Ensuite, personne n'est payé, 
Dis ça a sizanic qui a parlé d'argent pas moi 

> Tout est "open" sur github, si quelqu'un ne veut pas que quelque chose soit re-utilisé, il suffit de le signaler, sinon c'est public et re-utilisable, surtout que tout est tracé et daté, donc pas dur de justifier la proprieté du concept.
Il n'est pas permis d'utiliser le compte d'un autre pour republier ses mesages supprimer
Va voir le suivi 1.3.1 @sizanic se l'est approprié apres que je l'ai supprimé

**Comment by TmpName** [comment]
Ha ok ^^
Donc c'est moi qui "caché" le commentaire, il  est toujours la, il faut juste le faire apparaitre, car pour moi il etait hors sujet par rapport au titre de lissue.

**Comment by Che-debarras** [comment]
> Et je rappelle un truc : Sur le Discord il y a TOUT les logs du github, y compris les messages supprimés.

Je te parle pas de discord mais de github

**Comment by Arias800** [comment]
Oui, et je parle bien des messages d'ici. J'ai bien tous les messages du Github, même si ils ont été supprimés ici.

**Comment by Che-debarras** [comment]
> @TmpName
> Che est tellement hors contexte qu'il a confondu le fait que tu as déplacé son commentaire... il en veut tellement a sizanic qu'il croit que c'est lui...
> Bref, je suis d'accord avec toi que github est open... mais ca ne justifie pas de laisser des gens insulter les autres comme Che debarras le fait.. depuis longtemps!! Comme plusieurs, j'en ai été victime. Alors si quelqu'un doit être dénoncé ici, c'est bien lui!!

Voila le fameux toutou de sizanic qui lui aussi j'ai beau lui dire de pas interferer dans mes messages mais il a pas de vie apparemment

Il va expliquer a une personne qui a un problème avec un autre qu'il est hors contexte 
Parce qu'il sait mieux où est le problème et se la joue victime mdr

Depuis assez longtemps je signale le problème de communication ne alkodique et sizanic qui rabaisse les gens

Et le problème viens du suivi 1.3.1 qui a été republié alors que je l'ai supprimé 
Je ne parle pas d'un quelconque messages qui a été déplacé ou caché 

Allez voir dans les sujet clos : le suivi 1.3.1 a été remis par @sizanic donc j'ai supprimé et que je veux pas qu'il soit réutilisé #3330

**Comment by TmpName** [comment]
>Si justement car le suivi contient mon pseudo et j'ai bien supprimé le message et le suivi mais il a tout republié

J'ai pas du tout suivi l'histoire.
- Tu voulais que ton commentaire reste ou pas ?
- Tu voulais qu'on sache que c'etait de toi ou pas ?

**Comment by Che-debarras** [comment]
> Oui, et je parle bien des messages d'ici. J'ai bien tous les messages du Github, même si ils ont été supprimés ici.

Je te pensais bien plus intelligent (drole de voir ce tout alkodique liker toute le monde lol)

Qu'il soit visible sur discord ce n'est pas le problème 
Que tu vois un msg supprimés cela est pas normal car c'est supprimer 
Mais meme ça c'est pas le problème 
Le problème c'est une fois supprimé il doit le rester et pas le republier 

Moi je refuse que mes msg supprimés soit republier

**Comment by Che-debarras** [comment]
> > Si justement car le suivi contient mon pseudo et j'ai bien supprimé le message et le suivi mais il a tout republié
> 
> J'ai pas du tout suivi l'histoire.
> 
> * Tu voulais que ton commentaire reste ou pas ?
> * Tu voulais qu'on sache que c'etait de toi ou pas ?

Tu parles de quoi ? Jte parle de #3330 
Il a été republié par sizanic alors que je l'ai supprimé 
Donc je veux que suivi sois supprimé 

Cette issue a été faitr par moi mais sizanic se l ai approprié 
Je peux ni le modifier ni le supprimer car il a mis son pseudo 

Comprend tu le problème maintenant ?

**Comment by Arias800** [comment]
Et je n’ai pas l'attention de les republier ou je ne sais quoi.
D'ailleurs, c’était absolument pas une menace, je ne vois pas pourquoi tu le prends comme ça.

**Comment by TmpName** [comment]
>Moi je refuse que mes msg supprimés soit republier

Si c'est que ca, donnes nous le lien vers le message pour le supprimer, il a pu faire un c/c avant que tu le supprimes, c'est pas forcement fait pour te nuire, et si tu effaces tes messages, rien ne peut prouver que son copier/coller vient de toi. C'est pas dur de trafiquer un c/c.

**Comment by Che-debarras** [comment]
> Et je n’ai pas l'attention de les republier ou je ne sais quoi.
> D'ailleurs, c’était absolument pas une menace, je ne vois pas pourquoi tu le prends comme ça.

Dis ça a sizanic qui a republié mon suivi apres l'avoir supprimé

**Comment by alKODIque** [comment]
C'est vrai, je t'aime pas!!! Parce que tu agis méchamment et injustement. 🤷‍♀️
Mais sache que même si je ne t'aime pas, je serais ''ton petit toutou'' a toi si c'était sizanic qui serait dans le tort... car je suis capable de discerner qui a du sens et qui en a pas.. 

 Tu peux m'insulter sur le fait que je n'ai pas de vie. C'est peut-être le cas!!! Tu n'as aucune idée de ce qu'est ma vie et ca a rien a voir avec le développement de vStream qui ne t'appartient pas je te signale. C'est open source. 
Mais j'insulte personne, contrairement a toi

**Comment by TmpName** [comment]
Bon ca part en sucette la.

Merci de donner le lien qui pose probleme, pour corriger le tir, pas besoin d'une guerre pour ca.

**Comment by Che-debarras** [comment]
> > Moi je refuse que mes msg supprimés soit republier
> 
> Si c'est que ca, donnes nous le lien vers le message pour le supprimer, il a pu faire un c/c avant que tu le supprimes, c'est pas forcement fait pour te nuire, et si tu effaces tes messages, rien ne peut prouver que son copier/coller vient de toi. C'est pas dur de trafiquer un c/c.

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3330#issue-938143596

Tu vois bien que c'est pas un copier coller 
Il a republié mon issue , annuler la suppression et se l'est approprié avec son pseudo  
C'est mon pseudo mais désormais editer par lui donc maintenant seule sizanic a acces pour editer modifier supprimer 
![Screenshot_20210801-135630_Samsung Internet](https://user-images.githubusercontent.com/44464129/127770059-789c2d2f-fc04-4229-8995-cc4aa38ebdd4.jpg)

Et j'espère que personne n'est assez gamin pour copier coller mon msg

**Comment by Che-debarras** [comment]
> Bon ca part en sucette la.
> 
> Merci de donner le lien qui pose probleme, pour corriger le tir, pas besoin d'une guerre pour ca.
> 
> (et le lien du post, pas d'un topic de 100 posts)

Sauf que le post en question est un topic vu que c'est le 1e post d'un issue
Et la guerre c'est sizanic qui a commencé y a deja quelques jours 
Mais il n'a pas voulu s'arrêter quand je lui ai fait la remarque 
Bref je veux que ce poste soit supprimé comme il été 
Et qu'il ne sera pas copier coller par un autre

**Comment by TmpName** [comment]
Ben justement, on voit bien que c'est toi et editer par lui.
Y a rien de "fourbe" la dedans.

Tu veux supprimer toute l'issue ? (meme si je suis pas sur que ce soit possible)
C'est un peu con car meme si ouverte par toi, il ya  du monde qui y  partcipé depuis.

**Comment by Arias800** [comment]
On peut supprimer intégralité une issue, l'option existe puisque je l'ai déjà fait mdr

**Comment by Che-debarras** [comment]
> Ben justement, on voit bien que c'est de toi et editer par lui.
> Y a rien de "fourbe" la dedans.
> 
> Tu veux supprimer toute l'issue ? (meme si je suis pas sur que ce soit possible)
> C'est un peu con car meme si ouverte par toi, il ya du monde qui y a participé depuis.

Si c'est fourbe car j'ai supprimé le contenue du post en remplacant tout le contenu par le mot bye puis clos l issue
Mais ce bon sizanic avait fourbement predit ma réaction face a son manque de respect et il a copier coller mon suivi avant la suppression du contenu
Donc si tu edites le poste avec un autre texte , alors seule ce nouveau texte sera visible
Mais sizanic a remis le texte initial contenant les bugs pour qu'il soit a nouveau visible
Regarde le suivi des bugs 1.2.0 j'ai remplacé le 1e poste par bye donc meme fermé on ne lis que le mot bye pas de bug

Donc sizanic est  bien fourbe pour faire cela.

Mais pas principes et par respect,  j'ai le droit de supprimer un poste ou de modifier son contenu et personne n'a le droit de defaire un post d'autrui.

Donc si vous voulez  clore le problème,  il suffit d effacer mon poste #3330 et de ne pas le copier coller pour en faire un autre.
Sizanic a été tres clair, je n'ai pas a dire quoi corriger car je vous paye 

J'espère que ce post #3330 sera supprimer (et oui malheureusement toute l'issue le sera aussi)

**Comment by Che-debarras** [comment]
> On peut supprimer entièrement une issue, l'option existe puisque je l'ai déjà fait mdr

Ta de la chance car moi je l'ai fait mais sizanic la republier comme quoi

**Comment by Che-debarras** [comment]
Une fois que j'aurai acces à mon post https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3330#issue-938143596
Et que je supprime le contenu et que personne ne copie colle le post, je supprimerai tous mes autres messages concernant ce problème.

Tous cela n'aurait pas eu lieu si sizanic avez accepté la suppression de mon post.

**Comment by TmpName** [comment]
Issue supprimée.

>J'espère que ce post #3330 sera supprimer (et oui malheureusement toute l'issue le sera aussi)

Ben justement, c'etait surtout ca le probleme, tu l'avais lancé, mais d'autre avaient continué, toi tu n'en voulait plus mais @sizanic  lui voulait juste la laisser pour les autres, je ne pense pas qu'il voulait te nuire specialement, c'est plutot par rapport aux autres users.

Et il y a un historique, on voit exactement ce qui se passe sur une issue, et dans l'ordre.

**Comment by Che-debarras** [comment]
> Issue supprimée.
> 
> > J'espère que ce post #3330 sera supprimer (et oui malheureusement toute l'issue le sera aussi)
> 
> Ben justement, c'etait surtout ca le probleme, tu l'avais lancé, mais d'autre avaient continué, toi tu n'en voulait plus mais @sizanic lui voulait juste la laisser pour les autres, je ne pense pas qu'il voulait te nuire specialement, c'est plutot par rapport aux autres users.
> 
> Et il y a un historique, on voit exactement ce qui se passe sur une issue, et dans l'ordre.

Je l'avais lancé mais personne avait continué,  je le mettais a jour en fonction de ce qui a été corrigé ou non ou signalé par d'autres 
Et je le faisais pas pour moi mais pour les autres car aucun de ces bugs ne me dérange car j'utilise qu'une seul source et au pire hoster direct 

Tu peux le défendre mais vu ses propos il est claire que si moi je derange alors mon  temps perdu a faire ce suivi aussi et il n'a pas le droit de se l'approprier alors que ce n'est pas lui qui a fait ces vérifications et rédigé l issue.

Désolé mais on ne prend pas le travail d'un autre, si je décide que je le supprime on laisse supprimé.
Puisque je n'ai pas le droit de reporter des bugs alors qu'il ne garde pas mes report de bugs

Maintenant s'il veut pas nuire aux autres qu'il montre du respect envers ma personne car je sais que d'autres on besoin de ces suivi

Sizanic ne semble pas s'intéresser a mon suivi car il na jamais rien corriger de la liste même pire il gache tout avec son nouvelle adresse tirexo ou l'affichage liste.

Bref on peut dire qu'on repart a zero mais ce ne sera pas possible pour  2 raisons :
Mon suivi de bug va réapparaître par un copier coller magique de sizanic ou autre
Et je ne ferai plus de suivi car visiblement ya aucun respect de la part du grand manitou.

Dommage pour les autres

**Comment by KoRnEr007** [comment]
Très bien, ne fais plus de suivi sinon.
Comme ca, y a plus de guerre.

**Comment by alKODIque** [comment]
C'est pas la premièere fois qu'il fait le coup!! lol
Pathétique

**Comment by Che-debarras** [comment]
> Très bien, ne fais plus de suivi sinon.
> Comme ca, y a plus de guerre.

Sauf que cela pénalise les autres devs et ce qui le font le fond pas de façon pertinente pour les devs ce qui me pousse a revenir mais oui je vais arrêter définitivement.
Il faut remercier  alkodique et sizanic pour l'absence de suivi des bugs et le pire c'est qu'on essaie de clore ce problème et voilà que alkodique tente de relancer comme un troll 

Mais soit elle a ses problèmes du mois soit elle n'a pas de vie et galere devant sa poutine. Mais non j'espère qu'une personne mettra un terme au messages de cette gosse qui cherche a continuer le problème alors que le problème est clos.

**Comment by alKODIque** [comment]
ou soit ma vie n'est pas tes affaires.

**Comment by Che-debarras** [comment]
@TmpName 

> Maintenant ca repart a zero.

Si tu veux que ça part a zero faut que mette un terme a la ptite alkodique qui chercheva relancer le problème en trollant

**Comment by Che-debarras** [comment]
> ou soit ma vie n'est pas tes affaires.

Tu pourrais pas ma fermer et t'occuper de tes affaires car ce problème ne te concerne pas. Soit adulte et laisses les autres regler leur problème.
On est pas la pour t'occuper comme un feuilleton car tu te faire chier chez toi toutes seule sans amis ni boulot.

Bref le problème est terminé donc on ne pollue plus cette issue avec tes messags inutiles.

Debat clos

**Comment by alKODIque** [comment]
Le problème concerne tous ceux qui passent par ce discord puisque tu as décider d'insulter les gens ici, publiquement.  Maintenant, je t'invite a relire tout ce que tu as écris et tu constateras que le respect, c'est toi qui en manque..
Toujours toi. On se fou du problème mais non, je ne me la fermerai pas lorsqu'on tient publiquement des propos mysogine, des insultes aux autres. Ca se fait pas, point.

Et si je suis la seule a le dire que c'est pas bien et bien je serai la seule, c'est tout.
C'est pas du a mes problèmes du mois, c'est une simple question éthique et morale.

**Comment by TmpName** [comment]
> Désolé mais on ne prend pas le travail d'un autre, si je décide que je le supprime on laisse supprimé.

Entirement d'accord, mais il ne s'est rien approprié, le proprietaire (ou plutot createur) etait toujours toi, lui avait juste edité.
Il te suffiisait juste de lui dire que tu etais contre la reutilisation.

>Puisque je n'ai pas le droit de reporter des bugs alors qu'il ne garde pas mes report de bugs
>Sizanic ne semble pas s'intéresser a mon suivi car il na jamais rien corriger de la liste même pire il gache tout avec son nouvelle adresse tirexo ou l'affichage liste.

Il y fait attention vu qu'il y repond.

Et pour les autres, merci de ne pas relancer les tensions d'ici ce soir, le temps que je ferme tout, et que quelqu'un refasse une issue pour Tirexo sans le debat.

**Comment by Che-debarras** [comment]
> Entirement d'accord, mais il ne s'est rien approprié, le proprietaire (ou plutot createur) etait toujours toi, lui avait juste edité.

Vu que je n'ai plus accès , il se l'est approprié et ce n'est pas a nous de dire de pas réutiliser nos messages.
Surtout que je l'ai supprimé donc il aurait du demander la permission d'utiliser mais comme je le dit, il savait que je ne le voudrais pas alors il a copié collé le contenu avant que j'efface le contenu et que je clos le topic

> Il te suffiisait juste de lui dire que tu etais contre la reutilisation.

Non c'est a celui qui en a besoin de demander permission et je répète il claire qu'une personne qui efface un contenu qu'il ne soit pas réutiliser par un autre a son insu sans son accord, c'est du bon sens du respect de la maturité 

> Il y fait attention vu qu'il y repond.

J'ai beau le repeter mais cela ne semble pas trop entrer dans vos tetes que je ne cherche aucune attention ni reconnaissance et encore moi de sizanic qui son gros souci c'est qu'il ne sait pas repondre de manière poli respectueux et avec du recul surtout pour parler d'argent.

> Et pour les autres, merci de ne pas relancer les tensions d'ici ce soir, le temps que je ferme tout

Personnellement j'ai nettoyé mais mes msg pour dépolluer ce topic avec ce problème hors sujet et jte remercie d'avoir resolu ce problème rapidement et de manière courtois et de veiller à ce que personne notamment alkodique de relancer ce hors sujet résolu et clos

> et que quelqu'un refasse une issue pour Tirexo sans debat philosophique mais plutot des informations pour le developpment de l'application.

Sinon ceux qii qui sont intervenu sur le pb sans en etre concernés effacent les messages pour nettoyer ce topic par respect a l'auteur comme je l'ai fait.

NB: je supprimerai ce msg une fois qui sera lu

**Comment by TmpName** [comment]
Bon, comme signalé plus tot, je ferme cette issue, désolé, mais c'est plus rapide que tout nettoyer, Il vous faudra en re-ouvrir une pour le soucis Tirexo.

La je pars prendre l'apero, donc je repasse plus ici, bonne soirée tout le monde.
