### ISSUE TITLE
Résolution ''Indéterminée'' - Source Pastebin

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3336]
Bonjour :)

Dans la source Pastebin, 
Lorsque nous ouvrons le dossier ''Indéterminé'' dans la catégorie ''Films (Par résolutions)'', il est impossible de visionner un film qui s'y trouve.

Nous obtenons invariablement le message ''Aucune information'' et ce, peu importe le contributeur:

![Screenshot_20210720-102514](https://user-images.githubusercontent.com/49578130/126341349-e1758a76-05e6-43ae-b63d-3459e7aae6fe.png)
![Screenshot_20210720-102506](https://user-images.githubusercontent.com/49578130/126341355-153ad037-5254-40c5-8da3-e7eb6e107b08.png)

**Comment by sizanic** [comment]
Vu 👍

**Comment by Che-debarras** [comment]
Y a t'il moyen d'installer toutes les sources pastebin sans modifier nos réglages et nos favoris de kodi?

**Comment by sizanic** [comment]
> Y a t'il moyen d'installer toutes les sources pastebin sans modifier nos réglages et nos favoris de kodi?

oui, mais ce n'est pas le propos ici 🤔

**Comment by sizanic** [comment]
Corrigé
