### ISSUE TITLE
extension upnext

### ISSUE THREAD

**Issue by donguiza** [Kodi-vStream/venom-xbmc-addons#3338]
salut , j ai un petit souci avec l extension upnext c est  qu elle ne s active qu une seule fois chaque fois que je lance une épisode  , l enchainement des épisodes ne se poursuit pas est je suis obliger de lancer l épisode suivante manuellement et ainsi de suite
aussi j ai remarque que les épisodes activer avec upnext ne sont pas marquées comme vue
( testé avec Frenchstream et 01 streaming)

 - OS: [Android]
 - Version Kodi  [19.1]
- Version Vstream 1.3.1

**Comment by sizanic** [comment]
Salut,

Une correction pour l'enchainement des épisodes à été mise en place.
Elle sera disponible dans la prochaine version (prévue cette semaine).

Concernant l'information "VU", ce souci est connu et fera l'objet d'une prochaine correction.
