### ISSUE TITLE
Enchainement auto sur > 2 épisodes

### ISSUE THREAD

**Issue by gavaslow** [Kodi-vStream/venom-xbmc-addons#3340]
Salut et merci pour le boulot sur l'extension !

PR en lien : [3339](https://github.com/Kodi-vStream/venom-xbmc-addons/pull/3339)

Probleme avec NextUp je ne pouvais pas enchainer automatiquement plus de 2 épisodes, **SANS** cliquer sur _regarder maintenant_ sur la notif NextUp (Donc en laissant s'écouler le timer NextUp jusqu'au bout).
J'ai fait une PR avec un fix qui marche chez moi Android Box + PC Linux. Il y a peut-etre une meilleure solution (voir la le code dans la PR).

**Votre system**
 - OS: Ubuntu et Android
-  Appareil PC et Mi Box 3
 - Version Kodi  19.1
- Version Vstream 1.3.1

**Nous devons le reproduire**
Pour cela il nous faut:
- Tous
- Tous
- Tous

**Log**
https://paste.kodi.tv/faqiduwoje
Vers la fin

**Comment by sizanic** [comment]
Salut,
Je vais regarder ta PR de plus prêt pour analyser les impacts.
Je ne pensais pas que ce serait aussi simple.

**Comment by gavaslow** [comment]
Merci beaucoup 👍

J'ai fait ça rapidement pour que ça marche mais le truc c'est que je trouve pas la source du _endPlayback_ qui est envoyé au **player**.

Par contre il n'y a pas le bug si on clique sur regarder maintenant et qu'on laisse pas se finir le compteur de la notif **NextUp**.

J'ai l'impression que le deuxième **player** se lance avant que le premier se termine et du coup il reçoit le signal _endPlayback_ quand le premier se termine naturellement à la fin de l'épisode.

**Comment by sizanic** [comment]
Vu ta modif, le problème doit être quelque comme ça.
J'essaie de voir ce soir.

**Comment by eldon33** [comment]
merci pour ton effort , ca fait un moment que je cherche une solution pour ce problème j ai essayé ta solution et ca l air de bien fonctionner .seulement y a t il un moyen de marquer les épisodes lancer automatiquement avec upnext  comme vue

**Comment by gavaslow** [comment]
Pour les épisodes vus déclenchés par **nextup**, normalement ils devraient être marqués vus comme avec un lancement normal ? J'avoue que j'ai pas trop regardé ça, mais à voir

**Comment by eldon33** [comment]
> Pour les épisodes vus déclenchés par **nextup**, normalement ils devraient être marqués vus comme avec un lancement normal ? J'avoue que j'ai pas trop regardé ça, mais à voir

oui pour ma part  les épisodes  déclenchés par nextup ne sont pas marqués vus contrairement a ceux lancer manuellement

**Comment by sizanic** [comment]
Enchainement de plus de deux épisodes -> Corrigé en V1.4.0
