### ISSUE TITLE
Historique de recherche ne fonctionnne plus

### ISSUE THREAD

**Issue by eco-plus** [Kodi-vStream/venom-xbmc-addons#3348]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.
Bonjour, apres la maj 1.4 l'historique ne recherche retourne une erreur, impossible d'y accéder.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by sizanic** [comment]
Je viens de regarder et : 
- je retrouve bien mon historique de recherche
- la recherche est bien de nouveau lancer si je sélectionne un élément


As-tu un log à nous transmettre ?

Tu peux également supprimer cet historique (si tu es prêt à la perdre) pour essayer de réparer la fonctionnalité.

**Comment by eco-plus** [comment]
je précise , je suis encore sous kodi 16.1 sur une installe qui date de 4- 5 ans au moins .
en downgradant sur la 1.3.1 ça résout le problème, surement une erreur de conversion en int. (python 2 python 3)
et j'ai aussi une erreur dns python absent lors des recherches.

https://pastebin.com/FxWe9WZu

**Comment by sizanic** [comment]
J'ai une piste, je vais regarder.

**Comment by TmpName** [comment]
L'erreur de dns python n 'est pas grave, c'est juste que tu n'auras pas acces a certains site protegés. C'est juste une option a installer ou pas, selon les choix.

**Comment by sizanic** [comment]
> L'erreur de dns python n 'est pas grave, c'est juste que tu n'auras pas acces a certains site protegés. C'est juste une option a installer ou pas, selon les choix.

Quelle erreur de DNS Python ?? 🤣

**Comment by sizanic** [comment]
Pour l'historique de recherche, je ne vois pas le probleme de compatibilité ascendante.
J'ai ajouté un peu de code pour la robustesse, à voir si ça corrige.

**Comment by Arias800** [comment]
Pour l'erreur de DNS Python voir ici :
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3349
