### ISSUE TITLE
[Résolu] Addon.dnspython manquant

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3349]
Bonsoir,

Je viens de mettre à jour Vstream en 1.4.0 sur ma box Android, j'avais pris l'habitude d'utiliser la source Wifli.x que je trouve très efficace et bien fournie. Avec cette nouvelle mouture si j'utilise le chemin Films / Derniers ajouts / Wiflix j'ai une erreur "Addon.dnspython manquant" et cette erreur se produit sur plusieurs sources comme ZuStream, ZT, VoirFilms et bien d'autres.
Je ne trouve pas comment régler ce problème, si quelqu'un a une idée je suis preneur.

NB: je suis sous Kodi 19.1

**Comment by Arias800** [comment]
Bonjour,
L'addon DNS Python sert à contourner le blocage appliquer par les opérateurs.
Pour ne plus que l'erreur apparaisse il suffit d'installer ce script (il n'existe pas de version officielle pour Kodi 19, donc je n'ai fait une).
https://github.com/Arias800/script.module.dnspython/releases/

**Comment by Niconimes** [comment]
> Bonjour,
> L'addon DNS Python sert à contourner le blocage appliquer par les opérateurs.
> Pour ne plus que l'erreur apparaisse il suffit d'installer ce script (il n'existe pas de version officielle pour Kodi 19, donc je n'ai fait une).
> https://github.com/Arias800/script.module.dnspython/releases/

Salut Arias, 
Merci je vais tester ça.

**Comment by sizanic** [comment]
@Arias800  
> il n'existe pas de version officielle pour Kodi 19, donc je n'ai fait une.

pourquoi ne pas rendre cette dépendance disponible sur le depot vStream ?

**Comment by Arias800** [comment]
Parce que je voulais bien tester le code avant de le mettre a disposition (c'est pour ça que je viens de créer la release).

**Comment by Arias800** [comment]
@Niconimes Bizarre, pourtant le fichier est valide (je viens de réessayer).
Il faudrait que tu me donnes les logs pour que je puisse voir l'erreur.

**Comment by Niconimes** [comment]
> @Niconimes Bizarre, pourtant le fichier est valide (je viens de réessayer).
> Il faudrait que tu me donnes les logs pour que je puisse voir l'erreur.

Ok j'essaie de te faire ça

**Comment by Niconimes** [comment]
C'est bien upload log pour le sortir ? Parce que quand je tape l'adresse que Vstream me donne je tombe sur un truc qui n'a rien à voir

**Comment by Arias800** [comment]
On peut plus passer par cette option, le site que l'on utilisait est fermé.
Il faut récupérer le fichier à la main maintenant ou utilisé l'addon officiel de Kodi https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by Niconimes** [comment]
> On peut plus passer par cette option, le site que l'on utilisait est fermé.
> Il faut récupérer le fichier à la main maintenant ou utilisé l'addon officiel de Kodi https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

https://paste.kodi.tv/overawogel

**Comment by Arias800** [comment]
Je viens de tester sur ma box android et tout c'est installer sans problème.
Donc je ne sais pas d'où ça peux venir.

**Comment by Niconimes** [comment]
> Je viens de tester sur ma box android et tout c'est installer sans problème.
> Donc je ne sais pas d'où ça peux venir.

Ok tant pis, je suis de mariage cet après midi donc pas le temps de tester plus mais je tenterai une installation à neuf demain

**Comment by Niconimes** [comment]
Salut à tous, j'ai résolu mon problème en installant la bêta, tout fonctionne à nouveau, merci encore pour votre travail.

**Comment by donguiza** [comment]
par contre moi j ai pas l erreur Addon.dnspython manquant mais plutot page proteger par cloudflare veuiller execulter flaresolverr y a t il une solution pour ce message et merci

**Comment by donguiza** [comment]
> Ben tu peux installer Flaresolver pour tester ?
> Sans ca tu ne pourras pas avoir la page, donc c'est pas le message d'erreur qui va te bloquer.

je pense que flaresolver n est pas compatible avec kodi19.1

**Comment by doudoulabrel** [comment]
Salut 
C'est quoi la version bêta ? Si cela a fonctionné pour niconimes ...
Et sinon, comment est-ce possible sur une box android de récupérer les fichiers que arias800 a mis à dispo ?

**Comment by sizanic** [comment]
Une version Beta est la version du code en développement pour la prochaine mise à jour.

Ce code est instable car il bouge tous les jours.
Il ne doit pas être utilisé lors d'une utilisation normale, seulement pour des tests ponctuels.

Des fichiers mis à disposition par les développeurs comme Arias800 est encore plus à proscrire, ce n'est même pas en Beta.

**Comment by doudoulabrel** [comment]
Ok. Merci sizanic.
Il reste quoi comme solution pour résoudre le problème de trucs manquants ?
(Je précise, je comprends rien aux trucs informatiques !...)

**Comment by sizanic** [comment]
> Il reste quoi comme solution pour résoudre le problème de trucs manquants ?

Attendre la prochaine mise à jour.
D'après les discussions et l'avancement de la version Beta, la correction sera disponible dans la prochaine mise à jour.

**Comment by doudoulabrel** [comment]
Et elle sera quand cette mise à jour ? Vivement en tout cas ! Heureusement qu'on n'est plus en confinement ^^
Bon ben go pour s'ennuyer devant les mauvais replays de la télé. 
Merci pour les infos 😉

**Comment by sizanic** [comment]
Si tu penses que le changement automatique de DNS par vStream est la solution de ton problème, en attendant tu peux les changer manuellement, en suivant par exemple ce tuto : 
https://www.prodigemobile.com/tutoriel/modifier-dns-mobile-android/

**Comment by fred-dzign** [comment]
Bonjour à tous,

je rencontre quelques soucis avec Vstream 1.4.0 installé sur mon Kodi 19.1 sur une Xiaomi Mi box S Android.
Après l'installation du repository 0.0.4, et ensuite l'installation de Vstream 1.4.0, il y a des erreurs liées à des dépendances (non disponible), plus précisément script.module.urlresolver, script.module.dnspython et script.module.selenium. 
Auriez vous rencontré ce même problème ? comment puis-je résoudre ce problème afin de profiter de mon Vstream ?
Petite précision : J'ai exactement la même installation sur une seconde box Android TV, située dans une autre pièce de la maison et profitant de la même connexion internet, mais avec elle aucun soucis, je peux lancer des films depuis Vstream sans erreur ! Une idée ?

**Comment by Pepito974** [comment]
Merci sizanic tellement évident !!! mais j'y ai pas pensé merci encore tout fonctionne à nouveau en attendant vivement une mise à jour

**Comment by Alvesinho** [comment]
Bonjour,

J'ai suivi le tutoriel pour installer le script de @Arias800
Mais lorsque je lance le script j'ai cette erreur :(

"the dependency on xbmc.python version 3.0.0 could not be satisfied"

Si quelqu'un peut m'aider ?
Merci 

Voici la version que j'utilise:
Builde: Kodi 18.9 (18.9.0)
Git:newclock5-18.9-Leia

**Comment by yamoky** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/files/6872094/script.module.dnspython.zip

Installation ça si tu ne la pas fait encore regarde si y a pas de mise à jour plus récente

**Comment by Makavel73** [comment]
Pour kodi 18.9  il faut regarder dans les dépendances de vstream et installer dns python, le script de arias c'est pour kodi 19.

**Comment by Alvesinho** [comment]
> https://github.com/Kodi-vStream/venom-xbmc-addons/files/6872094/script.module.dnspython.zip
> 
> Installe ça si tu ne la pas fait encore regarde si y a pas de mise à jour plus récente

Toujours la même erreur :(

**Comment by Alvesinho** [comment]
> Pour kodi 18.9 il faut regarder dans les dépendances de vstream et installer dns python, le script de arias c'est pour kodi 19.

Je connais pas beaucoup vStream et Kodi.
Où se trouve les dépendances ? Quand j'ai ouvert le add-ons de vStream, j'ai 3 fichiers en .zip:
-plugin.video.f4mTester-2.7.2.zip
-repository.vstream-0.0.3.zip
-script.video.F4mProxy-2.8.8.zip

**Comment by sizanic** [comment]
![image](https://user-images.githubusercontent.com/47307622/132597063-c72edb3c-1ae8-4a10-9ddb-05f40f3bf693.png)


![image](https://user-images.githubusercontent.com/47307622/132597102-45a07643-ff08-43ad-b280-b24cf3d32e33.png)


![image](https://user-images.githubusercontent.com/47307622/132597134-4961ff2b-6804-444c-9216-2dc952cabc5f.png)

![image](https://user-images.githubusercontent.com/47307622/132597172-cee25c9c-bb60-43fc-b87f-13aa7f32b1a1.png)

**Comment by Pepito974** [comment]
Bonjour la communauté une petite information svp 
J'ai résolu mon problème de dns python manquant par contre quand je vais dans la version 1.4.0 de vstream j'ai script.module.urlresolver non disponible et script.module.selenium non disponible 
Un petit Zip disponible pour corriger ce soucis svp?

**Comment by alKODIque** [comment]
Bonjour @Pepito974 
C'est étrange que tu reçois ce message d'erreur... As-tu essayé de les télécharger via la fenêtre des dépendances? Si oui, tu n'avais pas besoin de le faire...
- Selenium n'est plus utilisé par vStream;
- UrlResolver, si tu en as besoin (car tu utilises un compte premium à un service de débrideur), se trouve ici: https://fusion.tvaddons.co/kodi-scripts/

Bon week-end :)

**Comment by Pepito974** [comment]
Bonjour alKODIque merci pour les informations peux tu juste m'expliquer brièvement où trouver ces fenêtres de dépendance svp?

**Comment by sizanic** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3349#issuecomment-915631560

**Comment by Mokoman30** [comment]
Vivement la Maj tellement hâte car c est embêtant le DNSPython manquant j’en ai marre de le voir

**Comment by sizanic** [comment]
Il suffit de désactiver la source qui pose problème 🤔 
ça prend 2 secondes dans les paramètres de vStream.

**Comment by razorex** [comment]
@Mokoman30 installe la version de @Arias800 [https://github.com/Arias800/script.module.dnspython/releases/](url) elle fonctionne. Tu la télécharge et tu fais installer depuis un fichier zip

**Comment by Mokoman30** [comment]
Merci beaucoup l équipe ❤️ finalement pas besoin de télécharger 
Sa me l’a proposer dans dépendance 

Merci énormément 

Seul soucis maintenant c est dood qui fonctionne pas sous Kodi 18.9 sinon tout est parfait merci 🙏🏼

**Comment by Mokoman30** [comment]
Par contre faut cliquer ou pour télécharger le dns Python j ai 3 assets j ai télécharger le 1er sur la clé usb pour l installer en zip je trouve pas le fichier j essaye de l installer sur kodi 19.1

**Comment by alKODIque** [comment]
> Par contre faut cliquer ou pour télécharger le dns Python j ai 3 assets j ai télécharger le 1er sur la clé usb pour l installer en zip je trouve pas le fichier j essaye de l installer sur kodi 19.1

C'est ici:
https://lesalkodiques.com/wp-content/uploads/2021/09/DNS-Python.jpg

**Comment by Mokoman30** [comment]
Justement moi j ai télécharger et tout mais quand je clique sur le dossier je trouve pas le fichier précis

**Comment by alKODIque** [comment]
Bin, c'est qu'une fois le fichier téléchargé, tu dois ensuite passer par kodi pour aller l'installer.. Tu vas dans Extension, installer depuis un fichier zip. Et tu choisis ce zip à l'endroit ou tu l'a téléchargé. Si ca ne fonctionne pas, c'est que le téléchargement c'est mal passé pour toi alors essaie de le télécharger à nouveau

**Comment by Mokoman30** [comment]
Merci bcp sa marche alKodlque

**Comment by bmw635CSI** [comment]
Bonsoir à tout le monde je ne sais pas si mon message est bien placé mais j'ai vu un peu plus haut que vous avez pu résoudre le problème pour pouvoir regarder les films avec Kodi mais je vois que vous avez téléchargé installer un lien et je ne sais pas comment faire est-ce que quelqu'un peut me répondre et m'aider comment le faire merci

**Comment by sizanic** [comment]
Et ce serait mieux de décrire le probleme dans un nouveau sujet.
Celui-ci est fermé.

**Comment by bmw635CSI** [comment]
Désolé mais je ne sais pas comme ça marche je viens tout juste de
m'inscrire sur le site car j'ai ce problème il y a plusieurs mois et là
comme je m'ennuyais j'ai voulu regarder un peu sur le net et j'ai vu que
quelques personnes ont résolu ce problème et je ne sais pas comment faire
si tu pourrais m'aider ça serait très sympa de ta part merci

**Comment by detobel36** [comment]
@bmw635CSI Je vous invite du coup à créer une nouvelle "issue": https://github.com/Kodi-vStream/venom-xbmc-addons/issues/new/choose
En mettant du coup l'erreur qui se trouve dans le journal.
Consulter cette page: https://kodi.wiki/view/Log_file#Log_file_location pour savoir où se trouve le fichier de log (le fichier journal).
