### ISSUE TITLE
problème slexy

### ISSUE THREAD

**Issue by fpodev** [Kodi-vStream/venom-xbmc-addons#3351]
Bonjour,
Il y as un problème avec slexy. Quand j'envoie mon log ça ne me donne pas d'adresse avec un id. 

Merci

**Comment by Niconimes** [comment]
> Bonjour,
> Il y as un problème avec slexy. Quand j'envoie mon log ça ne me donne pas d'adresse avec un id.
> 
> Merci

Salut, Slexy ne fonctionne plus, il faut utiliser ça maintenant : https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by fpodev** [comment]
Bonjour,

Merci pour l'info.
