### ISSUE TITLE
Plus aucun lien ne se lance

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3352]
Bonsoir à tous,

Désolé mais je reviens avec un nouveau souci, depuis mon bug dû au Dnspython manquant que j'avais résolu en installant la bêta tout marchait niquel jusqu'à cet après midi. Je n'ai rien touché à Vstream ou Kodi ni même à ma box mais subitement je ne peux plus lancer aucun lien et ce sur tout les sites dispos. En gros je vois les liens, ils sont débridés par Urlresolver vu la couleur du lien, je clique dessus, la roue bleue se lance, le nom débridé apparaît en haut à droite comme s'il allait se lancer, la roue s'arrête et je reviens sur l'écran bleu et la roue se remet à tourner non stop.
J'ai tout relancé, idem, vidé le cache de Kodi et Vstream redémarré le tout idem. J'ai donc désinstallé Vstream pour refaire l'install de 0 et idem. J'ai même fini par désinstaller Kodi et tout refaire à 0 et au final, idem, cette roue bleu qui tourne non stop... Je suis dépité et je n'ai plus du tout d'idée de quoi faire.
Je suis sur Kodi Matrix et Box Android Xiaomi.

Merci d'avance si vous avez une idée

Nico

NB: pour couronner le tout j'ai réinstallé Logfile Uploader et il refuse de poster le log (This fil is to large)

**Comment by sizanic** [comment]
Bonjour,

Pourquoi utiliser urlResolver ?
Quel débrideur utilises-tu ?

**Comment by Niconimes** [comment]
> Bonjour,
> 
> Pourquoi utiliser urlResolver ?
> Quel débrideur utilises-tu ?

Salut,

J'utilise Real-Debrid mais je ne pense pas que le souci vienne de là car même si je désactive Urlresolver le résultat est le même

**Comment by Niconimes** [comment]
Le problème s'est visiblement résolu de lui même je vais 🤞 pour la suite, merci encore pour cet addon
