### ISSUE TITLE
Un grand remerciement à tous les développeurs 

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3357]
Merci pour tout ce temps que vous nous offrez généreusement afin que chacun de nous puissions profiter grâce à vous, de la magie de vStream 

Chapeau les gars
Kris

(activez le son) ....
https://user-images.githubusercontent.com/31409100/131419116-672b930d-98ff-4424-a941-63204cbfdc9c.mp4

**Comment by sizanic** [comment]
@kris06 
Pourquoi fermer cette issue ?
Ca me donne l'impression que tu m'as repris un cadeau que tu venais de me faire.

**Comment by kris06** [comment]
erreur de manipulation.
Bien à toi


----- Mail original -----
De: "sizanic" ***@***.***>
À: "Kodi-vStream/venom-xbmc-addons" ***@***.***>
Cc: "kris06" ***@***.***>, "Mention" ***@***.***>
Envoyé: Mardi 31 Août 2021 01:50:36
Objet: Re: [Kodi-vStream/venom-xbmc-addons] Un grand remerciement à tous les développeurs  (#3357)





@kris06 
Pourquoi fermer cette issue ? 
Ca me donne l'impression que tu m'as repris un cadeau que tu venais de me faire. 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .
