### ISSUE TITLE
Mise à jour intermédiaire

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3360]
Beaucoup d’entre nous utilise vStream à partir des sources enregistrées dans les favoris, cependant ce chemin ne permet pas à vStream de faire sa mise à jour... 

En effet, j'ai remarqué, qu’il faut ouvrir VStream de façon traditionnelle pour la recevoir.   Certains de mes amis restent sans le savoir, sur des anciennes versions (intermédiaires) en raison de ce problème y compris parfois moi même

N’est-il pas possible d’ajouter une procédure de lancement de cette maj à l’ouverture de chaque source ?  Comme le fait VStream à son ouverture ?

je vous remercie

 - OS: [Windows 10
-  Appareil [Freebox pop - freebox mini4k - box Bouygues -  google tv - )
 - Version Kodi  19.1
-   Version 1.4.0

*

**Comment by sizanic** [comment]
Bonjour,
Cela fait un an que nous ne proposons plus de mise à jour intermédiaire. Nous ne proposerons plus que des mise à jour complète.
Elles s'installent automatiquement si l'option"mise à jour automatique" est bien activée sur l'extension.
Même sans ouvrir vStream, c'est géré par Kodi.

**Comment by kris06** [comment]
merci pour ta réponse, je ne comprends pas alors pourquoi certains  de mes amis (box Bouygues et Chromecast Google TV) ne reçoivent pas les mises à jours alors que l'option maj est activée !

**Comment by sizanic** [comment]
Alors là moi non plus 🤔
Ils étaient restés en 1.3.1 ?

Ou bloqué dans une version précédente ?
Sont ils passé dernièrement sous Kodi 19 et c'est depuis que la version n'a pas évoluée ?

**Comment by kris06** [comment]
oui ils étaient resté en  1.3.1 sur kodi 19.1   Il a fallu exécuter la mise à jour manuellement dans les paramètres.

Ce qui est curieux, c'est que ca c'est produit seulement  sur ces 2 appareils (box Bouygues et Chromecast Google TV)  j'ai pourtant vérifié avec eux,  tous les paramètres,  mais je n'ai rien trouvé d'anormal. 

C'est comme cela que j'ai pu constaté qu'en ouvrant  Vstream de manière normal (et non via  les favoris) ,  que vstream a pu installer la mise à jour.   (d'où mon premier message que je t'ai adressé)

**Comment by TmpName** [comment]
Oui et c'est pas un probleme de repo vu que tu as pu faire en manuel ...
