### ISSUE TITLE
Erreur d'authentification

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3364]
Bonjour :)

(J'ai la dernière bêta vStream installée, j'ai les DNS cloudflare, je suis au canada))

Depuis quelques jours, je vois que je suis dans l'incapacité d'utiliser mon compte premium uptobox pour visionner du contenu autre que celui de la source Pastebin.

Si je choisi un lien uptobox ou même uptostream à l'intérieur d'une autre source, j'ai un message d'erreur ''Authentification ratée''. Et de plus, je reçois un mail de la part de uptobox me mentionnant une tentative de connexion suspecte.

Voici la partie de mon log qui indique l'authentification ratée:
[log-part 1.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7118181/log-part.1.txt)

Voici un exemple du mail que je reçois ensuite:
(Je précise à nouveau que pour les liens uptobox à l'intérieur de pastebin, tout fonctionne normalement.)

Ce qui est étrange. c'est que le mail indique une tentative de connexion depuis un pays différent que le mien. Et ensuite, si je clique sur le lien qu'on me donne pour autoriser la connection, je me doit de refaire l'exercice si je me connecte à mon compte uptobox depuis mes autres appareils ... puisque ce sont alors ces derniers qui ne sont plus autorisés depuis que j'ai tenté l'autorisation a ma shield pour kodi (vStream)

![uptobox](https://user-images.githubusercontent.com/49578130/132268723-a82c7a2d-144c-4a5a-ac7b-430875e51db4.PNG)

**Comment by alKODIque** [comment]
Je viens d'activer et de passer par urlresolver (j'ai aussi un compte alldebrid) et les liens essayés plus tôt se lancent maintenant normalement

**Comment by TmpName** [comment]
Tu utilises un VPN ?
C'est la meme IP dans les deux cas ?

**Comment by alKODIque** [comment]
Oui, toujour la même ip. Je n'ai pas de VPN.
Le seul truc que je modifie, ce sont mes DNS pour ceux de cloudflare. Et je n'avais jamais eu ce problème avant.. 

C'est vraiment étrange ! J'utilise pourtant mon abonnement pour visionner les liens Pastebin et ça fonctionne.  Mais lorsque je je souhaite entrer dans mon compte, j'ai ''authentification ratée'' 🤷‍♀️

**Comment by alKODIque** [comment]
C'est un problème résolu pour moi depuis:
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/afad25de5b5b26e5825f58378b4a4ee14e99a395

Grand Merci :)
