### ISSUE TITLE
Problèmes avec certaines sources 

### ISSUE THREAD

**Issue by tombikz** [Kodi-vStream/venom-xbmc-addons#3366]
Salut, certains liens ne marchent pas à cause de cloudflare, et flaresolvrr ne marchent plus c'est dommage car du coup enstream série ou d'autre sources ne fonctionnent plus serait ce possible de régler ce problème ? 

J'utilise vstream matrix sur Android

Merci d'avance ;-)

**Comment by yodidon** [comment]
oui ce site es sous cloudfare et pour le moment pas de solution sur vstream malheureusement
