### ISSUE TITLE
Recherche similaire

### ISSUE THREAD

**Issue by fredo04** [Kodi-vStream/venom-xbmc-addons#3367]
**Décrivez le bug**
Bonjour a tous.
Je viens de m'apercevoir que la recherche similaire n'est plus disponible (je sais pas depuis quand).
Je trouve ça très pratique.

**Votre system**
 - OS:[Android 6]
-  Appareil [ beelink gt1]
 - Version Kodi  [19]
- Version Vstream, la dernière

**Comment by razorex** [comment]
Bonjour,
non elle est toujours présente. Elle a juste été renommée en "Rechercher".

**Comment by fredo04** [comment]
A oui en effet, dsl de pas avoir plus cherché.
