### ISSUE TITLE
Ajout source service( enfants et famille) "Benshi" 

### ISSUE THREAD

**Issue by xis-38** [Kodi-vStream/venom-xbmc-addons#3370]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Une description claire et concise de ce qu'est le problème. Ex. Je suis toujours frustré quand [...]

**Décrivez la solution que vous souhaitez**
Une description claire et concise de ce à quoi vous voulez arriver.

**Comment by xis-38** [comment]
Bonjour, un peu frustre qu'il ne soit porté toutes les applis Google store sur le Microsoft store . J'utilise le service Benshi pour les animations,Films et dessins animés pour mes enfants qui propose tout une sélection de media selon chaque âge des enfants . Mais voilà l'appli n existant pas sur Microsoft, je me demandais si il vous étiez possible de la passer sur vstream (le service nécessite un abonnement payant) . Pensez vous que ça soit réalisable ?? 

Merci pour votre retour 
Bonne journée à toutes et tous 
Grand merci pour votre taf c'est génial ^^

**Comment by TmpName** [comment]
He non, dsl, c'est une application complete, Vstream ne fait que "lire" des pages WEB a la recherche de liens video sur des hebergeurs classiques.

**Comment by sizanic** [comment]
@TmpName 
Les vidéos semblent disponibles également depuis leur site web.

@xis-38 Depuis quel équipement utilise-tu Kodi et vStream ?


Je pense que ce site nécessiterait une extension à part entière (comme il existe des extensions pour Netflix ou pour d'autres plateformes), et pas une source dans vStream.

Pour que nous décidions de lancer des développements pour cette source il faudrait connaître le niveau de demandes.

**Comment by xis-38** [comment]
Merci a vous pour ces réponses . Bon ben c'est bien dommage mais je comprend tout à fais . J'ai faire comme tout le monde et passer sur une box Android ;) . Perso je suis sur un PC Nuc Intel . Je doute qu'il soit possible et sans bug d'installer Android TV os sur ma monture dans qu'il n'y ai de disfonctionnement par rapport à une box . 
J'attendrais !... Merci a vous pour tout
