### ISSUE TITLE
Compte uptobox premium 

### ISSUE THREAD

**Issue by isandard** [Kodi-vStream/venom-xbmc-addons#3377]
Bonjour,
Depuis à peu près une semaine, il est impossible de parcourir un compte uptobox premium en faisant le menu mes fichiers et dossiers, alors que ça marchait parfaitement la veille et sans changer de version.
Le soucis a été détecté sur la 1.40 et reste identique sur la 1.50, ils ont du changer un peu leur API

Sur Xiaomi mi box 4 (android TV)

**Comment by manclev** [comment]
Bonjour
En effet cela fait maintenant 2 MOIS qu'il n'est plus possible sur un appareil Android (perso mini 4k), d'accéder à MES FICHIERS ET DOSSIERS sur mon compte UPTOBOX PREMIUM.
Ce problème s'était déjà produit il y a au moins un an (voire un peu plus) et il avait été résolu assez rapidement !!
J'ai lu la réponse ici qui dit que ce n'est pas grave de ne plus accéder à MES FICHIERS ET DOSSIERS puisque la fonction recherche existe et fonctionne.
Sauf que cela n'a rien de pratique !!! Perso j'ai de très nombreux fichiers et me les rappeler pour ensuite les visualiser n'est pas du tout pratique, d'autant que souvent c'est en les listant que l'envie me prend de regarder tel ou tel fichier.
Et enfin à quoi sert d'avoir une fonction MES FICHIERS ET DOSSIERS si elle ne fonctionne pas.
Le problème avait été résolu il y a un an alors pourquoi cette fois ci il ne l'est pas ??
Y a t il une âme charitable que qui pourrait ce problème svp ????
Par avance MERCI

**Comment by alKODIque** [comment]
si ton contenu uptobox n'est plus accessible via vStream, il y a probablement un luen qui cause problème à la racine de ton compte..
peut-être cette solution pourra t'aider, elle a resolu le problème pour tous les utilisateurs qui ont essayé:
https://lesalkodiques.com/docs/wiki-vstream/depannage-vstream/uptobox-ne-souvre-plus/

**Comment by manclev** [comment]
Merci mais je ne suis pas le seul à qui se problème arrive sur vstream et comme je le disais auparavant cela fonctionnait très bien avant  sauf il y a un an. Il y a eu une mise à jour et tout était revenu à la normal. Donc ça n'a rien à voir avec mes fichiers !!

**Comment by alKODIque** [comment]
Bin mon compte uptobox est accessible a vstream.

si j'ajoute un lien non reconnu par vStream à la racine, il ne l'est plus.

La façon dont l'API uptobox est appelé par vstream a été modifié depuis quelques temps et ce problème arrivé en même temps.
Alors oui, ceci a a voir avec un fichier non reconnu..

**Comment by manclev** [comment]
Alors dans ce cas nous sommes nombreux à avoir le problème dont tu parles !!!! Ne parle pas si tu ne sais pas s'il te plait l'ami. Je t'ai expliqué que ce probleme avait existé pour de très nombreuses personnes il y a au moins un an. Il y a eu une mise à jour sur kodi/vstream Android et le probleme a ete réglé !!!
Enfin c'est un problème sur Android puisque je n'ai pas ce probleme avec kodi/vstream sur mon pc windows !!!!
Donc ce que tu dis n'a pas de sens . merci quand meme d'avoir donné ton avis !!!

**Comment by alKODIque** [comment]
lol ok ;)

**Comment by TmpName** [comment]
C'est assez compliqué aussi d'avoir un debut de piste, donc on propose de tout. Tu pourrais fournir un log STP.
Car certains n'ont pas le probleme, ou n'ont meme pas de compte premium.

**Comment by alKODIque** [comment]
@TmpName 
Normal que tu ne te souvienne plus.. Il y a vraiment longtemps que le problème des liens non reconnus (vidéo) par vStream a é.té identifié et confirmé...

A moin qu'il y ait maintenant un nouveau problème, le problème d'accès a notre compte uptobox ne se résoud que de cette façon. Et puisque chaque personne ajoute ses propres liens, il faut donc identifier ces liens individuellement

**Comment by MalibuKoKo** [comment]
Hello,

Je fais le même constat ... des erreurs : **ERROR : ValueError: invalid literal for int() with base 10: 'x.y'**

L'erreur se présente visiblement dès qu'un fichier comporte dans son nom un chaîne comme celle-ci : **S01E01.1080p**

@TmpName @sizanic : j'ai regardé un peu le code et de ce que je constate il y a un problème dans la regex : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/75e96c6605168993b756ce218d05b13a92c20292/plugin.video.vstream/resources/lib/gui/guiElement.py#L219

la regex match des portitions de chaînes qui ne devrait pas l'être ... on peut la tester là : https://regex101.com/r/B8EVvT/1/

Vous cherchez à faire quoi dans cette fonction **TraiteTitre** ? Je vois pleins de regex, de remplacement de chaînes etc
Par ailleurs vous avez du test sur cette portion de code (pour éviter les régressions) ?

**Comment by MalibuKoKo** [comment]
@TmpName @sizanic 

Je vous propose une alternative, cf. https://regex101.com/r/P8lBIl/1

**Comment by sizanic** [comment]
Salut.

Ce type de nommage qui fait péter la regex, on l'avait bien repéré depuis octobre :
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3377#issuecomment-946391152

Mais on l'a un peu oublié 😅

Merci pour ta proposition, on voit pour la récupérer 👍🏻

**Comment by TmpName** [comment]
>Par ailleurs vous avez du test sur cette portion de code (pour éviter les régressions) ?

Lol, ben tiens, now que j'y pense, ben j y pense jamais a ca ^^, tres bonne idée, juste a mettre en commentaire dans le code au dessus de la fonction.
Surtout que ca doit etre un des plus vieux regex du code.

Inspiré du tien je proposerais
`(?i)(?:^|[^a-z])((?:E|x|(?:\wpisode\s?))(\d{1,2}[-\.]\d{1,2}(?!\d+)|\d{1,2}))`
Qui fait exactement la meme chose.

Franchement n'hesites pas a proposer tes modif au code, c'est plus facile pour nous d'oublier un commentaire ou un truc qu'on s'est dit "on verra plus tard", qu'un code deja proposé en Pull request.

**Comment by MalibuKoKo** [comment]
Effectivement, je pouvais rejoindre le tiret et le point ensemble: [-\.]

A 3H du mat, j'avais pas les yeux en face des trous ;)

De mon côté j'ai testé la regex que j'avais proposé et cela fonctionne bien.
Pas de soucis pour pousser les modifs, ce n'est pas la première fois que je participe à ce projet, vous faites du très bon boulot.

J'ai fais le même constat quand j'ai parcouru cette partie du code. Cette partie mériterai sans doute d'être refactoré mais avant cela plusieurs remarques :
- quel est le but de la fonction TraiteTitre ?
- est-il pertinent de supprimer étape après étape des morceaux de chaîne plutôt que d'extraire les infos (titre, année, saison, épisode etc) et générer / remettre en ordre les infos suivant une règle attendue ?
- cette partie est critique et peut avoir des effets de bord
- implémenter une classe de tests pour consolider le développement de cette fonction serait un plus

je manque d'exemples que tu as dût voir passer @TmpName au gré des évolutions.  
de même si on peut me faire un retour sur les quelques remarques ci-dessus ?

**Comment by TmpName** [comment]
>quel est le but de la fonction TraiteTitre ?

C'est une fonction vitale, elle prend le titre donné par les divers sites qui ont chacun leur syntaxe et mode d'affichage et le reformate de maniere unifié et en profite pour recuperer les infos comme la saison pour les series.

>est-il pertinent de supprimer étape après étape des morceaux de chaîne plutôt que d'extraire les infos (titre, année, saison, épisode etc) et générer / remettre en ordre les infos suivant une règle attendue ?

Bonne question, mais tu imagines la tete du regex qui ferait tout en une fois, et ca augmente aussi les temps de calculs. Et mine de rien de supprimer morceaux par morceaux facilite le regex, et ca ne coute rien en calcul (les manipulations de chaines ne coutent rien en ressources, surtout compare aux regex)

>cette partie est critique et peut avoir des effets de bord

Grave, fonction tres sensibles.

>implémenter une classe de tests pour consolider le développement de cette fonction serait un plus

Ben je voyais pas si loin, vu le bordel que c'est pour lancer une fonction dans le core de kodi. J'ai aussi vite fait d'ouvrir un site de "python en ligne" faire un c/c dedans pour tester la fonction
Mais de mettre en commentaire juste au dessus de la fonction, tes exemples, pour moi ca suffit, un c/c dans regex, le nouveau regex a tester, et on voit de suite si ca passe ou pas
Par contre la fonction etant composé de plusieurs regex et de traitement divers, ca ne testera jamais l'ensemble, mais ce n'est pas une fonction qui retourne "un" resultat, elle met a jour pas mal de données, moins facile de faire une classe de tests
Mais comme on y touche pas les jours, pour moi mettre tes exemples en com suffit largement a tester la fonction (les seuls qui vont oser y toucher savent se servir de regex101)

**Comment by sizanic** [comment]
J'ai revu les regex pour une meilleure compatibilité des fichiers Uptobox.

J'ai retiré le support des doubles numérotations du genre S01E20-2
Car le numéro d'épisode n'est plus un simple texte entretenu seulement par vStream, il doit être compatible avec les skins de Kodi.

**Comment by sizanic** [comment]
La version 1.8.0 de vStream est sortie avec la correction nécessaire à ce problème.
