### ISSUE TITLE
Impossible de se déconnecter de notre compte Trakt

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3381]
Bonjour,

Le suivi Trakt ne fonctionne plus depuis la maj, de même qu'il n'y a plus les options disponibles pour Trakt dans le menu contextuel

Merci pour votre travail,
A+

**Comment by alKODIque** [comment]
Oups..
En seulement, il est impossible de se déconnecter de notre compte.
Voir mon log
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7333700/kodi.log)

**Comment by alKODIque** [comment]
Je confirme que les visionnages ne se synchronisent pas.
D'ailleurs, d'après mon historique, plus rien ne se synchronise pour moi depuis le 24 septembe: https://trakt.tv/users/alkodique/history/all/added

Mais:
- Je vois mes listes perso dans mon compte;
- je suis capable d'ajouter des items à ma collection
- Si je ''Like'' depuis vStream, ça fonctionne aussi

Mais aucune synchronisation de visionnage. Avant, je n'avais qu'à ouvrir le site trakt.tv depuis mon iphone et j'y voyais immédiatement l'épisode ou la série que j'étais présentement en train de visionner. Maintenant non

Je sais que vous avez plusieurs autres priorités... 
Mais ce sera pour garder en note pour plus tard sinon :)

**Comment by sizanic** [comment]
Plusieurs modifications concernant Trakt ont été mise en place dans la dernière version.

-> Je clos cette demande.

Il faudra en ouvrir une nouvelle si un probleme persiste avec la dernière version.
