### ISSUE TITLE
Bug de chargement ça sur french Stream. Lol via la bêta

### ISSUE THREAD

**Issue by mickve** [Kodi-vStream/venom-xbmc-addons#3383]
**Décrivez le bug
J ai mis à jour via la bêta et le site french stream.lol bloque au chargement du coup je remis une ancienne mise à jour pour que ça refonctionne
**Votre system**
 - OS:androïde
-  Appareil [beelink gt King]
 - Version Kodi  [19]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- french stream.lol
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

**Comment by razorex** [comment]
C'est corrigé
