### ISSUE TITLE
Plantage à la fin de lecture d'un épisode tv

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3384]
Encore moi 👋😋

J'ai remarqué que lorsque je termine un épisode de série télé, il y a comme un genre de plantage qui se produit, ou je suis expulsée de vStream pour me retrouver dans la section Vidéos de kodi.

- Ceci ne se produit pas avec les films. **Seulement avec les séries**.

- J'ai la dernière beta disponible au moment de ce message d'installé sur ma shield en kodi 19.1

**Voici mon log:**
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7342086/kodi.log)

**Comment by razorex** [comment]
@alKODIque est ce toujours d'actualité ? Sinon ferme cette issue.
