### ISSUE TITLE
Nouveau host Kaydo

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#3386]
Il y a un "nouveau" host (en réalité il existe depuis longtemps, mais n'était utiliser sur les sites Français) sur le site de Kaydo nommée Hydrax.
J'ai déjà commencé à avancer un peu, mais je ne comprends pas comment il génère la playlist.

Il est trouvable sur la saison 1 de Burden of Truth.
Et, je pense qu'il va de plus en plus apparaitre.
https://github.com/Arias800/Fichier-divers/blob/master/hydrax.py

**Comment by TmpName** [comment]
Purée mais quelle usine, tu as passé combien de temps la dessus ?
Ca fait peur.

**Comment by Arias800** [comment]
J'ai mis a jour le code.
Cette fois, la durée est détectée directement via le chunck.
Le problème maintenant, c’est qu'il n'y a pas de buffer.

**Comment by Arias800** [comment]
C'est surtout que ça me permet de voir ce qu'on peut faire avec ce système de serveur local mdr

**Comment by sviet2k** [comment]
Bonsoir @Arias800,

Est-ce-que ce hydrax.py peut résoudre aussi le playhydrax?
hxxps://playhydrax.com/?v=fwLbJEvwb

Merci pour ton aide

**Comment by Arias800** [comment]
Le code ne marche pas, je n'arrive pas à dialoguer avec le websocket comme le site le fait.

**Comment by sviet2k** [comment]
Très dommage :(

**Comment by sizanic** [comment]
Qu'en est-il de ce nouvel host ?

**Comment by Arias800** [comment]
Pas de progrès, et c'est plus une perte de temps qu'autre chose d'essayer.
