### ISSUE TITLE
Qualités de visionnage des videos 

### ISSUE THREAD

**Issue by M0rn1ng574r** [Kodi-vStream/venom-xbmc-addons#3387]
Bonjour ! 
Une petite idée qui pourrait bien rendre le visionnage des videos plus fluide pour les personnes qui use de leurs connexion 4g pour regarder des films sur le plugin vstream via kodi.

L'idée est d'ajouter une fenêtre popup avant le lancement de la video qui propose de choisir la qualité video selon la disponibilité bien-sûr de chaqune des pistes videos streamé, et aussi réindexer les entrées vers les liens de videos en un seul choix (par exemple sur le menu de choix des films ensuite le choix de la source, une fois qu'on clique sur le film voulu a la place de donner plusieurs lignes de choix pour l'hébergeur de la viseo le mettre sur une fenêtre popup avec le choix direct de l'hébergeur et ensuite le choix de la qualité de visionnage) cela serais plus adapté et facile d'usage .

Je vous invite a voir le code des autres plugins kodi par exemple venom.

Merci beaucoup et sachez que votre projet et genial ! 
Bonne continuation et surtout bon codage 😉

**Comment by M0rn1ng574r** [comment]
Oui effectivement en popup ça serai un avantage pour faciliter l'accès aux contenus et aussi organiser proprement la présentation du menu,

En ce qui concerne la 4g j'ai fait allusion au débit instable comme vous savez déjà tout dépends de la force du signal reçu parfois c'est très médiocre contrairement au débit fibre par exemple du coup pour regarder une video fluide qui ne s'arrête pas au bout de chaque 3 secondes pour recharger le cache sa serai pratique d'avoir le choix de visionnage en 480 a la place de 750,  chez Netflix par exemple le lecteur bascule automatiquement de qualité selon le débit reçu, certes c'est un peu Complexe mais je pense bien qu'il y a un code pour automatiser le truc.
Enfin j'espère que cela vous donne une petite idée pour améliorer les prochaines mises a jour 🙂

**Comment by Arias800** [comment]
Vstream ne peux pas influer sur la lecture de la vidéo. Donc on ne peux pas changer de qualité à la volée.
J'avais pensé à utiliser Inpustream Adaptative (qui permets une gestion automatique de la qualité pour les fichier m3u8 et mpd sous Kodi 20). Mais malheureusement il n'accepte pas les playlists local.

Ensuite, les hébergeurs qui propose des choix de qualité sont assez rare, mais quand c'est possible, il y a le choix qui est proposé par Vstream.

**Comment by sizanic** [comment]
"ça le fait déjà" veut dire qu'il n'y a rien à faire, il n'y a pas de paramètre.


> Quand un hebergeur propose plusieurs qualités, il ya un popup pour selctionner un choix.

Ce type d'hebergeur est rare.

Il y a bien uptostream qui proposais plusieurs qualités pour un même flux.
Et il y avait bien une popup dans ce cas.

Mais ils viennent de changer, et ne proposent plus qu'n seul lien.
