### ISSUE TITLE
Source pour vstream 

### ISSUE THREAD

**Issue by Oruspo09** [Kodi-vStream/venom-xbmc-addons#3388]
Bonjour Je vous propose un nouveau site pour les screen qui est vraiment au top et qui fonctionne super bien voici le lien merci de le rajouter
http://tra tov.com/9ue3btn3wby99/home/tratov/

**Comment by sizanic** [comment]
- La seule page de "films(Derniers ajouts)" de kepliz contient bien tout les films (et dans le même ordre) que la page d'acceuil du site trat0v.
- J'ai bien toutes les pages dans la catégories "Films (a l'affiche)".
- J'ai testé quelques liens et les films se lancent.

Mais je t'avoue que j'utilise une version corrigée qui sera dans la prochaine version de vStream.

Le site que tu propose est vraiment un clone et n'apporte rien.
=> Nous avons corrigé kepliz.

**Comment by Oruspo09** [comment]
Ah OK car moi j'ai énormément de site qui ne fonctionne plus du coup j'utilise que wiflix qui est top, on verra la mise à jour merci

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Arias800** [comment]
Je rajoute un truc. Sur certain site, Kodi n'arrive plus à lire les jaquettes qui sont donné par les sites.
Pour le moment, il n'y a pas de correction pour ce bug précis.

**Comment by Oruspo09** [comment]
Bonjour tout les sites sur vstream ne  fonctionne plus depuis aujourd'hui merci

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
