### ISSUE TITLE
Plantage Neko Sama

### ISSUE THREAD

**Issue by CR3T0X13** [Kodi-vStream/venom-xbmc-addons#3391]
Bonjour, depuis quelques jours j'utilise vstream , tout est nickel , sauf que depuis hier , lorsque je cherche un animé , je met le nom en question dans la barre de recherche , le logiciel plante à 10/19 sur Neko Sama , j'ai beau réessayer , lancer kodi en admin , vider les caches , rien y fait , toujours à neko sama ça plante ... (il m'est donc impossible de visionner mon animé 👎 ).

Merci à vous !

 - OS: [Windows]
 - Version Kodi : Matrix 
- Version Vstream

**Comment by CR3T0X13** [comment]
up , ça re plante , tjr neko

**Comment by yodidon** [comment]
> up , ça re plante , tjr neko

Toujours via la recherche ?

**Comment by CR3T0X13** [comment]
> > up , ça re plante , tjr neko
> 
> Toujours via la recherche ?

Via recherche oui , arrivé à neko , l'app se ferme , et lorsque je vais dans l'historique des recherches de mon animé , rien ne se passe , ça cherche mais dans le vide , depuis que neko plante

**Comment by TmpName** [comment]
Bon ben com d hab, ca marche sans soucis de mon coté, un probleme temporaire du serveur ?
Tu mets quoi comme mot a rechercher ?

**Comment by CR3T0X13** [comment]
> Bon ben com d hab, ca marche sans soucis de mon coté, un probleme temporaire du serveur ? Tu mets quoi comme mot a rechercher ?

recherche -> nom de l'animé -> recherche (animés) ensuite ça charge jusqu'à 10/20 à neko sama , plantage de l'app

**Comment by CR3T0X13** [comment]
Bon bah j'ai viré neko sama des sources , et ça marque parfaitement ...

**Comment by TmpName** [comment]
Mais tu as mis quoi comme titre ? que je reproduise l'issue, car ca passe chez moi.

**Comment by CR3T0X13** [comment]
> Mais tu as mis quoi comme titre ? que je reproduise l'issue, car ca passe chez moi.

" detective conan "
