### ISSUE TITLE
Installation vstream sur kodi impossible

### ISSUE THREAD

**Issue by Marieug31** [Kodi-vStream/venom-xbmc-addons#3393]
Bonjour,
J’ai reçu ma nouvelle bbox Must.
J’ai bien mis Kodi dessus mais lorsque je tente d’installer le repository depuis le fichier zip, ça ne fait rien.
Apparemment, il n’est pas connecté au réseau.
Vous pouvez m’aider?
Merci 👌🏻😊

**Comment by sizanic** [comment]
Je clos. Il faudra revenir avec un nouveau détail si le probleme persiste.
