### ISSUE TITLE
Site fullmatchtv (Replays de plusieurs Sports)

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#3399]
![logo2-1](https://user-images.githubusercontent.com/48101775/139210903-ea341be1-b877-4757-ae10-6addd4c560bc.png)
✋
Voici le site  https://full match tv.com/ qui pourrait enrichir Vstream en sports Replays.

 Propose en Replay HD etc.. plusieurs Sports en vo (Mma,Nba,Nfl,Motorsport, Rugby etc..).✔️

**Comment by lebigboss** [comment]
génial, la qualité est ouf et le lecteur aussi, très fluide
Je vais enfin pouvoir me remettre à regarder des matchs de NBA et de MMA qui passe beaucoup trop tard
Merci

**Comment by sizanic** [comment]
Ce sera disponible dans la prochaine version.

Merci @yodidon 👍🏻

**Comment by victore447** [comment]
✋
![GOODJOBstudio_BrandonAnimé](https://user-images.githubusercontent.com/48101775/148412080-cf1d8e73-e68a-4d7c-b3bb-69e738c73c82.gif)

**Comment by sizanic** [comment]
De rien 😄 

En effet, nous ne l'avons pas rappelé ici, mais nous avons sortis une version la semaine dernière, avec cette nouvelle source.
