### ISSUE TITLE
Bug via la bêta

### ISSUE THREAD

**Issue by mickve** [Kodi-vStream/venom-xbmc-addons#3401]
**Décrivez le bug**
Bonjour,j ai un bug en mettant à jour v stream via la beta
J ai une erreur "la dépendance de xbmc.python version 2.1.0 n'a pas plus être satisfaite " . Du coup j ai plein de site qui me mette "aucune information "
French stream.lol
Enstream
Dpstream hd
Vf série ça me met aucune information quand je clique sur un épisode
Etc...
Une solution!😭😉

**Votre system**
 - OS:Android
-  Appareil beelink gt king,t95q
 - Version Kodi  19.3
- Version Vstream 1.1.0

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
![image](https://user-images.githubusercontent.com/48685663/139598679-c5ebfe9b-1d85-4993-8729-5af45fdd64f5.jpeg)

**Plus**
- [ ] Ajoutez plus d'information sur le problème ici.

**Comment by sizanic** [comment]
Nous n'apportons pas de support aux Beta, elles sont forcement instable.
C'est une copie du code à un moment donnée.
Le code évolue en permanence.

**Comment by sizanic** [comment]
> Version vStream 1.1.0

???

La dernière version stable est en 1.6.0 🤔

**Comment by mickve** [comment]
Oui effectivement je me suis trompé j étais en 1.6.0
Mais ce matin tous les site qui ne fonctionnait pas hier refonctionne.☺️
