### ISSUE TITLE
Affiches film/series WFLX

### ISSUE THREAD

**Issue by Che-Debaras** [Kodi-vStream/venom-xbmc-addons#3403]
**Décrivez le bug**

Wiflix n'affiche plus les posters de films ou series url wiflix.land

✅"_Dood ne fonctionne plus sur les nouvelles versions de kodi 19.3 et 20.0
NB :  dood ne fonctionne pas sue kodi 20, affiche un msg de cloudflare alors que sue 19.1 dood fonctionnais.
Donc il se peut que dood fonctionne sur 19.1 (je dois retrograder pour vérifier) mais en tout cas il ne marche plus sur 19.2 19.3 et sur 20 donc_ " **RÉSOLU** 

**Votre system**
 - OS: Android
-  Appareil [SmartTv, tf300t,s8+]
 - Version Kodi  [19.3] 
- Version Vstream 1.6.0

**Nous devons le reproduire**

- Le nom du site : wiflix pour les affiches et toutes sources pour dood
- Le titre du fim/serie : tous 
- Le nom du host : dood

**Comment by razorex** [comment]
Salut, oui je confirme que sur la 19.1 sa fonctionne et ne fonctionne plus en 19.3

**Comment by Che-Debaras** [comment]
> Salut, oui je confirme que sur la 19.1 sa fonctionne et ne fonctionne plus en 19.3 Pour moi le souci vient de tes dns, j'avais eu le même souci avec uqload.

Non le problème ne viens pas des dns car j'utilise l'application Dns changer que je connecte sur le dns de cloudflare
Sur 19.1 ça marchais chez moi mais j'ai maj a 19.3 et je pensais pas que y'aurait des changements problèmatique.
Sans dns, on a des sources vides sur v19 mais pas sur v20

**Comment by Che-Debaras** [comment]
Le problème est résolu  avec le commit 9784c17
J'ai testé sur mon Smartphone android et kodi 20 (dernière version du 05 Nov 2021)

Donc je suppose qu'il devrait marché sur kodi 19.3.

Merci @Arias800?

Je clos le sujet

**Comment by Arias800** [comment]
Oui j'ai oublié de mettre un message.
Pour Evoload, ça a l'air d'être un problème de timeout car le site mets très longtemps a répondre.

**Comment by Che-Debaras** [comment]
> Oui j'ai oublié de mettre un message. Pour Evoload, ça a l'air d'être un problème de timeout car le site mets très longtemps a répondre.

Qu'en est il des affiches sur wiflix qui ont disparu ?

**Comment by razorex** [comment]
Salut @Che-Debaras est ce que tes affiches sont revenues ??
Chez moi elles sont présentes et je viens de changer l'url de la source.

**Comment by Che-Debaras** [comment]
Oui c'est revenu , avant ta modification j'avais pas toutes les affiches mais là c'est bon donc je pense fermer le sujet.

Merci encore
