### ISSUE TITLE
C'est quoi ce titre ???????

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#3404]
Bonjour,
depuis un moment il y a des modifications d'affichage du titre.
donc voila le résultat
![titre](https://user-images.githubusercontent.com/26149640/140512112-18fed858-e406-42ea-8f18-a997b41a6cb3.png)

plus de SxxExx et plus de titre !!!! Et si je met en marque-page je me retrouve avec le même problème.
Alors est-ce la nouvelle orientation d'affichage de titre ou juste le fait que les modifications ne concernent que les user de metas et que l'user standard aurait été oublié. Je précise même si cela semblais clair que je n'utilise pas les metas et que toutes les sources sont impactés.

**Comment by sizanic** [comment]
Salut, 

> plus de SxxExx et plus de titre !!!! 
Alors est-ce la nouvelle orientation d'affichage de titre ?

S01E02 a été remplacé par 1x2. - Normalisation du nom avec ce qui peut être vu ailleurs, et ça prend moins de place.

plus de titre -> le titre de quoi ? de la série ?
La série c'est "Foundation".
Il n'y pas d'interet à le répéter sur chaque épisode 🤔 
On l'enleve, ça prend moins de place, pour une meilleure compatibilité avec les skins.

=> Donc oui, c'est bien la nouvelle orientation d'affichage => "épuration"

> les modifications ne concernent que les user de metas et que l'user standard aurait été oublié

non, avec les métas, c'est la même chose. "1x2" pour la numérotation et pas de nom de la série.
Ce qui change est que si les méta proposent un titre d'épisode, "Episode 1 " est remplacé par ce titre d'épisode.


> si je met en marque-page je me retrouve avec le même problème

Si la marque-page n'affiche pas le nom de la série, là il y à un problème, faudra qu'on corrige.


Pour la mise en place de cet affichage, il y a eu des discussions ici : 

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/2478165a41f582a4ae908c9244a9da6e466dc7b9#r55662162

Auquel tu as participé, ce qui nous à permis de ne pas enlever completement la numérotation des épisodes, avec les inconvénients que tu nous as soumis.

Et il y eu également près d'une centaine d'échanges ici (commentaires/corrections / tests) : 
https://github.com/Kodi-vStream/venom-xbmc-addons/pull/3354#issuecomment-903099896
