### ISSUE TITLE
vStream / 1fichier.com no stream possible. 

### ISSUE THREAD

**Issue by Jonny0r** [Kodi-vStream/venom-xbmc-addons#3406]
Sorry, my french is not the best i try to do it on english. :)

Downloaded the latest Kodi for Windows, Downloaded vStream from your repo and installed it.
I added a 1fichier.com premium to it and logged on there, i see some Video Test files which i uploaded (.mkv)
but when i click on them it starts loading for 1-2 sec and nothing happends.

**Votre system**
 - OS: [Windows]
 - Version Kodi  [19.3]
- Version Vstream 1.60 (rep x.4)

[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7492371/kodi.log)

**Comment by Smanar** [comment]
Hello.

> 2021-11-07 14:32:03.893 T:38500   ERROR <general>: ModuleNotFoundError: No module named 'resources.hosters.1fichier'

It s a name problem, give me  15 mn.

**Comment by sizanic** [comment]
It seems like #3402

**Comment by TmpName** [comment]
Yep.
Can you try to just rename your plugin.video.vstream/resources/hosters/onefichier.py to 1fichier.py ?

**Comment by Jonny0r** [comment]
Hello,

Thanks for your support,

with the BETA Update its working, but only when the File is "NOT" password protected. 
Is there any way to add the password to the plugin as i would like to keep the files private. 

![07-11-_2021_18-47-48](https://user-images.githubusercontent.com/3064788/140655921-2c065069-10ee-4742-b2c0-ed8b8e8daf26.jpg)

[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7492789/kodi.log)

**Comment by TmpName** [comment]
A password ? where ?
On 1fichier website ? on public link or personnal one ?

**Comment by Jonny0r** [comment]
Hello @TmpName,

on Personal Drive, i put mit Credentials (Login / Pass) into the Plugin, but when i try to start something i need to enter the password. 

This link is from my Log File (above) https://1fichier.com/?7jjeaj9ys2iblc64kezh , its from my personal drive and this is what the 1F Plugin tries to read, if i remove the password its fully working, but then no longer personal .. you know what i mean? :)

**Comment by TmpName** [comment]
But there is a problem.
All hosters can use a different password, and it will block all videos, if the password is displayed on the web site, Vstream can't guess it.
So not possible for publics links.

And if you use the source "Compte1fichier" you need also a password ? I m seing a part in the code that use a code.

**Comment by Jonny0r** [comment]
Hello @TmpName 
Yes, i understand that its not possible for public links, but VSTREAM is extracting this "plublic" link out of my Premium Account which is added in the "Addon". 
I only set a download Password, as im not sure if somebody von external could access my files which i dont want (except me :P).

Perhaps i have a wrong point a view on this and i dont need the password? 

I did a small video perhaps i do something wrong :)

Please let me know.

https://user-images.githubusercontent.com/3064788/141698453-75849e64-e7aa-4880-bfe5-56226b400c9c.mp4

**Comment by TmpName** [comment]
And if you use the website, it ask too for the password ? Even you are connected on your 1ficher account ?

**Comment by Jonny0r** [comment]
@TmpName Hello Sir. :)

Thanks for your support. Yes, even if im logged on he will ask for the password.

Attached a picture how it looks like :)

![16-11-_2021_20-34-02](https://user-images.githubusercontent.com/3064788/142053462-1376a2fe-ff85-4683-91a4-9d6ecef3fe80.jpg)

**Comment by TmpName** [comment]
Can you try with this fichier ? https://github.com/TmpName/Fichier_en_vrac/blob/master/1fichier.py
It will not work, but I m interested by logs.

You can try with setting the password on line 20

**Comment by Jonny0r** [comment]
@TmpName , Hello Sir :)

I exchanged the Script in the folder "..\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\hosters" and added the Password to Line 20.

Please find attached the log. :)

Regards

[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7564577/kodi.log)
,

**Comment by TmpName** [comment]
There is something bad, you are using last beta ?

>[PLUGIN] vStream: Utilise compte premium pour hoster onefichier

The name is now 1fichier. And it provoke a new issue, 

>[PLUGIN] vStream: Utilise compte gratuit pour hoster: 1fichier

Because the login/pass was still for the hoster onefichier, have just updated the beta again.

IDK if the page language change something but on my side I have too in logs
>INFO <general>: 	[PLUGIN] vStream: page protegee par mot de passe

**Comment by Jonny0r** [comment]
Hello,

Now i took the latest Beta (my last was from 7.11 dont know if there was some update later)
AND used your code for the 1fichier.py file & added the password.

But looks like as it would be still "onefichier".

I used this Plugin: and copied it completley to the addons folder.

https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/plugin.video.vstream

and changed the hoster 1fichier.py to:

https://github.com/TmpName/Fichier_en_vrac/blob/master/1fichier.py

[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7565686/kodi.log)

**Comment by TmpName** [comment]
Something is not working ...
Do you know python ?

```
        if '<input class="input-text ui-corner-all" type="password" name="pass"' in sHtmlContent :
            VSlog("Lien protegee par mot de passe")
```

I m making a test to check if the page have a password, it work on my side but not yours.
It's perhaps because of your settings, can you check the link in a browser then use the browser option "show source code" and check if you have the same string ?

**Comment by Jonny0r** [comment]
@TmpName, Hello Sir, Sorry for the late Feedback.

I used Google Chrome to check the source (latest version) and i was logged in the Page. Then i took the link from a file which i posted already above.

Its not exactly the same then you get. I posted a screenshot to show you more.
![21-11-_2021_21-53-00](https://user-images.githubusercontent.com/3064788/142778596-2f7693c2-16ae-4ca2-a6d8-bef9b1bf4fd4.jpg)

Thanks for your support

![21-11-_2021_21-51-17](https://user-images.githubusercontent.com/3064788/142778591-96edefd0-af28-4b50-baa1-661a67adc05f.jpg)

![21-11-_2021_21-53-00](https://user-images.githubusercontent.com/3064788/142778596-2f7693c2-16ae-4ca2-a6d8-bef9b1bf4fd4.jpg)

**Comment by TmpName** [comment]
>Its not exactly the same then you get

You are seing a difference ?

Else around line 212, there is this code

```
        fh = open('c:\\test.txt', "w")
        fh.write(sHtmlContent)
        fh.close()
```

Can put just after the else line 166

```
            else:
                fh = open('c:\\test.txt', "w")
                fh.write(sHtmlContent)
                fh.close()
                if '<input class="input-text ui-corner-all" type="password" name="pass"' in sHtmlContent :
```

It will save the html code in a file c:\\test.txt, but it depend permit right on the machine, you probably need to chnage the path too

Don't share the file, you can have personnal information inside, but try to find the same line.

**Comment by Jonny0r** [comment]
Hello Sir, Thank you very much for all your time.

Yes, this Lines are there in the 1fichier.py. 

But it doesnt create anything, also tried to create an empty file with this name, but also not.

Original the Code on Line 212 is commented with a "#", but when i remove it, it makes also no difference.

I guess this script should get exectured when i try to start something with Kodi?

**Comment by Jonny0r** [comment]
Just to show you.. added the line like on the photo, but it doesnt create anything not when i write d:\\ or d:\ ..

![23-11-_2021_23-08-34](https://user-images.githubusercontent.com/3064788/143137107-c834e49c-70e7-4165-9740-1d1aff127961.jpg)

**Comment by TmpName** [comment]
And no error ?

I have updated the file https://github.com/TmpName/Fichier_en_vrac/blob/master/1fichier.py

With all possibles debugs, if you haven't number in logs, it will mean Vstream don't use the file.

**Comment by Jonny0r** [comment]
Hello Sir @TmpName,

dont be bad with me, but for some reason the 1fichier.py was not loaded, it addon always went back to the onefichier.py plugin. I copyed your latest beta and renamed the file 1fichier.py to onefichier.py then your script was working.

First saw this when i checked the log correctly :( Sorry for that, but attached the logs : *I removed my mail..

[test.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7605324/test.txt)
)
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7605328/kodi.log)

**Comment by TmpName** [comment]
Ha nice it's better, we have the line now

>[PLUGIN] vStream: Lien protegee par mot de passe

So you have a popup with "Lien protege par mot de passe" Or you have put your password on line 20.

If I m right you have the popup only if the password is empty, and with luck if you set the password it will work.

**Comment by Jonny0r** [comment]
Hello Sir.. :)

I just set the password (in both files just to be sure xD), but i get the message that the file would be "not available".
If i open the Link in the Browser, its no problem at all.

Attached again the Kodi log, the Test.txt is still activated and give some errors because its not started in admin mode, but this doesnt change it. :)

[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7611512/kodi.log)

**Comment by TmpName** [comment]
So I m sorry but will be not possible.

The Vstream code don't use the same HTTP request than the one I can reproduce on my side with the browser. So to reproduce it I need to change all this part, and this part is working for other, so I prefer don't touch it.
I realy don't know where the code is from, but it s working for long time, so for me it s something stable I prefer let as it.

**Comment by Jonny0r** [comment]
Hello Sir,

Thanks for your answer. =) Yes, than it will be like that, but many many thanks for all your time, sharing and trying to support me. :)
