### ISSUE TITLE
Dood et kodi 18.9 ipad

### ISSUE THREAD

**Issue by Che-Debaras** [Kodi-vStream/venom-xbmc-addons#3407]
Y a t'il une solution pour vstream sur ipad 32bits concernant dood et dns python v1.12.2?
Dood ne fonctionne pas sur kodi 18.9
Impossible de mettre a jour avec kodi 19 car n'est plus prise en charge
Et dns python derniere version est en python 3.0

Merci

**Comment by TmpName** [comment]
Je pense que dood ne marche que sur kodi 19, ca vient de la version de python, rien a voir avec le dns.

**Comment by Che-Debaras** [comment]
Oui , j'ai parlé de dns car la source en a besoin mais pas spécialement dood.
Mais pourquoi dood aurait besoin de py3 quand les autres fonctionne sur py2
Je pense qu'il y a moyen de le faire fonctionner sur kodi 18
Apres visiblement  vstream sera compatible que py3 donc pas compatible kodi 18?

**Comment by Arias800** [comment]
Je pense que ça viens de la librairie requests.
C'est la librarie que Vstream utilise pour les connections internet, et dans une version précise, il semble quelle peu déclencher sans raison une erreur de Cloudflare. 
Ce qui semble être corrigé avec Kodi 19.

**Comment by Che-Debaras** [comment]
Merci @Arias800 mais ce hoster peut-il être corrigé pour kodi 18.8 ou kodi 18.9 car j'ai un ancien ipad qui n'est compatible que kodi 18.9 max.
Kodi abandonne les anciens ipad donc pas de kodi 19 et pas de python 3 donc est ce que dood peut etre résolu pour ces anciens ipad et kodi 18.9?

**Comment by Arias800** [comment]
Je ne peux pas dire, je n'ai pas d'ipad pour voir d'où viens le problème et donc le corriger.

**Comment by Che-Debaras** [comment]
> Je ne peux pas dire, je n'ai pas d'ipad pour voir d'où viens le problème et donc le corriger.

Je pense que c'est le même problème que sur android,  puisque dood ne fonctionne pas sur kodi 18.8 ou 18.9.
Donc je pense si dood fonctionne sur kodi 18.8 ou 18.9 Android il marchera sur kodi 18.8 18.9 sur ios car tout fonctionne parfaitement à part dood.

Est ce que dood fonctionne sur android kodi 18.9? Car mon ipad a kodi 18.8 donc jvais maj a 18.9 et voir si dood fonctionne 

Mais je pense que le souci vient du fichier dood qui est incompatible avec kodi 18 que ce soit android ou ios voire meme pc, peut etre il es codé uniquement en version python3?

**Comment by TmpName** [comment]
Rien a voir avec android, dood ne marche pas non plus sur windows, et la raison a été donné par @Arias800 
Kodi 18 marche avec python 2

**Comment by Che-Debaras** [comment]
Je clos ce sujet.
