### ISSUE TITLE
Mystère sur les interruptions des sources...

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3408]
Je n'ai toujours pas compris ce qui provoque ces interruptions d'accès aux sources...??
Wiflix est hors service depuis hier alors que votre mise à jour 1.6.0 est récente !

Les liens sur les sites dans cet exemple wiflix, ne changent pas,  alors qu'est ce qui provoque ces interruptions ? 
Quel est le mystère que renferme vStream et qui vous oblige sans cesse à devoir réactiver les sources dans vos mises à jour ?

Ca m'intéresserais beaucoup d'avoir quelques infos techniques..

En vous remerciant
Christian

**Comment by kris06** [comment]
Et bien merci sizanic,  je comprend mieux à présent, ces infos pourront aussi informer d'autres curieux que moi...

Les sources se rétrécissent , elles sont même souvent saturées certains soirs pour les plus populaires. Les restrictions des FAI se répandent , Espérons que vos efforts seront toujours à la porté et aux bénéfices de très nombreux utilisateurs de Vstream. Il est vrai que pouvoir regarder un Bond qui est encore à l'affiche est vraiment un joli cadeau

De bonnes fêtes à vous tous et merci.
C.

**Comment by sizanic** [comment]
Mon exemple est volontairement simplifié pour justement être compris par le plus grand nombre.

Et bien que nous continuerons à maintenir vStream pour toujours proposer l'accès à ces sites, je rappelle que  nous proposons aussi une source qui ne dépend pas d'un site.
Donc :
 - pas de maintenance pour retrouver des mots clés
- Pas de saturation
- Pas de blocage FAI
- Pas de protection captcha ou cloudflare
- que des liens de qualité maintenus par les utilisateurs vStream

**Comment by kris06** [comment]
quelle est la source en question ?

**Comment by Che-Debaras** [comment]
Wiflix est un cas a part:
Upnext ne fonctionne pas
Les affiches ne sont pas présentes 
Ils ont changé de Url: .land au lieu de .club
Donc ya sûrement d'autres changements que l'url

La en ce moment il affiche " pathname cannot be converted utf8..."

**Comment by alKODIque** [comment]
> quelle est la source en question ?

il s'agit de la source Pastebin :)

info: https://lesalkodiques.com/docs/pack-des-alkodiques/

**Comment by alKODIque** [comment]
pour wiflix, a titre d'info, toutes les affiches sont présentes si les métadonnées sont activées dans les paramètres de vStream
kodi 19.3
vStream 1.6 (dernire version officielle)

Je viens de tester un film (chang-chi) et le lien a démarrer sans soucis avec evoload.

upnext semble bien fonctionner également , la reprise de média se fait sans problème pour moi (testé 1er lien de la série 4400 avec evoload)
