### ISSUE TITLE
Tag read/unread

### ISSUE THREAD

**Issue by Kodi-User-Switzerland** [Kodi-vStream/venom-xbmc-addons#3410]
Bonjour,

Petite question d'ordre générale

Oû sont stockés les flags Read/Unread des favories et des liens Vstream.

Merci beaucoup.

Et continuer top boulot.

**Comment by sizanic** [comment]
Bonjour,
Dans le ficher vStream.db

Je te conseille la lecture de ce post :
#3288

**Comment by Kodi-User-Switzerland** [comment]
Merci

**Comment by Kodi-User-Switzerland** [comment]
re,

Marche plus ça, ou ça a jamais marché. Une solution de décentralisation de Vstream ?

<substitute>
      <from>special://masterprofile/addon_data/plugin.video.vstream/vstream.db</from>
      <to>smb://192.168.8.40/Kodi/Vstream/vstream.db</to>
</substitute>

**Comment by sizanic** [comment]
Donc c'était bien ta vraie question.
Savoir comment décentraliser la base et pas où se trouve les fichiers 😁

Je n'ai pas suivi la discussion à propos du substitue, pour te dire si ça peut le faire.
Mais cela m'étonnerait.

Pas de solution à ma connaissance.
