### ISSUE TITLE
Vstream error at startup 

### ISSUE THREAD

**Issue by lorieje** [Kodi-vStream/venom-xbmc-addons#3411]
Depuis l'update de kodi vers la version 19.3 je reçois au demarrage l'erreur vstream error.
Je n'arrive plus à acceder aux chaines sportives du chemin suivant : sports-->Sources-->Channel Stream-->Sport, elles affichent toutes "no information"
Mon systeme
 - Linux Mint 19.3 kernel linux 5.4.0-90-generic
-  Lenovo ideapad 330
 - Version Kodi  19.3
 - Version Vstream 1.6.0
[kodilogtobesent.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7555526/kodilogtobesent.log)

**Comment by sizanic** [comment]
Ce n'est pas un problème de la version 19.3.
C'est un problème général.
Nous avons constaté ce problème et travaillons à sa résolution.

**Comment by lorieje** [comment]
merci pour ce feedback et bonne journée

________________________________

**Comment by Arias800** [comment]
Un conseil, supprime tout ce qui les Wizard et ce genre de cochonnerie.
Ton installe s'en portera que mieux.
Et avoir  `ImportError: cannot import name 'ThreadingHTTPServer` alors que tu es sous Python 3, c'est pas normal.
À tous les coups, c'est ton installe qui est toute pourris avec des addons a la con qui créer des conflits.

**Comment by sizanic** [comment]
@lorieje 

Le souci n'est pas chez nous, mais chez notre fournisseur qui ne propose plus beaucoup de chaines.
La chaine RMC1 est actuellement dispo sur leur site, et **également** sur vStream 👍🏻
