### ISSUE TITLE
Problème de lecteur 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#3412]
Bonsoir à tous alors voici mon problème qui m empêche de regarder des animés sur ianime qui demande souvent 
Dood qui est actuellement sous cloudflare 
Streamtape qui marche jamais :/ 
Pstream non plus 
C est embêtant le site propose ces lecteurs qui marche même pas pour l instant avec la version 1.6.0

si quelqu’un a des infos sur une futur Maj qui règle tout sa 
Merci à tous

**Comment by TmpName** [comment]
Heelo, dood fonctionne sur kodi 19.
Pour les autres tu aurais un titre d'animés pour que je teste de mon coté, j'ai moins de soucis de mon coté.

**Comment by Mokoman30** [comment]
Moi Dood fonctionne ni sur le 19.3 android tv 
Ni sur le 18.9 sur une box android 

Pareil pour les autres lecteurs 

Teste Le dernière épisode de Shaman king 
Chez moi les lecteurs cités au dessus fonctionne pas depuis longtemps 
J’espère une Maj vite

**Comment by yodidon** [comment]
Peut être pas les bon episodes mais testé sur streamz et lancement de l’épisode (kodi 19.3 androïde tv vstream 1.6.0 dns Google)

**Comment by yodidon** [comment]
Sinon il me semble qu’ils sont dispo sur la source adkami

**Comment by Mokoman30** [comment]
Protection cloudflare pour dood 
Et pour les autres lecteurs cités au dessus il se passe rien sa marche pas

**Comment by TmpName** [comment]
Version VF ?
Dood et StreamZ ok chez moi
Upsteam HA sur le site aussi.

**Comment by yodidon** [comment]
> Version VF ?
> Dood et StreamZ ok chez moi
> Upsteam HS sur le site aussi.

Dood ok pour toi ?

**Comment by TmpName** [comment]
Yep, dood a toujours marché depuis mon passage en kodi 19

**Comment by yodidon** [comment]
> Yep, dood a toujours marché depuis mon passage en kodi 19

Pour moi cloudfare sur dood

**Comment by TmpName** [comment]
Je suis sous windows

**Comment by Mokoman30** [comment]
Sa me fais erreur page protéger par cloudflare veuillez exécuter Flaresolver

**Comment by yodidon** [comment]
Pour moi aussi dood est sous cloudfare et malheureusement flaresolver ne résout pas le problème, j’essaie de comprendre pourquoi tmpName n’as pas ce souci

**Comment by TmpName** [comment]
Et j'ai pas installé Flaresolver.
