### ISSUE TITLE
[ChannelStream] - "Aucune information" peut importe la chaine

### ISSUE THREAD

**Issue by 3dzack** [Kodi-vStream/venom-xbmc-addons#3413]
**Décrivez le bug**
à chaque fois que le clique pour ouvrir une chaine je tombe dans un dossier avec écrit "aucune information" et donc je ne peux pas regarder cette chaine, j'ai aussi essayer sur un docu idem même problème 
*
**Votre system**
 - OS: [linux]
-  Appareil [rp4]
 - Version Kodi  [last]
- Version Vstream

**Nous devons le reproduire**
tout vstream

**Comment by sizanic** [comment]
Bonjour,
Nous avons également constaté ce problème et travaillons à sa résolution.

**Comment by 3dzack** [comment]
merci ^^

**Comment by sizanic** [comment]
Attention.

Je parle seulement des chaines de sports venant de Channel Stre*m
Ce site ne propose plus pour l'instant les chaines de cinéma.
Donc nous ne pouvons pas les proposer non plus.

Et pour les chaines de sports, nous pourrons les proposer lorsqu'elle seront également revenu sur leur site.

**Le site ne propose plus actuellement aucune chaine !!**

**Le souci n'est pas chez nous, mais chez notre fournisseur.**

**Comment by sizanic** [comment]
J'ai testé un peu plus et finalement il n'y a aucun probleme avec vStream.

La chaine RMC1 est dispo sur le site, et **également** sur vStream 👍🏻

**Comment by djdave51** [comment]
Je confirme que RMC Sport 1 fonctionne (Eurosport aussi).
Avez vous des nouvelles pour les autres chaines?
Si Channelstream ne fonctionne plus, avez vous la possibilité d'intégrer d'autres flux sur VSTREAM? EN effet, streammonsport ne marche pas non plus...
Merci pour votre travail...

**Comment by sizanic** [comment]
> Avez vous des nouvelles pour les autres chaines?

Il faut se rendre sur leur site pour avoir des nouvelles, ils ont également un serveur Discord avec leurs annonces.
Nous n'avons pas plus d'info que ce qu'ils publient.


> avez vous la possibilité d'intégrer d'autres flux sur VSTREAM?

c'est le fonctionnement même de vStream : intégrer des flux 🤔 
As-tu des flux à proposer ?

Par contre nous n'intégrons que des flux disponibles.
Si ChannelStream ou Streamonsport ne proposent plus de flux, nous ne pouvons pas les inventer.

**Comment by sizanic** [comment]
La source Live-TV propose toujours des flux valides pour le sport.

**Comment by djdave51** [comment]
> Je ne la trouve pas dans l'arborescence. Pourrais tu me faire un screen?

**Comment by sizanic** [comment]
![image](https://user-images.githubusercontent.com/47307622/143856624-a1890898-99d5-46fb-9a2c-0db9a5d596a0.png)


😆

**Comment by djdave51** [comment]
Merci mais aurais tu le chemin pour y accéder? C'est dans VSTREAM ou faut il installer un autre addon?

**Comment by sizanic** [comment]
C'est dans vStream, c'est une **SOURCE** vStream, donc le chemin complet, comme pour toutes les **SOURCES**, c'est : 
"**Sources**"

**Comment by djdave51** [comment]
> 

Merci je regarderai ce soir.

**Comment by djdave51** [comment]
hesgoal.com mais je ne sais pas si vous pouvez en faire qq chose...Le 29 nov. 2021 14:05, sizanic ***@***.***> a écrit :
C'est dans vStream, c'est une SOURCE vStream, donc le chemin complet, comme pour toutes les SOURCES, c'est :
"Sources"

**Comment by djdave51** [comment]
J'ai essayé livestream mais la plupart des liens sont vides et pour ceux qui ne le sont pas, impossible de charger le flux (message d'erreur avec et sans VPN)...
Des nouvelles des investigations sur hesgoal.com?

Merci

**Comment by yodidon** [comment]
J’ai pas regardé, je regarde ça ce soir

**Comment by sizanic** [comment]
Une correction a été apportée à notre source ChannelStream.
Retour des liens pour du sports en directs.
Et c'est tout ce que nous pourrons faire.
Aucune Chaines ne sera remise.
(car aucune chaine n'est disponible sur les sites channelStream)

=> plus qu'a attendre notre prochaine mise à jour pour en profiter.

**Comment by Che-Debaras** [comment]
Nouveau url : ://channelstream.watch/chaine-tv.php

**Comment by sizanic** [comment]
Des corrections sur ChannelStream ont été apportées depuis.
Et il faut modifier le DNS pour y accéder.

Je clos ce sujet.
