### ISSUE TITLE
"Netu" au lieu de "lien direct"

### ISSUE THREAD

**Issue by HuitSoixanteQuinze** [Kodi-vStream/venom-xbmc-addons#3414]
Bonjour à tous et merci pour votre travail :)

J'ai apporté ma mi box tv s chez un ami, j'ai connecté la mi box a son wifi et les liens via channel stream ne fonctionnaient pas et se terminaient par "netu" au lieu de "lien direct".

C'est la première fois que je vois ce problème. N'ayant pas de problèmes chez moi, je me suis dit que cela pouvait venir de la box.
J'ai donc mis mon téléphone en partage de connexion et là tout était ok, pas de "netu" au lieu de "lien direct'.
La box de mon ami est une box orange (livebox 4) avec les paramètres d'origine. 

Pourriez vous me dire comment faire pour que cela fonctionne avec la box ? Merci d'avance. 

 - OS: Android
-  Appareil : Xiaomi mi box S
 - Version Kodi  19.3
- Version Vstream 1.6.0

![258713567_994465311132980_3888066964543057638_n](https://user-images.githubusercontent.com/66942760/142762753-7e009f81-9b7a-454f-8662-365e03e44e3c.jpg)

**Comment by TmpName** [comment]
???
Alors la meme machine mais connectée a internet differement n'afficherait pas les memes liens ?

**Comment by yodidon** [comment]
Hein ?

**Comment by HuitSoixanteQuinze** [comment]
> ??? Alors la meme machine mais connectée a internet differement n'afficherait pas les memes liens ?

Oui c'est exactement ca

**Comment by sizanic** [comment]
Problème de DNS, blocage par Orange

**Comment by HuitSoixanteQuinze** [comment]
> Problème de DNS, blocage par Orange

J'ai configuré la connexion a la livebox en ip statique avec dns Google directement dans le menu Android de la mi box et ca n'a rien changé 😕

**Comment by TmpName** [comment]
Tu peux cliquer dessus et lire dans les logs le lien utilisé (tu peux editer le texte)
Mais la serieux je vois pas, le DNS suis d'accord, mais ca marcherait pas du tout ? "lien direct" c'est un lien video aussi de memoire.

**Comment by HuitSoixanteQuinze** [comment]
ca marche je vais voir ca samedi et je vous partagerais ce que j'ai

**Comment by HuitSoixanteQuinze** [comment]
Impossible de reproduire le problème car depuis ce week-end j'ai "aucune information" pour channelstream et "stream mon sport"

**Comment by sizanic** [comment]
* Il faut obligatoirement changer le dns pour channelstream.
* Streamonsport à été corrigé dans la prochaines version.

Je clos le sujet.
