### ISSUE TITLE
Uptobox en source

### ISSUE THREAD

**Issue by freddykrueger59** [Kodi-vStream/venom-xbmc-addons#3415]
Bonjour et merci pour le super boulot que vous faites
J'ai un compte Uptobox premium et j'aimerais pouvoir importer mes dossiers en tant que source dans kodi . Vstream permet de les rajouter mais simplement en favoris donc sans pochette et infos .
Merci encore mille fois

**Comment by sizanic** [comment]
Bonjour,
tu ne peux pas en passant directement par vStream : il n'y pas de moyen de typer les dossiers (pouvoir dire s'il s'agit de films ou de séries).

Regardes du côté de l'outil "rclone" qui permet de monter ton compte uptobox comme un disque, tu devrais pouvoir alors ajouter les dossiers comme sources de kodi.
