### ISSUE TITLE
vstream 1.6.0 et fonction Hoster Direct 

### ISSUE THREAD

**Issue by alexlehay** [Kodi-vStream/venom-xbmc-addons#3416]
Bonjour a tous,

Tout d'abord je souhaite à vous remercier pour tout le travail accompli qui nous apporte un confort dans notre quotidien :)

Je viens vers vous car après avoir tout essayé, je n'arrive pas à utiliser l'outil Hoster Direct avec la dernière version de Kodi (ni même la beta). Cela me retourne une erreur de lecture. En version 1.5.1 il y a aucun soucis. J'utilise cet outil afin d'ouvrir les liens 1fichiers (après les avoir copié de tirexo) car je n'arrive pas à trouver les liens quand je vais directement dans sources et tirexo (aucune information).

Ce problème est-il déjà connu?

Merci pour votre aide

Alexis 

 - OS: Android 
-  Appareil: Amazon Fire Stick 
 - Version Kodi: 19.3
- Version Vstream: 1.6.0

Pour cela il nous faut:
- Le nom du site: tirexo via Hoster Direct
- Le titre du fim/serie: Ratatouille par exemple

**Comment by sizanic** [comment]
Il faudrait de nouveau tester avec la dernière version, et rouvrir un ticket si le problème persiste.
