### ISSUE TITLE
Besoin d'aide pour jouer continument un iptv lien

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#3417]
Bonjour Team,

J'ai trouvé ce Mezzo lien du site Cat iptv:
hxxp://new-pro.tv:8080/waelwael/2r1sBY8wJK/71624
Mais ça marche seulement pendant une minute. Kodi arrête de jouer après une minute.
Avez-vous une idée comment faire marcher ce lien?

Merci d'avance de votre aide

**Comment by sizanic** [comment]
Salut,
Je pense que ton lien fait partie d'un fichier m3u8 qui contient la liste des liens qui viennent après.
Chaque lien fait une minute, et kodi les lit les uns après les autres.

**Comment by sviet2k** [comment]
Merci pour ton aide mais c'est un video/mp2t.

**Comment by sizanic** [comment]
Je ne sais pas avec Kodi.
Je vois qu'avec VLC on peut lire ce lien en continue en forcant 'lecture en boucle'.
(il y a quand même une micro-coupure entre chaque changement).

**Comment by sviet2k** [comment]
C'est impossible de regarder un opéra ou un concert avec cette sorte de coupure. :(

**Comment by TmpName** [comment]
Tu n'aurais pas le lien precedent, qui donne sur celui la ?
Peut etre que le precedent fichier a plus d'info de connexions.

**Comment by sviet2k** [comment]
Malheureusement, c'est le lien trouve sur iptv. Pas de precdent lien.

**Comment by yodidon** [comment]
Ça ressemble à un lien xtream, je tenterais le coup si j’étais toi

**Comment by sviet2k** [comment]
Je ne connais pas xtream, Peux tu expliquer comment tenter le coup STP?

**Comment by yodidon** [comment]
Iptv smarter, onglet xtream code, dans utilisateur la première série de chiffres, dans passe la deuxième, et comme adresse le http jusqu’au 8080

**Comment by sizanic** [comment]
dans ce cas, il faudrait censurer cette publication en clair, car ce serait diffuser les informations d'un compte iptv 🤔

**Comment by boxkim14** [comment]
Ce lien n est pas un xtream lien

**Comment by sizanic** [comment]
sans être un lien xtream, ça reste un lien qui fait apparaitre les identifiants d'un certain Wael.

**Comment by sviet2k** [comment]
Merci tout le monde pour votre aide.
