### ISSUE TITLE
Vstream 

### ISSUE THREAD

**Issue by Oruspo09** [Kodi-vStream/venom-xbmc-addons#3418]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Windows, Android]
-  Appareil [nvidia shield, Ultra]
 - Version Kodi  [16.17.18]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.
Bonjour je tiens à vous signaler vstream installé sur boîtier Android. 
depuis aujourd'hui tous les liens de tout les site ne fonctionne plus ça lance puis le logo play s'affiche bien et plus rien le film se lance pas merci

**Comment by TmpName** [comment]
Salut, mais qu 'est ce qui te fait penser que ca vient de Vstream ?
On pourrait avoir des logs ?

**Comment by Oruspo09** [comment]
Je suis pas le seul à qui plus rien ne fonctionne ça a toujours bien marché pourtant

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sizanic** [comment]
chez moi ça fonctionne très bien, 
je ne suis pas le seul à qui tout fonctionne très bien. 

Je pense qu'on est plus nombreux à qui ça fonctionne que à qui ça ne fonctionne pas.

Donc qu'est ce qui te fait penser que ca vient de Vstream ?

**Comment by Oruspo09** [comment]
Car du jour au lendemain plus rien après je peux naviguer sur le site correctement tout voir mais dès que je prends un lien le film se lance pas,
Tu pense que ça pourrait venir de quoi alors

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TmpName** [comment]
Ton hebergeur, ton routeur, ton OS, un plugin tiers, ...
