### ISSUE TITLE
Ajouter odysee.com comme source ?

### ISSUE THREAD

**Issue by MX10-AC2N** [Kodi-vStream/venom-xbmc-addons#3419]
Bonjour à tous
Je n'ai trouvé aucun addon pour kodi permettant le lecture de vidéo du site odysee.com
Serait-il possible d'intégrer ce site dans les sources Vstream ?
Merci..

**Comment by sizanic** [comment]
Bonjour,

De même qu'il existe un addon pour youtube, il faudrait un addon spécifique pour odysee.

Mais ce n'est pas à vStream de proposer un accès à ce site.
Désolé, mais vStream ne se veut pas être l'extension à tout faire.

**Comment by MX10-AC2N** [comment]
Ah mince, dommage.. 
Merci qunad même..
