### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Gregh1969** [Kodi-vStream/venom-xbmc-addons#3420]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Une description claire et concise de ce qu'est le problème. Ex. Je suis toujours frustré quand [...]

**Décrivez la solution que vous souhaitez**
Une description claire et concise de ce à quoi vous voulez arriver.
I would like to be able to change the information and trailer source to IMDB

**Comment by sizanic** [comment]
Hello,
vStream use TMDB, but you can use informations from IMDB by installing other addon.
Then you must use the Informations menu from Kodi, not the vStream one.

**Comment by Gregh1969** [comment]
Or just tell me how to make trailers play from the information tab. I've tried everything I can think of

**Comment by sizanic** [comment]
If you don't activate the extended info dialog or the skin dialog, then the vStream dialog will bu use.

![image](https://user-images.githubusercontent.com/47307622/145570409-8e5c05da-c1c0-4443-86b3-3a9698cd6bd2.png)


.


So, the information dialog provide the trailer button:

![image](https://user-images.githubusercontent.com/47307622/145570608-4776a181-35a0-440b-a7af-ba975f2d037d.png)


![image](https://user-images.githubusercontent.com/47307622/145570908-5605bde5-96e9-4843-a5af-3bdf1332b374.png)

**Comment by Gregh1969** [comment]
SOLVED. it wasn't a Venom issue after all. I had to disable "support alternative players" in YouTube advanced settings. I appreciate your time in trying to help me. Thanks!
