### ISSUE TITLE
source 01streaming ne fonctionne plus

### ISSUE THREAD

**Issue by donguiza** [Kodi-vStream/venom-xbmc-addons#3421]
**Décrivez le bug**

salut , la source 01streaming etait toujours tres stable jusqu'à aujourd hui  , elle n affiche aucun cotenu

**Comment by TmpName** [comment]
Tu peux essayer la version a jour, par contre tu vas perdre les descriptions pour les series.

**Comment by donguiza** [comment]
ok merci pour la mise a jour rapide

**Comment by TmpName** [comment]
Si ca marche, tu peux clore l'issue stp.

**Comment by donguiza** [comment]
ca a marchait pour une journée après les liens sont disparus a nouveau :(

**Comment by donguiza** [comment]
oui ,merci ca marche bien , sauf que depuis la maj l enchainement des épisodes de cette source ne fonctionnent plus avec UPNext

**Comment by razorex** [comment]
Donc plus le même problème ==> close

**Comment by TmpName** [comment]
Ha merde ca c'est peut etre ma faute, j'ai aussi viré la description pour aller plus vite (Viens juste d'etre remit par @razorex )

**Comment by donguiza** [comment]
@TmpName  Malheureusement les liens sont a nouveau disparus même avec la mise a jour de @razorex

**Comment by TmpName** [comment]
Nouvelle version en ligne.

**Comment by razorex** [comment]
Oupps dsl @TmpName

**Comment by donguiza** [comment]
@TmpName @razorex  merci enormement pour votre effort mais je comprends pas pourquoi après cette mise a jours l enchainement des épisodes avec l extension UpNext ne fonctionne plus

**Comment by yodidon** [comment]
> 

As tu vérifier dans tes réglages de vstream ?

**Comment by donguiza** [comment]
@yodidon oui malheureusement l enchainement des épisodes se déclenche sans probleme avec la même série sur le meme hebergeur mais sur un autre site et ne se déclenche pas avec le site 01streaming et cela apres la dernière mise a jour du fichier o1streaming
