### ISSUE TITLE
streamonsport n'affiche plus les liens

### ISSUE THREAD

**Issue by chamtec** [Kodi-vStream/venom-xbmc-addons#3422]
Bonjour,

**Décrivez le bug**
Pour le site streamonsport les genres et la liste des matches sont bien affichés.
Par contre quand on clique sur un match il y a plusieurs liens mais ils sont tous vide.
Il n'y a pas de lien final qui va exécuter la vidéo mais "no information" en rouge

**Votre system**
 - OS: Windows, 
 - Appareil: PC
 - Version Kodi:  19.3
 - Version Vstream: 1.6.0 
 J'ai également testé avec la branche BETA au 04/12/2021 vu que le fichier streamonsport avait bougé après la release 1.6.0

Merci,
Chamtec

**Comment by sizanic** [comment]
Bonjour,

Les sources de vStream sont des sites que l'on trouve sur internet.

Le site ChannelStream ne propose plus de liens, vStream n'y peut rien.


https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3413

**Comment by chamtec** [comment]
Je n'ai peut être pas était clair.
Les live sont bien présent sur le site internet https://www.streamonsport.to/3940-regarder-bordeaux-begles-stade-toulousain-en-streaming-rugby.html par exemple. Avec plusieurs liens vidéos fonctionnels.

**Comment by sizanic** [comment]
Désolé, j'ai lu trop vite,
je pensais que tu parlais de ChannelStream alors que tu fais référence à Streamonsport.

On va regarder.

**Comment by Damartire** [comment]
Hello !

J'ai exactement le même problème que l'auteur depuis 1 semaine environ. Sur tous les liens Streamonsport il y a d'inscrit "aucune information" en rouge...

Je suis sur une Android TV, Kodi 19.3 et vStream dernière version.

**Comment by sizanic** [comment]
Salut.

Depuis une semaine nous n'avons pas sortie de version avec la correction 😄

Merci pour l'info.
On n'a pas eu le temps de regarder le problème.

**Comment by Whitebread40** [comment]
Bonjour, je confirme aussi de mon coté sur tous les liens Streamonsport il y a inscrit "aucune information" en rouge...je suis aussi sur une shield Android TV, Kodi 19.3 et vStream dernière version 1.6.0, ( même chose aussi pour les liens Live TV ) ....
plus de sources sport valide - merci pour le debug si vous trouvez la cause !

**Comment by babeejen** [comment]
Bonjour 
Idem ici impossible, continuellement le lien rouge "aucune information".

**Comment by sizanic** [comment]
Bonjour,

Merci pour vos retours.
Nous traiterons ce souci dès que possible.
Nous n'avons plus besoin de vos retours pour le moment.

Merci à toute notre communauté, que nous apprécions grandement, de ne pas tous venir nous rappeler que les liens ne sont pas fonctionnels 😆 

On vous tiendra au courant dès que ça bouge.

**Comment by Boomludo** [comment]
J'ai le même problème mais sur l'ensemble de vstream, impossible de regarder quoi que ce soit

**Comment by sizanic** [comment]
Dans ce cas, s'il ne s'agit pas d'un probleme spécifique avec Streamonsport, c'est un autre sujet.
Je te propose d'ouvrir un autre sujet, et de détailler ton probleme.

**Comment by Boomludo** [comment]
Ok merci

**Comment by Antoine-H** [comment]
Bonjour,

J'ai moi aussi le lien rouge "aucune information". Je suis sur LibreELEC 10.

Je vois une erreur dans les logs. Cette erreur apparait à chaque fois que je clique sur un menu, uniquement dans vstream :
```
Dec 17 22:07:26 TVSalon kodi.sh[1019]: Exception ignored in: <generator object path at 0xc8a651b8>
Dec 17 22:07:26 TVSalon kodi.sh[1019]: Traceback (most recent call last):
Dec 17 22:07:26 TVSalon kodi.sh[1019]:   File "/usr/lib/python3.8/importlib/resources.py", line 190, in path
Dec 17 22:07:26 TVSalon kodi.sh[1019]: NameError: name 'FileNotFoundError' is not defined
```

Je ne sais pas si c'est lié, mais j'ai les mêmes symptomes.

**Comment by sizanic** [comment]
Je ne sais si c'est lié mais si ça n'a rien a voir avec Streamonsport, merci de vous reporter à ma dernière réponse.

**Comment by sizanic** [comment]
Les corrections sur StreamOnSport sont apportées.

Plus qu'à attendre la prochaine version ...

**Comment by babeejen** [comment]
Super merci beaucoup 
A-t-on une idée du délais pour la maj de la prochaine version ? (Désolée si ma question est idiote)

**Comment by sizanic** [comment]
Bonjour,
Ta question n'est pas idiote, il est normal de se demander quand la prochaine mise à jour arrive car il n'y pas de règle.
On essaie normalement de proposer une maj par mois, mais cela fait maintenant 2 mois 😢 

Justement, le sujet a été soulevé hier entre développeurs et je t'annonce que la décision de sortir une mise à jour a été prise, donc elle ne devrait pas tarder.

**Comment by sizanic** [comment]
La mise à jour proposera les liens streamonsport et également le retour des liens ChannelStream.

#3413

**Comment by babeejen** [comment]
Merci beaucoup pour ta réponse rapide 🙏 et aussi pour votre travail ^^ 
Passez de Bonnes Fêtes !!

**Comment by jackG71** [comment]
Merci à vous ! Je suivais ce lien pour des problèmes identiques ! Bonnes fêtes de fin d’année à vous 

Envoyé de mon iPhone

**Comment by jackG71** [comment]
Bonjour j'ai à nouveau un problème avec streamonsport il n'affiche plus aucun lien depuis quelques jours ! Auriez vous des informations concernant un bug ? Merci cordialement

**Comment by sizanic** [comment]
Bonjour,

ce n'est pas un bug mais le site a changé d'adresse.

Nous avons apporté la modification nécessaire qui sera disponible dans la prochaine version.
(https://github.com/Kodi-vStream/venom-xbmc-addons/pull/3463)

**Comment by jackG71** [comment]
Entendu merci pour votre réponse !

**Comment by sizanic** [comment]
Le site Streamonsport change constamment d'adresse.
Nous avons apportés les modifications nécessaire pour suivre plus rapidement les changements d'adresses.

Cette évolution sera disponible dans la prochaine version ....

**Comment by Whitebread40** [comment]
Merci en tout cas pour le support en continu, on attendra la prochaine version !

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : sizanic ***@***.***>
Envoyé : Saturday, April 2, 2022 2:28:58 AM
À : Kodi-vStream/venom-xbmc-addons ***@***.***>
Cc : Whitebread40 ***@***.***>; Comment ***@***.***>
Objet : Re: [Kodi-vStream/venom-xbmc-addons] streamonsport n'affiche plus les liens (Issue #3422)


Le site Streamonsport change constamment d'adresse.
Nous avons apportés les modifications nécessaire pour suivre plus rapidement les changements d'adresses.

Cette évolution sera disponible dans la prochaine version ....

**Comment by sizanic** [comment]
Cette prochaine version est sortie il y a déjà une semaine 😆

**Comment by klig1** [comment]
Problème toujours pour la section streamonsport avec le message 'no information'. Y'a t il une maj de prévue pour fixer le problème ? Merci

**Comment by sizanic** [comment]
C'est corrigé.
La correction sera effective rapidement (entre 1 et 3 jours) sans nécessité de mise à jour.

En attendant, il y a la nouvelle source Leet365 qui est très intéressante.

**Comment by Whitebread40** [comment]
Merci encore pour la nouvelle source et les corrections streamonsport. Tout fonctionne !!

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : sizanic ***@***.***>
Envoyé : Sunday, May 1, 2022 1:00:33 AM
À : Kodi-vStream/venom-xbmc-addons ***@***.***>
Cc : Whitebread40 ***@***.***>; Comment ***@***.***>
Objet : Re: [Kodi-vStream/venom-xbmc-addons] streamonsport n'affiche plus les liens (Issue #3422)


C'est corrigé.
La correction sera effective rapidement (entre 1 et 3 jours) sans nécessité de mise à jour.

En attendant, il y a la nouvelle source Leet365 qui est très intéressante.

**Comment by babeejen** [comment]
Bonjour,
Je suis desolee de réouvrir la discussion mais je n'ai pas trouvé la réponse ailleurs (s'il elle existe n'hésitez pas à m'aiguiller)
STREAMONSPORT à changé d'adresse, du coup je n'y ai plus accès via vstream sur kodi.
Ma question est, y a t il un moyen d'y arriver ou plus du tout ?
J'utilise kodi via le fire stick Amazon, et j'ai la version 20.2 de kodi avec la version 2.6.3 de vstream
Encore merci et désolée si je ne suis pas au bon endroit

**Comment by TmpName** [comment]
Alors je n'utilise jamais ce site, mais c'et juste un changement d'adresse, tu peux la corriger dans le fichier resources/sites.json.
Et si ca marche proposer le changement.

**Comment by sizanic** [comment]
Bonjour,

Nous venons de mettre la nouvelle adresse.
Elle devrait arriver chez toi d'ici quelques heures.

**Comment by sizanic** [comment]
Malheureusement pour toi, nous devons effectuer des ajustements.
Il te faudra donc attendre une mise à jour pour profiter de cette source.

**Comment by babeejen** [comment]
Je vous remercie pour vos retours et tout ce que vous mettez en place...
Je vais donc attendre la mise à jour, savez-vous à peu près à quel moment elle sera disponible ?
En vous remerciant encore

**Comment by sizanic** [comment]
@babeejen 
J'aurais du dire d'ici quelques heures 😄 

La mise à jour  2.6.4 est disponible, avec l'accès aux liens de streamonsport.

(elle s'installe toute seule en quelques heures)

**Comment by babeejen** [comment]
Ahhhh vous êtes au top merci bcp !!!
