### ISSUE TITLE
Bug no information 

### ISSUE THREAD

**Issue by Boomludo** [Kodi-vStream/venom-xbmc-addons#3423]
**Décrivez le bug**
Aucun lien dspo dans toutes les catégorie, à chaque fois il y a marqué pas d'informations 

**Votre system**
 - Android tv 
-  Appareil fire stick 
 - Version Kodi  19.3
- Version Vstream 1.6.0

**Comment by sizanic** [comment]
Bonjour,
c'est un peu court.

Quelles catégories ?
Peux-tu donner un exemple de menu pour te rendre jusqu'au liens ?

Peux-tu essayer ce lien de la source ZuStream : 
vStream / source /zuStream / Films(Derniers ajouts) / Rose / Rose # 1 / Rose streamtape.

**Comment by Boomludo** [comment]
ça me le fait dans tous les menus, que ce soit dans series, films ou sports. 

je viens d'essayer ce que tu m'as dis ça m'a mis le message d'erreur no informations au moment d'aller dans dernier ajouts

**Comment by sizanic** [comment]
Tu es sans doute bloqué par ton opérateur internet.

Essaie de changer le dns.
https://fr.techtribune.net/securite/vpn/comment-changer-le-dns-sur-la-cle-fire-tv/140037/

Voici le dns à mettre : 
dns1 : 8.8.8.8
dns2 : 8.8.4.4

ne t'occupe pas de la partie VPN, tu n'as pas besoin de vpn, cet article est une publicité déguisée pour vendre un VPN.
Mais tout le début est correct, avec les valeurs que je t'ai donnée.

**Comment by sizanic** [comment]
Quoi que tu ne devrais même pas voir les films si ton fournisseur te bloque 🤔 

Est-ce que tu n'aurais pas essayé de renseigner des identifiants d'un compte Hebergeur ou débrideurs ?

**Comment by Boomludo** [comment]
Ok merci, je ferai ça demain matin et je te dis, 
Non pas du tout, je ne sais même pas ce que  c'est

**Comment by Boomludo** [comment]
Je viens d'essayer, toujours le même problème sauf que je n'ai plus le message d'erreur DNS python mais au moment d'aller sur rose 1 ça marque no informations

**Comment by Boomludo** [comment]
J'ai réessayé ça me remarque dns python manquant au moment d'aller voir de film (ajouts récent)

**Comment by yas06** [comment]
[salut]
 j ai eu le même problème en installent depuis le repos il manque 2 dépendance Dns python et url résolveur
pour le Dns python voila le lien [https://github.com/Arias800/script.module.dnspython/releases/download/1.12.1/script.module.dnspython-1.12.1.zip](url)
tu l Install ca résous ton problème de Dns et pour ceux qui on un souci de résolveur voila le lien pour urlresolver
(https://fusion.tvaddons.co/kodi-scripts/script.module.urlresolver-7.0.00.zip)

**Comment by Boomludo** [comment]
Ok merci je test quand je rentre et je vous dis ce qu'il en est
