### ISSUE TITLE
Source Mangas de Qualité Pour Vstream !

### ISSUE THREAD

**Issue by Redaahba** [Kodi-vStream/venom-xbmc-addons#3425]
Bonjours la communauté, Je me permet de poster ce message car J’ai trouvé une source intéressante pour les manga en VF sur le site (zone-anime. me ). Avec des Lien Upvid Stable je voulais savoir si vous pouvez jeter un œil dessus car ses un très bon complément au Travail qui a déjà été réalisée par votre équipe un grand merci

**Comment by yodidon** [comment]
J’essaie de regarder ça ce soir

**Comment by Redaahba** [comment]
Merci de ta réactivité ✅

**Comment by yodidon** [comment]
Pour la récupération des saisons et épisodes , ça va mais en ce qui concerne les hoster, je crains que ça ne soit pas dans mes compétences

**Comment by Redaahba** [comment]
Merci encore d’avoir essayé c’est dommage le site est complet, mais Hier j’ai découvert la source pastbin et sa change tout 🔥

**Comment by sizanic** [comment]
@yodidon 
propose déjà ce que tu as, on va regarder pour les hosters.

@Redaahba 
Notre source Pastebin est bien sûr intéressante.
Mais nous ne voulons pas pour autant arreter les autres sources.
Donc toutes nouvelles propositions de sources est la bienvenue.
Nous allons continuer l'étude de cette source.
(que tu n'utiliseras pas finalement 😄 , as-tu bien récupéré les codes Shamir pour les mangas/pastebin ?)

**Comment by yodidon** [comment]
@sizanic ne nettoie la source et je la partage, je pense qu’il n’y aura qu’un menu « dernière ajout » à voir s’il faut aller plus loin

**Comment by sizanic** [comment]
en plus de la recherche, je mettrais aussi : 
- Films (Populaires) (c'est le menu "Box office")
- Films (Genres)

**Comment by Redaahba** [comment]
> 

Ouais J’ai les est toute ajouter , si je l’utiliserais avec plaisir, car avec la source pastbin ses long à charger et depuis ce matin Vstream veux pas se lancer

**Comment by Redaahba** [comment]
Vstream ses lancée , mais comment je pourrais accéléré la source pastbin j’ai mis toute les sources dans le même dossier sa peut jouer ?

**Comment by sizanic** [comment]
C'est long à charger si tu as ajouté tous les codes dans le même dossier 🤔 

Crée un dossier "japanime" avec seulement les codes Shamir.
- crée un dossier "films" avec seulement 5 codes (ne prends pas les codes 4k si tu n'as pas de tv 4k, etc.).
- Pareil pour "séries", 5 codes.
- un dossier "concerts/spectacle" si nécessaire
- un dossier "documentaires" si nécessaire.

Mettre tous les codes films dans le dossier Films te permet d'avoir 15 liens pour le même film.
Cela n'a aucun interet, car tous les liens de Pastebin fonctionnent (il ne faut pas penser comme les autres source de vStream).
Ne prend que les 5 codes de grans contributeurs, tu auras quand même plusieurs liens par films, te permettant de choisir la qualité.

**Comment by Redaahba** [comment]
@sizanic J’ai tout mis dans le même dossier hier s’était long à charger mais sa fonctionne quand même et aujourd’hui plus rien sa tourne en rond , ya pas une façon d’aller plus vite que de crée les dossiers et mettre les code 1 par 1 ?

**Comment by sizanic** [comment]
comme tes codes sont déjà saisis,
si tu crée des nouveaux dossiers vides, 
ensuite, avec de GRANDES PRECAUTIONS, tu peux essayer de déplacer les codes en modifiant le fichier settings de vStream.
(a faire sur PC puis à déplacer sur ta box)

A savoir également : il y a un cache qui permet de ne pas télécharger la liste des contenus à chaque fois que tu navigues dans les dossiers pastebin.

Ce cache se vide toutes les 12 heures.
Donc tu ressentira un ralentissement à cette fréquence.

Il y a un paramètre dans le fichier settings pour augmenter cette valeur (pastebin_cacheDuration)
Je met personnellement la valeur 144 (soit 6 jours). Je n'ai pas besoin d'avoir plus fréquemment une liste à jour avec des nouveautés sorties la veille.


Voila tout ce que je peux te dire à propos de l'optimisation du chargement de pastebin.
Si tu veux en savoir plus, je te propose de t'informer sur le Discord officiel de la source Pastebin : https://discord.com/invite/Q8PEWuN

(c'est bien à cette adresse que tu as récupéré les codes ? )

**Comment by Redaahba** [comment]
Oui c’est bien à cette à adresse que j’ai pu avoir les codes , ses sans doute sa , J’ai tout recommencer à 0 , j’arrive pas à accéder au ficher de Kodi sur mon pc avec la télécommande sa veut pas faire de copier coller

**Comment by sizanic** [comment]
Pour des questions autour de pastebin, tu dois voir sur Discord.

Pour déplacer des fichiers d'un pc vers une box, ou tout autre manipulation avec Kodi, je te conseille ce bon groupe facebook : 
Les alKODIques.

**Comment by yodidon** [comment]
> en plus de la recherche, je mettrais aussi :
> 
> * Films (Populaires) (c'est le menu "Box office")
> * Films (Genres)

Je me demande s’il faut aller si loins, je sais pas si la résolution des hoster est faisable

**Comment by sizanic** [comment]
J'ai regardé et en effet, la résolution des hosters me fait peur.

Il me semble qu'il faut gérer des cookies, et ça je ne maitrise pas.

**Comment by TmpName** [comment]
Ben je crois que j'ai une mauvaise nouvelle, je pense qu'il y a du recpatcha.
Le site ne marche plus si on bloque ww w.gstatic.com

**Comment by razorex** [comment]
Alors on close ???????
