### ISSUE TITLE
importlib not found

### ISSUE THREAD

**Issue by Antoine-H** [Kodi-vStream/venom-xbmc-addons#3426]
Bonjour,

Quand je navigue dans les menus, je finis pas voir un lien rouge où il est écrit "aucune information" là où je suis censé pouvoir lancer une vidéo. Je suis sur LibreELEC 10.0.0, Kodi 19.1, Vstream 1.6.0.

Je vois une erreur dans les logs. Cette erreur apparait à chaque fois que je clique sur un menu, uniquement dans vstream :
```
Dec 17 22:07:26 TVSalon kodi.sh[1019]: Exception ignored in: <generator object path at 0xc8a651b8>
Dec 17 22:07:26 TVSalon kodi.sh[1019]: Traceback (most recent call last):
Dec 17 22:07:26 TVSalon kodi.sh[1019]:   File "/usr/lib/python3.8/importlib/resources.py", line 190, in path
Dec 17 22:07:26 TVSalon kodi.sh[1019]: NameError: name 'FileNotFoundError' is not defined
```

**Comment by sizanic** [comment]
Bonjour,

Il y a beaucoup de menu qui affichent "aucune information" même lorsque tout va bien.
Il n'y a aucune garantie qu'il y ai des liens partout.


-> Donnes nous un exemple.

Et je te propose de glisser le fichier de log complet dans ton message, il sera associé comme pièce jointe.
