### ISSUE TITLE
Impossible de regarder un film avec un lien Uptobox PREMIUM

### ISSUE THREAD

**Issue by Pistacheeeeee** [Kodi-vStream/venom-xbmc-addons#3428]
Bonjour,
Alors voilà j'ai installé vstream sur kodi et puis j'ai rentré mon compte uptobox PREMIUM. J'ai donc accès à mes fichiers et à leurs streaming sans problème or quand je recherche un film sur tous les sites et que je choisis par exmple Wawacity puis je choisis un film et avec comme lien "Nom du film qualité langue - **Uptobox**" et bien j'ai un chargement infini puis rien ou un captcha qui même si on le résout bien il nous renmène à la page avec les différents hébergeurs et ceux avec n'importe quel site ! Voilà si quelqu'un peut m'aider et me dire si il est possible de lire un film rechercher et le lire avec le lien direct uptobox sans devoir ajouter le lien à mon compte uptobox premium je suis preneur.

**Comment by sizanic** [comment]
Bonjour,
Si tu as un compte Uptobox, je te propose de te tourner vers la source Pastebin.

Elle donne accès à du contenu hébergé sur Uptobox par de nombreux Contributeurs (d'autres utilisateurs de vStream).
Les contenus sont partagés grâce à des codes qu'il faut saisir depuis la source Pastebin.
Tu peux retrouver les codes dans ce Discord : 
https://discord.gg/Q8PEWuN

Il y a tellement de contenu que c'est à la carte.
Tu dois choisir les codes en fonction du contenu qui t'interesse :
films/séries/doc/concerts/japanimes/spectacles/sports/...

**Comment by sizanic** [comment]
Je laisse ce ticket ouvert, cela pourrait intéresser d'autres personnes.
