### ISSUE TITLE
Affichage captcha

### ISSUE THREAD

**Issue by detobel36** [Kodi-vStream/venom-xbmc-addons#3433]
## Décrivez le bug
Le background noir permettant de voir quelle image du captcha est sélectionné, ne s'affiche pas bien sur le thème "Xperience1080".

## Votre system
- **OS:** Linux (ZorinOS (basé sur Ubuntu))
- **Appareil:** PC portable
- **Version Kodi:** 19.3 
- **Version Vstream:** BETA

## Nous devons le reproduire
Pour cela il nous faut:
- Installer Xperience1080 (ici: https://github.com/luizoti/skin.xperience1080 )
- Chercher un film sur un site qui a un captcha (par exemple "Extreme Down") 
- Sélectionner n'importe quel film à voir

## Log
Je pense pas que c'est utile vu que c'est visuel :wink:

## Image
**Erreur:**   
![capt](https://user-images.githubusercontent.com/5373615/147345553-329f25e9-d935-4fc0-a082-97ee3550615a.png)

**Affichage correct:**   
![captGood](https://user-images.githubusercontent.com/5373615/147345584-942f92c7-8617-487e-af53-b63c7f1d9323.png)

## Plus
Je pense que c'est simplement un problème de calque/couleur.  Mais comme je me suis pas encore plongé dans le code, j'ouvrir l'issue pour voir si quelqu'un à déjà eu le bug et à la solution...

**Comment by TmpName** [comment]
Oui, deja eu le bug, Aria aussi, mais jamais trouvé comment contourner le truc.
