### ISSUE TITLE
Bonne pratique pour importer urlparse

### ISSUE THREAD

**Issue by detobel36** [Kodi-vStream/venom-xbmc-addons#3435]
Pour importer `urlparse`, il y a deux écoles:   
- Se baser sur la version de Kodi (pas très "robuste" dans le temps):
  https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/player.py#L13
- Faire un try except:
  https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/cloudflare.py#L15

Il faudrait "uniformiser" tout ça histoire d'être cohérent :wink:

**Comment by TmpName** [comment]
Je vote pour la seconde.
