### ISSUE TITLE
Historique visionnage et remerciements

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#3437]
Salut à tous,
Déjà je voudrais dire que ça fait des années que je vous suis et que je vois vstream évoluer et devenir incontournable.
C'est pas vraiment une lettre d'amour mais c'est tout comme, parce que grâce à vous ma vie est moins moche loll, j'ai pas une vie facile mais je préfère éviter d'en parler.
Mais tout ça pour dire que vstream a souvent été là dans les mauvais moments pour penser à autre chose et beaucoup de gens j'ai pas les moyens de me payer autant d'abonnement pour avoir accès à des choses que j'aime ou qui m'intéresse.
Alors je voulais remercier toute la team de vstream et ceux qui contribue à son évolution.
Vous êtes toujours dispo pour chaque demande et très patient alors merci à vous.

Maintenant je commence ma demande.
J'ai déjà demandé pas mal de chose et vous l'avez fait.
- Le fait d'avoir le "en cours de visionnage".
- Les miniatures sur les séries et les résumés des épisodes
- le fait d'avoir les notes IMDb et autres
Bref, j'ai demandé tellement de choses que j'ai fini par oublié loll

Là j'aimerais vous demander l'ajout de l'historique de visionnage.
Ça serait comme "En cours de visionnage" mais on aurait la liste de ce qu'on a regarder, parce que souvent ça m'arrive de regarder une chose le soir et je m'endors et le lendemain j'oublie le titre ou la source ou j'ai vue.
Bref, j'imagine aussi que ça serait bien si l'historique est trié par date, on pourrait voir la date et les liens.

C'est à vous de me dire si c'est intéressant ou pas, merci et désolé pour la longueur du texte.

**Comment by sizanic** [comment]
Salut lebigboss,

Pour commencer, tes remerciements nous vont droit au coeur.
C'est ce genre de retours qui nous permettent de rester motivé.
(Alors que de mauvais retours comme on subit il y a quelques jours auraient pu nous démotiver)

Concernant ta demande, je ne trouve pas cette fonctionnalité d'un grand intérêt.
Mais comme Netflix le propose (dans sa section "Regarder de nouveau"), je me trompe peut-être 🤔 


On note ta demande dans notre liste des bonnes idées ...

**Comment by razorex** [comment]
Bonsoir lebigboss,
Avec "en cours de visionnage" il t'est encore possible de mettre en "marque page" voir même en favoris (kodi).
Donc beaucoup d'options pour te faire plaisir et profité de vStream.

**Comment by alKODIque** [comment]
Je vais dans le sens de @lebigboss , je crois égalementr que un dossier ''Vu récemment'' serait pratique... 
Oui, Il y a bien Netflix qui l'offre et il y en a d'autre aussi... Mais pour demeurer dans l'usage Kodi, même kodi offre en Natif ce dossier dans sa médiathèque locale.  Tout comme TMDb Helper, Embuary info Ainsi que Trakt (Trakt utilise nos dernioers visionnages afin de créer nos listes de recommandations personnalisées)

C'est utile dans le cas mentionné par lebigboss mais aussi lorsque l'on souhaite proposer un film a une autre personne que nous avons vu et dont on oublie le titre ;)  Bref, je me suis surprise a bien apprécier ce dossier en mode médiathèque locale.

Alors Joyeuses fêtes de fin d'année a tous et j'appuie tous les beaux mots de lebigboss :))

**Comment by sizanic** [comment]
En cours de visionnage n'est pas une solution au probleme du bigboss.

Car le bigboss s'endort et le film se joue jusqu'au bout, donc on ne retrouve pas le film dans les "en cours".
Bien sûr, la solution de mettre le film en marque-pages avant de le commencer est possible, mais cela est quand même contraignant. Car dans le cas où on a bien regardé le film en entier, il faut ensuite retirer le marque-page qui n'aura servi à rien.


Je reste quand même perplexe sur l'utilité d'une fonctionnalité qui nous rappele ce qu'on a déjà vu. Il est rare de vouloir revoir ce qu'on à déjà vu très rapidement.
A part dans le cas où on s'endort et que, en plus, on ne se rappelle plus ce qu'on avait commencé à regarder.
Cas possible mais très rare, cela nécessite-t-il vraiment une évolution 🤔 

(je poste ce message sans avoir lu la réponse de alko qui est arrivé entre temps ...)

**Comment by sizanic** [comment]
Les arguments de @alKODIque sont recevables 👍🏻

**Comment by detobel36** [comment]
Petite question en lien avec ça...    
Est-ce que les autres addon (on a évoqué Track, TMDBHelper, ...) prennent en compte le fait qu'on ai vu un film via vStream ?    
Si oui, je ne suis pas sûr que cette fonctionnalité d'"histoirque" soit nécessaire.     
Si non, est-ce quelqu'un à de la doc (technique) pour mettre ça en place (je me pencherais bien sur la question...)

**Comment by alKODIque** [comment]
Théoriquement, oui... grâce a Trakt.

Il est nécessaire de posséder un compte trakt.tv afin de pouvoir utiliser cette fonctionnalité.  Le problème est que même si vStream offre d'inclure notre compte perso a l'addon, l'intégration ne fonctionne pas bien dutout depuis un bon moment...  Nous avons accèes a nos listes perso, mais la synchronisation ne se fait plus vraiment sans problème.  Parfois nous avons l'historique, parfois non... 

D'ailleurs, il y a un fil de discussion dans les issues sur le sujet ici: https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3381

**Comment by lebigboss** [comment]
Oui ça ne fonctionne plus vraiment l'historique TRAKT pour les films, ça fonctionne toujours pour les séries.

Mais pour moi, voir l'historique serait intéressant si on a le même système que " en cours de visionnage", c'est à dire d'avoir l'historique avec les liens pour pouvoir visionner.

**Comment by sizanic** [comment]
> Mais pour moi, voir l'historique serait intéressant si on a le même système que " en cours de visionnage", c'est à dire d'avoir l'historique avec les liens pour pouvoir visionner.

@lebigboss 
"En cours de visionnage" est maintenant disponible en version 2.5.0.

Fallait pas perdre espoir après un an et demi 😅

**Comment by lebigboss59** [comment]
Merci beaucoup ça fonctionne nickel
