### ISSUE TITLE
2022

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3440]
https://user-images.githubusercontent.com/31409100/147830431-90effab4-5f7b-4c2d-9660-e23e6c99819a.mp4

Que l'aventure continue...
Un grand merci.

C.

**Comment by sizanic** [comment]
Merci Christian 💟 

On te souhaite aussi une BONNE ANNÉE !!

**Comment by yodidon** [comment]
Top 👍

**Comment by kris06** [comment]
merci  (le preview  ici ne permet pas d'entendre cette vidéo.. pourquoi ? )

**Comment by sizanic** [comment]
Je pensais que c'était exprès, que tu n'avais pas mis de son 😄 

Sans doute que le codec audio AC3 n'est pas supporté en preview, en changeant de d'encodage peut-être 🤔

**Comment by kris06** [comment]
https://user-images.githubusercontent.com/31409100/147830385-08fd1884-92b1-43e5-b0a6-1f52079b6a47.mp4

en effet voila la version sonore

**Comment by kris06** [comment]
Et si cela vous tente de glisser ici cette nouvelle version ci jointe cette fois en votre nom, dans les sources pour la période de janvier
n'hésitez pas. Je vous joins également la  jaquette que j'ai crée pour la source...

https://user-images.githubusercontent.com/31409100/147831224-3bfdffc3-2f4e-416a-bcd0-0a1dfb21c59f.mp4

![2022](https://user-images.githubusercontent.com/31409100/147831262-3f615289-a84e-45ff-800f-1d8959f15589.jpg)

**Comment by sizanic** [comment]
> Et si cela vous tente de glisser ici cette nouvelle version ci jointe cette fois en votre nom, dans les sources pour la période de janvier,  n'hésitez pas. Je vous joins également la jaquette que j'ai crée pour la source...

Nous l'aurions bien fait, mais vStream ne propose pas de contenu. Donc nous n'avons aucun menu pour proposer cette vidéo.

Encore merci pour ton soutien.
