### ISSUE TITLE
mise à jour 1.7.0

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3446]
Bonjour et tous mes vœux, j'avais déjà signalé ce problème et  j'attendais la mise à jour pour le vérifier encore
Nous sommes plusieurs à etre équipé  de  la petite clé Chromecast de google  (Google TV)   voir photo jointe

Malheureusement la mise à jour ne nous parvient pas malgré l'onglet de vStream coché "mettre à jour automatiquement" 
et malgré la dépendance  VStream repository 0.0.5 à jour

Il nous faut pratiquer cette mise à jour manuellement alors que vous nous adressez une mise à jour automatique majeur...
(d'ailleurs en ouvrant VStream il s'affiche  comme à l'ancienne   "mise à jour 1.7.0 disponible (en vert)

**Votre system**
 -  Android tv
-  Appareil [GOOGLE TV ]
![téléchargement](https://user-images.githubusercontent.com/31409100/147852052-98f18bd1-fe65-4578-8cac-a02fe1929d46.jpg)

 - Version Kodi  18.3
- Version VStream 1.0.7

*

**Comment by sizanic** [comment]
Bonjour,

ce que tu décris, je l'ai vu sur d'autres équipements, des box de tout genres.
La solution est qu'il faut juste attendre ...
Parfois jusqu'à 48h.

c'est kodi qui s'occupe de télécharger les mises à jours lorsque nous les mettons à disposition, ce n'est plus de notre ressort.

**Comment by Mokoman30** [comment]
Moi j ai un problème le DNS python 1.12.2 fais une maj fail 

sinon sur l un des 2 Kodi 
J ai réussi à mettre à jour la 1.7.0 sur l autre non 
je dispose d un Android Tv 
Et d une box android 
Sous Matrix 19.3

**Comment by kris06** [comment]
Salut sizanic, je reviens ici sur la m.a.j. auto et pour répondre à ton message  , en effet, cette m.a.j. arrive bien, quelque fois plus tard, mais là en l'occurrence, en ce qui concerne ce matériel (google tv)  elle ne s'installe pas comme habituellement sur les autres appareils, une manipulation manuelle est nécessaire ce qui me renvoie à penser qu'il s'agit d'un problème vStream ou de dépendance  VStream repository et non de Kodi.  

j'ai refais un test en revenant à la version 1.6.0 et je constate encore cette anomalie.

**Comment by sizanic** [comment]
Et concernant les autres extensions, se mettent-elles bien à jour toutes seules ?

**Comment by kris06** [comment]
oui sans difficulté

**Comment by arzaz** [comment]
Même problème sur Shield TV, je suis toujours sur la version 1.7.0
J'ai essayé d'installer manuellement la nouvelle version 1.8.0 mais sans succès !!!!!

**Comment by sizanic** [comment]
Les symptômes me font penser à ce scénario : 

Si une version de vStream a été installée manuellement, depuis zip (le zip de la Beta par exemple).
Alors dans ce cas, les mises à jour automatiques peuvent bloquer.


Dans tous les cas, nous n'avons pas de pistes pour une correction dans nos fichiers ....

**Comment by sizanic** [comment]
Pas de pistes de solutions.
Et il existe la solution manuelle.
Je clos cette demande.
