### ISSUE TITLE
Flaresolverr 

### ISSUE THREAD

**Issue by untiiis** [Kodi-vStream/venom-xbmc-addons#3448]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.

**Votre system**
 - OS: [Android tv]
-  Appareil [mi box]
 - Version Kodi  [18.9]
- Version Vstream : 1.7

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : french stream lol 
- Le titre du fim/serie 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Ajoutez plus d'information sur le problème ici.

Bonjour,
Je ne sais pas si c'est un bug ou autre chose, j'ai deux question
La première, après la mise à jour de vstream, le dns python ne se met pas à jour, je pense que c'est lié à kodi 18.9 ? Il n'est pas compatible

La 2ème qui me préoccupe, le site french-stream-lol n'est plus accessible (et dire que c'est l'une des page qui proposait le plus de lien valides)
C'est dit que : page protégé par cloudflare, exécuter flaresolverr

Il y a t il moyen de contourner cela sur Android ou c'est impossible

Merci 😊

**Comment by kris06** [comment]
essaie l'appli SmartDNS Client    elle est gratuite, pratique, rapide,  (cependant quelque difficultés de navigations sous Android tv) 

https://play.google.com/store/apps/details?id=icapurro.org.dnschanger&hl=fr&gl=US

**Comment by untiiis** [comment]
@kris06
J'ai tout essayé, changer le dns manuellement ou même tester l'appli 1.1.1.1 et d'autres appli, ça ne fonctionne pas
Je pense que c'est lié au site lui-même, sur Android, on ne peut contourner le cloudflare

**Comment by shkope** [comment]
Pareil du jour au lendemain la source french-stream-lol est protégé par cloudfare ☹️☹️

**Comment by kris06** [comment]
essaie l'appli que je te recommande, elle fonctionne bien et  french Stream  est accessible via tous les opérateurs orange Bouygues etc..

**Comment by untiiis** [comment]
@kris06
Ça ne fonctionne pas, je l'avais testé sur la boxandroid, et je parle de la source french-stream-lol et non french-stream
Ce n'est pas une question de vpn ou dns, vstream inclus un dns python qui change de dns pour accéder à des site, 
C'est le site lui-même qui est protégé

**Comment by yodidon** [comment]
Peut être une solution pour french s—tre-eam-lol j e test et vois

**Comment by untiiis** [comment]
Le site a l'air de refonctionner

**Comment by yodidon** [comment]
La modif sera sur la prochaine mise à jour
