### ISSUE TITLE
Trakt: Connection impossible

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3449]
Bonjour :)

Depuis la nouvelle version vStream, il est devenu impossible de se connecter a notre compte Trakt.

Voici mon log ou on peut constater l'erreur a partir de la ligne 1505:
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7799505/kodi.log)

Merci et une belle année a vous!

vStream v1.7
Kodi v19.3
nVidia shield

**Comment by TmpName** [comment]
Meilleurs voeux :)

>AttributeError: 'cTrakt' object has no attribute 'getToken()'

Alors la c'est bizarre, je la voit bien pourtant dans le fichier. Et evidement pas de soucis de mon coté, tu n'as pas touche aux fichiers ?

**Comment by alKODIque** [comment]
Non, c'est un fresh install de la v1.7 vStream
Et J'ai véréfié car des gens m'ont notifié avoir eu le problème... J'ai reproduit pour vérifier et voilàa: meme chose. Impossible de me connecter a mon compte

**Comment by sizanic** [comment]
J'ai un doute sur l'existence des parenthèse ici, dans getToken() :

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/edcd6bee6d0a94a79f62b3ad5d7a54ab8c1b26c2/plugin.video.vstream/resources/lib/trakt.py#L99

@alKODIque 
Si tu peux essayer de les enlever : 
```PYTHON
            oGui.addDir(SITE_IDENTIFIER, 'getToken', self.ADDON.VSlang(30305), 'trakt.png', oOutputParameterHandler)`
```

**Comment by sizanic** [comment]
mais tu passes dans ce code (qui ne fonctionne pas) alors qu'avant tu n'y passais pas car il y a ce log : 
[PLUGIN] vStream: bstoken invalid

**Comment by alKODIque** [comment]
Dac! Merci...
J'ai bien suivi maslgré tout loll
Je vous reviens après test :)

**Comment by alKODIque** [comment]
Bien vu!
Le fait de retirer les parenthèse a fonctionné 🎉

J'ai pu me connecté sans souci, Ca fonctionne a nouveau 👍
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7811505/kodi.log)

**Comment by sizanic** [comment]
ok, je mets la modif dans le code.
Merci pour ton test.
