### ISSUE TITLE
Site wrestlingnetwork  (Replays Sports de combats)

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#3452]
✋
![wrestling](https://user-images.githubusercontent.com/48101775/148414512-9a92af2a-84aa-4726-a7f5-51c2afe4963a.png)

Si interressé et que vous connaissiez pas, il y a aussi htt ps://wrestlingnetwork.in/ qui est un autre site des replays sports 🇺🇲 en FHD,HD etc... (Mma,WWE etc..).✅

**Comment by yodidon** [comment]
Ok je regarde si c’est intégrable

**Comment by yodidon** [comment]
faisable sur au moins un des hoster de mon coté

**Comment by sizanic** [comment]
Veut-on se diversifier vers ce genre de contenu ?

**Comment by yodidon** [comment]
> Veut-on se diversifier vers ce genre de contenu ?

Je ne crois pas, c’est beaucoup de suivi en plus

**Comment by sizanic** [comment]
Il serait préférable qu'on maintienne notre effort sur du streaming de films français.

**Comment by TmpName** [comment]
Je dirais pas mieux.

**Comment by sizanic** [comment]
Désolé @victore447 
On a voté.
Ce sera non pour l'instant 😆

**Comment by victore447** [comment]
✋
Y à pas de soucis de mon côté et comprend.
Si je tombe sur autres choses qui peut intéresser je vous en parle.
