### ISSUE TITLE
Page suivante dans les menus Trakt

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3453]
Bonjour a vous,

L'option ''Page suivante'' n'apparait plus dans les divers menus de notre compte Trakt. Résultat: il nous est possible de voir que les 10 premiers éléments de chaque menu.

EDIT: ce n'est pas ainsi partout... mais dans les menus des listes Trakt, c'est le cas

Merci de votre aide!
Kodi 19.3
nvidia shield
vstream 1.7 (beta - avec correctif donnant la possibilité de se connecter a trakt de nouveau :) )

**Comment by alKODIque** [comment]
bon..
je ne reproduis plus ce problème 🤯
je vois bien les pages suivantes maintenant

**Comment by ericlng** [comment]
Bonjour,
J’ai toujours ce problème de limitation à 10 items pour ma part sans page suivante. J’ai une mibox s, kodi 19.3 et vstream 1.7 avec le correctif pour trakt.
J’ai essayé de voir si le problème subsistait avec un install sur une autre plate forme. J’ai donc installé sur pc kodi 19.3, vstream 1.7 depuis le dépôt officiel et fait le lien avec trakt tv et… le problème est le même !
J’ai contacté le support de trakt tv pensant que la version free de trakt était limitatitve sur l’affichage mais ce n’est pas le cas d’après leur réponse.
Je ne vois plu trop où chercher la cause du problème.

**Comment by sizanic** [comment]
> bon.. je ne reproduis plus ce problème  je vois bien les pages suivantes maintenant

@alKODIque  Tu ne reproduis plus le problème avec la version Beta ? 

Il faudrait donc attendre la mise à jour de vStream pour profiter de la correction.

**Comment by alKODIque** [comment]
Je viens de refaire une vérification des menus trakt (avec la beta)...

En fait, j'ai le problème seulement au niveau des listes Trakt suivantes:
- Listes tendances
- Listes populaires
- Mes listes aimées.
Ces listes ne m'affichent que 10 entrées pas plus. Par contre, je vois bien toutes mes listes personnelles.

**Comment by ericlng** [comment]
Je n'ai pas pu constater dans mes listes personnelles, n'ayant qu'une seule liste avec 3 éléments 😉
Je vais tester quand même. En tout cas ce qui me rassure c'est que je ne sois pas le seul à rencontrer le problème !

**Comment by Arias800** [comment]
C'est corriger.
C'est normal que le problème n'apparaissaient que sur un nombre précis de liste, car la logique pour récupérer la page suivante des listes n'a pas la même pour chaque liste.

**Comment by alKODIque** [comment]
cool,
Merci @Arias800

**Comment by ericlng** [comment]
Je n'ai pas vu de changement pour ma part. Toujours 10 lignes sans bouton suivant. Ai je loupé quelque chose ? 🤔

**Comment by sizanic** [comment]
> Je n'ai pas vu de changement pour ma part. Toujours 10 lignes sans bouton suivant. Ai je loupé quelque chose ? 🤔

Avec la version modifiée en cours de développement ?

**Comment by sizanic** [comment]
> Je n'ai pas vu de changement pour ma part. Toujours 10 lignes sans bouton suivant. Ai je loupé quelque chose ? 🤔

Avec la version modifiée en cours de développement ?

C'est peut-être ça que tu as loupé, ce n'est pas dans la version officielle.

**Comment by ericlng** [comment]
On parle bien de cette version ? https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream
C'est celle que j'ai installée.

**Comment by sizanic** [comment]
oui, bien dans celle-ci, la version BETA (pas l'officielle).

Alors ça devrait être corrigé 🤔

**Comment by ericlng** [comment]
Alors je viens de voir qu'il me faut desinstaller l'ancienne version et réinstaller la nouvelle pour que cela fonctionne. Un install direct sur l'ancienne version ne marche pas. Ça fonctionne sur mes listes liked mais pas sur les listes tendance et populaire. J'avance 😊. En tout cas merci pour vos conseils.
