### ISSUE TITLE
Bloque la recherche à film streamingY

### ISSUE THREAD

**Issue by Choyoz** [Kodi-vStream/venom-xbmc-addons#3454]
**Décrivez le bug**
Une description claire et concise de ce qu'est le bug.
Bonjour, tout d'abord merci pour tout ! 
Lorsque l'on fait une recherche dans 
Search/Movie/
Arrivé a filmstreamingY la recherche bloque
**Votre system**
 - OS: [Windows, Android]
-  Appareil [firestick/pc]
 - Version Kodi   [19. 1]
- Version Vstream

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site: filmstreamingY
- Le titre du fim/serie recherche 
- Le nom du host (openload/vidzi)

**Log**
L’accès un votre fichier log seras un plus. Pour savoir comment uploader votre log voir:
https://kodi-vstream.github.io/docs/outils/

**Image**
Si votre soucis est visuel faite une capture d’écran.

**Plus**
Edit en cherchant un peu j'ai résolu le problème en désactivant la source dans settings/sources /enable disable source
 merci!! 
Ajoutez plus d'information sur le problème ici.

**Comment by TmpName** [comment]
Pareil, et je sais pas d'ou ca vient.
En passant par le site directement, rien ne marche (site HS) mais si on lance une recherche, ca freeze.

**Comment by kris06** [comment]
je m'adresse à TmpName et à ses collaborateurs , pourriez vous  techniquement améliorer cette recherche globale  ?  En effet,  il y a souvent des blocages interminables..  Même la fonction "annulation" "en cour de recherche ne fonctionne pas lorsqu'une la recherche est bloquée .. D'une manière générale, cette fonction "annulation" n'est pas très réactive
Merci à vous
C.

**Comment by sizanic** [comment]
Bonjour,

La fonction Annulation est prévue pour interrompre le cycle de la recherche globale, donc la recherche ne passera pas au site suivant dès que le site en cours aura répondu à notre demande.

Si le site interrogé met du temps à répondre, il est difficile de l'interrompre.
La réactivité de la fonction dépend donc du temps de réponse du site interrogé au moment où on l'active.

Sinon, nous avons bien en tête d'améliorer la recherche globale (en pertinence des résultats et temps de réponse).
Des développements sont en cours ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/pull/3447

**Comment by kris06** [comment]
En effet je savais qu'il y avait une nouvelle mouture en cours, j'ignorais qu'elle était aussi évoluée. Je n'avais pas vu la beta #3447
Hâte qu'elle soit en service..
merci pour votre travail

**Comment by TmpName** [comment]
Alors la c'est special ^^.
Quand c'est la recherche qui met du temps pour un probleme de serveur, il y a moyen de stopper. Mais la pour le coup le probleme est apres, c'est le regex qui n'est pas assez restrictif, et la par contre, la seule solution c'est Ctrl+Alt+Supp pr fermer kodi.

C'est corrigeable en modifiant le regex, mais le site etant HS, il suffira de supprimer le site si il ne revient pas dans quelques jours.

Ca ne change rien a ta remarque sur la recherche générale, mais la ca ne vient pas d'elle, tu peux tester directement sur le fichier site, meme probleme.

**Comment by TmpName** [comment]
Bon le site est de retour (avec quelques modifs)
Par contre j'aurais du faire un backup de la page quand ca deconnait car la je le trouve pas si mauvais le regex, j'ai pu le reduire un peu, mais ca m'emballe pas (37 000 step sur la page principale)

**Comment by sizanic** [comment]
> pourriez vous techniquement améliorer cette recherche globale ? En effet, il y a souvent des blocages interminables..

Ce sera disponible dans la prochaine version, d'ici peu ....
