### ISSUE TITLE
tirexo premium

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3457]
bjr
j'ai acheté un compte premium sur tirexo et j'ai entré mes identifiants uptobox dans vstream,  cependant aucun lien n'apparait
dans tirexo ? est ce qu'il manque une opération ?

[Windows, Android]
- Version Kodi: 19.3
- Version Vstream: [1.7.0]

**Comment by sizanic** [comment]
Bonjour.
Un compte premium sur Tirexo ne donneras pas plus de lien dans vStream.
Un compte Uptobox ne fera pas apparaître plus de liens en naviguant dans la source Tirexo.

Si avant tu arrivais jusqu'à des liens Uptobox en naviguant dans la source vStream, maintenant avec ton compte Uptobox tu pourras les lancer. Mais si tu n'en avais pas avant, ni un compte Tirexo ni un compte Uptobox ne les fera apparaître.

**Comment by sizanic** [comment]
Je ne sais pas à quoi peut bien servir d'acheter un compte Tirexo 🤔

**Comment by alKODIque** [comment]
> Je ne sais pas à quoi peut bien servir d'acheter un compte Tirexo 🤔

Pas de pub et possibilités de copier-coller tous les liens d'une saison complète de série... entre autre.
Moi, je ne peux plus m'en passer. On sauvve un temps énorme avec un Premium ;)

**Comment by sizanic** [comment]
ah ok, pour récupérer 👍🏻 

C'est ce que tu veux faire @kris06  ?
Utiliser ton compte Tirexo pour ajouter du contenu sur ton compte Uptobox et ensuite le voir dans vStream ?

Dans ce cas, ce n'est pas dans la source Tirexo que tu retrouveras le contenu de ton compte Uptobox, mais en passant par vStream/Compte/Uptobox.

**Comment by alKODIque** [comment]
Mais en fait, comme tu dis @sizanic  un compte Premium Tirexo ne permet pas de tirer avantage depuis kodi/vSream, a moins d'avoir souscri a la version Premium qui offre également un abonnement Alldebrid... Si c'est le cas, on peut utiliser ce compte Alldebrid dans les paramètres vStream et débrider les liens premium de toutes les sources (pas seulement Tirexo).

**Comment by kris06** [comment]
En effet aucun lien n'apparait,  je pensais naïvement qu'un simple abonnement à tirexo  donnait l'accès aux liens uptobox et 1fichier comme c'était le cas a une certaine époque ou tirexo fonctionnait

J'ai pas pris de grand risque,  2.50 euros pour 1 mois !  je survivrai lol
Mais alors pourquoi proposer la source tirexo dans vStream puisqu'il n'existe aucun moyen d'atteindre les liens ?

**Comment by sizanic** [comment]
> Pourquoi proposer la source tirexo dans vStream puisqu'il n'existe aucun moyen d'atteindre les liens

On essaye, en vain ... 😢 

Par contre si tu as maintenant un abonnement à uptobox, cela te donne la possibilité comme je le disais de récupérer les liens Tirexo sur ton compte uptobox, pour les voir ensuitre.


Mais surtout ....
de lire les liens hébergés sur d'autres comptes Uptobox.

Par exemple, comme tu as pu lire avant, @alKODIque récupère des séries complètes sur Tirexo.
Elle les sauvegarde sur son compte Uptobox.

Avec ton compte Uptobox, tu peux maintenant aller lire les séries qu'elle a récupérée.

Pour faire simple, tous le contenu de Tirexo a déjà été récupéré sur des comptes Uptobox et tu peux y accéder avec tes identifiants.

**Comment by kris06** [comment]
je sais que vous donnez beaucoup et  de mal pour notre plus grand plaisir et on cessera jamais de vous remercier pour votre incroyable travail.  Je  vais essayer un compte premium upto pour un mois,  le but étant de trouver une meilleur définition
Merci également  pour votre réactivité
C.

**Comment by sizanic** [comment]
Si tu veux essayer gratuitement ce que nous t'expliquons, tu peux prendre un compte gratuit d'une semaine chez alldebrid.

Cela va te donner accès à une bibliothèque plus grande que ce que te propose Tirexo, et que en bonne qualité.
