### ISSUE TITLE
Lire fichiers 1fichier

### ISSUE THREAD

**Issue by bobo15995** [Kodi-vStream/venom-xbmc-addons#3459]
**Décrivez le bug**

Bonjour,

Après l'installation du plugin, avoir configuré mon compte premium 1fichier, j'arrive à accéder à la liste des fichiers sur mon compte.
Par contre, quand je clique sur un film (que j'arrive pourtant à télécharger depuis le site de 1fichier), cela m'ouvre cette page : 

![image](https://user-images.githubusercontent.com/25310101/152062743-5269c11b-a6c1-4d7c-ab57-fda15b24b028.png)

Et quand je clique sur "No information", le logo de chargement apparaît une seconde puis plus rien.

**Votre system**
- OS: Windows 10
- Version Kodi: [18.9] (essayé avec la version 19.3 également)
- Version Vstream: [1.7.0] (essayé avec la version 1.6.0 également)

**Log**
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7982392/kodi.log)

**Image**

Aucune.

**Plus**

J'ai des compétences en développement si nécessaire.

Par ailleurs, quel host me conseillez-vous d'utiliser pour mon compte 1fichier svp ?  (même si j'ai bien compris que je faisais partie des rares utilisateurs à utiliser 1fichier...)
J'utilisais Wawacity mais il ne semble plus fonctionner (il m'affiche des captcha à l'infini).

Merci d'avance pour votre aide (et encore merci pour ce merveilleux plugin ❤️ ) !

**Comment by TmpName** [comment]
Alors j'ai beacoupo de mal a suivre tes logs.
Il y a des message d'erreurs qui ne concernent pas Vstream, mais je ne vois aucune ligne qui concerne la partie premium de Vstream.

Tu pourrais regarder si ca marche en passant pr un site proposant des liens 1fichier direct ?

Ensuite il y a peut etre des reglages a faire sur le compte 1fichier, a partir du site ?

**Comment by thorsten68** [comment]
Même problème pour moi, sur la shield et sur la tablette, plis d'accès à mon compte. Misère c'était ma dernière solution pour chopper des liens de qualité, les copier sur mon compte 1 fichier avec mon téléphone r, puis les ouvrir sur vstream pour les mater parce que tous les zt et wawa ne fonctionnent plus sur vstream. (je comprend que ce soit compliqué c'est pas un reproche).
Du coup retour à des liens en qualité de misère genre uqload

**Comment by thorsten68** [comment]
Si j'ai bien suivi une des solutions pour plus se faire chier est d'avoir un Premium alldebrid et passer par pastebin c'est ça ??

**Comment by thorsten68** [comment]
Je comprends pas mais si tu m'expliques je veux bien faire le test

**Comment by thorsten68** [comment]
On vient de rentrer de vacances. Je viens de tester et j'ai à nouveau accès à mon compte 1fich.
J'ai rien fait de spécial, pas de maj

**Comment by sizanic** [comment]
En relisant les échanges, je n 'ai pas l'impression qu'un soucis persiste.

Je clos le ticket.
