### ISSUE TITLE
Simplifications

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3460]
Je ne comprend pas quel est l’intérêt d’avoir séparé les sources de vStream (french Stream wiflix etc..)
Pourquoi finalement ne pas les réunir afin d’éviter à l’utilisateur de passer de l’une à l’autre ?
D’autant plus que cela éviterait les doublons, car les sources proposent souvent les mêmes liens.

VSTREAM DEVRAIT SE LIMITER AUX FONCTIONEMENT SUIVANT :
Une recherche générale (films &séries) 
3 catégories (Films – Séries – Autres) comme cela existe déjà
4 sous catégories (Nouveautés - Genres – Années - Vost ) Et basta

En effet, pour la suite, laissez le fichier indiquer de lui-même sa définition ou sa particularité 
(CAM -Webrip- HDrip 1080p etc.. ) comme vous le faites déjà (de toute façon c’est souvent erroné pour la définition)

En résumé, il resterait qu’une seule source dans laquelle serait réunie toutes les autres, ca me semble plus pertinent et plus simple

(On oublie les autres sous-catégorie 4K  720p  1080p  dvdrip 4k light  etc..  Qui ne servent à rien puisque le fichier de lui-même pourrait indiquer cette information)

C’est sûr c’est du boulot, mais tout cela mérite une simplification , une réflexion tout au moins.

Bien à vous tous
C.

**Comment by sizanic** [comment]
Merci pour tes propositions.

**Comment by bobo15995** [comment]
Et la recherche générale ferait une recherche sur toutes les sources ?

Ca me parait une bonne idée mais le problème c'est que toutes les sources ne proposent pas les mêmes hébergeurs. Je vois difficilement comment le contourner...

**Comment by sizanic** [comment]
Et toutes les sources ne proposent pas les mêmes sous-catégories.

Donc le menu est déjà en mode Catégories et Sous-catégories, puis les sources qui proposent la sous-catégorie sélectionnée.
Ensuite, a chacun de sélectionner la source selon l'expérience qu'il a avec les sources et ses préférences, et ses comptes premium...

**Comment by kris06** [comment]
on s'en fout des sous -catégories appartenant ou non à l'une ou à l'autre des  sources, le but , le travaille étant pour vStream de réunir le tout sous une forme simplifiée. 
Une seule source intégrant toutes les sources utilisées aujourd'hui par vStream

Puis une utilisation simple :

Recherche générale (films &séries)
3 catégories seulement  (Films – Séries – Autres) 
4 sous catégories (Nouveautés - Genres – Années - Vost )

**Comment by alKODIque** [comment]
Je suis en partie en accord avec ce que dis @kris06 ...
J'ai toujours trouvé qu'il y avait beaucoup trop de ''choix'' (ou sources).. Autant pour l'utilisateur que pour l'entretient que ca demande pour les développeurs.

Moi je verrais plus 2 catégories de liens.. Les gratuits et les Premiums.
Aucun réel besoin de passer ''visuellement'' par une source..

Mais ceci dit, si nous passons par le menu de recherche visuelle, nous pouvons passer outre les sources et choisir directement un média (au lieu de passer par une source en premier).

Éliminer le choix de source est quand-même une bonne idée donc... peut-être revoir le menu principal afin qu'il soit représentatif  d'un menu ''métadonnées'' --> (un peu comme les addons anglophones populaires tels que Fen ou Venom) C'est un peu ce qu'est le menu de recherche visuelle. Aussi, j'aimerais bien voir un genre de ''wizard'', peut-être, a l'installation de vStream (ou a la première ouverture) qui demande si nous désirons utiliser un mode Premium ou un mode Gratuit serait aussi génial a mon avis.

On parle pour parler hein 😉
Vive le _brainsorming_ lol

**Comment by alKODIque** [comment]
Je rajoute par contre que ceci occasionnerait des désavantages... car vStream récupère les images (pochettes) depuis les sources si nous n'activons pas les métadonnées... Alors ceci signifierait que la recherche de métadonnées deviendrait obligatoire. Donc Clé API TMDb obligatoire. Ce qui peut occasionner des lenteurs pour les systèmes de moindre performance... Et je crois que l'idée de base du Créateur de vStream @LordVenom  (salut en passant!!), était de rendre accessible GRATUITEMENT via kodi des contenus disponibles sur internet pour TOUS et pour ceux qui n'ont pas la possibilité de se payer des abonnements et/ou systèmes plus dispendieux...

Je crois aussi qu'il faut respecter cette idée de partage qui est la base... ;)

**Comment by sizanic** [comment]
> Aucun réel besoin de passer ''visuellement'' par une source..

Je suis d'accord avec toi @alKODIque 


> 4 sous catégories (Nouveautés - Genres – Années - Vost )

Mais je ne suis pas d'accord avec toi @kris06 


Car il y des sources qui ne proposent pas de classement par genre ni de classement par années.
Donc on fait quoi de ces sources 🤔 
On ne propose que leurs nouveautés ?
Alors qu'elle peuvent proposer un classement "Les plus vus".
Ce serait dommage de se passer de ce classement.

Par contre, une fois la sous-catégorie sélectionnée, il est vrai qu'il n'est pas forcement utile de re-sélectionner la source derrière.
Autant lancer sur toutes les sources (celles actives).

Avec peut-être un classement par source (comme avec la recherche).

-> Cela obligerai vraiment les gens à choisir leur 5 meilleures sources.
-> Cela n'oblige pas à activer les métadonnées (je n'ai pas trop compris cette contrainte 🤔 )

**Comment by alKODIque** [comment]
> -> Cela obligerai vraiment les gens à choisir leur 5 meilleures sources. -> Cela n'oblige pas à activer les métadonnées (je n'ai pas trop compris cette contrainte 🤔 )

Je parlais plutôt de si vStream ne proposerait qu'un menu principal sous forme de métadonnées (comme a l'intérieur de la recherche visuelle).. Je me disais qu'a ce moment, pour récupérer les métadonnées et pochettes, il devait impérativement faire en sorte de passer par l'API TMDb... une fois qu'on ''clique'' sur un média, a ce moment seul une recherche de lien s'effectue via les sources et hoster... Donc aucune sous-catégorie depuis les sources... 
Mais comme je ne m'y connais pas, je dis peut-être des bêtises car je ne comprends pas vraiment comme vous (les dev) comment un lien est récupéré depuis une source et quel chemin (ou logique) il faut emprunter lol

:))

**Comment by sizanic** [comment]
Ce que tu décris, c'est la recherche visuelle 🤔 
Une liste qui nécessite TMDB, puis on lance une recherche dans les sources...


Ce que nous faisons, c'est que nous référençons les liens vers les différentes pages que proposent les sites : nouveautés, genre, alphabétique, mieux notés, etc...

Donc nous proposons ces sous-catégories, chacune présentant la liste des sites correspondant.
Et en choisissant un site, nous nous rendons sur l'URL correspondant.

Il sera difficile de rendre tout ça transparent avec cette logique.

Prenons l'exemple de la sous-catégrorie "Nouveautés".
J'ai une liste de 15 sites qui proposent une page avec des nouveautés.

D'après vos propositions, il faudrait proposer les nouveautés sans faire apparaitre le noms des sites.
Mais comment ?
En parcourant les pages "nouveautés" de ces 15 sites, puis en supprimant les doublons ?

Et ensuite, si je suis choisi un film, je dois reparcourir tous les sites qui proposaient ce film pour retrouver la liste de tous les hosts ?

Bien sûr que tout ça serait possible, mais au détriment de la fluidité.
Etes-vous prêt à attendre plusieurs secondes entre chaque page ?

Pour exemple, c'est ce que nous faisons pour la recherche globale.
Pour un film sélectionné, nous parcourons une page de chaque sites pour créer la liste des résultats.

Là ce serait pareil, il faudrait parcourir la page "nouveautés" de chaque site pour créer la liste des nouveautés.

**Comment by alKODIque** [comment]
--> D'après vos propositions, il faudrait proposer les nouveautés sans faire apparaitre le noms des sites.
Mais comment ?

- Comment le font les addons populaires anglophone tels que Fen ou Venom: je sais pas... mais ca se fait puisqu'ils le font... Ils proposent un menu coimmun grace a l'API TMDb et lancent depuis ce menu la recherche de liens depuis diverses sources... et c'est rapide!! Et oui: c'est le même fonctionnement que la recherche visuelle mais les sources en moins dans les étapes de récupérations de liens.. on voit les hosters mais pas les sources...

**Comment by sizanic** [comment]
> Et oui: c'est le même fonctionnement que la recherche visuelle mais les sources en moins dans les étapes de récupérations de liens..

Et oui: donc la différence avec les autres addons (vu qu'on fait déjà les menus communs), c'est juste le nom des sources en moins.


On pourrait alors échanger sur cette partie, car pour le reste (les autres menus correspondant à de vraies sections des sites), c'est une exclusivité vStream, que les autres addons ne font pas 😄 

Concernant la récupération des liens sans afficher les sources, c'est discutable...
Il faudrait faire un sondage.
Peut-être que certains préfèrerait le garder pour certaines raisons : 
- choix de sa source préférée à la sélection
- recherche complète plus rapide
- etc..

Et cela permet d'intervenir en désactivant la source lorsque ce problème arrive : "blocage de la recherche à 12/42".

> La catégorie Nouveautés, pour reprendre ton exemple, ne provient pas d'une source mais des nouveautés diffusées sur tmdb.... tout comme genres, années, etc...

Tout comme dans le menu "Recherche visuelle" de vStream 🤔 
Mais peut-être pouvons nous ajouter quelques menus supplémentaires (je ne vois pas "Nouveautés" par exemple, mais on a bien par genre et par années).

**Comment by Arias800** [comment]
Ça va être drôle quand il faudra attendre 10 minutes avant d'arriver au lien, le temps que Vstream tente de résoudre Cloudflare, ou alors quand il va falloir résoudre 8 recaptcha d'affiler.
Ça a déjà été discuter il me semble, ce n'est pas réaliste de reprendre le modèle des addons anglophones.

À cela s'ajoute le fait que si on rend tout le chemin transparent, alors l'utilisateur sera incapable de faire un retour de bug correct, ce serait juste ingérable.
Certains ne savent même pas lire un truc aussi simple qu'un post https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2136.
Alors leur demander sur quoi ils ont cliqué, c'est le parcours du combattant. 
Et il y a les autres problèmes lister par Sizanic.

**Comment by sizanic** [comment]
Je ne pense qu'il était demandé de résoudre les liens, mais juste présenter les hosts.

Mais on se rejoint sur le fait de tout rendre transparent serait plus difficile à maintenir et moins souple pour les utilisateurs.

Mais on est pas contre ajouter de nouveaux menus TMDB...

**Comment by kris06** [comment]
Trop technique pour moi,  je n'ai qu'une vision utilisateur, cependant, je rejoins ici alKODIque faisant référence aux modèles anglophones et biens d'autres.. 
Vous connaissez surement cette copie approximative de Netflix (Teatv que je vous adresse plus bas) et qui ne trouve aucun mal a trouver très rapidement des liens dans tous les formats sur un modèle de recherche visuelle.  

Les ralentissements (Cloudflare recapcha ..) qu'évoque Arias800 sont probablement liés aussi à la structuration de vStream ou non, je l'ignore,  mais on peut tout même constater qu'il existe des addons qui possèdent des solutions pertinentes

Au regard des "concurrents" nous souffrons aussi en France de sources pas vraiment généreuses...

L'appli Teatv       Mais comment font il... ? 
https://www.dropbox.com/s/q7ikp4xfwr0s2ra/teatv_release_545%20NETFLIX.apk?dl=0
http://88.160.27.86:44428/share/Th7b5NrsbUVgUo2I/teatv_release_545%20NETFLIX.apk

**Comment by Arias800** [comment]
> L'appli Teatv Mais comment font il... ?

Réponse, c'est une application.
C'est incomparable, car Vstream se doit d'être multiplateforme.
Ça importe des restrictions sur ce que l'on peut faire ou pas.
En plus de cela, ce genre d'application gère le contenu qu'ils utilisent (un peu a la manière de Pastebin).

Ensuite, les sites anglophones utilisent beaucoup moins Cloudflare et Recaptcha.

**Comment by sizanic** [comment]
> cependant, je rejoins ici alKODIque faisant référence aux modèles anglophones et biens d'autres..

Nous faisons déjà comme les modèles anglophone en proposant des menus communs qui reposent sur TMDB.
-> tu dois aller dans vStream / Recherche visuelle.


> Vous connaissez surement cette copie approximative de Netflix (Teatv que je vous adresse plus bas) 

Très approximative en effet 🤣 

Alors qu'avec Kodi, on peut s'appuyer sur l'extension officielle TMDB pour avoir TOUS les menus de TMDB.
Et utiliser vStream pour les liens vers les vidéos.

Ce qui donne quand même une meilleure copie de Netflix : 

https://user-images.githubusercontent.com/47307622/152348977-337bfff0-bb54-4ff7-a6e6-272facec82aa.mp4

**Comment by sizanic** [comment]
c'est le titre de la vidéo, interface : Titan Bingie Mod
https://forum.kodi.tv/showthread.php?tid=355993

**Comment by bobo15995** [comment]
Je dois dire que je suis un peu perdu également dans toutes les configurations/hosts possible...

Quel est le meilleur moyen d'utiliser vStream sans compte premium de la façon la plus optimale ? (Et dont le service ne nécessite pas une mise à jour régulière du plugin)

**Comment by sizanic** [comment]
> Titan Bingie Mod est compatible avec vStream ?

vStream est compatible avec tous les habillages.
Les liens que l'on voit à la 42eme seconde de la vidéo sont des liens de vStream.

Dans cet exemple ce sont des liens de la source Pastebin de vStream.
Il faut un compte premium pour avoir ces liens, mais ce serait pareil avec des liens gratuits venant d'autres sources de vStream.


> Quel est le meilleur moyen d'utiliser vStream sans compte premium de la façon la plus optimale ?

Lance une recherche avec un film récent parmi toutes les sources de vStream.
Ce sera très long et pas optimum, mais tu repère ainsi les sources qui mettent du temps à répondre ou qui ne trouvent pas le film.
Tu te rends dans les paramètres de vStream et tu désactives ces sources.

Puis parmi les sources retenues, testes les résultats pour voir les hosts proposés. Essaies de lancer les liens.
Et rapidement tu pourras encore désactiver plusieurs sources.

A moins de vouloir garder des sources bien spécifiques (animés japonais, etc.), essais de réduire le nombre de sources à moins de 10, voire 5.

-> voilà une première optimisation

> (Et dont le service ne nécessite pas une mise à jour régulière du plugin)

On n'a jamais aucune idée de quelle source va s'arreter, va changer d'adresse ou va ajouter une nouvelle protection 🤔 

De toute façon, les mises sont régulières et automatiques.

**Comment by alKODIque** [comment]
D'accord, donc les dernières explications données me font comprendre que si c'est possible depuis le modèle des addons anglophone, c'est du au fait que les liens récupérés sont déjà en "vrac" et non récupérés depuis des sources de streaming organisées telles que depuis vStream..

exemple, depuis un addon anglophone, on voit que les liens sont généralement récupérés depuis un site torrent/nagnets. ces sites ne proposent pas de menus (genres, années, populaires, etc)..

Comme je disais plus haut, je n'ai pas vos connaissances de développeurs @Arias800  et @sizanic  🤪 mais vos arguments me font comprendre le pourquoi du comm 😉

Faudrait en aucun cas ralentir vStream, on est bien d'accord sur ce point 👍

**Comment by sizanic** [comment]
> exemple, depuis un addon anglophone, on voit que les liens sont généralement récupérés depuis un site torrent/magnets. ces sites ne proposent pas de menus (genres, années, populaires, etc)..


C'est un bon résumé 👍🏻 

Et inversement, c'est une force de vStream de pouvoir proposer ce genre de menu.
Je viens de remettre un menu (VOSTFR), qui propose des liens venant des sites qui proposent ce contenu.

Alors qu'il n'existe pas de menu VOSTFR sur TMDB 🤔

**Comment by bobo15995** [comment]
> Dans cet exemple ce sont des liens de la source Pastebin de vStream. Il faut un compte premium pour avoir ces liens, mais ce serait pareil avec des liens gratuits venant d'autres sources de vStream.

Mais où les utilisateurs se procurent ces liens Pastebin ? (Parce qu'on est d'accord qu'on parle bien de Pastebin l'hébergeur de fichiers textes ?)

> Lance une recherche avec un film récent parmi toutes les sources de vStream. Ce sera très long et pas optimum, mais tu repère ainsi les sources qui mettent du temps à répondre ou qui ne trouvent pas le film. Tu te rends dans les paramètres de vStream et tu désactives ces sources.
> 
> Puis parmi les sources retenues, testes les résultats pour voir les hosts proposés. Essaies de lancer les liens. Et rapidement tu pourras encore désactiver plusieurs sources.
> 
> A moins de vouloir garder des sources bien spécifiques (animés japonais, etc.), essais de réduire le nombre de sources à moins de 10, voire 5.
> 
> -> voilà une première optimisation

Ok merci. Je comprends donc qu'il n'y a pas une source privilégiée qui fonctionne mieux que les autres...
J'ai un compte premium 1fichier, donc je vais commencer par trouver la solution à mon problème https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3459 puis m'occuper de la source Wawacity. Ca te parait une bonne idée pour quelqu'un avec ce type de compte ?

> On n'a jamais aucune idée de quelle source va s'arreter, va changer d'adresse ou va ajouter une nouvelle protection 🤔
> 
> De toute façon, les mises sont régulières et automatiques.

Oui mais certains sites "évoluent" plus que d'autres. Je trouve par exemple que Wawacity est bien plus "stable" que Zone-Telechargement (j'avais codé mon propre système avant de découvrir cette semaine Kodi et ce plugin).

---

C'est un peu HS, mais je suis le seul à avoir un bug avec le captcha ? (Ils s'affichent à l'infini...)

**Comment by sizanic** [comment]
> Mais où les utilisateurs se procurent ces liens Pastebin ? (Parce qu'on est d'accord qu'on parle bien de Pastebin l'hébergeur de fichiers textes ?)

Oui, on parle de l'hebergeur de textes.

Il est possible pour tout le monde de saisir une liste de liens dans un fichier texte Pastebin et de partager cette liste en donnant l'identifiant Pastebin (la fin de l'adresse).

Pour accéder aux liens, il suffit alors dans la source Pastebin de vStream :
- Créer un dossier (à nommer par exemple "Films")
- Dans ce nouveau dossier, ajouter le code d'un Pastebin qui contient des liens vers des films
- Il est possible d'ajouter plusieurs codes dans le même dossier


Une communauté d'utilisateurs proposent déjà un ensemble de codes Pastebin, avec une grande collection de films et de séries.
Comme les liens ne sont pas hébergés sur un site, ils sont  : 
- toujours accessibles (la source réponds toujours, ce n'est pas un site de streaming)
- très rapide d'accès (pas de captcha ou de cloudflare, pas de décodage de JS, de GZIP, ...)
- valides et **vérifiés**

=> C'est la source la plus stable de vStream.
=> C'est la source qui propose le plus de contenu (films/séries/mangas/reportages/docs/sports/...)
=> C'est la source qui propose les meilleurs qualitées (tous les films récents en 4K)


La seul contrainte pour accéder aux liens : il faut un avoir un compte chez un hébergeur : Uptobox, AllDebrid ou RealDebrid
(ne gère pas 1fichier)

Plus d'info ici : 

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3045

**Comment by sizanic** [comment]
> Zone-Telechargement (j'avais codé mon propre système avant de découvrir cette semaine Kodi et ce plugin).

Tu ne connais vStream que depuis cette semaine ! 😱 
Bienvenue !


> mais je suis le seul à avoir un bug avec le captcha ? (Ils s'affichent à l'infini...)

Sans doute pas. Les captcha sont notre bête noire.

> Egalement, c'est possible de faire en sorte que mes fichiers stockés sur 1fichier apparaissent dans ma galerie de films ? 

Si tu veux dire dans la galerie à la racine de Kodi avec l'habillage par défaut, ce sera non.
Mais tu peux créer un raccourci en favoris pour y accéder rapidement.


> C'est un peu HS

Si tu as peur de faire du HS, vérifie si un sujet similaire n'est pas en cours.
Sinon, n'hésite pas à créer un nouveau sujet.

**Comment by Arias800** [comment]
> mais je suis le seul à avoir un bug avec le captcha ? (Ils s'affichent à l'infini...)

C'est normal, je pense que Google a encore augmenté la "sensibilité" ce qui les rendent impossibles sans navigateur.

**Comment by alKODIque** [comment]
> Et inversement, c'est une force de vStream de pouvoir proposer ce genre de menu. Je viens de remettre un menu (VOSTFR), qui propose des liens venant des sites qui proposent ce contenu.

Ca dépend de l'utilisateur... pour moi ce n'est pas le cas 🤷

> Alors qu'il n'existe pas de menu VOSTFR sur TMDB 🤔

Peut-etre, mais est-ce vraiment utile ce menu? --> encore une question de préférence... sachant que tout est a la base en VOSTFR, un menu ''MULTI'' ou VF serai vraiment beaucoup plus utile a mon goût :P

**Comment by alKODIque** [comment]
> Les ralentissements (Cloudflare recapcha ..) qu'évoque Arias800 sont probablement liés aussi à la structuration de vStream ou non, je l'ignore, mais on peut tout même constater qu'il existe des addons qui possèdent des solutions pertinentes
> 
Cloudflare et recapcha n'ont rien a voir avec vStream... ce sont les sites de streaming qui les utilisent malheureusement. Et puisque vStream ne fait que récupérer ce qui y est présent, il n'a poas le choix de récupérer également ces contraintes imposées par les sites

**Comment by TmpName** [comment]
>Le moin d'étapes il y a pour arriver au lien, le mieux c'est ;)

Ben le soucis, c'est que ce n'est pas le but de vtream, on prefere faire bosser l'utilisateur, qui est la machine la plus fiable, et etre sur d'avoir un resultat.

Mais tu peux desactiver des sites, et n'utiliser que les 2/3 qui te plaisent le plus non ?

**Comment by bobo15995** [comment]
> Tu ne connais vStream que depuis cette semaine ! 😱 Bienvenue !

Merci !

> Si tu veux dire dans la galerie à la racine de Kodi avec l'habillage par défaut, ce sera non. Mais tu peux créer un raccourci en favoris pour y accéder rapidement.

J'ai trouvé une solution qui est de monter mes films directement un dossier réseau et de l'importer dans la librairie Kodi. Comme ça, j'ai accès à tous mes films directement dans la galerie Films !

**Comment by sizanic** [comment]
> J'ai trouvé une solution qui est de monter mes films directement un dossier réseau

Je ne sais pas si tu as utilisé "rclone". C'est ce que nous préconisons pour ceux veulent monter leurs compte uptobox en réseau. Je ne sais pas s'il est compatible avec 1fichier.

**Comment by alKODIque** [comment]
> > Le moin d'étapes il y a pour arriver au lien, le mieux c'est ;)
> 
> Ben le soucis, c'est que ce n'est pas le but de vtream, on prefere faire bosser l'utilisateur, qui est la machine la plus fiable, et etre sur d'avoir un resultat.
> 
Oui je comprends... ca a les inconvénients de ses avantages hihi... mais aucun souci, je comprendxs l'idée 👍

> Mais tu peux desactiver des sites, et n'utiliser que les 2/3 qui te plaisent le plus non ?

Je n'ai qu'une source d'active, oui... ;)
Je suis trop difficile lol

**Comment by bobo15995** [comment]
> > J'ai trouvé une solution qui est de monter mes films directement un dossier réseau
> 
> Je ne sais pas si tu as utilisé "rclone". C'est ce que nous préconisons pour ceux veulent monter leurs compte uptobox en réseau. Je ne sais pas s'il est compatible avec 1fichier.

J'ai utilisé `1fichierfs` (https://forum.ubuntu-fr.org/viewtopic.php?id=2034345) qui est bien mieux que rclone pour 1fichier. Il ne télécharge le fichier que quand on l'ouvre. Toute la galerie ne prend donc aucune place (très pratique par exemple pour avoir des centaines de films sur une Raspberry Pi sans consommer le moindre espace disque !)

**Comment by sizanic** [comment]
Je ne ne connais pas assez les deux systèmes pour te dire, mais il me semble que rclone ne télécharge pas non plus de fichier, il monte un disque réseau pour accéder aux fichiers.

Mais vu que 1fichierfs a l'être d'être optimisé pour les comptes 1fichier, forcement ... 🤔 

Merci en tout cas pour l'info 👍🏻

**Comment by sizanic** [comment]
Même si je clos ce sujet, je sais que toutes ces discussions vont forcement nous influencer un peu dans nos développements futurs 😉
