### ISSUE TITLE
Trakt: Calendrier des sorties VO est KO

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3462]
Bonjour 😊

L'accès au calendrier des sorties VO, depuis mon compte Trakt ne fonctionne plus :(

![Screenshot_20220204-180023](https://user-images.githubusercontent.com/49578130/152614552-eb0595e4-ff12-4623-a224-d22306f8ef27.png)

Voici mon log, Ligne 1190 pour l'erreur 
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/8006719/kodi.log)

Je suis sous kodi 19.3 / nvidia Shield / vStream avec la dernière bêta disponible au moment de ce post

Merci!

**Comment by lebigboss** [comment]
Chez moi ça fonctionne, mais je suis avec une bêta

**Comment by alKODIque** [comment]
je suis avec la bêta aussi pourtant 🤯

**Comment by sizanic** [comment]
Une correction a été apportée suite à l'analyse du log.
