### ISSUE TITLE
Bandes annonces out

### ISSUE THREAD

**Issue by arzaz** [Kodi-vStream/venom-xbmc-addons#3464]
Problème de bandes annonces

- OS: [Android]
- Appareil: [nvidia shield]
- Version Kodi: [19.3]
- Version Vstream: [1.7.0]

Les bandes annonces ne fonctionnent pas. Une solution svp

**Comment by TmpName** [comment]
Hello, tu pourrais pas donner plus d'infos, car j'ai voulu tester de mon coté, et j'ai pas eu de soucis ...

**Comment by Digidix** [comment]
Bonjour,

@TmpName, j'ai effectivement le même problème, sur Windows, CoreELEC et Android, de la version 1.6.0 à 1.8.0.

Les BA fonctionnent en passant par le menu du skin dans "informationS", mais ne fonctionnent pas en passant par le menu contextuel "Bande annonce" ou "information".

Je pense que le problème est que le site de contournement mis en place par @Arias800 pour lire les BA YouTube ne fonctionne plus, car de mémoire, j'ai pu voir une fois le message timeout suivi de l'url du site qui remplace YouTube (souvent, on a le message de base, erreur de lecture d'un fichier ou erreur de Vstream je crois...), alors que depuis le skin, il me semble que ça prend la BA directement sur YouTube.

Ce n'est que des suppositions, si l'auteur a des logs, ce serait bien.

**Comment by sizanic** [comment]
Le faire depuis les favoris peut avoir un fonctionnement différent.

**Comment by TmpName** [comment]
Alors j 'avous je suis fort pour passer a coté des bugs mais la e viens de faire.

sources / vostfrfree / film (derniers ajout) , puis clic droit sur "a silent voice", bande annonce et c'est parti.

**Comment by Digidix** [comment]
Alors je viens de refaire pas mal de tests, ça a l'air plus compliqué que ça.

Le comportement des BA est très aléatoire, il faut tester sur plusieurs films.

Voici quelques exemples qui fonctionnent sur "information", "Bande annonce" et "informationS" (testé sur une source au hasard, sur Pastebin et en marque-page, avec vidage de tous les caches YouTube, Kodi et Vstream avant) :

-In From The Cold (Au service du passé)
-Dopesick
-Vengeance aux poings (depuis derniers ajouts Wiflix par exemple)
-Jumanji : Bienvenue dans la jungle

Exemples qui ne fonctionnent pas avec "information" et "Bande annonce" mais ok sous "informationS" (90 % des BA, se lance puis se ferme instantanément, on a juste le temps de voir le rond de chargement et le nom de la BA en haut de l'écran avec la barre de mise en cache comme quand ça fonctionne, mais ça se ferme instantanément sans message d'erreur, si on regarde ensuite dans le menu Kodi à gauche "liste de lecture actuelle", on a bien le lien de la BA, mais quand on clique dessus ça fait pareil) :

-Feria: The Darkest Light
-All of Us Are Dead
-Spider-Man : No Way Home

Étrange...

**Comment by TmpName** [comment]
Ca viendrait pas du format de la video ?
Tu aurais pas un exemple qui ne marche pas, mais sur une source classique ?

**Comment by Digidix** [comment]
@TmpName
> Quelqu'un se souvient pourquoi on utilise pas le plugin youtube pour ca ?

Je crois qu'Arias avait fait cette modification à cause de cette issue : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3359#issuecomment-941125291 (en gros, les BA avaient le problème de la mise en cache, mais c'était à cause du plugin YouTube et depuis le problème est résolu, donc peut-être est il possible de remettre le plugin de base je ne sais pas, Arias peut sûrement nous en dire plus).

Après, j'ai une autre piste, avant on pouvait choisir la définition de la BA (1080, 720...) et depuis le choix est en "Auto", ce qui est mieux, mais peut-être que ce réglage "Auto" fait que certaines BA ne se lancent pas.

**Comment by yodidon** [comment]
De mon côté, j’ai testé , en passant par informationS (skin aura mode) quelque bande annonce ce lance mais seulement si je suis sur mon réseau wifi qui n’utilise pas le dns Google, pas avec le réseau wifi qui lui passe en dns 1.1.1.1 - 1.0.0.1
Mais sur les 2 wifi avec les informations de vstream aucune ne se lance

**Comment by TmpName** [comment]
>Après, j'ai une autre piste, avant on pouvait choisir la définition de la BA (1080, 720...) et depuis le choix est en "Auto", ce qui est mieux, mais peut-être que ce réglage "Auto" fait que certaines BA ne se lancent pas.

Pas bete, je viens de tester, mais meme en 360p, meme resultat, ca trouve le fichier, recupere les infos, mais plante juste apres au moment de demarrer la lecture.

```
ERROR <general>: CCurlFile::FillBuffer - Failed: SSL peer certificate or SSH remote key was not OK(60)
ERROR <general>: CCurlFile::Open failed with code 0 for https
ERROR <general>: CFileCache::XFILE::CFileCache::Open - <https:
ERROR <general>: CVideoPlayer::OpenInputStream - error opening [https
```

**Comment by TmpName** [comment]
En tout cas, ca marche chez moi avec le plugin youtube https://pastebin.com/36RmiYgv

**Comment by Digidix** [comment]
@TmpName
Du coup le fix est dans la prochaine mise à jour ou il y a une manipulation à faire ?

**Comment by TmpName** [comment]
Ben je sais pas, pour le moment c'etait juste un test.
Je me souvient plus pouquoi on a retiré le dependance au plugin YT

Je pourrais mettre les deux mais le probleme c'est qu'il n y a pas moyen de savoir si un lien va marcher ou non avec la premiere solution (pour basculer sur la seconde), car c'est vraiement au moment de lire la video que ca deconne.

**Comment by Digidix** [comment]
> Je me souvient plus pouquoi on a retiré le dependance au plugin YT

--> https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3359#issuecomment-941125291

> Apres si personne n'est contre, je peux faire le rollback et repartir sur la vielle solution qui utilise le plugin YT.

À mon avis, puisque la dépendance YouTube n'a plus de problème, c'est qu'effectivement on peut rollback, mais peut-être que @Arias800 a un autre avis, puisque c'est lui qui avait mis en place ce fix ?

**Comment by TmpName** [comment]
J'ai mis a jour le fichier hoster pour youtube, le rollback est facile, juste une ligne a modifier.
Si la personne n'a pas le plugin youtube, ca bascule sur la methode generique.

**Comment by sizanic** [comment]
Sujet traité
