### ISSUE TITLE
Keyboard virtuel dans son compte uptobox

### ISSUE THREAD

**Issue by maxiben** [Kodi-vStream/venom-xbmc-addons#3465]
Kodi 19.3 (Android)

Lors d'une recherche a partir de l'item recherche du compte Uptobox dans vstream, la vidéo se lance puis à l'arrêt de celle-ci le keyboard virtuel réapparaît, puis toute action effectuée dans l'interface du skin (réinitialisation la position de reprise, ...) fait réapparaître le keyboard virtuel

**Comment by sizanic** [comment]
J'ai commencé à regarder, voilà mon analyse technique :

A la fin de la lecture d'un média lancé depuis les résultats de la recherche, kodi revient à la page précédente, qui est le résultat de la recherche.
Et cette page de résultats se rafraichit en repassant par le clavier pour saisir les mots à rechercher.
La page `showSearch`

Toute action dans la page des résultats à le même symptôme, le rafraichissement de `showSearch` passe par le clavier.

Une solution serait d'introduire une page intermédiaire après la recherche, avant d'afficher les résultats.

**Comment by TmpName** [comment]
Mais ca n'apparait que dans le site "Compte uptobox" ?

**Comment by sizanic** [comment]
oui, car depuis la recherche du compte uptobox, les résultats sont des liens tout de suite lisible. Contrairement aux résultats des autres sources qui affichent d'abord une liste de films, puis il faut entrer dans un résultat pour trouver les liens.

**Comment by sizanic** [comment]
Le souci est réglé.
Ce sera disponible dans la prochaine version.

**Comment by sizanic** [comment]
La version de vStream qui permet de régler ce souci de clavier lors d'une recherche sur son compte uptobox, vient de sortir.
La version 2.0.
