### ISSUE TITLE
Ou se trouve les marque-pages ?

### ISSUE THREAD

**Issue by kris06** [Kodi-vStream/venom-xbmc-addons#3466]
Ou se trouve le dossier  chargé du marque-page ?  quelle est la ligne correspondante.. ? ( le dossier bookmark est vide ! )

Aussi, peut on récupérer les enregistrement dans ce dossier en question? 

je vous remercie.
Kris

**Comment by TmpName** [comment]
Les pages sauvegardées dans la base de données, pas dans un repertoire.

**Comment by sizanic** [comment]
Si tu veux récupérer les marque-pages pour les déplacer entre plusieurs équipements, tu peux utiliser les outils de sauvegarde/restauration, accessibles dans les paramètres de vStream.

Autrement, toutes les informations qui concernent les données d'utilisation de vStream sont dans le fichier vstream.db.

**Comment by kris06** [comment]
merci  sizanic
