### ISSUE TITLE
vStream sur Stube TV

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3467]
vStream est disponible sur Stube TV sous Android qui est une version tout en un de Kodi et Vavoo avec une interface
plus dynamique à télécharger au https://github.com/ludopotte/vStream/releases/tag/vstreamstubetv

**Comment by ludopotte** [comment]
Oui tout a fait @sizanic mais c'est pour partager à la Communauté et non pour me faire de la promo.

**Comment by sizanic** [comment]
Malheureusement, si ce n'est pas de la promo, tu t'y prends mal.

Une annonce devrait plutôt ressembler à ça : 

`Pour rappel, vStream est compatible avec les clones de Kodi : SPMC, LibreELEC, Nodi, StubeTV, lodi, etc..`

-> Et c'est tout.

Là, tu as créé un zip tout-en-un sur ton github et tu viens ici nous en parler.

**Comment by ludopotte** [comment]
Ok merci de l'info, je referai mon annonce. Encore désolé @sizanic
