### ISSUE TITLE
vStream sur Stube TV

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3468]
Pour rappel, vStream est compatible avec la plupart des clones de Kodi : SPMC, LibreELEC, Nodi, StubeTV, lodi, etc

Pour Stube TV, de l'aide disponible ici : https://github.com/ludopotte/Kodi/releases/tag/vstreamstubetv

**Comment by sizanic** [comment]
La période pour te laisser faire la promotion de l'application Stube est terminée.
Je clos ce ticket.
