### ISSUE TITLE
Comment passer CloudFlare

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#3469]
Pour info, un petit tuto pour utiliser les sources protégées avec CloudFlare :

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-passer-CloudFlare

**Comment by ludopotte** [comment]
Merci @sizanic pour ce tuto mais quand c'est qu'on pourra passer CloudFlare sur Android et iOS ?
Car pour l'instant CloudFlare n'est disponible que pour Windows et Linux.

**Comment by yodidon** [comment]
> Merci @sizanic pour ce tuto mais quand c'est qu'on pourra passer CloudFlare sur Android et iOS ?
> Car pour l'instant CloudFlare n'est disponible que pour Windows et Linux.

Il suffit d’avoir un Windows ou un Linux avec flaresolver et toute les os sur le même réseau passeront cloudfare. Pas besoin d’une machine puissante

**Comment by sizanic** [comment]
> Merci @sizanic pour ce tuto mais quand c'est qu'on pourra passer CloudFlare sur Android et iOS ? Car pour l'instant CloudFlare n'est disponible que pour Windows et Linux.

Tu attends vraiment une réponse ?

Personne de la team vStream ne travaille actuellement sur une solution de contournement de Cloudflare, encore moins sur Android.

Donc je ne peux absolument pas te dire quand est-ce qu'on pourra passer CloudFlare sur Android et iOS 🤔

**Comment by lebigboss** [comment]
Merci @sizanic  en faite ça fonctionner plus chez moi, j'étais pas avec la bonne version, j'étais encore en 2.0.1
C'est bon ExtremeDown fonctionne maintenant

J'aimerai bien avec la même chose pour smartphone ça serait plus pratique

**Comment by lebigboss** [comment]
@Bmxfou  j'ai juste DL la dernière version 2.2.1

**Comment by Bmxfou** [comment]
J'ai une erreur a l'exécution de flaresolverr manque de dll j'ai tout essayé pour résoudre rien a faire

**Comment by yodidon** [comment]
Si Windows est en vrac je peux pas d’aider …

**Comment by Bmxfou** [comment]
Non mon Windows est stable et j'ai la dll présente dans system32, malgré tout j'ai l'erreur, enfin pas grave je vais essayer la source pastebin

**Comment by Che-Debaras** [comment]
> Non mon Windows est stable et j'ai la dll présente dans system32, malgré tout j'ai l'erreur, enfin pas grave je vais essayer la source pastebin

Pareil chez moi, flaresolverr ne fonctionne pas sur pc j'ai bien la dernière version.
Quel est ce fichier dll à avoir? Il est pas dans le zip de flaresolverr ?

**Comment by TmpName** [comment]
Vous auriez le message d'erreur complet au sujet de la dll ?

**Comment by Ujiuka** [comment]
> Pour info, un petit tuto pour utiliser les sources protégées avec CloudFlare :
> 
> https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-passer-CloudFlare

**Comment by Ujiuka** [comment]
Dans un système Android comment ça marche merci

**Comment by sizanic** [comment]
> Dans un système Android comment ça marche merci

il faut suive à la lettre le tuto donné dans le premier lien de cette publication !

- Installer FlareSolverr sur un pc sur le même réseau que le système Android utilise.
- Paramétrer vStream sur l'Android pour renseigner l'IP du PC.


**Pour quelle source cherches-tu as utiliser FlareSolverr ?**

Cette méthode n'est plus très fonctionnelle.
Peut-être as-tu juste un souci de DNS.

**Comment by sizanic** [comment]
Merci @zuli3n 👍🏻

**Comment by GravuTrad** [comment]
Hyper rapide sur la réslution du challenge, merci zulin3n.
En attendant que le repo officiel trouve une soluce lui étant adéquate pour le nouveau souci cloudflare.
