### ISSUE TITLE
Problème MAJ VStream

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#3472]
Bonsoir l équipe alors voici mon problème 
Depuis la 1.6.0 
La Maj verte se fait vers la 1.7.0 1.8.0 correctement 
Mais l appli en sois non 
Sa me fais cette extension n est pas compatible avec cette version 

je suis sur Mibox S 
19.3 kodi 

alors que sur mon autre TV 
Tout est bon
Toujours sous 19.3 

c est bizarre

**Comment by detobel36** [comment]
Bonsoir,

Aucun message d'erreur ?    
Sans logs, c'est compliqué d'aider...

**Comment by Mokoman30** [comment]
Message d erreur 
Cette add on  n est pas compatible avec cette version de kodi 
19.3 

alors que sur ma télé je tourne en 19.3 je suis à jour tout marche 
Mais sur ma Mibox
Sa me fais sa
Je bloque en 1.6.0 
je comprend pas

**Comment by sizanic** [comment]
Le mieux dans ce cas-là est de désinstaller vStream et dnsPython (si présent) et de réinstaller que vStream.

**Comment by Mokoman30** [comment]
Bon ba la je bloque complet je les désinstaller maintenant je peut ni réinstaller en 1.8.0 ni en version antérieur je n ai plus vstream HELP

**Comment by sizanic** [comment]
Tu n'utilises pas la même technique pour installer la version 1.8 que les versions antérieures ?

**Comment by Mokoman30** [comment]
non la version 1.8 je l avais fais comme d habitude proposer par vstream mais étant bloquer en 1.6.0 sa me faisais ses erreurs du coup je l ai désinstaller comme tu ma dit 

mais maintenant j ai télécharger les versions antérieures depuis ce site 
de la 1.8 a la 1.6 ma version 
ba  sa me met erreur pour toute ces versions 
je sais pas quoi faire

**Comment by Mokoman30** [comment]
je comprend pas pourquoi sa me fais ces erreurs la sa m était jamais arriver pendant une MAJ de l app

**Comment by sizanic** [comment]
> non la version 1.8 on me l avais proposer comme d habitude proposer par vstream mais étant bloquer en 1.6.0 sa me faisais ses erreurs du coup je l ai désinstaller comme tu ma dit
mais maintenant j ai télécharger les versions antérieures depuis ce site
de la 1.8 a la 1.6 pour voir si par usb sa marcher
ba sa me met erreur pour toute ces versions
je sais pas quoi faire


Je ne vois pas que tu ai tenté d'installer la version 1.8 de la version la plus normale

**Comment by sizanic** [comment]
Installer le repository selon cette méthode : https://kodi-vstream.github.io/docs/installation2/

Installer vStream depuis la méthode "2. Installer l’extension vStream" décrit sur cette page : https://kodi-vstream.github.io/docs/installation/

**Comment by Mokoman30** [comment]
J ai fais comme tu ma dit 
Sa me fais toujours l erreur 
![image](https://user-images.githubusercontent.com/46374635/157141993-ec52539b-46b1-472b-a7f0-6fbbbafb9d7a.jpg)
![image](https://user-images.githubusercontent.com/46374635/157142185-3ca8832d-4c18-4c20-817a-23ec6e3e99db.jpg)

![2FAE2B48-9704-4DBB-9085-9768D5FB9DC5](https://user-images.githubusercontent.com/46374635/157142249-0de6f0b6-5536-4e6b-8a81-c21bce1fe1a6.jpeg)
![image](https://user-images.githubusercontent.com/46374635/157142483-001819e7-5e96-4468-8d89-13ed5eb25846.jpg)

**Comment by Arias800** [comment]
t0mm0's, ce n'est pas une dépendance de Vstream, ni même d'aucune dépendance optionnelle.
Donc je ne comprends pas du tout ce que ton Kodi essaie de faire.
À la limite l'erreur xbmc.python, ça arrive quand le repo de Kodi est offline, mais a aucun moment t0mm0's devrait être appeler.

**Comment by sizanic** [comment]
Il faut que tu supprimes URLResolver à la main dans Kodi avant d'essayer d'installer vStream.

**Comment by Mokoman30** [comment]
Et comment je trouve  URLresolver svp ?

**Comment by sizanic** [comment]
> t0mm0's, ce n'est pas une dépendance de Vstream, ni même d'aucune dépendance optionnelle.

@Arias800 
J'ai essayé d'installer UrlResolver, cela demande l'installation de la dépendance t0mm0's 🤔 

@Mokoman30 
L'extension n'est pas visible dans Kodi, je ne vois que la suppression par les fichiers, en supprimant le dossier : 
\addons\script.module.urlresolver

**Comment by Arias800** [comment]
Ah bon ?
Pour le coup je ne savais pas.

**Comment by Mokoman30** [comment]
@sizanic je suis sur une box comment on supprime ce dossier stp

**Comment by Mokoman30** [comment]
Sayer j ai supprimer maintenant j ai l erreur Sélénium 
![Uploading image.jpg…]()

**Comment by Mokoman30** [comment]
![Uploading image.jpg…]()

**Comment by Mokoman30** [comment]
Sayer j ai dû supprimer sélénium aussi 
Et la c est bon Vstream se télécharge enfin

**Comment by Mokoman30** [comment]
Par contre le DNS Python reste en 1.12.1 au lieu du 1.12.2 il veux pas se mettre à jour sur tout les supports mais sa je pense c est pas grave

**Comment by Mokoman30** [comment]
Merci beaucoup @Arias800 @sizanic 🙏🏼

**Comment by sizanic** [comment]
> Ah bon ?
Pour le coup je ne savais pas.

@Arias800 

Moi non, plus c'est en cherchant la solution ici que je suis tombé dessus.

> j ai dû supprimer sélénium aussi

C'était bien l'idée, il faut supprimer les dépendances, quelles qu'elles soient, avant de réinstaller.

> Par contre le DNS Python reste en 1.12.1 au lieu du 1.12.2

Ce n'est pas grave en effet.
