### ISSUE TITLE
Plus d'accès extrême down

### ISSUE THREAD

**Issue by Bmxfou** [Kodi-vStream/venom-xbmc-addons#3473]
Bonjour, 

Depuis hier je n'ai pas accès à extrême down, quand je fais une recherche par section j'ai le message "page protéger par cloudflare veuillez lancer flaresolverr" et aucune information à la place des fichiers.

Je suis sous Android sur un boîtier a95xf3, sous coreelec et la version de vstream est la 1.8.0

Comment y remédier, j'ai désinstallé et réinstallé vstream c'est pareil.

J'ai essayé d'exécuter flaresolverr.exe sur un pc windows et de renseigner l'IP, j'ai un message d'erreur lors de l'exécution de l'exécutable avec une absence de DLL.

Merci

**Comment by sizanic** [comment]
Bonjour,

utiliser flaresolverr est pourtant bien la solution que tu dois mettre en place.
As-tu bien installer la dernière version : [v2.2.1](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.1) ?

Pour info : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-passer-CloudFlare

**Comment by Bmxfou** [comment]
Je n'arrive pas à l'installer sous Android

**Comment by sizanic** [comment]
Parce que tu utilises un vieux windows7 32 bits, alors que la version est prévue pour un windows 64 bits.

**Comment by Bmxfou** [comment]
Non c'est une version 64 bit que j'ai

**Comment by Arias800** [comment]
Il ne pourra pas faire grand-chose.
WS2_32.dll c'est un fichier système de Windows.
Il faut essayer une réparation système (peu importe si c'est Windows 7, le commande fonctionne exactement pareil).
https://www.commentcamarche.net/informatique/windows/25-verifier-et-reparer-des-fichiers-systeme-avec-windows-10/

**Comment by Bmxfou** [comment]
Je viens de faire un sfc/scannow et redémarrer 

Vous vous cliquez juste sur l'exécutable de flare et c'est bon?

Extrême down fonctionne chez vous?

**Comment by yas06** [comment]
> Je viens de faire un sfc/scannow et redémarrer, toujours pareil j'ai bien la dll présente dans system32
> 
> Vous vous cliquez juste sur l'exécutable de flare et c'est bon?
> 
> Extrême down fonctionne chez vous?

salut oui je clic et ca marche 
 si tu a bien la ddl dans ton système essaye de voir si ton antivirus ne bloque pas.
exécute en mode admin flaresolverr et crée une exception sur ton firewall pour la communication tcp qui est souvent bloque

**Comment by Bmxfou** [comment]
Je n'ai pas d'antivirus juste l'antimalware de windows, je vais essayer pour l'exception du firewall windows

**Comment by yas06** [comment]
> Je viens de faire un sfc/scannow et redémarrer, toujours pareil j'ai bien la dll présente dans system32
> 
sinon je pense que ton win 7 n est peut-être pas compatible avec l exe il se peut que tu as bien la dll presente mais l architecture du Windows à du changer entre Windows  7 et 10 l exe doit la chercher à un autre endroit j espère que tu vois ce que je veux dire 
en bref test avec un pc win 10 voir

**Comment by lebigboss** [comment]
Crée toi une VM en Windows 10

**Comment by lebigboss** [comment]
Par contre pour les séries il y a un souci, c'est pas possible d'accéder aux liens

**Comment by Bmxfou** [comment]
J'y ai pensé mais mais quand j'y penses ça le fait quand même chier de laisser tourner le pc pour flaresolverr pour accéder à du contenu sur la box Android.

Au final je passe par pastebin, actuellement j'ai installé l'Addon de rayflix et ce soir je test U2play pour comparer, donc plus vraiment besoin d'accéder a extreme de ce fait

**Comment by McFL7** [comment]
Bonjour,

Idem je n'arrive plus à accéder à Exteme-Down avec le fameux message FlareSolverr.

Je vois qu'il y'a cette solution avec Linux et Windows mais qu'en est-il pour ceux utilisant Kodi sur Android ou Firestick (comme moi dans ce dernier cas) ? Il faut utiliser un PC tiers et y faire tourner FlareSolverr en proxy. Dans mon cas je pense pouvoir utilser mon ancien Raspberry PI 3B+ mais y'a t'il une doc pour le configurer ?

**Comment by sizanic** [comment]
Bonjour 

Si tu as un windows sur un pc tiers, la doc est ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3469
Pour d'autres plateformes, des solutions avec Docker : https://github.com/FlareSolverr/FlareSolverr

**Comment by Che-Debaras** [comment]
Idem chez moi j'ai installé flaresolverr et il ne marche pas
J'ai testé avec wiflix mais il a encore changé de url 
Après .tel il est devenu .uno maintenant c'est. City

Mais avec les autres sources ça ne marche pas non plus
Meme une fraîche installation vstream n'installe plus les dépendances comme urlresolver ou résolveurl
J'ai du installer chaque dépendance manuellement

Je suis tjrs en kodi 19.3

**Comment by arzaz** [comment]
Marche pas sur Shield TV

**Comment by yas06** [comment]
salut
ca marche pas  ? quoi ?
sinon tu instal FlareSolverr v2.2.1 sur ton pc tu renseigne l adresse de ton pc dans les paramètres vstream ,source
quant tu ouvres FlareSolverr sur ton pc tu doit avoir ca

2022-02-21T17:17:29+01:00 INFO FlareSolverr v2.2.1
2022-02-21T17:17:29+01:00 INFO Testing web browser installation...
2022-02-21T17:17:43+01:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
2022-02-21T17:19:08+01:00 INFO Test successful
2022-02-21T17:19:08+01:00 INFO Listening on http://0.0.0.0:8191

si oui  regarde ca

> > Je viens de faire un sfc/scannow et redémarrer, toujours pareil j'ai bien la dll présente dans system32
> > Vous vous cliquez juste sur l'exécutable de flare et c'est bon?
> > Extrême down fonctionne chez vous?
> 
> salut oui je clic et ca marche si tu a bien la ddl dans ton système essaye de voir si ton antivirus ne bloque pas. exécute en mode admin flaresolverr et crée une exception sur ton firewall pour la communication tcp qui est souvent bloque

**Comment by arzaz** [comment]
On parle bien du site Extreme down? Oui ca marche pas sur shield tv (android)
Pourquoi utiliser un PC alors que j'ai une box android tv

**Comment by yas06** [comment]
> On parle bien du site Extreme down? Oui ca marche pas sur shield tv (android) Pourquoi utiliser un PC alors que j'ai une box android tv

oui c bien ca a cause du  CloudFlare et Android ne gère pas ce système donc y faut un pc comme proxy je sais c est galère mais je cherche une solution avec un rasperi ou carrément je suis en train de voir des mini pc a 10e sur aliexpress

**Comment by sizanic** [comment]
@arzaz 

Le système qui permet de contourner la protection n'est pas disponible sur Android.
Donc il faut l'utiliser sur un PC.
Et le système Android va se connecter au PC pour lui demander de contourner cette protection.


Voir cette discussion et le tuto pour la mise oeuvre.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3469

**Comment by McFL7** [comment]
Bonjour,

J'ai installé la dernière version 2.2.1 de FlareSolver sur un PC windows pour faire office de proxy à mon Kodi sur Firestick. Le serveur traite bien les requêts CloudFlare envoyées par Vstream mais j'ai des erreurs de Timeout 2000ms et les pages de Extreme-Down s'affichent à moitié ou pas du tout, et mettent du bcp de temps à charger. 

Quelqu'un a rencontré ce genre de soucis sur android et a t'il moyen de paramétrer le Timeout pour FlareSolverr, apparemment ça ne peut se faire que via un paramètre MaxTimeout envoyé avec la requête qui est envoyée au FlareSolverr, donc par Vstream. Vstream envoie apparemment une requête avec 2 secondes (2000ms) de Timeout. 

Il serait possible de rajouter dans Vstream un paramètre Timeout FlareSolverr en plus de l'adresse IP du serveur FlareSolverr ? 

Explication du paramètre MaxTimeout :
https://github.com/FlareSolverr/FlareSolverr#commands

![IMG_20220221_204835](https://user-images.githubusercontent.com/98433855/155018336-45e4c7cc-a21b-42ee-8d03-304155c64f9a.jpg)

Ci-dessous une capture de l'erreur : 

![IMG_20220221_204141](https://user-images.githubusercontent.com/98433855/155018482-4419f9d3-8e96-4310-ad4f-918fa8d4b248.jpg)

**Comment by lebigboss** [comment]
J'ai le même soucis, en faite flaresolverr ne traite qu'une seul requête maintenant, donc obliger de relancer le logiciel pour afficher les liens d'une section, ensuite de toute façon quand on clique sur une jaquette ça n'affiche pas les menus correctement

**Comment by pticon78** [comment]
Bonjour comment trouver l'addon u2pplay sur kodi svp désolé je fais un hors sujet mais je suis novice. Ou bien une solution sur kodi (Android tv) pour regarder en streaming vstream c cool mais j'aimerais en qualité vidéo meilleur avant y avait ZT mais ça ne fonctionne plus

**Comment by sizanic** [comment]
Bonjour,

Le contenu de bonne qualité que tu recherches dans l'addon u2pplay est également disponible dans vStream.
Les deux addons reposent sur la même technologie.
Et dans les deux cas il te faudra un compte premium chez Uptobox, allDebrid ou RealDebrid.

Dans vStream, ce contenu est disponible dans la source "Pastebin".
Il te faut saisir des codes.

La communauté "Les alKODIques" proposent des codes que tu peux retrouver sur leur Discord, leur site internet ou leur groupe facebook.

**Comment by pticon78** [comment]
Merci beaucoup pour ta réponse et ta réactivité 👍
