### ISSUE TITLE
QRCODE DE VSTREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3474]
vStream est disponible en QRCode à flasher au https://bit.ly/qrcodevstream

**Comment by sizanic** [comment]
J'espere que ce n'est pas encore un lien qui ramène finalement vers ta version de vStream 🤔

**Comment by ludopotte** [comment]
Non du tout @sizanic c'est un lien redirigeant vers le dépôt de vStream sur Github. J'ai trouvé ça utile de le faire pour la Communauté.

**Comment by sizanic** [comment]
ok, il faut que ce soit bien vers le dépot et pas vers l'addon.

Je pose la question car le lien dans ton message nous emmènes bien vers une image, mais elle est accompagnée d'un zip qui contient des versions : 
- beta.vstream
- beta.mobile
- plugin.mobile


Rien d'officiel 🤔 

Pour partager juste une image, es-tu vraiment encore obligé de glisser tes versions modifiées de vStream avec ?

**Comment by sizanic** [comment]
Tu n'as pas besoin de demander, mais tu dois bien respecter certaines règles, comme ne pas rediriger vers un autre site sans le préciser.

Voila une proposition propre : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3475
