### ISSUE TITLE
QRCODE DE VSTREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3475]
Je propose ce QRCode qui permet de télécharger directement le zip du dépot 0.0.5 de vStream.
Une fois le zip téléchargé, il faut l'installer dans kodi à partir du menu "installer une extension depuis un zip".

![QRCodevStream](https://user-images.githubusercontent.com/47307622/154670423-a0265564-4e40-419d-b3d2-5237d4cd0b85.png)

**Comment by sizanic** [comment]
QRCode ajouté en page d'accueil du github 👍🏻
