### ISSUE TITLE
Nouveau source - besoin de votre aide svp :)

### ISSUE THREAD

**Issue by TVINFO** [Kodi-vStream/venom-xbmc-addons#3479]
Bonjours la communauté, 

J'essaye de ajouter un nouveau source avec le site **ww w.irantv24.com** afin de faciliter la vie de mes parentes et de ma famille, mais également d'apprendre pour ajouter d'autre source.

J'ai regardé le tuto pour ajouter une source mais malheureusement je n'arrive pas a faire fonctionne ce que j'ai crée pour le site en question, après avoir essayé pendent plusieurs heure a debuger,  j'ai fait appel a votre aide, est-ce que quelqu'un pourrais me faire un exemple avec le site  **ww w.irantv24.com** ou bien m'aider tout simplement a trouver la solution dans mon fichier s'il vous plait ?

Je vous remercie pour votre aide.

Voici mon ce que j'ai crée sur **pastebin** : 
https://pastebin.com/raw/gqt8wZvW

**Comment by TmpName** [comment]
Essayes ca https://pastebin.com/MFp5x8SL

Film / genres / drama / ...

Par contre ce site utilise des host non encore géré par Vstream.

**Comment by sizanic** [comment]
> Par contre ce site utilise des host non encore géré par Vstream.

J'ai vu un lien ok.ru, qui est géré par vStream. Il y en a peut-être d'autres.

@TVINFO 
Par contre, il ne s'agit pas d'un site qui propose du contenu en français, qui est le propre de notre addon.

Aussi, nous ne pourrons pas forcement beaucoup t'aider, et tu devras maintenir seule cette source que nous n'ajouterons pas dans notre extension.

**Comment by yodidon** [comment]
@TVINFO passe sur discord si tu veux , je suis aussi en apprentissage, peut-être je pourrais d’aider pour le démarrage

**Comment by TVINFO** [comment]
> 

Merci Beaucoup cela m'aide vraiment beaucoup.
Avez-vous la possibilité de faire juste un exemple avec une serie pour que je puisse voir comment je peux récupérerles épisode s'il vous plait ? 
exemple: https://www.irtvs24.com/series/roozi-roozegari-series/ 

Merci encore  pour votre aide

**Comment by TVINFO** [comment]
> Merci Beaucoup cela m'aide vraiment beaucoup. Avez-vous la possibilité de faire juste un exemple avec une serie pour que je puisse voir comment je peux récupérerles épisode s'il vous plait ? exemple: https://www.irtvs24.com/series/roozi-roozegari-series/
> 
> Merci encore pour votre aide

**Comment by TVINFO** [comment]
> > Par contre ce site utilise des host non encore géré par Vstream.
> 
> J'ai vu un lien ok.ru, qui est géré par vStream. Il y en a peut-être d'autres.
> 
> @TVINFO Par contre, il ne s'agit pas d'un site qui propose du contenu en français, qui est le propre de notre addon.
> 
> Aussi, nous ne pourrons pas forcement beaucoup t'aider, et tu devras maintenir seule cette source que nous n'ajouterons pas dans notre extension.



> > Par contre ce site utilise des host non encore géré par Vstream.
> 
> J'ai vu un lien ok.ru, qui est géré par vStream. Il y en a peut-être d'autres.
> 
> @TVINFO Par contre, il ne s'agit pas d'un site qui propose du contenu en français, qui est le propre de notre addon.
> 
> Aussi, nous ne pourrons pas forcement beaucoup t'aider, et tu devras maintenir seule cette source que nous n'ajouterons pas dans notre extension.


Merci Beaucoup cela m'aide vraiment beaucoup. Avez-vous la possibilité de faire juste un exemple avec une serie pour que je puisse voir comment je peux récupérer les épisode s'il vous plait ? 
exemple: https://www.irtvs24.com/series/roozi-roozegari-series/

Merci encore pour votre aide

**Comment by TVINFO** [comment]
> Essayes ca https://pastebin.com/MFp5x8SL
> 
> Film / genres / drama / ...
> 
> Par contre ce site utilise des host non encore géré par Vstream.

Merci Beaucoup cela m'aide vraiment beaucoup. Avez-vous la possibilité de faire juste un exemple avec une serie pour que je puisse voir comment je peux récupérer les épisode s'il vous plait ? 
exemple: https://www.irtvs24.com/series/roozi-roozegari-series/

Merci encore pour votre aide

**Comment by TVINFO** [comment]
> > Par contre ce site utilise des host non encore géré par Vstream.
> 
> J'ai vu un lien ok.ru, qui est géré par vStream. Il y en a peut-être d'autres.
> 
> @TVINFO Par contre, il ne s'agit pas d'un site qui propose du contenu en français, qui est le propre de notre addon.
> 
> Aussi, nous ne pourrons pas forcement beaucoup t'aider, et tu devras maintenir seule cette source que nous n'ajouterons pas dans notre extension.

Oui je fait ca pour le moment pour apprendre, je vais essayer de prendre exemple  puis trouver des site en Français pour pouvoir participer :)

**Comment by TVINFO** [comment]
> @TVINFO passe sur discord si tu veux , je suis aussi en apprentissage, peut-être je pourrais d’aider pour le démarrage

Je veux bien si tu as un lien de discord ?

**Comment by yodidon** [comment]
> > @TVINFO passe sur discord si tu veux , je suis aussi en apprentissage, peut-être je pourrais d’aider pour le démarrage
> 
> Je veux bien si tu as un lien de discord ?
https://discord.com/

**Comment by TVINFO** [comment]
> > > @TVINFO passe sur discord si tu veux , je suis aussi en apprentissage, peut-être je pourrais d’aider pour le démarrage
> > 
> > 
> > Je veux bien si tu as un lien de discord ?
> > https://discord.com/
Je parle de lien de groupe discord ou le nom ^^

**Comment by yodidon** [comment]
> > @TVINFO passe sur discord si tu veux , je suis aussi en apprentissage, peut-être je pourrais d’aider pour le démarrage
> 
> Je veux bien si tu as un lien de discord ? https://discord.com/ Je parle de lien de groupe discord ou le nom ^^

Passe ton pseudo

**Comment by TVINFO** [comment]
> > > @TVINFO passe sur discord si tu veux , je suis aussi en apprentissage, peut-être je pourrais d’aider pour le démarrage
> > 
> > 
> > Je veux bien si tu as un lien de discord ? https://discord.com/ Je parle de lien de groupe discord ou le nom ^^
> 
> Passe ton pseudo

StreamLv#0406

**Comment by sizanic** [comment]
> Avez-vous la possibilité de faire juste un exemple avec une serie pour que je puisse voir comment je peux récupérer les épisode s'il vous plait ?

Dans ce tuto, il y a un exemple ("fichier squelette") pour le traitement des films et séries :

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source


Et les outils de développement et debug : 

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Debugger-avec-Eclipse
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Debugger-avec-Visual-Studio

**Comment by Che-Debaras** [comment]
Pour infos ya plein d'autres dossier host sur vstream non prise en charge
Ex: younetu, short, fembed etc....
