### ISSUE TITLE
ZONE TELECHARGEMENT

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3480]
Bonjour,

J'ai remarquer que Zone Téléchargement fonctionne pas correctement et que le site à souvent des Bugs.
Je propose une solution pour que le Site marche bien en changeant la Source dans vStream disponible
au http s://www.meilleure-innovation.com/quelle-est-la-nouvelle-adresse-officielle-de-zone-telechargement/

Est-ce que ca serais possible d'avoir la modification ?

Cordialement,
Ludo Potte

**Comment by razorex** [comment]
Bonjour la team vStream, si je fais cette source est ce que la récupération des hosters est possible vu que c'est du dl-protect, et est ce que qq'un serait prêt à le terminé ou m'assister sur la partie final ??
