### ISSUE TITLE
Sources vidéos - chaînes en streaming

### ISSUE THREAD

**Issue by poiluepistache** [Kodi-vStream/venom-xbmc-addons#3481]
Bonjour, je vous mets à disposition 2 sources vidéos que je connais pour regarder des chaînes en streaming principalement du sport pour but que si vous le pouvez, les ajouter à vstream parce que je ne sais pas coder donc je ne peux pas le faire. Sur les sites que je vais vous mettent à disposition il y a des chaînes Anglaises et comme je sais que l'addon vstream à pour but d'être 100% Français et bien prenez que les chaînes Françaises.

Sites de streaming : 

http://freestreams-live1.com ← Exactement pareil que le précédant le nom de domaine principal freestreams-live1.com redirige vers sw.freestreams-live1.com Sur ce site il y a beaucoup de chaînes non françaises et française et si vous pouvez ajouter les chaînes françaises il faut savoir que le player 2 et 3 est de meilleur qualité que le 1 généralement.

Voilà j'ai beaucoup plus de source normalement mais ce sont que des chaînes pas françaises donc je ne les partages pas. Je remercie d'avance si vous arriver à les intégrer à vstream. Merci et bonne journée!

**Comment by sizanic** [comment]
Salut,

Nous proposons déjà Streamonsport depuis longtemps 🤔 

Et en effet l'adresse change souvent, nous avons donc développé un nouveau système qui permettra de suivre plus rapidement les nouvelles adresses.
Ceci sera disponible dans la prochaine mise à jour.

**Comment by sizanic** [comment]
Pour sportsstats, tel que discuté en parallele sur le Discord vStream (le 01/06), il ne sera pas ajouté car disponible par l'addon TheCrew.

Pour freestreams, on va regarder à l'occasion...

**Comment by sizanic** [comment]
@poiluepistache 

Le site que tu proposait à été fermé par le gouvernement US.
