### ISSUE TITLE
DNS CHANGER SUR KODI

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3482]
Pour changer les DNS directement sur Kodi, télécharger le Depot "repository.space2walker..." pour Kodi Leia & Matrix
au https://github.com/Space2Walker/kodi-space-repo/releases et installer le Programme "DNS Leak-Test". ![Logo-DNS-Changer.png](https://www.turbopix.fr/images/2022/03/13/Logo-DNS-Changer.png)

**Comment by GravuTrad** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3509#issuecomment-1107937503

dnspython suffit largement

**Comment by sizanic** [comment]
Pas mieux.
La solution dnspython prise en charge nativement par vStream est la méthode la plus simple et la plus intégrée.
