### ISSUE TITLE
Accès compte UpToBox 

### ISSUE THREAD

**Issue by speedjeje** [Kodi-vStream/venom-xbmc-addons#3483]
Bonjour

Décrivez le bug
Depuis la mise à jour en version 1.8.0, impossible de lire les fichiers présents sur mon compte premium UpToBox.
Les dossiers sont accessibles et la liste des fichiers s'affiche mais lorsqu'on lance la lecture vStream indique "fichier introuvable".

Votre system
- OS: LibreElec
- Appareil: Raspberry Pi 
- Version Kodi: 18.9
- Version Vstream: 1.8.0

Nous devons le reproduire

- Nom du site:  UpToBox 

Merci

**Comment by sizanic** [comment]
Bonjour.
On va regarder ça...

**Comment by Pitipito** [comment]
Bonjour,
J'ai eu le même souci que "speedjeje" et j'ai résolu le problème en allant dans le menu de vstream : 
- Informations
- Versions
- Sélectionner Version 1.8.0
- OK
Ensuite c'est tout bon.
J'ai reproduit ce procédé sur 5 ou 6 appareils et ça a fonctionné.

**Comment by zneb06** [comment]
Bonjour Pitipito .Merci mais exige mise a jour. DNSpython 1.12.2. Salutations.

**Comment by speedjeje** [comment]
Merci pour vos contributions ....
Je pense aussi que c'est un problème de version de python
J'ai 6 appareils (sous différents OS) qui font tourner vStream 1.8.0 sans aucun problème car en python 3, le seul qui bugge c'est son Rpi sous LibreElec et python 2.

**Comment by sizanic** [comment]
@speedjeje 

vStream 1.0.8 est compatible en Python 2 et Python 3 🤔

**Comment by speedjeje** [comment]
Alors, je patauge encore plus ....
Parce que l'accès Uptobox se fait parfaitement, c'est lorsque je lance la lecture que ça ne trouve pas le fichier qui est pourtant listé ...

**Comment by speedjeje** [comment]
Problème réglé !!!
Désinstall et réinstall propre de vStream .... et tout roule 😎
Je ferme !!
