### ISSUE TITLE
Addons sport HD

### ISSUE THREAD

**Issue by us-mereau** [Kodi-vStream/venom-xbmc-addons#3484]
Bonjour, 
L addons sport HD ne fonctionne plus ???

**Comment by sizanic** [comment]
Bonjour,
ici c'est l'addon "vStream".

Parles-tu d'un autre addon, ou d'une section dans vStream ?

Nous proposons 3 sources de sports :
- channelStream
- liveTV
- streamonsport

Pour accéder aux deux premieres, tu dois simplement changer le DNS dans les paramètres réseau de ton équipement.

Pour la troisième, tu dois attendre la prochaine mise à jour.
La mise à jour proposera également une nouvelle source.

Mais nous n'avons aucune section "Sports HD" 🤔

**Comment by us-mereau** [comment]
Désolé en effet c'est un autre addons.
Par contre pourrais tu être plus précis sur le DNS a changer pour Channel stream ?
Merci.

**Comment by sizanic** [comment]
Changer son DNS :

Android :
https://www.phonandroid.com/changer-serveurs-dns-smartphone.html

fireTV :
https://www.prodigemobile.com/tutoriel/modifier-dns-mobile-android/


Ne pas installer de VPN comme préconisé par ces publicités déguisés en tuto.

Les valeurs à renseigner pour les DNS : 
DNS1 : 8.8.8.8
DNS2 : 8.8.4.4

C'est un exemple avec le dns google.

D'autres DNS intéressants sont ceux de CloudFlare ou OpenDNS : 

https://le-routeur-wifi.com/liste-serveurs-dns/
