### ISSUE TITLE
Wiflix

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#3492]
Bonjour à toutes et tous,

Depuis la mise à jour 19.2 le site Wiflix semble ne plus fonctionner.

Merci pour votre aide.

Encore un tout grand merci pour votre considérable travail.

**Comment by sizanic** [comment]
Bonjour,

Il y a pourtant un message "page protégé par cloudflare, essayer FlareSolverr".

La procédure pour utiliser flareSolver est ici : 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-passer-CloudFlare

**Comment by Papounet58** [comment]
Merci
