### ISSUE TITLE
Besoin d'aide Viki MPD fichier (Encore :))

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#3493]
Bonjour,

Désolé, voici le contexte: Addon Viki ne marche plus. Il y a deux problèmes:
1. Le API pour résoudre le lien ne marche plus
2. Vstream utilise Inputstream pour jouer le MPD fichier. Inpustream requiert la licence URL pour décoder le stream. Vstream ne fournit pas la licence URL. Ma question concerne le deuxième problème

Merci

Le MPD fichier a besoin URL de la licence: https://manifest-viki.viki.io/v1/license?dt=dt3&video_id=<video_id>
Mais je ne suis pas capable de le faire fonctionner.
J'apprécié beaucoup votre aide 👍 

MPD url:
hxxps://manifest-viki.viki.io/v1/1193743v/cloudfront/domain_4/mpd/vtt/viki/baseline/sd/ww/dt2_dt3/manifest.mpd?tag=mpdhd%3Abaseline%3Aww%3AsourceVIKI%3Ampd%3Acached%3Adt2_dt3&h_request_id=721921ea79ec10438a42f9f319e5d898%2F11473063642637891618&h_country=ca&device_model=vivo+1606&h_data_center=scr-2&h_host=playback-streams-7b74b7d55b-x4r5b&h_timestamp=1649277160&max_res=360p&app=100005a&sig=73e731cf228bd94365cdedcd072cbb5cf95346e6

Encore merci

**Comment by sizanic** [comment]
Bonjour,
Je ne comprend absolument pas le contexte.
Je n'ai aucune idée de quoi tu parles.

**Comment by Arias800** [comment]
Viki est trop complexe à mettre en place sur Vstream (au niveau d'inpustream adaptative).
Il faut que je me penche sur l'addon dédiée.

**Comment by sviet2k** [comment]
Bonjour @Arias800 ,
As-tu une idee comment trouver le 'licence" url de Viki? Ou comment faire fonctionner le MPD fichier avec Kodi?
Merci en avance de ton aide

**Comment by Arias800** [comment]
Regarde ici : https://github.com/Arias800/plugin.video.vikir
Je suis en train de mettre à jour le plugin fait par Majide (un dev d'addon).
Pour le moment je bloque à la signature de la licence.

**Comment by sviet2k** [comment]
Merci beaucoup @Arias800 .
Comme d'habitude, tu es vraiment génial 👍

**Comment by TmpName** [comment]
> Je serai d'avis de supprimer Viki de Vstream, car le maintenir à jour va être compliqué vu qu'il demande pas mal de paramètre spécifique pour Inputstream Adaptive et que ce serais compliquer à appliquer dans le fichier player.py de Vstream.

Je suis d'accord, vu la specificité, si en plus il a un addon a lui ...
