### ISSUE TITLE
NEWSLETTER DE VSTREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3496]
Si vous voulez avoir des Informations par E.Mail sur vStream, 
abonnez-vous à la Newsletter au https://xxxxxxxx/vstream

**Comment by sizanic** [comment]
Es-tu vraiment sérieux !???

**Comment by sizanic** [comment]
Tu viens ici sur le site officiel de vStream pour faire de la publicité vers un site que tu as créé pour diffuser tes versions modifiées de vStream !!!

**Comment by ludopotte** [comment]
Oui je suis sérieux et y'a pas que mes Versions de vStream dedans. J'ai créer cette Newsletter pour la Communauté. Apres si c'est pas valider par l'équipe tampis.

**Comment by sizanic** [comment]
Ton lien emmène vers ton github, ou tu proposes une version mobile de vStream :
_"vStream Mobile est la Version de l'Extension sur Kodi pour Android et iOS"_

Il y a un zip à télécharger.

Alors non, l'équipe ne valide pas.
Le seul zip officiel est sur ce github.

Et l'équipe n'a jamais développé une version spéciale pour mobile.
Donc nous ne savons pas ce qu'il y a dans ton zip.

Ce n'est pas la première fois que tu proposes des zip à télécharger sur ton github, et c'est **à chaque fois** la raison pour laquelle nous te demandons d'enlever tes messages.

Cela doit faire la 4eme fois.
Et tu retentes avec un nouveau site.
Mais cela ne change rien.
La raison est toujours la même.

Tu ne dois pas renvoyer vers un autre site qui permet de télécharger des fichiers non officiels !!!

**Comment by TmpName** [comment]
Pas mieux a repondre.
Mais pourquoi tu ne demandes jamais si c'est possible avant ?
