### ISSUE TITLE
Problèmes marque-page et Tirexo depuis version 1.9.3

### ISSUE THREAD

**Issue by Digidix** [Kodi-vStream/venom-xbmc-addons#3497]
Bonjour,

Encore une fois, merci pour cette mise à jour et votre travail sur Vstream, la rapidité de la dernière version est juste hallucinante, surtout sur des petits boîtiers TV !

Je me permets de soulever deux petits bugs, le premier est lorsqu'on ajoute une série en marque-page depuis la dernière version 1.9.3 (je n'ai pas testé la 1.9.1 ni la 1.9.2) avec Kodi Leia 18.9 sous CoreELEC et Aeon-Nox-SiLVO, je n'ai pas testé sur Kodi 19.

En effet, si on ajoute une série en marque-page, par exemple depuis Pastebin, et qu'on ouvre ensuite directement cette série dans marque-page, Vstream n'arrive pas à télécharger les métadonnées des épisodes, comme les notes, le titre et le synopsis de chaque épisode (le synopsis général de la série fonctionne toujours lui).

Par contre si les métadonnées sont déjà dans la DB, ça fonctionne.

Pour être un peu plus précis, ça donne quelque chose comme ça :

Je parcours les séries Pastebin (sûrement le même bug sur les autres sources), par exemple les plus populaires, je sélectionne une série au hasard, puis je sélectionne par exemple la saison 1, j'ai donc tous les épisodes de la saison 1 qui s'affichent avec toutes leurs métadonnées (en vue liste), le synopsis de chaque épisode, les notes, images...

Comme les métadonnées se sont affichées et viennent d'être téléchargées dans une DB, pour cette série et cette saison, si je sélectionne la série et que je l'ajoute en marque-page, j'aurais bien toutes les métadonnées de cette série et cette saison 1 dans marque-page.

Par contre, si par la suite je vide les caches de Vstream/Kodi et que je redémarre Kodi, lorsque je vais retourner sur cette série directement par marque-page, je n'aurais plus aucune info sur les épisodes.

Également, lorsque tous mes caches sont vidés et Kodi redémarré, si je parcours Pastebin et que j'ajoute une série en marque-page directement, sans être "rentré" avant dans la série pour voir les saisons et les épisodes, alors dans marque-page, il n'y aura aucune métadonnée sur les épisodes (puisque quand les métadonnées ne sont pas affichées et téléchargées depuis la source du lien, ici Pastebin, elles ne seront pas demandées par Vstream dans marque-page apparemment).

Du coup, est-il possible de faire quelque chose pour que les ajouts en marque-page fonctionnent comme si on avait le lien par la source elle-même ?

Les marque-pages ont toujours fonctionné un peu différemment, comme parfois, le synopsis de certains films ou les affiches ne sont pas les mêmes que via la source directe (encore une fois, je prends par exemple Pastebin, car je l'utilise le plus, mais le problème doit être présent sur les autres sources).

Si vous souhaitez reproduire ce bug, pensez bien à vider vos caches Vstream/Kodi et à bien redémarrer Kodi, car si vous avez des métadonnées déjà en place, vous n'aurez pas ce bug.

Le deuxième bug provient probablement de mon boîtier, mais dans le doute, je le mets ici :

Lorsque on sélectionne une série depuis la source Tirexo, souvent avant d'afficher les liens de la série, Tirexo est très long, et parfois le chargement ne s'arrête pas (même après 10 minutes), si j'essaye de faire un retour, ça fige le boîtier et je suis obligé de faire un reboot électrique du boîtier TV.

Cela le fait uniquement sur Tirexo, et uniquement sur les séries.

N'hésitez pas à me dire s'il vous faut plus d'information.

**Comment by sizanic** [comment]
Salut,
Tes remerciements sont appréciés.
Merci.

Pour les meta-données des séries en marque-pages.
Ta description est très clair.
Nous allons regarder 👍🏻 

Pour Tirexo, je pense qu'il sera de plus en plus difficile d'y naviguer facilement 😢

**Comment by alexlehay** [comment]
Salut digidix, 

Je pense que ton problème pour le deuxième bug ne vient pas de ton boîtier car j'ai exactement la même chose. Pour les films sous tirexo pas de soucis par contre quand je sélectionne une série, ça mouline à l'infini sans rien charger. Je n'ai pas d'autre solution que de forcer l'arrêt de Kodi pour re-avoir accès à l'appli. 

Alex

**Comment by TmpName** [comment]
Je viens de faire une modif sur tirexo, a tester si c'est mieux pour vous.
Moi ca bloque plus, mais le calcul est quand meme encore lourd.

**Comment by sizanic** [comment]
On n'aura plus de probleme avec TIrexo maintenant 😄 

Le soucis de metadonnées dans les marque-pages est réglé.

Fin du ticket.
