### ISSUE TITLE
Plus d'acces au depot vStream 

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#3498]
Le depot vStream n'est plus accesible pour installer vStream.

@Arias800 
le souci vient des dépendances vers ton github qui sont inscrites dans le dépot.
pour selenium et dnsPython

As-t'on toujours besoin de selenium ?
Peut-on heberger dnsPython ailleurs ?

**Comment by Arias800** [comment]
Tu peux supprimer selenium, et oui tu peux héberger dnsPython sur le git de Vstream.
C'est plus safe.
En fait, le problème vient du fait que j'ai fait du tri sur mon repo de test et j'ai supprimé un fichier qu'il ne fallait pas..

**Comment by sizanic** [comment]
On met juste le zip de dnsPython ici ?
https://kodi-vstream.github.io/repo/

Comment on fait ça ?

**Comment by Arias800** [comment]
C'est ici pour modifier les zip du site : https://github.com/Kodi-vStream/Kodi-vStream.github.io/tree/master/repo
Il faut générer un addon.xml et addon.xml.md5 pour DNSPython.
Et il faut aussi éditer l'addon.xml du repo pour qu'il pointe vers ces deux fichiers.

**Comment by sizanic** [comment]
on propose f4mTester-2.7.2.zip sur note repo.

On ne ferait pas la même chose, juste le zip ?

**Comment by Arias800** [comment]
L'objectif de base était qu'il s'installe automatiquement, d'où la procédure un peu longue.
Maintenant est-ce que ça marchait, je ne sais pas.

**Comment by sizanic** [comment]
je ne suis pas sur que ca fonctionnait :)

Maintenant la question est de savoir si on veut héberger le code source ou juste proposer l'addon dans le depot.

**Comment by Arias800** [comment]
Le code source est bien au chaud sur mon repo, donc pas utile de le bouger.

**Comment by sizanic** [comment]
Dépot à jour.
DNSPython s'installe maintenant depuis "installer depuis un zip" depuis le chemin github.
