### ISSUE TITLE
Les recherches sur Vstream bloquent 

### ISSUE THREAD

**Issue by Cetotomatix** [Kodi-vStream/venom-xbmc-addons#3499]
Bonjour. 
Depuis quelques jours, les recherches sur Vstream n’aboutissent plus. J’ai beau retirer les sources au fur et à mesure des blocages, ça ne résout pas mon problème et la liste des sources se réduit à peau de chagrin. 
Je n’en suis pas certain mais j’ai l’impression que les blocages sont aléatoires ou alors c’est l’ordre d’interrogation des sources qui est aléatoire. 
D’où le problème peut il venir ? DNS, FAI, url ? 
J’ai mis Kodi à jour pour voir si ça pouvait avoir une incidence mais rien de mieux. Et j’utilise ça sur une fire tv. 
merci pour votre aide

**Comment by sizanic** [comment]
Bonjour,

Si tu as bien une version 1.9 de vStream, tu devrais voir les sources qui bloquent la recherche, car la liste des sources interrogées apparaît maintenant pendant la recherche.
Et ce sont les dernières qui restent à la fin qui bloquent.

De plus, des messages d'erreur seront visibles au fur et à mesure des blocages, avec le noms des sources.

Si tu es confrontés à des blocages de DNS, le message sera également très explicite.
L’ordre d’interrogation des sources est toujours le même.

**Comment by Cetotomatix** [comment]
Bonjour,
Merci de la réponse. J’ai suivi tes recommandations et en effet je suis version 1.9.3 sur Vstream. 
j’ai beaucoup de messages disant que telle ou telle source est bloquée par cloudflare mais indépendamment de cela la recherche bloque et je n’ai d’autre choix que de forcer l’arrêt de l’application kodi puis de le relancer. 
Ça se présente ainsi : 

Résultat : 29
Sites restant : cinemay_cc, DpStream, DpStream HD, Extrême Down, ….. 10/41.

A chacun de mes essais, il reste 7 sites restant. En 3 essais, j’ai donc supprimé 21 sources. Il ne reste plus que 20 sources mais miracle, la recherche aboutit enfin. Elle est assez pauvre mais ça marche. 

Y’a t’il une explication à ces dysfonctionnements ? Des adresses qui changent ? Des sites qui ferment ? Mon installation déficiente ? 

Merci

**Comment by kdurand37** [comment]
Hello,

j’ai le même souci,
Peux tu me dire quelles sources tu as désactivées stp ?

**Comment by sizanic** [comment]
Avez-vous déjà changé les paramètres DNS de votre réseau.
Cela permet l'accès à plus de sources.

Exemple de tuto : https://www.phonandroid.com/changer-serveurs-dns-smartphone.html

Ou alors en installant l'extension DNSpython : 
Rendez-vous dans le menus Extensions de Kodi, puis "Installer depuis un zip". Sélectionner le chemin qui vous a servie à installer le depot de vStream, vous y retrouverez le fichier zip à installer :
 script.module.dnspython-1.12.1.zip

**Comment by kdurand37** [comment]
Merci pour le retour,

de mon côté j’ai bien installé DNSPython.
J’ai le même problème que @Cetotomatix les recherches se bloquent et je suis obligé de redémarrer Kodi. 
j'aimerais donc savoir comment régler le problème svp et quelles sources désactiver ? ;)

**Comment by sizanic** [comment]
Je pense à la source Psy-play ...

**Comment by kdurand37** [comment]
Les recherches bloquent toujours ;( a cause des sources cinemay, dpstream etc… comment faire ?

**Comment by sizanic** [comment]
Nous n'avons pas trouvé d'autre source bloquante que psyplay.

**Comment by Cetotomatix** [comment]
Bonjour tout le monde.

J’ai installé DNS python parce que j’avais beaucoup de messages d’erreur. C’est depuis cette installation que j’ai maintenant les messages cloudflare. Par contre, je ne l’ai pas installé depuis cette source mais je ne pense pas que cela ait une importance. 

Alors, voilà ce que j’ai désactivé :
Cinemay_cc, DpStream, DpStream HD, ExtremeDown, Free téléchargement, French-Stream lol, 4kstreamZ, Filmoflix, Hds-fm, Hds-stream, lanime, illimitestreaming, k-streaming, kepliz, k streaming film, libertyland, mes films, m’y stream, O1 streaming, psy play.

**Comment by kdurand37** [comment]
@Cetotomatix merci beaucoup pour ton retour !
@sizanic jai a peu près le même nombre de sources qui bloquent que @Cetotomatix… d’où cela peut il venir ? Pourquoi bloquent elles chez nous et pas chez toi ?

**Comment by sizanic** [comment]
Si une source est protégée par cloudflare, il faut installer un système qui contourne cette protection.
#3469 

Mais je conseille de désactiver ces sources car le contournement est lent. La source restera disponible en accès direct par le menu "Sources" mais ne sera plus utilisée dans la recherche globale.

**Comment by Cetotomatix** [comment]
Merci pour ces infos et pour ton aide Sizanic. Je vais garder mes messages Cloudflare 😉. Ça me dérange moins que de faire tourner un pc juste pour ça. 
Et merci pour le boulot que vous faites pour notre plaisir !! 👍

**Comment by sizanic** [comment]
Si tu ne veux pas contourner cloudflare, le mieux est donc de désactiver les sources protégées par cloudflare.
En plus de ne pas avoir les messages, les recherches seront plus rapides.

**Comment by Cetotomatix** [comment]
C’est vrai que ça serait mieux. Cependant une question, est ce que les sources protégées par cloudflare n’est pas une liste mouvante ou évolutive ? En fait, je me dis que si cette liste évolue, je peux très bien me supprimer des sources qui sont aujourd’hui bloquées mais ne le seront peut-être pas demain. Et de fait, je risque de finir avec zéro sources 😢

**Comment by sizanic** [comment]
Il y a 45 sources de films dans vStream.
Et sans doute seulement 5 sous cloudflare.
Ce qui peut arriver, est qu'il arrive que certaines de celles-ci enlèvent la protection quelques temps (mais ensuite ils la remette).

Et il peut arriver, il est vrai que certaines qui ne le sont pas encore, passent sous protections cloudflare. Mais je ne pense pas que cela concernera plus de 5 sources dans les 6 mois à venir.


Si pour l'instant tu n'enlèves que les 5 sources bloquantes, il t'en restera encore 40 !

Beaucoup de personnes laissent moins 10 sources actives en même temps. Tu as le temps de voir venir avant d'être à court de sources.

Surtout que d'ici 6 mois, on en aura remis 5 autres 😄

**Comment by Cetotomatix** [comment]
En fait, il ne me reste plus que 20 sources. Souviens-toi, j’ai du en supprimer 21 pour que la recherche ne bloque plus et j’en avais supprimé 4 il y a longtemps qui bloquaient aussi.
