### ISSUE TITLE
DEMANDE DE NEWSLETTER !

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3500]
Bonjour ou Bonsoir,

J'ai l'idée de créer une Newsletter (Lettre d'Informations) par rapport à vStream
pour que les Gens de la Communauté puissent avoir des Infos sur l'Extention
(Mise à jour, etc...). Est-ce que c'est possible avec l'accord de l'Equipe ?

Cordialement,
Ludo Potte

**Comment by sizanic** [comment]
Nous désirons garder qu'un seul canal de diffusion pour informer notre communauté : le discord.
