### ISSUE TITLE
Fonction recherche qui plante et freeze l'appli ou le firestick

### ISSUE THREAD

**Issue by blablabla1234567890123** [Kodi-vStream/venom-xbmc-addons#3502]
**Décrivez le bug**
Bonjour, depuis quelques jours, quand je cherche un film ou une série, cela plante vers la fin de la recherche (39/41 au niveau des sources) et ça me bloque soit l'appli (sur Mac) soit carrément mon FireStick, que je suis obligée d'éteindre et de redémarrer car il ne répond plus (il se met en veille). 
Même quand j'annule la recherche, cela ne change rien, cela freeze quand même et je suis obligée d'éteindre et rallumer le firestick. 
Tout le reste marche parfaitement, comme les recherches visuelles par exemple. 
Merci à vous pour ce gros travail que vous faites au quotidien !

**Votre system**
- OS: [Windows, Android] MacOS
- Appareil: [nvidia shield, Ultra] Mac et FireStick
- Version Kodi: [16.17.18] 19.4 Matrix
- Version Vstream: [1.7.0] 1.9.3

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

**Comment by sizanic** [comment]
Bonjour,

Il faut désactiver la source PsyPlay dans les paramètres.
C'est cette source qui bloque

**Comment by blablabla1234567890123** [comment]
Merci le problème est résolu !
