### ISSUE TITLE
Pas capable de configurer URLRESOLVER 

### ISSUE THREAD

**Issue by mannou78** [Kodi-vStream/venom-xbmc-addons#3503]
Bonjour,

Quand j'essaie d'aller configurer le URL Resolver dans Vstream, j 'obitens une erreur (Details de l erreur ci-dessous). Je suis sur Kodi Lea 18.9 Libreelect et j utilse la derniere version de Vstream 1.9.3

Merci !!

 Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'script.module.urlresolver'.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vstream/default.py", line 300, in <module>
                                                main()
                                              File "/storage/.kodi/addons/plugin.video.vstream/default.py", line 48, in __init__
                                                self.parseUrl()
                                              File "/storage/.kodi/addons/plugin.video.vstream/default.py", line 125, in parseUrl
                                                __import__('resources.lib.runscript', fromlist=['runscript'])
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/runscript.py", line 470, in <module>
                                                cClear()
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/runscript.py", line 41, in __init__
                                                self.main(sys.argv[1])
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/runscript.py", line 46, in main
                                                addon('script.module.urlresolver').openSettings()
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/comaddon.py", line 52, in openSettings
                                                return xbmcaddon.Addon(self.addonId).openSettings() if self.addonId else ADDONVS.openSettings()
                                            RuntimeError: Unknown addon id 'script.module.urlresolver'.

**Comment by sizanic** [comment]
Bonjouir,

tu essaies de configurer UrlResolver pour quel resolver ?

Il y a très peu de resolver qui nécessite de devoir configurer UrlResolver 🤔

**Comment by mannou78** [comment]
Bonjour,

J essaie d utiliser real-debrid pour avoir des liens plus rapides que ceux gratuits.

Quand je choisi configure URL Resolver dans VStream ca me donne une erreur.

Si je choisi URLResolver comme source dans les settings de VStream, aucun lien ne marche plus :(

Donc je veux associser URLResolver a VStream pour beneficier de liens plus rapides

Merci

**Comment by sizanic** [comment]
Real-Debrid ne se configure pas avec UrlResolver, mais directement dans les paramètres de vStream, dans l'onglet premium.

Tu l'actives et tu renseigne ton token
![image](https://user-images.githubusercontent.com/47307622/163693813-7288972a-8807-4421-bedb-86acbf7a99fe.png)

**Comment by sizanic** [comment]
Une fois que tu as renseigné ton token,
si tu veux vraiment des liens plus rapides, rend-toi dans la source Pastebin.

Sais-tu configurer cette source ?

**Comment by mannou78** [comment]
> Pastebin

Effectivement j ai effectue cette config mais les liens qui s affichent dans les sources sont encore bleus (au lieu de pink quand c'est un lien premium une fois urlresolve configure)

**Comment by mannou78** [comment]
> > Pastebin
> 
> Effectivement j ai effectue cette config mais les liens qui s affichent dans les sources sont encore bleus (au lieu de pink quand c'est un lien premium une fois urlresolve configure)

Non pas vraiment ca serait super gentil de  m expliquer comment ca marche dans VStream

Merci

**Comment by sizanic** [comment]
La source Pastebin est vide de contenu par défaut.
Il faut la configurer pour ajouter le genre de contenu désiré en ajoutant des codes.
Chaque code ajouté fera apparaitre des listes de contenus (films, séries, animes, sport, concerts, docs, etc...).

Pour cela, dans la section "gérer les codes", il faut créer des dossiers pour y ranger les codes.

On peut par exemple créer un dossier "Films" pour y ranger des codes de type Films.
etc.

Le groupe facebook "les alkodiques" est connu pour proposer un pack de codes tout prêt.

**Comment by alKODIque** [comment]
Je crois qu'il faudrait retirer la possibilité d'utiliser URLresolver de vStream, le procès légal intenté contre le développeur (TVaddons) est terminé et il a été jugé coupable.. depuis le verdict, il s'est complètement retiré et a fermé tous ses comptes en ligne dont le répertoire de URLresolver 🤷🏻‍♀️

Adioss tv-addons 😉

**Comment by TmpName** [comment]
Il y a les forks, par exemple https://github.com/Gujal00/ResolveURL

**Comment by alKODIque** [comment]
en fait, il y a longtemps que c'est devenu URLresolver qui était un fork de resolveURL..
-URLresolver reprenait nseulement le code de ResolveURL depuis plus de 3 ans...

**Comment by mannou78** [comment]
Merci tout le monde pour l interaction. Navre mais pas sur de comprendre est ce que les URLResolver n est plus supporte avec Vstream

Merci

**Comment by sizanic** [comment]
Ce qu'il faut comprendre c'est que ni UrlResolver ni ResolveURL n'ont un interet avec vStream.
Car vStream sait résoudre directement, en natif, les liens AllDebrid, RealDebrid et Uptobox.

Donc il n'y a aucun interet à utiliser un autre resolver.

De plus, se sont les plus utilisés sur les sites francais de streaming, et dont vStream propose les sources.

-> Utiliser ResolveURL pour résoudre quelle source ??

**Comment by sizanic** [comment]
CONCLUSION : 
Il ne faut plus utiliser UrlResolver.
Il sera enlever prochainement de vStream.

**Comment by sizanic** [comment]
@TmpName 
> Je pensais que des gens s'en servaient encore pour debrider par exemple uptobox ou onefichier (qui est pris en charge par Vstream mais sans debridage)

Que veux-tu dire par _"pris en charge mais sans débridage"_ ?

**Comment by TmpName** [comment]
Alors je ne m'en sert pas de mon coté, mais a l'epoque URLresolver prennait en charge les debrideurs. Du coup il y avait des gens qui avaient un compte alldebrid et s'en servait sur les autres sites (du coup sur 1fichier, mais sans avoir de compte 1fichier)

Du coups ma question est : Est ce que ResolveURL (https://github.com/Gujal00/ResolveURL)  (et non URLResolver qui est a l'abandon) les prend en charge ou pas ?

Il y a dans le code un fichier alldebrid, mais je ne m'en sert pas de mon coté et je n'ai pas de compte debrideur non plus.

**Comment by alKODIque** [comment]
mais c'est que urlresolver était inutile sans abonnement premium a un service de debrideur. et vatream prends maintenant en charge les debrideurs directement, sans intermédiaire

**Comment by sizanic** [comment]
>  il y avait des gens qui avaient un compte alldebrid et s'en servait sur les autres sites (du coup sur 1fichier, mais sans avoir de compte 1fichier)

Pour utiliser allDebrid (et debrider tous les liens avec, tel que des liens uptobox ou 1fichier), il suffit maintenant de renseigner son compte Alldebrid DIRECTEMENT dans vStream, sans passer par les paramètres de urlResolver.

Même chose pour l'utilisation du debrideur RealDebrid.

**Comment by TmpName** [comment]
Ok, ben je l'apprend ^^.
Jamais vu que Vstream supportait nativement Alldebrid et Realdebrid.
Donc effectivment ca apporte plus grand chose de plus.
