### ISSUE TITLE
Changement url pour wflx

### ISSUE THREAD

**Issue by Che-Debaras** [Kodi-vStream/venom-xbmc-addons#3504]
**Décrivez le bug**
 wflx a changé url ce n'est plus .cc mais .city

**Votre system**
- OS: [Windows &Android]
- Appareil: [PC & Android TV]
- Version Kodi: [19.3]
- Version Vstream: [1.9.3]

**Nous devons le reproduire**

- Nom du site: WFLX
- Titre du fim/serie: Tous
- Nom du host (openload/vidzi/...): tous

**Comment by TmpName** [comment]
Quelqu'un a deja du faire la correction https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites.json

**Comment by Che-Debaras** [comment]
Elle date de quand cette correction ? Car wflx ne donc plus depuis quelques jours

**Comment by TmpName** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/1f8b5eb0577930feec6f9ffd63dbcd46e2b34a7c

Peut etre un probleme de MAJ, je peux pas tester chez moi, j'ai la protection CF

**Comment by sizanic** [comment]
Mis à jour depuis plusieurs semaines. Mais protégé par cloudflare.

**Comment by Che-Debaras** [comment]
Sauf que avant la mise à jour wflx fonctionnais même avec le 1.9.2
Pour moi wflx était une fausse protection cf car on avait accès avec dns changé  maisJe pense que le problème viens des dernières mise à jour
Je vais tester avec les anciennes versions car wflx a toujours était sous CF et ça n'a pas empêché d'avoir accès sur android
