### ISSUE TITLE
Clone wflx

### ISSUE THREAD

**Issue by Che-Debaras** [Kodi-vStream/venom-xbmc-addons#3507]
Récemment wflx.city a des soucis , comme aujourd'hui Serait il possible d'avoir le cloné wflx.life en plus comme solution ?
Dans le même ordre d'idées que frnxhstrm ou dpstrm ou strmcplt  où ya 2 sources également 

Merci

**Comment by TmpName** [comment]
Ben le soucis c'est que ca ferait 2 fois la meme source.
Deja que les clones c'est pas franchement interessant, meme video proposées, les memes en pannes.

**Comment by Che-Debaras** [comment]
Oui mais c'est intéressant dans ce cas là car wflx a tendance à mettre CF en fonction des heures de la journée notamment en soirée donc mater un film ou série en soirée c'est impossible 
Alors que le clone lui n'a jamais de CF et c'est pas un simple clone je pense que c'est un site backup de wflx car il date depuis des années et ya jamais eu de 3e clone wflx
Évidemment même vidéo proposée et de même qualité c'est surtout ça qui est intéressant et sont jamais en panne ni sur la source original ni le clone.

C'est comme frnxhstrm, strmprvs ou dpstrm ou Zt, ta des doublons sur vstream car ce sont des sources très fournis en film série et qualité

J'insiste pas mais wflx est l'une des 2 ou 3 meilleurs sources fiable sur vstream,  j'aurai pas proposé cette source si elle en valait pas la peine.
Jamais je proposerais de clone de cinémay ou de zustrm etc.. que j'utilise jamais. J'utilise que 2 sources frnxhstrm et wflx et frnxhstrm à des clones sur vstream donc je me disais que wflx peur aussi en avoir 1.

Sur ce, si c'est pas possible,on peut clore ce sujet.
Merci d'avoir répondu.

**Comment by TmpName** [comment]
Ben si le clone est mieux, autant n'utiliser que le clone ?
C'est le meme site (uniquement l'url a changer) ou il faut aussi modifier tout les regex ?

**Comment by Che-Debaras** [comment]
Finalement laisser tomber ma proposition 
Je ne comprend pas pourquoi ce débat alors que d'autres source sont en double ou triple
Je clos le sujet

**Comment by sizanic** [comment]
Au moment où on est d'accord avec toi, que tu nous a convaincu, qu'on est prêt à développer la prise en charge du clone, qu'il n'y a donc plus de débat.

C'est ce moment-là que tu décides qu'il y a un débat et que tu clos le sujet 🤔 

Toujours ce souci de communication avec toi qui ne nous permet pas d'avancer convenablement, c'est bien dommage 😢

**Comment by Che-Debaras** [comment]
@sizanic je suis pas là pour débattre 
Trouve moi dans les messages répondu où vous êtes d'accord ?
Ce n'est pas un souci de communication mais de compréhension de votre part 
@TmpName dis qu'il ny a pas d'intérêt à avoir 2 sites identiques
Donc encore une fois vous aimez créer des débats la où y'en a pas
Si vous êtes d'accord dite le clairement 
En plus tu dis "on" comme si vous étiez nombreux mais j'ai eu qu'une réponse  et semble négatif

Donc arrête de voir des problèmes de communication car ma demande était simple et ça demande un oui ou un non que je n'ai pas lu

Donc si tu veux avancer convenable alors comprenez la demande et répondez clairement par oui ou non
J'ai quand même cité plusieurs sites clones sur vstream donc je vois pas où est le problème 

Bref je clos car visiblement quand il s'agit de mes demandes c'est directement refoulé 
Donc merci je demanderais plus rien

Bye

**Comment by sizanic** [comment]
![image](https://user-images.githubusercontent.com/47307622/165000889-3f5a0e71-3059-4641-901a-3fcc97e0adf5.png)



>  tu verras que ya qu'une personne qui a répondu

Oui, je vois bien qu'il y a qu'une personne qui a répondu. Et alors, ce n'est pas suffisant pour toi ?

**TU VOULAIS L'ACCORD DE COMBIEN DE PERSONNES POUR ETRE CONSIDÉRÉES AU SÉRIEUX ?**

> je ne vois pas d'accord pour la demande de développer ce clone 

La réponse de TmpName, est de te dire : 

> Donc si le clone est mieux, autant utiliser que le clone ?

Cela veut dire qu'il est convaincu par tes arguments, le clone semble mieux, et qu'il est intéressé par le développement de ce clone.

**CE N'EST PAS UN ACCORD ASSEZ EXPLICITE POUR TOI ?**

Puis il essaie d'établir un échange avec toi en te posant des questions, afin de mesurer le travail à réaliser pour développer ce clone.
Pour savoir si tu as poussé un peu plus l'analyse de ce clone.

- Est-ce qu'il a un inconvénient ?
- Est-ce que pour toi il ne s'agit que d'un changement d'url ou aussi de l'aspect du site ?

Mais ta réponse est de dire que personne ne te répond et qu'on veut débattre.

Alors qu'on te dit qu'on veut faire le clone, on veut tellement le faire qu'on veut même arrêter de maintenir la source originale et ne garder que ce clone.


C'est vraiment fatiguant que je sois obligé de faire une explication de texte pour te montrer cet accord de TmpName.
=> donc tu as une réponse et un accord !!

> surtout un problème de compréhension vu que tu comprend pas trop les messages.

@TmpName 
- tu as bien répondu ? Oui ou non
- Tu paraissais plutôt d'accord dans ta réponse pour développer ce clone ? oui ou non
- Est-ce que je n'ai vraiment pas compris les messages, j'ai un problème de compréhension et j'ai tout faux dans ma lecture de ta réponse ? Oui ou non

**Comment by sizanic** [comment]
ok, merci de ton retour.

Donc tu confirmes que je n'étais pas _**"hors-sujet"**_.
Je ne faisais donc pas ça pour me _**"défouler"**_.
Il n'y avait pas de ma part un _**"problème de compréhension"**_, vu que je ne **_"comprend pas trop les messages"_**.

Cela voudrait dire que je n'étais pas en train de **_"troller"_**.

Si tout cela est incorrect, cela voudrait dire aussi que finalement, je ne suis pas **_"pathétique"_**.

Si quelqu'un maintenant se sent de faire des excuses, et admettre que c'est lui qui ne comprend pas ce qu'on lui dit, on lui pardonnera son agression gratuite.

**Comment by Che-Debaras** [comment]
Sérieusement @sizanic tu le fais exprès pour avoir le dernier mot et encore troller 
Ce que tu dis n'a vraiment aucun sens 
Tu es dans un délire monologue où tu es complètement hors sujet 

Tu a bu ou fumer avant de répondre?

Celui qui doit s'excuser c'est bien toi et vu ton troll et défoulement et msg incompréhensible on voit bien que tu es pas dans ton état normal
Donc sois tu t'excuse d'avoir dit des conneries sans avoir lu et compris les messages soit tu cesse de répondre car j'ai bien clos le sujet

Donc lâche l'affaire car encore une fois à la même période tu t'acharne sur la même personne ça  deviens un rituel chez toi mdr

Donc oubli moi et mes messages , on stoppe la et chacun continue sa vie car pour moi ya bien longtemps que je n'attends rien de ta part.

Sur ce débat clos inutile de répondre sauf si tu veux continue ton troll ou recevoir encore mes réponses pour te remettre en place donc cesse de relancer ce faux débat 

Adios
