### ISSUE TITLE
EXTENSION VSTREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3509]
Pour Installer vStream sur Kodi facilement, vous pouvez directement sur
Ordinateur, Android/Android TV et iOS au https://31u1.short.gy/vstreamkodi

**Comment by sizanic** [comment]
Pourquoi proposer une méthode d'installation alternative ?

Notre méthode officielle, que nous documentons sur notre site officiel, n'est-elle pas assez simple ?
https://kodi-vstream.github.io/docs/installation2/

Ici, tu rediriges les gens vers un emplacement que tu es le seul à administrer.
Aucun développeur vStream ne peux administrer cet espace.
Nous ne sommes pas à l'abri que tu y déposes un jour du contenu qui n'est pas officiel à vStream (une version "patch" ou une une version "mobile" 🤔 ).

**C'est toujours non**

Merci de ne pas venir ici faire de la publicité vers des emplacements qui proposent du contenu que tu es le seul à administrer.

**Comment by shnorbluk** [comment]
Bonjour, je suis intéressé par votre méthode officielle. Auriez-vous un lien vers une page qui explique comment procéder? Merci

**Comment by sizanic** [comment]
Bonjour,
voici la doc officielle d'installation de vStream : https://kodi-vstream.github.io/docs/installation/

A noter qu'il est important aussi, à l'étape d'installation du dépot, d'installer également le module "script.module.dnsPython."

A retrouver ici, le tuto en vidéo par notre partenaire "les alKODIques" : 
https://vimeo.com/showcase/9615079
