### ISSUE TITLE
ExtremeDown

### ISSUE THREAD

**Issue by lebigboss** [Kodi-vStream/venom-xbmc-addons#3510]
**Décrivez le bug**
Bonjour, savez-vous pourquoi on ne peut pas accéder aux épisodes des séries quand cloudflare est activé ?

**Votre system**
- OS: Android
- Appareil: NVIDIA Shield 
- Version Kodi: 19.3
- Version Vstream: 1.9.3

**Nous devons le reproduire**
- Nom du site:  ExtremeDown

**Comment by yodidon** [comment]
Sur quelle source.

**Comment by sizanic** [comment]
Je viens de tester avec la nouvelle adresse, et on ne peux toiujours pas voir les épisodes.

Une petite correction à faire de notre côté :

2022-04-26 18:42:38.326 T:10988   ERROR <general>:   File "\resources\sites\extreme_down.py", line 575, in showSeriesLinks
                                                       sDisplayTitle = ('%s (%s)') % (sTitle, sQual)
2022-04-26 18:42:38.326 T:10988   ERROR <general>: UnboundLocalError: local variable 'sTitle' referenced before assignment

**Comment by sizanic** [comment]
ça devrait être mieux maintenant.

**Comment by lebigboss** [comment]
@sizanic  Je ne comprends , pour moi rien n'a changer loll
si tu as une méthode secrète

**Comment by sizanic** [comment]
Avec la bêta ?

**Comment by lebigboss** [comment]
@sizanic  Oui avec la bêta, je sais pas si ça fonctionne chez toi mais en faite chez moi c'est comme avant .
Impossible d'ouvrir une série.

**Comment by sizanic** [comment]
En effet, petite boulette de mon côté 😄 

ça devrait être mieux maintenant.

**Comment by lebigboss** [comment]
@sizanic Bizarre, pour moi rien à changer loll désolé

**Comment by Che-Debaras** [comment]
Au pti con @sizanic 
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by lebigboss** [comment]
C'est bon, les épisodes fonctionnent merci @sizanic

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by arzaz** [comment]
Bonjour,
Merci de confirmer si ExtremeDown a changé d'adresse ? Car impossible d'y acceder avec FlareSolverr

**Comment by arzaz** [comment]
Voici l'erreur sur FlareSolverr

2022-05-21T12:00:59+01:00 INFO REQ-3 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://www.extreme-down.io/films-new-hd/","session":"361b03d0-d8f5-11ec-abea-e5413c0ed1d0","postData":""}
2022-05-21T12:01:15+01:00 INFO REQ-3 Cloudflare detected
2022-05-21T12:01:56+01:00 INFO REQ-3 Challenge solved
2022-05-21T12:01:59+01:00 ERROR REQ-3 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=60000 (ms)

**Comment by sizanic** [comment]
Plus de nouvelle d'extrem-down ;(
