### ISSUE TITLE
Proposition Site pour Vstream 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#3511]
Bonjour la Team alors voilà j ai plein de site pas mal pour nous 
Je vous laisse voir 

htt ps://ww w.annuaire-telechargement.club/
ht tps://ww w.wawacity.blue/
ht tps://w ww.zone-telechargement.click/
ht tps://ww w.tirexo.cam/ ( vue que tirexo est mort) 
htt ps://animeko.co/ pour les animes 
ht tps://w ww.free-telecharger.xyz/

merci la team

**Comment by lebigboss** [comment]
Bonne proposition. Tu en ferme un, il y en dix qui ouvre derrière loll

**Comment by yodidon** [comment]
Je regarderais

**Comment by ludopotte** [comment]
Bonjour,

Voici ma Liste de Nouveaux Site pour vStream si dessous : 

Tirexo Officiel au https://tirexo.buzzfil.org/

Zone Telechargement au https://www.zone-telechargement.click/

**Comment by lebigboss** [comment]
Je pourrais ajouter le site
papflix.com
Il a des liens streaming mais aussi des liens uptobox

**Comment by yodidon** [comment]
> Je pourrais ajouter le site
> papflix.com
> Il a des liens streaming mais aussi des liens uptobox

Commencer mais pas si facile à finaliser pour moi …

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by yodidon** [comment]
> Je pourrais ajouter le site
> papflix.com
> Il a des liens streaming mais aussi des liens uptobox

Encore un soucie avec les hoster de séries à régler pour terminer
