### ISSUE TITLE
Bug Menu Trakt Films/Séries

### ISSUE THREAD

**Issue by Rygo92** [Kodi-vStream/venom-xbmc-addons#3512]
Bonjour,
Lorsque je vais dans le menu :
Mes comptes / Trakt / Films ou Séries
Je n'ai que la première ligne Collection et rien d'autre. 
J'ai désinstallé réinstallé vStream, pareil.
J'ai déconnecté reconnecté mon compte trakt, pareil. 
Je mets en copie un screen de mon cas, ainsi qu'un screen d'une configuration d'un membre sur Discord qui a le menu complet.
Merci. 
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/8584523/kodi.log)

![image](https://user-images.githubusercontent.com/77703379/165797934-ef2cdf54-8f36-47a2-b793-c67f3227097d.jpeg)

![image](https://user-images.githubusercontent.com/77703379/165797968-8549e9ec-bda4-468f-ab53-f29f85330122.png)

**Comment by Rygo92** [comment]
#bide

**Comment by alKODIque** [comment]
@Rygo92 
Regarde sur ton compte trakt si tu n'aurais pas réglé des trucs en privé par hasard..
Ca m'est déjà arrivé pour des listes et ça en était la cause

**Comment by alKODIque** [comment]
Il me semble que c'était dans la section dashboard des paramètres... tout en bas (mais pas certaine)
Il ne faut pas cacher ces éléments de menu:
![trakt](https://user-images.githubusercontent.com/49578130/166227805-ef3d88f4-25aa-430e-bd06-5db09637f896.png)

**Comment by Rygo92** [comment]
> Il me semble que c'était dans la section dashboard des paramètres... tout en bas (mais pas certaine)
> 
> Il ne faut pas cacher ces éléments de menu:
> 
> ![trakt](https://user-images.githubusercontent.com/49578130/166227805-ef3d88f4-25aa-430e-bd06-5db09637f896.png)
> 
> 

Merci pour ta réponse Julie. Je viens de vérifier dans les paramètres et je n'ai aucune de ces cases de cochées donc je pense que le problème est autre 😔

**Comment by alKODIque** [comment]
et tu as le même compte trakt sur tous tes appareils ?

Tu as un souci étrange... et d'habitude, je me plaisais a dire que ces soucis étranges n'arrivaient qu'a moi 📦 Du coup je me sens moins seule loll

(Mais ca ressemble vraiment a un souci de partage public / confidentialité)... faudrait peut-être voir si la config est ailleurs que dans ce que je t'ai suggéré alors)

**Comment by alKODIque** [comment]
j'ai vu ton log..
On dirait que ton compte vceut pas s'inscrire dans la mémoire
Ligne 428: `ERROR <general>: <generator object path at 0x28575b4a30>`

As-tu autorisé l'accès en écriture sur ton kodi ?

**Comment by Rygo92** [comment]
> j'ai vu ton log..
> 
> On dirait que ton compte vceut pas s'inscrire dans la mémoire
> 
> Ligne 428: `ERROR <general>: <generator object path at 0x28575b4a30>`
> 
> 
> 
> As-tu autorisé l'accès en écriture sur ton kodi ?

Alors j'ai essayé avec le skin de base et pareil, que la ligne collection. 

Concernant l'accès en écriture, j'ai jamais touché à ce paramètre, dis moi ou il se trouve que je vérifie ? 

Merci en tous cas d'essayer de trouver le problème, je me passerai bien de te battre dans le domaine des bugs paranormaux 😂

**Comment by alKODIque** [comment]
Je suis pas devant l'écra... mais je l'ai indiqué quelque part sur ce tuto, tu devrais trouver facilement: https://wiki.lesalkodiques.com/docs/guide-de-depart/reglages-de-base/

**Comment by alKODIque** [comment]
Case 2 et 3 !
![tuto](https://user-images.githubusercontent.com/49578130/166332742-3112306c-1f10-48d9-b867-c990a787116d.png)

**Comment by Rygo92** [comment]
> Case 2 et 3 !
> 
> ![tuto](https://user-images.githubusercontent.com/49578130/166332742-3112306c-1f10-48d9-b867-c990a787116d.png)
> 
> 

Effectivement ces 2 cases n'étaient pas cochées mais même après avoir vider le cache et redémarré, toujours pareil 😩

T'embêtes pas plus, merci déjà d'avoir passé du temps sur le souci 😊

**Comment by alKODIque** [comment]
:(

**Comment by alKODIque** [comment]
Bref,
si tu réussis a régler, ca m'intéresse de connaître ce qui se passait..
(peut-etre un paramètre de ta box alors.. car ton bug c'est vraiment comme si tu n'avais pas le droit d'écrire dans ton dossier)

**Comment by sizanic** [comment]
Le log me fait plutot penser qu'il manque un fichier.
Peut-être qu'une réinstallation est nécessaire.

**Comment by alKODIque** [comment]
ouais... ERROR <general>: name 'FileNotFoundError' is not defined

**Comment by Rygo92** [comment]
> Le log me fait plutot penser qu'il manque un fichier.
> 
> Peut-être qu'une réinstallation est nécessaire.
> 
> 

Il n'y a que ce menu qui déconne, ça m'aurait fait plaisir qu'il fonctionne normalement mais je t'avoue que je vais pas tout réinstaller pour ça avec en plus le doute que ça change rien 😂

**Comment by sizanic** [comment]
pas tout réinstaller, juste réinstaller trakt par dessus ton installation. en forçant une mise à jour de l'addon par exemple.

**Comment by alKODIque** [comment]
Mais pourquoi installer l'addon trakt? c'est seulement l'API depuis vStream qui est demandé non ?
on peut ne pas avoir l'addon trakt et seulement utiliser l'intégration avec un addon...

**Comment by sizanic** [comment]
ah oui, je me suis perdu. On parle de trakt intégré dans vStream 😸

**Comment by breizhou13** [comment]
J'ai eu ce soucis dernierement et j'ai reinstallé Kodi 4 fois....Et puis d'un coup ca a marché....
Jen'ai aucune explication du pourquoi du comment

**Comment by Rygo92** [comment]
> J'ai eu ce soucis dernierement et j'ai reinstallé Kodi 4 fois....Et puis d'un coup ca a marché....
> 
> Jen'ai aucune explication du pourquoi du comment
> 
> 

Merci pour ta réponse. Bon je t'avoue que j'aimerai bien avoir ce menu mais pas au point de réinstaller le tout 4 fois et sans la certitude que ça fonctionne 😂

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)
