### ISSUE TITLE
Au pti con de @sizanic

### ISSUE THREAD

**Issue by Che-Debaras** [Kodi-vStream/venom-xbmc-addons#3513]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by sizanic** [comment]
😂😂😂
Elle était bien bonne !

Tu sais qu'en signalant nos échanges à Github c'est toi qui risque d'être banni ?
Car j'ai le droit de faire ce que j'ai fait, mais toi tu n'as pas le droit d'insulter 🤔

**Comment by Che-Debaras** [comment]
Mdr mais j'en ai rien à foutre d'être banni
Et je T'ai signalé pour avoir usurper mon compte et laisse des messages à ma place
Donc tkt pas que tu as plus à perdre 

Où t'as le droit de usurper un compte pour écrire des messages à notre place?
Tu es vraiment trop con , tu ne peux pas écrire des conneries ala place du propriétaire du compte

Donc je t'ai signalé et on verra bien

A ta place je supprimé ce que tu as édité

**Comment by Che-Debaras** [comment]
@sizanic je peux comme tu vois faire le con donc je t'invite à retirer ce "désolé" si tu veux que cela cesse

**Comment by Che-Debaras** [comment]
> Je n'ai pas usurpé ton identité. J'ai édité ton message avec mon identité. Ce n'est pas pareil. Même toi tu as entouré mon nom, donc tu vois bien que c'est mon identité que j'ai utilisé, pas la tienne. Et ça j'ai le droit. Tu t'es cru sur un réseau social 😄
> 
> Je parlais du banissement que tu risques par le signalement que tu as fait au support github. Tu vas te bannir tout seul. Arroseur arrosé 😂

Non tu n'as pas le droit te faire passer pour moi

Je m'en fout d etre banni

Mais je n'ai pas écrit je suis désolé ça c'est toi qui l'a écrit parce que tu voulais mes excuses que j'ai refusé 

J'ai bien dis le débat clos mais tu as fait le con en mettant ce mot désolé pour faire croire que je suis désolé et au final regarde ce que ça a apporté 

J'ai entouré ton nom à la con pour montrer que c'est toi qui a édité ce message

Tu vois comment tu es con, tu écrit avec ton identité des excuses pour faire croire que c'est moi qui m'excuse 

Faut vraiment être con pour faire ça,  tu t'es senti mieux après avoir écrit ce désolé à ma place?

Tu vois tu fous la merde avec tes conneries de gamins et non seule tu comprends pas les commentaires mais en plus tu comprends pas les connerie que tu fais.

Crois moi que les devs partent à cause de toi , ce n'est pas une coïncidence donc grandi un peu et je pourrais te demander des excuses mais j'en ai rien à foutre 

Mais si tu veux que cela cesse retire ce "désolé"

**Comment by Che-Debaras** [comment]
> Mais tu le fais exprès ? Je ne suis pas con d'avoir laissé mon nom puisque je te dis que je n'ai pas usurpé ton identité et que j'ai intentionnellement laissé mon nom, car je revendique la modification du message 😹
> 
> Aucun dev n'est partie à cause de moi. J'ai fais rentré plus de dev qu'il en est partie d'eux-mêmes.
> 
> C'est dans ta tête si tu penses que je suis la cause de tout tes problèmes.

Mdr c'est toi qui est con vu que justement tu revendique ta connerie 
De toute façon c'est pas toi mais le site qui affiche la personne qui réédite avec le nom
Donc ne dis pas que c'est toi qui l'a laissé car tu n'as pas le choix 

Et encore une fois car tu es con je te réexplique, le problème c'est pas ton nom mais ta connerie d'avoir modifié mon message pour faire croire que je suis désolé 

Donc à cause de ça tu as créé tous ce spam et visiblement tu semble être fière de ta connerie. Donc soit faire de ce spam et de ces problèmes 

Et c'est à cause de toi que ces devs partent car tu fous la merde 

Mdr tu es vraiment con, car pour infos les pensées d'une personne c'est forcément dans sa tête lol

Et c'est malheureusement l'inverse c'est toi qui me prend pour cible pour la cause de tout tes problèmes puisque chaque année a la même période tu me trolle tu te défoule sur moi

Donc  on peut débattre des heures mais vu les connerie que tu dis on voit que tu est plus cons que ce que je pensais 

ICI LE PROPRIÉTAIRE EST SIMPLE : 
TA OUVERT TA GRANDE ALORS QUE TU AURAIS PAS DU
TA CHANGER MON COMMENTAIRE ALORS QUE TU AURAIS PAS DU
DONC  TU AURAIS DU FERMÉ TA GUEULE PLUTOT QUE D'INTERVENIR 

DONC SI TU ES PAS SI CON TU SAIS CE QUI TE RESTE A FAIRE POUR METTR ME FIN A CE PROBLÈME 

1: TU EXCUSE 
2: TU RETIRE CE MOT "DÉSOLÉ "

MAIS VU QUE TU ES CON TU VAS CONTINUER CETTE CONNERIE
