### ISSUE TITLE
comment contourner les limite de temps uptobox uptostream sur kodi

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#352]
En effet il existe un programe Datho VPN SUR KODI xbmc , qui vous permet de changer votre adresse ip au monment ou vous trouvez un message qui indiqueque vous avez obtenu le délai du temps alouer exp: x???minute avec ce vpn sans telechargement vous contournerez cette limite- appres instalation choisire une localisation kodi__program__Datho VPN jusqua votre video débloque  

1_ instaler OpenVPN sur votre appareil
2_ instaler Datho VPN 
     https://codeload.github.com/datho/datho-xbmc-repo/zip/master
     installer tout les fichiers repo (sous la dernière version)
3- inscription sur le site Datho VPN
    http://www.dathovpn.com/

![sans titre](https://cloud.githubusercontent.com/assets/11494048/14630938/0ebb3188-0611-11e6-8cd2-16f2e85c18b7.png)
![sans titre01](https://cloud.githubusercontent.com/assets/11494048/14630948/210d849e-0611-11e6-8537-f3806c9ce805.png)
![sans titre02](https://cloud.githubusercontent.com/assets/11494048/14630959/2fe546b4-0611-11e6-8453-6c5839311379.png)

**Comment by jojotango** [comment]
Intéressent cette astuce Datho VPN propose gratuitement un debit de 800 kb/s faut voir si le débit proposé est bien respecté.

**Comment by chicungunya** [comment]
De mon coté ça ne marche pas.
J'ai essayé plusieurs Pays, plusieurs villes mais je n'ai jamais la fenêtre Using date free servers.

**Comment by LordVenom** [comment]
@mino60  Tu peux faire un tuto au propre dans le Wiki que je fermer cette conversation.
