### ISSUE TITLE
bug uptostream 

### ISSUE THREAD

**Issue by tobal37** [Kodi-vStream/venom-xbmc-addons#3789]
**Décrivez le bug**
 Je voulais vous signialer un souci au niveau vstrem premium login uptobox si il et en mode proposer les deux mode sa rajouté des film et sa fait des bootloop sur les film souci que @crunch  et @tiiiit_74  quand  c en mode direct via uptobox pas de souci pouvez vous réparer sa ou mettre ke en mode direct uptobox pour tout le monde afin de ne pas avoir des souci avec sa 

**Votre system**
- OS: [tout systeme]
- Appareil: [apareil divers]
- Version Kodi: [latest]
- Version Vstream: [latest]

**Comment by Che-Debaras** [comment]
@sizanic 
Les personnes s'énervent lol 
Tu attends quoi pour corriger le commentaire

**Comment by poiluepistache** [comment]
oh mais ferme ta gueule vraiment tu t'enfonces encore plus! Ta quel âge pour être aussi gamin ???

**Comment by Che-Debaras** [comment]
> oh mais ferme ta gueule vraiment tu t'enfonces encore plus! Ta quel âge pour être aussi gamin ???

Vous vous acharnez sur la mauvaise personne
Il suffit juste que @sizanic corrige le commentaire qu'il a modifié 

Énervez vous etc... quand je serai le commissariat corrigé ou supprimé alors j'arrêterais

POUR INFOS JE SUIS INSOMNIAQUE DONC ÇA VA DURER TOUTE LA NUIT

**Comment by sizanic** [comment]
En effet, j'arrive à la reproduire ...

**Comment by tiiiit74** [comment]
C'est une option qui a été ajouté récemment ? Car je ne l'avais jamais remarqué, on a bien galéré avec Crunch et je suis content d'avoir résolu le souci. Merci @tobal37 d'avoir fait remonté.

**Comment by sizanic** [comment]
L'accès aux flux uptostream (pour avoir accès à des résolutions plus basses), n'est pas nouveau.

Je ne vois pas ce qui a changé. Peut être le format vidéo 🤔
C'est de l'adaptive inputsream, je ne maîtrise pas 😥

**Comment by tiiiit74** [comment]
Au final ce qui est "nouveau", c'est que ça a basculé tout seul sur cette option sans qu'on intervienne, maintenant qu'on a compris c'est déjà plus facile de répondre. Et peut-être allez-vous réussir à forcer le paramétrage. Rien de grave.

Etonnamment sur le groupe TMDb de Alko, presque en même temps, elle en a parlé. C'est donc un problème très récent. Bon courage.

**Comment by sizanic** [comment]
C'est à l'utilisateur de choisir son option, nous ne l'avons pas basculer et nous n'allons pas le forcer.
Ce qui est nouveau est peut-être le format du flux vidéo retourné par uptostream.

**Comment by tobal37** [comment]
Et si on install l extantion imput stream adaptative il se passe koi

**Comment by sizanic** [comment]
J'ai essayé mais pas réussi à aller plus loin. Mais je vous propose d'essayer de votre côté.

**Comment by tobal37** [comment]
sa marche pas

**Comment by Che-Debaras** [comment]
> J'ai essayé mais pas réussi à aller plus loin. Mais je vous propose d'essayer de votre côté.

Tu as cru te débarrasser tu problème ? Mdr j'attends tes excuses si tu veux que ça cesse

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by Che-Debaras** [comment]
Dis moi @Sizanic

D'où tu te permet de modifier mes messages pour avoir misérablement mes excuses?
Je t'ai bien précisé que je suis désolé de rien et je vais pas m'excuser devant un con comme toi

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3507#issuecomment-1109809789

Je te conseille de retirer ce "désolé" que tu a rajouté sans ma permission et de ne plus changer les messages des autres.

Je suis pas là pour débattre donc je t'invite petit conn et oui je suis vulgaire car ton pti jeu de merde de troll ou de dictateur et de frustré commence à m'énerver un peu.

T'as toujours foutu la merde par tes interventions hors sujet et cons mais la modifier un message pour faire croire que je suis désolé c'est que tu es tombé bien bas.

Tu peux pas t'empêcher de chercher les disputes pour donner un sens à ton pathétique existence et tu t'es toujours à cette période de l'année défouler sur moi.

Donc s'il te reste un atome de bon sens de dignité et de fierté je te conseille de supprimer ce mot que tu as rajouter 

Car que ce soit clair je serais jamais désolé pour un con qui ne comprend pas le français,  ne comprend pas les commentaires et s'amuse à faire des embrouilles là où y'en a pas.

Je T'ai signalé au support github que tu te permet de usurper l'identité des utilisateurs pour poster des faux messages  à leur place.

Ne répond pas @sizanic juste supprimé ce que tu a ecrit

Il prend les personne pour des cons en faisant croire que je me suis excusé,  si ce n'était pas pathétique 

![Screenshot_20220509-131209_Samsung Internet](https://user-images.githubusercontent.com/93712803/167398494-ec7e271b-7ec8-4121-beaa-11fb18effbdc.jpg)

**Comment by sizanic** [comment]
La dernière Version 2.4.0 de vStream corrige l'acccés aux flux upToStream
