### ISSUE TITLE
Librairies Vstream

### ISSUE THREAD

**Issue by mbencherifa2005** [Kodi-vStream/venom-xbmc-addons#38]
Hi
I have installed  vstrean 0.2.5 on Kodi 14.0. so when I try to lunch this addon , I get script error. eryone did  tested on this version of xbmc.

thanks

**Comment by LordVenom** [comment]
re,

Voila la liste completes

script.module.metahandler
xbmc.python
script.module.urlresolver
script.module.simplejson
script.common.plugin.cache
script.module.parsedom
plugin.video.youtube

et Sqllite 3 pour l'historique en option donc.

**Comment by ggkameleon** [comment]
Salut LordVenon est-ce qu'il serait possible de rajouter Bbtv dans la liste TELE ? Je sais qu'il y à sur les box android Tv L'application (pas celle pour tablette) qui fonctionne ! Moi j'ai une ATV2 et vu que Angelscry à arrêté sont Addons Télé.fr je souhaiterais pouvoir accéder à mes chaînes Tv de ma Box Bouygues ? Merci
