### ISSUE TITLE
Proposition d'améliorations sur vStream/Compte/TMDB

### ISSUE THREAD

**Issue by doctornono** [Kodi-vStream/venom-xbmc-addons#3902]
Bonjour à tous,

J'utilise la section Comptes/tmdb de vStream mais les actions de Noter un film, Ajouter/retirer un film des favoris ou de la watchlist (dans le menu contextuel tmdb) ne fonctionnent pas.

Voilà, un petit correctif qui rend ces actions fonctionnelles.

# vStream TMDB

<aside>
📌 Fichier : resources/lib/tmdb.py

Ajout de cette méthode à la suite de la méthode getUrl (ligne 1100)

Cette méthode est appelée depuis resources/sites/themoviedb_org.py (ligne 280) alors qu’elle n’existait pas

</aside>

```python
def getPostUrl(self, url, post):
        # Execute une requete POST vers l'API
        # Utile pour :
        #       - Noter film
        #       - Ajouter/Retirer le film des favoris
        #       - Ajouter/Retirer le film de la watchlist
        # Appelé depuis le menu contextuel TMDB
        #
        # Paramètres :
        #   url : le complément de l'url de l'api
        #           ex : '/movie/{movie_id}/rating' pour noter un film
        #           ou : '/account/{account_id}/favorite' pour ajouter aux favoris
        #   post : json qui sera envoyé Request Body
        #           ex :   {
        #                   "value": 8.5
        #                  }

        from urllib import request
        session_id = self.ADDON.getSetting('tmdb_session')

        urlapi = self.URL + url +'?api_key='+self.ADDON.getSetting('api_tmdb')+'&session_id='+ session_id
        
        req = request.Request(urlapi, method="POST")
        req.add_header('Content-Type', 'application/json')
        data = json.dumps(post)
        data = data.encode()
        r = request.urlopen(req, data=data)			
        response = r.read()
        r.close()
        data = json.loads(response)
        return data
```

<aside>
📌 resources/sites/themoviedb_org.py

Modification d’une ligne 270 : numboard = dialogs.numeric(0, 'Min 0.5 - Max 10') qui ne fait pas apparaitre le dialog numeric
```python
#Ligne 270
#numboard = dialogs.numeric(0, 'Min 0.5 - Max 10')
numboard = dialogs.DIALOG.numeric(0,'Min 0.5 - Max 10')

**Comment by sizanic** [comment]
Merci pour ta proposition, on va regarder ça 👍🏻

**Comment by doctornono** [comment]
Tu as vu, je te spamme ici maintenant ;-)
Si ca plait, je peux voir pour ajouter la création d'une liste tmdb et l'ajout de films à une liste utilisateur

**Comment by sizanic** [comment]
Oui, j'ai vu.
Et j'ai vu que tu n'as pris en compte aucune de mes propositions 😄 

1- utiliser dialog().numeric de comaddon
2- passer par une pull Request

Mais c'est pas grave, avance comme tu veux 👍🏻

**Comment by doctornono** [comment]
J'ai modifié par dialog.numeric.
Concernant le pull Request, je ne connais rien à github...

**Comment by sizanic** [comment]
Pour la pull Request, tu te rends sur le fichier : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/themoviedb_org.py

Tu passes en édition avec le stylo, et tu modifies directement le fichier.
Cela va créer tout seul une Pull Request : ta modification est soumise aux développeurs qui peuvent l'accepter ou la modifier ou apporter des commentaires dessus.

**Comment by doctornono** [comment]
Voilà, c'est fait , merci pour l'info

**Comment by sizanic** [comment]
Je ne suis pas sûr 🤔
Rien ici : https://github.com/Kodi-vStream/venom-xbmc-addons/pulls

**Comment by TmpName** [comment]
Oui on peut voir ton fork, mais la derniere modif visible c'est celle de Sizanic pour Uptobox.

**Comment by doctornono** [comment]
![image](https://user-images.githubusercontent.com/44597041/168479182-c6d3de39-de5e-4876-a333-69fb57cfa043.png)

Voilà, j'ai fait comme demandé @TmpName. C'est bon comme ça ?

**Comment by TmpName** [comment]
Yep, parfait ^^

**Comment by sizanic** [comment]
Traité, je clos 👍🏻 
Encore merci @doctornono
