### ISSUE TITLE
Tirexo est PapaFlix.com maintenant 

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#3904]
![byeb](https://user-images.githubusercontent.com/48101775/169663040-4ba49144-400c-4204-ad7c-38472f2121a0.gif)👉 [papaflix](https://fr.papaflix.com/) 
👉[De Phonandroid.com](https://www.phonandroid.com/tirexo-nest-pas-mort-le-site-pirate-sappelle-desormais-papaflix-com.html/amp)
👉 [Pour suivre les changements des noms de tirexo par les administrateurs c'est "T.ME"](https://t.me/s/tirexo_officiel) 
 ![respect-chapeau](https://user-images.githubusercontent.com/48101775/169663108-88eef6d7-0c80-4067-b390-c17b100067e2.gif)
![logo](https://user-images.githubusercontent.com/48101775/169662846-1a562ebd-602e-4017-a3bd-ac8b3ea855b5.png)

**Comment by sizanic** [comment]
R.I.P.
