### ISSUE TITLE
Problème lecture liens

### ISSUE THREAD

**Issue by falciatrice10** [Kodi-vStream/venom-xbmc-addons#3905]
Bonjour à tous

J utilise depuis longtemps Nodi v18 et tout allait bien.
Je viens de passer a Kodi 19.3 officiel
J'ai un compte premium uptobox
Je rencotre un problème lors de la lecture, je m explique :
J ouvre kodi
J ouvre l explorateur de mes fichiers uptobox
Je clique pour visionner un film/série
J obtiens le fameux message d erreur : **playback failed one or more items failed to play**
J essaye avec un autre lien que j ai déjà visionné et que je peux visionner via le navigateur , mais j obtiens le même message d'erreur.
Je ferme kodi
Je le relance
J'essaye a nouveau
Et la , tous les liens fonctionnent.
Remarque, j'ai le même problème avec Nodi v19
Mais tout fonctionne avec Nodi v18

Merci
**Votre system**
- OS: [ Android]
- Appareil: [x96 Max Plus 4g/64g S905x3]
- Version Kodi: [19.3]
- Version Vstream: [1.9.3]

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: tous
- Nom du host : uptobox

(J uploaderai le fichier log tout a l heure en rentrant)

**Comment by sizanic** [comment]
Bonjour @falciatrice10 

Je ne connais pas ce message d'erreur.

En ce moment, je suis en train de refaire la partie pour accèder à son compte uptobox.
Je te propose d'attendre la prochaine version de vStream pour voir si le problème persiste encore.

**Comment by tobal37** [comment]
@falciatrice10 je vois que tu n es pas sur la dernière version de vstream qui et la 1.9.3 met la a jour et réessaye déjà pour voir si tu as toujours le souci

cordialement

**Comment by falciatrice10** [comment]
> bonjour @falciatrice10 je vois que tu n es pas sur la dernière version de vstream qui et la 1.9.3 met la a jour et réessaye déjà pour voir si tu as toujours le souci
> 
> cordialement

Si si, je vais corriger le premier message

**Comment by falciatrice10** [comment]
Je viens de trouver !!!!

J'ai diminué la taille de mémoire tampon dans le fichier advancedsertings.xml de 600mo a 350mo .

Mais c'est quand même bizarre que kodi 18 accepte 600mo et pas kodi 19.
