### ISSUE TITLE
Rubrique Adulte

### ISSUE THREAD

**Issue by Azertixe** [Kodi-vStream/venom-xbmc-addons#3906]
Bonjour. Est-il possible de mettre une rubrique Adulte séparément du reste des Divers avec un code d’accès pour éviter que les enfants puissent y accéder facilement ?

Merci par avance 😁

**Comment by sizanic** [comment]
Bonjour.
Il y a déjà un paramètre vStream qui permet d'activer ou non l'accès à du contenu parental (sans code).
Nous devons le cibler source par source.
Merci de préciser la source pour que nous agissions en conséquence.

**Comment by Azertixe** [comment]
Salut. Merci pour la réponse rapide. J'utilise Pastebin. Sans rien enlever au travail de développeurs qui font du super boulot, actuellement la rubrique Divers contient un peu de tout mais on peut surtout tomber dedans sur du contenu adulte très trash.
Comme mes filles utilisent aussi Kodi, je voudrais éviter qu'elles puissent tomber dessus.
Merci encore =)

**Comment by sizanic** [comment]
S'il s'agit de Pastebin, c'est différent. Ce n'est pas ce paramètres qui pourra bloquer le contenu.
Pastebin fonctionne avec des codes à renseigner.
Chaque code correspondant à un type de contenu.
Il suffit de ne pas mettre le code adulte pour ne pas se voir proposer du contenu adulte 🤔

Ou alors créer deux profils dans Kodi. Un profil sans le code adulte, et un autre avec le code. Le deuxième profil sera protégé par mot de passe.

**Comment by Azertixe** [comment]
Salut sizanic. Je vois, merci pour cette solution !
Toutefois il me semble intéressant pour l'adulte qui veut avoir accès à du contenu coquin de le voir séparé du contenu sportif dans la rubrique Divers.
D'autant que suivant la dénomination, on ouvre parfois une rubrique sans savoir ce que l'on va y trouver xD

**Comment by sizanic** [comment]
Il n'y a plus de contenu adulte proposé dans Pastebin ...
