### ISSUE TITLE
kodi est fini???

### ISSUE THREAD

**Issue by CodingBDX** [Kodi-vStream/venom-xbmc-addons#3908]
**Décrivez le bug**

je n'ai plus acces a rien, je connais kodi depuis xbmc +de 10ans et avant c'etait ultra simple, y'avais même les mises a jour propose directement...
maintenant y'a des tonnes de depots mais aucun ne marche........et encore moins la recherche
**Votre system**
- OS: Android
- Appareil: [firetv]
- Version Kodi: [18]
- Version Vstream: [1.9.3]

**Log**

**Comment by CodingBDX** [comment]
non, je l'ai aussi sous debian bulleye et kodi 19 et ca fait la meme chose, ca fait 5mois environs que ca a commencé a deconné...

**Comment by sizanic** [comment]
> maintenant y'a des tonnes de depots mais aucun ne marche.

il n'y a qu'un seul dépot officiel et unique vStream et qui n'a jamais changé depuis la création de vStream : https://kodi-vstream.github.io/repo/

voir le tuto officiel vStream : https://kodi-vstream.github.io/docs/installation2/

**Comment by sizanic** [comment]
> 2022-06-24 16:33:24.334 T:62 INFO : [PLUGIN] vStream: could not load site: _4kstreamz error: argument of type 'bool' is not iterable


ok, il semble que l'accès au site "4kstreamz" n'est plus compatible et doit être modifié.
On va regarder.

De là à dire que Kodi lui-même ne fonctionne plus, c'est un peu extreme 🤔

**Comment by alKODIque** [comment]
Ouff!!
Mais pourquoi as-tu installé TOUS les addons PVR du dépôt Kodi ????
Ca ne doit certainement pas aider ç la fluidité de kodi

**Comment by TmpName** [comment]
Tu es sur d'avoir une connexion internet fonctionnelle ?
Car je viens de tester le site _4kstreamz et je n'ai pas vu de probleme.
Essayes d'utiliser un navigateur sur ta machine et connectes toi a ht_tps://w_ww.4kstreamz.net/ (sans les "_")

**Comment by CodingBDX** [comment]
quand je me connecte au site 4kstream, il me parle de configuration nginx????

ensuite sur la 30ene de sites disponible, il n'y en a que 2 qui fonctionne, il y a 4mois la moitié fonctionné, et 1an ils fonctionnaient tous....

ensuite j'utilise flatpak pour installer la derniere version de kodi...j'ai tous les pvr car je m'en sers pour l'iptv...

mais cela n'explique pas pourquoi cela ne fonctionne pas sur mon firestick 4k sous android...les 2 me donnent le même resultat
merci de votre aide

**Comment by sizanic** [comment]
Pour accéder à 4kstreamz (et pour d'autres sources également), tu dois changer de DNS.

Comment changer de DNS sous FireTV : https://fr.techtribune.net/securite/vpn/comment-changer-le-dns-sur-la-cle-fire-tv/140037/


ATTENTION : 
Il faut s'arreter avant le paragraphe "Mais quel paramètre DNS dois-je entrer?" qui est une publicité pour vendre un VPN.

**IL NE FAUT PAS DE VPN AVEC VSTREAM.**


voici une liste de paramètres DNS : 
https://www.phonandroid.com/meilleurs-serveurs-dns-gratuits.html

**Comment by sizanic** [comment]
Tu utilises un fireStick ?

Je ne connais pas flatpak, mais pour un fireStick j'utilise "Easy Fire Tools" qui permet d'installer kodi facilement .

**Comment by CodingBDX** [comment]
effectivement, c'est le dns qui n'etait pas inscrit...

mais je n'ai jamais eu a faire cette manipulation...ou est ce marqué????? car si tu me l'avais pas dit a aucun moment dans la doc, c'est marqué....

il y'a quand meme 2 3sites qui me marque "pas d'informations" ,dpstream notamment..
merci en tout cas

**Comment by TmpName** [comment]
C'est ton fournisseur d'accés qui doit bloquer ces adresses, c'est peut etre juste nouveau.

**Comment by sizanic** [comment]
> mais je n'ai jamais eu a faire cette manipulation.. ou est ce marqué????? car si tu me l'avais pas dit a aucun moment dans la doc, c'est marqué....

Parce que ce n'est pas un probleme avec vStream.
La solution ne se paramètre pas dans vStream.

C'est un probleme général avec ton fournisseur internet qui a récemment bloqué certains adresses.
D'ailleurs tu as pu vérifier que tu n'y a pas accès non plus depuis ton navigateur.

**Comment by sizanic** [comment]
vStream propose l'outil DNS Python, qui s'installe depuis Kodi "installer depuis un zip" en allant sur le dépot de vStream.

En cas de probleme DNS, vStream affiche un message : "essayer d'installer DNSPython".

On ne fera pas plus pour l'instant.
