### ISSUE TITLE
Sources et liens - Rien fonctionnent 

### ISSUE THREAD

**Issue by erikatremblay** [Kodi-vStream/venom-xbmc-addons#3911]
Bonjour, j’utilise Vstream depuis plus de 7 ans et actuellement je ne comprends plus rien.. aucun lien ou presque fonctionne j’ai clairement un problème a quelque part mais lequel? 🤦‍♀️ 

Vstream est à jour  
J’utilise Kodi 18.9 

mais sincèrement rien ouvre ou presque. Je ne sais plus quoi faire j’ai besoin de votre aide.

**Comment by erikatremblay** [comment]
Oui j’ai regarder les issues ouvertes. 

Pourquoi il y a un message qui explique mon problème ?

**Comment by sizanic** [comment]
ton probleme est "aucun lien ou presque fonctionne".

le probleme de l'issue précedente (nomé "kodi est fini ?")  est : "je n'ai plus acces a rien".

la réponse est dans les derniers messages 🤔

**Comment by erikatremblay** [comment]
Non je l’ai lu et ce n’est pas le même problème car lui il a kodi 19 moi non et moi mon soucis est que pratiquement tous les liens dans toutes les sources ne fonctionnent pas. Quand je réussi a en avoir un c’est la joie. Je n’ai jamais eut autant de difficulté à écouter quelque chose.

**Comment by sizanic** [comment]
Ok lui n'a pas de lien alors que toi tu as bien des liens mais ils ne fonctionnent pas.
C'est bien ça ?

**Comment by erikatremblay** [comment]
Oui j’ai les liens, mais pratiquement tous ne fonctionnent pas, quand j’en trouve un qui fonctionne c’est rare. Normalement je trouve en 1min ce que je veux écouter. Ce soir j’ai du changer de séries 3-4 fois pour en trouver une qui fonctionne mais que le lien gel..

**Comment by erikatremblay** [comment]
Les seuls liens qui fonctionnent sont les Uqload mais pas toujours. 

Et j’ai un message invalid url tirexoindex mais sa je crois que vous avez fait une publication sur cela. 

Et sur 4kstreamz aussi

**Comment by sizanic** [comment]
Pour 4kstreamz j'ai répondu dans l'autre sujet.

a toi de voir si tu ne veux vraiment pas appliquer la solution qu'on donne et qui permet d'obtenir plus de liens.

**Comment by erikatremblay** [comment]
Oui c’est officiel que je vais essayer de régler la problématique de 4kstreamz mais je ne comprends pas le DNS entk ahah la mon soucis est que la majorité des liens ne fonctionnent pas et là je ne parle pas de 4kstreamz

**Comment by erikatremblay** [comment]
Pourtant je viens d’aller lire sur les DNS et c’est pour en wifi moi ma beelink GT King Pro est connecté directement dans mon routeur. A moins que je comprenne tout croche.

**Comment by erikatremblay** [comment]
Bon j’ai changé mes paramètres DNS dans ma beelink mais sa ne fonctionne pas je n’ai plus d’internet maintenant 🙈😅 hey lala

**Comment by sizanic** [comment]
wifi ou filaire, c'est la même chose.

Plutot que de changer tes parametres DNS, il existe aussi la solution d'installer sur kodi une extension qui joue le même role qu'un DNS alternatif.

Il s'agit de DNSPython.


Pour l'installer sur Kodi 18.9, rien de plus simple, il suffit de passer par vStream !

En allant dans la fenetre d'informations de vStream, puis "Dépendances", il faut installer DNSpython, la version 1.12.2 si plusieurs versions sont proposées.

![image](https://user-images.githubusercontent.com/47307622/177526946-f8dd0b05-efdf-43d8-847f-e0a01e143240.png)

**Comment by erikatremblay** [comment]
Il l’est déjà installé 
![Uploading DFC38215-93AC-4280-BECC-61E55A0EAF83.jpeg…]()

**Comment by erikatremblay** [comment]
![E87BC25A-5A80-4234-A6D7-645959F4D9EB](https://user-images.githubusercontent.com/43388286/177549316-0814d277-67c5-46df-b2ea-0e3e9f8a01a2.jpeg)
![5067FBE7-9FC3-4973-A309-FEC2042D3339](https://user-images.githubusercontent.com/43388286/177549320-a2cffc59-2922-43c1-b67d-db5d24b0ec12.jpeg)

**Comment by sizanic** [comment]
Les sites évoluent beaucoup en ce moment.
(les deux plus gros ont fermés récement).

Nous faisons au mieux pour maintenir les autres.
Une nouvelle version de vStream devrait sortir très prochainement.

Si tu es abonné à un hébergeur (uptobox) ou à un débrideur (alldebrid ou realDebrid), as-tu regardé du côté de la source Pastebin ?
Il s'agit d'une source "Premium" : la plus grosse bibliothèque de liens, et tous les liens fonctionnent.

**Comment by erikatremblay** [comment]
Je suis abonné a uptobox, je vais vérifier plus tard aujourd’hui. Je comprends que beaucoup de sites rush actuellement pas d’inquiétude je voulais seulement m’assurer que ce n’était pas un soucis juste de mon côté car même avec le DNS installé 4kstreamz ne fonctionne pas. Je vérifie plus tard en soirée comment ca va pour les liens et vous reviens :) merci pour votre travail

**Comment by TmpName** [comment]
Si tu pouvais passer des logs on pourrais voir si le probleme viens de chez toi ou de l hebergeur.

**Comment by sizanic** [comment]
Si tu es abonné à Uptobox, as-tu bien  pensé à renseigner tes identifiants dans vStream afin de bénéficier des liens uptobox et uptobstream ?

**Comment by erikatremblay** [comment]
Oui et les liens uptobox ne fonctionnent pas souvent malheureusement 🤦‍♀️ 

Pour les logs je fais comment pour vous les envoyez ?

**Comment by sizanic** [comment]
> Pour les logs je fais comment pour vous les envoyez ?

Tu peux glisser/déposer ici le fichier kodi.log après avoir reproduit le problème.

**Comment by erikatremblay** [comment]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/9058156/kodi.log)

**Comment by sizanic** [comment]
Merci pour ce retour détaillé.

Il va nous servir de base pour retravailler certaines sources.

En attendant, grâce à ton compte uptobox, tu as la possibilité d'accéder à la source Pastebin qui te donneras toujours des liens fonctionnels et de bonne qualité.

**Comment by erikatremblay** [comment]
Ok je vais essayer cela mais moi mon gros soucis est que je vends des boites beelink GT King avec programmation kodi 😅🙈 donc mes clients n’ont pas tous un compte uptobox. Donc je leur dit seulement que vstream est pas trop fonctionnel actuellement?

**Comment by sizanic** [comment]
ça dépend,
elle est où notre commission ?

**Comment by erikatremblay** [comment]
Ahah bonne question 🙈 moi sa me rapporte pas grand chose je fais cela pour vendre mes forfaits internet.

**Comment by erikatremblay** [comment]
Donc est-ce que le soucis est juste de mon côté? Ou c’est généralisé? Avec mon log vous pouvez voir quoi ?

**Comment by erikatremblay** [comment]
> Merci pour ce retour détaillé.
> 
> Il va nous servir de base pour retravailler certaines sources.
> 
> En attendant, grâce à ton compte uptobox, tu as la possibilité d'accéder à la source Pastebin qui te donneras toujours des liens fonctionnels et de bonne qualité.

Il y a une façon d’utiliser la source pastebin ? Car moi les catégories m’écrivent toutes aucune information.. 🤦‍♀️

**Comment by sizanic** [comment]
On va regarder toutes les sources que tu nous a signalé qui ne fonctionnent pas.

**Comment by erikatremblay** [comment]
Ok parce que vous m’aviez dit que la source pastebin fonctionnait tout le temps mais de mon côté aussitôt que je clique sur une catégorie sa me dit aucune information.

**Comment by doctornono** [comment]
> Ok je vais essayer pour le log 😅
> 
> j’ai fait le tour des sources et voici mes résultats :
> 
> * 1 serie streaming : liens ouvrent mais gel
> * 33 séries : aucun liens fonctionnent
> * 4kstreamz : aucune information
> * Cine974 : error lien youtube ne joue pas dans mon pays : **`fonctionnel chez moi`**
> * Cinemay_cc : aucun liens fonctionnent **`fonctionnel chez moi`**
> * Cinemay : aucun liens fonctionnent **`fonctionnel chez moi`**
> * DPstream: aucune information 
> * DPstream HD aucune information
> * Du cine : aucun liens fonctionnent sauf uptobox **`fonctionnel chez moi`**
> * Enstream (series) : liens ouvrent mais lag et gel et uptobox ne fonctionne pas
>   -Filmoflix : n’ouvre pas les catégories
>   -French stream : aucun liens fonctionnent **`fonctionnel chez moi`**
>   -French stream lol : aucun liens fonctionnent **`fonctionnel chez moi`**
>   -HDS fm: aucun liens fonctionnent **`fonctionnel chez moi`**
>   -HDS STREAM : aucun liens fonctionnent **`fonctionnel chez moi`**
>   -illimitestreaming : aucun liens fonctionnent **`fonctionnel chez moi`**
>   -kstreaming : aucun liens fonctionnent
>   -kepliz: aucun liens fonctionnent
>   -kstreaming films: aucun liens fonctionnent
>   -kstreaming series: liens ouvrent mais lag et gel
>   -libertyland: Aucune information
>   -mes films : Aucune information
>   -my stream : aucun liens fonctionnent
>   -01 streaming: aucun liens fonctionnent
>   -serie streaming : 2 liens fonctionnent uqload et uptobox
>   -serie en streaming: n’ouvre pas les catégories
>   -series stream: Aucune information
>   -streamcomplet: aucun liens fonctionnent
>   -streamcomplet3: Aucune information
>   -streaming series : upstream ouvre mais lag et gel
>   -streamingdivx: aucun liens fonctionnent sauf uptobox
>   -streaminz: aucun liens fonctionnent
>   -streampourvous : n’ouvre pas les catégories
>   -Vf films: n’ouvre pas les catégories
>   -Vf Series: beaucoup de liens qui ne fonctionnent pas mais une fois de temps en temps 1 lien fonctionne
>   -Vfilms: aucun liens fonctionnent sauf upstream mais lag et gel
>   -voirfilms: aucune information
>   -voirseries: aucun liens fonctionnent
>   -watchvf: aucune information
>   -wiflix: aucun liens fonctionnent sauf upstream mais lag et gel
>   -zone téléchargement : aucune information
>   -zustream: aucune information

**Comment by doctornono** [comment]
@TmpName , de rien, ma petite pierre à l'édifice.
Si tu veux, je peux tester toutes les sources pour identifier les sources problématiques

**Comment by erikatremblay** [comment]
> > Ok je vais essayer pour le log 😅
> > j’ai fait le tour des sources et voici mes résultats :
> > 
> > * 1 serie streaming : liens ouvrent mais gel
> > * 33 séries : aucun liens fonctionnent
> > * 4kstreamz : aucune information
> > * Cine974 : error lien youtube ne joue pas dans mon pays : **`fonctionnel chez moi`**
> > * Cinemay_cc : aucun liens fonctionnent **`fonctionnel chez moi`**
> > * Cinemay : aucun liens fonctionnent **`fonctionnel chez moi`**
> > * DPstream: aucune information
> > * DPstream HD aucune information
> > * Du cine : aucun liens fonctionnent sauf uptobox **`fonctionnel chez moi`**
> > * Enstream (series) : liens ouvrent mais lag et gel et uptobox ne fonctionne pas
> >   -Filmoflix : n’ouvre pas les catégories
> >   -French stream : aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -French stream lol : aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -HDS fm: aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -HDS STREAM : aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -illimitestreaming : aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -kstreaming : aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -kepliz: aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -kstreaming films: aucun liens fonctionnent  **`fonctionnel chez moi`**
> >   -kstreaming series: liens ouvrent mais lag et gel
> >   -libertyland: Aucune information
> >   -mes films : Aucune information
> >   -my stream : aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -01 streaming: aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -serie streaming : 2 liens fonctionnent uqload et uptobox
> >   -serie en streaming: n’ouvre pas les catégories
> >   -series stream: Aucune information
> >   -streamcomplet: aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -streamcomplet3: Aucune information
> >   -streaming series : upstream ouvre mais lag et gel
> >   -streamingdivx: aucun liens fonctionnent sauf uptobox **`fonctionnel chez moi`**
> >   -streaminz: aucun liens fonctionnent **`fonctionnel chez moi`**
> >   -streampourvous : n’ouvre pas les catégories
> >   -Vf films: n’ouvre pas les catégories
> >   -Vf Series: beaucoup de liens qui ne fonctionnent pas mais une fois de temps en temps 1 lien fonctionne
> >   -Vfilms: aucun liens fonctionnent sauf upstream mais lag et gel **`fonctionnel chez moi`**
> >   -voirfilms: aucune information
> >   -voirseries: aucun liens fonctionnent
> >   -watchvf: aucune information **`fonctionnel chez moi`**
> >   -wiflix: aucun liens fonctionnent sauf upstream mais lag et gel  **`fonctionnel chez moi`**
> >   -zone téléchargement : aucune information
> >   -zustream: aucune information
> 
> J'ai presque tout testé (à partir de films-> derniers ajouts), la majorité des sources fonctionnent très bien, le problème n'est pas vstream. Certaines sources sont probablement down , certains liens peuvent être obsolètes dans les sources, mais rien de bien particulier. Tu as quoi comme DNS ?

J’ai l’application qui va avec Vstream DNSpython

**Comment by erikatremblay** [comment]
> @erikatremblay j'ai voulu comparer avec tes logs, j'ai laissé tomber. Desinstalles tout, installes un kodi vierge, et le ou les addons que tu veux, la franchement c'est une poubelle. Y a des erreurs de partout avec des plugins qui se lancent en meme temps que Vstream mais qui n'en font meme pas parti, beautifulsoup, des skinhelpers ...
> 
> @doctornono Merci pour les tests, ca va faire du tri, j'essaye de mettre ta liste a jour ce WE.

Ok je ne comprends pas car sa fonctionnait bien avant. 🤔 Je n’ai rien changé au build de mon kodi pourtant. Je vais revoir le tout alors. Je vais effacer et réinstaller seule vstream et voir si sa fonctionne et vous revenir. 

La seule chose que j’ai changer est que j’ai augmenté ma vitesse internet a 1gb et la compagnie m’a envoyé un nouveau modem internet. Est-ce que mon nouveau modem pourrait être la cause ?

**Comment by doctornono** [comment]
Teste sur une installation propre de Kodi. Si tu es sur Windows, tu peux tester sur une version portable de Kodi pour ne pas toucher à ton kodi initial. Mais comme te le dis TmpName, ton kodi n'est pas propre

[https://kodi.wiki/view/Portable_mode](url)

**Comment by erikatremblay** [comment]
> @erikatremblay juste un extrait
> 
> ```
> 2022-07-06 05:36:03.204 T:5777 WARNING: Repository add-on repository.elementum uses plain HTTP for add-on downloads in path http://127.0.0.1:65220/repository/elgatito/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:36:03.205 T:5777 WARNING: Repository add-on repository.T2K uses plain HTTP for add-on downloads in path http://t2k-repository.ml/T2K-Adult/T2K-Adult-Zone-Addon/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:36:03.205 T:5777 WARNING: Repository add-on repository.T2K uses plain HTTP for add-on downloads in path http://t2k-repository.ml/T2K/repository.T2K/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:36:03.207 T:5777 WARNING: Repository add-on lanik.repo uses plain HTTP for add-on downloads in path http://kodi.lanik.org/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:36:03.210 T:5777 WARNING: Repository add-on repository.grindhousekodi uses plain HTTP for add-on downloads in path http://grindhousekodi.tk/grindhouse/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:36:16.710 T:5794 WARNING: SEREN (-1): TraktSync: No Trakt auth present, no sync will occur
> 2022-07-06 05:38:46.946 T:30014 WARNING: Repository add-on repository.Rising.Tides uses plain HTTP for add-on downloads in path http://mullafabz.xyz/Plugins/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:38:46.947 T:30014 WARNING: Repository add-on repository.kodikrypton.quebec uses plain HTTP for add-on downloads in path http://kodikrypton.com/repository - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:38:46.947 T:30014 WARNING: Repository add-on repository.xstream.stable uses plain HTTP for add-on downloads in path http://cl226.vi-server.com/Ghost/xstream/stable - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:38:46.948 T:30014 WARNING: Repository add-on repository.lazyman uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/actionbronson/LazyMan/master/src/kodi/repository - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:38:46.948 T:30014 WARNING: Repository add-on repository.whitecream uses plain HTTP for add-on downloads in path http://offshoregit.com/whitecream/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:38:46.952 T:30014 WARNING: Repository add-on repository.podgod uses plain HTTP for add-on downloads in path http://offshoregit.com/podgod/repo/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:38:46.953 T:30014 WARNING: Repository add-on repository.kodibrasilforum uses plain HTTP for add-on downloads in path http://files.moxiweb.com/main/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2022-07-06 05:38:46.953 T:30014 WARNING: Repository add-on repository.supremacy uses plain HTTP for add-on downloads in path http://supremacy.org.uk/zip/plugin/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> ```
> 
> Tu es sur d'avoir besoin de TOUT ces repos ? Est ce que seulement tu te souviens a quel plugin ils servent ?

Ouais je vais vérifier car je vois lazyman et lazyman n’est plus fonctionnel depuis que le créateur l’a abandonné. Je fais le tour

**Comment by TmpName** [comment]
-    1 serie streaming : ok chez moi pour "black bird"
-    33 séries : aucun liens fonctionnent, pareil surement le cookie a recuperer, mis de coté
-    4kstreamz : Site HS chez moi erreur 503
-    DPstream: Site introuvable
-    DPstream HD Site introuvable
-    Filmoflix Protegé par cloudflare.
-    voirfilms: Site HS (deja supprimé sur github)
-    zustream: Site HS (deja supprimé sur github)
-    libertyland: Site HS ( a marquer HS sur le gituhb)
-    streamcomplet3: Reparé ( ils utilisent 1 seul hoster qui n'etait pas dans Vstream)
-   mes films : Corrige

**Comment by erikatremblay** [comment]
Parfait j’ai supprimer mes repo qui causaient problèmes. Je revérifie le tout dans quelques minutes 😉 sinon j’effacerai et recommencerai à zéro. ☺️

**Comment by erikatremblay** [comment]
Bon verdict de mon côté après avoir supprimé toutes les merdes que j’avais. Pas tout est entré dans l’ordre mise à part les sites que @doctornono a nommé plus haut. 

Mais moi certain ne fonctionnent pas et lui sa fonctionne 🤷‍♀️ Pas grave je suis bien contente que se soit revenu pas mal a la normal de mon côté 😅

**Comment by TmpName** [comment]
MAJ


-    1 serie streaming : ok chez moi pour "black bird"
-    33 séries : aucun liens fonctionnent, pareil, j'ai cherché c'est pas les cookies, le hash ne marche qu'un temps
-    4kstreamz : Site HS chez moi erreur 503
-    DPstream: Site introuvable
-    DPstream HD Site introuvable
-    Filmoflix Protegé par cloudflare.
-    voirfilms: Site HS (deja supprimé sur github)
-    zustream: Site HS (deja supprimé sur github)
-    libertyland: Site HS ( a marquer HS sur le gituhb)
-    streamcomplet3: Reparé ( ils utilisent 1 seul hoster qui n'etait pas dans Vstream)
 -   mes films : Corrige
 -   series stream: Ok chez moi
 -   serie en streaming : Sous CF non testé, je n'ai pas flaresolver
 -   Vf films: ok chez moi

**Comment by sizanic** [comment]
Top.
Cela va permettre de plannifier une mise à jour 👍

**Comment by sizanic** [comment]
J'ai testé les sources sous cloudflare avec flaresolver.

- Filmoflix -> OK
- serie en streaming : NOK - flaresolver s'active bien mais une erreur : "Request parameter 'cmd' is mandatory"
-streampourvous : NOK - flaresolver s'active bien mais avec un message : "Cloudflare not detected"
-Vf films : NOK - flaresolver s'active bien mais tombe en timeout

**Comment by arzaz** [comment]
Une solution pour Extreme download ?

**Comment by TmpName** [comment]
C'est pas une protection Recaptcha ?

**Comment by sizanic** [comment]
Nous avons le ménage dans les sources : 
- suppression des sources obsolètes
- corrections lorsque c'était possible.

Je clos ce ticket.

Il faudra créer un nouveau ticket si nécessaire lorsque la nouvelle version sera disponible.
