### ISSUE TITLE
debrid ZT

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#3912]
J'en appelle aux développeurs.

Comment débrider les liens dl-protect de zt.tel ?

J'a l'impression que je pourrais résoudre à partir du 'data-sitekey' récupéré, et l'ancien fichier sites/trash/dl_protect.py qui utilise resources/lib/recaptcha.py

Ou alors il faut que j'utilise librecaptcha ?

**Comment by TmpName** [comment]
Tu aurais la nouvelle adresse de ZT ?

**Comment by TmpName** [comment]
Mais le site est de retour ?
C'est quoi l'url ?

**Comment by sizanic** [comment]
www . zone - tele chargement . tel/

je ne sais pas si officiel mais les liens sont là :)

**Comment by TmpName** [comment]
Ben j'ai pas trouve le fichier sites/trash/dl_protect.py pour lire le code mais resources/lib/recaptcha.py est depassé la derniere fois on utilisait directement la lib bidouillée /lib/librecaptcha

Et je ne retrouve pas de vieux code pour ce site.
Requete POST vers dl-protect.info/numero_de_fichier avec en corps {"subform":"Unlock","g-recaptcha-response":"fdfgdgfdgdfgdfg"}

Par contre suis pas sur que la lib librecaptcha fonctionne encore, je viens de regarder la requete faite via le navigateur, il ya une dizaine de cookies ...
