### ISSUE TITLE
Bug - Recherche 

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3913]
Bonjour à vous,

Il y a un bug avec la recherche lorsque le titre d'un média comporte un caractère spécial.
Exemple, une recherche de film contenant le mot ''coeur'' ou le ''o'' et le ''e'' sont collé. Ou encore, lorsque le ''a'' et le ''e'' sont collés (ex: film Aeon Flux)
si nous entrons un de ces mots, aucun résultat n'est présenté dans la recherche.

Aussi, suite a ce problème, je me demandais s'il n'était pas possible d'aussi pouvoir faire une recherche avec le titre en VO ?

Exemple, film ''Coeur déchiré'' = aucun résultat. Le titre VO est ',Torn hearts'' et aucun résultat non plus.

Je suis avec la dernière bêta de vStream, Kodi 19.4, nvidia shield Pro

Merci!

**Comment by sizanic** [comment]
Bonjour,

La recherche de chaque source est gérée par le site associé.

Donc pour la recherche du titre en VO, c'est seulement si le site le supporte.
Et pour une source comme Pastebin, la recherche est réalisée sur le titre TMDB qui est dans le paste.
Ce serait lourd de mettre en place un système qui interroge TMDB à partir du titre en VO pour avoir l'id, et ensuite seulement faire la recherche dans le paste.
Voir pour utiliser plutot TMDBhelper.


Dans tous les cas, quelque soit la source, on va regarder pour voir quelles sont les sources qui supportent le changement des œ en oe, et mettre en place une évolution si c'est possible.

**Comment by alKODIque** [comment]
La question que je me pose, c'est pourquoi avec TMDb Helper, je retrouve bien ''Torn Heart'' ou ''Coeur brisé'', et qu'une fois trouvé, le player vStream (qui appelle mla recherche globale de vstream) réussi aussi a trouver le film?
Mais qu'en passant directement par la recherche globale ca ne fonctionne pas...

**Comment by sizanic** [comment]
> A mon avis, tmdbHelper envoie l'id du film vers vStream, et non pas le nom du film.

c'est ce que j'ai pensé au début mais je ne crois pas.
vStream ne sait pas lancer une recherche à partir d'un id.
je pense plutot qu'a partir du titre VO, tmdbhelper renvoi à vStream le titre en FR mais sans caractères spéciaux.

C'est à creuser.

**Comment by sizanic** [comment]
Ah ok.
Je pensais que depuis le début tu saisissait avec le caractère spécial et qu'il ne trouvait pas.
Mais c'est le contraire. 👍

**Comment by detobel36** [comment]
Pour être sûr à 100% d'avoir tous les résultats, il faudrait lancer plusieurs recherches.

Par exemple:
> Le crime de l'orient-express
(titre TMDB)

On pourrait faire deux recherches:
- `le%20crime%20de%20l%27orient-express`
- `le%20crime%20de%20l%20orient%20express`

Si on veut pousser le truc encore plus loin:
- `le%20crime%20de%20l%20orient-express`

Mais ça augmenterait le temps de recherche...

**Comment by TmpName** [comment]
Alors je vais me taire car je suis un extremiste.
Sur le papier, vous pouvez utiliser les caracteres que vous voulez, mais en informatique, jamais de cedille par exemple, je repense au fou fourieux qui a pris comme compte utilisateur "Jean-François"

Pour moi apres quelques echecs, les gens apprennent que pour chercher "Le crime de l'orient-express" on tape juste "crime express" par exemple.

**Comment by sizanic** [comment]
Je suis d'accord avec tmpname, on ne fera pas plusieurs recherches.

Si pour une source donnée, vous allez sur la barre de recherche du site de streaming correspondant et qu'il ne trouve rien pour "coeur" parce qu'il faut chercher "cœur", on ne fera pas mieux.


Il faudra taper cœur également avec vStream.
Ou les autres mots du titre.

La recherche de "cœur" dans vStream fonctionne très bien 
![image](https://user-images.githubusercontent.com/47307622/180274354-93c7cfe0-41c1-4cdf-b370-59e23ee43d41.png)

**Comment by detobel36** [comment]
Je suis d'accord avec vous.

Mais tout le raisonnement tombe à l'eau si vous passer par tmdb pour compléter le titre et faire la recherche à votre place ;)

(typiquement ce que je fais dans ma PR)

**Comment by TmpName** [comment]
Alors deja je suis surpris que ca marche avec "cœur" ...
Du coup j'ai testé en film avec ma config et la recherche classique ^^

"cœur battant" > 4 resultats
"coeur battant" > 7 resultats

Donc effectivement ca marche, mais je pense pas que ce soit le mieux.

Ce serait pas plus simple de faire une modif dans tmdb pour nettoyer les titres avant les recherches ? Y a deja des bout de codes qui  trainent qui font ca. En cherchant `unicodedata.normalize('NFD', name).encode('ascii', 'ignore')` on doit pouvoir en trouver des oublies (dans trakt, topimdb, utils, ect ...)

**Comment by sizanic** [comment]
Tu n'as pas le même nombre de résultats parce que ce n'est pas les mêmes résultats.

Les '4 résultats' ne sont pas inclus dans les '7'.
Il y a normalement 11 résultats.

Si tu nettoies/remplaces tu n'auras qu'une partie des résultats.

Le titre est écrit d'une façon différente selon les sites. il faudrait rechercher avec les deux typographie pour avoir tous les résultats, et on ne fera pas.

**Comment by TmpName** [comment]
Ha merde j'avais pas testé ca.
Mais oui du coup il y a des sites bien foutu qui supportent les 2 orthographes.
Mais il y en a comme wiflix qui ne marchent que avec l'orthographe francaise, donc meme si ces sites bancales sont en minorité, effectivement c'est mort pour moi.

**Comment by sizanic** [comment]
Il y a eu des changements depuis.
N'a pas l'air d'être très bloquant.
