### ISSUE TITLE
Ajouter l'addon InputStream.Adaptative en dépendance

### ISSUE THREAD

**Issue by Red-Hide** [Kodi-vStream/venom-xbmc-addons#3915]
**Votre demande de fonctionnalité est-elle liée à un problème? Décrivez s'il vous plait.**
Bonjour,

Depuis pas mal de temps j'essaye d'utiliser kodi pour regarder des animes et, utilisant le site neko-sama sur mon pc, je me suis dis que j'allais utiliser le même avec kodi. Mais après l'installation, erreur de vstream et pas moyen de le faire marcher. Après beaucoup de recherche j'ai vu sur discord qu'il fallait l'addon InputStream.Adaptative. Il faudrait que cette information soit mentionné clairement quelque part.

**Décrivez la solution que vous souhaitez**
Ajouter l'addon inputstream.adaptative en dépendance ou mentionner qu'il faut l'installer pour neko-sama ( et les autres hosters/sources qui l'utilisent) quelque part

**Comment by sizanic** [comment]
Bonjour,
Merci pour ton retour.

On va voir pour l'ajouter en dépendance je pense.
@TmpName 
Des contraintes à celà ?
Tu peux faire ?

.
Et sinon, tu as trouvé ton bonheur sur la source neko-sama et continuer à passer par vStream ?

**Comment by TmpName** [comment]
Ben je suis en train de regarder, je ne pense pas que cela est quelque chose a voir avec Vstream mais directement kodi
Le code qui l'utlisait dans Vstream a été desactivé, donc si ca a encore un impact c'est bizarre.

```
        #Si lien dash, methode prioritaire
        if False and splitext(urlparse(sUrl).path)[-1] in [".mpd",".m3u8"]:
            if isKrypton() == True:
                addonManager().enableAddon('inputstream.adaptive')
                item.setProperty('inputstream','inputstream.adaptive')
                if '.m3u8' in sUrl:
                    item.setProperty('inputstream.adaptive.manifest_type', 'hls') 
                else:
                    item.setProperty('inputstream.adaptive.manifest_type', 'mpd')
                xbmcplugin.setResolvedUrl(sPluginHandle, True, listitem=item)
                VSlog('Player use inputstream addon')
            else:
                dialog().VSerror('Nécessite kodi 17 minimum')
                return
```

**Comment by TmpName** [comment]
Pour le texte il suffit de rajouter
```
    if not addonManager().isAddonExists("inputstream.adaptive"): 
        oGui.addText(SITE_IDENTIFIER,"[COLOR red]inputstream.adaptive doit etre installe pour ce site[/COLOR]")
```

(Mais la fonction fonctionne a l'envers, je la corrige de suite)

**Comment by TmpName** [comment]
Et en passant moi je l'ai installé, mais nekosama ne marche pas pour autant chez moi.

**Comment by TmpName** [comment]
Du coup on part sur le message ?

@Red-Hide
De l'installer a chnagé quelque chose pour toi ?

**Comment by Red-Hide** [comment]
Après avoir vu sur discord la mention de l'addon j'ai installé kodi sur windows (kodi 19.4) spécialement pour le tester donc mon installation était nouvelle. J'ai testé sans l'addon inputstream, erreur, puis je l'installe et je retente neko-sama et là la vidéo se lance. J'ai fait la même chose sur android tv (kodi 19.3) et même résultat, la vidéo se lance seulement avec l'addon inputstream.

**Comment by TmpName** [comment]
C'est quoi ton hoster ? (Le nom en bleu sur le lien juste avant de lancer la video)
J'ai fais un deuxieme essais avec les liens Pstream,, toujours rien.

**Comment by Red-Hide** [comment]
Mon hoster est bien Pstream et je n'ai pas d'autres options.

**Comment by TmpName** [comment]
Me faudra re-essayer demain, il semble y avoir une securite par IP, une fois allé sur leur site, j'arrive a aller au lien final, mais ca plante encore (kodi 19.2)

**Comment by Red-Hide** [comment]
Non je l'ai juste installé depuis le repo officiel de kodi et ça marchait après.

**Comment by alKODIque** [comment]
Je sais pas si ça a un lien, mais l'addon officiel Youtube a InputStream Helper comme dépendance facultative..
Est-ce possible que cette source ait besoin de ce script pour fonctionner correctement?

![Screenshot_20220726-220842](https://user-images.githubusercontent.com/49578130/181145719-9739740b-5dd2-4ee5-907d-061cf9793d07.png)

**Comment by TmpName** [comment]
@alKODIque ben justement, ca me surprendrait pas, c'est justement a ca que sert inputstream.adaptive.

Par contre pourquoi chez moi ca marche pas ... (windows 7 ?)

**Comment by alKODIque** [comment]
@TmpName 
C'est peut-ête la commande widevine qui ne se fait pas bien sur ton windows 7?? Peut-être que ton kodi ne trouve pas la commande
Je sais pas trop, j'y connais pas grand-chose..

**Comment by TmpName** [comment]
Ha pas faux, me faudra verifier, hier je suis passé par la config de kodi pour re installer l'application, je pense qu'il a du choisir la bonne version, mais ca pourrait venir de ca.

Edit:
Win7 sous 64 bits version, manqué, mais win7 est vieux, peut etre plus supporté.

**Comment by sizanic** [comment]
@TmpName 

> Ben je suis en train de regarder, je ne pense pas que cela ait quelque chose a voir avec Vstream mais plutot directement kodi.
Le code qui l'utlisait dans Vstream a été desactivé, donc si ca a encore un impact je pense pas que cela vienne de nous.

> 
> ```
>         #Si lien dash, methode prioritaire
>         if False and splitext(urlparse(sUrl).path)[-1] in [".mpd",".m3u8"]:
>             if isKrypton() == True:
>                 addonManager().enableAddon('inputstream.adaptive')
>                 item.setProperty('inputstream','inputstream.adaptive')
> ```


Je pense qu'il n'y a que chez toi qu'il est désactivé, car il ne l'est pas 😉 

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/70d276f6ed70647f92363848ccbfc5515213534b/plugin.video.vstream/resources/lib/player.py#L119



> Si neko sama est le seul site a s'en servir, il est possible de voir si le plugin est present ou pas et afficher un message. Mais je sais pas si de forcer la dependance est une bonne chose.


Il y a aussi la source Viki qui l'utilise.

Et si message on devait mettre, on pourrait le mettre dans Player.

**Comment by TmpName** [comment]
Et il marche viki chez toi ?

Ce que je voulais dire c'est que c'est desactivé dans le code de Vstream (`if False`), c'est kodi qui gere ca, c'est plus nous avec du code python.

Quand tu parles du player, tu parles de Pstream ?

**Comment by sizanic** [comment]
Le  "if false"  n'est pas sur le github, je n'en trouve pas trace non plus dans l'historique.

> Et il marche viki chez toi ?

Je viens de corriger des trucs sur viki, ça lance bien la lecture avec InputStream.
Mais ensuite ça bloque, probleme d'identifiant

> Quand tu parles du player, tu parles de Pstream ?

non, je parle de player.py, Dans la section avec le 'if' imaginaire.

On essaie un : addonManager().enableAddon('inputstream.adaptive')

Et si on n'arrive pas à l'activer, on devrait mettre un message.

Finalement, on devrait même mettre le message dans addonManager.
Il n'y a qu'un log.
(qui ne fonctionne pas d'ailleurs, car on essaie d'activer mais si l'addon n'est même pas présent, il y a une exception).

**Comment by TmpName** [comment]
Yep, ca vient de moi, mais a quel moment j'ai touché a ca ...

Ben le truc c'est que de memoire cet addon n'est pas obligatoire.
Tu peux lancer un m3u8 sans cet addon, il suffit qu'il soit sans drm. Pour moi il n'y aurait que certain players qui en auraient besoin.

**Comment by Arias800** [comment]
Je suis tomber au pif sur cette issue.
Donc je vais répondre.

Inpustream a deux avantage majeur pour les playlist (quelle sois protéger ou non) : 
- Le choix de la qualité est directement intégré au lecteur de Kodi, c'est lui qui gère ce point tout seul.
- Avec Kodi 20, il y a la qualité adaptative qui est vraiment bien.
Et dans le cas de neko sama, c'est, de mémoire, obligatoire car ils utilisent un cryptage AES.

**Comment by sizanic** [comment]
Merci @Arias800 pour ton retour.
Ce qui nous ramène à ma toute première proposition.

Y a-t-il des contre-indications à l'ajouter en dépendance ?

**Comment by Arias800** [comment]
A ma connaissance, non.
Par contre, c'est plus safe de le mettre en facultatif car l'addon n'est pas directement installée sous Linux (il est séparer de Kodi comme les PVR).

**Comment by sizanic** [comment]
Le chargement de 'inputstream.adaptive' est maintenant intégré, si besoin : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/bc47cba8ff099eca7e458ff17c74b69810e65ec5/plugin.video.vstream/resources/lib/player.py#L119
