### ISSUE TITLE
live tv

### ISSUE THREAD

**Issue by hicha132** [Kodi-vStream/venom-xbmc-addons#3916]
bonjour le site live tv ne contient pas des liens s'il vous plaît
Arranger ça si possible

**Comment by TmpName** [comment]
Ben la je vois pas.
C'est des liens youtube, mais en modifiant le code pour utiliser le hoster de youtube (la partie avec get_video_info ne marche plus), ca plante en me disant que la video est privé, alors quelle passe sans probleme sur navigateur.

**Comment by sizanic** [comment]
Bonjour @hicha132 

En attendant, vous pouvez passer par Leet365, les liens sont tous fonctionnels.

**Comment by hicha132** [comment]
Leet365 Oui, il fonctionne bien en attendant de résoudre le problème de livetv

**Comment by TmpName** [comment]
Ben si tu pouvais tester la modif du debut, si ca marche je ferais la modif sur le fichier du site.

**Comment by hicha132** [comment]
> Ben si tu avais 10 mn pr tester la modif du debut, si ca marche je ferais la modif sur le fichier du site.

Ne fonctionne pas encore Expérimental

**Comment by sizanic** [comment]
> url2 = url.replace('/embed/', '/watch?v=').replace('?autoplay=1', '')

ça fonctionne chez moi.
J'ai ajouté le code.
Par contre j'ai laissé l'ancien embed en secours.

**Comment by sizanic** [comment]
Des corrections ont été apportées.
Fermeture de la demande.
