### ISSUE TITLE
Source wiflix.bet 

### ISSUE THREAD

**Issue by dragtaz** [Kodi-vStream/venom-xbmc-addons#3917]
Bonjour, la source wiflix.bet est devenue wiflix.zone et je voulais savoir où  et comment modifier l'url ou si cela sera fait prochainement. 

Merci.

**Comment by TmpName** [comment]
La modif est a faire ici https://github.com/Kodi-vStream/venom-xbmc-addons/commit/094209bb832278149ec2ec48de78844bac3f8d5f

Mais tant que l'ancienne url fait la redirection il y a pas d'urgence.

En tout cas merci pour l'info, la modif est deja en ligne.

**Comment by sizanic** [comment]
Demande traitée.
Merci
