### ISSUE TITLE
Evoload

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#3918]
Bonjour à vous,

Le Hoster Evoload ne figure plus sur les sites comme Wiflix et autres.
Celui-ci fonctionnait parfaitement avant la beta du 25/07.
Je ne comprends pas la raison.

Merci pour votre réponse.

**Comment by TmpName** [comment]
Hello, tu as regardé sur leur site ?
Je viens de regarder pour une serie au pif et je n'ai que dood, uqload et upstream

**Comment by Papounet58** [comment]
Effectivement.

**Comment by Papounet58** [comment]
Merci à toi.
Je viens de vérifier, plus aucun lien Evoload sur les sites, même sur la version avant béta depuis le +- 25 juillet.
