### ISSUE TITLE
Simplification des menus vStream

### ISSUE THREAD

**Issue by sizanic** [Kodi-vStream/venom-xbmc-addons#3921]
Au fil des années, vStream s'est vu agrémenté de nouvelles fonctionnalités.

On se retrouve maintenant avec un premier niveau de menu assez complet.
Et peut-être même un peu trop 😄 

L'idée est d'ouvrir le débat sur une proposition de simplification des menus.

Pour commencer, voici ma proposition, qui repose sur un regroupement par grand thème : 
- Ma bibliothèque
- Vidéos à la demande
- En direct
- Rediffusion
- Outils

Je détaille les sous-menus dans le premier message ci-dessous.

**Comment by sizanic** [comment]
Dans le détail, les menus existants se retrouvent répartis ainsi : 


Ma bibliothèque
	En cours de visionnage
	Marque-pages
	Mes comptes

Vidéos à la demande
	Rechercher
	Films
	Séries
	Documentaires
	Japanimes
	Dramas

En direct
	Sports
	Télévision
	Radio

Rediffusion
	Replay TV
	Sports
	Vidéo du net
	
Outils
	Sources
	Téléchargements
	Librairie
	Hoster-direct

**Comment by sizanic** [comment]
Et encore plus détaillé : 

```
Ma bibliothèque
	En cours de visionnage
		Toutes les catégories
		Films
		Séries
		Divers
	Marque-pages
		Films
		Séries
		Divers
	Mes comptes
		Tmdb
		Trakt
		Uptobox
		1fichier

Vidéos à la demande
	Rechercher
		Recherche thématique
		Films
		Séries
		Animés
		Dramas
		Historique de recherche
	Films
	Séries
	Documentaires
	Japanimes
	Dramas

En direct
	Sports
	Télévision
	Radio

Rediffusion
	Replay TV
	Sports
	Vidéo du net
	
Outils
	Sources
	Téléchargements
	Librairie
	Hoster-direct

```

**Comment by alKODIque** [comment]
J'adore..
Voici de petites modif terminologiques que je propose mais vraiment, ta proposition d'arborescence est quasi identique à ce que j'avais souhaité voir dans vStream ;)

```
**Mon suivi**
	En cours de visionnage
		Toutes les catégories
		Films
		Séries
		Divers
	Marque-pages
		Films
		Séries
		Divers
	Mes comptes
		Tmdb
		Trakt
		Uptobox
		1fichier
       **Historique de recherche**

**Vidéothèque**  (??)
	Rechercher
		Recherche globale
		Films
		Séries
		Animés
		Dramas

	Films
	Séries
	Documentaires
	Japanimes
	Dramas

En direct
	Sports
	Télévision
	Radio

Rediffusion
	Replay TV
	Sports
	Vidéo du net
	
Outils 
	Sources
	Téléchargements
	**Médiathèque locale**
	Hoster-direct
```

**Comment by sizanic** [comment]
Je me permet ces retours : 

# Historique de recherche

je trouve déroutant de déplacer **l'historique de recherche** ailleurs que dans un menu dédié à la recherche.
Car le but de l'historique de recherche est de relancer une recherche précédente.


# Recherche globale

Ma proposition de recherche thématique, vient remplacer la "recherche visuelle" qui est mal comprise.
Cela donne acces à des propositions de contenu par thèmes : 
Films (populaires)
Films (nouveautés)
Séries (par genre)
etc.

D'où la proposition de **Recherche par thème**.

Ce n'est pas l'accès à la **Recherche globale** actuelle.
La recherche globale disparaît, on choisit d'abord la catégorie (films, series), puis le clavier de recherche vient ensuite.


# Mon suivi
Je comprend la proposition du terme "Mon suivi", mais elle ne va pas ensuite avec le sous-menu "Mon compte Uptobox". Car ce compte ne contient pas du suivi mais du contenu personnel.

D'où l'idée premiere de "Ma bibliothqèque" correspondant à "Mon contenu", qui rassemble son contenu personnel (à travers ses comptes) et son contenu mis de coté à travers le marque-page ou la reprise.

Mais moi-même je cherche un meilleur terme que "Ma bibliothèque".

# Vidéothèque

ici, avec ma proposition de "Vidéo à la demande", je veux mettre en avant le "Streaming" ( = VOD).
**Vidéothèque** n'évoque pas le streaming.
On s'attend plutôt avec le terme "Vidéothèque" à ce que ça désigne du contenu local.

# Médiathèque locale

**Médiathèque locale** dans /Outils fait croire que vStream propose des outils en lien avec son contenu local ( disponible par exemple sur HDD).

**Comment by alKODIque** [comment]
Oui, j'ai aussi pensé comme toi après coup concernant l'historique de recherche.. mon premier réflexe en fait, allait dans le sens qu'il s'agissait de données "personnalisées " mais en y réfléchissant mieux, je pense comme toi 👍

Tes arguments m'ont convaincu aussi pour "vidéothèque".
Pour "Library, par contre, je n'aime pas le terme... mais je suis d'accord que "Médiathèque locale" peut porter à confusion 👍

**Comment by alKODIque** [comment]
Et j'ajoute que malgré la terminologie qui finalement, pourrait causer de longs débats inutiles 🤪 une fois que nous (utilisateurs) seront habitués au nouveau menu, la logique y est donc ce n'est que des détails :)

**Comment by alKODIque** [comment]
je pourrais proposer "Dossiers medias" au lieu de "Library" ?

**Comment by sizanic** [comment]
> je pourrais proposer "Dossiers medias" au lieu de "Library" ?

Pas mal 👍🏻 

Il faut bien se rappeler ce que ça fait pour trouver le bon terme.
(tu le sais sans doute, mon message est général)

En naviguant dans vStream, on peut ajouter des contenus dans cette "librairie" de vStream.
Et cette librairie est reconnu par Kodi en tant que "Source de médias".

Ici, la source "Films" est le dossier vStream/librairie/Films : 
![image](https://user-images.githubusercontent.com/47307622/184459744-6dfad878-1da9-4cb8-b346-6c01791acedb.png)


Donc il faudrait aussi revoir l'action "Ajouter à la Librairie" par l'action "Ajouter aux médias".

"Dossiers medias" serait donc l'emplacement pour retrouver nos médias ajoutés.

**Comment by alKODIque** [comment]
pour te donner une idée, les autres addons le nomme "Médiathèque" en traduction fr (pour library)

**Comment by sizanic** [comment]
Mais du coup, les contenus que l'on ajoute à cette médiathèque, ne devraient-ils pas plutôt être accessibles depuis le tout premier menu (Mon contenu / mon suivi) ?

**Comment by sizanic** [comment]
```
Mon contenu
	En cours de visionnage
		Toutes les catégories
		Films
		Séries
		Divers
	Marque-pages
		Films
		Séries
		Divers
	Dossiers médias
		Films
		Séries
		Enregistrements
	Mes comptes
		Tmdb
		Trakt
		Uptobox
		1fichier
```

**Comment by alKODIque** [comment]
je me crois pas..
je l'aurais aussi placé sous "Outils". 
parce qu'au final, nous ne retrouvons plus ce contenu dans vStream, mais dans la médiathèque locale de Kodi

**Comment by sizanic** [comment]
> parce qu'au final, nous ne retrouvons plus ce contenu dans vStream, mais dans la médiathèque locale de Kodi

On le retrouve bien toujours dans vStream 🤔 

(en plus d'être accéssible par kodi)

**Comment by alKODIque** [comment]
oui mais l'utilisation première est d'y avoir accès localement

**Comment by sizanic** [comment]
> oui mais l'utilisation première est d'y avoir accès localement

donc dans /outils, c'est plutot pour aller vérifier/administrer ce contenu. Je comprends.
(même si en vrai aucune action n'est possible 😄 )

**Comment by alKODIque** [comment]
Vrai.. ya pas d'action possible..
Alors ça revient un peu a ce que je disais plus haut :P on pourrait en débattre longtemps et a mon avis, inutilement hihi..
Que l'élément soit dans outils ou mes médias, ça va je crois. Et on aura vite fait de s'habituer à son emplacement :)
Je vote pour que la décision revienne au developpeur!! hihi

**Comment by sizanic** [comment]
> Que l'élément soit dans outils ou mes médias, ça va je crois.

oui, mais reste plus qu'à trouver le bon terme. Car "Mes médias" n'existe pas 😄 

Je propose "Mes contenus" pour le premier menu, pour regrouper ses contenus suivis et ses contenus premiums.

**Comment by sizanic** [comment]
Je vais commencer des modifications qui seront disponibles en versions Beta.
Ce qui permettra de tester.

Le débat reste ouvert avant finalisation.

J'attend vos retours.

**Comment by sizanic** [comment]
@detobel36, une proposition ?

**Comment by detobel36** [comment]
> @detobel36, une proposition ?

Sorry, les vacances... Pas trop de connexion internet 😛 

Personnellement j'ai l'impression qu'il y a déjà beaucoup de "sous menu".
Quand on fait une recherche de série par exemple (je fais de tête... J'ai pas Kodi en vacances 😉): recherche, recherche de type "Série", (entrer le nom), sélectionner le "site", choisir l'épisode (la saison à heureusement déjà été sélectionné en choisissant le site), sélectionner le provider, sélectionner le player.
Et puis quand aucun player est disponible, faut revenir en arrière, sélectionner un autre provider...

Mais ce que je décris ici n'est pas directement en lien avec le problème mentionné ici.
Pour vous donner une réponse complète, faut que je me pause... La comme ça je sais pas.

Ce que je peux dire par contre c'est qu'il est possible de "fusionner" l'historique de recherche avec la recherche. Il me semble que c'est l'extension "YouTube" qui fait ça. On clic sur recherche et la on a l'historique et un bouton "nouvelle recherche".

**Comment by sizanic** [comment]
Merci pour ton retour.

c'est vrai que pour l'instant, le sujet n'est pas de remettre en cause le processus pour atteindre les liens.

Concernant la recherche, je vois l'idée.
Dans le nouveau menu, on va déjà proposer de gagner une étape car il suffira maintenant d'un seul clic pour faire la recherche d'un film, alors qu'avant il fallait un premier clic pour saisir les termes recherchés, puis un deuxieme pour choisir la catégorie.

Pour le sous-menu de recherche, je pars sur ça, je ne vais pas "ouvrir" l'historique a ce niveau ; 
![image](https://user-images.githubusercontent.com/47307622/184503334-4bd0c63b-01b8-4884-b590-17c7764e2248.png)


Passes de bonnes vacances !
A+

**Comment by TmpName** [comment]
Ha oui refaire passer l "historique" sous "recherche", moi aussi je trouve ca bien.

**Comment by detobel36** [comment]
Hello,

Sur un PC c'est plus "lisible" :smile: 

Des petites questions:
<details> 
  <summary>Récap de la nouvelle arboraissance </summary>
<ul>
<li>
Mes contenus
    <ul>
    <li>
    En cours de visionnage
        <ul>
        <li>
        Toutes les catégories
        </li>
        <li>
        Films
        </li>
        <li>
        Séries
        </li>
        <li>
        Divers
        </li>
        </ul>
    </li>
    <li>
    Marque-pages
        <ul>
        <li>
        Films
        </li>
        <li>
        Séries
        </li>
        <li>
        Divers
        </li>
        </ul>
    </li>
    <li>
    Dossiers médias
        <ul>
        <li>
        Films
        </li>
        <li>
        Séries
        </li>
        <li>
        Enregistrements
        </li>
        </ul>
    </li>
    <li>
    Mes comptes
        <ul>
        <li>
        Tmdb
        </li>
        <li>
        Trakt
        </li>
        <li>
        Uptobox
        </li>
        <li>
        1fichier
        </li>
        </ul>
    </li>
    </ul>
</li>
<li>
Vidéos à la demande
    <ul>
    <li>
    Rechercher
        <ul>
        <li>
        Recherche thématique
        </li>
        <li>
        Films
        </li>
        <li>
        Séries
        </li>
        <li>
        Animés
        </li>
        <li>
        Dramas
        </li>
        <li>
        Historique de recherche
        </li>
        </ul>
    </li>
    <li>
    Films
    </li>
    <li>
    Séries
    </li>
    <li>
    Documentaires
    </li>
    <li>
    Japanimes
    </li>
    <li>
    Dramas
    </li>
    </ul>
</li>
<li>
En direct
    <ul>
    <li>
    Sports
    </li>
    <li>
    Télévision
    </li>
    <li>
    Radio
    </li>
    </ul>
</li>
<li>
Rediffusion
    <ul>
    <li>
    Replay TV
    </li>
    <li>
    Sports
    </li>
    <li>
    Vidéo du net
    </li>
    </ul>
</li>
<li>
Outils
    <ul>
    <li>
    Sources
    </li>
    <li>
    Téléchargements
    </li>
    <li>
    Librairie
    </li>
    <li>
    Hoster-direct
    </li>
    </ul>
</li>
</ul>
</details>

- Quel est le but de la catégorie "Mes comptes" ?  "Trakt" ou "Tmdb" ne permet pas de "lire" des films...  C'est pour configurer les comptes ?
- Quelle est la différence entre "Vidéos à la demande" et "Rediffusion" ?
  Je pense qu'on pourrait mettre les sous menus qui sont dans "Rediffusion" dans la même catégorie que "Vidéos à la demande".
- "Librairie" devrait être au pluriel si on est cohérent avec les autres sous-menu...
- Qu'est-ce que c'est `Hoster-direct` ?
- Quelle est la différence entre "Animés" et "Japanimes" ?
- Qu'est-ce que "Dossiers médias" ?


J'ai une autre proposition (mais pas sûr que ce soit une bonne idée et je suis même pas sûr que moi personnellement j'aimerais cette proposition, mais comme ça peut donner des idées, je donne:

- Films
    - Recherche
    - Vidéos à la demande
    - En cours de visionnage
    - Marque-pages
    - Dossiers médias
- Séries
    - Recherche
    - Vidéos à la demande
    - En cours de visionnage
    - Marque-pages
    - Dossiers médias
- Documentaires
    - Vidéos à la demande
    - En cours de visionnage (divers)
    - Marque-pages (divers)
- Animés/Japanimes
    - Recherche
    - Vidéos à la demande
    - En cours de visionnage (divers)
    - Marque-pages (divers)
- Dramas
    - Recherche
    - Vidéos à la demande
    - En cours de visionnage (divers)
    - Marque-pages (divers)
- Télévision
    - En direct
    - Replay TV
- Sports
    - En direct
    - Replay TV
- Radio
    - En direct
      (on affiche directement les éléments du sous menu, sauf si on rajoute d'autres sous-menu)
- Outils
    - Sources
    - Téléchargements
    - Librairie
    - Hoster-direct
    - Mes comptes
        - Tmdb
        - Trakt
        - Uptobox
        - 1fichier

Quand je met "Recherche", on met directement l'historique de recherche.

**Comment by sizanic** [comment]
Salut @detobel36,
merci pour ton retour,

> Quel est le but de la catégorie "Mes comptes" ? "Trakt" ou "Tmdb" ne permet pas de "lire" des films... C'est pour configurer les comptes ?

Dans "Mon contenu/Mes comptes", ce n'est pas pour configurer ses comptes, mais ça permet bien d'accéder aux "Contenus" de ses comptes.

L'accès à son compte Trakt permet par exemple d'accéder : 
- à ses listes personnelles
- à ses listes aimés
- à ses films surveillés
- à ses films regardés
- etc.

et tous les films proposés dans ces listes seront bien "lu" par vStream !

Et il en est de même pour TMDB, on peut accéder : 
- à  ses films favoris
- à ses listes
- etc.


Certaines personnes ne jurent que par les listes Trakt pour configurer leur skin Kodi.
En mettant leurs listes en widget.

De plus, il suffit à tout moment d'ajouter un élément à ses listes (depuis son téléphone par exemple, en navigant sur son compte trakt), pour les retrouver ensuite sur son kodi et "lire" le film par vStream.

=> Il faut avoir essayé Trakt une fois pour se rendre compte de tout de que ça peut faire.

=> Mais il s'agit bien d'accéder à "Son contenu", et ce sera "lu".

(le secret pour lire le film, c'est que vStream va lancer la recherche globale 😉 )

**Comment by sizanic** [comment]
> Quelle est la différence entre "Vidéos à la demande" et "Rediffusion" ?
> Je pense qu'on pourrait mettre les sous menus qui sont dans "Rediffusion" dans la même catégorie que "Vidéos à la demande".

Je me suis posé la même question, car dans les 2 cas il s'agit bien de regarder une vidéo .... à la demande.
Mais je classe dans rediffusion tout ce qui rediffusion télé (hors cinéma).
D'ailleurs, c'est bien "Replay TV" qui est utilisé ensuite en sous-menu.
Peut-être devrais-je utiliser le terme "Replay TV" dès la racine pour être cohérent 🤔 

Il est placé dessous "Direct" qui permet de regarder la TV en Direct.

Donc on pourrait avoir : 
- Vidéos à la demande
- TV en direct
- Replay TV

=> Mais je ne peux pas mettre "TV en direct" car dans cette section "Direct", il y a aussi des radios.


Je préfère différencier la "VOD cinéma" du Replay TV d'émissions.

**Comment by sizanic** [comment]
> "Librairie" devrait être au pluriel si on est cohérent avec les autres sous-menu...

Il n'y a plus de menu "Librairie" 😄 

Nous en sommes rendu à : 

![image](https://user-images.githubusercontent.com/47307622/184681818-3e3bbdd3-8d7b-4d28-9fd3-af3104f995e7.png)

**Comment by detobel36** [comment]
> Salut @detobel36, merci pour ton retour,
> 
> > Quel est le but de la catégorie "Mes comptes" ? "Trakt" ou "Tmdb" ne permet pas de "lire" des films... C'est pour configurer les comptes ?
> 
> Dans "Mon contenu/Mes comptes", ce n'est pas pour configurer ses comptes, mais ça permet bien d'accéder aux "Contenus" de ses comptes.
> 
> L'accès à son compte Trakt permet par exemple d'accéder :
> 
>     * à ses listes personnelles
> 
>     * à ses listes aimés
> 
>     * à ses films surveillés
> 
>     * à ses films regardés
> 
>     * etc.
> 
> 
> et tous les films proposés dans ces listes seront bien "lu" par vStream !
> 
> Et il en est de même pour TMDB, on peut accéder :
> 
>     * à  ses films favoris
> 
>     * à ses listes
> 
>     * etc.
> 
> 
> Certaines personnes ne jurent que par les listes Trakt pour configurer leur skin Kodi. En mettant leurs listes en widget.
> 
> De plus, il suffit à tout moment d'ajouter un élément à ses listes (depuis son téléphone par exemple, en navigant sur son compte trakt), pour les retrouver ensuite sur son kodi et "lire" le film par vStream.
> 
> => Il faut avoir essayé Trakt une fois pour se rendre compte de tout de que ça peut faire.
> 
> => Mais il s'agit bien d'accéder à "Son contenu", et ce sera "lu".
> 
> (le secret pour lire le film, c'est que vStream va lancer la recherche globale 😉 )

Okay, je vois. C'est ce que je fais avec TMDB (j'ai déjà essayé Track), je savais juste pas que c'était implémenté dans vStream.   
Au passage, dans la PR que j'ai ouverte on pourrait proposer l'option pour directement lancer le film (et pas juste la recherche)

**Comment by sizanic** [comment]
> Qu'est-ce que c'est Hoster-direct ?

Cela permet de coller directement un lien trouvé sur un site, alors même que ce site ne fait pas partie des sources de vStream.

Peut-être en effet que le terme est trop technique, on pourrait mettre : "Lien direct".

**Comment by detobel36** [comment]
> > Qu'est-ce que c'est Hoster-direct ?
> 
> Cela permet de coller directement un lien trouvé sur un site, alors même que ce site ne fait pas partie des sources de vStream.
> 
> Peut-être en effet que le terme est trop technique, on pourrait mettre : "Lien direct".

Hum, je le mettrais directement dans recherche non ?

**Comment by sizanic** [comment]
> Au passage, dans la PR que j'ai ouverte on pourrait proposer l'option pour directement lancer le film (et pas juste la recherche)

Bonne idée, oui 👍🏻

**Comment by sizanic** [comment]
>> Peut-être en effet que le terme est trop technique, on pourrait mettre : "Lien direct".

>Hum, je le mettrais directement dans recherche non ?

Bonne idée de le déplacer.
Mais d'un coté il s'agit bien d'un "outil" proposé par vStream.
Et d'un autre côté, je ne suis pas convaincu que dans Recherche soit l'endroit le plus approprié.


-> Je viens de voir que le message pour renseigner le lien est : "Tapez le lien que vous souhaitez rechercher".
Le message n'est pas correct !
=> Il ne s'agit pas vraiment d'une recherche.

Mais je n'ai pas d'autre endroit à proposer.
Il faudrait presque le mettre directement dans "Vidéos à la demande", en dernier.

**Comment by sizanic** [comment]
> Quelle est la différence entre "Animés" et "Japanimes" ?


Il n'y en a pas.
Les termes pour désigner les films d'animation ou séries d'animation en provenance du Japon et qui sont souvent l'adaptation d'un manga sont : 
- anime
- animé
- japanime
- japanimation

source : https://fr.wikipedia.org/wiki/Anime

Mais le terme "animé" utilisé jusqu'alors étant confusant pour les non-initiés, qui s'attendaient à retrouver des "Dessins animés".

=> On ne trouvera pas de dessins animé Disney dans cette section.

**Comment by sizanic** [comment]
> Qu'est-ce que "Dossiers médias" ?

Lorsqu'on navigue sur les liens de vStream, on peut les "Ajouter aux médias".

![image](https://user-images.githubusercontent.com/47307622/184686229-a04d80c3-b9e4-41a6-be86-bde00d4174a9.png)

Puis dans les outils, on pourra consulter les différents médias ajoutés dans les dossiers Films et Series.

Mais la GRANDE UTILITÉ de ces "Dossiers médias", est de les déclarer dans KODI.

![image](https://user-images.githubusercontent.com/47307622/184687125-742d1d12-f4d4-47f7-a3b0-7b97528f41f5.png)

Dans Kodi, il faut déclarer ces "Dossiers médias" comme des "Sources de médias".
Alors tous les médias contenus dans ces dossiers seront reconnus par Kodi COMME S'ILS ÉTAIENT EN LOCAL !!

**Comment by sizanic** [comment]
> J'ai une autre proposition (mais pas sûr que ce soit une bonne idée et je suis même pas sûr que moi personnellement j'aimerais cette proposition), mais comme ça peut donner des idées, je donne:

Cette approche par média n'est pas non plus la navigation que j'ai retenue lors de mes réflexions.
Mais comme tu as pris le temps de bien la décrire, cela me permet de la visualiser à la recherche d'idées ...

**Comment by sizanic** [comment]
> Mais comme tu as pris le temps de bien la décrire, cela me permet de la visualiser à la recherche d'idées ...

Avoir un raccourci de Recherche dans chaque catégorie média est bien, mais en complement d'un menu Recherche complet.
Je vais proposer ça.

**Comment by detobel36** [comment]
> Avoir un raccourci de Recherche dans chaque catégorie média est bien, mais en complement d'un menu Recherche complet. Je vais proposer ça.

Tu pourra faire un récap de la proposition "mis à jour" ?   
Pour pouvoir donner un avis sur la dernière idée "retenue" 😄

**Comment by sizanic** [comment]
La meilleure façon de se faire un avis est d'installer la Beta 😄 

Sinon, à l'écrit, ça donne : 

```
Mes contenus
     En cours de visionnage
          Toutes les catégories
          Films
          Séries/Japanimes
          Divers
     Marque-pages
          Films
          Séries/Japanimes
          TV
          Divers
     Téléchargements
     Enregistrements
     Mes comptes
          Trakt
               Films
               Séries
               Listes
               ...
          TMDB
               Films (Favoris)
               Séries (Favoris)
               Mes listes
               ...
          Uptobox
               Mes vidéos
               Mes fichiers
          1fichier

Vidéos à la demande
     Rechercher
          Recherche thématique
          Rechercher (Films)
          Rechercher (Séries)
          Rechercher (Japanimes)
          Rechercher (Drama)
          Rechercher (Documentaires)
          Historique de recherche
     Films
          Rechercher (Films)
          Films (Nouveautés)
          Films (Populaires)
          Films (Genres)
          Films (Années)
          Films (Alphabétique)
          Sources (Films)
     Séries
          Rechercher (Séries)
          Séries (Nouveautés)
          Séries (Populaires)
          Séries (Genres)
          Séries (Années)
          Séries (Alphabétique)
          Séries (VOSTFR)
          Sources (Séries)
     Documentaires
          Rechercher (Documentaires)
          Documentaires (Nouveautés)
          Documentaires (Genres)
          Sources (Documentaires)
     Japanimes
          Rechercher (Japanimes)
          Japanimes (Nouveautés)
          Japanimes (Populaires)
          Japanimes (Genres)
          Japanimes (Années)
          Japanimes (Alphabétique)
          Japanimes (VOSTFR)
          Sources (Japanimes)
     Dramas
          Rechercher (Dramas)
          Dramas (Nouveautés)
          Dramas (Populaires)
          Dramas (Genres)
          Dramas (Années)
          Dramas (Alphabétique)
          Dramas (VOSTFR)
          Sources (Dramas)

En direct
     Sports
          Sports (En direct)
          Sports (Chaines)
          Sports (Genres)
          Sources (Sports)
     Télévision
          Chaines (TNT)
          Chaines (Cinéma)
          Sources (Chaines)
     Radio
          Radio
          Radio (Genres)
          Radio (Alphabétique)

Rediffusions TV
     TV Replay (Nouveautés)
     TV Replay (Genres)
     TV Replay (sports)
     Sources (TV Replay)

Outils
     Ouvrir les paramètres
     Dossiers médias
     Téléchargements
     Lien direct
     Toutes les sources
```

**Comment by detobel36** [comment]
Du coup y a deux "Téléchargements" ?  Un dans "Mes contenus" et un autre dans "Outils".   
C'est quoi la différence ?

**Comment by sizanic** [comment]
Dans "Mes contenus/Téléchargements", ce sont les téléchargements que j'ai effectués (ou en cours) : 

![image](https://user-images.githubusercontent.com/47307622/184891248-3b15ccb4-9f2e-45cf-9c42-37af2d99bce1.png)

.
Dans outils, c'est la gestion des téléchargements.
.
![image](https://user-images.githubusercontent.com/47307622/184891410-117aaccc-8efc-407b-9d41-7167d12bfc53.png)

**Comment by sizanic** [comment]
Bonjour @alKODIque 

> dans la section recherche, il n'y a plus de recherche d'acteur, c'est volontaire?

Il n'y a jamais eu un accès direct vers une recherche d'acteur 🤔 

Il faut passer par : Recherche thématique / recherche TMDB / recherche (acteurs)

**Comment by detobel36** [comment]
Dans une idée de simplification, il ne faudrait pas "supprimer" cette partie "TMDB", "Track" ect... Il y a typiquement TmdbHelper qui fait "exactement la même chose".  La seule chose qu'il faut rajouter c'est le player/recherche via vStream.  Et ça on peut l'ajouter automatiquement à l'installation de vStream...

Ca simplifie les menus, réduit le code a maintenir et ne change rien aux fonctionnalités finales.

**Comment by alKODIque** [comment]
> Bonjour @alKODIque
> 
> > dans la section recherche, il n'y a plus de recherche d'acteur, c'est volontaire?
> 
> Il n'y a jamais eu un accès direct vers une recherche d'acteur 🤔
> 
> Il faut passer par : Recherche thématique / recherche TMDB / recherche (acteurs)

Ha, ok..
j'étais dans l'idée qu'on retrouvait cet élément, me suis trompé désolée ;)

**Comment by sizanic** [comment]
Mais ce serait l'occasion de remonter la partie "Recherche (TMDB)" d'un niveau : 

Plutot que : 
```
Rechercher
          Recherche thématique
                    Recherche (TMDB)
                              Rechercher un film
                              Rechercher une série
                              Recherche (Acteur)
                    Films (Nouveautés)
                    Films (Populaires)
                    Films (Genres)
                    Séries (Nouveautés)
                    Séries (Populaires)
                    Séries (Genre)
                    Acteurs (Populaires)
```

On aurait : 

```
Rechercher
          Recherche thématique
                    Rechercher (film)
                    Films (Nouveautés)
                    Films (Populaires)
                    Films (Genres)
                    Rechercher (série)
                    Séries (Nouveautés)
                    Séries (Populaires)
                    Séries (Genre)
                    Rechercher (Acteur)
                    Acteurs (Populaires)
```

**Comment by alKODIque** [comment]
> Dans une idée de simplification, il ne faudrait pas "supprimer" cette partie "TMDB" et "Track". Il y a typiquement TmdbHelper qui fait "exactement la même chose". La seule chose qu'il faut rajouter c'est le player/recherche via vStream. Et ça on peut l'ajouter automatiquement à l'installation de vStream...
> 
> Ca simplifie les menus, réduit le code a maintenir et ne change rien aux fonctionnalités finales.

Je ne crois pas que ce soit une bonne idée de retirer TMDb et Trakt.. Il s'agit d'un accès a nos comptes, directement depuis vStream. On y retrouve nos listes personnelles, notre calendrier de diffusion, et encore plus.
Ce n'est pas tout le monde qui utilise TMDbH, ce ne sont pas tous les skins non plus qui intègrent ses fonctionnalités.
Un accès depuis vStream est un gros plus, il me semble

**Comment by alKODIque** [comment]
@sizanic 
C'est peut-être moi qui suis aveugle, mais avec la bêta, je ne retrouve plus nule part la loupe de recheche par acteur..
De même, j'étais convaincu qu'elle figurait également dans la source Pastebin, mais je ne la retrouve plus

**Comment by alKODIque** [comment]
EDIT: ha oui... je la retrouve , désolée!! Dans TMDb
Donc c'est moi qui suis aveugle 📦

**Comment by alKODIque** [comment]
@sizanic 
J'ai vu que tu avais retiré la possibilité d'utiliser URLresolver.. Good! enfin, puisqu'iln'est plus utile et apportait plus de soucis qu'autre chose ;)

Dans le même ordre d'idée, depuis les paramètres, je ferais pareil pour ''utiliser la fenêtre d'information Extendedinfo''.. Puisque cet addon N,est plus maintenu depuis des années, et non compatible avec v19 a moin d'utiliser un de ses mod non officiel:

![Screenshot_20220816-101808](https://user-images.githubusercontent.com/49578130/184903360-00e452ca-e25a-4ca6-8f28-175a1786f700.png)

**Comment by doctornono** [comment]
> La meilleure façon de se faire un avis est d'installer la Beta 😄
> 
> Sinon, à l'écrit, ça donne :
> 
> ```
> Mes contenus
>      En cours de visionnage
>           Toutes les catégories
>           Films
>           Séries/Japanimes
>           Divers
>      Marque-pages
>           Films
>           Séries/Japanimes
>           TV
>           Divers
>      Téléchargements
>      Enregistrements
>      Mes comptes
>           Trakt
>                Films
>                Séries
>                Listes
>                ...
>           TMDB
>                Films (Favoris)
>                Séries (Favoris)
>                Mes listes
>                ...
>           Uptobox
>                Mes vidéos
>                Mes fichiers
>           1fichier
> 
> Vidéos à la demande
>      Rechercher
>           Recherche thématique
>           Rechercher (Films)
>           Rechercher (Séries)
>           Rechercher (Japanimes)
>           Rechercher (Drama)
>           Rechercher (Documentaires)
>           Historique de recherche
>      Films
>           Rechercher (Films)
>           Films (Nouveautés)
>           Films (Populaires)
>           Films (Genres)
>           Films (Années)
>           Films (Alphabétique)
>           Sources (Films)
>      Séries
>           Rechercher (Séries)
>           Séries (Nouveautés)
>           Séries (Populaires)
>           Séries (Genres)
>           Séries (Années)
>           Séries (Alphabétique)
>           Séries (VOSTFR)
>           Sources (Séries)
>      Documentaires
>           Rechercher (Documentaires)
>           Documentaires (Nouveautés)
>           Documentaires (Genres)
>           Sources (Documentaires)
>      Japanimes
>           Rechercher (Japanimes)
>           Japanimes (Nouveautés)
>           Japanimes (Populaires)
>           Japanimes (Genres)
>           Japanimes (Années)
>           Japanimes (Alphabétique)
>           Japanimes (VOSTFR)
>           Sources (Japanimes)
>      Dramas
>           Rechercher (Dramas)
>           Dramas (Nouveautés)
>           Dramas (Populaires)
>           Dramas (Genres)
>           Dramas (Années)
>           Dramas (Alphabétique)
>           Dramas (VOSTFR)
>           Sources (Dramas)
> 
> En direct
>      Sports
>           Sports (En direct)
>           Sports (Chaines)
>           Sports (Genres)
>           Sources (Sports)
>      Télévision
>           Chaines (TNT)
>           Chaines (Cinéma)
>           Sources (Chaines)
>      Radio
>           Radio
>           Radio (Genres)
>           Radio (Alphabétique)
> 
> Rediffusions TV
>      TV Replay (Nouveautés)
>      TV Replay (Genres)
>      TV Replay (sports)
>      Sources (TV Replay)
> 
> Outils
>      Ouvrir les paramètres
>      Dossiers médias
>      Téléchargements
>      Lien direct
>      Toutes les sources
> ```

J'aime beaucoup cette réorganisation des menus

**Comment by zombiB** [comment]
Slt à tous
Je propose de changer lien direct par "lecteur de lien" ou "resolveur de lien"  ou un autre terme qui explique l'usage de l'outil

**Comment by sizanic** [comment]
ça irait ?
en ajoutant un verbe d'action : 

Ouvrir un lien direct

**Comment by zombiB** [comment]
Oui je pense que c'est mieux,  meme "ouvrir un lien"  tout court ou "ouvrir un lien de vidéo"

**Comment by sizanic** [comment]
OK pour "Ouvrir un lien".

Car ce n'est pas forcement un "lien direct", ça peut être un "lien hoster" (c'est même plutôt un lien hoster d'ailleurs).
Mais pas besoin de préciser qu'il faut un lien vidéo 😄

**Comment by sizanic** [comment]
Menus simplifiés dans la version 2.0 👍🏻
