### ISSUE TITLE
la source french-stream-lol ne fonctionne plus

### ISSUE THREAD

**Issue by Glasco134** [Kodi-vStream/venom-xbmc-addons#3922]
**Décrivez le bug**
Depuis aujourd hui (ce dimanche) en faisant une recherche sur la source french stream lol (qui fonctionner tres bien depuis peu environ jeudi-vendredi) je n'ai plus aucun résultat sans message d'erreur ni quoique ce soit comme notifications

j'ai voulu regarder les autres sources mais  on dirait que les autres sources ne sont plus ou bien partiellement fonctionnelles

**Votre system**
- OS: android
- Appareil: mibox
- Version Kodi: 19.3
- Version Vstream: dernière version car je l'ai réinstallé

**Nous devons le reproduire**

- Nom du site: french-stream-lol
- Titre du fim/serie: exemple prey
- Nom du host (openload/vidzi/...): pas de lien

**Comment by sizanic** [comment]
Personnellement en essayant d'avoir des listes de films sur french stream lol, j'ai un message d'erreur qui m'encourage à installer flareSolver pour contourner un blocage CloudFlare.
Et en me rendant directement sur le site, je n'ai pas accès non plus aux médias.

vStream ne pourra rien afficher si le site n'affiche plus rien.

Sans compte premium, la source Wiflix semble etre la meilleure alternative pour l'instant (en attendant la prochaine version de vStream, d'ici quelques jours).

**Comment by sizanic** [comment]
ça a l'air d'être revenu.
Autant sur le site que sur vStream 👍🏻
