### ISSUE TITLE
Vstream problème

### ISSUE THREAD

**Issue by jackG71** [Kodi-vStream/venom-xbmc-addons#3923]
**Décrivez le bug**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

**Comment by sizanic** [comment]
Un peu court 🤔

**Comment by jackG71** [comment]
Mince ! J'ai dû faire une bêtise mon message n'apparaît pas ...

**Comment by sizanic** [comment]
ça devait sans doute commencer comme ça : 

```
bonjour
plus rien ne fonctionne sur vstream lorsque j'effectue une recherche rien ne se passe lorsque je clic sur le sport ou autre je n'ai pour seule réponse "aucune information " ! Je ne comprends pas pourquoi un tel bic alors que tout fonctionnait très bien depuis un moment ! Merci d'avance pour votre aide

Votre system
- OS: android 9.0.0 API LEVEL 28 (kernel Linux 4.9.113 )
- Appareil: Mi box s
- Version Kodi: 19.3
- Version Vstream: 1.9.3


```....

**Comment by jackG71** [comment]
**Décrivez le bug**
<!-- bonjour plus rien ne fonctionne sur vstream lorsque j'effectue une recherche rien ne se passe lorsque je clic sur le sport ou autre je n'ai pour seule réponse "aucune information " ! Je n'ai plus aucune source Je ne comprends pas pourquoi tout fonctionnait très bien depuis un moment ! Merci d'avance pour votre aide 

**Votre system**
- OS: android 9.0.0 API LEVEL 28 (kernel Linux 4.9.113 ) 
- Appareil: Mi box s
- Version Kodi: 19.3
- Version Vstream: 1.9.3

**Comment by jackG71** [comment]
bonjour plus rien ne fonctionne sur vstream lorsque j'effectue une recherche rien ne se passe lorsque je clic sur le sport ou autre je n'ai pour seule réponse "aucune information " ! Je n'ai plus aucune source Je ne comprends pas pourquoi tout fonctionnait très bien depuis un moment ! Merci d'avance pour votre aide 

**Votre system**
- OS: android 9.0.0 API LEVEL 28 (kernel Linux 4.9.113 ) 
- Appareil: Mi box s
- Version Kodi: 19.3
- Version Vstream: 1.9.3

**Comment by sizanic** [comment]
en allant dans ; 
- sources / wiflix / Films(derniers ajouts)

si tu n'as même pas la liste des films, c'est que tu n'as pas de réseau 😄

**Comment by sizanic** [comment]
Le probleme c'est que tu n'utilises pas les ponctuations.


`plus rien ne fonctionne sur vstream lorsque j'effectue une recherche rien ne se passe lorsque je clic sur le sport ou autre je n'ai pour seule réponse "aucune information "`

On ne sait pas si tu veux dire : 
- plus rien ne fonctionne sur vstream
- lorsque j'effectue une recherche rien ne se passe 
- lorsque je clic sur le sport ou autre je n'ai pour seule réponse "aucune information "`

Dans ce cas-là, vraiment **plus rien ne fonctionne**, aucune source, même la recherche et le sport.

OU si tu veux dire : 
- plus rien ne fonctionne sur vstream lorsque j'effectue une recherche
- rien ne se passe lorsque je clic sur le sport ou autre
- je n'ai pour seule réponse "aucune information "`

Dans cet autre cas, c'est **seulement la recherche et le sport** qui ne fonctionnent pas.
Mais tu peux toujours naviguer sur les sources pour voir les films.


Il faudrait vraiment être plus explicite.

**Comment by jackG71** [comment]
Pourtant lorsque j'utilise d'autre extension comme catch up tout fonctionne ...

**Comment by sizanic** [comment]
Un peu court 🤔

**Comment by jackG71** [comment]
@sizanic Je n'ai plus aucune source lorsque je fais une recherche que ce soit manuel ou dans film, série, sport etc

**Comment by jackG71** [comment]
Donc vraiment plus rien ne fonctionne

**Comment by jackG71** [comment]
@sizanic Je pense que mon problème vient du DNS de mon FAI  qui crée ce blocage je vais regarder ça ce WE et en changer ! Merci pour ton aide

**Comment by sizanic** [comment]
Le DNS peut bloquer quelque sources mais pas toutes.

Par exemple la source Wiflix n'est pas bloqué par les FAI.

Tu ne vois vraiment pas les films une fois dans :  vStream/sources / wiflix / Films(derniers ajouts)  ?

> Je n'ai plus aucune source lorsque je fais une recherche

Et sans passer par une recherche ?
en passant par le menu "/Sources/", le tout dernier menu.

Car tu peux ne plus avoir aucune source dans les recherches si toutes les sources sont désactivées dans le paramètres "Choix des sources pour les recherches" 🤔

**Comment by jackG71** [comment]
Salut @sizanic en réponse à tes questions : concernant wiflix je n'ai pas cette source ... lorsque je clic sur le menu film j'ai plusieurs choix : dernier ajout/qualité HD/les plus vues/mieux notes/genres/années/liste/VOSTFR/et sources qui est vide .... concernant l'autre menu source en bas page d'accueil j'ai 5 liens : Alldebrid/Debrid Link /Funeral for a manga/radio/top1000IMdb ... concernant choix des sources pour les recherches je ne trouve pas cela dans mes paramètres vstream ! Est ce que l'url de mon log que je vois affiché te serait utile ? Merci pour ton aide

**Comment by TmpName** [comment]
Ici
![kodi](https://user-images.githubusercontent.com/8311559/185743875-a9e43b70-4fc4-4910-9658-c0b7715196be.jpg)

**Comment by jackG71** [comment]
@TmpName Oui c'est bien ça ![image](https://user-images.githubusercontent.com/96024981/185744580-66347c39-2186-445a-9b1c-0d5a858aae61.jpeg)

**Comment by jackG71** [comment]
@TmpName ![image](https://user-images.githubusercontent.com/96024981/185744619-db33c3e5-5319-4e56-9fcf-699812f3dfb2.jpeg)

**Comment by sizanic** [comment]
![Uploading Screenshot_20220820-161510.jpg…]()

**Comment by sizanic** [comment]
![Screenshot_20220820-161510](https://user-images.githubusercontent.com/47307622/185751946-bff2a707-9106-4c72-9e9f-e273e50099b2.jpg)

**Comment by jackG71** [comment]
@sizanic Oui j'ai déjà fait ce matin "activer toutes les sources" ce matin et ça n'a rien changé

**Comment by jackG71** [comment]
Est ce que je vais devoir me résoudre a supprimer vstream pour le réinstaller ensuite ou changer mon dns ?

**Comment by sizanic** [comment]
DNS est hors sujet ici 🤔

Essaie une réinstallation par dessus.
Force l'installation depuis le dépôt.

**Comment by jackG71** [comment]
D'accord je vais faire ça merci @sizanic

**Comment by jackG71** [comment]
@sizanic Je te remercie pour ton aide, ton conseil était le bon tout est revenu dans l'ordre ! Merci aussi @TmpName pour l'intervention ! Merci beaucoup
