### ISSUE TITLE
Moteur de recherche Meagles

### ISSUE THREAD

**Issue by abda11ah** [Kodi-vStream/venom-xbmc-addons#3924]
Un moteur de recherche plus rapide que Vstream.

Si c'était intégré dans Vstream ça irait plus vite pour chercher.

htt ps://ww w.meagles.fr/

Bonne idée ?

**Comment by TmpName** [comment]
Ben bonne ideé je sais pas, mais tres bonne trouvaille.
Ca me servira plus tard pour trouver des adresses de site fonctionnelle quand celle utilisée disparaitrons.

Apres, personnellement ca ne m'epate pas, compares avec le film "brazil" sur Vstream et sur le site.

Surtout que contrairement a alluc qu'on utilisait avant de la meme maniere, les resultats ne sont pas un fichier video, mais un lien vers un site, si celui-ci n'est pas supporté par Vstream, non utilisable, et si il est supporté, le moteur de recherche de Vstream le trouvera aussi.

**Comment by sizanic** [comment]
oui, très bonne trouvaille en effet.

Mais je confirme, certains résultats font référence à des sources que vStream ne prend pas en compte.
Il faudrait alors les trier.

Le dernier moteur de recherche de vStream (qui scanne seulement ses propres sources), est maintenant très rapide (il faut penser à désactiver les sources qui nécessitent cloudflare).

-> Moins de 5 secondes pour un résultats parmi les sources supportés.

On ne gagnerait pas tant que ça à utiliser ce moteur.
