### ISSUE TITLE
🖐️Connection Refusée Compte Uptobox

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#3926]
![169663108-88eef6d7-0c80-4067-b390-c17b100067e2](https://user-images.githubusercontent.com/48101775/188266014-450d3291-9533-4e32-bf20-fae04d5c2bca.gif)La Connection est Refusée avec mon Compte Uptobox dans la rebrique "Mes comptes".
J'ai bien enregistré dans les paramètres de Vstream "nom utilisateur et mot de passe".
![201](https://user-images.githubusercontent.com/48101775/188266078-91371ea1-5ebf-4fe5-891e-63c0e3e3ba6d.gif)Même après avoir indiqué le N°Token de mon compte qui est premium .

Merci pour la réponse ✔️

**Comment by TmpName** [comment]
De memoire y a aussi une case a cocher.
Tu as regardé dans les logs si il n'y a pas un message utile ?

**Comment by sizanic** [comment]
> Même après avoir indiqué le N°Token de mon compte qui est premium 

Le token n'est pas utilisé pour l'accés à "Mes comptes", il faut les identifiants.

Le token est utilisé pour lire les médias dans les sources.
Et dans ce cas, ne renseigner que les identifiants est également suffisant car vStream va automatiquement renseigner le token en utilisant les identifiants.
Si le token ne se renseigne pas tout seul (lors de l'accès à une vidéo hors "mes comptes"), c'est que les identifiants ne sont pas bons.

**Comment by victore447** [comment]
![488](https://user-images.githubusercontent.com/48101775/188279758-517940c1-e3d5-4a9a-be37-11c05cb83d99.gif)J'ai activé dans paramètre la case correspondant pour  UPTOBOX.
Le premier message affiche "premium mode" et le 2eme "Authentification rate".
Toujours refusé pour Uptobox même en changeant le nom utilisateur par l'adresse mail.

![241](https://user-images.githubusercontent.com/48101775/188279804-5622435b-e840-4f11-9d5b-3ec50de7f726.gif)**Pour 1FICHIER  cela fonctionne :**
Le premier message affiche "premium mode" et le 2eme "Authentification réussi".

Pas de message dans les logs  ✔️

**Comment by victore447** [comment]
**Salut les loulous** ![156](https://user-images.githubusercontent.com/48101775/190928579-d6634418-6df0-4ad9-b749-3621e545e10c.gif)
Depuis la mise à jour vers  2.01 le problème est résolu et me connecte sur uptobox.live que j'ai  aperçu en ligne récemment.Et comme par hasard vous l'intégré dans le plugin.
![239](https://user-images.githubusercontent.com/48101775/190928615-665246c9-e124-4ca5-8f9a-8fe559d3fe51.gif)
-  https://lesseriestreaming.org
- https://www.hdss.uno
- https://www.voirfilms.io
- https://www.seriepourvous.rip 
Suite à la suppression de plusieurs sites
je vous joint des liens ci-dessus si cela vous intéressent✔️
![10](https://user-images.githubusercontent.com/48101775/190928759-aa72e607-e31e-4851-b7a7-cc9e705451ca.gif)

**Comment by sizanic** [comment]
Merci pour tes liens.

(sauf pour le lien Discord, nous n'y avons pas accès)

**Comment by victore447** [comment]
LE LIEN DISCORT C'EST SI VOUS CREER UN COMPTE GRATUITEMENT POUR SUIVRE LA TEAM 
![logo](https://user-images.githubusercontent.com/48101775/190929715-61f0a567-de96-40d0-a476-05395f3803f0.png)

**Comment by sizanic** [comment]
Je ne comprend rien.

Suivre quel team ?
Un compte gratuit de quoi ?
Un accès gratuit vers quoi ?

C'est un lien publicitaire pour nous inciter à créer un compte quelque part ?

De toute façon le lien ne va nulle part.

**Comment by victore447** [comment]
☝️La photo c'est tirexo et c'est en référence a la team tirexo qui est sur discord maintenant puisque le site n'exite plus.
Ils publient des annonces tel que création de uptobox.live etc..✔️

**Comment by sizanic** [comment]
La photo est arrivée après le lien, difficile de suivre tes indices.
Même avec la photo.

Il s'agit donc bien d'un lien d'invitation vers un serveur Discord.

Ce lien n'a pas sa place sur notre github.
Merci quand même, mais ici n'est pas un forum de partage de bons plans.

**Comment by victore447** [comment]
![143](https://user-images.githubusercontent.com/48101775/191214500-6a8cd595-06e6-48aa-931b-7e6f11a3a9a0.gif)En tout cas tout marche 
maintenant suite à la mise à jour 
si vous voulez clôturé le sujet✔️
![22655-applause03](https://user-images.githubusercontent.com/48101775/191214221-0a32a9e6-fadb-4eac-a66d-bd5d380414d5.gif)
