### ISSUE TITLE
Reprise de lecture avec fichier Strm

### ISSUE THREAD

**Issue by peto51** [Kodi-vStream/venom-xbmc-addons#3928]
Bonjour a tous,

Depuis quelques temps j'utilise des fichiers .strm pour ma bibliothèque de Films et Séries.
Ca fonctionne sans problème mise a part la reprise de lecture, lorsque je coupe le Film en plein milieu, il m'affiche l'icone comme quoi je n'ai pas terminé le film mais lorsque je relance il recommence du début.
J'ai fait le même test dans l'addon Vstream et dans mon compte hébergeur et là la reprise fonctionne.

System :
- Corelec
- Odroid N2
- Version Kodi 19.5
- Version Vstream 1.9.3

**Comment by sizanic** [comment]
Bonjour,

La lecture et la reprise des liens .strm est réalisée pas Kodi, pas par vStream.
Si ce sont des liens .strm vers du contenu de ta bibliothèque, il faudrait se rapprocher du support kodi.

Je ne suis pas sûr que l'on puisse faire quelque chose, on ne s'occupe que de vStream.

**Comment by peto51** [comment]
Le fichier strm ouvre un lien qui s'ouvre avec Vstream. C'est un lien 1fichier avec un compte premium.

**Comment by sizanic** [comment]
> j'utilise des fichiers .strm pour ma bibliothèque de Films et Séries.

On utilise généralement la formule "sa bibliothèque de films" pour désigner un contenu local sur disque dur.

> C'est un lien 1fichier avec un compte premium.

Donc finalement pas du tout du local 😄 

Je ne peux pas t'aider sur ce qui concerne 1fichier...

**Comment by alKODIque** [comment]
Je me souviens avoir lu qu'il y a un problème avec la reprise de lecture lorsque nous construisions notre médiathèque licale avec des fichiers.strm qui proviennent d'addons tiers.. c'est a dire, lorsque le lien a l'intérieur du fichier débute par plugin://
Je crois que c'est ce qui se passe ici.

Par contre, cette problématique n'est pas présente lorsque le .strm contient un fichier https://

je vais essayer de retrouver l'info car il me semble aussi que certains se sont penché 
sur le problème et ont apporté des pistes de solution qui fonctionnent dans certaines situations

**Comment by alKODIque** [comment]
Voilà la discussion sur le forum officiel Kodi: https://forum.kodi.tv/showthread.php?tid=358049

Et voilà la réponse concernant les strm en lien avec un addon: https://forum.kodi.tv/showthread.php?tid=358049&pid=2987303#pid2987303

Et comme majoritairement, il sagit d'addon ''illégaux'' qui offrent la possibilité de créer des fichiers .strm (lol), il ne faut pas s'attendre à ce que team kodi offre du soutient supplémentaire sur la question ;)

Mais peut-être que le développeur qui a mis au point la possibilité de points de reprises pourra donner plus d'indications via son github: https://github.com/xbmc/xbmc/pull/16076

**Comment by alKODIque** [comment]
@peto51 
si la reprise fonctionne bien à l'intérieur de vStream, c'est parce que c'est vStream qui gère d'un bout à l'autre..
Kodi n'intervient pas ''localement'' comme il le fait lorsque tu as migré ton lien à l'intérieur d'un fichier .strm.

Et j'aurais aussi une question qui s'adresse a un dev de vStream.. hihi
@sizanic  pourrait peut-être m'éclaircir? 

Pour la reprise de lecture, afin que Kodi reconnaisse qu'il s'agit bien d'un fichier média, je crois que le lien inclu dans le .strm doit obligatoirement se terminer par une extention reconnue (exemple, par .mkv)

Je demande car en local, un média en provenance de vStream est composé de:
- Un dossier --> qui est nommé idéalement au format ''Nom du film (année)'' (selon les règles recommandées kodi)
- Un fichier --> nom du film (année).strm
- Lien à l'intérieur du fichier --> 
`plugin://plugin.video.vstream/function=play&site=cHosterGui&sFileName=xxxxxxx&sMediaUrl=https%3A%2F%2Fxxx.mkv&sHosterIdentifier=lien_direct`

Donc je me demande si, dans le lien, il ne serait pas possible de faire en sorte d'inverser des fonctions afin que le ''.mkv'' soit à la fin  de ce lien ??

Dans mon exemple, le lien a l'intérieur du fichier .strm ressemblerait plus à: 
`plugin://plugin.video.vstream/function=play&site=cHosterGui&sFileName=xxxxxxx&sHosterIdentifier=lien_direct&sMediaUrl=https%3A%2F%2Fxxx.mkv`

Ainsi, peut-être que le .strm exporté en local serait mieux reconnu pour la reprise de lecture ?

**Comment by peto51** [comment]
Du coup j'ai fait l'essai en ajoutant le .mkv a la fin du lien 1fichier dans le fichier strm.
La reprise fonctionne si je reste dans la bibliothèque de film mais si je quitte et que je reviens sur la bibliothèque alors la ça reprend du début.

**Comment by sizanic** [comment]
ce n'est pas un souci de vStream
