### ISSUE TITLE
Format non supporté lors d'un ajout de code pastebin

### ISSUE THREAD

**Issue by clem-nesta** [Kodi-vStream/venom-xbmc-addons#3929]
**Décrivez le bug**

Il m'est impossible d'ajouter des codes Pastebin valides dans la source Pastebin.
L'erreur "Format non supporté" apparaît à chaque fois.

D'après mes investigations en mobilisant mes petites compétences, il y a selon moi, un soucis à l'exécution de la fonction de class _getCrypt() ligne 478 du fichier pastebin.py.
J'ai fait du pas à pas, et l'appel à cette fonction ligne 454 ne se passe pas bien.
Avec des xmbc.log, je me suis rendu compte que les objets retournés sont toujours vides.

A noter que je n'ai aucun problème sur Kodi Android ou des versions antérieures à la 19.4.

Merci pour ce travail extraordinaire !

**Votre system**
- OS: Linux Manjaro
- Appareil: Desktop X86
- Version Kodi: 19.4
- Version Vstream: 1.9.3

**Nous devons le reproduire**

- Nom du site: Pastebin
- Titre du fim/serie: N'importe quel code valide
- Nom du host (openload/vidzi/...):  Pastebin

**Comment by sizanic** [comment]
Bonjour,

Peux-tu nous confirmer qu'il s'agit déjà de toi qui as soumis ce probème sur le site des alKDOques ?

Afin de savoir si tu es la deuxième personne à signaler le problème, ou pas.

**Comment by clem-nesta** [comment]
Bonjour,
Oui c'est bien moi :)

**Comment by sizanic** [comment]
@clem-nesta
Le souci est-il toujours d'actualité ? (je ne retrouve plus ton sujet sur le site 🤔 )

Me confirmes-tu qu'il apparait seulement en version 19.4 de kodi, et qu'il n'était pas présent en 19.3 ?

Je penses que la gestion des fichiers est différente (la façon d'enregistrer un fichier ou la gestion des droits d'accès), et vStream n'arrive plus à enregistrer le fichier qui contient les codes saisis.

Les symptômes pourraient même être plus grave pour un nouvelle installation de vStream.
(tu avais déjà sans doute vStream avant de passer en V19.4).

**Comment by clem-nesta** [comment]
Bonjour @sizanic 
Je viens d'essayer sur la nouvelle version de vstream et malheureusement oui j'ai toujours le même problème.

Je n'ai pas supprimé le sujet du site pourtant.

Pour répondre à ta question, je me suis retrouvé dans les deux cas :
- Echec de tentative de renseigner un code après la mise à jour de Kodi vers 19.4 avec vstream déjà installé.
- Echec également sur une nouvelle installation de Kodi + Vstream.

**Comment by sizanic** [comment]
Merci pour ton retour.

concernant l'echec sur une nouvelle installation de Kodi + Vstream, ça ne me surprend pas.

J'ai invité quelqu'un de facebook à venir ici expliquer son souci, car il semble avoir le même.

En espérant que vous pourrez échanger vos experiences.

**Comment by JULIENBZH** [comment]
Bonjour, je rencontre également ce problème sur Linux(fedora) avec la version 19.4 de Kodi et la dernière de Vstream. Aucun problème sur Windows 11 ( sur la même machine).

**Comment by sharpordie** [comment]
@JULIENBZH, @clem-nesta
Pourriez-vous tester avec la dernière version de vStream ?

**Comment by sizanic** [comment]
> Pourriez-vous tester avec la dernière version de vStream ?

Cette version n'est pas encore sortie.
Une correction n'est disponible qu'en version Beta.

**Comment by clem-nesta** [comment]
Bonjour,
Devons nous tester la version Beta ou attendre la release ?

**Comment by sizanic** [comment]
Bonjour,
Si vous pouvez tester la beta, cela nous confortera avant de sortir la release 😁

**Comment by clem-nesta** [comment]
Je viens d'essayer sur mon Kodi Linux 19.4.
Malheureusement, j'ai toujours le même problème de "format non supporté"

**Comment by Arias800** [comment]
Sous linux, Kodi utilise la version de Python installé par l'OS directement.
Donc tout dépends de l'OS et de la version de ce dernier.

**Comment by sizanic** [comment]
Il faudrait donc que quelqu'un test sous linux en forçant l'installation d'un python 3.8 pour kodi 19.
Ou python 3.11 pour kodi 20.

**Comment by yodidon** [comment]
Je suis sous Linux avec nexus mais je vérifierai la version de Python

**Comment by clem-nesta** [comment]
Je viens d'installer python3.11 sur mon Ubuntu 22.04. Ainsi que Kodi 20.

Malheureusement, toujours le même problème.

**Comment by yodidon** [comment]
> Je viens d'installer python3.11 sur mon Ubuntu 22.04. Ainsi que Kodi 20.
> 
> Malheureusement, toujours le même problème.

effectivement apres maj vstream. avec python 3.11 et kodi 20 les codes pastbin ne fionctionnent plus

**Comment by alKODIque** [comment]
Bonjour,
Il y a une issue d'ouverte sur le forum officiel Kodi qui, justement, parle des problème de version python utilisées avec les systèmes sous Linux. 
Certains y apportent des possibles solutions à ce que je vois. Si jamais ça peut aider, voici le lien vers la discussion: https://forum.kodi.tv/showthread.php?tid=368069

**Comment by yodidon** [comment]
> Bonjour, Il y a une issue d'ouverte sur le forum officiel Kodi qui, justement, parle des problèmes de version python utilisées avec les systèmes sous Linux. Certains y apportent des possibles solutions à ce que je vois. Si jamais ça peut aider, voici le lien vers la discussion: https://forum.kodi.tv/showthread.php?tid=368069

normalement, correctif prêt à être déployé :)

**Comment by yodidon** [comment]
> Je viens d'installer python3.11 sur mon Ubuntu 22.04. Ainsi que Kodi 20.
> 
> Malheureusement, toujours le même problème.

correction dispo pour linux

**Comment by clem-nesta** [comment]
> correction dispo pour linux

J'ai pas compris ce qu'il fallait faire du coup. 
J'ai bien fait la mise à jour de Python mais j'ai le même problème.

**Comment by yodidon** [comment]
> > correction dispo pour linux
> 
> J'ai pas compris ce qu'il fallait faire du coup. J'ai bien fait la mise à jour de Python mais j'ai le même problème.

Il faut mettre le fichier modifié

**Comment by sizanic** [comment]
> Il faut mettre le fichier modifié
> https://github.com/Kodi-vStream/venom-xbmc-addons/blob/yodidon-patch-3/plugin.video.vstream/resources/sites/pastebin.py

Je regarde ta proposition et ce que tu fais est de demander à vStream d'utiliser Python 3 si on détecte être sous linux.

Sauf que c'est plus complexe que ça.

On peut être sous linux avec kodi 18 ou kodi 19 ou kodi 20, et utiliser pour ces versions du Python 2 ou du python 3 ou du python 3.1.

**Comment by sizanic** [comment]
@clem-nesta 

Essaies d'installer la version Beta de vStream en téléchargeant le zip depuis le bas de cette page : 
https://github.com/Kodi-vStream/venom-xbmc-addons

**Comment by yodidon** [comment]
> > Il faut mettre le fichier modifié
> > https://github.com/Kodi-vStream/venom-xbmc-addons/blob/yodidon-patch-3/plugin.video.vstream/resources/sites/pastebin.py
> 
> Je regarde ta proposition et ce que tu fais est de demander à vStream d'utiliser Python 3 si on détecte être sous linux.
> 
> Sauf que c'est plus complexe que ça.
> 
> On peut être sous linux avec kodi 18 ou kodi 19 ou kodi 20, et utiliser pour ces versions du Python 2 ou du python 3 ou du python 3.1.

Oui c’est pour ça que je te disais que ce serait plus judicieux de le mettre sous condition de nexus, puisque pour les autre version le problème n’est pas connu.

**Comment by sizanic** [comment]
J'ai fait une modification qui consiste à utiliser la bonne version en fonction de la version de python (pas en fonction de la version de Kodi).

**Comment by yodidon** [comment]
> J'ai fait une modification qui consiste à utiliser la bonne version en fonction de la version de python (pas en fonction de la version de Kodi).

Tu as fait cette modification sur la dernière mise à jour ?

**Comment by sizanic** [comment]
> Tu as fait cette modification sur la dernière mise à jour ?

oui, tu ne la vois pas ?

https://github.com/Kodi-vStream/venom-xbmc-addons/blob/91906d2b82ffa012e0fb0e0555761529618e93a6/plugin.video.vstream/resources/sites/pastebin.py#L72

je me suis même fait aider : 
![image](https://user-images.githubusercontent.com/47307622/210076309-b4728187-5886-469b-b00c-6de2e75f8018.png)

**Comment by yodidon** [comment]
autant pour moi je pensais qu'elle était dans la 2.3.0

**Comment by sizanic** [comment]
oui, dans la derniere mise à jour du fichier, pas dans la derniere mise à jour de la version 😆

**Comment by clem-nesta** [comment]
Désolé mais ce n'est pas mieux.

**Comment by sizanic** [comment]
@clem-nesta 

Le probleme n'est pas la saisie en elle-même.
Lorsque qu'on renseigne un code, vStream va lire le contenu associé.
Et dans ce cas, il refuse le code car il n'arrive pas à récupérer les medias associés.
En renseignant les codes dans le fichiers settings, vStream n'arrivera pas mieux à récupérer les médias.

La vérité est ailleurs, il nous faudrait ton fichier kodi.log.

**Comment by clem-nesta** [comment]
[error-kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/10327363/error-kodi.log)

Est-ce suffisant ? Ce sont les erreurs en lien avec Vstream

**Comment by sizanic** [comment]
impeccable, il y a l'erreur que je recherche 👍🏻

**Comment by sizanic** [comment]
J'ai ajouté des informations dans le log, il me faudrait un nouveau log à partir de la version Beta de vStream.

**Comment by sizanic** [comment]
@clem-nesta 

A tester avec la dernière Version 2.4.0 de vStream

**Comment by clem-nesta** [comment]
Bonsoir, 
Je viens d'essayer avec la version 2.4.1 et j'ai bien accès au contenu du pastebin.

Par contre si je regarde le log j'ai quand même des erreurs :

**Comment by sizanic** [comment]
Merci pour ton retour.

Sujet clos 👍🏻
