### ISSUE TITLE
Ajout site fifa+ car trop complexe pour moi

### ISSUE THREAD

**Issue by shadsnob** [Kodi-vStream/venom-xbmc-addons#3932]
Bonjour, pouvez-vous rajouter le site
https://ww w.fi fa.com/fi faplus/fr/live
j'ai essayé de créer par moi même et avec l''aide de Clark Kent sur discord mais je n'arrive pas a un résultat je vois bien l'information a faire en regex mais je sais pas comment l’intégrer au script merci

**Comment by TmpName** [comment]
J'ai voulu jeter un oeuil, j'ai pas pu lancer une video, mais je crois que c'est un lecteur maison ?

**Comment by shadsnob** [comment]
Voici mon regex pour visualiser les matchs diffuser <img src="En%20direct_fichiers\/(.+?)\.png" class="mcls-card-team-logo">(.+?)<\/span>

**Comment by sizanic** [comment]
@TmpName 
tu as réussi à aller jusqu'à la vidéo dans vStream ? (sans qu'elle se lance).

**Comment by sizanic** [comment]
@shadsnob 
j'ai l'impression que cette regex permet juste d'avoir l'image de prévisualisation, mais pas le lien de la vidéo.

**Comment by shadsnob** [comment]
le lien se creer a partir de ces liens qui donne un json avec le lien de la video en m3u8

https://mcls-api.mycujoo.tv/bff/events/v1beta1/2DNremvjZlZ907nfZSW66W92ngj

https://mcls-api.mycujoo.tv/bff/events/v1beta1?order_by=ORDER_START_TIME_ASC&page_size=8&start_after_time=2022-09-10T22%3A00%3A00.000Z&start_before_time=2022-09-11T22%3A00%3A00.000Z

**Comment by sizanic** [comment]
top, je n'étais pas aller aussi loin 👍🏻

**Comment by shadsnob** [comment]
Par exemple ce lien https://mcls-api.mycujoo.tv/bff/events/v1beta1?order_by=ORDER_START_TIME_ASC&page_size=15&start_after_time=2022-09-12T12%3A10%3A00.000Z&status=EVENT_STATUS_STARTED qui doit être créer a partir de la https://www.fifa.com/fifaplus/static/js/32.0b2eebc8.chunk.js

permet en réponse d'avoir un json avec dedans le lien m3u8 et dans l'en tête on a 
GET /bff/events/v1beta1?order_by=ORDER_START_TIME_ASC&page_size=15&start_after_time=2022-09-12T12%3A10%3A00.000Z&status=EVENT_STATUS_STARTED HTTP/2
Host: mcls-api.mycujoo.tv
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
Accept: application/json
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Authorization: Bearer 0FIQ3SKOSF09NH33IQO7IRARV5BSPT2N
Content-Type: application/json
Origin: https://www.fifa.com
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
ETag: 0
Pragma: no-cache
Cache-Control: no-cache
TE: trailers

**Comment by shadsnob** [comment]
J'ai trouvez une personne qui a créer carrément le plugins pour kodi https://iwf1.com/kodi/plugin.video.fifaplusbeta

**Comment by sizanic** [comment]
du coup, ce sera plus facile si on veut récupérer.

Mais veut-on le récupérer vu que un addon existe déjà et qu'il propose sans doute de meilleurs menus 🤔

**Comment by shadsnob** [comment]
sauf que les menus sont en espagnol ou moitie anglais et je n'arrive pas a le faire marcher sur kodi 18.9 mais fonctionne sous kodi 19.

**Comment by sizanic** [comment]
Pour le passer en francais, il faut changer : locale=fr 
dans la fonction root( )
du fichier fifa.py
ligne 26

**Comment by shadsnob** [comment]
J'ai fait un recap a modifier pour avoir du full français:
[fifa.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/9557071/fifa.txt)
