### ISSUE TITLE
Episode suivant 

### ISSUE THREAD

**Issue by untiiis** [Kodi-vStream/venom-xbmc-addons#3933]
**Décrivez le bug**

Bonjour, 
Il y a souci qui était là auparavant, puis reglé, et maintenant il recommence et je n'ai vu aucun ouvrir un sujet sur cela 
C'est la fonctionnalité de "épisode suivant" 
Vstream ne lance que un seul épisode après celui en cours et il s'arrête, et un autre truc, c'est que à l'épisode suivant, il n'y a pas d'informations affichées quant à la saison et le numéro de l'épisode 
Et un autre truc concernant les sources, je comprends que peut-être c'est assez confus d'en rajouter, mais il y a de bon site streaming comme hdss.uno (après s'il change de url, je ne sais pas) 

**Votre system**
- OS: [Android]
- Appareil: [Android box mi box s]
- Version Kodi: [18.9]
- Version Vstream: [la dernière]

**Comment by sizanic** [comment]
Bonjour.
Les soucis sur l'enchaînement des épisodes sera réglée dans la prochaine version (d'ici une semaine).
Merci pour le site, on va l'étudier.

**Comment by untiiis** [comment]
> Bonjour. Les soucis sur l'enchaînement des épisodes sera réglée dans la prochaine version (d'ici une semaine). Merci pour le site, on va l'étudier.

D'accord. Merci pour votre réponse et les efforts fournis

**Comment by detobel36** [comment]
Est-ce que cette issue est toujours d'actualité ?
La version 2.0.0 corrige le soucis non ?

**Comment by detobel36** [comment]
> > **Décrivez le bug**
> > Bonjour, Il y a souci qui était là auparavant, puis reglé, et maintenant il recommence et je n'ai vu aucun ouvrir un sujet sur cela C'est la fonctionnalité de "épisode suivant" Vstream ne lance que un seul épisode après celui en cours et il s'arrête, et un autre truc, c'est que à l'épisode suivant, il n'y a pas d'informations affichées quant à la saison et le numéro de l'épisode Et un autre truc concernant les sources, je comprends que peut-être c'est assez confus d'en rajouter, mais il y a de bon site streaming comme hdss.uno (après s'il change de url, je ne sais pas)
> > **Votre system**
> > ```
> > * OS: [Android]
> > 
> > * Appareil: [Android box mi box s]
> > 
> > * Version Kodi: [18.9]
> > 
> > * Version Vstream: [la dernière]
> > ```
> 
> il y a un service qui s'appelle UpNext (https://github.com/im85288/service.upnext) pour aller au prochain épisode, mais je ne suis pas sur de si vous pouvez l'implémenter ou pas

Il est déjà intégré 😉

**Comment by detobel36** [comment]
> Est-ce que cette issue est toujours d'actualité ? La version 2.0.0 corrige le soucis non ?

Du coup... C'est réglé non ?
