### ISSUE TITLE
Remise de l'onglet RECHERCHE VISUELLE

### ISSUE THREAD

**Issue by Hackulo** [Kodi-vStream/venom-xbmc-addons#3943]
Bonjours,
Je vien d ouvrir kodi, est la surprise. 
Je m'aperçois que Vstream à été mis à jour 👌.
Par contre je m'aperçois que l'onglet RECHERCHE VISUELLE n'est plus présent. 
Pourquoi ?
Je me sert énormément de cette onglet pour rechercher des nouveaux films ou série le VISUELLE  ses quand même important. 

Merci de réintégrer cette onglet.
Merci la team pour votre soutien, votre avancée continuez vaillant. 

Hackulo.

**Comment by sizanic** [comment]
Bonjour,

Nous l'avons juste renommé en "Recherche thématique".

Pour rechercher selon les thèmes : populaires, les mieux notés, selon l'acteur, etc...

Le VISUELLE est important, sauf que tous les menus proposent le visuel des films 🤔 
(si le paramètre "recherche des métadonnées" est bien activé).

**Comment by Hackulo** [comment]
Oui effectivement, mes ses moins pratique.
Car on est obliger de sélectionner chaque sources pour voire si il y a un nouveau films. 

Avant au sélectionner le films et il ne donner les sources ou le films été disponible.
Possible de faire une modification pour améliorer sa?

**Comment by sizanic** [comment]
Le menu "recherche visuelle" est toujours là avec le même fonctionnement qu'avant.
On sélectionne un film selon son visuel et il donne les sources où le film est disponible.

**Comment by Hackulo** [comment]
Alors voici, se que sa donne .

![20220924_143335.jpg](https://user-images.githubusercontent.com/114289636/192098274-a8b54131-a38e-4303-b7ee-973c2e161793.jpg)


![20220924_143353.jpg](https://user-images.githubusercontent.com/114289636/192098319-f936687f-7e70-40c9-abe7-ff663484d831.jpg)![20220924_143358.jpg](https://user-images.githubusercontent.com/114289636/192098334-5f033b6f-8ba1-4a07-beff-98a493bd4df1.jpg)![20220924_143410.jpg](https://user-images.githubusercontent.com/114289636/192098351-a3637ee3-462f-43f2-8f27-ef656f6c8902.jpg)![20220924_143426.jpg](https://user-images.githubusercontent.com/114289636/192098366-39c83874-5d65-49ea-9685-4b14ef535034.jpg)![20220924_143445.jpg](https://user-images.githubusercontent.com/114289636/192098401-bb710488-edcd-444c-b031-ccc28165340d.jpg)

**Comment by sizanic** [comment]
Merci pour toutes ces belles images, dans le doute où je ne saurais pas à quoi ressemble vStream.
J'ai bien vérifié toutes tes photos, et je vois au moins que je n'ai pas fait de fautes dans ces menus que j'ai créé moi-même 🤔 


Maintenant, pour en revenir à ta question, j'ai répondu dans mon premier message et je vois que tu ne tiens pas compte de ma réponse. Je ne sais pas quoi te dire de plus.

Je t'ai dit où trouver ce que tu cherches.
Et ça n'apparait pas sur tes photos.

**Comment by alKODIque** [comment]
@Hackulo 
Regarde la vidéo a partir de 10 secondes: https://vimeo.com/750635750

**Comment by sizanic** [comment]
Merci @alKODIque pour cette vidéo, car j'ai juste dit que le menu a été renommé en "Recherche thématique".
Sans préciser que cette "recherche" se trouve dans un menu qui s'appelle simplement "Rechercher".

Pour ceux qui n'ont pas trouvés, il faut passer à l'étape supérieure avec des vidéos 😆

**Comment by Hackulo** [comment]
Merci, alors il doit y avoir un problème car depuis le mise a jour, je nes plus cette onglet. 🙄

Au passage, merci d être cool.

**Comment by sizanic** [comment]
Dans ton message avec toutes les photos, je vois le menu "Rechercher" sur ta 3eme photo !!
Juste au dessus de ta sélection "Films".

Comme sur la vidéo.

Même la vidéo ne suffit pas 🤔

**Comment by Hackulo** [comment]
J'ai réinstaller et sa fonctionne.
Sûrement un bug à la mise à jour.

Merci alko❤
