### ISSUE TITLE
plus la recherche visuelle ? et logo bizarre !

### ISSUE THREAD

**Issue by solspire** [Kodi-vStream/venom-xbmc-addons#3947]
Mon logo vstream n'est plus celui habituel (play jaune à la place du A etc)
Pourtant j'ai bien la bonne source du repository.
Je suis avec un google Chromecast TV kodi 19.3

Le problème est que il n'y a plus LA RECHERCHE VISUELLE !

C'est essentiel pour faire une recherche.
Actuellement il faut choisir les sources avant.. 
pas de suggestion avant d'avoir selectionner une source c'est pas pratique

Cdt

**Comment by sizanic** [comment]
Bonjour,

Si ton logo à changé c'est parce que tu as maintenant la dernière version de vStream, la version 2 !

**Dans cette nouvelle version, aucune fonctionnalité de vStream n'a été retirée !!**

Les menus ont été regroupés, et certains ont été renommés.
Par exemple, l'ancien menu "Recherche visuelle" a été renommé en "Recherche thématique", dans la section "Rechercher".
Car elle permet de rechercher par thème : populaires, les mieux notés, par genre, selon l'acteur, etc.


Il ne faut pas hésiter à parcourir tous les menus de vStream !
En plus d'y retrouver ce qui n'a jamais disparu, on peut y découvrir de belles fonctionnalités insoupçonnées !

**Comment by TmpName** [comment]
> Il ne faut pas hésiter à parcourir tous les menus de vStream !
> En plus d'y retrouver ce qui n'a jamais disparu, on peut y découvrir de belles fonctionnalités insoupçonnées !

Lol, je confirme, je suis dessus aussi ^^.

**Comment by solspire** [comment]
Hello,
mumm.. hommes de peu de foi ;) Poster est pour moi un dernier recours, je fais mes devoirs avant.

Comme vous ne semblez pas me croire voici une video de ma navigation en direct :
https://photos.app.goo.gl/mgk67aXqTqSukn1U9

Je peux fouiller autant que je veux mais 
-la recherche visuelle (ou thématique du coup) ne m'affiche pas les jaquettes.
-les recherches series après avoir cliqué sur la recherche thématique ne marchent pas pour moi !!!
En fait la seule chose qui fonctionne c'est la recherche au 1er niveau, faut savoir quoi rechercher du coup.

Coté TV et redif je préfère Catch-up TV & More car ça ne marche pas super (pas du tout) sur vstream

Donc je songe à retrouver la version précédente qui faisait le job avec son super cherche visuelle qui me manque terriblement.

Aussi je me demande pourquoi toujours IMDB et jamais Allocine ..étant un plugin FR .. Un "tendance" + "bonne note" a de bonne chance d'être bon. Coté amélioration je choisirai d'avoir plus de filtres. En effet on cherche IMDB film 2021 et après on peut pas filtrer d'avantage. Les sections créés apportent un 1er niveau de filtre mais après ..on doit se laisser porter par le vent. L'autre solution  ce serai d'avoir l'affichage jacket avec /année/genre/note/nb de vote/ en dessous de la jacket plutôt que caché dans information.

Bon je m'égare, non pas de jacket pour moi dans cette nouvelle version. Et vous oui !? ça doit être sous mon nez alors !! Et pourtant je clic je clic je clic partout !

**Comment by sizanic** [comment]
> Comme vous ne semblez pas me croire voici une video ...


On ne semble pas te croire à propos de quoi ???

voici ton message initiale : 
```
Mon logo vstream n'est plus celui habituel (play jaune à la place du A etc)
Pourtant j'ai bien la bonne source du repository.
Je suis avec un google Chromecast TV kodi 19.3

Le problème est que il n'y a plus LA RECHERCHE VISUELLE !

C'est essentiel pour faire une recherche.
Actuellement il faut choisir les sources avant..
pas de suggestion avant d'avoir sélectionner une source c'est pas pratique
```

Et nous t'avons répondu : 

> Mon logo vstream n'est plus celui habituel (play jaune à la place du A etc)
> Pourtant j'ai bien la bonne source du repository.

Notre réponse : c'est normal que logo est changé, c'est la dernière version.

> Le problème est que il n'y a plus LA RECHERCHE VISUELLE !

Notre réponse : maintenant le menu s'appelle "Recherche thématique"

> C'est essentiel pour faire une recherche.
> Actuellement il faut choisir les sources avant..
> pas de suggestion avant d'avoir selectionner une source c'est pas pratique


Sélectionner une source avant de voir les propositions à toujours exister, lorsque qu'on ne passait par la recherche visuelle (qui s'appelle maintenant "thématique")

Notre réponse : aucune fonctionnalité de vStream n'a été retirée (ni ajoutée ! )

**Comment by sizanic** [comment]
> Je peux fouiller autant que je veux mais
-la recherche visuelle (ou thématique du coup) ne m'affiche pas les jaquettes.

Tu ne nous a jamais parlé de ce problème.

> -les recherches series après avoir cliqué sur la recherche thématique ne marchent pas pour moi !!!

Tu ne nous a jamais parlé de ce problème.

> mumm.. hommes de peu de foi ;)

Je ne sais pas qui sont les hommes de peu de foi, mais j'en connais un qui est de mauvaise foi ;)

**Comment by sizanic** [comment]
Pour les "nouveaux problemes" que tu décris, je te propose de les mentionner dans un nouveau sujet.

Je dis bien "nouveaux" car pour tes précédentes questions*, qui sont dans le titre de ton message "plus la recherche visuelle? et logo !", nous t'avons apporter les réponses.

(*questions :  je dis "questions" et pas "problemes" car ce n'est pas un probleme d'avoir renommer un menu et changer le logo.)


Et pour les propositions que tu cites, nous pouvons te répondre (et en débattre), mais également dans un autre sujet.

=> donc 2 sujets à créer.

**Comment by solspire** [comment]
Ok je vais créer un autre post : "plus de vue jaquettes ni de résultat en recherche thématique/visuelle depuis la MAJ (kodi 19.3 Vstream 2.0.1 sur Chromecast)"

J'aurai du être plus clair, c'est que je me suis dit recherche visuelle = vue visuelle des jaquettes.

Curieusement mon PC lui a toujours l'ancienne version (kodi 1.4, vstream 1.8). 
Vstream ne se met pas à jour alors qu'il est bien installé avec le même repository et y a bien la coche de mise à jour auto.

Je vais déplacer ma mauvaise foi ailleurs ;) merci pour vos réponses très rapide.
Bon dimanche

**Comment by alKODIque** [comment]
@solspire 
Désolée, mais le titre que tu souhaites donner a ta nouvelle issue n'a pour moi aucune signification...
Premièrement, la recherche visuelle existe toujours comme mentionné 2 fois plus haut. Elle a été renommée en ''Recherche thématique,
Deuxièmement, le problème que je note sur ta vidéo est que les menus de la recherche thématique ne s'ouvrent pas. Ce qui est selon moi, le nom que devrait porter le titre de ton issue!!

Et troisièmement, je suis certaine que les développeurs apprécieraient avoir un log ou tu reproduis l'erreur afin de vérifier ce qui ne va pas sur ton installation.

Bonne journée!

**Comment by solspire** [comment]
ok merci pour la suggestion du titre.
Coté log j'y ai bien pensé mais c'est sur ma tv.. pas facile de sortir le log (dongle Chromecast ne va pas repérer le clef usb sur la TV). je vais voir si il est possible de le sortir en l'enregistrant direct sur mon pc par réseau DLNA.

**Comment by alKODIque** [comment]
tu peux simplement installer l'addon "Log files uploader" disponible sur le dépôt officiel kodi et copier-coler le lien donné depuis cet addon.
Voir comment utiliser ici: https://lesalkodiques.com/docs/trucs-et-astuces/utiliser-laddon-log-file-uploader/
