### ISSUE TITLE
Soucis French Stream Lol

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#3948]
Bonsoir la team 
Alors voilà mon petit soucis avec french stream lol
C est quand je veux regarder un épisode je clique sur la série ça part sur les épisodes mais quand je choisi un épisode sa m emmène pas au lien il se passe rien pareil un film quand j appuie rien ne se passe 

Merci de m aider 
Sa me fais qu avec ce site 

**Votre system**
- OS: [Windows, Android]
- Appareil: 
- Version Kodi: [19.3
- Version Vstream: [2.0.1

**Comment by TmpName** [comment]
Chez moi ca passe, surement a cause de la correction de @sizanic https://github.com/Kodi-vStream/venom-xbmc-addons/commit/e2848b9c50f368fbf4340a782743fa5afafa66e2

**Comment by sizanic** [comment]
Bonjour,

Oui, il s'agit d'un probleme avec la version 2.0.1, c'est corrigé.
Ce sera disponible dans la prochaine version, prévue ce mois d'octobre.


TpmName, en tant que développeur, tu dois avoir la correction en effet.

**Comment by Mokoman30** [comment]
Ok Merci la team et bon courage
