### ISSUE TITLE
 les menus de la recherche thématique ne s'ouvrent pas (kodi 19.3 Vstream 2.0.1 sur Chromecast)

### ISSUE THREAD

**Issue by solspire** [Kodi-vStream/venom-xbmc-addons#3949]
Bonjour,
Je suis sur kodi 19.3 et le nouveau Vstream 2.0.1 (nouveau logo) sur un google Chromecast.
Avant Vstream fonctionnait très bien. Je faisais clic recherche visuelle + clic series populaire = affichage des jackets , clic choix de la serie + clic choix de l'épisode = ça scrape les sources =chargement et affichage des résultats classé par site source + clic +clic et c'est bon :)

Maintenant je fais video à la demande/rechercher/recherche thématique/séries populaires/... ça réfléchi vite fait puis rien je reste sur le menu de la recherche thématique. Dons pas résultat, pas d'affichage de Jacquette.

Merci d'avance pour votre aide.

**Comment by solspire** [comment]
Voici ce que dit le log :
WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!

Fichier entier ici :
[log vstream.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/9741602/log.vstream.txt)

**Comment by alKODIque** [comment]
Je crois qu'il y a un problè;me avec l'API TMDb.. car il ne semble pas possible, selon ton log, de communiquer avec le site.

Essaie d'aller dans les paramètres vStream et depuis l'onglet ''Affichage'' appuie sur ''Paramètres d'origine''..
Ceci va remettre l'API Par défaut fournie par vStream.

Une fois que tu as appuyé sur ''Paramètres d'origine'', depuis de même onglet ''Affichage'', assures-toi de sélectionner la case ''Rechercher les métadonnées''

![Screenshot_20221009-090754](https://user-images.githubusercontent.com/49578130/194758607-4252d31a-1b12-4cd1-83b5-ef6d2e638c35.png)

**Comment by alKODIque** [comment]
> Voici ce que dit le log : WARNING : Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 
> Fichier entier ici : [log vstream.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/9741602/log.vstream.txt)

Cet addon n'a aucun lien avec vStream.. il s'agit d'un problème avec un autre dépôt installé sur ton kodi: ''Chainsrepo''.

**Comment by solspire** [comment]
Merci l'alKODIque ;)
mais pas d'amélioration.
J'avais déjà essayer "paramètres d'origine" et la recherche de métadonnée est bien activée.
Ok pour la source morte, y en avait une en effet, je l'ai viré.

Une autre idée entre 2 bouteilles ?

**Comment by alKODIque** [comment]
Tiens, bizarre ça..
Et tu as bien des sources actives ?? je veux dire, tu n'as pas malencontreusement désactivé toutes les sources ici?:

![Screenshot_20221009-093133](https://user-images.githubusercontent.com/49578130/194759722-c180416b-8cfc-40a5-b4b1-d78c43131ef0.png)

**Comment by solspire** [comment]
Non elles sont bien toutes avec la croix verte et j'ai bien re cliqué sur "activer toutes les sources"
(ça aussi j'avais testé) 
"bizarre" aii c'est pas bon pour moi ça !

**Comment by alKODIque** [comment]
Probablement que @sizanic pourra te donner de meilleures pistes..
Nottament sur les erreurs  a partir de la ligne 1058 de ton log 🤔
`File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 159, in parseUrl  function()`

**Comment by solspire** [comment]
Je mets le log URL ce sera plus lisible à celui qui cherchera ..
https://paste.kodi.tv/nocanuvoja

Merci quand même pour ton aide !

**Comment by solspire** [comment]
J'ai aussi déjà essayer de désinstaller réinstaller Vstream (supprimer sources, réinstaller repo..) perdu mes marques pages bhou..sniff

J'ai peut être pas essayé de désinstaller carrément kodi.. c'est sortir le bazooka mais j'ai pas grand chose non plus.

**Comment by alKODIque** [comment]
Tout semble pourtant indiquer qu'il y a un erreur avec l'API TMDb... je ne vois rien d'autre, c'est bizarre de chez bizarre...

**Comment by solspire** [comment]
Une autre information notable :
si je cherche en écrivant ex "game of thrones" alors cela fonctionne.
Je peux chercher quelque chose de précis mais pas utiliser les menus ou avoir la vue avec les jaquettes

**Comment by sizanic** [comment]
J'arrive à reproduire le souci, avec cette même erreur : 
```
2022-10-09 19:29:53.952 T:1540    ERROR <general>:  
File "E:\Logiciels\Kodi20\portable_data\addons\plugin.video.vstream\resources\sites\themoviedb_org.py",
line 658, in showSeries
                                  total = len(result['results'])
```


-> Tout simplement en modifiant la clef TMDB !

Il s'agit bien d'un souci avec la clef.

Soit tu utilises ta propore clef TMDB, vérifies-là.
Soit tu utilises celle par défaut fournie par vStream.
L'action "d'origine" devrait la remettre.

Elle se termine par "7093".
Est-ce qu'il ne te manque pas le '3' final ?

**Comment by alKODIque** [comment]
Bsh voilà.. 
@solspire  est-ce que tu as bien appuyé sur "Paramètres d'origine " depuis l'onglet "Affichage"? car cette action est indépendante d'un onglet à l'autre et n'agira que sur la fenêtre ou est indiqué la clé API.

**Comment by solspire** [comment]
He bien merci beaucoup ! et pardon du dérangement.
J'ai encore pas été rigoureux : j'ai pensé que "paramètre d'origine" ça mettait les paramètres d'origines pour tout le menu paramètre, pas seulement "la page" de paramètre consultée. 

En effet il manquait le dernier chiffre, le 3 n'y était pas.
Cela fonctionne comme un charme.

Je vais continuer l'aventure en essayant de comprendre ce qu'il faut faire pour avoir moins de résultats inutilisables (messages "phyton croix rouge" en haut à droite & compte à créer et débrideur). Je commence par débrid link ....qui me met echec de lecture d'un ou plusieurs fichier .. Vous tous vos résultats de recherche sont toujours bon ?

Chaque jour suffit ça peine donc déjà cool d'avoir retrouvé ce bel affichage Jacquette.  Merci encore !

**Comment by sizanic** [comment]
De rien,
La disparation du dernier chiffre est un grand classique 😄 

Cela arrive avec l'utilisation du bouton "retour" de la télécommande alors que le token est sélectionné.
Cela efface le dernier caractère.

> déjà cool d'avoir retrouvé ce bel affichage Jacquette

Le terme "affichage jacquette" n'est pas à utiliser pour désigner cette section en particulier (la recherche thématique).

CAR LES JACQUETTES SONT AFFICHÉES DANS TOUTES LES SECTIONS DE VSTREAM 🤔 

Le "bel affichage" est visible partout !


> essayer de comprendre ce qu'il faut faire pour avoir moins de résultats inutilisables (messages "phyton croix rouge" en haut à droite & compte à créer et débrideur).


Le message DNSpyhton désigne un souci d'accès à une source lorsque le fournisseur internet bloque l'accès au site utilisé.
Pour contourner ce blocage, soit modifier le DNS dans les parametres de la carte réseau.
-> Soit installer l'extension DNSPython depuis le depot vStream (installer depuis un zip)  (*solution recommandée).

> Vous tous vos résultats de recherche sont toujours bon ?

Non, si on laisse toutes les sources actives.
Donc on supprime d'office les sources qui nécessitent la saisie d'un captcha, et d'autres moins pertinentes, pour n'en garder  qu'une dizaine. Voire même que 5.

> compte à créer et débrideur

Pour un compte à prendre, on te conseille "Uptobox" à 30€/an. Et en promo souvent à 35€/2 ans.
En plus de pouvoir ouvrir les liens uptobox des sources déjà proposées, cela va surtout te permettre d'accéder à la plus grosse bibliothèque de liens de vStream : la source Pastebin.

En attendant, si tu veux te renseigner sur la différence entre "Hébergeur" et "Débrideur", je te conseille la lecture de cet article : 
https://www.facebook.com/legacy/notes/687821468539125/

**Comment by solspire** [comment]
> CAR LES JACQUETTES SONT AFFICHÉES DANS TOUTES LES SECTIONS DE VSTREAM 🤔

oui ok il suffit de changer la vue qui par défaut n'est pas celle de la recherche thématique

> installer l'extension DNSPython depuis le depot vStream

ok merci ça marche 

> pour n'en garder qu'une dizaine. Voire même que 5

sacré boulot d'écrémage à faire... lesquels tu conseils de garder ? 

> on te conseille "Uptobox"   la plus grosse bibliothèque de liens de vStream : la source Pastebin

ok je verrais avec le temps si je dois en venir là

Merci pour ces bons conseils.

Encore une fois et aussi bien sur Vstream que sur toutes les plateformes payantes, il est dommage de ne pouvoir faire un tri de second niveau. Trier par note et ou par année et ou autres critères. Je comprends que les plateformes officielles ne fournissent pas ce service ça pourrait discréditer ou démontrer que l'offre est pauvre. Mais Vstream est libre de se genre de considération marketing alors pourquoi ne pas le permettre ? C'est techniquement difficile ? C'est un autre sujet je sais..

**Comment by sizanic** [comment]
>  Trier par note et ou par année et ou autres critères.

Alors oui il s'agit d'un autre sujet, mais comme la réponse va être simple, on ne va pas créer un sujet pour cela.

Je pense que ta question fait encore référence à la recherche thématique.

Pour les tris de second niveau, on ne peut pas faire mieux que ce que propose le site TheMovieDB (qui est la source de la recherche thématique).

Essaie toi-même d'utiliser des doubles filtres, et tu verras que les résultats ne sont pas exceptionnels.

Par exemple : 

Films populaires + Par note
![image](https://user-images.githubusercontent.com/47307622/195718697-3752abe9-d69a-4ffb-bb7e-df41c5e0bd40.png)

Films populaires + date recentes : 
![image](https://user-images.githubusercontent.com/47307622/195718886-bb2fb986-c1fc-4c47-8c12-a3a932893ed9.png)

Films populaires + date anciennes : 
![image](https://user-images.githubusercontent.com/47307622/195718952-f87be51e-f513-4f28-9cca-d34acc2706e3.png)

**Comment by sizanic** [comment]
>>CAR LES JACQUETTES SONT AFFICHÉES DANS TOUTES LES SECTIONS DE VSTREAM 🤔

>oui ok il suffit de changer la vue qui par défaut n'est pas celle de la recherche thématique

Je ne sais pas quel habillage tu utilises, mais normalement toutes les vues qui proposent des films utilisent la même représentation.

>>pour n'en garder qu'une dizaine. Voire même que 5

>sacré boulot d'écrémage à faire... lesquels tu conseils de garder ?

je sais que Wiflix et french_stream_lol sont pas mal.
Mais après que tu ais fait quelques recherches personnels de films, tu verras les sources que tu as l'habitude d'utiliser.

**Comment by TmpName** [comment]
>Mais après que tu ais fait quelques recherches personnels de films, tu verras les sources que tu as l'habitude d'utiliser.

Pas mieux, pareil pour les hosters, avec le temps tu choissira toi meme les meilleurs en fonction de l'age des liens, de l heure de la journe, des plantages du moi derniers, ....
