### ISSUE TITLE
Ajouter le nom du site dans lequel on se trouve dans la liste des films.

### ISSUE THREAD

**Issue by shmox75** [Kodi-vStream/venom-xbmc-addons#3951]
Bonjour à tous, je ne sais pas si c'est possible d'ajouter le nom du site dans lequel on se trouve en parcourant la liste des filmes.
Je trouve que ça serait sympa, car à chaque fois je voudrais savoir "oui j'oublie vite" sur quel site je me trouve je dois aller en arrière.
Si ce n'est pas claire j'ai attaché une image :) Merci aux devs pour leur fantastique travaille .
![image](https://user-images.githubusercontent.com/39054055/197347792-4079ddab-fe07-4078-bdf9-778e55fcc73c.png)

**Comment by sizanic** [comment]
Bonjour,

L'idée est intéressante.

Mais...
 
- Soit tu veux connaitre les nouveautés d'un site en particulier (et d'un seul), donc tu sais sur quel site tu trouves.

- Soit tu recherches un contenu en particulier, et de savoir sur quel site tu es n'est pas important.
Alors dans ce cas, il te suffit de parcourir plutôt les films en passant par le menu "Rechercher/Recherche thématique".

Essaies ce menu et dis-nous si cela te convient mieux.

**Comment by shmox75** [comment]
> Bonjour,
> 
> L'idée est intéressante.
> 
> Mais...
> 
> * Soit tu veux connaitre les nouveautés d'un site en particulier (et d'un seul), donc tu sais sur quel site tu trouves.
> * Soit tu recherches un contenu en particulier, et de savoir sur quel site tu es n'est pas important.
>   Alors dans ce cas, il te suffit de parcourir plutôt les films en passant par le menu "Rechercher/Recherche thématique".
> 
> Essaies ce menu et dis-nous si cela te convient mieux.

Merci, oui ça parait logique, ceci dit en me trouvant sur la liste d'un site bien précis, je passe beaucoup de temps à naviguer et essayer de trouver un lin qui marche "dood et uqpload son hs pour moi en ce moment je ne sais pas pourquoi" .. Donc au final j'ai passé tellement de temps dans la liste qu'au final, j'ai oublié sur quel site je me trouve. En même temps je comprends que cela paresse bizarre pour certains car j'ai une très mauvaise mémoire :(. Je serais curieux si cela arrive à d'autres .. Sinon ça ne vaut pas le coup d'ajouter ça rien que pour moi lol.

**Comment by sizanic** [comment]
Je ne dis pas qu'on ne va pas l'ajouter, on va y réfléchir.

Mais en attendant, passe par la "recherche thématique" pour choisir ton film, tu pourras alors parcourir les liens des différentes sources, les uns après les autres.

**Comment by shmox75** [comment]
> Je ne dis pas qu'on ne va pas l'ajouter, on va y réfléchir.
> 
> Mais en attendant, passe par la "recherche thématique" pour choisir ton film, tu pourras alors parcourir les liens des différentes sources, les uns après les autres.

Merci c'est très gentil. Oui j'utilise souvent la recherche 👍

**Comment by sizanic** [comment]
Je ne parle pas de la recherche à partir d'un titre.
Soyons bien d'accord, je vais le répéter pour la 3eme fois, je parle de la section "Recherche **_thématique_**".

**Comment by shmox75** [comment]
> Je ne parle pas de la recherche à partir d'un titre. Soyons bien d'accord, je vais le répéter pour la 3eme fois, je parle de la section "Recherche **_thématique_**".

Ah oui, c'est vrais, je l'ai essayé, ça marche super bien. Merci encore.
