### ISSUE TITLE
Display mode dans les differents menu

### ISSUE THREAD

**Issue by codegittest** [Kodi-vStream/venom-xbmc-addons#3952]
Bonjour,

J’essais de faire afficher en mode d’affichage « info media » ou info media 2 » dans tout les sous menus (video, serie, …), je fais des essais en configurant l’onglet « display » de vstream; avec 50 (list - pour les menu principaux), 503, 504 (pour les sous-menu) mais j’ai aussi lu que selon le skin utilisé (dans mon cas confluence), les # ne sont pas nécessairement les mêmes. Il semblerait aussi que le skin pourrais avoir prédominance sur les paramètres de l’addon. Tout ces facteurs rassemblé font en sorte que j’ai de la difficulté à obtenir l’affichage que je veux.

Je continue de faire des essais (maintenant en configurant le fichier xml du skin) et ferai un retour avec les meilleurs réglages trouvé (si je trouve) !

liens intéressants:

https://forum.kodi.tv/showthread.php?tid=340862
https://forum.kodi.tv/showthread.php?tid=178045

Copié-collé de divers informations:

si tu gères l'affichage avec vStream mais que tu sélectionnes un mode qui n'est pas présent dans ton skin, celui-ci reviendra en mode par défaut, le mode liste.
Par exemple, si tu forces le mode 508 mais que ton skin ne gère pas l'affichage "fanart", tu aura le mode "liste".

Pour confluence, les valeurs que j’ai trouvé:
List = 50 
Big List = 51 
ThumbnailView = 500 
PosterWrapView = 501 
PosterWrapView2_Fanart = 508 
MediaInfo = 503 
MediaInfo2 = 504 
WideIconView = 505 
MusicVideoInfoListView = 511 
AddonInfoListView1 = 550 
AddonInfoThumbView1 = 551 
LiveTVView1 = 560

**Comment by codegittest** [comment]
Voici le constat avec le skin confluence:

si modification faite directement dans le skin:(/kodi/addons/skin.comfluence/720P/MyVideoNav.xml), les résultats sont incertain, en changeant l’ordre d’affichage des différents menu certain addon ne fonctionnent plus ou mal.

Lorsque configuré avec addon vstream:
1) attention lors des essais, si une page avait déjà été affiché dans le mode demandé kodi et/ou vstream mémorise, il faut donc tester dans un hoster que vous etes certain de ne pas avoir modifier l’affichage. J’ai constaté que dans le menu « tool » de vstream, il est possible d’effacer le cache mais je ne suis pas certain lequel peut/doit etre effacé (si possible) pour remettre l’affichage par défaut. Idéalement, en ramenant l’affichage par défaut, il serait plus facile de voir l’impact du changement qui a été fait.
2) Changement d’affichage dans vstream:
-  tool/settings/ Onglet display:
     Désactiver « use the skin display for the info. Windows
     View mode: cocher « enable customized view »
     Laisser tout les paramètres a 50 ou 500 par défaut sauf essayer 503,504,515    
      et 551 pour  la ligne « view: movies ».

Résultats:
Avec le parametre 503, c’est bien de facon général mais, on dirait que pour certain hoster c’est le skin qui gere ou bien le paramètre de vstream ne fonctionne pas ou bien y’a un réglage qui prédomine sur celui de vstream.

os: corelelec matrix 19.5
Cpu: amlogic s905x

**Comment by sizanic** [comment]
merci pour ce retour 
(même si je n'ai pas trop compris le but)

> attention lors des essais, si une page avait déjà été affiché dans le mode demandé kodi et/ou vstream mémorise

si "Activer vue personnalisée" n'est pas activé : 
La mémorisation est faite par kodi selon le mode d'affichage choisi dans le skin pour chacun des types : film/serie/saison/episode/lien

si "Activer vue personnalisée" est activé : 
La vue est forcée par vStream selon le paramétre associé à chaque type : film/serie/saison/episode/lien


> Avec le parametre 503, c’est bien de facon général mais, on dirait que pour certain hoster c’est le skin qui gere ou bien le paramètre de vstream ne fonctionne pas ou bien y’a un réglage qui prédomine sur celui de vstream.

c'est bien cela, si dans vStream il est mal précisé s'il s'agit d'un film, d'une saison, d'un episode ou d'un simple lien, c'est kodi qui va utiliser un affichage par défaut.
Il est possible que pour certaines sources, le type soit mal renseigné par vStream.
-> on veut bien que tu nous dises lequel pour qu'on précise le bon type.

**Comment by codegittest** [comment]
Le retour est seulement pour la collectivité, au cas ou certains auraient vécu une situation de ce genre, il y a une 10aine d’annnées, confluence était le skin installé par défaut mais maintenant je sais pas si ce skin est encore populaire

J’ai tout fait mes essais avec « enable customized view (Activer vue personnalisé) » étant activé, donc je comprend que vstream ait enregistré mes préférence lorsque j’ai fait des changements d’affichage, et ce, pour chaque page, chaque hoster et recherche depuis un certain temps. Si on coche: « use the skin display… » cela prévaut sur la vue personalisé de vstream ?

est-ce que je peut effacer le cache dans tool pour refaire mes essais, si oui quel cache ?

Merci encore !

**Comment by sizanic** [comment]
> J’ai tout fait mes essais avec « Activer vue personnalisé » activé, donc je comprend que vstream ait enregistré mes préférence lorsque j’ai fait des changements d’affichage


non, non, non.

vStream n'enregistre pas les préférences lorsque tu fait un changement d'affichage.
vStream n'enregistre rien, il "applique" la valeur du paramètre à chaque ouverture d'une page, en fonction de ce que la page affiche (un film, une saison, ou un épisode).

> est-ce que je peut effacer le cache dans tool pour refaire mes essais, si oui quel cache ?

Il n'y a rien en cache, il n'y a aucun enregistrement de préférence.
Le mode d'affichage est forcé à chaque ouverture de page selon le paramètre saisie et le genre de média affiché.


> Le retour est seulement pour la collectivité, au cas ou certains auraient vécu une situation de ce genre,

Très bonne initiative, mais je ne comprend pas de quelle situation il s'agit 🤔 
Il y a un problème à la base ?

**Comment by codegittest** [comment]
Je ne sais pas si c’est un problème avec le skin et/ou vstream, ca doit etre avec le skin puisqu’il n’y a pas de configuration disponible avec le skin confluence pour configurer l’affichage tel que vstream l’offre dans l’onglet « display ». Cependant, avec le paramètre désactivé « use the skin display for the information windows », ca ne devrait donc pas venir du skin, d’ou mon questionnement.
Je pense qu’il y a un probleme (situation) parce que je doit constamment re-sélectionner le mode d’affichage « info media 2 » sur chaque page qui apparait en recherche film (streaming movie). Une fois ajusté, si je sort du menu et y retourne, l’affichage est comme je l’avais sélectionné, mais si je demande la page 2, 3, … je doit encore re-sélectionner

Pas facile, désolé si j’explique mal…

**Comment by sizanic** [comment]
" use the skin display for the information windows" permet de choisir la fenetre d'informations.
entre celle proposée par vStream (exemple ci dessous) ou celle du skin.
Ce la n'a rien à voir avec le mode d'affichage des vignettes.
![image](https://user-images.githubusercontent.com/47307622/198165788-ab352781-87af-4404-a1f8-8e378fda197b.png)


C'est peut-être plus clair en français : 
![image](https://user-images.githubusercontent.com/47307622/198165888-25c539d7-7542-419c-82a5-98b12ce64462.png)

**Comment by codegittest** [comment]
Merci,
Oui c’est bien de cette option que l’on parle (je préserve le menu en anglais sinon l’iptv recorder ne comprends pas le format date et hre).
Ok, je préfére quand c’est vstream qui gère (en cochant l’option), va rester a voir pourquoi je n’obtient pas toujpurs le meme résultat. J’ai peut-etre pas été chanceux sur un host qui est configuré différamment pour vstream. Je vais essayer de revenir avec un nom + concret.

**Comment by sizanic** [comment]
> Oui c’est bien de cette option que l’on parle

Cette option "fenetre d'information" ne modifie pas les modes d'affichages. C'est l'autre option en dessous.

> Je pense qu’il y a un probleme (situation) parce que je doit constamment re-sélectionner le mode d’affichage « info media 2 » sur chaque page qui apparait en recherche film (streaming movie). Une fois ajusté, si je sort du menu et y retourne, l’affichage est comme je l’avais sélectionné, mais si je demande la page 2, 3, … je doit encore re-sélectionner


Comme tu as activé les vues personnalisées qui permet à vStream de forcer le mode d'affichage , voici ce qu'il se passe : 
- tu arrives sur la première page, le mode d'affichage est forcé par vStream.
- ce mode d'affichage ne te plait pas et tu le changes avec « info media 2 » dans les parametres du skin.
- tu passe sur la page 2, alors vStream reforce le parametre que tu lui as mis en paramètre (différent de « info media 2 »)
- tu reviens sur la premiere page, ce n'est ni le skin ni vStream qui impose lemode d'affichage, mais Kodi qui à garder la page en cache, donc le mode d'affichage précédent (« info media 2 »).


=> Soit tu trouves le bon parametre d'affichage que tu mets dans vStream pour qu'il l'applique sur chaque page
=> Soit tu désactive les vues personnalisées de vStream, tu choisis lemode qui te plait avec ton skin et tu "forces" ce mode dans les parametres du skin.

> chaque page qui apparait en recherche film (streaming movie)

Quel menu exactement ? je ne vois pas à quel endroit tu fais référence 🤔

**Comment by sizanic** [comment]
Je viens de regarder, mais avec confluence, il n'y a pas le menu pour sauvegarder le mode d'affichage choisi.
Et en effet, le mode choisi n'est pas conservé entre les pages.
Le mode revient constamment sur "Liste"

Donc tu dois utiliser les "vues personnalisés" de  vStream.

J'ai testé avec 504 pour Films.

Et maintenant toutes mes pages films s'affichent en "Informations du média" au lieu de "Liste".
Et même si je force un mode liste dans une page, la page suivante revient en mode "Informations du media".
vStream fait son travail.


> chaque page qui apparait en recherche film (streaming movie)

Quel menu exactement ?

**Comment by codegittest** [comment]
Parfais merci, c’est tres clair commentca fonctionne et ca explique tres bien ce qui se passe ! Dans ce que j’ai pu voir que le skin supporte ca serait 503,504 ou 515. Quand j’ai fait mes essais en modiant le fichier «  MyVideoNav.xml » je cochait « utiliser la fenetre d’information du skin » et quand je fait des essais avec la config vstream, je la décoche et coche « activer une vue personalisé » et test avec les 503,504,515.
« Quel menu exactement:
…streaming/movies/movies(news)/33 series par exemple (1iere page media info 2, certaines autres pages apparaissent en mode list et ca varie d’un mode a l’autre d’une page a l’autre. J’imagine que c’est des pages qui ont déjà été consulté, c’est pourquoi je voulais trouver une facon d’effacer ce que le skin a enregistré.

**Comment by codegittest** [comment]
Désolé, pas le skin mais plutôt effacer ce que kodi (os) a enregistré comme tu expliquais !

**Comment by sizanic** [comment]
> Parfais merci, c’est tres clair comment ca fonctionne et ca explique tres bien ce qui se passe !

Il suffisait d'expliquer clairement le souci pour avoir une réponse clair 😄 

> Quand j’ai fait mes essais en modiant le fichier «  MyVideoNav.xml » je cochait « utiliser la fenetre d’information du skin » et quand je fait des essais avec la config vstream, je la décoche et coche « activer une vue personalisé » et test avec les 503,504,515.

« utiliser la fenetre d’information du skin » n'a aucune influence sur le mode d'affichage !!


> « Quel menu exactement:
…streaming/movies/movies(news)/33 series par exemple (1iere page media info 2, certaines autres pages apparaissent en mode list et ca varie d’un mode a l’autre d’une page a l’autre.

Je viens de tester 33series, et je n'ai pas d'alternance entre plusieurs modes de vues entre les pages.
vStream impose le 504 à chaque fois. Même si je force un autre mode d'affichage avec le skin sur une page, il suffit de revenir sur la page pour que vStream reforce le mode d'affichage. 


> J’imagine que c’est des pages qui ont déjà été consulté, c’est pourquoi je voulais trouver une facon d’effacer ce que le skin a enregistré.

C'est un cache, donc il suffit normalement de redémarrer Kodi.
