### ISSUE TITLE
Différence entre Animes et Japanimes

### ISSUE THREAD

**Issue by sharpordie** [Kodi-vStream/venom-xbmc-addons#3954]
J'ai **Japanimes** dans le menu principal de l'extension :

<img src="https://user-images.githubusercontent.com/72373746/197727706-dd9537b7-24b0-4165-a8e4-e819c5d77968.png" width=75% height=75%>

Mais, j'ai **Animes** dans le menu d'une source (ici Pastebin) :

<img src="https://user-images.githubusercontent.com/72373746/197728390-7c52e8c3-1f6e-4246-9f94-ae39889a514f.png" width=75% height=75%>

Est-ce normal ? Y a-t-il une différence ?

**Comment by sizanic** [comment]
Bonjour,

non, il n'y pas de différence.

https://fr.wikipedia.org/wiki/Anime
_Un "**anime**", ou "**animé**", également appelé parfois "**japanime**" ou "**japanimation**", désigne une [série d'animation](https://fr.wikipedia.org/wiki/S%C3%A9rie_d%27animation) ou un [film d'animation](https://fr.wikipedia.org/wiki/Film_d%27animation) en provenance du Japon souvent adapté d'un [manga](https://fr.wikipedia.org/wiki/Manga). C'est le diminutif du mot animēshon , lui-même transcription de l'anglais animation_


On va changer le terme dans la source Pastebin, pour être homogène.
Bien vu.

**Comment by sharpordie** [comment]
OK c'est bien ce que je pensais.
Sinon quel terme allez-vous garder ?

**Comment by sizanic** [comment]
> On va changer le terme dans la source Pastebin, pour être homogène.

Si je change celui de Pastebin, c'est que je garde l'autre 🤔 😄

**Comment by sharpordie** [comment]
Alors, il vaut mieux garder Japanimes. ;)

**Comment by sizanic** [comment]
Finalement, dans Pastebin on peut aussi retrouver des séries d'animations qui ne sont pas des séries d'animations japonaises.

Alors je pense conserver "Animes" (terme générique) pour Pastebin.

Ainsi, la "Recherche (Animes)" de pastebin permet tout aussi bien de retrouver une série disney que l'attaque des titans.

**Comment by sharpordie** [comment]
Donc, le nommage n'est absolument pas imposé par vStream !
Donc il y a bien une différence. Il faudra un jour que je jette un oeil au code source.

Je croyais au début que c'était juste une faute de traduction ou un oubli d'un ancien passage d'une architecture à une autre.

**Comment by sizanic** [comment]
Si le nommage est imposé par vStream.
Et je pourrais le changer en tant que développeur de vStream.

Mais pour la source pastebin, c'est le contenu qui n'est pas imposé.

Et certaines personnes qui contribuent au contenu de cette source ont proposé des dessins animés qu'ils ont rangé dans la catégories "Animes".
Je ne vais pas leur demandé de retirer leur contenus, donc je propose un entre-deux, avec le terme "animes" qui peut convenir pour des japanimes et dessins animés.

**Comment by TmpName** [comment]
Et au niveau des moteur de recherche, c'est deja le bordel pour faire la difference entre "serie" et "serie (jap)animées", alors si il  faut faire la difference entre "animées" et "japaanimées"

**Comment by sizanic** [comment]
En effet, c'est le bordel, on nous a même fait remarquer que la recherche par TMDB ne permet pas de rechercher dans les animes : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3946

_"pour une recherche de séries, les liens pour les animés de vstream sont exclu des recherches"_

**Comment by sharpordie** [comment]
Alors pour être entièrement compatible avec TheMovieDB Helper, il faudrait tout rassembler en films et séries.

- Films (Genre Documentaire) pour les films documentaires.
- Séries (Genre Documentaire) pour les séries documentaires.
- Séries (Genre Animation & Langue Originale: Inclure Japonais) pour les japanimes.
- Séries (Genre Animation & Langue Originale: Exclure Japonais) pour les dessins animés.
- Séries (Genre Reality) pour les telerealites (Master Chef) et jeux tele (Les 12 Coups de Midi).

Ce serait une très bonne chose.

Par contre, il faudra toujours laisser une catégorie diverse pour tout le reste comme les concerts ou encore les mires de tests.

**Comment by sizanic** [comment]
> Séries (Genre Animation & Langue Originale: Inclure Japonais) pour les japanimes.

Le souci est que maintenant, le genre "anime" s'étend à l'extérieur du japon.
Même certains studio français se sont lancés dans l'anime.

> pour les enfants (coucou lesalkodiques).

les alkodiques sont des enfants ? 🤔 🤣 


On va plutot faire un truc très simple : inclure les animes dans la recherche TMDB.

La recherche ramène déjà plus de résultats qu'il n'en faut en proposant les titres qui contiennent certains mots de la recherche.
Si on se retrouve avec un anime homonymes, ce n'est pas génant. (et ce sera rare)

Les séries et animes sont déjà rassemblés ensemble dans les marques-pages.
C'est une vieille histoire entre ces deux genres, ça n'a jamais vraiment gêné.
Ils sont de toute façon très liés.

**Comment by sharpordie** [comment]
> Le souci est que maintenant, le genre "anime" s'étend à l'extérieur du japon.
> Même certains studio français se sont lancés dans l'anime.

Effectivement, les filtres que je propose ne sont pas infaillibles et les APIs de TMDB ne permettent pas de tout filtrer.

Mes suggestions sont pour les utilisateurs et non pour les développeurs. Si tout est rassemblé en film, séries et divers (là je parle d'une refonte possible du menu principal de vStream), l'utilisateur pourra avoir accès au contenu souhaité via les filtres que j'ai mentionnés dans le précédent commentaire. Encore une fois ce ne sont que des suggestions.

> les alkodiques sont des enfants ? 🤔 🤣

Haha, je savais que cela allait faire réagir.

Ils ont une catégorie dessins animés différente des Japanimes. Je suppose que c'est pour filtrer les Japanimes violents et/ou a caractère sexuel. Pour cela il leur suffit d'ajouter le filtre Genre: Kids avec TheMovieDB Helper.

**Comment by sizanic** [comment]
> Ils ont une catégorie dessins animés différente des Japanimes. Je suppose que c'est pour filtrer les Japanimes violents et/ou a caractère sexuel. Pour cela il leur suffit d'ajouter le filtre Genre: Kids avec TheMovieDB Helper.

On ne peut pas ajouter de filtres tmdb pour les sources de vStream.
Le genre TMDB n'est connu qu'après avoir récupéré le média et interrogé TMDB pour avoir le genre associé.

Cela serait trop long de récupérer les infos de tous les médias pour appliquer un filtre ensuite.

Le seul emplacement pour mettre en place des filtres TMDB est dans les classements TMDB déjà proposés :
-> le menu "Recherche thématique".

Et c'est déjà regrouper par films et séries !

Et il y a déjà un classement par genre.

> - Films (Genre Documentaire) pour les films documentaires.

déjà disponible

> - Séries (Genre Documentaire) pour les séries documentaires.

déjà disponible

> - Séries (Genre Reality) pour les téléréalités (Master Chef) et jeux télévisés (Les 12 Coups de Midi).

déjà disponible


> - Séries (Genre Animation & Langue Originale: Inclure Japonais) pour les japanimes.

Le trie par langue n'est pas le bon trie. Séries (Genre Animation) -> déjà disponible


> - Séries (Genre Animation & Genre Kids & Langue Originale: Exclure Japonais)

Le trie par langue n'est pas le bon trie.
Séries (Genre Kids) -> déjà disponible (inclut les animations, pas de raison de les trier à part)

> Ne serait-ce pas encore une bonne raison de rassembler tout en films et séries ?
Comme avec la plupart d'autres addons de ce genre et comme avec Kodi finalement.

vStream propose des sites qui ne mettent à disposition que des animes.
Avoir un menu de recherche qui ne parcours que ces sites pour des raisons de performances et de résultats pertinents est une fonctionnalité que ne propose pas les autres addons 😉 


>> On va plutot faire un truc très simple : inclure les animes dans la recherche TMDB.

>Donc en gros, ne pas dissocier les japanimes des séries ? Qu'en est-il des documentaires alors ?

Ce que je propose est pour résoudre ce probleme : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3946
Pour rappel : en sélectionnant un japanime dans le menu "Recherche thématique" ou par un raccourci TMDBHelper, vStream ne parcourt pas ses sources  identifié "animes" mais seulement les sites "Séries". Donc il ne trouve pas l'anime. La modification consiste à faire en sorte que la recherche d'un anime parcourt les sites "séries" et les sites "animes".

**Comment by sharpordie** [comment]
> Recherche thématique

Rhaaa ! Je viens de voir ce menu et c'est exactement ce que je proposais... Quelle idée de mettre cela dans un sous-menu recherche. ^^'

Ce ne sont pas vraiment des recherches, mais plutôt des listes. Pour moi une recherche nécessite obligatoirement une entrée par l'utilisateur.

J'ai remplacé le lien de mon menu Arctic Horizon 2 pour qu'il pointe directement sur Recherche thématique.

**Comment by sizanic** [comment]
Alors oui, il y a un travail à faire de ce côté 😄 

On vient de changer, et on changera encore.
L'ancienne version proposait ce menu à la racine.
ça s'appelait "Recherche visuelle".

Pour sous-entendre que la recherche se fait à partir du visuel. 
**-> donc sans saisie par l'utilisateur**


On a changé pour "recherche thématique", car l'utilisateur part à la **recherche** de ce qu'il veut regarder selon des thèmes : 
- nouveautés
- selon un genre
- selon l'acteur
- etc..


Tu verras aussi un autre intérêt de passer par ce menu, c'est qu'il ne repose pas sur les sources.
Une fois le film choisi, la recherche est effectuée ensuite dans toutes les sources (celles actives).

**Comment by sharpordie** [comment]
Bon maintenant la question fatidique, TheMovieDB Helper ou pas ?

L'unification avec tous les autres addons et trakt en fait un addon presque indispensable. Mais on perd l'âme des addons originaux, l'auteur de Fen n'est d'ailleurs pas très favorable.

Bref, je m'écarte trop du sujet, si j'ai d'autres questionnements, j'ouvrirai une autre issue.

**Comment by sizanic** [comment]
Beaucoup ont adopté TMDBHelper avec vStream.
La comptabilité est très aboutie.


Tu auras vraiment les filtres qui t'intéresse.
Et il existe des players pour TMDBH adaptés à vStream.
Que ce soit pour lancer une recherche parmi les sources actives, ou pour une source en particulier (je pense à la source Pastebin et son player dédié.)

Mais cela est une autre histoire en effet.

si cela t'interesse, je peux te mettre sur une piste.
