### ISSUE TITLE
HELP !! Sources SPORT Direct ne fonctionnent plus ( addon DNS python manquant) 

### ISSUE THREAD

**Issue by Whitebread40** [Kodi-vStream/venom-xbmc-addons#3955]
**Décrivez le bug**

Sources SPORT en direct ne fonctionnent plus (addon DNS python manquant) > aucune information 
Ceci Pour Channel Stream, Leet 365 et Live TV 
 
Plus rien ne fonctionne, merci +++ pour le support 

**Votre system**
- OS: [Android]
- Appareil: [nvidia shield )
- Version Kodi: [19.3.0
- Version Vstream: [la dernière 2.0.1)

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

**Comment by sizanic** [comment]
Bonjour,

Il n'y a que ChannelStream qui nécessite DNSPython.

Pour l'installer, il suffit d'aller dans kodi / Extensions / Installer d'un fichier zip / vStream / script.module.dnspython-x.x.x.zip

**Comment by Whitebread40** [comment]
Quand je clique sur direct sport > sport ( en direct)  il y a 3 sources qui s’affichent ( Channel Stream, Leet 365 et Live TV)  et j’ai une notification en haut de l’écran me disant addon DNS python manquant streamonsport ?? 
puis quand je clique sur chaque source par ex pour Leet365 cela me marque dns Python manquant leet 365 et j’ai en rouge aucune information- 
Et apparemment, le moduLe python est bien installé??? 
Vous avez un remède ? 
MERCI

**Comment by sizanic** [comment]
L'erreur DNS indique que l'adresse du site n'a pas pu être résolue.
On présume qu'il s'agit d'un blocage DNS du fournisseur internet.
Le contournement est donc d'installer DNSPython.

Mais si l'erreur DNS apparaît tout le temps, ce n'est pas un blocage du fournisseur.
Mais un souci internet tout court.

VPN ?

**Comment by Whitebread40** [comment]
Bonjour, j’ai installé DNS python à partir du fichier zip et problème réglé. Je pensais qu’il était dans l’addonVStream.
Pour l’instant tout refonctionne, c’est parfait 👍
Grand merci pour votre support, au top !


Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : sizanic ***@***.***>
Envoyé : Saturday, October 29, 2022 12:09:24 AM
À : Kodi-vStream/venom-xbmc-addons ***@***.***>
Cc : Whitebread40 ***@***.***>; Author ***@***.***>
Objet : Re: [Kodi-vStream/venom-xbmc-addons] HELP !! Sources SPORT Direct ne fonctionnent plus ( addon DNS python manquant) (Issue #3955)


L'erreur DNS indique que l'adresse du site n'a pas pu être résolue.
On présume qu'il s'agit d'un blocage DNS du fournisseur internet.
Le contournement est donc d'installer DNSPython.

Mais si l'erreur DNS apparaît tout le temps, ce n'est pas un blocage du fournisseur.
Mais un souci internet tout court.

VPN ?
