### ISSUE TITLE
Wiflix Liens

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#3957]
Bonsoir à tous 
Je viens à vous annoncer que Wiflix.Zone est mort 
Maintenant c est Wiflix.cafe 

https://wiflix.cafe/

+ il ont un nouveau site supplémentaire en cas de
Lien mort dont vous pourrez  ajouter si vous le souhaitez 
https://www.frflix.com/

Merci la Team

**Comment by sizanic** [comment]
Bonsoir et merci.

On va regarder si ce site est compatible avec l'ancien ou s'il s'agit juste d'un site qui utilise le nom ...

**Comment by yodidon** [comment]
Je vais essayer de regarder de mon côté si je vois quelque chose à faire

**Comment by sizanic** [comment]
La nouvelle adresse du site a été mise à jour dans vStream.

Par contre l'autre adresse est un autre site.
On garde l'adresse de côté, on verra si elle vaut le coup plus tard.
