### ISSUE TITLE
Probleme vstream 2.1.0 avec propre librairie uptobox

### ISSUE THREAD

**Issue by maxime1321** [Kodi-vStream/venom-xbmc-addons#3961]
Bonjours anciennement j’avais acces a ma librairie uptobox mais la avec la maj plus rien de fonctionne la fonction a été délaissé ? Sinon avez vous plus de details ? Merci

**Comment by sizanic** [comment]
Bonjour,

Ce serait vraiment une grosse régression si cela ne fonctionne plus, on va vérifier.

**Comment by sizanic** [comment]
je n'ai pas de souci de mon côté, j'ai bien accès au contenu de ma librairie Uptobox.

**Comment by Zangdark** [comment]
Bonjour ,

j'ai exactement le même problème , suite un formatage de ma NVDIA SHIELD  , j'ai réinstallé Kodi et Stream et maintenant, quand je vais dans mes contenues que je sélectionnes uptobox, j'ai la popup qui me dit authentification réussie et après plus rien. juste un message (necessite un compte uptobox premium ou gratuit) alors que je suis connecté

**Comment by Zangdark** [comment]
![WhatsApp Image 2022-12-02 à 08 44 55](https://user-images.githubusercontent.com/119656228/205242335-c10bdd6c-495a-4dd4-be6e-633e11134261.jpg)

**Comment by sizanic** [comment]
Avec la dernière version, il faut saisir les identifiants ET le token.
D'après le symptôme, les identifiants sont bons mais pas le token.

**Comment by Zangdark** [comment]
Merci, sa marche

**Comment by swazen** [comment]
Salut ! Pb différent mais lié à l'ouverture du compte uptobox depuis vstream 2.3 avec Nexus (win & android)
message : invalid order field
Tout était fonctionnel il y a quelques jours (token en place depuis 12/2022).
Une idée ?

**Comment by TmpName** [comment]
Peut etre https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3995

**Comment by swazen** [comment]
> Peut etre meme soucis que  https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3995

Non je pense qu'il est différent

**Comment by maxime1321** [comment]
Meme chose ici sur 2 plateforme differente token inscrit mot de passe et user entré ne fonctionne pas

**Comment by sizanic** [comment]
ce souci est suivi ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3995

**Comment by sizanic** [comment]
plus de souci de saisie de token avec la derniere version
