### ISSUE TITLE
Proposer des liens 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#3962]
Bonsoir la team 

je viens ici pour vous apporter de nouveau site afin que sa sois rajouter sur Vstream si possible 

https://co flix.tv/
https://empire - streaming.co/
https://just daz.com/
https://anime ko.co/ 
https://anime - sama.fr/

Merci à vous tous

**Comment by sizanic** [comment]
Bonsoir,
Et merci.

"just daz" est un clone de kepliz, on le propose déjà.

**Comment by yodidon** [comment]
Intéressant 👍

**Comment by yodidon** [comment]
Je n’arrive pas à décoder les liens..

**Comment by TmpName** [comment]
De quel site ?

**Comment by yodidon** [comment]
> De quel site ?

Co flix . Tv si tu sais m’orienter je suis super preneur

**Comment by TmpName** [comment]
Ben deja je te deconseille ce site, ne serais-ce que par rapport au lecteur dispo.

Mais ce que je peux voir c'est que le site fais une requete 
`https://player.iptvforyou.fr/cdn/films/Titredufilmsans espace/01.mp4`

Cette requete est protegé surement par le referer, pas de cookies

`Referer : https://coflix.tv/`

Et ce fichier contient

`[{"src":"https://a.iptvforyou.fr?file=eyJXkiOiJmaWxtcfy9CdWxsZXRcmFpbi8wMS5tcDQiLCJleHBpcmUiOjE2Njg5OTU4MzQ1OTEsIlwIjoiMTc2LjE3MS4xNDcuMjMl4In0=&auth=e57756f3928769d63495b0da50a2d11784fc59bde2ea2111bb69f7b9b0023b89","type":"video/mp4","size":"1080 P"}]`

Le telechargement marche bien avec ce lien, mais si j'essaye de l'ouvrir dans le navigateur ca tourne en boucle.

**Comment by sizanic** [comment]
J'ai lu plus haut : 
> je deconseille ce site, peu de fichiers, lecteur pourave, peu de hosters.


On continue quand même ?

**Comment by yodidon** [comment]
Moi j’ai lâché coflix , pas encore regarder les autres

**Comment by Mokoman30** [comment]
Le Retour de Tirexo sous un nouveau site

https://www2.darkino.com/

**Comment by sizanic** [comment]
Merci 

On attend que le site se stabilise un peu, voir s'il tient quelques jours, et si une protection captcha n'est pas mise en place.

**Comment by zerosle** [comment]
Bonjours tout le monde, j’aimerai proposer des sites si c’est possible t’ajouter sur vstream pour la catégorie drama : 

- https://kdrama.best/
- https://mykdrama.co/
- https://dramacoreen.best/
- https://kdramavostfr.com/
  
Merci beaucoup

**Comment by zerosle** [comment]
je suis désolé je me connais pas du tout et merci de prendre ton temps encore 

> très bien, je vais vérifier tout ça
> 
> > Bonjours tout le monde, j'aimerai proposer des sites si c'est possible t'ajouter sur vstream pour la catégorie drama :
> > ```
> > * https://kdrama.best/
> > 
> > * https://mykdrama.co/
> > 
> > * https://dramacoreen.best/
> > 
> > * https://kdramavostfr.com/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Merci beaucoup

**Comment by yodidon** [comment]
> Bonjours tout le monde, j’aimerai proposer des sites si c’est possible t’ajouter sur vstream pour la catégorie drama :
> 
> * h ttps://kdrama.best/
> * ht tps://mykdrama.co/
> * ht tps://dramacoreen.best/
> * ht tps://kdramavostfr.com/
> 
> Merci beaucoup

Bonjour, ça parait faisable à première vu

**Comment by yodidon** [comment]
> Bonjours tout le monde, j’aimerai proposer des sites si c’est possible t’ajouter sur vstream pour la catégorie drama :
> 
> * h ttps://kdrama.best/
> * ht tps://mykdrama.co/
> * ht tps://dramacoreen.best/
> * ht tps://kdramavostfr.com/
> 
> Merci beaucoup

J'ai fini le premier mais je suis pas très au fait des Dramas, il n'y a pas de différentes saisons ? je ne trouve pas cette info sur kdrama
Merci

**Comment by zerosle** [comment]
> > Bonjours tout le monde, j’aimerai proposer des sites si c’est possible t’ajouter sur vstream pour la catégorie drama :
> > 
> > * h ttps://kdrama.best/
> > * ht tps://mykdrama.co/
> > * ht tps://dramacoreen.best/
> > * ht tps://kdramavostfr.com/
> > 
> > Merci beaucoup
> 
> J'ai fini le premier mais je suis pas très au fait des Dramas, il n'y a pas de différentes saisons ? je ne trouve pas cette info sur kdrama Merci

C’est très rare qu’il y a plusieurs saison dans un drama c’est souvent juste 1 saison

**Comment by Mokoman30** [comment]
Bonsoir la team 
Voici des liens d anime à proposer 
https://franime.fr/
https://streaming-integrale.com/
https://anime-sama.fr/

merci bonne soirée à vous la team

**Comment by sizanic** [comment]
Merci
on va étudier ça 👍🏻

**Comment by amidevous** [comment]
https://streaming/ - integrale.com/ = cloudflare

**Comment by sizanic** [comment]
Anime-Sama est maintenant disponible dans le version 3.2 de vStream 👍🏻
