### ISSUE TITLE
lliens qui rame

### ISSUE THREAD

**Issue by lil78711** [Kodi-vStream/venom-xbmc-addons#3964]
**Décrivez le bug**

**Votre system**
- OS: [Windows, Android]
- Appareil: [nvidia shield, Ultra]
- Version Kodi: 19.4
- Version Vstream: [2.1.0]

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

**Comment by lil78711** [comment]
les sources vstream mette longtemps a charger pour rien lancer au final je dois avoir que 3 source qui fonctionne normalement  comme ducine et 4kstream  et pour les mangas aucune y'a t il une solution pour reduire le chargement des sources merci a vous

**Comment by sizanic** [comment]
Bonjour 
Commence par : 
- N'utilise pas de vpn.
- Changes de DNS (ou installes DnsPython).

**Comment by arzaz** [comment]
J'ai un souci avec la source Free telechargement, rien ne s'affiche sur nvidia shield ?

**Comment by TmpName** [comment]
Le site est OUT pr le moment, tu peux tester sur navigateur http s://ww w.free-telecharger.top/
