### ISSUE TITLE
33serie

### ISSUE THREAD

**Issue by shmox75** [Kodi-vStream/venom-xbmc-addons#3971]
Bonjour, la plus part des liens ne lancent pas sur 33serie. Je ne sais pas si ça viens d'eux.. Ceci dit j'ai pu lancer la lecture depuis leur site
![image](https://user-images.githubusercontent.com/39054055/203340807-4396f54d-a929-4185-a942-deeda8da4efd.png)

**Comment by sizanic** [comment]
Bonjour,
Nous allons regarder.

**Comment by shmox75** [comment]
> Ca marche avec les series mais pas les films c'est ca ?

Pour être honnête, je n'ai pas testé les série.. Seulement les filmes.

**Comment by TmpName** [comment]
Ok alors mauvaise nouvelle pour toi, je m'y suis deja penché et a part faire planter les series j'ai pas reussi.

Meme le vieux code que j'avais fais ne marche plus. Franchemenent j'ai pas d'idéés, meme sur le site parfois ca deconne, et sur kodi parfois ca remarche, je sais pas si c'est un truc avec des timers, mais dans ce cas pourquoi ca marche sur les series.

**Comment by shmox75** [comment]
> Ok alors mauvaise nouvelle pour toi, je m'y suis deja penché et a part faire planter les series j'ai pas reussi, et comme il n y a qu'un seul hoster, j'ai laissé tomber.
> 
> Meme le vieux code que j'avais fais ne marche plus. Franchemenent j'ai pas d'idéés, meme sur le site parfois ca deconne, et sur kodi parfois ca remarche, je sais pas si c'est un truc avec des timers, mais dans ce cas pourquoi ca marche sur les series.

Dommage, merci bien quand même :) Je close!

**Comment by sizanic** [comment]
J'ai aussi regardé et pas trouvé non plus comment faire fonctionner les films.
