### ISSUE TITLE
👋☝️ Bug sur le site fullmatchtv.com en hd

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#3973]
🖐️ ![11](https://user-images.githubusercontent.com/48101775/205703015-3f6d9f15-3e20-449a-b49a-a9469de45353.gif)
En HD il y a blocage sur site sport  https://fullmatchtv.com/nba dans Vstream contrairement au site en lui même.
![logo2-1](https://user-images.githubusercontent.com/48101775/205703622-2ed67673-9f70-4cd8-9dcd-8862d4b49768.png)
![283](https://user-images.githubusercontent.com/48101775/205703281-da1bf81e-ccfc-4fcb-9501-e1be3d97185e.gif)
Les vidéos NBA s'ouvrent bien en HD (1280) mais au bout de quelques secondes restent bloqués sur une image depuis plusieurs semaines voir des mois.
**Par contre fonctionne bien en SD (852x480),Low,Lowest, mobile.**
![18](https://user-images.githubusercontent.com/48101775/205704108-93bc4357-3e08-4acb-b348-c0744b7e275a.gif) L'aviez vous remarquer lors de son intégration dans Vstream ? Et ne pouviez vous pas amélioré cela ?

**Merci pour la répons** ,✔️

**Comment by victore447** [comment]
![695](https://user-images.githubusercontent.com/48101775/205712668-c2798a82-8326-4dba-b7ef-efb97a8b4dcb.gif)

**Comment by TmpName** [comment]
>au bout de quelques secondes restent bloqués sur une image depuis plusieurs semaines voir des mois.

Et ca viendrait pas de kodi lui meme ?
En general, on trouve le lien, il marche ou pas, on le donne a kodi et il se debrouille avec.

Ca pourrait etre un probleme de fichier "fractionnés" un m3u mais ca marcherait pas en low

**Comment by sizanic** [comment]
peut-être en changeant le lecteur par défaut de kodi ? 🤔

**Comment by TmpName** [comment]
Je viens de tester l'autre mode, pas de message d'erreurs, mais meme resultat.

**Comment by sizanic** [comment]
le site n'est plus disponible
