### ISSUE TITLE
Token Uptobox

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3974]
Bonjour à vous!

J'aurais une suggestion:

Depuis quelques temps, le site uptobox a fait des modifications a sa structure. Depuis ces dites modifications, notamment à la section ''mon compte'' du site, vStream ne réussi plus a récupérer de façon automatique notre token. Nous devons donc l'enregistrer manuellement dans les paramètres vStream, section 'Premium/login'.

Ayant reçu quelques commentaires a cet effet via ma communauté, je me demandais si vous pouviez changer l'inscription ''optionnel'' pour ''obligatoire'' dans les paramètres ?
![111](https://user-images.githubusercontent.com/49578130/207500005-cd74c439-6e4a-4292-9d0a-5e5310a701a9.png)

**Comment by alKODIque** [comment]
Ha! C'est encore mieux donc ;)
Merci!

**Comment by sizanic** [comment]
Le token se remet tout seul depuis la version 2.3.0 sortie cette semaine.
