### ISSUE TITLE
Message d'erreur sur pastebin

### ISSUE THREAD

**Issue by PassionFlix** [Kodi-vStream/venom-xbmc-addons#3975]
**Décrivez le bug**
Bonjour tout le monde, depuis hier j ai des messages d'erreurs qui apparaissent lorsque je navigue dans la source pastebin.
Hier j'en avais perdu tous mes widget en rapport avec la dite source
Aujourd'hui ils sont revenu par je ne sais quel miracle mais toujours des messages qui apparaissent meme si j'arrive a lancer le média

**Votre system**
- OS: Windows 11
- Appareil: Pc de bureau 
- Version Kodi: 19.4.0
- Version Vstream: 2.1.2

**Nous devons le reproduire**

- Nom du site: Source Pastebin
- Titre du fim/serie: n'importe laquelle

**Log**

**Image**
![Screenshot_1](https://user-images.githubusercontent.com/71842302/208310422-fcdf882a-e33f-4f79-9d7c-8dd6d86d7b5c.png)
![Screenshot_2](https://user-images.githubusercontent.com/71842302/208310428-cb25f359-e701-4cc0-a3fc-3a24a98e8454.png)
![Screenshot_3](https://user-images.githubusercontent.com/71842302/208310434-b64021b8-8c48-49a9-94d7-bc76741faf36.png)

A chaque page de navigation dans la source j'ai les messages qui apparaissent

Merci à vous

**Comment by sizanic** [comment]
Salut,

On va regarder cela ensemble...

**Comment by PassionFlix** [comment]
Je suis totalement dispo et tout a toi :)

**Comment by PassionFlix** [comment]
Je remarque egalement que la recherche globale de vStream ne fonctionne plus ;(

**Comment by sizanic** [comment]
Il me faudrait ton log complet, stp

**Comment by PassionFlix** [comment]
Bizarrement je n ai plus aucun message d erreur en navigant dans les sections de la source pastebin

[https://paste.kodi.tv/wibejohuxo.kodi](url)

**Comment by sizanic** [comment]
En effet, je ne vois aucun souci de navigation dans Pastebin.

Du coup, je dois chercher dans ce log des traces d'un quelconque souci ?

**Comment by PassionFlix** [comment]
En dehors de celui posté sur le discord j'ai pas d'autre log du coup :(

**Comment by sizanic** [comment]
mais as-tu toujours des problemes ?

**Comment by PassionFlix** [comment]
non plus aucun lol
j ai fermé et ouvert kodi a plusieurs reprises et navigué dans la source
seul la recherche de vstream ne m affiche plus rien
Problème lié ???

**Comment by sizanic** [comment]
non.
Il faudrait maintenant plus de détails sur le souci de la recherche.

Liste des sources actives ?
Symptôme détaillé ?

**Comment by PassionFlix** [comment]
Toutes les sources actives
ensuite je vais dans "videos a la demande - Films - Rechercher un Film"
Dans la fenetre de recherche je met le titre Black adam par exemple
Et le résultat est NULL

![Screenshot_1](https://user-images.githubusercontent.com/71842302/208327993-5ae8f569-1bcd-4621-b8c3-ca0da2be3e25.png)

Idem si je vais dans "videos a la demande - Séries - Rechercher une série"
Je cherche par exemple la série "Mercredi"
J'obtiens le meme résultat que sur la capture précédente

**Comment by PassionFlix** [comment]
un nouveau log inclu les recherche la recherche effectué
[https://paste.kodi.tv/qexitenosu.kodi](url)

**Comment by sizanic** [comment]
Mais est-ce que tu as au moins la fenetre de progression ?

![image](https://user-images.githubusercontent.com/47307622/208329560-676739d0-e00d-4eab-a9dc-673ee52c5173.png)

**Comment by PassionFlix** [comment]
Pas du tout

**Comment by PassionFlix** [comment]
et pire meme
Quand je vais sur "Toutes les sources" ca m'ouvre les paramètres

![image](https://user-images.githubusercontent.com/71842302/208329740-2c94377d-50c4-467d-b791-09a8dc320127.png)

**Comment by sizanic** [comment]
> Quand je vais sur "Toutes les sources" ca m'ouvre les paramètres


N'utilises pas la souris mais le clavier.

**Comment by PassionFlix** [comment]
> > Quand je vais sur "Toutes les sources" ca m'ouvre les paramètres
> 
> N'utilises pas la souris mais le clavier.

C est exactement pareil

**Comment by sizanic** [comment]
>> Mais est-ce que tu as au moins la fenetre de progression ?

>pas du tout

Ne sélectionnes pas la proposition automatique de l'autocompletion

**Comment by PassionFlix** [comment]
[https://youtu.be/uEkkUjS14uA](url)

**Comment by PassionFlix** [comment]
On dirait que je n ai aucune sources

**Comment by sizanic** [comment]
Une fois que tu es dans les parametres, regardes les sources que tu as et celles qui sont actives.

**Comment by PassionFlix** [comment]
![image](https://user-images.githubusercontent.com/71842302/208331682-1e857c49-364f-4034-9cc9-32158dbe7f9c.png)

**Comment by PassionFlix** [comment]
Je comprend vraiment pas car j ai bien le fichier sites.json dans USERDATA/ADDON_DATA/PLUGIN.VIDEO.VSTREAM et il n ai pas vide

**Comment by sizanic** [comment]
Regardes surtout celui-là : \addons\plugin.video.vstream\resources\sites.json

Qui doit être le même que : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites.json

**Comment by PassionFlix** [comment]
il contient seulement le mot "FALSE"

**Comment by sizanic** [comment]
pas bon, remplace le contenu

**Comment by PassionFlix** [comment]
MIRACLEEEEEEEEEEE

Merci les sources sont revenu

**Comment by TmpName** [comment]
Encore presrnt ce bug ?

Cette modif n'est pas suffisante ? https://github.com/Kodi-vStream/venom-xbmc-addons/commit/359e5fd7eadc9f21c53e7118b29574a05c3d53a8

Mais pourquoi "false" ?
