### ISSUE TITLE
Ajout d'une source

### ISSUE THREAD

**Issue by MattSpace1** [Kodi-vStream/venom-xbmc-addons#3978]
Bonjour, j'ai découvert un nouveau site qui fonctionne super bien pour les films et séries (pas animes). C'est https://fa stream.tk  et je me demandais si il était possible de le rajouter aux sources ? 

Merci pour votre travail et bonne soirée !

**Comment by yodidon** [comment]
Je regarde ça ce soir

**Comment by yodidon** [comment]
> Bonjour, j'ai découvert un nouveau site qui fonctionne super bien pour les films et séries (pas animes). C'est https://fa stream.tk et je me demandais si il était possible de le rajouter aux sources ?
> 
> Merci pour votre travail et bonne soirée !

Apres test le hoster n'est pas a ma portée. Désolé

**Comment by TmpName** [comment]
Pas mieux ^^
Laisse tomber le bordel juste pour un lien, y a des malades quand meme.
Mais sinon je ne pense pas que le boulot que ca va demander pour recuperer les liens en vaille la peine.

**Comment by sizanic** [comment]
obsolete
