### ISSUE TITLE
Source Novaflix: Classement par année et Outil de recherche

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3983]
Bonjour la team 👋

**Premièrement, un petit souci:**
Dans la nouvelle source ''Novaflix'', le classement (tri) par année contient **et** des films, **et** des séries et ce, même si je choisi une catégorie particulière. 
- Exemple, je me rends dans le menu `Films / Films (Années) / 2022` et j'y retrouve aussi des séries. 
- La même situation se produit dans le menu Série.
- Le classement par genre, quant à lui, semble OK pour les 2 catégories

**Et deuxièmement, une petite question ou demande :**
Puisque la recherche utilise le même URL pour les films et les séries, cette source n'est pas accessible dans la recherche globale de vStream... C'est le même problème si on utilise TMDb Helper avec un player.  Je me doute bien que cette restriction est probablement due au fait que la recherche fonctionne de cette façon sur le site, mais je me demandais s'il n'était pas possible de faire en sotre que la recherche  puisse s'effectuer séparément ? Sait-on jamais, étant donné l'immense talent présent dans la team vStream 😝🙃

Merci encore pour votre travail !!
_J'en profite pour vous souhaiter de belles fêtes de fin d'année et plein de bon temps avec ceux qui vous sont chers_ 😘🎉

**Comment by sizanic** [comment]
Bonjour @alKODIque 

Je te souhaite également de passer de bonnes fêtes.

Merci pour ton retour sur cette nouvelle source.

Pour le tri film/série dans vStream, on devrait pouvoir faire une modification.
Pour TMDBH, tu nous lances un sacré défi, mais on va essayer d'user de notre immense talent 😄

**Comment by yodidon** [comment]
Bonjour @alKODIque ,
J’avais mis en place un filtre pour n’afficher que les films ou les séries dans le trie par année, mais cela n’étais pas très visuellement terrible. Par exemple pour les films , les séries étaient écartées ce qui donnait des Pages avec seulement 4 ou 5 affiches voir parfois moins.
Je vais regarder si je sais faire mieux.
Merci pour ton retour et de bonne fêtes

**Comment by sizanic** [comment]
Nova quoi ? 😄
