### ISSUE TITLE
INTEGRATION ZONE TELECHARGMENT ET TIREXO

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#3988]
Bonjour l'Equipe de vStream, je viens de voir que Zone Telechargement et Tirexo
sont de retour au https://www.zone - telechargement.bond/ et au https://www3.dark ino.com/

Est-ce possible de les intégrer à vStream ?

Cordialement,
Ludo Potte

**Comment by sizanic** [comment]
Bonjour @ludopotte 

On a bien noté ces adresses, et il est prévu de regarder pour les ajouter, si c'est possible.

**Comment by thorsten68** [comment]
C'est vrai que ça serait cool, surtout dark ino
Merci pour le taf 👍💪

**Comment by sizanic** [comment]
on attend vraiment que dark ino se stabilise, car pour l'instant il est plus souvent inaccessible que en fonctionnement.
Et les nouveautés ne sont pas encore arrivées, le catalogue est vieux.

**Comment by thorsten68** [comment]
Bonjour. J'ai vu que tu as fait pas mal de modifs ces derniers jours sizanic. Tu as pu rajouter dark ino ?

**Comment by sizanic** [comment]
Salut.
Non.
J'ai regardé un peu hier mais l'accès aux liens est protégé par cloudflare, ça va être compliqué 😟

**Comment by thorsten68** [comment]
Dommage...
Et zt. bond ?

**Comment by amidevous** [comment]
c'est .org pour darkino maintenant

**Comment by youcam-sat** [comment]
Uptobox.live est de retour.... ya t il un update pour le faire fonctionner ??

**Comment by sizanic** [comment]
obsolete
