### ISSUE TITLE
Proposition d'ajout de plusieurs sites

### ISSUE THREAD

**Issue by MarckuusS** [Kodi-vStream/venom-xbmc-addons#3989]
Bonjour l'Equipe de vStream, j'aimerais faire la demande pour ajouter une série de sites listé ci dessous. Il arrive que les sites sautent mais d'autres apparaissent rapidement pour les remplacer. Etant donné que les sites ont toujours la même architecture, j'imagine qu'une fois le premier intégrer les autres seront plus simple à réintégrer. 

La liste est la suivante 
- Voplav = 'https://voplav.com/'
- Badrip = 'https://badrip.com/'
- Dibrav = 'https://dibrav.com/'
- Choupox = 'https://choupox.com/'
- Rikmod = 'https://rikmod.com/'
- Votrob = 'https://www.votrob.com/'

N'hésitez pas à me tenir au courant si cela est réalisable.

Cordialement,

Marius

**Comment by sizanic** [comment]
Oui, ce sont tous des clones de kepliz que nous proposons déjà.
A savoir que les liens sont uniques entre les sources donc lorsqu'un site ne répond plus, les autres aussi.
C'est comme si c'était tous le même site mais avec une adresse différente.

**Comment by sizanic** [comment]
En ce moment kepliz (nom dans vStream) utilise l'adresse poblom.com, si ce site ferme on changera juste l'adresse avec une autre citée ci-dessus 😆

**Comment by Mariius45** [comment]
Autant pour moi ^^ 

Merci d'avoir répondu. Et oui ce sont bien tous des clones juste le nom et la charte graphique qui change.
