### ISSUE TITLE
Source Frenchstream-lol

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3990]
Bonjour à vous!
Je venais seulement signaler que la source mentionnée dans le titre est maintenant sous protection cloudflare :(  
Elle n'est donc plus accessible depuis vStream.  Je n'ai pas vu de site alternatif ou de clone pour la remplacer malheureusement.
(frenchstream(.)day)

**Comment by sizanic** [comment]
même avec flareSolverr ?

**Comment by alKODIque** [comment]
Ha, bin avec flaresolver c'est probablement accessible effectivement. je n'y avait pas pensé, j'ai pas le réflexe surtout sur ma box android ;)

**Comment by Mokoman30** [comment]
Bonsoir pour Le site French-stream
Le lien c est 
https://french-stream.gg/

**Comment by sizanic** [comment]
Bonsoir

Cette adresse ne répond pas non plus 😟

**Comment by TmpName** [comment]
Mwé, si il changent tout les 3 jours ....

**Comment by GravuTrad** [comment]
Le souci est que flaresolverr est passé à la version 3 (pour mieux suivre les protections mises en place par cloudflare) qui ne supporte pas encore pas mal d'options qui étaient présentes dans la version 2. Est ce que cela change l'implémentation de flaresolverr mise dans vstream?

**Comment by yodidon** [comment]
Flaresolver fonctionne indépendamment de vstream donc ça ne changera rien à vstream

**Comment by GravuTrad** [comment]
ok merci de la confirmation

**Comment by sizanic** [comment]
> ok merci de la confirmation. Mais totalement sûr? Y a quand même une implémentation quand même

non, vStream n'implemente pas flareSolverr.
flareSolverr s'installe de façon indépendante de vStream.
vStream va utiliser flareSolverr en utilisant une méthode générique qui reste compatible quelque soit la version utilisée de flareSolverr.
Donc oui, complètement sûr.

**Comment by GravuTrad** [comment]
Nicekl merci. Donc plus qu'à attendre un update de flaresolverr qui remarche.

**Comment by GravuTrad** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/pull/4004

**Comment by GravuTrad** [comment]
Maintenant french-stream.gg

**Comment by sizanic** [comment]
Merci, on a changé.

**Comment by Mokoman30** [comment]
French stream lol n est plus protéger a l heur actuel pourvu que sa dure

**Comment by GravuTrad** [comment]
French stream lol c'est depuis un moment maintenant french-stream.gg, et c'est toujours bien protégé par cloudflare.

**Comment by sizanic** [comment]
L'adresse utilisée par vStream pour la source "french stream lol" n'est ni en .lol, ni l'adresse .gg

C'est une autre adresse qui fonctionne bien, il n'y a que se rendre dans vStream pour constater de la collection de films proposés et que les liens sont accessibles (donc pas de cloudflare).

**Comment by GravuTrad** [comment]
En effet. Vous avez changé le lien? (car avant ça signalait bien cloudflare et de passer par flaresolverr)
Possible de savoir vers quel site il pointe?

**Comment by sizanic** [comment]
je viens de voir qu'il a été changé il y a 3 jours ( c'était bien .gg avant).

> Possible de savoir vers quel site il pointe?

Tout le code de vStream est visible ici.
Dans les resources du plugin.video.vstream, tu devrais rapidement trouver un fichier qui fait références aux sites.

**Comment by GravuTrad** [comment]
Ca me rassure. car le site de base pour cela est bien gg. Peut être un site miroir mis en place (clair que plus simple et moins chiant).
Merci sizanic je regarderais.
(car tout aussi efficace que l'original, mais je garde l'original en source sur mon ordi car c'est tout le même le site le plus réactif. Je pense que les autres récupèrent souvent chez eux.)

**Comment by GravuTrad** [comment]
oui vu. clairement une page miroir. sur le site original il y a l'accès vers le discord du site/groupe. Pas sur ce site. mais ça semble aussi réactif que sur celui d'origine. donc ça me va lol.

**Comment by sizanic** [comment]
On est bien obligé de passer par des sites miroir à cause des protections.
Tant mieux si ça te va,
alors ça nous va aussi 😄

**Comment by Mokoman30** [comment]
Bon 
French stream lol à nouveau protéger j ai plus accès maintenant 
Sa aura durer 2 semaine au moins 
Dommage

**Comment by GravuTrad** [comment]
Avec flaresolverr à jour ça marche de toute façon.

**Comment by GravuTrad** [comment]
mais pour le cas actuellement on dirait plus du souci semoule cloudflare
