### ISSUE TITLE
Bug - Source pastebin avec la dernière bêta

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#3991]
Bonjour @sizanic 

J'ai testé la dernière bêta, depuis ce commit pour la nouvelle réso dans la souce pastebin: https://github.com/Kodi-vStream/venom-xbmc-addons/commit/ef1ba59ecff3b5818d7f64c461be0283dcbf055e

 Les codes ne sont plus supportés. L'erreur concernant la mauvaise version python est revenue :
`[PLUGIN] vStream: Exception 'pastebin', ID=RMZgA92Vb, e=bad magic number in 'Chiffrage': b'U\r\r\n'`

Tout reviens à la normale en réinstallant la version officielle de vStream 👍

- Je suis sous Nexus RC2
- Test fait sur ma shield tv pro 2017

Bonne journée!

**Comment by sizanic** [comment]
Ok. 
Comme ça au moins j'ai des retours directs avec cette beta 😅

**Comment by sizanic** [comment]
J'ai ajouté des informations dans le log pour avoir la version Python.
Si tu peux regarder, je pourrais modifier le code en conséquence.

**Comment by sizanic** [comment]
@alKODIque 

A tester avec la derniere version 2.4.0

**Comment by sizanic** [comment]
Corrigé en Version 2.4.1
