### ISSUE TITLE
"Format non supporté" lors de l'ajout code pastebin kodi 20 nexus

### ISSUE THREAD

**Issue by nat80** [Kodi-vStream/venom-xbmc-addons#3993]
**Le bug**
Après avoir fait une réinstallation propre sur la nouvelle version kodi 20, j'ai l'erreur "Format non supporté" quand je rentre un code pastebin du pack alkodiques

**Votre system**
- OS: [Windows 11 64 bits]
- Version Kodi: [20.0]
- Version Vstream: [2.3.0]
- Version Python: [3.11.1]

**Log**
[[](https://pastebin.com/raw/ptvx5iSi)](https://pastebin.com/raw/ptvx5iSi)

**Comment by sizanic** [comment]
Il y a déjà plusieurs discussions à ce sujet 😟

**Comment by nat80** [comment]
J'ai refait le test sous kodi 19.5 avec une config sauvegardé et même erreur

**Comment by sizanic** [comment]
Traité ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3958
