### ISSUE TITLE
"Invalid order field" sur ouverture du compte uptobox via vstream

### ISSUE THREAD

**Issue by swazen** [Kodi-vStream/venom-xbmc-addons#3995]
**Description**
Consultation des vidéos liées au compte uptobox premium impossible !
Message : invalid order field

**Mes infos**
- OS: Windows 11 22H2 et Google TV (Android 11)
- Version Kodi: Nexus 20.0
- Version Vstream: 2.3.0

Les liens uptobox externes s'ouvrent parfaitement, seul ma librairie perso est inaccessible...
TOKEN installé depuis 12/2022

**Comment by syster49** [comment]
Je confirme j ai le même problème depuis hier.

**Comment by swazen** [comment]
Pb différent!! Token installé et fonctionnel depuis décembre

**Comment by Pitipito** [comment]
Bonjour,
Pour info, une maintenance générale du site uptobox a été effectuée hier (la plus grosse migration qu'ils aient faite en 12 ans d'après leurs dires) afin de proposer des améliorations, de nouvelles fonctionnalités et performances.
Le problème (invalid order field) est survenu juste après cette maintenance.

**Comment by syster49** [comment]
Non c pas le même problème.
Je confirme que ton token est bien configuré.
J ai regarde ds le kodi.log, je vois bien de logs du plug-in vstream mais pas de message d erreur.
Y a t il un autre moyen d avoir un débug ?

**Comment by sizanic** [comment]
La modification dans vStream pour supporter l'évolution d'uptobox vient d'être traitée.

Une nouvelle version de vStream va rapidement être disponible.

**Comment by sizanic** [comment]
> Non c pas le même problème. Je confirme que ton token est bien configuré. J ai regarde ds le kodi.log, je vois bien de logs du plug-in vstream mais pas de message d erreur. Y a t il un autre moyen d avoir un débug ?

Le probleme est corrigé, il faut attendre la mise à jour.

**Comment by syster49** [comment]
Super merci pour votre réactivité.

**Comment by swazen** [comment]
Merci @sizanic

**Comment by BENJI97200** [comment]
@sizanique....merci ,la mise a jour arrivera quand stp....désolé merci pour votre travail?

**Comment by sizanic** [comment]
c'est une question d'heure ...

**Comment by BENJI97200** [comment]
Merciii

**Comment by sizanic** [comment]
La dernière Version 2.4.0 de vStream est sortie et corrige ce probleme.

**Comment by domi74000** [comment]
Super ça fonctionne!!! Merci beaucoup sizanic pour le super boulot.

**Comment by BENJI97200** [comment]
Merci sizanic.. .. vraiment bravo ☺️
