### ISSUE TITLE
Kodi 20 - impossible de lancer un film (bad magic number in 'Chiffrage': b'\xa7\r\r\n')

### ISSUE THREAD

**Issue by nat80** [Kodi-vStream/venom-xbmc-addons#3996]
**Décrivez le bug**
Impossible de lancer un film via la source pastebin avec compte uptobox,
Le log indique : 
ImportError: bad magic number in 'Chiffrage': b'\xa7\r\r\n'

**Votre system**
- OS: [Windows 64bits]
- Version Kodi: [20.0]
- Version Vstream: [2.3.0]

**Log**
[https://pastebin.com/raw/QG7bMCvj](https://pastebin.com/raw/QG7bMCvj)

**Comment by nat80** [comment]
J'ai réinstallé l'addon, problème résolu

**Comment by nat80** [comment]
J'ai pris à partir de la beta oui j'ai oublié de préciser

**Comment by sizanic** [comment]
oui, ce serait bien de préciser car forcement tu peux avoir des dysfonctionnement si tu installes des versions Beta qui sont en cours de développement.

Sans le préciser, on ne cherche pas au bon endroit.

Normal que maintenant ça refonctionne en Beta, je viens de faire une correction.

En tout cas comme ça je sais que ma correction fonctionne pour Windows et Kodi20.

**Comment by nat80** [comment]
Super merci !
