### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#4002]
Bonsoir à tous,

**Décrivez le bug**

- ex: 4kstreamz (il y en a d'autres). Avec DNSCHANGER les posters s'affichent alors que avec dnspython pas, je précise que la aussi on utilise addLink et que le synopsis fonctionne pour les séries et les films mais on affiche pas les posters ???? peut être un lien entre ces 2 bugs (DNSpython) ou bug de addLink. 1seriestreaming aussi utilise addLink et la pas de souci ?????

- Dans guiElement la fonction unicode n'est pas importé, ligne 390. Mon IDE me propose de l'importé
   de "from resources.lib.librecaptcha.pyparsing import unicode" mais elle n'existe pas !!!
   unicode aussi utilisé dans la lib config mais pas importé.

- le titre des séries à l'utilisation de addEpisodes qui s'affichent "1x01. 1x1." ne peut on pas faire un choix ??? moi je suis pour 1x01, je serais même pour un retour de l'ancienne écriture S01E01 tout en laissant le choix du titre de l'épisode proposer si utilisation des métadonnées.
- L'utilisation des métas qui remplace les données fournies par la source, parfois elles sont erronées, ne peut on pas donnée la priorité aux données récupérer par la source, et si elles sont absentes on utilise les métadonnées. Exemple "les liens du sang" sur ducine (dead) pas le même film que la synopsis et le poster proposé par les métas..

Voila quelques bugs

**Votre system**
- Appareil: Box android et pc windaube
- Version Kodi: [19.4]
- Version vStream: la bêta

**Comment by yodidon** [comment]
au premier regard de addlink je vois pas ce qui serait mise en cause, a voir

**Comment by razorex** [comment]
@yodidon moi aussi j'ai regardé, et je m'explique pas non plus.. C'est pourquoi je soumet l'hypothèse extérieur à vStream (dnspython) mais la aussi rien de sûr. Quand j'étais encore sous kodi19.1 j'avais accès a 4kstremz sans dnspython. Depuis que je suis monté en 19.4 utilisation de dnspython obligatoire. En plus sur 3 sources en exemples 2 pb différent et une qui marche ????????

**Comment by razorex** [comment]
Bon petit retour après test:
J'ai enlevé DNSpython sur kodi sous windows,.
En ne modifiant que les dns IPv4 : 1.1.1.1 et 1.0.0.1 pas d'amélioration, en modifiant les dns IPv6 : 2606:4700:4700::1111 et 2606:4700:4700::1001 miracle sa fonctionne pour les posters sur 4kstreamz

**Comment by TmpName** [comment]
Alors le synopsis, tu aurais une capture qui fonctionne pour comparer ? J'ai essayé tout les affichages possibles, j'ai fais 3 sites, pas un seul qui les affiches.

Comment provoquer ton erreur unicode ?

Pour les titres je suis d'accord avec toi, je prefere aussi le standard SXXeXX, mais ca a été modifé de memoire pour des histoire de compatiblité, je suis plus avec quoi, mais je ne pense pas que ce soit utile d'avoir les doublons, si quelqu'un se souvient de la raison de ce changement ?

**Comment by razorex** [comment]
Salut @TmpName
Pour le titre moi il me semble que l'on m'avait répondu  "tout le monde fait ainsi",j'avais ouvert des issues et je simplifie la réponse, ma mémoire peut me faire faux bond. Le but premier était de remplacer le titre de la série par le titre de l'épisode récupéré en métadonnées mais on aurait pu garder le format SXXEXX puis Episode N°x (moi par défaut j'aurais garder le titre de la séries si pas de nom d'épisodes en méta) ou SXXEXX puis "Titre de l'épisode" récupéré en meta.

Pour le unicode c'est l'IDE qui me dit qu'il y a une erreur car la lib unicode n'est pas importé, pas un bug remonté en défaut.
Pour le synopsis j'ai donné des ex de sources, si tu n'a pas comme moi c'est encore plus dingue. je mettrais des captures d'écrans.
Ex: **alloflix, 4kstreamz, 1seriestreaming**

**Comment by razorex** [comment]
J'avais oublié la lecture de l'épisode suivant sur plusieurs source au lieu de lire le suivant on vient relire le N°1 et même parfois quand on a lu le dernier on reprend au 1....

**Comment by razorex** [comment]
une capture d'écran sur une série d'alloflix, comme tu peut le voir le synopsis est absent alors qu'on l'a récupéré. petite remarque d'habitude lorsqu'il n'y a rien il y a un "texte" sous l'affiche qui dit qu'il n'y a pas d'info...
![image](https://user-images.githubusercontent.com/26149640/213890219-d88a52ba-9ff8-40b6-b819-e07ace85b898.png)

**Comment by sizanic** [comment]
je viens d'installer un kodi 20 tout neuf, installation de vStream officiel 1.4.2.

Et voilà : 
![image](https://user-images.githubusercontent.com/47307622/213894410-15d9aeb7-81b7-44c4-8e9d-01af97f47766.png)

**Comment by sizanic** [comment]
Et si je désactive la recherche des métadonnées : 

![image](https://user-images.githubusercontent.com/47307622/213894501-84c0964c-7560-4fa0-bdb8-537171214bba.png)

**Comment by sizanic** [comment]
oups !!!

J'ai voulu supprimer un de mes commentaire mais j'ai supprimé le tien @razorex  😄

**Comment by sizanic** [comment]
C'était sur le fait qu'il n'y ai pas la description pour les épisodes de séries de Alloflix.

![image](https://user-images.githubusercontent.com/47307622/213894615-5c177df0-d338-49ef-a0ad-259a77962abd.png)

**Comment by sizanic** [comment]
> le titre des séries à l'utilisation de addEpisodes qui s'affichent "1x01. 1x1." ne peut on pas faire un choix ???

Il y a déjà un choix : 

![image](https://user-images.githubusercontent.com/47307622/213894665-ec007174-7915-4aa1-ae70-129aa6060a0d.png)


Pour reprendre ce qui est fait : 
On précise à kodi de quelle saison il s'agit et le numéro de l'épisode.
Et la saison et l'épisode sont alors affichés à un endroit qui diffère selon l'habillage.

Par exemple : 
![image](https://user-images.githubusercontent.com/47307622/213894741-f761bd1e-0a06-4131-b65e-2bc835535f08.png)

Mais il arrive ces informations ne soit pas bien visible, voire même pas du tout affichées sur ceratins habillages.
Donc, on peut activer une option pour forcer l'affichage de la numérotation de la saison et de l'épisode.

Ce qui peut donner : 

![image](https://user-images.githubusercontent.com/47307622/213894819-2645d074-8e77-4242-9e33-bd1d536391be.png)

**Comment by sizanic** [comment]
Il y a des habillages (celui par défaut par exemple) qui ont choisie d'afficher la numérotation au niveau du titre : 
![image](https://user-images.githubusercontent.com/47307622/213894880-e94887a4-ba58-449c-8366-c93a0007e2d5.png)


Et donc forcement, si on active l'option, les deux numérotations se retrouvent ensemble : 
![image](https://user-images.githubusercontent.com/47307622/213894907-83c69afe-4d20-4df3-b282-beb06a65b535.png)

**Comment by sizanic** [comment]
> moi par défaut j'aurais garder le titre de la séries si pas de nom d'épisodes en méta

Pas trop compris.
Si on prends par exemple la série "**Les rivières pourpres**" mais qu'on a pas les noms d'épisodes.

On ne met pas : 
- Episode 1
- Episode 2
- Episode 3


Mais on répète juste le nom de la série ?? : 
- Les rivières pourpres
- Les rivières pourpres
- Les rivières pourpres

**Comment by sizanic** [comment]
Pour la description des épisodes de alloflix, c'était pas la même regex que pour les films, j'ai changé.

**Comment by razorex** [comment]
Suis une nouille j'étais persuadé que la regex était la même. il me semblait pourtant avoir tester avec une séries.
Avant on aurai eu :
- S01E01 Les rivières pourpres
- S01E02 Les rivières pourpres
- S01E03 Les rivières pourpres
Mais ok avec cette option d'affichage saison et épisodes dans le titre

Il reste la lecture de l'épisode suivant et les posters qui ne s'affichent pas ex 4kstreamz et il y en a d'autres..

**Comment by sizanic** [comment]
> Avant on aurai eu :
S01E01 Les rivières pourpres
S01E02 Les rivières pourpres
S01E03 Les rivières pourpres

Avec un habillage qui affiche la saison et l'épisode en dehors du titre (comme ma première photo des rivières pourpres), on va se retrouver avec : 
- Les rivières pourpres
- Les rivières pourpres
- Les rivières pourpres

Plutot que : 

- Episode 1
- Episode 2
- Episode 3

**Comment by sizanic** [comment]
> Il reste la lecture de l'épisode suivant et les posters qui ne s'affichent pas ex 4kstreamz et il y en a d'autres..


Je referais un passage pour vérifier ça ...

**Comment by sizanic** [comment]
Lequel ? 😄 

Plusieurs soucis sont cités, je n'arrive pas à voir ce qui ne va pas 🤔

**Comment by TmpName** [comment]
Lol, pareil, comme sur l'autre issue, c'est histoire de filtrer les derniers problemes encore present.

**Comment by sizanic** [comment]
parmi les 5 points cités dans la demande initiale, il y en a 2 qui demandent encore réflexion.
Je vais y répondre.

**Comment by razorex** [comment]
Derniers problemes present !!!!!
Listé oui, mais il y en a d'autres encore..

**Comment by TmpName** [comment]
Pour le soucis unicode dans guiElement.py ca vient de python 2, en python 3 c'est en unicode par defaut.
On assure tjours la compatiblité python 2 ?

**Comment by sizanic** [comment]
J'ai vu ça pour unicode.

Et ce n'est pas le seul endroit.

Pour la compatibilité, il y a les try/catch
ou on peut mettre en place ce système : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/d01d12e9c4e1ee47581988897bec82d29614ec64/plugin.video.vstream/resources/lib/librecaptcha/pyparsing.py#L227


Concernant l'arret de la compatibilité de Py2, ça ne m'arrangerait pas vraiment que ce soit fait très prochainement.
Donc je m'en chargerais quand ce sera le bon moment (pour moi).

**Comment by TmpName** [comment]
Pas de probleme, c'etait juste pour savoir avant de proposer du code qui allait tout casser ^^.

Et yep bonne idée, c'est simple et rapide

```
try:
    unicode = str;
except:
   pass
```

**Comment by sizanic** [comment]
Sans tester je pense que ce n'est pas bon.
Car unicode existe en py2, il faut donc rediriger seulement en py3.

**Comment by TmpName** [comment]
Et ca ? (trouvé sur un forum)

```
try:
    unicode
except NameError:
    unicode = str   # Python 3 compatibility
```

**Comment by sizanic** [comment]
j'aime bien, plus performant je pense que la solution que j'ai proposée (avec la lecture de la version de python).

**Comment by sizanic** [comment]
Je pense que tout est bon.
Sinon, rouvrir un ticket
