### ISSUE TITLE
🖐️ Mise a jour incompatible avec Kodi 20

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#4003]
![8](https://user-images.githubusercontent.com/48101775/213864691-a3b09065-b436-4a5f-9bea-8f7902fe7a87.gif)**Bonjour,**
Je vous joint en photos l'erreur de Vstream 
pour la mise a jour **dans Kodi 20 Nexus**
publié sur google play store.

![674](https://user-images.githubusercontent.com/48101775/213864753-7aacbb90-f063-4c42-b8da-e14c4380738a.gif)**"Bloquage via Url Revolver"** .

_**Vstream en lui même fonctionne à part ça.**_ ✔️

![Vstream](https://user-images.githubusercontent.com/48101775/213864779-6f798afa-de4d-4e39-958d-d0c35921ea5b.jpg)

![Vstream2](https://user-images.githubusercontent.com/48101775/213864789-d1dda7b4-0493-4273-b6da-2ba3290c58d1.jpg)

![Vstream3](https://user-images.githubusercontent.com/48101775/213864801-938031ce-251f-478d-9609-8fb8ac7cd70e.jpg)

**Comment by TmpName** [comment]
Donc pour le moment c'est plutot compatible, surtout que c'est pas Vstream qui gere URLResolver.

**Comment by sizanic** [comment]
Oui, vStream n'utilise plus urlResolver mais...

Je vois toujours la dépendance (optionnelle) dans addon.xml 🤔

**Comment by TmpName** [comment]
Je viens de rechecker, nope, pas utilisé du tout.
Pour moi on peut retirer.

**Comment by sizanic** [comment]
et je pense que selenium aussi.

**Comment by TmpName** [comment]
Oui, lui c'est pire, y  a meme pas de trace de code avec ^^

**Comment by victore447** [comment]
![98](https://user-images.githubusercontent.com/48101775/213878507-3275b431-3391-468b-ad9c-816222e14db2.gif)**Attention pour info,
 il y a Android 11 qui restreint beaucoup ça racine avec kodi 20 sur les Box tv etc...**

Je l'ai remarqué avec l'addon backup.
Sous Android 11 via ma Shield tv on est obligé de crée une source smb via un stockage externe maintenant pour pouvoir sauvegardé et restauré Kodi 20.

![612](https://user-images.githubusercontent.com/48101775/213878586-8d215160-2dd9-40a7-90a8-18863796d964.gif)Si on n'a pas augmenté Android 11 par disque externe,Backup est inutilisable et on ne voie pas
la source cible sélectionné et souhaité 

![46](https://user-images.githubusercontent.com/48101775/213878540-3521b06c-e785-441c-b99a-370f79f6af21.gif)

https://github.com/robweber/xbmcbackup/issues/214

**Comment by sizanic** [comment]
Pour les utilisateurs Android 11+, il faut autoriser le stockage connecté localement.
Si vous utilisez un stockage externe USB sur votre Box, après la première exécution, procédez comme suit pour autoriser Kodi à accéder à vos dossiers et fichiers :

Après être passé sous Kodi v20, accédez aux paramètres Android et rendez-vous sur : Apps
puis " Voir toutes les applications "
Appuyez sur Kodi,
Allez dans Autorisations,
Fichiers et médias,
et changez l'autorisation pour ''toujours autoriser''.

**Comment by victore447** [comment]
![mini-respect-1392](https://user-images.githubusercontent.com/48101775/213880323-52e8388f-f67e-4533-8f92-13b2d62c9922.gif)
Exact Zizanic pour l'autorisation
de stockage et Bien vue.
Je vient de voir ça et n'y aurais pas pensé.

**Comment by sizanic** [comment]
C'est une information que j'ai retrouvée auprès de la communauté "les alKODIques".
(présente sur facebook, discord et site internet)

Je te la conseille.

**Comment by victore447** [comment]
![7](https://user-images.githubusercontent.com/48101775/213880768-e0c1586a-7a43-44c3-8e7a-bc3fdda50371.gif)**Ok Zizanic** ✔️
