### ISSUE TITLE
Hello my friend 

### ISSUE THREAD

**Issue by jasonalshamary** [Kodi-vStream/venom-xbmc-addons#4005]
Hello my friend I really like your addon 
It’s the best I ever used so far
I’ve been trying to make something like you addon 
I edit yours trying to learn but it didn’t work with me 
I was hoping you can teach me if that’s ok with 
On this website ht tps://www.cartoon-arabic.network/
Can you explain where to start please and thank you in advance 🥰

**Comment by TmpName** [comment]
Hello, you have a starting point here, with somes explanations, but in french https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source

**Comment by yodidon** [comment]
> Hello my friend I really like your addon
> It’s the best I ever used so far
> I’ve been trying to make something like you addon
> I edit yours trying to learn but it didn’t work with me
> I was hoping you can teach me if that’s ok with
> On this website ht tps://www.cartoon-arabic.network/
> Can you explain where to start please and thank you in advance 🥰

if you have discord, do not hesitate to contact me if I can help you

**Comment by jasonalshamary** [comment]
Thank you you are the best
I’m new on discord how can I add you ???

Sent from my iPhone

On Jan 28, 2023, at 5:22 PM, yodidon ***@***.***> wrote:

discord

**Comment by jasonalshamary** [comment]
You can add me

Jayjay2002#5111

Sent from my iPhone

On Jan 28, 2023, at 5:44 PM, jason alshammary ***@***.***> wrote:

﻿
Thank you you are the best
I’m new on discord how can I add you ???

Sent from my iPhone

On Jan 28, 2023, at 5:22 PM, yodidon ***@***.***> wrote:

discord

**Comment by jasonalshamary** [comment]
What your discord name bro

**Comment by TmpName** [comment]
Better to go direclty on the Vstream Discord https://discord.gg/S65HBXm
