### ISSUE TITLE
Notification Discord

### ISSUE THREAD

**Issue by PassionFlix** [Kodi-vStream/venom-xbmc-addons#4014]
Bonjour tout le monde,

Je souhaiterais émettre une petite proposition d'option configurable et activable ou non suivant les besoins des utilisateurs ;)

Certains me connaissent bien et d'autres non mais je suis (trop trop) connecté sur discord avec la communauté "les alKODIques"

Donc je me demande si dans les paramètres de vstream, il ne serait pas possible de mettre une option (que l'utilisateur active au besoin) paramétrable, permettant de mettre un webhook discord 

Celui ci enverrait simplement une notification pour dire le titre du média qui vient d etre lancé

Ca pourrait donner quelques choses du genre

@PassionFlix vient de lancer le média **Black Adam**

Il me semble que cela pourrait permettre d'engager des conversations autour de ses médias justement

Dans les paramètres que l'utilisateur devrait configurer il ne devrait y avoir que 

Option activé ou non
url du webhook
Pseudo discord de l'utilisateur

Merci de m'avoir lu ;)

**Comment by alKODIque** [comment]
Salut @PassionFlix 
Je sais pas si ce service peut être directement appliqué a un addon . J'ai l'impression qu'il s'agit de quelque chose qui doit être ajouté directement à Kodi, via un addon de service ifttt.

- Genre, cet addon: https://github.com/plucka3/service.ifttt

Mais malheur, il n'est plus entretenu et fonctionnait sous Kodi v18 (Leia). - donc pas en python 3

**Comment by PassionFlix** [comment]
Coucou @alKODIque 
Je ne connaissais pas ce genre de service
n'utilisant que vstream et la source pastebin sur tous mes appareils je ne voyais que la simplicité pour moi que d'avoir cette option dans le seul addon que j'utilise

**Comment by sizanic** [comment]
IFTTT
