### ISSUE TITLE
Problème recherche film avec uptobox

### ISSUE THREAD

**Issue by benstelll35** [Kodi-vStream/venom-xbmc-addons#4015]
**Décrivez le bug**
Je n'arrive plus à trouver des films avec la source Uptobox Live d'activée. Plus précisément, quand je cherche le nom d'un film et que je valide, kodi m'affiche un message d'erreur et ne trouve rien (No item).
Tout fonctionnait correctement il y a une semaine.
J'utilise kodi sur plusieurs appareils différent (nvidia shield, freebox pop, manjaro)

**Votre system**
- OS: [Manjaro]
- Appareil: [pc]
- Version Kodi: [20.0]
- Version Vstream: [2.4.3]

**Log**
https://pastebin.com/raw/NV4p9fvt

**Image**
![Screenshot_20230222_222634](https://user-images.githubusercontent.com/103068285/220763073-ff80a75f-1a9c-445b-8e07-26fb0038b2fc.png)

**Comment by sizanic** [comment]
Le site est fermé !
On ne sait pas si c'est temporaire, mais ça pourrait durer...

Si tu utilisais ce site, c'est que tu as un compte uptobox (ou un debrideur).

Tu peux toujours te rabattre sur la source Pastebin.

**Comment by benstelll35** [comment]
Ok super merci beaucoup pour ta réponse rapide.
Oui effectivement, j'ai un compte uptobox premium.
Parcontre je ne sais pas comment accèder à la bibliothèque de film sur pastbin. J'ai activé pastbin dans les sources sur Vstream et quand je fais une recherche il ne trouve rien.
J'ai pas encore tout compris...

**Comment by sizanic** [comment]
Le contenu de pastebin s'active en renseignant des codes.
Ce sont des codes privés. 

La communauté "les alKODIques" propose un pack de codes (des codes pour films, séries, animés, doc, concerts, reportages, doc, ...). Tu renseignes les codes qui t'intéresse.

Tu peux la retrouver sur facebook, Discord et leur site nternet.

**Comment by benstelll35** [comment]
Ok je comprend mieux !
En tout cas merci beaucoup vous êtes au top !!

**Comment by youcam-sat** [comment]
Uptobox.live est de retour.... ya t il un update pour le faire fonctionner

**Comment by gui78120** [comment]
Uptobox.live de nouveau en ligne mais seulement en lecture seule

**Comment by gui78120** [comment]
Uptobox.live devient Uptobox.mov.
Ça y est, le site n'est plus en lecture seule
