### ISSUE TITLE
carré kodi18 qui met le chargement

### ISSUE THREAD

**Issue by Espinete** [Kodi-vStream/venom-xbmc-addons#4017]
grâce à vous enfin et après un an et demi de recherche et de recherche, je peux voir les films uptobox sur kodi18, il s'avère qu'en bas à droite de kodi18 il y a un carré qui dit chargement et le film entier reste visible. Pourriez-vous, s'il vous plaît, me dire comment vous pouvez regarder le film sans voir ce carré qui indique chargement ?

- Version Kodi: [18]
- Version Vstream: [2.4.3]
![cargando](https://user-images.githubusercontent.com/18357275/224366987-d1686139-d91a-47c1-9245-e28e59aeb621.PNG)
[(https://user-images.githubusercontent.com/18357275/224366987-d1686139-d91a-47c1-9245-e28e59aeb621.PNG](url)

**Comment by sizanic** [comment]
Bonjour,
Essaie de changer le "lecteur par défaut" dans les paramètres du lecture de vStream.

**Comment by Espinete** [comment]
merci beaucoup, ça a fonctionné correctement

**Comment by sizanic** [comment]
Ce sont les films de ton compte que tu essaies de regarder ?

**Comment by Espinete** [comment]
Oui, je veux voir les films depuis mon compte, j'utilise mon addon qui est livestreampro et depuis cet addon j'appelle votre addon pour pouvoir voir le film

Je voudrais savoir comment demander des films sur le serveur uptobox

Pourriez-vous m'apprendre?

**Comment by sizanic** [comment]
Tout le code de vStream qui permet de récupérer le flux vidéo à partir d'un lien uptobox est disponible librement ici.

Je ne peux pas t'aider plus pour ton addon.
Surtout que je ne sais pas si ton addon est destiné à être vendu, et ce n'est pas notre philosophie.

Et surtout que vStream propose déjà l'accès à tout un catalogue de liens uptobox (32 000 films), je ne vois pas ce que tu pourrais proposer de plus.
(Je fais référence à la source premium de vStream : la source Pastebin)

**Comment by Espinete** [comment]
Ce que je veux, c'est apprendre à créer mon propre addon pour qu'à partir de mon addon créé par moi, je puisse demander uptobox mes films que j'ai téléchargés sur ce serveur, je suis passionné par tout ce monde de kodi mais je ne sais pas où je dois commencer à étudier pour atteindre mes objectifs

Ce que je veux, c'est que quelqu'un m'apprenne python axé sur la création de mon propre addon et aussi m'apprenne python axé sur la demande de films à partir du serveur uptobox

**Comment by Espinete** [comment]
Mon intention est d'avoir mon propre addon, de pouvoir voir les films que je télécharge sur le serveur uptobox et de partager mon addon avec mes amis et ma famille, je veux apprendre pour un simple divertissement sans but lucratif.

**Comment by sizanic** [comment]
C'est dommage de faire attendre tes amis et ta famille le temps que tu apprennes à faire ce que vStream fait déjà (le partage et la lecture des fichiers de ton compte uptobox).

Pourquoi ne pas leur partager vStream en attendant.

surtout qu'en attendant, on ne peut pas t'aider, désolé.
On a déjà pas assez de temps à consacrer à notre propre addon.
