### ISSUE TITLE
Ajout de Go4 stream

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#402]
Bonjour je souhaiterais savoir si c'est possible d ajouter Go4stream (anciennement series-ddl.com) et ddl-island.su?

Merci

**Comment by TmpName** [comment]
Si tu as deja teste ces sites, tu y as deja trouve du contenu qui n'est pas deja present sur Vstream ? ou en moins bne qualitee ?

**Comment by AizenKnower** [comment]
Des contenu qui sont pas dispo en HD comme marco polo ou black sails
Ya des series en SD c'est pas m ideal.
J ai plutot l impression que les series netflix et sd sont pas sur les autres site
Je n'ai que ces 2 la en tete mais ya tres peu de site sur vstream qui font des séries hd a part voirfilms.net mais certaines series hd sont pas accessibles sur vstream
Voirfilm et go4stream les 2 ensemble constituent une librairie complete de serie en HD
Ex saison 1 de black sails ya je 3 épisode en hd grace a Alluc alors je regarde sur go4stream et je vais regarde les saison 2 et 3 sur voirfilms grace a vstream si il y a ou grace a Alluc
Merci beaucoup car cela m evite de jongler entre vstream et le net
Merci



On Sat, Jun 18, 2016 at 5:16 PM +0200, "TmpName" <notifications@github.com<mailto:notifications@github.com>> wrote:


Si tu as deja teste ces sites, tu y as deja trouve du contenu qui n'est pas deja present sur Vstream ? ou en moins bne qualitee ?

-

**Comment by TmpName** [comment]
Tu as regarde le site megastr eam ? Ils ont des liens sur openload qui sont d'assez bne qualite.
Sinon je n'en ai pas trouve non plus sur Go4s tream en HD pour marco polo, il y a 720p dans le titre mais le fichier ne depasse pas les 420p en reglant tout au max.
