### ISSUE TITLE
Améliorer la partie TV en direct

### ISSUE THREAD

**Issue by MattSpace1** [Kodi-vStream/venom-xbmc-addons#4020]
Bonjour, 

J'ai remarqué que la partie IPTV de vstream n'était pas très complète au niveau du nombre de chaînes disponibles. 

Je me demandais donc si il était possible d'utiliser des liens m3u pour compléter le nombre de chaînes disponibles. J'ai trouvé de bonnes listes qui fonctionne vite et de bonne qualité. 

Je ne sais pas exactement comment vous faites pour intégrer les liens de streaming mais je propose quand même. 

Merci pour votre travail !

**Comment by sizanic** [comment]
Bonjour ,

vStream ne propose pas d'IPTV,
et il n'en proposera jamais !

Car l'origine des fichiers m3u sera toujours douteuse.

Si tu as un fichier m3u, tu peux l'utiliser dans kodi avec l'extension officielle IPTV de kodi, disponible dans le repo officiel de kodi : "IPTV Simple Client".


vStream ne propose que du streaming, pas d'IPTV.
Et le simple client IPTV le fait très bien, avec tout ce qui va avec : 
- gestion de l'EPG
- gestion des groupes de chaines
- intégration au menu "TV" de Kodi

**Comment by MattSpace1** [comment]
Ok c'était juste une proposition.

**Comment by sizanic** [comment]
Merci pour la proposition.
nous sommes toujours intéressé pas les propositions pour faire évoluer vStream.
(mais vStream n'évoluera pas vers de l'IPTV, surtout lorsque des systèmes existent déjà)

Si tu connais par contre des sites qui proposent des chaines en Live, cela nous intéressent pour agrémenter notre catalogue "En direct".
