### ISSUE TITLE
source pastebin hébergeur uqload marche pas sur les films

### ISSUE THREAD

**Issue by amidevous** [Kodi-vStream/venom-xbmc-addons#4025]
**Décrivez le bug**
les liens de l'hébergeur uqload.co ne fonctionne pas avec la source pastebin sur les films
alors qui fonctionne correctement sur les séries

**Votre system**
- OS: Android
- Appareil: Bbox 4K HDR
- Version Kodi: 20
- Version Vstream: stable

**Nous devons le reproduire**

- Nom du site: pastebin.com
- Titre du fim/serie: code pastebin pour tester 1fWrJ9BG (https://pastebin.com/raw/1fWrJ9BG)
- Nom du host uqload.co

**Log**

indisponible sur cette box fichier système inaccessible

**Video**

https://user-images.githubusercontent.com/7959572/226186450-2cff4932-b361-45b8-84cd-8cd408ab5a13.mp4

**Comment by amidevous** [comment]
sa serait possible de régler ce problème svp toujours pas de réponse de votre part depuis 2 jours

j'ai une bibliothèque de plus 25000 films et plus de 10000 séries a partager avec la comu sur cette hébergeur

et parmi lesquels une grande partie n'est actuellement disponible sur aucune des source actuellement compatible avec vstream

mais je peux rien partager tant que ce soucis n'est pas résolue donc svp merci de régler ce problème le plus rapidement possible

**Comment by alKODIque** [comment]
Je ne comprends pas, la source pastebin ne fonctionne qu'avec les liens premium uptobox 🤔

**Comment by sizanic** [comment]
Alors il y a bien un petit souci dans vStream.

Pour le contourner, contrairement à la doc : https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Voir-et-partager-sa-biblioth%C3%A8que-priv%C3%A9e

-> Enleves les apostrophes de chaque côté du lien.

Et si tes liens sont tous des liens uqload, tu peux le mettre dans l'entête et ne conserver que le nom de la page dans le lien du film.
ex : 
**CAT;TITLE;TMDB;GENRES;URLS=https://uqload.co/**

Ce pastebin fonctionne : 
https://pastebin.com/uZLv69Wy

Il y a également un autre petit souci visuel, le code du pastebin va apparaitre entre crochet derriere le titre 😅

**Comment by sizanic** [comment]
> Je ne comprends pas, la source pastebin ne fonctionne qu'avec les liens premium uptobox 🤔

non, pas pour des liens sur d'autres hébergeurs.
Rappeles-toi que tu avais essayé de créer un paste avec seulement des liens gratuits 😉

**Comment by alKODIque** [comment]
Haaa oui, c'est bien vrai...
Je me souviens, ça ne vallait tellement pas la peine, puisque les liens gratuits étaient éphémères en plus d'être de mauvaise qualité

**Comment by amidevous** [comment]
ok je vois faudrait juste mettre à jour ce que tu dit la sur la doc

donc si je comprend bien pour les genre même si ont met que un seul

faux toujours mettre entre crochet je pensais que c'étais que quand ont en mettez plusieurs

surtout que sa fonctionner comme sa avec un seul

j'imagine que c'est parreil pour les catégorie javais mis par ce que les catégorie ne marcher pas

et pour uqload si je les choisie c'est pour une raison précise

premièrement uptobox et payant et ceux même pour les utilisateurs

si moi je dois payer pour le stockage sa ne me dérange pas 

mais il faux que le stockage soit illimité sans aucune suppression de fichiers

et que sa soit gratuit pour les utilisateurs ce qui n'est pas le cas d'uptobox

pour les utilisateur c'est payant et des qui considéré qu'on a trop de fichiers a leur gout

ils les effaces sans avoir vraiment de raison valable sans alerte de d'abus de copyright ni rien de tous sa

deuxièmement c'est du ddl et non du streaming donc certain fichier non encoder

pour le streaming ne passe pas toujours très bien ou ont un navigation difficile

uqload ne fond pas sa il limite la taille maximum de chaques comptes a 20to soit

mais ils n'efface jamais les fichiers sans avoir reçus d'abus dessus

et encore j'ai même l'impression qui les ignore y a qua voir leur lien marche

quand d'autres hébergeur comme vidoza, mystream ou autres ont supprimer les même lien pour abus

et désoler si je t'es presser mais la raison et simple c'est que quand vous faites des modif

sur android tv ont doit toujours attendre 1 ou 2 semaine(s) que sa soit publier sur la version stable

pour avoir la mise à jour car sur c'est appareil les seul gestionnaire de fichier disponible

ne permettent pas d'accéder au fichier système (fichier cacher) 

ce qui fait que tu ne peux pas modifier manuellement un fichier et ta pas non plus accès au log

vu que le dossier .kodi et un dossier système cacher

sur android tu a des gestionnaires de fichiers qui permettent d'accéder a ce dossier

mais pas sur android tv sur android tv seul certaines applications sont disponible

uniquement les applications qui peuvent être gérer de la télécommande

alKODIque de mauvaise qualité tu dit dans ce cas

essayer cette hébergeur uqload utilise du hd 720  et non du sd comme le font les autres dons tu parle

alors après oui y a pas de 1080p mais a quoi sa sert le 1080p a part utiliser de la bp inutilement

suffit juste de pas avoir un écran trop grand pour regarder convenablement du 720p

un écran 80 cm c'est largement suffisant pur une utilisation familiale ta pas besoin de plus

avec un telle écran si tu l’accroche en hauteur tu peux regarder avec une dizaine de personnes dans un bon salon

si ne ce font pas bloquer ou fermer comme openload ils font très rapidement devenir

le meilleurs hébergeurs de streaming vu comment ils sont partie

en tous cas un grand merci a toi sizanic je vais regarder a tous sa et essayer de faire mon fichier au plus vite

pour que tous le monde puisse en profiter

**Comment by sizanic** [comment]
Des erreurs dans ce que tu dis.
Je reviendrai dessus ce soir.
