### ISSUE TITLE
Uptobox.live

### ISSUE THREAD

**Issue by youcam-sat** [Kodi-vStream/venom-xbmc-addons#4027]
Uptobox.live est de retour.... ya t il un update pour le faire fonctionner

**Comment by sizanic** [comment]
Voilà c'est mieux de poser la question ici que dans d'autres sujets parallèles.
Ça ne nous fera pas répondre plus vite de poser 3 fois la question.
Si tu pouvais aller retirer tes autres messages....

**Comment by youcam-sat** [comment]
Ah dsl j po fait attention  .... c bn j supprimé  le commentaire....
Ppir le sujet .... le site a fait son réouverture ya 2 jours seulement  avec des nouveautés .... c poir cela j fait la publication ..... et dsl encor une fois

**Comment by Jeanaimarre** [comment]
On a hâte... :)

**Comment by sizanic** [comment]
Trop tard 😆

**Comment by Jeanaimarre** [comment]
> Trop tard 😆

Pourquoi trop tard ?
Vs avez sorti un update entre temps !? :)

**Comment by sizanic** [comment]
trop tard pour qu'on s'y mette, y'a plus de site 😄

**Comment by sizanic** [comment]
Le site n'est plus disponible ;(

**Comment by gui78120** [comment]
Uptobox.live de nouveau en ligne mais seulement en lecture seule

**Comment by sizanic** [comment]
en lecture seule n'est pas genant pour ce que nous en faisons, car c'est justement ce que nous en faisons, de la lecture seule 😄

**Comment by sizanic** [comment]
Pour l'instant, je n'y ai pas trouvé "the mother", ni "Super Mario", mais j'y trouve surtout beaucoup de liens morts 😆 

Donc attendons de voir si ça évolue mieux ...

**Comment by ketingye** [comment]
> Le site n'est plus disponible ;(

Maintenant disponible

**Comment by Jeanaimarre** [comment]
Possible de réintégrer la souce

**Comment by TmpName** [comment]
Mais il marche ce site ?
J'ai fais des essais, deja ca retourne de vielle adresses bloquée en france sans changement de dns, donc je change par .eu, et je tombe que sur des liens morts ...

**Comment by alKODIque** [comment]
@TmpName 
Déjà, avant sa fermeture, ce site était un nid a liens morts...
Maintenant qu'il est accessible a nouveau, ça semble encore pire!

**Comment by TmpName** [comment]
Ok, ca me rsssure ^^ ca vient pas de moi

**Comment by gui78120** [comment]
Uptobox.live devient Uptobox.mov. 
Ça y est, le site n'est plus en lecture seule

**Comment by Uptobox-Mov** [comment]
Bonjour à tous,

Je vous remercie pour vos retours et nous avons pris en considération l'ensemble de vos remarques.
Nous avons effectué une passe sur les fichiers ayant une note négative pour supprimer l'ensemble des liens morts, nous avons ajouté un système qui détecte si un lien est mort lorsque vous glissez votre curseur sur le lien. 

Nous transformons aussi maintenant par défaut les liens pour avoir seulement des uptobox.eu.

Nous pouvons si vous le souhaitez crée une API avec une sortie en json afin d'effectuer les recherches directement dans notre base de données pour pouvoir l'intégrer plus facilement à votre addon.

Pour information, nous n'avons rien à voir avec les personnes ayant mis en ligne la première version de "Uptobox.live", nous avons simplement remis en ligne cette vraie mine d'or.

**Comment by sizanic** [comment]
Bonjour @Uptobox-Mov ,

Nous serions en effet très intéressé par une API.

Allez-vous la rendre publique, ou préférez-vous que nous la travaillons en privé ?

**Comment by Uptobox-Mov** [comment]
> Bonjour @Uptobox-Mov ,
> 
> Nous serions en effet très intéressé par une API.
> 
> Allez-vous la rendre publique, ou préférez-vous que nous la travaillons en privé ?

Pas de souci pour que cela soit disponible publiquement.
https://api.uptobox.mov/?search=<title>&sort=title&order=desc

Options pour le sort:
- title
- size
- like_count

Options pour l'order : 
- asc
- desc

Pour information, nous sommes joignable aussi via uptobox.su pour le site et l'API.

**Comment by sousouille** [comment]
Hello,

On a des news sur l'implémentation de l'API ainsi que du dev coté vStream ?

**Comment by sizanic** [comment]
C'est prévu, sans doute courant juillet.

**Comment by sousouille** [comment]
cool merci pour les news !

**Comment by sizanic** [comment]
@sousouille 
La version 6.2 sortie la semaine dernière intègre cette source.

**Comment by sizanic** [comment]
Bonjour @Uptobox-Mov 

Nous avons intégré l'API mais nous sommes constamment confronté au message d'erreur :  "Too many request, please try again.".

Une idée, une piste ?

**Comment by sousouille** [comment]
> @sousouille La version 6.2 sortie la semaine dernière intègre cette source.

Yes merci j'avais vu 👍

Pour l'histoire du throttling, je ne sais pas comment c'est géré coté API : passe-t-on par une gateway (apigee, wso2,...) ? Dans ce cas là, il faudrait augmenter le seuil pour le clientid que l'app utilise.

**Comment by sizanic** [comment]
je n'ai aucune idée de quoi tu parles 😄

**Comment by sizanic** [comment]
obsolete
