### ISSUE TITLE
Vos choix pour les DNS

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#4031]
Hello, alors je suis peut etre hors sujet mais comme ca concerne directement Vstream ....
Alors je n'utilise pas DNSPython car je change (enfin changeait) les DNS avec cette application https://www.trishtech.com/public-dns-server-tool/

Et jusqu'a depuis peu, pas de soucis, mais dernierement, j'ai de gros soucis sur Vstream avec des sites inaccessibles, donc j'ai voulu tester avec par exemple VFilms `https://wwvv.vfilms.live/`
Et bien ce site fonctionne sur une machine sous Win 10 avec un reseau bien configuré, mais pas du tout sur kodi qui tourne sur Win 7. J'ai voulu tester sur Firefox, impossible d'acceder au site, meme en testant tout les DNS proposé par l'application (Je fais Ctrl+F5 entre chaque changement, ou meme apres avoir relancé Firefox).

Quid de votre coté ? avec ce site, choix de DNS, autre solution ? idée du probleme ?

**Comment by sizanic** [comment]
Perso, j'ai accès au site avec le DNS google.

> ... mais pas du tout sur kodi qui tourne sur Win 7.
idée du probleme ?


Oui, ton problème est d'utiliser Win 7.

**Comment by TmpName** [comment]
>Oui, ton problème est d'utiliser Win 7.

Ben apparement, c'est ce qui est le plus posible, mais pourquoi ca marchait avant.
Je testerais bien dnspython, mais je trouve ca lourd.
Je vais faire quelques recherches ce WE.

**Comment by sizanic** [comment]
peut-être un soucis entre DNS ipv4 et ipv6.
Est-ce que win7 support l'ipV6 ?

**Comment by razorex** [comment]
Alors pour mon expérience j'avais modifié mes dns sous W7, ipv4 et ipv6, et sa fonctionnais.
J'avais déjà remonté l'info sur des pertes avec les montés de version kodi depuis la version 19.4
perso je n'utilise pas dns python avant, rendu "obligatoire" il me semble par kodi.
Pour moi c'est avec les montées de version kodi que l'on a "perdu" des sources.

**Comment by TmpName** [comment]
@razorex Ha oui, je viens de passer sous kodi 19 (une des raisons qui me motive pas pour dnspython, pas de version officielle)

Ca pourrait venir de ca, mais ca deconne aussi sous navigateur, peut etre un probleme de cache.
Mais je fais des tests ce week end.

**Comment by sizanic** [comment]
> je viens de passer sous kodi 19 (une des raisons qui me motive pas pour dnspython, pas de version officielle)

La version disponible sur le github de vStream est compatible kodi 19 et kodi 20 🤔 
Ce n'est pas une version officielle mais elle est maintenue et s'installe facilement depuis le gestionnaire de  fichiers de kodi.

**Comment by TmpName** [comment]
Bon ben, alors je sais pas si je passe pour un bouffon du coup, mais c'etait bien l'ipv6.
Je viens de la desactiver completement, et ca remarche sur kodi et sur navigateur.

A mon avis @razorex a mit le doigt sur le soucis, les dernieres version de kodi doivent forcer l ipv6 (logique, on me dira)
