### ISSUE TITLE
VAVOO DANS VSTREAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#4033]
Bonjour,

Vavoo excite sur Kodi et j'aimerais bien intégrer les Chaines dans le m3u 
de vStream mais je sais pas trop comment faire. Pouvez-vous m'aider ?

Cordialement,
Ludo Potte

**Comment by sizanic** [comment]
Bonjour,
Vavoo est une extension à part entiere qui sais lire ses propres chaines au format m3u.
Pourquoi ne pas utiliser vavoo directement ?

Quelle serait la valeure ajoutée que vStream propose les liens m3u venant d'une autre extension ?

Si tu arrives à avoir les m3u des chaines de vavoo, il te suffit de les lire directement avec Kodi, tu n'as pas besoin de vStream.

vStream n'est pas un lecteur vidéo. Que ce soit pour des fichiers .avi ou des .m3u.
vStream ne fait que proposer des liens, c'est Kodi le lecteur vidéo.

Si tu as les liens m3u, il faut les lire avec une extension iptv pour Kodi.
Et justement, kodi propose une extension officielle dans son depot : "IPTV Simple Client".

Utilises cette extension pour lire tes liens m3u.

**Comment by ludopotte** [comment]
Oui bien sur @sizanic mais pour la Communauté, ca serais mieux d'avoir toutes les Chaines directement dans la "Rubrique TNT"
de vStream (je suis sur que je suis pas le seul à penser ca).

**Comment by TmpName** [comment]
Ben perso j'ai demandé a amazon prime d'afficher les memes series que netflix en plus des leurs ils n'ont pas voulu non plus.

Sinon serieusement je dirais pas mieux que @sizanic sinon rajouter que la team de Vavoo ne bosse pas pour Vstream, et qu'il reste tres peu de developpeurs sur Vstream et je doute qu'ils aient le temps de bosser pour refaire quelque chose qui existe deja ailleurs.

**Comment by ludopotte** [comment]
Peut etre oui mais c'est pas sur l'Addon officiel de la Team Vavoo que j'ai trouver, c'est plutôt sur l'Addon de @michaz1988
