### ISSUE TITLE
Options en double dans le menu contextuel

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#4038]
Je viens de remarquer un autre petit bug dans le menu contextuel lorse activé sur une pochette présente dans un widget..

Quelques options sont inscrites en double:

https://user-images.githubusercontent.com/49578130/233222737-4a9ef36e-7b18-48ab-b5ad-0f7964a0c906.mp4

- On peut voir que les premières options sont celles de vStream (mais avec la couleur que j'ai sélectionné dans les paramètres - Jaune fluo)
- Un double de quelques-unes des mêmes options de vStream sont également présentes en fin de liste dans mon menu contextuel (cette fois, avec la couleur par défaut établie par vStream - saumon)

**Comment by doctornono** [comment]
@alKODIque Je confirme il y a un doublon des options Information, Marque-page et Rechercher dans le menu contextuel sur les widgets
![image](https://user-images.githubusercontent.com/44597041/233752754-4b635d9a-f54c-481d-a1ed-c4df1839024e.png)

En tout cas, merci de m'avoir fait découvrir la vue Information de vStream! Très réussi.

**Comment by sizanic** [comment]
> Je viens de remarquer un autre petit bug dans le menu contextuel activé sur une pochette présente dans un widget..
Quelques options sont inscrites en double.

Ce n'est pas un bug mais un effet indésirable suite aux dernières évolutions de ton skin.

En effet, pour tous les skins jusqu'à maintenant, les widgets n'étaient pas considérés comme étant des éléments de l'addon associé, mais étaient des éléments distincts gérés par l'habillage.

Par conséquent, ces éléments ne proposaient pas le menu normalement prévu.

La team vStream avait donc développé un menu spécial pour ces éléments lorsqu'ils sont utilisés en tant que widget.
Un menu dédié avec les actions : Informations/Marque-pages/Rechercher.


Mais il semble que maintenant l'habillage gère ces widgets de façon plus naturel, et les actions par défaut sont proposées.
-> Le menu spécial "widget" est maintenant inutile.

Le souci est qu'il va être difficile de détecter si ce menu spécial est nécessaire ou pas.
Si on l'enlève, la plupart des autres habillages ne proposeront plus d'actions pour les widgets.

**Comment by alKODIque** [comment]
Au fond ce n'est pas dérangeant dutout
Si ce doit faire doublon pour certains afin d'être présent pour d'autres: ya pas de mal 👍

Bisarre cependant que pour ''la 2e fois'' ou les options sont présentes, il y ait des options en moins 🤔

**Comment by sizanic** [comment]
> Bizarre cependant que pour ''la 2e fois'' ou les options sont présentes, il y ait des options en moins

non, ce n'est pas bizarre, c'est le fonctionnement qui a été mis en place.
Pour que des menus soient présents pour les widgets, il fallait un développement sépcifique, et dans ce développement nous n'avons mis en place que ces 3 actions (et pas les autres).
