### ISSUE TITLE
Autre question captcha

### ISSUE THREAD

**Issue by codegittest** [Kodi-vStream/venom-xbmc-addons#4040]
Bonjour,

Désolé, surement déjà répondu (pas acces a discord). Parfois, ZT  demande un captcha mais les caracteres ne sont pas visible.

Est-ce que cela pourrait etre causé par vstream ou c’est le flaresolver pas assez a jour pour certaine requete ?

note:
J’ai essayé la version Beta au cas ou .. mais sans résultat. Il pourrait être intéressant de pouvoir tester la version beta ET standard dispo. dans le même repo (ou dans un autre repo) sans avoir a editer le nom dans le zip de la beta pour créer un doublon sans écraser la version standard.

Merci si vous avez des info !

coreelec, matrix 19.5

**Comment by codegittest** [comment]
En essayant sur le site avec un navigateur, c’est peut-etre le comportement (captcha demandé) lorsque le lien est inacessible ? Genre de mauvaise re-direction ?

**Comment by alKODIque** [comment]
Mais ZT n'est plus dispo dans vStream, non ??
À moins que tu fasses référence à wawacity ?

**Comment by codegittest** [comment]
selection par source

**Comment by alKODIque** [comment]
Mais a moins que je ne comprenne rien à rien a ce que tu veux dire: Justement, la source ZT n'est plus disponible dans vStream depuis un moment.

**Comment by codegittest** [comment]
Je sais pas, j’ai peut-etre un vieux fichier source qui s’est pas mis a jour…

**Comment by alKODIque** [comment]
En fait, si ce n'est plus dans vStream: c'est parce que le site lui-même n'existe plus...

Le site du même nom que tu retrouves sur internet est en fait un clone du site wawacity... (comme la majorité des sites qui proposent du DDL  d'ailleurs)  sur wawa, il y avait bien un captcha mais pour les autres sources, c'était plutôt cloudflare le souci.

- Et les source sont maintenant mis à jour automatiquement dans vStream depuis qu'elles sont gérées avec un fichier json
- Regarde si tu possèdes bien la dernière version stable de vStream soit la v2.4.3 👍

**Comment by codegittest** [comment]
Oups…c’est plutot F-T

**Comment by sizanic** [comment]
Pour des sources avec captcha, j'ai déjà remarqué que lorsque les images ne s'affichent pas, cela dépend du skin.

**Comment by codegittest** [comment]
Merci beaucoup pour la suggestion ! Je vais faire des essais, je ne pensais pas que le skin pouvait avoir autant d’impact…

Bonne soirée !

**Comment by codegittest** [comment]
Juste pour info, parfois avec un debrid actif, j’ai un message d’erreur disant que ca prend un compte premium mais la réalité est que le lien n’existe plus (confirmé en passant par un navigateur).

Autres: il pourrait être intéressant de donner un autre vie a  un cpu s805(armbian) pour rouler flaresolve mais pas certain si os est trop vieux pour prolarr ?
https://i12bretro.github.io/tutorials/0361.html

merci !
