### ISSUE TITLE
Info sur médias avec la Beta actuelle

### ISSUE THREAD

**Issue by alKODIque** [Kodi-vStream/venom-xbmc-addons#4041]
Bonjour 👋
Seulement pour vous informer qu'avec la beta actuelle de vStream, les notations ainsi que les clearlogo (avec skin compatibles) n'apparaissent plus pour les films et séries.

(clearlogos sur widgets)

En réinstallant la dernière version stable, ça revient.

Différences beta VS Stable:

![beta1](https://user-images.githubusercontent.com/49578130/233685228-9f293e4a-4cd4-4d82-9e68-b3cabf706cac.png)
![stable 1](https://user-images.githubusercontent.com/49578130/233685265-68e5b9f5-3c12-481b-98f6-d9f6906b29f7.png)

![beta2](https://user-images.githubusercontent.com/49578130/233685357-78f7e480-43d7-4f8d-8d86-7a0b3df712b3.png)
![stable2](https://user-images.githubusercontent.com/49578130/233685377-a0f96d34-5d0d-4fdb-ae14-493064b92557.png)

**Comment by sizanic** [comment]
alors là je ne comprends pas car j'ai la Beta à jour et j'ai bien les notes.
windows / Kodi 20 / AH2

![image](https://user-images.githubusercontent.com/47307622/233742155-8af14f2e-ba95-4df0-969b-cae8cae13e33.png)

**Comment by alKODIque** [comment]
Ayayaye..
Trop bizarre..
Car j'ai testé a plus d'une reprise afin de m'assurer que j'avais vu juste. - Mais je suis sous Android et pas sous Windows.  Je n'ai pas testé sous windows
- As-tu aussi la version à jour du skin / TMDbH ?

**Comment by alKODIque** [comment]
Je viens de re-tester et toujours pareil..

Je te laisse mes logs (vStream Beta vs vStream stable) au cas ou tu puisses voir quelque chose.. (?)

[vstream-beta-kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/11299809/vstream-beta-kodi.log)
[vstream-stable-kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/11299810/vstream-stable-kodi.log)

**Comment by sizanic** [comment]
Pour les notations, en mettant l'option des informations sur "Plot" et non " Full" dans AH2 alors elles apparaissent en bas du poster.

Le souci serrait donc du côté de l'affichage par le skin (depuis la derniere version), et non pas de Vstream.

**Comment by alKODIque** [comment]
Non: c'est le contraire:
option ''Plot'' est pour limiter l'information au résumé seulement
option ''Full'' offre d'inscrire toute l'information (dont les notations)
-> il s'agit du comportement attendu de ces options.

**Comment by alKODIque** [comment]
J'ai fait d'autres tests...
**Est-il possible qu'il y ait un genre de cache persistant dans vstream.db ??**

Je demande parce que voici ce que j'ai testé:

**Premier test:**
Installation de la beta sans supprimer aucun cache
- toutes les notations ont disparu dans vStream (widgets et dans les menus de l'addon)
- notations toujours présentes depuis TMDbH 
- plus de clearlogos sur les widgets (et notations manquantes)
- Redémarrage Kodi (sans supprimer de cache): Toujours même résultat

**Deuxième test:**
Toujours sous la beta vStream, je supprime le cache manuellement
- cache Kodi (dossier temps)
- vignettes et textures13.db
- cache pastebin
- cache vstream (video_cache.db)
- au démarrage de Kodi: Rien n'a changé: absense de clearlogo et notations comme avant.

**Troisième test:**
Je fait pareil comme mon 2e test mais en plus, je supprime ma base vStream.db..
Au démarrage Kodi: Tadam!! Notations et clearlogos font leur apparition..
Mais ce qui est étrange, ce sont ces nouveaux fichiers qui ont fait leur apparitions dans mon dossier userdata de vStream (j'avais jamais eu avant) - voir image jointe.

Et de la vient ma question posée au début de ce post.... Franchement, je n'y comprends rien 🤯
(PS: J'ai accès en FTP a ma box.. donc l'arbo sur l'image ci-bas, bien que prise sous windows est en fait l'arbo de ma box)

![bases vstream](https://user-images.githubusercontent.com/49578130/233801173-0f1ca526-33ce-491c-9e33-5a1727193f29.jpg)

**Comment by sizanic** [comment]
Le souci vient du développement de la nouvelle fonctionnalité "Historique de visionnage".

Cette fonctionnalité n'est pas encore complétement aboutie, des corrections restent à faire, telles que signalé ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4037#issuecomment-1513802925

**Comment by TmpName** [comment]
Lol, en tout cas tes rapports de bugs sont superbes, le temps que tu dois mettre pour faire ca.
Autant certains font juste un post "ca marche pas", autant toi on pourrait faire une page web juste avec la description du bug ^^.

**Comment by alKODIque** [comment]
loll
C'est parce que le diable se cache dans les détails 😝

**Comment by sizanic** [comment]
A vérifier avec la version 2.5.0 de vStream.
Le souci devrait être corrigé maintenant.
