### ISSUE TITLE
Script pour activer/desactiver debrideur

### ISSUE THREAD

**Issue by codegittest** [Kodi-vStream/venom-xbmc-addons#4042]
**Votre demande de fonctionnalité est-elle liée à un problème? 

Dernièrement, j’ai constaté que le debrideur ne sert que tres rarement. Vstream est bien fait car il permet de permuter en mode normal lorsque la source n’est pas supporté par le débrideur. Le seul petit désavantage est qu’il est écrit le nom du débrideur sur tout les liens, il est alors difficile de privilégier une source peut-etre plus fiable qu’une autre.

**Décrivez la solution que vous souhaitez**

J’avais pensé créer 2 script, que je pourrait placer en favori (exemple: active-debrideur.sh ou désactive-debrideur.sh) pour éditer la config. Vstream dans le moins de « clic possible ». 

Bravo et merci a tous pour votre support !

**Comment by TmpName** [comment]
Alors c'est plutot vieux, mais tu aurais pas une capture de 

> ’il est écrit le nom du débrideur sur tout les liens

La je pense que je peux ta rajouter le nom du host dans l'affichage.

**Comment by codegittest** [comment]
Bonjour,
Je constate que c’est pas sur tout les host mais parmis ceux que j’ai vérifié et qui affiche le nom du débrideur partout, il y a:
Cinemay, hds-fm, illimitestreaming, k-streaming, vfilm,wiflix et ???
![3E9648CA-E08E-4075-B23A-9B19EC9C8433](https://user-images.githubusercontent.com/74158267/233790477-dc86d179-fc3f-44ff-9951-367341ad9ce9.jpeg)
![74A7F422-D9B2-4D39-91AE-019F099F724E](https://user-images.githubusercontent.com/74158267/233790479-056f3967-f7a9-48fc-857d-37bc83e94967.jpeg)

voir photo, certain skin, comme Estuary, offre la possibilité, par le menu latéral, d’accéder au paramètres de l’application plus rapidement. 

Merci !

**Comment by sizanic** [comment]
>  Le seul petit désavantage est qu’il est écrit le nom du débrideur sur tout les liens, il est alors difficile de privilégier une source peut-etre plus fiable qu’une autre.


Le solution rapide est que vStream affiche les deux.
Le nom du host d'origine, et une indication que le débrideur est activée.

**Comment by codegittest** [comment]
« Alors c'est plutot vieux… » ???

oui avec un visuel rapide sa serait encore mieux ! Super, Il n’y aurait pas de toggle on/off requis !

**Comment by TmpName** [comment]
>« Alors c'est plutot vieux… » ???

Ben de memoire y avait les 2 auparavant.
Je regarde ca demain mais je pense pouvoir faire afficher "RealDebrid Mixdrop" par exemple au lieu de juste "RealDebrid" si ca t'interesse ?

**Comment by codegittest** [comment]
Oui, ca serait vraiment super !
Espérant que ca soit pas trop compliqué, je pense que la collectivité en profiterais aussi…
Ca marcherait pour tout les fournisseur de débrideurs ?

**Comment by TmpName** [comment]
>Ca marcherait pour tout les fournisseur de débrideurs ?

Oui pour le moment j'ai fais que pour Alldebrid vu que c'est celui que tu as.

Tu peux tester la beta, ca va t'afficher Aldebrid/Mixdrop.com

**Comment by codegittest** [comment]
Bonjour,
Excellent, la source apparait maintenant sur tout les liens, par contre, moi j’ai realdeb (pas alldeb), ce qui explique peut être que le lien premium n’a pas fonctionné mais qu’il fonctionne avec le navigateur ? Je pourrais tester mais je suis pas mal certain que ca passait avant la beta….

Gros merci pour votre effort !

**Comment by sizanic** [comment]
@TmpName 
Je me demande si ce serait pas plus clair de n'afficher que le host sans surcharger avec le nom du debrideur.

**Comment by codegittest** [comment]
C’est vous les master, dans tout les cas, ca sera une belle amélioration ! 
 La version beta soumis que j’ai essayé ne mettait pas le nom du debrideur a coté, seulement 1fichier, mais c’est peut-etre parce qu’il était configuré pour fonctionner avec alldeb ?

J’ai déja vécu une expérience que plus rien ne fonctionnait, c’était a l’époque où que tout passait par le débrideur a partir du moment qu’il était activé, et c’a m’avait pris un délais avant de comprendre que mon débrideur était expiré. Les débrideur supportent beaucoup de host(sans que l’usager ne les connaissent tous), il peut être intéressant de savoir lorsque ce dernier est « sollicité » pour réaliser s’il n’est pas expiré. Autre petit avantage serait de pouvoir mieux évaluer si l’abonnement en vaut la peine…

**Comment by TmpName** [comment]
> par contre, moi j’ai realdeb (pas alldeb)

Ok, j'ai vraiment de la merde dans les yeux en ce moment.
Du coup j'ai fais la modif pour les deux, par contre j'ai pas testé pour alldebrid, mais c'est le meme code.

>Je me demande si ce serait pas plus clair de n'afficher que le host sans surcharger avec le nom du debrideur.

**Comment by sizanic** [comment]
> Je n'ai fais que re-activer du code dormant, c'etait comme ca avant, mais la modif est rapide.

non, ce n'était pas comme ça avant, il y a vraiment un système qui permet d'essayer avec le host d'origine si le debrideur échoue.
Avant, si realDebrid échouait, vStream ne faisait rien.

C'est là, ça fait seulement 6 mois que c'est en place : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/1237f1886298bbf4afceeb5dc253a813df2c8f97

**Comment by codegittest** [comment]
Merci a vous…. pas de presse…
A+

**Comment by TmpName** [comment]
Je parlais de l'affichage, le code est encore visible dans le fichier pour urlResover.
Ca affichait RSLVR-Mixdrop par exemple.

**Comment by sizanic** [comment]
Ok, J'ai eu un doute que tu parlais de l'affichage.

On va réussir à trouver le bon compromis 😄

**Comment by sizanic** [comment]
L'affichage du host d'origine en cas d'utilisation d'un débrideur est maintenant disponible dans la derniere version 2.5.0.
