### ISSUE TITLE
Aucun lien ne marche 

### ISSUE THREAD

**Issue by Sltrlle** [Kodi-vStream/venom-xbmc-addons#4043]
Bonjour j'avais désinstallé kodi il y a quelques mois et depuis 1 semaine je l'ai réinstallé avec vstream mais il y a 2 jours je regardais des épisodes et en voulant passer à l'épisode suivant l'écran chargé mais rester le même et quand je force l'épisode se lance mais l'écran reste noir , j'ai donc attendu quelques jours mais le problème persiste je voudrais bien de l'aide svp.Merci
Vos savoir que je regarde kodi sur un fire stick 
- Version Kodi: [20.1.0]
- Version Vstream: [2.4.3]
Je rajoute aussi que avant j'avais kodi depuis plus de 2ans et ce n'est pas moi qui l'a configuré voilà.

**Comment by sizanic** [comment]
Bonjour,
si le souci n'est présent que pour une seule vidéo, c'est qu'il y a un problème avec cette vidéo.
Et on ne pourra rien y faire, il faut chercher une autre vidéo de cet épisode.

La vidéo est dans quelle source de vStream ?

**Comment by Sltrlle** [comment]
Bonjour, ce n'est pas que cette vidéo toute les vidéos que j'ai essayé de lancer rien ne se lance

**Comment by TmpName** [comment]
Pourrait on avoir quelques logs ?

**Comment by Sltrlle** [comment]
Biensur mais je pourrais savoir c'est quoi pour que je vous le montre? C'est l'url que j'ai utilisé pour avoir vstream ?

**Comment by sizanic** [comment]
non, l'url de vStream, on la connait 😉 

C'est le fichier "kodi.log" qui se trouve dans le dossier d'installation de kodi qu'il nous faut.
Mais sur un FireStick, la manipulation pour récupérer ce fichier n'est pas des plus simple.

A moins d'utiliser l'extension ‘Logfile Uploader’

(un tuto ici au besoin : https://lesalkodiques.com/docs/depannage-kodi/utiliser-laddon-log-file-uploader/ )

**Comment by sizanic** [comment]
il n'y a aucun besoin de urlResolver.

C'est plutot un souci avec le lecteur vidéo.
Essaies de changer le "lecteur par défaut" dans les parametres de vStream.

**Comment by alKODIque** [comment]
Si tu as choisi des liens ''uptobox'', par exemple, et que tu ne possèdes pas d'abonnement premium à ce service, il est possible que tu ais atteint la limite gratuite quotidienne. Mais à ce moment, le lien devrait fonctionner à nouveau dans 24 heures (si tu n'en a pas visionné d'autres entre-temps)

**Comment by Sltrlle** [comment]
Je ne pense pas avoir choisi de privilège mais pleins d autres jours j'ai déjà regarder beaucoup plus d'épisodes que cette fois ci. J'ai essayé de changer le lecteur par défaut mais toujours rien parcontre j'ai reçu un message qui disait espace bientôt saturé alors que je l'ai depuis meme pas 2 semaines est ce normal le problème peut venir de la?

**Comment by Sltrlle** [comment]
Bon je ne sais pas trop c est quoi les logs mes avec log viewer for kodi il y avait pleins d'information en blanc et en défilant il y en avait une en jaune ou c'était marqué warning JSONRPC: Could not parse type

**Comment by TmpName** [comment]
Hello, des news depuis le temps ?

**Comment by sizanic** [comment]
si je reprend les symptôme initiaux : 

> je regardais des épisodes et en voulant passer à l'épisode suivant l'écran chargé mais rester le même

Je comprends ici que la lecture se fait mais l'enchainement est resté sur le même épisode.
Il s'agit d'un souci d'enchainement déjà identifié (surtout pour les japanimes) qui sera traité par ailleurs.

<br>

> il y a 2 jours je regardais des épisodes [.. ]et quand je force l'épisode se lance mais l'écran reste noir , 

Je comprends que la lecture se faisait, puis ne se faisait plus.
Cela ressemble plutôt à un souci avec le l'équipement (cache mémoire, place disque, drivers vidéo, etc..)
Ce n'est pas un souci vStream.

<br>
-> Trop vague et trop aléatoire pour que l'on puisse traiter côté vStream.

**Comment by Sltrlle** [comment]
Bonjour, personnellement le problème c'est réglé je ne sais comment, puisque j'ai arrêté d'aller sur kodi et quelques semaines après ça aller. Je ne sais toujours pas de quelle problème il s'agissait, peut-être c'est un problème d'espace ?

**Comment by sizanic** [comment]
Donc voilà ! 😄
