### ISSUE TITLE
Bandes-annonces

### ISSUE THREAD

**Issue by Papounet58** [Kodi-vStream/venom-xbmc-addons#4045]
Bonjour à tous,

Problème de lecture des bandes-annonces youtube.
Auparavant, les bandes-annonces se lisaient sans nécessiter sa propre clef API Youtube.
Depuis quelques semaines cela ne fonctionne plus sur box Android.
Message du type " cette video ne peut être lue dans cette application"
J'ai tenté de lire les bandes-annonces en utilisant l'addon Invidious et en l'ayant configuré dans Vstream, mais sans succès.
Plus aucune possibilité de régler ce problème.
Que dois-je faire ?

Excellente soirée à vous

**Comment by sizanic** [comment]
bonjour,

Le souci venait de l'addon Youtube.
Une mise à jour est sortie de cet addon youtube, assure-toi de bien l'avoir.

Et concernant Invidous, en effet cela ne fonctionnait plus avec vStream, mais cela a été corrigé (il faut maintenant attendre la mise à jour de vStream).

**Comment by Papounet58** [comment]
Merci

**Comment by alKODIque** [comment]
Par contre, la MAJ de l'addon n'est pas encore disponible dans le dépôt officiel kodi (addon YouTube). Le correctif est seulement présent dans la beta.
Afin d'en profiter immédiatement, il faut donc l'installer depuis: https://github.com/anxdpanic/plugin.video.youtube
Sinon, il faut attendre que le correctif soit disponible depuis l'addon officiel

**Comment by Papounet58** [comment]
Merci pour votre réponse.

**Comment by sizanic** [comment]
En attendant la prochaine version de Youtube, il est possible de lire les bandes annonces dans vStream en installant l'extension INVIDIOUS depuis le dépot officiel de Kodi.

Et configurer cet addon avec une de ces adresses : 
https://api.invidious.io/
