### ISSUE TITLE
Maj Vstream 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#4047]
Bonsoir la team 
J’aimerais savoir 
Pour quand la Maj svp car j ai pas mal de site down et 
Niveau serveur sur ianimes du jour au lendemain j ai qu un seul serveur c est viewsb et il me fais fichier non trouver sur toute les anime 

je suis sur android box en kodi 20.1 et Vstream a jour 2.4.3

Merci pour tout la team

**Comment by sizanic** [comment]
Bonsoir @Mokoman30 ,

Je pense que cette mise à jour arrivera vers la fin du mois.

**Comment by Mokoman30** [comment]
Ok Merci 
Bonne soirée

**Comment by TmpName** [comment]
Pour ianime, j'ai eu le meme probleme, je viens de rajouter un host pour faire apparaitre doodstream, et je suis sur viewsb, j'ai une version fonctionnelle chez moi, mais le code change tout les 2 jours, donc me faut trouver comment generer le code (j'utilise du code en dur)

**Comment by Mokoman30** [comment]
Ah oufff sa rassure 
Ok ba merci les gars 
Bonne soirée 
Et vivement la MAJ
