### ISSUE TITLE
problème lecture lien uptobox

### ISSUE THREAD

**Issue by ato18** [Kodi-vStream/venom-xbmc-addons#4048]
Bonjour,

**Décrivez le bug**
J'ai un problème de lecture de liens uptobox de mon compte premium.
Je peux accéder aux liens situés dans mon compte sans problème mais lors du lancement, j'ai l'erreur fichier introuvable. Les liens sont bien disponibles, je peux les lire depuis un mobile ou tablette avec uptostream via chrome.
J'ai le problème sur les deux appareils où kodi est installé, androidtv et tablette android.

**Votre system**
- OS: [Android et AndroidTV]
- Appareil: [Huawei Matepad, TV TCL]
- Version Kodi: [20.1.0]
- Version Vstream: [2.4.3]

**Nous devons le reproduire**

- Nom du site: wawacity
- Titre du fim/serie: 
- Nom du host (uptobox.): 

**Log**
2023-05-17 11:48:23.682 T:6254    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=The.Last.Kingdom.S02E05.FRENCH.1080p.BrRip.6CH.x265.HEVC.Wawacity.tv.mkv+&sCat=5&sMediaUrl=https%3A%2F%2Fuptobox.com%2Fbgr7qka9i63r&sHosterIdentifier=uptobox&sFileName=The.Last.Kingdom.S02E05.FRENCH.1080p.BrRip.6CH.x265.HEVC.Wawacity.tv.mkv&sTitleWatched=thelastkingdomench1080pbrrip6chx265hevcwawacitytvmkv_S02E05&sTitle=The.Last.Kingdom.S02E05.FRENCH.1080p.BrRip.6CH.x265.HEVC.Wawacity.tv.mkv+&sId=cHosterGui&siteUrl=%26path%3D%2F%2F&sourceName=siteuptobox&sourceFav=showFile&sSeason=02&sEpisode=05]

**Image**

**Plus**

Merci pour votre aide

**Comment by kevinbarbouze** [comment]
Bonjour,
J'ai le même problème DNS modifié uptobox accéssible par une page web, kodi remonte l'erreur fichier introuvable pour les liens uptobox.

**Comment by Phalae84** [comment]
Bonjour, je suis nouveau et je partage le même souci. J'ai un compte uptobox premium, et je stream du contenu sur ma tv Phillips via kodi. Tout fonctionnait parfaitement jusqu'à hier, depuis impossible de lancer du contenu. J'ai toujours le message: erreur:fichier introuvable. J'en appel à votre aide svp. Merci d'avance.

**Comment by sizanic** [comment]
Les fournisseurs d'accès à internet ne permettent plus l'accès direct au site "uptobox.com".

La solution est de changer les parametres DNS de l'équipement utiliser avec Kodi (ou directement dans les parametres réseau de la box de l'opérateur).

Voici des tutos : 
https://lesalkodiques.com/docs/changer-ses-dns/choix-des-dns/

**Comment by ato18** [comment]
J'utilise un pihole configuré en tant que serveur DNS et qui pointe vers les serveurs Google et cloudflare sur l'ensemble de mes équipements. Je peux lire des vidéos uptostream depuis mon mobile.
J'accède bien à mon compte Uptobox donc ça ne doit pas être ça :(

**Comment by Phalae84** [comment]
Idem de mon côté, j'ai changé mes dns hier, j'accède à nouveau à divers site, comme uptobox, j'ai accès à mon compte depuis mon iPhone, iPad,pc, mais plus la télé. Kodi charge bien mon compte uptobox, mais lors de la demande de lecture l'erreur fichier introuvable arrive systématiquement! Pour info j'ai également passé ma smartTV en adressage fiche et change les dns... rien ne fait. :( 
Une autre idée?

**Comment by sizanic** [comment]
Je n'ai pas plus d'idée.
Je viens de refaire le test, j'ai bien accès et la lecture des fichiers de mon compte depuis Windows avec l'utilisation du DNS Google.

**Comment by Phalae84** [comment]
Oui ça fonctionne très bien depuis Windows, mais plus depuis ma telé! J'espère que qqun pourra me venir en aide. Merci en tout cas de tes commentaires

**Comment by sizanic** [comment]
Le probleme devrait être réglé avec la version 2.5.0 de vStream qui vient de sortir.

**Comment by Phalae84** [comment]
Je vais essayer. As tu une source pour l'installer? Merci d'avance

**Comment by Jeanaimarre** [comment]
Hello
Vstream ce n'est PAS uptobox
Le blocage de Uptobox est contournable en modifiant vos DNS ou avec un simple VPN. Que cela soit Windows, Android ou RPI etc... Je vous confirme que cela fonctionne à partir du moment où vous changer vos DNS par 1.1.1.1 ou 8.8.8.8
Uptobox vient d'annoncer un nouveau site Web donc bye bye la censure des opérateurs. Enfin pour ceux qui n'aime pas faire des "manips" (si vstream avec la dernière version ne fait pas gentillement de manip pour faciliter le truc) vous pouvez passer par un débrider de type Uptostream qui masque votre IP et vous donne accès au même contenus.

**Comment by Phalae84** [comment]
En effet, je suis conscient de tout ça. Le blocage d'uptobox, le changement de dns et tout. Malgré ça impossible de lire mon contenu! Tj une erreur: fichier introuvable alors que vstream accède bien à mon compte uptobox (je vois le contenu que j'ajoute), mais après impossible de le lire! Et avant ça fonctionnait parfaitement. Du coup je cherche la solution! (Et tout fonctionne Nikel sur mon pc, tablette, smartphone etc... mais plus tele)

**Comment by ricounet13fr** [comment]
Salut à tous, petite participation j'ai le meme pro depuis 2 jours.
Merci a tous pour l'aide :)
Si ca peut aider, j'ai 2 TV android, accès au compte pretium uptobox( on a bien les fichiers) mais lecture impossible fichier introuvable.
Sur mon Mac installation de Kodi et vstream, compte pretium uptobox et la ca marche.
Le prob est uniquement sur les tv (android ou Firestick)
Peut être une bêtise mais a l'époque un parametrage de urlresolver avait fait des miracles (mais je ne sis pas si ca un lien avec cette erreur)

Je vais essayer la nouvelle version comme proposé par jeanaimarre, mais j'ai réinstallé deja hier kodi sur chaque tv :(

**Comment by Jeanaimarre** [comment]
> En effet, je suis conscient de tout ça. Le blocage d'uptobox, le changement de dns et tout. Malgré ça impossible de lire mon contenu! Tj une erreur: fichier introuvable alors que vstream accède bien à mon compte uptobox (je vois le contenu que j'ajoute), mais après impossible de le lire! Et avant ça fonctionnait parfaitement. Du coup je cherche la solution! (Et tout fonctionne Nikel sur mon pc, tablette, smartphone etc... mais plus tele)

Si ça fonctionne partout sauf sur ta TV c'est donc que le pb est sur ton équipement. Personne ne pourra aller plus loin dans la résolution de ton problème alors que tu es sur un forum Vstream...
Essaye les paramètres de config et test, après si ça marche pas, faudra faire la modif directement depuis ta box opérateur pour les DNS

**Comment by ricounet13fr** [comment]
ok je vais regarder de plus pret la tv, juste 2 questions pour essayer d'éliminer les prob.
Penses tu que les version kodi+vstream d'ordi ou de android TV ont les meme config a l'installation.
Penses tu qu'on puisse avoir un blocage sur un meme réseau, avec la meme version de vstream mais pas sur le meme support, si oui, devons nous configurer les paramètres de Vstream ou paramètre TV ? éventuellement la box mais pareil, est ce que la box peut différencier des accès/demande venant de la tv ou de l'ordi ?
J'espere que j'étais assez explicite, merci a tous pour votre aide
Je continue de chercher en attendant :)

**Comment by Phalae84** [comment]
Je ne trouve pas la source à installer sur Kodi pour vstream 2.5 si qqun peux me la partager afin que je puisse tester svp. 🙏🏼

**Comment by ricounet13fr** [comment]
je viens de trouver ca, je ne sais pas si je peux le partager la comme ca et si ca aide

plugin.video.vstream-2.5.0.zip

https://uptobox.com/kjr04w71mbrs

**Comment by ricounet13fr** [comment]
je l'ai pris la
https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/repo/plugin.video.vstream

**Comment by ricounet13fr** [comment]
Chez moi, meme compte premium
vstream 2.4.3 sur Mac ca marche
vstream 2.4.3 sur android tv ca marche pas, ca rend ouf :)

je vais essayer la 2.5 sur la tv si j'arrive a l'installer

**Comment by ricounet13fr** [comment]
Avec la version vstream 2.5 cela fonctionne sur ma tv

Merci a tous

**Comment by sizanic** [comment]
> je l'ai pris la https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/repo/plugin.video.vstream

Bah oui c'est quand même mieux de le prendre sur le site officiel, à l'endroit même où vous êtes tous en train de discuter en ce moment même 😆

**Comment by sizanic** [comment]
> Je ne trouve pas la source à installer sur Kodi pour vstream 2.5 si qqun peux me la partager afin que je puisse tester svp. 🙏🏼

Il n'y a rien à récupérer, la mise à jour s'installe tout seule sur les équipements

**Comment by sizanic** [comment]
Problème d'accès à uptobox via vStream résolu avec la version 2.5.0

**Comment by Phalae84** [comment]
Au risque d'être embêtant, la mise à jour de vstream ne s'est pas faite alors que l'onglet mise à jour auto est coché. Comment puis je récupérer et installer la nouvelle version? Pouvez vous me partager la source à installer afin de récupérer la version 2.5 svp. Merci d'avance.

**Comment by sizanic** [comment]
Le zip de la derniere version est ici !
Sur ce même site.
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/2.5.0

**Comment by Phalae84** [comment]
Problème résolu avec la V2.5! Merci pour vos commentaires et pour votre aide! 😍👍🏼 génial
