### ISSUE TITLE
Pas un bug : gestion debrid vs version 2.50

### ISSUE THREAD

**Issue by codegittest** [Kodi-vStream/venom-xbmc-addons#4054]
Bonjour,

Gros merci ! J’apprécie beaucoup la dernière mise a jour 2.5.x, pour l’intégration, notamment parmi les autres correctifs, de la suggestion pour préciser l’affichage des liens lorsqu’un débrideur est activé dans le tool de l’addon. 

Maintenant, meme si un usager configure un dédrideur, lors d’une consultation de recherche générale, les résultats afficherons la source des liens et l’usager pourra choisir le lien qu’il préfère au lieu que ce soit affiché le nom de son débrideur sur tout les liens.

Question:
-Comment vérifier si l’addon affiche bien le débrideur parmis une liste ? La seule source que j’ai pu trouver (free telecharge) que le débrideur devait entrer en action m’indique que je dois avoir un compte premium pour la requête alors que si je teste avec un pc, pour ce meme lien, avec un copier coller vers le debrideur, ca fonctionne! Je ne pense pas que cela ait un lien avec la dernière mise a jour mais vous pouvez essayer pour valider.

Merci encore pour votre aide !

**Comment by sciss1968** [comment]
J'ai le même problème. Mes débrideurs n'embarquent plus. Même en créant une nouvelle clé d'accès ou API... 
Il ne me demande plus d'aller valider un code sur le site du débrideur.
J'ai pu contourner ce problème en allant dans les sources et en demandant les "liens" sous mes débrideurs. 
J'ai eu le pop up avec le code PIN à valider. 
Je peux voir une session active dans mes débrideurs...
Mais je ne recois plus aucunes sources dans mes recherches... Sauf Vudeo.... Je ne vois aucun nouveaux liens  dans mes débrideurs. J'ai configuré les boites de plusieurs amis et nous avons tous des problèmes avec nos débrideurs. All dedrid ou Debrid Link.... Y a t'il une procédure spéciale à faire pour faire une réinitialisation quelconque?

**Comment by chasah68** [comment]
Je fais suite pour confirmer le bug lié aux fonctions premium. Malgré toutes mes tentatives (Renouvellement API...) impossible de faine apparaitre les liens débridés par Alldebrid
Cette fonctionnalité est pourtant opérante sur la version 2.43  de Vstream.
ResolveURL étant inopérant avec ces versions de Vstream comment remédier à ce problème ?

**Comment by sizanic** [comment]
Nous avons bien noté vos remarques et allons rapidement apporter une correction.

**Comment by TmpName** [comment]
@sizanic , on a cassé un truc dans la derniere version ?

**Comment by sciss1968** [comment]
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/11658898/kodi.log)
Je ne sais pas ou trouver les logs spécifiques a vStream s'il y en a... Mais voici celui de Kodi...

**Comment by TmpName** [comment]
Ben y a pas l'air d'avoir eu d'erreur critiques ...
Mais normalement maintenant avec la dernière version quand tu arrives sur la pages des "liens hosters", le nom du serveur qui heberge est du type uptostrean/alldebrid ?

**Comment by sciss1968** [comment]
J'ai bien compris cette nouvelle fonctionnalité qui devrait être assez pratique car choisir un des 40 alldebrid ou debrid-link d'une liste n'était pas commode. Personnellement. j'utiliserais simplement des couleurs ou une simple étoile pour dire quel lien est supporté ou non par le débrideur. 

Malheureusement que ce soit avec Alldebrid et ou Debrid-Link la session ne s'établi pas avec le débrideur. 
Si je regarde mes sessions actives sur Debrid-Link il n'y en a aucune pour "vStream". 
Que je change pour n'importe lequel de mes codes (et ce même si j'en ajoute un nouveau) sur Debrid-Link la session ne s'établi pas.. Je ne reçois jamais le pop-up pour saisir le NIP / Autoriser l'appareil sur le débrideur. 

Si je vais sous "Mes contenus - Mes Sources actives" et que je choisis mon débrideur dans la liste. Je vais finalement recevoir un pop-up avec un code pour autoriser mon appareil qui est alors visible dans la liste de périphérique actifs. 
Malheureusement cela n'aide pas plus à établir la connexion avec le débrideur lorsque je retourne sous Vidéos à la demande.

J'ai du monter une 15e de boites CoreElec avec vStream pour des amis et leurs amis... Chacun utilise soit Debrid Link ou Alldebrid comme débrideur mais aucune ne fonctionne depuis la nouvelle version. Je vais tenter de supprimer vStream et le reconfigurer de zéro sur une de mes trois boites.... Mais j'ai peu d'espoir. 

Notez que nous sommes tous du Canada. Donc il est possible que nous tentions des connections sur des serveurs du débrideur localisés dans un autre pays que celui utilisé lors de vos tests.

**Comment by sciss1968** [comment]
Et comme la nouvelle version ne réussi pas à se connecter à mes débrideurs... 
J'alterne entre les deux sites: un seul actif à la fois.
Je n'ai jamais de demande d'activation de PIN/Autorisation d'appareil....
Je n'ai jamais de débrideur listé...

**Comment by sciss1968** [comment]
Toujours pareil après avoir supprimé vStream et l'avoir réinstallé à partir du dépôt 0.6.
Version 2.5.1. Mis un nouveau code vStream... Toujours pas de pop-up... et toujours pas de vStream dans ma liste de résultat.. Et tjrs aucune session active dans vStream ni de nouveaux liens dans mon historique vStream...

**Comment by sciss1968** [comment]
Finalement une de mes trois boites a encore la version 2.4.7. Je me suis dépêché de désactiver les mises à jour automatique. Comme prévu cette boite accède bien au débrideur et on peut la voir dans la liste des périphériques actifs sur le débrideur.
Il y a aussi des liens dans l'historique du débrideur.

**Comment by TmpName** [comment]
> Mais normalement maintenant avec la dernière version quand tu arrives sur la pages des "liens hosters", le nom du serveur qui heberge est du type uptostrean/alldebrid ?

C'est le cas chez toi ?

> Malheureusement que ce soit avec Alldebrid et ou Debrid-Link la session ne s'établi pas avec le débrideur.

Tu utilises quoi comme debrideur ?
Debrid link a un fichier site complet, alldebrid lui ne fait que lire les information que tu as mis dans les setting de Vstream, il regarde si tu es premium et si oui utilise le token rentré.
A aucun moment on gere une histoire de popup pour celui la.

**Comment by sciss1968** [comment]
Résultats du premier test:
Si je vais voir le même épisode d'une série sur mes trois boites.
La boite 2.4.7 avec le "Debrid Link" à "On" m'affiche une liste de 5 liens "Debrid Link"
La boite 2.4.7 avec le "Debrid Link" à "Off" m'affiche une liste de 3 liens: Uqload, Dood, UpToStream 
La boite 2.5.1 "Debrid Link" m'affiche une liste de 3 liens: Uqload, Dood, UpToStream
La boite 2.5.1 "All debrid" m'affiche une liste de 3 liens:   Uqload, Dood, UptoStream

**Comment by TmpName** [comment]
Mais j'ai toujours pas les reponses a mes questions ^^.
Pour infos il FAUT passer par les fichiers sites pour mettre a jour les settings dans Vstream, une fois ca fait les infos peuvent etre cachée, tu peux forcer leur affichage en virant le "hidden"
```

        <setting label="Debrid Link" type="lsep"/>
        <setting type="sep"/>
        <setting id="hoster_debridlink_premium" type="bool" label="30403" default="false"/>
        <setting id="hoster_debridlink_ID" type="text" label="Client ID" default=""/>
        <setting id="hoster_debridlink_token" type="text" label="30328" option="hidden" visible="true" default=""/>
        <setting id="hoster_debridlink_tokenrefresh" type="text" label="Refresh Token" option="hidden" visible="true" default=""/>
```

**Comment by sciss1968** [comment]
J'aimerais bien pouvoir y répondre.
Mais tant que je serai incapable de connecter mes vStream 2.5.1 aux débrideurs... 
Mes réponses ne seront jamais celles que tu attends.

Depuis la mise à jour à 2.5.1 et ou 2.5.0 il est impossible de m'y connecter.
Je peux effacer les configurations et les refaire un millier de fois.. 
Mais je n'ai jamais la pop-up windows avec le code pour l'activation sur le site du débrideur.

Je peux faire sans tracas ces mêmes manipulations sur la version 2.4.3. 
J'ai le pop up et je peux activer mon device sans tracas. 

Je peux essayer une nouvelle installation de vStream sur Kodi PC et voir si en partant de zéro cela fonctionne.
Si cela fonctionne cela signifierait qu'il y a une donnée en cache ou un fichier orphelin qui cause des tracas.

**Comment by sizanic** [comment]
bon, je vais regarder tout ça en détails ...

**Comment by sizanic** [comment]
Bon déjà les comptes premium sont reconnus pas la source Pastebin.
Qui est quand même la source qui propose le plus de liens nécessitant un compte premium.

**Comment by sizanic** [comment]
Voilà, c'est corrigé.

Disponible en Beta.

Je prépare une mise à jour de vStream dans la soirée.
Le bug est assez important pour necessiter une nouvelle version.

**Comment by sizanic** [comment]
La Version 2.5.2 est disponible avec la correction pour utiliser les debrideurs.

**Comment by sciss1968** [comment]
Je confirme que la version 2.5.2 règle le problème. Merci pour la résolution. 
Dès ma première tentative j'ai eu le pop-up et un coup mon appareil autorisé sur le débrideur tout était nickel.

Encore une fois merci :) Ca devrait en calmer quelques uns

**Comment by alKODIque** [comment]
Ça m'intrigue..
Avec quelle(s) source(s) un débrideur est utile dans vStream??
Ya que la source Pastebin qui offre du ''vrai'' premium, digne de ce nom..
Alors je me demande en quoi un abonnement premium a un service de débrideur est utile ailleurs dans vStream?
J'ai beau chercher, je ne trouve pas 🤔

**Comment by codegittest** [comment]
Salut,
Merci beaucoup, tout est parfais, affichage super cool et debrid marche !
C’est certain qu’il n’y en a pas beaucoup de disponible avec le debrideur, c’est ce que j’avais constaté au moment ou je me demandais si ca valait le cout mais c’était difficile à voir du à l’afficheur qui écrivait debrid pas mal sur tout lorsqu’il était activé. Avec « free-t. » y’a quelques lien de qualités qui fonctionnent.

pasbin, je voudrais bien essayer mais la validation avec discord n’a pas de sens , # de tel et plein de renseignement requis pour inscription…😞😤

dans un futur x, ils y aura peut-etre d’autre et/ou plus de host qui fourniront des liens « premium » et, a ce moment,ca va bien affiché et fonctionner.

**Comment by alKODIque** [comment]
Pas obligatoire de passer par Discord tu sais ;)
Tu as aussi accès via lesalkodiques.com
Le guide est ici: https://lesalkodiques.com/Guides/pack-des-alkodiques/

Vraiment, ya que cette source qui vaut la peine de payer un débrideur... Tous les liens sont premium. Et aucun besoin de chercher un lien valide, ils le sont tous. (4k, 1080p, etc)  Pas besoin d'entrer un ''PIN'' a chaque fois que tu veux visionner quelque chose non plus. 
La quasi totalité des utilisateurs pastebin désactivent les autres sources car aucun besoin d'y avoir recours ;)

Tu devrais vraiment aller y jeter un oeil :))

**Comment by codegittest** [comment]
Merci poir le conseil, je vais essayer d’essayer, j’ai un debrid qui ne servait déja pas beaucoup mais encore moins c’est dernieres années !
