### ISSUE TITLE
Plus de suivi Trakt après les récentes MAJ de Vstream

### ISSUE THREAD

**Issue by 12Arthor** [Kodi-vStream/venom-xbmc-addons#4056]
Salut la Team Vstream, déjà un grand bravo pour votre taff de ouf avec cet outil.
Depuis les dernières MAJ Vstream le suivi de Trakt ne marche plus vraiment chez moi. A chaque fin de série ou film j'ai un message d'erreur Vstream en haut qui s'affiche et aussi au démarrage de Kodi je n'ai plus la petite ligne "Autorisation de Trakt XX.XXsec"
Alors j'ai essayé de re autoriser mon compte dans mon lecteur TMDBH mais ça n'a pas marché.

Mon Systeme
- Android
- Xiaomi Mi9
- Version Kodi: [20.1]
- Version Vstream: [2.5.1]

Reproduction du problème
- Nom du site: Pastebin
- Titre du fim/serie: Mission Impossible  / Citadelle / La Reine Cléopâtre
- Nom du host (openload/vidzi/...): Uptobox

Fichier Log en pièce jointe

Screenshot du problème en pièce jointe

Merci d'avance.
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/11596761/kodi.log)
![Screenshot_error_trakt](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/113166860/db6350c4-104e-43d8-8908-9f50a006d059)

**Comment by sizanic** [comment]
Le suivi Trakt est opérationnel depuis.
