### ISSUE TITLE
Voiranime

### ISSUE THREAD

**Issue by sirop2** [Kodi-vStream/venom-xbmc-addons#4057]
**Les episodes ne se lance pas**

- OS: [Ios]
- Appareil: [Ipad 6th gen]
- Version Kodi: [20.0]
- Version Vstream: [2.5.1]

- Nom du site: VoirAnime
- Titre du fim/serie: Tous
- Nom du host (tous): 

C'est le meilleur site pour les anime mais il ne fonctionne pas avec Vstream

**Comment by sizanic** [comment]
Merci de l'information, on va regarder ça.

**Comment by TmpName** [comment]
Tu as des soucis de ton coté ?
Moi win 7,  kodi 20.1

**Comment by sirop2** [comment]
Sur VoirAnime je peux pas choisir le host quand j'appuie sur l'épisode le chargement se lance 2 seconde et puis plus rien.

**Comment by TmpName** [comment]
Tu n'aurais pas des logs ?

**Comment by sirop2** [comment]
Non moi c'est sur la source "VoirAnime" mon problème

**Comment by TmpName** [comment]
Ok autant pour moi, du coup j'ai le meme soucis.
Alors j'ai commencé la correction, mais c'etait quand la derniere fois que tu t es servi de cette source ?
Il y a une protection recaptcha, qui m'a demandé 7/8 essais avant de marcher, puis j'arrive a une liste de hosts ou la plupart ne sont pas geré par Vstream.

**Comment by sirop2** [comment]
Ah oui chez moi pas de captcha juste le lecteur qui ne s'ouvre pas, mais si pas compatible ça doit venir de ça

**Comment by TmpName** [comment]
Ben ca marche mieux avec la derniere version en ligne.
La je suis en train d (essayer) de corriger recaptcha, car il ne marche que pour 2 mode sur 3.
Mais quand ca marche j'arrive sur des lecteurs non geré par Vstream, je peux bien regarder a en rajouter un ou deux, mais si ils ne sont pas supportés c'est qu'il doit y avoir une raison.

**Comment by TmpName** [comment]
Bon ben je suis désolé, mais la j'ai pas mieux.
J'ai mis a jour le fichier site et la lib recaptcha, tout a l'air bon, la requete aussi , mais le site me retourne un "0" au lieu du json.

Je pense que le soucis via de la lib recpatcha, je ne l'ai jamais vu fonctionner de mon coté.

**Comment by Toxine-San** [comment]
Salut, pour ma part je n'arrivais pas du tout à atteindre l'étape reCAPTCHA, en regardant les logs et le structure du site j'ai pu constater un delta entre le search sur l'id ligne 306 du fichier voiranime.py et ce qui se trouvait réellement dans l'html du site : 
id = re.search('<input type="hidden" style="display:none;" name="current_page_id" value="([^"]+)"', sHtmlContent).group(1)
<input type="hidden" name="current_page_id" value="88795">
J'ai simplement retiré le style="display:none;" et ça passe j'arrive enfin au reCAPTCHA et j'ai pu lancer un épisode après 5 captcha ce qui est clairement chiant pour regarder un épisode mais au moins ça se lance.
Je pense que ton "Edit: Ok ça marche, j'ai trouvé" veut dire que tu avais déjà cette info mais dans le doute et comme ce n'est pas publié je préfère poster un petit message.
Dans l'idéal si le fichier voiranime.py peut-être mis à jour sur le repo ce serais top car je n'arrive pas à le trouver sur ma box tv pour le modifier alors que sur mon PC c'était assez facile à trouver en suivant ce wiki : https://kodi-vstream.github.io/docs/folder/

**Comment by TmpName** [comment]
Honnetement je me souviens plus, le code du site peut avoir changé aussi.
Dans tout les cas je viens de corriger le code en fonction de ta remarque.

Merci pour la trouvaille.

**Comment by chrysal** [comment]
Bonjour, 
Je pense que cette issue peut être cloturé.
