### ISSUE TITLE
Outil de recherche: résultats différents

### ISSUE THREAD

**Issue by codegittest** [Kodi-vStream/venom-xbmc-addons#4067]
Bonjour,

J’ai constaté quelque chose qui m’a surpris lors de l’utilisation du menu contextuel de recherche à partir de n’importe quel hoster.
En résumé:
1) on choisit un hosteur au hasard dans la liste source
2) on chosit au hasard une video avec un nom « x ».
3)Exemple: les 3-4 lien hebergé ne fontionne pas, on veut donc rechercher + « global »
4) on retourne sur la video « x » et avec le menu contextuel on chosit « search »
5) Quel sont les attentes ? Je pense que nous devrions obtenir le même résultat de recherche que si la recherche aurait été faite avec le clavier avec l’outil de recherche à la source des menu vstream mais non, généralement les résultat nous amène sur le meme « hosteur» et parfois aucun.

Hypothèse:
- La video « x » trouvé contient des details spécifique sur la qualité audio et video qui n’est pas trouvé sur tout les autres hoster (trop scpécifique). Peut-etre que le nom est trop specifique aussi pour en trouver un semblable, je n’ai pas regardé le code pour savoir comment la recherche est faite.

Idéalement:
Serait-il possible que, lorsque l’on utilise le menu contextuel de recherche, cela revienne à obtenir le meme nombre de proposition de recherche qu’avec vstream d’origine ?

Merci !

**Comment by TmpName** [comment]
Alors je pense que tu as raisons, mais j'ai voulu tester de mon coté et impossible de retrouver ce menu contextuel.
Je suis allé sur une serie au pif, jusqu'au dernier lien, celui de l hebergeur, puis menu contextuel, et je n'ai pas de "recherche"

**Comment by TmpName** [comment]
>La video « x » trouvé contient des details spécifique sur la qualité audio et video

C'est possible si c'est dans le titre, la recherche se base sur le titre de la video

`sCleanTitle = oInputParameterHandler.getValue('sTitle') if oInputParameterHandler.exist('sTitle') else xbmc.getInfoLabel('ListItem.Title')`

Si tu as titre "brut" ca devrait mieux marcher ? Si ce n'est que ca, on peut nettoyer le titre, en virant par exemple tout ce qui est entre crochet ou parentheses ?

**Comment by codegittest** [comment]
Bonjour,
Excellent!
Oui, Si nous pourrions «cleaner» le titre pour garder seulement ce qu’un utilisateur aurait écrit normalement ca serait super et donnerait surement un résultat qui ressemble a celui obtenu avec l’outil de recherche a la base de l’addon (où l’on doit obligatoirement utiliser le clavier).
Désolé, j’ai oublié de mentionner que l’on doit reculer d’un répertoire, celui avec les pochette - avant les liens hosteur) pour avoir acces au menu contextuel avec l’option « recherche », j’imagine que vous aviez devinez….

Autres: Si c’est facile, ca pourrait aussi se mémoriser dans l’historique des recherche comme le fait l’outil principal de recherche de l’addon ?

Pas de presse la dessus, je sais que vous êtes probablement tres occupé et avec du temps limité pour aider.
Merci encore a cous tous, tres apprécié !

**Comment by codegittest** [comment]
Juste pas certain a quel niveau vous pensiez « cleaner » les titres, si c’est caché lors de l’utilisation du menu contextuel c’est parfais. Par contre si les titre sont « cleané » et on ne peu plus voir les details a l’écran ca ne serait pas souhaitable.

**Comment by sizanic** [comment]
Normalement tout ça est déjà en place.

- Il y a un nettoyage avant la recherche par le menu contextuel.
- Et cette recherche est ajoutée à l'historique.


Donne nous un vrai exemple de titre et ça nous servira pour tester et corriger le cas échéant.

**Comment by codegittest** [comment]
Bonjour,
Ok oui pas difficile de trouver de exemples:

recherche « elvis » a partir de l’addon (note: dans mes réglages je n’ai pas sélectionné toute les sources, les résultat peuvent varier)
Selon les host de recherche sélectionné, les résultat trouvé sont nombreux !
33 serie: 2h39
Cinemay_cc
Cinemay
Free Telechargement
French-stream
French-stream-lol
Hds-fm
I anime
Keplix
Pastebin
Vfilm
Wawacity
Wiflix

Maintenant, a partir du menu contextuel, on y va avec 
Wiflix « Elvis (HDLight)(TrueFrench) »:
Result for: Elvis (HDLight)(TrueFrench)
Cinemay
I anime
Pastebin
Wiflix

On y va avec Wiflix « Elvis (French) »:
Meme resultat qu’avec « Elvis (HDLight)(TrueFrench) »:

On y va avec Wawacity « Elvis (HRRIP) - VOST »:
Aucun resultat

on constate qu’il y a pas mal moins de résultat quand on y va a partir du menu contextuel, par contre, par le meme hosteur, meme s’il y a moins de resultat que ceux obtenu par l’addon, on obtient le meme nombre (exemple avec wiflix).

je pourrais sortir des exemple a l’infini, les résultat de recherche ne donne pas la meme chose que si on passe par l’addon.

Merci sizanic pour la question + précise parce que la section de code présenté ne me permettait pas de comprendre si tout était ok.


Note:
Lorsque l’on fait une recherche avec le menu contextuel, le tout se ramasse bien dans l’historique de recherche (mais avec les détails de qualité de la video et du language).

**Comment by sizanic** [comment]
Merci pour ce détail, c'est plus clair.

**Comment by TmpName** [comment]
Ben tu es tombé pile dessus ^^
La recherche se fait sur le titre `Elvis [COLOR lightcoral][HDLight][/COLOR] [COLOR lightcoral](TrueFrench)[/COLOR]`
Et bizarrement ca marche moins bien.

Mais la bonne nouvelle c'est que tout est entre crochet ou parenthes donc un truc du genre 

```
sCleanTitle = re.sub('\[.+?\]|\(.+?\)', '', sCleanTitle)
sCleanTitle = sCleanTitle.replace('  ',' ')
```

devrait suffire.

Bon la deuxieme ligne est optimisable, et ca va pas coriger les caracteres accentués, d'aileurs c'est bizarre qu'on ait pas une fonction toute prete pour ca dans le fichier util.py, ce bout de code  pour nettoyer doit etre partout.

Tu es deja dessus @sizanic ? Ou je peux y aller ?

**Comment by sizanic** [comment]
Salut @TmpName 

J'allais m'y mettre et je vois que tu voulais t'y coller.
Tu as pu avancer ou je peux ?

**Comment by sizanic** [comment]
J'ai apporté la correction. https://github.com/Kodi-vStream/venom-xbmc-addons/commit/865e96ffc3f7fbdd3c3eea981a30aee34a349b60

Il ne faut pas chercher à supprimer les meta-infos, mais plutôt utiliser le "titre propre" qui est déjà disponible.

**Comment by TmpName** [comment]
Ben tu as bien fait ^^.
Car moi je sortais l'artillerie lourde, j'avais pas confiance au "titre propre"

**Comment by codegittest** [comment]
Bonjour et encore gros merci a vous !
J’ai essayé la beta, Ca fonctionne super, la recherche n’est plus restrictive !

Petite note:
Pas de chance pour le 1 ier essaie ((movie - news - wiflix) - Fast X), mon ecran a figé lors du « loading » des résultats, je sais pas pourquoi, cela semble aléatoire, après plusieurs minutes un redémarrage de la boite multi média a été requis. Parfois je peux faire l’action « cancel » et sa prend quand meme beaucoup de temps avant de sortir de ce menu. 
A 1 occasion vstream s’est fermé et l’interface est revenu sur l’écran d’accueil kodi. 
Une fois le résultat obtenu, la mise en cache fonctionne très bien puisque pour une meme requete le résultat est tres rapide.
Peut-etre que vous avez déja vécu un situation similaire ? 
Os- corelelec, s905x, 1Go Ram

**Comment by TmpName** [comment]
Oui ca m'arrive souvent, je veux pas dire que c'est pas notre faute, mais kodi c'est de la merde.
C'est hyper instable, meme en dehors de Vstream, chez moi ca plante 1 fois sur 10 juste au demarrage.

Et en regardant les modif de @sizanic je doute que ca vienne de ca.

Par contre oui, le boutton cancel peut mettre plus de temps, de facon aleatoire, kodi lance une recherche en multithreading, mais si un site bloque, ca bloquera tout. Il peut meme ne pas repondre du tout, si un site bloque completement.

**Comment by codegittest** [comment]
Malgré ces petites imperfections, j’aime bien cette platforme kodi !

Je doutais de mon hardware, 1G de ram c’est pas beaucoup, c’est peut-etre du a une mauvaise utilisation de celle ci? Si cela survient a d’autres alors faudrait peut-etre réussir à mieux cibler si c’est le skin, kodi, le os, le matériel ou l’addon. J’ai confiance en ce linux optimisé comme OS, pour ce qui est de kodi, je trouve un peu désolant qu’il y ait une nouvelle version qui sort a tout les ans, ca laisse peu de temps pour stabiliser le code (même si, de ce que je comprends, ils utilisent tant que possible la meme version de « kernel »).

C’est pas tres grave de rebooter de tant a autre, j’ai aussi déjà eu a désactiver des sources pour éviter un blocage dans la recherche, peut-etre qu’un « time-out » plus court sur chaque source pourrait aider un peu (+ long pour pastbin et variable selon vitesse internet) ?

Ne vous gênez pas si je peut aider avec log ou autres !

**Comment by sizanic** [comment]
> Parfois je peux faire l’action « cancel » et sa prend quand meme beaucoup de temps avant de sortir de ce menu.

En vrai le bouton Cancel est là pour décorer. Il ne sert à rien 😄 

A cause du système mis en place pour rechercher en parallèle sur plusieurs sources en même temps, la recherche ne peut pas être interrompue.
Et comme Kodi ne propose pas de fenêtre de dialogue sans bouton, on utilise celle avec le bouton Cancel, mais il ne fait rien.

Et on se dit qu'un vStream bien paramétré aura moins d'une dizaine de sources d'activées.
Et dans ce cas la recherche globale mettra moins de 20 secondes.
Il n'est pas utile de pouvoir annuler une action qui met moins de 20 secondes.

**Comment by codegittest** [comment]
Merci pour la précision, c’est tres apprécié !

Eyey j’aime bien le terme « déco » !!!

Pourrait t-il y avoir une option pour choisir si l’on désire rechercher en // ou en serie (un a la suite de l’autre) ? Présentement et visuellement, meme si les recherches se font en //, ce n’est pas l’impression que ca donne sur l’interface usagé où l’on voit les host défiler a tour de role…ce qui est bien c’est qu’au moment ou ca bloque, il est facile de noter la source pour la désactiver ensuite.

**Comment by sizanic** [comment]
On ne mettra pas d'option pour revenir sur une mode "en série".
On connaît les performances de ce mode qui est l'ancien mode, et elles sont trop mauvaises.

Il faut bien comprendre que lorsque la liste des sources bloque sur un nom, les autres sources continuent d'être interrogées en parallèle. A la fin du blocage, on verra bien que le compteur de sources avance d'un coup.

Le durée de blocage d'une source est autour de 20/30 secondes.
Si c'est une seule source qui bloque, toutes les autres sources auront eu le temps d'apporter les réponses en 20 secondes (pendant le blocage).
Si le bouton "Annuler" fonctionnait, cela ferait en sorte de ne pas continuer sur les sources suivantes à la fin du blocage ("Annuler" ne permet pas d'annuler un blocage).
Sauf qu'à la fin du blocage, toutes les autres sources ont déjà terminées. Il n'y a plus rien à annuler 😉 


Et si tu as plusieurs sources qui bloquent, il faut plutôt revoir tes choix de sources à activer 😄
