### ISSUE TITLE
👋Menu contextuel (Créer une liste personnalisée)

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#4068]
![143](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/48101775/c5949e06-e1cc-4c2a-84ef-1251aca13d3c)**Bonjour**,
Des développeurs de plugins vidéos comme "**Cumination**" ont intégrés depuis longtemps dans leurs menu contextuel la possibilité  de créé une liste personnalisée (_Create Custom Liste)_ dans la page d'accueil. [👉Repo De Cumination d'accueil.](https://github.com/dobbelina/repository.dobbelina)
![46](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/48101775/92f6c879-d98a-470c-8a6d-fdcc06cec8e6)
![liste personnalisée](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/48101775/b8ae4095-8dec-4136-ae43-260ddc7c3eee)

☝️Ne pouvez vous pas faire cela pour que l'on puisse créé notre propre liste personnalisée pour les films ou séries etc.. (par genre etc..) dans les rebriques "Mes Marques de pages" (Films, Séries/Japanimes,Divers...) ?

👆Car quand il y a beaucoup d'ajouts cela prend du temps après a parcourir chaque pages.

**Merci pour la réponse** ✅

**Comment by TmpName** [comment]
Quelle est la durée des liens ? ^^
Le probleme de Vstream c'est que 1 lien mit en marque page n'a une durée de vie que de quelques mois.
L'utilité de cette fonction c'est de mettre de coté une serie le temps de la finir, pas de se faire un menu personnel.

**Comment by victore447** [comment]
🖐️**Ok** donc on ne peut que faire des ajouts à la médiathèque Local avec vstream.
☝️Et la durée de Vie d'ajout de films vstream (Pastebin) dans la médiathèque Local est de combien de temps alors? Pareil que dans Marques de pages ?

**Comment by sizanic** [comment]
> car quand il y a beaucoup d'ajouts cela prend du temps après a parcourir chaque pages.

Si tu as trop de pages dans tes marques pages, c'est que tu as trop de marques pages 😅

En ajoutant des sous-catégories à tes marques pages, tu continuera à alimenter tes marques-pages sans jamais que ça diminue.
Ça ne va pas t'aider, au contraire 😄

**Comment by sizanic** [comment]
> donc on ne peut que faire des ajouts à la médiathèque Local avec vstream.

Non. Il n'y a pas que les ajouts à la médiathèque, il a aussi les marques-pages 😜
Et les favoris de Kodi.


> Et la durée de Vie d'ajout de films vstream (Pastebin) dans la médiathèque Local est de combien de temps alors? Pareil que dans Marques de pages ?

Non, c'est pire.
Ce sont les liens de la médiathèque qui ne durent que la durée du lien, alors qu'un film en marque-pages va toujours proposer les derniers liens à jour. Ce ne seront pas toujours forcément les mêmes.

**Comment by victore447** [comment]
🖐️👉[alKODIque](https://lesalkodiques.com/groupes/kodi/forum/sujet/creer-sa-mediatheque-locale/#post-95697)  sur "Créer sa médiathèque locale" ✔️

**Comment by alKODIque** [comment]
Pour expliquer un peu la référence que tu donnes @victore447 ,
Il faut comprendre que lorsqu'on utilise la fonction d'ajout à la médiathèque locale de TMDb-Helper, c'est en fait une médiathèque de ''Métadonnées'' uniquement que l'on obtient.
- En ce sens, aucun lien n'est ajouté.  Une fois le NFO trouvé, le player (fichier Pastebin.json) qui récupère les liens associés.
- Ça a l'avantage de ne jamais voir sa ''pseudo-médiathèque'' non fonctionnelle.. Des liens seront toujours trouvés peu imporgte qu'ils ne soient pas les mêmes.
- Autre avantage pour les utilisateurs du skin Estuary, il est possible, grâce à cette méthode, de bien garnir sa fenêtre d'accueils grâce à ces médias, faute de pouvoir ajouter des widgets.

**Comment by victore447** [comment]
🖐️![131](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/48101775/4b2f77cc-2ba7-4dc7-af9d-8cf5ba8a53f0) Bon pour finir de mon côté 
**sizanic** & **TmpName** ,Si mon idée de Créer une liste personnalisée via menu contextuel de Vstream n'est pas fiable ;
C'est compliqué ou pas de le faire de votre côté ? ✔️

**Comment by TmpName** [comment]
Ben il y a les marques pages qui sont propres a Vstream, qui n'existent que pour lui, fabriqués a partir de sa base de donnée, et la la moindre modification demande a tout recoder, y compris rajouter un systeme pour pouvoir creer/modifier ce "menu"

La library par contre est plus "open", c'est une image de ta hierarchie de fichier sur le disque dur, donc la avec un simple editeur de fichier tu fais ce que tu veux.
Le probleme c'est ca a pas mal bougé depuis la derniere fois que j'ai vu ca, et que je suis a la ramasse, je vois que now ca s'appelle plus library mais "Dossier media" et je sais pas du tout comment ca fonctionn en ce moment ^^

**Comment by sizanic** [comment]
> [plugin.library.node.editor](https://github.com/XBMC-Addons/plugin.library.node.editor) permet de créer des dossiers (nœuds) dans la bibliothèque contenant d'autres dossiers ou contenus (pas encore eu le temp de tester).✔️

node.editor est justement une extension pour créer des sous-dossiers.

Ce n'est pas la spécialité de vStream.
Notre priorité est le maintien des sources de streaming, et nous avons déjà du mal à faire cela.

**Comment by sizanic** [comment]
il y a des addons pour cela.
