### ISSUE TITLE
uptobox

### ISSUE THREAD

**Issue by lil78711** [Kodi-vStream/venom-xbmc-addons#4069]
**Décrivez le bug**

**Votre system**
- OS: [Windows, Android]
- Appareil: [nvidia shield, Ultra]
- Version Kodi: [16.17.18]
- Version Vstream: [1.7.0]

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

bonjour je suis sur kodi  avec firestick  je n'arrive plus a acceder a uptobox depuis l'installation du dns python peut etre a casse de uptobox .com qui deviens uptobox.eu  comment faire pour acceder a mes fichier et meme les autres liens uptobox qui marche pas merci

**Comment by sizanic** [comment]
vStream 1.7.0 !! 😲

2 ans de retard 😄

Il faut la version 2.5.3 pour la compatibilité uptobox.eu

Et penses à activer la mise à jour automatique des extensions 😉

**Comment by lil78711** [comment]
c'est fait mais ca change rien c'est le dns python qui cause probleme

**Comment by sizanic** [comment]
Doublon avec #4070
