### ISSUE TITLE
uptobox

### ISSUE THREAD

**Issue by Espinete** [Kodi-vStream/venom-xbmc-addons#4070]
**Votre system**
- OS: [Windows]
- Appareil: []
- Version Kodi: [19.5]
- Version Vstream: [2.5.3]

il ne me laisse pas accéder à mes fichiers uptobox et me donne l'erreur suivante:
addon dnspython missing(uptobox.eu)

**Comment by sizanic** [comment]
Il n'y a plus qu'à installer l'addon DNSpython.
Kodi/extension/installer d'un Zip/ URL de vtsream

**Comment by Espinete** [comment]
Merci beaucoup pour la contribution, en effet la version 1.12.1 est pour Kodi 19.5

ajouter que tout est revenu à la normale, maintenant tout fonctionne parfaitement, merci à tous
