### ISSUE TITLE
Problèmes liens sportifs 

### ISSUE THREAD

**Issue by MCreepee** [Kodi-vStream/venom-xbmc-addons#4071]
**Décrivez le bug**
Bonjour !
Je me permet de venir vers vous puisque lorsque je me sers de vstream via kodi sur mon android tv je recontre un soucis avec la majorité des flux sportif. 
Par exemple, si je passe par streamonsport pour regarder une chaîne (type bein sport 1) 5liens sont proposés, parmi ceux là seul 2 sont réellement existant (en l’occurrence le lien 3 et 4) et seul le lien 4 marche par ailleurs. 
Les autres liens eux sont vides avec marquer en rouge "no item" 
Par ailleurs, le lien 4 est le seul à marcher mais se coupe tout seul au bout d'environ 1min (souvent par un freeze de l'image et du son)

Ce soucis est applicable à la majorité des flux streamonsport, mais aussi live tv (ex : match ATP tour Berlin de 13h aujourd'hui, seul 1 lien sur les 4 de live tv marchait, ou alors pour le match Uruguay Portugal de handball en U21 aucun des 5 liens ne marchait.)

S'il vous faut d'autres informations n'hésitez pas !

Pour les logs, les obtenir sur la pop est plutôt bordélique, je peux le faire si cela est vraiment nécessaire pour autant. 

**Votre système**
- OS: Android
- Appareil: Freebox PoP (Android TV)
- Version Kodi: Kodi v20.1 (Nexus)
- Version Vstream: 2.5.3

**Nous devons le reproduire**

- Nom du site:  Streamonsport
- Titre du fim/serie: N'importe quel flux (type bein sport 1)

**Comment by MCreepee** [comment]
Pour information mon problème semble similaire à celui décrit ici (https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3422) mais le post n'est pas très explicite quant aux potentiels soucis et solutions

**Comment by sizanic** [comment]
Nous faisons ce que nous pouvons pour maintenir des liens fonctionnels....
