### ISSUE TITLE
🖐️darkino (Tirexo)

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#4072]
![143](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/48101775/d05191a4-a9ff-4de9-81de-2a24a7c298ab)**Bonjour,**

Cela fait bientot 1 ans que le site [Darkino (Tirexo)](https://www2.darkino.net/fr) est stable et n'a pas été fermé.
**Pourquoi ne pas le réinclure dans Vstream?**
☝️Votre Probleme se situe dans le changement fréquent de l'url?
 ☝️ [Wiflix](https://wiflix.surf/) change également souvent de url mais reste actif dans Vstream.✔️

**Comment by alKODIque** [comment]
Le problème se situe plutôt au niveau de la protection cloudflare ;)

**Comment by victore447** [comment]
🖐️Ok merci.

**Comment by sizanic** [comment]
Oui, le site est trop protégé.
On a pourtant essayé ... en vain.
