### ISSUE TITLE
[DaddyHD] Erreur regex (+ ajout de chaines ?)

### ISSUE THREAD

**Issue by azgaresncf** [Kodi-vStream/venom-xbmc-addons#4073]
Bonjour à toute l'équipe. Je souhaiterais vous signaler que la source DaddyHD ne fonctionne pas, puisque l'architecture du site a un peu changé, les regexs doivent être changés (je vais essayer de faire un fix) ; et je ne sais pas si c'est une bonne idée, mais DaddyHD a récemment ajouté pas mal de chaines, je pense ainsi que certaines chaines pourraient être ajoutés à la liste de ceux disponibles. En vous remerciant encore du travail que vous fournissez chaque jour avec vStream.

(ps: même si c'est hors-sujet, je souhaiterais m'excuser si j'ai été aigri envers certaines personnes à l'époque ; je ne me rendais pas compte des propos que je tenais)

**Comment by azgaresncf** [comment]
Heureusement, à part les regex, j'imagine que rien n'est à changer

**Comment by sizanic** [comment]
Bonjour @azgaresncf 
> les regexs doivent être changés (je vais essayer de faire un fix) 

Vas-tu essayer ? Ce serait vraiment cool 👍🏻 
Un peu d'aide est toujours bienvenu.

Pourquoi cette demande est fermée ?

(ps: pas de souci, c'est pardonné)

**Comment by azgaresncf** [comment]
Puisque je me suis rendu compte qu'il ne s'agissait pas des regex, mais du resolver du m3u8
(du moins de ce que j'ai compris)
j'ai trouvé du code avec daddyhd qui utilise inputstream.helper

**Comment by sizanic** [comment]
ce n'est peut-être pas un souci de regex, il en reste que tu peux laisser la demande ouverte. On aura peut-être une solution.

**Comment by azgaresncf** [comment]
le code que j'avais trouvé pour jouer le stream c'était ça:
import inputstreamhelper
    PROTOCOL = 'hls'
    is_helper = inputstreamhelper.Helper(PROTOCOL)
    if is_helper.check_inputstream():
        play_item = xbmcgui.ListItem(path=stream)
        play_item.setMimeType('application/x-mpegurl')
        play_item.setContentLookup(False)
        if sys.version_info >= (3,0,0):
            play_item.setProperty('inputstream', is_helper.inputstream_addon)
        else:
            play_item.setProperty('inputstreamaddon', is_helper.inputstream_addon)
        play_item.setProperty('inputstream.adaptive.stream_headers', hdr)        
        play_item.setProperty("IsPlayable", "true")
        play_item.setProperty('inputstream.adaptive.manifest_type', PROTOCOL)
    
        xbmcplugin.setResolvedUrl(addon_handle, True, listitem=play_item)

**Comment by sizanic** [comment]
je ne connais pas du tout le code qui concerne InputStream.

Je viens de passer une correction pour la lecture des liens. Juste un souci de Referer.

Maintenant je vais regarder pour l'ajout des chaines.

**Comment by azgaresncf** [comment]
merci pour la correction !!

**Comment by sizanic** [comment]
Très propre ton code pour les chaines 👍🏻 

A la lecture, je ne vois pas le tri pour ne conserver que les chaines francaises.
vStream ne va pas se diversifier vers d'autres voies que le contenu FR.

**Comment by sizanic** [comment]
J'ai essayé les autres chaines FR, et je me rappelle du coup pourquoi on ne les avait pas mises.

Elle freezent et font planter Kodi.

**Comment by azgaresncf** [comment]
Je comprends !
En soi, suffirait juste de seulement inclure les chaînes ayant "France" dans leur nom

**Comment by azgaresncf** [comment]
> J'ai essayé les autres chaines FR, et je me rappelle du coup pourquoi on ne les avait pas mises.
> 
> Elle freezent et font planter Kodi.

C'est bizarre que ça fasse ça 🤔

**Comment by sizanic** [comment]
Je te laisse tester pour confirmer, je les ai mises en commentaire.

**Comment by azgaresncf** [comment]
logs:
(toutes les chaines font pareil)
```
2023-07-09 21:53:59.550 T:10352    info <general>: 	[PLUGIN] vStream: load site daddyhd and call function showLink
2023-07-09 21:54:02.974 T:3996     info <general>: 	[PLUGIN] vStream: load site cHosterGui and call function play
2023-07-09 21:54:02.975 T:3996     info <general>: 	[PLUGIN] vStream: Hoster - play : https://<lien>... /<lien>?id=645
2023-07-09 21:54:03.549 T:3996     info <general>: 	[PLUGIN] vStream: playertype from config: dvdplayer
2023-07-09 21:54:03.550 T:3996     info <general>: 	[PLUGIN] vStream: player initialized
2023-07-09 21:54:03.580 T:3996     info <general>: 	[PLUGIN] vStream: Player use setResolvedUrl() method
2023-07-09 21:54:03.601 T:8436     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=L%27%C3%A9quipe+&sCat=5&sMediaUrl=https%3A%2F%2F<lien>%2Fddh2%2Fpremium645%2Fplaylist.m3u8%7Creferer%3Dhttps%3A%2F%2Fntuplay.xyz%2Fpremiumtv%2Fdaddylivehd.php%3Fid%3D645&sHosterIdentifier=lien_direct&sFileName=L%27%C3%A9quipe&sId=cHosterGui&siteUrl=https%3A%2F%2F<lien>%2F%2Fcast%2Fstream-645.php&sourceName=daddyhd&sourceFav=showLink
2023-07-09 21:54:04.252 T:604      info <general>: Creating InputStream
2023-07-09 21:54:04.664 T:604      info <general>: Creating Demuxer
2023-07-09 21:54:11.339 T:604     error <general>: CVideoPlayer::OpenDemuxStream - Error creating demuxer
2023-07-09 21:54:11.339 T:604      info <general>: CVideoPlayer::OnExit()
2023-07-09 21:54:11.358 T:8436     info <general>: CVideoPlayer::CloseFile()
2023-07-09 21:54:11.358 T:8436     info <general>: VideoPlayer: waiting for threads to exit
2023-07-09 21:54:11.358 T:8436     info <general>: VideoPlayer: finished waiting
2023-07-09 21:54:11.386 T:3996     info <general>: 	[PLUGIN] vStream: player stopped
2023-07-09 21:54:13.501 T:8436  warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 0, because topmost modal dialog closing animation is running
```

**Comment by azgaresncf** [comment]
je confirme que je suis aussi extrêmement confus

**Comment by azgaresncf** [comment]
> le code que j'avais trouvé pour jouer le stream c'était ça: hdr='Referer='+quote(str(url_1))+'&User-Agent='+UA
> 
> ```python
> import inputstreamhelper
>     PROTOCOL = 'hls'
>     is_helper = inputstreamhelper.Helper(PROTOCOL)
>     if is_helper.check_inputstream():
>         play_item = xbmcgui.ListItem(path=stream)
>         play_item.setMimeType('application/x-mpegurl')
>         play_item.setContentLookup(False)
>         if sys.version_info >= (3,0,0):
>             play_item.setProperty('inputstream', is_helper.inputstream_addon)
>         else:
>             play_item.setProperty('inputstreamaddon', is_helper.inputstream_addon)
>         play_item.setProperty('inputstream.adaptive.stream_headers', hdr)        
>         play_item.setProperty("IsPlayable", "true")
>         play_item.setProperty('inputstream.adaptive.manifest_type', PROTOCOL)
>     
>         xbmcplugin.setResolvedUrl(addon_handle, True, listitem=play_item)
> ```

avec ce code toutes les chaines peuvent fonctionner (ça vient d'un certain addon tierce) (the crew)

**Comment by sizanic** [comment]
> avec ce code toutes les chaines peuvent fonctionner

Elles fonctionnent déjà chez moi, sauf qu'elles saccadent énormément et parfois s'arrêtent.

Je testerai quand même ce code...

**Comment by sizanic** [comment]
Tout ce qui pouvait être fait l'a été.
Et pour l'instant le site est down.

**Comment by azgaresncf** [comment]
Le lien du site commence par d.<suite>

**Comment by sizanic** [comment]
Merci, c'est mis à jour 👍🏻

**Comment by azgaresncf** [comment]
**Mise à jour :**
- J'ai refait un script pour récupérer les streams (le pastebin reste le même : 0rkSpDfF).
- Il y aussi un fichier JSON pour les émissions de sport du jour : https://(lien)/schedule/schedule-generated.json

**Comment by azgaresncf** [comment]
> **Mise à jour :**
> - J'ai refait un script pour récupérer les streams (le pastebin reste le même : 0rkSpDfF).
> - Il y aussi un fichier JSON pour les émissions de sport du jour : https://(lien)/schedule/schedule-generated.json

L'avantage du programme est qu'il prend en compte les nouveaux liens (stream, referer, etc...), ce qui évite de devoir modifier manuellement chaque chaine ainsi que le referer.

Ici, pour récupérer les liens, il teste le stream de toute la liste et il fait juste un copier-coller pour chaque stream

**Comment by sizanic** [comment]
> * Il y aussi un fichier JSON pour les émissions de sport du jour : https://(lien)/schedule/schedule-generated.json

On utilise déjà ce fichier json :
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/8335b74491897cc0f5461dd6ce7dbe341613fd6b/plugin.video.vstream/resources/sites/daddyhd.py#L24


Pour le reste de ce que tu proposes, on va regarder, merci beaucoup.

**Comment by azgaresncf** [comment]
> On utilise déjà ce fichier json :
Nickel !

Je vais **essayer** de voir pour faire un fix en Python (je suis vraiment une quiche en programmation, mais je peux tester)
