### ISSUE TITLE
[Feature Request] [UpToBox] Support external subtitles within same directory

### ISSUE THREAD

**Issue by TheRadziu** [Kodi-vStream/venom-xbmc-addons#4074]
I just found your addon and so far I am pleased with it. Although there is one thing it lacks with comparison to Google Drive Addon; Support for external subtitles (txt, ass, srt, ssa etc) within same directory for example:
FolderName
-video.mkv
-video.ass 

Video plays just fine but you cant select video.ass subtitles, only embeded subs. 

Hope it aint much to ask, should be a quick, yet very usable feature to add :)

My current setup is: latest version of the addon from repository + Direct Link Mode

**Comment by sizanic** [comment]
Our addon is for streaming only, so no subtitles are expected, as there is no folder for a streaming link.

In this case, it is possible to use a subtitle addon that downloads subtitles on demand.

![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/47307622/6eab8a3e-d0c1-497c-b0e9-8443a1241e2d)

**Comment by TheRadziu** [comment]
Subtitle files are already 'seen' by addon when it parses directory contents. Its just matter of adding 'when video is played, if there is the same filename with subtitle extension, download it to memory and use as forced subtitle track' 
![Screenshot_20230710-122843](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/7728545/ce735a70-07d6-438b-bae4-edee508f11e1)

Besides, using subtitle addon is out of the question since most of my subtitles are either downloaded from fansub site that has no addon or synced manually by me.

**Comment by sizanic** [comment]
I'll take a look... 👍🏻

**Comment by sizanic** [comment]
Uptobox is out.
