### ISSUE TITLE
Les liens ne fonctionnent pas lors d'une recherche

### ISSUE THREAD

**Issue by ghost** [Kodi-vStream/venom-xbmc-addons#4081]
Lorsque je recherche un film sur tous les sites en même temps, la plupart des liens ne fonctionnent pas ou sont vides. Il faut que je passe de longues minutes à les essayer un par un avant de trouver un bon résultat et la plupart du temps c'est en basse qualité SD. Quelle serait la meilleure méthode pour faire la recherche d'un film en grosse qualité (4K HDR, 1080p ...)

**Votre system**
- OS: [Windows, Android]
- Appareil: [tous]
- Version Kodi: [20]
- Version Vstream: [2.6.1]

**Nous devons le reproduire**

- Nom du site: tous
- Titre du fim/serie: tous

**Comment by TmpName** [comment]
Passer a une offre payante ?
Bonne chance pour trouver du 4k gratuit.

Par contre que tu ais tant de lien mort me fait penser que tu n'as peut etre pas changé les DNS ?

**Comment by sizanic** [comment]
Bonjour @jo-a11y 

Si tu n'as pas beaucoup de résultats, peut-être qu'il te manque des sources qui sont bloquées par ton opérateur internet.

Pour contourner ce blocage, tu dois installer DNSPython que tu trouveras dans notre dépot.

Dans ce tuto sur l'installation de vStream, suis le chapitre [Module DNS python](https://lesalkodiques.wiki/docs/module-dns-python/)

Quand à la qualité, c'est celle fournie par les différents sites, nous n'y pouvons rien.
La source Wiflix propose assez régulièrement de la bonne qualité.

Sinon, la seule source vStream qui te proposera des liens en fullHD et 4K (et au-délà) pour l'ensemble des films et séries, est la source Pastebin.
Et tous les liens y sont toujours fonctionnels.
Il s'agit d'une source premium, exclusive à vStream (elle ne repose pas sur un site, le contenu n'est accessible nulle part ailleurs).

Mais par défaut à l'installation de vStream, cette source est vide.
Pour avoir accès à ce contenu premium, il faut renseigner des codes privés.

L'équipe vStream ne fournit pas de codes.
Pour avoir des codes, tu dois te rapprocher d'une communauté qui fournie des  "codes Pastebin pour vStream".

La communauté "Les alKODIques" fourni un pack de codes complet (codes films, series, japanimes, concerts, spectacles, documentaires).

Tu peux suivre leur tuto pour la configuration de pastebin et pour accéder à leur codes : https://lesalkodiques.com/Guides/pack-des-alkodiques/

Pastebin est la seule source qui te proposera de la qualité jusqu'à 4KHDR+ et "Dolby Vision".


En conclusion, si tu adoptes cette source, tu n'utiliseras plus que celle-ci.

**Comment by sizanic** [comment]
La version 3.1 et les nouvelles sources qu'elle propose donne maintenant une grande variété de liens valides.
