### ISSUE TITLE
[Sport en direct] Temps de lecture limité

### ISSUE THREAD

**Issue by HuitSoixanteQuinze** [Kodi-vStream/venom-xbmc-addons#4082]
Bonjour à tous, 

Tout d'abord je souhaites vous remercier pour tout votre travail ! Vstream est vraiment super et fait partie de mon quotidien. 

Je souhaite remonter un problème avec certains liens de flux en direct. Lorsque le lien affiche la qualité en bas de l'écran et une durée (voir photo ci dessous), le live ne reste affiché que le temps indiqué (ici quand je mets bein sport 1, j'ai bien le live qui s'affiche mais 5 secondes). 

J'utilise souvent la chaîne DaddyHD mais depuis un moment impossible de l'utiliser. J'ai ce problème sur presque tous leurs liens et sur NeymarTV aussi. Pas de soucis avec les liens qui ne comporte pas ces différentes infos en bas. 

Est ce que le lecteur prend en compte cette info et stop le direct au bout de 5 secondes ? 

Peut être est-ce un paramètre de kodi ? 

Merci d'avance. 

**Votre system**
- OS: [Android]
- Appareil: [MiBox4]
- Version Kodi: [20.2]
- Version Vstream: [2.6.1]

**Nous devons le reproduire**
Exemple :
- En direct
- Sports
- Sports (Chaînes) 
- NeymarTV
- bein Sport 1

**Image**
![16900242258386841713193629971634](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/66942760/465c5057-7c5b-43bb-93bf-fa1b6bae1794)

**Plus**

**Comment by sizanic** [comment]
Bonjour,
La technique de streaming pour le direct est d'utiliser plusieurs fichiers de 5 secondes qui s'enchainent.
Il est donc normal de retrouver un fichier de 5 secondes.
Mais il n'est pas normal qu'il n'y est pas l'enchainement sur le suivant.

Par contre, vStream n'est pas le meilleur addon pour ce type de flux streaming en direct.
Il fait ce qu'il peut, et il peut arriver ce genre de souci.

Pour l'instant c'est tout ce que nous pouvons proposer.

**Comment by HuitSoixanteQuinze** [comment]
D'accord merci pour la réponse !
