### ISSUE TITLE
Vstream

### ISSUE THREAD

**Issue by fredseventyfive** [Kodi-vStream/venom-xbmc-addons#4084]
**Décrivez le bug**

La connexion a Uptobox via Vstream pas de fichier (tout bien configuré Compte plus Token. Idem sur une autre Xbox 
Re-install rien y fait (Kodi dernière version plus Vstream) 
**Votre system**
- OS: Windows
- Appareil: Xbox série X
- Version Kodi: 20.2
- Version Vstream: 2.6.1

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

**Comment by ato18** [comment]
Hello,
Même problème que toi, sur ma télé en Android TV, ainsi que ma tablette Huawei matepad10.
Le problème semble identique à l'issue que j'avais créé en mai https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4048#issue-1713546292.

L'accès au compte Uptobox est ok (dns ok) mais la lecture des films est impossible (fichier introuvable)

**Comment by sizanic** [comment]
L'adresse d'Uptobox est bloqué par certains fournisseurs internet.
Il faut changer les parametres DNS de vos carte réseau.

**Comment by ato18** [comment]
> L'adresse d'Uptobox est bloqué par certains fournisseurs internet. Il faut changer les parametres DNS de vos carte réseau.

Bonjour,
Je pense que tu n'a pas bien lu mon retour, 
Sur le même appareil, une tablette, je peux accéder à mon compte Uptobox ainsi qu'à uptostream via navigateur et lire les vidéos.
Via vstream, je peux accéder au compte mais ça ne lit plus les vidéos.
J'utilise les dns cloudflare.

**Comment by fredseventyfive** [comment]
DNS Clouflare je l’utilise aussi ne change pas le souci 

Frédéric

**Comment by sizanic** [comment]
@ato18 
> Le problème semble identique à l'issue que j'avais créé en mai https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4048#issue-1713546292.

Déjà pour cette issue, il fallait changer les DNS ou attendre une modification de vStream qui n'essaie plus de se connecter à uptobox.com mais à une adresse alternative uptobox.eu.

Et c'est maintenant uptobox.eu qui se voit bloquée par les opérateurs.

<br>

> Sur le même appareil, une tablette, je peux accéder à mon compte Uptobox ainsi qu'à uptostream via navigateur et lire les vidéos.

Il faudrait voir si tu as bien tous les indicateurs en vert ici : 
https://uptobox.info/status

vStream utilise le système API.

**Comment by ato18** [comment]
Hello,

Depuis ma tablette :

Vérification des stats en temps réel depuis votre connexion
Votre accès - Uptobox - Site Web
Opérationnel
Votre accès - Uptobox - API
Opérationnel
Votre accès - Uptostream - Site Web
Opérationnel
Votre accès - Support
Opérationnel

Je me demande du coup si le problème ne viendrait pas plutôt de l'ipv6 qui fournit des dns du FAI.
Ça va devenir problématique, je ne peux pas le désactiver sur les appareils ni sur la box du FAI, et on ne peut pas gérer les dns dessus non plus 😠

**Comment by fredseventyfive** [comment]
Après sur machine OS Apple aucun soucis de ce genre 

Frédéric

**Comment by fredseventyfive** [comment]
Problème résolu, il faut désactiver la Connectivité IPv6 dans vos box FAI (Orange) le problème de connexion sur compte Uptobox via Vstream dans Kodi  sur Xbox sera résolu.

**Comment by ato18** [comment]
Il n'est pas possible de le faire sur les box Bouygues 😭

**Comment by sizanic** [comment]
Il existe des valeurs de paramètres DNS pour l'IPV6.
l'adresse 1.1.1.1 de cloudflare est seulement pour l'IPV4.

Dans ce tuto, le 2eme chapitre "Change tes DNS!" renvoi sur une page où on trouvera un tableau en bas qui donne les adresses IPV6 des différents DNS.

https://lesalkodiques.wiki/categorie/changer-ses-dns/

**Comment by sizanic** [comment]
La nouvelle version 2.6.2 de vStream contourne ce blocage.
