### ISSUE TITLE
Problème lecteur Dood 

### ISSUE THREAD

**Issue by yasmineyun** [Kodi-vStream/venom-xbmc-addons#4089]
**Décrivez le bug**

**Votre system**
- OS: [Android TV]
- Appareil: [nvidia shield, Ultra]
- Version Kodi: [16.17.18]
- Version Vstream: [1.7.0]

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

Bonjour ! 
Je vien d’installer Kodi sur ma tv avec vstream sauf que la plus part des sources animes sont avec le lecteur Dood mais impossible d’ouvrir ça me met un message d’erreur…
J’ai déjà activé Flaresolverr mais rien y fait :/ 
Avez vous des réponses ou bien d’autres sources a part celle déjà comprise dedans ou je pourrais regarder des animes ?

**Comment by sizanic** [comment]
Bonjour,

Il faudrait regarder sur le site internet correspondant si les liens DOOD sont également inaccessibles.
Dans ce cas, nous ne pouvons rien faire.
-> Si tu nous trouves un lien dood fonctionnel sur un site, nous pourrons regarder pour une correction.

FlareSolverr est utile pour l'accès à certaines sources.
DNSPython est également utile pour l'accès à d'autres sources.
-> As-tu bien installé DNSPython (ou changer toi-même tes parametres réseau DNS) ?


Autre solution : 
Passer par la source premium de vStream : Pastebin
(tous les animes y sont, en bonne qualité, tous les liens sont fonctionnels)

Pour cela, il faut renseigner des codes pour accéder aux contenus de cette source privée.
vStream ne fourni pas de codes.
Cette communauté d'utilisateurs KODI fourni un pack de codes : les alKODIques.
site : https://lesalkodiques.com/
facebook : https://www.facebook.com/groups/alkodiques
Discord : https://discord.gg/3RTRvT2PSE

**Comment by chrysal** [comment]
Bonjour,
Il va être difficile de faire avancer cette issue sans plus d'information. 
Cloture ? (08/23)

**Comment by sizanic** [comment]
Plusieurs évolutions du lecteur Dood depuis la date de de cette demande.
Il faudra créer une autre demande si un souci existe toujours.
