### ISSUE TITLE
Fichier introuvable 

### ISSUE THREAD

**Issue by yasmineyun** [Kodi-vStream/venom-xbmc-addons#4091]
Bonjour,
Ayant un compte alldebrid et en mettant une clé,
Impossible de lire un film ou une série car ça me met toujours « fichier introuvable » ou « fichiers manquants »…
Pouvez vous m’aidez ? Je suppose que c’est le compte alldebrid peut être que je fait quelque chose de mal j’en ai aucune idée ..

**Comment by sizanic** [comment]
Bonjour,

Comme il t'a déjà été dit sur le groupe facebook des alkodiques, et sur le Disocrd des alkodiques : 

**As-tu bien mis en place la même méthode que dans ce tuto ?**
https://lesalkodiques.wiki/categorie/premium-vstream/

**Comment by chrysal** [comment]
Bonjour, 
cloture de l'issue ?
