### ISSUE TITLE
Problème ianimes

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#4093]
Bonjour j’aimerais savoir 
Pourquoi il y a t il pas plusieurs lecteurs de disponible sur ianimes Vstream par rapport au site lui même qui en propose plusieurs et pourquoi sa met fichier non trouvable quand je clique sur Voe mixdrop pour chaque anime c la même 

ianimes marche pas sur chaque anime sa me fais 
Sa 
merci l équipe

**Comment by TmpName** [comment]
Alors deja, bonne methode ^^.
Certains ne sont pas supporté par Vstream par exemple Netu, donc tu peux en avoir plus sur le site que sur Vstream.
Apres le site a pas mal de protection, donc Vstream peut en rater.
Par contre ceux qui s'affiche sur Vstream devraient tous fonctionner si la video fonctionne sur le site.

Donc si tu pouvais me donner les lecteurs qui sont present sur le site et pas Vstream, je pourrais t 'en dire plus.
Et pareil si tu as une video qui fonctionne sur le site et pas Vstream, ca m'interesse.

**Comment by TmpName** [comment]
Alors mixdrop fonctionne chez moi.
Voe ne marche pas, mais devrait.
Filelions et Vidguard ne sont pas dans Vstream, je peux les rajouter mais ca ressemble a des hosters de passage, qui vont disparaitre dans 3 mois. premiere fois que je les vois, tu penses qu'ils sont fiables ?

Pour Voe je regarde d'ici demain.

**Comment by Mokoman30** [comment]
Mixdrop je sais pas quoi faire pour qu’il marche 
Dood que faire il semble être down partout en fichier non trouver 
Pour voe merci 

après les autres host 
Vidguard oui 
L autre filelions je sais pas trop jle connais que depuis aujourd’hui 

a vrai dire tu peut toujours les rajouters
en cas de galère niveau host 
Surtout côté anime on en a + besoin

**Comment by TmpName** [comment]
Voe est reparé.
J'ai mis Filelions, mais non activé encore
La je regarde Vidguard, mais deja le nombre de hosts possibles me font penser que ca va etre le bordel (il s'appelle aussi fertoto pat exemple ...)

**Comment by Mokoman30** [comment]
Merci faudra attendre la maj à présent du coup 
@TmpName

**Comment by Mokoman30** [comment]
Merci faudra attendre la maj à présent du coup 
@TmpName

**Comment by TmpName** [comment]
Bon j'ai rajouté Vidgaurd et filelions, mais pas sur que cela fonctionne, ils changent sans arret de nom de domaine.
Par contre dood fonctionne aussi chez moi, tu es sur que ton probleme ne vient pas des dns ?

**Comment by Mokoman30** [comment]
Top merci @TmpName 

non pas de problème de DNS sa me le fais  qu’avec Dood 
Voe 
Mixdrop 
A l heur actuel côté anime c le soucis avec ces host 
Le reste c est bon côté série et film avec d autre host c est frustrant côté anime

**Comment by Mokoman30** [comment]
Tout remarche avec cette Nouvelle MAJ
Merci l équipe

**Comment by sizanic** [comment]
Au plaisir
