### ISSUE TITLE
VSTREAM SUR TELEGRAM

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#4094]
Bonjour, je viens de créer un Canal Telegram pour vStream au https://t.me/vstreamkodi pour 
les gens qui on Telegram et qui veulent être au courant des Mise à Jour de vStream etc...

**Comment by sizanic** [comment]
![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/47307622/eb2a684e-e60f-461e-9092-c84f6bd0e1cb)

**Comment by ludopotte** [comment]
Oui @sizanic c'est la Beta que je fais manuellement pour la Communauté issue de la Beta de votre page Github
que je mets à disposition.

**Comment by sizanic** [comment]
Oui, Encore un nouveau moyen d'essayer de refourguer ta version Beta !!

Je t'ai déjà dit d'arreter de venir sur le site officielle de vStream pour vanter ta pseudo version beta de vStream non-officielle.

Nous ne reconnaissons pas la validité de cette version Beta.

Et nous ne voyons pas ce que celà apporte à la communauté.
A part apporter les ennuis d'une version instable en cours de développement.

**Comment by ludopotte** [comment]
Ok je comprends

**Comment by sizanic** [comment]
La beta est déjà téléchargeable depuis notre page officielle Github.
![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/47307622/7d7d0fcf-13d3-400c-a7b3-f637de1c203d)

Le zip contient à chaque instant les derniers fichiers, contrairement à ton zip que tu crées périodiquement (et dont tu modifies certains fichiers).

**Comment by TmpName** [comment]
Lol, et si tu re-essayes dans 2 mois, a mon avis tu vas avoir la meme reponse, ca marchera pas a l'usure.

Que tu fasses une version "perso", on peut pas l'interdire, mais tu peux pas distribuer ca en l'appellant "version beta"

**Comment by azgaresncf** [comment]
En regardant avec les git commit, il n'apporte absolument rien de nouveau.

**Comment by sizanic** [comment]
Oui, aucun intérêt.
juste les logos qui changent, et c'est le principe qui ne va pas.
Un jour ça pourrait être plus que ça.
Et la beta est déjà disponible officiellement 🤔
