### ISSUE TITLE
Possibilité de rajouter une source 

### ISSUE THREAD

**Issue by katz38** [Kodi-vStream/venom-xbmc-addons#4095]
Bonjour à toute la team, serait-il possible de rajouter cette source  le site Internet n’a pas de pub et je trouve qu’il y a vraiment tous les films dans tout le monde pourrait avoir besoin https://waymav.com/lxbj9y7xh3n/home/waymav/

**Comment by sizanic** [comment]
Bonjour,

Ce site est déjà disponible sous le nom "Kepliz".

![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/47307622/34920c41-0e26-4c99-8eaf-9dc9d57da063)
