### ISSUE TITLE
Recherche accéléré Pastebin

### ISSUE THREAD

**Issue by codegittest** [Kodi-vStream/venom-xbmc-addons#4101]
Bonjour,

Je suis tres débutant pour l’utilisation des liens pastebin. Je ne pense pas avoir vu cette problématique sur ce site. C’est probablement dû a un mauvais usage de mon côté…ou mon matériel ?

Le petit problème rencontré est que j’ai dù enlever Pastebin de mes host de recherche qui sont sélectionné dans les « tool, onglet sources » meme si pastebin propose du contenu intéressant (et diverssifié) parce que, parfois, lorsque la recherche arrive sur le host pastbin,  c’est très long et je dois re-démarrer ma boite multi média quand c’est trop long (j’attends généralement au moins 15 minutes avant de re-démarrage).

Peut-etre que cela pourrait être améliorer en ajoutant une genre de librairie en « cache » qui serait rapide d’accès en storage local ?

Essais:
Note sur des essais de recherche en passant par tool, source, pastbin, rechercher (film):
1iere recherche: « spiderman » = resultat tres lent (environ 5minutes) = spiderman 2.2 -extended cut
2ieme recherche: « spider man » = resultat tres rapide (environ 15 secondes) = Plusieurs résultats au lieu de 0 item, SUPER !
3ieme recherche, comme la 1iere « spiderman = cette fois, resultat assez rapide (environ 25 seconde) = spiderman 2.2 -extended cut

4iere recherche: « antman » = resultat tres lent (environ 6 minutes) = No item
5ieme recherche: « ant man » = resultat tres rapide (environ 15 secondes) = 3 résultats au lieu de 0 item, SUPER !
6ieme recherche, comme la 1iere « antman = cette fois, resultat assez rapide (environ 25 seconde) = No item

En résumé:
Les essais ont été effectué avec réseau ethernet cablé. La performance des résultats semblent bien se répéter. L’addon utilise bien le cache de kodi lorsque disponible mais l’addon ne dispose pas de cache scpécifique pour pastebin. Il est préférable d’insérer des « espace », dans le doute, sur le titre de recherche pour obtenir + de résultat et + rapide.

Désolé si cette question a déjà été posé et gros merci a tous pour votre belle volonté a aider la collectivité !
Bonne journée!

**Comment by sizanic** [comment]
bonjour,

Il y a bien un cache local pour la source Pastebin.

Ce cache se vide selon la période définie dans le menu vStream/sources/pastebin/Gerer les contenus/Période de rafraichissement.

S'il est réglé sur 12 heures, cela est très court.
Alors que pour renouveler le cache, vStream télécharge toutes les listes de tous les contenus, ce qui prend plusieurs minutes.
Et si ton seul accès à Pastebin est lors d'une recherche, ce temps sera consommé lors de ta recherche.

Il est plus agréable de régler le cache sur une période d'une semaine.

6 minutes semble bien correspondre au temps de renouvellement du cache.


Désactiver cette source pour qu'elle ne soit pas utilisée lors de la recherche globale est un bonne solution, couplé avec des raccourcis qui permettent la recherche exclusivement dans Pastebin.
Je dis "des raccourcis", car il est malin d'avoir un raccourci pour la recherche Film et un autre pour la recherche des séries. Sans utiliser les menus directs : Pastebin/Rechercher(Films) et Pastebin/Rechercher(Séries), mais en utilisant plutôt les menus de recherche qui se trouvent dans les dossiers créés pour les renseigner les codes Films et Séries : 
- Pastebin/Gérer les codes/Films/Rechercher(Films)
- Pastebin/Gérer les codes/Séries/Rechercher(séries)

Ainsi les recherches ne s'effectueront que dans les codes correspondant aux type de contenus recherché.

**Comment by codegittest** [comment]
Wow, champion, je vais essayer ca !
Merci beaucoup, désolé si j’ai manqué un peu d’info a ce sujet !

**Comment by codegittest** [comment]
Ok, en y repensant un peu, cela implique qu’un utilisateur ait trouvé un bon host, qui lui offre l’occasion de trouver le film ou télé serie qui lui intéresse (certain host sont tres actif sur la classification du nouveau contenant, ce qui les rend intéressant) et qui, par la suite pourras aller faire une recherche pastbin de la «bonne » façons(rapide) pour voir si le contenu s’y retrouve également. Ca se complique un peu dans ce cas si 4 - 5 option d’émission sont intéressante et qu’il faut les prendre en note sur un bout de papier pour consulter pastebin avec les bon raccourcis par la suite ?

Mon questionnment d’amélioration pourrait maintenant être adapté pour nous orienter s’il pourrait etre possible d’améliorer la facon de faire apparaitre ces raccourcis pour qu’il soit disponible dans la page où l’usager se retrouve ?

**Comment by codegittest** [comment]
Petite idée, avec le menu contextuel sur un fichier en particulier, au lieu de faire « search » qui exclu pastebin (configuration: tool sélection des sources) parce que ce n’est pas la méthode efficace d’effectuer la recherche, une recherche pastbin pourrait etre ajouter au menu contextuel avec les raccoucis tel que M. Sizanic propose ?

Probablement difficilement réalisable si cela est possible, c’est juste une idée parmi d’autres ? Oui cela pourrait engorger le menu contextuel mais avec une option pour activer ou non selon l’utilisateur, ceux-ci pourrait choisir ce qui leur convient ?

**Comment by sizanic** [comment]
> Ok, en y repensant un peu, cela implique qu’un utilisateur ait trouvé un bon host, qui lui offre l’occasion de trouver le film ou télé serie qui lui intéresse et qui, par la suite pourras aller faire une recherche pastebin

Alors si l'objectif est de parcourir des suggestions de films pour en trouver un de bien avant de lancer une recherche, je te propose cette solution :

Parcours les films depuis le menu : 
_Videos à la demande/Recherche/Recherche thématique_

Toutes les nouveautés (et films populaires) y sont rassemblées, indépendamment des sources.
(Il s'agit des classements du site theMovieDB.org)
La sélection d'un film lancera automatiquement la recherche sur toutes les sources actives.

**Comment by sizanic** [comment]
Concernant la possibilité de faire une recherche seulement dans Pastebin, et une autre recherche sur les autres sources (et sans pastebin), il y a également cette solution : 

Plutôt que de parcourir les suggestions de TheMovieDB dans les menus de vStream, il est possible de parcourir les suggestions de TheMovieDB directement depuis l'extension officielle "TMDB-Helper".
Cette extension propose d'ailleurs beaucoup plus de classements (par diffuseurs, en salles, prochainement, etc.) . Il est même possible de créer ses propres filtres de recherche (mélange de genre et d'année par exemple).
Il sera donc beaucoup plus facile de trouver un contenu intéressant, sans se reposer sur les classements des différentes sources de vStream (et sur la présence ou non des films).

L'extension TMDB ne propose que des suggestions de films, elle ne propose pas de liens.
Ce sera toujours vStream qui fournira les liens.
Il faudra donc associer les deux extensions pour que la sélection d'un film dans TMDB lance la recherche de liens dans vStream.

De plus, la personnalisation de cette association permet de : 
- lancer d'abord une recherche dans la source Pastebin.
- si aucun résultat n'est trouvé, alors seulement une deuxième recherche est automatiquement lancée sur les autres sources actives.

Voici un tuto pour installer l'extension "TMDB-Helper", et pour associer les deux extensions (voir le chapitre sur les "players")
https://lesalkodiques.wiki/categorie/tmdb-helper/

**Comment by sizanic** [comment]
Et enfin, si tes recherches sont toujours très longues (et c'est ce qui te pousse à trouver des solutions), cela vient peut-être aussi des performances de ton équipement.

Un bon équipement qui a fait ses preuves pour une bonne utilisation de Kodi et vStream, est le "FireStick 4K MAX".
Et comme de par hasard ...
aujourd'hui débute une promo chez Amazon, ce stick est disponible à 43€ (au lieu de 75€).

**Comment by sizanic** [comment]
> une recherche pastbin pourrait etre ajouter au menu contextuel avec les raccoucis tel que M. Sizanic propose ?

Si tu t'adresses aux développeurs de vStream pour leur suggérer une évolution selon ma proposition, sache que je suis développeur vStream.
Du coup tu me parles à la 3eme personne 😵

**Comment by codegittest** [comment]
Merci beaucoup pour ces réponses précises, rapides et fonctionnelles et qui m’a conduit a essayer de quoi de nouveau !
Cela répond à probablement les 2 grosses problématiques que j’avais rencontrés depuis un certain temps (ou quelques années): la facon pour trouver du contenu intéressant et la recherche qui ne fonctionnait pas bien avec pastebin activé.

Pour ce qui est du matériel utilisé, effectivement je vais probablement l’améliorer pour un rpi4 ou ?…), je n’aime pas os android avec tout les services qui tournent en background, je recherche + un linux (light) optimisé pour le matériel et dédié pour la tache.

A propos de vous appeler a la 3ieme personnes, je ne comprend pas trop ce que voulez dire (une reproche ou un mauvais choix de mots ?). j’essais d’être courtois et poli d’autant que possible avec tous. Je sais que vous faites partie de ce qui semble être une très petite communautés qui ont la capacité de contribuer au développement et a aider pour des usagers qui ont des questions un peu comme moi. Pour cela, par politesse et quand j’y pense, j’ajoute parfois M (monsieur) avant le nom d’un membre d’un forum.

Gros merci encore!

Autre petite question, l’option des bookmark n’est peut-etre plus accessible en passant par l’interface de recherche, j’imagine que je devrais regarder de plus près comment trakt fonctionne ? Désolé, Tous ca est nouveau pour moi !

bonne journée a tous !

**Comment by sizanic** [comment]
> Merci ! Cela répond à probablement les 2 grosses problématiques que j’avais rencontrés depuis un certain temps (ou quelques années): la facon pour trouver du contenu intéressant et la recherche qui ne fonctionnait pas bien avec pastebin activé.

De rien.
Profites bien 😉 


> Pour ce qui est du matériel utilisé, effectivement je vais probablement l’améliorer pour un rpi4 ou ?…), je n’aime pas os android avec tout les services qui tournent en background, je recherche + un linux (light) optimisé pour le matériel et dédié pour la tache.

Je t'aurais bien proposé de prendre une clef Amazon Firestick 4KMax en promo en ce moment à 43€.
Même avec des services en arriere plan, elle fait bien le job pour faire tourner Kodi !
Mais c'est de l'android, et même pire (un MOD d'android encore plus figé) !
Bien que le prix fasse réfléchir.

> A propos de vous appeler a la 3ieme personnes, je ne comprend pas trop ce que voulez dire (une reproche ou un mauvais choix de mots ?). j’essais d’être courtois et poli d’autant que possible avec tous.

Ce n'était pas du tout un reproche.
Plutôt une blague.
J'apprécie toujours ta courtoisie et ta politesse, je voulais donc me permettre un peu d'humour.

Tu poses une question aux développeurs : _"une recherche pastbin pourrait etre ajouter au menu contextuel  ?"_
Et je suis développeur, donc tu me parles directement.
Mais tu fais référence à la suggestion de sizanic  : _"avec les raccourcis tel que M. Sizanic propose"_
Donc tu me parles en faisant référence à quelqu'un d'autre à la troisième personne du singulier.
Sauf que ce quelqu'un d'autre c'est moi aussi 😄 

Je trouvais cette tournure de phrase un peu drôle.

**Comment by sizanic** [comment]
> Autre petite question, l’option des bookmark n’est peut-etre plus accessible en passant par l’interface de recherche, j’imagine que je devrais regarder de plus près comment trakt fonctionne ? Désolé, Tous ca est nouveau pour moi !


Je ne comprends pas trop.
Normalement, les résultats de recherche de vStream propose le menu "marque-pages".

(si ton menu s'appelle "bookmark", penses à régler ton kodi en Français 😉 )

S'il s'agit d'une recherche avec une autre extension que vStream, forcement seule la fonction "Favoris" de Kodi est disponible.

**Comment by codegittest** [comment]
Bonjour,

parfais super cool alors !

Coté bookmark, oui mon menu kodi est en anglais causé par un mauvais fonctionnement d’un addon iptv pvr que j’avais testé a une certaine époque , suite a certains essais, j’ai constaté qu’il ne supportait pas le format (caché) date-heure-region du guide (?). Je pourrais remettre en francais, effectivement, cela fait aussi en sorte que le contenu démarre en anglais par défaut. Oui, Tel que vous mentionnez, le comportement est le suivant, recherche externe, si la 1iere recherche avec pastbin ne trouve pas, le fallback avec les autres host nous retourne a vstream et permet alors l’ajout de bookmark(marque page) comme d’habitude. Je comprend maintenant que la recherche externe possède un menu contextuel différent qui n’a rien a voir avec vstream mais lorsque du contenu est trouvé avec pastbin, les liens sont affiché avec l’inscription «vstream » en haut (ce qui laisse croire que nous avons basculé dans l’addon de vstream rendu a ce niveau). C’est un peu pour cette raison que j’avais pensé voir l’option du marque page les résultat aussi ontenu avec pastebin. J’aime bien les marque page car ils ont l’avantage (comparé a l’utilisation des favoris) de séparer la liste en 2 plus petites (film ou serie). L’autre avantage est de ne pas trop remplir les favoris qui sert aussi a une bonne quantité de addons. Je vais regarder l’option Trakt qui semble faire une bonne gestion mais « online » (au lieu de local ) et avec peut etre l’avantage de pouvoir sélectionner un usager en particulier.

pour android, c’est pas juste tout les services inutile en background, il doit y avoir pas mal de telemetrie aussi (ca serait un peu comme branché ma tv sur le net)…En roulant quelque chose comme corelec au lieu de android me semble avoir deja constaté un usage cpu 25-30% plus faible, le matériel peu donc etre un peu moins puissant (malgré que l’important est plutot un bon hardware video décodeur) , ce qui au bout du compte doit pas mal équivaloir au prix de la firestick. J’avoue que pour le atmos passtrow 4k c’est plus difficile a trouver a bon $ mais le atmos francais est encore rare je pense.

Autre question si vous permettez (svp! 😉), dans la config tmdb helper, j’ai sélectionné mon api avec tmdb existant au lieu de m’en créer un nouveau avec omdb et ca marchait bien mais, avec tout les essais, il y a eu un blocage de la recherche en fin de journée (ok aujourd’hui), j’ai pensé que j’avais peut-etre atteint une limite « token »?  Il y a peut-etre un avantage a utiliser ombd si c’est ce qui est suggéré ?

Merci encore !

**Comment by sizanic** [comment]
> le comportement est le suivant, recherche externe, si la 1iere recherche avec pastbin ne trouve pas, le fallback avec les autres host nous retourne a vstream et permet alors l’ajout de bookmark(marque page) comme d’habitude.

cool, tu as vraiment mis en place tmdbhelper avec fallback, sans trop de probleme.


> Je comprend maintenant que la recherche externe possède un menu contextuel différent qui n’a rien a voir avec vstream mais lorsque du contenu est trouvé avec pastbin, les liens sont affiché avec l’inscription «vstream » en haut (ce qui laisse croire que nous avons basculé dans l’addon de vstream rendu a ce niveau). C’est un peu pour cette raison que j’avais pensé voir l’option du marque page les résultat aussi obtenu avec pastebin. 

Même en passant directement par vStream, il n'est pas possible de mettre un "lien" en marque-page.
Mais avant d'afficher le lien, il y a normalement l'affichage du résultat de pastebin (la pochette du film). C'est à ce niveau que devrait se trouver le menu vStream (avec marque-page).


> dans la config tmdb helper, j’ai sélectionné mon api avec tmdb existant 

Si l'APi TMDB existant est bien celle installée par défaut avec vStream, il serait préférable que tu crées la tienne.
vStream fournit une API TMDB seulement pour la recherche des pochettes. C'est une API partagée par tous les utilisateurs de vStream.
A partir du moment que tu utilises TMDBHelper, tu dois utiliser ta propre API pour profiter de tout ce que peut t'apporter cet addon (créer tes propres listes, etc..) .


Si tu veux maintenant te renseigner sur Trakt, ou approfondir tes connaissances sur les api OMDB et sur les fonctionnalités TMDBHelper, comme cela s'écarte un peu de vStream, je te propose de continuer avec la communauté des alKODIques.

En plus des tutos, elle est très active sur : 
Discord : https://discord.gg/3RTRvT2PSE
Facebook : https://www.facebook.com/groups/alkodiques

**Comment by codegittest** [comment]
Oui j’avais créé mon propre api key pour tmdb avec un conseil que j’ai peut-etre trouvé ici sur github et c’est pourquoi j’ai pensé l’utiliser. Je le partage avec seulement 2-3 amis. Je comprends que maintenant il serait interessant que ceux ci ait leur propre api key. Par contre ils n’ont pas de débrideur donc une configuration que l’on pourrait dire traditionnel (pour ne pas dire ancienne) avec un usage pas tres fréquent de ce que j’en sais.

Je ne suis pas sur les réseau sociaux, si rapidement vous pouvez me dire s’il y a un avantage particulier a utiliser omdb par rapport a tmdb j’apprécierais. Sinon je comprend que omdb serait dévellopé open source semblable a tmdb, peut-etre avec moins de restriction  mais avec des pochettes, info, classement,…. Similaires ?

Merci !

**Comment by sizanic** [comment]
> Je ne suis pas sur les réseau sociaux, si rapidement vous pouvez me dire s’il y a un avantage particulier a utiliser omdb

Pas besoin d'être sur les réseaux pour te documenter, toutes les infos sont disponibles sur le site lesalkodiques.com, sans avoir besoin de s'inscrire.

Par exemple : 
https://lesalkodiques.info/les-cle-api/

**Comment by codegittest** [comment]
Ok, merci beaucoup !
Vous avez raison qu’il y a beaucoup d’info a lire un peu partout….vraiment désolé !
J’ai encore beaucoup a appendre sur l’interaction entre les addons. Parfois, il serait bien d’avoir un info bulle sur chacune des options disponible mais c’est programmé en python et ca n’a pas d’l’air facile !

**Comment by sizanic** [comment]
> Vous avez raison qu’il y a beaucoup d’info a lire un peu partout….vraiment désolé !

Ne soit pas désolé
C'est juste que je suis déjà très actif sur les réseaux des alkodiques, je ne peux pas maintenir le même niveau d'échange ici.

Si c'est bon pour toi pour ta question initiale, je te laisse cloturer ce ticket.

**Comment by codegittest** [comment]
Parfais merci !
