### ISSUE TITLE
Proposition d'un site

### ISSUE THREAD

**Issue by ceux70** [Kodi-vStream/venom-xbmc-addons#4102]
bonjour

Est ce possible de rajouter ce site sur vstream ?

fastream.re

encore merci pour tous 

cordialement

**Comment by sizanic** [comment]
Bonjour,

Merci pour cette proposition, nous allons l'étudier.

**Comment by TheSamurai4861** [comment]
C'est vrai que ce site possède des liens de qualité 👍🏻

**Comment by chrysal** [comment]
Bonjour, 

Le site n'existe plus je pense que l'issue peut être clôturé

Cordialement,

**Comment by sizanic** [comment]
bien vu...
