### ISSUE TITLE
New Sources

### ISSUE THREAD

**Issue by neirdah6040** [Kodi-vStream/venom-xbmc-addons#4103]
voici quelques sites qui pourrait vous intéressez pour rajouter a l'addon 
ht tps://dessins-anime.com/
h ttps://voircartoon.com/
ht tps://ww3.french-streams.biz/
htt ps://www.enstream.top/
h ttps://www.filmstreaming1.one/
htt ps://filmz-streaming.net/
h ttps://streaminze.org/
htt ps://mesfilms.sbs/
htt ps://voir-films.net/
ht tps://www.vfilms.club/
ht tps://wvvv.voirseries.rip/
htt ps://www.blablastream.one/
ht tps://findmovies.vip/
ht tps://www.cpasfini.me/
ht tps://www.dpstream.life/
ht tps://allostreaming.one/
h ttps://wwv.serieflix.biz/
ht tps://sadisflix.us/
htt ps://vrewal.com/
ht tps://wvw.skstream.rip/
ht tps://wwv.streamdeouf.net/
ht tps://cinetimes.org/
ht tps://www.quedustreaming.top/
h ttps://www.seriecenter.top/
ht tps://www.omgflix.xyz/

**Comment by sizanic** [comment]
Bonjour et merci pour tes propositions,

Cela fait pas mal d'adresse.
Nous aurions besoin d'aide et tu peux nous aider.


Voici les sites que nous utilisons : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites.json

Ce que tu peux faire pour nous aider : 
- supprimer de ta liste ceux que nous proposons déjà (mesfilms.sbs, vrewal = kepliz par exemple)
- vérifier que nos adresses ne sont pas d'anciennes adresses et nous donner la correspondance vers la nouvelle adresse (par exemple : nous avions streaminze.com alors que tu as la nouvelle : streaminze.org)

**Comment by neirdah6040** [comment]
voici la liste des mise à jours et nouveaux site 
bien à vous 

Update :

https://1seriestreaming.com/ devient : https://1seriestreaming.net/
https://www.4kstreamz.net/ devient : https://www.4kstreamz.fr/
https://vf.alloflix.com/ devient : https://www.alloflix.vin/
https://ianime-fr.com/ devient : https://franime.fr/
https://www.extreme-down.app/ devient : https://www.extreme-down.moe/
https://www.illimitestreaming.co/ devient : https://www.illimitestreaming.top/
http://livetv.sx devient : http://62.182.83.65/frx/ 
https://serie-streaming.plus/ devient : https://series-streamings.net/
https://ww.streamcomplet.click/ devient : https://streamcomplet.top/
https://vf-film.top/ devient : https://www.vf-film.tv/
https://voirseries.io/ devient : https://wvvv.voirseries.rip/



New :

https://www.filmstreaming1.one/
https://www.seriestream.stream/
https://streamcomplet.top/
https://www.enstream.top/
https://www.seriepourvous.vin/
https://www.serieflix.top/
https://series-fr.org/
https://series-streamings.net/
https://empire-stream.net/
https://voirseries.tv/
https://wwv.blablastream.rip/
https://www.monstream.top/
https://wwvv.cocostream.rip/
https://seriecenter.com/
https://poblom.xyz/
https://www.cpasmal.one/
https://voir.dustreaming.online/
https://streamingclic.top/
https://wwv.streamdeouf.net/
https://coflix.cam/
https://ww3.filmstoon.ink/
https://megastream.monster/
https://www.gocine.rip/
https://wwvv.frstream.rip/
https://www.frenchstream.kim/
https://www.topfilm.buzz/
https://www.streamingvf.life/
https://www.allostreaming.club/
https://www.frenchstream.club/
https://www.filmnetflix.org/
https://streamingseries.cam/
https://voirseries.monster/
https://www.filmfrench.stream/
https://ww1.darkino.co/
https://www.juststream.homes/
https://dpstream.homes/
https://www.zonestreaming.top/
https://www.01streaming.top/
https://www.waystreaming.top/
https://www.streamdeouf.top/
https://www.wishflix.top/
https://www.quedustreaming.life/
https://filmscultes.online/
https://seriescultes.website/
https://champiov.com/

**Comment by sizanic** [comment]
Vraiment merci pour ce travail.

Mais reste encore un peu de tri à faire sur la nouvelle liste.

Par exemple champiov.com est un clone de vrewal qui est un clone de kepliz.
Ce n'est pas la peine de proposer tous ces clones qui ont la même apparence (la petite fenêtre d'accueil "binvenue sur XXX" qu'il faut cliquer pour entrer.)


Cette adresse ne fonctionne plus : https://ww1.darkino.co/
Mais de toute façon nous ne prendrons pas ce site (sujet déjà discuté).

Et la liste est trop grande.
Des grandes listes comme celle-ci, nous pouvons en trouver facilement.

Nous attendons plutôt des propositions "étudiées".

J'ai essayé quelques sites et les films populaires sont proposés en CAM, alors que des liens HD existent.

Il faut trouver des sites qui sont régulièrement mis à jour avec les derniers liens.

("Le Chat Potté 2" sur cpasmal.one est une pub 1xBET)

**Comment by TmpName** [comment]
Merci, mais le probleme c'est qu il y a peu de developpeur pour rajouter de nouveau site, donc tu peux en proposer 2/3 au cas ou passe un motivé, mais la ca fait trop.

**Comment by sizanic** [comment]
On regarde déjà pour les changements d'adresses.

J'ai déjà changé pour streaminze et liveTV.

**Comment by neirdah6040** [comment]
petit question, j'ai pu remarquer que quand l'on va sur le moteur de recherche DuckDuckGo en mettant le nom de n'importe quel film suivi de french stream on pouvait trouver n'importe quel film.
ne serait il pas possible d'ajouter une genre d'API DuckDuckGo ce qui permettrais de ne plus devoir ajouter les sites car tout serait disponible directement dans la recherche comme sur un pc mais sur kodi

**Comment by sizanic** [comment]
Je n'ai pas réussi à installer duckduckgo car je n'ai pas la bonne version de windows.
Mais j'ai installé l'extension pour chrome.
Peut-être que le résultat n'est pas le même.

Mais la recherche de streaming me donne bien des liens vidéos, mais il faut ensuite se rendre sur le site qui propose le lien pour voir la vidéo.

Si c'est juste ça, vStream ne saura pas lire la vidéo d'un site s'il ne sait pas comment est constitué le site.
Et ainsi éviter l'affichage des publicités, décrypter le lien pour retrouver le fichier vers l'hébergeur, etc...

**Comment by neirdah6040** [comment]
avec une IA se sera peut être possible mais c'est un énorme travail

**Comment by neirdah6040** [comment]
par contre je pense que j'ai trouver un site intéressant : http://pandax.space/

**Comment by sizanic** [comment]
l'interface est sympa mais très pauvre en contenu.
Il n'y a que ce qu'on voit dans la page "Films".

**Comment by neirdah6040** [comment]
nouveau site je suppose l'on verra dans le temps

**Comment by neirdah6040** [comment]
a l'air prometteur aussi https://tofliw.net/

**Comment by neirdah6040** [comment]
je sais pas si c'est possible mais sur ce discord il  y a blindé https://disboard.org/fr/server/1110912720448012349

**Comment by Chromatic-governor** [comment]
Bonsoir,
Quels sont les pré-requis techniques pour une possible intégration d'un site dans Vstream ? Car je pense à 2 sites dont le contenu est plutôt accès sur de la qualité HD : 
- https://empire-streaming.app/ 
- https://1jour1film.website/
Pour un site de séries (uniquement) dont les mises à jour sont quotidiennes : 
https://megastream.land/

**Comment by sizanic** [comment]
> a l'air prometteur aussi https://tofliw.net/

Même avis que le précédent : 
- beau mais trop peu de contenu
- trop récent, il faut un site assez vieux pour s'assurer qu'il perdurera

**Comment by sizanic** [comment]
> je sais pas si c'est possible mais sur ce discord il y a blindé https://disboard.org/fr/server/1110912720448012349

On ne fait rien qui nécessite d'être connecté, ou d'avoir un compte.

**Comment by sizanic** [comment]
@Chromatic-governor 
Merci pour tes propositions

> https://empire-streaming.app/

le site est protégé par cloudflare, on ne s'attarde plus sur ce genre de site.

> https://1jour1film.website/

on l'a déjà dans notre liste de sites intéressants, il faudra qu'on s'y attarde, cette source nous est régulièrement proposée 👍🏻 

> https://megastream.land/

Tout à fait le genre de site interessant.
Du vieux comme du récent.
Plusieurs hébergeurs par lien.
Les séries sont  bien classées par saisons.

On le met dans notre liste 👍🏻

**Comment by neirdah6040** [comment]
Par contre pour les dessins animés ce site n'est pas a négliger ce serait bien de le rajouter 
https://dessins-anime.com/

**Comment by sizanic** [comment]
oui, très bon site, dans les critères 👍🏻

**Comment by neirdah6040** [comment]
voici une très bonne source pour la tv en direct 
http://www.callofliberty.fr/tv/tv.php

**Comment by sizanic** [comment]
> callofliberty

je ne connaissais pas.
Très bon site 👍🏻

**Comment by haloule13** [comment]
Salut la communauté. ;Je vous propose une liste de site de qualite (1080p) pour film:
ht tps://1jour1film.website/
ht tps://ww2.cpasmieux.boats/
ht tps://empire-streaming.app/

et pour series:
ht tps://www.cinezzz.club/films-complet/
ht tps://seriecenter.com/
ht tps://streaming-series.la/

et pour émissions/feuilleton TV
h ttps://coolflix.co/tv

**Comment by TmpName** [comment]
Et il n y a personne qui veut se lancer pour commencer un nouveau fichier site ? https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-cr%C3%A9er-sa-propre-source (je ne demande pas aux actuels devs de Vstream evidement)

Je peux filer un coup de main, j'ai de la dispo cette semaine.

**Comment by abda11ah** [comment]
une liste que j'ai trouvé sur un forum (onche.org)
j'ai enlevé les anglophones et les certains liens morts


https://www.zone-telechargement.fit/ (url mise à jour le 26/11/2023)

https://www.zone-annuaire.xyz/ /!\ suspendu, en attente d'une nouvelle url

https://www.tirexo.boo/ màj 26/11/2023

https://movieparadise.org/

https://youflix.fr/ (Regroupe les films postés sur diverses plateformes y compris youtube)

https://hawkmenblues.net/

http://rarelust.com/ sélection de films rares et cultes (mais pas que)

https://muaddib-sci-fi.blogspot.com/

http://empire-streaming.co/

https://www.streampourvous.lol/

https://www3.yggtorrent.qa/


Blogs francophones :

[http://atreyucinema.blogspot.com](https://atreyucinema.blogspot.com/)

[http://aupalacecesoir.blogspot.com](https://aupalacecesoir.blogspot.com/)

https://buddy-movierepack.blogspot.com/

https://le-bunker-des-inedits.blogspot.com/ (permet de retrouver des films inexistants en l'état, par exemple avec l'image restaurée en HD sur laquelle on a resynchronisé la bande son d'un ancien doublage disparu depuis, comme "Amadeus" par exemple)

[http://cineseance.blogspot.com](https://cineseance.blogspot.com/)

https://cineseptbis.blogspot.com/

https://filmarevoirnad.blogspot.com/

https://filmdutemple.blogspot.com/

https://humungus-cinebisart.blogspot.com/

[http://indianagilles.blogspot.com](https://indianagilles.blogspot.com/)

https://leparadisdufilm.blogspot.com/

https://lupanarsvisions.blogspot.com/


[http://stalkerjany.blogspot.com](https://stalkerjany.blogspot.com/)

https://kebekmac.forum-canada.com/ (nécessite un compte pour effectuer une recherche, j'en suis membre vous pouvez y aller)

Autres :

https://www.zone-telechargement.homes/ (Accessible uniquement via un VPN ou en modifiant vos DNS, voir les explications dispos en page 4)


http://unfilmpourmatablette.unblog.fr/

Un petit rajout : https://bmoviesblog.wordpress.com/

les séries TV :

[http://vegas-remingston.blogspot.com/](https://vegas-remingston.blogspot.com/)

et du même auteur :

Liens partagés par les membres de Onche (merci à vous) :

https://www.frenchstream.live/

https://wallostreaming.com/ Barré car site de merde

https://www.cpasfini.rip/

https://neko-sama.fr/ (Animes en VO et VOSTFR)

https://www.filmstreaming1.click/films/uqload

http://voirfilms.io/

https://www.voirseries.kim/

https://www2.darkino.net/

https://voircartoon.com/

https://www.papadustream.uno/

https://nyaa.si/ (Pour les KJ)

https://www.wawacity.kim/

https://fmovies.name/ Liste des url de fmovies

https://french-stream.bio/

https://www.juststream.mom/

https://ridomovies.pw/

https://on.imoviz.com/

https://www.mavanimes.co/

https://mavanimes.cc/

https://www.megastream.monster/

https://monstream.dog/

https://www.hdss.zone/

http://www6.f2movies.to/ (site de VOST)

http://yopflix.cc/

http://myflixerz.to/ (site de VOST)

https://wiflix.voto/


https://susflix.tv/all_movies inscription obligatoire mais pas besoin d'email

https://aniwatch.to/ animes

https://aniwave.to/ animes

https://animeflix.live/ animes

https://rarefilmm.com/ films rares


http://www.lookmovie2.to/

https://nightflix.app/

https://v5.voiranime.com/ animes

https://t.me/netfluxxxx (nécessite un compte telegram)

https://abokav.com/k1b02obeok2bw4/home/abokav

https://droskop.com/3osm5vq41x/home/droskop

https://topkiv.com/p40c6mrayi25/home/topkiv

https://saypap.com/yls4vtakk01ki6w/home/saypap

https://lokarn.com/x31rs9qei7/home/lokarn

https://www1.voirfilms.st/

https://coolflix.co/ (Films/Séries/émissions TV)

https://french-stream.digital/

https://www.pelistream.co/

**Comment by sizanic** [comment]
Merci mais ...
Trop de propositions tue les propositions 😄 

Voir mes premiers échanges en haut de cette discussion.

**Comment by MrKabriol** [comment]
> Salut la communauté. ;Je vous propose une liste de site de qualite (1080p) pour film: ht tps://1jour1film.website/ ht tps://ww2.cpasmieux.boats/ (uniquement pour l'hebergeur HYDRAX en 1080p)
> 
> et pour series: ht tps://www.cinezzz.club/films-complet/ ht tps://seriecenter.com/ ht tps://streaming-series.la/
> 
> et pour émissions/feuilleton TV h ttps://coolflix.co/tv

Bonjour, petit up pour la short liste suivante : 
tps://1jour1film.website
tps://www.cinezzz.club/films-complet
ttps://coolflix.co/tv

Ainsi que si possible résoudre les sources Darkino et Wawacity. Ce sont 5 sites très actifs. O:-)

**Comment by sizanic** [comment]
Bonjour,
on n'a pas perdu cette liste de vue 👍🏻 

Pour le moment, on vient de sortir une nouvelle version avec ces 6 nouvelles sources : 
**_FILMS / SÉRIES :_**
JustStream
WIKIflix

**_FILMS/SÉRIES/TV RÉALITÉ :_**
Monstream

**_SÉRIES :_**
BLUEseries
DuLourd

**_JAPANIME :_**
animeultra

<br>
<br>
Pour Darkino et Wawacity, le même souci ne nous permet pas pour l'instant de les prendre en charge.

**Comment by sizanic** [comment]
Les sites sont triés et ajoutés selon nos capacités de traitement
