### ISSUE TITLE
vStream version web

### ISSUE THREAD

**Issue by DavidHenryThoreau** [Kodi-vStream/venom-xbmc-addons#4104]
Je souhaterais pouvoir utiliser vstream dans un navigateur depuis un VPN sur un PC.
L'option du remote desktop n'est pas pratique. 

Est-ce qu'il est possible d'auto-herberger vstream derrière un serveur web ?

**Comment by detobel36** [comment]
vStream est un addon Kodi...
Il a besoin de Kodi pour tourner.

Donc... Non c'est pas "possible" (en tout cas, pas en l'état) sans modifier le code

**Comment by DavidHenryThoreau** [comment]
@sizanic 
Héberger vStream sur un serveur est se connecter dessus via un reverse proxy.

@detobel36  Dommage, Merci pour ta réponse

**Comment by sizanic** [comment]
> Héberger vStream sur un serveur est se connecter dessus via un reverse proxy.

Je ne comprends pas du tout quel est l'intention. A quoi cela peut servir.

Kodi existe pour toutes les plateformes, il suffit d'installer kodi sur chacune des plateformes où tu veux utiliser vStream.

**Comment by detobel36** [comment]
> > Héberger vStream sur un serveur est se connecter dessus via un reverse proxy.
> 
> Je ne comprends pas du tout quel est l'intention. A quoi cela peut servir.
> 
> Kodi existe pour toutes les plateformes, il suffit d'installer kodi sur chacune des plateformes où tu veux utiliser vStream.

Et bien ne pas devoir installé Kodi partout... C'est une bonne utilisation.

Par exemple, je suis chez moi, j'ai 2 téléphone, 2 PC, une tablette, les membres de ma famille ont au moins un téléphone également...
Chaque appareil doit avoir Kodi d'installé et de configuré.

Si il était possible de faire tourner vStream sur un serveur, je n'aurai qu'a visiter une URL et/ou faire une requête et je recevrait l'URL pour lire mon film/ma série directement dans mon navigateur.

Donc je comprend la demande. Mais vStream n'a pas été fait pour ça 😉
