### ISSUE TITLE
Alldebrid

### ISSUE THREAD

**Issue by jeyjey43** [Kodi-vStream/venom-xbmc-addons#4108]
Je ne parviens pas à ouvrir le dossier "Liens" de ma source Alldebrid dès lors que les liens sont trop nombreux.
Cela provoque un freeze voire cela provoque la fermeture de Kodi.

- OS: Windows et android
- Version Kodi: 20.2
- Version Vstream: 2.6.4

**Comment by sizanic** [comment]
Bonjour.
C'est noté. On va regarder.

**Comment by jeyjey43** [comment]
La maj a réglé le problème. Merci

**Comment by sizanic** [comment]
De rien 👍🏻
