### ISSUE TITLE
Liens Vstream fonctionnent sous Windows mais pas Android

### ISSUE THREAD

**Issue by johnLamarck** [Kodi-vStream/venom-xbmc-addons#4114]
Bonjour. J'ai un petit soucis avec mon Kodi 18.8/18.9/20.2 : alors que les liens Vstream fonctionnent ds Windows 10 les mêmes liens n’apparaissent pas sous Android (Tablette+Android Box). Tout va bien jusqu à ce que je doive cliquer sur le lien final (par ex. Uqload) : celui ci apparait ds Windows mais pas dans Android. Mes DNS sont changés je précise. Une idée ?

**Comment by TmpName** [comment]
Hello, les DNS sont changes sur android et windows ?
Si tu as un navigateur sur la machine android suffit d'aller voir sur le site directement.

**Comment by johnLamarck** [comment]
> Hello, les DNS sont changes sur android et windows ? Si tu as un navigateur sur la machine android suffit d'aller voir sur le site directement.

Merci pour ta réponse. En fait j'ai changé les dns sur ma tablette (en wifi) pour ceux de cloudflare : j'ai un message d'erreur de Vstream me disant d'utiliser flaresolver (donc un proxy) apparemment ... et pourtant ça marche comme sur Windows  maintenant (et sans proxy)! Je vais essayer sur mon Android box (en ethernet) et je te tiens au courant (pour cloturer le sujet).

**Comment by sizanic** [comment]
Mais les liens de quelle source ?
Ce n'est pas précisé mais je pense qu'il s'agit de Wiflix.

J'ai le même souci, selon l'utilisation sut PC ou tablette, il me dit que c'est protégé par Cloudflare sur PC..

**Comment by johnLamarck** [comment]
C'était bien le filtrage DNS du provider qui était en cause. Merci à l communauté :-)

**Comment by chrysal** [comment]
Bonjour, 
Cloture de l'issue ?
