### ISSUE TITLE
Nouvelle source (anime)

### ISSUE THREAD

**Issue by BrozardOff** [Kodi-vStream/venom-xbmc-addons#4115]
Bonjour, voici maintenant quelques mois j'ai commencé à regarder l'animé One Piece (avec les codes ADN d'un ami), après une longue pose dû à l'arc Skypia qui devenait franchement très long et ennuyeux, j'ai décidé de reprendre ma lecture de ce magnifique animé ! 
Malheureusement mon ami en question à cesser son abonnement ADN, voici donc ma demande aujourd'hui :

Je propose donc une nouvelle source : h ttps://ww.animesultra.net/
J'ai eu l'occasion de naviguer sur le site, il est pratique et nous y retrouvons une multitude d'animés en VF ! Le site est très bien fournis pour les adeptes d'animés.

En vous remerciant, bon courage !

**Comment by sizanic** [comment]
Bonjour,

Merci pour cette proposition, nous allons l'étudier.

En attendant, as-tu pu trouver les épisodes sur les sources existantes ?

**Comment by sizanic** [comment]
Quel episode par exemple ?

**Comment by BrozardOff** [comment]
de 160 (jusqu’à 180), je trouve tout les épisodes sur une seule source mais les liens ne sont pas fonctionnels (je ne sais plus la source, je regarde ça ce soir)

**Comment by yodidon** [comment]
La source est dispo sur la version beta en espérant que tu y trouves ton bonheur.

**Comment by sizanic** [comment]
La source est maintenant disponible dans la version 2.7.6 de vStream.
