### ISSUE TITLE
Netu de retour ?

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#4116]
Il semblerait que quelqu'un ait reussi a contourner leur captcha
https://github.com/movieshark/waaw/tree/main

Et ca doit marcher car reprit dans UrlResolver.

Evidement pas moyen de reutiliser la lib telle quelle. Donc j'ai commencer a l'adapter, si quelqu'un trouve trouve comment l'utiliser sans avoir a la modifier ca m'arangerait car la je defonce leur boulot.

Bon evidement ca ne marche pas pour le moment, la je dois laisser tomber pr le moment, si quelqu'un veut y jeter un oeuil.

https://github.com/TmpName/Fichier_en_vrac/tree/master/waaw

Pour les fichiers manquants (images) j'ai copier la lib d'origine dans le repertoire de kodi.

**Comment by sizanic** [comment]
Personnellement, je n'ai malheureusement pas de temps de disponible pour regarder cela rapidement ;(

**Comment by TmpName** [comment]
Bon ben, bonne nouvelle, ca marche.
Je met ca au propre et je met a jour demain.

**Comment by TmpName** [comment]
Bon c'est en cours.
Soit ca marche pas, soit me fait bloquer pr abus de requetes ^^, je re essaye plus tard.
