### ISSUE TITLE
IPTV framapad

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#412]
Simple vous avez envie de partager une iptv avec les utilisateurs de vStream allez sur 

https://annuel.framapad.org/p/vstream

Et ajouter votre iptv il faut juste **garder la mise en page**  Pas de gras ou d'italique Merci

Voici un lien pour une explication similaire https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/TV-FramaPad

```

#EXTINF:0,FR: NOM DE LA CHAINE

http://url de la chaine
```

Vous retrouverez votre chaine dans la section TV/Framapad presque instantanement.

Bon Film

**Comment by patoche2025** [comment]
Bonjour tout le monde,

Je viens vers vous pour Framapad quand je clique dessus il me met un message d'erreur j'ai la dernière version de vstream je crois que c'est dû au fait que je suis en belgique pourtant j'utilise Cyberghost pour que mon adresse IP soit une IP Française mais voilà ca ne marche est ce que vous pouvez m'aider ou me donner des tuyaux  (je sais que j'ai déjà posé cette question mais je trouve pas de solution)

D'avance je vous remercie

**Comment by domtom25** [comment]
salut j arrive pas acceder ca me mais erreur faut il attendre la prochaine mise a jour  merci

**Comment by LordVenom** [comment]
Dans vstream tu veut dire ?  Je vient de tester pas d erreur . fait moi une copie du log de xbmc stp

**Comment by domtom25** [comment]
c es bon il fallai la mise a jour merci

**Comment by evsdroid** [comment]
Salut, j'ai un soucis au début j'avais bien eut la mise à jour avec l'accès à l'IPTV framapad, mais j'ai eut un soucis avec ma android tv j'ai du la réinitialiser, j'ai réinstaller l'extension 0.4.2 la dernière et je n'ai plus l'accès a framapad, j'ai l'ancienne interface avec l'accès au chaine Orange, SFR etc.

J'ai lancer la recherche de mise à jour d'extension dans kodi mais il m'indique que tout est à jour.

Peut tu me dire comment forcer la mise à jour celle que j'ai reçu le 30 juin 2016? Pour avoir accès à lPTV framapad.

Merci pour ta réponse et ton aide

Cdt

Evan

**Comment by TmpName** [comment]
Normallement tu peux tricher en avancant la date de ton ordi de 3 jours avant de lancer vstream.

**Comment by evsdroid** [comment]
Ok super, ça fonctionné, merci

**Comment by evsdroid** [comment]
Bonjour,
Framapad ne fonctionne plus il n'affiche plus de chaine tv et quand on vas sur le site https://annuel.framapad.org/p/vstream tout les url ont été supprimé.

**Comment by TmpName** [comment]
Ha oui ^^, protection antibot ?

**Comment by evsdroid** [comment]
Je ne sais pas, simplement quand j'ai voulu accéder à framapad via Kodi la liste était vide. Donc j'ai jeter un oeil sur le site framapad et c'est la que j'ai vu que sur chaque chaine il n'y avait plus d'url

**Comment by LordVenom** [comment]
Ou Simplement un utilisateur qui a supprimer des liens HS.

**Comment by TmpName** [comment]
Y a un historique ? Parce que le gars a tout supprime.

**Comment by LordVenom** [comment]
Oui y a historique https://annuel.framapad.org/p/vstream/timeslider#219

**Comment by joss-rendall** [comment]
la dernière version disposant de liens est la version 210
https://annuel.framapad.org/p/vstream/timeslider#210

**Comment by johngf** [comment]
sur la version 0.4.6 de vstream je n'arrive pas a ouvrir le repertoire de framapad
http://pastebin.com/QtrZaTtv

**Comment by TmpName** [comment]
Oui, il y a une erreur sur le fichier framapad, 
Je corrige freebox.py pr eviter ce bug et addfolder().
Mais il vaudrait mieux aussi corriger le fichier framapad.

**Comment by cocoboy31380** [comment]
Bonsoir tous le monde, désolé si je dérange, je découvre l'iptv sur KODI via vstream et j'ai du mal a comprendre comment tout ça fonctionne, quand je vais sur "framapad" parfois j'ai un message d'erreur en rouge, parfois une petite liste de chaine commençant par "BE :", sur tv du web j'ai bien les chaines de la TNT a part celles du groupe M6 D8, chasse et peche rmc decouverte etc etc, je vois aussi des chaines de canalsat mais qui fonctionnent pas non plus. Comment tout cela fonctionne svp ? Merci beaucoup pour vos réponses et désolé si je suis un boulet ..

**Comment by yuni572** [comment]
La même. quand je veuc regarder la tele  sur framapad(beta)   sa me met un message derreur en rouge.
probleme de lecture avec la playlist...
jaimerai mattez eurosport 1 ^^
