### ISSUE TITLE
Problème No item

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#4121]
Bonsoir à tous 
J’ai un soucis 
Frenchstream dès que je rentre dessus sa marche mais que côté film j’ai accès au host ,niveau série je clique sur n’importe quel série sa me met No item 

Wiflix par contre je rentre sa me met No item direct aucun accès 

Enstream  pareil que wiflix 

**Votre system**
- OS: [ Android]
- Version Kodi: [20.2]
- Version Vstream: [2.6.7]

Merci l équipe 

édit wiflix remarche pour le moment 

mais french stream côté série toujours pas
Ni Enstream

**Comment by sizanic** [comment]
Bonsoir,
Merci pour cet état des lieux.
On va regarder cela.

**Comment by Mokoman30** [comment]
Je pense que c du a un changement d interface chez french stream côté série du coup une Maj s imposé j’imagine 

merci la team

**Comment by yodidon** [comment]
c'est plutot french stream lol ?

**Comment by Mokoman30** [comment]
Oui dsl de pas avoir précisé le lol @yodidon

côté série j’ai no item 
Enstream est down chez moi

**Comment by yodidon** [comment]
Ok je push la correction demain si j’oublie pas …

**Comment by Mokoman30** [comment]
Merci et bonne soirée la team

**Comment by sizanic** [comment]
La version 2.7 de vStream vient de sortir avec la correction pour FrenchStream.LOL.

Par contre Enstream n'est plus disponible.

**Comment by Mokoman30** [comment]
Merci à toute l équipe 
c est génial
