### ISSUE TITLE
Aucun lien dans Vstream ne fonctionne

### ISSUE THREAD

**Issue by Stream76** [Kodi-vStream/venom-xbmc-addons#4122]
Bonjour, 

Je suis un utilisateur récent de Kodi et plus précisément de l'extension Vstream. (depuis Août).
Je suis vraiment novice j'espère vous donner suffisamment d'info sinon je complèterai en fonction de vos remarques

Je n'avais aucun problème pour regarder principalement du sport en direct et désormais quand je lance un lien j'ai le message suivant:
« Echec de lecture d’un ou plusieurs fichiers. Consulter le journal pour plus d’informations »

Je suis sur PC W10 avec la v20.2 de kodi et Vstream j'ai installé https://kodi-vstream.github.io/repo/ qui je crois permet d'avoir la dernière version 

Je pense que le problème c'est plutôt "moi" et non kodi ou Vstream...

Avez-vous une solution pour moi? que dois-je vérifier?
Merci par avance =)

**Comment by sizanic** [comment]
Bonjour,

je pense plutot que le souci et vStream 😄 

Sans doute que le site internet qui correspond à la source sur laquelle tu regardes ton sport dans vStream à changé (changement d'adresse, de présentation ou de de protection) et vStream ne sait pas encore adapté (ce qui engendrera une mise à jour).

Quelle source par exemple ?

**Comment by Stream76** [comment]
J'avais l'habitude de regarder sur Streamonsport 

Je ne sais pas si c'est le mieux mais c'était assez complet quand ça fonctionnait

**Comment by sizanic** [comment]
LiveTV est très complet également, en attendant.

**Comment by Stream76** [comment]
J'essayerai demain.
Merci d'avoir pris le temps

**Comment by sizanic** [comment]
La version 2.7 de vStream vient de sortir avec des corrections pour les liens sportifs.

**Comment by Stream76** [comment]
Merci beaucoup car effectivement même sur les autres sources c’était compliqué
