### ISSUE TITLE
ADDON DNPYTHON

### ISSUE THREAD

**Issue by Emaut** [Kodi-vStream/venom-xbmc-addons#4127]
**Décrivez le bug**
Bonjour, lors d'une recherche de film Vstream se lance correctement et charge sur les différents plateformes mais une fois arrivé à la fin de la recherche un message apparaît sur le côté droit :
"ERREUR : Addon dnpython manquant : (french-stream.moe et/ou www.novaflix.io...)"

Dans l'espoir d'avoir une réponse, merci.

**Votre system**
- OS: android
- Appareil: mibox 
- Version Kodi: 20.2
- Version Vstream: 2.7.0

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: Peu importe le film
- Nom du host (openload/vidzi/...): aucun résultat 

**Log**

**Image**
![20231104_132149](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/149875589/88651cb9-fe79-45d3-963c-eed7ed3114cc)

**Plus**

**Comment by sizanic** [comment]
Bonjour,
tu trouveras ici un tuto pour l'installation de DNSPython : 
 https://lesalkodiques.wiki/categorie/doc-vstream/

**Comment by Emaut** [comment]
Bonjour, merci de répondre aussi vite.

J'ai bien installé le module DNS comme indiqué dans votre tutoriel.
Seulement lors d'une recherche de films, le message d'erreur n'apparaît
plus mais la bibliothèque est vide.

Hors hier je trouvais bien plusieurs résultats..

**Comment by erikatremblay** [comment]
Pareille ici pourtant la recherche de série fonctionne 🤔 mais pas celle de films

**Comment by sirop2** [comment]
Pareil ici la recherche de film est buggé est impossible de downgrade Vstream

**Comment by sizanic** [comment]
Plutôt que d'essayer de downgrader, essaie plutôt l'upgrade vers la 2.7.1 qui corrige ce problème.

**Comment by Emaut** [comment]
Merci ! MAJ effectuée et tout fonctionne 👌
