### ISSUE TITLE
Bug de recherche

### ISSUE THREAD

**Issue by jlbrt0** [Kodi-vStream/venom-xbmc-addons#4128]
**Décrivez le bug**
Quand je recherche des films, quelques fois la recherche n’aboutis pas pourtant je vois bien le nombre d'éléments trouvés augmenter. J'ai essayer pas mal de chose sans succès (FlareSolverr, DNS Python, Réinstalle de Vstream)

**Votre system**
- OS: Windows
- Appareil: Asus
- Version : Kodi: 20.2 (Nexus)
- Version : 2.7.0

**Nous devons le reproduire**
Vous pouvez par exemple rechercher un film connu (moi ça ne fonctionne pas avec "Avengers")

**Log**
Je n'ai pas trouvé comment faire

**Image**
Le résultat de la recherche : 
[https://i.imgur.com/tCptLvm.png](url)
FlareSolverr après plusieurs recherche : 
[https://i.imgur.com/BYf3Sgs.png](url)

**Comment by jlbrt0** [comment]
Je précise que je n'ai pas touché au paramètre de Vstream (à par pour Trakt)

**Comment by jlbrt0** [comment]
Je viens de tester quasi toutes les sources et je remarque que le problème vient de WiliFilm. (En gros, quand toutes les sources sont actives sauf elle ça marche, sinon la recherche bug). On voit aussi lorsque la recherche n'aboutis pas qu'il n'y à pas le message disant qu'aucun élément a été trouvé, alors que elle fonctionne réellement et qu'aucun film ne correspond à la recherche qu'on a fait, ce message apparait.

Désolé pour les fautes s'il y en a

**Comment by sizanic** [comment]
Bonjour,
Merci pour ce diagnostic.

Nous voyons bien le souci maintenant avec la source Wilifilm.

Nous préparons la correction.

**Comment by sizanic** [comment]
La version 2.7.1 vient de sortir pour corriger cette anomalie.
