### ISSUE TITLE
Ajout de listes TMDB

### ISSUE THREAD

**Issue by TheSamurai4861** [Kodi-vStream/venom-xbmc-addons#4134]
Bonjour, 

J'aimerais savoir s'il est possible de rajouter des listes TMDB comme Tendances du jour/semaine et Les mieux notés pour chaque type de média. 

J'ai remarqué que la partie Films était déjà bien fournie mais dans les parties Séries et Animes, il manque Les mieux notés et les tendances pour les Animes.

Merci pour votre travail !

**Comment by sizanic** [comment]
Bonjour,
si on parle bien du menu "VOD/Rechercher/Recherche thématique", les listes sont en effet celles de TMDB.

Et TMDB ne propose pas plus de listes que celles que nous avons repris.
Rien n'est proposé pour les animes.

![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/47307622/35ab7386-641a-4396-ad7a-2241fe891160)

**Comment by TheSamurai4861** [comment]
Je n'avais pas vu la recherche thématique. 

Merci pour les éclaircissements !
