### ISSUE TITLE
Erreur dynamic setCountries dans gui.py

### ISSUE THREAD

**Issue by xonsap** [Kodi-vStream/venom-xbmc-addons#4136]
J'utilise beaucoup vstream en ajoutant les videos via le menu *Ajouter aux medias* > * Films*.
Une fois le contenu aggregé, cela fonctionne parfaitement.
Le probleme se situe lorque l'on scrape les metadonnées, kodi peut renvoyer 1 ou plusieurs pays. Si les metadonnées contiennent plusieurs pays alors la lecture n'est pas possible, et vstream retourne l'erreur *fichier introuvable*.
En regardant le log de kodi, on se rends compte que vstream essaye de mettre une chaine au lieu d'un tableau de chaine dans l'entrée de la playlist via videoInfoTag->setCountries dans gui.py ligne 428.
Il faudrait donc corriger cette ligne pour qu'elle ressemble a celle de la ligne setStudios ou setGenres.
Je rencontre le soucis avec kodi *Kodi Media Center 20.2 (20.2.0) Git:20.2-Nexus* sur rpi 3.

**Votre system**
- OS: LibreElec
- Appareil: rpi3
- Version Kodi: 20
- Version Vstream: [1.7.0]

**Comment by sizanic** [comment]
traité depuis

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/acc0397873d2b8e66b1c718203218f60bb3a1b3c
