### ISSUE TITLE
Problème No Item 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#4140]
Bonjour la team 
J’ai quelque soucis Concernant 
Gum Gum streaming No item ne marche plus alors que le site marche  

French stream (anime) aucun lien marche d aucun anime 
ianimes : Aucun hébergeur marche 
Dood a disparu alors qu’il est fonctionnel sur site 
Neko sama quand je choisi un épisode peu importe l anime sa me met No item 

toon anime qui plante il me met Connection fail invalid Url quand je choisi n’importe quel épisode d un anime 

VoirAnime qui me propose du captcha qui mène au final pas à l épisode a un no item a chaque fois 

Vostfree No item ne marche plus 

Merci la team

**Comment by Mokoman30** [comment]
Pas de soucis on est là pour prévenir d soucis merci  la team

**Comment by sizanic** [comment]
Merci pour cette liste.

**Comment by Mokoman30** [comment]
Pas de problème merci à vous la team vous êtes les best

**Comment by MisuIancu** [comment]
Bonjour,
D’abord, j’aimerais vous remercier pour votre temps dépensé pour maintenir en vie cet addon. J’ajouterai aux commentaires de Mokoman qu’il y a des sources qui semble figés, pas des nouvelles séries depuis longtemps. Cinemay,Films et Videos, French-stream , 01 Streaming en font partie.
Merci et bonne continuation!

**Comment by sizanic** [comment]
Merci @MisuIancu pour ton mesage.
On note ton retour pour regarder cela en détail.

**Comment by MisuIancu** [comment]
Plaisir. A+

**Comment by yodidon** [comment]
Côté série + Film
French stream lol no item **je ne reproduit pas le problème fonctionnel chez moi**
NovaFlix no item **je ne reproduit pas le problème fonctionnel chez moi**
Streamiz charge indéfiniment  **cloudflare**
01 streaming No item **je ne reproduit pas le problème fonctionnel chez moi**
01 série streaming no item **je ne reproduit pas le problème fonctionnel chez moi**
33 séries marche pas chaque serie + film mènent a un No item  l**e site ne répond pas**
Filmoflix No item **cloudflare**
Mes Films No item **cloudflare**
Planète streaming No item **j'essai de réparer**
Viki Erreur Contenu payant partout
Vostfree Mort aucun film marche

Merci pour ces précieux retour

**Comment by sizanic** [comment]
@Mokoman30 
As-tu bien installé l'extension "DNSPython" que l'on propose sur notre dépôt ?

Il s'installe dans Kodi depuis le menu "Installer depuis un zip" et choisir le chemin du dépot vStream.
Cette extension permet de contourner le blocage internet de ton fournisseur.

Tu peux installer cette extension ou modifier toi-même les paramètres DNS de ta carte réseau (ou sur la partie routeur de ta box internet).

**Comment by sizanic** [comment]
> il y a des sources qui semble figés, pas des nouvelles séries depuis longtemps. Cinemay,Films et Videos, French-stream , 01 Streaming ...

Bonjour @MisuIancu ,
J'ai vérifié pour chacune de ces sources et ce que propose vStream reflète bien ce qu'il y a sur les sites.

Si les sites ne proposent rien de nouveau, nous n'y pouvons rien 😅

**Comment by MisuIancu** [comment]
Merci pour votre travail, je comprends que les sites n’ajoutent pas des nouvelles séries. Par ailleurs, il avait à moment donné Enstream qui fonctionné très bien. Ce serait possible de le remettre? Merci .

**Comment by yodidon** [comment]
> Merci pour votre travail, je comprends que les sites n’ajoutent pas des nouvelles séries. Par ailleurs, il avait à moment donné Enstream qui fonctionné très bien. Ce serait possible de le remettre? Merci .

Ce site n’existe plus apparemment

**Comment by sizanic** [comment]
> Merci pour votre travail, je comprends que les sites n’ajoutent pas des nouvelles séries. Par ailleurs, il avait à moment donné Enstream qui fonctionné très bien. Ce serait possible de le remettre? Merci .

Je confirme, nous avons retiré Enstream car il n'y a plus de site à l'adresse indiquée.

Pour la source FilmsEtVideos, nous allons voir pour changer les séries proposées afin d'en avoir de plus récentes.

**Comment by Mokoman30** [comment]
Moi je comprends pas mon problème du coup 
Sa a toujours marcher correctement jusqu’à ce que je signale le problème 
J’ai toujours eu DNS python 1.12.1
Que faire sachant que c’est pas toute les sources juste une bonne parti Quoi 
Bizarrement

**Comment by sizanic** [comment]
Une bonne partie des sources est bloquée par ton FAI et pas l'autre.
DNSPython permet de contourner le blocage pour cette partie des sources, tant que ton fournisseur internet t'attribue une adresse IPV4.

Il est possible que tu aies maintenant une adresse IPV6, de plus en plus de FAI y viennent.
DNSPython n'est plus suffisant, tu dois maintenant passer par une modification manuelle de tes paramètres DNS pour contourner la protection DNS IPV6.

Soit en modifiant ces paramètres sur la carte réseau de ton équipement, soit directement au niveau de configuration routeur de ta box internet.

_Astuce_ : tu peux vérifier que c'est bien ton operateur qui te bloque en utilisant le partage de connexion d'un téléphone pour accéder à ces sources.

**Comment by Mokoman30** [comment]
Exact c est bien ma FAI
incroyable 
Merci mais je suis pas en ipv6 pourtant

**Comment by sizanic** [comment]
Je sais que des évolutions sont prévues dans DNSPython.
Sans doute pour contrer de nouvelles protections, qui sont celles que tu as rencontrées.

**Comment by Mokoman30** [comment]
Bon j’ai modifier les DNS sur les équipement et c est bon maintenant incroyable Merci

**Comment by sizanic** [comment]
Si tu as plusieurs équipements (et pour les prochains), essaies une modification directement sur le portail de configuration de ta box internet.

**Comment by Mokoman30** [comment]
Ok Merci 
Facile pour le première équipement 
Mais le deuxième j’ai un peu galerer il m’a mis pas de connexion avant de couper la wifi de la tv et d’la remettre

**Comment by Mokoman30** [comment]
French-stream lol 
Niveau Serie  seulement j’ai no item sur chaque série que je choisis 

merci l équipe

**Comment by sizanic** [comment]
bonjour @Mokoman30 
Nous sommes déjà en train de modifier la source french-stream.lol pour s'ajuster aux dernières évolutions du site 👍🏻

**Comment by lesueurnicolas27** [comment]
n
[README.md](https://github.com/Kodi-vStream/venom-xbmc-addons/files/13752762/README.md)

**Comment by yodidon** [comment]
French stream lol a changé d'url et en a profité pour passer à cloudflare je sais pas si, pour le moment, c'est utile d'aller plus loin

**Comment by Mokoman30** [comment]
Ba ça marche niveau film pourtant pour le moment 
J’ai pas eu le cloudflare 
il y a que côté série qui marche pas 

mais sizanic est son équipe sont sur le coup 
Donc c est parfait

**Comment by sizanic** [comment]
> mais sizanic est son équipe sont sur le coup

yodidon fait partie de l'équipe 😄 

@yodidon, l'adresse que j'utilise pour cette source (.moe) ne me propose pas de cloudflare non plus 🤔 
j'ai bien avancé pour les séries.

**Comment by yodidon** [comment]
> > mais sizanic est son équipe sont sur le coup
> 
> yodidon fait partie de l'équipe 😄
> 
> @yodidon, l'adresse que j'utilise pour cette source (.moe) ne me propose pas de cloudflare non plus 🤔 j'ai bien avancé pour les séries.

Bah moi il me bascule sur .hair …🥹

**Comment by yodidon** [comment]
[Capture vidéo du 24-12-2023 17:59:42.webm](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/39896943/5adee8d9-d7da-404e-b503-b0148794bad9)

**Comment by yodidon** [comment]
Mais effectivement si je passe en navigation privée ça ne me redirige pas

**Comment by Mokoman30** [comment]
> Bonjour la team J’ai quelque soucis Concernant Gum Gum streaming No item ne marche plus alors que le site marche
> 
> French stream (anime) aucun lien marche d aucun anime ianimes : Aucun hébergeur marche Dood a disparu alors qu’il est fonctionnel sur site Neko sama quand je choisi un épisode peu importe l anime sa me met No item
> 
> toon anime qui plante il me met Connection fail invalid Url quand je choisi n’importe quel épisode d un anime
> 
> VoirAnime qui me propose du captcha qui mène au final pas à l épisode a un no item a chaque fois
> 
> Vostfree No item ne marche plus
> 
> Merci la team

**Comment by sizanic** [comment]
le site 33series connu par vStream n'existe plus à cette adresse 🤔

**Comment by yodidon** [comment]
Gum gum je regarde mais j’avoue je galère…

**Comment by sizanic** [comment]
Retour de la source FrenchStream.lol avec la version 2.7.5 de vStream 👍🏻

**Comment by sizanic** [comment]
@MisuIancu 

> J’ajouterai aux commentaires de Mokoman qu’il y a des sources qui semble figés, pas des nouvelles séries depuis longtemps. Cinemay, Films et Videos, French-stream , 01 Streaming en font partie. Merci et bonne continuation!

La source FilmsEtVideos propose maintenant des nouveautés plus pertinentes dans la version 2.7.5 de vStream 👍🏻

**Comment by Mokoman30** [comment]
Merci l équipe 

J’ai un problème 

sur mon android tv Sony j’ai la maj 2.7.5 j ai toute les  sources french stream lol toute est bon 

Et sur la box android maj 2.7.5  mais j’ai plus french stream lol et les autres [
![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/46374635/038c265d-911d-4b43-92a3-2dff5df989ce)
](url)

Je comprends pas pourquoi

**Comment by sizanic** [comment]
L'apparition des sources est independantes de la mise à jour des versions, la source devrait apparaitre rapidement d'ici quelques heures. (après quelques redemarrage).

Et s'assurer qu'elle est bien activée dans les parametres de vStream.

**Comment by Mokoman30** [comment]
Elle n’est pas dans la liste des sources à activer  désactiver la source  frenchstreamlol c est le seul qui manque c est étrange 

J’espère d ici quelque heurs en tout cas 

Merci en tout cas l équipe

**Comment by Mokoman30** [comment]
Toujours pas de French Stream lol sur ma box android contrairement à ma tv android ou il y figure après plusieurs redémarrage kodi 

je comprends pas  c est la même Maj sur les 2 support 
En Maj auto en + les 2 
Comme toujours 
Je sais plus quoi faire à part attendre

**Comment by sizanic** [comment]
Il faut encore attendre.

J'ai précisé "quelques heures" pour être optimiste, sachant que la période pour mettre à jour les sources est tous les 3 jours.
Ce serait vraiment pas de chance si la dernière mise à jour des sources venait d'être effectuée chez toi juste 1 heure avant, et que tu doives vraiment attendre 3 jours !

**Comment by Mokoman30** [comment]
Ahhh d’accord 
Mince je comprends mieux maintenant 
Merci Sizanic 

merci l équipe 
Passez de bonne fêtes
