### ISSUE TITLE
1Fichier Vstream

### ISSUE THREAD

**Issue by pimpampoum2** [Kodi-vStream/venom-xbmc-addons#4141]
Bonjour Depuis quelques joursje constate des anomalies : impossible de me connecter a mon compte 1fichier et je n'ai plus accès aux vidéos a la demande , j'obtiens le message aucun élément comme pour 1fichier. Seuls fonctionnent TV tnt et Radio
ma config:
os:Android
Appareil T95
Kodi: 20.2
Vstream : 2.7.3
autre chose j'avais mis des films en favoris avant le problème et ceux ci sont toujours accessibles
Merci pour vos conseils

**Décrivez le bug**

**Votre system**
- OS: [Windows, Android]
- Appareil: [nvidia shield, Ultra]
- Version Kodi: [16.17.18]
- Version Vstream: [1.7.0]

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

**Comment by pimpampoum2** [comment]
Bon j'ai desinstallé Vstream et reinstallé tout fonctionne a nouveau

**Comment by sizanic** [comment]
super, parce qu'on avait aucune idée de comment t'aider 😄
