### ISSUE TITLE
Besoin d'aide pour CloudScraper

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#4147]
Bonjour,

Je ne suis pas capable de decoder ce lien protege par CloudFlare:

hxxxs:// www1.bookys-ebooks.com /romans/policier-suspense?page=1

Est ce qu'il y a un lib qui peut decoder correctement ce lien?

Merci d'avance de votre aide.

**Comment by chrysal** [comment]
Bonjour, 
Je dirais que le site est devenu : https://www2.bookys-ebooks.com/romans/policier-suspense?page=1
Il est possible de lire des ebooks au travers de vStream ?
