### ISSUE TITLE
Téléchargement lent

### ISSUE THREAD

**Issue by rjousse18** [Kodi-vStream/venom-xbmc-addons#4149]
Bonjour,

C'est normal que les téléchargement depuis vstream soient si lent ? Dès que j'essaie de télécharger un film ça doit télécharger à même pas quelques mb/s alors que si je télécharge le même lien depuis mon navigateur je suis à 100mb/s.

C'est un bug ? ou une limitation de kodi ? ou alors j'ai pas activer l'option qui résout tout par magie ?

Merci d'avance.

**Comment by sizanic** [comment]
Bonjour.
Oui c'est normal.
vStream est une solution de streaming, pas une solution de téléchargement.
La possibilité de télécharger est proposée pour améliorer l'expérience de streaming en donnant la possibilité de précharger quelques minutes avant de lancer la lecture. Cette fonction "télécharger et lire" est utile pour les équipements limitées en debit.

**Comment by rjousse18** [comment]
Ha je vois, merci pour les éclaircissements !
