### ISSUE TITLE
Nouvelle source qui ne s'affiche pas dans les source de VSTREAM 

### ISSUE THREAD

**Issue by airfmessoual** [Kodi-vStream/venom-xbmc-addons#4150]
J'ai ajouté une nouvelle source dans les site de vstream et quand je démarre kodi et que je vais vers vstream, toute les source , je ne trouve pas la nouvelle source que j'ai ajouté sachant que j'ai placé mon fichier.py dans le répertoire sites et que je les déclaré dans le fichier sites.json

**Comment by sizanic** [comment]
Je me permet de fermer cette demande.
Tu as été aidé depuis pour la création de la référence de la source à créer dans le fichier sites.json.
