### ISSUE TITLE
Bloqué sur chargement 

### ISSUE THREAD

**Issue by Tyk56** [Kodi-vStream/venom-xbmc-addons#4151]
Bonjour tout fonctionnais bien et depuis ce matin dès que je fais une recherche ça reste bloqué sur changement en continue j’ai désinstallé kodi et tout réinstaller rien n’y fait avec vous une idée ?

**Comment by sizanic** [comment]
Bonjour,
Recherche de film ou de séries ?

Essaies de désactiver la source dont le nom reste visible sur la barre de progression.

**Comment by DaX59** [comment]
Salut, 
J'ai eu le tour cette après midi. J'ai désactivé french stream lol et wiflix. Les recherches ont refonctionné ensuite

**Comment by Tyk56** [comment]
Ça a fonctionné merci beaucoup
