### ISSUE TITLE
wfilix source introuvable dans la recherche de film par libellé, j'ai pourtant accès à la source quand je vais dans mes sources

### ISSUE THREAD

**Issue by iqueezh** [Kodi-vStream/venom-xbmc-addons#4156]

**Comment by sizanic** [comment]
Bonjour.
C'est normal.
Comme plusieurs autres sources, elle n'est plus sollicitée pour la recherche mais reste disponible en accès direct.
Car elle bloque la recherche dans beaucoup de cas, chez plusieurs personnes.

**Comment by iqueezh** [comment]
Bonjour,
Cela veut dire que je ne peux plus rechercher de film sur wiflix ?

**Comment by sizanic** [comment]
Non.
Certaines sources ne font plus partie de la recherche globale, mais il est toujours possible de rechercher en se rendant directement dans la source.
vStream/vod/films/sources/wiflix/rechercher.

**Comment by iqueezh** [comment]
Ah, chez moi quand je vais dans les sources et que je recherche je ne trouve rien, le site wiflix est surement HS sur vstream pour le moment

**Comment by sizanic** [comment]
A part la protection CloudFlare, Wiflix sur vStream n'est pas HS.

Il suffit de se rendre dans "Wiflix/ films( derniers ajouts)" pour constater que les films sont présents et peuvent être lus 🤔 

Et le chemin pour une recherche dans wiflix est plutôt : 
vStream/Outils/Toutes les sources/wiflix/Recherche Film.

Mais il est vrai que la recherche ne semble pas fonctionner 👍🏻

**Comment by bibiche67** [comment]
Chez moi dans wiflix/Films dernier jour je n'ai aucun film. Rien ne fonctionne de mon côté pour wiflix et french stream lol

**Comment by yodidon** [comment]
@bibiche67  tu as bien installé  dnspython (il est sur le repo vstream) ?

**Comment by bibiche67** [comment]
Salut oui j'ai bien dnspython. Wiflix est revenu mais pas french stream lol malheureusement.

**Comment by sizanic** [comment]
Pour passer les blocages "CloudFlare" de FrenchStream.lo et Wiflix, voici le dernier tuto à jour : 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-passer-CloudFlare

**Comment by pasnox** [comment]
no way

**Comment by chrysal** [comment]
Bonjour, 

Il est possible que vous ayez le même problème que moi.
J'ai poussé une PR #4219 qui resoud le soucis chez moi.

Cordialement,
