### ISSUE TITLE
Proposition d'ajout 

### ISSUE THREAD

**Issue by M0rn1ng574r** [Kodi-vStream/venom-xbmc-addons#4159]
Je vous propose de rajouter cette source parmi votre bibliothèque : 

https://www.lookmovie2.to/

 j'ai remarqué d'ailleurs qu'il y a de moins en moins de sites sources disponibles je vous proposerai quelques-uns à l'avenir

**Comment by sizanic** [comment]
Merci pour cette proposition, nous allons l'ajouter dans la liste avec les autres à analyser : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4103
😄

**Comment by sizanic** [comment]
Les films ne sont pas en français
