### ISSUE TITLE
Proposition d'ajout

### ISSUE THREAD

**Issue by ceux70** [Kodi-vStream/venom-xbmc-addons#4167]
bonjour a vous

voila quelques sites en fullhd
filmscultes.online point négatif pas trouver mode recherche 
seriescultes.homes
fastream.re
1jour1film.homes point négatif pas trouver mode recherche
videofutur.online point négatif pas trouver mode recherche
vu que maintenant pastebin est obsolète avec la perte de uptobox et darkibox rame sur kodi et pas moyen d activer sous titre ect 
je pense que vstream devrais retrouver ces fondamentaux  pas avoir de compte de darkibox ect avoir des sites gratuit et de bonne qualité 
apres ces facile pour moi de dire cela j imagine meme pas le travail considérable que vous faites 
cordialement

**Comment by yodidon** [comment]
j'ai l'impression que le hoster de fastream est protégé par cloudflare, je n'arrive pas a aller plus loin

**Comment by sizanic** [comment]
Ces propositions font partie d'une liste qu'on va regarder. Encore merci.
