### ISSUE TITLE
Problème Anime 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#4168]
Bonjour la team tout d abord bonne année à vous tous 

J’ai quelque soucis Concernant

- Gum Gum streaming No item ne marche plus alors que le site marche

- French stream (anime) aucun lien marche d aucun anime ( Faudrais le supprimer) 

- Neko sama No item sur tout le catalogue d anime proposer 

- VoirAnime qui me propose du captcha qui mène au final pas à l épisode a un no item a chaque fois

- Vostfree Bug loading ultra lent impossible à accéder a l anime 

et si possible d ajouter de nouveau site d anime Merci la team

**Comment by Mokoman30** [comment]
https://anime-sama.fr/  
https://www1.jetanimes.com/ 
Les meilleurs

**Comment by Mokoman30** [comment]
ianimes No item 
Car ianimes a changer d url 
C est https://www.ianimes.one/index.php

Merci 

@sizanic

**Comment by sizanic** [comment]
@Mokoman30 

Merci, c'est changé 👍🏻

**Comment by sizanic** [comment]
Anime-Sama vient d'être ajouté à la version 3.2.0 de vStream.
