### ISSUE TITLE
Tres peu de sources en resultats de recherche

### ISSUE THREAD

**Issue by Nico2501Rab** [Kodi-vStream/venom-xbmc-addons#4172]
Bonjour,
J'utilise Vstream depuis longtemps sans vraiment maitriser le sujet. Je viens vers vous aujourd'hui car sur tous mes appareils utilisant vstream j'ai le meme soucis.
Lors de mes recherches j'ai peu de retour, tres peu de sites/sources me renvoi quelque chose. Au mieux j'ai 3 sites qui me donnent quelque chose mais la plupart du temps aucun ne fonctionnent. J'ai 52 éléments dans la liste de sources qui sont activés. Cela se produit sur tout type de recherche meme sur des films ou series tres courants.

**Votre system**
- OS:Android
- Appareil: nvidia shield
- Version Kodi: [20.2.0]
- Version Vstream: [2.7.5]

Merci par avance

**Comment by sizanic** [comment]
Bonjour,

cette question sur le manque de résultats est souvent posée, je te renvoi sur une de mes anciennes réponses : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4081

**Comment by Nico2501Rab** [comment]
> Bonjour,
> 
> cette question sur le manque de résultats est souvent posée, je te renvoi sur une de mes anciennes réponses : #4081

Merci pour ton retour, j'avais deja consulté ce thread. DNS python est bel et bien installé depuis longtemps sur tous mes appareils. Existe t il un moyen de verifier qu il est installé comme il faut ?

**Comment by sizanic** [comment]
Tu peux vérifier que DNSPython est bien installé depuis la fenetre d'informations/dépendance de vStream : 
![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/47307622/439c95de-076f-402e-86d8-df91166ac11f)


<br><br><br>
MAIS il arrive maintenant que DNSPython ne soit plus suffisant pour contourner les blocages des operateurs.

Et DNSPython ne fonctionne que pour les adresses IPV4.

Il faut alors modifier ces paremètres DNS pour en utiliser un pour des adresses IPV6.

Tu peux suivre le 2e chapitre ici "Change tes DNS!" : 
https://lesalkodiques.wiki/categorie/changer-ses-dns/

**Comment by Nico2501Rab** [comment]
Merci je regarde ça ☺️
    Envoyé à partir de Outlook pour iOS
  

 De : sizanic ***@***.***>Envoyé : mardi, janvier 16, 2024 2:09 PMÀ : Kodi-vStream/venom-xbmc-addons ***@***.***>Cc : Nico2501Rab ***@***.***>; Author ***@***.***>Objet : Re: [Kodi-vStream/venom-xbmc-addons] Tres peu de sources en resultats de recherche (Issue #4172) 
Tu peux vérifier que DNSPython est bien installé depuis la fenetre d'informations/dépendance de vStream :
image.png (view on web)

MAIS il arrive maintenant que DNSPython ne soit plus suffisant pour contourner les blocages des operateurs.
Et DNSPython ne fonctionne que pour les adresses IPV4.
Il faut alors modifier ces paremètres DNS pour en utiliser un pour des adresses IPV6.
Tu peux suivre le 2e chapitre ici "Change tes DNS!" :
https://lesalkodiques.wiki/categorie/changer-ses-dns/

**Comment by sizanic** [comment]
@airfmessoual 
Tu vois mes messages ?

**Comment by Nico2501Rab** [comment]
Désolé j ai mis un peu de temps avant de pouvoir tester.
Cela semble bien mieux avec un autre dns.
Merci beaucoup
