### ISSUE TITLE
Recherche globale

### ISSUE THREAD

**Issue by Bibohead** [Kodi-vStream/venom-xbmc-addons#4179]
**Votre demande de fonctionnalité est-elle liée à un problème ?
Bonjour a tous
Depuis la modification des sources dans la recherche globale de vstream, jen n’ai plus que 8 sources avec pastebin qui remontent des resultats ( tout au moins qui sont parcourues lors de la recherche)

Les autres sources comme wiflix sont toujours actives et si on passe par le menu outils on trouve des films et series ( quoique la recherche semble ne pas fonctionner correctement pour wiflix…?)

**Décrivez la solution que vous souhaitez**
Y aurait-il une possibilité de remettre manuellement les sources voulues dans cette recherche globale ( film ou series, …) , comme auparavant on désactivait une source trop lente a remonter des résultats et pas toujours pertinents, car meme en les activant dans les paramètres/sources de vstream elles ne remontent pas lors d’une recherche globale films ou series.
je comprends le fait de limiter les sources pour accélérer les recherches mais selon les configurations certaines peuvent être rajoutées sans nuire au résultat.

bibohead

**Comment by Bibohead** [comment]
Ok merci
Je vais essayer d.activer flaresolverr et voir ce que ça me remonte… je vous tiens au courant

**Comment by Bibohead** [comment]
J’ai cependant remarqué qu.au fil des jours le nombre de spurces augmentent cependant je ne vois plus de mise a jour ( en vert en ligne du haut ) comme auparavant 
Mais des sources sont régulièrement ajoutées quand meme

**Comment by Bibohead** [comment]
Je suis passé de 8 a environ une quinzaine

**Comment by sizanic** [comment]
> je ne vois plus de mise a jour ( en vert en ligne du haut ) comme auparavant

ça doit bien faire 3 ans que cette fonctionnalité a été retirée, maintenant les mises à jour sont complètement automatique 😉 
<br>
> Je suis passé de 8 a environ une quinzaine

C'est pour ça que je te déconseille de te lancer dans la mise en place de flaresolverr.
Avec la dernière version, les résultats de la recherche globale est améliorée.

**Comment by sirop2** [comment]
Bonjour ! Peut on peut réactivé wiflix dans la recherche globale sans passer par le flaresolver ?

**Comment by sizanic** [comment]
Pour beaucoup wiflix nécessite flaresolver.
Alors cette source ne sera pas remise dans la recherche globale.
Que tu aies besoin ou pas de flaresolverr pour accéder à wiflix, tu sera obligé de passer directement par la source.

Ce n'est pas nous qui décidons s'il faut utiliser FlareSolverr, c'est le site qui met en place une protection ClouFlare.

**Comment by sirop2** [comment]
Oui je sais il y'a des jours ou cloudflare est actif sur wiflix le week-end surtout surement à cause de la grande affluence, dommage qu'on ne puisse pas choisir les site dans la recherche globale, car wiflix est le site avec le meilleur catalogue tenu à jour avec des liens qui fonctionne , ces derniers temps que je fais des recherches je tombe que sur des site avec liens morts 😞.

**Comment by sizanic** [comment]
Les liens de la source kepliz proposent de la HD pour les films.
Ensuite il y a toujours la source privée Pastebin si on veut se garantir de bons liens.

**Comment by sirop2** [comment]
Merci je vais m'intéresser à pastebin dans se cas !

**Comment by sirop2** [comment]
Je suis tombé sur un vieux post ou un lien discord était partagé est-il toujours actif ?

**Comment by sizanic** [comment]
Pour le Discord de vStream, c'est celui-là : https://discord.gg/KRsDT7PNHN

Mais si tu veux t'interesser à Pastebin, il faut te rapprocher de la communauté "les alKODIques".
vStream ne propose pas de contenu dans la source Pastebin, il faut ajouter des codes qui donnent accès à du contenu privé.

Les alKODIques partagent un pack de codes (code films, code séries, japanime, doc, reportage, séries, concerts, ...)

Leur Discord : https://discord.gg/3RTRvT2PSE
Leur site : lesalKODIques.com
facebook : https://www.facebook.com/groups/alkodiques

**Comment by sirop2** [comment]
Merci beaucoup pour votre réactivité et votre travail 🤩
