### ISSUE TITLE
rajout d un dossier site_beta 

### ISSUE THREAD

**Issue by neomatrix45** [Kodi-vStream/venom-xbmc-addons#4189]
serait t il possible de rajouter un dossier source genre site_beta ou site_perso  avec le fichier source json corespondant afin de ne pas subir l effacement d une  source en devloppement  dans site.json  a chaque mise a jour

**Comment by yodidon** [comment]
> serait t il possible de rajouter un dossier source genre site_beta ou site_perso avec le fichier source json corespondant afin de ne pas subir l effacement d une source en devloppement dans site.json a chaque mise a jour

Bonjour tu utilise quoi pour développer ??

**Comment by neomatrix45** [comment]
j'utilise vscode

**Comment by sizanic** [comment]
Pour ne pas subir l'écrasement du fichier sites.json, il est possible de modifier son chemin d'accès, ou de mettre en commentaire la récupération du fichier.

Voir ce code :
\resources\lib\update.py
