### ISSUE TITLE
Les films en hdlight se lance en SD

### ISSUE THREAD

**Issue by sirop2** [Kodi-vStream/venom-xbmc-addons#4191]
Bonjour je me confronte à un problème qui semble s'être installé depuis la nouvelle maj,les films et série en Hdlight, ne s'ouvre plus en Hd mais en sd comme en témoigne les photos ci joint, c'est pareil sur ma chromecast 4k ou mes appareils ios.

![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/20713597/669bce6a-8d3b-4eef-9788-bd39f9b222c3)
![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/20713597/e59b0f43-fcc2-401b-8048-194ae835b5b7)

**Votre system**
- OS: [Android,Ios]
- Appareil: [Chromecast 4k,Iphone 13 pro max]
- Version Kodi: [23.0]
- Version Vstream: [2.8.0]

**Nous devons le reproduire**

- Nom du site: wiflix.voto
- Titre du fim/serie: Wonka
- Nom du host : Uqload

**Comment by sizanic** [comment]
Je suis allé sur le site pour ce film, il y a 10 liens (dood, hqload, upstream, ...)

Ils sont censés tous être en HD ?
Comment le vérifies-tu ?

J'ai testé le lien de streaming upstream et il était en SD.
