### ISSUE TITLE
demande d'ajout

### ISSUE THREAD

**Issue by TiHabs** [Kodi-vStream/venom-xbmc-addons#4194]
Bonjour esceque c'est possible d'ajouter coolflix sur votre addon ? c'est un site de streaming dans le meme genre que buzzmonclick mais avec beaucoup plus de contenu cela serai top, je vous remercie , bonne fin de soiree

**Comment by sizanic** [comment]
Bonjour,

Merci pour ta proposition.

Coolflix fait déjà partie des sites que nous allons étudier :
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4103

**Comment by TiHabs** [comment]
Rien bien : ) Merci

**Comment by sizanic** [comment]
Nous allons remonter sa priorité dans notre liste

**Comment by sizanic** [comment]
L'équipe de ce site a pris la décision cet été de fermer le site.
