### ISSUE TITLE
Les chaines en directes ne marchent plus

### ISSUE THREAD

**Issue by KenshiroBlind** [Kodi-vStream/venom-xbmc-addons#4195]
Salut la team 
J'aimerais juste tirer votre attention sur le fait que les chaines en direct ne marchent plus depuis un bon bout de temps ( 2 semaines a peu pres), que ce soit avec l'addon daddylive ou streamonsport.

Bien de choses a vous

**Comment by sizanic** [comment]
J'en connais un qui voudrait bien voir le combat de ce soir 😆 

On a mis à jour les adresses de DaddyHD et LiveTV avant-hier.
ça devrait être mieux maintenant.

On va regarder pour streamonsport.

**Comment by KenshiroBlind** [comment]
oui c'est vrai que j'aimerais voir le combat de ce soir , merci pour l'info mais ma remarque était plus sur les chaines de sports

**Comment by sizanic** [comment]
Je parle bien de sports également (le combat de ce soir est bien du sport)

Et passer par le sport "par genre" ou directement par la chaine renvoi vers le même lien.


Je viens de tester avec succès l'accès à la chaine Bein1, par :
StreamOnSport/Chaines/Bein sport 1/Lien 4

**Comment by KenshiroBlind** [comment]
> Je parle bien de sports également (le combat de ce soir est bien du sport)
> 
> Et passer par le sport "par genre" ou directement par la chaine renvoi vers le même lien.
> 
> Je viens de tester avec succès l'accès à la chaine Bein1, par : StreamOnSport/Chaines/Bein sport 1/Lien 4

je fais la meme manip , et le lien 4 me donne un retout " no item ecris en rouge " , le lien 5 affiche bein sport 1 lien direct mais donne un retour " playback failed " 
peut etre un geo-locking ? je suis en afrique du sud .. bien que je n'avais jamais eu de soucis avec avant

**Comment by Jbla0712** [comment]
Ca a bien jamais fonctionné

**Comment by sizanic** [comment]
on fait ce qu'on peut pour maintenir les liens au fil des changements ...
