### ISSUE TITLE
Les liens japanime de otakuFr ne fonctionnent plus

### ISSUE THREAD

**Issue by Ushlake** [Kodi-vStream/venom-xbmc-addons#4202]
**Décrivez le bug**

Salut amis dev :)
Les liens japanime de otakuFr ne fonctionnent plus.
Le lien affiché en rouge est : https://about:blank
Un grand merci pour tout le travail que vous abattez/avez abattu 👏 

**Votre system**
- OS: [Android TV]
- Appareil: [TV Philips]
- Version Kodi: [20.5]
- Version Vstream: [2.8.2]

**Nous devons le reproduire**

- Nom du site: OtakuFR
- Titre du fim/serie: tous sans exception 
- Nom du host (openload/vidzi/...): tous sans exception

**Log**

**Image**

![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/153598795/6c9d7df5-1d41-4c91-b05e-64f07faf6f72)
![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/153598795/74cafe64-79dc-4112-b13f-5115f63633ff)
[](url)
**Plus**

**Comment by sizanic** [comment]
Bonjour,

nous l'avons corrigé dernièrement, ce sera rapidement disponible dans une mise à jour.

**Comment by Ushlake** [comment]
Bonjour et merci pour la réponse rapide 👍
Force à toute la team 💪🏽

**Comment by sizanic** [comment]
La nouvelle version est sortie, les liens sont de nouveau accessibles.
