### ISSUE TITLE
🖐️Darkino publie son site de streaming "DarkiVod"

### ISSUE THREAD

**Issue by victore447** [Kodi-vStream/venom-xbmc-addons#4203]
🖐️ **_Avez-vous vu ça ?_**
Il y a deux mois [Darkino](https://darkino1.top/)  à sortie son site de streaming👉 [DarkiVod](https://www.darkivod.net) avec ces sources vidéos 4k,FHD etc..sans popus et totalement gratuit.

☝️Bloquage de Cloudflare aussi pour  [DarkiVod](https://www.darkivod.net) dans Vstream ?

Merci pour la réponse.

**Comment by sizanic** [comment]
Oui, protection Cloudflare sur chaque lien !

Ce sera sans nous.

**Comment by randomlessly** [comment]
Le site n'a plus l'air d'avoir des protections Cloudflare (du moins chez moi avec des requêtes en Python, j'en ai pas besoin).

**Comment by randomlessly** [comment]
J'ai rien dit, j'ai oublié les captchas (Turnstile...)

**Comment by victore447** [comment]
👋 L'application  [ADM+](https://play.google.com/store/apps/details?id=idm.internet.download.manager.plus&hl=fr&gl=US&pli=1)
Arrive à contourner Cloudflare sur DarkiVod et extrait des liens comme ceci 👉 https://dl34.darkibox.com/hls2/12/00560/5sgno9bro3c6_x/index-v1-a1.m3u8?t=zSVKBs-L8z5Ell18A8MNtvwOJaEeTQbdMKSEzH2SiUU&s=1716987552&e=43200&f=2801713&i=0.0&sp=0&fr=5sgno9bro3c6 

[FILM CIVIL WAR 2024](https://www.darkivod.net/post/films/1087515-civil-war) Lisible dans Kodi en le créant en fichier strm et sur les navigateurs web.

-☝️En fait ce sont des fichiers (films,Séries etc..) stoker dans https://darkibox.com (hébergeur de type Uptobox) qui sont diffusés en streaming sur DarkiVod.com ensuite.

- Peut-être cela peut donner une idée à un des développeurs via la méthode de l'appli  [ADM+](https://play.google.com/store/apps/details?id=idm.internet.download.manager.plus&hl=fr&gl=US&pli=1)   ✅
