### ISSUE TITLE
Date de visionnage

### ISSUE THREAD

**Issue by bremmo76** [Kodi-vStream/venom-xbmc-addons#4204]
Bonjour,
Existe t'il un addon qui permettrait de mettre la date du dernier visionnage du média ? 
Et est ce que l'on aurait la possiblité d'agrandir la liste des ajouts récents. 
J'utilisais zappitti dont la liste n'était pas figée.
Merci

**Comment by sizanic** [comment]
Bonjour,

On ne pourra te répondre ici que pour ce qui concerne l'addon vStream.
Si tu recherches d'autres addons, essaie de voir auprès de la communautés "les alKODIques", 
facebook : https://www.facebook.com/groups/alkodiques
Discord : https://discord.gg/3RTRvT2PSE
Site : http://lesalKODIques.com


Concernant "les derniers ajouts", je pense que tu fais référence aux listes disponibles avec la source Pastebin.
(tu dois donc déjà connaître les alkodiques, car c'est sans doute auprès d'eux que tu as récupéré les codes Pastebin).

Pour augmenter le nombre d'éléments dans les menus Pastebin, tu peux modifier le paramètre "nombre d'éléments" depuis le menu "Pastebin/Gérer les contenus".

vStream propose bien une liste des visionnage en cours, elle est classée par défaut par ordre de visionnage inversé (les plus récents en premier), mais n'affiche pas la date.
Cette fonctionnalité n'est pas prévue.
