### ISSUE TITLE
Marque comme vus en selection multiple

### ISSUE THREAD

**Issue by bremmo76** [Kodi-vStream/venom-xbmc-addons#4206]
bonjour 
Désolé, mais Depuis les paramètres de vStream, dans l'onglet "Outils". je ne vois quel paramètre nous permet de faire une sélection multiple pour cocher des médias déjà vus. 

Pour information , Par rapport à mon message précédent, effectivement je ne pouvoir avoir de sauvegarde, car l'arrêt de mon application précédente m'a fait utiliser Kodi (que je regrette d'ailleurs)  et paramétrer la sauvegarde également 😊

**Comment by sizanic** [comment]
Bonjour
Il n'était pas question de faire une sélection multiples depuis les outils, mais bien de faire une sauvegarde des médias lus afin de les restaurer.

**Comment by bremmo76** [comment]
RE bonjour,
Oui, çà c'est fait la sauvegarde. C'est simplement la sélection m'intéressait si elle est possible.


Pascal LEMARECHAL

06 86 94 90 34

________________________________
De : sizanic ***@***.***>
Envoyé : mardi 2 avril 2024 09:09
À : Kodi-vStream/venom-xbmc-addons ***@***.***>
Cc : bremmo76 ***@***.***>; Author ***@***.***>
Objet : Re: [Kodi-vStream/venom-xbmc-addons] Marque comme vus en selection multiple (Issue #4206)


Bonjour
Il n'était pas question de faire une sélection multiples depuis les outils, mais bien de faire une sauvegarde des médias lus afin de les restaurer.

**Comment by sizanic** [comment]
non, la sélection multiple n'est pas possible.

**Comment by sizanic** [comment]
Aucune évolution n'est prévue dans ce sens prochainement.
