### ISSUE TITLE
Aucun élément après sélection d'un hébergeur sur JustStream

### ISSUE THREAD

**Issue by Pilgrim80** [Kodi-vStream/venom-xbmc-addons#4216]
**Décrivez le bug**

Lors de la sélection d'un hébergeur aucun résultat ne ressort. Message "Aucun élément" pour le site JustStream.

**Votre system**
- OS: [Windows et Android]
- Appareil: [TX3 Mini]
- Version Kodi: [20.2.0]
- Version Vstream: [2.9.1]

**Nous devons le reproduire**

- Nom du site: JustStream
- Titre du fim/serie: Jules
- Nom du host (openload/vidzi/...): tout host confondus

**Log**

**Image**

![image](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/91007206/dc0ad06f-9c6f-4997-964f-c1cf327ea8ad)

**Plus**

Lorsque l'on se rend via un navigateur web sur e site JustStream, aucun souci pour lire la vidéo.
En revanche, depuis Vstream, le résultat est toujours "Aucun élément".

**Comment by sizanic** [comment]
Bonjour,

Lorsque tu passes par un navigateur, tu remarqueras une petite de fenêtre "Cloudflare" avant le démarrage de la vidéo.

C'est une protection que vStream ne sait pas contourner.

Donc pour l'instant cette source va être désactivée.

**Comment by Pilgrim80** [comment]
@sizanic : Bonjour. Merci pour ce retour d'information.
