### ISSUE TITLE
Wiflix - Nouvelle adresse

### ISSUE THREAD

**Issue by khalistoo** [Kodi-vStream/venom-xbmc-addons#4224]
nouvelle adresse de wiflix: https://wiflix.date/

**Comment by sizanic** [comment]
Merci, c'est changé 👍🏻

**Comment by khalistoo** [comment]
Merci @sizanic  pour la reactivite. 

j'ai modifie mon propre "site.json" en local, vu que je ne sais pas comment faire le build depuis github sur ubuntu... mais c'est pas bien grave, j'attendrai une release.

Ma question c'est plus de savoir ou je trouve dans le code les regex pour wiflix (ou autres sites), parce que j'imagine que le site a aussi change de layout et donc forcement ca ne semble pas marcher. 

Je vois bien la liste des series/films, je ne sais pas si ca vient d'une autre source que le site lui meme mais aucun liens, 0 items, peu importe la video. (en tout cas ni sur android ni sur ubuntu) 

Je n'ai pas d’expérience avec les addon mais je touche un peu ma bille en regex et python donc si je peux aider...

**Comment by sizanic** [comment]
en effet, le changement d'adresse n'a pas suffit.

La regex pour les liens est là : 
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/0b4878f58a6138511044e4521eaf143775e00c1f/plugin.video.vstream/resources/sites/wiflix.py#L346

**Comment by sizanic** [comment]
J'ai modifié les regex, ce sera lors de la prochaines mise à jour de vStream.
Prévu dans moins d'une semaine.

**Comment by sizanic** [comment]
La version 2.9.3 de vStream vient de sortir et contient cette évolution.
