### ISSUE TITLE
Wiflix ne fonctionne plus .

### ISSUE THREAD

**Issue by ktm520** [Kodi-vStream/venom-xbmc-addons#4225]
Bonjour a tous , Wiflix ne fonctionne plus , l'URL a changé , comment faire , pour avoir accès au contenu , de Wiflix ?
Faut il faire , une mise a jour de Vstream ?
Merci d'avance  .

**Comment by sizanic** [comment]
Bonjour,
L'url a été mise à jour dans vStream.

Il faut attendre quelques temps que cette nouvelle url se propage automatiquement sur les installations.
(cela ne nécessite pas de mise à jour)

La diffusion peut prendre jusqu'à 2 jours grand maximum.
(c'est toujours moins)

Cdt.

**Comment by ktm520** [comment]
Merci beaucoup .

**Comment by ktm520** [comment]
Je viens de verifier  , j'ai le message suivant  : aucun élément .

**Comment by sizanic** [comment]
voir ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4224
