### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by i300220** [Kodi-vStream/venom-xbmc-addons#4226]
Bonjour,

Merci pour cette extension.

Juste une suggestion pour un site qui en vaut la peine.  Je cherchais un film recemment et je ne l'ai pas trouve avec votre extension.  Je suis alors alle sur _cpasmieux.is_ et ils l'avaient.  Ils ont pas mal tous les films et series via _uqload_ et _vidoza_ plus d'autres qui ne fonctionnent jamais comme netu.

Ils sont tres resilients.  Des que leur site est ferme, ils en ouvrent un autre, qui semble toujours deja pret avec un autre extension de domaine.  Il y a peu de temps, c'etait _cpasmieux.casa_, puis _cpasmieux.es_.

Si je ne me trompe leur site est base sur feu  [libertyland_tv.py](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/trash/libertyland_tv.py)

**Comment by sizanic** [comment]
Bonjour,

Ce site a en effet bonne réputation.
Il fait bien partie de ceux que nous aimerions intégrer prochainement.

**Comment by i300220** [comment]
https://fstream.one/ est egalement tres a jour et particulierement fort a filtrer les 1xbet.  j'ai reussi a voir une version impeccable du comte de monte-cristo (2024).  Si vous ne deviez voir qu'un film en 2024, c'est celui-la que je suggere.  Tres fidele au pretigieux roman meme s'il saute des bouts, ce qui est comprehensible, le roman faisant plus de 1000 pages.

**Comment by sizanic** [comment]
Bonsoir,

je te confirme qu'on travaille sur l'integration de cpasmieux.
Quant à ce site, il s'agit d'une copie d'un autre site french-stream sur lequel nous travaillons également.

Ces 2 sites seront bien dans la prochaine version de vStream.
Merci pour ces 2 propositions.

**Comment by sizanic** [comment]
Bonjour @i300220 ,

comme annoncé, les sites que tu proposais, cpasmieux et frenchstream, sont maintenant disponibles dans la version 3.0 de vStream.

**Comment by i300220** [comment]
Excellent boulot! Je teste depuis 2 jours et tout fonctionne a merveille.  La version 3 constitue un avancement majeur, tout particulierement pour la recherche.  Un gros merci a l'equipe!
