### ISSUE TITLE
impossible de changer de page dans la watchlist tmdb

### ISSUE THREAD

**Issue by xonsap** [Kodi-vStream/venom-xbmc-addons#4233]
**Décrivez le bug**
Impossible de changer de page dans la watchlist tmdb via mes contenus > mes comptes > tmdb > films (liste de suivi).
Lors du click sur *page 2 >>>* rien ne se passe

**Votre system**
- OS: LibreElec
- Appareil: RPI5
- Version Kodi: 20.3
- Version Vstream: latest

**Comment by sizanic** [comment]
Bonjour,

Merci pour l'information, on va regarder.

**Comment by sizanic** [comment]
@xonsap 
Je n'ai plus constaté de souci de pagination TMDB avec la dernière version 3.0 qui vient de sortir.
