### ISSUE TITLE
vStrem dans stremio

### ISSUE THREAD

**Issue by DarabT** [Kodi-vStream/venom-xbmc-addons#4235]
Bonjour,

Après des années d'utilisation de codes open-source de la communauté github, je décide d'essayer de participer.

Cela fait un moment que j'utilise vStream sur kodi (que j'adore), mais c'est insupportable sur android kodi crache tout les deux lancement. J'ai décidé donc (contre mon gré) de voir quel autre solution était possible, et c'est là que je tombe sur stremio, outil assez complet avec sync entre plusieur appareil, etc... je le teste rapidement avec l'addon "torrentio" (et real-debrid) une vrai merveille une fois configuré sur PC, il suffit juste de se connecté pour avoir les addons (porsuivre la lecture ...etc). En revanche deux problemes: 
- le contenu principalement anglophone (que je n'avais pas avec vStream)
- et la limitation à un seul écran (que je n'avais pas avec vStream)

Vous me voyez venir, j'ai décidé donc de regarder le code source de vStream pour voir s'il est possible de transposer sur stremio, le code est en python pas mon point fort malheureusement. J'ai décider de découper le problème en plusieurs petites parties, en premier j'ai pris un épisode au pif d'une série, avec le navigateur et l'extension IDM j'ai récupéré le lien direct de la video, et je l'ai mis dans un addon stremio fait à l'arrache, Test OK l'épisode se lance bien.

**La deuxième test:** peut-on lancer un script python depuis un addon stremio et récupérer des infos de ce script? La réponse est oui j'ai fait un script rapide qui renvoi le lien direct de l'épisode (écris en dur dans le script). et le test est "OK" à coup de "const spawn = require("child_process").spawn;" et "const pythonProcess = spawn('python', ["Python_Script/main.py"]);"

**Le troisième test (celui où je bloque actuellement) :** faire un mini script python pour choper le lien direct de la video (je présume que vStream, est capable de retourner un lien comme IDM, non ?), (à coup de lignes commentées et des print dans tout les sens, j'avais dit que python c'est pas mon point fort) On donnent un lien vers la page de l'épisode j'arrive à choper le lien des lecteurs, notamment un lien sibnet (mes essais se concentrent sur ce lien donc) et j'ai tout simplement recopié une partie du code: 
`def showHosters():
    sUrl = 'XXXXX' #lien vers l'episode

    oParser = cParser()
    oRequestHandler = cRequestHandler(sUrl)
    sHtmlContent = oRequestHandler.request()

    sStart = 'class="eps" style="display: none">'
    sEnd = '/div>'
    sHtmlContent = oParser.abParse(sHtmlContent, sStart, sEnd)
    
    # Pour les liens myvi
    sHtmlContent = sHtmlContent.replace('!//', '!https://').replace(',//', ',https://')

    sPattern = '(https:.+?)[,|<]'
    aResult = oParser.parse(sHtmlContent, sPattern)

    if aResult[0]:
        for aEntry in aResult[1]:

            sHosterUrl = aEntry` 

Mais je n'arrive pas à passer cette étape, pour choper le "vrai" lien du stream http. et la forte dépendance avec les import "xbmc" ne m'aide pas à comprendre le code.

Pensez-vous que c'est possible ? si ça trouve vStream ne peut pas retourner le même de lien qu'IDM ?
Transformer vStream, en lib serait une tache facile ? (je ne penses pas, mais je pose la question dans le doute)
et l'idée de cette lib est deux action :
- On lui donne une page web, elle nous listes les lecteur (ce que j'ai à peu près pu faire)
- On lui donne un lecteur elle nous retourne le lien direct (la où je bloque)

Merci de vos réponse par avance.

Pour ceux que ça intéresse, mon idée final est d'avoir un serveur avec l'addon pour stremio et deux script python:
- le premier script python (exécution journalière): dans une liste de site venir lister tout les épisode/film/anime avec leur liens vers lecteur, save le tout dans une db.
- le deuxième script python (qui viendra donc remplacer mon script qui retourne un lien fix): ce script vient depuis la db faire lien entre épisode/film/anime souhaité et son lien de lecteur et de retourner depuis ce dernier le lien direct.

ce qui devrait alléger pas mal l'attente de réponse du script python depuis node.js.

**Comment by sizanic** [comment]
Salut,

Partir sur tout ça parce que ta version d'Android plante une fois sur deux n'est déjà pas une bonne raison.
Mon kodi Android plante une fois par mois avec une utilisation quotidienne. (donc une fois sur 30)

Ensuite, si tu enlèves de vStream toute la partie d'intégration dans kodi, il ne fait que parcourir les pages des sites pour retrouver les liens.
Pour chaque site, parce qu'ils sont construit différemment, il doit analyser la page d'une façon différente.
Pour cela, il utilise des expressions régulières.

C'est vraiment la seule partie qui est intéressante à récupérer si tu veux refaire un développement dans un autre langage. Surtout que les expressions régulières ne dépendent pas du langage.

Il n'est pas intéressant d'essayer de conserver du code python de vStream si tu dois développer dans un autre langage.


Enfin, nous n'envisageons pas de modifier vStream pour qu'il soit utilisable autrement qu'en tant qu'extension de Kodi.

**Comment by DarabT** [comment]
Salut,

Merci de ton retour;

`Partir sur tout ça parce que ta version d'Android plante une fois sur deux n'est déjà pas une bonne raison.`
pour moi c'était une raison suffisante 😅.

`Pour chaque site, parce qu'ils sont construit différemment, il doit analyser la page d'une façon différente.
Pour cela, il utilise des expressions régulières.

C'est vraiment la seule partie qui est intéressante à récupérer si tu veux refaire un développement dans un autre langage. Surtout que les expressions régulières ne dépendent pas du langage.`

Je m'acharne sur le code vstream pour rien alors 😂(du moins une partie, car la partie expression régulière pour analyser la page et chopper les différent hébergeur et lien est **utile**). 
Ce n'est pas l'addon vStream qui converti le lien :
"https://video.sibnet.ru/shell.php?videoid=3343XXX" à un lien du type : "https://cvs17-2.sibnet.ru/31/54/04/3154XXX.mp4?st=NOlb1R0xhz4fev6JfX0cGA&e=1723480000&stor=45&noip=1" (lisible directement par stremio, ce lien je l'obtient avec IDM).

C'est kodi qui arrive à gérer directement un lien du premier type ?

J'ai tenter de mettre à disposition le lien "https://video.sibnet.ru/shell.php?videoid=3343XXX" à youtube-dl un autre dépôt python, il arrive bien à lancer le téléchargement de la vidéo avec l'option "-g" (geturl) j'obtient un "https://video.sibnet.ru/v/526b8a7880ab53738ef2bce43e31c5f0/3343XXX.mp4" j'ai l'impression qu'il me manque une une sorte de "clé" comme pour le lien obtenu par "IDM"

Merci d'avoir pris le temps de me répondre :)

**Comment by sizanic** [comment]
> > Partir sur tout ça parce que ta version d'Android plante une fois sur deux n'est déjà pas une bonne raison.`

>pour moi c'était une raison suffisante 😅.

oui, bien sûr, mais ce que je voulais dire c'est qu'il fallait plutôt essayer de résoudre le souci de plantage.

**Comment by sizanic** [comment]
> Ce n'est pas l'addon vStream qui converti le lien :
"https://video.sibnet.ru/shell.php?videoid=3343XXX" à un lien du type : "[https://cvs17-2.sibnet.ru/31/54/04/3154XXX.mp4?](https://cvs17-2.sibnet.ru/31/54/04/3154XXX.mp4?st=NOlb1R0xhz4fev6JfX0cGA&e=1723480000&stor=45&noip=1)

vStream ne "convertie" pas, il parcourt les liens jusqu'à trouver un lien avec une extension "mp4" ou "avi".
Il passe d'une page à l'autre avec des expressions régulières.

Pour cet exemple, il faut utiliser l'expression régulière qui recherche le lien entre guillemets qui suit "{src : ".

![image](https://github.com/user-attachments/assets/c4064a64-03c2-489f-9315-cde791d709dc)

**Comment by DarabT** [comment]
> vStream ne "convertie" pas, il parcourt les liens jusqu'à trouver un lien avec une extension "mp4" ou "avi".
> Il passe d'une page à l'autre avec des expressions régulières.
> 
> Pour cet exemple, il faut utiliser l'expression régulière qui recherche le lien entre guillemets qui suit "{src : ".

Bon, après avoir examiné le code de "youtube-dl", j'ai finalement réussi à obtenir un lien direct généré automatiquement et à l'injecter dans l'addon de Stremio (c'est une petite victoire, mais c'est toujours bon à prendre). Le code utilise la bibliothèque youtube-dl avec plusieurs conditions "if" court-circuitées (ce n'est pas très propre). C'est grâce à l'import de la bibliothèque "urllib" que j'obtiens le lien avec la signature/clé, etc.

J'ai remarqué que la bibliothèque "urllib" est également utilisée par vStream, donc il est possible de rendre le code encore plus propre.

Il ne me reste plus qu'à trouver le temps pour examiner tout cela 
et ajouter un script pour créer une base de données.

> C'est vraiment la seule partie qui est intéressante à récupérer si tu veux refaire un développement dans un autre langage. Surtout que les expressions régulières ne dépendent pas du langage.

C'était dans l'optique de ne pas avoir à réinventer la roue et de n'avoir qu'un seul code à maintenir.

**Comment by DarabT** [comment]
j'ai miss click 😅

**Comment by sizanic** [comment]
Je ne sais pas ce que je peux récupérer de cet échange.

Il est question dans la demande initiale d'une limitation concernant la reprise de la lecture.
Cela est maintenant possible en version 3 (avec l'aide de trakt).

C'est ce que nous allons faire avec vStream, ajouter constamment de nouvelles fonctionnalités.

**Comment by DarabT** [comment]
Salut,

Après une longue absence, j'ai enfin pu avancer sur le sujet. Deux points m'ont fait perdre beaucoup de temps :

- J'ai réalisé que mon idée de départ s'appler  "scraper" un site web, mais j'ai constamment été banni. J'ai essayé différentes méthodes sans succès : soit le site me bloquait pour requêtes excessives 😒 (😂), soit les nouveaux films/séries/animes n'étaient pas en haut de la liste, ce qui forçait mon script à scanner toutes les pages (une fois par jour, mais c’était long sur un raspberry pi). De plus, il fallait modifier beaucoup de code de vStream pour chaque site.

- Certains liens de streaming ne fonctionnaient pas sur Android. Après avoir perdu énormément de temps dessus, j'ai découvert que choisir un lecteur externe (MX Player dans mon cas) réglait le problème.

En résumé, voici mon brouillon : https://github.com/DarabT/vStreamIO

J'ai fais que qlq lignes sur le fork vStream, ce qui me permet de le mettre à jour facilement sans gérer de conflits.

PS : le temps de réponse actuellement est entre 8~45secondes (ce qui extrêmement long et aléatoire)

**Comment by BudTFR** [comment]
Bonjour à toi! 
Merci pour tout ce travail!
Il y a un moyen de pouvoir essayer lenvrouillon que tu as fait, le projet est tellement ambitieux
