### ISSUE TITLE
Problème avec l'intégration de Upnext

### ISSUE THREAD

**Issue by Yonn1981** [Kodi-vStream/venom-xbmc-addons#4236]
**Décrivez le bug**
Bonjour,
Il y a un problème avec l'intégration de Upnext. Cela ne fonctionne que dans la saison 1. Dans les autres saisons, il n'apparaît pas ou passe à l'épisode suivant.

Exemple :
Site : BLUEseries

Fire Country - S1 Fire Country - Episode 1 - Upnext suggère l'épisode 2 OK Upnext montre et lit l'épisode suivant.

Fire Country - S2 Fire Country - Episode 1 -  Pas de Upnext

Une idée ? Merci

**Votre system**
- OS: Windows or Android
- Version Kodi: 21
- Version Vstream: 2.9.4

**Nous devons le reproduire**

- Nom du site: BLUEseries
- Titre du fim/serie: Fire Country
- Nom du host (openload/vidzi/...): Any

**Comment by sizanic** [comment]
Bonjour,

Merci pour ce retour détaillé.
En effet, la source BlueSerie ne permet l'enchainement des épisodes au delà de la saison 1.

Nous venons d'apporter la correction.
Une mise à de vStream va d'ailleurs être disponible d'ici demain.

**Comment by sizanic** [comment]
La mise à jour 2.9.5 de vStream vient de sortir et corrige ce problème.
