### ISSUE TITLE
Proposition Anime 

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#4239]
Bonsoir la team 
J’aimerais vous faire part d un site vraiment incroyable que j’ai découvert d Anime 

https://sekai.one/
Merci de le rajouter l équipe 
Bonne soirée 

Sinon a quand la réparation de gum gum stream toujours là mais il marche toujours pas 
Merci à vous

**Comment by sizanic** [comment]
Bonjour,

Quel est le souci avec GumGum-streaming ??

https://github.com/user-attachments/assets/ce6eefe8-a13e-43d3-a5de-df27c94c7c05

**Comment by sizanic** [comment]
Merci pour cette proposition de site.
Mais il a l'air de ne proposer que la simple sélection de la page d'accueil.
Et seulement en VO.

**Comment by Mokoman30** [comment]
Ba moi sa fais plusieurs mois que sa marche pas 
Chez moi c la seul source qui me fais No item 

Uploading 74565800940__547E54B9-57B0-4E32-B43D-40B86AA6A542.MOV…

**Comment by Mokoman30** [comment]
> Merci pour cette proposition de site. Mais il a l'air de ne proposer que la simple sélection de la page d'accueil. Et seulement en VO.

Oui en effet mais si sa vous intéresse pour le côté full vostfr c est pas mal du tout pour tout ce qui sort récemment

**Comment by Mokoman30** [comment]
Bonsoir @sizanic 
Alors voilà Update de la situation 
Otakufr marche plus No item a l heur ou j écrit ses lignes sûrement une panne de leur serveur 
ianimes sous cloudflare c est embêtant 
GumGumStreaming chez moi c est No item depuis beaucoup trop longtemps alors que chez vous ça marche je n’ai pas compris pourquoi 

bref niveau Anime c est très embêtant 
j espère un correctif 
Et des ajouts svp 

merci bonne soirée

**Comment by sizanic** [comment]
Bonsoir Mokoman,

Une nouvelle version de vStream arrive dans les heures qui viennent.

Avec plus de résultats pour les Animes.

**Comment by Mokoman30** [comment]
Merci 🙏🏼

**Comment by sizanic** [comment]
tu as l'air satisfait de cette nouvelle version 😉 
ça fait plaisir.

**Comment by Mokoman30** [comment]
Effectivement j aime beaucoup il y a un large choix c est encore plus clean et organisé 
Merci l equipe
