### ISSUE TITLE
Set timeout on Requests 

### ISSUE THREAD

**Issue by khalistoo** [Kodi-vStream/venom-xbmc-addons#4240]
Search function keeps hanging, perhaps because requests doesn't come with a default timeout value. It might worth to investigate if it's possible to set it to something like 30 seconds as it's petty standard and would prevent hanging forever

**Comment by sizanic** [comment]
Bonjour,
le timeout est réglé sur 20 secondes.

Avez-vous une idée de la source concernée ?

**Comment by khalistoo** [comment]
Bonjour,  

Yes wiflix, et pour info il y a moins d'une semaine (je dirai) ca ne posait pas de soucis. 
Comme je ne savais pas que le timeout était set, je me suis permis de poster. 

Est il possible de désactiver une source de la recherche uniquement tout en la gardant accessible pour la navigation classique ?

Merci

**Comment by sizanic** [comment]
Comme wiflix est une source identifiée comme étant protégée par CloudFlare, alors d'office elle n'est pas utilisée lors des recherches.
A moins que le paramètre "Utiliser FlareSolverr" soit activé dans ta configuration.

D'une semaine à l'autre, la protection CloudFlare de wiflix n'a pas toujours le même comportement.

**Comment by khalistoo** [comment]
Ok ca doit être ca, j ai en effet flareSolverr d'active, donc comportement "expected".  
Merci pour tout

**Comment by sizanic** [comment]
En effet, dans ce cas c'est flareSolverr qui prend le relai et ça lui prend du temps de contourner CloudFlare.
