### ISSUE TITLE
Sport en direct

### ISSUE THREAD

**Issue by babeejen** [Kodi-vStream/venom-xbmc-addons#4241]
Bonjour tout le monde.

Je suis désolée si je ne suis pas au bon endroit mais je n'ai pas vraiment un bug plutôt une interrogation sur un problème rencontré avec Vstream sur Kodi installé sur un FireStick Amazon.

La version de kodi est v19.3

Je m'explique, mon ami a comme moi kodi avec Vstream sur un firestick amazon 
Lorsque le stick est connecté chez lui à son réseau wifi et à sa télé il n'a "aucun lien" en rouge qui s'affiche sur toutes les sources de sport en direct.
J'ai pris le stick chez moi pour voir s'il n'y avait pas des maj à faire et chez moi tout fonctionne correctement.
En lui rapportant, chez lui ça ne fonctionne pas...

Avez vous une idée d'où peut venir le problème ? 

Merci beaucoup pour vos lumières et votre travail !!!

**Comment by sizanic** [comment]
Bonjour,
La réponse est toute simple.
L'operateur internet de ton ami bloque l'accés à certains sites.
Pour contourner ce blocage, il faut installer l'extension DNSPython qui se trouve dans notre dépot.

Pour cela : 
- se rendre dans Kodi/Extensions/installer d'un zip.
- sélectionner le chemin du "repo vStream"
- installer l'extension module.dnsPython

**Comment by babeejen** [comment]
Merci beaucoup je vais aller lui installer !!!

**Comment by sizanic** [comment]
alors @babeejen ?
