### ISSUE TITLE
Lien kepliz - Wiflix ko

### ISSUE THREAD

**Issue by jrosette** [Kodi-vStream/venom-xbmc-addons#4244]
**Décrivez le bug**

**Votre system**
- OS: [Android]
- Appareil: [Mibox]
- Version Kodi: [20.1]
- Version Vstream: [2.9.5]

**Nous devons le reproduire**

- Nom du site: kepliz
- Titre du fim/serie: tous les films
- Nom du host (openload/vidzi/...): 

Bonjour,

Depuis 3-4 jours tous les liens de films via kepliz ne marchent plus. Le lien est bien disponible mais quand je clique dessus ça ne marche plus.
Et la source Wiflix ne me renvoie plus de films j'ai un no link

Cordialement,

Jros

**Comment by Ayuzerak** [comment]
```
def set_wiflix_url(url):
	# Nouvelle adresse URL à insérer
	nouvelle_url = url

	sites_json = '/home/linuxlite/.var/app/tv.kodi.Kodi/data/addons/plugin.video.vstream/resources/sites.json'
	# Charger le fichier JSON
	with open(sites_json, 'r') as fichier:
		data = json.load(fichier)

	# Modifier l'URL du site "wiflix"
	if 'wiflix' in data['sites']:
		data['sites']['wiflix']['url'] = nouvelle_url
		
	# Sauvegarder les modifications dans le fichier JSON
	with open(sites_json, 'w') as fichier:
		json.dump(data, fichier, indent=4)

def get_wiflix_url():
    response = requests.get("http://www.wiflix.name")
    content = response.text
    
    # Find the position of "Nom de domaine principal"
    target_position = content.find("NOS SITES")
    
    if target_position == -1:
        return None
    
    # Extract the content after the target text
    content_before_target = content[target_position:]
    
    # Use regex to find all web addresses
    web_addresses = re.findall('href="(https?://[\\w.-]+(?:\\.[\\w\\.-]+)+(?:/[\\w\\.-]*)*)', content_before_target)
        
    if web_addresses:
    	return web_addresses[0].replace("http","https") + "/" # Return the last found address after the target text
    
    return None

set_wiflix_url(get_wiflix_url())
```
Ce code permet de mettre à jour l'addresse de wiflix

**Comment by sizanic** [comment]
Bonjour @jrosette ,
Une nouvelle version de vStream vient de sortir avec une correction pour kepliz. Les liens devraient maintenant être accessibles.
Quant à Wiflix, le souci vient du site qui active parfois une protection Cloudflare.
Il n'y a alors rien à faire.

**Comment by jrosette** [comment]
Merci pour ta réponse @sizanic j'ai vu effectivement que ça remarchait depuis hier

**Comment by jrosette** [comment]
Salut @sizanic,

Maintenant les liens n'apparaissent même plus avec la nouvelle version de vstream. Est-ce que d'autres personnes ont ce bug ? 

Cordialement,

Jros

**Comment by sizanic** [comment]
Pour la source Kepliz ?
A part pour The Crow, il y a bien les liens.

**Comment by jrosette** [comment]
Bizarre j'ai installé l addon youtube et j'ai tout les liens maintenant
