### ISSUE TITLE
API key non valide pour alldebrid sur vstream

### ISSUE THREAD

**Issue by bri-mal** [Kodi-vStream/venom-xbmc-addons#4249]
Bonjour,

Ma clé API est invalide dans vstream, j'ai la certitude que celle-ci est bonne et qu'il n'y a pas de faute dans la chaine de character. Une solution, je  fait quelque chose de travers ?

Réponse : Aussi incroyable que cela puisse paraître, il faut valider votre token avec le bouton OK dans l'extension vstream.

**Comment by sizanic** [comment]
Et tu as l'air de débuter avec Alldebrid et vStream.

Saches que la seule et vraie utilité d'utiliser un compte alldebrid avec vStream est d'accéder à des catalogues privés de contenus (films et séries en fullHD et 4K) à travers la source "Pastebin".

La source Pastebin de vStream est vide par défaut.
Il faut ajouter des codes privés pour accéder à des contenus partagés par des communautés.

La communauté "les alKODIques", avec qui nous sommes partenaire, partage un pack de codes très complet (films, series, japanimés, documentaires, ...)

**Comment by bri-mal** [comment]
Bonjour merci pour ta réponse, en faite, il suffisait d'appuyer sur OK et ensuite tester le token (j'ai honte, je faisais l'inverse). J'avais déjà configuré une sources pastebin (celle que tu cite) et  je ne comprenais pas pourquoi le token n'était pas valide.
Merci pour ton temps, et bon weekend.
