### ISSUE TITLE
Chaines Streamonssport non disponible

### ISSUE THREAD

**Issue by KenshiroBlind** [Kodi-vStream/venom-xbmc-addons#4251]
**Décrivez le bug**
La recente mis a jour a enlever les chaines de sports qui etaient disponible via l'extension streamonsport

**Votre system**
- OS: [Android]
- Appareil: Mecool KD2]
- Version Kodi: [21.1]
- Version Vstream: [2.9.6]

**Plus**
 quand je click sur l'icone streamonsport, je me retrouve devant une icone avec un point d'exclamation

**Comment by sizanic** [comment]
Bonjour,
ce n'est pas la mise à jour qui a retiré StreamOnSport.
C'est le site StreamonSport qui s'est retiré du web 😄

**Comment by KenshiroBlind** [comment]
> Bonjour, ce n'est pas la mise à jour qui a retiré StreamOnSport. C'est le site StreamonSport qui s'est retiré du web 😅

oh zut alors , je ne savais pas que StreamonSport n'etait plus dispo. étant dans un pays anglophone, c'etait vraiment cool de pouvoir regarder le sport en français. Se pourrait-il qu'une alternative soit dispo d'ici la ?

**Comment by sizanic** [comment]
Stremonsport n'était pas la seule source à proposer des liens sportifs en français 🤔 
Retrouve les autres sources dans le menu "En direct/sport".

**Comment by KenshiroBlind** [comment]
Heu, je pense qu'il y a malentendu, je ne dis pas que StreamOnSport était la seule source a proposer des liens mais c'etait bien la seule source a proposer des chaines que je pouvais laisser tourner/regarder meme quand il n'y a pas un événement sportif en direct/live (ie laisser tourner beinsport toute la journée)

**Comment by sizanic** [comment]
vStream propose pourtant un accès "En direct/Sports(Chaines)" qui regroupe la liste des sources qui proposent des chaines de sports en continue.
StreamonSport n'y est plus mais il en reste au moins une autre de fonctionnelle.


https://github.com/user-attachments/assets/040683d7-7e84-4817-a43c-e08929f21a3b

**Comment by KenshiroBlind** [comment]
D'accord, merci pour l'info, j'avoue que je me disais que l'option direct ne proposait des liens que lorsqu'il y avait des événements sportifs, my apologies

**Comment by sizanic** [comment]
Tu as raison de penser que l'option "Sports(En direct)" ne propose que les événements en direct, mais là on parle de l'option "Sports(Chaines)".


Es-tu sûr de ne pas avoir désactivé "NeymarTV" dans les paramètres de vStream ?

De plus, comme je vois que tu as toujours "StreamOnSport", NeymarTV ne sera pas fonctionnel dès que tu l'auras dans la liste.
Dans les prochaines 48 heures, il te faudra redémarrer kodi pour attendre que Streamonsport disparaisse, alors Neymar devrait te proposer des chaines.

**Comment by KenshiroBlind** [comment]
> Tu as raison de penser que l'option "Sports(En direct)" ne propose que les événements en direct, mais là on parle de l'option "Sports(Chaines)".
> 
> Es-tu sûr de ne pas avoir désactivé "NeymarTV" dans les paramètres de vStream ?
> 
> De plus, comme je vois que tu as toujours "StreamOnSport", NeymarTV ne sera pas fonctionnel dès que tu l'auras dans la liste. Dans les prochaines 48 heures, il te faudra redémarrer kodi pour attendre que Streamonsport disparaisse, alors Neymar devrait te proposer des chaines.

Je viens de désinstaller l'extension vstream et en le re-installant, je me suis rendu compte que je n'avais pas le script dns.python, etrangement le zip n'apparait pas dans le repo via kodi donc j'ai récupéré le zip via mon notebook, puis je l'ai envoyé via wifi sur ma box android et effectuer l'installation manuelle (de script.dns.python j'entends) à partir de kodi.
je suis allé dans réglages et j'ai activer toutes les sources, puis dans vstream je suis allé dans outils, puis sources, puis neymar tv et j'ai pu trouver un lien qui marche (lien 6 pour Bein sports 1 en l'occurence).
je vais revoir tout ça une fois de retour chez moi (petite course rapide à faire) et m'assurer que tout fonctionne comme prévu. 
Encore merci pour ton aide et désolé pour les fautes d'orthographe (clavier qwerty et correcteur d'ortho un peu façon de Microsoft edge n'aident pas vraiment)

**Comment by sizanic** [comment]
Pour DNSPython, tu ne l'as pas trouvé car il ne s'installe pas depuis le dépot.
Mais il s'installe comme le dépot.
En passant par "Installer d'un zip" et en naviguant sur l'adresse github de vStream.

Tu peux suivre un tuto ici : https://lesalkodiques.wiki/docs/module-dns-python/

Et pour te rendre sur neymarTV, pourquoi passer par "outils" ?
Si tu recherches une "chaine de sports en direct", tout est dans le nom 😉 

"chaine de sports en direct" -> En direct/Sports/Chaines

**Comment by KenshiroBlind** [comment]
Merci encore champion🥇

**Comment by sizanic** [comment]
Une nouvelle source de sport devrait arriver bientôt.
On remettra la source StreamOnSport lorsque le site sera revenu.
