### ISSUE TITLE
Proposition d'ajout : tokyvideo

### ISSUE THREAD

**Issue by karlo2105** [Kodi-vStream/venom-xbmc-addons#4252]
[Tokyvideo](https://www.tokyvideo.com/fr) est une plate-forme de vidéos qui propose des longs et courts métrages complets notamment en français. Ce serait intéressant de l'ajouter dans les sources.

**Comment by sizanic** [comment]
Bonjour,

Il est incontestable que ce site renferme de beaux documentaires.
Et il y a en effet un filtre sur les contenus en français.
Mais je n'ai vraiment pas trouvé de contenu en français malheureusement.

A la rigueur, ce qu'on peut garder de non-français serait les concerts.
Mais il s'agit vraiment de concerts "historiques".

Je ne pense pas qu'il y ait suffisamment de public intéressé par ce contenu parmi les utilisateurs de vStream 🤔 

Intégrer ce site ne sera pas dans la liste de nos sites prioritaires (je note en plus que certaines vidéos sont de Youtube, ce que nous avons du mal à traiter)

**Comment by karlo2105** [comment]
En cherchant sur Google Video, ce [film](https://www.google.com/search?q=l%27as+des+as&client=firefox-b-m&sca_upv=1&udm=7&prmd=visn&tbs=dur:l&dpr=3), j'obtiens quand même 2 résultats sur Tokyvideo.

**Comment by sizanic** [comment]
Un seul film n'est malheureusement pas suffisant.

**Comment by orzel** [comment]
je ne sais pas en 2024, mais aujourd'hui, tokyvideo, c'est un incontournable, y compris pour le francais.
