### ISSUE TITLE
Les résultats wiflix sont incomplets

### ISSUE THREAD

**Issue by xonsap** [Kodi-vStream/venom-xbmc-addons#4267]
**Décrivez le bug**
Quand on fait une recherche de série, les résultats wiflix sont incomplets.
Par exemple 'From' et 'Silo' sont des séries en 10 episodes, et les 10 apparaissent bien sur le site mais seulement 9 épisodes dans vstream sont affichés.
Je ne sais pas si cela est limité a wiflix, ni si la liste des films comporte le même problème.

**Votre system**
- OS: LibreElec
- Appareil: Rpi5
- Version Kodi: 21.1
- Version Vstream: last 

**Nous devons le reproduire**
- Nom du site: wiflix-hd.me
- Titre du fim/serie: silo, from
- Nom du host (openload/vidzi/...):  dood, uqload

**Comment by sizanic** [comment]
Bonjour,
Merci pour cette information, on va regarder.

**Comment by sizanic** [comment]
Une correction a été mise en place, elle sera disponible dans la prochaine version de vStream.

**Comment by sizanic** [comment]
Très bien, merci pour ton retour sur cette correction mise à disposition dans la version 3 de vStream.
