### ISSUE TITLE
Wilifilm : Aucun élément

### ISSUE THREAD

**Issue by Ocin05** [Kodi-vStream/venom-xbmc-addons#4268]
**Décrivez le bug**
Je n'ai plus accès à la source Wilifilm dans les films. Quand je regarde si le site est dispo sur google tout est ok. Mais avec Vstream c'est Aucun élément trouvé. Avez-vous une solution ??

**Votre system**
- OS: Libre Elec
- Appareil: RPI 4
- Version Kodi: [21]
- Version Vstream: [2.9.11]

**Nous devons le reproduire**

- Nom du site: Wilifilm

**Comment by sizanic** [comment]
Bonjour,
Merci pour l'info.
On va regarder si une modification est nécessaire.

**Comment by Ocin05** [comment]
@sizanic Excusez moi de vous déranger. Avez-vous relevez des problèmes pour cette source ?

**Comment by sizanic** [comment]
Bonsoir.
J'ai répondu aujourd'hui à 1h du matin. J'ai donc peu dormi pour me lever à 7:00 pour partir au travail.
Et là je viens de prendre mon train pour rentrer chez moi.
Donc non, je n'ai rien relevé pendant cette journée au travail.
Peut-être attendre que je passe un peu de temps chez moi 🤔😁

**Comment by sizanic** [comment]
le site qui correspond à l'adresse utilisée par vStream n'est plus disponible.

Une autre adresse existe ?

**Comment by Ocin05** [comment]
Bonsoir, 
Excusez moi pour ce dérangement. Il est vrai que je me suis un peu précipité. J'ai relevé cette adresse pour la source Wilifilm "https://latraverseepourlespoir.fr/"

**Comment by sizanic** [comment]
J'ai également noté ce site, mais il s'agit d'un faux site qui fait semblant d'avoir les vidéos mais qui va demander de s'inscrire pour voler des adresses mails.
Ils n'ont pas réellement les films.

**Comment by Ocin05** [comment]
Bien reçu. J'ai beau chercher, je ne trouve pas d'autre adresse malheureusement.
