### ISSUE TITLE
Bug 3.0.0 Vstream

### ISSUE THREAD

**Issue by Mokoman30** [Kodi-vStream/venom-xbmc-addons#4280]
Bonjour @sizanic 
Enfin la version 3.0 mais quand je clique sur 
News ou autre sa ne s ouvre plus comme avec l ancienne version 

j’ai accès à tout par source que sa sois film 
Série anime 
J’imagine c la maintenant ?
Car j accéder par News moi avant la 3.0  mais News s ouvre plus c normal ? 

merci 

- OS:  Android]
- Version Kodi: [21.1]
- Version Vstream: [3.0.0]

**Comment by sizanic** [comment]
ce n'est pas normal.
L'accès par source n'est plus à prioriser.
Il y a bien un souci si les DNS ne sont pas changés, alors vStream n'affichera rien.

Il faut modifier les parametres DNS (ou attendre la correction).

**Comment by sizanic** [comment]
C'est bon ou pas ?

**Comment by Mokoman30** [comment]
Oui c est bon ça fonctionne Merci 
J’aime beaucoup la 3.0.0 
Bravo pour votre travail à tous j adore
