### ISSUE TITLE
vStream version cloudstream 

### ISSUE THREAD

**Issue by DZFOORT** [Kodi-vStream/venom-xbmc-addons#4281]
bonjour cher développeurs 
je vous invite à rejoindre mon groupe cloudstream french team
https://t.me/**********************_TEAM

on a un repos qui s'appelle (FrenchRepo)
code : peaLOVpK

si vous pouvez développer un extension vstream pour cloudstream ça serait super

merci 
@sizanic

**Comment by Ujiuka** [comment]
Ça sera vraiment cool d'avoir peaLOVpK

**Comment by sizanic** [comment]
Bonjour,

Merci de ne pas faire sur notre groupe de la publicité pour le votre.
Et c'est valable pour tous les réseaux, on ne publie pas non plus d'invitation sur les groupes facebook des autres.


Quant à un redéveloppement de vStream pour Cloudstream, je ne pense pas que nous le ferons.

Nous voulons rester sur un seul développement et c'est kodi que nous avons choisi.

**Comment by DZFOORT** [comment]
> Bonjour,
> 
> Merci de ne pas faire sur notre groupe de la publicité pour le votre. Et c'est valable pour tous les réseaux, on ne publie pas non plus d'invitation sur les groupes facebook des autres.
> 
> Quant à un redéveloppement de vStream pour Cloudstream, je ne pense pas que nous le ferons.
> 
> Nous voulons rester sur un seul développement et c'est kodi que nous avons choisi.

c juste une proposition 😉😉

**Comment by sizanic** [comment]
Oui, je comprends bien, une proposition de travailler sur une extension.
C'est juste une proposition mais c'est nous qui allons travailler.
Et nous n'avons pas la structure pour travailler sur d'autres extensions.
