### ISSUE TITLE
Demande de suppression de site web

### ISSUE THREAD

**Issue by Izak57** [Kodi-vStream/venom-xbmc-addons#4283]
**Bonsoir à l'équipe de vStream** 🖐

Je suis Izak, l'un des 2 développeurs du site de streaming [SeeFrench](https://seefrench.xyz/).
Je voulais vous demander la suppression de l'addon SeeFrench de vos catalogues de scripts,
- étant donné que SeeFrench **ne stock pas directement les films**:
il serait préférable pour vous d'aller les chercher à la source.

- Notre site est **100% gratuit et tient instablement** sur des moyens d'hébergement gratuit:
plus le traffic est grand, plus la stabilité diminue et le site **risque de s'écrouler**.

Je vous remercie d'avoir lu mon message et j'espère que vous serez en compréhension avec moi 💗.
Bonne soirée à vous et franchement je trouve le projet incroyable, continuez de scrape mais pas nous svp 🙏🙏😭😎

Izak

**Comment by TheSamurai4861** [comment]
@Izak57 je vous conseille de sécuriser votre API si vous ne voulez pas qu'elle soit utilisée par d'autres.

**Comment by TheSamurai4861** [comment]
Vous pouvez également obliger la fermeture du site dans le cas où un curieux irait voir les requêtes réalisés vers l'API via l'inspecteur 😉

**Comment by Izak57** [comment]
haha j'avoue que c pas mal je note 📃✍🤣

**Comment by TheSamurai4861** [comment]
Voilà voilà haha

**Comment by sizanic** [comment]
Bonjour @Izak57,

>Oui effectivement on va implémenter une captcha et plusieurs autres sécu par la suite.

Il s'agit là de solutions pour sécuriser le site.
Mais nous ne passons pas par le site, mais par les API.

Il s'agit donc pour nous de récupérer quelques réponses en texte.
Ce qui est beaucoup moins gourmand en ressources que ce que nécessite l'accès à votre site par un navigateur internet (qui télécharge également les images, les styles css, des fichiers js, génère des allers/retours de requetes, et bien plus encore).

On ne scrape pas les pages après avoir récupéré l'ensemble de ces ressources.

Nos requêtes sont peu nuisibles à votre trafic et sollicitent très peu vos ressources.

Je note également que votre business model n'est pas d'afficher des publicités sur votre site.
Vous partagez donc vos liens de façon désintéressé, sans objectif de profit, vous voulez juste proposer des liens de streaming aux gens. (**Comme nous**)
Et pour cela vous les mettez à disposition sur un site accessible depuis n'importe quel navigateur internet.

Mais il faut aussi voir vStream comme un navigateur !
Un navigateur qui affiche aussi votre site, mais de façon beaucoup plus light (avec une mise en page différente, et en ne téléchargeant que le minimum).

Notre solution de partage est donc aussi un moyen pour vous de partager vos liens.
vStream est un navigateur qui propose des adresses de sites préenregistrés.

**POUR AUTANT**

Je ne dis pas que nous ne sommes pas sensibles à votre demande.

Nous en avons discuté entre admins et nous serions plutôt d'accord de retirer votre site de notre navigateur.

> étant donné que SeeFrench ne stock pas directement les films:
il serait préférable pour vous d'aller les chercher à la source.

Je suis complètement d'accord !
J'aimerai bien ne pas passer par un site intermédiaire pour récupérer les liens des différents hébergeurs.

Je viens de vérifier les liens que vous proposez, et alors qu'il me semblait que vous en proposiez une dizaine par film, je n'en vois plus que deux par film.
Dont le lien commun FREmbed.

Et pour l'autre nous allons regarder comment fonctionne leur API.

Si vous avez quelques astuces, nous sommes preneur 😄 
Faut-il obligatoirement un compte chez cl..dm..oc  ?

**Comment by Izak57** [comment]
Bonsoir,

> Il s'agit là de solutions pour sécuriser le site.
Mais nous ne passons pas par le site, mais par les API.

Effectivement, mais je parlais surtout d'un captcha qui permet aussi de générer un token de session pour l'utilisation de l'API.

> Nos requêtes sont peu nuisibles à votre trafic et sollicitent très peu vos ressources.

C'est vrai que passer par notre API est moins gourmande en traffic que le scrapping par un web driver ou n'importe quelle autre méthode 😅 Mais notre API utilise beaucoup de ressources dans le système de récupération de média que nous utilisons qui est vraiment instable et fais des loops de tries de requêtes qui épuise le réseaux de l'hébergement 💀

> Je viens de vérifier les liens que vous proposez, et alors qu'il me semblait que vous en proposiez une dizaine par film, je n'en vois plus que deux par film.

SeeFrench est de - en - stable et maintenu mais nous allons tout régler d'ici quelques semaines.

> Si vous avez quelques astuces, nous sommes preneur 😄

Yes, je vous invite à m'ajouter sur Discord pour qu'on puisse en parler moi et mon associé. Discord: `@izakdu57` 👌

> Faut-il obligatoirement un compte chez cl..dm..oc ?
Dutout 😁

Merci de votre réactivité et passez une bonne soirée 😎🙏

**Comment by sizanic** [comment]
> Mais notre API utilise beaucoup de ressources dans le système de récupération de média que nous utilisons qui est vraiment instable et fais des loops de tries de requêtes qui épuise le réseaux de l'hébergement 💀

J'imagine !

Je rappelle ici notre Discord si vous voulez nous suivre : https://discord.gg/S65HBXm

Sinon, je vous contacterai aussi en privé.

**Comment by sizanic** [comment]
Suite à la demande amicale des propriétaires du site, nous l'avons retiré de notre addon.
