### ISSUE TITLE
Research returns empty black screen

### ISSUE THREAD

**Issue by calvin4242** [Kodi-vStream/venom-xbmc-addons#4284]
**Décrivez le bug**
Hello!
Quoi que je fasse sur Vstream, recherche native, recherche par genre, etc., la fenêtre contextuelle de Vstream apparaît avec les sources trouvées, mais après sa fermeture, il y a un écran vide au lieu de la liste des résultats des éléments trouvés ou de la liste des hebergeurs (je ne sais plus). Kodi ne freeze pas car je peux naviguer. Juste un écran vide sur le résultat de la recherche. J'ai essayé avec le skin Estuary et même résultat.

**Votre system**
- OS: COREELEC 21
- Appareil: odroid N2+
- Version Kodi: 21.1.1omega
- Version Vstream: 3.0.0

**Nous devons le reproduire**

- Nom du site: 
- Titre du fim/serie: 
- Nom du host (openload/vidzi/...): 

**Log**

**Image**

**Plus**

**Comment by LoakAudio** [comment]
Bonjour,
Même chose pour un collègue. Il est chez Bouyges et il semblerait que leurs DNS bloquent les sites utilisés par vStream pour les recherches, donc pas de résultats.
La solution a été de changer les DNS dans Libreelec.

**Comment by sizanic** [comment]
Bonjour,

il est préférable de toute façon de modifier les DNS pour avoir accès à l'ensemble des sources de vStream, et en effet cela va effectivement corriger le souci de la recherche vide.

S'il n'est pas possible de changer les DNS ou si le problème persiste, il faut désactiver la source qui pose problème : **streamizseries**

Il faudra la réactiver dans quelques jours avec la prochaine mise à jour de vStream.

**Comment by LoakAudio** [comment]
Vous avez des serveurs DNS à conseiller ?

**Comment by calvin4242** [comment]
J'ai été obligé d'attribuer une IP statique directement à la box tv et changé les serveurs de nom dans Coreelec et celà a résolu le problème. 
DNS1: 1.1.1.1 
DNS2: 1.0.0.1
DNS3: 8.8.8.8

mais je ne sais pas si l'ipv6 prend la modification aussi. ..
Merci pour ces infos! 👍

**Comment by GravuTrad** [comment]
Possible de mettre une option facile de changement des dns dans vstream? (voire kodi). Car en ce moment dans kodi je ne peux même plus voir un zip dans le repo de vstream alors que je sais qu'ils y sont, et même après surcouche d'un vpn. Même en mettant aussi cloudflare y a ces soucis d'affichage.

**Comment by GravuTrad** [comment]
bon je dis des aneries, sur ma box j'ai changé depuis un moment pour mettre ceux d'fdn. sur mon ordi aussi. sur le kodi de la box ca ne s'affiche pas alors que sur l'ordi oui. c'est quoi le bins

**Comment by TmpName** [comment]
Oui, meme soucis pour moi, je viens de tout re-installer et je comprend pas.
De mémoire ca marchait avant mais la meme avec les DNS modifiés sous windows, donc l'explorateur affiche bien la page, ca ne marche pas sur kodi.
Par contre avec dnspython ca marche de suite.

**Comment by sizanic** [comment]
@TmpName 
Quel souci ?
J'ai expliqué la cause et résolu le problème  🤔

**Comment by GravuTrad** [comment]
Tu as expliqué quoi et résolu comment? car ca ne s'applique pas qu'à cette source mais partout. et peu importe le dns à priori (puisque j'ai bien précisé que j'avais déjà changé)

**Comment by sizanic** [comment]
Il est question ici des résultats de recherche qui ne s'affichent pas.
Cela vient du souci pour accéder à la source streamizseries.
Donc : 
- soit on utilise un DNS qui permet d'accéder à cette source
- soit on la désactive dans les paramètres
- soit on utilise la version Beta qui contient la correction
- soit on ne fait rien car de toute façon j'ai désactivé cette source de façon générale dans vStream.

**Comment by TmpName** [comment]
Pas de soucis, ca fonctionne en ce moment, je rebondissais sur ce commentaire https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4284#issuecomment-2552419502

De changer les DNS sur la machine directement fonctionne sur un navigateur, mais pas sur kodi (et j'ai tout redemarré) et la je vois pas pourquoi ....

**Comment by calvin4242** [comment]
je ne comprends pas les commentaires precedents vous parlez de Kodi de navigateur et de windows on ne sait pas votre config ni sur quoi est installé qui. En fait soit vous changez les dns dans la configuration de votre box/routeur FAI et dans ce cas tous les appareillages ou sont installé Kodi seront impactés, soit vous modifiez les dns sur chaque appareil ou est installé Kodi individuellement et c'est ce que j'ai fait car mon FAI ne me permet pas cette modif via la box. Et puis il faut attribuer des IP fixes a votre LAN car je suppose que votre box est en mode routeur sinon les dns marcheront pas.

**Comment by GravuTrad** [comment]
Oui tmpname c'est exactement de ça que je parle, pas que de cette source. pb plus global, comme toi à priori.

pour calvin42, on a déjà fait tout ça (car seul moyen de contournement bien sûr, tout est clair) et ca ne marche pas quand même sur le player de la box (android). contrairement à tmpname moi ca marche bien sur le kodi windows, pas sur le kodi du player box

**Comment by calvin4242** [comment]
ipv4? ipv6? android en wifi ou filaire? ip statique? version android? Archi de votre resau local? etc etc...On ne peut pas resoudre votre pb sans données par l'operation du st esprit. Amen

**Comment by GravuTrad** [comment]
Ipv4, player box sous android 10 en wifi ac, ip statique, wifi de la box, tout en dns fdn.

**Comment by calvin4242** [comment]
questions: 🧐
00-Marque et modele de ta Player box?
0-As tu un routeur en plus de la box de ton FAI?
1-As tu mis une ip statique sur ta player box et aussi la même dans les réglages de l'administration de la box de ton FAI?
2-Kodi t'affiche t'il bien l'ip statique et pareil dans l'admin de ta box?
3-quels etaient tes précédents dns?
4-quels sont les actuels dns? 
5-As tu testé avec par ex les dns google?
6-As tu redemarré le box/routeur?
7-As tu fait un test par ethernet pour isoler un pb de wifi?
8-ta player box est elle visible sur le reseau local? Ping ok?

**Comment by sizanic** [comment]
Le souci initial de ce ticket est résolu avec la version 3.1.0.
Les résultats de la recherche sont maintenant affichés.

Je vais devoir fermer ce ticket ...

**Comment by TmpName** [comment]
Oui, tu peux cloturer, on derive, c'etait juste un commentaire en passant car je n'arrive pas a expliquer ce qui se passe, les DNS changés sur la meme machine, marchent sur une application (un navigateur), mais pas une autre (kodi), alors que tout est sur la meme machine.
Et ce soucis ne concerne meme pas Vstream, donc oui cloture.
