### ISSUE TITLE
upnext non fonctionnel

### ISSUE THREAD

**Issue by tobal37** [Kodi-vStream/venom-xbmc-addons#4287]
**Votre system**
- OS: [linux , windows, android ,tvos]
- Appareil: [pc, apple tv shield]
- Version Kodi: [21.1]
- Version Vstream: [3.0.0]

**Nous devons le reproduire**

- Nom du site: pastebin
- Titre du fim/serie: toute les series 
- Nom du host alldebrid

bonjour depuis la 3.0.0 de vstream upnext ne fonctionne plus j utiloise pastebin donc il et bien activer dans les paramettre de vstream et upnext et bien installé a la fin de mon épisode je me retrouve sur le menu alors que je devrais avoir l episode suivent

**Comment by rjousse18** [comment]
Tu saurais envoyer les logs de ton kodi pour essayer d'y voir plus clair ? Plusieurs bugs de ce genre ont été remontés mais c'est pas systématique

**Comment by sizanic** [comment]
Bonjour,
Ce n'est en effet pas systématique car dépend des sources. Pastebin est bien une source touchée par ce souci.
Le probleme a été trouvé, il est corrigé et une mise à jour de vStream devrait arriver ce week-end !

**Comment by rjousse18** [comment]
Top ! 👍

**Comment by sizanic** [comment]
La version 3.1 de vStream vient de sortir et apporte une correction pour l'enchainement des épisodes.

**Comment by osmoze06** [comment]
Bonjour, testé sur la source **Pastebin**, cela ne fonctionne toujours pas.
Fresh Install de la version 3.1, testé sur 4 séries différentes...
Y a une manipulation particulière à refaire ?
Merci.

**Comment by sizanic** [comment]
Il faut avoir lu au moins 3 minutes de l'épisode avant de chercher de passer au suivant.

**Comment by osmoze06** [comment]
En laissant 3 minutes pleine de lecture (sans forcer l'avancement), c'est OK, merci pour la précision @sizanic
![image](https://github.com/user-attachments/assets/78d70536-7b3c-4439-9293-9067375b0c63)
