### ISSUE TITLE
topimdb

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#434]
je voulez créer une source " topimdb " pour les films on français Mais je n'arrive pas à trouver une regex qui permet de vérifier l'url et afficher les films
topimdb: 
http://pastebin.com/CBGinzG3
log:
http://pastebin.com/PZZLfJmV

**Comment by LordVenom** [comment]
Je voie pas qu'est ce que ça apporte de plus que TMDB?

**Comment by mino60** [comment]
Les films populare frençais de haute qualité video hebergée sur putlocker "google.video

http://www.imdb.com/search/title?title_type=feature,tv_movie&num_votes=100,&production_status=released&languages=fr%257c1&sort=moviemeter,asc&count=40&start=1

**Comment by TmpName** [comment]
?
Y a pas de film sur ce site ?

**Comment by mino60** [comment]
bien sur!.. mais les films sont classé top films et avec le mode de recherche on passe par putlocker.systeme qui heberge les films sur google video qhalité hd.

**Comment by TmpName** [comment]
Mais y a pas de film sur le site ? ou alors j'ai pas vu ou ?

**Comment by LordVenom** [comment]
Pareil j'ai pas suivis la.

**Comment by mino60** [comment]
j'ai toujour une erreur Pattern!!! ... est ce que on peut affichez la première page de se site? ?.....

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16739486/a59292d4-479a-11e6-977a-83d27e40c24d.png)

![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16739531/e4144840-479a-11e6-8d20-d05801bd6ba4.png)

**Comment by TmpName** [comment]
Alors tu vas rigoler ^^
J'ai fait un copier/coller de ta source au premier post, et j'ai pas eu ton bug.
Ca marche tres bien

Moi j'ai un bug l92 " sCom = aEntry[3] " car tu ne recupere que 3 entrees (0 /1 / 2)

**Comment by mino60** [comment]
Tu ai sur quelle version de kodi moi c'est jarvis 16.2

**Comment by mino60** [comment]
je suis presque arrivé a resoudre le problème mais j'ai une erreur "json"? ?..

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16847628/4d1d0d00-49f2-11e6-8799-2d815a96a7ad.png)

**Comment by TmpName** [comment]
On vois pas le nom du fichier ou se trouve la ligne que tu as surligné (trop a droite), mais c'est bizarre car dans le code que j'ai moi il y a pas de ligne json ?

**Comment by mino60** [comment]
Le "json" c'est pour aficher le numéro de la page

voissi le lien top 1000 films fr

ttp://www.imdb.com/search/title?title_type=feature,tv_movie&num_votes=1000,&production_status=released&languages=fr|1&sort=moviemeter,asc&count=40&start=1

je ne comprend pas pourquoi les titres des films son en francais sur le navigateur mozilla firefox
mais sur kodi c'est en allemand ?

ce que je veux faire plus tard

afficher le titre l'année la durée du film exp:
 Amelie (2006)                              2:02:00
Comedy/Romance



http://pastebin.com/UKbR1KzB

**Comment by TmpName** [comment]
???
Je ne vois aucun rapport avec ton message d'erreur et le code que tu donnes.
La je n'ai plus acces a l'ordi pr tester, mais sinon plus simple, il y a des sites qui proposent un recherche de film fr eg htt p://w ww.voirfilms.org/nationalite/francais/1

**Comment by mino60** [comment]
j'ai corrigé le script maintenant je peux voir les films avec le moteur de recherche vstream  ou alluc
mais je n'arrive pas a affiché les titres des films et leurs classements 

http://pastebin.com/msrA6LY4

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16859590/6b60bfb2-4a30-11e6-8219-38e6dc8b32bb.png)

**Comment by mino60** [comment]
je voudré ajouté "runtime" la recherche et NextPage

je n'arrive pas toujour a comprendre pourquoi les titres sont en allmand et pourtont ils son en français sur Mozilla firefox? ?

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16878652/b30320e4-4aad-11e6-8b10-100a3d3c3bc6.png)

http://pastebin.com/B8gT55Hi

**Comment by TmpName** [comment]
Pour avoir en francais
>>    oRequestHandler = cRequestHandler(sUrl)
    oRequestHandler.addHeaderEntry('Accept-Language','fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3')
    sHtmlContent = oRequestHandler.request()

**Comment by mino60** [comment]
j'ai essayé votre truc pour avoir une les titres en francais mais son sucsée?!! pareille concernant Next page.

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16880017/7906cebc-4ab3-11e6-85f0-e80fcf9bbf7f.png)

**Comment by TmpName** [comment]
Put1 tu t'es bien equipe niveau logiciel ^^.

Y a juste une ligne a rajouter pour l'avoir en fr, tu as des lignes en trop (141 142)

**Comment by mino60** [comment]
Pour la source de recherche Putlocker j'ai un bug pour afficher les films?

LOG: http://pastebin.com/AUUKNsfF

putlocker : http://pastebin.com/ZP6hUWXF

**Comment by TmpName** [comment]
Tu essayes d'ouvrir le site 'http://url'

Mais putlocker est un site anglophone ?

**Comment by mino60** [comment]
Oui mais c'est les fillms francais qualité HD héberger sur google.video ou vieomega , openload
en plus il ya le sous titres et telechargement

**Comment by TmpName** [comment]
Ben le plus facile pour moi c'est de passer par Exodus (la version anglaises, pas exodusFr), ces sites font justement partis de leurs sources.
Sinon j'ai teste intouchables et me suis retrouves sans les sous titres ? Tu va faire comment pr rajouter les sous titres ?

**Comment by mino60** [comment]
Peut être le premier site putlocker par contre le deuxième c'est moi qui la choisie, il n'existe pas sur le pluguin exodus!..
j'ai ^pas comprie "me suis retrouves sans les sous titres ?"

il y a plus de deux millions videos hebergé sur l'ancienne plateforme putlocker et il ya beaucoup de sites putlocker très connnue il ya aussi film-streaming.co un site tres complet on plus la qualilé des films blu ray 720p.

mais le problème c'est la fonction recherche?...

**Comment by TmpName** [comment]
Non le probleme c'est que c'est un site anglais, avec des films anglais, non sous titre en francais, lance la video sous google, elle sera sans sous titre, et la video seule, pas via le player qui lui peut rajouter les sous titres.

**Comment by mino60** [comment]
j'ai essayé 5 film sur les top40 francais la voix et francaise ( la haine , intouchable, martyrs, nikita, mommy) si non on peut utiliser les sources francaise comme Z-t film-streaming.co

**Comment by TmpName** [comment]
Alors deja 1 suis pas sur que cela marche sans les cookies.
La page est "h ttp://mov ieshd.tv/api/v1/cautare/apr"
La requete se fait en post et il ya au moins 6 parametre.
Tu dois l'avoir fonctionnelle sur SALT car j'ai trouve ca en passant >> ht tps://gith ub.com/XvBMC/repository.xvbmc/blob/master/plugin.vid eo.salts rd.lite/scrapers/flixa nity_scraper.py

**Comment by mino60** [comment]
j'ai une erreur de page
http://pastebin.com/Nus22Z6f

en vérité j'ai rien comprie salt,scrapers?...

**Comment by TmpName** [comment]
http://pastebin.com/CfRSbKA7

Tu as un code fonctionnel.
1 er partie a mettre en haut
2 eme partie a mettre en debut aussi
3 eme partie a copier et adapter dans ta recherche

Laisse la partie mise en commentaire, car chez moi ca marche sans, mais il se peut que le site ait juste memorise mon IP. En commentaire je charge la page pr chercher le token, sans je prend un token au hazard.

**Comment by mino60** [comment]
Salut...j'ai mit ton code sur le script(movieshd) juste la 3 eme partie ou je sais pas ou la mettre on fin j'ai essayé sur "showMovies" et "showSearch" mais sont succès: 

http://pastebin.com/ehdvDe22

**Comment by TmpName** [comment]
Vire les lignes 87 / 88

sFilm  = sSearchText

et faut refaire toute les tabulations

et dans sHtmlContent (affiche dans les logs) tu vas avoir les infos dont tu as besoin.

**Comment by mino60** [comment]
j'ai pas trouvé le regex pour la fonction showHosters par contre beaucoup de script java?

erreur? ?..
http://pastebin.com/8wkFEP11

**Comment by LordVenom** [comment]
(hors sujet): @mino60  j'ai supprimer certaine image du post, tu peux limiter les image quand cela et vraiment nécessaire merci :)

**Comment by TmpName** [comment]
Pour le premier bug, je l'ai dit precedement faut refaire les tabulation tout le code doit etre deplace de 4 espaces
>>IndentationError: ('expected an indented block', 

Pour le second import urllib

Pour le troisieme me faut le log.

**Comment by mino60** [comment]
le log pour showHosters et la recherch : 
http://pastebin.com/bGFVbdwU

**Comment by TmpName** [comment]
Premier lien, vla le lien que tu essayes de lancer
>>PLUGIN] Vstream: Hoster - play ('#" selected disabled>Change Source</option><option value="_4391002', 'allmyvideos.net', 'allmyvideos.net')

Le deuxieme lien, tu peux tout mettre a la poubelle, ce n'est plus le bon code, il y a plein de truc utiles qui n'y sont plus et a la place plein de truc qui servent a rien.

**Comment by mino60** [comment]
toujour erreur pour showHosters

http://pastebin.com/4xmiAt0A

sur la page html il n'y a pas de liens googlevideo ..??

**Comment by TmpName** [comment]
Tu recuperes mal le lien, la le lien que tu essaye de lire c'est
>>[PLUGIN] Vstream: Hoster - play ('_4363852', 'openload.co', 'openload.co')

Pour la haine, le lien est bien en googlevideo
>> defaultStream.movie = "htt s://redire ctor.googlevideo.com/videopl ayback?requiressl=yes&id=17ea4483a604a068&itag=22&source=webdrive&ttl=transient&app=texmex&ip=2a05:840::e098&ipbits=32&expire=1468932114&sparams=requiressl,id,itag,source,ttl,ip,ipbits,expire&signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx29AB44737AF8E76B&key=ck2&mm=30&mn=sn-5hne6nld&ms=nxu&mt=1468917151&mv=u&nh=IgpwcjxxxxxxxxxxxxxxxxxC4wLjE&pl=48";

**Comment by mino60** [comment]
J'ai pas parvenu de trouvait le film la haine dans la fonction recherche voici le script et le log (erreur 404 ) ? ?..
movieshd.py: 
http://pastebin.com/HMKGiuyu

http://pastebin.com/U2huqFks

**Comment by TmpName** [comment]
ligne 283
Tu essayes de parser "sHtmlContent" mais a aucun moment tu mets quelque chose dans la variable.
>>local variable 'sHtmlContent' referenced before assignment

**Comment by mino60** [comment]
Comment importer la fonction recherce des sites sur Top 1000 IMDb? ?

http://pastebin.com/EJnV8XxN

**Comment by TmpName** [comment]
Je comprend pas trop la question, la recherche se fait juste avec le lien h ttp://w ww.imdb.com/find?ref_=nv_sr_fn&s=all&q=nom_du_film

**Comment by mino60** [comment]
En fait, je veux plutôt créer un moteur de recherche pour 4 ou 5 sites
exemple quand je choisie le film francais classé numero 01 ( intouchable)
un tableaux me demande de choisire le moteur de recherche pour les 5 sites : 
zone_telechargement
film-streaming
kepliz
megastream
movieshd

quand je choisie zone_telechargement par exemple soit j'aurai le resultat direct ou soit un autre tableaux avec le non du film intouchable "KeyBoard" qui apparaît et il suffit que je clic sur ok pour avoir le résultat,
désolé pour les images car le site imdb.com et out en ce moment!...

![sans titre](https://cloud.githubusercontent.com/assets/11494048/17118117/b3daac70-52bf-11e6-8f2b-7fd8913cfbd2.png)

![sans titre1](https://cloud.githubusercontent.com/assets/11494048/17118136/c26a2d56-52bf-11e6-962c-86472f30b77a.png)
en peut ajouter d'autre section film par acteur les series ...le script et l'incone imdb je les ai mit sur beta.

**Comment by TmpName** [comment]
Ha ok, jette un oeuil sur le fichier rechercheHandler.py.
Car le probleme c'est que Vstream par defaut va rechercher dans tout les site enregistre, si tu ne veux le faire que sur certain site tu vas devoir te faire ta propre fonction __importPlugin

**Comment by mino60** [comment]
Je vais opter pr ta méthode elle me semble la plus simple et je ne parviens pas a trouver le nouveaux regex pour le site imdb.com apparemment ils en changer leurs page html ?!!!...

**Comment by mino60** [comment]
est ce que c'est possible d'avoir un tuto complet comment testé la "Pattern" sur le site regex.org

**Comment by TmpName** [comment]
Suis pas sur que sur ce site le regex marchent comme sur python, je me servais de celui la, car plus facile mais j'avais des prbs au niveau des saut de ligne du coup suis passe sur https://regex101.com/

**Comment by mino60** [comment]
J'ai troujour une erreur :     aResult = oParser.parse(sHtmlContent, sPattern)

voila la page

htt p://www.imdb.comsearch/title?groups=top_1000&sort=user_rating,desc&start=1

    sPattern ='<span class="lister-item-index unbold text-primary">(.*?)</span>.*?<img alt="(*?)" class="loadlate" data-tconst=".*?" src="(.*?)".*?<a href="/title/.*?">(.*?)</a><span class="lister-item-year text-muted unbold">(.*?)</span>'

**Comment by TmpName** [comment]
Le code sur la beta est le meme que celui dont tu te sert ?
C'est quoi le message d'erreur ?

**Comment by mino60** [comment]
voila le msg

![sans titre](https://cloud.githubusercontent.com/assets/11494048/17627697/6c6f2ebe-60b2-11e6-866a-f7239b5b060f.png)

**Comment by mino60** [comment]
Le code sur la beta est le meme que celui dont tu te sert ?

c'est parce que c'est le meme sur la page html

**Comment by TmpName** [comment]
Nope, je te demande ca, car je ne sais pas quel fichier tu utilises, moi c'est 
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/topimdb.py
et celui la ne correspond pas avec le tien.

**Comment by mino60** [comment]
voila mon fichier:

http://pastebin.com/UQytSWTs

pour ajouter une source j'ai utilisé themoviedb car il marche avec le mème principe

**Comment by TmpName** [comment]
Nope ca ne marche pas du tout avec le meme principe, themoviedb utilise un parser JSON pour lire des infos directement d'une api (pas de regex dans showMovies), et le tien est un site html a scrapper comme les autres.

Et ce n'est pas non plus ton fichier, dans ton log
ligne 165 
>aResult = oParser.parse(sHtmlContent, sPattern)

et le fichier que tu donnes a en ligne 165
>#sCom = unicode(aEntry[3], 'utf-8')#converti en unicode

Et pour le regex
![err](https://cloud.githubusercontent.com/assets/8311559/17634770/6f2eb63e-60d4-11e6-940a-f0187a66af72.jpg)

**Comment by mino60** [comment]
c'est par ce que j'ai supprimer la fonction showPage () la ligne 165 a changé 

j'ai essayé le regex
    sPattern ='<span class="lister-item-index unbold text-primary">(.*?)<\/span>.*?<img alt=".*?" class="loadlate" data-tconst=".*?" src="(.*?)".*?<a href="(.*?)">(.*?)<\/a><span class="lister-item-year text-muted unbold">(.*?)<\/span>' 

il n y a pas d'erreur mais working ne s'arrete pas citation!?

**Comment by TmpName** [comment]
Mais tu l'as essaye dans https://regex101.com/, il ne marche meme pas sur le site pas besoin de le tester dans kodi.

Essaye ca
\<span class="lister-item-index unbold text-primary">(.*?)\<\/span>\<a href="(.*?)">(.*?)\<\/a>.+? src="([^"]+)"

**Comment by mino60** [comment]
j'ai essayé ton truc mais j'ai juste une page vierge

           
          
peut être un problème d'entrée ? ?

>   oOutputParameterHandler = cOutputParameterHandler()
            oOutputParameterHandler.addParameter('siteUrl', ('none'))
            oOutputParameterHandler.addParameter('sMovieTitle', str(aEntry[2]))
            oOutputParameterHandler.addParameter('sThumbnail', str(aEntry[1]))            
            oGui.addMovie(SITE_IDENTIFIER, 'showHosters', sTitle, '', aEntry[1], '', oOutputParameterHandler)

**Comment by TmpName** [comment]
Affiche le resultat du regex, tu verras qu'il est vide, celui la fonctionne dans kodi et surtout est beacoup plus rapide
![err](https://cloud.githubusercontent.com/assets/8311559/17648258/c431c816-620e-11e6-9e35-fb047e42afbd.jpg)

**Comment by mino60** [comment]
j'ai essayé rien qui marche 
![images](https://cloud.githubusercontent.com/assets/11494048/17651045/0a89f0f0-625e-11e6-84ac-07f6c01fd1e1.jpg)


           
          
peut être un problème d'entrée ? ?

>   oOutputParameterHandler = cOutputParameterHandler()
            oOutputParameterHandler.addParameter('siteUrl', ('none'))
            oOutputParameterHandler.addParameter('sMovieTitle', str(aEntry[2]))
            oOutputParameterHandler.addParameter('sThumbnail', str(aEntry[1]))            
            oGui.addMovie(SITE_IDENTIFIER, 'showHosters', sTitle, '', aEntry[1], '', oOutputParameterHandler)

**Comment by TmpName** [comment]
Oui, tu as lu le message d'erreur ?
Le regex fonctionne.
C'est tes fonctions qui deconnent apres, fonctions qui ne sont pas dans le fichier type, mais qui sont dans le fichier que tu as utilise comme base car "c'est le meme principe".
C'est toi qui as choisis de mettre ces fonctions, moi j'aurais pas fais comme ca. Donc soit tu continue comme tu as commence, soit tu effaces tout ce que tu ne comprend pas, et repars avec les fonctions classiques.

**Comment by mino60** [comment]
je n'ai  pas un message d'erreur et c'est ça le problème???... juste une page vièrgej'ai supprimé
#sTitle = sTitle.encode( 'utf8 ) 
mais toujour une page vièrge don le résultat.

**Comment by TmpName** [comment]
Pas de message d'erreur c'est qu'il ya un prb dans le regex.
Des que je recupere l'acces a l'ordi je fait une MAJ du fichier.

**Comment by mino60** [comment]
j'ai repartie a zero mais toujour j'ai une page vierge??

http://pastebin.com/p1E2Th3c

**Comment by TmpName** [comment]
Une version avec regex fonctionnant.
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/topimdb.py

print(aResult) ne marche pas sur la derniere version a la place utilises xbmc.log(str(aResult))

**Comment by mino60** [comment]
erreur vstream ligne 151 (    fh = open('c:\\test.txt', "w")

**Comment by TmpName** [comment]
Ha merd2, dsl, je rajoute ces lignes a chaque fois pr debogguer et tres souvent j'oublis de les remettre en commentaire.

Pour les poster, me suis plante dans le regex je ne prend pas la bonne image, il y en a une au format png (avec "nopicture" dans le nom) et une au format jpg, pas de bol j'ai pris la mauvaise.

**Comment by mino60** [comment]
Salut...j'ai changer le regex fonctionne mais les posters ne s'affiche pas en plus probleme Pattern Next page

http://pastebin.com/i7h1b15K

**Comment by TmpName** [comment]
Je ne vais pas encore mettre une capture d'ecran, mais le prb  se voit de suite dans regex101.com.

Tu prend l'image en png avec "nopicture" au lieu du jpg comme je l'ai dis juste avant.
Et ton regex prend les films 2 par 2.

**Comment by mino60** [comment]
Pour les posters j'ai activé les métadonnés , j'ai ajouté la fonction MyimportPluguin sur rechercheHandler

le resultat toujour =0

> def zone_telechargementSearch(sMovieTitle):
    oGui = cGui()
   
    exec "from resources.sites import zone_telechargement_com as search"
    sSearchText = oGui.showKeyBoard() 
    if (sSearchText != False):
        sUrl = URL_SEARCH_MOVIES[0] + sSearchText +'&tab=all&orderby_by=popular&orderby_order=desc&displaychangeto=thumb'
        showMovies(sUrl) 
        oGui.setEndOfDirectory()
        return

**Comment by TmpName** [comment]
??? Pourquoi je lis "zone_telechargement_com" ?

**Comment by TmpName** [comment]
Les scripts se font meta desactivées.

**Comment by mino60** [comment]
Pour Zt ça marche son modif sur rechercheHandler mais les autre sources j'ai toujour une erreur
est ce que il y a un moyen pour afficher les posters "png" car j'ai essayer tout les entrée son succès

http://pastebin.com/BLHC1Jwb

**Comment by TmpName** [comment]
J'ai teste avec MOVIE_WORLD et c'est bon , il te faut justement les jpg pas les png.

Apres pour les autres, je peux pas trop dire
film_streaming_co vient d'etre repare
L'adresse de kepliz que tu utilises n'exsite plus
movieshdSearch tu utilises le clavier
....

**Comment by mino60** [comment]
Salut....
FIN pour le probleme jpg il reste le next page et la mise a jour des sites sur Zt la recherche decone film streming.co out....
http://pastebin.com/5ae38K8J

**Comment by TmpName** [comment]
Tu as les accees pour la beta ?
Met le directement a jour https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/topimdb.py
Plus facile pr tester.
