### ISSUE TITLE
Framapad sans coupure.

### ISSUE THREAD

**Issue by henri4ter** [Kodi-vStream/venom-xbmc-addons#436]
Je me permets de remettre un message que j'ai mis dans le thread sur framapad car je pense que c'est important : les problémes de coupures au bout de 10s avec les chaines IPTV disparaissent quand on remplace dans le fichier liste les extensions .ts par l'extension .m3u8.
D'ailleurs on trouve sur le net des programmes qui le font automatiquement.

**Comment by TmpName** [comment]
Ha ouais ?
Put1 que c'est bon a savoir ca.

**Comment by henri4ter** [comment]
Avec le fichier iptv de framapad à 14h00 il n'y avait plus que bein 1 hd fr qui fonctionner.
TmpName va sur http://iptvlivestream.com/iptv/ et choisis une liste d'aujourdh'ui puis remplace les .ts par .m3u8 . En utilisant simple iptv de kodi tu verras que tout marche parfaitement.
Il n'y a pas de raison que framapad ne puisse pas faire la méme chose ou alors framapad n'utilise pas simple iptv ( je ne connais pas du tout le fonctionnement de framapad je donnais simplement l'astuce utilisée depuis longtemps par les utisateurs de fichiers iptv).
En tout cas l'idée de framapad est excellente on n'a plus a aller sur des sites étrangers rechercher des listes à jour il suffit que quelqu'un de confiance mette une fois par jour un fichier qui fonctionne et récupérer par exemple sur http://iptvlivestream.com/iptv/

**Comment by LordVenom** [comment]
Les modifications sont ouvert a tous et anonim 

https://github.com/LordVenom/venom-xbmc-addons/issues/412

**Comment by henri4ter** [comment]
Quelqu'un à modifier le fichier des chaines et mis les extensions .m3u8.
Non seulement il n'y a plus de coupure et en plus en interrrompant une chaine on revient automatiquement sur la liste des chaines disponibles.
C'est nickel. Cependant les liens ne sont valides que pour un ou deux jours car les revendeurs suppriment les comptes dés qu'ils deviennent publiques.
J'ai essayé d'ajouter une chaine (cinéfx) mais quand j'arrive sur https://github.com/LordVenom/venom-xbmc-addons/issues/412 la page n'est pas éditable.
En tous cas bravo pour cette nouvelle option de vstream .

**Comment by LordVenom** [comment]
https://annuel.framapad.org/p/vstream n'est pas editable pour toi ?

**Comment by henri4ter** [comment]
Si! ca y est j'y arrive.
J'ai ajouté qques chaines.

**Comment by TmpName** [comment]
Merci ^^

**Comment by patoche2025** [comment]
C'est super mais dommage que ca coupe après 20 sec quelqu'un a trouvé une solution ? Et toi @henri4ter est ce que ca coupe aussi?

**Comment by henri4ter** [comment]
Non ca ne coupe plus.
Il y a peut-étre une ou deux chaines qui coupent à cause du serveur qui sature.
Actuellement cana l décalé marche très bien.

**Comment by patoche2025** [comment]
merci @henri4ter  moi ca couper avec paris premiere mais je vais tester canal + décalé

**Comment by patoche2025** [comment]
Bizarre moi ca couper avec 30 sec sur canal + décalé tu as modifié des paramètre dans kodi @henri4ter ? Ou c'est dû que je suis en Belgique peut être

**Comment by henri4ter** [comment]
Non pas de paramétrage particulier.
J'ai fait un essai avec paris premiere à l'instant :  1) coupure net au bout de 30 secondes.2) je me remets sur paris première immédiatemant ....et ca marche nickel aucune coupure ( pendant caméra café) .
Tu as peut-ètre un problème avec les flux HD qui exige une connexion rapide.
Essaie d'abord avec les diffusions SD.

**Comment by patoche2025** [comment]
Ok merci @henri4ter je vais essayer avec le sd

**Comment by patoche2025** [comment]
Effectivement ca dépend de ma connexion internet j'ai vue que tu avais rajouté des chaînes si tu pouvais trouver la chaîne MCM se serai génial @henri4ter

**Comment by Elrondo46** [comment]
Le problème est fort simplement visible quand on test par chaine en m3u8 avec mpv sous Linux on reçoit des erreurs 403 forbidden en cours de stream et donc coupure

**Comment by isxela** [comment]
Bonjour, 
Novice dans ce domaine je parcours internet mais en vain 
Je rencontre le même problème que vous,  concernant les coupures. 
Pourriez-vous m'indiquer comment procéder pour changer l'extension.

Je possède une Android box

Merci d'avance pour votre aide

**Comment by TmpName** [comment]
Tout depend des chaines que tu cherches, mais en passant par "tv du web" tu auras quelques chaines qui elles fonctionnent tout le temps.

**Comment by isxela** [comment]
J'ai été voir déjà sur tv du Web, hélas pas assez de chaînes fonctionnement.

**Comment by big8extreme** [comment]
ça coupe encore sur kodi avec l'extension vstream. quelqu'un a une solution?

**Comment by quadcoreside** [comment]
En extension m3u8, avec un caching de plus de **5000 ms** = 5 seconde beaucoup moins de crash, vous pouvez également **augmenter** ce délais si ce problème persiste.
Reste a trouvez comment faire avec kodi...

**Comment by johngf** [comment]
le cache est inutile kodi ne met pas en cache les fichiers plylist m3u8 tu peux le verif grace au infos codec touche o du clavier sur kodi16
