### ISSUE TITLE
Soucis frenchstream

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#458]
Bonjour tous le monde,

Petit soucis lors d'une recherche sur vstream la recherche se bloque sur FRENCHSTREAM longtemps avant de passer au dessus quelqu'un a eu le problème?

D'avance merci

**Comment by TmpName** [comment]
C'est normal, le site est out en ce moment, tu peux le desactiver dans les parametres de vstream.
Si le site revient ce sera corrigé, sinon le site sera supprime.
Pour le moment, je viens juste de le voir, j'attend pour voir comment cela va evoluer.

**Comment by patoche2025** [comment]
Super merci pour l'info

**Comment by TmpName** [comment]
On peut meme retirer completement ma bidouille, c'etait a l'epoque ou le site etait banni sur certain providers, et donc l'url n'etait pas decodée (bloquage DNS), vu qu'il refonctionne je vais tout virer.

**Comment by kris06000** [comment]
merci pour l'information je m’inquiétais de ce dysfonctionnement
par ailleurs, pourquoi ne pas installer un système de mise à jour automatique pour les sources, en effet,  on ne voit pas toujours en bas de l’écran qu'elle est demandée. 

Dans cette  même idée,  pourquoi n'est il pas possible d'avoir aussi une mise à jour automatique du fichier v-stream compressé,  il est difficile d'être informé qu-une mise à jour est à nouveau disponible, en l 'occurrence la version 0.4.4 qui vient de sortir... 

Un grand merci à toute l’équipe
kris

**Comment by TmpName** [comment]
Si tu installes le repo de Vstream, il va se mettre a jour tout seul, pas besoin d'installer de version de Vstream compressée.

Et il y a un systeme de mise a jour auto des sources ^^. Tout les 3 ou 4 quatres jours (me souvient plus) Vstream compare les fichiers sites et host et affiche une option pour les mettre a jours sur la page d'acceuil.
Elle n'est pas vraiment automatique pour deux raisons, ne pas surcharger le serveur de requetes (github est gratuit) et si tu bidouilles toi meme les fichiers pour eviter tout les 4 jours de voir toutes tes modifs effacées.

**Comment by incognitous** [comment]
+1 désactiver frenchstream dans les options

**Comment by TmpName** [comment]
Ca a l'air d'etre dej
