### ISSUE TITLE
ZT -  mode Médiathèque

### ISSUE THREAD

**Issue by mcallew** [Kodi-vStream/venom-xbmc-addons#463]
Bonjour, 

Le site Zone-Telechargement affiche les résultats en mode Liste en place du mode Médiathèque.

Une idée de la raison ? 

Mathieu

**Comment by TmpName** [comment]
C'est quelle page que tu appelles resultats ?

**Comment by mcallew** [comment]
ShowMovies dans le script. J'ai fixé le problème dans #462

**Comment by TmpName** [comment]
Avec la modif sur oGui.addMisc() ?

Normallement l'affichage est gere par la fonction xbmc.executebuiltin('Container.SetViewMode(500)')

Mais j'ai du remettre oGui.addMisc. oGui.addTV sert pr les serie, oGui.addMovie pour les film et oGui.addMisc pour le reste. Sur la premiere page il peut y avoir des mix, du coup on a prit addMisc  pour eviter les problemes. Mais je ne vois pas comment cette ligne peut chnager l'affichage ?

**Comment by mcallew** [comment]
Oui.  Kodi gère principalement deux modes liste et mediatheque. Le premier étant utilisé pour le misc justement et se limite à des vues génériques. 

Du coup faudrait en fonction du type de fichier faire appel à ou l'autre fonction.  Pas mal de vos sites sont codés déjà comme ça. 

Ce qui est sur c'est que se retrouver avec des vignettes pour afficher des posters c'est un peu dommage :)

**Comment by TmpName** [comment]
Ha ok, apres tests, je viens de comprendre, on ne peut pas afficher les grands posters par exemple sur la premiere page.
Ceci dit, c'etait le choix du createur de la source, et je ne m'en etait jamais rendu compte, vu que la pluparts des infos ne sont pas primordiales sur la premiere page pr moi. C'est purement personnel mais je prefere avoir des miniatures sur la premiere page pr avoir le max de choix possibles, et quand j'ai choisi, la je regarde poster et infos.

**Comment by mcallew** [comment]
Dans mon cas, je souhaite afficher le mode mur  qui n'existe qu'en mode mediatheque, ce qui correspond à des vignettes format poster

**Comment by LordVenom** [comment]
Vous oublier la nouvelle option pour activer la vue personnaliser. 
Ca va modifier movies , tvshow, files.  addMisc et un file. addTV et un tvshow. et donc si tu as activer l'option d'affichage ça change tout.

**Comment by mcallew** [comment]
Bonjour @LordVenom

Ou se trouve cette nouvelle option ? Option de ton api ? De kodi?

**Comment by TmpName** [comment]
Dans les parametres de Vstream, mais meme en pouvant personnaliser addmisc, je ne pense pas que tu puisses avoir les memes affichages que dans addTV, apres j'ai pas teste.

**Comment by mino60** [comment]
Est ce que on peut utilisé cette fonction pour avoir les info sur la première page "showMovies"

>     if 'synopsis' not in sUrl:
      sPattern = '<div style="height:[0-9]{3}px;"><a title="" href="([^"]+)[^>]+?><img class="[^"]+?" data-newsid="[^"]+?" src="([^<"]+)".+?<a title="" href[^>]+?>([^<]+?)<'
    else: 
      sPattern = '<a href="([^"]+)">(.*?)<\/a><\/h1>.*?<img src="([^<"]+)">.*?<\/div><br><div align="center">(.*?)<\/div>'

le 2iem regex c'est a partir du mode large sur le site Zt

**Comment by TmpName** [comment]
Ben essaye mais on a deja teste, certains films qui n'ont pas de resume foutent la merde. Ca peut marcher mais le regex demande tellement de calcul (le nombre d'iteration) qu'il buggue assez souvent.

C'est realisable, mais pour le peu qu'il apporte, personne n'a voulu le faire.
