### ISSUE TITLE
Zone de telechargement plus d'accès aux liens

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#474]
Le site zone de telechargement à dû modifier un truc car ce matin ils étaient En maintenance et depuis sur vstream impossible de voir les liens d'un film ou d'une serie @TmpName si tu peux y jetee un œil merci d'avance

**Comment by TmpName** [comment]
Mis a jour.

**Comment by sebi0606** [comment]
Nickel merci beaucoup @TmpName

**Comment by chataigne73** [comment]
Salut. Ils ont mis en place une restriction sur le user Agent c'est ça ?

**Comment by driteur** [comment]
J'ai essayer ce matin et le problème avec zone téléchargement persiste...

**Comment by lemoine34** [comment]
oui sa marche toujour pas je confirm

**Comment by LordVenom** [comment]
https://github.com/LordVenom/venom-xbmc-addons/issues/11

**Comment by TmpName** [comment]
J'ai pas encore teste, mais pour repondre a @chataigne73 non, ca c'est un reliquat de mes tests, en fait j'ai juste retire un " du regex, suite a une petite modification de leur site.
Le UA n'a pas d'impact, et je crois meme que en passant par les fonctions interne a Vstream, ca rajoute d'office celui de firefox.

**Comment by rayan35** [comment]
Bonjour, comment faire la maj pour que les liens ZT refonctionnent? J'ai désinstaller, réinstaller rien y fait. Merci pour votre aide.

**Comment by mannou78** [comment]
Bonjour,

Sur une machine Android les liens TZ s affichent correctement.

Cependant, sur une machine libreelect aucun lien ne s affiche.

Est ce que quelqu<un aurait identifie une solution a ce probleme

Merci beaucoup

**Comment by rayan35** [comment]
En complément: je suis sur Android TV (BBOX MIAMI Bouygues T), j'ai désinstallé kodi, supprimé manuellement tous les répertoires de kodi et des plug-in (y compris les cachés), redémarrer la box en vidant le cache. Réinstallé kodi depuis le store, first démarrage, installl du depot, install du plug in, je ne touche pas à la conf, je vais sur toutes les sources, ZT, je choisi un contenu, vstream me liste les qualités disponibles et après, plus rien. Je clique sur un lien, ça fait comme si ça chargeait mais ça reste sur cette même page... (Essai effectué sur pas mal de lien ZT => Même problème! Sur d'autre sources pas de souci) Une idée???

**Comment by LordVenom** [comment]
Si tu peux fournis ton log:

https://github.com/LordVenom/venom-xbmc-addons/wiki/Dossier-log

**Comment by TmpName** [comment]
Le reinstaller ne sert a rien, v uque le fichier config ne s'efface pas (enfin je peux dire une connerie.
Avance la date de 3 jours avant de demarrer kodi et selectionne mise a jour dans la page d'acceuil.
Si tu n'as pas l'icone mise a jour ca ce n'est pas normal, car les fichier ne sont pas a jour par defaut.

**Comment by mannou78** [comment]
@TmpName 
Je pense tu as raison Vstream n'a pas demande a etre mis a jour sur la machine LibreElect alors que sur Android il a etait mis a jour.

Pourrais-tu stp confirmer la procedure pour forcer la MAJ (Jouer avec la date de Kodi simplement?)

Merci bien

**Comment by TmpName** [comment]
Oui, avance la date de ton systeme de 3 jours avant de redemarrer kodi.

**Comment by rayan35** [comment]
Je suis dans l'impossibilité d'avancer la date de la bbox miami.
Une autre solution pour pousser la MAJ?

**Comment by TmpName** [comment]
Il y en a une autre ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/497
Sinon il suffit d'attendre quelques jours tout simplement.

**Comment by fredkerm** [comment]
Bonjour,
J'ai toujours le souci avec la version 0.4.4

`17:12:00 T:1205859248  NOTICE: Thread JobWorker start, auto delete: true
17:12:00 T:1003479984  NOTICE: Thread LanguageInvoker start, auto delete: false
17:12:01 T:1003479984  NOTICE: -->Python Interpreter Initialized<--
17:12:02 T:1003479984  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
17:12:02 T:1003479984  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function showLinks
17:12:04 T:1003479984  NOTICE: mode film
17:12:04 T:1003479984  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
17:12:05 T:1003479984  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.8.7.1
17:12:05 T:1003479984  NOTICE: metahandler: No SQLite rows requiring update
17:12:07 T:1003479984  NOTICE: Previous line repeats 8 times.
17:12:07 T:1003479984  NOTICE: 	[PLUGIN] Vstream: close dialog
17:12:07 T:1284502448  NOTICE: Thread BackgroundLoader start, auto delete: false
17:12:07 T:1003479984  NOTICE: 	[PLUGIN] Vstream: Table initialized
17:12:07 T:1284502448  NOTICE: Thread JobWorker start, auto delete: true
17:12:13 T:1003479984  NOTICE: Thread LanguageInvoker start, auto delete: false
17:12:13 T:1003479984  NOTICE: -->Python Interpreter Initialized<--
17:12:14 T:1003479984  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
17:12:15 T:1003479984  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function showHosters
17:12:15 T:1003479984  NOTICE: http://www.zone-telechargement.com/films/x264-1080p-hdlight/149469-captain-america-civil-war.html
17:12:15 T:1003479984  NOTICE: 	[PLUGIN] Vstream: Table initialized
17:12:15 T:1945739840   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Captain%20America%3a%20Civil%20War%20&sThumbnail=http%3a%2f%2fimages.zone-telechargement.com%2f360%2fhttp%3a%2f%2fimages.allocine.fr%2fpictures%2f16%2f03%2f11%2f09%2f46%2f182814.jpg&site=zone_telechargement_com&siteUrl=http%3a%2f%2fwww.zone-telechargement.com%2ffilms%2fx264-1080p-hdlight%2f149469-captain-america-civil-war.html&title=Captain%20America%3a%20Civil%20War%20%20-%20%5bCOLOR%20skyblue%5d1080p%20HDLight%20(TRUEFRENCH)%5b%2fCOLOR%5d
17:12:15 T:1945739840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Captain%20America%3a%20Civil%20War%20&sThumbnail=http%3a%2f%2fimages.zone-telechargement.com%2f360%2fhttp%3a%2f%2fimages.allocine.fr%2fpictures%2f16%2f03%2f11%2f09%2f46%2f182814.jpg&site=zone_telechargement_com&siteUrl=http%3a%2f%2fwww.zone-telechargement.com%2ffilms%2fx264-1080p-hdlight%2f149469-captain-america-civil-war.html&title=Captain%20America%3a%20Civil%20War%20%20-%20%5bCOLOR%20skyblue%5d1080p%20HDLight%20(TRUEFRENCH)%5b%2fCOLOR%5d) failed
17:12:15 T:1003479984  NOTICE: Thread BackgroundLoader start, auto delete: false
`

**Comment by TmpName** [comment]
Je viens de retester, pas de problemes.
Compare le fichier de ton systeme avec celui la https://github.com/Kodi-vStream/venom-xbmc-addons/blob/master/plugin.video.vstream/resources/sites/zone_telechargement_com.py
La ligne 351 doit etre
> if 'épisode par épisode' in sHtmlContent or '<b>Episode :</b>' in sHtmlContent:

**Comment by fredkerm** [comment]
Bizarrement, je n'avais pas le bon fichier.
Après avoir recopié le fichier, c'est nikel !
Merci
