### ISSUE TITLE
Ma replay tv : plus d'acces au liens ...

### ISSUE THREAD

**Issue by natzen** [Kodi-vStream/venom-xbmc-addons#479]
Bonjour ,ma replay tv ne donne plus acces au liens ... si c'est possible de corriger.
Merci beaucoup :-)

**Comment by TmpName** [comment]
Quelques modifs, a tester.
Pour forcer la MAJ, avancer la date de 3 jours avant de lancer kodi.

**Comment by johngf** [comment]
il y des fois plusieurs vidéos par page ou plusieur liens avec un sélecteur il manque un système d'épisode à l'heure actuel on ne récupère que le premier lien de la premiere vidéo

**Comment by TmpName** [comment]
Ha oui j'avais pas vu.
A completer du coup.

**Comment by TmpName** [comment]
Nouvelle version a tester.

**Comment by johngf** [comment]
cette version est ok.
j'étais parti sur ce genre de pattern `'<li><a href="(.+?)">(.+?)</a></li>'`  ça fonctionné sauf avec les vidéos bonus du 29 Août 2016 (1 seul lien sur 7) à quoi correspondent dans le tien les \/\  et celui que tu a rajouté dans le `</a><\/a>` ?

**Comment by TmpName** [comment]
Je jete un oeuil de suite pour les thumbs.
Le \ est un caractere d'echappement, c'est tjours le meme sur tout les language de programmation (ou la plus grosse partie en tout cas)
Le regex 'e.' veut dire 1 'e' ou plus.
Le regex 'e\.' veut dire 'e.'

Va sur https://regex101.com/ et teste '/a' et '\/a' tu vas avoir une erreur sur l'un d'entre eux, car le / fait parti des caracteres speciaux.

En utilisant les fonctions de Vstream tu ne vois pas l'erreur car Vstream "corrige" le regex (il facilite le developpement), mais si tu passes ailleurs ca ne marchera pas.

**Comment by TmpName** [comment]
Encore une nouvelle version en ligne. Et la j'ai les thumbs, par contre si ca rechange c'est qu'ils surveillent faudra prendre des regex plus costaud.

**Comment by johngf** [comment]
il ne fonctionne plus a nouveau . 
dernier ajouts =ok 
par genre=pas de video
toutes les videos=aucune

**Comment by TmpName** [comment]
Nouvelle version a tester encore.

**Comment by johngf** [comment]
testé version ok

**Comment by johngf** [comment]
il y a une petite erreur de categorie REPLAYTV_REPLAYTV = (URL_MAIN + 'video/', 'showMovies')
toutes les videos = REPLAYTV_REPLAYTV = (URL_MAIN + 'videos/', 'showMovies')

**Comment by TmpName** [comment]
corrige.
Mais ils vennaient de faire la modif, et pour le moment les 2 ont l 'air de fonctionner.

**Comment by natzen** [comment]
chez moi j'ai beau avancé les dates j'ai pas la mise à jour hier j'ai reussi à mettre à jour mais ça ne fonctionner pas ... :-(

**Comment by johngf** [comment]
les deux fonctionnent oui mais la liste est plus grande avec videos moin de navigation.

**Comment by johngf** [comment]
natzen il faut attendre la prochaine maj
