### ISSUE TITLE
Nouvelle Branch

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#483]
Afin de travailler sur les dernières version de fichier utiliser la Branche Beta: 

https://github.com/LordVenom/venom-xbmc-addons/tree/Beta

**Comment by chataigne73** [comment]
salut
je suis un peu perdu
donc on utilise plus LordVenom/venom-xbmc-addons-beta  mais labranche beta de LordVenom/venom-xbmc-addons    c'est ça ??

**Comment by LordVenom** [comment]
Moi aussi lol, beta et devenue la branche par defaut donc quand tu propose un Pull logiquement ça vas dedans. Oui LordVenom/venom-xbmc-addons-beta et considérer comme off.

**Comment by TmpName** [comment]
Et comment ca marche pour les acces ?
L'avantage de la beta, c'est que c'etait openbar, il y a moyen de filer des acces pour une branche et pas une autre ? Car la c'est dommage d'avoir tout bloque en attente de validation a chaque fois. Et je sais meme pas comment tester sans valider le truc.

**Comment by LordVenom** [comment]
Je suis un peux perdu aussi. La banche par défaut et beta donc le system et le même tu valide et quand tu as fait les tests tu pull request sur la branche master et la les fichiers serons dispo pour la mise ajour.

Note: j'ai du modifier les urls pour la mise a jour auto voir 
https://github.com/LordVenom/venom-xbmc-addons/wiki/Mise-a-jour-(admin)

**Comment by TmpName** [comment]
Perso, le changement va etre rude pr moi, j'ai l impression de redecouvrir le feu.
A chaque fois que je vois un pull je suis comme un con.
1 - comment je le teste
2 - si je valide pas j'en fais quoi ?
3 - si je met un commentaire, je le perd, impossible de retomber dessus apres.

**Comment by LordVenom** [comment]
1 - Si y a un Pull tu le valide en vérifiant que tu et dans la branche Beta.
2 - tu le l'aisse trainer jusqu'a ceux que je m'en oqp lol
3 - J'ai pas tester les commentaires je regarderais au prochain pull
4 - C'est beta par defaut.
Sur la page d'accueil Github te diras que tu as des modif et tu proposeras de comparer avec Master et de le (merge)

**Comment by TmpName** [comment]
Ok, donc pull request on valide direct, plus facile pour tester, et sans danger pour la branche master, au pire on recorigera plus tard.

**Comment by LordVenom** [comment]
Bon y a une logique dans ce bordel :)

Les pulls que tu valide sont en Closed avec leur commentaire donc tu peux toujours discuter du fichier en cour mais faut choisir closed a chaque foix pas trés pratique mais bon

https://github.com/LordVenom/venom-xbmc-addons/pulls?q=is%3Apr+is%3Aclosed

**Comment by TmpName** [comment]
Question !
Il ya un moyen de faire passer les modif de la beta a la master pour 1 seul fichier ?
Car pour le moment, je lance la beta, fait un copier, lance le master et colle le tout.

**Comment by LordVenom** [comment]
Oui j'ai modifier le Wiki

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-a-jour-(admin)

**Comment by LordVenom** [comment]
J'ai tester en utilisant des branches mais il utilise toujours le repo complet bizarre.

**Comment by TmpName** [comment]
Pareil, je galere comme un porc.
Pas trouve comment mettre a jour uniquement les fichiers sites sans modifier le coeur de Vstream (vu que tu mes tout a jour a chaque fois lors de la fusion)

**Comment by LordVenom** [comment]
Logiquement il faut creer des branches depuis Master pour n'avoir que les changements dans la branche mais aprés il faut merge Master et Beta pour avoir les modifs dans les 2 c'est chiant.
