### ISSUE TITLE
Zone telechargement - impossibilité de voir les liens de certains animes

### ISSUE THREAD

**Issue by disizleboss93** [Kodi-vStream/venom-xbmc-addons#486]
Bonjour,

Je n'arrive pas à acceder aux liens de certains animes tels que Mob psycho 100 ou encore Mobile Suit Gundam UC RE :0096.

Lorsque je clique sur ses series rien ne se passe.

Pouvez vous y jeter un oeil?

Merci d'avance

**Comment by chataigne73** [comment]
en effet
le problème survient avec certaines pages formatées de manière "batarde"
j'ai proposé une modification sur la branche beta ...  mais je n'ai pas encore eu trop le temps de tester d'éventuels effets de bord

**Comment by disizleboss93** [comment]
Merci pour la reponse. Je viens de tester la version beta. Le problème est toujours présent

**Comment by chataigne73** [comment]
je n'ai pas fait la modif sur l'ancienne beta (LordVenom/venom-xbmc-addons-beta) mais j'ai fait un pull request sur la branche beta de LordVenom/venom-xbmc-addons 

bouge pas je fais la modif sur l'ancienne beta sur laquelle j'ai directement la main et tu vas pouvoir retester

**Comment by disizleboss93** [comment]
Je viens de tester la modif. Ca fonctionne tres bien maintenant. Pour ce qui est des effets de bord, je n'en ai pas constaté pour l'instant.

Merci beaucoup

**Comment by TmpName** [comment]
Je sais pas encore comment tester, je crois que LordVenom a deja valide le truc, mais ca risque de deconner pour des films comme "Star wars episode 1 : la menace fantome" ou le film "episode 50".
Faudrait un truc moins generaliste.

**Comment by disizleboss93** [comment]
Pour episode 50 ca fonctionne.
Par contre je ne peux pas lancer star wars episode 3.
Seul les liens interchangeables sont affichés. les liens premium ne sont pas visible quelque soit la qualité.
Pour Star wars episode 1, cela depend de la qualité choisit. Ca ne fonctionne pas en HDLight 720P mais c'est OK en 1080P H265

**Comment by disizleboss93** [comment]
Apres plusieurs tests sur la section films, je ne peux voir que les liens interchangeables pour la plupart des films

**Comment by mannou78** [comment]
Salut, je crois que ce defect est un dup de #474
Faudrait les merger ensemble

Merci

**Comment by TmpName** [comment]
Beacoup de bugs corrige sur ZT ces derniers jours, je pense que celui la en fait parti.
