### ISSUE TITLE
Pb Tvweb M6, W9,....

### ISSUE THREAD

**Issue by Allonsbon2004** [Kodi-vStream/venom-xbmc-addons#492]
Plusieurs chaines ne fonctionne plus tel que M6 W9 et d'autres

**Comment by TmpName** [comment]
Il y a de gros prbs de ce cote en ce moment, mais pour les chaines m6 et w9, a mon avis tu peux mettre une croix dessus, ces chaines n'ayant pas de lien officiel, les liens trouves ne durent jamais.

**Comment by Allonsbon2004** [comment]
OK merci.

C’est vrai que coté chaine tv en streaming y a eu un peu de perte. En tout cas un grand merci pour votre taf et votre réactivité.

Si framapad devient stable cela sera Top.

Bon courage à la team

 

De : TmpName [mailto:notifications@github.com] 
Envoyé : samedi 3 septembre 2016 09:32
À : Kodi-vStream/venom-xbmc-addons <venom-xbmc-addons@noreply.github.com>
Cc : Allonsbon2004 <plancelo@free.fr>; Author <author@noreply.github.com>
Objet : Re: [Kodi-vStream/venom-xbmc-addons] Pb Tvweb M6, W9,.... (#492)

 

Il y a de gros prbs de ce cote en ce moment, mais pour les chaines m6 et w9, a mon avis tu peux mettre une croix dessus, ces chaines n'ayant pas de lien officiel, les liens trouves ne durent jamais.
