### ISSUE TITLE
Impossible d'utiliser Zone-telechargement dans Vstream

### ISSUE THREAD

**Issue by camelone** [Kodi-vStream/venom-xbmc-addons#493]
Bonjour, cela fait maintenant trois jours que je ne sais plus rien lancer à partir de ZT dans Vstream et ce sur plusieurs TV Box Android et sur mon pc également. Au moment de choisir le film, il me propose la qualité voulue, et lors de la sélection, rien ne se passe. Je viens d'installer la version 17 et cela fait la même chose. Voici le log:
Une idée?

14:07:03 T:2624   DEBUG: CWinEventsWin32::WndProcWindow is active
14:07:03 T:5876   DEBUG: CAnnouncementManager - Announcement: OnScreensaverDeactivated from xbmc
14:07:03 T:5876   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverDeactivated
14:07:03 T:2624   DEBUG: ------ Window Init (Pointer.xml) ------
14:07:04 T:2624   DEBUG: ------ Window Deinit () ------
14:07:05 T:304   DEBUG: Thread JobWorker start, auto delete: true
14:07:07 T:2624   DEBUG: CInputManager::ProcessMouse: trying mouse action leftclick
14:07:07 T:2624   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Captain%20America%3A%20Civil%20War%20&sThumbnail=http%3A%2F%2Fimages.zone-telechargement.com%2F360%2Fhttp%3A%2F%2Fimages.allocine.fr%2Fpictures%2F16%2F03%2F11%2F09%2F46%2F182814.jpg&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Ffilms%2Fx264-720p-hdlight%2F149461-captain-america-civil-war.html&title=Captain%20America%3A%20Civil%20War%20%20-%20%5BCOLOR%20skyblue%5D720p%20HDLight%20(TRUEFRENCH)%5B%2FCOLOR%5D)
14:07:07 T:2624   DEBUG:   ParentPath = [plugin://plugin.video.vstream/?function=showLinks&sCat=5&sFav=showLinks&sId=zone_telechargement_com&sMovieTitle=Captain%20America%3A%20Civil%20War%20&sThumbnail=http%3A%2F%2Fimages.zone-telechargement.com%2F360%2Fhttp%3A%2F%2Fimages.allocine.fr%2Fpictures%2F16%2F03%2F11%2F09%2F46%2F182814.jpg&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Ffilms%2Fdvdrip-bdrip%2F149454-captain-america-civil-war.html&title=Captain%20America%3A%20Civil%20War%20]
14:07:07 T:4740   DEBUG: Thread JobWorker start, auto delete: true
14:07:07 T:304   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.vstream] took 195 ms
14:07:07 T:4740   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin vStream('plugin://plugin.video.vstream/','24','?function=showHosters&sMovieTitle=Captain%20America%3A%20Civil%20War%20&sThumbnail=http%3A%2F%2Fimages.zone-telechargement.com%2F360%2Fhttp%3A%2F%2Fimages.allocine.fr%2Fpictures%2F16%2F03%2F11%2F09%2F46%2F182814.jpg&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Ffilms%2Fx264-720p-hdlight%2F149461-captain-america-civil-war.html&title=Captain%20America%3A%20Civil%20War%20%20-%20%5BCOLOR%20skyblue%5D720p%20HDLight%20(TRUEFRENCH)%5B%2FCOLOR%5D')
14:07:07 T:1284   DEBUG: Thread JobWorker start, auto delete: true
14:07:07 T:4200   DEBUG: Thread LanguageInvoker start, auto delete: false
14:07:07 T:4200    INFO: initializing python engine.
14:07:07 T:4200   DEBUG: CPythonInvoker(25, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): start processing
14:07:07 T:4200   DEBUG: -->Python Interpreter Initialized<--
14:07:07 T:4200   DEBUG: CPythonInvoker(25, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): the source file to load is "C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py"
14:07:07 T:4200   DEBUG: CPythonInvoker(25, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): setting the Python path to C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.common.plugin.cache\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.addon.common\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.metahandler\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.myconnpy\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.parsedom\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.simplejson\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
14:07:07 T:4200   DEBUG: CPythonInvoker(25, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): entering source directory C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream
14:07:07 T:4200   DEBUG: CPythonInvoker(25, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): instantiating addon using automatically obtained id of "plugin.video.vstream" dependent on version 2.1.0 of the xbmc.python api
14:07:07 T:4200   DEBUG: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
14:07:07 T:4200   DEBUG: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function showHosters
14:07:07 T:2624   DEBUG: ------ Window Init (DialogBusy.xml) ------
14:07:07 T:4200   DEBUG: http://www.zone-telechargement.com/films/x264-720p-hdlight/149461-captain-america-civil-war.html
14:07:08 T:4200   DEBUG: 	[PLUGIN] Vstream: Table initialized
14:07:08 T:4200    INFO: CPythonInvoker(25, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): script successfully run
14:07:08 T:4200    INFO: Python script stopped
14:07:08 T:4200   DEBUG: Thread LanguageInvoker 4200 terminating
14:07:08 T:2624   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Captain%20America%3A%20Civil%20War%20&sThumbnail=http%3A%2F%2Fimages.zone-telechargement.com%2F360%2Fhttp%3A%2F%2Fimages.allocine.fr%2Fpictures%2F16%2F03%2F11%2F09%2F46%2F182814.jpg&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Ffilms%2Fx264-720p-hdlight%2F149461-captain-america-civil-war.html&title=Captain%20America%3A%20Civil%20War%20%20-%20%5BCOLOR%20skyblue%5D720p%20HDLight%20(TRUEFRENCH)%5B%2FCOLOR%5D
14:07:08 T:2624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Captain%20America%3A%20Civil%20War%20&sThumbnail=http%3A%2F%2Fimages.zone-telechargement.com%2F360%2Fhttp%3A%2F%2Fimages.allocine.fr%2Fpictures%2F16%2F03%2F11%2F09%2F46%2F182814.jpg&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Ffilms%2Fx264-720p-hdlight%2F149461-captain-america-civil-war.html&title=Captain%20America%3A%20Civil%20War%20%20-%20%5BCOLOR%20skyblue%5D720p%20HDLight%20(TRUEFRENCH)%5B%2FCOLOR%5D) failed
14:07:08 T:2624   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.vstream/?function=showLinks&sCat=5&sFav=showLinks&sId=zone_telechargement_com&sMovieTitle=Captain%20America%3A%20Civil%20War%20&sThumbnail=http%3A%2F%2Fimages.zone-telechargement.com%2F360%2Fhttp%3A%2F%2Fimages.allocine.fr%2Fpictures%2F16%2F03%2F11%2F09%2F46%2F182814.jpg&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Ffilms%2Fdvdrip-bdrip%2F149454-captain-america-civil-war.html&title=Captain%20America%3A%20Civil%20War%20)
14:07:08 T:2624   DEBUG:   ParentPath = [plugin://plugin.video.vstream/?function=showMovies&sFav=showMovies&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Fexclus.html&title=Exclus%20(Films%20populaires)]
14:07:08 T:4740   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.vstream] took 201 ms
14:07:08 T:304   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin vStream('plugin://plugin.video.vstream/','25','?function=showLinks&sCat=5&sFav=showLinks&sId=zone_telechargement_com&sMovieTitle=Captain%20America%3A%20Civil%20War%20&sThumbnail=http%3A%2F%2Fimages.zone-telechargement.com%2F360%2Fhttp%3A%2F%2Fimages.allocine.fr%2Fpictures%2F16%2F03%2F11%2F09%2F46%2F182814.jpg&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Ffilms%2Fdvdrip-bdrip%2F149454-captain-america-civil-war.html&title=Captain%20America%3A%20Civil%20War%20')
14:07:08 T:5900   DEBUG: Thread LanguageInvoker start, auto delete: false
14:07:08 T:5900    INFO: initializing python engine.
14:07:08 T:5900   DEBUG: CPythonInvoker(26, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): start processing
14:07:08 T:5900   DEBUG: -->Python Interpreter Initialized<--
14:07:08 T:5900   DEBUG: CPythonInvoker(26, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): the source file to load is "C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py"
14:07:08 T:5900   DEBUG: CPythonInvoker(26, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): setting the Python path to C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.common.plugin.cache\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.addon.common\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.metahandler\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.myconnpy\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.parsedom\lib;C:\Users\Romuald\AppData\Roaming\Kodi\addons\script.module.simplejson\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
14:07:08 T:5900   DEBUG: CPythonInvoker(26, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): entering source directory C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream
14:07:08 T:5900   DEBUG: CPythonInvoker(26, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): instantiating addon using automatically obtained id of "plugin.video.vstream" dependent on version 2.1.0 of the xbmc.python api
14:07:08 T:5900   DEBUG: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
14:07:08 T:5900   DEBUG: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function showLinks
14:07:08 T:2624   DEBUG: ------ Window Init (DialogBusy.xml) ------
14:07:09 T:5900   DEBUG: mode film
14:07:09 T:5900   DEBUG: DialogProgress::Open called
14:07:09 T:5900   DEBUG: ------ Window Init (DialogConfirm.xml) ------
14:07:09 T:5900   DEBUG: 	[PLUGIN] Vstream: close dialog
14:07:09 T:5900   DEBUG: 	[PLUGIN] Vstream: Table initialized
14:07:09 T:5900    INFO: CPythonInvoker(26, C:\Users\Romuald\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): script successfully run
14:07:09 T:5900    INFO: Python script stopped
14:07:09 T:5900   DEBUG: Thread LanguageInvoker 5900 terminating
14:07:09 T:2624   DEBUG: Saving fileitems [plugin://plugin.video.vstream/?function=showLinks&sCat=5&sFav=showLinks&sId=zone_telechargement_com&sMovieTitle=Captain%20America%3A%20Civil%20War%20&sThumbnail=http%3A%2F%2Fimages.zone-telechargement.com%2F360%2Fhttp%3A%2F%2Fimages.allocine.fr%2Fpictures%2F16%2F03%2F11%2F09%2F46%2F182814.jpg&site=zone_telechargement_com&siteUrl=http%3A%2F%2Fwww.zone-telechargement.com%2Ffilms%2Fdvdrip-bdrip%2F149454-captain-america-civil-war.html&title=Captain%20America%3A%20Civil%20War%20]
14:07:09 T:2104   DEBUG: Thread BackgroundLoader start, auto delete: false
14:07:09 T:2104   DEBUG: Thread BackgroundLoader 2104 terminating
14:07:09 T:1284   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url
14:07:09 T:2624   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
14:07:09 T:2624   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
14:07:12 T:2624   DEBUG: Keyboard: scancode: 0x38, sym: 0x0134, unicode: 0x0000, modifier: 0x100
14:07:12 T:2624   DEBUG: CInputManager::OnKey: alt-long-leftalt (0x104f0d4) pressed, action is
14:07:13 T:2624   DEBUG: ------ Window Deinit (Pointer.xml) ------
14:07:13 T:2624   DEBUG: CWinEventsWin32::WndProcWindow is active
14:07:13 T:2624   DEBUG: CWinEventsWin32::WndProc: Focus switched to process C:\Windows\explorer.exe

**Comment by camelone** [comment]
Désolé pour la date, j'ai modifié la date de mon pc pour voir une éventuelle mise à jour..

**Comment by chataigne73** [comment]
il y a actuellement un gros problème avec notre manière de différencier les séries et les films car ZT a fait quelques changements     et je pense que ton problème peut être lié à cela
as tu fait une MAJ des sites (cliquer sur le texte vert "mise à jour disponible") ?

**Comment by chataigne73** [comment]
j'ai proposé une nouvelle correction, à tester une fois validée pour voir si c'est mieux

**Comment by TmpName** [comment]
Je confirme, ca marche beacoup mieux, tu dois avoir une vielle version, j'ai essaye le meme film sans problemes.

**Comment by camelone** [comment]
Visiblement ça refonctionne. Merci pour la collaboration et votre très bon travail.

**Comment by TmpName** [comment]
Je cloture, car il y a 3 issues sur ZT, et je commence a m y perdre.
