### ISSUE TITLE
Probleme de type de vue dans kodi 17

### ISSUE THREAD

**Issue by bubuleur** [Kodi-vStream/venom-xbmc-addons#494]
Bonjour,
Je viens à vous pour un petit problème sur la nouvelle version de LibreELEC (Krypton) v7.90.004 ALPHA
J’ai installé l'addon vstream dernière version et j’ai un problème pour afficher des exemples d’images

www.hostingpics.net/viewer.php?id=381614IMG20160831222454.jpg

www.hostingpics.net/viewer.php?id=529898IMG20160831222147.jpg

www.hostingpics.net/viewer.php?id=839263IMG20160831222312.jpg

Lorsque je change le type de vu de ça marche parfois j’ai toute l’image mais c'est pénible il faut tout le temps changer le type de vue pour chaque liste de film
(ps : J’ai remarqué que dans les addons pour kodi comme youtube ca fait la même chose)
En vous remerciant
Cordialement

**Comment by spcxsat** [comment]
hello,

mais par defaut le type de vue 53

ou alors instal Estuary MOD de Guilouz la tu aura tt les vue

**Comment by TmpName** [comment]
Kodi 17 est en beta, donc on attend la version finale pour corriger.
Mais il y a beacoup d'autres choses qui vont deconner, comme les captcha de ZT.

**Comment by bubuleur** [comment]
Bonjour,
Merci a toi spcxsat mais comment on fait pour mettre par défaut le type de vue merci
Sinon merci a vous deux pour votre réponse très rapide

**Comment by spcxsat** [comment]
dans les parametre de vstream premier onglet tu a l'option

**Comment by bubuleur** [comment]
Ok merci pour ta reponse bonne journée
