### ISSUE TITLE
Fonction mise à jour

### ISSUE THREAD

**Issue by mmtest1** [Kodi-vStream/venom-xbmc-addons#497]
bonjour,
j'utilise kodi et vstream sous osmc (raspberry pi b+) et je n'ai pas de clavier, l'accès aux mises à jour est parfois long et certains sites deviennent inaccessibles, le changement de date du système est plutôt laborieux en ssh afin de forcer les mises à jour. 
Serait-il possible d'ajouter une fonction de recherche de mise à jour manuelle en plus de l'automatique ?
Je vous remercie pour votre excellent travail et le suivi.

**Comment by spcxsat** [comment]
Salut,

c'est vrais que ca serais pas mal, car il sufie que le corectife sort le vendredi avec un peu de mal chance on l'aura le lundi
donc site hs le weekend quand on sans serre le plus pour moi

**Comment by jojotango** [comment]
Moi je mets à jour vStreamBêta avec un script en bash. Tu peux faire pareil avec la branche master en utilisant la commande : 
`git clone https://github.com/Kodi-vStream/venom-xbmc-addons.git`

**Comment by LordVenom** [comment]
Bonjour, je crains que cela ne devienne trop lourd pour l'api Github mais comme le dit @jojotango y a d'autre solution comme de venir cherche le fichier et le remplacer dans le dossier vstream.

**Comment by TmpName** [comment]
Exactement, le truc d'avancer la date est officieux, c'est juste pour depanner.
Tu imagines si a chaque fois qu'une source deconne, si tout les utilisateurs essayent de faire des MAJ en boucle.
La MAJ se fait tout les 3 jours, donc si ca deconne, le temps de s'en rendre compte, de faire la modif, de la tester et la mettre en ligne, 3 jours c'est pas enorme, surtout que pendant ces 3 jours il y a d'autres sources qui fonctionnent tres bien.

**Comment by mmtest1** [comment]
je vous remercie pour vos reponses, c'est vrai que trois jours ce n'est pas enorme et qu'il y a toujours d'autres sources fonctionnelles, il s'agissait d'une suggestion mais si cela est trop lourd pour l'api et les serveurs, 
si cela devient genant je telechargerai et remplacerais les fichiers manuellement
Dans tous les cas je vous remercie grandement pour le partage de l'extension
