### ISSUE TITLE
ATTENTION Nouvelle Url

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#499]
Afin d'affiner les permissions le repositories change en organisation normalement les urls suivent automatiquement et ce week end je ferais les modifs au coeur de vStream. que ceux qui veulent des permission ce face connaitre.

https://github.com/Kodi-vStream

**Comment by TmpName** [comment]
Arf , l'url de base va changer ?
Ca va etre tres lourd ca, pour le referencement google, et le temps des MAJ sur tout les systemes.
Tu es sur que ca va pas poser plus de problemes qu'en resoudre ?

**Comment by LordVenom** [comment]
Il change oui mais y a un suivis de l'ancien donc pas de soucis même pour le maj pareil ça vas fonctionne mais je mettrais a jour le coeur de vStream quand même pour faire les chose bien.

**Comment by TmpName** [comment]
Arf, tu as deja supprime le beta ?
J'avais des liens mit pr memoire dans les issues.

**Comment by johngf** [comment]
il y a un soucis quand on veut télécharger via clone or download la version fait 163mo

**Comment by LordVenom** [comment]
Oui Dsl

**Comment by TmpName** [comment]
Pas grave j'ai tout retrouve sur le cache de google.

**Comment by Kodigoal** [comment]
Salut LordVenom et TmpName,
Ca serait possible d'avoir à nouveau la permission de modifier sur la beta ?
Merci

**Comment by LordVenom** [comment]
Tu reçus une invitation des que j'ai ouvert la nouvelle url, ça te permettra d'avoir les droits.

Pour info il reste mino60 , Kodigoal et FreeFighter77 en attente.

**Comment by TmpName** [comment]
D'ailleurs tant que j y pense, j'ai fais une modif sur le fichier about.py pour forcer la recherche des MAJ lors d'une premiere install, jettes y un oeuil stp, car si me suis loupe ca risque de foutre le bordel a la prochaine MAJ du coeur.
Pour moi ca a l'air bon, mais j'aime pas trop toucher au coeur.

**Comment by Kodigoal** [comment]
Ah ok mince, bal mail qui efface messages après quelques jours donc invitation loupée.

**Comment by LordVenom** [comment]
Pas de soucis c'est renvoyer :)

**Comment by Kodigoal** [comment]
:-) rien recu , alors je vienq de changer l'email  , ca devrait le faire maintenant si ca te derange pas te renvoyer l'invit ^^ 
désolé
ps: Ou il faut que je coche des options dans les paramêtres du compte pour recevoir ?

**Comment by Kodigoal** [comment]
:-) rien recu , alors je viens de changer l'email  , ca devrait le faire maintenant si ca te derange pas te renvoyer l'invit ^^ 
désolé
ps: Ou il faut que je coche des options dans les paramêtres du compte pour recevoir ?

**Comment by LordVenom** [comment]
@TmpName  pas vue de problème on verras lol

**Comment by TmpName** [comment]
Bon j'ai relu le wiki, comment faire un pull request sur uniquement certain fichiers ?
Si je change les fichiers de la master est ce que ca va influencer la version actuelle ? ou est ce que c'est la version zippe qui est telechargée par defaut ?

**Comment by LordVenom** [comment]
Ha non c est tout les fichiers modifier qui vont être pull j avais pas penser a ça pas grave pull quand même pour lancer une mise a jour officiel faudrais modifier la addons.XML et le ZIP donc pas de soucis

**Comment by TmpName** [comment]
Bon alors j'ai essaye.
J'ai du faire 4 ou 5 pull request pour qu'il ne m'en propose plus, je ne sais absoluement pas ce qu'il a fait
Mais j'ai pas toucher au zip et le fichier xml.

Pour moi ca ne sert a rien le systeme de pull.
Ca demande plus de manips, c'est plus complique, augmente le risque d'erreur, et la meme manip ne donne pas toujours le meme resultat.
