### ISSUE TITLE
How to install script.module.metahandler

### ISSUE THREAD

**Issue by emailradhesh** [Kodi-vStream/venom-xbmc-addons#503]
Using Raspberry PI (OpenELEC and Kodi) when installing script.module.metahandler it shows  

> dependencies not met

Other dependencies installed successfully from ZIP are

1. script.module.parsedom-2.5.2.zip
2. script.module.requests-2.9.1.zip
3. script.module.simplejson-3.3.0.zip
4. script.module.urlresolver-3.0.1.zip

Because of this error I cannot get vstream-addon installed

**Comment by emailradhesh** [comment]
I read issue #38 before putting this question.

**Comment by Phobos1337** [comment]
Did you install the script.module.metahandler from the zip or from the repo ? If you have installed the script from the repo, try to force refresh the repo it might work or could you just give me the exact error in the kodi log ? ^^

**Comment by emailradhesh** [comment]
Thanks @Phobos1337 I was attempting to install from ZIP. Let me refresh REPO and reply.

**Comment by emailradhesh** [comment]
Added vstream repo on fresh install and then installed vstream addon. And it failed. Attached is 
[kodi.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/453203/kodi.txt)

**Comment by emailradhesh** [comment]
With debug on the log file is 
[kodi.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/453231/kodi.txt)

**Comment by emailradhesh** [comment]
Is it right that /home is owned by root:root?

**Comment by emailradhesh** [comment]
I think I found the issue... Partition wasn't resized. It was running low in space.
This is because I created "/storage/.kodi" and/or "/storage/.config" and/or "/storage/.cache" after flashing .img file.
