### ISSUE TITLE
Ajouter_un_hoster.py

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#505]
bonjour, serait t'il possible d'avoir un fichier commenté comme ajouter_une_source.py mais pour crée un hoster ?

**Comment by TmpName** [comment]
J'ai commence, mais c'est encore succinct.
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_un_hebergeur.py

**Comment by johngf** [comment]
merci

**Comment by TmpName** [comment]
J'ai mis une nouvelle version, avec les fonctions les plus utilisées.
Apres c'est completable.

**Comment by johngf** [comment]
en faite je me demande ou vous trouver le pattern sur le site ou sur l'hebergeur et comment savoir si il y a un codage (AAdecoder , cpacker..)

**Comment by johngf** [comment]
le pattern sur l'hebergeur je pense

**Comment by TmpName** [comment]
Ben c'est la le prb, c'est pour ca qu'on propose un ajouter_une_source.py et pas un ajouter_un_hebergeur.py, c'est un poil plus pointu.
Pour les hebergeurs de base, ca marche comme pour creer un site, tu regardes le code dans ton navigateur pour trouver le pattern, tu selectionnes juste au dessus de la video, juste au dessous, puis "afficher le code de la selection".

Pour le codage (si il y en a un), c'est en lisant le code, mais pareil tu le reperes vite.

Un exemple va voir une video openload, affiche le code de toute la page et jette un oeuil.
La ou y a ecrit "eval (function(p,a,c,k,e,d)" > cpacker
La ou y a ecrit ωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ ['_'] > AAdecode

**Comment by TmpName** [comment]
Au pire donne moi l hebergeur, je te dirais le codage ou si il y en a un.

**Comment by johngf** [comment]
l'hébergeur c'est Tune.pk je pense pas qu'il a un codage

**Comment by TmpName** [comment]
Nope.
Ca envois par exmple sur la page h ttp://embed.tune.pk/video.php?vid=2661264&player=6
et tu as le lien sur la seconde ligne.

**Comment by johngf** [comment]
le probleme est de récupérer ce lien vstream essaye de play le premier pour l'instant.

**Comment by TmpName** [comment]
Je ne sait pas comment est ton premier lien mais j'utiliserais la fonction __getIdFromUrl pour recuperer le numero de la video.
Et je refabriquerais le lien dans la fonction getMediaLinkForGuest
Surl  = 'h ttp://embed.tune.pk/video.php?vid=' + id + '&player=6'

**Comment by johngf** [comment]
bon j'ai réussi a faire ça [http://pastebin.com/LaPREsCp](url) .
C'est pas fini et c'est pas correct mais kodi play la vidéo (pas de choix qualité dispo)
il faut que je trouve comment trouver seulement le numero de la video avec __getIdFromUrl sans avoir le reste &folder=2016/09/03/&width=770&height=350&autoplay=no

**Comment by johngf** [comment]
2eme version avec choix de la qualité mais erreur 
CCurlFile::Stat - Failed: HTTP response code said error(22)
CCurlFile::FillBuffer - Failed: HTTP returned error 400
http://pastebin.com/SEQR4ByG

**Comment by TmpName** [comment]
Alors j'ai fait quelques test.
1- je recupererais l id avec ce regex vid=([0-9]+) dans Getidfromurl
2 - je charge la page https://embed.tune.pk/play/' + id + '?autoplay=&ssl=yes&inline=true'
3 - j utilise ce regex pr le lien "file":"([^"]+)".+?"label":"([^"]+)"

**Comment by johngf** [comment]
vid=([0-9]+)  ne récupére pas l'id ([0-9]) si mais récupére aussi la suite (True, ['6669907', '2016', '09', '03', '770', '350'])
pour vid=6669907&folder=2016/09/03/&width=770&height=350&autoplay=no

**Comment by johngf** [comment]
merci pour l'aide j'ai finalement réussi.
