### ISSUE TITLE
zone-telechargement.com down

### ISSUE THREAD

**Issue by darky78** [Kodi-vStream/venom-xbmc-addons#508]
Bonjour, tout d'abord merci pour ce super addon! Il me semble y avoir un problème avec les liens zone-telechargement.com, effectivement j'arrive bien à naviguer dans les différentes catégories, mais dès que je choisi un film/série, le menu pour choisir entre les différentes qualités apparait, mais quand je clique sur une des qualités disponibles rien ne se passe, je vois bien l'icône "working" qui tourne 2 petite secondes et plus rien.

J'ai essayé d'activer toutes les options de recherche pour ce site et aussi de rajouter mon compte uptobox mais cela ne change rien.

Une idée pour résoudre ce soucis ?

Merci.

**Comment by johngf** [comment]
je viens d'essayer et ça fonctionne tu as la derniere version disponible ?
je pense que le probléme a été résolut ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/474

**Comment by darky78** [comment]
Merci ! J'étais déjà tomber sur ce lien/post du forum, et effectivement mon fichier zone_telechargement_com.py contenais :

if 'épisode par épisode' in sHtmlContent:

a la place de 

if 'épisode par épisode' in sHtmlContent or '<b>Episode :</b>' in sHtmlContent:

Alors voilà ce que j'ai essayé de faire :
1-Si je remplace directement le fichier par un copier/coller (avec ES explorer), ça ne marche plus du tout, Zone téléchargement n'apparait même plus dans la liste des sources sous VStream
2-Du coup j'ai réinstaller et éditer le fichier directement et modifier la ligne en question, et le résultat est le même, ça ne lance ni les films ni les séries (même après redémarrage de la box, et vérification du fichier zone_telechargement_com.py qui a bien garder les modifications réalisés)

Autre remarque :
Je venais de faire un installe de 0 de la version 0.4.4 car je viens d'avoir ma Box android, si le fichier zone_telechargement_com.py est corrompu il l'est donc dans la version 0.4.4, car c'est la seule version que j'ai installée, je n'avais aucune version de Xmbc ou de Vstream avant.

D'autres idées?

**Comment by darky78** [comment]
Autre info, avant ces changements dans la liste des sources Zone-telechargement apparait en rose/rouge, je ne sais pas si c«est normal.

Et voici mon dernier fichier log:

21:52:46 T:18446744072444038656  NOTICE: special://profile/ is mapped to: special://masterprofile/
21:52:46 T:18446744072444038656  NOTICE: -----------------------------------------------------------------------
21:52:46 T:18446744072444038656  NOTICE: Starting Kodi (16.1 Git:2016-04-24-f6ceced). Platform: Android ARM 32-bit
21:52:46 T:18446744072444038656  NOTICE: Using Release Kodi x32 build
21:52:46 T:18446744072444038656  NOTICE: Kodi compiled Apr 24 2016 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
21:52:46 T:18446744072444038656  NOTICE: Running on Arcadyan BouygtelTV with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.10.46
21:52:46 T:18446744072444038656  NOTICE: FFmpeg version: 2.8.6-kodi-2.8.6-Jarvis-16.0
21:52:46 T:18446744072444038656  NOTICE: Host CPU: ARMv7 Processor rev 1 (v7l), 4 cores available
21:52:46 T:18446744072444038656  NOTICE: Product: BouygtelTV, Device: HMB4213H, Board: unknown - Manufacturer: Arcadyan, Brand: BouyguesTelecom, Model: BouygtelTV, Hardware: HMB4213H
21:52:46 T:18446744072444038656  NOTICE: External storage path = /storage/emulated/0; status = ok
21:52:46 T:18446744072444038656  NOTICE: ARM Features: Neon enabled
21:52:46 T:18446744072444038656  NOTICE: special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
21:52:46 T:18446744072444038656  NOTICE: special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
21:52:46 T:18446744072444038656  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
21:52:46 T:18446744072444038656  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
21:52:46 T:18446744072444038656  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
21:52:46 T:18446744072444038656  NOTICE: The executable running is:
21:52:46 T:18446744072444038656  NOTICE: Local hostname: localhost
21:52:46 T:18446744072444038656  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
21:52:46 T:18446744072444038656  NOTICE: -----------------------------------------------------------------------
21:52:46 T:18446744072444038656  NOTICE: load settings...
21:52:46 T:18446744072444038656   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
21:52:46 T:18446744072444038656 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
21:52:46 T:18446744072444038656   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
21:52:46 T:18446744072444038656   DEBUG: AESinkAUDIOTRACK - 44100 supported
21:52:46 T:18446744072444038656   DEBUG: AESinkAUDIOTRACK - 48000 supported
21:52:46 T:18446744072444038656   DEBUG: AESinkAUDIOTRACK - 96000 supported
21:52:46 T:18446744072444038656  NOTICE: Found 1 Lists of Devices
21:52:46 T:18446744072444038656  NOTICE: Enumerated AUDIOTRACK devices:
21:52:46 T:18446744072444038656  NOTICE:     Device 1
21:52:46 T:18446744072444038656  NOTICE:         m_deviceName      : AudioTrack
21:52:46 T:18446744072444038656  NOTICE:         m_displayName     : android
21:52:46 T:18446744072444038656  NOTICE:         m_displayNameExtra: audiotrack
21:52:46 T:18446744072444038656  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
21:52:46 T:18446744072444038656  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR,SL,SR
21:52:46 T:18446744072444038656  NOTICE:         m_sampleRates     : 48000,44100,48000,96000
21:52:46 T:18446744072444038656  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS
21:52:46 T:18446744072444038656   DEBUG: CSkinSettings: no <skinsettings> tag found
21:52:46 T:18446744072444038656  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
21:52:46 T:18446744072444038656  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
21:52:46 T:18446744072444038656  NOTICE: Default DVD Player: dvdplayer
21:52:46 T:18446744072444038656  NOTICE: Default Video Player: dvdplayer
21:52:46 T:18446744072444038656  NOTICE: Default Audio Player: paplayer
21:52:46 T:18446744072444038656  NOTICE: Disabled debug logging due to GUI setting. Level 0.
21:52:46 T:18446744072444038656  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
21:52:46 T:18446744072444038656  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
21:52:46 T:18446744072444038656  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
21:52:46 T:18446744072444038656  NOTICE: Loaded playercorefactory configuration
21:52:46 T:18446744072444038656  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
21:52:46 T:18446744072444038656  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
21:52:46 T:18446744072444038656  NOTICE: Running database version Addons20
21:52:46 T:18446744072444038656  NOTICE: ADDONS: Using repository repository.xbmc.org
21:52:46 T:18446744072444038656  NOTICE: ADDONS: Using repository repository.vstream
21:52:46 T:18446744072444038656  NOTICE: ADDONS: Using repository repository.fightnight
21:52:46 T:18446744072444038656  NOTICE: ADDONS: Using repository superrepo.kodi.isengard.all
21:52:46 T:18446744072444038656  NOTICE: ADDONS: Using repository repository.passion.xbmc.org.gotham
21:52:47 T:18446744072444038656  NOTICE: virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: android
21:52:47 T:18446744072444038656  NOTICE: CEGLNativeTypeAndroid: Switching to resolution:
21:52:47 T:18446744072444038656  NOTICE: Current resolution: 1920x1080 @ 50.00 - Full Screen
21:52:47 T:18446744072444038656  NOTICE: Previous line repeats 1 times.
21:52:47 T:18446744072444038656  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
21:52:47 T:18446744072444038656  NOTICE: Found (1920x1080@50.000000) at 16, setting to RES_DESKTOP at 16
21:52:47 T:18446744072444038656  NOTICE: Checking resolution 16
21:52:47 T:18446744072444038656  NOTICE: Current resolution: 1920x1080 @ 50.00 - Full Screen
21:52:47 T:18446744072444038656  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 1920x1080 @ 50.00 - Full Screen
21:52:47 T:18446744072444038656  NOTICE: GL_VENDOR = Vivante Corporation
21:52:47 T:18446744072444038656  NOTICE: GL_RENDERER = Vivante GC4000
21:52:47 T:18446744072444038656  NOTICE: GL_VERSION = OpenGL ES 2.0 V5.0.11.p6.31013
21:52:47 T:18446744072444038656  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.00
21:52:47 T:18446744072444038656  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_half_float GL_OES_element_index_uint GL_OES_mapbuffer GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_rgb8_rgba8 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_depth24 GL_OES_depth32 GL_OES_packed_depth_stencil GL_OES_fbo_render_mipmap GL_OES_get_program_binary GL_OES_fragment_precision_high GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_dxt1 GL_EXT_texture_format_BGRA8888 GL_EXT_texture_compression_s3tc GL_EXT_read_format_bgra GL_EXT_multi_draw_arrays GL_EXT_frag_depth GL_EXT_discard_framebuffer GL_EXT_blend_minmax GL_EXT_multisampled_render_to_texture GL_EXT_robustness GL_VIV_direct_texture
21:52:47 T:18446744072444038656  NOTICE: Current resolution: 1920x1080 @ 50.00 - Full Screen
21:52:48 T:18446744072444038656  NOTICE: Running database version Addons20
21:52:48 T:18446744072444038656  NOTICE: Running database version ViewModes6
21:52:48 T:18446744072444038656  NOTICE: Running database version Textures13
21:52:48 T:18446744072444038656  NOTICE: Running database version MyMusic56
21:52:48 T:18446744072444038656  NOTICE: Running database version MyVideos99
21:52:48 T:18446744072444038656  NOTICE: Running database version TV29
21:52:48 T:18446744072444038656  NOTICE: Running database version Epg11
21:52:48 T:18446744072444038656 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
21:52:49 T:18446744072444038656  NOTICE: ActiveAE DSP - starting
21:52:49 T:18446744072444038656  NOTICE: initialize done
21:52:49 T:18446744072444038656  NOTICE: Running the application...
21:52:49 T:18446744072444038656  NOTICE: starting zeroconf publishing
21:52:49 T:18446744072444038656  NOTICE: starting upnp client
21:52:49 T:18446744072045627520  NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777
21:52:49 T:18446744072444038656   ERROR: JSONRPC Server: Failed to bind ipv4 serversocket
21:52:49 T:18446744072444038656  NOTICE: Current resolution: 1920x1080 @ 50.00 - Full Screen
21:52:49 T:18446744072444038656  NOTICE: GL_VENDOR = Vivante Corporation
21:52:49 T:18446744072444038656  NOTICE: GL_RENDERER = Vivante GC4000
21:52:49 T:18446744072444038656  NOTICE: GL_VERSION = OpenGL ES 2.0 V5.0.11.p6.31013
21:52:49 T:18446744072444038656  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.00
21:52:49 T:18446744072444038656  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_half_float GL_OES_element_index_uint GL_OES_mapbuffer GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_rgb8_rgba8 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_depth24 GL_OES_depth32 GL_OES_packed_depth_stencil GL_OES_fbo_render_mipmap GL_OES_get_program_binary GL_OES_fragment_precision_high GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_dxt1 GL_EXT_texture_format_BGRA8888 GL_EXT_texture_compression_s3tc GL_EXT_read_format_bgra GL_EXT_multi_draw_arrays GL_EXT_frag_depth GL_EXT_discard_framebuffer GL_EXT_blend_minmax GL_EXT_multisampled_render_to_texture GL_EXT_robustness GL_VIV_direct_texture
21:52:49 T:18446744072045627520  NOTICE: UDP: Listening on port 9777
21:53:41 T:18446744072046654848  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:53:41 T:18446744072046654848  NOTICE: 	[PLUGIN] Vstream: call load methode
21:53:43 T:18446744072046654848  NOTICE: 	[PLUGIN] Vstream: Table initialized
21:53:47 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showSources
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Root Folder /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Sites Folder /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin adkami_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin alluc_ee
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin buzzmonclick_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin cinemay_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin docspot_fr
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin enquetedereportages_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin filmstreamingz_fr
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin filmstreamvk_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin filmsvostfr_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin film_illimit_fr
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin film_streaming_co
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin freebox
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin frenchstream_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin fullmoviz_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin full_streamvk_net
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin full_stream_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin hd_stream_in
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin kepliz_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin les_docus
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin libertyland_tv
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin libre_stream_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin mangacity_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin mareplaytv
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin megastream
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin neuf_docu
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin planet_streaming
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin regarder_films
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin reportagestv_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin seriefr_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin series_en_streaming_tv
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin serie_streaming_watch
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin sokrostream_biz
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin spion_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin streamcomplet
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin streamingk_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin streaming_series_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin streaming_series_xyz
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin streamzer_net
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin streamzzz_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin themoviedb_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin tntv_rattrapage
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin tv_streaming_ch
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin videobuzzy_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin vkstreamingfilm_biz
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin voirfilms_org
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin zone_telechargement_com
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Load Plugin __init__
21:53:48 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Cant import plugin __init__
21:53:51 T:18446744071997230080  NOTICE: 	[PLUGIN] Vstream: Table initialized
21:53:56 T:18446744072046657408  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:53:56 T:18446744072046657408  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function load
21:53:58 T:18446744072046657408  NOTICE: 	[PLUGIN] Vstream: Table initialized
21:54:02 T:18446744071989369600  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:54:02 T:18446744071989369600  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function showMovies
21:54:05 T:18446744071989369600  NOTICE: 	[PLUGIN] Vstream: Table initialized
21:54:08 T:18446744071990588288  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:54:08 T:18446744071990588288  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function showLinks
21:54:08 T:18446744071990588288  NOTICE: mode film
21:54:09 T:18446744071990588288  NOTICE: 	[PLUGIN] Vstream: close dialog
21:54:09 T:18446744071990588288  NOTICE: 	[PLUGIN] Vstream: Table initialized
21:54:12 T:18446744071997228800  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:54:12 T:18446744071997228800  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function showHosters
21:54:12 T:18446744071997228800  NOTICE: http://www.zone-telechargement.com/films/720p/150532-triple-9.html
21:54:12 T:18446744071997228800  NOTICE: 	[PLUGIN] Vstream: Table initialized
21:54:13 T:18446744072444038656   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Triple%209%20&sThumbnail=http%3a%2f%2fimages.zone-telechargement.com%2f360%2fhttp%3a%2f%2fimages.allocine.fr%2fpictures%2f16%2f02%2f24%2f18%2f01%2f453823.jpg&site=zone_telechargement_com&siteUrl=http%3a%2f%2fwww.zone-telechargement.com%2ffilms%2f720p%2f150532-triple-9.html&title=Triple%209%20%20-%20%5bCOLOR%20skyblue%5dHD%20720p%20(TRUEFRENCH)%5b%2fCOLOR%5d
21:54:13 T:18446744072444038656   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Triple%209%20&sThumbnail=http%3a%2f%2fimages.zone-telechargement.com%2f360%2fhttp%3a%2f%2fimages.allocine.fr%2fpictures%2f16%2f02%2f24%2f18%2f01%2f453823.jpg&site=zone_telechargement_com&siteUrl=http%3a%2f%2fwww.zone-telechargement.com%2ffilms%2f720p%2f150532-triple-9.html&title=Triple%209%20%20-%20%5bCOLOR%20skyblue%5dHD%20720p%20(TRUEFRENCH)%5b%2fCOLOR%5d) failed
21:54:25 T:18446744072444038656  NOTICE: Storing total System Uptime
21:54:25 T:18446744072444038656  NOTICE: Saving settings
21:54:25 T:18446744072444038656  NOTICE: stop all
21:54:25 T:18446744072444038656  NOTICE: stop player
21:54:25 T:18446744072444038656  NOTICE: ES: Stopping event server
21:54:25 T:18446744072444038656  NOTICE: stopping upnp
21:54:25 T:18446744072444038656  NOTICE: stopping zeroconf publishing
21:54:25 T:18446744072045627520  NOTICE: ES: UDP Event server stopped
21:54:25 T:18446744072444038656  NOTICE: stop sap announcement listener
21:54:25 T:18446744072444038656  NOTICE: clean cached files!
21:54:25 T:18446744072444038656  NOTICE: unload skin

**Comment by johngf** [comment]
le mieux est d'attendre la maj mais essaye ça télécharge ce fichier puis remplace le tiens par copier/coller dans plugin.video.vstream/resources/sites
https://www.libndown.com/download?id=2IXATZOJQMS0YCK

**Comment by mino60** [comment]
Essayé ce plugin  : 
h ttp://www47.zippyshare.com/v/cQTfnCZU/file.html
utiliser l'outil dcc pour entrée don AppData
DCC : h ttp://www5.zippyshare.com/v/8gzTn6g2/file.html
utiliser urlresolver sur paramètres vstream cochée la case associée Activer.

**Comment by TmpName** [comment]
Le reinstaller ne sert a rien, la version livre avec la version 0.4.4 n'est pas a jour, c'est normal, le fichier a evolue depuis.
Il faut l'installer, et attendre que Vstream propose la MAJ.
De memoire c'est tout le temps en rose, c'est pour indiquer les sites utilisant des hosters speciaux (DDL au lieu de streaming)

**Comment by darky78** [comment]
Merci johngf! ton fichier a résolu le probleme.

J'avais pourtant télécharger le fichier de l'autre post... mais sans succès (ça ne marchais pas après le copier/coller), en tout cas avec le tiens ça marche nickel!

Problème résolu, merci encore!

**Comment by johngf** [comment]
je pense que tu as oublié de cliquer sur raw pour copier coller la premiere fois.

**Comment by darky78** [comment]
je confirme, je n’avais pas cliquer sur RAW en copiant le fichier de l'autre post! Par contre le donwload direct avec le lien que tu as fournis plus haut marche parfaitement, merci encore.

**Comment by Xiaomisenz1** [comment]
Bonjour, encore une fois merci pour cette excellent addon, moi c'est ai niveau des recherches visuels que j'ai un soucis, lorsque je sélectionne un film il ne me trouve que sur 3 sources, avant j'avais plusieurs choix sur toutes les sources, maintenant j'ai que trois ou quatre sources ou je peux choisir

**Comment by johngf** [comment]
oui j'ai le meme soucis la cause et film-streaming.co apparament il fait planté la recherche

**Comment by TmpName** [comment]
Chez moi j'ai plus de resultats, pas de soucis avec film-streaming-co mais effectivement il me manque des sites.

J'y jete un oeuil la.

**Comment by darky78** [comment]
Effectivement j'avais aussi trouver hier quelques liens zone telechargement qui ne marchais toujours pas, la dernière version a corriger tous ces petites problèmes, magnifique! ça tourne du tonnerre maintenant, merci!
