### ISSUE TITLE
Probléme lien "v2" avec zone-telechargement

### ISSUE THREAD

**Issue by mako83** [Kodi-vStream/venom-xbmc-addons#511]
Bonjour,

Je viens vous signaler un petit problème je suis amateur de mangas et  je les regarde via la source zone-téléchargement et dans l'ensemble cela fonctionne très bien.

Mais sur certain mangas tels que dragonball z super on ne peut pas visionné l'episode 53,54,55,56 on à seulement marqué en rouge V2 alors que via le site sur un pc cela est possible

(Ce probléme est là pour plusieurs mangas one piece,naruto etc)

Si vous avez une solution ou autres merci :) !

**Comment by johngf** [comment]
regarde ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/486

**Comment by TmpName** [comment]
Je suis dessus.

**Comment by mako83** [comment]
Tout d'abord merci de vos réponse,

Cool que c'est en cours de résolution :) ça fait plaisir un suivie pareil de l'extension ! 
Car c'est vraiment compliqué de regarder des mangas.

J'aurais d'autre question y'a t'il possibilité par exemple de démarré VSTREAM et que celui ci démarre  directement sur  la source zone telechargement? car c'est la seul source que j’utilise sur Vstream

**Comment by TmpName** [comment]
Nope ce n'est pas possible, et je ne pense pas que cela se fasse justement pr montrer que les autres sites ont egalement des videos qui peuvent fonctionner quand tel ou tel site ne marche plus.

**Comment by mako83** [comment]
d'accord et cela est il possible que quand je démarre kodi, vstream démarre automatiquement?

**Comment by johngf** [comment]
peut être avec un script voir si ça déjà été fait recherche sur google

**Comment by mino60** [comment]
Tu peux utiliser les widgets (disponible dan le skin Aeon Nox:5)
voir ici: 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/424

**Comment by johngf** [comment]
mako83 si tu cherche toujours comment lancé vstream au démarrage de kodi #657
