### ISSUE TITLE
cUtil().DecoTitle

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#515]
la pise en compte par decotitle des épisodes du genre 422-423 ou 07.5

**Comment by TmpName** [comment]
Alors la, j'ai pas le site qui pose probleme devant les yeux, mais essayes de voir dans la fonction FormatSerie() du fichier utils.py, ligne 156
[0-9] a remplacer par [0-9.-]
Ca va prendre tout les chiffres ainsi que . et - sans modidier le reste, donc normallement ca ne peut pas faire bugguer le reste.

**Comment by johngf** [comment]
Après avoir essayé sans succès je me demandais si c'était possible apparament non donc j'ai commencé a partir du fichier site.
pour 422-423 le problème est le - une fois supprimé on obtient E422423. 
maintenant j'arrive a les isoler avec re.search ou re.findall('(\d+)[- _](\d+)',sTitle) reste plus qu'a supprimer le - uniquement pour ce genre d'épisode ou alors ne pas utiliser décotitle et tenté de colorer la fin pour avoir un look uniforme.

**Comment by johngf** [comment]
cela fonctionne avec ce code j'obtiens E422423
`            p = re.search(r'(\d+)[- _](\d+)',sTitle)
            if p:
                sTitle = re.sub(r'(\d+)[- _](\d+)', p.group(1) + p.group(2) ,sTitle) 
            else:
                sTitle = aEntry[1]`

**Comment by TmpName** [comment]
J'y jette un oeuil des que je recupere la tv.
Mias moiu je laisserais E422-423 ou E422E423, sinon ca donnerait episode numero 422423.

Et les modifs sont a faire dans le fichier utils.py pour que cela marche sur tout les sites.

**Comment by TmpName** [comment]
Bon j'ai fait quelques modifs mais me faudrait le site ou tu vois ces problemes que je puisse tester.

**Comment by johngf** [comment]
pas fini et a optimiser mais fonctionelle le site a ajouter http://pastebin.com/bEffC30N 
pour tester ta modif : toutes les sources/otakufrcom/animpopulaire/naruto

**Comment by TmpName** [comment]
Essaye avec ce fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/util.py

**Comment by johngf** [comment]
nickel je m'étais rendu compte que le probleme etait a cause de int() et finalement la solution est plus simple que je pensais

**Comment by johngf** [comment]
pour ceux avec des espaces ou _  celui ci fonctionne `m = re.search( ur'(?i)(\wpisode ([0-9- _]+))(?:$| [^a\u00E0])',string,re.UNICODE)`

**Comment by TmpName** [comment]
Pour le _ on peut le rajouter mais pour l'espace j'ai peur que cela provoque des bugs, comme si on a "serie truc episode 1 2 eme partie" surtout que dans la deuxieme partie du regex j'attend justement un espace (?:$| [^a\u00E0].

Tu as vraiement beacoup de leins qui deconnent a cause cet espace ?

**Comment by johngf** [comment]
en faite sans l'espace il reste genre  422 blanc et 423 couleur

**Comment by johngf** [comment]
sinon je pense que je vais récupérer la 2eme partie du titre de l'épisode généralement mieux formaté
exemple Naruto Shippuden Ep-465 (mauvais)- Naruto Shippuden 465 vostfr (bon)

**Comment by TmpName** [comment]
Je preferais autant, vu que je ne peux pas garantir le resultat, par contre je rajoute le _ dans le fichier.

**Comment by johngf** [comment]
j'ai testé il faut enlever le _ du fichier util sinon bug sur certain le titre se colore aussi

**Comment by TmpName** [comment]
Ca buggue sur des titres ?
Lequel par exmple ?

**Comment by johngf** [comment]
la c'est ok . pour ce qui est des espaces pour assurer l'uniformité
`sTitle = re.sub(r'(\d+)[ ](\d+)', p.group(1) + "-" + p.group(2) ,aEntry[1]) `
dans le fichier site et c'est bon.

**Comment by TmpName** [comment]
Nickel ^^

**Comment by johngf** [comment]
je viens de remarqué que la modif de util.py rajoute un zero sur les épisodes de adkami et mangacity

**Comment by TmpName** [comment]
Je viens de verifier, en fait avant il y avait une fonction pour reformater le chiffre au format XX, donc 2 devenait 02 et 002 devenait aussi 02.
La j'ai juste fait une fonction pour passer 2 a 02 car la syntaxe de base c'est SXXEXX, du coup ceux avec 3 chiffre restent comme ca, mais c'est pas genant Alluc gere aussi les SXXEXXX, surtout que les animes ont souvent plus de 100 episodes, c'est surement pr ca que leurs sites les notent avec 3 chiffres en standard.
