### ISSUE TITLE
vStream as a backend

### ISSUE THREAD

**Issue by romainvv** [Kodi-vStream/venom-xbmc-addons#518]
Bonjour,

Est-ce possible d'avoir vStream en tant que backend, j'aimerai avoir les chaines accessibles et intégrés sous télévision (PVR) et pas sous addons. Est-ce possible ?

Merci

**Comment by LordVenom** [comment]
Oui c'est possible en utilisant l'add-on IPTV simple il me semble.

url tv du web:
https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons/master/repo/resources/webtv2.m3u

url framapad:
https://annuel.framapad.org/p/vstream/export/txt

Pour l'XMLTv je te conseil http://kazer.org/

Voila avec c'est infos et un peux de recherche tu doit pouvoir faire ceux que tu veut, bon courage.
N’hésite pas a partager ta démarche pour aider les autre utilisateur :+1:
