### ISSUE TITLE
Problème téléchargement ZT et marque page

### ISSUE THREAD

**Issue by K3R0ZEN** [Kodi-vStream/venom-xbmc-addons#519]
Messieurs dames, Bonjour.

Pour commencer je tiens a vous remercier pour cette merveilleuse App qui est vraiment au top. 

Ma femme et moi l'utilisons quotidiennement.

Je me permet de vous faire remonter 2 petit souci que nous avons remarquer il y a peu.

La premier est avec les marques pages. En effet il fonctionne mais malheuresement une fois a l'intérieur les jaquettes des films n'apparaisse plus et les icônes son buggé.

La deuxième chose concerne le téléchargement a proprement parler. En général quand je regarde un film j'aime bien utiliser le fameux "DL et visualiser" mais plus rien ne se passe. Vstream me dit bien enregistrés avec succès, il temine bien dans les téléchargement mais ne démarre pas, même manuellement. Enfin même si je sélectionne seulement télécharger même combat, rien ne se lance.

Je tiens a preciser que cela fonctionner encore il y a quelques jours et que j'utilise un débrideur. A priori le problème ne viens pas de chez moi.

Encore une fois félicitations pour se Vstream au pti oignon et pour votre dévouement.

Belle soirée a vous.

K3R0ZEN

**Comment by K3R0ZEN** [comment]
Ok petite modification. Je viens de me rendre compte que les Films que je mets en Marque Page vienne se mettre dans la catégorie "Divers" et effectivement les jaquettes n'apparaisse pas. Par contre je ne comprends pas vraiment pourquoi mais un seul Film mis en marque page a bien fini dans la catégorie "Films". Du coup la jaquettes est bien visible mais si j'essai de le lancer rien ne se passe, juste écrit "en cours" puis plus rien.

Bon j'espère ne pas vous avoir perdu... 

Merci

**Comment by TmpName** [comment]
Alors pour les bugs j'y jete un oeuil des que je recupere la tv mais pour le coup des favoris, une petite explication.
Quand tu lances une recherche, tu peux avoir n'importe quoi a l'ecran serie comme film, du coup si tu met en favoris cette page la ca va partir en divers. Si tu selectionne le film, Vstream devine que c'est un film et si tu met en favoris cette deuxieme page elle va partir en film.

Pour le coup des DL:
Essaye justement sans debrideurs, eg uptobox marche en gratuit, pour voir si le prb ne vient pas justement du debrideur.
Tu as teste quel host ?
Tu n'aurais pas les logs de cette partie ?

**Comment by K3R0ZEN** [comment]
Salut et merci pour ta réponse.

Je viens d'essayer a l'instant. Peu importe le host avec ou sans débrideur aucun téléchargement ne se lance.

Pour les logs je suis désolé je ne sais pas comment faire. Si tu veux bien me renseigner je te te les ferai parvenir avec plaisir.

PS :  Je suis RPI3 avec openElec 

Merci pour les marques pages je comprend mieux maintenant. 

A bientôt

**Comment by TmpName** [comment]
Je viens de tester avec uptobox, pas de prb, essaye en desactivant l'urlesolver (ce n'est pas nous qui geront cette partie).
Si vraiment ca ne marche pas sans urlresolver je t'expliquerais la procedure pour les log, mais je suspecte un prb de debrideur.

Tu aurais le nom du film ou les icones ne s'affichent pas ?

Tu as bien la derniere version de ZT ? pas d'icones verte pour la  MAJ qui apparait sur la page d'acceuil de Vstream ?

**Comment by K3R0ZEN** [comment]
Salut.

J'ai essayé avec ou sans urlresolver mais sa ne fonctionne toujours pas, je pense que le souci viens de chez moi alors je vais essayer de désinstaller puis réinstaller Vstream.

Toutefois il semble que ZT et vraiment buggé depuis fin d'après midi. Je choisi le film ou serie peu importe et au moment ou il faut choisir le choix de la qualité rien ne se passe .. J'ai essayer avec d'autre source que zone téléchargement et la pas de souci sa fonctionne. La source ZT déconne aussi bien sur mon PC que sur mon RPI3. 

Pour les icones qui ne saffiche pas t'en fait pas, cela se produit uniquement si le film viens se mettre dans le marque page "divers". Dans "films" par exemple cela fonctionne.

**Comment by TmpName** [comment]
Si tu le reinstalles, tu n'auras pas la derniere version, depuis la version officielle, les fichiers ont ete mit a jour et il n'y a que la MAJ auto qui peut les mettre a jour.
Tout les 3 jours tu as une nouvlle icone qui apparait sur la page d'accueil de Vstream pour ca (il y a moyen de tricher en avancant la date de 3 jours avant de lancer vstream)

Je te dis ca car tes bugs, ressemblent aux derniers qui ont ete corriges. (MAJ de uptobox, icones et lien qui n'apparaissaient pas)

La j'ai re-teste sur un film qui est partit en divers, pas vu de prbs.

**Comment by K3R0ZEN** [comment]
Tes un chef. Tout fonctionne si je fait la mise a jour. Du moins sur le PC parce que j'ai comme un problème sur mon RPI qui tourne avec OpenElec, impossible de changer la date. L'heure j'y arrive en simulant un autre pays de residence mais la date non.

Si tu as une idée je suis preneur. En tout cas encore merci d'avoir pris le temps de me dépatouiller.

Super boulot.

**Comment by TmpName** [comment]
Quelqu'un avait propose une solution mais je la retrouve pas, en fait tu peux simplement copier/coller le fichier prit directement sur le site, mais si ca se trouve la MAJ va t etre proposée dans les heures a venir.

**Comment by K3R0ZEN** [comment]
D'accord , je viens d'essayer en récupérant le zip sur le site (plugin.video.vstream-0.4.4.zip) mais malheureusement pour moi sa ne change rien. Tu parler bien de se fichier ?

**Comment by TmpName** [comment]
Non pas du tout, celui la c'est celui que tu obtient en installant Vstream.
Celui a jour c'est https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_com.py

**Comment by K3R0ZEN** [comment]
Ah merci, par contre je suis vraiment désolé de faire mon boulet mais je ne comprend pas comment télécharger se fameux fichier .py et encore moins ou le coller par la suite ... Je ne trouve pas de bouton DL alors je pense que je peu faire un copié/collé mais ou le coller 😉

**Comment by K3R0ZEN** [comment]
Ok ne t'embête pas j ai fini par trouver ou coller le tout 😊

J'ai donc désinstaller Vstream puis réinstaller avec mon nouveau Zip modifier. 

Alors il y a du mieux mais sa ne fonctionne toujours pas. Je selectionne mon film mais je ne vois aucun hebergeur.. C a y perdre la tête lol

**Comment by K3R0ZEN** [comment]
Oups il n'y a pas de commande éditer. J'ai oublié de te dire que curieusement a chaque fois que je désinstalle Vstream et même en supprimant le cache, a la reinstall il garde toutes mes préférence . j'arrive jamais a repartir sur une install propre ..

**Comment by TmpName** [comment]
Oui les preferences sont dans un autre repertoire.
Normallement tu installes le repo de Vstream, et pas le zip de vstream.
Tu avances la date de 3jours (ou 6 si tu l'as deja fait).
Une nouvelle icone apparait sur la page d'accueil de vstream pour une MAJ.

Si ca ne marche pas, essayes de nous faire passer les logs (sur pastebin, surtout pas de copiercoller)
Methode assez vielle ht tp://media-passion.fr/support-general-des-addons/comment-recuperer-les-logs-et-decrire-un-probleme-avec-un-scriptplugin/

**Comment by K3R0ZEN** [comment]
Ok je comprend mieux pour les preferences.
Pour mon cas je devait réinstaller le zip de Vstream car j'avais modifier le fichier de ZT manuellement. Enfin je pense qu' il fallait faire comme sa.

En effet changer la date pourrait être la solution mais j'ai retourner internet et je ne trouve rien sur une quelquonque possibilité de la modifier.

Je vais prendre mon mal en patience et attendre la mise a jour auto 😉

Si sa ne marche pas je t'enverrai le log .

Encore une fois merci TmpName pour ton aide précieuse et bonne fin de journée.

**Comment by K3R0ZEN** [comment]
Salut TmpName,

Juste pour t' informer que j'ai bien eu une mise a jour se matin et que enfin tout re fonctionne 😊

Par contre un nouveau souci, les téléchargement sont très lent environ 50 ko/s alors que je télécharge a 2 mo/s . j'ai essayer sur plusieurs films et plusieurs hébergeur pourtant. Activer et desactiver le resolver. 

Sur le pc par contre pas de souci. Alors je ne sais pas si c'est pareil pour tout le monde ou seulement moi .

J'ai même essayer d'installer Jdownloader sous kodi voir si sa m'aider mais apparemment il  ne fonctionne plus.

Bonne journée.

**Comment by TmpName** [comment]
C'est fait expres ^^.
Il y a un bridage sur les telechargements, Kodi est fait en priorite pour lire les medias, ce n'est pas un outil pour dl des fichiers, c'est pour eviter d'avoir des saccades sur le film que tu regarde a cause d'un dl en arrierre fond.
Pour virer le bridage, fichier download.py, ligne 50
>self.__bFastMode = True

**Comment by K3R0ZEN** [comment]
Ah C'est bon a savoir. Par contre le fameux download.py je le trouve seulement dans le ZIP d'installation Vstream, alors je peu le modifier pour ensuite le réinstallé mais il faudra encore que j attende 3 jours pour que tout fonctionne.

Je suppose qu il y a un moyen de le modifier directement mais je ne trouve pas où. En mettant la carte micro sd dans mon pc je ne trouve rien sur Vstream. Donc pas de download.py. Arf je galère. 

Il y a bien un dossier system sur ma micro Sd mais je ne sais pas comment l'ouvrir..

**Comment by TmpName** [comment]
C'est con que personne avec ton systeme ne passe par ici pour te repondre, je sais que tu peux bidouiller tes fichier en te connectant en SSH, et qu'il se peut que tes fichiers soit caches par defaut.
Jetes un oeuil dans /storage/.kodi/addons/plugin.video.vstream/resources/

Si tu modifie le fichier DownLoad.py, il sera effectif des ta modif, celui n'est mit a jour que lors de la MAJ de Vstream (1 fois par mois), pas d'histoire de 3 jours qui ne concerne que les fichiers sites et hosts.

Par contre si tu prend DL et visionner, il n'y a plus de bridage. C'est normal, le but et de regarder le film en meme temps que le DL, donc oblige d'aller a fond sinon au bout d'un moment il n'y a pas assez de fichier a lire. En fait c'etait une astuce pour les users qui n'avaient pas de premium, donc qui ne pouvaient pas streamer, il suffisait de dl le fichier et de le lire en meme temps.

**Comment by K3R0ZEN** [comment]
Ah ah tes un champion TmpName, tu ma bien aiguiller du coup je suis arrivée a avoir un accès à download.py en modifiant mon fichier samba.conf 😊

Maintenant sa télécharge plus rapidement mais c'est pas encore le top du top, je t'explique.

Enfaite quand je fait visionner et DL le téléchargement et très rapide les 20 premières seconde, au max de ma connexion (je suppose que c'est voulu pour démarré la video le plus vite possible) et ensuite sa telecharge 2 mo puis sa fait une pause de 3 seconde puis hop encore 2 mo etc ... 

La du coup en passant la commande en "True" sa me fait la même chose.

En résumé y a t il une autre ligne de commande que je peu modifier pour lui donner le droit de DL au max sans interruption ?

**Comment by TmpName** [comment]
La par contre je ne pense pas que cela vient de Vstream, ca doit venir de l'hebergeur, je crois qur flashX marche comme ca, jamais eu de prbs sur uptobox.
Normalement le code fait une boucle dans un thread separe, le seul truc qui peut la ralentir c'est quand Vstream attend les données du serveur.

Ce n'est pas nous qui agissons sur le ralentissement au bout de 20s, un thread qui DL aussi vite qu'il peut et un autre qui lit ce meme fichier au bout de quelques secondes, pas de reel "tampon" vu que le "tampon" est le fichier DL.

**Comment by K3R0ZEN** [comment]
Ok. C'était vraiment pour chipoter parce que sa marche déjà très bien comme sa.

Merci pour toutes les astuces et explications. 

Continuer a faire du bon boulot c'est vraiment apprécié. J'ai auparavant essayer d'autre appli dont je ne citerai pas forcément les noms et je doit dire que Vstream est vraiment mon coup de coeur.

Belle journée a toi TmpName. @++

**Comment by sengoku86** [comment]
bonsoir, je viens de lire tout le post et je crois qu'il m'arrive la même chose. J'avais installé kodi sur ma bbox miami et avec vstream couplé avec un compte premium. Donc regarder des series sur ZT c'était nickel en plus de pouvoir choisir la qualité du visionnage. 

Donc je m'explique, erreur de ma part je désinstalle l'appli de ma box. Donc j'essaie de resinstaller pas de soucis ! cependant dès que j'installe vstream il fonctionne mais mes liens sur ZT n'apparaissent plus ! Je sais plus quoi faire.

De plus comment peut on forcer une mise à jour ou comment faire pour changer le défaut des 3 jours ?

Merci d'avance de votre aide 

A plus Seng

**Comment by K3R0ZEN** [comment]
Salut Sengoku,

Ton souci ressemble effectivement au mien. Le truc qui corrigera ton problème sera sans doute la mise a jour qui arrive tout les 3 jours.

Pour la forcer il faut donc tromper Vstream en avançant la date de 3 jours.

Je n'ai pas de Bbox miami alors je ne pourrai pas t'aider sur le comment faire mais tu trouvera certainement avec une recherche google. 

Si malheureusement tu ne peu pas changer la date ( comme moi sur raspberry pi) il va falloir prendre ton mal en patience.

Bon courage.

**Comment by sengoku86** [comment]
Salut K3R0ZEN de ta réactivité !!! je vais voir si je peux faire quelquechose pour la date !! 

sinon comme tu dis je vais attendre dans 3 jours !!

merci encore et je te ferai un retour .

A plus.

**Comment by TmpName** [comment]
En fait ce probleme est normal.
Quand tu installes Vstream la premiere fois, tu as le mauvais fichier site, mais Vstream te propose de le mettre a jour, et enregistre la date dans tes parametres.
Quand tu le desinstalle, ca supprime les fichiers, mais pas les parametres.
La deuxieme fois que tu l'installe, il te remet le mauvais fichier site, mais ne te propose pas la MAJ avant la date prevue, donc tu restes avec la mauvaise version.

Faut voir avec LordVenom qui connait mieux le fonctionnement de sa bete, mais pour moi c'est normal. La desisntal est gere par Kodi, donc si il ne veut pas supprimer le fichier de config on y peut rien.
Et lors de la reinstall, on ne peut pas detecter que c'est le premier lancement si le fichier de config est deja la.
