### ISSUE TITLE
les liens openload de nouveaux inacessibles

### ISSUE THREAD

**Issue by natzen** [Kodi-vStream/venom-xbmc-addons#521]
Bonjour , malheureusement les liens openload sont de nouveaux introuvable :-(
.
si quelqu'un à une solution ce serait top
Merci

**Comment by TmpName** [comment]
Lol, comme tout les 7 jours, je jette un oeuil ce matin.

**Comment by TmpName** [comment]
Corrige.

**Comment by natzen** [comment]
oui ça ouvre une video mais pas la bonne ,c'est ecrit que on utilise un lien contrefait ... :-(

**Comment by TmpName** [comment]
Ha oui merde, ca a pas dure longtemps, je corrige ca.

**Comment by TmpName** [comment]
C'est bon c'est corrige, et cette semaine je pense que je vais plancher sur une nouvelle methode pour ce host.

**Comment by Phobos1337** [comment]
Je vais voir aussi ce que je peux faire pour aider ^^

**Comment by TmpName** [comment]
En fait j'attend leur prochaine modif pour voir, mais a chaque fois leur lien chnage d'une seule lettre (et d'un decalage de 3 max).
Docn si je galere pour trouver la bne lettre je teste les 5 liens et je lancerais celui qui n'affiche pas les pigeons. Du coup plus besoin de chercher la bonne lettre.

**Comment by johngf** [comment]
cette fois ci ça fait comme flashx la dernière fois faut insister pour avoir le bon lien de la video

**Comment by TmpName** [comment]
Je viens de mettre a jour openload, avec AAdecoder et le nouveau codage.

Pour l'explication, ils changent leur codage tres souvent, mais toujours de peu, donc j'avais rajoute la derniere fois une options qui detecte les videos de pigeons et qui essaye au hazard 4/5 variantes en fonction de la premiere url quand ca ne marche pas.
Ce n'est pas infaible mais ca evite d'avoir a corriger toute les semaines.

Mais bizarrement ca ne devrait pas marcher quand c'est les pigeons, si tu as les pigeons ca m'interesse d'avoir ton log a ce moment. Pour info je fais le test l72, vu que chez moi le fichier a tjours le meme nom.

**Comment by johngf** [comment]
bah j'ai du bidoullé quelque chose parcequ'il ne me les affiche plus

**Comment by TmpName** [comment]
Avant ou apres ma modif ?
Car j'ai aussi modifie l algo, et du coup il trouve direct le bon lien, donc plus de pigeons.

**Comment by johngf** [comment]
j'ai bidouillé avant la modif pour ça les pigeons, la c'est bon il y en a plus
