### ISSUE TITLE
Zone-telechargement 

### ISSUE THREAD

**Issue by Brahimbaz** [Kodi-vStream/venom-xbmc-addons#525]
Bonjour à tous, 
Je vous explique mon cas.
J'ai vstream sur ma freebox 4k, sur mon smartphone, sur une box android dans la chambre, je l'ai installé chez ma belle soeur, chez des amis. Et la j'ai un ami qui vient d'acheter une box android pour lui installer vstream sur kodi . Donc tout s'installe nikel. Je vais dans les serie et film nikel. Mais des que je choisi le format de la video hdtvvf 720pvf 1080pvf etc la rien ne s'ouvre ca charge mais ca reste au même endroit. Avez-vous déjà eu le même problème et trouvé une solution? Jai essayé avec la version 4.4 et 4.3 rien ne change. Merci de vos réponses

**Comment by TmpName** [comment]
Normallement apres l'installation, (ca met max 3 jours), tu as une nouvelle icone sur la page d'acceuil de Vstream pour mettre a jour les sources, il te suffit de cliquer dessus.
Si tu l'as deja fait, c'est qu'on a un prb ^^.

Tu peux aussi tricher en avancant la date de l'ordi de 3 jours avant de lancer kodi.

Par contre je pensais que a la premiere install, ca verifiait les MAJ ? Normallement tu aurais du avoir cette icone des la premiere fois.

**Comment by Brahimbaz** [comment]
Merci TmpName! J'ai avancé la date de 3 jours et ca m'a proposé la maj. Et la miracle ca marche lol. 
Merci beaucoup pour l'astuce.
Je l'ai installé il y a 3 semaine sur une autre box ca ne m'avait pas fait ce beug. 
En tout cas merci je saurais quoi faire pour les futures installation.
