### ISSUE TITLE
Ajouter une chaine iptv

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#526]
BonSoir..

je voulez ajouter une chaine iptv sur la page : h ttps://annuel.framapad.org/vstream
mais j'ai trouver tout les liens ce termine par ts par contre le site : h ttps://livego.tv/live-streams/bt-sport-1-live-stream.html par exemple idm me donne un lien :  rtmp:xxxxx/xxxx/xxxx=1
est ce que je peut mettre ce lien dans la liste framapad/vstream

pour ce enregistré sur le site livego.tv  utiliser cette carte: 

Édit de venom hou la non lol

**Comment by TmpName** [comment]
Tu peux le tester dans vlc si tu as un doute, mais oui l'extension n'est pas forcee, moi j'en ai en .php.

**Comment by LordVenom** [comment]
C'est pourquoi il y avais un n° de carte bancaire mais c'est au dessus de ce que je tolère en terme d'illegal.

**Comment by mino60** [comment]
problème de lecture avec vlc 

> Your

 input can't be opened:
VLC is unable to open the MRL 'rtmp://158.85.70.91/edge//6856?token=7f664478f240980610f9c8e9845ea117&bid=1&pid=16&uid=82406&did=53f03730da74d39e5953bf9fa024e10f&g=1&gm=1&platform=1'. Check the log for details.

**Comment by TmpName** [comment]
Donc ca repond a ta question, si vlc ne peux pas, kodi non plus, apres tu peux chercher pkoi (peut etre ces fameux logs) surement un prb d authentification vu que ce sont des liens payants.
