### ISSUE TITLE
Kodi Vsteam Uptobox Premium

### ISSUE THREAD

**Issue by 000Gunther000** [Kodi-vStream/venom-xbmc-addons#531]
Bonsoir à tous,

J'utilise depuis peu (2 jours ! c'est très très peu ^^) Kodi + Vsteam.
J'ai depuis un certain temps un compte Premium Uptobox.

Mais malgré le fait d'aller dans les paramètres de Vsteam et d'entrer mes identifiants Uptobox et de l'activer, les vidéos Uptobox proposées par Znoe Telehcargmeent ne se lisent pas !

Dès que je souhaite lire une vidéo, l'icone en bas à droite "en cours" s'affiche, puis disparait instantanément sans même faire apparaître de message d'erreur.

J'ai pourtant suivi quelques posts à ce sujet (maintenant fermés) comme le #455 mais rien n'y fait !

Je ne passe par aucun VPN.

Merci d'avance pour votre aide :)

**Comment by TmpName** [comment]
Verifie que sur ton compte uptobox (sur navigateur) tu n'ais pas coche "téléchargement direct" et "telechargement SSL".

Dis moi si c'est ca, si c'est le cas je vais peut etre avoir un fichier a te faire tester, vu que tu n'es pas le premier dans ce cas.

**Comment by TmpName** [comment]
Des news ?

**Comment by 000Gunther000** [comment]
Salut TmpName !

Je viens de me rendre compte que tu es l'un des auteurs de cette extension !!! Felicitations !!! Ca a quand même vachement de gueule Vstream !!! :)

J'ai bien vérifié que mon compte Uptobox ait bien ses options de décochées : OK, tout décoché

Dès l'installation de Vstream, je suis en 0.4.4, aucune mise à jour ne m'a été proposée 
(même en faisant "mettre à jour" en antidatant de 3-4 jours mon Windows).
Même après avoir réinstallé Kodi (sait-on jamais), toujours le message : 
"Il n'y a actuellement pas de mise à jour disponible pour cette extension" pour Vstream (même en antidatant à nouveau)

Sinon, Znoe Telecahrgemnet apparaît en rose, par rapport aux autres streamers qui apparaissent en gris.

Bref, toujours l'icône en bas à droite qui apparaît un cours instant (1/2 seconde à peine) puis disparait

En tout cas, merci pour l'intérêt que tu me portes ! :)

**Comment by jojotango** [comment]
Pour avoir les mises à jour il te faut avoir installé vStream via le dépôt <a href="https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository">Vstream Repository</a>

**Comment by TmpName** [comment]
Ok alors c'est bon, en fait ce n'est pas la mise a jour de Vstream dont je parle (celle qui est gerée par kodi).
Meme si tu as la derniere version du site, tu auras des fichiers qui ne seront pas a jour, pour les sites et hebergeurs il y a des MAJ tout les jours.
Il s'agit d'un systeme interne a Vstream, il regarde ses propres MAJ tout les 3 jours, et si tu viens de l'installer, il est impossible que tes fichiers soient a jours (vu la date de la derniere version). Sur la page d'acceuil de Vstream tu DOIS avoir une icone "Mise a jour disponible" c'est elle qui apparait en modifiant la date (la prochaine MAJ l affichera direct a la premier install, mais pas lors d'une reinstal).

La couleur rose c'est normal, c'est pour les sites "non streaming".

Mais de memoire, uptobox a été mit a jour apres la derniere version, donc sans cette MAJ interne a kodi, ca ne marchera pas, meme en installant la derniere version.

**Comment by 000Gunther000** [comment]
Quand tu parles de la page d'accueil, tu parles de : 

la page "Informations sur l'Extension" :
https://drive.google.com/open?id=0B-90DT5ePUenYWQ3YVhqQ2I2VGc

ou du menu principal ?
https://drive.google.com/open?id=0B-90DT5ePUenemJ1ajhTV1Bwd1U

Quoi qu'il en soit, même en antidatant (3 jours ou +) je n'ai pas d'icone "Mise a jour disponible" qui apparait... (je suis sous W10)
(ni même en réinstallant Vstream à partir du lien fourni par jojotango)

En tout cas, je resterai mercredi (histoire d'avoir accumulé 3 VRAIS jours) et je vous ferai un retour !

**Comment by TmpName** [comment]
Ca devrait etre sur ton 2 eme SS (menu principal), juste apres "toutes les sources".
Et la reinstallation ne changera rien, vu que ca ne remet pas a zero le fichier de configuration, et c'est la que la date est enregistree.

**Comment by 000Gunther000** [comment]
Question à part... je crois que je vais me prendre une box Multimedia Minix Neo X8-H Plus
http://www.mykodibox.fr/pages/minix-neo-x8-h-plus

Est-ce que Vstream s'installe bien sur ce genre de plateforme Android avec Kodi ?

**Comment by TmpName** [comment]
La je ne peux pas te repondre, a part que je partirais plutot sur un mini PC.
Tu as quelques exemples de systemes ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/190

**Comment by chataigne73** [comment]
Perso j'ai une mini box Android  (wetek core) et vstream marche très bien dessus ;-)

**Comment by 000Gunther000** [comment]
Bien le bonsoir !
Le jour fatidique est arrivé accompagné du bouton "Mise à jour Disponible" à la fin du menu principal, sur lequel j'ai cliqué !

Tout fonctionne nickel avec mon compte Uptobox !

Je ne comprends pas vraiment pourquoi rien n'apparaissait même en changeant la date... peut-être dû a un logiciel sur mon PC... j'en sais rien... et je confirme que si "Téléchargement Direct" est coché dans les options Premium Uptobox, Vstream ne lira pas les vidéos !

**Comment by TmpName** [comment]
Je peux pas trop te dire, je vais peut etre rajouter une ligne en debug qui affichera la date de la prochaine verif, mais comme la technique du changement de dates est une magouille non officielle, on se pose pas trop la question.

**Comment by cuisto** [comment]
j'ai entré les info de compte premieum 1fichier et uptobox.. erreur sur autantification de uptobox et je ne trouve pas 1fichier.com
