### ISSUE TITLE
problème avec page suivante film-illimite 

### ISSUE THREAD

**Issue by dias7** [Kodi-vStream/venom-xbmc-addons#532]
Salut, est-ce que vous pouvez fixer le problème de page suivante dans le site film-illimite; parce qu'elle ne s'affiche pas comme les autres sites;
Cordialement

**Comment by TmpName** [comment]
Mit a jour, merci.

**Comment by johngf** [comment]
trop rapide ^^ sinon ca fonctionne aussi avec `sPattern = 'class="current">.+?<a rel="nofollow" class="page larger" href="(.+?)">(.+?)</a>'`
`return aResult[1][0][0]`

**Comment by TmpName** [comment]
Ha ? Merde c'est vrai.
J'ai completement change la mathode car je ne ne me souvenais plus d'ou venait le regex.
Je rajoute le tiens en commentaire dans le code, plus stable que le mien.

**Comment by dias7** [comment]
Merci, ça marche bien maintenant
