### ISSUE TITLE
Demande d'ajout de source streaming HD

### ISSUE THREAD

**Issue by Manojuly** [Kodi-vStream/venom-xbmc-addons#534]
Bonjour,
Tout d'abord félicitations pour votre travail, ce plugin est génial. Et je vous en remercie car je profite de votre travail
Je souhaitais savoir si il vous est possible de rajouter une  source streaming => itazar.com anciennement nopoy
Le gros avantage c'est que tous les films sont en HD cela évite des recherches un peu plus longue pour trouver une qualité correcte
Je demande à tout hasard si pas possible tant pis, si cela est possible je vous remercie par avance pour le travail fourni
Merci

**Comment by chataigne73** [comment]
Bjr manojuly
Itazar est un clone de grudal.com, ex kepliz et qui est déjà dans vstream... donc c'est inutile

**Comment by Manojuly** [comment]
Merci pour l'information je ne savais pas :-)
