### ISSUE TITLE
rutube hs

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#535]
les liens rutube ne fonctionnent plus
`[PLUGIN] Vstream Erreur: Connection Impossible,http://rutube.ru/api/play/trackinfo/http://rutube.ru/play/embed/9724163?p=1S0w5Rn7IIV_tw1DexJy_Q/?format=json`

**Comment by TmpName** [comment]
Tu as un site qui l'utilise comme host ?

**Comment by johngf** [comment]
j'ai testé sur plusieurs adkami otakufr ...

**Comment by TmpName** [comment]
J'ai mis une nouvelle version, mais uniquement sur la beta, a tester, mais ca marche sur otaku.

**Comment by johngf** [comment]
en parlant de rutube si on recherche rutube sur global ou fullmoviz.org ca plante vstream grave avec le proc a 100%  obligé de kill kodi

**Comment by johngf** [comment]
testé sur adkami aussi résolut

**Comment by TmpName** [comment]
Ok je valide rutube du coup, et j'ai corrige fullmoviz qui bloquait tout.

**Comment by TmpName** [comment]
A propos de otaku, met le fichier sur la beta (si tu l'as fini), car la il n'y etait pas du coup depuis la MAJ ca m'a supprime le fichier.

**Comment by johngf** [comment]
c'est fait
