### ISSUE TITLE
Qu'est ce qu'il se passe avec zone-telechargement.com 

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#537]
Bonjour tous le monde,

Alors tout abord encore merci pour ce que vous faites avec Vstream. Je viens vers vous pour vous posez une question quelqu'un sait ce qu'il se passe avec le site zone-telechargement.com car c'est galère de visionner quelques chose sur cette source, on dirait que ça sent la fin non? 

Merci d'avance pour vos réponse

**Comment by johngf** [comment]
le site est surchargé ou attaque ddos enfin le site a un soucis mais rien de grave je pense

**Comment by patoche2025** [comment]
Ah ok j’espère que ca va s'arranger car ca fait quelques semaine quand même que ca dure.

Sinon j'avais laisser le code de la source : http://www.extreme-down.co/  avec des erreurs de programmation peut-etre si quelqu'un pouvait y rejouter un oeil au cas ou que le site zone-telechargement.com meurt pour de bon je croise les doigts pour que ca arrive pas

**Comment by johngf** [comment]
aprés est-ce que tu as la derniere version de zone telechargement ? il a été mise a jour récemment

**Comment by patoche2025** [comment]
Oui j'en ai eu une tantôt, tu as été cherché la dernier version sur la bêta?

**Comment by patoche2025** [comment]
non pas encore et j'avoue je suis un peu perdu je sais plus ou c'est la version beta

**Comment by johngf** [comment]
oui , sinon ton probleme est du a la navigation sur le site  ou la lecture de fichier ?

**Comment by patoche2025** [comment]
Si le site ne s'affiche pas, bah dans  kodi je sais pas faire de recherche ou lire un fichier de la source ZT et ce qu'il est normal tu vas me dire.

Ici il 8:34 et tout va bien mais pour combien de temps ? Bref j'espere que ca va devenir plus stable ( j'ai un doute ca fait 2 semaine 1/2 qu'il a un problème), je croise les doigts pour que le site reste stable.
