### ISSUE TITLE
re-captcha avec images à cocher

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#538]
salut TmpName

j'ai trouver un site intéressant, mais il utilise la variante recaptcha avec des images à cocher en fonction d'une question

ex : h**p://www.belangerfils.com/imgs/Captcha2.PNG

penses-tu que ce soit possible de l'implémenter dans vstream ?

merci

**Comment by TmpName** [comment]
Ce captcha s'appelle Recaptcha made in google.
Alors si ca t'interesse, je peux te passer pas mal d'infos la dessus, j'ai meme commence un code pour faire du "reverse engineering" dessus, mais ce que j'ai vu m'a fait peur. L'algorythme est vraiment tres lourd, tellement lourd que pour lui je pense que meme si tu prend une lib speciale qui utilise un "navigateur" pour executer le code, ce serait moins lourd pour toi.
Vstream a deja un debut de code pour gerer ce captcha (non fonctionnel bien sur), mais je te dis de suite, si tu n'as pas prevu d'y passer 1 ou 2 mois dessus, tu peux zapper ^^.

Il y a aussi des sites payants qui te proposent une api pour resoudre ce captcha, 3$ pour 1000 requetes par exemple. Jamais teste.

Sinon regarde bien le site, il y a surement plus simple.
1 - Le site affiche page 1, puis page avec captcha, puis page 3, regarde si il n'y a pas une astuce pour passer direct de la 1 a la 3.
2 - Le site propose de s'enregister, et dans ce cas ne propose plus de captcha.

**Comment by chataigne73** [comment]
Je vais regarder pour  les 2 dernières astuces dont tu parles... 
Mais sinon je ne parlais pas de contourner ce captcha, mais de pouvoir le résoudre à l'écran, comme on le fait aujourd'hui pour le texte : vstream afficherais les images avec la question et l'utilisateur cliquerait sur les bonnes images

**Comment by TmpName** [comment]
Ca, ca marche deja dans Vstream, le seul probleme c'est l'antibot de google, il envois une chaine de caracteres codées contenant la resolution, les mouvement de la souris, des infos sur ton navigateurs, des infos sur la page affichées, ect ....
Un exemple de leur algorythme qui cree ce token > http://pastebin.com/tj2HATVf

C'est completement debile en plus, car c'est cette partie que les spammeurs ont contourne en premier, et sur le sites payant ce serait des humains qui selectionnent les images.

**Comment by chataigne73** [comment]
bon ben dommage, mais ça dépasse mes modestes compétences
je voulais ajouter le site ddlfr.org  car je trouve qu'il est très complet, et est une excellente alternative à ZT pour des liens uptobox et fichier

**Comment by patoche2025** [comment]
salut, je viens d'aller sur le site c'est clair qu'il est très complet un peut comme http://www.extreme-down.co peut-être un jour qui sait

**Comment by TmpName** [comment]
Tu as teste avec un enregistrement sur le site ?

**Comment by chataigne73** [comment]
TmpName : comprends tu qqc à cette discussion ?
hxxps://forums.tvaddons.ag/shanis-addon-repository/24190-release-livestreamspro-130.html#post340480

**Comment by chataigne73** [comment]
bon, pour l'instant je suis en train de tester ton code recaptcha.
pour le moment ça échoue ici `message = re.search(r'case "' + q5 + '".+?e\+="(.+?)";', q3).group(1).decode('unicode-escape')`

**Comment by TmpName** [comment]
En fait au debut il y avait une faille dans Recaptcha, tu pouvais utiliser celui de la demo pour generer un cookie et t'en servir pour les autres sites. Un des addons utilisant cette faille etait justement LiveStreamsPro, normallement si tu jettes un oeuil a mon code tu vas trouver le lien du fichier de Shani08.

Mais ca ne marche plus ^^. Actuellement impossible d'obtenir la variable bg sans navigateur.

Apres il y a des sites ou tu résous des captchas pour avoir des credits, et avec ces credits faire resoudre tes propres captcha, j'ai commence a jetter un oeuil mais il te donnent les bonnes images et c'est a toi de faire un requete en utilisant un navigateur, donc pas possible uniquement avec python.

Mais serieusement y a plein de site comme celui la, beacoup moins chiant, attend l'enregistrement ne sert a rien, et ca te redemande le captcha a chaque fois, bien lourd dingue.

**Comment by johngf** [comment]
c'est vraiment mort de résoudre un recaptcha sur vsteam ? j'ai trouvé un hoster qui demande d'en résoudre un pour activé le streaming pour 4h pour ton ip sans ça il manque un partie du lien final et on est redirigé sur une video du meme genre que les pigeons d' openload.
rien a voir avec les cookies,ni une mauvaise url ou redirection
le code est fait ,j'ai résolu le captcha en ligne est ça fonctionne
(voir si on peut esquivé le captcha?)

**Comment by johngf** [comment]
Je suis tombé sur ça une api qui resout le captcha apparament en créant un compte gratuit on a une api key http://blog.clarifai.com/clarifai-featured-hack-never-let-a-recaptcha-question-your-humanity-again/#.WBM_YnuvTML

**Comment by TmpName** [comment]
Moi j'avais jete un oeuil sur ht tps://ww w.9kw.eu/hilfe.html mais pas au point.

**Comment by johngf** [comment]
je l'ai vu sur alluc ee par hasard il est deja dans vstream je l'ai modifié

**Comment by TmpName** [comment]
Je viens de faire un test, ca me demande pas da captcha ?
ht tp://w ww.thevideo.me/embed-dbna2fsmnqkf.html

**Comment by johngf** [comment]
ca demande un captcha que sur kodi avec le lien final pas sur firefox ou autre

**Comment by TmpName** [comment]
Tu aurais un lien avec captcha stp.
Il se peut que ton navigateur ne te propose plus le captcha car tu viens juste de le rentrer.

**Comment by johngf** [comment]
ht tps://thevideo.me/pair? pour faire le captcha

**Comment by TmpName** [comment]
Nope une video, qui deconne sans le captcha.
Ca ca sert a rien, openload propose la meme chose, c'est juste un truc pour pouvoir lire une video sur un autre appareil en autorisant ton IP apres un captcha justement.

**Comment by johngf** [comment]
edit je me suis mal exprimé ça te demande jamais le captcha j'ai trouvé l'adresse par hasard et me suis rendu compte qu'il fallait en faire un pour activé le stream sinon on a pas le "vt"

**Comment by johngf** [comment]
une video qui fonctionne pas avec l'ancienne version sur alluc ee recherche watching ensuite they're watching

**Comment by TmpName** [comment]
Pas de cpatcha chez moi sous firefox donc c'est contournable.
J'installe ta modif, et je regarde comment se passer du cpatcha.

**Comment by TmpName** [comment]
Lol, je viens de voir la video "bonus", effectivement c'est comme le coup des pigeons ^^
Marrant.

**Comment by TmpName** [comment]
Alors 
```
<script>
			var mpri_Key='LDsmQUk6QylIPFZRVDhXJU0K';
			eval(function(p,a,c,k,e,d){e=function(c){return c};if(!''.replace(/^/,String)){while(c--){d[c]=k[c]||c}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('3.2(\'<0 4\'.1(\'8="\'+\'/5\'.1(\'/\'+7+\'">\\6/0>\')))',9,9,'script|concat|write|document|s|jwv|x3C|mpri_Key|rc'.split('|'),0,{}))
		</script>
Te donne un lien

Sur ce lien tu trouves VT.

Tout est code, mais par un enfant de 8 ans.
```

**Comment by johngf** [comment]
J'etais tombé sur ça mais en faisant  unpack il y avait pas de lien

**Comment by TmpName** [comment]
Bon je dois filer, j'ai pas pu finir, le code est incomplet
Il y a un premier pave de desactive car ca deconne, mais comme le lien ne chnage pas je le fabrique moi meme (url2)

Le second code a unpacker deconne, doit y avoir un caractere en trop ou en moins, mais tu peux aussi le trouver a coup de regex, c'est la chaine la plus longue.

**Comment by johngf** [comment]
bon je l'ai terminé ça fonctionne par contre le sHtmlcontent2 etait impossible a unpack avec la lib de vstream alors que sur le site dean packers ça fonctionne

**Comment by TmpName** [comment]
Je viens de tester avec une nouvelle video, mot cle "arrow" et je suis tombe sur la video "bonus".
J'y rejette un oeuil.

**Comment by johngf** [comment]
ok sinon tu sais quel genre de codage c'est ça:
p=[c[(K9Z.a0+K9Z.I0X+K9Z.u2X+K9Z.t4O+K9Z.W3+K

**Comment by TmpName** [comment]
Nope jamais sur des lien videos, peut etre sur des scripts de pubs/sponsoring.

C'est pour ou ?

MAJ pr unpack et thevideo.

**Comment by johngf** [comment]
sinon je vais update nowvideo tu peut jeté un oeuil voir si il y pas quelque chose d'inutile

**Comment by TmpName** [comment]
Nope, rien a dire, juste que suis pas sur que "var fkzd" reste fixe.

Edit: j'ai un prb sur un lien, 5 mn

**Comment by johngf** [comment]
j'ai testé sur film streaming. cc para normal acti vity 3

**Comment by TmpName** [comment]
Lol, c'est bizarre, ce n'est meme pas le meme lecteur.
A voir si on peut convertir un lien vers l 'autre.

**Comment by johngf** [comment]
j'ai commencé un truc pour les videos en redirection sur alluc ee c'est ce qui ma amené sur nowvideo
https://github.com/johngf/venom-xbmc-addons/blob/Beta/test.py
sauté une nav c'est possible ou pas ?

**Comment by TmpName** [comment]
Ben je pense qu'ils utilisent les 2 methode
http://ww w.nowvideo.sx/embed/?v=da1e40530f1b4
http://w ww.nowvideo.sx/embed/?v=127c1b47361e2

Un marche avec ta methode l'autre non, donc je pense qu'il faut gerer les 2.

**Comment by johngf** [comment]
oui pas le meme lecteur

**Comment by TmpName** [comment]
Essaye Voirfilm / nerve / vostfr
Marchera pas car c'est l'autre lecteur.

V modifier le source pr gerer les 2.

**Comment by TmpName** [comment]
Bon je laisse tomber, je sais pas pkoi, ils sont du me freiner car now j'arrive a lancer aucune video, ca tourne dans le vide indefiniment.

**Comment by johngf** [comment]
non c bon

**Comment by TmpName** [comment]
Teste les 2 modes si tu peux alors, moi j'ai pas pu tester celui de voirfilm, et je ne sais pas non plus pkoi il y a 3 liens a chaque fois.

**Comment by johngf** [comment]
en plus ils ont l'air d'etre tous en 720 c'est les meme

**Comment by chataigne73** [comment]
salut
je reviens sur le sujet du recaptcha
car, quoi que tu en dises TmpName, ddlfr est un des sites français les plus fourni en films ! et ça me fait vraiment mal de devoir faire l'impasse dessus
donc Tmp, tu me confirmes qu'il n'y a vraiment rien à faire ?
tu vois de fallback ça parle ici : `https://forums.tvaddons.ag/eldorado-s-xbmc-addons/45321-icefilms-beta-1-99-03-released-9.html#post380435` ?

**Comment by TmpName** [comment]
Nope, pas mieux pr le moment,je vois
-La machine JS virtuelle, trop lourd (comme JSphamtom je crois, c'est vraiment de memoire).
- Le service qui propose la resolution de captcha, j'en ai pas vu d'utilisable, le mieux demande d'avoir un proxy perso, pour pouvoir valider le captcha avec l'ip de ton proxy pour que tu puisses t'en resservir, (laisse tomber l'usine).
- Trouver l'algorytme de google, mais pour l'avoir deja vu une fois decodee, c'est du n'importe quoi, c'est la pire methode des 3, c'est utile pr proteger la valise nucleaire, pas un site de dl ....
- Trouver une faille sur le captcha, je pense qu'avec le nombre de personne qui s'y penche dessus, y en a bien un qui va trouver.
- Trouver une faille sur le site ddlfr.

**Comment by chataigne73** [comment]
ok merci pour ces précisions Tmp  ;-)

**Comment by johngf** [comment]
je crois que alluc ee c'est mort ils ont mis un recaptcha pour accéder a la recherche

**Comment by TmpName** [comment]
Je viens de tester, et j'ai pas eu le capcha ?
Au bout d'un certain nbre de requetes ?

**Comment by johngf** [comment]
Bon j'ai i changé d'ip supprimer cookie.dat et plus de captcha ils ont du mettre une limite pour la recherche

**Comment by chataigne73** [comment]
Les recaptcha commencent à pulluler :-(

**Comment by johngf** [comment]
Effectivement deja certain lien netu qui passe par waaw .tv demande un captcha ils sont rare mais ça commence

**Comment by TmpName** [comment]
Moi je trouve ca bien , ca va motiver les gens a trouver une parade.
Surtout que nous contrairement aux bots qui les contournent facilement on peut repondre au capcha en temps qu'humain.

**Comment by johngf** [comment]
par contre aujourd'hui pas eu de captcha meme en faisant 20 requete d'affilé
c'etait peut etre temporaire

**Comment by TmpName** [comment]
Bon je remonte cet ancetre, mais j'ai quand meme une question, hier j'ai vu un site mettre a jour son code pr recaptcha.
J'ai donc voulu retester, et pareil ca ne marche pas. Donc soit mon code est foireux, soit ils hallucinent tous.
On peut retrouver ce code sur exodus, pyload, urlresolver et gaves d'autres sources.
Quelqu'un a deja vu ce code fonctionner ?

Et dur de tester, Impossible de trouver une video avec captcha sur exodus par exemple.

**Comment by johngf** [comment]
Megatrack movie on mis recaptcha maintenant faudrait test la

**Comment by chataigne73** [comment]
je ne suis pas certain de te suivre @TmpName 
il y a qq temps tu m'avais dit `En fait au debut il y avait une faille dans Recaptcha, tu pouvais utiliser celui de la demo pour generer un cookie et t'en servir pour les autres sites. Un des addons utilisant cette faille etait justement LiveStreamsPro, normallement si tu jettes un oeuil a mon code tu vas trouver le lien du fichier de Shani08.

Mais ca ne marche plus ^^. Actuellement impossible d'obtenir la variable bg sans navigateur.`

tu as du nouveau ?
tu te demandes si ACTUELLEMENT certains plugin type exodus savent résoudre les recaptchas ?

**Comment by TmpName** [comment]
Ben non, mais je trouve bizarre que certains sites mettent a jour ce fichier si ca ne marche pas. Peut etre que ca ne marche que pour le version sans JS, mais la franchement j'ai un doute.

Donc oui je demande si quelqu'un a deja vu au jours d'aujourdhui une application pouvant utiliser ces captcha ?

**Comment by chataigne73** [comment]
salut
apparemment, le plugin SALTS `https://github.com/tknorris/tknorris-beta-repo/blob/master/zips/plugin.video.salts/plugin.video.salts-2.0.129.zip`    arrive à se loguer sur un site protégé par recaptcha (superchillin.com) ....   le code est dans noobroom_scraper.py

**Comment by TmpName** [comment]
La vache tu as vu ca comment ? Un coup de bol ?
Sinon j'ai regarde le code, ca a l'air out of date, le captcha est un recaptcha et le code demande juste de taper le mot lu sur l'image.
En fait generallement je tombe sur ca aussi, des vieux bout de code ne marchant plus, et impossible de tester en utilisant l'addon.
