### ISSUE TITLE
vstream -> Source ZT -> uptostream : pb pas de choix piste audio et CC

### ISSUE THREAD

**Issue by quispiamnemo** [Kodi-vStream/venom-xbmc-addons#540]
Bonjour,

depuis la source ZT dans vstream, en lançant en streaming une source uptostream, on peut choisir la qualité de la vidéo mais pas la piste audio et les sous-titres. De nombreuses sources disposent de la piste en anglais et en français, la piste audio est choisie par défaut. Idem pour les sous-titres. Pas de possibilités pour changer la piste par la suite?

Une solution?

Merci.

**Comment by TmpName** [comment]
On a deja eu ca, mais me souvient plus du resultat.
Tu aurais un exemple de film ? Je viens de tester (tres rapidement) et a chaque fois je n'ai eu qu'une seule video sur uptostream. (uptostream et pas uptobox ?)

**Comment by quispiamnemo** [comment]
Bonjour,
Merci pour votre réponse.
Je viens de tester par exemple Money Monster en 1080p truefrench sur vstream, le film est en anglais ainsi que les sous-titres. Depuis un navigateur, avec l'url uptostream, les deux flux audio sont disponibles.

**Comment by TmpName** [comment]
Ok, je viens de faire une modif qui affichera la resolution avec la langue. Ca marche avec ton film

**Comment by quispiamnemo** [comment]
Bonjour,
Merci pour votre travail.
je viens de recevoir la maj et viens de re-tester. J'ai tjrs le choix de la qualité ms pas celui de la langue. Faut-il faire une manipulation particulière?

**Comment by TmpName** [comment]
Ha ?
Normalement chez moi ca affiche 360p French 480p french 1080 french 360pEnglish 480p English, ect ... 
Tout ca sur la fenetre ou je choisis la qualite.

Teste sur money monster 10_80p True FR

Je clique sur le lien uptobox puis choisit de passer par uptostream.

**Comment by quispiamnemo** [comment]
Bonjour,

Mille excuses, ayant l'habitude de prendre la dernière résolution de la liste, je n'avais pas constaté que les qualités apparaissaient deux foix. Maintenant que je sais que la première série de choix correspond à la piste audio française, je vous confirme que cela fonctionne parfaitement pour moi également.

Merci pour votre efficacité et votre excellent travail.

**Comment by Kodigoal** [comment]
J'ai testé sur le même film via Uptostream et je n'ai pas les langues affichées.
Vu le log kodi , il utilise l'hoster Uptobox pour lancer le listage et la vidéo , je le vois pas utiliser le
fichier uptostream.py ?

**Comment by TmpName** [comment]
Ce que je fait moi.
ZT je cherche le film "money monster 10_80p True FR
Je prend uptobox, passer par uprostream.
Et la ca me propose Resolution ET langues

>ca affiche 360p French 480p french 1080 french 360pEnglish 480p English

**Comment by Kodigoal** [comment]
Oui mais ca fonctionne pas  chez moi aussi ^^ si je modifie uptobox.py pour la langue c'est bon, il utilise pas uptostream.py ( je l'ai même virer pour  voir) , vu qu'on lance le lien uptobox au debut,  il prend uptobox.py pour ouvrir la popup  streaming/direct  et lister ensuite resolution et lance vidéo ...

**Comment by TmpName** [comment]
Ha merde, ca y est j'ai compris.
Dsl me suis loupe.
Je corrige de suite.

**Comment by Kodigoal** [comment]
:-) Merci.
Sinon  hors sujet, j'ai un petit soucis: 
J'ai rajouté manuellement le fichier .py de la nouvelle source que LordVenom a faite (FilmenstreamingHD) dans le répertoire /sites/ et la maj du settings.xml qui le prend en compte.
Et en listant par les différents Menus ,  il est pas classé comme il devrait , il apparait toujours à la fin de la liste des sites proposés.( même après avoir vider cache vstream/xbmc)
Faut que j'efface un fichier particulier  de Vstream pour qu'il soit bien pris en compte/trié dans le listage ?
Ou obligé de réinstaller le zip complet ?

**Comment by TmpName** [comment]
Tu veux dire quoi par " il apparait toujours à la fin de la liste des sites proposés".

Sinon le copier dans le repertoire suffit pour pouvoir s'en servir, le fichier settings.xml sert surtout pour son integration (eg pour les recherches).
Va voir dans les parametres de Vstream, il se peut que ce site ne soit pas configure.

**Comment by Kodigoal** [comment]
Si je vais par exemple  dans le menu Home/Films /Sources :
Le site devrait être placé par ordre alphabétique donc parmi les sites commençant par F.

Mais là , il est à la fin de la liste en dessous de ZT ^^ ( si je m'amuse à rajouter d'autres  sites/fichiers .py dans le répertoire /sites/ , je rencontre le même soucis , ils se mettent en fin de liste après Zone téléchargement).

J'ai tout essayé , activer/désactiver le site dans les paramêtres, vider cache et cie ... 
J'ai même effacé tous les .pyo du répertoire /sites/  pour tester que ca recompile au lancement de Vstream mais ca a rien réglé .

Pêtre il prend en compte la date du fichier .py que je rajoute et il le liste à la fin ..
,Je cherche depuis un moment lol ,  car je pige pas  le pourquoi du comment il me 
trie pas le fichier  rajouté par ordre alphabétique, ca me hante ce petit soucis ^^

**Comment by TmpName** [comment]
Ha c'est ca ^^.
Moi j'ai rajoute un fichier otaku.fr, et ca l a mit au bon endroit. Juste cree le fichier et c/c le code dedans.
Aucune manip magique ^^, pas touche a la config, pas de modif d xml.

Un reglage dans kodi qui afficherait par date ? Essaye en modifiant ZT pour changer sa date.

Encore un mystere, ta machine est sous unix ?

**Comment by Kodigoal** [comment]
3 installs sous  Android.
Si je modifie les .py des sites , aucun soucis , il reste bien trié.
Là j'ai viré ZT (.py/.pyo) , j'ai crée nouveau fichier ZT.py , j'ai copier/coller le code dedans.
Je relance en me disant il sera en fin de liste lol 
Et ben non , il est à la même place qu'avant et toujours Filmenstreaminghd en dernier ^^

Je refais  la  même manip pour Filmenstreaminghd et bingo se retrouve toujours à la fin lol
Ca rend dingo ^^

**Comment by TmpName** [comment]
XD, j'imagine.

La je ne comprend pas du tout, surtout que je n'ai pas le prb de mon cote. Peut etre une histoire de cache (mais j'ai vu que tu as deja teste aussi).

**Comment by Kodigoal** [comment]
Oui tout tenter , mais je trouverais un jour lol , je vais tester sous windows à l'occasion.

**Comment by Kodigoal** [comment]
Après avoir fouiller un peu partout j'ai trouvé d'ou vient le soucis xD
Dans les fichiers siteHandler.py ( Listage des sites) et pluginHandler.py ( pour Listage Toutes les sources) ,  on récupére le contenu du répertoire /sites/ et sous Android ( à voir sous Linux aussi)   il doit se baser sur je ne sais quel paramêtre mais il ne met pas les sites par ordre alphabétique , d'ou mon soucis d'avoir les sites créés manuellement à la fin du listage.
En rajoutant  items.sort() dans les 2 fichiers  , il va  trier la liste items par ordre alphabétique et ca régle le soucis.
 [code]
def __getFileNamesFromFolder(self, sFolder):
        aNameList = []
        #items = os.listdir(sFolder)
        items = os.listdir(unicode(sFolder, 'utf-8'))
        items.sort()

Si ca pose pas de soucis sous Windows ? on peut envisager de faire la modif ?

**Comment by TmpName** [comment]
XD, nope ca pose pas de problemes, mais perso d'avoir les fichiers dans le desordre ca ne me pose pas de probleme non plus ^^.
tu peux faire la modif sans problemes.

**Comment by Kodigoal** [comment]
Ok ben sinon je fais juste la modif de mon côté , ca suffit.
A voir si un jour une issue sera ouverte sur ce petit détail sous Android , on sera quoi modifier^^

**Comment by TmpName** [comment]
Vas y met la, elle coute rien, ca ne nuiera pas aux performances, et ca evitera a d'autres des tempetages de tete.

**Comment by Kodigoal** [comment]
xD ok je fais ca  ce soir
