### ISSUE TITLE
Chargement de la page Home.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#541]
Bon j'ai une question.
Pourquoi la page defaut.py n'est pas charge a chaque demarrage de Vstream ?
Dans le fichier defaut.py
```
class main:
    def __init__(self):
        xbmc.log( 'Debug 0' )
        self.parseUrl()
        cDb()._create_tables()
```

En fait si on vide le cache de kodi, ok ca marche pas de probleme, mais si on ferme kodi et on le re ouvre ca n'affiche plus "debug 0', j'ai teste avec d'autres addons, pareil , youtube affiche au premier lancement un message dans les logs, mais plus apres.

Kodi recharge cette page tout les combien, a quelle occasion ?

Ca pose un probleme car les verification de MAJ sont faites ici, et donc si pas de chargement de page, pas de verification de MAJ, c'est surement pour ca que certains n'ont rien meme en avancant la date de 3 jours.

PS : D'ailleurs, pour info, pour ceux qui seront bloque dans le futur, dans les parametres de vstream "Vider cache kodi" marche tres bien.

**Comment by johngf** [comment]
je viens d'essayer et chez moi de debug 0 s'affiche à chaque démarrage

**Comment by Kodigoal** [comment]
kodi 15.2 / Android:  'debug 0' s'affiche aussi à chaque lancement de Vstream.

**Comment by LordVenom** [comment]
Pareil pour moi debug 0 a chaque fois.

**Comment by chataigne73** [comment]
j'en profite pour poser une question un peu HS (désolé)
quel est l'avantage d'utiliser xbmc.log('') plutot que print ???

**Comment by LordVenom** [comment]
Print ne fonctionne plus sauf si tu active le mode debug de kodi

**Comment by LordVenom** [comment]
Tu peux tester dans gui fonction setEndOfDirectory

`xbmcplugin.endOfDirectory(iHandler, True)`

Par 

`xbmcplugin.endOfDirectory(iHandler, True, cacheToDisc=False)`

Chez moi ça na jamais rien changer pour ça que je le mais par defaut il et True.

**Comment by TmpName** [comment]
Ben chez moi ca affiche "debug 0" si je vais dans "recherche "film" ou favoris" a chaque fois.
Mais la page d'acceuil pas a chaque fois, pareil si je modifie le fichier python, les changements ne se font pas de suite, et j'arrive pas a comprendre pkoi j'ai une mise en cache chez moi ?
La ma copine s'en est servi cet apres midi, elle a eu le 'debug 0' plusieurs fois mais pas de recherche de MAJ, j'ai refait un test y a 5 mn et j'ai eu le "debug 0" sur la page "Home" et la verif de MAJ.

Mais plus apres, meme apres un reload complet.

Ceci dit, meme si me saoule, ca a l'air de se faire au moins une fois par jours, donc suffisant pour nos verifs, mais c'est vraiment bizarre et pourquoi uniquement sur la page "home". ?

**Comment by johngf** [comment]
''pareil si je modifie le fichier python'' j'ai déja remarqué qu'en mettant un site en favoris si je modifie le contenue pour fix quelque chose et que je verifie si ca fonctionne en relancant le site par favoris 
les changements ne se pas pris en compte

**Comment by johngf** [comment]
est-ce que quelqu'un a aussi un probleme au niveau de la navigation page home ?
09:35:38 T:2793003840  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showDocs
09:35:38 T:2793003840  NOTICE: 	[PLUGIN] Vstream: Table initialized
freeze un peut ici en cours 30 a 60s
donc retour arriere
09:35:44 T:2784611136   ERROR: CPythonInvoker(12, /home/john/.kodi/addons/plugin.video.vstream/default.py): script didn't stop in 5 seconds - let's kill it

pour chaque site j'ai ça dans le log
09:34:53 T:2769226560  NOTICE: 	[PLUGIN] Vstream: Load Plugin: freebox
09:34:53 T:2769226560  NOTICE: 	[PLUGIN] Vstream: cant import plugin: freebox
09:34:53 T:2769226560  NOTICE: 	[PLUGIN] Vstream: Load Plugin: streaming_series_xyz
09:34:53 T:2769226560  NOTICE: 	[PLUGIN] Vstream: cant import plugin: streaming_series_xyz
etc...

**Comment by TmpName** [comment]
Ha ca non ???

Je suis pas sur de ton log car la ou tu as mit 30 a 60s de freeze il y a juste 6s de temps (09:35:38 a 09:35:44)

A moins qu'il soit justement a 09:35:44, et la d'apres ce que je comprend
Fichier defaut.py qui passe par home.py et bloquerait a showdocs() mais cette fonction est appelle quand tu selectionnes "Documentaires" pas sur la page "Home"
Et cette fonction ne charge pas de page web, n'utilise pas de regex, rien qui pourrait bloquer .....

**Comment by johngf** [comment]
en faite en forçant le retour en arriere quand ca freeze un peu c'est ce qui cause 
ERROR: CPythonInvoker(12, /home/john/.kodi/addons/plugin.video.vstream/default.py): script didn't stop in 5 seconds - let's kill it
il ne faut pas se fier a l'heure vu que ça ma saouler de voir en cours...
maintenant ça me le fait meme au autres page de navigation meme sans charger de page web

**Comment by TmpName** [comment]
Ha oui, tu as un temps anormal au debut.
>17:43:53 T:2708462400  NOTICE:  [PLUGIN] Vstream: load site cHome and call function animNews
17:44:23 T:2708462400  NOTICE:  [PLUGIN] Vstream: Root Folder: /home/john/.kodi/addons/plugin.video.vstream

Cette fois c'est animNews, mais pareil je vois pas pkoi ca bloque, dans kodi il y a une option pour augemter les message de logs Systemes/journalisation.

Sinon, tu peux essayer de vider les caches Vstream et kodi y a l'option dans les parametres de Vstreams.

Tu fonctionnes avec ou sans metahandlers ?

**Comment by johngf** [comment]
j'ai tout nettoyé et réinstallé kodi et vstream et le problème est toujour la et metahandler est activé oui

**Comment by TmpName** [comment]
Moi j'avais l'addon des meta qui me ralentissait a un moment (m'a fallu vider le cache de cet addon) mais toi ca ne te sert pas pr la page home donc je ne pense pas que ce soit ca.

En plus c'est bizarre que ca ne te la fasse que sur Vstream.

Si tu as reinstalle kodi, tu as bien pense a effacer aussi les fichiers de config ?

Ca bloque aussi sur la recherche ? (c'est aussi le fichier home.py qui gere les recherches)

**Comment by johngf** [comment]
oui j'ai effacé tous les fichier de config de kodi vstream et autre addons meme dans root ,j'ai mis a jour sqlite est toujour pareil(peut etre un prob materiel)
demain je vais voir si le probleme est aussi sur windows7

**Comment by johngf** [comment]
script.module.urlresolver est installé chez vous ? moi non il est pas dans le depot kodi

**Comment by TmpName** [comment]
Oui, il y est et normallement il doit y etre lors de l'install de Vstream, il est en dependance.
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/addons.xml

**Comment by johngf** [comment]
il l'ont peut etre supprimer du depot

**Comment by TmpName** [comment]
C'est peut etre recent, mais il etait officiel a ma derniere verif.
Y avait meme le detail de l'api sur un site officiel de kodi.

**Comment by Kodigoal** [comment]
http://mirrors.xbmc.org/addons/jarvis/script.module.urlresolver/

Mais ya une version plus récente 3.0.1 par Eldorado:
https://offshoregit.com/iCanuck/iCanuck-Repo/raw/master/

**Comment by johngf** [comment]
j'ai essayé c'est pareil meme sur windows 7 sur un autre pc fresh install kodi et vstream ça me le fait kodi 16.1 jarvis
en cours..... pour accéder a un répertoire mais pas tous le temps.

**Comment by Kodigoal** [comment]
T'as testé  sous kodi Isengard 15.2? voir si ca te fait pareil ?

**Comment by johngf** [comment]
non je vais le faire la on dirait un probleme de cache qui se vide a chaque fois
21:53:06 T:5960  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showMovies
21:53:27 T:5960  NOTICE: 	[PLUGIN] Vstream: Table initialized
21s pour ouvrir un répertoire
