### ISSUE TITLE
Dl & visualiser plante kodi après 5min

### ISSUE THREAD

**Issue by baaaaaziiiiingaaaaa** [Kodi-vStream/venom-xbmc-addons#542]
Bonjour,

Je suis face à un problème depuis 1 semaine. Quand je lance un épisode en HD (2Go) avec la fonction "Dl & visualiser" sur "uplea" et "uptobox" kodi plante au bout d'environ 5min et je me retrouve sur l'accueil d'android. Même si je met le lecteur en pause.
Bien évidement le téléchargement est stoppé (400mo) et pas possible de le reprendre (non premium).

Auriez-vous une idée? en streaming pas de problème, mais la fonction est disponible uniquement avec uptobox.

Merci à vous

```
14:26:07 T:1913531304  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
14:26:07 T:1787898528  NOTICE: DVDPlayer: Opening: /storage/emulated/0/Android/s01 vf7.flv
14:26:07 T:1787898528 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:26:07 T:1881822488  NOTICE: Creating InputStream
14:26:08 T:1881822488  NOTICE: Creating Demuxer
14:26:08 T:1881822488  NOTICE: Opening stream: 0 source: 256
14:26:08 T:1881822488  NOTICE: Creating video codec with codec id: 28
14:26:09 T:1881822488  NOTICE: Creating video thread
14:26:09 T:1881822488  NOTICE: Opening stream: 1 source: 256
14:26:09 T:1881822488  NOTICE: Finding audio codec for: 86020
14:26:09 T:1908914000  NOTICE: running thread: video_thread
14:26:09 T:1881822488  NOTICE: Creating audio thread
14:26:09 T:1881822488  NOTICE: Opening stream: 2 source: 256
14:26:09 T:1883328032  NOTICE: running thread: CDVDPlayerAudio::Process()
14:26:09 T:1883328032  NOTICE: Creating audio stream (codec id: 86020, channels: 6, sample rate: 48000, no pass-through)
14:26:09 T:1908914000  NOTICE:  fps: 23.976024, pwidth: 1280, pheight: 720, dwidth: 1280, dheight: 720
14:26:09 T:1908914000  NOTICE: Display resolution DESKTOP : 1280x720 @ 60.00 - Full Screen (16)
14:26:09 T:1787898528  NOTICE: Using GL_TEXTURE_2D
14:26:09 T:1787898528  NOTICE: GL: Using BYPASS render method
14:26:09 T:1787898528  NOTICE: GL: NPOT texture support detected
14:26:09 T:1883328032  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 10
14:26:10 T:1913531304  NOTICE: Previous line repeats 2 times.
14:26:10 T:1913531304  NOTICE: 	[PLUGIN] Vstream: Table initialized
14:26:31 T:1908914000 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available
14:32:22 T:1883328032 WARNING: Previous line repeats 1449 times.
14:32:22 T:1883328032   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
14:32:22 T:1908914000 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
```

**Comment by TmpName** [comment]
Essaye de telecharger le fichier (via Vstream, menu contextuel), pour voir si c'est le DL qui bloque ou la lecture.

**Comment by baaaaaziiiiingaaaaa** [comment]
J'ai testé et c'est pareil. J'ai flash le firmware avec un "wipe cache and factory" et désinstallé kodi rien y fait. La semaine dernière cela fonctionner.

**Comment by TmpName** [comment]
Donc ca plante meme si tu ne fais que telecharger un fichier ?
Essaye en configurant le dossier de sauvegarde sur un disque externe (si tu as ca sous la main ou un autre repertoire), il te reste combien de place sur ton systeme ?

**Comment by baaaaaziiiiingaaaaa** [comment]
Bonsoir, J'ai débloqué la vitesse de téléchargement "download.py" ligne 50. 
En téléchargement le fichier bug aussi dans les 400mo au 2eme "waiting" pour actualiser la taille du fichier télécharger.
Téléchargement en interne 4go de libre et téléchargement sur disque externe même problème.
 J'ai regardé le lien, pour mon dossier /org.xbmc.kodi/files/.kodi/temp/ par ftp il fait 1.34mo il y a un autre dossier "/org.xbmc.kodi/files/.kodi/temp/temp/" il est vide.

**Comment by TmpName** [comment]
C'es quoi le "2eme "waiting" pour actualiser la taille du fichier" ?
Moi quand je lance un DL, j'ai juste une fenetre en haut avec une progessbar. Je n'ai les fenetre "waiting" que quand je met le DL en route.

Tu as essaye de regarder les "statistique " de ta machine durant le DL , memoire restante, taille sur disque, ect ...
Mais normallement si tu ne fait que DL sans visualiser, ca ne devrait rien consommer, ca ne devrait meme pas toucher a ton cache.

**Comment by baaaaaziiiiingaaaaa** [comment]
Le 2eme waiting s'affiche dans la rubrique "Téléchargement" "Liste de téléchargement", j'ai aussi la fenêtre en haut avec la progression.

Pour les stats hors téléchargement le CPU0 entre 25 et 50% CPU1 et 3 fixe a 38% "pas de CPU2?" et la mémoire 427mb use 53%. En téléchargement le CPU0 entre 70 et 96% et plantage au bout de 20mo. Je teste à nouveau tout à l'heure. voir si j'ai du mieux ou si c'est lié à une surcharge du processeur.

J'ai télécharger par le navigateur sur la box android le même fichier aucun problème.

Je me demande si ce n'est pas du aussi a kodi 16.1 car il me semble que la semaine dernière j'avais la version 15. Et a chaque lancement de kodi dans la rubrique "vidéo" j'ai le droit au message "first run help..."

**Comment by TmpName** [comment]
Si tu supprimes le bridage, c'est possible que le cpu grimpe en fleche, mais ariver a 96% c'est pas mal quand meme.
La je sais pas trop quoi te dire, le coup de la modif du firmware, c'etait avant ou apres les crashs ?

**Comment by baaaaaziiiiingaaaaa** [comment]
Je pense que la box à un soucis car elle m'affiche 2 cpu / 4 et des fois les 4. j'ai réussi 1 seul fois a télécharger un fichier et hier le fichier a planté vers les 800Mo.
Par contre 1fichiers.com ne marche pas même sur la nouvelle version c'est un bug chez moi ou c'est tout le monde?

**Comment by TmpName** [comment]
Moi j'ai teste en cliquant dessus (sans passer par dl+visu) et ca a marche, now me faut attendre le delais pour pouvoir retester avec cette option, mais ca a marche.

**Comment by baaaaaziiiiingaaaaa** [comment]
Si je clic direct dessus j'ai le message ( attention pas de streaming sans premium...)

**Comment by TmpName** [comment]
Ha merde, vrai, j'avais oublie la magouille pour avoir 10G gratuit pr tester.
Du coup, pareil ca buggue, j y jette un oeuil de suite.
