### ISSUE TITLE
ZT "en cours" puis rien

### ISSUE THREAD

**Issue by alfred5959** [Kodi-vStream/venom-xbmc-addons#543]
Bonjour, j'ai un problème sur mon android box beelink. Sur ZT, j'arrive sur les jaquettes mais quand je sélectionne le flux pour la qualité du fichier, j'ai "en cours" en bas à droite puis rien. Je n'arrive pas sur le choix de l'hébergeur. Ce doit être un problème de paramétrage car sur mon ordi je n'ai pas de problème. Si quelqu'un a une idée, je prends! Je précise que je peux visionner un film sans passer sur ZT.

**Comment by TmpName** [comment]
Est ce que sur ta machine sous android tu as deja clique sur "Mise a jour disponible" ?
En fait la version par defaut est deja perimée.
3 solutions.
- Avancer la date de 3 jours avant de lancer kodi (bordel sur certain android)
- Mettre soit meme le fichier a jour en faisant un copier/coller (bonne version ici > https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_com.py
- Attendre les 3 jours.

**Comment by Elorian9** [comment]
Ayant installé ma machine Android hier, c'est étonnant qu'elle ne soit pas à jour. Donc, si je comprends bien, avec la mise à jour, ça va fonctionner?

**Comment by johngf** [comment]
oui

**Comment by TmpName** [comment]
En fait les sites changent tout les jours, donc certains fichiers aussi.
Le coeur de Vstream (ce que tu as installe) est mit a jour 1 fois tout les mois (ou tout les deux mois).
Donc meme en ayant installe toutes les dernieres versions, certains fichiers ne seront pas a jours, et pour eviter de defoncer le serveur, ces MAJ ne sont verifiees que tout les 3 jours.

**Comment by alfred5959** [comment]
Merci TmpName pour ta réponse rapide. Après quelques essais, ça fonctionne de nouveau. Pour info, j'ai mis la date au 10 octobre...En tout cas, cela fonctionne. Un grand merci pour ce superbe travail!!! Bon dimanche.

**Comment by TmpName** [comment]
D'ailleurs Venom si tu passes par la, tu as les dates de la prochaine MAJ ?

**Comment by LordVenom** [comment]
Je suis DSL y a tellement de changement que j ai du mal a faire des tests. Je suis du matin si je tombe pas de sommeil je fait ça dans la semaine.

**Comment by johngf** [comment]
j'ai du temps libre en ce moment :)
