### ISSUE TITLE
Besoin d'un coup d’œil expert

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#544]
j'ai fait une modif pour sauté une navigation niveau hoster bonne façon de faire ?

http://pastebin.com/Rp57SJAz

**Comment by TmpName** [comment]
C'est quoi le site en question ? Il y a tant de risque de lag pour que tu prevois un timeout ? Je te demande ca car avec ma telecommande je passe moins de 2s par page de navigation, donc si faut attendre plus longtemps pour afficher une page de moins ...

Sinon comme j'ai pas trouve la version d'avant, donc je peux pas trop comparer mais je vois pas pkoi ca marcherait pas, rien vu de genant (A part peut etre vers la fin si hLinks n'existe pas, oHoster non plus et ca risque de faire une erreur python quand tu la testes, mais franchement c'est vraiment du chipotage).

Surveilles bien le pattern sPattern = '<a href="([^"<>]+/[0-9]/)">([^"]+)<\/a>' , il ne faudrait pas qu'il prenne trop de lien, ce qui te ferait perdre encore du temps.

En passant cRequestHandler a maintenant une option setTimeout() (mais que sur la beta, donc ca ne marchera pas avant la future MAJ).

Pour moi c'est bon rien a redire sur ta methode a part le timeout mais je connais pas le site.

Edit:
Si je mettrais juste except: au lieu de except IOError: comme ca toute les erreurs afficheront le message, meme si ce n'est pas le bon, ca bloquera pas et l'user aura un message dans tout les cas.

**Comment by johngf** [comment]
le site c'est celui sur lequel je travaille otakufr le dimanche soir c'est bondée 5 secondes ne suffisent pas
la version d'avant passé par un showlink avant showhoster vu que chaque lien est dans une autres pages

http://pastebin.com/FKxjRMCC

**Comment by TmpName** [comment]
Du coup le dimanche soit ca ne marche plus, soit tu attend 10s* 5 a 9 lien.
Et je ne vois pas comment repasser a l'ancienne version si tu as trop de timeout. Car si tu as l'erreur de timeout au second lien, c'est foutu, faudrait re-effacer la page et afficher les precedents liens.

Ou alors faire une boucle a l'exterieur de la partie avec cHosterGui().
1 er boucle tu l'as deja faite, tu recupere les 1 er liens.
2 eme boucle on utilise les 1 er lien pour avoir les seconds.
Si erreur sur le tableau 2, on utilise le tableau de la boucle 1.

Par contre je viens de voir 2 nouveaux hosts Sendvid et Rapidhost, tu as commence dessus ?

**Comment by johngf** [comment]
voila c'est uniquement le dimanche que c'est galére 
pour les host non sendvid c'est pour telecharger la video rapidvideo,cloudy,brighcove... il y en plusieur

**Comment by TmpName** [comment]
Sendvid a la'ir de marcher aussi en stream cf 91 days.
Brighcove pas encore vu
Cloudy de memoire est deja en place.

J y jete un oeuil.

**Comment by johngf** [comment]
brightcove c'est sur surtout les anciens lien genre darker than black

**Comment by TmpName** [comment]
J'ai un prb unicode a 91 days.

Rapidvideo ne marchera pas avant kodi V17.

**Comment by johngf** [comment]
bizarre je n'ai pas d'erreur a 91 days

**Comment by TmpName** [comment]
Ben je l'avais pas avant non plus, surement un prb de convertion a cause de pastebin.

**Comment by TmpName** [comment]
Par contre ca deconne justement a darker than black ^^.
A la liste de hoster, j'ai le titre a la place d'un des hosters.

**Comment by johngf** [comment]
http://pastebin.com/p2uhf43p et celle ci oui c'est purevid est hs

**Comment by TmpName** [comment]
Purevid est payant (au bout de 30mn). C'est pour cela qu'il n y est pas sur Vstream.
Cloudy repare
Brightcove, je galere encore, j'en ai aucun qui marche chez moi ??
Je teste la nouvelle version.
Sinon tu l'a ici aussi https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/trash/otakufr_com.py (mais vielle version)

**Comment by johngf** [comment]
brightcove moi aussi aucune video ne fonctionne d'ailleurs ils ont arreté d'hebergé chez eux

**Comment by TmpName** [comment]
J'ai trouve le bug, c'est un peu ce dont je t'avais parle plus haut.
Si hLinks n'existe pas oHoster lui peut exister (a cause de la precedente boucle) donc pour eviter ce bug suffit de decaler tout le bloc (ligne 282 a 288) vers la droite (au meme niveau que la ligne 280, pour que ce bloc ne soit execute que si hLinks  existe.

**Comment by johngf** [comment]
exact

**Comment by johngf** [comment]
cloudy fonctionne chez toi sans le UA avec l'url final ? chez moi non

**Comment by TmpName** [comment]
Nope, pareil chez moi, je le remet.
