### ISSUE TITLE
zone-telechargement ne fonctionne pas sur Vstream-Kodi

### ISSUE THREAD

**Issue by Elorian9** [Kodi-vStream/venom-xbmc-addons#548]
Bonjour,

J'ai installé Kodi sur ma nouvelle shield et installé VStream. Je n'arrive pas à streamer depuis zone-téléchargement. Il est affiché en rose et quand je sélectionne un film, il ne se passe rien. Pour info, j'ai renseigné mes infos de user premium pour 1fichier, mais ça ne change rien.

Pouvez-vous m'aider?

Merci d'avance,
Elorian.

**Comment by johngf** [comment]
regarde ici #543

**Comment by Elorian9** [comment]
Merci!
