### ISSUE TITLE
Un addon basé sur vstream 

### ISSUE THREAD

**Issue by zombiB** [Kodi-vStream/venom-xbmc-addons#549]
Salut Venom ,
je viens de créer un plugin clone basé sur ton superbe addon vstream ,le mien permet de visionner du contenu  en arabe .
Je voulais te remercier et Tmpname  pour toutes les indications et explications mentionnées dans le code ça m’a beaucoup aidé .
bien sur j’ai bien gardé tout les droits sur les fichiers.
Le clone est disponible [ici](https://github.com/zombiB/zombi-addons/tree/master/plugin.video.smsm) si tu veux jeter un œil.
Cordialment,
Zombi

**Comment by TmpName** [comment]
Lol, c'est sympa de prevenir.
Par contre dans tes fichiers sites, la ligne 
>#-*- coding: utf-8 -*-
Doit toujours etre en premier, ca aide l'interpreteur python pour savoir quel codage utiliser.

Et les fichiers du dossier "sites" sont surtout a toi, en plus se sont des sites arabes exclusif a ton addon, donc je pense que pour ceux la, tu peux retirer aussi le
>#Venom

**Comment by zombiB** [comment]
Merci @Tmpname je vais corriger , en fait je suis en train d'apprendre
petit à petit :)
