### ISSUE TITLE
Source vide

### ISSUE THREAD

**Issue by AizenKnower** [Kodi-vStream/venom-xbmc-addons#551]
Depuis peu certaines sources sont vide alors que les titres sont affichés comme Voirfilms par exemple Quand je clique sur la serie ya rien aucune video. (Ya aussi filmillimité et frenchstream fullstreamvk et possible d autre vue que je n'ai pas tous vérifié) 

Donc est ce ya un moyen de fixer tous ça ? Merci

**Comment by TmpName** [comment]
Doublon de https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1500
