### ISSUE TITLE
Série en HD

### ISSUE THREAD

**Issue by boulbix** [Kodi-vStream/venom-xbmc-addons#565]
Hello, je trouve ton addon vraiment bien pr contre est il possible d'avoir une rubrique hd pour les séries ?

**Comment by TmpName** [comment]
C'est faisable, meme si de memoire il y a moins de sites que pour les films.

**Comment by boulbix** [comment]
Oui beaucoup moins de site du coup une rubrique hd permettra d'avoir directement les liens hd car actuellement c'est compliqué de s'y retrouver.

**Comment by TmpName** [comment]
C'est en cours, mais ne marchera que a la prochaine version ou si tu testes la beta.

**Comment by boulbix** [comment]
Ok merci je vais tester la bêta

**Comment by TmpName** [comment]
Mais rien ne presse, pour le moment je crois qu'il n'y qu'une source qui est configuree pour les serie HD.

**Comment by johngf** [comment]
ça serait bien  aussi une catégorie dernier ajouts vostfr pour les séries (pour ceux qui veulent regardé en vostfr et ceux qui ne veulent pas)

**Comment by TmpName** [comment]
Pour les series HD j'en ai trouve que 4 pr le moment.
Et je sais pas si il y a des sites qui proposent les nouveautes soit en vf soit en vostfr.

**Comment by johngf** [comment]
si mais ils sont parfois mélangé au vf

**Comment by TmpName** [comment]
Ben justement ce site classe automatiquement par ordre chronologique, donc si tu prend juste Serie VOSTFR tu vas avoir les nouveautes VOSTFR, pas besoin d'une section speciale.
Y a plein de sites ou on triche deja sur ca ^^, que tu prennes Film Nouveaute ou Tout les films, tu vas avoir les memes resultats.

**Comment by johngf** [comment]
je veux dire séparé les section , dans la section dernier ajouts tu as du vostfr mais tu t'en rend compte quand lançant la video
