### ISSUE TITLE
Sous titres.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#569]
Bon alors suite a differents tests, il semblerait que sur certains hebergeurs les sous titres soient dans des fichiers separes.
Donc j'ai commence des modifs sur le coeur de Vstream (donc ca peut provoquer des gros bugs)

Je n'ai pas fini, et ca ne marchera pas dans tout les cas, il y a plusieurs mode de lecture dans l'addon.

Pour tester ce qui marche pour le moment.
Prendre un hoster au hazard, a la fin du fichier il y a tjours un truc du genre.

> return True, api_call

Remplacer par

> return True, api_call, "c:\st.srt"

Et vous allez avoir les sous titres du fichier st.srt.

La fonction permet de rajouter plusieurs sous titres, a chaque appel a AddSubtitle() ca rajoute un sous titre qui sera selectionnable avec la premiere icone en bas de l'ecran.

Donc maintenant suffit juste de modifier le fichier uptostream.py par exemple pour rajouter le fichier de sous titres si present.

A optimiser.
Impossible pour le moment de rajouter plus de 1 sous titre (pas sur que ce soit utile d'en mettre plusieurs, c'est un addon FR, la langue fr suffira)
Forcer l'affichage des sous titres, si il y en a, he oui ca depend des reglages de kodi, y a une fonction showSubtitles(visible) que j'ai pas encore mise.
J'ai fais mes tests avec un fichier local, pas eu le temps de tester avec un fichier distant.

**Comment by Kodigoal** [comment]
Je vais tester tout ca sur une série ce soir pour les .srt distants.

**Comment by TmpName** [comment]
Bon j'ai commence sur le host uptostream, j'ai desactive le truc pour le moment, suffit de virer le # pour tester.

Probleme:
En fait il y a toujours des sous titres, meme sur un film FR, parfois c'est juste 2 ligne en debut de film.
Je ne sais pas comment savoir si un fichier de sous titre est utile ou pas (French / forced / ...)

**Comment by Kodigoal** [comment]
Quand j'avais testé ( sur série vostfr)  , dans les .srt  'forced' yavait juste quelques lignes soit début, soit fin avec crédit auteurs sous titres,  le 'french' était le bon ... Donc ca peut varier , je crois pas qu'on peut les différencier dans le code.
Ou déclencher que quand on a affaire a un film/série  VO /VOSTFR , normalement dans le nom du fichier c'est toujours indiqué ca .. 
Tu testes sur quel site? pour ZT faut je  mette tes modifs dans uptobox.py

**Comment by LordVenom** [comment]
Sinon 

http://redeneobux.com/fr/tutorial-como-adicionar-inserir-colocar-legendas-nos-filmes-series-opensubtitles-xbmc-kodi/

**Comment by TmpName** [comment]
Yep, me servais de ca pour genesis, mais il faut voir si il y a un moyen de faire ca automatiquement si le film est en pure VO avec sous titres proposes pour le fichier lui meme.

**Comment by Kodigoal** [comment]
Pas réussi à l'intégrer à uptobox.py pour tester via ZT. 
Le Return stream_url, Subtitle  pose problème, même erreur que quand yavait le return True, stream_url.. 
Testé via sokostream, ca récupére bien le .srt si présent , mais ya toujours un subtitle English par defaut , alors qu'il affiche rien comme sous titres , pêtre un tag dans le fichier vidéo inclus qui  fait ca .
 mais sinon impec ! à voir pour récupérer tous les .srt inclus dans le code de la page , après on peut  choisir lequel on veut ^^

**Comment by TmpName** [comment]
Tu as teste sur quel film sur ZT ?

**Comment by Kodigoal** [comment]
Je testais sur les derniéres séries vostfr 720p.
J'arrive bien à avoir les 2 liens , vidéo + .srt  vu log , mais le return stream_utl, Subtitle
me sort comme erreur:
ERROR: EXCEPTION: argument "path" for method "XBMCAddon::xbmcgui::ListItem" must be unicode or str
NOTICE: [PLUGIN] Vstream Erreur: Fichier introuvable
Si t'as une version uptobox.py qui fonctionne pour ZT? ^^

**Comment by TmpName** [comment]
Testes https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/uptobox.py

**Comment by TmpName** [comment]
En passant il y a moyen de rajouter plusieurs sous titre now
SubTitle = "fichier1' pour 1 sous titre
SubTitle = ['fichier1','fichier2','fichier3'] pour plusieurs fichiers.

**Comment by Kodigoal** [comment]
Testé et ca fonctionne bien.
Je pense on peut seulement garder les Label 'full.fr' et French'
J'ai pas réussi pour charger si ya 2 .srt ( genre 'French' + 'Forced') pour tester.
J'ai changé le regex , un peu jouer avec SubTitle =  ['',''] 
Faut modifier en gros comme ca ? 
if (aResult[0] == True):
For aEntry in aResult[1]
fichier1 = 'http:' + aEntry[0]
fichier2 =  'http:' + aEntry[1]
return fichier1,fichier2
Et modifier en  SubTitle = ['fichier1','fichier2']
Je suis paumé ^^

**Comment by TmpName** [comment]
Pour faire une liste
>Files = {]
Files.append(file1)
Files.append(file2)

Et non j'ai pas trouve comment chnager l'affichage, en fait ca dependrait du nom du fichier et de sa syntaxe.

**Comment by Kodigoal** [comment]
Ah Oui , testé en renommant le fichier nom.srt en nom.fr.srt pour qu'il affiche French/external.
Faudrait alors charger le fichier en local , le renommer et l'ajouter avec setSubTitle.
Je pense pas que c'est la peine de s'embêter juste pour avoir le 'French/external'.
Sinon je m'en sort pas pour prendre juste les label 'full.FR' / 'French' et ensuite
vérifier si ya 1 ou 2 srt pour les rajouter ...
Je maitrise pas pour sortir le code bien optimisé qui va bien lol

**Comment by TmpName** [comment]
Nope, moi je ne ferais pas ca, ca obligerait a dl tout les fichiers, et certains peuvent etre gros.
Apres, je laisserais le code tel quel, en modifiant le regex pour prendre aussi le label "label='([^']+)'

Et dans le boucle je ferais des tests avec, car il risque d'y avoir des variantes.
>if 'full' in AEntry[X]:
Files.append(AEntry[Y])

**Comment by Kodigoal** [comment]
oui mieux comme ca , je vais réessayer si j'arrive,  en testant pour commencer  'full' et 'french' pour le label , en attendant de tomber sur des variantes.

**Comment by Kodigoal** [comment]
Bon après une bonne prise de tête lol , est ce que ca te parait bon ce code ?
Testé et ca a l'air bon.
http://pastebin.com/7TfYTAqB
Si c'est ok  , je fais la modif sur la beta plus tard.

**Comment by TmpName** [comment]
Moi ca me semble parfait.

**Comment by Kodigoal** [comment]
Ca semblait xD 
En fait en testant d'autres séries/films, je suis tombé sur un label ' francais' ,
bon jusque là on rajoute le label , pas de soucis.
Mais je sui tombé aussi sur un scrlang 'en' et label 'english'  pour des sous-titres qui sont en francais ...
Alors est ce qu'il faut pas faire l'inverse pour être tranquille , rajouter tout les .srt ( scrlang=(.+?) sauf si label contient  'Forced'.
De toute facon , on chargera 1 .srt,  voir 2 max je pense.
Sinon on va plus s'en sortir ^^

**Comment by TmpName** [comment]
Lol, effectivement.
Le prb c'est que il y a tjours des *.srt.
Apres je ne pense pas que ca soit genant, soit ca fait 1 M et c'est indispensable, soit ca fait 50ko et meme si ca sert a rien, ca va pas ralentir kodi.

Faut tester en faisant comme tu dis, les mettre dans tout les cas, sauf les forced.

**Comment by Kodigoal** [comment]
ok maj uptobox.py effectuée, on verra si faut bannir d'autres labels avec le temps.
Je teste encore un peu ce soir et  je modifie le uptostream.py plus tard.

**Comment by Kodigoal** [comment]
Maj uptobox.py ok.
Par contre j'ai pas réussi à faire fonctionner le showSubTitles pour que le Player
n'active pas les sous-titres au lancement , c'est vrai que ca peut être embétant 
si yen a sur les Films en French (souvent le cas) ...
Mieux vaut les activer manuellement si besoin, je sais pas trop...

**Comment by TmpName** [comment]
La fonction c'est showSubtitles(visible).
Mais en fait moi je pensais justement la forcer a visible, Sur les film "French" les fichiers sous titres c'est pas tous des "forced" ?

**Comment by Kodigoal** [comment]
Oui j'ai essayé la fonction mais j'arrive pas à desactiver xD 
Par exemple , sur le film superman vs batman 720p TrueFr tu as 2 .srt
( souvent c'est le cas en testant) , il vire le forced mais te reste  les sous-titres
en francais ^^

**Comment by TmpName** [comment]
Et merde, il mettent des sous titres fr sur un film deja en fr ?
Vais voir comment utiliser cette fonction.

**Comment by TmpName** [comment]
Bon ben j'ai pas trouve, en fait Vstream utilise  methode et je sais pas comment les desactiver siu on utilise la methode via xbmcplugin.setResolvedUrl

Proposer les sous titre dans le popup qui affiche le choix de la qualites ?

**Comment by Kodigoal** [comment]
Bon on peut les désactiver par les options du player icone son ( en appliquant à toutes les vidéos le changement ) , après oui pourquoi pas les proposer dans la popup.

**Comment by TmpName** [comment]
Ouais mais le truc c'etait de se simplifier la vie au depart, je suis sur qu'il y en a qui ne savent meme pas comment fonctionnent les sous titres.
Si il y en a plus qui doivent les desactiver pour pouvoir lire le film que les activer, on cree plus de problemes que de solutions.

Faudrait vraiment ne les proposer que si necessaire, meme si ils sont manquants dans certains cas (il ya tjours la solution opensubtitle via la meme icone au pire.

**Comment by Kodigoal** [comment]
Je vois bien une popup après le choix de la résolution genre ' Sous-Titres disponibles , voulez-vous les télécharger?  oui/non ' , 1 click de plus mais comme ca chacun à le choix et on a vraiment tout à dispo
comme sur le site:
Choix piste audio / qualité / sous-titres

Car pour les films en fr , ca peut être aussi
utile d'avoir le choix de charger les sous-titres si présents  si ya des utilisateurs sourds malentendants par exemple.

Ou laisser comme ca avec le message ' sous-titres disponibles 'pour informer  et rajouter en dur le lien  d'un .srt vide en début de liste subTitle ,  et si on veut les sous-titres , on fait 'suivant' dans l'icone ^^

Sinon je vois pas trop comment on peut définir ou c'est nécessaire de les charger ou pas tellement ca varie d'un lien à l'autre.

**Comment by TmpName** [comment]
Ha ?
Si on rajoute un srt vide ? ca affiche rien juste, pas de bug ? Pas de message d'erreur ?
Si oui je pense que c'est une bonne solution, y a plein de fenenat qui ralent qu'il y a trop de clic a faire pr acceder aux videos.

Car parfois sur un film il y a 4/5 resolution en fr 4/5 resolution VO, si on rajoute les st sur la meme fenetre ca fait trop de choix, et un second popup ....

**Comment by Kodigoal** [comment]
Après test , si tu le laisses vide le .srt (en le rajoutant en dur en début de liste donc) ,  il va choisir le 2ème .srt.
Donc suffit de mettre dedans qu'à la 50ème heure de visionnage de la vidéo , il affiche Vstream par exemple: 
Contenu .srt
1
50:00:00,240 --> 50:00:00,250
Vstream

Faut voir pour trouver un nom au fichier 
.srt qui sera affiché dans la liste des srt dispos qui indique que c'est le suivant le bon
srt à activer .. 
Vide.fr.srt = French-Vide 
Vide.srt = inconnu-Vide
srt-suivant-ok.fr.srt = French/srt-suivant-ok

Je sais pas trop quoi mettre là.
Et pour le .srt, on l'héberge ou ? 
github ou en local

**Comment by TmpName** [comment]
Ha merde c'est plus bidouille que ce que je pensais.
Et en commencant par
>Files.append('')

Ca va creer un fichier n'existant pas, ca marche pas ?

**Comment by Kodigoal** [comment]
Non il passe au 2ème .srt aussi ^^
Tester encore de trouver comment désactiver au lancement de la vidéo , mais rien à faire ..
avec le xbmcplugin.setSetting mais rien trouvé qui fonctionne ...
Soit lien en dur , le moins compliqué , juste voir ou l'héberger .
Soit pêtre au choix de la popup uptostream/uptobox , rajouter 1 choix  via uptostream + sous-Titres ..
Pas joli joli non plus...

**Comment by TmpName** [comment]
Pareil j'ai meme teste en simulant des raccourcis clavier.
Tu peux demander sur les forums de kodi, mais pour infos, moi j'y ai jamais eu de reponses.

En fait le prb c'est que le mec a juste a activer les sous-titre opensubtitle en bas de l'ecran, donc si on fait quelque chose, il faut que se soit plus simple, sinon ca sert a rien.

**Comment by Kodigoal** [comment]
En fait t'as l'impression que tant que la vidéo n'a pas commencé dans le player , tu peux rien lancer comme commande pour désactiver les sub.
Si tu mets un sleep  c'est bon , on peut les désactiver mais ca affiche la notification ' sous-titres désactivés' ....
(pour test 35sec de pause)
xbmcplugin.setResolvedUrl(sPluginHandle, True, item)
xbmc.sleep(35000) xbmc.executebuiltin("Action(ShowSubtitles)")

Donc encore mieux charger un .srt tuné pour que rien s'affiche et click 'suivant' si on les veut ..
Ou afficher seulement sur les noms des fichiers qui contiennent vostfr vo ..
Ou seulement les séries.

**Comment by TmpName** [comment]
Bon alors, je pense qu'on va mettre les sous-titre en pause car j'ai trouve un prb dans le lecteur.
Comment desactiver les sous titres
```
        player = xbmc.Player()
        for _ in xrange(30):
            if player.isPlaying():
                break
            time.sleep(1)
        player.showSubtitles(False)
```

En fait il faut simplement attendre que le lecteur demarre.

Mais il y a un soucis dans le code.
```
        while not xbmc.abortRequested:
            try: 
               self.currentTime = self.getTime()
               self.totalTime = self.getTotalTime()
            except: break
xbmc.sleep(1000)
```
En fait il n'ya pas de fonction gettime() et gettotaltime() donc on passe direct au break, et on quitte la boucle, qui apres tests ne sert a rien.

```
timer = int(cConfig().getSetting('param_timeout'))
xbmc.sleep(timer)
```
Je ne sais pas a quoi ca sert mais on ne peut pas le remplacer justement par ma boucle avec if player.isPlaying(): ?

**Comment by LordVenom** [comment]
Si y a une fonction getTime http://mirrors.xbmc.org/docs/python-docs/stable/xbmc.html#Player

**Comment by TmpName** [comment]
Ben Player().getTime() mais nous on a self.getTime() et comme cette fonction n'existe pas on passe direct au exept et break.

Je pense que c'est integre au lecteur now, car elle devrait bugguer, et moi ce me demande a chaque fois "voulez vous redemarrer au debut ou a 2 mn"

J'ai fais une modif dans le code avec une boucle qui attend que le lecteur demarre, casupprime en passant le message d'erreur
>EXCEPTION: XBMC is not playing any media file 

Qu'on avait a chaque fois, mais du coup
>#timer = int(cConfig().getSetting('param_timeout'))
   #xbmc.sleep(timer)

Ne sert plus a rien pour moi.

Chez moi ca marche, permet de desactiver les sous titres, mais je sais que tu as trouve pas mal de bug dans le lecteur que je n'ai jamais vu sur ma version, donc je sais pas ce que mes modifs vont entrainer.

**Comment by TmpName** [comment]
Heu , en fait nope ^^.

J'ai un bug curieux, je sais pas d'ou il vient, mais depuis ma modif, a chaque video que je lance, via vstream ou pas, j'ai un message qui me demande si je veux demarrer a 0.02 ou reprendre depuis le debut.

**Comment by Kodigoal** [comment]
Même bug xD  sinon ok pour les sous-titres qui sont désactivés au lancement , ca fonctionne^^

**Comment by LordVenom** [comment]
`xbmc.Player.__init__(self)`

Self et xbmc.Player c'est pour ça qu'on peux apeller les fonctions onPlayBackStopped ect... si y a plus de boucle les fonctions pause stop play ne fonctionne plus. A tu regarder ce que font les fonctions setSubtitleStream, setSubtitles, showSubtitles

**Comment by LordVenom** [comment]
Bon ça fonctionne quand ça veut faut quand même les laisser peux importe la boucle 

while not xbmc.abortRequested: , while self.isPlayingVideo():, mais on peux try au pire.

` try: self.totalTime = self.getTotalTime()
            except: pass
            try: self.currentTime = self.getTime()
            except: pass`

**Comment by TmpName** [comment]
Yep j'ai compris ca apres.
Pour le moment j'ai une nouvelle version qui corrige tout nos bugs, le message d'erreur qu'on avait avant, les sous titres et mon bug a la con , mais il me faut laisser ta boucle (me demande pas pkoi, mais elle est indispensable).

Effectivement mettre la fonction dans onPlayBackStarted marcherait, mais je prefere eviter de polluer le code, la au moins on a toutes nos fonctions sous-titres ensembles, on peut desactiver le bloc complet juste avec un if ou un try.

La je suis en train de lire le code du player maintenant que j'ai compris qu'il marche avec celui de Vstream, et je m'apercois de la complexite du truc, le premier createur a du faire gave de tests avant de tomber ca.

Ca gere meme les ancien "resume" avec le popup vstream et les nouveaux avec le popup kodi, je pensais que tout etait automatique moi.

@LordVenom j'ai fait une modif qui supprime le second
>EXCEPTION: XBMC is not playing any media file 

Quand on quitte la video avec la ligne
>while self.xbmcPlayer.isPlaying():

Ca risque de provoquer des bugs ?

**Comment by nmagre** [comment]
J'ai pas tout suivie mais pour l'histoire du "timer" si il est dans `while self.xbmcPlayer.isPlaying():` c'est tout simplement pour ne pas occuper le CPU a 100%, en générale on fait `while monTestEstFaux(): "attend X millisecondes ou secondes"`.

**Comment by LordVenom** [comment]
Normalement non

**Comment by TmpName** [comment]
Nope, je parlais de ce timer
```
timer = int(cConfig().getSetting('param_timeout'))
xbmc.sleep(timer)
```

Que j'ai vire vu que j'utilse
```
        #Attend que le lecteur demarre, avec un max de 10s
        for _ in xrange(10):
            if self.xbmcPlayer.isPlaying():
                break
xbmc.sleep(1000)
```

Mais a part supprimer un message d'erreur dans les logs, je ne vois pas a quoi il servait, je n'avais aucune difference avec ou sans.

Enfin bon du coup les sous-titres fonctionnent a 100 % ? J'ai pas vu ton code ou tu regardes si "vosftr" se retrouve dans le titre @Kodigoal ?

**Comment by Kodigoal** [comment]
def checkSubtitle(self,sHtmlContent):
        oParser = cParser()
        
        sPattern = "<head><title>(.+?)</title>"

        aResult = oParser.parse(sHtmlContent, sPattern)
        
        
        if 'VOSTFR' in aResult[1][0]:

           
           oParser = cParser()
           sPattern = "<track type='srt' kind='subtitles' src='([^']+)' srclang='.+?' label='([^']+)'>"
           aResult = oParser.parse(sHtmlContent, sPattern)
           if (aResult[0] == True):
               Files = []
               for aEntry in aResult[1]:
                   url = aEntry[0]
                   label = aEntry[1]
                
                   if not url.startswith('http'):
                       url = 'http:' + url
                   if 'Forc' not in label:
                       Files.append(url)
               return Files
        else:
            return False

Bon vu qu'on désactive les sub , mieux vaut plus trier pour pas en louper si présent xD
Pêtre juste le "Forced" à corriger en 'Forc',  j'avais vu un 'Forcé"  sur un film.

**Comment by TmpName** [comment]
J'ai encore trouve un petit prb sur le player suite a mes modifs. Si tu lances une video 1 et que sans l'arretter tu lances une video 2, ca va te demander si tu veux "resumer" la video2 au moment ou tu en etais sur la video 1.

**Comment by Kodigoal** [comment]
Ok j'ai modifié le 'Forced' en 'Forc' et virer le message 'sous-titres disponibles'.
Par contre si on lance les liens sans compte gratuit ou premium , pas de sous-titres chargés.
On laisse comme ca ? 

J'ai encore parfois le bug qui affiche la fenêtre 'reprendre vidéo ...oui-non' .

**Comment by TmpName** [comment]
On corrigera plus tard le coup du premium/free, il doit marcher partout mais la fenetre de reprendre me saoule.
Tu arrives a la provoquer toi ? impossible de savoir si c'est normal ou un bug, tellement c'est rare, sauf hier soir ou ct a chaque episode, mais ce matin plus rien.

Tu devrais supprimer le bug en inversant les lignes 107 et 108, mais je sais pas pkoi (et je pense qu'il faut redemarrer kodi aussi)

**Comment by TmpName** [comment]
Bon, je vois plus de bug la.
Nouvelle version du player et du fichier uptobox gerant les ST dans tout les cas, enfin j'espere.

**Comment by Kodigoal** [comment]
La détection 'vostfr' ne fonctionne pas de mon côté.
Jouer un peu avec le re.match mais j'arrive à rien...
J'ai encore le bug popup  par contre en faisant mes tests , j'ai vidé les cache addon et xbmc mais toujours là.

**Comment by TmpName** [comment]
Moi j'ai plus le bug !
J'ai fais mes test sur une serie jamais vue.
Et si je lance un nouvel episode, pas de popup.
Je lance un second episode, tjours pas.

Tu as quoi comme temps sur le popup ?

**Comment by Kodigoal** [comment]
Ya des temps aléatoires en seconde là.
Suffit que je lance une série sur zt via uptostream ou uptobox , je stoppe je relance 1-2x et j'ai la popup , qui sera après sur toutes les vidéos.
Même si j'ai d'abord la fenêtre vstream pour reprendre par exemple à 40min un film ,  je lance et m'affiche popup avec 'reprendre à x secondes' ..
Vais refaire test plus tard , même en inversant les
lignes 107-108 j'ai le bug.

**Comment by TmpName** [comment]
Aucun prb chez moi, enfin si mais c'est nouveau
J'ai le popup de reprise de kosi avant de choisir si je veux passer par uptostream ou uptobox et quand le film demarre j'ai le popup de Vstream.

Par contre aucun prb si je lance l'episode d'apres.

Tu es sur d'avoir la derniere version et d'avoir redemarre kodi ?

Sinon j'ai corrige uptobox pr la detection vostfr.

**Comment by Kodigoal** [comment]
En fait j'ai pareil que toi.
Je lance un film sur Kepliz , j'avance à 6min et je stoppe.
En relancant ,  ya la popup kodi pour commencer à 6min ou du début.
Et une fois la vidéo lancée, la popup vstream s'affiche reprendre à 6m30 oui ou non.
Il rajoute à chaque fois 30 secondes au temps ou je stoppe la vidéo.
Si je stoppe à 5m50 , il affichera 5m80.

Merci pour la détection , ca fonctionne ^^

**Comment by TmpName** [comment]
Ben je sais pas ^^.
Faudra comparer avec la vielle version, si ca se trouve le bug etait deja la, mais on y faisait moins attention.

Le popup kodi est plus chiant car il demande a reprendre avant meme de resoudre le lien, meme si celui ci n'existe plus.
Me faut faire des tests pr le decalage de 30s, mais ca peut aider a trouver pkoi ca deconne.

Pour le double emploi, je pense que a l'origine kodi ne le gerait pas, ou moins bien, mais la de proposer avant de resoudre le lien c'est pas le top.

Je cherche des infos, et je te dis, en attendant faudra faire gaffe a ne pas faire la MAJ trop tot (on approche de la fin du mois)

**Comment by TmpName** [comment]
Bon j'ai commence les tests, et non seulement j'ai plus les bugs mais le temps est bon aussi.
Faut juste faire gaffe que le temps en en centieme et non pas secondes, 0.25 = 15s pas 25s.

**Comment by Kodigoal** [comment]
En fait après d'autres tests , c'est pas toujours 30s de décalage ... et sur certains liens elle apparait pas.
Mais si tu dis oui pour reprendre sur la popup vstream  il met au bon temps ..
Pêtre qui ya un moyen de désactiver le resume kodi , sinon je vois pas trop, a part désactiver le resume vstream...

**Comment by TmpName** [comment]
En tout cas le bug est revenu chez moi (celui des 10s a chaque demarrage) , et je pense savoir comment le provoquer, j y jette un oeuil demain.

Desactiver le resume kodi, je pense pas que ce soit possible, celui de Vstream si, mais je sais pas si les gens le trouve utile.

**Comment by LordVenom** [comment]
La double popup c est a cause des versions de kodi le player des vielles version ne supporte pas le résume a trouver depuis quand c est automatique et il suffiras de faire un if sur la version.

**Comment by johngf** [comment]
pour ce qui est des sous titre j'ai fait la meme chose avec openload pour les sous titre de leur lecteur(quand il y en a pour l'instant 1 seul video testé j'ai pas cherché plus)
https://raw.githubusercontent.com/johngf/venom-xbmc-addons/Beta/opl

par contre la popup qui te previens pour les sous titres ne s'affiche pas des fois ou est fermé trop vite

**Comment by TmpName** [comment]
Y a aussi des vostfr sans tous titre incruste sur openload ?
Sinon j'ai le bug sur easyvid mais pas sur openload, je cherche encore pkoi.

Sinon avec la V17 qui va sortir, je pense qu'il n'y a plus trop de monde sur une V14 ou moins. On pourrait le desactiver, mais perso c'est plutot celui de kodi que je cherche a virer.

**Comment by johngf** [comment]
Oui il y en a pour la popup de kodi on peut la kill avec son id quand elle veut s'affiché je l'ai fait une fois pour la fenetre en cour....

**Comment by TmpName** [comment]
Bon j'ai mis une nouvelle version en ligne, avec plus de ligne de debug
Decommenter la ligne 113 pr les tests.

Il y a un gros probleme, quand on selectionne une seconde video, sans fermer la premiere, les deux tournent en meme tmeps (meme si on n'en vois qu'une seule) en regardant la valeur de self.currentTime().

A la premiere video, un affichage toute les seconde, au bout de 2 videos, 2 toutes les secondes, et le log "Closing player" n'apparait QUE si on ferme avec la touche X par exemple, et si y avait 2 video,  on a 2 fois l'inscription des les logs.

En fait a chaque nouvelle video rajoute, cette valeur repart a zero.

**Comment by johngf** [comment]
Est la commande stop() ?

**Comment by LordVenom** [comment]
Pour le moment ont peux trier avec cConfig().isDharma()

**Comment by TmpName** [comment]
Ca y est j'ai finallement trouve ^^.

J'utilise l'event onPlayBackStarted pour savoir si un film demarre au lieu de isplaying() car si c'est une autre video que celle qu'on veut voir ca donne True aussi.
J'utilise une detection de bug (qui repere un second onPlayBackStarted () lors du demarrage de la seconde video) qui me fait quitter la boucle avec self.forcestop(), et oui car comme la seconde video tourne, isplaying est tjours a True, meme si ce n'est plus la meme video.

Et now ca marche chez moi, y a toujours les 2 popup pour resumer, mais plus de prb.

Now on garde kel popup ?
Soit on code un truc comme le dit Lordvenom
Soit on vire tout simplement celui de Vstream (pas sur qu'il y en ai encore sous de vielles versions), sachant que seule la V17 gerant correctement le SSH (j'ai deja des bugs sur un hebergeur a cause de ca)
Soit on cache celui de Kodi, la je sais pas faire, et perso j'ai plus de reglage sur celui de kodi par defaut, eg ilk ne memorise pas la position si je regarde moins de 5% du film ou si je quitte 10% avant la fin.

**Comment by Kodigoal** [comment]
Pour être sur de pas léser d'éventuels utilisateurs de vieilles versions , un petit if ferait l'affaire même si c'est tentant de tout virer xD 

Je vais test tes modifs pour voir.
Pour la popup st , parfois elle disparait vite , et à part la popup en cours ya rien d'autre , ou c au lancement du player ca coupe les notifs cash pêtre ? si la vidéo s'ouvre vite , on la voit moins longtemps ?

**Comment by johngf** [comment]
Pour la popup des ST c'est a cause de la popup en cours.... elle doit empecher l'autre de s'ourir correctement

**Comment by TmpName** [comment]
Y a encore un truc que j'ai pas fais car je trouvais ca inutile, si on selectionne une seconde video sans arretter la premiere, ca saute une partie, je pensais que c'etait pas grave, mais du coup ca ne met pas la video en "vu", donc pas bon.

Pour le coup de la popup "en cours" je vais avoir si j'arrive a m'intercaller entre elle et le debut de la video.

**Comment by TmpName** [comment]
Bon encore une version a tester ^^.
Ca passe par toute les parties, et j'ai decale la fenetre de sous titre a apres le popup "en cours".
Ca marche moyen si il ya aussi un "resume"

**Comment by johngf** [comment]
pourquoi pas viré la fenetre en cour si il y a des soustitre ?
http://forum.kodi.tv/showthread.php?tid=252426

**Comment by TmpName** [comment]
Put1 que c'est beau comme fonctions je les rajoute de suite dans Vstream, meme si ca sert pas aujourdhui, ca pourrait servir.

Sinon la le popup s'affiche apres, donc ca gene plus, et surtout si ca rate durant le "en cours" ca affiche pas la fenetre pr rien.

**Comment by TmpName** [comment]
MAJ dans 2 jours. Ca a l'air bon ?

On desactive le "resume" pour les version recente ?

**Comment by LordVenom** [comment]
Oui

**Comment by TmpName** [comment]
Ca je prefererais eviter d'y toucher pr le moment, ca gene pas, et me faut approfondi le truc. Tu te souviens a un moment quelqu'un a eu des prbs a cause d'un conflit avec le "lu" de kodi et celui de vstream.
Me faut retrouver l'issue avant de toucher a ca, et retester.

Par contre je trouve plus de film avec ST a part pr tester (et suis pas en premium) donc si quelqu'un peut confirmer que c'est bon aussi.

Je m'occupe de la deasactivation du resume pr version recente.

**Comment by TmpName** [comment]
Bon j'ai desactive les 2 finallement, watched et resume, uniquement pour l ecriture dans la base de donnée, aucune modif sur la lecture de la base de données, mais si on ecrit pas dedans Vstream ne s'en servira pas.

Je teste ce matin.

**Comment by Kodigoal** [comment]
Ou uniquement via uptostream ( et via openload vu johngf)  , en direct via uptobox il charge le mkv qui contient les srt.
D'ailleurs faudrait aussi retoucher le uptostream.py pour les liens directs via les autres sites non ?
Pour l'instant ca a l'air bon tes modifs , je teste encore.

**Comment by TmpName** [comment]
Ouais c'est pour ca que ca marchait plus, j' y ai pense apres ...

Ben moi je trouvais pas ca genant d'avoir encore le popup pour les anciennes videos, en fait ca commencait a marcher pour les nouvelles. Du coup je rajoute la selection de version partout.

Apres pr le tri on pourra toujours modifier les fichiers sites, mais plus le fichier player.py, c'est pour ca que je prefere etre sur.

**Comment by Kodigoal** [comment]
Sinon dans le log ya ca en lancant les vidéos:

> NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
13:59:30 T:1941095400   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/player.py:25: DeprecationWarning: object.__init__() takes no parameters
                                              xbmc.Player.__init__(self,sPlayerType)
13:59:30 T:1941095400  NOTICE: 	[PLUGIN] Vstream: player initialized

Je sais pas si c'est normal comme erreur?

**Comment by TmpName** [comment]
Oui et non.
Cf http://forum.kodi.tv/showthread.php?tid=173887&pid=1516662#pid1516662

En fait Vstream utilise de vielles fonctions qui ne servent plus.
Moi c'est rigolo mais je ne l'ai pas ce message d'erreur. Ca provoque un bug ?

**Comment by Kodigoal** [comment]
Non pas de bug en vue ^^ 
Je tourne sous kodi 15.2/android pêtre pour ca.

**Comment by TmpName** [comment]
Alors en fait cette partie ne servirait que pour XBOX, et uniquement en passant par la fonction play().
Je sais pas si il vaut mieux la laisser ou pas, mais sur windows elle ne sert a rien.

Autre prb si on passe par XbmcPlugin aucun prb mais si on passe par Xbmcplay et mplayer, ca marche mais on a un message d'erreur a chaque fois.
La premiere fois qu'on lance video > erreur de chargement alors que la video tourne
La seconde fois plus de prb
J'ai essaye de jouer avec la ligne xbmcplugin.endOfDirectory(sPluginHandle, True, False, False)

J'ai eu a chaque fois un prb different.

**Comment by TmpName** [comment]
Bon ben ca marche en mettant sur auto, donc je laisse tomber, pas besoin de s'arracher les cheveux.

Si tu n'as pas encore rajoute ton code, met la ligne suivante en commentaire en meme temps stp
`<setting id="param_timeout" label="30027" type="number" default="1000"/>`

Sinon moi j'aurais fais
```
if (self.SubtitleActive):
     if (cConfig().getSetting("srt-view") == 'true'):
     else:
```

**Comment by Kodigoal** [comment]
Par contre je met ou l'option dans settings.xml , enfin quel onglet? ^^
ok je vais modif comme tu dis c'est mieux.

**Comment by TmpName** [comment]
Moi je le mettrais dans l onglet "general"

**Comment by Kodigoal** [comment]
Je vais le changer de place ^^
Sinon je comprends pas pourquoi la popup 'sous titres charges' avec  un délai de 15sec disparait en 1-2 sec au lancement de la vidéo en mettant l'option 'activer les sous titres' sur Non,
et si on active auto les srt , j'ai mis une popup ' sous titres' avec délai 5sec qui dure bien 5 secondes,
ca dure trop longtemps xD pourquoi elle part pas comme l'autre plus vite ? 
J'ai loupé un truc là ... ou on vire cette popup si on active auto ? je sais pas si elle est très utile dans ce cas?

**Comment by TmpName** [comment]
Peut etre que le fonction showSubtitles() prend plus ou moins de temps selon si c'est true ou false, apres c'est kodi faut pas chercher a comprendre, faut faire avec, en trichant sur les tempo ou en mettant des sleep().
Par contre je laisserais la popup, au pire l'user la vois pas donc ca derange pas, et en cas de bug, il pourra tjours dire si il a vu la popup ou pas (meme si ca dure 1s).
