### ISSUE TITLE
entrée/sortie d'un répertoire

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#580]
bonjour, après avoir testé sur linux avec kodi jarvis 16.1 et sur windows7 avec kodi 15.2 et 16.1 
sur deux pc différent je pense qu'il y a un soucis.
Quand on navigue sur vstream par moment la table met un certain temps a s'initialiser pour enter ou sortir d'un répertoire ce qui donne comme résultat en cours..... de 30s a 1min30
quelqu'un peut-il confirmer si c'est pareil chez lui ?

http://pastebin.com/ngBk3J9J

**Comment by LordVenom** [comment]
dsl chez moi c'est instantanée a chaque foix

'09:31:52 T:6304  NOTICE: 	[PLUGIN] Vstream: Table initialized
09:31:53 T:4896  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
09:31:53 T:4896  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showMovies
09:31:53 T:4896  NOTICE: 	[PLUGIN] Vstream: Table initialized
09:33:41 T:6944  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
09:33:41 T:6944  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showMovies
09:33:42 T:6944  NOTICE: 	[PLUGIN] Vstream: Table initialized
09:33:44 T:6976  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
09:33:44 T:6976  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showMovies
09:33:44 T:6976  NOTICE: 	[PLUGIN] Vstream: Table initialized'

**Comment by johngf** [comment]
xbmc.python >> pas trouvé
script.module.urlresolver >> l'ajouté ne change rien
de addon.xml ne sont pas dans le depot kodi

**Comment by johngf** [comment]
probleme trouvé c'est du a ma connection internet qui a un soucis (a cause de travaux dans ma rue)
mon debit fait du yoyo donc meme si je navigue dans les pages sans site le fait que vstream verifie si il ya une mise a jour ralenti le chargement de la page

**Comment by LordVenom** [comment]
Il ne fait pas que ça en arrière plant il prend des stats aussi.

**Comment by johngf** [comment]
bon finalement je ne pense pas que ma connection internet soit le problème j'ai remarqué a chaque bug pour entré dans un répertoire un fichier .fi est créé dans le dosier temp genre 10025-d3dbaaea.fi 
(que j'ai lu avec un éditeur hexadecimal)
si je sors du repertoire et y retourne il est supprimé.
peu d'info sur le net concernant ces fichier .fi certain parle d'erreur d'autre de cache.
apparament il enregistre l'url du repertoire visité et d'autre info sur l'addon

plugin://plugin.video.vstream/?function=showDocs&sFav=showDocs&site=cHome&siteU3rl=http%3a%2f%2fvenom&title=%5bCOLOR%20gray%5dDocumentaire%5b%2fCOLOR%5d.

**Comment by TmpName** [comment]
Ha oui, je connaissais pas mais apparement ca ne serait utilisé que quand tu passe par les favoris de kodi (et uniquement kodi V16).

Je galere pr trouver des infos "fi" c'est court pour une recherche sur google.

Mais ca n'explique pas le prb, pourquoi ca ralenti le systeme, c'est pas la creation de ce fichier qui prend 30s.

**Comment by johngf** [comment]
bah apparament si on dirait qu'il galère a le faire

**Comment by TmpName** [comment]
Un timeout ?
L'addon essaye peut etre de se connecter quelque part, tu as pas des messages d'erreur sur des sites non joignables ?

**Comment by johngf** [comment]
jamais aucun msg d'erreur c'est comme si j'avais des trous dans ma connection
