### ISSUE TITLE
Interfaçage avec AllDebrid

### ISSUE THREAD

**Issue by tonydd** [Kodi-vStream/venom-xbmc-addons#584]
Hello !

Alors déjà, super add-on, merci beaucoup !

Une petite proposition/idée : en ce qui concerne le streaming, le service alldebrid (que vous devez surement connaitre) permet, quand on a un compte, de débrider les liens et de générer des liens de streaming en illimité. Ils ont une API qui permet d'utiliser cette fonctionnalité en HTTP (j'ai déjà sous la main un script shell qui permet de débrider, si ça peut aider) et ce serait vraiment génial de pouvoir entrer son compte quelque part (fichier de conf ?) pour profiter du streaming sans limitation \o/

Je suis disposé à participer au dev si il y a suffisamment d'infos pour m'aiguiller !

Si cette possibilité existe déjà et que j'ai mal cherché/regardé, mea culpa ...

**Comment by nmagre** [comment]
Ça existe déjà, dans les options tu as "Configurer URLResolver" (il faut l'installer) ou tu peux ajouter ton compte alldebrid/real-debrid/...

**Comment by tonydd** [comment]
Effectivement c'était si con que ça, au temps pour moi ...

Merci !
