### ISSUE TITLE
Recherche par "type"

### ISSUE THREAD

**Issue by nmagre** [Kodi-vStream/venom-xbmc-addons#585]
Actuellement si je définis par exemple pour "Search 1" le nom "Films" lors de la recherche il va retourner tout et n'importe quoi parce-qu’il va (si j'ai bien compris) utiliser 'URL_SEARCH'.
Hors certain sites peuvent faire des recherches plus fine dépendante du "type" que l'on recherche.

L'idée serais de définir en dur (ou pourquoi pas de façon dynamique mais ça me parait compliqué) des "type" pour la recherche Ex: 
  "Search 1"  :  name = "Films" , type = "Movie"

Ça permettrais de passer ce paramètre lors de la recherche pour utiliser la "bonne" méthode (si c'est possible), voir même d'aller plus loin et avoir une fonction 'getSupportedSearchType' et donc pouvoir récupérer de façon automatique la liste des sites par rapport a un "type".

Hors sujet (je peux rajouter d'autre "issue" pour ça) :
- Une amélioration pour la recherche de "zone_telechargement_com.py" toute bête est de supprimé les doublons en comparant les URL des images (ça ne supprime pas tout mais ça élague déjà pas mal)
  
  Ex : (je n'y connais rien en python)  
      Fonction `showMovies` :

``` python
    if (aResult[0] == True):
        sThumbLnks = []            // Thumbnail link list
        total = len(aResult[1])        
        for aEntry in aResult[1]:

            sTitle = str(aEntry[2])
            sUrl2 = aEntry[0]
            #sFanart =aEntry[1]
            sThumbnail=aEntry[1]

            if sThumbnail in sThumbLnks: // If thumbnail link already exist skip it
                total = total - 1
                continue

            sThumbLnks.append(sThumbnail)
```
- Certain débrider supportent les liens "protégés" et du coup c'est dommage de demander le captcha alors que le debrider peux être utilisé (Ex: realdebrid et les liens dlprotect).

**Comment by TmpName** [comment]
Alors pour le point 1.
Je suis d'accord, y a un probleme ici. En fait ce que tu dis est deja en place jette un oeuil sur cette source https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/libertyland_tv.py
Mais ca na marche QUE avec la config par defaut, a cause du probleme dont tu parles. LordVenom a modifie cette partie pour faire "Film recent' et "Vieux films" du coup chez lui cette souce doit bugguer.
J'ai pas encore trouve de methode pour ce probleme sans faire de facon non dynamique. On pourrait faire film/serie/animes/perso et pouvoir modifier la categorie perso, mais il en faudrait plusieurs et on a des probleme sur les machines qui ont une vielle version de kodi, les "dialogues dynamiques" deconnent.

La seule solution que je vois c'est un combo avec des categories predefinies quitte a en mettre 10 et en utiliser que 4. Ce serait plus clair (on utiliserait "catfilm" ou lieu de "search3" mais ca changerait le mode de fonctionnement de Vstream, donc faut l'avis du boss, ou une methode plus light que j'ai pas trouve.

Pour le point 2.
J'y ai pensé aussi, mais pas fiable, dans certains cas ils ont des doublons (exactement la meme video, meme qualite mais page differente) on perdrait du coup pas mal de liens fonctionnels, et y a aussi le prb du VF VOSTFR, pas les meme fichiers mais la meme affiche.

Pour le point 3.
La je savais meme pas, et c'est fiable a 100 % ? car si on supprime cette option ce sera impossible aux utilisateur de debrideur de taper le captcha ?

En tout cas pour le point 1, je suis d'accord, faut faire quelque chose, mais je sais pas encore quoi.

**Comment by nmagre** [comment]
Pour le point 1.  

J'avais aussi pensé à utiliser `disp` comme il le fait mais forcément ça ne marche pas, d’où le faite que j'ai proposé d'attribuer un 'type'.  
J'ai peut être loupé un épisode mais ce que je proposais doit fonctionner avec le design actuel (même si le refaire serais je pense plus judicieux)

- Créer une liste/énumération/... global en dur dans le code  
  Ex: Movie, TVShow, ...., None
- Rajouter une combobox avec la liste fixe de 'type' en dessous de chaque "Recherche personnalisé" dans la config.
- Lors de la création du menu de recherche ajouter 'type' a `cOutputParameterHandler`
- En théorie tout marche encore ya plus qu'a modifier les fonctions de recherches des sites avec un switch/case.

Pour le point 2.  

La "seul" méthode pour un "vrai" filtre de doublon serais d'avoir un crawler externe ce qui n'est pas vraiment envisageable ou de faire une requête par résultat donc trop lent.
Cependant étant donné que l'on peut trier par date et que la probabilité que les liens soit fonctionnels sur une source plus récente est plus forte que sur une ancienne source, je pense que ça vaut le coup. Il faudrait faire plus de test pour voir si il y a beaucoup de cas défavorable (j'en ai fais quelques un sur des films et j'en ai pas trouvé encore).

Pour le point 3.  

Pour "real-debrid" et "dlprotect", oui a 100%. J'avais il y a longtemps trouvé un moyen de le faire en java mais ça ne fonctionne plus et j'ai passé pas mal de temps à chercher une autre méthode mais sans succès. A mon avis ils ont un partenariat ou quelque chose dans ce goût là (ou il sont bien meilleur que moi, ce qui ne m’étonnerais pas)

**Comment by nmagre** [comment]
J'ai fais un mini test et ça a l'air de coller.  

Fichier `home.py` , fonction `showSearch`

```python
        oOutputParameterHandler.addParameter('siteUrl', 'http://venom')
        oOutputParameterHandler.addParameter('disp', 'search1')
        oOutputParameterHandler.addParameter('type', 'movie') # FIXME Use config: cConfig().getSetting('search1_type')
        oOutputParameterHandler.addParameter('readdb', readdb)
        sLabel1 = cConfig().getlanguage(30077)+": "+cConfig().getSetting('search1_label')
        oGui.addDir(SITE_IDENTIFIER, 'searchMovie', sLabel1, 'search.png', oOutputParameterHandler)
```

Fichier `zone_telechargement_com.py`, fonction `showMovies`

```python
    oGui = cGui() 
    oInputParameterHandler = cInputParameterHandler()
    sType = oInputParameterHandler.getValue('type') 

    if sSearch:
      if sType == "movie":
        sSearch = sSearch.replace(URL_SEARCH[0], URL_SEARCH_MOVIES[0])

      sUrl = sSearch


    else:
        sUrl = oInputParameterHandler.getValue('siteUrl') 
```

Par contre c'est pas très élégant de faire du `replace` a la sauvage au lieu d'utiliser la bonne URL directement.

**Comment by TmpName** [comment]
Par contre du coup on pourrait supprimer la ligne
>oOutputParameterHandler.addParameter('disp', 'search1')

Mais j'aimerais avoir le feu vert de venom d'abord pour modifier le mode de fctment de Vstream.
Car avant ca bugguait mais l'user pouvait mettre ce qu'il voulait.
Si on fait la modif il aura un choix predefinis, et si on fait un choix predefinis on met quoi dedans ?

Vieux films, Fims recent, Vielles Serie, serie recentes, Animes, documentaires, Emmissions TV, Favoris, Sport, .....

**Comment by nmagre** [comment]
Bonne question.

Il y a plusieurs choix, le problème est de ne pas en mettre trop. Une solution pourrais être de rajouter un autre paramètre 'quality' ou 'version' ou ..., pour éviter d'avoir 'film', 'film_hd', 'film_3d', 'série', 'série_vostfr', ....

Étant donné que c'est une recherche 'vieux'/'récent' ne me paraisse pas pertinent.
Je verrais plus quelque chose comme ça :

type :
- film
- série
- émission
- anime
- documentaire
- spectacle
- concert
- divers
- aucun

quality/version/.... :
- sd
- 4k
- 1080p
- 720p
- 3D
- screener
- hdlight
- vostfr
- aucun

**Comment by TmpName** [comment]
Tu imagines la gueule du dialogue de configuration ?
Et LordVenom justement s'est fait une section vieux film et une section film recent, certains sites sont specialise dans l'un d'entre eux, en fait le probleme c'est justement de ne leser personne
En fait moi je laisserais tout tel quel, et juste sous la case 
"recherche personnalisée " ou tu choisit le nom a y donner je rajouterais un combobox avec le type  a prefer pour la recherche Ca demande juste a rajouter 4  combobox.

Autre probleme, quand tu retournes dans pluggin on/off ca affiche "Recherche personnalisée 1" j'ai jamais trouve comment mais se serait cool si ca pouvais afficher "films" si justement la recherche 1 est pour les films.

**Comment by nmagre** [comment]
> Tu imagines la gueule du dialogue de configuration ?

Il y aurait juste 2 combobox de plus par "recherche personnalisée " (donc 8 a rajouter). Mais une combobox de plus ça marche aussi c'est juste qu'on peut moins filtré ce que l'on cherche.

>  Et LordVenom justement s'est fait une section vieux film et une section film recent, certains sites sont specialise dans l'un d'entre eux, en fait le probleme c'est justement de ne leser personne

Ça ne lèse personne, si tu recherche "king kong" avec le type "film", certes tu va avoir le film récent mais aussi le "vieux", donc je vois pas ou est le problème surtout que les 'type" ne s'applique que si c'est possible, donc même avec un 'type' "vieux film" (ou "vieux" serais a définir. 1990 < c'est vieux ?,  1950 < ? , ...  ) un site qui ne le gère pas va te renvoyer des résultats (si y'en a), sauf si tu compte faire que si il ne le gère pas il renvoie rien mais c'est pas très "user friendly".

> Autre probleme, quand tu retournes dans pluggin on/off ca affiche "Recherche personnalisée 1" j'ai jamais trouve comment mais se serait cool si ca pouvais afficher "films" si justement la recherche 1 est pour les films.

Je viens de regarder la doc d'xbmc et apparemment il n'y pas de condition sur un label donc mise a part modifier le xml (settings.xml) a la volé je ne vois pas trop comment tu pourrais le faire. A noté que de le générer si il existe pas au démarrage ou si la version du plugin a changé aurait été pas mal au lieu de l'avoir en dur.

**Comment by LordVenom** [comment]
Alors j'ai pas tous suivis mais pour le moment on ne touche pas a la recherche, mais ont peux ajouter un menu recherche étendue et avoir en dur les menu qui ce suivent exemple:

recherche 1
recherche 2
recherche étendue
- films
-- qualiter 
-- vf
-- vost
-series
-ectt

le tous et de faire ça dynamiquement afin de pas coder tous en dur.

functions type()
return lang

functions lang()
return qual

function qual()

bref je sais pas si vous avez compris l'idée;

ensuite pour les site ajouter un URL_MEGASHEARCH avec les possibilier de la recherche 

urlde recherche?q=1080&type=movie&lang=vf

MEGASHEAR = ()
append(q,qual)
apend(type,type)
append(lang,lang)

pour avoir un tableau avec une correspondance dans notre recherche par apport au site si il utilise q ou qual pour la qualiter chez nous c'est qual.

de la on refait un recherchehandler qui vas comparer les possibliter trouver avec les site donner et importer , recherche sur les sites pouvant le faire.

**Comment by TmpName** [comment]
Ben il y a peu de moteur de recherche qui prennent en compte la qualitee.
A part ZT ils prennent generalement film/serie/animees.

Moi je vois ca avec  1 combo juste dessous le nom que definis l'user.

Ca donnerait.
Recherche 1 : Vieux film / film avec tv-stremin g -ch
Recherche 2 : Film recent / film avec film-ilimitee
Recherche 3 : ZT / Film avec ZT
Recherche 4 Film HD / film avec Megastre am

ect ...

Et une fois dans le code il ya meme myen de continuer a utiliser "disp" au lieu de "type" du coup on garde la compatibilitee avec ce qui a deja ete fait, on a juste a completer les sources qui ne le gerent pas comme ZT.

Ca evite d'avoir a faire if type = "film' or type ="film hd' or type = '3d'
Si le mec choisit 'divers' ou 'aucun" tu utilises quoi comme moteur de recherche ?

**Comment by LordVenom** [comment]
ok dans les paremettres ont peux ajouter un type préférer pour la recherche films,anime,series,Mais l'idée d'une recherche etendu et pas mal aussi faut voir le nombre de site compatible.

**Comment by TmpName** [comment]
Ben je vous laisse cogiter pr la recherche etendue ^^, car la je vois pas encore comment mettre ca en place.

Et si j'ai le temps ce WE je commence la prise en compte des type pour Vstream, je ne fais aucune modif pouvant provoquer des bugs, je vais avancer a tatons, des que cela peut provoquer des bugs, je stoppe et on attednra la prochaine MAJ mensuelle. (car vais devoir aussi modifier les fichiers sites qui partent en MAJ auto)

**Comment by nmagre** [comment]
Rien ne presse pour la recherche.

> Ca evite d'avoir a faire if type = "film' or type ="film hd' or type = '3d'

Normalement les if/else ne devrait pas exister, mais le "core" devrait appeler les systèmes de recherche compatible et filtrer ensuite les résultats si besoin est (il faut voir si c'est compatible par rapport aux autres sites et pas juste ZT pour la notion de filtre).  

> Si le mec choisit 'divers' ou 'aucun" tu utilises quoi comme moteur de recherche ?

Le "divers" c'était pour tous ce qui ne rentre pas dans un "type" prédéfinit comme par exemple pour spion. Le "aucun" est mal formulé, c'était la recherche actuel (par source) donc "défaut" ou "source" aurait été bien plus explicite.

J'ai aussi plusieurs autres "suggestions" sur divers choses mais qui peuvent impliquer de gros changement sur l'architecture.

Exemple :   
- Ne surtout pas parser le html avec des regex (je vous invite a vous renseigner la dessus) mais plutôt utiliser XPath, ou un parser DOM (xbmc en fournit un il me semble). Ça permet de corriger plein de bug actuels sur les parser et aussi de corriger très rapidement un site si il change ou pour fixer un cas spécial. 

- Utiliser de l'objet (héritage) pour les sites notamment pour diminuer le code mais pas que en théorie les sites ne devrait pas s'occuper de l'UI (sauf cas spécial si y'en a) et aussi éviter de faire des requêtes (pour ça forcément ya des cas ou ya pas le choix), .... 

- ...

Je ne sais pas si ça peut vous intéresser, je ne prétends pas apporter "la" façon de faire mais plutôt des pistes a explorer et après libre a vous d'extraire ce qui vous intéresse.

**Comment by TmpName** [comment]
Pour le coup du XPath, j'avais utilise elementtree a un moment (apres c'est peut etre pas exactement la meme chose)  mais a des moment meme si j'utilsais ca pour faire le gros du travail, y avait tjours des bouts de code avec des regex (habitude quand tu nous tient).

Apres c'est purement personnel mais meme si c'est moins rapide et plus aleatoire, je trouve plus facile de modifier un regex, plus accessible, surtout avec des sites comme https://regex101.com/. Les sites modifiant aussi souvent la structure de leur page suis pas sur que ce soit plus efficace, apres je t'avous je suis tellement du cote des Regex que me suis meme pas pose la question ici.

**Comment by TmpName** [comment]
Bon j'ai commence mes tests, j'ai utilise exactement ton code, on pourrait eviter le replace en modifiant 
>URL_SEARCH = ('', 'showMovies')

Mais suis pas que ca serve pas ailleurs, et le replace me derange pas.

Normallement les user ayant la vielle version de Vstream mais le nouveau fichier site ne verront pas la difference.

**Comment by johngf** [comment]
planet streaming compatible

**Comment by nmagre** [comment]
XPath c'est différent de `elementtree` et ce n'est pas une obligation, personnellement je trouve bien mieux d'utiliser XPath que un simple parser DOM. Il y a un post intéressent sur le sujet sur le ![forum de kodi](http://forum.kodi.tv/showthread.php?tid=57386)

> Les sites modifiant aussi souvent la structure de leur page suis pas sur que ce soit plus efficace, apres je t'avous je suis tellement du cote des Regex que me suis meme pas pose la question ici.

Pour faire court c'est impossible de parser du HTML avec des Regex, il y a un tas de discussions, articles, ... sur le web qui en parle. Avec XPath et/ou DOM tu peux tester directement dans ton navigateur si ce que tu va faire fonctionne en plus.

Exemple : Je sélectionne la description des sites sur une recherche google :
 
![screenshot-2](https://cloud.githubusercontent.com/assets/5362098/19411761/c6518aee-9307-11e6-8ac4-3ba9e0393316.png)

En gros ya il y a que des inconvénients a utiliser des Regex mise a part que si tu ne connais pas un minimum le HTML (DOM) et XPath forcément il faut apprendre et ça peut être galère au début.

**Comment by LordVenom** [comment]
Oui c'est pas mal mais a trouver comment integrer ça c'est pas gagner.

**Comment by TmpName** [comment]
Oui mais a partir du moment ou on se fiche de parser du html mais du "texte brut" (pour ne pas utiliser le mot html) tu as de forte chance de repasser par les regex.

Ca peut servir pour trouver les vignettes, les titres, les resumes, tres facilement. vu que le document est structure, mais au bout d'un moment si tu as besoin de 2 lettres d'un mot precis qui n'apparait que a certaines conditions et dans un bout de code en javascript, hop tu trouves un bout de regex au millieu du code Xpath.

Je reconnais que zt serait mieux avec Xpath, mais franchement si tu dit pas que c'est du html pour pas piquer les oreilles, les regex marchent tres bien.

Si tu veux des exemples, exodus a certaines sources avec ce systeme (DOM je crois).

**Comment by TmpName** [comment]
planet stre aming rajoute
vkstre amingfilm .biz ne propose pas que des films ?

**Comment by nmagre** [comment]
Il ne faut pas confondre le scrap avec le traitement de la donnée, selon ce que tu veux comme donnée oui en effet il faut la filtré avec une Regex ou autre, et même parfois tu as besoin de Regex dans XPath (XPath 2.0 le supporte avec `matches`).  

Pour les débutants ça dépend vraiment du site et de ce que tu veux récupérer, sur certain c'est plus facile d'utiliser XPath même si tu ne connais pas et que tu connais les Regex et même pour corriger, j'ai juste a copier/coller dans mon nav et voir ce qu'il va pas alors qu'avec les Regex ....
mais pour d'autres ça peut être vraiment plus compliqué.
Rien n’empêche de garder les deux systèmes en même temps.

Si vous voulez intégrer XPath, je peux aider. Il faut le rajouter via une lib ou un plugin xbmc et ensuite faire un `Helper` (classe utilitaire) pour simplifier certaine chose comme récupérer un attribut , ... enfin ça dépend de la lib utilisée. Même si je ne connais pas le python ça devrait le faire, je peux vous faire un patch git avec un exemple sur un site qui utilise XPath.

**Comment by LordVenom** [comment]
@TmpName la database? ou et pk?

@nmagre j'ai regarder mais c'est pas révolutionnaire et mal intégrer a Kodi qui a priori n'a pas l'intention de l'integrer.

Si tu connais un peux le html tu pourras sortir un regex correct aussi facillement que du xpath. Pour visualiser les resultats d'un regex https://regex101.com/ meilleur site du monde.

**Comment by LordVenom** [comment]
Tu peux pas supprimer sdisp comment tu vas gerer les films qui n'ont pas de categorie movie dans leur recherche?

**Comment by TmpName** [comment]
En fait j'avance petit a petit, vu que les fichiers de la beta se retrouvent souvent en MAJ auto.

Pour le moment je fonctionne avec les deux, "sDisp" en priorite et si "sType" est present je m'en sert.
En fait dans la configuration de Vstream j'ai appelle ca "Type de recherche a privilegier".
Si le site n'a pas plusieurs categorie > recherche classique.
Si l'user demande une categorie non gere par le site > recherche classique.
Si l'user demande une categorie speciale geree par le site > recherche speciale.

A deux endroits sDisp me pose probleme, et j'ai du mettre des patch pour convertir sDisp en sType ou vice-versa.
+ Lors de recherche, tu memorises la recherche dans un historique, et donc tu memorises "sDisp"
+ Lors de recherche via tmdb tu utilises oHandler.setDisp(sDisp)

Je crois aussi que pour les metas a un moment on utilises "Sdisp" pour partir soit en mode serie, soit en mode film, (pas sur, j'ai pas encore regarde).

Donc
+ soit on fait tout en double, en rajoutant dans la table sql, "type" et une fonction oHandler.setType(sDisp)
+ soit on garde les meme fonction et la meme table mais on aura stype = oHandler.getType(sDisp)

La seconde solution provoquera moins de probleme, mais faudra s'en souvenir, en fait mon but et de completement remplacer if "sDisp" = "search1" par if "sType" = "film"

**Comment by TmpName** [comment]
Bon alors effectivement impossible de se passer de "sDisp" car il faut memoriser non pas le type mais "la configuration de moteur choisie" par l'user.
Et a partir de sDisp on peut en deduire le type, donc pas besoin de se prendre la tete.

Je pense avoir fini les modifs, j'ai teste un peu tout, et ca marche sur pas mal de site.

Du coup j'ai re-active un popup sur la recherche visuelle qui demande quellle "configuration de moteurs" a utiliser.

**Comment by TmpName** [comment]
Y'en a qui ont teste ou tout le monde s'en fou ? ^^

**Comment by Kodigoal** [comment]
Je suis largué pour tester  xD 
Ca doit changer quoi ? 
Si je fais recherche visuelle pour un film , je choisis un film , popup rechercher par vstream et ca redemande film/série/anime ?

**Comment by nmagre** [comment]
Faut que je compile une version antérieur de xbmc (j'ai tout cassé le mien) et je teste ça ce soir ou demain.

**Comment by nmagre** [comment]
J'ai fais un petit test et ya au moins un problème avec ZT (c'est peut être pas du a cette modif).
J'ai bien les résultats filtrés mais quand on fait "next" , j'ai d'autre type et en plus "next" est a l'infinie (même si il retourne toujours la même chose)

**Comment by Kodigoal** [comment]
@nmagre ok,  merci pour l'explication.
je teste plus tard de mon côté.

**Comment by TmpName** [comment]
Heu, alors la, j'ai pas compris.
Je vais dans les options, je selectionne une recherche, je l'apelle "serie" ou je prend celle qui s'apelle deja comme ca.
Je selectionne comme type "serie", je met ZT dedans.

Je m'en sert pr rechercher "arrow" j'arrive sur ZT avec que des series (et que des arrows) mais y a pas de lien next ?

J'ai fait avec "ncis" la j'ai bien le lien "next" mais je bascule sur la version ZT classique mais sans prbs.

**Comment by nmagre** [comment]
@TmpName Au temps pour moi, j'ai lancé ma recherche ("matrix" avec type "film") sur ZT et c'est lui qui déconne (un bug dans la matrice ? ^^ ), il renvoie d'autre type et toujours la même page.

**Comment by TmpName** [comment]
Lol, ils auraient voulu le faire expres qu'ils auraient pas fait mieux ^^.

**Comment by Kodigoal** [comment]
@TmpName merci pour tes explications , plus qu'à faire me un bon petit moteur xD

**Comment by nmagre** [comment]
J'ai fais plusieurs tests et ça semble ok.

J'ai juste un problème mais qui concerne pas directement vstream, j'utilise la recherche directement dans mon skin avec `ActivateWindow(videos,plugin://plugin.video.vstream/?....)` et le soucis c'est que les variables comme par exemple le titre `$ESCINFO[Window.Property(Title)]` ne sont pas encodé (urlencode) du coup ça ne marche pas avec tous.

Y a-t-il une astuce pour passer le titre non encodé a vstream pour faire une recherche ? ou je suis obligé de faire un plugin pour encodé et ensuite qu'il appelle vstream ?

**Comment by TmpName** [comment]
Je pense que tu es bon pr te refaire un pluggin.

De memoire plus de 75% des fichiers sites ne vont pas marcher ne serait ca qu'a cause de l'espace a la place du %20. Et eux ne calculent rien, ils envoient direct le terme recherche dans la requete.

**Comment by nmagre** [comment]
ok, merci. Je vais chercher un moyen détourné pour le faire, je vois plusieurs solutions :

- Stocker une variable encodée accessible depuis le skin (je ne sais pas si c'est possible)
- Modifier le ou les sites
- Modifier vstream pour qu'il encode lui même (en lui ajoutant un paramètre par exemple)
- Faire un plugin qui encode et appel vstream
- ...

Bref ça devrait ce faire sans trop de problème je pense, c'est dommage qu'il n'y ai pas de fonction de ce type directement utilisable depuis un skin. Si c'est "intéressent" (et dans vstream) je mettrais le code ici.

**Comment by TmpName** [comment]
Apres je ne sais pas quel lien tu appelles via ton skin, mais si par exemple c'est dans le fichier cRechercheHandler() pour lancer une recherche globale, on peut y rajouter une fonction a la con qui traiterait ton titre avant de s'en servir, et qui ne servirait que a ca, ou un clone d'une fonction mais qui gererait le codage, on est pas a 10 lignes pres. Car si si tu dois modifier les fichiers sites, tu vas jamais finir.

Apres pas besoin d'un pluggin complet qui encode et appel vstream, un fichier perso dans Vstream devrait servir (mais qui sera supprime a chaque MAJ je crois)

**Comment by nmagre** [comment]
J'utilise cette url : `plugin://plugin.video.vstream/?site=cHome&amp;function=searchMovie&amp;title=$ESCINFO[Window.Property(Title)]&amp;disp=search1&amp;searchtext=$ESCINFO[Window.Property(Title)]&amp;readdb=False&amp;sFav=searchMovie&amp;siteUrl=http%3A%2F%2Fvenom&amp;type=film`.

Peut être qu'il suffit juste de rajouter un `rawsearchtext` , si il existe l'encodé et le mettre dans `searchtext`, supprimer `rawsearchtext`.

**Comment by TmpName** [comment]
Dans searchmovie() tu peux le rajouter, suis sur a 100% que ca va rien changer pr les autres, et meme ca va leur servir, pour le mettre dans parseurl() a moins d'y voir une utilite pr tes skins suis moins chaud et la je t'avous, en ce moment, perso j'ai pas trop le temps de me pencher sur l'effet que cela pourrait avoir.

**Comment by nmagre** [comment]
Perso j'en ai juste besoin dans `searchmovie` et je pense pas que ce soit utile de l'avoir ailleurs (sauf si ya d'autre fonction de recherche).

Le soucis c'est que ça fait un peu bricolage et c'est pas explicite de le mettre là, je pense que le mettre le plus "haut" possible (donc dans `default.py`) c'est le mieux, ça permet de savoir que ça existe (pour les autres personnes avec le même problème que moi, ...), et si un jour vous avez besoin de couper en morceaux vstream avec un script + un plugin, ... il est directement a porté de vue et pas "caché". Ça permet aussi d'éviter qu'il soit supprimé dans les sources, perso je tombe la dessus dans  `searchmovie` et je vois que c'est utilisé nul part, je le dégage direct.

**Comment by TmpName** [comment]
Le truc c'est que dans parseurl, je ne suis pas sur que ce soit utile (surtout que lui ne se sert ni de sTitle ni de sSearch, donc le gros patch que tu ferais au debut, aurait, pour moi, plus l'occasion de degager que si il se trouve dans la fonction searchmovie() ou la, meme sans commentaire son utilite est plus facile a comprendre)

En fait en cas de recherche globale il est encode de suite apres la saisie sur le clavier, pour la recherche visuelle pareil, il est encode juste avant et apres ca passe par cRechercheHandler(). La recherche encode les titres, pas le reste. L'encodage se fait "naturellement", le prb vient plus du skin que de l'addon.
Ce que je veux dire c'est que entre le moment ou tu lis un titre sur une page web, et que tu t'en sert sur la page suivante, il n'a aucun appel a la fonction urllib.quote_plus, meme mieux les espaces sont code avec des + et non pas des %20.

Donc a moins de relire tout le code car je dis ca de memoire (et de me faire peur en passant car Vstream est justement tres bricole), tant que je ne suis pas sur que cela puisse servir un jour, je ne toucherais pas.
