### ISSUE TITLE
Falsh X - Fichier introuvable

### ISSUE THREAD

**Issue by Turk182es** [Kodi-vStream/venom-xbmc-addons#586]
Salut,

Depuis l’actualisation 0.45 j'ai que des fichier introuvable sur le serveur FlashX. Je me doute bien que ce n'est pas un soucis de l'addon mais il y a t'il une solution ou une manip à faire ?

C'est embêtant car les serie 80's de TVStreaming.ch sont souvent sur FlashX

En tout cas merci pour votre aide.

**Comment by johngf** [comment]
sur quelle serie ou film tu as fichier introuvable ?

**Comment by Turk182es** [comment]
Salut, sur toute les series essayées sur StreamingTV.CH par exemple : L'homme qui valait 3 milliards, Dallas etc....

**Comment by johngf** [comment]
je vais essayé après c'est possible que les liens soit hs

**Comment by TmpName** [comment]
Effectivement, le premier lancement deconne toujours a cause d'un lien special, et a partir du second tout est ok.
J'ai fais une modif pour eviter ca, mais si tu relances ca fonctionnera.

**Comment by johngf** [comment]
http://play.cdn12.fx

**Comment by TmpName** [comment]
C'est bon ca, chez moi c'est le fichier du film, enfin c'est celui que ouvre kodi.

**Comment by johngf** [comment]
enfin si mais faut toujour relancer plusieurs fois

**Comment by TmpName** [comment]
Avec ma modif, ca marche pas ?
J'ai ca dans les logs
>7:26:55 T:448  NOTICE: Test sur : ht tp://flas..qv5o77
17:26:55 T:448  NOTICE: Test sur : ht tp://w ww.flash..5o77
17:26:55 T:448  NOTICE: Test sur : ht tp://ww w.flas..77.html
17:26:56 T:448  NOTICE: page bloquee
17:26:56 T:448  NOTICE: Test sur : h ttp://w ww.flashxx.tv/reloadit.php?w=e&c=1454o77
17:26:57 T:448  NOTICE: Test sur : htt p://ww w.flashxx.tv/playvid-o4vogjqv5o77.html
17:26:57 T:448  NOTICE: lien code
17:26:58 T:1856  NOTICE: DVDPlayer: Opening: htt p://play.cdn14.fx.fast

La page qui fout la merde c'est celle avec 'reloadit'

**Comment by johngf** [comment]
oui on est pas sur que c'est h ttp://w ww.flashxx.tv qui manque

**Comment by TmpName** [comment]
Ha ?
Ca j'ai pas ce bug chez moi.
Je testes sur l homme qui valait 3 millard et tout tourne a chaque fois.

**Comment by johngf** [comment]
moi je suis sur dallas saison 1

**Comment by TmpName** [comment]
Dallas S01E01 aucun prb, ta connexion ? Tu as un message explicatif apres le message d'erreur ?

**Comment by johngf** [comment]
ça doit étre chez moi alors je sais pas
17:52:28 T:3024676800  NOTICE: DVDPlayer: Opening: h ttp://play.cdn14.fx.fastcontentdelivery.com/luq4lreng3ixexzw6vc3higwqtppmn4j4teclyyavgqyudrmbdju5pfhwqga/normal.mp4
17:52:28 T:3024676800 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:52:28 T:2756459328  NOTICE: Creating InputStream
17:52:29 T:2756459328  NOTICE: Creating Demuxer
17:52:59 T:2756459328   ERROR: Open - Error, could not open file ht tp://play.cdn14.fx.fastcontentdelivery.com/luq4lreng3ixexzw6vc3higwqtppmn4j4teclyyavgqyudrmbdju5pfhwqga/normal.mp4
17:52:59 T:2756459328   ERROR: OpenDemuxStream - Error creating demuxer
17:52:59 T:2756459328  NOTICE: CDVDPlayer::OnExit()

**Comment by TmpName** [comment]
Tu as essaye d'ouvrir le fichier dans un navigateur ? (le mp4)

**Comment by johngf** [comment]
le probleme vient de chez moi ta modif est ok ça confirme mes doutes j'ai un soucis de connection

**Comment by Turk182es** [comment]
Y'a une modif à faire ? Parce que je viens d'essayer et c'est toujours pareil : Fichier introuvable 
J'essaye plusieurs fois le même fichier mais sans aucun résultat :-(

**Comment by johngf** [comment]
@Tmpname a fait une mis a jour le fichier il faut attendre la mise a jour ou recuperer le fichier dans le liens et faire copier coller dans flashx.py
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/dfe0e95fc5427973303dba0ba4b0b1ffcc9170d3/plugin.video.vstream/resources/hosters/flashx.py

**Comment by Turk182es** [comment]
A d'accord ! Désolé pour le dérangement alors!

Super merci pour la mise à jour !
