### ISSUE TITLE
vStream charge mais ne lance pas la chaine

### ISSUE THREAD

**Issue by AnthonyRio** [Kodi-vStream/venom-xbmc-addons#589]
Bonjour,

J'ai un petit soucis, quand je choisi une chaîne sur vstream, elle charge (logo) mais elle ne se lance pas... J'ai bien installer f4mtester (enfin il la fait tout seul), ça a fonctionné quelques jours mais depuis hier soir rien ne se passe...

vstream est à jour et f4mtester aussi

Pouvez vous m'aider ? Je suis en manque de chaîne sportive haha

merci d'avance :-)

**Comment by TmpName** [comment]
Ha ca a marche chez toi ?
Je croyais que c'etait en rade depuis plusieurs mois ?
Tu as teste quoi comme chaine ?

**Comment by AnthonyRio** [comment]
OUI une soirée lol !

Toutes les chaînes fonctionnais !

**Comment by TmpName** [comment]
Tu passes par "framapad" ou "tv du web" ?

**Comment by AnthonyRio** [comment]
Framapad

**Comment by johngf** [comment]
certaines chaînes fonctionnent en bas de la liste

**Comment by TmpName** [comment]
Alors c'est normal, framapad fonctionne avec des liens non officiels, si quelqu'un le met a jour, ca va marcher quelques jours mais les liens se font fermer tres vite.
