### ISSUE TITLE
Netu-Fichier introuvable

### ISSUE THREAD

**Issue by s1994** [Kodi-vStream/venom-xbmc-addons#590]
Bonjour.

Depuis 2 jours je n'ai que des fichier introuvable sur le media Netu.
y a t'il une solution? 

Merci d'avance pour votre aide.

**Comment by TmpName** [comment]
Pareil mais les videos ont l'air out aussi sur navigateur.

**Comment by s1994** [comment]
Bonjour. Si ils fonctionnent sur le web. http://filmstreamvk.com/serie/south-park-saison-17/Episode/07-VF

**Comment by TmpName** [comment]
Exact, confirme, j' y jette un eouil today.

**Comment by s1994** [comment]
Merci

**Comment by TmpName** [comment]
Fichier mit a jour, merci du signalement.

**Comment by s1994** [comment]
Merci beaucoup. Une petite question, comment j peut avoir la mise à jour? J attend la mise à jour qui se fait tout les 3 jour où y a t'il un otre moyen de l'avoir ?

**Comment by TmpName** [comment]
Tu peux editer ton fichier en copiant/collant le bon contenu > https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/netu.py

Tricher en avancant la date de ton systeme de 3 jours avant de lancer Vstream.

La mise a jour est manuelle, tu vas avoir une nouvelle option dans la page d'acceuil de Vstream, page home.

**Comment by s1994** [comment]
Super merci
