### ISSUE TITLE
Sauvegarder l'id tmdb

### ISSUE THREAD

**Issue by nmagre** [Kodi-vStream/venom-xbmc-addons#594]
Dans certain cas l'id tmdb et peut être l'id imdb sont fournit via une API, ...
Exemple : "Recherche visuelle"  -> "Acteurs populaires"

Si les métadonnées sont activé parfois le mauvais film est récupéré (même titre mais pas la même année par exemple). `oOutputParameterHandler` pourrait être utilisé pour passer les données (tmdb id, imdb id, et l'année) puis être stocker dans `guiElement` pour être utilisé dans `getMetadonne` (avec `metahandler`)

Ex :

Fichier `themoviedb_org.py`  
  fonction `showActors`

``` python
for e in i['known_for']:
    ...
    oOutputParameterHandler.addParameter('sTmdbId', sId)
    # TODO add year ? (e['release_date'] = 2003-11-05)

    oGui.addMovieDBid(SITE_IDENTIFIER, 'showHosters', sTitle, '', sThumbnail, sFanart, oOutputParameterHandler)
```

  fonction `showFilmActor`

``` python
for i in result['cast']:
    ...
    oOutputParameterHandler.addParameter('sTmdbId', i['id'])

    oGui.addMovieDB(SITE_IDENTIFIER, 'showHosters', sTitle, '', sThumbnail, '', oOutputParameterHandler)
```

Fichier `gui.py` fonction `addMovieDB`

``` python
     ...
    oGuiElement.setCat(7)

    params = {
        "sMovieTitle": oGuiElement.setFileName,
        "sTmdbId": oGuiElement.setTmdbId,
        "sImbdId": oGuiElement.setImdbId,
        "sYear": oGuiElement.setYear,
    }

    for sParam, callback in params.iteritems():
        value = oOutputParameterHandler.getValue(sParam)
        if value:
            callback(value)
```

Fichier `guiElement.py` fonction `getMetadonne`

``` python
if self.getMeta() == 1:
    try:
        from metahandler import metahandlers
        grab = metahandlers.MetaData(preparezip=False,  tmdb_api_key='XXXXXXXXXXX')
        meta = grab.get_meta('movie', self.__sFileName, self.__sImdbId, self.__sTmdbId, self.__sYear)
```

Note: Peut être que je me trompe mais le cache (si il y en a un) ne semble pas vraiment marcher sur "Acteurs populaires"
Note2: ~~Il y a un problème de charset ou de conversion, certain film avec des caractères Japonais/Chinois/...  apparaisse avec un titre vide~~ J'ai vérifié et c'est un bug dans l'API de tmdb il renvoie des caractères dans un format autre que utf-8

**Comment by TmpName** [comment]
Alors la, je decouvre ^^.
Je croyais que chaque film avait son propre id (TMBD ou IMDB) donc normallement a partir de celui ci, il y a moyen de faire une requete a la database en ligne sans se tromper (je vois meme pas pkoi on aurait besoin du titre).

C'est quoi le cache sur "Acteurs populaire" ?

**Comment by nmagre** [comment]
Il faut le fournir pour qu'il face la requêtes et actuellement ce n'est pas le cas. Vstream utilise `metahandlers` (un autre addon) pour récupérer les infos (si je dis pas de bêtise) et actuellement il a juste comme argument le titre du film. C'est justement ce que je propose ici de rajouter les id et l'année, bien-sur dans mon exemple je l'ai mis juste sur `addMovieDB` mais il faudrait que ce soit de façon général (`addMovie`, `addTV` , ...) et aussi pour les série TV donc avec l'id tvdb

> C'est quoi le cache sur "Acteurs populaire" ?

Pour le cache je parle de celui de `metahandler` donc c'est pas lié directement a "Acteurs populaire" mais partout ou est utilisé `metahandler`.
J'ai l'impression qu'il va récupérer les infos a chaque fois qu'on y retourne. C'est une hypothèse je me trompe peut être.

**Comment by TmpName** [comment]
Ok, alors j'ai fais quelques tests et effectivement, j'ai pu voir : 
1 - activer les meta données.
2 - aller dans la recherche visuelle
3 - choisir au pif, eg "film en salle" ou comme l'exemple a @nmagre "acteurs populaires"

A ce moment Vstream interroge les base en ligne, recupere le bon id, mais affiche les infos metadata comme pour le reste de Vstream c'est a dire a partir du titre, donc on peut avoir des mauvais resultats alors qu'on a l'id unique du bon film.

Pas sur que l'annee soit indispensable (de memoire l'id est unique), pas sur que l'id imdb soit utile, car ses resultats sont en anglais, mais pour l'id de tmdb, c'est effectivement vraiment dommage de ne pas s'en servir.

**Comment by nmagre** [comment]
L'année est utile que si il n'y a pas d'id et encore ça peut être problématique dans certain cas, je ne sais pas comment il gère ça dans `methandler`.
Certain films/séries sortent des années après en france, et souvent il y a un an de différence a cause de la date de sortie en dvd/blu-ray qui est plus tard en france, ou année de production/année de sortie.
C'est mieux de la rajouter au cas ou même après ce que je viens de dire, peut être qu'un jour il y aura un addon avec des scrapers plus performants sur le multi-langue/source que ce qui existe. 

Les id tmdb et imdb sont uniques et la plupart des API fonctionnent avec l'id imdb, c'est le cas pour tmdb (on peut utiliser les deux) et il sert de base dans beaucoup de scraper (en générale on a des fonctions de `lookup` pour "transformer" l'id imdb en tmdb/...). Même si imdb n'est plus en Français (oui il l'a été), il y a des infos qui ne sont pas liées à la langue ex: la durée du film, les acteurs, la note, ...

**Comment by TmpName** [comment]
Ok donc on part sur annee et l'id imdb (vu qu'il sert pr les deux).
Par contre si quelqu'un veut s y tenter, moi ce sera pas avant ce WE.

**Comment by nmagre** [comment]
Mon exemple fonctionne (je l'ai testé), mais pour faire ça de façon "générique" il faut "refactoring" les fonctions "add..." pour y ajouté le : 

```python

    params = {
        "sMovieTitle": oGuiElement.setFileName,
        "sTmdbId": oGuiElement.setTmdbId,
        "sImbdId": oGuiElement.setImdbId,
        "sYear": oGuiElement.setYear,
    }

    for sParam, callback in params.iteritems():
        value = oOutputParameterHandler.getValue(sParam)
        if value:
            callback(value)
```

Et c'est pas si évidant que ça a faire, même si la plupart ont les même arguments ou presque.  
On peut aussi rajouter simplement une fonction qui fait juste ça et l'appeler dans les "add..." ou le rajouter dans `addFolder` directement.

**Comment by TmpName** [comment]
Ben moi j'avais prevu un truc tout con, juste rajouter 
>oOutputParameterHandler.addParameter('sTmdbId', XXX['id'])

Dans les fonction showmovies, showactor, ect ...

Puis dans la fonction addMovieDB()
>oGuiElement.setTmdbid(id)


Et m'en reservir dans la fonction getMetadonne(), si present je m'en sert, si non present on continu comme d'hab.

**Comment by nmagre** [comment]
> Ben moi j'avais prevu un truc tout con, juste rajouter
>
>  >  oOutputParameterHandler.addParameter('sTmdbId', XXX['id'])

Par exemple sur ZT (et sûrement plein d'autre) tu peux recup que la date, du coup avec ma modif dans `addFolder`, tu as pas besoin de t'en soucier, tu fais `oOutputParameterHandler.addParameter('sYear', year)` et idem pour le reste, tu as l'info tu la rajoute.

L'avantage c'est que c'est compatible sur tous les types de "dossier" et ça permet aussi de rajouter n'importe quoi dans le futur facilement qui sera lui aussi disponible peut importe la fonction "add..." appelé et même avec les nouvelles fonction ajoutées plus tard (si elles utilisent `addFolder`).

**Comment by TmpName** [comment]
Ha ok, je pensais pas que tu voyais si loin, moi c'etait juste pour corriger la recherche visuelle, je pensais pas que tu voulais aussi rajouter les dates pour les fichiers sites.

Mais du coup tu vas avoir plus que addMovieDB() a bidouiller, addTVDB(), addMovie() , ect ... ?

Ou alors c'est addFolder() que tu vas passer au bistouri ? J'ai vu que tu parlais de ca aussi (dsl suis un peu speed en ce moment, je lis en travers, 1 post sur 2).

**Comment by nmagre** [comment]
T'inquiète moi aussi je suis sur un gros refactoring pas facile donc je suis peut être pas très clair dans ce que je dis.

C'est bien `addFolder()` dont je parle, les autres `add...()` je n'y touche pas sauf pour enlever ce qui sera en double.

**Comment by TmpName** [comment]
Bon pr info j'ai commence, donc pas la peine d'en faire autant, la j'ai plus la tv pr tester.
Je passe le code demain.

**Comment by nmagre** [comment]
Ok. Enfaîte je parlais d'un de mes soft ou je suis a fond dessus en ce moment.
Pour la modif là ça ce fait en 5minutes, ya presque pas de code a modifier.

**Comment by TmpName** [comment]
Yep, ca a ete rapide, mais ma copine est malade et reste devant la TV, donc j'ai modfie le code mais je ne peux pas le tester.
En fait j'ai juste modifie addfolder(), j'ai meme pas enleve les doublons pour eviter les prbs car il peut y avoir 2 fois les miniature par exemple, une fois dans les parametres et une autre dans la ligne de commande, et ils peuvent etre differents si besoin, donc pour le moment j'ai fais au minimum.
