### ISSUE TITLE
Urlresolver erreur d'extension 

### ISSUE THREAD

**Issue by Stefle33** [Kodi-vStream/venom-xbmc-addons#595]
Bonsoir, 
Quand je veux rentrer mes identifiants dans urlresolver, c'est impossible et un message apparaît "erreur d'extension". 
Avez vous une solution ? 
Merci

**Comment by johngf** [comment]
si tu as fait une nouvelle install avec kodi 16 urlresolver n'est plus dans les dépot kodi il faut l'installer manuellement
https://offshoregit.com/iCanuck/iCanuck-Repo/raw/master/script.module.urlresolver/

**Comment by Stefle33** [comment]
C'était bien cela merci beaucoup :)
