### ISSUE TITLE
Nettoyage

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#596]
Ajouter à Runscript.py
1: la possibilité de supprimer les fichiers .fi qui polluent le dossier Temp
2: la possibilité de supprimer toutes les thumbnails de Kodi qui a la longue prennent beaucoup de place 
nettoyage du fichier Textures db inclus pour éviter les erreurs (dans les logs)
ce qui donne ça:
https://raw.githubusercontent.com/johngf/venom-xbmc-addons/ef4bf88ca1660077b1798e2078c21eacbf42e3d4/screenshot075.png

Testé sur linux ok
`

        elif (env == 'fi'):
            dialog = xbmcgui.Dialog()
            if dialog.yesno('vStream', 'Êtes-vous sûr ?','','','Non', 'Oui'):
                xbmc.executebuiltin("XBMC.Notification(Clear .fi Files ,Successful,2000,"")")
                path = xbmc.translatePath('special://temp/')
                filenames = next(os.walk(path))[2]
                for i in filenames:
                    if ".fi" in i:
                        os.remove(os.path.join(path, i))
            return

        elif (env == 'thumb'):
            dialog = xbmcgui.Dialog()
            if dialog.yesno('vStream', 'Êtes-vous sûr ? Ceci effacera toutes les thumbnails ','','','Non', 'Oui'):
                xbmc.executebuiltin("XBMC.Notification(Clear Thumbnails ,Successful,2000,"")")
                path = xbmc.translatePath('special://userdata/Thumbnails/')
                path2 = xbmc.translatePath('special://userdata/Database/')
                for i in os.listdir(path):
                    folders = os.path.join(path, i)
                    if os.path.isdir(folders):
                        p = next(os.walk(folders))[2]
                        for x in p:
                            os.remove(os.path.join(folders, x))
                       
                filenames = next(os.walk(path2))[2]
                for x in filenames:
                    if "exture" in x:
                        con = sqlite3.connect(os.path.join(path2, x))
                        cursor = con.cursor()
                        cursor.execute("DELETE FROM texture")
                        con.commit()
                        cursor.close()
                        con.close()
            return

`
code complet: https://raw.githubusercontent.com/johngf/venom-xbmc-addons/Beta/plugin.video.vstream/resources/lib/runscript.py

il faut ajouté 2 label au fichier settings.xml fi et thumb

**Comment by TmpName** [comment]
Moi je vote pour l'integrer direct.
Ca me servira pas car je n'ai pas de probleme avec ces fichiers, mais c'est utile et ca gene pas le fct de Vstream.

**Comment by johngf** [comment]
bah en faite les fichiers .fi ne crée pas de problème (c'etait ma connection tous est revenu a la normal) mais s'accumule sans limite ce matin 75 fichier .fi dans temp

**Comment by TmpName** [comment]
Valide le sur la version beta, je ne vois pas pkoi ca generait, ca peut apporter un plus et aucun moins.

**Comment by johngf** [comment]
Je dois verifié demain si pour ceux qui utilise metahandler si ça provoque pas d'érreur dans les logs

**Comment by TmpName** [comment]
J'ai pas vu le rapport avec metahandllers, si tu parles des thumnails, moi je les ai dans le repertoire de metahandlers justement. Ceux de special://userdata/Thumbnails/ me servent pour tout les addons.

**Comment by johngf** [comment]
C'est ce que je voulais voir justement

**Comment by johngf** [comment]
bon moi (sur archlinux) si j'active metahandlers les thumbnails vont dans userdata/Thumbnails/  avec les autres
les repertoires de metahandlers sont créée dans userdata/addon_data/script.module.metahandler/ mais reste vide , seul la db sqlite est utilisé et aucun bug recensé je crois qu'il mais a jour la db quasi
en temps réel et remplace les vieilles entrée

**Comment by TmpName** [comment]
En fait je te dis ca, car metahandler a deja provoque un bug sur Vstream, y a une issue dessus. En fait il y avait un ralentissement lors de l'affichage des pages, et certaines icones manquaient carrement, pour le resoudre il fallait supprimer tout le repertoire metahandler (et pas celui du pluggin), au lancement suivant le repertoire etait recrée mais sans le bug.

**Comment by Kodigoal** [comment]
Ca sera rajouté à la maj  ou tu fais d'autres tests avant de l'inclure?

**Comment by TmpName** [comment]
Pour moi pas besoin de test, si tu touches pas, tu vois pas la differences, si tu touches, tu sais ce que tu fais.
Y a que du bon a prendre pour moi.

**Comment by johngf** [comment]
je l'ai ajouté
