### ISSUE TITLE
Addic7ed Sous titres

### ISSUE THREAD

**Issue by alexgasio** [Kodi-vStream/venom-xbmc-addons#597]
Bonjour à tous, 

J'ai installé l'addon addic7ed pour Kodi mais lorsque je lance une video et que je cherche des sous titres, cela ne fonctionne pas. Et j'ai un message "Manual search not enabled currently".

Quelqu'un sait pourquoi? 

Merci d'avance,

**Comment by johngf** [comment]
tu recherche des sous titres a partir des videos en streaming via vstream ? si c'est le cas
apparament la recherche de sous titre fonctionne que si tu as la video sur ton dique dur, elle ne fonctionne pas avec les video en streaming
https://github.com/Amelandbor/service.subtitles.addic7ed/issues/6 en anglais

**Comment by LordVenom** [comment]
Voir : http://redeneobux.com/fr/tutorial-como-adicionar-inserir-colocar-legendas-nos-filmes-series-opensubtitles-xbmc-kodi/

**Comment by TmpName** [comment]
Petite question perso, tu as essaye de lancer un film sous Vstream sans sous-titre ?
Si oui tu pourrais me donner le site et l 'hebergeur stp.

**Comment by alexgasio** [comment]
@johngf ahhhhh tout s'explique merci !
@LordVenom Merci pour le tuto, mais j'avais déjà opensubtitles mais un peu galère pour retrouver les sous titres dedans !

@TmpName je passe par ZT et Uptobox

**Comment by TmpName** [comment]
Pour info, si tu t'y connais un peu, car les bidouilles risquent de faire planter ta version de Vstream
Kodigoal est en train de rajouter des sous titre automatique, justement pour cet hebergeur.
cf https://github.com/Kodi-vStream/venom-xbmc-addons/issues/569

**Comment by alexgasio** [comment]
@TmpName merci ! J'ai suivi aussi le thread :-)
