### ISSUE TITLE
Any changes in Hosters (netu or dailymotion)

### ISSUE THREAD

**Issue by emailradhesh** [Kodi-vStream/venom-xbmc-addons#598]
Hi,

1. [TopBestSite](http://w ww.topbestsite.com/) has links of videos which are hosted in hqq.tv website.
1. I extract links from TopBestSite and host it in GitHub. For example [BiggBoss](ht tps://emailradhesh.github.io/topbestsite/bigg-boss-kannada-season-4-videos.html)
1. I'd written a working resource/sites/[topbestsite_com.py](https://raw.githubusercontent.com/emailradhesh/topbestsite/master/scripts/topbestsite_com.py) using this addon.
1. With latest update of vstream the netu is not playing and shows below error
`20:20:29 T:140615904618240 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=bigg-boss-kannada-season-4-17102016-episode-9_Alternate+%5BCOLOR+skyblue%5Dnetu%5B%2FCOLOR%5D&sHosterIdentifier=netu&sTitle=bigg-boss-kannada-season-4-17102016-episode-9_Alternate+%5BCOLOR+skyblue%5Dnetu%5B%2FCOLOR%5D&siteUrl=http%3A%2F%2Fhqq.tv%2Fplayer%2Fembed_player.php%3Fvid%3D235254266235224273235259261208277261194271217261258%26autoplay%3Dno&sFav=play&sMediaUrl=http%3A%2F%2Fhqq.tv%2Fplayer%2Fembed_player.php%3Fvid%3D235254266235224273235259261208277261194271217261258%26autoplay%3Dno&sCat=4&sId=cHosterGui&sFileName=bigg-boss-kannada-season-4-videos
20:20:29 T:140615904618240   ERROR: InputStream: Error opening, plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=bigg-boss-kannada-season-4-17102016-episode-9_Alternate+%5BCOLOR+skyblue%5Dnetu%5B%2FCOLOR%5D&sHosterIdentifier=netu&sTitle=bigg-boss-kannada-season-4-17102016-episode-9_Alternate+%5BCOLOR+skyblue%5Dnetu%5B%2FCOLOR%5D&siteUrl=http%3A%2F%2Fhqq.tv%2Fplayer%2Fembed_player.php%3Fvid%3D235254266235224273235259261208277261194271217261258%26autoplay%3Dno&sFav=play&sMediaUrl=http%3A%2F%2Fhqq.tv%2Fplayer%2Fembed_player.php%3Fvid%3D235254266235224273235259261208277261194271217261258%26autoplay%3Dno&sCat=4&sId=cHosterGui&sFileName=bigg-boss-kannada-season-4-videos`

It will be of great help if you can let me know if there is any change in hoster. I'll make respective change.

I observe Dailymotion is showing only quality LIVE and also shows same error. 

Thanks for this great add-on.

[kodi.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/539226/kodi.txt)

**Comment by johngf** [comment]
they have been updated here copy paste in your files
dailymotion:
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/6b947eda2ba4cc1bb1035f90d88b1677c1bd006e/plugin.video.vstream/resources/hosters/dailymotion.py

netu : 
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/6b947eda2ba4cc1bb1035f90d88b1677c1bd006e/plugin.video.vstream/resources/hosters/netu.py

**Comment by emailradhesh** [comment]
Thanks @johngf for the update. Will take a look at it and wait.
