### ISSUE TITLE
Zone téléchargement - marque page qui ne fonctionne plus au bout d'un certain temps

### ISSUE THREAD

**Issue by disizleboss93** [Kodi-vStream/venom-xbmc-addons#603]
Bonjour,

Lorsque j'ajoute des marques pages pour des series ou animes, je peux y accéder dans la foulée.
Par contre, au bout d'un certain temps, certains deviennent obsolètes. Lorsque je tente d'y accéder, rien ne se passe. Je dois donc supprimer les marques pages qui ne fonctionnent plus pour les recréer. Malgré cela, certains redeviennent obsolètes au bout d'un certain temps.

Merci d'avance

**Comment by TmpName** [comment]
Oui c'est normal.
Tu ne peux pas rajouter les liens obtenus par la recherche en favoris.
Fais une recherche sur ZT sur un film et en passant le pointeur dessus regarde le lien.
>ht tp://w ww.ZT.com/7f92de3b49478587780b729995f395de6eae3a8ea61

Et ce lien n'est valide qu'un temps limite.

Donc il te faut le selectionner, il sera decode, et mettre en favoris a partir de la seconde page.

**Comment by disizleboss93** [comment]
En utilisant la méthode décrite, ca fonctionne tres bien. Merci
