### ISSUE TITLE
Dadadebrid

### ISSUE THREAD

**Issue by noipo** [Kodi-vStream/venom-xbmc-addons#604]
J'ai réussi a trouver un .py du debrideur dadadebrid et je ne sais pas comment l'inclure dans vstream.
Voici le fichier .py : 
# -_\- coding: utf-8 -_-

import urllib,urllib2,random,re
from cookielib import CookieJar
from base64 import b64decode

useragent = "'Mozilla/5.0 (X11; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0'"
cj = CookieJar()
opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))

def adfly(url):
req = urllib2.Request(url)
req.add_header('User-Agent', useragent)
html = opener.open(req).read()
ysmm = re.findall(r"var ysmm =._\;?", html)
if len(ysmm) > 0:
ysmm = re.sub(r'var ysmm \= \'|\'\;', '', ysmm[0])
left = ''
right = ''
for c in [ysmm[i:i+2] for i in range(0, len(ysmm), 2)]:
left += c[0]
right = c[1] + right
decoded_url = b64decode(left.encode() + right.encode())[2:].decode()
if re.search(r'go.php\?u\=', decoded_url):
decoded_url = b64decode(re.sub(r'(._?)u=', '', decoded_url)).decode()
return decoded_url
else:
return url

def dadadebrid(url):
s = ''
for i in range(15):
s = s + str(random.randint(0,9))
data = urllib.urlencode({'rand': "0."+s, 'urllist': url, 'captcha': 'none'})
req = urllib2.Request("htt ps://panel.dadadebrid.fr/index.php?rand=0."+s)
req.add_header('User-Agent', useragent)
req.add_header('Referer', "htt ps://panel.dadadebrid.fr")
req.add_header('host', "panel.dadadebrid.fr")
response = opener.open(req,data).read()
match = re.search("href='(._?)'",response).group(1)
decoded_url = adfly(match)
if "dadadebrid" in decoded_url: 
req = urllib2.Request(decoded_url)
req.add_header('User-Agent', useragent)
req.add_header('Referer', match)
response = opener.open(req,data).read()
match = re.search('download" href="(._?)"',response).group(1)
return match
else:
return decoded_url
# === Exemples ===
# print dadadebrid("ht tp://uptobox.com/v3kl6vpjk9cq")
# print dadadebrid("htt ps://1fichier.com/?98qt2k34ag")
# print dadadebrid("htt p://uplea.com/dl/74E0D0DF3AAE7BF")

**Comment by TmpName** [comment]
Le plus facile pour tester, tu prend un hebergeur que tu aimes bien
eg 1 fichier (onefichier.py)

Tu copis tout ton fichier dedans, puis tu refais la fonction getMediaLink(self):

```
def getMediaLink(self):
    url = 'https://1fichier.com/?' + self.__getIdFromUrl(self.__sUrl)
    return True, dadadebrid(url)
```

Bon y a aucune gestion des erreurs mais ca devrait marcher pr des tests.

Apres je sais pas si il est assez fiable pour le laisser en fixe (meme si il ne gere que 4/5 site)

**Comment by noipo** [comment]
ou est-ce que je dois le mettre le get medi link ?
A la fin du py ?

**Comment by TmpName** [comment]
Getmedialink() existe deja, elle est a modifier

**Comment by noipo** [comment]
Comme ça  ? : 
from resources.lib.handler.requestHandler import cRequestHandler
from resources.lib.parser import cParser
from resources.lib.config import cConfig
from resources.hosters.hoster import iHoster
from resources.lib.gui.gui import cGui

from resources.lib.handler.premiumHandler import cPremiumHandler

import urllib,urllib2
import xbmc

UA = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0'

class cHoster(iHoster):

    def __init__(self):
        self.__sDisplayName = '1Fichier'
        self.__sFileName = self.__sDisplayName
        self.__sHD = ''

    def getDisplayName(self):
        return  self.__sDisplayName

    def setDisplayName(self, sDisplayName):
        self.__sDisplayName = sDisplayName + ' [COLOR violet]'+self.__sDisplayName+'[/COLOR]'

    def setFileName(self, sFileName):
        self.__sFileName = sFileName

    def getFileName(self):
        return self.__sFileName

    def getPluginIdentifier(self):
        return 'onefichier'

    def setHD(self, sHD):
        self.__sHD = ''

    def getHD(self):
        return self.__sHD

    def isDownloadable(self):
        return True

    def isJDownloaderable(self):
        return True
        
    def __getIdFromUrl(self, sUrl):
        #http://kzu0y3.1fichier.com/
        #https://1fichier.com/?s6gdceia9y
        id = sUrl.replace('https://','')
        id = id.replace('http://','')
        id = id.replace('1fichier.com/?','')
        id = id.replace('.1fichier.com','')
        id = id.replace('/','')
        
        return id

    def setUrl(self, sUrl):
        self.__sUrl = str(sUrl)

    def checkUrl(self, sUrl):
        return True

    def __getUrl(self, media_id):
        return
        
    def getMediaLink(self):
        
        self.oPremiumHandler = cPremiumHandler(self.getPluginIdentifier())
        print self.oPremiumHandler.isPremiumModeAvailable()
        
        import sys
        if ('site=cDownload&function' not in sys.argv[2]) and not (self.oPremiumHandler.isPremiumModeAvailable()):
            oDialog = cConfig().createDialogOK('ATTENTION, Pas de streaming sans premium\nPour voir le film passer par l\'option "DL et Visualiser" du menu contextuel.')
            return False,False

        cGui().showInfo('Resolve', self.__sDisplayName, 5)
        
        if (self.oPremiumHandler.isPremiumModeAvailable()):
            return self.__getMediaLinkByPremiumUser()

        return self.__getMediaLinkForGuest()

        
    def __getMediaLinkByPremiumUser(self):
        
        if not self.oPremiumHandler.Authentificate():
            return False, False

        url = 'https://1fichier.com/?' + self.__getIdFromUrl(self.__sUrl)
        
        #Mode = ''
        #Mode = {'dl_no_ssl' : 'on' , 'dlinline' : 'on'}
        #Mode = {'dl_no_ssl' : 'on' }
        #postdata = urllib.urlencode( Mode )
        
        #Pas de page html mais lien direct
        #sHtmlContent = self.oPremiumHandler.GetHtml(url,postdata)
        #fh = open('c:\\test.txt', "w")
        #fh.write(sHtmlContent)
        #fh.close()        
        
        #mode inline
        #url = url + '&inline'
        
        api_call = url + '|' + self.oPremiumHandler.AddCookies()
        
        #print api_call
        
        if (api_call):
            return True, api_call
            
        return False, False
        
    def __getMediaLinkForGuest(self):

        url = 'https://1fichier.com/?' + self.__getIdFromUrl(self.__sUrl)
        
        headers = {'User-Agent': UA ,
                   'Host' : '1fichier.com',
                   'Referer' : self.__sUrl ,
                   'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                   'Accept-Language' : 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3'
                   #'Content-Type': 'application/x-www-form-urlencoded'
                   }
        
        Mode = ''
        #Mode = {'dl_no_ssl' : 'on' , 'dlinline' : 'on'}
        Mode = {'dl_no_ssl' : 'on' }
        postdata = urllib.urlencode( Mode )
        
        req = urllib2.Request(url,postdata,headers)
        
        try:
            response = urllib2.urlopen(req)
        except URLError, e:
            print e.read()
            print e.reason
        
        sHtmlContent = response.read()
        response.close()        
        
        api_call = GetMedialinkDL(sHtmlContent)
        
        if (api_call):
            return True, api_call
            
        return False, False
        
def getMediaLink(self):
    url = 'https://1fichier.com/?' + self.__getIdFromUrl(self.__sUrl)
    return True, dadadebrid(url)
		
		# -*- coding: utf-8 -*-

import urllib,urllib2,random,re
from cookielib import CookieJar
from base64 import b64decode

useragent = "'Mozilla/5.0 (X11; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0'"
cj = CookieJar()
opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))

def adfly(url):
    req = urllib2.Request(url)
    req.add_header('User-Agent', useragent)
    html = opener.open(req).read()
    ysmm = re.findall(r"var ysmm =.*\;?", html)
    if len(ysmm) > 0:
        ysmm = re.sub(r'var ysmm \= \'|\'\;', '', ysmm[0])
        left = ''
        right = ''
        for c in [ysmm[i:i+2] for i in range(0, len(ysmm), 2)]:
            left += c[0]
            right = c[1] + right
        decoded_url = b64decode(left.encode() + right.encode())[2:].decode()
        if re.search(r'go\.php\?u\=', decoded_url):
            decoded_url = b64decode(re.sub(r'(.*?)u=', '', decoded_url)).decode()
        return decoded_url
    else:
        return url

def dadadebrid(url):
    s = ''
    for i in range(15):
        s = s + str(random.randint(0,9))
    data = urllib.urlencode({'rand': "0."+s, 'urllist': url, 'captcha': 'none'})
    req = urllib2.Request("https://panel.dadadebrid.fr/index.php?rand=0."+s)
    req.add_header('User-Agent', useragent)
    req.add_header('Referer', "https://panel.dadadebrid.fr")
    req.add_header('host', "panel.dadadebrid.fr")
    response = opener.open(req,data).read()
    match = re.search("href='(.*?)'",response).group(1)
    decoded_url = adfly(match)
    if "dadadebrid" in decoded_url: 
        req = urllib2.Request(decoded_url)
        req.add_header('User-Agent', useragent)
        req.add_header('Referer', match)
        response = opener.open(req,data).read()
        match = re.search('download" href="(.*?)"',response).group(1)
        return match
    else:
        return decoded_url
    
# === Exemples ===
#print dadadebrid("http://uptobox.com/v3kl6vpjk9cq")
#print dadadebrid("https://1fichier.com/?98qt2k34ag")
#print dadadebrid("http://uplea.com/dl/74E0D0DF3AAE7BF")

**Comment by TmpName** [comment]
Comme ca
http://pastebin.com/hF4006my

Et je n'ai pas mit les 2 fonctions de ton code, car je n'ai pas les tabulations. J'ai juste mis la declaration de la fonction.

**Comment by noipo** [comment]
Donc j'ai juste à remplace ce que tu m'as donné par ce que il y aoriginalement sur onefichier.py ?
Merci

**Comment by Kodigoal** [comment]
Tu rajoutes le contenu des 2 fonctions def adfly(url) et def dadadebrid(url) , elles sont vides dans le fichier donné par TmpName.
