### ISSUE TITLE
nouveau source 

### ISSUE THREAD

**Issue by homayon50** [Kodi-vStream/venom-xbmc-addons#607]
Bonjour ,
je suis a la recherche d'une solution pour ajouter le site suivent: http://ww w.iranproud.net/iran-1-movies/TV+%26+CINEMA a mes source sur le super addon vStream ,j'ai regarder le tuto pour ajouter une source mais malheureusement je n'arrive pas ,après avoir essayer une vingtaine de fois  je commence perdre espoirs .. est ce que quelqu'un pourrais me faire un exemple  avec le site suivent :  http://w ww.iranproud.net/iran-1-movies/TV+%26+CINEMA. 

Ca sera vraiment très sympas .

sa fait vraiment très longtemps que j’essaye de faire sa ,j'ai trouver d'autre méthode pas trop pratique car a chaque fois que il ya un nouveau film je doit l'ajouter manuellement..

Merci d'avance.

**Comment by johngf** [comment]
je t'ai fait ça mais je me suis concentré sur les genres parce que new releases et recommanded movies n'ont pas d'URL tu peux toujours essayer d'ajouter la fonction qui affiche la page d'accueil pour les avoirs mais façon ils sont dans les genres donc.
série genre fonctionne
movie genres fonctionne
recherche fonctionne
ajoute ça dans le dossier sites
http://www99.zippyshare.com/v/3kSTVwZ2/file.html

**Comment by homayon50** [comment]
Bonjour @johngf 
Merci beaaaaaucoup sa marche a merveille ! 👍 💯 
J’essaye de crée mon propre Addon avec un menu très simple (pour mes parents). 
voici a quoi ressemble mon addon   : http://www76.zippyshare.com/v/FIl4H5wT/file.html  je voulait savoir si il y'avais un moyen d'avoir le meme menu que j'ai sur mon addon plus un autre dossier qui vas chercher  ''iranproud_net.py''. ou tout simplement  un exemple d'un addon avec un menu simple.

Bien cordialement.

**Comment by johngf** [comment]
Je n'ai pas encore regardé ton addon 
La fonction qui'affiche la page d'acceuil il faul la creer pour quelle ouvre l'adresse de la page d'acceuil
Actuellement tu as SERIES_GENRES et MOVIES_GENRES rajoute en un du nom que tu veut MOVIES_MOVIES par exemple avec l'adresse du site pour la page d'acceuil ensuite regarde le script comment tu appelles les functions tu devra en creer d'autres

**Comment by johngf** [comment]
Je n'ai pas reussi a utilisé ton addon il manque des extensions que je ne trouve pas quand il sera instalable avec les extensions je testerai 
Je clos l'issue bonne continuation pour ton addon
