### ISSUE TITLE
Problème Lien ZT Vstream Android

### ISSUE THREAD

**Issue by Stefle33** [Kodi-vStream/venom-xbmc-addons#612]
Bonjour, 

Il m'est impossible de lire les liens de zone téléchargement sur vstream (kodi android). 

Je clique sur le lien, le "en cours" apparaît puis... Rien. 

J'ai effectué les manœuvres décrite sur ce lien : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/543

Une mise à jour à donc été faite mais ça ne marche toujours pas. 

Avez vous une solution ? 

Merci d'avance

**Comment by johngf** [comment]
c'est quelle lien ? t'en a essayé d'autres ?

**Comment by Stefle33** [comment]
Je n'ai justement pas accès au hebergeur ça bloque avant. 

J'ai essayé plein de lien série comme film toujours le même problème

**Comment by johngf** [comment]
tu peut posté le log sur pastebin ?

**Comment by Stefle33** [comment]
Euh... C'est à dire ?

**Comment by johngf** [comment]
tu as un fichier log de kodi poste le sur pastebin et donne le lien ici

**Comment by TmpName** [comment]
Si tu as un navigateur sur ta machine, essaye d'aller voir directement sur leur site, si c'est pas une histoire de bloquage.

**Comment by Atomium25** [comment]
J'ai également ce problème depuis le milieu d'après-midi, d'un coup sur ma box Android zone téléchargement n'a plus voulu me donner accès aux hébergeurs, chargement en boucle.. 
À noter que mon FAI est Free et que j'ai un accès "normal" lorsque j'essaye d'y accéder depuis mon portable en données mobiles. En Wi-Fi sur le téléphone même problème que sur la box, chargement en boucle.

**Comment by Atomium25** [comment]
Effectivement depuis le navigateur quand je veux lancer un film le message suivant s'affiche :

"Suite à de trop nombreuses demandes depuis votre adresse IP, impossible d'afficher la page, veuillez réessayer plus tard.
(Dans 18055s)"
 Il est vrai que j'ai un petit peu spam, en ajoutant un grand nombre de séries aux favoris ces dernières 24h, test de qualité oblige, je n'ai donc plus qu'à patienter --'

Problème résolu pour moi donc :)

**Comment by Stefle33** [comment]
Ras sur le site de ZT. 
Je précise que ça bloque sur mon portable (galaxy note 4) avec les données mobiles. 
J'ai vstream sur la box Android miami et aucun problème. 
Idem sur deux autres pc et aucun problème. 
Pareil sur la tablette Samsung ça fonctionne correctement. 

Il y a seulement les liens ZT qui ne marche pas sur mon smartphone, en passant par d'autres sources (youwatch...) ça marche...

**Comment by Stefle33** [comment]
Comment tu fais pour essayer depuis le navigateur ?

**Comment by TmpName** [comment]
En allant essayer de voir le film directement sur le site de ZT via un navigateur.
