### ISSUE TITLE
Site Mongol

### ISSUE THREAD

**Issue by valas69** [Kodi-vStream/venom-xbmc-addons#613]
Salut !
J'aimerais me tenter dans l'ajoutation de source / site dans Vstream.
J'ai fouillé dans le zip et j'ai trouvé un .py "ajouter une source".
Je l'ouvre et là, je n'ai rien compris.
J'aimerais bien mettre plusieurs site. Si quelqu'un pouvais m'aider.
Voilà à quoi ressemble la plupart des sites: http://ubkinochid.xyz/

**Comment by LordVenom** [comment]
Oui ont peux t'aider mais faut avoir commencer un minimun

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Cr%C3%A9er-une-source

**Comment by valas69** [comment]
Oui j'ai lu ça :)
J'ai même tenté de le compléter, mais quand je l'ai mis dans le dossier "site", il n'apparaissait pas dans Kodi :/

**Comment by TmpName** [comment]
Si il y a un bug sur ton fichier, il n'apparaitra pas (c'est une securite)
Passes nous ton fichier via pastebin (pas de c/c complet sur github stp)

**Comment by valas69** [comment]
Tenez. En réalité, je veux deux chose:
- Afficher tous les films
- Rechercher un film
Je me fiche de les sortir genre par genre, de A-Z etc..
C'est pour ça que j'ai pas modifié énormément de chose.
http://pastebin.com/z7FuvwQ4 
ou
http://hastebin.com/lofaxokobe.rb (plus propre je trouve)

Merci pour vos réponse.

**Comment by TmpName** [comment]
Le prb est a la ligne 48, apres url tu as mis 2 '.
Apres la source apparaitra.

**Comment by valas69** [comment]
Ah oui, j'y avais pas touché pourtant :p 
Merci, je tenté de me débrouiller seul ^^

**Comment by valas69** [comment]
Bon, après une bonne heure de recherche. J'ai rien trouvé.
Au début, je pensais que c'était la faute du site, du coup j'ai testé avec "'http://official-film-illimite.net/"
Hastebin: http://hastebin.com/aketuxucer.py
Pastebin: http://pastebin.com/MSUTPsgy

Et bien il se trouve en faite que je suis nul. 
Dans les deux cas (site), quand je faisais une recherche, aucun film n'apparaissait...

**Comment by nmagre** [comment]
@valas69 C'est normal, c'est a toi de "scrap" (récupérer les infos), le code par défaut ne peut pas fonctionner, tu dois l'adapter selon le site par exemple ta fonction `showMovies`, tu a une Regex qui cherche "class="movie movie-block"..." et il n'y pas de div/span/... sur ton site qui a ça comme classe.

**Comment by TmpName** [comment]
Mince, dsl, j'ai mit le fichier squelette a jour, merci.
