### ISSUE TITLE
lecteur externe

### ISSUE THREAD

**Issue by rod93** [Kodi-vStream/venom-xbmc-addons#619]
Bonjour
bravo pour le ad-don 
avez vous une idée comment lire avec un lecteur externe?

**Comment by TmpName** [comment]
Ha bonne question, je sais meme pas comment ca va marcher.
En fait ca ne depend pas de Vstream mais de kodi, tu peux configurer kodi pour passer par un lecteur externe, et du coup Vstream va en faire autant, mais je n'ai jamais teste ca.

**Comment by rod93** [comment]
Non je nais pas précise mon kodi est déjà configure avec 2 lecteurs externe mpc-hc et powerdvd mais mpchc ne se lance pas avec le add-on

**Comment by johngf** [comment]
dans les parametre de vstream tu peut choisir ton lecteur aussi xbmcplugin dvdplayer etc..
il faut voir si mpchc est dans la liste

**Comment by TmpName** [comment]
Y a le "auto" qui devrait marcher.
Mais comme ces fonctions sont maintenant obsolettes http://forum.kodi.tv/showthread.php?tid=173887&pid=1516662#pid1516662
Je sais pas du tout ce que cela va changer.

Pas de soucis sur les autres addons ?

**Comment by rod93** [comment]
Non cela ne fonctionne pas en auto
Je n'utilise pas d'autres add-on mais je vais essayer
Par contre cela fonctionne pour mes films en local
En fait mon problème est que l'image est que les blancs sont brûlés  avec les lecteurs interne a kodi  merci

**Comment by LordVenom** [comment]
Cette page t'aide ?

http://kodi.wiki/view/external_players

**Comment by TmpName** [comment]
Si tu t'y connais en python, je peux t'indiquer des trucs a tester, mais franchement Vstream utilise une commande standard, donc je pensais que ca utilisait les memes reglages que le reste de kodi.

Apres il se peut que le lecteur externe ne marche que pour le local, c'est pour ca que je te demande de tester un autre addon.

**Comment by Kodigoal** [comment]
Comme dit avant faut faire un fichier
playercorefactory.xml pour lancer des players
externes sans rien toucher à la config de vstream ( on laisse par défaut XbmcPlugin(recommandé) avec auto en grisé)

Par exemple pour mpc-hc sous windows:
ici il lance les streams internet en http/https par MPC , si autres protocoles il passera par DVDPlayer.
http://pastebin.com/E0rdpbX3

(attention à vérifier dans le xml le chemin installation de mpc-hc)
Lien qui explique pour ton cas je pense (en anglais)
http://forum.kodi.tv/showthread.php?tid=209596

Xml a modifier selon protocoles que tu veux pour les streams internet.

Sous Android si je veux VLC ou autres comme player externe je met ca comme xml:
http://pastebin.com/A0NWeVib
(faut juste modifier les noms des app si pas juste dans la 1ère partie et choisir quel appli pour tel protocole)

Xml à copier dans kodi/userdata/

**Comment by TmpName** [comment]
Mais d'apres ce que j'ai compris, il a deja un kodi fonctionnant avec des lecteurs externes.
C'est juste que Vstream lui ne passe pas par les lecteurs externes.

**Comment by Kodigoal** [comment]
Je pense ya pas les protocoles stream internet configurés dans son xml.

**Comment by TmpName** [comment]
Ha ok, j'avais pas compris ca.

**Comment by rod93** [comment]
ok merci effectivement je n'avais pas configuré mpc-hc pour "http, https"
par contre maintenant cela lance mpc-hc mais plante aussitôt
"Problem 168380: ffdshow!DllGetClassObject "

**Comment by Kodigoal** [comment]
Alors là ... soucis avec ffdshow pêtre.
Vu le lien ou ya des explications pour configurer mpc-hc et cie , je ne saurais dire ce qui cloche.
Faut pêtre tester comme lui fait pour voir si ca marche.
Jamais testé de lecteur externe sous windows.

**Comment by rod93** [comment]
ok j'ai tester avec mpc-hc64
pas d'erreur mais ca s'ouvre et se ferme aussitôt
je ne comprend pas je fais essayer de virer ffdshow dans les filtres de mpc-hc64 pour voir
car habituellement j'utilise lavcodec>ffdshow>avisynth>madvr sur mpc-hc 32 bits bref une usine a gaz mais qui donne une image de malade

**Comment by Kodigoal** [comment]
Oui doit yavoir un binz quelque part dans les filtres ou autres ..
Si j'ai le temps cette semaine , je vais tester si j'arrive.
Tu testes quel film /site/ hebergeur ?

**Comment by LordVenom** [comment]
Pense a partager avec nous tes avancées merci.

**Comment by Kodigoal** [comment]
Pas tout compris à cette usine à gaz, j'ai installé mpc-hc 32bits version stable sur le lien donné plus haut.( tout configurer par defaut) 
En effet mpc-hc s'ouvre et se ferme quand il rencontre une erreur,
genre error to render file ou quand tu veux ouvrir par ex sur ZT les liens direct via uptobox ( mkv) ,
et encore certains fonctionnent XD l'impression qu'il gére pas les chapitres ou je ne sais quoi.

Car en t'aidant du log kodi (kodi.log)  , tu vas chercher le lien de la vidéo dans le log et 
tu l'ouvres directement par mpc-hc voir quelle erreur il sort ...
En gros les liens ZT via uptobox en version 720/1080 light fonctionnent, les versions 720/1080 'normales' ca dépend ..
En passant via uptostream ( ZT) , ca fonctionne aussi.
Sinon pour les autres hosters , ca varie ... Fonctionne ou pas c'est la loterie.

Alors le mieux à faire et fonctionne à 100% ( normalement xD) , c'est d'utiliser sur le lien vidéo clic droit et 'dl et visualiser' sur les vidéos qui pose problème.

Tu devrais comme ca pouvoir tester si ca fonctionne chez toi.
J'ai tout désinstaller car franchement j'ai rien pigé et configurer tout ca juste sur mon portable ca me sert à rien xD.

**Comment by TmpName** [comment]
XD, ha le monde merveilleux de linux. Et c'est pas comme si cette appli n'avait qu'un an d'existence. Si tu n'es pas bidouilleur, en general ca se fini par "bon ben ca fait 2 jours que je galere, que j'installe des dizaines de trucs, que je consulte des dizaines de forums, j'ai decouvert plein de truc, mais ca m'avance pas, ne me servira a rien et pire plus j'avance, moins je comprend ce qui se passe".

Et le pire c'est que meme sous windows on se retrouve avec la meme quete infernale.

Enfin bon, vais pas y cracher dessus, c'est l'appli qui me sert le plus apres le navigateur web, mais des mysteres sur son fonctionnement, je pourrais en ecrire un livre.

**Comment by Kodigoal** [comment]
xD,  c'est clair.
Bon là c'est plus mpc-hc qui pose problème vu l 'usine à gaz.
Si le lien vidéo s'ouvre pas non plus si tu le passes en direct par mpc-hc ...
J'y connais rien à mpc-hc , madVR et cie et chacun en plus doit avoir sa config perso sur ce machin .. vas y pour trouver ce qui cloche cas par cas.( codecs manquants, option pas cocher, filtres pas bon,..)
Mais bon reste l'option via 'dl + visualiser' , plus de soucis sur la config 'all inclusive' mpc-hc que j'avais install.
On verra si ca fonctionne pour lui.

**Comment by rod93** [comment]
salut
de retour apres plusieurs essais, toujours pareil, j'ai viré ffdshow et passe en direct sur lav video puis madvr cela ne fonctionne pas non plus
je vais essayer en récupérant un lien dans le fichier log et vous tiens au courant

**Comment by rod93** [comment]
ca avance....
pas de lien dans le fichier log

13:37:50 T:13920  NOTICE:     Device 2
13:37:50 T:13920  NOTICE:         m_deviceName      : default
13:37:50 T:13920  NOTICE:         m_displayName     : default
13:37:50 T:13920  NOTICE:         m_displayNameExtra:
13:37:50 T:13920  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
13:37:50 T:13920  NOTICE:         m_channels        : FL,FR
13:37:50 T:13920  NOTICE:         m_sampleRates     : 192000,96000,48000,44100
13:37:50 T:13920  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
13:37:50 T:4028  NOTICE: 	[PLUGIN] Vstream: player stoped
13:37:50 T:4028  NOTICE: 	[PLUGIN] Vstream: Closing player
13:37:50 T:4028  NOTICE: 	[PLUGIN] Vstream: Table initialized

**Comment by Kodigoal** [comment]
T'as la derniere version de vstream installée? 
T'as testé en passant par 'dl + visualiser' ? 
tu testes via quel site ? quel film?

**Comment by rod93** [comment]
Oui dernière version de vstream
J'ai tester un lien en direct ça s'ouvre ne plante pas mais reste en pause
J'utilise les liens zt en premium
Qui fonctionne parfaitement en lecture interne (star trek en 1080p) par
exemple

**Comment by rod93** [comment]
Par contre je ne sais pas comment utiliser le liens DL+streaming

**Comment by Kodigoal** [comment]
Sur le lien du film , tu clic droit dessus et tu auras des options , tu choisis 'dl + visualiser' , ensuite il va demander ou enregistrer le fichier , tu choisis un repertoire et 'ok' .
Ensuite si c sur Zt ton lien , il ouvre popup pour demander via uptostream ou via uptobox , tu fais comme d'hab. et il lancera le telechargement et une popup qui met en cache , à 100% le film se lance.
Option 'dl+visualiser' en image:
[lien](http://img15.hostingpics.net/pics/227989IMG20161102202931.jpg)
Sinon la version  star trek 1080 hdlight se lance pas ?
ou via uptostream?

**Comment by rod93** [comment]
bonjour
auriez vous le protocole et format utilisé par vstream merci

**Comment by TmpName** [comment]
Ce n'est pas Vstream qui decide mais kodi, on utilise juste l'api fournie avec.

**Comment by rod93** [comment]
Ok c'est bon cela fonctionne à peu près pas sur mpchc 64 sans traitement avisynth mais pas davance ni de recul rapide 
Qui connais les protocoles et format pour configurer correctement 
( Mon problème venait d'un conflit entre protocole et le format j'ai donc tout mis en lecture externe dans le

**Comment by TmpName** [comment]
dans le ?
J'ai rien trouve pour toi a part sur leur forum
1 - un gars qui a utilise autoit pour MPC-HC http://forum.kodi.tv/showthread.php?tid=43511
2 - Un gros tuto http://forum.kodi.tv/showthread.php?tid=116724
