### ISSUE TITLE
Film et Film 3D sur UPtoBox

### ISSUE THREAD

**Issue by CharlyNetSky** [Kodi-vStream/venom-xbmc-addons#623]
Salut l'équipe, alors déja un énorme +1 pour votre taff car avoir tout un catalogue de film, série ... dans sa poche et sur sa tv (et ça même avec un débit de m****) c'est juste géant donc encore merci !

J'ai quelques questions : 
- j'ai un compte premium chez UpToBox mais j'arrive pas a regarder en direct sa charge et sa plante alors que l'autre fonction fonctionne très bien. Why ? :)
- J'ai tester de regarder un film streamer en 3D mais impossible de convertir le flux alors que ma tv le fait automatiquement sur les films en 3D que je possède (SBS la 3D généralement) y'aurait il une fonction à activer que j'ai loupé ?

Merci pour vos futurs réponses

**Comment by LordVenom** [comment]
Bonjour,

1) Je laisse les pros de Upto te dire je l'utilise pas.

2) Je pense pas que le lecteur de xbmc supporte la 3d il te faut passer par un lexteur externe  TMT5 ou PDVD11

Pour configurer un lecteur externe il faut modifier le fichier playercorefactory.xml  http://kodi.wiki/view/external_players

**Comment by CharlyNetSky** [comment]
Merci pour ta réponse :)
Si si le lecteur par défaut de XBMC prend en charge la 3D car mes propres rip de 3D SBS  sont détectés en tant que 3D et la tv fait ensuite la conversion
En espérant que quelqu'un passe par la pour UpToBox :)
Bon WE

**Comment by TmpName** [comment]
Pour la 3D, jamais teste mais kodi gererait la 3D (dont le format SBS) depuis la V13.
Tu as teste avec kodi et un fichier avi directement ?

Pour uptobox il y a 2 mode via uptobox et via uptostream, le second est gratuit et de moins bne qualite, et le premier payant avec authentification mais les fichier demande une meilleure connexion.
Tu as bien authentification reussie qui apparait ?
Tu passes par les resolvers de Vstream ou UrlResolver ?

Si tu as un mauvais debit, il y a une option en clic droit "Dl et Visualiser"

**Comment by CharlyNetSky** [comment]
oui j'ai déja testé avec un fichier 3D mkv et sa marche. 

Pour ce qui est de UpToBox j'ai un compte premium que j'ai configurer dans Vstream et il m'indique bien que l'authentification a réussi mais en direct impossible à regarder il m'affiche la fenêtre avec les 90% de chargement mais c'est tout je peux le laisser 10 min a la fin il me marque que c'est pas possible ...

**Comment by johngf** [comment]
Surement acceleration graphique le raspberry est il assé puissant pour decodé dela 3d ?

**Comment by CharlyNetSky** [comment]
bah le soucis c'est que pi est en ethernet, le W10 sur ma tablette est en Wifi. j'essairai de réinstaller de nouveau ... 
Oui le pi est assez puissant pour décoder la 3D et le 5.1 je l'ai déja fait avec un .mkv :)
merci pour vos réponses

**Comment by TmpName** [comment]
Tu pourrais pas nous faire passer les logs au moment ou tu lances la video stp ?

Sinon pour la 3D passes par un navigateur, et DL le meme fichier directement sur le site de ZT, pr le tester sous kodi, ils utilisent peut etre un nouveau codec.

**Comment by Kodigoal** [comment]
Quand la tv detecte pas la 3D , je met manuellement le mode 3D sur la tv , tu peux pas le faire
manuellement ?
Après parfois kodi detecte pas non plus la 3D , sinon il met l'interface en mode 3D normalement.
La aussi faut le faire manuellement mais embétant à faire car le menu player est mal affiché..
T'as bien les derniers fichiers uptobox.py / zone-telechargement.py à jour ? 
Je suis pas premium mais en testant ca fonctionne en lancant les films , à part les lag ensuite xD

**Comment by CharlyNetSky** [comment]
oui Kodigoal je fais la même chose que toi aussi quand la tv la détecte pas mais le soucis c'est que quand j'appuie sur mon bouton 2D vers 3D, la tv passe l'image en 3D et pas le flux. COmme je sais pas si j'ai été assez claire :/ la 3D SBS afficher a l'écran (2images) n'est pas convertis en une seule image mais reste bien en 2images avec le flou

je vous poste sa dans 5 min :)

**Comment by CharlyNetSky** [comment]
alors maintenant aller comprendre j'ai décocher mon compte premium dans les paramètres le lien direct avec UpToBox fonctionne mais j'ai pas le son ... j'ai que la vidéo ...

**Comment by Kodigoal** [comment]
Ah oui bizarre ca , et si tu changes le mode 3D stéréoscopique  par défaut sur automatique  en cote à cote dans le menu du player en lecture ? 
Mais tu lances le flux 3D par le rasp ou ta tablette via hdmi tv ?

**Comment by TmpName** [comment]
Ha oui pour uptobox, il y a des options a ne pas activer dans ton compte (reglage sur navigateur, sur ton compte uptobox).
Je recherche les options.

**Comment by CharlyNetSky** [comment]
alors la je vous dis un grand merci !!

Le fait d'avoir enlever les 2 options dans UpToBox m'a permit d'avoir accés au direct et de ce fait j'ai la 3D détecter maintenant :D 
Par contre j'aurai une question pour toi TmpName tu as sus sa comment ? par mon Log ? Si oui ou exactement ?

Encore merci !!

**Comment by TmpName** [comment]
Lol, nope j'ai meme pas vu que tu avais mis le log.
J'ai eu la puce a l'oreille quand tu as dit que ca avait remarche en desactivant ton compte uptobox (y a pas ces options en mode gratuit)

**Comment by samfox92** [comment]
Salut
J'ai besoin d'une explication concernant kodi/uptobox/vstream/captcha.
Sur mon galaxy s6 edge plus tous fonctionne. Le captcha s'affiche je peut saisir la séquence.
Sur ma box h96 configuré pareil le captcha s'affiche pas dons impossible  à lancer une série ou autre sur zone telechargement. 
A quoi cela est dû?  Y a t-il une solution ?
Merci d'avance.
Ps : les 2 options de download dans uptobox sont désactivé et kodi et vstream sont les dernières versions

**Comment by TmpName** [comment]
Tu tournes sous quelle version de kodi ?

**Comment by samfox92** [comment]
Kodi v16.1 “Jarvis”

**Comment by TmpName** [comment]
Tu n'aurais pas les log stp ?
(Sur pastebin ou autre site externe)

**Comment by samfox92** [comment]
Bonjour,
Voila le fichier log: http://pastebin.com/7X558k12

Je pense que le problème viens de là?

Init (DialogBusy.xml) ------
19:35:19 T:18446744072306233320   DEBUG: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function Display_protected_link
19:35:19 T:18446744072306233320   ERROR: ffmpeg[AC5B0FE8]: [png] Invalid PNG signature 0x4749463837611E01.
19:35:19 T:18446744072306233320   DEBUG: Error [-1094995529] while decoding frame: Unknown error 1094995529
19:35:19 T:18446744072306233320   ERROR: AVFrame* CFFmpegImage::ExtractFrame(): Could not decode a frame
19:35:19 T:18446744072306233320   DEBUG: bool CBaseTexture::LoadFromFileInternal(const string&, unsigned int, unsigned int, bool, const string&) - Load of /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.vstream/Captcha.png failed.

Mais je comprend pas le problème merci d'avance pour ton aide.

**Comment by TmpName** [comment]
Ton systeme aurait un prb pour lire le fichier du captcha ?
Tu as un navigateur sur ta box, pour aller voir directement le site de dl-protct ?

Ou simplement, essaye de voir si tu peux visualiser cette image
![captcha](https://cloud.githubusercontent.com/assets/8311559/20244840/fba4f722-a990-11e6-8c52-60ef0ff15b1a.gif)

**Comment by samfox92** [comment]
Salut
J'ai installé chrome et le captcha s'affiche correctement dans le navigateur mais toujours pas dans kodi.
Désolé de mettre du temps pour te répondre mais le boîtier est accessible pour moi que le week-end. 
Si tu as une autre idée ou tu as besoin de fichier pour plus d'investigation je suis à ton écoute.
Merci

**Comment by TmpName** [comment]
Kodi peut egalement faire lecteur d'image non, a tester aussi si tu peux.
J'ai vraiment l'impression que la version de kodi android doit etre bancale, en fait c'est un fichier genere par un script, le format ne doit pas etre standard.
Et le navigateur n'utilise pas les memes librairies que kodi.

Sinon c'est le telechargement qui deconne.
Dans le dossier userdata de kodi, tu devrais trouver un fichier "Captcha.png", jette un oeuil pour voir si il est complet.
