### ISSUE TITLE
Nouvelle source pour Vstream

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#624]
Bonjour tous le monde comment allez vous. En surfant sur le web je suis tombé sur ce site qui à l'air d'être sympa pour rajouter dans la liste des sources je vous donne le site : ht tp://directstream.ws/ 
je l'ai testé et ça fonctionne très bien à vous de voir les amis

**Comment by johngf** [comment]
le temps de réponse du site n'est pas terrible a 12h30 je me demande ce que ça va etre le soir

**Comment by patoche2025** [comment]
Ah bon moi tantôt le site avait répondu rapidement

**Comment by TmpName** [comment]
Bon je viens de tester, alors pour moi :
- Tres lent, j'ai meme cru que le site etait out.
- Peu de lecteurs, et pas les meilleurs
- Tres bon catalogue, j'ai essaye de le planter avec des vieux films a la con, il a tout trouve.
- pas vu de liens morts.

Edit, en fait j'ai trouve un nid de lien mort dans les series ^^, donc je reste discret sur mon 3 eme point.
