### ISSUE TITLE
référencement hoster hs ou site hs

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#627]
Axavid
Azerfile
V-vids
Veevr
Full stream vk fermé ou maintenance a suivre
Tntv rattrapage n'est plus mis a jour depuis dec 2015 surement abandonné
Enquete de reportage suit le meme chemin rien depuis fevrier 2016

**Comment by TmpName** [comment]
wat.tv ferme

**Comment by johngf** [comment]
Certain hoster on changé de nom divxstage c'est la cas

**Comment by TmpName** [comment]
Ha merde, et c'est quoi le nouveau nom ?

**Comment by johngf** [comment]
on pourrait pas mettre un timeout par site pour la recherche global parcequela liberty land planet stream et libre stream flingue la recherche impossible d'annulé

**Comment by TmpName** [comment]
Yep, mais c'est bizarre normalement ca doit pas annuler la recherche, juste bloquer le temps du timeout par defaut.

**Comment by TmpName** [comment]
Heee, attend j'ai pas eu le temps de corriger.
Pour le moment je vais au moins virer, les hoster ferme.
Si tu clotures l'issue dans 2 jours j y pensrais meme plus.

**Comment by johngf** [comment]
par contre divxstage fonctionne

**Comment by TmpName** [comment]
Wé, je sais, je viens de me faire engueler, je remet.
