### ISSUE TITLE
Mega-Stream HS

### ISSUE THREAD

**Issue by Atomium25** [Kodi-vStream/venom-xbmc-addons#631]
Comme indiqué dans le titre, depuis hier soir impossible d'avoir accès à Mega-Stream, si vous pouviez m'éclairer sur le problème ou y jeter un coup d'oeil ce serait cool.

Merci d'avance,

**Comment by TmpName** [comment]
Je suis dessus, ils ont refait leur site, de maniere plus simple,

**Comment by Atomium25** [comment]
Ok merci, tiens nous au courant ;)

**Comment by TmpName** [comment]
Bon la j'ai commence, on peut lancer les films, next page ok.
Les series ca affiche juste la page
Pas refait ni les genres ni la recherche.

Si quelqu'un veut continuer, moi ce soir j y touche plus, je vais d'abord corriger un prb sur openload (encore ...)

**Comment by Kodigoal** [comment]
Genres ok.
Le reste je galere xD

**Comment by Atomium25** [comment]
Merci pour ce que vous faites, c'est dispo en mettant à jour manuellement avec l'astuce des 3 jours ou c'est juste en beta.. ?
Tenez nous informé de l'avancement de la chose, encore merci pour votre boulot :)

**Comment by Kodigoal** [comment]
Pour l'instant en beta vu que c'est pas fini.
Tu peux deja copier/coller le code de la beta dans ton fichier megastream.py en local pour voir les films.

**Comment by Atomium25** [comment]
Merci de ta réponse, je l'utilise surtout pour les séries en HD. Une fois terminé cela serait sympa de pouvoir avoir accès aux séries HD de Mega-Stream directement depuis Série ---> Série en HD comme c'était le cas récemment. J'attendrai le déploiement sur l'officiel pour l'essayer sur ma Box Tv Android, merci pour votre réactivité en tout cas :)

**Comment by TmpName** [comment]
Le alt je m'en mefis, tu peux y mettre ce que tu veux, tandis que le titre c'est ce que tu lis, donc la oblige de mettre un vrai titre. Mais tu peux changer si ca t'arrange.

Sinon la je suis sur openload, je vais faire une fonction pr convertir le code JS en python pour eviter de tout refaire pour une modif digne d'un gamin de 8 ans toute les semaines, et ca va me prendre pas mal de temps, me faut aussi corriger la methode brute-force.

Du coup j'y jetterais un oeuil que ce WE.

**Comment by johngf** [comment]
bon j'ai corrigé affichage saison et episode hoster en cours...

**Comment by Atomium25** [comment]
Merci pour ton travail, dommage qu'il n'y ait plus la possibilité d'avoir que les séries en HD, c'était vraiment très pratique ... Le déploiement sur l'officielle est prévu pour quand selon toi ? :)
Et oui s'il y a la possibilité d'avoir le top 100 ce serait vraiment sympa ;)

**Comment by johngf** [comment]
j'ai ajouté top film et top serie sinon il faut attendre qu'il soit fini il reste la recherche a faire elle fonctionne plus

**Comment by TmpName** [comment]
Rajout de la recherche, mais j'ai pas trouve comment non plus selectionner uniquement les videos HD.

**Comment by Atomium25** [comment]
Ok merci, quand cela sera t-il disponible sur la version officielle ? :)
Du coup t'as avancé sur le problème d'Openload, parce qu'il me semble que Mega-Stream n'utilise que ça ..

**Comment by TmpName** [comment]
Oui Openload refonctionne, mais c'est provisoire, me faut securiser le truc, j'utilise une fonction pas tres "secure", faudrait que kodi tourne sous python 3.

**Comment by TmpName** [comment]
Dis nous si ca tourne bien quand tu pourras la tester stp. Qu'on puisse clore l'issue.

**Comment by doubidave** [comment]
Salut, mega stream est mort aussi? Car je n obtient aucun résultat sur aucun type de recherche... 🤔 merci 😊

**Comment by TmpName** [comment]
Tout est vide, j'y jette un oeuil de suite.

**Comment by TmpName** [comment]
Mit a jour, mais encore en MAJ auto.
Fichier dispo ici https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/megastream.py

**Comment by doubidave** [comment]
Je suis loin de comprendre comment tout bidouiller mais un grand merci pour le suivi en tout cas 😊

**Comment by doubidave** [comment]
Pour j ai essayé de le faire moi même mais pas moyen. J ai deux kodi, un ou j ai testé et soit la source disparait soit j ai un message d erreur. Et l autre kodi j ai pas touché et je n ai pas de résultat. Je crois que je vais attendre la maj, je suis pas doué...

**Comment by TmpName** [comment]
Faut juste ouvrir ton fichier avec un editeur de fichier, et faire un copier/coller du precedent lien.
Mais je met les fichiers en MAJ ce soir, si personne le fait avant.

**Comment by doubidave** [comment]
Ah d accord, moi j avais juste remplacer l ancien py par le tien, a la sauvage 😕 Je vais attendre la maj et je desespere pas d un jour reussir ce que beaucoup font ici. Encore merci d avoir pris la peine de me répondre TmpName 😆

**Comment by doubidave** [comment]
J ai eu une maj mais j ai un message d erreur pour  megastream. Je suppose que ca fonctionnera bien a un moment.

**Comment by TmpName** [comment]
Ha ? si tu as eu la maj apres dimanche millieu d'apres midi, c'est pas normal.
Tu as tout qui deconne, ou juste une partie ?

**Comment by Atomium25** [comment]
Bonjour,

Toujours un petit problème au niveau de la recherche dans Mega-Stream, lors d'une recherche le résultat s'affiche avec un [+5] par exemple, indiquant qu'il y'a d'autres résultats disponible pour cette recherche mais une fois rentré dans le résultat, impossible d'avoir les différents épisodes d'une série par exemple... J'ai du mal à expliquer, mais testé la recherche si vous pouvez et vous verrez ce à quoi je fais référence :)

Merci d'avance, bonne journée et merci pour le taff que vous faites ;)

**Comment by TmpName** [comment]
Ha oui, j y jette un oeuil de suite.

**Comment by TmpName** [comment]
Corrige, merci.

**Comment by Atomium25** [comment]
Merci beaucoup, également un problème au niveau du top 100 film/série, mais il me semble que le problème date un peu maintenant ..

**Comment by johngf** [comment]
résolu @Atomium25

**Comment by Atomium25** [comment]
Un grand merci à vous pour tout ce que vous faites ! Dernière petite question, j'ai forcé la MàJ avec l'astuce des 3 jours mais pas de changement, vous avez modifié sur la Beta ou ce sera bientôt disponible pour l'officielle ?

Bonne soirée :)

**Comment by johngf** [comment]
Il faut attendre que le fichier soit dans la master ou faire copier coller

**Comment by Atomium25** [comment]
De nouveau un problème, au niveau des liens, après être rentré dans les films/séries plus aucun lien d'hébergeur disponible ...
Désolé de vous relancer mais y'a vraiment des problèmes avec ce site, dommage car il y a pas mal de contenus HD en série comme en films.


Merci d'avance en tout cas :)

**Comment by TmpName** [comment]
C'est bon, c'est corrige, par contre je ne lancerais la MAJ que plus tard dans la soiree, il y a des prbs sur d'autres sites, et il risque d'y avoir d'autres modif a faire en MAJ.

**Comment by Atomium25** [comment]
Ok merci pour tout ! Vraiment niveau support vous êtes au top, rien à redire ! ;)
