### ISSUE TITLE
Afficher les marques pages dans la libraire de kodi

### ISSUE THREAD

**Issue by noipo** [Kodi-vStream/venom-xbmc-addons#633]
tout est dans le titre :)

**Comment by TmpName** [comment]
Si tu fais un clic droit et "rajouter en librairie" au lieu de "rajouter en marque page", ca ne marche pas ?
Bon j'avoue cette partie n'a jamais ete finie.

**Comment by noipo** [comment]
Non fonctionne pas ....

**Comment by johngf** [comment]
la librairie c'est pour les liens final avec hoster et marque page le reste

**Comment by TmpName** [comment]
Tu as configure les repertoires dans les parametres de Vstream et de kodi ?
Il te faut choisir un repertoire et le rajouter dans les parametres de Kodi et Vstream.

**Comment by LordVenom** [comment]
Je pense juste qu il n y a pas ajouter a librairie depuis le context des marques page a verifier
