### ISSUE TITLE
Adding new Web Video Source

### ISSUE THREAD

**Issue by emailradhesh** [Kodi-vStream/venom-xbmc-addons#634]
Hi,

I've script (similar to videobuzz_com.py). It pulls videos from website [TopBestSite](http://www.topbestsite.com). The videos are in Indian languages. Every time there is update to vstream add-on the script gets deleted and I've to copy it manually. Is there anyway I can ensure my script is not deleted during update or copy my script automatically after updating Vstream add-on.

Thanks to all the contributors of Vstream add-on. Because of this add-on my script is simple.

**Comment by johngf** [comment]
"Every time there is update to vstream add-on the script gets deleted"  >>> only once a month when new release is annonced
The update check if there are differences and replace them
you can create a script (.sh  .bat  .py) and run it in background on boot (many example on google)
>> check if file exists 
>> if not 
>> restore your file from backup folder

**Comment by emailradhesh** [comment]
Thanks @johngf these will be dependent on OS. I guess I've to find if there is any job that can be run in Kodi.

**Comment by emailradhesh** [comment]
Leaving last comment for others. There is official add-on [Kodi_Callbacks](http://kodi.wiki/view/Add-on:Kodi_Callbacks) to do user defined tasks as and when event happens in Kodi. Exploring it.
