### ISSUE TITLE
Problème à l'ajout d'un nouveau site

### ISSUE THREAD

**Issue by destroyxx** [Kodi-vStream/venom-xbmc-addons#635]
Bonjour/Bonsoir,
J'ai un problème lorsque que je veux ajouter de nouveaux site pour regarder des films streaming. Le nom du site apparais sur kodi mais une fois que je clique dessus aucun film n'est affiché pouvez jeter un coup d'oeil merci ? (je met le fichier a votre disposition)
[streamay_com.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/572162/streamay_com.zip)

**Comment by destroyxx** [comment]
J'ai compris. C'est le pattern qui doit être changer. Y'a t-il un logiciel qui crée automatiquement le code pattern selon un site car je ne comprends pas comment ça fonctionne ?

**Comment by TmpName** [comment]
Il y a aussi une erreur chez moi a la ligne 47, il manque la focntion.
Pour le faire tourner, me faut supprimer les lignes 45 a 47.

Et non il y a pas de logiciel automatique ^^.
- dans le navigateur afficher code source
- copier la zone qui t'interesse dans https://regex101.com/
- bidouiller a tatons, avec juste les bases et les exemples de Vstream tu peux t'en sortir.

Donnes moi quelques mn stp.

**Comment by TmpName** [comment]
Essaye ce code http://pastebin.com/bfkjqkVJ
Tu as un debut de regex fonctionnant.

Mais tu aurais du partir de ce fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_une_source.py
Moins de code inutile et plus d'aide.

**Comment by destroyxx** [comment]
Merci beaucoup, je vais voir ça :)

**Comment by destroyxx** [comment]
Quelle est la fonction qui afficher les liens du film ?

**Comment by TmpName** [comment]
Dans le dernier fichier c'est la fonction ShowHosters()
>>oGui.addMovie(SITE_IDENTIFIER, 'showHosters', sTitle, '', sThumb, '', oOutputParameterHandler)

**Comment by destroyxx** [comment]
Merci. Donc je dois également changer le sPattern de la fonction ShowHosters ?

**Comment by destroyxx** [comment]
J'ai compris un peu comment cela fonctionne pour le ShowMovie. (Cela ressemble un peu a du java). Mais pour le ShowHoster j'applique exactement la même méthode (Les outils que vous donnée dans ajouter_source) mais je ne comprend pas pourquoi il m'affiche toujours pas les liens vidéo pour les lancer dans kodi. 
[streamay_com.zip](https://github.com/Kodi-vStream/venom-xbmc-addons/files/573284/streamay_com.zip)

**Comment by TmpName** [comment]
Essaye ca http://pastebin.com/gZiAUty5

**Comment by destroyxx** [comment]
Merci ça marche. J'ai également réussi a mettre la fonction qui permet de passer les pages. Est-ce que la fonction def GetLink() s'adapte à tous les sites ? Comment vous avez procédé pour trouver cela |  sPattern = 'code":"([^"]+)'  |   C'est par rapport à quoi que vous vous êtes basé pour trouvé le sPattern ? Et encore merci pour le code.

**Comment by TmpName** [comment]
J'utilise httpfox sur firefox, j'ai juste clique sur un film et regarde le contenu du fichier
eg htt p://streamay.com/streamer/15689/allvid

**Comment by destroyxx** [comment]
Merci pour ton aide. Je trouve que la partie showHoster est la plus dur. Je commence a maitrisé les pattern (regex).

**Comment by TmpName** [comment]
Si tu l'as fini, ca nous interesse aussi, met ton nom en auteur et poste le lien ici, on la rajoutera en officielle.

**Comment by TmpName** [comment]
Heu perso je la trouve pas mal cette source, moi ca m'interesserait de la rajouter dans Vstream, attend un peu avant de cloturer stp.

**Comment by destroyxx** [comment]
Désolé, je n'ai pas su le finir à cause de l'école...

**Comment by TmpName** [comment]
Ok , pas de soucis, c'etait juste pour avoir des nouvelles, vu qu'elle est deja pas mal avancee.

**Comment by LordVenom** [comment]
up ?

**Comment by TmpName** [comment]
Lol, au pire on cree un repertoire "A_Finir" dans le dossier site de la beta, et on la met dedans  ?
Car la j'ai pas le temps, et y a une nouvelle source tout les jours, donc y a pas urgence.

**Comment by LordVenom** [comment]
C'est juste pour pas clôturer et voir si @destroyxx  et toujours la. 
Si tu veut garder une trace de la source il vaut mieux en faire une copie sur la bêta oui.Les sujets nouvelle source sont trop nombreux et ça m’embête de clôturer une source déjà travailler.

**Comment by TmpName** [comment]
Pareil.
Source mise dans le dossier "non_finie" du dossier site.

**Comment by johngf** [comment]
tu jetteras un oeil @destroyxx je l'ai finis
