### ISSUE TITLE
Choix page ?

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#641]
bonjour , vstream a t'il une fonction non active pour le choix de page 
exemple : il y a 50 page je veux aller directement a la 25 >> clic droit sur next >> la popup >> aller a la page >> une popup pour entré le n° >> ok >> page 25
dans gui il y a bien def selectpage(self): mais je ne sais pas si c'est la function ?

**Comment by TmpName** [comment]
C'est tombe a l'abandon, car peu utile et chiant a mettre en place.
En fait c'est au fichier site de gerer ces fonctions, de la meme maniere que le Nextpage. Et je ne me souvient plus quel etait le site qui gerait ces fonctions.

**Comment by johngf** [comment]
A ok sinon de mettre en favoris le numero de page en favoris ça devrait etre possible simplement pour revenir directement la ou on c'est arreté actuellement ça dit impossible de mettre en fav je ne sais pour quel raison pourtant il y a une url

**Comment by TmpName** [comment]
Je viens de faire une modif, now tu peux rajouter le "next page" en favoris mais uniquement si le site utilise addNext() et non pas Addmisc pour ce lien.

Par contre dans les favoris, ca affiche "Next >>>" pour se souvenir de ce que c'est .....

**Comment by johngf** [comment]
Merci ça fonctionne la page est ajouté au fav de kodi en faite c'etait pour la recherche visuel pour eviter d'avoir a cliquer autant de fois sur next pour revenir a la page ou j'etais la veille

**Comment by johngf** [comment]
bon ben c'est ok mais les thumbs des films sont plus petites depuis la modifs

**Comment by TmpName** [comment]
Ha merde.
A quel moment ? Dans showmovies() on utilise  oGui.addMovieDB() donc normallement c'est pas celle la qui doivent chnager.
Il faudrait utiliser oGui.addMovieDB a la place de oGui.addDir la ou ca deconne.

**Comment by johngf** [comment]
Au moment de l'affichage des thumbs elle sont plus petites pourtant mode miniatures

**Comment by TmpName** [comment]
C'est pas plutot le mode d'affichage qui a change ?

**Comment by johngf** [comment]
Oui voila c'est toujour en mode miniatures mais les thumbs sont plus petite

**Comment by TmpName** [comment]
J'ai trouve c'est un bug de Vstream.
On declare une fois la focntion 
>oGui = cGui()
puis plusieurs fois
> oGui.addMovieDB
puis 1 fois
>oGui.addDir
Et enfin 
>oGui.setEndOfDirectory()

Donc sans la modif oGui.addDir recupere le status de film de oGui.addMovieDB, et avec la modif quand je valide le Gui, ca se valide avec le status de fichier (de addDir).
En fait pr bien faire faudrait ajouter 1 oGui = cGui() et 1 oGui.setEndOfDirectory() dans le next page, trop lourd, le mieux c'est de corriger la fonction Gui().

**Comment by TmpName** [comment]
Bon j'ai fait la modif, et en prime tu vas recuperer dans la fonction Showmovies() une nouvelle valeur "SelPage" si tu as selectionne une page.

**Comment by johngf** [comment]
la ça fonctionne nickel par contre j'ai pas compris "tu vas recuperer dans la fonction Showmovies() une nouvelle valeur "SelPage" si tu as selectionne une page"

**Comment by TmpName** [comment]
>sSelPage = oInputParameterHandler.getValue('Selpage')

Qui est soit a None, soit la page que tu as selctionne, si tu utilises la fonction pour choisir la page.
Mais je t'avous, j'ai pas teste, en fait j'etais partis sur une fonction ShowPage() qu'on aurait pu mettre dans tout les fichiers sites (si besoin) mais j'ai pas trouve. Du coup j'ai laisse que cette partie pour le moment.

**Comment by johngf** [comment]
ah ok je pensais a cette fonction la mais j'étais pas sur

**Comment by johngf** [comment]
parcontre la fonction ajouter ala playlist elle fait quoi au juste ? j'ai ajouté 2 film mais aucune playlist trouvé

**Comment by TmpName** [comment]
Bonne question ^^.
M'en suis jamais servis, ca rajoute rien dans les favoris de kodi ?

**Comment by johngf** [comment]
non rien j'ai cherché partout peut etre qu'il faut d'abord en crée une je ne sais pas

**Comment by TmpName** [comment]
L'icone en forme d'etoile ?

**Comment by johngf** [comment]
non ça c'est pour les signets je parlais de la liste de lecture normalement si on ajoute a la playlist elle devrait etre la mais non

**Comment by LordVenom** [comment]
Logiquement tu as la playlist dans le menu gauche avec le choix de la vue

**Comment by johngf** [comment]
Merci, effectivement les videos ajoutés sont visible depuis le menus gauche et jusqu'au rédémarage de kodi

**Comment by johngf** [comment]
Pour ce qui est du showpage la popup s'affiche bien ajouté un num ne fonctionne pas on arrive a la page 2 mais il y a peut etre moyen de le faire fonctionné 
url + num et retour url num -1 la le retour nous envoie sur home
Je testerai ça

**Comment by TmpName** [comment]
En fait pr le faire fonctionner, il te faut faire tout le code de gestion dans le fichier site ou tu veux t'en servir.
Ca reaffiche la meme page mais avec un parametre en plus qui peut te permettre de chnager la page.

**Comment by LordVenom** [comment]
Pour la navigation de page voir oGui.addNext

**Comment by johngf** [comment]
Bon pour l'instant j'ai reussi a aller a la page voulu mais pas comme je le souhaiterai
Quand je clique sur entrée apres avoir entrer le num ça me crée un deuxieme next qui est un racourcis vers la page alors que je veux aller direct a la page en cliquant sur entrée
C'est en cours...

**Comment by TmpName** [comment]
Mais tu bidouilles quel fichier ?
Normallement avec le dernier code, juste avec le fichier site c'est possible.

**Comment by johngf** [comment]
bah le fichier site mais j'ai pas eu le temps d'appronfondir j'ai eu une coupure de courant pendant 2 jours a cause d'une fuite d'eau enfin bref je vais voir

**Comment by johngf** [comment]
j'ai avancé un peu la dessus j'utilise showmovie pour aller a la page voulu me reste un soucis de la page précédente qui n'ai pas mémorisé vu que je n'utilise pas oguiaddnext donc je retourne sur home a chaque fois il y a une fonction qui gère la page précédente ? ou on doit forcement passé par ogui.addnext

**Comment by LordVenom** [comment]
J'arrive pas a te suivre la, les ... au debut de ligne te ramene toujours a la page précedente. pour faire une navigation de page y a des exemple sur d'autre site ont utilise une variable page que l'on passe en out

`    iPage = 1
    if (oInputParameterHandler.exist('page')):
        iPage = oInputParameterHandler.getValue('page')`

`            iNextPage = int(iPage) + 1
            oOutputParameterHandler = cOutputParameterHandler()
            oOutputParameterHandler.addParameter('siteUrl', sUrl)
            oOutputParameterHandler.addParameter('page', iNextPage)`

**Comment by TmpName** [comment]
En fait j'ai fais une modif sur le fichier gui, plus de variable en out (pas que ce soit compatible sur tout les fichiers site).
Maintenant en cas de selection de page, on se retrouve sur la meme fonction mais avec une valeur en plus "SelPage".

Par defaut tu es a shwomovies et "SelPage" = '', si tu as selectionne une page tu te retrouves sur Showmovies mais avec "SelPage" = 5 par exemple.

Donc pour choisir la page, il suffit de modifier le fichier site, et de modifier l'url a la volee juste avant de charge rla page.

**Comment by johngf** [comment]
de la page 1 je clique droit sur next puis selectionner page entre le numero dans la popup puis ok j'arrive a la page du numero 
mais pour l'instant les ... me ramène sur home
par contre next fonctionne
edit : il faut donner une url de retour

**Comment by LordVenom** [comment]
Dans la function viewback de gui y a xbmc.executebuiltin('XBMC.Container.Update(%s, replace)' % sTest )

normalement le replace supprime l'historique donc ça serais normal, mais même sans ça fonctionne pas donc je sais pas dsl

**Comment by LordVenom** [comment]
@TmpName  pas vue passer cette modif tu peux donner un exemple voir commenter ton code stp

**Comment by TmpName** [comment]
Lol, ben justement, j'avais commence en essayant de creer une fonction  ShowPage() qui serait dans chaque fichier sites et qui serait appelle par le fichier gui, mais ca a pas marche, du coup me suis rabattu sur cette solution, mais j'ai jamais fini.
Mais ca devrait ressembler a 

```
def showMovies(sSearch = ''):
     oInputParameterHandler = cInputParameterHandler()
     sSelPage= oInputParameterHandler.getValue('SelPage')
     sUrl = oInputParameterHandler.getValue('siteUrl')

    if (sSelpage):
           sPattern = '?page=([0-9]+)'
           aResult = re.search(sPattern,sUrl)
           if aresult:
                  sUrl = sUrl.replace(aResult.group(0),'?page=' + str(int(sSelpage))
                 
```

**Comment by johngf** [comment]
une question pour @TmpName j'ai un petit soucis avec notepad++ il me décale légérement le code comment le configure tu ? j'ai essayé plein de truc sans succés

**Comment by TmpName** [comment]
Si j'ai bien compris ta question, il y a une option pour convertir les tab en espace, et une pour l'activer par defaut.
A chaque pression sur la touche tab, ca me fait 4 espaces au lieu d'un tab.

Sinon ca deconne lors de copier/coller ?

**Comment by johngf** [comment]
en faite quand j'ouvre un fichier il est légèrement décalé vers la gauche et oui quand je colle sur github c'est décalé (rajoute des espaces)
j'ai essayé identation auto ,insérer espace a la place des tabs , langage python rien y fait la seul manière qui fonctionne a peut près c'est de choisir langage msdos style puis language python

**Comment by TmpName** [comment]
Encodage UTF-8 sans BOM ?
Essayes de reset la config.

**Comment by johngf** [comment]
en faite j'ai réinstallé notepad ++ est me suis aperçu que c'est le theme Obsidian qui crée ça si on demarre notepad avec ce theme par defaut

**Comment by TmpName** [comment]
Lol, il y a plein de truc obscur sur cette appli.
Une fois j'ai modifier la taille de la police (en fait c'est plutot le chat en marchant sur le clavier) et impossible de revenir en arriere, la molette de la souris ne marchait pas, par le menu non plus, oblige de tout re initialiser

**Comment by johngf** [comment]
Du coup a partir du theme de base vu que je n'ai trouvé le bug j'ai refait obsidian ça fonctionne nickel maintenant

**Comment by LordVenom** [comment]
J'utilise aussi notepad++ mais je vais surement passer sur https://atom.io/.

**Comment by TmpName** [comment]
On m'en parle souvent, tu l'as teste ?
C'est aussi leger que notepad++ , vu que c'est ma raison premiere pour ce choix.

**Comment by LordVenom** [comment]
J'utiliser notepad++ pour la seul raison qu'il pouvais ouvrir le fichier .log de Kodi sans planter sublime_text par exemple n y arriver pas et la avec Atom pas de soucis non plus.

**Comment by johngf** [comment]
j'ai trouvé la solution je pense c'est tellement bete que je n'y ai pas pensé
xbmc.executebuiltin('XBMC.Container.Update(%s, replace)' % sTest )
par
xbmc.executebuiltin('XBMC.Container.Update(%s, '')' % sTest )
c'est le replace le probleme

**Comment by LordVenom** [comment]
Bizarre j'avais tester pourtant voir mon message de 4jours.

**Comment by johngf** [comment]
Oui mais pas dans la function viewback jai modif def selectpage

**Comment by TmpName** [comment]
Bon j'ai encore un prb avec notepad++.
Le fichier aadecode.py, sur un ordi il s'affiche correctement, sur l'autre j'ai des symboles bizarres.
Y en a un qui se souvient de la manip ?

**Comment by johngf** [comment]
C'est pas retour a la ligne auto ?

**Comment by TmpName** [comment]
Nope.
Essaye avec la chaine de caractere de cette page http://superuser.com/questions/576431/notepad-inserting-special-unicode-characters-in-utf-8 3 eme post, sur un ordi sa s'affiche bien, sur l'autre j'ai que des carres.

**Comment by TmpName** [comment]
Bon en fait je crois pas que ce soit notepad++ le probleme, mais windows, doit me manquer une police.
Meme dans notepad tout con j'ai le meme probleme.

En fait je suis en train de coder un truc qui permet de lire un code javascript en python, ca marche nickel pour openload, pour le jspacker, mais quand j'ai voulu tester le aadecode, me suis prit un crash par la gueule a cause du codage.

**Comment by johngf** [comment]
j'ai quelque carré sur notepad ++ aussi

**Comment by johngf** [comment]
pour le choix page j'ai fait un 1er test avec film vostfr http://pastebin.com/Wuft4Uef
il faut enlever le replace dans def selectpage ça a l'air de fonctionné

**Comment by LordVenom** [comment]
Ok la function et buguer quand tu rentre un numero de page ça avance juste la page de 1 il me sembler que ça fonctionner.

Faut juste réparer cette function on vas pas en creer une nouvelle.
vas au plus simple si la page existe pas tu reload le site ou tu affiche une erreur et op.

**Comment by johngf** [comment]
sur le pastebin du dessus ça fonctionne 
je viens de testé "selectpage en selectpage2 et selectpage2 en selectpage" est ça fonctionne de la meme manière sauf pour la verif que la page existe elle n'est pas prise en compte donc le selectpage actuel est ok
si on enleve le replace

**Comment by johngf** [comment]
version corrigé le pattern de GetLastPage change en cour de route donc on utilise le titre 
film nouveautés(745p) ,serie nouveautés(93p) ,anim nouveautés(50p) ok
http://pastebin.com/raw/FPmAhKft

**Comment by TmpName** [comment]
Honnettement fait au plus simple, pas besoin de faire un controle de la derniere page.
Quand ca marche plus c'est que tu as ete trop loin, l'utilite c'est de reprendre ou tu t'arrettes, pas de choisir de commencer a la page 40 sur 200.

**Comment by johngf** [comment]
yé bon j'ai trouvé la solution

**Comment by johngf** [comment]
bon en faite @LordVenom avait raison je ne sais pas pourquoi ça n'as pas fonctionné la 1ere fois que j'ai testé en inversant selectpage et selecpage 2 c'est ok
choix page et mettre en favoris le next sur la recherche visuelle

**Comment by johngf** [comment]
bon j'ai réussi a le faire fonctionné sur filmvostfr et filmstreamco en utilisant le meme principe que
sNextPage = __checkForNextPage(sHtmlContent) toujours en checkant la derniere page 
sLastPage = __checkForLastPage(sHtmlContent)

`        sNextPage = __checkForNextPage(sHtmlContent)
        if (sNextPage != False):
            sLastPage = __checkForLastPage(sHtmlContent)
            oOutputParameterHandler = cOutputParameterHandler()
            oOutputParameterHandler.addParameter('siteUrl', sNextPage)
            oOutputParameterHandler.addParameter('lastPage', sLastPage)
            oGui.addNext(SITE_IDENTIFIER, 'showMovies', '[COLOR teal]Next >>>[/COLOR]' , oOutputParameterHandler)`

**Comment by TmpName** [comment]
Ben je me repete mais franchement sachant qu'on va devoir le faire pour chaque site, je trouve vraiment que de gerer la derniere page c'est en trop.
Ca augmente les calculs, les interaction avec le fichier GUI, juste pour afficher un depassement qui risque de ne jamais arriver (la plupart des sites ont 200 pages, qui va aller aussi loin.)
