### ISSUE TITLE
ajout d'une source 

### ISSUE THREAD

**Issue by s1994** [Kodi-vStream/venom-xbmc-addons#645]
Bonjour.

je voudrai ajouté se site pour mais source vstream ht tp://filmvf.ws/  
 j'ai essayé de le faire moi-même mais je n'ai pas réussi.

Merci d'avance pour votre aide .

**Comment by TmpName** [comment]
Donnes toujours la ou tu en es (en passant par pastebin par exemple) et explique la ou tu bloques.
Je doutes que tu trouves quelqu'un pour te faire la source complete depuis rien du tout.

**Comment by s1994** [comment]
bonjour
je n'y connais vraiment rien a la programmation, j'ai cherché un tuto dans les issue et j'ai trouvé qu'il fallait passait par la pour commencé https://github.com/LordVenom/venom-xbmc-addons/blob/master/ajouter_une_source.py 
ensuit je ne sait vraiment pas quoi faire.
pouvaient vous me montré la marche a suivre 
merci d'avance
