### ISSUE TITLE
Zone-Telechargement

### ISSUE THREAD

**Issue by nirmou72** [Kodi-vStream/venom-xbmc-addons#646]
Bonjour, tout d'abord un grand merci pour votre plugin

Je me demandais s'il etait possible de pouvoir rajouter une rubrique par date de sortie des films comme c est propose sur le site de zone telechargement.

Cela permettrais de trouver des films recents qui ne sont pas forcement dans la rubrique "films les plus vus", parceque dans la rubrique "derniers films ajoutés" on ne trouve pas forcement de film recents.

Je sais pas si c est possible de faire ca (par un newbie comme moi) ou si pour vous ca serai faisable facilement ? 

merci pour aide

**Comment by chataigne73** [comment]
où se trouve la rubrique par date de sortie des films à laquelle tu fais allusion sur le site de ZT ?

**Comment by nirmou72** [comment]
sur cet url

http://www.zone-telechargement.com/films-gratuit.html?tab=all&orderby_by=rlsdate&orderby_order=desc

**Comment by chataigne73** [comment]
j'ai fait la modif sur la beta
pas encore testé

**Comment by nirmou72** [comment]
Merci beaucoup ca fonctionne nickel, j'ai du coup un peu mieux compris avec ta modif.

j'ai changé l'url par celle là : 

films-dvdrip-bdrip.html?tab=all&orderby_by=rlsdate&orderby_order=desc 

en limitant l'affichage pour les dvdrip et bdrip comme les doublons s'affiche moins voir pas du tout mais reste accessible lors du choix des sources 

MERCI BEAUCOUP

**Comment by chataigne73** [comment]
En effet j'avais à un moment pensé faire ça aussi pour éviter les doublons, car en principe ya toujours le dvdrip pour un film également présent en hd.

**Comment by nirmou72** [comment]
bonjour à tous, j'ai une autre question toujours concernant Zone telechargement

je cherche à savoir comment avoir le resumé des films dès le choix dans la liste d'une rubrique, car ce n'est pas le cas.

Exemple : dans "films les plus vus" en affichage "list" on ne voit que le fanart en grand, il faut choisir le film et selectionner une sources pour avoir le resumé.

je me demandais si il y avait moyen de pouvoir changer ça et de voir directement les resumés

**Comment by TmpName** [comment]
Nope, on ne l'a pas mit en place car le regex devenait tres lourd, lent et instable.
Il faudrait recoder l'ensemble avec un autre systeme pour avoir quelque chose de sur.

Par contre tu parles des affches ou vraiment du fanart ? Car si tu as les metas datas actives dans le second cas si le scrapper recuperer le fanart il recupere aussi le resume, et donc ont devrait pouvoir utiliser celui la.

**Comment by nirmou72** [comment]
Je parle des affiches (même si je croyais que c'était la même chose).  Je suis pas sur d'avoir été clair. Il y a t il moyen de joindre des images pour vous montrer sur le forum pour mieux expliqué

**Comment by TmpName** [comment]
Nope j'ai compris, et donc c'est bien ce que je disais.
C'est techniquement possible, mais on ne l'a pas fait car ca provoquerait plus de bug/lenteur que ca apporte comme plus, pour le moment ce n'est pas en projet (enfin pas a ma connaissance).

**Comment by nirmou72** [comment]
Ok merci pour ton aide
