### ISSUE TITLE
real debrid ? 

### ISSUE THREAD

**Issue by hakoupo13** [Kodi-vStream/venom-xbmc-addons#650]
bonjour avez vous une solution pour utiliser real debrid avec les liens uptobox ? merci

**Comment by johngf** [comment]
As tu urlresolver installé et activé regarde ici #332

**Comment by LordVenom** [comment]
Résolut ?

**Comment by hakoupo13** [comment]
non j'ai vu : 


Bon j'ai rajoute sur la beta (pas contre faudra DL tout le pack, y a des fichiers partout), dans la partie premium une case a cocher pour passer par UrlResolver.
Tu coches la case et configure l'UrlResolver, donc tu pourras utiliser les Debrideurs.

Par contre Vstream ne gere pas du tout cette partie, eg Youwatch n'a pas l'air de marcher.

A tester, mais ca a l'air bon.

j'ai pas de case dans votre plugin et quand je met urlresolver sa donne rien .

si on stream via uptobox des restrictions sont faites à l'heure ou autre ?
un épisode par heure fin si vous savez ?

merci pour votre rapidité de réponse , bonne soirée .

**Comment by TmpName** [comment]
Dans les parametres de Vstream (pas de kodi), onglet "premiun/login", tout en bas

Et oui il y a des restrictions
Sur uptobox, une fois que tu as lancer une video (meme si tu l'arrette de suite), tu dois attendre un certain temps pr recommencer.
Sur uptostream 1h30 par jours sans login 3h avec login gratuit.

**Comment by hakoupo13** [comment]
il y a rien je comprends pas regarde :          http://img11.hostingpics.net/pics/542473vstream.jpg

pourtant j'ai la dernière version ..  0.4.6 

merci

**Comment by johngf** [comment]
c'est normal il faut naviguer avec les onglet du haut

**Comment by hakoupo13** [comment]
merci je cliquais sur fleche de droite en haut et j'avais rien je me suis servit de la touche du clavier droite et là j'ai tout ! 
désolé pour le dérangement bonne soirée , résolue !
