### ISSUE TITLE
Reprise film en cours

### ISSUE THREAD

**Issue by rod93** [Kodi-vStream/venom-xbmc-addons#651]
Bonjour
Depuis plusieurs jours lors de la reprise de lecture d'un lien vstream ne me propose plus de reprendre la lecture.
Avez vous constaté ce problème ?

**Comment by TmpName** [comment]
Heu, arf je crois qu'on a un prb ^^.

Bon alors, on a modifie le code de Vstream lors de la derniere MAJ (qui gere justement cette partie).
Il nous faudrait ta version de kodi et ton OS.
Normallement on a desactive la reprise par Vstream, donc uniquement celle par kodi fonctionne.
Essaye avec un fichier local, pour voir si ca ne vient pas des reglages de kodi.

**Comment by LordVenom** [comment]
Des nouvelles ?

**Comment by rod93** [comment]
Désolé oui la reprise fonctionne bien dans kodi en local

**Comment by LordVenom** [comment]
Sa vas être dur de comprendre sans tes réponses a @TmpName

**Comment by rod93** [comment]
Kodi 16.1 sur Android 6.1desole

**Comment by TmpName** [comment]
Lol. Pas de soucis.
Enfin presque, je viens de retester, pas de soucis chez moi.
J'ai pris un film au hazard sur openload, je me suis mit a 50% du film, j'ai ferme.
Retour sur Vstream avec le temps ou je me suis arrette qui s'affche a droite du nom de la selection (avec le petit triangle)
Je le relance, et ca me demande dans un petit popup si je veux reprendre ou pas, petit popup, celui de Kodi avec juste 2 lignes et l'affichage tronque a 60%.
