### ISSUE TITLE
Inclure vstream dans bibliotheque

### ISSUE THREAD

**Issue by Stefle33** [Kodi-vStream/venom-xbmc-addons#652]
Bonjour, 

Existe-t-il une solution quelconque pour inclure les films dispos dans Vstream (plus précisément la source ZT)  dans notre catégorie film de kodi et les séries Tv dans la catégorie de Kodi qui porte également le même nom.

Le but serait de pouvoir retrouver nos films et séries favorites avec les résumés et jaquettes comme avec ses propres films.

Merci par avance de vos réponses

**Comment by LordVenom** [comment]
Depuis les Hosts (openload ect..) ajouter a la librairie, il te faut ajouter le dossier film et series de vstream voir paramètre (librairie) de vStream dans tes dossiers sources de films et series.

**Comment by Stefle33** [comment]
Bien reçu merci, par contre je ne comprend pas la partie sur : 

"depuis les hosts ... ajouter a la librairie..."

car quand je suis sur un film, puis clic droit, je peux ajouter aux marques pages mais non a la libraire

**Comment by Stefle33** [comment]
Correction, j'arrive bien a ajouter mon film dans ma librairie c'est bon ^^

J'ai ajouter le source qui maintenant ce synchronise avec mon onglet film de Kodi. Cependant à l'ajout d'un film, j'ai un fichier strm qui ne se met pas a jour automatiquement.

Je m'explique, si je vais dans mon onglet film et que je met a jour ma bibliotheque, rien ne se passe, je suis obligé d'aller dans mes fichiers, mon dossier film vstream, cliquer droit sur le fichier strm et trouver manuellement les informations du film.

Pourtant dans les paramètres de Vstream j'ai bien coché la case mise a jour à chaque ajout pour la librairie.

**Comment by Stefle33** [comment]
Bon dernier message pour conclure mon sujet, le problème devait venir que sur certains films car maintenant tout fonctionne correctement.

Merci pour ta réponse LordVenom, bonne journée
