### ISSUE TITLE
Flash X erreur

### ISSUE THREAD

**Issue by Turk182es** [Kodi-vStream/venom-xbmc-addons#653]
Salut,

C'est encore moi et mes problèmes de Flash X, depuis aujourd'hui lorsque on lance une série sur flash X, il y a un message de 30 seconde nous demandant d'enlever l'anti Pop Up et de recharger la page. Chose impossible depuis OSMC par exemple ... une idée ?

**Comment by TmpName** [comment]
Yep, on vient de s'en apercevoir aussi ^^.
M'en occupe dans la soiree.

**Comment by TmpName** [comment]
Mit a jour, merci pr le signalement.

**Comment by Turk182es** [comment]
WOAW! Sacré support! Encore merci pour votre aide et votre super efficacité ! 

Cordialement.
Stephane
