### ISSUE TITLE
Capcha Kodi 17

### ISSUE THREAD

**Issue by Smog418** [Kodi-vStream/venom-xbmc-addons#654]
C'est une question de newbie, j'en conviens, mais où trouve-t-on les capcha à inscrire dans kodi pour les sources de zone-telechargement? J'arrive au tableau pour l'inscrire et j'ai pas l'info. 

J'ai un compte real debrid que j'ai inscrit dans le urlresolver.

**Comment by johngf** [comment]
normalement il doit s'affiché a l'ecran tu as quel version de kodi ? 16 ou 17

**Comment by Smog418** [comment]
17

**Comment by johngf** [comment]
le captcha ne fonctionne pas pour l'instant avec kodi 17

**Comment by Smog418** [comment]
Ha! Zut🙁 désolé!

**Comment by Sph1re** [comment]
@Smog418 +1

A partir de quand le code ne risque-t-il plus de changer? en phase RC?

**Comment by TmpName** [comment]
La phase RC est aussi une phase de developement pour tester l'appli, mais c'est celle qui s'approche le plus de la version publique.
