### ISSUE TITLE
Astuce démarrage auto vstream au lancement de kodi

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#657]
salut
ceci n'est pas une issue, mais un partage d'astuce

pour lancer automatiquement vstream lors du lancement de kodi, créer un fichier nommé autoexec.py dans le répertoire userdata de kodi et y mettre
`xbmc.executebuiltin("RunAddon(plugin.video.vstream)")`

encore plus fort : pour lancer automatiquement vstream sur un site en particulier (dans mon exemple zone_telechargement) mettre
`xbmc.executebuiltin("ActivateWindow(10025,plugin://plugin.video.vstream/?function=load&sFav=load&site=zone_telechargement_com,return)")`

voilou, je poste juste ces astuces au cas où certains auraient eu envie de faire la même chose que moi

**Comment by johngf** [comment]
quand zone téléchargement mettra des re-captchas il y en as qui vont pleuré :)

**Comment by TmpName** [comment]
Ils l'ont deja fait, ils ont du trouver ca trop lourd.
Meme pour l'user c'est lourdingue, le proposer une fois pour un enregistrement ok mais toute les heures ou pire a tout les films comme l'autre site, c'est l'enfer.
