### ISSUE TITLE
FlashX actualisation ne marche pas

### ISSUE THREAD

**Issue by Turk182es** [Kodi-vStream/venom-xbmc-addons#658]
Salut,

Je viens d'actualiser VStream sur OMSC et FlashX ne marche toujours, cette fois il nous envoie sur un film en boucle appelé Planet Earth, et cela sur tous les fichiers FlashX essayés.

Voilà, j'espère avoir pu vous aider.

Stephane

**Comment by johngf** [comment]
flashx est mis a jour après jusqu'à quand ça fonctionnera ...?

**Comment by Turk182es** [comment]
Ok merci! J'essaye ça cet aprèm !

**Comment by johngf** [comment]
depuis hier il y a eu du changement j'ai fait un autre modif a testé chez moi ça a l'air de fonctonné
testé sur dallas

**Comment by Turk182es** [comment]
Cool! J'attends l'actualisation avec impaciente alors!
encore merci pour votre support !

**Comment by johngf** [comment]
tu as testé ?

**Comment by Turk182es** [comment]
Ben oui mais c'est toujours pareil ! D'ailleurs VStream ne s'est pas actualisé.
Et FlashX me lance un documentaire sur la Chine sur n'importe lequel épisode de n'importe quelle série :-)

**Comment by johngf** [comment]
oui je viens de voir ça a encore changé ce matin

**Comment by johngf** [comment]
bon en faite des qu'on lit une video sur flahx avec firefox après ça fonctionne dans kodi

**Comment by Turk182es** [comment]
Le problème est qu'avec OSMC sur Raspberry on a pas Firefox :-(

**Comment by johngf** [comment]
on utilise un navigateur internet pour trouver le bon code donc en faite chez moi ça fonctionné parce qu'en testant je vais sur le site de flashx c'est pour cette raison c'est trompeur mais bon moi ou quelqu'un d'autre va trouvé la soluce

**Comment by Turk182es** [comment]
Pas de souci! C'est déjà un luxe, d'avoir un support comme celui la ;-)

Encore merci pour tout!

**Comment by johngf** [comment]
bon j'ai remis l'ancien code a 1 ou 2 détail près c'est le adblock de flashx qui nous empeche d'avoir la bonne video
pour l'instant ....

**Comment by TmpName** [comment]
Yep j'avais vu ca aussi, en fait a chaque essais reussi, il fallait chnager de video, sinon l'ip est memorise et ca marche a chaque fois.
Par contre ca deconne encore chez moi, je re-essaye.

**Comment by johngf** [comment]
Le anti adblock est il y a quelque jour il y avait 2 resultat au niveau de unpack plus maintenant

**Comment by TmpName** [comment]
J'ai fais une modif, mais suis pas sur qu'elle tienne, en fait le faux lien a un caractere en plus.
Donc je compare les liens et prend le plus court.
Si ca marche pas le faux lien a une balise "hidden" (pour ne pas que les gens cliquent dessus)
Si ca ne marche tjours pas, on fera comme pour openload, on bombarde leur serveur avec tout les iens de la page jusqu'a trouver le bon si ils aiment ca.

Pour le unpack, si ca redeconne je pense qu'il suffira de regarder le contenu pour voir lequel est le bon. Mais pareil on prend tout et on fait en sorte que Vstream puisse trouver tout seul lequel est le bon.

**Comment by johngf** [comment]
Oui dans le mauvais il y a fx.99

**Comment by TmpName** [comment]
Ha tiens moi c'etait juste un '1' a la fin de l'url ^^, mais apparement c'est tjours un truc en plus.
Apres je debarque, donc j'ai pas fais autant de tests que toi, mais si ils changent tout les 2 jours faut que l'addon repere tout seul les mauvais liens, il y a plein de moyen pr ca.

**Comment by johngf** [comment]
Je parlais de l'url que vstream essaie de lire en mp4 sinon oui pour l'url de depart c'est pareil que toi un 1

**Comment by johngf** [comment]
j'ai testé et ne fonctionne pas, j'ai testé d'autre truc ne fonctionne pas.
et la modif que tu as fait hier a changé ce matinplus d'url plus petite que l'autre j'ai mis des # sur les changement
le probleme est des le debut on trouve le "(\s*eval\s*\(\s*function(?:.|\s)+?)<\/script>" mais un faux
http://pastebin.com/raw/k1uh16bU

**Comment by johngf** [comment]
j'ai mis une nouvelle version si quelqu'un peut testé chez lui

**Comment by TmpName** [comment]
Ca marche chez moi mais il faudrait rendre le code plus "autonome".
eg La ligne 149 est trop restrictive si le fichier se retrouve sur flashx.org (et ils ont gave d'hebergeur) ca ne marchera plus.
Et il faut trouver un moyen pr differentier les bonne url des mauvaises, vu que la taille ne marche pas apparement.

**Comment by johngf** [comment]
Je vais modifier ça et a ce niveau L149 pour l'instant c'est toujours la 2eme url je faire un test plus poussé

**Comment by TmpName** [comment]
Attend donne moi 10 mn.Je bricole 2 truc
1 - un regex avec hidden and opacity
2 - un scan pr les bonne url.

**Comment by TmpName** [comment]
Bon j'ai mis en ligne.
J'ai modifie le regex qui cherche la bne url (la premiere), j'ai trouve 2 variantes (mais y en a surement plus)
Dans le cas ou elle ne soit pas bonne, passage en mode barbare et je teste toutes les urls.

Reste a faire la partir qui trouve le bon code a unpack, mais la j'ai pas encore eu le probleme.

**Comment by johngf** [comment]
j'ai changé d 'ip et testé ta modif fausse video direct

**Comment by TmpName** [comment]
Put1 j'ai pas ca moi.
Mais ca a pas marche ou tu as eu la video avec les bulles ?

**Comment by johngf** [comment]
oui

**Comment by TmpName** [comment]
Oui les bulles ?

**Comment by johngf** [comment]
exact

**Comment by TmpName** [comment]
Les bulles se debloquent avec la partie "fastcontentdelivery", normallement ya pas d UA avec.
Tu testes avec quel film/site ?

**Comment by johngf** [comment]
sur tv streaming la serie premier baiser mdr et des fois la partie fascontentdelivery renvoie sur une page vide

**Comment by TmpName** [comment]
Lol.
Bon sinon, rien a faire, je peux rien faire de mon cote, ca marche a tout les coups.
Mais pour info si tu ne vas pas sur cette fameuse page > video avec les bulles. et si tu y as ete une fois, c'est foutu, plus jamais les bulles (ca memorise l'ip).

Si la seule solution c'est de chnager l UA, on va le chnager mais j'aimerais savoir pkoi.

**Comment by johngf** [comment]
je teste toujours en changeant d'ip pour etre sur et comme j'ai dit plus haut ils doivent avoir mis des restrictions sur l'user agent de firefox

**Comment by Turk182es** [comment]
Je viens de mettre à jours et maintenant j'ai "Fichier introuvable " sur tous les FlashX

Voilà j'espère avoir pu apporter mon grain de sable.

**Comment by johngf** [comment]
Le probleme est resolu ça fonctionne reste un detail a la prochaine maj ça sera ok

**Comment by TmpName** [comment]
@Turk182es la derniere version a tester est ici
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/hosters/flashx.py

Si  ca ne marche pas, teste avec "Iphone42" a la ligne 16.

En fait j'attendais de savoir pkoi ca marche mieux avec justement "Iphone42" avant de mettre a jour.

Edit: je lance la MAJ on verra demain pr le reste.

**Comment by Kodigoal** [comment]
Après test sous 2 appareils kodi15.2/android même ip publique:
- En laissant 'firefox' ligne 16, j'ai les fameuses bulles sur les 2 appareils.
- En changeant par 'Iphone42' sur un appareil , ca fonctionne , mais pas sur l'autre appareil resté en 'Firefox'  avec même ip publique.

**Comment by johngf** [comment]
oui le soucis viens de la j'ai mis Streamphone5 a la place de Iphone42 pas de bulles

**Comment by TmpName** [comment]
Mais pkoi moi j'ai pas de prb, c'est dingue.
Surtout que ca doit marcher avec firefox, si vous y allez avec le navigateur ca passe. Surement un prb dans le headers de la partie antibulle.

**Comment by Kodigoal** [comment]
Je sais pas xD mais en testant des UA différents , ya que le Iphone (même sans 42 , mis UA = 'Iphone') et Streamphone5 ou ca fonctionne ...
Mais si tu t'amuses a mettre des UA aléatoires  genre UA= 'pouet pouet' , ya les bulles.
Ya pêtre un filtre en place qui laisse passer certains mots et pas Firefox et cie ou nom pas connu du filtre.

**Comment by johngf** [comment]
sinon celui la fonctionne 'Nokia7250/1.0 (3.14) Profile/MIDP-1.0 Configuration/CLDC-1.0'

**Comment by TmpName** [comment]
Bon nouvelle protection, je vais finir par croire qu'ils nous surveille.
Et le mode barbare n'a pas l'air de marcher

**Comment by TmpName** [comment]
Bon encore un mystere
Avec le lien playvid-hjjjhgjhgjjhjgg.html?playvid
Ca marche sans headers avec httprequester mais j'ai un 404 avec urllib avec ou sans headers
Et le premier lien ne marche que si il n'y pas de headers

A tester avec une autre lib que urllib

**Comment by johngf** [comment]
Je jetterai un oeuil demain

**Comment by TmpName** [comment]
C'est bon, ma faute, mes fonction ne gerait pas le httpS.
Par contre y a plein de truc non actives, mais vu  que ca change tout les jours on verra demain.

**Comment by TmpName** [comment]
Bon encore une nouvelle version, ca marche, mais le lien qui debloque la fausse video n'est plus le meme.
Et il n'est plus propre a la video, si on voit une seule video sur le net, elles sont toutes debloquees.
Du coup c'est mort je peux peux plus filtrer.

Pour info je me sert de "tamper data" sous firefox, je bloque toutes les urls, et je les debloque 1 par 1 pour savoir la quelle est celle qui debloque tout.

**Comment by johngf** [comment]
ok  si c'est peut etre un process auto pour changer le liens

**Comment by TmpName** [comment]
Oui, j'ai pense exactement pareil, trop regulier, mais pour le moment, j'ai pas encore vu 2 fois le meme truc, donc je sais pas combien de techniques ils ont code.

**Comment by TmpName** [comment]
Bon ben pas de chnagement, lol, je crois vraiment qu'il y a un pauvre type dont le boulot est de regarder notre github et de changer une ligne de code a chaque fois ^^.

Sinon mes tests de ce soir (vu que je suis bloque pr 24h)
Autorisé:
Tout les liens en flashx.tv (meme si suis sur que tous ne servent pas)
cdn99.fx.fastcontentdelivery (doute sur celui la)
Tout les liens en zoneid=
cdn.cavixoapp... production/platforms/....

Bloque:
flash x.tv/cdn-cgi/
.smartadserver.com

Et c'est tout ca a suffit a debloquer.

**Comment by johngf** [comment]
cdn99fx c'est les fausses videos

**Comment by TmpName** [comment]
Yep mais je sais pas quel lien debloque les videos, et vu que c'est le meme serveur ....
Faudrait voir si on ne bloque que celui la, si ca debloque quand meme la video.

**Comment by johngf** [comment]
j'ai une question HS c'est mieux de faire des requetes ou de passé le sHtmlcontent entre les fonction ?

**Comment by TmpName** [comment]
Ha bon ?
C'est plus rapide de refaire les requetes en double que de passer le code html entre fonctions ?

**Comment by johngf** [comment]
Bah sur siteupto.py sur une version optimisé mais pas publié avant de passé par premium handler version actuelle
C'etait moin fluide en envoyant la page entre les fonctions

**Comment by johngf** [comment]
ils ont encore changé ?

**Comment by TmpName** [comment]
Yep, ils ont declare la gueurre a kodi ^^.
Ils vont chnager tout les jours, don va falloir faire un systeme de MAJ comme pour urlresolver.

La version actuelle ne marche pas encore, j'ai pas le temps de trouver l'url qui debloque tout. Je laisse chercher les autres :).
Celle en ligne necessite de se connecter 1 fois sur navigateur, et apres de tout laisser tourner toute la journee pour bouffer leur bande passante.

**Comment by johngf** [comment]
je viens de jeter un coup d'oeil un flash x effectivement meme avec la bonne url ça fonctionne uniquement si ta lancé une vid sur leur site

**Comment by TmpName** [comment]
Yep, mais la j'ai pas trop le temps, donc je laisse de coter pr le moment, en fait la je lance une video juste avant d'allumer la machine du salon ^^.

**Comment by johngf** [comment]
Je vais jeter un oeil demain par contre le code que tu as ajouté n'est pas utilsé il est indispenssable ?

**Comment by Kodigoal** [comment]
Je suis largué pour aider sur les hosters xD
Vais essayer de comprendre pour aider mais c'est pas gagné ..

**Comment by TmpName** [comment]
Nope, il est pas encore utilise ^^.
C'est prevision de leurs futures modifs, il y a plein de bout de code, il y en a un qui sera capable de lire tout les liens de la page et d'y aller, de relire les nouveau lien et ect ... (pour trouver le lien qui debloque les pubs)

**Comment by johngf** [comment]
bah en faite l'ancienne version fonctionne trés bien avec 2-3 petite modif

**Comment by TmpName** [comment]
Tu es sur quelle fonctionne ? Il faut attendre 24h si ca marche une fois, a cause de l'ip memorisee. Moi la derniere marche tres bien. Tu as teste quelle version ?

**Comment by johngf** [comment]
Celle sur la beta elle fonctionne pas chez moi j'ai repris l'ancienne avec iphone42 et modif 2 3 truc pour voir est ok

**Comment by TmpName** [comment]
Ha oui, le coup de l'user-agent, ca j'ai tjours pas compris pkoi, chez moi j'ai tjours pas de prb.

Change la, si tu veux, v mettre la prochaine en brouillon dans le dossier trash.

**Comment by TmpName** [comment]
Autant pour moi, ils viennent de le remodifier.

Je remet en ligne un version avant que tu bidouilles les user-agent stp.

**Comment by johngf** [comment]
dans get id from url ils sont en https maintenant

**Comment by TmpName** [comment]
Ha merde je corrige ca.

**Comment by johngf** [comment]
bon j'ai fait un essaie avec ta dernière modif > bulles | changement UA > ok

**Comment by TmpName** [comment]
Yep, ma derniere modif c'est pour virer la fausse video sur son "voyage en chine", moi j'ai encore les bulles sauf si je vais voir une video sur firefox.

J'ai pas teste le changement d UA sans aller voir de videos, mais je doute que cela suffise a virer les bulles, vasis tester ce soir.

**Comment by johngf** [comment]
Fx99 les bulles et autres

**Comment by TmpName** [comment]
XD, bon je viens de tester avec le header de nokia, plus de bulles ^^.
Du coup on va laisser ca pour le moment le temps de trouver comment debloquer pr firefox :)

Merci, je fais 2/3 tests et je le met en ligne avant 21h.

**Comment by johngf** [comment]
Il faut peut etre un test pour voir si c'est réellement firefox ?

**Comment by TmpName** [comment]
Ou alors le nokia doit mal gerer les pubs, et ils laissent passer en se disant que c'est un bug.
Mais avant de mettre en ligne j'ai peut etre trouve, ca a marche avec le UA firefox, mais ca veut rien dire vu que ca marche chez moi et pas chez toi.
Mais si avec l UA de nokia ca tourne, on laisse comme ca pr le moment, en fait tu avais raison des le debut, meme si c'est dommage de ne pas trouver la parade avec firefox.
Apres ca va pas durer, ils ont prevu de changer tout les jours.

**Comment by johngf** [comment]
@Turk182es ça fonctionne chez toi?

**Comment by Turk182es** [comment]
Ben j'ai essayé encore il y a deux jours et non ...Fichier introuvable. Par contre j'ai pas eu d'actualisation.

**Comment by johngf** [comment]
Des que tu as la maj dis nous si c'est ok

**Comment by Turk182es** [comment]
Salut,

Alors le FlashX marche maintenant mais par contre dans l'Add On le menu est vide :-)
Je peut voir plus ou moins ou je suis grâce aux icônes sur la droite mais les textes (search, film, TV Show etc...) on disparus ... c'est vide :-(

**Comment by johngf** [comment]
Tu as essaye de redemarré parceque chez moi c'est ok

**Comment by Turk182es** [comment]
Oui 3 fois :-( ... c'est vraiment bizarre :-/

**Comment by Turk182es** [comment]
Je viens de changer la langue à Français et toujours pareil ... vraiment bizarre

**Comment by johngf** [comment]
Sur tous vstream tu as des page vide ?

**Comment by Turk182es** [comment]
Que sur le menú principal, si je rentre dans une section c'est bon.

**Comment by johngf** [comment]
sur osmc as tu le theme de base de kodi ?

**Comment by Turk182es** [comment]
Oui oui ! J'ai jamais changé de thème

**Comment by johngf** [comment]
dans les parametres de vstream essaye de desactivé les sites ddl island zon tel .eu ensuite tu met mode liste avec le volet sur ta gauche

**Comment by Turk182es** [comment]
Excuse moi  mais j'ai peur de pas bien saisir le suivant : "desactivé les sites ddl island zon tel .eu" :(

**Comment by johngf** [comment]
dans les parametree de vstream fonction plugin on off tu peut activer ou desactiver les sites

**Comment by Turk182es** [comment]
Ok, ce soir je regarde ça! Merci pour ton aide!

**Comment by TmpName** [comment]
Oui il y a le probleme de cache, la page home de Vstream est mise en cache sur certain systeme, ce qui fait que meme en chnageant la langue ca met plusieurs jours a se mettre a jour.
Now j'ai la technique, dans les parametres de Vstream > outils > vider le cache de Kodi.

**Comment by johngf** [comment]
@Turk182es  tu doit avoir une partie dans une autre langue dans kodi verifie #748 tous doit etre en fr ensuite vide le cache

**Comment by Turk182es** [comment]
Bon ben c'est tout revenu sans rien toucher :-) et FlashX marche :-)
On peut fermer le ticket!
Encore une fois du super boulot ! Vous êtes vraiment au top ! Encore merci !

**Comment by johngf** [comment]
Ok si jamais flash x redeconne signale le nous
