### ISSUE TITLE
top 1000 imdb

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#659]
Je travail pour finire ce script depuis plusieurs jour,mais j'ai trouvée un problème sur le resultat final de la recherche qui affiche une page qui n'a rien de rapport avec le titre du film de la recherche?!!!!.....

http://pastebin.com/5cS9JY85

**Comment by TmpName** [comment]
Quant tu lances une recherche via le menu :
1 - tu passes par showSearch()
2 - tu fabriques l'url : h tp://imd b.com/search/title?groups=top_1000&sort=user_rating,desc&start=Nom_du_film avec Start etant la premier page et non le titre du film
 3 - Tu envois le resultat a resultSearch() qui n'existe pas.

**Comment by mino60** [comment]
le problème est sur le resultat comme film-streaming.co

![sans titre](https://cloud.githubusercontent.com/assets/11494048/20609266/98e7f618-b28a-11e6-8d8f-ec0cbc6d511a.png)
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/20609270/acb7cf7e-b28a-11e6-8d16-fc685bdeda8c.png)
![sans titre2](https://cloud.githubusercontent.com/assets/11494048/20609273/b6f3d762-b28a-11e6-8867-227ed2a8bae0.png)

**Comment by mino60** [comment]
sur le navigateur il affiche un message d'erreur

Resultat de votre recherche :
Erreur : Ressayez en utilisant plus de 3 caractères
avec la mème page sur kodi
. les gardiens de la galaxie
. Louise-Michel
.  .......

sur xbmclog: 
![sans titre](https://cloud.githubusercontent.com/assets/11494048/20632838/89fd08b2-
b340-11e6-8dac-6f4ccbf71980.png)

topimdb.py: 
http://pastebin.com/xvvyvDse

**Comment by LordVenom** [comment]
Dejas y a pas de titre dans la recherche c'est pas normal. Un xbmc.log(str(aResult)) te donneras la réponse

`('Le parrain', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNTUxOTdjMDMtMWY1MC00MjkxLTgxYTMtYTM1MjU5ZTJlNTZjXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UY98_CR1,0,67,98_AL_.jpg', '2.', '1972', '9,2/10')`

titre = aEntry[0]
image = aEntry[1]
numero = aEntry[2]
anné = aEntry[3]
note = aEntry[4]

**Comment by mino60** [comment]
le problème et résolu merci pour votre aide pour le film inception je trouve 1 resultat sur film-streaming.co mait je ne peux pas voire le film est ce que c'est le site qui est on panne ou il reste à maitre à jour le script?.

**Comment by johngf** [comment]
chez moi ça fonctionne pour inception la recherche film ne fonctionne pas par contre
`line 164, in showMovies
                                                aResult = oParser.parse(sHtmlContent, sPattern)
                                            UnboundLocalError: local variable 'sHtmlContent' referenced before assignment`

**Comment by mino60** [comment]
est ce que je peux ajouter Fanart pour les poster et  come,t passer a deuxieme page

next page.

**Comment by mino60** [comment]
Next page est ce aue ca marche avec ce code !!


           
    self['Page'] = Label(_("Page:"))
    self.page = 1
    self.lastpage = 20		
    self.start = 1
    self.start = (self.page * 50) - 49

    url = "http://www.imdb.de/search/title?groups=top_1000&sort=user_rating,desc&start=%s" % str(self.start)
    getPage(url, headers={'Content-Type':'application/x-www-form-urlencoded', 'User-agent':'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0', 'Accept-Language':'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3'}).addCallback(self.parseData).addErrback(self.dataError)
    oParser = cParser()
    aResult = oParser.parse(sHtmlContent, sPattern)
    if (aResult[0] == True):
        return aResult[1][0]

**Comment by LordVenom** [comment]
@johngf  a réparer la fonction mais j'ai mis le nez dedans depuis vas voir la conversation ça devrais t'aider 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/641

**Comment by LordVenom** [comment]
J'ai un peux avancer http://pastebin.com/CbhpMrfw par contre la recherche je vais mettre celle de base si tous les sites choisisse les recherche ont vas mettre le bordel.
