### ISSUE TITLE
Options de vues Zone téléchargement

### ISSUE THREAD

**Issue by Sph1re** [Kodi-vStream/venom-xbmc-addons#660]
Bonjour à tous,

Je voulais savoir si il était possible d'ajouter des option de vues pour zone téléchargement?
car je vous explique mon cas...

- sur kodi 17 les covers et info de zone téléchargement apparaissent correctement mais pas de captcha visible...
- sur kodi 16 je n'ai pas les covers ni info (même en activant les options) avec option de vue: liste et grande liste j'ai des thumbnails mais pas d'info

Pour info:
skin Artic Zephyr officiel sur Kodi 17
skin AZ:FA beta sur kodi 16 (l'officiel indispo et celui du repo n'est plus fonctionnel pour moi)

Dommage pour le captcha sur 17... ça aurai été parfait (et je comprend le choix de ne pas le rendre actif pour le moment)

**Comment by johngf** [comment]
kodi 16 pour les infos du film récupéré par le script lui meme si c'est du synopsis que tu parle ça fonctionne elle ne sont pas sur la 1ere page il faut cliqué sur le film après sur le lien tu peut avoir les info

**Comment by TmpName** [comment]
Metahandlers s'active tout seul ?
Tu veux dire a la premiere install ?

Le fonctionnement normal c'est pas de covers, ni d'infos, mais captcha ok.
Normallement les 2 addons doivent etre desactive par defaut, apres sur Kodi 17 tout est possible, c'est juste un prototype, rien n'est sense fonctionner correctement.

**Comment by johngf** [comment]
non pas a la première install si je clique info sur la popup il s'active sans etre activé mais dans les options il est toujours désactivé
17:53:07 T:1612   ERROR: EXCEPTION: Unknown addon id 'script.extendedinfo'.
17:53:07 T:1612  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
17:53:08 T:1612  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.8.6
17:53:08 T:1612  NOTICE: metahandler: No SQLite rows requiring update

**Comment by Sph1re** [comment]
@johngf @TmpName 

Sur le même poste. 
La je vien de faire l'essai sur un autre PC, kodi 16 et skin de base ça fonctionne parfaitement (option recherche metadonnées)

je test à nouveau ce skin beta (AZ:FA) qui me semble bien bancale...

**Comment by Sph1re** [comment]
Bon... ça fonctionne pas avec le skin beta... (vignette vstream a la place)

Soit:
- j'attend que le catcha soit effectif sur la V17 
- je change de skin (et tout mes réglages et habitudes!!!!!!!! ;) )
- je trouve un moyen de faire fonctionner le thème V17 sur V16
- je rajoute l'option au skin (ça me gonfle...)

**Comment by TmpName** [comment]
Ha oui ca me revient ^^.
Quand metahandler est active, il va chercher les infos et les images pour chaque film a chaque fois (et c'est tres long). Pas quand il est desactive.
Par contre quand il est desactive, si tu demandes a voir les infos, on passe par lui pour recuperer les infos, mais uniquement lors du passage via le menu contextuel, il n'est pas actif par defaut.
