### ISSUE TITLE
Voir ses fichiers uptobox

### ISSUE THREAD

**Issue by Per0x** [Kodi-vStream/venom-xbmc-addons#661]
Bonjour,
Le plugin fonctionne correctement pour zone-telechargement, mais j'aimerais savoir
si il serait également possible d'accéder aux fichiers uptobox sur son compte personnel ? (dans: ht tp://uptobox.com/?op=my_files) en plus des sites de partage comme zone-telechargement ?
Merci.

**Comment by LordVenom** [comment]
Bonjour, 

Lol j'ai rien compris tu veut acceder à tes fichiers personnel upto depuis vStream?

**Comment by Per0x** [comment]
Oui c'est ça. Mes fichiers uptobox sont sous format video visibles en streaming donc je voudrais savoir si on pouvais les voir depuis le plugin vstream de kodi.

**Comment by johngf** [comment]
j'ai commencé un truc basic il y a moyen de faire mieux en passant par premiumHandler sans doute mais ça fonctionne.
tu dois ajouté au script ton identifiant et pass puis tu met le script dans le dossier sites

**Comment by LordVenom** [comment]
A ajouter dans "dossier vStream"\resources\sites il devrais être visible dans le menu vStream toutes les sources.

**Comment by Per0x** [comment]
ça marche impeccable !
Merci infiniment vous êtes des chefs. Je vous ferais bien un petit don, mais vous acceptez pas les bitcoins ;)

**Comment by johngf** [comment]
J'ai oublié de te dire sauvegarde le quelque part sur ton pc parceque quand vstream fait la grosse maj du mois il efface tous ce qui n'est pas dans son fichier zip
Pour les dons voir lord venom

**Comment by LordVenom** [comment]
Ho y a des chances que @TmpName  aime ça donc si il le met dans les sites il passeras dans la mise à jour officiel.

**Comment by johngf** [comment]
Moi non plus je n'utilse pas uptobox ou zone tel j'ai crée un compte gratuit pour testé

**Comment by TmpName** [comment]
Moi non plus ^^, j'adore cet hebergeur, mais le gratuit me suffit pr le moment, donc peux pas tester pr le cote premium.
Apres le gros a ete fait par @johngf , je pense pas que ca doit etre dur de finir.

**Comment by johngf** [comment]
Meme avec un compte gratuit tu peut upload des fichiers sur ton compte mais apres ça fonctionne premium ou gratuit je pensé premiumhandler pour le pass et l'identifiant evité de le rentré manuellement dans le script

**Comment by LordVenom** [comment]
Ben avec la pub que l'on lors fait il vont bien faire ça donc a ceux qui passe par leur page facebook ou twitter dire leur de nous offrir des pass :)

**Comment by johngf** [comment]
j'ai mis sur le site une 2eme version qui gère les dossiers @Per0x 
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/9cdada06651fc03fe664e695f988b52f87229f26/plugin.video.vstream/resources/sites/siteuptobox.py

**Comment by Per0x** [comment]
Merci. Ah vous me fascinez les programmeurs. En un jour vous pondez un script fobctionnel gratuitement pour un type random. Balèze.

**Comment by johngf** [comment]
Bon j'ai fait une version optimisé et ajouté la possibilité d'upload les liens uptobox que vous trouverez sur les sites vers votre compte perso gratuit ou premium pour les regardés plus tard

**Comment by Per0x** [comment]
J'ai fait une mise a jour et je ne retrouve plus le lien vers votre script.

**Comment by johngf** [comment]
il sera dans la maj qui arrive
si @TmpName passe par la c'est possible de mettre une condition d'affichage de la popup authentification réussie elle empeche la mienne de s'afficher si je passe par premium handler
genre def Authentificate(self, popup=False) ?

**Comment by LordVenom** [comment]
Il y a une function oPremiumHandler 

`from resources.lib.handler.premiumHandler import cPremiumHandler`

Puis voir ici http://pastebin.com/mMqQeXER

Juste la popup a chaque fois c'est chiant y a un moyen de savoir si ont et deja connecter ?

**Comment by johngf** [comment]
bah en faite le code est deja fait mais la popup me saoule

**Comment by LordVenom** [comment]
Dans mon dernier code j'ai refait un parsbin y a plus de popup.

http://pastebin.com/85v3JMa2

**Comment by johngf** [comment]
mon code actuel http://pastebin.com/raw/j7sm0fRf je vais voir si je peut adapter

**Comment by LordVenom** [comment]
Je pense que tu peux utiliser

` if (not oPremiumHandler.isPremiumModeAvailable()):`

Pour voir si il et connecter ou pas pas besoin de changer oPremiumHandler.Authentificate

**Comment by LordVenom** [comment]
Tu peux envoyer sur le Github, j'utilise parsebin pour pas te mélanger dans tes Pulls. Pareil avec hoster si tu as fait des test ça me vas.

**Comment by johngf** [comment]
ou plus simple afficher la popup quand cas d'echec

**Comment by TmpName** [comment]
J'ai pas suivi, mais c'est quoi le prb en fait ?
Le popup apparait trop souvent ?
Si tu sauvegarde le cookie dons ton code, tu devrais pouvoir le reutiliser sans avoir a t authentifier.
Moi je partirais sur la version de LordVenom et je laisserais le popup quand tu essayes de t authentifier.
Il y a moyen de n'avoir qu'un seul popup le temps de validite du cookie.

**Comment by johngf** [comment]
en faite j'ai ajouté une fonction pour ajouté les liens uptobox a son compte perso sauf que la popup authentification empeche la mienne qui donne le résultat de l'upload

**Comment by TmpName** [comment]
Et tu as besoin de la fonction checkConnection = GetConnect() dans UploadFile() ?
Normalement si tu es deja authentifie, les cookies sont bon, pas besoin de te reauthntifier, donc pas de popup.

Apres il te faut juste taiter le code venant de GetHtml(), si ca affiche que tu n'est pas connecte, a ce moment et uniquement a ce moment tu utilise la fonction GetConnect().

**Comment by johngf** [comment]
l'upload se fait a partir de la popup au niveau du lien donc on est pas connecté
les cookies ont une date d'expiration non ?

**Comment by TmpName** [comment]
Pas forcement, certain ont une duree de fin illimitées, c'est le site qui choisit.
Mais les cookies sont memorise sur ton disque dur, donc meme si tu n'utilises pas la fonction d'authentification, il sont utilisables.

**Comment by johngf** [comment]
en faite j'utilise l'auth pour renouvelé le cookie pour eviter des erreurs inutile

**Comment by TmpName** [comment]
Ben dans la version du github, tu appelles la fonction UploadFile() qui apelle la fonction GetConnect() qui elle appelle la fonction oPremiumHandler.Authentificate() qui elle te reauthentifie a chaque fois.

Moi je virerais les lignes 122 a 126, et je ferais appel a la fonction GetConnect UNIQUEMENT si le resultat de la ligne 136 n'est pas bon.

**Comment by johngf** [comment]
Je vois avec un
 try:
 shtmlcontent = etc...
 except 
opremiumhandler authentificate

**Comment by LordVenom** [comment]
Tu peux faire comme moi pour track pour être sur j ai créer une fonction pour ce déconnecter comme ça si ça bug on peux ce reconnecter.

**Comment by johngf** [comment]
tiens pour les membres avec compte gratuit il y a une promo 1an pour 6,5$ au lieu de 30

**Comment by TmpName** [comment]
Nope pas avec try/execpt car ca marchera toujours, mais dans la page html tu devrais avoir un detail qui chnage, style une phrase, "vous n'etes pas connecte", ou l'absence du lien.

Si c'est le cas, c'est que la personne n'est pas authentifie ou que le cookie est perime, tu refais appel a la fonction opremiumhandler authentificate, et le cookie est regenere et sauvegarde.
Il te suffit de recharger la page, attention pas de boucle, sinon en cas de bug tu vas bombarder le site de uptobox.

Et pr les video je sais, mais c'est moins grave une authentification pour un film de 1h, c'est pas mechant, a l 'epoque j'ai fais ca a la barbare. Apres il y a moyen de savoir si c'est bon ou pas, dans le code html quand tu es connecte , il y a le boutton "deconecter"  sinon il y a le boutton "connecter".

J'y jetterais un oeuil cet apres -midi.

**Comment by johngf** [comment]
pour l'instant en cas d'erreur on est redirigé vers la page login
    sHtmlContent = oPremiumHandler.GetHtml(Upurl)
    if (len(sHtmlContent) > 50):
        checkConnection = GetConnect()
        if (checkConnection == False):
            xbmcgui.Dialog().notification('Info connexion', 'Connexion refusé', xbmcgui.NOTIFICATION_ERROR,2000,False)
            return
        sHtmlContent = oPremiumHandler.GetHtml(Upurl)

**Comment by LordVenom** [comment]
J'ai toujours une popup "authentification reussis" a chaque deplacement.

**Comment by johngf** [comment]
oui j'ai remarqué quand on retourne sur load mais chez moi c'était aléatoire je suis en train de corrigé

**Comment by johngf** [comment]
j'ai remplacé la connexion auto par une vérif de la présence du fichier cookie c'est ok
après tous mes test ont était fait en gratuit je ne sais pas si les cookies premium ont une duré plus courte ou non

**Comment by TmpName** [comment]
Yep, la presence d'un cookie ne veut rien dire, il peut etre perime depuis 6 mois.
Je m'y met dans 5 mn

**Comment by TmpName** [comment]
Bon alors nouvelle version du fichier premium.
La fonction GetHtml() suffit pour avoir la page, pas besoin d'authentification.
Elle verifi toute seule si le cookie est valable, ne marche que pour uptobox pour le moment, mais tout les cas j'ai mit un verrou pour ne faire qu'une seule authentification a chaque fois, pas de risque de flood.

**Comment by johngf** [comment]
bah maintenant a chaque fois que j'ouvre un dossier j'ai une popup authentification

**Comment by TmpName** [comment]
Essayes en supprimant tout les GetConnect()

**Comment by johngf** [comment]
il y en as plus

**Comment by TmpName** [comment]
Ha ? Tu peux mettre la version du github a jour stp que je teste pour voir ?

**Comment by johngf** [comment]
elle est deja sur github mais getconnect n'est pas appelé vu que j'ai un cookie

**Comment by TmpName** [comment]
C'est bon, je teste http:// et le lien etait https://.
Re teste

**Comment by johngf** [comment]
c'est ok par contre ça rame ou alors c'est a cause de d'upto

**Comment by TmpName** [comment]
La je peux pas dire mais tant que les cookies sont present, il ne charge qu'une page et une seule fois. donc pas de raisons que ca traine, apres j'ai pas tout teste.

**Comment by johngf** [comment]
pour l'instant j'ai la popup si j'upload seulement

**Comment by johngf** [comment]
en passant au début que j'ai commencé la fonction upload j'ai cherché a compliqué et pas vue la facilité
donc j'ai fait une v4 avant la v3 celle qui permet d'upload de n'importe quelle hosters tant que le liens est le liens final en mp4 ou autre le code n'est pas finie mais ça fonctionne

**Comment by johngf** [comment]
c'est ok juste un detail si tu entre dans dossiers ou fichiers avec avec cookie invalid tu as une page vide vu que le temps qu'ont récupère le nouveau cookie le script a déja fini il suffit de faire retour arriere  d'y entrer a nouveau

**Comment by TmpName** [comment]
Bizarre, normalement quand tu essayes de lire la page, si tu n'as pas ecrit "logout" (donc pas connecte) mais cookie present et pas essaye d'authentification, ca affiche 'Cookies non valables', ca re authentifie, et recharge la page, ligne 224 a 231 de premiumhandler.

**Comment by TmpName** [comment]
Peut etre une fausse manip qui invalide le cookie a la volee, eg une connexion avec le meme cookie, meme ip mais user-agent different.

**Comment by johngf** [comment]
oui ça affiche cookie non valable mais ensuite page vide

**Comment by TmpName** [comment]
Et ca affiche pas ''Authentification reussie'' juste apres ?
Essayes en virant les lignes 83 a 85

**Comment by johngf** [comment]
si ça affiche Authentification reussie

**Comment by johngf** [comment]
c'est pareil page vide popup premium mode est un nouveau cookie

**Comment by johngf** [comment]
j'ai trouvé cette partie utilise l'ancien cookie
        if not(self.Checklogged(sHtmlContent)) and not self.__LoginTry and self.__Ispremium :
            xbmc.log('Cookies non valables')
            self.Authentificate()
            if (self.isLogin):
                sHtmlContent = self.GetHtmlwithcookies(url,data,cookies)
            else:
                return ''
        
        return sHtmlContent
 il faut ajouter 
cookies = self.Readcookie(self.__sHosterIdentifier)

**Comment by TmpName** [comment]
Ha oui, yessssss ^^
Bvo, je cherchais encore.

**Comment by johngf** [comment]
bon sinon maintenant il y a la possibilité d'ajouter les liens onefichier a son compte upto
a testé voir les autres hebergeur genre r*gator u*loaded etc....
