### ISSUE TITLE
Ajout du numero d'episode fonction "telechargement"

### ISSUE THREAD

**Issue by baaaaaziiiiingaaaaa** [Kodi-vStream/venom-xbmc-addons#666]
Bonjour,

Je regarde les séries sur ZT et j'utilise la fonction "dl & visu" ou "dl" à chaque fois je suis obligé de rajouté le numéro d’épisode pour éviter le message "nom déjà utilisé".
Serait il possible de rajouter le numéro d'épisode "S02E10" disponible à l’étage au-dessus ou carrément prendre le nom disponible sur le site de téléchargement "uptobox" "uplea" ect...?

Liste des épisodes sur ZT
* - - VF (HD720p) S02E10

puis sur uplea ou uptobox et autre
* - - VR (HD 720P) S02

Nom de l'enregistrement
* s02 vf.flv

Merci l'équipe

**Comment by TmpName** [comment]
Yep m'en occupe dans les jours a venir, surement ce WE.

**Comment by TmpName** [comment]
C'est bon, normallement tu as le numeros d'episode qui va se rajouter.
Par contre je ne force pas la MAJ pour ca, pour tester remplace ton fichier par celui la
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/zone_telechargement_com.py
