### ISSUE TITLE
Probleme pour vstream

### ISSUE THREAD

**Issue by thewolf51** [Kodi-vStream/venom-xbmc-addons#671]
Salut 
Je n arrive plus à trouver un fichier reposyteri vstresm zip qui fonctionne pour xmbc 
Y'a toujours un message d erreur lors de l installation  sur xmbc 
Merci de M aider

**Comment by LordVenom** [comment]
Et le message d'erreur et ?

**Comment by thewolf51** [comment]
[image1.JPG]

Martin

Le 25 nov. 2016 ? 13:05, Lord Venom <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Et le message d'erreur et ?

-

**Comment by johngf** [comment]
Cela ne serait pas ton parfeu qui empeche l'install ? moi j'ai eu ce probleme et pareil pour les majs
Sur ma machine windows avec eset smart security

**Comment by thewolf51** [comment]
Je reçois ce message D erreur 
Addon is incompatible or has been marked broker in repository. 
Dependencies not met please contact addon author

**Comment by thewolf51** [comment]
J ai loader xmbc dernière version

**Comment by thewolf51** [comment]
Avec Windows 7

**Comment by johngf** [comment]
Tu as essayé avec kodi 16 ?

**Comment by thewolf51** [comment]
non
se suis vraiment pas tres habile 
j ai acheter un kodi pour rendre ma tv intelligente  et il a rebooter et depuis pas capable de le reinstaller et j ai voulu l installer aussi sur mon ordi  et ca me dit le meme message d erreur

**Comment by johngf** [comment]
Pour t'aider si possible il faudrait le fichier log de kodi kodi.log poste le sur pastebin et poste le lien ici https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by LordVenom** [comment]
voila l'url du repo officiel

https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository

**Comment by thewolf51** [comment]
bon je viens de remplacer xmbc par kodi sur mon ordi  et la ca marcher

**Comment by thewolf51** [comment]
mais comment faire pour mon lecteur kodi   la est la question

**Comment by thewolf51** [comment]
mais comment faire pour mon lecteur kodi   la est la question  mais la j ai plus de temps  vous reviens en soirer  heure du quebec ,ca  
merci 
en passant je n ai rien compris johngf de ton dernier post mais je crois que ces moi qui ne comprends pas ;)

**Comment by LordVenom** [comment]
C est quoi un lecteur kodi ?

**Comment by TmpName** [comment]
XD, c'est du commercial.
C'est juste une boite avec le logo kodi et un raspberry dedans.

**Comment by thewolf51** [comment]
effectivement ces une boite que l on branche a une tv pour pouvoir naviguer sur le web
celle que j ai ces ``enjoy tv ``  my gica  fait par android payer environ 100 dollard canadien  qui a les fonctionne bouton ; netflix, play store et celu qui me concerne XMBC  
quand j appuis sur le bouton XMBC la tv s affiche avec la version ``12,2`` frodo

**Comment by thewolf51** [comment]
lorsque je suis le tutoriel pour y installer le repository vstream  on m indique  `` vstream  dépendances non supportées ``  
pourtant je l ai depuis 2 ans et tout fonctionnais bien  
il a comme rebooter et depuis  plus capable de le reinstaler 
ces la que j ai besoin d aide :)

**Comment by TmpName** [comment]
Tu as la liste des dependance ici https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Liste-des-d%C3%A9pendances

Normallement sur ton message d'erreur tu devrais avoir le nom de la manquante.

Il te suffit de l'installer directement via kodi, elles sont toutes dans les repo de base.

**Comment by thewolf51** [comment]
comme dit precedemment je suis pas trres bon la dedans 
ou je peux trouver le fichier dans xmbc qui me dit la dependance manquante 
je dois allez dans systeme et apres .....

**Comment by thewolf51** [comment]
desoler j ai comme besoin qu on me prenne par la main :0

**Comment by johngf** [comment]
Sinon plus simple essaie de mettre a jourkodi sur ton boitier vers kodi 16

**Comment by thewolf51** [comment]
ouin j ai essayer mais pas reussi  :(

**Comment by johngf** [comment]
Tu as le playstore sur ta machine ?

**Comment by thewolf51** [comment]
oui

**Comment by thewolf51** [comment]
en passant je suis un utilisateur de apple  de la ma meconnaissance d android

**Comment by Kodigoal** [comment]
lol johngf j'allais juste mettre le même lien xD
ou passer  par l'appli mygicastore sur ta box pour les updates d'applications ?

**Comment by johngf** [comment]
^^ a partir de la tu mettre a jour xbmc vers kodi

**Comment by johngf** [comment]
@Kodigoal tu peut testé flashx avec le nouveau code chez toi ?

**Comment by LordVenom** [comment]
Logique si il font payer leur boitier il doivent avoir un support

1) mettre a jour ton Kodi vStream devrais tourner a partir de la version 14
2) Vérifier les dépendances voir le lien donner par @TmpName 
3) les installer si inexistante mais pareil vStream devrais les installer si tu a le repo officiel de kodi

**Comment by thewolf51** [comment]
bon  j ai reussis a installer kodi 16  
croyais vous que ces trop  lourd ou ca va fonctionner correctement

**Comment by thewolf51** [comment]
tout semble parfaitement fonctionner 
un gros MERCI a vous tous pour vos conseil et votre patience ;)

**Comment by johngf** [comment]
Trop lourd non c'est pareil
