### ISSUE TITLE
taille du zip

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#675]
il y a quelque temps nous avons discuté de gagné quelque Mo sur le fichier zip de vstream
j'ai proposé d'héberger les images et donc après un béta test (je n'ai pas tous testé ni fini) ça fonctionne.
Les images sont dl une fois par kodi et mis en cache dans sont dossier thumbnails pour cela j'ai crée sur github le répertoire /art de vstream et modifié quelques fichiers pour qu'ils utilisent ce répertoire.
code : https://github.com/johngf/img
donc si un jour vous voulez changez c'est faisable facilement

**Comment by TmpName** [comment]
Mais le soucis de cette methode c'est les requetes, le serveur prefere une requete avec un gros fichier que tout plein de petites, Exodus utilise un second repo juste pour les images, mais je sais pas si ca vaut le coup de se pencher sur la methode.

**Comment by johngf** [comment]
effectivement kodi vérifie que l'url est valide sauf pour la page home de vstream

**Comment by johngf** [comment]
Apres c'est juste pour info sur github ou un autre hebergeur c'est faisable

**Comment by TmpName** [comment]
Lol, le mystere de la page home, hier encore ca m'a prit la tete quand j'ai voulu tester trakt, now j'ai la technique, je vide le cache de kodi via l'option de vstream.
