### ISSUE TITLE
Trakt

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#676]
Bon alors Nouveau topic pour les testeurs de la fonction Trakt.

J'essaye de la faire tourner sans les metas actives, car trop lourd. Pour le moment on peut en clic droit rajouter un film en watchlist mais par contre lors de la navigation les images n'apparaissent pas alors qu'elles sont bien chargées par la fonction getTmdbInfo()

Apres vu que je n'ai besoin que des posters il y a peut etre une api plus legere pour ca.

**Comment by LordVenom** [comment]
Mis a jour, note tu trouve ça plus rapide que d'activer les Meta perso c'est pareil.

**Comment by TmpName** [comment]
Nope c'est pas plus rapide, j'ai teste.
Je pense que la mise en cache se fait toute seule par contre (juste pr les images, cache de kodi), mais le prb reste le meme, je veux juste des posters car les titres seuls ca fait trop pauvres, mais juste pr recuperer 5 images ca me prend 10 plombes.
La methode n'est pas du tout bonne. Trouver une api plus legere ?
En fait ca prend autant de temps pr tout recuperer que juste un lien pour un poster.

Pour le message, faut mettre un truc plus neutre, style "Film rajoute".

**Comment by LordVenom** [comment]
Bon ça plante il peux pas trouver les infos pour les saisons et les episodes. Dans collection si tu clique sur une series ça vas dans les saisons puis dans les epidodes.

**Comment by LordVenom** [comment]
Bon toujours pas les séries affiche d'autre fiche c'est jamais la bonne.J'ai aussi beaucoup d'erreur connection impossible.

**Comment by LordVenom** [comment]
La lenteur et peux etre du au limite de l'api Tmdb

`We currently rate limit requests to 40 requests every 10 seconds. You can inspect the status of your limits by looking at the X-RateLimit response headers.`

C'est pour ça que les autres addon oblige les utilisateur a avoir leur propre clef API mais je trouve ça nul.

**Comment by LordVenom** [comment]
Pour moi le meilleur api c'est https://www.omdbapi.com/ tu as tout en 1 requete par contre pas d'info en Français.

**Comment by TmpName** [comment]
40 requetes toutes les 10s ?
C'est pas possible, y a des sites avec 20/30 titres par pages, on fait au moins 1 requetes par film, tu m'etonnes qu'on pedale dans la choucroute.

Sinon utiliser metahandler mais active juste pour ce fichier (comme on fait pour les infos en menu contextuel)
Au moins sa gerera le cache. En fait moi ca me derange juste pour pour 2 raisons.

1- Je ne veux pas metahandlers pour l'integralite de Vstream.
2 - Tu imagines la tailles du cache sur quelqu'un qui aura vu 100 films et qui suivra 10 series ?

En tout cas pour le moment suis d'accord avec toi, TMDB on evite, le seul prb c'est qu'on est oblige de passer par lui pour avoir l'id imdb, il n'y a que tmdb qui marche avec les titres francais. Apres on passe par n'importe lequel.

Le je suis bloque pour flaxhX, vais voir pr trakt.

**Comment by TmpName** [comment]
Bon j'ai corrige un poil.
J'ai commence l'affichage du calendrier (en fait j'ai juste mit un lien en bourrin ^^) mais c'etait pr les tests.
J'ai un site qui donne les traduction FR.
Mais je pense faire une sous section pour le calendrier (trop de trucs)

**Comment by LordVenom** [comment]
J'ai tester l'api omdb c'est pas plus rapide dsl.

**Comment by LordVenom** [comment]
Bon pour activer uniquement metahandler sur trakt tu peux mettre dans trackt.py getfolder()

`oGuiElement.setMetaAddon('true')`

Par contre il faut supprimer 

`oGuiElement.setTmdbId(sTmdb)`

C'est bugguer.

**Comment by TmpName** [comment]
En fait j'ai pas supprime la fonction setTmdbId(sTmdb) mais il y a un return des le debut donc elle ne devrait plus gener. Pour le moment elle apporte rien de plus que metahandlers (aussi longue). C'est la fonction getTmdbID que j'ai ameliore.

Mais j'ai de gros prb avec stype, on coup c'est "movie" un coup "movies" et pour certains sites (voirfilm), c'est aussi "movie" pour les series, pourtant on utilise bien addTV().

Pour le moment je vais tourner avec ta modif.

**Comment by LordVenom** [comment]
Hum dans Trakt.py function getfolder() il faut supprimer 

`#oGuiElement.setTmdbId(sTmdb)`

Je sais pas pk mais ça fonctionne pas avec ça.

**Comment by LordVenom** [comment]
J'ai réparer guiElement tu peux l'aisser setTmdbId() j'ai fait quelque test et ça tourne tu me diras si tu voie un bug.

**Comment by LordVenom** [comment]
Le calendrier a l'air bien bugguer même direct sur leur api c'est la misere.

**Comment by TmpName** [comment]
Moi ca marche pas trop mal, par contre laisses tomber la quantite de donnees, et je sais pas quoi mettre comme filtre.

**Comment by LordVenom** [comment]
J'avais des bug dans le calendrier mauvais codage surtout titre de série a la con lol. J'ai fait quelque modif (popup de retour, Saison et episode sur 2 chiffre date en FR ect..) c'est pas mal la.

**Comment by TmpName** [comment]
Moi j'ai commence la recherche hier, mais faudra tout refaire en passant par tmbd, car trakt ne gere pas les nom francais, au moins y a le squelette.

**Comment by LordVenom** [comment]
Tu peux faire une recherche par la recherche visuelle et l'ajouter direct a track aussi donc pas vraiment utile la recherche trakt

**Comment by TmpName** [comment]
Je viens de corriger la fonction getTmdbID() pr le prb avec avatar.
En passant j'ai modifie le code pour que si on passe par la recherche visuelle on conserve l'id tmbd, plutot que d'utiliser cette fonction.
Par contre j'ai des prb avec tmdb tmdbId imdb ImdbId ect ....

Et exact du coup la recherche trakt ne sert plus.

**Comment by LordVenom** [comment]
Ok merci perso j'ai corriger le probleme imdb c'est chiant c'est id j'ai mis un commentaire ligne 666 de trak.py 

`  #entrer imdb ? venant d'ou?`

Y a une entrer imdb qui venait de trakt je les virer pour mettre tmdb je sais plus pourkoi j'avais changer mais ça tourne comme ça donc si tu pas le souvenir d'une autre entrer imdb tu peux virer la condition.

**Comment by TmpName** [comment]
Sinon a reflechir.
+ La recherche ne sert pas, mais je pense que je ne serais pas le seul a ne pas penser a passer par la recherche visuelle > faire un raccourcis qui renvoit a la recherche visuelle
+ Hier j'ai ete con, en passant par la recherche visuelle, je suis parti avec TmdbId mais j'avais egallement le Imdbd
+ C'est con que metahandler ne propose de mettre sa propre cle API, je suis d'accord avec toi, que c'est mieux d'en avoir une propre au logiciel plutot que d'imposer aux users d'en prendre une, mais pour celui qui s'en sert a la toque, il aurait un meilleur debit.
+ J'ai un site qui propose les dates de sortie des version FR, vais le rajouter dans le calendrier.

**Comment by TmpName** [comment]
Bon je sais pas si c'est un prb du cote de leur serveurs, mais je n'ai plus les fanart dans trakt.
Si je vais dans les options de metahandler, efface la database, je les ai de nouveau, mais si je fais un retour et revient plus rien...
Et pourtant dans les logs il y a des acces vers MH.

**Comment by TmpName** [comment]
Je viens de trouver un truc utile, pour limiter le nbe de video a la fois.
http://docs.trakt.apiary.io/#introduction/pagination

Par contre ca ne marche pas pr les calendriers ....

**Comment by TmpName** [comment]
Pour les series a surveiller, suis pas sur que ce soit utile d'avoir autant de choix.

**Comment by LordVenom** [comment]
Y a besoin de tout c'est xbmc.log ? Pour une information a l'utilisateur utilise plutot cconfig.log() c'est la même mais y ecrit [PLUGIN] Vstream dans le log.

**Comment by TmpName** [comment]
Nope, tu peux les virer, c'est juste pr moi, pr le deboggage, si je pouvais je mettrais juste print(), en fait j'utilise le truc le plus facile a taper, je prevois pas de le laisser sur le long terme. Apres parfois, par reflexe je continu avec ca a la place de cconfig.log() mais tu peux changer aussi, rien de definitif.

**Comment by johngf** [comment]
j'ai voulu test trackt mais comment ça fonctionne
- vstream te donne un code ,tu crée un compte et du donne le code après .....

**Comment by LordVenom** [comment]
Ha j'ai jamais fait gaffe a ça je sais pas si ont peux re-chopper la session fermer.
