### ISSUE TITLE
Zone-telechargement

### ISSUE THREAD

**Issue by arzaz** [Kodi-vStream/venom-xbmc-addons#677]
Zone telechargement est vide sur vStream

**Comment by johngf** [comment]
Le site ne fonctionne pas non plus c'est normal

**Comment by arzaz** [comment]
Le site fonctionne bien sur pc

**Comment by johngf** [comment]
ah pas chez moi peut etre comme #665

**Comment by johngf** [comment]
a confirmer par d'autre personne chez moi le site HS

**Comment by johngf** [comment]
Retest pour voir j'ai reussi a me connecté sur leur site

**Comment by Gregwar** [comment]
Le site répond à nouveau mais encode tout en `gzip`
J'ai fait une PR qui décode le `gzip` et avec ça ça marche (#679)

**Comment by johngf** [comment]
je test ça

**Comment by johngf** [comment]
c'est ok

**Comment by johngf** [comment]
@arzaz r

**Comment by Stefle33** [comment]
Bonsoir, 

Une solution pour les machines comme Bbox miami ou l'on ne peut pas directement modifier le fichier en question ? 

Merci

**Comment by Gregwar** [comment]
J'ai releasé un dépôt TEMPORAIRE (un peu bricole)

Tu peux ajouter la source
http://gregwar.com/kodi/

Et installer l'extension "Gregwar vStream" depuis le dépôt d'extension

**Comment by sebi0606** [comment]
Bonjoir a tous,
Malgré l'installation du dépôt temporaire chez moi zone de téléchargement toujours vide help

**Comment by johngf** [comment]
si tu ne peut pas édité le fichier a la main il faut attendre la maj

**Comment by sebi0606** [comment]
Ok merci @johngf en espérant que celle ci arrive vite bonne journée

**Comment by johngf** [comment]
en faite j'ai dit une connerie ce genre de fichier n'est pas mis a jour par la maj il faudra attendre la maj mensuelle ou modif le fichier site ZT

**Comment by johngf** [comment]
le site est hs pour l'instant il faut attendre qu'il fonctionne pour test la modif

**Comment by sebi0606** [comment]
Le site sur le Web fonctionne très bien il n'y a que sur vstream ou il est vide testé à l'instant

**Comment by johngf** [comment]
en faite des fois il ne fonctionne plus un moment puis revient

**Comment by johngf** [comment]
réessaie sur vstream pour voir

**Comment by sebi0606** [comment]
Toujours vide dans vstream et zt fonctionnel  sur le web

**Comment by johngf** [comment]
j'ai trouvé la soluce

**Comment by sebi0606** [comment]
????? @jonhgf la soluce ?

**Comment by johngf** [comment]
je viens de le mettre a jour 
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/1e1a50ccb1c633fca444936aad3b3ae5aa288856/plugin.video.vstream/resources/sites/zone_telechargement_com.py

**Comment by sebi0606** [comment]
Merci @johnf marche nickel

**Comment by LordVenom** [comment]
J'ai accepter la modif gzip mais dispo que dans la version officiel dans quelques semaines je préférer ta modif @johngf  mais bon ça mange rien de la prendre en compte. merci @Gregwar .

**Comment by Gregwar** [comment]
@LordVenom effectivement je pense que de toutes façons si la réponse HTTP est du `gzip` autant essayer de le décompresser

**Comment by renoooo** [comment]
Bonjour,
Je suis attentivement votre fil d'eau, j'ai un box android sunvell t95z, est il possible d'injecter le lien? Si oui comment merci. Chez moi ZT ne fonctionne plus avec vstream depuis hier fin matinée

**Comment by ddav33** [comment]
Bonjour suis novise ,mais on en fait quoi de la solution johongf

**Comment by renoooo** [comment]
@,
Tout pareil meme question mais sur une box?  :-)

**Comment by renoooo** [comment]
Faut il editer un fichier de kodi?
Vstream?
Si oui quel est le chemin svp merci.
Faut il faire un copier/coller du dit fichier ou rajouter le code?
Merci

**Comment by ddav33** [comment]
Faut il attendre une mise a jour de vstream pour que cela re fonctionne? Dans combien de temps sinon?

**Comment by renoooo** [comment]
Ddav33
Tu es sur une box?

**Comment by ddav33** [comment]
Android 5.1

**Comment by renoooo** [comment]
Android oki mais ordi ou box?

**Comment by Gregwar** [comment]
@ddav33 @renoooo zt a l'air down de toutes façons en ce moment

**Comment by ddav33** [comment]
Box oui ,un boîtier mx3

**Comment by LordVenom** [comment]
Mise a jour auto lancer Max 3 jour pour avoir le bon fichier.

**Comment by johngf** [comment]
Copier coller dans zone-telechargementz.py ou attendre la maj quand elle sera dispo

**Comment by renoooo** [comment]
A gregwar,
Meme constat que decrit plus haut,
Hier en direct sur ordi ZT est ok il me semble. Juste soucis via kodi non?

**Comment by Gregwar** [comment]
@renoooo moi j'ai une erreur cloudfare quand j'y vais avec mon pc aussi

**Comment by Gregwar** [comment]
@renoooo en fait ça a l'air de marcher de façons très intermitentes

**Comment by LordVenom** [comment]
Leur serveur souffre en ce moment c'est les vacances? lol un peux de patience donc.

**Comment by ddav33** [comment]
OK comme je doute fort de pouvoir bidouille le ZIP sur ce boîtier vais attendre 3 jour mise a jour, merci pour ces infos 👋;-)

**Comment by renoooo** [comment]
Oki, merci a tous pour votre reactivité, bravo pour tous les efforts dont tout le monde profite.
Vais essayé bidouille ma box (et la bricker lol) on se revera certainement par la car la communauté a l'air chouette.
Bon appetit a bientot et merci pour vos reponses. 
Reno

**Comment by ddav33** [comment]
Idem pour moi aussi refonctionne, ne marchera plus 5mn avant  sur Firefox Android puis sur vstream revenu tout seul apparemment

**Comment by johngf** [comment]
dans la prochaine version de vstream il y aura un nouveau site du meme genre megatrack movie au cas ou

**Comment by renoooo** [comment]
A johngf, yes super merci

**Comment by ddav33** [comment]
Zt m'intéresse beaucoup pour les films en 3d si sur le nouveau y en a d'autres je suis preneur😉

**Comment by fawado** [comment]
Zone telechargement est mort a priori. 
Gendarmerie a tapé à la porte.

http://www.numerama.com/politique/212505-la-gendarmerie-annonce-la-fermeture-du-site-pirate-zone-telechargement.html

**Comment by ddav33** [comment]
Arff voilà tout s'explique, punaise juste au moment où j'avais tout configurée comme il faut 😧😴

**Comment by gralex68** [comment]
Hello, les amis, je viens de m'inscrire et de constater la fermeture de zt 😭. Le site ddl-island.su pourrait être un bon substitut. Merci et @+

**Comment by doubidave** [comment]
Bonjour, je suis nouveau aussi. La poisse pour ZT. Sinon il y a aussi ce site qui recense sensiblement les mêmes liens

http://www.zone-telechargement.eu/

Si ca peut aider et soulager notre peine 😢

**Comment by mino60** [comment]
il y a aussi mieux 

http://www.free-telechargement.org/1/films-bluray/1.html

**Comment by ddav33** [comment]
Merci mono60 l'offre sur free-tele... En 3d et vraiment pas mal reste à savoir si c'est possible de le voir par kodi 😕😋

**Comment by doubidave** [comment]
Ca serait vraiment top si ca pouvait passer par kodi oui.

**Comment by chataigne73** [comment]
à voir mais je pense que .free-telechargement.org est mort : c'était une copie de ZT (il pompait tout dessus) et depuis que ZT est down ils n'ont sorti aucun nouveau film ... à confirmer dans les jours qui viennent

**Comment by ddav33** [comment]
Va être dur de trouver des 3d, zt était les mieux que j'ai pu trouver, t'en a pas beaucoup qui référence ce genre de lien avec autant de nouveauté, si vous en connaissez je suis preneur 😦😉

**Comment by renoooo** [comment]
Bonjour a tous,
Est il possible de rajouter les adresses qui sont citées dessus dans les addons kodi sur une box. Dans exodus ou vstream peut importe. Si oui comment merci.

**Comment by renoooo** [comment]
Exodus fr perso ne me propose que des liens en sd? Ya t il un reglage qui oriente vers les liens hd?, merci

**Comment by ddav33** [comment]
@renoooo sur Exodus y a un réglages max mais après ce sont les liens dipo qui définie la qualité, regard configuration'lecture'max qualités 1080p

**Comment by renoooo** [comment]
Yeap, merci deja fait,

**Comment by doubidave** [comment]
Ce qui est compliqué sans zt est d avoir un résultat clair sur ce qu on ouvre. Trouver un truefrench en hd bonne chance 😖 Je ne sais pas si un vrai equivalent a zt existe. Niveau serie et dessin animé par exemple. Niveau film c est plus répandu. En tout cas bravo pour vstream 👍

**Comment by ddav33** [comment]
zt de nouveau en ligne 👍

**Comment by doubidave** [comment]
Sérieux? Je peux pas le tester du boulot mais j en pleure de joie si c est le cas 😭

**Comment by ddav33** [comment]
Oui mais  pour  le moment aucun lien ne fonctionne dl protect HS 😕

**Comment by renoooo** [comment]
Up

Est il possible de rajouter les adresses qui sont citées dessus dans les addons kodi sur une box. Dans exodus ou vstream peut importe. Si oui comment merci.

Pas de reponses?, merci

**Comment by renoooo** [comment]
Non serieux comment sur une box maintenant on peut regarder une serie en 720p? Des tuyaux, merci

**Comment by gralex68** [comment]
Hello les amis, je suis très novice en programmation, mais je profite de ce second message pour vous remercier pour ce que vous faites pour nous, pauvres ignares que nous sommes!

Pour résumer, je crois que les sites que nos "cerveaux" peuvent ajouter se doivent de proposer du streaming dès le départ. De plus, comme tous essaient de se protéger via des URL protection et consorts, je sais que ce n'est pas évident. Après fermeture, redlist à redémarré (en .tv), les liens sont anciens, mais il y a du streaming (et il faut du temps pour que ce site redémarre et propose de nouveaux liens.)

Bien à vous et@+ les amis
