### ISSUE TITLE
Recherches de concerts

### ISSUE THREAD

**Issue by camelone** [Kodi-vStream/venom-xbmc-addons#680]
Juste une petite suggestion. Y aurait-il moyen de faire une recherche de concerts sur base de l'artiste, un peu comme une recherche de films ou séries sur ZT? Car c'est un peu un bric à brac de résultats et c'est pas toujours évident de trouver ce que l'on cherche..

Bravo pour votre travail en tout cas!

**Comment by LordVenom** [comment]
Recherche Visuelle / recherche de films mais pas sur que vstream trouve quelque chose aprés peux etre alluc.
