### ISSUE TITLE
LA Pattern du site

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#687]
Bonjour j ai trouver ce site sur le net je crois qu'il est un bon site de streaming.

xxx://officiel-streamingfr.over-blog.com/
xxx://youtu.be/h8CoH-wUumA
et merci d avance pour votre aide précieuse.

**Comment by TmpName** [comment]
Ben il ya juste 200 film a tout casser et meme pas 20 series.
