### ISSUE TITLE
Fermeture de Zone Téléchargement

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#688]
Voilà qu'elle a été ma stupeur ce matin en découvrant que le site ZT a été fermé par la gendarmerie, je vous mets le lien l'article. Du coup, je me suis mis a cherché un autre site qui est dans la même lignée que le site et j'ai trouvé ce site ----> ht tp://www.free-telechargement.org/ et j'en avais déjà parlé lors d'un des postes, il reste encore ht tp://www.extreme-down.me/home.html voilà. Bref Jesuiszonetelechargement

**Comment by johngf** [comment]
#677 est pour exdown c'est définitivement pas possible ils utilisent plusieurs captcha différent dont recaptcha #538

**Comment by lebigboss59** [comment]
Salut à tous
Moi aussi je suis grave dégouté
Mais il n'y a pas moyen de remplacer la source par extreme down, emule-island.ru ou free-telechargement ?

En tout cas j'espère que les mecs de ZT vont s'en tiré

**Comment by VincentGrimond** [comment]
Salut,

ZT est à nouveau en route.
Par contre je ne sais pas si c'est un site Fake ou le vrai... mais j'ai pu m'y connecter avec la même URL qu'avant.

**Comment by lebigboss59** [comment]
Oui j'ai vue il est à nouveau fonctionnel, c'est bizard 
Sois ils ont étaient innocentés sois c'est la gendarmerie qui dirige le site lol

**Comment by lebigboss59** [comment]
Bon apparemment DL-Protect est down donc il faut attendre que ZT arrange ça aussi

**Comment by TmpName** [comment]
En attente pr le moment. Essayez de rester discret quand vous parlez de ce genre de site.
