### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by kenbest69** [Kodi-vStream/venom-xbmc-addons#689]
Salut suite à la fermeture de zone téléchargement j'ai trouver son digne successeur est-il possible de l'ajouter à sa place ? 
xxxx.zone-telech argement.eu

Merci d'avance.

**Comment by TmpName** [comment]
Merci d'aretter de proposer des sites de remplacement, j'en vois plusieurs par jours, et chacun propose les siens, je pense qu'il y a deja quelqu'un sur le coup, et qu'il a deja choisit un site.
Si ca continu le github de Vstream va ressembler a un annuaire de site warez.

**Comment by kenbest69** [comment]
Désolé je ne savais pas que vous étiez déjà sur le coup ;) toujours aussi efficace les gars. 
Longue continuation à vstream

**Comment by doubidave** [comment]
J'ai proposé le même hier et je suis heureux d apprendre que qqu un est sur le coup. Encore merci pour tous vos efforts et votre travail.

**Comment by TmpName** [comment]
He how, 5mn, suis pas dans la confidence des dieux ^^, j'ai rien dit d'officiel, c'est juste que je connais les habitudes des autres devs et que je me doute bien que ca va pas en rester la.

**Comment by kenbest69** [comment]
sinon est-ce possible que quelqu'un me fasse une source car j'ai essayer mais je n'y comprend absolument rien j'ai trouver une autre source. Et elle pourrait vous servir par la suite si vous la trouvez bien.

**Comment by TmpName** [comment]
@kenbest69 J'ai vu que tu avais pose la question dans un autre post, donc on va continuer la bas.
Et du coup je ferme celui -la
