### ISSUE TITLE
Upnp / DLNA

### ISSUE THREAD

**Issue by Gummmy** [Kodi-vStream/venom-xbmc-addons#690]
Bonjour, je découvre Kodi et Vstream, et j'essai de transmettre le film que je regarde en streaming depuis Vstream vers ma TV connecté ou ma freebox revolution ! Mais impossible d'avoir l'option "lire avec" quand je clic droit sur le film !

J'ai essayé avec youtube, vimeo et 9gag, et la pas de soucy j'ai bien cette option pour lire la video sur ma tv ou ma freebox, mais avec Vstream impossible ...

Avez vous une solution ?

Merci d'avance !

**Comment by LordVenom** [comment]
Heu... je savais même pas qu'il y avais cette option.

**Comment by Gummmy** [comment]
lol maintenant tu le sais ;) et ce serait vraiment cool de pouvoir diffuser directement sur la tv la video vu en streaming depuis vstream ! J'ai trouver une solution pour le moment utiliser miracast depuis mon telephone mais vu que mon pc n'as pas miracast je ne peux pas opter pour cette solution et perso je prefere utiliser mon pc plutot que mon telephone pour les gros fichiers en streaming !

**Comment by LordVenom** [comment]
Ton pc n'a pas de sortis HD :) Je regarderais mais envoyer en stream en stream c'est pas commun.

**Comment by LordVenom** [comment]
Bon j'ai tester mais ça fonctionne pas avec les stream perso même youtube ne fonctionne pas uniquement mes fichiers local. Mais bon pour avoir le choix de sélection il faut utiliser un raccourcis clavier pendant la lecture.
`Y	Switch/choose player. For example, can be used to switch between internal player or a UPnP target player.	Switch/choose player	Switch/choose player`

En gros tu lance la video sous vStream et tu tape Y

**Comment by Gummmy** [comment]
Ok je vais essayer merci :-)

**Comment by Gummmy** [comment]
J'ai tester, ca marche avec le raccourci clavier "Y" effectivement je choisi d'envoyer sur ma tv et hop la video se met sur la tv, seul hic ca ne marche pas avec toutes les videos, pour cetaines "format non supporté" pour d'autres l'appli sur la tv ne se lance meme pas ! Mais c'est deja mieu que rien ;)

Merci encore a toi !
