### ISSUE TITLE
captcha systématique

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#691]
salut
cela n'en n'étonnera pas certains, je suis en train de tester un nouveau site.
ce site contient une protection par captcha...
en bidouillant des morceaux de codes existants (que TmpName reconnaitra) j'arrive à résoudre le captcha

mon problème est que le captcha est demandé de manière systématique, même après un captcha correct.
ce n'est pas le comportement normal du site web.
je pense que le problème vient du fait qu'il faut que j'envoie le cookie stocké après un captcha correct, mais je ne vois pas comment l'implémenter dans ma fonction DecryptddlProtect...

votre aide m'intéresse  ;-)

mon code (en version très brouillon pour le moment : `http://pastebin.com/7SGNukKE`
merci

**Comment by kenbest69** [comment]
Petite question qui n'a rien à voir mais tu n'aura pas un tuto pour créer une source comme tu la fait car je n'y comprend rien et j'aimerai bien essayer de m'y mettre ou si tu peut m'aider. 
Merci d'avance, et désolé du dérangement.

**Comment by TmpName** [comment]
En fait il n'y a pas vraiment de tuto.
Il y a un fichier squelette https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_une_source.py avec ca tu vas demarrer tres vite
Mais tu vas surement bloquer quand tu vas decouvrir les regex, la par contre, je retrouve plus le topic d'aide mais on passe generallement par https://regex101.com/ avec comme flag gmis.

Apres proposes ton debut de code, il y a souvent d'autres useres qui aident en cas de bloquage, mais vu qu'on a pas besoin de nouvelle source pr le moment, ca m'etonnerait que quelqu'un en refasse une de zero.

@chataigne73 , lors de la dernier MAJ j'ai rajoute des fonctions expres pr les cookies dans les fonctions de bases de Vstream, je te dis ca de suite.

**Comment by kenbest69** [comment]
Ok je te remercie je vais regarder à sa ce soir voir ce que je peut faire. Et dans tout les cas je vous tiendrais au courant.
Merci à la team d'être aussi réactif.

**Comment by TmpName** [comment]
@chataigne73 ton code ne marchait plus donc j'ai un poil bidouille mais teste ca
http://pastebin.com/dZ0jsqhm

Par contre j'ai du rajouter 3 fonctions pour memoriser les cookies, je pense que vais les inclure dans les fonctions de bases de Vstream pour la prochaine MAJ.

**Comment by chataigne73** [comment]
Merci tmpname, je regarde ça dès que j'ai un moment
