### ISSUE TITLE
Nouvelle source pour Vstream

### ISSUE THREAD

**Issue by kenbest69** [Kodi-vStream/venom-xbmc-addons#692]
Bonjour tous le monde comment ça va? En cherchant à regarder suicide squad extended version (pas mal d'ailleurs), je suis tombé sur ce site qui est bien fournis pour rajouter dans la liste des sources je vous donne le site : ht tp://www.extreme-down.me
je l'ai testé et ça fonctionne très bien à vous de voir la team. 

Édit : comme dit précédemment  je vais regarder à sa ce soir et essayer de la faire moi-même ;)
Merci pour ton aide.

**Comment by johngf** [comment]
slt avant de posté il faut regardé si ça na pas déjà était proposé #688

**Comment by kenbest69** [comment]
Ha effectivement je n'avais pas vu donc sa ne sert à rien que j'essaye de faire la source vu que tu à indiquer que c'était impossible.
