### ISSUE TITLE
Coupures Flux

### ISSUE THREAD

**Issue by Asy4Ever** [Kodi-vStream/venom-xbmc-addons#696]
Bonjour,

j'utilise l'addon vStream depuis peu et je rencontre quelques problèmes. Je n'arrive pas à déterminer d'ou vient mon problème : j'ai des coupures sur la plupart des chaines Framapad mais pas de problèmes sur NT1 par exemple. J'ai modifié les réglages de buffer avec  "Advanced Settings", modifier le "Video Cache size" à l'aide "Ares Wizard": même problème.
J'ai une connexion internet à 16M testé sur speeduptest.(testé en filaire et wifi)
J'ai testé d'installé sur un RapsberryPi 3 avec OSMC et OpenElec et sur mon PC Windows: idem.

S'agit t'il d'un problème générale ou suis-je le seul à rencontrer ce genre de problème ?

Merci :)

**Comment by johngf** [comment]
c'est un problème connue #436

**Comment by Asy4Ever** [comment]
Merci pour la précision !
