### ISSUE TITLE
Est-ce qu'on peut télécharger avec Vstream?

### ISSUE THREAD

**Issue by Hitman78** [Kodi-vStream/venom-xbmc-addons#697]
Si oui, peut-on m'écrire les étapes svp.

**Comment by TmpName** [comment]
Oui, plus ou moins, mais Vstream n'est pas fait pour ca du coup le dl est bride, pour eviter de faire lagguer si tu veux voir une video en meme temps. C'est une solution de depannage pour les petits debits.

Quand tu es sur le dernier lien, en menu contextuel tu auras d'autres options, et ce n'est pas valable pour tout les hebergeurs.
