### ISSUE TITLE
Tests ddl-island

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#700]
Je crée cette discussion pour la nouvelle source que j'ai déposée sur la beta : ddl-island.
'https://github.com/Kodi-vStream/venom-xbmc-addons/raw/Beta/plugin.video.vstream/resources/sites/ddl_island_su.py'

Vos retours de tests sont les bienvenus

**Comment by chataigne73** [comment]
Déjà je pense qu'il y a encore un pb avec la gestion des cookies, par exemple quand on rallume vstream après un moment... Peut-être un problème de cookies périmés..
 Peut-être supprimer le cookies à l'extinctionou au lancement de vstream?

**Comment by johngf** [comment]
Ou sauvgardé a chaque fois le nouveau cookie dans un fichier texte comme upto le new cookie efface l'ancien

**Comment by TmpName** [comment]
C'est quoi le soucis avec les cookies ? Si tu passes par un navigateur, tu peux voir la "duree de vie" du cookie.
Apres j'ai pas teste ce qui se passe avec un cookie perime, mais ca doit juste te redemander le captcha ?

**Comment by kenbest69** [comment]
Je viens d'essayer et impossible de lancer un film ou série à chaque fois erreur vstream

**Comment by camelone** [comment]
Chez moi ça ne marche pas. J'arrive jusqu'au lien (multiples) je choisis uptobox dans mon cas car je suis premium. Mais ensuite j'ai une erreur. Raspberry pi2 kodi 16.

**Comment by chataigne73** [comment]
je viens de faire des corrections
ceux qui veulent peuvent retester ;-)

@TmpName : oui on rentre bien dans la boucle de demande de captcha, mais ça bloque ici `cookies = oRequestHandler.GetCookies()` car en fait qq lignes plus haut on a fait ça `oRequestHandler.addHeaderEntry('Cookie',cookies)`car il existait un cookies
j'ai rajouté un test mais ça fonctionne pas ... faut que je creuse

**Comment by Kodigoal** [comment]
Ok pour maj serie HD.
Ta dernière maj 'Menage' ca a tout pété par contre ??

**Comment by Stefle33** [comment]
Bonjour, comment faire partie de la bêta ? Merci

**Comment by chataigne73** [comment]
@Stefle33    il faut télécharger le fichier ici `https://github.com/Kodi-vStream/venom-xbmc-addons/raw/Beta/plugin.video.vstream/resources/sites/ddl_island_su.py`et le mettre manuellement dans le répertoire "sites" de ton kodi

**Comment by camelone** [comment]
On avance, on avance! Catalogue: OK. Choix du film: OK. Liens proposés: OK. (Uptobox dans mon cas). Captcha: OK. Je clique sur le film, ensuite le choix streaming ou en direct et là, dans les deux cas: Fichier introuvable. J'ai testé avec la reine des neiges :-) et l'age de glace 3. Mais j'ai confiance en vous, je sais que c'est une question de temps! Merci pour votre boulot! on ne vous le dit jamais assez!!!

**Comment by johngf** [comment]
si le lien du film est HS c'est normal

**Comment by camelone** [comment]
Ben... le lien du film n'est pas HS. J'arrive à le voir sur ddl-island. ;-)

**Comment by camelone** [comment]
Rectification: ça fonctionne! En fait, je viens de tester avec plusieurs films. Il faut parfois s'y reprendre à deux fois et puis ça marche.  Beau boulot les gars!

**Comment by kenbest69** [comment]
Ha super je regarde à sa en rentrant alors :)

**Comment by johngf** [comment]
Ça c'est pas normal par contre tu es premium ou gratuit ?

**Comment by camelone** [comment]
Uptobix premium

**Comment by camelone** [comment]
Uptobix = uptobox

**Comment by chataigne73** [comment]
le problème de s'y prendre à 2 fois j'en ai parlé plus haut ... c'est lié à la gestion des cookies ... j'espère avoir les lumières de TmpName sur ce sujet

**Comment by chataigne73** [comment]
**nouvelle version en test**
ajouts de nouveaux menus, des spectacles, émissions tv, mangas ...

à vos tests !   ;-)

**Comment by mako83** [comment]
J'aimerais beaucoup test le site :)
Comment fait on pour telecharger vstream beta?

Merci d'avance

**Comment by camelone** [comment]
Chataigne73 c'est vrai maintenant que je relis tout.. tu l'avais mentionné. Par contre, ça n'a rien à voir avec vous, mais je trouve que les liens sont quand même brouillons sur leur site. Rip ZT.

**Comment by TmpName** [comment]
Je galere avec les accents, comment vous faites pour telecharger uniquement ce fichier, en Raw ca passe pas ....

**Comment by Kodigoal** [comment]
chataigne73 xD oui vu ta maj juste après. 
En tout cas merci pour ta source^^

Sinon au niveau du listing showSeriesReleases() pour que le titre soit moins long ,
on pourrait mettre en premier en haut
le sMovieTitle et laisser juste le aEntry[1] pour le sTitle, genre par exemple comme ca:
[URL=http://www.hostingpics.net/viewer.php?id=298497fotonoexif.jpg][IMG]http://img4.hostingpics.net/thumbs/mini_298497fotonoexif.jpg[/IMG][/URL]

Parce que les noms des titres+episodes sont super long a defiler xD
Et petit soucis repéré avec le NextPage en cherchant une série ( testé en cherchant grey's anatomy).

**Comment by chataigne73** [comment]
@Kodigoal   oui tu as tout  fait raison, les affichages sont trop longs
j'intègre sa proposition dans ma prochaine maj

**Comment by chataigne73** [comment]
nouvelle mise à jour avec : modif affichage noms, ajout films et séries par genre, correction nextpage

**Comment by Kodigoal** [comment]
Testé ok.
Autre proposition xD:
Renommer le sQual  en 'HD' ou '3D' ou 'SD' pour
bien differencier et simplifier , car on a souvent sinon 
'BDrip' pour du sd ou hd .. 
Code du genre:
for aEntry in aResult[1]:
            sQual = 'SD'
            if '-hd-' in aEntry[0]:
                sQual = 'HD'
            if '-3d-' in aEntry[0]:
                sQual = '3D'
Ex: tu recherches en Film 'black storm' , il te sort
4 versions de black storm sans savoir laquelle est sd , hd ou 3D .
Tu as (BDRip) 3 fois puis 1 (DVDRIP) 
Si on renomme le sQual ca donnera:
http://img11.hostingpics.net/pics/315949fotonoexif.jpg
En un coup d'oeil je trouve qu'on voit mieux de suite si sd,hd,3d pour pas tester à chaque fois lequel sera
hd ou 3d si plusieurs choix.
Idem pour les autres rubriques.

Sinon oui quand on affiche par ex une recherche
Série 'grey's' , laisse tomber pour savoir laquelle
est la saison 13 hd d'un coup sans passer en mode liste simple .. 
Si ya moyen de retravailler l'affichage du nom
pour simplifier en mode poster genre:
Genre pour affichage recherche séries:
(SD/HD)-S01/Sxx - vostfr /vf -Nom en dernier ( deja sur le poster)
Pour series ajoutées:
(SD/HD)-S01e09 -vostfr vf - Nom
en prenant juste le numéro de l'épisode dans les [e09 / ddl e09/?? ] car ca rallonge ce truc ...
Je sais pas ce que t'en pense , et si tu veux un  coup de main pour modifier pas de soucis ^^

**Comment by kenbest69** [comment]
Merci chataigne pour ce taff ;) par contre comme disait kodigoal se serait super pour les series également :)

**Comment by kenbest69** [comment]
Par contre j'ai remarquer un problème de nextpage dans les recherches de films ou series

**Comment by Kodigoal** [comment]
@chataigne73
Bon j'ai pondu un pavé ( on se moque pas xD)  juste pour les séries ( recherche série comprise) , le reste pour l'instant (films/spectacles/emissions)  c'est bon par defaut , à voir pour les Mangas par contre...
Faudra voir à faire une fonction pour pas se répeter inutilement , je met à jour demain sur la Beta.
Petit apercu:
http://img4.hostingpics.net/pics/976292fotonoexif.jpg
http://img4.hostingpics.net/pics/456752fotonoexif.jpg
Après niveau couleur du sDisplayTitle , à voir aussi.

**Comment by johngf** [comment]
vous avez tous un compte premium up tobox ?

**Comment by sebi0606** [comment]
En ce qui me concerne @johngf oui

**Comment by johngf** [comment]
parceque dans la prochaine version qui arrive il y aura la possibilité via un click droit sur le lien d'ajouté le fichier a votre compte #661  lien upto one fichier et uplea pour l'instant compatible

**Comment by sebi0606** [comment]
Excellente nouvelle @johngf le top du top

**Comment by camelone** [comment]
Premium aussi @johngf. Super travail! Il vous arrive qd même de vous reposer de temps en temps ?? ;-)

**Comment by Kodigoal** [comment]
@johngf  ca transfere direct de site en site ? ou d'abord ca telecharge en local et ca envoit en même temps ?

**Comment by johngf** [comment]
Transfert direct

**Comment by Kodigoal** [comment]
xD la classe

**Comment by kenbest69** [comment]
Compte premium uptobox également

**Comment by Kodigoal** [comment]
Maj pour le reformatage affichage titre des séries/recherche série.
A tester si pas de bug ou modifier les couleurs selon tes envies.
Doit yavoir plus simple mais bon , ca fonctionne pour l'instant xD

**Comment by LordVenom** [comment]
Enorme taff :+1:  mais les titres en bleue ? couleur reserver au lien host et si y a rien de special a faire voir, une année, une qualiter, le nombre de vue ext.. le titre en lui même n'a pas de couleur.

**Comment by TmpName** [comment]
Pr infos, il y a des fonction dans Vstream qui reformatent et colorent toute seules les titres.

Pour afficher le titre propre sur le lien final l 636.
>sTitle = '[COLOR skyblue]' + aEntry[0]+ '[/COLOR] ' + sMovieTitle
Mais c'est un exemple j'ai pas compris pkoi tu avais sMovieTitle et sMovieTitle2, un seul suffit pas ?

**Comment by Kodigoal** [comment]
Oui j'ai fait comme ca pour le moment sans passer par le decodeTitle.
Je vais modifier tout ca ce soir.
Sinon comment faire pour:
Si '-serie-' ou bien 'mangas' est dans sUrl2:
pour filtrer aussi les Mangas ( comme les series donc) sans repeter tout le code ?

**Comment by TmpName** [comment]
> if ('-serie-' in sUrl2) or ('mangas' in sUrl2):

Paenthese pas obligatoire

J'ai commence le choix des saisons, ca deconne plein pot, le regex est pas bon, le squeltte est la mais ils ont des pages vides sur leurs site aussi.

**Comment by Kodigoal** [comment]
Mais si on met juste un lien a cliquez qui lance la recherche des autres saisons  avec le sTitle, ca devrait etre bon et moins chiant a faire?

**Comment by johngf** [comment]
@chataigne73 tu as remarqué mega T movie on mis des recaptcha ?

**Comment by chataigne73** [comment]
@johngf.  Et merdum un de plus, ou plutôt un de moins 
:-(

**Comment by TmpName** [comment]
Et la methode que j'ai commence a mettre en place pour les saisons ne te plait pas ? Je recupere juste les lien affiches sur la page, ils ont des liens mort mais il suffit d'afficher "pas de lien disponible".
En passant par la recherche, tu risque d'avoir des problemes pr trier les autres series qui vont apparaitre.

**Comment by Kodigoal** [comment]
si si xD c'était juste une idée comme ca. 
Juste si tu peux voir pour le soucis du code là,
Je trouve pas comment résoudre le soucis...

**Comment by TmpName** [comment]
C'est quoi le soucis ?

**Comment by camelone** [comment]
Je pense avoir trouvé un ptit bug.. quand on parcourt les films par genre, la première page est ok mais les suivantes sortent carrement du genre. Ex: animation, on se retrouve avec des films d'horreur sur les pages suivantes..

**Comment by Kodigoal** [comment]
Comme on affiche en mode poster , le but c'était mettre la saison avant le titre pour voir de suite sans faire défiler le titre si long mais bon c'est un détail.

Sinon c'est aussi H.S chez vous les liens hosters ? 
Oui ya un soucis niveau du NextPage pour les genres.

**Comment by chataigne73** [comment]
@Kodigoal      slt, je viens de modifier le pattern dans showhosters ...  ça devrait remarcher maintenant ... tu confirmes ?

**Comment by Kodigoal** [comment]
@chataigne73 C'est bon , Merci ^^

**Comment by Kodigoal** [comment]
Maj:
Correction du bug nextPage pour les Genres.
Modif affichage  qualité pour les Mangas/dessins-animes/spectacles/emissionTV. 
( Sinon on avait 'sd' pour tous et c'est pas le cas )
Modif affichage '[vostfr]' en minuscule , ca pique les yeux en Majuscule avec tout ce orange, mais
à rechanger si ca pose problème.
