### ISSUE TITLE
Idée  d'amélioration: sélection automatique des sources par préférences

### ISSUE THREAD

**Issue by flowtime** [Kodi-vStream/venom-xbmc-addons#704]
Bonjour,

une petite idée d'amélioration qui serait sympathique, (activable ou non via les paramètres).
Lorsque l'on rentre dans une série ou un film il existe plusieurs fournisseurs de contenu, il faut alors cliquer sur le fournisseur, et nous avons alors le lien de la vidéo.

Il serait sympathique de pouvoir activer une option qui permettrai de lire directement le contenu en sélectionnant les fournisseurs par préférence.
Ainsi par exemple, dans une série, lorsque l'on choisi un épisode, si la préférence 1 est youwatch le lien s'ouvre directement, si le fichier n'existe pas, la préférence 2 s'active, netu etc.
Il est peut-être compliqué de lister toutes les sources pour les sélectionner mais ça doit pouvoir s'arranger en limitant le nombre de préférences par exemple ou en posant la question sur un lien de contenu donné etc ..

Merci de votre attention ;)

**Comment by TmpName** [comment]
Nope pas possible. Rien ne fera mieux qu'un humain pour choisir la bonne source.
Selon l'age de la serie, l'heure de la journee, l'hebergeur teste precedement, le site en question, je choisit tel ou tel hebergeur, pas moyen de faire deviner ca automatiquent.

Si par exemple tu as mit youawtch  en premier, c'est bien a 10h du matin, mais le soir a 21h, tu vas te retrouver bloquer pendant 1 mn si tu as mit le timeout a 1mn, alors que tu sais tres bien qu'il faut jamais de YW apres 20h.

**Comment by flowtime** [comment]
Je suis d'accord avec le principe, c'est ce que tout le monde rencontre je pense. 

Pour ma part je choisi toujours les mêmes sources dans le même ordre d'où ma question. Le but n'étant pas de "deviner" mais d'appliquer des règles établis par l'utilisateur.
D'où l'intérêt de désactiver et/ou de remettre à zéro selon l'utilisation de chacun.

**Comment by TmpName** [comment]
Yep mais si tu programmes un truc de ce genre en cas de prb c'est la faute de Vstream, meme si c'est l'user qui a configure nawak. En l'etat on est sur a 100% que ca marche et a toi ca te coute juste un clic de plus.

En fait c'est une des regles de base de Vstream : c'est a l'utilisateur de bosser vu que c'est lui le plus doue.

Par exemple, on pourrait faire un filtrage sur les faux resultats de recherche par exemple, mais ca ferait disparaitre de bon resultat. du coup ca affiche n'importe quoi mais tout les bon resultats sont la.
L'ergonomie OK, mais uniquement si il n'y rien a perdre.

**Comment by flowtime** [comment]
Je comprends bien le soucis avec l'utilisateur et la responsabilité aie aie aie :+1: 
Vraiment dommage ça m'éviterait quelques énervements lol

**Comment by flowtime** [comment]
Ne pourrait on pas réduire d'un Click "quand c'est possible", c'est à dire ne pas avoir à rentrer dans "fournisseur" pour avoir le lien? Trop lourd? Pose également un problème?

**Comment by TmpName** [comment]
Lol, je dis pas que ce n'est pas possible, je n'ai pas tout les codes en tete, mais par exemple pour certains sites avoir le lien necessite un decodage, donc tu as la liste des liens et apres le clic, un lien tout seul, oui ce serait possible de supprimer un clic mais ca demanderait de decoder tout les liens a chaque fois meme si l'user n'en choisit qu'un ou aucun, et le decodage peut demander du temps sur certain site.

C'est mon avis perso, certains ont deja essaye de supprimer des clics, et meme y sont arrives parfois, mais en ce qui me concerne 3 clics me demandent moins de 2 s sur ma telecommande, sur la TV il y 15mn de pub pour 1h de serie, je ne trouve pas ces 2s en trop comme un probleme.

Jetes un oeuil aux codes, et tu verras le boulot que cela peut demander et les sources de bugs que ca peut provoquer juste pour 5s de perdue pr toi.

Des bidouilleurs donnent des astuces pr se simplifier la vie, eg faire demarrer directement sur une source, mais tu n'auras jamais ca par defaut sur la config officielle de base.

**Comment by flowtime** [comment]
Tu as bien raison :+1:  
J'ai bien vu le travail dans le programme! C'est du temps et du casse tête :+1: 

Avec la télécommande ps3 bluetooth c'est 2 secs comme tu dis ;) 
Merci pour ton explication j’entrevoyais déjà le soucis 

Je ferme la discussion :)
