### ISSUE TITLE
Idée d'amélioration: enregistrement de la position de la navigation

### ISSUE THREAD

**Issue by flowtime** [Kodi-vStream/venom-xbmc-addons#706]
Bonjour,
Lorsque l'on quitte Kodi, que l'on ferme Kodi plutôt, la position du curseur dans la navigation n'est pas mémorisé.
Serait-il possible de sauver cette position dans l'application?
Merci à vous :)

**Comment by TmpName** [comment]
Heu, c'est quoi la position du curseur ?
Vstream/film/site1 ?

**Comment by flowtime** [comment]
désolé si l'explication n'est pas claire :) Lorsque l'ont navigue par exemple dans les marques pages, le focus est sur le dernier lien choisi ou rentré. Lorsque l'on suit plusieurs séries cela permet d'aller directement à la saison, le numéro de l'épisode etc Jusqu'au redémarrage de kodi.

**Comment by TmpName** [comment]
Alors la, bne question ^^, je n'ai jamais vu de fonctions pour faire ca, mais c'est vrai que kodi memorise ca sur une session donc c'est peut etre possible.

Ca me servirait aussi ca. Faut voir si ca existe.

**Comment by flowtime** [comment]
Je cherche pour le moment google n'est pas mon ami. Question de mots clés. Je ne sais pas si c'est le skin ou l'interface qui se "souvient" de la position. ça serait permanent sur kodi directement ça serait plus simple mais rien trouvé pour le moment.

**Comment by TmpName** [comment]
Pareil, tjours rien, j'ai trouve du monde qui avait deja pose la meme question sur les forum de kodi mais pas de reponses.

**Comment by flowtime** [comment]
Oui pareil j'ai trouvé la question plusieurs fois sur divers forums. Après faire ça dans un script ça risque d'être lourd... ça implique de sauvegarder la position et de la rappeler.

Je n'ai pas trouvé dans quel cache se trouve cette navigation.

**Comment by TmpName** [comment]
Ben le truc c'est que je n'ai meme pas trouve de fonctions pour faire ca, la, je pense que les devs y ont meme pas pense.

**Comment by flowtime** [comment]
Je regarderai si je trouve, sinon je vais poser la question sur la localisation du cache, curieux :) Je ne pense pas que ça soit dans le thème mais ça reste possible.

**Comment by TmpName** [comment]
Suis pas sur que ce soit memorise dans un cache, car justement sur mes forums les gens demandaient un moyen que cela reste en cache apres une extinction de la machine. La, ca ne marche que si tu laisses tout allume.

**Comment by flowtime** [comment]
Oui, curieuse bête :)

Sur ce post je ne suis pas certain d'avoir compris les fonctions mais je pense que l'on peut faire son propre fichier de sauvegarde de la navigation et restauration
http://forum.kodi.tv/showthread.php?tid=94099&pid=723508#pid723508

getFocusId()? Je n'ai pas eu le temps de chercher aujourd'hui plus que ça je n'ai pas lu les détails proprement.

**Comment by TmpName** [comment]
Mais ca ca l'air pour des list 'custom' nous on utilise les fonction de base, on ne cree pas de nouvelle liste comme le font les createurs de skin.
On utilise aucun fichier xml avec des truc de ce genre
><control type="fixedlist" id="51">

sauf pour afficher les infos.
Je ne vois pas comment utiliser ca avec le code "de base".

**Comment by flowtime** [comment]
Bon je n'ai rien trouvé pourtant ça doit bien être stocker quelque part, au final cela concerne kodi directement

**Comment by Kodigoal** [comment]
Pêtre dans la ram

**Comment by TmpName** [comment]
Je pense aussi, car si tu fermes violement l'application ca pert tout.
