### ISSUE TITLE
kodi message d erreur 

### ISSUE THREAD

**Issue by thewolf51** [Kodi-vStream/venom-xbmc-addons#707]
salut;
j essaie de mettre en marche kodi nouvellement charger sur mon ordi  qui fonctionne sur windows 7 
toute les mise a jours sont faite  et ca affiche toujours cela 
ERROR: Unable to create GUL. Exiting

merci de votre aide 
Martin

**Comment by johngf** [comment]
salut il faudrait pensé a faire un minimum de recherche sur google avant de posté ici 
http://media-passion.fr/support-windows/error-unable-to-create-gui-exiting/
ou sur google kodi ERROR: Unable to create GUI. Exiting /page en français

ce serait un problème de carte graphique ou pilote de Carte graphique

**Comment by LordVenom** [comment]
Tu est plus rapide que le support de Kodi @johngf  :+1:
