### ISSUE TITLE
caracteres speciaux dans url

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#708]
salut
j'ai un soucis que je n'arrive pas à résoudre
j'ai affaire à une url contenant des caracteres speciaux, du style 
`http://site/telecharger-cigognes-compagnie-13-57478?rlz=Cigognes+%26+Compagnie+-+vfq+-+1080p+-+ac3&provider=0` 
 où le %26 notamment est un &

quand je passe cette url dans le parameterhandler
 `oOutputParameterHandler.addParameter('siteUrl', str(url))`
je la récupère comme ça
`sUrl = oInputParameterHandler.getValue('siteUrl')`
et le résultat est
`http://site/telecharger-cigognes-compagnie-13-57478?rlz=Cigognes & Compagnie - 720p&provider=0` 

et quand je le passe dans requesthandler le résultat est KO

auriez vous une idée ?

**Comment by johngf** [comment]
il faut encoder l'url

**Comment by johngf** [comment]
comment ut as fait pour arriver a cette url la recherche ne fonctionne pas chez moi

**Comment by chataigne73** [comment]
merci je vais essayer le quote ou unquote
je ne comprends pas ta remarque sinon ; pour moi tout fonctionne à présent dans ddl-island (recherches, tri par genre, etc...) 
testé ok aussi par Kodigoal

**Comment by johngf** [comment]
j'ai pris la derniere version et il ya que top film qui affiche quelque chose

**Comment by chataigne73** [comment]
je viens de retélécharger la dernière version (je le fais via click-droit+enregistrer le lien sous sur le bouton raw) et de le remettre dans Kodi ... tout fonctionne parfaitement ... je ne comprends pas  :-(

**Comment by johngf** [comment]
en tous cas pour ton url c'est a cause des espaces

**Comment by johngf** [comment]
le probleme vient surement de chez moi vstream n'est pas a jour

**Comment by johngf** [comment]
le probleme est le é de qualité

**Comment by chataigne73** [comment]
bon ben écoute je ne comprends pas ; perso, si j'enlève les accents cela ne marche pas, et tout fonctionne correctement avec les accents

**Comment by johngf** [comment]
peut etre que ça fonctionnera avec la prochaine maj avec le fichier inclus

**Comment by johngf** [comment]
pour ton url sUrl = sUrl.replace(' ','+')

**Comment by chataigne73** [comment]
bon, pour moi ça marche avec ça  `sUrl = sUrl.replace(' & ','+%26+').replace(' ','+')`
mais franchement je trouve pas ça super propre

**Comment by johngf** [comment]
tu as essaiyé urlib.urlencode

**Comment by chataigne73** [comment]
oui, ça ne marchait pas
le pb vient en fait du & dans le nom du film, pas des espaces

PS : tout de même, le fait que le site ne fonctionne pas chez toi m'interpelle   :-s
j'ai vérifié, on utilisait déjà sans pb des é dans les patterns de ZT

**Comment by johngf** [comment]
en enlevant les é si @TmpName avait le meme soucis hier

**Comment by chataigne73** [comment]
je pense que ça doit venir de la manière dont vous récupérez le fichier sur le github

**Comment by johngf** [comment]
bah copier coller en raw

**Comment by johngf** [comment]
ça fonctionne avec ça sUrl = urllib.quote(sUrl, safe=':/.+?&')

**Comment by chataigne73** [comment]
moi je télécharge le fichier, je ne fais pas de copier coller (click droit enregistrer sous sur le bouton raw du fichier concerné)

**Comment by chataigne73** [comment]
sUrl = urllib.quote(sUrl, safe=':/.+?&') ne fonctionne pas

**Comment by johngf** [comment]
bah chez moi si niveau 
def showHosters():# recherche et affiche les hotes
    print "showHosters"
    
    oGui = cGui()
    oInputParameterHandler = cInputParameterHandler() #apelle l'entree de paramettre
    sMovieTitle = oInputParameterHandler.getValue('sMovieTitle')
    sUrl = oInputParameterHandler.getValue('siteUrl')
    sThumbnail=oInputParameterHandler.getValue('sThumbnail')
    xbmc.log(str(sUrl))
    sUrl = urllib.quote(sUrl, safe=':/.+?&')

**Comment by chataigne73** [comment]
tu es en encodage UTF-8 dans le menu "encoding" de notepad++ ?

**Comment by johngf** [comment]
oui

**Comment by johngf** [comment]
c'est a cause de ça les accents ?

**Comment by johngf** [comment]
en tous cas `sUrl = urllib.quote(sUrl, safe=':/.+?&')` chez moi c'est ok

**Comment by chataigne73** [comment]
moi si je le mets , le tri des releases n'est pas fait et cela retourne tous les liens de toutes les qualités
par ex : films / derniers films hd / cigognes / choisir 720p (1er lien)     --> cela doit retourner 10 liens (OK avec mon fichier maintenant en ligne sur le github)

si je mets `sUrl = urllib.quote(sUrl, safe=':/.+?&')`  --> cela retourne tous les liens de toutes les qualités, soit environ 26 liens

**Comment by johngf** [comment]
a oui lol j'avait pas fait gaffe donc laisse la première soluce des fois il y a pas le choix

**Comment by TmpName** [comment]
Oui, j'avais un prb avec les accents, c'est plutot le genre de trucs a eviter, pour faire tourner le code j'ai remplace les caracteres accentue par 2 '.' dans le regex.
télécharger > t..l..chargez

Sinon pour le prb d'url avec urllib.quote_plus(url, ':&=') ca marche pas ? ca remplace les espace par des +
Apres c'est sans plus pour avoir les %20
