### ISSUE TITLE
Pb détection protection cloudfare

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#709]
je suis sur un site protégé par cloudfare, mais ladétection de protection que nous avons en place ne fonctionne pas
dans requesthandler : 
`except urllib2.HTTPError, e:
            if e.code == 503:
                if cloudflare.CheckIfActive(e.headers):
                    cookies = e.headers['Set-Cookie']
                    cookies = cookies.split(';')[0]
                    print 'Page protegee par cloudflare'
                    from resources.lib.cloudflare import CloudflareBypass
                    sContent = CloudflareBypass().GetHtml(self.__sUrl,e.read(),cookies)`

dans le cas de mon site , le texte "Page protegee par cloudflare" n'est pas présent dans les headers mais dans le e.read()

normal ?

**Comment by johngf** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/series_en_streaming_tv.py
regarde si ça peut t'aider

**Comment by chataigne73** [comment]
en effet merci pour la piste johngf

mais je préfèrerais faire évoluer le requesthandler
il suffirait de modifier  `if cloudflare.CheckIfActive(e.headers):`
en
`if cloudflare.CheckIfActive(e.read()):`   et ça marche dans mon cas

mais je ne me permets pas de toucher aux lib sans avis des pros

**Comment by TmpName** [comment]
Ha oui merde, c'est ma faute, quand ils ont mit a jour j'ai corrige le fichier cloudflare.py mais pas le fichier requesthandler.
Je fais ta modif de suite.
