### ISSUE TITLE
Tester la beta de Vstream

### ISSUE THREAD

**Issue by mako83** [Kodi-vStream/venom-xbmc-addons#710]
Bonjour,

Je voudrais savoir comment fait on pour essayer la beta de Vstream :)

Merci d'avance

**Comment by LordVenom** [comment]
Tu la télécharge direct depuis la page d’accueil du Github. Ensuite vue que c'est une bêta et qui bouge énormément des base sur l'utilisation de Github et fortement recommender.

**Comment by johngf** [comment]
en faite il veut avoir ddl island lol

**Comment by LordVenom** [comment]
Ben reste qu'il a un compte github et qu'il peux remonter les bug quand c'est bien fait ça aide pas mal.

**Comment by johngf** [comment]
je me trompe ou la beta est mise a jour a partir de la master ?

**Comment by mako83** [comment]
Bonjour , 

Oui c’était pour ddl island et aussi pour tester la beta:) mais aussi pour ajouter ma propre source plus tard j'essaie d'apprendre petit à petit.

Alors j'ai reussi en telechargant le fichier depuis la page d’accueil github puis j'ai transformé le fichier présent dans le zip "plugin video vstream" en zip et installé depuis ma tv android :)

C’était la bonne méthode? ou il y a une autre méthode?


En tout cas vous faite un sacré bon jb

**Comment by TmpName** [comment]
Moi j'utilise la methode bourrin, je change le nom de la version officielle que je met de cote et je copis le contenu du zip par dessus la version deja installée. Si ca te demande une confirmation pour ecraser les fichiers existant c'est que c'est rate.

Et je peux me tromper, mais le repo ne marche que pour la VO.

**Comment by LordVenom** [comment]
Attention la mise a jour des sources ce fait depuis master.a éviter si vous utiliser la beta.

**Comment by LordVenom** [comment]
C'est pas une bonne idée si tu ne pense pas nous aider tu vas avoir du mal a suivre les Pulls pour te faire une idée https://github.com/Kodi-vStream/venom-xbmc-addons/commits/Beta. Voila à la vitesse que ça bouge :100:

**Comment by TmpName** [comment]
Pour info @Gregwar  a fait passer 2 nouvelles sources a tester.
ZT.eu et Frenchldd

**Comment by Gregwar** [comment]
En vrai ça serait faisable d'avoir un menu dans vStream pour passer en beta

**Comment by TmpName** [comment]
Yep, mais je trouve ca bien, ca permet d'eviter que tout le monde soit sur la beta.
Au moins comme ca on est sur que le mec a deja quelque notions en bidouille  avant de tester. Regarde le nombre de personne qui ralent sur la V17 de kodi alors que c'est encore une version de developpement.
