### ISSUE TITLE
ddl island

### ISSUE THREAD

**Issue by moimeme45** [Kodi-vStream/venom-xbmc-addons#712]
bonjour a tous 
je viens de mettre le fichier  DDL island ça fonctionne bien le seul soucis c'est que j'ai un compte 1fichier 
premium  et ce site ne propose pas de liens :-(

vous serait il possible de faire la même chose avec un site qui propose du 1 fichier premium.

je n'y connais rien en code et suis bien content de vous lire et tester votre travail

encore merci.

:-)

**Comment by johngf** [comment]
il a d'autre site avec des liens 1fichier ex le site film vostfr le nom est trompeur parce qu'il y a les deux vf et vostfr

**Comment by TmpName** [comment]
Strea ming GK propose aussi des liens 1fichier, suis tombe dessus hier. Mais j'ai pas regarde la qualite de la video.

**Comment by johngf** [comment]
Il y a meme des sites ou les liens pour ce type'dhebergeur ne sont pas pris en compte dans le script

**Comment by TmpName** [comment]
Yep, je sais, mais a l'epoque c'etait presque voulu, la maintenant c'est plutot un truc a faire ...

**Comment by noipo** [comment]
Tu peux partager le py dll island ?
Merci

**Comment by Kodigoal** [comment]
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/ddl_island_su.py

**Comment by noipo** [comment]
Par contre quand je sélectionne uptobox et tout les autre hébergeurs ça me dit erreur :(

**Comment by moimeme45** [comment]
salut.
bon j'ai envoyer un mail pour leur demander de mettre des liens 1 fichier pas de réponse :-( tant pis pour moi mais vous avez fait un super boulot pour ce site.
sur la bêta je vais voir megatrckmovies il y a quelques lien 1 fichier mais ça marche mal.
jaquettes pas bonnes quand on clique sur le lien  souvent fichier non disponible !
j'ai été voir sur leur site quand je suis dessus firefox me dit "site d'hameçonnage" avast me dit ça aussi.
j'ai vraiment pas de bol pour mes liens 

ciaooooo

**Comment by noipo** [comment]
cela ne fonctionne pas, voilà ce que j'ai dans le log : 
14:38:32 T:7880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: cRequestHandler instance has no attribute 'GetCookies'
                                            Traceback (most recent call last):
                                              File "C:\Users\tufar\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 169, in <module>
                                                main()
                                              File "C:\Users\tufar\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 31, in __init__
                                                self.parseUrl()
                                              File "C:\Users\tufar\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 81, in parseUrl
                                                exec "plugin."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\tufar\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\ddl_island_su.py", line 717, in Display_protected_link
                                                sHtmlContent = DecryptddlProtect(sUrl)
                                              File "C:\Users\tufar\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\ddl_island_su.py", line 782, in DecryptddlProtect
                                                cookies = oRequestHandler.GetCookies()
                                            AttributeError: cRequestHandler instance has no attribute 'GetCookies'
                                            -->End of Python script error report<--

**Comment by johngf** [comment]
c'est normal met a jour vers la 4.7 ça sera ok

**Comment by noipo** [comment]
direct depuis l'addon ?
