### ISSUE TITLE
Vstream c'est vraiment de la bombe

### ISSUE THREAD

**Issue by therudy** [Kodi-vStream/venom-xbmc-addons#719]
Hello !

Merci beaucoup à ceux qui ont créer vstream, c'est vraiment de la bombe... sur raspberry je me régale !!

C'est juste dommage qu'il n'y ai pas plus de site de manga, ou tout du moins les principaux comme gum gum streaming, car c'est compliqué de trouver dragon ball z :(  en tout cas je m'en sert tout les jours de vstream, et c'est une tuerie

merci beaucoup au créateurs !

**Comment by johngf** [comment]
il y 3 site principal de manga manga city ad kami otaku fr dbz y est présent un peu de recherche...

**Comment by johngf** [comment]
par contre @LordVenom j'avait activé adkami pour la recherche d'anime tu l'as enlevé c'est voulu ou une erreur ?
