### ISSUE TITLE
Z-T is Back

### ISSUE THREAD

**Issue by K3R0ZEN** [Kodi-vStream/venom-xbmc-addons#720]
Salut tout le monde et en particulier au pti génie de Vstream. ZT à publier une news comme quoi il etait de retour zone-telechargement.ws 

Si vous pouvez nous faire la mise a jour sur Vstream sa serai super sympa se votre part.

Bonne soirée ;)

**Comment by johngf** [comment]
c'est une copie

**Comment by chataigne73** [comment]
1/ c'est un fake, et la BDD est quasiment vide (plus aucun ancien film par exemple)
2/ le système de protection des liens n'est pas contournable par vstream

**Comment by K3R0ZEN** [comment]
Merdouille..

Sinon je cite le communiqué de ZT : Bonsoir,

Comme vous le savez tous, le domaine Zone-Telechargement.com a été fermé , aussi les serveurs, nous essayons de récupérer la base de données sur cette nouvelle adresse , merci de patienter et partager cette information.

Espérons donc que le catalogue de film continue a s'enrichir et que la protections des liens devienne contournable.

**Comment by johngf** [comment]
D'autre disent que c'est un faux compte facebook ou tu as lu ce message

**Comment by K3R0ZEN** [comment]
En faite au tout début de ZT il y a quelques années il avait créé se compte facebook pour faire un peu de communication, puis le site prenant de l'envergure et pour éviter tout problèmes il ont fini par dire que cela n'avait rien d'officiel ...

Quoi qu il en soit que le nouveau zone téléchargement soit vrai au faux il est une copie de l'autre et donc parfaitement bien présenter a mon goût.  Choix de qualité de langue belle presentation et j'en passe.

Pour l'instant je n'ai pas trouvé mieux et j espère vraiment qu il finira par être compatible avec Vstream.

**Comment by lebigboss59** [comment]
En tout cas une belle copie de l'ancien même si il n'y a pas les anciens fichiers, au moins il y a du HD et plusieurs liens valide de plusieurs hébergeur, ce qui donne plus de choix.

Autant faire semblant de croire que c'est la ré-ouverture de l'ancien ZT

**Comment by mino60** [comment]
j ai essaye de faire un script pour Zt le nouveaux site mais je n arrive pas a decoder le dl-protect

zone-telechargement.ws

http://pastebin.com/KqsCGeHF

![sans titre](https://cloud.githubusercontent.com/assets/11494048/21076151/7306c31a-bf24-11e6-9db0-dff4fb876bd3.png)



h ttp://www.zone-telechargement.ws/nouvelle-adresse.html

h ttp://majax31isnotdown.blogspot.com/2016/11/sites-warez.html

**Comment by K3R0ZEN** [comment]
Bien joué Mino. J'ai cru comprendre que le problème avec ce nouveau site réside dans le nouveau dl protect. Je me demande juste si c'est possible mais difficile ou juste si c'est impossible ?

Je ne suis pas assez caler pour cela mais en tout cas je te remercie d'essayer. ..

**Comment by Kodigoal** [comment]
Il utilise recaptcha non ? donc pas possible pour le moment

**Comment by lebigboss59** [comment]
C'est bien du recaptcha 
![capture](https://cloud.githubusercontent.com/assets/24246566/21076690/3e452190-bf32-11e6-9f7a-6b5b3b1dd87c.PNG)

**Comment by mino60** [comment]
Pour moi le meilleure site pour les films et les series c est 
http://www.telecharger.planete-series.info/films-hd/

**Comment by arzaz** [comment]
Je suis tout a fait d'accord avec toi mino60 surtout pour les qualités HD.

**Comment by K3R0ZEN** [comment]
Mino on est quand même loin de l'excellence que ZT avait atteint. La je constate qu'il y a beaucoup moins de truefrench et de choix de qualité. 

Mais il faut reconnaître que sa reste intéressant, je ne crache pas dans la soupe..

**Comment by lebigboss59** [comment]
Moi je trouve qu'il y a 2 ou 3 site vachement mieux que Planete-serie
Je dirai que aujourd'hui il est 4ème ou 5ème dans mon classement 
D'ailleurs je vais plus du tout sur Planete serie depuis un moment, bizarrement le site était plus intéressant quand il s'appelait wawa-....

**Comment by K3R0ZEN** [comment]
Lebigboss, vu qu'on est en plein dedans, partage ;-)

**Comment by doubidave** [comment]
C est celui ci?

http://www.fredzone.org/zone-telechargement

**Comment by doubidave** [comment]
Sorry mauvais lien

http://www.fredzone.org/zone-telechargement-est-de-retour-pour-de-bon-cette-fois-773

**Comment by chataigne73** [comment]
https://www.undernews.fr/warez-telechargement/zone-telechargement-de-retour-et-fonctionnel.html

regardez bien la conclusion du dernier paragraphe

**Comment by koala784** [comment]
Bonjour, étant plutôt intéressé par du VOSTFR, mais ayant des connaissances préférant les VF, le DL ou le streaming sur Vstream avec ZT était pour moi plutôt pertinent (possibilité de choisir entre SD, 720p ou 1080p, et en TF, VOSTFR ou Multi selon la qualité choisie).

J'ai essayé tout les sites proposés sur Vstream, mais le résultat est loin d'être comparable à ZT.

Le nouveau ZT.ws, que ce soit un clone ou non, me semble la solution la plus proche de ZT, mais le système de recaptcha empêche, à l'heure actuelle, d'en faire une solution viable pour Vstream.

Auriez-vous une combinaison de sites (films, séries et animes), déjà disponible sur Vstream,  permettant de se rapprocher du système de qualités et de langues que ZT proposait ?

Sinon, une combinaisons de sites non-présents sur Vstream, que je pourrai tenter d'ajouter en source ?

Veuillez m'excuser si je m'exprime sur le mauvais topic :)

**Comment by johngf** [comment]
Il y a sur vstream sur les autres sites du 1080 du 720 480 etc.. du vf du vostfr du dl et autres 
Il faut juste ce donné la peine de cherché ce que les personnes accros a zt ne font pas

**Comment by koala784** [comment]
Je me suis mal exprimé. Je recherche principalement des liens en multi (VF et VOSTFR).
J'ai déjà essayé toutes les sources de Vstream. Bien souvent, les liens 1080p sont en VF, et les liens VOSTFR dépassent rarement du 480p.

Edit : J'ai activé toutes les sources dans les paramètres de Vstream (en activant également les 3 champs de recherches : films, séries et animes) , je viens de toutes les réessayer : 

-Films -> Films (qualité HD) -> toutes les sources proposent du 720p et du 1080p, mais uniquement en VF
-Séries -> Séries (qualité HD) -> toutes les sources proposent du 720p et du 1080p, mais uniquement en VF
- Séries -> Séries (VOSTFR) -> toutes les sources proposent du VOSTFR, mais au mieux en 480p

- Recherche -> Recherche 1: Films -> j'ai écris "VOSTFR" -> au mieux de la VOSTFR en 480p
- Recherche -> Recherche 2: Séries -> j'ai écris "VOSTFR" -> au mieux de la VOSTFR en 480p

Étant donné que ce topic a été fermé alors que je relève des questions pertinentes, je vais ouvrir un topic intitulé "VOSTFR/MULTI 720p/1080p".
