### ISSUE TITLE
Besoin d'aide pour ajout de source

### ISSUE THREAD

**Issue by bilal28100** [Kodi-vStream/venom-xbmc-addons#721]
Salut à tous et ravi de vous rejoindre je suis un fervant utilisateur de vstream et j'aimerais savoir si c'est possible de rajouter une source qui contient des films dans une autre langue. En fait je voudrais rajouter une source pour de films turk car j'ai un ami qui me demande. Mon second probleme c'est que j'essaye tant bien que mal de creer le fichier .py et jusqu'ici j'ai seulement réussi a faire apparaitre le nom du site dans la liste des sources et direct gros message d'erreur de vstream. J'aimerais savoir si l'un d'entre vous avais les competence pour m'aider à le faire si cela est possible. d'avance merci

**Comment by LordVenom** [comment]
Salut,
Il vas falloir avancer un maximum pour que l'on regarde et en ce moment ont et sur la mise a jour mensuel donc un peux de patiente. Tu code un maximum et tu nous partage le code sur http://pastebin.com/

**Comment by bilal28100** [comment]
Ok merci pour cette réponse très rapide. Je vais faire de mon mieux pour préparer la chose mais n'ayant aucune connaissance dans ce milieu il faudra pas se moquer de mon résultat.

**Comment by LordVenom** [comment]
C'est pas le genre de la maison :+1:
