### ISSUE TITLE
nouveau moteur de recherche 

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#726]
Bonjour à tous serait-il possible de rajouter ce moteur de recherche h ttp://1fichier-uptobox.com/
Avec la possibilité de copier les liens sur son compte premium uptobox merci d'avance

**Comment by johngf** [comment]
Ce n'est pas vraiment un moteur de recherche il utilise google pour trouver des sites ou il y a peut etre ce qu 'on cherche et non des liens directement

**Comment by sebi0606** [comment]
Ok merci @johngf effectivement à l'usage pas top
