### ISSUE TITLE
Bug depuis le 12/12?

### ISSUE THREAD

**Issue by doubidave** [Kodi-vStream/venom-xbmc-addons#731]
Bonjour, depuis ce matin j observe de droles de phénomènes sur vstream.

Lorsque je fais une recherche, la vue change et passe automatiquement en vue miniature meme si je remet la vue "liste" avant par exemple.

Toujours dans la recherche, je remarque qu il ne trouve plus de résultats sur certains sites alors qu ils apparaissent bien quand on recherche manuellement depuis l onglet source. Par exemple sur film illimite. Hier j ai commencé a regarder un film et aujourd'hui il ne sort plus, mais si je vais sur l onglet source il est bien là.

Je ne sais pas si j ai bien expliqué. Encore merci pour votre travail en tous cas.

**Comment by johngf** [comment]
pour la recherche certain site ne sont pas activé pour la recherche global c'est a toi de les activé dans les parametres de vstream niveau plugin on off activer/desactiver

**Comment by doubidave** [comment]
Et c est censé se désactiver seul? Parce que hier tout fonctionnait et je n ai rien touché depuis. J y jetterai un oeil dès que possible alors. Merci pour la réponse.

**Comment by johngf** [comment]
le prob est ddl island desactive le  pour la recherche globalet c'est ok

**Comment by doubidave** [comment]
Ca roule, merci beaucoup pour l aide 😊

**Comment by doubidave** [comment]
Alors je viens de faire tout ce que tu as dis et le bug visuel est bien corrigé mais le reste non. J ai tout d activé dans les parametres sauf zone et ddl qui n apparaissent donc plus dans les résultats.
Par contre pour mon exemple de film illimite je vois qu il n y a pas le "activer/desactive"r comme les autres.

**Comment by doubidave** [comment]
My bad, ca apparait maintenant. Par contre pour ne plus avoir de bug, je dois laisser tomber ZT et ddl pour le moment si j ai bien compris.

**Comment by doubidave** [comment]
Par contre bizarre, j ai voulu les remettre pour tester et meme en les activants ils n'apparaissent plus dans la liste. 

Bon, ben je suppose qu une maj reglera ca a un moment.

Merci ^^

**Comment by johngf** [comment]
peut etre le decalage dans settings.xml qui crée ça

**Comment by doubidave** [comment]
Ca va devenir trop compliqué pour moi je sens 😁

J espere que maj réglera ça ^^

**Comment by johngf** [comment]
oui vaut mieux attendre

**Comment by lebigboss59** [comment]
Chez moi DDL Island ne fonctionne plus depuis la MAJ d'aujourd'hui
Aucun lien n'apparait et pourtant le site n'est pas down

**Comment by LordVenom** [comment]
@doubidave 

`Par contre bizarre, j ai voulu les remettre pour tester et meme en les activants ils n'apparaissent plus dans la liste.`

Quelle liste ? ben non rien a voir avec settings puisqu'il peux les activer.

**Comment by doubidave** [comment]
Par exemple ddl island. Meme si je le réactive il n apparait plus. ZT etait revenu mais il faisait bugger la vue et je n arrivais a rien lancer depuis cette source alors je l ai enlevé. Merci

**Comment by johngf** [comment]
En plus d'activer il faut activer 1 2 3 ou 4selon ce que tu veut cherché 1= film 2=serie 3=anim 4=docu

**Comment by doubidave** [comment]
J ai aussi testé avec les numéros selon les informations entre parenthèses mais ca n a rien changé. Je réessayerai ce soir.
 Je suis le seul a avoir ce problème?

**Comment by johngf** [comment]
Quand tu dit il n'apparait plus c'est ou dans sources ?

**Comment by doubidave** [comment]
Non quand je fais une recherche. Normalement meme s il ne trouve rien, le nom du site apparait mais ici il n apparait nullepart hormis dans source et ds les paramètres.

**Comment by doubidave** [comment]
Si ca peut aider ddl island n apparait chez moi que dans toutes les sources. Dans sources de films et serie il n apparait pas alors qu il est bien activé en recherche 1 et 2 dans les parametres.

**Comment by johngf** [comment]
Il faut laisser ouvert tans qu'il'ya un bug

**Comment by doubidave** [comment]
Je sais meme pas comment j ai clôturé le sujet mais ce n etait pas intentionnel. Désolé.

**Comment by TmpName** [comment]
Dans les nouvelles sources dans showmovies')
>    #tPassage en mode vignette sauf en cas de recherche globale
    if not bGlobal_Search:
xbmc.executebuiltin('Container.SetViewMode(500)')

**Comment by doubidave** [comment]
Je ne sais pas si c est aussi lié, mais sauf erreur, sur film-streaming.co le film se lance automatiquement en SD. J ai par exemple regardé miss peregrine samedi via cette source et quand je cliquais sur le lien il y avait 2 choix HD et SD. J avais testé sur d autres films et il y avait parfois 3 choix de qualité. Maintenant lors de mes tests il n y a systématiquement plus aucun choix et c est le SD qui se lance.
Je ne sais pas si quelqu'un a remarqué la même chose...

**Comment by johngf** [comment]
chez moi ça fonctionne après des fois il y a qu'un seul choix donc il se lance auto

**Comment by doubidave** [comment]
Je me doute mais dans ce cas ci j ai eu et vu la hd puis le lendemain je n ai plus ce choix. En plus si ca fonctionne encore chez toi ca m inquiète encore plus... parce que la pour le coup je sais pas comment revenir aux choix que j avais zncore samedi.

**Comment by TmpName** [comment]
Tu as du confondre, il y a toujours qu'un seul hebergeur pr stre aming co et c'est chez eux, Et il se lance plus vite du coup vu qu'il n y a pas de selection d hebergeur.

**Comment by doubidave** [comment]
Je suis pratiquement sur car pour peregrine on a regardé la bande annonce qui est proposée juste sous le lien avant. Bon, peut etre que le site ne le propose plus tout simplement.

**Comment by johngf** [comment]
Il a raison sur streaming co il y a un choix maintenant car on doit passé par le m3u8 j'ai fait la modif il y a un moment @TmpName

**Comment by doubidave** [comment]
Je vais retester ce soir avec tous les liens un par un. On verra si au moins un fonctionne. Merci pour les réponses.

**Comment by TmpName** [comment]
Ha ?
En fait j'ai teste sur le site directement, et j'ai pas vu de selection, et la modif est passée inapercue chez moi ^^. 
Sinon je viens de tester du coup, et effectivement y a du nouveau que j'avais pas vu, mais j'ai pas eu de bol, 1 seule source a chaque fois, apres le code a l'air bon, ca vient surement du site.

**Comment by johngf** [comment]
en faite tu t'est trompé de site c'est hd stream in @doubidave

**Comment by johngf** [comment]
@TmpName si tu veut voir  la popup film les plus vues/film stre am co/camping

**Comment by doubidave** [comment]
J en suis pas certain. Sur hd stream je n ai aucun résultat de recherche. Et lorsquz je vais sur toutes les sources, j ai beau cliquer sur un film il ne se passe rien.

Sur film stream co je viens de tester les 3 camping sur mon autre raspberry et je n ai aucun choix c est directement en SD.

C est étrange car je n ai touché a rien depuis lors...

**Comment by johngf** [comment]
Tu n'as pas un pc windows ou autre avec kodi pour voir si ça fonctionne parceque chez'moi c'est ok sur 2 pc w7'et linux donc...

**Comment by doubidave** [comment]
Voila je viens d essayer sur win 10 et j ai les memes résultat que sur raspberry. Je ne comprend pas. :-S

**Comment by TmpName** [comment]
Ben je viens de tester camping3 sur film les plus vue film stre am co, pas de popup non plus.

**Comment by johngf** [comment]
oui je viens de voir je n'ai plus la popup non plus maintenant alors que avant oui sur camping bizarre

**Comment by doubidave** [comment]
Hd str chez moi ne fonctionne pas. Il n ouvre aucun film.

**Comment by johngf** [comment]
chez moi ok hd stre am in

**Comment by doubidave** [comment]
Peut etre la prochaine maj reglera ca... j espère... j ai testé sur raspberry et mon pc.

**Comment by johngf** [comment]
il y a un soucis je jette un oeuil sur film stream co

**Comment by TmpName** [comment]
nope, je pense que lui est bon, je regarde le fichier, il n 'y avait qu'un lien dedans, vu que c'est eux qui hebergent les liens, ils doivent faire en fonction de leurs humeurs. Pour HDstrmin la c'est bizarre par contre.

Sinon quand je suis passe par internet, y avait une protection bizarre qui me demandait de passer pr google.

**Comment by doubidave** [comment]
Je ne comprends pas trop non plus comment ca peut marcher ailleurs. On utilise la meme chose quand meme non?

**Comment by johngf** [comment]
bon apres miss machin sur leur site na pas plusieurs qualité @doubidave

**Comment by doubidave** [comment]
Merci pour votre aide en tout cas. Je ne comprend pas trop mais je suppose que comme je n ai touché a rien ca marchera bien a un moment  🤔

Hd machin qui va chez vous et pas chez moi c est bizarre

**Comment by johngf** [comment]
Comme dit @TmpName il faidrait nous montré les log xbmc.log

**Comment by doubidave** [comment]
Ok je vais essayer de comprendre votre demande et des que j ai je vous dis.

**Comment by TmpName** [comment]
Ca bug tjours depuis ta MAJ ?

**Comment by doubidave** [comment]
Depuis la maj, j ai de nouveau le choix avec hd et sd sur fstreamco 😊

Je viens de faire un test, island et zone( activés dans paramètres)ne sortent toujours pas quand je lance une recherche mais le bug d affichage semble avoir disparu. Encore merci pour le suivi et votre travail 🤗
