### ISSUE TITLE
Problème d'affichage depuis la version 0.4.7

### ISSUE THREAD

**Issue by EruIluvatar2** [Kodi-vStream/venom-xbmc-addons#736]
Bonjour ;a vous tous

Merci beaucoup pour votre beau travail

Depuis la version 0.4.7, j'ai un problème d'affichage avec Kodi 16.2 (PC), SPMC 16.4.2 et SPMC 16.5.2

![image](https://cloud.githubusercontent.com/assets/24532921/21118159/9ee5ba60-c08a-11e6-9222-feaf57220fc4.png)

Est-ce que c'est uniquement un problème de mon côté ?

Merci beaucoup

**Comment by LordVenom** [comment]
A verifier changer de theme et la langue de kodi en français.

**Comment by EruIluvatar2** [comment]
Merci beaucoup LordVenom, j'ai changé mon langue de Francais (Canada) à Francais et tout semble bien fonctionner.

**Comment by mannou78** [comment]
Salut, comment on fait pour ceux qui preferent l affichage dans une langue autre que le francais (Anglais par exemple). Serait-ce possible de fixer ce bug s'il vous plait

Merci bien

**Comment by zerud** [comment]
Salut, 
oui j'ai eu le même problème avec mon Kodi sous Windows.  

 Il semble avoir une erreur dans le fichier (strings.xml) dans le répertoire 
Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\language\English J'ai recopier le fichier strings.xml du répertoire \french et cela fonctionne avec les langues (Anglais et Français Canada)

notez que \xxx est l'user name que vous utilisez et que le répertoire AppData est un dossier caché de windows.  Si vous ne savez pas comment afficher les dossiers cachés, je vous suggère de ne pas faire cette manip et de changer votre langue de Kodi en français.

**Comment by TmpName** [comment]
J'y jette un oeuil de suite.

**Comment by TmpName** [comment]
Pas de bol c'etait juste a cause de quelques majuscules, j'ai corrige les fichiers mais par contre les modifs ne se feront qu'a la prochaine MAJ complete.

**Comment by zerud** [comment]
Super Merci....
Continuer votre bon travail !

**Comment by mannou78** [comment]
Salut, Je viens de mettre a jour l add-on et le probleme d affichage n est pas encore resolu.

Merci pour le super travail!

**Comment by Kodigoal** [comment]
Copie-colle dans Kodi\addons\plugin.video.vstream\resources\language/English/ string.xml
la maj du fichier:
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/language/English/strings.xml

**Comment by TmpName** [comment]
Yep, le probleme ne sera resolu qu'a la prochaine MAJ complete, c'est a dire dans 1 mois, si on fait la MAJ de suite, sa va la redeclencher chez tout le monde et comme on est le 15 du mois, ca va faire un traffic enorme sur le serveur.
Pour le moment la seule solution c'est de faire comme dit @Kodigoal
