### ISSUE TITLE
Vstream plante le systeme avec Sokrostream

### ISSUE THREAD

**Issue by raco82** [Kodi-vStream/venom-xbmc-addons#737]
Bonjour, 
j'ai du mal à savoir si cela vient de la dernière mise à jour du plugin ou de la mise à jour du site sokrostream qui sont arrivées en même temps, mais kodi plante  integralement lorsque je tente d'accéder à sokro par tout les moyens (recherche, dernier film, derniere serie, etc) que ce soit sous windows, raspberry et android.

une issue? désactiver sokrostream? de retour dans une prochaine mise à jour?

**Comment by johngf** [comment]
il a été mis a jour https://github.com/Kodi-vStream/venom-xbmc-addons/commits/Beta

**Comment by raco82** [comment]
mis a jour dans la beta? parce pas à jour dans l'officiel en tout cas

**Comment by johngf** [comment]
Si j'ai eu la maj ce matin

**Comment by TmpName** [comment]
Dans 3 jours max apres ta derniere MAJ, tu devrais avoir l'icone pour mettre a jour sur la page d'acceuil de Vstream.
