### ISSUE TITLE
Ajouter une source sport

### ISSUE THREAD

**Issue by JaqenGOT** [Kodi-vStream/venom-xbmc-addons#738]
Bonjour, tout nouveau sur le site. Je tiens tout d'abord a féliciter la team vstream pour le travail que vous faite. 
Etant fan de NBA, je voulais savoir si c'était possible d'ajouter une source sport tel que http://tvrex.net/.
Je sais que cela est possible car cette source a été développé par NATKO1412  dans son addon castaway. Mais apparemment l'addon ne fonctionne plus ou n'est plus mis à jour d'après son tweeter.
Je ne suis pas développeur, donc si il y a des tutos pour pouvoir le faire, je suis prêt à me lancer et a contribuer à faire avancer le projet vstream, sinon si quelqu'un connaît la procédure et puisse le faire ça serait super.
Merci davance

**Comment by Kodigoal** [comment]
http://pastebin.com/2e5UJHVL
A copier/coller dans un fichier a créé tvrex.py et à mettre dans le répertoire /sites/ de Vstream.
Vite fait donc ya que les Replay de cette saison et 2016 playoffs ( pas toutes) qui fonctionnent.
A revoir pour les replay 2015 et all star Weekend.
Pour le Live le plus important je suppose? 
A voir quand ya des matchs diffusés pour voir
comment c'est foutu.
Si t'as bien tout copier, ca sera pour test ici :
Menu Sport/Tvrex/

**Comment by JaqenGOT** [comment]
Je copie dans un fichier texte? 
Pour les replays et le live oui en priorité, mais le reste aussi.
Merci, je vais tester ça en espérant que cela fonctionne

**Comment by Kodigoal** [comment]
Oui  , bien le nommer tvrex.py

**Comment by JaqenGOT** [comment]
Ok. Par contre je trouve pas le répertoire /sites/ de Vstream.
Je vais bien dans programme/Kodi/addons/. La j'ai.plusieurs dansons mais pas Vstream??

**Comment by JaqenGOT** [comment]
C'est bon j'ai trouvé désolé. Je vais test

**Comment by JaqenGOT** [comment]
C'est bon j'ai bien le lien tvrex dans menu sport, mais par contre depuis la.mise à jour de vstream, chaque lien ou je clik ça me met une erreur. Donc je peux pas tester si tweed fonctionne. Une solution pour l'erreur vstream?attendre une mise à jour?avancer de 3 jour la date??

**Comment by Kodigoal** [comment]
C'est a dire? erreur sur les liens vidéos openload?
ou pour rentrer dans les sous-menus tvrex?

**Comment by JaqenGOT** [comment]
N'importe quels liens, de n'importe quelle sources ne fonctionne. Que se soit pour les films, series. Erreur vstream.

**Comment by JaqenGOT** [comment]
C'est depuis que j'ai fait la mise à jour 0.4.7

**Comment by LordVenom** [comment]
Il nous faut ton log

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by JaqenGOT** [comment]
Je trouve pas. J'a bien été dans appData/Roaming/KODI mais je ne trouve pas le Kodi.log.
Est ce le fichier texte kodi?
Désolé mais je suis novice...

**Comment by Kodigoal** [comment]
Lance une recherche de fichier sinon : kodi.log
il contient quoi ton kodi texte la ?
copie/colle le contenu du log sur pastebin et met le
lien ici si c'est ok.

**Comment by JaqenGOT** [comment]
Je sais pas si c'est ça:
http://pastebin.com/5GpQJ8di

**Comment by Kodigoal** [comment]
c'est bien ca.
T'as pas cocher par hasard dans les paramètres de vstream Urlresolver dernier onglet tout en bas ? ce qui fout la merde ?

**Comment by JaqenGOT** [comment]
oui car je passe par un débrideur. ça ma jamais causé problème.

**Comment by Kodigoal** [comment]
Et si t'essaye sans , les liens refonctionnent?

**Comment by JaqenGOT** [comment]
c'est bien URLRESOLVE qui déconné.  J'ai fais une mise à jour et ça fonctionne. Par contre pour tvrex ça marche pas. J'accede bien au menu et sous menu mais quand je clik sur "REPLAY NBA GAME" ca me met erreur vstram.

**Comment by Kodigoal** [comment]
Bizarre moi ca fonctionne lol

**Comment by JaqenGOT** [comment]
Je sais pas, j'ai redémarré toujours pareil. Faut que ça marche BORDEL....

**Comment by Kodigoal** [comment]
http://pastebin.com/UdL8xPKb
lien pour charger le fichier .py directement.
maj:
Nextpage ok.
Listage des Live dispo pour le fun.
Les liens vidéos pour les '2015 replay' et 'all star weekend' c'est le bordel, dailymotion ou googlevideo mais l'impression que beaucoup de liens sont k.o.
Après pour les lives à voir quand ils mettent liens vidéos , 15min avant match.
Je sens que ca va bien être tordu cette histoire.
Bon c'est vraiment un brouillon pour tester , mais les liens openload , faut les relancer plusieurs fois pour que la vidéo se lance .. les liens sont ok , mais l'attente pour charger la vidéo est trop long parfois.

**Comment by JaqenGOT** [comment]
Franchement t'assure, je vais tester ça en espérant que ça marche. Je croise les doigts..

**Comment by Kodigoal** [comment]
Les replay ca va , mais le live faudra l'aide des pro si c'est possible et pas trop compliqué à gerer , on va pas s'amuser à modif tous les soirs ce truc ..  et si ca a sa place sur vstream ce site ...

**Comment by JaqenGOT** [comment]
C'est déjà pas mal les replays,  vu l'heure a laquelle passe les matchs..lol

**Comment by Kodigoal** [comment]
Oui c'est sur. Après ya d'autres addons qui proposent les live. A voir si possible et la qualité des streams.
Si c'est du sd , on trouve mieux ailleurs.

**Comment by Kodigoal** [comment]
edit: bon à cette heure , liens se lancent niquel ^^
Doivent brider à mort quand trop de monde sur leur serveur.

**Comment by JaqenGOT** [comment]
oui j'ai d'autres addons(NBA Full Game) mais les liens ne fonctionnent plus depuis une semaine environ. dommage parce que c'était le top. J'ai un message en rouge dans les infos de l'extension de nba full game qui dit"The author does not host or distribute any of the content displayed by this addon.The author does not have any affiliation  whith the content provider"
C'est pourquoi je cherché une alternative. Mais la je viensde tester le replay de nba full game ca marche a voir pour le live.... Ca rend fou..Lol

**Comment by Kodigoal** [comment]
lol mais tvrex c'est bon maintenant chez toi?
Sinon pro Sport c'est pas mal pour live quand bon stream dispo.

**Comment by JaqenGOT** [comment]
truc de fou ça veut pas marcher.

**Comment by Kodigoal** [comment]
Même sans cocher Url Resolver?
Sinon remet log kodi

**Comment by JaqenGOT** [comment]
c'est pas en rapport avec mes fichiers py dans sites. ils sont tous daté du 17/12 sauf le tvrex qui date du d'aujourdh'ui du 15/12. C'est tout  a lheure avec mon probleme de vstream j'avais avancé l'horloge de 3 jours pensant que le probléme venait de la.
Tu pense que ca  à un rapport tvrexqui ne fonctionne pas??

**Comment by Kodigoal** [comment]
Je pense pas que ca joue.
Pour le live, le site bloque  les streams si pas ip usa/canada ..

**Comment by JaqenGOT** [comment]
même en désactivant Url Resolver ça fonctionne pas.
http://pastebin.com/0UGL6dQh

**Comment by JaqenGOT** [comment]
Pro sport aussi pas mal. En ce moment le liens nbastreames.pw est top (720P). Pourvu que ça dure..
On peut pas le rajouter ce lien dans vstream ??

**Comment by Kodigoal** [comment]
ok je crois avoir trouver le bug .. Mais sous android  ca marche lol
http://pastebin.com/EZKdTx7t
Comme avant à charger et copier dans /sites/

Je sais pas d'ou il sorte leur lien mais il le mette au dernier moment donc ... 
Oui parfois bon lien , si ca coupe pas parfois ..

**Comment by JaqenGOT** [comment]
T au top. Impeccable ca fonctionne, je sais pas où t'as pu trouver la faille dans tout ce shminblique. LOL. Reste plus qu'à passer par un vpn pour pouvoir voir les streams des matchs en live..

**Comment by Kodigoal** [comment]
J'ai fait une erreur dans le code mais ce qui est bizarre sous android il a pas bronché.
Pas mal le 720p la sur 76ers vs raptors^^
Ca ramera trop en vpn et il detecte vpn en + sur certains streams.
C'est trop le bordel , a voir l'avis de la Team la dessus...
Je crois pro sport ca recupere des liens postés sur reddit.
Mais ce soir à part ce match , les 3 autres ya pas trop de liens ...

**Comment by JaqenGOT** [comment]
Washington aussi, après la plupart c'est acestram faut telecharger addon plexus pour que ça fonctionne. C'est quoi reddit en gros?

**Comment by Kodigoal** [comment]
Genre un site/reseau social ou les utilisateurs postent des liens /discussions et cie.
Mais les nbastreampw doit les choper autre part .. 
Vu le code de l'addon je suis perdu moi xD

**Comment by JaqenGOT** [comment]
Ok. En tout cas merci pour tout. J'espère que la team se penchera sur tvrex pour les lived parce que franchement le site est super fonctionnel.

**Comment by Kodigoal** [comment]
Mis la source sur la Beta:
Petite Maj:
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/Tvrex_net.py
Virer rubrique playoffs 2015/ All Star Weekend pour le moment.
Regrouper l'affichage des replay saison en cours par date.
Recherche ok.
Pour les Live , juste listage.
Vu le bordel vpn et cie par ce site , et vu les autres addons qui sont spécifique sport et/ou nba qui galerent à proposer liensHD, je vois pas comment proposer mieux lol.
Enfin si d'autres arrivent à lister par ce site les streams live , à voir.

**Comment by TmpName** [comment]
Mais ca marche chez vous les lives ?
Chez moi c'est geo bloque, mais j'ai pas regarde si c'etait le site ou le serveur video qui me bloquait.

**Comment by Kodigoal** [comment]
Geo blocage et si VPN le detecte sur certains channel ... c'est le bordel^^

**Comment by JaqenGOT** [comment]
Aucun lien sur les lives. Aucun moyen de pouvoir les affichers? Sur les addons les liens sont récupéré sur reddit (enfin je crois), ou provienne de nba league pass(Sharon??), peut-on faire pareil pour tvrex? Peut-on récupérer ce lien: nbastreampw qui est le meilleur en terme de qualité pour les lives?
Je sais ça fait beaucoup de questions...

**Comment by JaqenGOT** [comment]
Sharon=Sharing

**Comment by Kodigoal** [comment]
Ce site il prend les streams d'autres sites de stream...
La qualité est sd pour ceux que j'ai testé là.
Si tu chopes pas 100 virus en lancant un stream , t chanceux xD
Bref pour moi usine a gaz...

**Comment by JaqenGOT** [comment]
Ok. Trop le bordel en fait. C'est déjà bien d'avoir les replays en HD dès le lendemain. Ou le mieux serait de trouver les chaines qui diffuse les matchs(nbatv, espn, foxsport, c'est ce que je fais quand je trouve pas les liens. Mais bon on trouve pas toujours aussi.

**Comment by JaqenGOT** [comment]
Je regarde allemand a l'instant HD720, avec nbastreampw. La chaîne qui diffuse le match est SN1 ou foxsport ohio. Recherche iptv de SN1(c'est une alternative)

**Comment by JaqenGOT** [comment]
Allemand=Cleveland. Lol

**Comment by Kodigoal** [comment]
Oui idem à jongler pour trouver^^
Sinon le reddit :
http://pastebin.com/kt0isXh8
Pro sport recup la dessus et ailleurs vu le code mais trop compliqué pour moi..

**Comment by TmpName** [comment]
Mais a cause de la geolocalisation, on va avoir regulierement des gens qui vont venir dire que tel ou tel lien ne marche plus.

**Comment by JaqenGOT** [comment]
Ok d'accord. Mieux vaut se contenter des replays pour l'instant.Ce qui est déjà pas mal..

**Comment by Kodigoal** [comment]
Bon commencer un site pour test, j'essaye de choper stream , bonne qualité , qui diffuse une selection match premier League/ nba mais il utilise le player jwplayer ...
Dans le code du site( desktop) , lien rtmp  , ca parait simple ben non ^^ me lance pas le stream.
Essayer d'inspecter avec chrome mais je m'en sors pas.
Ya version mobile ou desktop , pêtre lien http via mobile...
Mais je sais pas quoi utiliser pour voir les vrais liens finaux ( si token et cie) en lancant le stream..
Ca a l'air chaud à récupérer.
 De plus pour les tests , faut attendre les diffusions ...
Code:
http://pastebin.com/9LbnTQpY

**Comment by TmpName** [comment]
En utilisant httpfox, tu n'as pas les infos ?
Moi j'ai deja eu le lien me demandant le user-agent ou meme un cookie.

**Comment by Kodigoal** [comment]
Faut que je m'installe ca pour tester quand diffuse.merci

**Comment by TmpName** [comment]
Mais sont ou les stream sur navixsport ? Je tombe que sur des replays ?

**Comment by Kodigoal** [comment]
Home next match shedule ya les diffusions prévues.
Ou par les images en haut |1er league| la liga|
Pour ca on peut faire test que quand diffuse

**Comment by Kodigoal** [comment]
Bon choper son lien http dans log tel, toujours le même pour les matchs nba testé aujourd'hui.
Stream nba league pass.
Il limite les visiteurs en bloquant le player sur son site quand trop nombreux mais en lancant le lien direct  ca passe sans problème^^
Je sais pas si tout le monde va matter les streams mais on risque fort de  tout faire ramer si trop nombreux dessus.
A voir match foot si même url.
Par contre le truc chiant , c'est en lancant le lien .m3u8 , te met juste le son sans image , faut relancer jusqu'à avoir l'image ..  ca lit des fragments .ts
Pêtre qu'avec le lien rtmp c'est mieux, à voir.

**Comment by TmpName** [comment]
Plutot instable comme site quoi ^^.

**Comment by Kodigoal** [comment]
Non justement ^^ toujours même url avec 3-4 ip !
1 url suffit mais la ya Manchester en live.
L'url http est dans une div je crois sinon , je pige pas trop comment la choper pour proposer les autres ip.
Sinon stream ca va , pixelise parfois , pêtre ma connection . 
Pour le rtmp pas encore pu le choper.
Un petit choix foot/nba , ca peut servir lol

**Comment by TmpName** [comment]
Bon rien a faire, j'y connais quedale en sport mais la ....
J'ai pu arriver sur "match started" "it's on" mais pas de video, j'ai juste des message qui me disent que les videos seront dispo apres le match.

**Comment by Kodigoal** [comment]
Faut passer en user agent android mobile ^^ yaura le player.
Parfois il met pas version desktop rtmp  via jwplayer.

**Comment by Kodigoal** [comment]
18h15:  version desktop aussi
h ttp://www.navixsport.com/sport.php?id=2415User_ManScrewIt

**Comment by TmpName** [comment]
Alors pr lire le rmtp
HandShake: client signature does not match! 

J'en suis la pr le moment
http://forum.kodi.tv/showthread.php?tid=58572

J'ai pas lu , me sauve pr bouffer, mais essayes en simulant un user agent (celui du lecteur flash).

**Comment by Kodigoal** [comment]
oui j'arrive pas non plus , tester plusieurs combinaisons..
Bon il utilise les url config par défaut d'adobe media server , sans token et autre sécu deja pour le http.
J'essayerais avec wireshark voir ce que ca donne.
Sinon des explications côté serveur ams:
http://thekuroko.com/2013/01/21/live-http-dynamic-streaming/
https://helpx.adobe.com/adobe-media-server/dev/stream-live-media-rtmp.html
Tu vois l'url rtmp de base par défaut pour lire le stream qu'il montre en exemple et vu que le type met tout par defaut, on devrait pouvoir se connecter via vlc par ex pour test sans se casser la tête par le site et leur jwplayer à trouver un rtmp compliqué lol.
Plus qu'à attendre prochain stream ..

**Comment by TmpName** [comment]
Ben si, enfin suis pas sur a 100% mais a une epoque il y  avait un hebergeur qui marchait avec ca.

**Comment by Kodigoal** [comment]
Ok vais fouiller^^

**Comment by JaqenGOT** [comment]
C'est un peu galère à mettre en place tout ça. Moi je patauge à vous ecouter. Une question, peut-on récupérer les streams à la source même de nba league pass?

**Comment by Kodigoal** [comment]
Comme ca, directement avoir le vrai flux,  je dirais non vu que c'est payant l'accès.
En géneral , streameurs ont accès ( en payant ou pas lol) au site/appli nba league pass et capture video et la rebalance derrière sur leur site , vidéo de leur site  qui sera elle meme recapturé et rebalancé par un autre site .. et rebelotte jusqu'à avoir un flux à la ramasse lol
Ou pêtre si lien complet avec token et cie ca s'ouvre mais je pense que niveau de leur serveur , ca doit pas rigoler côté sécu du flux^^
Bon la ca tourne deja via http si tu veux test stream nba vers 1h30 je crois après.
Sinon vais tester aussi choper les stream nbastreampw posté sur reddit , et après faire l'hoster pour les lire mais là je vais coincé xD 
Par contre t'arrive à tous les lire les nbastreampw ?
Certains se lancent pas et dans le log kodi ca parle de ssl erreur et cie , pêtre kodi 15.2 le soucis..

**Comment by Kodigoal** [comment]
Maj tvrex : interface affichage.
Reste plus qu'à choper stream nbastreampw + youtube sur les game Thread reddit pour les live.
Certains nbastreampw , faut ip usa.

Navixsport: j'avais choper le rtmp complet mais arrive pas à le lancer .. handshake erreur.
Je crois vais rester aux liens mobiles , lu qu'il allait rajouter lien  pour stream sur ps4 et cie ..  a voir.

J'ai fait un autre site entre temps qui stream chaines sports avec lien direct , mais après test ca lag de trop pour rajouter à vstream...

**Comment by JaqenGOT** [comment]
C'est où qu'on peut récupérer les fichiers a jour de tvrex et Navixsport?

**Comment by Kodigoal** [comment]
tvrex:
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/Tvrex_net.py
Live tjrs pas actif , à faire encore.
Navixport pour test
http://pastebin.com/raw/1Xpx9pvE
à copier/coller contenu dans les fichiers .py

**Comment by Kodigoal** [comment]
Bon les liens reddit  nbastreampw ok ( sauf pas réussi a ouvrir ceux avec ip usa ( si ip canada ok)  , meme avec vpn ip usa , faut que je teste un autre vpn mais lien est ok pourtant). 
Récupération  des liens m3u8 navixsport ok aussi.
Si il  limite les visiteurs via le site  , je lance à la place le lien m3u8 par défaut.
Je ferais maj dans les prochains jours.

**Comment by JaqenGOT** [comment]
Ok. Super. Tu assures grave. I Love This Game. Lol

**Comment by Kodigoal** [comment]
-Navix sport
 Je met le code ici car je sais pas si faut l'inclure à vstream.
La qualité des stream ca dépend, parfois niquel si Nba tard dans la nuit lol là stream foot ca affiche pixels si ca merdouille mais bon ca se regarde , orienté plus sur tablette/tel mais tv ca passe si pas trop de pixels. 
http://pastebin.com/tLmMTEg4
ps: si bloque visiteur via son site , lien [bypass] prend le relai.
-Tvrex : 
Si lien nbastreampw sur thread reddit, s'afficheront mais certains  bloqués geo ip ( usa ou usa/canada) ou pire
via jwplayer avec lien  m3u8 protégé par aes/token + IV ..  ou url protégé par token.
L'impression qui ya 2 voir 3 liens max qui se lancent avec toujours même url .. 
Les autres vu la sécu je pense c'est mort.
Si s'ouvre dans pro sport = ok dans tvrex sinon si ya un motivé qui veut se pencher sur les liens protégés, bon courage lol
ps: je voulais rajouter capture lien youtube en plus mais j'arrive à rien..
Vu un peu les autres sites postés sur les threads , même bordel via jwplayer ou iframe pris d'autres sites ou sécu. 
Bref m'etonne pas que celui qui a fait pro sport le met plus à jour coté Nba on dirait .. trop prise de tête xD ou impossible avec les sécus.
Reste navigateur pour les nbastreams , liens sont dans le log kodi.

**Comment by TmpName** [comment]
Lol, plus motive tu meurs.
Les liens proteges ne s'affichent pas ? tu pourrais pas plutot les afficher en rouge ? plus facile pour quelqu'un d'essayer de voir pkoi ca marche pas, parce que la entre les 2 sources suis un un peu lache moi.

**Comment by Kodigoal** [comment]
lol je sens que ca va pas faire long feu les live xD
Deja pro sport ca affiche plus grand chose non plus, ya les acestream p2p aussi mais on gere pas ca.
Si, tous les liens nbastreamspw s'affichent , si se lance c'est du bol ^^ yen a 2-3 pas secu max .. le type ou les types   a un compte twitter bloqué , doit pêtre faire payer acces pour d'autres liens non posté sur reddit, fait sa pub sur reddit en balancant quelques liens.
Si se lance pas ca affiche live non disponible ! on peut changer pour dire lien protégé ..
Le mieux si tu veux jeter un oeil c'est voir lien log ou direct sur reddit quand mette les posts 1h avant début des matchs.Il laisse un certain temps les anciens aussi.
Pour navixsport c'est ok. Après qualité ca dépend.
Et lui aussi poste sur les thread soccer reddit un lien qui ya pas sur son site , ou ya le jwplayer rtmp .. lui sur son site il capture son ecran et diffuse en m3u8, bord blanc autour image et parfois il stream direct sans capture ecran.
La ya Manchester ,  il limite vite , j'imagine que si on met a dispo la source   si ya genre 100 qui lancent le lien bypass direct si limite on va tout faire peter xD 
A voir si il va voir que ca vient de chez nous ^^
Après je sais pas si LordVenom veut inclure ca.
On peut la laisser ici ou juste beta. 
Ou voir sa réaction quand son serveur va lacher ..

**Comment by Kodigoal** [comment]
Maj Tvrex sur beta:
Rajout live : Lien Youtube ( souvent vite banni et qualité varie du pire au moins pire xD)

Mis petite annotation code pour récupérer le lien protégé 100% m3u8 (aes+iV) version JWplayer Enterprise,
si ya des génies qui passent dans le coin pour soluce  ou sur les autres liens moins sécus...

Sinon, faut jouer avec l'UA parfois pour récupérer le lien m3u8 , là j'ai mis un UA qui à l'air de tourner
mais on peut surement faire un petit code  loop pour parser 2 fois avec un UA  différent pour être sur de pas avoir louper le lien m3u8 si la première fois il trouve rien ? je sais pas trop comment bidouiller ca,
à part refaire un pavé de code 
Après je stop lol

**Comment by TmpName** [comment]
On causera pas de degat a son serveur, ca m'etonnerait qu'il y ait plus de 2 personnes venant de Vstream a chaque fois au meme moment.

Apres j'ai essaye de jeter un oeuil, mais pas un lien live au moment de mes tests.

**Comment by TmpName** [comment]
D'ailleurs avant que je dise des conneries, y a moyen de savoir combien de personnes lancent Vstream en meme temps sur une fourchette de 1h ? par exemple entre 19 et 21 H ?.

**Comment by LordVenom** [comment]
Non mais ont peux le calculer du décompte de la journer

Mardi 03/01

19h : 50060
20h: 71841
21h: 107150

**Comment by TmpName** [comment]
Elle est pas encore officielle aussi.

Bon si je calcule ca fait 57 000 lancements. Si on part avec 10 pages par users en moyenne, ca fait quand meme 5 000 personnes juste sur ces 2 heures.
Si on part sur 30 sources ca fait 166 connectes par site.
Donc ca va, chaque site ne doit recevoir la visite d'un user de Vstream que entre 5 et 200 fois durant ces 2 heures, selon la popularite, pas tres mechant.
