### ISSUE TITLE
VOSTFR/MULTI 720p/1080p

### ISSUE THREAD

**Issue by koala784** [Kodi-vStream/venom-xbmc-addons#740]
Étant amateur de films et séries en **VOSTFR** de qualité **720p** ou **1080p**, j'ai effectué quelques tests sur Vstream afin de trouver ce genre de contenus.

J'ai activé **toutes** les sources dans les paramètres de Vstream (en activant également les 3 champs de recherches : films, séries et animes) , je viens de toutes les essayer :

-Recherche -> Recherche 1: Films -> j'ai écris "VOSTFR" -> au mieux de la **VOSTFR en 480p**
-Recherche -> Recherche 2: Séries -> j'ai écris "VOSTFR" -> au mieux de la **VOSTFR en 480p**

-Films -> Films (qualité HD) -> toutes les sources proposent du 720p et du 1080p, mais **uniquement en VF**
-Séries -> Séries (qualité HD) -> toutes les sources proposent du 720p et du 1080p, mais **uniquement en VF**
-Séries -> Séries (VOSTFR) -> toutes les sources proposent du VOSTFR, mais **au mieux en 480p**

Bien souvent, les liens **1080p** sont **en VF**, et les liens **VOSTFR** dépassent rarement du **480p**.

J'aimerais essayer d'ajouter de nouvelles sources à Vstream en utilisant le fichier "**ajouter_une_source.py**"

Auriez-vous des sites proposant des liens **VOSTFR/MULTI** en **720p et/ou en 1080p** ?

**Comment by Kodigoal** [comment]
ddl-island serie hd vostfr
pour les films hd en vostfr , depuis ZT k.o .. doit plus y avoir grand chose lol

**Comment by johngf** [comment]
Ecrire vostfr ou vf pour la recherche est une mauvaise idée vu que souvent c'est ajouté par celui qui a codé le script pour le site donc tu n'auras aucun resultat en recherche @koala784

**Comment by koala784** [comment]
@Kodigoal : J'ai essayé ddl-island avec les 2 séries les plus téléchargés depuis plusieurs années (Game of Thrones et The Walkind Dead), il n'y a que la saison 5 de Game of Thrones qui soit complète, en VOSTFR et en 720p. Les autres saisons pour les deux séries, en VOSTFR HD, possèdent la plupart du temps moins de la moitié des saisons.

@johngf : j'ai également essayé les catégories HD pour les films et séries sur Vstream, avec toutes les sources d'activées, la conclusion est la même.

En recherchant sur Google "download multi 1080p", je suis tombé sur ce site : http://www.extreme-down.me/

Il propose des liens en VF/VOSTFR/MULTI, SD/720p/1080p/3D/1080p3D, et il possède une interface similaire à ZT pour le choix de la qualité et de la langue : 

![sans titre](https://cloud.githubusercontent.com/assets/24566850/21189748/fb9e84bc-c21f-11e6-95a8-2c6017983652.png)

Cependant, comme pour ZT.ws, les liens passent par l'intermédiaire d'un captcha "je ne suis pas en robot".

Pensez-vous qu'il soit possible de l'ajouter en source ?

**Comment by johngf** [comment]
#688

**Comment by koala784** [comment]
@johngf : Merci, je n'ai pas suffisamment cherché^^

**Comment by Kodigoal** [comment]
addon exodus + ss titres à telecharger par kodi sinon.

**Comment by koala784** [comment]
@Kodigoal Merci ;)

**Comment by doubidave** [comment]
Pour l exemple de game of thrones et ddl island, j ai aucun résultat moi par exemple. Ddl island n apparait nullepart hormis dans toutes les sources et il est bien activé pourtant. Mais bon je suis le poissard de vstream apparemment 😅

**Comment by koala784** [comment]
@doubidave : Pour mon exemple j'ai utilisé ddl-island en allant dans "Toutes les sources",

**Comment by doubidave** [comment]
@koala784 ah ok donc c est normal. Par contre il me dit de faire telecharger et visualiser. Si je fais ca l épisode est stocké quelque part ou ca reste du streaming quand même?

**Comment by koala784** [comment]
@doubidave : Je pense que ça va le stocker (si tu as définis un dossier de téléchargement dans les paramètres de l'extension) et lancer le streaming en même temps.

**Comment by doubidave** [comment]
Ok dommage, j aime pas trop stocker. Sinon en plus d'exodus je vais aussi sur popcorn time. Tu vas sur l episode et tu restes appuyé. Tu auras le choix de la qualité et pour l exemple de game of thrones tu as 1080, 720, 480 et 3d. Avec un vrai 1080 et son 5.1. Par contre c est en vo donc j utilise des addon de sous titres. Si ca peut aider...
