### ISSUE TITLE
Traitement du titre

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#741]
Quand vous avais une information a mettre en couleur genre année nombre de vue ect...

avant 
sTitle = 'mon titre'+[COLOR ect...
`oGui.addMovie(SITE_IDENTIFIER, 'showHosters', sTitle, '', sThumb, aEntry[3], oOutputParameterHandler)`

Maintenant
sTitle = ['montitre', 'test', 'voila']

` oGui.addMovie(SITE_IDENTIFIER, 'showHosters', sTitle, '', sThumb, aEntry[3], oOutputParameterHandler)`

Le titre doit être en premier dans la liste le reste ceras colorer en orange automatiquement pas de limite au info mais pas trop quand même :)

Note: l'ancienne methone fonctionne toujours pas besoin de refaire tous les sites.
Renote a ne pas utiliser avant la prochaine maj sinon les sites vont planter et mince.

**Comment by LordVenom** [comment]
Pour le moment les Saison et Episode doivent etre en premier decotitre

exemple 

titre = 'montitre s02ep03"
lang = 'vf'

display = [cUtil().DecoTitle(sMovieTitle), lang]

J'aimerais asser envoyer les episodes et les saisons au listItem (pour les afficher dans le theme) pour ça il faudrais trouver les episode et les saison dans guiElement si quelqu'un et motiver je suis nul en regex.

**Comment by LordVenom** [comment]
ok j'ai fait ça 

re.search('(?i)(s(?:[a-z]+son\s?)*([0-9]+))', string)

pour qu'il prenne s02 ou saison20 ou season02

**Comment by LordVenom** [comment]
```
 def setTitle(self, sTitle):
        if type(sTitle) is list:
            self.__sTitle = sTitle[0]
            #cherche les saison
            string = re.search('(?i)(s(?:[a-z]+son\s?)*([0-9]+))', self.__sTitle)
            if string:
                self.__sTitle = self.__sTitle.replace(string.group(1),'')
                self.__sTitle = "%s [COLOR coral]S%02d[/COLOR]"%(self.__sTitle, int(string.group(2)))
                self.addItemValues('Season', string.group(2))
            del sTitle[0]
            if len(sTitle) >0:
                self.__sTitle +=  " [COLOR coral]["+ '] ['.join(map(str,sTitle)) + "][/COLOR]"
        else:
            self.__sTitle = sTitle
```

Le soucis c'est que ça fonctionne que si Saison et en premier dans la liste
titre = ['montitre saison05',' vf']

Je cherche comment le trouver dans n'importe quel emplacement de la liste mais re.search ne prend pas les liste.

**Comment by TmpName** [comment]
Dans la fonction DecoTitle (ou utilise par elle), il y a un regex qui sert justement a extraire saison et episode pour les remplacer par SXXEXX.

**Comment by LordVenom** [comment]
J'ai vue oui et logiquement j'utilise ça en général mais pour envoyer l'info au skin il faut etre dans guielement et il faut que ça me retourne l'info si c'est une saison ou un episode et que ça me retourne uniquement le chiffre.J'ai commencer ça a cause de sMovietitre ont souvent perdu sur ceux qui doit etre dedans le but final que cguielement retourne lui même le filename et gere les saison et episode.

**Comment by TmpName** [comment]
J'ai pas encore regarde les skins, mais au pire integre la fonction decotitle a l'interieur de la fonction addMovie() (ou plutot addfolder()) comme ca tu pourras en extraire les infos.
Elle est pas genante, si y a rien a colorer, elle ne fera rien, si vraiment elle gene, faire une option pr la desativer.
Tout les sites auront les memes couleurs.

Et pr la desactiver, et garder la compatibilite avec la vielle version suffit de faire une fonction vide dans le fichier config.py.
