### ISSUE TITLE
Ajout de source

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#743]
Bonjour je voulez ajouter cette source sur la beta  mais je me suis heurté a deux proble,e

le premier pour afficher la qaulite du film; et le deuxieme pour la captcha

http://pastebin.com/wS2purTL
je teste sur Film HD
![sans titre](https://cloud.githubusercontent.com/assets/11494048/21213287/9998ba66-c293-11e6-91da-c4a205255b16.png)
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/21213303/b4516c2c-c293-11e6-873d-f5bcbd561b55.png)
![sans titre2](https://cloud.githubusercontent.com/assets/11494048/21213384/4239c6ec-c294-11e6-9a43-2edabb1d3eec.png)

remarque j ai cherccher le film les 7 samurai par tout sur vstream  mais j ai rient trouver pourtant il exister sur Zt on qualiter 1080p!!!!.

**Comment by lebigboss59** [comment]
Comme par hasard j'allais aussi essayer de l'ajouter hier
Bon bah j'essayerai avec un autre site si jamais tu partage, bon courage
