### ISSUE TITLE
Source T 411??

### ISSUE THREAD

**Issue by JaqenGOT** [Kodi-vStream/venom-xbmc-addons#744]
Bonsoir.
Est-il possible d'ajouter une source provenant du site T411??

**Comment by johngf** [comment]
Non Les fichier torrent ne sont pas des video

**Comment by lebigboss59** [comment]
Pourtant il y a des logiciels qui lisent directement les torrents vidéo en Streaming
Je pense que c'est possible mais reste à savoir comment

**Comment by TmpName** [comment]
C'est pas dur mais Vstream n'est pas un logiciel de p2p.

**Comment by johngf** [comment]
Le plus simple une seedbox chez libndown exemple ou vous mettez vos fichier torrent  de la avec kodi connection par ftp et vous pouvez lire vos videos

**Comment by JaqenGOT** [comment]
@lebigboss49. C'est pour ça que je me suis permis de poser la question.

**Comment by JaqenGOT** [comment]
@Johngf. Ce que tu dis m'intéresse. Mais je n'y connais pas grand choses. Est Ce possible avec kodi sous Windows??

**Comment by johngf** [comment]
Oui je le faisait avant

**Comment by johngf** [comment]
Nocice ou pas avec google on arrive a trouver faut cherché c'est tous

**Comment by JaqenGOT** [comment]
Ok. Je testerais ça. En fait depuis la fin de ZT, difficile à trouver des films VF en 1080P.

**Comment by JaqenGOT** [comment]
LOL. Comme on dit google est ton ami...
