### ISSUE TITLE
Ajout de nouvelles sourceS

### ISSUE THREAD

**Issue by max891** [Kodi-vStream/venom-xbmc-addons#745]
Bonjour,
Pensez-vous qu'il est possible d'ajouter comme sources ces deux sites:
xxx.emule-island.ru/
xxx.dpstream.net/index.php
?
Sinon existe t'il un tuto pour créer ses propre sources?
Merci d'avance pour vos réponse.

**Comment by johngf** [comment]
Emule island est deja la c'est ddl island

**Comment by max891** [comment]
ok merci je vais regarder ça

**Comment by max891** [comment]
Merci je n'avais pas fait attention qu'on pouvais en activer d'autre.
Pour dpstream vous pensez que cela est possible? car il à une assez grande base de donnée.

**Comment by TmpName** [comment]
Nope pas de tutos, mais un fichier squelette:
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/ajouter_une_source.py

Au debut ca va aller vite mais tu vas bloquer net quand tu vas decouvrir les regex, c'est normal.
Si tu commences le fichier, poste le ici (via pastebin par exemple), tu as plus de chance d'avoir de l'aide si tu commences a chercher toi meme, beacoup de monde demande des sources, et l'equipe ne peut pas toute les faire.

**Comment by max891** [comment]
OK merci je regarderai ça

**Comment by max891** [comment]
j'ai commencé a faire un fichier sources pour dpstream si quelqu'un peu y jeter un oeil. Merci d'avance.
http://pastebin.com/Cm8QStxX

**Comment by TmpName** [comment]
Je t'ai corrige tout les problemes de tabulation, ca affiche la premiere page si tu vas dans "films". Rien de cliquable
http://pastebin.com/XwD6z2EJ

Mais tu aurais mieux fait de partir du fichier squelette et non pas un fichier commence.

**Comment by max891** [comment]
ok merci. Je l'ai aussi en fichier squelette si c'est mieux.
http://pastebin.com/7pgXG1Ai
Encore merci pour votre aide.

**Comment by max891** [comment]
le code sources du site dpstream peu m'aider ou pas ?

**Comment by TmpName** [comment]
Ben tu peux voir comment c'est fait, mais tu vas y trouver plein de code dont tu ne vas pas voir l'utilite, ca va plus te perturber qu'autre chose, le fichier squelette est plus simple comme base.

**Comment by max891** [comment]
ok merci je vais essayer de continuer sur le fichier squelette que j'ai mis plus haut mais j’avoue je comprend pas tout.
