### ISSUE TITLE
sous titre Openload et autres

### ISSUE THREAD

**Issue by max891** [Kodi-vStream/venom-xbmc-addons#746]
Bonjour, existe t'il un moyen d'avoir les sous titres avec openload ou autre sur un film HD?
Ou il faut forcement utiliser opensubtitle.org.
Pour l'instant il n'y a que sur uptobox en direct que j'arrive à les avoirs.
Merci d'avance.

**Comment by johngf** [comment]
Sur une video en vo sans sous titre ?

**Comment by max891** [comment]
Non sur un film Hd en français mettre les sous titre french forced

**Comment by johngf** [comment]
Sur upto tu as les SS parcequ' il sont dispo avec sur les autres hebergeur c'est rarement le cas

**Comment by max891** [comment]
A ok je pensais que pensais que ça venait de vstream car il y à aucun sous-titre de proposé sur ses hébergeur.

**Comment by johngf** [comment]
Non vstream ne recupere pas les ss si ils sont avec il y a moyen'sinon il faut passé par opensub ou autres

**Comment by max891** [comment]
C'est normal que avec le lecteur uptostream je ne peux mettre que les sous titre anglais?

**Comment by johngf** [comment]
As tu le francais avec au moin

**Comment by max891** [comment]
non quand je met les sous titre je n'est que l'anglais de possible par contre le film est bien en français

**Comment by johngf** [comment]
Jette un oeil la #569

**Comment by johngf** [comment]
Tu peut pas avoir french subforced si il y a que l'anglais dispo

**Comment by max891** [comment]
Oui je me doute mais quand je passe le même lien en direct avec uptobox j'ai les sous titre français de proposé

**Comment by johngf** [comment]
A je vois surement un soucis de code pour reconnaitre langue voir si @TmpName ou @Kodigoal  peut corrigé

**Comment by johngf** [comment]
C'est qu'elle video ? Quel site ?

**Comment by max891** [comment]
la video je vais regarder de suite. le site c'est zone-telechargement.eu

**Comment by max891** [comment]
Le film c'est sully. D'ailleur je viens de remarquer uptostream ne me propose que le soustitre anglais et uptobox en direct que le sous titre french forced. pourtant c'est le même lien.

**Comment by LordVenom** [comment]
Le probleme c'est que sur  opensubtitle.org tu vas pas trouver du français leur addon et pas fini il aurais du faire un choix de langue dans les préf a voir. Il me semble que j'avais déjà travailler dessus un moment.

**Comment by LordVenom** [comment]
J'ai rien dit c'est moi qui et mal chercher pour la langue des sous titre c'est dans system/video/sous-titre langue pour les sous titre a télécharger. Hé je met mon login dans les préférence de l'addon mais pas mon choix de langue c'est un peux confus sorry.

**Comment by Kodigoal** [comment]
Alors pour les vidéos Fr uptostream qui affichent parfois juste 1 ss English(1/1) , c'est pas des ss , tu peux test en l'activant t'auras aucun ss affiché , ca doit être un tag dans le fichier vidéo qui affiche ss English.
Aucun srt n'est chargé.
Pour les 'Forced'  on a décidé de pas les prendre en
compte quand on avait codé la chose car sur toutes les vidéos FR   ou presque via uptostream te mettait les ss Fr Forced .. Chiant à désactiver à chaque fois.
A revoir ce filtrage car @TmpName avait trouvé comment ne pas les activer par défaut  au lancement vidéo.
Faut voir avec @LordVenom et @TmpName si on vire le filtre 'Forced' ou pas.

**Comment by max891** [comment]
ok merci. c'est vrai que d'avoir les sous titres en french forced c'est pas mal quand même.

**Comment by TmpName** [comment]
J'ai essaye de tester mais j'ai pas tout compris, j'ai teste pr sully sur openload et uptostream et sur aucun des 2 j'ai trouve de fichier ST.
Et sur uptobox il ne peut pas y avoir de fichier st ? vu qu'on lit juste 1 fichier.

**Comment by max891** [comment]
Quand je l'ai regarder c'était sur box android. après je peux essayer sur un autre film si vous voulez.

**Comment by max891** [comment]
Je viens d'essayer avec suicide squad. le résultat est le même sur uptostream sous titre anglais et sur uptobox en direct sous titre fr et fr forced de possible.

**Comment by TmpName** [comment]
Alors je vient de tester pr la version HD1080 de 1.5G.
Sur navigateur.
Pour Uptostream.
label='FR Forcé' qui sert a rien
label='FULL FR' qui sont les vrais ST.
Pour uptobox.
Pas de fichier str, les sous titres sont integre au fichier (fichier mkv), la ca depend de tes reglages de kodi, choix de la langue favrorite, ect ... (chez moi ca deconne plein pot, j'ai beau mettre FR, j'ai souvent ENG).

Edit:
C'est bon j'ai trouve le prb, en fait on active les ST unqiquement si vostfr se trouve dans le titre.

**Comment by Kodigoal** [comment]
Les ss Forcé sur sully là , ca traduit quand on voit par exemple la scene d'une tv qui diffuse info ou titre anglais journal papier  , ou au final générique , traduit le discours.
Alors soit faut pas filtrer , soit on laisse comme ca...
ps: st Anglais deja dit plus haut , il affiche English(1/1) mais c un tag dans la vidéo ou je ne sais quoi , il charge rien.

**Comment by TmpName** [comment]
Ben je sais plus qui a eu l'idee de n'afficher les st QUE si vostfr est dans le titre, mais c'est une bne idee.
Par contre dans ce cas la, les ST french forced n'apparaissent pas.

Pour moi je laisserais comme ca, car pour moi
1 - Les st french forced ca sert a rien, (a part un dialogue en russe qui dure 2mn ou la tu entend juste du son).
2 - Je trouve le code actuel bien foutu, leger et peu de risque d'avoir trop de ST inutiles.

Meme si on autorisait les ST forced, ca m'etonnerait que le mec pense a l'activer juste car a un moment il a rien compris au dialogue russe.

Par contre si il y a une video en VO sur openload sans ST, la ca m'interesse.

**Comment by johngf** [comment]
J'avait deja fait le code pour ça mais il faut que je retrouve la video
