### ISSUE TITLE
vstream sokro 

### ISSUE THREAD

**Issue by veve87** [Kodi-vStream/venom-xbmc-addons#747]
bonjour depuis quelques temps dans vstream quand je fais une recherche par genre "serie epouvante horreur"si je choisi sokrostream j ai bien les series qui s affichent mais si je clic par exemple sur walking dead j ai aucun liens pour visionner un episode j ai juste 3 petits points en haut voila le probleme.en vous remerciant d avance .et merci pour votre taf c est genial

**Comment by johngf** [comment]
oui il y a un soucis meme en modifiant le pattern quand on passe par serie sources ou serie news ca bug

**Comment by johngf** [comment]
bon j'ai corrigé par contre pour serie derniers ajouts et serie sources une fois que tu as cliqué sur la serie pour avoir les saisons il n'y a plus de titre juste s01 ensuite s01e01 si je change l'ordre du pattern ça fous le bordel et fonctionne plus la c'est ok

**Comment by veve87** [comment]
ok merci et bravo tu es super réactif je te remercie

**Comment by max891** [comment]
Bonsoir, j'ai le même soucis. À chaque fois que je clique sur le lien de se site il n'y a aucun lien ensuite. C'est toujours vide.

**Comment by johngf** [comment]
il faut attendre la mise a jour

**Comment by max891** [comment]
Ok merci

**Comment by chataigne73** [comment]
Je pense que sokrostream ne marche plus du tout à part les liens OK.ru
Si qqn pouvait confirmer...
Ils ont mis en place des URL de redirection sur les liens...  Pas trop difficile à réparer, faut juste trouver le temps pour le faire. :-p

**Comment by johngf** [comment]
je suis dessus
