### ISSUE TITLE
noms masqués

### ISSUE THREAD

**Issue by diouf76** [Kodi-vStream/venom-xbmc-addons#748]
salut, j'ai un bug sur le menu pour la sélection pour le choix entre film , tv , animes etc... j'ai les icônes mais pas les noms a coté.

Une idée?

En passant beau boulot.

**Comment by johngf** [comment]
Dans les parametres de vstream il y a vider le cache de kodi essaie de le faire voir si ça résout le probleme

**Comment by diouf76** [comment]
nan cela ne change rien

**Comment by johngf** [comment]
Tu n'est pas le premier a avoir ce soucis tu utilise un autre theme kodi ? Ou celui de base
La langue dans kodi est elle tous en francais ?

**Comment by diouf76** [comment]
merci, c est bon comme j'avais une partie en anglais le problème venait de là donc c'est réglé.
Merci encore.

**Comment by Stormy01** [comment]
Salut, est-ce que je peux savoir ce que tu as changé exactement? J'ai essayé de changer ma langue de Français Canada à Français tout court et cela ne change pas, je ne vois pas le nom des menus...

**Comment by johngf** [comment]
tu vide le cache xbmc puis tu met francais francais ou il y a une langue a choisir

**Comment by TmpName** [comment]
Essayes plutot l'inverse, d'abord mettre l'addon en fr et apres vider le cache pour forcer l'actualisation.

**Comment by diouf76** [comment]
J ai vidé le cache puis tout en fr et ça marchait comme ça

**Comment by Stormy01** [comment]
J'ai vidé ma cache, mais je ne vois qu'un seul endroit où mettre français, j'imagine qu'il doit y avoir un autre endroit parce que ça ne fonctionne toujours pas...

**Comment by TmpName** [comment]
Quand j'ai teste j'ai ete directement dans les parametres de tout kodi systeme/apparence/internationalisation mais je sais pas si il y a moyen de le faire pour un seul addon.

**Comment by Stormy01** [comment]
C'est là que je l'ai changé, j'ai mis Français au lieu de Français Canada, mais je ne vois toujours rien sur la première page...

**Comment by TmpName** [comment]
Et apres avoir teste dans Vstream/parametres/outils/vider le cache kodi ?

**Comment by Stormy01** [comment]
Ça marche de nouveau, un gros merci!!!!!!!! Je ne sais pas dans quel ordre, il faut faire le tout, mais bon, ça fonctionne de nouveau, super, merci!!!!

**Comment by diouf76** [comment]
Cool tout le monde a son problème de régler je peux fermer le post

**Comment by TmpName** [comment]
Par contre c'est bizarre mais le fichier french ne marche que pour les FR-fr francais de france, si on choisit la langue belge ou canadienne, on se retrouve avec le fichier anglais.
Je viens de jeter un oeuil dans le code, pas vu l'astuce.

**Comment by Sassinak** [comment]
Super, ça a marché
