### ISSUE TITLE
strea_ming UHD 4k

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#753]
Bonsoir a tout 
je voulez voir le film Mad Max Fury Road on UHD 2160p mais une erreur 
de streaming s est prodiute erreur fichier introuvable

sur mon portable xperia sony z5 premium j ai essaye de changer la langue on francais  mais  impossible
de voir le menu vstream message kodi instalation failed

je crois que le probleme et don le host uptostream  d'ailleur ca marche pas avec 720p et 1080p aussi

est ce que on peut ajouter l icône qui est on vert HD pour UHD

.

**Comment by TmpName** [comment]
Tu as teste sur quel site ?

**Comment by mino60** [comment]
Sur film illimite comme par hazard j ai choisie top 250 sur topimdb puis le film Mad Max Futy Road j ai trouvais la qualite 2160p sur ce site.

**Comment by Kodigoal** [comment]
C'est bizarre car tu mets le lien uptostream du log dans un navigateur c'est ok.

**Comment by TmpName** [comment]
Boulette, on avait oublie d'importer la lib re.
C'est bon c'est corrige.

Rajout de l'cione 4k aussi.

**Comment by TmpName** [comment]
c'est bon pr toi @mino60 ou tu attend la MAJ pr tester ?

**Comment by mino60** [comment]
C est bon ca marche tres bien et merci pour votre aide j attend juste une reponce pour vstream vide sur la langue englais j ai essaye de changer la langue on francais ,ais j ai un message d erreur instalation faiiled

z5 experia premium kodi 16.1

**Comment by TmpName** [comment]
Tu la change ou la langue ?
Jetes un oeuil ici
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/748
