### ISSUE TITLE
Emission Sport [J+1, CFC, etc]

### ISSUE THREAD

**Issue by lebigboss59** [Kodi-vStream/venom-xbmc-addons#754]
Salut à tous
Connaissez vous les sources qui propose ce genre d'émission
Qui permettent de regarder en replay ce qu'il y a eux la veille sur Canal ou Beinsport surtout ? Ou SFR Sport ?
J'ai vue qu'il y a des sites comme Topreplay qui propose ce genre de vidéo avec J+1 et c'est du Openload HD et il n y a que Telefoot et J+1 pas de CFC ou de Le Club et ce n'est pas sur Vstream 

![capture](https://cloud.githubusercontent.com/assets/24246566/21296515/1a5b078a-c56e-11e6-99a4-b9df21bb380f.PNG)

**Comment by lebigboss59** [comment]
J'ai vue qu'il y a des sites comme Topreplay qui propose ce genre de vidéo avec J+1 et c'est du Openload HD et il n y a que Telefoot et J+1 pas de CFC ou de Le Club et ce n'est pas sur Vstream 

![capture](https://cloud.githubusercontent.com/assets/24246566/21296515/1a5b078a-c56e-11e6-99a4-b9df21bb380f.PNG)

**Comment by TmpName** [comment]
Heu dsl de demander ca, mais tu es pas motive pour au moins commencer le fichier ^^.
En ce moment moi suis un peu a l'ouest et le reste de la team sort plusieurs sites par jours, donc le temps de les tester, paufiner, et garder a jours je pense qu'elle est un poil debordee aussi.

En tout cas je met de cote.

**Comment by lebigboss59** [comment]
@TmpName Franchement j'aimerais bien mais en ce moment je suis overbooker lol, je suis en pleine période de stage
Donc je vais essayer mais je garanti pas le résultat tout de suite et il faut que je comprenne un peu mieux les scripts 

En tout cas je vais essayer, quand j'y arriverai je ferrai d'autres sites. Il me faut juste le TEMPS.

**Comment by TmpName** [comment]
Pareil pour tout le monde, en plus c'est pas la periode ou on a le plus de temps libre :)

**Comment by johngf** [comment]
j'ai une question le ssl ne fonctionne pas avec kodi 16 ? c'est pour un hosters

**Comment by TmpName** [comment]
Yep, exactement, se sera corrige a la V17, pr le moment je contourne en remplacant https par http ou

```
    #patch a virer a la V17 de kodi
    import ssl
    ssl.PROTOCOL_SSLv23 = ssl.PROTOCOL_TLSv1
```

**Comment by johngf** [comment]
j'ai testé ça que j'ai trouvé sur le net mais fonctionne pas je retest demain

**Comment by TmpName** [comment]
Tu peux aussi bloquer la redirection, si le code est present juste avant, mais moi aussi j'ai un hoster en attente a cause de ca.

**Comment by johngf** [comment]
essayé aussi j'ai mis en attente sinon je me suis rendu compte que sur ce site il a bcp hoster pas seulement opl et c'est un peu le bordel a mettre en place les liens sont raccourcis /etc...=g5gdf58g
sinon j'ai commencé usercloud comme hoster aussi et vu que c'est du dl je ne sais pas pourquoi ça fonctionne pas avec mp4 et mkv ou alors passé par dl et visualiser (avi flv ok)

**Comment by TmpName** [comment]
C'est normal en version gratuite, uplea fait pareil. En fait tu ne peut te connecter qu'une fois, si tu arrette le dl et recommence, c'est mort, Kodi lui fait plusieurs requetes pr streamer, Vstream en fait 1 seule pour dl le fichier.

**Comment by johngf** [comment]
oui mais pourquoi ça fonctionne avec les avi et flv ? tous le temps

**Comment by TmpName** [comment]
Une histoire de requete je pense, les fichiers ne sont pas foutu pareil, flv est fait pour le stream, donc je pense que kodi doit prendre au debut et lire non stop, le mkv est compose de plusieurs parties, kodi doit essayer de faire plusieurs requetes pour avoir toutes les infos.

C'est lequel ton hoster qui bloque ?
Sinon pr les liens redirige c'est pas un soucis, avec le regex tu recuperes
`<option value="/hoster=v9ss2iru8epx" style="background:#292929;">nom du hoster</option>`

Tu affiches le nom du hoster, et la page suivante recuperera le lien. (et moi perso je mettrais meme 2 pages, meme si je sais que les gens ralent quand ils ont une page qui sert a rien).

**Comment by TmpName** [comment]
Et vaut mieux un hoster qui ne marche pas a tout les coups (quitte a mettre un message d'erreur) que pas de hoster du tout.

**Comment by johngf** [comment]
ce que je fais c'est que je recrée le hoster a chaque fois
    elif 'daily motion' in sHosterUrl:    
          code = re.search('/dailymotion=([^"]+)',sHosterUrl)
          if code:
             return 'http://www.dailymotion.com/embed/video/' + code.group(1)
