### ISSUE TITLE
Date 1969

### ISSUE THREAD

**Issue by bubuleur** [Kodi-vStream/venom-xbmc-addons#755]
Bonjour,
Je viens vers vous pour une remarque 
J'ai un raspberry pi 3 et j'ai la dernière version a ce jour de kodi et de Vstream et j'ai remarqué que souvent sur les titres des films sur vstream il y a de marquer 1969 c'est toujours la mème date et pourtant les films ne sont de 1969 
Peut on enlever cette date parce que ca fait bizarre 
En vous remerciant
Cordialement

**Comment by johngf** [comment]
ben pas chez moi jamais vue 1969 sur quel sources tu as 1969 ?

**Comment by bubuleur** [comment]
Merci pour ta réponse je suis pas chez moi la mais je te fais des photos ce soir pour que tu vois
Merci encore

**Comment by bubuleur** [comment]
Ci joint photo ce 1969 ça me le mets souvent
![img_20161219_220351](https://cloud.githubusercontent.com/assets/21688137/21340999/64947ff8-c68a-11e6-8ece-27e2440b4cde.jpg)
![img_20161219_220439](https://cloud.githubusercontent.com/assets/21688137/21341000/6496c27c-c68a-11e6-8bc3-a5b9148099df.jpg)

**Comment by johngf** [comment]
yu utilise quel theme pour kodi celui de base ou un autre ? et tu utilise kodi 16 ou 17 ?

**Comment by johngf** [comment]
bon j'ai trouvé le site ou tu as testé donnie darko et je n'ai pas 1969 donc le probleme viens de chez toi

**Comment by bubuleur** [comment]
Merci pour ta réponse pourtant c'est le thème de base de kodi que j'ai mis je n'y est pas touché sinon c'est Kodi v17 “Krypton” Beta 6 avec libreelec que j'ai mis sur le raspberry

**Comment by johngf** [comment]
Vstream n'est pas encore totalement compatible avec kodi 17 beta il est préférable d'utilisé kodi 16 jarvis
