### ISSUE TITLE
Test menu recherche

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#756]
Bonjour, Alors j'ai créer un menu dans les paramètre vStream pour sélectionner les sources pour la recherche.Si vous pouvez tester et me dire voir si ça tourne chez tous le monde que je puisse virer l'ancienne méthode.

![image](https://cloud.githubusercontent.com/assets/4380112/21306157/dc2b5eee-c5cf-11e6-8178-722248cc7df6.png)

**Comment by TmpName** [comment]
Alors chez moi ca marche (a part que j'ai encore galere comme un porc pour que kodi me fasse une reinitialisation de la page)
C'est superbe, juste un detail, y a pas moyen de rajouter un texte style "Les sources activees sont en jaune, et blancs pour non activees" car moi ca m'a pas saute de suite aux yeux, apres j'ai peur que selon les themes ca chnage .....

**Comment by Kodigoal** [comment]
Testé c'est ok.

**Comment by LordVenom** [comment]
C'est plus clair la non ?

![image](https://cloud.githubusercontent.com/assets/4380112/21343187/e373eede-c695-11e6-9a2a-150071b1d322.png)

**Comment by Kodigoal** [comment]
Ca le fait oui ^^
