### ISSUE TITLE
Petit bug 

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#757]
Bonjour à tous, 

Encore merci pour tout le travailler que vous faites je viens tout juste d'installer la nouvelle version de vstream et je remarque une nouvelle source ht tp://www.frenchddl.com et quand je fais une recherche sur celle-ci il met une erreur, je suis aller voir le site pour voir s'il était pas HS et celui-ci fonctionne bref, c'était juste pour vous le signaler

@+ Patrice

**Comment by max891** [comment]
J'ai le même problème pour zone telechargement.

**Comment by TmpName** [comment]
Moi je viens de tester les deux sans prbs.
A confirmer par d'autres, mais je pense que vous n'avez pas encore les derniers fichiers.

**Comment by max891** [comment]
Existe t'il un moyen de faire sa mise à jour manuellement pour avoir les dernière modifs?

**Comment by TmpName** [comment]
Le plus simple (pour moi, il ya plein de methode) ouvrir le fichier sur ta machine avec un editeur de texte et coller le nouveau fichier dedans.
Pour les nouveau fichiers 
https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/plugin.video.vstream/resources/sites
Choisit le fichier, clique sur "raw", "tout selectionner", copier

**Comment by Kodigoal** [comment]
Le listage fonctionne pas sur Frenchddl chez moi ..
Faut que je rajoute les bGlobal_Search False et True dans le code car sinon il est pas défini.
Vous pas ? ( j'avais mis à jour zt.eu même soucis)

**Comment by TmpName** [comment]
Mince autant pr moi, j'ai confondu avec la source dlllfrench.
Je met a jour dans 10 mn.
