### ISSUE TITLE
Vstream marque page 

### ISSUE THREAD

**Issue by phenix60** [Kodi-vStream/venom-xbmc-addons#758]
Bonjour,
Voila j'ai crée un liste d'anime utilisant la fonction marque page de vstream mais je ne trouve pas comment les organiser autrement que par "date" car l'option est grisée et je ne peut pas la modifier , aussi j'ai pensé allez chercher la liste dans les fichier mais pareil je n'arrive pas a la trouver .

Pourriez vous me dire ou sont stocker les marque page que vstream enregistre ou comment faire pour les organiser par ordre alphabétique plutôt que par date ? merci

Petite dernière chose j'ai crée ma liste en utilisant les marque page car je ne pouvais pas l'importer depuis  Imdb a l'image de trakt pensez vous ajouter l'import de liste via imdb ?  merci

**Comment by TmpName** [comment]
Alors la bne question ^^.
Effectivement a chaque fois le choix est grise, mais c'est partout dans Vstream, et je sais pas pkoi.
Par contre c'est rigolo car dans "toute les sources", c'est tjours par ordre alphabetique meme avec le triage par date.
Les marques pages sont stockes dans la base sql, ce ne sont pas des fichiers, mais c'est editable avec des applications externes.

Par contre si tu connais trakt pkoi tu ne l'utiliserais pas pour tes listes. Bon c'est encore en beta, ce soir je rajoute une limite pr le nbre de resultats par page, mais le classement se ferait par ordre alphabetique.

Par conte le gros avantage/inconvenient de trakt, c'est que les liens vers les videos ne sont pas definis, a chaque fois, ca relance une recherche. L'inconvenient des marques pages c'est que au bout de quelques mois, le site va chnager les liens ou son nom de domaine, du coup tout tes liens seront HS.

**Comment by phenix60** [comment]
Bah en faite je n'utilise pas trakt car j'ai tester vite fais quand je chercher a faire ma liste et faudrait peut être je me penche plus dessus mais c'est vraiment pas pratique de faire et rechercher les séries films animes sur leur site pour faire une liste , donc j'avais du import mes liste creer sur imdb via un programme tier dans trakt , faisable mais pas pratique .
A la différence après je sais pas si c'est bien de dire sa mais l'autre programme j'utilise principalement pour mes séries c'est exodus qui a une fonction très pratique pour les liste car on peut link notre compte imdb au programme et il peut voir les différentes liste déjà créer sur le site ( imdb ) pour les rechercher directement dans ces sources.
Après je pense que l'on peut arriver au même résultat avec trakt mais comme j'ai dit j'ai juste survoler les possibilité pour le moment mais sa me parait bien plus complexe au premier regard, je fouillerais d'avantage quand mème car j’apprécie beaucoup vstream, juste ce petit soucis de liste qui me dérange actuellement.
Pour les marque page tu dis ils sont éditable avec des applications externe tu pourrais m'en conseiller une s'il te plait et un peut me dire comment faire s'il te plait ? merci

**Comment by TmpName** [comment]
Yep, on a teste betaSerie aussi mais on a finit par choisir trakt.
Sinon, tu peux faire tes recherches avec la recherche visuelle de Vstream, ou n'importe quel moteur, puis clic droit (ou menu contextuel) et a jouter a trakt. Mais c'est en cours de dev, donc pas exempt de bugs.

Pour editer la base sql, j'utilise "DatabaseBrowserPortable" (mais un user m'avait passe une autre appli plus simple que j'ai perdu)
Pr m'en servir.
Connexion/Add
Type>Sqlite
Name> abcdef
En lien j'ai
C:\Users\BRIX\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.vstream\vstream.db

Et apres c'est intuitif, tu cliques partout, c'est comme un explorateur de fichier.

**Comment by Kodigoal** [comment]
Sinon pour tester, rajouter cette ligne dans le fichier favourite.py ligne 156
plugin.video.vstream/resources/lib/favourite.py
`  row = sorted(row, key=lambda data:data[1])`

         try: `
            row = cDb().get_favorite()
            row = sorted(row, key=lambda data:data[1])
            for data in row:

                title = data[1]
                
                siteurl = urllib.unquote_plus(data[2])
                site = data[3]
                function = data[4]
                cat = data[5]
                thumbnail = data[6]
                fanart = data[7]
`

Par contre si lees Titres  sont du genre (Webrip)Dragon et cie en Marque page ,  ca classera en W , pas en D.

**Comment by phenix60** [comment]
Bon j'ai essayer l’éditeur de base sql mais je suis pas arriver a sauvegarder les changement je faisait , mais bon comme tu me la fais remarquer les marque page pourrait devenir hs si les liens change donc je suis retourner voir comment faire bien fonctionner Trakt, donc j'ai bien créer ma liste dans "collection" mais je suis venu a rencontrer a une probleme il me semble lier a vstream tu pourras surement me dire , quand je vais dans vStream > Trakt (beta) > Série > Collection , je vois bien ma liste mais aucun des titres n'a de pochette ( fanart )  download . 

Faut il que j'aille les telecharger et lui ajoute en local d'un quelconque manière ou une option que je n'ai pas activer ?

![trakt1](https://cloud.githubusercontent.com/assets/24650325/21350956/8338a77e-c6ba-11e6-9086-591f3ad09d37.png)
![trakt2](https://cloud.githubusercontent.com/assets/24650325/21350955/8336bf90-c6ba-11e6-8ef3-93838fd08664.png)

la 1ere image j'ai ajouter quelque titre pour tester que j'ai dans "collection" ( chemin d’écrit plus haut ) en passant par vStream.
La 2eme image c'est la même liste dans "collection" utilisant un autre programme, j'aimerai si possible obtenir le même résultat sur la 1ere image.

Donc je sais que le Trakt sur vStream est encore en beta c'est peut être pour sa cela ne fonctionne pas encore je pose la question pour savoir si c'est normal dans l’état actuel ou si je peut remédier au problème en faisant quelque chose.

**Comment by TmpName** [comment]
Ben pour le moment sur la version actuelle, tu n'as pas les resumes mais tu as le poster et le fan art en fond.

Ha wi mince ^^, me souvient, j'ai corrige ca le lendemain de la sortie de la version.
Alors ca va etre un poil complique, ouvre le fichier trakt.py de ton repertoire de Vstream avec un editeur de texte, et colles dedans le contenu de celui la
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/lib/trakt.py

**Comment by LordVenom** [comment]
Perso j'ai tester en proposant un choix mais c'est pas concluant ça retourne pas les bon trie.

xbmcplugin.addSortMethod pour les courageux.

**Comment by TmpName** [comment]
Ha ? ca marche pas bien la technique a @Kodigoal  ?

**Comment by phenix60** [comment]
Bah moi j'ai tester en copiant le Trakt.py que tu ma donner TmpName donc sa a corriger une bonne partie des (poster/ fanart) manquant environ 90% mais bizarrement j'ai encore quelque titres qui n'ont pas le ( poster /fanart) d'activer. Je joindrait un screen plus tard si tu veut la pas trop le temps.

Et merci en tous cas de ton aide ^^
