### ISSUE TITLE
film strea ming

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#759]
Depuis plusieurs mois j ai pas vue un film sur ce site est ce que il  y a un bug sur cette source ou le site lui meme qui ai en pagne  ou ca ne fonctionne pas que chez moi remarque la liste des films s affiche normalement le problème ai dan showHoster.

**Comment by johngf** [comment]
Chez nous ça fonctionne

**Comment by Kodigoal** [comment]
Chez moi fonctionne plus niveau showhosters
Adresse en .club 
Regex a refaire.
Hd stream in k o aussi

**Comment by johngf** [comment]
chez moi ça a toujours fonctionné les 2

**Comment by Kodigoal** [comment]
Bien vu ^^ liens changent selon pays.

**Comment by johngf** [comment]
l'adresse en club ne change rien au fonctionnement pour l'instant je l'avais deja remarqué

**Comment by Kodigoal** [comment]
Oui.
Sinon on peut pas le gruger en envoyant ip french dans le code ?

**Comment by johngf** [comment]
je ne pense pas que se soit possible tu peut pas leur donné une fausse ip comme un faux user agent

**Comment by mino60** [comment]
Toujours rien remarque je suis a l ouest d algrie  voila le log ;

`20:15:24 T:6728   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires
20:15:24 T:6728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires) failed
20:15:26 T:3260  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:15:26 T:3260  NOTICE: 	[PLUGIN] Vstream: load site film_streaming_co and call function showHosters
20:15:28 T:3260  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:15:28 T:6728   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires
20:15:28 T:6728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires) failed
20:15:31 T:6660  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:15:31 T:6660  NOTICE: 	[PLUGIN] Vstream: load site film_streaming_co and call function showHosters
20:15:34 T:6660  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:15:34 T:6728   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires
20:15:34 T:6728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires) failed
20:15:37 T:7704  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:15:37 T:7704  NOTICE: 	[PLUGIN] Vstream: load site film_streaming_co and call function showHosters
20:15:39 T:7704  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:15:39 T:6728   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires
20:15:39 T:6728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires) failed
20:15:41 T:6096  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:15:41 T:6096  NOTICE: 	[PLUGIN] Vstream: load site film_streaming_co and call function showHosters
20:15:43 T:6096  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:15:43 T:6728   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires
20:15:43 T:6728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires) failed
20:15:45 T:8004  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:15:45 T:8004  NOTICE: 	[PLUGIN] Vstream: load site film_streaming_co and call function showHosters
20:15:48 T:8004  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:15:48 T:6728   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires
20:15:48 T:6728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sMovieTitle=Les%207%20Mercenaires&sThumbnail=http%3a%2f%2fwww.film-streaming.co%2fthumb%2fles-7-mercenaires-streaming-2016.jpg&site=film_streaming_co&siteUrl=http%3a%2f%2fwww.film-streaming.co%2fles-7-mercenaires-streaming.php&title=Les%207%20Mercenaires) failed
`

**Comment by TmpName** [comment]
Essayes sur un navigateur pour voir si ca ne vient pas de ton ip.

**Comment by mino60** [comment]
Ca marche sur mon navigateur ?!!..
![sans titre](https://cloud.githubusercontent.com/assets/11494048/21406520/65090aec-c7cc-11e6-935e-ea110fa9924f.png)

**Comment by Kodigoal** [comment]
Video via FlashXsur ton image.
Faut ip french pour avoir les vidéos en lien direct m3u8.
Code à modifier si pas résultat pour le regex actuel.

**Comment by TmpName** [comment]
J'ai fait une version a tester, mais moi je ne peux pas la tester, je passe par des web proxy qui me modifient le code, donc e peux pas etre sur.

Si ca ne marche pas jettes un oeuil au regex ligne 259.

**Comment by Kodigoal** [comment]
après Test rapide ca a l'air ok.
Sauf sur hoster vidup , regex a maj je pense:
`sPattern = '"file":"([^"]+)","label":"([0-9]+)p"
`

**Comment by mino60** [comment]
Ooi effectivement ca marche tres bies juste il y a un probleme de qualité
les 7 mercenaire la video et on sd

![sans titre](https://cloud.githubusercontent.com/assets/11494048/21448754/476ca5dc-c8e6-11e6-8c51-be5149d6eb3b.png)

**Comment by TmpName** [comment]
Ben sur le nvavigateur tu devrais avoir la meme qualitee non ? Je recupere juste le lien flash.
Donc soit tu as la meme qualitee, soit c'est le resolver flash qui deconne.

**Comment by Kodigoal** [comment]
Non j'ai croisé du vidup openload flashX ..
Pour la correction oui dans le host vidup , après à vérifier sur d'autres liens vidup d'autres sites si c'est pareil ...

**Comment by johngf** [comment]
Effectivement ce n'est pas parcequ'il marquesur le site 7 mercenaires en strea ming hd que les liens sont en hd
