### ISSUE TITLE
Z T

### ISSUE THREAD

**Issue by Brahimbaz** [Kodi-vStream/venom-xbmc-addons#760]
Salut à tous,
Je pense que ht tp://www.zone-telechargement.ws/ est le nouveau ZT.
J'ai fait le tour du site, il y a toutes les saisons d'une serie proposé sur la meme page avec les vf hdtv, vf 720, vf 1080p, vostfr hdtv, vostfr 720p, vostfr 1080p avec tous les fournisseurs habituel uptobox, 1fichier, uploaded, rapidgator, turbobit, uplea.
Sur les films il y a pareil vf hdtv vf 720p vf 1080p vf hdlight 720p etc etc 
Il n'y a pas toutes les saisons encore sur toute les series mais je pense que c'est le temps qu'ils refasse tout le boulot.

**Comment by johngf** [comment]
#517 ici

**Comment by Brahimbaz** [comment]
Non du tout, http://www.zone-telechargement.ORG est une très mauvaise copie. Mais le http://www.zone-telechargement.WS est "si" c'est bien une copie la meilleur des copies. Le catalogue du site est en train de se remplire. Ce qui est normal vue que le site à ouvert ces portes la 1ere semaine de décembre. Il est mise à jour tous les jours. Il utilise le dl-protect. Et il y a pleins de choix de formats videos (dont les hdlight sur les film) et de sources de telechargements. Je pense qu'il mérite de près et de loin ca place sur les sources VSTREAM.
