### ISSUE TITLE
free telechargement

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#761]
#Il y a un bug free-telechargement.org dans  Next page je voulai le corriger sur la beta mais je ne sais pas comment activer Pull request
`
  {  sPattern = '<span class="courante">[0-9]+<\/span> *<a href="(.+?)">'  }`

**Comment by chataigne73** [comment]
chez moi le next page fonctionne
tu as observé un pb de comportement dans quelles rubrique ?

**Comment by mino60** [comment]
Dans la section Dernier films HD-720p et HD-1080p ajoutés la 3 et 4iem page et plus!!!!...

**Comment by TmpName** [comment]
Ha wi effectivement, pareil chez moi.
Mais normallement si tu essayes d'editer la source.
1 - tu t'es inscrit sur le "truc" de LordVenom (je sais plus comment ca s'appelle) et la modif se fait direct.
2 - sinon ca cree automatiquement le pull, qui va etre valide.

Sinon c'est juste une remarque, mais vu le nbre de resultats par page c'est pas mieux d'utiliser le mode liste plutot que le mode vignette ?

**Comment by chataigne73** [comment]
pb nextpage corrigé ...  je regarde le reste

**Comment by mino60** [comment]
J'ai constaté qu'il y a un bug dans la recherche section Dernier films HD-720p et HD-1080p

le regex @chataigne73  n'ai pas juste 
Edit:
    sCom = ''
    sQual = ''
    sHtmlContent = sHtmlContent.replace('<span style="background-color: yellow;"><font color="red">', '').replace('</font></span>', '').replace('</b></p>', '')

{  sPattern = '<p style="font-size: 18px;"><a href="([^"]+)">(.*?).*?<td align="center"> *<img src="([^"]+?)".+?<b>Description : </b></br></br>(.+?)<br /><br />Origine'  }

exemple:
je cherche le film titre "favelas" le resultat = Pelé la légende
je cherche le film titre Avant toi le resultat = 0
avec le corrective voila le resultat:
![sans titre](https://cloud.githubusercontent.com/assets/11494048/21412050/7e52ca80-c7ed-11e6-8f7d-3daf4bf4f70d.png)
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/21412054/894d6a6c-c7ed-11e6-8b80-360ef94a67e3.png)

**Comment by TmpName** [comment]
C'est bon modif avec sHtmlContent.replace en place.
