### ISSUE TITLE
Z-T encore

### ISSUE THREAD

**Issue by neoseeyou** [Kodi-vStream/venom-xbmc-addons#762]
Salut à tous

Merci à l'auteur pour ce plugin ;-)

Je voulais savoir si vous comptiez rajouter la source du nouveau site de ZT: zone-telechargement.ws

Je profite de ce poste pour demander si une fonction comme celle présente sur exodus permettant de rentrer son compte real debrid pourrait voir le jour?

**Comment by neoseeyou** [comment]
J'ai solutionné ma deuxieme question avec url resolver ;-)

**Comment by johngf** [comment]
#517 #720
