### ISSUE TITLE
codage html

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#763]
Hi, comment on se débarrasse de se genre de codage (html entity) pour les accents sans utilisé replace ? j'ai essayé decode et encode 
plein de truc meme cUtil unescape qui donne une erreur ascii codec ... rien y fait
`enqu&ecirc;te` `L'&Acirc;ge` `&Agrave;`

**Comment by TmpName** [comment]
cUtil().unescape devrait marcher mais il faut surement convertir d'abord la chaine en utf8.
>                sTitle = aEntry[0].decode("utf8")
                sTitle = cUtil().unescape(sTitle).encode("utf8")

**Comment by johngf** [comment]
Je pense l'avoir fait de cette maniere mais pas sur je testerai ça pour voir

**Comment by johngf** [comment]
bon ça fonctionne par contre si j'enleve le ".encode("utf8")" ça fonctionne plus
