### ISSUE TITLE
Quel site est le plus rempli et autres questions

### ISSUE THREAD

**Issue by yamoky** [Kodi-vStream/venom-xbmc-addons#765]
Salut tout le monde j'ai quelques petites questions

1) Quel est le site le plus remplie (EN HD de préférence )?

2) J'aimerais transférer des compte premium de jdownloader si possible

3)J'aimerais vous mettre les comptes premium directement ici (je ne connais pas le codage) sachant qu'il change trés souvent comme ça les personnes peuvent télécharger au max

j'ai remarquer un truc quand on met un compte on as plus le choix de passer en streaming c'est dommage je penses car des fois (perso) je passes en sur mon data mobile et j'aimerais éviter de regarder un films qui pèse 8 go au lieux de 1.2go

Merci a l'équipe de Vstream

Au fait a chaque réparation de pc que je fait j'installes kodi et vstream ;p

**Comment by TmpName** [comment]
Heu, c'est quoi des compte premiums Jdownloader ? C'est des premiums sur differents hebergeurs ? Vstream en gere nativement 3 ou 4 sinon il te faut passer par urlresolver.

Si tu passes par un premium uptobox, tu as tjours la possibilitee de passer par leur site de streaming uptostream, mais si tu passes par onefichier, tu n'as qu'un seul fichier de propose donc pas possible d'avoir un "fichier light" ?

**Comment by yamoky** [comment]
j'ai du modifier le fichier pour que je puisse vous le passé

a changer .html et pas en .png

tu auras normalement tout le compte et mot de passe 



![jdownloaderpasswordlist](https://cloud.githubusercontent.com/assets/23269347/21440162/f43d88b2-c891-11e6-98c0-688e817df926.png)

**Comment by TmpName** [comment]
En fait ce sont des user et des mots de passe pour certains hebergeur ?
Si c'est ca, j'en ai vu aucun gere par Vstream, mais certains devrait marcher avec urlResolver ( il y a des debrideurs dans la liste)

**Comment by LordVenom** [comment]
humm...
