### ISSUE TITLE
il n y a pu de menu! 

### ISSUE THREAD

**Issue by djayan07** [Kodi-vStream/venom-xbmc-addons#766]
Depuis quelques jours au menu principal il n y a pu de menu 
![capturevstream](https://cloud.githubusercontent.com/assets/15129314/21412053/3d93aef6-c7bb-11e6-9c93-501701acef13.PNG)

**Comment by Kodigoal** [comment]
Regarde ici vers la fin pour régler le soucis.
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/748
