### ISSUE TITLE
ExodusFr repository

### ISSUE THREAD

**Issue by bubuleur** [Kodi-vStream/venom-xbmc-addons#767]
Bonjour,
Je viens vers vous pour savoir pourquoi le repository d'exodusfr ne marche plus
Cordialement
Merci

**Comment by johngf** [comment]
comment veut tu qu'ont le sache ? ici c'est uniquement vstream personne ici ne fait partie de kodi ou exodus

**Comment by bubuleur** [comment]
pourtant 
https://plus.google.com/+LordVenom57/posts/VQygcLVQs1X

**Comment by johngf** [comment]
oui @LordVenom  a partagé le lien exodus voila tous

**Comment by bubuleur** [comment]
ah pardon donc l'addon a peut etre mort c'est bete sinon 
Merci pour tes renseignements

**Comment by johngf** [comment]
je crois qu'il fonctionne encore mais doit manqué des dépendances pour l'install il faut le fichier log pour savoir ce qu'il se passe quand tu essaie de l'installé kodi.log

**Comment by bubuleur** [comment]
Ah d'accord moi je l'installe sur un raspberry pi c'est dans ce chemin $HOME/.kodi/temp/kodi.log

**Comment by johngf** [comment]
je viens de jeter un oeil a exo dus fr et il que 5 source de film et serie ...

**Comment by bubuleur** [comment]
C'est vrai que c'est un peux pauvre mais je m'en sers de compléments a Vstream

**Comment by johngf** [comment]
je suis pas sur mais je pense qu'il a été abandonné la page google + du developpeur n'existe plus

**Comment by bubuleur** [comment]
j'ai vu oui j'allais sur ça page avant il voulez améliorer l'addon alors la je sais pas
En tout ça merci pour ton aide

**Comment by TmpName** [comment]
Je sais pas non plus ce qui s'est passé, Addonmaster a completement disparu, sans donner d'infos officielles.
Il a peut etre juste besoin d'un break (gerer un addon tout seul c'est un enfer).
