### ISSUE TITLE
problème réinstallation vstream

### ISSUE THREAD

**Issue by erwann29280** [Kodi-vStream/venom-xbmc-addons#772]
Bonjour,
tout d'abord bravo pour votre travail, je possède une atv2 avec kodi hélix. La dernière mise a jour s'est bien installée et tout fonctionnait normalement, au redémarrage stream avait disparu des extensions vidéos.
J'ai donc voulu réinstaller, pour la version 0.0.2 l'extension s'active et se met a jour mais impossible de la lancer (bouton grisé) depuis extensions activées puis extensions vidéos.
Et depuis télécharger des extensions puis vstream repository et rien (trois petits points).
Pour les autres versions ça me marque dépendances non satisfaites.
Pouvez vous m'aider svp ?
Par avance merci, et surtout passez de bonnes fêtes de fin d'année

**Comment by johngf** [comment]
Kodi helix est dépassé tu ne peut pas installé kodi 16 jarvis sinon sans le fichier log on peux pas vraiment t'aider kodi.log

**Comment by erwann29280** [comment]
dans préférences je n'ai que kodi puis addons, media, sounds, system,temp, userdata

**Comment by TmpName** [comment]
Aucun fichier appelle kodi.log ? Fichier cache ?
Il y a pas moyen de faire une recherche sur ton systeme ?

**Comment by erwann29280** [comment]
C'est bon j'ai tout supprimé et tout réinstaller
Ça fonctionne à nouveau
Merci beaucoup
Et bonnes fêtes de fin d'année 
Et encore merci et bravo pour votre travail
