### ISSUE TITLE
Comment affiché Fanart ..

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#776]
Salut ...

comment affiché les Fanarts sur kodi sur la source topimdb est ce que il faut une adresse api pour ca
Fanart sur la source themoviedb

![sans titre](https://cloud.githubusercontent.com/assets/11494048/21461635/ac0047e8-c953-11e6-9162-2d12a65ca4a7.png)

**Comment by TmpName** [comment]
Si tu actives les metas datas c'est automatique, mais c'est lourd pour un usage courant.
Sinon faut une API oui, y a un exemple dans trakt.py.
