### ISSUE TITLE
1fichier.com => Source

### ISSUE THREAD

**Issue by Smeagold** [Kodi-vStream/venom-xbmc-addons#777]
Bonjour,

Merci tout d'abord pour votre travail! 
Je voulais savoir si c'est possible de faire le lien avec un compte premium sur 1fichier (comme pour uptobox #661). Je stock pas mal de film dessus et j'aimerais pouvoir les lire directement de vstream! (être autonome (RIP ZT...) sans passé par un site de stream ou down)
Çà serait génial! En plus si je pouvais par la suite trouver un moyen de les afficher en vignettes ça ferait une vidéothèque dans le cloud!

Merci à vous!

Edit : J'ai essayé de mettre onefichier.py dans  \resources\sites\ mais il ne s'affiche pas dans vstream (c'est peut être pas du tout la bonne manip!)
Edit 2: Je suis preneur du fichier qui sert pour lire depuis uptobox j'ai un compte premium aussi mais moin fournis. Je le trouve pas sur le l'issue #661 .Thx

**Comment by LordVenom** [comment]
Bonjour,

- Pour Onefichier a voir.
- Pour Upto si tu as la dernière version de vStream il est dedans rubrique toutes les sources / VotrecompteUptobox.

**Comment by Smeagold** [comment]
@LordVenom Merci impec pour uptobox j'avais pas la dernière version. J'ai plus qu'a transférer mes 12TB sur uptobox de 1 fichier si personne de motivé pour l'host 1fichier.

Merci!

**Comment by LordVenom** [comment]
La il vas te falloir de la patiente c'est période de fête.

**Comment by diouf76** [comment]
Cela m intéresse, il suffit de mettre les fichiers vidéos sur le compte premium et de le renseigner dans vstream pour pouvoir les consulter et les voir sur vstream? Et avec les jaquettes?  Et autre question est il possible de le faire directement dans le menu film de kodi? 

Merci de vos réponses
