### ISSUE TITLE
HELP : Localiser les fichiers que met Kodi sur mon PC lorsque je lis une video

### ISSUE THREAD

**Issue by euro912** [Kodi-vStream/venom-xbmc-addons#778]
Bonjour à tous,

je suis à bout. J'ai installé Kodi y a 2 jours et puis boum , après avoir regardé 3 films sur Vstream ( même pas jusqu'au bout !u ) 4 GIGA ont disparu de mon disque dur. Donc mon soucis, c'est de localiser ou Kodi a stocké les fichiers qui m'ont pris 4 giga et les supprimer. J'ai essayé en désinstallant Kodi ou en allant supprimer le fichier Kodi dans Appdata mais je n'ai pas récupéré mes 4 giga. Ou sont-ils s'il vous plais ? Mon ordi rame à mort maintenant à cause de ca.

Merci pour votre aide

PS: j'ai cherché partout sur les internet mais pas trouver de solutions meme en installant " mAINTENACE TOOLS" et en supprimer cache, logs, add-on. :(

**Comment by LordVenom** [comment]
Bonjour,

vStream ne garde pas de fichier une fois lus puisque c'est du Streaming à moins que tu les ais téléchargés dans ce cas tu les trouveras dans la rubrique téléchargement.

- Tu as dans les préférence de vStream de quoi vider le cache de vstream et aussi de Kodi.
- Kodi créer des répertoire cacher regarde si il font 4go c:/utilisateurs/ %APPDATA%\roaming\kodi\
APPDATA est un fichier cacher.

**Comment by euro912** [comment]
Bonjour,

je ne pense pas avoir télécharger "volontairement" une vidéo mais dés que je lance un film, 1 ou 2 gigas disparaissent de mon disque dur. Vous voyez le problème ? c'est normal ?

Bien à vous

**Comment by euro912** [comment]
Et le dossier Kodi dans appdata ne fait que 60 mb... :(

**Comment by johngf** [comment]
tu as window 7 tu lance des films a partir de quel liens upto box 1 fichier ?, les films que tu lance sont de quelles tailles hd 1080p 3d ? tu as fait une recherche sur ton ordi en utilisant le nom du film que tu as regardé ?

**Comment by euro912** [comment]
j'ai regardé trois bouts de film. Un en hd et les autres normal. ils etaient sur openload je pense.

**Comment by euro912** [comment]
pardon, oui j'ai windows 7. Et oui j'ai essayé de rechercher les fichiers mais sans succès.

**Comment by johngf** [comment]
bah comme a dit @LordVenom vstream n'enregistre pas les fichiers si les lis seulement, tu n'as pas eu une ou des maj de w7 qui a crée des points de restauration ?

**Comment by euro912** [comment]
je ne pense pas. je vais essayer de désinstaller complètement Kodi et on verra. Ou trouver les préférences pour Vstream ?

**Comment by johngf** [comment]
desinstaller kodi ne sert a rien si le fichier est ailleur

**Comment by euro912** [comment]
d'accord.
"Tu as dans les préférence de vStream de quoi vider le cache de vstream et aussi de Kodi. "
µ
Ou trouver les préférences svp ?

**Comment by johngf** [comment]
je ne pense pas que le probleme vienne de kodi ou vstream

**Comment by Kodigoal** [comment]
Utilise  voir un logiciel pour voir quel répertoire prend le plus d'espace sur ton DD , pêtre les sauvegardes du système ...
http://forums.cnetfrance.fr/topic/1248425-trouver-les-dossiers-utilisant-le-plus-d-espace-disque-avec-treesizefree/
tu fais un scan avant avec ce logiciel ,  tu lances kodi vstream pour lancer un film et si t'as perdu 1go , tu rescan avec le logiciel.
Tu devrais trouver le fautif qui te pompe l'espace.

**Comment by euro912** [comment]
ok merci

**Comment by Kodigoal** [comment]
Des news?

**Comment by euro912** [comment]
non pas encore eu le temps d'essayer, je verrais ce soir :)

**Comment by johngf** [comment]
tu as réussi?
