### ISSUE TITLE
upload log

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#779]
Slt comme beaucoup de monde ne sait pas ce qu'est le fichier kodi.log ou n'y a pas accés sur les "machines exotiques"
j'ai ajouté ce code a runscript qui upload kodi.log sur un site et envoie en réponse un code 
code qui permettra d'accéder au log pour celui qui souhaite aider a résoudre l'issue.
en utilisant l'adresse que j'ai replace dans le script + code
https://raw.githubusercontent.com/johngf/divers/master/uplog.py

**Comment by Kodigoal** [comment]
La classe ^^ merci

**Comment by johngf** [comment]
il faut ajouter 
<setting label="Upload log" type="action" action="XBMC.RunScript(special://home/addons/plugin.video.vstream/resources/lib/runscript.py, uplog)"/> 
a settings .xml en dessous de 
<setting id="history-view" type="bool" label="Activer l'historique de recherche" default="true"/>

**Comment by Kodigoal** [comment]
ok je vais tester

**Comment by Kodigoal** [comment]
Rajouter post_data['private'] = '1' sinon ca apparait dans la List recent sur le site.
Sinon niquel ^^

**Comment by TmpName** [comment]
Vraiement utile, meme pour les configs classiques.

**Comment by johngf** [comment]
Je vais voir ça demain on peut aussi mettre une date d'expiration ,un nom ...

**Comment by johngf** [comment]
v2 avec un autre hebergeur vu que le premier ne fonctionne pas aujourd'hui y compris sur leur site
https://raw.githubusercontent.com/johngf/divers/master/uplogv2
vais voir si par l'api paste bin ça fonctionnerai

**Comment by johngf** [comment]
bon alors:
text share com
le 1er : refonctionne mais date d'expiration est dans l'api mais ne fonctionne pas(voir fiabilité sur long terme)
slexy org
le 2eme : fonctionne
paste bin
le 3eme : fonctionne mais la personne qui ira voir le log pour la 1ere fois devra résoudre un recaptcha
https://raw.githubusercontent.com/johngf/divers/master/uplogv3

**Comment by johngf** [comment]
bon jai choisis slexy finalement (private + 3j d'expiration)donc il faudra utilisé 
xxx://slexy.org/view/ + code
ou
xxx://slexy.org/raw/ + code

**Comment by LordVenom** [comment]
Tester http://slexy.org/view/s2lnos4II4 Nickel

**Comment by TmpName** [comment]
XD, merci mais je pense bien ne pas etre le seul, pour le moment je passais par le refresh cache des options de Vstream.

**Comment by johngf** [comment]
On pourrait ajouter la marche a suivre au wiki.

**Comment by TmpName** [comment]
Yep en editant la page ou sont les repertoires logs.

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil
