### ISSUE TITLE
Bibliothèque plusieurs kodi

### ISSUE THREAD

**Issue by hornet49** [Kodi-vStream/venom-xbmc-addons#780]
Bonjour,
ayant  5 installation de kodi dans mon foyer, j'ai vu un tuto pour centralisé sa bibliothèque avec une base sql. Nickel ça fonctionne, par compte quand je mets un film dans le marque page, il n’apparaît pas sur les autre kodi d’ailleurs ni les films vu (à confirmer pour le dernier point)
Si y'a une solution que je connais pas je suis preneur....
en tout cas sinon bravos pour ce travail !!!! 
c'est déjà formidable après si c'est pas possible c'est pas gênant ;-)

**Comment by johngf** [comment]
C'est normal vstream a ça propre db pour les marques page il ne sont pas dans la db de kodi

**Comment by hornet49** [comment]
Merci pour t'as réponse super réactive !!!!
Ok c'est ce que je pensais dommage et sinon pour les marqués en "Vu" ça, ça fonctionne ou c'est pareil ?

**Comment by johngf** [comment]
Je pense que c'est pareil a confirmé,par contre tu peux copier le fichier db sur tes autres machines

**Comment by hornet49** [comment]
ou le mettre sur un nas en partage peut être ? pas possible ?

**Comment by johngf** [comment]
Ça jamais testé peut etre possible, mais je pensais a le mettre a jour avec un script chaque jour sur chaque machine a voir il y a peut etre une soluce sur google

**Comment by johngf** [comment]
Apres est ce que le systeme que tu as utilsé pour kodi ne fonctionnerai pas avec la db vstream qui est aussi sql?

**Comment by hornet49** [comment]
Alors j'ai utilisé ce tuto: http://technotips.fr/132-kodi-xbmc-creer-base-donnees-centralisee/
je confirme près test que les coches Vu et non Vu fonctionne avec Vstream
par compte pas les marques pages ni l'historique des recherches.
Est ce que ses 2 fonctions peuvent êtes mise dans la même "base sql" ?

**Comment by TmpName** [comment]
Nope.
Les vus sont depuis 1 ou 2 MAJ dans la base sql de kodi mais les marques pages sont propres a Vstream, sinon testes la mise en librairie au lieu des marques pages.

**Comment by hornet49** [comment]
Alors là, comment on fait pour mettre en librairie ? car j'ai bien les options "marquer Vu/recherche similaire/bande annonce/Information marque page/voir marque page" mais j'ai pas mettre en librairie :-(
et pourtant j'ai bien un menu librairie au démarrage mais celui-ci  contient film et série mais les 2 sont vides j'ai du loupé quelque chose :-(

**Comment by johngf** [comment]
La librairie s'affiche sur le iens finale de la video

**Comment by TmpName** [comment]
Ha wi merde donc galere pr les series.

**Comment by hornet49** [comment]
ha oui dommage ça :-(

**Comment by johngf** [comment]
Je suis tombé sur ca @hornet49 pour synchro
https://github.com/fabienLadrat/kodiUpdateDatabase
