### ISSUE TITLE
Joyeux Noël et Bonne Année

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#781]
Tout est dans le titre !
Bonnes fêtes de fin d'année à tous !!!

**Comment by TmpName** [comment]
Lol pareillement, mais en fait j'attendais le 1 er.

**Comment by LordVenom** [comment]
Merci Joyeux noel a vous aussi. La bonne année dans 6 jours :)

**Comment by Kodigoal** [comment]
Merci bonnes fêtes à vous.

**Comment by LordVenom** [comment]
Cette année vStream à reçus 185 481 288 sessions, détail dans un post début 2017. 

Bref le chiffre importe peux.C'est juste motivant et vous êtes motivant vous les programmeurs, les bidouilleurs, les curieux.Merci d'avoir fait de vStream ceux qu'il est !!!

Bonne et heureuse année 2017

**Comment by GitanHubert** [comment]
Bonne année
