### ISSUE TITLE
url avec des caractères accentué (UTF-8) ne semble pas fonctionné

### ISSUE THREAD

**Issue by stevedion** [Kodi-vStream/venom-xbmc-addons#782]
Bonjour,

  Les URL avec des accents ne semble pas fonctionné dans VStream (erreur= "Error, could not open file")

  log:

{code}
16:39:32 T:10228  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
16:39:32 T:10228  NOTICE: 	[PLUGIN] Vstream: load site megastream and call function showHosters
16:39:36 T:10228  NOTICE: 	[PLUGIN] Vstream: close dialog
16:39:36 T:10228  NOTICE: 	[PLUGIN] Vstream: Table initialized
16:39:38 T:3388  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
16:39:38 T:3388  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
16:39:38 T:3388  NOTICE: 	[PLUGIN] Vstream: Hoster - play https://openload.co/embed/vK8CW-hOPM4/
16:39:38 T:3388  NOTICE: url teste : https://openload.co/embed/vK8CW-hOPM4/
16:39:38 T:3388  NOTICE: AA encryption
16:39:38 T:3388  NOTICE: hidden url : ('iaMcJzZz5Sx', '102981819512256201771126718055012341327920110031470710205276152391923218166112101620515226171561023118115060960416604175121681217613231181891409605128080560106802326200800021413237180800113506269181240523013')
16:39:38 T:3388  NOTICE: 1 er url : https://openload.co/stream/vK8CW-hOPM4~1482788378~70.31.0.0~PT9FKYJd?mime=true
16:39:41 T:3388  NOTICE: Url decodee : https://pgli2y.oloadcdn.net/dl/l/W3pRIbx4eJUAKpwB/vK8CW-hOPM4/Les+Animaux+fantastiques.Film%C3%A9.FR.kl?mime=true
16:39:41 T:3388  NOTICE: Url validee : https://pgli2y.oloadcdn.net/dl/l/W3pRIbx4eJUAKpwB/vK8CW-hOPM4/Les+Animaux+fantastiques.Film%C3%A9.FR.kl?mime=true
16:39:41 T:3388  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
16:39:41 T:3388  NOTICE: 	[PLUGIN] Vstream: player initialized
16:39:41 T:3388  NOTICE: 	[PLUGIN] Vstream: Player use setResolvedUrl() method
16:39:41 T:2840  NOTICE: DVDPlayer: Opening: https://pgli2y.oloadcdn.net/dl/l/W3pRIbx4eJUAKpwB/vK8CW-hOPM4/Les+Animaux+fantastiques.Film%C3%A9.FR.kl?mime=true
16:39:41 T:2840 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:39:41 T:852  NOTICE: Creating InputStream
16:39:43 T:852  NOTICE: Creating Demuxer
16:40:01 T:852   ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file https://pgli2y.oloadcdn.net/dl/l/W3pRIbx4eJUAKpwB/vK8CW-hOPM4/Les+Animaux+fantastiques.Film%C3%A9.FR.kl?mime=true
16:40:01 T:852   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
16:40:01 T:852  NOTICE: CDVDPlayer::OnExit()
16:40:45 T:2840   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=+%5BCOLOR+coral%5D%5BFILME%2FFR%5D%5B%2FCOLOR%5D+FR+-+Les+Animaux+fantastiques+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&sHosterIdentifier=openload&sTitle=+%5BCOLOR+coral%5D%5BFILME%2FFR%5D%5B%2FCOLOR%5D+FR+-+Les+Animaux+fantastiques+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2Fopenload.co%2Fembed%2FvK8CW-hOPM4%2F&sFav=play&sMediaUrl=https%3A%2F%2Fopenload.co%2Fembed%2FvK8CW-hOPM4%2F&sCat=4&sId=cHosterGui&sFileName=FR+-+Les+Animaux+fantastiques]
16:40:45 T:2840  NOTICE: CDVDPlayer::CloseFile()
{code}

Kodi 16.1

**Comment by Kodigoal** [comment]
Fonctionne chez moi meme site meme film.

**Comment by stevedion** [comment]
j'ai cette erreur dans Kodi en cliquant sur le lien du film.  Si je copie/paste l'URL dans mon browser, le vidéo démarre mais Kodi n'arrive pas à l'ouvrir!

Est-ce qu'il y aurait une config à vérifier/modifier?

 Merci pour votre aide

**Comment by Kodigoal** [comment]
dernière Maj d'openload.py ya 20 jours donc je pense t'es à jour de ce côté là..
Faut insister en relancant plusieurs fois le film , il va se lancer.
J'ai relancé 10x avant.

**Comment by Kodigoal** [comment]
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/megastream.py

https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/hosters/openload.py

Tu peux copier/coller le contenu dans les fichiers correspondants en local chez toi,
pour être sur d'être à jour...
Après ..pour moi faut juste insister si erreur.

**Comment by stevedion** [comment]
ok ça finis par fonctionner.

Merci beaucoup!
