### ISSUE TITLE
Is VStream broken in Kodi v17 “Krypton” Beta 7

### ISSUE THREAD

**Issue by emailradhesh** [Kodi-vStream/venom-xbmc-addons#783]
Text items are missing after updating to Kodi v17 “Krypton” Beta 7. May be the new default skin has broken this add-on. Isn't it?

**Comment by emailradhesh** [comment]
Internet videos aren't working even after reinstalling add-on or updating repos

**Comment by johngf** [comment]
Vstream is not yet fully compatible with kodi 17 beta (kodi 16 jarvis recommended)
text items : replace content in /plugin.video.vstream/resources/language/English/strings.xml
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/language/English/strings.xml
and clear xbmc cache in vstream parameter and restart

**Comment by emailradhesh** [comment]
Thanks @johngf Let me apply, fix it and close this issue.

**Comment by johngf** [comment]
any news ?

**Comment by emailradhesh** [comment]
Sorry for late reply @johngf Was ill and did not check it. For time being I'll close the issue.
