### ISSUE TITLE
KAYDO

### ISSUE THREAD

**Issue by Gregwar** [Kodi-vStream/venom-xbmc-addons#784]
Le nouveau HD STREAM
http://pastebin.com/P6P9mQUs

**Comment by johngf** [comment]
Deja fait par @LordVenom

**Comment by Gregwar** [comment]
Oops :)

**Comment by Gregwar** [comment]
Il marche chez toi celui de @LordVenom ?

**Comment by Gregwar** [comment]
Pas chez moi
Apparement j'ai besoin d'ajouter des r=n dans l'URL

**Comment by johngf** [comment]
J'ai pas testé mais je pense qu'il a juste changé le nom du site

**Comment by Gregwar** [comment]
En fait y'a pas mal de trucs qui ont l'air d'avoir changé

**Comment by LordVenom** [comment]
Oui il fonctionne j'ai juste pas mis les séries.

**Comment by Gregwar** [comment]
Mets ton navigateur en privé et va sur http://www.kaydo.ws/ tu verra que tu
sera redirigé vers le login
Par contre http://www.kaydo.ws/?r=n la ca passe

**Comment by LordVenom** [comment]
lol non

**Comment by Gregwar** [comment]
Ça fait pareil sur mon tel en 4g

**Comment by LordVenom** [comment]
On vas attendre que les autres tests si je peux éviter les r=n partout.

**Comment by Gregwar** [comment]
En fait une fois que tu as mis r=n tu peux naviguer, ça doit definir un
truc en session

**Comment by LordVenom** [comment]
La même session sur mon tel et mon ordi ? non c'est autre chose.

**Comment by Gregwar** [comment]
@LordVenom ça a un rapport avec les IPs, si je proxy par mon serveur par exemple ça me redirige tout le temps vers le form de login (même avec r=n)

**Comment by johngf** [comment]
#759 il detecte les ips etrangere ou proxy vpn

**Comment by Kodigoal** [comment]
Oui faut ip french sinon k.o , faut le r=n
Et film streaming co est redirigé sur kaydo là...

**Comment by Gregwar** [comment]
(Mais c'est un peu bidouille le code)

Le mar. 27 déc. 2016 19:51, Grégoire Passault <g.passault@gmail.com> a
écrit :

> Dans mon pastebin ya le r=n
>

**Comment by Kodigoal** [comment]
vais test merci

**Comment by Kodigoal** [comment]
Parler trop vite...
Si VPN , même avec le r=n en utilisant ton fichier  , 
ca ne fonctionne pas...
En passant par le navigateur, même en mettant le r=n , me redirige toujours vers page login...
Si ip French,  le commit de LordVenom  ou ta version fonctionne toutes les 2.

**Comment by Gregwar** [comment]
Ok, chez moi  maintenant en 4g systématiquement le login et sur ma box (fr)
ça marche que avec r=n

**Comment by Kodigoal** [comment]
4g je pense c'est vu comme un proxy l'ip publique donc blocage.
Vpn ca passe par https://anonym.to/?http://www.kaydo.ws
Une fois charger le site , c'est ok.
Pêtre si on envoit 1 fois cette url en début de code , ca marchera pour lister.
Je sais pas trop.

**Comment by johngf** [comment]
bon chez moi la version de venom fonctionne sauf hoster vu que ça finit plus par m3u8 mais par =

**Comment by johngf** [comment]
apres avoir fait plusieur essaie de lecture ça fonctionne plus maintenant

**Comment by Kodigoal** [comment]
Envoyer des valeurs en header pour spoofer l'ip.
HTTP_X_FORWARDED_FOR	ip french
HTTP_X_REAL_IP  ip french
Pêtre que ca passera en vpn.
h ttp://kaydo.ws/test.php  on voit ses valeurs tableau php variable.

**Comment by Gregwar** [comment]
@johngf les fichiers sont des bons .mp4 directs maintenant, je ne comprends pas ton problème

**Comment by johngf** [comment]
non @Gregwar les fichier sont des m3u8 pour ip normal fr

**Comment by johngf** [comment]
apres le site est nouveau est bug parfois

**Comment by Gregwar** [comment]
@johngf regarde dans la source de la page d'un film tu as un truc du genre:

```
[{file:"http://svX.kaydo.ws/mp4/XXXXXXXXX.mp4"}]
```

**Comment by Gregwar** [comment]
Dans ma version j'utilise ce mp4 (la regex match ce pattern)

**Comment by johngf** [comment]
a cet endroit moi c'est le m3u8 plus haut

**Comment by LordVenom** [comment]
Nickel @johngf  manquer juste un truc dans Hoster c'est fait.

note: Les .mp4 sont les bande annonces.

**Comment by Gregwar** [comment]
@LordVenom les MP4 de la balise video sont des bandes annonces mais ceux du JS sont le film (dans le [{file:"XXXXXX.mp4"}])

**Comment by Gregwar** [comment]
Un exemple de ce que j'ai chez moi http://pastebin.com/mG6M3Vi9 
p-e ça dépend des films

**Comment by LordVenom** [comment]
Le site et HS chez moi pour le moment je regarde ça plus tard.

**Comment by johngf** [comment]
apparemment kay do remplace film stream co et hd stream in

**Comment by TmpName** [comment]
Je crois aussi, apres je sais pas si le renvois est definitif, sinon hd strea min n'est plus dans la liste des sites, il avait deja ferme avant ?

**Comment by Kodigoal** [comment]
oui et si vpn&proxy toujours ok ,  il redirige pas pour l'instant.

**Comment by Gregwar** [comment]
Toujours pareil chez moi (la Beta ne marche pas mais mon fork marche)

**Comment by LordVenom** [comment]
Tu peux test le nouvelle version

**Comment by Gregwar** [comment]
@LordVenom oui c'est parfait thx ;-)

**Comment by Gregwar** [comment]
Remarque: maintenant c'est plus r=n mais r=TkYteA==  (bon, je ne vous en voudrai pas si vous ne modifiez pas la beta à chaque fois qu'ils changent)

**Comment by TmpName** [comment]
Lol, nan mais on va trouver un autre systeme.
Y a surement moyen de recuperer le lien si il n'est pas fixe.

**Comment by Gregwar** [comment]
Oui dans l'en tête location: de hd-stream.in

**Comment by TmpName** [comment]
Ok, donc pr recuperer la bonne url, tu essayes hd-stream.in et ca te renvois sur la bne url avec la correction ?

**Comment by Gregwar** [comment]
Exactement
(C'est dans le location au niveau http)

**Comment by TmpName** [comment]
Wé mais le site hd-stream.in va surement fermer, et apres on l'aura dans l'os ?
Y a pas moyen a partir de l'adresse normale de le trouver quelque part ?

**Comment by Gregwar** [comment]
Dead à cause d'une MàJ de leur part

Fix possible, remplacer la ligne

    sPattern = '{file:"([^\"]+?)"'

Par

    sPattern = '"(http://[^"]+)",'

**Comment by johngf** [comment]
j'ai mis a jour kay do maintenant on a les 2 choix mp4 ou m3u8 a voir pour certain si c'est ok

**Comment by johngf** [comment]
bon il y a un soucis quand on a une ip mobile via 4g le site pense qu'ont passe par un vpn et nous redirige vers la page login 
par contre film streaming club le site jumeau fonctionne lui il faudrait peut etre le remettre

**Comment by TmpName** [comment]
Je viens de retester et ca ma renvoye a Hd-strm, (ainsi que kaydo)

**Comment by johngf** [comment]
Oui kaydo renvoi sur hdstream mais film stream club  pas .co avec ip 4g fonctionne alors que kaydo
Non

**Comment by TmpName** [comment]
Lol me dit pas qu'il faudrait faudrait faire passer Vstream pour un telephone pour acceder a du contenu viable ?

**Comment by johngf** [comment]
Non c'est l'inverse kaydo detecte l'ip 4g croit que c'est un vpn ou proxie et bloque @Gregwar avait fait une modif il y a lgt mais ça fonctionne plus
