### ISSUE TITLE
Free telechargement recherche

### ISSUE THREAD

**Issue by Gregwar** [Kodi-vStream/venom-xbmc-addons#785]
Les URLs utilisées ici:
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/free_telechargement_org.py#L383

Ne sont pas bonnes et font que utiliser free telechargement en recherche ne passe pas

**Comment by Gregwar** [comment]
(URL_SEARCH_MOVIES n'existe pas mais URL_SEARCH_MOVIES_SD et URL_SEARCH_MOVIES_HD existent)

**Comment by Kodigoal** [comment]
mince fausse manip.
Effectivement ya un soucis.

**Comment by TmpName** [comment]
Bon nouvelle version, cette fois sur le beta, a l'air de tourner.

**Comment by mino60** [comment]
C'est bon mais juste une remarque sur le film "favelas" qualité HD61080p le fichier existe lien uptobox
mais aucune affiche aux niveau hosters ???!!!...

**Comment by TmpName** [comment]
Je viens de faire une petite MAJ mais moi j'avais les posters, c'est juste que j'avais un peu n'importe quoi comme liens.

**Comment by mino60** [comment]
il y a toujour un probleme au niveau showhosters je crois que cette version et juste il manque quelque chause

http://pastebin.com/GjSLB1mq

**Comment by TmpName** [comment]
Mais c'est quoi le prb ?
J'avais juste un prb sur la premiere ligne.

**Comment by mino60** [comment]
Le titre lien premium n'apparait pas avec showHosters  de la dernier modif est ce que tu peux testé quelque titres ''films"?..

**Comment by TmpName** [comment]
Remit a jours, en fait je testais que les SD.

**Comment by LordVenom** [comment]
La recherche fait planter l'addon pour la recherche via tmdb ou global.

**Comment by TmpName** [comment]
C'est cinemay qui fout le dawa chez moi, je corrige de suite (si pas deja fait)

**Comment by TmpName** [comment]
Ce bug est provoque pr l'absense de
>    if not sSearch:
oGui.setEndOfDirectory()

J'ai corrige 2 sources, ca a l'air bon now.

**Comment by mino60** [comment]
Toujour problème avec la recherche essayé le film "favelas" le resultat 10 titres un seul lien premium

portant les fichiers existe sur lhébergeure uptobox

**Comment by TmpName** [comment]
Alors je fait film/recherche/favelas.
Dans la liste, je prend HD / favelas.
4 liens qui s'affichent, je prend uptobox, et le film est bon.
???
