### ISSUE TITLE
Dependencies not meet

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#786]
Bonjour ,
Alors voila j'ai un problème avec votre addon vstream avec la version frodo de kodi lorsque je l'installe ce message apparaît "Dependencies not meet" 
Merci de votre aide

**Comment by johngf** [comment]
vstream n'est plus compatible avec xbmc frodo 12 trop vieux essaye d'installé kodi 16 jarvis

**Comment by Arias800** [comment]
Bon bah j'ai réussit a le faire fonctionner sur frodo de force

**Comment by johngf** [comment]
tu as essayé ? kodi 16.1 jarvis pas le kodi 17

**Comment by Arias800** [comment]
Voulez vous que je donne la façon donc j'ai résolue le problème ?

**Comment by johngf** [comment]
tu as installé un ancien vstream ?

**Comment by Arias800** [comment]
Non j'ai copier coller mon dossier addons d'une version de kodi (16) a mon kodi frodo et ça a fonctionner (il y a juste le 1er menu qui marche pas sinon tout fonctionne

**Comment by Arias800** [comment]
oui il y a rien d’écrit sauf téléchargement ; librairie ; trakt et mise a jour disponible mais il fonctionne

**Comment by johngf** [comment]
tu as réussi ?

**Comment by Arias800** [comment]
réussit quoi ?

**Comment by johngf** [comment]
#748 essaie la manip la

**Comment by Arias800** [comment]
C'est bon ça a marcher merci beaucoup pour l'aide

**Comment by LordVenom** [comment]
C'etait pas un soucis de compatibilité mais une dépendance manquante tu aurais pus simplement installer les addons nécessaire avant l'installation de vStream et j'aurais bien aimer s'avoir quel addon manquer ca doit s'installer tout seul normalement mais bon.

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Liste-des-d%C3%A9pendances

**Comment by johngf** [comment]
deja url resolver sur n'est plus dans les dépot kodi apres une fois un gars a résolut ce problème en installant l'aadon youtube

**Comment by Arias800** [comment]
Rebonjour en ce qui concerne les dépendance  j'ai essayer de les installer les un après les autre mais pour youtube par exemple il manquait encore des dépendance donc c’était sans fin et url resolver pareil.

**Comment by TmpName** [comment]
Je viens de verifier, il n'y a pas de dependance pour urlresolver.
D'ailleurs je ne comprend pas, mais ma version de youtube n'a pas urlresolver dans les depdendances non plus ??

**Comment by Arias800** [comment]
Ça doit être un problème de la version frodo le message "dependance not meet "qui apparaît tout le temps

**Comment by Arias800** [comment]
Et youtube n'a pas urlresolver comme dependance ou alors ce n'est pas dit dans le fichier addon.xml
