### ISSUE TITLE
TV du web vstream

### ISSUE THREAD

**Issue by Fouedaster** [Kodi-vStream/venom-xbmc-addons#787]
Bonjour à tous, 

Tout d'abord un énorme merci à Venom ainsi que tous les développeurs qui y ont contribué pour cet énorme boulot abattu...
En installant le repo il y a 2 semaines tout fonctionnait très bien mais aujourd'hui il m'est impossible d'avoir une chaîne telle que canal ou bein sur TV du web (je lance et rien ne se passe). Avez vous le même souci ? Savez vous si ça sera corrigé ? Pour framapad bêta je n'arrive pas à contourner la coupure au bout de quelques secondes mais je pense que c'est pour tout le monde pareil. 

Merci pour votre aide.

**Comment by TmpName** [comment]
Il y a du y avoir une MAJ il y a 2 semaines, car c'est tres rare que cela fonctionne, trop instable.
Il y aura surement une MAJ un jour mais dans tout les cas elle ne durera pas.

**Comment by Fouedaster** [comment]
Merci, pas de chance pour le timing ! Encore merci pour votre boulot et excellente année à tous ;)

**Comment by johngf** [comment]
Oui il y a quelque chaine qui demande a changé d'adresse 
J'ai remarqué que certaine sont aussi hebergé sur dayli ou you tube en mettant cette adresse ça fonctionne
