### ISSUE TITLE
hoster a partir d'hoster

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#788]
salut c'est possible d'importer un hoster a partir du fichier d'un autre pour qu'il fasse le nécessaire pour play le lien a la place du premier hoster ?
un peu comme plugin you tube

**Comment by TmpName** [comment]
J'y ai pense pour uptostream appelle par uptobox, mais j'ai eu la flemme.
C'est faisable mais peut etre lourd pour ce que tu veux faire (c'est pour ca que j'ai lache l'affaire).
Tu veux faire quoi ?

**Comment by johngf** [comment]
Bah en faite sur'papy strea ming leur serveur a crashé et depuis ils ont changé la facon d'acceder a leur hoster (que j'appelle papylink)  du coup l'url ne play plus le lien ça passe par une appli .js qui crée le lien final puis redirection mais en faite on a un lien google drive des le debut

**Comment by TmpName** [comment]
Et c'est pas plus facile de faire la bidouille dans le fichier site ?
Apres il y a plein de prb, le premier c'est le nom de la classe "cHoster", il y a celle du fichier et celle que tu veux importer, comme ellles ont le meme nom je sais pas comment goupiller ca.
Peut etre
from resources.hosters.hoster import iHoster as cHoster2

Et apres tu te sert de cHoster2.
```
c = cHoster2()
c.setUrl(www.abc)
url, work = c.getMediaLink()
```

**Comment by johngf** [comment]
merci grace a ton aide j'ai réussi ça fonctionne 
https://github.com/johngf/divers

**Comment by spcxsat** [comment]
Salut,
yes je connais ce site il es pas mal.
on l'intergre comment dans vstream car tu pas mal de fichier sur ton lien et surtous ou les placer.
merci d'avance

**Comment by johngf** [comment]
alors celui la > https://raw.githubusercontent.com/johngf/divers/master/papystreaming_org.py
dans \plugin.video.vstream\resources\sites

celui la > https://raw.githubusercontent.com/johngf/divers/master/papylink.py
dans \plugin.video.vstream\resources\hosters

celui la il va remplacer un autre > https://raw.githubusercontent.com/johngf/divers/master/hoster.py
dans \plugin.video.vstream\resources\lib\gui

clique droit et télécharge chaque fichier

**Comment by spcxsat** [comment]
yes ca fontion pour les version en HD j'avais pas placer les deux dergnier fichier donc jFavais que ceux en SD

merci beaucoup
