### ISSUE TITLE
meta compte upto

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#789]
Bonjour à tous et bonne année 
Serait t'il possible pour voir ces fichiers sur son compte uptobox d'avoir un next page car on est bloqué à ces 25 premiers fichiers 
Merci d'avance

**Comment by Smeagold** [comment]
+1 et j'ai remarqué que si il y a un sous dossier a un dossier ça ne fonctionne pas, et si un fichier comporte un caractère spécial plus aucun fichier ne s'affiche dans le dossier. Sinon c'est prometteur! Merci pour le taf!

**Comment by johngf** [comment]
pour les é è chez moi ça fonctionne tu pourrais posté ton fichier log sur pastebin est donné le liens ici

**Comment by Smeagold** [comment]
Autant pour moi je devais surement avoir un mixe des deux .J'ai tout "formaté" dans le doute sans accent et caractère spéciaux! Merci dsl et pour la fausse info...

**Comment by johngf** [comment]
Je jetterai un oeil demain pour les sous dossiers voir aussi nextpage

**Comment by Smeagold** [comment]
Tu sais si c'est possible d'afficher l'affiche d'un film et quelques infos avec ce host? mon but étant d'avoir ma vidéothèque dans le cloud. Plus de soucis de contrainte de place...

**Comment by johngf** [comment]
Non il y a pas d'affiche sur le site

**Comment by johngf** [comment]
nextpage ok pour les fichiers ,
pour les dossiers il y a pas de nextpage apparemment j'ai été jusqu'a 102 pas de nextpage

**Comment by johngf** [comment]
pour les images "choisir l'illustration" avec la touche i ou(info) ne fonctionne pas
vstream n'a pas de fonction pour récup les images et les affiché en thumb( a moin que je l'ai pas trouvé)
pour l'instant j'y arrive en mettant une url d'image ex: http://fr.web.img3.acsta.net/pictures/16/07/26/15/53/423143.jpg
dans la description d'un dossier (pas dans la description d'un fichier!) manuellement sur le site et les image s'affiche

**Comment by Smeagold** [comment]
C'est une bonne avancé déja merci! Et pk pas c'est du boulot mais c'est plus fun à l'affichage! Ça fonctionnerai "FILMS" (Dossier principal) puis sous dossier "ACTION" (Genre) puis sous dossier "TITRE DU FILM" (avec url affiche.jpg dans description) puis fichier vidéo a lire à l'intérieur du dossier?

**Comment by johngf** [comment]
Oui possible mais ça serait mieux d'avoir les img sans devoir les ajoutés manuellement

**Comment by LordVenom** [comment]
Si tu ajoute par addMovie pour un films ou addTV pour une serie et que les meta sont activer les infos serons rechercher.

**Comment by johngf** [comment]
j'avais deja testé ça a part cGuiElement().getThumbnail() après metahandler le problème c'est qu'il faut détaillé > si plusieurs films ont le meme nom ça en prend un au hasard ou le plus connu

**Comment by LordVenom** [comment]
Tu peux ajouter l'année si tu la, oOutputParameterHandler.addParameter('sYear', sYears)

La vitesse peux être améliorer en utilisant sont api personnel d TMDB dispo dans la prochaine mise a jour.

**Comment by johngf** [comment]
comme il veut faire une bibiothéque je pense qu'il va y mettre bcp de films,avec 10 dossier metahandler je trouve ça long alors avec 50 dossier ou plus ça doit etre bien pénible

**Comment by Smeagold** [comment]
Coucou @LordVenom @johngf Merci de bosser dessus en tout cas, j'espère pas être le seul a qui ça intéresse mais quand je vois des offres payante comme ple X qui vas bientôt se synchro avec amazo N Cloud , je pense que ça peut intéressé du monde! surtout que c'est "privé" et pas de risque de suppression ou fermeture. 
Sinon en gros j'ai 20 dossiers (GENRE = Drame,Action etc) avec dedans mes films
Après si il faut adapter les dossiers ou les titres des fichiers pas de problème je m'adapte car si ça récupère les infos des films ça serait génial...

**Comment by LordVenom** [comment]
Oublie pas que ça seras en cache par la suite.

**Comment by TmpName** [comment]
Ha c'est pas con ca, utiliser le multithreading.
Mais je pensais a trakt surtout, car pour ce cas je vois plus une option "rechercher les fanart" et le mec part au taff pr retrouver le resultat en rentrant.
Meme avec le multithread, l'user va avoir une page vide (le temps que metahandler dl tout les bouzins) et la quitera de suite. Pas besoin de le faire en direct.

**Comment by johngf** [comment]
je vais testé trackt voir comment ça fonctionne vu que j'ai aussi pensé a un dialog qui chercherai des img qqpart mais apparemment c'est pas facile a faire sans fichier xml

**Comment by TmpName** [comment]
Dans le code de trakt tu trouveras aussi une fonction qui donne l ID tmdb a partir d'un nom de film. Et je crois meme qu'il y a encore celle qui donne les infos metadatas en fonction de cet ID.

Et LordVenom a meme active l'affichage des metas pour cette lib meme si ceux-ci sont desactives dans les options.

**Comment by LordVenom** [comment]
Je déconseille l'api trakt sans l'id tmdb c'est impossible et recherche l'id sur l'api tmdb puis retourner sur l'api track c'est pas rentable. 
Dans trakt ont cherche l'id TMDb uniquement pour le context ajouter à trakt puisqu'il nous faut l'id pour ajouter un film à la collection trakt.
Si tu arrive à trouver comment chercher les info en arriere plant chapeau.
Le fanart et le poster étant ceux qu'il y a de plus lourd dans la requête autant prendre toute les infos.

La solution pour forcer les meta et dans trakt la function getFolder au lieu d'utiliser addMovie ou addTv qui apelle une fonction gui.folder j'en ai creer une nouvelle ou je peux forcer les metas

**Comment by johngf** [comment]
C'est pour autre chose mais quelqu'un sait comment crée une seul liste a partir d'argument qui arrive les uns apres les autres en sortie de boucle ? Ex une boucle try: qui envoie $ a def qqchose qui crée la liste

**Comment by TmpName** [comment]
append ?

**Comment by johngf** [comment]
Liste.append fonctionne mais cree une liste pour chaque element pas trouvé la soluce c'est pour ça que j'ai posé la question ^^

**Comment by TmpName** [comment]
Ben faudrait voir la partie ou arrive les arg, c'est la ou il faudrait mettre un test pour detecter fin de la boucle.
Mais ta methode est bne.

```
list = []

arg = "je sais pas d'ou ca vient"
while arg:
    list.append(arg)
    arg = "je sais pas d'ou ca vient"

xbmc.log(list)
```

**Comment by johngf** [comment]
c'est bon trouvé

**Comment by johngf** [comment]
bon pour que les meta fonctionne que sur le site je dois mettre ça dans la boucle

` 
       for aEntry in aResult[1]:
            cConfig().updateDialog(dialog, total)
            if dialog.iscanceled():
                break
                
            sUrl = aEntry[0]
            if not sUrl.startswith('https'):
               sUrl = 'https://uptobox.com/' + sUrl
            sTitle = aEntry[1]
            
            oGuiElement = cGuiElement()#a chaque fois
            oGuiElement.setMetaAddon('true')#a chaque fois
            oGuiElement.setMeta(1) ou 2#a chaque fois
            oGuiElement.setFunction('showFile')
            oGuiElement.setTitle(aEntry[1])
            oGuiElement.setFileName(aEntry[1])

            oOutputParameterHandler = cOutputParameterHandler()
            oOutputParameterHandler.addParameter('siteUrl', sUrl)

            oGui.addFolder(oGuiElement, oOutputParameterHandler)`

**Comment by johngf** [comment]
j'ai commencé un truc avec metahandler et sous dossier apres le truc c'est de voir pour faire le tri serie film correctement
https://raw.githubusercontent.com/johngf/divers/5f08cd993ff6394da7291bd5c509d365b44b62dc/encour.py

**Comment by diouf76** [comment]
Cool si tu l'intègre dans vstream après

**Comment by TmpName** [comment]
Pour la distinction, si les titres sont bien fait, tu devrais avoir SXXEXX pour les series ?

**Comment by LordVenom** [comment]
Tu doit envoyer les type dans oOutputParameterHandler.addParameter('type', 1)

et le recuperer ensuite.

sType = oInputParameterHandler.getValue('type')

J'ai pas compris pk le showFolder a une recherche Meta?

**Comment by johngf** [comment]
Bah showfolder affiche les dossiers donc je me sers du titre du dossier que l'user va cree pour rechercher les meta pas du titre du liens pour l'instant des fois les liens n'ont meme pas de titre

**Comment by Smeagold** [comment]
@johngf En tout cas pour moi ce que tu veux... je m'adapte! Merci pour les avancées en tout cas!

**Comment by diouf76** [comment]
Yes moi aussi je m adapte, bravo les gars pour le taff.

**Comment by johngf** [comment]
bon j'ai activé metahandler il ne démarre meme pas au niveau Hoster il manque des fonctions a vstream 
donc faut un dossier avant pour qu'il démarre donc recherche meta sur les liens c'est mort

**Comment by johngf** [comment]
J'ai une question c'est faisable d'ajouter une entrée au menu clique droit depuis le fichier site ?

**Comment by Smeagold** [comment]
Super avancé ça! Moi par contre je pourrai pas m'adapter car trop trop de films sur mon compte, donc créer un dossier par film c'est ingérable mais si c'est fait au fur et à mesure pk pas... 
Merci en tout cas tu taf! ;-)

**Comment by johngf** [comment]
Les dossiers servent pour faire le tri entre film et serie sur le site il ya la fonction deplacer en bas
vais voir pour avoir les meta sur liens si c'est possible mais pareil il faudra comme meme un dossier film avec tous les film dedans et que le nom soit bien ecrit sinon n'importe quoi ou pas de résultat

**Comment by Smeagold** [comment]
Ok! Actuellement j'ai un dossier film et des sous dossiers genre (action,drame etc) et les films dans sous dossier renommé avec titredufilm.année.1080p.etc , c'est bon ou il faut pas de sous dossier? uniquement un seul dossier film?

**Comment by johngf** [comment]
C'est bon il faut que le premier dossier au debut s'appelle film c'est ce'dossier qui sert a faire le tri apres les sous dossiers ne compte pas pour le tri

**Comment by diouf76** [comment]
Ok et un dossier après pour chaque film aussi non?

**Comment by johngf** [comment]
meta sur fichier final c'est bon mais j'ai du ajouté un bout de code

**Comment by Smeagold** [comment]
Comment je récupère ta dernière version? Il suffit de le coller (https://raw.githubusercontent.com/johngf/divers/master/encour.py) dans \\site dans l'addon vstream ? Il faut activer un paramètre après?

**Comment by johngf** [comment]
copier coller dans le siteuptobox.py oui mais ça va encore changé >pas finis

**Comment by Smeagold** [comment]
@johngf Ok merci , j'attendrai t'es dernière version! Merci pour tout!

**Comment by diouf76** [comment]
Ça sera dans la prochaine maj de vstream?

**Comment by johngf** [comment]
pouvez testé celle la > https://raw.githubusercontent.com/johngf/divers/master/usine_a_Gaz.py
on peut renommer les fichier(pas les dossier pour l'instant) depuis vstream

**Comment by LordVenom** [comment]
Ya moyen d'utiliser le multithreading pour les meta ?

**Comment by TmpName** [comment]
Oui, c'est techniquement possible, mais je vois pas comment m'en servir !
Tu ouvres une page, tu t'attend a avoir les images de suite, ca sert a rien de les DL en tache de fond.
Et si c'est pour faire une recherche pour un dossier, ca peut marcher comme pour la fonction de la mediatheque de kod, tu selectionnes ton dossier, et tu laisses tourner le temps qu'il faut en afk.
Pour trakt par contre, ca permettrait d'ajouter ce que tu regardes a ta watching list, en meme temps que tu regardes la video.

**Comment by johngf** [comment]
oui j'étais entrain de faire un truc avec  j'ai deja un bout de code mais j'ai mis en pause pour le faire avec metahandler
le truc c'est que je pense il ne faut pas le mettre dans une boucle  du genre 
-for aEntry in a result sinon sa sert a rien

ce que j'ai commencé a faire c'est mettre les noms dans une liste grace au resultat du pattern

a partir de la > recherche meta en rafale en dehors de la boucle > les mettre dans une liste

reste a appliqué les metas après la boucle  ou les intégré d'une façon ou d'une autres

**Comment by Smeagold** [comment]
J'ai test usine_a_Gaz.py, c'est a copié collé dans siteuptobox.py ? ou juste dans site sur vstream? il faut activer quelque chose dans vstream pour les meta? car sinon j'ai crée un dossier Film avec 2 vidéos renommé titre et année mais aucune meta ne s'affiche. J'ai du raté un truc... Bonne soirée

**Comment by johngf** [comment]
oui c'est a cause des extensions a la fin metahandler a besoin de nom correct pas .mp4 .avi etc .... retest j'ai mis une correction

**Comment by johngf** [comment]
je viens de remarqué que la lenteur s'explique par le fait que tmdb recherche des metas avant d'envoyé la réponse
omdb( en anglais )ne cherche pas il affiche le resutat de l'url ou none c'est instantané(mais certain poster sont moche)

**Comment by LordVenom** [comment]
ombd ne recherche pas les titres en français il me semble.

**Comment by johngf** [comment]
ça depends des films http://www.omdbapi.com/?t=les+visiteurs&y=&plot=short&r=json
apres pour l'image j'ai trouvé l'astuce mais le synopsis est en anglais

**Comment by johngf** [comment]
en faite avec tmdb il faut que les noms soit écris correctement ou ça ralentit la recherche

**Comment by LordVenom** [comment]
Tu as lus mon post https://github.com/Kodi-vStream/venom-xbmc-addons/issues/804

Je sais pas comment il fait mais c'est nettement plus rapide.De toute facon faudras qu'on ce face un graber d'info methandler n'est plus sur le repo de kodi ceux qui fait buguer les nouvelles installe de vstream.

**Comment by johngf** [comment]
Oui j'ai vue mais la je continue mon code que j'avais commencé puis mis en pause avec le multi 
Pour faire plus leger qu'avec meta handler
Edit la recherche global plante toujour chez moi

**Comment by LordVenom** [comment]
Pareil sur mon pc salon ça bug mais pas sur la bêta y a un fichier qui est pas passer en mise a jour encore ça vas ce faire.

**Comment by LordVenom** [comment]
2 Solution soit créer une class metahandler soit un addon a coter gerer par notre repository je pense que ça change pas grand chose plus simple de faire une simple class.

**Comment by johngf** [comment]
j'ai commencé ça pour upto c'est vraiment un début il récup que les images, j'ai mis des annotation
https://github.com/johngf/divers/blob/master/multidebut.py

**Comment by TmpName** [comment]
Je confirme, seul tmdb fonctionne pour les films francais, il se peut que pour certains films tres connus, cela passe, mais a partir du moment ou le titre a plusieurs traductions c'est mort, je crois que j'avais teste avec "orange mecanique" entre autre.

**Comment by johngf** [comment]
Je suis tombé sur ca pour meta
https://github.com/mashedon/ProxyScraper/blob/master/service.scraper.proxy/TMDBScraper.py

**Comment by LordVenom** [comment]
Hum pas de cache pas de mutlithread le multi on peux sens passer le cache c'est vraiment pas une bonne idée.

**Comment by johngf** [comment]
J'ai essayé la fonction lock fonctionne pas  mais pas rlock qui est du meme genre je testerai ça

**Comment by LordVenom** [comment]
hum celui la et pas mal entre les 2 mon coeur balance surtout pour celui la

https://github.com/AnthonyBloomer/tmdbv3api/blob/master/tmdbv3api/__init__.py

Pk a cause de la gestion de append_to_response

https://developers.themoviedb.org/3/getting-started/append-to-response

Par contre plus de boulot car la c'est clairement pas fait pour Kodi et toujour pas de multi

**Comment by johngf** [comment]
Une petite question si qqun sait comment meta handler verifie que le poster est deja présent ? 
apres la requete et reponse de tmdb par l'url de l'image ou il compare le titre du film dans la db sqlite?
J'ai un doute

**Comment by LordVenom** [comment]
il verifie l'url dans un sql il me semble.

**Comment by TmpName** [comment]
Yep, je pense aussi, comme si c'etait un fichier sur ton DDR, si tu change une lettres dans le lien/url, il recommence a zero.

**Comment by LordVenom** [comment]
C'est un fichier sur ton ordi dans temp y a une base donner pour metahandler et pour d'autre.

**Comment by LordVenom** [comment]
Pas dans temp dsl C:\Users\''\AppData\Roaming\Kodi\userdata\addon_data\script.module.metahandler\meta_cache

**Comment by johngf** [comment]
J'avais commencé un truc qui lisait texture db et recup l'url pour la check vue qu'il n'y a pas de titre dedans
Mais c'est mieux par le titre pour evité les requete inutile peut etre sauvé les titres dans vstream db ou ailleur

**Comment by johngf** [comment]
bon pour evité d'utilisé t .join() je compare les noms de film avec ceux récup sur tmdb et ça va bcp plus vite

**Comment by diouf76** [comment]
Je voulais savoir pour profiter de tout cela va falloir que le rajoute le .py ou cela sera dans une prochaine maj de vstream?

**Comment by johngf** [comment]
Oui il faut l'ajouté soit meme par copier coller apres avoir cliqué sur le boutton raw cette version ne sera pas dans pas vtream 
J'essai d'autres choses et je ne sait pas quand ça sera finis ou pas
En attendant je ferme le sujet
