### ISSUE TITLE
Comment ajouter l'api de ALLUC? 

### ISSUE THREAD

**Issue by eSkRo32** [Kodi-vStream/venom-xbmc-addons#790]
salut a tous, désolé pour écrire ici mais je ne sais pas où demander cette question :/

Voilà, je sais que c'est possible d'ajouter l'api de ALLUC dans vstream... Mais quelqu'un peut m'indiquer où cliquer? 

Merci beaucoup bonne année à vous tous! Santé!

**Comment by johngf** [comment]
Alluc ee est deja dans vstream tu veut faire quoi au juste ?

**Comment by eSkRo32** [comment]
Bonjour et merci de vouloir m'aider. 

Quand on s'enregistre sur le site de ALLUC, 
Il nous donne un api-key qu'on peut utiliser pour avoir accès au contenu de alluc dans d'autres application. 

Il me semble que vstream a besoin de savoir qu'elle est cette api-key pour pouvoir fonctionner et donc utiliser l'option alluc_ee. 

Sinon les films ne "load" pas.

**Comment by johngf** [comment]
Pas besoin de la key Quand les films ne fonctionne pas c'est que les liens hs

**Comment by eSkRo32** [comment]
Hs?

**Comment by johngf** [comment]
Le lien a été supprimé sur le site de lhebergeur de la video le plus souvent ou l'hebergeur n'est pas pris en charge par vstream

**Comment by eSkRo32** [comment]
D'accord, merci. 
Mais, me semble que vstream ma déjà demander demander d'entrer l'api-key de ALLUC... 
Ou j'ai rêver sa? LoL

**Comment by TmpName** [comment]
Comme le dit @johngf la version d'alluc sur Vstream fonctionne sans l'api, pas besoin de t'enregistrer, quand tu trouves un lien ne fonctionnant pas, regarde sur un navigateur si il est fonctionnel ou pas.
C'est peut etre corrigeable, mais comme dit precedement, les liens sont ephemeres.

Tu dois confondre avec la cle pour trakt ?

**Comment by johngf** [comment]
Tu as révé lol c'est pas pour alluc. j'avais pensé a ajouté l'option a un moment ou il demandé de résoudre un captcha mais c'est plus le cas 
Apres certain site sont desactivé pour la recherche c'est a toi de les activés si tu veux plus de résultats

**Comment by eSkRo32** [comment]
D'accord alors, merci pour votre temps et votre aide! J'aime beaucoup vstream, si je veux aider a ma façon y-a-t-il un forum de discussion ou un site officiel pour vstream?

**Comment by johngf** [comment]
Non c'est ici que ça se passe peut toujour aider tuto,etc...

**Comment by eSkRo32** [comment]
D'accord super alors ce sera ici
