### ISSUE TITLE
Texte invisible des menus / Menu masqué / Caractères disparus

### ISSUE THREAD

**Issue by GitanHubert** [Kodi-vStream/venom-xbmc-addons#791]
Salut,

Malgré que tout est à jour, les caractères des menus Vstream sont invisibles sur Android.
Voici un aperçu (Nexus 5 sur CM13) : 
![screenshot_20170102-082241](https://cloud.githubusercontent.com/assets/24871457/21585701/0ac77dc2-d0c6-11e6-8875-cdfcc706d0e5.png)
C'est la seule extension qui rencontre ce problème.
J'ai testé sur d'autres appareils, Samsung S6 et F60 avec OS d'origine : même problème.
Sur Nexus 5 avec OS d'origine et Box TV Android : l'affichage se fait correctement.

Quelqu'un aurait une solution ?

PS : Merci pour votre travail.

**Comment by johngf** [comment]
un peu de recherche avant de posté #748

**Comment by johngf** [comment]
tu as réussi ?

**Comment by GitanHubert** [comment]
Merci pour ces liens.

J'avais cherché sans trouver car on a utilisé des mots clés différents.

Donc je vais détailler la réponse pour les prochains qui passeront ici, avec la marche à suivre :
1) Régler Kodi en Langage "French" et Région "France" dans Système / Paramètres / Apparences / Internationalisation.
2) Faites un Clear Cache Addon et XBMC dans Système / Extensions / Mes Extensions / Tout / vStream / Configurer / Outil A propos.

**Comment by johngf** [comment]
la maj du mois arrive bientot le problème sera résolu

**Comment by GitanHubert** [comment]
Cool merci
