### ISSUE TITLE
ajout de source

### ISSUE THREAD

**Issue by ajonh** [Kodi-vStream/venom-xbmc-addons#792]
bonjour , 
j'aimerai savoir comment insérer une nouvelle source , aprés avoir remplit le fichier "ajouter nouvelle source.py"

cordialement

**Comment by TmpName** [comment]
il suffit de mettre ton fichier dans le dossier "site" de Vstream, et elle va apparaitre dans "toutes les sources", a partir de la tu pourras la tester.

**Comment by ajonh** [comment]
bonjour ,
merci pour la réponse rapide.
c'est ce que j'ai fait mais elle ne s'affiche pas.

**Comment by LordVenom** [comment]
Regarde ton log si y a une erreur lors du chargement c'est un problème de code attention python et très chiant avec les espaces.

**Comment by TmpName** [comment]
Les prbs ne s'affichent pas dans les log a cause du traitement anti-erreur de Vstream (les try/except).
Moi je desactive des lignes pour afficher les erreurs, mais c'est vrai que c'est dommage.

Pour les prbs avec les espaces ou la syntaxe, le mieux c'est un editeur avec coloration syntaxique, y avait quelqu'un qui avait passer son code sur un en ligne, c'etait superbe, mais j'ai plus le lien.

Au pire passes ton code sur un lien pastebin.

**Comment by TmpName** [comment]
Je viens de trouver un truc super
http://infoheap.com/python-lint-online/

Ca donne les erreurs de syntaxes et d'ident, ca marche online.

**Comment by TmpName** [comment]
Et meilleurs voeux en passant ^^.

**Comment by LordVenom** [comment]
Ha mince je me suis encore mal exprimer dans vstream tu fait toutes les sources puis direct tu regarde ton log tu auras pas mal de ligne genre

`01:16:19 T:6276  NOTICE: 	[PLUGIN] Vstream: Load Plugin masource_org

01:16:19 T:6276  NOTICE: 	[PLUGIN] Vstream: Cant import plugin masource_org`

Si ta source est en cant import c'est un problème de codage.
