### ISSUE TITLE
Pb de lenteur avec filmstreamvk

### ISSUE THREAD

**Issue by CyrilDegout** [Kodi-vStream/venom-xbmc-addons#793]
Bonjour, 
Merci pour ce super plugin que je découvre depuis peu, j'essaye de regarder la série Walking Dead en FR via filmstreamvk mais je rencontre des lenteurs en utilisant vstream.
Hier il y avait un chargement de 10-15 secondes toutes les 12-20 secondes donc pas regardable, je suis alors passé en direct sur le PC et je pouvais déjà mieux regarder (même si certains lenteurs arrivaient toutes les 10 minutes, ce qui est mieux tout de même)

Je viens de refaire le test ce soir et via le site en direct sur mon PC aucun pb de lenteur ce soir, et sur le kodi via Vstream j'ai eu une mise en cache au bout de 2 minutes 30.

Est-ce qu'il y a un tuning Kodi ou Vstream qui pourrait m'aider à bufferiser mieux ou plus souvent ?
Est-ce que d'autres ont rencontré cette lenteur ?
Est-ce que vous avez une autre source à me conseiller pour la VF de Walking dead à partir de la saison 4 ?

Contexte 
Kodi (Jarvis) sur RPi 2
vStream en dernière version officielle à priori (mise à jour auto activée)
Je suis en WiFi (mais sur le PC aussi et j'ai pas ce pb là)
Vidéo testée Walking dead S04E11 et S04E13 via netu sur la source filmstreamvk

Merci d'avance et bonne année 2017 !

**Comment by LordVenom** [comment]
Bonsoir,

J'ai tester et chez moi en wifi dans la pièce du fond pas de chargement.
Le soucis c'est qu'il peux y avoir tellement de raison.

Je vais pas tous énuméré la, mais j’opterais pour ton RPi qui n'a pas assez de cache. Voir si quelqu'un ici a ce genre de matériel.

**Comment by johngf** [comment]
j'ai eu la meme chose avec netu sa na rien a voir avec film stre am vk c'est les servers de netu qui sont surchargés ont ne peut rien y faire a part essayé de regardé (hors heure de pointe le soir ou le lendemain) ou sur une autre source
"Est-ce que vous avez une autre source à me conseiller " > fonction recherche >WD
dans les parametres de vstream certain site sont desactivé pour la recherche c'est a toi de les activés si tu veux plus de résultats

**Comment by TmpName** [comment]
Essayes voirfilm, il y a une tres grande quantitee d hebergeurs, de qualitee variables.

**Comment by CyrilDegout** [comment]
Merci pour vos conseils je vais essayer ça.

J'ai testé hier soir et j'ai eu 3 coupures sur un épisode et une dizaine sur l'autre.
Dans le cas de filmstreamvk l'autre hébergeur est openload et il me dit fichier introuvable.
Et les autres sources testées 4 pour le moment ne donnent rien en listing de visualisation ou fichier introuvable également.

**Comment by TmpName** [comment]
Je viens de tester voirfilm, walking dead S4E13
Youwtch ok
Uptostream ok
allvid ok

Et j'ai arrette la.

**Comment by CyrilDegout** [comment]
Je vais comparer les sources et réessayer et choisir celui qui convient à mes envies.
Merci de vos réponses en tout cas.
