### ISSUE TITLE
HD-stream.in mort ?

### ISSUE THREAD

**Issue by Ronaldonizuka** [Kodi-vStream/venom-xbmc-addons#794]
Bonsoir à tous, 
Bonne année et bonne santé à tous ! 
Encore merci pour tout le travail que vous fournissez et les nouvelles sources de plus en plus nombreuses. 
Cela fait quelque jour que j'ai remarqué que la source HD-stream.in était morte, je voulais savoirs si cétait pareil pour tout le monde et si elle allait revenir un jour :D, en effet c'est la seul qui propose quasi systématiquement un choix entre HD et SD et qui a des films plus ou moins rares, du style : l'inspecteur se met à table de hitchcock que l'on ne retrouve sur aucune autre source.
Merci d'avance pour votre réponse et encore merci pour tout.

**Comment by LordVenom** [comment]
Bonsoir et bonne année.

Oui Hd-stream et mort mais y a un remplacent qui seras dispo dans la prochaine mise a jour.

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/784
