### ISSUE TITLE
series_en_streaming_tv HS

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#796]
Le site a changer de style

Perso je bloque sur le showHosters. 

http://pastebin.com/S0QrquEL

**Comment by TmpName** [comment]
Nouvelle version 
http://pastebin.com/4UgSzv8p

A finir:
Virer la protection Cloudflare qui ne sert plus.
Showmovie ne marche que pour la recherche.
La mise en page.
Virer toutes mes lignes de debug (xbmc.log, write, ect ...)

Dois me sauver, pas pu finir.

**Comment by LordVenom** [comment]
Merci j'ai pus finir :+1:
