### ISSUE TITLE
jaquette et uptobox

### ISSUE THREAD

**Issue by diouf76** [Kodi-vStream/venom-xbmc-addons#798]
bonjour, est il possible d avoir la jaquette des films quand on va sur nos fichiers uptobox?

Merci par avance de votre réponse.

**Comment by johngf** [comment]
Ici #789

**Comment by johngf** [comment]
Et pour que ça fonctionne faudra crée un dossier au nom du film sur le site avec un film a l'interieur

**Comment by diouf76** [comment]
ok pas besoin de rajouter l url de l image comme expliquer dans le post?
