### ISSUE TITLE
VSTREAM Echec de lecture d'un ou plusieurs fichiers.

### ISSUE THREAD

**Issue by KevinTahiti** [Kodi-vStream/venom-xbmc-addons#799]
Bonjour tout le monde, je rencontre le problème indiquez dans le titre. En effet, tous les liens (youwatch, openload, exshare) que je lis ne fontionne pas et me donne cette erreur sauf pour le lien de "net.ru".
S'il vous plait aider moi cela fait plusieur jours que cherche une solution a mon problème un peut partout sans rien trouvé.

**Comment by TmpName** [comment]
Verifis sur un navigteur, pour voir si
1 - le lien est valide.
2 - ta configuration permet l'acces au lien.

**Comment by KevinTahiti** [comment]
Comment puis-je copier le lien ou voire le lien ? sachant que je suis sur smartphone android.

**Comment by TmpName** [comment]
Tu vas sur le site internet du meme nom que sur Vstream, meme video. Si il y a un navigateur sur ton systeme ?

**Comment by KevinTahiti** [comment]
Désoler du retard, alors voila j'ai tester avec le film S.O.S Fantôme sur le sur le site site STREAMVK sur le navigateur "Net.ru", "openload" fontionne et exshare non. Mais sur Kodi openload et exshare ne fontionne pas

**Comment by TmpName** [comment]
Chez moi pareil, a part que openload fct aussi sur kodi.
Essayes le site voirfilm, il y a plus d hebergeurs possibles, si flashX ne fct pas non plus, c'est que tes fichiers ne sont surement pas a jours.
Tu as deja clique sur l'icone "Mise a jour dispo" dans l'acceuil de Vstream (il y a moins de 4 jours) ?

Venom a fait une MAJ complete de Vstream aujourdhui, tu ne l'as surement pas encore chez toi, mais tu peux forcer la MAJ dans les parametres de kodi (extensions/menu deroulant de gauche).

**Comment by KevinTahiti** [comment]
Je vient de tester le site voirfilm et aucun herbergeur ne fontionne a part "Net.ru" et sa peut importe le film que je lis. Et j'ai 0.4.7 de VSTREAM et je suis de Tahiti.

**Comment by KevinTahiti** [comment]
Ah réctification, je vient de mettre à jour mais sa na rien réglè a mon problème et j'ai oublier aussi de préciser que peut importe les sites aussi il n'y a que Net.ru qui fonctionne je peut te fournire mon log si vous voulez.

**Comment by TmpName** [comment]
Yep, je veux bien le log (sur pastebin ou autre) car avec les derniers fichiers pas normal que tu ais autant d'erreurs.

**Comment by Morraax** [comment]
Alors moi aussi impossible de faire fonctionner un film une serie ou autre alors qu'hier ça fonctionnait bien. J'ai essayé sur mon galaxy s6, mon ipad air 2, mon mac et mon pc plus possible ..

**Comment by Morraax** [comment]
Il n'ya que net.ru qui fonctionne aussi

**Comment by Morraax** [comment]
Netu pardon desole pour les 3 post

**Comment by TmpName** [comment]
La je suis en train de corriger Openload, mais sur voirfilm, il y a 8/10 hebergeurs proposes, c'est pas normal que tous soit HS.

**Comment by TmpName** [comment]
Openload mit a jours.

**Comment by edvede** [comment]
Bonjour a tous.j utilise vstream sur différentes plateformes (windows et raspberry)
j arrive a forcer la mise a jour sur windows en avançant l heure du système de trois jours, dans ce cas il me remonte la mise a jour mais pour le raspberry pas moyen de changer l heure manuellement (osmc + kodi) , faut il attendre trois jours avant que la mise a jour remonte?
Merci a vous .

**Comment by TmpName** [comment]
Oui, mais ma derniere mise a jour ne t'apportera que openload, il y a eu une MAJ complete (nouvelle version de Vstream) ce Week End.
Tu peux aussi editer toi meme le fichier, nouvelle version ici https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/hosters/openload.py

**Comment by KevinTahiti** [comment]
[Log Kodi.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/692339/Log.Kodi.txt)

Voilà mon log que j'ai fait aujourd'hui meme..

**Comment by edvede** [comment]
Oui effectivement j'ai effectue la mise a jour de vstream ce weekend par contre quand je copie le contenu de ton fichier et le colle dans un nouveau fichier openload.py ,ca ne fonctionne pas sur les hoster openload (erreur) . par contre sur windows ton fichier fonctionne très bien en mise a jour automatique.j espère me faire comprendre et merci pour tout
Désolé en code je n y connais rien je ne pourrais pas vous aider la dessus.

**Comment by edvede** [comment]
ah Pardon j avais pas vu ton dernier post desole je test de suite...

**Comment by KevinTahiti** [comment]
Tu pourrais m'expliquez comment fait on pour forcer sois même l'installation S'il te plait. Je m’excuse j'y vraiment rien.

PS: mon log je c'est l'afficher directement sur le site comme vous le faite.

**Comment by johngf** [comment]
@KevinTahiti pour ton log regarde la 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil

**Comment by KevinTahiti** [comment]
[file:///C:/Users/Rauarii/Desktop/kodi.log](url) 

merci johngf

**Comment by KevinTahiti** [comment]
Merci johngf, et Pour forcer la MAJ sois même j'aimerai bien aussi apprendre car lorsque chercher une solution mon problème j'ai lus plein post qui disait que tu pouvait toi même changer les fichier openload.py ou bien de youwatch.py. Mais j'ai chercher des tutoriels mais rien trouvé.

**Comment by TmpName** [comment]
J'ai regarde vite fait le log, je regarderais mieux demain.
Mais pr flashX, le lien etait HS.
Pour openload ( a essayer avec la nouvelle version)
Pour Youwatch, ca aurait du marcher, tu as mit combien en timeout ? le temps que ta machine essaye de charger la video ? Quand tout est bloque.

**Comment by KevinTahiti** [comment]
ok d'accord j'attendrait demain de t'es nouvelles. Et pour le TIMEOUT "10" BUFFERMODE"1" REDBUFFERFACTOR"1.5" CACHEMEMBUFFERSIZE"104857600" voila ma config samsung galaxy s7 edge
Sincèrement merci à vous de m'aider et demain alors.

**Comment by johngf** [comment]
Timeout trop petit a mon avis essaie 30s ou plus

**Comment by KevinTahiti** [comment]
D'accord merci johngf. :)

**Comment by TmpName** [comment]
Yep en fait quand tu lances une video, kodi se met en idle (tout bloque et un petit rond se met a tourner en bas) puis ca t'affiche un message d'erreur.
Si ce temps d'attente est plus petit que 30s ca explique tout, youwatch peut mettre jusrqu'a 1mn pr lancer la video aux heures pleines.

**Comment by KevinTahiti** [comment]
Alors comme débit internet j'ai du 4 méga, pour le TIMEOUT j'ai corriger hier avec Easy Advance Setting (dit si c'est bien se timeout) j'ai 40 puis 60 alors youwatch fonctionne 1 fois puis quand j'éssaye de relancer éxactement le même film "erreur". Est ce mon débit est suffisant ou mon timeout est trop cours pour résoudre mon problème et avoire un streaming confortable... S'il te plait...

**Comment by TmpName** [comment]
Prend juste une montre et comptes, si ca met moins de 30s (avec un reglage a 30s) y a un soucis sur tes reglages, si c'est ca je te dirais comment je fais en modifiant le fichier advancedsetting.xml.

Apres les serveurs sont caricieux (surtout youwatch) c'est frequent que apres une demande, il te bloque la seconde si faite trop rapidement.

Mais si ca remarche pour youwatch (et c'est bon signe, car ca doit etre le pire pr le timeout) , retestes plusieurs serveurs sur voirfilm.

**Comment by KevinTahiti** [comment]
Me re voilà je vient de mesurer le timeout, Sa varie sa ne respecte pas les 40 seconde demander  avnt de me faire une erreur sa dépend des hébergeurs. cela peut être préférable que je régle a ta façon si sa te dérange pas de m'expliquer comme sa je suis que sa ne vient pas du timeout.

**Comment by TmpName** [comment]
Jette un oeuil dedans, aide ici http://kodi.wiki/view/advancedsettings.xml partie 2.8.3 network.

Moi j'utilise
```
      <network>
<!--     <buffermode>1</buffermode>
         <cachemembuffersize>52428800</cachemembuffersize>
         <readbufferfactor>10.0</readbufferfactor> -->
         <curlclienttimeout>60</curlclienttimeout>
         <curllowspeedtime>60</curllowspeedtime>
         <!--<curlretries>2</curlretries>-->
         <disableipv6>true</disableipv6>
      </network>
```

Sachant qu'il y a du code desactive, c'est juste un c/c.

**Comment by KevinTahiti** [comment]
D'accord, Merci TmpName, j'installe cette config je regarde un peut se que tu ma donner puis je te fait un résumer demain de se que sa donner avec cette config Merci beaucoup TmpName et à demain.

**Comment by Morraax** [comment]
moi ça commence clairement à me saouler ça marchait très bien il y'a 3jours mais là plus rien ça m'énerve tellement

**Comment by LordVenom** [comment]
@Morraax : Hum soyons clair ici c'est pas un forum 14-18 ans c'est un github une plateforme de codage commune, ont parle de code et ont travail tous ensembles sur un projet. Alors soit tu nous aide a t'aider c'est a dire que tu fait quelque recherche de ton coter pour solutionner le bug et partager tes avancer soit tu t'en vas.

**Comment by Morraax** [comment]
Soyons clair Venom. Je suis pas un petit crois pas j'ai 14-18 ans ou je ne sais quoi je fais mes recherches de mon côté j'ai réussi à me débrouiller tout seul pendant un moment j'ai fait mes affaires avec kodi. Maintenant, tu prends tes airs je ne sais pourquoi alors que je me plains juste, à un moment donné faut comprendre je me plains pas à vous mais au fait que ça ne fonctionne plus car c'est juste relou j'attaque personne mdr. Et comme je l'ai dit au dessus j'ai fait mes recherches j'ai essayé pleins de choses sur mes 4 appareils où j'ai installé kodi mais rien n'y fait.


Sur ce, j'ai une question sachant que kodi je connais pas depuis super longtemps j'ai vu qu'on pouvait ajouter des sources de sites pour v stream pour avoir plus de contenu au niveau séries films etc mais je sais pas comment on fait tu pourrais m'expliquer stp merci

**Comment by LordVenom** [comment]
pfff je suis fatiguer moi...

J'ai fait toutes une belle tirade pour t'expliquer que **l'on ne ce plaint pas d'un logiciel open source, ont y participe**, mais les grand air la tu ma tuer, y a plus rien à répondre la.

**Comment by KevinTahiti** [comment]
Ne tinquiet pas LordVenom vous faite du bon travail, rapide et éfficace il faut juste un peut de travail de notre côter, en plus il est open source on peut le travailler comme ont le souhaite. En tout les cas, moi malgré mon problème (car je sais dans un future tous se réglera) je suis satisfait et je félicite votre équipes

**Comment by TmpName** [comment]
Si ca marchait avant, c'est pas normal que ca deconne sur 4 machines d'un coup, tu as un routeur/proxy ou vpn ?
A chaque NOUVELLE instal ca propose une mise a jour des sources, pas apres une reinstall (a moins de supprimer toi meme les fichiers), mais vu que la derniere version date de meme pas une semaine, il y a pas grand chose de plus en mise a jour ponctuelle.
Il y a plus de chance que le prb vienne de ton cote (software ou hardware) que de Vstream.

Sinon pour rajouter des sources https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-creer-sa-propre-source.

**Comment by Morraax** [comment]
Bon, du coup j'ai taffé de mon côté ça a remarché mais à certains moments quand je cherche une série il trouvé rien ou quoi du coup c'est bizarre alors que ça marchait. j'ai une question est ce que c'est normal quand j'ai fait la mise à jour 0.4.8 il demande des trucs premium!? 
Non, je n'avais pas routeur ou vpn ou quoi....

Aussi il y a 3 jours aussi je pouvais lire kodi sur mon chromecast du coup je regardais sur la télé et maintenant impossible je comprends pas pq.. y'a pleins de problèmes qui se sont enchaînés alors que j'ai touché à rien. 

Et merci pour le lien pour les sources

**Comment by TmpName** [comment]
Il demande des trucs premium ?
Il y a tjours des options pr les premiums, mais par defaut il ne demande jamais.

**Comment by Morraax** [comment]
oui par exemple avant je regardais la série vikings sur openload ça marchait nickel (ajd ça marche plus) mais j'ai fait la mise à jour 0.4.8 ça me dit attention .... premium et je peux pas lire

**Comment by TmpName** [comment]
Sur openload ?
Pas normal, tu as le film et le site stp ?

**Comment by Morraax** [comment]
j'ai remit le vstream en 0.4.7 j'ai plus le problème avec la fenêtre qui s'ouvrait pour le premium.. 

et sinon est ce que vous pensez qu'un jour on pourra mettre vstream sur le chromecast pour regarder sur la télé ??

ça a été mis à jour mais ça fonctionne pas du tout chez moi

**Comment by johngf** [comment]
une fenêtre premium pour quoi ?

**Comment by TmpName** [comment]
J'ai jamais essaye mais apparement c'est possible, j'ai vu plein de tuto sur google, mais sur que ce soit pr la derniere version non plus.

**Comment by Morraax** [comment]
ah je vous aime je viens d'avoir la mise à jour pour openload ça refonctionne bien comme avant merci bcp force à vous

**Comment by alfred5959** [comment]
@Morraax, plutôt que la chromecast, je te conseille une box android, plus confortable je pense. Pour environ 40E tu pourras installer Kodi ou toute autre application android. Peut être que tu connaissais, mais ce serait dommage de passer à côté. Bon week-end à tous

**Comment by Morraax** [comment]
Ah je connaissais pas du tout les box android car moi j'ai acheté le chromecast mais comme je vais vendre mon galaxy s6 je pourrai plus mettre avec l'ipad alors je pense je vais me prendre une box comme t'as dit merci pour l'idée

**Comment by edvede** [comment]
Salut a tous et encore merci pour votre travail...chapeau bas.
Depuis hier j'ai constate que la plupart des liéns ne s ouvraien pas (erreur de fichiers) puis en modifiant mon adresse ip (en utilisant un routeur 4G) les liens se remettaient a s ouvrir...
Pouvez vous me dire si il y a une limite par adresse ip sachant que j utilise une ip publique fixe ?

Merci

**Comment by TmpName** [comment]
Ce n'est pas nos qui bloquont les IPs, mais si c'est une ip tres utilisée, c'est un peu normal qu'elle soit bloquée.

**Comment by edvede** [comment]
Un ou deux films par semaine ca fait beaucoup ? et sinon techniquement sur differents sites c est possibles qu ils bloquent ? Du coup je comprends pas trop a quel niveau ca peut bloquer ?
Merci én tout cas.

**Comment by TmpName** [comment]
C'est quoi que tu appelles une IP publique ? Pour moi c'est quand tu te connectes via un truc tout public, style un macdo, une gare, ...
Apres les hebergeurs bloquent eux-meme certaines IP, j'ai plein d'outils en ligne qui ne marchent pas sur cloudflare car bloque chez eux, donc tout les sites qui passent par cet hebergeur reagissent pareil.

**Comment by edvede** [comment]
ok c est bien de mon ip vu de l exterieur (ip fixe orange fibre)dont je parle...et oui je reside en france
Merci de t² reponse je vais voir pourquoi ca fonctionne des que je passe par un autre routeur en utilisant le meme appareil au meme moment ??
j ai meme ch²nger le dns sans succes donc le pb vient d ailleurs...(orange peut etre)

pour info je uis fibre chez orange (ou ca bloque parfois) et modem 4G chez bouygue (fonctionne).

**Comment by TmpName** [comment]
Ha wi les dns, pas bete, j'y ai pas pense. Si tu passes par un navigateur, les memes sites deconnent ?
Car la je vois pas pkoi le site bloquerait une ip orange et pas bouygue.

**Comment by edvede** [comment]
Bon j ai plus de probleme aujourdhui mais le mystere rzste present.
j avais teste le dns google 8.8.8.8 sans succes mais le test sera pas possible avec un autre....
Faut attendre que ca bloque a nouveau.Je vous tiens au jus et merci Tmpname.

**Comment by katsuhara80** [comment]
Bonjour, depuis plusieurs semaines le script netu.py ne fonctionne plus chez moi avec l'erreur cité dans le sujet du post.
Après vérification des log j'ai une erreur type " Vstream Erreur: Fichier introuvable " ou dans un navigateur web "HTTP 404 ERROR" avec par exemple le l'url ci-dessous:
https://hqq.tv/player/embed_player.php?vid=234259265223261258278257269237210227194271217261258&autoplay=no

J'ai bien essayé de modifier le script netu.py pour ne plus utiliser le lien https://hqq.tv/player/embed_player.php?vid= mais plutôt https://hqq.tv/watch_video.php?v= testé dans un navigateur web avec l'exemple:
https://hqq.tv/watch_video.php?v=234259265223261258278257269237210227194271217261258&autoplay=no
Mais sans succès, "vstream" ne prend pas en compte mes modifications même après un redémarrage, réinstallation ou nouvelle installation avec le script netu.py modifié.

Pourriez-vous m'aider à corriger ce bug ?
Merci

**Comment by TmpName** [comment]
Netu est out, je suis dessus.

**Comment by TmpName** [comment]
Netu remit a jours.

**Comment by katsuhara80** [comment]
Merci pour votre travail !

**Comment by TmpName** [comment]
Et netu , reremit a jours.
