### ISSUE TITLE
[Source] Z-T.ws meilleur que .eu 

### ISSUE THREAD

**Issue by lebigboss59** [Kodi-vStream/venom-xbmc-addons#800]
Salut à tous 
J'aimerais savoir pourquoi avoir mis la source Z-T.eu alors que la .ws est la meilleur réplique de l'original ?

**Comment by johngf** [comment]
#720  tu étais sur cette discussion en plus ... (copie et recaptcha)

**Comment by TmpName** [comment]
Et rien comme video dessus.

**Comment by lebigboss59** [comment]
@johngf  je sais plus mais le site a du changer entre temps puisque ça n'est plus du recaptcha
![capture](https://cloud.githubusercontent.com/assets/24246566/21742539/56b5a798-d4f1-11e6-8e04-e87333fc6c47.PNG)

**Comment by chataigne73** [comment]
j'ai jeté un coup d'oeil, mais ça semble toujours être du recaptcha, même si c'est un simple slider.
en tous cas moi je ne trouve pas comment obtenir la qaptcha_key à envoyer dans la requete POST

**Comment by chataigne73** [comment]
bon apparemment c'est du JQuery Qaptcha et cela semble facilement contournable
je suis par ex tombé sur ça : http://stackoverflow.com/questions/10609201/qaptcha-is-it-effective

**Comment by TmpName** [comment]
Mais le site est naze, y a rien dessus, il profitent juste de la renommee du precedent.
Te prend pas la tete avec ce site.

**Comment by sebi0606** [comment]
Bonjour à tous je suis pas d'accord avec toi TmpName beaucoup de film en HDLight et des nouveautés le site est mis à jour tous les jours il serait intéressant de l'intégrer à vstream
Merci d'avance

**Comment by chataigne73** [comment]
J'ai presque fini, je le posterai demain

**Comment by chataigne73** [comment]
mis sur la beta

**Comment by sebi0606** [comment]
Merci @chataigne73
