### ISSUE TITLE
Alldebrid bug sur Vstream

### ISSUE THREAD

**Issue by lebigboss59** [Kodi-vStream/venom-xbmc-addons#803]
Salut à tous
Chez moi Alldebrid me débride les liens 1080p sois en 540p ou sois pas du tout.
Si quelqu'un sait quoi faire.
Sur les sources
Rapidgator
1fichier
Uploaded
Uptobox
Turbobit

**Comment by TmpName** [comment]
La je sais pas si ton probleme concerne alldebrid ou l'urlresolver, mais dans tout les cas ce n'est pas nous qui geront cette partie.
On recupere le lien, on l'envoit a l'urlresolver qui le passe a alldebrid et qui nous revoit un nouveau lien.
Regarde si ce n'est pas le site qui met une fausse indiquation 1080p, en essayant via un navigateur.
Ou si ce n'est pas alldebrid qui bride, en passant directement par leur site.
