### ISSUE TITLE
MultiThread

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#804]
J'ai trouver un exemple mais moi je comprend rien et je voie pas comment l'utiliser mais en suivant le code il utilise bien metahandler avec le multithread donc pour les acharner de temps en temps j'y gete un oeil et fait des test ça finiras par payer au pire.

https://github.com/Seko34/Kodi-Development/blob/master/script.module.seko.scraper/lib/scraperModule/__init__.py

**Comment by LordVenom** [comment]
Bon j'ai commencer un fichier perso de meta pour vStream pour le moment rien ne fonctionne je met le fichier quand même histoire de le sauvegarder et de travailler ensemble dessus voir lib/tmdb.py

**Comment by johngf** [comment]
en faite je viens de remarqué que meme avec les requetes en multithreading
kodi utilise les images thumb et fanart qu'il a dans son cache texture.db 
bcp plus rapide que metahandlers d'ailleurs la dernière fois j'ai demandé si il envoyé les requetes ou se servait du nom et enfaite de ce que j'ai compris en regardant le code
il envoie la requete puis essaie d'ecrire les infos dans ça db si il n'y arrive pas c'est que ça existe déja 
donc il prend les infos de la ça db

**Comment by LordVenom** [comment]
Pero j'ai stop le fichier tmdb j'arrive a rien avec le multi je tente toujours de l'appliquer a metahandler une foix réussis je reprendrais le code de tmdb.py

Le plus long c'est l'attente des url de tmdb c'est ça qu'il faut multi.

**Comment by johngf** [comment]
Le multi est utile par liste d'url il ne faut pas qu'il cherche pour chaque film dans une boucle car au final c'est pas du multi ça
Moi la j'envoie a tmdb 15 a 20 film a cherché en meme temps ça va super vite
Je suis encore dessus .

**Comment by LordVenom** [comment]
Perso je test dans guielement et j'init donc chaque lien et envoye au meta et un thread mais j'arrive pas a bloquer l'attente de la réponse. Hate de voir ton code.

**Comment by johngf** [comment]
il y a une fonction qui permet d'avoir accès a toutes les options de vue niveau hoster avec oGui.addHost ?
comme sur oGui.addmovie ou c'est pas possible(je n'ai pas trouvé) on a que 4 mode dispo niveau hoster a chaque fois

**Comment by LordVenom** [comment]
Enfaite j'ai declarer cGui.CONTENT à files par defaut dans gui.py puis je modifie a la voler si c'est une serie un film.

`ligne 573 de gui xbmcplugin.setContent(iHandler, cGui.CONTENT)`

Donc en ajoutans  cGui.CONTENT = "movies" dans la fonction gui.addhost ça devrais fonctionner.Mais vue que les metas sont rarement la boff.

Variable possible pour content

`files, songs, artists, albums, movies, tvshows, episodes, musicvideos`

**Comment by johngf** [comment]
comme ça demande a etre optimisé juste un exemple pour remettre tout en ordre https://github.com/johngf/divers/blob/master/multi_t.py

**Comment by LordVenom** [comment]
J'ai avancer tmdb et je l'ais activé par défaut sur la bêta n'hésiter pas à activer les métas pour tester y a encore pas mal de taff, les seasons ne sont pas gérer mais il l’était déjà pas avant.
