### ISSUE TITLE
Recherche type

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#805]
Alors impossible de faire fonctionne la recherche dll_island ça passe par les type mais les type passer par outpout ne fonctionne pas avec la recherche global donc grosse modif.

@TmpName  j'espere que j'ai pas oublie un truc sur les types et que j'ai pas tuer ton code

Pour la recherche global

sType = xbmcgui.Window(10101).getProperty('search_type')

réponse film|serie|anime.

**Comment by TmpName** [comment]
C'est bizarre que tu es des prb pr ce site.
Il y en a plein qui marchait sans prb mais qui du coup ne marcheront plus.
cf freetelechargment , fullstreamorg, ect ...

A l'epoque de sa mise en place, ca tournait via output.

**Comment by LordVenom** [comment]
Non le soucis vener de la recherche via la popup film,serieect.. via tmdb. y a pas de réponse pour tous c'est site bizard qu'on les jamais remarquer.

**Comment by TmpName** [comment]
C'est juste parce que themoviedb.py ne gere pas (plus) le type, c'est moi qui ait fait le con
cf https://github.com/Kodi-vStream/venom-xbmc-addons/commit/d73f662a49770d740da43866fe521f56564d4ee5 (me demande pas pkoi ...)

Faut juste remettre les lignes, et on obtient
`{'function': 'showHosters', 'sMovieTitle': 'The%20Strain', 'siteUrl': 'The%20Strain%7c%20S03E04', 'sTmdbId': '47640', 'title': '%5bCOLOR%20coral%5dS3E4%5b%2fCOLOR%5d%20-%20Episode%204', 'site': 'themoviedb_org', 'sEpisode': '4', 'sThumbnail': 'https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw396%2f4kGvO4djTl6gdZCutxKjYR2p9ui.jpg', 'sSeason': '3', 'type': 'serie'} `

D'ailleurs autre bug possibles,  il y a des decos dans Title, et Smovietitle n'a pas la saisons et l'episode.

**Comment by LordVenom** [comment]
Quoi humm ok ça fonctionne mais c'est pas logique. Pourquoi les catégories aurais un type.

La fenêtre de sélection s'ouvre je choisis ma recherche et ça me retourne le type préférere de la recherche.

**Comment by TmpName** [comment]
Ha oui, mince tu as raisons, ca affiche un choix de moteur de recherche, et pour chaque choix il y a un type a preferer (regle dans les parametres) c'est surement pour ca que je l'avais vire alors, mais franchement je me souvient plus.

En tout cas, c'est vrai, le choix de le fenetre de selection doit etre preponderant.

**Comment by LordVenom** [comment]
J'ai remis comme c'etait avec la correction pour tmdb pour le moment ça tourne comme ça et sa évite de refaire les sites mais faudras y penser.
