### ISSUE TITLE
pb kepliz

### ISSUE THREAD

**Issue by raslittle** [Kodi-vStream/venom-xbmc-addons#808]
Bjr, depuis quelques jours j'ai Kepliz qui ne marche plus.
un problème sur le site ou ça déconne chez moi?

**Comment by LordVenom** [comment]
Leur serveur met trop de temps a répondre. Pas de solution pour le moment dsl.

**Comment by raslittle** [comment]
ok merci, je pensais que ça venait de chez moi, je suis rassuré.
