### ISSUE TITLE
Vstream ne trouve plus rien :/

### ISSUE THREAD

**Issue by eSkRo32** [Kodi-vStream/venom-xbmc-addons#809]
Bonjour, je suis sur la v0.48 et tout est à jour. 
Mais a présent, vstream ne trouve plus rien.. 

Il n'y a que KAYDO.WS (beta) qui apparaît dans les résultats de recherche normal et visuel.. 

Et ce sur n'importe quel filme.. 

Que faire? Merci!

**Comment by johngf** [comment]
#622 il faut attendre la maj ou désactivé strea mase  dans les parametres de  vstream en attendant
si ça continue désactive tous les sites de couleur rose

**Comment by eSkRo32** [comment]
D'accord j'attendrai la majoration.. Merci!

**Comment by jackouille2** [comment]
bonjour,
juste pour info et si ça peut aider, j'ai le même soucis

**Comment by johngf** [comment]
le soucis est résolu @jackouille2  ta version n'est pas a jour il faut attendre la maj
