### ISSUE TITLE
Kaydo comment ca fonctionne

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#810]
Bonjour tout le monde,

Je viens de faire la mise jour 0.4.8 et je vois qu'il y a des nouveautés donc Kaydo mais voilà comment ca fonctionne?

Merci pour le boulot que vous faites pour l'add-on

**Comment by johngf** [comment]
kaydo remplace c'est hd stream in film sream co "comment ça fonctionne" tu veux dire quoi par la ?

**Comment by patoche2025** [comment]
Ah ok en faite quand je vais sur le site il demande un login et un mot de passe. Quand je vais sur la source par vstream et que je fais une recherche rien ne s'affiche

**Comment by johngf** [comment]
la recherche global déconne #809 recherche sur le site lui meme a partir de sources

**Comment by patoche2025** [comment]
Ok @johngf, moi ca marche pas bizarre lol

**Comment by LordVenom** [comment]
@patoche2025  tu as une ip étrangère ? si oui test en passant par un vpn

**Comment by TmpName** [comment]
Le nouveau site kaydo est en court de creation, pour le moment le owner du site filtre les IPs.
