### ISSUE TITLE
MaReplayTv hs

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#812]

**Comment by johngf** [comment]
pas chez moi

**Comment by LordVenom** [comment]
Je t'assure ce regex et mort <a href="(.+?tape=[0-9]+)">([0-9]+)<\/a> un espace invisible ou un truc a la ... que j'arrive pas a trouver.

**Comment by LordVenom** [comment]
https://regex101.com/r/Z2A4b1/1

**Comment by johngf** [comment]
`<a href="([^"<>]+)\/\?tape=(\d+)">(\d+)</a>` celui la ?

**Comment by LordVenom** [comment]
Y a trois groupe mais c'est ça oui

**Comment by johngf** [comment]
`<a href="([^"<]+)\/\?tape=.+?">(\d+)</a>` celui la 2 groupe

**Comment by LordVenom** [comment]
j'avais tester ça pfffff

**Comment by johngf** [comment]
il faut toujour ignoré les ? avec un \? apparemment

**Comment by LordVenom** [comment]
<a href="(?:.(?!</a>))*tape=[0-9]+">([0-9]+)</a>

truc de fous par un membre

**Comment by LordVenom** [comment]
Bonne réponse <a href="([^"<]+tape=.+?)">(\d+)</a> il faut le tape dans l'url

Note il ont un nouvelle Host : Estreamto a voir.
