### ISSUE TITLE
Clé API TMDB

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#819]
Hello
J'ai voulu obtenir une clé TMDB pour obtenir les metatags plus rapidement.

Mais le formulaire me demande plein de truc et entre autre le "Lien de l'Appli"

Je mets l'adresse de Vstream sur Github ?

Ca m'étonnerait !? :)

Comment avez-vous rempli ce form?

Merci pour votre aide.

![tmdb](https://cloud.githubusercontent.com/assets/15065996/21830177/47ab44c4-d771-11e6-850b-a40293ba115c.png)

**Comment by johngf** [comment]
tu ecris de fausse info > n'importe quoi ça passe tu auras la clef comme meme
il y a que l'adresse1 code postal ville qui est vérifié auto mais la aussi t'est pas obligé de mettre la tienne
12 rue victor hugo 75000 paris > exemple

**Comment by canopre** [comment]
Merci : je vais essayer en suivant vos instructions
