### ISSUE TITLE
Suite dernière Update Kodi

### ISSUE THREAD

**Issue by stormz85** [Kodi-vStream/venom-xbmc-addons#820]
Hello Mister Venom ! Ça roule ?

Dis il y a eu une mise a jour ya pas long et depuis par exemple Kepliz et autre liens ne marche plus normal ? Et du coup pas mal de liens mort cote openload par exemple ça aussi j'ai trouver bizzare.

Merci d'avance pour ta réponse.
Et surtout merci bcp pour tout ton travail !

**Comment by TmpName** [comment]
Pour kepliz, pas de changement, tu as du tester a un moment ou leur serveur etait out, ou alors donnes moi le film qui deconne stp.
Openload a ete mit a jour le lendemain de la MAJ je crois, tu es bon pr attendre la maj ponctuelle (qui se fait tout les 3 jours) ou mettre a jour le fichier a la main.

**Comment by stormz85** [comment]
ah d'accord, alors on va gentillement attendre dans ce cas la, merci encore pour ton super taff vraiment !

**Comment by TmpName** [comment]
Openload a ete mit a jour hier, donc tu devrais avoir la MAJ ponctuelle dans max 2 jours, selon la date ou tu as fais la derniere.
