### ISSUE TITLE
Possibilité d'ajouter une nouvelle

### ISSUE THREAD

**Issue by Zayatoshi** [Kodi-vStream/venom-xbmc-addons#821]
Bonjour
Cette application est géniale, et merci aux développeurs pour leur travail et contribution.
Cependant dans les sources déjà disponibles, il y en a une qui sera sympa de pouvoir ajouter, c'est extreme-down. Qui reprend le flambeau de feu zone-telechargement.com
Donc serait-il possible d'ajouter SVP la source suivante ? :+1: 

xxxextreme-down.in

Par avance merci.

**Comment by johngf** [comment]
ici pour les demande #517 et pour ex down #688

**Comment by Zayatoshi** [comment]
ok merci. Je poste dans la bonne rubrique.
