### ISSUE TITLE
Problème avec trakt (collection) 

### ISSUE THREAD

**Issue by Lolobeboy** [Kodi-vStream/venom-xbmc-addons#826]
Bonjour, 
J'ai ajouté  plusieurs films à ma collection trakt mais lorsque je veux à accéder à ma collection, la recherche s'arrête et 14 et on me marque erreur vstream,  vérifier dans journal.... .  Et je n'ai pas ce problème lorsqu'il s'agit de ma collection pour les séries.  Quelqu'un pourrait m'éclairer ?  Merci

**Comment by LordVenom** [comment]
Tu peux nous fournir une copie de ton log 

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by Lolobeboy** [comment]
Oui bien sûr,  voici le lien :
 http://slexy.org/view/s2h6ip01y2
Et merci pour votre aide 👍

**Comment by Lolobeboy** [comment]
http://slexy.org/view/s2PNUPOQ21
C'est plutôt ce lien dsl,  ligne 3484-3485. 
Merci

**Comment by johngf** [comment]
c'est parce que le titre du film est un numero le film 31 mais il est vide dans la case title
3456

**Comment by Lolobeboy** [comment]
Ah  d'accord  je vais supprimer le film de ma collection ou essayer de le renommer.  Je vais tester ça tout de suite.  Merci ☺👍

**Comment by johngf** [comment]
Apres pourquoi la case était vide ça ... je sais pas comment fonctionne trackt 
Pas encore testé
Tu ajoute les films sur les sites a trackt ou depuis trackt tu recherche des films sur les sites?

**Comment by Lolobeboy** [comment]
Je viens de tester mais ce n'est pas du au film,  vu que je l'ai enlevé de la collection et j'ai réessayer mais c'est toujours le me problème. Je rajoute les films dans trakt via vstream section films....

**Comment by TmpName** [comment]
Essayes en remplacant ta version de trakt.py par celle la
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/lib/trakt.py

**Comment by Lolobeboy** [comment]
OK j'essaie tout de suite.  Merci

**Comment by Lolobeboy** [comment]
J'ai remplacé ma version de trakt mais c'est toujours le même problème.

**Comment by TmpName** [comment]
Tu pourrais refaire passer les logs stp, je trouves ca bizarre.

**Comment by Lolobeboy** [comment]
Bien sûr,  je fais ça tout de suite

**Comment by Lolobeboy** [comment]
Voici le log :http://slexy.org/view/s21LDpqNak

**Comment by TmpName** [comment]
Il y a eu un soucis dan ta manip.
Dans le log 
>data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/trakt.py", line 350, in getTrakt
                                                sFile = ('%s - (%s)') % (sTitle.encode("utf-8"), int(sYear))

Or la ligne 350 a change, now c'est 
>if sYear:

cf https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/trakt.py

**Comment by Lolobeboy** [comment]
Cette fois,  je l'ai bien remplacé et le problème est résolu, super merci 👍
