### ISSUE TITLE
Mort de mangaCity ?

### ISSUE THREAD

**Issue by Fullpom** [Kodi-vStream/venom-xbmc-addons#827]
Bonjour,
Depuis quelques temps impossible de se connecter à mangaCity (autant sur vstream que sur le net).  Vous n'y pouvez sûrement rien mais avez vous au moins une idée de ce qui se passe? C'est peut être un piratage car ça renvoie vers une page facebook dont les admin ne sont pas au courant. C'est dommage après zone téléchargement on perd vraiment les meilleures sources.
Si c'est vraiment mort autant le virer de vstream ou en trouver un autre qui sait

**Comment by johngf** [comment]
Magacity c'est ianime tv maintenant est il fonctionne sur vstream et sur le net ça vient de chez toi le soucis

**Comment by Fullpom** [comment]
Après redémarrage de mon matériel j'ai réussi a accéder au site mais c'est toujours bloqué au niveau de vstream (je savais que c'était devenus ianime). Il met "erreur: connexion impossible". Ça ne dois donc pas être ma localisation. C'est donc que ça marche pour vous?

**Comment by Kodigoal** [comment]
site ok de mon côté, même via vpn . ..

**Comment by TmpName** [comment]
Salut, tu habites ou ?
Tu as essaye a partir d'un navigateur ?

**Comment by Fullpom** [comment]
De plus en plus étrange, ça marche sur mon pc mais pas sur mon smartphone android ni sur ma TV (AndroidTv).
En utilisant un vpn ou en allant chez des amis, ça remarche sur mon smartphone. Si j'avais été bannis (je ne vois pas pourquoi) ça ne marcherait pas non plus sur mon pc??? J'habite dans une petite bourgade près d'Angoulême.

**Comment by Kodigoal** [comment]
Autre dns configuré sur pc pêtre.
Sinon faudrait log kodi quand te fait erreur.

**Comment by TmpName** [comment]
Le vpn peut changer le user-agent ?

**Comment by TmpName** [comment]
Ok c'est ca, je viens de tester avec un faux user-agent > error 403.
Par contre pkoi ca marche chez nous et pas chez toi ?

**Comment by Fullpom** [comment]
Désolé, à partir de là je suis largué. Je constate juste que magacity sur vstream/kodi android (et pas pc) me met une "erreur: connexion impossible" sauf si je passe par un vpn (autres bugs possibles). J'ai réinstallé le tout et essayé plusieurs versions de vstream mais ça n'y a rien fait. Ça dois donc venir de chez moi mais je n'ai aucune idée d'où ça viens (DNS, IP, UA, je n'y connais pas grand chose) surtout que ça marchait très bien avant (depuis 1 mois environ). Vus que ça n'a l'air de concerner que moi ne vous prenez pas la tête. C'est dommage mais je vais essayer de me débrouiller surtout que j'arrive à accéder au site maintenant (en utilisant Firefox plutôt que chrome). Merci quand même.

**Comment by TmpName** [comment]
Ca peut venir de leur site, un nouvau filtre. Mais la je peux pas tester, je ne pense pas pas que ce soit l'UA car le fichier python utilise son propre UA.
Et contre un bloquage par IP, a part le vpn , pas de solution.

**Comment by Fullpom** [comment]
Au cas où ça pourrait vous aider, voici mon log kodi: s2FepYfvGo
L'erreur est localisée L209

**Comment by TmpName** [comment]
C'est ce dont j avais peur, juste un message pour dire que la connexion avait rate, mais pas d'infos.
Je vais rajouter un truc pour avoir un numero d'erreur mais dans ton cas ca aidera pas,
Mais si ca ne marche que via VPN c'est un blocage par IP. J'ai teste avec quelques webproxy et j'ai eu un peu de tout.

**Comment by Fullpom** [comment]
Ça remarche. Allez savoir pourquoi (cloudflare peu être). Merci à vous pour avoir répondus en tout cas.
