### ISSUE TITLE
Mettre la dernière recherche en cache

### ISSUE THREAD

**Issue by noraef** [Kodi-vStream/venom-xbmc-addons#828]
Salut !

Premier message ici, donc tout d'abord, un grand merci pour vStream, qui est un addon bougrement cool.

Une petite amélioration sur la recherche serait toutefois très pratique. Après avoir effectué une recherche, quand on choisit un site, si on se rend compte que ses sources sont mortes ou que la qualité est pouilleuse, quand on revient en arrière pour afficher les autres sites trouvés, il faut se retaper une recherche...

Ce qui est d'autant plus long quand on active beaucoup plus de sources que par défaut (ce que je trouve nécessaire, dans mon cas), et est assez pénible, puisqu'on a déjà effectué cette même recherche quelques instants plus tôt.

Donc, si le résultat d'une recherche pouvait être conservé en cache tant qu'on ne revient pas à la page d'accueil de vStream, ce serait vraiment classe.

Encore merci pour le travail sur cet addon génial, et en espérant que cette suggestion soit intéressante.

**Comment by TmpName** [comment]
Ha ?
Moi ca me le fait que si je clique sur "suivant" qui apparait sur les sites mal foutus qui affichent trop de resultats.
Pour revenir en arriere j'utilise la fonction "back" et justement cette page est en cache, (gere nativement par kodi).

**Comment by LordVenom** [comment]
Pareil j'utilise la touche retour arrière ou les .. de Kodi et ma page de recherche revient.

**Comment by noraef** [comment]
Chez moi, ça ne met jamais la recherche en cache. 

Mettons que :
-  je cherche un truc aussi simple qu'un film (pas de sous répertoire pour les saisons)
- j'obtiens une liste de sites, avec pour chacun d'eux les résultats trouvés dans cette même liste
- j'en choisis un
- s'affiche alors la liste des sources pour ce résultat
- comme souvent, sources mortes ou qualité crade, donc je reviens en arrière, soit avec le .., soit avec le bouton retour via HDMI CEC (l'un ou l'autre ne change rien)
- ça me relance la recherche pendant des plombes parce que j'ai activé plein de sources (sans quoi, par défaut, je ne trouve rien qui m'intéresse)

Sinon, j'utilise la dernière alpha de LibreElec (7.90.009) parce que j'ai besoin de Krypton pour diverses raisons.

**Comment by LordVenom** [comment]
Ha j'ai jamais tester la v17 de kodi. 

- Aurais tu un problème d’accès au disque dur des droit bizarre de linux.
- Aurais tu activer le mode debug celui ci enlève le cache.
- A tu tester un vidage de cache par les outils de vStream.

**Comment by noraef** [comment]
- les droits sont toujours un peu bizarres sur ces distros dédiées (genre, SSH via root uniquement ; je ne sais même pas s'ils se servent vraiment du multi-user)
- debug sur off
- j'avais déjà testé le nettoyage complet via les outils vStream
- j'utilise le nouveau thème par défaut de Krypton

**Comment by chataigne73** [comment]
Tu es sur quel type de machine? J'ai déjà eu le même soucis sur une box Android et une distri librelec et ça venait d'un mauvais mapping de la touche back
Si tel est ton cas il existe une extension kodi pour remapper les touches, je me souviensplus du nom

**Comment by noraef** [comment]
Je suis sur un NUC Braswell, d'où Krypton (support EGL qui allège bien [la bête est dans un boîtier passif] et qui gère proprement les espaces colorimétriques, et obligé de passer par un dongle CEC au cul du HDMI, lequel dongle a des problèmes avec les Jarvis que j'ai testés).

Le souci ne vient pas du mappage, il me semble : avec un clavier, la touche "efface" produit la même chose que ".." ou "retour" via CEC...

**Comment by johngf** [comment]
J'ai aussi un nuc sur le tiens tu na pas de ir en facade pour telecommande ? Ca t'est vraiment necessaire le cec

**Comment by noraef** [comment]
Nécessaire, non : juste super pratique de tout gérer via la télécommande de la TV. Et de tout façon, le problème reste le même avec le clavier, et reste EGL comme raison de passer à Krypton.

**Comment by johngf** [comment]
En faite quand tu clique une fois ça envoie double signal je sais qu'avec lirc qui normalement est dans openelec on peut mettre un delais pour évité ce genre de truc faudrait voir de ce coté

**Comment by noraef** [comment]
Bah, ça n'a pourtant l'air d'envoyer le signal qu'une fois : quand j'appuie sur retour (CEC aussi bien que clavier), ça ne revient bien que d'un cran en arrière... Le problème est que ça ré-effectue la recherche entière, ce qui est long.

**Comment by johngf** [comment]
Ah ok des que tu clique retour ça recommence de suite la recherche automatiquement ?

**Comment by noraef** [comment]
Oui, voilà. Ça le fait d'ailleurs partout, y compris quand je reviens à la liste de sources après lecture d'une vidéo (sauf que là, comme il n'y a qu'un seul site à parcourir, c'est très rapide, contrairement à quand je reviens à la racine de la recherche, ce qui la relance complètement, et qui est assez long).

**Comment by johngf** [comment]
Fait quelque manip de ce genre et donne nous ton log avec upload log il y aura peut etre qq chose qui aidera
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil

**Comment by noraef** [comment]
Ah, tiens : ça ne veut pas uploader le log de Kodi. Quand je demande à le faire, vStream me demande de confirmer, mais rien ne se passe, notamment pas de popup pour me donner une ID d'upload...

**Comment by johngf** [comment]
Donc je pense que tu as un probleme de droit sur ta machine mais si tu as acces au log met le sur pastebin pour voir

**Comment by noraef** [comment]
Faut que je me connecte en SSH et que je farfouille (je sais qu'ils n'ont activé le SSH que pour root [oui, je sais : vilain-vilain], ce qui me fait penser que ce n'est peut-être même pas multi-user pour ce qui est de l'OS [j'imagine pour alléger la distro, si c'est le cas]). Je vais essayer de voir ça demain.

**Comment by LordVenom** [comment]
Des nouvelles ?

**Comment by noraef** [comment]
Désolé, je n'ai pas eu le temps de m'en occuper hier. Je suis en convalescence d'un gros pépin de santé depuis un moment et passe donc la plupart de mon temps allongé (devant Kodi et vStream, donc encore mille mercis).

Or mon laptop est dead depuis une dizaine de jours, et je dois me lever jusqu'à mon bureau pour accéder au HTPC via SSH (pas assez pratique à mon goût via le smartphone). Et comme je ne peux pas rester assis très longtemps... :-(

**Comment by jackouille2** [comment]
bonjour,
j'ai le même pb lorsque je reviens en arrière ça me relance une recherche à chaque fois donc c'est long
je suis sur une box Android avec Marshmallow

**Comment by LordVenom** [comment]
Pas de soucis je voulais pas te presser juste avoir des nouvelles.

@jackouille2  fait les tests demander et dit nous.

**Comment by johngf** [comment]
@noraef pour le cache #879 c'est un soucis de kodi17

**Comment by noraef** [comment]
@johngf : merci pour l'info. Désolé de ne repasser que maintenant : j'attendais de recevoir mon nouveau laptop, que Lenovo a mis des plombes à me faire parvenir (trop à la peine niveau santé pour passer du temps à un bureau)... Bon, bah plus qu'à attendre que Krypton se stabilise.

**Comment by lefou66** [comment]
pourtant jai deux boite android avec kodi 17.6 et une seule fait ce que noraef dit...des solutions?
