### ISSUE TITLE
kepliz change de nom

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#829]
j'ai mis a jour grudal qui maintenant s'appelle ozporo mais j'ai pas tous testé notament dans le script
il reste des grudals a quelque endroit mais apparement le format rare dans showmovies est devenus la norme je ne suis pas tombé sur le format classique si des personnes peuvent confirmé

**Comment by Benaland** [comment]
Chez moi il s'appelle topulor.com

**Comment by johngf** [comment]
Le site a plusieur copies ou clone

**Comment by khalilounet** [comment]
Comment tu as insérer le fichier de mise à jour .py dans Kodi ?

**Comment by TmpName** [comment]
Si tu veux le faire manuellement, tu as le nouveau fichier ici
https://raw.githubusercontent.com/Kodi-vStream/venom-xbmc-addons/Beta/plugin.video.vstream/resources/sites/kepliz_com.py

Sinon tu l'auras chez toi dans max 3jours, selon la derniere fois ou tu as fais la MAJ ponctuelle (celle que tu declenches dans la page d'acceuil de Vstream).

**Comment by khalilounet** [comment]
Nickel merci !

J'ai effectué la mise à jour manuelle en cliquant sur **mise à jour disponibles** sur l'écran d'accueil de Vstream !
