### ISSUE TITLE
Erreur de catcha

### ISSUE THREAD

**Issue by AsterixetKodi** [Kodi-vStream/venom-xbmc-addons#830]
Bonjour a tous,

Tout d<abord un tres grand merci pour le travail accompli.

Depuis la derniere mise a jour de vStream, j,ai un probleme de catcha les sources. Le catcha n'est pas lisible lorsque ce dernier est demande (oblige de lancer adresse IP pour voir le catcha, le reternir, revenir en arriere et enfin renseigner le catcha). Y a t il un moyen de resoudre cet inconfort?

Pour le site free telechargement je ne vois meme plus les chiffres de l'image (le catcha n'apparait meme pas).

Un gros merci

![bug](https://cloud.githubusercontent.com/assets/25143059/21970421/20dda2b8-db74-11e6-9807-f524c9d8fd1d.jpg)

**Comment by johngf** [comment]
si tu as kodi 17 #654

**Comment by TmpName** [comment]
D'ailleurs ils en sont a la RC3, elle va pas tarder a sortir, on va avoir du taff ^^.

**Comment by AsterixetKodi** [comment]
Bonjour,

Effectivement je suis sur Kodi 17 RC3 ;)

**Comment by LordVenom** [comment]
Le soucis c'est que les petites machine htcp vont mettre une plombe a faire la mise à jour eux.

**Comment by spcxsat** [comment]
Apres il y a peu etre une facon de faire car avec DDL-Island sur vstrem ca fonctionne avec Kodi 17

**Comment by TmpName** [comment]
Le captcha marche sur ddlisland ? Et pas sur les autres ? Put1 ca sent mauvais ca, je pensais que ca venait d'une nouvelle api de kodi, mais si ca marche dans un cas mais pas dans l'autre c'est pas normal, faudrait pas que ce soit un prb de format d'image.

**Comment by spcxsat** [comment]
![imag0010](https://cloud.githubusercontent.com/assets/465563/22156905/9b4bf9d6-df35-11e6-82a1-9ea1778e8523.jpg)
Oui ça fonctionne très bien dessus regarde

**Comment by spcxsat** [comment]
Peut-être la façon son la captchat et appeler ou demander à être afficher j'en sais rien je mi connais pas lol

**Comment by AsterixetKodi** [comment]
Bonjour a tous,

merci pour votre réponse. J'ai fais plusieurs tests sur différents sites.

Voici le catcha que j'obtiens sur le site DDL Island

![probleme ddl-island](https://cloud.githubusercontent.com/assets/25143059/22158181/0a9f6ad4-df09-11e6-8e30-338479be30fc.jpg)

Assez étrange mais il est toujours possible le lire le catcha en passant par adresse IP

Pour free téléchargement le catcha est impossible a lire meme en passant par adresse IP

![probleme free telechargement](https://cloud.githubusercontent.com/assets/25143059/22158234/4dec6198-df09-11e6-9693-104a325b5afc.jpg)


Et je suis un early adopter puisque je suis sur Kodi V17 RC3 sur mon PC et ma box android.


Je sais que j'en demande beaucoup mais j'aurais un petit commentaire sur la fonction recherche.
Je m'explique:
- lors d'une recherche nous avons plusieurs affiches présentes sur différents sites.
 - Je sélectionne une affiche mais ne trouve pas de liens. Je retourne donc vers ma page de résultats de recherche
- et le probleme est que je dois a nouveau recommencer ma recherche (ressaisir les mots de ma recherche) pour avoir les résultats. Ne serait-il pas possible de retomber sur les résultats de notre recherche initiale?

Je ne sais pas si je suis assez clair...

Merci encore a vous tous

**Comment by johngf** [comment]
@AsterixetKodi #828 c'est un probleme de droit sur ta machine

**Comment by AsterixetKodi** [comment]
Meme si la plupart des tests sont realises en mode grand administrateur sur Windows avec le meme resultat? Ne serait ce pas plutôt un probleme de droit sur Kodi v17 RC3?

**Comment by johngf** [comment]
Ptete a cause de kodi 17 Je pense a un truc sur kodi 16 on a une ligne dans le log a l'execution d'un script qui dit 'script invoked without addon this feature will be removed in the future ' peut etre qu'ils l'ont fait et c'est ça qui cause le soucis en tous cas sur kodi 16 pas de soucis

**Comment by spcxsat** [comment]
Mais pourquoi ça fonctionne alors avec DDL-Islande et pas les autres site qui demande un captchat. 
Par contre j'efface juste le txt taper les lettres/chiffres de l'image pour une question de confort sur DDL..

**Comment by TmpName** [comment]
En ce qui me concerne, j'attend la sortie officielle de kodi 17 avant de commencer a adapter le code.
