### ISSUE TITLE
Suite streamase

### ISSUE THREAD

**Issue by kenbest69** [Kodi-vStream/venom-xbmc-addons#834]
Bonjour,
Est-ce que quelqu'un travail sur la suite de streamase? Je parle de l'ajout de séries et mangas. Je trouve ce site très intéressant et il mérite amplement d'être sur vstream.
Merci d'avance.

**Comment by chataigne73** [comment]
je voulais m'en occuper, mais je n'ai pas le temps pour l'instant ...

**Comment by Arias800** [comment]
Bonjour je peux m en occuper normalement elle devrait être finit demain

**Comment by Arias800** [comment]
Manga fait je m'attaque au series

**Comment by TmpName** [comment]
Vu.
Par contre j'ai fusionne tes fichiers avec le premier fichier, histoire d'avoir les 3 types de videos sur le meme fichier site.
Il y a encore l'affichage a ameliorer, et j'ai pas tout teste.

**Comment by Arias800** [comment]
Bonjour mon but était de faire un script  fonctionnel pour kenbest69 le temps que quelqu'un de plus expérimenté les fusionne et amélioré le script
