### ISSUE TITLE
film illimit

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#835]
ils ont modifié leur système un peu comme papy strea ming avec une redirection vers g video au lieu de drive 
j'ai commencé seulement niveau serie apres niveau film il y a les 2 version hébergeur classique et leur systeme de redirection par contre pas trouvé comment mettre la qualité a coté du liens de 1080p a 360p vu qu'il sont séparé
on a le lien final de g video x fois suivant la qualité mais je me demande si c'est pas plus simple de mettre ce genre de redirection
dans un fichier hoster comme liens direct 
enfin si quelqu'un veut jeter un oeuil et continué ou pas
http://pastebin.com/2uWmYb8G

**Comment by TmpName** [comment]
C'est du JSON, tu as
{"l":[liste d'url)],  "q":[liste de qualitee]}.
Soit on peut utiliser les fonctions deja presentes dans python pour gerer le JSON, soit bidouiller avec les regex (une lib de moins a appeller)
Je vais m'en occuper dans la soiree, si personne le fait avant, avec la seconde methode je pense.
Sinon tu as teste la modif sur paylink ?

**Comment by TmpName** [comment]
Modif pr quality
http://pastebin.com/3PSEH5tt
C'est plus crade que les api python, mais une lib de moins a charger.

Le reste plus tard, si j'ai le temps

**Comment by TmpName** [comment]
Derniere version pr ce soir
http://pastebin.com/1SKBRgHe

Manque encore les 2 hosters.

**Comment by johngf** [comment]
watcher ok mais obligé de passé par m3u8 sinon video de 3 minute
papy stream > modif ta modif vue que ça a encore changé maintenant c'est g video au lieu de drive
,del papylink de la beta il faudra le faire dans la master et fichier host json

**Comment by TmpName** [comment]
Nickel pour les 2 hosts.

Je met a jours avec la modif pour goo.gl.
