### ISSUE TITLE
Flash X down

### ISSUE THREAD

**Issue by Turk182es** [Kodi-vStream/venom-xbmc-addons#836]
Salut!

FlashX est encore down je crois, erreur de fichier introuvable :-)
Voilà, encore un grand merci pour votre aide 

Stephane

**Comment by TmpName** [comment]
J'ai mis en place un patch qui devrait marcher, le temps de remettre le code a jours.
Dispo au meme endroit que d'habitude.

**Comment by Turk182es** [comment]
Je regarde ça et je vous confirme.

Encore merci pour votre support!

**Comment by Turk182es** [comment]
Vsteam actualisé mais le problème persiste.
Fichier introuvable.

**Comment by johngf** [comment]
il a été refixé et fonctionnera dans la prochaine maj @Turk182es

**Comment by TmpName** [comment]
Ha ?
Ben je l'ai modifie hier, mais c'etait juste un nettoyage, l'avant derniere version aurait du marcher.

**Comment by johngf** [comment]
Chez moi ça fonctionne

**Comment by Turk182es** [comment]
Pas chez moi :-(

Je viens encore d'essayer sur TVStreaming.ch et fichier introuvable sur toute les séries :-(

**Comment by TmpName** [comment]
D'autres personnes ont teste ?
Le site memorise les ips, c'est peut etre pour cela que ca passe chez nous.

**Comment by johngf** [comment]
des news @Turk182es

**Comment by Turk182es** [comment]
Hier soir toujours rien, "Fichier introuvable" sur tout les Flash X...Ce soir je confirme.

**Comment by johngf** [comment]
bon en mettant en # devant 
#on debloque la page (en test ca a l'air inutile)
#sHtmlContent = self.GetRedirectHtml(aResult[0],sId)
mais apparement l(url finis par mobil.mp4 au lieu de v.mp4 (donc faible qualité je pense) a voir

**Comment by johngf** [comment]
bon j'ai fait une modif a confirmé chez vous

**Comment by Turk182es** [comment]
Je te confirme ça ce soir dés que je rentre du boulot.

Super merci en tout cas!

**Comment by TmpName** [comment]
Moi c'est bon je confirme, c'est nickel.
1 - Ca marche.
2 - Si on change l UA on a effectivment l'autre video
3 - Mais d'apres kodi c'est exactement les meme fichiers.

Par contre si ils rechangent leur lien de debloquage avant 1 semaine, je remet en place le scan barbare.

**Comment by Turk182es** [comment]
Arf! j'ai pas pu essayer hier soir désolé! Je regarde ça ce soir!

**Comment by Turk182es** [comment]
Salut,

Alors ca marche toujours pas :-(

Même erreur sur tout les FlashX de TV-Streaming.ch sur OSMC version Raspberry 

Voilà, de toute façon encore merci pour votre boulot !
Stephane

**Comment by TmpName** [comment]
Alors j'ai voulu restester, ca a deconne
L'url etait du style https://cdn fast1.fx.fastco ntentdelivery.com/trailer/trailer2.mp4?gfydgkygjb54ny 

Puis apres quelques test ca a remarche, donc j'attend quelques heures pour voir si ca vient pas de la memorisation de l'ip.

**Comment by TmpName** [comment]
Bon alors nouvelle version en ligne, mais j'ai pas pu tout tester mais je me sauve en Week end.
@johngf Il y a une seconde url de debloquage tiree d'un script js, parfois ca deconne, mais si je lance l'url dans le navigateur, ca me redebloque, donc peut etre un prb de timer, ou de requetes dans le mauvais ordre. Et j'ai remit en place le systeme bourrin qui charge tout les script js de la page.

**Comment by johngf** [comment]
J'ai pas encore jeté un oeil mais chez mo l'ancienne version fonctionne toujour test hier et aujourdhui ip differente

**Comment by Turk182es** [comment]
Je viens d'essayer et toujours pareil .... Fichier introuvable :(

**Comment by johngf** [comment]
@TmpName a mis une nouvelle version sur la beta donc soit copier coller oou attendre la maj

**Comment by TmpName** [comment]
Nope, ca ne marche pas chez moi non plus.
Mais ca marche si j'ouvre l'url dans le navigateur, le prb c'est qu'il me faut attendre plusieurs heures entre cheques tests. 
Don ca va prendre un peu de temps.

**Comment by TmpName** [comment]
C'est bon ca a l'air de tourner la.

**Comment by johngf** [comment]
@Turk182es c'est bon ? quel version de kodi tu as 16 ou 17 sur 17 c'est Hs j'ai pas cherché le pourquoi du comment vu que c'est le bordel avec xbmc.log sur la 17 il faut activé le mode debug et meme avec ça fonctionne quand il veut du coup j'ai remis la 16

**Comment by Turk182es** [comment]
J'essaye ça ce soir.
Je ne me rappelle plus la version de Kodi, je sais que j'ai la dernière version de OSMC.

**Comment by Turk182es** [comment]
Salut,

Alors ça ne marche toujours pas et la version de Kodi est la 16.1

Voilà :-)

**Comment by TmpName** [comment]
Lol, moi je viens de retester toujours ok, dsl, tu pourrais pas refaire passer un log stp ?

**Comment by Turk182es** [comment]
Je días pas trop comment faire pour les logs, par contre Vstream ne s'est toujours pas actualisé donc c'est peut être le problème.
Est ce que l'actualisation doit être automatique comme d'habitude ?

**Comment by TmpName** [comment]
Yep (celle des 3 jours), et comme le fichier est en ligne depuis 5 jours, ca devrait etre bon, Apres kodi a la sale habitude de mettre tout en cache, et chez moi ca decale tout.

**Comment by bdnico** [comment]
Bonjour, tout d'abord je tiens à vous remercier pour cet addon que je ne connaissais pas et qui est une bonne alternative depuis que ExodusFR est down.

Après installation de vstream et recherche de série/films en streaming je me suis rendu compte que tous les liens flashX.tv et openload (qui sont les plus nombreux) me donnait exactement la même erreur : fichiers introuvables.

J'ai essayé sur une dizaine de série et sur une dizaine de films différents et toujours la même réponse

Je ne sais pas trop comment accèder à mes logs pour les faire parvenir si besoin.
 
Pour info je suis sous kodi 16.1 sur un raspberry 3 dual boot et Kodi tourne sous raspbian et j'ai mis a jour la dernière version de vstream la 0.4.8.
En vous remerciant encore pour votre travail.
Bien cordialement

**Comment by johngf** [comment]
C'est parcequenta version n'est pas a jour il faudra attendre la prochaine maj ou la suivante si tu ne peux
Pas ajouté les fichiers a jour manuellement par copier coller ou remplacer

**Comment by bdnico** [comment]
Merci de la réponse rapide.
Je veux bien attendre la prochaine maj mais pourrais tu m'expliquer quel fichier faut-il que je mette a jour manuellement et ou se trouve-t-il dans l'arborescence Kodi. 
Est-ce que la mise à jour manuelle des hosts peut se faire via ssh ?
Merci d'avance.

**Comment by johngf** [comment]
Quand je dis manuellement c'est avec un explorateur de fichier comme sur windows 
Sur raspbian tu as un bureau ou kodi direct ?
Apres ça doit etre faisable par le terminal mais les commandes ....... je peux pas t'aider
Pour l'arborescence plugin video.vstream/resources/hosters

**Comment by bdnico** [comment]
Ca roule merci je vais regarder alors et je suis avec un bureau sous raspbian mais je peux aussi utiliser filezilla pour voir les fichier sur le raspberry depuis mon pc

**Comment by TmpName** [comment]
Normallement si c'est ta premiere install, dans l'acceuil de Vstream, tu as une option (la derniere de la liste) qui va apparaitre "Mise a jour". Elle devrait apparaitre tout les 3 jours.

**Comment by Turk182es** [comment]
De mon côté j'ai toujours pas de mise à jour qui s'affiche :-(

**Comment by TmpName** [comment]
Alors :
1 - Verifier si le fichier flash est a jours
Dans le fichier flash.py ligne 41
def GetHtml(url,headers): > fichier a jours
autre chose > pas a jours

2 - Si fichier a jours > passer le log
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil

3 - Si fichier pas a jours:
+ Le mettre a jours a la main
+ vider le cache de kodi (dans les outils de Vstream) pour forcer l'actualisation de la page d'acceuil.

Chez moi ca fait 1 semaine que la MAJ aurait du se faire, mais a cause du cache de kodi, nada ...

**Comment by Turk182es** [comment]
Salut !

Alors mise à jour c'est fait par contre FlashX toujours pareil :-(

**Comment by johngf** [comment]
Vide tous les caches et fichier .fi grace aux outils de vstream ensuite fait plusieurs essai de video differente ensuite retourne dans les parametres https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil
upload kodi log normalement un code va s'afficher dans une popup note le et donne le ici si il s'affiche pas c'est un autre probleme

**Comment by johngf** [comment]
Bon bah hs chez moi aussi v4.9

**Comment by TmpName** [comment]
Et tu vois pkoi dans les logs ? Moi teste sur voirfilms, tjours aucun prbs.

**Comment by johngf** [comment]
non rien fichier introuvable
19:21:43 T:2849438528  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
19:21:43 T:2849438528  NOTICE: 	[PLUGIN] Vstream: Hoster - play ht tps://flashx.tv/embed-iqjkfr7wdkua-710x360.html
19:21:43 T:2849438528  NOTICE: Test sur : ht tp://flashx.tv/embed.php?c=iqjkfr7wdkua
19:21:43 T:2849438528  NOTICE: 	[PLUGIN] Vstream Erreur: Fichier introuvable

**Comment by johngf** [comment]
normalement il y a plusieurs ligne test sur

**Comment by johngf** [comment]
bon j'ai fait une modif qui fonctionne sur les deux linux et windows donc normalement ça doit etre ok chez toi
bizarre qu'un truc qui n'était pas utilisé faisait échoué le script

**Comment by bdnico** [comment]
Tout d'abord un grand merci et encore bravo pour la qualité de votre travail et la réactivité. 
Après avoir fait la dernière maj les liens flashX fonctionnent chez moi par contre toujours rien avec Openload :/ toujours cette erreur : "Vstream Erreur: Fichier introuvable"

**Comment by johngf** [comment]
Tu as kodi 16 ou 17 le 17 peut causé des soucis

**Comment by johngf** [comment]
Open load hs chez moi aussi c'est le genre d'hébergeur qui provoque souvent des soucis

**Comment by bdnico** [comment]
Je suis sous Kodi 16 oki merci au moins ca vient pas de moi ^^

**Comment by Turk182es** [comment]
FlashX toujours down chez moi. Kodi 17

**Comment by johngf** [comment]
La derniere fois que j'ai testé sur kodi 17 ça fonctionné pas je ne sais pas pourquoi sur la 16 c'est ok

**Comment by johngf** [comment]
bon alors kodi 17 windows 7 ok je peux pas testé sur une base linux comme openelec parceque j'ai pas l'intention de mettre kodi 17 sur mon nuc
kodi 16 fonctionne mieux et sans soucis avec vstream
quand tu auras fait la maj dit nous si c'est ok

**Comment by TmpName** [comment]
Toujours pas de prb chez moi ^^.
Je regrette pas d'avoir fait ma machine sous windows.

**Comment by johngf** [comment]
Moi avec archlinux sur mon nuc mis a part le fix d'hier que j'ai corrigé hier pas de soucis
Mais comme arch c'est rolling release( toujour a jours) si je met la 17 je ne pourrais pas revenir en arriere si je refait une install complete du systeme

**Comment by Turk182es** [comment]
YESSSSS! Ca marche !!! Vous êtes vraiment excellent !!! Super merci pour tout !!! 
Si vous passez sur Barcelona je vous doit plein de bières !!! :-)
Encore merci pour votre support !

**Comment by TmpName** [comment]
Lol, c'est con c'est pas sur notre trajet cette année.
Enfin bon, on va enfin pouvoir cloturer ce monstre.
