### ISSUE TITLE
pattern Gum Gum

### ISSUE THREAD

**Issue by Norton-breman** [Kodi-vStream/venom-xbmc-addons#840]
Bonjour,

je suis en train de créer la source pour gum gum streaming. Je débute sur Kodi mais j'ai bien pigé le fonctionnement pour l'ajout de sources. Par contre je suis pas super bon en regexp et je galère parce que le site utilise trois pattern (au moins) différents pour définir les liens vers les épisodes:

1) `<a href="LIEN" title="TITRE_COURT">• TITRE_LONG</a>`
2) `<a title="TITRE_COURT" href="LIEN">• TITRE_LONG</a>`
ou 3) `<a href="LIEN">• TITRE_LONG</a>`

Du coup je n'arrive pas à trouver l'expression régulière à utiliser pour gérer les 3 cas de figure. Pour l'instant j'en suis à :

sPattern = 'href="([^"]+)">• (.+?)</a><br />' 
mais ça ne gère que les cas 2 et 3 (95% des épisodes de gumgum streaming).

Quelqu'un aurait une suggestion ?
Merci, Antoine

**Comment by johngf** [comment]
ce qui est important c'est le lien et 1 seul titre pas besoin des deux titre essaie ça
`<a.+?href="([^"]+)">([^<]+)<\/a>`

**Comment by diouf76** [comment]
Cool ça m'intéresse surtout si on y trouve les derniers épisodes car sur vstream pas moyen de trouver les derniers qui marchent.

**Comment by Norton-breman** [comment]
Voilà la source : [http://pastebin.com/qRtapCBd](url). Je n'ai pas encore pu la tester sur un autre pc que le mien, donc aucune certitude quant à sa portabilité. Ça fonctionne pour Kodi 1.6 sous Windows 7. Je vais essayer cet après midi sur Debian Jessy.

**Comment by TmpName** [comment]
Pas vu de prbs.
Je vais la passer en officielle dans la journee.
Elle ne sera pas integree a Vstream car pas de moteur de recherche, mais elle sera visible ailleurs.
Merci.
