### ISSUE TITLE
kaydo hs

### ISSUE THREAD

**Issue by sebi0606** [Kodi-vStream/venom-xbmc-addons#844]
Bonsoir à tous kaydo n'aboutit plus sur les sources quand on clique sur un film si quelqu'un peux me confirmer et corriger ?
Merci d'avance

**Comment by johngf** [comment]
mis a jour

**Comment by johngf** [comment]
il est de nouveau hs a confirmer chez vous ?

**Comment by johngf** [comment]
codé base 64 mais decodé donne des truc bizarre comme ci encodé autre choses

**Comment by TmpName** [comment]
Pas trop dur, j'ai trouve le code javascript. Donne moi une demi heure, je te le converti en python.

**Comment by TmpName** [comment]
http://pastebin.com/xvCqK1aC

Tu as un exemple tire d'une page et son lien decode, en bas du fichier le code javascript nettoye que j'ai utilise.
Apres il se peut que le code soit dynamique, et chnage de temps en temps, si c'est le cas faudra utiliser des regex pour recuperer les paramtres.

**Comment by johngf** [comment]
le code du bas tu l'as trouvé sur le site ?

**Comment by TmpName** [comment]
Nope, page principale, fais une recherche sur 'function hh()' mais il est nettoye.

**Comment by johngf** [comment]
je l'avait trouvé ça mais j'essayé justement de les decodé directement avec base64

**Comment by TmpName** [comment]
Il y a plein de sites qui nettoient le code, moi je me sert de http://www.jsnice.org/
Tu colle le code crado dedans, et ca te ressort un truc nickel, mais par contre si il manque un ; ou un < c'est mort.

**Comment by johngf** [comment]
résolu jusqu'a la prochaine modif

**Comment by johngf** [comment]
effectivement le code change testé sur stargate saison 10 décodé ça donne Stargate SG1 S10E01.mkv
