### ISSUE TITLE
Uptobox /UPTOSTREAM

### ISSUE THREAD

**Issue by arzaz** [Kodi-vStream/venom-xbmc-addons#846]
Erreur "Fichier introuvable" avec les hosts Uptobox & UPTOSTREAM sur DDL-ISLAND et FREE téléchargement.
Vstream installé sur Android.

**Comment by johngf** [comment]
bonjour,merci

**Comment by TmpName** [comment]
Lol.
Sinon moi j'en ai teste un sur FT, qui n'a pas marche mais le fichier etait out sur le site.
Puis 1 sur ddlisland, uptobox ok, et uptosream pas encore ok sur le site non plus.
