### ISSUE TITLE
ajout french-stream

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#847]
Bonjour alors voila j'essaye d'ajouter le site french-stream en me basant sur le fichier "ajouter une source" mais malheureusement je n'y arrive pas 
voila le code que j'ai fait: http://pastebin.com/8Xb5m6XG
Merci pour votre aide

**Comment by Arias800** [comment]
J'ai un nouveau probleme kodi affiche ce message dans les log "    oOutputParameterHandler.addParameter('siteUrl', str(aEntry[2])) #sortie de l'url
                                            IndexError: tuple index out of range"

**Comment by johngf** [comment]
parce que l'entrée aEntry[2] ou une autre n'existe pas

**Comment by Arias800** [comment]
ok merci parce que le pire c'est que ça a l'air de marcher si il y  avais pas ce problème :c

**Comment by johngf** [comment]
après c'est pas une course si tu n'y arrive pas ça veut pas dire que tu ne vas pas y arrivé
il faut insisté et regardé le code dans les fichiers site, testé des trucs jusque ça fonctionne demandé un coup de main après avoir essayer plusieurs trucs pas au premier echec

**Comment by Arias800** [comment]
oui je sait ^^

**Comment by johngf** [comment]
dans stre mase le soucis url_main tu aurais pu ajouté URL_MAIN2 = 'http://manga.streamase.com/'
au lieu de tous remplacé ça t'aurais premit de combiné

**Comment by Arias800** [comment]
si je mettais un URL_MAIN2 ca me faisait disparaître le site de vstream

**Comment by johngf** [comment]
ça c'était pas au cause de url_main2 il devait avoir une erreur quelque part dans le code un ' ou une parentèse ou " ou autres

**Comment by Arias800** [comment]
c'est bon a savoir pour une  prochaine fois ^^

**Comment by TmpName** [comment]
Je sais, pas ou tu en es mais ce site utilise la meme mise en page que le site ht tp://fu ll-strea m.nu
Mais ce ne sont pas les memes liens, donc sites differents.

**Comment by Arias800** [comment]
Je teste le regex de full-stream.nu et je te dit ce que ça donne

**Comment by Arias800** [comment]
Alors j'ai testé ça détecte 1 lien a chaque fois il faut que je me penche sur le regex pour les hoster

**Comment by TmpName** [comment]
Des news @Arias800  ?
Sinon je pense qu'il va etre propose a la team pr etre termine.

**Comment by LordVenom** [comment]
Je les mis dans les projet pour pas le perdre et fermer l'issues.

**Comment by Arias800** [comment]
Oui j'ai du nouveau le cote film fonctionne mais pas les série ça ne trouve pas de hoster et j'ai mit a jour le pastebin (désole le pour le temps qui est passe depuis les dernier message)
Lien pastebin : http://french-stream.com/index.php?newsid=10330

**Comment by TmpName** [comment]
^^.
Y a eu un rattage sur ton lien.

**Comment by TmpName** [comment]
Mit sur le github.
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/en_cours/french_stream_com.py

**Comment by Arias800** [comment]
Merci @TmpName

**Comment by Arias800** [comment]
Bon bah les série marche sur kodi 17 la je comprends plus >.<

**Comment by TmpName** [comment]
lol.
J'ai fait une modif juste apres.
https://github.com/Kodi-vStream/venom-xbmc-addons/commits/Beta/plugin.video.vstream/resources/sites/en_cours/french_stream_com.py

C'est pour ca que c'est plus facile sur github, pour suivre les evolutions.
