### ISSUE TITLE
Live TV ne fonctionne plus 

### ISSUE THREAD

**Issue by xne0n** [Kodi-vStream/venom-xbmc-addons#851]
Salut,
Il y a un souci avec pas mal de chaines, elles ne répondent plus... 
Pour franceTV je crois qu'ils on fermer l'adresse ( http://live.francetv.fr/simulcast/France_2 ) qu'utilisait le script, pour le reste je ne sais pas trop.
Quelqu'un saurait arranger ça ? ou me conseiller une autre extension pour regarder la tv en live ?

Merci 
Xne0n

**Comment by TmpName** [comment]
Bon j'ai commence a jeter un oeuil.
Pas drm, pas de cookie.
Sur le site officiel ils passent par 
http://hdfauthftv-a.akamaihd.net/esi/TA?format=json&url=http%3A%2F%2Flive.francetv.fr%2Fsimulcast%2FFrance_2%2Fhds%2Fmanifest.f4m&callback=_jsonp_loader_callback_request_2

Pour avoir le lien f4m.

Prb nous on utilise le lien m3u8.

**Comment by TmpName** [comment]
Bon j'ai commence, normallement france2 devrait remarcher.
Mais il te faut le nouveau fichier https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/freebox.py
Soit tu le mets le fichier a jours toi meme, soit faut attendre 3 jours pr avoir la MAJ propose chez toi.

Si c'est ok je corrige les autres

**Comment by xne0n** [comment]
Ok merci je vais voir ça, tu es génial !

**Comment by TmpName** [comment]
Alors c'est mieux ?

**Comment by Benaland** [comment]
Yes beaucoup mieux même, merci !

**Comment by TmpName** [comment]
Ok alors je corrige les autres chaines de france TV dans la journee.

**Comment by TmpName** [comment]
Remise en place de gulli et france O en liens officiels.

**Comment by TmpName** [comment]
Bon c'est bon j'ai trouve le moyen de rajouter TF1 et les derives LC1, ect ...
Les liens seront officiel, la methode pr les avoir un peu moins.

Par contre necessite d'attendre la prochaine version COMPLETEde Vstream, pas les Maj ponctuelle.

**Comment by xne0n** [comment]
Whaou super merci beaucoup
