### ISSUE TITLE
Erreur Série TV

### ISSUE THREAD

**Issue by johnboisvert** [Kodi-vStream/venom-xbmc-addons#858]
Bonjour, 
j'ai des problemes avec les série je donne exemple District 31 j'ai écouté 1ere émisssion, la 2e ne fonctionne pas la 3e oui 4e non ...
c'est la meme chose avec Lost (Les perdues) a partir de saison neuf ca fais la meme chose
pouvez vous m'aider svp

Merci

**Comment by johngf** [comment]
peut etre que les liens sont hs  ou soucis avec l'hebergeur vstream donne juste un accés aux liens dispo sur les sites
sinon pour ton soucis quel site ,quel hebergeur, fichier log ?
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log
ou
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil

**Comment by johngf** [comment]
sinon essaie de changé de site pour ta serie c'est pas ce qui manque pour voir

**Comment by johnboisvert** [comment]
C'est les seuls site vstream qui fonctionne pour ces 2 séries ca arrive fréquemment mon frere aussi meme problème merci a toi  je vais envoyer les log mais désolé je suis pas vraiment hot le log je l'envoit ou ?

**Comment by TmpName** [comment]
J'ai trouve disctrict 31 (avec 3 hosts par episode) sur seri e.stra ming.wa tch. Ceux sur filmstrmvk passent par netu qui vient juste d'etre repare.
Pour lost je peux pas te dire, il n'y a que 6 saisons ???

**Comment by johngf** [comment]
en cherchant bien a partir des sources n'ont pas a partir de la recherche global on trouve

**Comment by johnboisvert** [comment]
Merci TmpName oui j'ai vue district que c'est réparer c'est ca coche !! pour Lost oui ya 6 saisons mais genre épisode 1 marche pas 2 marche 3 non etc... mais jai pas revérifier :) good job

**Comment by johnboisvert** [comment]
En passant si vous voulez rajouter ca comme lien c'est un bon petit site :) http://www.film-streaming.club/
Bonne semaine et merci énormément

**Comment by johngf** [comment]
film streaming club c'est hd stream qui est kaydo dans vstream c'est le meme site

**Comment by johnboisvert** [comment]
ok merci :)
