### ISSUE TITLE
Recherche visuelle : Pourquoi le second menu films/séries/annimés/Reportage

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#859]
Bonjour,

Depuis 2 ou 3 mise à jour,
Quand on utilise la recherche visuelle.
Puis par exemple : Films + Genre + Action + On choisit un film.
A ce moment il y a un nouveau menu qui apparait avec :
Films / Séries/ Animés / Reportages / Choix Multiple

A quoi sert-il ?

Comment le supprimer ?

Merci d'avance pour votre aide.

**Comment by LordVenom** [comment]
Petite énigme en image.

![image](https://cloud.githubusercontent.com/assets/4380112/22187756/4ac0cd06-e10c-11e6-8edb-39986eebb796.png)

**Comment by canopre** [comment]
Oui oui : C'est exactement ça qui m'arrive !

Et pourtant j'ai fait une recherche visuelle dans les films donc ca n'est normalement plus la peine de reposer la question ?

Pour mon info : Quel skin utilises/conseilles tu pour tourner avec Vstream ?

**Comment by TmpName** [comment]
Lol, meme moi je galere avec ca. En fait Vstream a modifier son mode de fonctionnement. Avant ca te demandait le type de recherche, maintenant ca te demande ton "groupe de site".
Dans l'exemple de LordVenom, tu peux choisir Film/FilmsHD/ZT , a chaque fois ca va chercher des "films" mais pas sur les memes sites. Si tu prend ZT (qui n'existe plus je sais) ca va chercher des "films" vu que Vstream sais que tu recherche un film mais uniquement sur ZT.

**Comment by canopre** [comment]
hum hum...

Ca a pas l'air simple.... :)

Une idée pour simplement supprimer ce menu ?

**Comment by TmpName** [comment]
Plus possible avec le nouveau mode de fct, car tu vas avoir plusieurs "lot de sites" pour chaque type de video, il faudrait coder un systeme de "lot par defaut" a activer ou desativer (sachant que ca va bugguer si le user ne configure que des lots "films" et choisit une serie). Beacoup de boulot pour eviter un clic.

**Comment by johngf** [comment]
Parceque avant meme si tu etais dans categorie film la recherche sur les sites retournées des serie des mangas etc........
Comme certain site sont compatible pour une recherche avancé donc film=film serie=serie etc...
Il y a eu cette modif #585

**Comment by canopre** [comment]
Ok alors : Je comprends mieux : Merci pour ces explications.
