### ISSUE TITLE
Kepliz ne fonctionne plus

### ISSUE THREAD

**Issue by satch38** [Kodi-vStream/venom-xbmc-addons#866]
Les listes sont bien chargées mais dès qu'on rentre dans un film par exemple, le répertoire est vide (pas de liens googlevideo).

**Comment by johngf** [comment]
j'étais dessus en plus :)

**Comment by satch38** [comment]
Merci beaucoup johngf. C'est du rapide.

**Comment by johngf** [comment]
comme ils ont changé d'adresse il va surement encore avoir du changement par la suite

**Comment by satch38** [comment]
On vous tiendra au courant si ça merdoit à nouveau. Boulot formidable de l'équipe très réactive.
