### ISSUE TITLE
Fichier introuvable

### ISSUE THREAD

**Issue by flip45** [Kodi-vStream/venom-xbmc-addons#869]
Bonjour,

Peu importe ce que je fais je suis jamais capable d'ouvrir un video. Je reçois toujours le message fichier introuvable. Voici mes log:
paste.unbuntu.com/23864529/

Merci de l'aide.

**Comment by johngf** [comment]
Je n'arriva a accedé a ton log met le'sur pastebin ou https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil

**Comment by flip45** [comment]
il y a absolument rien qui fonctionne sur aucun site. je reste au canada et j'ai un pc. Pour les logs:
S21nzZ5Bk4

**Comment by oijkn** [comment]
Bonjour, tout d'abord je tiens à vous remercier pour ce super addons qui est une bonne alternative depuis que GenesisFR est down.

J'en profite qu'un sujet sois déjà ouvert, je rencontre depuis plusieurs jours le même soucis "Fichier introuvable". Je n'ai pas changé de config ou quoi que se soit, j'ai même essayé de vider le cache avec le tool de chez Ares-Project mais le problème persiste :\ Ce qui est un peu bizarre également, je rencontre des soucis aussi avec un autre addon ExodusFR. Je ne sais pas si il y a un lien...

Voici mon fichier [log](https://ares-project.uk/logupload/log.php?id=731345) en espérant que cela vous aide !

La suite est un peu hors sujet mais pensez-vous pouvoir ajouter la fonction qu'avait GenesisFR c'est à dire de pouvoir ajouter nos films/séries dans la librairie et ainsi pouvoir y accéder directement depuis le menu principal de Kodi ? 

Merci d'avance pour vos actions et keep your mind dude :)

**Comment by johngf** [comment]
Dans ton log c'est comme ci tu n'a meme pas essayé de lire une video il n'y a aucune erreur de lecture de vstream 
Redémarre kodi puis vstream teste plusieur video et re upload ton log
Tu a activé utilise urlresolver dans vstream ? C'est pas une bonne idée si oui

**Comment by flip45** [comment]
les nouveau logs :s213GZ9loD
je l'ai peut-être activé accidentellement je vais voir ça.

**Comment by oijkn** [comment]
Fausse alerte, après avoir clear cache Xbmc, fi files, thumbnailset refresh skin lors de la recherche j'obtiens beaucoup plus de serveur (résultat recherche). Donc du coup je peux visionner le stream depuis un autre serveur :) Malgré cette manip si j'essaie les stream des vidéos précédentes (voir mon dernier post) ça ne fonctionne toujours pas donc j'image que cela vient des serveurs et non de l'addon ^^

Sinon je veux bien une p'tite réponse pour ma requête si possible :) Merci les mecs !

**Comment by johngf** [comment]
D'apres ce que je vois tu essaie sur un site que des liens openl oad qui a était mis a jour il y a quelque temps teste sur d'autre site avec d'autre liens pour voir au hasard you watch etc.....

**Comment by johngf** [comment]
Oijkn les liens vstream ne les verifies pas il les affiche c'est tous des fois les liens sont hs dans ce cas il faut cherché sur d'autres sites

**Comment by oijkn** [comment]
johngf je te confirme qu'avec d'autres liens ça fonctionne merci aux outils vstream ;)

Pense tu pouvoir effectuer une portabilité de la fonction de GenesisFR (désolé pour le HS), merci !

**Comment by johngf** [comment]
Vstream a deja une librairie, des marque pages, @TmpName pourra sans doute mieux te répondre que moi j'ai jamais utilisé exodus ou genesis

**Comment by flip45** [comment]
ça marche pas tout le temps sur youwatch mais openload fonctionne maintenant

s2MN90db57

**Comment by oijkn** [comment]
@flip45 teste les manips suivantes : clear cache Xbmc, fi files, thumbnailset refresh skin (pour ma part ça a résolu mon problème)
@johngf merci pour ton retour, oui j'ai bien vu cette fonctionnalité dans vstream :) avec Genesis en fait la librairie est celle de kodi directement d'après ce que je vois vstream utilise sa propre librairie.

**Comment by johngf** [comment]
@flip45 des fois les liens sont hs ce qu'il faut faire pour etre sur tu prend le liens dans ton log tu teste
Sur ton navigateur
Edit pour @TmpName il y a une ligne sur libraire packer dans le log

**Comment by TmpName** [comment]
Normallement la librairie de Vstream fct exactement comme celle de Exodus, sauf qu'elle n'est pas aussi developpée (je suis pas sur que les gens s'en servent, sachant que les liens mit en librairie seront out quelques jours apres).
Par contre c'est a toi de rajouter le chemin de la librairie de Vstream dans kodi (cela ne se fait pas par defaut) , il y a un onglet "librairie" dans les options de Vstream pour le chemin des repertoires.

**Comment by johngf** [comment]
Oui je lui est fait la remarque plus haut il a un soucis qui vient de chez lui

**Comment by oijkn** [comment]
@TmpName salut, merci pour l'info je vérifierai sur mon Kodi. Ce que j'aimais bien dans la fonction de Genesis c'est quand tu vas dans le menu "Series" depuis l'écran d'accueil je pouvais avoir un visuel de toutes mes séries en cours :) chose que je ne retrouve pas avec vstream. Sur votre addon on a que les liens direct des séries ou films ^^ merci en tout cas pour votre super taf !!!

**Comment by TmpName** [comment]
Nope, tu auras uniquement les series que tu met en librairie, apres de memoire, ca classe les episodes dans un repertoire par serie.
Apres on travaille aussi sur trakt, il y aura la possibilitee de rajouter directement les series que tu regardes sur ton compte trakt, pour le moment c'est manuel, mais ce sera possible en auto. Moi pour le moment je laisse en attente, j'attend les retours.

**Comment by brenek** [comment]
Je poursuis le post, je suis nouveau dans l'utilisation de Vstream via Kodi sur une box Android.
Cela fonctionnait très bien au début (jarvis 16.1 et Vstream 0.4.8).
Mais j'ai maintenant dans erreur fichier introuvable.

Quand je regarde mon log les URL sont OK par contre j'ai des erreurs(voir ci-dessous):
 NOTICE: DVDPlayer: finished waiting
13:09:21 T:18446744073172621616  NOTICE: 	[PLUGIN] Vstream: player stoped
13:09:21 T:18446744073172621616  NOTICE: 	[PLUGIN] Vstream: Closing player
13:09:21 T:18446744073172621616  NOTICE: 	[PLUGIN] Vstream: Table initialized
13:09:38 T:18446744073035389232  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
13:09:38 T:18446744073035389232  NOTICE: 	[PLUGIN] Vstream: load site filmstreamvk_com and call function showLinks
13:09:42 T:18446744073035389232  NOTICE: 	[PLUGIN] Vstream: close dialog
13:09:42 T:18446744073035389232  NOTICE: 	[PLUGIN] Vstream: Table initialized
13:09:44 T:18446744073035389232  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
13:09:44 T:18446744073035389232  NOTICE: 	[PLUGIN] Vstream: load site filmstreamvk_com and call function showHosters
13:09:46 T:18446744073035389232  NOTICE: 	[PLUGIN] Vstream: close dialog
13:09:46 T:18446744073035389232  NOTICE: 	[PLUGIN] Vstream: Table initialized
13:10:16 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
13:10:16 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
13:10:16 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://hqq.tv/player/embed_player.php?vid=233222231235212205213234205213235231194271217261258&autoplay=no
13:10:17 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream Erreur: Fichier introuvable
13:10:17 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: Table initialized
13:10:17 T:18446744073506126128   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=Seul+sur+Mars+%5BCOLOR+skyblue%5Dnetu%5B%2FCOLOR%5D&sHosterIdentifier=netu&sTitle=Seul+sur+Mars+%5BCOLOR+skyblue%5Dnetu%5B%2FCOLOR%5D&siteUrl=http%3A%2F%2Fhqq.tv%2Fplayer%2Fembed_player.php%3Fvid%3D233222231235212205213234205213235231194271217261258%26autoplay%3Dno&sFav=play&sMediaUrl=http%3A%2F%2Fhqq.tv%2Fplayer%2Fembed_player.php%3Fvid%3D233222231235212205213234205213235231194271217261258%26autoplay%3Dno&sCat=4&sId=cHosterGui&sFileName=Seul+sur+Mars]
13:10:37 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
13:10:38 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: load site filmstreamvk_com and call function showHosters
13:10:39 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: close dialog
13:10:39 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: Table initialized
13:10:41 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
13:10:42 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
13:10:42 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://exashare.com/embed-0pqei5xpeb4o-660x340.html
13:10:43 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
13:10:43 T:18446744073171126576   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/player.py:25: DeprecationWarning: object.__init__() takes no parameters
                                              xbmc.Player.__init__(self,sPlayerType)
13:10:43 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: player initialized
13:10:43 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: Player use setResolvedUrl() method
13:10:43 T:18446744073506126128  NOTICE: DVDPlayer: Opening: http://179.43.162.114/pwx2myavymm56odwt3t6nxfruugf24pbhyjs4djnh34ygcnw7cbvpykeqowq/v.mp4
13:10:43 T:18446744073506126128 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
13:10:43 T:18446744073090365744  NOTICE: Creating InputStream
13:10:43 T:18446744073090365744  NOTICE: Creating Demuxer
13:11:03 T:18446744073090365744   ERROR: bool CDVDDemuxFFmpeg::Open(CDVDInputStream*, bool, bool) - Error, could not open file http://179.43.162.114/pwx2myavymm56odwt3t6nxfruugf24pbhyjs4djnh34ygcnw7cbvpykeqowq/v.mp4
13:11:03 T:18446744073090365744   ERROR: bool CDVDPlayer::OpenDemuxStream() - Error creating demuxer
13:11:03 T:18446744073090365744  NOTICE: CDVDPlayer::OnExit()
13:12:34 T:18446744073087486256   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
13:12:34 T:18446744073087486256  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 1
13:12:35 T:18446744073506126128   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=Seul+sur+Mars+%5BCOLOR+skyblue%5DExashare%5B%2FCOLOR%5D&sHosterIdentifier=exashare&sTitle=Seul+sur+Mars+%5BCOLOR+skyblue%5DExashare%5B%2FCOLOR%5D&siteUrl=http%3A%2F%2Fexashare.com%2Fembed-0pqei5xpeb4o-660x340.html&sFav=play&sMediaUrl=http%3A%2F%2Fexashare.com%2Fembed-0pqei5xpeb4o-660x340.html&sCat=4&sId=cHosterGui&sFileName=Seul+sur+Mars]
13:12:35 T:18446744073506126128  NOTICE: CDVDPlayer::CloseFile()
13:12:35 T:18446744073506126128  NOTICE: DVDPlayer: waiting for threads to exit
13:12:35 T:18446744073506126128  NOTICE: DVDPlayer: finished waiting
13:12:35 T:18446744073506126128  NOTICE: CDVDPlayer::CloseFile()
13:12:35 T:18446744073506126128  NOTICE: DVDPlayer: waiting for threads to exit
13:12:35 T:18446744073506126128  NOTICE: DVDPlayer: finished waiting


J'arrive pas à les comprendre 
    [PLUGIN] Vstream: Hoster - play http://exashare.com/embed-0pqei5xpeb4o-660x340.html
13:10:43 T:18446744073171126576  NOTICE: 	[PLUGIN] Vstream: playertype from config: dvdplayer
13:10:43 T:18446744073171126576   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/player.py:25: DeprecationWarning: object.__init__() takes no parameters
                                              xbmc.Player.__init__(self,sPlayerType)

Ou celle là

Opening: http://179.43.162.114/pwx2myavymm56odwt3t6nxfruugf24pbhyjs4djnh34ygcnw7cbvpykeqowq/v.mp4
13:10:43 T:18446744073506126128 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
13:10:43 T:18446744073090365744  NOTICE: Creating InputStream
13:10:43 T:18446744073090365744  NOTICE: Creating Demuxer
13:11:03 T:18446744073090365744   ERROR: bool CDVDDemuxFFmpeg::Open(CDVDInputStream*, bool, bool) - Error, could not open file http://179.43.162.114/pwx2myavymm56odwt3t6nxfruugf24pbhyjs4djnh34ygcnw7cbvpykeqowq/v.mp4
13:11:03 T:18446744073090365744   ERROR: bool CDVDPlayer::OpenDemuxStream() - Error creating demuxer


Une idée ???
Merci d'avance

**Comment by johngf** [comment]
Poste ton log sur pastbin.com puis teste #872 dans les params de vstream outils tous les clear etc...

**Comment by brenek** [comment]
Voilà mon log
http://pastebin.com/PkP3LTDE

Les clears ne fonctionnent pas.
Les URL sur navigateurs sont OK
J'ai désactivé l URLResolver
j'ai modifier le timeout en créant un advancesettings.xml

**Comment by johngf** [comment]
Le timeout de advancesettings tu as mis combien? Mais il y a comme meme un soucis avec ton install
3:06:58 T:18446744073043163440 WARNING: Attempt to use invalid handle 3
Se répete souvent

**Comment by brenek** [comment]
ça ve dire quoi ce warning? tu as une idée.

j'ai mis  60 de timeout après je suis pas sur qu'il prenne bien mon fichier.
Il faut bien le mettre dans userdata ?
Non France...

**Comment by LordVenom** [comment]
Change de lecteur dans la config pour voir.

**Comment by LordVenom** [comment]
Je confirme c'est bizarre les Attempt to use invalid handle 3

**Comment by johngf** [comment]
Je pense que ça version n'est pas a jour

**Comment by LordVenom** [comment]
je me note ça fait un print de la version pour les futur log

**Comment by TmpName** [comment]
Perso le "Attempt to use invalid handle 3" m'arrive aussi de temps en temps, mais n'a jamais gene le fctment, mais je l'ai jamais eu a cet endroit.
Openload, tu as une vielle version.
Youwatch exashare et mystream tu as eu les bonnes urls, mais ton systeme n'a pas pu les ouvrir, donc comme precedement je pense a un prb de timeout.
Pendant combien de temps le systeme cherche la video avant de la lancer (tout est bloque, tu ne peux que attendre)

Sinon comme dit @johngf tu as quelle version de kodi et de Vstream ?
>13:12:54 T:18446744073171388720   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/player.py:25: DeprecationWarning: object.__init__() takes no parameters
De memoire ce prb est corrige depuis un moment !

**Comment by brenek** [comment]
Salut,

Comme dit plus haut, la version de Kodi 16.1 et la vstream 0.4.8, je vérifierai ce soir, mais la dernière ces sur!
ça cherche un moment, j'ai pas chrono mais bien une trentaine de seconde.
pour le advancesettings.xml il faut le positionner dans userdata/ j'ai l'impression au vue du log que ça me le prend pas ?

dans le fichier j'ai mis ça 
<advancedsettings>
      <network>
         <readbufferfactor>10.0</readbufferfactor> 
         <curlclienttimeout>60</curlclienttimeout>
         <curllowspeedtime>60</curllowspeedtime>
         <disableipv6>true</disableipv6>
      </network>
</advancedsettings>

il faut autre chose ?

Merci beaucoup pour votre aide et réactivité.

**Comment by johngf** [comment]
Oui il n'est pas pris en compte voir si le fichier est bien redigé,si tu la mis dans le bon dossier(fichier caché)

**Comment by TmpName** [comment]
Tu peux aussi tester dans l'onglet "general" '"lecture par defaut" passer un peu tout les parametres.
```
Moi j'ai ca dans le mien
      <network>
         <curlclienttimeout>60</curlclienttimeout>
         <curllowspeedtime>60</curllowspeedtime>
         <disableipv6>true</disableipv6>
      </network>
```

Mais 30s tu devrais avoir au moins quelques liens qui tournent (il y a 20s dans tes log entre le moment ou ca commence et le message d'erreur, mais meme 20s y en a qui devraient passer)

**Comment by brenek** [comment]
Toujours pareil.
les URL marchent dans le navigateur dans le log on voit qui prend bien mon advancesettings.xml
J'ai testé les autre lecteur idem :(

voilà le log
http://pastebin.com/4XQZXqQG

**Comment by brenek** [comment]
Et ca viendrait pas du player.by qui serait hs

Autre chose hier le film dans le log fonctionnait via vstream et aujourd'hui non:(
Il y a forcément un truc qui deconne, le cache de vstream est vide et celui de Kodi aussi.
Est-ce qu'il y a des fichiers qui sont modifiés après lecture ou suite à des MAJ auto?

**Comment by johngf** [comment]
non c'est juste un avertissement de dépréciation player py fonctionne tres bien
tu ulilise quel player dans les param de vstream lecture par defaut >> il doit avoir xbmcplugin

**Comment by brenek** [comment]
oui celui là et j'ai testé les autres aussi :( :(
désolé, mais je découvre vstream donc j'ai un peu de mal à tout comprendre pour le moment.

**Comment by johngf** [comment]
test ça tv replay/tv replay dernier ajout/ mareplay tv/touche pas a mon poste 31 janvier 2017 essaie de lire la video

**Comment by johngf** [comment]
comme t'est sur android quel droit as tu donné a kodi parce que regarde dans ton log
20:03:54 T:18446744073007003952   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
android ne t'empecherai pas de te connecté ?

**Comment by brenek** [comment]
Bon je viens d'essayé sans succès!
le log ci-dessous il y a une erreur
http://pastebin.com/sEa5WC8F

Bon piste pour les droits android, mais je ne vois pas où je peux régler cela.
Je viens de faire un tour dans les settings de ma box... j'ai rien trouvé de parlant

**Comment by johngf** [comment]
test plusieurs videos you watch pour voir open load n'est pas a jour dans ta version je pense

**Comment by brenek** [comment]
je viens d'essayer la série gotham sur Youwatch cela fonctionne...!!!
Bon je vais voir, mais c'est bizarre que dans un cas le lien marche puis après il marche pas.
Après est-ce que c'est pas le site de stream qui bloque ?

**Comment by johngf** [comment]
fais un test de debit pour voir http://speedof.me/
mais comme j'ai deja dit je pense tu n'est pas a jour donc il faut attendre la mise a jour

**Comment by brenek** [comment]
Elle est prévue quand ?

37 en download et 6.5 en up

**Comment by johngf** [comment]
c'est tous les 3 jours

**Comment by brenek** [comment]
Ok merci beaucoup
a bientot surement :)

**Comment by johngf** [comment]
les liens sur les sites ne sont pas garantis des fois il faut cherché sur plusieurs site différent pour avoir ce que tu cherche

**Comment by LordVenom** [comment]
J'ai tester un emulateur android 4.4.2 au debut ca fonctionner pas mais aprés la mise a jour journalière le menu vert "mise a jour disponible" ça tourne

![image](https://cloud.githubusercontent.com/assets/4380112/22502189/30b20eae-e86c-11e6-9ad4-d279e1eab5f7.png)

**Comment by brenek** [comment]
#johngf oui oui je sais qu'il faut regarder sur plusieurs lien, mais le test du départ était sur le meme lien... 

merci de votre aide, je vais voir si après la MAJ cela fonctionne, sinon je chercherai du coté d'Android...

**Comment by emailradhesh** [comment]
I've a script similar to videobuzzy_com.py. It fetches video frames from a site. The video frames are in Dailymotion, HQQ TV, etc. After update of LibreELEC to Kodi Krypton the videos are not getting displayed.

I attempted to view translated text of this issue. It is not clear. Hence requesting someone to help me in English please.

Before posting, I attempted to clear all caches available within this add-on settings and still the error comes up.

**Comment by emailradhesh** [comment]
Ignore the previous update of this issue. It worked now for other videos.
