### ISSUE TITLE
Demande d'infos

### ISSUE THREAD

**Issue by ticiap** [Kodi-vStream/venom-xbmc-addons#870]
Bonjour, Merci pour votre super boulot! Je suis assez novice avec Kodi. J'aimerai savoir si je peut télécharger des films sur vstream au lieu de les voir en streaming car des fois ils mettent du temps à charger à cause de la mise en cache. Jai une box mxq pro. Merci

**Comment by TmpName** [comment]
Vstream n'est pas prevu pour ca, tu trouveras plus performant comme application. Le mieux de de choisir un stream en plus basse qualitee.
Sinon clic droit et "telecharger" quand tu arrives sur le lien final, cette fonction est bridée (tres ralentie), mais ca peut depanner.
