### ISSUE TITLE
Site de streaming hd sans pub

### ISSUE THREAD

**Issue by bubuleur** [Kodi-vStream/venom-xbmc-addons#871]
Bonjour,
Déjà merci pour votre addons très complet en films merci encore
J'ai une proposition de site web streaming hd sans pub
ht tp://ler iov.com
Si vous pouviez le mettre dans vstream se serait super
Les films sont de bonne qualité et il marche bien
Merci bien

**Comment by johngf** [comment]
Bah #852 c'est encore un clone de kepliz qui est dans vstream le site a plein de nom different

**Comment by TmpName** [comment]
XD.
Avoue tu es une machine ?

**Comment by johngf** [comment]
Un bot comme sur irc avant lol
