### ISSUE TITLE
Fichier introuvable 

### ISSUE THREAD

**Issue by OstreumDeus** [Kodi-vStream/venom-xbmc-addons#872]
Bonjour, peut importe le film ou la source, l'erreur est toujours la même : "fichier introuvable"
J'ai voulu vous joindre les logs, cependant, l'outils "Upload Kodi.log" ne semble pas fonctionner. En effet, après avoir validé l'upload, rien ne se passe.
Voilà, merci d'avance

PS: J'ai installé Vstream via le repository

**Comment by TmpName** [comment]
As tu essaye d'aller sur les sites via un navigateur ?
Meme prb ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/869

**Comment by OstreumDeus** [comment]
Merci pour cette réponse rapide, 
j'ai fait tout les "clear" et tout fonctionne merci beaucoup !!
Du coup je ferme l'issue
