### ISSUE TITLE
recherche globale

### ISSUE THREAD

**Issue by johngf** [Kodi-vStream/venom-xbmc-addons#873]
bonjour, la recherche global recherche/anime/un anime n'a pas l'air de fonctionné sur adkami meme en modifiant l'erreur de label > label="30091" au lieu de label="30090" pour anime qu'il y a dans settings vstream n'essaie meme pas de load le plugin la raison a ça ??? pas trouvé de soluce
la recherche a partir du site fonctionne

**Comment by LordVenom** [comment]
![image](https://cloud.githubusercontent.com/assets/4380112/22368386/81e84462-e486-11e6-9ff5-b7e28c0bcfea.png)

**Comment by johngf** [comment]
c'est une recherche choix multiple que tu as fait ? je parle de la recherche de base en cliquant sur recherche3:animes/un anime
chez moi fonctionne pas

**Comment by TmpName** [comment]
Je vient de tester, pas vu de prb.
J'ai le meme ecran que @LordVenom mais sans les chiffres devant.
Et j'ai tout de base avec les animes en recherche 3 aussi.

Et second test "recherche choix multiple" / naruto / adkami (tout seul), pareil c'est ok.

Il se charge dans les log ?

**Comment by johngf** [comment]
non vstream ne load jamais le site tous les sites sont activé sur ce pc je vais voir sur mon autre pc

**Comment by TmpName** [comment]
Tu as le message classique "can't load pluggin X" ou meme pas ?

**Comment by johngf** [comment]
Non pas de message comme si le site existe pas la recherche commence a film stream hd sur 2 pc different

**Comment by TmpName** [comment]
Alors la je peux pas trop aider mais le fichier recherchehnadler.py fait un scan des fichiers disque dont la je pense que c'est bon puis passe a la fonction __importPlugin et la regarde le fichier unquement si 
`if (bPlugin == 'true') and (OnPlugins == 'true'):`

Ligne 88, essayes en bidouillant a ce niveau

**Comment by johngf** [comment]
bon j'ai pas trouvé le soucis mais comme j'ai tous désinstallé et réinstallé pour test kodi 17 le soucis a disparu

**Comment by TmpName** [comment]
Mwé, mais suis quand meme curieux de savoir ce qui s est passe.

**Comment by johngf** [comment]
en reinstallant kodi 16 je viens de me remarqué c'est pareil avec les films tous ce qui est avant 
film enstreaminghd_com n'est pas pris en compte
