### ISSUE TITLE
Bonjour Tout le monde

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#874]
Bonjour,

J'adore le boulot que vous faites je l'ai déjà dit mais mille merci pour le taf! Je sais bien que le site Kaydo.ws en béta mais c'est normal que je vois aucun lien sur cette source? (voir image), désolé de vous embêter pour çà, merci d'avance pour vos réponses.

![image](https://cloud.githubusercontent.com/assets/16462265/22366916/44d69148-e47f-11e6-9656-0a78c308e8c9.png)

![image](https://cloud.githubusercontent.com/assets/16462265/22366973/76abd87c-e47f-11e6-8ff0-877869e8b091.png)

**Comment by johngf** [comment]
bah ils passent leur temps a changé

**Comment by patoche2025** [comment]
Ah tout s'explique maintenant lol

**Comment by johngf** [comment]
fix dispo sur la beta

**Comment by patoche2025** [comment]
Super @johngf je vais essayer ça sur le temps de midi lol
