### ISSUE TITLE
Ajout à la librairie

### ISSUE THREAD

**Issue by Lolobeboy** [Kodi-vStream/venom-xbmc-addons#878]
Bonjour,  je voudrais savoir si c'était encore possible de faire un ajout à la librairie parce que quand je regarde dans le menu, il n'y a pas cette option.  Merci d'avance

**Comment by Lolobeboy** [comment]
OK merci,  mais l'option n'est pas là,  tout ce que j'ai c'est marquer vu/non vu,  marque page,  trakt,  voir marque page,...

**Comment by TmpName** [comment]
Cliques sur le lien et re-essayes sur le suivant. Ce menu n'apparait que sur le dernier.

**Comment by Lolobeboy** [comment]
Super merci,  c'est résolu 👍
