### ISSUE TITLE
Transféré un .py

### ISSUE THREAD

**Issue by diouf76** [Kodi-vStream/venom-xbmc-addons#879]
Bonjour je voudrais rajouter un site en .py dans le répertoire caché, je suis sous Android TV mais je n arrive pas à coller le fichier dans le répertoire, savez vous comment faire? Que ce soit en réseau local ou direct depuis l Android TV.
Merci par avance

**Comment by LordVenom** [comment]
Bonjour, 

Tu ne trouve pas le dossier ? https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-vStream
ou
Tu n'a pas les permissions ?

**Comment by diouf76** [comment]
En fait j'ai accès au répertoire "site" j'ai fait la copie du fichier à basculer avant mais une fois dans le répertoire plus moyen de coller . J ai essayé sous es explorer.

**Comment by LordVenom** [comment]
Il faut que es explorateur et les droit de "root" il me semble.

**Comment by diouf76** [comment]
Je vais voir ça

**Comment by TmpName** [comment]
Regardes ici.
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Comment-rajouter-ou-creer-sa-propre-source.
Si tu n'as pas le fameux message

> Cant import plugin masource_org

**Comment by diouf76** [comment]
Je regarde ca ce soir, sinon j'ai fait la même chose sur kodi sous Windows et j'ai eu droit à la mise à jour et le site était dispo.

**Comment by diouf76** [comment]
Je précise que c est un site. Py dispo sur votre github donc approuvé donc l erreur est ailleurs ou l upload s est mal passé je re essaie ce soir.

**Comment by johngf** [comment]
Comment tu l'as pris le fichier py tu as cliqué droit sur le boutton raw puis telecharger ou pas ?

**Comment by diouf76** [comment]
J'ai cliqué droit sur le fichier

**Comment by johngf** [comment]
Donc c'est normal que ça fonctionne pas il faut toujour cliqué sur raw avant de téléchargé ou'de copier coller

**Comment by diouf76** [comment]
Ok merci, je teste ce soir, et dernière question, site.py que tu as fait pour uptobox, je dois le remplacer par celui existant?

**Comment by johngf** [comment]
Je modif le nom pour que tu puissent en avoir 2 sinon a chaque maj il sera remplacé donc tu fera click droit enregister sous ou autre vers le repertoire site de vtream
Note dans l'avenir je ne sais pas quand lemois prochain ou celui d'apres metahandler ne sera plus dans vstream donc ça fonctionnera plus a moin que tu rajoute metahandler toi meme si tu reinstalle tous

**Comment by LordVenom** [comment]
je penserais a regarder.

**Comment by chataigne73** [comment]
à titre d'info, il existe une méthode beaucoup plus simple pour mettre à jours tous les fichiers au même niveau que la beta : 
1/ télécharger tous les fichiers de la beta via ce lien https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2Fplugin.video.vstream
2/ dans kodi, aller dans preferences/addons et choisir de mettre à jour à partir d'un fichier zip, et selectionner le fichier zip téléchargé précédemment
3/ et voilà, votre vstream est au mêmeniveau que la beta

**Comment by LordVenom** [comment]
ça fonctionne ce systeme cool bon pour le wiki ça mais pas de "ca marche pas" il nous faut un vrais retour si vous installer la beta.

**Comment by johngf** [comment]
@chataigne73 ok mais le site en question n'est pas sur la beta mais sur mon compte perso

**Comment by diouf76** [comment]
Bon finalement en suivant tes conseils tout marche et mon compte uptobox t'en remercie aussi.

**Comment by LordVenom** [comment]
@johngf tu utilise guielement pour les metas ça fonctionneras toujours :)

**Comment by johngf** [comment]
je disait ça au cas ou il refait une install complete kodi et vstream
