### ISSUE TITLE
chargement avec Kodi 17

### ISSUE THREAD

**Issue by kroukes2000** [Kodi-vStream/venom-xbmc-addons#882]
Bonsoir a tous
bon je viens de mettre a jour kodi 17 rc4 sur ma box tv android, il est plus stable avec ma box.
Mais avec vstream maintenant a chaque fois que je remonte les dossiers parents d'une recherche il relance le chargement ou la recherche et c'est pénible surtout quand on regarde une série.
je sais pas si c'est une option a activer ou désactiver sur kodi ou autre chose dans vstream.
quelqu’un a une ptite idée?
Merci

**Comment by johngf** [comment]
si tu regarde recherche dans les issues qui sont fermé en cliquant sur closed ex: #830
vstream ne supporte pas encore kodi 17 beta nous attendons la version final de kodi 17 pour corrigé les bugs si il y en a donc si tu veux pas de bug installe kodi 16 jarvis

**Comment by johngf** [comment]
alors j'ai jeté un oeil a kodi 17 et le soucis vient de kodi 17 beta lui meme il n'y a plus de fichier ne navigation
 (les fichiers .fi dans temp) la fonction qui crée ces fichiers n'est surement pas activé par les devs de kodi pour le moment ou le sera pas je ne sais pas encore donc a chaque retour arrière kodi ne se rappelle plus ou il était donc le chargement se relance

**Comment by TmpName** [comment]
Lol, et ils en sont a la RC4, je la sens mal la V17.

**Comment by mako83** [comment]
la beta de kodi 17 est fini maintenant non ?

**Comment by TmpName** [comment]
Nope, RC4.

**Comment by johngf** [comment]
et plein de bug
