### ISSUE TITLE
Erreur Vstream lors d'une Recherche Visuelle 

### ISSUE THREAD

**Issue by Vdauphin** [Kodi-vStream/venom-xbmc-addons#888]
Bonjour,
Je ne parviens plus à effectuer de recherche visuelle lorsque je clique sur "Films Populaire" ou autre.
Kodi me renvoye une erreur : Erreur Vstream voir log

[kodi.old.txt](https://github.com/Kodi-vStream/venom-xbmc-addons/files/752378/kodi.old.txt)

Avez vous une idée ?

Cordialement.

PS: j'ai reinstallé l'extension sans succès.

**Comment by johngf** [comment]
retourne sur la page home et clique sur recherche visuelle tu arrive a y entrée ou tu as une erreur

**Comment by Vdauphin** [comment]
J'arrive à y entrée. C'est lorsque je clique sur la catégorie de recherche que cela génère l'erreur.

**Comment by johngf** [comment]
ton log est trop court fait plusieurs essai ensuite https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil 
upload kodi log normalement un code va s'afficher dans une popup note le et donne le ici si il s'affiche pas c'est un autre probleme

**Comment by LordVenom** [comment]
La nouvelle version passer en mise a jour n est pas compatible avec la version 038 la prochaine mise a jour mensuel corrigeras ça.

**Comment by Vdauphin** [comment]
> La nouvelle version passer en mise a jour n est pas compatible avec la version 038 la prochaine mise a jour mensuel corrigeras ça.

Qui n'est pas compatible avec la version 038 de quoi ? ^^

**Comment by johngf** [comment]
il y a eu une modif de vstream et la recherche visuelle ne fonctionnera qu'a la prochaine maj du mois
ou alors il faut soit installé vstream et ne pas faire la mise a jour ou il faut installé la version beta tu as quoi comme machine ?

**Comment by Vdauphin** [comment]
C'est sur un serveur Odroid C1+.  Un copier coller n'est pas impossible cela depend où ...
Si cela sera corrigé dans un mois automatiquement je peux patienter.

**Comment by johngf** [comment]
j'ai pensé au copier coller de la beta mais en faite ça ne va pas résoudre le problème la recherche visuelle va buggé sinon test https://github.com/Kodi-vStream/venom-xbmc-addons/archive/Beta.zip

**Comment by johngf** [comment]
bon en faite c'est ok avec la beta copie pluginvideovstream du zip et remplace celui que tu as

**Comment by TmpName** [comment]
Si la MAJ complete a lieu dans un moment, on peut laisser la vielle version en attendant ?
Quite a mettre les 2 fichier sur la beta ?
Sinon on risque d'avoir souvent le meme post.

**Comment by LordVenom** [comment]
Non elle vas pas tarder je vérifie quelques fichiers prend des notes (voir project)  et je lance ça bientôt 1ou3jours. J'avoue ce system de bêta me perturbe j'oublie toujour les mises a jours faudrais pouvoir verrouiller un fichier a voir.

**Comment by Vdauphin** [comment]
Resolue via v0.4.9
Merci !
