### ISSUE TITLE
Probleme avec kepliz kodi 17.0

### ISSUE THREAD

**Issue by mino60** [Kodi-vStream/venom-xbmc-addons#892]
Bonsoir...j'ai un probleme pour afficher les liens google (erreur consulter le journal pour plus d'information)
kodi 17. 0 sur mon smart phone xp z5 pr? par contre pas de probleme sur PC kodi 15.1!!!...

**Comment by LordVenom** [comment]
vStream n'est pas tester sur Kodi 17.

**Comment by TmpName** [comment]
Lol, encore 1 a 2 semaine je pense et on va tous pouvoir pleurer sur la V17.

**Comment by LordVenom** [comment]
La 0.4.9 apporte beaucoup de modification j'attend les retours puis je passe en V17

**Comment by spcxsat** [comment]
Bonjour, 

Perso moi sur ma Nvidia Sheild TV avec Kodi 17 aucun soucis avec Kepliz ça fonctionne normalement

**Comment by LordVenom** [comment]
Kepliz les liens google fonctionne pas sur film illimit

**Comment by spcxsat** [comment]
Oui je suis d'accord les lien Google ne fonctionne pas sur film illimité 
Sauf ceux avec la résolution 360p ceux là fonctionne

**Comment by johngf** [comment]
oui c'est moi la façon de séparer les liens je jette un oeil

**Comment by johngf** [comment]
fix sur beta pour film illimit

**Comment by LordVenom** [comment]
Dans film illimit la fonction ShowSpecialHosters() 

Si tu fait un eval(str(sHtmlContent)) ça devrais te retourner un dict utilisable en boucle.Mais temps que ça marche :)

**Comment by LordVenom** [comment]
ça fonctionne pas et Kepliz aussi et mort

**Comment by johngf** [comment]
film illimite est ok chez moi http://pastebin.com/NESv2Uet

**Comment by LordVenom** [comment]
Oui le soucis doit venir du host.

**Comment by johngf** [comment]
oui testé sur plusieur videos differente qualité

**Comment by LordVenom** [comment]
Ok meme sur le site illimite j'ai un message d'erreur pour leur jplayer.

**Comment by johngf** [comment]
tu est sur kodi 17 ?

**Comment by LordVenom** [comment]
j'ai tester sur les 2 mais le soucis ce trouve aussi sur leur site.

**Comment by TmpName** [comment]
J'ai eu le meme prb hier, vous en etes ou ?
J'ai pu voir que le lien recuperer etait s://redirector.... au lieu de https://redirector ....
Quelqu'un a corrige ca depuis ?

**Comment by johngf** [comment]
Oui

**Comment by TmpName** [comment]
Au fait ca y est kodi passe en V17 officiellement.

**Comment by LordVenom** [comment]
Si je vais sur official-film-illimite.net (film illimit) film le-dernier-loup leur jplayer me retourne error loading ceux qui doit être les liens googlevideo car sur vstream tous les liens google ne fonctionne pas.Y a que moi ou ça fonctionne pas ? tester sous Kodi 16 et 17

**Comment by johngf** [comment]
chez moi ça fonctionne kodi 16 meme film je voulais faire une capture video de mon bureau mais ça plante avec vlc

**Comment by johngf** [comment]
https://vid.me/JulU
