### ISSUE TITLE
Actualiter RSS

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#893]
Dans le Home qu'est ce que vous penser de faire une sorte de RSS des informations modifiable uniquement sur Master pour écrire ben ceux qu'on veut du genre "regler vos recherches pour avoir tous les sites" ou encore bug connus sur kepliz ect..

**Comment by TmpName** [comment]
J'y ai pense aussi mais.
1 - connexions suplementaire sur le github.
2 - a cause de cette put1 de mise en cache de kodi de la page home (a voir si tjours presente sur V17) le flux ne changera pas chez moi (et chez d'autre)
3 - j'ai pas trouve comment presenter le truc, si le mec fait comme moi et affiche la page home sous le mode "icone" ou "vignette", ca ressemble plus a rien.

**Comment by LordVenom** [comment]
Non tu ma convaincus ont pourais faire une popup mais non ça fait trop pour juste quelque info c'est inutile.

**Comment by TmpName** [comment]
Apres j'ai pas encore teste la V17, mais deja je regrettais de ne pas pouvoir la position dans les menus, eg "Favoris/TV/" ou "site1/film/top/" alors un flux rss ....
