### ISSUE TITLE
Interview LordVenom

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#894]
Comme toujours je remercie tous ceux qui participe à vStream de toute les manières possible. Dans cette optique le site http://looma.fr/ à fait deux article excellent merci de lui faire péter son compteur.

vStream
http://looma.fr/films-et-series-en-streaming-illimite-grace-a-kodi-et-vstream/

LordVenom
http://looma.fr/interview-de-lord-venom-fondateur-de-lextension-de-streaming-vstream/

**Comment by TmpName** [comment]
XD, autant le premier lien j'en vois partout, autant le second c'etait une surprise, par contre je te voyais pas comme sur la vignette qui illustre la page ^^.
Nan serieusement c'est sympa, ca te personnifie.

**Comment by zombiB** [comment]
cool interview :)

**Comment by johnboisvert** [comment]
Vraiment ca coche !!!

**Comment by Ronaldonizuka** [comment]
Cool l'interview, c'est vrai qu'il est étrange ce monde, on se parle souvent, mais on ne se connais pas. 
Tourneur/fraiseur ?! c'est la grande classe, je travail sur une petite cnc maison là ;)
