### ISSUE TITLE
Kodi V17 (popup sur back & capcha)

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#899]
Bon ok, ca n'a rien a voir avec Vstream, mais je commence a avoir la sale manie de demander ici par defaut.
Je viens d'installer kodi v17, et je suis perdu avec le nouveau theme.
1 - Y a t il un moyen d'avoir une page d'acceuil "pratique", qui affiche TOUT en resume, marre de faire 10 manip juste pour acceder a Vstream, alors que sur le precedent theme je l'avais au demarrage de kodi.
2 - Comment changer taille et couleur des textes du theme par defaut, blanc sur bleu clair, mais serieux si c'est pas debile comme choix.
3 - j'ai plus la possibilite de choisir le mode d'affichage sur la page d'acceuil de Vstream ???

(A suivre)

**Comment by johngf** [comment]
Oui moi j'ai reinstallé l'ancien theme je trouve il est mal fichu le nouveau

**Comment by TmpName** [comment]
XD, nan mais serieux, j'ai essaye de faire un screen du ma machine pour montrer le resultat, il est inutilisable.

J'ai l'ecran divise en 3 verticalement.
1 er partie > Un bloc noir avec juste en haut le titre, decoupe en 3 car evidement ca rentre pas.
2 eme partie > Un bloc bleu clair, avec texte en blanc/bleu et heureusement orange, ecrit en fin et tout petit, avec une mise en page a la con qui rend le site filmenstreamingHD incomprehensible.
3 eme partie > L'affiche ..... sur 33% de l'ecran

Ok je suis d'accord, cette page je peux modifier le type d'affichage, mais put1 on fait en sorte que le mode par defaut soit utilisable.

**Comment by johngf** [comment]
Il faut ajouter le dossier de photos  pour faire un screen

**Comment by TmpName** [comment]
J'ai fait comme toi, j'ai re DL l'ancien, je vais voir si ma copine reagit bien, mais a mon avis ce WE on repart avec confluence.

**Comment by johngf** [comment]
Moi j'ai cherché des infos sur google pour modif est rien trouvé pour l'instant

**Comment by TmpName** [comment]
Bon j'ai craque, suis repasse sous confluence.
Et du coup bonne nouvelle, les captcha fonctionnent ^^, suffit d'avoir un theme utilisable.

**Comment by LordVenom** [comment]
![image](https://cloud.githubusercontent.com/assets/4380112/22662523/a9c37e2c-eca9-11e6-9c6d-8871b7d6b5f0.png)

![image](https://cloud.githubusercontent.com/assets/4380112/22662583/db1d9548-eca9-11e6-8e11-15bc5a5d3b18.png)

**Comment by LordVenom** [comment]
Le mien et buguer y a pas la langue FR je suis en canadien lol

**Comment by LordVenom** [comment]
![image](https://cloud.githubusercontent.com/assets/4380112/22662728/41f2126c-ecaa-11e6-8ae8-b7d5fe9a247e.png)

**Comment by johngf** [comment]
La langie fr faut l'install soit meme via depot

**Comment by LordVenom** [comment]
Allais petite video d'installation:

https://www.youtube.com/watch?v=1uS5gbd8jpE

**Comment by TmpName** [comment]
Bon avant pr debogguer on faisait "print truc" puis apres on a du faire "xbmc.log(truc)" et maintenant faut faire quoi ?
Pas trouve de commande pour afficher une ligne en debug soit devoir activer TOUT le mode debug dans la config de kodi.

Et je decouvre le probleme du retour arriere ..... Quelqu'un a une solution ?

**Comment by LordVenom** [comment]
xbmc.log et activer le mode debbug on pour le soucis j'ai toujours pas trouver.

**Comment by johngf** [comment]
Pareil sans le mode debug xbmc.log fonctionne pas

**Comment by LordVenom** [comment]
J'ai tester exodus US il n'a pas de soucis mais beaucoup d'addon l'ont

**Comment by TmpName** [comment]
Ha oui le coup des *.fi files.
Tu aurais une page qui donne des infos sur ces fichiers ?
J'ai fais une recherche sur leur forum : 3 personnes qui en parlent et aucune reponse pour les 3, (com d'hab vous me direz ...)

**Comment by johngf** [comment]
Je me rappelle plus des pages que j'avais lu pareil 2 ou 3 mais les fichiers fi contenait l'adresse de chaque repertoire visité et d'autres truc en binaire et un nouveau fichier est crée a chaque fois

**Comment by TmpName** [comment]
Ha ca , je sais pas ou il l'ont mit, mais je peux te dire que par defaut c'est pas utilise.

**Comment by johngf** [comment]
Apres quand j'ai test la 17 il y avait un soucis de dialog de config.py ligne 188 si je souviens bien
Dialog2 etc.....

**Comment by johngf** [comment]
Je pense qu'il parle de ça a un moment ht tps://github.com/xbmc/xbmc/pull/11582

**Comment by TmpName** [comment]
Je jetterais un oeuil demain, sinon me faut aussi voir comme @LordVenom si le prb est abscent sur exodus.
ca voudrait dire que c'est codable.

**Comment by johngf** [comment]
je viens de remarqué un soucis a l'install avec script.common.plugin.cache

**Comment by LordVenom** [comment]
J'ai juste modifier le dossier de destination de kodi17 avec ce system la v16 et 17 utilise les même dossier utilisateur et donc le même vStream.

Bon comme j'ai formater depuis j'ai plus du tout la v16.

**Comment by johngf** [comment]
ah ok bien si ça t'intéresse j'ai posté la version portable de kodi 16 en fr il reste juste a y installé vstream
et édité le raccourcis bureau a l'intérieur pour qu'il corresponde au chemin répertoire ou il sera C:\ ou etc..
http://uptobox.com/2oc44mnv5q1n

**Comment by LordVenom** [comment]
J' ai modifier themoviedb_org uniquement pour la recherche alluc ça tourne mais la ça vas etre chaud pour la recherche global j'ai même pas une idée de comment faire.

**Comment by johngf** [comment]
la recherche normal ne fonctionne pas sur alluc mais a partir de the moviedb ou recherche visuelle si qu'est-ce qui fonctionné pas avec alluc avec the movie db ?

**Comment by LordVenom** [comment]
Pardons la recherche visuel uniquement pour le moment.

avec l'ancienne version recherche visuelle alluc puis dans un des dossier de reponse quand tu revient popup de recherche.
avec la nouvelle ça revient dans la liste non ?

si je resous le prob comme ça il vas falloir modifier tout les sites impossible de déclarer sSearch de la fonction showmovie.il faudras passer par un SetProperty. Je cherche un autre moyen mais pour le moment nada

**Comment by johngf** [comment]
avec la nouvelle quand je recherche visuelle/alluc j'ai 2 fois le dialog progress a la suite au début aprés c'est ok

**Comment by LordVenom** [comment]
J'ai vus mais c'est un moindre mal et je sais pas d'ou ça vient.

**Comment by LordVenom** [comment]
si tu trouve comment déclarer sSearch je suis preneur sinon modif sur tout les sites pas enorme mais quand même.

**Comment by johngf** [comment]
mais il y a comme meme plein erreur dans le log et plus de cache on dirait

**Comment by LordVenom** [comment]
Ben j'ai bien fait le tour et sur tous ceux que j'ai tester y a que ça qui ma retourner un résultat correct.

**Comment by TmpName** [comment]
@johngf un grand merci pour le log notice ^^, je le rajoute direct dans le fichier config de Vstream, trop utile pour moi.

**Comment by LordVenom** [comment]
Je parle du refresh de la popup quand ont fait back.

**Comment by johngf** [comment]
Et des fois quand on fait back le clavier de recherche s'ouvre

**Comment by TmpName** [comment]
Ben j'ai pas de popup ?
Je clique sur un film, je choisis alluc, ca m'affiche des liens, si je clique sur back, je reviens a la recherche visuelle avec toute les affiches de films ?
Peut etre parceque j'ai remis le vieux theme ?

**Comment by johngf** [comment]
Avec les deux theme c'est pareil alluc hs a partir de recherche allucc pas recherche visuelle
La modif crée 2 dialog progress d'affillé

**Comment by TmpName** [comment]
Ben meme comme ca.
"recherche" / "recherche alluc" / je tape "taken" / Ca m'affiche une liste de lien (quasi que du openload) / back / retour a la fenetre "Recherche".

**Comment by LordVenom** [comment]
Pardons la recherche visuel uniquement pour le moment.

avec l'ancienne version **recherche visuelle alluc puis dans un des dossier de reponse** quand tu revient popup de recherche.
avec la nouvelle ça revient dans la liste non ?

si je resous le prob comme ça il vas falloir modifier tout les sites impossible de déclarer sSearch de la fonction showmovie.il faudras passer par un SetProperty. Je cherche un autre moyen mais pour le moment nada

**Comment by LordVenom** [comment]
Bon ben ça donne rien de concluant ***** de Kodi.Si il faut modifier tous les exec c'est la merde.

**Comment by johngf** [comment]
Ça fonctionne pas sans le exec ? Comme j'avais fait pour importer un hoster ?

**Comment by LordVenom** [comment]
ben je test mais je suis null en import

**Comment by Allonsbon2004** [comment]
Salut,
Je signale un petit soucis avec La V17 (kodi OSMC) et Vstream. Ceci concerne les captchas. Le texte apparait furtivement en haut de l'écran mais disparait lorsque le clavier est à l'écran. Donc impossible à mémoriser et saisir. Bon courage pour les modifs à faire

**Comment by johngf** [comment]
@Allonsbon2004 d'apres @TmpName  c'est a cause du theme install l'ancien theme de kodi confluence tu pourras résoudre les captchas

**Comment by Allonsbon2004** [comment]
Merci. Nickel avec Confluence

**Comment by LordVenom** [comment]
Bon j'ai renvoyer la modif + un modif de default.py chez moi ça tourne j'ai toujours le chargement 2 foix mais ça c'est rien du tout même sur exodus ça merdouille.Par contre pour la recherche global ce system ne vas pas fonctionner.

**Comment by LordVenom** [comment]
Bon leur kodi et buguer même Exodus si tu fait une recherche 1 chance sur 2 que ça passe pas et quand tu fait back la recherche s'affiche.Bref impossible de coder quelque chose dans ces conditions tester sur le nouveau theme et confluence.

**Comment by johngf** [comment]
Bah oui je suis sur que le soucis viens du faite qu'il n'y plus de cache dans temp fichier .fi a voir si il vont le remettre avec la 17.1

**Comment by TmpName** [comment]
C'est pas gagne, shani08 a propose une modif pour que cela refonctionne, mais pas encore fonctionnel.
Par contre y a de plus en plus de remonte de ce probleme, ils vont peut etre comprendre que c'etait debile de le retirer.

**Comment by johngf** [comment]
@TmpName ton probleme de cache ne viendrait pas du fait que tu accede a vstream par un racourcis
Favoris ?

**Comment by TmpName** [comment]
Yes ^^.
C'est peut etre ca alors, en fait j'ai Vstream en extension favoris "Sous menu Video de la page d’accueil". Il est en permanence sur la page d'accueil de Kodi.

**Comment by Kodigoal** [comment]
Ca restera rétro compatible vStream pour les versions Kodi 14/15.2  vu les modifs éventuelles pour Kodi 17 ?

**Comment by TmpName** [comment]
Je pense que oui, ce qui marchait avant marchera encore, mais les nouveaux ajouts risquent de ne pas tourner, eg nouveaux hosters.

**Comment by johngf** [comment]
ex: vid lox fonctionne que sur la 17

**Comment by Kodigoal** [comment]
Ok merci , un peu testé kodi 17 , sans revenir au theme confluence j'adhère pas trop xD.

**Comment by johngf** [comment]
moi je resterai sur le 16.1 jusqu'a ce qu'il n'y ait plus de bug

**Comment by johngf** [comment]
sinon sur la 16 onglet recherche: alluc_ee fonctionne chez vous moi on dirait que ça load les sites

**Comment by LordVenom** [comment]
Vas falloir attendre la 17.1 pour être sur. Le cache et désactiver sur la 17 il sont ou courant.

https://github.com/xbmc/xbmc/commit/fb8a030af142ed7717e010a696c01e9a2faa7397

**Comment by johngf** [comment]
peut etre avec la beta mais avec la master que j'ai réinstallé et supprimer tous cache a jour c'est hs

**Comment by TmpName** [comment]
@Kodigoal de toute facon meme sous la V17 sans le theme confluence pas de captcha.

**Comment by LordVenom** [comment]
Tester avec free-telechargement/films/ films sd les plus vue/Hunder games aucune source ne fonctionne pas d'image pour le capcha sous confluence Kodi 17

**Comment by johngf** [comment]
bon j'ai trouvé pourquoi il ne fonctionne pas c'est parce qu'il est en mode false dans settings
et comme il n'apparait pas dans les paramètres de vstream on ne peut pas le mettre true 
obligé de le faire manuellement

**Comment by LordVenom** [comment]
@johngf Le system alluc ne verifie pas si il et activer ou pas pour le lancer c'est un import.

**Comment by johngf** [comment]
si je met pas true dans settings (test les 2 fichier settings) il ne s'affiche meme pas dans les sources et fonctionne pas
https://vid.me/8nAL

**Comment by LordVenom** [comment]
ok y a un bug dans home.py il devrais etre coder code dans site/themoviedatabase

**Comment by LordVenom** [comment]
ok si je modifie

"<setting visible="false" id="plugin_alluc_ee" type="bool" label="active alluc" default="false"/>"

par

"<setting id="plugin_alluc_ee" type="bool" label="active alluc" default="false"/>"

Que j'active ensuite alluc dans les paramettre ça fonctionne.

**Comment by johngf** [comment]
oui par contre il faut peut etre le mettre defaut true comme les autres

**Comment by LordVenom** [comment]
J'ai envoyer un commit et il faudrais modifier themoviedatabase qui et mal coder.

**Comment by LordVenom** [comment]
@TmpName Point 3 tu peux pas modifier le type d'affiche avec le nouveau theme; a tester

gui.py ligne 48

`CONTENT = 'files'`
par
`CONTENT = 'addons'`

fonctionne uniquement sur la v17

**Comment by johngf** [comment]
sur themoviedatabase le soucis c'est la parti allucsearch ?

**Comment by LordVenom** [comment]
oui elle et coder en import et devrais utiliser la function VstreamSearch, la popup devrais sauter plus de vstream ou alluc mais direct la popup des films, series et la ajouter alluc en disp10, je sais pas si suis clair lol

**Comment by johngf** [comment]
alluc se retrouverait sur la popup choix film serie etc.... 1 popup en moin

**Comment by LordVenom** [comment]
exacte et tous seras gerer pas recherchehandler

**Comment by johngf** [comment]
par contre le extratitle est vraiment nécessaire pour alluc ?

**Comment by TmpName** [comment]
Yep, j'ai eu le prb d'affichage mais unquement sur leur theme foireu, sur confluence plus aucun prb (pour le moment) donc je sais pas si il vaut mieux utiliser ta modif, ou qu'ils fassent un truc potable.

**Comment by johngf** [comment]
chez moi la modif qui avait était faite sur les 2 theme ça fonctionné pas

**Comment by johngf** [comment]
j'ai commencé une modif pour viré une popup ça a l'air de fonctionner
[ici](https://github.com/johngf/divers/tree/master/test2)

**Comment by spcxsat** [comment]
Salut,

c'est quand meme marrant on arrive d'avoir le capcha que sur DDL-Island avec la v17 mais pas sur les autres sites

**Comment by johngf** [comment]
@spcxsat lis plus haut c'est a cause du theme

**Comment by TmpName** [comment]
Les captcha marchent sur ddlisland  avec la V17 ?

@johngf Pour cette ligne, pour moi il vaut mieux trop de resultats que louper les bons, mais tu peux la commenter, on testera . Apres si vraiment ca gene, on verra a l'usage, franchement c'est tellement vieux que je me souvient meme plus pkoi c'est la, peut etre a cause d'un seul site qui n'existe meme plus.

**Comment by spcxsat** [comment]
Oui ils fonctionne avec le thème d'origine de la V17 on a l'image avec les chiffres et les lettres
Et quand on les tapes on peu bien faire partir le film.

**Comment by Allonsbon2004** [comment]
Pas de captcha avec thème confluence sur Free telechargement en V17, mais OK sur DDL. Autrement un peu hors sujet mais impossible d'installer un addon depuis Super Repo krypton. Vous confirmez ?

**Comment by TmpName** [comment]
Bon pr le captcha qui ne s'affiche pas sur la V17
ERROR: CFFmpegImage::ExtractFrame: Could not decode a frame
ils utilisent leur propre version de la lib, et evidement la leur deconne, l'image se charge mais leur codec n'aime pas le format. Donc soit on attend en croisant les doigts, soit faut editer le fichier apres l'avoir dl pour corriger le truc.

**Comment by johngf** [comment]
Vous avez test la modif alluc 7 post plus haut ?

**Comment by TmpName** [comment]
Il faut quoi pour tester, procedure ?
Recherche globale / visuelle ? (Vu que moi j'ai jamais de prbs ...)

**Comment by johngf** [comment]
Recherche visuelle popup recherche alluc

**Comment by LordVenom** [comment]
Ha ben j’attender que tu post sur la bêta moi, je regarde ça.

**Comment by johngf** [comment]
Par contre la popup chargement affiche init etc... au lieu du nombre lien mais ça c'est normal 
elle ne load que alluc ee pas les autres

**Comment by LordVenom** [comment]
Hum oui bizard les autre recherche n'affiche pas les ignorer ou j'ai jamais fait gaffe.

**Comment by johngf** [comment]
Moi init s'affiche toujour meme sans la modif d'ailleurs dans choix multiple il y a init

**Comment by LordVenom** [comment]
Faudrais que je voie je voudrais bien m'inspirer de la fonction searchGlobal
https://github.com/Lynx187/plugin.video.xstream/blob/master/xstream.py

**Comment by johngf** [comment]
Bah en faite elle est utile vu que la reccherche global ne cherche pas sur tous les sites pour chaque fonction
Film serie anime doc il manque le choix label pour bcp de site

**Comment by LordVenom** [comment]
Je suis entrain de refaire la fonction 2 ou 3 jour avant test.

**Comment by johngf** [comment]
alluc si tu recherche trop a la suite tu as droit a cloudflare ça c'est ok 
mais des fois recaptcha et la c'est HS pendant x temps heure/ jour je ne sais pas
reponse 403 forbidden

**Comment by LordVenom** [comment]
Refonte total de la recherche, Faite des test regarder si j'ai louper un truc c'est un peux hard.

Maintenant y 2 import 1 qui teste si y a bien une recherche 1 qui fait la recherche pas de ralentissement sur l'addon.

**Comment by johngf** [comment]
a chaque clique sur un dossier ou appelle d'une fonction showmovie showhoster
Prochaine verification de MAJ le : etc...

`07:38:12 T:1160  NOTICE: 	[PLUGIN] Vstream: load site etc... and call function showMovies
07:38:15 T:1160  NOTICE: 	[PLUGIN] Vstream: Prochaine verification de MAJ le : 2017-02-18
07:38:16 T:1160  NOTICE: 	[PLUGIN] Vstream: close dialog
07:38:16 T:1160  NOTICE: 	[PLUGIN] Vstream: Table initialized
07:38:17 T:576  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
07:38:17 T:576  NOTICE: 	[PLUGIN] Vstream: load site etc... and call function showMenuFilms
07:38:18 T:576  NOTICE: 	[PLUGIN] Vstream: Prochaine verification de MAJ le : 2017-02-18
07:38:18 T:576  NOTICE: 	[PLUGIN] Vstream: Table initialized
07:38:19 T:1660  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
07:38:19 T:1660  NOTICE: 	[PLUGIN] Vstream: load site etc... and call function load
07:38:19 T:1660  NOTICE: 	[PLUGIN] Vstream: Prochaine verification de MAJ le : 2017-02-18
07:38:19 T:1660  NOTICE: 	[PLUGIN] Vstream: Table initialized
07:38:23 T:3716  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
07:38:23 T:3716  NOTICE: 	[PLUGIN] Vstream: load site etc... and call function load
07:38:26 T:3716  NOTICE: 	[PLUGIN] Vstream: Prochaine verification de MAJ le : 2017-02-18 
07:38:26 T:3716  NOTICE: 	[PLUGIN] Vstream: Table initialized
07:38:27 T:1972  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
07:38:27 T:1972  NOTICE: 	[PLUGIN] Vstream: load site etc.... and call function showMovies
07:38:28 T:1972  NOTICE: 	[PLUGIN] Vstream: Prochaine verification de MAJ le : 2017-02-18 
07:38:29 T:1972  NOTICE: 	[PLUGIN] Vstream: close dialog
07:38:29 T:1972  NOTICE: 	[PLUGIN] Vstream: Table initialized`

**Comment by LordVenom** [comment]
Réparer

**Comment by johngf** [comment]
par contre l'option plugin parametres quand on le ferme refresh la page et erreur dans le log
XFILE::CDirectory::GetDirectory - Error getting 
CGUIMediaWindow::GetDirectory

**Comment by johngf** [comment]
sinon pour la recherche mise a part les 2 import ça ma l'air pareil qu'avant

**Comment by TmpName** [comment]
Ben surtout si dans 15 jours la kodi team revient en arriere, tout ca aura servi a rien, je vois pas les avantages de la nouvelle version, mais je la teste par morceau ( pas installe l'integralitee)

**Comment by johngf** [comment]
La modif de la recherche n'a rien avoir avec les 2 popup c'est a part et ne résout pas le soucis de l'abscence de cache

**Comment by LordVenom** [comment]
@sinon pour la recherche mise a part les 2 import ça ma l'air pareil qu'avant

Tu peux être plus précis le post fait 90 messsage la modif n'a pas changer l'import init ? moi je le voie plus.

La recherche ne fonctionne plus depuis recherchehandler mais depuis default ça éviter les import hors default. Alors même si au l'utilisation y a pas de différence pour le suivis du code c'est plus propre.

**Comment by johngf** [comment]
Bah pas de bug sur la recherche comme avant
