### ISSUE TITLE
Simple iptv

### ISSUE THREAD

**Issue by mmtest1** [Kodi-vStream/venom-xbmc-addons#900]
Bonjour,
depuis la dernière mise à jour touchant la web2tv il est de nouveau possible de regarder la tv depuis vstream - tv du web (un grand merci) mais je l'utilise également par l'addon simple iptv à l'adresse suivante https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons/master/repo/resources/webtv2.m3u, la liste des chaînes apparaît bien mais seul arte se lance, les autres : france2, 3, 4, 5, ..... restent inactivent.
Est-ce-que l'url de la liste des chaîne m3u a été modifiée ? Ou bien la nouvelle technique de contournement des protections est incompatible avec l'extension simple iptv ?
Merci pour le suivi et un grand merci pour votre extension qui nous redonne un peu de pouvoir sur la tv

**Comment by TmpName** [comment]
Gagne.
En fait maintenant les url "bougent", elle changent a chaque connexion, et il faut recuperer un token.
L'avantage c'est qu'elle sont officielles et donc fiables, l'inconvenient c'est qu'elle ne sont plus compatible avec l'iptv.
La serie tf1 lc1 ect va revenir aussi mais toujours non compatible avec l'iptv, dsl.

**Comment by mmtest1** [comment]
Merci pour le suivi,
dommage pour simple iptv qui permettait de bien intégrer la tv à kodi
encore merci d'avoir rétabli la fonction tv, seul moyen d'accès à la tv chez nous
bonne continuation

**Comment by TmpName** [comment]
TF1 en place
