### ISSUE TITLE
Série Télé probleme

### ISSUE THREAD

**Issue by johnboisvert** [Kodi-vStream/venom-xbmc-addons#904]
Bonjour,
suis-je le seul quand je vais dans Séries populaire ca menvoit un message d'erreur comme ca
![20170208_124625](https://cloud.githubusercontent.com/assets/25285509/22750857/53be6002-ee00-11e6-987a-a730e8a9c52c.jpg)

Merci gang !
en passant vous etes sur la grosse coche !

**Comment by johngf** [comment]
Kodi 17 a des soucis avec vstream il n'est pas conseillé pour le moment

**Comment by johnboisvert** [comment]
Je me rappel pas d'avoir fais la mise a jour de Kodi 16 à Kodi 17... il y a un moyen de retourner au 16 alors ? Merci John de ton aide

**Comment by johngf** [comment]
Verifie ta version apres je me trompe peut etre c'est addiciel qui ma induit en erreur tu est en langue canadien

**Comment by johnboisvert** [comment]
Oui c'est bien la version 16 que j'ai 
ca fonctionnais avant j'ai changer aucun setting etc...

**Comment by Allonsbon2004** [comment]
Salut,
Pas de soucis chez moi. Essai avec supernatural SO1E01 via youwatch OK, bien que je sois en V17

**Comment by LordVenom** [comment]
Y a une liste de lecture dans vStream ? je savais même pas.

**Comment by TmpName** [comment]
Lol, c'est clair, comment on fait pour arriver la ?

**Comment by johnboisvert** [comment]
Bonne question c'est dans Kodi je click vstream serie populaire et paff ca s'enva la avec un erreur 
tres bonne question lol

**Comment by johnboisvert** [comment]
C'est depuis l'update vstream que ca me fais ca il m'arrive toujours des chose bizzare :P

**Comment by TmpName** [comment]
Mais j'ai pas ca moi ?
Quelqu'un a code une version alternative ^^ ?

**Comment by johnboisvert** [comment]
Pourtant c'est le code principale de vstream ca va surment ce regler à la prochaine mise à jour 
je comprend pas j'ai le ponpon? :P

**Comment by johngf** [comment]
Je pense que tu as ajouté des fichier a la liste de lecture de kodi c'est ça @johnboisvert ?

**Comment by johnboisvert** [comment]
non je n'est rien rajouter je roule avec ca depuis le début mon ami

**Comment by Kodigoal** [comment]
J'ai pareil quand vstream plante parfois ou kodi bug , ca ramène à cette page menu vidéo. ( kodi 15.2).
Relance vStream et c'est ok.

**Comment by johnboisvert** [comment]
J'ai fermer Kodi p-t 5 fois et ca me refais toujours ca juste dans cette option et j'ai Kody 16.1

**Comment by Kodigoal** [comment]
Recherche visuelle puis serie populaire ? 
Pas de soucis non plus de mon côté...

**Comment by TmpName** [comment]
Franchement je ne vois que 2 solutions.
Modifier tes listes de lectures via kodi, supprime celle qui concerne Vstream (si il y en a une).
Re-installer Vstream, apres l'avoir supprime.

**Comment by LordVenom** [comment]
Des nouvelles ?

**Comment by johnboisvert** [comment]
J'ai du enlever la mise a jour 4.9 et remettre la 4.7 pour que tous fonctionne 
j'attenderai donc la mise a jour 5.0 voir si ca regle :) ca ma fais ca sur mes 2 box android

**Comment by LordVenom** [comment]
Perso j'aurais supprimer vstream et détruit le dossier restant pour réinstaller la v4.9 vue qu'on l'on a pas trouver tu auras le même soucis en 5.0

**Comment by johnboisvert** [comment]
D'accord donc je suprime vstream et je retelecharge le .zip sur ce site ? (Plus réscente mise a jour) https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository  Merci

**Comment by LordVenom** [comment]
Oui tu installe le repo puis tu télécharger vstream depuis "installer depuis un repository"

**Comment by johnboisvert** [comment]
Si je telecharge le .zip sur https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository
c'est la mise a jour réscente 4.9 ? donc je la met sur une clef USB et je fais installer via un .zip ca fonctionne ? désolé je suis nul

**Comment by LordVenom** [comment]
https://www.youtube.com/watch?v=1uS5gbd8jpE&t=3s

que tu soit en kodi v16 ou 17 l'installer et quasi pareil.

**Comment by johnboisvert** [comment]
c'est normal que le .zip c'est la mise a jour 4.8 et non 4.9 ?

**Comment by johnboisvert** [comment]
J'ai fais la procédure sur mes 2 box la ca fonctionne mais quand je clique sur la prochaine page ca m'apparais l'erreur de regarder le journal je comprend pas

**Comment by Kodigoal** [comment]
Si tu peux mettre ton log Kodi sur pastebin quand t'as ton erreur là.
Relance pas vStream après l'erreur sinon il genere un nouveau kodi.log et on verra pas l'erreur dedans.
Localise kodi.log et copie/colle le sur pastebin en mettant le lien ici, voir si on trouve ce qui cloche chez toi.
Aide pour localiser le kodi.log:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by johnboisvert** [comment]
Apres désinstallation réinstallation 3 fois ca la marché je vous remercie énormément !!! :D 
j'ai une derniere question qui na pas rapport avec ca mais que je cherche depuis une semaine vue vous etes ca coche peut-etre que vous savez vous pouvez me repondre ici ou par email john.boisvert@hotmail.com 
J'ai kodi sur ma box avec vstream mes 2 freres aussi et je met a jour leur kodi avec des option etc.. est-ce qu'il y a une facon de faire une sauvegarde kodi avec un option mise a jour direct sur un hébergeur quand je fais une mise a jour ils peuvent la faire via le site ou via ma box svp ?
