### ISSUE TITLE
Soucis touche retour info film-serie

### ISSUE THREAD

**Issue by Kodigoal** [Kodi-vStream/venom-xbmc-addons#905]
Quand on affiche les informations (via popup menu) d'un film/série,
ca affiche en plein ecran avec bouton si  résumé/casting/bande Annonce/ et tout à droite
bouton ( ya rien marquer dessus) pour fermer la popup , plus image en fond si dispo.
Avant ou pouvait fermer l'ex popup avec touche retour ( sous tel android ou box android avec telecommande pour ma part).
La,  la touche retour ne fonctionne plus pour fermer la popup, faut se déplacer sur le bouton pour fermer, pas pratique ...
Mais si on remet '92' dans le code suivant ( config.py)
def onAction( self, action ):
                if action.getId() in ( 9, 10, 11, 30, 247, 257, 275, 61467, 61448, ):
                    self.close()
La touche retour ferme à nouveau la popup information.
Ya eu un commit ou a été enlevé  les nombres (92,216).
On peut les remettre en place ou ca va poser problème quelque part?

**Comment by johngf** [comment]
chez moi ça fonctionne la touche retour tu as quel version de kodi ?
![screenshot001](https://cloud.githubusercontent.com/assets/21311232/22851705/dd4aea3a-f02a-11e6-9d5c-6ba309fba2a7.png)

**Comment by Kodigoal** [comment]
Version Kodi 15.2
Pas de touche Echap sous Android/kodi dispo pour ma part , pour naviguer obliger d'utiliser retour arrière sur tel ou box telecommande.
Et si on remet 92( = ACTION_NAV_BACK) , c'est ok.
Le mode plein écran des infos ca doit jouer.

**Comment by TmpName** [comment]
Si le prb c'est la touche esc (qui sert beacoup sur kodi) pkoi tu la configures pas sur ta telecommande simplement ? plus de touches dispos, ou non detectees par kodi ?

**Comment by Kodigoal** [comment]
C'est pas la touche esc... j'en ai pas sous android.
C'est retour arrière qu'on utilise via tel ou box.
Ma telecommande fournie ya que retour arrière en plus.
Après je rajoute juste ' 92 ' de mon côté et c'est ok de nouveau.
C'était pour savoir si on peut le remettre dans le  code ou si je fais la modif juste chez moi xD

**Comment by LordVenom** [comment]
Pas de raison particuliere je vais poster la modif juste avant tu peux tester ligne 625 de skin/default/720/dialoginfo.xml

"<label>15067</label>"

par

"<label>$LOCALIZE[15067]</label>"

**Comment by Kodigoal** [comment]
@LordVenom Testé mais ca n'affiche toujours pas 'Fermer'
Si je change la valeur en 20410 ( = Bande Annonce) ou 31127 (TvTunes) ca s'affiche ses valeurs.
Mais il va chercher ou ce 15067 ? ca vient avec les infos tmdb ?

**Comment by LordVenom** [comment]
https://github.com/xbmc/translations/blob/master/kodi-translations/kodi-main/merged-langfiles/kodi.core/resource.language.fr_fr/resources/strings.po

**Comment by LordVenom** [comment]
Je comprend pas ça devrais fonctionner, si tu met 30033 ça affiche Outil ? si oui je modifirais pour creer un language dans l'addon directement.

**Comment by Kodigoal** [comment]
Ca doit kodi 15.2 , j'ai réinstallé la langue fr , il me telecharge la version 1.0.6 , et vu ton lien  la version actuelle est en 3.0.11  ...
Sur toutes mes installs kodi 15.2 , il me telecharge la 1.0.6 ou ya pas la valeur label 15067 dans strings.po
Doit se baser sur un ancien repo pour telecharger sous 15.2.
Ou rajouter cette valeur en dur dans le string.xml Fr/En pêtre?
Je vais encore bidouiller voir le lien qu'il telecharge en installant la langue, bizarre ce bug.

**Comment by Kodigoal** [comment]
ok en fait sous kodi 15.2 ( version android , autre os pareil surement) il prend le dépot suivant :
http://mirrors.kodi.tv/addons/isengard/resource.language.fr_fr/
Et on est en version 1.0.6 max en language fr ou ya pas la valeur 15067 (Fermer).
On peut le mettre en dur dans le strings.xml pour Fr/En et dans le label on met:
<label>$ADDON[plugin.video.vstream 30033]</label>
Ca affiche bien 'Outil' là.
Pas génant pour moi le soucis 'fermer'  perso, après si faut garder une certaine rétro compatibilité , à voir.
Plus la touche arrière qui manque ^^

**Comment by LordVenom** [comment]
Résolut dans la prochaine version.

**Comment by Kodigoal** [comment]
Testé ok, merci xD

**Comment by johngf** [comment]
par contre des fois la nouvelle fenetre ne fonctionne pas et affiche l'ancienne fenetre mais vide

**Comment by LordVenom** [comment]
Normal si pas d info trouver c est la popup de base vide . mais ça serais plus logique de faire un message pas d info trouver c est vrais.

**Comment by TmpName** [comment]
Question !
Est qu'il y a des cas ou ca affche la vielle fenetre mais pleine ?

Il suffirait de remplacer tout les "xbmc.executebuiltin("Action(Info)")" par un popup, mais j'aimerais etre sur qu'il n'y ait pas de prbs (eg si meta active ou pas)

**Comment by johngf** [comment]
J'ai eu des fois pas pleine juste la thumb du film

**Comment by TmpName** [comment]
Ben vla c'est pour ca que j esite.
Tu peux l'avoir vide avec jsute le thumb et un lien au format pluggin.
Mais si les infos sont deja dans kodi, tu peux aussi avoir la vielle version mais pleine, mais ca depend de tellement de trucs que je ne sais pas comment ca se produit.

Et il y a aucun moyen de savoir si elle va etre pleine ou vide vu que c'est kodi qui gere tout.

**Comment by LordVenom** [comment]
Click sur info de la télécommande ou I du clavier = fenêtre d'info du skin peux importe si meta activer ou pas donc vide ou pleine.

Click sur le context information peux importe si meta activer ou pas il vas cherche les infos sur TMDB et affiche la popup de l'addon ou extendedinfo si activer.
Si TMDB  plante pour une raison indeterminer except: affichage de la popup skin si pas imdb_id un popup d'information "erreur pas d'info".

**Comment by TmpName** [comment]
Et on peut pas avoir le cas ou tmdb plante, mais que les infos soit deja dans kodi, et donc affichage possible ?
Quoique statistiquement, avant que ca arrive ....

**Comment by LordVenom** [comment]
Hum... Il vas chercher dans la base de donner avant d'allais sur l'api.Et dans tous les cas imdb_id seras vide et ça retourneras "erreur d'info" mais si tu as trouver un code plus propre pas de soucis pour moi fait toi plaisir :)

Note : Perso j'utilise cette fonction pour les résumer et le fanart.

**Comment by TmpName** [comment]
J'ai mit une modif en test.
Mais pr les tests... j'ai des soucis d'affichage du dialog, mise en page, mais ca a l'air de marcher.

**Comment by johngf** [comment]
dites on pourrait pas mettre en veilleuse comme j'ai fait sur siteuptobox ? popu silencieuse
les popup d'erreur et autres il y en a souvent avec vstream
je dois pas etre le seul a qui ça prend la tete le son de confluence(pas tester avec le nouveau theme

**Comment by zombiB** [comment]
dans parametres systeme -audio-tu peux désactiver le son de l'interface graphique ou gui sounds

**Comment by johngf** [comment]
@zombiB ça desactive tous les sons ce n'est pas ce que je veut  je parle des popup erreur

**Comment by TmpName** [comment]
Moi ca me derange pas mais il y a xbmcgui.Dialog().notification

http://mirrors.xbmc.org/docs/python-docs/stable/xbmcgui.html#Dialog-notification

Tu peut desactiver le son dans cette api, mais j'ai pas teste donc je connais pas les differences.

**Comment by johngf** [comment]
Par default c'est optionel le son et si il n'y a pas l'argument c'est toujours true 
Donc oui ça serait possible avec checkbox activer desactiver dans settings

**Comment by TmpName** [comment]
Si le boss valide, je peux m'en occuper demain je pense. Et perso je partirais sur la chackbox a cocher ou pas, je vois pas pkoi certaines notifications aurait plus besoin d'un son qu'une autre, meme si perso moi ca me derange pas.

**Comment by LordVenom** [comment]
ça me dérange pas non plus avec ou sans pas de soucis.

**Comment by TmpName** [comment]
J'ai rajoute une section divers dans le menu de config du coup.
A tester.

**Comment by johngf** [comment]
j'étais dessus aussi je cherché comment convertir true en True sans ajout de code

**Comment by TmpName** [comment]
Ben pour les erreurs le son me semble normal, en temps normal pas d'erreurs > pas de sons.

**Comment by TmpName** [comment]
Bon j'ai remodifie le code.
Meme si l'user a tout laisse par defaut (son on), il y a moyen de desactiver les son en mettant flase dans la fonction, pour les notification unitile (sous titre, authentification, ect ...)

**Comment by johngf** [comment]
un bon exemple de prise de tete avec le son de confluence pour moi
c'est de regarder plusieurs épisodes d'une série a la suite ou le volume doit etre augmenté car bas
donc on le fait au premier épisode ensuite on oublie de le baisser(ou alors c'est chiant monté et descendre le volume) et au prochain episode
resolve ouverture du flux le son de confluence a fond!

**Comment by TmpName** [comment]
XD, je comprend.
