### ISSUE TITLE
Suggestion : papystreaming

### ISSUE THREAD

**Issue by Ronaldonizuka** [Kodi-vStream/venom-xbmc-addons#915]
Bonjour à tous, 
Je pense que vous connaissez déjà, mais mon cousin m'a parlé d'un site de streaming ou il y a plein de source par film. Alors je n'ai pas pu m'empécher de pensez à vous.  (ht tp://papystreaming.com/fr)
Désolé si la source a déjà été proposé. 
Aussi le boss m'avait parlé d'un remplaçant pour la source HD-stream.in (du HD en lien direct et un choix exceptionnel... c'était la belle époque), qui est ce fameux remplaçant. 
Encore merci pour tout votre travail ! A bientôt.

**Comment by johngf** [comment]
il y a papystreaming .org dans vstream qui fonctionne, le tiens ne donne pas de lien utilisable par vstream passe par cacaoweb #797
