### ISSUE TITLE
1fichier resolve impossible

### ISSUE THREAD

**Issue by baaaaaziiiiingaaaaa** [Kodi-vStream/venom-xbmc-addons#917]
Bonjour,

J'ai un compte premium chez 1fichier et en passant par vstream il m'est impossible de télécharger ou de visualiser alors que mon lien est valide.
J'ai enlevé le SSL pour télécharger plus vite sur l'ordinateur et mon compte est bien configuré sur vstream.

Merci d'avance

**Comment by johngf** [comment]
il faut pas enlever le ssl 1fichier fonctionne en https

**Comment by TmpName** [comment]
Dans le fichier onefichier.py
`Mode = {'dl_no_ssl' : 'on' }`

Mais je sais pas si le difference se ressent, d'apres leur site il disent que oui mais jamais teste.

Apres j'ai pas pu tester encore, j'ai plus le menu de configuration dans Vstream ???

**Comment by johngf** [comment]
Moi j'ai fait un test sans rien touché ça fonctionné

**Comment by baaaaaziiiiingaaaaa** [comment]
Bonjour,

Il y a une grosse différence avec un gestionnaire de téléchargement comme IDM sur pc. Je passe de 800ko en 1 connexion à 50méga en 8 connexions.

**Comment by TmpName** [comment]
Bon alors y a du gros dossier qui arrive avec la V17, la gestion du ssl.

@baaaaaziiiiingaaaaa remplace les 2 fichiers, onefichier.py et premionhandler.py et resteste.

Et je viens de voir que moi aussi j'ai desactive le ssl dans les parametres de mon compte, c'est peut etre ca qui fait que ca fonctionne chez @johngf.

**Comment by TmpName** [comment]
Si tu veux tester le premium @johngf, tu as une case a cocher dans ton compte pr debloquer 10Giga pr tester.

Mais du coup ca m'interesse aussi de savoir si j'ai pas case le mode gratuit avec mes bidouilles.

**Comment by johngf** [comment]
Sur la 16.1 il y a un moment j'avais testé ssl create context ca me mettait erreur je retesterai

**Comment by TmpName** [comment]
Ha oui mince, j'ai pas pense a ca.

**Comment by johngf** [comment]
Il faudrait check la version de kodi avant

**Comment by TmpName** [comment]
Faut voir ou se trouve l'erreur. Mais avec un try/except c'est peut etre possible, surtout si ca deconne a l'import.

**Comment by LordVenom** [comment]
`cConfig().isKrypton`

return True ou False

**Comment by TmpName** [comment]
Super, deja en place avant d'en avoir besoin ^^.
Par contre je regarde le fichier config.py, ca vaudrait pas le coup de le couper en 2, les fonctions "config"  (getSettingCache,isKrypton) et les fonction "d'action" (show_busy_dialog,openerror).

Car je vois que juste pr afficher une ligne de log via CConfig().log ca lance tout le contenu de __init__. Je sais pas si kodi a tout en cache ou si a chaque fois, ca cherche sur le disque dur ?

Il y a moyen de faire MyConfig = cConfig() en debut et apres utiliser Myconfig.log, mais perso j'y pense jamais.

**Comment by baaaaaziiiiingaaaaa** [comment]
Bonsoir,

J'ai eu le droit à une mise à jour hier soir, mais sa ne marche pas.
Je n'ai pas modifié sur 1fichier pour le ssl il est toujours désactiver. 
Sur un lien valid j'ai le message "authentification rate" et "fichier Introuvable". 
Je fait des tests plus approfondie demain avec le ssl et si je trouve les logs. :)

**Comment by johngf** [comment]
donc la modif qu'a fait @TmpName sur la beta n'était pas nécessaire ça fonctionne avec l'ancien fichier

**Comment by TmpName** [comment]
Ha ?
Lol, bon alors la je sais plus quoi faire ^^.
Tu as quelle version de kodi @baaaaaziiiiingaaaaa  ?

**Comment by baaaaaziiiiingaaaaa** [comment]
@TmpName J'ai kodi 17 avec le thème chroma.
Je pense que j'ai eu le soucis quand j'ai eu le droit à la mise a jour de kodi il y à 2 semaine environ.
Pas besoin de faire de mise à jour donc.

**Comment by TmpName** [comment]
Ben j'esite, vu que chez moi ca a bien deconne aussi (mais depuis 1 semaine j'ai l'impression d'etre seul au monde avec une version bancale)

**Comment by TmpName** [comment]
Remise en place de la vielle version.
