### ISSUE TITLE
Parametres en menu contextuel.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#918]
Alors la je sais pas si ca vient de moi ou pas.
Kodi V17, theme confluence.
Quand je suis dans la page d'acceuil de Vstream, j'ai plus la fonction "paramtres" en menu contextuel.

**Comment by LordVenom** [comment]
C'est normal il et dans le menu de droite maintenant, c'est pas vstream qui creer ce menu mais kodi.

**Comment by TmpName** [comment]
Je le vois pas ?
J'ai juste options de vue/ options diverses / Actions

**Comment by LordVenom** [comment]
Arff theme confluence ? dans ce cas vas dans ta liste d'addon video et context sur vstream la tu auras les paramètres.

**Comment by TmpName** [comment]
La ca marche, mais c'est beaucoup plus de manips, c'est moi qui deconne ou c'est pareil chez vous ?

**Comment by LordVenom** [comment]
Pareil chez moi mais problème résolut avec le nouveaux home.

**Comment by TmpName** [comment]
Nickel merci.
La je galere un peu avec mes resulats, ceux de @johngf et les tiens, j'ai jamais comme vous.

**Comment by LordVenom** [comment]
Magie ? Sorcellerie ? vaudou ?

**Comment by TmpName** [comment]
Un peu de tout ca, et les devs de kodi qui veulent ma mort.

**Comment by johngf** [comment]
ça cause un bug sur la 16, sur la 17 je sais pas #899 pas trouvé la soluce

**Comment by TmpName** [comment]
Je vais faire mon boulet mais c'est pas mieux de mettre les parametres en menu contextuel ?
Je dis ca pour moi car j'ai l'affichage en mode icone et il y a pile 5* 3 icones, et en rajoutant les parametres du coup c'est plus visible.

**Comment by johngf** [comment]
Je pensais a ça aussi menu contextuel car sinon le bug sera toujour la

**Comment by johngf** [comment]
@TmpName pour ajouter le menu paramètres de l'extension a kodi 17
https://raw.githubusercontent.com/johngf/divers/master/menu.py

**Comment by TmpName** [comment]
Ben moi je prefere cette version aussi.
J'attend le feu vert de @LordVenom pour savoir quelle version on prend.

**Comment by johngf** [comment]
le check de kryton dans addDir peut etre remplacé par `if (cGui.CONTENT == 'addons'):`

**Comment by TmpName** [comment]
Oui mais si un jour modifi le code de cGui.CONTENT (sans le savoir), ca va deconner et on risque de galerer pr trouver pkoi.
Par contre je pense qu'il ya moyen d'alleger le fichier config.py

**Comment by johngf** [comment]
je disais ça vue que c'est deja dans gui https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/gui/gui.py#L51

**Comment by LordVenom** [comment]
envoyer

**Comment by TmpName** [comment]
Ha oui exact.
