### ISSUE TITLE
xstream l’ancêtre de vStream

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#919]
Je vient de faire le menage de mes favoris et la je trouve ça

https://github.com/Lynx187/plugin.video.xstream

Depuis le temps y a quand même pas mal de changement par exemple il a fait du thread une recherche global dans le fond ça reste quasi pareil mais bon j'ai tester ça tourne pas chez moi mais quelque idée peuvent être utile a nos code.

**Comment by johngf** [comment]
il est toujours maintenue ht tps://github.com/xStream-Kodi/plugin.video.xstream

**Comment by LordVenom** [comment]
Cool Merci
