### ISSUE TITLE
récupérer mot de passe

### ISSUE THREAD

**Issue by marcelus123** [Kodi-vStream/venom-xbmc-addons#920]
Bonjour.
J'ai perdu mes identifiants pour 1fichier ainsi que l'adresse mail jetable que j'avais utilisé.
Avec Vstream que j'utilise sur mon android box mon compte premium 1fichier est enregistré dans la rubrique dédiée. Mon nom d'utilisateur apparait lisible mais le mot de passe est caché par des astérisques.
Que dois-je faire pour lire ce mot de passe en toutes lettres ?.
Merci.

**Comment by LordVenom** [comment]
Bonjour, il sont stocker dans la base de donner de kodi et coder si il ont bien fait leur taff.

**Comment by johngf** [comment]
quelle machine tu as windows /android etc.... ?

**Comment by marcelus123** [comment]
Bonjour.
Merci pour votre aide.
Je fonctionne sous android. Ce mot de passe est forcément mémoriser dans un  fichier.
Ou peut-ètre y a-t-il une option qui permet de voir les mots en toutes lettres sans afficher les astérisques .
Je ne l'ai pas trouvée pour l'instant

**Comment by johngf** [comment]
des fois les fichiers sont cachés sur android a voir 
normalement  recherche ce fichier \userdata\addon_data\plugin.video.vstream\settings.xml
et ouvre le avec un lecteur tu verras 1fichier etc....

**Comment by LordVenom** [comment]
La base de donner et un fichier .db

**Comment by johngf** [comment]
regarde mon settings de sur win 7 \userdata\addon_data\plugin.video.vstream\settings.xml
j'ai mis un faux compte dans vstream
    <setting id="hoster_uptobox_password" value="daqfre" />
    <setting id="hoster_uptobox_premium" value="true" />
    <setting id="hoster_uptobox_username" value="dres" />

**Comment by marcelus123** [comment]
Je progresse grâce à vous.
J'ai installer un lecteur de fichier en mode root et je peux lire les fichiers cachés.
J'ai trouvé les fichiers setting.xml qui contient un coockie pour onefichier.
J'ai trouvé la base de données en .db mais je ne sais pas avec quoi la lire.

**Comment by johngf** [comment]
tu n'as pas trouvé le pass direct comme moi ? grace au settings.xml

**Comment by Kodigoal** [comment]
J'ai pas les login en clair dans settings.xml de mon côté ( sous android) .
Mais simplement en enlevant option="hidden"  dans la ligne suivante dans le code settings.xml:
<setting id="hoster_onefichier_password" type="text" label="30402" default="" option="hidden"/>
remplace par:
<setting id="hoster_onefichier_password" type="text" label="30402" default=""/>

En allant ensuite dans l'onglet Premium/Login,
yaura le mot de passe en clair affiché sans les étoiles.

**Comment by johngf** [comment]
il a 2 fichier settings xml @Kodigoal

**Comment by marcelus123** [comment]
Résolu !.
Merci à tous . J'ai édité le fichier settings.xml comme dit par johngf. Je ne me suis pas rendu compte tout de suite que je ne voyais pas tout le fichier sur ma TV. En descendant j'ai retrouvé mon password.
@Kodigoal : Ta méthode m'intéresse mais ton message n'est pas complet... on remplace option="hidden" par quoi ?.
En tous cas merci à tous j'ai récupéré mon abonnement jusqu'& fin mars.

**Comment by Kodigoal** [comment]
@johngf ah oui , même pas fait gaffe qu'il yen avait 2 xD désolé . Ya bien les pass en clair dedans ^^

@marcelus123  par rien. Faut juste virer dans la ligne  de code  option='hidden'.

**Comment by LordVenom** [comment]
Arff j'avais zaper ce fichier et c'est en clair dans ce fichier vive la protection !!!
