### ISSUE TITLE
Free telechargement

### ISSUE THREAD

**Issue by jeyjey43** [Kodi-vStream/venom-xbmc-addons#921]
Bonjour,

Pour la source Free téléchargement, les sous menus ne ramènent plus les sources mais simplement la lettre "h" en lieu et place.
Exemple avec le sous menu "Derniers Films HD 720p et 1080p ajoutes", en cliquant sur un film, les liens se génèrent sur plusieurs lignes et chaque ligne renvoie la lettre "h". Les liens sont cliquables mais ne génèrent rien si ce n'est une ligne vide.
Même constat avec la fonction "Recherche de films".
Merci à vous et super addon cela dit en passant.

**Comment by TmpName** [comment]
Tu dois avoir une vielle version, chez moi ca tourne mais je n'ai pas la fonction recherche par contre.

**Comment by Kodigoal** [comment]
Même soucis pourtant qui affiche 'h' ^^
Ca vient du showHoster je pense au niveau 
du if 'multi' ,  après doit afficher le sHostsname mais yen a pas dans le aResult et aEntry[0], il affiche 'h' alors ...
Je pige pas trop le code là.

**Comment by TmpName** [comment]
Tu passes par ou pr avoir le probleme ?

**Comment by Kodigoal** [comment]
Toutes les sources/ Free Telechargement / Films / Derniers Films HD 720p et 1080p ajoutes/
et je prend le film Allies.

**Comment by jeyjey43** [comment]
J'utilise la dernière version de vstream 0.4.9 avec la dernière version de kodi v17 sur Android TV. J'ai essayé sur tous mes supports et le problème est identique. Je préfère utiliser free téléchargement comme source plutôt que zone téléchargement ws car le script extended info fonctionne correctement.

**Comment by TmpName** [comment]
Nouvelle version a tester
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/free_telechargement_org.py

**Comment by jeyjey43** [comment]
Je viens de tester la modification du code. Les hébergeurs s'affichent bien. Par contre les liens premium ne sont pas affichés. Seuls les liens découpés sont affichés donc impossible de lancer une vidéo en streaming ou en lecture directe.

**Comment by Kodigoal** [comment]
@jeyjey43 Si tu peux tester cette version pour les différentes catégories films si ya des bugs, merci.
http://pastebin.com/j0q20HgX

Vite fait mais ca prend tous les liens en compte (sauf si lien non standard si yen a parfois) ..

**Comment by jeyjey43** [comment]
Impeccable. Je garde ce py dans l'attente de la mise à jour de la bêta. Merci pour la réactivité.

**Comment by Kodigoal** [comment]
Ca fonctionnera pas pour tout cette version.( catégorie sd classique erreur a gogo par ex)
Celle la devrait éviter les erreurs si lien pas standard:
http://pastebin.com/usyd0bNW
En attendant.

**Comment by chataigne73** [comment]
j'ai fait une toute petite modif sur la beta
merci de me dire si ça tourne

**Comment by jeyjey43** [comment]
Testé pour les films avec sources HD. A priori pas de problème. Ce sont bien les liens premium. 
Néanmoins, la fonction recherche ramène encore parfois des liens découpés. 
Juste pour info en ce qui concerne les séries, elles ont toutes un affichage qui commence à partir de l'épisode 2.

**Comment by chataigne73** [comment]
tu as un exemple de recherche qui ramène des liens découpés ?

**Comment by jeyjey43** [comment]
Interstellar. 
Les résultats de la recherche ramènent 7 lignes en qualité SD et quatre ligne en qualité HD. Je sélectionne la première ligne HD. Là j'ai le nom complet du fichier avec six hébergeurs. Je sélectionne uptobox qui me donne 7 liens après saisie du captcha.

**Comment by chataigne73** [comment]
en effet le cas de la recherche interstellar est intéressant...
je regarde ça de plus prêt
