### ISSUE TITLE
1fichier probleme

### ISSUE THREAD

**Issue by moimeme45** [Kodi-vStream/venom-xbmc-addons#922]
salut a tous
depuis ma box androïd
je lance le film  ex: "l’exception a la règle "sur zone telechargement.ws je choisis le lien 1fichier
j'ai bien le 1fichier résolve qui se lance ensuite premium mode"authentification réussis"
et la ça tourne ça tourne et échec
je fais la même chose sur le pc idem.
je refais la même chose sur ma tablette et là ça fonctionne a merveille

sur la box et le pc j'ai fait la mise a jour bêta hosters onefichier.

sur un autre post il avait le même problème lui il parle d'une mise a jour (kodi,1fichier,vstream ?)
j'ai pas compris ce qu’il voulait dire.

merci pour tout votre travail vous êtes des chefs :-)

**Comment by johngf** [comment]
tu as oublié celle la qui va avec https://github.com/Kodi-vStream/venom-xbmc-addons/blob/a2bf9ce885ee0e39efaecc57ab3bd3f22ed5836c/plugin.video.vstream/resources/lib/handler/premiumHandler.py
si tu lis l'autre post tu verras que j'ai signalé qu' il y avait avoir des soucis
si ça fonctionne pas enleve 
" la mise a jour bêta hosters onefichier." que tu as mis et remet la normal depuis master

**Comment by TmpName** [comment]
Ca remarche pour toi ?

**Comment by moimeme45** [comment]
Salut 
j'ai essayé avec les 2 fichiers bêta ça fait pareil j'ai remis 2 fichiers master et c'est la même chose je vais attendre une MAJ si vous trouvés le problème 
Encore merci pour le boulot que vous faite :-)

**Comment by johngf** [comment]
tu as kodi 17 je parie ?

**Comment by moimeme45** [comment]
non
j'ai sur le pc "kodi jarvis 16.1 et la box android  "spmc

**Comment by johngf** [comment]
test comme @baaaaaziiiiingaaaaa efface pass + id puis remet les

**Comment by moimeme45** [comment]
Je vais tester ca 
Je le trouve ou? Pass +id
Dans les reglages de vstream c'est ça non ?

**Comment by johngf** [comment]
D'abord j'ai un doute tu as un compte premium ?

**Comment by moimeme45** [comment]
Oui j'ai un compte premium

**Comment by johngf** [comment]
Donc tu as mis ton id et pass dans les parametres de vstream et activé le compte ?

**Comment by moimeme45** [comment]
Oui c'est fait depuis des lustres :-)  j'ai meme enlever et remis mes identifiants .
Ce qui est bizarre c'est que certains films se lancent avec un peut d'attente d autres en les lançant deux fois ça passe 
 je fais le test a l' instant avec #brice#  une fois echec et 2º tentative ça marche

La je suis largué

**Comment by baaaaaziiiiingaaaaa** [comment]
Tu as le mode SSL actif ou pas sur 1fichier? perso il est désactivé pour être plus rapide en téléchargement sur l'ordinateur

**Comment by moimeme45** [comment]
Idem ssl décoché

**Comment by TmpName** [comment]
Ok, bon je remet l'ancienne version de onefichier, de toute facon les modifs seront sur le site si on veut les remettre plus tard.
