### ISSUE TITLE
Framapad

### ISSUE THREAD

**Issue by harrynou123** [Kodi-vStream/venom-xbmc-addons#923]
Bonsoir aucune chaîne présente sur framapad ne fonctionne

**Comment by Kodigoal** [comment]
Bonsoir, faut soit attendre qu'une personne mette à jour les liens , soit par toi même si tu trouves une liste de liens fonctionnels.
Tout le monde peut maj cette liste dispo via
https://annuel.framapad.org/p/vstream

**Comment by harrynou123** [comment]
le lien ne marche pas 
![2017-02-15](https://cloud.githubusercontent.com/assets/25793078/22996812/5e68b798-f3d0-11e6-8bb4-e0b22c7920e6.png)

**Comment by Kodigoal** [comment]
Oui faut attendre je pense que ca remarche leur site.

**Comment by harrynou123** [comment]
pas pour moi

**Comment by Kodigoal** [comment]
Mal exprimé , je disais faut attendre que ca remarche , doit yavoir un problème au niveau de leur site en ce moment.

**Comment by harrynou123** [comment]
c'est bon j'ai mis les lien mais il faut avoir l'add on f4mtester pour que sa marche
