### ISSUE TITLE
hosters supportés lors de l'utilisation d'urlresolver

### ISSUE THREAD

**Issue by chataigne73** [Kodi-vStream/venom-xbmc-addons#924]
Salut
Depuis quelques temps j'ai pris un abonnement à un débrideur, et je passe donc maintenant par urlresolver.

Le problème est que vstream se limite au listage des hosters supportés par vstream dans la plupart des fichiers sites... ex: 
`oHoster = cHosterGui().checkHoster(sHosterUrl)`
suivi de 
`if (oHoster != False):`

hors c'est dommage de cacher des hosters si le débrideur les supporte

avez vous une idée pour remédier à cela ?

peut-être modifier checkhoster et renvoyer tout le temps true quand on utilise urlresolver ?

**Comment by TmpName** [comment]
J'ai l'impression que tu sur-estimes le resolver ^^.
Quand url resolver est active, il est prioritaire, si il supporte le lien, il sera affiche.
Si il ne le supporte pas on teste ceux de Vstream
Si tjours pas supporte on retourne False.

Tu as trouve quoi comme hoster gere par urlresolver et pas Vstream ? Rapidgator ou le reste de la serie ?
