### ISSUE TITLE
Impossible s'installer Vstream via le repo avec Kodi 17

### ISSUE THREAD

**Issue by Benaland** [Kodi-vStream/venom-xbmc-addons#928]
Salut la team, je n'arrive pas à installer Vstream sur kodi 17 via le repo. Plusieurs personnes ont le même problème que moi.
J'ai trouvé une solution assez mac giver en installant kodi 16.1 et en mettant Vstream, puis mettre à jour et passé en 17 en gardant notre contenu. Voili voilou :)

**Comment by LordVenom** [comment]
Salut, ça t'aide ? sinon message d'erreur ? log ?

https://www.youtube.com/watch?v=1uS5gbd8jpE

**Comment by Benaland** [comment]
Déjà fait, je viens de refaire et toujours rien. J'envoie le log comment ?

**Comment by Kodigoal** [comment]
Dans les paramètres de vStream, onglet Outils.
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil
Voir point upload log.

**Comment by Benaland** [comment]
Merci, par contre impossible vu que je n'ai pas Vstream lol

**Comment by johngf** [comment]
C'est le,log de kodi tu l'as automatiquement

**Comment by Kodigoal** [comment]
Oui j'ai édité mon post entre temps lol

**Comment by Benaland** [comment]
C'est bon, merci j'ai réussi à l'installer. Avec la technique de l'issue #930  . Mais bon toujours impossible via le repo ...

**Comment by johngf** [comment]
Dans les params de kodi tu as activer l'option install via repo inconnu

**Comment by Benaland** [comment]
Oui bien-sûr, j'ai installé d'autres extensions comme Exodus et c'est niquel.

**Comment by LordVenom** [comment]
J'ai refait mon installation avec la 4.9 pour la video j'ai pas eu de soucis sans log je sais pas.

**Comment by Benaland** [comment]
T'as essayé à partir d'un kodi 17 vierge ?

**Comment by LordVenom** [comment]
Oui tous était neuf même Windows.

**Comment by Benaland** [comment]
Hmm bizarre bizarre... Et sur Android t'as essayé ?

**Comment by LordVenom** [comment]
Nop linux et Windows seulement j'ai pas de box android faudrait que j'installe un émulateur mais j'ai la flemme :)

**Comment by Kodigoal** [comment]
Je teste ce soir sous android voir si même soucis.

**Comment by Kodigoal** [comment]
Ok via Kodi17 (vierge) /Android , installation de vStream par le repo sans soucis ...

**Comment by johngf** [comment]
tu n'aurais pas installé un antivirus ? meme si c'est un peu inutile sur android 
sur win 7 le mien qui fait parfeu et antivirus bloque l'install via le repo je suis obligé de le désactivé temporairement le temps que vstream s'installe

**Comment by Benaland** [comment]
Hmm bizarre, j'envoie mon log ce soir.
Et non je n'ai pas installé d'antivirus sur mon smartphone

**Comment by Allonsbon2004** [comment]
Salut,
J'ai un pb similaire avec les addons de super repo. Systeme KOdi osmc sur raspberry. Les addons sont visibles via super repo krypton mais ne se chargent pas. Les sources inconnues sont bien activées.
Les addons de kodi repo qui ont une taille fichier quand a eux se téléchargent

**Comment by Benaland** [comment]
Voici mon log http://slexy.org/view/s21hQes2FD

Sachant que j'ai réussi à installer Vstream manuellement sans passer par le repo. Puis parallèlement j'ai installé le repo pour fusionner les deux en cas de mise à jour.

**Comment by johngf** [comment]
bah le truc c'est que dans ton log il n'y a rien qui concerne vstream ou quelconque erreur d'install donc ...

**Comment by Benaland** [comment]
Ah... Pour re situer le problème je vais refaire un petit résumé. 

J'ai installé Kodi 17 sur un nouvel appareil Android. Bien évidemment en priorité j'installe le repo de Vstream. Jusque là tout fonctionne. Puis j'entre dans le repo, je clique sur installer Vstream mais rien ne se passe. Je redémarre et insiste pour l'installer, mais toujours rien. Aucun message d'erreur ni rien... Du coup j'installe vstream manuellement avec le fichier zip de la version 4.9 et là tout fonctionne... 

Je suis sur un groupe Facebook et je vois que je ne suis pas le seul à avoir ce problème.

**Comment by Kodigoal** [comment]
Faudrait faire la manip de zéro , kodi vierge , installer repo , puis par le repo installer vstream, attendre voir si il installe ou pas.
Si il installe pas, minimise kodi et localise le fichier kodi.log sous android:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

et copie-colle le sur pastebin .com
et met le lien pastebin ici.

**Comment by Benaland** [comment]
D'accord, par contre on utilise quoi pour ouvrir un fichier .log ?

**Comment by LordVenom** [comment]
Un simple éditeur de texte

**Comment by Kodigoal** [comment]
Merci , mais le log aide pas , je vois pas d'erreur au moment ou il tente d'installer..
Vais réinstaller,  voir le log chez moi ce qu'il sort.

**Comment by Kodigoal** [comment]
Uhmmm alors j'ai le même soucis si j'installe pas la bonne version du repo...
Et dans ton log je vois lequel tu as installé..
Faut prendre celui la :
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/master/repo/repository.vstream/repository.vstream-0.0.2.zip
Si c'est pas ca ton erreur de prendre le mauvais zip repo , je vois pas trop d'ou ca peut venir alors..

**Comment by LordVenom** [comment]
Ou tu chope l'ancienne version du repository ? encore une installe avec supert repo ? normal que ça bug

**Comment by Kodigoal** [comment]
@LordVenom ya encore l'ancien zip repo ici
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/master/repo/repository.vstream/repository.vstream.zip

**Comment by Benaland** [comment]
Re. 
J'ai installé le repo 0.2 avec la source Fusion. 

Je viens de supprimer le repo précédemment installé et réinstaller le repo que @Kodigoal viens de partager et là... Comme par magie tada ! Ça fonctionne !

**Comment by Kodigoal** [comment]
xD 
La bonne page pour télécharger le repo c'est ici : ( à partager à ceux  qui ont le même soucis que toi comme t'avais dit que tu n'étais pas le seul)
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository

**Comment by LordVenom** [comment]
Installer tester sous fedora Ok. Je supprime l'ancien repo bientot

**Comment by Karoly1963** [comment]
- [ ] @Kodigoal
