### ISSUE TITLE
Easyvid hoster pb

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#929]
bonjour à toute l'équipe, juste pour vous informer que easyvid ne fonctionne plus depuis dimanche.
voila, c'était pour vous le signaler. bonne journée

**Comment by ttrd06** [comment]
en fait, après avoir regardé le source d'une serie sur easyvid, ils ont mis le code mp4 en dur dans la page ...
plus besoin de passer par le cPacker().unpack

**Comment by johngf** [comment]
c'est bon mais faut laisser unpack au cas ou d'ancienne page utilse ce systeme de codage
