### ISSUE TITLE
Probleme Marque-pages !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#931]
Bonjour,

Je peux plus ouvrir mes marques-pages sur Vstream sous Kodi Jarvis 16.1 ?

Quelqu'un peux m'aider.

**Comment by johngf** [comment]
ils doivent etre corrompu ça mais deja arrivé en y mettant quelque chose qu'après je n'arrive plus a y acceder

ma solution
firefox / installe le module complémentaires sqlite manager/ 
sur firefox outils sqlite manager 
avec le dossier marron
ouvrir \Kodi\userdata\addon_data\plugin.video.vstream\vtream.db  (sur win7)
clique sur favorite ensuite parcourir et rechercher et supprime la dernière de la liste 
si ça fonctionne pas recommence jusqu'a trouvé le marque page corrompu

**Comment by TmpName** [comment]
On pourrais mettre une option pr remttre a zero les favoris ?
Ou celle pour remettre a zero les bases de Vstream suffisent ?

**Comment by johngf** [comment]
je me suis fait avoir comme ça j'ai perdu tous mes marque pages avec les clears cache j'ai pas pensé a les sauvegarder avant de cliqué

**Comment by LordVenom** [comment]
Je veut bien la BDD corrompu pour test.

**Comment by TmpName** [comment]
Oui, pas bete, tu pourrais pas nous faire parvenir le fichier vtream.db ?

**Comment by johngf** [comment]
il a tous réinstallé
