### ISSUE TITLE
Problème de recherche films/séries

### ISSUE THREAD

**Issue by chicungunya** [Kodi-vStream/venom-xbmc-addons#932]
Bonjour,

Quand je recherche une série ou un film, je n'ai pas de résultats sur certaines sources.
Pourtant quand je vais directement sur la source (zone-telechargement.ws), les films y sont.
Kodi 16.1

Merci

**Comment by johngf** [comment]
c'est normal certain site ne sont pas pris en compte dans le fichier settings via recherche film serie anime doc
ça recherche toujours sur les memes sites >> (peut etre a modif)
pour contourner ça clique sur recherche choix multiples et clique sur les sites de ton choix puis ok

**Comment by chicungunya** [comment]
Merci pour ta réponse.
Même en passant par la recherche multiples, je n'ai pas de résultats sur zone-telechargement.ws

**Comment by johngf** [comment]
c'est quoi le titre que tu cherche ?

**Comment by chicungunya** [comment]
Pour n'importe quel film ou série quand je fais une recherche multiple sur zone-telechargement.ws je n'ai aucun résultat.

**Comment by johngf** [comment]
a oui je viens de voir il a été mis a jour il y a peu donc il faut attendre la maj

**Comment by chicungunya** [comment]
La maj arrive quand ? 

Merci

**Comment by chicungunya** [comment]
J'ai l'application sur iOS
Comment faire ?

**Comment by TmpName** [comment]
Sur iOS vous n'avez pas acces aux fichiers non plus ?

**Comment by chicungunya** [comment]
Mon iPhone n'est pas jailbreaké donc je n'ai pas accès à ce dossier. A moins que vous ayez un tuto pour y accéder sans jaillbreak ?

Sinon j'attendrai la MAJ de Vstream.

Merci

**Comment by Kodigoal** [comment]
Salut,
sur Youtube ' ifile ios no jailbreak'
Mais bon , dangereux si l'appli est vérolé via les sites proposés pour l'installer...
Sinon avancer la date de 3 jours sur ton ipad devrait proposer la maj auto de vstream.

**Comment by chicungunya** [comment]
J'ai essayé avec iFile mais il faut payer une licence.
J'ai avancé la date à 3 jours et fait les MAJ mais toujours rien en recherche sur zone-telechargement.ws

**Comment by johngf** [comment]
Il faut attendre que le fichier soit dans la version master ce soir ou demain

**Comment by chicungunya** [comment]
Ok j'attends votre feu vert.
Merci à tous !

**Comment by Kodigoal** [comment]
Ah oui pas sous Master encore,  désolé.

Sinon en testant recherche multiple je viens de voir 
que ca me fait erreur chez moi , pas de popup pour choisir ( Kodi15.2/android).
log: 
http://pastebin.com/fF0wtSh2

**Comment by TmpName** [comment]
Mince, dsl ,je met sur master.

**Comment by chicungunya** [comment]
Ça ne marche toujours pas de mon côté . Pourquoi avoir mis résolu ?

**Comment by Kodigoal** [comment]
Avance la date de nouveau pour avoir la maj ( +3 jours ou plus jusqu'à que vstream te propose la maj) , fichier a été mis sur la Master , ca devrait fonctionner.

**Comment by chicungunya** [comment]
Au top un grand merci !
