### ISSUE TITLE
Format d'image et version kodi.

### ISSUE THREAD

**Issue by TmpName** [Kodi-vStream/venom-xbmc-addons#933]
Bon encore des trucs a tester.
Sur le site freetelechargement, le captcha est au format gif chez moi (V17/Wndows) (pas vu d'autre format).
Le code est maintenant capable de mettre la bne extension au fichier, mais chez @chataigne73 (Kodi V16/Android), l'image ne se charge pas si l'extention n'est pas png.

Pour savoir le format de l'image, il suffit de l'ouvrir avec le blocnote (Vstream le sauvegarde sur le disque dur) et de lire les 5/6 premier caracteres.

Sur kodi V17 message d'erreur si extension png.
Could not decode a frame.

En fait ca marcherait sur Windows, mais pas android.

**Comment by Kodigoal** [comment]
Ya un film ou série à tester avec image en gif  qui fonctionne pas sous android chez @Chataigne73?
Parce que là en testant un peu sous android/kodi15.2 , je rencontre pas de soucis pour l'instant.
Voir si c'est juste sous Kodi16 le problème...

**Comment by johngf** [comment]
`if (cConfig().isKrypton() == True):
     Format gif`
Format Jpeg, jpg ? A testé

**Comment by chataigne73** [comment]
Excusez moi, je vous ai induit en erreur, il s'agit d'une box Android, mais je l'utilise avec une installation de librelec... Donc il s'agit plutôt d'une distribution Linux si ne dit pas de conneries...
Je ferai des tests et des logs dans la soirée

**Comment by TmpName** [comment]
@Kodigoal  Le prb se pose sur le captcha de freetelechargement.
Chez moi, suis sur a 100% c'est du gif.
Apres c'est bizarre quand meme que sur linux, le format soit du png, ou que le gif ne s'ouvre que sous l'extension png.

**Comment by Kodigoal** [comment]
@TmpName testé quelques films encore là , il trouve du gif , mais sous 15.2/android je peux mettre  Captcha.lol  ou .gif ou .png , ca s'affichera sans soucis.
Verra les logs sous Linux , vais tester aussi d'ailleurs.

**Comment by johngf** [comment]
Linux c'est large nbr de distrib etc..........
Je testerai demain sur la mienne

**Comment by Kodigoal** [comment]
kodi 14.2 / Debian  vStream Beta à jour , pas de soucis de captcha gif/png. ( a voir sous kodi16 , faut que je maj un de ses jours)
Juste le même soucis que sous 15.2 pour l'erreur recherche Multiple ( pas de fonction Dialog.multiselect), logique xD.

**Comment by chataigne73** [comment]
bon alors voici ce que donne le log en enregistrant l'image en .gif dans free_telechargement
[http://pastebin.com/Uzn8qukw](http://pastebin.com/Uzn8qukw)

**Comment by Kodigoal** [comment]
T'as quoi comme skin sur kodi?

**Comment by chataigne73** [comment]
Skin standard, confluence

**Comment by johngf** [comment]
bon alors apres test pareil que @chataigne73 parce que kodi16 ne gere pas les gifs je pense vu qu'il n'arrive pas a les afficher quand les thumb des films sont en .gif

solution qui fonctionne sur les deux captcha.raw et c'est ok linux et windows 16 et 17

**Comment by TmpName** [comment]
Ha pas bete ^^.
A tester le coup du raw.

Mais ils sont trop fort quand meme, fichier gif ne marche pas, mais si tu le renomme en png la ou il t'ouvre le fichier gif, sont vraiment perches les devs kodi.

**Comment by Kodigoal** [comment]
idem en fait via kodi16/android , .raw régle soucis.

**Comment by chataigne73** [comment]
pareil, .raw testé ok pour free_telechargement et ddl_island sur ma box android en 16.1
