### ISSUE TITLE
Design (avis/proposition)

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#934]
Envie de changement dans le design de vStream j'ai rien contre.

![fanart](https://cloud.githubusercontent.com/assets/4380112/23165622/6412b6dc-f83d-11e6-9ca9-4673431b71ea.jpg)

Je vous fournis le .png tout et modifiable vous pouvez aussi proposer vos idée.

https://github.com/Kodi-vStream/venom-xbmc-addons/tree/Beta/repo/resources

**Comment by johnboisvert** [comment]
Dans la prochaine mise a jour ? je suis tous a fais  OUI :)

**Comment by johngf** [comment]
avis perso le design actuelle me convient, je préfère amélioré facilité et confort d'utilisation de vstream

**Comment by TmpName** [comment]
Ben pareil que @johngf, et je rajouterais clarte et visibilitee, (ce que n'a pas leur dernier skin immonde).
Je prefere un truc sobre, la y a trop de couleurs.

**Comment by LordVenom** [comment]
Pour moi limiter le nombre de click c'est augmenter le temps de chargement et moi c'est ça que je supporte pas.

**Comment by Kodigoal** [comment]
Proposer les 2  designs via option vStream et permettre de rajouter un personnalisé via chemin répertoire fichier pêtre?
Perso j'affiche pas les fonds addons, transparence et le fond est le wallpaper choisi de kodi.

**Comment by LordVenom** [comment]
Non non trop lourd pour rien l'image et souvent masquer par le skin et les catégorie sont dejas modifiable via les paramètre de vstream.Soit on trouve un nouveau Fanart qui plaise a tous soit on touche pas.

**Comment by Benaland** [comment]
Ça me plaît
