### ISSUE TITLE
Recherche de film retourne tout et n'importe quoi

### ISSUE THREAD

**Issue by greg2fs** [Kodi-vStream/venom-xbmc-addons#935]
Bonjour, voila je teste vstream depuis quel jours et lorsque je recherche un film exemple "vaiana" j'ai plein de résultats incohérents:

> Recherche: vaian
> Tv-streaming.ch
> Aucune information
> l'affaire dupont
> <span class="b">6x5<span class="a">saison x épisode<spa...

Donc un peu n'importe quoi, des sites, des films et quand même quelques résultats avec vaiana.
Est-ce comme ça pour tout le monde ?

**Comment by johngf** [comment]
Oui le resultat et le meme que sur les sites internet ou tu cherche

**Comment by TmpName** [comment]
Et certains sites proposent effectivement n'importe quoi ^^.
Les pires ont un filtrage, mais pas tous.
Si tu trouves plus de 4/5 resultats avec aucuns mots contenus dans la recherche, c'est qu'on a oublie le filtrage.

**Comment by johngf** [comment]
Souvent les sites retourne bcp de hors sujet mais ça reste utile film ou serie qu'on a jamais vu etc.....

**Comment by TmpName** [comment]
Yep, suis d'accord avec toi, c'est pour ca que en general ca ne me derange pas.
Dans streamingk le filtrage ne demarre qu'a partir de 3 resultats par exemple.
Mais il y a des sources qui donnent facile 10 resulats qui n'ont rien a voir.

**Comment by greg2fs** [comment]
Mouais je ne suis pas convaincu, j'ai déjà programmé ce genre de filtrage
et je ne vois pas de raison de ne pas filtrer ce genre de résultat
automatiquement même si les site ne filtre pas eux même...

**Comment by LordVenom** [comment]
Je doit pas avoir le même vStream moi lol et le nom c'est vaiana toi tu recherche vaian mais bon j'ai tester les résultats son correct.

![image](https://cloud.githubusercontent.com/assets/4380112/23210987/24920abc-f900-11e6-94e1-e36484a57f0b.png)

**Comment by LordVenom** [comment]
Je me demander d’ailleur la recherche film / série en texte de TMDB serais pas mieux dans la recherche normal ?

**Comment by greg2fs** [comment]
A part les span, c'est a peu près ce que j'ai, j'en conclu les les noms de
site sont fait exprès pour lister ce qu'il trouve pour chaque site ? Ce
n'est pas évident avec la présentation que j'ai (tout est horizontal, mais
c'est dû au skin).

2017-02-22 13:13 GMT+01:00 Lord Venom <notifications@github.com>:

**Comment by LordVenom** [comment]
Ha peux être bloquer la recherche au vue de fichier et pas de movie a voir.

**Comment by TmpName** [comment]
Franchement sur ce skin, c'est illisible.
Couleur se fondent les unes dans les autres.
Trop d'espace entre les lignes
Ecrit trop petit
Le symbole dossier en debut de ligne perturbe et ne sert a rien
Espace mal occupe sur l'ecran
Ect ....

Apres je sais pas la difference entre l'affichage fichier et movies sur ce skin.

**Comment by LordVenom** [comment]
Bon j'ai retoucher la recherche qui renvoye maintenant 1seul boucle donc dans la logique ont peux la trier mais je suis pas pour et on peux aussi faire une function qui limite les erreurs mais j'ai pas trouver comment .

**Comment by TmpName** [comment]
Lol, ben j'espere pas etre le seul, et qu'il vont corriger leur *****. Sinon du coup je reste sous confluence.

Sinon il y a deja une fonction pr limiter la recherche (elle est implante par exemple dans streamingk)
Si la recherche donne donne plus de 2 resultats, elle se met en route et supprime tout les resultats qui n'ont aucun mot en commun avec la recherche.

**Comment by johngf** [comment]
ce thème c'est la mode du "mobile version" il manque surement la version pc si on pouvait tous customisé
(couleur, taille police, fenetre synopsis on off du moins pas toujours ouverte , icone toujours a droite) 
en gros confluence estuary lol
ça passerait mais la ....
en plus il manque des modes d'affichage

**Comment by LordVenom** [comment]
Ben j'avais pas penser a ça mais si je vire des titres qui n'ont rien en commun je vire aussi les titres des sites.

**Comment by johngf** [comment]
Donc il y aurait une nouvelle fonction recherche filtré ?
Pour les titres c'est pas grave si il n'y a rien ça n'affiche rien ou aucune info

**Comment by LordVenom** [comment]
Non il a pas tord la recherche global donne souvent à coter, ceux qui ne m'a jamais dérangé et même fait découvrir des truc. Mais virer le titre des sites j'aime pas l'idée vue que j'ai des sites préférer j'aime bien voir d'ou vient le lien et mettre le nom du site avec le nom du film ça vas faire long.

**Comment by LordVenom** [comment]
![image](https://cloud.githubusercontent.com/assets/4380112/23259856/64b77ea4-f9cf-11e6-8a72-2d03d6c7ca9f.png)

![image](https://cloud.githubusercontent.com/assets/4380112/23259868/7f3884ee-f9cf-11e6-817f-d1b1ca43a90c.png)

**Comment by LordVenom** [comment]
Bon la différence et pas flagrande faut améliorer la function de filtre.

**Comment by TmpName** [comment]
Ben sur confluence, ca ressort vraiment mieux, on voit bien les "sections", juste en jouant avec les couleurs (possibilitees aussi de jouer avec gras ou italique ?)
Sinon non, pour moi faut pas retirer le nom du site, avec l'usage on connait les sites, donc on sait si tel ou tel site propose beacoup de sources ou pas, du youwatch ou de la HD,...

Sinon j'ai pas compris ce que tu veux faire avec le filtrage ?
- En mettre un global juste dans la recherche globale (qui du coup ne tournera pas si l'user passe par le site direct)
- Le mettre dans tout les fichiers sites, meme ceux qui n'en ont pas vraiment besoin
- Laisser comme ca
- Le rajouter dans les fichiers sites des sites qui proposent trop de resultats ?

**Comment by LordVenom** [comment]
Ben hum la il reste que peux de choix soit j'y touche pas soit on fait une option filtre qui vas virer les nom des sites et les resultat off.Vue qu'il sont dans la même boucle je peux pas garder le nom des sites et faire le tris.

**Comment by TmpName** [comment]
Honnetement, je ne vois pas comment retirer les sites sans reponse mais
1 - ca ne me derange pas
2 - au moins on est sur que l'addon a teste sur le site X ou Y

Et pour le prb des faux resultats par site, si vraiment le site part en sucette suffit de rajouter le meme code que celui de streamingk

**Comment by johngf** [comment]
Donc si c'est une nouvelle section `recherche filtré` a part qui ne modifie pas le global actuel ça me va

**Comment by LordVenom** [comment]
Nop pas une section une option dans setting.

**Comment by johngf** [comment]
la modif affiche le resultat trouvé un bref instant dans la popup dialog recherche

**Comment by LordVenom** [comment]
Envoyer possibilité d'activer ou pas le filtre et de modifier ça pertinance.

Note j'ai reussis a garder le nom des sites 👍

**Comment by TmpName** [comment]
Nickel pour l'activation ou pas.
Par contre j'ai des doutes sur l'algo utilise pour comparer les chaines de caracteres.

 CheckOrd(aaaab) donne 486
 CheckOrd(aaaac) donne 487(+1)
 CheckOrd(aaaaz) donne 510 (+23)

Il y a 1 lettre de different a chaque fois mais le resultat est beacoup plus important, pkoi ne pas utiliser CheckOccurence() qui donne le nbre de mot en commun ou pire celui de trakt qui est encore plus precis (compare le nombre de mot identique ET le nombre de mot total)
C'est plus simple de comparer les mot que les lettres, et plus fiable car ca evite d'avoir le resultat "wold war" si tu cherches "underworld" a cause des lettres W O R L D. Moins efficace avec les fautes de frappes mais si le mec tape undreworld et trouves pas, faut pas deconner non plus.

**Comment by TmpName** [comment]
Apres si tu a fond la dedans j'ai un algo de fou qui permet de donner la correspondance entre 2 chaine de caracteres.
Du type de celui de google. Si tu veux faire monter le processeur a 100% lors des recherches ^^.

**Comment by LordVenom** [comment]
Je voulais un truc reglable dans le genre j'ai trouver que ça, faut voir a l'usage j'ai fait quelque test ça avais l'air pas trop mal.Hé question gourmandise ben c'est un retour sur une liste a 26 lettre avec une addition ça doit pas être si gourmand que ça. D'ailleur a ceux que j'ai lus si tu fait "test" == "test" il fait la même chose.

**Comment by johngf** [comment]
c'est voulu que le résultat de recherche défile dans le dialog recherche avant de s'afficher alors ?

**Comment by LordVenom** [comment]
Oui y a deux boucle une pour load les addmovies et l'autre pour afficher.

**Comment by TmpName** [comment]
Nope, pas gourmand non plus, je te parlais d'un gros algorythme qui m'avait servi dans un autre projet qui donnait en pourcentage la correspondance entre 2 chaines.

Par contre c'etait quoi le prb avec CheckOccurence , je peux peut etre l'ameliorer, car un autre soucis c'est qu'il faut donner un titre complet, moi si je cherche "stars wars episode X la menace fantome" je tape que "stars wars fantome" du coup vais me faire refouler avec CheckOrd().

**Comment by LordVenom** [comment]
Effectivement j'ai eu le soucis avec les [le,un] supprimer si le reglage et strict ça fonctionné j'ai du les remettre, mais bon normal si ont Filtre faut s'attendre a ceux que ce soit filtrer lol

Hum CheckOccurence pour un film "comme les bêtes" retourne True pour tous ceux qui comprend comme ou bête c'est super vaste comme filtrage et tu supprime les [un, des] mais autant des fois c'est cool autant ça fonctionne pas "le batman" et "batman" sont pas les même film. 

Du coup je me demande si la recherche TMDB devrais pas allais a la recherche global histoire que tu cherche un film avec un bout de texte lui te retourne le bon nom et tu peux lancer la recherche vstream dessus.Utile pour les films au nom a la con.

**Comment by TmpName** [comment]
Peut etre un peu lourd si automatique, faire une option "proposition de titre" ?

Apres d'un point de vue purement perso, c'est comme sur google, il vaut mieux chercher 2/3 mots caracteristiques qu'une expression complete. moi ce ne me gene pas de voir "le batman" si je cherche "batman", par contre ca me gene plus si je cherche "la batman" et que ca me sort "le superman", c'est pour ca que je filtre les articles, pareil pour le mot "comme".

Moi j'ai peur que certains activent le filtre, et se plaignent de ne trouver aucuns films car ne sachant pas utiliser un moteur de recherche.

Le but de CheckOccurence est juste de virer les resultats qui ne devraient pas etre la a 100%.

**Comment by LordVenom** [comment]
Je compte bien sur les retours si y en a de la ont aviseras.

**Comment by Kodigoal** [comment]
Ya pas un soucis au fichier topimdb.py ? 
Fonctionne plus via recherche visuelle/topImdb/
