### ISSUE TITLE
Catégories incohérentes

### ISSUE THREAD

**Issue by greg2fs** [Kodi-vStream/venom-xbmc-addons#936]
Bonjour, lorsque je vais dans "Film" puis "Films (genre)", je n'ai que des nom de site:

> Cinemay.com
> Film illimite
> Film-streaming.co
> filmenstreaminghd

En fait c'est pareil dans toutes les sous catégorie de toutes les catégories.

**Comment by Kodigoal** [comment]
Bonjour , c'est normal , par genre par exemple , tu vas choisir le site puis les genres dispos sur ce site seront affichés.

**Comment by johngf** [comment]
D'ailleur il faut mettre a jour ta version film streaming co n'existe plus

**Comment by johngf** [comment]
Vstream ne fait que naviguer sur les sites internet que tu choisis pour trouvé ce que tu cherche

**Comment by TmpName** [comment]
Ca va t'afficher tout les "sites" qui propose ce type de categories.

**Comment by greg2fs** [comment]
Le problème, c'est que déjà ça oblige à passer en revu tous les sites alors
que ça pourrait simplement parcourir tous les sites.
Et du coup une fois qu'on a choisi un site de la catégorie FILM par
exemple, il peut n'y avoir aucun contenu ANIMATION à l'intérieur c'est
vraiment frustrant et long en recherche alors que c'est quand même le but
de l'application.
Je vais m'intéresser à la programmation d'addon kodi, je maitrise pas mal
ce genre de "fonction" en php et c++ ça devrait le faire en python...

2017-02-21 21:01 GMT+01:00 TmpName <notifications@github.com>:

**Comment by johngf** [comment]
"que ça pourrait <<simplement>> parcourir tous les sites" je ne pense pas il faudrait modifier tous les fichiers sites et surement d'autres fonctions de vstream ( personne n'aura envie de le faire)
ça serait plus long que de faire une recherche basique vu le nombre de sites et parfois leurs temps de réponse(surtout le soir pour certains)
en 4 clics films/films genres/ le site que tu as choisis/categorie >> liste de films

sinon il y a la recherche visuelle qui affiche les films par genre grace a themoviedb et ensuite recherche sur les sites

**Comment by greg2fs** [comment]
Je connais encore mal le fonctionnement de l'extension, peut etre qu'il
faudrait passer par un serveur php qui ferait tout le travail de recherche,
de facon à n'avoir qu'une source dans l'addon...
Effectivement ça va vite si on sait sur quel site chercher, ce n'est pas
mon cas.
Je ne savais pas pour la recherche visuelle je vais tester, merci.

**Comment by TmpName** [comment]
Tu as pu voir que certains sites mettent plusieurs seconde pr repondre
Imagines si juste pour aller voir dans le genre "comedie" il fallait aller verifier sur une dizaine de sites.
Ce qui se passe en general, a l'usage tu te trouves 2 ou 3 sites favoris (que tu preferas pour le catalogue, le choix des hebergeur, la qualitee, ect ...) et tu ne va tourner que avec ceux la sauf quand vraiment il ne trouveront pas de reponse.
80% des sites de Vstream ne te serviront jamais.
