### ISSUE TITLE
openload

### ISSUE THREAD

**Issue by stevebou** [Kodi-vStream/venom-xbmc-addons#940]
Bonjour, 

depuis quelques jours, vstream ne parvient plus à récupérer des flux sur openload (resolve puis fichier introuvable). 
Je me permets de le signaler ici car j'ai l'impression que le soucis vient de vstream, et pas d'openload.
En effet, voici une partie de mon kodi.log

13:04:55 T:139796823406336  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
13:04:55 T:139796823406336  NOTICE: 	[PLUGIN] Vstream: Hoster - play htt ps://openload.co/embed/eUqEy8LzLIA/
13:04:55 T:139796823406336  NOTICE: url teste : htt ps://openload.co/embed/eUqEy8LzLIA/
13:04:55 T:139796823406336  NOTICE: Nbre d'url : 2
13:04:55 T:139796823406336  NOTICE: AA encryption
13:04:55 T:139796823406336  NOTICE: hidden url : ('TmqnNmzHcq', '13065280661713507089080691605925078100860906218098010820305929094390890605931139330683509337114000691412602139220641908334061320873613911065130692006941069050681513404115400622106226062240621206130069230702708038')
13:04:55 T:139796823406336  NOTICE: 	[PLUGIN] Vstream Erreur: Fichier introuvable
13:04:55 T:139796823406336  NOTICE: 	[PLUGIN] Vstream: Table initialized
13:04:55 T:139797518059520   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=+%5BCOLOR+coral%5D%5BDVD%2FFR%5D%5B%2FCOLOR%5D+FR+-+Pixels+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&sHosterIdentifier=openload&sTitle=+%5BCOLOR+coral%5D%5BDVD%2FFR%5D%5B%2FCOLOR%5D+FR+-+Pixels+%5BCOLOR+skyblue%5DOpenload%5B%2FCOLOR%5D&siteUrl=https%3A%2F%2Fopenload.co%2Fembed%2FeUqEy8LzLIA%2F&sFav=play&sMediaUrl=https%3A%2F%2Fopenload.co%2Fembed%2FeUqEy8LzLIA%2F&sCat=4&sId=cHosterGui&sFileName=FR+-+Pixels]

Le lien direct donné dans le log par vstream fonctionne dans un navigateur. Par contre vstream retourne une erreur pour le lire dans kodi.

J'utilise kodi 16, et la dernière version du repository récupéré ici (c'est à dire vstream branche beta, version 0.4.9, et les dernières sources vidéos sont bien à jour, et marchent d'ailleurs, puisque le lien du film est bien récupéré et est correct en url direct dans le navigateur).

Une idée d'où ça peut venir ?

Merci pour votre réponse, et surtout pour votre boulot sur cette extension qui a changé mon kodi !!

**Comment by johngf** [comment]
Pas testé ton lien mais chez moi open load fonctionne

**Comment by stevebou** [comment]
Non, c'est bien XbmcPlugin dans lecture par défaut.

Je n'arrive à voir aucun lien openload. Là j'en avais pris un au hasard pour créer un log. 

Par exemple, dans Films(Genre)>Film illimite>Action/Aventure, le premier de la liste est "Echo Effect". Le lien open load ne se lance pas, avec la même erreur dans le log.

kodi installé sur un pc et un raspberry pie, et même problème sur les deux, qui est arrivé au même moment... Et je n'ai pas touché aux options de kodi a priori (sur le raspberry c'est sur. Je fais juste les mises à jour de sources quand vstream le signale).

**Comment by johngf** [comment]
Le meme lien que tu viens de testé fonctionne chez moi

**Comment by stevebou** [comment]
Tu es sous kodi 16.1 ?

**Comment by johngf** [comment]
Oui kodi 16.1
Par hasard tu n'as pas ajouté un fichier adancedsettings perso a kodi ?

**Comment by stevebou** [comment]
Non, mais le problème vient de moi. J'ai supprimé le répertoire .kodi pour tout réinitialiser, et j'ai réinstaller juste vstream (dernière version et dernière source), et là, ça marche.

J'aurai du commencer par faire ça avant d'ouvrir un post et vous embêtez. J'y ai pas pensé... Désolé !

Ceci dit, je n'ai rien fait de particulier. J'imagine qu'il doit y avoir une autre extension qui, en se mettant à jour, à casser quelque chose dans kodi ? 

Bref, on peut mettre le sujet en résolu, puisque le problème n'a rien à voir avec vstream...

**Comment by johngf** [comment]
Aucune idée
