### ISSUE TITLE
Erreur vStream !

### ISSUE THREAD

**Issue by luluvulcain** [Kodi-vStream/venom-xbmc-addons#941]
Il y a un soucis avec l’extension que j'ai sur Android TV car impossible de cliquer sur le contenu dans toutes les catégories (ca marche "Erreur vStream"). Quelqu'un peut m'aider ?

**Comment by johngf** [comment]
#931 si tu veut de l'aide commence deja par répondre au sujet(issue) que tu ouvre
sinon il nous faut le log de kodi
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

**Comment by luluvulcain** [comment]
Merci pour ton Aide johngf mais j'ai régler le problème en réinstallant tout.

**Comment by johngf** [comment]
quand c'est résolut signale le comme ça on ferme l'issue

**Comment by luluvulcain** [comment]
ok ben tu peux fermer l'issue car mon problème est résolu.

**Comment by johngf** [comment]
ok
