### ISSUE TITLE
Recherche multiple k.o si kodi < 16

### ISSUE THREAD

**Issue by Kodigoal** [Kodi-vStream/venom-xbmc-addons#942]
Je sais pas si on doit s'embêter à résoudre ce soucis pour garder une rétro compatibilité  pour les versions Kodi < 16..
Mais la recherche multiple ne fonctionne plus via
la fonction xbmcgui.Dialog.multiselect  qui n'est pas disponible sous kodi 15 et 14.
http://pastebin.com/fF0wtSh2
Comme dit, pas très handicapant , le reste est fonctionnel.

**Comment by johngf** [comment]
c'est normal http://kodi.wiki/view/Jarvis_API_changes la fonction n'existe pas avant jarvis

**Comment by Kodigoal** [comment]
Oui de mon côté, je peux me passer de la recherche multiple ou soit maj kodi c'est vrai xD 
Mais je pense toujours a ceux qui peuvent pas maj ou qui aime rester sous d'ex versions Kodi pour x raisons.
Garder une rétro compatibilité même si tout n'est pas fonctionnel à 100% , ca peut pêtre en sauver certains.

**Comment by LordVenom** [comment]
Pour faire le multiselect des paramètre sélectionner vos sources j'ai du créer un xml personnaliser et re-coder les metas.Beaucoup de travail pour un multiselect. Donc la pas de retro-compatibilité dsl trop de travail.

**Comment by Kodigoal** [comment]
Pas de soucis , c'était juste une question xD je cloture.
