### ISSUE TITLE
zone-telechargement.WS

### ISSUE THREAD

**Issue by marcelus123** [Kodi-vStream/venom-xbmc-addons#943]
Bonjour.
En faisant la mise à jour sous windows le site w ww.zone-téléchargement.ws a disparu.
Il reste w ww.zone-téléchargement.EU qui fonctionne mal.
Mémé problème aprés une mise à jour de vstream dans openelec linux.
Cette disparition est-elle volontaire ?

**Comment by Arias800** [comment]
Bonjour,
Je ne pense pas que ce soit normale chez moi les deux apparaisse et dans le code de zone-telechargement.ws il n'y a rien qui a pour but de le faire disparaitre (après j'ai survoler le code) mais je pense pas que ce soit volontaire

**Comment by johngf** [comment]
pour le eu c'est normal il est buggé en attente de quelqu'un le répare l'autre le .ws a été mis a jour il a peu
il devrait fonctionné

**Comment by Arias800** [comment]
J'ai trouve l'erreur de zone-telechargement.eu le site s'appelle maintenent zone-telechargement.ru

**Comment by johngf** [comment]
ba oui il est dans projet

**Comment by Arias800** [comment]
ah ok j'avais pas vu ^^

**Comment by marcelus123** [comment]
Résolu.
Il y a certainement eu un bug lors d'une mise à jour.
J'ai téléchargé le zip de la version béta sur lordvenom et tout est revenu.
