### ISSUE TITLE
problème streamase

### ISSUE THREAD

**Issue by kenbest69** [Kodi-vStream/venom-xbmc-addons#944]
Bonjour à tous, 
Je pense qu'il y a un soucie je ne sais pas si sa vient que de chez moi. Mais je n'ai plus aucune jaquette de films et quand je clique sur un film (que ce soit n'importe lequel) il n'y a aucun lien de dispo :/

**Comment by TmpName** [comment]
Exact.
J'y jette un oeuil

**Comment by Arias800** [comment]
Personnellement j'ai les jaquette avec les option comme "dernier film ajoute" par contre je soulève un autre problème car "dernier série ajoute" retourne l'erreur 404

**Comment by Arias800** [comment]
Pour le probleme des serie il faut juste changer le URL_MAIN_SERIE par 'http://serie.streamase.com/' a la place de  'http://series.streamase.com/'

**Comment by TmpName** [comment]
Ha mince j'ai corrige le reste, mais pas les series.
Du coup le fichier passera en MAJ auto dans quelques jours, je vais pas tout relancer juste pr un fichier.

Je met en place ta correction.

**Comment by Arias800** [comment]
Au pire ouvre une issue pour précisé que les série vont être fix pas qu'il y est des demande

**Comment by kenbest69** [comment]
Merci l'équipe vous êtes au top et toujours très réactif
