### ISSUE TITLE
Probleme zone-telechargement.ru

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#949]
Voila l'erreur qui apparaît dans les log : URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
Apres des recherche plus approfondit j'ai trouvé ce lien :http://stackoverflow.com/questions/33972671/downloading-https-pages-with-urllib-error14077438ssl-routinesssl23-get-serve
Ou il explique que ça peut être liée a un problème de support mais question est la suivante qu'elle version de python vstream utilise ?

**Comment by johngf** [comment]
Ça veut dire en gros qu'il faut kodi 17 pour que ça fonctionne kodi inferieur ne gere pas le ssl

**Comment by Arias800** [comment]
d'accord

**Comment by johngf** [comment]
Mais kodi 17 n'a plus de cache pour l'instant ce qui rend penible l'utilisation de vstream
Ça sera surement resolu avec kodi 17.1

**Comment by Arias800** [comment]
D'accord de tout facon kodi 17 je vais l'utilise juste pour voir si les changement que j'ai effectue sur zone-telechargement.ru fonctionne

**Comment by Arias800** [comment]
Voila zone-telechargement.eu en version fixe pour kodi 17 lien : http://pastebin.com/S5Gy2i8j

**Comment by TmpName** [comment]
J'ai pas suivis toute l'histoire, mais si tu as apporte une correction, modifis directement la version du github.
Plus facile pour nous de voir les difference, et de suivre les modifs.
Pas de danger, ca ne touchera pas au coeur de Vstream, et il y a la possibilite de revenir en arriere, (et j'ai souvent fait bugger Vstream avec des code foireux) donc n'hesites pas.

**Comment by johngf** [comment]
Pour resume ne fonctionnera que sur kodi  17

**Comment by Arias800** [comment]
J'ai juste change les url et ca marche chez moi avec kodi 17 comme @johngf  la preciser

**Comment by TmpName** [comment]
Fichier mit en ligne
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/zone_telechargement_eu.py
En mettant une info sur la version de kodi.
