### ISSUE TITLE
Possibilité d'ajouter une entrée au menu contextuelle

### ISSUE THREAD

**Issue by mmtest1** [Kodi-vStream/venom-xbmc-addons#950]
Bonjour,
j'utilise quotidiennement votre extension avec grand plaisir et je souhaiterai soumettre une proposition quand à l'ajout d'une entrée dans le menu contextuelle au niveau de la recherche si cela est possible et peut-être utile à d'autre. 
Au fur et à mesure de l'utilisation de vstream l'historique de recherche a tendance à s'alourdir entre films, séries, ..., il y a bien la possibilité de supprimer l'ensemble de l'historique mais pas un ou des éléments en particuliers, alors que lorsque l'on à regarder un film il y a peu de chance de le regarder à nouveau, une recherche sur les séries à une durée de vie plus longues par exemple. Il serait peut-être intéressant d'ajouter à : "Voir marque page, Ajouter au favoris", "Supprimer l'entrée" (ou quelque chose dans le style). Cela permettrait de maintenir une liste fluide et un chargement plus rapide de cette catégorie (je tourne encore sur rpi b+ et osmc) sans devoir retaper à la télécommande les séries en cours après une suppression complète.
Si je suis le seul dans ce cas la cela ne vaut certainement pas le coup de coder cette fonction mais je suppose que pouvoir gérer son historique est un plus pour l'extension et les utilisateurs.
Dans tous les cas je vous remercie pour votre excellente extension,
bonne soirée

**Comment by Arias800** [comment]
Bonnes idées faut voir ce qu'en pense d'autre personne mais  moi je trouve ça pas mal comme idée

**Comment by johngf** [comment]
bon je viens de le faire et testé c'est ok par contre pour l'instant on ne peut utilisé que le titre comme filtre
donc si il y a x fois le meme titre ça supprime x fois l'entrée

**Comment by Kodigoal** [comment]
Et après recherche d'une série , mettre 1 résultat en marque-page d'un site préféré ou fiable , et ensuite à partir du marque-page on peut relancer une recherche  si on veut...
ex: mis série en marque-page à partir d'une recherche , par la suite soit la série toujours dispo via le site , soit on relance une recherche simulaire.
https://s14.postimg.org/6h0mcbvv5/foto_no_exif.jpg

**Comment by johngf** [comment]
@Kodigoal c'est deja le cas si c'est une saison si c'est un épisode on peut pas oui

**Comment by mmtest1** [comment]
merci pour le suivi, c'est vrai que je n'ai pas l'habitude d'utiliser les marque-pages, il faut que j'essaie, la gestion de l'historique de recherche peut-etre complementaire dans tous les cas
@johngf la modification sera prise en compte dans la prochaine maj ?

**Comment by TmpName** [comment]
La prochaine MAJ complete (la mensuelle) surement.

**Comment by mmtest1** [comment]
En attente de la v.0.5.0, il y a du ménage à faire dans ma liste...
Merci beaucoup pour votre extension et votre réactivité
bonne soirée

**Comment by johngf** [comment]
Bon apres j'avais pensé a coupé le son de la popup info vu que si on en supprime plusieur a la suite
... ça risque d'etre pénible. Je sais pas

**Comment by Kodigoal** [comment]
xD la chasse aux sons 
Pour ton code siteuptobox , ca serait pas mal un 'supprimer' aussi , ou trop chiant à faire ?

**Comment by johngf** [comment]
Supprimer sur le site a partir de vstream non c'est faisable je jetterai un oeil plus tard

**Comment by Kodigoal** [comment]
Ok merci , enfin si tu trouves que ca peut être un plus , sinon pas la peine de t'embéter avec ca ^^

**Comment by johngf** [comment]
Bah perso j'utilise pas uptobox si les hosters du genre si je trouve sur les autres
Mais je vais voir comme meme

**Comment by johngf** [comment]
@Kodigoal  test celle la on peut renomer fichier et dossier suprimer fichier et dossier
[https://github.com/johngf/divers/blob/master/kodigoal/siteuptobox.py](clique ici)

**Comment by Kodigoal** [comment]
@johngf  Testé, tout est ok. Merci.
