### ISSUE TITLE
openload bis

### ISSUE THREAD

**Issue by stevebou** [Kodi-vStream/venom-xbmc-addons#951]
Bonjour,

je reviens vers vous car le problème signalé ici n'est finalement pas complêtement résolu :

https://github.com/Kodi-vStream/venom-xbmc-addons/issues/940

Je n'arrive à nouveau plus du tout à accéder aux liens open load. Par exemple, dans Films(HD)>Film illimite, j'ai pris le premier de la liste.
Le log me trouve bien le lien, puis j'ai à nouveau "fichier introuvable" :

Pour être sûr cette fois, j'ai effacé le répertoire .kodi de mon home, et je n'ai installé que l'extension vstream, à partir du repository, la version beta 0.4.9, afin d'être certain que ça ne viennent pas d'une interférence avec une autre extension.

Quelqu'un a-t-il une idée ?

(Je suis sous ubuntu, version de kodi 16.1)

Merci d'avance.

**Comment by Arias800** [comment]
Chez moi le lien ouvert (dans le navigateur) affiche fichier introuvable cela expliquerai pourquoi tu ne peux pas l'ouvrir ^^

**Comment by johngf** [comment]
Chez moi open load est HS sur vstream aujourd'hui

**Comment by Arias800** [comment]
Effectivement openload ne fonctionne pas sur vstream c'est bizarre je l'ai utilise ce matin ^^

**Comment by stevebou** [comment]
ok. 

Par contre, pour le lien, il est pas hs. Il faut le copier dans une fenetre "vierge" et il se lance. En tout cas, chez moi c'est le cas (je viens de reessayer sur le lien donné plus haut, après deux fenetres popup inutile, le film part...

En tout cas, je suis rassuré de voir que ça ne marche pas chez vous non plus sur vstream.

**Comment by johngf** [comment]
c'est bon jusqu'a la prochaine modif perso je clic sur open load qu'en dernier choix ça déconne souvent

**Comment by johngf** [comment]
de nouveau HS
