### ISSUE TITLE
Question suite MAJ Kodi 17

### ISSUE THREAD

**Issue by ballost** [Kodi-vStream/venom-xbmc-addons#957]
Bonjour a tous

encore merci pour le taf des développeurs ....
j'ai une petite question : depuis la MAJ en kodi 17 sur android, lorsque l'on a recherché un film et que l'on est allé jusqu'à le lancer, lorsque l'on arrête et veut revenir à la liste des sources et liens, la recherche se relance automatiquement pour réafficher cette liste

avant, la liste provenant de la première recherche était affichée sans relancer la recherche

J'espère avoir été clair :)
aviez vous une idée si cela peut se corriger car cela prend du tps si on veut naviguer entre les sources

Merci d'avance
Cordialement
ballost

**Comment by johngf** [comment]
Sujet plusieur fois discuté c'est a cause de kodi 17 le probleme sera surement resolu d'apres ce qu'on a lu avec kodi 17.1

**Comment by Arias800** [comment]
J'utilise kodi 17.1 et je confirme que le problème est réglé

**Comment by johngf** [comment]
Ah il est sortis j'avait pas vue

**Comment by TmpName** [comment]
Haaaaaaaaa ^^, j'ai jamais ete aussi content de voir une nouvelle version.

**Comment by Arias800** [comment]
Elle est en beta faut prendre la nightly build mais chez moi ca tourne très bien j ai pas eu de bug particulier

**Comment by ballost** [comment]
Merci johngf

je n'avais pas trouvé clairement le sujet dsl
je l'ai trouvé après mon post :)
comme c sur ma télé android , j'attendrai la release offciciel 17.1 et la mise a jour

Cdlt

**Comment by Arias800** [comment]
Kodi 17.1 a sa premier release officiel ^^

**Comment by Allonsbon2004** [comment]
Est ce que la recherche visuelle fonctionne chez vous ? Moi j'ai erreur Vstream.

**Comment by LordVenom** [comment]
Une mise a jour non compatible avec le coeur actuelle et passer ça nous arrive souvent dsl.

2 solution

- attendre la mise a jour officielle bientôt
- installer la bêta

**Comment by Allonsbon2004** [comment]
Pas de soucis, je vais attendre.

**Comment by LordVenom** [comment]
Arff pas de mise a jour sur fedora.

**Comment by kikikodi** [comment]
Lordvenom tout d'abord un grand bravo à toi superbe boulot! 
Une question quand tu parles d'attendre la MAJ TUNPARKES DE LA VERSION 18? Ou il y en aura une intermédiaire qui ne sera pas en bêta ? 
Est-ce que le problème définit ici est bien le fait que lorsque l'on lance un film depuis l'onglet recherche visuelle celui-ci indique une erreur et ne se lance pas ? J'ai effectivement ce problème egalement: 
Aussi j'ai vu que des box Android propose une version 7.0, est-ce que cette version sera nécessaire pour faire tourner kodi 18? 
Merci de ta réponse 
Mika

**Comment by kikikodi** [comment]
Désole pour les majuscules l'iPhone est resté verrouillé

**Comment by kikikodi** [comment]
@johngf je viens de découvrir kodi la semaine dernière dernière, je mélange peut d'être un peu tout 😜
Vstream de st censé se metre a jour automatiqueme t si dans les réglages de kodi la fonction mise a jour automatique est activée ou bien il faut le faire différemment

**Comment by johngf** [comment]
Vstream se met a jour automatiquement

**Comment by TmpName** [comment]
Il y a 2 mises a jour.
Celle du coeur de Vstream (actuellement la V 5.0) celle la est geree par kodi (1 fois par mois).
Les fichiers "sites" et "hosts " verifies tout les 3 jours

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Mise-%C3%A0-jour

**Comment by patoche2025** [comment]
Bonjour à tous,

Je me doute que la question a déjà été posté mais je retrouve pas la solution, du coup je permets de la reposer comment fait on pour les captchas sur kodi 17, le captcha apparaît puis disparaît quand le clavier arrive désolé de reposer encore la même question

D'avance je vous remercie

**Comment by LordVenom** [comment]
Change de theme.

**Comment by johngf** [comment]
@patoche2025 c'est quel site ?

**Comment by patoche2025** [comment]
@johngf Salut moi j'ai ça sur la source DDL-Island et @LordVenom Ok je vais regarde pour changer de thème merci

**Comment by kikikodi** [comment]
Bonsoir, 
Y a t'il une solution pour simplifier la lecture d'un film ou pas, parceque pour en lancer un il y a un série de validation avant d'arriver à la bonne sources entre nous plutôt compliquee. 
Autre chose est il possible de supprime toutes mes sources openload et autres qui nécessitent un compte ?

**Comment by TmpName** [comment]
Une serie de validation ?
Openload ne necessite pas de compte.
Il doit y avoir 2 hebergeurs a tout casser qui demandent un compte.

**Comment by LordVenom** [comment]
La recherche visuelle ?

**Comment by johngf** [comment]
Je pense qu'il parle des clics ou captcha ou autres pour arriver a la source final playable 
@kikikodi  vstream c'est comme un navigateur internet 

Pour un film tu choisis ton film,l'hébergeur de la video,puis lecture
Pour une serie ou anim tu choisis la serie,saison episode ,hebergeur ,puis lecture etc....
Certains site protege les liens donc parfois t'est obligé d'ajouté un clic pour le choix

Supprimer ou filtrer les sources au cas par cas c'est pas possible

Note: ce qui est possible c'est la lecture automatique sur le liens hébergeur que je teste en ce moment
(sans ralentissement)

**Comment by kikikodi** [comment]
Merci pour ta reponse,
Ce que j'essayes de vous expliquer c'est que lorsque j'arrive sur la liste
des différents liens(version plus complexe) c'est un peu le fouilli,
franchement ridicule de s'y retrouver, une fois que tu trouve un lien ok,
tu dois de nouveau choisir le lecteur, ZStream, flashsx... La aussi
certains lecteur/ou hébergeurs nécessite(en tout cas pour moi sur openload
par exemple d'aller sur une page internet si j'ai bien compris. Ma question
est est-ce normal ou non? Si oui estce que je peux décider de retirer
openload dans les réglages de vstream de manière à ce qu'il ne me soit plus
proposé ?
quand tu dis que tu test  le lien hébergeur , tue parles de quoi exactement
?

Merci

**Comment by kikikodi** [comment]
Merci pour ta reponse, 
Ce que j'essayes de vous expliquer c'est que lorsque j'arrive sur la liste des différents liens(version plus complexe) c'est un peu le fouilli, franchement ridicule de s'y retrouver, une fois que tu trouve un lien ok, tu dois de nouveau choisir le lecteur, ZStream, flashsx... La aussi certains lecteur/ou hébergeurs nécessite(en tout cas pour moi sur openload par exemple d'aller sur une page internet si j'ai bien compris. Ma question est est-ce normal ou non? Si oui estce que je peux décider de retirer openload dans les réglages de vstream de manière à ce qu'il ne me soit plus proposé ? 
quand tu dis que tu test  le lien hébergeur , tue parles de quoi exactement ? 

Merci 

Le dim. 12 mars 2017 à 07:23, johngf <notifications@github.com> a écrit :
Je pense qu'il parle des clics ou captcha ou autres pour arriver a la source final playable
@kikikodi vstream c'est comme un navigateur internet

Pour un film tu choisis ton film,l'hébergeur de la video,puis lecture
Pour une serie ou anim tu choisis la serie,saison episode ,hebergeur ,puis lecture etc....
Certains site protege les liens donc parfois t'est obligé d'ajouté un clic pour le choix

Supprimer ou filtrer les sources au cas par cas c'est pas possible

Note: ce qui est possible c'est la lecture automatique sur le liens hébergeur que je teste en ce moment
(sans ralentissement)

**Comment by kikikodi** [comment]
Pas "ridicule" mais "difficile"

**Comment by johngf** [comment]
bon explication:
-hebergeur = openload,youwatch,flashx etc ... ce que tu appelle lecteur

-"c'est que lorsque j'arrive sur la liste des différents liens(version plus complexe)"
ce n'est pas une liste de liens playable que tu as  mais une liste d'url 
qui aprés clic active une fonction qui trouvera le vrai lien playable par kodi
normalement le dernier lien qui permet de lire la video est bleu ciel openload youwatch etc...

--bien que sur certain site certaine personne ont mis du bleu ciel la ou il ne fallait pas --

aucun hébergeur video openload y compris ne nécessite d'aller sur son site pour qu'il fonctionne 
le soucis viens de chez toi
tu viens de quel pays ?

**Comment by TmpName** [comment]
Tu utilises l'urlresolver ? Lui demande de passer par le net, pas si tu passes directement par Vstream.

**Comment by johngf** [comment]
il est rarement mis a jour ce truc il faudrait le réservé seulement pour certain hébergeur de dl

**Comment by kikikodi** [comment]
Bein je sais se que j'utilise j'ai juste installe vstream ultrastream exodus ... Et a chaque fois que je lance openload il est écrit ouvrir ce lien ( redirection vers openload.com...) me demandant de cliquer dessus mais je ne peut rien faire. Et apres plus rien ... Estce normal ou pas ? Et je suis en France, idem depuis Freebox et tout révèlent chez bbox
Le mieux c'est d'utiliser alluc ou lien plus complexes?

**Comment by kikikodi** [comment]
Et oui j'ai bien urlresolver mais je pense qu'il sert aussi aux autres addons

**Comment by kikikodi** [comment]
@johngf
Effectivement j'ouvre aussi mes addons depuis les favoris, je ne savais pas que cela causait des problèmes. 
Il faut vider le cache systématiquement ou on peut le faire automatiquement ? 
Merci

**Comment by johngf** [comment]
Dans les parametres de vstream desactive le 
Pour openload faudra attendre la maj il etait hs depuis quelque heure je viens de le mettre a jour

**Comment by phpag** [comment]
bonjour à tous, je viens de passer de Kodi 16 à la version 17 et je ne retrouve plus les marques pages.  Merci d'avance pour les réponses.
