### ISSUE TITLE
2 petites améliorations utilies

### ISSUE THREAD

**Issue by canopre** [Kodi-vStream/venom-xbmc-addons#958]
J'espère qu'en plus elles ne seront pas trop compliquées !

Mais ca serait bien pratique dans les options de pouvoir ;

1 - Désactiver Alluc qui donne des résultats tellement aléatoire que je ne l'utilise vraiment jamais : et ma femme encore moins :)

2 - Activer les meta sans activer le fanart en background : il faudrait que ces 2 options soient séparées : qu'on ne soit pas obligé d'afficher les fanarts en background quand la recherche par méta est activée.

En espérant que ca sera utile à d'autre et peut-être avoir ces nouvelles fonctions à l'avenir.

Merci d'avance et encore merci pour ce super addon !

**Comment by johngf** [comment]
pour alluc il ne s'active que si tu clic dessus sinon il ne fonctionne pas, n'est pas pris en compte pour la recherche si tu pense a la popup vstream alluc elle ne sera plus la avec vstream 5 pour bientot

**Comment by canopre** [comment]
Salut John et merci pour ta réponse rapide.

Oui oui : je pensais bien à la popup choix vstream/alluc.

Alors vivement la V5 !

Et pour ne pas afficher les fanart en background quand on active les métas ? Une idée ?

Les métas : c bien pratique !

Mais le fanart en background : ca gène souvent pour lire .... les métas :)

Bon we à tous et encore 1000 mercis !

**Comment by TmpName** [comment]
Y aurait pas un reglage directement dans kodi pour ca ? Au niveau du skin peut etre.

**Comment by TmpName** [comment]
Trouve !
Parametres/interface/habillage/configurer l'habilage/Arriere-plan/....
