### ISSUE TITLE
Regex aide

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#959]
Je cherche a ajouté une source mais je n'arrive pas a trouve le regex du coup je suis allez sur le site regexr(http://www.regexr.com/3fcqt) pour m'aide mais malheureusement j'ai trouve un regex qui me permet de récupéré l'url sur regexr mais il ne marche pas sur kodi rien ne se passe
Merci d'avance

**Comment by johngf** [comment]
quel site ?

**Comment by Arias800** [comment]
le site c'est coco-stream.com

**Comment by Arias800** [comment]
Enfaîte c'est bon j'utilise une version de sauvegarde de mon script mais pas celui qui est dans kodi ^^
