### ISSUE TITLE
Probleme url coupe

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#960]
Alors voila mon probleme je voudrai ajoute le site coco-stream.com mais le probleme c'est que kodi obtiens des url coupe (sans coco-stream.com)devant ma question est comme le faire apparaitre devant l'url qui est coupé

Edit: 
Lien pastebin : http://pastebin.com/iHUg1zpS

**Comment by johngf** [comment]
bah url_dusite + 'urlcoupé' ex URL_main + '/lien'

**Comment by Arias800** [comment]
Oui mais c'est l'url recupére par le regex qui est coupé donc je vois pas oui je doit place URL_MAIN

**Comment by johngf** [comment]
bah url_dusite + 'urlcoupé' 
ex url = URL_MAIN + 'ton bout d'url'

**Comment by Arias800** [comment]
C'est bon j'ai reussit ^^
