### ISSUE TITLE
Flax again :)

### ISSUE THREAD

**Issue by Turk182es** [Kodi-vStream/venom-xbmc-addons#962]
Salut,

VStream c'est mis à jour aujourd'hui et et les FlashX ont été remplacé par une vidéo en boucle comme la dernière fois.

De plus j'ai pas mal d'erreur de fichiers introuvable sur Openload, Youwatch etc... mais j'ai pas tout vérifie.

Par contre pour Flash X c'est sur.

Encore merci pour votre super boulot!

Stephane

**Comment by johngf** [comment]
You watch et open load sont ok pour open load tu n'as sans doute pas la derniere version
Flash t'as surement raison

**Comment by Turk182es** [comment]
C'est possible pour les deux mentionnés ke me suis basé que sur un seul film. Par contre FlashX c'est du sur.

**Comment by TmpName** [comment]
Yep on recupere trailer.mp4 au lieu de la bne video, chez moi ca tourne pas en boucle mais y a bien un prb.
Par contre je ne peux pas non plus ce soir, apero time.

**Comment by Arias800** [comment]
J'ai trouve pourquoi ça affiche ça en faite flashx bloque xbmc;kodi comme les bloqueur de pub

**Comment by TmpName** [comment]
Bien joué @johngf , put1 suis degoute, ca aurait presque pu durer 1 semaine de plus sans corrections.

**Comment by johngf** [comment]
Pour ce genre de hoster les 3 jours avant maj sont un probleme

**Comment by TmpName** [comment]
Le temps de s'en apercevoir, signaler, corriger, sur les 3 jours reste pas trop longtemps a tourner sur un hoster de secours.

Edit:
et merde, j'ai encore oublie. De mettre la correction en MAJ auto aussi, ca aide

**Comment by johngf** [comment]
C'est quoi maj auto ? celle sans cliqué ? mais faut comme meme respecté le delais de 3j

**Comment by TmpName** [comment]
Yep (enfin si, faut cliquer, je parlais de celle de 3 j), mais si comme un con j'attend quelle passe toute seule en maj auto, elle risque d'attendre longtemps sur la version beta.

Ce que je voulais dire, c'est qu'il y a deja 33% qui pourront mettre a jour dans moins de 24h. Je trouves pas ca abuse comme delais 3 jours. Le plus malchanceux etant celui qui c'est apercu que ca marchait pas et qui justement fait la maj 5 mn avant ta correction ^^.

**Comment by johngf** [comment]
@Turk182es t'as eu la maj ?

**Comment by Turk182es** [comment]
J'ai pas l'impression car ce soir ca marchait toujours pas.
Demain je refais un essai !
