### ISSUE TITLE
Site dangereux

### ISSUE THREAD

**Issue by Arias800** [Kodi-vStream/venom-xbmc-addons#967]
Bonjour,
Je vous invite a retirer megatrackmovies car il est dangereux preuve  : https://www.virustotal.com/fr/url/de05002048948e935a208f9b52d3532297a138572bbf934b2bfcef325ee03d33/analysis/1488266089/

**Comment by LordVenom** [comment]
Pas grave ça les fichier de Master sont simplement une sauvegarde des fichiers correct la mise ajour mensuelle ce fait depuis les .zip

**Comment by LordVenom** [comment]
@Arias800 même si le site et bourrer de pub ou de malware je doute qu'il arrive a passer via une requête python.

**Comment by Arias800** [comment]
@LordVenom c'est pas faut mais bon personnellement je préféré prévenir que guérir ^^

**Comment by LordVenom** [comment]
Pour prevenir mais toi sous Linux :+1:

**Comment by Arias800** [comment]
Personnellement Linux j'aime pas trop :/

**Comment by johngf** [comment]
Mis dans trash
