### ISSUE TITLE
Fichier introuvable 

### ISSUE THREAD

**Issue by YasinGS** [Kodi-vStream/venom-xbmc-addons#969]
Bonjour, tout d'abord j'aimerais vous remercier pour cet addons, il y a tout. Merci beaucoup. Voilà maintenant depuis quelque semaines j'ai un problème, lorsque je clique sur le replay j'ai le message suivant : fichier introuvable. J'ai regardé le logs, j'ai essayé de regarder sur le navigateur c'est bon mais sur kodi ça ne marche pas. Que ce soit Openload ou autre cela ne fonctionne pas. 
Voici le logs : https://ares-project.uk/logupload/log.php?id=1042441
Je suis sous Android et j'ai la version 16 de kodi

**Comment by Arias800** [comment]
Chez moi ça fonctionne donc soit tu mets a jour les fichier d'openlaod et d'estream manuellement soit tu attend la mise jour qui devrait arriver dans quelque jours

**Comment by YasinGS** [comment]
Mais c'est un problème de plusieurs semaines.. Même après plusieurs mise à jour il n'y a rien qui a changer.

**Comment by Arias800** [comment]
Bon bah c'est peut être bien la version de vstream qui est en cause car moi j'ai kodi 17.1 et ça marche très bien

**Comment by LordVenom** [comment]
Pas de soucis chez moi avec les lien openload et buzzmonclick

**Comment by Arias800** [comment]
Quel version de kodi @LordVenom  ?

**Comment by LordVenom** [comment]
17.0

**Comment by Arias800** [comment]
Donc ça doit bien être un problème de kodi 16

**Comment by YasinGS** [comment]
Je vais essayer avec la version 17

**Comment by YasinGS** [comment]
J'ai toujours le problème même avec krypton

**Comment by YasinGS** [comment]
J'ai essayé la version bêta de vstream et ça refonctionne..

**Comment by johngf** [comment]
Oui ça n'a rien a voir avec kodi 16 ou 17 des fois vidé les caches dans les parametres de vstream
pour certaines personnes qui n'arrive plus a lire de video fonctionne moi jamais eu de soucis

**Comment by TmpName** [comment]
D'ailleurs, c'est juste une impression pr le moment, mais a propos des caches, je trouve que j'ai plus souvent la MAJ propose sur la page home de Vstream, y a peut etre du mieux de ce cote.
