### ISSUE TITLE
Probleme recherche visuelle [Résolu]

### ISSUE THREAD

**Issue by Bundy01** [Kodi-vStream/venom-xbmc-addons#973]
Bonjour,

Depuis quelques temps, en faisant une recherche visuelle dans n'importe quelles catégories, aucun films ne s'affichent. J'ai changer de version de kodi (17 puis 17.1) sans succès. J'ai également changé la version de vstream (beta), idem.

En effectuant une recherche manuelle, pas de problèmes.
Je ne pense pas que ça vienne de votre super extension (au passage :) ) car exodus me fait pareil (aucun film) ainsi qu'une autre extension pour l'IPTV.

Si vous avez une idée, je suis preneur.
Merci en tous cas pour le travail accompli.

**Comment by Kodigoal** [comment]
Bonsoir,
Possible d'upload ton log kodi après avoir refait quelques fois tes manips de recherche qui posent soucis pour voir si on voit quelque chose.
Pour upload ton log par vStream Directement:
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Outil

**Comment by Bundy01** [comment]
Bonsoir,
je n'ai pas pu envoyer le log avec l'outil mais le voici: [http://dl.free.fr/wPOGvIcdX](url)
Merci.

**Comment by Kodigoal** [comment]
Bon ..  je vois pas d'erreur , pêtre mettre le mode debug sur ON dans kodi.
Tu dis aucun film ne s'affiche , genre les résultats après que la recherche soit lancée ? ou avant en allant dans les catégories recherche visuelle , rien ne s'affiche ? 
Si t'as testé la beta ( zip complet?) , c'est bizarre , ca devrait fonctionner.
T'arrive à aller par un navigateur sur https://www.themoviedb.org/documentation/api par exemple via ton poste ou ya kodi.

**Comment by johngf** [comment]
@Bundy01 #963 le recherche visuelle est hs jusqu'a la v5 de vstream

**Comment by Kodigoal** [comment]
Le truc c'est qu'il dit avoir tester la beta. ( via le zip dev je sais pas...)

**Comment by LordVenom** [comment]
La mise a jour et envoyer est ce que ça corrige ton probleme

@Kodigoal Il y a un lien pour télécharger la bêta depuis les releases beaucoup de gens veulent tester mais n'utilise pas Github.

**Comment by Kodigoal** [comment]
@LordVenom oui voilà , je parlais de ce lien (zip dev, mal exprimé lol ).
Si il a testé par ce biais , cela aurait dû fonctionner normalement.
Verra avec la mise à jour.

**Comment by johngf** [comment]
@Bundy01 essaies d'abord ce que j'ai demandé plus haut pour aider a savoir pourquoi ça fonctionne pas chez certains upload log si chez toi ça fonctionne pas les autres fonctions ne devrait pas non plus fonctionné clear cache etc.....

**Comment by Bundy01** [comment]
@Kodigoal: Après recherche visuelle, j'ai "film en salle , populaire, genres ... mais une fois dans la catégorie: aucun film. Avec mon navigateur, je peux aller sur le site que tu m'as fourni.

@johngf: J'ai effacer les thumbnails, il me reste que des dossiers vides (chiffres, lettres et vidéo)

J'avais pris la beta ici, j'ai essayé avec la v.5. Le problème est toujours là :( .
Pour le problème lié au up du log, vsteam me donne un lien mais quand je vais sur le site, il n'y a aucun log (sur la page: "The submitted URI contains characters that are not allowed.")

**Comment by LordVenom** [comment]
Hum.. vas prendre ton log toi même

https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Dossier-log

et colle le sur pastebin http://pastebin.com/

Je sais pas pourquoi mais ça sens le probleme de permission Linux ou Android ? lol

**Comment by Kodigoal** [comment]
@LordVenom Je sais pas si c'est juste chez moi , mais j'avais signalé dans une autre issue qu'il y a pêtre un soucis au niveau du fichier topimdb.py , fonction showMovies :
if URL_SEARCH[0] in sSearch:
Si recherche visuelle/TopImdb/ rien ne liste car URL_SEARCH non défini (  car commenté au début du script)
Ou j'ai loupé un truc ...
@Bundy01 Active dans les options de Kodi  par icone 'eventlog'  les options suivantes :
http://img4.hostingpics.net/pics/738338fotonoexif.png
Yaura plus d'infos dans le log pêtre.
Refait les manips de recherche  visuelle ou ca pose soucis et ensuite fais comme LordVenom te demande pour nous donner le log.

**Comment by Bundy01** [comment]
@LordVenom: J'ai penser aussi à un problème dans mon dossier .kodi, je l'ai donc effacer mais impossible de réinstaller a partir du repo voici le log [http://pastebin.com/x91APwjA](url)

Je ne pense pas que ce soit du aux permission car j'utilise l’extension depuis un moment sans problèmes

**Comment by Bundy01** [comment]
Bon,
j'ai installer vStream en manuel et ça refonctionne. Je viens d'y penser mai j'avais créer un fichier advancedsettings.xml dans userdata contenant:
`<advancedsettings>
    <network>
        <buffermode> 1 </buffermode>
        <readbufferfactor> 1.5 </readbufferfactor>
        <cachemembuffersize> 104857600 </cachemembuffersize>
    </network>
</advancedsettings>
Ce fichier me permettait de régler des problème avec le cache de kodi. Pensez vous que ça puisse venir de ce fichier ?`

**Comment by TmpName** [comment]
Non, aucune chance pour moi que cela vienne de la.

**Comment by Bundy01** [comment]
Ok,

je ne vois pas ce qui déconnait, mais le sujet est résolu.

Merci pour votre aide et pour cette super extension :)

**Comment by Kodigoal** [comment]
@Bundy01 Et pour ton soucis d'install de vStream par le repo,  utilise le repo d'ici( ceux dispo par dépôt Fusion et cie ne sont pas à jour chez eux, d'ou le soucis pour l'install de vStream )
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository

**Comment by Bundy01** [comment]
@Kodigoal: Il s'agissait bien de ce repo

**Comment by Kodigoal** [comment]
@Bundy01 mystère de l'informatique alors xD
