### ISSUE TITLE
Erreur de lecture KODI V17.0 via Synology

### ISSUE THREAD

**Issue by paulnoelandry** [Kodi-vStream/venom-xbmc-addons#979]
Bonjour,

je possède un DSM 211J dont je me sert pour divers utilisations et notamment comme source pour regarder des films au format HD.

Je lis les films par l'intermédiaire de la nvidia Shield avec l'application KODI v17.0. Depuis la dernière mise à jour du DSM 6.1-15047, je vois toujours ma source mais lorsque je la sélectionne après plusieurs secondes un message d'erreur apparais : "un ou plusieurs fichiers ne peuvent être lus" .

je ne trouve pas quelle modification apportée pour régler ce problème.

 

Auriez vous une solution ?

 

Merci pour votre aide

**Comment by johngf** [comment]
Ton soucis n'a rien a voir avec vstream ? Mais kodi lui meme

**Comment by vic1997** [comment]
Je ne sais pas si c'est la même erreur que moi, mais ça me le fait également (sur Vstream, après j'ai pas testé sur d'autres programmes) sur les live TV sur Framapad, ça me dit que le fichier ne peut pas être lu avec une erreur, alors qu'en fond ça s'allume haha mais quand on appuie sur le "OK" de l'erreur ça quitte. Du coup c'est bizarre, mais j'ai trouvé une solution c'est de ré-essayer et l'erreur n'apparait plus et on peut continué à regarder.

**Comment by johngf** [comment]
@vic1997 framapad n'est pas fiable et ne le sera jamais les liens sont souvent hs et tous le monde peut en ajouté #678 
Certain mettent des liens qui finnisent par tsdownloader qui ont besoin d'un autre plugin pour fonctionné 
Bien qu'en les editant correctement on peut ce passé de ce plugin

**Comment by TmpName** [comment]
C'est quoi deja la bidouille ?
J'ai essaye de remplacer l'extension par m3u8 ca a pas marche ?

**Comment by vic1997** [comment]
@johngf Oui, mais l'erreur n'est pas là. Framapad marche bien chez moi, il y a juste une erreur qui n'en est pas une vu que ça marche ! (ça m'affiche une erreur comme quoi ça marche pas mais en arrière plan y a le stream qui commence et ça marche, problème, quand on clique sur OK sur l'erreur, ça annule le stream) La solution est simple c'est de simplement allumer une deuxième fois le stream et l'erreur n'apparait plus et on peut voir le stream !

**Comment by TmpName** [comment]
Chacun son probleme ^^
Moi ca marche du premier coup, mais juste 10s, du coup me dit que le fichier n'est pas trop "incompatible" avec le lecteur de base de kodi.

**Comment by johngf** [comment]
@TmpName quand il y a ts downloader tu les met comme sur le framapad actuel

**Comment by TmpName** [comment]
Ha mince c'est deja modifie ?
Bon alors j'ai un prb :).
Ca charge le fichier mais ca ne charge que 10s, on voit la barre de progression, et une fois au bout, ca coupe.

**Comment by johngf** [comment]
Ba oui debit insuffisant du serveur de l'url pas de cache donc ça coupe

**Comment by TmpName** [comment]
Ok, je pensais que ca venait de moi.

**Comment by johngf** [comment]
Quand l'audio arrive a 0% kodi coupe la video c'est le soucis des ts et m3u8 il faut un debit constant et elevée

**Comment by vic1997** [comment]
Ayant un débit très bas je m'en doutais (je n'utilise pas le streaming framapad pour le moment mais je me prépare pour quand j'aurais la fibre dans 4 mois) car ça coupe aussi au bout de plusieurs seconde (ça varie, ça peut être moins de 10 secondes ou carrément 2 minutes).
Après si c'est le serveur on peut rien faire.
