### ISSUE TITLE
Petit question pour kodi 17

### ISSUE THREAD

**Issue by patoche2025** [Kodi-vStream/venom-xbmc-addons#980]
Bonjour à tous voilà je m'explique je possède une box android sous android 4.4 et ce matin j'ai voulue Kodi 16.1 en 17 mais voilà il me dit que c'est pas compatible avec mon android d'ou la question qui suit est ce que vstream va rester compatible avec la version kodi 16.1 ou il y a un moment j'aurais pas d'en acheter une autre qui sera sous une version plus récente d'Android.

D'avance je vous remercie

**Comment by johngf** [comment]
Oui tu peux resté sous kodi16.1 qui fonctionne tres bien pas besoin de kodi17 ou d'acheter une autre box
Vstream sera compatible pour longtemps encore
Il y en as qui sont encore sur la 14 ou la 15 de kodi et ça fonctionne

**Comment by patoche2025** [comment]
Génial merci @johngf

**Comment by johngf** [comment]
Perso je suis sur kodi 16 suivre de suite les nouveautés ne rapporte que des bugs

**Comment by Arias800** [comment]
Chez moi ca marche meme avec kodi 12 donc bon ^^

**Comment by patoche2025** [comment]
Mille merci pour vos réponses @johngf et @Arias800
