### ISSUE TITLE
Pb sur différents sites

### ISSUE THREAD

**Issue by ttrd06** [Kodi-vStream/venom-xbmc-addons#985]
bonjour à tous,
pour infos plusieurs sites utilisent maintenant sucuri en protec comme voirfilms, sokro ... d'autres ne fonctionnent plus (nouvelle adresse ?) comme official-film-illimite par ex
j'ai réussi en dur à transformer les pages pour voirfilms et utiliser sucuri: ça fonctionne (certainement 2 secs pour tmpname :-) )
mais pour poster une recherche sur voirfilm avec sucuri dedans, ben la .... je seche ...

**Comment by TmpName** [comment]
Pour voirfilm, c'est bon la protection a ete desactivee.
J'esite a la mettre en auto dans le coeur de vstream, mais la de toute facon c'est foutu vu que la MAJ complete a eu lieu recement.

pr officialillimite pas trouve nouvelle url.

sokro je m'y met de suite.

**Comment by Kodigoal** [comment]
official film illimité, le site devait être down , là de nouveau en ligne serveur web mais encore rien dessus, faut attendre pour voir...

**Comment by TmpName** [comment]
J'ai mis en place un patch provisoire pour sokro, mais comme pour cloudflare me faut modifier la fonction pr gerer le POST.

**Comment by ttrd06** [comment]
@TmpName compte sur moi, pour le moment et à part ceux que j'ai indiqué le reste fonctionne.
ce matin, voirfilm a jonglé pendant plusieurs longues minutes entre cloudflare + sucuri et inverse, puis cloud seul et enfin terminer par sucuri.
Incroyable ...
j'avais écris une fonction pour gérer les 2 puis au bout de 2 heures, ils sont restés sur sucuri.

**Comment by TmpName** [comment]
Mais hier, il etait completement off, peut etre que depuis qu'ils sont sur exodus, il se font bombarder de requetes.

**Comment by johngf** [comment]
@ttrd06 tu n'as pas bien verifié strea may cloudflare puis vide papy streaming crash du serveur .......

**Comment by TmpName** [comment]
Ca fait beaucoup en 2/3 jours !
C'est le meme hebergeur, (cloudflare) ou il y a une attaque sur les sites de stream ?

**Comment by TmpName** [comment]
Strmaway, c'est bizarre, ca m'affiche decode cloudflare mais rien. Alors que sous naviateur c'est ok.
Soit le code est foireux, soit le site a bouge.

**Comment by johngf** [comment]
Hier et avant hier ça fonctionné bien strea may je maté une serie dessus et il n'y avait pas cloudflare

**Comment by TmpName** [comment]
La ce soir je decroche, mais demain je fais comme toi et je m'attaque a une verif complete, j'aurais plus de temps.

**Comment by noipo** [comment]
Ya kepliz (ozporo.com) qui est mort

**Comment by TmpName** [comment]
Bon alors plus de prb sur strmway (m'en doutait un peu)
Petite correction pr papystrm, mais j'ai l'impression qu'elle va pas servir longtemps.

**Comment by ttrd06** [comment]
pour voirfilm, la rech ne fonctionne pas. je pense qu'il y a peut etre du sucuri derriere.
j'ai regardé, ils ont changé l'url de post mais en changeant par la nouvelle ça marche pas non plus ...
@TmpName si tu peux regarder ?

**Comment by cestles** [comment]
je pense aussi que kaydo.ws peut être supprimé, ne fonctionne pas

**Comment by Kodigoal** [comment]
Kaydo fonctionne là.
robindesdroits k.o , ils recherchent un nouvel hebergeur.

**Comment by Muuan** [comment]
Salut. Je viens de tester pour Sokro, j'ai bien les dossiers/sous-dossiers pr accéder aux streams, mais un fois dans le dernier sous-dossier, pas de lien pour la vidéo.

**Comment by TmpName** [comment]
@johngf a deja lance une session de correction et voirflm en fait partie.
Sinon pr sokro moi j'ai pas de prbs, tu as teste quoi ? Tu vas peut etre avoir un prb pr les series, mais c'est parce que la modif a pas ete encore validee.

**Comment by Muuan** [comment]
Yop. C'était bien pour les séries le problème. Je viens de tester à nouveau, et tout semble être rentré dans l'ordre pour Sokro. Merci pour ce bon gros boulot!

**Comment by TmpName** [comment]
Tu passes par ou ?
Moi j'ai plus le nom de la serie, mais sion j'arrive jusqu'a la source sans prb.

**Comment by TmpName** [comment]
Edit: une nouvelle sucuri protection sur la recherche de sokro ^^  a base de captcha.

**Comment by Kodigoal** [comment]
L'effet trafic > revenus pub .. xD

**Comment by TmpName** [comment]
Lol, ben j'en sais rien , le site est totallement accessible, ca bloque juste la recherche, ca doit etre a cause des robot style celui de alluc.

**Comment by LordVenom** [comment]
Tu me dit si il faut pousser une grosse mise a jour.J'ai pas tout suivis mon ordi a encore lacher.

**Comment by TmpName** [comment]
Lol, pauvre bete, mais tu lui fais quoi pr le crever si souvent ?
Nope, que des modifs qui passent an MAJ auto, pas de soucis.

**Comment by LordVenom** [comment]
Rien de spéciale les multiples format n'ont pas réparer le DD j'ai fini par le changer.

**Comment by TmpName** [comment]
Pour sokro, il faut un cookie maintenant en plus de celui de cloudflare pr avoir la recherche, mais plus de cpatcha.
