### ISSUE TITLE
Kepliz (OZPORO.COM)

### ISSUE THREAD

**Issue by noipo** [Kodi-vStream/venom-xbmc-addons#987]
La source fonctionne bizzarement, on voit les films s'afficher mais quand on clique sur l'un d'eux, rien ne s'affiche ( on ne peut choisir la qualité et un flux)

**Comment by johngf** [comment]
ça fonctionne c'était peut etre temporaire et il n'y a pas de popup choix du flux la qualité et a coté du titre
