### ISSUE TITLE
Autoexec vStream - recherche visuelle

### ISSUE THREAD

**Issue by FEARZYAH** [Kodi-vStream/venom-xbmc-addons#988]
Bonjour,

J'essaie de faire en sorte qu'au démarrage de Kodi, l'extension vStream s'ouvre automatiquement sur la recherche visuelle.

Néanmoins j'ai un peu de peine avec le autoexec.py, j'ai réussi à faire ça mais c'est un peu du bricolage :

xbmc.executebuiltin("ActivateWindow(10025,plugin://plugin.video.vstream,return)")
import time
time.sleep(2)
xbmc.executebuiltin("Action(Down)")
xbmc.executebuiltin("Action(Down)")
xbmc.executebuiltin("Action(Select)")

Pouvez-vous m'aider svp? :)

S'il y a un moyen d'utiliser que la première ligne du code en mettant je ne sais quelle valeur pour tomber sur directement la recherche visuelle.

Car là je dois attendre 2 secondes et ne rien toucher pour tomber direct dedans.

Merci !!!

**Comment by LordVenom** [comment]
Pour afficher la recherche visuelle

plugin://plugin.video.vstream/function=load&sFav=load&site=themoviedb_org&siteUrl=http%3a%2f%2fvenom&title=Recherche%20visuelle']

Film popuplaire
plugin://plugin.video.vstream/function=showMovies&sFav=showMovies&site=themoviedb_org&siteUrl=movie%2fpopular&title=Films%20Populaires

Film en salle
plugin://plugin.video.vstream/function=showMovies&sFav=showMovies&site=themoviedb_org&siteUrl=movie%2fnow_playing&title=Films%20en%20salle

**Comment by johngf** [comment]
ou #657 mais au lieu de zone tel tu met le site the movie db mais bon en faisant ce genre de truc tu n'auras plus de maj je pense a moins de passé de temps en temps sur la page d'accueil

**Comment by FEARZYAH** [comment]
@LordVenom  Merci pour ta réponse, par contre quand j'entre ceci : 
xbmc.executebuiltin("ActivateWindow(10025,plugin://plugin.video.vstream/function=load&sFav=load&site=themoviedb_org&siteUrl=http%3a%2f%2fvenom&title=Recherche%20visuelle,return)")

Au démarrage de kodi, je tombe sur l'accueil de l'extension et non pas dans la recherche visuelle..

Ai-je fais une erreur?


@johngf  J'avais vu ce post mais je comprends pas grand chose au fonctionnement de l'url..  oui les mises à jour je vais les faire moi même mais c'est juste pour faciliter la vue pour un utilisateur final. Car je trouve quand même plus sexy de passer par la recherche visuelle :smiley:

**Comment by LordVenom** [comment]
oops 

plugin://plugin.video.vstream/?function= ext....

**Comment by LordVenom** [comment]
#toutes la recherche visuelle
`xbmc.executebuiltin("ActivateWindow(10025,plugin://plugin.video.vstream/?function=load&sFav=load&site=themoviedb_org&siteUrl=http%3a%2f%2fvenom&title=Recherche%20visuelle,return)")`

#Recherche visuelle Films populaire
`xbmc.executebuiltin("ActivateWindow(10025,plugin://plugin.video.vstream/?function=showMovies&sFav=showMovies&site=themoviedb_org&siteUrl=movie%2fpopular&title=Films%20Populaires,return)")`

#Recherche visuelle Series populaire
`xbmc.executebuiltin("ActivateWindow(10025,plugin://plugin.video.vstream/?function=showSeries&sFav=showSeries&site=themoviedb_org&siteUrl=tv%2fpopular&title=S%c3%a9ries%20Populaires,return)")`

**Comment by FEARZYAH** [comment]
@LordVenom  Top merci beaucoup!! :+1:
