### ISSUE TITLE
travail sur les titres

### ISSUE THREAD

**Issue by LordVenom** [Kodi-vStream/venom-xbmc-addons#993]
Bon je vais abondonner le multi titre personne ne s'en serv et ça vas compliquer par contre j'ai commencer un code dans guielement pour remplacer decotitle pk?

- La possibiliter d'ajouter l'info au theme via self.addItemValues('Season', self.__Season)
- La possibiliter de traiter tous les titres dans le coeur de vstream
- Armoniser l'affichage et possibiliter de modifier les couleurs.

Par contre je suis mauvais en regex et il faut donc un code pour l'année du film, pour les HD SD 1080 plutôt une recherche dans une liste prédéfinie pareil pour la langue et un code pour tous ceux qui et entre () et qui n'entre pas dans les recherches ulterieur.

**Comment by TmpName** [comment]
Des regex qui font ca, y en a un peu partout (trakt, utils, ...), je peux m'en occuper, mais tu veux le traitement dans quelle fonction/fichier ?

**Comment by LordVenom** [comment]
Fonction getDeco dans guielement j'ai commencer mais j'aime pas la ligne

 `sTitle = re.sub('([\(|\[](?![0-9]{4}).{1,7}[\]|\)])',' [COLOR '+self.__sDecoColor+']\\1[/COLOR] ', sTitle)`

Il faudrais faire une recherche depuis une liste qui vas chercher VF|VOSTR que l'on puisse retravailler par exemple si je trouve French ou True French je peux retourner VF pareil pour 1080p ou 1080i je retourne que 1080.

bref le system reste le même si la liste et modifiable facilement et donc tous ceux qui et entre () ou [] qui n'entre pas dans ces liste purement et simplement supprimer.

**Comment by TmpName** [comment]
La tu t'emmbarque dans la meme galere que addonmaster pour exodus.
C'est a gerer quand tu fais le fichier site ca, trop aleatoire a gerer pr le coeur. Et il risque d'y avoir des trucs utiles qui vont disparaitre.

Je vais commencer ce soir, et je vais deja faire quelque chose pr assurer la compatibilite avec les vielles et future version. (Si [color] dans le titre = vielle version > on touche pas)

**Comment by LordVenom** [comment]
Le soucis c'est qu'il y a en as partout et qu'il ne sont pas utilisable pour le coeur le site fait le tris et le coeur aussi pour retirer les infos meta et Skin donc faut y faire le menage mais oui faut faire ça progressivement et voir ceux qu'il pourrais manque ou pas.

**Comment by TmpName** [comment]
Ben pour les infos, et l'affichage, je comprend l'importance des saisons ou années, mais la langue, bof, surtout que le resulat est pas garantis sur tout les sites.
Pour moi c'est au fichier site de faire le premier formatae, qui va dependre du site pr avoir un truc a peu pres standard que le coeur de Vstream va pouvoir gerer.

Je vais te bidouille le code pour que par defaut le site fasse le tris (comme avant) , et si on vire la fonction decotitle du fichier site, ce soit le coeur, comme ca, 100% compatible et un seul tri.
Bon c'est en theorie, je commence juste, et j'ai juste l'idee.

**Comment by LordVenom** [comment]
La lange la qualiter tout peux passer dans le skin enfin tout y a plusieurs niveau d'autre seront utilisable uniquement dans gui mais ça c'est pour plutart.Le site ne fait pas le tris puisque c'est decotitre dans la plupart des cas.j'ai fait une function pour envoyer une deco sans touche au tris mais tous passe par decotitre si javais pus j'aurais juste coller la function mais c'est en sub et j'ai besoin des infos année saison ext.. pour les utilisers.

**Comment by TmpName** [comment]
Je viens de mettre un truc en ligne.
- compatible avec anciens et futurs fichier sites.
- colore automatiquement
- recupere les infos

Pour t'en servir, prends le site "voirflm.py" et vire tout les decotitle (> sDisplayTitle = sMovieTitle), et relance le.

**Comment by TmpName** [comment]
Pour la qualite y a deja une icone qui se rajoute automatiquement.
La langue c'est pas fiable.

Pour moi ca suffit, tout les tags restant sont en couleurs mais sans recuperer les infos.

**Comment by LordVenom** [comment]
Pk ne pas avoir l'aisser 

```
    def DecoTitle(self, string):
return string
```

ca permet d'utiliser direct la fonction sans modifier le site.

**Comment by TmpName** [comment]
Si je le laisse, les gens qui auront le nouveau coeur mais les vieux fichier site n'auront pas les couleurs.

**Comment by LordVenom** [comment]
Nonn lol les sites ne change pas et le coeur ne seras mise a jour que a la fin du mois

**Comment by LordVenom** [comment]
![capture d ecran de 2017-03-11 19-38-40](https://cloud.githubusercontent.com/assets/4380112/23825865/63adb404-0692-11e7-8819-3717d2fbf5b2.png)

Tous les () devrais etre colorier c'est juste chez moi ?

**Comment by TmpName** [comment]
Arf, je viens aussi de voir que ca colore aussi les menus de Vstream.
Pour la coloration c'est normal dans le regex il y a une limite (min 1 caractere, max 12). Car pour moi plus de 12 caracteres, c'est plus un tag mais une infos complete.

2 Solutions.
- on vire ma limite, mais ca va colorer aussi les menus (et sa risque de faire des trucs sur le skin la ou il n'y en a pas besoin)
- on trouve on moyen pour que cela ne s'active que sur les sites.

**Comment by TmpName** [comment]
Par contre chez moi la couleur par defaut c'est rose, pas orange ??

**Comment by LordVenom** [comment]
Non mais c était pas voulus mais j aime bien moi et vue que la couleur et paramétrable pas grave sur n importe quel skin.oui j ai mis orange dans les param

**Comment by TmpName** [comment]
Ben perso je prefere le orange justement ^^. C'est pour ca que je me posais la question si meme le mec qui avait choisit le rose utilisait le orange ...

**Comment by LordVenom** [comment]
Hum par default j'ai mis plum prune selon le traducteur mais j'ai pas vraiment fait attention je reglerai sur orange par default promis! ou rose bonbon ou jaune caniris ? lol

**Comment by TmpName** [comment]
Y a pas "taupe" ? C'est la couleur a la mode ici.

**Comment by TmpName** [comment]
Ha ?
Moi je faisais un reformatage SXXEXX titre [tag] (annee), donc oui c'est possible, ca a du deconner.

**Comment by johngf** [comment]
Oui c'est mieux sxxexx titre etc....
Sur le new theme de kodi avec un long titre( mode liste) on ne verra pas sxxexx avant la fin du defilement

**Comment by TmpName** [comment]
Yep ^^, c'est exactement mon probleme (et sur l'ancien skin), et j'ai le prb sur les hosters qui sont tjours affiche a la fin.

Sinon a valider par le boss.
Pour empecher le traitement de se faire n'importe ou (uniquement sur les titres de films et series), je propose d'utiliser self.__sCat ou self.__sMeta.
Probleme il va falloir changer l'ordre
```
        oGuiElement = cGuiElement()
        oGuiElement.setSiteName(sId)
        oGuiElement.setFunction(sFunction)
        oGuiElement.setTitle(sLabel)
        oGuiElement.setIcon(sIcon)
        oGuiElement.setThumbnail(sThumbnail)
        oGuiElement.setMeta(2)
        oGuiElement.setDescription(sDesc)
        oGuiElement.setTvFanart()
        oGuiElement.setCat(2)
```

oGuiElement.setTitle(sLabel) DOIT etre apres, quitte a mettre un message d'erreur si c'est pas le cas pour les futurs codeurs.

**Comment by johngf** [comment]
Pour la couleur ça aurait pas était plus simple un config().get setting color dans les fichiers site ?

**Comment by TmpName** [comment]
Ben c'etait comme ca avant (avec decotitle() ) mais en fait avec cette methode en meme temps qu'on decortique le titre on peut extraire les saisons/episode et colorer en meme temps.
La couleur c'est pas un prb, mais les saisons/epiosode/anne et ect ne sont gere que par le fichier guielement

**Comment by LordVenom** [comment]
Aucune importance oui si S01 et avant le titre ou pas temps qu'il et partout au même endroit Pour les site c'est asser simple si tu met un texte entre [] ou () il seras coloriser automatiquement plus de couleur dans les sites.

**Comment by LordVenom** [comment]
Pour le Hoster il vas cherche quand même avec if sitename == cHosterGui
Si les info du site ne sont pas utilile c'est pas au coeur de le trier mais au site beaucoup supprime "streaming" a voir ect.. J'ai corriger un bug d'un affichage bizarre des Hosters du moins sur Kodi 17.

Perso c'est quand j'active l'unicode qu'il n'arrive pas a lire les accents.Je sais plus le nom du site je surf pas mal pour voir un peux tout les affichages.

**Comment by johngf** [comment]
le site que je viens de mettre sur la beta documovies a plein de tag entre parentheses ou demi parenthese
nom de personne, numero, etc...
a test sur ce site le nouveaux systeme de deco

**Comment by LordVenom** [comment]
Bon reste 1 soucis il me retourne 

` [COLOR lightgreen]S06E09[/COLOR] The Waling Dead - [COLOR lightgreen][VOSTFR] - (15/02/2016)[/COLOR]`

ça serais pas plus normal de Fermer [/COLOR] a chaque foix ?

**Comment by TmpName** [comment]
Tu preferes 
`[COLOR lightgreen]S06E09[/COLOR] The Waling Dead - [COLOR lightgreen][VOSTFR][/COLOR] -[COLOR lightgreen] (15/02/2016)[/COLOR]`

Moi non, je trouve que ca rallonge le titre pr rien.

Sinon tu as pas repondu pour que le traitement se fasse unqiuement pour les titres de film/serie, et pas les menus. En utilisant self.__sCat ?

**Comment by LordVenom** [comment]
Non c'est bon j'ai rien dit il suffis de passer en mode radin .+?

**Comment by TmpName** [comment]
Lol.
Moi j'aime pas car incontrolable, ca colore n'importe quoi.

**Comment by LordVenom** [comment]
![capture d ecran de 2017-03-14 17-42-14](https://cloud.githubusercontent.com/assets/4380112/23911602/9caddab6-08dd-11e7-8591-2cfb517e7008.png)

Ben ça rend bien (surtout en rose) lol

**Comment by TmpName** [comment]
Ben recherche visuelle, ca colore automatiquement S01(18) S02(18)
Et ca lance aussi les calcul regex sur tout les menus.

**Comment by TmpName** [comment]
C'est plus leger, tu connais le titre vu que tu l 'as selectionne 5 mn avant. C'est l'enfer les titres trop long, surtout avec leur nouveau theme a la con.

**Comment by TmpName** [comment]
Bon now, le code peut gerer quelques couleurs, eg celle qu'on met pour les hosters.
Ou certains site qui mettent Titre du film > Hoster (avec hoster en couleur)

Donc on peut utiliser des couleurs, qui resteront mais ne JAMAIS metre en crochet ou parethses.
eg 
`Titre [COLOR red]> Ne marche pas [COLOR]`
C'est bon, mais pas
`Titre [COLOR red][ Ne marche pas ][COLOR]`

Car Vstream va laisser la precedente couleur et rajouter la sienne entre, donc ca bugguera pas, mais ca sert plus a rien.

**Comment by LordVenom** [comment]
J'ai rien compris si y a [COLOR la fonction n'est pas utiliser j'ai du modifier themoviedb pour virer les couleurs et que la fonction travail

`if not sTitle.startswith('[COLOR'):`

Alors a quoi serv la fonction 

`sTitle = re.sub('([\(|\[](?!\/*COLOR).+?[\]|\)])','[COLOR '+self.__sDecoColor+']\\1[/COLOR]', sTitle)`

enfin surtout le [COLOR]

**Comment by TmpName** [comment]
La premiere modif.
Certaines personnes affichent une ligne pour des commentaires en couleurs par exemples "pas de sources dispnible" ou "VOSTFR" ou "Voir les marques pages" ou "Votre historique" ou meme parfois le titre du film pour ne pas l'afficher dans les liens. Et dans ce cas pas de traitement, car le '[color' est toujours en debut de titre (vu qu'ils colorent tout le titre).

Et la seconde colore toujours les tags sauf quand c'est un tag de couleur, et oui car le [color = red] vu que c'est entre crochet est considere comme un tag aussi.
Avec cette modif par exemple dans la listes des hoster, on peut toujours colorer le nom du hoster en bleu (pr les stream) et rose (pour les ddl) ou dans certains site ou le hoster est affiche avant la page des hosters (car le site demande un decodage) et que le dev le met en couleur pour le refaire sortir.
En resume ca laisse Vstream colorer lui les titres, tout en gardant la possibilitee de colorer en plus.

**Comment by johngf** [comment]
quand il y a saison3&4 le &4 se retouve en dehors a la fin vu sur gumgum > vostfr
ou saison 1 a 11 pareil a 11 en dehors

quand la liste est longue a colorer ça ralentit comme meme l'affichage (sur les rapsberry ou autres petite machine faudrait voir)

et en faite meme quand on utilise decotitle le nouvelle methode modifie le titre comme meme

**Comment by TmpName** [comment]
Ha ?
C'est bizarre car @LordVenom a desactive la fonction (si tu as le fichier util.py a jour)
```
def DecoTitle(self, string):
    return string
```

Donc normallment elle ne doit rien changer. Par contre si tu met un truc en couleur en fin de titre (si tu le met toi meme via le fichier site, sans utiliser de [] ou de () ), ta couleur devrais rester. Par contre Vstream reformatera le titre pour les saisons/episode/date, le reste ne chnage pas (sauf si bug)

Apres pr le temps de calcul, c'est a optimiser, mais pour le moment il doit juste y avoir 1 ou 2 regex max en plus que l'ancienne fonction Detcotitle(). Ceci dit j'ai aussi une impression de ralentissement mais qui doit venir d'ailleurs, j'ai essaye de desactiver la fonction pour tester, pas vu de grosse difference.

Pour le prb je vais voir mais on a vire pas mal de truc du regex (comme les "-")donc ca vient surement de la.

**Comment by LordVenom** [comment]
Je me tate pour mettre une couleur a aDdText ça evite que les couleurs d'information change a chaque site.

**Comment by TmpName** [comment]
Nope, moi je mettrais pas car si par exemple tu veux afficher (comme sur l'ancien ZT)
```
Titre du film
Note du film : 7
VF
Lien 1
Lien 2
VOSTR
Lien 3
Lien 4
Petit commentaire
```

Tu risque de vouloir toi meme plusieurs couleurs (et pas le rouge qui est generallement choisit), et a chaque fois tu vas utiliser AddText(), bon la evidement c'est un cas extreme ^^, mais je trouve plus sympa de laisser au dev le choix de ses couleurs.

**Comment by LordVenom** [comment]
ok

**Comment by TmpName** [comment]
Par contre,  j'ai de gros prbs pr gumgum, grosses modifs et j'ai pas fini.

**Comment by LordVenom** [comment]
Ha mince c'est la merde ? si le regec devient trop compliquer fait un truc genre tous ceux qui et dans () colorer mais pas traiter et ont choperas que les saison qui sont en "espace"Saison"espace" non ?

**Comment by TmpName** [comment]
Ha oui pas betes, pr les sites tordus, faire le traitement des couleurs via les parentheses.
A voir la limite.

**Comment by LordVenom** [comment]
ou tu taite les saison et episode en () et espace espace mais pas en [] et tu transforme les () de gum gum en []

**Comment by johngf** [comment]
Je pense que des soucis il y en auras aussi sur d'autre site pas encore remarqué c'est tout
bcp ne formate pas de maniere reguliere

**Comment by TmpName** [comment]
Yep streamingk aussi de memoire a l'epoque.
Faut trouver un compromis, je peux corriger le regex pr traiter 1-10 sans trop alourdir les calculs (ca peut etre utile, et donne quelques possibilitees) mais pas plus. Apres soit on reformate via le fichier site, soit on fait comme dit @LordVenom et tant pis pr le traitement.

Y a aussi les "-" qui m'ont pose probleme, si on les vire dans le titre ca manque, mais y a gave de site qui se retrouvent avec des "-" qui servent plus.

La c'est apero time, demain je regarde si je peux alleger le regex et mieux gerer le "-" entre les chiffres. Me faut tester des trucs comme  [0-9]+(?:\-[0-9]+)

**Comment by LordVenom** [comment]
le skin si tu le envoie 05-06 il ne prend que 05.

**Comment by LordVenom** [comment]
Mine de rien grace a ça j'ai trouver un gros bug dans le fichier tmdb si il y avais la date il retourner aucune information même si il la trouver sur tmdb. Bref c'est corriger maintenant ont gagne vraiment une requette si il y a la date :)

**Comment by LordVenom** [comment]
Y a des - qui ce balade tous seul vue sur Zonetelechargement.ws 

D'ailleur à propos il me semble que j'en ai deja supprimer mais y en a encore les infos style (qualiter disponible pour ce films) c'est vraiment utile ? ecrit en dur dans le code et je vous parle pas de la tête que ça a en mode miniature.

**Comment by johngf** [comment]
sur alluc recherche nowvideo
affiche du titre tel quel Watch-WaDe704-online-NowVideo
showhoster qui utilise le meme titre
e704- Watch-WaDonline-NowVideo
ou
le titre xxx-VoirFilms-org-1763-vf-Dvdrip-xvid
vstream colore 1763 comme ci c'était une année

**Comment by TmpName** [comment]
Pour le premier, on peut faire quelque chose : [^| ]
Pour le second par contre ....
Vu le bordel des titres alluc, c'est pas mieux de desactiver le traitement pour lui ?

**Comment by LordVenom** [comment]
Vue dans Kaydo series Ep 1 :

**Comment by TmpName** [comment]
Pas encore trouve d'exemple sur otaku pr tester.
Corrige directement dans fichier site pour kaydo.
Pour alluc, par trouve comment faire un truc propre, juste supprimer les "-" depuis le site ? ca va etre moche mais dans tout les cas, les titre de fichier alluc ....

**Comment by johngf** [comment]
donc en faite pour evité des décos aléatoire sur certain site il faut passer par le mode liste

**Comment by TmpName** [comment]
Ha ?
Le mode de vue chnage quelque chose ?

**Comment by johngf** [comment]
Mode liste n'active pas traitetitre donc tu peux gerer tous via le fichier site title=[x,a,c]

**Comment by TmpName** [comment]
Ha oui, bne idee, reste a savoir si @LordVenom a pas prevu de faire sauter partie now.

**Comment by LordVenom** [comment]
Le mode liste ne change rien au mode icon ou fanart a pars la place utiliser par le texte et la taille de l'image.De plus addDir et limiter a 2 option liste ou icon et le addmovie addtv a 4 ou 5 mode je sais plus.Je voie pas ce que ça apporterais de modifier le texte suivant l'affichage.

**Comment by johngf** [comment]
certain titre avant showhoster mais avec le nom de l'hebergeur ne sont plus colorés vu que decotitle est désactivé et que les titres non pas de () ou [ ]

**Comment by LordVenom** [comment]
Perso je suis partis la dessus

sTitle = ('%s [%s] (%s) [COLOR coral]%s[/COLOR]') % (sTitle, sQual, sLang.upper() , sHoster)

**Comment by TmpName** [comment]
Oui et non, la coloration en rose ou bleu se fait toute seule.
Mais oui certains site affiche l'hebergeur via le fichier site donc brut, et c'est quand meme plus visible en couleurs, mais c'est faisable via le fichier site (cf filmstrmvk)

**Comment by LordVenom** [comment]
Oui mais c'est pour savoir vos préférence juste soit 

sTitle = ('%s [%s] (%s) (%s)) % (sTitle, sQual, sLang.upper() , sHoster)

Soit 

sTitle = ('%s [%s] (%s) [COLOR coral]%s[/COLOR]) % (sTitle, sQual, sLang.upper() , sHoster)

bon sur certain site ca vas pas être possible mais sur la plupart oui.

**Comment by TmpName** [comment]
Te prend pas la tete, y a peu de site qui s'en servent, on mettra la couleur dans le fichier site vu quelles sont conservé ou alors on mettra le nom entre crochet ou parentheses.
Faut que la fonction de traitement soit la plus legere possible.

**Comment by LordVenom** [comment]
Je parlais du site justement.

**Comment by TmpName** [comment]
Ha, alors 2 eme solution pr moi, j'aime bien avoir les hosters d'une autre couleur.

**Comment by johngf** [comment]
je viens de voir sur kaydo serie sense8 se transforme en e08

**Comment by LordVenom** [comment]
`(?i)(\W[e|é|É](?:[a-z]+sode\s?)*([0-9]+[0-9\-\?]*)\W)` ?

**Comment by TmpName** [comment]
Ben j'ai mis un truc en test, plus simple, ca fait juste gaffe a ce qu'il n'y ai aucune lettre avant le 'e' mais le '_' est considere comme une lettre, donc a voir si on tombe sur ce cas.

**Comment by johngf** [comment]
Kodi 16 Je ne sais pas si c'est la cause mais lorqu'on navigue saison episode hoster 
Puis on retourne en arriere ça recharge souvent

**Comment by TmpName** [comment]
Ha ca j'ai pas encore vu, mais d'apres le code de kodi c'est une histoire de temps de chargement, ca utilise le cache si le temps de chargement depasse une certaine valeur.

**Comment by johngf** [comment]
La recherche visuelle de serie recherche avec des titre mode sxxexx rarement sur les sites vu qu'on les transforme en sxxexx donc rarement de résultat

**Comment by TmpName** [comment]
Ha oui, j'ai pas pense a ca. En fait si on recherche "Strain S01E07" on a moins de resultats que avec "Strain" ?
Si c'est ca, suffit de virer le SXXEXX ?
A l'origine de memoire y avait une fonction qui nettoye le nom avant la recherche (elle virait les article aussi)  je crois qu'elle a saute lors de la creation de globalsearch.

**Comment by johngf** [comment]
Et aussi recherche visuelle series populaire tu clic sur une serie saison episode il devrait etre ecrit saison1 episode 1 pas 》 s1 e1 episode 1

**Comment by johngf** [comment]
Je ne pense que c'est histoire de nettoyage mais a caus du titre en sxxexx qui est utilisé et non pas
Saison 1 episode 1

**Comment by LordVenom** [comment]
Vérifier encore j ai fait une modif un lien cliquable pour chercher série ou saison uniquement

**Comment by johngf** [comment]
Je testerai mais ce que je veux dire c'est si on clic sur un episode avant on avait comme resultat des saisons des episodes etc..maintenant quasi rien a cause de sxxexx

**Comment by TmpName** [comment]
Ben avant ca virait saison et episode pr ne faire la recherche que sur le titre.

**Comment by johngf** [comment]
@TmpName la derniere fois tu cherchais un episode genre 6.5 
[ici](http://www.filmsvostfr.cc/anime-youjo-senki.html)

**Comment by LordVenom** [comment]
Les liens S01Ep01 sont plus a utiliser avec alluc les sites n'aime pas trop d'ou les nouvelles recherche série complete et saison complete.

**Comment by johngf** [comment]
Ça fonctionne aussi a partir de serie populaire ? Ça recherche la ou les saisons au lieu de l'episode ?
Qui n'aura quasi aucun resultat avec sxxexx

**Comment by LordVenom** [comment]
Ben le soucis c'est que ceratin site vont préférer S12 d'autre saison 12 avec toutes les source c'est difficile de plaire a tous le monde lol

**Comment by TmpName** [comment]
Pour moi c'est simple, on vire tout ce qui gene pour les recherches, pas besoin de remettre tout le code precedent, mais faut virer saisons et episode (surtout que la plupart des sites ne le gere meme pas). Il faut aussi virer tout les tags.

J'ai corrige le ep6.5 mais j'ai pas eu le bug pour 19-2, normallement le dernier regex ne marche que si il n'y a aucun caractere avant le "e".

**Comment by johngf** [comment]
Oui en faite on n'a plus de resultat quand on recherche uniquement le titre de la serie 
Sur episode ou saison quasi rien a cause du format utilisé

**Comment by johngf** [comment]
et c'est pareil pour la recherche de meta sur episode ou saison

**Comment by TmpName** [comment]
A ca y est me souvient pourquoi je virais les '-', mais now on sait que ca peut faire deconner pour certaine recherche. Le virer si encadre par 2 espaces ?, si c'est dans un titre il est colle aux mot ?

Enfin bon pr moi faut remettre la partie nettoyage qu'il y avait avant.

**Comment by TmpName** [comment]
J'ai corrige pr la recherche, mais pr les metas ....
On recupere 'sMovieTitle'
On l'envois dans self.__sFileName
Et c'est lui qui est utilise pr les metas

C'est con car durant TraiteTitre on pourrait extraire le nom "propre", sinon faut remettre un nettoyage de nom.

**Comment by LordVenom** [comment]
C'est prevus mais pas tout de suite quand ça seras stable et il faut encore un codage derriere il me semble que __filename et utiliser pour la base de donnée donc pas d'accent pas de maj et aucun [][]()

**Comment by LordVenom** [comment]
https://github.com/Kodi-vStream/venom-xbmc-addons/projects/2#card-2225748

Une boucle a tester mais un code decode devrais le faire j'ai juste pas trouver le bon.

**Comment by johngf** [comment]
Si tu parle de la boucle que j'ai mis ce matin j'ai essayé plusieurs decode
Le soucis c'est que \xC3 ce transforme en 0xC3 donc le decode ne fonctionne pas ignore replace non plus

**Comment by LordVenom** [comment]
Marche pas la boucle elle supprime les accents autant passer par un unicodata qui lui transforme les é en e mais j'attend de voir ce que @TmpName en pense.

**Comment by TmpName** [comment]
C'est la fonction dont je me sers aussi, cf themoviedb_org.py lgn 595. Radical.

**Comment by johngf** [comment]
@TmpName en faite lafonction qui recup le é e  d'episode une fois recup rajoute un xc3 >é a la fin du titre

**Comment by TmpName** [comment]
Ha ? alors ca vient peut etre du fait que le regex n'est plus unicode mais ton titre le serait encore, je pense qu'il y a moyen de passer ca en convertissant les titres directement dans le fichier site.

**Comment by LordVenom** [comment]
Il me dit que le titre et en str

**Comment by johngf** [comment]
Le titre n'a pas l'air de l'etre juste é majuscule

**Comment by LordVenom** [comment]
Il aime pas les [] tester avec 

`(?i)(?:^|[^a-z])((?:e|é|É)(?:[a-z]+sode\s?)*([0-9]+(?:[\-\.][0-9\?]+)*))`

**Comment by TmpName** [comment]
Ha yep ca marche aussi avec ta methode ^^, J'avais pas pense a ca.
Reste plus qu'a tester les deux et choisir. Moi j'ai fais au plus simple.

Sinon je croyais que la fonction marquer vu/non vu avait disparu du code de vstream pr utiliser la fonction de base se kodi (en appuyant sur "w") qui elle ne buggue pas.
Par exemple dans le code du player, elle a ete desactivee, mais pas dans le menu apparement.

**Comment by TmpName** [comment]
Ben y a la menu deroulant de gauche aussi. Et on peut aussi garder le menu mais utiliser l'api de kodi pour marquer en vu/non vu.
En fait il y a un conflit entre les 2 methodes qui peut provoquer des bugs, y a une issue la dessus.

**Comment by johngf** [comment]
Quand je marque vu via le menu gauche ça fait rien du tout

**Comment by LordVenom** [comment]
Le menu de gauche ? la c'est bugguer avec le nouveau system CONTENT = 'addons' ont peux plus marquer lue les hosts mais toujours les dossiers perso c'est toujours ça que je marque lus

**Comment by johngf** [comment]
Puis le menu gauche c'est pour masquer pas marquer

**Comment by TmpName** [comment]
Ha oui, autant pr moi, j'ai hallucine ou ils ont vire cette option ?

**Comment by LordVenom** [comment]
lol bne j'avais pas penser au replace é par e lol c'est quoi le plus rapide le replace surement non ?

**Comment by LordVenom** [comment]
Bon j'ai encode('utf-8') favorite ligne 107 les accent bugguer les marques pages pas certain que ce soit compatible avec les ancien marque page dans le doute j'ai try: except: mais j'ai pas pus tester

**Comment by johngf** [comment]
pour la modif [ici](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/d6349d577e61aefd47243fcf369743d7cc903a8e/plugin.video.vstream/resources/lib/gui/hoster.py#L62) il doit avoir un bug quelque part parce que c'est vstream qui le rajoute sur krypton pas kodi

**Comment by TmpName** [comment]
Bon retour de prb unicode.
Avec la bidouille des replaces ca fait deconner la recherche.

Donc soit on decide d'un format et on en bouge plus, soit on vire tout les accent direct, moi ca me saoule, ca sert a rien et c'est que des emmerde en informatique.

**Comment by LordVenom** [comment]
Pareil je suis gonfler la avant ça passer un str tu encode en unicode tu travailler dessus puis tu repasser en str. La ont reste tout le temp en str et ça merde...

**Comment by LordVenom** [comment]
Alors voila tu peux pas decode('utf-8') au debut de la fonction ça plante les accents
mais tu peux sTitle = unicode(sTitle,'utf-8') resultat un unicode qui passe bien
Apres tu peux remettre la re.search en re.UNICODE ça passe.

et au final faut repasse en str sinon l'addon plante
sTitle2 = sTitle.encode('utf-8')

**Comment by LordVenom** [comment]
ok un 

```
        try:
            sTitle = unicode(sTitle,'utf-8')
        except:
            pass
```

Au debut de code resouds les sites qui eux retourne un unicode par contre le regex et foireux quand il lit S05E04 il retourne E05E04

**Comment by LordVenom** [comment]
`(?i)(?:^|[^a-z])((?:e|\xe9|\xc9)(?:[\w]+sode\s?)*([0-9]+(?:[\-\.][0-9\?]+)*))`

fonctionne mais il l'aisse des ( ) tester sur Alaska : La ruée vers l'or (E07S15)

**Comment by LordVenom** [comment]
Ont remet decotitre et ont pense a autre chose pour regler tous ça la ça pars en live.

**Comment by TmpName** [comment]
J'avais corrige le prb pr le prb sur alaska, mais tu as vire ma modif.

Sinon je vais faire un dernier test, avec l'ancien code (celui de decotitle)

**Comment by TmpName** [comment]
Alors, nouvelle version a tester, merci de ne pas changer le codage dedans, pkoi ?
Si le titre est en utf-8 elle le passe en unicode
Si le titre est en unicode, elle n'y fera rien.
Si le titre en en "latin-1" ou "iso-8859-1", message d'erreur, mais ce n'est pas la faute a cette fonction, elle ne peut pas gerer tout les codage, si ca plante, il faut modifier le titre dans le fichier site.

La fonction est unicode car plus facile a gerer pour les accents.

Elle renvois un titre en ut-8 car c'est un standard, normallement compatible a 100% avec le reste de Vstream, pour pouvoir faire if titre == str

Pas vu de prb pr la serie 100
Pas trouve le cas ou les episode sont du type Serie abcd episode 7 à 10 (et je sais que ca existe, mais plus ou)
Pas trouve un titre avec épisode en majuscule pr tester, mais ca devrait passer.
Fonctionne sur mangacity. (ps : ce site est en "iso-8859-1" par exemple)

Pas encore vu de bug, mais loin d'avoir tout teste, et j'ai pas tout les fichiers de la beta (j'ai quelques vieux fichiers)

**Comment by johngf** [comment]
Mega stream serie é maj

**Comment by TmpName** [comment]
Xd, leur serveur est down ^^, tu aurais pas un autre exemple ?

**Comment by johngf** [comment]
Non pas cherché mais au final ça revient au meme que de traité les titres depuis le fichiers sites des le depart et las dans guielement

**Comment by TmpName** [comment]
Yep, mais la fonction TraiteTitre a besoin d'un standard, sinon tout le monde va y passer n'importe quoi, et j'ai pas envie de me battre avec les unicodes. Apres la convertion de codage n'est pas la partie la plus importante de la fonction.
La au moins c'est regle, elle prend utf-8 ou unicode sinon erreur, et on est sur a 100% que le prb ne viens pas de elle (sauf si me suis rate, mais je pense etre bon). Et en sortie que du utf-8.

Elle devrait marcher avec 80% des sites directements, mais dans le cas contraire on touche au fichier site uniquement.

Apres si on converti les titre en unicode suis pas sur que le reste de Vstream le gere, le mieux etant l'utf-8

**Comment by johngf** [comment]
Ce matin je cherché comment afficher un drapeau langue ou tag un peu comme l'image 1080p sur du 1080p mais il y a pas moyen a cause du theme je pense qui n'a pas les images ou ne gere pas
Pour evité de taggué les titres et avoir des titres propres

**Comment by LordVenom** [comment]
.addStreamInfo('audio', {'codec': 'dts', 'language': 'en', 'channels': 2})

Mais le skin n'affiche pas la langue dsl juste les codex et les channels

**Comment by LordVenom** [comment]
Il reste des sites avec des - egarer

**Comment by johngf** [comment]
Oui j'ai testé 
Et bcp de sites on des - egarer

**Comment by TmpName** [comment]
Yep mais la je sais pas trop si il vaut mieux nettoyer cote site ou cote traitetitre ? J'ai peur de virer des "-" utiles dans le titre.

**Comment by johngf** [comment]
Il sont souvet a la fin du titre

**Comment by LordVenom** [comment]
Je suis perplexe y a que moi qui aime que ce soit carrer.Franchement pk pas parser les titres mais site par sites en espérant que les site garde le même affichage d'un titre a l'autre lol.je vais faire des tests en off.

**Comment by LordVenom** [comment]
Virer double - - et les derniers - qui traîner pas vue de soucis pour le moment.

**Comment by johngf** [comment]
Est ce quelqu'un a deja eu ça des titres dans du json avec caractere mélangé unicode utf8 ou latin
Genre \xc9 \\00293 
Si on encode en utf8 certain sont ok d'autre ont des caracteres utf8 encodé en latin avec symbole comme le symbole r entouré GalillÃ©
Une soluce pour le passé ?

**Comment by TmpName** [comment]
Oui, je pense deja avoir eu ca, y a une commande  .decode('string-escape') qui peut t'etre utile, mais ca depend de beacoup de chose. Tu aurais pas le site en question ?

**Comment by johngf** [comment]
c'est un site que je suis entrain de faire mais du coup j'étais passé par replace pour faire le job
mais depuis je récupère le titre ailleurs 
dans le json je prend que l'url final
